### ISSUE TITLE
Component is not clickable after trying to remove a team member

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10004]
### Issue Summary

In Teams, after trying to remove a member, the button component is not clickable anymore. After refreshing the page it is back to normal.

### Steps to Reproduce

1. Create a team
2. Add a few members to that team
3. Click on the three dots button
4. Click on the `Remove` option
5. Click on the `Yes, remove member` or `Cancel` button just to close the modal window
6. Note that the three dots button is not clickable

### Actual Results

- Three dots button is not clickable after trying to remove a member

### Expected Results

- After the removing confirmation modal window closes, the three dots button should be clickable

### Technical details

- Tested on Chrome (114.0.5735.134)

### Evidence

https://www.loom.com/share/e85e147cc63e4f08b32bc5c54d20598b

**Comment by CarinaWolli** [comment]
Can't reproduce it anymore, looks like this already got fixed
