### ISSUE TITLE
Members in pending status should be accepted automatically after an Organization is verified

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10005]
### Is your proposal related to a problem?

Currently, if an unverified Organization has members not confirmed yet (Pending status), after the acceptance, its members from the same Organization are still in Pending status.

### Describe the solution you'd like

All members from the same Organization (slug) should be accepted automatically.

### Describe alternatives you've considered

It could be configurable with a toggle in the admin settings.

**Comment by shirazdole** [comment]
Yes, once an organization is confirmed their members with the same domain should be autoaccepted
