### ISSUE TITLE
[CAL-2126] New Booker: Sync month/week/column view with URL

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#10000]
Currently the selected view is only saved in a local state. Meaning that a refresh or browser back/forward button won't have any effect. We should use the URL as the main source of truth. Also this will allow to share a link with a pre-selected view.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2126](https://linear.app/calcom/issue/CAL-2126/new-booker-sync-monthweekcolumn-view-with-url)</sub>

**Comment by iamanishroy** [comment]
@zomars, 
I'm interested in working on this issue. Could you kindly assign it to me?

**Comment by nish9142** [comment]
@zomars 
I’m interested too. Can you assign this to me?

**Comment by nish9142** [comment]
@zomars 
The URL already has the state ...https://cal.com/satya-nishanth-fw5qyl/15min?date=2023-07-11&slot=2023-07-11T04%3A15%3A00.000Z ?

**Comment by nish9142** [comment]
@zomars 
The main branch doesn’t contain the toggle button of month/week/column in booker section

**Comment by rene-mueller** [comment]
@nish9142 that's not true it's in `/new-booker/` folder. Additionally, there is an internal redirect in `next.config.js`.
The old booker will be removed in https://github.com/calcom/cal.com/pull/10053

**Comment by Pushpajit** [comment]
@zomars 
I'm interested can you please assign me

**Comment by nish9142** [comment]
@zomars 
can you please review this?
