### ISSUE TITLE
Allow drag and drop to rearrange event types

### ISSUE THREAD

**Issue by Praneeth2k** [calcom/cal.com#10016]
### Is your proposal related to a problem?

It would be nice if we could drag and drop the event types instead of using arrows to move them one step up or down.

https://github.com/calcom/cal.com/assets/47350983/71919323-eeba-4828-8ec5-1e95414f35b8

### Describe the solution you'd like

Implement drag and drop using [react-beautiful-dnd](https://www.npmjs.com/package/react-beautiful-dnd?activeTab=readme).

### Describe alternatives you've considered

There are other libraries like react-dnd but react-beautiful-dnd seems to be the most popular one.

### Additional context

There was an issue that was raised before and was closed as it was low priority and since drag and drop tends to be flaky: https://github.com/calcom/cal.com/issues/7125.
With this in mind this feature can be considered a prototype, which will need extensive testing before it can be submitted.

**Comment by jaypitroda12** [comment]
@Praneeth2k Since react-beautiful-dnd is not currently actively maintained, I think [dnd-kit](https://dndkit.com/) would be a more suitable choice.

**Comment by moinbukhari** [comment]
have done drag and drop in my project with react-beautiful-dnd, check out muddhakir on my github or muddakir.app apply section to try it out. The only issue is that it might be better to use dnd-kit since react-beautiful-dnd doesn't work for flex boxes or grids when they overflow to the next line.

/claim #10016

**Comment by Ashutosh-Bhadauriya** [comment]
@baileypumfleet I would like to work on this

**Comment by Praneeth2k** [comment]
@gupta-piyush19 [Yes](https://github.com/calcom/cal.com/pull/10017), but this feature was not assigned to me.

**Comment by gupta-piyush19** [comment]
Let me know if you need any help, or I'll pick it up if you drop it.

**Comment by Praneeth2k** [comment]
> Let me know if you need any help, or I'll pick it up if you drop it.

Made some progress over the weekend and opened the PR for review. I will let you know if I need some help, Thanks!

**Comment by PeerRich** [comment]
i thought about this more and i dont think we should be doing drag and drop here. sorry about the bounty

**Comment by valdemartti** [comment]
No worries!
