### ISSUE TITLE
[CAL-2127] feature: 30 day email digest

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10026]
https://twitter.com/steventey/status/1678107446857072640?s=46&t=XsU6yrqPhYPfQwlOR-9I-w

<sub>[CAL-2127](https://linear.app/calcom/issue/CAL-2127/feature-30-day-email-digest)</sub>

**Comment by PeerRich** [comment]
maybe some graphs from insights?

**Comment by giteshsarvaiya** [comment]
@PeerRich great idea! what kind of stats do you look forward to have in that email digest ?

 Also, I dont see the api to fetch insights data, please guide me in how to proceed with this

**Comment by satya-nishanth** [comment]
@PeerRich  can you throw more light on what kind of stats are required in the email digest? Just a rough flow would suffice
