### ISSUE TITLE
Empty Spaces in Text Field Do Not Trigger Inline Field Error

### ISSUE THREAD

**Issue by akhil27styles** [calcom/cal.com#10028]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I would like to report an issue regarding the behavior of a text field in my application. When I input empty spaces into the Your name field and submit, no inline field error is displayed to notify the user of the invalid input.
### Steps to Reproduce

1. Schedule any meeting
2. Give empty spaces in your name section 

### Screenshot
![image](https://github.com/calcom/cal.com/assets/52193850/b431072a-1603-4b09-b659-a8818fa04775)
![image](https://github.com/calcom/cal.com/assets/52193850/220df981-0cbe-4014-94f7-7ded66753fa9)

**Comment by greatmaxy** [comment]
I want to work on this. Mod, can you please assign this to me?
