### ISSUE TITLE
About section editor contains unnecessary scrollbar

### ISSUE THREAD

**Issue by MehulZR** [calcom/cal.com#10036]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On getting started page, the about section contains a unnecessary scrollbar.

### Steps to Reproduce

1. Create a new user and verify the email.
2. Once you login again
3. On step 5 of profile setup, you will see the unnecessary scrollbar.

### Current Behaivour
![image](https://github.com/calcom/cal.com/assets/86384652/382bd88d-20ee-4883-b4f4-b7648e98246c)

### Supposed to be
![image](https://github.com/calcom/cal.com/assets/86384652/0762f00a-9a29-4390-b983-e71789ec51ea)

### Technical details

- Browser: Chrome Version 114

**Comment by Chavda-Mitul** [comment]
hey I am new to this project so with this issue I would like to start contributing in this project
