### ISSUE TITLE
[CAL-2128] Embed Code Snippet Generator should use event slug as namespace for API

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10031]
Using event slug as namespace for the generated code would allow users to have more than 1 embed on a single page without making any changes to the code snippet.

This is a problem faced by a user [as reported in Discord](https://discord.com/channels/1125390093386010654/1126084367119290438/1126122986106265640)

<sub>[CAL-2128](https://linear.app/calcom/issue/CAL-2128/embed-code-snippet-generator-should-use-event-slug-as-namespace-for)</sub>

**Comment by keithwillcode** [comment]
Removing from milestone because PR went stale.
