### ISSUE TITLE
[CAL-2131] No text visible in assignment selection select box if the users don't have name set.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10040]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/29c2f82b-3cd7-4141-b338-8d8a19bbcdb0/9bcfb560-b569-4f99-bbc1-3d2a4c2413e8)

[Source image](https://github.com/calcom/cal.com/assets/1780212/9d5a1cf8-54ca-449b-97e6-4b654a6e6f99)

It is easily possible to have a user with no name now because org owner can invite a user and then immediately want to assign him.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2131](https://linear.app/calcom/issue/CAL-2131/no-text-visible-in-assignment-selection-select-box-if-the-users-dont)</sub>

**Comment by gitstart-calcom** [comment]
Hey @hariombalhara a doubt here, It should be possible to assign to a member who has a requesting invitation?
It would help a lot if we have the steps to reproduce the issue and the exact desired behavior. 😄

**Comment by ashish1233** [comment]
Hi Team, I am new contributor in Cal.
as i can see it has quick wins label can i pick this one? if i get more detail on this, as i can't acess to this ticket.

**Comment by hariombalhara** [comment]
> Hey @hariombalhara a doubt here, It should be possible to assign to a member who has a requesting invitation? It would help a lot if we have the steps to reproduce the issue and the exact desired behavior. 😄

So, that's not possible yet. But will be soon.  I had this scenario because I created an organization and in that case Organization onboarding is done and user can end up without a name and still configure many things in the app.

**Comment by keithwillcode** [comment]
Cannot be reproduced
