### ISSUE TITLE
Cal.com documentation returns code 500

### ISSUE THREAD

**Issue by jamesthesken** [calcom/cal.com#10049]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Accessing the documentation pages results in an error code of `500 Internal Server Error.`. This does not occur on the landing page of the documentation, but does for other docs routes (e.g., [https://cal.com/docs/introduction/quick-start](https://cal.com/docs/introduction/quick-start))

### Steps to Reproduce

1. Go to a page in the documentation - e.g.,  [https://cal.com/docs/introduction/quick-start](https://cal.com/docs/introduction/quick-start)
2. Wait for page to load
3. Encounter error code 500.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

  - Error Code 500 Internal Server Error 

### Expected Results 

  - Access to documentation pages.

### Technical details

  - System: 2020 MacBook Pro (Intel)
  - Browsers: Safari v16.4, Chrome Version 114.0.5735.198 

### Evidence

  - How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
<img width="2032" alt="Screenshot 2023-07-10 at 12 27 01 PM" src="https://github.com/calcom/cal.com/assets/22358037/fa8c6805-b27d-4660-8048-f6b313b81186">

**Comment by aashish0909** [comment]
I don't see this error. I am able to access the documentation pages.

**Comment by vats147** [comment]
It Will work fine now i Guess
![image](https://github.com/calcom/cal.com/assets/89577062/9835c8a6-9531-49f8-9a28-a6d3e7720577)
