### ISSUE TITLE
[CAL-2133] Show proper error when booker has already signed up for a timeslot

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10057]
When an email has already signed up for a seated timeslot, the booking is rejected. But proper error isn't shown to user.

Error shown to user

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5845c678-de8d-495a-9d0d-62560824b651/d4b3a0b7-a9c2-4d6b-b502-20061a25c65a)

[Source image](https://github.com/calcom/cal.com/assets/1780212/050bc30f-e9ac-43e8-a484-c9b5a545de22)

Actual Error

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f19c36fe-1bfe-46e8-ade2-7f90a2771812/867d9155-0733-420f-887b-81d347d801e6)

[Source image](https://github.com/calcom/cal.com/assets/1780212/759840cf-e5c3-4b4c-88e0-9a8909e34cd7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2133](https://linear.app/calcom/issue/CAL-2133/show-proper-error-when-booker-has-already-signed-up-for-a-timeslot)</sub>

**Comment by arin-r** [comment]
Can I take up this issue? 
It would involve checking if the error is an instance of HttpError with a status code of 409.
I would then have to add a new error message for every language, right?
