### ISSUE TITLE
[CAL-2134] Toggle to open custom success page in embed itself.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10058]
Provide an option to choose where the custom success redirect page would open
- Outside the embed - **Default**
- Within the embed

<sub>[CAL-2134](https://linear.app/calcom/issue/CAL-2134/toggle-to-open-custom-success-page-in-embed-itself)</sub>

**Comment by vats147** [comment]
I cannot able to access issue why ??
![image](https://github.com/calcom/cal.com/assets/89577062/7d215be9-abef-401e-9407-61107bc59e43)

**Comment by PeerRich** [comment]
the [CAL-2134](https://linear.app/calcom/issue/CAL-2134/toggle-to-open-custom-success-page-in-embed-itself) link is for internal use only. the ticket in linear is identical with what you see here
