### ISSUE TITLE
[CAL-2145] /onboarding: No feedback on buttons in onboarding

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10061]
After I click a button, it should show in loading state similar to other parts of the app

[https://github.com/calcom/cal.com/assets/8019099/52c75b87-3d4c-4878-b6e9-089213198104](https://github.com/calcom/cal.com/assets/8019099/52c75b87-3d4c-4878-b6e9-089213198104)

[Button Brief - Cal DS - Components (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=309%3A42062&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2145](https://linear.app/calcom/issue/CAL-2145/onboarding-no-feedback-on-buttons-in-onboarding)</sub>

**Comment by Raghul18** [comment]
@Jaibles  : I would like to work on this issue. Can you please assign this to me? Also can you please attach any screenshot or video if possible?

**Comment by PeerRich** [comment]
added video https://github.com/calcom/cal.com/assets/8019099/52c75b87-3d4c-4878-b6e9-089213198104

**Comment by nish9142** [comment]
@PeerRich Can you assign this to me?
