### ISSUE TITLE
[CAL-2188] Events and emails are being sent to an old, disconnected Google account

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#10066]
### Issue Summary

I recently was asked if I was joining a call that someone had scheduled with me and I noticed the event was not put onto the calendar I have linked but instead it was sent to an old, disconnected Google account that I had already completely removed from my Cal.com account.

### Steps to Reproduce

1. Link 1 Google account and set that as the default calendar for where events are added
2. Link another Google account
3. Delete the first Google account added and make sure the 2nd one is now the default. 
4. Submit bookings to your account.

### Actual Results

  - I'm getting Google calendar events and emails to an old, disconnected Google account instead of the one that is set in app.cal.com (it's the only one even connected).

### Expected Results

  - To get events on the calendar that is linked and set as default or overridden on event types

### Evidence
<img width="768" alt="Screen Shot 2023-07-11 at 4 29 51 PM" src="https://github.com/calcom/cal.com/assets/2538462/e8acc246-5a7b-4850-a663-bdedee850ba1">

<img width="1415" alt="Screen Shot 2023-07-11 at 5 04 38 PM" src="https://github.com/calcom/cal.com/assets/2538462/6b10928b-e411-4b62-be99-9b9c225e4d59">

<sub>[CAL-2188](https://linear.app/calcom/issue/CAL-2188/events-and-emails-are-being-sent-to-an-old-disconnected-google-account)</sub>

**Comment by joeauyeung** [comment]
Update on this issue. I'm able to replicate this on production but not locally on `main` and `v3.1.3`.

**Comment by Udit-takkar** [comment]
@keithwillcode i am also unable to replicate this bug locally.

**Comment by Udit-takkar** [comment]
also works fine on production ( v3.1.4)

**Comment by keithwillcode** [comment]
@Udit-takkar Ok I will try again on prod and see if I can reproduce.

**Comment by keithwillcode** [comment]
@Udit-takkar This is still happening for me on production.

**Comment by Udit-takkar** [comment]
@keithwillcode can you send me the booking page url of the event type ?

**Comment by keithwillcode** [comment]
@Udit-takkar It's https://app.cal.com/keithwillcal/15min.
@alishaz-polymath I've done that multiple times actually. Keeps persisting.

**Comment by emrysal** [comment]
@keithwillcode Is it possible your cal.com account was created using that google calendar? I remember an issue in the past about that.

**Comment by keithwillcode** [comment]
Yeah it most likely was.

**Comment by keithwillcode** [comment]
This is no longer happening though. Going to close.
