### ISSUE TITLE
[CAL-2146] Create <AvatarFor> component to make the avatar code DRY

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10065]
There is avatar image path calculation logic spread throughout the app. See this PR https://github.com/calcom/cal.com/pull/10062 which tried to fix the image at all the places.

We should create a wrapper probably <AvatarFor team org user> that can accept one of team/org/user and accordingly automatically show the correct image using <Avatar> component

<sub>[CAL-2146](https://linear.app/calcom/issue/CAL-2146/create-avatarfor-component-to-make-the-avatar-code-dry)</sub>

**Comment by vats147** [comment]
I cannot acvess the issue on liner why??

**Comment by hariombalhara** [comment]
Linear is just for our internal tracking. There is no additional information in the ticket that's not here.

**Comment by Sudhanva-Nadiger** [comment]
can i work on this ?

**Comment by MuminBashir** [comment]
@hariombalhara @PeerRich Greetings! I would like to work on this issue.

**Comment by hariombalhara** [comment]
This is sorted already.
