### ISSUE TITLE
[CAL-2148] Cal.dev api/username not working

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#10074]
Currently not working and returning 405 Method not allowed.

Blocking cal.dev orgs testing.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2148](https://linear.app/calcom/issue/CAL-2148/caldev-apiusername-not-working)</sub>

**Comment by ashishsurya** [comment]
Assign this to me, I will work on it
