### ISSUE TITLE
Meeting booking link -> long event description -> text wrapping is odd

### ISSUE THREAD

**Issue by brennanfoo** [calcom/cal.com#10070]
### Issue Summary

Text wrapping on cal.com/{bookinglink} looks funny sometimes. (I'd expect "dive right in" to be in the red area rather than wrapping to the next line. Looks kinda funky as is.)

![image](https://github.com/calcom/cal.com/assets/4824169/a82fcfdf-377f-4028-a9e1-ada251c393e2)

### Steps to Reproduce

1. Create a meeting type with a description that occupies at least 2 lines.
2. Go to your booking page (or see https://cal.com/bwfoo for a live demo...)

### Actual Results

Long descriptions break lines without using the full width of the container [see red highlighted area].

### Expected Results

Either: (1) descriptions to occupy the full width of the container, or (2) for the container width to be smaller.

### Technical details

Brave, but same behaviour on Chrome

### Evidence

Go to cal.com/bwfoo. Maximize the window at 1920x1080+ res. Look at the description for the first meeting.

**Comment by PeerRich** [comment]
fixed https://github.com/calcom/cal.com/pull/10071
