### ISSUE TITLE
[CAL-2156] Back button removed in profile page embed

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10085]
That back button is intentionally removed from the embed I guess. This should be fixed.Back button should be disabled only when user embeds an event-type directly. If user embeds the profile page it should be shown

Created via Threads. See full discussion: [https://threads.com/messages/263f3faa-645f-468a-b845-62d27fb7b5a6?messageID=863d68dc-73b6-4ae5-8f17-2dd186ef0f48](https://threads.com/messages/263f3faa-645f-468a-b845-62d27fb7b5a6?messageID=863d68dc-73b6-4ae5-8f17-2dd186ef0f48)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2156](https://linear.app/calcom/issue/CAL-2156/back-button-removed-in-profile-page-embed)</sub>

**Comment by PeerRich** [comment]
not sure if i understand the ticket @milospuac

**Comment by kcrimi** [comment]
@PeerRich I believe this came from my conversation with @milospuac 

You can see my example embed here https://tech.kevincrimi.com/widgets/cal/services/

### Repro steps

1. Open the embed with the button
2. Select one of the services from the list of event types to open calendar screen

### Expected 
Can navigate back to the profile menu to select another service if desired

### Actual
No back button present to navigate back. Closing the modal and reopening still shows the calendar view. The only way to get back to the profile screen is to fully reload the whole page

**Comment by shirazdole** [comment]
@PeerRich can we get this prioritized? I've seen other customers deal with this issue as well. cc @keithwillcode

**Comment by arjavsethi** [comment]
Hey , as far as i understand this issue , just have to add back button in our event page right?
![image](https://github.com/calcom/cal.com/assets/75158301/bdd2428c-d7d1-46d4-b889-2e7c38ff971d)

If yes , then can i work on this issue?
@keithwillcode
