### ISSUE TITLE
[CAL-2151] Top banner has weird z-index position in settings

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10080]
[https://github.com/calcom/cal.com/assets/8019099/10c87eb6-d4e3-4c2b-a66e-02adaa5945ad](https://github.com/calcom/cal.com/assets/8019099/10c87eb6-d4e3-4c2b-a66e-02adaa5945ad)

The banner should behave the same as on the regular pages.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2151](https://linear.app/calcom/issue/CAL-2151/top-banner-has-weird-z-index-position-in-settings)</sub>

**Comment by AlimurtuzaCodes** [comment]
I can fix this issue assign it to me.

**Comment by hasnaat-iftikhar** [comment]
Can I start working on that one?

**Comment by Amdadullah-Raihan** [comment]
Dear Mr. @Jaibles,

I am eager to work on this issue. Would you like me to set up the project locally and start working on it, and then create a pull request? Or would you like to assign the project to me directly?

Thank you for your time and consideration.

Sincerely,
Amdadul Islam

**Comment by cverma61** [comment]
Dear Mr. @Jaibles,
Please assign me this issue. I'm new to open source but have 1.5 years of experience in front - end development.

**Comment by Jaibles** [comment]
We're not assigning issues to people. Feel free to create a pr and mention this issue if you want to tackle it 🙏

**Comment by sonu71432** [comment]
please assign me this issue

**Comment by gitstart-calcom** [comment]
Hi @PeerRich We didn't push a PR to solve it because already have an open PR here, do you want us to solve this?
