### ISSUE TITLE
Preview State in Embed Dialog is getting revert to default state after changing the tabs

### ISSUE THREAD

**Issue by sjana7797** [calcom/cal.com#10087]
### Issue Summary

The preview state is reverted to the default state after changing the tab. All the selected colors and themes are being lost to the default state. The main issue is due to the state being managed by the query params, and because of this, the EmbedDialog Component is being rendered repeatedly after we change the tab.

### Steps to Reproduce

1. Go to event types and click on more options and select the embed option
2. The dialog box will open, change the color and theme and select the new tab  (preview or react).
3. the preview state gets reverted to the default one.

### Actual Results

  - The state is being lost when we change the tab.

### Expected Results

  - The state should be preserved even when changing the tab.

### Evidence

  - Below is the issue
![cal-com-embed-dialog-state-error](https://github.com/calcom/cal.com/assets/72548403/bc1b985a-eced-4d3f-b354-e3ac96ac7bb8)

**Comment by PeerRich** [comment]
@hariombalhara i have seen this before on my end too
