### ISSUE TITLE
Dangling zero in the dashboard

### ISSUE THREAD

**Issue by thecmdrunner** [calcom/cal.com#10082]
### Issue Summary

There's a dangling zero at the bottom of the dashboard

![image](https://github.com/calcom/cal.com/assets/38887390/906fe17c-3a94-4476-aec0-53b7ac75a5fc)

### Steps to Reproduce

1. Click edit on any of your existing events - for example: https://app.cal.com/event-types/123456?tabName=advanced
2. Scroll to the bottom
3. Find a dangling zero down there

### Actual Results

  - There's a random zero at the bottom of the dashboard

### Expected Results

  - There should not be a random zero at the bottom of the dashboard

**Comment by PeerRich** [comment]
this is likely due to someone checking for length with `&& component` instead of `? component : null` which causes trailing 0's

**Comment by PeerRich** [comment]
fixed

**Comment by thecmdrunner** [comment]
Hey @PeerRich, still seems to be the case...

https://github.com/calcom/cal.com/assets/38887390/b45dcabf-5385-4d1e-9bb4-3068cd4fe940
