### ISSUE TITLE
[CAL-2152] Ability to resend team invites

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#10081]
I should be able to trigger resend of invite emails to pending members in my teams & organizations. We can include it in the dropdown action menu.

![Linear-hosted image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ae274d53-5005-4973-afc6-2aed8ecc9c58/9a7666e0-a4af-4bd2-a9eb-348900a0d3f4)

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ae274d53-5005-4973-afc6-2aed8ecc9c58/9a7666e0-a4af-4bd2-a9eb-348900a0d3f4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2152](https://linear.app/calcom/issue/CAL-2152/ability-to-resend-team-invites)</sub>

**Comment by anikdhabal** [comment]
@Jaibles I have question like, when I resend invite emails to pending members is it open a dialog to reselect the role of that member and also for copying Invite Link or It just simply send an invite email.

**Comment by rkreddy99** [comment]
Hey @Jaibles is this image public?

**Comment by rkreddy99** [comment]
Hi @Jaibles Can I work on this?

**Comment by rkreddy99** [comment]
Is this the required change https://github.com/calcom/cal.com/compare/main...rkreddy99:cal.com:rkreddy99/cal-2152

![image](https://github.com/calcom/cal.com/assets/49095575/3bb7530e-b2cd-4e51-98a4-b5b53fec7b7c)
 Added resend invitation for a pending user

**Comment by Hanaffi** [comment]
@Jaibles @PeerRich 
Can you assign it to me please?

**Comment by leog** [comment]
Already implemented!
