### ISSUE TITLE
Fix the design of the "change username" dialog

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#10091]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The dialog of username change is not in correct design.
![Screenshot 2023-07-12 173931](https://github.com/calcom/cal.com/assets/81948346/7b630bc1-cff5-44e8-8f88-181c132afc10)

### Steps to Reproduce

1. Go to profile
2. change username

**Comment by AlimurtuzaCodes** [comment]
I can fix this issue assign it to me.

**Comment by PeerRich** [comment]
@AlimurtuzaCodes go for it, no need to be assigned!

**Comment by AlimurtuzaCodes** [comment]
Updated Design

![image](https://github.com/calcom/cal.com/assets/88965204/24629f9d-6c9f-46fe-ab05-01c9790d3682)

**Comment by AlimurtuzaCodes** [comment]
Done PR #10095 .
