### ISSUE TITLE
[CAL-2159] sendgrid: bypass unsubscribe groups for transactional emails

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10093]
ignore unsubscribe for:
- email verification
- booking emails
- password reset

https://docs.sendgrid.com/ui/sending-email/index-suppressions#bypass-list-management

<sub>[CAL-2159](https://linear.app/calcom/issue/CAL-2159/sendgrid-bypass-unsubscribe-groups-for-transactional-emails)</sub>

**Comment by PeerRich** [comment]
we should also ignore bounce lists. some emails bounce once and then never get emails again

**Comment by keithwillcode** [comment]
Fixed by #11877
