### ISSUE TITLE
RFC: [CAL-2158] Use BOOKER_URL instead of WEBAPP_URL for booking pages links

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10092]
Use BOOKER_URL instead of WEBAPP_URL to link to booker pages. Earlier WEBAPP_URL and BOOKER_URL were always same but now due to an org being able to have it's own subdomain(eg. [acme.cal.com](http://acme.cal.com)) for booker, this is not the case.

BOOKER_URL can't be a constant because it is derived from the slug set for the organization. So, this responsibility can be taken care of by  a new `useBookerUrl` hook which can give the URL(after deriving from useOrgBrandingValues)

Also, avatars are also supposed to be loaded from BOOKER_URL.

There are many many occurences where the instances are spread across the app. Goal is to be easily able to manage booking URL at a single place.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cb384417-f597-49c6-82f7-7a0a5e759b0e/d89e6a8c-faca-41e9-ba44-28789c2097b2)

[Source image](https://github.com/calcom/cal.com/assets/1780212/ef40b419-33bc-4a68-8f7f-5c99021bc0f9)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2158](https://linear.app/calcom/issue/CAL-2158/use-booker-url-instead-of-webapp-url-for-booking-pages-links)</sub>

**Comment by PeerRich** [comment]
agree with this
