### ISSUE TITLE
Weekly view displays a day ahead on self hosted instance

### ISSUE THREAD

**Issue by JohnKimDev** [calcom/cal.com#10107]
In a weekly view, all schedules display a day ahead. As a result, when I click on a day in a weekly view display (say 1/15), it opens a modal popup display with the day before (1/14).  Other views are fine. 

A different way to reproduce the issue:
When I turn off Sunday from the availability, in the weekly view, I see Monday is displayed as unavailable instead of Sunday.

**Comment by PeerRich** [comment]
do you have screenshots or even a video?

**Comment by rkreddy99** [comment]
unable to reproduce this https://www.loom.com/share/612ff52bea5b4ae486ac0e8759adba94?sid=7b2e0996-a4bc-4569-924d-1eee7be7c92e

**Comment by JohnKimDev** [comment]
It may be my configuration issue but I am having the problem. Here is the video recording. 
https://d.pr/i/W2chOF

Note that this issue only happens in the "weekly" view.  Other views work fine.

**Comment by JohnKimDev** [comment]
> do you have screenshots or even a video?

It may be my configuration issue but I am having the problem. Here is the video recording.
https://d.pr/i/W2chOF

Note that this issue only happens in the "weekly" view. Other views work fine.

**Comment by JohnKimDev** [comment]
with the latest codes, the issue no longer exists.
