### ISSUE TITLE
Organization URL (slug) is empty on the Organization profile

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10114]
### Issue Summary

The organization URL is empty on Organization Profile.

Maybe related: https://github.com/calcom/cal.com/issues/9864

### Steps to Reproduce

1. Create an organization (/settings/organizations/new)
2. Skip the team creation step
3. Go to the settings page (settings/my-account/general)
4. Go to the Organization profile page (/settings/organizations/profile)
7. Check the Organization's URL content

### Actual Results

  - Slug is empty for the Organization URL

### Expected Results

  - It should have the slug set during the Organization creation.

### Technical details

  - Tested on Chrome Version 114.0.5735.199 (Official Build) (64-bit)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/f00f0d51-ab4d-4268-9b88-1a6205c33097)

**Comment by 0xWormh0le** [comment]
Assign it to me please

**Comment by 0xWormh0le** [comment]
Organization slug is showing on my side.
![image](https://github.com/calcom/cal.com/assets/18642714/f445f1c3-8267-4c7a-a099-b8fc6f0f4db5)
@ericrommel

**Comment by hariombalhara** [comment]
I too can't replicate this @ericrommel. Can you record a birdeatsbug or loom for it if it's still replicable

**Comment by ericrommel** [comment]
The issue was solved after DB fixing.
