### ISSUE TITLE
Getting 404 from Event Type after fresh setup (Organizations)

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10115]
### Issue Summary

After setting up the Organization profile, the preview button and the link copied are going to the 404 page

### Steps to Reproduce

1. Create an organization (/settings/organizations/new)
2. Skip the team creation step
3. Set up the Organization profile
4. When back to Event Type page, click on Preview button (or click on copy link button and paste it in another tab)
5. Observe the 404 page

### Actual Results

  - The link from preview button and link are pointing to a 404 page

### Expected Results

  - It should open the booking page with a calendar to set it

### Technical details

  - Tested on Chrome (114.0.5735.134)

### Evidence
  
![image](https://github.com/calcom/cal.com/assets/10250819/2a5a386c-649f-4a3e-b02c-0db21b852671)

![image](https://github.com/calcom/cal.com/assets/10250819/27114908-5d51-4bcf-a004-1cb166c6c526)

**Comment by hariombalhara** [comment]
It's a Vercel config issue that happened earlier and won't happen for new orgs.
