### ISSUE TITLE
[CAL-2162] Make impersonation organization aware.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10123]
Usernames aren't unique anymore and thus impersonating only by username can accidentally impersonate into unexpected account.
Internal discussion as well: [https://threads.com/34506453732?s=oFtgvQ78FcLkLFzP6D5jZw](https://threads.com/34506453732?s=oFtgvQ78FcLkLFzP6D5jZw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2162](https://linear.app/calcom/issue/CAL-2162/make-impersonation-organization-aware)</sub>

**Comment by sean-brydon** [comment]
Fixed
