### ISSUE TITLE
[CAL-2185] Embed inline missing time slots on IPhone 12

### ISSUE THREAD

**Issue by gabrielberlanda** [calcom/cal.com#10120]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I've found a weird bug happening only on IOS, I am using an iPhone 12, and I've tested it on my android and Windows PC and it is working fine, if I test the same behavior in using my public page it also works, I could only reproduce it with the React embed component.

If I start navigating through my availability and then I select a day with for example 10 slots and then I select a day with only one or two slots, the slot container hides my available slots and I've also noticed a blank space above the time slots container.

### Steps to Reproduce

1. Went to an event
2. Clicked on a day with lots of time slots
3. Clicked on a day with only one or two time slots

### Actual Results

  - The embed component hides my available time slots

### Expected Results

  - I would be able to see and book all my available time slots

### Technical details

  - Iphone 12 on Safari and Chrome
  - "@calcom/embed-react": "^1.2.2",
  - React embed inside a client-side nextjs 13 page

```import Cal, { getCalApi } from "@calcom/embed-react"

const ServiceCard = ({ name, description, duration, price, calUrl, cta = 'Agende seu horário' }: ServiceProps) => {
  const [showCal, setShowCal] = useState(false)
  useEffect(() => {
    (async function () {
      const Cal = await getCalApi();
      Cal("ui", {
        hideEventTypeDetails: true,
      })
    })();
  }, []);

  const descriptionElement = typeof description === 'string' ? <p>{description}</p> : description

  return (
    <div className="mt-4 mb-4 bg-linen-50 rounded-md drop-shadow-md">
      <div className="p-8">
        <h3 className="font-bold">{name}</h3>
        {descriptionElement}
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center space-y-2 mt-4">
          <div className="flex flex-col">
            <div className="flex flex-row space-x-2">
              <Clock />
              <span>{duration} min</span>
            </div>
            <span className="font-bold">R$ {price}</span>
          </div>
          <Button className="" variant='gradient' onClick={() => setShowCal(prev => !prev)}>
            {showCal ? <X /> : cta}
          </Button>
        </div>
      </div>
      {showCal && (
        <div className="mt-4 mb-4">
          <Cal
            calLink={calUrl}
            config={{
              theme: 'light'
            }}
          />
        </div>
      )}
    </div>
  )
}
```
I've also removed all the page content and added just an embed component and the same issue happened.

```
export default function BookingPage() {
  return (
    <Cal
      calLink={CAL_URL}
      config={{
        theme: 'light'
      }}
    />
  )
}
```

### Evidence

 

https://github.com/calcom/cal.com/assets/11332820/410135af-7840-4eea-8cda-b25346c83f24

<sub>[CAL-2185](https://linear.app/calcom/issue/CAL-2185/embed-inline-missing-time-slots-on-iphone-12)</sub>

**Comment by PeerRich** [comment]
@hariombalhara can try to investigate. can you scroll? or is it unreachable?

**Comment by hariombalhara** [comment]
Also, do you see the issue without the embed as well, if you directly open the cal.com link in iPhone

**Comment by gabrielberlanda** [comment]
@hariombalhara the link can be accessed here: https://studiomellber.com.br/agendamento

If I open the cal.com link it does work well, I could reproduce only with the embed
