### ISSUE TITLE
on event type paid if you reschedule you have to double paid!

### ISSUE THREAD

**Issue by zodman** [calcom/cal.com#10121]
### Issue Summary

When you have activated the stripe integration,  the user can schedule an event type. then paid with Stripe. But if you reschedule, you have to pay again to reschedule. double payment? naah!

The application should be checked if the event is paid not to show again the stripe form.

### Steps to Reproduce

`yarn run e2e stripe  -g reschedule`

run the e2e test to reproduce the error..

**Comment by rkreddy99** [comment]
Pls ignore the above pr.

**Comment by rkreddy99** [comment]
@zodman 

The verification for a successful payment does exist.

However, at least in my specific local setup, the payment has been processed to Stripe, but not paid from stripe to the event owner's account, as shown in the attached picture. Consequently, the "paid" column in the database is not being marked as true. As a result, when a user attempts to reschedule the meeting, the payment page reappears.

So i believe that once the payment goes thru to the event owner's account, there might be some webhook trigger that will make sure that the "paid" col is updated.

PFA stripe payments page, and bookings page from cal

![image](https://github.com/calcom/cal.com/assets/49095575/8b48dc90-fb9d-4cc5-aa11-ec1e9a42fdbd)
(you can see all the payments are held up)

![image](https://github.com/calcom/cal.com/assets/49095575/ba832a1a-7797-46fb-b3a1-f31216e9fa96)
(all bookings have payment pending tag)

@joeauyeung -Can you confirm that whether this is what is happening? thanks.

**Comment by zodman** [comment]
oooh yes you are right! is invalid
