### ISSUE TITLE
[CAL-2163] /bookings - container issues, content not stretching full width

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10124]
[https://share.cleanshot.com/M3nnHTv4](https://share.cleanshot.com/M3nnHTv4)

Container width should match other pages. Should be:

[https://share.cleanshot.com/fRN4lLjf](https://share.cleanshot.com/fRN4lLjf)

[View in Figma](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=23%3A40442&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2163](https://linear.app/calcom/issue/CAL-2163/bookings-container-issues-content-not-stretching-full-width)</sub>

**Comment by greatmaxy** [comment]
Hi Jaibles, I would like to work on this issue.
