### ISSUE TITLE
[CAL-2170] Wrong slot starting times for timezones that are not full hours

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#10136]
The slot starting times aren't correct for timezones like Asia/Kolkata (+5:30). Hourly events would start at half-hour slots instead of full-hour slots.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2170](https://linear.app/calcom/issue/CAL-2170/wrong-slot-starting-times-for-timezones-that-are-not-a-full-hour)</sub>

**Comment by ccmaris** [comment]
Can I pick this one please?
