### ISSUE TITLE
[CAL-2168] bug: og-image stopped working for event links

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10131]
![Linear-hosted image](https://github.com/calcom/cal.com/assets/8019099/48563c61-8313-4316-ae15-0040344c3197)
[Image source](https://github.com/calcom/cal.com/assets/8019099/48563c61-8313-4316-ae15-0040344c3197)

[cal.com/peer](http://cal.com/peer) works, [cal.com/peer/30min](http://cal.com/peer/30min) doesnt

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2168](https://linear.app/calcom/issue/CAL-2168/bug-og-image-stopped-working-for-event-links)</sub>

**Comment by ccmaris** [comment]
Can I pick this one?

**Comment by PeerRich** [comment]
sure go for it @ccmaris
