### ISSUE TITLE
Set up Organizations fields are not being validate well

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10148]
### Issue Summary

The three fields from the "Set up your organization" page are mandatory. They shouldn't be empty. In that case, they also should accept only spaces as a name/address. This is actually occurring.

1. Log in as an Admin
2. Go to the first step of creating an organization (/settings/organizations/new)
3. Click on the "Continue" button
4. Observe that the three fields show notifications saying that can't be empty
5. Type only one space in each field
6. Click on the "Continue" button
7. Observe that only the "Organization URL" field shows a notification
8. Play around it to see other behaviours (see the loom attached)

### Actual Results

- Fields are not being properly validated

### Expected Results

- Fields should handle invalid values

### Technical details

- Tested on Chrome (114.0.5735.134)

### Evidence

https://www.loom.com/share/14302e6936664fa8bbcf1b9239f5b9b7

**Comment by JunedKhan101** [comment]
If this is available to work on. I would like to pick this up.
