### ISSUE TITLE
[CAL-2184] Importing from @calcom/embed-react causes build error

### ISSUE THREAD

**Issue by lpalazzi** [calcom/cal.com#10145]
### Issue Summary

My app fails when importing `{ getCalApi } from '@calcom/embed-react'` to add an embedded floating pop-up button.

### Steps to Reproduce

1. Using own React app (with Remix)
2. Install package (I used `yarn add @calcom/embed-react`)
3. Include `import { getCalApi } from '@calcom/embed-react';` in the root jsx file
4. Run build

### Actual Results

Build error:
```
import { getCalApi } from "@calcom/embed-react";
         ^^^^^^^^^
SyntaxError: Named export 'getCalApi' not found. The requested module '@calcom/embed-react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@calcom/embed-react';
const { getCalApi } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

### Expected Results

Correctly builds and displays the embedded component.

### Technical details

If I manually edit the `node_modules/@calcom/embed-react/package.json` file to include `"type": "module"`, my app builds and runs as expected, including the embedded floating pop-up button.

<sub>[CAL-2184](https://linear.app/calcom/issue/CAL-2184/importing-from-calcomembed-react-causes-build-error)</sub>

**Comment by PeerRich** [comment]
@hariombalhara i think i have seen this before

**Comment by hariombalhara** [comment]
@lpalazzi I quickly setup a bare minimum next.js repo here https://github.com/hariombalhara/cal-embed-react-next-js
The build works fine for me there.
<img width="790" alt="Screenshot 2023-07-14 at 8 58 52 PM" src="https://github.com/calcom/cal.com/assets/1780212/776b1d23-5937-4fbf-a027-67d1a15f73b0">

There is `module` property set in package.json, so it should have worked fine 
<img width="399" alt="Screenshot 2023-07-14 at 8 59 20 PM" src="https://github.com/calcom/cal.com/assets/1780212/4eada266-74f8-4841-b9db-960f978ba298">

Is it possible for you to setup a bare minimum example where it fails.

**Comment by hariombalhara** [comment]
> @hariombalhara i think i have seen this before

Seeing this error for the first time.

**Comment by lpalazzi** [comment]
@hariombalhara 

I was able to reproduce with a new Remix app: https://github.com/lpalazzi/remix-app

build error:
![image](https://github.com/calcom/cal.com/assets/33534854/55a3bc66-5927-4f72-860f-17b3805b6e9a)

**Comment by hariombalhara** [comment]
Thanks. Will check 🙏
