### ISSUE TITLE
Async forEach callbacks cause unpredictable results and prevent error handling

### ISSUE THREAD

**Issue by nicktrn** [calcom/cal.com#10156]
### Issue Summary

Found many instances of `forEach(async ..)` pattern.

JS engine will just fire off the statements, go to the next line, and essentially run those async callbacks in the background.

It's impractical to handle or even catch errors with these constructs. It also creates race conditions that result in unexpected and unpredictable results.

This _could_ be intentional, i.e. hackish way to implement "backround tasks" to speed up parent function returns. But I would *strongly* advise against this for the above reasons.

### Steps to Reproduce

Example from wipemycal:
```js
try {
  bookingRefsFiltered.forEach(async (bookingRef) => {
    // some code
  });
} catch (error) {
  // THIS WILL NEVER FIRE
  if (error instanceof Error) {
    logger.error(error.message);
  }
}
// THIS WILL RUN BEFORE THE ASYNC CODE
await sendRequestRescheduleEmail(..)
```

### Actual Results

Parallel task execution, with:
- uncaught errors + no error handling
- unpredictable results

### Expected Results

Parallel task execution, with:
- error handling
- predictable results

### Evidence

`forEach()` [expects a synchronous function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#:~:text=expects%20a%20synchronous%20function)

**Comment by nicktrn** [comment]
Thanks for bumping this. Rather critical as you said.

Can reopen #10157 if needed, also a bit more info in there, but think this needs more discussion before continuing.

**Comment by hariombalhara** [comment]
The PR looks really good already @nicktrn. Can you remove the custom eslint plugins, I think those might not be needed with `no-misused-promises`.

Also, in there you are fixing some other things. Because this PR is going to touch many pieces, I would really want it to not touch unrelated pieces. We can tackle them separately. Could you make those changes please.

**Comment by nicktrn** [comment]
Thanks @hariombalhara! Will restructure the PR to deal with out-of-scope issues separately.
