### ISSUE TITLE
Allow limit option for duplicate meetings with the same e-mail id, within a week or day.

### ISSUE THREAD

**Issue by akshar001** [calcom/cal.com#10153]
### Is your proposal related to a problem?

I am talking about In general HR interviews, what happened to me is sometimes people schedule two times by mistake for an interview.

### Describe the solution you'd like

 It shall be optional that using same e-mail id within a week there shall be no two consecutive bookings.

**Comment by PeerRich** [comment]
what you are saying is, there has to be a cool-down for the same email to be used multiple times?

**Comment by ciaranha** [comment]
For now this one is going to have to be a manual resolution and the correct one cancelled.
