### ISSUE TITLE
[CAL-2175] No cancellation email when canceling seat

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#10167]
### Issue Summary

When a seat is canceled the organizer an the attendee are not receiving a cancellation email. It only works for the first seat. 

### Steps to Reproduce

1. Create a seated event 
2. Book a seat 
3. Book another seat in the same slot 
4. Cancel the second seat 
5. See that no cancelation email is sent

<sub>[CAL-2175](https://linear.app/calcom/issue/CAL-2175/no-cancellation-email-when-canceling-seat)</sub>

**Comment by AshishKothariii** [comment]
hii CarinaWolf can i get visual representation for reproducing it ? also do i need 2 ids to book 2 seats?

**Comment by rkreddy99** [comment]
@CarinaWolli should the mail be send to other attendees as well or just for the cancelled attendee?

If for all, can we reuse the calendar event that is being generated in the later part of the code?
else, can a new calendar event be created with the current attendee as the only one marked as attendee?

**Comment by iamr-kumar** [comment]
Hey @CarinaWolli, would like to have your thoughts on this. 
Thanks
