### ISSUE TITLE
[CAL-2173] /embed: weekly view - header is broken and I can't move to next week

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10165]
The position of the fixed day header is broken in embeds and the top header showing the date and allowing me to move forward in the month is missing.

[https://github.com/calcom/cal.com/assets/4536123/fd7d5bca-e73e-453d-93c7-8388b20ccc94](https://github.com/calcom/cal.com/assets/4536123/fd7d5bca-e73e-453d-93c7-8388b20ccc94)

Steps to reproduce:

* Embed an event type in a website using the "floating pop-up button" option
* Click the "book a call" button when on the website.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2173](https://linear.app/calcom/issue/CAL-2173/embed-weekly-view-header-is-broken-and-i-cant-move-to-next-week)</sub>

**Comment by ptdatta** [comment]
Hey @Jaibles  can you share steps to reproduce this issue?

**Comment by puru-khedre** [comment]
I can't reproduce this issue, Everything looks fine to me in weekly view.

**Comment by ptdatta** [comment]
> I can't reproduce this issue, Everything looks fine to me in weekly view.

Yeah for me too

**Comment by Jaibles** [comment]
Steps to reproduce in description. Also just click the "book a call" button here to see: https://ciaran.design/
