### ISSUE TITLE
The "PRODUCT FEATURES" option under "More Stories" in "Blog" not working.

### ISSUE THREAD

**Issue by charucjoshi** [calcom/cal.com#10173]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The "PRODUCT FEATURES" option under "More Stories" in "Blog" not working.

### Steps to Reproduce

1. Went to cal.com
2. Navigated to blog
3. Scrolled down and clicked PRODUCT FEATURES (https://cal.com/blog/category/product-features)
4. Fails to run.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

  - What's happening right now that is different from what is expected

### Expected Results

  - This is an ideal result that the system should get after the tests are performed

### Technical details

  - Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
  - Node.js version
  - Anything else that you think could be an issue.

### Evidence

![image](https://github.com/calcom/cal.com/assets/91797128/bbc0cf8b-4f64-43d5-b1ca-3357dd8e6b2d)

**Comment by SiddiqulHaque** [comment]
@charucjoshi It is working fine. You should check it one more time.

**Comment by charucjoshi** [comment]
Not working still! Just click the Product Features option (Under More Stories). The link that I gave here also is not redirecting to the page. So just click on that button.

**Comment by Cipher-08** [comment]
Yes , this issue is valid , it's not working !

**Comment by rortan134** [comment]
> @charucjoshi It is working fine. You should check it one more time.

It only happens when you click on it through the button on the blog, accessing the url directly seems to work fine

https://github.com/calcom/cal.com/assets/37253958/7c517a8d-36e0-4d3e-8adf-4ff66c81a891

**Comment by charucjoshi** [comment]
Yes, that's correct.

**Comment by PeerRich** [comment]
ive submitted a fix, deploying now
