### ISSUE TITLE
 Feature Request: Implementing Navbar Position Change on Scroll Behavior

### ISSUE THREAD

**Issue by Myselfmuzammil** [calcom/cal.com#10178]
### Is your proposal related to a problem?

Yes, the proposal is related to addressing a problem with the current static navbar position during scrolling.

### Describe the problem

The problem is that our website's navbar remains fixed in position regardless of scrolling behavior. This can lead to a less optimal user experience, as the navbar can obstruct content and reduce the visibility of important information.

### Describe the solution you'd like

I would like to propose implementing a feature where the navbar position changes dynamically based on scrolling behavior. Specifically, when scrolling up, the navbar should hide, and when scrolling down, the navbar should be shown. This behavior will provide a better user experience by allowing users to focus on the content while still having access to the navbar for navigation purposes.

### Describe alternatives you've considered

An alternative that has been considered is keeping the navbar fixed in position at all times. However, this alternative does not provide the desired user experience of an unobstructed view of the content during scrolling.

### Additional context

Implementing this feature will require applying appropriate CSS styles to enable dynamic position changes of the navbar. JavaScript or a JavaScript library (such as jQuery) will also be needed to handle scroll events and trigger the navbar position changes. Testing across different browsers and devices will be necessary to ensure consistent functionality.

### Requirement/Document

If there is any document or design that supports this feature proposal, please share it here.

**Comment by shobhitexe** [comment]
> ### Is your proposal related to a problem?
> Yes, the proposal is related to addressing a problem with the current static navbar position during scrolling.
> 
> ### Describe the problem
> The problem is that our website's navbar remains fixed in position regardless of scrolling behavior. This can lead to a less optimal user experience, as the navbar can obstruct content and reduce the visibility of important information.
> 
> ### Describe the solution you'd like
> I would like to propose implementing a feature where the navbar position changes dynamically based on scrolling behavior. Specifically, when scrolling up, the navbar should hide, and when scrolling down, the navbar should be shown. This behavior will provide a better user experience by allowing users to focus on the content while still having access to the navbar for navigation purposes.
> 
> ### Describe alternatives you've considered
> An alternative that has been considered is keeping the navbar fixed in position at all times. However, this alternative does not provide the desired user experience of an unobstructed view of the content during scrolling.
> 
> ### Additional context
> Implementing this feature will require applying appropriate CSS styles to enable dynamic position changes of the navbar. JavaScript or a JavaScript library (such as jQuery) will also be needed to handle scroll events and trigger the navbar position changes. Testing across different browsers and devices will be necessary to ensure consistent functionality.
> 
> ### Requirement/Document
> If there is any document or design that supports this feature proposal, please share it here.

Hey can you plz specify which navbar you are talking about 

as you can see there's no navbar in calc calendar page ass seen on attached SS below 
![image](https://github.com/calcom/cal.com/assets/29349136/8d3a5be4-3d38-40ba-a5ef-9c254010ca63)

and if we talk about landing page of calc 
the navbar is not fixed and well optimized as seen on attached video below 
 

https://github.com/calcom/cal.com/assets/29349136/af3eb19f-9875-445c-92e6-c44579e89cb6

**Comment by PeerRich** [comment]
cannot reproduce this
