### ISSUE TITLE
Bug In Navigation Bar

### ISSUE THREAD

**Issue by sonusharmawevdev** [calcom/cal.com#10171]
In navigation when I click on DOCS link we can't not appear Docs then when I reload window then appear.

![image](https://github.com/calcom/cal.com/assets/113982847/2635a53f-5594-4090-b6d0-29ca0860adbc)

![image](https://github.com/calcom/cal.com/assets/113982847/73c9558d-8fa2-42c9-bdc5-dbb03d1a1826)

https://www.loom.com/share/1989eda6c29c4f47b75441ae647562be

**Comment by sonusharmawevdev** [comment]
Bug In Navigation Bar

**Comment by PeerRich** [comment]
@p6l-richard can you investigate this?

**Comment by p6l-richard** [comment]
> @p6l-richard can you investigate this?

Yes, I'm taking a look today.

**Comment by p6l-richard** [comment]
I deployed a fix yesterday to staging, where it works again:
![CleanShot 2023-07-18 at 10 49 11](https://github.com/calcom/cal.com/assets/18185649/8a120fb0-f6a1-4de0-83ae-7a5bd138b46b)
