### ISSUE TITLE
Bullet Points are not format in the Cal.com v3.1 - Organizations, moving to Discord, embeds & more mail

### ISSUE THREAD

**Issue by akhil27styles** [calcom/cal.com#10176]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Points are not formatted in the email in Cal.com v3.1 - Organizations, moving to Discord, embeds & more

### Mail I got
Received a mail about  Cal.com v3.1 - Organizations, moving to Discord, embeds & more

### Screenshot

![image](https://github.com/calcom/cal.com/assets/52193850/66a58325-6f97-4dc3-aa49-1175a83de038)

here this point is not aligned
 We enabled the new public page on embeds.

**Comment by PeerRich** [comment]
too low priorty but thank you for reporting!
