### ISSUE TITLE
Delete modal style issue for Calendar apps.

### ISSUE THREAD

**Issue by Krishna2323** [calcom/cal.com#10179]
### Issue Summary
The styling for the Calendar app delete modal is broken.

### Steps to Reproduce
1. Delete a calendar app.

### Actual Results
<img width="1710" alt="Monosnap Installed Apps | Cal com 2023-07-16 10-59-06" src="https://github.com/calcom/cal.com/assets/85894871/42483230-c44e-460e-91b4-26a01b32bf74">

### Expected Results
<img width="1710" alt="Monosnap Installed Apps | Cal com 2023-07-16 11-00-03" src="https://github.com/calcom/cal.com/assets/85894871/f7cd18d8-2d72-479f-aeea-9c0c9dda1433">

**Comment by sourabh-shrivastava33** [comment]
I want to work on this issue if it is still open please assign it to me

**Comment by PeerRich** [comment]
@sourabh-shrivastava33 go for it, no need to be assigned

**Comment by sourabh-shrivastava33** [comment]
> @sourabh-shrivastava33 go for it, no need to be assigned

Okay 👍
