### ISSUE TITLE
[CAL-2180] Booking with invalid/unsupported timezones goes through

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#10189]
### Issue Summary

Currently, it is possible for a booking to go through with an unsupported Timezone as we can define unsupported timezone in the Booking API POST request in Timezone, and it goes through. Later, when one attempts to open the [cal.com/bookings](http://cal.com/bookings) page, it would hard crash.

### Steps to Reproduce

1. Create a booking using the API with an unsupported Timezone `eg: America/Pacific`. Note that this isn't listed in the UI, but one can create a booking with this timezone via API
2. Once the booking goes through, open `cal.com/bookings` and that should return in hard crash

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1d164cab-907c-4697-809d-3a84ae4052cb/bccaed23-f587-457e-b06e-c3c4d918b1b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xZDE2NGNhYi05MDdjLTQ2OTctODA5ZC0zYTg0YWU0MDUyY2IvYmNjYWVkMjMtZjU4Ny00NTdlLWIwNmUtYzNjNGQ5MThiMWI5IiwiaWF0IjoxNjg5NTkxNDU3LCJleHAiOjE2ODk2Nzc4NTd9.xbyEjux1lD15d6xr3BkePsmgXEVGHOJlHqGchcG390g)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* The booking goes through even with unsupported Timezone and later crashes in UI

### Expected Results

Ideally,

* we want to be able to parse and confirm that the timezone passed is supported. If not, we should return error and the booking shouldn't go through.
* We should also handle such situations in the UI a bit better, instead of hard crashing. Also, ideally, we should provide a nice mapping somewhere which allows the user to find out what their timezone is in our DB, like the closest supported alternative

### Technical details

* In production

### Evidence

Reported by a couple of users, confirmed that we **do not** currently have ways to handle it in place.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2180](https://linear.app/calcom/issue/CAL-2180/booking-with-invalidunsupported-timezones-goes-through)</sub>

**Comment by jaypitroda12** [comment]
Hi @PeerRich, can you assign someone to review #10209 ?

**Comment by Udit-takkar** [comment]
> We should also handle such situations in the UI a bit better, instead of hard crashing. Also, ideally, we should provide a nice mapping somewhere which allows the user to find out what their timezone is in our DB, like the closest supported alternative

@alishaz-polymath how can we get the closest supported alternative just from "America/Pacific"?

**Comment by alishaz-polymath** [comment]
@Udit-takkar That's a tough one. I'm still trying to figure out what the best way would be. There would need to be a mapping system, but obviously, it might need quite a bit of extensive manual work (unless we can find a registry that handles this for us). Currently looking for such registries. 👀

**Comment by alishaz-polymath** [comment]
Another bit is still left to be fixed
