### ISSUE TITLE
[CAL-2179] Error when organizer tries to reschedule booked seat

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10188]
Created via Threads. See full discussion: [https://threads.com/34507839790](https://threads.com/34507839790)

When organizer tries to reschedule the attendee on a seated event error shows up

![Screenshot 2023-07-17 at 14.20.19.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ad0620a4-ec71-4cb5-a92a-9c55e776ed0a/15a386ee-623a-4cdd-973b-7a1d16173a31?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hZDA2MjBhNC1lYzcxLTRjYjUtYTkyYS05YzU1ZTc3NmVkMGEvMTVhMzg2ZWUtNjIzYS00Y2RkLTk3M2ItN2ExZDE2MTczYTMxIiwiaWF0IjoxNjg5NTk2NTIyLCJleHAiOjE2ODk2ODI5MjJ9.B8dTs8jVtj1UXrOkY9mnJrpKu64KHCiJexHDMx6WRQI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2179](https://linear.app/calcom/issue/CAL-2179/error-when-organizer-tries-to-reschedule-booked-seat)</sub>

**Comment by joeauyeung** [comment]
Issue caused by previous seats regression. Resolved this user's error.
