### ISSUE TITLE
Add discord icon in the place of slack icon.

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#10182]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Add discord icon in the place of slack icon.
![Screenshot 2023-07-14 212341](https://github.com/calcom/cal.com/assets/81948346/df851e24-0d5e-4eb0-8fd9-2cc78e1874d4)

**Comment by tcchawla** [comment]
I think I can work on this. Can you please assign this to me?

**Comment by mayank-sahai** [comment]
@anikdhabal `lucide-react` package is being used for Icons, but it doesn't support the discord icon yet.

**Comment by anikdhabal** [comment]
> @anikdhabal `lucide-react` package is being used for Icons, but it doesn't support the discord icon yet.

Yes , and they are not going to add brand icons. So have to follow any different method.

**Comment by PeerRich** [comment]
feel free to just use an svg. the 404 page already has the icon: https://cal.com/404-page

**Comment by JunedKhan101** [comment]
I'd like to take this up. Kindly assign this to me.

**Comment by tcchawla** [comment]
Hey @PeerRich, Can you assign this to me?
