### ISSUE TITLE
[CAL-2189] change: "Dynamic Collective 60min Event" to "Firstname, Firstname & Firstname"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10194]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2f55963a-68d6-4c72-9d37-fe07224a9fdf/20e500e7-784a-4f13-bcdf-a72763c86267?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yZjU1OTYzYS02OGQ2LTRjNzItOWQzNy1mZTA3MjI0YTlmZGYvMjBlNTAwZTctNzg0YS00ZjEzLWJjZGYtYTcyNzYzYzg2MjY3IiwiaWF0IjoxNjg5NjAzOTcyLCJleHAiOjE2ODk2OTAzNzJ9.5FKr4IN88m4Q4WIlKfFrWNd03p_noqyDjuw-yd9o2E4)

lets change this to include the peoples firstnames instead.

if its 2: "Firstname1 & Firstname2

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/56f04e2d-c4b5-4728-a2c1-236a253a1346/e027681a-bf0d-4dd9-99ab-245271e434e0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81NmYwNGUyZC1jNGI1LTQ3MjgtYTJjMS0yMzZhMjUzYTEzNDYvZTAyNzY4MWEtYmYwZC00ZGQ5LTk5YWItMjQ1MjcxZTQzNGUwIiwiaWF0IjoxNjg5NjA0MTYyLCJleHAiOjE2ODk2OTA1NjJ9.L6kRh2S_U1VYfuSrlvPrW-At4j6TMWpbeM96D6TxmB0)

if its more, it's "Firstname 1, Firstname2 & more"

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7466ee8f-1925-44bb-b2d5-fd62a769d0ea/35876dbf-45da-49fd-b5dc-afb6c50efc7d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83NDY2ZWU4Zi0xOTI1LTQ0YmItYjJkNS1mZDYyYTc2OWQwZWEvMzU4NzZkYmYtNDVkYS00OWZkLWI1ZGMtYWZiNmM1MGVmYzdkIiwiaWF0IjoxNjg5NjA0MTYyLCJleHAiOjE2ODk2OTA1NjJ9.xDaETtHdyF8UMjpsBMYLEaqZ2r1i1h4_mMuOu3Vz_0Y)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2189](https://linear.app/calcom/issue/CAL-2189/change-dynamic-collective-60min-event-to-firstname-firstname-and)</sub>

**Comment by PeerRich** [comment]
i dont think we have firstName so maybe we just do fullName instead

**Comment by AyushGovil** [comment]
I would like to attempt this issue. /attempt #10194.

**Comment by AyushGovil** [comment]
Hey @PeerRich , just to confirm, you want to have the full name marked with blue to the place marked at orange as well?
![image](https://github.com/calcom/cal.com/assets/33975149/1503a553-6fa3-4e4f-b0df-f89646e1ead0)

**Comment by PeerRich** [comment]
> Hey @PeerRich , just to confirm, you want to have the full name marked with blue to the place marked at orange as well? ![image](https://user-images.githubusercontent.com/33975149/253987796-1503a553-6fa3-4e4f-b0df-f89646e1ead0.png)

the way I outlined in the ticket

**Comment by puru-khedre** [comment]
@PeerRich how can i reproduce on my side.
