### ISSUE TITLE
[CAL-2191] Event type returns 404 with slug mismatch

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#10197]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Event type's public page returns 404 as there is a slug mismatch in a very specific situation. When you have "-" enveloped between two white spaces, enveloped between two words, it converts to "---" in the public link formation where as the slug itself remains with "-".
So, for example, if we create an event type with slug `hello - there`, it converts to `cal.com/johndoe/hello---there` and the slug instead remains `hello-there`, so it returns 404 either way.

### Steps to Reproduce

1. create an event type with slug `hello - there`
2. try to access the public page
3. look at the 404 being returned and take note of the URL versus what the slug shows in the event-type settings page

### Actual Results

  - Slug vs public page URL mismatch

### Expected Results

  - If we enter the same value as the slug of an event type in the public page, it should be accessible and not return 404

### Evidence
 
  - Client came up with the issue described above and the issue was resolved as soon as the event type's slug was manually edited to ensure the slug matches the booking URL.

<sub>[CAL-2191](https://linear.app/calcom/issue/CAL-2191/event-type-returns-404-with-slug-mismatch)</sub>

**Comment by fancymithun** [comment]
Hi @alishaz-polymath I tried with both slugs in prod "hello-there" and "hello---there" both worked fine for me.
![cal-issue-2](https://github.com/calcom/cal.com/assets/68776547/c60a9f1b-7e55-49f8-935f-ef4f71c36bb2)

**Comment by ujwalkumar1995** [comment]
Hey @alishaz-polymath 
I am unable to replicate this issue. Could you please share some video evidence if possible?

**Comment by alishaz-polymath** [comment]
Closing due to lack of replicability
