### ISSUE TITLE
UI from modal windows look like out of the correct place

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10202]
### Issue Summary

This is a UI issue. The position of the text and buttons for the modal windows look out of the correct place. Check the screenshots attached to see it better.

### Steps to Reproduce

1. Login using an incognito mode window
2. Walkthrough where these notifications can appear. E.g.: waiting for the `Update timezone` notification or going to disband a team
3. Observe the buttons

### Actual Results

  - Buttons and text are out of the correct place

### Expected Results

  - Buttons and text should be better positioned

### Technical details

  - Tested on `app.cal.dev`
  - Tested on: Firefox (v115.0.2) and Chrome (v114.0.5735.199)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/32e09b24-305a-4a46-b0d1-64cabd3b8817)

![image](https://github.com/calcom/cal.com/assets/10250819/83d1ea17-c3e6-4165-94b0-f81847ec0346)

![image](https://github.com/calcom/cal.com/assets/10250819/a5c564a5-42f0-4cc6-8e0c-9a11255c9af2)

![image](https://github.com/calcom/cal.com/assets/10250819/95c17ed9-cdc0-4002-8c88-f4be304f0833)

**Comment by JunedKhan101** [comment]
@ericrommel This seems like a good issue to kickstart contributing to Cal. I'd like to take this up, kindly assign this issue to me 😄

**Comment by devanshuc** [comment]
Hi @ericrommel,
I came across issue #10202 and I'm interested in contributing to it. I've reviewed the problem and screenshots, and I believe I can help fix the mispositioned buttons and text on the modal windows.
Could you please assign this task to me? I'm eager to start working on it.
