### ISSUE TITLE
No length limit for duration causes error 500

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10205]
### Issue Summary

When setting a duration, if the number is higher than 899999999 (INT4 - 32-bit signed integer), it causes error 500 from the server. From the duplicate event type option, it shows a nice notification but from the event type configuration, it shows the DB error happened from the server.

### Steps to Reproduce

1. In an Event type, click on the `Duplicate` option
2. Set `9000000000` as the length value
3. Click on the `Continue` button
4. See the notification error
5. Save it with a valid number, like 15
6. From the Event Type configuration, set the duration to `9000000000`
7. Click on the `Save` button
8. See the notification

### Actual Results

  - An error 500 is thrown on both pages but in the Event type configuration page, the notification is the error from the server

### Expected Results

  - A nice notification should be shown. Ideally, both fields should have a value limitation that can be typed.

### Technical details

  - Tested on `app.cal.dev`
  - Tested on: Firefox (v115.0.2) and Chrome (v114.0.5735.199)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/a52d0bc8-a131-4e32-adbe-4fd3e110059b)

![image](https://github.com/calcom/cal.com/assets/10250819/804ed2a4-4948-4302-8ea0-ee8719e6f817)

**Comment by rishitashaw** [comment]
I'd love to tackle the duration issue and propose a nifty client-side solution! Can you please assign this to me? I'll make sure to implement validation and error handling to smoothen the user experience.

Thanks
Rishita
