### ISSUE TITLE
App is crashing when a recurring event type is set with negative occurrences

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#10204]
### Issue Summary

The recurring event types are accepting negative values as the number of occurrences. This situation causes the app to crash. Same if you type a big number.

### Steps to Reproduce

1. Create an Event-type and set a Recurring for that
2. Open a preview for that event
3. Write `-1` or use the arrow down from the component to change to a negative number
4. Select an available date
5. Select an available time
6. Observe

### Actual Results

  - Recurring event type is accepting dash and plus sign. It allows the user to set a negative value and it causes a crash

### Expected Results

  - The occurrences field should only accept numbers and cannot be more than the maximum set in the configuration.

### Technical details

  - Tested on `app.cal.dev`
  - Tested on: Firefox (v115.0.2) and Chrome (v114.0.5735.199)
 
### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/1849858e-a87b-4929-b8ca-e11e4ea435f1)

**Comment by Ruchir-D** [comment]
I would like to work on it. @PeerRich  can you assign it to me
