### ISSUE TITLE
[CAL-2197] No feedback on button when saving availability

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10216]
The button should show a loading state the same as when saving an event type.

Current behaviour:
https://github.com/calcom/cal.com/assets/4536123/8314e16e-75f9-4249-a184-8547a7644067

[View button in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=309%3A42062&mode=dev)

<sub>[CAL-2197](https://linear.app/calcom/issue/CAL-2197/no-feedback-on-button-when-saving-availability)</sub>

**Comment by yashchaddha** [comment]
Hi, I would like to contribute on this, Can i please get assigned to it?
