### ISSUE TITLE
Team availability shows only to the member owning it

### ISSUE THREAD

**Issue by marcociarrocca** [calcom/cal.com#10215]
### Issue Summary
I am part of a team. Another member of the team sets an availability for a team's event, and it correctly shows to them. When I view the same event's availability, I cannot see/edit the schedule, because the schedule "is theirs".

### Steps to Reproduce
1. Go to "Availability" in the left side-menu
2. Create a schedule that will be set to the event
3. Go to "Event Types" in the left side-menu
4. Create a new team event
5. Assign the created schedule to the event
6. Team members that don't own the schedule cannot edit or even view it

We expect team members to be able to view and edit the team's schedule, not just the creator of the schedule. In this case, since it's a custom schedule for a team's event, some degree of control sharing is required.

### Actual Results
Schedules are personal, and only the owner is allowed to view/edit them.

### Expected Results
Teams should have schedules editable by more than one member of the team.

### Technical details
Tested with Safari 16.3, Cal.com versions 2.9.2 and 3.1.0

### Evidence
Schedule owner's view
![Here is what the creator sees](https://github.com/calcom/cal.com/assets/25442454/d68dbc47-7ed2-4707-a0de-ad31815b3f0b)

Other team members' view
<img width="448" alt="Here is what I see" src="https://github.com/calcom/cal.com/assets/25442454/35741c56-dd6c-43e0-82e7-f580cf732feb">

**Comment by marcociarrocca** [comment]
The issue is not fixed yet.
Thank you for the improvements, I can now see the availability schedule, but I cannot edit it.
I am an admin of the team.

This is what I see
<img width="1437" alt="Screenshot 2023-09-07 at 11 17 24" src="https://github.com/calcom/cal.com/assets/25442454/3af1191a-9af6-4786-8f43-17bf6d782e93">

This is what the creator of the schedule sees
![Clipboard%20-%20September%207,%202023%2011_22%20AM](https://github.com/calcom/cal.com/assets/25442454/37e0ddf1-fdb5-4dd7-8f71-30a61d291891)

**Comment by CarinaWolli** [comment]
@ciaranha Do we want the admin to be able to edit that schedule? This schedule is another user's schedule that may also used for other event types

**Comment by kerberjg** [comment]
It would be very helpful to have "team-managed" schedules though. Very often one of us is just not in the office or at the computer so having someone else be authorized to managed that as a team admin would be nice ✨

**Comment by CarinaWolli** [comment]
> It would be very helpful to have "team-managed" schedules though. Very often one of us is just not in the office or at the computer so having someone else be authorized to managed that as a team admin would be nice ✨

@kerberjg Agree, time-wide schedules would be nice. As a team admin, you could also impersonate the user and then you can change the schedule. That could be a temporary solution if you know whose schedule it is
