### ISSUE TITLE
[CAL-2198] Private git submodule inside monorepo causing error when we aren't careful to see what's in yarn.lock

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10217]
This is how it happens

* A contributor checkouts the code
* He doesn't have access to auth, website, console
* He runs `yarn` locally in three monorepo on his system that doesn't have the above folders and thus 3 package.json files are missing
* Now, `yarn` ends up removing these 3 packages as well as their dependencies.
* When a core contributor(who has access to the private repo) and that is checked out locally on his machine, runs `yarn dev` or any other `yarn` command, he would see an error like following. It basically says that there is apps/auth with package.json but that isn't there in yarn.lock

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/90ed4f29-badb-4c17-8983-c33e91a8f31f/7236a044-500d-4adc-bad6-4cba20b190f9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MGVkNGYyOS1iYWRiLTRjMTctODk4My1jMzNlOTFhOGYzMWYvNzIzNmEwNDQtNTAwZC00YWRjLWJhZDYtNGNiYTIwYjE5MGY5IiwiaWF0IjoxNjg5Njc1MTcyLCJleHAiOjE2ODk3NjE1NzJ9.OBZtkQ9Bws2x4UEukBH2RV0rLCQUAelAT0vC9yTgT0o)

* The only way to solve it is that he run yarn and commit the updated yarn.lock  and solve it for others too.

I think that we should move auth, website, console outside the monorepo into their own repositories. These 3 being apps, aren't going to be a depenendency of each other and they are just going to need some packages from @calcom monorepo.

To allow an app like console, to be able to access to monorepo packages, we can maybe use file: URI in package.json to refer to local dependencies and use tsconfig compilerOptions path to map the packages to locally checked out monorepo
<img width="682" alt="Screenshot 2023-07-18 at 3 41 21 PM" src="[https://github.com/calcom/cal.com/assets/1780212/af1abb3e-4f9f-4a5a-aa4a-f4f7b7c50693](https://github.com/calcom/cal.com/assets/1780212/af1abb3e-4f9f-4a5a-aa4a-f4f7b7c50693)">

We can also go the ideal way where we publish all the packages in monorepo to npm and then use those packages.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2198](https://linear.app/calcom/issue/CAL-2198/private-git-submodule-inside-monorepo-causing-error-when-we-arent)</sub>

**Comment by zomars** [comment]
Added a [new entry to our handbook](https://handbook.cal.com/engineering/codebase/keeping-the-lock-file-in-sync) hoping to clear things up. 🙏🏽
