### ISSUE TITLE
[CAL-2196] location icon missing dark mode

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10213]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4d7476b3-85a2-4e92-8adc-6fd848f88ebe/95c0813d-beea-4e3c-a04a-2e42c5289aee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80ZDc0NzZiMy04NWEyLTRlOTItOGFkYy02ZmQ4NDhmODhlYmUvOTVjMDgxM2QtYmVlYS00ZTNjLWEwNGEtMmU0MmM1Mjg5YWVlIiwiaWF0IjoxNjg5NjcxMjAyLCJleHAiOjE2ODk3NTc2MDJ9.LAB3qPnFWTZB_pI4Ix5eIh97BTmbLm_SXgw3UqRQRfY)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2196](https://linear.app/calcom/issue/CAL-2196/location-icon-missing-dark-mode)</sub>

**Comment by ahirhiten06** [comment]
sir pls provide how to reproduce this

**Comment by gitstart-calcom** [comment]
Hi @PeerRich , we have fixed this issue in #9993  

<img width="402" alt="image" src="https://github.com/calcom/cal.com/assets/121884634/32f64aa4-6e73-48b1-a5cd-acac54e8777d">

**Comment by PeerRich** [comment]
> Hi @PeerRich , we have fixed this issue in #9993

@gitstart-calcom awesome!
