### ISSUE TITLE
Prefill Username + Email in booking page when logged in. 

### ISSUE THREAD

**Issue by paul-siteway** [calcom/cal.com#10227]
### Is your proposal related to a problem?

i am cal.com user named paul and I sometimes schedule meeting with my coworkers with dynamic booking links like paul+peer+peter. 
On the last screen, i am asked for my name and my email. 

cal.com should know that i am logged in as "paul" and prefill my data or don't ask for a name and email. 
I might ask if I am scheduling for someone else and offer to change the data. 

### Describe the solution you'd like

Maybe like so: 
![Schedule](https://github.com/calcom/cal.com/assets/3603487/df0975f0-aa65-4d0b-abdb-e01a4ef9dd68)

**Comment by kharbandaashu** [comment]
Hey @paul-siteway , I would like to work on this. Please assign to me. Could you please share this design as well ?
