### ISSUE TITLE
[CAL-2204] RFC: mandatory email reminder for attendees with @gmail.com

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10247]
due to googles new privacy policy, events are not automatically added for @gmail.com emails. They first need to opt-in "I know this person" before getting email invites.

I bet there are people missing events because of this.

We should send a mandatory email reminder to attendees with @gmail.com to be extra safe, maybe 15 min before the meeting? Or one hour? Or both?

<sub>[CAL-2204](https://linear.app/calcom/issue/CAL-2204/rfc-mandatory-email-reminder-for-attendees-with-gmailcom)</sub>

**Comment by Himanshu4776** [comment]
Hey @PeerRich , Can I work on this feature. Please assign it to me.
