### ISSUE TITLE
"Awaiting approval" emails sent for unpaid bookings

### ISSUE THREAD

**Issue by kcrimi** [calcom/cal.com#10253]
### Issue Summary

When a booking is not completed due to the booker abandoning the flow before paying, an email saying "**An event is still waiting for your approval**" is sent to the organizer despite the booking not actually being subject to approval.

### Steps to Reproduce

1. As user A: make a paid event with no requirement for confirmation
2. As user B, fill out the form in booking flow until payment screen
3. As user B, abandon flow and do not paid, resulting in `pending payment` booking
4. As user A, verify the booking shows in Bookings tab and is unconfirmed due to lack of payment
5. Wait for a while (unknown time)

### Actual Results

- User A receives an email unknown amount of time later saying **An event is still waiting for your approval**, making it seem like action is needed from User A

### Expected Results

- Booking should pass without being confirmed
- User A should not be alerted to the booking since it is unconfirmed

### Technical details

- n/a.

### Evidence

![Screenshot_20230719-182909](https://github.com/calcom/cal.com/assets/2559359/cfa68b0e-9aec-4ff4-8066-9bdf06c5275b)

**Comment by PeerRich** [comment]
i agree about this. happened to me before too, bit confusing. doesn't negatively affect the product but indeed confuses.

@zomars @alannnc we should change this. lets not send "requires confirmation" when indeed the user has to pay

**Comment by nicktrn** [comment]
Confirming the event via the link in the email removes the unconfirmed badge from the dashboard. The pending payment badge remains. No emails are sent out.
