### ISSUE TITLE
[CAL-2205] ui: more brand color for calendar view

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10250]
## before

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d029a9ba-42cb-45ac-883b-8e06f9bdaa16/cd8ba5a8-d438-43fd-adcb-849e362cd9b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kMDI5YTliYS00MmNiLTQ1YWMtODgzYi04ZTA2ZjliZGFhMTYvY2Q4YmE1YTgtZDQzOC00M2ZkLWFkY2ItODQ5ZTM2MmNkOWIyIiwiaWF0IjoxNjg5NzY5MzYyLCJleHAiOjE2ODk4NTU3NjJ9.oXrR-u8vBc0AJku936pj5WnTRpID1-IYsllzzYuyLdk)

## after

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/82bc26f8-b95c-49eb-a554-304696b6972d/82e6d3f8-8f20-433b-ade0-dce931a16c43?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84MmJjMjZmOC1iOTVjLTQ5ZWItYTU1NC0zMDQ2OTZiNjk3MmQvODJlNmQzZjgtOGYyMC00MzNiLWFkZTAtZGNlOTMxYTE2YzQzIiwiaWF0IjoxNjg5NzY5MzYyLCJleHAiOjE2ODk4NTU3NjJ9.BEgnA_TmBY879G4vhtItTKzqiu5ciLrSOi75XHVIWcY)

waiting for @Jaibles approval

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2205](https://linear.app/calcom/issue/CAL-2205/ui-more-brand-color-for-calendar-view)</sub>

**Comment by Jaibles** [comment]
Looks good to me. I probably wouldn't brand the duration selector. But no strong objections.

**Comment by JunedKhan101** [comment]
Hey, This seems like a good issue to kickstart contributing, Kindly assign to me if its available to work on.

**Comment by PeerRich** [comment]
@JunedKhan101 no need to be assigned, go for it
