### ISSUE TITLE
UI breaks in Desktop App

### ISSUE THREAD

**Issue by amirfakhrullah** [calcom/cal.com#10266]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

UI Breaks in Desktop app

### Steps to Reproduce

1. Open the desktop app
2. Login
3. See the top of the sidebar

### Actual Results

<img width="243" alt="image" src="https://github.com/calcom/cal.com/assets/73758525/a470e940-9c0b-4538-a152-82c3b950a554">

### Expected Results

Should have some gaps on top of the avatar

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by PeerRich** [comment]
i think if you update your client it should be fine
