### ISSUE TITLE
[CAL-2210] Filtering event types by team throws an error

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10268]
Filtering event types by Team throws an error - [https://app.birdeatsbug.com/sessions/UYy6TqrCAXWij2oz2vZFiBGRf76ZSEErf-x8Q7M9gotY](https://app.birdeatsbug.com/sessions/UYy6TqrCAXWij2oz2vZFiBGRf76ZSEErf-x8Q7M9gotY) [https://app.birdeatsbug.com/sessions/UYy6TqrCAXWij2oz2vZFiBGRf76ZSEErf-x8Q7M9gotY](https://app.birdeatsbug.com/sessions/UYy6TqrCAXWij2oz2vZFiBGRf76ZSEErf-x8Q7M9gotY)

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=3ce3327a-138e-40f3-943d-d7c4b45b2e9a](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=3ce3327a-138e-40f3-943d-d7c4b45b2e9a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2210](https://linear.app/calcom/issue/CAL-2210/filtering-event-types-by-team-throws-an-error)</sub>

**Comment by Udit-takkar** [comment]
* Not able to reproduce locally

![Screenshot 2023-07-23 at 1.50.23 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/62ec6a2f-9e9d-4fcc-b658-4c995df213ad/d6e68103-3565-418a-936e-b21cbb86de08)

But getting 500 on production for some reason. Filter by all, user id is working fine
