### ISSUE TITLE
Booking failed when zoom fails

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#1026]
### Issue Summary

When creating a video meeting, the booking may fail if the Zoom token is expired. On the user side it just show a "Booking failed" error. But the booking is actually created.

### Steps to Reproduce

1. You need an expired Zoom token (IDK how to reproduce this)
2. Try to book an event that needs confirmation with Zoom as location
3. It will display an error.
4. On the dashboard the booking will be pending.

**Comment by PeerRich** [comment]
we have better alerts now and fall back to cal video
