### ISSUE TITLE
[CAL-2213] fix: empty screen full width

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10277]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a1e8f55b-3570-4b45-9156-0cfa83ab373e/d4384f26-8ff9-4d2f-9685-a45a83e234e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMWU4ZjU1Yi0zNTcwLTRiNDUtOTE1Ni0wY2ZhODNhYjM3M2UvZDQzODRmMjYtOGZmOS00ZDJmLTk2ODUtYTQ1YTgzZTIzNGU5IiwiaWF0IjoxNjg5ODYxNzYwLCJleHAiOjE2ODk5NDgxNjB9.a52EJRqDMQtpbCLlmVakNhpqitsGSJ1JZRZnEvOH9_0)

after

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/72abc098-5c07-4104-9f35-94e463cca1f2/ab5be2e5-b868-488b-b4aa-bdde4fbd8f78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83MmFiYzA5OC01YzA3LTQxMDQtOWYzNS05NGU0NjNjY2ExZjIvYWI1YmUyZTUtYjg2OC00ODhiLWI0YWEtYmRkZTRmYmQ4Zjc4IiwiaWF0IjoxNjg5ODYxNzYwLCJleHAiOjE2ODk5NDgxNjB9.c5osUDq71dlf6R4URhN0Ldl71SwiiF0vUkFJ_zxLf2E)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2213](https://linear.app/calcom/issue/CAL-2213/fix-empty-screen-full-width)</sub>

**Comment by vats147** [comment]
@PeerRich Can i work on this issue??
