### ISSUE TITLE
When switching between months put me on 1st of month - desired?

### ISSUE THREAD

**Issue by yangwao** [calcom/cal.com#10295]
### Issue Summary

Hey, I'm testing this from the perspective of a user, and I'm a bit confused about what's happening when I want to book and looking the right time to suite me going to next month and back. 

### Steps to Reproduce

1. Go to https://cal.com/yangwao/25min
2. Click on next month 
3. Click on previous months

When I'm looking for dates I see available slots for next month, but when I click back, shows me all booked at first sight, however, I need to click on the first available date to see slots

### Actual Results

- Shows "All booked", even there are available days in that month

### Expected Results

- I would like to see choose the first available slot from previous months

### Evidence

https://github.com/calcom/cal.com/assets/5887929/aa3fe7c3-70cb-45c0-b86b-102ffc10cf46

**Comment by emrysal** [comment]
You're right, it should start at the first available day.

**Comment by MehulZR** [comment]
Is this behaivour desirable? 
- If the *selected date* is available for other months assign that and if not assign the first available date?
- If the user hasn't selected any date, user can change the month(+1, -1) without automatically assign the first available date?

https://github.com/calcom/cal.com/assets/86384652/73900760-afa3-4449-ae3a-4cd8b7ea6750
