### ISSUE TITLE
Erroe ESlint / Rule prettier/prettier

### ISSUE THREAD

**Issue by MyPsyOnline** [calcom/cal.com#10292]
Hello,

i have an error when building fresh install :

### Issue Summary
Fresh install from github version 3.1.4
I'm able to access at webinterface when i'm on the stage "yarn dev"

But when i do : yarn build, i have this error : 

`@calcom/web:build: - error ESLint: Cannot read properties of undefined (reading 'buildError') Occurred while linting /home/debian/cal.com/apps/web/components/apps/App.tsx:1 Rule: "prettier/prettier"`

### Actual Results

I'm stucked as yarn build doesn't success

### Technical details

- nodejs version 18.16.1

**Comment by PeerRich** [comment]
cant reproduce. 

i can run yarn build and yarn dev just fine with 3.1.4

**Comment by MyPsyOnline** [comment]
Thanks for this answer.
I reproduce the same error when i try to update an actual running version of cal.com.

is it possible That this issue is specific to my configuration ?
In this case, any idea to guide me to a solution ?

**Comment by nicktrn** [comment]
I've had the same error before, but could still proceed with the build. Maybe try to run with `CI=1 yarn build`

**Comment by MyPsyOnline** [comment]
> I've had the same error before, but could still proceed with the build. Maybe try to run with `CI=1 yarn build`

Yes, Build has ending with success  !
Thank you so much !!
