### ISSUE TITLE
[CAL-2214] UI: Tooltips should not be branded

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10291]
Currently, tooltips are taking on the brand color.
<img width="1093" alt="CleanShot 2023-07-21 at 08 41 50@2x" src="https://github.com/calcom/cal.com/assets/4536123/22bc1127-4b7a-43f1-8aba-69419085c722">

They should keep the standard tokens with `bg-inverted` `content-inverted`
<img width="1494" alt="CleanShot 2023-07-21 at 08 52 28@2x" src="https://github.com/calcom/cal.com/assets/4536123/cf44e21e-0404-4113-9f1c-b394fee91f45">

**View in Figma**

<sub>[CAL-2214](https://linear.app/calcom/issue/CAL-2214/ui-tooltips-should-not-be-branded)</sub>

**Comment by bhargavagonugunta** [comment]
hi @Jaibles  i made changes please look in to it
` className="popover-content slideInBottom border-5 content-inverted bg-inverted text-inverted border-subtle rounded-md p-3 text-sm shadow-sm">
          {times.map((time) => (
            <span className="mt-2 block first:mt-0" key={time.timezone}>
              <span className="inline-flex align-baseline">
                {time.startTime} - {time.endTime}
                {(time.isNextDay || time.isPreviousDay) && (
                  <span className="text-medium ml-2 inline-flex h-5 w-5 items-center justify-center rounded-full bg-gray-700 text-[10px]">
                    {time.isNextDay ? "+1" : "-1"}
                  </span>
                )}
              </span>`

**Comment by MehulZR** [comment]
After changing the background color from *Brand* to *Inverted*

There is hard coded value of gray for the *+1* and *-1*

Should I use the default background color  and text color for those or you will prefer it as it is?

Left: Hard-coded value (currently in use)
Right: Default background and text color

![image](https://github.com/calcom/cal.com/assets/86384652/eb2d0a2a-54e7-490d-ba16-b8ef2d798182)

**Comment by bhargavtenali** [comment]
@Jaibles Fixed the above issue with very minor code change 😋
PR #10327
