### ISSUE TITLE
Back button on blog post goes to 404

### ISSUE THREAD

**Issue by yangwao** [calcom/cal.com#10294]
### Issue Summary

Back button on blog post goes to 404

### Steps to Reproduce

1. go to https://cal.com/blog/longevity
2. Clicked on "back"
3. 404

### Actual Results

- I see 404

### Expected Results

- I expected took me to list of blog posts page

### Evidence

https://github.com/calcom/cal.com/assets/5887929/e4a4773a-2e97-48b6-91ba-416bec808daa

**Comment by PeerRich** [comment]
interesting, that is regressing. investigating

**Comment by p6l-richard** [comment]
I have a hunch about where this stems from. 

Investigating once I get back to computer later today.

**Comment by p6l-richard** [comment]
Thanks for flagging this @yangwao

We've merged a fix which should be deployed shortly.

**Comment by p6l-richard** [comment]
Working again. 👍
