### ISSUE TITLE
Rate limiting issues on production

### ISSUE THREAD

**Issue by jsolly** [calcom/cal.com#10304]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce
1. Visit cal.com in a browser and login
2. Click on "Go to App"
Rate limited
![image](https://github.com/calcom/cal.com/assets/9572232/fe1c9126-3fde-4427-abe5-3aa7dd31878a)

![image](https://github.com/calcom/cal.com/assets/9572232/8ff55230-46a5-4e25-a43e-0de87ed7eb7a)

### Technical details
- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
[app.cal.com-1689971370749.log](https://github.com/calcom/cal.com/files/12134504/app.cal.com-1689971370749.log)

### Evidence
I did a 'save as' in my browser console and attached here. Seems like a pretty big issue, so you probably know about it.

**Comment by PeerRich** [comment]
resolved
