### ISSUE TITLE
[CAL-2217] Org onboarding: Upload avatar modal UI issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10309]
The position of the buttons in the modal should follow our DS.

Currently

![CleanShot 2023-07-22 at 10.17.11@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bccf02ce-07b0-4f75-beac-da94f3718404/c12e5921-beab-480d-a7a8-f4bc582dfcf7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iY2NmMDJjZS0wN2IwLTRmNzUtYmVhYy1kYTk0ZjM3MTg0MDQvYzEyZTU5MjEtYmVhYi00ODBkLWE3YTgtZjRiYzU4MmRmY2Y3IiwiaWF0IjoxNjkwMDE3NTQ2LCJleHAiOjE2OTAxMDM5NDZ9.mho3O5eIajNsYKhpn4UIAS7NBiaHe0d2g3NHSLxNyxk)

Should be

![CleanShot 2023-07-22 at 10.18.34@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c21fd47d-b586-48ec-b437-dc79b087ee5b/8a526e96-0846-43da-a186-0a6620d92c83?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jMjFmZDQ3ZC1iNTg2LTQ4ZWMtYjQzNy1kYzc5YjA4N2VlNWIvOGE1MjZlOTYtMDg0Ni00M2RhLWExODYtMGE2NjIwZDkyYzgzIiwiaWF0IjoxNjkwMDE3NTQ2LCJleHAiOjE2OTAxMDM5NDZ9.mSKuHfYNAXEJr-rlw41IaN06LTTG_wJSbqyBZ-KItpc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2217](https://linear.app/calcom/issue/CAL-2217/org-onboarding-upload-avatar-modal-ui-issues)</sub>

**Comment by fancymithun** [comment]
Hi @Jaibles and @Udit-takkar 

I have added margin bottom 16px from those save and cancel buttons and looks like this. Please verify

![cal-profile](https://github.com/calcom/cal.com/assets/68776547/cce13019-98f9-49de-ad5c-a0770bffd68a)

**Comment by Udit-takkar** [comment]
@fancymithun you opened the PR on your forked repo

**Comment by fancymithun** [comment]
> @fancymithun you opened the PR on your forked repo

@Udit-takkar Yes I forked main cal.com from my account🙂
