### ISSUE TITLE
Add a 'Remove all active sessions' button

### ISSUE THREAD

**Issue by ConnorGargano** [calcom/cal.com#10301]
Add a 'Remove all active sessions' button.

**Comment by PeerRich** [comment]
where?

**Comment by PeerRich** [comment]
how important is this? who is asking for this

**Comment by ConnorGargano** [comment]
On a security stand point, it gives the user added security. It was just a thought.

If added, somewhere like https://app.cal.com/settings/my-account/profile or under "Security" tab.
