### ISSUE TITLE
[CAL-2221] Orgs: Invited members to team, don't see them in Members area

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10312]
![CleanShot 2023-07-22 at 11.07.05@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/523414fe-eea4-4d8b-a3e9-a4bedf4be94e/115b9225-7e41-486b-9764-9ae38075452c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81MjM0MTRmZS1lZWE0LTRkOGItYTNlOS1hNGJlZGY0YmU5NGUvMTE1YjkyMjUtN2U0MS00ODZiLTk3NjQtOWFlMzgwNzU0NTJjIiwiaWF0IjoxNjkwMDIwNjk4LCJleHAiOjE2OTAxMDcwOTh9.BaxnArWnuSMhJ3_HELJOsAJcQBpG_ww93J1IVruk6dA)

Here's the invited users

![CleanShot 2023-07-22 at 11.11.28@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/97ffc435-cbf8-4556-b581-94ba196e8638/5a2bc5ef-cc7a-40d5-9093-29e82c5cc2c0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85N2ZmYzQzNS1jYmY4LTQ1NTYtYjU4MS05NGJhMTk2ZTg2MzgvNWEyYmM1ZWYtY2M3YS00MGQ1LTkwOTMtMjllODJjNWNjMmMwIiwiaWF0IjoxNjkwMDIwNjk4LCJleHAiOjE2OTAxMDcwOTh9.dp2lQgWb473HqXK-\_EqcTsvUbqIlNisj6eHxUavrWFM)

![CleanShot 2023-07-22 at 11.10.12@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/67b5590c-0ff0-493d-9f75-db68e743b8ec/7b18b4f5-708f-4bd9-8a68-7c0f67d00209?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82N2I1NTkwYy0wZmYwLTQ5M2QtOWY3NS1kYjY4ZTc0M2I4ZWMvN2IxOGI0ZjUtNzA4Zi00YmQ5LThhNjgtN2MwZjY3ZDAwMjA5IiwiaWF0IjoxNjkwMDIwNjk4LCJleHAiOjE2OTAxMDcwOTh9.IP4dc0t-hLGemMgpOByY6JRZ254DKM-s9kX5oMBwdD0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2221](https://linear.app/calcom/issue/CAL-2221/orgs-invited-members-to-team-dont-see-them-in-members-area)</sub>

**Comment by sean-brydon** [comment]
Fixed: https://github.com/calcom/cal.com/pull/10340
