### ISSUE TITLE
[CAL-2225] Organizations: Managed Event Type view has no "Event setup" Tab

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10314]
![CleanShot 2023-07-22 at 11.31.07@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2bafd44d-34be-4a88-8b15-f38967a69674/2d146b0d-6c14-473f-af6c-27a04f1b9523?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yYmFmZDQ0ZC0zNGJlLTRhODgtOGIxNS1mMzg5NjdhNjk2NzQvMmQxNDZiMGQtNmMxNC00NzNmLWFmNmMtMjdhMDRmMWI5NTIzIiwiaWF0IjoxNjkwMDIxOTQyLCJleHAiOjE2OTAxMDgzNDJ9.gA0TIxoxB0RNRGU0mR69xHQgJTQsj01i-vksKHHoG_Y)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2225](https://linear.app/calcom/issue/CAL-2225/organizations-managed-event-type-view-has-no-event-setup-tab)</sub>

**Comment by Hs809** [comment]
hi @Jaibles, I can see clearly the Event setup Tab at Managed Event Type view as shown in the below ss. can you give me the steps to reproduce this issue? Thanks 
![image](https://github.com/calcom/cal.com/assets/62794768/4416f418-f75a-4da5-976a-38cbc6b228e8)
