### ISSUE TITLE
[CAL-2279] Round robin assignment fails to respect availability

### ISSUE THREAD

**Issue by madppiper** [calcom/cal.com#10315]
### Issue Summary

In a local team we have a group of 4 people, out of which one works only monday-wednesday. All are connected with google calendar. We set up a team event and  auto-assign available slots per round robin method. Even though one of the team members is only available from mon-wed, clients still managed to book the timeslot with her. The timeslot also remained available even as all 4 people were booked, leading to double-bookings.

This does not seem to be a consistent bug, but could be reproduced consistently on some of the machines - others failed to recreate the issue.

### Steps to Reproduce

1. Set up a team with 3-4 people
2. Adjust each profile so that most are available throughout the week, but make sure that one of the profiles is unavailable on at least one of the days
3. Book a specific timeslot over and over until it has been booked at least 3 times.
4. On the fourth time, validate that the timeslot is unavailable. Check that the unavailable person does not receive a calendar invite

### Actual Results

* The work-hours are not respected for all team members
* Timeslots remain open even when there was noone available to assign to
* Double-bookings of some of the members

### Expected Results

* work-hours should be respected

### Technical details

* This was reproduced on Chrome - failed to reproduce on Edge
* could be reproduced on 3.1.3 and 3.0.15

### Evidence

* a pic showing all 4 people receiving invites & double bookings

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2bc15d60-0323-463d-9e39-27b61e70cb10/a340a15e-5f3d-49ca-b5ac-4f50d659cd8c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yYmMxNWQ2MC0wMzIzLTQ2M2QtOWUzOS0yN2I2MWU3MGNiMTAvYTM0MGExNWUtNWYzZC00OWNhLWI1YWMtNGY1MGQ2NTljZDhjIiwiaWF0IjoxNjkwODg4OTgyLCJleHAiOjE2OTA5NzUzODJ9.LBPTeKs1_SBkf4Z34jWz99dgapyL6YXqEZ140IuN8v4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2279](https://linear.app/calcom/issue/CAL-2279/round-robin-assignment-fails-to-respect-availability)</sub>

**Comment by sikehish** [comment]
Yup, makes sense. Also, how can I reproduce the same error on my machine without having to pay 60$ to publish my team to figure out the solution?

**Comment by emrysal** [comment]
I'm looking into this; the logic is based on least recently booked, so it is indeed not random. Note that it is not randomised at this moment; added a ticket for this; https://github.com/calcom/cal.com/issues/10339

@sikehish the only way to do this for free is to self host cal.com and enable team features; for developer use this is free so you can make teams as long as you don't use it for commercial purposes.

**Comment by madppiper** [comment]
> 

I locally set it up with the community edition, so should be possible, yes. 

Try to: 

1. set up a new team
2. add users to the team (unlike the global users panel, you can add users to a team without requiring the license) - impersonate the team, go to the teams dashboard and add the users from there
3. For each user, set the availability (make sure one is not available on all the days) in their accounts (you can impersonate each user as an admin)
4. Impersonate the team again, create a round robin event
5. go through the steps described in the ticket description

**Comment by sikehish** [comment]
I'm facing a problem with google calendar unfortunately on my local machine. Trying to fix it

**Comment by sikehish** [comment]
Update: I couldn't reproduce the problem, but Ive discovered another problem. Ive taken 4 team members(just the way you've considered 4 members) with one member working from Monday to Wednesday while the rest are available throughout the week. But the member who's working from Monday to Wednesday is not being assigned any event. Ive created 5 events and none of the events were being allocated to the member working from Monday to Wednesday.  This is resulting in other members being overworked while one member isn't allocated any event
