### ISSUE TITLE
App-Store-CLI Error: 'cp' Command Not Supported on Windows Environment

### ISSUE THREAD

**Issue by vachmara** [calcom/cal.com#10324]
### Issue Summary

When attempting to create an app with the App-Store-CLI on a Windows environment, an error is encountered due to the 'cp' command not being recognized as an internal or external command, executable program, or batch file. This issue arises specifically during the copying of files using the 'cp' command within the App-Store-CLI process.

### Steps to Reproduce

1. Run the App-Store-CLI on a Windows environment.
2. Attempt to create an app using the 'basic' template.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

```bash
Error: Command failed: cp -r C:\Users\Valen\Desktop\Projet\cal.com\packages\app-store\templates/basic/* C:\Users\Valen\Desktop\Projet\cal.com\packages\app-store\intercom
'cp' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.
```
### Expected Results

- App created

### Technical details

- Windows environnement
- Node.js version 18.17.0

### Proposed Solution

To ensure compatibility with Windows environments, consider using the appropriate command for copying files. For instance, 'cp' is a Unix-based command, whereas 'xcopy' or 'copy' should be used for Windows environments. By modifying the relevant part of the App-Store-CLI code to handle file copying appropriately based on the user's environment, the issue can be resolved.

This adjustment will provide a more inclusive development experience for Windows users, enabling them to create apps using the App-Store-CLI without encountering this specific 'cp' command error.

**Comment by shubh-rgb** [comment]
Try to use below command>
Copy-Item -Path C:\Users\Valen\Desktop\Projet\cal.com\packages\app-store\templates/basic/* -Destination C:\Users\Valen\Desktop\Projet\cal.com\packages\app-store\intercom -Recurse

**Comment by vachmara** [comment]
I open a pull request that fix this, thanks @shubh-rgb !
