### ISSUE TITLE
[CAL-2233] i18n: "cancel" is not always "cancel"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10335]
in a lot of languages, "cancel" a meeting is different to "cancel" a dialog modal.

in german "cancel" an event is "absagen" whereas "cancel a dialog" is abbrechen.

we need to introduce a new string_key identifier for both cases

<sub>[CAL-2233](https://linear.app/calcom/issue/CAL-2233/i18n-cancel-is-not-always-cancel)</sub>

**Comment by fancymithun** [comment]
Is it quick fix like need to update only in german?

**Comment by sikehish** [comment]
Do we have to introduce a new string_key only for German or considering other cases. Some clarity on this help would help!
