### ISSUE TITLE
UI Issue with Scrollbar: Cal Video on Firefox

### ISSUE THREAD

**Issue by candideu** [calcom/cal.com#10332]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There's a random scroll bar in the Cal Video Meeting that blocks the arrow which shows additional meeting details.

![image](https://github.com/calcom/cal.com/assets/55474996/02d4c04f-c09f-40d9-8ec4-300579b5df87)

### Steps to Reproduce

1. Create a meeting with Cal Video as the conferencing
2. Access a Cal Video link on Firefox Desktop, 100% Zoom

### Actual Results

Scrollbar hides the arrow

### Expected Results

No scrollbar and arrow would be visible

### Technical details

Firefox, version 115.0.2

### Evidence

see screenshot

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by JunedKhan101** [comment]
I am trying to reproduce this issue however for some reason when I schedule the meeting I don't get any email and hence I can't join the meeting to reproduce the error. Tried with gmail and outlook.

**Comment by Sranjan0208** [comment]
> I am trying to reproduce this issue however for some reason when I schedule the meeting I don't get any email and hence I can't join the meeting to reproduce the error. Tried with gmail and outlook.

Same issue here. Since I am running this locally, I am using test users and trying to join the meeting. But since the meeting link is sent on the user email, I am not able to access the meeting window.

**Comment by pranay-0512** [comment]
@candideu, I cant seem to reporduce this issue in firefox v115..0.2, video call seems to be working fine without any scrollbar even at 100% zoom.

![image](https://github.com/calcom/cal.com/assets/122438466/c287807c-c0f7-449f-a76a-5fc057a81abe)
Take a look at this.

**Comment by JunedKhan101** [comment]
@pranay-0512 Can you share how did you join a meeting in localhost? so that we can try to reproduce the issue on our side as well.

**Comment by PeerRich** [comment]
cant reproduce on latest firefox, nor chrome, nor safari


![image](https://github.com/calcom/cal.com/assets/8019099/c4c7ade0-3ae9-43fc-a7b3-3f069a88b549)

**Comment by candideu** [comment]
The issue disappeared today out of nowhere... Very strange. Thanks for checking, folks!
