### ISSUE TITLE
Unable to Sign Up with Google 

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [calcom/cal.com#10342]
### Issue Summary

I'm experiencing this issue while trying to sign up for the website using the "Sign up with Google" option after navigating to Plans -> Individual/teams. When I click on the Google sign-up button, nothing happens, and I'm unable to proceed with the registration process.

### Steps to Reproduce

1. open cal.com
2. Navigate to Plans (individuals/teams)
3. Click on the "Sign up with Google" button.

### Actual Results

Upon clicking the "Sign up with Google" button, there is no response, and the Google login page does not appear. I'm unable to proceed with the sign-up process.

### Expected Results

After clicking on the "Sign up with Google" button, I should be redirected to the Google login page to authenticate my account. Once authenticated, I should be redirected back to the website to complete the sign-up process.

https://github.com/calcom/cal.com/assets/71914071/8e99b82d-116b-4d91-acb8-0f36e4304f29

**Comment by PeerRich** [comment]
you need to enter a username as the error indicates
