### ISSUE TITLE
[CAL-2238] "Could not book the meeting." - Consistent error with any date and time

### ISSUE THREAD

**Issue by bennyschmidt** [calcom/cal.com#10343]
Trying to book on a user's calendar, first time I have seen this app. It doesn't work, the request just hangs no matter what date & time I choose, then I get the following error:

![image](https://github.com/calcom/cal.com/assets/1780212/98a50a4c-1bf2-4556-afbc-eeb493b00575)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2238](https://linear.app/calcom/issue/CAL-2238/could-not-book-the-meeting)</sub>

**Comment by PeerRich** [comment]
hey @bennyschmidt can you help me reproduce this? What is the link?

**Comment by PeerRich** [comment]
you can also send me the link to peer@cal.com

**Comment by bennyschmidt** [comment]
@PeerRich Sent you his calendar link

**Comment by nicktrn** [comment]
I just came across the same issue when fixing weekly limits in #10404. It would happen on mismatch between UI and actual availability. Could this be related?

**Comment by gitwittidbit** [comment]
Experiencing this issue right now on a fresh (docker) install (v 3.3.7).

I have set up a number of open slots and when I pick one (and complete the other booking steps), cal.com tells me that the booking failed and asks me to try another time.

Docker logs show this

`@calcom/web:start: 19:35:18.688 ERROR book:user 5:user/appointment2023 Booking 5 failed Error when saving booking to db No Credential found 
@calcom/web:start: NotFoundError [PrismaClientKnownRequestError]: No Credential found
@calcom/web:start:     at /calcom/node_modules/@prisma/client/runtime/library.js:34:609
@calcom/web:start:     at async /calcom/node_modules/@prisma/client/runtime/library.js:34:549
@calcom/web:start:     at async createBooking (/calcom/apps/web/.next/server/chunks/63603.js:4704:81)
@calcom/web:start:     at async handler (/calcom/apps/web/.next/server/chunks/63603.js:4733:19)
@calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:688:21)
@calcom/web:start:     at async /calcom/apps/web/.next/server/chunks/1683.js:59:28 {
@calcom/web:start:   code: 'P2025',
@calcom/web:start:   clientVersion: '5.2.0',
@calcom/web:start:   meta: undefined
@calcom/web:start: }
@calcom/web:start: 19:35:18.696 ERROR [[redactError] Error:  {"stack":"NotFoundError: No Credential found\n    at /calcom/node_modules/@prisma/client/runtime/library.js:34:609\n    at async /calcom/node_modules/@prisma/client/runtime/library.js:34:549\n    at async createBooking (/calcom/apps/web/.next/server/chunks/63603.js:4704:81)\n    at async handler (/calcom/apps/web/.next/server/chunks/63603.js:4733:19)\n    at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:688:21)\n    at async /calcom/apps/web/.next/server/chunks/1683.js:59:28","message":"No Credential found","name":"NotFoundError","code":"P2025","clientVersion":"5.2.0"} `

Can I do anything about this?

**Comment by swapyxdev** [comment]
Hi, this issue still persists. Any solution please?

**Comment by lnovitz** [comment]
looks like this is an issue with recurring events for me. this is the API call. `https://cal.com/api/book/recurring-event` returning a 500 error
