### ISSUE TITLE
Adding URL Workflow Variables to Hyperlinks

### ISSUE THREAD

**Issue by candideu** [calcom/cal.com#10354]
### Is your proposal related to a problem?
When adding URL-based variables such as `{MEETING_URL}`, `{CANCEL_URL}`, `{RESCHEDULE_URL}`, the variable appears to render as text only, and not as a hyperlink.

### Describe the solution you'd like
When creating workflow email reminders, I would love if...

1. The variable turned into a hyperlinked URL once sent by email, and
2. I had the ability to add a URL-based variable as the target of a hyperlink.

![image](https://github.com/calcom/cal.com/assets/55474996/370e1662-1a53-408b-b4c9-eec0bf1f0645)

Right now, if I try to add them as the target, the hyperlink in the email sent it just set to `https`

**Comment by CarinaWolli** [comment]
This should already work. I just tested {MEETING_URL} it and it does work for me. 

@candideu Did you test all of the three variables ({MEETING_URL}, {CANCEL_URL}, {RESCHEDULE_URL})?

**Comment by candideu** [comment]
@CarinaWolli It doesn't work on Gmail.
Here's an example, from the Gmail Android app.

![Screenshot_20230728-124648](https://github.com/calcom/cal.com/assets/55474996/9f779078-a2b9-4115-ad03-65d85bbc4e22)


I'll test with the other variables later today.

Using the variables as hyperlinks is still a feature that's missing though.
