### ISSUE TITLE
Link meeting omits 'https:' on booking page when 'Display on booking page' is chosen

### ISSUE THREAD

**Issue by jsolly** [calcom/cal.com#10352]
### Steps to Reproduce

1. Create an event with a meeting location of `Link Meeting` make sure the `display on booking page checkbox is checked`
Use this link
https://umd.zoom.us/j/6279782951?pwd=changemeplease

![image](https://github.com/calcom/cal.com/assets/9572232/bf80586f-0081-4a0a-acbd-563f4b5f464f)

2. Visit the booking page
![image](https://github.com/calcom/cal.com/assets/9572232/0f91d45e-dd72-4103-9a60-47dd61d8fff7)

The link appears as `//umd.zoom.us/j/6279782951?pwd=changemeplease` with the protocol omitted

### Expected Results

I would expect the full link to be shown on the booking page

### Technical details
Brave 1.56.11

### Thoughts
I think this is an HTML sanitizer scrubbing the links in the UI. If this is the case, the rules should be relaxed for this field to show whatever URL the author chooses.

Of course, an ftp:// wouldn't make sense, but https is a must.

**Comment by N-NeelPatel** [comment]
@jsolly - I checked the code and found that removal of protocol is added intentionally. This is often used when a page can be accessed via both `http` and `https` and you want the URL to inherit the current protocol to avoid mixed content issues.

```
// Static links always require organizer to input
    if (newLocation.linkType === "static") {
      newLocation.organizerInputType = location.organizerInputType || "text";
      if (newLocation.organizerInputPlaceholder?.match(/https?:\/\//)) {
        // HACK: Translation ends up removing https? if it's in the beginning :(
        newLocation.organizerInputPlaceholder = ` ${newLocation.organizerInputPlaceholder}`;
      }
    } else {
      newLocation.organizerInputType = null;
    }
```
