### ISSUE TITLE
Secret booking questions

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#10365]
Can you please add the function that you can set booking questions as "secret"? So that you or the owner of the appointment can see these questions or answers, but the guest does not get to see them?

Example: Sales teams often exchange their internal notes on appointments with other sales people. For example, a qualification meeting takes place with a prospect, and the salesperson takes notes on the meeting. Afterwards, this salesperson then schedules a sales call with the prospect, but another salesperson conducts the call. Therefore, the 1st sales person now makes the appointment booking via Cal.com for the sales call, using the appointment link of the 2nd sales person (or via Round Robin). In order for salesperson 2 to receive the notes from the qualification meeting, a booking question is stored in his calendar for this purpose, where salesperson 1 stores all the notes.

The problem with this is that the prospect also receives all the notes from the call, as these are displayed on the confirmation page (when rescheduling and canceling the appointment), as well as in their appointment confirmation email and in their calendar. However, this should not be the case, as these notes are only for internal sharing.

**Comment by rkreddy99** [comment]
@RainerZufall9393 Is this what you want?

![image](https://github.com/calcom/cal.com/assets/49095575/36b3e8d9-1b7f-460c-b905-7760042ab801)

**Comment by rkreddy99** [comment]
https://www.loom.com/share/0fc24982eaa0488a94a0a79d3fd22259?sid=9f95e41b-cbef-4ff4-b31a-61fd89d63b62

@RainerZufall9393 can you check this and give your inputs

**Comment by RainerZufall9393** [comment]
Hey @rkreddy99 that looks really good from the implementation!

Only the workflow would not fit for us so yet. For us, it would be important that only the owner of the event, sees the secret answers. In our process, salesperson 1 does not enter his own contact data in the form, but that of the prospect. We normally do not use the “Guest” field, or we use it very rarely.

This is how the display of secret answers would be optimal:
- Event owner: sees secret answers
- Event booker: sees NO secret answers
- Other guests: sees NO secret answers






The person who enters via the form, as well as other guests, should not see them.

**Comment by rkreddy99** [comment]
@RainerZufall9393 In the current flow, the salesPerson1 doesnt receive the secret answer in the mail, only the owner receives it. So even if we directly enter prospect details there, shouldnt be an issue ig.

> The person who enters via the form, as well as other guests, should not see them.

Does this mean that after salesPerson1 enters the details of the prospect in booking form, we shouldnt show the secret answer in bookingConfirmed page (in the image attached below)?

![image](https://github.com/calcom/cal.com/assets/49095575/0874f474-5106-4310-bfb4-2fda6bd3033f)

**Comment by RainerZufall9393** [comment]
@rkreddy99 

> In the current flow, the salesPerson1 doesnt receive the secret answer in the mail, only the owner receives it. So even if we directly enter prospect details there, shouldnt be an issue ig.

Okay, then that should fit!

> Does this mean that after salesPerson1 enters the details of the prospect in booking form, we shouldnt show the secret answer in bookingConfirmed page (in the image attached below)?

Yes, that is correct. If it is possible, only the event owner should be able to see the secret answers in his Google Calendar, Apple Calendar or similar - the other participants should not.

**Comment by rkreddy99** [comment]
> Yes, that is correct. If it is possible, only the event owner should be able to see the secret answers in his Google Calendar, Apple Calendar or similar - the other participants should not.

Yeah sure, that change has been taken care of in the calender event that will be sent

**Comment by RainerZufall9393** [comment]
Perfect! Then that sounds like the perfect solution. :)

**Comment by rkreddy99** [comment]
** INCOGNITO TAB IS BOOKERS PERSPECTIVE **

https://www.loom.com/share/d50bf1ac34aa42f5b952a15cb1eec949?sid=3df385f3-c71a-41f4-917d-36e9200e7ba8

**Comment by RainerZufall9393** [comment]
When will the feature be released? @baileypumfleet @PeerRich

**Comment by Rutik7066** [comment]
@baileypumfleet @PeerRich @RainerZufall9393 if no one is working on. can you assign this to me

**Comment by reubence** [comment]
@baileypumfleet i think this issue should be merged and closed.

**Comment by keithwillcode** [comment]
Going with https://github.com/calcom/cal.com/issues/12222 instead
