### ISSUE TITLE
[CAL-2246] Copy profile link doesn't work

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#10368]
When I click this:

![Captura de pantalla 2023-07-25 a las 14.31.52.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/35aa60a0-8e53-4d64-bac6-b8a48bb9120b/2604d401-7ce2-4f3d-9fb6-9aaed010f470?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zNWFhNjBhMC04ZTUzLTRkNjQtYmFjNi1iOGE0OGJiOTEyMGIvMjYwNGQ0MDEtN2NlMi00ZjNkLTlmYjYtOWFhZWQwMTBmNDcwIiwiaWF0IjoxNjkwMjkxOTc3LCJleHAiOjE2OTAzNzgzNzd9.Iw1Hqdgo8OkUGpswxFhtWQ1eNIpjBcyWupUtdj2mUCM)

As you can see, it goes to the wrong link. Also this should include my profile picture in the URL

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2246](https://linear.app/calcom/issue/CAL-2246/copy-profile-link-doesnt-work)</sub>

**Comment by amansingh1712** [comment]
is this issue is fixed now.?I can see it is working fine for the web.
