### ISSUE TITLE
[CAL-2243] Organizations: Upgrade banner in settings is going behind the sidebar

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10364]
![CleanShot 2023-07-25 at 13.02.36@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/21013623-1629-45bb-bbbc-37aeab321839/ecb07daf-5b4e-4758-91ec-44e0c4a65cc4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yMTAxMzYyMy0xNjI5LTQ1YmItYmJiYy0zN2FlYWIzMjE4MzkvZWNiMDdkYWYtNWI0ZS00NzU4LTkxZWMtNDRlMGM0YTY1Y2M0IiwiaWF0IjoxNjkwMjg2NjA4LCJleHAiOjE2OTAzNzMwMDh9.pL7ReiL1k3mWfQ9DRtsT18C-17cUFcSdSBAHkEZ21ek)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2243](https://linear.app/calcom/issue/CAL-2243/organizations-upgrade-banner-in-settings-is-going-behind-the-sidebar)</sub>

**Comment by Udit-takkar** [comment]
dupicate of https://github.com/calcom/cal.com/issues/10080
