### ISSUE TITLE
[CAL-2237] "Limit booking frequency" setting doesn't work

### ISSUE THREAD

**Issue by qu8n** [calcom/cal.com#10361]
### Issue Summary

I have a [Cal.com](http://Cal.com) event at [this link](https://cal.com/quanx/boba). In this event's settings > "Limits" > "Limit booking frequency", I added a rule of 1 per week. After I've set this rule, people could still book > 1 per week: evidently, I already have 1 booking this week and another next week, yet my public event page still allows people to book during these weeks.

### Steps to Reproduce

1. In an event's settings > "Limits" > "Limit booking frequency", add a rule of 1 per week
2. Book a meeting this week for that event
3. Return to the booking page to see that this week is available for more bookings

### Actual Results

* People can still book after I've set a rule of only one event booking per week

### Expected Results

* If this week already has a booking, people should see that this week no longer has any open slots for more booking

### Technical details

* I'm using Chrome / Arc browsers
* Confirmed that this setting has been saved and was set for several days now

### Evidence

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/32dfe618-fb8d-46b2-ae4f-cce10a2dbe7b/846df973-90c8-416c-8bbb-7172345b3b6b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMmRmZTYxOC1mYjhkLTQ2YjItYWU0Zi1jY2UxMGEyZGJlN2IvODQ2ZGY5NzMtOTBjOC00MTZjLThiYmItNzE3MjM0NWIzYjZiIiwiaWF0IjoxNjkwMjg0NTExLCJleHAiOjE2OTAzNzA5MTF9.hQqkfAvv22SYCYZOz1r3nC2RRT5LAGai62YZDMqUGrE)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/95325fed-ec39-416b-9e8a-8c9419867c61/8cb696bb-8682-468a-b591-b3a20a3abd2a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NTMyNWZlZC1lYzM5LTQxNmItOWU4YS04Yzk0MTk4NjdjNjEvOGNiNjk2YmItODY4Mi00NjhhLWI1OTEtYjNhMjBhM2FiZDJhIiwiaWF0IjoxNjkwMjg0NTExLCJleHAiOjE2OTAzNzA5MTF9.aKNzreasBqU41wvKCTEKGeZFGSpwhN9kE3RRcdef-8c)

<img width="446" alt="CleanShot 070349@2x" src="[https://github.com/calcom/cal.com/assets/86090707/9f035858-fa2b-483b-9944-bd6fe0c02508](https://github.com/calcom/cal.com/assets/86090707/9f035858-fa2b-483b-9944-bd6fe0c02508)">

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7962e0f9-36b9-4a2b-beac-16a3f2d283bf/04b42a4d-d4bf-4330-858e-5ace2bed05d9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83OTYyZTBmOS0zNmI5LTRhMmItYmVhYy0xNmEzZjJkMjgzYmYvMDRiNDJhNGQtZDRiZi00MzMwLTg1OGUtNWFjZTJiZWQwNWQ5IiwiaWF0IjoxNjkwMjg0NTExLCJleHAiOjE2OTAzNzA5MTF9.292dkqPZjMwAVNd8S1r92ks1AJHO0jHTzTwU67Pyn-Y)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2237](https://linear.app/calcom/issue/CAL-2237/limit-booking-frequency-setting-doesnt-work)</sub>

**Comment by nicktrn** [comment]
@qu8n thanks for reporting. Looked into this and also found a related bug, both hopefully fixed after the incoming PR.

**Comment by rkreddy99** [comment]
I believe the merged fix wont work for in the case of `PER_MONTH` limit. Lets say there a was an event booked on 3rd, and current date is 28th, the getUserAvailability receives start and end date as 28th and 31st. so changing it based on week wont solve this, as the dates would be 23rd and next month's 5th.

Also is altering the date range for busyTimes func a good idea because it fetches events from connected calenders and other events for the given duration? But in case this is not much of a performance issue we can just change start and end dates to `dayjs.min(startDate.startOf(month), startDate.startOf(week))` and `dayjs.max(endDate.endOf(month), endDate.endOf(week))`

But if this is not a good idea, i have created a pr addressing this.

**Comment by nicktrn** [comment]
@rkreddy99 Looks like you discovered another linked bug: **Past events may be ignored when placing monthly limits.** Three separate bugs from just one issue :eyes:

I believe weekly limits behave as they should now, so let's move the discussion into your PR!

**Comment by rkreddy99** [comment]
> @rkreddy99 Looks like you discovered another linked bug: Past events may be ignored when placing monthly limits. Three separate bugs from just one issue

It's not "another" bug 😅, its the same issue of checking correct range, the exisiting limits check functionality doesn't look for bookings for selected event before start and after end date (current date and month end in this case).

**Comment by nicktrn** [comment]
I feel responsible here as I submitted the original PR. Just had some time to have another look and found more things that don't work. Bit of a nightmare these limits - let's fix them for good. Will report back when I have more.
