### ISSUE TITLE
[CAL-2241] Organizations /profile screen is empty

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10373]
![CleanShot 2023-07-25 at 12.58.29@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f0592bdd-5f2b-4c76-b20f-f5fad729f612/254fe2f1-8f0b-4a8d-8e08-eb273ac908c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMDU5MmJkZC01ZjJiLTRjNzYtYjIwZi1mNWZhZDcyOWY2MTIvMjU0ZmUyZjEtOGYwYi00YThkLThlMDgtZWIyNzNhYzkwOGM2IiwiaWF0IjoxNjkwMjk4MTcxLCJleHAiOjE2OTAzODQ1NzF9.8gGr8ACR5MAdPRyo8bw60fKwwGbeuo6kVqrNRkTtlk8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2241](https://linear.app/calcom/issue/CAL-2241/organizations-profile-screen-is-empty)</sub>

**Comment by CarinaWolli** [comment]
Can't reproduce this. @Jaibles is this still happening to you? Do you see any errors in the console?

**Comment by Jaibles** [comment]
Can't reproduce. I've a feeling it happened shortly after onboarding. I'll close this, go through onboarding again and see if I can reproduce with more context/errors.
