### ISSUE TITLE
[CAL-2252] Team name is empty

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#10371]
![Captura de pantalla 2023-07-25 a las 15.19.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0f41eb0d-ee66-4ca6-9769-76f6049cc650/f2aea27c-21c8-4afd-83e2-627143239e2d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wZjQxZWIwZC1lZTY2LTRjYTYtOTc2OS03NmY2MDQ5Y2M2NTAvZjJhZWEyN2MtMjFjOC00YWZkLTgzZTItNjI3MTQzMjM5ZTJkIiwiaWF0IjoxNjkwMjk0NzgxLCJleHAiOjE2OTAzODExODF9.pSC47y1fc-U3B3vX7TDTFV3UgEGknrHKXSccqLFWT7E)

It very often doesn't load any of the data here

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2252](https://linear.app/calcom/issue/CAL-2252/team-name-is-empty)</sub>

**Comment by Zahidd02** [comment]
Can you let us know which page is this from?
