### ISSUE TITLE
[CAL-2258] Password hints don't match

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#10379]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/27f7823e-9cfb-4bcd-bee0-994a7bc84f6b/05a7abd9-dd69-475a-b301-749e6d5b805c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yN2Y3ODIzZS05Y2ZiLTRiY2QtYmVlMC05OTRhN2JjODRmNmIvMDVhN2FiZDktZGQ2OS00NzVhLWIzMDEtNzQ5ZTZkNWI4MDVjIiwiaWF0IjoxNjkwMzA3ODA5LCJleHAiOjE2OTAzOTQyMDl9.Is4yq7fp7m8BhQSGmYXau616PR0S_ZFdmSJNdpMeRLA)

Here we can see that we don't have any lowercase nor uppercase letter, but we still show it green.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d207cfd2-8e4e-49b6-bb1a-11251869e1ba/1db0c8d6-6206-42a6-9756-a4bec86a5652?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kMjA3Y2ZkMi04ZTRlLTQ5YjYtYmIxYS0xMTI1MTg2OWUxYmEvMWRiMGM4ZDYtNjIwNi00MmE2LTk3NTYtYTRiZWM4NmE1NjUyIiwiaWF0IjoxNjkwMzA3ODA5LCJleHAiOjE2OTAzOTQyMDl9.MUAp6-HfUFK9OsZwPkNDGKk-szGhVfTNpYA18p0zmac)

Here we see that we have at least a number but we display the error anyways

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/54e9caa0-e2f5-4845-9358-2485a7466752/fb10cb6d-f767-4f3d-895c-ee53f880d114?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81NGU5Y2FhMC1lMmY1LTQ4NDUtOTM1OC0yNDg1YTc0NjY3NTIvZmIxMGNiNmQtZjc2Ny00ZjNkLTg5NWMtZWU1M2Y4ODBkMTE0IiwiaWF0IjoxNjkwMzA3ODA5LCJleHAiOjE2OTAzOTQyMDl9.-fze52pLAFHfjw0dlTip2dtqV104Q6PiUSf77VgsC8c)

Here we see bot upper and lowecase letter but the error remains

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2258](https://linear.app/calcom/issue/CAL-2258/password-hints-dont-match)</sub>

**Comment by khan-shazid** [comment]
Hi there,

upon digging, we can see that password only have length validation which is 7 (String must contain at least 7 character(s)). should we just remove the other validation messages? and only show message for the length? or do we want to implement all the mentioned validations? 
- Mix of uppercase & lowercase letters
- Minimum 7 characters long
- Contain at least 1 number

**Comment by siddanth-6365** [comment]
can you give the location or page where you are facing problem ?

**Comment by MehulZR** [comment]
> can you give the location or page where you are facing problem ?

It's the signup page.

**Comment by MehulZR** [comment]
As far as I have figured out. If we want the hints to indicate that some of them have passed(checked) and others failed.
We need to keep some sort of state.

Zod supports multiple errors per field (superRefine). But react hook form only forwards one error per field. We can create a solution using *message* props of react hook form but that does seems really hacky. 

Either we can create a specific component for that purpose. 
or
We can display the error rfh provides us (only one error at a time) and display the hints as purely bullet points.

> On sidenote. I think we should validate the form on onBlur or onTouched for better UX.

**Comment by wolf-4bit** [comment]
Hey all,
Upon further investigation, the schema of signup's backend endpoint is designed in a way of having a minimum of 7 length password. I believe the rework of both frontend and backend is required in case of a mismatch of password hints.

1) We can either use superRefine for catching multiple errors  and send it back to frontend 
OR
2) We can use regex for pattern matching and send back the error to frontend if password is mismatched with validation.

**Comment by rajesh-1252** [comment]
Hey all,

**Comment by rajesh-1252** [comment]
Hey all,
I have fixed this bug by using regex in the signup page 
![image](https://github.com/calcom/cal.com/assets/71485855/98285ef0-dbcf-47f8-8dd8-1fc01a7ceb83)

https://github.com/calcom/cal.com/assets/71485855/584d6f3c-c582-48ef-94ce-d9b7df3452de
