### ISSUE TITLE
Link to v3 blog leads to an error page

### ISSUE THREAD

**Issue by tansanDOTeth** [calcom/cal.com#10386]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

https://github.com/calcom/cal.com/assets/92072158/0bdc74ad-a40b-483b-b533-ca6d1ea666dd

### Actual Results

It goes to an error

### Expected Results

To see the blog post

**Comment by emrysal** [comment]
Thanks for the report @tansanDOTeth 

@p6l-richard This seems to me like a one-off, not related to rewrites/caching. https://cal.com/blog/v-3-0 - inspecting the console it looks like the cover image has a missing url in the CMS

**Comment by KUNDAN1334** [comment]
can you plz tell me in which file i can found this..
