### ISSUE TITLE
No padding below buttons in Update Avatar of team dialog

### ISSUE THREAD

**Issue by BhuvaneshPatil** [calcom/cal.com#10387]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
No space below(padding) buttons when updating team avatar on team page

### Steps to Reproduce

1. Create a team
2. Click on Update button next to team avatar

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

no padding below the buttons as we showing in other modal/dialog

### Expected Results
Padding should be there

### Evidence
<img width="776" alt="Screenshot 2023-07-26 at 8 09 03 AM" src="https://github.com/calcom/cal.com/assets/27822551/353e1924-544a-4e61-bde3-182444264189">

**Comment by Udit-takkar** [comment]
Fixed here https://github.com/calcom/cal.com/pull/10319
