### ISSUE TITLE
Upload Avtar should have some padding at the bottom

### ISSUE THREAD

**Issue by chwasifjameel** [calcom/cal.com#10385]
### Issue Summary

While signing up, I noticed that the **Close** and **Save** buttons are too near to the bottom. We should add some spacing to make the design consistent.

### Steps to Reproduce

1. Go to Signup
2. Verify your email
3. Fill in personal information and attach calendars.
4. Go to upload a profile picture

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Buttons too near to the bottom of the modal

### Expected Results

- Buttons should have some padding at the bottom

### Technical details

N/A

### Evidence

<img width="726" alt="image" src="https://github.com/calcom/cal.com/assets/33599674/3010321f-e8c3-42ec-a8e5-2a4f9994a0d4">

**Comment by chwasifjameel** [comment]
Please assign this to me. I'll fix it.

**Comment by emrysal** [comment]
@chwasifjameel Just so your aware, a fix was attempted for this so it will show up different in our main branch. It's not working correctly though so your help is much appreciated.

Tip: You can replace the title markup with the following:

```javascript
<DialogContent title={t("upload_target", { target })}>
```

**Comment by chwasifjameel** [comment]
Okay, thanks for the tip.

**Comment by BhuvaneshPatil** [comment]
Fixed here https://github.com/calcom/cal.com/pull/10319

**Comment by emrysal** [comment]
Re-opening because the viewport height seems to affect the location of the buttons
<img width="1247" alt="image" src="https://github.com/calcom/cal.com/assets/1046695/92f2a0da-3be7-4bbb-a09a-0de9e11488eb">
