### ISSUE TITLE
[CAL-2261] If the input type "Name" is selected, the label can't be changed from our default label "Your Name"

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10390]
[https://app.birdeatsbug.com/sessions/-ZDXRm7sd1JSyC-NEoXm8ZHSyTbWMWezvkAllOzlsN2Z](https://app.birdeatsbug.com/sessions/-ZDXRm7sd1JSyC-NEoXm8ZHSyTbWMWezvkAllOzlsN2Z)
Created via Threads. See full discussion: [https://threads.com/34513965502](https://threads.com/34513965502)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2261](https://linear.app/calcom/issue/CAL-2261/if-the-input-type-name-is-selected-the-label-cant-be-changed-from-our)</sub>

**Comment by hariombalhara** [comment]
[https://www.loom.com/share/e78c7bf2b1a54fc0b73d5df1d8bdeac5](https://www.loom.com/share/e78c7bf2b1a54fc0b73d5df1d8bdeac5)

It's actually working, but not showing correctly in app.

**Comment by ZainGulbaz** [comment]
#10618 If the input type "Name" is selected, the label can't be changed from our default label "Your Name"
