### ISSUE TITLE
Gitpod instance uses localhost:3000 as NEXT_PUBLIC_WEBAPP_URL when in an external tab

### ISSUE THREAD

**Issue by mohamedaleya** [calcom/cal.com#10391]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.
After creating an instance on Gitpod and opening the preview in a new tab (outside of Gitpod), clicking signup/login... will redirect you to localhost:3000 when it should be that Gitpod instance's URL. This is only applicable if you open it in a separate tab.
If you open it on that same Gitpod tab, you will be redirected to a blank grey page, and for it to work correctly, you need to reload the tab with the preview (not the entire Gitpod tab).

### Steps to Reproduce

1. Create a Gitpod instance of the project
2. Sign up for a new account or log in to your account after opening the link in a new tab
3. You should be redirected to localhost:3000 as shown in the BEB recording below

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
This is not a critical bug but should improve the developer experience for people wanting to contribute through Gitpod.

### Actual Results

- After signing up or logging in from a new tab (while running your project on Gitpod), you will be using localhost:3000 which is not the NEXT_PUBLIC_WEBAPP_URL for Gitpod projects.

### Expected Results

- Use Gitpod's assigned URL instead of localhost

### Technical details

- Browser version: Brave [Version 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)](https://brave.com/latest/)
- Bird Eats Bug Recording: [Click here](https://app.birdeatsbug.com/sessions/Fw2KePZr2yIJYhwwPojNCPACdnD7-TrPxigmY71TFzvx?networkPane=true)
- Node.js version: Gitpod's node version is v18.16.1

### Evidence

- Please check the Bird Eats Bug recording above

(This is my first issue here and I am still trying to get familiar with everything, so please excuse me if I misunderstood something.)

**Comment by suyash5053** [comment]
Hey @mohamedaleya , I too use Gitpod, before running a local host website on a new tab you have to run a yarn dx command in the terminal and then the terminal will give you a link that will be suitable to you. Try refreshing and letting the web pack compile completely, If the issue persists.
