### ISSUE TITLE
[CAL-2263] Add @typescript-eslint/no-floating-promises  and https://typescript-eslint.io/rules/no-misused-promises

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10398]
Also consider enabling https://typescript-eslint.io/linting/configs/#recommended-type-checked

<sub>[CAL-2263](https://linear.app/calcom/issue/CAL-2263/add-typescript-eslintno-floating-promises-and-httpstypescript)</sub>

**Comment by hariombalhara** [comment]
cc @zomars

**Comment by zomars** [comment]
Let's adopt no-misused-promised. This would help catch some recent bugs that we have found.
