### ISSUE TITLE
Show relevant email organizer address depending on calendar

### ISSUE THREAD

**Issue by georgekrax** [calcom/cal.com#10410]
I am a big fan of using multiple calendars on Cal.com to separate personal chat calls from professional meetings. On the platform I have added both my personal **(@gmail.com)** and professional work **(@thestartupuniverse.org)** Google calendars. 

### Issue Summary

I have one _Chat_ event for personal calls with friends and one event _Startup Universe_ for work meetings. When someone books a call on the "Chat" event, I have configured it to book the call on my personal calendar (@gmail.com) and connected the event with that calendar. When someone books a call on the "Startup Universe" event, I have configured it to book the call on my work calendar (@thestartupuniverse.org) and connected the event with my work calendar. 

The events are booked perfectly fine on each calendar depending on the event type. I have set my email on Cal.com to be my professional one and not my personal one (the one with the @thestartupuniverse.org domain).

![image](https://github.com/calcom/cal.com/assets/62029562/ff2ce1bb-cdc9-40da-88ef-9af2f73659c1)

### Expected Results

Whenever an event is booked, the calendar invitation and Cal.com booking email from hello@cal.com is sent **only** to george@thestartupuniverse.org. What I would like to, do is for personal calls the booking email to be sent to my personal domain @gmail.com. 

At the same time when a "Chat" event is booked on my personal calendar, I would like the organizer's email to be my personal email with the @gmail.com domain. Not the one with the @thestartupuniverse.org domain.

![image](https://github.com/calcom/cal.com/assets/62029562/c24d990e-b6b9-4078-97d9-7c4e7a5d063d)

**Comment by PeerRich** [comment]
this is in the making

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/pull/12821
