### ISSUE TITLE
[CAL-2264] [CAL-2296] Refactor /event-types/[type]

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#10419]
### Is your proposal related to a problem?

Fetch only required data from event type table instead of everything when user navigates to /event-types/[id]?tabName=setup

https://threads.com/34515073378?s=5ryKLpBt8fbuER5g2UxguU

<sub>[CAL-2264](https://linear.app/calcom/issue/CAL-2264/refactor-event-types[type])</sub>

**Comment by Raghul18** [comment]
@Udit-takkar : Could we obtain more information about this issue? Currently, I've noticed that only the 'teamMembers' prop is being passed unnecessarily into 'EventSetupTab.' Is the requirement to remove this prop?

**Comment by alannnc** [comment]
I have some work in progress related to this, my plan here will be use event types pagination in trpc, so we can load individual event types and team even types with limits and offsets. This will increase load time and also use cache if required. @keithwillcode @Udit-takkar

**Comment by Udit-takkar** [comment]
duplicate of https://linear.app/calcom/issue/CAL-2296/improve-number-of-called-queries-when-loading-event-types
