### ISSUE TITLE
Booking layout settings not visible

### ISSUE THREAD

**Issue by verstratenbram** [calcom/cal.com#10414]
### Issue Summary

When going to Settings - Appearance the section about Booking layout is not always visible.

### Steps to Reproduce

1. Go to Settings -> Appearance.
2. Booking layout is missing.
3. Lose focus on the browser tab (open a different app or even a different browser tab).
4. Regain focus on the browser tab.
5. The Booking layout section is visible again.

Sometimes a page refresh is required (while on the Appearance page) for the Booking layout section to turn invisible.

### Actual Results

- The Booking layout section is missing from the Appearance page.

### Expected Results

- The Booking layout section should always be visible.

### Technical details

- Browser: Chrome 115.0.5790.98
- OS: macOS 13

### Evidence

https://github.com/calcom/cal.com/assets/29309992/2bc8725c-b693-42ca-82d8-e0427d66a2cc

**Comment by Ali7040** [comment]
I want to work on it please assign it to me.

**Comment by alceil** [comment]
Can I have a dab at this issue? @PeerRich

**Comment by Ali7040** [comment]
Sorry, I am busy nowadays.

**Comment by Rajesh270712** [comment]
I will work on this you can assign it to me.
