### ISSUE TITLE
"Generate private link" event setting resets after save

### ISSUE THREAD

**Issue by O4epegb** [calcom/cal.com#10423]
### Issue Summary

`Generate private link` advanced event setting resets after repeated save

### Steps to Reproduce

1. Go to event Settings -> Advanced panel
2. Enable `Generate private link` toggle and Save
3. Reload the page
4. Change something else, e.g. event title and Save
5. Reload the page
6. `Generate private link` is not toggled off

### Actual Results

I did not expect it to be toggled off

### Expected Results

`Generate private link` should still be on?

### Technical details

Probably not important, reproduced both in production and in dev main branch.

### Evidence

https://github.com/calcom/cal.com/assets/12836237/2704cbe9-e0b9-4c9e-8f33-e4bb7ebb0050

**Comment by O4epegb** [comment]
I would like to tackle it too, if no one minds

**Comment by Kaneki-Ken-7** [comment]
@PeerRich can you check my PR?

**Comment by O4epegb** [comment]
> @PeerRich can you check my PR?

I said I wanted to fix it and actually also prepared PR with a bit of refactoring 😅 but well, never mind I guess, you can do it.

**Comment by Kaneki-Ken-7** [comment]
> > @PeerRich can you check my PR?
> 
> I said I wanted to fix it and actually also prepared PR with a bit of refactoring and reenabled test 😅 but well, never mind I guess, you can do it.

I didnt saw anyone assigned to it so I gave it a try.
