### ISSUE TITLE
"NAUF: Ends between a busy time slot" for user defined event lengths

### ISSUE THREAD

**Issue by dihedral** [calcom/cal.com#10422]
### Issue Summary

When trying to book an event where user defined length is allowed, and chosen booking time is smaller than the default value, the function checkForConflicts() is not checked against the selected duration but for the default duration.
i.e. default 60 mins, user selected 30 mins, and opts for a time slot where 60 mins will actually conflict, but 30 mins will not.

### Steps to Reproduce

1. create an eventtype with user selectable durations (e.g. 30 mins and 60 mins)
2. eventtype should allow event start times in 15 min intervals
3. eventtype buffer before and after of 10 mins
4. the eventtypes default duration should not be the smalles value (e.g. 60 mins)
5. create an event in your kalendar as a conflict that start at the full hour
6. book through this eventtype, select for a 30 min event, and start at the 15 minute mark before the conflicting event at the full hour

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- checkForConflicts() will check for a 60 min slot and fail due to conflicting event in calendar

### Expected Results

- selected 30 min event length should be honored and the event should be bookable.
- checkForConflicts() should only check for the duration about to be booked.

### Technical details

- original error: ERROR [api] book:user NAUF: Ends between a busy time slot {"start":"2023-08-01T11:00:00.000Z","end":"2023-08-01T12:00:00.000Z","time":"2023-08-01T11:15:00+00:00"}
- modified output (including event start, event end and checked duration): ERROR [api] book:user NAUF: Ends between a busy time slot {"start":"2023-08-01T11:00:00.000Z","end":"2023-08-01T12:00:00.000Z","timeStart":"2023-08-01T10:15:00+00:00","time":"2023-08-01T11:15:00+00:00","duration":60}
- Node.js v20.3.1 (though I doubt that plays a role)

### Evidence

- See the Log Output above

**Comment by amiltonpaglia** [comment]
> "...checkForConflicts() is not checked against the selected duration but for the default duration."

I'm experiencing a similar issue. I've configured an event type with a 5-minute duration. However, when someone books a 5-minute slot, the next available slot appears as if the booked event was 15 minutes long. As a result, it skips two 5-minute slots that should have been available.

**Comment by dihedral** [comment]
is it too dodgy to calculate duration from start and end?


```
diff --git a/packages/features/bookings/lib/handleNewBooking.ts b/packages/features/bookings/lib/handleNewBooking.ts
index 5404f3095..f8abe15a2 100644
--- a/packages/features/bookings/lib/handleNewBooking.ts
+++ b/packages/features/bookings/lib/handleNewBooking.ts
@@ -349,6 +349,7 @@ async function ensureAvailableUsers(
   }
 ) {
   const availableUsers: IsFixedAwareUser[] = [];
+  const duration = dayjs(input.dateTo).diff(input.dateFrom, 'minute');
   /** Let's start checking for availability */
   for (const user of eventType.users) {
     const { dateRanges, busy: bufferedBusyTimes } = await getUserAvailability(
@@ -366,6 +367,7 @@ async function ensureAvailableUsers(
     }

     console.log("calendarBusyTimes==>>>", bufferedBusyTimes);
+    console.log("duration=>>>", duration);

     let foundConflict = false;
     try {
@@ -380,10 +382,10 @@ async function ensureAvailableUsers(
         // running at the first unavailable time.
         let i = 0;
         while (!foundConflict && i < allBookingDates.length) {
-          foundConflict = checkForConflicts(bufferedBusyTimes, allBookingDates[i++], eventType.length);
+          foundConflict = checkForConflicts(bufferedBusyTimes, allBookingDates[i++], duration);
         }
       } else {
-        foundConflict = checkForConflicts(bufferedBusyTimes, input.dateFrom, eventType.length);
+        foundConflict = checkForConflicts(bufferedBusyTimes, input.dateFrom, duration);
       }
     } catch {
       log.debug({

```
