### ISSUE TITLE
[CAL-2268] *Could not book a meeting* error but the meeting goes through

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10432]
![Screenshot 2023-07-28 at 10.26.37.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/492398e7-c436-4934-95fd-34b861d0cfea/95b2be45-ddfb-4b89-b49f-9a7ee48f7b2a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80OTIzOThlNy1jNDM2LTQ5MzQtOTVmZC0zNGI4NjFkMGNmZWEvOTViMmJlNDUtZGRmYi00Yjg5LWI0OWYtOWE3ZWU0OGY3YjJhIiwiaWF0IjoxNjkwNTMzMjAwLCJleHAiOjE2OTA2MTk2MDB9.5L-pVoYUGqRhO5txJ7MAQCPY6mf9okknE6y7mfA2L-s)

Created via Threads. See full discussion: [https://threads.com/34515684392](https://threads.com/34515684392)

![Screenshot 2023-07-28 at 10.26.49.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/35a75e50-8f1e-4e57-a6a9-6d04d07fefe8/5f92e902-e372-42dd-bf6e-9ecd0e943845?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zNWE3NWU1MC04ZjFlLTRlNTctYTZhOS02ZDA0ZDA3ZmVmZTgvNWY5MmU5MDItZTM3Mi00MmRkLWJmNmUtOWVjZDBlOTQzODQ1IiwiaWF0IjoxNjkwNTMzMjAwLCJleHAiOjE2OTA2MTk2MDB9.8arYl44vjbVq8W89lUbVbMcltHG0Q-2lfC0zGT0S7Cw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2268](https://linear.app/calcom/issue/CAL-2268/could-not-book-a-meeting-error-but-the-meeting-goes-through)</sub>

**Comment by Tanmai2002** [comment]
The Thread is not accessible

**Comment by hariombalhara** [comment]
It can happen when CalVideo meeting creation errors. 

Third party app integrations failure shouldn’t case core flow to fail i.e. Booking should be created in DB and emails should be properly sent and booker should be notified of the success. 

We should fix it in both creation and updation.

**Comment by hariombalhara** [comment]
@keithwillcode How do we want to proceed here?  I rechecked and it seems like CalVideo meeting creation failure wouldn't allow calendar event to be created as well as meeting is created first in the flow.

As in this case Calendar Event was created, this has to be something else. As this issue isn't replicable, I am inclined towards closing this issue as it could be something else broken at that time.

**Comment by keithwillcode** [comment]
Yeah if we can't replicate, will close for now until new report with details comes through.
