### ISSUE TITLE
[CAL-2267] Bookings are getting created twice for the booker

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#10431]
I have one incident of this happening on an event type with different "Add to calendar" settings than the default. But another incident on one with no change to the "Add to calendar" settings in the event type. [This one](https://cal.com/ciaran/daily-catch-up).

**Steps to recreate**

* Someone booked me.
* 1 showed on mine correctly as per add to calendar settings
* 2 bookings showed on their calendar.
* 
  * One with my **Add to Calendar** settings (personal gmail email). Note: this calendar has different "Add to calendar" than my default.
* 
  * One with my [ciaran@cal.com](mailto:ciaran@cal.com) email

Then where this really becomes an issue...

* He deleted 1 of his 2 bookings.
* Turns out it was the one I see.
* Now I see this and think we're not having a meeting.

![CleanShot 2023-07-28 at 08.28.25@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8a62249c-cd83-4aec-be2d-8135aee9d1a8/f85b1627-1a19-4b0f-8d44-5806dd9ecc19?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84YTYyMjQ5Yy1jZDgzLTRhZWMtYmUyZC04MTM1YWVlOWQxYTgvZjg1YjE2MjctMWExOS00YjBmLThkNDQtNTgwNmRkOWVjYzE5IiwiaWF0IjoxNjkwNTI5NjU4LCJleHAiOjE2OTA2MTYwNTh9.XkwnN1l_6oTtTHvYXBcP0w_QrVENeP4nnkDS5VkyAXI)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5561a183-1b01-4579-b65d-459e76ba34ee/a7780d85-2e9e-4f71-af15-8fc9466f0127?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81NTYxYTE4My0xYjAxLTQ1NzktYjY1ZC00NTllNzZiYTM0ZWUvYTc3ODBkODUtMmU5ZS00ZjcxLWFmMTUtOGZjOTQ2NmYwMTI3IiwiaWF0IjoxNjkwNTMwMTY3LCJleHAiOjE2OTA2MTY1Njd9.hSc5cgKxjwAGDDe95cTA_NTtYYv9032ngIA89n_hkAQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2267](https://linear.app/calcom/issue/CAL-2267/bookings-are-getting-created-twice-for-the-booker)</sub>

**Comment by tarunclub** [comment]
Hey, I think I can help with this issue can you assign this to me?

**Comment by Jaibles** [comment]
@tarunclub no need for assigning. Feel free to create a pr and mention this issue in it and our team will review the pr. Thanks!

**Comment by keithwillcode** [comment]
Not seen for awhile. Closing until new report

**Comment by ciaranha** [comment]
Fresh report of this
![image](https://github.com/calcom/cal.com/assets/4536123/cc35ef55-19d7-4f59-97b6-7960fbcaf86a)

**Comment by Udit-takkar** [comment]
Just tested on that account. I only received one invite
