### ISSUE TITLE
`yarn install` modifies `yarn.lock`

### ISSUE THREAD

**Issue by O4epegb** [calcom/cal.com#10436]
### Issue Summary

I'm not sure if maybe I am doing something wrong, but just simple `yarn install` on main branch produces changes for `yarn.lock`. It's just a little bit annoying to clean up the changes after every install 😄 

Does anyone else have this? Or it's my local problem?

```
yarn.lock | 1842 ++----------------------------------------------------------------------------------------------------------------------------
 1 file changed, 24 insertions(+), 1818 deletions(-)
```

### Steps to Reproduce

1. Do `yarn install`
2. Check for changes in `yarn.lock`

### Expected Results

`yarn.lock` is not modified

### Technical details

yarn 3.4.1
node v18.8.0

**Comment by O4epegb** [comment]
I also think it might be a good idea to use `--immutable` flag to bail out on CI if lock file is modified?

Docs here https://yarnpkg.com/cli/install#options

**Comment by hariombalhara** [comment]
This is due to https://github.com/calcom/cal.com/issues/10217

**Comment by O4epegb** [comment]
> This is due to #10217

Oh, I see, thank you. Well, then I guess this issue can be closed, because it's not easily solvable by just running `yarn`
