### ISSUE TITLE
Not receiving booking emails

### ISSUE THREAD

**Issue by thecmdrunner** [calcom/cal.com#10445]
### Issue Summary

- After changing my email address, I don't receive booking emails on either my old or new email address.
(even after this fix PR: #10155)

- There's a dangling ***"You may need to log out and back in to see any change take effect"*** message, even after logging out and in again.

### Steps to Reproduce

- Go to My account -> Profile
- Change your email address to something else
- Enter the password when prompted, and then submit

### Actual Results

- I don't receive booking emails on my updated email address.
- This message doesn't go away 👉 ***"You may need to log out and back in to see any change take effect"***
- Seems like my new email is marked verified, even though I never got a verification email, and was never asked to perform any other verification method.
![image](https://github.com/calcom/cal.com/assets/38887390/8d5115c1-dade-4640-b77d-49b527745729)

### Expected Results

- I should receive booking emails on my updated email address.
- This message should go away after re-logging in 👉 ***"You may need to log out and back in to see any change take effect"***
- Send a verification email?

### Technical details

- Browser version: Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)

### Evidence

https://github.com/calcom/cal.com/assets/38887390/334189d0-5bdc-4de3-a2a3-88813a6bcd14

**Comment by Udit-takkar** [comment]
@thecmdrunner the fix was merged https://github.com/calcom/cal.com/pull/10306 recently and has not been deployed to production.

**Comment by Udit-takkar** [comment]
@thecmdrunner can you turn on allow impersonation so i can see what's wrong in your account?

**Comment by thecmdrunner** [comment]
@Udit-takkar Sure! Changing my email to the old one, and then back to the new one seems to send me the emails correctly now.
I've enabled User Impersonation anyway, so you can take a look at it, and any other bugs which could be there, thanks a lot! 😃🙌

**Comment by thecmdrunner** [comment]
Hey @Udit-takkar, seems to be fixed now, can close the issue 🙂. Did you find anything wrong with my account?

**Comment by CarinaWolli** [comment]
Fixed by #10306
