### ISSUE TITLE
[CAL-2272] {ATTENDEE} workflow variable always uses first attendee for for seated event

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#10451]
### Issue Summary

When utilizing the "workflow" to send booking confirmation emails to attendees, the {ATTENDEE} variable consistently displays the name of the first attendee for all subsequent attendees. As a result, the 2nd and 3rd persons confirming the booking receive an email with the name of the first attendee instead of their own names.

<sub>[CAL-2272](https://linear.app/calcom/issue/CAL-2272/attendee-workflow-variable-always-uses-first-attendee-for-for-seated)</sub>

**Comment by suyash5053** [comment]
It would be great if you share some more information like screenshot or a loom video
