### ISSUE TITLE
End date in Scheduler Heading does not match with calendar 

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#10452]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

 End date in the Scheduler Heading does not match the end date in the weekly view of the calendar. Today is the 28th, so the end date should be the 3rd, but it is showing as the 4th in the Scheduler Heading. Due to this, when incrementing the week, the end date is missed in the calendar.
![Screenshot 2023-07-28 222953](https://github.com/calcom/cal.com/assets/81948346/5cac2355-46f8-4004-9535-466036cdc248)

After Incrementing
![Screenshot 2023-07-28 223016](https://github.com/calcom/cal.com/assets/81948346/71287f2a-e578-4ef2-b33c-47d390b4d7cb)

### Steps to Reproduce

1. open weekly view

**Comment by ZainGulbaz** [comment]
@keithwillcode  I think it resolved in #10742. Kindly have a look so that we can close this issue.

**Comment by Udit-takkar** [comment]
end date bug has been fixed already https://github.com/calcom/cal.com/pull/10514
