### ISSUE TITLE
Allow search engine blocking (noindex) for user/booking page and events

### ISSUE THREAD

**Issue by mbscala** [calcom/cal.com#10465]
### Is your proposal related to a problem?
I have a focus on privacy and do not want my cal.com link, user/profile/booking page and events to be publicly accessible through search engines.

Currently, for example if you search for "site:cal.com" on Google, you will find all users's booking pages, because the cal.com source code contains the meta-tags "index,follow" in the header sections. Obviously, similar search results are to be expected when searching for the user's name that he provided on his cal.com account.

### Describe the solution you'd like
In the general settings for the cal.com account, it should be possible to generally disable the SEO indexing, for example by adding a checkbox "Disallow search engines from accessing your booking pages". When this checkbox is active, the meta-tags in the header sections should change from "index,follow" to "noindex, nofollow".

Networks like LinkedIn offer similar options in their profile settings.

### Describe alternatives you've considered
The only option is to create a secret event type as this has already been implemented here: https://github.com/calcom/cal.com/issues/6815

However, this does not protect the general booking page (cal.com/USERNAME) from being crawled by search engines.

**Comment by pandeymangg** [comment]
I'd like to work on this!
