### ISSUE TITLE
Signup form card requires margin from top

### ISSUE THREAD

**Issue by prasadsawant7** [calcom/cal.com#10469]
### Issue Summary

In the signup page there are 2 divs, 1st one containing some text that is properly spaced, but the 2nd div contains signup form card which requires margin from as it is touching top. Margin from top is required only in Large device (lg) i.e. laptop/desktop.

### Steps to Reproduce

1. Open [cal.com](https://cal.com/) in laptop or desktop.
2. Click Login button.
3. Click Don't have an account? option.
4. You can see the Signup form card is at the very top without margin top.

I am thinking of solving this issue myself as I am new to Open Source contribution, this issue would give me a good start and confidence for open source contribution

### Actual Results

[Cal_actual.webm](https://github.com/calcom/cal.com/assets/58025997/934ad514-2710-4bf8-a7d3-e3664d32fea6)

### Expected Results

[Cal_expected.webm](https://github.com/calcom/cal.com/assets/58025997/e00fd7f4-ede1-4ed3-a914-b942ff41acf1)

### Technical details

- This issue is persisting in Chrome and Firefox browsers (latest versions).

**Comment by Xofirn** [comment]
@prasadsawant7 I don't understand what the issue here is at all. Can you explain it a bit more clearly?

**Comment by Anshul1811** [comment]
I understood the signup card is not showing margin top property. Can I work on this issue?

**Comment by wolf-4bit** [comment]
Hi @prasadsawant7,
I've tested this in my Chrome browser and it is working as intended. Could you please be more specific about the issue?
![image](https://github.com/calcom/cal.com/assets/125653095/c8c04b4d-63d4-4846-9e48-d2993a4baded)

**Comment by azim1410** [comment]
the issue exists when opened on a screen of 16 inches at 100% size

**Comment by Jaibles** [comment]
We're going to completely rebuild this page in the near future.
