### ISSUE TITLE
Private link does not regenerate after use

### ISSUE THREAD

**Issue by O4epegb** [calcom/cal.com#10461]
### Issue Summary

Private link hint says that `Your private link will regenerate after each use`. But it seems that it does not happen right now.

The param that is used to regenerate is hardcoded to `false` right now:

https://github.com/calcom/cal.com/blob/8f9f096723335bf92638e7a2fdd99980f3ef09e9/packages/features/bookings/lib/book-event-form/booking-to-mutation-input-mapper.tsx#L50

https://github.com/calcom/cal.com/blob/8f9f096723335bf92638e7a2fdd99980f3ef09e9/packages/features/bookings/lib/handleNewBooking.ts#L2327

So what is the correct expected behaviour right now?

Either regeneration should be fixed, or hint should be removed, right?

There is also a e2e test for this, but it's basically disabled with `fixme`:

https://github.com/calcom/cal.com/blob/8f9f096723335bf92638e7a2fdd99980f3ef09e9/apps/web/playwright/hash-my-url.e2e.ts#L9

### Steps to Reproduce

1. Enable `Generate private link` for event
2. Visit this link, book an event
3. Visit settings again, link is still the same

**Comment by asadath1395** [comment]
@PeerRich This is a duplicate of https://github.com/calcom/cal.com/issues/11676 and it has been fixed by https://github.com/calcom/cal.com/pull/11705

**Comment by keithwillcode** [comment]
Nice thanks @asadath1395
