### ISSUE TITLE
Continously getting error on running yarn dx

### ISSUE THREAD

**Issue by ayushgupta4002** [calcom/cal.com#10467]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Hi everyone, So I was following the instructions given to set up the project locally, I have tried it multiple times but this error keeps coming up every time!
I have already set the Nextauth_secret ,DATABASE_URL and CALENDSO_ENCRYPTION_KEY as mentioned

![image](https://github.com/calcom/cal.com/assets/66496371/09c0f6d9-25c6-4057-9f16-1d08eef98c0b)

What can be done to pass through this fault?

**Comment by wolf-4bit** [comment]
Hey @ayushgupta4002,
Could you please provide a screenshot that is not cropped from the above and bottom? The current screenshot which you have provided is not sufficient to diagnose the error.

**Comment by ayushgupta4002** [comment]
> Hey @ayushgupta4002, Could you please provide a screenshot that is not cropped from the above and bottom? The current screenshot which you have provided is not sufficient to diagnose the error.
![image](https://github.com/calcom/cal.com/assets/66496371/c0c3d5d8-7f79-4199-b630-e79b42d0cea7)


here is the image for the  complete error

**Comment by ayushgupta4002** [comment]
I have used supabase for my postgres DATABASE_URL

**Comment by KrishRathor** [comment]
The error is in .env file in packages/prisma:
Currently it is using '../../.env' which is giving the error you can fix it by copying the content of '.env file ' present in root folder and pasting it in the .env file of packages/prisma

**Comment by ayushgupta4002** [comment]
> The error is in .env file in packages/prisma: Currently it is using '../../.env' which is giving the error you can fix it by copying the content of '.env file ' present in root folder and pasting it in the .env file of packages/prisma

![image](https://github.com/calcom/cal.com/assets/66496371/4188e081-e759-42ce-9be5-90ba3ca53082)

It's giving me this now...Do you know a solution for this?

**Comment by Xofirn** [comment]
@ayushgupta4002 I think you shouldn't tamper with the .env anymore than what has been specified in the README. Try cloning the project again or replacing the .env files with the ones on the repo.

**Comment by Xofirn** [comment]
@ayushgupta4002 Clone the repo again.

**Comment by PeerRich** [comment]
have you tried yarn dx with docker running?

also try https://cal.com/docs/introduction/quick-start/self-hosting/upgrading

**Comment by ayushgupta4002** [comment]
> 

It was some error with Prisma .env not able to access root env . Solved it anyhow after cloning it again and experimenting with paths !
