### ISSUE TITLE
Session calls return different data

### ISSUE THREAD

**Issue by O4epegb** [calcom/cal.com#10472]
### Issue Summary

So there are 2 session endpoints (not quite sure why there are two 😄 ):
https://app.cal.com/api/auth/session
https://app.cal.com/api/trpc/public/session

And they return different result for me right now after I changed my nickname. 

Potentially because of LRU cache?
https://github.com/calcom/cal.com/blob/e68ace87e2b6cc23f1f8031208a2629bebdb51a3/packages/features/auth/lib/getServerSession.ts#L14

And some parts of UI are bugged because of that, e.g. `View public page` button leads to old nickname page.

### Steps to Reproduce

I am not sure how to reproduce locally though right now, will try to investigate further

This is autogenerated nickname that I think I got after the registration:
<img width="258" alt="Screen Shot 2023-07-30 at 17 59 02" src="https://github.com/calcom/cal.com/assets/12836237/9f2c19b2-adf9-42db-a62f-71ee65cb6402">

And this is my new custom one:
<img width="504" alt="Screen Shot 2023-07-30 at 17 59 19" src="https://github.com/calcom/cal.com/assets/12836237/dc9fbd03-1748-4ad8-9408-41cee3605a1d">

**Comment by keithwillcode** [comment]
@sean-brydon and I actually investigated this this week. It's already been fixed.
