### ISSUE TITLE
[CAL-2273] Use ui-avatar.com only for all default avatars

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10475]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/314b6fcf-f531-46f7-beda-c76f8232624f/ac285051-830a-459d-9223-330c8075bf13?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMTRiNmZjZi1mNTMxLTQ2ZjctYmVkYS1jNzZmODIzMjYyNGYvYWMyODUwNTEtODMwYS00NTlkLTkyMjMtMzMwYzgwNzViZjEzIiwiaWF0IjoxNjkxNjU3NDAzLCJleHAiOjE2OTE3NDM4MDN9.Tn10MPeLMb0d3R4l-yLACkIci_Rt4s0blarW7K0CSsM)

Possible Followup: Avatar component has fallback image support but it uses [gravatar.com](http://gravatar.com) maybe we can just switch it with [ui-avatars.com](http://ui-avatars.com) and automatically enable fallback.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1b4918a4-d41f-4e86-a5d8-eccf17dd4644/75e6e8ca-7d2b-4991-ac8f-c433a04edca6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xYjQ5MThhNC1kNDFmLTRlODYtYTVkOC1lY2NmMTdkZDQ2NDQvNzVlNmU4Y2EtN2QyYi00OTkxLWFjOGYtYzQzM2EwNGVkY2E2IiwiaWF0IjoxNjkxNjU3MzAwLCJleHAiOjE2OTE3NDM3MDB9.JDfePznE99pRvzFyNuhoqB_8jZPB0BcjMtGTxnxoJOA)

There is one concern that sometimes we show a initials based avatar and sometimes the silhouette avatar.

\*Originally posted by @hariombalhara in \*[*https://github.com/calcom/cal.com/pull/10383#discussion_r1275991923*](https://github.com/calcom/cal.com/pull/10383#discussion_r1275991923)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2273](https://linear.app/calcom/issue/CAL-2273/use-ui-avatarcom-only-for-all-default-avatars)</sub>

**Comment by Saga-sanga** [comment]
@hariombalhara I've submitted a PR where I replaced the use of [gravatar.com](http://gravatar.com/) with [ui-avatars.com](http://ui-avatars.com/). The use of silhouette avatars is preserved and untouched while the rest of the avatars utilise initials now.

**Comment by PeerRich** [comment]
i think we should remove any third party avatar APIs
