### ISSUE TITLE
Support Apple's Travel Time

### ISSUE THREAD

**Issue by andreyrd** [calcom/cal.com#10474]
### Is your proposal related to a problem?

Apple calendar has a feature called "Travel Time" that is supposed to block out travel time needed to get to an event location. Cal.com doesn't seem to support this, as it still lets people book on top of my "travel time".

### Describe the solution you'd like

Cal.com should handle the "travel time" and consider it to be blocked off.

### Describe alternatives you've considered

It's possible to just manually schedule a block with an event for travel time, but that's clutters the calendar with events that aren't really events - and is why Apple created the Travel Time feature.

### Additional context

The data seems to be already available from CalDAV as someone posted here:
https://community.home-assistant.io/t/caldav-add-support-for-travel-time/525502

### Requirement/Document

N/A

**Comment by rishi-raj-jain** [comment]
@baileypumfleet Would like to work on this. Would love some initial direction.

**Comment by nicktrn** [comment]
A few thoughts:

1. Blocking off travel time _before_ the event makes sense
2. What about _after_? Do we just block off the same travel time again, i.e. there and back?
3. Maybe it should depend on the event type, e.g. in-person meeting vs call
4. Does it work the other way around, i.e. Cal -> Apple? Buffer time is essentially the same thing.

Needs some discussion. To keep things simple it could just be added before the event.

I will submit a draft PR for now to handle the custom prop if it's present and block off additional time.

**Comment by alishaz-polymath** [comment]
I wonder if this can be sorted with buffer time 🤔 
It is definitely a cool-to-have feature, however, only when it is reliable. I understand that buffer time is probably a constant and the travel time would be variable depending upon the location, but, it might be a nice workaround for the time being.

**Comment by nicktrn** [comment]
I assumed the issue was only regarding travel time for non-Cal.com events. But of course there is a scenario where organizers could retrospectively add travel time to the Apple Calendar entries that Cal creates for bookings.

**Comment by alishaz-polymath** [comment]
> I assumed the issue was only regarding travel time for non-Cal.com events. But of course there is a scenario where organizers could retrospectively add travel time to the Apple Calendar entries that Cal creates for bookings.

Ah, that's a good point. As long as we can make it reliable 🎉

**Comment by nicktrn** [comment]
I don't see any issues for availability checks to consider travel time before the event start. I will modify the PR to only consider that scenario for now and get it ready to merge ASAP. The rest can be discussed later I think.

**Comment by andreyrd** [comment]
> A few thoughts:
> 
>     1. Blocking off travel time _before_ the event makes sense
> 
>     2. What about _after_? Do we just block off the same travel time again, i.e. there and back?
> 
>     3. Maybe it should depend on the event type, e.g. in-person meeting vs call
> 
>     4. Does it work the other way around, i.e. Cal -> Apple? Buffer time is essentially the same thing.
> 
> 
> Needs some discussion. To keep things simple it could just be added before the event.
> 
> I will submit a draft PR for now to handle the custom prop if it's present and block off additional time.

Thanks so much for implementing! Yeah ultimately I was just looking for parity with what Apple Calendar currently does.

2. Apple Calendar doesn't do _after_ - so for anyone using it they aren't expecting _after_ to be blocked off.
4. Handling input of a non-standard Apple-only feature is nice for fully supporting Apple calendar - but writing it for new events is not necessary unless it becomes a standard CalDAV thing imo.
