### ISSUE TITLE
[CAL-2274] In Person Attendee Address translation key is shown instead of value.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10476]
If In Person(Attendee Address) is selected, the Current Location during 'Edit Location' flow of the booking shows the key instead of the label.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/90046ba9-8909-4417-a6b3-712eab8eb220/c01513f4-eb69-4f04-b4bc-3e15c5856049?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MDA0NmJhOS04OTA5LTQ0MTctYTZiMy03MTJlYWI4ZWIyMjAvYzAxNTEzZjQtZWI2OS00ZjA0LWI0YmMtM2UxNWM1ODU2MDQ5IiwiaWF0IjoxNjkwNzg0NjYwLCJleHAiOjE2OTA4NzEwNjB9.qSMfPRi4t_hVa30tUmC6LrbPL1AzY_Z_5X17R1aEu4c)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2274](https://linear.app/calcom/issue/CAL-2274/in-person-attendee-address-translation-key-is-shown-instead-of-value)</sub>

**Comment by cherish2003** [comment]
<img width="1213" alt="Screenshot 2023-07-31 at 1 04 50 PM" src="https://github.com/calcom/cal.com/assets/88829894/22db8e9a-dcef-42fc-89c2-4bce3949590e">
@hariombalhara  i am able see it in bookings page can you specify the page where it is occurring ?

**Comment by hariombalhara** [comment]
I think you have chosen organizer address. Happens for attendee address

**Comment by subr1oto** [comment]
![Screenshot from 2023-07-31 15-52-29](https://github.com/calcom/cal.com/assets/114584787/231ba1cc-590a-48be-aca9-d8246c8fe53e)
I don't think there is any bug here at attendee address

**Comment by cherish2003** [comment]
> ![Screenshot from 2023-07-31 15-52-29](https://user-images.githubusercontent.com/114584787/257192262-231ba1cc-590a-48be-aca9-d8246c8fe53e.png) I don't think there is any bug here at attendee address

Now if you try update again it will result in bug
<img width="1148" alt="Screenshot 2023-07-31 at 4 05 01 PM" src="https://github.com/calcom/cal.com/assets/88829894/468d1f35-dcf7-44d7-b4f5-c3ffc71874d9">

**Comment by cherish2003** [comment]
@hariombalhara  the same issue is occuring for attendee phone number also the major reason for both issues is that we are trying to get `in_person_attendee_address` and `attendee_phone_number` but the values should be given by the attendee while booking the meeting itself but that's not the case so it is resulting in this bug 
<img width="806" alt="Screenshot 2023-07-31 at 4 34 04 PM" src="https://github.com/calcom/cal.com/assets/88829894/7233d176-3843-4a45-b6d8-1ece04ea7da5">

As you can see here i have selected the my attendee place while booking itself 
<img width="1254" alt="Screenshot 2023-07-31 at 4 44 57 PM" src="https://github.com/calcom/cal.com/assets/88829894/99aea0e2-f04a-49cc-a6be-65b4bac7f211">

Now i can see it is working fine
<img width="1201" alt="Screenshot 2023-07-31 at 4 46 16 PM" src="https://github.com/calcom/cal.com/assets/88829894/f846a886-166e-48c0-9d3f-c6013294a882">

what are your comments on my explanation ?

**Comment by subr1oto** [comment]
but there should be a proper validation, at beginning so user cannot proceed before entering required details, and this is a bug. I don't understand from where it is getting default value as new value entered from edit address input field does not appear to be change.
