### ISSUE TITLE
[CAL-2277] Fix String of Text in Workflows under Booking Questions

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10490]
![CleanShot 2023-07-31 at 10.29.05@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/448c0830-f79c-4360-9fa6-bd8602d04aaa/0395fa75-21a7-4291-89bd-16c14168ec6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NDhjMDgzMC1mNzljLTQzNjAtOWZhNi1iZDg2MDJkMDRhYWEvMDM5NWZhNzUtMjFhNy00MjkxLTg5YmQtMTZjMTQxNjhlYzZhIiwiaWF0IjoxNjkwODM1Mzk4LCJleHAiOjE2OTA5MjE3OTh9.OMHLoxKNUOmpXMmoo1EYQss6QEknVGNrSU4sbOzQipo)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2277](https://linear.app/calcom/issue/CAL-2277/fix-string-of-text-in-workflows-under-booking-questions)</sub>

**Comment by Rishi143** [comment]
Can you please elaborate on what to be fixed here?

**Comment by rkreddy99** [comment]
Hey @Rishi143 so calcom uses i18n for translations, and `number_sms_notifications` is a key for which you have to provide the translation instead of directly showing that.

For reference check other fields in the same form.

**Comment by N-NeelPatel** [comment]
@rkreddy99 - how to add workflows in booking questions?
