### ISSUE TITLE
 'auth' Can be Registered as User

### ISSUE THREAD

**Issue by Tanmai2002** [calcom/cal.com#10495]
Found a bug? Please fill out the sections below. 👍
### Issue Summary
![image](https://github.com/calcom/cal.com/assets/40868910/8f19b1f0-c079-4102-98e2-b38fa6c9158c)

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. try going to cal.com/auth

This is a bug and mostly a ambiguity bug.
### Actual Results

- Can create a user 'auth' into 
### Expected Results
User should not be able to create users with api keywords like auth.
Else:
path should be changed to somthing like localhost/user/{username}/{...}

### Evidence
![image](https://github.com/calcom/cal.com/assets/40868910/56b20fb1-30d6-4814-a046-1aac8b1640ff)
![image](https://github.com/calcom/cal.com/assets/40868910/ba7bf421-7bc2-4386-871f-98ee4537476a)

I was able to create event with login leading to path as localhost/auth/login-> Now technically points to 2 locations
When I tried : localhost/auth-> 
![image](https://github.com/calcom/cal.com/assets/40868910/bb3d818d-9400-4007-b02b-e4ed1818f395)

When I clicked Login Page it led me Login in page rather than to calendar for scheduling

**Comment by Tanmai2002** [comment]
I want to solve this Issue. Can you assign this to me?

**Comment by Tanmai2002** [comment]
![image](https://github.com/calcom/cal.com/assets/40868910/402287e4-2897-4684-8b4b-16e591f222f5)
Since auth was premium, i tried creating with other username. 
https://cal.com/getting-started/test
### Expected Behavior:
Show Calendar

###Actual Behavior

Logged In: Dashboard (`/event-types`)
Not Logged In: Login Page (`/auth/login`)

**Comment by wolf-4bit** [comment]
I believe we should change the API endpoint to ```/user/{name}``` since it is more user-friendly and imposing restrictions over usernames would result in bad UX. The user shouldn't be concerned with the technical details of the app.

**Comment by PeerRich** [comment]
we wont change links to cal.com/user/peer it'll always be cal.com/peer

we can just overwrite the /auth/ endpoint and redirect it

**Comment by Tanmai2002** [comment]
@PeerRich  This issue is not only associated just with auth, it is also associated with all the api keyword. As i attached earlier, it also gives issue with getting-started and other api ends
