### ISSUE TITLE
[CAL-4740] Embed brand colors doesn't work properly

### ISSUE THREAD

**Issue by prateekjain98** [calcom/cal.com#10497]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The brand color set in the Settings>Appearance is not set automatically in the brand color in embeds. When I try to set brand color from the color picker, it is set only for one theme, either dark or light. 

### Steps to Reproduce

1. Set your brand colors in Settings>Appearance.
2. Open embeds from an event. Select inline embeds.
3. The brand color is not selected according to the colors set in Settings.
4. When I select the brand color, it is only visible in preview for one theme, either light or dark.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

Brand color is not being set properly

### Expected Results

I shouldn't have to set brand colors in the embeds as it's already set in the settings. If the option to set brand colors is still required, the selected value should be according to the colors selected in the settings and should be available for both the themes.

### Technical details

https://app.birdeatsbug.com/sessions/N2G-znF0x0ipbn--ofl88su--GlD613Iqo31PVJsPl7G

### Evidence

Manual testing. Video recording attached above

<sub>[CAL-4740](https://linear.app/calcom/issue/CAL-4740/embed-brand-colors-doesnt-work-properly)</sub>

**Comment by pratyush3124** [comment]
Hey I have opened a PR solving this issue, could someone review it please.
