### ISSUE TITLE
Select different schedules for specific dates

### ISSUE THREAD

**Issue by jayeshsidhwani** [calcom/cal.com#10510]
### Is your proposal related to a problem?

Sometimes I travel to different time zones for a longer period. I cannot plan my availability ahead of time because I can use only a single availability schedule per event type

### Describe the solution you'd like

For each event type, I should be able to select different availability schedules for a block of dates. Each availability schedule can be set for a different time-zone. Because I know my travel plans ahead of time, I can adjust my availability based on different time-zones for different days

### Describe alternatives you've considered

Right now, I have to change my availability schedule a few days before my travel 

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by PeerRich** [comment]
duplicate of https://github.com/calcom/cal.com/issues/6790
