### ISSUE TITLE
[CAL-2281] payload and headers wrong for meeting ended webhook trigger

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#10516]
### Issue Summary

The webhook "MEETING_ENDED" has a content-type header "text/plain". It should be application/json
<img width="433" alt="Screenshot 2023-08-01 at 16 43 34" src="[https://github.com/calcom/cal.com/assets/30310907/7d697f81-d0ef-4a24-8bff-b2fb0b94e1ad](https://github.com/calcom/cal.com/assets/30310907/7d697f81-d0ef-4a24-8bff-b2fb0b94e1ad)">

Also payload doesn't look the exact same as for the other triggers and custom payload isn't working.

### Expected Results

Payload and headers for the  "MEETING_ENDED"  trigger should be the same as for all other triggers.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2281](https://linear.app/calcom/issue/CAL-2281/payload-and-headers-wrong-for-meeting-ended-webhook-trigger)</sub>

**Comment by IMPranshu** [comment]
I am working on fixing this issue. Please assign this to me.

**Comment by CarinaWolli** [comment]
Great, no need to assign you. You can start working on it and just link this issue in your PR :)

**Comment by CarinaWolli** [comment]
Tested and this is already fixed
