### ISSUE TITLE
Cannot disconnect Google integration with an `invalid_grant`

### ISSUE THREAD

**Issue by timfee** [calcom/cal.com#1051]
### Steps to Reproduce

1. Connect Google Calendar to Cal.com
2. Revoke permissions.
3. Visit integrations screen.
4. Observe the following behavior:

![Screen Shot 2021-10-26 at 08 39 51](https://user-images.githubusercontent.com/3246342/138913726-11647c51-0f0e-4dc7-a9a4-d7e730a9cd7b.gif)

### Technical details

- Browser version: Safari 15
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15`

**Comment by redhoyasa** [comment]
I have tested this and it's already fixed.

**Comment by PeerRich** [comment]
i think this was fixed a log time ago
