### ISSUE TITLE
[CAL-2285] Orgs: Apps - Install app on dropdown has unusual order and "Nameless"\

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10542]
* Returns "Nameless" user for me
* The order currently is
  * User
  * Team
  * Org
  * Team
  * Team

![CleanShot 2023-08-02 at 16.47.50@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b27ff05e-a008-43f8-b27c-7cef6d2e2e50/4275a3f3-af86-4211-bec4-c1acf3405240?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iMjdmZjA1ZS1hMDA4LTQzZjgtYjI3Yy03Y2VmNmQyZTJlNTAvNDI3NWEzZjMtYWY4Ni00MjExLWJlYzQtYzFhY2YzNDA1MjQwIiwiaWF0IjoxNjkwOTkxNjQwLCJleHAiOjE2OTEwNzgwNDB9.w6nx1czp6rF8u9YENQfr0yKrQOQ75ZNt-p81cyFbctU)

**Ultimately we want org wide apps.**

![CleanShot 2023-08-02 at 16.51.13@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/861fa99b-48fb-4345-bcd3-b9682905a6f4/ed9ac599-f8d3-420b-8f9d-92afe81725f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84NjFmYTk5Yi00OGZiLTQzNDUtYmNkMy1iOTY4MjkwNWE2ZjQvZWQ5YWM1OTktZjhkMy00MjBiLThmOWQtOTJhZmU4MTcyNWYyIiwiaWF0IjoxNjkwOTkxNjQwLCJleHAiOjE2OTEwNzgwNDB9.if24gCylD5PfWKTdgDVXpQMRt8gWsMWxWKVR7CTNGdU)

**But in the mean time we should at least do**

* User
* Org
* Team
* Team

![CleanShot 2023-08-02 at 16.53.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cb0841ff-9512-4952-aff7-288d359b4b65/5431d4f9-37a0-412c-b738-be264b1edd86?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jYjA4NDFmZi05NTEyLTQ5NTItYWZmNy0yODhkMzU5YjRiNjUvNTQzMWQ0ZjktMzdhMC00MTJjLWI3MzgtYmUyNjRiMWVkZDg2IiwiaWF0IjoxNjkwOTkxNjQwLCJleHAiOjE2OTEwNzgwNDB9.fxxDT90pkefzdS7vPr3UV7qv-cukteMsgnLosbe9oMo)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2285](https://linear.app/calcom/issue/CAL-2285/orgs-apps-install-app-on-dropdown-has-unusual-order-and-nameless\)</sub>

**Comment by babblebey** [comment]
Hi @Jaibles 

New here! I can try patch a fix for this if you will assign me.

**Comment by AkshayBandi027** [comment]
Hey @Jaibles, tried to reproduce it, but it worked correctly. I don't think there is any issue.
