### ISSUE TITLE
[CAL-2284] Orgs: Trying to access members team within an org shows blank members area then goes to white screen of death

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10540]
https://github.com/calcom/cal.com/assets/4536123/e1dee40e-9219-44b6-a11d-8b77f9636058

<sub>[CAL-2284](https://linear.app/calcom/issue/CAL-2284/orgs-trying-to-access-members-team-within-an-org-shows-blank-members)</sub>

**Comment by sean-brydon** [comment]
Can't replicate 🤔can you add me to one of the effected teams? 

@Jaibles

**Comment by keithwillcode** [comment]
@Jaibles Is this still a bug?

**Comment by Jaibles** [comment]
No I don't think so.
