### ISSUE TITLE
Slots Endpoint does not Provide End Time for each Slot

### ISSUE THREAD

**Issue by flcno** [calcom/cal.com#10548]
### Is your proposal related to a problem?
This proposal is to make the slots endpoint easier to use to generate an array of available time slots with start AND end time in the response. As a Cal.com user that only uses the backend functionality and does not use the front-end functionality, the seamlessness of the API is crucial for us.

Currently, the Slots endpoint within the Cal.com API does not provide an end time for each slot. Although one may implicitly determine it by checking the duration assigned to the eventTypeId, it does not make the response very user friendly. It seems counterintuitive to then attempt to use the create booking endpoint as it requires a start and end time in the request body.

# Example Response:
```json
{
    "slots": {
        "2023-08-03": [
            {
                "time": "2023-08-03T13:00:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T13:30:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T14:00:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T14:30:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T15:00:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T15:30:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T16:00:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T16:30:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T17:00:00.000Z",
                "users": []
            },
            {
                "time": "2023-08-03T17:30:00.000Z",
                "users": []
            }
        ]
    }
}
```
### Describe the solution you'd like

The proposed improvement would make the current response to the API (example above) look more like this:
```json
{
    "slots": {
        "2023-08-03": [
            {
                "startTime": "2023-08-03T13:00:00.000Z",
                "endTime": "2023-08-03T13:30:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T13:30:00.000Z",
                "endTime": "2023-08-03T14:00:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T14:00:00.000Z",
                "endTime": "2023-08-03T14:30:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T14:30:00.000Z",
                "endTime": "2023-08-03T15:00:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T15:00:00.000Z",
                "endTime": "2023-08-03T15:30:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T15:30:00.000Z",
                "endTime": "2023-08-03T16:00:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T16:00:00.000Z",
                "endTime": "2023-08-03T16:30:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T16:30:00.000Z",
                "endTime": "2023-08-03T17:00:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T17:00:00.000Z",
                "endTime": "2023-08-03T17:30:00.000Z",
                "users": []
            },
            {
                "startTime": "2023-08-03T17:30:00.000Z",
                "endTime": "2023-08-03T18:00:00.000Z",
                "users": []
            }
        ]
    }
}
```
### Describe alternatives you've considered

1. I have considered an assumption of duration based on a check of details of the eventTypeId
2. I have considered programmatically determining the endTime on the front-end for each slot

**Comment by Abhijeetmishr** [comment]
@PeerRich @hf-nfalcione 
can I pick this up ?
my localhost is running successfully how do I reproduce this ?

**Comment by hf-nfalcione** [comment]
> @PeerRich @hf-nfalcione can I pick this up ? my localhost is running successfully how do I reproduce this ?

To reproduce in Postman, I used the Get User Available Slots endpoint with a fork of the Cal.com API postman collection. I created a DEV API key to use and created an account within Cal.com public and attached that as a query param.

My request under the hood looked like:
```bash
curl --location 'https://api.cal.com/slots?usernameList=<user-name-goes-here>&eventTypeSlug=30min&startTime=2023-08-07&endTime=2023-08-09&timeZone=America%2FToronto&apiKey=<your-api-key-goes-here>' \
--data ''
```

**Comment by a5r0n** [comment]
Is there any documentation for this API endpoint?

**Comment by hf-nfalcione** [comment]
> Is there any documentation for this API endpoint?

I don't think there is documentation for the slots endpoint here:
https://cal.com/docs/enterprise-features/api/api-reference#managing-users
