### ISSUE TITLE
[CAL-2286] UI: We need a better way to handle stacked top banners

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#10543]
![CleanShot 2023-08-02 at 17.00.55@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5dc19f7f-ff78-4f88-a18e-7248f7e33e8b/2d4be636-b935-448f-8dd9-4c298a77f31f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ZGMxOWY3Zi1mZjc4LTRmODgtYTE4ZS03MjQ4ZjdlMzNlOGIvMmQ0YmU2MzYtYjkzNS00NDhmLThkZDktNGMyOThhNzdmMzFmIiwiaWF0IjoxNjkwOTkyMTA5LCJleHAiOjE2OTEwNzg1MDl9.0MFDEps8cDS1xIa5fzqeiJbYsbb1OwtDdot5JZq9zA0)

We need to paginate these.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2286](https://linear.app/calcom/issue/CAL-2286/ui-we-need-a-better-way-to-handle-stacked-top-banners)</sub>

**Comment by PeerRich** [comment]
low prioirty, doesnt happen often either
