### ISSUE TITLE
[CAL-2325] Showing verify email option on top even after I verified my email two times.

### ISSUE THREAD

**Issue by iSatVeerSingh** [calcom/cal.com#10541]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am new to [cal.com](http://cal.com). I have created a new account. I have already verified my email two times. Still, I am seeing verify your email option, and after clicking on it, it is sending a verification email.

### Steps to Reproduce

1. Create a new account.
2. verify your email address
3. login into your account
4. after some time refresh the page and see verify email option top of the page

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* What's happening right now that is different from what is expected

### Expected Results

* I should not see the email verification option after I verify the email for the first time.

### Technical details

* I have created an account on [cal.com](http://cal.com), which is production website.
* Browser - Chrome Version 115.0.5790.110 (Official Build) (64-bit)
* Linux

### Evidence

* 

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c3c08fa8-24dc-42f2-8067-96c23b0a4e6a/b82eafbb-3c2e-4df2-8991-263435e515e0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jM2MwOGZhOC0yNGRjLTQyZjItODA2Ny05NmMyM2IwYTRlNmEvYjgyZWFmYmItM2MyZS00ZGYyLTg5OTEtMjYzNDM1ZTUxNWUwIiwiaWF0IjoxNjkxNTkwNTY1LCJleHAiOjE2OTE2NzY5NjV9.fikp7l5_CkIewhjPHQhx4RMB22QSH7Pfwa3qGa-bF3M)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2325](https://linear.app/calcom/issue/CAL-2325/showing-verify-email-option-on-top-even-after-i-verified-my-email-two)</sub>

**Comment by Udit-takkar** [comment]
i am not able to reproduce this bug. i also got the top banner a few times but not now. @iSatVeerSingh any other information that might help me to reproduce this bug?

**Comment by iSatVeerSingh** [comment]
Not happening now.
