### ISSUE TITLE
Dialog Box Padding Issue

### ISSUE THREAD

**Issue by vishwasganatra** [calcom/cal.com#10558]
The Confirm username change dialog box has improper padding for buttons cancel and save.

Steps to Reproduce

1. Go to Profile
2. Enter a new username and Click on Update

![2023-08-03 17_03_58-Profile _ Cal com](https://github.com/calcom/cal.com/assets/65550758/5f5474c7-9c07-492e-a4c1-4d2f6fc671ec)

**Comment by vishwasganatra** [comment]
Hey team, if you think this issue falls under low priority bug, would love to fix it, as am I starting to explore cal.com's code base. Thanks!

**Comment by ZainGulbaz** [comment]
I have made a pull request for this issue: #10629
