### ISSUE TITLE
Spacing issue in Documentation

### ISSUE THREAD

**Issue by vishwasganatra** [calcom/cal.com#10559]
Was going through Cal.com documentation and found a spacing mistake.

Steps to Reproduce
1. Went to Event types > Location of events

![2023-08-03 17_12_29-Location of the event - Cal com Docs](https://github.com/calcom/cal.com/assets/65550758/ffa34409-aaef-4f93-b293-3bd294d09d03)

**Comment by DkRadhey** [comment]
@vishwasganatra I would like to work on this issue. Could you please assign it to me?

**Comment by alishaz-polymath** [comment]
Hi @DkRadhey Thank you for offering it, however, we don't have the docs github integration in place yet. 🙏
