### ISSUE TITLE
Dynamic Event Rescheduling has Disabled && Mandatory fields

### ISSUE THREAD

**Issue by jobenjada** [calcom/cal.com#10554]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Dynamic Event Rescheduling has Disabled && Mandatory fields

### Steps to Reproduce
1. Setup dynamic event with +
2. Try to reschedule 

### Actual Results

- Couldnt reschedule bc disabled fields are mandatory

### Expected Results

- Let me reschedule

### Evidence

![grafik](https://github.com/calcom/cal.com/assets/72809645/af35b634-8265-42cd-898e-6d73c9fd37c3)

https://app.cal.com/kristian-mikhel-o0bkzq+johannes/dynamic?rescheduleUid=5zdpZAyNAPALjRtvCdo3a8&duration=60&date=2023-08-10&month=2023-08&slot=2023-08-10T12%3A00%3A00.000Z

**Comment by DivyanshuP11** [comment]
I think this event is not reschedulable here is an attachment of the code 
![image](https://github.com/calcom/cal.com/assets/81802699/3f93d562-575e-49c5-af31-37bee7330c9b)

**Comment by alishaz-polymath** [comment]
Thank you @DivyanshuP11 
Yeah, it seems to be currently non rescheduleable but it's probably worth exploring if we can make it rescheduleable or do we need to simply block it in the UI as well. Worth exploring.

**Comment by DivyanshuP11** [comment]
Yes, I will explore the options of making it reschedulable or simply blocking and showing a message to the user. Whatever is best will try to work on it.
