### ISSUE TITLE
[CAL-2310] Cancelling a single seat cancels entire booking.

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#10551]
Again being reported, but I think we already have a test for this.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2310](https://linear.app/calcom/issue/CAL-2310/cancelling-a-single-seat-cancels-entire-booking)</sub>

**Comment by alannnc** [comment]
Did a run on local and everything is working. Test working too.
Should close if @joeauyeung verifies this too.

**Comment by joeauyeung** [comment]
Verified locally that this working as expected. Closing for now.
