### ISSUE TITLE
[Bug]: Selected section not highlighted (App Store and Installed Apps)

### ISSUE THREAD

**Issue by RohitSaini15** [calcom/cal.com#10553]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

App Store and Installed Apps not highlighted(selected) when it gets clicked unlike the other ones.

### Steps to Reproduce

1. Go to cal.com
2. Clicked on Apps Section on the left side navigation bar.
3. Click on the Installed Apps or App Store.

### Actual Results

![bug cal com](https://github.com/calcom/cal.com/assets/71682713/1baa8fff-7cca-4cde-8aa4-3e532e3119d5)

Installed Apps is selected in the above image but it is not highlighted in the navigation bar.

**Comment by Anshul1811** [comment]
@Udit-takkar  I want to work on this issue.

**Comment by tarunclub** [comment]
@RohitSaini15 The text is highlighted though when you click on it

**Comment by RohitSaini15** [comment]
it highlights when you hover over it. it doesn't stay when you click on it like it happens with other navigation options.

**Comment by GamerQuanTuM** [comment]
Is it still open

**Comment by finalyeargroup9** [comment]
i want to work on this issue
