### ISSUE TITLE
[CAL-2307] Unneeded wait time with getSchedule after session

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#10564]
> Fix issue where we wait to load getSchedule after the session call has completed. It’s a public endpoint and doesn’t need a session, correct?

![](https://lh6.googleusercontent.com/\_ohsJxz3em_tlL4O7Zo1_VB9zrQkKYOfkiZprD0SdkXXvZJAtll2p1p3BfalQ-48QdUYTk8wp0q5kRg0lNejjMUAt47hlFujpinCK7jx4-Cs8Pc3Cuu6MvS0wA3tUyCcplL8JD99jRYBCEQdSfCm5tg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2307](https://linear.app/calcom/issue/CAL-2307/unneeded-wait-time-with-getschedule-after-session)</sub>

**Comment by leog** [comment]
@alannnc We are moving this to Urgent and Udit is going to take it right now.

**Comment by keithwillcode** [comment]
^^ That comment was actually by me. Seems to be a bug with SyncLinear.

**Comment by hariombalhara** [comment]
@alannnc has a PR open for it already for the duplicate ticket #10552

**Comment by keithwillcode** [comment]
This was fixed.
