### ISSUE TITLE
Video links are not added to events when multiple locations are options

### ISSUE THREAD

**Issue by fross123** [calcom/cal.com#1056]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When allowing users to choose from multiple locations for an event, no link to a video meeting is added to either the calendar event or the notification email. When only one location is available for the event, ie: user does not make a location selection to book a time, the link is created as normal (notwithstanding other bug report #1054).

### Steps to Reproduce

1. Create a new event
2. Add Google Meet or Daily as the location
3. Preview the event/create a test booking
4. Video chat link is added to the email and calendar
5. Edit event to add another location. (ex: Now both Google Meet and Daily.co should be options for location)
6. Preview the event/create another test booking
7. Video chat link does not appear in the email or in the calendar event.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: Chrome 95 on MacOS Big Sur, Safari 15
- Node.js version: v14.18.1
- Anything else that you think could be an issue.

**Comment by artistro08** [comment]
Not sure if this isn't marked as fixed, but in the self-hosted version, I can successfully add two different types of locations.

**Comment by sean-brydon** [comment]
Closing - this was fixed https://github.com/calcom/cal.com/pull/2161/
