### ISSUE TITLE
[CAL-2316] Fix Contact support button

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#10579]
https://discord.com/channels/1125390093386010654/1136285402244845608/1136697091700310016

<sub>[CAL-2316](https://linear.app/calcom/issue/CAL-2316/fix-contact-support-button)</sub>

**Comment by itsvanshchavda** [comment]
@Udit-takkar Give some images & description which contact button ?

**Comment by Mritunjay0001** [comment]
I will fix this , can you assign me
