### ISSUE TITLE
Email missing at Rescheduling

### ISSUE THREAD

**Issue by sgineiger** [calcom/cal.com#10571]
### Issue Summary

Missing Emails for Rescheduling bookings  (new booking and cancelling emails are sent!).

### Steps to Reproduce

1. Book an booking with a customer email
2. Read the email sent to the customer
3. Click on the link to Rescheule or cancel
4. Change the event to other time and click  "Reschedule"

### Actual Results

1. There are no email sent after Reschedule
2. Info: at creating and cancelling events, emails are sent to organizer and customer

### Expected Results

Reschedule sends emails to customer and organizer

### Technical details

- cal.com (self-hosted, no licence)

### Evidence

![Screenshot cal com rescheduling](https://github.com/calcom/cal.com/assets/41108014/b5b1d897-ca11-458a-a3dd-3790469adfc5)

**Comment by Raju-github-profile** [comment]
Hey !! Wanted some help ??
I have setup everything as said in documentation to run locally in my system.When I do login , it simply remains on that page and do not navigate to any other page.
I have provided my console info below in screenshot. Please help me out..I want to do some contributions in this project.

![Screenshot (310)](https://github.com/calcom/cal.com/assets/108010466/6a0fffc2-ada1-487a-91b1-d96bcc49c61d)

![Screenshot (311)](https://github.com/calcom/cal.com/assets/108010466/41401d20-2f60-4bf8-99e9-4309e2078b3b)

**Comment by ibharatsaini** [comment]
Reschedule and cancellation notification emails are being sent on my end. Can you record a video of the bug?

**Comment by sgineiger** [comment]
Thank you all for your support - I found it - had an old version of cal.com(2.4.7). Update solved the problem.
