### ISSUE TITLE
Problem Selecting Invitees can Schedule Radio Button on Event Types Page

### ISSUE THREAD

**Issue by justshrey** [calcom/cal.com#1057]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The event types detail page - advanced option - Invitees can Schedule Radio Button is not working

### Steps to Reproduce

1. Have tried both on hosted version as well a self hosted version
2. See below

https://user-images.githubusercontent.com/1253625/139180040-f8a1d4fb-d25f-4630-b3e4-80e4044c2df5.mp4

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

Have tried on both in chrome and firefox

- Node.js version
- Anything else that you think could be an issue.

Have figured out a fix  - raising an issue to map to PR

**Comment by PeerRich** [comment]
i think this was fixed a log time ago
