### ISSUE TITLE
Cancelling Email contain variables instead of real text

### ISSUE THREAD

**Issue by sgineiger** [calcom/cal.com#10573]
### Issue Summary

Cancelling Emails contain variable names instead of the real text. 

### Steps to Reproduce

1. create a booking
3. cancel the booking  
4. read the cancelling email
5. change language to german
6. create a booking
7. cancel the booking
8. read the cancelling email

### Actual Results

The email contains variable names instead of the real text
1. event_cancelled_subject both in the english and german mail body
2. {{ eventType }} and {{ name }} in the german mail subject

normal booking emails contain the real text, in german and english.

### Expected Results

 cancelling emails contain text, not variables, in german and in english.

### Technical details

self hosted cal.com.

### Evidence

Wrong Germain Cancelling Mail: ![image](https://github.com/calcom/cal.com/assets/41108014/bc06f590-9b23-438a-9a91-9215811df742)
Wrong English Cancelling Mail: ![image](https://github.com/calcom/cal.com/assets/41108014/977b8d17-d4b8-436b-9c79-d0ca60219e5a)
Correct German Booking Mail: ![image](https://github.com/calcom/cal.com/assets/41108014/22aa051c-6e22-42e1-af09-8fd2ed21b02b)
Correct English Booking Mail: 
![image](https://github.com/calcom/cal.com/assets/41108014/d51ada49-8295-4ccb-b6a7-a3093a280ab9)

Videos - for the german part:
1) booking and cancelling: https://github.com/calcom/cal.com/assets/41108014/83fbc6aa-ac4d-4af8-bf97-ee5ee46327b4
2) the correct booking mail: https://github.com/calcom/cal.com/assets/41108014/cc52d0f0-fa5b-46f1-a63e-ce813f3c276a
3) the problem cancelling mail: https://github.com/calcom/cal.com/assets/41108014/1c3f5ac4-4d96-4a17-bb2e-2cf1670e388d

**Comment by Abhijeetmishr** [comment]
Hey @sgineiger,
Can I work on this ?
I have completed my local setup successfully.

**Comment by sgineiger** [comment]
Hi @Abhijeetmishr,
I just submitted my first two bugs, maybe I don't understand the process here, but I know nothing against you working on this. So, yes. :-)

**Comment by Abhijeetmishr** [comment]
> Hi @Abhijeetmishr, I just submitted my first two bugs, maybe I don't understand the process here, but I know nothing against you working on this. So, yes. :-)
Hey @sgineiger can you help me with reproducing the error.
a short video will be very helpful in debugging.
So that I can mimic the process.

**Comment by sgineiger** [comment]
> > Hi @Abhijeetmishr, I just submitted my first two bugs, maybe I don't understand the process here, but I know nothing against you working on this. So, yes. :-)
> 
> **Hey @sgineiger can you help me with reproducing the error. a short video will be very helpful in debugging. So that I can mimic the process.**

Hi @Abhijeetmishr - See on the bottom of the bug I uploaded 3 small videos, hope this helps.

**Comment by Abhijeetmishr** [comment]
> > > Hi @Abhijeetmishr, I just submitted my first two bugs, maybe I don't understand the process here, but I know nothing against you working on this. So, yes. :-)
> > 
> > 
> > **Hey @sgineiger can you help me with reproducing the error. a short video will be very helpful in debugging. So that I can mimic the process.**
> 
> Hi @Abhijeetmishr - See on the bottom of the bug I uploaded 3 small videos, hope this helps.

Great @sgineiger I appreciate this.

**Comment by PeerRich** [comment]
go for it @Abhijeetmishr (

**Comment by Abhijeetmishr** [comment]
Hi @PeerRich 
this is the piece of code we are concerned about if I am not wrong ?

**AttendeeCancelledMail**

```
import { renderEmail } from "../";
import AttendeeScheduledEmail from "./attendee-scheduled-email";

export default class AttendeeCancelledEmail extends AttendeeScheduledEmail {
  protected getNodeMailerPayload(): Record<string, unknown> {
    return {
      to: `${this.attendee.name} <${this.attendee.email}>`,
      from: `${this.calEvent.organizer.name} <${this.getMailerOptions().from}>`,
      replyTo: this.calEvent.organizer.email,
      subject: `${this.t("event_cancelled_subject", {
        title: this.calEvent.title,
        date: this.getFormattedDate(),
      })}`,
      html: renderEmail("AttendeeCancelledEmail", {
        calEvent: this.calEvent,
        attendee: this.attendee,
      }),
      text: this.getTextBody("event_request_cancelled", "emailed_you_and_any_other_attendees"),
    };
  }
}

```

**Comment by Abhijeetmishr** [comment]
Hi @PeerRich How to check the mail ? I am able to book and cancel the meeting in local env.
I am using this Pro@example.com user.

Regards,
Abhijeet

**Comment by keithwillcode** [comment]
@Abhijeetmishr We have configuration built in that sets up mailhog locally. Were you able to use the instructions in the [README](https://github.com/calcom/cal.com#manual-setup) to get it running?

**Comment by Abhijeetmishr** [comment]
> @Abhijeetmishr We have configuration built in that sets up mailhog locally. Were you able to use the instructions in the [README](https://github.com/calcom/cal.com#manual-setup) to get it running?

@keithwillcode Yes I am able to run cal.com locally using README instructions and I can see the postgres and mailhog running in docker.
Where do I check if  want to check exact mail template while booking/cancelling in local env ?

**Comment by BhargavaCreates** [comment]
@Abhijeetmishr  has this been solved?

**Comment by MahithChigurupati** [comment]
@keithwillcode @PeerRich ,

i just tried replicating this issue in local setup, looks like things are working fine now as i don't see any variables in the mail i received in mailhog upon booking cancelation.

attaching screenshot for reference -

![image](https://github.com/calcom/cal.com/assets/62823527/6cbd1a45-d31b-42ac-abd1-3dae8c53336e)

**Comment by keithwillcode** [comment]
@MahithChigurupati Amazing. Thanks for testing!
