### ISSUE TITLE
[CAL-2317] E2E: Headless Router - Response collection 

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10586]
Once [this](https://github.com/calcom/cal.com/pull/9183) PR is merged, we need a test to verify that headless router is correctly collecting data.

We can add the test [here](https://github.com/calcom/cal.com/blob/9c823e4b428dd5f7d1ded7e1d9cd0c53ba51474e/packages/app-store/routing-forms/playwright/tests/basic.e2e.ts#L292) 

<sub>[CAL-2317](https://linear.app/calcom/issue/CAL-2317/e2e-headless-router-response-collection)</sub>

**Comment by adarsh-technocrat** [comment]
Hi, @hariombalhara I can take this up, once PR gets merged!

Thanks :)

**Comment by keithwillcode** [comment]
@adarsh-technocrat that PR was merged. Any interest in taking this one still?
