### ISSUE TITLE
Padding missing between icons and loading skeleton.

### ISSUE THREAD

**Issue by AbhijitMatsagar** [calcom/cal.com#10587]
Found a bug? Please fill out the sections below. 👍

Padding missing between icons and loading skeleton.

A summary of the issue. This needs to be a clear detailed-rich summary.
There should be padding between icons and the loading skeleton. While loading the page icons and loading skeleton attach together and then after loading complete text bounce vertically. That doesn't look natural.

### Steps to Reproduce

1. Got to Apps
2. Then installed apps.
3. then reload the page you will see the issue

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- No padding between icons and text. Text bounces vertically after loading.

### Expected Results

- There should be padding between the icons and loading skeleton and text shouldn't bounce vertically after loading is done.

### Evidence

https://github.com/calcom/cal.com/assets/71217265/954f76e5-4169-4135-977b-ea3308e538d0

**Comment by Zahidd02** [comment]
I will try working on it. Will update soon! :)

**Comment by Zahidd02** [comment]
Hi there, I believe this is fixed. Can you check if this is what you wanted before I create a PR? ✌️✌️✌️

https://github.com/calcom/cal.com/assets/96968285/f3b71d49-0c1a-4826-afbd-456ee953493b

**Comment by AbhijitMatsagar** [comment]
Yes it is exact.

**Comment by MSVhora** [comment]
Hi @Zahidd02,

I am not sure, why you added the top margin in `VerticalTabItem.tsx` file. There will not be a noticeable difference in UI, as you added very less margin in else case. But it is not good practice to change components code which will then affect other areas of the platform.

Also as the platform supports ltr and rtl. So in `Skeleton` class, you should add proper margin with respect to ltr and rtl.

**Comment by Zahidd02** [comment]
Hi thanks for the suggestion I am kinda new to Next.js and stuff. 
Anyways, so you mean to say I should undo changes from VerticalTabItem.tsx?
And I am not sure what you mean by ltr and rtl, can you tell me more? Thanks

**Comment by MSVhora** [comment]
I think you are new to GitHub contribution as well, you should not use the main branch to add your commit,

> Anyways, so you mean to say I should undo changes from VerticalTabItem.tsx?
Yes, I think there is no need to add top margin for this issue.

> And I am not sure what you mean by ltr and rtl, can you tell me more? Thanks
LTR and RTL mean Left to Right and Right to Left. It's used to support localization, as some languages are ltr like English and some are RTL like Arabic. As such for LTR, you need left margin and for RTL you need right margin.

**Comment by suresh-3x** [comment]
I was going to work on this issue. Looks like this is closed from the comments. Can anyone confirm if this is resolved if so why the status still shows open?

**Comment by Zahidd02** [comment]
@MSVhora, You were right the component was also rendering settings tab, so if I did any changes to that code it reflected in "Settings tab" and "Installed Apps" page. Thanks for pointing that out!

**Comment by Zahidd02** [comment]
@MSVhora, Also regarding LTR and RTL, both languages have the same Skeleton configuration. So for RTL the skeleton appears on left side and magically jumps to right side as soon as rendering is finished.

**Comment by MSVhora** [comment]
> @MSVhora, Also regarding LTR and RTL, both languages have the same Skeleton configuration. So for RTL the skeleton appears on the left side and magically jumps to the right side as soon as rendering is finished. Maybe it needs a separate issue created?

I don't know the issue you are mentioning here, what I mean to say about LTR and RTL, is if you add the extra margin, then in the case of LTR, the left margin should be added and in the case of RTL, the right margin should be added.
