### ISSUE TITLE
[CAL-2318] embed: remove autofocus inside embed

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10590]
https://twitter.com/judecornish/status/1687411810570240000

<sub>[CAL-2318](https://linear.app/calcom/issue/CAL-2318/embed-remove-autofocus-inside-embed)</sub>

**Comment by Raghul18** [comment]
I would like to work on this

**Comment by JudeCornish** [comment]
FYI Problem persists on Arc browser for me? Not sure if updated yet.

https://github.com/calcom/cal.com/assets/50799584/92d135cf-96e1-409f-9537-60819924b3b4

**Comment by hariombalhara** [comment]
It is not yet deployed to production. Should be tagged soon

**Comment by mikelgo** [comment]
For me this issue still occours. You can reproduce when visiting: https://www.berger-engineering.io/

**Comment by KlotzJesse** [comment]
Happening again

**Comment by mikelgo** [comment]
@PeerRich 
We might want to reopen this issue? 

Even if I'm totally unfamiliar with the source code of cal.vom I would offer to investigate the issue and provide a fix for it.

**Comment by hariombalhara** [comment]
Have found the cause. A recent change elsewhere is causing this issue. Will fix soon.

**Comment by mikelgo** [comment]
> cause. A recent change elsewhere is causing this issue. Will fix soon.

Awesome! Many thanks ☺️

**Comment by osmangund** [comment]
This problem still persists, so ChatGPT wrote a solution for me in React. I hope it helps you too: 

```
import { useEffect, useState } from "react"
import Cal, { getCalApi } from "@calcom/embed-react"

const CalComponent = () => {
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          setIsVisible(true)
          observer.disconnect() // stop observing once the component is visible
        }
      },
      { threshold: 0.1 } // trigger when 10% of the section is visible
    )

    const section = document.getElementById("calForm")
    if (section) {
      observer.observe(section)
    }

    return () => {
      if (section) observer.disconnect()
    }
  }, [])

  useEffect(() => {
    if (isVisible) {
      ;(async () => {
        const cal = await getCalApi({ namespace: "namespacePlaceholder" })
        cal("ui", {
          styles: { branding: { brandColor: "#000000" } },
          hideEventTypeDetails: false,
          layout: "month_view",
        })
      })()
    }
  }, [isVisible])

  return isVisible ? (
    <Cal
      namespace="namespacePlaceholder"
      calLink="name/meeting-name"
      style={{ width: "100%", height: "100%", overflow: "scroll" }}
      config={{ layout: "month_view" }}
    />
  ) : null // Don't render anything if not visible
}

export default CalComponent
```
