### ISSUE TITLE
Public Page link uses stale username after changing to a new username

### ISSUE THREAD

**Issue by akxcix** [calcom/cal.com#10603]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

<img width="229" alt="Screenshot 2023-08-03 at 11 04 41 PM" src="https://github.com/calcom/cal.com/assets/29173346/b79a1543-d89a-42a1-945b-09997e3f183c">

i changed my username from `adarshkumar` to `akxcix`, but this link seems to be stale somewhere. does not update to the updated name even after hard-reloading

### Steps to Reproduce

- go to cal.com
- update your username
- refresh the page
- the public page link still uses the old username

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
- the public page link should be using my updated username
### Actual Results

- the public page link is using my old username

### Expected Results

- the public page link should be using my updated username

### Technical details
- Brave browser v1.56.14

### Evidence
<img width="229" alt="Screenshot 2023-08-03 at 11 04 41 PM" src="https://github.com/calcom/cal.com/assets/29173346/b79a1543-d89a-42a1-945b-09997e3f183c">

**Comment by VinoV1999** [comment]
hi @akxcix I tried twice but link is updating properly..

**Comment by tadinski** [comment]
Experiencing the same issue in local dev environment. 

Username is properly updated in the database however the link is still pointing to the old username. Upon inspection it seems that next-auth's session cache is stale and needs revalidation.

![SCR-20230805-l7m](https://github.com/calcom/cal.com/assets/6358371/b951846f-0b74-45d4-b97f-2b3545509c5e)

![SCR-20230805-l9e](https://github.com/calcom/cal.com/assets/6358371/5faf12ee-99b4-4e9f-b9b7-2588005c5b8b)

**Comment by BurhanRaja** [comment]
Actually, its working fine for me in the local and in production both. :sweat_smile:

**Comment by akxcix** [comment]
works fine after clearing cookies, maybe caching related as @tadinski suggested

**Comment by vaibhavsardar** [comment]
yes its working
