### ISSUE TITLE
Reschedule event webhook, payload not giving the new booking uid

### ISSUE THREAD

**Issue by Harsh4999** [calcom/cal.com#10631]
### Issue Summary

So in rescheduling event the webhook which we receive it consist of payload and payload consist of uid (new booking uid) and reschedule uid (old booking uid)

Now the thing is we dont always get uid (new booking uid) in payload in case of rescheduling event. Say for example I have a slot  of 9-9:20 AM on 9 Sep I also allow 20 seats for that slot. Now say for example 2 people with different emails booked the slot on 9 Sep 9-9:20 AM. Now lets say person A rescheduled the event to 10 Sep 9-9:20 AM and when they rescheduled the event I got a webhook payload like this

```json
{
    'description': '',
    'additionalNotes': '',
    'customInputs': {},
    'startTime': '2023-09-10T03:30:00Z',
    'endTime': '2023-09-10T03:50:00Z',
    'organizer': {
        'id': 3,
        'name': 'John Sharma',
        'email': 'HIDDEN',
        'username': 'johnsharma',
        'timeZone': 'Asia/Calcutta',
        'language': {
            'locale': 'en'
        },
        'timeFormat': 'h:mma'
    },
    'responses': {
        'name': {
            'label': 'your_name',
            'value': 'Harsh Trivedi'
        },
        'email': {
            'label': 'email_address',
            'value': 'HIDDEN'
        },
        'location': {
            'label': 'location'
        },
        'title': {
            'label': 'what_is_this_meeting_about'
        },
        'notes': {
            'label': 'additional_notes'
        },
        'guests': {
            'label': 'additional_guests',
            'value': []
        },
        'rescheduleReason': {
            'label': 'reason_for_reschedule'
        },
        'itvId': {
            'label': 'Interview Id',
            'value': 'ba57f85e-bfef-48fd-be19-2b809101e8f3'
        },
        'appId': {
            'label': 'Application Id',
            'value': '4040de69-818f-4241-a2ee-3749929ba4d1'
        }
    },
    'userFieldsResponses': {
        'itvId': {
            'label': 'Interview Id',
            'value': 'ba57f85e-bfef-48fd-be19-2b809101e8f3'
        },
        'appId': {
            'label': 'Application Id',
            'value': '4040de69-818f-4241-a2ee-3749929ba4d1'
        }
    },
    'attendees': [{HIDDEN}],
    'location': '',
    'destinationCalendar': None,
    'hideCalendarNotes': False,
    'requiresConfirmation': None,
    'eventTypeId': 9,
    'seatsShowAttendees': False,
    'seatsPerTimeSlot': 20,
    'uid': '5tyzhjiZKNZubctLchWHUA',
    'attendeeSeatId': '1b0a8dfa-6908-4580-883f-416563da2cb4',
    'eventTitle': 'AI Interview',
    'eventDescription': '',
    'price': 0,
    'currency': 'usd',
    'length': 20,
    'bookingId': 47,
    'rescheduleUid': 'hk78KGqQK6Z8YX8zZQYFZe',
    'metadata': {},
    'status': 'ACCEPTED'
}

```
Notice how I got ```uid ```  variable in payload that is our new booking uid which is on 10th Sept 9-9:20AM
Now lets say user B who still had event scheduled on 9th Sept rescheduled event to 10th Sept 9-9:20AM now what has happened is the 9th Sept booking has now 0 bookings and it will get cancelled and the new booking uid is not getting created as we already have a booking on 10th Sept 9-9:20 AM so payload is not sending booking uid but this is a problem like how can we know what booking uid this is related to. The payload which I receive after User B rescheduled their booking from Sept 9  to Sept 10

```json
{
    'description': '',
    'additionalNotes': '',
    'customInputs': {},
    'startTime': '2023-09-10T03:30:00Z',
    'endTime': '2023-09-10T03:50:00Z',
    'organizer': {
        'id': 3,
        'name': 'John Sharma',
        'email': 'HIDDEN',
        'username': 'johnsharma',
        'timeZone': 'Asia/Calcutta',
        'language': {
            'locale': 'en'
        },
        'timeFormat': 'h:mma'
    },
    'responses': {
        'name': {
            'label': 'your_name',
            'value': 'Harsh Trivedi'
        },
        'email': {
            'label': 'email_address',
            'value': 'HIDDEN'
        },
        'location': {
            'label': 'location'
        },
        'title': {
            'label': 'what_is_this_meeting_about'
        },
        'notes': {
            'label': 'additional_notes'
        },
        'guests': {
            'label': 'additional_guests',
            'value': []
        },
        'rescheduleReason': {
            'label': 'reason_for_reschedule'
        },
        'itvId': {
            'label': 'Interview Id',
            'value': 'a6b10c18-ffd8-48b4-ac87-e3090a8ea97c'
        },
        'appId': {
            'label': 'Application Id',
            'value': '7d80ca85-278a-4b7b-83de-43be47dce7dd'
        }
    },
    'userFieldsResponses': {
        'itvId': {
            'label': 'Interview Id',
            'value': 'a6b10c18-ffd8-48b4-ac87-e3090a8ea97c'
        },
        'appId': {
            'label': 'Application Id',
            'value': '7d80ca85-278a-4b7b-83de-43be47dce7dd'
        }
    },
    'attendees': [{HIDDEN}],
    'location': '',
    'destinationCalendar': None,
    'hideCalendarNotes': False,
    'requiresConfirmation': None,
    'eventTypeId': 9,
    'seatsShowAttendees': False,
    'seatsPerTimeSlot': 20,
    'eventTitle': 'AI Interview',
    'eventDescription': '',
    'price': 0,
    'currency': 'usd',
    'length': 20,
    'bookingId': 50,
    'rescheduleUid': 'hk78KGqQK6Z8YX8zZQYFZe',
    'rescheduleStartTime': '2023-09-09T03:30:00Z',
    'rescheduleEndTime': '2023-09-09T03:50:00Z',
    'metadata': {},
    'status': 'ACCEPTED'
}


```

Notice here ```uid``` is missing in the payload.

### Expected Results

- In ideal condition it should have sent uid in any case whether its for booking rescheduling or creation

### Current work around
- I use the start time provided by payload to get the booking id which is accepted from Bookings table

**Comment by ologbonowiwi** [comment]
I started digging into this and found some interesting stuff.
 
Ok, let's say that I book the same time to two different users; on my `/bookings/upcoming` page, I'll see this:
<img width="1596" alt="image" src="https://github.com/calcom/cal.com/assets/100464352/df8edff5-cde5-418f-a7af-530dcfd4b054">

But when I reschedule both to a new time, I get this result on `/bookings/upcoming`:
<img width="1598" alt="image" src="https://github.com/calcom/cal.com/assets/100464352/58036872-e106-4f1a-9630-8f906534f340">

IDK if this is a concern, but the second user to reschedule it'll see the name of all others that rescheduled to that event: 
<img width="563" alt="image" src="https://github.com/calcom/cal.com/assets/100464352/b7ec5af7-92e9-4890-9c1e-21b62c1f9c46">

Should both attendees be attached to the same booking or have different bookings @PeerRich

**Comment by ologbonowiwi** [comment]
Without changing the current implementation where we add more attendees to one booking, on #10654, I'm returning the new booking `uid` as requested by @Harsh4999.

Let me know if there's anything that I need to change on #10654. 😄

**Comment by Harsh4999** [comment]
> 

yeah that is one of my concerns too how to turn off this feature so that they dont see who else is having a booking at same time

**Comment by ologbonowiwi** [comment]
According to [this comment](https://github.com/calcom/cal.com/issues/7127#issuecomment-1432864026) on #7127, this is the expected behavior.

> As an organiser, 1 booking with 10 seats is still just 1 booking. I'm not hosing 10 separate events. It's all seats in one room, whether physical or online.
> 
> Seated event
> Fri, 24 Feb - 9am - 5pm
> 5/10 seats booked
