### ISSUE TITLE
[CAL-2320] Fix apps/web/playwright/workflow.e2e  tests

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#10640]
### Issue Summary

Test is currently flaky. Sometimes it fails randomly. It seems like sometimes the workflow gets created and the listing fail to revalidates. Disabled temporarily in 46de1a85180456cdd711f628e049873e320f6032

[https://github.com/calcom/cal.com/blob/46de1a85180456cdd711f628e049873e320f6032/apps/web/playwright/workflow.e2e.ts#L14-L69](https://github.com/calcom/cal.com/blob/46de1a85180456cdd711f628e049873e320f6032/apps/web/playwright/workflow.e2e.ts#L14-L69)

### Steps to Reproduce

1. yarn e2e  apps/web/playwright/workflow.e2e.ts

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5efb6483-a7a2-4cb0-aa26-dc6d724b2c56/e026c318-2fe5-4edd-b9dc-6b7f27947c46?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ZWZiNjQ4My1hN2EyLTRjYjAtYWEyNi1kYzZkNzI0YjJjNTYvZTAyNmMzMTgtMmZlNS00ZWRkLWI5ZGMtNmI3ZjI3OTQ3YzQ2IiwiaWF0IjoxNjkxNDU1ODkyLCJleHAiOjE2OTE1NDIyOTJ9.jJOnTNUg5l25peIzHj3d7q7pXljdu1qCio9rKp9gKmA)

### Expected Results

* No errors/flakyness

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2320](https://linear.app/calcom/issue/CAL-2320/fix-appswebplaywrightworkflowe2e-tests)</sub>

**Comment by keithwillcode** [comment]
@montocoder Have at it!
