### ISSUE TITLE
[CAL-2516] Form state changes doesn't lead to change in UI for some fields.

### ISSUE THREAD

**Issue by MehulZR** [calcom/cal.com#10647]
### Issue Summary

When making some change in the eventType form. The form changes are not reflected in the UI for some fields. They are registerd in the form state but for the UI rendering logic they are dependant on the data fetched from backend. 

This can lead to bad UX. The customer can not be sure what is the current form state due to UI mismatch.
The customer may change a field (eg. enabling recurring event), switches the tabs and decides to disables the recurring event. When he switches back to the recurring event tab. He might assume that his changes did not persisted and the recurring event is disabled ( which infact is enabled in the form state ) and leads to unexpected behaivour for the customer.

### Steps to Reproduce

1. Edit a event type(meeting).
2. Make some changes in a tab and switch between tabs back and forth. ( for eg. lets change the recurring event setting)
3. The change will be registed in the form state but will not be reflected in the UI.

### Actual Results

https://github.com/calcom/cal.com/assets/86384652/6d2591bc-b2e0-4790-916a-512c63dd7431

### Expected Results

https://github.com/calcom/cal.com/assets/86384652/f0629779-1ae5-4b69-9b5c-879dfae832cb

### Technical details

- Browser version: Chrome 115
- Node.js version: 18.16.1

<sub>[CAL-2516](https://linear.app/calcom/issue/CAL-2516/form-state-changes-doesnt-lead-to-change-in-ui-for-some-fields)</sub>

**Comment by moonpatel** [comment]
Hey @MehulZR , I think you forgot to press the save button in the first video and thus the backend does not receive any request to update the event type. I checked it after pressing the save button and the changes were reflected correctly in the UI

**Comment by MehulZR** [comment]
All those form tabs are implemented as a single form. It would be weird to save multiple times when you are switching between tabs and configuring settings.

**Comment by moonpatel** [comment]
> All those form tabs are implemented as a single form. It would be weird to save multiple times when you are switching between tabs and configuring settings.

Yeah you are right that definitely leds to bad user experience.

**Comment by Siddharth-2382** [comment]
@PeerRich If this is yet to be resolved I can do the quick fix and raise a new PR. Should I go for it?
