### ISSUE TITLE
/Payments API returns error

### ISSUE THREAD

**Issue by kcrimi** [calcom/cal.com#10665]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to retrieve payment information via the `/payments` endpoint. Instead a 400 error is returned

### Steps to Reproduce

1. Use the apiKey from an account which has confirmed and completed paid bookings
2. Call `{{API_URL}}/payments

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- A 400 response is returned with the [body error message](https://gist.github.com/kcrimi/1f8a071ff1a9e78974f17bd818491f26)

### Expected Results

- List of payments is returned in JSON

### Technical details

- Using the cloud-hosted version of Cal.com
- Only tested with my account that already has successful payments
- 
### Evidence

- https://gist.github.com/kcrimi/1f8a071ff1a9e78974f17bd818491f26

**Comment by abhinaisai2002** [comment]
Can i work on this issue

**Comment by asadath1395** [comment]
Seems like this is working fine now in latest code
<img width="527" alt="image" src="https://github.com/user-attachments/assets/1093cebd-9d74-433c-b74b-6f266fed74b4">

cc @keithwillcode @PeerRich
