### ISSUE TITLE
Provide information to link bookings to Stripe payments

### ISSUE THREAD

**Issue by kcrimi** [calcom/cal.com#10668]
### Is your proposal related to a problem?

With paid bookings, I am unable to link specific charges in my Stripe account with the specific booking for which it was charged.

The only identifiable information available in Stripe seems to be `"application": "ca_KHCNqOhNnle2Od6KZ6iKmha6g9xlFdC1",` which seems to be generic to the Cal.com / Stripe app integration.

I'm looking to have multiple Cal accounts share one Stripe which also receives non-Cal.com payments so it is important for me to be able to tie payments to Cal, Cal user account, and booking for accounting purposes.

### Describe the solution you'd like

Ideally there would be a 2 part solution:

#### Cal.com -> Stripe link
- Stripe transaction ID would be returned with the webhook for a completed paid booking
- Stripe transaction ID would be returned with payment API data (_currently unable to test due to https://github.com/calcom/cal.com/issues/10665)_

#### Stripe -> Cal.com link
Add metadata to the Stripe payment to identify the following (in order of importance)
- The id of the booking
- The id of the organizer
- The id of the booking type

### Describe alternatives you've considered

The only other option I see is storing a redundant data set of all the events and using time stamps and inference to try to determine which payment corresponds to which booking which is very unreliable. 

I'm open to other methods to achieve the same reliable result as the above proposal though.

### Additional context

n/a

### Requirement/Document

n/a

**Comment by MyPsyOnline** [comment]
maybe a solution would be to have a dynamic redirection url ?
For example,  https://redirect_url?uid={event_uid}

With that, the payment_url from Stripe would be able to link the event with no doubt

**Comment by kcrimi** [comment]
@MyPsyOnline I don't think I fully understand the redirect_url idea. Would this url show up in the Stripe dashboard under the transaction information? Or within the booking webhooks/api? Or both?

**Comment by MyPsyOnline** [comment]
the personalize redirect url would make possible the identification of the payment link : https://stripe.com/docs/payments/checkout/custom-fields

in stripe, we would have the custom field with the id of the event, and in cal.com, we already have the id.
Linking would be very easy.

**Comment by kcrimi** [comment]
So are you suggesting that instead of using Cal.com's payment flow, I would need to set up my own payment links and then redirect to those?

To be clear, my intention is to use Cal.com's booking and payment flow but be able to access the data of stripe transaction or payment id when receiving Cal webhooks or calling Cal APIs.

**Comment by kcrimi** [comment]
Then the price needs to be managed in 2 places: 1) Cal via the Stripe integration and 2) The payment link on the Stripe account. 
There is currently a checkout experience in Cal via the Stripe integration. There's no way to return the resulting transaction ID from that successful checkout experience?

**Comment by MyPsyOnline** [comment]
Prices need to be equal between Cal events and payment link in Stripe. (not so difficult)
That's right, but...

But it makes some enhances Vs Stripe in Cal integration :
- if i want to have a payment link where my customer can choose the price,
- If i want to have a Payment link from a single Product in Stripe,
- if i want to have different fees between events,
- ...

If "id" could be inserted in redirection link, all that would be possible.

**Comment by alannnc** [comment]
I think we will handle this issue on it's respetive issue.
- #10678 Add more data to stripe payment metadata
- #10679 Add more data to booking_paid webhook
Please continue the discussion on it's respetive issue, if you need other data in each webhook/stripe metadata let us know.

Close issue if those scenarios cover this one please.

**Comment by MyPsyOnline** [comment]
Thanks alannc

I will open another issue for the new topic: "enhance the redirect url"

**Comment by kcrimi** [comment]
@alannnc I've opened a new PR for adding some of the remaining information to the stripe metadata https://github.com/calcom/cal.com/pull/11221
CC: @shirazdole
