### ISSUE TITLE
[CAL-2517] Recurring Event - Error while booking a meeting.

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#10673]
### Issue Summary
I get the Couldn't Book Meeting Error while trying to book a recurring meeting. 

### Steps to Reproduce

1. Book a recurring event type

![Screenshot](https://github.com/calcom/cal.com/assets/22683064/05f30421-bdaf-4f29-b617-c65ae13fd21a)

[Chrome logs](https://paste.c-net.org/FelicityComrades)

<sub>[CAL-2517](https://linear.app/calcom/issue/CAL-2517/error-while-booking-a-meeting)</sub>

**Comment by shivamklr** [comment]
Also, one more finding, even though this is code 500, it went through and is now added in my list of bookings.
![Screenshot from 2023-08-10 09-17-25](https://github.com/calcom/cal.com/assets/22683064/937d5117-1639-46f1-bdee-1977d3505d8a)

**Comment by MehulZR** [comment]
@shivamklr Can you share the *response* sent by the *recurring-event* call from the network tab.
Also are you connected with the google calendar?

**Comment by mpette200** [comment]
I am also facing this issue. I followed these steps:

1. Link a google calendar
2. Try to book a recurring meeting
3. Message says "Could not book".
4. Even though message says "Could not book", all the meetings apart from the first of the series, become booked anyway and show up in the list of bookings.
5. At this point it seems to be impossible to cancel the meeting to free up the time. Effectively that time slot becomes unavailable forever.

**Comment by MehulZR** [comment]
> I am also facing this issue. I followed these steps:
> 
> 1. Link a google calendar
> 2. Try to book a recurring meeting
> 3. Message says "Could not book".
> 4. Even though message says "Could not book", all the meetings apart from the first of the series, become booked anyway and show up in the list of bookings.
> 5. At this point it seems to be impossible to cancel the meeting to free up the time. Effectively that time slot becomes unavailable forever.

The issue is exactly the same aside from the 5th point. I would look into it further.
@mpette200  Can you share a screenshot or relevant information of what exactly happens when you try to cancel the meetings?

**Comment by mpette200** [comment]
> 1. Link a google calendar
> 2. Try to book a recurring meeting
> 3. Message says "Could not book".
> 4. Even though message says "Could not book", all the meetings apart from the first of the series, become booked anyway and show up in the list of bookings.
> 5. At this point it seems to be impossible to cancel the meeting to free up the time. Effectively that time slot becomes unavailable forever.

Apologies @MehulZR , I seem to be mistaken on the 5th point. I think the Cal system was just very slow that day and was taking a lot of time to remove the meeting.

**Comment by shivamklr** [comment]
@mpette200 @MehulZR I have added chrome logs in the issue. You can save to an HAR file and import it in the network tab in chrome devtools to investigate.

**Comment by MehulZR** [comment]
The conflict arrises here due to the over-fetching ( which can be intentional ) of the calendar slots.

>  _handleNewBooking.ts_

![image](https://github.com/calcom/cal.com/assets/86384652/d8460cd6-18e5-4e9e-a8a8-f9a133ad04a8)


If the currentRecurringIndex != 0, it checks for the conflict for the particular recurring event and when the currentRecurringIndex == 0, it checks for all the recurring events. Here the over-fetch leads to a conflict as all the others recurringEvents are already processed ( and will be shown in the _bufferedBusyTimes_ ) because the recurring events req are processed in reverse order.
> _recurring-event.ts

![image](https://github.com/calcom/cal.com/assets/86384652/c0434fa2-c99e-40c8-97a6-015a02e63845)

It may be that I have misunderstood something and would like some thoughts regarding the _currentRecurringIndex == 0_ condition.

**Comment by hariombalhara** [comment]
@keithwillcode I am not sure what we finalized for this recurring events issue but I saw some discussion on threads. Have we decided on a strategy

**Comment by hariombalhara** [comment]
Private thread here to keep it easily accessible: https://threads.com/34541278221?s=xeUvkwCbQTo3iY7Vymjn2H

Will share the results from there later.
