### ISSUE TITLE
[CAL-2327] Add more data to stripe payment metadata

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#10678]
Adding { identifier: "[cal.com](http://cal.com)", userId, eventName } as requested by user.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2327](https://linear.app/calcom/issue/CAL-2327/add-more-data-to-stripe-payment-metadata)</sub>

**Comment by jimjoice2804** [comment]
@alannnc please explain in detail what you want, 
1-  what is the current result/outcome. 
2- what is the result you are looking for.

**Comment by MeenuyD** [comment]
Hello @alannnc can you explain a bit more

**Comment by kcrimi** [comment]
I may be the customer in question. I opened a separate ticket with more information 
https://github.com/calcom/cal.com/issues/10668
