### ISSUE TITLE
[CAL-2328] Add more data to booking_paid webhook

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#10679]
We can add { stripePaymentId, stripeCustomerId, providerId: "cal.com", userId, eventName, eventId }

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2328](https://linear.app/calcom/issue/CAL-2328/add-more-data-to-booking-paid-webhook)</sub>

**Comment by NextThread** [comment]
can i work on this?
