### ISSUE TITLE
[CAL-2329] default currency not showing on new-booker or payment page

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#10682]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c6301006-c64e-43c7-929c-b543c1a88460/092c749b-7475-4492-8688-6d14386b22dc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jNjMwMTAwNi1jNjRlLTQzYzctOTI5Yy1iNTQzYzFhODg0NjAvMDkyYzc0OWItNzQ3NS00NDkyLTg2ODgtNmQxNDM4NmIyMmRjIiwiaWF0IjoxNjkxNzEzNTMzLCJleHAiOjE2OTE3OTk5MzN9.TkNhXgLPQVAqvwqRnrytUZRt2Ltx2O7z_FG4c7PdLuY)

Add default currency form payment.currency table.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2329](https://linear.app/calcom/issue/CAL-2329/default-currency-not-showing-on-new-booker-or-payment-page)</sub>

**Comment by MeenuyD** [comment]
Hello @alannnc can you explain bit more

**Comment by alannnc** [comment]
Sure, we have a field "currency" inside payment table that should have the value to display here: "usd" | "eur" | "mxn".
Instead of just $10.00 it should say $10.00 USD.
@MeenuyD

**Comment by xonx4l** [comment]
A solution from my side -:Update Payment.tsx #10688

**Comment by xonx4l** [comment]
and aef110693fdac12dc333e90d9dc1e850a6cd0553
