### ISSUE TITLE
[CAL-2330] slack app

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10683]
- send notifications to slack channel

<sub>[CAL-2330](https://linear.app/calcom/issue/CAL-2330/slack-app)</sub>

**Comment by PeerRich** [comment]
what else should this app be able to do?

**Comment by PeerRich** [comment]
how to build an app

https://cal.com/docs/how-to-guides/how-to-build-an-app#steps-in-creating-an-app

**Comment by Wholesomebruh** [comment]
Hi @PeerRich , please state the issue at once .

**Comment by MeenuyD** [comment]
Hello @PeerRich can you explain bit more

**Comment by Shubhamtribhuvan8** [comment]
hey @PeerRich  can you explain issue.

**Comment by Shubhamtribhuvan8** [comment]
hey @PeerRich i am working on this issue please assign to me!

**Comment by sumit-badsara** [comment]
@rkreddy99 Are you still working on this?

**Comment by Wholesomebruh** [comment]
@rkreddy99 resolve the changes requested , convert it to PR if it's still in draft and ask reviewer if there are changes to be made.

**Comment by rkreddy99** [comment]
@Wholesomebruh thanks for the info on how to get a pr merged 😅, i had already made the requested changes, and added some of my own comments

**Comment by sambhavgupta0705** [comment]
@PeerRich can I take up this issue?

**Comment by keithwillcode** [comment]
Removing from 3.8 because of the extra work needed that Joe pointed out regarding Slack Bolt.

**Comment by joeauyeung** [comment]
As pointed out in this issue: https://github.com/slackapi/bolt-js/issues/1494#issuecomment-1159859792

We will have to use https://github.com/seratch/slack-bolt-extensions/tree/main/packages/bolt-http-runner and https://github.com/seratch/slack-bolt-extensions/tree/main/packages/bolt-prisma

**Comment by ameeetgaikwad** [comment]
Is someone working on this?

**Comment by keithwillcode** [comment]
@ameeetgaikwad not at the moment

**Comment by Bhavyajain21** [comment]
Can i be assigned?
