### ISSUE TITLE
[CAL-2334] Orgs: url in event type settings for individual doesn't reflect the org context

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10690]
Currently

![CleanShot 2023-08-10 at 09.35.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/24339063-e304-46d8-a425-dca9b8c42e1f/8f8282e5-8596-41a3-b9ea-1ef58b2ff8a1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yNDMzOTA2My1lMzA0LTQ2ZDgtYTQyNS1kY2E5YjhjNDJlMWYvOGY4MjgyZTUtODU5Ni00MWEzLWI5ZWEtMWVmNThiMmZmOGExIiwiaWF0IjoxNjkxNjU2NjY2LCJleHAiOjE2OTE3NDMwNjZ9.yutwNkz_dEKHFFksWW0IcjWuT8hSlLkuGzF6tYQ-kbo)

Should be

![CleanShot 2023-08-10 at 09.36.51@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5277cd14-a090-47d3-aae1-4b52bbc9805e/d86311bd-8ed8-4fec-b215-157c42c00608?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81Mjc3Y2QxNC1hMDkwLTQ3ZDMtYWFlMS00YjUyYmJjOTgwNWUvZDg2MzExYmQtOGVkOC00ZmVjLWIyMTUtMTU3YzQyYzAwNjA4IiwiaWF0IjoxNjkxNjU2NjY2LCJleHAiOjE2OTE3NDMwNjZ9.SSYWQAE1vGHwSFVgKrTnmeIhnrzVcX7wmqvSVdw4iQE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2334](https://linear.app/calcom/issue/CAL-2334/orgs-url-in-event-type-settings-for-individual-doesnt-reflect-the-org)</sub>

**Comment by yashpatel21102002** [comment]
can you please elaborate more

**Comment by BhuvaneshPatil** [comment]
@Jaibles Is there any documentation about setting up the organisation on localhost.

**Comment by esau-morais** [comment]
@BhuvaneshPatil check the .env.example file
