### ISSUE TITLE
[CAL-2335] Someone reported there are scrollbars on safari in Embed

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10693]
https://twitter.com/navilan/status/1689569204180070400

Doesn't replicate for me. Maybe safari version specific.

<sub>[CAL-2335](https://linear.app/calcom/issue/CAL-2335/someone-reported-there-are-scrollbars-on-safari-in-embed)</sub>

**Comment by hariombalhara** [comment]
@shivamklr Could you try replicating this please ?

**Comment by hariombalhara** [comment]
Note to Self: try various safari versions on browserstack

**Comment by zomars** [comment]
This is a macos setting. It only appears when using a mouse with scrollwheel.

You can force it to appear by setting system settings to always show scrollbars

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/14be21a0-eb2f-419e-942f-3da8b5bd58cd/20f21626-da02-468d-8159-910bac717e4e)
