### ISSUE TITLE
2 1/2 Hours / 150min duration time for scheduling not possibe

### ISSUE THREAD

**Issue by Obiast** [calcom/cal.com#10711]
I'm trying to set up an scheduling option for 150 min, but I seem not to be able to do so. Only 120 and 180 min are possible or at least clickable when I let my clients choose from different duration times.

![2023-08-11 10 00 35 app cal com 5bbf75861d45](https://github.com/calcom/cal.com/assets/141999812/357b3e4d-16a7-4ef2-9cf2-ac95d55e7aae)

Any idea / workaround / fix how to offer 2 1/2 hours appointments?

Thanks in advance and anyways I'm really happy for this amazing tool!

**Comment by Lakshvyas007** [comment]
I want to contribute.
