### ISSUE TITLE
[CAL-2337] Allow background color of booker to be changed in embed

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10710]
Changing the background color is quite easy but we don't really want to allow that because that would mean that the text might not be clearly visible on that background.

Is it possible for you to share a screenshot of how you would want it to look. I am interested in seeing the background color and how the booking page text looks on it.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/issues/8841#issuecomment-1674274472_
            

<sub>[CAL-2337](https://linear.app/calcom/issue/CAL-2337/allow-background-color-of-booker-to-be-changed-in-embed)</sub>

**Comment by zacsanter** [comment]
I actually was able to change it. Using bg-muted (please don't disable this!!)

https://clientflow.webflow.io/acquisition/book-a-call

**Comment by zacsanter** [comment]
Another slight variation - https://clientflow.ai/book-a-call
