### ISSUE TITLE
[CAL-2338] Orgs: As an admin of an org, I should be able to add people to teams I'm not in and join them myself

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#10716]
As an org admin, I need to be be able to:

* Add myself to a team
* Add other members to a team, even without joining it myself

[https://github.com/calcom/cal.com/assets/4536123/7d4c8e68-a202-4c5c-86d3-72afebfd98e0](https://github.com/calcom/cal.com/assets/4536123/7d4c8e68-a202-4c5c-86d3-72afebfd98e0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2338](https://linear.app/calcom/issue/CAL-2338/orgs-as-an-admin-of-an-org-i-should-be-able-to-add-people-to-teams-im)</sub>

**Comment by anikdhabal** [comment]
> As an org admin, I need to be be able to:
> 
> * Add myself to a team
> * Add other members to a team, even without joining it myself
> 
>  CleanShot.2023-08-11.at.11.57.55.mp4 
> From [SyncLinear.com](https://synclinear.com) | [CAL-2338](https://linear.app/calcom/issue/CAL-2338/orgs-as-an-admin-of-an-org-i-should-be-able-to-add-people-to-teams-im)

@Jaibles can you clear this point -"Add myself to a team". Should there be a button called 'Join,' which is only visible to orgAdmins? After clicking the button, orgAdmins would be added directly to the team as admin. Or the button could open a dialog for selecting the role before joining.
