### ISSUE TITLE
[CAL-2344] Next/previous buttons on week view move 8 instead of 7 days

### ISSUE THREAD

**Issue by thgh** [calcom/cal.com#10739]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Next/previous buttons on week view move 8 instead of 7 days

### Steps to Reproduce

Before click:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/137cbc87-bec4-4549-80a3-e321d80d1922/5f9f585a-22a9-4b25-9350-2cc9c72546fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xMzdjYmM4Ny1iZWM0LTQ1NDktODBhMy1lMzIxZDgwZDE5MjIvNWY5ZjU4NWEtMjJhOS00YjI1LTkzNTAtMmNjOWM3MjU0NmZlIiwiaWF0IjoxNjkyMDE4ODEzLCJleHAiOjE2OTIxMDUyMTN9.WjVpKmV57s7ur9m5YQQBtYqdfUk97M7f5Kb3jm9Hgqc)

After click:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f2b053c8-a70c-4e39-9e9c-2bf68583bdb4/f630606a-5547-4b2a-a143-65667b496c9d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMmIwNTNjOC1hNzBjLTRlMzktOWU5Yy0yYmY2ODU4M2JkYjQvZjYzMDYwNmEtNTU0Ny00YjJhLWExNDMtNjU2NjdiNDk2YzlkIiwiaWF0IjoxNjkyMDE4ODEzLCJleHAiOjE2OTIxMDUyMTN9.2LMqLP2eXFxz_imW9c0HxTStA7MM9pE4vft_nz0dyeU)

### Actual Results

Date range is Aug 22-28

### Expected Results

Date range is Aug 21-27

### Technical details

* Browser version, Chrome

### Evidence

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2344](https://linear.app/calcom/issue/CAL-2344/nextprevious-buttons-on-week-view-move-8-instead-of-7-days)</sub>

**Comment by premkamal23** [comment]
@thgh Please provide the steps to reproduce this.

**Comment by Udit-takkar** [comment]
@thgh what timezone did you select in your booker ?

**Comment by moonpatel** [comment]
Hey @Udit-takkar @thgh I have created a PR for the fix of this issue

**Comment by thgh** [comment]
Repro: open the week view, click the chevron right icon
Timezone: I'm in the Europe/Brussels timezone


https://github.com/calcom/cal.com/assets/1109982/b3922d7c-d2da-4942-9cfa-ad624b5f974d

**Comment by moonpatel** [comment]
Hey @keithwillcode I have already linked a PR for this issue
