### ISSUE TITLE
Workflow with email notification is broken. It always send email just after booking, not before event

### ISSUE THREAD

**Issue by sterid** [calcom/cal.com#10749]
### Issue Summary

I use workflow for notification clients about future bookings. I configure 2 workflows: 24 and 1 hour before event starts. But workflow always send all email to clients just after booking at the same time. Therefore my clients reveice 3 email at once
• Default cal.com email
• Workflow notification that should be sent 24 hours before events starts
• Workflow notification that should be sent 1 hour before events starts

### Steps to Reproduce

1. Create new workflow:
when = before event starts
How long before event starts= 24 hours
Action = send email to attendees 
<img width="1370" alt="Screen_2023-08-14_edhD4scC" src="https://github.com/calcom/cal.com/assets/22502995/ad7665bf-3228-4fd3-99a3-2f0a97c6f227">

3. Apply workflow to any event type
4. Go to event type and choose any date in the future. Life in 36 hours in advance
5. Receive 2 email notification. One dafault from cal.com, second is from workflow (but it should be sent only tomorrow for example)

### Actual Results

- All email workflow for event type triggred at the same time. Not at starts before event.

### Expected Results

- I get first default email just after event has been booked
- Send email will be send 24 hours before event start

### Technical details

- Google Chrome 115, Safari 16.6

### Evidence

-

**Comment by pateldivyesh1323** [comment]
I can see only one default mail after I reproduced this issue.

**Comment by CarinaWolli** [comment]
this got fixed with https://github.com/calcom/cal.com/pull/10890
