### ISSUE TITLE
[CAL-2348] Return Schedule information in event-types GET request

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#10748]
Currently, we only return timeZone property in the GET event-types request which is essentially for backward compatibility, and essentiall null most of the time.

We get timeZone and availability associated with an event-type only via Schedule object which isn't being returned as part of the GET request. This means, there is no way for us to get this information via API alone. 

We need to return Schedule  object (primarily scheduleId, name and timeZone) to help API users get this information and then incorporate it in their flow.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2348](https://linear.app/calcom/issue/CAL-2348/return-schedule-information-in-event-types-get-request)</sub>

**Comment by LemmyMwaura** [comment]
@alishaz-polymath, I think has already been implemented. The entire eventType is returned along with the scheduleId, unless I'm missing something

**Comment by alishaz-polymath** [comment]
You're correct. It was fixed in PR #10816
