### ISSUE TITLE
[CAL-2647] Configure 'Check For Conflicts' at the event type level

### ISSUE THREAD

**Issue by mreilly-lula** [calcom/cal.com#10754]
### Is your proposal related to a problem?

There is a disjoint experience when I can choose a calendar an event type should place events on, but I can only choose which calendar to check for conflicts at the account level. Ideally, I would be able to select a calendar for a specific event type, then cal.com would both place events on that calendar AND pull availability from just that calendar.

### Describe the solution you'd like

The below input exists when configuring an event type:
<img width="941" alt="Screenshot 2023-08-14 at 1 06 32 PM" src="https://github.com/calcom/cal.com/assets/57537896/8bc5b62b-67e3-42be-b990-97d055854c07">
And the below exists when configuring a calendar within account settings:
<img width="914" alt="Screenshot 2023-08-14 at 1 06 59 PM" src="https://github.com/calcom/cal.com/assets/57537896/16373e95-7487-4e22-8736-626329ed6f18">

Including something like the conflict checker component on the event type configuration screen would accomplish the desired outcome. It would let the user select where events should be placed, and what calendar should represent the availability for the event type.

### Describe alternatives you've considered

The main alternative is creating new cal.com accounts for each calendar. This leads to a rapidly increasing cost.

### Additional context

n/a
### Requirement/Document

n/a

<sub>[CAL-2647](https://linear.app/calcom/issue/CAL-2647/configure-check-for-conflicts-at-the-event-type-level)</sub>

**Comment by PeerRich** [comment]
i agree this would be nice to be overwriteable on event-types. whats your take @Jaibles ?

**Comment by brianclements** [comment]
Good luck. They really don't want to implement this feature. I asked for something similar in December last year and they just [closed it](https://github.com/calcom/cal.com/issues/5887).

**Comment by mreilly-lula** [comment]
Think positive @brianclements! It would open up a massive amount of use cases for cal.com, and would be a differentiating feature I haven't seen on any similar platforms. It's a headache Ive run into on every system I've tested, and cal.com is the only one even listening to my requests.

**Comment by iamr-kumar** [comment]
Hey @PeerRich, I would love to work on this.

**Comment by mhlauf1** [comment]
This would be much appreciated!!

**Comment by FourthBestDevAtMyWork** [comment]
Game changer! +1 on this. Will be checking back on this hoping for solutions

**Comment by Jaibles** [comment]
Hey everyone, we had marked this as low priority as while we understood the value, we didn't think there was a wide need and we were trying to be careful not to overwhelm our app with settings. Of course we may have misjudged it as it seems like quite a few people want it! Will consider it for the near term roadmap!

**Comment by AhmedKamal** [comment]
I would love to have this feature, it will improve how cal.com can be used by hardcore users and differentiate it from the Google Calendar Appointment system that shall be adopted soon by a lot of people.

**Comment by mreilly-lula** [comment]
Hi @ciaranha ! has this been added to any of the upcoming milestones? Thank you!

**Comment by mreilly-lula** [comment]
Hello! is there any update on when this will be added to a milestone? thank you

**Comment by jimafisk** [comment]
I was confused by this too, I thought setting the calendar in advanced settings under Event Types would limit the conflict checking to that calendar, but it appears to using the calendar selected under the account settings. It would be awesome to be able to check conflicts against multiple calendars :heart:

**Comment by mreilly-lula** [comment]
@ciaranha THANK YOU!! This is such a game changer for us

**Comment by jeremyosih** [comment]
This would really be a life saving feature for me, currently ! Would this be implemented in v3.7 ? That would be awesome ❤️.

**Comment by iamr-kumar** [comment]
Hi @mreilly-lula, I have started to take a look into this.

Just to understand the requirement clearly, you should be able to select a particular calendar type for an event type in its settings and then choose the calendars under only that type to check for conflicts, irrespective of what other calendars you have toggled on the setting for in account setting. Is that right?

For example, if you have the account setting turned on for Google Calendar, but for a particular event type you choose Apple Calendar and turn on the toggle for two calendars under it, the bookings for that event type should only check for conflicts with other selected Apple Calendars, and not the Google Calendar.

Please correct me if I am wrong or missed something.

**Comment by mreilly-lula** [comment]
@iamr-kumar the use case that I am looking for is:

I've set up a cal.com account and connected it to one google calendar account (ex resources@company.com). That google calendar account has many sub calendars, ex. Resource 1 and Resource 2.
I'd like to be able to have an event type for Resource 1 that pulls availability from the Resource 1 sub calendar, and places events on the Resource 1 sub calendar.

This would allow me to have one google account and one cal.com account that can manage events and scheduling separately between the sub calendars.

So for my use case, it's less about being able to switch between apple calendar and google calendar, and more about being able to configure conflict checking at the event type level so that my different event types can pull availability from different calendars.

Currently I'm only able to configure which calendars to pull availability from at the account level.


I hope this answers your question, let me know if I'm being unclear / confusing. Thank you!

**Comment by iamr-kumar** [comment]
Thanks @mreilly-lula , that clears it up!

**Comment by mreilly-lula** [comment]
I realize that fixing this issue would have an impact on revenue for cal.com, as the workaround is creating more accounts on the team plan. Just want to add here that I would gladly pay more per month / year for this feature.

**Comment by henryholtgeerts** [comment]
Chiming in that this is a feature I'd love to see in cal.com, as it is the only thing keeping me from switching my organization over from Google Calendar's Appointment Scheduler (which handles this exact use case -- a default calendar to check for conflicts that can be overwritten on per booking type).

**Comment by lpietrobon** [comment]
Hi @ciaranha, I see I am not the first at raising a request for this feature, but it looks like it has been delayed a bit. Could you give an update on where this stands?

**Comment by santivdt** [comment]
Need this desperately. Love cal.com so much but this is a bit of a dealbreaker.

**Comment by ahnafa** [comment]
This feature absolutely needs to be implemented. On the surface the use cases may seem insignificant but if the other comments are any indication, a lot of users would immediately benefit from this. 

I would also like to add another tangential feature request: the ability to quickly override conflicts within the **_Bookings_** view. Sometimes, new bookings can be deemed more important that what's already existing on my calendar and I would for there to be a way to replace events and thus remove the conflict. 

![image](https://github.com/user-attachments/assets/983a3348-d212-4c03-90c4-bacf0b0e4a51)

**Comment by ypetzold** [comment]
Hi @ciaranha, is 4.7 a real thing now? For us this missing feature is a showstopper, we want to use one account to book meetings with lecturers and need the conflict check at event level. Thank you
