### ISSUE TITLE
[CAL-2354] Sorting function for workflows and routing forms

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#10753]
Can you also implement a sorting function for the workflows and routing forms like for the events? I have quite a few workflows and that would really improve the clarity.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/906d2c04-3ea6-4675-b512-49d79275485f/84ebcb62-491a-434e-aa0e-0171bccce96b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MDZkMmMwNC0zZWE2LTQ2NzUtYjUxMi00OWQ3OTI3NTQ4NWYvODRlYmNiNjItNDkxYS00MzRlLWFhMGUtMDE3MWJjY2NlOTZiIiwiaWF0IjoxNjkyMTAyNzc4LCJleHAiOjE2OTIxODkxNzh9.QdWa7FyeWpxmhEeE0zu_iBMF33Zkay-i_F3Xb-iVCuc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2354](https://linear.app/calcom/issue/CAL-2354/sorting-function-for-workflows-and-routing-forms)</sub>

**Comment by atul-bisht-ABCodes** [comment]
yes it can definitely be done.  Can u please share more info about on what basis u have to sort it?
@RainerZufall9393
