### ISSUE TITLE
[CAL-2351] app store: rank apps by most installed in categories

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10751]
this:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e1c426fa-4315-445f-b121-d43d9bbee6fe/fbd44b8b-ba0c-4793-a4d7-c414aa3ddf26?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lMWM0MjZmYS00MzE1LTQ0NWYtYjEyMS1kNDNkOWJiZWU2ZmUvZmJkNDRiOGItYmEwYy00NzkzLWE0ZDctYzQxNGFhM2RkZjI2IiwiaWF0IjoxNjkyMDM0MjAwLCJleHAiOjE2OTIxMjA2MDB9.mpZWrA37cvV7pjHKaj6BfowJjVzAvR8zEtJbOK4Sh6Q)

should be ranked by most installed

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2351](https://linear.app/calcom/issue/CAL-2351/app-store-rank-apps-by-most-installed-in-categories)</sub>

**Comment by ssinghal13** [comment]
@PeerRich, in case the installCount values are equal, would you like me to additionally sort the apps based on their names in lexicographical order?
