### ISSUE TITLE
Can't login on dev environment when ORGANIZATIONS_ENABLED=1

### ISSUE THREAD

**Issue by vineetpradhan-dev** [calcom/cal.com#10752]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Can't login on dev environment when ORGANIZATIONS_ENABLED is set to be 1 in .env. Even on entering wrong credentials its not showing error message for 'incorrect email or password'. 

Only getting this error in terminal:
![Screenshot 2023-08-14 230259](https://github.com/calcom/cal.com/assets/138296762/3ca0933a-d153-450a-b8aa-4f8050c51a18)

### Steps to Reproduce

1. In .env set ORGANIZATIONS_ENABLED=1
2. Restart the server
3. Try to login with any account

### Technical details

- Node.js version: 18.17.1
- Using docker to run the server

**Comment by emrysal** [comment]
Are you trying to access organisations with `app.cal.local:3000` or localhost, organisations only works with the former.

**Comment by vineetpradhan-dev** [comment]
@emrysal I can't access `app.cal.local:3000`

**Comment by emrysal** [comment]
You need to add this to your /etc/hosts file (or the windows equivalent of this)
