### ISSUE TITLE
Double Booking (for requests that require confirmation)

### ISSUE THREAD

**Issue by mywebmasteruk** [calcom/cal.com#10789]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If two different users try to book the same slot that requires Confirmation. The admin is able to Confirm both, and this creates a double booking.

### Steps to Reproduce

1. 1st user books a slot (requires confirmation)
2. 2nd user books the same slot (requires confirmation)
3. Admin Confirms first slot booking
4. Admin Confirms 2nd booking for the same slot

### Actual Results

- It is allowing Admin to Confirm the same slot from two different requests

### Expected Results

- It should not allow Admin to confirm a slot, once it has been confirmed 

### Technical details

using hosted app.cal.com

### Evidence
Screneshot
https://www.awesomescreenshot.com/image/42238430?key=bccaaa338af85f1393a0a9bdd56189e6

**Comment by vineetpradhan-dev** [comment]
@mywebmasteruk  If user accepts one booking, the remaining booking should request for reschedule or cancel the booking
