### ISSUE TITLE
[CAL-2361] Booker bundle analysis and improvements

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10798]
## libphonenumber\[Resolved\] - \~8% reduction

* Phone Number validation library adding 27KB to bundle size
* Possible optimization Scope
  * It's needed only when Phone Number field is there. So, lazy load it only when needed and not in initial payload.

    ![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/62b9483a-6cc4-42e0-bdac-ac39ab8650a7/a48ec460-ee5b-48b3-8501-f8076a8d9a80?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82MmI5NDgzYS02Y2M0LTQyZTAtYmRhYy1hYzM5YWI4NjUwYTcvYTQ4ZWM0NjAtZWU1Yi00OGIzLTg1MDEtZjgwNzZhOGQ5YTgwIiwiaWF0IjoxNjkyMTg4MTYzLCJleHAiOjE2OTIyNzQ1NjN9.kUNkkhelnAJcEjyn1k9nNxobAEh5UDpaeQGHqMGJZHY)

## sanitize-html\[Resolved\] - \~29% reduction

* It should never be imported client side.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/944e84b6-385b-4709-9c57-cc039343ab48/fe522701-94b9-4094-9225-c9b01843118e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NDRlODRiNi0zODViLTQ3MDktOWM1Ny1jYzAzOTM0M2FiNDgvZmU1MjI3MDEtOTRiOS00MDk0LTkyMjUtYzliMDE4NDMxMThlIiwiaWF0IjoxNjkyMTg4MTYzLCJleHAiOjE2OTIyNzQ1NjN9.ZB-CsJ-rUJtPk1jaSvmenmWGr7Vnw1OKYCJGHiYWm6Q)

## AppStore payload\[In Review\] - No significant reduction

[https://github.com/calcom/cal.com/issues/7276](https://github.com/calcom/cal.com/issues/7276)

## Lodash \[Done\]

* We shouldn't really need lodash. Let's remove it

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2a6dd0fc-f5ed-4703-9952-81400fc058d4/c57b10bc-97f3-4d05-8d68-91241df0661a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yYTZkZDBmYy1mNWVkLTQ3MDMtOTk1Mi04MTQwMGZjMDU4ZDQvYzU3YjEwYmMtOTdmMy00ZDA1LThkNjgtOTEyNDFkZjA2NjFhIiwiaWF0IjoxNjkyMjY0NzI0LCJleHAiOjE2OTIzNTExMjR9.lCJVumtFralpqSgId8_MTSJWK1BVpI90Xdnmr24foVo)

## react-select\[Done\]

It could be lazy loaded

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d961fb5d-8317-4627-8d30-0d8a67997761/5cbe5805-fa1b-4578-9dbf-05c8940851e6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kOTYxZmI1ZC04MzE3LTQ2MjctOGQzMC0wZDhhNjc5OTc3NjEvNWNiZTU4MDUtZmExYi00NTc4LTlkYmYtMDVjODk0MDg1MWU2IiwiaWF0IjoxNjkyMjY5MDI3LCJleHAiOjE2OTIzNTU0Mjd9.PV5TWXcIWWoemNNLM1iyQXWNrNhQo6LF0hRZdF8LzUY)

## purify.js\[Done\]

* Who needs it on client?

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f706275d-8b25-4752-829e-d9974b4b12f8/484c880c-9f54-4498-97c0-39a503de63a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mNzA2Mjc1ZC04YjI1LTQ3NTItODI5ZS1kOTk3NGI0YjEyZjgvNDg0Yzg4MGMtOWY1NC00NDk4LTk3YzAtMzlhNTAzZGU2M2E5IiwiaWF0IjoxNjkyMjcxNjA4LCJleHAiOjE2OTIzNTgwMDh9.NAlmDsktlgpvIrDGplAisg8Yd_8o08Ln5k5M7sYCqAs)

## To measure the impact of working on these bundle optimizations let's check PSI Report

* [https://pagespeed.web.dev/analysis/https-cal-com-hariom-30min/eg6wdda7ce?form_factor=mobile](https://pagespeed.web.dev/analysis/https-cal-com-hariom-30min/eg6wdda7ce?form_factor=mobile) → 17th Aug\[No Optimization Live yet\]

# Before any of the above optimizations

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7f0f3929-9cec-4994-a771-ad17af1c9b8b/c51fdab1-8318-4edd-a257-06728f349af6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83ZjBmMzkyOS05Y2VjLTQ5OTQtYTc3MS1hZDE3YWYxYzliOGIvYzUxZmRhYjEtODMxOC00ZWRkLWEyNTctMDY3MjhmMzQ5YWY2IiwiaWF0IjoxNjkyMjg1Njk5LCJleHAiOjE2OTIzNzIwOTl9.R4o1K49Ww_k6KmiDJUXH2hZpyCuEYr2DG5fXIzKQdSk)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2361](https://linear.app/calcom/issue/CAL-2361/booker-bundle-analysis-and-improvements)</sub>

**Comment by Abdel-Monaam-Aouini** [comment]
please remove lodash
