### ISSUE TITLE
[CAL-2359] color tokens are not used in payment form

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#10796]
### Issue Summary

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/85140c4a-f39c-408d-a8c2-83882679591f/03724a59-b9f1-4721-85de-d9bbaf803417?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84NTE0MGM0YS1mMzljLTQwOGQtYThjMi04Mzg4MjY3OTU5MWYvMDM3MjRhNTktYjlmMS00NzIxLTg1ZGUtZDliYmFmODAzNDE3IiwiaWF0IjoxNjkyMTc1Mjg0LCJleHAiOjE2OTIyNjE2ODR9.dcXFWWj5oi4aPaJi7sryxPpOk7REO0S6o13aQarkvJY)

### Steps to Reproduce

1. Install Stripe and create a paid booking
2. Book a time slot
   \]

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2359](https://linear.app/calcom/issue/CAL-2359/color-tokens-are-not-used-in-payment-form)</sub>

**Comment by iSatVeerSingh** [comment]
I want to work on this issue but Stripe app is not installing in my development server. I am getting this error while installing the Stripe app. Please help me.
![Screenshot from 2023-08-16 15-49-34](https://github.com/calcom/cal.com/assets/85070570/5f1b84a7-0bce-4f21-950d-6e5aae1aa3f8)

**Comment by vineetpradhan-dev** [comment]
@iSatVeerSingh https://cal.com/docs/introduction/quick-start/self-hosting/install-apps/stripe#setting-up-stripe
