### ISSUE TITLE
Ability to add booking yourself and add guests manually

### ISSUE THREAD

**Issue by thomasmol** [calcom/cal.com#10794]
### Is your proposal related to a problem?

Sometimes I've already agreed on a time and date with someone on a meeting. In this case I don't want to sent them my cal.com link but just create the booking myself and add them as guests and sent them the confirmation email. I think this is possible in other meeting apps, where the organizer just sets a time and date and the guests all receive an invite through email.

### Describe the solution you'd like

Ability to create a booking in the app environment and add guests.

### Describe alternatives you've considered

A possible workaround is to create a booking using your link yourself and then adding the guests there. Problem is that you yourself become both a guest and organizer in the booking: 
<img width="570" alt="image" src="https://github.com/calcom/cal.com/assets/6241551/787ae3d4-3306-405c-adc1-7da8de6c9e78">

So you get double confirmation/reminder/cancel emails, and two calendar entries.

### Additional context

It would also be cool if I could create a booking myself and just sent a link with the booking to someone, like an invite. Then on that page they can confirm the booking and enter their email to get the confirmation and calendar entry.

### Requirement/Document

None!

**Comment by austriker27** [comment]
Id love to see this - I was shocked its not possible when its such a widely used feature in competitors like zoom.

**Comment by felipeschneider88** [comment]
Another similar use case is when someone shows up to my shop and I have an open slot and I want to provide the service. Something like a button "no agenda" to add them quickly

**Comment by milospuac** [comment]
_It would also be cool if I could create a booking myself and just sent a link with the booking to someone, like an invite. Then on that page they can confirm the booking and enter their email to get the confirmation and calendar entry._

TRY THIS: 
<img width="839" alt="Screenshot 2023-09-21 at 11 32 52" src="https://github.com/calcom/cal.com/assets/97884287/845e0f79-38d9-4d3e-a4c6-a5724cb9f80a">

**Comment by thomasmol** [comment]
Alright thanks @milospuac for the call and explanation. My original request in this issue is technically possible so I have created a new feature request here #11477 that suggests a UI/UX improvement for this use case.

**Comment by itstomekk** [comment]
How about adding guests **after** the booking, is it possible?
