### ISSUE TITLE
[CAL-2357] [E2E]: A test that verifies that having same team and user slug would work

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10793]
This test would have avoided this regression https://github.com/calcom/cal.com/pull/10724.

If there is a username 'acme-1234' and there is a team with slug 'acme-1234', both of them should work. One has a link /acme-1234 and other one has link team/acme-1234/

<sub>[CAL-2357](https://linear.app/calcom/issue/CAL-2357/[e2e]-a-test-that-verifies-that-having-same-team-and-user-slug-would)</sub>

**Comment by codingmickey** [comment]
Hi @hariombalhara I would like to add this test.. can I get a head start on how to proceed? Thank you!

**Comment by codingmickey** [comment]
Hi @PeerRich so the flow isn't like first assigning the issue then working on it? I thought it was that is why didn't pick up on this.. :(
