### ISSUE TITLE
[CAL-2365] missing border-subtle for api keys

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10829]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/43a8cb10-696a-42f9-9341-bd0fd77483ef/642faa35-6e8a-4b05-ac93-dae91c12745b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80M2E4Y2IxMC02OTZhLTQyZjktOTM0MS1iZDBmZDc3NDgzZWYvNjQyZmFhMzUtNmU4YS00YjA1LWFjOTMtZGFlOTFjMTI3NDViIiwiaWF0IjoxNjkyMzUxMDg5LCJleHAiOjE2OTI0Mzc0ODl9.VRvqTFJMvsIRrD9Y9NBrtniaPhpJlMM9heEZAjrfSR8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2365](https://linear.app/calcom/issue/CAL-2365/missing-border-subtle-for-api-keys)</sub>

**Comment by hempun10** [comment]
@PeerRich  Hey, can you explain the issue a little bit more?
