### ISSUE TITLE
[CAL-2364] Italics doesn't save as italics in the event description

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10828]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/03caf122-2959-40ef-a534-d7219d0f97de/a0b83909-54c9-461a-9ba9-976c02a4305a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wM2NhZjEyMi0yOTU5LTQwZWYtYTUzNC1kNzIxOWQwZjk3ZGUvYTBiODM5MDktNTRjOS00NjFhLTliYTktOTc2YzAyYTQzMDVhIiwiaWF0IjoxNjkyMzQ0MzM0LCJleHAiOjE2OTI0MzA3MzR9.TTEIBAYSlj7nSSXkvTVAWkaeOcyEuEV-vVUqnOVi37c)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ebed2c23-ebcc-43fc-add0-f09a1be3a894/bcc0024d-812a-42ac-8105-d20988f5e7d5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lYmVkMmMyMy1lYmNjLTQzZmMtYWRkMC1mMDlhMWJlM2E4OTQvYmNjMDAyNGQtODEyYS00MmFjLTgxMDUtZDIwOTg4ZjVlN2Q1IiwiaWF0IjoxNjkyMzQ0MzM0LCJleHAiOjE2OTI0MzA3MzR9.wMYCS50ChfltUXB00ZN4nDsVp6_wAvqWX8JJJsKMeAI)

Italics doesn't save as italics in the event description

Created via Threads. See full discussion: [https://threads.com/34527608301](https://threads.com/34527608301)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2364](https://linear.app/calcom/issue/CAL-2364/italics-doesnt-save-as-italics-in-the-event-description)</sub>

**Comment by hrutik7** [comment]
Hey @milospuac ,
I noticed this behavior too
if possible can you please assign this to me
