### ISSUE TITLE
Deleting availability date overrides deletes the wrong entry

### ISSUE THREAD

**Issue by sirodoht** [calcom/cal.com#10839]
### Issue Summary

In 'Availability', if one chooses a set of hours, and adds some date overrides, then if one deletes an entry, then another entry will be deleted instead of the one clicked.

### Steps to Reproduce

1. Went to https://app.cal.com/availability
2. Clicked on my set of available hours
3. Add 4 date overrides, which are all 'All day unavailable'
4. Save
5. Refresh
6. At the same set of available hours, delete the first entry.
7. The last entry gets deleted instead of the first.

### Actual Results

- Last entry gets deleted

### Expected Results

- First entry should have been deleted.

### Technical details

- https://github.com/calcom/cal.com/assets/553444/f1468480-2430-470e-8144-d160b9e15077
- Firefox 116.0.2
- macOS Ventura 13.5

### Evidence

https://github.com/calcom/cal.com/assets/553444/f1468480-2430-470e-8144-d160b9e15077

**Comment by anshuljangra003** [comment]
for me its working perfectly.

**Comment by sumitsingh6** [comment]
works fine to me

**Comment by ciaranha** [comment]
Can't reproduce. Closing.
