### ISSUE TITLE
Dashboard doesn't load anymore

### ISSUE THREAD

**Issue by marielisevw** [calcom/cal.com#10831]
Since yesterday, my dashboard won't load anymore.
This is the screen I get to see: https://prnt.sc/kdtWfvKO2W6E

I already deleted my cookies, but the issue remains...

How can I fix this?

Thank you!

**Comment by Udit-takkar** [comment]
@marielisevw try login again here https://app.cal.com/auth/login. if this doesn't fix the issue can you tell me your cal username?

**Comment by marielisevw** [comment]
Hi Udit,

When I click on the link, I immediately go to
https://app.cal.com/event-types and I can not logout from there, since the
page looks like this:

[image: image.png]

I've tried it on a Windows computer (and Chrome) and there it works.
My own computer is a Mac (with Chrome) and here it doesn't...

Thank you for your help,

Marie

Op zo 20 aug 2023 om 21:58 schreef Udit Takkar ***@***.***>:

**Comment by PeerRich** [comment]
can you try and remove your cookies and cache on your Mac? I cannot reproduce this, this sounds like a local problem
