### ISSUE TITLE
pass id of the event in redirect url

### ISSUE THREAD

**Issue by MyPsyOnline** [calcom/cal.com#10841]
### Is your proposal related to a problem?

Cal.com is a nice tool for Bookings. But other tools are nice for billing, customer relationship, etc..
But how to link events from cal.com with other tools ?

### Describe the solution you'd like

  I would like to be able to pass the uid of the event in the redirect url

### Suggestion

This should only need a variable, like we already have for the event name ( {Organiser} , ..), but for redirection url.
For example, https://redirect_url?uid={event_uid}

**Comment by mohdsaad17** [comment]
Please assign this to me

**Comment by MyPsyOnline** [comment]
@PeerRich : Hello can you assign to @mohdsaad17 or should i do it ? (how?)

**Comment by MyPsyOnline** [comment]
To be more precise, the id needed would be `bookingId` and not `uid`
