### ISSUE TITLE
[CAL-2368] Workflow trigger not working properly with approvals

### ISSUE THREAD

**Issue by ahmedsadman** [calcom/cal.com#10846]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

For all my meetings, I have approvals turned on. For the past few days, what I'm seeing is, when I approve one meeting, all the workflows get triggered at once, without respecting the current day or time.
For example, I have a 24hr and 1hr reminder for me and the attendee. Let's say someone booked a meeting with me on 25th August and I approve it on Aug 20. I would immediately get both reminders on that time, which is not expected.

### Steps to Reproduce

1. Create a 60 min event
2. Turn on approval setting for that event
3. Book a slot
4. Make sure some kind of "email reminder" workflows are there. Like 24hrs ahead notification. Both for host and attendee
5. Approve the slot
6. All workflows get trigerred

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Workflows gets triggered without respecting timing rules

### Expected Results

- Workflow should only get triggered if a meeting is approved, and at the proper time.

### Technical details

- Chrome  116.0.5845.96.

### Evidence

Please refer to reproduction steps

<sub>[CAL-2368](https://linear.app/calcom/issue/CAL-2368/workflow-trigger-not-working-properly-with-approvals)</sub>

**Comment by ahmedsadman** [comment]
On a different note, I have been using Cal.com for quite some time. But recently it has got buggier than ever. I know it's an open-source free product, nevertheless, such regressions are not really expected at this scale. In my humble opinion, I believe the user experience would be much better if you introduce/improve rigorous testing. My customers are complaining about various unexpected issues on a regular basis. Again, I know it's a free product and I respect that. It's just that I would love to stay on open-source solutions.

**Comment by PeerRich** [comment]
@ahmedsadman we have been working on a comprehensive suite of tests, what bugs are you running into specifically? it helps if we have tickets for them and we will add a high priority label to it

**Comment by PeerRich** [comment]
@CarinaWolli can you look into this?

**Comment by ahmedsadman** [comment]
@PeerRich I don't have reproduction steps but will try to figure it out. The most I faced was a booking failure with a message of a similar sort: "Could not book the meeting. Please try another date/time". Although, I could confirm I was free at those times. This has happened multiple times.

@CarinaWolli Just to add, I figured out it's not just an issue with approvals, the same behavior can be observed with non-approval events as well

**Comment by CarinaWolli** [comment]
I am able to reproduce it, definitely a regression. Thank you for reporting that 🙏
