### ISSUE TITLE
[CAL-2366] Running E2E locally yields ECONNREFUSED

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#10855]
```
          @leog @shivamklr I think this is why I get so many errors running e2e locally on production builds.
```

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2781b65e-2432-4ba5-b399-8c213733a911/8b48aed9-97d3-4467-95c3-69621bd12fef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yNzgxYjY1ZS0yNDMyLTRiYTUtYjM5OS04YzIxMzczM2E5MTEvOGI0OGFlZDktOTdkMy00NDY3LTk1YzMtNjk2MjFiZDEyZmVmIiwiaWF0IjoxNjkyNTcyMjAyLCJleHAiOjE2OTI2NTg2MDJ9.cyvdfuInuU0eMakTb1vRoZ7yAO6v-4a1XzwUiq2zmXo)

Can we make this optional? Only check for mailhog if it's enabled. I spent quite a while figuring out why all my tests were failing locally. At least we should document and update the README with instructions.

\*Originally posted by @zomars in \*[*https://github.com/calcom/cal.com/pull/10606#discussion_r1299447778*](https://github.com/calcom/cal.com/pull/10606#discussion_r1299447778)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2366](https://linear.app/calcom/issue/CAL-2366/running-e2e-locally-yields-econnrefused)</sub>

**Comment by shivamklr** [comment]
@zomars Thank you for your feedback. I understand your frustration with the mailhog dependency for running e2e locally on production builds. I agree that we should make this optional and update the README accordingly. I have created a pull request at #10881 that implements a possible solution. It allows the emails fixture to return undefined if the E2E_TEST_MAILHOG_ENABLED environment variable is not set to "1". This way, the mailhog API object will only be initialized if needed. I hope this resolves the issue and makes the e2e testing more convenient for you. Please let me know what you think of this approach.
