### ISSUE TITLE
Dynamic Booking Links: Location Options lost

### ISSUE THREAD

**Issue by paul-siteway** [calcom/cal.com#10859]
### Issue Summary

On the dynamic booking link pages, the video conferencing options are not available (Zoom/MS Teams/...). Only one option is show. Even though all users have installed the apps. 

### Steps to Reproduce

1. Open https://meet.helden.com/paul/15min See that **multiple** video conferencing options are available
2. Open https://meet.helden.com/richard/15min See that **multiple** video conferencing options are available
3. Open https://meet.helden.com/paul+richard See that **only one** video conferencing option is available 

### Actual Results

- Only one Video conferencing option is available. 

### Expected Results

- All (shared?) video conferencing option should be available. 

### Technical details

[v.3.2.0-sh](https://go.cal.com/releases)

### Evidence

![image](https://github.com/calcom/cal.com/assets/3603487/b6433af4-1faf-47a6-a2b1-63252b97cd06)
![image](https://github.com/calcom/cal.com/assets/3603487/35edbb28-6ecc-498e-9da7-c98979247cf1)
![image](https://github.com/calcom/cal.com/assets/3603487/fe5bde17-e23a-4fc1-8804-21d03d908d03)

**Comment by PeerRich** [comment]
this is by design, we can only take defaults because in group meetings we cant decide whos video link to take. so for now, all dynamic links have the same location link: Cal Video

**Comment by paul-siteway** [comment]
Does this apply to the self hosted version? 

At least in our instance we get google meet as same location link in dynamic booking links. As you can see in the screenshots.
