### ISSUE TITLE
[CAL-2519] Cannot book Dynamic Event Type

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#10857]
### Issue Summary

On Prod, I noticed while booking a dynamic event, I received a 500 status code error and an error message.

### Evidence
![response500](https://github.com/calcom/cal.com/assets/22683064/17926105-3d71-4e2e-9328-942cf17fcbc9)

<sub>[CAL-2519](https://linear.app/calcom/issue/CAL-2519/cannot-book-dynamic-event-type)</sub>

**Comment by keithwillcode** [comment]
This has been fixed.
