### ISSUE TITLE
Stripe Connect with Payouts and comissions

### ISSUE THREAD

**Issue by giovannicocco** [calcom/cal.com#10870]
Improve integration between platform and users (providers) using Stripe Connect.

The objective is to generate the option to commission the platform for each appointment made with advance online payment.

In a medical clinic, law firm or consultancy, professionals (users/providers) share the revenue from appointments with the company (platform).

Platform admin chooses between Standard, Express and Custom Stripe Connect types;

When a user (provider) signs up, you must create a corresponding user Account (referred to as a connected account).

Link a user Account to platform account;

Choose whether the commission will be a % (percentage) or a fixed amount;
Choose whether the commission will be applied to all users or whether the commission will be at the user or team level.

Accept payments and payout;

**Comment by PeerRich** [comment]
you can already do this with the STRIPE_FEE (or so) .env environments when self-hosting
