### ISSUE TITLE
[CAL-2370] Public booking page embed needs margins around the sides

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#10878]
The embed modal should have a margin on the left and right that matches the margin at the bottom, it should not hug the edge of the page.

![CleanShot 2023-08-22 at 08 45 25@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2d462c4c-91de-4c8b-b62a-c7883e3b2c75/bc62f182-0fc2-4809-96ff-0c5975a9004c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yZDQ2MmM0Yy05MWRlLTRjOGItYjYyYS1jNzg4M2UzYjJjNzUvYmM2MmYxODItMGZjMi00ODA5LTk2ZmYtMGM1OTc1YTkwMDRjIiwiaWF0IjoxNzA0NDA0MjYwLCJleHAiOjE3MDQ0OTA2NjB9.QIlqyTad1l3ilkqic74mxgzdZsvzjo4amthn9v-4-k4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2370](https://linear.app/calcom/issue/CAL-2370/public-booking-page-embed-needs-margins-around-the-sides)</sub>

**Comment by joe-shajan** [comment]
I would like to work on this. Can you assign this to me @ciaranha ?

**Comment by ciaranha** [comment]
@joe-shajan feel free to tackle and mention this issue in your pr and our team will review it. Thank you 🙏

**Comment by hritikRajput** [comment]
> 

@ciaranha How can I reproduce this screen?
