### ISSUE TITLE
[CAL-2371] Show busy blocks overlayed on public calendars when logged in

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#10879]
When a user is logged into [Cal.com](http://Cal.com) and views another person's calendar, we should show their busy blocks so they don't book times on someone elses calendar when they're not available themselves.

The v2 of this feature will allow users to login with other providers to "overlay their calendar" but this v1 will just do it for people who are logged in already. However, we can utilise the design solutions for the calendars from those designs for this v1:

[New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=5679%3A305336&mode=dev)

![Weekly view.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e28f2fb9-a3fa-4148-b4a8-ba7b6465c1e8/0dee4c1d-75d1-41f1-9a46-9d9f962c0e5b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lMjhmMmZiOS1hM2ZhLTQxNDgtYjRhOC1iYTdiNjQ2NWMxZTgvMGRlZTRjMWQtNzVkMS00MWYxLTlhNDYtOWQ5Zjk2MmMwZTViIiwiaWF0IjoxNjkyNjkyMTUzLCJleHAiOjE2OTI3Nzg1NTN9.FwBuGs40LeHy_IwJVLtHsiKLhykFCWGfP6-o4kFMKiU)

![Column view.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9205f5e3-6e9b-4ca7-b12e-87eed7917513/e367719b-55a6-4cb7-b487-3ccfe5d34348?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MjA1ZjVlMy02ZTliLTRjYTctYjEyZS04N2VlZDc5MTc1MTMvZTM2NzcxOWItNTVhNi00Y2I3LWI0ODctM2NjZmU1ZDM0MzQ4IiwiaWF0IjoxNjkyNjkyMTUzLCJleHAiOjE2OTI3Nzg1NTN9.G7etlENI40eWCPA7VvnlwX5UtwDxSQW2jk4F-pKU9Qc)

![Monthly view.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/454aac3d-6b1f-420b-ba5a-5d7145ff8b91/caafd481-1184-4f04-8d08-0477b1608843?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NTRhYWMzZC02YjFmLTQyMGItYmE1YS01ZDcxNDVmZjhiOTEvY2FhZmQ0ODEtMTE4NC00ZjA0LThkMDgtMDQ3N2IxNjA4ODQzIiwiaWF0IjoxNjkyNjkyMTUzLCJleHAiOjE2OTI3Nzg1NTN9.PNRTGbasqPY1831IKSoIpBQWhPYkyDSb-iwMtJbHUiM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2371](https://linear.app/calcom/issue/CAL-2371/show-busy-blocks-overlayed-on-public-calendars-when-logged-in)</sub>

**Comment by MehulZR** [comment]
![image](https://github.com/calcom/cal.com/assets/86384652/8b07d7b1-1179-44f8-8f02-687e915a0262)

Hey @ciaranha What is the difference between the dashed time slots borders and the solid time slots borders?

**Comment by MehulZR** [comment]
https://github.com/calcom/cal.com/assets/86384652/d3969ff7-fb14-4585-a30d-a0edbcc8df82

Early build.

Need some input regarding above questions from @ciaranha so I can proceed further.

**Comment by aspiers** [comment]
Isn't this a duplicate of #2558, or am I missing something?

**Comment by ciaranha** [comment]
V2 of this feature coming soon https://github.com/calcom/cal.com/issues/12763
