### ISSUE TITLE
[CAL-2373] Dark mode badges

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#10883]
Current Badges:-

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/df82e3d3-c146-4385-880f-89b54455cb16/8224c649-a619-4289-82af-0f75da47963c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kZjgyZTNkMy1jMTQ2LTQzODUtODgwZi04OWI1NDQ1NWNiMTYvODIyNGM2NDktYTYxOS00Mjg5LTgyYWYtMGY3NWRhNDc5NjNjIiwiaWF0IjoxNjkyNzA0NDI5LCJleHAiOjE2OTI3OTA4Mjl9.WqMaphsVazl2LcV0k14j0FD83uIp2yfSnQKYPun_Cns)

the badges should have different colours in dark mode. figma [https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=37611-2419&mode=design&t=HFnrHHX2EdFAec3N-0](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=37611-2419&mode=design&t=HFnrHHX2EdFAec3N-0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2373](https://linear.app/calcom/issue/CAL-2373/dark-mode-badges)</sub>

**Comment by AshfaqKabir** [comment]
@Udit-takkar what's the Url Route to this page

**Comment by PeerRich** [comment]
@AshfaqKabir no need to viist that page, just change the colors from current to the ones in figma

**Comment by vipul1079** [comment]
![Screenshot 2023-08-23 164420](https://github.com/calcom/cal.com/assets/56021224/46f21e53-f66c-44f1-8dc8-9303b3b1866e)
![Screenshot 2023-08-23 164430](https://github.com/calcom/cal.com/assets/56021224/25308f9e-f8f3-4063-9b1c-84459de6b216)

While I was trying to set up cal.com locally , I was stuck on logging in . Can anyone help me i am new to open source

**Comment by MeenuyD** [comment]
Hello @vipul1079 when you run the command yarn dx there are multiple emails and passwords you can try for locally.

**Comment by vipul1079** [comment]
hey @MeenuyD Thanks for the heads up I will try this.

**Comment by Chinmay-Deo-2004** [comment]
@Udit-takkar, Is anyone working on this issue currently? If not, please assign it to me. I'd like to fix it.
