### ISSUE TITLE
[CAL-2372] Perf: Bundle Size Booker - if Possible, Lazy load useAnimate or replace with m.div

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10880]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a719c4b5-0710-4d57-aa5e-09ce2e28a245/1f5da07e-6cc6-4638-ac38-d80073cad44b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNzE5YzRiNS0wNzEwLTRkNTctYWE1ZS0wOWNlMmUyOGEyNDUvMWY1ZGEwN2UtNmNjNi00NjM4LWFjMzgtZDgwMDczY2FkNDRiIiwiaWF0IjoxNjkyNjk0NzcyLCJleHAiOjE2OTI3ODExNzJ9.JPM8oXNOJ6-JZMwavejFM_hbPXvlfrRNfJNjCDpGR5o)

m.div is lazy loadable
[https://www.framer.com/motion/use-animate/##useanimate-vs-motiondiv](https://www.framer.com/motion/use-animate/##useanimate-vs-motiondiv)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2372](https://linear.app/calcom/issue/CAL-2372/perf-lazy-load-useanimate-or-replace-if-possible-with-mdiv)</sub>

**Comment by xNOVA2** [comment]
working on it
