### ISSUE TITLE
[CAL-2378] All existing workflows for the event type sent instead of one

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10899]
[https://www.loom.com/share/d620aac1b09d47159eb9e6cf7be3c098?sid=bced9d06-8c00-47b5-9108-cc89b786e113](https://www.loom.com/share/d620aac1b09d47159eb9e6cf7be3c098?sid=bced9d06-8c00-47b5-9108-cc89b786e113)

Created via Threads. See full discussion: [https://threads.com/34529355688](https://threads.com/34529355688)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2378](https://linear.app/calcom/issue/CAL-2378/all-existing-workflows-for-the-event-type-sent-instead-of-one)</sub>

**Comment by CarinaWolli** [comment]
fixed here: [10890](https://github.com/calcom/cal.com/pull/10890)
