### ISSUE TITLE
Same Booking slot can be booked multiple times

### ISSUE THREAD

**Issue by manjufy** [calcom/cal.com#1089]
### Issue Summary

The same booking slot can be booked multiple times.

I have an event with booking starting from 9 am to 12 pm.

I made a booking for the 9 am slot, and I could do the same multiple times. If the 9 am booking slot has already been taken, I believe, we should disable the slot for further booking.

### Steps to Reproduce

1. Create an Event Type
![Screenshot 2021-10-31 at 12 40 46 PM](https://user-images.githubusercontent.com/5035624/139568057-2d0bc7a9-5eaf-4a12-8e1b-cf06c07af6f9.png)

2. Define Availability as shown below
![Screenshot 2021-10-31 at 12 40 54 PM](https://user-images.githubusercontent.com/5035624/139568066-247c9d10-ed37-44ef-81a5-fc6b0ed175bd.png)

3. Go to the Preview link and select the first slot and confirm the booking, 
![Screenshot 2021-10-31 at 12 41 02 PM](https://user-images.githubusercontent.com/5035624/139568070-d7c273ad-f29b-49fc-bc96-5472a0838e4c.png)
4. Repeat steps 3, and you could notice, you would be able to do multiple bookings for the previously booked slots.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
- Node.js version
- Anything else that you think could be an issue.

**Comment by manjufy** [comment]
Quite similar to https://github.com/calendso/calendso/issues/877

**Comment by aleexalcaraz** [comment]
Hello
I think it could be a good idea to have the option to be able to book a slot only once or multiple times.

I don't know if they are going to submit a PR for this but what I did to be able to only book a slot once is:

On pages/[user]/[type].tsx getServerSideProps I added
`const bookings = await prisma.booking.findMany({
    where: {
      eventTypeId: {
        equals: eventTypeObject.id,
      },
    },
  });`

 I pass it on the props all the way to useSlots.ts. Here, before setting the slots on the state, I filtered the slots that are already on the bookings array. If the date matches the slots date I remove it from the slots array.
 
 `const finalSlots = loadedSlots.filter((slot) => !bookingsArr.includes(slot.time.toString()));`

Hope it helps

**Comment by manjufy** [comment]
I will give it a try @aleexalcaraz 
That's a great help. Thank you so much.

**Comment by oleppe** [comment]
@aleexalcaraz Could you please share the full code how to implement this. I'm new to react and I found it a little bit hard to understand this. Thanks

**Comment by PeerRich** [comment]
did you connect a calendar? this happens when no calendar is connected

**Comment by PeerRich** [comment]
hey, can you try the latest version?
