### ISSUE TITLE
[CAL-2376] turn API setup into OAuth permission screen

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10891]
instead of creating keys and copy/pasting them, it would be nice if we have a "xxx wants to access your [Cal.com](http://Cal.com) account" OAuth screen like Google and other apps:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a2504e50-f18f-4c21-ad34-285217492c02/cb9440d5-33db-47b7-a6b9-f8758fd4ee1e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMjUwNGU1MC1mMThmLTRjMjEtYWQzNC0yODUyMTc0OTJjMDIvY2I5NDQwZDUtMzNkYi00N2I3LWE2YjktZjg3NThmZDRlZTFlIiwiaWF0IjoxNjkyNzIxODg2LCJleHAiOjE2OTI4MDgyODZ9.inlRYDHgf5wql1wBAaI_O_BM5EJZR1HONCLcSZ9da_Q)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9a159e5b-4390-4fa6-99e0-c9f0521d012f/c48fb43b-c768-44f0-9b8e-20814dc7503a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85YTE1OWU1Yi00MzkwLTRmYTYtOTllMC1jOWYwNTIxZDAxMmYvYzQ4ZmI0M2ItYzc2OC00NGYwLTliOGUtMjA4MTRkYzc1MDNhIiwiaWF0IjoxNjkyNzIxODg2LCJleHAiOjE2OTI4MDgyODZ9.IQZR4gmK_q4gvgURMGyWMBmoK7ga9ymRzsGUe_PfecI)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/57db96a3-1ac5-42af-862f-e4af6eb45907/3dc11a61-78ca-4535-ad2b-2e8c1d9d6924?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81N2RiOTZhMy0xYWM1LTQyYWYtODYyZi1lNGFmNmViNDU5MDcvM2RjMTFhNjEtNzhjYS00NTM1LWFkMmItMmU4YzFkOWQ2OTI0IiwiaWF0IjoxNjkyNzIxODg2LCJleHAiOjE2OTI4MDgyODZ9.o2bAUhxf4mQ96uBERdISSILH93WZ7Q2WPNoMf98YebY)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1af9d3b3-2fbc-469c-87b1-c23445c07c77/585ac009-81dd-4c9c-8770-483e9a86b6ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xYWY5ZDNiMy0yZmJjLTQ2OWMtODdiMS1jMjM0NDVjMDdjNzcvNTg1YWMwMDktODFkZC00YzljLTg3NzAtNDgzZTlhODZiNmNlIiwiaWF0IjoxNjkyNzIxODg2LCJleHAiOjE2OTI4MDgyODZ9.Kr5SMEMMIoMKGJBbLzsYmWX5sIuj0-xAOVGButm2328)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2376](https://linear.app/calcom/issue/CAL-2376/turn-zapier-api-setup-into-oauth-permission-screen)</sub>

**Comment by mohitkhairia** [comment]
So just the UI needs to be changed, the OAuth functionality needs to be implemented or just the UI needs to be updated?

**Comment by PeerRich** [comment]
both. I am working on the UI, I think Carina may work on logic

**Comment by mohitkhairia** [comment]
Sounds good
