### ISSUE TITLE
[CAL-2377] Allow custom text in event type location

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#10892]
![CleanShot 2023-08-22 at 13.16.21.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5e79eccb-87eb-425b-b809-0a4c31451baf/e619ce82-c4fd-4f2c-b038-e76cea4f2b9a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ZTc5ZWNjYi04N2ViLTQyNWItYjgwOS0wYTRjMzE0NTFiYWYvZTYxOWNlODItYzRmZC00ZjJjLWIwMzgtZTc2Y2VhNGYyYjlhIiwiaWF0IjoxNjkyNzI0NjIzLCJleHAiOjE2OTI4MTEwMjN9.N5eP5tV92U34a7-UKb5RHP3lbKobGdS9YSrQH4X3lqI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2377](https://linear.app/calcom/issue/CAL-2377/allow-custom-text-in-event-type-location)</sub>

**Comment by Taha-1005** [comment]
Hi @joeauyeung , can I get some more information related to the feature you are referring to above. Thanks.

**Comment by joeauyeung** [comment]
The idea is to have a free text box as a location option for an event type. 

![CleanShot 2023-08-22 at 20 44 53](https://github.com/calcom/cal.com/assets/65426560/5af7070c-a505-44f9-8871-4b1f9dbf0c92)

The text would then show up on the booker page as the location.
![CleanShot 2023-08-22 at 20 46 35](https://github.com/calcom/cal.com/assets/65426560/dbf3f6d0-3ee7-4751-aa92-3318f88e4908)

**Comment by PiyushXmishra** [comment]
So @joeauyeung  you are saying that  to have a custom text box in Edit Location dropdown?



<img width="459" alt="image" src="https://github.com/calcom/cal.com/assets/110087602/c3d8c547-3b29-4489-ba4a-ace2473ca653">
e saying that  to have a custom text box in Edit Location dropdown?

**Comment by Taha-1005** [comment]
Hi, when I am setting up the project I am facing the following error:
![image](https://github.com/calcom/cal.com/assets/82571791/4dfe0120-386a-4465-a0a7-01d4a2c062dc)
Can someone help me out or direct me to someone who can? Thanks. @joeauyeung @PiyushXmishra @PeerRich

**Comment by ZainGulbaz** [comment]
#11105 @joeauyeung @PeerRich . Kindly have a look at this PR and let me know for any changes.

**Comment by ZainGulbaz** [comment]
[https://github.com/calcom/cal.com/pull/11105](url)
