### ISSUE TITLE
[CAL-2379] Required "Add guests" button isn't required on attendee's end

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10900]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/60ebb774-cc7a-450b-875e-7bf7c16e9cd0/4053d9b7-6e13-4545-b6b4-4101f81820f4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82MGViYjc3NC1jYzdhLTQ1MGItODc1ZS03YmY3YzE2ZTljZDAvNDA1M2Q5YjctNmUxMy00NTQ1LWI2YjQtNDEwMWY4MTgyMGY0IiwiaWF0IjoxNjkyNzgwODY4LCJleHAiOjE2OTI4NjcyNjh9.IHD57W3HhJAkN9nJHegvNHHBAWaHHAli702oEBgYaDs)

Attendee is able to book without providing the required section

Created via Threads. See full discussion: [https://threads.com/messages/263f3faa-645f-468a-b845-62d27fb7b5a6?messageID=bae323b0-0b16-41c6-b810-ef97ff3cabc1](https://threads.com/messages/263f3faa-645f-468a-b845-62d27fb7b5a6?messageID=bae323b0-0b16-41c6-b810-ef97ff3cabc1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2379](https://linear.app/calcom/issue/CAL-2379/required-add-guests-button-isnt-required-on-attendees-end)</sub>

**Comment by KSSaiTeja** [comment]
can i work on this issue

**Comment by PrathameshTheurkar** [comment]
can I work on  this issue

**Comment by parteekcoder** [comment]
The issue title and issue description doesnot point to the same bug

**Comment by ZainGulbaz** [comment]
@milospuac Can you please explain the issue?

**Comment by milospuac** [comment]
@ZainGulbaz pretty much self-explanatory. Make "Add guests" field mandatory. Try to test out the booking - It isn't mandatory.
