### ISSUE TITLE
Week view is not working in Arc browser

### ISSUE THREAD

**Issue by eliasfaltin** [calcom/cal.com#10908]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Week view is not working in Arc browser (gives the "not available on mobile, use desktop browser" error) 

### Steps to Reproduce

1. go onto a booking page
2. select weekly view
3. get error

Arc Version 1.4.1 (40966), Mac Dock hidden, Maximized window size (not the full screen mode, but maximized window size)

### Actual Results

- I get the "use a desktop browser" error while using a desktop browser. I would expect to see the week view

### Expected Results

- Week view works in the Arc browser..

### Technical details

- Arc Version 1.4.1 (40966), M2 MB Air, Mac Dock hidden, Maximized window size (not the full screen mode, but maximized window size)

### Evidence

![CleanShot 2023-08-23 at 16 49 23@2x](https://github.com/calcom/cal.com/assets/36010212/4bddadce-34cc-47e2-bb7a-3d952f04f625)

I was testing one of my own meeting links (actual link, NOT the "preview" link) when finding this bug.

**Comment by Ujjwal-Agarwal** [comment]
It works for me. Are you using any extensions/script modifiers?

<img width="1442" alt="image" src="https://github.com/calcom/cal.com/assets/70232756/af43ff24-0de8-4518-b4c7-eeaa799f6a83">

**Comment by eliasfaltin** [comment]
I am not using anything special that I know of... I will try to reproduce
it early next week (out hiking atm). Is there anything other than a screen
recording I could grab? Something from the dev console? Not an expert what
here on what could be useful...

**Comment by eliasfaltin** [comment]
I updated the browser, cleared my cache and browsing history, restarted my Mac, and restarted my browser. None of this fixes it.

I also contacted Arc's support to see if they have an idea. So far, they just recommended doing the above as well. I had this issue with another web app, so it is more likely this is either something on Arc's side or my side. I'll keep this updated if I hear something from Arc.

Here is a video of the issue: https://share.cleanshot.com/9mVzBjTG

Let me know if there is anything I can do in the dev console to get some relevant data/readouts for you!

**Comment by eliasfaltin** [comment]
I went ham and deleted a bunch of extensions a few days ago, and one of them must have been the culprit (I did not do a good job keeping track of which ones I deleted and don't want to blame the wrong one now).

But yeah, definitely was a me issue, not a you issue. Week view now works again!
