### ISSUE TITLE
[CAL-2381] invited by link throws 500

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10906]
inviting someone to a team via link is currently throwing a 500

<sub>[CAL-2381](https://linear.app/calcom/issue/CAL-2381/invited-by-link-throws-500)</sub>

**Comment by coolBrown12** [comment]
can you explain me clearly please where could be the error you are facing

**Comment by shivam969619** [comment]
can i take this issue

**Comment by abhijeetsingh-22** [comment]
> can i take this issue

Bro its already solved.
