### ISSUE TITLE
App installs not allowing a choice to select where to install - Inconsistent behavior across apps

### ISSUE THREAD

**Issue by jdefranco** [calcom/cal.com#10919]
### Issue Summary

I had been testing the installation of various apps and upon clicking install was given an option to select myself or a team as where to install. Now it is no longer asking me where and it is just defaulting to myself. So I am unable to add any other conferencing options to my Team. It is very odd behavior as for certain apps it prompts you others it doesn't. And particularly odd with jitsi as it gives the option and says it installs to both but it only installs to 1. 

### Steps to Reproduce

1. Clicked install
2. clicked 1 of two options My User or the Team
3.  It installs into that specified from above
4. Install is shown to be specific by creating an event type and seeing it now as an option .
5. Continue to do installs of other video conferencing apps

I was able to do about 3 or so installs where it prompted me where to install it, but now I can't get it to appear, it just auto installs to the one.

### Actual Results

- Only installing to a default 

### Expected Results

- Not giving option to install to team

### Technical details

- self hosted on vercel
- Node.js version 18

### Evidence

- Please see screencapture https://www.awesomescreenshot.com/video/20178335?key=e6dc37f13f71b83e47786e84bd8f43d2
- It is very odd how for some apps it asks you where to install and some they don't and as you can see in this video for jitsi it gives the option, and after installing it it still prompts the option selections but it delects them out to be unclickable and marked as already installed on both the team and user . When checking event types for both, it shows that jitsi is only available in the originally selected install and not on the other as it says they are both installed.

**Comment by PeerRich** [comment]
i can reproduce this. odd. let us investigate!

**Comment by PeerRich** [comment]
ok found out: its not enabled for all apps. some apps you cant install for teams. that's why
