### ISSUE TITLE
[CAL-2384] Canceled Booking throws off Variable

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10916]
![CleanShot 2023-08-23 at 08.09.32@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2b6fc47b-b1f8-406e-a7c7-3cfe50a34a3f/2bf179ee-8032-4c08-afad-603efb085be4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yYjZmYzQ3Yi1iMWY4LTQwNmUtYTdjNy0zY2ZlNTBhMzRhM2YvMmJmMTc5ZWUtODAzMi00YzA4LWFmYWQtNjAzZWZiMDg1YmU0IiwiaWF0IjoxNjkyODE0Mjk5LCJleHAiOjE2OTI5MDA2OTl9.OiWOiuLSjmy6sW-hDo3HYiSuhTr1pBizqB-5JJgYdEE)

![CleanShot 2023-08-23 at 08.09.40@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9a04e425-4c0b-4ca4-9f34-3a18cd6239ba/af0706f7-bed0-4529-8ecd-6bc4036b9139?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85YTA0ZTQyNS00YzBiLTRjYTQtOWYzNC0zYTE4Y2Q2MjM5YmEvYWYwNzA2ZjctYmVkMC00NTI5LThlY2QtNmJjNDAzNmI5MTM5IiwiaWF0IjoxNjkyODE0Mjk5LCJleHAiOjE2OTI5MDA2OTl9.WVFS_uFxVYwt8FTgrSyLI0MgePmx56H1Nk-Tn6ejH-g)

I put "**TEST**" as the company name that this is pulling in, not sure why it's throwing off a variable

![CleanShot 2023-08-23 at 08.10.52@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4c8ed7b9-c9b0-4f2d-a72e-63d329242244/dad30f31-e3b7-44b2-8e0a-72fe16361f09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80YzhlZDdiOS1jOWIwLTRmMmQtYTcyZS02M2QzMjkyNDIyNDQvZGFkMzBmMzEtZTNiNy00NGIyLThlMGEtNzJmZTE2MzYxZjA5IiwiaWF0IjoxNjkyODE0Mjk5LCJleHAiOjE2OTI5MDA2OTl9.4zDL_d-8MR-zC_ffwmUZlgUCj4zZ7ACrogck_0ULLfo)

Customer: [cal.com/team/spot](https://cal.com/team/spot)

Collective event: Meet with Spot

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2384](https://linear.app/calcom/issue/CAL-2384/canceled-booking-throws-off-variable)</sub>

**Comment by Udit-takkar** [comment]
![Screenshot 2023-08-24 at 1.38.36 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/569c3e8f-d5bd-40ee-a3f4-56f1dcc71aca/68105743-952e-4c9b-aef8-72c19f81c4d8)

i don't see {company} in available variables. can we add booking question answer in event name?
