### ISSUE TITLE
[CAL-2382] Bug on Event-Type with Required Fields

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10911]
A customer is dealing with an issue on their event type when they have the label "How did you hear from us" and the identifier is "source.identifier" and made "required" the booking won't go through and says "this is a required field" even though there is text 

Customer: [cameron@spotdx.com](cameron@spotdx.com)

I've impersonated and made sure this is a valid bug when the "required field is on" 

![CleanShot 2023-08-23 at 07.47.16@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/22ab4df5-596e-4841-877e-f053b096a575/637c5702-3544-45d3-b1bd-fc9f91b193af?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yMmFiNGRmNS01OTZlLTQ4NDEtODc3ZS1mMDUzYjA5NmE1NzUvNjM3YzU3MDItMzU0NC00NWQzLWIxYmQtZmM5ZjkxYjE5M2FmIiwiaWF0IjoxNjkyODEzMDE4LCJleHAiOjE2OTI4OTk0MTh9.di0CweJ5Wext4HBJ5HDNOAZCkK0dCcOfgyaxOQM6spQ)

![CleanShot 2023-08-23 at 07.48.25@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6593fc6e-b826-439b-8f2c-edfd47203554/dcd8efea-8605-4f63-a65e-9ed6a2dd5633?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82NTkzZmM2ZS1iODI2LTQzOWItOGYyYy1lZGZkNDcyMDM1NTQvZGNkOGVmZWEtODYwNS00ZjYzLWE2NWUtOWVkNmEyZGQ1NjMzIiwiaWF0IjoxNjkyODEzMDE4LCJleHAiOjE2OTI4OTk0MTh9.WbG6PH_giPBmYXyn9dS8i3BWHf3Ig_yRE3pTwJTi7ic)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2382](https://linear.app/calcom/issue/CAL-2382/bug-on-event-type-with-required-fields)</sub>

**Comment by hariombalhara** [comment]
This is already fixed in main. Dot would be converted to - when the event-tyoe is saved again.

**Comment by hariombalhara** [comment]
Release should go today itself, so after that saving it again would fix the issue and it won't be possible to add a dot again

**Comment by shirazdole** [comment]
Thank you!
