### ISSUE TITLE
[CAL-2383] Sharing reason (optional) on recurring events breaks cancellation

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10913]
I recently tried to cancel my booking with David, and when I add a reason as to why I get a 404 error, and the cancellation doesn't go through.

However, when I don't add a reason, the cancelation happens.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2383](https://linear.app/calcom/issue/CAL-2383/sharing-reason-optional-on-recurring-events-breaks-cancellation)</sub>

**Comment by riteshsinghh-coder** [comment]
not getting the error

**Comment by ciaranha** [comment]
Closing. Can’t reproduce. We can reopen if @shirazdole or anyone can reproduce in future.
