### ISSUE TITLE
Issues with installing Apps in app store

### ISSUE THREAD

**Issue by jdefranco** [calcom/cal.com#10917]
### Issue Summary

I am unable to install several apps from the app store after adding env variables in vercel 

I have added Daily, twilio, google, zoom, and sendgrid. The only one I am able to install is sendgrid.
Daily doesn't come up as an option, and google calendar and zoom errors.

### Steps to Reproduce

1. added env variables
2. seeded app store
3. attempted to install apps from App Store

### Actual Results

- erroring

### Expected Results

- Should install the apps

### Technical details

- Self Hosted on Vercel
- Node.js version 18

### Evidence
Screencapture:
https://www.awesomescreenshot.com/video/20176814?key=5aed37673d48b8a459f5a4d0ea8f68ee

**Comment by gitstart-calcom** [comment]
Hi @jdefranco @keithwillcode We believe this is not an issue, the issue creator try to install zoom app in the description video, this specific app needs some changes on .env file to work. We tried to install other apps and worked.
