### ISSUE TITLE
[CAL-2509] Remove brandColor usage in Embed Snippet Generator

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#10925]
<img width="584" alt="Screenshot 2023-08-24 at 2 09 55 PM" src="https://github.com/calcom/cal.com/assets/1780212/40a50b89-2afd-4498-bfca-19d6f0c6d78f">

We need to switch to using CSS variables - [Demo](https://codesandbox.io/s/embed-advanced-css-vars-x2sdgy) for the same

<sub>[CAL-2509](https://linear.app/calcom/issue/CAL-2509/remove-brandcolor-usage-in-embed-snippet-generator)</sub>

**Comment by JoeSkills** [comment]
Can I do it?

**Comment by varunsripad** [comment]
Can i work on this

**Comment by keithwillcode** [comment]
@JoeSkills @varunsripad no need to assign issues. Feel free to open a PR and we will review.
