### ISSUE TITLE
Daylight Savings Time (DST) bug is scheduling bookings an hour early

### ISSUE THREAD

**Issue by jimafisk** [calcom/cal.com#1092]
### Issue Summary

When booking appointments after 11/7 (daylight savings end), the start and end times get shifted one hour earlier on the confirmation page. The time looks correct when initially selecting a time slot and filling in your information:

<details>
<summary>See booking screenshot</summary>

![dst_before](https://user-images.githubusercontent.com/5913244/139622781-f71456c4-72a7-431a-bd43-bbdc71476e61.png)

</details>

However, the confirmation page and the event that actually gets added to my calendar are an hour early:

<details>
<summary>See confirmation screenshot</summary>

![dst_after](https://user-images.githubusercontent.com/5913244/139622707-1391574b-bc77-4425-8423-bade09688ade.png)

</details>

Booking appointments before 11/7 works as expected, so I suspect this is a DST issue.

### Steps to Reproduce

1. Book an event after 11/7 like normal
2. Observe that event gets added to your calendar an hour earlier than the time you picked

### Technical details

- Browser version: Chrome 95
- Calendar is hosted on cal.com (not self-hosted)

**Comment by ConnorGargano** [comment]
Hi @jimafisk,
Thank you for making us aware! We are working on this and we hope to get this fixed soon!
-Thanks, Connor

**Comment by wzrdtales** [comment]
not just the scheduling. events read from a calendar also interpreted an hour earlier. big issue

**Comment by wzrdtales** [comment]
it is very very weirdly wrong programmed.

the invitation is on time. the ics inside the invitation is one hour earlier. the zoom meeting is one hour earlier and the meeting parsing respects only one hour earlier.

**Comment by rjherrera** [comment]
hi there! I experienced this bug today, and i think it's related to this, as we will change our timezone this saturday.

In the link it shows the correct slot, but once the appointment is confirmed, it appears in my calendar one hour earlier, and it disregards any conflict (I have another meeting there).

Do you guys know if it is fixed in any recent release or commit?

**Comment by astrojuanlu** [comment]
Folks, I know that Timezones Are Hard™ but I can't think of anything that is more important to get right in a scheduling app to be completely honest. I know I'm not being particularly helpful here, just trying to highlight the fact (well, just my opinion actually) that "handling timezones correctly and transparently" is not a "nice to have", it's critical functionality. Mandatory XKCD reference:

[![tornadoguard](https://user-images.githubusercontent.com/316517/160885910-788d818f-c9ae-443a-acc4-f1be9e042ca4.png)](https://xkcd.com/937/)
