### ISSUE TITLE
[CAL-2387] Copy Invite Link on Teams Invite Broken

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10948]
When you go to the team invite wizard and select "copy invite link," when a user clicks on it, it throws a 500 error 

![CleanShot 2023-08-24 at 21.51.43@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6b60423c-1413-4b27-a066-d53f07af7c56/9b0d9761-6c22-44bb-ae0a-eb3c9296dc00?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82YjYwNDIzYy0xNDEzLTRiMjctYTA2Ni1kNTNmMDdhZjdjNTYvOWIwZDk3NjEtNmMyMi00NGJiLWFlMGEtZWIzYzkyOTZkYzAwIiwiaWF0IjoxNjkyOTQ5OTY5LCJleHAiOjE2OTMwMzYzNjl9.n-K6A3HVMyH9rsv3gh_gKR8dJJ434NpBzUZ5VNfthOs)

![CleanShot 2023-08-24 at 21.52.14@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/96ee60cb-98aa-428e-8610-f5662e5a4471/05847970-ab53-4872-bf07-56a8523d8541?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NmVlNjBjYi05OGFhLTQyOGUtODYxMC1mNTY2MmU1YTQ0NzEvMDU4NDc5NzAtYWI1My00ODcyLWJmMDctNTZhODUyM2Q4NTQxIiwiaWF0IjoxNjkyOTQ5OTY5LCJleHAiOjE2OTMwMzYzNjl9.1IEHWpLkNQwV35llsoDuYf4mb5IWX3S5TXuhhjQjdWc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2387](https://linear.app/calcom/issue/CAL-2387/copy-invite-link-on-teams-invite-broken)</sub>

**Comment by SomayChauhan** [comment]
i'd like to work on it

**Comment by SomayChauhan** [comment]
[Screencast from 25-08-23 02:50:38 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/2d182571-82f8-4dae-a365-855357be502f)
:thinking: works fine for me, am i missing something?

**Comment by Udit-takkar** [comment]
current implementation https://github.com/calcom/cal.com/pull/8355 requires the user to have an account and logged in to accept the team invite from "copy link" url. i would have to change our current implementation

**Comment by PeerRich** [comment]
i think this is a duplicate and has been fixed, no?

**Comment by srikary12** [comment]
#10906

**Comment by Udit-takkar** [comment]
duplicate
