### ISSUE TITLE
[Bug] Need to redirect to Event-types page after saving an event

### ISSUE THREAD

**Issue by bmprajwal** [calcom/cal.com#10947]
### Issue Summary

After creating an event type and saving it, user expects him to redirect to his event-types page.

### Steps to Reproduce

1. Go to cal.com
2. Go to Event-Types
3. Create NEW event 
4. Save the event

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
UX would be better.

### Actual Results
![redirect-issue](https://github.com/calcom/cal.com/assets/89903153/4b254279-206b-4b9a-8f9a-bde598ce96c7)

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
- 
![redirect-issue](https://github.com/calcom/cal.com/assets/89903153/6c1d69db-cad3-4493-a9a1-890e962303bd)

**Comment by PeerRich** [comment]
we dont want to redirect to event-types because people sometimes just want to save
