### ISSUE TITLE
Appointment list is not sorted correctly

### ISSUE THREAD

**Issue by hursittarcan** [calcom/cal.com#10944]
### Issue Summary

Normally all future appointments are sorted from first to last (by date).
Currently this is not the case and the appointments are sorted randomly.

### Steps to Reproduce

1. Login to cal.com
2. Go to appointments
3. See randomly sorted appointments

### Actual Results

- Appointments are sorted randomly.

### Expected Results

- Appointments should be sorted from first to last (by date).

### Technical details

- Google Chrome.

### Evidence

- I logged in to check my appointments and realized an appointment of 6PM, than 11AM, than 2PM, ...

**Comment by headshigh** [comment]
i would like to work on it

**Comment by hursittarcan** [comment]
@headshigh Hey 👋, I just checked and looks like it has been fixed.
