### ISSUE TITLE
[CAL-2622] [Web] Refactor /api/auth/signup and add E2E tests. 

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#10953]
Currently this file does a lot and its really hard to find your way through whats happening. We should refactor this and move to a more concise functional approach. 

^ Will allow us to unit test a lot of the areas too if required. 

<sub>[CAL-2622](https://linear.app/calcom/issue/CAL-2622/[web]-refactor-apiauthsignup-and-add-e2e-tests)</sub>

**Comment by sanket-reddy** [comment]
hey , I would like to work on this

**Comment by sean-brydon** [comment]
This has been done and lots of e2e tests added
