### ISSUE TITLE
[CAL-2392] Change Background on Individual and Collective Event Types

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10962]
![CleanShot 2023-08-25 at 07.32.42@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/05acec90-aa11-40a5-8660-90c220d10fb8/21ebea79-7638-4072-b530-88743d714932?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wNWFjZWM5MC1hYTExLTQwYTUtODY2MC05MGMyMjBkMTBmYjgvMjFlYmVhNzktNzYzOC00MDcyLWI1MzAtODg3NDNkNzE0OTMyIiwiaWF0IjoxNjkyOTg0ODQxLCJleHAiOjE2OTMwNzEyNDF9.HE6M8Z_eiUSgmbymuALukoel3P52DMM_TqOk6_Om7gs)

On orgs, have the ability to upload an image to be the background image for individual and collective event-types. Eventually, be able to adjust the background image per event-type, but for now, just one image for all backgrounds. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2392](https://linear.app/calcom/issue/CAL-2392/change-background-on-individual-and-collective-event-types)</sub>

**Comment by ameeetgaikwad** [comment]
Would like to do this!

**Comment by PeerRich** [comment]
this needs more spec from our product team. will likely be part of a bigger "theme" release

**Comment by davetanguay-envision** [comment]
Would love this feature since even though I have the setting "Disable Cal.com branding" disabled, it's still branded with the Cal.com image when I share my Cal.com link with clients.
