### ISSUE TITLE
[CAL-2391] Ability to Change Logo on Event Page

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10961]
This will be on organizations and the logo the organization owner sets at the org level will be applied to the event pages

![CleanShot 2023-08-25 at 07.26.55@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/624d19ae-302e-44d0-bc0e-613294778f15/78567e5b-7e78-42ca-8314-99a72bf5cf8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82MjRkMTlhZS0zMDJlLTQ0ZDAtYmMwZS02MTMyOTQ3NzhmMTUvNzg1NjdlNWItN2U3OC00MmNhLTgzMTQtOTlhNzJiZjVjZjhlIiwiaWF0IjoxNjkyOTg0NTAxLCJleHAiOjE2OTMwNzA5MDF9.-oI0xmYo6kWsHWpoxL_Yg7flzlBCedzeMcqOI4qhRtI)

![CleanShot 2023-08-25 at 07.26.32@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6f463d84-6bd9-437c-be60-04f3d4802cac/ae8deaf2-064a-4734-af07-2cbf3f1d6c88?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82ZjQ2M2Q4NC02YmQ5LTQzN2MtYmU2MC0wNGYzZDQ4MDJjYWMvYWU4ZGVhZjItMDY0YS00NzM0LWFmMDctMmNiZjNmMWQ2Yzg4IiwiaWF0IjoxNjkyOTg0NTAxLCJleHAiOjE2OTMwNzA5MDF9.mYhIgKqZglgmnTLL5gDn2W_obEtWbBqYppjSVBYGzYY)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2391](https://linear.app/calcom/issue/CAL-2391/ability-to-change-logo-on-event-page)</sub>

**Comment by shirazdole** [comment]
Add logo to individual page as well in orgs
<img width="936" alt="CleanShot 2023-08-25 at 07 29 29@2x" src="https://github.com/calcom/cal.com/assets/16177678/3d7517ed-d154-4b89-8546-cee9d0e71039">

**Comment by Subhojit-Dey1234** [comment]
Raised a PR for this issue. https://github.com/calcom/cal.com/pull/10970.
I will like to work on this issue.
