### ISSUE TITLE
Bug: Wrong Image Post In Pin Blog 

### ISSUE THREAD

**Issue by B2-krunalrana** [calcom/cal.com#10977]
###Wrong Image Post In Pin Blog INDIA IMAGE SHOUD SHOWS KASMIR AND SOME OTHER PART PLEASE FIX THIS ELSE GOV INDIA MAY TOOK ACCTION AGAINSET THIS 

### Steps to Reproduce

1. Open Main Web of cal.com
2. Go to blog section 
3. check image mention in pined blog Date: 27-08-2023 ( https://cal.com/blog/relocating-service-when-joining-cal-com )

###EVIDANCE 
![image](https://github.com/calcom/cal.com/assets/90046525/3fd81d54-a9c9-44d6-b94c-85a5bc2e07ca)

**Comment by Amitooo1** [comment]
hey @B2-krunalrana , may i know what is wrong with the image?

**Comment by ameeetgaikwad** [comment]
@Amitooo1 the map of India is wrong, in this map some of the Indian region is shown as part of pakistan.

**Comment by B2-krunalrana** [comment]
> hey @B2-krunalrana , may i know what is wrong with the image?

Kashmir is a region that has been a subject of territorial dispute between India, Pakistan, and China. The status of Kashmir is complex and has led to various conflicts and tensions between these countries.

India's official stance has been that the entire region of Jammu and Kashmir is an integral part of its territory, and it is depicted as such on Indian maps. The specific details of how Kashmir is shown on Indian government maps can vary, but generally, it is depicted as an integral part of India.

**also google about this u can Easly find that :**
**### if any site keep this kind of map in there website then gov of India may took action against them or they have right to ban that web for India region**

**Comment by PeerRich** [comment]
this is a map of all direct flights from the USA. This is the [Srinagar Airport](https://en.wikipedia.org/wiki/Srinagar_Airport)

**Comment by B2-krunalrana** [comment]
> this is a map of all direct flights from the USA. This is the [Srinagar Airport](https://en.wikipedia.org/wiki/Srinagar_Airport)

yes sir @PeerRich but still If u check  u find that this is part of India and in our website it India border shows different 

![image](https://github.com/calcom/cal.com/assets/90046525/b9aff3c5-1ffa-43ff-b7d7-c17137925f7d)

**Comment by PeerRich** [comment]
fixed
![CleanShot 2023-08-28 at 13 44 46@2x](https://github.com/calcom/cal.com/assets/8019099/5475c257-2ded-4437-ade9-bf12fc54ac2a)

**Comment by B2-krunalrana** [comment]
Thank you for responding so quickly. @PeerRich
