### ISSUE TITLE
[BUG]: Incorrect Availability Display in Event Preview

### ISSUE THREAD

**Issue by ashwintelmore** [calcom/cal.com#10979]
# Bug Report: Incorrect Availability Display in Event Preview

## Description
I encountered an issue while using the event creation feature on the platform. When a new event is created with availability selected, the preview or actual share link should display the availability as days. However, in the preview, the feature does not work as expected.

## Steps to Reproduce
1. Create a new meeting.
   ![Screenshot 1](https://github.com/calcom/cal.com/assets/67059525/e728fd72-80b0-45a7-87f2-94efeed308d6)

2. Select "Noon" as availability, making all days of the week available.
   ![Screenshot 2](https://github.com/calcom/cal.com/assets/67059525/26445868-9558-4e47-b830-052d809683d9)

3. Preview the event to observe the availability display issue.
- ![Screenshot 3](https://github.com/calcom/cal.com/assets/67059525/628c5d02-22d3-4836-96f0-3e75900466e7)

## Expected Behavior
- The preview should accurately display the selected availability as days of the week.

## Actual Behavior
- The preview only allows the selection of dates for Sundays.
- ![Screenshot 4](https://github.com/calcom/cal.com/assets/67059525/628c5d02-22d3-4836-96f0-3e75900466e7)

## Additional Information
- even i tried to change availability where time range is 9am to 5pm
![image](https://github.com/calcom/cal.com/assets/67059525/bb077712-0ba5-458b-906e-7c62a1d942e1)

- but now it working fine but time range are not working fine as it showing time range just for single shot
![image](https://github.com/calcom/cal.com/assets/67059525/1a9a4501-0931-4de9-b355-92e8eae6cf2d)

## Technical Details
- Operating System: Ubuntu
- Browser: Firefox

## Evidence
As provided in the screenshots above.

Please address this issue as it affects the accurate representation of event availability in the preview, impacting the overall user experience.

Thank you for your attention to this matter.

**Comment by yatharth1706** [comment]
Hi there, would love to work on its fix.

**Comment by srikary12** [comment]
The issue is not reproducible.

![image](https://github.com/calcom/cal.com/assets/121927567/75583452-421d-40e2-b183-581116f5a8ce)

**Comment by ashwintelmore** [comment]
issues is solved i think
