### ISSUE TITLE
embed: skeleton instead of loading spinner

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10988]
instead of this: ![CleanShot 2023-08-28 at 14 23 45@2x](https://github.com/calcom/cal.com/assets/8019099/413558eb-bc39-4268-91f7-431b0b036ebe)

can we add a skeleton that sort of looks like the embed:

![CleanShot 2023-08-28 at 14 29 50@2x](https://github.com/calcom/cal.com/assets/8019099/a684733c-8ff5-450a-9dc1-9e38591e1eae)

**Comment by hrithiksinngh** [comment]
what's the bounty for this?

**Comment by MeenuyD** [comment]
Hello @PeerRich I see you assigned itself I would like to work on this issue. This feature I embed in one of the projects this feature is known as the shimmer UI.

**Comment by PeerRich** [comment]
feel free to raise a PR yourself. btw. there is a Skeleton Component in our project already

**Comment by PeerRich** [comment]
if not, i will raise a PR this week

**Comment by MeenuyD** [comment]
Ok, thanks @PeerRich I will try.

**Comment by MeenuyD** [comment]
Can I use it in the inbuilt css Library?

**Comment by ameeetgaikwad** [comment]
@PeerRich which page is this?

**Comment by ameeetgaikwad** [comment]
already there is skeleton: 
![image](https://github.com/calcom/cal.com/assets/76063569/5fbfa097-d8cc-4896-b594-71df08a2f554)

**Comment by ameeetgaikwad** [comment]
@PeerRich why is my local development environment showing me this?
![image](https://github.com/calcom/cal.com/assets/76063569/830b3745-785c-4662-8c9f-c81a9a7bfe08)

**Comment by PeerRich** [comment]
dont worry i am working on this already
