### ISSUE TITLE
[CAL-3881] as team owner/admin, be able to reject "requires confirmation" team events

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#10990]
i am the owner/admin of "Hiring Call" round robin team event. 

the event type has "requires confirmation"

right now, only Bailey, the person who got selected for round robin, can confirm or reject.

better: every admin/owner can confirm/reject "requires confirmation" bookings

![image](https://github.com/calcom/cal.com/assets/8019099/62c67b74-fdaa-44a0-8826-1e09e7df906f)

<sub>[CAL-3881](https://linear.app/calcom/issue/CAL-3881/as-team-owneradmin-be-able-to-reject-requires-confirmation-team-events)</sub>

**Comment by shivam969619** [comment]
can i take this issue

**Comment by ShivaKodes** [comment]
I can solve this. can you assign me?

**Comment by Taha-1005** [comment]
Hi @PeerRich , how can I reproduce this error?

**Comment by PeerRich** [comment]
hmmm i think the owner/admin of teams only

**Comment by SomayChauhan** [comment]
attempt [#11045](https://github.com/calcom/cal.com/pull/11045)
