### ISSUE TITLE
[CAL-2393] Team Invite Broken: Cannot Invite Userrnames only Emails

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10993]
When you try to invite a user to a team using "username," it says this user cannot be invited because  email cannot be found. We should be able to invite via username AND email 

![CleanShot 2023-08-28 at 09.21.40@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/959b4a7c-f227-49de-aac8-dd36dd86cf8f/80920ed9-b25e-4a64-9a4e-c70c1feeb1c4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NTliNGE3Yy1mMjI3LTQ5ZGUtYWFjOC1kZDM2ZGQ4NmNmOGYvODA5MjBlZDktYjI1ZS00YTY0LTlhNGUtYzcwYzFmZWViMWM0IiwiaWF0IjoxNjkzMjUwODM1LCJleHAiOjE2OTMzMzcyMzV9.JSEHzTi77imkgAHTWfNK4EMGWh0aa4tZ3Ml4tNn89uM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2393](https://linear.app/calcom/issue/CAL-2393/team-invite-broken-cannot-invite-userrnames-only-emails)</sub>

**Comment by Miranda-Ryan** [comment]
Hi, this is my first open-source contribution.
Kindly let me know if there are any issues or if you would like me to refactor anything.
