### ISSUE TITLE
[CAL-2394] Bug: Double team creation

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#11001]
There has been reports that teams get duplicated when creating them. We need to validate double click on input doesn't create team twice.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2394](https://linear.app/calcom/issue/CAL-2394/bug-double-team-creation)</sub>

**Comment by arungk703** [comment]
Can you explain it briefly.

**Comment by alannnc** [comment]
@arungk703 Try to create a team inside settings page, follow all the instructions but try to make the input that send the post /mutation to create team to execute twice or more by clicking the submit button many times.

**Comment by alannnc** [comment]
Tried both local and production environment with no luck trying to obtain duplicated teams. Please re open if it happens again.
