### ISSUE TITLE
RFC: Plan some kind of tests for EventTypeAppCardInterface and AppCard

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11005]
[EventTypeAppCardInterface](https://github.com/calcom/cal.com/blob/109292352373b0bdfd954a69451946c9602922cf/packages/app-store/_components/EventTypeAppCardInterface.tsx#L10) and [AppCard](https://github.com/calcom/cal.com/blob/109292352373b0bdfd954a69451946c9602922cf/packages/app-store/_components/AppCard.tsx#L12) are common components used by all event type apps.

We need some kind of tests for this. Idea is to quickly do changes in them without needing to test all the apps that are using it. Goal is to be able to merge [PRs like this](10781) with peace of mind
These are the apps using `EventTypeAppCardInterface` at the moment
<img width="737" alt="Screenshot 2023-08-29 at 11 03 24 AM" src="https://github.com/calcom/cal.com/assets/1780212/45f17b11-23f1-427a-80b5-6ff90be4b3aa">

Initially these tests can be component tests(like [this]( https://github.com/calcom/cal.com/pull/10705)) so that they are super quick to execute and let's see if we need to add e2e.

**Comment by memoryStack** [comment]
@hariombalhara is it still open ? I have some idea about test-cases for this component but i see that a similar [issue](https://github.com/calcom/cal.com/issues/11370) has been marked as closed.

**Comment by keithwillcode** [comment]
This was fixed as part of #11370
