### ISSUE TITLE
tablet menu not centered

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11017]
![CleanShot 2023-08-29 at 23 50 04@2x](https://github.com/calcom/cal.com/assets/8019099/432238be-b6ff-4b40-9991-77b5eab4f6ef)

![CleanShot 2023-08-29 at 23 50 35@2x](https://github.com/calcom/cal.com/assets/8019099/a440ca1f-be40-420e-be2c-d372c9342bd8)

**Comment by atharvam2004** [comment]
I am working on this issue
