### ISSUE TITLE
[CAL-2903] Transcribe and summarize video meetings using AI

### ISSUE THREAD

**Issue by aar2dee2** [calcom/cal.com#11013]
### Is your proposal related to a problem?

I use Cal to schedule user interviews for [Telborg](https://telborg.com), then take handwritten notes during the video meeting and rewrite those notes in Slab. 

### Describe the solution you'd like

I'd love a workflow where I can:
1. request consent to record automatically when meeting starts
2. transcribe the conversation using a speech-to-text model such as [Whisper](https://platform.openai.com/docs/models/whisper)
3. Summarise the conversation using GPT 3.5/4 /other LLM
4. Send transcript + summary to Notion/[Slab](https://slab.com/)/Google Docs/other wiki provider
5. (Optional) send follow-up email to meeting attendees summarising the conversation

### Describe alternatives you've considered

I currently use Google Meet for the meetings. A Zapier workflow with access to Google Drive might be possible but I would have to
1. remember to ask for consent and enable recording
2. setup zapier + google drive to access recording
3. setup zapier + openai to transcribe and summarise
4. setup zapier  + notion/slab/google docs to store transcript and summary

The whole setup can be simplified by 
1. using [daily.co's transcription service](https://docs.daily.co/reference/rn-daily-js/instance-methods/start-transcription#main) - this has native support for [Whisper](https://developers.deepgram.com/docs/model#whisper) 
2. building Cal integrations for the wiki providers we want to support

### Additional context

I love Loom's AI features - using AI to transcribe the recording, generate a summary, generate a relevant title. And all of this happens nearly real-time.

Happy to work on this independently or with other contributors!

### Requirement/Document

<sub>[CAL-2903](https://linear.app/calcom/issue/CAL-2903/transcribe-and-summarize-video-meetings-using-ai)</sub>

**Comment by goesbyabhi** [comment]
So you want a browser extension of cal.com to transcribe meets and summarize them?

**Comment by Akhilbisht798** [comment]
This is a pretty big change and honestly i think this will be helpful for the users.
I am all for it.

**Comment by PeerRich** [comment]
yes the daily.co transcription service is perfect for this

**Comment by PeerRich** [comment]
we can send the call summary by email afterwards to all attendees

**Comment by aar2dee2** [comment]
> yes the daily.co transcription service is perfect for this

great. I'll get started on this.

**Comment by aar2dee2** [comment]
> So you want a browser extension of cal.com to transcribe meets and summarize them?

is there a browser extension that does this?

**Comment by Akhilbisht798** [comment]
@aar2dee2, Hey are you working on this issue.

**Comment by aar2dee2** [comment]
Hey @Akhilbisht798,
yea I am
