### ISSUE TITLE
Cannot create more than one in-person location

### ISSUE THREAD

**Issue by sbw78** [calcom/cal.com#1102]
### Issue Summary

I can add a single "Link or In-person meeting" location option, but when I go to add another the previous one is just modified.

### Steps to Reproduce

1. Go to event details (edit event)
2. Select 'Link or In-person meeting' and add an address/place/link
3. Click '+ Add a location' and select 'Link or In-person meeting' again.

    The previous address/place/link entered will be filled in. Modifying this will change the already existing location and will not add a second option.

* Note: I was able to reproduce this same bug in Safari v15.0 with these steps

<https://user-images.githubusercontent.com/57336312/139726204-a8cf846d-2dc5-44f3-b0c2-025f5e136780.mov>

### Technical details

- Browser version: Firefox 93 on OS X 10.15
- Node.js v16.8.0
- Also tried disabling ad/script blockers, but this did not make a difference.

Thank you!

**Comment by ConnorGargano** [comment]
Hi there,
I will get this raised to the engineering team and see if we can find a solution.
-Thanks, Connor

**Comment by sean-brydon** [comment]
Closing - This was fixed in https://github.com/calcom/cal.com/pull/2161/
