### ISSUE TITLE
Late response without Loading animations

### ISSUE THREAD

**Issue by GautamTirumala** [calcom/cal.com#11022]
### Issue Summary

During my signUp the page was taking some time to load without any loading animations due to which the page is not responding 
(I clicked each button 2-3 times thinking that my mouse is not working properly)

### Steps to Reproduce

1. Open Cal.com
2. Click on any button then go to Teams and Apps
3. Observe the lag in opening 

### Actual Results

- Now the pages are taking time to load (when changing the routes Teams and Apps and during SignUp)

### Expected Results

- Either we should show the user some loading animation or something else so that user is not hanging

**Comment by abdulrehmanjaved-1** [comment]
Handle it to me.

**Comment by PeerRich** [comment]
this has been fixed, sorry about that!

**Comment by abdulrehmanjaved-1** [comment]
Hey Peer, Got it and thanks for this amazing application.
I am going to follow you and hope that you follow me back.
Thanks
