### ISSUE TITLE
Add rescheduleReason and cancellationReason to Booking PATCH API

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#11028]
### Is your proposal related to a problem?

1. Reschedule Booking API does not currently allow rescheduleReason (unlike UI), and 
2. Cancellation Booking API does not currently allow cancellationReason.
3. When rescheduling a booking event, if it is possible to add guests, it would be great.

### Describe the solution you'd like

> when rescheduling booking event, we need a way to
> - edit(add/remove) guests, maybe like in POST requests with property similar to that:     "responses": {
>        "guests": ["e1@c.com", "e2@c.com", "e3@c.com"]
>     },
> - add a rescheduleReason
> and for cancellation booking,
> - add a canellationReason
> and all these properties being reflected in the get reqeusts.

**Comment by SauravChanda** [comment]
Please assign this to me

**Comment by SauravChanda** [comment]
@alishaz-polymath The bookings/{id}/cancel does have a reason field, from what I can see.

**Comment by piyush09-05** [comment]
working on it.

**Comment by alishaz-polymath** [comment]
Not on the roadmap for now
