### ISSUE TITLE
[CAL-2900] RFC: handoff redirection (OOO, Vacation)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11031]
same as email, where you can redirect incoming emails to a new inbox for a predefined period, we wanna auto-redirect cal.com links to someone elses link who is temporarily replacing you

scope of how this will look like will follow

open questions:
- how will round robin/collective be affected?

<sub>[CAL-2900](https://linear.app/calcom/issue/CAL-2900/rfc-handoff-redirection-ooo-vacation)</sub>

**Comment by PeerRich** [comment]
- prevent circle loops (i.e. cal.com/peer redirects to bailey, bailey to peer, etc)

**Comment by PeerRich** [comment]
maybe throw a small hint that a person is OOO (somewhere in the new persons link)

goal: prevent people being confused why they end up with bailey but they entered peers link

**Comment by itsmingjie** [comment]
a weird case would be rescheduling. sayI book a call with A on 9/5, but A is out of office between 9/1-9/10. so my call gets redirected to B instead. then I want to reschedule to 9/15 instead from my end. who then is responsible for deciding whether the call stays on A's calendar or B's?

**Comment by PeerRich** [comment]
i agree rescheduling could get messy. maybe for the sake of simplicity we dont do redirects for reschedules? most of the time, rescheduling causes some human conversations anyway. also, if the person is OOO the person rescheduling cant book a time where that person is not available anyway

**Comment by PeerRich** [comment]
we should extend this menu point:
![image](https://github.com/calcom/cal.com/assets/8019099/cde4de89-6185-4918-b999-2f6ff8af90c5)

and link to 

https://app.cal.com/settings/my-account/ooo

like here:

https://github.com/calcom/cal.com/issues/8018

**Comment by PeerRich** [comment]
the person going OOO should input the email address of a cal.com user (so we support orgs too) and not the username.

i.e. the input should be:

"What is the email of the person temporally replacing you?": bailey@cal.com

we should also maybe consider adding a date range so people can say from when to when. maybe get some inspiration of google mail clients

--

should we make this opt-in where we send an email to bailey@cal.com to confirm the redirect?

if active, we should have a TopBanner with "You are currently OOO and your links are redirecting to {username}."
