### ISSUE TITLE
Bug : Google signup not work 

### ISSUE THREAD

**Issue by mandalpawan** [calcom/cal.com#11035]
Google signup not work

How to Reproduce
Step:

1. Without login go to pricing.
2. Select any plan.
3. There is signup option if we try to login with google signup.
4. Fail to signup
Expected: Got a popup box for google signup box. where user can easily signup.

![image](https://github.com/calcom/cal.com/assets/42595868/c42618df-eb99-4ad5-8ec6-2c6c6b6cdf0c)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue @keithwillcode

**Comment by punyeeet** [comment]
You can see that it wants a username. I think it is made that way, fill in username -> Google Signup

**Comment by mandalpawan** [comment]
@punyeeet username always fetch from google auth not required to pass username externally. Google auth automatically take care of all of thing.

**Comment by sciencenawaaz** [comment]
> You can see that it wants a username. I think it is made that way, fill in username -> Google Signup

No you don't need to fill the username in that input box..the actual problem the person above is stating is cause of the Google external authentication they are not getting the pop up when you click on sign in using Google you then have to type your Google credentials there .

**Comment by sciencenawaaz** [comment]
@mandalpawan  I think it's because they aren't using google sign-in API script in the header of _app.js .

```

<Head>
        {/* Include Google Sign-In API script */}
        <script src="https://apis.google.com/js/platform.js" async defer></script>
      </Head>

```

**Comment by mandalpawan** [comment]
@sciencenawaaz  okay i will check or you can also create PR for that's.

**Comment by sciencenawaaz** [comment]
> @sciencenawaaz  okay i will check or you can also create PR for that's.

Will have to fork and run it locally, make the changes and see if it actually works and doesn't break anything before I even think of opening a PR. It's late here will check it out tomorrow if no-one has solved it by then and I am able to run the repository locally and test my solution.

**Comment by PeerRich** [comment]
@sean-brydon is working on an entire new signup page, so I think we can close this.

you need to enter a username first

**Comment by ali55ahmad6677** [comment]
https://github.com/calcom/cal.com/issues/11035

**Comment by ali55ahmad6677** [comment]
> Thank you for opening your first issue, one of our team members will review it as soon as it possible. ❤️🎉

**Comment by TUMMENE** [comment]
https://github.com/calcom/cal.com
