### ISSUE TITLE
bug : Heading size too big

### ISSUE THREAD

**Issue by Rohit-Dumka** [calcom/cal.com#11030]
### Issue Summary
Heading size too big it should be smaller so that it can be easy to read and user friendly . 
### Steps to Reproduce

1. When you reaches the Home page
2. Look at the heading named : "Scheduling infrastructure for everyone. " it's size is soo big

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Evidence
![image](https://github.com/calcom/cal.com/assets/96404582/7c4bea30-92db-4ec2-93d1-2243e4441212)

**Comment by Tostiffent** [comment]
I'm willing to work on this

**Comment by theunhackable** [comment]
@Tostiffent u can it's a quick win. Create a pr as soon as possible else someone will do that.

**Comment by RahulKhati9458** [comment]
I want to work on this. Can I?

**Comment by theunhackable** [comment]
First PR wins

**Comment by pateldivyesh1323** [comment]
I think that was made that way. Let a team member first review this issue.

**Comment by PeerRich** [comment]
perfectly fine size, this is a design choice

**Comment by PeerRich** [comment]
also, this is the website repo, not app repo

**Comment by Rohit-Dumka** [comment]
Sorry my bad +__+
