### ISSUE TITLE
Page not Found in Round Robin Team Payment

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#11043]
### Issue Summary

In the Round Robin Team Event type with Stripe and Confirmation Required is enabled. The App returns a 404 when booking is submitted.

### Steps to Reproduce

1. Enable Stripe  
2. Create an event-type with the settings mentioned in summary.
3. Book an event.

[Video](https://youtu.be/kaYvNgkYFS0)

**Comment by gnakul2001** [comment]
@PeerRich please assign me with this problem.
