### ISSUE TITLE
[CAL-2621] org.cal.com/support route clashing with app.cal.com/support route

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11055]
if you make an org team called "support" which is very common, you'll end up with a broken link that goes to app.cal.com/support

same is true for other names that clash with /pages, such as "event-types" or "bookings" -- tho these names are less likely to happen (still possible)

https://github.com/calcom/cal.com/assets/8019099/7d31c5dd-ac8a-4bb5-a41e-89bfcb63c95f

app.cal.com/support has to be different than org.cal.com/support

<sub>[CAL-2621](https://linear.app/calcom/issue/CAL-2621/orgcalcomsupport-route-clashing-with-appcalcomsupport-route)</sub>

**Comment by SaiDevaHarshaR** [comment]
Rather than utilizing app.cal.com/support, I believe we can opt for app.cal.com/team/support.

**Comment by hariombalhara** [comment]
This is fixed as part of [https://github.com/calcom/cal.com/pull/11080](https://github.com/calcom/cal.com/pull/11080)
