### ISSUE TITLE
Weekly view does not load

### ISSUE THREAD

**Issue by arjunattam** [calcom/cal.com#11066]
### Issue Summary

My booking page is configured to load the weekly view by default, but it does not work.

<img width="1624" alt="Screenshot 2023-09-01 at 10 57 06 AM" src="https://github.com/calcom/cal.com/assets/284612/305112cc-ad19-4ef9-8c99-53fc5c4093f1">

### Steps to Reproduce

1. Navigate to https://cal.com/arjunattam/30 
2. See issue

Or if you'd like to repro my steps in your account

1. Edit appearance config for your booking page to load weekly view by default
2. Navigate to the booking page
3. See issue

### Actual Results

The calendar does not render.

### Expected Results

The calendar should render.

### Technical details

- Chrome: Version 116.0.5845.140 (Official Build) (arm64)

**Comment by romiljain5** [comment]
It is working, Can u check again and close the issue if not valid

**Comment by arjunattam** [comment]
The weekly view is working for me now, thanks. Is there a commit that has the fix? If not, the issue will potentially re-appear? The issue is "valid" as shown in the console log screenshot.
