### ISSUE TITLE
Feature to not show "x seats available" 

### ISSUE THREAD

**Issue by reachkrishnaraj** [calcom/cal.com#11065]
### Is your proposal related to a problem?

- Displaying number of seats when seats feature is enabled handicaps certain markerting technique like FOMO.
- It also gives away the business's internal insight to competitors.

(Write your answer here.)

### Describe the solution you'd like

- Provide a flag/preference to not show the "x seats available" caption/copy. Screenshot below

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

<img width="259" alt="image" src="https://github.com/calcom/cal.com/assets/5241226/14f68f5c-92ee-4e92-b4ef-71e33d6e7977">

**Comment by shubhams167** [comment]
Hey @reachkrishnaraj, I like this idea. I hope this feature is approved.
