### ISSUE TITLE
Users can book appointments that are not within the availability reach

### ISSUE THREAD

**Issue by hursittarcan** [calcom/cal.com#11070]
### Issue Summary
My availability states from 09:00 - 19:30. But I've had instances where users booked appointments that exceeded 19:30, like from 20:00-.... How can this happen? 

I've also had instances where available slots are not showing up...

**Comment by shawnvanderveer** [comment]
> ### Issue Summary
> My availability states from 09:00 - 19:30. But I've had instances where users booked appointments that exceeded 19:30, like from 20:00-.... How can this happen?
> 
> I've also had instances where available slots are not showing up...

Check if you have a general availability and different form availability.

**Comment by sagarmohit22** [comment]
please assign the issue to me
