### ISSUE TITLE
Team event types have no padding at the bottom.

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11077]
![CleanShot 2023-09-01 at 14 22 31](https://github.com/calcom/cal.com/assets/55134778/ee2ca11d-f466-4b81-b05b-c6b793dae835)

Team event type list at /event-types should have padding separating each list item  (This value should be the same as the event-types for your user above)

**Comment by MeenuyD** [comment]
On which page

**Comment by sean-brydon** [comment]
> On which page

This is on the /event-types page 
![Sizzy-MacBook Air app cal local 01Sep 14 52](https://github.com/calcom/cal.com/assets/55134778/855d5621-d036-4690-b1e6-59f096e8a6c4)

**Comment by MeenuyD** [comment]
but I can not see

**Comment by Judis07** [comment]
I believe that using the margin property instead of padding is the more appropriate choice in this context.

**Comment by pateldivyesh1323** [comment]
I tried to reproduce it. I saw it for just a split second.

**Comment by sean-brydon** [comment]
> I believe that using the margin property instead of padding is the more appropriate choice in this context.

Correct - ideally we use gap or space-y here

**Comment by NidhiSharma63** [comment]
I don't see this UI. could anyone help me!
![image](https://github.com/calcom/cal.com/assets/99652555/2f7b9eb7-2340-47b0-b44d-db0405b95d1e)

**Comment by MeenuyD** [comment]
> I don't see this UI. could anyone help me? ![image](https://user-images.githubusercontent.com/99652555/265048837-2f7b9eb7-2340-47b0-b44d-db0405b95d1e.png)

I also can not see
