### ISSUE TITLE
setup Embed Checkly tests for deployment

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11083]
inside checkly, check for working embed and make it required for tagged deployments

**Comment by zomars** [comment]
related to #11090 

Done! 

![image](https://github.com/calcom/cal.com/assets/3504472/f5cc05a1-4a5a-43c4-bc70-703ea2671924)

![image](https://github.com/calcom/cal.com/assets/3504472/e42a7fe1-ced7-4e8d-a7e4-712ada5e45f7)
