### ISSUE TITLE
Require an 'Email' placeholder in the 'Add guest' field."

### ISSUE THREAD

**Issue by shreyash1080** [calcom/cal.com#11094]
Require an 'Email' placeholder in the 'Add guest' field."

When I click on "Add guest," it's not clear what information to input, whether it's a name or an email. However, when I hover over the cross mark, it displays "Remove email," indicating that an email should be added. The placeholder in the "Add guest" text field should include the label "Email."

![image](https://github.com/calcom/cal.com/assets/76811518/e40acdbe-658d-42b5-9d30-af084a5be7ec)

Answer:
Simply add the placeholder "Email" to the "Add Guest" field input.

**Comment by lrmaxx** [comment]
Fix Issue #11094

**Comment by ShivamJha2436** [comment]
Okay , I will fix this issue
