### ISSUE TITLE
[BUG]: In phone width that navigation buttons will be scrolling its have alredy adjusted

### ISSUE THREAD

**Issue by omkarvilasmote** [calcom/cal.com#11108]
##Titile
In the small width that navigation buttons will be scrolling

### Issue Summary
some time some phones width that no scrolling features and that some phones we scolling that perticular buttons on nevigation we have a also spaces but its scrolling

### Steps to Reproduce
1.Open in phone
2.Open the cal.com
3. Clicked on... 3 dots navigation
4. then check to scoll that buttons

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

https://github.com/calcom/cal.com/assets/109019862/1fb2e9b5-de15-4564-85c3-7e7cf99ad60f

### Actual Results
we no need there scrolling if alredy have space

**Comment by PeerRich** [comment]
no an issue and planned implementation
