### ISSUE TITLE
Add placeholder design to the dates to override panel.

### ISSUE THREAD

**Issue by sheoranabhishek** [calcom/cal.com#11106]
### Is your proposal related to a problem?

The panel where we add overrides for the dates in the available booking schedule, we see this empty blank box , we need a placeholder for this space or else the user might feel this is a UI bug unless a date is selected. 

<img width="800" alt="image" src="https://github.com/calcom/cal.com/assets/53663443/7470dd19-a87b-48ee-b3c8-a57275af8838">

### Describe the solution you'd like

The modal could look something like this.
<img width="800" alt="image" src="https://github.com/calcom/cal.com/assets/53663443/3bb65c41-73e9-4331-ac34-d6f0b644f222">

**Comment by sheoranabhishek** [comment]
I would like to contribute to this.

**Comment by MaryamArif7** [comment]
i want to try this / #11106
