### ISSUE TITLE
There Should be a Loading icon when click on button events

### ISSUE THREAD

**Issue by PratyushSawan** [calcom/cal.com#11113]
### Is your proposal related to a problem?

When I am onboarding on the app. Every Time I click the Next or Continue button I am confused is that clicked or not. Because there is no loading effect or any loader showing after clicking on the button.

### Describe the solution you'd like

There should be a loader icon after clicking on the buttons.

### Describe alternatives you've considered

We can also disable the button after click them once.

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by MeenuyD** [comment]
Can you please share the video

**Comment by DevFaizann** [comment]
kindly show steps to reproduce the issue

**Comment by KSSaiTeja** [comment]
i would like work on this issue.. please assign me this issue... i am trying to contribute many issues, but everytime they're assigning to others. Atleast please assign me this issue..

**Comment by PeerRich** [comment]
which button do you refer to? can you show a  video? Most of our buttons have a disabled loading state after clicking

**Comment by gracebir** [comment]
@PratyushSawan could you please share a video that replicates this issue please?

**Comment by FaisalAI541** [comment]
@PratyushSawan Please share the **Screen Shot** or the **Video** of your issue.

**Comment by chakricherala** [comment]
@PeerRich This issue can be seen when signing up on cal.com. you can find it on the Welcome to cal.com page in Step 3.

**Comment by PratyushSawan** [comment]
Hi @gracebir @FaisalAI541 @MeenuyD ,

Here are the screens where you can see the bug. I am attaching a video file please check it.


https://github.com/calcom/cal.com/assets/40737575/54e54e77-ec49-4577-9da6-8667ffde3dc8

**Comment by Ashish15678** [comment]
I believe i can create a Loader , and I am new to contributions too , please assign me this issue :-).

**Comment by keithwillcode** [comment]
@Ashish15678 No need to assign. Feel free to open and link a PR to fix the issue and we'll review!

**Comment by Ashish15678** [comment]
> @Ashish15678 No need to assign. Feel free to open and link a PR to fix the issue and we'll review!

Thank you so much for replying , if you could tell , do i need to apply a text as "processing" some icon or what exactly is expected , Then it would be awesome .
Thank you.

**Comment by KSSaiTeja** [comment]
i want to work on this.. can i proceed and raise a PR for this...?

**Comment by nick2432** [comment]
i want to work on this.

**Comment by ashishsurya** [comment]
@PeerRich I have fixed the issue, take a look at this #11624
