### ISSUE TITLE
Issue/Suggestion: "Inconsistent Uppercase Usage"

### ISSUE THREAD

**Issue by Roshanbhadauriya** [calcom/cal.com#11115]
Issue/Suggestion: "Inconsistent Uppercase Usage"

### Issue Summary

 In some parts, the words are not in uppercase where they should be.
 I suggest that avatar should be Avatar. and Connect your calendar should be Connect your  Calendar.

### Evidence

![Screenshot (174)](https://github.com/calcom/cal.com/assets/75900678/69857bfe-bd43-4232-95dc-d787de59575b)
![Screenshot (175)](https://github.com/calcom/cal.com/assets/75900678/ddf99bd5-2233-4cf5-9a73-69487f602905)

**Comment by sayanmondal31** [comment]
I would like to contribute / #11115

**Comment by PeerRich** [comment]
i think we should keep normal english: "Connect your calendar"

**Comment by ciaranha** [comment]
The rule for the Cal.com app is sentence case.
