### ISSUE TITLE
Reformat the LOCATION option in Event Types

### ISSUE THREAD

**Issue by imsoumya18** [calcom/cal.com#11122]
### Issue Summary

While editing an event type, there is an option `Location` at the bottom.
![1](https://github.com/calcom/cal.com/assets/50456734/22257ead-0342-4fe3-9d0e-a27d25da6df0)
1. When clicked on that, it is actually to choose whether to meet in-person (for which, the term "Location" is suitable) or to choose on which app to schedule a meeting (for which, the term "Platform"/"App" is suitable).
2. Also, there is a pencil icon, as if there is an option to edit/write. Even after clicking that a pop-up appears which is nothing but, a drop-down menu to choose the platform. The pencil/edit button is just an unnecessary extra barrier step, which can be resolved if we put the drop-down at the edit option itself.
![2](https://github.com/calcom/cal.com/assets/50456734/2f34185c-dcf1-401f-b060-e87452b4b463)

### Steps to Reproduce

1. Visit the event types page.
4. Click on the `Location` option at the bottom.
5. You can see the bugs mentioned above.

### Actual Results

1. `Location` term is not suitable for both apps and in-person meetings.
2. The `edit/pencil` icon is an unnecessary step.

### Expected Results

1. Instead of `Location` make it `App/Location` or any other suitable term, feedbacks are welcome.
2. Remove the edit option and put the dropdown in the edit option itself.

### Evidence

**(I have attached screenshots above)**

**Comment by PeerRich** [comment]
@ciaranha you said you wanted to eliminate the dialog alltogether, do you have designs?

**Comment by ciaranha** [comment]
Yes we have an existing issue here: https://github.com/calcom/cal.com/issues/7223

And designs here: https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=2463%3A143103&mode=dev
