### ISSUE TITLE
Add Discord as messaging app

### ISSUE THREAD

**Issue by imsoumya18** [calcom/cal.com#11121]
### Is your proposal related to a problem?

While adding messaging apps, there are only 3 apps available: WhatsApp, Telegram & Signal. WhatsApp maybe convenient but, I think like me many would like to prefer Discord as a messaging app. It would be great if Discord could be added.

### Describe the solution you'd like

Add Discord as a messaging app.

### Describe alternatives you've considered

Add Discord as a messaging app.

### Additional context

(Write your answer here.)

### Requirement/Document

![Screenshot from 2023-09-04 08-53-11](https://github.com/calcom/cal.com/assets/50456734/b6e7b25c-a062-469c-87a4-ca90cfe760a8)

**Comment by PeerRich** [comment]
discord is currently a conferencing app: https://app.cal.com/apps/discord

**Comment by imsoumya18** [comment]
Got it. Thanks for the clarification
