### ISSUE TITLE
Improvement: Enhance 'Add a location' Functionality and Provide Duplicate Location Feedback

### ISSUE THREAD

**Issue by DevFaizann** [calcom/cal.com#11126]
### Is your proposal related to a problem?

**Yes.**

The current behavior of the "Add a location" functionality on the "Event Setup" page can be confusing for users. When clicking the "Add a location" button, a pop-up with the title "Edit location" and a button labeled "Update" appears. This behavior doesn't align with the user's intention to add a new location. Additionally, there is no feedback provided when a user attempts to add a location that already exists.

### Describe the solution you'd like

I propose the following changes:

1. **Change the Pop-up Title**: When a user clicks the "Add a location" button in the form, the pop-up title should be changed from "Edit location" to "Add location." This modification will make it clear that the user is adding a new location.
2. **Update Button Text**: Within the pop-up, change the text of the button from "Update" to "Add." This alteration corresponds to the user's intention to add a location.
3. **Toast Message for Duplicate Location**: If a user attempts to add a location that already exists, display a toast message indicating that the location has been previously added. This feedback will enhance the user experience and prevent data redundancy.

### Describe alternatives you've considered

I have not considered any alternatives at this time. The proposed changes aim to align the user interface with the user's intention, making the process more intuitive, and provide helpful feedback in case of duplicate locations.

### Additional context

This issue is related to the "Event Setup" page on the cal.com platform. The current behavior can be confusing for users, as the pop-up suggests editing rather than adding a location. Implementing these changes and providing a toast message for duplicate locations will improve the user experience.

### Steps to Reproduce

1. Navigate to the "Event Setup" page on the cal.com platform.
2. Click the "Add a location" button.
3. Observe the pop-up title and button text.
4. Attempt to add a location that already exists (if applicable). The pop up will just close with no feedback message or a toast message.

### Requirement/Document

![image](https://github.com/calcom/cal.com/assets/126244804/59e91324-5ab5-4764-b934-b582d451361a)
Click on Add a location to see this pop up: 
![image](https://github.com/calcom/cal.com/assets/126244804/da6e4e5d-400d-4297-adab-c9057d751636)

**Comment by gracebir** [comment]
I will work in this @PeerRich

**Comment by PeerRich** [comment]
this will be solved differently! we are redesigning the whole location component!

here is the new designs: https://github.com/calcom/cal.com/issues/11122#issuecomment-1704968114
