### ISSUE TITLE
bug: On team members page tool-tip not visible if multiple calendars are connected.

### ISSUE THREAD

**Issue by abhijeetsingh-22** [calcom/cal.com#11120]
### Issue Summary
After the changes made by #11048 and #11040 . Now if a member have connected more than one calendar (any calendar)  then only one of them shows the tooltip with the email ID. 

### Steps to Reproduce

1. Create a team
2. Connect two or more calendars from one of the team member
3. Open the team member page from the owner/admin account. 
Only one of the connected calendars will show the tooltip.

### Actual Results

- Only one of the connected calendars is showing tooltip 

### Expected Results

- All the connected calendar should show the email Id in tooltip

### Evidence
In the following sceenshots it can be seen that out of 3 connected calendars only 1 is showing the email tooltip

![Screenshot from 2023-09-04 00-44-55](https://github.com/calcom/cal.com/assets/55000107/c717cd82-e574-4457-b3fa-5f82a1bd32a2)

![Screenshot from 2023-09-04 00-45-07](https://github.com/calcom/cal.com/assets/55000107/a76931e5-3ce2-497c-b1a6-7d800c0c0401)

![Screenshot from 2023-09-04 00-45-15](https://github.com/calcom/cal.com/assets/55000107/4a39755c-1afd-42e5-aa76-2b6ecc00c3cd)

**Comment by srikary12** [comment]
Found the issue, the external id is null for other calendars. The TRPC query is returning null. 

Not sure how to proceed. Please help.

<img width="521" alt="Screenshot 2023-09-07 at 18 48 20" src="https://github.com/calcom/cal.com/assets/121927567/2f1aaf09-8429-4989-97a3-bb3a128eb27a">
<img width="521" alt="Screenshot 2023-09-07 at 18 50 35" src="https://github.com/calcom/cal.com/assets/121927567/e4112ae5-803d-4219-b9a5-b4311a614e9d">

**Comment by asadath1395** [comment]
We no longer show installed apps besides name, it was changed in this PR https://github.com/calcom/cal.com/pull/15344. So we can close this issue i believe

cc @PeerRich @keithwillcode
