### ISSUE TITLE
[CAL-2404] getSchedule called twice on booking page

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#11138]
Due to recent changes getSchedule get called twice on booking page, we need to investigate further down.

related changes to have in mind: [https://github.com/calcom/cal.com/pull/9815](https://github.com/calcom/cal.com/pull/9815)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2404](https://linear.app/calcom/issue/CAL-2404/getschedule-called-twice-on-booking-page)</sub>

**Comment by FaizAdhikari** [comment]
where is the booking component/js file can you please help , I am a beginner and I want to try this
