### ISSUE TITLE
Loading calendar for large round robin is slow

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#11134]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When having round robins consisting of lots of users, we simply run too many queries and the performance is heavily degraded. We've talked about having a first version to fix this that loads availability for 10 users in the round robin upon page load. 

If the user who is doing the booking cannot find a slot that works for them, they click a "Show more" button and we load availability for 10 more users in the round robin. The user has the option to continue loading more availability until all users' availability is shown.

### Steps to Reproduce

1. Create a round robin event with lots of users (e.g. 50)
2. Load the calendar for that round robin

### Actual Results

- It's taking around 15 seconds to load the availability for 50 people

### Expected Results

- We should be able to load a round robin calendar for 10 users at a time in under a couple of seconds.

**Comment by zomars** [comment]
I see this as a two part problem. First, I think we should create an optimized algorithm for round robin specifically. And second, we should implement caching responses from third party APIs.

Currently the round robin algo checks for all participants availability. When in reality we only need to know if "there's someone available at this slot or not".

In theory we could optimize the round robin use case by "paginating in the backend" without disrupting the frontend at all.

Putting the example for 150 people in a round robin event.
- We get the a 10 people sample and get availability.
- If someone is available, we return early and stop looking
- If not, we check the next 10 and repeat the process

This would make the algorithm from a O(n) every time to a possible O(log n), falling back in the worst case scenario back to O(n)

<img width="594" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/185121e5-739e-46ff-a9da-183bc1d0e57d">

**Comment by keithwillcode** [comment]
Hey @thisisamish, appreciate the request! For this one, we're going to tackle it on the core team. If you're looking for work to pick up as a new contributor, you can also check out our [Good First Issue](https://github.com/calcom/cal.com/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%E2%9C%85+good+first+issue%22) list.
