### ISSUE TITLE
remove gravatar alltogether and replace default image with static one

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11151]
we are making unnecessary calls to gravatar and in general, we should reduce dependencies. 

instead we should be showing a static default avatar photo and urge people to upload their own image

**Comment by ciaranha** [comment]
Two options here! Fill is my preference.

<img width="567" alt="CleanShot 2023-09-05 at 15 09 10@2x" src="https://github.com/calcom/cal.com/assets/4536123/e303fb38-f971-46c6-a494-952ab5787523">


![avatar-fill](https://github.com/calcom/cal.com/assets/4536123/d9d79167-3144-4f6c-9d06-0ff6f59753e1)

![avatar-outline](https://github.com/calcom/cal.com/assets/4536123/9144d273-8f95-4c4a-a053-824f9c7c52ae)

**Comment by PeerRich** [comment]
first one. will use

**Comment by PeerRich** [comment]
![image](https://github.com/calcom/cal.com/assets/8019099/39ba93e0-c282-4e62-be90-69e0bc3890e9)
second looks bad on dark mode

**Comment by pateldivyesh1323** [comment]
I would like to work on this. Can you guide me.
