### ISSUE TITLE
[CAL-2407] Meeting event and meeting url created on different accounts

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#11168]
Reported by customer:-

> I have two Teams calendars integrated in my cal.com. cal.com creates the appointment in the calendar, but creates the meeting link with the other account. I want to have the link created in the <xxxx> calendar and the appointment also sent there. 

https://app.intercom.com/a/inbox/z9l4o9ru/inbox/conversation/2306?view=List

<sub>[CAL-2407](https://linear.app/calcom/issue/CAL-2407/meeting-event-and-meeting-url-created-on-different-accounts)</sub>

**Comment by vachmara** [comment]
Thank you for the reporting @Udit-takkar.

Can I have a way to reproduce this issue on my development environment? 

> Reported by customer:-
> 
> > I have two Teams calendars integrated in my cal.com. cal.com creates the appointment in the calendar, but creates the meeting link with the other account. I want to have the link created in the  calendar and the appointment also sent there.
> 
> https://app.intercom.com/a/inbox/z9l4o9ru/inbox/conversation/2306?view=List
> 
> [CAL-2407](https://linear.app/calcom/issue/CAL-2407/meeting-event-and-meeting-url-created-on-different-accounts)

I cannot access to the link unfortunetly

**Comment by Udit-takkar** [comment]
I think this has been fixed but let me try if i can reproduce the bug now
