### ISSUE TITLE
[CAL-2408] bug: server error when opening team link

### ISSUE THREAD

**Issue by abhijeetsingh-22** [calcom/cal.com#11165]
[Screencast from 2023-09-06 03-56-17.webm](https://github.com/calcom/cal.com/assets/55000107/2f7672c9-59a3-4b0a-9d9b-16c0699b745b)

<sub>[CAL-2408](https://linear.app/calcom/issue/CAL-2408/bug-server-error-when-opening-team-link)</sub>

**Comment by khalidumar29** [comment]
I tested it on my development end and it works perfectly.
