### ISSUE TITLE
Option to remove avatar & larger preview window

### ISSUE THREAD

**Issue by imsoumya18** [calcom/cal.com#11178]
### Is your proposal related to a problem?

There should be an option to remove avatar, not only to change the avatar.
![Screenshot from 2023-09-07 00-16-53](https://github.com/calcom/cal.com/assets/50456734/1a2c7c35-2e93-4eeb-8878-325338806edc)

### Describe the solution you'd like

There should be an option like "remove avatar" and after that there should be a generic human figure icon instead of any previously uploaded avatar picture.

### Describe alternatives you've considered

There should be an option like "remove avatar" and after that there should be a generic human figure icon instead of any previously uploaded avatar picture.

### Additional context

Also, while changing the avatar, the preview window is too small causing stress on the eyes to check if the crop is ok.
![Screenshot from 2023-09-07 00-20-32](https://github.com/calcom/cal.com/assets/50456734/154c57ce-e336-4b6c-9ccd-23553aa6d256)

**Comment by ashwintelmore** [comment]
should work on it?

**Comment by PeerRich** [comment]
i dont think this is a critical issue, no?
