### ISSUE TITLE
Redirect URI not changing from localhost during production build

### ISSUE THREAD

**Issue by mklaver** [calcom/cal.com#11183]
### Issue Summary

The request: I want to run this on port 80/443 so it's available directly by IP or URL but I can't seem to figure that part out.

Even after I do the production build with yarn build && yarn start (and even setting NODE_ENV=production) my redirect URI keeps getting set to localhost:3000... I've set the URL to the correct one in .env and packages/prisma/.env but it doesn't change anything.

This is what I get on startup, no matter what I set in the .env files:
```
@calcom/web:start: - ready started server on 0.0.0.0:3000, url: http://localhost:3000

**Comment by PeerRich** [comment]
sounds like an issue with your .env

**Comment by mklaver** [comment]
> sounds like an issue with your .env

Pasting the relevant section below, hopefully someone sees something glaringly wrong.

```
# - SHARED **************************************************************************************************
# Set this to http://app.cal.local:3000 if you want to enable organizations, and
# check variable ORGANIZATIONS_ENABLED at the bottom of this file
NEXT_PUBLIC_WEBAPP_URL='https://cal.mydomain.tech'
# Change to 'http://localhost:3001' if running the website simultaneously
NEXT_PUBLIC_WEBSITE_URL='https://cal.mydomain.tech'
NEXT_PUBLIC_CONSOLE_URL='https://cal.mydomain.tech'
NEXT_PUBLIC_EMBED_LIB_URL='https://cal.mydomain.tech/embed/embed.js'

# Define which hostnames are expected for the app to work on
#ALLOWED_HOSTNAMES='"cal.com","cal.dev","cal-staging.com","cal.community","cal.local:3000","localhost:3000"'
ALLOWED_HOSTNAMES='"cal.mydomain.tech"'

**Comment by zomars** [comment]
It seems like your env isn't being picked up at all. Can you check on the logs something like "loaded env from..."

**Comment by mklaver** [comment]
> It seems like your env isn't being picked up at all. Can you check on the logs something like "loaded env from..."

Yep, it's picking them up according to this log entry

```
@calcom/prisma:post-install: Environment variables loaded from .env
@calcom/prisma:post-install: Prisma schema loaded from schema.prisma

**Comment by mklaver** [comment]
Attaching the full log output from both yarn build and yarn start for reference
[log.txt](https://github.com/calcom/cal.com/files/12552541/log.txt)

**Comment by shawshankkumar** [comment]
Hey,

@mklaver I tried doing the same by changing the port to 3002 in root .env doesn't work. 

But you can do this:
1. Go to the web folder
2.  https://github.com/calcom/cal.com/blob/main/apps/web/package.json#L10 here put -p 3002
<img width="357" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/1a50fcb9-e4c0-4379-8305-a1107bff7111">
<br/>
3. If you wanna run build and start , making a .env inside web and adding PORT=<port> should also work

Let me know if these work for you!

**Comment by shawshankkumar** [comment]
Since the original issue has been fixed, I think this can be closed?

@PeerRich @mklaver

**Comment by mklaver** [comment]
Changing the port as suggested worked, and using an nginx config like below allowed the port forwarding to happen. Worth noting, running certbot _after_ setting up the nginx config below was essential.

```
server {
    server_name x.y.com;

    location / {
        proxy_pass http://localhost:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
