### ISSUE TITLE
[CAL-2409] orgs: duplicate invites for orgs and non-orgs with dynamic bookings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11186]
both [cal.com/peer](http://cal.com/peer) and [meet.cal.com/peer](http://meet.cal.com/peer) (see emails) are getting invites with dynamic links

same goes for [cal.com/bailey](http://cal.com/bailey) and [meet.cal.com/bailey](http://meet.cal.com/bailey)

i've only realised this since i renamed people today

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7adba475-cae7-4d6b-bb60-c23c42b5b7d6/7538201f-75d8-480a-89be-30fb4d4e71a5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83YWRiYTQ3NS1jYWU3LTRkNmItYmI2MC1jMjNjNDJiNWI3ZDYvNzUzODIwMWYtNzVkOC00ODBhLTg5YmUtMzBmYjRkNGU3MWE1IiwiaWF0IjoxNjk0MDM2MTQ1LCJleHAiOjE2OTQxMjI1NDV9.AIiAsIfLi5Uo-So73fxCjt07031Ov11XCWViBk7Qgyc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2409](https://linear.app/calcom/issue/CAL-2409/orgs-duplicate-invites-for-orgs-and-non-orgs-with-dynamic-bookings)</sub>

**Comment by keithwillcode** [comment]
This also sends multiple calendar invites
