### ISSUE TITLE
[CAL-2411] orgs: dark mode issues for multi select

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11193]
* [ ] border
* [ ] hover is same as checkbox
* [ ] filter dropdown

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b6ea4e84-66f7-477c-8b49-07f469b1a5fd/1ff7849a-63c8-4c48-8551-354cb4edf28b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iNmVhNGU4NC02NmY3LTQ3N2MtOGI0OS0wN2Y0NjliMWE1ZmQvMWZmNzg0OWEtNjNjOC00YzQ4LTg1NTEtMzU0Y2I0ZWRmMjhiIiwiaWF0IjoxNjk0MDc5MDYwLCJleHAiOjE2OTQxNjU0NjB9.le8MZh2_PUzor18313U_U_tMRWimuSVnDZEHh4CDmHI)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a7116dcc-60d8-4073-a357-91e3001143fd/3407cb4f-8c07-4168-8551-984df3cf61ff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNzExNmRjYy02MGQ4LTQwNzMtYTM1Ny05MWUzMDAxMTQzZmQvMzQwN2NiNGYtOGMwNy00MTY4LTg1NTEtOTg0ZGYzY2Y2MWZmIiwiaWF0IjoxNjk0MDc5MzYzLCJleHAiOjE2OTQxNjU3NjN9.piVEdw5QDKw9Q_Y-3kRef4knyX6qAKp7Xzy7hN33z5E)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2411](https://linear.app/calcom/issue/CAL-2411/orgs-dark-mode-issues-for-multi-select)</sub>

**Comment by ashwintelmore** [comment]
hey , can you please tell me how to reproduce this issue
