### ISSUE TITLE
[CAL-2413] date overwrites: keep dialog open after adding a new overwrite

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11198]
https://github.com/calcom/cal.com/assets/8019099/c3947fd4-757e-424a-9a0b-cd8f47387488

<sub>[CAL-2413](https://linear.app/calcom/issue/CAL-2413/date-overwrites-keep-dialog-open-after-adding-a-new-overwrite)</sub>

**Comment by AFZL210** [comment]
This seems fairly easy to fix. Can I try this one?

**Comment by PeerRich** [comment]
@AFZL210 go for it

**Comment by anikdhabal** [comment]
@PeerRich can you check my PR once?
