### ISSUE TITLE
[CAL-2412] Email embed: Can't pick times

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#11194]
[CleanShot 2023-09-07 at 10.48.30.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dec2fa0a-99a6-4c37-bab0-d553b874530f/52742bed-141f-452c-b969-e48bb97f6898)

I should be able to pick times once I pick a date to embed in my email

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2412](https://linear.app/calcom/issue/CAL-2412/email-embed-cant-pick-times)</sub>

**Comment by Kfelts** [comment]
Confirming that I am experiencing this too. I am using Cal hosted by the platform, so all of my features are what is rolled out with the product.

**Comment by hariombalhara** [comment]
This was a bug for sometime back then. It was fixed long back.
