### ISSUE TITLE
[CAL-2410] Auto-save availability schedule right after a date override is added

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#11191]
**Problem**

*adding a date override in 'availbility' requires scrolling up and clicking 'save'. Our entire team have been caught out by this at one point or another!*

**Solution**

An ideal solution is that our entire app has auto-save on availability schedules, event types, settings etc. In the mean time, we need to at least save each availability schedule after you add a date override. So once the modal is closed, the schedule is saved. You do not have to also hit the save button.

We should throw a small toast notification saying "Date override added" once the modal is closed.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2410](https://linear.app/calcom/issue/CAL-2410/auot-save-availability-schedule-right-after-a-date-override-is-added)</sub>

**Comment by keithwillcode** [comment]
We've actually ripped this out because auto-saving one thing while editing the overall availability can cause slots issues. We went back to preferring the Save button.
