### ISSUE TITLE
Wrong time zone in bookings

### ISSUE THREAD

**Issue by shawshankkumar** [calcom/cal.com#11199]
### Issue Summary

my preferred time is in asia/kol but the time on bookings is shown in British summer time. I refreshed and it is still that. I even checked the cookies and it is fine there

<img width="295" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/46634c4e-a006-4fd5-85d1-f1f814d62cdb">
<br/>

<br/>
<img width="279" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/cf0f6b9b-f5d1-4df0-80d5-2499c8b5bbb4">

### Steps to Reproduce

1. make a booking link and check bookings

### Actual Results

- Shown in British time

### Expected Results

- In asia/kolkata time

### Technical details

- using arc browser latest

**Comment by shawshankkumar** [comment]
I'll try to do this after im done watching bun 1.0 launch video :p @PeerRich

**Comment by gitstart-calcom** [comment]
Hi @PeerRich @shawshankkumar we tried to reproduce the issue and we didn't see this behavior, can you provide more context about that?

**Comment by shawshankkumar** [comment]
> Hi @PeerRich @shawshankkumar we tried to reproduce the issue and we didn't see this behavior, can you provide more context about that?

Yes sure, may I know in which environment you guys tried to debug this?

**Comment by gitstart-calcom** [comment]
We tried to reproduce it on Arc and Chrome browser for windows and safari for macOS @shawshankkumar

**Comment by shawshankkumar** [comment]
That's a lot of browsers. But no, i meant did you create a new account or
was it tested on the old account?

**Comment by 1axmansharma** [comment]
Hey! @shawshankkumar, I tried the same on my local setup it is working fine. I read your description and it seems like the cookie you are mentioning is not from cal.com. Can you try to check the issue by changing your timezone from general settings ?

**Comment by shawshankkumar** [comment]
> Hey! @shawshankkumar, I tried the same on my local setup it is working fine. I read your description and it seems like the cookie you are mentioning is not from cal.com. Can you try to check the issue by changing your timezone from general settings ?

hey I'll drop a video soon of the exact issue so its easier to debug

**Comment by keithwillcode** [comment]
Cannot be reproduced
