### ISSUE TITLE
Add Conferencing app opens an white blank screen

### ISSUE THREAD

**Issue by henilGondalia** [calcom/cal.com#11196]
When I Click on Add Conferencing app It Shows mw blank page

### Steps to Reproduce

 Logged in and Clicked on My profile > Conferencing > click on the button "+ Add Conferencing app"

https://github.com/calcom/cal.com/assets/34880491/636c4544-d90f-4059-a62f-fd149950715f

**Comment by razmishra** [comment]
I faced the same issue at that time, but now it is working fine for me.
Can you please try to add a conferencing app again?

**Comment by razmishra** [comment]
Actually problem is when you are at https://cal.com/settings/my-account/conferencing then "Add conferencing app" is not taking anywhere, but when you are at https://app.cal.com/settings/my-account/conferencing, then it's working fine..

**Comment by PeerRich** [comment]
interesting

**Comment by PeerRich** [comment]
i think we should prevent the cal.com usage of dashboard and instead always link to app.cal.com
