### ISSUE TITLE
[CAL-2418] Settings members table duplicates entries upon adding more people

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11207]
### Issue Summary

Adding people to a sub-team in settings members table will duplicate the entries of existing members upon submitting the invitation. Reloading corrects the issue.

### Steps to Reproduce

1. Create an org
2. Invite 2 people
3. Invite 1 more person

### Actual Results

Table shows duplicates of the existing 2 invited people

### Expected Results

Don't duplicate

<sub>[CAL-2418](https://linear.app/calcom/issue/CAL-2418/settings-members-table-duplicates-entries-upon-adding-more-people)</sub>

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2023-09-12 at 1 30 12 PM" src="https://github.com/calcom/cal.com/assets/53316345/e292a357-2196-453b-8e61-ab80c4ece0df">

@leog I can't replicate this bug. I don't see any duplicate after inviting user

**Comment by leog** [comment]
I couldn't repro either, not sure what state of the app I was on to experience it, but can't now. Closing, thanks anyway!
