### ISSUE TITLE
[CAL-2419] User profile avatar flicks between fallback and real avatar

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11208]
### Issue Summary

User profile avatar flicks between fallback and real avatar

### Steps to Reproduce

1. Create an org
2. Update your profile avatar
3. Go to your profile public page

### Actual Results

See your avatar flick between fallback and your uploaded avatar

### Expected Results

Show directly the uploaded avatar

### Evidence

[https://github.com/calcom/cal.com/assets/467258/ab8b0a7e-9bd3-49b1-80bf-f3b28852157e](https://github.com/calcom/cal.com/assets/467258/ab8b0a7e-9bd3-49b1-80bf-f3b28852157e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2419](https://linear.app/calcom/issue/CAL-2419/user-profile-avatar-flicks-between-fallback-and-real-avatar)</sub>

**Comment by leog** [comment]
@sean-brydon I saw that this happens because the fallback loads even if it is delayed using `delayMs=600` and then the avatar comes up. Do you recommend increasing the delay to avoid showing the fallback and then experience a flick when actual avatar is loaded?

**Comment by ahsan-abc** [comment]
yes

**Comment by arjavsethi** [comment]
Hey! @leog  can i work on this issue?

**Comment by leog** [comment]
> Hey! @leog can i work on this issue?

Sure, go ahead @arjavsethi. Thank you.

**Comment by arjavsethi** [comment]
@leog 
Is this the expected result?
[3e1c58fe-cb54-4adb-8b37-22227078914f.webm](https://github.com/calcom/cal.com/assets/75158301/eae85970-2933-4e3b-952e-307c39f757cd)

**Comment by leog** [comment]
Good question. I was thinking that maybe we want to leverage n`next/image` for this one, that provides a way to give priority and other stuff to preload the image. WDYT @sean-brydon?

**Comment by arjavsethi** [comment]
@leog  will try next/image and show you the results
