### ISSUE TITLE
Error message looks odd

### ISSUE THREAD

**Issue by shawshankkumar** [calcom/cal.com#11201]
### Describe the solution you'd like

<img width="1064" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/a5816224-f31f-401a-b401-a7a00157d203">

here, something went wrong looks odd. throwing an error here does not feel apt, instead , maybe a simple message can be shown?

The server responds with a 500 status code. It should be 404 or an empty arr. 

I am not sure if this is intentional or not, but when an user creates an account, this is shown before verification.

Please close this if this is intentional!

**Comment by shreyas0924** [comment]
It is getting redirected to the login page. I dont think this is an issue right? Please correct me if I am wrong.

**Comment by shawshankkumar** [comment]
Not for me.
If i use an email and password, it reflects to the thing in the screenshot.

**Comment by PeerRich** [comment]
i think this may have been a temporal 15 min outage. still happening for you?

**Comment by shawshankkumar** [comment]
> i think this may have been a temporal 15 min outage. still happening for you?

hey @PeerRich yes it is still happening if you have created a new email id. I can fix it just need to know what's the expected behaviour

<img width="1792" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/ebf383dc-f0a0-49bd-8bed-a9c4fadaaae9">
