### ISSUE TITLE
[CAL-2415] Can't re-invite someone to an org

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11204]
### Issue Summary

Deleting a pending invitation doesn't delete the user from the Users table causing an error when trying to invite again

### Steps to Reproduce

1. Create an org
2. Invite someone to the org
3. Delete the invitation
4. Try to invite the same person again (same email)

### Actual Results

Getting an error that that person already exists

### Expected Results

Should be able to re-invite the deleted invited person

<sub>[CAL-2415](https://linear.app/calcom/issue/CAL-2415/cant-re-invite-someone-to-a-sub-team)</sub>

**Comment by abhinav700** [comment]
@leog Can you assign this video to me? I would like to work on it
