### ISSUE TITLE
Build failing on latest version v3.2.9

### ISSUE THREAD

**Issue by krumware** [calcom/cal.com#11217]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Build is failing on v3.2.9, it looks like it's on a file or type reference:
https://github.com/calcom/docker/actions/runs/6105259960/job/16568496886#step:10:12271

Here is a link to the build summaries: https://github.com/calcom/docker/actions
It failed on the most recent nightly, then the release

**Comment by kevingrondin** [comment]
on docker hub https://hub.docker.com/r/calcom/cal.com/tags the last vesion is v3.2.8

**Comment by krumware** [comment]
That's because 3.2.9 is failing to build

**Comment by PeerRich** [comment]
we're tagging 3.2.10 today!

**Comment by PeerRich** [comment]
3.2.10 was tagged. can you check if the build works?

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/releases/tag/v3.2.10

**Comment by krumware** [comment]
Note @keithwillcode the promotion from pre-release to release didn't trigger the docker release automatically. If that becomes a standard flow then we may need to update the action. In the meantime I triggered the build manually!

**Comment by krumware** [comment]
Just confirming, this is resolved in the latest release (3.2.10)
