### ISSUE TITLE
[CAL-2423] Org/team members table flicks columns width

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11213]
### Issue Summary

Org/team members table flicks columns width, causing a weird state when position of table is in a certain point.

### Steps to Reproduce

1. Create an org
2. Invite a lot of people
3. Scroll the members table

### Actual Results

Column width changes and in certain point causes the UI to flick

### Expected Results

Show table members correctly even when scrolling

### Evidence

https://github.com/calcom/cal.com/assets/467258/d7b57fdc-0021-4574-b055-df2451378f9b

<sub>[CAL-2423](https://linear.app/calcom/issue/CAL-2423/orgteam-members-table-flicks-columns-width)</sub>

**Comment by leog** [comment]
> @leog When table is scrolled at the end, suddenly a new table row comes at the top whose height keeps on changing from 150px to 200px violently, this makes the table flicker. One thing we can do is remove the 70vh height and make it full, this also makes it scrollable on mobile, as it will not get confused between table scroll and page scroll.

@pateldivyesh1323 that would be great I think, wondering if you can work on it and show a Loom of how it looks, and @sean-brydon blessing on this one would be great as he worked on this in the past

**Comment by pateldivyesh1323** [comment]
@leog sure i will create a PR.

**Comment by pateldivyesh1323** [comment]
@leog Does this look good or will this affect the data which gets rendered in parts?


https://github.com/calcom/cal.com/assets/109150688/c010c1a6-c530-496b-8c39-441ba54d9e48

**Comment by pateldivyesh1323** [comment]
@sean-brydon Sorry I didn't understood that.

**Comment by Siddharth-2382** [comment]
> > @sean-brydon Sorry I didn't understood that.
> 
> Would it be possible to make the table head sticky?
> 
> e.g. https://css-tricks.com/position-sticky-and-table-headers/

I have done it and would like to create a pull request for the same if allowed.
Here's how it looks like:
https://github.com/calcom/cal.com/assets/94699055/688c601d-c0bd-4230-9f22-886470fb22cc

**Comment by Siddharth-2382** [comment]
Also the UI flickering issues seems to be fixed as I'm unable to reproduce it in both production as well as development runs.

**Comment by sean-brydon** [comment]
> Also the UI flickering issues seems to be fixed as I'm unable to reproduce it in both production as well as development runs.

This looks great - do you think we could maybe have the search bar + filter selection be sticky as well? Feel free to create a PR and request a review from me

**Comment by Siddharth-2382** [comment]
@sean-brydon If the following looks fine I'm ready to create a PR.

https://github.com/calcom/cal.com/assets/94699055/9ac0d0f7-a58c-4f50-9222-68f810a92919

**Comment by Siddharth-2382** [comment]
@sean-brydon I would like to apologise for the first PR as I screwed something up on my side as this was my first contribution. I have redone everything now and I am good to make more contributions to cal.com
