### ISSUE TITLE
[CAL-2460] Redirection on signup with email pass fails

### ISSUE THREAD

**Issue by shawshankkumar** [calcom/cal.com#11218]
### Issue Summary

<img width="1205" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/0642b670-ad25-44d6-9197-277afe713805">

If you sign up with email and password, the redirection afterwards fails. 

### Steps to Reproduce

1. Create an account here https://cal.com/signup?callbackUrl=https://app.cal.com/
2. After submit, it breaks.

I tried to debug and find out the cause locally, but after almost 2 hours, no result. Any insight is appreciated.

### Technical details

- ARC latest version

<sub>[CAL-2460](https://linear.app/calcom/issue/CAL-2460/redirection-on-signup-with-email-pass-fails)</sub>

**Comment by btme0011** [comment]
working on this issue

**Comment by joydeep808** [comment]
after signup what cal.com suppose to do ? 
it will redirected to the home page or another page 
i am  confuse

**Comment by joydeep808** [comment]
after signup is sucessfully
it suppose to  redirect on this url  http://app.cal.com
but it will redirected to this url http://app.cal.com//http:s:/app.cal.com
also i tried to debug this but not able to do it

**Comment by shawshankkumar** [comment]
Yes. I tried to debug it too but it's working locally

**Comment by SomayChauhan** [comment]
yes!! they recently fixed this,
maybe they haven't deployed it yet

**Comment by SomayChauhan** [comment]
yes!! they recently fixed this,
maybe they haven't deployed it yet

**Comment by PeerRich** [comment]
@emrysal was able to reproduce and is investigating

**Comment by emrysal** [comment]
Hi @shawshankkumar this is now fixed (if you could confirm that'd be appreciated, but not needed) - thank you for reporting 💯

**Comment by shawshankkumar** [comment]
> 

Hey @emrysal @PeerRich , it is working now 🚀 
Can you please tell me in which pr it was fixed? since this issue has no linked prs. I tried to fix this myself but couldn't reproduce the error locally myself 😢

**Comment by emrysal** [comment]
Hi @shawshankkumar I found the PR that caused the issue and reverted it in https://github.com/calcom/cal.com/commit/594c62506df9007555ec39ab4ca5a63f6481ff01 - that feature needs to be patched but I was unable to do that quickly.

**Comment by shawshankkumar** [comment]
> Hi @shawshankkumar I found the PR that caused the issue and reverted it in [594c625](https://github.com/calcom/cal.com/commit/594c62506df9007555ec39ab4ca5a63f6481ff01) - that feature needs to be patched but I was unable to do that in an acceptable timeframe whilst this bug existed.

Makes sense, I was playing around with these files to debug, but couldn't. Thanks for the fix !
