### ISSUE TITLE
[CAL-2425] Members table in settings is not scrollable on mobile

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11215]
### Issue Summary

Members table in settings is not scrollable on mobile

### Steps to Reproduce

1. Create an org
2. Invite a lot of people to the org
3. See the member list of the org in a mobile device

### Actual Results

The table can't scroll

### Expected Results

Have the table scroll as expected

<sub>[CAL-2425](https://linear.app/calcom/issue/CAL-2425/members-table-in-settings-is-not-scrollable-on-mobile)</sub>

**Comment by sabir-sayyed** [comment]
can you provide a screenshot please ..? i cant find how to create an organization

**Comment by leog** [comment]
> can you provide a screenshot please ..? i cant find how to create an organization

@sabir-sayyed The URL is `http://app.cal.local:3000/settings/organizations/new`

**Comment by Siddharth-2382** [comment]
@leog I have tried reproducing the issue and it seems that when scrolling on mobile devices once you start scrolling on the table itself, the mobile can't discriminate if you are still trying to scroll the table or the complete page.

My proposed solution is to not make the parent of the table have fixed height and making auto as scrolling inside a div and scrolling through the screen won't make any difference.

If it would be fine, I would like to make the necessary changes and create a PR.

**Comment by sean-brydon** [comment]
Fixed by https://github.com/calcom/cal.com/pull/11711
