### ISSUE TITLE
Creating a Team with a previously used name fails silently

### ISSUE THREAD

**Issue by jimafisk** [calcom/cal.com#1122]
### Issue Summary

It seems that Teams get a specific namespace like https://cal.com/team/test. If you try to create a team with a name that is already taken, you won't get any UI notifications, but the team will not get added to your account. This could be confusing for someone who isn't familiar with what is supposed to happen when a team is added successfully. 

### Steps to Reproduce

1. Sign in to cal.com and click "New Team" in the team settings: https://app.cal.com/settings/teams
2. Enter a team name that has likely been used before, for example "Test" and press "Create Team"
3. You will be brought back to the team settings, but no team will have been added and no validation error presented
4. Try steps 1 & 2 with a more creative name, and a team will be added visually to the team settings page

Maybe the team name could be namespaced to your account to avoid conflicts? Not sure if that defeats the intended purpose of teams... At the very least some sort of notification to the user would help clear up confusion.

### Technical details

- Browser version: Brave Version 1.31.87
- Tested on cal.com (not self-hosted)

**Comment by acvalencia** [comment]
I can take a look at it issue

**Comment by PeerRich** [comment]
this has been fixed
