### ISSUE TITLE
[CAL-2428] better error message if user books seat from same slot again

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#11234]
### Issue Summary

We should show a better message when a users tries to book a seat that they have already booked in a seated event.

Currently, we show this generic message:
<img width="394" alt="Screenshot 2023-09-08 at 11 18 01" src="https://github.com/calcom/cal.com/assets/30310907/ffc33d36-a9cf-4f09-a55f-8c90162cde1a">

We should show something like 'Could not book meeting. Already signed up for this booking.'

### Steps to Reproduce

1. Create an event with seats
2. Book a slot 
3. Book the same slot again with the same user 

<sub>[CAL-2428](https://linear.app/calcom/issue/CAL-2428/better-error-message-if-user-books-seat-from-same-slot-again)</sub>

**Comment by TheNatkat** [comment]
hey i want to work on this and please tell me the message you want instead of this message
