### ISSUE TITLE
[CAL-2429] External invited org user could encounter username clash

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11240]
### Issue Summary

In the edge case of inviting an external user john@foobar.com on an Org with domain acme.com which has already a john@acme.com, then the external user will not be able to accept the invitation due to username clash and not able to pick an alternative.

### Steps to Reproduce

1. Create the org acme as john@acme.com (`http://app.cal.local:3000/settings/organizations/new`)
2. Verify the org (Admin user at `http://app.cal.local:3000/settings/admin/organizations`)
3. Invite someone from acme, such as peter@acme.com
4. Have the invited user in last step accept the invitation
5. Invite another person this time external one with the same email address handle such as peter@foobar.com
6. Have the invited user in last step accept the invitation

### Actual Results

User peter@foobar.com will not be able to accept the invitation receiving an error regarding username `peter` being already in use, with no chance to select an alternative username (as it is inferred and disabled)

### Expected Results

Always set username for external users as email address handle hyphen the email domain name, such as peter-foobar in previous example.

<sub>[CAL-2429](https://linear.app/calcom/issue/CAL-2429/external-invited-org-user-could-encounter-username-clash)</sub>

**Comment by Ayushshrma18** [comment]
Automatically generate unique usernames for external users based on their email address handles and domains to prevent conflicts. Provide clear error feedback and an option for users to select alternative usernames when needed.
