### ISSUE TITLE
Bookings made on cal.com do not show up in Nextcloud

### ISSUE THREAD

**Issue by dl-lim** [calcom/cal.com#1124]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Connected Cal.com with Nextcloud via CalDAV, but bookings made on cal.com do not show up in nextcloud

### Steps to Reproduce

1. Successfully connected to Nextcloud via Cal.com
2. Can see multiple calendars in Cal.com interface.
3. Make booking on Cal.com
4. Visit Nextcloud to see calendar with no bookings, even after 15 mins

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
Nextcloud version 22

**Comment by chintan-mishra** [comment]
I can confirm this issue exists in my case as well. CalDAV doesn't work with the mentioned version of NextCloud.

**Comment by PeerRich** [comment]
can you try again? we shipped a Nextcloud fix

**Comment by borishinzer** [comment]
Works for me (Nextcloud 19), but got another issue. Existing appointments are not taking into account. Slots remain free to book.

**Comment by alishaz-polymath** [comment]
It has been fixed, tested and confirmed 🙏
