### ISSUE TITLE
Allow for custom Available durations

### ISSUE THREAD

**Issue by mywebmasteruk** [calcom/cal.com#11256]
In Event Setup, currently the "Available durations" field will only let you select options from the list of pre-defined durations; from 5min to 180min. 

### Describe the solution you'd like

Please make it possible that we can add custom duration. Either as dropdown item in the list or as input field.

I would also welcome an option for the user to manually input the duration in hours. or to select Start Time and End Time.
 
Thanks

**Comment by Akhilbisht798** [comment]
Hey, I have been looking into this issue. I think we can add a custom duration for Event setup.
If i  am not mistaken i think you are taking about this.

![2023-09-09-20-49-26_screenshot](https://github.com/calcom/cal.com/assets/92508481/20966139-8115-4f9a-ad3b-c14c4e41090c)

**Comment by mywebmasteruk** [comment]
That is of-course, good. But it does not go far enough. As users are confined to selecting the same slot duration.

What would be ideal is a custom list of option for the user to choose from, or input field they can specify the hours or minutes they want to book for.

**Comment by tyler71** [comment]
Concur with this.
I need to be able to schedule 2 4 or 6 hours.
I'm looking at this screen when editing an event

![image](https://github.com/calcom/cal.com/assets/4926565/5b956669-4834-43d7-90c6-1fca272bb57d)

**Comment by PeerRich** [comment]
why would anyone wanna book 32 minutes vs 30 minutes? whats the use case? I think the settings we have today is best. it gives control to the event organiser, not booker

**Comment by mywebmasteruk** [comment]
The use case is for longer sessions, not granular variety. Currently we are restricted to minutes, to a maximum of 180. What would be ideal is to add hours: 1, 2, 3 etc. thanks

**Comment by mywebmasteruk** [comment]
@PeerRich please consider re-opening this. thanks
