### ISSUE TITLE
throws error when trying to invite a member to a organization by copying the invite link

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#11259]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

throws error when trying to invite a member to a organization by copying the invite link

### Steps to Reproduce

1. create a new organization
2. go to settings/organizations/members
3. click on Add
4. Invite team member modals opens up
5, click on  `Copy invite link` button 

### Evidence
[Screencast from 09-09-23 06:12:25 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/453534f2-8234-4365-b110-30104126dedf)

**Comment by janvi01** [comment]
Hey, I am not able to reproduce this bug. The steps as mentioned works perfectly fine.

**Comment by KrishRathor** [comment]
yeah it works perfectly fine
