### ISSUE TITLE
Prisma error while setting up cal.com locally.

### ISSUE THREAD

**Issue by satishkumarsajjan** [calcom/cal.com#11268]
When i run "yarn dx" while setting up the project locally i get this error.
![Screenshot (35)](https://github.com/calcom/cal.com/assets/55579930/8a3d2eb5-b999-4acf-a4cc-48b786c85498)

**Comment by lalitkumawat1m** [comment]
Please run docker daemon while setup locally

**Comment by satishkumarsajjan** [comment]
> Please run docker daemon while setup locally

i am using windows and my docker desktop is running. Even then i am getting this error.

**Comment by satishkumarsajjan** [comment]
You use Linux?

**Comment by satishkumarsajjan** [comment]
emails container is running but not prisma.
![Screenshot (37)](https://github.com/calcom/cal.com/assets/55579930/d3ec4645-11b0-4058-a4ce-1f07bb03a828)

**Comment by satishkumarsajjan** [comment]
I was able to set it up in linux environment without any problems. May be it's a sign to move away from windows.
