### ISSUE TITLE
Hardcoded strings in english that will not get translated

### ISSUE THREAD

**Issue by ujwalkumar1995** [calcom/cal.com#11265]
### Issue Summary

While working on some other issue, I found few strings that were hardcoded in place and won't get translated.

- "Invite via email" (Shows up when we try to invite user to an organization and when we try to invite admins to an organization)
- "Upload a .csv file" (Shows up when we try bulk uploading user to invite to an organization)

### Steps to Reproduce

These labels are rendered when trying to invite users to an organization.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- The mentioned labels won't get translated.

### Expected Results

- The mentioned labels would get translated when translations are added in the future.

### Evidence

- I did not test it but it is quite evident from the code that they won't get translated in other languages.

**Comment by Aashu1Singh** [comment]
@ujwalkumar1995  can you help me in setting project locally. I am getting this error 
![image](https://github.com/calcom/cal.com/assets/99324068/c70a3d76-4f2b-4ca3-a10e-18b1f7d7e236)

This code is creating problem. Can you provide solution  please?
![image](https://github.com/calcom/cal.com/assets/99324068/934fe825-0189-48fc-954c-a083ac819924)

**Comment by ujwalkumar1995** [comment]
Hey @Aashu1Singh 
Can you copy .env.example file to .env?

**Comment by Aashu1Singh** [comment]
@ujwalkumar1995  yes, i have done this and also set up the superbase 

![Uploading image.png…]()

**Comment by ujwalkumar1995** [comment]
Hi @Aashu1Singh 
I am not using superbase to setup the db.. I guess the contributing guidelines might have gotten updated. I setup the repo long time back. I am using docker to run the db. After following the steps in the contribution guidelines, I just run yarn dx instead of yarn dev.

**Comment by Aashu1Singh** [comment]
@ujwalkumar1995  can you help me to set up with docker. I am also using same command. what have you provided in database url?

**Comment by ujwalkumar1995** [comment]
@Aashu1Singh 
Use the same mentioned in .env.example

**Comment by vicheanath** [comment]
> @ujwalkumar1995 can you help me to set up with docker. I am also using same command. what have you provided in database url?

it simple you need to install docker desktop and follow guridline on read me
