### ISSUE TITLE
[CAL-2436] feat: make jitsi video ready for self-hosters

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11275]
right now the jitsi app only works with hosted jitsi links. it would be nice if self-hosters could change the "JITSI_URL" inside the admin key manager

<sub>[CAL-2436](https://linear.app/calcom/issue/CAL-2436/feat-make-jitsi-video-ready-for-self-hosters)</sub>

**Comment by PeerRich** [comment]
go for it @neo773! 🥳

**Comment by hariombalhara** [comment]
This is already supported through jitsiHost 
See it working on main(tested locally)
![image](https://github.com/calcom/cal.com/assets/1780212/567ba27c-1652-4727-8b25-f3533fba7cac)

**Comment by PeerRich** [comment]
turns out we already have support for self-hosted jitsi, my bad!
