### ISSUE TITLE
[CAL-2438] Multiple (organizer) addresses for attendee to choose from doesn't select the one that's clicked on

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#11276]
[https://github.com/calcom/cal.com/assets/97884287/542b8769-0320-4e33-afdf-25a106ab85a6](https://github.com/calcom/cal.com/assets/97884287/542b8769-0320-4e33-afdf-25a106ab85a6)

Created via Threads. See full discussion: [https://threads.com/34535458143](https://threads.com/34535458143)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2438](https://linear.app/calcom/issue/CAL-2438/multiple-organizer-addresses-for-attendee-to-choose-from-doesnt-select)</sub>

**Comment by abhijeetsingh-22** [comment]
Not able to reproduce. It seems to be working fine

[Screencast from 2023-09-23 13-20-08.webm](https://github.com/calcom/cal.com/assets/55000107/c548f5d0-11f7-460e-a5c5-32a658df0b49)
