### ISSUE TITLE
[CAL-2449] Duplicate bookings when using a payment type on the booking

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#11278]
### Issue Summary

Duplicate bookings when using a payment type on the booking

### Steps to Reproduce

Booking with a payment type on it, then not paying, then someone books in that slot that you took, then paying, then the slot is booked by both people.

### Actual Results

- Two bookings are made for the same time.

### Expected Results

- The person that paid, should either be told they lost their slot, or should have it held reserve for a time period.

### Technical details

- Chrome latest
- Node 18

### Example

![image](https://github.com/calcom/cal.com/assets/53020786/9c82790c-62e7-4df2-8fa8-9d82218fcada)

<sub>[CAL-2449](https://linear.app/calcom/issue/CAL-2449/duplicate-bookings-when-using-a-payment-type-on-the-booking)</sub>

**Comment by hona9** [comment]
@Hybes How do I reproduce the bug?

**Comment by hona9** [comment]
@PeerRich

**Comment by Hybes** [comment]
@hona9 are you still looking in to this? I can help you reproduce, it's somewhat a crucial issue between making payments and making bookings.
