### ISSUE TITLE
[CAL-2442] [CAL-2441] Variable not populated

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#11279]
{ATTENDEE_FIRST_NAME} variable isn't being populated

Created via Threads. See full discussion: [https://threads.com/34535512484](https://threads.com/34535512484)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2441](https://linear.app/calcom/issue/CAL-2441/variable-not-populated)</sub>

<sub>[CAL-2442](https://linear.app/calcom/issue/CAL-2442/[cal-2441]-variable-not-populated)</sub>

**Comment by CarinaWolli** [comment]
It only works if name splitting is enabled: 
<img width="547" alt="Screenshot 2023-09-11 at 11 47 19" src="https://github.com/calcom/cal.com/assets/30310907/f0f0abc4-df13-4853-b6c9-53e5e94079a0">

We should also make it work if this is not enabled:

First name = first word of the name field
Second name = last work of the name field, if it is only one word then keep it empty
