### ISSUE TITLE
[CAL-2440] [CAL-2439] Removing Google Cal from installed apps throws an error

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#11277]
<img width="1141" alt="Screenshot 2023-09-11 at 08 20 03" src="https://github.com/calcom/cal.com/assets/97884287/a5eaad4c-c9be-43f1-b53d-90bcc7ab1260">

Created via Threads. See full discussion: [https://threads.com/34535408270](https://threads.com/34535408270)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2439](https://linear.app/calcom/issue/CAL-2439/removing-google-cal-from-installed-apps-throws-an-error)</sub>

<sub>[CAL-2440](https://linear.app/calcom/issue/CAL-2440/[cal-2439]-removing-google-cal-from-installed-apps-throws-an-error)</sub>

**Comment by Nabhag8848** [comment]
Hey @milospuac @PeerRich I can't reproduce this issue anymore. I can remove the app succesfully without any errors. Is there anything, i'm missing?

**Comment by Nabhag8848** [comment]
Cool Thanks!
