### ISSUE TITLE
[CAL-2435] baking buns: nodejs to bun migration

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11270]
lets see what this bad boy https://bun.sh can do

![image](https://github.com/calcom/cal.com/assets/8019099/7c729c77-4d9e-4b96-9edb-4fa6d1217051)

<sub>[CAL-2435](https://linear.app/calcom/issue/CAL-2435/baking-buns-nodejs-to-bun-migration)</sub>

**Comment by PeerRich** [comment]
ah right, workspaces will be tricky 
![CleanShot 2023-09-11 at 11 17 31@2x](https://github.com/calcom/cal.com/assets/8019099/d6216731-1797-4cac-846a-7b3a3f35e9ca)

**Comment by PeerRich** [comment]
not sure how to migrate workspaces yet but here are docs https://bun.sh/docs/install/workspaces

**Comment by PeerRich** [comment]
i'm failing getting workspaces up and running. adding a bounty

**Comment by neo773** [comment]
It's a bug in bun
https://github.com/oven-sh/bun/issues/533#issuecomment-1712865027

**Comment by PeerRich** [comment]
great to hear! will wait 🙏

**Comment by Hebilicious** [comment]
Happy to contribute to this, there is a few blockers though : 

- No publish support means npm/yarn/pnpm etc are still necessary to publish to the registry
- Workspace support works with some workaround (need to use `workspace:*`)
- playwright doesn't work with bun yet
- turborepo support (?)

**Comment by KSSaiTeja** [comment]
shall i work on this..?

**Comment by imran-khani** [comment]
> shall I work on this..?

why ask if you can? do it.
