### ISSUE TITLE
[CAL-2448] bug: create team UI doesnt handle overflow correctly

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11298]
![CleanShot 2023-09-12 at 11 27 57](https://github.com/calcom/cal.com/assets/55134778/40f14256-e933-4d25-a947-5a0270da2914)

<sub>[CAL-2448](https://linear.app/calcom/issue/CAL-2448/bug-create-team-ui-doesnt-handle-overflow-correctly)</sub>

**Comment by noobCode-69** [comment]
I would like to work on this @sean-brydon
