### ISSUE TITLE
[CAL-2452] speed up insights

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11306]
app.cal.com/insights is quite slow, maybe we need a better "timeseries" database structure to improve queries

<sub>[CAL-2452](https://linear.app/calcom/issue/CAL-2452/speed-up-insights)</sub>

**Comment by alannnc** [comment]
Right now we might be taking a lot of time from the DB, I have investigated a little more and found some new bugs for insights that should help us in the short term.
The big goal will be using a separated DB for reading all the data insights require.

https://github.com/calcom/cal.com/issues/11352
https://github.com/calcom/cal.com/issues/11351
