### ISSUE TITLE
[CAL-2451] Orgs - Not deleting user on team invite

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11300]
When a user is not a member of an org 

and when they are invited to a team first - removing the invite leaves the user still existing in pending state.

We should apply the same logic we do currently - check if any username/password is set if not just delete the user

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2451](https://linear.app/calcom/issue/CAL-2451/orgs-not-deleting-user-on-team-invite)</sub>

**Comment by hariombalhara** [comment]
I think it's not valid now. Adding the user to team also adds the user to organization. So, if the user is removed just from the team, he is still a part of the org and deletion shouldn't happen. And when he is remove from the organization also then the user is deleted as per the existing conditions.

cc @sean-brydon for confirmation to close this ticket.

**Comment by hariombalhara** [comment]
Actually closing it, can be reopened if it still makes sense.
