### ISSUE TITLE
[CAL-2456] Create testcases to cover "Connect selected calendar to credential" 

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#11310]
### Is your proposal related to a problem?

Follow up https://github.com/calcom/cal.com/pull/11283 with adding tests.

<sub>[CAL-2456](https://linear.app/calcom/issue/CAL-2456/create-testcases-to-cover-connect-selected-calendar-to-credential)</sub>

**Comment by CodeWithUmair** [comment]
Hi @emrysal hope your are well. Please tell me more about this issue, I have to do this.

**Comment by 0xJaskeerat** [comment]
@PeerRich Hey is this issue done ? 
As I can see a merged PR , if yeah please close the issue

**Comment by RohitPendurkar** [comment]
is this issue open or closed?? I can see a merged pull request.

**Comment by keithwillcode** [comment]
@RohitPendurkar it’s still open because that PR didn’t include tests

**Comment by xiejosh** [comment]
I would like to work on this.
