### ISSUE TITLE
[CAL-2520] GET /v1/event-types is broken 💥

### ISSUE THREAD

**Issue by another-guy** [calcom/cal.com#11317]
### Issue Summary

List event-type API endpoint is broken. 💥 

For some reason the issue is not surfaced on Status page https://status.cal.com/ 🤔 

### Steps to Reproduce

1. Invoke call GET `https://api.cal.com/v1/event-types?apiKey=cal_live_<...>`

This is a bug because recently this API endpoint worked fine in the same environments.

### Actual Results

HTTP 400 with body:

```
{
    "message": "An error occured while querying the database."
}
```

### Expected Results

Valid list of configured event types.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

* Tested from Postman and cURL
* `curl --location 'https://api.cal.com/v1/event-types?apiKey=cal_live_<...>' \
--header 'Content-Type: application/json'`

<sub>[CAL-2520](https://linear.app/calcom/issue/CAL-2520/get-v1event-types-is-broken-💥)</sub>

**Comment by PeerRich** [comment]
we are investigating

**Comment by jenilsavani9** [comment]
I've tested the endpoint myself, both from Postman and cURL, and it seems to be functioning correctly on my end. I received the expected valid list of configured event types without any errors or hiccups.

It's important to note that this endpoint had been working fine in the same environments for me, and I can't seem to reproduce the reported issue. It might be specific to certain configurations or conditions that I'm not encountering.

If there's anything specific you'd like me to test or if you need more information to pinpoint the problem, please let me know.

**Comment by another-guy** [comment]
@jenilsavani9  The issue was manifesting itself consistently on the date of the report (Sept 12, 12:17 PST). I was not the only person who was seeing that. In fact, we have the 500 responses logged to DataDog and had an alert. That's how we learnt about the issue in the first place.

I don't know if the issue was specific to our Cal.com tenant or not. Up until yesterday morning, we had such configuration that more than one Google Calendar integration was enabled simultaneously, with the same calendars and event-type connections. As of now, we only have one integration enabled right now and the issue is gone.

**Comment by agencia904** [comment]
Same error here.

**Comment by al8** [comment]
ok this seems sporadic. We have automation running that GET event-types periodically, and frequently we're getting the 400 error


```
{"message":"An error occured while querying the database.","error":{"stack":"Error: An error occured while querying the database.\n    at redactError (/var/task/apps/api/.next/server/chunks/39487.js:68:16)\n    at Executor.captureErrors [as currentFn] (/var/task/apps/api/.next/server/chunks/85223.js:58:108)","message":"An error occured while querying the database."}}
```

Is there some sporadic database issue that's occurring between your web and database layers?

**Comment by keithwillcode** [comment]
We believe this is related to some database issues we've experienced recently. We made fixes yesterday to clear these up.

**Comment by another-guy** [comment]
@keithwillcode @PeerRich @jenilsavani9 This happened again on 2023-10-06T11:06:25 Pacific time. I think it was too early to close this issue.
