### ISSUE TITLE
[CAL-2458] Automated test for collective event hosts

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#11316]
Follow up automation test for [https://github.com/calcom/cal.com/pull/10967](https://github.com/calcom/cal.com/pull/10967)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2458](https://linear.app/calcom/issue/CAL-2458/automated-test-for-collective-event-hosts)</sub>

**Comment by supalarry** [comment]
#11670 already added collective scheduling testing so will close this.
