### ISSUE TITLE
[CAL-2459] insights upgrade screen has no title and subtitle for upgrade screen

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11319]
insights upgrade screen:

![CleanShot 2023-09-12 at 23 05 37@2x](https://github.com/calcom/cal.com/assets/8019099/02b77a88-f35e-480e-925a-d45d8cbc0702)

misses the headline and subtitle, like routing forms:

![CleanShot 2023-09-12 at 23 05 52@2x](https://github.com/calcom/cal.com/assets/8019099/5dfd5f6c-a119-49de-947e-631ee7d8aad4)

<sub>[CAL-2459](https://linear.app/calcom/issue/CAL-2459/insights-upgrade-screen-has-no-title-and-subtitle-for-upgrade-screen)</sub>

**Comment by void-main1812** [comment]
I can work on this issue can you assign this one to me ?

**Comment by PeerRich** [comment]
sure

**Comment by PeerRich** [comment]
tho #11328 has already been submitted
