### ISSUE TITLE
[CAL-2461] Show Routing From End Route on the submission form

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#11329]
**Problem:**

Sometimes people will fill out a routing form but then don't schedule a meeting, or complete the flow on the page/link they were directed to.

**Solution:**

On the submission response, we should show what link / event type they were directed to after filling out the form so that it's always clear, even if they don't complete the flow and book a meeting, where exactly they were sent. We can add it right at the bottom.

Examples of what we would show at the bottom of the submission email:

* Routed to: Event redirect (/sales/30mins)
* Route to Custom page ([https://cal.com/pricing](https://cal.com/pricing))

**Temporary solutions and why this is not urgent:**

You can work it out yourself by filling out the form with their exact responses but for more complex forms this is very time consuming and tedious.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2461](https://linear.app/calcom/issue/CAL-2461/show-routing-from-end-route-on-the-submission-form)</sub>

**Comment by btme0011** [comment]
can i work on this feature?
