### ISSUE TITLE
[CAL-2521] Make E2E test: Paid booking with payment confirmation should be able to be rescheduled

### ISSUE THREAD

**Issue by ologbonowiwi** [calcom/cal.com#11339]
This is closer to what we made on #9368.

The difference is that on #10069, we needed a way to confirm the payment on Stripe stuff; we already have this now on [apps/web/playwright/fixtures/users.ts:482](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/fixtures/users.ts#L482~L511), and it's easily usable via `await user.confirmPendingPayment();` as on [apps/web/playwright/integrations-stripe.e2e.ts:126](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/integrations-stripe.e2e.ts#L126).

The test should be implemented on [apps/web/playwright/integrations-stripe.e2e.ts:147](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/integrations-stripe.e2e.ts#L147).

<sub>[CAL-2521](https://linear.app/calcom/issue/CAL-2521/make-e2e-test-paid-booking-with-payment-confirmation-should-be-able-to)</sub>

**Comment by Ahmadkashif** [comment]
Hi there, I would like to work on this please.

**Comment by ologbonowiwi** [comment]
Go for it @Ahmadkashif!

**Comment by ologbonowiwi** [comment]
https://github.com/calcom/cal.com/blob/main/apps/web/playwright/integrations-stripe.e2e.ts#L85~#L94 probably this snippet it'll be useful @Ahmadkashif

**Comment by Ahmadkashif** [comment]
Hi @keithwillcode @ologbonowiwi :wave: 

Check out my attempt in the PR mentioned above :point_up_2:
