### ISSUE TITLE
Team embeds and routing form embeds 404 on Safari

### ISSUE THREAD

**Issue by mreilly-lula** [calcom/cal.com#11346]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I'm still experiencing consistent 404s on Safari only when loading embeds that route to team booking links or routing forms.
[This next js asset](https://cal.com/_next/static/chunks/pages/apps/%5Bslug%5D/%5B...pages%5D-f95756bebb620320.js) for example will load on Chrome, but 404 on Safari. 

**This is leading to embeds being broken.**

### Steps to Reproduce

1. Visit the above link in Chrome, and observe that it loads
2. Visit the above link in Safari, and observe that it throws a 404
I'm hesitant to share a link to our product where this bug can be observed, but happy to PM to team members who end up looking into this.

<img width="482" alt="Screenshot 2023-09-04 at 10 48 17 AM" src="https://github.com/calcom/cal.com/assets/57537896/a529eaf4-305d-413f-ab5c-59ef054b0ccb">
<img width="407" alt="Screenshot 2023-09-04 at 10 48 09 AM" src="https://github.com/calcom/cal.com/assets/57537896/1bebe07a-777d-43cd-acf7-f518745a1f64">
<img width="421" alt="Screenshot 2023-09-04 at 10 48 00 AM" src="https://github.com/calcom/cal.com/assets/57537896/3a07b7e7-d8a7-410e-8f4c-92bc93cede82">

**Comment by PeerRich** [comment]
can you send us a link with that embed?
