### ISSUE TITLE
Line clamp on Profile not working on safari/iPhone

### ISSUE THREAD

**Issue by kcrimi** [calcom/cal.com#11343]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Recently, the description length was clamped to make the event lists on the profile page more readable.https://github.com/calcom/cal.com/pull/10795

Looks like this doesn't really work on safari and iPhone due to the way safari implements `line-clamp`

### Steps to Reproduce

1. Go to a profile with longer event descriptions on Safari / iPhone (eg https://cal.com/artbysandramejia)

### Actual Results

- Descriptions are clamped to 3 lines similar to chrome
<img width="250" src="https://github.com/calcom/cal.com/assets/2559359/1c19b6e4-92a3-40e8-b4a5-7fe7536173f2">

### Expected Results

- Text is not clamped and instead there is text overlapping
<img width="250" alt="Screenshot 2023-09-13 at 11 53 17 AM" src="https://github.com/calcom/cal.com/assets/2559359/0a46d3c1-d516-47ed-b375-e8c838af681f">

### Technical details

- iPhone 14 Pro with the latest iOS on Safari.
- iPhone 12 with the latest iOS on Safari
- iPad 13 Pro Max with the latest iOS on Chrome

### Evidence

- See above examples

**Comment by PeerRich** [comment]
![CleanShot 2023-09-15 at 15 13 41@2x](https://github.com/calcom/cal.com/assets/8019099/02dad842-9163-428a-b2b2-62aa8bea4393)
i can reproduce this in safari...

**Comment by PeerRich** [comment]
@sean-brydon will fix this this week! should be live by tuesday
