### ISSUE TITLE
[CAL-2468] follow up #11350 performance

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11362]
If we chain `.filter` and `.map` we are essentially iterating through the array twice. By replacing this with a `.reduce` we're able to filter through values while only iterating through the array once.

_Originally posted by @joeauyeung in https://github.com/calcom/cal.com/pull/11350#discussion_r1325302281_
            

<sub>[CAL-2468](https://linear.app/calcom/issue/CAL-2468/follow-up-11350-performance)</sub>

**Comment by joeauyeung** [comment]
Already solved in #11350
