### ISSUE TITLE
[CAL-2471] Ability to change stripe currency to different from default.

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#11374]
This probably need some investigation but we should be able to change currency on stripe payment configuration.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2471](https://linear.app/calcom/issue/CAL-2471/ability-to-change-stripe-currency-to-different-from-default)</sub>

**Comment by PeerRich** [comment]
i thought its whatever stripe's connect currency it is?

**Comment by alannnc** [comment]
> i thought its whatever stripe's connect currency it is?
@PeerRich 
We take the default to create the payment order, but probably can be switch to something else. I'm gonna test it and get back to this. Payouts on the other hand can only be received in stripe account available currency from that country.
