### ISSUE TITLE
Tests for EventTypeAppCardInterface and AppCard

### ISSUE THREAD

**Issue by gitstart-calcom** [calcom/cal.com#11370]
Related issue: https://github.com/calcom/cal.com/issues/11005

### EventTypeAppCardInterface: 

- [x] packages/app-store/_components/EventTypeAppCardInterface.tsx https://github.com/calcom/cal.com/pull/11344
- [ ] packages/app-store/ga4/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/qr_code/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/giphy/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/gtm/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/fathom/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/paypal/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/plausible/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/metapixel/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/stripepayment/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/basecamp3/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/templates/booking-pages-tag/components/EventTypeAppCardInterface.tsx
- [ ] packages/app-store/templates/event-type-app-card/components/EventTypeAppCardInterface.tsx

### AppCard: 

- [ ] packages/app-store/_components/AppCard.tsx
- [ ] packages/ui/components/apps/AppCard.tsx

**Comment by PeerRich** [comment]
this doesnt look very useful
