### ISSUE TITLE
[CAL-2472] orgs: ability to edit avatar

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11376]
![CleanShot 2023-09-15 at 09 31 43@2x](https://github.com/calcom/cal.com/assets/8019099/4748f04d-3bcd-4027-81e5-20f3c78bed70)

<sub>[CAL-2472](https://linear.app/calcom/issue/CAL-2472/orgs-ability-to-edit-avatar)</sub>

**Comment by Arjunkrishna17** [comment]
@PeerRich I'd like to work on this issue, but I need more details. Can you clarify what's expected for editing avatars? Is it about cropping, filters, and color adjustments?

**Comment by lalitcap23** [comment]
@PeerRich ,  can you please clarify what exact changes are to be expected from avatar edits .
