### ISSUE TITLE
[CAL-2474] E2E: Test email embed

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11380]
Extend these Embed Code Generator tests  to add Email Embed tests. [https://github.com/calcom/cal.com/blob/25d0c294942020aa7428d339cc11dbd8c1f16247/apps/web/playwright/embed-code-generator.e2e.ts#L114](https://github.com/calcom/cal.com/blob/25d0c294942020aa7428d339cc11dbd8c1f16247/apps/web/playwright/embed-code-generator.e2e.ts#L114)
Should select a few dates and slots and verify that the corresponding html is available in the textarea for copying

Motivation: Something that could have avoided [this](11379) issue

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2474](https://linear.app/calcom/issue/CAL-2474/e2e-test-email-embed)</sub>

**Comment by btme0011** [comment]
can i work on this issue?

**Comment by Yashh56** [comment]
Sir can you provide screenshot of this issue ?

**Comment by hariombalhara** [comment]
This is what needs to be tested https://cal.com/docs/core-features/embed/adding-slots-to-your-email

**Comment by keithwillcode** [comment]
@btme0011 Feel free to open a PR and we'll review!

**Comment by Yashh56** [comment]
Sir, I don't understand this issue can you help me with this issue?
I am new to open source.

**Comment by suyash5053** [comment]
@btme0011 Anyone can take up the issues and work on it, Hope to see you PR soon.
@Yashh56 In this issue you need to add some testcases for testing https://cal.com/docs/core-features/embed/adding-slots-to-your-email , you can surf the internet and learn about testing, then you can solve this issue.

**Comment by Samrj12** [comment]
Is this still workable or done?
