### ISSUE TITLE
Minimum Time is not correct.

### ISSUE THREAD

**Issue by anisur2805** [calcom/cal.com#11394]
This time should not be less then 10 minutes during the update time.
![image](https://github.com/calcom/cal.com/assets/11018986/13204dde-187b-4c82-b8ac-b68115491874)

**Comment by up1512001** [comment]
@anisur2805 can you further explain how to replicate this bug?

**Comment by abhinaisai2002** [comment]
can i work on this issue

**Comment by yavinash249** [comment]
@anisur2805  can you give the path?

**Comment by abhinaisai2002** [comment]
which path?

**Comment by adarshSrivastava01** [comment]
Is it a global configuration that this could not be less than 10 minutes?

**Comment by PeerRich** [comment]
why not less than 10?

**Comment by anisur2805** [comment]
@PeerRich because the minimum time is 10 minutes. And here i found its work less than 10.
