### ISSUE TITLE
Time Buttons Should be Scroll not the Whole Right Side

### ISSUE THREAD

**Issue by anisur2805** [calcom/cal.com#11392]
If there is a scroll besides time select buttons it will be more user friendly. Currently its scrolling but the date and time format goes top which is not user friendly.
![image](https://github.com/calcom/cal.com/assets/11018986/a0bf2ede-1970-40c3-bbd7-d91dc0af0340)

**Comment by shirsho-roy** [comment]
Can you assign me this issue // @kemiller

**Comment by anisur2805** [comment]
@shirsho-roy you don't need to assign by someone else, just work on an open issue and after done the fixing create a pull request. That's all.
