### ISSUE TITLE
[CAL-2480] bug: request for reschedule did not ca cancel initially meeting

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11397]
### Issue Summary

request to reschedule does not cancel initial meeting

### Steps to Reproduce

1. make a test booking
2. inside https://app.cal.com/bookings 
3. request reschedule

![image](https://github.com/calcom/cal.com/assets/8019099/520418b0-6dae-4c61-bdb5-4cabcdc54b83)

### Actual Results

- old event is still on the calendar

### Expected Results

- the event where reschedule has been requested should get cancelled on the calendar. the email already says cancelled ![image](https://github.com/calcom/cal.com/assets/8019099/03a47841-2182-42a8-ad61-1e9e197a513a)

### Technical details

- v3.3

<sub>[CAL-2480](https://linear.app/calcom/issue/CAL-2480/bug-request-for-reschedule-did-not-ca-cancel-initially-meeting)</sub>

**Comment by PeerRich** [comment]
test required for PR

**Comment by ologbonowiwi** [comment]
@PeerRich, what's the Calendar that you're using?

I'm asking cause I tested here (locally) with Apple Calendar), and it worked fine.

And it looks like we're even testing this on https://github.com/calcom/cal.com/blob/main/apps/web/playwright/reschedule.e2e.ts#L21~L46.

What's missing? Can you give more details on how you found this bug, which Calendar app you're using, etc.?

**Comment by ologbonowiwi** [comment]
I tested here under https://cal.com/ologbonowiwi, and the Google Meet/Calendar event was canceled fine. The event does not appear on my Google Meet/Calendar in either of the (attendee/organizer) e-mails.

I still want to handle this, but I'll need more clarification. Feel free to message me on Discord (I'm also ologbonowiwi there) if you prefer.

**Comment by vijayraghav-io** [comment]
@PeerRich , was able to recreate the issue and is fixed by this PR https://github.com/calcom/cal.com/pull/11411

**Comment by PeerRich** [comment]
google calendar

**Comment by vijayraghav-io** [comment]
This issue occurs irrespective of calendar type (google or apple or ...), I have raised a PR to fix this ,please look into this https://github.com/calcom/cal.com/pull/11411 for more details.

**Comment by ologbonowiwi** [comment]
I see that @vijayraghav-io didn't /claim the bounty. Remember to /tip him for it @PeerRich! 😄

**Comment by vijayraghav-io** [comment]
I thought the bounty label was removed, hence didn't claim it  :)
