### ISSUE TITLE
[CAL-2486] Let admin choose autoAcceptEmailDomain on org creation

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#11424]
When creating an org, if the user creating the org is an admin, the org property `autoAcceptEmailDomain` should be able to be chosen by the admin instead of inferring it from the owner email address. This will let admin create orgs for third parties without having to change that property manually after org creation.

<sub>[CAL-2486](https://linear.app/calcom/issue/CAL-2486/let-admin-choose-autoacceptemaildomain-on-org-creation)</sub>

**Comment by Siddharth-2382** [comment]
Hello @leog I'd like to work on this issue but I'm not getting absolutely what you're saying. Can you give me a little more explanation about the issue and what we are expecting.
