### ISSUE TITLE
[CAL-2488] The clickable area of the 'x' in add guests section is not user friendly.

### ISSUE THREAD

**Issue by hashkazi00** [calcom/cal.com#11423]
### Is your proposal related to a problem?

It's not intuitive to have to click exactly on the cross icon in the add guest email input.

### Describe the solution you'd like

The clickable area should be increased atleast by 4px on each side or the whole contain should be made clickable. 

### Additional context

https://github.com/calcom/cal.com/assets/37013706/05ed075d-9a45-410a-adc7-444cbe61844b

<sub>[CAL-2488](https://linear.app/calcom/issue/CAL-2488/the-clickable-area-of-the-x-in-add-guests-section-is-not-user-friendly)</sub>

**Comment by anirudh12032008** [comment]
Hi, this would be my first open source contribution I hope my fix will help
