### ISSUE TITLE
[CAL-2489] Doc: Embed prefilling

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11436]
Create a doc on prefilling embed.

Document this sandbox [https://codesandbox.io/s/react-prefill-attendee-address-email-sqhf7r?file=/src/App.js](https://codesandbox.io/s/react-prefill-attendee-address-email-sqhf7r?file=/src/App.js)

Motivation: Users getting confused on what parameter to pass, what value to give

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2489](https://linear.app/calcom/issue/CAL-2489/doc-embed-prefilling)</sub>

**Comment by hariombalhara** [comment]
Doc In Review cc @alishaz-polymath

**Comment by alishaz-polymath** [comment]
Live ✅
