### ISSUE TITLE
[CAL-2523] Expose answers collected for all questions (incl. custom) of the bookings listed in GET /v1/bookings

### ISSUE THREAD

**Issue by another-guy** [calcom/cal.com#11430]
### Is your proposal related to a problem?

The `GET https://api.cal.com/v1/bookings?apiKey=cal_live_<...>` API endpoint does not return responses to custom booking questions as a part of `bookings.[index].responses`.

As an API consumer I want all the collected responses to be exposed to me so that I can use them for custom automations.

I configure the event type in Cal.com web app to have a custom question:

![image](https://github.com/calcom/cal.com/assets/5762340/70c17071-f1c3-4256-ba4f-d70226063732)

After a user has successfully books a time on my calendar, I am able to see the response collected for the custom question.

<img width="707" alt="image" src="https://github.com/calcom/cal.com/assets/5762340/509927e7-ae98-46a1-98ab-e8f17196031f">

Yet the API response doesn't show it.

### Describe the solution you'd like

Ensure that `GET /v1/bookings` endpoint exposes all the answers for bookings.

### Describe alternatives you've considered

We could call a different API endpoint to fetch the bookings's answers, but 1) it doesn't seem to exist; 2) it'd be very unusable to have to make a query per booking.

### Additional context

-

### Requirement/Document

-

<sub>[CAL-2523](https://linear.app/calcom/issue/CAL-2523/expose-answers-collected-for-all-questions-incl-custom-of-the-bookings)</sub>

**Comment by PeerRich** [comment]
maybe @hariombalhara can look into this

**Comment by hariombalhara** [comment]
@arjavsethi the steps look correct to me. 
@another-guy could you see any issue with it?

**Comment by another-guy** [comment]
@hariombalhara this seems to be working now, but I swear I was not seeing the custom responses collected when reported the issue. It seems like something did change

**Comment by keithwillcode** [comment]
Closing as it’s working now.
