### ISSUE TITLE
[CAL-2493] Invite users bugs

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#11441]
https://github.com/calcom/cal.com/pull/11356#issuecomment-1725187534

https://github.com/calcom/cal.com/pull/11356#issuecomment-1725200529

<sub>[CAL-2493](https://linear.app/calcom/issue/CAL-2493/invite-users-bugs)</sub>

**Comment by keithwillcode** [comment]
Closing because both PRs mentioned in the description have been merged.
