### ISSUE TITLE
[BUG]:On Hover only Bitcoin Icon color changes in Job section 

### ISSUE THREAD

**Issue by Karan8501** [calcom/cal.com#11445]
### Issue Summary
In the [https://cal.com/jobs] the In the Given Job section On hovering on the component the color of the bitcoin icon chages 
irelavent where i am hovering on the component.

### Steps to Reproduce

1.  Went to [https://cal.com/jobs]
2. Go to the Job profile before the Hover
![image](https://github.com/calcom/cal.com/assets/106527836/fb0b6f4e-a3bf-45be-b63b-a3ca64cb38e0)

4.Hover on the Job section 
![image](https://github.com/calcom/cal.com/assets/106527836/26027f15-8abd-425a-a23a-24b66129557c)
5 Hover on the other part and check the issue

Instead on Hovering only the Bitcoin Icon it should Hover on the the all give icon in the job section

### Actual Results

- Only Hover on the Bitcoin Icon

### Expected Results

- Hover should work on every Icon on the component

### Technical details
Chrome Browser Version 116.0.5845.188
Windows 10
### Evidence

https://github.com/calcom/cal.com/assets/106527836/4749991a-ce2c-4eaa-973c-d3c6f92ea589

**Comment by sushilmagare10** [comment]
Can someone just tell me what colors you need for each icon

**Comment by Junaid0067** [comment]
This job section is a part of open source or not?

**Comment by PeerRich** [comment]
this is a design choice
