### ISSUE TITLE
All-Day Events Don't Block Bookings

### ISSUE THREAD

**Issue by AlexIsMaking** [calcom/cal.com#11447]
### Issue Summary

When an all-day event has been added to the user's calendar with availability set to "busy", users can still book events on that day.

### Steps to Reproduce

1. Create a calendar event in Google Calendar
2. Set the time period to all-day
3. Make sure that the availability is set to busy
4. Check bookings page - timeslots on that day will still be available

### Actual Results

Users can still book events on days with all-day events

### Expected Results

Users should not be able to book events on days with all-day events

**Comment by gutogalego** [comment]
I can't replicate this. Tried it, worked out fine
<img width="440" alt="Screenshot 2023-09-20 at 5 14 39 PM" src="https://github.com/calcom/cal.com/assets/31139680/46492b6e-7d82-48e0-b09e-fc3be9376219">
<img width="1112" alt="Screenshot 2023-09-20 at 5 14 59 PM" src="https://github.com/calcom/cal.com/assets/31139680/3678e1f7-1e4d-4ff7-bd10-d91c39eb7ed3">

**Comment by AlexIsMaking** [comment]
@gutogalego apologies, I can't replicate the issue either now, I must have been mistaken.
