### ISSUE TITLE
Yarn build returns error

### ISSUE THREAD

**Issue by techguruagi** [calcom/cal.com#11457]
### Issue Summary

Trying to setup my self-hosted environment production version and yarn-build returns the following error

### Steps to Reproduce

yarn build

calcom/embed-react:build: ../../../apps/web/playwright/fixtures/bookings.ts(53,11): error TS2322: Type 'AttendeeCreateNestedManyWithoutBookingInput' is not assignable to type 'AttendeeUncheckedCreateNestedManyWithoutBookingInput | AttendeeCreateNestedManyWithoutBookingInput | undefined'.
@calcom/embed-react:build:   Type 'import("/home/livechatcm/node_html/calcom/node_modules/.prisma/client/index").Prisma.AttendeeCreateNestedManyWithoutBookingInput' is not assignable to type 'import("/home/livechatcm/node_html/calcom/packages/prisma/node_modules/.prisma/client/index").Prisma.AttendeeCreateNestedManyWithoutBookingInput'.
@calcom/embed-react:build:     Types of property 'create' are incompatible.

Appreciate your support

**Comment by Dhoni77** [comment]
Hi @techguruagi  yarn build is working fine from my end.
You can try to take the latest pull or clone the latest release.
Thanks

**Comment by PeerRich** [comment]
cant reproduce either. can you pull latest version, install docker and try `yarn dx`?
