### ISSUE TITLE
[CAL-2497] Organizer address is not showing in the confirmation email

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#11455]
* Set up organizer address as the location
* Book a meeting
* it just says "In person (Organizer Address) without the listed address in the location field

Created via Threads. See full discussion: [https://threads.com/34537580183](https://threads.com/34537580183)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2497](https://linear.app/calcom/issue/CAL-2497/organizer-address-is-not-showing-in-the-confirmation-email)</sub>

<sub>[CAL-2498](https://linear.app/calcom/issue/CAL-2498/[cal-2497]-organizer-address-is-not-showing-in-the-confirmation-email)</sub>

**Comment by PeerRich** [comment]
i think this is a security feature no? does the address get sent via email afterwards?

**Comment by imatoria** [comment]
Following are screenshots from development.

Detailed View Page: Prefilled location field visible.
![image](https://github.com/calcom/cal.com/assets/5390758/f443a9f5-7e1e-455d-8d56-0def59ea6258)

Preview Page: location field not visible.
![image](https://github.com/calcom/cal.com/assets/5390758/c8abad4b-14bc-4c0a-a789-dab0288f6d09)

**Comment by milospuac** [comment]
@PeerRich I am all for it to not appear on the public page, but there is nothing in the confirmation mail either

**Comment by milospuac** [comment]
The address needs to be in the confirmation email, and this shouldn't be low priority. Quite a lot of users affected

<img width="1130" alt="Screenshot 2023-10-06 at 10 21 40" src="https://github.com/calcom/cal.com/assets/97884287/ea7fa6eb-ace8-45bf-b83c-fca254dcc699">

**Comment by gitstart-calcom** [comment]
We checked now and we saw the correct behavior, please check this video:
https://www.loom.com/share/8851e6500b78436dbc91cba24752a3c8?sid=31a0837c-5049-4be2-8f78-e9da9f4e2294
