### ISSUE TITLE
[CAL-2506] Cant post to bookings endpoint - status 500

### ISSUE THREAD

**Issue by Matt-roki** [calcom/cal.com#11461]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cant post to bookings endpoint. I am using cal.com as the hosting but getting a 500 status with error message as "An error occured while querying the database" 

### Steps to Reproduce

1. post to https://api.cal.com/v1/bookings?apiKey=cal_live_apikey
2. An error occured while querying the database is returned.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Should book event.

### Technical details

Tested on nextjs and postman both have same result 

<sub>[CAL-2506](https://linear.app/calcom/issue/CAL-2506/cant-post-to-bookings-endpoint-status-500)</sub>

**Comment by rahul-k-srvastva** [comment]
@Matt-roki Can you please share data (request body) which you are passing in the request ?

**Comment by Matt-roki** [comment]
> @Matt-roki Can you please share data (request body) which you are passing in the request ?

`
method: 'post',
    url: 'https://api.cal.com/v1/bookings?apiKey=cal_live_MYAPIKEY',
    data: '{"responses":{"email":"customeremail","name":"Michael White","notes":"","location":{"optionValue":"","value":"HQ"},"guests":[],"product1":"Haircut","product2":"NA","product3":"NA","product4":"NA","groomsmen":"No"},"start":"2023-10-18T12:30:00","end":"2023-10-18T13:00:00","eventTypeId":410604,"eventTypeSlug":"haircut","timeZone":"Europe/London","language":"en","metadata":{},"hasHashedBookingLink":false}'
`

**Comment by tedspare** [comment]
Possibly same as #11626

**Comment by francoisvogel** [comment]
I'm also having the same issue as described above. Please can you look into it.

**Comment by keithwillcode** [comment]
Yes we are seeing intermittent issues with queries run from the API. We are looking into it

**Comment by henrymazza** [comment]
I'm seeing the same error: 
```
https://api.cal.com/v1/bookings?apiKey={{calcom_key}}
Content-Type: application/json
{
  "value": {
    "eventTypeId": 2323232,
    "start": "2023-05-24T13:00:00.000Z",
    "end": "2023-05-24T13:30:00.000Z",
    "responses": {
      "name": "Hello Hello",
      "email": "hello@gmail.com",
      "metadata": {},
      "location": "Calcom HQ"
    },
    "timeZone": "Europe/London",
    "language": "en",
    "title": "XXXXX",
    "description": null,
    "status": "PENDING",
    "smsReminderNumber": null
  }
}
```
Result
```
{
  "message": "An error occured while querying the database."
}
```

**Comment by rodgetech** [comment]
@henrymazza, were you able to solve this, I'm getting the same issue

**Comment by henrymazza** [comment]
Yes! In my case it was either a wrong `eventTypeId` or the event time in an unavailable time slot or overlaping with another event. Does it make sense?

**Comment by omunozind** [comment]
@henrymazza I am setting the start date and time, based on the available times, but I still get the same error

I have not been able to find a solution, can someone help me?

**Comment by henrymazza** [comment]
`eventTypeId`? did you create one?

**Comment by omunozind** [comment]
@henrymazza 
![image](https://github.com/calcom/cal.com/assets/62778585/8f01e197-0210-4878-830c-6140ee3064ef)

**Comment by henrymazza** [comment]
where's the end date? i'm not kidding, this code gives weird errors for basic validation... could you try it out please?

**Comment by omunozind** [comment]
`{
  "value": {
    "eventTypeId": 523258,
    "start": "2024-01-04T08:00:00.000Z",
    "end": "2023-01-04T20:00:00.000Z",
    "responses": {
      "name": "Hello Hello",
      "email": "helddlo@gmail.com",
      "metadata": {},
      "location": "Calcom HQ"},
    "timeZone": "America/Bogota",
    "language": "ES"
  }
}`

I just added it, but I still get the error, I didn't add it because it was not a required field

**Comment by omunozind** [comment]
@keithwillcode Is there anything new with this?

**Comment by outerpreneur** [comment]
I have the same issue, with the event type id and the hours matching with availability. Any hints or ideas?
`  fetch(`https://api.cal.com/v1/bookings?apiKey=${apiKey}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      start: "2024-04-24T10:00:00.000Z",
      end: "2024-04-24T10:45:00.000Z",
      eventTypeId: "641549",
      responses: {
        name: "John",
        email: "johndoe@gmail.com",
        metadata: {},
      },
      metadata: {},
      timeZone: "Europe/Zurich",
      language: "en",
      title: "XXXXX",
      description: null,
      status: "PENDING",
      smsReminderNumber: null,
    }),`

**Comment by milospuac** [comment]
@zomars Can you look into it?

**Comment by outerpreneur** [comment]
Hi @zomars , would you be able to see why I cannot create a booking . This is the current testing environment https://github.com/outerpreneur/API-testing.git and the live page https://outerpreneur.github.io/API-testing/

**Comment by milospuac** [comment]
@ThyMinimalDev can you have a look?

**Comment by virtcaio** [comment]
Getting the same error 500

**Comment by outerpreneur** [comment]
@milospuac @virtcaio @zomars ? Do you have any updates on this? We get no feedback or help

**Comment by virtcaio** [comment]
I moved to Calendly unfortunately

**Comment by Matt-roki** [comment]
I also ended up building my own system away from Cal and Calendly

**Comment by PeerRich** [comment]
Sorry, we don't somehow get notificaitons for closed issues. This should've either been reopened or a new issue to be made

**Comment by PeerRich** [comment]
![CleanShot 2024-04-10 at 10 59 05@2x](https://github.com/calcom/cal.com/assets/8019099/ccb73d9d-0dd3-4b23-adb8-5934fc8458ff)

**Comment by harrydragon1** [comment]
exact same issue again @PeerRich @milospuac @zomars @ThyMinimalDev 

also getting 	{"message":"invalid_type in 'metadata': Required"} when i fix it. passing metadata placeholder

**Comment by arnasp13** [comment]
I made the event type ID integer and it solved the problem.

But now I am getting the exact same error as @harrydragon1. Or if I move metadata out of responses object (as suggested in the API docs...), I am getting error {"message":"Invalid event length"}...

**Comment by thisisshub** [comment]
Did you find a way to make it work @Rinshin-Jalal?

**Comment by Muhammad-Ali-Saqib** [comment]
I have resolved it by making the eventTypeId to int. And it should be correct.

**Comment by horiyorrmi72** [comment]
if you make the eventTypeId typeOf Integer and it's giving you an error of metadata blah blah, you can set the metadata to an empty object "{}", then if it gives you an error of requiring the smsReminderNumber declare the smsReminderNumber within the responses data. that solved it for me.
Thanks everyone.

**Comment by cameronking4** [comment]
I keep getting:
{
    "message": "Invalid event length"
}

**Comment by horiyorrmi72** [comment]
Are you passing the eventTypeId as an integer?
