### ISSUE TITLE
UI issue on the Home page for Mobile users

### ISSUE THREAD

**Issue by Junaid0067** [calcom/cal.com#11467]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I found a UI issue on the home page for mobile or short screen.
Text and Google Calendar & Apple calender box are overlapping.

### Steps to Reproduce

1. Go to the home page on Mobile 
2. Scroll down

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Text and Google Calendar & Apple calender box are overlapping

### Expected Results

- Text and Google Calendar & Apple calender box should not overlap. 

### Evidence

![Screenshot_20230920_233125_Chrome](https://github.com/calcom/cal.com/assets/96833116/32406138-ed75-4454-a9a5-7e028acf1989)

**Comment by anirudh12032008** [comment]
I think the home page is not open source?

**Comment by PeerRich** [comment]
correct. homepage is not open source

**Comment by PeerRich** [comment]
i also dont think this is a bug either
