### ISSUE TITLE
Improve UI , Change Background color.

### ISSUE THREAD

**Issue by ReL001** [calcom/cal.com#11468]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by MeenuyD** [comment]
Hello @ReL001 I would like to work on this issue can you please more elaborate it

**Comment by ReL001** [comment]
Change background colour website

**Comment by MeenuyD** [comment]
Can you share the screenshot

**Comment by ReL001** [comment]
![Screenshot (752)](https://github.com/calcom/cal.com/assets/106170474/2334e233-a145-4cec-adb0-d68953a30be6)
Here change the background color

**Comment by MeenuyD** [comment]
I think the main page and docs of cal.com are not open-source.

**Comment by ReL001** [comment]
Ok
