### ISSUE TITLE
[CAL-2502] [CAL-2501] {MEETING_URL} variable not working

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#11479]
<img width="1232" alt="Screenshot 2023-09-21 at 16 30 37" src="https://github.com/calcom/cal.com/assets/97884287/fc8d12cf-acf0-4bdf-a202-96bcca8b9fc1">
<img width="812" alt="Screenshot 2023-09-21 at 16 30 55" src="https://github.com/calcom/cal.com/assets/97884287/e60d34ac-7f3e-4790-a40f-77aa22b6b6a6">

Created via Threads. See full discussion: [https://threads.com/34537950555](https://threads.com/34537950555)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2501](https://linear.app/calcom/issue/CAL-2501/meeting-url-variable-not-working)</sub>

<sub>[CAL-2502](https://linear.app/calcom/issue/CAL-2502/[cal-2501]-meeting-url-variable-not-working)</sub>

**Comment by rahul-k-srvastva** [comment]
Can you please provide steps to reproduce the issue ?

So far I have tried with meeting URLs of Google Meet, Cal Video and custom URLs. All are working fine.
Also, the discussion link is not working for me.

**Comment by Dhoni77** [comment]
Hi In docs, it is mentioned that
**_If the location is a video conferencing app then the {LOCATION} would be ‘Zoom’ or ‘Google Meet’ and {MEETING_URL} would be the actual link to the meeting. If the location is not a video conferring app then {MEETING_URL} is empty._**
https://cal.com/docs/enterprise-features/workflows#dynamic-text-variables

**Comment by pranavburnwal** [comment]
I am using MS Teams, workflow sends 'new' meeting url's with reminder emails.

**Comment by milospuac** [comment]
@Dhoni77 Thank you for quoting the doc that we wrote :) 

I had Google Meet linked to that event type and wanted the URL to the meeting to show in the workflow. It didn't but after recreating the workflow it started working again. Will close this.
