### ISSUE TITLE
[CAL-2504] Prefilled needs name first to not ignore other query params

### ISSUE THREAD

**Issue by askasp** [calcom/cal.com#11488]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.
If you prefill data in the url you need to add the name as a query param first, else the res is ignored

### Steps to Reproduce

https://cal.com/askasp/samma?userid=samma  <- does not work
https://cal.com/askasp/samma?name=hei&userid=samma   <- does work.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected
- right now userid is not prefilled without having name, im expecting it to be

<sub>[CAL-2504](https://linear.app/calcom/issue/CAL-2504/prefilled-needs-name-first-to-not-ignore-other-query-params)</sub>

**Comment by PeerRich** [comment]
maige ignore the "❗️invalid" label

**Comment by PeerRich** [comment]
@hariombalhara can take a look, tho slightly lower priority

**Comment by nilsreichardt** [comment]
I have the same issue. As an additional note: It does not need `name` be the first the argument. `name` needs to be somewhere and then it works:

https://cal.com/askasp/samma?userid=samma <- does not work
https://cal.com/askasp/samma?name=hei&userid=samma <- does work
https://cal.com/askasp/samma?userid=samma&name=hei <- does work

**Comment by hariombalhara** [comment]
@nilsreichardt @askasp Thanks for reporting. It's fixed in #11418 but yet to be merged. There are some unit tests as well in there for the flow that had this bug.
