### ISSUE TITLE
[CAL-2505] cal.com completely crashes when I try to login

### ISSUE THREAD

**Issue by janoschsworkspace** [calcom/cal.com#11480]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When I try to log in with my email (SSO through Google). I briefly see the cal.com loading screen, but then everything just completely blacks out. I wanted to contact support, but I can't access anything inside the app. 

### Steps to Reproduce

1. Go to cal.com
2. Log in with my account through Google (can't share details here)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
Here's what I see when I open the site:
<img width="1507" alt="Bildschirm­foto 2023-09-21 um 16 04 41" src="https://github.com/calcom/cal.com/assets/52420424/412c1370-ae49-4950-b2d4-f16b110eaf5f">

### Actual Results
The site completely blacks out

### Expected Results
I should be able to access my cal.com account normally

### Technical details
I'm on the latest version of Chrome as of the time of writing this, but this issue has occurred in earlier versions as well. See screenshot above for console.log.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>[CAL-2505](https://linear.app/calcom/issue/CAL-2505/calcom-completely-crashes-when-i-try-to-login)</sub>

**Comment by Narottamchy** [comment]
can please explain this issue because testing this on my local system and on the website it's working fine??

**Comment by RamK777-stack** [comment]
is dark mode enabled in your system? @janoschsworkspace

**Comment by jayesh77-ai** [comment]
@janoschsworkspace it's working completely fine dude. I cross-checked your screenshot that you have attached and I can see that there is hex-color issue that means it may be you have enabled dark mode on your system.

**Comment by janoschsworkspace** [comment]
@Narottamchy Hey, tbh I don't know how to give additional context, I tried to describe everything I experienced in the original bug report. If it helps, here's a quick Loom that showcases what happens when I try to access my account: https://www.loom.com/share/cde2224b4fb4439fbe2764a80d1a44d5?sid=1015093b-a969-4608-94e4-f0c0efc1845f

**Comment by jayesh77-ai** [comment]
Hey @janoschsworkspace can you please try with any other browser once?

**Comment by janoschsworkspace** [comment]
@jayesh77-ai Sure, tried with Firefox, but same issue: 
<img width="1508" alt="Bildschirm­foto 2023-09-26 um 11 34 00" src="https://github.com/calcom/cal.com/assets/52420424/761c9f5c-3d04-4ad0-a792-9dedef49b14f">

**Comment by janoschsworkspace** [comment]
Maybe it's related to my account? I'd rather not share my email here, but if it helps, I can share it with the team privately.

**Comment by keithwillcode** [comment]
@janoschsworkspace Looks like we have a PR up to fix this. Should be released today/tomorrow.

**Comment by janoschsworkspace** [comment]
Works now, thank you!
