### ISSUE TITLE
Cal.com booking page crash on Chrome

### ISSUE THREAD

**Issue by paul-phan** [calcom/cal.com#11501]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

My booking page crashes on Chrome but works fine on Safari and Chrome Mobile even after trying Incognito mode.

### Technical details

- Chrome version 116 (latest)

### Evidence

![crash on chrome](https://cdn.shopify.com/s/files/1/0613/8383/5877/files/Screenshot_2023-09-24_at_23.04.42.png?v=1695571985)
![code](https://cdn.shopify.com/s/files/1/0613/8383/5877/files/Screenshot_2023-09-24_at_23.04.55.png?v=1695572039)
![work normal on safari](https://cdn.shopify.com/s/files/1/0613/8383/5877/files/Screenshot_2023-09-24_at_23.05.13.png?v=1695572074)

**Comment by The-Robin-Hood** [comment]
Tried with different version of Chrome. Couldn't able to reproduce the issue.

**Comment by jayesh77-ai** [comment]
Tried the same  @paul-phan it is working fine for me. Have you tried it once by clearing your caches/cookies?

**Comment by PeerRich** [comment]
works fine for me https://cal.com/paulphan/weaverse
