### ISSUE TITLE
Manage room bookings via virtual Accounts

### ISSUE THREAD

**Issue by eiclu** [calcom/cal.com#11515]
### Is your proposal related to a problem?

We want to coordinate room reservations via cal.com (Selfhosted). As far as I see bookings are always associated with a person. This is kind of annoying, because then we need separate credentials for each room, including email, which we have to create for the room, and a password, which multiple people managing the room then have to share.

### Describe the solution you'd like

We would like a type of account, which is managed by other accounts and cannot login. When creating you would be able to select which people may access this account from their profile and which permissions they have. You would then be able to select this account in the profile dropdown in the top left.

### Describe alternatives you've considered

Right now we create accounts for the rooms and then share the credentials between the managing people. But that seems clunky for all the reasons listed above.

**Comment by PeerRich** [comment]
we are not moving into "resource" scheduling anytime soon given its an entire new space for us, so its unlikely we'll look into this anytime soon. if we do, likely in the "platform" product
