### ISSUE TITLE
Dynamic pricing for each service

### ISSUE THREAD

**Issue by lozano312** [calcom/cal.com#11513]
It would be amazing to include dynamic prizes based on the selected custom fields.

When creating a custom fields, you can select whether the client chooses that option that increases or decreases the final price. For example when selecting the language or the number of participants. Add extras, etc.

Also possibility of paying in advance, only a percentage or option to pay on the premises.

**Comment by PeerRich** [comment]
pretty big feature, i recommend using different event-types with different prices for now
