### ISSUE TITLE
Button unresponsive

### ISSUE THREAD

**Issue by akhilrocz** [calcom/cal.com#11526]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Button not navigating to next page when clicked for the first time.

### Steps to Reproduce

1. Go to the home(app.cal.com/getting-started) page.
2.Click on the "Next Step" button.
3. Observe that the page does not navigate to the next page.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

-The page doesn't navigate to next page

### Expected Results

-I expect the page should navigate to the next page when clicked for the first time

https://github.com/calcom/cal.com/assets/118684885/890e0db2-ae77-4013-a6cc-0efd34244ba9

**Comment by JatinBawne** [comment]
it is working for me.

https://github.com/calcom/cal.com/assets/99788083/13683e6f-157c-4ea8-8b9f-21930c7530d5

**Comment by akhilrocz** [comment]
@JatinBawne I have checked in mobile also it is not working for me when i clicked for first time,for the second or third time it is working

**Comment by AshishKumar409** [comment]
https://github.com/calcom/cal.com/assets/76529660/8975754b-061d-4791-963f-c9c0b4b19682

@akhilrocz it's working on first click, but i think the "Next Step" button should not enable until the page navigated to next page

**Comment by Ayushkkkkkkk** [comment]
I also had this error a while ago but worked after several clicks

**Comment by akhilrocz** [comment]
@Ayushkkkkkkk I mean it's like after 2 or 3 clicks right?

**Comment by akhilrocz** [comment]
@AshishKumar409 @JatinBawne Although it has some issue,it worked for me now.

**Comment by mohit-sankhla2002** [comment]
I think it's alright it just takes a few seconds to propogate to the next tab of the getting-started form. It works for me I just waited like 4-5 seconds.
