### ISSUE TITLE
[CAL-2524] Inbound Webooks from gCal

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#11524]
[https://developers.google.com/calendar/api/guides/push](https://developers.google.com/calendar/api/guides/push)

This will allow us to keep the cache up to date in an async manner. That way we can serve the cache first with more confidence on it's freshness.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2524](https://linear.app/calcom/issue/CAL-2524/inbound-webooks-from-gcal)</sub>

**Comment by skmanoj322** [comment]
@keithwillcode @zomars  hope these is not an internal issue.looks intersting

**Comment by zomars** [comment]
> i am planning to initilize google calenders WATCH in add.ts in googlecalendar app. and create sepreate webhook to watch any changes in calendar. but the problem is what about the user that are already installed the google calendar? @zomars @keithwillcode your response is valuable

There already work in progress here: https://github.com/calcom/cal.com/pull/11928

> but the problem is what about the user that are already installed the google calendar?

For this we could either notify the user to require user action in order to opt-in for this. Or we can come up with some kind of gradual migration via an endpoint that process a batch of users under a CRON until it's finished.
