### ISSUE TITLE
team: lowercasing of username not working

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#11532]
Found a bug? Please fill out the sections below. 👍

### edit by @PeerRich 

- https://cal.com/team/CrowdDotDev/community-strategy works
- https://cal.com/team/CrowdDotDev throws 404
- we need to allow different casing. we already do the same for individuals links where we allow cal.com/Peer and cal.com/Peer/30min

### Issue Summary

When I tried to open some team page it shows that it's not found, and direct to the cal.com team page. 

### Steps to Reproduce

1. Visit: https://cal.com/team/CrowdDotDev/community-strategy
2. Change the link to: https://cal.com/team/CrowdDotDev 
![image](https://github.com/calcom/cal.com/assets/18273833/5c5f011e-1453-4fc4-b1c8-2e365ca05767)

**Comment by Udit-takkar** [comment]
This link loads https://cal.com/team/crowddotdev

**Comment by PeerRich** [comment]
yeah seems like there are issues with the lack of lowercasing

**Comment by a0m0rajab** [comment]
Thanks for the information 🙏
