### ISSUE TITLE
[CAL-2526] new 404 page for teams: https://cal.com/team/does-not-exist

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11537]
- [ ]  remove "cal.com" before team name

![CleanShot 2023-09-26 at 21 33 48@2x](https://github.com/calcom/cal.com/assets/8019099/4434d981-d92b-46fa-b864-f90bcb2c299f)

<sub>[CAL-2526](https://linear.app/calcom/issue/CAL-2526/new-404-page-for-teams-httpscalcomteamdoes-not-exist)</sub>

**Comment by krishkdev** [comment]
Hi @PeerRich , is this issue still open?

**Comment by ashish1233** [comment]
hi @krishkdev, @Dhoni77 has linked the PR, his changes looks good to me.

cc : @PeerRich
