### ISSUE TITLE
[CAL-2528] Round Robin Rescheduling reschedules to the previous user's calendar instead of to the new user.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11547]
Rescheduling a round-robin booking(which has a calendar Event in User-1’s calendar and User-1 has been chosen for the booking) changes the attendee from User-1 to User-2 in the existing calendar event(which is actually User-1’s calendar). 
This way the Calendar event is still blocking the slot for User-1 and thus rescheduling a round-robin to a particular slot effectively blocks that timeslot for both users - I observed this behavior with Google Calendar.

Ideally the calendar event should be moved to User-2’s calendar. 

																								

<sub>[CAL-2528](https://linear.app/calcom/issue/CAL-2528/round-robin-rescheduling-reschedules-to-the-previous-users-calendar)</sub>

**Comment by sajanlamsal** [comment]
Hello, @keithwillcode @PeerRich  @hariombalhara 
Could you provide an update on the issue regarding the fluctuating release version? It's impacting our workflow significantly. Last I checked with support, a fix was said to be on the way soon. Any news on this would be greatly appreciated.
