### ISSUE TITLE
[CAL-2604] Priority Ranking for Members in Round Robin Events

### ISSUE THREAD

**Issue by its-julian** [calcom/cal.com#11545]
### Is your proposal related to a problem?

(Running a remote sales team, I'm always monitoring who the high-performers are on the team so I can send more calls into their calendars & less into the newly onboarded salesreps. 

When everyone is on the same calendar, round-robin style - it's super important we're able to prioritize the best team members. So they get inbound calls first, and then when their calendar is full it moves to the next person on the priority list.)

### Describe the solution you'd like

(Simply add a Star or "Score" rating inside of the event, next to the attached members - so we can prioritize members by order of importance on each event. 

Ideally this is also accessible through the API, so we can automatically update member priority on our sales calendar based on indicators we're measuring in our back-end business systems.)

### Describe alternatives you've considered

(Other scheduling tools like Calendly, but the issue is their prioritization is very limiting... it only has a rank of 1-3, and no API access so it's not useful with larger teams - especially when trying to automate it.)

<sub>[CAL-2604](https://linear.app/calcom/issue/CAL-2604/priority-ranking-for-members-in-round-robin-events)</sub>

**Comment by PeerRich** [comment]
this is planned!
