### ISSUE TITLE
[CAL-2530] Zoho Calendar - Rescheduling error if booking is deleted directly on Zoho Calendar

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11549]
<img width="757" alt="Screenshot 2023-09-25 at 1 10 14 PM" src="https://github.com/calcom/cal.com/assets/1780212/7765925c-2674-4087-a3b2-6d24f139e644">
If for the booking being rescheduled in Cal.com, Zoho calendar event doesn't exist due to some reason(I deleted that in my case), there comes an error in rescheduling the event on Zoho.

I think we should handle it gracefully, by creating the event on rescheduled time.
Though not a blocker, we can create a ticket for it and work on it later.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/10429#discussion_r1335503702_
            

<sub>[CAL-2530](https://linear.app/calcom/issue/CAL-2530/zoho-calendar-rescheduling-error-if-booking-is-deleted-directly-on)</sub>

**Comment by ankit10000** [comment]
can i resolve this issue
