### ISSUE TITLE
[CAL-2529] Zoho Calendar integration throws error when I enable 'Show me busy during non-work hours option', reason being the date format sent by Zoho changes in that case.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11548]
This throws error when I enable 'Show me busy during non-work hours option', reason being the date format sent by Zoho changes in that case.
![image](https://github.com/calcom/cal.com/assets/1780212/b5222e45-54b9-4513-9174-3729e455252d)
<img width="1117" alt="Screenshot 2023-09-25 at 1 01 22 PM" src="https://github.com/calcom/cal.com/assets/1780212/2d29ac1f-5687-403b-bdb9-1fcdd9c332a8">

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/10429#discussion_r1335494085_
            

<sub>[CAL-2529](https://linear.app/calcom/issue/CAL-2529/zoho-calendar-integration-throws-error-when-i-enable-show-me-busy)</sub>

**Comment by vndpal** [comment]
I don't see Zoho Calendar available at the app store. is zoho calendar released on the live cal.com? 
![image](https://github.com/calcom/cal.com/assets/39481600/d8273090-66a4-4e62-8e26-a824294264e9)

**Comment by NicksonYap** [comment]
this error happens as well if we are to set "All day" events

**Comment by NicksonYap** [comment]
packages/app-store/zohocalendar/lib/CalendarService.ts

The issue is due to non-handling of the format "YYYYMMDD[T]" (missing time)
Fix:

Before
```js

    return (
      data.freebusy
        .filter((freebusy: FreeBusy) => freebusy.fbtype === "busy")
        .map((freebusy: FreeBusy) => ({
          // using dayjs utc plugin because by default, dayjs parses and displays in local time, which causes a mismatch
          start: dayjs.utc(freebusy.startTime, "YYYYMMDD[T]HHmmss[Z]").toISOString(),
          end: dayjs.utc(freebusy.endTime, "YYYYMMDD[T]HHmmss[Z]").toISOString(),
        })) || []
    );
```
After
```js
    return (
      data.freebusy
        .filter((freebusy: FreeBusy) => freebusy.fbtype === "busy")
        .map((freebusy: FreeBusy) => ({
          // using dayjs utc plugin because by default, dayjs parses and displays in local time, which causes a mismatch
          start: dayjs.utc(freebusy.startTime, ["YYYYMMDD[T]HHmmss[Z]", "YYYYMMDD[T]"]).toISOString(),
          end: dayjs.utc(freebusy.endTime, ["YYYYMMDD[T]HHmmss[Z]", "YYYYMMDD[T]"]).toISOString(),
        })) || []
    );
```
