### ISSUE TITLE
[CAL-2581] Embed breaks back button behavior on react/next.js sites

### ISSUE THREAD

**Issue by ankrgyl** [calcom/cal.com#11558]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you embed cal.com into a next.js/react site, eg it breaks the back button. This is a well known issue that can be solved by placing the `key` prop in the `iframe` (see https://github.com/vercel/next.js/issues/8107)

### Steps to Reproduce

```
    <Cal
      calLink="<YOUR LINK>"
      style={{ width: "100%", height: "100%", overflow: "scroll" }}
      config={{
        layout: "month_view",
      }}
    />
```

### Actual Results

If you hit back in the browser, nothing happens. You need to hit back a few times (presumably to undo the history stack introduced by the cal.com iframe).

### Expected Results

Hitting back in the browser should navigate to the previous page

### Technical details

Next.js/vercel 13.4

### Evidence

This was tested by integrating cal.com into our website and observing that "back" in the browser does not seem to work. This is on an unreleased website at the moment, but if needed, I can send a video in the next few days.

<sub>[CAL-2581](https://linear.app/calcom/issue/CAL-2581/embed-breaks-back-button-behavior-on-reactnextjs-sites)</sub>

**Comment by ItIsOHM** [comment]
Hey there maintainers, i'm new to Cal and would like to start working on this issue.
I'll set-up the dev environment and will get back to you ASAP :)

**Comment by ItIsOHM** [comment]
I added a key value to the props passed, but I'm stuck if it should be modified in the Cal function. I'd love the help from the maintainers or other contributors as I'm a beginner here :)

**Comment by OD91** [comment]
Ah, have the same issue --> #https://github.com/calcom/cal.com/issues/11672

**Comment by 5war00p** [comment]
@PeerRich Fixed this and raised a PR.

**RCA**:
Iframe shares browsers history stack. As we are using same iframe and replacing the `src` content, going back & forth results in navigation within iframe content instead of main page. 

**Solution**:
To solve this, we need to re-create new iframe for every distinct content, so that it won't touch history stack, as we are using reactjs, by passing `key` as prop the react reconciliation process treats as new element and remounts it again which prevent pushing into browser stack.

**Comment by OD91** [comment]
It's still not working for us. The browser behaviour is not acceptable for our customers. either it will be fixed immediately or we can unfortunately no longer use Cal, but an alternative like Calendly... What is the issue?

**Comment by 5war00p** [comment]
@PeerRich Look into my closed PR once: https://github.com/calcom/cal.com/pull/11755, which sets a key to the iframe as Iframe shares browser history, and that messes up navigating pages back & forth if the same iframe is reused. To solve this, we need to recreate the iframe for every src url, as we are using react by passing key prop react DOM interprets it as new element and it solves problem. But the merged PR missed this at one more place, which I added in my PR: https://github.com/calcom/cal.com/pull/11755. This might fix the issue.

**Comment by OD91** [comment]
Don't understand; can you provide me with a updated code snippet that I can use to fix it?

**Comment by OD91** [comment]
For us this ticket is still unsolved?! any udpate? why is this one closed?

**Comment by sarah-inkeep** [comment]
I am also still having this issue with the latest package.

**Comment by OD91** [comment]
Any Update?
