### ISSUE TITLE
[CAL-2531] add tests for Event Type filter

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#11553]
Regression:-  https://github.com/calcom/cal.com/issues/11550

<sub>[CAL-2531](https://linear.app/calcom/issue/CAL-2531/add-tests-for-event-type-filter)</sub>

**Comment by bhargavagonugunta** [comment]
hi @Udit-takkar can you please look in to my PR I made changes accordingly

 
Thanks in Advance

**Comment by Udit-takkar** [comment]
@bhargavagonugunta this issue is for writing automated tests. i don't see any tests in your PR
