### ISSUE TITLE
Block/Restrict e,-,+ for number input fields for Event Type page

### ISSUE THREAD

**Issue by MauryanKansara** [calcom/cal.com#11555]
Found a bug? Please fill out the sections below. 👍

At Event Type page while creating a new event or editing an event, we are able to enter e,-,+ for "duration" field. Duration field accepts only number so we should block/restrict user from entering these characters.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. go to the "Event Types" page
2. Create a new event or edit an existing event
3. enter e,-,+ for duration field and try saving those changes.

### Actual Results

https://github.com/calcom/cal.com/assets/86093112/82363877-8ed8-49bb-96eb-1fd93a183493

### Expected Results
We should be able to block/restrict user from entering those characters instead of showing them error message.

**Comment by MauryanKansara** [comment]
And also I'm working on this issue.

**Comment by SomayChauhan** [comment]
this might be browser specific,
working fine on chrome

**Comment by MauryanKansara** [comment]
> this might be browser specific, working fine on chrome

yeah but in some browser it is showing error messages so I thought it would be better if we make it consistent across all the browsers.
