### ISSUE TITLE
[CAL-2532] install app dropdown way too large

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11561]
should only be as wide as the content

https://github.com/calcom/cal.com/assets/8019099/6342e962-d22e-426b-919f-a79b4a4acc33

![CleanShot 2023-09-27 at 22 38 48@2x](https://github.com/calcom/cal.com/assets/8019099/c2bad569-3e69-424d-8364-2a30bafdd10c)

<sub>[CAL-2532](https://linear.app/calcom/issue/CAL-2532/install-app-dropdown-way-too-large)</sub>

**Comment by Tanush-J** [comment]
I am not getting the same issue on gitpod setup

<img width="959" alt="image" src="https://github.com/calcom/cal.com/assets/75922615/46cde41f-1947-4efe-bf0e-09a15df28391">
