### ISSUE TITLE
[CAL-2533] Booking failure in some payment requiring event for some payment app

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11572]
Seeing this error in axiom recently that would be failing the bookings for these Paid events in whatever the case - Actionable: Catch the errors from calling collectCard and create and log them properly, with the name of the PaymentService and other things.

![image](https://github.com/calcom/cal.com/assets/1780212/06e9d079-4454-45f7-a9c8-dacb94b38204)

<sub>[CAL-2533](https://linear.app/calcom/issue/CAL-2533/booking-failure-in-some-payment-requiring-event-for-some-payment-app)</sub>

**Comment by hariombalhara** [comment]
@alannnc Could it be the new payment app that hasn't been configured properly.

**Comment by alannnc** [comment]
Yeah definitely something related, but I think it's a non blocker. Will fix it shortly. Thanks @hariombalhara

**Comment by alannnc** [comment]
After a dive in the code this error belongs to paypal, but we just recently switched out credentials.parse for -> .safeParse due to this error being printed out. It's been a few days since it has stopped appearing, can we close at the end of the week if it doesn't pop up again?

**Comment by hariombalhara** [comment]
I am closing it. Will reopen if I see it again as I analyze errors on daily basis
