### ISSUE TITLE
[CAL-2541] Fix the UX/UI of our filters on the booking page

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#11586]
**Current problem**

The current filters jump between left and right aligned on tablet vs desktop and don't align with design.

**Solution**

Match the filter UI/UX to Figma.

[View in Figma](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=7869%3A93929&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2541](https://linear.app/calcom/issue/CAL-2541/fix-the-uxui-of-our-filters-on-the-booking-page)</sub>

**Comment by bhargavagonugunta** [comment]
hi @ciaranha can i develop another page

**Comment by davidnoelopez** [comment]
Hi, can I work in this issue?

**Comment by arjavsethi** [comment]
![image](https://github.com/calcom/cal.com/assets/75158301/46510d22-0273-436a-bf4e-106c6d11f0c2)
![image](https://github.com/calcom/cal.com/assets/75158301/ea978ed3-f7e4-4ca8-800d-943bdca41237)
This two dropdowns / buttons are the same right @Udit-takkar  ?
Above image is from figma and below one is from my local

**Comment by davidnoelopez** [comment]
Hey I probably should have waited for a reply to work on this 😅 
but I had time yesterday and worked on this. Let me know if the PR is ok, or if I need to change something.

If the bookings is ok I can work in the Insights and Routing Forms filters too.

**Comment by officialsachin4** [comment]
Hi,
You can work on that.

Thanks,
Sachin Sharma

**Comment by amitabh-sahu** [comment]
Hi, can I work on this?

**Comment by officialsachin4** [comment]
Yes, you can do that.

Thanks,
Sachin Sharma

**Comment by Samrj12** [comment]
@ciaranha Is this still open?

**Comment by TanujResp** [comment]
@ciaranha Is this PR is still workable as it seems as the UI changes are done in it

**Comment by priyansu12** [comment]
I would like to contribute! if anyone is not working on it

**Comment by officialsachin4** [comment]
I would be happy to contribute.
