### ISSUE TITLE
[CAL-2539] feat: ability to use one "." inside a username

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11581]
allowing "." would mean we can auto convert: [leo.giovanetti@acme.com](mailto:leo.giovanetti@acme.com) to [acme.cal.com/leo.giovanetti](http://acme.cal.com/leo.giovanetti) for Enterprise/Org users

## requirements

* username cannot start or end with "."
* no limits of "."
* cannot have two dots ".."
* ~~**maybe?** we need to introduce a banlist for file extensions (.exe, .jpg, .svg, etc.)~~

see google:

![CleanShot 2023-09-28 at 13 23 21@2x](https://github.com/calcom/cal.com/assets/8019099/6504a34c-343e-4263-94cc-9577ce8530bf)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2539](https://linear.app/calcom/issue/CAL-2539/feat-ability-to-use-one-inside-a-username)</sub>

**Comment by PeerRich** [comment]
i dont even know if we really need a banlist. Instagram for example allows .exe as username: https://instagram.com/john.exe I wouldn't know why we wanna ban it

**Comment by PeerRich** [comment]
what is the spec for email usernames? we should use the same validation

found this:
https://serverfault.com/questions/395766/are-two-periods-allowed-in-the-local-part-of-an-email-address

**Comment by AbdulBasit2733** [comment]
@PeerRich Hi sir, i am new to openSource so will please tell me where should i find this in the repo directory.
