### ISSUE TITLE
Error to install Stripe App

### ISSUE THREAD

**Issue by giovannicocco** [calcom/cal.com#11582]
When I tried to install Stripe App I got some zod error. I already add all my stripe env variables. Some help?

@calcom/web:dev: [PERF]: getByViewer(1) took 187.01046100258827ms
@calcom/web:dev: API handler should not return a value, received object.
@calcom/web:dev: API handler should not return a value, received object.
@calcom/web:dev: [
@calcom/web:dev:   {
@calcom/web:dev:     "code": "invalid_type",
@calcom/web:dev:     "expected": "string",
@calcom/web:dev:     "received": "undefined",
@calcom/web:dev:     "path": [
@calcom/web:dev:       "client_id"
@calcom/web:dev:     ],
@calcom/web:dev:     "message": "Required"
@calcom/web:dev:   },
@calcom/web:dev:   {
@calcom/web:dev:     "code": "invalid_type",
@calcom/web:dev:     "expected": "string",
@calcom/web:dev:     "received": "undefined",
@calcom/web:dev:     "path": [
@calcom/web:dev:       "client_secret"
@calcom/web:dev:     ],
@calcom/web:dev:     "message": "Required"
@calcom/web:dev:   },
@calcom/web:dev:   {
@calcom/web:dev:     "code": "invalid_type",
@calcom/web:dev:     "expected": "string",
@calcom/web:dev:     "received": "undefined",
@calcom/web:dev:     "path": [
@calcom/web:dev:       "public_key"
@calcom/web:dev:     ],
@calcom/web:dev:     "message": "Required"
@calcom/web:dev:   },
@calcom/web:dev:   {
@calcom/web:dev:     "code": "invalid_type",
@calcom/web:dev:     "expected": "string",
@calcom/web:dev:     "received": "undefined",
@calcom/web:dev:     "path": [
@calcom/web:dev:       "webhook_secret"
@calcom/web:dev:     ],
@calcom/web:dev:     "message": "Required"
@calcom/web:dev:   },
@calcom/web:dev:   {
@calcom/web:dev:     "code": "invalid_type",
@calcom/web:dev:     "expected": "number",
@calcom/web:dev:     "received": "undefined",
@calcom/web:dev:     "path": [
@calcom/web:dev:       "payment_fee_fixed"
@calcom/web:dev:     ],
@calcom/web:dev:     "message": "Required"
@calcom/web:dev:   },
@calcom/web:dev:   {
@calcom/web:dev:     "code": "invalid_type",
@calcom/web:dev:     "expected": "number",
@calcom/web:dev:     "received": "undefined",
@calcom/web:dev:     "path": [
@calcom/web:dev:       "payment_fee_percentage"
@calcom/web:dev:     ],
@calcom/web:dev:     "message": "Required"
@calcom/web:dev:   }
@calcom/web:dev: ]
@calcom/web:dev:     at get error [as error] (file:///Users/giovannicocco/Documents/Sites/calcom/node_modules/zod/lib/index.mjs:538:31)
@calcom/web:dev:     at ZodObject.parse (file:///Users/giovannicocco/Documents/Sites/calcom/node_modules/zod/lib/index.mjs:638:22)
@calcom/web:dev:     at getParsedAppKeysFromSlug (webpack-internal:///(api)/../../packages/app-store/_utils/getParsedAppKeysFromSlug.ts:13:19)
@calcom/web:dev:     at async handler (webpack-internal:///(api)/../../packages/app-store/stripepayment/api/add.ts:20:27)
@calcom/web:dev:     at async handler (webpack-internal:///(api)/./pages/api/integrations/[...args].ts:88:13) {
@calcom/web:dev:   issues: [
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'number',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'number',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     }
@calcom/web:dev:   ],
@calcom/web:dev:   addIssue: [Function (anonymous)],
@calcom/web:dev:   addIssues: [Function (anonymous)],
@calcom/web:dev:   name: 'ZodError',
@calcom/web:dev:   errors: [
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'string',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'number',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     },
@calcom/web:dev:     {
@calcom/web:dev:       code: 'invalid_type',
@calcom/web:dev:       expected: 'number',
@calcom/web:dev:       received: 'undefined',
@calcom/web:dev:       path: [Array],
@calcom/web:dev:       message: 'Required'
@calcom/web:dev:     }
@calcom/web:dev:   ]
@calcom/web:dev: }
@calcom/web:dev: API handler should not return a value, received object.
@calcom/web:dev: API handler should not return a value, received object.

**Comment by arjavsethi** [comment]
@giovannicocco how did you solved this issue?

**Comment by giovannicocco** [comment]
@arjavsethi You need to add the Stripe keys to .env and .env.appStore and run the command **yarn workspace @calcom/prisma db-migrate**.

In my case I had run the command yarn workspace @calcom/prisma db-migrate **before** adding the keys so I needed to delete the tables and run it again after adding the keys. Just running the command does not update the keys, you need to delete the tables.

**Comment by arjavsethi** [comment]
Thanks for your response , I am still getting the error  do you know anywhere it is documented

**Comment by tauseedzaman** [comment]
I am getting this error , any idea?
![image](https://github.com/calcom/cal.com/assets/64689921/ef07f031-6c2a-44da-8c83-35a86c29cbed)

**Comment by alexsbferreirawinflow** [comment]
https://github.com/calcom/cal.com/issues/9699
