### ISSUE TITLE
[CAL-2544] chore: "install" on dropdown needs min-width for children and left-align

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11597]
![CleanShot 2023-09-28 at 21 37 14@2x](https://github.com/calcom/cal.com/assets/8019099/16fa4e1f-d258-4055-83d7-d84b379d25ab)

<sub>[CAL-2544](https://linear.app/calcom/issue/CAL-2544/chore-install-on-dropdown-needs-min-width-for-children-and-left-align)</sub>

**Comment by bhargavagonugunta** [comment]
hi @PeerRich can you please look in to this 
<img width="1512" alt="Screenshot 2023-09-29 at 3 12 40 AM" src="https://github.com/calcom/cal.com/assets/118610174/e53e8b5e-9163-425d-b262-14fa04965f44">
and 
<img width="1512" alt="Screenshot 2023-09-29 at 3 18 02 AM" src="https://github.com/calcom/cal.com/assets/118610174/20afef0a-10d8-4834-8a69-2bbcf11c2e92">
