### ISSUE TITLE
[CAL-2547] chore: a few more settings improvements

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11601]
* \[ \]
* \[X\]
* \[X\]
* \[X\]
* [X] subtitles are different (not sure which one is correct)

![CleanShot 2023-09-28 at 23 46 21@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/86dbd185-b47f-4f39-a761-e0539b5469b0/6a7e3875-6b3a-40e2-a987-05439d58fb6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84NmRiZDE4NS1iNDdmLTRmMzktYTc2MS1lMDUzOWI1NDY5YjAvNmE3ZTM4NzUtNmIzYS00MGUyLWE5ODctMDU0MzlkNThmYjZhIiwiaWF0IjoxNzAxNzkxNTk5LCJleHAiOjE3MDE4Nzc5OTl9.MFwRnQpWtFs-m1CdjHwRd8U3UQ6DaJ_ZwDkPqPJBhjE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2547](https://linear.app/calcom/issue/CAL-2547/chore-a-few-more-settings-improvements)</sub>

**Comment by MeetM15** [comment]
Hey! I was looking to work on this @Udit-takkar  , can you describe the requirements for this issue ?

**Comment by Udit-takkar** [comment]
@MeetM15 This issue is old. I already made these changes.
