### ISSUE TITLE
[CAL-2556] Integration tests for Payment failures

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11629]
Integration tests for Payment failures.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2556](https://linear.app/calcom/issue/CAL-2556/integration-tests-for-payment-failures)</sub>

**Comment by hariombalhara** [comment]
@alannnc I will identify a few scenarios, but could you suggest some failure tests.

**Comment by alannnc** [comment]
Mmm I think my comment was more related to the newly integration test created but to force some state error on those. Not exclusively fails on payment flow.

But what you want is to test some failed scenarios, we can simulate a fail when creating payment/order when triggering the PaymentService.ts should that stop handleNewBooking and rollback?
