### ISSUE TITLE
[CAL-2557] new cal video logo

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11631]
![icon](https://github.com/calcom/cal.com/assets/8019099/99095c03-4fee-4341-bd4a-417c88803ac6)

<sub>[CAL-2557](https://linear.app/calcom/issue/CAL-2557/new-cal-video-logo)</sub>

**Comment by aaditya9899** [comment]
hey can i work on this

**Comment by PeerRich** [comment]
already on it, thanks
