### ISSUE TITLE
[CAL-2558] remove feature flag for "new booker"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11632]
since old booking page does no longer exist

* remove feature flag
* clean up code

![CleanShot 2024-01-04 at 17 54 26@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6a6ac76a-25c3-446b-a912-6a6da655df0d/170cc5ae-8623-4b4f-9c4c-a3532187907f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82YTZhYzc2YS0yNWMzLTQ0NmItYTkxMi02YTZkYTY1NWRmMGQvMTcwY2M1YWUtODYyMy00YjRmLTljNGMtYTM1MzIxODc5MDdmIiwiaWF0IjoxNzA0MzkwODk5LCJleHAiOjE3MDQ0NzcyOTl9.U4p6xq65UXKYHTdbop1Vh677ie6KxXPnKH6z1mlVG10)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2558](https://linear.app/calcom/issue/CAL-2558/remove-feature-flag-for-new-booker)</sub>

**Comment by Dhoni77** [comment]
Hi @PeerRich the linear link shows that I don't have access where can I request access from ?

**Comment by prithvi009** [comment]
HI @PeerRich , I'm trying to address this issue.
<img width="784" alt="Screenshot 2023-10-03 at 11 26 40 PM" src="https://github.com/calcom/cal.com/assets/96919987/49f20725-bc73-4f58-890e-520897d950fd">
can you provide the access to me ?
