### ISSUE TITLE
Unable to modify the location of a booking when rescheduling

### ISSUE THREAD

**Issue by sebastianquek** [calcom/cal.com#11650]
### Issue Summary

Having set a event's location to be "In Person (Attendee Address)", trying to modify it during a reschedule does not work. I noticed the input field for the location is set to `readonly` but not `disabled`.

### Steps to Reproduce

1. Create a new event type
2. Set Location to be "In Person (Attendee Address)"
3. Save the event 
4. View public page and open the event type
5. Schedule a booking with the address filled in
6. Reschedule
7. The location cannot be modified

I consider this a bug because the location of a meeting is bound to be updated.

### Actual Results

- Location input field cannot be modified and is set to read-only
- Cursor over input field still shows the test selection (i.e. `cursor: text`)
- _Interesting_, removing the readonly and modifying it actually causes location to be committed to the backend, albeit not entirely.
  - The location under "Where" still shows the value pre-modification
  - However, when rescheduling, the location input actually shows the value post-modification

![image](https://github.com/calcom/cal.com/assets/577802/a56f26d6-65fc-4ab2-9795-6c3bc0b62b18)

### Expected Results

The location should be modifiable and reflected in the booking confirmation and associated webhooks.

### Technical details

- Chrome Version 117.0.5938.92

### Evidence
[cal-reschedule-location-bug.webm](https://github.com/calcom/cal.com/assets/577802/8996a4d9-7902-4875-b4f9-8b133443508f)

**Comment by PeerRich** [comment]
this should be an easy fix. i agree rescheduling should be able to change address
