### ISSUE TITLE
[CAL-2563] recurring events: only check for 2 recurrences for conflict, not all of them

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11654]
lets only check 2 recurrences in advanced, not N

if you are booking an event for 12 weeks, check for 2 weeks, not all 12.

this will make more recurring bookings pass

downside: you recurring event may conflict with your calendar in 3 weeks, but this is fine because people offering recurring events typically clear their schedule anyway:

i.e.: personal tennis training is always Monday 5PM

<sub>[CAL-2563](https://linear.app/calcom/issue/CAL-2563/recurring-events-only-check-for-2-recurrences-for-conflict-not-all-of)</sub>

**Comment by ErrolFernandes** [comment]
Instead of checking for N weeks individually ,we can Boolean check it once together.

**Comment by PeerRich** [comment]
w want to check at least 2 occurrences. not only one

**Comment by hariombalhara** [comment]
@PeerRich Should we show this info somewhere to the booker that the 'Only the first 2 occurences are confirmed and remaining would be reviewed by Organizer' or something similar?

**Comment by hariombalhara** [comment]
Weirdly, we start booking the slots from end. We have got to change that logic as well.
https://github.com/calcom/cal.com/blob/3669e04975b554996fb294685df6fdf5a7894f37/apps/web/pages/api/book/recurring-event.ts#L23
