### ISSUE TITLE
[CAL-2564] recurring events: use proper "recurring" API from calendar APIs

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11655]
right now people select how many events they wanna book (i.e. 12 Mondays)

this shortcut was taken to ship this feature faster.

lets use the proper "recurring" APIs from google/outlook (maybe caldav?)

we could fall back to individual events for other calendars but I think all of them should support recurring events 

<sub>[CAL-2564](https://linear.app/calcom/issue/CAL-2564/recurring-events-use-proper-recurring-api-from-calendar-apis)</sub>

**Comment by shakthi2003-ice** [comment]
Hey @PeerRich 
It would be grateful if you could assign me this issue.

**Comment by PeerRich** [comment]
no need to ask, just open a PR

**Comment by keithwillcode** [comment]
Moving to v3.6 with high priority because this will help fix many issues with recurring events
