### ISSUE TITLE
Can Book the Meeting with Identical Host and User(Host to Host)

### ISSUE THREAD

**Issue by arunkumar201** [calcom/cal.com#11658]
Found a bug? Please fill out the sections below. 👍
I have encountered an issue while attempting to book a meeting by copying the URL from event types and opening it in the side tab. It seems that we are able to book a meeting when the same host and user (host to Host). Actually, we are not allowed to any host to book the meeting itself.
### Issue Summary
![book](https://github.com/calcom/cal.com/assets/70876302/f075aeb4-be98-49ac-95ae-368c6060e406)

### Steps to Reproduce

1. Go to  Event Types section 
2. Copy the URL
3. open a new tab with the same window where you have already logged it 
2. select time and enter the same data (as host data like email)
3. click  on confirm btn 
4. we will see the booking  successfully (HOST TO HOST)

### Expected Results
It is not possible for users to book a meeting with themselves or Booking a meeting with oneself is not permitted.

**Comment by gambhirsharma** [comment]
Hey! I would love to contribute to this issue along with @devarshishimpi
We both would work on this in a team and provide you with the fix PR while keeping the Contributing Guidelines in mind.
Requesting the team to kindly assign the issue to both of us! Thanks!

**Comment by PeerRich** [comment]
why would we not wanna allow this? maybe people book themselves for private events, like walking the dog haha.

i don't see this a bug worth fixing. let people book themselves
