### ISSUE TITLE
[CAL-2583] Create E2E tests to check timezone and date behaviors in a regular booking

### ISSUE THREAD

**Issue by gitstart-calcom** [calcom/cal.com#11663]
Create tests simulating the user changing the timezone and check if the available dates are aligned with the current date

<sub>[CAL-2583](https://linear.app/calcom/issue/CAL-2583/create-e2e-tests-to-check-timezone-and-date-behaviors-in-a-regular)</sub>

**Comment by Powell-v2** [comment]
Hi there, I'd like to take a stab at this one if no one else has picked this up already.

**Comment by techwithsrikanth** [comment]
Can this be an implementation of cypress and libraries like luxon to correctly ensure timezone and date behaviors?
let me know your thoughts on it

**Comment by zahidhussain998** [comment]
can you plase send quick  "ss"
