### ISSUE TITLE
[CAL-2572] feat: app.cal.com/upgrade url

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11679]
we have this button: 
![image](https://github.com/calcom/cal.com/assets/8019099/45444996-763b-4e72-abf2-0d86e8eef747)

but i cant send someone the link: just go to app.cal.com/upgrade

a redirect that then opens stripe would be nice

<sub>[CAL-2572](https://linear.app/calcom/issue/CAL-2572/feat-appcalcomupgrade-url)</sub>

**Comment by pragyamishra56** [comment]
Kindly assign this issue to me. I'm eager to work on it and provide a resolution. Thank you for your consideration

**Comment by Gowrish7** [comment]
> Kindly assign this issue to me. I'm eager to work on it and provide a resolution. Thank you for your consideration

Hey pragya you dont have have to wait for someone to assign you the issue just start working on it

**Comment by pragyamishra56** [comment]
Hey @PeerRich  DM me on my Twitter handle
