### ISSUE TITLE
[CAL-2570] add resend.com as email provider

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11673]
let self-hosters choose between sendgrid, smtp and resend.com, maybe loops.so (different PR)

whatever .env is available, that service will be used

likely needs a more modular EmailService adapter 

<sub>[CAL-2570](https://linear.app/calcom/issue/CAL-2570/add-resendcom-as-email-provider)</sub>

**Comment by PeerRich** [comment]
we want optionality for self-hosters so they can decide between different email providers.

we already do this for intercom, zendesk and helpscout

**Comment by zenorocha** [comment]
excited for this one

**Comment by mfts** [comment]
exciting 🔥
