### ISSUE TITLE
[CAL-2580] Function sendScheduledSeatsEmails ignore rule "Disable default confirmation emails for attendees"

### ISSUE THREAD

**Issue by xandyalexandrec** [calcom/cal.com#11677]
### Issue Summary

When you have a event that offers seats, the confirmation email is sent to the 2nd attendees onwards even if the option _"Disable default confirmation emails for attendees"_ is enabled and you have active workflow to send emails for the event type.

The confirmation email is not sent for the first attendee because it uses the function `sendScheduledEmails` which have the props `hostEmailDisabled` and `attendeeEmailDisabled`, however the `sendScheduledSeatsEmails` doesn't have this props and ignore the rule to disable default confirmation emails for attendees.

### Steps to Reproduce

1. Create a Event that offers seats (Tab Advanced - Offer Seats)
2. Create and apply a custom workflow that sends email to the attendee after a event is booked
3. Go back to the event, Advanced Tab and check the option _Disable default confirmation emails for attendees_
4. Register for the event, you will receive only one e-mail, from the workflow.
5. Register again for the event with a different e-mail, you will receive two e-mails, one from the workflow and the other one from default email confirmation.

### Actual Results

- It doesn't respect the configuration _"Disable default confirmation emails for attendees"_

### Expected Results

- To not send the default confirmation when using the function `sendScheduledSeatsEmails` when the option _"Disable default confirmation emails for attendees"_ is enabled and you have active workflow to send emails for the event type.

### Technical details

Using production env.

### Evidence

![Screenshot 2023-10-03 at 12 31 33](https://github.com/calcom/cal.com/assets/2214768/b337b136-4f74-4bf9-a305-f7cc90a23e0b)

![Screenshot 2023-10-03 at 12 32 45](https://github.com/calcom/cal.com/assets/2214768/4f779ff1-a79b-41e3-987b-93039e659219)

![Screenshot 2023-10-03 at 12 33 13](https://github.com/calcom/cal.com/assets/2214768/9ce3195c-0dd1-4c98-bfb1-06152a78b203)

<sub>[CAL-2580](https://linear.app/calcom/issue/CAL-2580/function-sendscheduledseatsemails-ignore-rule-disable-default)</sub>

**Comment by Siddharth-2382** [comment]
@CarinaWolli I would like to work on this issue. Could you assign it to me?

**Comment by CarinaWolli** [comment]
@Siddharth-2382  Feel free to work on it :) When you create the PR please make sure to link this issue 🙏

**Comment by Siddharth-2382** [comment]
@CarinaWolli Can you review my PR if it fixes this issue?
