### ISSUE TITLE
[CAL-2582] org-team - adding team members from organization tab that alredy exist throws an error

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#11687]
### Issue Summary

adding team members from organization tab that alredy exist throws an error which is correct though the message could be better,
but the existing member should not be visible or should be disabled, becuse if i am selecting multiple users to add from the org tab and one of them alredy exists then it throws error and none of them will be added.

### Expected Results
should not show the members that alredy exist or the checkbox should be disabled

### Evidence

[Screencast from 04-10-23 01:25:07 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/ecab81f7-49c4-4938-a782-33314d4b6004)

<sub>[CAL-2582](https://linear.app/calcom/issue/CAL-2582/org-team-adding-team-members-from-organization-tab-that-alredy-exist)</sub>

**Comment by Siddharth-2382** [comment]
I tried to reproduce it and even though it doesn't throw the error it says "1 user has been invited" and no change is there on the next screen. Though it doesn't throw an error I feel the already invited names shouldn't be there.
