### ISSUE TITLE
[CAL-2573] Rescheduling Link Expires RIGHT AFTER Meeting

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#11683]
I think the reschedule link should be extended 6-12 hours after the meeting is done, some times a person misses the meeting and wants to reschedule. 

Now when they go to the reschedule link, they're hit with a "page does not exist" which is a pretty bad experience 

<img width="708" alt="CleanShot 2023-10-03 at 06 35 27@2x" src="https://github.com/calcom/cal.com/assets/16177678/4b86b25d-6aea-4468-85a4-a61ee2eada1a">

Next steps:

Extend reschedule window to 6-12 hours post call
Swap out this page with something like "This meeting can no longer be rescheduled because it occurred already. Please reach out to the host to reschedule." 

<sub>[CAL-2573](https://linear.app/calcom/issue/CAL-2573/rescheduling-link-expires-right-after-meeting)</sub>

**Comment by shirazdole** [comment]
cc @zomars @ciaranha

**Comment by itzabhinavarya** [comment]
Hii @shirazdole Sir, Can you please explain this task in briefly, And assign it to me. I want to work on this issue. Please help me to contribute in this issue.

**Comment by Udit-takkar** [comment]
@shirazdole I just tried opening the rescheduling link of an old booking and I don't get 404. I am redirected to the booking page to reschedule.
