### ISSUE TITLE
adding member to "other team" in an org by admin/owner gives unexpected behaviour

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#11691]
### Issue Summary
adding member to "other team" in an org by admin/owner gives unexpected behaviour
* the members that were alredy present in the team are repeated twice and the go away once we refresh the page

### Evidence

[Screencast from 04-10-23 03:43:45 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/8da333ff-816e-48c2-ba72-62da9ee12d34)

**Comment by Vishnuedge** [comment]
Can someone assign this to me.

**Comment by Vishnuedge** [comment]
@SomayChauhan Hey! How did you created an organization. I already followed .env things still I can't create one.
