### ISSUE TITLE
organizations - should allow org owners and admins to delete members from subteams

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#11709]
### Issue Summary
if we are allowing org owners and admins to add members to sub-teams then we should also allow them to remove users from sub-teams

### Actual Results
 - currently org owners and admins can add members to sub teams but not delete them

### Expected Results

- should allow org owners and admins to add as well as remove members from sub-teams

### Evidence
![Screenshot from 2023-10-05 15-54-38](https://github.com/calcom/cal.com/assets/32706411/36ed82b4-c528-4451-8637-0461518fc2be)

here the add button is visible but the options button in front of each member is missing

**Comment by Adugnatad** [comment]
@SomayChauhan  This already available 
![remove team](https://github.com/calcom/cal.com/assets/91078751/e5128cb9-33d2-4bec-a8e3-5bf5635731bb)

**Comment by SomayChauhan** [comment]
you need to go to settings/organizations/new and create a new organization and then create a new team under that organization
