### ISSUE TITLE
[CAL-2584] Missing translation for number_sms_notifications

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#11718]
### Issue Summary

Translation is missing, see here: 
<img width="405" alt="Screenshot 2023-10-06 at 09 28 17" src="https://github.com/calcom/cal.com/assets/30310907/98f7dc1e-ebad-4846-bcea-1ec8f9c43aea">

This was replaced with `number_text_notifications` when we introduced Whatsapp workflow actions, but workflows that existed before still have the default label `number_sms_notifications`. 

The text should be: Phone number (SMS notifications)

<sub>[CAL-2584](https://linear.app/calcom/issue/CAL-2584/missing-translation-for-number-sms-notifications)</sub>

**Comment by Nikeshkumar-tk** [comment]
#11724 Replaced Phone number (Text notifications) with Phone number (SMS notifications)
