### ISSUE TITLE
[CAL-2585] org team page not found with uppercase letters

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#11719]
### Issue Summary

https://meet.cal.com/engineering shows the team 
https://meet.cal.com/Engineering throws 404 This page does not exist.

<sub>[CAL-2585](https://linear.app/calcom/issue/CAL-2585/org-team-page-not-found-with-uppercase-letters)</sub>

**Comment by hariombalhara** [comment]
Works for me now. Maybe something changed. Closing it @CarinaWolli .

![Screenshot 2023-12-11 at 1.24.59 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f96b0c7d-24fc-4683-a21b-b8d2b3b7cec3/80dff7bf-c485-4083-876a-64f60e854d1d)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1742839e-3a5d-484c-8f99-eb392974d458/5eb73eaa-482c-4f1e-b687-ef1843fa81cb)
