### ISSUE TITLE
[CAL-1683] troubleshooter doesn't provide sufficient info

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#1171]
### Is your proposal related to a problem?

The troubleshooter doesn't provide sufficient info to figure out what is blocking availability.  It simply gives a list of busy times:

![image](https://user-images.githubusercontent.com/100738/141397401-f20e0218-cbf2-4fc2-8fc4-a10e6a1751e5.png)

which on an account with multiple integrations / calendars doesn't help figure out where the bookings are coming from.

### Describe the solution you'd like

For each booking, show the event title, *and* which integration / calendar it comes from.

### Describe alternatives you've considered

Instead of showing a list of bookings, copy calendly's approach, and show a list of slots, and for each unavailable slot, an explanation of why it is unavailable:

![image](https://user-images.githubusercontent.com/100738/141398077-1f7ee50c-eb06-440e-bd28-8c7f124a1603.png)

This is probably better, because it can explain that slots are unavailable not just due to overlap with existing events, but also for other reasons, e.g. the slot is outside the standard working hours for the account, or it's too short notice to book that slot, or it doesn't leave enough of a buffer before the next meeting.

### Additional context

Notice how much clearer calendly's date picker is.  The cal.com one is really hard to spot:

![image](https://user-images.githubusercontent.com/100738/141398174-d681636a-1802-49be-93c4-9772c55e2c40.png)

<sub>[CAL-1683](https://linear.app/calcom/issue/CAL-1683/troubleshooter-doesnt-provide-sufficient-info)</sub>

**Comment by ConnorGargano** [comment]
Hi @aspiers,
I will get this raised with our engineering team to see how we can improve this.

**Comment by aspiers** [comment]
Thanks @ConnorGargano, much appreciated!

**Comment by aspiers** [comment]
Hey @ConnorGargano any thoughts on this one?

**Comment by PeerRich** [comment]
the troubleshooter has been deprioritized and will get more attention after 2.0! 🙏

**Comment by keithwillcode** [comment]
The troubleshooter is getting a major overhaul.

**Comment by aspiers** [comment]
@keithwillcode Great to hear it's getting a major overhaul! In that case presumably there is another issue you can link to from here so we can follow that one?  Otherwise it's a bit dissatisfying to see this acknowledged as an issue but closed with no further information on how to track progress.

And in that case, shouldn't this be closed as a duplicate rather than as "completed" or "not planned"?  Neither of those statuses seem congruent with the good news that it's getting a major overhaul.

Thanks!

**Comment by aspiers** [comment]
I elaborated a bit further on this topic of optimal communications in https://github.com/calcom/cal.com/issues/6729#issuecomment-1822727602.
