### ISSUE TITLE
[CAL-2586] Clarity Improvements for Cal Video and Booking

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11723]
Feedback by [MrNick_Buzz](https://twitter.com/MrNick_Buzz/status/1710208786282226039)

I use [@calcom](https://twitter.com/calcom) a lot and we & our clients love it! But there are a few things I would like to see changed to make the experience better for everyone.

- [x] #11730

Ability to join a call without having to click the meeting card and enter the meeting details page

![image](https://github.com/calcom/cal.com/assets/8019099/b8f063b2-3c2d-4423-9374-c891295e9a59)

- [x] #11728
The video call page lacks hierarchy and everything is dark when the videos of the participants are turned off

![image](https://github.com/calcom/cal.com/assets/8019099/73f2261a-0eb2-4f0b-a429-6d2cc54849ee)

- [ ] #11731
Most of our clients struggle to share their screens. Maybe make it descriptive and easy to understand, than just "Share", as it can mean anything from sharing the link to sharing the screen.
![image](https://github.com/calcom/cal.com/assets/8019099/cd3ea591-c547-41c4-b104-2ea29f48a10d)

- [x] Buttons instead of link URLs
CTA is totally removed in the pre-meeting experience, all of them are replaced with links. Would recommend adding clear CTA's that are easy to find over text links

![image](https://github.com/calcom/cal.com/assets/8019099/6117e783-e1fb-4b16-b618-86e1b39bcda9)

<sub>[CAL-2586](https://linear.app/calcom/issue/CAL-2586/clarity-improvements-for-cal-video-and-booking)</sub>

**Comment by ciaranha** [comment]
Great points raised. Will look into these.

**Comment by Siddharth-2382** [comment]
@PeerRich what to do with the cancel button for the first change?

**Comment by Siddharth-2382** [comment]
@PeerRich what to do with the cancel button?

**Comment by PeerRich** [comment]
> @PeerRich what to do with the cancel button for the first change?

I think we will put the video link somewhere else. its a good idea but I think the positioning is better to have CANCEL | EDIT on the right and the location link somewhere else

**Comment by Siddharth-2382** [comment]
@PeerRich Of all the changes mentioned above I was able to find the parts that need to be changed. I'm new and don't know much about where different things fall into. Learning more everyday but I am not able to find the code which is supposed to fix "Share Screen". I'd like to work on this issue if designs are ready.

**Comment by PeerRich** [comment]
>  CTA is totally removed in the pre-meeting experience, all of them are replaced with links. Would recommend adding clear CTA's that are easy to find over text links

this one I disagree with, I think its easier to find a link (i.e. meet.google.com/..) than a button.

i could see adding both 

Button
Link

**Comment by Siddharth-2382** [comment]
@PeerRich For the third one will you open a new issue? I would like to work on that one.

**Comment by PeerRich** [comment]
all addressed, some not merged yet
