### ISSUE TITLE
[CAL-2590] Show link location in /bookings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11730]
show link to join a call in the /booking overview

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2590](https://linear.app/calcom/issue/CAL-2590/show-link-location-in-bookings)</sub>

**Comment by PeerRich** [comment]
how about this? 
![CleanShot 2023-10-06 at 13 44 42@2x](https://github.com/calcom/cal.com/assets/8019099/745e637f-003a-48f6-bd48-e46336898a45)

**Comment by PeerRich** [comment]
alternatively, show the name of the app: 
![CleanShot 2023-10-06 at 13 49 03@2x](https://github.com/calcom/cal.com/assets/8019099/bc75d80e-a1ee-439e-87ca-7104c40056c7)

**Comment by Siddharth-2382** [comment]
Meeting Link seems to better as it is more of general term and conveys the message about what it does clearly. Also if you could finalise the design, I'd have liked to work on this issue but seems like you have self assigned it🙂

**Comment by SeekerHub** [comment]
If the issue is opened I did like to work on it

**Comment by Tan28bha** [comment]
pr

**Comment by caioluis** [comment]
What is the state of this issue in fact? I've seen that multiple closing/reopening happened.

**Comment by ptdatta** [comment]
Is this completed?

**Comment by asadath1395** [comment]
@PeerRich I think this is done here https://github.com/calcom/cal.com/pull/11866, can we close this? Thanks
