### ISSUE TITLE
[CAL-2592] Test for googlecalendar reschedule and cancel.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11736]
Let's add a test for reschedule and cancel.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/11733#discussion_r1348751679_
            

<sub>[CAL-2592](https://linear.app/calcom/issue/CAL-2592/test-for-googlecalendar-reschedule-and-cancel)</sub>

**Comment by ASCE-D** [comment]
Hey @hariombalhara I was working on this, the function is private so I cannot create its object inside the test file 
```  
test("authedCalendar returns a calendar", async () => {
  const calendarService = new CalendarService(testCredential);
  const calendar = await calendarService.authedCalendar();
  expect(calendar).toBeDefined();
}); 


error  :  Property 'authedCalendar' is private and only accessible within class 'GoogleCalendarService'.ts(2341)
(property) GoogleCalendarService.authedCalendar: () => Promise<calendar_v3.Calendar>
 ```

So should I create object in an public function or can I create an public function like this

```
public async publicFunction() {
  const calendar = await this.authedCalendar();
 
}

```
