### ISSUE TITLE
[CAL-2591] Add "Share Screen" to Cal Video (instead of only "Share")

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11731]
this issue has to be addressed by [daily.co](http://daily.co) since we are using their prebuilt UI

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2591](https://linear.app/calcom/issue/CAL-2591/add-share-screen-to-cal-video-instead-of-only-share)</sub>

**Comment by Mayank-2210** [comment]
hey @PeerRich can i work on this issue. can you please assign it to me.
thank you

**Comment by vanshraghav** [comment]
Hey @PeerRich Can I work on this issue?
