### ISSUE TITLE
organization - org owners and admins should show their respective badge when they join a sub-team

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#11732]
### this is my organization members page
![Screenshot from 2023-10-06 17-17-07](https://github.com/calcom/cal.com/assets/32706411/d1f1aad3-2947-4467-be21-e726430874a1)
* as you can see i have temp1 as admin and somay and somay2  as owners
### this is one the teams under my organizations
![Screenshot from 2023-10-06 17-22-20](https://github.com/calcom/cal.com/assets/32706411/ac148a94-56c7-405b-977c-02fa3b495c5b)
* as you can see all of them are joined as members but temp1, somay and somay2 all have the admin access to these teams i.e. they can add and remove members from teams so they should show owner/admin instead of member

PS: this is just a suggestion however, I may be wrong here.

**Comment by Tashuuuu** [comment]
So you want temp1, somay, and somay2 to also join as members?

**Comment by akshaybhinge19** [comment]
![image](https://github.com/calcom/cal.com/assets/87247305/2d8cad71-c6c5-4f22-9370-57f2594a9e86)
I don't think this bug is valid. can you confirm? @SomayChauhan

**Comment by subham1399** [comment]
Hi, Can you kindly help to understand the exact point that you want to highlight here?

**Comment by code0monkey1** [comment]
<img width="1529" alt="Screenshot 2023-10-09 at 12 09 06 PM" src="https://github.com/calcom/cal.com/assets/13780166/046f6686-2c2c-49db-9efb-368c6a7fdeba">
---
<img width="1789" alt="Screenshot 2023-10-09 at 12 11 04 PM" src="https://github.com/calcom/cal.com/assets/13780166/9f449167-76da-448f-b6cf-d11be556838d">


---

**Non - reproducible !**

I made 2 teams, and both show the member roles clearly!

**Comment by mohammadruman** [comment]
Heyy Can you please Elaborate Your Issue

**Comment by Yash-verma18** [comment]
can you add more details on this ? Do we want them to join as a member ?

**Comment by NyayadhishViraj** [comment]
@PeerRich I would like to attempt this issue.

**Comment by Swapnil7711** [comment]
@SomayChauhan correct me if I am wrong here. so you want to show the "Admin/Owner" tag instead of "Member" tag for the team members if they have "admin/owner" access.
