### ISSUE TITLE
Feat: Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [calcom/cal.com#11758]
### Is your proposal related to a problem?
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Cal.com application [as shown here](https://elest.io/open-source/cal.com). I think it would be a great idea if we can add it to official readme/documentation here.
In addition to this, if you are interested we provide collaboration opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just drop me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### Requirement/Document

<img width="1426" alt="image" src="https://github.com/calcom/cal.com/assets/53310847/0bdb42e9-bfef-4a03-a015-32ffa02d2779">

**Comment by koushikromel** [comment]
I came across this typo not sure whether to post here or not.
The added link `https://elest.io/open-source/cal.com`  is not a valid link `https://elest.io/open-source/cal` this is the valid one that redirects to the cal page on elest.io.
Kindly check this @kaiwalyakoparkar 

This is my first ever contribution/doubt/issue that I am raising in opensource, let me know if there is anything that I should change in my approach
