### ISSUE TITLE
Steps to create a user.

### ISSUE THREAD

**Issue by asharabu** [calcom/cal.com#1175]
Hi,

Please provide the steps to create a user for selfhosted calendso. I am facing issues trying to create via prismastudio.

![image](https://user-images.githubusercontent.com/42669995/141757781-2fcdd892-d343-4018-b0dd-6a6c90dab868.png)

![image](https://user-images.githubusercontent.com/42669995/141757638-2be5667c-d22c-4b44-a0b5-beda8597de85.png)

**Comment by kamikazebr** [comment]
In https://github.com/calendso/calendso#manual step 8 and 9 instructions to create user and password.

I'll recommend you some **offline bcrypt generator** like https://www.npmjs.com/package/bcrypt-cli using work_factor/**salt length** of **12** instead 10

You error looks like your database dont ran all migrations on prisma, that self-hosted its local machine?

**Comment by sean-brydon** [comment]
Closing as this issue is stale - Please reopen this issue if you are still having this problem.
