### ISSUE TITLE
[CAL-2599] broken layout email embed generator

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11779]
Mon 09 12h 24h should be on top, not next to it

its worth noting this component is being used in the booking page, so be careful when fixing!

![image](https://github.com/calcom/cal.com/assets/8019099/bb7e48d3-3e0b-4e27-a9c8-5be6b47dc3be)

<sub>[CAL-2599](https://linear.app/calcom/issue/CAL-2599/broken-layout-email-embed-generator)</sub>

**Comment by pratik9818** [comment]
I can do it !
