### ISSUE TITLE
[CAL-2601] When a pending booking is rescheduled, it doesn't show the rescheduleReason on the booking success page - I think it should be shown

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11784]
[https://github.com/calcom/cal.com/blob/2faf24fb986c7a323ee9aa1ff9387bcc14033439/apps/web/pages/booking/\[uid\].tsx#L401](https://github.com/calcom/cal.com/blob/2faf24fb986c7a323ee9aa1ff9387bcc14033439/apps/web/pages/booking/%5Buid%5D.tsx#L401)

This check is what prevents it from showing it for a rescheduled booking that's in pending state because `reschedule` is true only when booking status is accepted.

Steps would be

1. Create an event that requires confirmation
2. Book that event. The event would go to Pending state
3. Now, reschedule that event and add a reschedule reason
4. Booking would be rescheduled to the new time and status would remain pending
5. Notice that booking success page doesn't show the reschedule reason

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2601](https://linear.app/calcom/issue/CAL-2601/when-a-pending-booking-is-rescheduled-it-doesnt-show-the)</sub>

**Comment by Siddharth-2382** [comment]
@hariombalhara I'm sorry to ask but as I am new to this project can you tell me how to recreate this? I don't understand what is considered as a pending booking. I would like to work on this one. I have gone through the code which ironically made sense to me but just to test things out I should know how to recreate it ;)

**Comment by hariombalhara** [comment]
@CarinaWolli Added clear steps to the issue description.
