### ISSUE TITLE
Getting 500 when booking "user doesn't exist"

### ISSUE THREAD

**Issue by stefanbielmeier** [calcom/cal.com#11782]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When someone is on my public page and wants to book an appointment (https://cal.com/stefan), different 500 errors show up.
![image](https://github.com/calcom/cal.com/assets/31830577/0d372c96-64f4-488e-8a80-9c95c0f0bef1)
![image](https://github.com/calcom/cal.com/assets/31830577/d76622c9-9a30-4b39-b109-5cfac5b9dfb3)

Additionally, when I upload a new profile picture, it first saves it successfully. But once I leave the page, the standard avatar is shown again. 

And, whenever I try to change my email address, I also get a 500
<img width="673" alt="Screenshot 2023-10-10 at 11 18 12 AM" src="https://github.com/calcom/cal.com/assets/31830577/aac201ba-b970-4cff-b875-2d8da8c71a64">

### Steps to Reproduce

1. Go to cal.com/stefan
2. Try booking
3. Get 500 error

This is a bug because no one can book although I set up the right permissions in settings. And see above screenshots (500 http)

### Technical details

This might be because I'm a user from very early days with a short username? Seems that it can't find my account linked to my email anymore or something.

### Evidence

See above

**Comment by PeerRich** [comment]
maige, don't use the "❗️invalid" label

**Comment by stefanbielmeier** [comment]
Hi, is there anything I can do from my end? I feel like my username is not connected with whatever user data you have stored in your DB. But I don't have access to your DB to fix it 😓

**Comment by stefanbielmeier** [comment]
happy to jump on a call to help debug and resolve @emrysal – just saw 1-2 people trying to do test bookings (might have been you) which went through, but the 500 error is still showing 😕

**Comment by stefanbielmeier** [comment]
This has been fixed! (by creating an account with another username and milo from support re-assigning my old username from the account linked to the broken email address.)
