### ISSUE TITLE
[CAL-2605] chore: fix padding in event-types

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11797]
![CleanShot 2023-10-10 at 16 48 39@2x](https://github.com/calcom/cal.com/assets/8019099/4ef0645c-b0bb-433f-a414-3bdc4c97f536)

<sub>[CAL-2605](https://linear.app/calcom/issue/CAL-2605/chore-fix-padding-in-event-types)</sub>

**Comment by anishsoni29** [comment]
Hey, I'm not able to find the link to make appropriate commits. Kindly help.

**Comment by anikdhabal** [comment]
> Hey, I'm not able to find the link to make appropriate commits. Kindly help.

You can find it here.
![Screenshot 2023-10-10 230251](https://github.com/calcom/cal.com/assets/81948346/0b4a41e1-71b6-439b-b5a0-0e4fc10f1c94)
