### ISSUE TITLE
Hide User on Team Page

### ISSUE THREAD

**Issue by neoprogger** [calcom/cal.com#11792]
### Is your proposal related to a problem?

We are using an "admin" account to manage our Teams (Availability, Memberships etc.)
This admin user is Team-Admin and Displayed on the Team-Site - but as this is a technical admin, it should be hidden

### Describe the solution you'd like

Add the possibility to "hide this member in team-site" 

### Describe alternatives you've considered

Using an actual member of the team does not work as we don't want them to be able to manage the team

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by Mayank-2210** [comment]
can you please assign this issue to me

**Comment by ecrode** [comment]
I have a same issue, tried doing so via nginx, but so far couldn't get it to work

location ^~ /team/ {
    proxy_set_header Accept-Encoding "";
    sub_filter_types text/html;
    sub_filter '<a href="/admin">[\s\S]*?</a>' '';
    sub_filter_once off;
    proxy_pass $srv;
}

**Comment by ecrode** [comment]
Considering that admin user is likely not to have any available event types for selection, perhaps it can be used as a logic when filtering the users from the team. In case next screen after user selection would show an empty screen, filter out said user, regardless if they are admin or not.
