### ISSUE TITLE
Allow team administration without being a member of the team

### ISSUE THREAD

**Issue by ecrode** [calcom/cal.com#11798]
### Is your proposal related to a problem?

I'm an administrator, but not one of the people that should be available as a selection when booking. Right now I cannot administer a team without being a selectable member.

### Describe the solution you'd like

Allow admin or owner account to be hidden from a public team page.

### Describe alternatives you've considered

Edit the html via nginx reverse proxy and/or retaining password to a designated owner of the team.

**Comment by neoprogger** [comment]
https://github.com/calcom/cal.com/issues/11792
duplicate?

**Comment by ecrode** [comment]
> #11792 duplicate?

Yes, I apologize. Checked this morning and saw no similar suggestions, while I was messing about with nginx, a similar issue was raised. Please close as duplicate, I’ll follow the earlier post.
