### ISSUE TITLE
[CAL-2606] Avatar and users fullname spacing incorrect

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11803]
![CleanShot 2023-10-10 at 20 16 30](https://github.com/calcom/cal.com/assets/55134778/cd1a994f-29d2-4273-839b-9956eeed2a3e)

This should match the figma design

https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=4302-156745&mode=design&t=jfEpS6cx7xtpzbCf-4

Top of my head this is located: features/shell/Shell.tsx

<sub>[CAL-2606](https://linear.app/calcom/issue/CAL-2606/avatar-and-users-fullname-spacing-incorrect)</sub>

**Comment by Mohith705** [comment]
Please, assign me this issue

**Comment by SidVermaS** [comment]
@sean-brydon 
Here's the fix, please merge my PR
https://github.com/calcom/cal.com/pull/11823

**Comment by PeerRich** [comment]
fixed
