### ISSUE TITLE
[CAL-2874] Mobile scrolling issue (booking page)

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#11811]
In the mobile browser, the booking page scrolls down automatically and much too far after opening.

https://github.com/calcom/cal.com/assets/126205884/80a190bf-1f30-4209-a29e-ea4e862e8adf

<sub>[CAL-2874](https://linear.app/calcom/issue/CAL-2874/mobile-scrolling-issue-booking-page)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar how far are we scrolling here?

**Comment by Udit-takkar** [comment]
@RainerZufall9393 ok thanks for reporting.I will look into this bug

**Comment by ciaranha** [comment]
@Udit-takkar is this still an issue?
