### ISSUE TITLE
[CAL-2610] Improve the UX for the "Identifier" input in Booking Questions

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#11813]
**Problem**
Currently, every user has to interact with the "Identifier" field in booking questions even though most people have no need for it, and don't know what it is.

**Solution**
- Prefill it based on the label
- Let people edit it (only if they need to)
- Make it less prominent in the UI
- Provide a tooltip/docs link to explain what it is.

**Designs**
https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=12250%3A205581&mode=dev

<sub>[CAL-2610](https://linear.app/calcom/issue/CAL-2610/improve-the-ux-for-the-identifier-input-in-booking-questions)</sub>

**Comment by Siddharth-2382** [comment]
Can I work on this? Also I need some help regarding where to find the SVGs(info - ⓘ, learn more - ↗) used in the design.

**Comment by Siddharth-2382** [comment]
@ciaranha I've started working on it. But I have a few questions like:
Is the ⓘ button besides `Identifier` label supposed to be clickable? Does the `pre-filled-label` which is visible in the design page-2 always visible or after ⓘ is clicked?

**Comment by ShakirFarhan** [comment]
Hello @ciaranha could you please let me know if i can take up this issue and work on?
