### ISSUE TITLE
[CAL-2609] /event-type-single: Button icons tooltips opening out of view due to padding issue

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#11812]
It looks like we've reduced the padding at the top of the event types screen so now the tooltips are out of view:

<img width="334" alt="CleanShot 2023-10-11 at 05 45 14@2x" src="https://github.com/calcom/cal.com/assets/4536123/7b0b56d1-d800-441d-9df2-4e793644d888">

Should be:

<img width="811" alt="CleanShot 2023-10-11 at 05 51 13@2x" src="https://github.com/calcom/cal.com/assets/4536123/fcc7170d-63f7-4103-acd1-d32c7b169bff">

<sub>[CAL-2609](https://linear.app/calcom/issue/CAL-2609/event-type-single-button-icons-tooltips-opening-out-of-view-due-to)</sub>

**Comment by MeenuyD** [comment]
Can you please review this #11816

**Comment by PeerRich** [comment]
we should show the tooltip at the bottom instead of changing padding

**Comment by Siddharth-2382** [comment]
> we should show the tooltip at the bottom instead of changing padding

I have made the tooltip to be shown at bottom. For some buttons they passed in the tooltip as a prop so I added an additional prop for the button so on can describe the side for tooltip in the <Button> element itself.

**Comment by ciaranha** [comment]
> we should show the tooltip at the bottom instead of changing padding

The padding used to be larger and matched the designs in Figma. Someone reduced it recently. We can of course put the tooltip at the bottom, but I'm suggesting we put the padding back to what it was before and what we have in Figma.
