### ISSUE TITLE
Override button hidden by toast on mobile

### ISSUE THREAD

**Issue by juliusmarminge** [calcom/cal.com#11814]
![image](https://github.com/calcom/cal.com/assets/51714798/62f15f12-4ead-4f89-b3f8-60884b8a544a)

The following is what it looks like when adding 2 overrides in a short timeframe, the toast hides the button so i cant add more overrides until the toast goes away.

I'm on an iPhone 12 if screen size is of relevance.

---

Also, huge props to how this flow has been improved. It used to be quite the pain to add overrides for multiple days but now it's much less friction as the modal stays open and i can just click the dates i want much faster. Thanks for that 🙏

**Comment by pratik9818** [comment]
@juliusmarminge ,  i think if we can remove the 1st toast when 2nd toast comes , it means only latest override toast remain on the mobile screen until new toast not come

**Comment by bhanusingh008** [comment]
@juliusmarminge, Hey i think i fixed it, can you assign it to me.

**Comment by PeerRich** [comment]
no need to ask, go for it just raise a PR
