### ISSUE TITLE
Prisma is not defined

### ISSUE THREAD

**Issue by kkenacton** [calcom/cal.com#11821]
Found a bug

Repository: cal.com GitHub Repository
Error: "Prisma not defined" during team member invite processes

It appears that the Prisma library or module is not correctly imported or defined in the relevant codebase, causing these errors to occur. As a result, I am unable to complete these actions, which are crucial for the functionality of our project.

### Steps to Reproduce

1. Navigate to https://mydomain.com/settings/teams/1/members.
2. near the member there is a 3 dot.
3. click on resend invitation.
4. and below in the right corner it shows "Prisma is not defined"

I should be able to invite team members without encountering any errors related to Prisma.

### Actual Results

- Prisma is not defined

### Expected Results

- Invite send successfully

### Technical details
followed this doc for self deployment :
https://cal.com/docs/introduction/quick-start/self-hosting/installation#development-setup-&-production-build

screenshot of error: https://img.enacton.com/i/2023/10/chrome_6tpCeRxgcf.png
- Node.js version: 18.x

I would greatly appreciate your assistance in resolving this matter. If there are any additional logs, configurations, or code snippets you require to investigate the issue further, please let me know, and I will provide them promptly.

**Comment by PeerRich** [comment]
i believe this has been fixed
