### ISSUE TITLE
[CAL-2612] missing icon: request reschedule

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11829]
![image](https://github.com/calcom/cal.com/assets/8019099/4e834bdc-89d5-49c2-b0ba-da456494c962)

<sub>[CAL-2612](https://linear.app/calcom/issue/CAL-2612/missing-icon-request-reschedule)</sub>

**Comment by shubhalgupta** [comment]
Hello! Can you please tell which files needs to be edited

**Comment by Chiranjeev-droid** [comment]
@PeerRich  is this what we need or if not can you please share the figma link of  this particular ui.

## Dark Mode
![image](https://github.com/calcom/cal.com/assets/66114276/aa2fcd9b-74dc-42ee-aed2-78be50245f29)

## Light mode
![image](https://github.com/calcom/cal.com/assets/66114276/541e03a2-3860-436d-94b0-2e3163960f18)

**Comment by Siddharth-2382** [comment]
@PeerRich Can you explain more about the changes required as you reverted Abhinav's changes? I would like to fix it quick.

**Comment by Siddharth-2382** [comment]
> @PeerRich Can you explain more about the changes required as you reverted Abhinav's changes? I would like to fix it quick.

The icon's parent div has inline-css bg-[#fafafa]. An easy fix is as abhinav had done by doing bg-subtle but it seems a lit odd to me. We can just have a bg-default which makes the logo look much cleaner. If you're fine with it I can do the changes.

**Comment by tanavdev** [comment]
so this issue is solved, now you can close this
