### ISSUE TITLE
Minimum Booking Notice, next day?

### ISSUE THREAD

**Issue by notflip** [calcom/cal.com#11855]
### Describe the solution you'd like

Right now the min booking notice allows hours or days, it would be great to be able to say "Next day", for example, **so people can't book on the current day.**

**Comment by PeerRich** [comment]
![CleanShot 2023-10-12 at 16 36 26@2x](https://github.com/calcom/cal.com/assets/8019099/9a2808a2-caba-4a43-9149-f55f4ef46ef0)
this doesnt work?
