### ISSUE TITLE
[CAL-2816] Google Calendar Integration credentials are not refreshing

### ISSUE THREAD

**Issue by lawweiliang** [calcom/cal.com#11870]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Can't book using [cal.com](http://cal.com).

### Steps to Reproduce

Try to book a time using [cal.com](http://cal.com) link.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/58375146-06c7-49b9-b9c0-2e15bda86430/2f960be7-985b-416b-8fbf-c574fc847140?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ODM3NTE0Ni0wNmM3LTQ5YjktYjljMC0yZTE1YmRhODY0MzAvMmY5NjBiZTctOTg1Yi00MTZiLThmYmYtYzU3NGZjODQ3MTQwIiwiaWF0IjoxNzAyOTUwNjk1LCJleHAiOjE3MDMwMzcwOTV9.bhmDF77flfuRNd2Yx_1DiA7obORsp4Du8VDkZxB7U9o)

My clients do not receive any confirmation email.
I did not receive any confirmation email.

Yet, behind the scenes, bookings are made.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e42f1e5d-7689-49f7-88be-08d752ae6168/dc7b6f21-5d76-480a-af4a-867285a8e31d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNDJmMWU1ZC03Njg5LTQ5ZjctODhiZS0wOGQ3NTJhZTYxNjgvZGM3YjZmMjEtNWQ3Ni00ODBhLWFmNGEtODY3Mjg1YThlMzFkIiwiaWF0IjoxNzAyOTUwNjk1LCJleHAiOjE3MDMwMzcwOTV9.k3KUW8to1j-ePlxs0EzaRinZgIt7v97DBtQt4mZd2qE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2816](https://linear.app/calcom/issue/CAL-2816/google-calendar-integration-credentials-are-not-refreshing)</sub>

**Comment by technicalrutvik** [comment]
For me, it's working.
I don't see any flaws here.

**Comment by technicalrutvik** [comment]
@lawweiliang Can you check it again?

**Comment by lawweiliang** [comment]
@technicalrutvik 

The problem still exists. 

![image](https://github.com/calcom/cal.com/assets/34936929/ae623fd6-be47-43a1-bc90-7d382e267796)

**Comment by PeerRich** [comment]
can you post the link here?

**Comment by sundaram2021** [comment]
I think i got the issue

after creating the event , 
in the preview section  after setting the time and confirming it 
you are not getting any email of confirmation in your inbox

right @lawweiliang 


please correct me if i am wrong

**Comment by lawweiliang** [comment]
@sundaram2021 

> I think i got the issue
> 
> after creating the event , in the preview section after setting the time and confirming it you are not getting any email of confirmation in your inbox
> 
> right @lawweiliang
> 
> please correct me if i am wrong

Yes

**Comment by lawweiliang** [comment]
> Hi @PeerRich, Thank you for taking the time to read through the problems.
> 
> Here is the link. I need to remove the link

Everyone, please do not test the event using my previous link because it is live for my client usage and not for testing purpose, 
Go and create a link yourself and test it accordingly.
Thanks, everyone.

**Comment by Udit-takkar** [comment]
> now when I got the issue , @PeerRich can you assign me this so that i can start working

@sundaram2021 what is the issue that you find in the code? can you elaborate?

**Comment by sundaram2021** [comment]
The error is in production side , when to try to preview an event and after the sheduling the time
and entering the email of some attendee then you will get an error " Could not book the meeting ",
but when you see the bookings tab in home page the meeting is already scheduled without confirmation

In the developement side you can schedule  the meeting entering the email of some other attendee but here there
is problem in adding  video metting link

**Comment by sbouafif** [comment]
Hi @lawweiliang,

Did you fix the issue on your side? 

I had the same one trying cal.com for the first time. When I added a third party app I did not accept all the rights it was asking. This is what led to the error. Removing / reconfiguring the third party app fixed the issue on my side.

Looks like cal.com team is aware of that https://github.com/calcom/cal.com/issues/10432#issuecomment-1738620858

But not sure when/how will they fix it

**Comment by lawweiliang** [comment]
@sbouafif 
No, the problem is there. I think they need more time to fix the bug.  
At the moment, I have switched it to https://calendly.com/.

**Comment by Udit-takkar** [comment]
> The error is in production side , when to try to preview an event and after the sheduling the time and entering the email of some attendee then you will get an error " Could not book the meeting ", but when you see the bookings tab in home page the meeting is already scheduled without confirmation
> 
> In the developement side you can schedule the meeting entering the email of some other attendee but here there is problem in adding video metting link

@sundaram2021 yeah but i am not able to reproduce the bug. I created an event type with location as meeting link but i don't get "could not book the meeting"

**Comment by Udit-takkar** [comment]
@lawweiliang Looks like your google calendar integration are expired.

<img width="951" alt="Screenshot 2023-11-01 at 2 51 40 PM" src="https://github.com/calcom/cal.com/assets/53316345/5bd62ffc-7bb9-403c-a1ff-281a6c0be5ab">

After removing the calendar integration. I can book the event type. could you please connect your calendar again?

<img width="707" alt="Screenshot 2023-11-01 at 2 54 26 PM" src="https://github.com/calcom/cal.com/assets/53316345/66a7b782-fcbc-4857-9f0b-fbc8ce556bdf">

**Comment by Udit-takkar** [comment]
> Hi @lawweiliang,
> 
> Did you fix the issue on your side?
> 
> I had the same one trying cal.com for the first time. When I added a third party app I did not accept all the rights it was asking. This is what led to the error. Removing / reconfiguring the third party app fixed the issue on my side.
> 
> Looks like cal.com team is aware of that [#10432 (comment)](https://github.com/calcom/cal.com/issues/10432#issuecomment-1738620858)
> 
> But not sure when/how will they fix it

@sbouafif could you send me your cal username and event type url in which you are getting this error?

**Comment by lawweiliang** [comment]
[Udit-takkar](https://github.com/Udit-takkar)

> @lawweiliang Looks like your google calendar integration are expired.
> 
> <img alt="Screenshot 2023-11-01 at 2 51 40 PM" width="951" src="https://user-images.githubusercontent.com/53316345/279630800-5bd62ffc-7bb9-403c-a1ff-281a6c0be5ab.png">
> After removing the calendar integration. I can book the event type. could you please connect your calendar again?
> 
> <img alt="Screenshot 2023-11-01 at 2 54 26 PM" width="707" src="https://user-images.githubusercontent.com/53316345/279631526-66a7b782-fcbc-4857-9f0b-fbc8ce556bdf.png">

Thanks @Udit-takkar 

As far as what I remember. 
As long as I receive the invitation email, click "yes" over the invitation email. It will automatically add the event to my google calendar. I don't think I have done any integration in the past. Need your guidance on this.

**Comment by Ryukemeister** [comment]
Hey @lawweiliang, in order to check your calendar intergrations you can go under the settings page on the bottom left of cal webapp
<img width="227" alt="Screenshot 2023-11-01 at 3 38 24 PM" src="https://github.com/calcom/cal.com/assets/86043008/63822860-4779-4183-b5e5-07894f858319">

<img width="1710" alt="Screenshot 2023-11-01 at 3 35 59 PM" src="https://github.com/calcom/cal.com/assets/86043008/220ddfc0-a21b-495d-a48d-d9cb4ddfae3a">
Under your settings tab you'll see an option to see your calendars on the left side of your profile. The reason you weren't asked to do any calendar intergration might be because you maybe have signed up with a gmail account and so it already configured your google calendar as the default calendar.

**Comment by Udit-takkar** [comment]
@lawweiliang you might need the integration to check for conflicts with other events

**Comment by lawweiliang** [comment]
Thanks @Ryukemeister.

---

@Udit-takkar 
Questions
1. In future, how do I know whether the google calendars integration is expired or not?
2. How do I avoid this problem from happening again? Is there any tips for this? 

Thanks.

**Comment by lawweiliang** [comment]
@Udit-takkar 
This is another feature that maybe you could add-on in near future.

Scenario
When I remove the event in my Google calendar. 
The event over cal.com should be removed as well but now it is still there. 
Currently, I need to do double works, delete the event over google calendar then delete the event over cal.com. 

![image](https://github.com/calcom/cal.com/assets/34936929/b245d196-f75f-4807-b627-0ce13fccb13b)


![image](https://github.com/calcom/cal.com/assets/34936929/0e706fd8-d318-4baf-81da-00e3ff2bf190)

**Comment by Udit-takkar** [comment]
@lawweiliang I have now added a top banner when there is some issue with calendar connection

**Comment by lawweiliang** [comment]
> @lawweiliang I have now added a top banner when there is some issue with calendar connection

@Udit-takkar How can I try this? Is there any safe environment for me to test this function?

**Comment by Udit-takkar** [comment]
https://github.com/calcom/cal.com/pull/12532
