### ISSUE TITLE
Webhook settings list not having enough padding on the top

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11875]
![CleanShot 2023-10-13 at 13 00 03@2x](https://github.com/calcom/cal.com/assets/8019099/53f3468b-428d-433f-bb7d-afbac07265de)

List container also looks a bit weird

**Comment by harshN-17** [comment]
Hi, Can you tell me where is the file exactly located?

**Comment by Udit-takkar** [comment]
@harshN-17 just replace this line https://github.com/calcom/cal.com/blob/cbab279c3b3ad7f5618bd95c0008ee84b7cfcffc/packages/features/webhooks/pages/webhooks-view.tsx#L81 to 

borderInShellHeader={data && data.profiles.length === 1}

This is how it would look (if you are not part of any team)

<img width="1512" alt="Screenshot 2023-10-13 at 5 40 23 PM" src="https://github.com/calcom/cal.com/assets/53316345/58726ee4-b24f-4fa6-b324-fcbc1f05ba96">

**Comment by MeenuyD** [comment]
Thank you @Udit-takkar
