### ISSUE TITLE
[CAL-2615] Meeting url sometimes not working

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#11872]
In workflows, the {MEETING_URL} variable is sometimes empty. Investigate when this occurs and determine whether the meeting URL is visible in the confirmation email in such cases.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2615](https://linear.app/calcom/issue/CAL-2615/meeting-url-sometimes-not-working)</sub>

**Comment by technicalrutvik** [comment]
Can you show me proof? @CarinaWolli 
exactly where problem is coming?

**Comment by CarinaWolli** [comment]
That's what we need to investigate. I don't have any more info yet on when this happens, but some users reported that problem

**Comment by CarinaWolli** [comment]
Duplicate issue, here is some more information: https://github.com/calcom/cal.com/issues/10758
