### ISSUE TITLE
managed event types: be able to have your own limits

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11882]
![CleanShot 2023-10-13 at 15 16 54@2x](https://github.com/calcom/cal.com/assets/8019099/67b5f9ae-12df-406c-80bb-1f38056eff56)

as a non-admin member of a managed event-type it would be nice if people could still have their own buffers etc. for managed event-types

**Comment by PeerRich** [comment]
requested by enterprise customer

**Comment by rameshguditalu** [comment]
Hi @PeerRich, Can you elaborate the issue in more context. Thanks

**Comment by Chiranjeev-droid** [comment]
@PeerRich  So what all access to be given to non admin 
Editing these fields 
Before event buffer time
After event buffer time , minimum notice and time slot intervals , these only right??

Or these fields also
Limit booking frequency,Limit total booking duration,Limit future bookings, Offset start times
