### ISSUE TITLE
Add ability to set the team as a landing page

### ISSUE THREAD

**Issue by ecrode** [calcom/cal.com#11881]
### Is your proposal related to a problem?

Right now if we include the description of the website to book a meeting, we have to use a full URL: cal.our.domain/team/ours...
In our case we only have one team, and would like pople visiting cal.our.domain to see the team page right away.

### Describe the solution you'd like

Ability to designate a team to be the default landing page, whereas people visiting cal.out.domain would see the team page right away (via redirect for example)

### Describe alternatives you've considered

So far I was able to do this via nginx, but there is a few drawbacks, such as no clear link to a login page.
Note that the below section has a side fix of hiding admin user from the team list as it should not be a selectable option.

### Additional context

Here is an example of the nginx config I'm using:

```
	location = / {

		proxy_set_header Accept-Encoding "";
		sub_filter 'text-subtle' 'hidden';
		sub_filter '<a href="/caladmin">' '<a href="/" hidden>';
		sub_filter_once off;
		proxy_pass $srv/team/ourteamname;
		proxy_set_header Cookie $http_cookie;
	}

	location = /auth/login {
		rewrite ^ /bookings/upcoming? permanent;
		proxy_pass $srv;
		proxy_set_header Cookie $http_cookie;
	}
```

**Comment by PeerRich** [comment]
can you try the react embed, make it full screen and add the link to it? 

https://codesandbox.io/s/inline-demo-react-for-docs-forked-3hznnl?file=/src/App.js
