### ISSUE TITLE
Add wrong or cross button to exit from embed option

### ISSUE THREAD

**Issue by RUPAKparajuli07** [calcom/cal.com#11899]
Feature Request: Add an Exit Option for Embedded Calendars in Cal.com

Explanation:

Background:
Cal.com is a widely used tool for embedding calendars into various platforms, such as GitHub issues. While this feature greatly enhances collaboration and organization, it currently lacks a convenient exit option within the embedded calendar view.

Feature Request:
I propose the addition of a "Wrong" or "Cross" button to the embedded calendar interface, which would allow users to easily exit the embedded view and return to the parent page.

Rationale:

1. Improved User Experience: The addition of an exit button would significantly enhance the user experience by providing a clear and intuitive way to leave the embedded calendar view. Currently, users may find it challenging to navigate away from the embedded calendar, which can lead to frustration.

2. Consistency with UI Norms: Many web applications and websites adhere to common UI norms by including a close or exit button to allow users to return to the previous page or view. Adding this feature would align Cal.com with these established user expectations.

3. Accessibility and Inclusivity: An exit button can also benefit users with disabilities who rely on screen readers or keyboard navigation. It would make the embedded calendar view more accessible by providing an explicit option for exiting the embedded view.

4. Reduced Confusion: Sometimes, users may resort to browser navigation options, which can be confusing and may result in unexpected behavior. The presence of an exit button would make the process more straightforward and reduce confusion.

Implementation:

The implementation of this feature should be straightforward. A clearly visible "Wrong" or "Cross" button could be added to the embedded calendar view, either as a standalone button or integrated into the existing user interface. When clicked, this button will return the user to the previous page.

Conclusion:
Adding an exit option within embedded calendars on Cal.com is a small but valuable enhancement that can significantly improve the user experience and accessibility of the platform. We believe this feature would be appreciated by the Cal.com community and contribute to a more user-friendly interface for embedded calendars, especially in applications like GitHub issues.

![image](https://github.com/calcom/cal.com/assets/110843279/13864536-6667-4b8e-8a31-a0cd889ea657)

**Comment by Rajesh270712** [comment]
Hey , If no one is working on this feature. Can you assign it to me I will work on this.

**Comment by Subhahdip** [comment]
@Rajesh270712 how to reproduce the issue?

**Comment by parteekmalik** [comment]
if you click outside the box it disappear automatically . so no need of button

**Comment by RUPAKparajuli07** [comment]
@parteekmalik if you click ctrl+W then the currently open tab of the browser co why there is a cross button.



![Screenshot 2023-10-15 153317](https://github.com/calcom/cal.com/assets/110843279/4e9135e3-e9fb-4043-8fb4-7a27549c9a46)

**Comment by PeerRich** [comment]
we dont need an X button for this. you can just exit by clicking out of the dialog.

we could add a "Close" button where the primary button area is but I don't even think that's needed
