### ISSUE TITLE
regression: FAB wrong side

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11896]
should be on the right 

![image](https://github.com/calcom/cal.com/assets/8019099/5b941995-fa0e-4047-a818-59a0fcc9844c)

**Comment by MeenuyD** [comment]
Hello @PeerRich where you find these because i can not see it is correct
<img width="308" alt="Screenshot 2023-10-15 at 7 29 47 AM" src="https://github.com/calcom/cal.com/assets/116630390/05d0faff-1125-4c97-b1ef-ce23d8d90bd6">
