### ISSUE TITLE
regression: icon in dialog wrong padding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#11897]
![image](https://github.com/calcom/cal.com/assets/8019099/d602205d-57b9-41a4-a8b7-567eee8c7b21)

**Comment by Siddharth-2382** [comment]
@PeerRich I tried recreating this and the padding seems to be fine. Maybe a glitch? Yesterday I was on login page and the `password` and `Forgot?` were getting overlapped on safari but wasn't a issue on chrome.
