### ISSUE TITLE
CORS error: refused to execute inline script

### ISSUE THREAD

**Issue by bedus-creation** [calcom/cal.com#11909]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Thanks for the great tools! I found the following console error when visiting the simple booking page. 
https://cal.com/bedram-tamang-cjhzti/15min?month=2023-10&duration=15

![image](https://github.com/calcom/cal.com/assets/25701752/3c475022-e5bb-4ce2-b58e-2de4986159f4)

**Comment by PeerRich** [comment]
seems like CORS cc @hariombalhara

**Comment by PeerRich** [comment]
i am getting the error too https://cal.com/peer/30min?duration=30&month=2023-10

**Comment by PeerRich** [comment]
we can ignore this error for now
