### ISSUE TITLE
Integration with outlook.com calendar fails all the time.

### ISSUE THREAD

**Issue by GentleHoneyLover** [calcom/cal.com#11913]
### Issue Summary

Might be related to this issue: https://github.com/calcom/cal.com/issues/7777

I'm using a free hosted cal.com plan. Connecting my outlook.com calendar. It connects and works for about an hour, then I get this:<br>
<img width="960" alt="Снимок экрана 2023-10-16 в 12 56 58" src="https://github.com/calcom/cal.com/assets/38346023/31e22a8c-f103-4883-acad-54ccd73a1a06">

Obviously all scheduling fails:<br>
<img width="630" alt="Снимок экрана 2023-10-16 в 13 09 52" src="https://github.com/calcom/cal.com/assets/38346023/279cfe30-b249-424c-a16f-376a6f7b322e">

When I delete integration from cal.com and add it again it works for another hour or so and then fails the same way.

When I look at the Microsoft account, it shows no issue:

<img width="1545" alt="Screenshot 2023-10-16 в 10 59 06" src="https://github.com/calcom/cal.com/assets/38346023/d4824ecd-3507-4fd8-88b6-ee728c159627">

Please help!

Thanks!

### Steps to Reproduce

1. Connect the outlook.com calendar to cal.com
2. Wait for about an hour
3. Cal.com reports that there's a problem with the outlook calendar integration.
4. Delete outlook integration from cal.com and add it back.
5. Integration works for about an hour and then fails the same way

### Technical details

- Running a free cal.com hosted plan
- Paid Microsoft 365 family subscription with custom GoDaddy domain associated with it

### Evidence

- See screenshots above

**Comment by Udit-takkar** [comment]
@GentleHoneyLover thanks for reporting this issue. @joeauyeung is already working on this https://github.com/calcom/cal.com/pull/11862

**Comment by GentleHoneyLover** [comment]
@Udit-takkar, @joeauyeung, thanks! Can't wait for the solution to go into production!!!
