### ISSUE TITLE
Uploading profile picture doesn't work

### ISSUE THREAD

**Issue by reboottime** [calcom/cal.com#11910]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Updating user's picture doesn't work at cal.com

### Steps to Reproduce

1. Went to page https://app.cal.com/settings/my-account/profile
2. Click Update avatar right close to the avatar icon
3. Upload a picture via clicking the choose picture from the picture updating button
4. Get successful picture uploading indicator

### Actual Results

Refreshing the page, the picture I just uploaded doesn't show up correctly

### Expected Results

After I get successfully uploaded picture UI indicator,  my uploaded picture should be reflected on my profile avatar area.

### Technical details

chrome browser, I believe this issue also happens on any browsers ( as a frontend dev)

### Evidence

- visit user's profile page, try to upload a picture as the user's profile picture
- refreshing page and the uploaded picture is not showing correctly

**Comment by Subhahdip** [comment]
@reboottime I just tried reproducing the issue. Everything works fine for me. Can you upload a video with the describing the issue?

**Comment by v11t** [comment]
happens for me as well (on a self-hosted docker instance)

**Comment by v11t** [comment]
what helped me fix it temporary (get the avatar to show in the profile and on the scheduler page), was to follow the steps below:
1. /settings/my-account/profile -> click on 'Upload picture' and select the wanted picture 
2. Hit 'Update' on the bottom of the card, wait for it to finish the rpc call
3. Open the console, then right click on the Chrome refresh button, then click on 'Empty cache and hard reload' 

hope this helps

**Comment by PeerRich** [comment]
we are on it,  there is a PR in the making

**Comment by Zackhardtoname** [comment]
> v11t

That unfortunately didn't work for me on Chrome Version 118.0.5993.117(mac)

**Comment by johosbm** [comment]
I am facing the very same issue. Any updates?

**Comment by leoatflowdigital** [comment]
It seems this issue is closed?

**Comment by cosedimarketing** [comment]
Any news guys? I have the same issue. Tested on several browsers from desktop and mobile too.

**Comment by johosbm** [comment]
Here it's somehow worked after a while

**Comment by hemeshvpatel** [comment]
+1 - Having the same issue

**Comment by maxhoffmann** [comment]
same problem here

**Comment by Tanaykmr** [comment]
Still facing the same issue.
Using Google Chrome Version 138.0.7204.93 (Official Build) (arm64)

**Comment by hbjORbj** [comment]
@Tanaykmr Please upload a screencast showing that the avatar change doesn't work. Works for me as expected.

**Comment by dusanradojcic00** [comment]
I have the same problem still

**Comment by joseph24a** [comment]
exact same issue for me what am I supposed to do
