### ISSUE TITLE
[CAL-2986] After migration appears error connecting to engine PostgreSQL

### ISSUE THREAD

**Issue by scebll** [calcom/cal.com#11911]
### Issue Summary

We have recently upgraded from version 3.1.9 to version 3.3.9 and since the upgrade we are seeing many errors in the console that are flooding the service and appears randomly some seconds/minutes after start.

Apparently it appears to be connecting to a database on localhost (::1) when we are using an external postgresql outside of even the kubernetes service where it is running.

This has been running for the past months without problem at all.

Could it be that some change has been made that I missed in the changelog and is producing this error? There's not much detail either and even increasing the debug level doesn't show any errors other than these lines.

### Steps to Reproduce

It also appears that the update migrations have been successful (or so we believe) and we are not able to reproduce the error as such, it just appears.

1. Container starts
2. A few seconds/minutes later the error starts to appear.

### Actual Results

- No errors at all.

### Expected Results

- A more detailed of the error or the error not-present at all.

### Technical details

- Cal.com version 3.3.9.
- PostgreSQL 13.5.
- Kubernetes 1.26.8 (rke2r1) (we know that is build for docker, but runs smoothly so far).

Current environment variables are like this:

```
CALENDSO_ENCRYPTION_KEY: <hidden>
DATABASE_URL: postgresql://calcom:password@postgres.database.dns/calcom
EMAIL_FROM: <hidden>
EMAIL_SERVER_HOST: <hidden>
EMAIL_SERVER_PASSWORD: <hidden>
EMAIL_SERVER_PORT: "587"
EMAIL_SERVER_USER: <hidden>
JITSI_HOST_URL: <hidden>
NEXT_PUBLIC_LICENSE_CONSENT: true
NEXT_PUBLIC_WEBAPP_URL: <hidden>
NEXTAUTH_SECRET: <hidden>
NODE_ENV: production
```

### Evidence

The error is this one:

```
@calcom/web:start: error connecting to engine: sql, type: postgres db: Error: connect ECONNREFUSED ::1:5432
@calcom/web:start: error connecting to engine: sql, type: postgres db: Error: connect ECONNREFUSED ::1:5432
@calcom/web:start: error connecting to engine: sql, type: postgres db: Error: connect ECONNREFUSED ::1:5432
[..]
```

Attached the log of the application running.

[calcom-calcom-app-6bcfd55fc5-m4r66-1697453038413861000.log](https://github.com/calcom/cal.com/files/12915350/calcom-calcom-app-6bcfd55fc5-m4r66-1697453038413861000.log)

<sub>[CAL-2986](https://linear.app/calcom/issue/CAL-2986/after-migration-appears-error-connecting-to-engine-postgresql)</sub>

**Comment by PeerRich** [comment]
it looks like it cant connect to the database. did something change?

**Comment by gitwittidbit** [comment]
Seeing this, too, after upgrading to 3.3.7 (docker).

The only (conscious) change was this upgrade.

**Comment by notflip** [comment]
Same here! I keep seeing this logged in the console, on the latest version (the app does seem to work?)

**Comment by rtpa25** [comment]
Fixed this if you check logs inside the postgres container it said  
![Screenshot 2023-10-20 at 7 10 02 AM](https://github.com/calcom/cal.com/assets/72537293/2ceeedd5-b132-49c3-ae79-73ce5aee7808)
After some tweeks to the docker compose file inside the prisma package 
![Screenshot 2023-10-20 at 7 14 01 AM](https://github.com/calcom/cal.com/assets/72537293/27a514ef-6a13-4366-91ac-cbd6df8f2711)
Making a pr asap

**Comment by gitwittidbit** [comment]
Thanks rtpa25

But in my case, I did and do not see the errors in the database container log you are showing in your second screenshot. The logs of my database container do not contain anything suspicious at all.

So yours might be a different issue than mine :(

**Comment by rtpa25** [comment]
Second container ss is all good first one is the actual issue that is being discussed, for which I shot a PR

**Comment by gitwittidbit** [comment]
Sorry, I meant the first screenshot (the of your database container).
I don't see those errors in my database container.

**Comment by rtpa25** [comment]
Sorry for the late reply @gitwittidbit can you share your container logs, and further can you try the changes in https://github.com/calcom/cal.com/pull/12010 in your local system to test if it solves the problem?

**Comment by gitwittidbit** [comment]
> Sorry for the late reply @gitwittidbit can you share your container logs, and further can you try the changes in #12010 in your local system to test if it solves the problem?

Well, I just pulled the current docker images and - what can I say? The error is gone. My logs are not flooded anymore with the error connecting to engine.

Guess your fix did the trick. Thanks!

**Comment by icsy7867** [comment]
I am getting these errors as well.

Settings are saving, but it looks like things are trying to connect on localhost ipv6?  Very strange.

**Comment by cpunnelliehealth** [comment]
I'm getting this error as well. Connection is fine to the db and it's retrieving and saving data okay, but it still shows this error about once every two seconds:

@calcom/web:start: error connecting to engine: sql, type: postgres db: Error: connect ECONNREFUSED ::1:5432

**Comment by icsy7867** [comment]
> I'm getting this error as well. Connection is fine to the db and it's retrieving and saving data okay, but it still shows this error about once every two seconds:
> 
> @calcom/web:start: error connecting to engine: sql, type: postgres db: Error: connect ECONNREFUSED ::1:5432
> 
> I'm not running in a docker container.

The only thing I can see that references local host and 5432 (postgres port) is this
https://github.com/calcom/cal.com/blob/c6f26f2a2a488195292505e77c47db9b83a862ed/.github/actions/cache-db/action.yml#L6

**Comment by cpunnelliehealth** [comment]
I found another issue thread with the same issue and came across this fix -- it seems to work for me and resolved this issue:

https://github.com/calcom/cal.com/pull/12437

**Comment by sneko** [comment]
Also having this issue after upgrading... waiting for an official fix 👍

**Comment by xcellentavi** [comment]
I'm also getting the flood of ECONNREFUSED when trying to log in.  If I don't navigate to /auth/login page, it doesn't show up.  I think it's related to the NEXTAUTH_URL variable.  If I use http://serverIP:PORT/api/auth, then I get these errors.  If I change to https://my.domain.com/api/auth, no issues logging and or getting any ECONNREFUSED errors.  However, the client fetch error eventually surfaces which is only resolved by switching back to http://serverIP:PORT/api/auth.

Any advice or is this just me?

**Comment by kart1ka** [comment]
I am getting the same error too. Although I am using supabase cloud db instead of docker container.
