### ISSUE TITLE
[Feature] Make the dropdown menu to come back to its original form

### ISSUE THREAD

**Issue by ShashankMPatil** [calcom/cal.com#11924]
### Issue Summary

The dropdown menu in the documentation page fails to return to its default state upon a double-click or when clicking on the arrow button. It remains open, creating a usability issue and preventing users from collapsing the dropdown as expected.

### Steps to Reproduce

1. Go to DOCS page
2. Observe by clicking on the dropdown menus present on the side bar

### Actual Results

- Dropdown menus doesn't return to their original form when clicked, or when clicked on the arrow button 

### Expected Results

- Dropdown menus should return to original form when clicked or when clicked on the arrow button

### Evidence

- https://github.com/calcom/cal.com/assets/135035523/5c99f7cb-3205-421e-8bc2-35dd28cfacce

**Comment by Keerthivardhan1** [comment]
The original functionality implemented is like 
the dropdown menu will return to its original position only after clicking on other option / other dropdown menu.
If I am not wrong, you're trying to convey that 
if we click on the dropdown menu which is “open”, it should be closed.
If yes, this will not be the bug, it is a kind of feature.
I would like to work on this issue.

**Comment by ShashankMPatil** [comment]
I appreciate your correction, @Keerthivardhan1. My mistake.

**Comment by Keerthivardhan1** [comment]
I would like to take this issue
