### ISSUE TITLE
Allow cancellation for Past time slots

### ISSUE THREAD

**Issue by reachkrishnaraj** [calcom/cal.com#11922]
### Is your proposal related to a problem?

  400 error when cancelling past time slots.

We should be able to cancel Past time slots.

### Describe the solution you'd like

Allow past time slots with out error. Allow psuedo-cancel atleast(meaning, just updating the status as noop.) and send webhook.

Rationale:
- clients like us use cal com for direct consumer bookings. In our case, healthcare bookings. We acquire customer via multiple social channels including google. We teach google seo model good and bad bookings. We use no show annotation on a booking while cancelling and stream the data to Google Analysis via a custom data pipeline. 
Hence allow cancellation of past slots without causing 400

**Comment by Siddharth-2382** [comment]
@PeerRich Can you provide some directions for this issue if it's ok. I would like to work on this one.

**Comment by Chandanmali** [comment]
@PeerRich Can you provide some directions for this issue if it's ok. I would like to give it a try.

**Comment by JiyaGupta-cs** [comment]
@PeerRich I think this should be closed since it's solved
