### ISSUE TITLE
[CAL-2905] Autocomplete in person event location

### ISSUE THREAD

**Issue by supalarry** [calcom/cal.com#11931]
### Is your proposal related to a problem?

If a person wants to schedule an in-person event then there is juggling between writing the location and then googling it to make sure that it's the right place.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6acc8604-9b2c-47ff-9efb-6a7c736e4108/8ead83cd-bd53-4f0a-a289-67a05329ab2f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82YWNjODYwNC05YjJjLTQ3ZmYtOWVmYi02YTdjNzM2ZTQxMDgvOGVhZDgzY2QtYmQ1My00ZjBhLWEyODktNjdhMDUzMjlhYjJmIiwiaWF0IjoxNzA0OTAyMzg1LCJleHAiOjE3MDQ5ODg3ODV9.dijxhkj8u4uy_gWmF-MWhA4HN8Wsf8H4j0nhDrM3pJU)

Imagine a tour guide who wants to start the tour at a specific statue - he / she needs to google it, then copy it's address and then paste it in "Location" field.

### Describe the solution you'd like

Autocomplete for the location:

![Screenshot 2023-10-17 at 09 41 12](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6ab01ace-40f7-4e2d-b4a7-ae180db33f88/57f39743-e27a-425c-9860-a122d0612212?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82YWIwMWFjZS00MGY3LTRlMmQtYjRhNy1hZTE4MGRiMzNmODgvNTdmMzk3NDMtZTI3YS00MjVjLTk4NjAtYTEyMmQwNjEyMjEyIiwiaWF0IjoxNzA0OTAyMzg1LCJleHAiOjE3MDQ5ODg3ODV9.vI2TciWE3_ZheDkHiZPuRk5DsEl8bdT-LdlBGLrb7Bo)

Bonus: would be cool if when booking the event the place is seen in map that is clickable and takes to google maps.

### Describe alternatives you've considered

As far as I remember Calendly does not have this feature.

### Additional context

Most probably implemented using [Google's Place Autocomplete](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2905](https://linear.app/calcom/issue/CAL-2905/feature-autocomplete-in-person-event-location)</sub>

**Comment by PeerRich** [comment]
i wonder if there is a more API based approach so the dropdown looks nicer (dark mode too) 
![CleanShot 2023-10-17 at 11 15 27@2x](https://github.com/calcom/cal.com/assets/8019099/676af0d2-6076-4c40-b1d2-4b6d1cf92d84)

**Comment by manish-singh-bisht** [comment]
@PeerRich  by api based you mean that we custom create the dropdown and use the api for the results?

**Comment by SomayChauhan** [comment]
we can just add custom styles to the existing classes, worked for me in past,
may need to add !important

**Comment by stylessh** [comment]
Will try to add the autompletion through api, and integrate it with the proper design :)

**Comment by keithwillcode** [comment]
We decided to not go with this feature because of the added dependency and need for a Google plan.
