### ISSUE TITLE
feature: social icons for cal.com/user page

### ISSUE THREAD

**Issue by supalarry** [calcom/cal.com#11933]
I imagine having cal.com/user as a virtual business card where people can get to know me and schedule a meeting, so I think it would be useful to be able to add links to your socials and private webpage, and then for them to show up as icons on your cal.com/user page.

Before:
<img width="1507" alt="Screenshot 2023-10-17 at 09 47 04" src="https://github.com/calcom/cal.com/assets/42170848/006431a6-5faa-4b2c-8976-1405112366db">

After:
<img width="1508" alt="Screenshot 2023-10-17 at 09 49 35" src="https://github.com/calcom/cal.com/assets/42170848/6819d2b9-870c-4c97-9b81-e8de9e08a327">

### Additional context

Probably best place to add social and personal webpage links would be in "My Settings" -> "Profile" as a new section "Links" that have input field for twitter, personal webpage etc.

**Comment by PeerRich** [comment]
we thought about this before, the thing is, i think its a slippery slope that people keep asking for more link types and icons and i dont know if we wanna compete with all the "link in bio" products out there

**Comment by Gourav2609** [comment]
Can i work on this issue

**Comment by supalarry** [comment]
@PeerRich I see your point. I do think that with LinkedIn, Twitter, GitHub and personal website page it covers 80% of use cases and that's good enough imo.

**Comment by ShakshiAgl** [comment]
i am working on this issue

**Comment by AdityaSingh-02** [comment]
Hey @supalarry, @PeerRich I would Like to work on this issue, Please assign me.

**Comment by PeerRich** [comment]
we've decided to not work on this for now. we are not a link sharing platform
