### ISSUE TITLE
Doesn't receive confirmation email in local setup when i am logging with my own id

### ISSUE THREAD

**Issue by sundaram2021** [calcom/cal.com#11954]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

while logging in with my own email id i didn't receive any confirmation email

### Steps to Reproduce

1. set up cal.com locally
2. and try to log in with your email id

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- confimation email should be there in the inbox

### Technical details

- Google Chrome
- Node.js  18 >.

### Evidence

- just produce this by yourself

**Comment by PeerRich** [comment]
are you missing some .env variables? did you setup an email service?

**Comment by Siddharth-2382** [comment]
are you using docker image?

**Comment by sundaram2021** [comment]
Yes I am receiving email at localhost:8025

but now my question is why am i receiving email at port 8025 instead of my google email inbox

**Comment by sundaram2021** [comment]
It's weird.......

> Because it is localhost. And docker image is running in your machine.
