### ISSUE TITLE
Issues with bad data -> gaps in the consumer api exposed by cal.ai

### ISSUE THREAD

**Issue by DexterStorey** [calcom/cal.com#11957]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

This issue is an aggregate of several reports of cal.ai not being able to fetch bookings and in rare cases, event types.

This is likely because those accounts have at least one "bugged" meeting in the past. The way the GET /bookings consumer api works - is it returns ALL meetings ever - possibly paginated? But at the very least - a ton of meetings from the past.

If there is a single booking with malformed data -> it can error. Not sure but it's possible it times out if you have booked a ton of meetings.

Note: This is likely not a bug with cal.ai - but since cal.ai is many users' first interaction with the consumer api - it is exposing historically bad data in the DB / gaps in the api that do not get flagged when just using the frontend.

Note 2: This issue seems to disproportionately affect power users, early adopters and cal team, investors, etc. Since those are the accounts that have tested beta features or been around long enough to have experienced migrations.

We cannot reproduce this naturally with new accounts.

### Steps to Reproduce

*TO TEST IF YOU HAVE BUGGED BOOKINGS*

1. [Create an API KEY here](https://app.cal.com/settings/developer/api-keys)
2. Navigate to https://api.cal.com/bookings?apiKey=[YOUR_API_KEY]
4. If the page does not load or returns an error, you have at least 1 bad historical meeting or (possibly) too many meetings

*TO CREATE A BUGGED BOOKING FOR TESTING*

- On Local, POST to the /bookings route with a number in the userId section of responses (supposed to be a string). This api call won't fail but should since you are supposed to pass userId as a string.
<img width="506" alt="Screenshot 2023-10-17 at 4 30 22 PM" src="https://github.com/calcom/cal.com/assets/36115192/afd91d50-b921-402c-81d9-34f485a0b6c1">

- Watch as the data is inserted into the db improperly in prisma studio with `yarn db-studio`
<img width="428" alt="Screenshot 2023-10-17 at 4 30 31 PM" src="https://github.com/calcom/cal.com/assets/36115192/941d2bee-42ad-43e2-8aa2-c90fb8e1abd0">

*UPDATE* This method no longer works to break getBookings locally, so I'm not sure exactly how to reproduce breaking getBookings locally anymore.

This video is additional proof of a bugged booking in prod:
https://github.com/calcom/cal.com/assets/36115192/9c1951c8-05a7-4a12-87cd-6f9df925bc77

@PeerRich, @DexterStorey, @tedspare and others have this bug in prod.

### Actual Results

In Cal.ai:
<img width="654" alt="Screenshot 2023-10-17 at 3 35 39 PM" src="https://github.com/calcom/cal.com/assets/36115192/eed856ba-106e-42bd-8564-ed14c87365f0">

With API directly:

`{"message":"An error occured while querying the database."}`

OR

<img width="1102" alt="Screenshot 2023-10-17 at 3 51 32 PM" src="https://github.com/calcom/cal.com/assets/36115192/08e86931-fbab-4e38-b092-54ab65884785">

### Expected Results

- You have 2 meetings today...

### Ideas

- It seems too many users are effected to manually clean the data - unless a util is built.
- Loosening zod types on the consumer api could work but isn't super clean (although the zod types should be looked at since you can currently pass bad data to createBookings without error / validation)
- Adding "dateFrom and dateTo" to the getBookings api could be the way. [We already filter the response in cal.ai](https://github.com/calcom/cal.com/blob/59fa713549e38aa92161499e171b74cceb9f578b/apps/ai/src/tools/getBookings.ts#L42) (because if we gave the AI all the meetings it would be too much text). So we could just implement something similar in the consumer API (that way past meetings wouldn't be fetched 99% of the time)

(just some ideas! - let's brainstorm!)

### Evidence

- Tested with cal.ai "What meetings do I have today" and using the consumer api at api.cal.com

**Comment by DexterStorey** [comment]
This is pretty dense but did my best to outline the issue as simply as possible. @PeerRich, @zomars, @emrysal, @keithwillcode -> I think this might be a cool opportunity to improve the consumer API and would have high ROI impact on cal.ai as well as lots of other integrations that make use of the consumer api! Wouldn't be surprised if getting to the bottom of this ends up accidentally fixing a bunch of stale issues across the repo. 🤝🫨

**Comment by zomars** [comment]
I think a carefully thought migration/script could get us 80% there. Just need to take a dive to investigate and find the faulty data first.

**Comment by matthijs-relay** [comment]
At [Relay.app](https://www.relay.app) we recently launched a cal.com integration that uses `/bookings`, and we've now encountered several users (pretty much all of them that have tried it) that aren't able to use the cal.com integration because the endpoint returns `An error occured while querying the database.` for them.

Is there any fix on the horizon for this? We'd also be happy with the suggested `dateFrom`/`dateTo` workaround for now, but we're not able to rely fully on just webhooks for some of our functionality (like trigger previews) so until this is fixed, it's hard for us to provide a full-featured integration.

**Comment by husseyexplores** [comment]
I'm also constantly getting 400 status code with this response:

{
  "message": "An error occured while querying the database.",
  "error": {}
}

I've tried this with multiple accounts, multiple endpoints (GET users, event-types, books etc) - all resulting in the same error.

**Comment by husseyexplores** [comment]
I'm constantly getting 400 status code with this response:

```json
{
  "message": "An error occured while querying the database.",
  "error": {}
}
```
I've tried this with multiple accounts, multiple endpoints (GET users, event-types, books etc) - all resulting in the same error.
