### ISSUE TITLE
[CAL-2620] Overlay calendar - no error when access token expired

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#11964]
LGTM. 

Just one thing I don't get any warning or error when my calendar credentials are broken. I only see it after opening calendar settings

<img width="1509" alt="Screenshot 2023-10-18 at 3 42 39 PM" src="https://github.com/calcom/cal.com/assets/53316345/6b36c444-9f73-4cd1-872e-9e9aa8843686">

<img width="1509" alt="Screenshot 2023-10-18 at 3 42 52 PM" src="https://github.com/calcom/cal.com/assets/53316345/649e3d66-803d-4ee0-8999-d6cf0f2bf883">

_Originally posted by @Udit-takkar in https://github.com/calcom/cal.com/pull/11961#pullrequestreview-1684664312_
            

<sub>[CAL-2620](https://linear.app/calcom/issue/CAL-2620/overlay-calendar-no-error-when-access-token-expired)</sub>

**Comment by imkuldeepahlawat** [comment]
Hii Team, can i start work on that

**Comment by Udit-takkar** [comment]
@Pratik-Kumar-621 first connect your calendar then start prisma studio with yarn db-studio and then go to 'Credential' table and make some random changes in acess_token and refresh_token
