### ISSUE TITLE
[CAL-2618] Add tests to `handleSeats`

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#11971]
This will require a refactor of `handleNewBooking` and `handleSeats` as both functions are tied very closely together.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2618](https://linear.app/calcom/issue/CAL-2618/add-tests-to-handleseats)</sub>

**Comment by pankajsajwan12** [comment]
can you assign me this issue also please explain a little more.

**Comment by jayam30** [comment]
can you assign me this issue

**Comment by Rohxn16** [comment]
what exactly is the change that we need to make?

**Comment by Jayanth-Kammela** [comment]
Can please you assign this for me?

**Comment by codesmith922** [comment]
handleSeats is a mammoth 600 lines function. Deserves its own file and test suite.

**Comment by AnuragM23** [comment]
can you please elaborate on the issue
