### ISSUE TITLE
[CAL-2625] Duplicate labels for Destination Calendar

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#11988]
![image](https://github.com/calcom/cal.com/assets/1780212/121be4d9-e306-4885-adeb-72f1afc89e7c)
<sub>[CAL-2625](https://linear.app/calcom/issue/CAL-2625/duplicate-labels-for-destination-calendar)</sub>

**Comment by Siddharth-2382** [comment]
@hariombalhara Can I raise a PR?

**Comment by Siddharth-2382** [comment]
Are we expecting just `Google Calendar - example@gmail.com` instead of `example@gmail.com (Google Calendar - example@gmail.com)`
