### ISSUE TITLE
Google meet shows cal video link

### ISSUE THREAD

**Issue by shawshankkumar** [calcom/cal.com#11984]
### Issue Summary

I made a event and when people booked it, it should have shown a google meet link which i selected but it actually shows a cal link but the text says google meet

(will add videos and more soon, in hurry for some other work)

### Technical details

- app.cal.com

### Evidence

<img width="737" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/2134c4ec-a501-4b19-be49-5590a85d4d11">

**Comment by manpoffc** [comment]
Hey @shawshankkumar ,
I tried to reproduce your steps. I did it using two different methods:
1. With setting location as Link other meetings.
2. With installing and integrating google meet.
In both the cases the link was showing meets link.
Please show the steps you followed so I can follow along and see what’s wrong.

**Comment by Udit-takkar** [comment]
@shawshankkumar  can you check you google calendar integration if it has been revoked or expired? 
If it is fine can you send me your cal username ?

**Comment by shawshankkumar** [comment]
> @shawshankkumar can you check you google calendar integration if it has been revoked or expired? If it is fine can you send me your cal username ?

Yeah sure. Discord?

**Comment by Udit-takkar** [comment]
@shawshankkumar  here or discord DM

**Comment by Udit-takkar** [comment]
Update:- 

Can't reproduce the bug on that event type

**Comment by shawshankkumar** [comment]
@Udit-takkar yup yup, once i tinkered with the meet and calendar app, it started working and new bookings show the meet link, but the old ones still show cal video

for example the person who booked a few days ago got this in the mail:
<img width="649" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/6c9b3d54-4cf3-4936-9f42-dcf30036d1e2">

where as i got this today :

<img width="659" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/3546efe9-9844-4cfe-b93f-5479ef428633">


So it seems it is an issue with one of the apps' sessions expiring, tho i dont think this is how it should be handled .

Lemme know if i can help out

**Comment by shawshankkumar** [comment]
one more issue btw @PeerRich @Udit-takkar 

When i hover over the meet link in /bookings/upcoming they show a different link:
<img width="445" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/cecfc956-5751-40b9-be7c-faec3d6636f5">


and if i open the same in their booking page, it shows a different link.

intentional? If not, i would love to help fix it!

**Comment by shawshankkumar** [comment]
Hey @Udit-takkar @PeerRich if the team is working on other priority issues, i would love to help fixing this, can i get some help (or a start) on this? Like where should i begin for starters

**Comment by Udit-takkar** [comment]
> Hey @Udit-takkar @PeerRich if the team is working on other priority issues, i would love to help fixing this, can i get some help (or a start) on this? Like where should i begin for starters

the last issue(https://github.com/calcom/cal.com/issues/11984#issuecomment-1772927163) has been fixed. I am still looking into why you got cal video meeting url when google calendar integration was not expired.

**Comment by Udit-takkar** [comment]
@shawshankkumar are you able to reproduce the bug again locally or on app.cal.com ?

**Comment by shawshankkumar** [comment]
hey, no not on cal ofcourse, but i haven't tried locally (not completely
sure how to expire the meet app session)
