### ISSUE TITLE
Not all bookings are displayed on bookings page

### ISSUE THREAD

**Issue by marvinhomburg** [calcom/cal.com#11994]
### Issue Summary

- We have a fully booked event today and cannot access the booking list to see all attendees. The event is running from 9am to 4pm today and I can only view the booking until 12pm. “Load more results” doesn’t work.
- We can only see bookings for the upcoming 60 minutes.
- We can confirm that bookings are created and confirmed as we have received confirmation emails.

### Steps to Reproduce

1. Go to **bookings**
2. Go to **upcoming**
3. Click on **load more results**

I need to see the full list for the day. The event is booked out

### Actual Results

- I only see all bookings until 12pm instead of until 4pm

### Expected Results

- Show all bookings and attendees

### Technical details

- Tested in different browsers and browser versions

### Evidence
![Limited list of bookings](https://github.com/calcom/cal.com/assets/46927005/a38e51ed-0fc5-4ce5-91e9-216c3bc5f92a)

**Comment by Siddharth-2382** [comment]
Did you tried `load more results` at the bottom?

**Comment by marvinhomburg** [comment]
Yes. It did not work as expected.
When you click the button several times it is disabled und you have to refresh the page.

**Comment by PeerRich** [comment]
investigating!

**Comment by keithwillcode** [comment]
@marvinhomburg. I cannot reproduce this. Is it still happening for you?

**Comment by mrdarboe** [comment]
I am currently experiencing this same issue. What was the resolve?
