### ISSUE TITLE
Show occupied/not-available slots as grayed out, instead of hiding them

### ISSUE THREAD

**Issue by notflip** [calcom/cal.com#12004]
### Is your proposal related to a problem?

Would it be possible to show all blocks, but show the occupied/not-available ones as grayed out, instead of not-showing them, this way the bookers do see that there are meetings at this point, but they're only not available.

### Describe the solution you'd like

An option/checkbox to show all booking slots, or hide the occupied ones

**Comment by codesmith922** [comment]
IMO, hiding unavailable slots is a cleaner interface. 
Do you think this option to show all booking slots should be available to the calendar owner or the one who is booking a slot?

**Comment by tedspare** [comment]
Maige label this

**Comment by notflip** [comment]
The calendar owner, it would be nice to show our bookers that we're fully booked for that day, instead of maybe not having any slots available. This way they know we're normally available at this time, but fully booked, as opposed to maybe not working for that period.

**Comment by PeerRich** [comment]
I think hiding is a lot better for clarity
