### ISSUE TITLE
Can't connect to a Zoho Calendar

### ISSUE THREAD

**Issue by sergiodevelop78** [calcom/cal.com#12006]
Found a bug? Please fill out the sections below. 👍

### Can't connect to a Zoho Calendar

I am inserting the data the Web asks for the connection, but in the end I get an error: **"Could not add this caldav account".**
I tried adding this same calendar into the Thunderbird program on my PC, using the same CalDAV credentials and URL, and it worked without a problem.

How can I solve it?

### Steps to Reproduce

1. Go to URL: https://app.cal.com/apps/caldav-calendar/setup
2. I entered the CalDAV URL and credentials and I got the error message: Could not add this caldav account

### Actual Results

- Error message appears: Could not add this caldav account

### Expected Results

It should accept the credentials and CalDAV URL entered, and integrate Zoho's CalDAV calendar into my CAL.com account.

### Technical details
- Browser: Microsoft Edge Versión 118.0.2088.46 (Compilación oficial) (64 bits)
- Windows 11 Home Edition

### Evidence

Attached screenshot with error.
![image](https://github.com/calcom/cal.com/assets/47869204/1e05e126-050e-4f0b-b60f-d0096c767761)

**Comment by tedspare** [comment]
maige label this

**Comment by PeerRich** [comment]
i dont think zoho calendar is supported by caldav. we are adding a native zoho calendar integration soon!

**Comment by sergiodevelop78** [comment]
> i dont think zoho calendar is supported by caldav. we are adding a native zoho calendar integration soon!

HI, Zoho CalDAV is working good on another tools and software like Thunderbird Calendar or on my Android Phone.
Besides,  Zoho calendar, offers the URL for CalDAV link

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/issues/12405
