### ISSUE TITLE
[CAL-2634] bug: team availability slider overflow

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#12015]
Content overflows behind header on team availability slider 

![CleanShot 2023-10-20 at 10 21 26](https://github.com/calcom/cal.com/assets/55134778/b0fd8cb0-4e91-4670-a616-6be847e4c185)

<sub>[CAL-2634](https://linear.app/calcom/issue/CAL-2634/bug-team-availability-slider-overflow)</sub>

**Comment by rayy40** [comment]
Hey @sean-brydon , Can you assign me this?

**Comment by vikaspatil0021** [comment]
@sean-brydon I am not able to reproduce the issue 
Did you check if this issue has been resolved before or not?

Here i have two members

![Screenshot 2023-10-20 163647](https://github.com/calcom/cal.com/assets/112180774/f2edc660-4417-419a-bf3f-3ee53f4a1b09)

**Comment by Siddharth-2382** [comment]
@vikaspatil0021 it happens when you have a lot of members and then you scroll down.

**Comment by vikaspatil0021** [comment]
@Siddharth-2382 Can you share a video of the same and describe the expected behaviour.

**Comment by Siddharth-2382** [comment]
just create a team and invite a lot of members, go to availability and switch to team availability. Scroll down to see the table header stick at the top and other content pass through the back of it.

**Comment by vikaspatil0021** [comment]
@Siddharth-2382  Did you invite me?
