### ISSUE TITLE
Fix the padding and position of tabs on the Team Availability page

### ISSUE THREAD

**Issue by itsberkaya** [calcom/cal.com#12025]
It looks like there's too much padding at top
<img width="1800" alt="Screenshot 2023-10-20 at 23 07 23" src="https://github.com/calcom/cal.com/assets/110773293/6ac131cd-3a6e-4cd4-864e-312aa0b6c44a">

And we changed the location of the tabs to make them easier for users to recognize and consistent with other pages. The new design is here.
https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=7869-78157&mode=dev

**Comment by rishuraj1** [comment]
Hi @itsberkaya , I really want to contribute. Kindly assign this issue to me. Thanks!

**Comment by Siddharth-2382** [comment]
Decreasing the padding breaks the table header, it was added recently. When there are a lot of team members and you scroll down, the table header will stick at a certain height from the top. Changing the sticky height of table header will break orgainsation members table. Hence more padding was added.

**Comment by Siddharth-2382** [comment]
@sean-brydon what if we add the `search` field as it is there in `Org members` table? It will help to remove the padding as the search field itself can be made sticky similar to `Org members` page. Also it will allow users to search for specific members by name when there are too many members on team.

**Comment by shantanusoni72** [comment]
I am working on it

**Comment by sean-brydon** [comment]
> @sean-brydon what if we add the `search` field as it is there in `Org members` table? It will help to remove the padding as the search field itself can be made sticky similar to `Org members` page. Also it will allow users to search for specific members by name when there are too many members on team.

Search and filters here would be amazing - That was something i always planned to add just never got round to it

**Comment by Siddharth-2382** [comment]
@sean-brydon should I do it and submit a PR for your review?
