### ISSUE TITLE
The sticky topbar of not upgrading the cal.com for teams is not getting full width . It gets some margin from right side .

### ISSUE THREAD

**Issue by vaishnavi1902** [calcom/cal.com#12026]
Bug

### Issue Summary
The sticky topbar of not upgrading the cal.com for teams is not getting full width . It gets some margin from right side .

### Steps to Reproduce
1. go to cal.com
2. team availability
3. new team
4. see the topbar before upgrading to teams of cal.com

### Actual Results

It is getting some margin from right side of the topbar even if 100% given in the code 

### Expected Results

It should get complete horizontal space

### Evidence

![image](https://github.com/calcom/cal.com/assets/80633315/d7f848d0-7f00-4b8d-9e72-77fab914870f)

**Comment by Shreyas0410** [comment]
I would like on this issue. Please assign it to me.

**Comment by saifulbdDev** [comment]
Please assign it to me.

**Comment by Siddharth-2382** [comment]
It's fine on my device. Tested on different browsers.

**Comment by vaishnavi1902** [comment]
> It's fine on my device. Tested on different browsers.

Okay
