### ISSUE TITLE
[CAL-2637] Instant Meeting

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12034]
# problem:

* sales teams want to do a call immediately if possible

# solution:

* add "Instant Meeting" as an option for Round Robin events
* if a person is available, show a link: "Join Meeting" immediately
* use webhook and zapier for notifications
* notify host
  * v0: send a slack message to a group "A lead is looking for a call"
    * have a dynamic link that expires so only one person can join
    * i.e.: [http://app.cal.com/instant-meeting/6YsEEOIom8HbXrzQOWdo](http://app.cal.com/instant-meeting/6YsEEOIom8HbXrzQOWdo)
    * later: add more notification options (SMS, Email, Phone Call)
  * require logged in user for the "host"
  * track who joins (need logged in [cal.com](http://cal.com) account)
  * trigger a full booking flow (as if someone booked a time in the future)
* add that event to their account (for analytics purposes)
* fastest to join gets the call
* requires team to be on enterprise (Upgrade button)

[https://github.com/calcom/cal.com/assets/8019099/c0baff7e-889f-4e75-90ba-6aa6a25f9845](https://github.com/calcom/cal.com/assets/8019099/c0baff7e-889f-4e75-90ba-6aa6a25f9845)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2637](https://linear.app/calcom/issue/CAL-2637/instant-meeting)</sub>

**Comment by PeerRich** [comment]
new animation:

https://github.com/calcom/cal.com/assets/8019099/7a1a5e03-e7fd-46ae-a501-fd256f534dd2

**Comment by PeerRich** [comment]
we could add all settings to a new tab:

![CleanShot 2023-10-25 at 11 00 30@2x](https://github.com/calcom/cal.com/assets/8019099/1d249104-ca85-4307-999d-0ba1a2450e70)

**Comment by PeerRich** [comment]
v.0.1 we'll be using zapier and webhooks

**Comment by ciaranha** [comment]
[https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=13060%3A429570&mode=design&t=HsiCPp3M7aHccCof-1](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=13060%3A429570&mode=design&t=HsiCPp3M7aHccCof-1)
