### ISSUE TITLE
fix : sanitize html tags from input fields in booking questions of advanced tab in edit event type

### ISSUE THREAD

**Issue by itskish0re** [calcom/cal.com#12030]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The booking questions in advanced tab from edit event type has no html sanitization in labels and placeholders of input fields except for "checkbox input".

### Steps to Reproduce

1. In event type page click on edit for any existing event type
2. Go to advanced tab
3. In Booking questions section click on add a question or edit existing question
4. Enter any value containing html tags in the label input
5. Save and preview

### Actual Results

- So, when the form is loaded the labels have the html tags in them.

### Expected Results

- The expected result should be the labels without html tags in them. This can be done by sanitizing the value of the label input.

### Technical details

- Browser Chrome Windows
- Date: Oct 22, 2023 around 2:40pm IST

### Evidence
![Screenshot1](https://github.com/calcom/cal.com/assets/59221338/1b5b0796-d873-4d45-b5ee-e70794e44886)
![Screenshot2](https://github.com/calcom/cal.com/assets/59221338/ec5c1972-ef6f-4fa5-9fb2-7eed50d0ac70)

### Note
This bug is seen everywhere in the form where string input is given as a question except the <b><i>Checkbox</i></b> input.

**Comment by kushalv238** [comment]
@itskish0re  can you specify the page

**Comment by itskish0re** [comment]
> @itskish0re can you specify the page


https://github.com/calcom/cal.com/assets/59221338/0b7130fe-a2a5-42c8-8168-c46ceb2aff3b

**Comment by PeerRich** [comment]
why would we want to have HTML in there in the first place? makes no sense. It's correct to sanitize here
