### ISSUE TITLE
Time slots gone wrong on self-hosted cal

### ISSUE THREAD

**Issue by sreekaransrinath** [calcom/cal.com#1203]
### Issue Summary

Timings gone awry on self-hosted cal. 
Availability page timings start at 18:30 instead of 00:00.
![image](https://user-images.githubusercontent.com/50989977/143292352-208a1ca3-d9a8-4360-a8fb-3ead13b5c825.png)

My scheduling slots are offset as well (when I set my availability to be 12:00 PM to 10:00 PM on the event page, my availability shows up from 6:00 AM to 4:00 PM)
![image](https://user-images.githubusercontent.com/50989977/143292199-dcb27b59-27d5-45ca-ab94-da10fddba63a.png)

### Steps to Reproduce

1. Self-hosted cal on Vercel (app) and Railway (db)

### Technical details

- Browser version: Chrome 96. UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
- Node.js version: v16.13.0

**Comment by sreekaransrinath** [comment]
Just checked, app.cal.com has the same issue.

![image](https://user-images.githubusercontent.com/50989977/143306936-41b5c356-db94-439d-8fab-f33b8c68caf3.png)
For reference, my timezone is set as IST (GMT +5:30) across booking and scheduling

**Comment by sreekaransrinath** [comment]
Rolled back to release 1.1 and this issue doesn't seem to exist there

**Comment by sreekaransrinath** [comment]
Release 1.1 completely breaks. Separate issue:

[GET] /event-types/4
02:12:49:46
pe"."requiresConfirmation", "public"."EventType"."disableGuests", "public"."EventType"."minimumBookingNotice", "public"."EventType"."schedulingType", "public"."EventType"."userId", "public"."EventType"."price", "public"."EventType"."currency", "public"."EventType"."teamId" FROM "public"."EventType" WHERE ((("public"."EventType"."id") IN (SELECT "t0"."A" FROM "public"."_user_eventtype" AS "t0" INNER JOIN "public"."users" AS "j0" ON ("j0"."id") = ("t0"."B") WHERE ("j0"."id" = $1 AND "t0"."A" IS NOT NULL)) OR ("public"."EventType"."id") IN (SELECT "t0"."id" FROM "public"."EventType" AS "t0" INNER JOIN "public"."Team" AS "j0" ON ("j0"."id") = ("t0"."teamId") WHERE (("j0"."id") IN (SELECT "t1"."id" FROM "public"."Team" AS "t1" INNER JOIN "public"."Membership" AS "j1" ON ("j1"."teamId") = ("t1"."id") WHERE ("j1"."userId" = $2 AND "t1"."id" IS NOT NULL)) AND "t0"."id" IS NOT NULL)) OR "public"."EventType"."userId" = $3) AND "public"."EventType"."id" = $4) LIMIT $5 OFFSET $6
prisma:query SELECT "public"."Availability"."id", "public"."Availability"."label", "public"."Availability"."userId", "public"."Availability"."eventTypeId", "public"."Availability"."days", "public"."Availability"."startTime", "public"."Availability"."endTime", "public"."Availability"."date" FROM "public"."Availability" WHERE "public"."Availability"."eventTypeId" IN ($1) OFFSET $2
prisma:query SELECT "public"."EventTypeCustomInput"."id", "public"."EventTypeCustomInput"."eventTypeId", "public"."EventTypeCustomInput"."label", "public"."EventTypeCustomInput"."type", "public"."EventTypeCustomInput"."required", "public"."EventTypeCustomInput"."placeholder" FROM "public"."EventTypeCustomInput" WHERE "public"."EventTypeCustomInput"."eventTypeId" IN ($1) OFFSET $2
prisma:query SELECT "public"."_user_eventtype"."A", "public"."_user_eventtype"."B" FROM "public"."_user_eventtype" WHERE "public"."_user_eventtype"."A" IN ($1)
prisma:query SELECT "public"."users"."id", "public"."users"."name", "public"."users"."username", "public"."users"."avatar", "public"."users"."email" FROM "public"."users" WHERE "public"."users"."id" IN ($1) OFFSET $2
20:42:54.936 timeZoneName DEBUG [error] server side logged this: Error: Attempted to serialize scalar 'unlimited' with incompatible type 'String' for field periodType. 
20:42:54.943 timeZoneName INFO [error] return props,  
{
statusCode: 500,
hasGetInitialPropsRun: true
}
2021-11-24T20:42:54.962Z	f379a224-ae60-47ee-883d-e7520099f6b3	WARN	react-i18next:: You will need to pass in an i18next instance by using initReactI18next
2021-11-24T20:42:54.990Z	f379a224-ae60-47ee-883d-e7520099f6b3	ERROR	PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Attempted to serialize scalar 'unlimited' with incompatible type 'String' for field periodType.
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getServerSideProps (/var/task/.next/server/pages/event-types/[type].js:2591:26)
    at async Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:479:20)
    at async doRender (/var/task/node_modules/next/dist/server/next-server.js:1389:38)
    at async /var/task/node_modules/next/dist/server/next-server.js:1484:28
    at async /var/task/node_modules/next/dist/server/response-cache.js:63:36 {
  clientVersion: '2.30.3',
  page: '/event-types/[type]'
}
RequestId: f379a224-ae60-47ee-883d-e7520099f6b3 Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by emrysal** [comment]
The select dropdown starting at 18:30 is purely a visual bug and does not affect the working;

I suspect some prisma commands need running: `prisma migrate deploy` & `prisma generate` as "DEBUG [error] server side logged this: Error: Attempted to serialize scalar 'unlimited' with incompatible type 'String' for field periodType." indicates an outdated client.

**Comment by sreekaransrinath** [comment]
Well, something was going wrong, otherwise 1 PM should not have been book-able. I triple-checked to make sure that the timezones were lining up, and even tried booking events. Sure enough, the timeslots I'd made available for booking were offset.

**Comment by sreekaransrinath** [comment]
This is probably a stupid question, but I'm hosting on vercel and railway. How and where do I run prisma migrate deploy and prisma generate?

**Comment by sreekaransrinath** [comment]
It has now completely died.
![image](https://user-images.githubusercontent.com/50989977/144261439-75ac8317-9548-45fd-93dd-e00bf1d49bc3.png)

**Comment by sreekaransrinath** [comment]
Has this not been fixed yet? @emrysal

**Comment by PeerRich** [comment]
hey, can you try the latest version?
