### ISSUE TITLE
[CAL-2636] Not able to create a team with in the org with same name as the org

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12033]
Consider an org with slug `calcom`. I can't create a team with slug `calcom` within it. Technically there is no limitation and it should be allowed

<sub>[CAL-2636](https://linear.app/calcom/issue/CAL-2636/not-able-to-create-a-team-with-in-the-org-with-same-name-as-the-org)</sub>

**Comment by PeerRich** [comment]
i agree, but is this useful? why would someone make an org called acme.cal.com/acme ?
