### ISSUE TITLE
no use of pointer cursor on calcom logo

### ISSUE THREAD

**Issue by Amitverma0509** [calcom/cal.com#12046]
### Is your proposal related to a problem?

(Write your answer here.)

remove the pointer cursor from calcom logo

(Describe your proposed solut

https://github.com/calcom/cal.com/assets/148716794/33fcc564-e504-4657-aabe-6c82a283010c

ion here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by Siddharth-2382** [comment]
It's used to bring users back to home page when they are on some other pages like blog, docs, etc.
