### ISSUE TITLE
[CAL-2640] Attendees not receiving reschedule/cancel updates

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#12040]
### Issue Summary

> We've encountered some issues with reschedule/cancel booking flows, as attendees don't get reschedule/cancel updates.
when the host is using microsoft calendar, all attendees associated with microsoft gets the updates of the booking-schedule and attendees using google don't get any updates.
Conversely,, both google-attendees and microsoft-attendees initially receive the schedule event update, However, for all reschedule/cancel updates only attendees with google calendar receive these updates.
This issue seems to be consistent and could be reproduced

### Steps to Reproduce

1. when the host is using microsoft calendar, all attendees associated with microsoft gets the updates of the booking-schedule and attendees using google don't get any updates
2. if the host is using google calendar, both google-attendees and microsoft-attendees initially receive the schedule event update, However, for all reschedule/cancel updates only attendees with google calendar receive these updates.

### Actual Results

- when the host is using microsoft calendar, all attendees associated with microsoft gets the updates of the booking-schedule and attendees using google don't get any updates
- if the host is using google calendar, for all reschedule/cancel updates only attendees with google calendar receive these updates

### Expected Results

- They should all get an update

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>[CAL-2640](https://linear.app/calcom/issue/CAL-2640/attendees-not-receiving-reschedulecancel-updates)</sub>

**Comment by shirazdole** [comment]
This is also affecting hosts, I've had several attendees cancel and reschedule on me over the past few weeks on individual and collective links and I haven't received any emails notifying me of the change. I just notice the change on the calendar.
