### ISSUE TITLE
Browser Page Crashing When Trying to Update Availability

### ISSUE THREAD

**Issue by Kfelts** [calcom/cal.com#12059]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to update availability or override the daily availability, the browser freezes and then crashes

### Steps to Reproduce

1. Clicked on availability
2. Clicked on working hours [or whatever default availability is]
3. Clicked on "add an override" and wait...nothing happens or the screen goes black, then after a minute Chrome has a popup about an unresponsive page asking to either wait or kill the page. I am also unable to open the browser console to inspect the issue. Once on the availability page, most functions seem to be disabled or frozen.

### Actual Results

- When going into my availability and trying to add an override for the day, the entire page crashes and does not allow me to alter my availability at all.

### Expected Results

- When going into my availability and adding an override for the day, usually I can select the calendar date and updating the time slots or block off the entire day. Then I can save it and it reflects on the booking page.

### Technical details

- Chrome v 118.0.5993.70 (Official Build) (arm64) 
- Hosted version of Cal.com

### Evidence
<img width="509" alt="Screenshot 2023-10-24 at 10 25 16 AM" src="https://github.com/calcom/cal.com/assets/51497445/e1cd21b2-c3e2-4ee5-bc01-5d23994edf3c">

https://github.com/calcom/cal.com/assets/51497445/dd912eaa-ab8d-43b8-a1e5-9b4c80b8d43d

**Comment by Udit-takkar** [comment]
@Kfelts i am not able to reproduce this bug. could you send me your cal username?

**Comment by kikemarto** [comment]
I had to go back to the latest release version manually and it was solved

**Comment by Kfelts** [comment]
As of right now, it seems to be resolved.
