### ISSUE TITLE
Web UI hangs when trying to get the embedded HTML content for event

### ISSUE THREAD

**Issue by moilejter** [calcom/cal.com#12052]
Found a bug? Please fill out the sections below. 👍

Web UI hangs when trying to get the embedded HTML content for event

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Went to Events
2. Scroll down to last event in list
3. Click on "..." to view actions
4. Click on "Embed"
5. Popup dialog appears with content, including HTML to copy to target website - but whole browser window hangs.
 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

At that point, I should be able to click on "Copy" button to copy the HTML content to the target window, then dismiss the dialog.

### Actual Results

Browser displays popup with Embed content for HTML page, then hangs.

### Expected Results

I  should be able to click on "Copy" button to copy the HTML content to the target window, then dismiss the dialog.

### Technical details

- Happens with either Safari or Chrome (newest one for each) on MacBook Pro M2.

### Evidence

![Screenshot 2023-10-24 at 12 48 51 AM](https://github.com/calcom/cal.com/assets/10899980/9ecc119d-13fd-4947-a41f-4f20532f71e6)

![Screenshot 2023-10-24 at 12 46 39 AM](https://github.com/calcom/cal.com/assets/10899980/159476fd-4558-4c34-b5f3-0090fd93f1b1)

![Screenshot 2023-10-24 at 12 46 22 AM](https://github.com/calcom/cal.com/assets/10899980/f6ec5f76-6997-4648-bd3f-1e44c9ba059e)

**Comment by Siddharth-2382** [comment]
Can't reproduce. Tried on different browsers and different accounts with multiple events in it. Tried the steps you gave and also checked for other events as well.

**Comment by Vijaykv5** [comment]
I would love to work on this issue

**Comment by PeerRich** [comment]
it seems to be a temporarily outage
