### ISSUE TITLE
[CAL-2642] Creating an event type doesn't update the list.

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#12054]
Full refresh is needed in order for the newly created event type to show up. (trpc doesn't invalidate)

<sub>[CAL-2642](https://linear.app/calcom/issue/CAL-2642/creating-an-event-type-doesnt-update-the-list)</sub>

**Comment by Dhoni77** [comment]
Hi @emrysal when we create an event type it is showing up in the event types page without refresh in local.
Can you provide the steps to reproduce this issue ?
