### ISSUE TITLE
[CAL-2641] add .tz(userTimezone) in bookings/[status].tsx

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12053]
@CarinaWolli nice catch.

we would also have add .tz(userTimezone) at few places in bookings/[status].tsx also 
https://github.com/calcom/cal.com/blob/19eced00f5568446cf2401e03f8b8cb8f554d1bd/apps/web/pages/bookings/%5Bstatus%5D.tsx#L135. 

As you can see in the screenshot the second 20th october meeting doesn't show up in bookingsToday 

<img width="1103" alt="Screenshot 2023-10-20 at 4 03 53 PM" src="https://github.com/calcom/cal.com/assets/53316345/c2d075ef-16db-425d-a653-595b4baf0ba9">

_Originally posted by @Udit-takkar in https://github.com/calcom/cal.com/pull/12007#pullrequestreview-1689749496_
            

<sub>[CAL-2641](https://linear.app/calcom/issue/CAL-2641/add-tzusertimezone-in-bookings[status]tsx)</sub>

**Comment by MeenuyD** [comment]
Hello @Udit-takkar I would like to work on this issue can you please tell where should i add.

**Comment by MeenuyD** [comment]
Hello @Udit-takkar I would like to work on this issue can you please tell how should i add user timezone in a book today
