### ISSUE TITLE
In booking tab "Canceled" spelling is incorrect

### ISSUE THREAD

**Issue by mrinmay7875** [calcom/cal.com#12064]
### Issue Summary

In booking tab the Canceled spelling is incorrect.

### Steps to Reproduce

1. Go to the booking tab and see the `Canceled` spelling is incorrect

### Actual Results
Here is a screenshot:
<img width="1131" alt="image" src="https://github.com/calcom/cal.com/assets/33797909/e4e149e5-2e81-4712-a048-d8fef4ccc417">

- What's happening right now that is different from what is expected

### Expected Results
The spelling should be `Cancelled`.

**Comment by harshit-ostwal** [comment]
No, Actually both the Spellings are correct only either this Canceled or Cancelled

**Comment by mrinmay7875** [comment]
Sorry my bad, Yes, both the spelling is correct. 
`Cancelled` with two L’s is used in British English, while `canceled` with one L is preferred in American English. Closing the issue.
