### ISSUE TITLE
Choose which google calendar to write to

### ISSUE THREAD

**Issue by pedrorrivero** [calcom/cal.com#1208]
### Is your proposal related to a problem?
Currently events are written to my main calendar in Google calendar. 

### Describe the solution you'd like
I would like to be able to choose the calendar where events are created. It would be best if this could be chosen for each event type, with a default option under general settings.

### Additional context
Calendly allows to select one calendar to write all its events to. This would improve upon that.

**Comment by ConnorGargano** [comment]
Hi @pedrorrivero,
I can confirm this is on our roadmap to complete and should be available soon.

**Comment by PeerRich** [comment]
You should be able to do it for a couple of months now
