### ISSUE TITLE
[CAL-2646] Availability of last day of month missing

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#12082]
### Issue Summary

In some UTC+ timezones (for example, Sydney Australia) the last day of the month doesn't show any available slots between October and March. 

It's about the timezone the system is running, not the timezone set on the booking page. 

Probably related to the issue that got fixed here: https://github.com/calcom/cal.com/pull/11820

<sub>[CAL-2646](https://linear.app/calcom/issue/CAL-2646/availability-of-last-day-of-month-missing)</sub>

**Comment by mateoradman** [comment]
Hi, I am still facing this issue in a self-hosted instance of Cal after last night's change from CEST to CET. Monday 30th October shows unavailable and it shows that I am available today on 29th October.

**Comment by mateoradman** [comment]
Update at 22:42 CET, I've noticed that my calendar shows available slots as expected on Monday 30th October again. It could be as a result of me changing the host time zone from UTC to CET or simply getting close to the start of the Monday. I hope this feedback helps when looking further into this problem. Cheers
