### ISSUE TITLE
[CAL-2648] if profile only has one public event-type, redirect to it

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12089]
1. https://cal.com/peer only has one visible event-type (others are secret/hidden)
2. visiting https://cal.com/peer should redirect to https://cal.com/peer/meet immediately
3. however, if you click the avatar, it should go back to profile without redirecting (i.e. as a URL parameter: ?redirect=false)
![CleanShot 2023-10-25 at 20 36 10@2x](https://github.com/calcom/cal.com/assets/8019099/2a093b0d-9677-4b18-ae7d-6eec78aeb8a8)

# why:
- having only one event-type means a user can only take one action anyway
- speeds up, so people can send cal.com/peer vs cal.com/peer/meet

<sub>[CAL-2648](https://linear.app/calcom/issue/CAL-2648/if-profile-only-has-one-public-event-type-redirect-to-it)</sub>

**Comment by Dhoni77** [comment]
Hi @PeerRich If the user wishes to edit the event how would the user be able to edit the single event.
Since the page would be redirected to `https://cal.com/peer/meet` ?

**Comment by PeerRich** [comment]
what do you mean edit? you edit things in the logged in dashboard no?

**Comment by Dhoni77** [comment]
Ohh ok got it @PeerRich thanks👍

**Comment by gitstart-calcom** [comment]
Hi @PeerRich We already provided a solution for this issue, we will push a PR now
