### ISSUE TITLE
Missing booking ID in webhook payloads

### ISSUE THREAD

**Issue by BorisKamp** [calcom/cal.com#12093]
On the `booking.canceled` webhook, I do not get the `id` of the booking back, I do however get the `uid` back but I cannot use that to fetch the booking, why is that?

It seems all the booking webhooks are missing the booking `id` itself, they only have the `uid`....
My use case is that I want to save the booking ID (and UID) in a third party system, this way, I can cancel the booking from the third party system because I have the ID of the booking at hand. Now I don't see a way to do this.

**Comment by alishaz-polymath** [comment]
Pretty sure this was fixed in the PR #11906 

Tested locally and could confirm that ID is infact sent out with the webhook payload on `booking.canceled` trigger.

The attribute you're looking for is  `bookingId`
Closing this, but please feel free to re-open if this is not the case

**Comment by BorisKamp** [comment]
> Pretty sure this was fixed in the PR #11906
> 
> Tested locally and could confirm that ID is infact sent out with the webhook payload on `booking.canceled` trigger.
> 
> The attribute you're looking for is `bookingId` Closing this, but please feel free to re-open if this is not the case

It is fixed indeed, thanks! I figured this out a couple of weeks ago and in the meantime it is fixed, great!
