### ISSUE TITLE
Allow to cancel and delete past bookings

### ISSUE THREAD

**Issue by pedrorrivero** [calcom/cal.com#1209]
### Describe the solution you'd like
Bookings should include an option to cancel them that could be used both by the host and the person who scheduled the event.
Additionally, a delete booking option should be added to erase them from history. This is useful if someone makes a mistake, or you are just testing a newly created event type.
This should all be reflected on calendar integrations, and the parties involved in the booking should be notified automatically.

### Describe alternatives you've considered
We should at least be allowed to delete bookings.

**Comment by ConnorGargano** [comment]
Hi @pedrorrivero,
I will get this raised with our engineering team now for you.
