### ISSUE TITLE
[CAL-2649] Fix test: Seated booking cancellation test

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12091]
[https://github.com/calcom/cal.com/blob/96f6b8897b6293a622eb1120f6082ba6ba5a466a/apps/web/playwright/booking-seats.e2e.ts#L402](https://github.com/calcom/cal.com/blob/96f6b8897b6293a622eb1120f6082ba6ba5a466a/apps/web/playwright/booking-seats.e2e.ts#L402)

This test isn't written correctly, AFAIU. It creates a seated booking [by adding some offset from current time](https://github.com/calcom/cal.com/blob/96f6b8897b6293a622eb1120f6082ba6ba5a466a/apps/web/playwright/lib/testUtils.ts#L271), so that could actually be beyond 9-5PM availability and thus testing that after cancelling that seated event, all seats are available will be always true when there was never a booking within 9-5Pm slot.

We should create the booking within 9-5 slot to correctly test.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2649](https://linear.app/calcom/issue/CAL-2649/fix-test-seated-booking-cancellation-test)</sub>

**Comment by joeauyeung** [comment]
The unit tests should replace the E2E test here
