### ISSUE TITLE
Console enterprise tier link throws 404

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#12104]
### Issue Summary

Clicking "Scheduling a time" for the Enterprise tier in [https://console.cal.com](https://console.cal.com) leads to a 404 redirecting to [https://i.cal.com/team/cal/enterprise](https://i.cal.com/team/cal/enterprise).

Tagging @hariombalhara, can't assign.

### Expected Results

See a way to book the team for an enterprise license.

**Comment by hariombalhara** [comment]
Thanks @leog, getting it checked internally

**Comment by hariombalhara** [comment]
This is a configuring issue. Informed @shirazdole. Closing it.
