### ISSUE TITLE
[CAL-2655] Avatars not showing correctly

### ISSUE THREAD

**Issue by Siddharth-2382** [calcom/cal.com#12102]
### Issue Summary

The profile avatar and organisation avatars are not showing correctly on the left sidebar even after multiple attempts of saving it. Once you upload and save your avatar the left sidebar just has some broken image placeholder rather than the recently uploaded image. I don't have any plan currently active and I don't think not having a plan should be doing these.

### Steps to Reproduce

1. Go to settings
2. Go to profile(your account or organisation)
3. Upload a new image for the avatar and save it

### Actual Results

- The image is uploaded and saved successfully but the left sidebar shows a broken image icon.

### Expected Results

- Should be showing the latest uploaded image as the avatar.

### Technical details

- Tested on different accounts
- Tested on safari and brave browser (latest versions)
- Happens on live version of cal.com 

### Evidence

https://github.com/calcom/cal.com/assets/94699055/a0fa8228-e778-4a54-b261-286a1cbb09b0

<sub>[CAL-2655](https://linear.app/calcom/issue/CAL-2655/avatars-not-showing-correctly)</sub>

**Comment by poorna-prakash-sr** [comment]
Hey I can work on this one!
