### ISSUE TITLE
Display long durations in hours on the booking page

### ISSUE THREAD

**Issue by nicwortel** [calcom/cal.com#12107]
### Is your proposal related to a problem?

When using Cal.com to schedule longer events (such as workshops, trainings, etc. which take a half or full working day), displaying durations on the booking page in minutes (such as 240 minutes or 480 minutes) is confusing.

### Describe the solution you'd like

On the booking page, durations longer than a certain threshold should be rendered as `X hours` or `X hours Y mins` instead of in minutes.

My suggestion would be to do this for durations of 60 minutes and more, meaning that 60 minutes would be displayed as `1 hour` and 90 minutes would be displayed as `1 hour 30 mins`, but that is open for discussion.

This applies to event types with a fixed duration as well as event types where the booker can choose from multiple duration options.

Current | Proposed solution
---|---
![afbeelding](https://github.com/calcom/cal.com/assets/1055691/76294541-676e-4d3c-adcd-8177cd07f471) | ![afbeelding](https://github.com/calcom/cal.com/assets/1055691/01b69601-953a-4016-8837-0b29c7272148)

### Describe alternatives you've considered

The scope of this issue is intentionally limited to the booking page. I initially also considered the event type management page, but that would introduce a lot of complexity in order to handle different input modes, standard durations vs events where the booker can choose from different durations, etc.
A solution for the event type management page could be proposed in a separate issue, but for me personally that would have less priority than this one. As the owner of the event I just have to convert hours to minutes once when I setup the event, as compared to every booker having to convert the number of minutes to hours.

Instead of the proposed threshold of 60 minutes a higher threshold could be considered. For example by setting it to 120 minutes, 120 minutes would be displayed as `2 hours` but 90 minutes would still be `90 mins`, which would avoid the complexity of singular/plural translations (needing different translations for `1 hour` and `2 hours`).

Alternatively, the singular/plural issue could simply be ignored, always showing plural (such as `1 hours` or `1 hours 30 mins`), but that doesn't feel like a good solution. For minutes I think it is less of an issue, because I don't think having a duration of X hours and 1 minute will be a very common use case.

I have also considered limiting this to very specific durations (for example a hard-coded mapping from 240 and 480 minutes to `4 hours` and `8 hours`), but I think a more generic solution would be preferable and will support more use cases.

### Additional context

#10663 introduced 240 and 480 minutes as options for multiple duration event types, resolving #10181.
In https://github.com/calcom/cal.com/issues/10181#issuecomment-1671588333 I suggested displaying longer durations in hours instead of minutes.

**Comment by The5cheduler** [comment]
/contribute 
Can I work on this issue?

**Comment by rishuraj1** [comment]
hi, I would really like to contribute and solve this, can I get assigned to this issue please. Thanks

**Comment by The5cheduler** [comment]
Hey @rishuraj1 , I am finished with this issue!
It is under the testing!!
