### ISSUE TITLE
[CAL-2653] UI/UX improvements in settings pages

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#12105]
1) Members only view of organization

![image](https://github.com/calcom/cal.com/assets/53316345/f3eb28bc-20b3-499a-a3f3-97e13980bb8e)

2) password screen when managed by google

<img width="1512" alt="Screenshot 2023-10-26 at 6 50 48 PM" src="https://github.com/calcom/cal.com/assets/53316345/84cb3d34-26b1-4533-9bae-c8671acde8aa">

<sub>[CAL-2653](https://linear.app/calcom/issue/CAL-2653/uiux-improvements-of-settings-pages)</sub>

**Comment by opcxder** [comment]
could you provide a more detailed explanation of issue
