### ISSUE TITLE
[CAL-2654] Broken Icons in org invitation email 

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12112]
![image](https://github.com/calcom/cal.com/assets/1780212/07c4679d-1746-4504-8d42-32e2e18c211d)

<sub>[CAL-2654](https://linear.app/calcom/issue/CAL-2654/broken-icons-in-org-invitation-email)</sub>

**Comment by Shaunak-Bhandare** [comment]
What do we have to do to fix and recreate this issue?
