### ISSUE TITLE
No email is going to attendees after booking the event  

### ISSUE THREAD

**Issue by MithNo1** [calcom/cal.com#12129]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
No email is going to attendees after booking the event not even in spam folder of their Gmail so I have to resend the mail manually myself.   

### Steps to Reproduce

After booking no emails goes to them and this needs to be checked and fixed. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
It's a big bug and I'm using an skiff email as a organizer in cal so I don't know if that's affecting it? To my attendees who are using mostly Gmail but non-google calendars.
### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- emails should to go the attendees even in spam folder or somewhere it should just go automatically. 

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by Siddharth-2382** [comment]
1. Is it happening on live version of cal or local host?
2. Are you sure you haven't disabled them from event-type `Advanced` tab?

If possible can you share the screen recordings of it?

**Comment by MithNo1** [comment]
> 1. Is it happening on live version of cal or local host?
> 2. Are you sure you haven't disabled them from event-type `Advanced` tab?
> 
> If possible can you share the screen recordings of it?

Everything is set on default no settings changed and I'm using normal version of cal. If that's what you mean by live version.

**Comment by PeerRich** [comment]
this looks like an isolated issue for your account, is your email on a blacklist maybe? Can you reach out to support@cal.com so we can investigate? I am receiving emails, cannot reproduce this.

Can you also make a new, free cal.com account with a different email?
