### ISSUE TITLE
Availibility shown is not correct when minimum notice date lands on Nov 5 (DST change day)

### ISSUE THREAD

**Issue by WispOfTheWinds** [calcom/cal.com#12137]
### Issue Summary

Booking availability shown is "offset" from actual availability in month of November when minimum notice lands on Nov 5 (DST change day).

### Steps to Reproduce

1. Set minimum notice for event to 7 days (ending on Nov 5)
2. Go to public page
3. Availability is incorrect

### Actual Results

Availability shown is offset from actual availability

### Expected Results

Availability should match availability set for event (in this case default).

### Technical details

 - Default, availability, and booking time zones are all set to America/New York -4:00
 - Running live Cal on cal.com.

### Evidence

7 day notice (Nov 5):
<img width="588" alt="image" src="https://github.com/calcom/cal.com/assets/32007014/8711eb17-f9b9-426e-9163-d71e1894ba8d">

6 day notice (Nov 4):
<img width="581" alt="image" src="https://github.com/calcom/cal.com/assets/32007014/e5f0b937-9042-4106-ae54-ad0577878776">

8 day notice (Nov 6):
<img width="587" alt="image" src="https://github.com/calcom/cal.com/assets/32007014/0c08aca9-74d0-4822-b198-8afa3e822688">

Expected Availability:
<img width="358" alt="image" src="https://github.com/calcom/cal.com/assets/32007014/eb865650-5893-4e9a-b822-cb23862601d5">

**Comment by emrysal** [comment]
@WispOfTheWinds Thank you very much for reporting this; as it gave us a ~7 day heads-up for investigating what turned out to be a huge failure incoming on November 5th for the DST change in negative timezones; I expect the fix to auto-merge and will get tagged in the next tag (either today or tomorrow)

**Comment by WispOfTheWinds** [comment]
Thanks for addressing this so quickly! DST bugs are nasty -- glad it worked out.
