### ISSUE TITLE
[CAL-2660] A team in an org with slug starting with "team" get's rewritten to non-org route.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12146]
1. Create a team with slug 'team-to-test' in org calcom.cal.local:3000
2. Open the page calcom.cal.local:3000/team-to-test -> it gives 404
3. Rename the team slug to "to-test-team" -> It would work.

It happens because in step-2, the route used isn't org/\[orgSlug\] but some non-org route.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2660](https://linear.app/calcom/issue/CAL-2660/a-team-in-an-org-with-slug-starting-with-team-gets-rewritten-to-non)</sub>

**Comment by MehulZR** [comment]
Not able to reproduce.

https://github.com/calcom/cal.com/assets/86384652/415c6255-2037-4db9-8388-2e915ef74c83

**Comment by sean-brydon** [comment]
![CleanShot 2023-12-01 at 09.31.02.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2cbd989b-fdaa-4cec-8c36-934f5ff2c2d5/c3008d20-4ff4-436b-b7ba-9f0befc34a0d)

Hey @hariombalhara - are you still able to replicate this? I was going to try and fix this but it appears working fine on my end

**Comment by keithwillcode** [comment]
Rejecting because unable to repro
