### ISSUE TITLE
Cal.com site is broken

### ISSUE THREAD

**Issue by crisprcoders** [calcom/cal.com#12140]
Found a bug? Please fill out the sections below. 👍
- While visiting the main site (cal.com) site is broken with **Application error: a client-side exception has occurred (see the browser console for more information).** message
### Steps to Reproduce

1. Visit cal.com site

### Actual Results

- Page is broken with  **Application error: a client-side exception has occurred (see the browser console for more information).** message

### Expected Results

- See cal.com site in action.

### Technical details

- Browser version:Google Chrome Version 117.0.5938.88 (Official Build) (arm64)

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<img width="1303" alt="Screenshot 2023-10-30 at 07 52 20" src="https://github.com/calcom/cal.com/assets/60551574/29a1f300-c2f1-449e-b592-f93f34c6b5e7">

**Comment by PeerRich** [comment]
this is a niche bug that i cant replicate. is this still ongoing? does it work in different browsers?

**Comment by crisprcoders** [comment]
@PeerRich this bug is gone now. I am not able to reproduce it.
