### ISSUE TITLE
Booking time slots doubling up and not rendering in correct order

### ISSUE THREAD

**Issue by Shpadoinkle** [calcom/cal.com#12142]
### Issue Summary
- Available times are not combining and ordering correctly on Booking page for an event.  Occurs when using multiple members with differing availabilities. 
- Times seems to be listed in order of earliest to latest for one member, then starts again at the start of the next member availability. 
- Would expect them to be in correct order, and not duplicating same time slots.   combined if overlapping.

* occurs when
  * when using multiple members that have staggered/broken availabilities on a single day.  (more prevalent after three or more members)
  * using one user with multiple short availabilities on the one day, and another user with one large availability. 

### Steps to Reproduce
- have an event-type (i was using a round robin type). 
- event time is 10 mins
- no common Schedule was chosen. 
- Used different availabilities for the event members on their personal schedules. 
- Example below

| Member One          | Member Two            | Member Two.      |
|-----------------|------------------|------------------|
|![image](https://github.com/calcom/cal.com/assets/11312962/7101f275-fd41-41e4-9553-351ba1efcf17)|![image](https://github.com/calcom/cal.com/assets/11312962/2d17d592-32d1-4072-ac12-a4dd465c142c)|![image](https://github.com/calcom/cal.com/assets/11312962/ed1459b6-6081-4335-bdab-ffaef340ff2c)|

### Actual Results
When trying to book an appointment for that event on a tuesday. These times were available.
Times around the 10am slots, it repeats the slots during 10 till 11 times.
![image](https://github.com/calcom/cal.com/assets/11312962/fad17d1d-4ed6-4ec0-95a1-7ab5b2d0ed2e)

### Steps to Reproduce 2
- same setup as above, but change availability to have one member with full day, no breaks.   Another with staggered availabilities on that day.
- Example below

| Member One          | Member Two            |
|-----------------|------------------|
|![image](https://github.com/calcom/cal.com/assets/11312962/bb9862ac-ebfb-4650-9776-e058a1e3fd96)|![image](https://github.com/calcom/cal.com/assets/11312962/a97f56ca-cd40-48c4-a2fc-53398934ffd0)|

### Actual Results 2 
When trying to book an appointment for that event on a tuesday. These times were available.
Timeslots available start again once you scroll down past the 4-5pm times.
![image](https://github.com/calcom/cal.com/assets/11312962/e84f8d84-79b2-461a-9bfc-e8de64dfe081)

### Expected Results
- I would expect the earliest time slots to be combined somehow,  not start again after one members availability for the day ends. 
- ie-  so availability slots of the same time do not appear more than once?

### Important Note

- This issue is **not reproducible** on certain timezones (tested and couldn't reproduce on Asia/Dubai as host timezone)
- This issue is **reproducible** on certain timezones (tested and reproduced on Australia/Brisbane as host timezone)

### Technical details
- using chrome. 
- latest main branch of calcom/cal.com

### Evidence
- as written above in reproduce/actual results steps.
- Sayed managed to reproduce using Australia/Brisbane timezone

**Comment by lalitkumawat1m** [comment]
Can I work on this issue

**Comment by alishaz-polymath** [comment]
@lalitkumawat1m Yeah feel free to have a go, you don't really need to ask to work on it 😅

**Comment by shvuuuu** [comment]
I just faced it myself and found this here.

**Comment by supalarry** [comment]
@Shpadoinkle thank you for such a detailed issue description, appreciate it!

Just so that everyone is on the same page - when you mention "timezone" you refer only to a timezone of an availability under the "Availability" tab? Not "My settings" -> "General" -> "Timezone" and not timezone in the booking page (where you see the timetable), right?

That's what I have gathered but want to confirm it so it's easier for others to reproduce and investigate. Thank you!

**Comment by Shpadoinkle** [comment]
@supalarry  the timezone pickers i am referring to is the timezone option while setting the availability on the schedule, and the timezone option when you are in the calendar/booking page.  Both times I was using Australia/Brisbane as that is my local. 

I'm not sure what my users settings->general->timezone was set to.  I'll double check that in the morning.  I assume it was probably the same.

**Comment by shvuuuu** [comment]
> > I just faced it myself and found this here.
> 
> Thanks for reporting! Which timezone do you have?

India (GMT+5:30)

**Comment by supalarry** [comment]
@Shpadoinkle @shvuuuu we just shipped a fix to this issue. If you could check if all works on your end as expected that would be nice, otherwise let me know if you run into any problems : )

**Comment by shvuuuu** [comment]
@supalarry Yeah, the issue seems to be pretty well fixed for me.
