### ISSUE TITLE
Licence placeholder

### ISSUE THREAD

**Issue by rphlmr** [calcom/cal.com#12150]
Hello, just wanted to 'warn' you, in case it matters.

### Issue Summary

There is un-completed placeholders in the licence.

### Steps to Reproduce

https://github.com/calcom/cal.com/blob/31fc4724e0573c7150af9edcb4668ca00ceb3d57/LICENSE#L640-L641

### Actual Results

/

### Expected Results

/

### Technical details

/

### Evidence

/

**Comment by PeerRich** [comment]
no, this is an example license you can attach to your new license
