### ISSUE TITLE
Incorrect Availability dates for multi-day events with Google Calendar

### ISSUE THREAD

**Issue by giswqs** [calcom/cal.com#12157]
### Issue Summary

On my Google Calendar, I have a three-day event (8am on Nov. 15 - 5pm on Nov. 17). I would expect that cal.com to show  that I am unavailable on these three days, but it does not. It appears that multi-day events on Google Calendar are not recognized by cal.com, which is supposed to mark those days as unavailable. One workaround is to duplicate the event on each date (8am-5pm on Nov. 15, 16, 17, respectively), which is a bit inconvenient. 

### Evidence

![image](https://github.com/calcom/cal.com/assets/5016453/4e544378-7919-4a94-bd45-dcbc5b3cbde4)
![image](https://github.com/calcom/cal.com/assets/5016453/5a76f5e1-e180-4b12-aebd-6c20ebb8d874)

![image](https://github.com/calcom/cal.com/assets/5016453/c867ed04-5c1d-476d-85e7-877643473ef2)

**Comment by CarinaWolli** [comment]
I just tested that and it did block off my availability. @giswqs just to make sure, is your event marked as a busy event?

**Comment by CarinaWolli** [comment]
> Marking the event as `busy` solves the issue. Thank you, @CarinaWolli

Solved

**Comment by VicFouq** [comment]
@CarinaWolli I still have the same problem and don't understand how to use this `busy` config

**Comment by CarinaWolli** [comment]
> @CarinaWolli I still have the same problem and don't understand how to use this `busy` config

When editing a event in google calendar you can set it as busy or free
![Screenshot 2024-04-11 at 10 05 01 AM](https://github.com/calcom/cal.com/assets/30310907/011b503a-7d0f-41c9-8019-3c6c74947402)

**Comment by VicFouq** [comment]
@CarinaWolli Perfect, thanks
