### ISSUE TITLE
[CAL-2664] Phone Number Input

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#12162]
The Phone number type input only supports international phone numbers so local numbers like 415-999-9999 would become "+415 999 9999". 

- Add information icon next to label with text "Please enter number in international format"

- Cache country code for some time

https://github.com/calcom/cal.com/assets/53316345/6caff0f5-1f6b-4980-adb3-f01e1de653d0

<sub>[CAL-2664](https://linear.app/calcom/issue/CAL-2664/phone-number-input)</sub>

**Comment by adarshlilha** [comment]
@Udit-takkar can I take this up, if available?
A pointer on where this view is visible would be helpful, I do not see this input while creating a new event

**Comment by manpoffc** [comment]
> @Udit-takkar can I take this up, if available? A pointer on where this view is visible would be helpful, I do not see this input while creating a new event


Just edit any existing event and under location tab add 'Attendee  Phone Number' option and got to the event booking page and you'll be able to see the above output.

**Comment by Amit91848** [comment]
Hey! 
I have added the information icon for the label. But unsure where and how to cache the country code @Udit-takkar ?
