### ISSUE TITLE
[CAL-2665] Remove button not displayed now in avatar upload ( Regression)

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#12164]
https://github.com/calcom/cal.com/pull/12143#pullrequestreview-1703557065

<sub>[CAL-2665](https://linear.app/calcom/issue/CAL-2665/remove-button-not-displayed-now-in-avatar-upload-regression)</sub>

**Comment by MeenuyD** [comment]
Hello @Udit-takkar where are you see this because I can see the remove button.
<img width="938" alt="Screenshot 2023-11-01 at 7 15 32 AM" src="https://github.com/calcom/cal.com/assets/116630390/30994ec5-ae83-4315-8640-0e66a5b03d8b">

**Comment by Udit-takkar** [comment]
@MeenuyD 

1) Remove button should be displayed only when an image is set. 
2) Remove button should not be displayed when default image is used ( like in the screenshot you sent)

**Comment by MehulZR** [comment]
![image](https://github.com/calcom/cal.com/assets/86384652/aa343474-185f-4264-9db2-f0cbbc53db5a)

UserData always contains the organization object(even for new account).
1. The condition on line 95 fails
2. fetchedImgSrc becomes ""(empty string)
3. checkIfItFallbackImage func returns true.

![image](https://github.com/calcom/cal.com/assets/86384652/52559fb6-49ae-4199-be2c-9172e74aedd8)

4. isFallbackImg prop becomes true.

![Screenshot from 2023-11-02 23-56-10](https://github.com/calcom/cal.com/assets/86384652/cd16bc9f-272a-4c91-80f2-a1c65e0bd8e8)

5. Causing the showRemoveAvatarBtn to be false

![image](https://github.com/calcom/cal.com/assets/86384652/597b624f-5545-457c-bc19-1de8aaffcd8f)

**Comment by Udit-takkar** [comment]
@MehulZR ok feel free to raise a PR to fix this

**Comment by MehulZR** [comment]
PR is just about done. 
Just a quick question. What should be the case when user doesn't have a avatar?
1. ![image](https://github.com/calcom/cal.com/assets/86384652/43ee8969-5689-4275-bda2-dd5e354c15d7)
2. ![Screenshot from 2023-11-04 01-10-28](https://github.com/calcom/cal.com/assets/86384652/6c678747-0f2f-4658-a477-45ce61009425)
