### ISSUE TITLE
Double Works when removing an event. 

### ISSUE THREAD

**Issue by lawweiliang** [calcom/cal.com#12182]
@Udit-takkar 

Scenario
When I remove the event in my Google calendar. 
The event over cal.com should be removed as well but now it is still there. 
Currently, I need to do double works, delete the event over google calendar then delete the event over cal.com. 

![image](https://github.com/calcom/cal.com/assets/34936929/b245d196-f75f-4807-b627-0ce13fccb13b)

![image](https://github.com/calcom/cal.com/assets/34936929/0e706fd8-d318-4baf-81da-00e3ff2bf190)

**Comment by Udit-takkar** [comment]
@joeauyeung should it be removed?

**Comment by joeauyeung** [comment]
Right now we don't see what users do to their calendars but @lawweiliang, I would suggest cancelling the event on Cal.com as it'll delete the event from your calendar and let your attendees know.

@Udit-takkar in the future we could make use of what @zomars is doing with the calendar caching.

**Comment by lawweiliang** [comment]
@joeauyeung 
Hmm, right. Delete the event over cal.com would delete the event over my calendar. Thanks.
