### ISSUE TITLE
Bookings Page Keep Loading

### ISSUE THREAD

**Issue by lawweiliang** [calcom/cal.com#12181]
### Issue Summary

After booking, user clicked "Back to bookings". Then, the booking page keeps loading. 

### Evidence

![keep_loading](https://github.com/calcom/cal.com/assets/34936929/ffdde7bd-1687-44cf-87fb-a2cbf2becefc)

**Comment by Udit-takkar** [comment]
@lawweiliang not able to reproduce this bug. do you see any error in console?

**Comment by Udit-takkar** [comment]
or network tab

**Comment by lawweiliang** [comment]
@Udit-takkar 

Browser
![image](https://github.com/calcom/cal.com/assets/34936929/166846d3-bec5-4d91-baef-c14ce0ff0c5b)

Console
![image](https://github.com/calcom/cal.com/assets/34936929/0d4e9839-60f8-46cc-9e09-2d5a9c78b571)

Network
![image](https://github.com/calcom/cal.com/assets/34936929/a10faf2e-0637-40f0-ae07-97770e165920)

**Comment by Udit-takkar** [comment]
@lawweiliang It loads fine for me when i impersonate your account

<img width="1512" alt="Screenshot 2023-11-01 at 10 29 05 PM" src="https://github.com/calcom/cal.com/assets/53316345/d19a0e6a-39b7-4d0b-a331-30a9a3b10395">

**Comment by Udit-takkar** [comment]
@lawweiliang  please use https://app.cal.com/bookings/upcoming instead of  https://cal.com/bookings/upcoming. This could be the reason.

**Comment by lawweiliang** [comment]
@Udit-takkar 
I don't think the problem is from the link. You may take a look on the following picture. 

![image](https://github.com/calcom/cal.com/assets/34936929/46687c5a-f638-424a-a47a-96c06e93b0e2)

**Comment by Udit-takkar** [comment]
@lawweiliang could you try [app.cal.com](https://app.cal.com/bookings/upcoming) ?

**Comment by lawweiliang** [comment]
> @lawweiliang could you try [app.cal.com](https://app.cal.com/bookings/upcoming) ?

app.cal.com is working.

Question
Why back to booking and link it to cal.com? Mistake?

**Comment by Udit-takkar** [comment]
> Question Why "back to booking" button link it to cal.com?

Oh Okay will have to fix this then
