### ISSUE TITLE
[CAL-2906] Event with seating: The custom question answers of the first user to book are unintentionally exposed to subsequent attendees when rescheduling or canceling.

### ISSUE THREAD

**Issue by xandyalexandrec** [calcom/cal.com#12188]
### Issue Summary

When you host an event that provides seats and includes custom booking questions, the answers of the first user to book are inadvertently revealed to subsequent attendees of the event when they attempt to reschedule or cancel.

### Steps to Reproduce

1. Create an event that offers seats, uncheck both checkboxes 'Share attendee information between guests' and 'Show the number of available seats.'
2. Add custom questions like phone number, zip code, and so on.
3. Register for this event.
4. Register again for the same event on the same day and time, but provide different answers and use a different email.
5. Open the second registrant's email inbox for the confirmation email and click on the button to cancel or reschedule the meeting.
6. Notice that the first person to register for this event appears in the field instead of the user's own questions.

### Actual Results

* The answers of the first user to book are inadvertently revealed to subsequent attendees of the event when they attempt to reschedule or cancel.

### Expected Results

* To display the answers of the correct attendee instead of the first attendee, or have them appear blank instead.

### Technical details

* Production env.

### Evidence

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ffabd2d3-d4c7-46f2-ba9b-c7b6a35a2b9d/8a38e8a3-afbd-474b-a055-572b872cd243?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mZmFiZDJkMy1kNGM3LTQ2ZjItYmE5Yi1jN2I2YTM1YTJiOWQvOGEzOGU4YTMtYWZiZC00NzRiLWEwNTUtNTcyYjg3MmNkMjQzIiwiaWF0IjoxNzA0OTAzNjIwLCJleHAiOjE3MDQ5OTAwMjB9.SetlACdYI5_8zPycz36tWNEnScsgDLEGaJmy2EDTL10)

![Screenshot 2023-11-01 at 17 02 33](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/90ab6823-ce23-4e83-861a-cc6fd7fb6b51/c19c25e7-8b2d-4495-9db0-f3f03150e407?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MGFiNjgyMy1jZTIzLTRlODMtODYxYS1jYzZmZDdmYjZiNTEvYzE5YzI1ZTctOGIyZC00NDk1LTlkYjAtZjNmMDMxNTBlNDA3IiwiaWF0IjoxNzA0OTAzNjIwLCJleHAiOjE3MDQ5OTAwMjB9.ltBCz3jDDValGC5HuXmXag5a8KgBeLc-yOR6MEXkDY4)

![Screenshot 2023-11-01 at 17 07 53](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c0dbf390-3e43-45ca-b4fc-c963c88ed1ee/29309ea7-38b0-4880-992c-29c22b6d4852?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jMGRiZjM5MC0zZTQzLTQ1Y2EtYjRmYy1jOTYzYzg4ZWQxZWUvMjkzMDllYTctMzhiMC00ODgwLTk5MmMtMjljMjJiNmQ0ODUyIiwiaWF0IjoxNzA0OTAzNjIwLCJleHAiOjE3MDQ5OTAwMjB9.N6zn2pxe69nW2tZTFH7caNpkNcsj3gI9BkkR4KW5Jxs)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2906](https://linear.app/calcom/issue/CAL-2906/event-with-seating-the-custom-question-answers-of-the-first-user-to)</sub>

**Comment by MehulZR** [comment]
After looking into it a bit, this is the current situation.
If this solution is viable then I can start working on it.
![Untitled-2023-11-07-2048](https://github.com/calcom/cal.com/assets/86384652/2665bfdf-5491-4d53-8510-15ad13684642)

**Comment by xandyalexandrec** [comment]
Hi @MehulZR, for me it makes a lot of sense to be inside of the Booking Seat ID instead of the Booking ID.

**Comment by MehulZR** [comment]
@xandyalexandrec Yeah. If one of the core team members approves this, then we can get this going.

**Comment by CarinaWolli** [comment]
@MehulZR Sorry I totally missed that. But this sounds good to me. Sounds about the same as what I said in the comment [here](https://github.com/calcom/cal.com/pull/12547#issuecomment-1843391404): 

> It appears that the main issue is that we don't save custom answers for additional seats
> We should store these answers in the data field of bookingSeat, where we are already saving additional notes. This should also enable us to display the correct custom answers upon rescheduling.

**Comment by MehulZR** [comment]
Hey @CarinaWolli, I have been working on this and I am assuming some things and have some question regarding those (correct me if I am assuming anything wrong). When we are looking for the details from the perspective of single user( attendee ), we show only his response.

Which looks something like this

https://github.com/calcom/cal.com/assets/86384652/2e316a0f-dac4-4ba9-aa91-6d14facafc9c

 
What I wanna know about is, what should we show if we are looking from the perspective of the host. 

Like in the video below?

https://github.com/calcom/cal.com/assets/86384652/bddf33a7-00c2-4bb6-b333-32da966d4f07

Do we want to show all the responses?

Also currently I have fixed custom questions and description (notes) field, there are also other fields which do not have correct behaviour such as location, title ( as you can see the title is set between host and first attendee), cancellation and rejection reason.

**Comment by CarinaWolli** [comment]
> Hey @CarinaWolli, I have been working on this and I am assuming some things and have some question regarding those (correct me if I am assuming anything wrong). When we are looking for the details from the perspective of single user( attendee ), we show only his response.

correct

> What I wanna know about is, what should we show if we are looking from the perspective of the host.
> Do we want to show all the responses?

Good question. I don't think we have any designs for that yet. To keep it simple, for now, I would vote for not showing the custom answers in the booking detail for the organizer (if there is only one seat booked we can). The host would need to look at the booking confirmation email to get the answers of the attendee, not ideal but good enough for now.

> Also currently I have fixed custom questions and description (notes) field, there are also other fields which do not have correct behaviour such as location, title ( as you can see the title is set between host and first attendee), cancellation and rejection reason.

Sounds good 🙏

**Comment by TaduJR** [comment]
Hello @CarinaWolli. Do you have any idead why is bookingUid is attached when someone browses the available time slot for booking?https://github.com/calcom/cal.com/blob/main/packages/trpc/server/routers/viewer/slots/util.ts#L594

**Comment by MehulZR** [comment]
Hey @CarinaWolli, I have pulled the PR. There are some tests failing, will look into those tomorrow. Typescript isn't happy rightn ow, how should I enforce typesafety for JSON values retured by the prisma? Shall I just enforce them with `as` or is there a better way?
