### ISSUE TITLE
API - return `hosts` on event-types response

### ISSUE THREAD

**Issue by Shpadoinkle** [calcom/cal.com#12190]
### Is your proposal related to a problem?
- Currently we can assign `hosts` to an event-type using the PATCH request 
- But the response for event-type does not return the list of current existing hosts 
- This is an issue, as the `host` array passed to the PATCH request is used to overwrite the current hosts.  So we would need to be able to first retrieve the current list of hosts if we ever needed to add or remove someone via the API. 

### Describe the solution you'd like
- Easiest solution
  - add `hosts: true` to the query in `apps/api/pages/api/event-types/_get.ts` and `apps/api/pages/api/event-types/[id]/_get.ts` 
- or another endpoint for 'adding' and 'removing' a single user as a host from an event type  

### Describe alternatives you've considered
no alternatives i can see as the hosts data is needed on the event-type response 

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by kaulshashank** [comment]
I'm facing the same issue, we have many team members but only a few assigned as round robin hosts to certain event types.

Listing availabilities by event type id gives availabilities of all team members even if they are not a host on the event type. So as an alternative I was looking to see if `hosts` is populated on the event type, but it's always an empty array.

We're currently blocked from building our automation so any quick patches would be greatly appreciated.

cc: @PeerRich and team

**Comment by alishaz-polymath** [comment]
I'll look into it. Thank you for raising the issue 🙏

**Comment by kaulshashank** [comment]
@alishaz-polymath what is the usual timeline for merged PRs in this repo to ship to api.cal.com?

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath what is the usual timeline for merged PRs in this repo to ship to api.cal.com?

Depends on when the release is. Once a PR is merged, it usually is shipped either later same week or early next week.
