### ISSUE TITLE
[CAL-2668] App: Pipedrive CRM

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12197]
same as the other CRMs

<sub>[CAL-2668](https://linear.app/calcom/issue/CAL-2668/app-pipedrive-crm)</sub>

**Comment by jatinsandilya** [comment]
on it!

**Comment by NishanthMolleti** [comment]
Hi @jatinsandilya  , can I join you on this task?

**Comment by Ansh-Sonkusare** [comment]
@PeerRich what other crm is implemented in the repo. Can you refer the code location for it.

**Comment by Min2who** [comment]
@PeerRich when i opened the CAL-2668
it says permission denied could you reference once more
