### ISSUE TITLE
Error alert not removing

### ISSUE THREAD

**Issue by sirilmp** [calcom/cal.com#12203]
### Issue Summary
I updated the email, and clicked the "Update" button, which triggered a password prompt in a modal box. However, I mistakenly entered the wrong password and received an error message below the input box. Despite clearing the input box, the error message persisted. Subsequently, I entered another incorrect password and attempted to confirm, but the error message remained. Frustrated, I clicked the "Close" button and then retried clicking the "Update" button, only to encounter the same popup and the persisting error message.

### Steps to Reproduce

1. Click on you're name in the left sidebar
2. Click on the My Profile button
3. Edit the email and click the Update button
4. Enter the wrong password and click on the confirm button
5. show an error message under the input box.
6. clear the input box, still the error will show.
7. click on the close button and the popup will close 
8. then click on the update button again, the same error message will show

### Actual Results
1. Remove the error message when we clear the input box or click on the confirm button
2. when closing the model, also remove the error message

### Expected Results
1. Remove the error message when we clear the input box or click on the confirm button
2. when closing the model, also remove the error message

### Evidence
https://github.com/calcom/cal.com/assets/73417488/169a54b8-6126-49b9-b6e1-570416748bcf

**Comment by Sahil-B07** [comment]
I think I have the solution

**Comment by PeerRich** [comment]
i dont think we need this
