### ISSUE TITLE
Docs( contributing ): different bytes for 'CALENDSO_ENCRYPTION_KEY'

### ISSUE THREAD

**Issue by Sahil-B07** [calcom/cal.com#12205]
during setup I notice that the command for **CALENDSO_ENCRYPTION_KEY** as `openssl rand -base64 24 `which was given in CONTRIBUTING.md, but while setting the .env there was `openssl rand -base64 32`, suggest to use 32 bytes encryption algorithm.

was that an option to use either of them ?

**CONTRIBUTING.md**
<img width="916" alt="Screenshot 2023-11-02 at 7 26 12 PM" src="https://github.com/calcom/cal.com/assets/92709590/f17b110e-a772-414c-b9db-71682362e273">

<hr>

**.env**
<img width="916" alt="Screenshot 2023-11-02 at 7 27 22 PM" src="https://github.com/calcom/cal.com/assets/92709590/ad04b4b6-bdb8-4155-9f1f-e236805183f3">

**Comment by Swapnil-2502** [comment]
I used both of them while setting up the project locally. Just follow all the points mentioned in it.

**Comment by Sahil-B07** [comment]
> I used both of them while setting up the project locally. Just follow all the points mentioned in it.

Yes, me too
was just pointing out that

**Comment by Swapnil-2502** [comment]
> > I used both of them while setting up the project locally. Just follow all the points mentioned in it.
> 
> Yes, me too was just pointing out that
> 
> and idk how did the bot labelled it as bounty ;(

Yeah even I was thinking the same.

**Comment by PeerRich** [comment]
i think this has been fixed

**Comment by Sahil-B07** [comment]
okay, but why there are two different commands for CALENDSO_ENCRYPTION_KEY
i doubt, plz look contributing.md and .env for CALENDSO_ENCRYPTION_KEY
