### ISSUE TITLE
Sync events backwards from Google to Cal

### ISSUE THREAD

**Issue by jobenjada** [calcom/cal.com#12206]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I moved an event in my Google calendar but in Cal it still shows the old time. It looks like the old time blocks my availability.

### Steps to Reproduce

1. Create event
2. Move it in Google calendar
3. Check cal event list
4. Try to book slot for initial time of event

**Comment by PeerRich** [comment]
i think this is under way and has a duplicate issue
