### ISSUE TITLE
Redirection to custom static HTML page not working

### ISSUE THREAD

**Issue by pietro14** [calcom/cal.com#12217]
### Issue Summary

Redirection to a custom static HTML page is not working as expected.

### Steps to Reproduce

1. Set the URL of a custom page (in this case, a static HTML page in a public Google Cloud bucket).
2. Click on the "Schedule" button within the scheduler.

### Actual Results

When attempting to redirect, the following error is encountered:

![Error Screenshot](https://github.com/calcom/cal.com/assets/41691318/911e261d-5dcf-443f-8800-c7df3a6fdb69)

It appears that cal.com is forwarding additional parameters, resulting in an incorrect URL. The final URL should be:

https://storage.googleapis.com/show_confirmation/confirm.html

However, the final URL includes unwanted parameters, resulting in this:

https://storage.googleapis.com/show_confirmation/confirm.html?user=pietro14&type=EVENT-60&isSuccessBookingPage=true&email=EMAIL&eventTypeSlug=EVENT&title=EVENT+-+USER&description=&startTime=2023-12-12T08%3A00%3A00.000Z&endTime=2023-12-12T09%3A00%3A00.000Z&location=LINK

- Browser version: Version 118.0.5993.117 (Official Build) (64-bit)

Note: I am not self-hosting.

**Comment by PeerRich** [comment]
can you host your page somewhere else? this seems to be a google apis issue
