### ISSUE TITLE
Enhance app discoverability with search tags

### ISSUE THREAD

**Issue by ubinatus** [calcom/cal.com#12212]
### Is your proposal related to a problem?

As the App Store expands with an influx of new apps, users could face challenges in discovering specific types of apps due to limited search capabilities. For example, apps like "Alby" that enable bitcoin payments are not easily discoverable when users search using relevant keywords such as "bitcoin". The existing 'payment' category filter does not adequately narrow down search results to show bitcoin-related apps.

### Describe the solution you'd like

To address this, it would be beneficial to implement a tagging system for app metadata. Requiring apps to include specific "search tags" could greatly enhance the discoverability of apps within the store. This would allow users to find apps by keywords associated with an app's functionality, beyond the current category filters, especially as the number of integrated apps continues to grow.

For example, the "Alby" app could be tagged with keywords: _bitcoin, cryptocurrency, payments, blockchain, lighting network_. These tags would help users find the "Alby" app when searching for solutions related to bitcoin and cryptocurrency payments within the Cal.com App Store.

Importantly, to maintain the quality and relevance of these tags, I think that they should be subject to review by the Cal.com team as part of the app submission process. This step ensures that tags remain consistent, appropriate, and valuable in improving search results for end-users.

**Comment by PeerRich** [comment]
eventually, yeah but not right now. the categories only have 10 apps each so it shouldn't be that bad. also the search works across descriptions

**Comment by ubinatus** [comment]
> eventually, yeah but not right now. the categories only have 10 apps each so it shouldn't be that bad. also the search works across descriptions

Hey Peer! Thanks for the reply. Btw, the AppStore page currently, [as last commit](https://github.com/calcom/cal.com/commit/d1d50b0d9131e650eab2a88396e130dfb2067da4), does not search across descriptions:

https://github.com/calcom/cal.com/blob/d1d50b0d9131e650eab2a88396e130dfb2067da4/packages/ui/components/apps/AllApps.tsx#L168
