### ISSUE TITLE
Server Error - Error: Error serializing `.csrfToken` returned from `getServerSideProps` in "/auth/login".

### ISSUE THREAD

**Issue by arpitprod** [calcom/cal.com#1221]
### Issue Summary

Code not running after setup new project

<img width="1439" alt="Screenshot 2021-11-26 at 16 06 24" src="https://user-images.githubusercontent.com/19798516/143568274-4c0a0163-c433-442f-9169-988262c216b7.png">

### Steps to Reproduce
1. Setup new project
2. run yarn dev

### Technical details

- Browser version: Chrome 96
- Node.js version: v16.13.0

**Comment by kamikazebr** [comment]
You tried ran `yarn` and `yarn dx`?

**Comment by arpitprod** [comment]
yes, I tried with Quick start (`yarn` and `yarn dx`) and manual both (`yarn` and `yarn dev`)
When Quick start not worked then I tried with manual also

**Comment by manjufy** [comment]
Experiencing the same problem here.

**Comment by manjufy** [comment]
@arpitprod 
do the following
```
- remove node_modules
- make sure you have run the latest migrations `npx prisma migrate deploy`
- make sure the port you are running is the same as in one in your .env
````

For me the issue was.
I was running the project on port 3005 by changing `dev: next dev -p 3005` and my .env was pointing to `http://localhost:3000`

**Comment by AshnaSabu123** [comment]
Facing the same issue.

**Comment by agustif** [comment]
This seems related to NextAuth somehow will investigate it further

**Comment by alannnc** [comment]
I ran into this issue and it was due a miss match ports for web/website.

**Comment by Ifenna-Pascal** [comment]
I am facing same error

**Comment by yanickrochon** [comment]
After performing `signOut`, I get this from my sign-in page. Whatever value is being read, it's not there (i.e. `undefined`) and it should default to `null` to fix this error. Unfortunately, the `getCsrfToken` function does not specify what value is being used from the `IncomingMessage` argument.

This is clearly **not** "completed" as this issue seems to indicate.

**Comment by aquodigital** [comment]
This mostly happens due to a missing variable in `.env` file. 

At least in my case that was the issue.

**Comment by leultefera** [comment]
Make sure you have the right .env files for the codebase on file and it should work.

**Comment by jeni1616** [comment]
In your .env file, if you are on a local site, use / at the end of the URL.

NEXTAUTH_URL=http://localhost:3000/

It fails when we use NEXTAUTH_URL=http://localhost:3000

Stupid mistake, it took me hours before I found https://github.com/nextauthjs/next-auth/discussions/4220#discussioncomment-3188228

**Comment by sgtpenguin** [comment]
@jeni1616 Incredible.  I don't think I would have ever thought of this.  Thank you so much

**Comment by getellez** [comment]
Remove `node_modules` worked for me. Having the slash at the end was not necessary.

**Comment by Spiteless** [comment]
Just ran into this today, was because I was running something else on the default `http://localhost:3000`
