### ISSUE TITLE
[CAL-2670] Verify more things in ics file in `bookingScenario` tests.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12214]
Currently bookingScenario tests don't check the title in ics file but they do test it in Email content, we can quickly add the support to verify this in ics file. We would just need to modify `toHaveEmail` function as it already has all the appropriate data.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/12170#discussion_r1381165515_
            

<sub>[CAL-2670](https://linear.app/calcom/issue/CAL-2670/verify-more-things-in-ics-file-in-§bookingscenario§-tests)</sub>

**Comment by ptdatta** [comment]
@hariombalhara Can I work on it?

**Comment by hariombalhara** [comment]
@ptdatta Yeah feel free to pick it.
