### ISSUE TITLE
[CAL-2671] Individual Insights Page has Team Insights

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12215]
Individual insights page has insights from from "most booked" and "least booked" members. It should just be data that pretains to them:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e74bdb02-5e26-41e8-87be-8dda7e382fd4/f48ddf61-24ba-4a09-b94c-ed1aa2b50df4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNzRiZGIwMi01ZTI2LTQxZTgtODdiZS04ZGRhN2UzODJmZDQvZjQ4ZGRmNjEtMjRiYS00YTA5LWI5NGMtZWQxYWEyYjUwZGY0IiwiaWF0IjoxNjk4OTkxOTYyLCJleHAiOjE2OTkwNzgzNjJ9.dSRqQBHSC2TupIr9T7wnYSh8Vm3x1KlTsSEo1NIejwI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2671](https://linear.app/calcom/issue/CAL-2671/individual-insights-page-has-team-insights)</sub>

**Comment by GauravBurande** [comment]
> Individual insights page has insights from from "most booked" and "least booked" members. It should just be data that pretains to them:
> 
> ![](https://camo.githubusercontent.com/61fd4f3ccbcf571b636baa937a227f00492b632e9e87fc1fbc554636642c1386/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f65373462646230322d356532362d343165382d383762652d3864646137653338326664342f66343864646636312d323462612d346130392d623934632d6564316161326235306466343f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c3255344e6d4a6d4f5455334c5751344d6d59744e4459315a5331694d6a41314c54457a4e5455314f575930596a59794d79396c4e7a52695a4749774d6930315a5449324c5451785a5467744f4464695a5330345a4752684e32557a4f444a6d5a4451765a6a51345a47526d4e6a45744d6a526959533030595441354c5749354e474d745a57517859574579596a55775a4759304969776961574630496a6f784e6a6b344f546b784f5459794c434a6c654841694f6a45324f546b774e7a677a4e6a4a392e645352715142485343325475704972395437776e59536838566d3378314b6c547353456f314e49656a7749)
> 
> From [SyncLinear.com](https://synclinear.com) | [CAL-2671](https://linear.app/calcom/issue/CAL-2671/individual-insights-page-has-team-insights)

So, we just need to remove those two components, right?

**Comment by AnkityadavIITR** [comment]
Hey , i want to know is this issue still open?

**Comment by rajdip-b** [comment]
Is the issue still relevant? I went through the insights section and found this:
![image](https://github.com/calcom/cal.com/assets/83924254/49dab3fa-1b36-454b-a338-c6e85531fa5a)

I'm assuming the topmost and the left most components need to be removed. @shirazdole

**Comment by shyamtawli** [comment]
@shirazdole Sir, Can you explain it more? I like to work on it but I am not getting the problem statement.

**Comment by rahulvivek** [comment]
Hi @shirazdole, Is this issue still relevant?
