### ISSUE TITLE
Switch Close CRM integration to use OAuth

### ISSUE THREAD

**Issue by philfreo** [calcom/cal.com#12228]
### Is your proposal related to a problem?

When the [Close CRM app](https://app.cal.com/apps/closecom) was created, Close only supported Basic Auth via API Key.

Now Close supports OAuth:
https://developer.close.com/topics/authentication-oauth2/

### Describe the solution you'd like

It would be great if the integration could be converted so that at least new users would be prompted to connect via OAuth instead.

### Additional context

Beyond ease of set up and better security for users, there may be other benefits that Close gives toward OAuth apps. For example it also means Cal could take advantage of Close's new [Meeting Integration Notes feature](https://developer.close.com/resources/activities/meeting/#create-or-update-third-party-meeting-integration) which requires an OAuth connection. Similarly, Close's new [Scheduling Link feature](https://developer.close.com/resources/scheduling-links/) can also be more sophisticated once there's an OAuth connection.

Related to:
https://github.com/calcom/cal.com/blob/d1d50b0d9131e650eab2a88396e130dfb2067da4/packages/app-store/closecom/lib/CalendarService.ts#L34-L38

Get in touch with phil@close.com or support@close.com if you want to collaborate on a deeper integration!

**Comment by PeerRich** [comment]
i agree. lets collaborate here. feel free to open a PR
