### ISSUE TITLE
[CAL-2820] invalid type of error in reschedule booking (Invalid phone number)

### ISSUE THREAD

**Issue by ankit10000** [calcom/cal.com#12220]
### Issue Summary

invalid type of error in reschedule booking (Invalid phone number)

### Steps to Reproduce

1. Go on bookings.
2. Click on edit bookings.
3. reschedule booking and click
4. after you go next page you select date
5. you select date after click on button reschedule button you got an error (phone number not found)
6. phone number section is not visible, but error is showing

![Web capture_1-11-2023_23238_localhost](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9f84bcaf-07a6-487f-92d5-35359b380c22/afa248d4-336f-4ced-9a3e-9824ab397f0a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85Zjg0YmNhZi0wN2E2LTQ4N2YtOTJkNS0zNTM1OWIzODBjMjIvYWZhMjQ4ZDQtMzM2Zi00Y2VkLTlhM2UtOTgyNGFiMzk3ZjBhIiwiaWF0IjoxNzAyOTUwNzExLCJleHAiOjE3MDMwMzcxMTF9.6X6IbWPnhtmeADfzeYdt9IVXXQj5AnGDYqk0A78L3-0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2820](https://linear.app/calcom/issue/CAL-2820/invalid-type-of-error-in-reschedule-booking-invalid-phone-number)</sub>

**Comment by aaronsharon** [comment]
Can you tell me how to set up it to my local system?

**Comment by TaduJR** [comment]
> ### Issue Summary
> invalid type of error in reschedule booking (Invalid phone number)
> 
> ### Steps to Reproduce
> 1. Go on bookings.
> 2. Click on edit bookings.
> 3. reschedule booking and click
> 4. after you go next page you select date
> 5. you select date after click on button reschedule button you got an error (phone number not found)
> 6. phone number section is not visible, but error is showing
> 
> ![Web capture_1-11-2023_23238_localhost](https://private-user-images.githubusercontent.com/88035341/280271016-a26394bf-635f-4116-8679-2c8265853bd2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzUyOTcsIm5iZiI6MTcwMDkzNDk5NywicGF0aCI6Ii84ODAzNTM0MS8yODAyNzEwMTYtYTI2Mzk0YmYtNjM1Zi00MTE2LTg2NzktMmM4MjY1ODUzYmQyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNzU2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2NlYzNhZDJmMjdjM2FiYjlhMzRmZWM5MzM4OWRhNWYwOTIwZTFmNTZmMGY1ZTI5MjExZTk2ZTQxMTNmOTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GYGtXLkbIWsFiaZeDh-qgCZPyRInjOUGcxdUEVCMIjE)

Hello @ankit10000. I couldn't reproduce the issue. Have you enabled other advance setting for that specific booking which you didn't included on steps to reproduce..

**Comment by skmanoj322** [comment]
ya i am also not able to reproduce the bug

**Comment by PranitPatil03** [comment]
Hello @ankit10000 

I tried to replicate the bug in my local environment, and I can reschedule the bookings. Everything else is working fine.

**Comment by keithwillcode** [comment]
Closing until we can reproduce again.
