### ISSUE TITLE
[Bug] wrong color of svg hamburger menu at routes which are in dark themes at small screens

### ISSUE THREAD

**Issue by hxdy-1** [calcom/cal.com#12235]
### Issue Summary

in the devices like tablets and smaller ones, on routes/pages that are in dark theme ("/platform" and "/enterprise" to be precise) the hamburger menu svg is still in black color and hence users cant see it. On click it still opens the drop down menu tho.

### Steps to Reproduce

1. Go to cal.com and open the dev tools to see the website in smaller devices using responsive mode
2. Click on the hamburger menu and from dropdown go to the "Platform"
3. Now you can see the hamburger is not visible anymore, but it is still there and you can still click on it

### Actual Results

- What's happening right now that is different from what is expected
On the routes/pages with dark themes, that hamburger svg of dropdown menu is also in black color and hence makes it invisible

### Expected Results

- This is an ideal result that the system should get after the tests are performed
On the routes/pages with dark themes, the hamburger of dropdown menu should be of color white

### Evidence

cal.com/platform:
look at the top right corner in all ss...
![image](https://github.com/calcom/cal.com/assets/115286446/5a9ed769-4e2b-468f-b7ee-66e5937f0ea6)
![image](https://github.com/calcom/cal.com/assets/115286446/5ee73955-a54f-478e-8bac-5b3f504b6bcc)

it should be like this IMO:
dropdown is closed:
![image](https://github.com/calcom/cal.com/assets/115286446/f4c3ff16-c8f7-421e-9876-bce6063238b9)

dropdown is opened:
![image](https://github.com/calcom/cal.com/assets/115286446/0b8a5116-58c2-476d-9e5f-5a4139f72799)

**Comment by RakeshBB08** [comment]
attempt #12235

**Comment by ZeusAbhi** [comment]
attempt #12235

**Comment by chetansource** [comment]
attempt #12235

**Comment by chetansource** [comment]
hello i have installed project locally but unable to find where the error is occurring can anyone help

**Comment by hassanonweb** [comment]
attempt #12235

**Comment by Vivek7038** [comment]
attempt #12235

**Comment by PeerRich** [comment]
this is inside the website repo and not inside the app. will fix

**Comment by hxdy-1** [comment]
> this is inside the website repo and not inside the app. will fix

Alright

**Comment by SouravGRoy** [comment]
It's still not working, if you want it to be solved than open the issue

**Comment by hxdy-1** [comment]
> It's still not working, if you want it to be solved than open the issue

One of the maintainer closed this issue, i think they'll look after it later

**Comment by SouravGRoy** [comment]
oh alright👍
