### ISSUE TITLE
Error connecting to postgres

### ISSUE THREAD

**Issue by TaduJR** [calcom/cal.com#12234]
![2023-11-05 15_28_45-Settings](https://github.com/calcom/cal.com/assets/90861780/4d3bdcc4-d68e-4964-b098-60f1c2ad8b11)
I am trying to start the project but It's giving me an error. The error is related to the database "yarn workspace @calcom/prisma db-migrate" successfully migrated which indicates the connection string in .env is fine but yarn dev is raising an error when I try to login on localhost:3000 using the migrated credentials 

@calcom/web:dev: - wait compiling /...
@calcom/web:dev: error connecting to engine: sql, type: postgres db: error: password authentication failed for user "postgres"

This is my .env
DATABASE_URL="postgresql://postgres:toor@localhost:5432/calendso"

**Comment by Udit-takkar** [comment]
did you have postgres installed with database name calendso and username and password postgresql://postgres:toor@localhost:5432/calendso?

**Comment by TaduJR** [comment]
Thank you so much for your reply.

Yes I did all of them. Even "yarn workspace @calcom/prisma db-migrate" migrated successfully and able to create the all the sample tables and records. The occurs when I try to login using the sample accounts after "yarn dev" command.

**Comment by TaduJR** [comment]
> did you have postgres installed with database name calendso and username and password postgresql://postgres:toor@localhost:5432/calendso?

Thank you so much for your reply.

Yes I did all of them. Even "yarn workspace @calcom/prisma db-migrate" migrated successfully and able to create the all the sample tables and records. The occurs when I try to login using the sample accounts after "yarn dev" command.

**Comment by Udit-takkar** [comment]
@zomars might know about this

**Comment by seeker-ibu** [comment]
Hi, This an authentication issue. Which means your password is incorrect. 

First of all, the password in the URL is set to "toor." Make sure that the "toor" password is indeed the correct password for the "postgres" user in your PostgreSQL database.

Incase if you don't know your password also don't worry, I will explain the steps to change your postgres password, if you know your system password

Run this command in the terminal "sudo -u postgres psql", then it will ask system password, just enter that.After then you have to run "\password postgres" and give new password.Then change the password in the URL in .env file.

This would be enough to go through. Thanks.

**Comment by TaduJR** [comment]
> Hi, This an authentication issue. Which means your password is incorrect.
> 
> First of all, the password in the URL is set to "toor." Make sure that the "toor" password is indeed the correct password for the "postgres" user in your PostgreSQL database.
> 
> Incase if you don't know your password also don't worry, I will explain the steps to change your postgres password, if you know your system password
> 
> Run this command in the terminal "sudo -u postgres psql", then it will ask system password, just enter that.After that you have to run "\password postgres" and give new password.Then change the password in the URL in .env file.
> 
> This would be enough to go through. Thanks.

I don't think you read the whole problem. As I posted firstly "yarn workspace @calcom/prisma db-migrate" command successfully migrated using the same connection string which indicates the connection string in .env is fine. The problem start to occur after yarn dev. Any other idea? But thank you so much for your help.

**Comment by vinayv-456** [comment]
I am also facing the same issue. Any updates on this?

**Comment by vinayv-456** [comment]
This worked for me. Check this out  [https://stackoverflow.com/questions/64210167/unable-to-connect-to-postgres-db-due-to-the-authentication-type-10-is-not-suppor#:~:text=data%5Cpg_hba.conf-,And%20Simply%20Change%20scram%2Dsha%2D256%20under%20Column%20Method%20to%20trust.,-It%20worked%20For](url)

**Comment by TaduJR** [comment]
Which password encryption method did you use trust or md5?

**Comment by vinayv-456** [comment]
Earlier it was md5 i changed to trust

**Comment by MehulZR** [comment]
@vinayv-456 @TaduJR What version of postgresql are you using?

**Comment by MehulZR** [comment]
The error message originated from [this commit](https://github.com/calcom/cal.com/commit/b5cf4e50a953f24c4080e925a64dc623f334bd0f).
I have already spent alot of time today pin pointing the error message to this commit, will look into it what is actually causing the issue tomorrow.
