### ISSUE TITLE
[CAL-2680] Hide notes in email aswell as calendar

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12259]
We currently have the ability to "Hide notes in calendar". These notes still show up in the email for the booker.

We should edit this so that when you hide notes, it hides notes for the booker in the calendar invite and in the email.

The organiser should still receive the Notes in their email.

Open question:

* Do we also hide the notes in the booking confirmation page?

![CleanShot 2023-11-07 at 11.08.18@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e1978b00-c7e6-445a-aa27-54db02534908/ab0242e4-2d42-47c4-9325-10a790a17309?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lMTk3OGIwMC1jN2U2LTQ0NWEtYWEyNy01NGRiMDI1MzQ5MDgvYWIwMjQyZTQtMmQ0Mi00N2M0LTkzMjUtMTBhNzkwYTE3MzA5IiwiaWF0IjoxNjk5MzU4NDQyLCJleHAiOjE2OTk0NDQ4NDJ9.bVy5uDyRivNEaSWIvpCpkl7-bZByr26PiKswU0BWqS0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2680](https://linear.app/calcom/issue/CAL-2680/hide-notes-in-email-aswell-as-calendar)</sub>

**Comment by hariombalhara** [comment]
Booking Confirmation page should still show it, I think, after validating that the viewer is either organizer or assigned team member(for a team event)
