### ISSUE TITLE
[CAL-2695] bug: cal is scheduling events to wrong Google Account

### ISSUE THREAD

**Issue by HelloAlexPan** [calcom/cal.com#12257]
### Issue Summary

When users schedule an event on my calendar, the event is being scheduled to the incorrect calendar despite:

1. The correct calendar being set in `Add events to` in the event page

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/edb8f8ea-3455-470e-8eaa-1fdf6979287e/e32e36d6-c45b-4fd9-b4c2-899d943d4f3a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lZGI4ZjhlYS0zNDU1LTQ3MGUtOGVhYS0xZmRmNjk3OTI4N2UvZTMyZTM2ZDYtYzQ1Yi00ZmQ5LWI0YzItODk5ZDk0M2Q0ZjNhIiwiaWF0IjoxNjk5ODEzOTg4LCJleHAiOjE2OTk5MDAzODh9.fLNtpZi0vNuYWU4X0SUyNKMDLeyfBma6vl_MRkSdG8I)

1. The correct calendar being set in `default calendar` in global settings

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/583143e3-4fd9-4ca6-b64a-f766d364457f/059f51c4-b8e9-41d9-86e7-b98f73877a5e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ODMxNDNlMy00ZmQ5LTRjYTYtYjY0YS1mNzY2ZDM2NDQ1N2YvMDU5ZjUxYzQtYjhlOS00MWQ5LTg2ZTctYjk4ZjczODc3YTVlIiwiaWF0IjoxNjk5ODEzOTg4LCJleHAiOjE2OTk5MDAzODh9.Mf7ORAqDRHw0qsI0UUWNKZuUMn1JwAJqV-p-2FbrAwY)

### Steps to Reproduce

1. I add Calendar `A`, `B`, and `C` to my [cal.com](http://cal.com) account.
2. I set `A` as the default calendar both globally and in the event settings
3. The schedulee uses my cal link to schedule a time

### Actual Results

Calendar `B` is the event owner, creating the invite, with an invite sent to both the schedulee and Calendar `A`

### Expected Results

Calendar `A` is the event owner, with an invite sent to the schedulee

### Technical details

1. We are using the [cal.com](http://cal.com) SaaS offering, i.e., not self-hosting. If the cloud environment is up to date with the OSS source, then it would have been [v3.4.6](https://github.com/calcom/cal.com/releases/tag/v3.4.6)
2. I do not know the schedulee's browser environment. That being said, this seems like a server side issue.

### Evidence

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/66de8368-40cf-4e34-8a48-54cc5ec7f504/2d0c6b29-a925-4336-8a60-3e68f6d9c2c2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82NmRlODM2OC00MGNmLTRlMzQtOGE0OC01NGNjNWVjN2Y1MDQvMmQwYzZiMjktYTkyNS00MzM2LThhNjAtM2U2OGY2ZDljMmMyIiwiaWF0IjoxNjk5ODEzOTg4LCJleHAiOjE2OTk5MDAzODh9.Jooy9dct_CTQLx724rODJkvj_7K7hremU7MUH36GV3c)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2695](https://linear.app/calcom/issue/CAL-2695/bug-cal-is-scheduling-events-to-wrong-google-account)</sub>

**Comment by PeerRich** [comment]
can you try changing your cal.com email address inside settings and see if it goes to the correct email instead?

**Comment by HelloAlexPan** [comment]
@PeerRich could you send a screenshot of the specific field you're referring to, or the URL path?

**Comment by PeerRich** [comment]
of course, here: https://app.cal.com/settings/my-account/profile

![CleanShot 2023-11-10 at 11 48 04@2x](https://github.com/calcom/cal.com/assets/8019099/d56bc690-cffb-4758-b510-d0d82d86659b)

**Comment by HelloAlexPan** [comment]
@PeerRich my email field is showing the correct email, so no changes required

**Comment by keithwillcode** [comment]
Related to #10066?

**Comment by joeauyeung** [comment]
Thanks for reporting @HelloAlexPan. 

Can you email me at joe@cal.com and share which emails appear under those calendar events?

**Comment by HelloAlexPan** [comment]
Done. Note, I fixed this by removing all cal accounts but the primary and re-adding the other accounts. More details in the fix sent over email.
