### ISSUE TITLE
[CAL-2678] No loader on clicking install button from apps listing page.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12253]
https://www.loom.com/share/f934ebd75f0343928715860d7ec39787

<sub>[CAL-2678](https://linear.app/calcom/issue/CAL-2678/no-loader-on-clicking-install-button-from-apps-listing-page)</sub>

**Comment by Amit91848** [comment]
Hey! Can I work on this?

**Comment by romiljain5** [comment]
is this fixed or still open @hariombalhara

**Comment by TheAlchemist82** [comment]
I'm pretty sure this issue has been resolved, the loaders are visible for me.

**Comment by mjsf1234** [comment]
is the issue this open?

**Comment by Anny023** [comment]
Can I work on this? Is it still open?

**Comment by DebasishBarai** [comment]
Is this issue still open? can I work on this?

**Comment by rijuoddusual1999** [comment]
I think it is fixed in the later PRs 

![Screenshot from 2023-12-12 11-14-35](https://github.com/calcom/cal.com/assets/113231164/bee466ce-b6cc-478e-a624-1124b11f11e1)

the loader is visible to me

**Comment by s7abab** [comment]
Is this problem solved?

**Comment by Bhushankadam17** [comment]
this issue is closed.
