### ISSUE TITLE
[CAL-2682] Weird date overrides behaviour 

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#12265]
https://www.loom.com/share/df6fccf178d74d61b85ce100dfc4c66b?sid=9b30e077-de45-4397-bd1c-2a15f97b4d1d 

<sub>[CAL-2682](https://linear.app/calcom/issue/CAL-2682/weird-date-overrides-behaviour)</sub>

**Comment by kinnshuuu** [comment]
Hey team, I want to work on this bug
Can you explain what should be the expected behavior here?
