### ISSUE TITLE
BUG(App Store): google calender still has install button after 3 installs!

### ISSUE THREAD

**Issue by GauravBurande** [calcom/cal.com#12262]
### Issue Summary

I already installed the google calender in the account creation flow, but when I saw the app store page, the google calender app card was still showing the install button, I clicked on it 2 more times and now it's showing 3 installs! 😂

### Steps to Reproduce

1. go to app store
2. if google calender card shows install button click on it
3. keep clicking on it until you have a satisfied number of google calender app installs, I was satisfied at 3.

![image](https://github.com/calcom/cal.com/assets/100035026/b2f00eda-1626-40d2-bafc-ef7114bd847b)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results
Even after installing the app card shows install button
### Expected Results
The app card should only have details button, the install button should not be there!
### Evidence

![image](https://github.com/calcom/cal.com/assets/100035026/b2f00eda-1626-40d2-bafc-ef7114bd847b)

**Comment by Udit-takkar** [comment]
@GauravBurande we allow to connect multiple google calendars

**Comment by PeerRich** [comment]
we allow specific apps to be installed multiple times (most people have more than one google calendar)
