### ISSUE TITLE
[CAL-2821] Request details: redirect_uri=https://cal.com/api/auth/callback/google

### ISSUE THREAD

**Issue by bilalmirza74** [calcom/cal.com#12277]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

During sign up, I encountered an error.

Request details: redirect_uri=[https://cal.com/api/auth/callback/google](https://cal.com/api/auth/callback/google)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2fde1112-6fe5-41ad-8e1c-c168964cffce/c5b2b87a-b408-429c-91bc-fd6605542b67?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yZmRlMTExMi02ZmU1LTQxYWQtOGUxYy1jMTY4OTY0Y2ZmY2UvYzViMmI4N2EtYjQwOC00MjljLTkxYmMtZmQ2NjA1NTQyYjY3IiwiaWF0IjoxNzAyOTUwNjkzLCJleHAiOjE3MDMwMzcwOTN9.RQJLGRx--N05HHwfru-ihwvL86wYYDguBcXEUpqF5sU)

After trying again, I was able to sign in successfully.

"When I attempted to connect to Microsoft 365, I encountered an error message and have been unable to proceed since."

{"message":"No code returned"}

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cc4f12cc-c289-4bdc-ab1f-26ec140ef7c8/8ebafc21-74e3-4d0b-940f-eb42c3c9b517?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jYzRmMTJjYy1jMjg5LTRiZGMtYWIxZi0yNmVjMTQwZWY3YzgvOGViYWZjMjEtNzRlMy00ZDBiLTk0MGYtZWI0MmMzYzliNTE3IiwiaWF0IjoxNzAyOTUwNjkzLCJleHAiOjE3MDMwMzcwOTN9.JvlmGAJGn21BexGdq8M-Aqh--v0uxD_kMxF8dpStsNY)

[https://app.cal.com/api/integrations/office365video/callback?error=invalid_scope&error_description=The provided value for the input parameter 'scope' is not valid. The scope 'OnlineMeetings.ReadWrite offline_access' does not exist.&state={"returnTo":"https://app.cal.com/apps/installed"}](https://app.cal.com/api/integrations/office365video/callback?error=invalid_scope&error_description=The%20provided%20value%20for%20the%20input%20parameter%20%27scope%27%20is%20not%20valid.%20The%20scope%20%27OnlineMeetings.ReadWrite%20offline_access%27%20does%20not%20exist.&state=%7b%22returnTo%22:%22https://app.cal.com/apps/installed%22%7d)

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. [https://app.cal.com/getting-started/connected-video](https://app.cal.com/getting-started/connected-video)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* What's happening right now that is different from what is expected

### Expected Results

* This is an ideal result that the system should get after the tests are performed

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2821](https://linear.app/calcom/issue/CAL-2821/request-details-redirect-uri=httpscalcomapiauthcallbackgoogle)</sub>

**Comment by zomars** [comment]
I wasn't able to reproduce. For the microsoft case, can yo confirm you're not using a personal account? Assuming you're trying to add a Teams account. We display this warning when trying to install.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/da315e24-1627-49a7-b475-a46b55cc35bd/8427b7a4-1754-41d0-896e-55612d3c5ca8)

For Google Meet we require you to have a Google Calendar installed first. Can you confirm the error is still happening on your account?

**Comment by zomars** [comment]
Tagging @joeauyeung as he may have more context on this.

Also attaching a possible related issue. Google Meet allows you to install without a gCal connected.


https://github.com/calcom/cal.com/assets/3504472/183d722b-8440-4626-8c16-b7f84805e58c
