### ISSUE TITLE
[CAL-2685] Inline Embed Shortcode doesn't work with Wordpress plugin

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12296]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2e11c6e0-7b13-4b92-8e06-d338cef852d4/ec517b91-d1fc-4f91-b502-d90263eafcaa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yZTExYzZlMC03YjEzLTRiOTItOGUwNi1kMzM4Y2VmODUyZDQvZWM1MTdiOTEtZDFmYy00ZjkxLWI1MDItZDkwMjYzZWFmY2FhIiwiaWF0IjoxNjk5NTM1NzAzLCJleHAiOjE2OTk2MjIxMDN9.xkkgKZTCkmhZKvctnY5TzzBhuWh0-hh-qk5DmAAvxy0)

Demo -  [https://workdpress-hariom-test.000webhostapp.com/2023/11/inline-embed-cal-demo](https://workdpress-hariom-test.000webhostapp.com/2023/11/inline-embed-cal-demo)

Popup works - [https://workdpress-hariom-test.000webhostapp.com/2023/11/popup-embed-cal-demo](https://workdpress-hariom-test.000webhostapp.com/2023/11/popup-embed-cal-demo)

Happens because Wordpress is adding embed snippet at the bottom of the page.

Workaround: Directly add HTML to wordpress page.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2685](https://linear.app/calcom/issue/CAL-2685/inline-embed-doesnt-work-with-wordpress-plugin)</sub>

**Comment by milospuac** [comment]
Should we get this one moving again?
