### ISSUE TITLE
Outgoing Event Type Webhook Sends Empty Payload

### ISSUE THREAD

**Issue by kevinhoodme** [calcom/cal.com#12309]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Created new webhook inside "event type" > "webhooks".  Created custom payload template.  Webhook received includes proper "key" values but "variable" values are empty.

### Steps to Reproduce

1. Log in to cal.com dashboard
2. Click event types on sidebar menu.
3. Select event type.
4. Select webhooks.
5. Click "add new".
6. Enter "Hook Deck Connection URL" into "Subscriber URL".
7. Select Event Trigger "Booking Created"
8. Enter Custom Payload:

{
  "first_name": "{{first_name}}",
  "last_name": "{{last_name}}",
  "email": "{{email}}",
  "timezone": "{{timezone}}",
  "phone": "{{phone}}"
}

9. Click Save
10. Create Successful Booking via Event Type
11. Hook Deck Connection Response Reads:

{
"first_name": "",
"last_name": "",
"email": "",
"timezone": "",
"phone": ""
}

12. I believe this is a bug because I expected the variable values such as {{email}} to contain the guests email address.

### Actual Results

Received Custom Payload Reads:

{
"first_name": "",
"last_name": "",
"email": "",
"timezone": "",
"phone": ""
}

### Expected Results

Expected Payload Results to Read:

{
"first_name": "Guest First Name",
"last_name": "Guest Last Name",
"email": "Guest Email Address",
"timezone": "Guest Timezone",
"phone": "Guest Phone"
}

### Technical details

Browser: Chrome Version 113.0.5672.127 (Official Build) (64-bit)

### Evidence

https://www.loom.com/share/2efd20e1cb8f433a8f141679f9a39f77?sid=b218f961-f9a4-4bba-973a-22bf0d0c93a6

**Comment by harshithpabbati** [comment]
I would like to work on this, can I assign it to myself?

**Comment by kevinhoodme** [comment]
**The first time I tried this it partially worked:**

Custom payload in cal.com:

{
"first_name": "{{attendees.0.first_name}}",
"last_name": "{{attendees.0.last_name}}",
"email": "{{attendees.0.email}}",
"timezone": "{{attendees.0.timezone}}",
"phone": "{{attendees.0.phone}}"
}

**Received payload at hookdeck**

(5 items)
{
"first_name": "",
"last_name": "",
"email": "kevin@kevinhood.me",
"timezone": "",
"phone": ""
}

**Next attempt, custom payload in cal.com**

{
"full_name": "{{attendees.0.name}}",
"email": "{{attendees.0.email}}",
}

**Received payload at hookdeck.com**
(1 item)
{
"{ "full_name": "Kevin Hood", "email": "kevin@kevinhood.me", }": ""
}

**Endpoint response**
{
"success": false,
"data": {
"message": "Validation failed.",
"errors": {
"email": {
"required": "The email field is required."
}
},
"type": "email_validation_failed"
}
}

**Notes**

I've tried copy/pasting the custom payload template from cal.com docs and editing it.

I've hand typing the custom payload from scratch.

I've tried to deleting the webhook and re-creating it.

For whatever reason, the payload sends as a single, item in a single line, with incorrect formatting causing the webhook to fail.

**Comment by kevinhoodme** [comment]
This worked.

However I did run into a problem trouble shooting this.

{
"name": "{{attendees.0.name}}",
"email": "{{attendees.0.email}}",
"timezone": "{{attendees.0.timezone}}"
}

I had to omit the final comma in the payload to get it to work properly.

Thanks for your help.
