### ISSUE TITLE
[CAL-2690] Error when trying to edit my email

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12314]
Steps to reproduce

* I'm a user in an org
* I'm trying to update my email and see the following error

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2690](https://linear.app/calcom/issue/CAL-2690/error-when-trying-to-edit-my-email)</sub>

**Comment by DarkWolff71** [comment]
Does this happen to a specific org or is it always observed? Can you please mention the exact steps to reproduce the issue since I'm not facing/able to reproduce the issue in the dev environment? @ciaranha @PeerRich

**Comment by ciaranha** [comment]
Issue resolved.
