### ISSUE TITLE
Bug: issue deploying v3.4.8 - yarn.lock file.  `deel` missing

### ISSUE THREAD

**Issue by Shpadoinkle** [calcom/cal.com#12310]
### Issue Summary

issue deploying latest calcom v3.4.8

AWS ECS error logs:
Error: 
Internal Error: @calcom/deel@workspace:packages/app-store/deel: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

### Steps to Reproduce
deploying latest version.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence
- ECS logs while deploying latest version
- ![image](https://github.com/calcom/cal.com/assets/11312962/0b1c8a62-7b46-45fd-bcb3-6acff23ca3eb)

**Comment by PeerRich** [comment]
`main` needs a new yarn.lock

can you run "yarn" in root?
