### ISSUE TITLE
[CAL-2691] Time slot interval not being saved 

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#12315]
trying to update that event's Time-slot interval value to 30 minutes but it is not saving correctly and not giving me an error. It is just silently not saving the value.

Here is a video below: 

https://app.birdeatsbug.com/m-LT4HCX1tvFgg7OV94MaAPgfGZdPlXfehiJQzfAbX24

<sub>[CAL-2691](https://linear.app/calcom/issue/CAL-2691/time-slot-interval-not-being-saved)</sub>

**Comment by VenkateshSircilla123** [comment]
its working for me
