### ISSUE TITLE
[CAL-2694] Radicale and e is undefined

### ISSUE THREAD

**Issue by jtmusselman** [calcom/cal.com#12329]
### Issue Summary

When attempting to add my Radicale calendar to the Caldav app, I receive an infinite wait with only a small message that says e is undefined.

### Steps to Reproduce

1. Set up Radicale and use it.
2. Try to use the Caldav app with Radicale
3. See error and wait infinitely for the calendar to be added

### Actual Results

Infinite load times, no discernable error message or setup instructions

### Expected Results

The calendars should be added

### Technical details

* Librewolf 119.0-7
* Radicale v3.1.8
* [Cal.com](http://Cal.com)

### Evidence

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c3c60990-d85c-4b44-b5de-54c9b81cbab6/68ae9d27-4d32-412e-a868-14a80722ba7b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jM2M2MDk5MC1kODVjLTRiNDQtYjVkZS01NGM5YjgxY2JhYjYvNjhhZTlkMjctNGQzMi00MTJlLWE4NjgtMTRhODA3MjJiYTdiIiwiaWF0IjoxNjk5ODExMDk3LCJleHAiOjE2OTk4OTc0OTd9.Cqrm-h59-2f6-yZ4iMoDVYQ-xPX_AKuMJycR78t_3SY)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2694](https://linear.app/calcom/issue/CAL-2694/[bug]-radicale-and-e-is-undefined)</sub>

**Comment by jtmusselman** [comment]
**More information!**

On Microsoft Edge version 119.0.2151.58  

I get the error:

`Cannot destructure property 'auth' of 'e' as it is undefined.`

**Comment by tessaSAC** [comment]
Adding here that I also see the `r` error with a different calendar provider
