### ISSUE TITLE
[CAL-2138] Ability to disband organizations

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12328]
Disbanding organization without teams breaks so we will hide this for now.

Look to prioritize this in 3.2 or 3.3. Manually deal with for now when an organization needs to disband.

Created via Threads. See full discussion: [https://threads.com/34505385110](https://threads.com/34505385110)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2138](https://linear.app/calcom/issue/CAL-2138/ability-to-disband-organizations)</sub>

**Comment by hariombalhara** [comment]
For visibiity, [this PR]( https://github.com/calcom/cal.com/pull/12424) implements the organization deletion by instance admin.
