### ISSUE TITLE
[CAL-1714] "null" teams

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12330]
more teams are reporting nullified team slugs

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1714](https://linear.app/calcom/issue/CAL-1714/null-teams)</sub>

**Comment by PeerRich** [comment]
The issue is that when a team payment fails, the slug gets nullified. But when the payment is fixed. It doesn't get denullified. We should fix the latter webhook.

**Comment by zomars** [comment]
@keithwillcode we can cancel this one as team are now be paid from creation.

**Comment by keithwillcode** [comment]
even better!
