### ISSUE TITLE
[CAL-2697] A team with slug `designer` is 404 for an org

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12334]
In an org **/designer** path gives 404.

e.g. app.cal.local:3000/**d**esigner is 404 always

Note that app.cal.local:3000/team/designer still works

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2697](https://linear.app/calcom/issue/CAL-2697/a-team-with-slug-designer-is-404-for-an-org)</sub>

**Comment by SomayChauhan** [comment]
something that might be related or helpful
#12165
