### ISSUE TITLE
[CAL-2707] [CAL-2706] Rescheduling with booking limits

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#12348]
We want to ignore the original booking when rescheduling and booking limits are active.

So if there is a limit of 1 a day, then the user should still be able to reschedule on the same day as the original booking

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2706](https://linear.app/calcom/issue/CAL-2706/rescheduling-with-booking-limits)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2706](https://linear.app/calcom/issue/CAL-2706/rescheduling-with-booking-limits)</sub>

**Comment by queen-x-vee** [comment]
can i work on this

**Comment by CarinaWolli** [comment]
@queen-x-vee Yes, for sure! Make sure to tag this issue when opening a PR :)

**Comment by saurav0705** [comment]
@CarinaWolli I am unable to open the linear tickets attached above can you please give me the workspace access or elaborate the issue

**Comment by CarinaWolli** [comment]
> @CarinaWolli I am unable to open the linear tickets attached above can you please give me the workspace access or elaborate the issue

@saurav0705 The linear ticket is a copy of this ticket, it doesn't include any more information

**Comment by CarinaWolli** [comment]
> So if there is a limit of 1 a day, then the user should still be able to reschedule on the same day as the original booking

Tested this and this is already fixed
