### ISSUE TITLE
[CAL-2708] Google Meet link not saved in metadata

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#12350]
Google Meet link is not saved in booking metadata (videoCallUrl)

Steps to reproduce:

* Install Google Meet
* Create event type with Google Meet as location
* Book event type
* Bug: videoCallUrl in booking metadata is empty

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2708](https://linear.app/calcom/issue/CAL-2708/google-meet-link-not-saved-in-metadata)</sub>

**Comment by Asifdecoder** [comment]
stepstoreproducetheerrorplease
