### ISSUE TITLE
[CAL-2710] Join Team Link not Working

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12356]
A customer invited a user via a join a team link and they were getting a error when trying to create a new account. They eventually did google SSO and that worked. They should be able to creat the account if they want to. This is a repeat bug from the past cc @sgriff96-brydon 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2710](https://linear.app/calcom/issue/CAL-2710/join-team-link-not-working)</sub>

**Comment by keithwillcode** [comment]
This was fixed and released today.
