### ISSUE TITLE
[CAL-2727] opening invite team link in email throws error on signup page

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#12359]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

on inviting a pending member to a sub team in an organization, an email is sent out and opening that email gives error on the signup page

### Steps to Reproduce

1. add a new member to an organization (sends one email ignore that)
2. add that pending member to any one of sub-teams
3. another email is sent out, open it and click on create your account 

### Evidence

[Screencast from 14-11-23 01:20:21 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/0ca3ec96-6f83-45ad-9e69-a8b72e37df1b)

<sub>[CAL-2727](https://linear.app/calcom/issue/CAL-2727/opening-invite-team-link-in-email-throws-error-on-signup-page)</sub>

**Comment by PeerRich** [comment]
i believe this has been fixed. if not, I added urgent priority
