### ISSUE TITLE
[CAL-2713] Selected Calendars - Inconsistencies Between Installed & Settings Pages

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#12367]
These inconsistencies are affecting what users believe which calendars are being selected to check for availabilities. The settings page had it's own logic and components compared to `<CalendarListContainer />` that was being used in the installed apps page and onboarding.

Refactor to have the same components & logic between these pages.
[https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=7684-26931&mode=design](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=7684-26931&mode=design)

[https://threads.com/thread/34546541751/34546675985?s=qP7XpM1vHJBE9RNuBdp4Hn](https://threads.com/thread/34546541751/34546675985?s=qP7XpM1vHJBE9RNuBdp4Hn)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2713](https://linear.app/calcom/issue/CAL-2713/selected-calendars-inconsistencies-between-installed-and-settings)</sub>

**Comment by Udit-takkar** [comment]
Fixed here https://github.com/calcom/cal.com/pull/12388
