### ISSUE TITLE
Unhandled organisation user

### ISSUE THREAD

**Issue by sanand404** [calcom/cal.com#12365]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If organisation do not have any users. If user navigates to organisation profile page breaks.

### Steps to Reproduce

1. Add a Team in team table 
2. Login to calcom
3. Navigate to organisation profile page

### Technical details
<img width="1477" alt="image" src="https://github.com/calcom/cal.com/assets/23119685/e99c6f0c-1bd4-47a9-84d2-e0444b4a7248">
### Evidence
[calcom-bug.webm](https://github.com/calcom/cal.com/assets/23119685/986d3db7-5874-4b22-8c26-38e0771f46f6)

**Comment by asadath1395** [comment]
This is working fine now, probably fixed by https://github.com/calcom/cal.com/pull/12539. Loom video showing the same https://www.loom.com/share/207b0748c1fc4ea08c2c1ac8bbe61340?sid=9e5ff1bf-a757-441b-9dbb-8b229e4f0c3e. We can close this i believe

cc @PeerRich @keithwillcode
