### ISSUE TITLE
Basecamp application still not available

### ISSUE THREAD

**Issue by flacombe** [calcom/cal.com#12372]
### Issue Summary

Basecamp integration was merged in #9195 and announced in Cal.com 3.3 but is still not available in app store.

### Steps to Reproduce

1. Go to the Cal.Com app store
2. Look for Basecamp application
3. Notice its absence

It sounds like a bug since applications introduced in Cal.com 3.4 are actually available.

### Actual Results

Basecamp application is not available in app store.

### Expected Results

Basecamp application should be available in app store.

**Comment by PeerRich** [comment]
ha! a variable was missing. thanks!  wokring now

![CleanShot 2023-11-16 at 21 48 56@2x](https://github.com/calcom/cal.com/assets/8019099/c38fea6e-8b1f-438d-83b7-89a5c8436d97)

**Comment by flacombe** [comment]
Thank you!
