### ISSUE TITLE
Lack of contrast in the venue options on the booking page (phone icon)

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#12379]
In the venue options on the booking page, the phone number icon lacks the necessary contrast - both in light and dark mode.

<img width="424" alt="Bildschirmfoto 2023-11-16 um 00 41 06" src="https://github.com/calcom/cal.com/assets/126205884/0de77ee1-95d5-40c5-bad5-04d498c54c50">
<img width="516" alt="Bildschirmfoto 2023-11-16 um 00 40 45" src="https://github.com/calcom/cal.com/assets/126205884/c9cef8d7-3190-4f81-b88a-fbb8c8bef0be">

**Comment by Sahil-B07** [comment]
steps to reproduce ?

**Comment by RainerZufall9393** [comment]
@Sahil-B07 



https://github.com/calcom/cal.com/assets/126205884/89b26a6e-78d0-4a79-91f3-0365109179f2
