### ISSUE TITLE
[CAL-2728] Issue with webhook after meeting ends

### ISSUE THREAD

**Issue by buzzard10** [calcom/cal.com#12378]
### Issue Summary
I don't know why, but webhook which should be sent after meeting ends, but i don't receive it? 

### Steps to Reproduce

1. Create webhook with proper option
2. Create new meeting with ms teams type event
3. Wait until finish
4. check whether 

### Actual Results
I don't receive any webhook after meeting end 

<sub>[CAL-2728](https://linear.app/calcom/issue/CAL-2728/issue-with-webhook-after-meeting-ends)</sub>

**Comment by xta** [comment]
Same, thanks for filing an issue! https://github.com/calcom/cal.com/issues/12370

**Comment by buzzard10** [comment]
@PeerRich do you have any updates regarding this issue? :) 
Thanks for your work!
