### ISSUE TITLE
[CAL-2714] Session booking event goes through the webhook even though there is a credit card payment failure

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12371]
This is inflating the stats customers are seeing because it is counting that as a booked session even though it failed. 

This has happened twice and in both cases the person rebooked and must have used a different credit card. 

Is it possible to not trigger the booking event through the webhook unless the credit card is properly processed and the payment is made?

cc @Jaibles this is for Skillshare 🙏🏽

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2714](https://linear.app/calcom/issue/CAL-2714/session-booking-event-goes-through-the-webhook-even-though-there-is-a)</sub>

**Comment by Krriishhhhhh** [comment]
I am doing it, but i need some context for this as cal.com is new to me.....help would be appreciated

**Comment by shirazdole** [comment]
Did we ever get this resolved or still persists? Skillshare hasn't mentioned it since then
