### ISSUE TITLE
BAA page does not exist at listed path

### ISSUE THREAD

**Issue by xta** [calcom/cal.com#12381]
on this page (https://cal.com/enterprise), it says

> How do I get a signed BAA?

> Yes, on cal.com/BAA

At cal.com/BAA, it is 404 / This page does not exist.

<img width="1512" alt="404" src="https://github.com/calcom/cal.com/assets/465358/235aa80f-b381-44e5-9b3a-89e850b03550">

**Comment by PeerRich** [comment]
try again!
