### ISSUE TITLE
[CAL-2720] e2e tests for team invites

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#12386]
Much like @hariombalhara did for orgs in [https://github.com/calcom/cal.com/pull/12241](https://github.com/calcom/cal.com/pull/12241) 

Implement e2e tests for team invites 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2720](https://linear.app/calcom/issue/CAL-2720/e2e-tests-for-team-invites)</sub>

**Comment by Amit91848** [comment]
Is this open for anyone?

**Comment by sean-brydon** [comment]
> Is this open for anyone?

Feel free to give this a shot! We dont normally assign issues to none-core members so just submit a PR and tag me. I'll take a look
