### ISSUE TITLE
Settings option to turn the "Overlay my calendar" feature on or off

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#12398]
It would be great if we could get the option to turn the "Overlay my calendar" feature on or off in the Event Settings and/or Global Settings.

<img width="726" alt="Bildschirmfoto 2023-11-17 um 06 17 36" src="https://github.com/calcom/cal.com/assets/126205884/17bced0d-4f5c-4d4f-814a-12d24cc5e964">

**Comment by PeerRich** [comment]
why?

**Comment by PeerRich** [comment]
i think this is useful for everyone and I imagine only a very small handful of people will deactivate it. I don't understand why you would want to remove it

**Comment by mlazowik** [comment]
Overlaying requires logging in. We self host, and have sign up disabled, so the feature is not usable for anyone outside our org, leads into a dead end

**Comment by xboxhaxorz** [comment]
Basically it allows any random individual to create an account and get a booking link with your domain, so they could pretend to be in your org

**Comment by herzkerl** [comment]
@PeerRich +1, same reason as @mlazowik stated.

**Comment by tim-the-arcane** [comment]
Same here. Please reconsider this issue. It's just misleading and not useful. All that you'd have to do is add a boolean setting and conditionally rendering the button. I can create a PR if that would help :)

**Comment by amirasyraf** [comment]
> i think this is useful for everyone and I imagine only a very small handful of people will deactivate it. I don't understand why you would want to remove it

Why is this closed? Seems like a very basic ask.

**Comment by Lars-** [comment]
Ask any AI to create a sub_filter in nginx that hides `[data-testid="overlay-calendar-switch"]`. Only works if you are using nginx as reverse proxy of course. 

It is very hacky, but it works...

**Comment by gulito** [comment]
I think it would be useful, as we do not want our customers to register or create an account but only book meetings with us. We also have registration disabled, therefore it will cause issues, when customers are stuck there. Furthermore we have seperated customer-portal and backend and our employees only sign in via backend.

**Comment by Nexulo** [comment]
@PeerRich how can you not understand the issue? As the author already said, if we have "sign up" disabled, there is a “dead” link/option for visitors that makes no sense.

Since @tim-the-arcane even suggested the solution/PR, this should be taken up again as an open issue.

**Comment by CobySim01** [comment]
This would be very useful. My average user is quite old, and I just want them to book a meeting, I don't want to distract them with confusing features.
