### ISSUE TITLE
Invalid Australian phone numbers beginning +61493 or +610493

### ISSUE THREAD

**Issue by Shpadoinkle** [calcom/cal.com#12394]
### Issue Summary
- Phone validation issues with phone numbers in Australia starting with +61493 or +610493.    
  - A few work, most common as well with an 8 after the 3 as well. ie +61493800000
- these are valid phone numbers in Australia and prevents bookings

### Steps to Reproduce
Enter Australian phone number.  for example +61493812345

### Actual Results
- phone number is labelled as invalid, so cannot complete booking.

### Expected Results
- phone number should be seen as valid, and booking should be able to be completed

### Technical details
- calcom version 3.4.7

### Evidence
![Screenshot 2023-11-17 at 11 42 26 am](https://github.com/calcom/cal.com/assets/11312962/7147d0a0-d111-4f0a-a537-9570ea5ef9dd)
![Screenshot 2023-11-17 at 11 42 43 am](https://github.com/calcom/cal.com/assets/11312962/3691a3f9-778f-4c66-99f3-66ef14a5f720)

**Comment by ezhil56x** [comment]
@Shpadoinkle @mrkirthi-24

The current implementation to verify a valid phone number works perfectly 🚀

| 1 | 2 |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/11312962/283644155-7147d0a0-d111-4f0a-a537-9570ea5ef9dd.png) | ![image](https://user-images.githubusercontent.com/11312962/283644162-3691a3f9-778f-4c66-99f3-66ef14a5f720.png) |

1 is invalid because it has 10 digits after the county code
2 is invalid because it falls outside the range of valid mobile numbers

### Found some info about Australian numbers
1. Australian numbers start with country code `+61` or `0` followed by 9 digits
2. Digital Mobile services (3G, 4G, 5G and GSM) only starts with 4
3. These are the mobile number ranges that are valid 👇🏻
![image](https://github.com/calcom/cal.com/assets/103899034/888661e4-09f9-4cad-b22f-f30bc4f33b3c)

**Reference**
[wikipedia/Telephone_numbers_in_Australia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia)
[australia.gov.au/telephone-country-and-area-codes](https://www.australia.gov.au/telephone-country-and-area-codes)

---
So I think this issue can be closed ✨

**Comment by thisshri** [comment]
Should we not update the error message so the error makes more sense? 🤔

**Comment by jkcs** [comment]
@PeerRich I tried validating an Australian phone number on the [Microsoft registration page](https://signup.live.com/signup) and the result I obtained was that we do not need to update the phone number verification rules.

**Comment by Shpadoinkle** [comment]
@ezhil56x the phone number I provided on this ticket was an example phone number and not the real one that was used when the error was detected. I did not share the actual failing number to protect customer privacy. 

I can guarantee you that there are many Australians with phone numbers starting with +61493.

**Comment by Shpadoinkle** [comment]
@jkcs Microsoft most likely aren't using the same inputs or phone validation packages

**Comment by Shpadoinkle** [comment]
Might be worth testing if updating the libphonenumber-js package will solve the issue.

**Comment by jkcs** [comment]
@Shpadoinkle You are right, I found the key code snippet.

https://github.com/google/libphonenumber/blob/c310e78a4357b0c2e19decef7ab872f41d6d704b/release_notes.txt#L43-L46

**Comment by ologbonowiwi** [comment]
Hey @Shpadoinkle, the library used here is [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js), they already have [an issue](https://gitlab.com/catamphetamine/libphonenumber-js/-/issues/127) opened on their repo, but according to them this should be reported directly to Google's [libphonenumber](https://github.com/google/libphonenumber).
The same person that opened [the issue](https://gitlab.com/catamphetamine/libphonenumber-js/-/issues/127) on [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) also opened one for [libphonenumber](https://github.com/google/libphonenumber) [directly on Google's issue tracker](https://issuetracker.google.com/issues/307583364?pli=1). This was the last comment there:
> We update the Australian numbers directly based on [ACMA (telephone authority)](https://www.thenumberingsystem.com.au/#!/smartnumbers-login) as they are more accurate and updated. They last updated on 24/10/2023 and as per it, none of these prefixes i.e 239, 241, 252 and 254 are valid.
> 
> If you still think they are then please share any working numbers or evidence you may have. See our guidelines: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence.

You should read their "[Providing Authoritative Evidence](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#provide-authoritative-evidence)" on their [CONTRIBUTING.md](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md), and provide some evidence that these are valid numbers. In case you're asking how to do so:
> Ideally, change requests for ranges should be accompanied by authoritative evidence such as official government or public carrier documents.
>
> If the evidence is publicly available online, please provide the link.
>
> If the evidence is not publicly available online, make sure that you have the rights to share this with us, and confirm this by reading and signing the appropriate Contributor License Agreement (CLA). Then we can accept this on GitHub, or we can invite you to a private Google Group archive if you prefer not to share on GitHub.

IMO, we shouldn't handle these kinds of edge cases manually, as they open up breaches to invalid numbers.
Another option is to change the library that we're using to validate numbers. If you know anything that works with the Australian numbers @Shpadoinkle, please share it with us, and I can implement it here on our repo.

**Comment by ologbonowiwi** [comment]
Oh, I did not saw that PR! @algora-pbc guys, can you link #12519 to this issue, please? Thanks!

**Comment by algora-pbc** [comment]
@ologbonowiwi already linked! :pray:
