### ISSUE TITLE
[CAL-2731] Can't get the hosts in the response from the API for team event types

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#12402]
@alishaz-polymath and i were able to reproduce this 

![Screenshot 2023-11-17 at 09.54.46.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/305b14ec-eab6-4a40-aeaa-505d5eed6db6/3478363b-d021-4a39-8a33-3cb0328e89a0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMDViMTRlYy1lYWI2LTRhNDAtYWVhYS01MDVkNWVlZDZkYjYvMzQ3ODM2M2ItZDAyMS00YTM5LThhMzMtM2NiMDMyOGU4OWEwIiwiaWF0IjoxNzAwMjExMzI1LCJleHAiOjE3MDAyOTc3MjV9.7DZAQHaXqVm0SQP7u07l_WzZTHzXCQefj1gZFsvBVRE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2731](https://linear.app/calcom/issue/CAL-2731/cant-get-the-hosts-in-the-response-from-the-api-for-team-event-types)</sub>

**Comment by kaulshashank** [comment]
Hi, can someone tell me if the fix for this is simply adding

```
include: {
      hosts: { select: { userId: true, isFixed: true } },
}
```

over here? https://github.com/calcom/cal.com/blob/f2c39fc7861b1f4f32ac07f572d7c9b135b6737e/apps/api/pages/api/teams/%5BteamId%5D/event-types/_get.ts#L48-L59


I'd be more than happy to PR this, it's high priority for an integration my team is building.

**Comment by alishaz-polymath** [comment]
> Hi, can someone tell me if the fix for this is simply adding
> 
> ```
> include: {
>       hosts: { select: { userId: true, isFixed: true } },
> }
> ```
> 
> over here?
> 
> https://github.com/calcom/cal.com/blob/f2c39fc7861b1f4f32ac07f572d7c9b135b6737e/apps/api/pages/api/teams/%5BteamId%5D/event-types/_get.ts#L48-L59
> 
> I'd be more than happy to PR this, it's high priority for an integration my team is building.
> 
> If that's correct then I can go ahead and replicate the include that's present here:
> 
> https://github.com/calcom/cal.com/blob/f2c39fc7861b1f4f32ac07f572d7c9b135b6737e/apps/api/pages/api/event-types/_get.ts#L44-L51

Yes, that should solve it. You can always test it locally and confirm that the fix you're raising the PR for actually works 🙏 
And yes, please replicate the include from `api/event-types/_get` for consistency 🙌

**Comment by kaulshashank** [comment]
@alishaz-polymath just posting here in case it was missed: https://github.com/calcom/cal.com/pull/12459
