### ISSUE TITLE
[CAL-2735] Issue with Email Notifications

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12407]
https://www.loom.com/share/268a3400267340349da2e175fea96194?sid=ba761580-c88a-4957-91d4-2bcedd0d0d79

<sub>[CAL-2735](https://linear.app/calcom/issue/CAL-2735/issue-with-email-notifications)</sub>

**Comment by adwait-godbole** [comment]
can I work on this issue ?

**Comment by Udit-takkar** [comment]
can't reproduce the second issue 

<img width="624" alt="Screenshot 2023-11-29 at 8 15 49 PM" src="https://github.com/calcom/cal.com/assets/53316345/d01c2aec-d080-4a6a-9253-8b0b9b9edad8">

**Comment by Udit-takkar** [comment]
IIRC @CarinaWolli made a PR some time ago fixing the first issue which was cancelling workflow emails when event has been cancelled

**Comment by CarinaWolli** [comment]
The first issue with still receiving workflow reminders for already canceled bookings should be fixed now, I just tested it and I didn't receive the email

**Comment by goforbg** [comment]
I'm still able to reproduce AM/PM issues & the wrong email notifications

**Comment by goforbg** [comment]
Also, for more context on the bug @CarinaWolli - my concern is on rescheduled meetings. 

Thanks all <3

**Comment by CarinaWolli** [comment]
> my concern is on rescheduled meetings.

@goforbg so reminders are still sent out for the old meeting when it was already rescheduled?

**Comment by CarinaWolli** [comment]
I can't reproduce any of the mentioned issues also not the AM/PM issue. To the AM/PM issue: You can set your own date format for workflow variables like that {EVENT_DATE_ddd, MMM D, YYYY HH:mm}

Will close this issue for now, if you are still having issues please provide more information then we can reopen it 🙏
