### ISSUE TITLE
[CAL-2904] Request to add 2 Fields to Webhook Payloads

### ISSUE THREAD

**Issue by henrym9345** [calcom/cal.com#12415]
### Is your proposal related to a problem?

I'm using the webhooks to trigger appointment reminders (internal and external) from our marketing automation tool rather than use built in reminders. 

Problem 1: I want to include cancel and reschedule links in these messages which require the url slug, which is not present in the webhook. The current workaround is to maintain a collection that contains the url slug and event type ID. This is called upon in the messaging workflow and a slug is obtained that matches the event type ID in the webhook. This is suboptimal though because this collection must be maintained as new events are added, slugs can be somewhat easily changed from cal.com and it just adds additional steps.

Problem 2:Timestamps for the appointments must be in the correct timezone on all messages. Since the payload only provides UTC time, a conversion must be performed[ using Liquid tags](https://customer.io/docs/journeys/liquid-tag-list/#timezone). This requires a UTC offset (ie -7), so the timezone string (ie America/Los Angeles) must be matched to provide this. This is done with a similar method as described in Problem 1. To make matters more complicated our local timezone of America/Phoenix does not observe daylight savings, so the offset will switch between -7 and -8. This adds the need for additional logic to check the current date before performing the timezone conversion. 

### Describe the solution you'd like
Solution for Problem 1: Add a field for url slug to the webhook payload

Solution for Problem 2: 
Option 1: Add the attendee UTC offset (ie -7) as a field, rather than the string of the timezone. 
Option 2: Add a timestamp field where the timestamp is already matches the timezone setting of the appointment.

(Describe your proposed solution here.)

### Describe alternatives you've considered

Possible alternative for Problem 1: Use url parameters+ a hidden field to pass through the slug. Not particularly stable though.

### Additional context

NA

### Requirement/Document

NA

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-2904](https://linear.app/calcom/issue/CAL-2904/request-to-add-2-fields-to-webhook-payloads)</sub>

**Comment by PeerRich** [comment]
i think this is reasonable. looking for people to help 🙏

**Comment by TwistingTwists** [comment]
Would like to take this up. Is there a timeline for this ?

**Comment by pawar1231** [comment]
./bounty

**Comment by guptadeepak8** [comment]
./attempt #12415

**Comment by henrym9345** [comment]
It looks like the slug is now showing in a field called "type", I think I saw someone working on that in a different issue, but can't find that now.

**Comment by mallela32** [comment]
So is the issue is resolved form their PR or i need to work on this to get the pr closed would you please clarify?

**Comment by alishaz-polymath** [comment]
@henrym9345 Webhooks payload contains "type" field which is essentially the event-type slug, as you mention, and it has been there for a while. We do not have a field for the offset yet though.

**Comment by henrym9345** [comment]
@alishaz-polymath Yes that field has been there for a while but I think it was updated recently. When I wrote this issue the value would have spaces in it like this:

![image](https://github.com/calcom/cal.com/assets/151242123/243d732e-cd6c-4138-9bcb-ae611e491992)

But now it is dash separated and matches the slug, so it will be usable. Still would like the offset field though.

**Comment by alishaz-polymath** [comment]
Yes, the bounty is still open for that, so hopefully we should have it in soon enough 🙏

**Comment by mallela32** [comment]
okay I will make changes and just push only the offset field part, thanks for clarification

**Comment by jkcs** [comment]
Can I be assigned to this if no one else is assigned?
/attempt #12415
