### ISSUE TITLE
Add a functionality to remove filters in the booking section

### ISSUE THREAD

**Issue by DikshaMakkar** [calcom/cal.com#12427]
### Is your proposal related to a problem?

This is not related to any existing problem, its just a suggestion!

I noticed that we are able to add filters like people and event type for booking but there is no option to remove these filters.
Adding this feature to remove filter might improve user experience on cal.com.

![image](https://github.com/calcom/cal.com/assets/62770475/e26f19e7-9d85-4764-9c73-90b4c4986740)

### Describe the solution you'd like

We can have a option like: **clear all filters** or a **X** beside individual filters to remove that specific filter.

### Describe alternatives you've considered

These filters can be removed by refreshing the page but I believe its not a good idea to refresh page each time you want to remove filter and there should be a handy option to add and remove filters.

Thank you!

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by CodeWithInferno** [comment]
its my first contribution and im working on it

**Comment by itzabhinavarya** [comment]
@PeerRich Assign this issue to me.
