### ISSUE TITLE
[Cal Video] Asking about Stop/store recording when leave the call without stop recording

### ISSUE THREAD

**Issue by hoangbits** [calcom/cal.com#12422]
### Is your proposal related to a problem?

Hi Guys, 
We are using https://cal.com/apps/daily-video with self-host version of call.com

I have tried to start recording the meeting and then leaving it and noticed We could not receive any webhook related to event RECORDING_READY once the meeting reached its end time.

As I checked on Daily.co I see they do support `cloud` recording type.

My questions are:
1. Are you guys using `cloud` recoding type for Cal Video?
2. Does the recording automatically stop when the meeting's end time is reached?

We can not get the RECORDING_READY event if we don't click on stop recording.

### Describe the solution you'd like

1. Using cloud recording for cal.com as default?
2. Stop recording once the meeting's end time is reached.
3. Also Emit RECORDING_READY webhook event for that video that was generated by (2)

### Describe alternatives you've considered

The most important thing We would like to happen is: 2. Stop recording once the meeting's end time is reached.
It's similar to a Zoom meeting. Users don't have to remember to click on stop the recording before stopping the call.

### Requirement/Document

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by Udit-takkar** [comment]
1) yes we are using `cloud ` recoding type for Cal Video

2) No the recording doesn't stop when meeting end time is reached. You can click on stop recording to stop it.

I am working on adding daily webhooks https://github.com/calcom/cal.com/pull/12273 now so whenever your recording will be ready to download you would receive email and RECORDING_READY webhook would be triggered even if you are left the call without clicking stop recording.


Although The best practise is to click on 'Stop Recording' and wait for few seconds before leaving the call.

**Comment by hoangbits** [comment]
@Udit-takkar Where did you call "RECORDING_READY webhook would be triggered" in source code?
does  RECORDING_READY get triggered without user click stop recording now?

**Comment by Udit-takkar** [comment]
@hoangbits check in triggerWebhook function. when user stops recording daily video would trigger this url /api/recorded-daily-video

**Comment by hoangbits** [comment]
> @hoangbits check in triggerWebhook function. when user stops recording daily video would trigger this url /api/recorded-daily-video
> 
> 

May I know what happen if user forget to click stop recording?

**Comment by Udit-takkar** [comment]
@hoangbits most probably it still does trigger the api endpoint whenever the recording is ready to be downloaded but it is recommended to click on stop recording to ensure it does.
