### ISSUE TITLE
[CAL-2746] Bad availability result with multiple Google Calendars

### ISSUE THREAD

**Issue by kleinpetr** [calcom/cal.com#12438]
### Issue Summary

When I connect my Google Calendar when I am subscribed to multiple other calendars (within Google Workspace) the availability is calculated from the disabled ones as well.

### Steps to Reproduce

1. Connect Google Calendar with multiple calendars
2. keep disabled one of them
3. add full day event to the disabled calendar
4. check the availability

Not sure, but first time I've been connecting the Google I realized a bug within constraint over Prisma. But then I removed all connections and installed the App from scratch.

Also when I change the type from Busy to Free, the slot is released.

### Actual Results

* I cannot disable specific calendars. they are all synced to my availability

### Expected Results

* When I disable any calendar I would expect to be not synced and used for my availability calculation

### Evidence

* I've been testing to remove and recreate the connection multiple times. Also moving the events to another disabled calendar, but it's still there.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/375f0ba4-f860-40f0-af0e-7aba7aaf8360/c7125d7e-776b-41e9-80de-37061245933f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zNzVmMGJhNC1mODYwLTQwZjAtYWYwZS03YWJhN2FhZjgzNjAvYzcxMjVkN2UtNzc2Yi00MWU5LTgwZGUtMzcwNjEyNDU5MzNmIiwiaWF0IjoxNzAwNjA4ODQyLCJleHAiOjE3MDA2OTUyNDJ9.Egk0NDJhefskkJbGtiuO-PVXPZWlhJWOp8DZLpAFjoU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2746](https://linear.app/calcom/issue/CAL-2746/bad-availability-result-with-multiple-google-calendars)</sub>

**Comment by emrysal** [comment]
Hey @kleinpetr is this still happening for you, I am so far unable to reproduce this on local.
