### ISSUE TITLE
[CAL-2738] If event owner reschedules, email seems not to go out

### ISSUE THREAD

**Issue by jobenjada** [calcom/cal.com#12440]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I as the owner have rescheduled a few events recently and it happened 4, 5 times that the other attendee was not informed accordingly (neither got email nor reschedule request in their calendar).

Didnt validate just had people reaching out asking where I was :)

<sub>[CAL-2738](https://linear.app/calcom/issue/CAL-2738/if-event-owner-reschedules-email-seems-not-to-go-out)</sub>

**Comment by milospuac** [comment]
Hi Johannes

We will investigate, thanks for reporting this

**Comment by keithwillcode** [comment]
@milospuac Any other reports of this recently?

**Comment by emrysal** [comment]
@jobenjada Hey man! Had a couple of run-throughs but it looks like this no longer happens 😎
