### ISSUE TITLE
[CAL-2747] Missing dependency node-mocks-http

### ISSUE THREAD

**Issue by krumware** [calcom/cal.com#12446]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When building from scratch, it appears that there is a missing dependency in the yarn/npm lockfile.

```
#16 206.7 @calcom/web:build: ./test/utils/bookingScenario/createMockNextJsRequest.ts:1:29
#16 206.7 @calcom/web:build: Type error: Cannot find module 'node-mocks-http' or its corresponding type declarations.
#16 206.7 @calcom/web:build: 
#16 206.7 @calcom/web:build: > 1 | import { createMocks } from "node-mocks-http";
#16 206.7 @calcom/web:build:     |                             ^
#16 206.7 @calcom/web:build:   2 | 
#16 206.7 @calcom/web:build:   3 | import type {
#16 206.7 @calcom/web:build:   4 |   CustomNextApiRequest,
```

### Steps to Reproduce

1. Build the docker image

### Actual Results

Image will not build

### Expected Results

Image should build

### Technical details

n/a

### Evidence

Build log:
https://github.com/calcom/docker/actions/runs/6886177759/job/18738607721

<sub>[CAL-2747](https://linear.app/calcom/issue/CAL-2747/missing-dependency-node-mocks-http)</sub>

**Comment by GarvAgarwal26** [comment]
Hey @PeerRich Is this issue is still open ??
