### ISSUE TITLE
[CAL-2748] wrong email sent out on `resend invitation` for a pending member

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#12458]
### Issue Summary

in an organization if I invite a pending member to a team and then click `resend invitation`, it  sends an `View Invitation` email, which is a bit off i think, becasue the user has not yet created an account. and if i open the link i am redirected to login page instead of signup page 

### Steps to Reproduce

1. add a new member to an organization (ignore the email sent out)
2. now add that pending member to a team ((ignore the email sent out)
3. now click on resend invitation and notice the email sent out

### Expected Results

- a pending user should be asked to create an account and be added to the organization, (which happens if we open the other 2 previous emails)

### Evidence

[Screencast from 15-11-23 10:43:04 AM IST.webm](https://github.com/calcom/cal.com/assets/32706411/81cede10-1dea-4cad-a325-4c46a2a2e414)

<sub>[CAL-2748](https://linear.app/calcom/issue/CAL-2748/wrong-email-sent-out-on-resend-invitation-for-a-pending-member)</sub>

**Comment by hariombalhara** [comment]
No longer replicable after [https://github.com/calcom/cal.com/pull/12442](https://github.com/calcom/cal.com/pull/12442)
