### ISSUE TITLE
[CAL-2749] Could not book the meeting. Cannot read properties of undefined (reading 'appId')

### ISSUE THREAD

**Issue by ArthurSrz** [calcom/cal.com#12464]
### Issue Summary

Created a new account. Coud not book any slot

### Steps to Reproduce

1. go to the URL : [https://cal.com/romain.debru-gmail/30min?month=2023-12&date=2023-12-22&slot=2023-12-22T08%3A30%3A00.000Z](https://cal.com/romain.debru-gmail/30min?month=2023-12&date=2023-12-22&slot=2023-12-22T08%3A30%3A00.000Z)
2. Try to book any available slot
   3

### Actual Results

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/94339379-406e-4031-b95e-14719f2773b7/63ef3355-b6da-46ed-b068-118fb193525b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NDMzOTM3OS00MDZlLTQwMzEtYjk1ZS0xNDcxOWYyNzczYjcvNjNlZjMzNTUtYjZkYS00NmVkLWIwNjgtMTE4ZmIxOTM1MjViIiwiaWF0IjoxNzAwNjA5Nzg1LCJleHAiOjE3MDA2OTYxODV9.vjime9IPnpKP3S8oDJFTvss8DlwuvANzeoKBdMUb_N0)

* This is an ideal result that the system should get after the tests are performed

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2749](https://linear.app/calcom/issue/CAL-2749/could-not-book-the-meeting-cannot-read-properties-of-undefined-reading)</sub>

**Comment by chnoumanejaz** [comment]
There is no error like that I tried to reproduce several times.

![image](https://github.com/calcom/cal.com/assets/66419928/b125c230-6e18-48c4-aa25-1c8040b538b2)

**Comment by Falit** [comment]
Hi, is this resolved?

**Comment by chnoumanejaz** [comment]
> Hi, is this resolved?

Yess

**Comment by ArthurSrz** [comment]
Yes, it was a misunderstanding from the user who set up an apple calendar.

**Comment by sean-brydon** [comment]
Was able to reproduce this myself 

[https://threads.com/thread/34548796018/34548796019?s=7xFSAyjivrw2Ydvkg9hcr7](https://threads.com/thread/34548796018/34548796019?s=7xFSAyjivrw2Ydvkg9hcr7)

**Comment by harshithpabbati** [comment]
+1

I just got the same error 

<img width="957" alt="Screenshot 2023-11-27 at 4 28 22 PM" src="https://github.com/calcom/cal.com/assets/43822585/ba90e9ad-34ae-46d1-97b2-b8dfbc83b949">

**Comment by xandyalexandrec** [comment]
The same thing is happening for here for me:
https://cal.com/soraschools/virtual-info-session
