### ISSUE TITLE
Missing yarn.lock dependency tough-cookie

### ISSUE THREAD

**Issue by krumware** [calcom/cal.com#12497]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

This commit introduced jsdom to the dependencies. JSDOM has a dependency on @types/tough-cookie, but it doesn't appear it was successfully added to the yarn.lock
https://github.com/calcom/cal.com/commit/48dde246e92fd2ed94c84bf39389078ab9ec639a

Running `yarn` or `yarn install` again updates the yarn.lock file appropriately, but CICD processes which depend on the yarn.lock file will fail.

This is also breaking the cal.com/docker build.

(I believe the yarn.lock simply needs to be regenerated and updated)

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Builds dependent on dependency lockfiles fail

### Expected Results

- Builds dependent on dependency lockfiles succeed 
- 
### Technical details

n/a

### Evidence

https://github.com/calcom/docker/actions/runs/6952718952/job/18932636904#step:10:295

**Comment by krumware** [comment]
I am also using node 18 as recommended.
I would make a PR for this but on my end there are many differences to the yarn.lock (mostly removals) and feel it may be most confidently addressed by a core team member.

**Comment by hariombalhara** [comment]
This is fixed in main now. I can see it
<img width="914" alt="Screenshot 2023-11-23 at 12 20 50 PM" src="https://github.com/calcom/cal.com/assets/1780212/42a40b67-272f-4eb5-82a8-678e409e5fb4">
