### ISSUE TITLE
Ensure users have to intentionally decide for location and for durations (not implicitly)

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#12552]
### Is your proposal related to a problem?

This requirement is a UX requirement.
A requirement against the stupid users.

Lets get down to the technical issue:
- the meeting duration is sadly always preselected
- the meeting location too

So the users are often NOT reading and using the preselected and causing additional work, due to the fact that they "missunderstood" the form

The form shall require that the users have to INTENTIONALLY select 
- a meeting duration
- a meeting location

E.g. the meeting duration is mandatory configured in the backend/admin. Here it would be great if it is not mandatory in the backend and the meeting bookers have to intentionally select the meeting duration.

The second thing is that the user are getting the first radio button preselected for the meeting location. Instead the radio button shall not be preselected at all, so that the bookers here have to intentionally decide.

I know this features are really stupid user handling, but sadly we are having some that stupid users and they cause senseless additional work due to missunderstand, due to callbacks, due to being late since wrong decisions and many more
It could be easily evicted if the users are having to have to intentionally decide, else they cannot book the meeting at all.

### Describe the solution you'd like

see above

In my opinion it shall be possible to define in the backend, if the user has to intentionally to decide.
E.g. by having an optional admin entry for the 
Default-Location
Default-Duration

If this is not set, the booking-users have to select the values, if mutliple values are available. It shall in that case never happen that the users are getting any arbitrary decision without having intentionally decided (e.g. like it is now on Location)

### Describe alternatives you've considered

We tried to write in the E-Mail already notification what to consider.
But know what... 
They also do not read it..

### Additional context

this feature is for unexperienced users but it is a good practice for good UX to ensure that users do intentionally decisions if the decision is relevant for the next steps.
Except if it makes sense to have some defaults, (but this cannot be configured at all in the backend)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
if this is a recurring problem, can you not make different event types for each scenario? This seems to be a niche edge case. making it pre-selected helps with the checkout flow for everyone else. I dont think removing that preselection is a good idea
