### ISSUE TITLE
[CAL-2762] Zapier subscriber url shown in webhooks

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#12555]
When creating a new Zap with the Cal.com trigger, the Zapier subscriber URL is shown in webhooks as if it was a normal webhook. Zapier webhooks should not show up here, they are deleted automatically when the Zap is disabled or deleted. 

![Screenshot 2023-11-27 at 11.28.13 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f34908bc-3e05-49a3-a12b-1105893fa2fe/bc882fc6-1e47-42a8-8bb1-26b9b6e1df1c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMzQ5MDhiYy0zZTA1LTQ5YTMtYTEyYi0xMTA1ODkzZmEyZmUvYmM4ODJmYzYtMWU0Ny00MmE4LThiYjEtMjZiOWI2ZTFkZjFjIiwiaWF0IjoxNzAxMTAyNjU1LCJleHAiOjE3MDExODkwNTV9.BhpJTliE1yT5343W5HrovFUzJtfZPpFhX5vlvijywas)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2762](https://linear.app/calcom/issue/CAL-2762/zapier-subscriber-url-shown-in-webhooks)</sub>

**Comment by tapassaha-01** [comment]
is this issue solved or have in live?

**Comment by CarinaWolli** [comment]
This issue is not yet solved
