### ISSUE TITLE
[BUG] While selecting the Cal.com is better with teams it is not behaving appropriately. 

### ISSUE THREAD

**Issue by ankitdubey10** [calcom/cal.com#12575]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

While selecting the Cal.com is better with teams, and its text content, and moving the arrow to the right side of the image or to towards the end of that particular block, it is getting dark and the below two corners which should be rounded turns to pointed once. Even the Lean More button becomes less visible. 

### Steps to Reproduce

1. First open the https://app.cal.com/teams 
2. Select the **Cal.com is better with teams**  and select the below text and then move the arrow towards end of that block.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- When we are individually selecting the texts then according to the highlight it is getting changed, but when we are as a whole selecting the whole content then the color of the font is not changing. 
- 
![image](https://github.com/calcom/cal.com/assets/91322957/c886c80a-f850-4610-b961-995e9be151d4)
![image](https://github.com/calcom/cal.com/assets/91322957/34ccc98b-1e73-4938-bf8b-d5bce1ccecf1)
![image](https://github.com/calcom/cal.com/assets/91322957/ba3973a4-04f9-4020-a9bb-2cf7a11c3a44)
In the above images we can clearly see that individual it is ok and good to go.
But when we just take the cursor to the image side or towards downwards. It makes Learn More less visible and its entire text as well. 
![image](https://github.com/calcom/cal.com/assets/91322957/1b125da4-4c07-4f71-b60c-38e18ad493a6)

### Expected Results

- Bottom two corner of the block should be same as of above as while selecting above part is not changing to square one. 
- So we need to make sure that boths' shape remain same. 
- While selecting the whole content of that block it must be able to show the Learn More and other texts, like in the above mentioned screenshots. 

### Technical details

- It is simple issue related to the highlight. It is completely a frontend related to styling. 

### Evidence
here I am attaching the complete screen recording. 

https://github.com/calcom/cal.com/assets/91322957/be1c87c3-4b3b-4d9a-8bea-2ab65c7d2742

**Comment by Pratik-Kumar-621** [comment]
The issue is because it is when you are selecting completely then the background image also get selected. if you make the image unselectable then the issue is resolved.
