### ISSUE TITLE
All new bookings are missing `eventTypeId` (value is set and returned as null)

### ISSUE THREAD

**Issue by al8** [calcom/cal.com#12582]
### Issue Summary

All new bookings have missing eventTypeId

(related to https://github.com/calcom/cal.com/issues/12576)

### Steps to Reproduce

1. create new booking of an event type using the URL e.g. `https://cal.com/<name/id>/<event name>`
2. query `curl -s "https://api.cal.com/v1/teams/XXXX/event-types?apiKey=<redacted>`
3. observe `"eventTypeId": null,`

### Actual Results

observe `"eventTypeId": null,` in new booking where I'm expecting the event type

### Expected Results

expect bookings to be correctly created with the eventTypeId filled in.

### Technical details

This is likely due to this bug https://github.com/calcom/cal.com/issues/12576 where you are unable to lookup the eventId. Your system can be improved with static type checking.

**Comment by alishaz-polymath** [comment]
@al8 
1. We're booking via UI here?
2. Why are we querying a team event type here exactly? This shouldn't be affected by any bookings made at all. When a booking is made, it **does not** affect an event-type. Can you please confirm the thought process here and that this isn't a typo?

**Comment by al8** [comment]
@alishaz-polymath sorry for the delay - the notification for comments got lost in my pile.

Checking the information in bookings, it does indeed look generally fine. There are several bookings with 'null' for eventTypeId, but they are older bookings.
