### ISSUE TITLE
Signup options are not disabled after clicking on signup button and some other minor issues

### ISSUE THREAD

**Issue by shazzx** [calcom/cal.com#12586]
## Issue Summary

Main Issue:

After clicking on signup button, you can still click on signup with google or SAML SSO which is not a good thing and can bring unexpected results. when you click on signup first and then signup with google it will take you to the google signup page. and when you try to go back you'll see that your account is created in a result of your first signup click

[signup-issue-calcom.webm](https://github.com/calcom/cal.com/assets/131521332/f819667a-52d5-4624-9e81-71e26f497486)

### Other Minor Issues:

![email-body-issue-calcom](https://github.com/calcom/cal.com/assets/131521332/994bde68-720d-4c85-b5e7-b541fcffa004)

#### 1st Issue 
on verify email section there is a text "verify_email_page_body"  which appears before the main text is loaded. which is not good for user experience.

#### 2nd Issue
on verify email section when you click on back you can see I'm navigated to the previous account deletion survey page which is the result of my prior account deletion. this is unexpected and should not happen. (I also have experienced after signing up you'll be redirected to the verify email section and when you click back 1 or 2 times you'll be redirected to the user dashboard)

#### Suggestion:
user should directly be navigated to dashboard on signup because without verifying email you can still access the user dashboard so why not directly redirect the user to the main page and the main topbar will guide the user that their email is not verified so they have to verify the email.

### Steps to Reproduce the Main Issue:

1. Go to signup page and fill out the required details.
2. Click on signup and then click on signup with google.
3. You'll be redirected to google signup page and your account will be created because of first signup click.
4. for other issues watch full video.

**Comment by Pratik-Kumar-621** [comment]
for the main issue we can create a boolean state and buttons are enabled only if that state is true and if user click on any signup button we can set that state to false resulting in disabling other signup buttons.
