### ISSUE TITLE
[CAL-2775] Add ability to flight features

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#12598]
### Describe the solution you'd like

Our feature flags currently only support on/off. It would be great to have a feature flighting system where we can roll out new features to small subsets of users and/or particular users.

### Desired features:

* **Controlled Rollouts**: Develop a system that allows us to control the rollout of new features to specific user segments or a percentage of the user base.
* **Granular Targeting**: Provide the ability to target features to specific user attributes, such as user roles, geography, or any custom criteria relevant to our application.
* **Configuration Management**: Hook into our current configuration management system that enables easy toggling of features on and off without requiring code changes.
* **Metrics and Monitoring**: Integrate metrics and monitoring capabilities to track the performance and user engagement of features during flighting.
* **Rollback Mechanism**: Include a rollback mechanism to quickly revert the rollout of a feature in case of unexpected issues or negative user feedback.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2775](https://linear.app/calcom/issue/CAL-2775/add-ability-to-flight-features)</sub>

**Comment by keithwillcode** [comment]
@antonio-pedro99 Are you still interested in taking this one? Feel free to submit a PR and we'll review!

**Comment by SomayChauhan** [comment]
Hey @keithwillcode, I came across an open-source library called Flagsmith. It seems to cover most of the features we're looking for right off the bat. Check out this video I found for a clearer picture: [[link]](https://www.youtube.com/watch?v=CrXRXhRGCXQ). Can I give it a shot and implement it using this library?

**Comment by SomayChauhan** [comment]
@keithwillcode 

I was looking into this—would it be okay if I use a third-party open-source library like flagsmith that we can self-host? Or should we aim to build the entire solution in-house and improve the existing feature-flag system we have?

**Comment by keithwillcode** [comment]
@SomayChauhan Yeah something that's self-hosted could be a good option if it provides lots of the features we are looking for, which it looks like Flagsmith does. Saw you opened a draft PR. We'll take a look!

**Comment by zomars** [comment]
I would go for improving our current approach but I'll gladly explore other options.
