### ISSUE TITLE
[CAL-2774] videoCallUrl missing in webhooks for event types that require confirmation

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#12590]
In the custom templates for webhooks, you get the video call URL like that: {{metadata.videoCallUrl}}

For event types that require confirmation, the videoCallUrl is always empty.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2774](https://linear.app/calcom/issue/CAL-2774/videocallurl-missing-in-webhooks-for-event-types-that-require)</sub>

**Comment by antonio-pedro99** [comment]
Hi I am interested in this one, can you assign?

**Comment by CarinaWolli** [comment]
@antonio-pedro99 great, no need to get assigned you can start working on it. Don't forget to link the issue in your PR 🙏

**Comment by maxdiplogit** [comment]
Hi, is this issue resolved? If not, I would like to work on this issue :smile:

**Comment by CarinaWolli** [comment]
> Hi, is this issue resolved? If not, I would like to work on this issue 😄

@maxdiplogit not yet resolved, you can go ahead and work on it :)

**Comment by SomayChauhan** [comment]
Hi @CarinaWolli ,

Isn't this the desired behavior? For event types that require confirmation, the videoCallUrl is generated after the meeting is confirmed by the host. So, it will not be available when the bookingCreated webhook is triggered, and we don't have any bookingConfirmed webhook

**Comment by CarinaWolli** [comment]
> Hi @CarinaWolli ,
> 
> Isn't this the desired behavior? For event types that require confirmation, the videoCallUrl is generated after the meeting is confirmed by the host. So, it will not be available when the bookingCreated webhook is triggered, and we don't have any bookingConfirmed webhook or am i missing something here?

Hi @SomayChauhan, that's right. But the meeting URL is also not available when the booking is confirmed and the bookingCreated webhook is triggered

**Comment by SomayChauhan** [comment]
ohh i see, thank you so much!!!
