### ISSUE TITLE
[UI] Very dim text color on theme change success popup in Dark Mode.

### ISSUE THREAD

**Issue by shazzx** [calcom/cal.com#12601]
### What's the issue?

**Update: I've also checked other parts of the application and noticed the same dim text on popup when updating something...**

When you change the bookings theme, success popup appears with a very dim text color in dark mode which should be a lighter color. there is also one more issue. when you select darkmode and click on update two times at a time the selection (border) of dark mode disappears.

![calcom-dim-text-color](https://github.com/calcom/cal.com/assets/131521332/01cab9cf-bcef-4663-b1e4-9a3df23f1601)

[calcom-ui-text-color-issue.webm](https://github.com/calcom/cal.com/assets/131521332/2a855d5f-d311-4929-a620-1b07f5c686ea)

### Steps to Reproduce
note: your browser should be in darkmode

1. Click on settings, go to appearance page.
2. Select and update the theme  
3. You'll see a success popup with very dim text color

1. To reproduce the second mentioned issue
2. Select darkmode click on update two times at a time.
3. You'll see there'll be no selection (border) on the darkmode container.

**Comment by HeratPatel** [comment]
@shazzx 
I am not able to reproduce the issue. For me it is coming correct.

<img width="1728" alt="Screenshot 2023-11-30 at 8 40 15 AM" src="https://github.com/calcom/cal.com/assets/22561658/ba75fbdf-4de3-4dd3-99d8-40a28f223bed">

**Comment by shazzx** [comment]
For me it's still there.

### Firefox.

![Screenshot from 2023-11-30 09-47-57](https://github.com/calcom/cal.com/assets/131521332/dcea4cdd-adc0-4891-b1a0-5323433e062c)

### Google Chrome
![Screenshot from 2023-11-30 09-49-11](https://github.com/calcom/cal.com/assets/131521332/ac573c95-5380-4afb-b4e4-149c9b4bb4b7)

**Comment by shazzx** [comment]
> I am not able to reproduce the issue. For me it's correct. Tested the same on Chrome too.

I think it's resolved now.
