### ISSUE TITLE
[CAL-2781] Cancelling Access to google account gives Json output

### ISSUE THREAD

**Issue by JIbil12** [calcom/cal.com#12602]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
For the first time i Login with google, website brings to the step 1 of 5 , while completing this on step 2 connecting to google calendar if i  cancel the access " Cal.com wants access to your Google Account "  , It brings to an error " https://app.cal.com/api/integrations/googlecalendar/callback?error=access_denied&state=%7B%22returnTo%22:%22https://app.cal.com/apps/installed%22%7D " Showing {"message":"`code` must be a string"}

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Login
2. Connect to Calendar Pop ups Step 1/5
3. Choose google calendar and connect
4. Choose account
5. If cancel the access error shows up

https://github.com/calcom/cal.com/assets/98404323/22c35115-be86-4625-8b96-a9cdd0a15b61

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>[CAL-2781](https://linear.app/calcom/issue/CAL-2781/cancelling-access-to-google-account-gives-json-output)</sub>

**Comment by Udit-takkar** [comment]
@JIbil12 we need both of the permission when connecting google calendar. we are already working on displaying an error message or toast instead of this json error

**Comment by Samrj12** [comment]
@Udit-takkar Hello, can I help you with it in anyway?

**Comment by Udit-takkar** [comment]
> @JIbil12 we need both of the permission when connecting google calendar. we are already working on displaying an error message or toast instead of this json error

joe is already working on this https://github.com/calcom/cal.com/pull/12513
