### ISSUE TITLE
[CAL-2780] Refactor database layer

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#12608]
Our current codebase tightly couples Prisma database calls throughout the application, making it challenging to write effective unit tests and increasing the risk of unintended side effects during database interaction. To address this, we propose a refactoring initiative to encapsulate Prisma database calls behind facades. These facades will provide a clean and testable interface, improving code maintainability, scalability, and the overall quality of our application.

### Desired Features:

* **Facade Implementation**: Develop facades that encapsulate Prisma database calls within distinct modules, offering a clean and organized API for database interactions. e.g. Repository Pattern
* **Testability**: Design facades to be easily testable, allowing developers to write comprehensive unit tests for business logic without directly interacting with the database layer.
* **Code Organization**: Improve code organization by separating database-related concerns from business logic, promoting a more modular and maintainable architecture. Abstraction of Prisma Queries: Abstract away Prisma-specific query details within facades, ensuring that changes to the database schema or ORM do not ripple through the entire codebase.
* **Documentation**: Provide clear documentation for developers on how to use the new facades, emphasizing their role in enhancing testability and code organization.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2780](https://linear.app/calcom/issue/CAL-2780/refactor-database-layer)</sub>

**Comment by manpoffc** [comment]
Would implementing DTOs, Data Mappers, and the repository pattern align with the requirements of this issue?

**Comment by keithwillcode** [comment]
@manpoffc Yes

**Comment by riddhesh-mahajan** [comment]
@keithwillcode @zomars @PeerRich 

Hey, I'd like to share a code snippet of my initial implementation. I'd appreciate an internal review before moving on to other models.
https://github.com/riddhesh-mahajan/cal.com/commit/36b54982e89c9a51b9bc762f7b66832fa6274ca3

Developers can utilize the query builder and repositories in the following manner:

```
const query = new UserQueryBuilder()
  .where(new UserQueryBuilder().whereUserIdIs(6).whereUsernameIs("free").build())
  .select(new UserQueryBuilder().selectUsername().build())
  .build();

const allUsers = await new UserRepo().getUsers(query);
```


This is just a demonstration, and I plan to incorporate additional clauses, better types and DTOs (Currently I am directly returning prisma result, but it would be better to add DTOs, to handle column name changes) once I receive approval. Looking forward to your feedback!
