### ISSUE TITLE
[CAL-2777] Refactor large UI components

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#12600]
To improve the modularity, testability, and maintainability of our UI, we propose refactoring these large components into smaller, more focused, and "dumb" components. 

### Desired Features:

- **Modular Refactoring**: Break down large UI components into smaller, self-contained, and modular "dumb" components that focus on specific responsibilities.
- **Clear Separation of Concerns**: Ensure that each refactored component has a clear and singular responsibility, promoting the separation of concerns.
- **Reusability**: Design components to be easily reusable across different parts of the application, fostering a more efficient and consistent user interface.
- **Testing Support**: Facilitate unit testing by creating components that are independent of business logic, making it easier to mock and test in isolation.
- **Documentation**: Provide clear documentation for developers, explaining the purpose and usage of each refactored component.

<sub>[CAL-2777](https://linear.app/calcom/issue/CAL-2777/refactor-large-ui-components)</sub>

**Comment by itzabhinavarya** [comment]
@keithwillcode Assign me please
