### ISSUE TITLE
[UI] Login options are not disabled when clicking on login button.

### ISSUE THREAD

**Issue by shazzx** [calcom/cal.com#12612]
## Issue Summary

When clicking on sign in button, other login options are not disabled (sign in with google or SAML/OIDC).

[calcom-login-issue.webm](https://github.com/calcom/cal.com/assets/131521332/0078fe18-0067-4ee6-b9f0-8e041367de27)

### Steps to Reproduce:

1. Go to the login page.
2. Fill out the details and click on sign in button and then click on sign in with google.
3. You'll be redirected to google sign in page.

**Comment by shazzx** [comment]
@Udit-takkar 

The problem is still there and you've closed this issue. why?

**Comment by Udit-takkar** [comment]
@shazzx I fixed in the PR https://github.com/calcom/cal.com/pull/12610 (not live on production yet)

**Comment by shazzx** [comment]
@Udit-takkar ok good.
