### ISSUE TITLE
There should be pointer curson while hovering over "choose photo" option for uploading Avatar

### ISSUE THREAD

**Issue by Afrin127329** [calcom/cal.com#12617]
### Is your proposal related to a problem?
Yes

### Describe the solution you'd like

In the "choose a file" option, the cursor should be pointer, It's happening when you try to upload your avatar, both from settings >> upload avatar option or if you are signing up for the first time. See the video below

https://github.com/calcom/cal.com/assets/125039325/46dd15d7-5113-4dbc-a427-cbcf286624c2

### Requirement/Document

Some style change can solve this issue

**Comment by PeerRich** [comment]
done https://github.com/calcom/cal.com/pull/12624
