### ISSUE TITLE
[CAL-2782] use "Email validation" from sendgrid for Booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12627]
add a new section in advanced settings:

![CleanShot 2023-12-01 at 19 48 44@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8496c432-f47b-4efd-8687-410e3c8315cb/e15797d6-2d79-41aa-a59e-fc054e6a756b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84NDk2YzQzMi1mNDdiLTRlZmQtODY4Ny00MTBlM2M4MzE1Y2IvZTE1Nzk3ZDYtMmQ3OS00MWFhLWE1OWUtZmMwNTRlNmE3NTZiIiwiaWF0IjoxNzAxNDYwMTQxLCJleHAiOjE3MDE1NDY1NDF9.8WahifRcaka7eCZrQIONnV9JYOmC2-zyzO9X3YGby74)

if checked, use Sendgrids Email validation and if the API returns with a potential spam email, the booking should "require confirmation"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2782](https://linear.app/calcom/issue/CAL-2782/use-email-validation-from-sendgrid-for-booking-page)</sub>

**Comment by Amit91848** [comment]
Hi @PeerRich. I am interested in working on this, but to use the api, you need to have a email pro or premium account. Any guidance on accessing the API for contributors? Additionally, I've explored [Abstract API validator](https://www.abstractapi.com/api/email-verification-validation-api) as a potential alternative.

**Comment by Amit91848** [comment]
@Ryukemeister Sendgrids Email validation api requires you to have email pro or premium account ([Email Validation is only available for Email API Pro and Premier plans, this is not available for reseller accounts.](https://docs.sendgrid.com/ui/managing-contacts/email-address-validation#generating-your-email-validation-api-key)). Additionally, SendGrid has stringent criteria for account creation, and I encountered difficulties in signing up to obtain the API keys

**Comment by 826625219** [comment]
How! This community is so active!

**Comment by Ryukemeister** [comment]
> @Ryukemeister Sendgrids Email validation api requires you to have email pro or premium account ([Email Validation is only available for Email API Pro and Premier plans, this is not available for reseller accounts.](https://docs.sendgrid.com/ui/managing-contacts/email-address-validation#generating-your-email-validation-api-key)). Additionally, SendGrid has stringent criteria for account creation, and I encountered difficulties in signing up to obtain the API keys

@Amit91848 I don't really have much knowledge about how email validation works in sendgrid. Lemme check that out first and I'll let know you about any workarounds for email validation without a pro account. For the time being you can look into some other issues :)

**Comment by amankumarm** [comment]
@Amit91848  
> @Ryukemeister Sendgrids Email validation api requires you to have email pro or premium account ([Email Validation is only available for Email API Pro and Premier plans, this is not available for reseller accounts.](https://docs.sendgrid.com/ui/managing-contacts/email-address-validation#generating-your-email-validation-api-key)). Additionally, SendGrid has stringent criteria for account creation, and I encountered difficulties in signing up to obtain the API keys

facing same issue in obtaining api keys from sendgrid, is there any workaround?

**Comment by Ryukemeister** [comment]
> @Amit91848
> 
> > @Ryukemeister Sendgrids Email validation api requires you to have email pro or premium account ([Email Validation is only available for Email API Pro and Premier plans, this is not available for reseller accounts.](https://docs.sendgrid.com/ui/managing-contacts/email-address-validation#generating-your-email-validation-api-key)). Additionally, SendGrid has stringent criteria for account creation, and I encountered difficulties in signing up to obtain the API keys
> 
> facing same issue in obtaining api keys from sendgrid, is there any workaround?

@amankumarm I tried looking into getting api keys for email validation with a freebie account but wasn't able to. Don't know any workarounds but will ask someone from the team if they have any ideas about it

**Comment by amankumarm** [comment]
@Ryukemeister, is there any way to just replace sendgrid and use resend for email notifications.

**Comment by Ryukemeister** [comment]
> @Ryukemeister, is there any way to just replace sendgrid and use resend for email notifications.

@amankumarm that's a possible solution but that comes with a lot of questions on it's own. Like how much effort and time would that take and also if its worth replacing sendgrid with resend? So I don't know what an ideal solution would look like at the moment but i've posted a message about this in our internal chat on threads, will get back to you as soon as I have a solution.
