### ISSUE TITLE
Edit Location modal truncates fields/cannot scroll on mobile

### ISSUE THREAD

**Issue by twolfson** [calcom/cal.com#12640]
### Issue Summary

When I receive a new booking and try to edit the location on my phone, I can choose a Meeting URL but then the successive field for Meeting URL is truncated.

It's visible once I switch to landscape mode, but that also seems quite broken since the previous fields aren't visible.

Screenshot at bottom

I did see #5987 and #3476 but those seem resolved already, and am unable to find others that are the same issue

### Steps to Reproduce

1. On a mobile device with a small screen
    - I'm using a Sony Xperia XZ2 Compact, resolution 1080x2160
    - There's a similar issue in 2160x1080 but it's different in that the fields pop out at the bottom
3. Navigate to an existing listing in https://app.cal.com/bookings/upcoming
4. Click on "Edit -> Edit Location"
5. Select "Link meeting"
6. See that new "Provide a Meeting Link" field is not visible and cannot be scrolled to

### Actual Results

- Field is getting cut off and not accessible via scrolling

### Expected Results

- All fields should be visible or scrollable

### Technical details

- Browser version: Chrome on Android, 119.0.6045.163
- Node.js version: N/A, using https://app.cal.com/

### Evidence

Screenshots:

![Screenshot_20231202-134150](https://github.com/calcom/cal.com/assets/902488/abedcf57-72b5-4a9e-817e-e096dcbacb51)

![Screenshot_20231202-134211](https://github.com/calcom/cal.com/assets/902488/a352f7c1-ffc0-41c2-aa8c-75eb4658656a)

**Comment by JeevanJoshi4434** [comment]
Can I work on this issue?

**Comment by Ryukemeister** [comment]
> Can I work on this issue?

Feel free to work on this if you're able to reproduce the issue and resolve it, just make sure that no one is working on this at the same time as you : )
