### ISSUE TITLE
Can't add an override in hosted version

### ISSUE THREAD

**Issue by joeczucha** [calcom/cal.com#12676]
### Issue Summary

Can't save overrides on hosted version

### Steps to Reproduce

1) On the hosted version, click into **Availability**
2) Click **Working hours**
3)  choose **Add an override**. 
4) Adding an override appears to work (you get a success message) 
5) Refresh the page, the override is lost. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

Doesn't save override

### Expected Results

Should save override

### Technical details

Hosted version [v.3.5.4-h](https://go.cal.com/releases)[-2e50625](https://github.com/calcom/cal.com/commit/2e5062516581958268fa2ff8ee7c20dc59e2783a)

Tried Firefox 120.0.1 (64-bit), Chrome Version 119.0.6045.199 (Official Build) (arm64), turning off Ublock, etc

### Evidence

https://share.cleanshot.com/x5nMpSlJ

**Comment by Tanujgarg37** [comment]
If you are saving your overrides then its still there .
I think this isn't a bug
