### ISSUE TITLE
feat: Add the ability to block certain emails/numbers from booking

### ISSUE THREAD

**Issue by sypion** [calcom/cal.com#12697]
I’ve had a couple of instances where I no longer wanted to allow certain individuals from booking on my Cal. I can only cancel those appointments, ultimately allowing them to just continuously block slots in the future.

### Describe the solution you'd like

Add the ability to block certain emails and/or phone numbers from being able to book on my Cal.

### Describe alternatives you've considered

- Requiring users to pay before booking
- Cancel said appointments

**Comment by PeerRich** [comment]
makes sense. will think about a blocklist

**Comment by Yashraghuvans** [comment]
An alternative to blocking specific emails and phone numbers from booking on your Google Calendar would be to set up a booking system that requires payment before the appointment is confirmed. This can help prevent no-shows and ensure that only serious and committed clients are booking appointments with you.

**Comment by sypion** [comment]
@Yashraghuvans, thank you for the suggestion. I’ve tried this previously but doesn’t work well for certain occupations. For example, if you’re a barber, you’d rather have payments in person to have an opportunity for tips.

**Comment by prasoon2211** [comment]
Hey guys any update/workaround for this? Someone is spamming my cal.com links with frivolous meetings!

**Comment by bapspatil** [comment]
Hey folks, does anyone have any update on this? I'd really appreciate the feature of blocking some emails from scheduling meetings. Getting booked with no agenda, and dealing with a lot of spam.

**Comment by markojak** [comment]
Any updates? This is a small issue but horribly annoying

**Comment by PeerRich** [comment]
this has been merged

**Comment by PeerRich** [comment]
in advanced settings of a link, click "email"

![image](https://github.com/user-attachments/assets/a63e1bc1-aa56-4273-aeee-b01c9180cbb5)

**Comment by markojak** [comment]
Oh nice thanks
Quick  response
definitely founder mode

**Comment by sypion** [comment]
Ah, true love. Thanks again!

**Comment by nirobio** [comment]
Hello, along a similar vein, is it possible to do the inverse, i.e. whitelist a certain list of email addresses for a specific booking link?

**Comment by eyedean** [comment]
Hello,

I believe this feature is not working as expected.  I entered someone's email address in the "Exclude" field (to block them from booking, as the title and the top post asked), but they can still book with their email address. (I tested that, so it's the exact same email address.)

Before filing a ticket/bug, I wanted to make sure that I am not missing anything on my end. @PeerRich can you please confirm that I am using it the right way?

Thanks!
