### ISSUE TITLE
[CAL-2784] Attendees who are booked for a seated event receive the updated info with details of other attendees, even if info sharing is off.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#12706]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1ffe0141-bd9b-4b28-9409-865f7cf3c0cd/51d65c35-d018-4924-ab93-13e083d5abe8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xZmZlMDE0MS1iZDliLTRiMjgtOTQwOS04NjVmN2NmM2MwY2QvNTFkNjVjMzUtZDAxOC00OTI0LWFiOTMtMTNlMDgzZDVhYmU4IiwiaWF0IjoxNzAyMjY3NjEwLCJleHAiOjE3MDIzNTQwMTB9.rclyD9LO7-88OnXoiQu_s6zTZrzLkYHKOVXB0QP6vd4)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/71b0c629-2349-4b3c-b696-3724a895af24/d6d5c901-e8f2-4117-8898-94253dc29642?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83MWIwYzYyOS0yMzQ5LTRiM2MtYjY5Ni0zNzI0YTg5NWFmMjQvZDZkNWM5MDEtZThmMi00MTE3LTg4OTgtOTQyNTNkYzI5NjQyIiwiaWF0IjoxNzAyMjY3NjEwLCJleHAiOjE3MDIzNTQwMTB9.-Sg8qPxdkICigFJR148Aidw3Fga1_Oj2eJzqVZQZHjg)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a0d54fa1-5b1f-4131-9bbe-9c72a927213c/1ada42b6-c36a-4c19-a136-9f4fc176ce9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMGQ1NGZhMS01YjFmLTQxMzEtOWJiZS05YzcyYTkyNzIxM2MvMWFkYTQyYjYtYzM2YS00YzE5LWExMzYtOWY0ZmMxNzZjZTljIiwiaWF0IjoxNzAyMjY3NjEwLCJleHAiOjE3MDIzNTQwMTB9.DOQc5aVQTTNeWAzhyTywAt_I6BTY9tCcN37G5rMdp4g)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2784](https://linear.app/calcom/issue/CAL-2784/attendees-who-are-booked-for-a-seated-event-receive-the-updated-info)</sub>

**Comment by Utkarshn10** [comment]
Hey @milospuac I am unable to view the images you shared, hence this question. Did you turn `Share attendee information between guests` option on while creating the event? 

![image](https://github.com/calcom/cal.com/assets/58587256/d7c94e4c-f53c-46f7-9635-fe7f6fdfb7ee)

**Comment by Utkarshn10** [comment]
Hey @milospuac can you please reshare the images, as they are'nt visible.
