### ISSUE TITLE
[CAL-2783] translate boolean values in emails

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#12703]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4783b38b-7689-4cc4-b3b4-df99fc250509/db3aea98-74a0-4ce7-a30a-55b5b1c0786e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NzgzYjM4Yi03Njg5LTRjYzQtYjNiNC1kZjk5ZmMyNTA1MDkvZGIzYWVhOTgtNzRhMC00Y2U3LWEzMGEtNTViNWIxYzA3ODZlIiwiaWF0IjoxNzAyMjY3MTYzLCJleHAiOjE3MDIzNTM1NjN9.4U29Uq2FRTv9Gscq8f3KFg53M6EqbNZBpBXWheVNQlA)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9603682b-7ef3-4392-bcc6-602bb907bf14/be5ecd83-703c-4847-b62a-6e98be644c42?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NjAzNjgyYi03ZWYzLTQzOTItYmNjNi02MDJiYjkwN2JmMTQvYmU1ZWNkODMtNzAzYy00ODQ3LWI2MmEtNmU5OGJlNjQ0YzQyIiwiaWF0IjoxNzAyMjY3MTYzLCJleHAiOjE3MDIzNTM1NjN9.Ha-jEKcSz5-SNE8HA4DTrdBHIKWKukT_Y7gE5cqwbYs)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2783](https://linear.app/calcom/issue/CAL-2783/translate-boolean-values-in-emails)</sub>

**Comment by 01582** [comment]
Sure i can help.

**Comment by 01582** [comment]
without an approval for this feauture, i can't help for this issue

**Comment by PeerRich** [comment]
approved

**Comment by Ashu463** [comment]
could you pls share the file name pls
