### ISSUE TITLE
Feature Request: Meeting Survey (like in calendly.com)

### ISSUE THREAD

**Issue by eigenstil** [calcom/cal.com#12710]
### Is your proposal related to a problem?

I'm always frustrated, when I want to schedule a meeting with more than one person. For this scenario I need to scan through my calendar, block times by hand, have to remember which times I blocked (note them down in an email) and send theses times via mail to the concerning persons.

### Describe the solution you'd like

I would like to have the possibility to create a meeting survey (just like calendly.com). I would like to have an interface, where I 

1. select a timespan (e.g. 30 Minutes)
2. select a couple of free dates in my calendar
3. name this new event
4. choose whether I want to block all these times in my calendar or not
5. get a unique link after saving, that I can share with all the concerning persons

The next step is, that people fill out the time slots, when they are available, I get notified and when I feel that enough "votes" are accumulated I can select the final date. After that, all the people that were available on this particular date and time should get notified and invited as always with cal.com. If I selected to block all the other dates, thos other dates should get deleted after "finishing" the survey.

### Describe alternatives you've considered

Do everything manually, which is very tedious and errorprone (forgetting which times I actually blocked, forget to delete all the blocked events after the final date was set etc.)

### Additional context

I did some screenshots, how it looks at calendly:
<img width="894" alt="image" src="https://github.com/calcom/cal.com/assets/37832701/4c417700-fddb-41f7-8794-f2041ad75733">
<img width="436" alt="image" src="https://github.com/calcom/cal.com/assets/37832701/58171e7f-570b-4d57-8413-60d15681f64e">
<img width="503" alt="image" src="https://github.com/calcom/cal.com/assets/37832701/7f398f09-8037-4bf6-bd83-ec37d734bf40">

### Requirement/Document

Calendly has some information on their public website: https://calendly.com/features/meeting-polls

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
this has come up not so often yet, and is a huge undertaking. I know this is possible in other scheduling products but we are not sure if this makes it into the core roadmap anytime soon. check out https://rallly.co for poll-based scheduling!

**Comment by eigenstil** [comment]
@PeerRich ok, thank you for your answer.

**Comment by elisabeth-gbl** [comment]
Hi I would love this feature as well. Would it be possible to revisit the idea of implementing this?

**Comment by cannibalflea** [comment]
I would also love to have this feature. It is one of calendly's best options. rallly is a decent alternative but it would be so much better to have this within the same calendar experience, in particular to be able to see your other appointments when building the poll (something you can do in calendly's implementation).

**Comment by rob-cr** [comment]
Really would love this feature as well. It is the only reason I cannot stick to cal.com yet, as this major feature is missing.

**Comment by eigenstil** [comment]
actually I think it is the same as here:
- https://github.com/calcom/cal.com/issues/12571
- and here https://github.com/calcom/cal.com/issues/7595

So this is more or less a duplicate

**Comment by AsafDafna** [comment]
I would also love to have this feature in cal.com
I quite like the savvycal implementation of this (https://savvycal.com/meeting-polls). 
Also, it would be great to have optional extra fields in the meeting survey like phone etc. that could be used in later stages.

**Comment by WinterMarchDev** [comment]
why is this still not available?

**Comment by davefladung** [comment]
@PeerRich Any reason this isn't developed yet? I love most of cal.com but this is a feature that I find I need constantly working with other entrepreneurs with busy schedules. I am currently working with Calendly and Cal.com because of it.
