### ISSUE TITLE
Disregarding already booked spots or blocked calendar times

### ISSUE THREAD

**Issue by dmonn** [calcom/cal.com#1271]
### Issue Summary

Current events are disregarding already booked spots and blocked calendar times. This means bookers can double-book and generally don't know when a time is taken.

### Steps to Reproduce

1. Have a day fully blocked in your calendar
2. Head over to booking (https://cal.com/dom/15min?date=2021-12-15%2B0100)
3. Time is available

![Screenshot 2021-12-08 at 08 47 17](https://user-images.githubusercontent.com/6407031/145169427-a11d61a9-1e15-4eb3-a50d-73e84ae5ad82.png)
![Screenshot 2021-12-08 at 08 47 05](https://user-images.githubusercontent.com/6407031/145169431-98ea0e55-f04d-483a-b012-7f271f28cade.png)

### Technical details

- Browser version: Chrome 96.
- Node.js version: Using cal.com hosted
- GCal is connected in integrations

**Comment by ConnorGargano** [comment]
Hi @dmonn,
Can you confirm these events are set to 'Busy' and not 'Free'

**Comment by dmonn** [comment]
Can confirm

**Comment by sec0ndhand** [comment]
This could fix [office 365](https://github.com/calendso/calendso/pull/1269) but I haven't looked into GCAL.
