### ISSUE TITLE
Enhance the DB Model Creation Workflow

### ISSUE THREAD

**Issue by aaryamvn** [calcom/cal.com#1272]
### Is your proposal related to a problem?
 
My proposal isn't necessarily about a problem, however, it is something in regards to

- Increasing the scalability of DB Models
- Developing a more effective model-creation workflow
- Having a class-based approach to models, allowing the utilization of the model in other aspects of the application for type annotations.

### Describe the solution you'd like

Use Decotix! It allows you to form decorator-first typescript classes that represent your DB models. On the usage of one simple command, it generates a Prisma schema from the class-based models you created.

**the repo:** https://github.com/Angshu31/decotix
**the documentation:** https://decotix.netlify.app/docs/intro

### Describe alternatives you've considered

I've considered proposing the use of https://github.com/jamiepine/prismix, however, I've found that Decotix follows a much more seamless approach and Prismix can get redundant at times.

### Aditional Remarks

This is going to be quite a large implementation in the repo considering the pre-existing models, but it's certainly worth it in the long term.

**Comment by PeerRich** [comment]
hey, we'll not move from prisma right now
