### ISSUE TITLE
Navbar Malfunction: when I resize window to more than half navbar always disappear.

### ISSUE THREAD

**Issue by ahmadfaransiddiqui** [calcom/cal.com#12724]
Found a bug...

Issue is with the navbar, navbar is fixed when scrolling in windows less than half of the size of screen but disappear when scrolling on windows larger than half of the screen size.

### Steps to Reproduce

1. Go to cal.com [https://cal.com/]
2. On the home screen of landing page, scroll the page.
3. Notice the behavior of navbar with the window resized to less than half the size of screen and notice when the window is maximized or is resized to the size more than half of the screen.
4. Or scroll the page and resize the window after scrolling down to any part of the page and notice the shift in navbar behavior.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

The navbar disappears on scrolled pages when window is resized to any size larger than half the size of the screen.

### Expected Results

The navbar shall remain fixed to the top of the page at all times to enhance UX and in order to make interaction with the site proper.

### Technical details

- CSS or the main skeleton framework of the site needs to be rectified.

### Evidence

https://github.com/calcom/cal.com/assets/97630818/24497113-cba9-49e4-b331-7e79f8489c87

**Comment by PeerRich** [comment]
thats not an error but a design decision
