### ISSUE TITLE
[CAL-2788] String of text shows on the org onboarding for creating teams

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12729]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9ddf8f3a-5019-40c1-acc5-ffad4ec7392b/860df1f1-8379-4830-b994-fcea049f05e2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85ZGRmOGYzYS01MDE5LTQwYzEtYWNjNS1mZmFkNGVjNzM5MmIvODYwZGYxZjEtODM3OS00ODMwLWI5OTQtZmNlYTA0OWYwNWUyIiwiaWF0IjoxNzAyNDMxNjM0LCJleHAiOjE3MDI1MTgwMzR9.pR2lsx9Yp8VWx8zZBY0KRiPQi62mkFxP-AA1kGyD56g)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2788](https://linear.app/calcom/issue/CAL-2788/string-of-text-shows-on-the-org-onboarding-for-creating-teams)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar this was added by you 4 days ago, should be a quick fix
