### ISSUE TITLE
[CAL-2794] Onboarding redesign

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12739]
[Designs](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=7441%3A41085&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2794](https://linear.app/calcom/issue/CAL-2794/onboarding-redesign)</sub>

**Comment by Pratik-0621** [comment]
@ciaranha ?

**Comment by dew-dr0p** [comment]
Would love to work on this, can I get approval?
