### ISSUE TITLE
[CAL-2789] Padding Off

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12731]
![CleanShot 2023-12-12 at 11.39.07@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e66549b9-c41e-4717-b8a2-ffc2f6460712/b9f545fd-ede1-45ed-b384-109d295189d1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNjY1NDliOS1jNDFlLTQ3MTctYjhhMi1mZmMyZjY0NjA3MTIvYjlmNTQ1ZmQtZWRlMS00NWVkLWIzODQtMTA5ZDI5NTE4OWQxIiwiaWF0IjoxNzAyMzUyNTAwLCJleHAiOjE3MDI0Mzg5MDB9.Q-EYlZnrnZcEXOn_p5RS8GBoWusHVRBhK5yzCxJ5b4o)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2789](https://linear.app/calcom/issue/CAL-2789/padding-off)</sub>

**Comment by soniyaprasad77** [comment]
What are the steps to reproduce this issue? I am not getting such a UI issue here.
![Screenshot (351)](https://github.com/calcom/cal.com/assets/63783532/73588b33-e654-47b7-bafe-04b361f19af1)
