### ISSUE TITLE
[CAL-2793] Attributes in teams

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12738]
Prepare the Attributes project

for "marketplace embed" and for routing forms

[**Designs**](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=15496%3A500553&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2793](https://linear.app/calcom/issue/CAL-2793/attributes-in-teams)</sub>

**Comment by PeerRich** [comment]
cal.com/experts (dogfood our own)

**Comment by PeerRich** [comment]
talketry

**Comment by PeerRich** [comment]
ollie.health

**Comment by dew-dr0p** [comment]
Would love to work on this.
Can I get approval alongside more information to help me?

**Comment by SomayChauhan** [comment]
hi @ciaranha,
are these designs ready for dev?
can i work on them?

**Comment by ninadvyas** [comment]
Hello I would like to work on this issue.
