### ISSUE TITLE
New troubleshooter provides no way to exit page

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#12748]
### Issue Summary

Apparently the new troubleshooter is now live (although I'm [struggling](https://github.com/calcom/cal.com/issues/6729#issuecomment-1822722557) to [get](https://github.com/calcom/cal.com/issues/1171#issuecomment-1807127855) any confirmation of this).  However I immediately see a few UI issues, including this one, which is that there's no UI elements for exiting the troubleshooter. (The other ones are #12749 and #12750.)

### Steps to Reproduce

1. Go to an availability page
2. Click "Launch troubleshooter" which takes me to https://app.cal.com/availability/troubleshoot?eventType=date

### Actual Results

- No UI elements for exiting the page back to where I came from, other than hitting the browser's back button.

### Expected Results

- There should be some kind of icon and/or button for exiting the troubleshooter. 

### Technical details

- Version 119.0.6045.123 (Official Build) (64-bit)

### Evidence

Can't think of anything to add here.

**Comment by aspiers** [comment]
A cause for this has been suggested in https://github.com/calcom/cal.com/issues/6729#issuecomment-1852523227

**Comment by ciaranha** [comment]
@aspiers I'm going to close this as a duplicate as I have identified the issue in the one you have linked https://github.com/calcom/cal.com/issues/12751. Thank you for reporting this.

**Comment by aspiers** [comment]
@ciaranha OK thanks, could this perhaps also explain #12750?

**Comment by ciaranha** [comment]
I suspect it's related. Although I will keep that issue separate for @sean-brydon to investigate at the same time.

**Comment by aspiers** [comment]
Sounds good, thanks!
