### ISSUE TITLE
Error related to Sentry code when listing availabilities

### ISSUE THREAD

**Issue by kaulshashank** [calcom/cal.com#12753]
### Issue Summary

I'm making an API call and getting an JS property access on undefined error:

```
{
  "message": "Cannot read properties of undefined (reading 'startChild')"
}
```

The API call is

```
curl https://api.cal.com/v1/teams/7212/availability\?eventTypeId\=374468\&apiKey\=<API_KEY>\&dateFrom\=2023-12-11T14:25:11Z\&dateTo\=2023-12-12T14:25:11Z
```
### Technical details

- Node.js version: 18.x
- From the looks of it, this is erroring: https://github.com/calcom/cal.com/blob/7a67331d965ae1b5758c429b580ecf4dc23d39a6/packages/core/sentryWrapper.ts#L27-L30
- This might be of some help: https://github.com/getsentry/sentry-javascript/issues/4731. Looks like Sentry might not be setup correctly for production.

**Comment by PeerRich** [comment]
i believe this has been fixed
