### ISSUE TITLE
[CAL-2799] chore: checkbox component using tailwind forms blue

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#12755]
```
          Is this fix about it being blue? Because this is happening for all checkboxes:
```

![Screenshot 2023-12-12 at 3 53 01 PM](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2f992eea-4485-4f17-8ff1-a90ca1555205/e4e60c06-80c9-40cf-b088-e3597f066231?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yZjk5MmVlYS00NDg1LTRmMTctOGZmMS1hOTBjYTE1NTUyMDUvZTRlNjBjMDYtODBjOS00MGNmLWIwODgtZTM1OTdmMDY2MjMxIiwiaWF0IjoxNzAyNDE0NTQ2LCJleHAiOjE3MDI1MDA5NDZ9.JHEpl0tuTxXs-7um3gFGD5a_v3nDCrRZXtgG3WGDcbE)

\*Originally posted by @CarinaWolli in \*[*https://github.com/calcom/cal.com/pull/12742#pullrequestreview-1778418083*](https://github.com/calcom/cal.com/pull/12742#pullrequestreview-1778418083)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2799](https://linear.app/calcom/issue/CAL-2799/chore-checkbox-component-using-tailwind-forms-blue)</sub>

**Comment by PeerRich** [comment]
i think this was fixed no @Udit-takkar ?

**Comment by Udit-takkar** [comment]
@PeerRich i only fixed the team filter dropdown checkbox color and not here

**Comment by mrsourav1** [comment]
do you wanna change the color of the checkbox if yes what color?

**Comment by mrsourav1** [comment]
i can do it
