### ISSUE TITLE
[CAL-2796] Troubleshooter - Vertical scrolling not working on left panel or calendar

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12751]
When the left panel is higher than the viewport, you are unable to scroll.

In addition to this, there is some weird behaviour causing it to show the content from the bottom up, rather than the top down. As a result, you can't access the back button

This scenario is most likely to occur if you have more than one calendar connected, however it of course depends on the viewport height.

Also, scrolling on the right panel does not appear to be working.

[https://github.com/calcom/cal.com/assets/4536123/48485486-7dc2-47fa-8b4c-ea7e89bb2db7](https://github.com/calcom/cal.com/assets/4536123/48485486-7dc2-47fa-8b4c-ea7e89bb2db7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2796](https://linear.app/calcom/issue/CAL-2796/troubleshooter-vertical-scrolling-not-working-on-left-panel-or)</sub>

**Comment by sean-brydon** [comment]
Reopening as #12792 had to be reverted as it broke scroll in booker

**Comment by VivekTarun** [comment]
will fix it

**Comment by sean-brydon** [comment]
Scroll on booker is borked - [https://threads.com/thread/34562173686/34562173691?s=vFm7bqJ6vPcHPQQUf1GtCP](https://threads.com/thread/34562173686/34562173691?s=vFm7bqJ6vPcHPQQUf1GtCP) 

Will take this and figure out what is wrong. I fixed it on a local branch that broke the scroll on troubleshooter. Need some time to figure out what happened
