### ISSUE TITLE
[CAL-2800] Change Usernames on Enterprise Orgs

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12761]
Give **Enterprise** customers **OWNERS** the ability to toggle whether their users can change their usernames or not.

Currently, only [Cal.com](http://Cal.com) team can change usernames, but this can be a huge issue for customers depending on how their emails are set up. We want to make it easier for customers if they so choose to update their usernames or not.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2800](https://linear.app/calcom/issue/CAL-2800/change-usernames-on-enterprise-orgs)</sub>

**Comment by shirazdole** [comment]
cc @peer

**Comment by iprime2** [comment]
@shirazdole in page/url should I add this feature?

**Comment by iprime2** [comment]
Hey @shirazdole  we can solve this by following:
- First we have to add a field in table usernameChangePermission which will boolean in nature.
- In frontend/UI we can add a switch which toogle/change the value of usernameChangePermission variable.
- Now When ever user want to change their username in the backend it will first check/validate/authorize if user has permission to do that.
Note : Once functionality is stable we can discuss UI, there are distinct ways of doing that.

**Comment by PeerRich** [comment]
i dont think this should be a toggle. i think admins/owners should just be able to change usernames
