### ISSUE TITLE
bug:Overflow width of Component in home page 

### ISSUE THREAD

**Issue by swayam018** [calcom/cal.com#12768]
### Issue Summary
In the home page SCHEDULING FOR COMPANIES AND EMPLOYEES OF component is overflowX 

A summary of the issue. This needs to be a clear detailed-rich summary.
component is overflowX when the screen with larger than 1024px in smaller viewport working well. 

### Steps to Reproduce

1. go to cal.com
2. scroll down to SCHEDULING FOR COMPANIES AND EMPLOYEES OF component
3. the logo are overflowing out of width

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- overflowing company logo in x direction

### Expected Results

- Shouldn't overflow

### Technical details

screenshot of the bug
![Screenshot 2023-12-13 161110](https://github.com/calcom/cal.com/assets/59478020/8a5e01e4-4270-4856-a046-f8e1483bd64d)

### Evidence

![Capture](https://github.com/calcom/cal.com/assets/59478020/083dcef1-a142-4e8f-9183-56d35cd764d1)

**Comment by divyadhimaan** [comment]
Hi @PeerRich ,

I hope this message finds you well. I came across issue #12768 and I'm interested in contributing to this project.

If there are any specific steps or additional information I should be aware of, please let me know. I look forward to your guidance.

**Comment by imkrunalkanojiya** [comment]
You have to just add width:100% and overflow: auto

**Comment by PeerRich** [comment]
thank you! fixing

**Comment by PeerRich** [comment]
fixed. deploying
