### ISSUE TITLE
When clicking a deleted type event while it's "deleting", it sends you to 500 error

### ISSUE THREAD

**Issue by Soft-Bred** [calcom/cal.com#1277]
### Issue Summary

When clicking a deleted type event while it's "deleting", it sends you to 500 error

### Steps to Reproduce

1. Have an event type
2. Delete event type
3. Quickly click on the event type you just deleted, before it gets removed from the list
4. Get redirected to a 500: INTERNAL_SERVER_ERROR page
![image](https://user-images.githubusercontent.com/60551230/145277623-b1812964-8400-4f0b-9d3b-f2778685cbab.png)

### Technical details

- Browser version: Firefox 95

**Comment by ConnorGargano** [comment]
Hi there, thank you for raising this, I will pass this over to the engineering team.

**Comment by emrysal** [comment]
@Soft-Bred I wonder how to reproduce this issue; when I go into an event type, then click "Delete" - I am presented by this dialog:

![image](https://user-images.githubusercontent.com/1046695/146589120-0aa46f0a-e718-4b1b-a46e-7191ad910eef.png)
(That one has a little text bug)

Which keeps blocking until the user is redirected back to the event-types page.

**Comment by Soft-Bred** [comment]
Yes, that is what should happen, after clicking the "yes, delete event type" button, when the page is redirected to the event types page, the just deleted event will still be there for a split second. if one spam clicks the event before it disappears, it takes you to an error page.

I just tried it and it still works. i would suggest adding multiple event types so as to create some "lag" before the deleted event is actually removed from the list.

**Comment by rajatkulkarni95** [comment]
@emrysal The issue seems to occur when multiple consecutive clicks are done on the Delete CTA (kinda like a double click) since multiple `DELETE` events get called synchronously. Disabling the button on the first click should solve it, as the `onClick` would no longer be fired.

I can take a look at this if no one is already working on it

**Comment by emrysal** [comment]
@rajatkulkarni95 It's easy to fix but low priority (500 error looks bad but it does not break anything to re-attempt a deletion, as well as not happening for most users) - so I'll probably have a look in the next 1-2 weeks; to put in a debounce. If you're able to have a look before; great!

**Comment by juliopiubello** [comment]
@emrysal what approach do you want to take here? 

@jaysoni-ash42 is working on it

he started by doing a loading on the modal to prevent the user to try to delete the event again while it is loading
what other changes you want to be done? to change the error to bad request and a proper message?

**Comment by emrysal** [comment]
Loading state of deleting now works properly (Just double checked) and this issue is fixed :)
