### ISSUE TITLE
API endpoint for availability date override

### ISSUE THREAD

**Issue by ronissim** [calcom/cal.com#12780]
### Is your proposal related to a problem?

I want to be able to adjust future availability of hours automatically based off of the timezone I'll be in.
I already have code that extracts the timezone I'll be in based off of the flights that are in my calendar (you're welcome to build this in as a feature of your own)
for example : I book a flight to SF next week ,I want the available hours to now be from 8am pacific and not 8 am eastern. If you're even cooler - you can have cal.ai email me telling me if there are already meetings scheduled outside of what was defined as working hours.

### Describe the solution you'd like

(Describe your proposed solution here.)

most simple: API endpoint for adjusting future availability date overrides - ideally add a date override that shifts all existing working hours according to a timezone.

More complex: Deduce future timezone automatically and adjust based off of flights in my calendar

calendly's undocumented API

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
thats a really cool idea to mix that with the flights in the calendar. never thought about that. we do plan a travel mode where you can set up your timezone in advance for a certain period

**Comment by PeerRich** [comment]
related https://github.com/calcom/cal.com/issues/6790

**Comment by PeerRich** [comment]
@ronissim lets continue in https://github.com/calcom/cal.com/issues/6790
