### ISSUE TITLE
[CAL-2808] Public booking page: Add a setting/toggle to show user profile first when a user only has 1 event type

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12789]
**Currently**

When a user only has one event type, the link to their public project automatically redirects right into the calendar view to book that event type.

**Proposal**

Add a setting somewhere so the the user can decide whether their profile comes up first or it redirects automatically to the event type.

**Considerations**

* I think we should have this toggle on by default
* Would likely live under Settings/Appearance

Copy could do with work but could look something like

![CleanShot 2023-12-14 at 08 43 20@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a5de6d1a-a7a0-4290-a55f-23dd514728c9/f61f05ca-1772-49c9-900c-6aac46514ba7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNWRlNmQxYS1hN2EwLTQyOTAtYTU1Zi0yM2RkNTE0NzI4YzkvZjYxZjA1Y2EtMTc3Mi00OWM5LTkwMGMtNmFhYzQ2NTE0YmE3IiwiaWF0IjoxNzAyNTQzNDMwLCJleHAiOjE3MDI2Mjk4MzB9.mqzMmu-j-eu9P1BlYGnPgtAKDfk7JonUdiDTc6F4VxA)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2808](https://linear.app/calcom/issue/CAL-2808/public-booking-page-add-a-settingtoggle-to-show-user-profile-first)</sub>

**Comment by PeerRich** [comment]
i am not sure if we wanna do this
