### ISSUE TITLE
CC another person on all events of a certain type.

### ISSUE THREAD

**Issue by ronissim** [calcom/cal.com#12782]
### Is your proposal related to a problem?

I have different event types for different types of people I meet.
When I meet people for product feedback, I want our VP PRoduct included in the invite
When I meet a customer. I want an AE included in the invite.

### Describe the solution you'd like

Most simple: default add someone to an event of a certain type

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
you can achieve this with (a) a collective event or (b) with dynamic group links: i.cal.com/peer+bailey (just do a +) in between usernames
