### ISSUE TITLE
Add special menu to the event name

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#12786]
### Is your proposal related to a problem?

![image](https://github.com/calcom/cal.com/assets/18273833/fa793b77-cd8c-4759-9a2b-e56158abc240)
While choosing the event name to an event, it would be  great if we had a feature that shows the special options while writing instead of going to a new dialog. I would like to be able to see it like this: 
![image](https://github.com/calcom/cal.com/assets/18273833/1db16be5-a60e-4078-922a-0c468d8df987)

### Describe alternatives you've considered

A simple implementation would be letting those options to be added when you click them . 

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
you mean you want to prefill the options such as {Organiser} etc.? I think the current solution is good enough. a dropdown is too low prioirty for now

**Comment by a0m0rajab** [comment]
Yes that's what I meant, if not that I would think to have a button for  the available variables to prefill them
