### ISSUE TITLE
Not granting permissions bad user experience 

### ISSUE THREAD

**Issue by Hacksore** [calcom/cal.com#1279]
### Issue Summary

If you are using google calendar and you don't allow access to any scope you get into a denied state but only at something like an API layer.

I know this is rather "user error" but it would be good to drop them back to the app with something nice to look at explaining what they did wrong and or how to resolve it 😬.

### Steps to Reproduce

1. Link your Google Calendar
2. Do not select any access scopes
3. Continue anyway

### Video

https://user-images.githubusercontent.com/996134/145307229-be70efb1-b964-4787-9890-27305b6b3119.mov

**Comment by PeerRich** [comment]
not sure if we can change this, is this Google behavior? @baileypumfleet @emrysal

**Comment by emrysal** [comment]
No we have control over this endpoint.

**Comment by PeerRich** [comment]
yeah lets fix this @emrysal i agree this is not good behaviour

**Comment by sean-brydon** [comment]
Closing - this appears to be fixed and now redirects you to /event-types
