### ISSUE TITLE
[CAL-2811] Organization's Team invite email review and fixes

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12804]
In the screenshot it shows email sent when an email was invited in a team(Engineering) of an organization(Org1)

* Subject is wrong - It should have said something like 'Engineering's admin invited you to join the team in Org1 organization'
* There are other similar discrepancies in the content

  @peer @ciaranha Need the copy from you for this.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/78fe558a-ef82-4be6-8819-ddc37ee86224/26580508-dc57-42d8-804c-db96e80580ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83OGZlNTU4YS1lZjgyLTRiZTYtODgxOS1kZGMzN2VlODYyMjQvMjY1ODA1MDgtZGM1Ny00MmQ4LTgwNGMtZGI5NmU4MDU4MGVkIiwiaWF0IjoxNzAyNjIxNTc0LCJleHAiOjE3MDI3MDc5NzR9.x6zRWKb1UmXZTJ25guQIE51TJvKOMbD30rB8-u_3B3c)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2811](https://linear.app/calcom/issue/CAL-2811/organizations-team-invite-email-review-and-fixes)</sub>

**Comment by Parvezkhan0** [comment]
@hariombalhara can i take this issue?
