### ISSUE TITLE
[CAL-2810] Copy Invite link not working on safari

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12801]
Copying doesn't show an error on Ui but there is an error in console.

![Screenshot 2023-12-15 at 11.15.59 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c4aa9b36-e45b-4686-8816-9c869042cb0b/56d05e58-cb2e-4005-a3b8-25905f13684a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jNGFhOWIzNi1lNDViLTQ2ODYtODgxNi05Yzg2OTA0MmNiMGIvNTZkMDVlNTgtY2IyZS00MDA1LWEzYjgtMjU5MDVmMTM2ODRhIiwiaWF0IjoxNzAyNjE5MTk0LCJleHAiOjE3MDI3MDU1OTR9.A9ZAaNDDvnrCH5WsZ85kpZB9GFaTNhc4Yi366C7vNAY)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2810](https://linear.app/calcom/issue/CAL-2810/copy-invite-link-not-working-on-safari)</sub>

**Comment by hariombalhara** [comment]
It seems that Safari doesn't allow clipboard access when accessed in async context. Here is the workaround to get it correctly working in Chrome, Safari and Firefox
https://wolfgangrittner.dev/how-to-use-clipboard-api-in-firefox/ - We need to implement this.

**Comment by ritiksharmarj** [comment]
@hariombalhara even though I was following the same article to solve this issue but failed. Why did you create promise to set invitelink in the blob?

and your code is working fine in Safari, I checked it.

**Comment by hariombalhara** [comment]
@ritiksharmarj It was as per the article's recommendation. Because you can't do an async operation before writing to clipboard, the async operation has to happen within clipboard API.
