### ISSUE TITLE
logging in and going to homepage  page gives `ERROR 404  This page does not exist`

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#12802]
### Issue Summary

logging in and going to homepage  page gives `ERROR 404  This page does not exist`

### Steps to Reproduce

1. take the latest pull from main

### Evidence

[Screencast from 15-12-23 11:14:11 AM IST.webm](https://github.com/calcom/cal.com/assets/32706411/0e28702c-6ea5-497e-b5c7-1bd41b150be5)

**Comment by TaduJR** [comment]
@SomayChauhan I am not able to re-produce it. Are you still facing it?

**Comment by SomayChauhan** [comment]
yup!, still getting it

**Comment by Ryukemeister** [comment]
@SomayChauhan tried reproducing this and indeed got a 404 myself. I've posted about this in the engineering chat so hopefully this will be resolved in a while. Thanks for bringing this up :)
