### ISSUE TITLE
Documentation and Script Key Generation Mismatch

### ISSUE THREAD

**Issue by guptadeepak8** [calcom/cal.com#12806]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The deploy/install.sh script instructs users to use openssl rand -base64 32 to generate a key and add it under CALENDSO_ENCRYPTION_KEY in the .env file. However, the documented command in the README is openssl rand -base64 24. This may lead to confusion or unexpected behavior.

### Steps to Reproduce

1.Navigate to the deploy directory.
2.Open the install.sh script.
3.Observe the line containing the CALENDSO_ENCRYPTION_KEY .

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

The install.sh script uses openssl rand -base64 32 to generate a key for CALENDSO_ENCRYPTION_KEY, instead of documented openssl rand -base64 24.

### Expected Results

- The documentation and the install.sh script should align in specifying the correct command for generating the key, avoiding confusion.

**Comment by rijuoddusual1999** [comment]
hii @guptadeepak8 I have solved this issue locally, pls assign me

**Comment by emrysal** [comment]
Hi @guptadeepak8 - this was actually a documentation error in the README.md - I pushed a fix.
