### ISSUE TITLE
invalid_type in client_id

### ISSUE THREAD

**Issue by ebdavison** [calcom/cal.com#12820]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Trying to install zoom app in a self-hosted docker environment.  I get a red pop-up that said "invalid_type in client_id" whenever I attempt an install.

### Steps to Reproduce

1. install and do intitial setup in docker
2. Apps -> App Store -> zoom
3. Install App

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

Nothing got installed

### Expected Results

- This is an ideal result that the system should get after the tests are performed

Zoom app installed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
  - firefox 120.0.1
  - docker install environment
- Node.js version
  - 13.5.6 was installed as part of the docker pull
- Anything else that you think could be an issue.
  - nginx proxy of https -> container (localhost:3001)
  - version showing on bottom of page: © 2023 [Cal.com, Inc.](https://go.cal.com/credits) [v.3.5.5-sh](https://go.cal.com/releases)

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by ebdavison** [comment]
Here is a screen capture of the error.
![image](https://github.com/calcom/cal.com/assets/549431/012333c7-a4f6-4c73-8f83-c9c970671fb6)

**Comment by SomayChauhan** [comment]
hi @ebdavison you first need to configure zoom on your instance
follow these steps to get up and running - 

# Obtaining Zoom Client ID and Secret
Open [Zoom Marketplace](https://marketplace.zoom.us/) and sign in with your Zoom account.
On the upper right, click "Develop" => "Build App".
On "OAuth", select "Create".
Name your App.
Choose "User-managed app" as the app type.
De-select the option to publish the app on the Zoom App Marketplace.
Click "Create".
Now copy the Client ID and Client Secret to your .env file into the ZOOM_CLIENT_ID and ZOOM_CLIENT_SECRET fields.
Set the Redirect URL for OAuth <Cal.com URL>/api/integrations/zoomvideo/callback replacing Cal.com URL with the URI at which your application runs.
Also add the redirect URL given above as an allow list URL and enable "Subdomain check". Make sure, it says "saved" below the form.
You don't need to provide basic information about your app. Instead click on "Scopes" and then on "+ Add Scopes". On the left, click the category "Meeting" and check the scope meeting:write.
Click "Done".
You're good to go. Now you can easily add your Zoom integration in the Cal.com settings.

after that run `yarn workspace @calcom/prisma seed-app-store` and you should be good to go

**Comment by ebdavison** [comment]
Thank you. I will go though those steps and reply with the results. 

If I am running this as a docker container, is it sufficient to stop/start the container? It looks like yarn runs when the container starts up.

**Comment by PeerRich** [comment]
a lot of self-hosting support can also be found in our discord: https://go.cal.com/discord

**Comment by maxbritto** [comment]
> hi [@ebdavison](https://github.com/ebdavison) you first need to configure zoom on your instance follow these steps to get up and running -
> 
> # Obtaining Zoom Client ID and Secret
> Open [Zoom Marketplace](https://marketplace.zoom.us/) and sign in with your Zoom account. On the upper right, click "Develop" => "Build App". On "OAuth", select "Create". Name your App. Choose "User-managed app" as the app type. De-select the option to publish the app on the Zoom App Marketplace. Click "Create". Now copy the Client ID and Client Secret to your .env file into the ZOOM_CLIENT_ID and ZOOM_CLIENT_SECRET fields. Set the Redirect URL for OAuth <Cal.com URL>/api/integrations/zoomvideo/callback replacing Cal.com URL with the URI at which your application runs. Also add the redirect URL given above as an allow list URL and enable "Subdomain check". Make sure, it says "saved" below the form. You don't need to provide basic information about your app. Instead click on "Scopes" and then on "+ Add Scopes". On the left, click the category "Meeting" and check the scope meeting:write. Click "Done". You're good to go. Now you can easily add your Zoom integration in the Cal.com settings.
> 
> after that run `yarn workspace @calcom/prisma seed-app-store` and you should be good to go

It seems Zoom has changed the process to create apps and this process no longer works. Does anyone know the new way of creating and connecting a Zoom app with cal.com ? Thanks!

**Comment by Noweisri** [comment]
> Here is a screen capture of the error. ![image](https://github.com/calcom/cal.com/assets/549431/012333c7-a4f6-4c73-8f83-c9c970671fb6)

Hi @ebdavison,

Can you let me know what happened to you regarding your issue (invalid_type) as i have faced the same error while installing webex on hosted calcom

**Comment by henningtillmann** [comment]
Is there any solution? I updated `ZOOM_CLIENT_ID` and `ZOOM_CLIENT_SECRET` in the `.env` file but cannot install the Zoom app ("invalid_type …"). The same happens to me when I try to install Google Calendar/Meet.

**Comment by Noweisri** [comment]
Hi @henningtillmann ,

I had the same problem with webex integration.
I redeployed my whole setup and it worked somehow, you can try that if it's a new deployment for you.

**Comment by henningtillmann** [comment]
@Noweisri Starting all over again is not an Option unfortunately. I have been running calcom for a few months, just wanted to add Zoom (or Google).

**Comment by cjbarroso** [comment]
In the same boat, I want to connect to google calendar.
