### ISSUE TITLE
[CAL-3112] If i am trying to install outlook app there is issue with backend response

### ISSUE THREAD

**Issue by pankajjhaa** [calcom/cal.com#12834]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Go to apps
2. Try to install the Outlook app
3. you will see the error

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- The app needs to be installed and it shows in my installed apps.

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Evidence

- I am attaching a recording link which I took using Bird Early bug extension
https://app.birdeatsbug.com/3gBnwfAKc-l-0gVXrKjYo6dEz-nifPxkTDU0CRlOXGj0

<sub>[CAL-3112](https://linear.app/calcom/issue/CAL-3112/if-i-am-trying-to-install-outlook-app-there-is-issue-with-backend)</sub>

**Comment by ramanujangunturu** [comment]
I'm unable to reproduce it and it installs just fine. can any one confirm ?

**Comment by omraval18** [comment]
@ramanujangunturu was it already installed when you tried it ? if not try when calendar is already installed in the app

**Comment by omaramraninejjar** [comment]
Hello, I have a similar issue. After sign-in into Microsoft account, it redirects to the app but no calendar is synched! nothing happened I can't see any errors!

**Comment by dantosXD** [comment]
> Hello, I have a similar issue. After sign-in into Microsoft account, it redirects to the app but no calendar is synched! nothing happened I can't see any errors!

I am also seeing this error.

**Comment by aaronjedwards** [comment]
I was able to install the Outlook app earlier this year, but was having issues with events not being added to calendars and uninstalled the Outlook app, only to now not be able to install it again. This puts us in a really bad spot as our main calendar integration is now broken and we are unable to leverage Cal.com.
