### ISSUE TITLE
[bug]: Fix the page width

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#12835]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

![Screenshot 2023-12-16 205356](https://github.com/calcom/cal.com/assets/81948346/de2655cf-0978-4424-9d50-c04288b5595b)

**Comment by ParasRawat29** [comment]
This is happening because of the property
**_scrollbar-gutter: stable_**  
 applied to html element If we set it to auto . it will fix the issue but will recreate this ( #11398)  issue .

**Comment by PeerRich** [comment]
i agree. fixing #11398 was a mistake. reverting it
