### ISSUE TITLE
Change the color of the text during login at step 5 at Nearly there!

### ISSUE THREAD

**Issue by MohammedTanveergithub** [calcom/cal.com#12830]
Found a bug.

### During login time at step 5 at Nearly there! the text below input box is not visible due to same color as the background.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Login (Using google account)
2. Skip starting 4 Step
3. At 5th step(Nearly there!)
4. There is bug below About text box (or) Input box

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Just can the color of the text to resolve the issue

### Actual Results

- The color of the text should be different when compared to background.

### Expected Results

- The ideal solution is to find the particular text in the code and change the color of it to white or grey. So, that it could be visible.

### Evidence

![image](https://github.com/calcom/cal.com/assets/122883259/06e3ae8e-5c0b-4eea-92b6-9a0876229bfe)
![image](https://github.com/calcom/cal.com/assets/122883259/d68a8eef-4294-486f-b002-683900c562d5)

**Comment by MohammedTanveergithub** [comment]
particularly on which file should i work to solve this bug...

**Comment by mrsourav1** [comment]
Ok i solved this issue and made a pr

**Comment by sanjayrajput54** [comment]
Its not reproduce in my case
<img width="881" alt="Screenshot 2023-12-16 173540" src="https://github.com/calcom/cal.com/assets/22739571/e8339a32-b854-4b35-896a-aab505bfca75">

**Comment by MohammedTanveergithub** [comment]
The issues is only visible in dark-mode.

**Comment by suprabhu77** [comment]
@mrsourav1 How can I link the PR to particular Issue?
Is it something only contributor can make it?
