### ISSUE TITLE
[Feature] Removing white borders after toggling buttons

### ISSUE THREAD

**Issue by H9660** [calcom/cal.com#12836]
While toggling buttons in the `event-types` page, I found that when we toggle them and their is a white border that comes around them which does not go until we click somewhere. 

What I propose it that we could either remove that white border that comes every time the button is toggled or make it transparent.

Here is a short demonstration:

https://github.com/calcom/cal.com/assets/73359258/87d0f709-0cfc-4795-b87c-0f9bd2e6a1ac

Steps to reproduce:

- Visit https://app.cal.com/
- Click login and create an account
- You will then be redirected to the event types page. 
- There you can find the above demonstration.

**Comment by ameeetgaikwad** [comment]
Would like to help! Can someone assign me?

**Comment by H9660** [comment]
@ameeetgaikwad This feature is no longer needed. Thanks!
