### ISSUE TITLE
[CAL-2824] Settings sidebar needs a UI update

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12866]
The settings sidebar doesn't match the designs. The reason is that the component in the sidebar is re-used in the event types sidebar and any changes are reflected in event types, resulting in the icon not being aligned properly. 

It was fine in the sidebar until you have a lot more items (like in Orgs) and then things start to get pretty messy. The sidebar in orgs is way too long and all the extra padding and spacing makes it really hard to scan. Particularly in the teams area.

Summary of issues

* The menu items are 4px higher than in design. Doesn't seem like much but when all items are added up it's a big difference.
* Spacing is not accurately reflected (all spec'd in Figma)
* We have the wrong colour on titles making them hard to differentiate from menu items
* We show the Organisation name instead of "Organisation" in design. Another user pointed this out recently and I agree that it's harder to scan this way.
* He also made the point about changing the top one from the username to just "My account". Given it's the first in the list I actually think it's easy to identify as is and doesn't need to change and shows context but open to trying it.
* We should alphabetize teams

![CleanShot 2023-12-19 at 08.53.39@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a2abe105-cb26-4004-bcab-4d56b24edbf7/43b4634b-dbc2-4c09-97e1-f3dfb5f19590?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMmFiZTEwNS1jYjI2LTQwMDQtYmNhYi00ZDU2YjI0ZWRiZjcvNDNiNDYzNGItZGJjMi00YzA5LTk3ZTEtZjNkZmI1ZjE5NTkwIiwiaWF0IjoxNzAyOTc2MDUxLCJleHAiOjE3MDMwNjI0NTF9.TRHIBhBw0nIQddbOpaSqHcoNVX7HnNlp6OynjzFytiU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2824](https://linear.app/calcom/issue/CAL-2824/settings-sidebar-needs-a-ui-update)</sub>

**Comment by Aryanshu919** [comment]
please assign it to me. i want to contribute..

**Comment by sean-brydon** [comment]
> please assign it to me. i want to contribute..

Hi @Aryanshu919 we don't assign issues due to a lot them being hard to keep track of. I havent started working on this so feel free to submit a PR if you decided to work on this

**Comment by Aryanshu919** [comment]
Thank's @sean-brydon i will do that.

**Comment by Aryanshu919** [comment]
@sean-brydon can you share the figma file with me so i can update the text color.

**Comment by yaman-694** [comment]
Please Update with valid image
