### ISSUE TITLE
[CAL-2822] Organization Onboarding bugs

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12862]
Use of backtick and &#39

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fc3e57c4-540f-444d-bccd-321de0bd139d/232b5d86-dad1-468f-87ae-3dc5b9ea6c84?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mYzNlNTdjNC01NDBmLTQ0NGQtYmNjZC0zMjFkZTBiZDEzOWQvMjMyYjVkODYtZGFkMS00NjhmLTg3YWUtM2RjNWI5ZWE2Yzg0IiwiaWF0IjoxNzAzMjcwMjM2LCJleHAiOjE3MDMzNTY2MzZ9.MimjNHvM7EY5mrTH2KhsXSyqKkULaNxT5pk7tFRQVFQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2822](https://linear.app/calcom/issue/CAL-2822/organization-onboarding-bugs)</sub>

**Comment by hariombalhara** [comment]
Also see [CAL-2811](https://linear.app/calcom/issue/CAL-2811/organizations-team-invite-email-review-and-fixes)

**Comment by ritiksharmarj** [comment]
@hariombalhara how to check this error and what should be the expected results?

**Comment by PeerRich** [comment]
we can probably rewrite this to:

An admin of {team} has invited you to their Organization: {team} on Cal.com
