### ISSUE TITLE
[CAL-2827] Creating a Team and not Paying Does not Create a Team

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12871]
I'm not sure if we made a change on purpose, but if you create team, and then press back on the Stripe check out page, you are shown the user settings screen which is confusing. 

Also, no team is created which is confusing  as well — I believe before we had teams created, but they're just unpublished? If the intention is that no team will be created, then the language needs to be more clear along with a warning message rather than just dropping the user into user settings

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2827](https://linear.app/calcom/issue/CAL-2827/creating-a-team-and-not-paying-does-not-create-a-team)</sub>

**Comment by PeerRich** [comment]
i believe this change was necessary to make teams paid only, otherwise some hackers abused the invite endpoint to spam-invite people

**Comment by shirazdole** [comment]
> i believe this change was necessary to make teams paid only, otherwise some hackers abused the invite endpoint to spam-invite people

We need to update the UX / languanging then -- otherwise it looks buggy and broken :( cc @ciaranha 

Maybe it can wait till Morgan redoes the pricing page
