### ISSUE TITLE
[CAL-2826] Weird API Error Message when Adding Microsoft Calendar

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12870]
If you are adding Microsoft calendar on account creation and choose to change your mind on the page where Microsoft is asking for permissions (it was in german so I'm not sure what button exactly she clicked, probably "cancel" or something from the Microsoft view)

then you get this weird no code error message

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3f6d8019-c1b2-4e60-9122-40e6df96d231/79a8453b-8b75-43ea-8870-d63a1c3b63b3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zZjZkODAxOS1jMWIyLTRlNjAtOTEyMi00MGU2ZGY5NmQyMzEvNzlhODQ1M2ItOGI3NS00M2VhLTg4NzAtZDYzYTFjM2I2M2IzIiwiaWF0IjoxNzAzMjcwMDg5LCJleHAiOjE3MDMzNTY0ODl9.SL3mw2Gp_LajRWDhz24fESo6qKxYM4cNo2RDP-oWcd0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2826](https://linear.app/calcom/issue/CAL-2826/weird-api-error-message-when-adding-microsoft-calendar)</sub>

**Comment by Krishcode264** [comment]
@shirazdole  i just tried to go through it , when  adding microsoft calender when i clicked cancel to last prompt from microsoft which was about to give access to cal for their calender it returned me to : https://app.cal.com/api/integrations/office365calendar/callback?error=access_denied&error_description=The%20user%20has%20denied%20access%20to%20the%20scope%20requested%20by%20the%20client%20application.&state=%7b%22returnTo%22:%22https://app.cal.com/apps/installed/calendar%3fhl%3doffice365-calendar%22%7d         

it should return to atual apps page where user started adding calender . i had seen same issue with google calender too #13217

**Comment by iprime2** [comment]
@Krishcode264 the issue #13217 is resolved I tried today and it working fine.
I look into this issue.
Thanks

**Comment by shirazdole** [comment]
Resolved
