### ISSUE TITLE
Invisible/Very low contrast buttons in Getting Started workflow

### ISSUE THREAD

**Issue by flatypus** [calcom/cal.com#12884]
When I was setting up a new account on cal.com, going through the Getting Started workflow, I ended up trying to look for where the Continue buttons were because they had very low contrast on my screen. They should be a lot lighter; check the evidence.

[Arc - Chromium; MacOS]
### Evidence
When linking calendar:
<img width="1117" alt="image" src="https://github.com/calcom/cal.com/assets/68029599/623e51f0-6082-47e9-b886-8f0cf97782e9">

Example without white rectangle outline. It looks like theres an empty space under the options, but that's where the 'Next Step ->' button is. I can barely see it.
<img width="1117" alt="image" src="https://github.com/calcom/cal.com/assets/68029599/1042cc92-f326-443d-a9cb-1fddc9e158be">

Same thing here; the description 'A few sentences about yourself' is very difficult to see.
<img width="576" alt="image" src="https://github.com/calcom/cal.com/assets/68029599/dbaf582a-19f1-4cd4-b347-17327d69374c">

**Comment by a0m0rajab** [comment]
Related codes: 
Few sentences: https://github.com/calcom/cal.com/blob/e248dfbda787144390fbdc8ed72b92aaaf90a0f9/apps/web/components/getting-started/steps-views/UserProfile.tsx#L146-L160

The continue button: 
https://github.com/calcom/cal.com/blob/e248dfbda787144390fbdc8ed72b92aaaf90a0f9/apps/web/components/getting-started/steps-views/ConnectCalendars.tsx#L81-L92

**Comment by ayushjha119** [comment]
@flatypus  Can you assign this to me, i can fix this

**Comment by flatypus** [comment]
git cloned project just now, should be fixed as of latest commit
