### ISSUE TITLE
[BUG]: The Button is different from the usual one - as it has White Background in Dark Mode

### ISSUE THREAD

**Issue by jaskrrish** [calcom/cal.com#12889]
The Button is different from the usual one - as it has White Background in Dark Mode.
Found a bug? Please fill out the sections below. 👍

### Issue Summary
In the **Getting-Started** the **Buttons** are different from the usual

### Steps to Reproduce

1. Go to Login and Sign up 
2. Go to Step-2 or Step-3 the buttons will be different

### Actual Results

- The background of the button is very greyish and different from the usual button seen 

### Expected Results

- The background of the button should be white as usual

#### Usual-Button
![image](https://github.com/calcom/cal.com/assets/144443132/acdfb094-6f4e-42af-8435-5cfc5b8b2385)

_Originally posted by @jaskrrish in https://github.com/calcom/cal.com/issues/12874#issuecomment-1863880257_
 ####    Button Seen in Step-2 and Step-4       
![image](https://github.com/calcom/cal.com/assets/144443132/240347e7-9435-4f23-a106-f2f47950071c)

### Idea-to-Resolve: 
- In Step-1 and Step-4 the Button component is imported from @calcom/ui
- Whereas in Step-2 and Step-3 normal HTML5 button is used and styling is added even if change the color to white the button is seen very greyish

Please Resolve the error...........

**Comment by mrsourav1** [comment]
actually button is unclickable here if you connect your calender it will be white and clickable. i dont think its a bug

**Comment by jaskrrish** [comment]
yeah sorry didn't notice my code has changed 
thanks @mrsourav1
