### ISSUE TITLE
[CAL-2833] Custom Brand Colors not Updating Brand Colors

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12886]
![CleanShot 2023-12-20 at 16.20.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0d79f2e0-e04e-4950-b748-126435f90f99/00739490-4a75-4880-824c-f56631f99561?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wZDc5ZjJlMC1lMDRlLTQ5NTAtYjc0OC0xMjY0MzVmOTBmOTkvMDA3Mzk0OTAtNGE3NS00ODgwLTgyNGMtZjU2NjMxZjk5NTYxIiwiaWF0IjoxNzAzMDYwNTE5LCJleHAiOjE3MDMxNDY5MTl9.cQ7Z0wC7Rkk4XGwVuCliNd5hrOFtsQzWKsn6ehaAXkg)

Individual link as part of an organization: 

![CleanShot 2023-12-20 at 16.21.05@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/455ad5b7-709b-49cb-9fd2-4356e43a60e6/5aa92443-444d-43e8-a586-3c2d12c42939?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NTVhZDViNy03MDliLTQ5Y2ItOWZkMi00MzU2ZTQzYTYwZTYvNWFhOTI0NDMtNDQ0ZC00M2U4LWE1ODYtM2MyZDEyYzQyOTM5IiwiaWF0IjoxNzAzMDYwNTE5LCJleHAiOjE3MDMxNDY5MTl9.y75_AdhH9qs2dwIFCUJOYCh-zW_vzruV0e4FuRqQ9Vc)

Collective link as part of an organization:

![CleanShot 2023-12-20 at 16.21.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b7e755b4-0266-4331-8c4c-fcac1319ad8c/f7e61bc4-4004-48ca-b1e6-80c3642d4d91?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iN2U3NTViNC0wMjY2LTQzMzEtOGM0Yy1mY2FjMTMxOWFkOGMvZjdlNjFiYzQtNDAwNC00OGNhLWIxZTYtODBjMzY0MmQ0ZDkxIiwiaWF0IjoxNzAzMDYwNTE5LCJleHAiOjE3MDMxNDY5MTl9.H27-gmMlj2NN3DoNkpbaQ2MSvKHqRO8TxwOJFSsz_Do)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2833](https://linear.app/calcom/issue/CAL-2833/custom-brand-colors-not-updating-brand-colors)</sub>

**Comment by PeerRich** [comment]
![image](https://github.com/calcom/cal.com/assets/8019099/0fd15d6b-b32d-4b5b-ab07-8f3ed9adb0b1)

![image](https://github.com/calcom/cal.com/assets/8019099/46abd2c0-4b96-46a9-b242-a8684fd58f1e)

![image](https://github.com/calcom/cal.com/assets/8019099/50009e32-980b-4e3c-b1f4-e0c661e1f9bd)

**Comment by ritiksharmarj** [comment]
@PeerRich @shirazdole I've checked it on the local server and it's working fine. The first one is for the light theme so if we set the theme to light then it works and similarly second one is for the dark.

If I missed something then I'd like to work on it.

**Comment by shirazdole** [comment]
Can you impersonate me on orgs and try? @sgriff96-brydon

**Comment by shirazdole** [comment]
![CleanShot 2024-01-11 at 19.28.28@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/38ae238b-8e36-4e07-8e89-145a11802d36/f4e5eeaf-ab46-49d3-91ac-fcae9048a58a)

![CleanShot 2024-01-11 at 19.28.07@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3c94adf8-b5f1-45ff-8910-c474ef8ef13b/5f8b2629-24dd-42e9-a48f-87f1b506e6bd)

I don't think it's still not working, at least on our org

**Comment by sean-brydon** [comment]
Interesting @shirazdole. So team based brand colours are based on the teams>appearance. 

I wonder if in this case - if a "team" has the "default" brand colour assigned do we go up a level and use the brand of the orgs? 

I think that makes the best sense in this case.  Let me know what you think - i dont think this would be too hard to implement. 

@Jaibles can you sense check my logic here too?
