### ISSUE TITLE
[CAL-2829] RESCHEDULE_EVENT workflow trigger not working for event type that require confirmation

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#12881]
### Issue Summary

When an attendee reschedules a booking that requires confirmation (won't be automatically confirmed), the 'when event is rescheduled' workflow trigger is not triggered. 

### Steps to Reproduce

1. Create workflow with trigger 'when event is rescheduled' 
2. Set active on an event type that requires confirmation 
3. Book event type 
4. Reschedule event type (not with organizer, do it in icognito)
5. This should now trigger workflow but it doesn't

<sub>[CAL-2829](https://linear.app/calcom/issue/CAL-2829/reschedule-event-workflow-trigger-not-working-for-event-type-that)</sub>

**Comment by Amit91848** [comment]
https://github.com/calcom/cal.com/blob/50fb903ba6555045ad84264702f4ec7cf69349f0/packages/features/ee/workflows/lib/reminders/reminderScheduler.ts#L146

This is preventing all workflows from triggering if event requires confirmation. @CarinaWolli

**Comment by CarinaWolli** [comment]
> https://github.com/calcom/cal.com/blob/50fb903ba6555045ad84264702f4ec7cf69349f0/packages/features/ee/workflows/lib/reminders/reminderScheduler.ts#L146
> 
> This is preventing all workflows from triggering if event requires confirmation. @CarinaWolli

Yes, for the trigger 'when event is booked' an event type that requires should not trigger when booked but when confirmed. If I remember correctly, that's what this line of code is here for
