### ISSUE TITLE
[CAL-2832] Apperance turn off Branding Switch Unclear

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12885]
I have no idea if this switch is on or off, it stays the same neutral color and the prompt says "your settings have been updated successfully" 

![CleanShot 2023-12-20 at 16.17.18@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a951beca-1e18-4384-8590-f59f1243e8e7/d336b857-51c7-45c8-b9eb-3f2156232df2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hOTUxYmVjYS0xZTE4LTQzODQtODU5MC1mNTlmMTI0M2U4ZTcvZDMzNmI4NTctNTFjNy00NWM4LWI5ZWItM2YyMTU2MjMyZGYyIiwiaWF0IjoxNzAzMDYwMjg3LCJleHAiOjE3MDMxNDY2ODd9.nyR7-fHZNTVuqnFNa1zTkLQHhVnRBoCOfNstDIQ_Aqc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2832](https://linear.app/calcom/issue/CAL-2832/apperance-turn-off-branding-switch-unclear)</sub>

**Comment by ritiksharmarj** [comment]
@shirazdole I checked it on my local server it's working fine. 

https://github.com/calcom/cal.com/assets/54701022/1c5eb6b2-0f1e-4784-b37a-b7f974fb221e
