### ISSUE TITLE
[CAL-2831] Managed Event Types has a String showing in Product

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#12883]
![CleanShot 2023-12-20 at 04.42.26@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bab939bb-324b-45d2-b6b4-5aa4e0fbbf23/2437e310-f541-40a1-9452-b0613c25f30c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iYWI5MzliYi0zMjRiLTQ1ZDItYjZiNC01YWE0ZTBmYmJmMjMvMjQzN2UzMTAtZjU0MS00MGExLTk0NTItYjA2MTNjMjVmMzBjIiwiaWF0IjoxNzAzMDE4NTk2LCJleHAiOjE3MDMxMDQ5OTZ9.vlllDbf0Li-ugYEVF4jS86_Qstl5-SlaMoNtzJrjQXU)

"count_members"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2831](https://linear.app/calcom/issue/CAL-2831/managed-event-types-has-a-string-showing-in-product)</sub>

**Comment by ritiksharmarj** [comment]
@shirazdole what should be the expected result?
