### ISSUE TITLE
Meeting - Video effects makes diagonal lines instead camera video

### ISSUE THREAD

**Issue by pablorq** [calcom/cal.com#12896]
### Issue Summary

In a meeting, or before it, when applying video effects to the camera, it makes some diagonal lines instead of the video from the camera. The camera works well and not applying video effects shows the right video form the camera.

### Steps to Reproduce

1. In Ubuntu, open Firefox.
2. Click in a Cal meeting link.
3. In the preview before the meeting, activate the video.
4. Video is shown ok.
5. In the settings, add a video effect.
6. The video from the camera is replaced with diagonal lines.
7. If the video effect has a background, the silhouette of the person is detected, but the video is replaced for the diagonal lines.

### Actual Results
The video from the camera is replaced with diagonal lines.
The silhouette of the person is detected correctly, but the video is replaced for the diagonal lines.

### Expected Results
The video from the camera.

### Technical details
- Ubuntu 23.10
- Firefox 120.0.1 (64-bit) snap (defult)
- Tested with different USB cameras with the same result.
- The same setup works with Google Meet, Zoom and Teams.

### Evidence

![Screenshot 2023-12-20 at 16-47-51 Cal com Video](https://github.com/calcom/cal.com/assets/774839/6d9a574c-b8e1-4e54-b84d-ab747988284c)

![Screenshot 2023-12-20 at 16-48-01 Cal com Video](https://github.com/calcom/cal.com/assets/774839/141a5480-f5a6-40f1-a277-6d2bd5064bd5)

Any idea?

**Comment by PeerRich** [comment]
this seems to be an isolated bug, could not reproduce. also we cant make changes to the video, its a dependency built by daily.co

**Comment by pablorq** [comment]
Is there any test that I can do?

I mean, this is odd because the same hardware setup works with other meeting services.

**Comment by pablorq** [comment]
Hi @PeerRich !

This issue is still here. I've tested in Chrome and it works fine. The problem seems to be with Firefox.

The same hardware with 2 different cameras and Ubuntu 23.10:
- Google Chrome Version 121.0.6167.85 (Official Build) (64-bit): works fine, no lines, effects could be applied.
- Firefox 122.0 (64-bit): show the lines when effects are applied.
- Firefox 122.0 (64-bit), private window: show the lines when effects are applied.

Any idea or test to do?
