### ISSUE TITLE
[CAL-2021] Hide preview URL for members that are pending

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12898]
Or at least disable it and explain with a tooltip that it will be active once invite is accepted.

![CleanShot 2023-06-22 at 09.47.11@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/87405c3e-fc1c-4cc1-9698-3a5c2a5deb00/a7c90e4b-5bde-4769-89a0-523ba08e89a7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84NzQwNWMzZS1mYzFjLTRjYzEtOTY5OC0zYTVjMmE1ZGViMDAvYTdjOTBlNGItNWJkZS00NzY5LTg5YTAtNTIzYmEwOGU4OWE3IiwiaWF0IjoxNzAzMDkxNjQ4LCJleHAiOjE3MDMxNzgwNDh9.Mz6DTbVHXpo_IPwD_Y9MjsNOrbjFtcpw9D-onl3rAgo)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2021](https://linear.app/calcom/issue/CAL-2021/hide-preview-url-for-members-that-are-pending)</sub>

**Comment by ImtiazNayeemShawon** [comment]
I wanna contribute assign me the issue  please

**Comment by mrsourav1** [comment]
i just hide the preview URL icon for the pending user
