### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by chroniusdan** [calcom/cal.com#12906]
It would be easier to get a handle on all of our outstanding bookings if we could see them all at once in a calendar view (i.e., a view that shows calendar and then within each square of the calendar it would show the appointments that exist on that date). Ideally, would be able to filter that view on a particular person (both booker and bookee).

**Comment by imkuldeepahlawat** [comment]
something similar like this would help alot
![Screenshot from 2023-12-21 16-24-19](https://github.com/calcom/cal.com/assets/84150035/bce30590-0fd6-4b9c-b451-2dc593453ee4)

**Comment by chroniusdan** [comment]
Yes, though a full-on calendar view (a full-month view) would be even more
helpful, just to see all the appointments on a given day (in this view,
there would be no need to see the *time* of the appointment, only would
need to see that a given appointment is on a given day of the month).

**Comment by PeerRich** [comment]
as of today weve decided to not ship a calendar view given how much of a UI challenge it is and people will keep asking for more calendars. we will not aim to replace existing calendars and always recommend using existing calendars (Such as google calendar, outlook, apple calendar or any of the CalDav open source calendars)

this project is focussed on scheduling, not the calendar experience for now
