### ISSUE TITLE
[CAL-3416] Ability to turn the cal.com email flow off

### ISSUE THREAD

**Issue by mreilly-lula** [calcom/cal.com#12920]
### Is your proposal related to a problem?

Currently, users automatically receive cal.com automated emails when they book events. This is amazing in most use cases. However, I have a few event types where we would want to send more custom emails that include further information. 

### Describe the solution you'd like

Combining webhooks and the ability to turn off the cal.com booking flow emails would allow us to build any email notification workflow we want.

### Describe alternatives you've considered

I haven't found any way to stop the cal.com automated emails.

##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3416](https://linear.app/calcom/issue/CAL-3416/ability-to-turn-the-calcom-email-flow-off)</sub>

**Comment by PeerRich** [comment]
i think giving people the option to turn off emails is a risky move. in the past we've decided to not implement this, mostly knowing that some people may deactivate this by accident. lemme keep this one open and see if more people want this

**Comment by alelotti96** [comment]
I've spent a week exploring cal.com and am interested in integrating it into my website. I've set up a custom notification system using webhooks and Amazon AWS. However, the inability to disable the default notification system is quite frustrating, resulting in duplicate notifications. The only workaround is to self-host cal.com, but dealing with the APIs in that scenario is challenging. It would be greatly appreciated if there were an option to turn off default notifications, perhaps by adding this feature to the "danger zone." Nevertheless, I want to express gratitude for this wonderful software.

**Comment by tristansusie** [comment]
I would also second that proposal to be able to turn off the initial email and deal with it inside the Workflows tab.

Having the option for HTML emails to style them as well would give the user superpowers.

Thank you for your dedication!

**Comment by jin-ds** [comment]
I'd love to option to disable the default and then use the workflow to customize it further. +100 for me

**Comment by peregrinescode** [comment]
Me too! Would also help with issue [CAL-2970] https://github.com/calcom/cal.com/issues/13321

**Comment by dominikhron** [comment]
I would appreciate the option to turn off confirmation emails being sent to myself as the organizer when a guest creates an event. I have Cal set up to add events to my Google Calendar. Confirmation emails are sent to my Outlook and show in my Outlook Calendar as pending. Since I have the two calendars synchronized, I end up with two duplicate events in my Google Calendar. Turning off email confirmations would fix this.

**Comment by PeerRich** [comment]
we will look into this for this milestone. we need to be very careful that people don't do this by accident

**Comment by Jojo14234** [comment]
Hi, am I missing something or is it only currently possible to disable the sending of confirmation emails but not cancellation emails?

I only see this option...

<img width="957" alt="Screenshot 2024-04-12 at 22 42 59" src="https://github.com/calcom/cal.com/assets/41197000/fb497aae-775c-495b-b8fb-17a55965f49a">

**Comment by bsh3p** [comment]
I want this also, please.

I send all my customer emails via Mailjet to maintain consistency and I need to disable cal.com notifications sent to Customers to achieve this without duplicating.

**Comment by ahsanz024** [comment]
We also want to send our own custom emails, can we prevent all emails to customers via Cal.com?

**Comment by fabriziospadaro** [comment]
It's a much-needed feature. 
I tried to hack this by sending a fake email in the hidden field and asking for the real one in another field, to prevent the user from receiving any emails from the calendar and sending them using my own email provider. 

However, the user doesn't receive the event on the calendar.

This is a super dirty hack that I am looking forward to avoiding once we have the option to turn off automatic calendar emails.

**Comment by BorisUpheave** [comment]
@fabriziospadaro how did you do that? _email_ field cannot be hidden in the embedded form.

**Comment by Adillwma** [comment]
+1

**Comment by CarinaWolli** [comment]
We are adding that for organizations: https://github.com/calcom/cal.com/pull/15902
Currently, there is no plan to add that for individual or team accounts

**Comment by fabriziospadaro** [comment]
@CarinaWolli Just to be 100% honest with the community, it's not a technical limit, but rather a paid feature under the "organizations" plan.

**Comment by CarinaWolli** [comment]
> @CarinaWolli Just to be 100% honest with the community, it's not a technical limit, but rather a paid feature under the "organizations" plan.

The only reason we are so careful about offering this feature is that we're concerned people might accidentally enable it and then complain about missing emails. 

Since it has been requested quite a few times, we are now exploring design options so we can offer this feature to all users.

**Comment by mreilly-lula** [comment]
What if, at least initially, this could only be enabled via the api?

**Comment by bsh3p** [comment]
> > @CarinaWolli Just to be 100% honest with the community, it's not a technical limit, but rather a paid feature under the "organizations" plan.
> 
> The only reason we are so careful about offering this feature is that we're concerned people might accidentally enable it and then complain about missing emails.
> 
> Since it has been requested quite a few times, we are now exploring design options so we can offer this feature to all users.

This is fair to worry about users stuffing this up.

I have a few ideas. 

1. Enable this with some smart UI, like the common UI  to delete an account where you have to type 'Enable Feature' with a link nearby to knowledge article and a warning.  If people are dumb enough to enable without reading a warning and the instructions and still type in the keywords... Then I don't think you can do much more to help these people. This way the UI kind of protects your team from complaints.

2. Bit of upfront effort but once done would be useful for other such features. That is to allow users to opt in to beta features, for others they'll not even see this option.

3. Combine both of the above would be even better

Thank you for continuing to consider this.

**Comment by nakul-malhotra** [comment]
is this ever going to be introduced for individuals? why are we blocking this to enterprise only?

**Comment by graid2030** [comment]
Paid feature to avoid spam, nice

**Comment by sliynex** [comment]
Is it ever going to be implemented for Individuals plan?
We all understand the willing of having "special features" for paid users but this is a basic feature, it's same like saying "We're blocking Tuesdays for non-paid users", lol.
Tons of people asked for it for the last 2 years, it's already exist, so it's only question of enabling or not for us..
Please re-consider it as some of us built complicated marketing flows and wish to avoid spamming the user with double notifications...
