### ISSUE TITLE
[CAL-2840] chore: remove "Commercial license required"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12934]
this is still showing up:

![CleanShot 2023-12-22 at 18 05 53@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d3920e37-af02-4e1a-bd84-0516a67e345d/eec1b637-9161-4cd4-8dbf-90140509b058?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kMzkyMGUzNy1hZjAyLTRlMWEtYmQ4NC0wNTE2YTY3ZTM0NWQvZWVjMWI2MzctOTE2MS00Y2Q0LThkYmYtOTAxNDA1MDliMDU4IiwiaWF0IjoxNzAzMjY4Mzg4LCJleHAiOjE3MDMzNTQ3ODh9.8jFMC7CWkXjUaMrl3thbOXcw7I2eur0P2zfPGjD2K1c)

but we already shipped the agplv3 free signup component

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2840](https://linear.app/calcom/issue/CAL-2840/chore-remove-commercial-license-required)</sub>

**Comment by vikram-s-narayan** [comment]
Also ... not able to access or add the cal.ai app after doing a git clone of the codebase and getting it to run on local. Not sure if this is intentional.

**Comment by mehuylsharma** [comment]
@PeerRich what route does this page correspond to?
