### ISSUE TITLE
[CAL-2849] Calendar Event ICS doesn't sync for timezones

### ISSUE THREAD

**Issue by RitZz48** [calcom/cal.com#12938]
There are multiple reports of this issue on the Discord Community.

[https://discord.com/channels/1125390093386010654/1184552597135310940/1184552597135310940](https://discord.com/channels/1125390093386010654/1184552597135310940/1184552597135310940)
[https://discord.com/channels/1125390093386010654/1163813318952243240/1163813318952243240](https://discord.com/channels/1125390093386010654/1163813318952243240/1163813318952243240)

Here is an Email that the invitee receives.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a6693433-6a14-458b-9a63-1130de9acdcb/c5bbff43-e66e-4542-acdd-551d3bd69093?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNjY5MzQzMy02YTE0LTQ1OGItOWE2My0xMTMwZGU5YWNkY2IvYzViYmZmNDMtZTY2ZS00NTQyLWFjZGQtNTUxZDNiZDY5MDkzIiwiaWF0IjoxNzAzODc1MzExLCJleHAiOjE3MDM5NjE3MTF9.5RNdG0LvT-3xYSMr8WyFfQJUZs4zK4l8izE6tcHlRLE)

As you can see at the bottom right, When shows Invitee's time in their timezone, However the ICS they receive contains the timezone of Host user which you can see on the top left.

I've tried using caldav and google calendar the problem persist in both.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2849](https://linear.app/calcom/issue/CAL-2849/calendar-event-doesnt-sync-for-timezones)</sub>

**Comment by WongChoice** [comment]
Couldnt reproduce in devmode
this is as far as i got

`    startInputType: "utc",
`

to

`    startInputType: "local",
`

Thanks

**Comment by emrysal** [comment]
Requested more info, it's possible this is not an issue.
