### ISSUE TITLE
Button to take user on top in footer at homepage

### ISSUE THREAD

**Issue by Aman003** [calcom/cal.com#12948]
### Is your proposal related to a problem?

When I open homepage/Landing page of website and keep scrolling to bottom, since it's a long page, it's good to have a button in footer which will take user immediately on top or can say jump the screen on top. So that they don't have to scroll it again. It's "good to have" feature.

### Describe the solution you'd like

Have a button in footer of page or keep it always at bottom of current view of page and as scrolling down button should move down. so that at any time if user wants to go on top, they don't have to scroll it up again and again. Keep this available on different pages as well if size is too big.

### Describe alternatives you've considered

Currently, user has to keep scroll up to go on top.

### Additional context

N/A

### Requirement/Document

![image](https://github.com/calcom/cal.com/assets/20884444/d2bf5c36-10bd-43e2-9192-3e317f2134d4)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by rakshitnegi1234** [comment]
Since I am a Beginner. I am not able to find the files/folders so that I can make Add this feature Here.

**Comment by PeerRich** [comment]
this repo is not for the cal.com website, only for the app (app.cal.com)

**Comment by Aman003** [comment]
Can you direct me to web repo?
