### ISSUE TITLE
Action buttons are hidden in dark mode during onboarding

### ISSUE THREAD

**Issue by phukon** [calcom/cal.com#12945]
# Issue Summary
## Dated [23 December 2023 1740hrs]
The action buttons that guide the user (during onboarding) to the next section is hidden in dark mode.

![bug](https://github.com/calcom/cal.com/assets/60285613/7d3e810b-77ff-42fe-b580-95a600679947)
![bug2](https://github.com/calcom/cal.com/assets/60285613/d1130ba1-a9ed-47a8-9027-d37236351a2e)

### Steps to Reproduce

1. Sign Up
2. Follow the steps to setup the calendars and link services.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Expected Results

- The action buttons should contrast the background.

### Technical details
- Google Chrome (Windows) 119.0.6045.200 (Official Build) (64-bit)

**Comment by VREDDY-01** [comment]
I think everything working fine.
![image](https://github.com/calcom/cal.com/assets/54312804/a607b34d-b87d-4019-801e-71563147a796)
might be issue with the browser or old versioned bowser.

**Comment by phukon** [comment]
Thanks for the heads up. Lemme just check again after an update.

**Comment by PeerRich** [comment]
fixed
