### ISSUE TITLE
`/settings/teams` layout is wrong

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#12947]
### Steps to Reproduce

1. go to /settings/teams and notice the layout

### Evidence

[Screencast from 26-12-23 03:53:37 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/60353e17-50d9-47df-bb0d-693b344b279a)

**Comment by doctone** [comment]
Are there any links to expected layout?

**Comment by SomayChauhan** [comment]
`/teams`

**Comment by adityacodes30** [comment]
Got it ,  will start working on this

**Comment by adityacodes30** [comment]
<img width="1597" alt="image" src="https://github.com/calcom/cal.com/assets/110766802/d5e047c5-f39c-4960-8504-ec1c5b6e4ade">

I get this on the url , has the issue been fixed ?

**Comment by nhannv** [comment]
I can reproduce this issue on cal.com production:

1. Go to /settings/teams
2. Press Create Team
3. Press Cancel

Actual:
<img width="1678" alt="image" src="https://github.com/calcom/cal.com/assets/7042953/f5fb04ba-2f77-4fd1-b3a4-9f482590081e">

**Comment by PeerRich** [comment]
wtf thats the wildest bug i have seen so far

**Comment by PeerRich** [comment]
cannot reproduce this

**Comment by Rksingh090** [comment]
I am also able to reproduce it.
![Screenshot from 2023-12-30 00-45-26](https://github.com/calcom/cal.com/assets/54115599/e0858d65-3322-4c3f-bd76-5c314d752dc5)

**Comment by Rksingh090** [comment]
Can you please review. I have opened a new pull request.
