### ISSUE TITLE
[CAL-2842] Zoho Calendar integration results in 500 server error

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#12955]
![Screenshot 2023-12-26 at 12.41.17.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b1f322c8-cef3-4144-874d-47ab68fa2ba9/7a357ef6-3c8d-448e-8e64-6362a19189da?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iMWYzMjJjOC1jZWYzLTQxNDQtODc0ZC00N2FiNjhmYTJiYTkvN2EzNTdlZjYtM2M4ZC00NDhlLThlNjQtNjM2MmExOTE4OWRhIiwiaWF0IjoxNzAzNzU2MDcyLCJleHAiOjE3MDM4NDI0NzJ9.0iLUEnuBEQGvAvLuQT7p8fELHVEUzGWAa45nck6Pvjg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2842](https://linear.app/calcom/issue/CAL-2842/zoho-calendar-integration-results-in-500-server-error)</sub>

**Comment by thedigitalnachos** [comment]
This is a huge issue for us, would love if someone could merge the PR :)

**Comment by PeerRich** [comment]
duplicate of https://github.com/calcom/cal.com/issues/12405 

added a bounty
