### ISSUE TITLE
Responsiveness issue when toggling on filter options on bookings page

### ISSUE THREAD

**Issue by Afrin127329** [calcom/cal.com#12952]
### Issue Summary

On bookings page, when toggling on filter options, it shrinks the whole booking content area. Kindly take a look on the following video for better understanding. Thanks

https://github.com/calcom/cal.com/assets/125039325/216f701d-d613-4ee9-b36e-8892613acf29

### Steps to Reproduce

1. Log in to your account
2. Go to bookings page
3. Click on filters
4. Toggle filter buttons

**Comment by leelabhaskar22** [comment]
i think everything is working fine


https://github.com/calcom/cal.com/assets/107635790/3ae1a172-a5d6-4259-a0b9-6370fdbd9aeb

**Comment by PeerRich** [comment]
can't reproduce either. also if this in-fact happens, it's too much of a small priority to fix right now 🙏

**Comment by Afrin127329** [comment]
Maybe it's my  browser compatibility issue. Extremely sorry for creating misunderstanding...
