### ISSUE TITLE
Feishu Cal connect

### ISSUE THREAD

**Issue by techknowlogick** [calcom/cal.com#12953]
### Is your proposal related to a problem?

I am unable to connect a feishu calendar to cal.com, as the connection doesn't exist yet

### Describe the solution you'd like

Cal.com supports Lark, the international version of Feishu. However, depending on where your tenant is, you are unable to use the Lark connection.

### Describe alternatives you've considered

Utilizing the Lark connection, unfortunately due to the tenant being in a localized region, the Lark app is unable to connect

### Additional context

The existing Lark code works, except different endpoints are needed. The likely route to achieving this would be to make the Lark code accept alternate endpoints and have the code be called twice, once with the default Lark endpoints, and the second time with Feishu endpoints.

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
so technically you could copy the app folder of lark and add the new endpoints, no?
