### ISSUE TITLE
[CAL-2848] i18n: check your email page flickers i18n

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#12966]
https://github.com/calcom/cal.com/assets/8019099/c84ae104-cd2d-49e8-84fe-e52fb422e28d

<sub>[CAL-2848](https://linear.app/calcom/issue/CAL-2848/i18n-check-your-email-page-flickers-i18n)</sub>

**Comment by WongChoice** [comment]
@PeerRich Hey attempted a fix please have a look 
thanks.
