### ISSUE TITLE
[CAL-2846] Allow creating availability at Team and User level

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12962]
Same as Webhooks, Workflows, Routing Forms - We need a New Button here

We should use `CreateButtonWithTeamsList` component for this.

We need this as we plan to add Profile switcher and then we really need to be able to create availability for a team of the organization.

Creating availability for the organization itself will follow later.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/99beeb07-dcd0-4d46-8eb5-409862ee4c2b/4788ac32-1240-4286-8902-2ad6016a11db?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85OWJlZWIwNy1kY2QwLTRkNDYtOGViNS00MDk4NjJlZTRjMmIvNDc4OGFjMzItMTI0MC00Mjg2LTg5MDItMmFkNjAxNmExMWRiIiwiaWF0IjoxNzAzODQ3NTIyLCJleHAiOjE3MDM5MzM5MjJ9.3_ODYpuaNasiIwOJiFkhmuX2JIVU1sMH457OfVpxgKk)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2846](https://linear.app/calcom/issue/CAL-2846/allow-creating-availability-at-team-and-user-level)</sub>

**Comment by emrysal** [comment]
I don't really see the reason for having availability on Team level 😕

**Comment by PeerRich** [comment]
i dont understand the reason to have that for teams and orgs either
