### ISSUE TITLE
Not able to setup the project locally

### ISSUE THREAD

**Issue by skushagra9** [calcom/cal.com#12964]
I am using ubuntu 
 after running yarn dx it is showing this error 
 my node version is the LTS, i.e 20.10.0
 
 if (typeof process !== "undefined" && typeof process.stderr?.write !== "function") {
@calcom/prisma:db-migrate:                                                                 ^
@calcom/prisma:db-migrate: 
@calcom/prisma:db-migrate: SyntaxError: Unexpected token '.'
@calcom/prisma:db-migrate:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
@calcom/prisma:db-migrate:     at Module._compile (internal/modules/cjs/loader.js:963:27)
@calcom/prisma:db-migrate:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
@calcom/prisma:db-migrate:     at Module.load (internal/modules/cjs/loader.js:863:32)

**Comment by PeerRich** [comment]
can you ask self-hosting questions in our discord? That's much likelier to get a solution than here 🙏

**Comment by skushagra9** [comment]
Ok
