### ISSUE TITLE
[CAL-2850] After reschedule Cal Video link is broken

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#12971]
Consistenly replicable after a reschedule

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2850](https://linear.app/calcom/issue/CAL-2850/after-reschedule-cal-video-link-is-broken)</sub>

**Comment by Vijaykv5** [comment]
Could you explain more about it

**Comment by Udit-takkar** [comment]
@hariombalhara can't reproduce. is this fixed?

<img width="612" alt="Screenshot 2024-01-02 at 1 12 10 PM" src="https://github.com/calcom/cal.com/assets/53316345/cc8ba83f-b875-434a-9179-0778bd05a931">

<img width="1512" alt="Screenshot 2024-01-02 at 1 12 24 PM" src="https://github.com/calcom/cal.com/assets/53316345/e7f2dabf-3b36-4ef3-bbde-13536b345285">

**Comment by Vijaykv5** [comment]
Can you assign the issue to me?

**Comment by Udit-takkar** [comment]
@Vijaykv5 yeah but are you able reproduce the bug?

**Comment by hariombalhara** [comment]
cc @alishaz-polymath
