### ISSUE TITLE
### Bug Report: "Go Home" Link Redirection Issue on Cal.com

### ISSUE THREAD

**Issue by abhiishekk02** [calcom/cal.com#12978]
### Issue Summary
The "Go home" link on the Cal.com website is not functioning as expected. Instead of redirecting to the home page on a single click, it redirects to an irrelevant page. Additionally, the link requires two clicks to initiate the redirection.

### Steps to Reproduce

1. Open the Cal.com website.
2. Add an arbitrary string or parameter to the end of the URL to trigger a 404 error page.
3. Navigate to the bottom of the page where the "Go home" link is located.

### Actual Results

- Clicking the "Go home" link redirects to an irrelevant page.
- The redirection occurs after two clicks instead of a single click.

### Expected Results

- Clicking the "Go home" link should immediately redirect users to the home page.
- The redirection should occur with a single click, providing a seamless user experience.

###Recording
https://github.com/calcom/cal.com/assets/80751160/c59d167f-b8cf-41a5-96fb-38fcbc1a3a52

**Comment by PeerRich** [comment]
i've already fixed this, should go live soon
