### ISSUE TITLE
[CAL-2851] Profile picture takes some time to load

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#12977]
Go to https://app.cal.com/event-types or cal.com/[username]

This sometimes take 5 - 10 seconds

https://github.com/calcom/cal.com/assets/53316345/8da50176-8c57-4b7f-b652-15f9189abab9

https://github.com/calcom/cal.com/assets/53316345/b109532a-5b96-4fa8-a040-2e366bfd7521

<sub>[CAL-2851](https://linear.app/calcom/issue/CAL-2851/profile-picture-takes-some-time-to-load)</sub>

**Comment by PeerRich** [comment]
i noticed the same @emrysal

**Comment by Shashank245** [comment]
Hey @PeerRich, @Udit-takkar I have made an attempt to resolve this issue both in event types page and user's profile page I have been able to test and check that the loading time of the profile image has significantly reduced. Please do let me know if there is any further change to be done. 

As this is my first open source contribution apologies for any steps that i missed out to work upon.

Thank you :)

**Comment by emrysal** [comment]
I'm going to handle this one; it's unfortunately a bit more complicated @Shashank245 - but I appreciate your effort; it's a very good first contribution! As an improvement you also shouldn't commit in your .env.example changes (this potentially leaked your environment)

Also try to never commit the yarn.lock file.

Code wise looks good, preload is a good way of approaching it (just not the right one in this situation)

**Comment by Shashank245** [comment]
@emrysal , Thank you for the acknowledgement!! I will surely take care of things you mentioned. Glad you liked the approach I used. Will Check out how you solve it, just so that I could learn more. Thank you..!!!
