### ISSUE TITLE
[CAL-3366] Avoid duplication of inline embed for same namespace

### ISSUE THREAD

**Issue by gitomit** [calcom/cal.com#12983]
### Issue Summary

On my website (https://disigner.nl/) I've implemented the Cal.com inline embed in a popup. The website is build with Wordpress and Elementor. In Elementor Popup builder the embed looks fine https://gyazo.com/0e6d4325c996ee662eef5d9e4bf21d96. But when I try it on the frontend on top of the embed there is a loading animation https://gyazo.com/3ec607bab36272e305750c44bd677f8c. When I go to the code it looks like the <cal-inline> loads 2 times. 

### Steps to Reproduce

Here is a video: https://gyazo.com/069619a002c97612ee4be32e2d2a8f2d

1. Pressed the yellow phone button in the header
2. A popup shows with 2 loading animations
3. The bottom animation loads but the top does not, which should not be there in the first place.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- 2 loading animations. It seems that somehow the <cal-inline> is implemented 2 times when looking at it in the front-end.

### Expected Results

- When pressing the popup the inline embed should load only 1 time.

### Technical details

- Wordpress 6.4.2
- Elementor 3.18.2
- Elementor Pro 3.18.1
- WP Rocket 3.15.6
- PHP version: 8.1.24

### Evidence
https://gyazo.com/069619a002c97612ee4be32e2d2a8f2d

<sub>[CAL-3366](https://linear.app/calcom/issue/CAL-3366/avoid-duplication-of-inline-embed-for-same-namespace)</sub>

**Comment by PeerRich** [comment]
can you show your code? my only explanation is that you copied the code twice. i cannot reproduce this

**Comment by gitomit** [comment]
This is the code I've used (https://gyazo.com/2b8625dfaee31b0805a0b68c470dbde3):

`
<div style="width:100%;height:100%;overflow:scroll" id="my-cal-inline"></div>
<script type="text/javascript">
  (function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; typeof namespace === "string" ? (cal.ns[namespace] = api) && p(api, ar) : p(cal, ar); return; } p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", {origin:"https://cal.com"});

  Cal("inline", {
	elementOrSelector:"#my-cal-inline",
	calLink: "disigner/kennismaking",
	layout: "month_view"
  });
  
  Cal("ui", {"theme":"light","styles":{"branding":{"brandColor":"#000000"}},"hideEventTypeDetails":false,"layout":"month_view"});
  </script>
  `
  
  Seems I can't copy the whole code for some reason (see screenshot for all the code).

**Comment by PeerRich** [comment]
weird i cant relpicat this. code looks fine. @hariombalhara any ideas?

**Comment by hariombalhara** [comment]
I think it's happening because the website flow executes the inline embed code twice(which happens as the HTML is re-inserted when the popup on the website opens). Though it should be avoided, we should handle it at our end as well.

See the code where jQuery is executing cal.com snippet.
![image](https://github.com/calcom/cal.com/assets/1780212/bc443a0e-3a2b-45f7-b5c9-fbee167f44ee)
