### ISSUE TITLE
Email notifs for bookings changes, etc

### ISSUE THREAD

**Issue by randomishwalk** [calcom/cal.com#12997]
### Is your proposal related to a problem?

Really annoying to have to monitor calendar to see when stuff is booked, moved, cancelled etc.

### Describe the solution you'd like

Have email notifs when something is booked/changed/etc

### Describe alternatives you've considered

Calendly does this nicely

### Additional context

n/a
### Requirement/Document

n/a

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
don't you get notifications from your calendar service like Google or Outlook?

We send email notifications whenever someone reschedules or cancels etc. You are not getting these?

Moving an event inside your own calendar wont notify us, thereby we cant send emails

**Comment by randomishwalk** [comment]
Hmm, it does not in Outlook I think? I just moved over to cal.com from Calendly--Calendly always used to send me an email notif when something got booked or moved. Don't think I ever had to configure it to do that? It was just the default setting / feature I think.
