### ISSUE TITLE
feat: mobile apps

### ISSUE THREAD

**Issue by randomishwalk** [calcom/cal.com#12995]
### Is your proposal related to a problem?

iOS mobile app would be really nice and convenient.

### Describe the solution you'd like

See above.

### Describe alternatives you've considered

PWA works fine for now.

### Additional context

Calendly has a nice iOS app as an example.

### Requirement/Document

Refer to Apple / iOS app store documentation for their libraries and the app store approval process.

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by SomayChauhan** [comment]
Don't forget your Android friends :full_moon_with_face:  

ps: love the idea of a app

**Comment by randomishwalk** [comment]
Yes 🙌. android too of course :)

**Comment by PeerRich** [comment]
what features would you want to see?

**Comment by PeerRich** [comment]
this is not an easy task and we will be very careful to not stretch ourselves too thin.

a mobile app basically means hiring an entire new small team to keep track of it

**Comment by randomishwalk** [comment]
Thanks @PeerRich! I think the minimum ought to be easy ability to copy-paste event invite links. The workflow would be open email client app (or messaging app) --> draft up message there asking for a meeting --> flip over to the Cal.com mobile app --> copy link to event type (ideally private event link but regular is fine too) --> flip back to email client or messaging app --> paste cal.com event invite link.

Totally understand though that building and maintaining a mobile app will require considerable resources, especially if you want it to be good.

Maybe a halfway plan is to simply have the bare (table stakes) minimum features needed? Like I don't think I'd need to be able to create *new* event types or even edit existing event types from the app--just want an easy way to copy-paste private event links.

All that being said, the iOS PWA works ok for now! This is more of a quality-of-life thing.
