### ISSUE TITLE
[CAL-2862] change "Dynamic" to "Group Meeting" and fix Meta and OG images

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13019]
before:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bc6ba6d0-2be4-4fa1-9325-c15b2f3be519/82dd548b-dd4e-4139-9eb8-980e7fe86f89?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iYzZiYTZkMC0yYmU0LTRmYTEtOTMyNS1jMTViMmYzYmU1MTkvODJkZDU0OGItZGQ0ZS00MTM5LTllYjgtOTgwZTdmZTg2Zjg5IiwiaWF0IjoxNzA0MzAxMDkxLCJleHAiOjE3MDQzODc0OTF9.W7VQCkjsbBO71BMvJ9tm2D3VRVPtw2i6yFAhElKHn6E)

After:

Title: Meet Cécile Veneziani & Nicolas Filzi
OG Image: "Group meeting"

add Description: Meet both Cécile Veneziani and Nicolas Filzi in a conference call.

also the booking page:

![CleanShot 2024-01-03 at 16 59 06@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/925d4f0d-670d-4a35-97ea-01fd052037b2/95cdca4e-f48f-4277-9098-43f03197c004?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MjVkNGYwZC02NzBkLTRhMzUtOTdlYS0wMWZkMDUyMDM3YjIvOTVjZGNhNGUtZjQ4Zi00Mjc3LTkwOTgtNDNmMDMxOTdjMDA0IiwiaWF0IjoxNzA0MzAxMTY2LCJleHAiOjE3MDQzODc1NjZ9.eni1oA0N4CfUFmstpIslZjWaQTZ5xLtHHNEy4RU-vVY)

if it's more than two people, it'll be:

* 3 people: Bailey Pumfleet, Peer Richelsen and John Doe.
* more than 3 people: Bailey Pumfleet, Peer Richelsen and 3 others

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2862](https://linear.app/calcom/issue/CAL-2862/change-dynamic-to-group-meeting-and-fix-meta-and-og-images)</sub>

**Comment by nfilzi** [comment]
Perfect 🔥
cc @cveneziani
