### ISSUE TITLE
[CAL-2863] Show tip of "Group Meetings" inside the app

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13020]
explain that you can do "+" between usernames for Group Meetings

<sub>[CAL-2863](https://linear.app/calcom/issue/CAL-2863/show-tip-of-group-meetings-inside-the-app)</sub>

**Comment by stylessh** [comment]
Can I get more context from this? 😄  @PeerRich

**Comment by Sahil-B07** [comment]
Need a clear desc :)

**Comment by Crosstons** [comment]
can you please elaborate?
