### ISSUE TITLE
[CAL-2864] Team availability slider overflow 

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#13023]
Slider has overflow at unconventional screen sizes 
https://github.com/calcom/cal.com/assets/55134778/6678eacd-4592-4b8a-a0c0-dbf36344ca11

<sub>[CAL-2864](https://linear.app/calcom/issue/CAL-2864/team-availability-slider-overflow)</sub>

**Comment by tejasdevani83** [comment]
Hi @sean-brydon, I changed some styles. Would you please review it?
<img width="837" alt="Screenshot 2024-01-03 at 8 05 11 PM" src="https://github.com/calcom/cal.com/assets/60130524/c853518c-076b-4c8c-b9b7-b5155db092f6">

**Comment by sean-brydon** [comment]
Hi thanks for your contribution- we need this to scroll and not wrap thanks!

**Comment by PeerRich** [comment]
will take this

**Comment by PeerRich** [comment]
fixed https://github.com/calcom/cal.com/assets/8019099/f6995149-074f-431b-a8a3-999870ddbfc1

**Comment by tejasdevani83** [comment]
@PeerRich Thank you.

**Comment by RajsekharPanda** [comment]
fixed the issue #13037
