### ISSUE TITLE
[CAL-2871] German Translation Issues

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#13035]
![CleanShot 2024-01-04 at 21.49.24@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/46ca5e7d-ed2e-4b7d-9871-5a928745f7d6/b87c565e-bb24-4c04-ac66-811878426371?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NmNhNWU3ZC1lZDJlLTRiN2QtOTg3MS01YTkyODc0NWY3ZDYvYjg3YzU2NWUtYmIyNC00YzA0LWFjNjYtODExODc4NDI2MzcxIiwiaWF0IjoxNzA0Mzc2MTc1LCJleHAiOjE3MDQ0NjI1NzV9.Px62eXYQBNsEa295W_K7uYza4tu7ZwojY9UdK4Ss9hI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2871](https://linear.app/calcom/issue/CAL-2871/german-translation-issues)</sub>

**Comment by PeerRich** [comment]
i am german and i dont see the issue here. what am i missing?

**Comment by shirazdole** [comment]
I'm not german and I don't know
