### ISSUE TITLE
[CAL-2877] Invalid Cal Video link on calendar event

### ISSUE THREAD

**Issue by FelixMalfait** [calcom/cal.com#13060]
I had a meeting today that appears in my Google Calendar and in [Cal.com](http://Cal.com)
But when I clicked on the calendar link it redirected me to a [app.cal.com](http://app.cal.com) link with:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7f87c95b-9b25-4153-b20b-e77afd8892f4/c207442d-921f-4101-9c34-bb0ad12d44d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83Zjg3Yzk1Yi05YjI1LTQxNTMtYjIwYi1lNzdhZmQ4ODkyZjQvYzIwNzQ0MmQtOTIxZi00MTAxLTljMzQtYmIwYWQxMmQ0NGQ2IiwiaWF0IjoxNzA0NDczMDgxLCJleHAiOjE3MDQ1NTk0ODF9.GQcR4X8wSyH-F1YzMOYqlOLIS5HZMM-az53tQXGsr5c)

When I clicked on "Join Cal Video" from the [cal.com](http://cal.com) UI it was actually a different link [https://meetco.daily.co/xxxx](https://meetco.daily.co/xxxx) which worked fine but the meeting attendee didn't get that link.

Thanks!

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2877](https://linear.app/calcom/issue/CAL-2877/invalid-cal-video-link-on-calendar-event)</sub>

**Comment by PeerRich** [comment]
by any chance was the event rescheduled or moved manyually?

**Comment by kart1ka** [comment]
If the concerned booking required confirmation, it might be related to the issue #12941. I've already addressed that issue with a PR #12944, although it's not yet live in production. Once it is, the Cal Video link problem should get resolved.

**Comment by FelixMalfait** [comment]
It was a booking that required confirmation and the guest rescheduled it so I had to confirm it twice. 
(I.e. it wasn't moved manually from Google Calendar but properly moved on their side via the Cal UI I believe)

Meeting URL I received in the confirmation email when I accepted the first time:
<img width="437" alt="Screenshot 2024-01-06 at 10 03 23" src="https://github.com/calcom/cal.com/assets/6399865/30722801-6ecb-4db9-8d7c-f421543f7e8b">

Meeting URL I received in the confirmation email when I accepted the second time:
<img width="446" alt="Screenshot 2024-01-06 at 10 04 07" src="https://github.com/calcom/cal.com/assets/6399865/4fb72075-ac53-4759-bfa4-2d8606fe2889">
New ID so a new event was created?
Meeting URL on the Google Calendar event was the same as in this confirmation email. Time of the event remained the same in this confirmation email.
But it returned "The meeting you're trying to join does not exist".

And here's the URL on daily.co that I could access from the dashboard and that worked:
<img width="995" alt="Screenshot 2024-01-05 at 17 03 02" src="https://github.com/calcom/cal.com/assets/6399865/f2f2cafd-7410-4564-b0cc-ce418d8b4e82">

So I'm not sure it's going to be fixed by #12944 - seems like it's something  different

**Comment by Udit-takkar** [comment]
hey @FelixMalfait this issue should be fixed by https://github.com/calcom/cal.com/pull/12944 and another PR that i opened yesterday https://github.com/calcom/cal.com/pull/13058 (that fixes this bug while rescheduling in require confirmation events).

**Comment by FelixMalfait** [comment]
Aah yes indeed probably #13058 will fix it! Closing issue. Thanks @Udit-takkar!
