### ISSUE TITLE
Drag Event Currently It Having A Button Which Is Little Bit Bad For UX 

### ISSUE THREAD

**Issue by kunaldevxxx** [calcom/cal.com#13067]
### Is your proposal related to a problem?

https://www.loom.com/share/77bde77b9bf54992b4baf270fd2c3b65?sid=e2405963-2bba-4dba-8150-430c113c04c6

We Can Do Drag Option Like By Holding On It Put Where He Want

### Describe the solution you'd like

implement a DraggableList component that uses react-dnd for drag-and-drop functionality.

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

Yes  https://react-dnd.github.io/react-dnd/docs/tutorial Here Is Documentation By Where We Can Implement it

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
we had a PR previously with drag and drop and didn't like it. will keep this for now. you dont reorder your events this often

**Comment by Airbornharsh** [comment]
I have solved this Should i make a PR for it

**Comment by Airbornharsh** [comment]
@PeerRich
