### ISSUE TITLE
Logo hover color change

### ISSUE THREAD

**Issue by pawansharma111104** [calcom/cal.com#13063]
How to reproduce-
1. Go on home page
2. Scroll to "SCHEDULING FOR COMPANIES AND EMPLOYEES OF"

Problem-
If we hover any company's name the color of logo doesn't change.
Solution-
On hovering color of logo should be changed to the original logo of company
Example screenshot-
Before hovering-
![image](https://github.com/calcom/cal.com/assets/68536005/0234d361-db64-471f-a131-737b7c2420b9)
After hovering-
![image](https://github.com/calcom/cal.com/assets/68536005/fb89cb0c-5c17-4de1-a17f-50c6bdf93122)

##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by moshiuzzaman** [comment]
Waiting for approval and UI design

**Comment by Somnath-sanu** [comment]
Can i start working on it??
**/needsApproval**

**Comment by PeerRich** [comment]
this is a design decision and not needed to be addressed
