### ISSUE TITLE
First timeslot delayed

### ISSUE THREAD

**Issue by austinbrown101** [calcom/cal.com#1306]
### Issue Summary

Depending on the length of the meeting, callendso sometimes has an arbitrary empty time from when the person is available to when a timeslot is offered.  

For example, person "test" is scheduled to have availability starting at noon, but for a 17min meeting, the first timeslot isn't offered until 12:11. Why the wasted 11min? The program seems to work just fine for 10, 15, and 30 min meetings, but I had a reason to do 25min meetings and sometimes the program was leaving 20min gaps when I want them back-to-back.

### Steps to Reproduce

1. Create a meeting with an arbitrary duration (not 10, 15, 30 or "standard" durations.
2. Go to the booking site and see that the next time available is not what would be expected.

### Technical details

- Browser version: Edge 96
- I'm self-hosting the docker version 

![startTime](https://user-images.githubusercontent.com/20783165/145972341-d6c723bd-1a8b-49c2-b6e5-8d2438249b79.jpg)
![avaliability](https://user-images.githubusercontent.com/20783165/145972344-65bd0eda-751f-41a1-815f-96f869d688de.jpg)

**Comment by PeerRich** [comment]
@emrysal is currently working on a new system that likely fixes this

**Comment by PeerRich** [comment]
i think this was fixed a log time ago
