### ISSUE TITLE
Sidebar is not aligned properly

### ISSUE THREAD

**Issue by riddhesh-mahajan** [calcom/cal.com#13081]
### Issue Summary

Sidebar has extra top margin.

<img width="960" alt="Extra Padding" src="https://github.com/calcom/cal.com/assets/40472653/726c98e7-ecc5-4698-9977-384865945da2">

### Steps to Reproduce

1. Login
2. Go to any page
3. Check sidebar top margin

**Comment by PeerRich** [comment]
oh this is new. will check

**Comment by PeerRich** [comment]
i cant reproduce this

**Comment by Utkarshn10** [comment]
I also tried reproducing it but couldn't

**Comment by riddhesh-mahajan** [comment]
@PeerRich @Utkarshn10 

I tried it in incognito mode, and everything looks good. I believe some Chrome extension is affecting the UI.

This issue seems to be only on my end.

Thank you for your time. I am closing this issue.
