### ISSUE TITLE
Book event api is accepting invalid start end values

### ISSUE THREAD

**Issue by riddhesh-mahajan** [calcom/cal.com#13086]
### Issue Summary

http://localhost:3000/api/book/event

Book event api is accepting any start end time. I can give first available slot as “start” and last available slot as “end”, It will create a single booking which will block the whole day.

Note: backend will throw error if start and end time is using different days. For example today’s start time and tomorrows end time.

```
const axios = require("axios");

// TODO: Update the data object with your own values
const data = {
  responses: {
    email: "free@example.com",
    name: "Free Example",
    guests: [],
  },
  user: "free",
  start: "2024-01-12T14:30:00+05:30",
  end: "2024-01-12T22:00:00+05:30",
  eventTypeId: 21,
  eventTypeSlug: "jj",
  timeZone: "Asia/Kolkata",
  language: "en",
  metadata: {},
  hasHashedBookingLink: false,
};

axios
  .post("http://localhost:3000/api/book/event", data, {
    headers: {
      "Content-Type": "application/json",
    },
  })
  .then((res) => {
    console.log(res.data.id);
  })
  .catch((err) => {
    console.log(err.response.data);
  });


```

Above event has 30 min duration per slot. But API allows to block all slots in a day with single API call.

In database all eventTypes are created with periodType as “UNLIMITED". This period types has no checks for out of bound period. You can check isOutOfBounds.tsk which is used in handleNewBooking.ts

Maybe someone from internal team can investigate this further.

**Comment by shravan20** [comment]
@PeerRich: May I pick this up if it is available?
