### ISSUE TITLE
[error] Error while setup: yarn dx

### ISSUE THREAD

**Issue by soham2k06** [calcom/cal.com#13117]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

While setting up the project, in the step of 'yarn dx' there is an error:
command (/Users/soham/Desktop/cal.com) yarn run env-check:common exited (1)

 Tasks:    1 successful, 3 total
Cached:    0 cached, 3 total
  Time:    3.242s 
Failed:    //#env-check:common

 **ERROR  run failed: command  exited (1)**
 
I also tried node version 17,18,19,20.
I have also set up posgres (supabase) and added it to .env

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- yarn version: 3.4.1
- Node.js version: tried 17,18,19,20

**Comment by PeerRich** [comment]
maige

**Comment by PeerRich** [comment]
maige please label this accordingly

**Comment by PeerRich** [comment]
do you have docker installed and running? also i never tried supabase postgres, i dont think you need that, just run yarn dx with docker running

**Comment by PeerRich** [comment]
can you ask self-hosting questions in discord? https://go.cal.com/discord

yarn dx works for me and many others
