### ISSUE TITLE
[CAL-2925] [feature] some of the buttons are not having loading animation while loading

### ISSUE THREAD

**Issue by soham2k06** [calcom/cal.com#13110]
### Is your proposal related to a problem?

Buttons 'update' located in appearance page are not having loading spinners while updating. It will be a good feature for user to show that your requested update is on progress.

### Describe the solution you'd like

Simply you will have isLoading state, use that to show loading spinners like other buttons.

### Requirement/Document

https://github.com/calcom/cal.com/assets/118199354/427b66b1-70d2-4219-8f17-a1f8c45146a9

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-2925](https://linear.app/calcom/issue/CAL-2925/[feature]-some-of-the-buttons-are-not-having-loading-animation-while)</sub>

**Comment by moulibrota-das** [comment]
Added the loading state to the buttons and forms. Fixes the problem.
