### ISSUE TITLE
[CAL-2883] Real time slot reservation system

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#13114]
### Is your proposal related to a problem?

In order to deal with the greatest amount of bookers; our slot reservation system has to be realtime - currently it's not and this allows for race conditions to occur during high traffic periods or incidental times when bookings are made between milliseconds of eachother.

<sub>[CAL-2883](https://linear.app/calcom/issue/CAL-2883/real-time-slot-reservation-system)</sub>

**Comment by alishaz-polymath** [comment]
Can we employ a booking queue system and simply reject the booking request in such cases? Potentially adds more processing time for the booking but could it be a decent solution? 🤔

**Comment by PeerRich** [comment]
i always thought what we had was in real time? i think only via API you can race condition it

afaik once you select a time, thats locked in
