### ISSUE TITLE
[CAL-2886] implement avatarapi.com to pre-fill avatars

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13121]
when making an account, we should prefill the avatar based on the email thats used to signup

![CleanShot 2024-01-09 at 15 24 18@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/33da36f2-e3a5-430f-945a-5bb6b331b76d/d69e3bd1-6a06-4319-be4e-fac8f92d3e62?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zM2RhMzZmMi1lM2E1LTQzMGYtOTQ1YS01YmI2YjMzMWI3NmQvZDY5ZTNiZDEtNmEwNi00MzE5LWJlNGUtZmFjOGY5MmQzZTYyIiwiaWF0IjoxNzA0ODEzODg0LCJleHAiOjE3MDQ5MDAyODR9.pg7HU34lIthIzZlehntIo7gGUCSeBkTStrb2qVKwtXQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2886](https://linear.app/calcom/issue/CAL-2886/implement-avatarapicom-to-pre-fill-avatars)</sub>

**Comment by Sashi-Bhumaraju** [comment]
hey! @PeerRich this is my first opensource contribution. 

I saw avatarapi.com  is paid, only limited number of api requests for free.
![image](https://github.com/calcom/cal.com/assets/90443391/2f72f016-b764-444f-ac1b-ecac74648c27)

please guide me on this.
