### ISSUE TITLE
Conferencing Apps for Dynamic Links on a Team Level

### ISSUE THREAD

**Issue by jornvandijk** [calcom/cal.com#13141]
We use cal.com mostly for easy scheduling meetings between team members such as:

1. https://cal.com/oscarcarlsson+katedonnellan/
2. https://cal.com/eelcolempsink+teresalynch/
3. https://cal.com/jornvandijk+jurre/

The first two use Cal Video while the latter uses Zoom (this is my default conferencing app).

- Everyone on the Framer team has Google Calendar enabled which should be the default instead of Cal Video. There is no way to set a default app for the entire team.
- Some people have manually set Zoom to be the default which should override the default preference.
- We don’t want to use Cal Video for these interviews (low usage)

**Comment by PeerRich** [comment]
i believe this is based on the first persons default video link
