### ISSUE TITLE
Can we have a specific address for sending invoice emails for teams?

### ISSUE THREAD

**Issue by mrchrisadams** [calcom/cal.com#13142]
### Is your proposal related to a problem?

My company has a dedicated email address for 3rd party platforms (incl. billing), so that invoices can be processed without relying on a specific user to forward invoices along to the correct address, or that user's account needing to exist indefinitely (if they switch jobs for example).

In some cases we end up needing to create a totally separate user called billing@my-company.com that our own finance staff sign in with for a service, but this feels like a pretty unsatifactory solution, compared to the value you get for actual users using the cal.com booking features.

### Describe the solution you'd like

In settings, for an team/organisation, we'd have the ability to specify an email address where invoices emails are sent to for our records. When an invoice is sent to the user account currently associated with the payment method, an copy of the email is sent to this email address too.

I'm referring to the following url path:

https://app.cal.com/settings/teams/XXXXX/billing

Which currently looks like this:

![Screenshot 2024-01-10 at 11 25 12](https://github.com/calcom/cal.com/assets/17906/19583647-8508-4e49-9855-c834bd0648dd)

My assumption here is that the team is the unit that accrues bills, a bit like how organisations might have an account associated with them to pay, rather than a single user having an account to pay.

### Describe alternatives you've considered

I've mentioned the option of creating a totally separate user. In large orgs it makes more sense, but for smaller teams, paying for an whole new seat, when we only use one very specific feature once a month makes the service less attractive compared other services.

### Additional context

There is some related work in #13031. I've also been in touch with support who were able to manually make a change with Stripe to send to an email address we specificy - this makes me think this would be somethign that could be built into the system in a self service fashion.

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
i am confused, can you not open the Billing portal (stripe) and change your email=

![CleanShot 2024-01-10 at 18 20 11@2x](https://github.com/calcom/cal.com/assets/8019099/f98e124e-c8f6-4ed1-b872-766bb372bd17)

**Comment by mrchrisadams** [comment]
Ah, I hadn't realised they were so loosely coupled - thanks for letting me know.

In my case, another member of staff had entered payment details for stripe, but I couldn't see them, nor the invoice history ( I think it might be linked to their user account, rather than the team, perhaps?)

I can see that I can log into the billing portal for my user account and change the billing address.

Based on this, I think the member of staff who originally set up the original payment details would need to edit the billing portal from _their_ account, to set a different billing address - it's not clear to me that me setting a new billing address would change anything.

![Screenshot 2024-01-10 at 19 38 00](https://github.com/calcom/cal.com/assets/17906/e2e6fd1b-e7b7-4caa-bb0a-4db28a8aa2bd)

Would me adding a new billing address from my account have any impact if the original payment details were added by someone else?
