### ISSUE TITLE
[CAL-2899] add booking date range filters and freeze GPT-4 version

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#13156]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2899](https://linear.app/calcom/issue/CAL-2899/add-booking-date-range-filters-and-freeze-gpt-4-version)</sub>

**Comment by adwait-godbole** [comment]
How can I read this issue ? Linear says I can't access the workspace.
