### ISSUE TITLE
Availability summary is not respecting the "Start of week" setting

### ISSUE THREAD

**Issue by piroux** [calcom/cal.com#13160]
### Issue Summary

Currently, although I have selected "Monday" as the first day of the week in the cal.com settings, the summary of any availability that sets some time available on a Sunday is going to use "Sunday" as the first day in the availability summary instead of "Monday".

### Steps to Reproduce

1. In the cal.com settings, set "Monday" as the first day of the week,
2. Create a new Availability,
3. For a simple example, choose the time window "06:00 - 21:00" for "Monday",
4. Copy this time window to the other days of the week,
5. Save,
6. At the top left of the page, below the Availability name, find the Availability summary.

### Actual Results

The summary of the Availability is:
`Sun - Sat, 06:00 - 21:00`.

### Expected Results

The summary of the Availability should be:
`Mon - Sun, 06:00 - 21:00`.

### Technical details

Beyond solving this issue for "Monday", please note that the "Start of week" setting lets the user choose any day of the week.

So if someone would select "Wednesday" as the first day of the week, one could expect the availability summary, in the case of having the same time window "06:00 - 21:00" selected for each day of the week, to actually look like:
`Wed - Tue, 06:00 - 21:00`

### Evidence

![Screenshot from 2024-01-10 19-20-43](https://github.com/calcom/cal.com/assets/438492/c6297b2d-111c-48e9-a5ad-8ebdfbf6016a)

**Comment by pawansharma111104** [comment]
I think it is resolved.
![image](https://github.com/calcom/cal.com/assets/68536005/36fcc545-b9bb-49f2-b915-2d92a6980d03)

**Comment by shubhampol56** [comment]
https://github.com/calcom/cal.com/assets/35174869/ad1a7d36-b63a-4e77-a97a-b7b727cb0777


Hello @PeerRich  and @piroux ,

I've taken the liberty to address the issue and have attached a video demonstrating the solution. Based on my understanding, I've formatted the summary of availability in what I believe to be the expected manner. 

If this aligns with your expectations, I've implemented the solution locally and have verified that it correctly displays the availability on both the "list of availability" and "availability" pages. 

I am eager to receive your feedback and confirmation at your earliest convenience.

Thank you for your time and consideration.

**Comment by piroux** [comment]
Hi @PeerRich 

While closing @shubhampol56 's attempt at fixing this localization issue in their mentioned PR, you might have inadvertently closed this issue here at the same time.

Could you reopen this issue as the problem is still present?
