### ISSUE TITLE
[CAL-2913] Improvements in instant meetings

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#13174]
- [X] Display team members pfp
- [X]  Add option to add webhook in Switch
- [X] a countdown of 60 seconds: "We’ll connect you within 60 seconds or find a date slot in the future in 45, 44, 43 etc.”
- [X] Afterwards: "Oops, we couldn't connect you this time. Please schedule a future call instead"
- [ ] royalty free lo-fi music
- [X] a mini game while waitiing? flappy birds or chrome dinosaur run?
- [X] lets block "closing tab" while waiting, i think there is a browser API to throw an alert when closing a tab
- [ ] lets play a sound when the "wait screen" turns into the video link and someone joins (some people change tab while waiting)

new:

> We are connecting you!
> Please schedule a future call if we're not available in XX seconds.

Then...

> Oops, we couldn't connect you this time.
> Please schedule a future call instead. We value your time.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2913](https://linear.app/calcom/issue/CAL-2913/improvements-in-instant-meetings)</sub>

**Comment by PeerRich** [comment]
also:
- lets block "closing tab" while waiting, i think there is a browser API to throw an alert when closing a tab
- lets play a sound when the "wait screen" turns into the video link and someone joins (some people change tab while waiting)

**Comment by Udit-takkar** [comment]
> lets play a sound when the "wait screen" turns into the video link and someone joins (some people change tab while waiting)

Browser required granting permission to play background sound
