### ISSUE TITLE
[bug] Navbar Button content is wrong while loading

### ISSUE THREAD

**Issue by soham2k06** [calcom/cal.com#13175]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In the very first page. It fetches for the auth data and show navigation bar's button as per authentication's status.
Whenever while fetching, button's content is 'Login' no matter user has logged in or not.

### Steps to Reproduce

1. Login to the cal.com website (if not already done)
2. Navigate to https://cal.com/
3. Reload the page
4. Notice button content of navigation bar

### Actual Results

It is showing wrong content while fetching.

### Expected Results

It should show loading indicator or skeleton.
Keep button hidden while loading (unpopular).

### Evidence

https://github.com/calcom/cal.com/assets/118199354/de102ab1-1bf9-4e01-ab72-3802fca7a44b

**Comment by yaswanthkosuru** [comment]
i want to solve these issue but  i cannot find the  code place folder.
 can any one help me finding folder in which the above page exists

**Comment by Ali7040** [comment]
assign it to me. I want to work on that issue.

**Comment by Krishcode264** [comment]
from my observations : during reloading the page , it  checks if user has alredy logged in or not if yes it directly puts "go to app " and if it doesnt found user info related previous login it puts " login ", 

so i dont think its an issue .

**Comment by soham2k06** [comment]
> from my observations : during reloading the page , it checks if user has alredy logged in or not if yes it directly puts "go to app " and if it doesnt found user info related previous login it puts " login ",
> 
> so i dont think its an issue .

Actually it is matter of what to show during fetching auth data.
There are 3 options during loading:
1. show default data (can be wrong)
2. show loader with content 'loading...'
3. don't show the whole button
