### ISSUE TITLE
Skeleton component fails to render when the loading state is true, resulting in a lack of visual indication for ongoing content loading.

### ISSUE THREAD

**Issue by omkarjagtap2212** [calcom/cal.com#13188]
### Issue Summary
Upon navigating to app.cal.com/apps, the sidebar contains navigation items such as Teams, Apps, Routing Forms, and Insights. Clicking on these components results in unresponsiveness, making it feel like the application is stuck. On the other hand, the same navbar contains components like Event Types, Bookings, Availability, and Workflow. Clicking on these components displays skeleton components, creating a noticeable contrast. It seems that Teams, Apps, Routing Forms, and Insights navbar components are missing skeleton components, impacting the user experience.

### Steps to Reproduce

1. Navigate to app.cal.com/apps.
2. Observe the side navbar for Teams, Apps, Routing Forms, and Insights.

### Expected Results

Upon visiting app.cal.com/apps and clicking on any of the navbar components (Teams, Apps, Routing Forms, Insights), users should not experience a feeling of being stuck. Implementing skeleton components or loading indicators when the loading state is true would enhance the user experience by providing visual feedback and indicating that the content is loading. This not only prevents frustration but also contributes to a smoother and more polished user interface. Consider incorporating this approach to improve the overall usability of the application.

### Technical details

-Operating System: Windows 11 (i5)
-Browsers:
1. Brave: Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (64-bit)
2. Google Chrome: Version 120.0.6099.216 (Official Build) (64-bit)
-Node.js Version: v20.10.0

### Evidence

-  I'm attaching a screen Recording 

https://github.com/calcom/cal.com/assets/93461504/2ec2b124-b841-4bb5-a0a4-030cbfbe51e2

**Comment by PeerRich** [comment]
Maige label this

**Comment by PeerRich** [comment]
we are moving these pages to App Router right now

**Comment by PeerRich** [comment]
and will be significantly faster afterwards
