### ISSUE TITLE
[CAL-2922] Block out 'Contact Support' at the bottom of the help card

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#13204]
It blocks out contact support for free users at the top, but still shows 'Contact Support' at the bottom:

![PNG image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6b564e69-e313-4f9b-883a-031daf014fac/0fa80245-998f-4546-8d05-8cae1c0b2e07?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82YjU2NGU2OS1lMzEzLTRmOWItODgzYS0wMzFkYWYwMTRmYWMvMGZhODAyNDUtOTk4Zi00NTQ2LThkMDUtOGNhZTFjMGIyZTA3IiwiaWF0IjoxNzA1MDc1NzU2LCJleHAiOjE3MDUxNjIxNTZ9.vYCD0pWP75yneUXzZ-l64aLomSpu3ZDoWGvQlpF31gU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2922](https://linear.app/calcom/issue/CAL-2922/block-out-contact-support-at-the-bottom-of-the-help-card)</sub>

**Comment by ameeetgaikwad** [comment]
I would like to contribute @baileypumfleet

**Comment by vishal9708** [comment]
Hi @baileypumfleet, can you assign me or is there a PR open..?

**Comment by VenkateshSircilla123** [comment]
how to reproduce?

**Comment by PeerRich** [comment]
dome
