### ISSUE TITLE
1-on-1 appears by event types unnecessarily, causing confusion

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#1320]
### Issue Summary

As a user of cal.com, I see '1-on-1' appears by each event type despite additional guests enabled, causing confusion and clutter on the booking screen.

### Steps to Reproduce

1. Create an event type without any team members 
2. Ensure 'allowing additional guests' is enabled.
3. Observe the confusing & unnecessary '1-on-1' label by the event type on the dashboard and booking page.

**Comment by ConnorGargano** [comment]
Hi @ChipWolf 
Thank you for raising this, I will get this passed over to our engineering team now for you

**Comment by ChipWolf** [comment]
> Hi @ChipWolf Thank you for raising this, I will get this passed over to our engineering team now for you

Hey @ConnorGargano any chance of an update here? Thanks :)

**Comment by ChipWolf** [comment]
@PeerRich event types that have guest invitations disabled do not show the badge to indicate they are for 1 person
