### ISSUE TITLE
[CAL-2926] Perma Signup + Join Team Invite Link Broken

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#13220]
Signup link with token doesn’t seem to work.

E.g. this link worked in early December: [https://app.cal.com/signup?token=0fa4e780ef9596510f84e18e987436dc39481045b1873b38b4a8260ba1a4bfe9&callbackUrl=/getting-started](https://app.cal.com/signup?token=0fa4e780ef9596510f84e18e987436dc39481045b1873b38b4a8260ba1a4bfe9&callbackUrl=/getting-started)

But returns 404 now:

![CleanShot 2024-01-15 at 13.07.14@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9a48b9c-0cad-43bf-84b9-3e4e8c529475/569f83bd-c6b4-4414-9bdf-6ba8696ac6ea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lOWE0OGI5Yy0wY2FkLTQzYmYtODRiOS0zZTRlOGM1Mjk0NzUvNTY5ZjgzYmQtYzZiNC00NDE0LTliZGYtNmJhODY5NmFjNmVhIiwiaWF0IjoxNzA1Mjk1MjQyLCJleHAiOjE3MDUzODE2NDJ9.MEsDAXXKX2RnaBIRJI_0cw9ZK2vzfkX0SiSf1UZd0Y4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2926](https://linear.app/calcom/issue/CAL-2926/perma-signup-join-team-invite-link-broken)</sub>

**Comment by iprime2** [comment]
@shirazdole can you please provide me steps to reproduce this issue?
