### ISSUE TITLE
[CAL-2930] Org branding isnt centered in shell

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#13225]
![CleanShot 2024-01-15 at 21.58.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e56535ae-a4ef-4e94-bf77-7a52851df856/6e073bdf-e1d1-4de3-8c20-8aa707992eab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNTY1MzVhZS1hNGVmLTRlOTQtYmY3Ny03YTUyODUxZGY4NTYvNmUwNzNiZGYtZTFkMS00ZGUzLThjMjAtOGFhNzA3OTkyZWFiIiwiaWF0IjoxNzA1MzA5MDk2LCJleHAiOjE3MDUzOTU0OTZ9.XfgEO-Gzsto-PWbTwfoxgcEB8s0OJuIC_fERopnjm4o)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2930](https://linear.app/calcom/issue/CAL-2930/org-branding-isnt-centered-in-shell)</sub>

**Comment by aditya-armal** [comment]
I'm eager to take this issue as it perfectly aligns with my skills. I'm excited about the opportunity to contribute meaningfully.

**Comment by MarcinMaciejewski12** [comment]
Hello, can I help you with this one? :)

**Comment by sean-brydon** [comment]
> I'm eager to take this issue as it perfectly aligns with my skills. I'm excited about the opportunity to contribute meaningfully.

Brilliant - we dont assign issues just tag us in the PR and we will review <3

**Comment by Krishcode264** [comment]
hello , actually i cant see org branding logo
![Screenshot 2024-01-15 144501](https://github.com/calcom/cal.com/assets/114551368/ca414805-4815-4876-93eb-088c221d7b92)

**Comment by sean-brydon** [comment]
You need to visit `https://localhost:3000/settings/organizations/new` to create a new organization then follow the onboarding steps

**Comment by Krishcode264** [comment]
thank you for help
