### ISSUE TITLE
[CAL-2928] Insights on Orgs may be Down

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#13222]
![CleanShot 2024-01-15 at 14.53.59@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/353d27d0-e64c-4645-982b-c6210c01d3ce/6d14c76b-3870-4a28-88ce-f0597366471e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zNTNkMjdkMC1lNjRjLTQ2NDUtOTgyYi1jNjIxMGMwMWQzY2UvNmQxNGM3NmItMzg3MC00YTI4LTg4Y2UtZjA1OTczNjY0NzFlIiwiaWF0IjoxNzA1MzAxNjU5LCJleHAiOjE3MDUzODgwNTl9.Ln7MFurqje2X89tFrpwTd8_hwU5oLavL5PpmWkj54qg)

Insights on Orgs for both myself and @alishaz-polymath isn't working

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2928](https://linear.app/calcom/issue/CAL-2928/insights-on-orgs-may-be-down)</sub>

**Comment by keithwillcode** [comment]
This was fixed when we changed the default timespan to 7 days.
