### ISSUE TITLE
[CAL-2935] ability to add duration behind dynamic plus links (i.e.: i.cal.com/peer+bailey/90)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13233]
right now we offer people 3 options:

* 15min
* 30min
* 1 hour

as a default for: [https://i.cal.com/peer+bailey](https://i.cal.com/peer+bailey)

![CleanShot 2024-01-15 at 13 41 22@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b6dc7e58-21c5-42a7-a13d-20636695824a/599cce7d-a255-495e-9304-982d67366d4b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iNmRjN2U1OC0yMWM1LTQyYTctYTEzZC0yMDYzNjY5NTgyNGEvNTk5Y2NlN2QtYTI1NS00OTVlLTkzMDQtOTgyZDY3MzY2ZDRiIiwiaWF0IjoxNzA1MzI2MzQ4LCJleHAiOjE3MDU0MTI3NDh9.hCImQRFn2581ikoF_LK4b5eVcLy-W2aYhXI6hGYrBcU)

it would be nice, that if you put /15 /90 or /120 etc. it would **force** that duration and remove the other options:

example:

## [i.cal.com/peer+bailey/90](http://i.cal.com/peer+bailey/90)

duration: 1 hour 30 mins

![CleanShot 2024-01-15 at 13 44 29@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/89e0e75d-5f03-4d72-8bbd-bdf206b4dbd2/86c3704c-7182-4f67-b852-c3c82a8b0d52?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84OWUwZTc1ZC01ZjAzLTRkNzItOGJiZC1iZGYyMDZiNGRiZDIvODZjMzcwNGMtNzE4Mi00ZjY3LWI4NTItYzNjODJhOGIwZDUyIiwiaWF0IjoxNzA1MzI2MzQ4LCJleHAiOjE3MDU0MTI3NDh9.0o_BZl3iW7Sbw9MEd8kHAtyQpeJlvL9QVjWpzQC6BYs)

## [i.cal.com/peer+bailey/15](http://i.cal.com/peer+bailey/15)

duration: 15

etc. etc.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2935](https://linear.app/calcom/issue/CAL-2935/ability-to-add-duration-behind-dynamic-plus-links-ie)</sub>

**Comment by Krishcode264** [comment]
do we also want to enable feature by which users can add custum duration rather than just  15/30/60 ?

**Comment by nerd500** [comment]
@PeerRich Do we want the user to be able to select any time, or are we enforcing specific time, like {15, 20, 30, 45, 60, 90, 120} etc?
Also, does this issue also cover the feature for the host, to enforce what length of meeting they allow to be scheduled?

**Comment by reubence** [comment]
> @PeerRich Should users only change the booking duration by modifying the URL?

Good point, if users make the change we can either >
- force show it if it's part of the default options
- if not, then just show the default options
