### ISSUE TITLE
[CAL-2975] Allow impersonation from the /settings/admin/users page.

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#13240]
### Is your proposal related to a problem?

We have a clear list of users, and then a seperate impersonation page, where we type in the user?

![CleanShot 2024-01-17 at 13 09 23@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8ae90389-bff0-4e3b-8b92-8e57d81ff2df/ea7ddd32-f138-49eb-bfec-9cda48e18332?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84YWU5MDM4OS1iZmYwLTRlM2ItOGI5Mi04ZTU3ZDgxZmYyZGYvZWE3ZGRkMzItZjEzOC00OWViLWJmZWMtOWNkYTQ4ZTE4MzMyIiwiaWF0IjoxNzA1NjcwNzY4LCJleHAiOjE3MDU3NTcxNjh9.qyYkV-Uy9-Etvy6E3H5bhpaDSZ0FuBx69tcOK-WdJDQ)

Why are these not just tied together? and/or better yet, inside the dropdown for the edit/lock/etc.

### Describe the solution you'd like

Add impersonation to the dropdown on the users row of /settings/admin/users
(Describe your proposed solution here.)

### Describe alternatives you've considered

Could just put the impersonation on this page?

---

##### House rules

* If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  * For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  * Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2975](https://linear.app/calcom/issue/CAL-2975/allow-impersonation-from-the-settingsadminusers-page)</sub>

**Comment by PeerRich** [comment]
yup that is smart and should be easy
