### ISSUE TITLE
[CAL-2953] Cal.com 3.7.0 docker image not available

### ISSUE THREAD

**Issue by kolaente** [calcom/cal.com#13242]
Pulling the `calcom/cal.com:v3.7.0` docker image results in this error:

```
Error response from daemon: manifest for calcom/cal.com:v3.7.0 not found: manifest unknown: manifest unknown
```

This is a constant issue, not only with this release. Docker images are either published very late or not at all.

<sub>[CAL-2953](https://linear.app/calcom/issue/CAL-2953/calcom-370-docker-image-not-available)</sub>

**Comment by PeerRich** [comment]
this not working? https://github.com/calcom/docker/releases/tag/v3.7.0

**Comment by keithwillcode** [comment]
I see the issue why it's having problems pushing to Docker Hub. Will fix

**Comment by alishaz-polymath** [comment]
The issue was fixed and v3.7.9 docker image is now available

**Comment by kolaente** [comment]
@alishaz-polymath This is a problem again with the v3.7.14 release

**Comment by xcellentavi** [comment]
@keithwillcode I see that docker hub has not pushed an update in 17 days.  Currently showing v3.9.1 (https://hub.docker.com/r/calcom/cal.com/tags) but v3.9.5 was released 2 days ago.  Is there a better way to alert if updates are not being added to the repo or should we just keep asking here if it isn't appearing after some time?  Sorry to bother and thank you for your help!

**Comment by xcellentavi** [comment]
@keithwillcode @PeerRich  Still not seeing the newer containers on docker hub, stuck at v.3.9.1 and now I see v3.9.7 was published.  Reported on the docker repo as well: https://github.com/calcom/docker/issues/338

If anyone has an update or explanation, please feel free to share, thank you!

**Comment by alishaz-polymath** [comment]
Hey @xcellentavi we're currently looking into it. There's an issue in the install step that we've been facing and are actively trying to sort out. As soon as that's sorted, we will update here 🙏

**Comment by julianortlieb** [comment]
Any updates?

**Comment by xcellentavi** [comment]
@alishaz-polymath, @keithwillcode, @PeerRich, I'm just tagging in case this fell off anyone's radar. We are now over two months and 15 releases behind on Docker Hub (https://hub.docker.com/r/calcom/cal.com/tags). Please let us know if more progress has been made to get the images working again. I very much appreciate all your time and effort, and thankfully, nothing is broken running on v 3.9.1.

Thank you!

**Comment by xcellentavi** [comment]
@keithwillcode, since this is marked closed, I hope that means the problem has been fixed and we will see the new updates on docker soon.  Thank you!
