### ISSUE TITLE
[CAL-2974] Missing <title> on a bunch of pages.

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#13241]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A lot of pages don't have a <HeadSeo> set and therefore default to Cal.com | Cal.com.
Pages are listed below.
Pages: 

- [ ] bookings, 
- [ ] availability, 
- [ ] teams, 
- [ ] apps, 
- [ ] routing-forms, 
- [ ] workflows and 
- [ ] insights.

### Steps to Reproduce

Go to any of the pages listed and look at the title, it's just Cal.com | Cal.com

### Actual Results

Cal.com | Cal.com

### Expected Results

Bookings | Cal.com
Availability | Cal.com 
etc...

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

Just looking.

<sub>[CAL-2974](https://linear.app/calcom/issue/CAL-2974/missing-title-on-a-bunch-of-pages)</sub>

**Comment by VishalMCF** [comment]
Can this issue be taken up? It does not have any tags.

**Comment by PeerRich** [comment]
agree. lets also remove all of the t("key_string") from Title and Description and always use English here
