### ISSUE TITLE
[CAL-2943] Update deprecated property from Vital in the App Store

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#13255]
Got this email from the Vital team:

> This is the final reminder that the field \`*source*\` is supersede by \`*provider*\` throughout our API and Webhooks payloads.
>
> We will remove the former by the end of this week.

Link to the docs [https://docs.tryvital.io/wearables/providers/resources#sleep-stream](https://docs.tryvital.io/wearables/providers/resources#sleep-stream)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2943](https://linear.app/calcom/issue/CAL-2943/update-deprecated-property-from-vital-in-the-app-store)</sub>

**Comment by shekharkalshetti** [comment]
can i work on this?

**Comment by keithwillcode** [comment]
@shekharkalshetti sure thing. We’ll have a look if you open a PR!
