### ISSUE TITLE
[CAL-2959] Booking time slot issue

### ISSUE THREAD

**Issue by Harsh4999** [calcom/cal.com#13269]
So we allow 4 seats in a booking and each booking slot is of 20 minutes. Now the issue is lets say the slots are from 4:40am-5:00am then consecutively 5:00am-5:20am and so on. Now the issue its also allowing 4:50am-5:10am slots. Why is it allowing booking slot between an ongoing slot. As there is already an ongoing slots from 4:40-5:00 then it should not allow booking from 4:50-5:10.

In screenshot you can see there are already slots booked from 4:40-5:00 but when I open a scheduling page it allows me booking from 4:50-5:10. How to stop this?

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e4c9a47a-15be-45f7-a50b-a856a96ceace/bd48e4d0-e120-4e78-b739-2fc17383325e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNGM5YTQ3YS0xNWJlLTQ1ZjctYTUwYi1hODU2YTk2Y2VhY2UvYmQ0OGU0ZDAtZTEyMC00ZTc4LWI3MzktMmZjMTczODMzMjVlIiwiaWF0IjoxNzA1NTc2MTY0LCJleHAiOjE3MDU2NjI1NjR9.YWlVtXrfUogIGcepRFpfSrDB2HjKD3TPnQQzoz3kMQo)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8f832162-27e0-40da-a462-acd8e9b89eea/31b0a71d-2bee-4ca3-9b83-d8e35ccf7710?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84ZjgzMjE2Mi0yN2UwLTQwZGEtYTQ2Mi1hY2Q4ZTliODllZWEvMzFiMGE3MWQtMmJlZS00Y2EzLTliODMtZDhlMzVjY2Y3NzEwIiwiaWF0IjoxNzA1NTc2MTY0LCJleHAiOjE3MDU2NjI1NjR9.g5oUuziCGE6uEG_c8IY9UUHEoVRm-hsGv_6weiinYI0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2959](https://linear.app/calcom/issue/CAL-2959/booking-time-slot-issue)</sub>

**Comment by Utkarshn10** [comment]
Have picked this up.

**Comment by Utkarshn10** [comment]
Hey @Harsh4999 I can see in the screenshots the booking are for 16th January while the 4:50-5:10am slot is for 17th January. As far as I know that shouldn't be a problem.

**Comment by Harsh4999** [comment]
Hey @Utkarshn10 so as you can see in the bookings page screen shot there are 2 consecutive slots within 10 minutes gap whereas I have kept slot length as 20 minutes. So why is it allowing a new slot to start in midst of another slot going on.

So as first slot if from 10:10am-10:30am the next slot should be from 10:30am-10:50am  right?

<img width="1405" alt="Screenshot 2024-01-18 at 8 57 34 AM" src="https://github.com/calcom/cal.com/assets/69167510/cf8b0f0b-7299-40cb-bc5d-ea9badc8e75a">

**Comment by Utkarshn10** [comment]
I see. What were the steps that led to this? Could you please state them.

 I tried creating an event with 20 min duration but this didn't happen.
![image](https://github.com/calcom/cal.com/assets/58587256/dac48223-2df1-4693-a545-a2db2c940375)

**Comment by Harsh4999** [comment]
We have configured the event normally but there can be a thing which may lead to this that our slots almost get booked out every day so you may try booking out an event full on a specific time in your cal.com event and then re-check the scheduling page with different device it may show you post 10 min slots.

These are our configuration for event just for reference:
<img width="1209" alt="Screenshot 2024-01-18 at 9 38 38 AM" src="https://github.com/calcom/cal.com/assets/69167510/f813e7ba-72e5-4065-81b0-b5ca0bf9cf2c">
<img width="1209" alt="Screenshot 2024-01-18 at 9 38 51 AM" src="https://github.com/calcom/cal.com/assets/69167510/affc85ef-c457-4d15-8d50-72669e1447f7">
<img width="1209" alt="Screenshot 2024-01-18 at 9 39 02 AM" src="https://github.com/calcom/cal.com/assets/69167510/a62b7d2c-099a-4842-8b26-f18c631350b2">
<img width="1209" alt="Screenshot 2024-01-18 at 9 39 08 AM" src="https://github.com/calcom/cal.com/assets/69167510/09d1272d-e6cc-4174-8894-51a5ebeb0c7c">
