### ISSUE TITLE
[CAL-2945] Time range wrong in OOO feature

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#13268]
![Screenshot 2024-01-16 at 3.56.25 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/93883a7d-ece1-4740-bf50-7bb19038c85c/db52c06a-f2e9-4ee2-bd0f-80c6deb6ede5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85Mzg4M2E3ZC1lY2UxLTQ3NDAtYmY1MC03YmIxOTAzOGM4NWMvZGI1MmMwNmEtZjJlOS00ZWUyLWJkMGYtODBjNmRlYjZlZGU1IiwiaWF0IjoxNzA1NDM4NjE4LCJleHAiOjE3MDU1MjUwMTh9.m3c0IFpcyXa2VLCGwjgsvqPKDSoDLKOodx8c9WTd-Iw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2945](https://linear.app/calcom/issue/CAL-2945/time-range-wrong-in-ooo-feature)</sub>

**Comment by Mishra-Pravin** [comment]
@CarinaWolli May I work on fixing this bug?

**Comment by CarinaWolli** [comment]
Hey @Mishra-Pravin, I am already working on resolving this
