### ISSUE TITLE
Cal.com - video blur effects issue on cal.com native video desktop web app

### ISSUE THREAD

**Issue by randomishwalk** [calcom/cal.com#13263]
### Issue Summary

When using Cal.com's video calling on desktop, it seems like the "soft blur" and "strong blur" effects don't work properly. Normal video is fine, but the moment I turn on "blur", my video just shuts off?

### Steps to Reproduce

1. Click into cal.com video call link
2. Click on "effects"
3. Click "soft blur" or "strong blur"

### Actual Results

Video shuts off completely when attempting to use "blur"

### Expected Results

Should blur my background with the video being functional

### Technical details

- cal.com v1.6.0
- Windows 11 pro
- Browsers tried: Brave and Edge

### Evidence

- Happy to screen share. Just let me know best way to contact you all over email

**Comment by PeerRich** [comment]
will forward this to daily.co who built the cal video infrastructure

**Comment by randomishwalk** [comment]
thanks @PeerRich!
