### ISSUE TITLE
[CAL-2951] [API] [/webhooks] [POST] Event Triggers in Webhooks API are now broken after last PR.

### ISSUE THREAD

**Issue by anthonybdev** [calcom/cal.com#13260]
Hey, everyone, please fix this ASAP.

### Issue Summary

After some PR's made to Webhooks API this week, eventTriggers body param is not working. So I'm unable to POST a webhook to my event type with specified eventTriggers anymore. Last time I tested it and it was woking correctly was of 4th of January 2024.
I've investigated what's changed in this [PR](https://github.com/calcom/cal.com/commit/fbc3f7b51fd325ddfc9dc13fdeb6db1645ec9452) and I think `eventTriggers` are not in the body of `args.data.eventTriggers` on line 95 anymore, because of the desctructuring made on line 72.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f1e6039a-6574-4f20-ba10-2062ccb6e67b/a0994430-8e7b-4276-b27c-dbb98abf491c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMWU2MDM5YS02NTc0LTRmMjAtYmExMC0yMDYyY2NiNmU2N2IvYTA5OTQ0MzAtOGU3Yi00Mjc2LWIyN2MtZGJiOThhYmY0OTFjIiwiaWF0IjoxNzA1NDk2NDcxLCJleHAiOjE3MDU1ODI4NzF9.CDOBCQk20wB-3h5LadCBKMD5bbfYWHsmmmSFwCaqaK8)

### Steps to Reproduce

1. Create new event type
2. Find the id of the event type using REST API
3. Make POST request to `https://api.cal.com/v1/webhooks?apiKey=YOUR_API_KEY` with event triggers array in body 
   `{ "eventTypeId":  561712, "subscriberUrl": "https://test.com3", "eventTriggers": ["BOOKING_CREATED", "BOOKING_CANCELLED", "BOOKING_RESCHEDULED"], "active": true }`

### Actual Results

* I'm receiving empty eventTriggers prop and empty list of events to be triggered in my Dashboard.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/31c1ef6e-b1a1-48fa-8e25-42ad5de91a7c/b083c6df-d8e2-4420-8cc9-c659dd9f10cc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMWMxZWY2ZS1iMWExLTQ4ZmEtOGUyNS00MmFkNWRlOTFhN2MvYjA4M2M2ZGYtZDhlMi00NDIwLThjYzktYzY1OWRkOWYxMGNjIiwiaWF0IjoxNzA1NDk2NDcxLCJleHAiOjE3MDU1ODI4NzF9.80-LvDcIKi5mb6qQIxcl2na5TPZr5AGl4NLIucHtisQ)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0d2813d0-50b9-441a-9659-6081cf27de64/967c8534-7f96-4347-a64f-0896cdf51ff7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wZDI4MTNkMC01MGI5LTQ0MWEtOTY1OS02MDgxY2YyN2RlNjQvOTY3Yzg1MzQtN2Y5Ni00MzQ3LWE2NGYtMDg5NmNkZjUxZmY3IiwiaWF0IjoxNzA1NDk2NDcxLCJleHAiOjE3MDU1ODI4NzF9.ulvKJRJcUR1pjJhU-LAE993Pm7LhCzM3wXWd6QenHa8)

### Expected Results

* It should parse eventTriggers prop in request body and return it as well.

### Technical details

* Postman
* Node.js

### Evidence

It was tested in POSTMAN and using my dev env in Node.js with Axios.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2951](https://linear.app/calcom/issue/CAL-2951/[api]-[webhooks]-[post]-event-triggers-in-webhooks-api-are-now-broken)</sub>

**Comment by Udit-takkar** [comment]
cc: @sean-brydon

**Comment by amanzrx4** [comment]
Hey, fixed it in #13312 . could you check please
