### ISSUE TITLE
Pre-fill not working on website embeds

### ISSUE THREAD

**Issue by danielcharrua** [calcom/cal.com#13288]
### Issue Summary

Pre-fill not working on website embeds.

### Steps to Reproduce

1. Embed calendar on wordpress website
2. Included URL parameters (same as using the calendar at cal.com)

I thought embeds worked with URL parameters to pre-fill fields but no.
Also would be nice to customize the `name` parameter because on WordPress the parameter `name` is a reserved one.

### Actual Results

Embeds calendars seem to not uspport pre-filling.

### Technical details

The tested URL was formed like:
https://domain.com/20min/?email=manuel@domain.com

**Comment by devanmolsharma** [comment]
I will work on it if it's fine

**Comment by PeerRich** [comment]
you would need to pass the parameters into your embed with some custom javascript. should be quiet easy depending on your framework

**Comment by danielcharrua** [comment]
@PeerRich is there any docs pointing on how to pass the parameters with Javascript when using embed as HTML?
Thank you.

**Comment by danielcharrua** [comment]
Found them here, thanks! 
https://cal.com/docs/core-features/embed/prefill-booking-form-in-embed#inline-embed
