### ISSUE TITLE
[CAL-3060] JSON Error during login  due to incorrect encoding on CALENDSO_ENCRYPTION_KEY

### ISSUE THREAD

**Issue by jdalrymple** [calcom/cal.com#13290]
### Issue Summary

After a fresh install, I go to login and after about 20 seconds, i see this error pop up in the login screen:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7674c8fe-1726-40f2-85e4-9087cd601839/c8a506d1-d81c-4146-968c-bde64031612b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83Njc0YzhmZS0xNzI2LTQwZjItODVlNC05MDg3Y2Q2MDE4MzkvYzhhNTA2ZDEtZDgxYy00MTQ2LTk2OGMtYmRlNjQwMzE2MTJiIiwiaWF0IjoxNzA2NzE0OTM0LCJleHAiOjE3MDY4MDEzMzR9.-wAXHUh7h1RGFLrMtld2tMTfoQBnQ2k9nFk6ZmKXBII)

Note related issues: #9527 #9690
Original issue: [https://github.com/calcom/docker/issues/321](https://github.com/calcom/docker/issues/321)

### Steps to Reproduce

1. Setup repository locally and generate template .env file as per the [instructions](!%5Bimage%5D(https://github.com/calcom/cal.com/assets/3743662/340d8c50-2485-4da1-996b-07e8c36649ec))
2. Update the .env file to use a secret generated by this command as described in the [comments](https://github.com/calcom/cal.com/blob/e99e8b169afe72e188a56f8ecb7c7e82335a1043/.env.example#L92) for the CALENDSO_ENCRYPTION_KEY env variable

```
openssl rand -base64 32
```

1. spin up docker containers via `docker compose up -d`
2. Login
3. Be greeted by this banner 'You are admin but you do not have a password length of at least 15 characters or no 2FA yet Change Password to gain admin access'
4. Attempt to setup twofactor auth and receive error messages shown in images below

### Actual Results

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/913de513-d0fb-4cce-9c64-a5f471e3b0bd/8ee46aae-3805-4b37-85f9-a128e228ee82?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MTNkZTUxMy1kMGZiLTRjY2UtOWM2NC1hNWY0NzFlM2IwYmQvOGVlNDZhYWUtMzgwNS00YjM3LTg1ZjktYTEyOGUyMjhlZTgyIiwiaWF0IjoxNzA2NzE0OTM0LCJleHAiOjE3MDY4MDEzMzR9.6c9ib5TrH8Mq6ZrOMlI6Nc9ingTIwdJ_87kyjoJM2ns)

### Expected Results

Not have issues with the encryption key.

### Technical details

*Environment:*

Hosting service: GCP e2-small
OS: Debian Bullseye
Docker Images: see [docker compose](https://github.com/calcom/docker/blob/main/docker-compose.yaml) file

*Config:*

I kept the defaults from here, however ive updated the NEXT_PUBLIC_WEBAPP_URL to be my own domain.

### Evidence

This was tested using the docker containers outlined above, both locally and in the cloud to limit any additional sources of error.

Here are my findings in the order in which i found them:

**update 1**

I do see this error in the browser console:

```
Error setting up two-factor authentication SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data two-factor-auth-5a03d5ad2d4dbd78.js:1:5962
handleSetup NextJS
```

**update 2**

It looks like the fetch call to '...api/auth/two-factor/totp/setup' is returning an internal server error, which then sends back the JSON error when the response.json() function is called.

**update 3**

Default config is outdated. The newer config file makes sure to specify the length of the encryption key:

```
# Application Key for symmetric encryption and decryption
# must be 32 bytes for AES256 encryption algorithm
# You can use: `openssl rand -base64 32` to generate one
CALENDSO_ENCRYPTION_KEY=
```

**update 4**

So even changing the key to a 32 byte key using the algo mentioned above, the error still persists:

```
: RangeError: Invalid key length
@calcom/web:start:     at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
@calcom/web:start:     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
@calcom/web:start:     at new Cipheriv (node:internal/crypto/cipher:249:3)
@calcom/web:start:     at Object.createCipheriv (node:crypto:141:10)
@calcom/web:start:     at symmetricEncrypt (/calcom/apps/web/.next/server/chunks/69559.js:1:278)
@calcom/web:start:     at handler (/calcom/apps/web/.next/server/pages/api/auth/two-factor/totp/setup.js:1:2125) {
@calcom/web:start:   code: 'ERR_CRYPTO_INVALID_KEYLEN'
```

**update 5**

Doing some local testing with the touched code, it looks like the base64 encoding of the string generated through openssl rand -base64 32 command, is failing when converting into a buffer which sets the encoding to latin1, resulting in a 44 length string, not 32. This is what causes the error.

**update 6**

Temporary solution would be to just create a 32 character long alphanumeric string without the openssl function, and updating the docs/comments to reflect the importance of this, seeing as the Buffer.from function expects the string to be binary/latin1 encoded

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3060](https://linear.app/calcom/issue/CAL-3060/json-error-during-login-due-to-incorrect-encoding-on-calendso)</sub>

**Comment by PeerRich** [comment]
thank you for the detailed report.

i think you can get some self hosting help in our community: https://go.cal.com/discord

**Comment by amandesai01** [comment]
So what is the fix? I just finished setting up this and facing same issue. Unable to gain admin access since it requires 2FA

**Comment by tomquas** [comment]
if i understand correctly, a fix has been provided already with #13484 but has been declined by the dev team for the greater goal of #12698.
that may make sense, but us docker self-hosters now have to wait till release 4.1+ for a working system. personally, i think it would have been the right thing to apply and deploy the fix and not render the self-hosted version unusable. 

i also found that https://hub.docker.com/r/calcom/cal.com/tags is pretty outdated – 3.9.8 was just released, 3.9.1 is available on docker hub. just thinking loud...

**Comment by lucasjohnston** [comment]
To be super clear this means the current `calcom` build is effectively broken for new set-ups, as you can't login as an admin without configuring 2FA. Feels like there should be an interim fix here given the severity of impact?

**Comment by lucasjohnston** [comment]
As a short-term fix, I'd propose changing the `CALENDSO_ENCRYPTION_KEY` generation instructions from:
```
openssl rand -base64 32
```
to
```
python -c "import random; import string; print(''.join(random.choices(string.ascii_letters + string.digits, k=32)))"
```

It'll fill the gap temporarily given the current command doesn't work, and I think it's reasonable to assume most users have python installed :)

**Comment by mgopic18** [comment]
if someone in year 2026 coming for this issue. read @lujstn  comments python -c "import random; import string; print(''.join(random.choices(string.ascii_letters + string.digits, k=32)))". you killed it bro

**Comment by Steven-baron** [comment]
Thanks @lujstn 

For anyone stuck with the admin warning banner that doesn’t go away even after changing the password, these are the steps that worked for me.

1. Generate a strong encryption key

I generated a random 32-character key:

python -c "import random, string; print(''.join(random.choices(string.ascii_letters + string.digits, k=32)))"

2. Set the encryption key in .env

Add the generated value to your environment variables:

CALENDSO_ENCRYPTION_KEY=your_generated_key_here


(After changing this, restart the app.)

3. Enable Two-Factor Authentication (2FA)

Go to Settings → Security

Set up Two-Factor Authentication

Complete the setup

4. Log out and log back in

After enabling 2FA:

Log out completely

Log back in again

After doing this, the admin security banner disappeared for me.
