### ISSUE TITLE
[CAL-2960] default event-types after creating a team

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13300]
right now, a team starts without event-types:

![CleanShot 2024-01-18 at 13 08 09@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d6e1f657-17b4-4648-9c7a-f9e88b464135/f1ced02d-eaec-43d8-8595-4afdd24e1b79?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kNmUxZjY1Ny0xN2I0LTQ2NDgtOWM3YS1mOWU4OGI0NjQxMzUvZjFjZWQwMmQtZWFlYy00M2Q4LTg1OTUtNGFmZGQyNGUxYjc5IiwiaWF0IjoxNzA1NTgzMzQ1LCJleHAiOjE3MDU2Njk3NDV9.koGM4WGbSTLtycOl2eHq3F581dpJbQnY_5waOs3QS9k)

we should make some generic event-types as a starter:

* Collective
* Round Robin
* 30min (managed event type?)

we could also ask a few questions during team creation and have templates

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2960](https://linear.app/calcom/issue/CAL-2960/default-event-types-after-creating-a-team)</sub>

**Comment by Utkarshn10** [comment]
Hey @PeerRich after creating a Team we are showing these options in `Teams` tab. We can show similar modal option to create the event type before creating a team as **Step 3** here:

![image](https://github.com/calcom/cal.com/assets/58587256/994fa004-8ea6-4c54-a606-2889a603a695)


Modal contains `event type` options:
![image](https://github.com/calcom/cal.com/assets/58587256/81ec67dc-833e-45d0-81bc-f461da94c19c)
