### ISSUE TITLE
[CAL-2972] Back button on the booking page is not working properly

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13324]
[https://www.loom.com/share/69d30529b3e44b8dae7e9953ab5ba9d7?sid=010987a8-55d9-4832-ac1d-2db8dfbd5b14](https://www.loom.com/share/69d30529b3e44b8dae7e9953ab5ba9d7?sid=010987a8-55d9-4832-ac1d-2db8dfbd5b14)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2972](https://linear.app/calcom/issue/CAL-2972/back-button-on-the-booking-page-is-not-working-properly)</sub>

**Comment by PeerRich** [comment]
more


> When a customer goes to my [cal.com](http://cal.com/) link, your the site does two or three redirects. So when they hit the back button, it doesn't do anything. 
> 
> I like a lot of things on [cal.com](http://cal.com/) more than calendy, but I switched back for now because of this. Just thought I'd like yall know!
> 
> Thanks

**Comment by walkonmars36** [comment]
Hi, I am also having this issue. I am building a site in Astro and I am linking to my calendar on cal.com and then redirecting to a success page on booking. This would be fine, but if a user decides against making a booking for whatever reason then it's taking around 5 or 6 clicks of the back button to get back to my site. I could open the calendar in a new tab of course, but this is not ideal and I don't want to embed as I'd rather not have a cookie notice.

Hopefully you can find a solution soon as I love the app 👏

Thanks
Mark

**Comment by milospuac** [comment]
@Udit-takkar @PeerRich do we have an ETA on this?

**Comment by PeerRich** [comment]
![CleanShot 2024-04-16 at 11 25 32@2x](https://github.com/calcom/cal.com/assets/8019099/715e5c05-9f5a-44bf-a4b4-ac1f9d4c4b98)

**Comment by Udit-takkar** [comment]
> @Udit-takkar @PeerRich do we have an ETA on this?

I'll try to finish it this week

**Comment by ayusham001** [comment]
Hi @milospuac, 
Can I work on it?

**Comment by syedbarimanjan** [comment]
> /attempt #13324 Is this up for grabs? @PeerRich @Udit-takkar @milospuac
> 
> Options

@PeerRich @Udit-takkar
