### ISSUE TITLE
[CAL-2973] Not able to install apple calendar

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#13328]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Reported on discord

> I am having trouble connecting my calendar to the Apple app calendar. The process is not proceeding as expected, and I am still waiting for completion. Could you please find a solution for me to be able to connect my calendar on Cal.com to my iPhone’s calendar? Thank you in advance for your assistance.

https://discord.com/channels/1125390093386010654/1125390093386010657/1197807388720369696

<sub>[CAL-2973](https://linear.app/calcom/issue/CAL-2973/not-able-to-install-apple-calendar)</sub>

**Comment by alishaz-polymath** [comment]
This error shows up when one uses their Apple Password instead of **app-specific password**. They need to create an app-specific password to use here, and that should work
![image](https://github.com/calcom/cal.com/assets/52925846/7c694ba2-35df-42a7-b2f5-dfdf8e78e501)
