### ISSUE TITLE
[CAL-2976] Hubspot installed but can't be activated in the apps section

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13332]
It doesn't show up in the Apps section of the event type settings

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5bb4f4db-bb38-40db-b71f-2e3341ef44f4/be687e55-0a3b-4346-9479-6edbb49d5dbc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81YmI0ZjRkYi1iYjM4LTQwZGItYjcxZi0yZTMzNDFlZjQ0ZjQvYmU2ODdlNTUtMGEzYi00MzQ2LTk0NzktNmVkYmI0OWQ1ZGJjIiwiaWF0IjoxNzA2MDE4MjI0LCJleHAiOjE3MDYxMDQ2MjR9.ES5di0LzHiZyVbMc8LVw2Qk-WPs6ZxAp8A4_9S9LbHc)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/745e56d7-7e7b-4f58-a11e-f2db75a3975e/768226ff-acbf-4c20-ab25-21564fd3d51d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83NDVlNTZkNy03ZTdiLTRmNTgtYTExZS1mMmRiNzVhMzk3NWUvNzY4MjI2ZmYtYWNiZi00YzIwLWFiMjUtMjE1NjRmZDNkNTFkIiwiaWF0IjoxNzA2MDE4MjI0LCJleHAiOjE3MDYxMDQ2MjR9.04agKW84OPA5m0my9dFRyA9JZvCPZtMeamG_aPIUbN0)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4e481fc6-1a9f-4a8d-bdac-7da994f26ace/e60a09cf-01ee-4e0e-bbdd-6db057b183e7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80ZTQ4MWZjNi0xYTlmLTRhOGQtYmRhYy03ZGE5OTRmMjZhY2UvZTYwYTA5Y2YtMDFlZS00ZTBlLWJiZGQtNmRiMDU3YjE4M2U3IiwiaWF0IjoxNzA2MDE4MjI0LCJleHAiOjE3MDYxMDQ2MjR9.hWfvWjje218uZuxcTzFddk8Lxd7iyG6_5WCKTERb_e0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2976](https://linear.app/calcom/issue/CAL-2976/hubspot-installed-but-cant-be-activated-in-the-apps-section)</sub>

**Comment by Amit91848** [comment]
https://github.com/calcom/cal.com/blob/95e037c664d119b8a5d2cdec99bd33264e8f9797/packages/app-store/hubspot/_metadata.ts#L5-L20

Many apps like hubspot doesn't have extendsFeature: "EventType" like many other apps in its _metadata.ts or config.json


So it gets filtered out here

https://github.com/calcom/cal.com/blob/95e037c664d119b8a5d2cdec99bd33264e8f9797/apps/web/components/eventtype/EventAppsTab.tsx#L21-L24

Not sure what extendsFeature exactly does though, some other apps are also not shown. Should I add it just for hubspot?
