### ISSUE TITLE
cal link aliases to keep track of the source

### ISSUE THREAD

**Issue by alexbit-codemod** [calcom/cal.com#13348]
### Problem

I want to share my cal link for 15-min event type in different places. but i wish i could have different link aliases for that event type so i can keep track of who is coming from which source. e.g. if imagine i have two cal link aliases like:
https://cal.com/alexbit/15min-landing-page
https://cal.com/alexbit/15min-github

and both of these links are related to one event type like this: https://cal.com/alexbit/15min

so once the user submits a meeting for me, i know from which link they have created that invite.

### Describe the solution you'd like

When I set an event type, let me create different link aliases (just like how in google workspace, for a given user you can create different email aliases)

### Describe alternatives you've considered

the alternative is to duplicate event types. the problem with that is:
1. makes my cal landing page ugly and crowded.
2. if i want to change something in one event type, i need to do the same in all the other duplicates too.

### Additional context
this is nice to have.
maybe this setting could be in the advanced settings.

**Comment by PeerRich** [comment]
consider adding a "Booking question" and prefill it like this: 

https://i.cal.com/peer/meet?source=Github&duration=15

![CleanShot 2024-01-23 at 13 52 42@2x](https://github.com/calcom/cal.com/assets/8019099/958d0efd-4344-4a98-a30e-c9f86f47a6b8)
