### ISSUE TITLE
Name query string leading to 404 on WordPress after redirect

### ISSUE THREAD

**Issue by basislockhart** [calcom/cal.com#13346]
### Issue Summary

When setting up the redirect on successful booking, one of the queries passed is `name`, which conflicts with WordPress [reserved terms](https://codex.wordpress.org/Reserved_Terms).

### Steps to Reproduce

Going to this page: https://keyspanish.com/private-tutoring/trial/confirmation/?name=Cangis+Kan&email=gahekom814%40konican.com&user=keyspanish&type=trial&isSuccessBookingPage=true&email=gahekom814%40konican.com&eventTypeSlug=trial&title=Spanish+Trial+Lesson%3A+Cangis+Kan+%E2%AC%8C+Alejandro&description=Test&startTime=2024-01-22T11%3A30%3A00.000Z&endTime=2024-01-22T12%3A00%3A00.000Z&location=integrations%3Agoogle%3Ameet

Leads to 404. However, changing `name` to `name1` solves the issue.

This seems to happen when there's only one event with a redirect configured, when adding more, the `name` query is not longer passed and it works. However, the scheduler name does not seem to be in any queries...

**Comment by basislockhart** [comment]
It seems this happens when I pass on the query name myself to Cal.com, which then passes it to the confirmation page. If you could change the identifier from `name` to `names` I think it will solve the issue.

**Comment by PeerRich** [comment]
i am not quiet sure if i understand where this change should happen. also can you not just have two event types as mentioned?

**Comment by basislockhart** [comment]
> i am not quiet sure if i understand where this change should happen. also can you not just have two event types as mentioned?

Cal.com has the identifier name, so if I want to pass a query I need to use that in the URL, which in turn leads to a 404 on any WordPress site on redirect. And no, having 2 events does not fix the issue.

![image](https://github.com/calcom/cal.com/assets/73283871/1f94936f-65e8-482c-aa5a-a378e6985a58)
