### ISSUE TITLE
[CAL-2993] Organization dashboard uses https://cal.com for team links if the `organization` is unpublished

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#13357]
(Attachment: )

Created via Threads. See full discussion: [https://threads.com/34561286474](https://threads.com/34561286474)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2993](https://linear.app/calcom/issue/CAL-2993/organization-dashboard-uses-httpscalcom-for-team-links-if-the)</sub>

**Comment by asadath1395** [comment]
@hariombalhara I am trying to reproduce this, this is what i am seeing, am i in the wrong screen
![image](https://github.com/calcom/cal.com/assets/37188392/134a22d4-7b60-4319-be92-8efdb2190738)
