### ISSUE TITLE
Make Cal Desktop app usable with self-hosted instance

### ISSUE THREAD

**Issue by CodeShakingSheep** [calcom/cal.com#13353]
### Is your proposal related to a problem?

I want to use Cal Desktop app with my self-hosted Cal instance. This seems not possible at the moment as I can only login against Cal.com server.

### Describe the solution you'd like

I could imagine two possible approaches.

1. Add a menu entry under File
A menu entry named "Preferences" or "Settings" should be added under "File" menu entry above "Check for updates". When clicking on it, there should be the option to specify the server URL in a text field and a button to save it. If an URL is entered and saved there, Cal Desktop app authenticates a user against the specified server.
![image](https://github.com/calcom/cal.com/assets/19874562/a95f6909-aa03-472d-b3cd-b4d2fae088dd)

2. Add a button in login screen
Another possible solution would be to add a third button "Sign in to another server" in the login screen. When clicking on it, another text field "Server URL" should appear above "Email address" field. f an URL is entered there, Cal Desktop app authenticates a user against the specified server.
![image](https://github.com/calcom/cal.com/assets/19874562/902ac6ff-0245-4f62-855a-be103674c4c4)

### Describe alternatives you've considered

Using the web app.

### Additional context

None.

### Requirement/Document

None.

**Comment by PeerRich** [comment]
you can build your own desktop app with https://todesktop.com

**Comment by PeerRich** [comment]
we cant specify another URL in the settings unfortunately
