### ISSUE TITLE
[CAL-3003] Cal Video does not work in 3.7.3

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#13368]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Caused by https://github.com/calcom/cal.com/pull/13184.

TypeError: Cannot read properties of undefined (reading 'endTime')

### Steps to Reproduce

1. Run v3.7.3 and go to a Cal video link

<sub>[CAL-3003](https://linear.app/calcom/issue/CAL-3003/cal-video-does-not-work-in-373)</sub>

**Comment by zomars** [comment]
Solved by https://github.com/calcom/cal.com/commit/ffcb04fa99d4f7987724741ef3d5624159108a08 I suppose
