### ISSUE TITLE
[CAL-3006] after renaming username, redirect to your previous username

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13372]
- only the previous one

example:

cal.com/peer-richelsen -> cal.com/peer-rich -> cal.com/peer 

would free up cal.com/peer-richelsen again

<sub>[CAL-3006](https://linear.app/calcom/issue/CAL-3006/after-renaming-username-redirect-to-your-previous-username)</sub>

**Comment by heathhenley** [comment]
This would be useful also for teams, when I created our team I called it `teamname-product-dev` but we want to switch to just `teamname` and have the invite links that were already sent still work
