### ISSUE TITLE
[CAL-3009] Wrap up the User automatic provisioning PR

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#13378]
[https://github.com/calcom/cal.com/pull/11169](https://github.com/calcom/cal.com/pull/11169)
cc @peer

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3009](https://linear.app/calcom/issue/CAL-3009/wrap-up-the-user-automatic-provisioning-pr)</sub>

**Comment by compgeniuses** [comment]
hurrey, so looking forward to this..

**Comment by PeerRich** [comment]
@compgeniuses we work on our own time-tables. thank you for the patience
