### ISSUE TITLE
Change start time

### ISSUE THREAD

**Issue by lantai5** [calcom/cal.com#13380]
I have a 50 min event.. I want to edit the start time to always be at 10 past the hour. Is it possible? I can't find a way.

![image](https://github.com/calcom/cal.com/assets/157572214/8a58c547-c0e1-4d74-b278-3a1f30274e82)

**Comment by PeerRich** [comment]
have you tried using the interval set to 10 min?
 
![CleanShot 2024-01-24 at 11 32 30@2x](https://github.com/calcom/cal.com/assets/8019099/b2bb4bc0-e5d7-42c8-ae89-ac059f265a7d)
