### ISSUE TITLE
[CAL-3021] still not published on npm

### ISSUE THREAD

**Issue by LarsArtmann** [calcom/cal.com#13398]
12327 fix a compiler error, unfortunately it's still not published on npm.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bc7648f3-0616-4cff-a086-b7c0b15983bb/fc9ca7bd-60e1-4a1c-8aa6-a8917ef50eef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iYzc2NDhmMy0wNjE2LTRjZmYtYTA4Ni1iN2MwYjE1OTgzYmIvZmM5Y2E3YmQtNjBlMS00YTFjLThhYTYtYTg5MTdlZjUwZWVmIiwiaWF0IjoxNzA2MTc1MzU4LCJleHAiOjE3MDYyNjE3NTh9.I6AECp53Afj47FFZ8CdAg_pVmXNT1m08lSU92oW3D1M)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3021](https://linear.app/calcom/issue/CAL-3021/12327-still-not-published-on-npm)</sub>

**Comment by PeerRich** [comment]
looking into this

**Comment by LarsArtmann** [comment]
@EnriqCG unfortunately version 1.3.1 never got published to npm.
But it seems like 1.3.2 has it.
https://www.npmjs.com/package/@calcom/embed-react?activeTab=versions

Did you try version 1.3.2?

**Comment by Ghawas1981** [comment]
This version is deprected, please install v1.1.0+ which is also on this list

stremio://ea627ddf0ee7-shluflix.baby-beamup.club/manifest.json

**Comment by EnriqCG** [comment]
> But it seems like 1.3.2 has it.

Yup, I confirm 1.3.2 has the types. Thanks for the help. I should have checked the latest version before posting, but I figured it was still a thing as this was still open and part of the [v4.0 milestone](https://github.com/calcom/cal.com/milestone/47).
