### ISSUE TITLE
[CAL-3042] Odd behavior on copy and on changing calendar

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#13417]
### Issue Summary

if you change to a specific google calendar
you save
and you reload the page
=> the specific calendar is gone and the default calendar of the account is selected

This behavior is occuring on Cloning a eventtype too and creating a mess!
Since you do not think about that if you clone some fields are changed to something else

the bad thing: this was working in the past!

### Steps to Reproduce

default case:
1. ensure to have a google calendar from another account on which you have got full permissions
2. on an event type, select this specific calender
3. save it
4.  go to a different event type
5. reload the prior event type
6. you see that your account calender is now selected and the specific is not anymore

this same behavior occurs if you do a clone of a event type

### Actual Results

- see above

### Expected Results

- the user selected calendar will never be changed automatically
- on clone the identical calendar is selected also for the new cloned

### Technical details

- Browser independent

### Evidence

- via UI

<sub>[CAL-3042](https://linear.app/calcom/issue/CAL-3042/odd-behavior-on-copy-and-on-changing-calendar)</sub>

**Comment by milospuac** [comment]
reported here #13419
