### ISSUE TITLE
Guests rescheduling under identity of original/main scheduler

### ISSUE THREAD

**Issue by kuriosdoulos** [calcom/cal.com#13412]
Might be a design question/decision, so will leave it for others to decide, but wanted to report.  Thanks!!

### Issue Summary

When an invite is created by an "Original booker" and includes guests, a guest can click the link in the invite to reschedule (which is fine), BUT the rescheduling cal.com page that loads presents them as if they are the **original/main scheduler** (and adding themselves again as a guest).  Perhaps this is the intended behavior, but the greyed-out field names say "Your name" and "Email address" -- implying that's you.  Maybe just a matter of changing those fields to be "Main scheduler" or whatever language makes sense?  Otherwise appears that the guest is impersonating the original scheduler in the scheduling process (which I don't believe is the case).

### Steps to Reproduce

1. Create invite with a guest
2. Have guest click "Reschedule" in the confirmation email they receive
3. Observe the greyed-out fields naming the original/main scheduler as "Your name"... when it is the guest that at that moment is accessing the invite to reschedule [see pic attached].

### Technical details

- Firefox 121.0.1 (64-bit) 

### Evidence
![image](https://github.com/calcom/cal.com/assets/31422238/3292994f-16e0-4f71-8f0a-ff283ec5ba65)

**Comment by PeerRich** [comment]
i dont think this is possible yet, since the name is being identified by the link and both host and guest have the same link

**Comment by PeerRich** [comment]
for now this is a technical limitation unless we send a unique link per guest, and thats not really possible when sharing the same calendar invites
