### ISSUE TITLE
[CAL-3030] Attendee doesn't get an updated confirmation after rescheduling/canceling a team event

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13418]
Attendee doesn't get an updated confirmation after rescheduling/canceling [https://www.loom.com/share/84ea9ed8711b40f58260d43037a5bef8?sid=c52240fe-d0c1-4a14-9e62-7557cdb26250https://www.loom.com/share/84ea9ed8711b40f58260d43037a5bef8?sid=c52240fe-d0c1-4a14-9e62-7557cdb26250](https://www.loom.com/share/84ea9ed8711b40f58260d43037a5bef8?sid=c52240fe-d0c1-4a14-9e62-7557cdb26250https://www.loom.com/share/84ea9ed8711b40f58260d43037a5bef8?sid=c52240fe-d0c1-4a14-9e62-7557cdb26250)

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=33fb4163-c3f1-4e1b-92ac-04afa0836809](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=33fb4163-c3f1-4e1b-92ac-04afa0836809)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3030](https://linear.app/calcom/issue/CAL-3030/attendee-doesnt-get-an-updated-confirmation-after)</sub>

**Comment by MehulZR** [comment]
Not able to reproduce in a non-org environment.
