### ISSUE TITLE
[CAL-3045] Overlay Calendar forces scheduler to create a Cal.com account AND still doesn't take them back to the original scheduling link

### ISSUE THREAD

**Issue by kuriosdoulos** [calcom/cal.com#13415]
### Issue Summary

Overlay Calendar forces scheduler/invitee to create a [Cal.com](http://Cal.com) account -- including going through the *entire* setup process (picking username, calendar link, work/available hours, integrating calendar screen, etc.) AND still doesn't take them back to the original scheduling link, which is the reason scheduler was there in the first place.

### Steps to Reproduce

1. Send an invite link
2. Have another account try to Overlay calendar by clicking on toggle in top right
3. Observe shown "Welcome back" screen (regardless of whether actually returning) as a sign-in screen
4. Click "Sign in with google"

### Actual Results

* step 4 above takes the invitee/scheduler through all the hoops possible (making new [Cal.com](http://Cal.com) account, fully configuring it, etc.), and never actually takes them back to the calendar of the person that invited them.

### Expected Results

* After step 4 above, should directly proceed to the Google sign-in and Google approval screens so familiar for granting access -- without requiring all the extra [cal.com](http://cal.com) account steps or even creation of a [cal.com](http://cal.com) account at all
* Then after google approval/sign-in, should immediately be taken back to scheduling from the page that originally took the person to [cal.com](http://cal.com) (to schedule something)

Not sure if the current flow is purposeful, to increase user account #s, but if it is, it'll only lead to a more frustrating user experience... so fewer actual *active* and *return* users -- and fewer recommendations and referrals.

### Technical details

* Firefox 121.0.1 (64-bit) as well as Microsoft Edge Version 120.0.2210.144 (Official build) (64-bit)

### Evidence

in progression:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/06a1ccfe-9d82-49d6-a5f1-bf84e43ff61d/d7eddb03-373a-4463-a52e-84618044e7fa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wNmExY2NmZS05ZDgyLTQ5ZDYtYTVmMS1iZjg0ZTQzZmY2MWQvZDdlZGRiMDMtMzczYS00NDYzLWE1MmUtODQ2MTgwNDRlN2ZhIiwiaWF0IjoxNzA2NTM0NTc2LCJleHAiOjE3MDY2MjA5NzZ9.LUPY4bcv-Iov2qqvofq-uFAEVNCgksgKbeM70CeCcjA)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d96fcaec-26e6-4edc-a57b-6c5217b922d9/d49280b1-11e8-45ff-a6a6-68f0d8a45f9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kOTZmY2FlYy0yNmU2LTRlZGMtYTU3Yi02YzUyMTdiOTIyZDkvZDQ5MjgwYjEtMTFlOC00NWZmLWE2YTYtNjhmMGQ4YTQ1ZjljIiwiaWF0IjoxNzA2NTM0NTc2LCJleHAiOjE3MDY2MjA5NzZ9.y7L9FccRg7cidBXid_gE8UfqiSTt-kTVZrVNIvCq-vs)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1a99ca7a-77d5-4c8d-959d-a7042b531a4b/e4f7433e-d2f5-482f-bb23-b48d27c472ab?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xYTk5Y2E3YS03N2Q1LTRjOGQtOTU5ZC1hNzA0MmI1MzFhNGIvZTRmNzQzM2UtZDJmNS00ODJmLWJiMjMtYjQ4ZDI3YzQ3MmFiIiwiaWF0IjoxNzA2NTM0NTc2LCJleHAiOjE3MDY2MjA5NzZ9.AhAg7O-I_A_U24TvlJQisbLcKN1rD49wcogqD1RPrJw)

after account created, just stays in this new account's dashboard:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e3f9089d-1d20-44f4-95fb-be52a3f491bb/f9c1da08-b235-47ae-b89c-c9068a96bc07?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lM2Y5MDg5ZC0xZDIwLTQ0ZjQtOTVmYi1iZTUyYTNmNDkxYmIvZjljMWRhMDgtYjIzNS00N2FlLWI4OWMtYzkwNjhhOTZiYzA3IiwiaWF0IjoxNzA2NTM0NTc2LCJleHAiOjE3MDY2MjA5NzZ9.YbLeQYyam1cKPKoDR7ntcUhM9y6-d7RbMKXs5qY5OJE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3045](https://linear.app/calcom/issue/CAL-3045/overlay-calendar-forces-scheduler-to-create-a-calcom-account-and-still)</sub>

**Comment by PeerRich** [comment]
I agree this behaviour is rather unfriendly for people without accounts. we wanna improve this very soon!

**Comment by TyceHerrman** [comment]
This is the same as #12763 right?

**Comment by CarinaWolli** [comment]
> This is the same as #12763 right?

Yes, same as 'Overlay my calendar v2'
