### ISSUE TITLE
[CAL-3034] move "make organistion private" settings into "General"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13421]
the settings is hard to find for larger organisations (its at the bottom)

![CleanShot 2024-01-26 at 12 57 50@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ad4b74d1-6982-4694-b064-da888359bc04/13a574b2-f37c-4277-b535-ee399d4f7081?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hZDRiNzRkMS02OTgyLTQ2OTQtYjA2NC1kYTg4ODM1OWJjMDQvMTNhNTc0YjItZjM3Yy00Mjc3LWI1MzUtZWUzOTlkNGY3MDgxIiwiaWF0IjoxNzA2MjczOTQwLCJleHAiOjE3MDYzNjAzNDB9.d2S5XGzIXeA-Yb0cgNbC4LACMZkwgQYvzqLOVvbgQ9Q)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3034](https://linear.app/calcom/issue/CAL-3034/move-make-organistion-private-settings-into-general)</sub>

**Comment by khushalmajoka** [comment]
> the settings is hard to find for larger organisations (its at the bottom)
> 
> ![CleanShot 2024-01-26 at 12 57 50@2x](https://camo.githubusercontent.com/7d21664d4dca666ff7444cc47d59ff36bdb2105316ccf5e8e120f41b703a0412/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f61643462373464312d363938322d343639342d623036342d6461383838333539626330342f31336135373462322d663337632d343237372d623533352d6565333939643466373038313f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c3255344e6d4a6d4f5455334c5751344d6d59744e4459315a5331694d6a41314c54457a4e5455314f575930596a59794d7939685a4452694e7a526b4d5330324f5467794c5451324f545174596a41324e43316b595467344f444d314f574a6a4d4451764d544e684e546330596a49745a6a4d33597930304d6a63334c5749314d7a55745a57557a4f546c6b4e4759334d4467784969776961574630496a6f784e7a41324d6a637a4f5451774c434a6c654841694f6a45334d44597a4e6a417a4e4442392e6432533558477a495865412d59623063674e6243344c41434d5a6b77675159767a714c4f56766267513951)
> 
> From [SyncLinear.com](https://synclinear.com) | [CAL-3034](https://linear.app/calcom/issue/CAL-3034/move-make-organistion-private-settings-into-general)

@PeerRich  The image is not Visible, Can the issue be defined more clearly.

**Comment by khushalmajoka** [comment]
Are you talking about this switch?

<img width="600" alt="image" src="https://github.com/calcom/cal.com/assets/56840292/358c34fb-bf5a-4474-8519-acb99960e7ea">

**Comment by PeerRich** [comment]
##13693

**Comment by CarinaWolli** [comment]
fixed with https://github.com/calcom/cal.com/pull/13693
