### ISSUE TITLE
Issue with @calcom/embed-react: Calendar Functionality Not Working as Expected

### ISSUE THREAD

**Issue by peter-palmer** [calcom/cal.com#13428]
### Description
I am currently experiencing an issue with the `@calcom/embed-react` package in my React application. Despite following the official documentation, the calendar functionality is not working as expected. The error regarding the property `consultoria-gratis` being undefined was resolved, but the expected functionality is still not operational.

### Environment
- React version: 18.2.0
- `@calcom/embed-react` version: 1.3.0
- Browser: Google Chrome

### Steps to Reproduce
1. Install `@calcom/embed-react` using npm/yarn.
2. Implement the `getCalApi` method as demonstrated in the official documentation.
3. Use `cal.ns["consultoria-gratis"]` to configure the calendar.

### Expected Behavior
The calendar should be able to be clickable through a button.

### Actual Behavior
The calendar does not open.

### Code Snippet
```javascript
/* First make sure that you have installed the package */

/* If you are using yarn */
// yarn add @calcom/embed-react

/* If you are using npm */
// npm install @calcom/embed-react

import { getCalApi } from "@calcom/embed-react";
import { useEffect } from "react";
export default function MyApp() {
  useEffect(() => {
    (async function () {
      const cal = await getCalApi();
      cal.ns["consultoria-gratis"]("ui", {
        theme: "light",
        styles: { branding: { brandColor: "#000000" } },
        hideEventTypeDetails: false,
        layout: "month_view",
      });
    })();
  }, []);
  return (
    <button
      data-cal-namespace="consultoria-gratis"
      data-cal-link="adria-solans/consultoria-gratis"
      data-cal-config='{"layout":"month_view"}'
    >
      Click me
    </button>
  );
}

```

### Error:
```
main.3bcf4d56cc0bb7ecc71b.hot-update.js:39 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'consultoria-gratis')
```

### Additional Information
- I have checked for errors in the console and there are none relevant to this issue.
- The useEffect hook seems to be executing as expected.
- I have verified the installation of the `@calcom/embed-react` package and its dependencies.

### Attempted Solutions
- I tried verifying the initialization of `getCalApi`.
- Added checks for `cal` and `cal.ns["consultoria-gratis"]` before using them.
- Reviewed the official documentation for any updates or changes in usage.

### Request
I would appreciate any guidance or suggestions on how to resolve this issue. If there are any known issues with the `@calcom/embed-react` package or if I am missing a crucial step in the implementation, please let me know.

Thank you in advance for your time and assistance.

**Comment by MehulZR** [comment]
Hey @peter-palmer, I was not able to find something regarding the property `Cal.ns`. Can you share me the resource from where you configured it & I can look into it.

Meanwhile, This is a working example for your case (Maybe not configured in exactly the way you want). 

```javascript
import { getCalApi } from "@calcom/embed-react";
import { useEffect } from "react";

function App() {
  useEffect(() => {
    (async function() {
      const cal = await getCalApi();
      cal("ui", {
        theme: "light",
        styles: { branding: { brandColor: "#000000" } },
        hideEventTypeDetails: false,
        layout: "month_view",
      });
    })();
  }, []);
  
  return (
    <button
      data-cal-link="adria-solans/consultoria-gratis"
    >
      Click me
    </button>
  );
}
```

**Comment by PeerRich** [comment]
@peter-palmer can you try the above example?
