### ISSUE TITLE
[CAL-3036] prefill avatar when signing up with Google

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13426]
example: https://github.com/dubinc/dub/blob/main/apps/web/lib/auth/options.ts#L195

<sub>[CAL-3036](https://linear.app/calcom/issue/CAL-3036/prefill-avatar-when-signing-up-with-google)</sub>

**Comment by Rameshk84** [comment]
Here we need to change the code in of :- apps/web/lib/auth/options.ts

Here is the correct code Code 👨‍💻 :- For #13426 

callbacks: {
  signIn: async ({ user, account, profile }) => {
    console.log({ user, account, profile });
    if (!user.email || (await isBlacklistedEmail(user.email))) {
      return false;
    }
    
    if (account?.provider === "google") {
      const userExists = await prisma.user.findUnique({
        where: { email: user.email },
        select: { name: true, image: true },
      });

      // If the user already exists via email and doesn't have a name or image,
      // update the user with their name and image from Google
      if (userExists && (!userExists.name || !userExists.image)) {
        await prisma.user.update({
          where: { email: user.email },
          data: {
            name: userExists.name || profile?.name || "",
            image: userExists.image || profile?.picture || "",
          },
        });
      }
    }

    return true;
  },
  // ... other callbacks
},
