### ISSUE TITLE
[CAL-3035] Buffer not saving

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13422]
[https://app.birdeatsbug.com/qRVsP7EQkakw1E2VODyKPAi3jHng1s4Casaw89M6Eg7shttps://app.birdeatsbug.com/qRVsP7EQkakw1E2VODyKPAi3jHng1s4Casaw89M6Eg7s](https://app.birdeatsbug.com/qRVsP7EQkakw1E2VODyKPAi3jHng1s4Casaw89M6Eg7shttps://app.birdeatsbug.com/qRVsP7EQkakw1E2VODyKPAi3jHng1s4Casaw89M6Eg7s)

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=039594eb-e27e-4222-af26-86dfaca35b8f](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=039594eb-e27e-4222-af26-86dfaca35b8f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3035](https://linear.app/calcom/issue/CAL-3035/buffer-not-saving)</sub>

**Comment by keithwillcode** [comment]
Found that the data is saved to the DB but not loaded correctly in the UI. Looking into root cause
