### ISSUE TITLE
Unable to select another Google calendar to save events

### ISSUE THREAD

**Issue by laetitiamdb** [calcom/cal.com#13439]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When I select another calendar from the same Google account for adding my events and save my changes, the default calendar reverts to the one selected and my events continue to be saved in the default calendar in addition to the calendar I want to select.

### Steps to Reproduce

1. Edit an event
2. Click on Advanced
3. Select the calendar in which to add the events
4. Save

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

I consider this a bug, because I want some events to be added in one calendar and others in another. In the end, I end up with duplicate events in my Google Calendar, because my events are saved in 2 calendars.

### Expected Results

Event A should register in calendar A, and only that one, and event B in calendar B and only that one.

### Technical details

- Arc Browser version 1.27.1.
[Screen recording](https://share.cleanshot.com/bkmXy1Pm5nkwMCf97WJM
)

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by SomayChauhan** [comment]
fixed in #13440
