### ISSUE TITLE
[CAL-3055] 500 when inviting a team member and there's a conflict in the generated username

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#13464]
The bug comes from here:

[https://github.com/calcom/cal.com/blob/d6927c504927223c2ac1e8b2a3a241d36038457e/packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts#L235-L258](https://github.com/calcom/cal.com/blob/d6927c504927223c2ac1e8b2a3a241d36038457e/packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts#L235-L258)

This is causing a weird edge case where there might be the possibility that the generated user may exist already. causing a prisma error. Example: we have `robert@example.com` being converted to `robert-example` username. Which already exists in prod. On production this only returns a 500 error:

On dev we get this:

```
Object { message: "Invalid `prisma.user.create()` invocation: Unique constraint failed on the fields: (`username,`)", code: -32603, data: {…} }
```

Originally posted by @zomars in [https://github.com/calcom/cal.com/pull/11238#discussion_r1470584485](https://github.com/calcom/cal.com/pull/11238#discussion_r1470584485)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3055](https://linear.app/calcom/issue/CAL-3055/500-when-inviting-a-team-member-and-theres-a-conflict-in-the-generated)</sub>

**Comment by AnthonyJHizon** [comment]
When is the createNewUsersConnectToOrgIfExists() endpoint being called? Is it called each time a user is invited to a team?
