### ISSUE TITLE
[CAL-3054] redirects in /signup.tsx component with parameters

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13460]
it would be nice if

[https://app.cal.com/signup?redirect=https://app.cal.com/settings/teams/new](https://app.cal.com/signup?redirect=https://app.cal.com/settings/teams/new)

redirects to:

[https://app.cal.com/settings/teams/new](https://app.cal.com/settings/teams/new)

after the entire onboarding is done

that way we can change the signup button on the [https://cal.com/pricing](https://cal.com/pricing) page:

![CleanShot 2024-01-30 at 11 25 04@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/809a87bb-a253-448b-aadc-e8982a059f27/a25ae5d1-df65-461e-8cea-2ea802db90c0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84MDlhODdiYi1hMjUzLTQ0OGItYWFkYy1lODk4MmEwNTlmMjcvYTI1YWU1ZDEtZGY2NS00NjFlLThjZWEtMmVhODAyZGI5MGMwIiwiaWF0IjoxNzA2NjEzOTgzLCJleHAiOjE3MDY3MDAzODN9.7y0GWHgyjpBZ0hPb_WkQA0rDVkNQqs8iRDszas1ELuE)

to route correctly to the team creation flow

important: make sure the redirect only works within [app.cal.com](http://app.cal.com), to prevent abusing the redirect feature for harmful external links.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3054](https://linear.app/calcom/issue/CAL-3054/redirects-in-signuptsx-component-with-parameters)</sub>

**Comment by PeerRich** [comment]
potentially we want to change the onboarding flow, waiting for confirmation

**Comment by omair-muhammad** [comment]
Hi, can you share some more details regarding the flow.

**Comment by sidhhantPr** [comment]
Hi, can you share some more details??
