### ISSUE TITLE
[CAL-3056] avatarapi.com not prefilling

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13467]
i tried [peeroke@gmail.com](mailto:peeroke@gmail.com) and got no avatar:

![CleanShot 2024-01-30 at 15 23 20@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dabdeb98-5d4b-4bd6-a3f7-5d1e21c0a148/86fbd781-5bdd-4643-88da-2e27a6cd7ff9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kYWJkZWI5OC01ZDRiLTRiZDYtYTNmNy01ZDFlMjFjMGExNDgvODZmYmQ3ODEtNWJkZC00NjQzLTg4ZGEtMmUyN2E2Y2Q3ZmY5IiwiaWF0IjoxNzA2NjI4MjQwLCJleHAiOjE3MDY3MTQ2NDB9.plATj60R4OQlG2GmP4rn4fpDddVvssHeHeWkA0f20fU)

![CleanShot 2024-01-30 at 15 23 44@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ffc72dcf-cc77-4343-9199-76761e6eb399/8cff243f-9c3d-4736-94a5-75574eb41850?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mZmM3MmRjZi1jYzc3LTQzNDMtOTE5OS03Njc2MWU2ZWIzOTkvOGNmZjI0M2YtOWMzZC00NzM2LTk0YTUtNzU1NzRlYjQxODUwIiwiaWF0IjoxNzA2NjI4MjQwLCJleHAiOjE3MDY3MTQ2NDB9.TLNLFBkR1jSyNRAP5g2Ip50EI1Cre6WrXGdLGl2mfKQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3056](https://linear.app/calcom/issue/CAL-3056/avatarapicom-not-prefilling)</sub>

**Comment by PeerRich** [comment]
PR that added avatarapi.com: https://github.com/calcom/cal.com/pull/13185

I made sure to add production keys to vercel

**Comment by PeerRich** [comment]
@Amit91848 or @infiniteloopltd can you help?

**Comment by Amit91848** [comment]
@PeerRich Just checked, it is working fine for me.

![Screenshot (12)](https://github.com/calcom/cal.com/assets/74371312/ac421529-22cb-489f-8b4d-c5a88a95562a)


https://github.com/calcom/cal.com/assets/74371312/7e405675-82a8-4f95-ac53-6e17bda732e0

**Comment by PeerRich** [comment]
can you try this on production?

**Comment by Amit91848** [comment]
@PeerRich it is not working on production. Did you check how many credits you have?

**Comment by PeerRich** [comment]
we have enough credits

**Comment by PeerRich** [comment]
these are correct .env variables right?

![CleanShot 2024-02-04 at 19 26 45@2x](https://github.com/calcom/cal.com/assets/8019099/cb9ec176-5a94-4619-93ad-3c27add86d10)

**Comment by PeerRich** [comment]
or does it need to be NEXT_PUBLIC prefix?

**Comment by infiniteloopltd** [comment]
Hi, 

   Our company operates AvatarAPI.com - so I'll offer what I can in terms of diagnistics here;
 
   Here is the history of requests for the use peeroke@gmail.com 

|   id   |         email          | username |      dateRequested      |
|--------|------------------------|----------|-------------------------|
| 529010 | peeroke@gmail.com     | v0ltZz   | 2024-01-31 12:50:56.187 |
| 529008 | peeroke@gmail.com     | v0ltZz   | 2024-01-31 12:46:23.603 |
| 515773 | peeroke@gmail.com     | calcom   | 2024-01-18 22:35:35.193 |
| 460063 | peeroke@gmail.com     | grandprix| 2023-11-10 22:48:23.110 |


  The account has enough credit, and the username and password (as supplied by emal) were correct. 
  The user account "calcom" would have been expected to have made more than just 1 request.

   So, A question, can anyone see any exception coming back from "AvatarAPI" ? are the errors logged anywhere within your system? 

i.e. 

```{
    "Success": false,
    "Error": "Login failure"
}
```

would indicate that the credentials are incorrect , or

```{
    "Success": false,
    "Error": "Failed Due to XYZ"
}
```

would indicate perhaps a mis-formatting of the email

**Comment by Amit91848** [comment]
> or does it need to be NEXT_PUBLIC prefix?

I don't think so, we are only using it in server to there is no need for any prefix.


> Hi,
> 
> Our company operates [AvatarAPI.com](https://www.avatarapi.com) - so I'll offer what I can in terms of diagnistics here;
> 
> Here is the history of requests for the use [peeroke@gmail.com](mailto:peeroke@gmail.com)
> 
> id	email	username	dateRequested
> 515773	[peeroke@gmail.com](mailto:peeroke@gmail.com)	calcom	2024-01-18 22:35:35.193

Also request reached to avatarapi.com so env variables seems to be working fine. Could be authentication error?

> So, A question, can anyone see any exception coming back from "AvatarAPI" ? are the errors logged anywhere within your system?

```
  if (!info.Success) {
    console.log("Error from avatar api: ", info.Error);
    return null;
  }
```

https://github.com/calcom/cal.com/blob/296a3679558646946c55756eb616fd48fcf041c0/packages/features/auth/signup/utils/prefillAvatar.ts#L78C1-L81C4

Errors should be logged here.

**Comment by keithwillcode** [comment]
Is this still an issue?

**Comment by emrysal** [comment]
Fixed April 20 in [https://github.com/calcom/cal.com/pull/14675](https://github.com/calcom/cal.com/pull/14675)
