### ISSUE TITLE
[CAL-3059] Integration with Plausible doesn't work

### ISSUE THREAD

**Issue by D-32** [calcom/cal.com#13476]
### Issue Summary

We tried to install the Plausible integration, but it doens't seem to work and I couldn't find any detailed instructions beyond random blog posts by third parties.

Browser: Chrome on Mac

![image (42)](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4a15d60c-90dc-4180-b216-f290384a6633/45ec13f7-e37f-45e0-84c3-fd2743b886c9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80YTE1ZDYwYy05MGRjLTQxODAtYjIxNi1mMjkwMzg0YTY2MzMvNDVlYzEzZjctZTM3Zi00NWUwLTg0YzMtZmQyNzQzYjg4NmM5IiwiaWF0IjoxNzA2NzAyMzk2LCJleHAiOjE3MDY3ODg3OTZ9.x2D1-QSuDcUIM_yc9Cf_SxDhn766bXSiFBdZ2fOoWIc)

That's all we setup, is there anything else one has to do?

Clicking the gear/settings icon leads to an empty page:

![image (43)](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/94f354a1-627c-445d-ab58-f5aa706cb2ab/6d6056d6-e01b-44c4-89c5-36c79521ca78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NGYzNTRhMS02MjdjLTQ0NWQtYWI1OC1mNWFhNzA2Y2IyYWIvNmQ2MDU2ZDYtZTAxYi00NGM0LTg5YzUtMzZjNzk1MjFjYTc4IiwiaWF0IjoxNzA2NzAyMzk2LCJleHAiOjE3MDY3ODg3OTZ9.6NJyLqyyrKd0GgSghpHvspnBWCTGFdNF8uSWutDm5-Q)

Thanks!

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3059](https://linear.app/calcom/issue/CAL-3059/integration-with-plausible-doesnt-work)</sub>

**Comment by PeerRich** [comment]
thank you for reporting, we will look into this!

**Comment by PeerRich** [comment]
@hariombalhara could this be violation of CSP?

**Comment by D-32** [comment]
@PeerRich thanks for looking into this. Can you maybe explain more how this integration is even supposed to work? Should bookings show up as a goal conversion inside Plausible?

**Comment by D-32** [comment]
@PeerRich configuration page loads, but nothing's showing up inside Plausible:
<img width="1162" alt="image" src="https://github.com/calcom/cal.com/assets/3063279/d0483817-42ce-44a5-a9e5-2d33cffd5476">
