### ISSUE TITLE
[BUG] Heading overlapping with content on pricing page

### ISSUE THREAD

**Issue by nehagupta1504** [calcom/cal.com#13487]
### Issue Summary

1. In desktop view the "contact us" heading is overlapping on the content
2. In mobile view the "$12 /user/month" in this /user is going above $12 which is not looking good

Attaching screenshots for both issues
1.
<img width="1006" alt="image" src="https://github.com/calcom/cal.com/assets/66299920/840bdd28-f073-43c1-853a-afafd622c403">
2. 
<img width="452" alt="image" src="https://github.com/calcom/cal.com/assets/66299920/edf64498-17f2-4cf8-9687-c35bb2c1ee2a">

### Steps to Reproduce

1. Click on pricing
2. Check headings on desktop and mobile version

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Expected Results

- The heading should not overlap content and should have proper symmetry

**Comment by Kviraj722** [comment]
Issue solved. right?

**Comment by nehagupta1504** [comment]
I saw it yesterday only and attached the screenshot, not sure whether it is solved today or not

**Comment by Kviraj722** [comment]
It's solved. I've verified.
