### ISSUE TITLE
[CAL-3065] Prefill Avatar with Google avatar after connecting a Google Calendar

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13492]
i think this is possible

would be nice if people sign up with email + password but then add a Google Calendar

<sub>[CAL-3065](https://linear.app/calcom/issue/CAL-3065/get-someones-google-avatar-after-connecting-a-google-calendar)</sub>

**Comment by PeerRich** [comment]
only if there is no avatar set yet

**Comment by anoopw3bdev** [comment]
Hello @PeerRich, I would like to work on this issue.

Do I need to get an issue assigned before submitting a PR or can I directly submit one?
