### ISSUE TITLE
[CAL-3078] Events awaiting approval: wrong e-mail title

### ISSUE THREAD

**Issue by guiljo** [calcom/cal.com#13514]
When a participant creates an event which is awaiting confirmation, they receive an e-mail with the title "Réservation confirmée" (confirmed booking) instead of "En attente de validation" (awaiting approval).

The organizer receives the right email though.

Maybe only happens in French?

### Steps to Reproduce

1. Set language to French
2. Create an event
3. Check parameter "Requires confirmation"
4. Create a booking
5. Check participant's emails

### Actual Results

Email title: "Réservation confirmée : ..."

### Expected Results

Email title: "En attente de validation : ..." or "Demande de réservation envoyée: ..."

### Technical details

Probably not relevant here

### Evidence

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1ab51490-88c1-4b65-91b1-7d21398e6dfe/9de61105-2ed9-49b5-b9b4-31034943dbe6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xYWI1MTQ5MC04OGMxLTRiNjUtOTFiMS03ZDIxMzk4ZTZkZmUvOWRlNjExMDUtMmVkOS00OWI1LWI5YjQtMzEwMzQ5NDNkYmU2IiwiaWF0IjoxNzA3MTMzNjY3LCJleHAiOjE3MDcyMjAwNjd9.Ny0JxlwBEr1egkBEtqyNTReU4vvU79-hAyL3czUyJpM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3078](https://linear.app/calcom/issue/CAL-3078/events-awaiting-approval-wrong-e-mail-title)</sub>

**Comment by PeerRich** [comment]
can you check if this is correct? https://github.com/calcom/cal.com/pull/13536
