### ISSUE TITLE
[CAL-3090] Hide branding still retains the space

### ISSUE THREAD

**Issue by laneme** [calcom/cal.com#13527]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/eeac45e9-75c1-42cf-a4a7-c9c87edc9700/80ad5fd5-653c-4570-9e4e-9e4e7ef5db45?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lZWFjNDVlOS03NWMxLTQyY2YtYTRhNy1jOWM4N2VkYzk3MDAvODBhZDVmZDUtNjUzYy00NTcwLTllNGUtOWU0ZTdlZjVkYjQ1IiwiaWF0IjoxNzA3MzA3NjU2LCJleHAiOjE3MDczOTQwNTZ9.2ytgr1Pqx-3xXmyyAdXcROuViQtAB14dDWqc2oMa68k)

Most of the marked space in the above screenshot is retained even after I hide the branding.
The entire element (with margin/padding) should be hidden instead of only the text.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3090](https://linear.app/calcom/issue/CAL-3090/hide-branding-still-retains-the-space)</sub>

**Comment by PeerRich** [comment]
can you send the link here and a screenshot of your settings?

**Comment by SudeshHirave** [comment]
will display: none; work on it?
new to the opensource world

**Comment by laneme** [comment]
@SudeshHirave it works but its react, the entire element can be hidden instead.
