### ISSUE TITLE
[CAL-3129] Lock timezone on booking page based on availability timezone

### ISSUE THREAD

**Issue by lucidfoxes** [calcom/cal.com#13521]
### Is your proposal related to a problem?

The toggle to 'Lock timezone on booking page' for in-person events on the advanced events setup page is a very useful feature. But it doesn't appear to be working as expected for our needs. This is because the timezone that the booking page is locked to isn't the timezone we have set in the 'availability' settings for that event, but rather it is based on the timezone of the user accessing the booking page. This could cause serious misunderstandings, for example when the event is a trade show in third country, which is neither in the Organizer's or Attendee's current timezone.     

### Describe the solution you'd like

We would like to be able to force the display of the timezone on the booking page for in-person events to a specific timezone. Ideally this would be the same timezone for which the 'availability' settings for that event have been defined, and not based on the current timezone of the user accessing the booking page.

### Describe alternatives you've considered

The only solution for us at the moment seems to be to remind whoever we share the booking link with, to use the dropdown to set the appropriate timezone manually to the timezone of the trade show on the booking page. It might be possible to add a timezone parameter to the url string for an event booking page, but I haven't be successful when trying to do this. 

<sub>[CAL-3129](https://linear.app/calcom/issue/CAL-3129/lock-timezone-on-booking-page-based-on-availability-timezone)</sub>

**Comment by Pritam-sd-dev** [comment]
I want to work on this, please assign this task to me asap. thank you :) .

**Comment by keithwillcode** [comment]
@Pritam-sd-dev no need to be assigned. Feel free to open a PR and we’ll review.
