### ISSUE TITLE
Remove the scroll from the scheduling for companies section.

### ISSUE THREAD

**Issue by Bashamega** [calcom/cal.com#13533]
Hello:)

I have noticed that there is a scroll bar on the companies' section but there is no scroller, because my screen is big. So it looks unprofessional.
This is what I mean:
![image](https://github.com/calcom/cal.com/assets/110662505/27535c1b-704f-419c-9c33-d93286452144)

To fix it change the `overflow-scroll` on the div to `overflow-auto`, and this way you will have a smooth looking landing page.
I would love to work on it.

**Comment by PeerRich** [comment]
i think its fine for now
