### ISSUE TITLE
[CAL-3103] Multiple bookings for meetings that require calendar owners confirmation.

### ISSUE THREAD

**Issue by kevinhoodme** [calcom/cal.com#13548]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a 3rd party books a meeting which requires calendar owners confirmation & email verfication when integrating with google calendar -- 3 different calendar events are created in the same time slot with different meeting links.

### Steps to Reproduce

1. User selects a meeting time.
2. User enters name & email address
3. User verifies email.
4. I receive 3 emails to approve 3 separate meeting events at the same time.
5. If all are approved - 3 separate meetings with different meeting links are added to everyone's calendar.

### Actual Results

I receive 3 emails and each one is asking me to approve a separate meeting event when only one was booked.

### Expected Results

I expect to receive a single email for me to approve the meeting.

### Technical details

Not reproduceable by me on my own computer.

Only happens when other people book _(it has happened 5 times in a row when other people are booking)._

https://www.loom.com/share/b7bcafc6e9fc4d67b8d05e590982069b?sid=23b5736b-802f-49e2-9a47-046af1256110

### Evidence

Only happens when other people book _(it has happened 5 times in a row when other people are booking)._

<sub>[CAL-3103](https://linear.app/calcom/issue/CAL-3103/multiple-bookings-for-meetings-that-require-calendar-owners)</sub>

**Comment by khaledmosllim** [comment]
It happened with me today, the booking was duplicated **more than 7 times!!**
That happened only when I activated the email confirmation option for the bookers

**Comment by keithwillcode** [comment]
Looking at logs for debugging the no_available_users_found error, we are seeing duplicate requests coming from iPhone a majority of the time.

**Comment by emrysal** [comment]
I don't see a reason this would happen other than when bookings are duplicates, but any reason should be entirely resolved when queues is done. This bug is very rare.

**Comment by kevinhoodme** [comment]
> I don't see a reason this would happen other than when bookings are duplicates, but any reason should be entirely resolved when queues is done. This bug is very rare.

It happens when the person booking the calendar has to verify their email address before completing the booking.

In regard to rarity, It happened every single time someone booked when this feature is enabled, so I had to disable it.

Appreciate the effort to resolve the issue.  Thanks everyone!
