### ISSUE TITLE
[CAL-3083] Out of office (OOO) v2

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13558]
### Current behavior

We shipped an v1 of OOO which serves a basic function, but has some issues. If, for example, I mark myself as OOO today and tomorrow, anyone who visits my link today or tomorrow cannot book me at all. This means they can't book me 2 days out from now, even though I will be back and fully available. Essentially, we're blocking out **all** future dates, and not just the OOO ones.

The designs below show that "I am not accepting new bookings". This is problematic in that while I'm not accepting new bookings today and tomorrow, I want people to book me for my return.

![CleanShot 2024-02-06 at 12.45.56@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d42ee44c-27ef-49b1-a4e1-867ea0537af3/7cb9e8d6-bce9-479c-acc2-a6455ae2a26f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kNDJlZTQ0Yy0yN2VmLTQ5YjEtYTRlMS04NjdlYTA1MzdhZjMvN2NiOWU4ZDYtYmNlOS00NzljLWFjYzItYTY0NTVhZTJhMjZmIiwiaWF0IjoxNzA3Mjg4MDg2LCJleHAiOjE3MDczNzQ0ODZ9.AlMDHaJhPW7GZW1bbmShkk3xSRVhpnGazOgmFmMMm8U)

### Desired behaviour

As a user, I want to be able to

* Set myself as OOO for a date range
* Assign someone else on my team to be able to take bookings in my absence (optional, and based on whether you are on a team or not)
* View all OOO entries I have created for the future (including date and redirect assignee if applicable)
* Delete any OOO I have created

As a booker landing on the link of a Cal.com user, I want to…

* See when the person I am trying to book is OOO
* See when they will return
* See who I can book instead (if someone has been assigned), if I don't want to wait till they return
* ..across all calendar views (monthly/weekly/column)

[**View provisional designs**](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=17668-117405&mode=design&t=6RppeyK4OWTObEg9-11)

![CleanShot 2024-02-06 at 12.39.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/969a0594-5340-4d23-9293-83d505ba795e/db18947a-f961-49d6-aa3d-cb8e48e64486?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NjlhMDU5NC01MzQwLTRkMjMtOTI5My04M2Q1MDViYTc5NWUvZGIxODk0N2EtZjk2MS00OWQ2LWFhM2QtY2I4ZTQ4ZTY0NDg2IiwiaWF0IjoxNzA3Mjg4MDg2LCJleHAiOjE3MDczNzQ0ODZ9.o_2RtQi5XqBswiShraSzRSfKqpoA-EmABsG4vZWVCKU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3083](https://linear.app/calcom/issue/CAL-3083/out-of-office-ooo-v2)</sub>

**Comment by alannnc** [comment]
Looks great! Nice description, will be currently working on this. PR should come soon. Thank you @ciaranha

**Comment by CarinaWolli** [comment]
There's currently an issue with orgs in our OOO feature. @alannnc can you make sure org usernames will be handled correctly in v2? 

Current issue: 
> OOO entries from non-org account sets org account with same user name as away.

> OOO feature is missing organization handling. It needs to query by username the same way we query for user's event-types
> https://github.com/calcom/cal.com/blob/89bb2dc07a5bf8f59f3416a66685eeef6dab71b8/packages/features/booking-redirect/handle-user.ts#L11

**Comment by alannnc** [comment]
> There's currently an issue with orgs in our OOO feature. @alannnc can you make sure org usernames will be handled correctly in v2?
> 
> Current issue:
> 
> > OOO entries from non-org account sets org account with same user name as away.
> 
> > OOO feature is missing organization handling. It needs to query by username the same way we query for user's event-types
> > https://github.com/calcom/cal.com/blob/89bb2dc07a5bf8f59f3416a66685eeef6dab71b8/packages/features/booking-redirect/handle-user.ts#L11

Sure, looks like we are removing redirection instead and instead display OOO on the calendar. I'll make sure that redirection or the new "forwarding" uses id instead of username.

**Comment by CarinaWolli** [comment]
Found an issue with the booking-redirect-notification email, in [ this line](https://github.com/calcom/cal.com/blob/main/packages/emails/templates/booking-redirect-notification.ts#L27) it needs to be: 

``to: `${this.bookingRedirect.toName} <${this.bookingRedirect.toEmail}>,`` 
instead of      
``to: ${this.bookingRedirect.toEmail} <${this.bookingRedirect.toName}>`,``

**Comment by alannnc** [comment]
@CarinaWolli Thank you I will include this change.
