### ISSUE TITLE
[CAL-3084] self-rescheduled meeting didn't have cal.com meeting

### ISSUE THREAD

**Issue by jobenjada** [calcom/cal.com#13563]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fd4a2764-8844-465f-bcec-ef4398db0cc2/002941e0-e9bd-4e7c-ba68-82c99b4b74ea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mZDRhMjc2NC04ODQ0LTQ2NWYtYmNlYy1lZjQzOThkYjBjYzIvMDAyOTQxZTAtZTliZC00ZTdjLWJhNjgtODJjOTliNGI3NGVhIiwiaWF0IjoxNzA3MjQ3MjA2LCJleHAiOjE3MDczMzM2MDZ9.x8x_abtoEm0A30whBv4a0_cZ3LiRR4U71TptGYKz-0Y)

I rescheduled the meeting myself (twice) and the [cal.com](http://cal.com) meeting got lost ( see above )

This was the meeting: [https://app.cal.com/video/8Pyt9CDagAw8rghxtQbvvG](https://app.cal.com/video/8Pyt9CDagAw8rghxtQbvvG)

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* What's happening right now that is different from what is expected

### Expected Results

* This is an ideal result that the system should get after the tests are performed

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3084](https://linear.app/calcom/issue/CAL-3084/self-rescheduled-meeting-didnt-have-calcom-meeting)</sub>

**Comment by Udit-takkar** [comment]
@jobenjada did you got any new meeting link after rescheduling?

**Comment by dmonn** [comment]
Users are reporting the same with us. Rescheduled meetings do not get an updated Cal.com video link, leading to an "expired link" error.

**Comment by Udit-takkar** [comment]
@dmonn could you share the booking success page url?
