### ISSUE TITLE
[CAL-3116] `bookingSuccessful` event is emitted even when the user clicks on `Cancel`, `Nevermind` etc...

### ISSUE THREAD

**Issue by baptisteArno** [calcom/cal.com#13562]
### Issue Summary

When embedding a cal.com widget, the `bookingSuccessful` event is emitted even when the user clicks on `Cancel`, `Nevermind` etc...

I'd expect it to only be emitted whenever an event is successfully booked.

### Steps to Reproduce

1. Embed a widget
2. Subscribe a callback to `bookingSuccessful` event
3. Book an event, then click on Cancel, then Nevermind

<sub>[CAL-3116](https://linear.app/calcom/issue/CAL-3116/bookingsuccessful-event-is-emitted-even-when-the-user-clicks-on-cancel)</sub>

**Comment by Yash-271120** [comment]
Hi!  I would like to take this up if it is available

**Comment by asadath1395** [comment]
@baptisteArno This is fixed in this PR https://github.com/calcom/cal.com/pull/13755. Mind testing this again

cc @PeerRich
