### ISSUE TITLE
[CAL-3087] Make linting rule disallowing use of Prisma includes using only "true" and not a field selector

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#13577]
To ensure we only retrieve necessary data from the db and to protect unwanted data from crossing application boundaries.

Example:

include: {

  user: true;

}

Should cause a linting error

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3087](https://linear.app/calcom/issue/CAL-3087/make-linting-rule-disallowing-use-of-prisma-includes-using-only-true)</sub>

**Comment by bandevedant** [comment]
Hello Keith , the above stuff can be solved by adding 
rules: {
    // Other rules...
    'no-prisma-include-true': 'error', // Add the custom rule here
  },
in  cal.com/packages/config/eslint-preset.js  Please correct me if I am wrong. I am ready to be assigned. Thank you.

**Comment by keithwillcode** [comment]
@bandevedant no need to be assigned. Feel free to open a PR and we will review. Thanks!
