### ISSUE TITLE
[CAL-3088] /teams page text not visible on light mode

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#13578]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f52194af-7109-4142-873e-f883792ea059/f47e8040-3205-411a-b936-d947a0343750?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mNTIxOTRhZi03MTA5LTQxNDItODczZS1mODgzNzkyZWEwNTkvZjQ3ZTgwNDAtMzIwNS00MTFhLWI5MzYtZDk0N2EwMzQzNzUwIiwiaWF0IjoxNzA3Mjk3MzE5LCJleHAiOjE3MDczODM3MTl9.NKGDnC5kVd_L3Yvh6Z7-IhZxa2Fdz3iaW8UmRfMOMAM)

text is not visible

### Steps to Reproduce

1. Go to /teams page

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3088](https://linear.app/calcom/issue/CAL-3088/teams-page-text-not-visible-on-light-mode)</sub>

**Comment by bandevedant** [comment]
<img width="790" alt="image" src="https://github.com/calcom/cal.com/assets/103803803/25e95ee6-1d46-4bdb-848e-fde7c53fde89">
Hello Udit  I think it was a error the teams page text seems fine in vision.

**Comment by rixitgithub** [comment]
This is my first time here in open source. How should I start working on it?

**Comment by Shivansh-243** [comment]
@Udit-takkar please assign it to me 
or  please reply if without being assigned i can work on it

**Comment by khushalmajoka** [comment]
@Udit-takkar This seems fine in light mode.

Microsoft Edge Browser:
<img width="769" alt="image" src="https://github.com/calcom/cal.com/assets/56840292/c96f013d-8d99-44d7-a37e-20647c57eacf">
Opera Browser:
<img width="778" alt="image" src="https://github.com/calcom/cal.com/assets/56840292/66c03f3f-58a8-4d72-ae06-bfc85e29222e">

**Comment by saurabhraj123** [comment]
Looks fine on my browser as well.. @Udit-takkar, can you please confirm?

**Comment by Udit-takkar** [comment]
@saurabhraj123 I was on Brave browser

**Comment by tanavposwal** [comment]
close this issue
