### ISSUE TITLE
[CAL-3091] double bookings with zoho calendar

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13584]
Recently we have been getting double booked 

[@techityconsult](https://twitter.com/techityconsult)

 - we have setup our  Zoho calendars setting toggled on to check for conflicts. When I used the calendar troubleshooter, it doesn’t show our existing mtgs.

Any additional thing we should be enabling on Zoho Mail?

<sub>[CAL-3091](https://linear.app/calcom/issue/CAL-3091/double-bookings-with-zoho-calendar)</sub>

**Comment by Pritam-sd-dev** [comment]
please assign this task to me, i want to contribute to this project.

**Comment by keithwillcode** [comment]
@Pritam-sd-dev no need to be assigned. Feel free to open a PR and we’ll review.

**Comment by Pritam-sd-dev** [comment]
ok thanks, i have started working on it.
