### ISSUE TITLE
[CAL-3130] Support webhooks that listen to platform-wide events

### ISSUE THREAD

**Issue by jalada** [calcom/cal.com#13587]
### Is your proposal related to a problem?

I'm working on an integration between our self-hosted [cal.com](http://cal.com) instance and an internal platform. As part of that, I'd like the internal platform to be notified about *any* bookings made, cancelled etc. regardless of who they were for or what event type they were for. Right now, if I want to do that, I'll need to manually or programmatically create a webhook configuration for every user (or every event type) and make sure that stays in sync as users (or event types) are added and removed.

### Describe the solution you'd like

I'd like to be able to create webhooks that are 'unfiltered' e.g. the endpoint is notified about *every* booking created, cancelled etc. Only admins should be able to create these; they already have access to view all this information anyway.

### Describe alternatives you've considered

As above, I could manually/programmatically manage a suite of webhooks for every user and event type, but this is considerable extra work on the internal platform vs. (what I think is) the required change within [cal.com](http://cal.com).

---

##### House rules

* If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  * For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  * Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3130](https://linear.app/calcom/issue/CAL-3130/support-webhooks-that-listen-to-platform-wide-events)</sub>

**Comment by PeerRich** [comment]
wait but this would leak other users information, would it not?

**Comment by jalada** [comment]
> wait but this would leak other users information, would it not?

Updated to reflect:

> Only admins should be able to create these; they already have access to view all this information anyway.
