### ISSUE TITLE
[CAL-3089] View Bookings of Team

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#13582]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Reported on discord
 [https://discord.com/channels/1125390093386010654/1204544773697044591/1204544773697044591](https://discord.com/channels/1125390093386010654/1204544773697044591/1204544773697044591)

I created a team and added a few members. Then I added a few event types to those members. When customers started to book events I was expecting to see "Upcoming" events listed. However, I cannot see the bookings of my team members, only my own...I know they exist because my team member can see upcoming bookings but I cannot!

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fcf14eaf-d3fd-463e-91ed-50e8fba06cc4/ce157da0-d82f-48eb-8a64-e03bc5e0373f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mY2YxNGVhZi1kM2ZkLTQ2M2UtOTFlZC01MGU4ZmJhMDZjYzQvY2UxNTdkYTAtZDgyZi00OGViLThhNjQtZTAzYmM1ZTAzNzNmIiwiaWF0IjoxNzA3MzAxNzQxLCJleHAiOjE3MDczODgxNDF9.4MAlkkjZO3FM2QDP8YKOFn8n2cLOohbSzWm6-KhfsQ8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3089](https://linear.app/calcom/issue/CAL-3089/view-bookings-of-team)</sub>

**Comment by keithwillcode** [comment]
@ciaranha input on this?

**Comment by zachgitt** [comment]
This might be a silly question, but as a developer who does not work on open-source projects, can I review the code and create a PR if someone points me to it? It's unclear to me as to whether only the FE is open-source if it the BE is as well.

**Comment by ciaranha** [comment]
> @ciaranha input on this? 

The admin of a team should see the bookings of his members. Is that the question here @keithwillcode ?

**Comment by zachgitt** [comment]
As the original poster on discord. Yes this was my question. But this is not the behavior.

**Comment by ciaranha** [comment]
> As the original poster on discord. Yes this was my question. But this is not the behavior.

Yea it's a bug.

Should look like this where the default view is all of the bookings of your team members:
![CleanShot 2024-02-07 at 21 59 45@2x](https://github.com/calcom/cal.com/assets/4536123/54b2ca17-953f-4780-aee7-c4acc71be114)

**Comment by keithwillcode** [comment]
#13591 was reverted due to DB load issues introduced. It needs to be redone.
