### ISSUE TITLE
[CAL-3417] Microsoft 365 Calendar Invite problems

### ISSUE THREAD

**Issue by robertmclaws** [calcom/cal.com#13608]
### Issue Summary

There are extensive issues with the calendar invites sent out to people that make them look amateur in quality. I have noticed this happens for any invite that goes out, whether it is from an individual account or a team.

![image](https://github.com/calcom/cal.com/assets/8019099/12acd044-bba9-443e-902d-a3406443033d)

**1. The invite is adding me as an attendee to my own event in a way that is not reconciling in Outlook.
   a. if I send an update I instantly get a NDR response from Microsoft for my own email address.**
2. The description text does not appear to be configurable at all, after attempts to access it from several different directions in the account.
3. The text is missing line breaks between pieces of information
4. The rescheduling link is not actually a link.

### Steps to Reproduce

1. Schedule a meeting.
2. Receive the calendar invite
3. Log into your account to try to control the content of the invites
4. Find out you can't control the content of the invites.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* The system is sending out invitations to my customers that do not look professional at all.

### Expected Results

* I expect that the invitations my customers receive do not look this bad.

### Technical details

* Calendar: Office 365 / Outlook

### Evidence

* I spent over 45 minutes looking through the entire UI for customization options and found none. Across all of my configured teams and personal events, this is the same consistent invitation that goes out to everyone.
* This seems to be related to [https://github.com/calcom/cal.com/issues/13529](https://github.com/calcom/cal.com/issues/13529) where users cannot configure email templates for notifications... but this issue is a lot more egregious.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3417](https://linear.app/calcom/issue/CAL-3417/extensive-calendar-invite-problems)</sub>

**Comment by PeerRich** [comment]
this is the email that I get 🤔

<img width="570" alt="CleanShot 2024-05-28 at 09 47 48@2x" src="https://github.com/calcom/cal.com/assets/8019099/78b7ed14-ff4b-47b8-9b4a-8af9e9af8090">

**Comment by robertmclaws** [comment]
Not even close to what I'm getting. I'm technically not even getting an email when someone creates an event. I just have to look for it on my calendar.

Here's an example of Calendly's calendar invite:

![image](https://github.com/calcom/cal.com/assets/1657085/98f805c1-f5e8-4ce5-9e36-da5a50d7f746)

**Comment by robertmclaws** [comment]
I changed the name of this issue again. It is not just about line breaks. The invitation is being sent to invalid email addresses as well.
