### ISSUE TITLE
[CAL-3102] Managed Event Types Option not Always Displaying

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#13610]
I have seen this bug myself a few times in the product. After refreshing a few times, it eventually shows up

![CleanShot 2024-02-09 at 10.20.53@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fd4fb59c-2223-4c4f-9b70-5a91af6992bb/e76a3a78-61da-4bbf-bb8f-f1764b9e3f03?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mZDRmYjU5Yy0yMjIzLTRjNGYtOWI3MC01YTkxYWY2OTkyYmIvZTc2YTNhNzgtNjFkYS00YmJmLWJiOGYtZjE3NjRiOWUzZjAzIiwiaWF0IjoxNzA3NDQ1MjkwLCJleHAiOjE3MDc1MzE2OTB9.HWOb8fItzytc_z8XUJOIH9IJJv2iumDz6vT7x0qn-i4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3102](https://linear.app/calcom/issue/CAL-3102/managed-event-types-option-not-always-displaying)</sub>

**Comment by SomayChauhan** [comment]
was recently fixed by #13469
not sure if its in prod yet

**Comment by keithwillcode** [comment]
Will make it to prod today

**Comment by shirazdole** [comment]
Sweet notified the customer!
