### ISSUE TITLE
[CAL-3110] Remove Skiff

### ISSUE THREAD

**Issue by titanism** [calcom/cal.com#13629]
Hi there - you should remove Skiff (e.g. <https://github.com/calcom/cal.com/blob/b183a5779a4ec63969f2533316b200e7abf0cdcd/packages/app-store/skiff/api/add.ts#L14>) since they are defunct and shutting down service in 6 months.

See <https://skiff.com/data-migration>

An alternative may be https://forwardemail.net 😄 

<sub>[CAL-3110](https://linear.app/calcom/issue/CAL-3110/remove-skiff)</sub>

**Comment by suyash5053** [comment]
@keithwillcode Hey, wanted to know that should I remove everything about the app, from the app store?
