### ISSUE TITLE
[CAL-3120] add a banner to org links

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13643]
same banner as twitter [https://x.com/deel](https://x.com/deel)

![CleanShot 2024-02-12 at 14 15 49@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fa229bb3-0f41-4227-bbe8-ec5901164606/fcc860c6-c26c-4a10-aaf8-53d7784885de?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mYTIyOWJiMy0wZjQxLTQyMjctYmJlOC1lYzU5MDExNjQ2MDYvZmNjODYwYzYtYzI2Yy00YTEwLWFhZjgtNTNkNzc4NDg4NWRlIiwiaWF0IjoxNzA3NzQ3MzY5LCJleHAiOjE3MDc4MzM3Njl9.BDUQKjd_C0FDFuvbG6NSWS0wW9_Nx_srlcmBqR46PWE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3120](https://linear.app/calcom/issue/CAL-3120/add-a-banner-to-org-links)</sub>

**Comment by saurabhraj123** [comment]
Can you please elaborate more on the issue @PeerRich

**Comment by PeerRich** [comment]
i'm already working on it, no worries

**Comment by shirazdole** [comment]
Will this be in 3.9? Trying to get a timeline update for an orgs customer asking
