### ISSUE TITLE
[CAL-3119] routing forms: select team members to receive emails

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13641]
right now we have a switch to turn emails on and off:

![CleanShot 2024-02-12 at 13 47 09@2x](https://github.com/calcom/cal.com/assets/8019099/e51ae241-0786-4768-8ace-7320ccfb36d0)

it would be nicer if we were able to select team members from that team:
![CleanShot 2024-02-12 at 13 46 08@2x](https://github.com/calcom/cal.com/assets/8019099/601e0a47-02e5-4e44-99bb-65f9ec795b7f)

we can use the same input from team link assignment in event-types:

![CleanShot 2024-02-12 at 13 46 39@2x](https://github.com/calcom/cal.com/assets/8019099/5f0b1b75-a162-4bb1-96b5-26a2780eae1b)

<sub>[CAL-3119](https://linear.app/calcom/issue/CAL-3119/routing-forms-select-team-members-to-receive-emails)</sub>

**Comment by raulrusu88** [comment]
if it's all right, I can take a look at this
