### ISSUE TITLE
[CAL-3123] open routing forms reporting in new tab

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13658]
this is too crowded for a reporting table:

![CleanShot 2024-02-13 at 14 58 20@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4c1f2bd4-9c5b-44b2-9e88-62e91f7456e6/2ae98cb2-9756-43d4-81e0-eb29d8ba8a02?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80YzFmMmJkNC05YzViLTQ0YjItOWU4OC02MmU5MWY3NDU2ZTYvMmFlOThjYjItOTc1Ni00M2Q0LTgxZTAtZWIyOWQ4YmE4YTAyIiwiaWF0IjoxNzA3ODM2MzI4LCJleHAiOjE3MDc5MjI3Mjh9.FQI8NR35CRERA4ZffP4yrQRDbkQgb1x-QDQlK7kgJrs)

instead lets open this in full screen as a new tab

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3123](https://linear.app/calcom/issue/CAL-3123/open-routing-forms-reporting-in-new-tab)</sub>

**Comment by shravan20** [comment]
@PeerRich: Can I pick this up?
