### ISSUE TITLE
[CAL-3124] Drop deprecated password column

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#13664]
[https://github.com/calcom/cal.com/blob/e1f2dbab849de5d4e5bf825ee1f29f6a6b215a7c/packages/prisma/migrations/20240209223121_adds_user_password/migration.sql#L29-L30](https://github.com/calcom/cal.com/blob/e1f2dbab849de5d4e5bf825ee1f29f6a6b215a7c/packages/prisma/migrations/20240209223121_adds_user_password/migration.sql#L29-L30)

[https://github.com/calcom/cal.com/pull/13662#discussion_r1488397593](https://github.com/calcom/cal.com/pull/13662#discussion_r1488397593)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3124](https://linear.app/calcom/issue/CAL-3124/drop-deprecated-password-column)</sub>

**Comment by kart1ka** [comment]
The password column is already being dropped. On running db-migrate command, a new migration gets created which drops the password column from the user table.

**Comment by zomars** [comment]
> The password column is already being dropped. On running db-migrate command, a new migration gets created which drops the password column from the user table.

This is part of a 2-step deployment plan to prevent data-loss. Once the first step is done we will commit the missing migration.
