### ISSUE TITLE
Fix signup form validation

### ISSUE THREAD

**Issue by saurabhraj123** [calcom/cal.com#13661]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Signup form validation is not correct. 

When I enter my password, even though three requirements are there:
- Mix of uppercase & lowercase letters
- Minimum 7 characters long
- Contain at least 1 number

When password is entered, it shows tick marks next to it as if the password is acceptable, even though above mentioned criteria is not met. Only when we submit it does it say that the password is wrong. 

Also, it only checks for the length of the password to be at least 7 and other two requirements are not checked.

<img width="616" alt="Screenshot 2024-02-13 at 11 44 18 PM" src="https://github.com/calcom/cal.com/assets/24193157/7ba805a8-bd1a-4fe5-acfa-3cdac071f34d">

### Steps to Reproduce

1. Go to `http://localhost:3000/signup`
2. Use signup form

### Actual Results

Not validating the inputs correctly..
- Before form submission, even if none of the conditions are met, password hint shows tick marks indicating, the password is acceptable.
- After we submit the form once, it says that password is incorrect but still only password length is validated and other requirements are ignored.

### Evidence
<img width="616" alt="Screenshot 2024-02-13 at 11 44 18 PM" src="https://github.com/calcom/cal.com/assets/24193157/7ba805a8-bd1a-4fe5-acfa-3cdac071f34d">

https://github.com/calcom/cal.com/assets/24193157/2d52e671-8279-4b5c-a3d4-375915f1a2fc

**Comment by PeerRich** [comment]
my signup looks like this 

i cant reproduce this. are you on an older version? i am confused

![CleanShot 2024-02-13 at 22 34 13@2x](https://github.com/calcom/cal.com/assets/8019099/302f76af-81eb-4ee6-8980-e5409a2ca515)

**Comment by PeerRich** [comment]
this issue was due to an older version. please pull latest main
