### ISSUE TITLE
[CAL-3127] Can access/view other team's calendars from booking page or embed

### ISSUE THREAD

**Issue by jsjoeio** [calcom/cal.com#13666]
Not sure if bug or feature. If not bug, would like it to be a feature to disable this.

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Go to a calendar i.e. [https://i.cal.com/bailey+peer/dynamic](https://i.cal.com/bailey+peer/dynamic)
2. Click Company logo/avatar
3. See other team's calendars 😅

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I didn't expect this to happen. At least without not explicitly enabling this in our Cal embed. And I've searched the docs and asked the AI help, and looked in the type definitions and cannot figure out how to disable this.

**why this is important to us:**

we're using the Cal embed and we don't want users to be able to access other team's calendars

### Actual Results

![2024-02-13 15 07 16](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/902700e3-3c22-4a96-8e89-7cfd1e942d96/97f37364-a88f-4246-894a-15c2633dc895?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MDI3MDBlMy0zYzIyLTRhOTYtOGU4OS03Y2ZkMWU5NDJkOTYvOTdmMzczNjQtYTg4Zi00MjQ2LTg5NGEtMTVjMjYzM2RjODk1IiwiaWF0IjoxNzA3ODY3NDM0LCJleHAiOjE3MDc5NTM4MzR9.qCTe2nOk0olsw68hVOmFIECwq100K3mY32O5MpAZMvY)

### Expected Results

You shouldn't be able to see other team's calendars.

### Technical details

N/A (I don't think this is relevant)

### Evidence

See gif above

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3127](https://linear.app/calcom/issue/CAL-3127/can-accessview-other-teams-calendars-from-booking-page-or-embed)</sub>

**Comment by PeerRich** [comment]
this happens because bailey and peer are in an organisation, and the logo indicates that. i dont think this is a bug. maybe a questionable design decision, but i dont mind keeping it. i also dont mind having the links visible, since anyone can visit i.cal.com (or in general acme.cal.com) to find this

**Comment by jsjoeio** [comment]
@PeerRich wait sorry for the confusion, how do I disable this? 

We don't want users to be able to access other team's calendars

**Comment by PeerRich** [comment]
ohhhh i see

**Comment by PeerRich** [comment]
i understand. lemme remove the link there for embeds.
