### ISSUE TITLE
[CAL-3125] show top banner for broken integrations

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13667]
when we show this:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c86f9a1a-c2fe-47e9-9200-a42ccba72db9/799740da-e0d0-46fc-909c-8e47919d5872?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jODZmOWExYS1jMmZlLTQ3ZTktOTIwMC1hNDJjY2JhNzJkYjkvNzk5NzQwZGEtZTBkMC00NmZjLTkwOWMtOGU0NzkxOWQ1ODcyIiwiaWF0IjoxNzA3ODYzMTU4LCJleHAiOjE3MDc5NDk1NTh9.TpFFWRGU4RWQrorgNM6KZR4OPlerRpu1v2D6TTg0k4E)

we should also show the top banner and link to the app that needs to be reinstalled

![CleanShot 2024-02-13 at 22 24 52@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3edd4272-7744-487b-b064-98ba487aaec5/7e4838ba-7c02-4874-a5b0-451168760301?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zZWRkNDI3Mi03NzQ0LTQ4N2ItYjA2NC05OGJhNDg3YWFlYzUvN2U0ODM4YmEtN2MwMi00ODc0LWE1YjAtNDUxMTY4NzYwMzAxIiwiaWF0IjoxNzA3ODYzMTU4LCJleHAiOjE3MDc5NDk1NTh9.lDLXtErFm2xFi1PoYfyyzNiBAR-Wr3c4DvCXDRGoYRA)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3125](https://linear.app/calcom/issue/CAL-3125/show-top-banner-for-broken-integrations)</sub>

**Comment by PeerRich** [comment]
oh instead "Click here to stop" it should say something different

in general, not happy with the copy, should we change both sentences?

**Comment by ciaranha** [comment]
What about..

> It looks like permissions expired or were revoked for {App name}. _Reinstall app_

**Comment by VenkateshSircilla123** [comment]
> oh instead "Click here to stop" it should say something different
> 
> in general, not happy with the copy, should we change both sentences?

how is it , if we replace this "reinstall" link instead "click here to stop"

**Comment by TheVixhal** [comment]
> oh instead "Click here to stop" it should say something different
> 
> in general, not happy with the copy, should we change both sentences?

Uh Oh, [App Name]'s Not Feeling Well! Give it a Dose of [Reinstallation Medicine](url)

**Comment by VenkateshSircilla123** [comment]
> oh instead "Click here to stop" it should say something different
> 
> in general, not happy with the copy, should we change both sentences?

![Screenshot from 2024-02-16 11-47-39](https://github.com/calcom/cal.com/assets/113850972/f42f9f36-54a5-4fe5-9df6-f231fc06aed0)

how is this? when we click on "Go to app" link it will take you to app details
