### ISSUE TITLE
[CAL-3131] Profile Switcher Support - Allowing a user to be added to multiple organizations.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#13671]
Right now profile switcher is't enabled.

Current Status

* We have profile table now that allows us to create any number profiles for a user
* It allows us to invite an existing user to an organization and create his profile.

What's Pending

* We are only storing the creator **profileId** for EventType. We need to do the same for all other entities
  * Workflows
  * Routing Forms
  * Bookings
  * …….. and many more
* We also need to change the querying logic to ensure that the profileId is included in there. This is similar to what we did for querying viewer/event-types/getByViewer.
* After we are done with making these changes, we could then enable profile switcher.

More details in v2.0 Release for new schema

[https://docs.google.com/document/d/1ii3eyn0F0LaUCrX1c58YgdMt2V7xZWI2AGX1yKKM2Ik/edit#heading=h.t0b99gdcznsi](https://docs.google.com/document/d/1ii3eyn0F0LaUCrX1c58YgdMt2V7xZWI2AGX1yKKM2Ik/edit#heading=h.t0b99gdcznsi)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3131](https://linear.app/calcom/issue/CAL-3131/profile-switcher-support-allowing-a-user-to-be-added-to-multiple)</sub>

**Comment by PeerRich** [comment]
nice, however i dont think many people anytime soon will be in two organizations, so if thats the only requirement we can deprioritize this a bit

**Comment by PeerRich** [comment]
after an org claims a personal account, why do we want to keep the personal account alive? can we not disable it and basically "claim" all links. we can send an email notifying the owner that their account has been claimed and that if they want personal bookings, they should make a new account
