### ISSUE TITLE
[CAL-3134] ability to mark guests as no-show

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13677]
![image](https://github.com/calcom/cal.com/assets/8019099/c8bcca3d-3be9-4c34-b2bf-3671cafa6a4b)

click will open a dropdown:

* "copy email"
* "mark as no-show"

![image](https://github.com/calcom/cal.com/assets/8019099/2fe63944-9997-4951-8518-927ff74311e0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3134](https://linear.app/calcom/issue/CAL-3134/ability-to-mark-guests-as-no-show)</sub>

**Comment by Udit-takkar** [comment]
duplicate issue https://github.com/calcom/cal.com/issues/13573

**Comment by PeerRich** [comment]
lets also add the statistics here as a new panel and new line:
![CleanShot 2024-03-16 at 18 16 49@2x](https://github.com/calcom/cal.com/assets/8019099/60fecb18-5da0-42af-963c-8e2640493027)

**Comment by PeerRich** [comment]
and a noshow leaderboard 

![CleanShot 2024-03-16 at 18 18 24@2x](https://github.com/calcom/cal.com/assets/8019099/d356aad9-724a-4c64-a0c6-6b1f666f72d6)

**Comment by PeerRich** [comment]
i just realised we need two types of noshows:

Host No-Show
Guest No-Show

**Comment by shirazdole** [comment]
Will there be a webhook to send this no show data to other places like a CRM for example? Or only lives within cal.com for now?

**Comment by shirazdole** [comment]
@alishaz-polymath will this be ready by the 15th? Just need to know how to communicate timeline to customer

**Comment by alishaz-polymath** [comment]
@shirazdole unlikely. Currently higher priority ticket is being handled. This is next, but unlikely that this will be done by 15th this month
