### ISSUE TITLE
[CAL-3135] Email embed not showing available slots

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13679]
<img width="1353" alt="Screenshot 2024-02-14 at 11 50 22" src="https://github.com/calcom/cal.com/assets/97884287/999fadd2-8cae-4074-825b-7253052d8f24">
<img width="1347" alt="Screenshot 2024-02-14 at 11 50 29" src="https://github.com/calcom/cal.com/assets/97884287/5657957a-01da-4343-b0c6-a5dc96e6163c">

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3135](https://linear.app/calcom/issue/CAL-3135/email-embed-not-showing-available-slots)</sub>

**Comment by NateHutchison** [comment]
not sure if I should make a new one or this is related, but I have the following issue with email embed as well, where it shows the day before even if you select a day and time:
![image](https://github.com/calcom/cal.com/assets/15898888/42c5a2b1-662c-468f-a148-bb89dc239ad1)

**Comment by CarinaWolli** [comment]
@Udit-takkar is this already fixed with https://github.com/calcom/cal.com/pull/13917?

**Comment by Udit-takkar** [comment]
@CarinaWolli yeah that PR should fix it if the user was part of any organization

**Comment by CarinaWolli** [comment]
> @CarinaWolli yeah that PR should fix it if the user was part of any organization

It's a team not an organization, so I guess this is still open then
