### ISSUE TITLE
[CAL-3128] Attendee address and phone number field not shown in booking questions

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#13670]
### Issue Summary

When choosing 'In Person (Attendee Address)' or 'Attendee phone number' as an event location this field should show as a booking question (advanced tab). Right now, it's not shown and can't be edited.

### Steps to Reproduce

1. Create event type
2. Change location to In Person (Attendee Address)
3. Go to Advanced and see that the booking question for the Attendee Adress is not shown

<sub>[CAL-3128](https://linear.app/calcom/issue/CAL-3128/attendee-address-and-phone-number-field-not-shown-in-booking-questions)</sub>

**Comment by Adityaupadhye** [comment]
@CarinaWolli can you please share a screenshot of this bug.

**Comment by CarinaWolli** [comment]
Location set: 
![Screenshot 2024-02-14 at 11 07 08 AM](https://github.com/calcom/cal.com/assets/30310907/814e0e38-ee9b-4f7e-a6e1-d2175e3bdfe3)

Adds a new field on the booking page:
![Screenshot 2024-02-14 at 11 07 51 AM](https://github.com/calcom/cal.com/assets/30310907/2e6b4076-bb82-40a2-a0bc-c1dddf9f292a)

But doesn't show in booking questions to move the position or edit the label
![Screenshot 2024-02-14 at 11 08 24 AM](https://github.com/calcom/cal.com/assets/30310907/1f412343-fa80-452c-b908-f4b87b978768)

**Comment by Pritam-sd-dev** [comment]
hi,
i have started working on this issue.

**Comment by CarinaWolli** [comment]
> @CarinaWolli Not sure whether its really a bug because this was deliberately done in this PR https://github.com/calcom/cal.com/pull/7734. And we show the field when 2 or more location fields are added

Thank you for pointing that out. This fix was for having locations without and input field, meaning if there is only one then we don't want the a booking question as there is nothing for the user to do on the booking page. But if the location requires input from the user like attendee's phone number or address then we should show the booking question
