### ISSUE TITLE
[CAL-3141] (+1) badge not aligned

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13688]
the +N badge (+7) is too high

![CleanShot 2024-02-14 at 18 21 20@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ae789fc7-f328-46f4-942d-22f839779238/9ccfe569-a18c-478a-8a60-5e9e6a452fde?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hZTc4OWZjNy1mMzI4LTQ2ZjQtOTQyZC0yMmY4Mzk3NzkyMzgvOWNjZmU1NjktYTE4Yy00NzhhLThhNjAtNWU5ZTZhNDUyZmRlIiwiaWF0IjoxNzA3OTM0OTYxLCJleHAiOjE3MDgwMjEzNjF9.PG2Z2fds2kjhyDiczEfSPrFuQxH1700IPdrmnabx2dw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3141](https://linear.app/calcom/issue/CAL-3141/1-badge-not-aligned)</sub>

**Comment by Pritam-sd-dev** [comment]
@PeerRich where is this part present on ui.

**Comment by Pritam-sd-dev** [comment]
@PeerRich 
.....

**Comment by RabihJabr29** [comment]
Hello @PeerRich ,
The image URL is broken, can you provide a new one?
