### ISSUE TITLE
Contributors Docs Guide not found

### ISSUE THREAD

**Issue by RabihJabr29** [calcom/cal.com#13714]
### Issue Summary
Requesting https://docs.cal.com/docs/docs/knowledgebase/contributors-guide/quick-start return a 404 not found error.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

Simply access https://docs.cal.com/docs/docs/knowledgebase/contributors-guide/quick-start

Or how I found the bug...

1. Go to https://docs.cal.com/docs

2. Click on "Get Started"
![image](https://github.com/calcom/cal.com/assets/52083785/760d8855-f8d0-4123-b91b-77c2dfc74bb3)

3. Then click on "Quick Start for contributors"
![image](https://github.com/calcom/cal.com/assets/52083785/f63b980c-ee73-455c-a263-efd560d316b1)

4. Then you get this page
![image](https://github.com/calcom/cal.com/assets/52083785/e0ffc5a4-d24a-48eb-a388-fd2592636fad)

**Comment by shravan20** [comment]
It is available: https://docs.cal.com/docs/knowledgebase/contributors-guide#priorities

This issue would essentially be part of [calcom-docs-repo](https://github.com/calcom/docs), if I am not wrong.

**Comment by RabihJabr29** [comment]
Yes it is available when accessing it from another place (Search).
I will move this issue from here to the other repo.
Thanks @shravan20 for pointing it out!

**Comment by shravan20** [comment]
> > It is available: https://docs.cal.com/docs/knowledgebase/contributors-guide#priorities
> > This issue would essentially be part of [calcom-docs-repo](https://github.com/calcom/docs), if I am not wrong.
> 
> where should we raise a pr if some issue is there in cal.com docs

It would go as PR to this repo - https://github.com/calcom/docs
