### ISSUE TITLE
[CAL-3152] Give ORG Owners the Ability to lock Event-Types

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#13716]
Some org customers are offering scheduling for hundreds of users and want users to only use their org account [acme.cal.com/user](http://acme.cal.com/user) for booking meetings related to their business.

Therefore, they don't want them to create other event-types for other purposes. They just want to use managed-event types that users can use to book meetings.

Proposal — give admins/owners the ability to lock personal event-type creation for all users in an organization.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3152](https://linear.app/calcom/issue/CAL-3152/give-org-owners-the-ability-to-lock-event-types)</sub>

**Comment by PeerRich** [comment]
i like this. essentially what you mean: only allow managed event-types, disable existing personal links?

**Comment by PeerRich** [comment]
where should this setting be? what happens to old links? block them? hide them? delete them?

**Comment by shirazdole** [comment]
@peer correct, I'm not sure what happens to old links, maybe we can give it as an option to owers/admins to decide?

**Comment by ciaranha** [comment]
> where should this setting be? what happens to old links? block them? hide them?

I think this should probably live under **General** under the **Org** in settings. We can provide an option to "lock" or "turn off" personal event-type creation. When they toggle it, we could present a modal that offers them a choice of what to do with existing links and essentially whether to keep or delete them.

**Comment by shirazdole** [comment]
@keithwillcode I don't think these are duplicative, one is for availability, the other is for event-types

**Comment by keithwillcode** [comment]
Oh my fault!

**Comment by sean-brydon** [comment]
Ill take this and [CAL-3086](https://linear.app/calcom/issue/CAL-3086/give-org-owners-the-ability-to-lock-availability) next week

**Comment by alishaz-polymath** [comment]
Maybe just redirect old links to the user's public booking page where they should have the managed event types 🤔

**Comment by PeerRich** [comment]
do we really need to force this? can we not tell org admins to make managed-event types and tell their team to not use other links

**Comment by PeerRich** [comment]
since we have a very short connection between org owners usually and we can help during onboarding

**Comment by shirazdole** [comment]
@PeerRich sure no problem 👌🏽 that sounds good and makes sense

**Comment by PeerRich** [comment]
i just learned that the PR is almost ready so we can just have @sean-brydon ship this

**Comment by PeerRich** [comment]
i would never delete links as an admin tho. we can hide private events instead

**Comment by ciaranha** [comment]
> i would never delete links as an admin tho. we can hide private events instead

Pretty sure Sean was allowing for that option.
