### ISSUE TITLE
[CAL-3149] Double and triple entries in calendar/bookings tab

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13710]
![Screenshot 2024-02-15 at 15.21.56.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9987be91-fafd-407d-aabc-cfe708c59423/ff88e49a-e270-4e8b-bff9-5f685db6bf4b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85OTg3YmU5MS1mYWZkLTQwN2QtYWFiYy1jZmU3MDhjNTk0MjMvZmY4OGU0OWEtZTI3MC00ZThiLWJmZjktNWY2ODVkYjZiZjRiIiwiaWF0IjoxNzA4MDA3MDE4LCJleHAiOjE3MDgwOTM0MTh9.OxpCNfKwg72MPnqG-SidvqRWlksQTMpnpybHhqGdb0A)

![Screenshot 2024-02-15 at 15.22.06.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1be3bff5-7971-4a0c-afa2-1e20ab3c6cf5/5980910b-b6ac-4f87-b74c-24ab997ebd8d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xYmUzYmZmNS03OTcxLTRhMGMtYWZhMi0xZTIwYWIzYzZjZjUvNTk4MDkxMGItYjZhYy00Zjg3LWI3NGMtMjRhYjk5N2ViZDhkIiwiaWF0IjoxNzA4MDA3MDE4LCJleHAiOjE3MDgwOTM0MTh9.zAR5DnRaKIfiBSflTGLdXxTUDPYIhwMls8XWlM4E2J4)

![Screenshot 2024-02-15 at 15.22.26.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e573ab38-d5e0-4041-a090-d3e586db353b/c10c0a66-7416-4e94-91ca-356da7678f60?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNTczYWIzOC1kNWUwLTQwNDEtYTA5MC1kM2U1ODZkYjM1M2IvYzEwYzBhNjYtNzQxNi00ZTk0LTkxY2EtMzU2ZGE3Njc4ZjYwIiwiaWF0IjoxNzA4MDA3MDMxLCJleHAiOjE3MDgwOTM0MzF9.St1mtQMVFaMAteNeZFldnDypdqtHU3QHxkN44JekVX0)

[cal.com/capital](http://cal.com/capital)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3149](https://linear.app/calcom/issue/CAL-3149/double-and-tripple-entries-in-calendarbookings-tab)</sub>

**Comment by ryanfurrer** [comment]
Commenting here that I experienced the same thing on two difference occasions, each one a different event (one 15-minute chat, one 60-minute chat).

[Ryan Furrer's Cal](https://cal.com/ryandotfurrer)

**Comment by GetGankNow** [comment]
Same here.

**Comment by keithwillcode** [comment]
We've released #13865 which should prevent this from happening. Will close for now and reopen if new reports come through.

**Comment by ciaranha** [comment]
I booked a meeting today with someone and it went on my calendar 3 times

![CleanShot 2024-02-28 at 15.52.39@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e0077483-8fc8-4120-91c8-6a8938ee570c/f88697dd-262b-4d9c-995f-ef47e6a26408)
