### ISSUE TITLE
Meeting start times - end of day times ignored

### ISSUE THREAD

**Issue by ksfraser** [calcom/cal.com#1373]
Scenario:
I have multiple meeting lengths available.  Testing the 2 hour (120 minutes) meeting, I discovered I could book a meeting 1 hour before the end of the day.  This was using the default block length (advanced settings).

Similarly, when using 15 minute block sizes I am shown an 8:45pm meeting start time for a 2 hour meeting when end of day is 9pm.

**Comment by PeerRich** [comment]
i believe this was fixed a long time ago. can you try again?
