### ISSUE TITLE
[CAL-3173] resource booking / checking multiple calendars

### ISSUE THREAD

**Issue by mokkin** [calcom/cal.com#13745]
Our available places in our current booking system are

1. phone
2. online
3. office 1
4. office 2

If a customer selects `phone` or `online` just the availability of the employee has to be checked, but if one of the offices is selected and the customer wants a meeting in person, a resource needs to be checked as well.
In our current system both - employees and rooms - are separate CalDav calendars in our Nextcloud. In case a personal meeting is selected, the conference room is checked and booked too.

In my opinion this is a very important feature and essential for cal.com too. The same applies for other resources than rooms such as projectors, cars or medical equipment.

<sub>[CAL-3173](https://linear.app/calcom/issue/CAL-3173/resource-booking-checking-multiple-calendars)</sub>

**Comment by keithwillcode** [comment]
@ciaranha for approval

**Comment by ciaranha** [comment]
This is a great request and something we're likely to do at some stage. I'm not sure it will fall on the very near term roadmap though as there's likely a decent amount of complexity to it and I've never seen this request before.

I would love to hear if any other customers have requested this as that could well change the priority. @milospuac or @shirazdole has this ever come up on your side  before?

**Comment by ciaranha** [comment]
> In case a personal meeting is selected, the conference room is checked and booked too.

I wonder could this be resolved by using a team event type with a round robin by setting "Fixed host" on the employee and "Round robin" on the conference rooms... 🤔

**Comment by mokkin** [comment]
I'm happy that you like the feature request :smile: 
But I'm also surprised that nobody had this or a similar request before? This feature is quite common and other appointment booking systems like [Calendly](https://help.calendly.com/hc/en-us/articles/12303248557719-Scheduling-with-Conference-Rooms#scheduling-with-conference-rooms-0-0) or [eTermin](https://support.etermin.net/hc/de/articles/360001622591-Wie-kann-ich-zus%C3%A4tzliche-Ressourcen-Ger%C3%A4te-oder-R%C3%A4ume-bei-der-Buchung-belegen-lassen) do offer that.

**Comment by ciaranha** [comment]
> I'm happy that you like the feature request 😄 But I'm also surprised that nobody had this or a similar request before? This feature is quite common and other appointment booking systems like [Calendly](https://help.calendly.com/hc/en-us/articles/12303248557719-Scheduling-with-Conference-Rooms#scheduling-with-conference-rooms-0-0) or [eTermin](https://support.etermin.net/hc/de/articles/360001622591-Wie-kann-ich-zus%C3%A4tzliche-Ressourcen-Ger%C3%A4te-oder-R%C3%A4ume-bei-der-Buchung-belegen-lassen) do offer that.

Interesting, looks like Calendly also adds the conference room as a user as I suggested above. I need to investigate but I think this means we can already do this in cal.com.
