### ISSUE TITLE
[CAL-3172] Make more options available for durations.

### ISSUE THREAD

**Issue by dupemacaulay** [calcom/cal.com#13746]
### Is your proposal related to a problem?

I'm using [cal.com](http://cal.com) for my location rental business. I'd like people to be able to book slots ranging from 2 hours long to a full day (8 hours). Right now, I can do some of  that with a single event type - 2 hours, 3 hours, 4 hours, and 8 hours. But I need to create new event types for 5 hours, 6 hours, and 7 hours.

### Describe the solution you'd like

I'd like Cal to include the option for 300 minutes, 360 minutes, and 420 minutes in the available durations drop-down, so my customers can book their preferred number of hours. Another option is to let me (the organiser) create custom durations that the user can pick from.

### Describe alternatives you've considered

The alternative is to create a different event type for each duration, which isn't a great experience for the user.

### Additional context

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5681bd8a-c3f5-4765-b80a-6d7db4082831/48ce8d95-4091-4c94-a07c-5221a80abd4a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81NjgxYmQ4YS1jM2Y1LTQ3NjUtYjgwYS02ZDdkYjQwODI4MzEvNDhjZThkOTUtNDA5MS00Yzk0LWEwN2MtNTIyMWE4MGFiZDRhIiwiaWF0IjoxNzA4NDE0ODkxLCJleHAiOjE3MDg1MDEyOTF9.10qUcLTOKnCLfDr0jERf_DTonGyqBw-HHd9l76apWPM)

---

##### House rules

* If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  * For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  * Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3172](https://linear.app/calcom/issue/CAL-3172/make-more-options-available-for-durations)</sub>

**Comment by Zafeeruddin** [comment]
hey can i work on this?

**Comment by keithwillcode** [comment]
Cc @ciaranha for approval on this

**Comment by ciaranha** [comment]
Yes we should do this. Added "needs design" in order to explore whether we should just add additional options or go the likely more preferred route of adding the "custom" option.
