### ISSUE TITLE
[CAL-3183] Better Error Message/Response

### ISSUE THREAD

**Issue by alvnrapada** [calcom/cal.com#13747]
### Issue Summary

I tried to create a new booking [via api](https://cal.com/docs/enterprise-features/api/api-reference/bookings#create-a-new-booking) twice with the same parameters expecting I would get an error message stating that the slot was taken or duplicate booking.

### Actual Results

* I got a `no_available_users_found_error` which is totally not related to what I did.

### Expected Results

* An error message stating that the slot was taken or duplicate booking

Error when running the api the 2nd time with same param:

![Screenshot 2024-02-19 at 2 45 28 PM](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7d41110d-1dd9-4758-b836-3242abcd516d/3cc6b703-2ac1-4dc9-94d5-d7565667c5de?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83ZDQxMTEwZC0xZGQ5LTQ3NTgtYjgzNi0zMjQyYWJjZDUxNmQvM2NjNmI3MDMtMmFjMS00ZGM5LTk0ZDUtZDc1NjU2NjdjNWRlIiwiaWF0IjoxNzA4NTIyODkzLCJleHAiOjE3MDg2MDkyOTN9.4eMmpkXoWJ0JO-MNpoVlcfPcx5BbeyQGmK20Cm00TSw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3183](https://linear.app/calcom/issue/CAL-3183/better-error-messageresponse)</sub>

**Comment by keithwillcode** [comment]
I’m currently working on fixing this
