### ISSUE TITLE
[CAL-3165] Bug with recurring bookings with seats enabled

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#13758]
How to reproduce? 

1. Create recurring event type with 10 seats enabled 
2. Book one seat with for example 5 occurrences 
3. Use another email to book the same seats again 
4. On the booking details page you see that the new attendee was assigned several times. If you go to availability page you see that only 4 seats out of the then area available now

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3165](https://linear.app/calcom/issue/CAL-3165/bug-with-recurring-bookings-with-seats-enabled)</sub>

**Comment by Pritam-sd-dev** [comment]
@CarinaWolli 
Thank you for taking the time to open the GitHub issue. Your contribution is invaluable in helping us improve our project. We appreciate your feedback and look forward to addressing the issue promptly.

**Comment by Pritam-sd-dev** [comment]
i have started working on it, will be resolved asap.
