### ISSUE TITLE
[CAL-3175] og-image broken for website and for app.cal.com

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13777]
[https://www.opengraph.xyz/url/https%3A%2F%2Fcal.com%2Fpeer](https://www.opengraph.xyz/url/https%3A%2F%2Fcal.com%2Fpeer)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/72fa69c4-efb6-42a3-b392-f61aa5695a37/0a833193-c581-43fe-9a6e-e9aa76e5c3e3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83MmZhNjljNC1lZmI2LTQyYTMtYjM5Mi1mNjFhYTU2OTVhMzcvMGE4MzMxOTMtYzU4MS00M2ZlLTlhNmUtZTlhYTc2ZTVjM2UzIiwiaWF0IjoxNzA4NDIxMDQzLCJleHAiOjE3MDg1MDc0NDN9.r-N_UmJzCUPucqUbqCIctvmgf_XXSLMEmj4WbRrT5qI)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c3851f8f-e63d-4061-b9b8-3e043d025d4d/adb61c21-d3f6-4b8d-9483-eddbccabaf78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jMzg1MWY4Zi1lNjNkLTQwNjEtYjliOC0zZTA0M2QwMjVkNGQvYWRiNjFjMjEtZDNmNi00YjhkLTk0ODMtZWRkYmNjYWJhZjc4IiwiaWF0IjoxNzA4NDIxMDQzLCJleHAiOjE3MDg1MDc0NDN9.NyCvkKwPdJ9RlT0hUGm9sCtwlbpj5d4yZqQ5t29MPZ0)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3dbe6157-0c61-40ae-87b5-2c1ad9b1aed4/d11abdab-62ce-4e9b-ac2d-21bc0b949bd6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zZGJlNjE1Ny0wYzYxLTQwYWUtODdiNS0yYzFhZDliMWFlZDQvZDExYWJkYWItNjJjZS00ZTliLWFjMmQtMjFiYzBiOTQ5YmQ2IiwiaWF0IjoxNzA4NDIxMDQzLCJleHAiOjE3MDg1MDc0NDN9.1vHX6PjqvASmcXL80c51CXctes5zGOt8V39ZBrskqLo)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3175](https://linear.app/calcom/issue/CAL-3175/og-image-broken-for-website-and-for-appcalcom)</sub>

**Comment by keithwillcode** [comment]
> Already fixed here #13790

It’s still broken for @PeerRich. @zomars tested his own and it worked fine but something it still wrong

**Comment by zomars** [comment]
Can confirm this is fixed now:

![image](https://github.com/calcom/cal.com/assets/3504472/36a033b3-bc2c-4d15-ba37-2f66c0427a1b)
