### ISSUE TITLE
[CAL-3184] {{consoleUrl}} and {{supportMail}} not rendering correctly (in Portugese, maybe more languages)

### ISSUE THREAD

**Issue by GiovaniMaia** [calcom/cal.com#13771]
Hello everyone, I installed [cal.com](http://cal.com) today on my server and I need to send requests through an integration to the tool, but when trying to add the API it generates this error, does anyone know how to solve it?

To enable this feature, get a development key from the {{consoleUrl}} console and add it to your .env as CALCOM_LICENSE_KEY. If your team already has a license, contact {{supportMail}} for help.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5372ce78-c807-4d6a-a8c4-d29eeecf65b6/63869860-f480-4896-995c-0bda24ce868d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81MzcyY2U3OC1jODA3LTRkNmEtYThjNC1kMjllZWVjZjY1YjYvNjM4Njk4NjAtZjQ4MC00ODk2LTk5NWMtMGJkYTI0Y2U4NjhkIiwiaWF0IjoxNzA4NTIzMDI3LCJleHAiOjE3MDg2MDk0Mjd9.j-WhGz2pOtObQvnOzGAAD6axWhppkPyD6uUSfTOFuDY)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3184](https://linear.app/calcom/issue/CAL-3184/consoleurl-and-supportmail-not-rendering-correctly-in-portugese-maybe)</sub>

**Comment by PeerRich** [comment]
did you make changes to your .env.example by any chance?

**Comment by GiovaniMaia** [comment]
negative, I only did it in .env
