### ISSUE TITLE
[CAL-3174] Email embed selector displaying the previous day

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#13776]
I think this is timezone related because when I impersonated this customer it was working fine. But this is the screenshot he sends

![Screenshot 2024-02-20 at 09.54.01.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3f86dede-73cb-4f6b-a207-a9cf18d062a8/c4d3e653-615a-47f6-a6cb-5821d170181a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zZjg2ZGVkZS03M2NiLTRmNmItYTIwNy1hOWNmMThkMDYyYTgvYzRkM2U2NTMtNjE1YS00N2Y2LWE2Y2ItNTgyMWQxNzAxODFhIiwiaWF0IjoxNzA4NDE5OTgzLCJleHAiOjE3MDg1MDYzODN9.O9AH4vHa9W6oXaI2rpUsRHKHefXHjZB9XktDdLJgWeE)

Customer: jinyan-zang

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3174](https://linear.app/calcom/issue/CAL-3174/email-embed-selector-displaying-the-previous-day)</sub>

**Comment by ejm554** [comment]
I'm experiencing this also. 

**_Question: Can I workaround it by manually editing the (incorrectly) displayed day in my email message?_**

FWIW, here's a screenshot illustrating the issue:

![screenshot of Email Embed window with markups illustrating the issue](https://github.com/calcom/cal.com/assets/26723535/6f079888-8b98-4a90-b907-096d84597667)

FYI, when I hover over the time slot button, e.g., 10:00am, in the Preview section, it appears that the related link is referencing the _correct_ day: 

`https://cal.com/xxx?duration=30&date=2024-03-26&month=2024-03&slot=2024-03-26T15:00:00.000Z`

**Comment by Udit-takkar** [comment]
> I'm experiencing this also.
> 
> **_Question: Can I workaround it by manually editing the (incorrectly) displayed day in my email message?_**
> 

I have found the issue and opened the PR for this
