### ISSUE TITLE
add alerts in calendar events

### ISSUE THREAD

**Issue by jcolomb** [calcom/cal.com#13781]
### Is your proposal related to a problem?

I am missing meetings because the events added to my calendar do not have any alerts.

### Describe the solution you'd like

I would like the default event to have an alert 5 minutes before start.
This would be added in the advanced option for the event setup.

(Describe your proposed solution here.)

### Describe alternatives you've considered

One can do workflows, but that is not ideal, as I do not read my emails that often (calendar notifications are going through the focus work option I often use.

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by Udit-takkar** [comment]
> I am missing meetings because the events added to my calendar do not have any alerts.

Thats odd. I do get calendar alerts on my phone before the meeting

**Comment by PeerRich** [comment]
same. i think this is your calendar settings?

**Comment by PeerRich** [comment]
which calendar are you using?

**Comment by jcolomb** [comment]
Oh indeed, there seem to be an alert 5min before as default, sorry.

(It did not work for me - I do not know why-, so I looked at a way to add alerts but could not find one, then saw someone asking for it on discord -probably an old message- and thought there was nothing.)

There is no way to change the alert though ? (10 minutes instead of 5 for example).

**Comment by jcolomb** [comment]
Hello,

I got the issue again. 

- I am using a google calendar, it does not add reminders. I do not see any settings in google calendar related to default reminder for new events...
- tested 3 different event types, also with one created just now.

**Comment by jcolomb** [comment]
this is something with google calendar, if I use an icloud calendar, the alert 5 min before start is there.
