### ISSUE TITLE
detect timezone and choose am/pm or 24h per event type

### ISSUE THREAD

**Issue by maishumanos** [calcom/cal.com#1378]
I don’t have coding skills but I would like to suggest a feature:

The ability to preset the display am/pm or 24h time format on the event time page.

I’m saying this because the user option to change the time format is hidden under the Timezone selector on the booking page and in some countries (like Brasil for example) the 24h format is more popular. We do often have people that got confused with the am/pm nomenclature (people here who don't speak english often doesn't know if am is before or after the lunch time for example)!

Maybe it can have this preset and also give the user the ability to change based on their own preferences during the booking but showing the am-pm / 24h button somewhere is not so hidden.

Thank you guys!

Edit by @PeerRich: we've decided to detect the local timezone and show 24hrs or am/pm based on the booking persons location, not what someone has preset in the settings

**Comment by PeerRich** [comment]
yep. planned!

**Comment by PeerRich** [comment]
instead of making it a setting in event-types, we will use the locale timezone of the link receiver and show either am/pm or 24h

**Comment by AlexRoehm** [comment]
Proposal: The default setting could be part of the user profile (where you also find the timezone default)

**Comment by PeerRich** [comment]
> Proposal: The default setting could be part of the user profile (where you also find the timezone default)

yes but for the booking page it should be based on the guests timezone, no?

**Comment by AlexRoehm** [comment]
> > Proposal: The default setting could be part of the user profile (where you also find the timezone default)
> 
> yes but for the booking page it should be based on the guests timezone, no?

True

**Comment by PeerRich** [comment]
so yeah @maishumanos  and @AlexRoehm this is coming, just not as a dropdown but location-checked. 

for the dashboard (your own timezone) + booking page (timezone of the guest)

**Comment by maishumanos** [comment]
Hi Peer, this is amazing!

And reading what you said, I had another idea: 

The language of the booking page could also be defined based on the guest location! 

I don't know how much effort is needed but this would be a cool feature! :)

Thank you guys and I wish to you all a happy new year!

**Comment by PeerRich** [comment]
yes that is planned. based on guests location

**Comment by agustif** [comment]
Hey, I'll start working on this now, we should have a good solution for it soon.
