### ISSUE TITLE
Element Call plugin behaves unexpected

### ISSUE THREAD

**Issue by MTRNord** [calcom/cal.com#13780]
### Issue Summary

The Element Call Plugin seems to only have a single global call.
In the jitsi calls this is solved a lot nicer by having a call per event (even generated after confirmation only).

Having one global/per event type call also comes with privacy issues as someone can just remember/keep it and join it at any time. It would be nicer if it could be closer to the jitsi one. I believe in element call you cant just stick a random string to the url so it might need to be an input on confirmation or something.

### Technical details

- This is tested on the hosted cal.com version.

**Comment by VenkateshSircilla123** [comment]
give me steps to reproduce

**Comment by shashank40** [comment]
Hey @MTRNord!
Can you please let me know how to reproduce so that i can take an attempt to fix it?

**Comment by MTRNord** [comment]
I believe all information was given in the initial post hence no reply before. Please read what I wrote. This is not even a bug so there isnt much to reproduce. Its a feature request about matching the flow with the other apps as you would have seen in the initial post .

**Comment by AmanSal1** [comment]
@MTRNord Is the issue available?

**Comment by MTRNord** [comment]
Closing as it attracts spam...

**Comment by pReya** [comment]
@MTRNord Can you open it again (even though it attracts Spam)? It's still relevant, and it's even worse: The existing extension doesn't do anything at all. It's not creating ANY meeting IDs. It just contains a static link to `call.element.io`. See original PR here: https://github.com/calcom/cal.com/pull/10585/files
