### ISSUE TITLE
New Event modal appears blurred

### ISSUE THREAD

**Issue by teyim** [calcom/cal.com#13783]
### Issue Summary

The modal for creating a new event type appears blurred

### Steps to Reproduce

1. Click on event types on the dashboard
2. Click on the new button in the top right-hand corner of the screen

### Actual Results

- The modal appears blurred.

### Expected Results

- The modal should be visible while its background blurred out

### Evidence

![Screenshot from 2024-02-20 12-44-34](https://github.com/calcom/cal.com/assets/48864977/ce363169-0759-4158-8811-76ec9b95bece)

The blurry nature of the modal might not be very visible on this screenshot.

**Comment by teyim** [comment]
Would like to fix this .

**Comment by PeerRich** [comment]
cannot reproduce this 🤔 feel free to fix but my modals look fine

**Comment by teyim** [comment]
hmm, that's strange.. I'll open a PR to fix this.

**Comment by hichemfantar** [comment]
Can confirm this. the issue should be fixed by #15919
