### ISSUE TITLE
[CAL-3197] The Url input field overflows when updating profile

### ISSUE THREAD

**Issue by jainakshitagithub** [calcom/cal.com#13786]
### Issue Summary

The URL input field overflows when the URL is very long, breaking the UI.

### Steps to Reproduce

1. Go to My setting
2. Clicked on Profile
3. Update the input field of URL

### Actual Results

1. The URL field overflows horizontally breaking the UI
2. Check in the popup and the also in the events edit section

### Expected Results

1. The URL field should accommodate long URL strings.

### Evidence

![2024-02-20](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/31f737c8-137d-4388-aa77-9a33cbec2d48/e08fa30b-c2dd-4cfb-88f7-894875b91e2c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMWY3MzdjOC0xMzdkLTQzODgtYWE3Ny05YTMzY2JlYzJkNDgvZTA4ZmEzMGItYzJkZC00Y2ZiLTg4ZjctODk0ODc1YjkxZTJjIiwiaWF0IjoxNzA4NjA2NTg3LCJleHAiOjE3MDg2OTI5ODd9.EA1O638qqsk99cl6wm17rmKvU38_bRk2CSpAfhxnNOw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3197](https://linear.app/calcom/issue/CAL-3197/the-url-input-field-overflows-when-updating-profile)</sub>

**Comment by Ekam219** [comment]
@jainakshitagithub may i work on this issue?

**Comment by IshThumber** [comment]
hey @Ekam219 I would like to work on this issue.
May I work?

**Comment by PeerRich** [comment]
feel free to truncate

**Comment by Vaibhav-Kumar-K-R** [comment]
I want to work in this issue

**Comment by vishalranka2003** [comment]
is the issue closed ?

**Comment by KushagraSn2004** [comment]
closed??

**Comment by Lucifer4255** [comment]
is this issue still open??

**Comment by saurabhraj123** [comment]
Can someone please help me setting up cal.com? When I am running `yarn dx`, I am getting error everytime.. @Lucifer4255  @keithwillcode  @vishalranka2003  @subhanahujha007 @PeerRich

**Comment by niks-nikhil-anand** [comment]
I have already done Pull request  and solved the issues , but some test is failed . Can you guide me through it .

**Comment by hybs123** [comment]
Hello
I want to work on this issue.
Can you please locate the file, I am having trouble to do so.
Also the file that contains CSS for this page too.

**Comment by Rameshk84** [comment]
Ok
