### ISSUE TITLE
[CAL-3181] Yarn build failure with 3.8.1 upwards

### ISSUE THREAD

**Issue by nebulade** [calcom/cal.com#13796]
While trying to build the app package for Cloudron for 3.8.1 (but also 3.8.2 now), our tests found a build failure:

```
@calcom/web:build: ../../packages/atoms/booker/wrappers/BookerWebWrapper.tsx:83:5
@calcom/web:build: Type error: Type '{ name: string | null; guests: string[] | undefined; }' is not assignable to type '{ guests: string[]; name: string | null; }'.
@calcom/web:build:   Types of property 'guests' are incompatible.
@calcom/web:build:     Type 'string[] | undefined' is not assignable to type 'string[]'.
@calcom/web:build:       Type 'undefined' is not assignable to type 'string[]'.
@calcom/web:build: 
@calcom/web:build:   81 |     hasSession,
@calcom/web:build:   82 |     extraOptions: routerQuery,
@calcom/web:build: > 83 |     prefillFormParams,
@calcom/web:build:      |     ^
@calcom/web:build:   84 |   });
@calcom/web:build:   85 |   const bookings = useBookings({
@calcom/web:build:   86 |     event,
@calcom/web:build: ERROR: command finished with error: command (/app/code/calcom/apps/web) yarn run build exited (1)
command (/app/code/calcom/apps/web) yarn run build exited (1)
```

This is with nodejs 18.18.0 if this matters for the type mismatch.

<sub>[CAL-3181](https://linear.app/calcom/issue/CAL-3181/yarn-build-failure-with-381-upwards)</sub>

**Comment by keithwillcode** [comment]
We will look now. Thanks for reporting and apologies for the error

**Comment by muskan2622** [comment]
Yes I faced the same issue.To fix this To fix this issue, we need to ensure that the guests property is always defined and is of type string[]. Ywe can do this by checking if guests is undefined and providing a default value or handling this case appropriately.

**Comment by keithwillcode** [comment]
Fixed in https://github.com/calcom/cal.com/pull/13798/files

**Comment by nebulade** [comment]
I can confirm patching the file fixes the problem also for us. Thanks!
