### ISSUE TITLE
[CAL-3182] save previous event-type slug and redirect

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13799]
same as with username changes, lets save the previous event-type slug

but only the previous.

also, it would be possible to overwrite it:

- old: /15min
- new: /15

means /15min redirects to /15 unless the user makes a new /15min

<sub>[CAL-3182](https://linear.app/calcom/issue/CAL-3182/save-previous-event-type-slug-and-redirect)</sub>

**Comment by Amit91848** [comment]
Duplicate #13497 ?
