### ISSUE TITLE
[CAL-3420] Google Event when rescheduled it got lost on my calendar.

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#13809]
### Issue Summary

Had a dynamic event made through cal.com appear on my Gcal, but when rescheduled email arrived and new event is no longer there.

### Steps to Reproduce

1. Book dynamic like on https://cal.com/alan+leog
2. Reschedule it.
3. Main calendar event removed but rescheduled didn't appear.
4. Email arrived with an event id but when opening link it appears event no longer exists.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
If it works for tracking the error I can provide this event id from google: "XzZkYjdpcWI5YjFsbWN1YmRkNHI2c29qYjlwMjdlY3I4OXBuazBncjFkZ242NnJyZCBhbGFubm5jQG0"

### Actual Results

- What's happening right now that is different from what is expected

Event should exists on my calendar after reschedule.

### Evidence

This is my bookingId on cal.com "hxH3uXqRfy3Hoh1pyxHXF1" that the error happened, probably worth checking some tables.

<sub>[CAL-3420](https://linear.app/calcom/issue/CAL-3420/google-event-when-rescheduled-it-got-lost-on-my-calendar)</sub>

**Comment by Pritam-sd-dev** [comment]
Thank you for taking the time to open the GitHub issue. Your contribution is invaluable in helping us improve our project. We appreciate your feedback and look forward to addressing the issue promptly.

**Comment by Pritam-sd-dev** [comment]
I have started working on it.

**Comment by Pritam-sd-dev** [comment]
@alannnc 
hi, i have just booked a time slot and after that also rescheduled, and it is also reflected on GCal.
