### ISSUE TITLE
debugging not working in vscode 

### ISSUE THREAD

**Issue by Pritam-sd-dev** [calcom/cal.com#13812]
### Steps to Reproduce
just go to vscode debug extension and run the app as shown in video.

### Technical details
- Node.js version : 18

### Evidence
https://www.loom.com/share/6feeaf29c2d14bf2a5ab086f74412200?sid=582caae0-7d35-483c-a56b-1b1b08e71a26

**Comment by PeerRich** [comment]
not related to our repo
