### ISSUE TITLE
Unable to PATCH event type metadata via API

### ISSUE THREAD

**Issue by mreilly-lula** [calcom/cal.com#13816]
### Issue Summary

I'm unable to PATCH event type `metadata` via the api.
```
curl --location --request PATCH 'https://api.cal.com/v1/event-types/{event_type_id}?apiKey={hands_off_my_keys}' \
--header 'Content-Type: application/json' \
--data '{
    "metadata": { "test": "true" }
}'
```

returns error
```
{
    "message": "Unrecognized key(s) in object: 'metadata'"
}
```

Thank you!

**Comment by keithwillcode** [comment]
This is by design. Are there specific fields in the metadata you want to patch or just wanting to put custom metadata there?

**Comment by mreilly-lula** [comment]
Oh I see. I was hoping to store custom metadata there after seeing it in the schema defined [here](https://cal.com/docs/enterprise-features/api/api-reference/event-types#edit-an-existing-event-type) but if that's not recommended, I will find an alternative solution

**Comment by mreilly-lula** [comment]
I see now where `metadata` is left out for edit [here](https://github.com/calcom/cal.com/blob/main/apps/api/lib/validations/event-type.ts#L113) but included for create [here](https://github.com/calcom/cal.com/blob/main/apps/api/lib/validations/event-type.ts#L82). Is POSTing event types with custom metadata included discouraged?

**Comment by keithwillcode** [comment]
It is discouraged, yes. We are currently working on building out a better model for saving custom metadata to records.
