### ISSUE TITLE
[CAL-3188] [CAL-3187] improvements to org member list

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13810]
- [ ] sticky actionbar in wrong place
![CleanShot 2024-02-21 at 19 27 50@2x](https://github.com/calcom/cal.com/assets/8019099/0f075c4f-28c3-4b82-a6ca-a2e5358d5360)

- [ ] make teams clickable and filterable, same as roles
![CleanShot 2024-02-21 at 19 25 49@2x](https://github.com/calcom/cal.com/assets/8019099/21147406-d3ba-4f49-a7c9-7b7630f0f1fd)

- [ ] thereby, change "Roles" to "Filters" because we are adding Teams as another filter

![CleanShot 2024-02-21 at 19 26 19@2x](https://github.com/calcom/cal.com/assets/8019099/cd274fff-24cd-4fc8-851c-45be786ea078)

- [ ] Change placeholder to "Filter"
- [ ] Add divider after roles and add teams
![CleanShot 2024-02-21 at 19 26 55@2x](https://github.com/calcom/cal.com/assets/8019099/333ad271-3650-4c94-9eb2-e902177477b6)

- [ ] add total members (only if it doenst slow us down like crazy)
![CleanShot 2024-02-21 at 19 24 51@2x](https://github.com/calcom/cal.com/assets/8019099/eb475d07-299b-4040-b209-548d5433d551)

- [ ] add pending here:
![CleanShot 2024-02-21 at 19 01 52@2x](https://github.com/calcom/cal.com/assets/8019099/17629d7f-9464-4f07-8f21-e2ca7b44898d)

- [ ] checkboxes not aligned
![image](https://github.com/calcom/cal.com/assets/8019099/67dde8cd-cbf1-46ee-a1db-67770e0b8bdd)

<sub>[CAL-3188](https://linear.app/calcom/issue/CAL-3188/[cal-3187]-improvements-to-org-member-list)</sub>

**Comment by Amit91848** [comment]
@CarinaWolli  Sorry I got busy with college, forgot to commit the changes for this.

> add pending here:
> ![image](https://github.com/calcom/cal.com/assets/74371312/272c58ed-404b-4bbf-8887-b49f425fd37b)

Will make another pr.
