### ISSUE TITLE
[CAL-3196] Cancelling 1 instance of a recurring event is not removing it from my Google cal

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#13827]
### Issue Summary

I have a recurring event setup for every 2 weeks. When cancelling 1 occurence of the event, it was removed from Cal.com but not from my Google calendar.

<sub>[CAL-3196](https://linear.app/calcom/issue/CAL-3196/cancelling-1-instance-of-a-recurring-event-is-not-removing-it-from-my)</sub>

**Comment by Pritam-sd-dev** [comment]
@CarinaWolli 
have you started working on it ?
please confirm it once so that i can pick this up.

**Comment by Pritam-sd-dev** [comment]
@CarinaWolli 
@keithwillcode 
i have checked by doing myself but everything is working fine in my case.

**Comment by CarinaWolli** [comment]
Hi @Pritam-sd-dev, I have not yet started to work on this. Feel free to work on it, please keep me updated 🙏

**Comment by Pritam-sd-dev** [comment]
hi, i have started working on it, also i keep updating you as i proceed. :bell:

**Comment by Pritam-sd-dev** [comment]
@CarinaWolli 
if you don't mind, could we connect? I need to explain the bug, its cause, and the solution. I understand this may not be the best way to ask, but it's just to save time. It won't take too much of your time."

**Comment by Pritam-sd-dev** [comment]
If you can't connect, let know I will manage to record a detailed video and will share then.

**Comment by Pritam-sd-dev** [comment]
@keithwillcode 
@CarinaWolli 
https://www.loom.com/share/63412c140f33466ba2478e4cce0b3e7c?sid=5e7170d2-6093-4b05-b1b9-d871fa67ac78

**Comment by Pritam-sd-dev** [comment]
here i think we need to change db design like every booking will have a desination calender which should not change on changing default calendar for that booking's event.

**Comment by Pritam-sd-dev** [comment]
i think we need to change logic like
each booking have a destination calendar that should be not change on changing event's default calendar

**Comment by CarinaWolli** [comment]
If I understand it correctly, the issue you found is not related to recurring bookings, right? This looks like a different bug (that we also need to fix)

To this issue: 
I tested it and for me, an event got removed from google calendar but the wrong one, not the date I canceled

**Comment by Tom-H-L** [comment]
I am facing this with  regular events (not recurring), too. If I cancel an event on [https://app.cal.com/bookings/upcoming](https://app.cal.com/bookings/upcoming) or right after creating it right in the booking confirmation screen, an error occurs: "An error with status code 500 occurred. Please try again." see screen shot:
![Your booking has been confirmed Cal com](https://github.com/calcom/cal.com/assets/76924808/f6e557bd-801f-4ff8-abad-84410628dfd8)

**Comment by Pritam-sd-dev** [comment]
> If I understand it correctly, the issue you found is not related to recurring bookings, right? This looks like a different bug (that we also need to fix)
> 
> To this issue: I tested it and for me, an event got removed from google calendar but the wrong one, not the date I canceled

the issue that i found is common like it is happening in recurring and others also.

**Comment by CarinaWolli** [comment]
@Pritam-sd-dev  I created a new issue for that, as this is not directly related to this issue: https://github.com/calcom/cal.com/issues/13902
