### ISSUE TITLE
[CAL-3202] Meeting invites are being duplicated in calendars with MS Teams

### ISSUE THREAD

**Issue by alandaviesdyonix** [calcom/cal.com#13823]
### Issue Summary

Meetings get duplicated in users and clients calenders. With the intergration into Teams the meeting invites also get duplicated here too, with different meeting links each time. 
When deleting the appointment, [Cal.com](http://Cal.com) removes only one of the duplicated meetings.

We are using [Cal.com](http://Cal.com) with the intergration into Office 365 and Teams.

### Steps to Reproduce

1. Book a  meeting through the users page
2. User has to accept the booking request

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* Meeting gets duplicated

### Expected Results

* Meeting should not be duplicated

### Technical details

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cd7127d2-d842-4692-be03-c6d62b54cde8/ce38d67f-030f-44a6-8beb-2f6b269af057?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jZDcxMjdkMi1kODQyLTQ2OTItYmUwMy1jNmQ2MmI1NGNkZTgvY2UzOGQ2N2YtMDMwZi00NGE2LThiZWItMmY2YjI2OWFmMDU3IiwiaWF0IjoxNzEzMTg0MDIwLCJleHAiOjE3MTMyNzA0MjB9.B2gcLbDBx5tHg8rGLKdOn3I6cgYgX6hYHWwFJV096ic)

* NodeJS v18.19.0
* Using the latest official Docker image

### Evidence

Please see screenshot

<sub>[CAL-3202](https://linear.app/calcom/issue/CAL-3202/meeting-invites-are-being-duplicated-in-calendars-with-ms-teams)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3421](https://linear.app/calcom/issue/CAL-3421/[cal-3202]-meeting-invites-are-being-duplicated-in-calendars-with-ms)</sub>

**Comment by Pritam-sd-dev** [comment]
working on it, will resolve asap.
