### ISSUE TITLE
 [CAL-3225] Re-schedule doesn't fire `bookingSuccessful` event

### ISSUE THREAD

**Issue by bedus-creation** [calcom/cal.com#13835]
I am using Event Listener to listen booking events on my vue project (embedding). The `bookingSuccessful` event is used to fire on creating a new booking, re-scheduling, and canceling the event. But from today, this event isn't being fired on re-schedule or canceled.

After looking into a PR, https://github.com/calcom/cal.com/pull/13755/files#diff-35d749cb6fd62f8883025b6b0e7c74b1f0f3c03fefb9dba67ae47be887fe65ce

I found changes regarding to event, seems like separate events will fire on re-schedule and cancel cases. 

I am not sure how to track these changes, I am using it with embedding, behind the scenes, the API changes, and feature breaks.  
I couldn't find documentation of these new events. Am I missing something? Or what would be the suggested way to listen to these events?

<sub>[CAL-3225](https://linear.app/calcom/issue/CAL-3225/re-schedule-doesnt-fire-bookingsuccessful-event)</sub>

<sub>[CAL-3423](https://linear.app/calcom/issue/CAL-3423/[cal-3225]-re-schedule-doesnt-fire-bookingsuccessful-event)</sub>

**Comment by hariombalhara** [comment]
This was a mistake where we accidentally changed existing behaviour.

Only documentation is missing here now.
