### ISSUE TITLE
[CAL-3223] Currency Not Reflecting Correctly

### ISSUE THREAD

**Issue by dninomiya** [calcom/cal.com#13845]
A severe bug has occurred where amounts set in Japanese Yen are being settled in dollars during actual transactions. As a result, customers have been charged 100 times the intended amount. The UI consistently displays the amount in Japanese Yen right up to the final stage, so customers only realize the massive overcharge when it is already too late.

For the time being, I have paused the settlement calendar, hoping that this issue will be resolved.

## Stripe Settings

![スクリーンショット 2024-02-24 10 26 57](https://github.com/calcom/cal.com/assets/5842851/d6067389-268a-4961-b2c4-183cf2af81db)

## Payment UI

At this point, the amount is still correct in Japanese Yen.

![スクリーンショット 2024-02-24 10 25 03](https://github.com/calcom/cal.com/assets/5842851/0244a4a9-1fd7-4781-8e34-f8f9c8dc39ef)

## Stripe Dashboard

In reality, an amount 100 times greater is being charged by Stripe.🥶

![スクリーンショット 2024-02-24 10 20 33](https://github.com/calcom/cal.com/assets/5842851/b47ceca9-c5ec-47a6-9472-3176ab454c0e)

---

Thank you for your support!

<sub>[CAL-3223](https://linear.app/calcom/issue/CAL-3223/currency-not-reflecting-correctly)</sub>

**Comment by Pritam-sd-dev** [comment]
@dninomiya 
Thank you for bringing the "Currency Not Reflecting Correctly" issue to our attention on GitHub. Your contribution is invaluable in ensuring the accuracy and quality of our project, and rest assured, it will be fixed soon.

**Comment by Pritam-sd-dev** [comment]
i have started working on it. will be fixed soon.

**Comment by dninomiya** [comment]
@Pritam-sd-dev 
Thanks!
