### ISSUE TITLE
[CAL-3206] [CAL-3205] do not show hidden booking questions to guests

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#13841]
lets not show hidden fields in confirmation screens, emails and calendar entries for guests

![image](https://github.com/calcom/cal.com/assets/8019099/68ee388f-641b-4220-b9bd-ae67d56abd98)

![image](https://github.com/calcom/cal.com/assets/8019099/0c1a192c-415b-4041-ba1c-77af5dd801cf)

<sub>[CAL-3205](https://linear.app/calcom/issue/CAL-3205/do-not-show-hidden-booking-questions-to-guests)</sub>

<sub>[CAL-3206](https://linear.app/calcom/issue/CAL-3206/[cal-3205]-do-not-show-hidden-booking-questions-to-guests)</sub>

**Comment by Udit-takkar** [comment]
@PeerRich should i hide hidden fields responses for both organizer and attendees email? or only hide from attendees?
