### ISSUE TITLE
[ERROR ]Refused to execute inline script because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by iborisbelov** [calcom/cal.com#13844]
Hi guys.
I have these errors:

[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-LeYI+W5S6XECpdjnp7IWAg==' 'strict-dynamic' 'self' 'unsafe-inline' https:". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

[Report Only] Refused to load the image 'https://cal.com/api/avatar/cc9f080a-90ea-4d86-8c12-e56bc6d4798e.png' because it violates the following Content Security Policy directive: "img-src 'self' https://app.cal.com https://img.youtube.com https://eu.ui-avatars.com/api/ data:".

![image](https://github.com/calcom/cal.com/assets/45220581/2758c26f-fbac-4357-ab53-001b4ebc97f1)

---

I realize that they have no effect on the functionality of the website and widget, and everything works. 

BUT! This is very bad for website optimization, and Google PageSpeed Insights reminds about these errors as well. How to solve them?

Since I see and know that these errors are also present in your direct link.

**Is there anything I can do to prevent these errors?**

**Comment by iborisbelov** [comment]
@PeerRich @hariombalhara Hi guys! Do you have any progress here?

**Comment by Juanmalopezg** [comment]
Same issue here using the embedded calendar


![image](https://github.com/calcom/cal.com/assets/31255822/500faaf0-32b8-434c-98bc-18e0c6fbefbf)

**Comment by hariombalhara** [comment]
Working on it at the moment

**Comment by iborisbelov** [comment]
![image](https://github.com/calcom/cal.com/assets/45220581/da036d0b-2e83-4cf9-8d3a-e3de0fd78d6f)

Hi @hariombalhara .

**Comment by hariombalhara** [comment]
It is not yet tagged and released. A release is expected to happen today sometime.

**Comment by iborisbelov** [comment]
@hariombalhara  Thank you. I'm in wild expectation.
