### ISSUE TITLE
ICS Feed app broken? Connect to an ICS Feed -> No handlers found for ics-feed

### ISSUE THREAD

**Issue by EduNetEurope** [calcom/cal.com#13856]
We cannot add an ICS feed. The ICS app seems broken.
![image](https://github.com/calcom/cal.com/assets/148647197/2fff5284-bcbe-4f46-92e4-122b97e6d671)
![image](https://github.com/calcom/cal.com/assets/148647197/73909e55-b8e0-44e9-9be4-0834c5828857)

### Steps to Reproduce
1. Go to Apps / App Store
2. Try installing ICS Feed
3. Try connecting to an ICS Feed by inserting an address in iCal format (.ics)
-> Error message: No handlers found for ics-feed

**Comment by Rubenkl** [comment]
Same problem!

**Comment by shifakhan** [comment]
Bumping this up. Just signed up for cal.com, thank you all for building this and supporting ICS feeds! 
Sharing the sample public calendar ics link I tried to add from proton calendar - [Link](https://calendar.proton.me/api/calendar/v1/url/CHaM7UMCpNPQrJBgeTMFktPk_CNxSyB3f89PUNDcVAJWNH9PU1e-gpAX032t_sz3C__8ugFk2CTHhsh7y9YqLg==/calendar.ics?CacheKey=tI5tNtaAwxe42S79vz2rBw%3D%3D&PassphraseKey=RF6x16yoUm1gXDz8Xsro4CgzojC4pmc95FOmSsavmxM%3D)
Will be a very happy user and promote it in the [protonmail community](https://www.reddit.com/r/ProtonMail) if this works out. Cheers!

**Comment by davidwinter** [comment]
Same issue with a shared calendar from Fastmail. Would love to use cal.com

**Comment by doebi** [comment]
Supporting this, having the same problem.

**Comment by tom-sherman** [comment]
When will this be released to app.cal.com?
