### ISSUE TITLE
[CAL-3424] [CAL-3227] Large padding on small screens for embedded booking widgets.

### ISSUE THREAD

**Issue by albertborsos** [calcom/cal.com#13854]
### Issue Summary

I embed my booking widget (`inline` )with my main URL, and not with the URL of the service. After I select a service, then it adds a large padding to the top of the widget, but just on small screens. 

### Steps to Reproduce

1. Get the "Inline Embed" HTML snippet, and paste it to your site.
2. remove the /service-to-remove from `calLink: "username/service-to-remove",`
3. Now the service selector appears on your site.
4. choose a service
5. On large screens it is OK, on small screens it has a large "padding" on the top

This is because the `main` element inside the iframe has a `min-h-[100dvh]` tailwind class. If I replace it with `min-h-[calc(100dvh)]`, then it look good on small screens too.

### Actual Results

- On mobiles and small screens it gets a large padding over the widget.

### Expected Results

- The widget does not get a large top padding on small screen devices.

### Technical details

- I use the cal.com hosted widget.
- Browser version: latest chrome and safari

### Evidence:

screen recording:

https://github.com/calcom/cal.com/assets/7307145/17f1c27e-65f7-4aa4-87ae-b3db885aa503

<sub>[CAL-3227](https://linear.app/calcom/issue/CAL-3227/large-padding-on-small-screens-for-embedded-booking-widgets)</sub>

<sub>[CAL-3424](https://linear.app/calcom/issue/CAL-3424/[cal-3227]-large-padding-on-small-screens-for-embedded-booking-widgets)</sub>

**Comment by niks-nikhil-anand** [comment]
I am started working on this issue

**Comment by suyash5053** [comment]
> I am started working on this issue

@niks-nikhil-anand The PR for this is already merged and is completed,

**Comment by niks-nikhil-anand** [comment]
yeah , saw that ?
that was mistaken

**Comment by albertborsos** [comment]
Thanks! I close it since the PR is already merged.

**Comment by albertborsos** [comment]
I had to reopen this, because this fix did not solved the issue. The attached screen recording is still valid.

**Comment by kapilG0** [comment]
Hello @albertborsos can I work on this issue ?

**Comment by kapilG0** [comment]
@albertborsos please assign this issue to me i am ready to work on that

**Comment by CarinaWolli** [comment]
> @albertborsos please assign this issue to me i am ready to work on that

Feel free to work on it, no need to be assigned. Just make sure to link this issue to your PR, thank you 🙏

**Comment by kapilG0** [comment]
Hello @CarinaWolli i am facing issue in running project i followed the guidelnes which is mentioned . can you help me out little bit in that ? 
![image](https://github.com/calcom/cal.com/assets/59639410/ba58682e-2eee-44f9-b737-5fd93e64ae71)

**Comment by albertborsos** [comment]
It is still not OK. Please select a service, then the large padding appears. On first pageload it is OK, the problem occures after you chose a service from, the list.

**Comment by rushikeshrtledgers** [comment]
@albertborsos In next release of cal, will get reflect the changes made.
