### ISSUE TITLE
ICS Feed app not in the app store

### ISSUE THREAD

**Issue by mschneiderwng** [calcom/cal.com#13860]
The ics feed app implemented in https://github.com/calcom/cal.com/pull/13337 is not available in the app store at https://app.cal.com/apps

**Comment by suyash5053** [comment]
Hey @mschneiderwng , The Ics feed app will be released in the future version, may in v3.9

**Comment by PeerRich** [comment]
check again! https://app.cal.com/apps/ics-feed
