### ISSUE TITLE
[CAL-3216] Broken reschedule link in email created by workflow for team event

### ISSUE THREAD

**Issue by fabiansteuer** [calcom/cal.com#13869]
### Issue Summary

The reschedule link in email created by the workflow for a team event doesn't work because its slug doesn't contain `/team`.

### Steps to Reproduce

1. Create an event type _for a team_.
2. Assign a workflow to the event type that sends an email containing the `{RESCHEDULE_URL}` variable.
3. Book the team event (`cal.com/team/team-name/event-name`).
5. Receive an email containing a reschedule link for the event via the workflow.
6. Click on the reschedule link in the email.

### Actual Results

The reschedule link in the email looks like `app.cal.com/team-name/event-name?rescheduleUid=...`. Clicking on it results in a 404 page because `/team` is missing in the slug.

### Expected Results

The reschedule link in the email should look like `app.cal.com/team/team-name/event-name?rescheduleUid=...` and open the reschedule page of the event.

<sub>[CAL-3216](https://linear.app/calcom/issue/CAL-3216/broken-reschedule-link-in-email-created-by-workflow-for-team-event)</sub>

**Comment by Pritam-sd-dev** [comment]
Hi there! Thanks for raising the issue on GitHub. we'll have it fixed ASAP. Appreciate your patience!

**Comment by Pritam-sd-dev** [comment]
cal team, i have started working on it.

**Comment by keithwillcode** [comment]
Thank you, @Pritam-sd-dev. We’ll review the PR when submitted!
