### ISSUE TITLE
[CAL-3215] Faux bold in cal-font forces browser to fake bold text

### ISSUE THREAD

**Issue by dev-cb** [calcom/cal.com#13879]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Noticed that there is only the SemiBold font file loaded with no further weight declaration in the @font-face which makes the browser interpret the font-weight is normal/400. This will then cause the browser to faux bold elements where `.font-cal.font-bold` or `.font-cal.font-samibold` classes are applied.

### Steps to Reproduce

Example 1: `h3.font-cal.font-semibold` heading on /event-types
<img width="1119" alt="Bildschirmfoto 2024-02-27 um 09 39 38" src="https://github.com/calcom/cal.com/assets/13319306/0f1c4729-d06c-4943-b1d5-d3e77796635a">

Example 2: `h1.font-cal.font-bold` heading on /settings/my-account/profile
<img width="1031" alt="Bildschirmfoto 2024-02-27 um 09 42 18" src="https://github.com/calcom/cal.com/assets/13319306/4cea8c30-9bdb-4860-aeee-c2ea2491d7db">

### Expected Results / Fix

Following the design system the Cal-Font is only available in SemiBold (font-weight: 600).
Therefore the way to a fix is the following:
1. Use @next/font weight function argument in `/apps/web/app/layout.tsx` and `/apps/web/components/PageWrapper.tsx` to properly define the font-weight of the loaded font file to 600. The weight function argument is required if the loaded font is not a variable font, as documented [here](https://nextjs.org/docs/app/api-reference/components/font#weight).
2. find all heading elements which have `.font-cal` and `.font-bold` applied and replace `.font-bold` with `.font-semibold`.

<sub>[CAL-3215](https://linear.app/calcom/issue/CAL-3215/faux-bold-in-cal-font-forces-browser-to-fake-bold-text)</sub>

**Comment by MysteryHawk17** [comment]
@keithwillcode 
fixed this issue 
Raising  PR

**Comment by dev-cb** [comment]
That's was a quick one.

**Comment by MysteryHawk17** [comment]
Had the code set up. Saw the issue and solved it 🙂
