### ISSUE TITLE
[CAL-3326] [CAL-3220] Not able to create an event 

### ISSUE THREAD

**Issue by alidotdeveloper** [calcom/cal.com#13873]
### Issue Summary

After logging with google account. My account is created but when I click on the create button It moves to the getting start page. when I click on next step button it didn't able to move to next step. on checking console I see we are getting error: 
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### Steps to Reproduce

1. go to https://app.cal.com/
2. sign in through google account
3. after login, click on the create event type button
4.  you will redirect to getting started page 
5. then fill details and click on next step

### Actual Results

Not able to move to next step 

### Expected Results

it should move to the second step as it's 5 step form

### Evidence

[screen-capture (1).webm](https://github.com/calcom/cal.com/assets/74443787/c893685d-3bae-4250-b6d2-a5473612f092)

<sub>[CAL-3220](https://linear.app/calcom/issue/CAL-3220/not-able-to-create-an-event)</sub>

<sub>[CAL-3326](https://linear.app/calcom/issue/CAL-3326/[cal-3220]-not-able-to-create-an-event)</sub>

**Comment by zomars** [comment]
@alidotdeveloper we can't seem to replicate the behavior. Can you confirm this is still happening after v4.0 launch?

Will close the issue for now but feel free to re-open if the issue persists. 🙏🏽
