### ISSUE TITLE
[CAL-3219] [CAL-3218] {RESCHEDULE_URL} is returning "undefined" in the url and not working

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13885]
**Steps to recreate**

* Create a workflow with a custom message 
* Add a {RESCHEDULE_URL}
* View the email that is sent: It returns a link that does not worl

![CleanShot 2024-02-27 at 11.11.42@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ab8fd3cf-7db0-4f24-9098-108841d2ea89/2a3993f9-0a74-49c0-a353-a90edfc8be57?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hYjhmZDNjZi03ZGIwLTRmMjQtOTA5OC0xMDg4NDFkMmVhODkvMmEzOTkzZjktMGE3NC00OWMwLWEzNTMtYTkwZWRmYzhiZTU3IiwiaWF0IjoxNzA5MDMyMzc3LCJleHAiOjE3MDkxMTg3Nzd9.JBmdPFN_9PD5UAqt0mAYdh21rbaIPwXJ8L6cZGrWAhU)

![CleanShot 2024-02-27 at 11 34 39@2x](https://github.com/calcom/cal.com/assets/4536123/1cdbab35-132a-49b9-8861-0cb84c75793f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3218](https://linear.app/calcom/issue/CAL-3218/reschedule-url-is-returning-undefined-in-the-url-and-not-working)</sub>

<sub>[CAL-3219](https://linear.app/calcom/issue/CAL-3219/[cal-3218]-reschedule-url-is-returning-undefined-in-the-url-and-not)</sub>

**Comment by Pritam-sd-dev** [comment]
@keithwillcode 
i have started working on it.

**Comment by bparlan** [comment]
I am getting similar issues, 'undefined' in URL for both Reschedule and Cancel functions in Both emails where Host gets and User gets. Event is a Seated event, and new booking workflow is only assigned to single event. Any suggestions to solve this?
