### ISSUE TITLE
[CAL-3431] Error Message on registering/installing CalDAV calendar from All-inkl.com

### ISSUE THREAD

**Issue by snack753** [calcom/cal.com#13898]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am using a CalDAV calendar hosted by [https://all-inkl.com](https://all-inkl.com)
When I try to install/register this calendar to my [Cal.com](http://Cal.com) account I get the following error message:
"Cannot restructure property 'auth' of 'r' as it is undefined."

### Steps to Reproduce

1. Set up my calendar on [https://all-inkl.com](https://all-inkl.com)
2. got my sharing details from the calendar page
3. used the calendar details in different apps (e.g. Apple calendar, iOS calendar, Thunderbird, etc.) - confirmed this works
4. navigate to [https://app.cal.com/apps/categories/calendar](https://app.cal.com/apps/categories/calendar)
5. tried to add the CalDAV app on [Cal.com](http://Cal.com)
6. click on CalDav beta
7. click install
8. enter the credentials that work for other calendar apps (see obove)

### Actual Results

In Brave browser:
Get error message: Cannot restructure property 'auth' of 'r' as it is undefined

In Safari browser:
Get error message: Right side of assignment cannot be restructured

In Firefox:
'r' is undefined

### Expected Results

See success message and get my calendar details synced to [Cal.com](http://Cal.com)

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3840a49c-3154-422c-8646-6e703c5dcc4c/056cbd78-0c3a-467a-8ac3-bb247edd08af?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zODQwYTQ5Yy0zMTU0LTQyMmMtODY0Ni02ZTcwM2M1ZGNjNGMvMDU2Y2JkNzgtMGMzYS00NjdhLThhYzMtYmIyNDdlZGQwOGFmIiwiaWF0IjoxNzEzMTg0MDMxLCJleHAiOjE3MTMyNzA0MzF9.879OBe6sw6ujozS4kVkZOLwBnyFIzgFgmvLjHRcwPio)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2a5a13bd-6977-44ba-8dd9-4566b27ac96f/cb37331d-517a-45b4-ac35-de5302d121b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yYTVhMTNiZC02OTc3LTQ0YmEtOGRkOS00NTY2YjI3YWM5NmYvY2IzNzMzMWQtNTE3YS00NWI0LWFjMzUtZGU1MzAyZDEyMWI3IiwiaWF0IjoxNzEzMTg0MDMxLCJleHAiOjE3MTMyNzA0MzF9.ph5tnFPwfov1jkdZBb3tmM4VrUrzPxIARointeQQpXE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3431](https://linear.app/calcom/issue/CAL-3431/error-message-on-registeringinstalling-caldav-calendar-from-all)</sub>

**Comment by alishaz-polymath** [comment]
cc: @joeauyeung who is leading CalDAV. 
Can you please take a look here?

**Comment by tessaSAC** [comment]
Adding that I see the same 'auth' of `r` destructure error message in Chrome with a different calendar service provider.
