### ISSUE TITLE
[CAL-3432] [CAL-3229] [CAL-3228] Managed event types of a deleted team stay assigned to individual users and cannot be deleted

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13894]
Steps to recreate

* Create a team
* Create managed event types and assign them to users
* Delete the team
* The users still have managed event types from the team assigned to them and they cannot delete them

Solution

* Delete managed event types when we delete a team
* or make them not managed so that the individual has control (preferred)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3228](https://linear.app/calcom/issue/CAL-3228/managed-event-types-of-a-deleted-team-stayed-assigned-to-users)</sub>

<sub>[CAL-3229](https://linear.app/calcom/issue/CAL-3229/[cal-3228]-managed-event-types-of-a-deleted-team-stayed-assigned-to)</sub>

<sub>[CAL-3432](https://linear.app/calcom/issue/CAL-3432/[cal-3229]-[cal-3228]-managed-event-types-of-a-deleted-team-stay)</sub>

**Comment by Pritam-sd-dev** [comment]
hi cal team
i will pick this up and will resolve asap.

**Comment by Amit91848** [comment]
Has this been resolved? I tried the steps, but after deleting the team, the managed event was deleted for everyone it was assigned to.

**Comment by zeeshanbhati** [comment]
@Amit91848  Yes I think it's resolved

**Comment by Udit-takkar** [comment]
> Has this been resolved? I tried the steps, but after deleting the team, the managed event was deleted for everyone it was assigned to.

cc: @ciaranha

**Comment by ciaranha** [comment]
> > Has this been resolved? I tried the steps, but after deleting the team, the managed event was deleted for everyone it was assigned to.
> 
> cc: @ciaranha

Not sure, I haven't tested. Please test and confirm..
