### ISSUE TITLE
[CAL-3232] [CAL-3231] Limiting availability 30 days into the future blocks all availabilty

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13895]
[CleanShot 2024-02-27 at 13.56.58.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/075a502f-1eee-4748-9299-55ff64e3f967/1d2e0727-3871-48fb-a371-98ada0d69174)

Steps to recreate

* Go to "Limits" on an event type
* Limit availability to the next 30 days
* All availability for the next month is blocked out

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3231](https://linear.app/calcom/issue/CAL-3231/limiting-availability-30-days-into-the-future-blocks-all-availabilty)</sub>

<sub>[CAL-3232](https://linear.app/calcom/issue/CAL-3232/[cal-3231]-limiting-availability-30-days-into-the-future-blocks-all)</sub>

**Comment by ciaranha** [comment]
> @ciaranha i think this issue is addressed by this merged PR #13851

Oh that's great!

**Comment by keithwillcode** [comment]
Yeah I confirmed this is fixed on prod
