### ISSUE TITLE
[CAL-3226] [CAL-3224] Embed in email not pulling any availability

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13891]
Right now if you try to embed any event type in an email, it will show zero availability.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3224](https://linear.app/calcom/issue/CAL-3224/embed-in-email-not-pulling-any-availability)</sub>

<sub>[CAL-3226](https://linear.app/calcom/issue/CAL-3226/[cal-3224]-embed-in-email-not-pulling-any-availability)</sub>

**Comment by Udit-takkar** [comment]
After some debugging This issue is only for org event types

https://app.cal.com/api/trpc/public/slots.getSchedule?input=....  => 404 
https://{orgDomain}.cal.com/api/trpc/public/slots.getSchedule?input=...  => 200

When you select email embed app.cal.com domain is used instead of  orgDomain
