### ISSUE TITLE
[CAL-3425] desination calendar of old bookings changes when default calendar of event is updated

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#13902]
When the default calendar of an event is changed the destination calendar of all previous bookings changes as well. So when canceling the event, the calendar event is not deleted

Discussed here: https://github.com/calcom/cal.com/issues/13827
> each booking have a destination calendar that should be not change on changing event's default calendar.
[Loom](https://www.loom.com/share/63412c140f33466ba2478e4cce0b3e7c?sid=5e7170d2-6093-4b05-b1b9-d871fa67ac78)

<sub>[CAL-3425](https://linear.app/calcom/issue/CAL-3425/desination-calendar-of-old-bookings-changes-when-default-calendar-of)</sub>

**Comment by Pritam-sd-dev** [comment]
hi, i have started working on it.

**Comment by Shaik-Sirajuddin** [comment]
The issue is specific to Google Calendar Integration , where the logic verifies default calendar of event to match the bookings associated calendar.

This fails the operation of calendar updating when a booking is cancelled

**Comment by Shaik-Sirajuddin** [comment]
Found that , Each event is associated with a destination calendar , when the default calendar of an event is updated , the destination calendar entry for the particular event is updated.
Destination Calendar seems directly not associated with Booking , a externalD field is available in booking reference which remains unchanged by the modification of events default calendar.

This is used while deleting an calendars event , except in case of google calendar where an additional logic is in place.
