### ISSUE TITLE
[CAL-3238] Add API endpoint that lists connected calendars for a user

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#13905]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3238](https://linear.app/calcom/issue/CAL-3238/add-api-endpoint-that-lists-connected-calendars-for-a-user)</sub>

**Comment by keithwillcode** [comment]
This is coming in v2 I believe cc @ThyMinimalDev @exception @supalarry @Ryukemeister

**Comment by Ryukemeister** [comment]
PR for connected calendars for a user https://github.com/calcom/cal.com/pull/13559

**Comment by supalarry** [comment]
v2 api: the thing is that the connected calendars endpoint is behind an access token, but v1 uses api token. So either:
1. Integrate v1 api token logic in v2 api - longer path but we would switch to v2 at some point anyway. However, user the would need to use v1 endpoints + v2 endpoints which would be messy IMO - either one uses v1 or v2.
2. Once platform is merged in main (should be next week), just re-use [this lib helper](https://github.com/calcom/cal.com/pull/13559/files#diff-40234d044a7b817c8a743908131b8ad9ec2800e325a1df68564a8c8b14f93ee8) and add a new v1 endpoint - this would be the quickest way.

**Comment by keithwillcode** [comment]
> v2 api: the thing is that the connected calendars endpoint is behind an access token, but v1 uses api token. So either:
> 
> 1. Integrate v1 api token logic in v2 api - longer path but we would switch to v2 at some point anyway. However, user the would need to use v1 endpoints + v2 endpoints which would be messy IMO - either one uses v1 or v2.
> 2. Once platform is merged in main (should be next week), just re-use [this lib helper](https://github.com/calcom/cal.com/pull/13559/files#diff-40234d044a7b817c8a743908131b8ad9ec2800e325a1df68564a8c8b14f93ee8) and add a new v1 endpoint - this would be the quickest way. Or just copy paste the helper to main and create v1 endpoint.

Yeah, let's just add the easiest support for this endpoint in v1 and then look at add token support to v2

**Comment by joeauyeung** [comment]
Awesome, keep in the loop about this one. A customer is expecting this for 3.9.

**Comment by joeauyeung** [comment]
Unassigning myself as this will be handled in the v2 API
