### ISSUE TITLE
translating only the booking widget

### ISSUE THREAD

**Issue by albertborsos** [calcom/cal.com#13910]
### Is your proposal related to a problem?

Hi!

I started to translate to my language (which is hungarian), but there are around 22k strings to translate. It is an impossible work for me to finish, it needs months in my spare time.

I think the most valueable strings (for me and for my customers) are those which appears in the booking flow. I think the translations for the dashboard and the whole application and landing pages are less important, because I bet 90% of your users/customers understand english so they can easily use the dashboard and the site.

But 90% of my customers (who are using only the booking flow) does not understand english, and for them it is hard to book via this amazing booking flow. 

### Describe the solution you'd like

Would it be possible to separate the strings which are related to the booking flow, and make translations only for those?

It would be much faster to release translations and make this scheduler accessible in more countries.

It means the dashboard will need another language selector for the booking flow.

### Describe alternatives you've considered

I think this is the simplest solution.

### Additional context

Nothing.

### Requirement/Document

Nothing.

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
i dont think this is easily be done, the entire i18n script pipeline is build around one file.

however, i think what you can do is look at the booking page and then search for the string, that should be quiet fast. i18n files can be incomplete, that is fine

**Comment by albertborsos** [comment]
Thanks. I am going to give it a try.
