### ISSUE TITLE
[CAL-3240] Stripe: Don't auto-issue refunds when a user cancels

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13916]
When a user cancels an event, it is automatically refunded. This is not clear and also not ideal. Since there are fees associated with issuing refunds, it should be up to the organizer on when and if it is appropriate to issue a refund. They can do this through Stripe.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3240](https://linear.app/calcom/issue/CAL-3240/stripe-dont-auto-issue-refunds-when-a-user-cancels)</sub>

**Comment by lucamastella** [comment]
We need this as well
