### ISSUE TITLE
[CAL-3433] [CAL-3241] When limit for the day is reached, don't show day as available

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13919]
With booking limits, we're still letting people select days and times and then throwing an error at the last step saying the limit is reached. Can we block out the day entirely once the limit is reached?

![CleanShot 2024-02-28 at 16.40.04@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9088ceff-5fbd-44c9-bde5-c7a929f84e4c/46c40572-922a-4eab-ac54-a6612b51b16b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MDg4Y2VmZi01ZmJkLTQ0YzktYmRlNS1jN2E5MjlmODRlNGMvNDZjNDA1NzItOTIyYS00ZWFiLWFjNTQtYTY2MTJiNTFiMTZiIiwiaWF0IjoxNzA5MTM4NTY4LCJleHAiOjE3MDkyMjQ5Njh9.wYg-RvH9BsAWQIjYnkxZEEXLPDDQJiWapolsXoV2vpQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3241](https://linear.app/calcom/issue/CAL-3241/when-limit-for-the-day-is-reached-dont-show-day-as-available)</sub>

<sub>[CAL-3433](https://linear.app/calcom/issue/CAL-3433/[cal-3241]-when-limit-for-the-day-is-reached-dont-show-day-as)</sub>

**Comment by MysteryHawk17** [comment]
If this  issue is still available i would like to take up this issue. 
Thanks

**Comment by keithwillcode** [comment]
@MysteryHawk17 yes it is! Feel free to open a PR against this and we’ll review. 🙏🏼

**Comment by MysteryHawk17** [comment]
On it. Will raise a PR against this once solved . 
Thanks .

**Comment by MysteryHawk17** [comment]
On it. Will raise a PR against this once solved . 
Thanks .

**Comment by udshar5995** [comment]
![image](https://github.com/calcom/cal.com/assets/23457326/e129cde9-957e-467c-a1f3-82afdf0dfa2c)
![image](https://github.com/calcom/cal.com/assets/23457326/123792ae-5495-463b-b137-c8a9cc8f5557)
![image](https://github.com/calcom/cal.com/assets/23457326/e2336d19-1665-4fc0-a3fa-d607c505c4a0)

@keithwillcode seems like the issue has been resolved, I cannot select the day (4th march) once I have booked a 30 min meeting for that day after setting a limit of  '1 per day'.

**Comment by keithwillcode** [comment]
@ciaranha were there special conditions where you saw this? e.g. overrides

**Comment by MysteryHawk17** [comment]
@keithwillcode 
The problem is @udshar5995 booked after a particular duration 
If you try to book them simultaneously they get booked.
if you take time while hitting the api then it works perfectly.

**Comment by MysteryHawk17** [comment]
The problem is that the db is not staying consistent between two bookings which happen within a short span of time.

**Comment by MysteryHawk17** [comment]
@keithwillcode 
Here are a few images to show that the meeting gets booked for two accounts . 
![image](https://github.com/calcom/cal.com/assets/95360396/008740c0-17e6-44a5-8a58-55d1315255be)
![meeting1](https://github.com/calcom/cal.com/assets/95360396/63e86507-eb49-4b52-b411-c9ebd194127b)
![meeting2](https://github.com/calcom/cal.com/assets/95360396/4f402380-ed2d-4fbc-a41f-444957966fac)

Please let me know if i missed something.

**Comment by zeeshanbhati** [comment]
@MysteryHawk17  I tried to replicate it multiple times, using puppeteer as well , this only happens when someone passes the availability page.

**Comment by MysteryHawk17** [comment]
Yes. The original issue said that we should not  display the availability page if the dates are not available. 
Now the availability updates with each booking and while a booking is in progress i.e before the api call is complete it shows available and that is why we are able to view it. 

Now a way to deal with this according to me is involving transactions and implementing something which resembles a critical section such as it prevents the fetching of availability page while a booking is in progress  which would solve the problem.
