### ISSUE TITLE
[CAL-3434] [CAL-3242] Could not book the meeting "Unexpected token '<, *<!DOCTYPE "… is not valid JSON

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13920]
[Details in threads](https://threads.com/thread/34565999644?s=uq8WDdAnR1BfdUakkQ2dha)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3242](https://linear.app/calcom/issue/CAL-3242/could-not-book-the-meeting-unexpected-token-doctype-is-not-valid-json)</sub>

<sub>[CAL-3434](https://linear.app/calcom/issue/CAL-3434/[cal-3242]-could-not-book-the-meeting-unexpected-token-doctype-is-not)</sub>

**Comment by keithwillcode** [comment]
Looks like this occurs when an Outlook calendar has a permissions issue
