### ISSUE TITLE
[CAL-3245] Booking question "short text" not being passed to the booking confirmation page or email

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13923]
Steps to recreate:

* Create an event type
* Add a "Short text" booking question and mark it required
* Try book yourself. The field will be required as expected and you have to enter it
* But the response will not appear in the booking confirmation or in the email and I can't find that response the user entered anywhere

![CleanShot 2024-02-28 at 18.31.48@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/80fea6d2-032a-4461-b8e1-14fcee28c58d/d150808f-2c31-436d-9746-29b906879b2f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84MGZlYTZkMi0wMzJhLTQ0NjEtYjhlMS0xNGZjZWUyOGM1OGQvZDE1MDgwOGYtMmMzMS00MzZkLTk3NDYtMjliOTA2ODc5YjJmIiwiaWF0IjoxNzA5MTQ1MTIwLCJleHAiOjE3MDkyMzE1MjB9.FbK8Zsc_4fjvMnTqWOMULKpl9vqcOJdjf5g5EOscrkQ)

![CleanShot 2024-02-28 at 18.31.18@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9e6524eb-05c6-4ce1-903b-958a51e1299a/743470f7-10cb-423b-a34c-4e86f4989981?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85ZTY1MjRlYi0wNWM2LTRjZTEtOTAzYi05NThhNTFlMTI5OWEvNzQzNDcwZjctMTBjYi00MjNiLWEzNGMtNGU4NmY0OTg5OTgxIiwiaWF0IjoxNzA5MTQ1MTIwLCJleHAiOjE3MDkyMzE1MjB9.JvbErT1dNWgsZRjld1p0QvDQdjM7ORwhUCJj77CnEWQ)

![CleanShot 2024-02-28 at 18.31.48@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a4edb3f3-ec40-4478-b3ab-f5833371c930/41b71da9-a1cb-4330-8885-4cf8172c4c94?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNGVkYjNmMy1lYzQwLTQ0NzgtYjNhYi1mNTgzMzM3MWM5MzAvNDFiNzFkYTktYTFjYi00MzMwLTg4ODUtNGNmODE3MmM0Yzk0IiwiaWF0IjoxNzA5MTQ1MTIwLCJleHAiOjE3MDkyMzE1MjB9.Vjjmm289c0FwNXj4iSe2rk2PiS3_GZaRfvhkBtU7dNI)

![CleanShot 2024-02-28 at 18.31.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4f6e2f77-77a9-4c52-a5c7-5e90659c8d4f/d8d904bd-81a8-48ac-86d3-91e6670f47a2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80ZjZlMmY3Ny03N2E5LTRjNTItYTVjNy01ZTkwNjU5YzhkNGYvZDhkOTA0YmQtODFhOC00OGFjLTg2ZDMtOTFlNjY3MGY0N2EyIiwiaWF0IjoxNzA5MTQ1MTIwLCJleHAiOjE3MDkyMzE1MjB9.XxDSPolz07tSd55zJMflWD6QCoIgWIWDV_3TRWajg44)

[CleanShot 2024-02-28 at 18.29.41.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a3201269-7417-4af6-bfad-f8cffe53ee29/1ed9689c-aaf1-45ce-958d-b676130d926e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMzIwMTI2OS03NDE3LTRhZjYtYmZhZC1mOGNmZmU1M2VlMjkvMWVkOTY4OWMtYWFmMS00NWNlLTk1OGQtYjY3NjEzMGQ5MjZlIiwiaWF0IjoxNzA5MTQ1MTIwLCJleHAiOjE3MDkyMzE1MjB9._8g91QDTNrIYNRxxOwbjRAGkmkpPpZqSmc9q1UH-TeM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3245](https://linear.app/calcom/issue/CAL-3245/booking-question-short-text-not-being-passed-to-the-booking)</sub>

**Comment by zeeshanbhati** [comment]
Its already coming in the api we just need to show it in the UI 

Field name is `bookingInfo.responses`

**Comment by MehulZR** [comment]
@ciaranha It is not related to the Question field being `shortText`. It is happening because of the identifier being `title`.
Same as `location`, `name`, `guests`, etc field has specific location in the UI. But currently we are not displaying the `title` field for non-dynamic event.

Do we want the it like this:
![image](https://github.com/calcom/cal.com/assets/86384652/a06e3f74-af0f-49d7-b269-a5231c129e80)

Or this:
![image](https://github.com/calcom/cal.com/assets/86384652/e15d5e00-dce7-43b2-ba83-fb03f615e7af)

**Comment by ciaranha** [comment]
@MehulZR I'm afraid I don't really understand your explanation of the issue/resolution. I just know that short text does not arrive in email confirmation or booking confirmation page and it should show up. @Udit-takkar maybe you can respond to the question better? I think the desired outcome is clear.

**Comment by ciaranha** [comment]
> Its already coming in the api we just need to show it in the UI
> 
> Field name is `bookingInfo.responses`

Yes pleaes
