### ISSUE TITLE
Banner text not showing correctly in light mode

### ISSUE THREAD

**Issue by hichemfantar** [calcom/cal.com#13928]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Banner text not showing correctly in light mode. looks good in dark mode.

### Steps to Reproduce

1. Go to settings > appearance
2. turn on light mode
3. go to a page with a banner (teams, insights, routing forms)
4. text is dark on a dark background

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- text is dark on a dark background

### Expected Results

- text is light on a dark background

### Technical details

- Chrome 122
- MacOS Sonoma

### Evidence

![image](https://github.com/calcom/cal.com/assets/34947993/18662c6b-6294-4689-83e8-5672e88679a6)
![image](https://github.com/calcom/cal.com/assets/34947993/016fab52-d6dc-4de6-868f-73c61b1b7c5d)
![image](https://github.com/calcom/cal.com/assets/34947993/bf879d6d-00eb-4c74-bae1-92ca32bab15e)

**Comment by vikas-verma** [comment]
attempt #13928

**Comment by niks-nikhil-anand** [comment]
Started working on this bug .
assign me

**Comment by niks-nikhil-anand** [comment]
Almost i have done it..
😍😍

**Comment by muskan2622** [comment]
![Screenshot from 2024-03-03 19-42-11](https://github.com/calcom/cal.com/assets/84541807/dbb4cc27-b635-4780-bde1-43c52038995b)
![Screenshot from 2024-03-03 19-42-02](https://github.com/calcom/cal.com/assets/84541807/6a7a39d8-d567-4a0a-874b-64d62ad4b871)

**Comment by muskan2622** [comment]
It is working fine with me in both the local host as well as the production.

**Comment by niks-nikhil-anand** [comment]
Hey Can we talk on twitter.
I have talk regarding my queries 

https://x.com/niks_developer?t=Cc5BP8nvODRuxwVitLVTlQ&s=09
