### ISSUE TITLE
[CAL-3244] Could not book the meeting "Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13922]
Details in [threads](https://threads.com/thread/34565738923?s=34S5Wx9KDPRxtJvSnrGHz9).

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3244](https://linear.app/calcom/issue/CAL-3244/could-not-book-the-meeting-cannot-read-properties-of-undefined-reading)</sub>

**Comment by keithwillcode** [comment]
Fixed by https://github.com/calcom/cal.com/pull/13888
