### ISSUE TITLE
Pre-lock "requires confirmation" booking requests so others can't request the same slot.

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13936]
**Is your proposal related to a problem?**
Whenever the "Requires confirmation" option is enabled on Cal.com, multiple users can book the same slot before the initial reservation is manually confirmed. This may lead to potential conflicts and confusion.

**Describe the solution you'd like**
Implement an optional pre-locking mechanism for slots that are awaiting confirmation. This would prevent multiple bookings for the same slot until the initial reservation is either confirmed or declined, ensuring a smoother and more organized booking process.

**Describe alternatives you've considered**
One alternative could be a temporary hold on the slot, allowing the first user to initiate the booking process, and during this period, other users are prevented from booking the same slot. However, a pre-lock mechanism seems more straightforward and effective.

**Additional context**
This feature enhancement aims to streamline the reservation confirmation process, providing a more user-friendly experience and reducing potential booking conflicts. No related issues have been identified at this time.

**Requirement/Document**
No specific document is available at the moment. The proposed feature aligns with the goal of improving user experience on Cal.com by addressing potential booking issues.

**Comment by keithwillcode** [comment]
@ciaranha would you imagine this to be configurable or just the way all event types work?

**Comment by ciaranha** [comment]
> @ciaranha would you imagine this to be configurable or just the way all event types work? 

Probably just how all should work. (I pasted this into GitHub from a user request)
