### ISSUE TITLE
Ability to add a company logo to the booking page

### ISSUE THREAD

**Issue by EduNetEurope** [calcom/cal.com#13942]
We would like to be able to add our company logo to the booking page.
We would also like to [add images to each event type](https://github.com/calcom/cal.com/issues/13941).

**Comment by Vikaskumardane** [comment]
hello , Can you provide little more details about the issue and also company logo information.

**Comment by EduNetEurope** [comment]
Hi, we started using cal.com in the self-hosted version on Cloudron. The booking page is very simple. We would like to have a large organisation logo on top, images for different event types, maybe the ability to select colours and font types, etc. to make it look a bit more elaborate.

**Comment by Udit-takkar** [comment]
<img width="1512" alt="Screenshot 2024-03-01 at 5 28 21 PM" src="https://github.com/calcom/cal.com/assets/53316345/08d9e309-b03f-4bd5-97db-cce2cc10a9c0">

@EduNetEurope you can upload team's logo in settings

**Comment by EduNetEurope** [comment]
> @EduNetEurope you can upload team's logo in settings

@Udit-takkar Thanks! Seems like a good workaround. Ideally, we would have different team logos (for projects) in addition to a company logo.
