### ISSUE TITLE
Disable default reschedule and cancel emails for host and for attendees

### ISSUE THREAD

**Issue by albertborsos** [calcom/cal.com#13947]
### Is your proposal related to a problem?

If I added a workflow for reschedule and/or cancellation events, then the host and the attendees receive 2-2 emails.

One is the default email, and the other is my custom email.

### Describe the solution you'd like

Like under the Event Types > Event > Advanced menu, the following options are exists:

 > Disable default confirmation emails for attendees ON/OFF
 > Disable default confirmation emails for host ON/OFF
 
 It would be great to have the following options too:
 
 > Disable default reschedule emails for host ON/OFF
 > Disable default reschedule emails for attendees ON/OFF
 
 > Disable default cancellation emails for host ON/OFF
 > Disable default cancellation emails for attendees ON/OFF

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by albertborsos** [comment]
related issue: https://github.com/calcom/cal.com/issues/12920

**Comment by nessie134** [comment]
This needs to be dealt with. I keep receiving unwanted emails that are not part of any workflows or any options.
