### ISSUE TITLE
[CAL-3254] Booking’s that don’t require payment are showing as “Pending Payment” on /bookings

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13946]
![IMG_6842.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d69a8056-33b5-4340-81ee-d0499ab60a2a/d0f8369b-4e48-49ea-8410-06554ce6f161?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kNjlhODA1Ni0zM2I1LTQzNDAtODFlZS1kMDQ5OWFiNjBhMmEvZDBmODM2OWItNGU0OC00OWVhLTg0MTAtMDY1NTRjZTZmMTYxIiwiaWF0IjoxNzA5MjkxNTI0LCJleHAiOjE3MDkzNzc5MjR9.8rVrc5NPzHvusxJZlwyUU0CKKa9dNxBTq-1_toB-EM4)

Booking links

[https://cal.com/booking/dZwnP4Tx4HNkZ4KPvBS7XG](https://cal.com/booking/dZwnP4Tx4HNkZ4KPvBS7XG)

[https://cal.com/booking/hwrSQSg2Jv836XzT2uuMPy](https://cal.com/booking/hwrSQSg2Jv836XzT2uuMPy)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3254](https://linear.app/calcom/issue/CAL-3254/bookings-that-dont-require-payment-are-showing-as-pending-payment-on)</sub>

**Comment by Udit-takkar** [comment]
@ciaranha I don't see pending payment tag

<img width="1281" alt="Screenshot 2024-03-02 at 1 46 31 AM" src="https://github.com/calcom/cal.com/assets/53316345/905b8a8d-adf3-491b-ad3d-aece9fd1a489">

**Comment by ciaranha** [comment]
> @ciaranha I don't see pending payment tag
> 
> 
> 
> <img width="1281" alt="Screenshot 2024-03-02 at 1 46 31 AM" src="https://github.com/calcom/cal.com/assets/53316345/905b8a8d-adf3-491b-ad3d-aece9fd1a489">
> 
> 

Did you impersonate me? They're still in there as payment pending

**Comment by Udit-takkar** [comment]
> Did you impersonate me? They're still in there as payment pending

yes i did. I didn't see any pending payment tag like you can see in screenshot
