### ISSUE TITLE
Url Input feild Inconsistent UI/UX

### ISSUE THREAD

**Issue by Manideep-Sitaram** [calcom/cal.com#13955]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When we try update the URL with a long name the name feild is overflowing the Confirm panel and the UI seems Inconsistent.

### Steps to Reproduce

1.Go to My setting
2.Clicked on Profile
3.Update the input field of URL

### Actual Results

- The New name feild is exceeding the width of the Confirm username change panel.

### Expected Results

- The UI have to be consistent having the vertical-y scroll bar to avoid this issue

### Evidence
![Screenshot 2024-03-02 133819](https://github.com/calcom/cal.com/assets/159648924/e1ac5c1d-36c0-4ac7-a669-fa6bceac53a9)

**Comment by Ryukemeister** [comment]
@Manideep-Sitaram I tried reproducing this and it seems like there's some issues with the [overflow-x](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x) property of this `Confirm username change` modal. Another issue is that the tick icon gets hidden if a text is long enough, can you also look into that?

Before:
<img width="893" alt="Screenshot 2024-03-02 at 2 19 01 PM" src="https://github.com/calcom/cal.com/assets/86043008/bf6e5ecd-ef3f-4787-ae5c-5f86da7cbc25">

After:
<img width="893" alt="Screenshot 2024-03-02 at 2 19 13 PM" src="https://github.com/calcom/cal.com/assets/86043008/6cef9ad9-0ca5-427e-b415-465722fd3a04">

And there's the width issue
<img width="994" alt="Screenshot 2024-03-02 at 2 19 30 PM" src="https://github.com/calcom/cal.com/assets/86043008/48ad4a81-675c-417a-892e-fd260d255e6c">

**Comment by Manideep-Sitaram** [comment]
Sure Rajiv,
Let me look into this and get back to you
