### ISSUE TITLE
Ability to Schedule a Meeting with Non-Users

### ISSUE THREAD

**Issue by johnaweiss** [calcom/cal.com#13959]
### Is your proposal related to a problem?

Others can schedule meetings with me, but i cannot schedule meetings, unless i enter portal as if i'm not myself, and request a meeting with myself. 

### Describe the solution you'd like

Ability to Schedule a Meeting with Non-Users

**Comment by PeerRich** [comment]
can you not use your own link?

**Comment by johnaweiss** [comment]
As mentioned, i can i enter portal as if i'm not myself, and _request_ a meeting with myself, using a different email address. Obviously doesn't make sense to request a meeting with myself. The resulting meeting then has multiple me's attending. So it's a hacky workaround. Not the same as me simply scheduling a meeting.

**Comment by johnaweiss** [comment]
It seems proper to give both parties the ability to schedule meetings. Since both scenarios happen in reality. The assumption that i'll never need to schedule a meeting with others seems obviously incorrect. 

In both cases, i'm the host. When someone else schedules the meeting, it's a "request". When i schedule it, it's an "invitation". 

In reality, there are two invitation scenarios. 

- Accept/Decline: I select a fixed time, and the guest can simply accept or decline. Outlook, Google Calendar, and Zoom have this feature. 
- Choose Date: I offer multiple dates, and the guest can choose from the dates i offer. On Calendly it's called a "[one-off](https://help.calendly.com/hc/en-us/articles/14074838011543-One-off-meetings#h_01FCRXBD3WR4FZNRBSBP09NW6P)". 

Both invitation scenarios seem missing from cal.com. Cal.com _allows_ the guest the set a specific time and the host can accept/decline. But the _host_ cannot set a specific time for the guest to accept/decline. To allow one but not the other seems an arbitrary limitation, and gives the guest more power than the host. 

To host fixed-time events, you might say, "just use Outlook for that". But cal.com is a front-end for Outlook, which provides a variety of meeting tools, such as videoconferencing tools. If a guest schedules the meeting, we can use cal.com videoconferencing tools. But if the host schedules the meet, we're not able to use the videoconferencing tools. To me, that makes no sense. 

you can book a meeting with yourself, on behalf of someone else using their credentials
That's a workaround, in which i'm impersonating the other person. That seems inappropriate. 

To emulate a fixed-time event, I could create a new event-type, which offers only a single available time. Then the guest can only select that one available time. That's a workaround. It's more steps for and the guest, then simply "accept/decline".
