### ISSUE TITLE
Enhance User Experience with App Store and Installed App Icons

### ISSUE THREAD

**Issue by anuragnegi000** [calcom/cal.com#13967]
### Is your proposal related to a problem?

Add icons for both app store and installed apps to improve user experience and clarity in navigation.

### Describe the solution you'd like

Currently, our application lacks visual indicators for distinguishing between apps available in the store and those already installed. This can lead to user confusion and a suboptimal experience. To improve usability, I propose adding distinct icons for both app store listings and installed applications within our interface. These icons will provide clear visual cues, facilitating easier navigation and reducing user frustration. This enhancement aligns with our goal of delivering a seamless and intuitive user experience.

(Describe your proposed solution here.)

### Describe alternatives you've considered
There are no alternatives as this is a feature

### Additional context

Add icons for both app store and installed apps to improve user experience and clarity in navigation.

### Requirement/Document

![cal com_issue1](https://github.com/calcom/cal.com/assets/115611556/94ae3f35-6c54-4529-81aa-13bbe846087e)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
I think its fine for now. sub links dont need icons imo
