### ISSUE TITLE
Events created in google calendar have incorrect time.

### ISSUE THREAD

**Issue by Amit91848** [calcom/cal.com#13961]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When you have a connected google calendar, events that are created have wrong time. Events are created in UTC timezone even though I am in IST timezone.

### Steps to Reproduce

1. Connect to a google calendar
2. Create an event
3. Book the event
4. Timings are correct in cal.com. But they are off in google calendar.

https://github.com/calcom/cal.com/assets/74371312/630f2198-b47c-46d7-9894-f2e676e99013

### Actual Results

- Event created for wrong time.

### Expected Results

- Event should have the same time in both cal.com and google calendar

**Comment by Ryukemeister** [comment]
@Amit91848 I tried reproducing this issue and I'm not able to do so, can you share some more context around this?

**Comment by Amit91848** [comment]
Nvm there was an issue with google calendar and not cal.com @Ryukemeister.
