### ISSUE TITLE
[CAL-3302] [CAL-3258] Add {first name} variable to Organizer & Scheduler custom event name

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13974]
Currnetly we can only do full name. Would be nice to do first name if you have split the name collection in the booking questions.

![CleanShot 2024-03-04 at 17.52.39@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cd1d1d42-15fe-4a4f-a07e-6bdcb50a9a45/93bd9337-4778-4ecf-a7f0-15a55c11d364?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jZDFkMWQ0Mi0xNWZlLTRhNGYtYTA3ZS02YmRjYjUwYTlhNDUvOTNiZDkzMzctNDc3OC00ZWNmLWE3ZjAtMTVhNTVjMTFkMzY0IiwiaWF0IjoxNzA5NTc0ODMzLCJleHAiOjE3MDk2NjEyMzN9.22X9rzi7HkcPGgqoxM0e_dWIPECZpxUnhk5Ut1Q36V8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3258](https://linear.app/calcom/issue/CAL-3258/add-first-name-variable-to-organizer-and-scheduler-custom-event-name)</sub>

<sub>[CAL-3302](https://linear.app/calcom/issue/CAL-3302/[cal-3258]-add-first-name-variable-to-organizer-and-scheduler-custom)</sub>

**Comment by angshumanraj** [comment]
Hello team,

I'm interested in taking on the [CAL-3258] task to integrate the {first name} variable into custom event names. Would it be possible to assign this issue to me? I'm eager to get started and contribute to the project.

Thank you,
Angshuman Pal Chowdhury

**Comment by ciaranha** [comment]
@angshumanraj No need to have it assigned. Feel free to make a or and the team will review it.

**Comment by angshumanraj** [comment]
Thanks for the clarification. Is there anything specific I should know or any setup instructions I should follow for this project?

**Comment by Ryukemeister** [comment]
> Thanks for the clarification. Is there anything specific I should know or any setup instructions I should follow for this project?

With regards to setup I think the readme should be good enough to get started :)

**Comment by angshumanraj** [comment]
@Ryukemeister hi, I'm currently running the project on Gitpod. Could you please suggest how I can create or view the issue in the browser so I can start working on it? Thank you for your assistance.

**Comment by Ryukemeister** [comment]
@angshumanraj you have to create an event type first and then navigate to the `advanced` tab inside of this newly created event type, you'll see a booking questions section there

**Comment by angshumanraj** [comment]
thanks for the response and clarification . On it
