### ISSUE TITLE
[CAL-3439] Location set to blank, but keeps adding cal video link

### ISSUE THREAD

**Issue by solace** [calcom/cal.com#13977]
### Issue Summary

Despite location being left blank on an event type, when a location is confirmed, the calendar entry adds cal video as a default which causes confusion with the attendees.

### Steps to Reproduce

Edit the event, in location, leave blank, and remove any existing entries.

### Actual Results

When an event is confirmed, the calendar item contains a link to cal video.

### Expected Results

The calendar item should have nothing in the location.

### Technical details

No additional information.

### Evidence

A guest booked an interview time via cal.com using an event type which displays an empty location in edit view. But the calendar entry on confirmation shows a cal video link. On the day, the guest was sitting in cal video waiting even though we had made other arrangements speak via a different method because the calendar entry for location was not empty as I had intended.

Is there a way to have it left empty and stay empty? Or at least correctly report that this option cannot be removed in edit view?

Thanks

<sub>[CAL-3439](https://linear.app/calcom/issue/CAL-3439/location-set-to-blank-but-keeps-adding-cal-video-link)</sub>

**Comment by Ryukemeister** [comment]
@Udit-takkar @sean-brydon is there a way we can let someone know that if they have an empty location set in an event type it will default back to cal video? like a tooltip or some kind of a warning

**Comment by Udit-takkar** [comment]
> @Udit-takkar @sean-brydon is there a way we can let someone know that if they have an empty location set in an event type it will default back to cal video? like a tooltip or some kind of a warning

yeah we should add this info somewhere

**Comment by solace** [comment]
Or maybe just not allow it to be set to empty? It's not very intuitive at the moment.

**Comment by PeerRich** [comment]
i agree. an empty location should be fine. i am surprised we dont offer this yet

**Comment by PeerRich** [comment]
/maige never add the "🚧 wip / in the making" label

**Comment by ASQUAREEE** [comment]
> i agree. an empty location should be fine. i am surprised we dont offer this yet

We can Implement a feature where leaving the location field blank in an event type automatically defaults to a generic placeholder (e.g. "Virtual Meeting")
