### ISSUE TITLE
[CAL-3256] Workflows "Meeting URL" not showing up in emails

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13972]
When adding Meeting URL to a workflow email, it is returning as completely blank / not appearing at all.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3256](https://linear.app/calcom/issue/CAL-3256/workflows-meeting-url-not-showing-up-in-emails)</sub>

**Comment by CarinaWolli** [comment]
@ciaranha do you know what video app was used and what workflow trigger?

Cal Video link on 'when new event is booked' trigger works for me

**Comment by ciaranha** [comment]
@CarinaWolli it was Whereby

**Comment by CarinaWolli** [comment]
> @CarinaWolli it was Whereby

Thank you, I can reproduce it with Wherby. The issue is that the link is saved in the location but not in metadata as the videoCallUrl
