### ISSUE TITLE
[CAL-3259] Allow people who created account with Google to add an email login

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13978]
We get a bunch of requests every week from people who signed up with Google and now want to add an email to login for a variety of reasons (changing from Google to something else, updated emil in google and cal.com login breaks)

We should allow people to add an email login if they have created their account with Google.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3259](https://linear.app/calcom/issue/CAL-3259/allow-people-who-created-account-with-google-to-add-an-email-login)</sub>

**Comment by PeerRich** [comment]
this is a very common UI/UX for SaaS apps where you can add multiple ways of signing in. we should do the same and make it easily discoverable in settings

**Comment by varshith257** [comment]
@PeerRich Can I get assigned this issue?
