### ISSUE TITLE
Set time before/after event type 

### ISSUE THREAD

**Issue by AlexRoehm** [calcom/cal.com#1398]
> Please check if your Feature Request has not been already raised in the [Discussions Tab](https://github.com/calendso/calendso/discussions), as we would like to reduce duplicates. If it has been already raised, simply upvote it 🔼.

### Is your proposal related to a problem?

When I am working from home office I usually do Video calls. If I choose to offer an in person meeting, I need to commute to one of my offices. This takes me 20min before the meeting and in some cases time to get back. For some kinds of meetings I like also preparation time instead of time to commute. This feature I have used with calendly.

### Describe the solution you'd like

Have two settings per event type - time before and time after - which is checked in the calendar before offering available times. 

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
@emrysal is working on this already :) should go live soon

**Comment by PeerRich** [comment]
@Jaibles anything that needs to be mocked? or has this been mocked already? can you show the screenshot, here?

@alishaz-polymath do you want to work on this?

gives @emrysal a bit more room to work on cached calendars and availability 🙏

**Comment by alishaz-polymath** [comment]
Yeah, I can pick this up!

**Comment by Jaibles** [comment]
I'll mock this and put in a link 👍

**Comment by Jaibles** [comment]
[Here is a link to the designs](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=3412%3A41843)

And a screenshot...
<img width="1440" alt="CleanShot 2022-02-22 at 10 45 40@2x" src="https://user-images.githubusercontent.com/4536123/155116688-a12548d5-fecf-49db-8914-c723fd95407f.png">
