### ISSUE TITLE
[CAL-3260] Double & Triple dashes getting in to public booking links

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13980]
We have had two cases recently of users ending up with "--" and "---" in their public booking links and when you try to visit the page it is throwing a 404.

In both cases, the users had space, -, space or similar with a (. When you type these out when creating an event type you can see that we add double and triple dashes in the URL in the modal but after you hit proceed we strip it out.

I think when users are updating their username, we are regenerating the links and taking the URL from the title again but not stripping it out.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3260](https://linear.app/calcom/issue/CAL-3260/double-and-triple-dashes-getting-in-to-public-booking-links)</sub>

**Comment by ikbalarslann** [comment]
i can take this one
