### ISSUE TITLE
[CAL-3329] [CAL-3267] Write avatar migration

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#13994]
- [ ] Completely remove this data from user and team tables
- [ ] App should rely on the avatars coming from the separate avatar table
- [ ] (potentially) use AvatarAPI.com to backfill missing avatars
  - [ ] #14019

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3267](https://linear.app/calcom/issue/CAL-3267/write-avatar-migration)</sub>

<sub>[CAL-3329](https://linear.app/calcom/issue/CAL-3329/[cal-3267]-write-avatar-migration)</sub>

**Comment by PeerRich** [comment]
great idea
