### ISSUE TITLE
[CAL-3264] Embed in email not pulling any availability

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13992]
We recently fixed this for individual event types, but it's still not working for team events.

> Right now if you try to embed any event type in an email, it takes a really long time to load availability and once it does, it says "No availability" even when there is loads.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3264](https://linear.app/calcom/issue/CAL-3264/embed-in-email-not-pulling-any-availability)</sub>

**Comment by Udit-takkar** [comment]
@ciaranha already fixed here https://github.com/calcom/cal.com/pull/13990 (not live yet)

**Comment by CarinaWolli** [comment]
already fixed in main
