### ISSUE TITLE
[CAL-3271] Paypal app is not working

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#14005]
> We installed Paypal and the integration was working smoothly until today.
>
> They reported problems while trying to pay for booking. And while debugging it, we decided to Uninstall and Reinstall the Paypal integration by adding the App ID and Secret again.
>
> It got stuck.
>
> Right now:
>
> \- We cannot see bookings (it times out in the website)
>
> \- We cannot see the event types (times out too)
>
> \- We cannot deactivate Paypal (we get an error
>
> ### **Something has failed**
>
> \[ { "code": "invalid_type", "expected": "string", "received": "undefined", "path": \[ "apps", "stripe", "currency" \], "message": "Required" } \]

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3271](https://linear.app/calcom/issue/CAL-3271/paypal-app-is-not-working)</sub>

**Comment by asadath1395** [comment]
@ciaranha I think its working fine now, just now i installed the PayPal app and it went through smoothly without a problem.
