### ISSUE TITLE
[CAL-3436] [CAL-3272] Enable sending email as the Company or Org - ie coming from their own email address and having their logo

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#14006]
This has been requested a number of times in support within one week (3-5 times).

Today, all emails come from [hello@cal.com](mailto:hello@cal.com) and have the [cal.com](http://cal.com) logo.

An organisation should be able to have the email confirmations look like they come from their own email address, and therefore show their own logo.

They should be able to specify the exact email.

We would need to use the Sendgrid API to add new SMTP records and verify them

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3272](https://linear.app/calcom/issue/CAL-3272/enable-sending-email-as-the-company-or-org-ie-coming-from-their-own)</sub>

<sub>[CAL-3436](https://linear.app/calcom/issue/CAL-3436/[cal-3272]-enable-sending-email-as-the-company-or-org-ie-coming-from)</sub>

**Comment by ASQUAREEE** [comment]
Please assign this issue to me

> This has been requested a number of times in support within one week (3-5 times).
> 
> Today, all emails come from [hello@cal.com](mailto:hello@cal.com) and have the [cal.com](http://cal.com) logo.
> 
> An organisation should be able to have the email confirmations look like they come from their own email address, and therefore show their own logo.
> 
> They should be able to specify the exact email.
> 
> From [SyncLinear.com](https://synclinear.com) | [CAL-3272](https://linear.app/calcom/issue/CAL-3272/enable-sending-email-as-the-company-or-org-ie-coming-from-their-own)
