### ISSUE TITLE
[CAL-3270] Zapier doesn't allow FirstName and LastName split

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#14004]
Currently, we don't have a way in Zapier to identify firstname and lastname split which is allowed in our bookings responses. This is quite a crucial difference as well, since many people prefer to use Zapier for Salesforce account creation and it is potentially faulty unless there's a firstname and lastname split.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3270](https://linear.app/calcom/issue/CAL-3270/zapier-doesnt-allow-firstname-and-lastname-split)</sub>

**Comment by ikbalarslann** [comment]
i can take this one  if you didn't started working on it

**Comment by CarinaWolli** [comment]
I just looked into that and see that we already return first name and last name in the responses. Let's first clarify what the issue is here (cc @alishaz-polymath )

**Comment by alishaz-polymath** [comment]
Looks like we already do it!
