### ISSUE TITLE
[CAL-3268] Event type: Changing the email displayed as the Organizer copy adjustments

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#14001]
There's two things we need to update here.

In the implementation, 

1. there's an extra label on the input that implies we're just sending details to this email address. We are not just sending the email, we are using this person as the organiser. That means most importantly, that we will show that email as the organizer to your booker - thats' the main reason people want this feature. Simply removing that label makes it clearer
2. I know why we added this help text, but we need to make the tooltip actually helpful for the feature as per designs and find another solution for this text. My proposal is we show a toast the first time someone toggles this and never again.
3. We're missing additional help text below the input when this is toggled on

**Current**

![CleanShot 2024-03-07 at 08.57.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c89adc21-2c9f-46c7-86bf-1ef0fe20cf4d/22d97208-a87b-4a7a-bbf3-8c8426f2f025?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jODlhZGMyMS0yYzlmLTQ2YzctODZiZi0xZWYwZmUyMGNmNGQvMjJkOTcyMDgtYTg3Yi00YTdhLWJiZjMtOGM4NDI2ZjJmMDI1IiwiaWF0IjoxNzA5ODAyMTYyLCJleHAiOjE3MDk4ODg1NjJ9.05_j04G5fPZSUEmH4IqT_dFSke4v8nWCndqIlumZswI)

**Designs**
![CleanShot 2024-03-07 at 09 16 44@2x](https://github.com/calcom/cal.com/assets/4536123/4e1a72f4-56a1-49d6-a8ca-f18c65cca1aa)
![CleanShot 2024-03-07 at 09 16 52@2x](https://github.com/calcom/cal.com/assets/4536123/731e4cd5-483a-4d77-ae9e-4fc8c7a784aa)

Please also pay specific attention to the spacing of the input that appears below when toggled and match it to designs.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3268](https://linear.app/calcom/issue/CAL-3268/event-type-changing-the-email-displayed-as-the-organizer-copy)</sub>

**Comment by Udit-takkar** [comment]
Just one thing  the help text "Please note that you may need to disconnect and then reconnect your 'Add to Calendar' account to use this feature." was added because for older calendar connection this feature wouldn't work and they would have to reconnect

**Comment by ciaranha** [comment]
> Just one thing the help text "Please note that you may need to disconnect and then reconnect your 'Add to Calendar' account to use this feature." was added because for older calendar connection this feature wouldn't work and they would have to reconnect

I recall yea. What are the conditions under which "they may have to reconnect"? If it's more than 50% should we just insist that people do and show a message once, or can we show a toast the first time they toggle it?

@Udit-takkar 
Uploading CleanShot 2024-03-07 at 11.33.42.mp4…
