### ISSUE TITLE
[CAL-3273] Org usersnames

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#14014]
Usernames are linked to emails.

If a user updates their company email, and updates it in Cal.com, the username does not get updated.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3273](https://linear.app/calcom/issue/CAL-3273/org-usersnames)</sub>

**Comment by PeerRich** [comment]
how do you update a company email? Ive never heard this. admins can already change usernames, so that should be fine

**Comment by ciaranha** [comment]
> how do you update a company email? Ive never heard this. admins can already change usernames, so that should be fine

Marriage with a second name change. Happened this week with someone in one of our existing orgs. Zomars tried to change it in the db and looks updated when looking at the user info but all links still not updated.
