### ISSUE TITLE
[CAL-3361] always show intercom on desktop by default (hidden on mobile)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14043]
we wanna start showing the intercom launcher on every page by default.

lets make it possible to toggle it on and off:

![CleanShot 2024-04-04 at 11 49 50@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5cf17ea6-de1d-48be-ab07-9cb48c57efd6/17e1d8bd-c8a5-46a9-aae7-a0ffaec04ff3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81Y2YxN2VhNi1kZTFkLTQ4YmUtYWIwNy05Y2I0OGM1N2VmZDYvMTdlMWQ4YmQtYzhhNS00NmE5LWFhZTctYTBmZmFlYzA0ZmYzIiwiaWF0IjoxNzEyMjQ4MTY3LCJleHAiOjE3MTIzMzQ1Njd9.rLOkh6P8kHCfFnB607Nrv7Io4cx_cBlHUfpwy-vQf8Q)

![CleanShot 2024-04-04 at 11 48 42@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7b986c46-0e05-4cc7-acdb-8819c3027797/33863239-5240-4804-936e-b7ce13b3c178?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83Yjk4NmM0Ni0wZTA1LTRjYzctYWNkYi04ODE5YzMwMjc3OTcvMzM4NjMyMzktNTI0MC00ODA0LTkzNmUtYjdjZTEzYjNjMTc4IiwiaWF0IjoxNzEyMjQ4MTY3LCJleHAiOjE3MTIzMzQ1Njd9.6d4tsuIC-lx0jvwP-VE5RMbga5r9O7_JvA7wmc4xlEA)

![CleanShot 2024-03-09 at 10 13 51@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6572caf7-9416-4e72-ab26-3776c86c16b8/7f976f20-146f-4b1d-a410-e2e91263f1dd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82NTcyY2FmNy05NDE2LTRlNzItYWIyNi0zNzc2Yzg2YzE2YjgvN2Y5NzZmMjAtMTQ2Zi00YjFkLWE0MTAtZTJlOTEyNjNmMWRkIiwiaWF0IjoxNzEyMjQ4MTY3LCJleHAiOjE3MTIzMzQ1Njd9.6W_0sEUOSCMj8c7rI_AuktjQEmLJLnVfjsrXM7VfioM)

we only wanna hide it on mobile, to open it on mobile, you can still go through help:

![CleanShot 2024-03-09 at 10 14 31@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/027d1321-30cf-4f1a-af32-6de6ad9efb2b/854a2cf7-310c-464b-9452-8e8c200a3652?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wMjdkMTMyMS0zMGNmLTRmMWEtYWYzMi02ZGU2YWQ5ZWZiMmIvODU0YTJjZjctMzEwYy00NjRiLTk0NTItOGU4YzIwMGEzNjUyIiwiaWF0IjoxNzEyMjQ4MTY3LCJleHAiOjE3MTIzMzQ1Njd9.2F8v5siG4wH9XOqzuOcWN0kKxG30DlVoRfySC8XwHEQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3361](https://linear.app/calcom/issue/CAL-3361/always-show-intercom-on-desktop-by-default-hidden-on-mobile)</sub>

**Comment by murtaza030** [comment]
please more explain

**Comment by PeerRich** [comment]
@SomayChauhan will work on this

**Comment by PeerRich** [comment]
@ThyMinimalDev will take over
