### ISSUE TITLE
New round-robin team events should defaults to having no assigned team members

### ISSUE THREAD

**Issue by jckw** [calcom/cal.com#14045]
### Issue Summary

When creating a new team event, the default assignment does not include any team members. This behaviour is different to previous versions (I think) and confusing because the schedule shows as empty (rightly so!).

It would be better to enable the "Add all team members, including future members" setting by default here IMO, or add a warning that there are currently no assigned team members for this event type.

### Steps to Reproduce

1. Create a team
2. Create a round-robin event
3. View the event preview, which shows no available dates
4. Note that the event setting have no members added by default

I would expect "all team members, including future members" to be enabled.

### Actual Results

- No team members are assigned to the event

![CleanShot from Jack Weatherilt 2024-03-09 at 14 18 06](https://github.com/calcom/cal.com/assets/11884004/e3cf62cf-14f6-4d1e-99fe-34f4e30f78e9)

Empty schedule example:

![CleanShot from Jack Weatherilt 2024-03-09 at 14 16 53@2x](https://github.com/calcom/cal.com/assets/11884004/981a28e4-a03b-446a-90c3-34d32e253ea2)

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Fresh install on tag v.3.8.7

### Evidence

- Screenshots above

**Comment by PeerRich** [comment]
it depends. a lot of teams are very big and wont use every person in the team

![CleanShot 2024-03-11 at 10 16 52@2x](https://github.com/calcom/cal.com/assets/8019099/b17a18d7-cc25-4e34-8745-15dfce52cab4)

**Comment by jckw** [comment]
Yeah, that makes sense. I guess it would still be good to have a warning somewhere that no one is assigned to this meeting, but that's lower prio

**Comment by ciaranha** [comment]
We will tackle this problem with this issue https://github.com/calcom/cal.com/issues/14848
