### ISSUE TITLE
[CAL-3479] Rejected Appointments are Still Charged

### ISSUE THREAD

**Issue by Kfelts** [calcom/cal.com#14040]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a paid appointment is declined, usually the charge does not go through. On 3/3 and appointment request was submitted which I rejected. I asked the client to schedule again at a different time, and they did. However, I was alerted today that they were charged twice, thus requiring a refund and payment of those fees.

### Steps to Reproduce

1. On dashboard, decline paid appointment
2. When going on to stripe, it is confirmed that the charge did go through
3. Rejected appointment was also confirmed

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Charge to be reversed or hold to be released

* What's happening right now that is different from what is expected

Declined appointments are still being charged, requiring manual refunds

* This is an ideal result that the system should get after the tests are performed

N/A

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

Tested by booking an actual appointment, rejecting it, and confirming the charge went through.

![Screenshot 2024-03-08 at 1 42 12 PM](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/047e20fb-3cfd-4b3d-9973-60414950eb3d/04ff588e-b613-4d4d-b044-f89660feca4f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wNDdlMjBmYi0zY2ZkLTRiM2QtOTk3My02MDQxNDk1MGViM2QvMDRmZjU4OGUtYjYxMy00ZDRkLWIwNDQtZjg5NjYwZmVjYTRmIiwiaWF0IjoxNzEzMjcwOTU2LCJleHAiOjE3MTMzNTczNTZ9.C17Ggs_5dD9KFtVxWc94Bz9Y9xxj-DYb3qUponj_oNI)

![Screenshot 2024-03-08 at 1 43 57 PM](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/46063c6c-1fa6-4056-915b-4b3c99791228/59183cba-a83a-42bc-8a50-79c9db9f02d6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NjA2M2M2Yy0xZmE2LTQwNTYtOTE1Yi00YjNjOTk3OTEyMjgvNTkxODNjYmEtYTgzYS00MmJjLThhNTAtNzljOWRiOWYwMmQ2IiwiaWF0IjoxNzEzMjcwOTU2LCJleHAiOjE3MTMzNTczNTZ9.SLovLvJd_UAoXxQ_iUxpEfLIhXURFiLYdEdqVRyj3OA)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3479](https://linear.app/calcom/issue/CAL-3479/rejected-appointments-are-still-charged)</sub>

**Comment by sean-brydon** [comment]
> Found a bug? Please fill out the sections below. 👍
> 
> ### Issue Summary
> When a paid appointment is declined, usually the charge does not go through. On 3/3 and appointment request was submitted which I rejected. I asked the client to schedule again at a different time, and they did. However, I was alerted today that they were charged twice, thus requiring a refund and payment of those fees.
> 
> ### Steps to Reproduce
> 1. On dashboard, decline paid appointment
> 2. When going on to stripe, it is confirmed that the charge did go through
> 3. Rejected appointment was also confirmed
> 
> Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
> 
> Charge to be reversed or hold to be released
> 
> * What's happening right now that is different from what is expected
> 
> Declined appointments are still being charged, requiring manual refunds
> 
> * This is an ideal result that the system should get after the tests are performed
> 
> N/A
> 
> * How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
> 
> Tested by booking an actual appointment, rejecting it, and confirming the charge went through.
> 
> ![Screenshot 2024-03-08 at 1 42 12 PM](https://camo.githubusercontent.com/228b8d9107f27060193ea626dc70e8c2ff72c65522f56b6902aa971791b1503d/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f30343765323066622d336366642d346233642d393937332d3630343134393530656233642f30346666353838652d623631332d346434642d623034342d6638393636306665636134663f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c3255344e6d4a6d4f5455334c5751344d6d59744e4459315a5331694d6a41314c54457a4e5455314f575930596a59794d7938774e44646c4d6a426d5969307a59325a6b4c5452694d3251744f546b334d7930324d4451784e446b314d4756694d3251764d44526d5a6a55344f475574596a59784d7930305a44526b4c5749774e4451745a6a67354e6a59775a6d566a5954526d4969776961574630496a6f784e7a457a4d6a63774f5455324c434a6c654841694f6a45334d544d7a4e54637a4e545a392e4331374767735f356444394b4674567857633934427a39593978786a2d445962337155706f6e6a5f6f4e49)
> 
> ![Screenshot 2024-03-08 at 1 43 57 PM](https://camo.githubusercontent.com/0040d4922bc27c45e003458ae052690837b868efffbf5dcc20129b55a97e6ecb/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f34363036336336632d316661362d343035362d393135622d3462336339393739313232382f35393138336362612d613833612d343262632d386135302d3739633964623966303264363f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c3255344e6d4a6d4f5455334c5751344d6d59744e4459315a5331694d6a41314c54457a4e5455314f575930596a59794d7938304e6a41324d324d32597930785a6d45324c5451774e5459744f54453159693030596a4e6a4f546b334f5445794d6a67764e546b784f444e6a596d45745954677a595330304d6d4a6a4c5468684e5441744e7a6c6a4f5752694f5759774d6d51324969776961574630496a6f784e7a457a4d6a63774f5455324c434a6c654841694f6a45334d544d7a4e54637a4e545a392e534c6f764c764a645f55416f5878515f6955787045664c496858555246694c59644564715652796a334f41)
> 
> From [SyncLinear.com](https://synclinear.com) | [CAL-3479](https://linear.app/calcom/issue/CAL-3479/rejected-appointments-are-still-charged)
![CleanShot 2024-04-24 at 12 14 21@2x](https://github.com/calcom/cal.com/assets/55134778/0c3d1d4a-4ee7-431a-8f25-aca03b7e47ae)

Hi sorry for the issue you are facing - could you please let me know your cal.com username so i can take a look at what is happening here on your account/stripe. I've tested this myself locally and can see that upon canceling a requires confirmation event we do indeed handle refunds.  

Feel free to reply here or DM me on discord / [twitter](https://twitter.com/SeanBrydon13) so we can dig into this for you
