### ISSUE TITLE
[CAL-3437] Team events with "Organizer's default app" show no location on Booker

### ISSUE THREAD

**Issue by jckw** [calcom/cal.com#14046]
### Issue Summary

Team events with the location set to "Organizer's default app" are missing the "location" (e.g. Cal Video/Zoom) on the booker component and don't create meeting links. This means that the booking UI cannot be used to book Zoom calls.

### Steps to Reproduce

1. Ensure you have a default app for your profile (e.g. Cal Video)
2. Create a team event (where you are one of the assigned team members)
3. Select "Organizer's default app" in the event setup location field
4. Preview the event
5. See that there is no location rendered, and when booking the event, no link is created

### Actual Results

![CleanShot from Jack Weatherilt 2024-03-09 at 15 55 34@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b7f7b6e6-c2c5-48bb-88a0-2e97a26ffa6e/27c5f044-1a63-4a5d-816b-3fdc0ce57e61?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iN2Y3YjZlNi1jMmM1LTQ4YmItODhhMC0yZTk3YTI2ZmZhNmUvMjdjNWYwNDQtMWE2My00YTVkLTgxNmItM2ZkYzBjZTU3ZTYxIiwiaWF0IjoxNzEzMTg0MDQ0LCJleHAiOjE3MTMyNzA0NDR9.7mmdifKIFnX_vRwV5gAFNV2cf0P_4Hmgss5h3woI2iU)

* There is clearly a gap in the UI (empty padded divs) where nothing has been rendered, suggesting that this is a bug. This is also noticeably different to when no location is set, and that gap doesn't exist.

### Expected Results

* I would expect it to show the organiser's default app app, e.g. Cal or Zoom. Even if it intentionally shows no app here, I would expect the booking to create a valid event link.

### Technical details

* Test on main (b8c1d623f) on a fresh install on localhost
* New team, one team member

### Evidence

![CleanShot from Jack Weatherilt 2024-03-09 at 16 04 20@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8f4df3d0-a1ec-47e8-8960-537a609583d0/f221ccff-bfcd-41d0-b6ec-8390277b06ad?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84ZjRkZjNkMC1hMWVjLTQ3ZTgtODk2MC01MzdhNjA5NTgzZDAvZjIyMWNjZmYtYmZjZC00MWQwLWI2ZWMtODM5MDI3N2IwNmFkIiwiaWF0IjoxNzEzMTg0MDQ0LCJleHAiOjE3MTMyNzA0NDR9.eYncGXjVISFYhvuprMZmoA0DZeHcXlCl6-fllF2hE_w)

![CleanShot from Jack Weatherilt 2024-03-09 at 15 57 59@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f0c7da9f-5c6a-4f09-94b0-af4a88ae388f/1af56d6f-ff76-44a0-818b-2478f64efd05?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMGM3ZGE5Zi01YzZhLTRmMDktOTRiMC1hZjRhODhhZTM4OGYvMWFmNTZkNmYtZmY3Ni00NGEwLTgxOGItMjQ3OGY2NGVmZDA1IiwiaWF0IjoxNzEzMTg0MDQ0LCJleHAiOjE3MTMyNzA0NDR9.\__OWdd10Z7wRw2V7GqLQqKNk4sm2wZmkb_6uaV-gc0c)

![CleanShot from Jack Weatherilt 2024-03-09 at 16 05 14@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/160c4644-93a1-4cb4-9ad9-1a54c81f8d7a/d29ec17e-8cfd-490b-b6f1-dd107ff3d65e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xNjBjNDY0NC05M2ExLTRjYjQtOWFkOS0xYTU0YzgxZjhkN2EvZDI5ZWMxN2UtOGNmZC00OTBiLWI2ZjEtZGQxMDdmZjNkNjVlIiwiaWF0IjoxNzEzMTg0MDQ0LCJleHAiOjE3MTMyNzA0NDR9.TTmxftJPAKY6_r7bObuWhrfGFJvHWaJ3ND3_0kOtFkE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3437](https://linear.app/calcom/issue/CAL-3437/team-events-with-organizers-default-app-show-no-location-on-booker)</sub>

**Comment by Shaik-Sirajuddin** [comment]
Observed that the meeting links are created and sent via mail ( tested with google meet and cal video ) locally 
Although I see the location is not shown on booking page in prior.

**Comment by jckw** [comment]
What appears in the UI is one thing, but it seems that what appears in the UI right now is tied to what appears in the admin UI.

I.e., when looking at the "Bookings" list, the link doesn't show up there either.

Screenshot attached of the UI I'm talking about:

![CleanShot from Jack Weatherilt 2024-03-27 at 21 38 21](https://github.com/calcom/cal.com/assets/11884004/6ee1e56e-16e8-42ad-a1ab-8c1772228f02)

This is a big issue if you're self-hosting / don't want to use email as the primary mechanism for sharing links
