### ISSUE TITLE
[CAL-3378] allow to select Hungarian language

### ISSUE THREAD

**Issue by albertborsos** [calcom/cal.com#14051]
### Is your proposal related to a problem?

I can not select the Hungarian language for the booking page and my customers are barely speaks english.

### Describe the solution you'd like

I translated all the dictionary items of the booking page. And I would like to select it in Settings > General > Language to actually use it.

### Describe alternatives you've considered

- I wrote to Discord > translations too.
- Looked into the code, but i am not sure where can I enable it to create a PR.

### Additional context

https://github.com/calcom/cal.com/issues/13910

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3378](https://linear.app/calcom/issue/CAL-3378/allow-to-select-hungarian-language)</sub>

**Comment by kissgyula** [comment]
Hello, I am already finished the Hungarian translation on crowdin. Is there any way to test it in place?

I am also cannot select the hungarian language in the dropdown.
