### ISSUE TITLE
[CAL-3466] Add multiple Zoom accounts

### ISSUE THREAD

**Issue by andy-vdg** [calcom/cal.com#14053]
### Describe the solution you'd like
Now that I can set different email addresses for events (awesome thank you!). I also would like to be able to add the Zoom / Teams event to the different accounts. 

Currently I have andy@work.com linked to both Teams and Zoom. 
For one of my events however I use andy@otherwork.com which works great for the calendar invites. However, the event itself is still scheduled in the first accounts Teams / Zoom account. 
A great solution would be to have the ability to add multiple Zoom / Teams accounts like the ability to add multiple Google accounts and then select which one I want to use in the events. 

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3466](https://linear.app/calcom/issue/CAL-3466/feature-send-zoom-teams-meeting-invite-from-calendar-organizer-account)</sub>

**Comment by ciaranha** [comment]
I'm updating the title since if we just allowed adding multiple zoom accounts we already have the ability in the event type to just edit the location to zoom account with the email that matches the add to calendar. 
(ie if Add to calendar = me@work.com then go to location and set it to zoom account = me@work.com)

**Comment by clarkbalan** [comment]
Hello. I am interested in this as well.

I self-host my cal.com . Works well, no complaints. On my main user I can add Zoom (after creating Zoom API keys adding them to .env). 

Then another member of my team (with their own account) tries to add Zoom as an app to their account and Zoom asks them to log in. If they log in with the Zoom account that I used to create API keys then their account gets Zoom integration and I lose my integration. If they use their Zoom account, Zoom says the app they are trying to add does not exist - obviously there is no API in that Zoom account.

So what is the process here?
How Do I have one Zoom Account and then be able to let all team members integrate with it?

Thanks
