### ISSUE TITLE
[CAL-3478] app.cal.com takes 55s to fetch my timezone

### ISSUE THREAD

**Issue by CyriacBr** [calcom/cal.com#14054]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/88228d19-2d54-4431-9a92-7b627847d9a5/605c5503-f44e-4ce1-a9ca-9feac4fd52ba?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84ODIyOGQxOS0yZDU0LTQ0MzEtOWE5Mi03YjYyNzg0N2Q5YTUvNjA1YzU1MDMtZjQ0ZS00Y2UxLWE5Y2EtOWZlYWM0ZmQ1MmJhIiwiaWF0IjoxNzEzMjcwOTQxLCJleHAiOjE3MTMzNTczNDF9.53pP2JxKuDINRCfN3qVvuAKtIjD9H52_Dhf68PpHx0I)

### Steps to Reproduce

1. Create a new account
2. Get redirected to the /getting-started page

### Actual Results

* It takes 55s to fetch my timezone

### Expected Results

* It shouldn't take that long. For a non-technical person, they'll assume the app is broken. And it's even more confusing that the "Next" button isn't disabled while the timezone is being fetched...

### Technical details

* Chrome 114.0

### Evidence

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/70d31d07-c791-4bcc-a5fd-213858a37d4b/07daf896-9e82-4e5f-acc4-59a7170c763c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83MGQzMWQwNy1jNzkxLTRiY2MtYTVmZC0yMTM4NThhMzdkNGIvMDdkYWY4OTYtOWU4Mi00ZTVmLWFjYzQtNTlhNzE3MGM3NjNjIiwiaWF0IjoxNzEzMjcwOTQxLCJleHAiOjE3MTMzNTczNDF9.OygrlChNBqxnf1L4SjqGGZTqMKj00JPKfVmbOzXiTPE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3478](https://linear.app/calcom/issue/CAL-3478/appcalcom-takes-55s-to-fetch-my-timezone)</sub>

**Comment by CyriacBr** [comment]
On a related note, there's no feedback when clicking the next button. I sat there for 10s waiting for something to happen, without any UI feedback whatsoever...

**Comment by jckw** [comment]
I was digging into this endpoint recently (for reference on another project) and also noticed the list of timezones is cut down multiple times in different places from a 1.8mb list of timezones (from this library https://github.com/kevinroberts/city-timezones) only the end up displaying around 300 timezones in the UI.

There's server-side filtering (so only ~750 endpoints are returned via API endpoint) the and client-side filtering in the UI bringing the total displayed timezones to ~300 I think.

**Comment by keithwillcode** [comment]
Thanks for the confirmation, @rudyrdx
