### ISSUE TITLE
Word misspelled in .github/PULL_REQUEST_TEMPLATE.md 

### ISSUE THREAD

**Issue by Gabbar-v7** [calcom/cal.com#14080]
### Issue Summary

There is spelling error in Ln16 of .github/PULL_REQUEST_TEMPLATE.md 
The word a is misspelled as ab.

### Steps to Reproduce
1. Click on this link: https://github.com/calcom/cal.com/blob/main/.github/PULL_REQUEST_TEMPLATE.md
2. See line16

#### Alt.
1. Create a new Pull Request 
2. Checkout 2nd line in ## Requirement/Documentation

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
This might be a bug because no other word suites correctly in that space. Also the word ab doesn't exist.

### Actual Results

- The sentence is "- If there is ab UI/UX design document, please, share it here."

### Expected Results

- The sentence should be "- If there is a UI/UX design document, please, share it here."

**Comment by manideep1428** [comment]
fix : #14081
