### ISSUE TITLE
[CAL-3462] Google Meet link missing after rescheduling team meeting

### ISSUE THREAD

**Issue by mr-visor** [calcom/cal.com#14086]
### Issue Summary

If someone schedules a team meeting and organizers have Google Meet connected as a default conferencing app, Google Meet link is on the event (both on the meeting scheduling page an in the email). If organizer **confirms it and then reschedules the event**, Google Meet link is missing from the rescheduled event (only in the email - on the meeting page it's still there).

### Prerequisites

* "Requires confirmation" option should be enabled for the event type.

### Steps to Reproduce

1. Schedule new team meeting (Google Meet should be connected) as a guest user (for example using incognito mode in the browser).
2. Organizer should **confirm it first**.
3. Then organizer should reschedule it.
4. Check the email.

### Actual Results

* After rescheduling, the email does not have a link to Google Meet.

### Expected Results

* After rescheduling, the email have a link to Google Meet.

### Technical details

* [Cal.com](http://Cal.com) v3.8.9 (docker)

### Evidence

* First email (Google Meet link is in place):

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/660fa48f-11d3-4c71-983c-1fde6982f28b/d6111ca6-3ee7-4577-9235-fd2fddcfc3ba?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82NjBmYTQ4Zi0xMWQzLTRjNzEtOTgzYy0xZmRlNjk4MmYyOGIvZDYxMTFjYTYtM2VlNy00NTc3LTkyMzUtZmQyZmRkY2ZjM2JhIiwiaWF0IjoxNzEzMjQ5MDQ3LCJleHAiOjE3MTMzMzU0NDd9.tn0i_v1AJ6822JUltIR72eUWLLe0wJJdDHWXA4tjTF4)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4008e3fe-a4bb-41f1-b0b9-4d9440833720/d80db6ce-0d9c-4ad8-a86c-1d0b37fab342?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80MDA4ZTNmZS1hNGJiLTQxZjEtYjBiOS00ZDk0NDA4MzM3MjAvZDgwZGI2Y2UtMGQ5Yy00YWQ4LWE4NmMtMWQwYjM3ZmFiMzQyIiwiaWF0IjoxNzEzMjQ5MDQ3LCJleHAiOjE3MTMzMzU0NDd9.\_Z_9vXNggm7dAvAgkbrtYYlKqftK5EsyfnrkM_AayOE)

* Rescheduling email (Google Meet link is absent):

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c4e161e1-c8a2-44d9-a4a8-5a22a571709d/c8fa1ef0-1e75-4e2b-8ef1-f82e4f692bb7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jNGUxNjFlMS1jOGEyLTQ0ZDktYTRhOC01YTIyYTU3MTcwOWQvYzhmYTFlZjAtMWU3NS00ZTJiLThlZjEtZjgyZTRmNjkyYmI3IiwiaWF0IjoxNzEzMjQ5MDQ3LCJleHAiOjE3MTMzMzU0NDd9.sRTAwp6wwY3uVLb5h8LKqOYIOqDcUguDgdswMXVcE9g)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/82665cd2-d25c-4dbb-a3ee-5ca09abc0df2/71352753-a44c-45b8-a1ca-31d84c42b747?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84MjY2NWNkMi1kMjVjLTRkYmItYTNlZS01Y2EwOWFiYzBkZjIvNzEzNTI3NTMtYTQ0Yy00NWI4LWExY2EtMzFkODRjNDJiNzQ3IiwiaWF0IjoxNzEzMjQ5MDQ3LCJleHAiOjE3MTMzMzU0NDd9.MTqEFe7NiVDPz2Niu_iC1NKw_Sdp6yyjfi-pbiJrriE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3462](https://linear.app/calcom/issue/CAL-3462/google-meet-link-missing-after-rescheduling-team-meeting)</sub>

**Comment by mr-visor** [comment]
Seems to be similar to https://github.com/calcom/cal.com/issues/13931

**Comment by manideep1428** [comment]
It working for me. I tried many times, it works, try again
