### ISSUE TITLE
[CAL-3748] Iframing issue related to SameSite attribute on very old version of cal.com

### ISSUE THREAD

**Issue by aelmasry** [calcom/cal.com#14098]
We're encountering an issue while integrating the appointment booking service calendar from our Calcom app into our website, either as an iframe or a pop-up window. Despite following the integration steps outlined in the documentation, we're facing difficulties as it's not functioning as expected, and we're observing errors in the console.

The Calcom app is self-hosted on AWS, and in its edition from two years ago, we added new functions such as creating interviews and generating tokens.

We've diligently checked the console for error messages, but unfortunately, we're struggling to pinpoint the exact cause of the problem. Interestingly, when attempting to use the same link in a new tab, it functions properly.

If anyone has experience with integrating the Calcom app into a website or has encountered similar issues before, we would greatly appreciate any guidance or suggestions you can provide.

This link look

http://localhost:3000/availability/185?next=/event-types/185&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjo1LCJ1c2VybmFtZSI6Im0tbWFobW91ZC1oYWt0aXYtY29tIiwiZW1haWwiOiJtLm1haG1vdWRAaGFrdGl2LmNvbSIsIm5hbWUiOiJIQUtUSVYiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwOTgxNTk4Mn0.zCrv-womJ9W950l0dhnGyn9RVHt-tQOCTeK34eh1Nfs

Thank you in advance for your help

![Screenshot from 2024-03-12 21-35-37](https://github.com/calcom/cal.com/assets/479740/50bc72c8-b33d-47f2-9794-962d8d844355)

![Screenshot from 2024-03-07 15-55-04](https://github.com/calcom/cal.com/assets/479740/d84b8f7d-779d-4b4c-a15c-8bbbbcd1961a)
![Screenshot from 2024-03-07 16-00-05](https://github.com/calcom/cal.com/assets/479740/d3d7e2e2-f1ff-46d1-b033-6e7cbd4ca418)
![Screenshot from 2024-03-11 00-11-27](https://github.com/calcom/cal.com/assets/479740/b5e2e8a2-1e0c-4d96-9bd5-19d88f19438d)
![Screenshot from 2024-03-11 00-56-40](https://github.com/calcom/cal.com/assets/479740/3ff8bb59-19d0-4efa-ba3c-81a57c208eb6)
![Screenshot from 2024-03-11 22-43-22](https://github.com/calcom/cal.com/assets/479740/b1c8e22c-014c-4b47-9213-5370d37d26f7)

<sub>[CAL-3748](https://linear.app/calcom/issue/CAL-3748/i-try-call-our-calcom-app-in-embed-iframe-html-issue)</sub>

**Comment by aelmasry** [comment]
There is a relatively new cookie attribute called SameSite that was being set by my server automatically. Disabling this (while retaining the settings listed in the question) allows the iframe access to its own cookies in Chrome.

See also [Chrome feature status](https://www.chromestatus.com/feature/4672634709082112) & [IETF draft](https://datatracker.ietf.org/doc/html/draft-west-first-party-cookies-07)

UPDATE Aug 2020

Chrome now blocks cookies without SameSite set, so you need to explicitly set it to samesite=none and secure=true.

https://stackoverflow.com/questions/45094712/iframe-not-reading-cookies-in-chrome

**Comment by PeerRich** [comment]
> Chrome now blocks cookies without SameSite set, so you need to explicitly set it to samesite=none and secure=true.


@hariombalhara can you look into this?

**Comment by hariombalhara** [comment]
We added support for SameSite attribute sometime 2 years ago itself.  As [https://github.com/calcom/cal.com/blob/d4f3726875aa6f9b74b73b2fd16b9019f990451f/packages/lib/default-cookies.ts#L32](https://github.com/calcom/cal.com/blob/d4f3726875aa6f9b74b73b2fd16b9019f990451f/packages/lib/default-cookies.ts#L32)

Could you see if you have similar code in your version(which you mention is 2 years old). If it's there maybe debug there why it is not working.

Also, it is still possible that there might be some issues in that old version.

**Comment by hariombalhara** [comment]
Closing this issue
