### ISSUE TITLE
[CAL-3310] new workflow message template: RATING

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14117]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2dac9ea1-10bb-4a07-b2ec-2a8cc9ba757b/ddbd0c14-6d89-4333-9a43-e3cc7d3472de?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yZGFjOWVhMS0xMGJiLTRhMDctYjJlYy0yYThjYzliYTc1N2IvZGRiZDBjMTQtNmQ4OS00MzMzLTlhNDMtZTNjYzdkMzQ3MmRlIiwiaWF0IjoxNzExNDYwNTIyLCJleHAiOjE3MTE1NDY5MjJ9.o7nLstDO2g4mi9jl8x20zKaQyrkTNSg0_HgThi9RYrM)

## urls when clicking emojis and "no show" link:

rating URL when clicking the emoji: [https://app.cal.com/booking/jnr4iTYMn3THXopuTh9?rating=4](https://app.cal.com/booking/jnr4iTYMn3THXopuTh9?rating=4)

and no-show: [https://app.cal.com/booking/jnr4iTYMn3THXopuTh9?noShow=true](https://app.cal.com/booking/jnr4iTYMn3THXopuTh9?noShow=true)

## page after clicking emoji:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/86d113c6-c6e8-4ee2-b9ac-55291d3fb444/340e44ce-f3a1-4fb8-8956-0d51345c2b6c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84NmQxMTNjNi1jNmU4LTRlZTItYjlhYy01NTI5MWQzZmI0NDQvMzQwZTQ0Y2UtZjNhMS00ZmI4LTg5NTYtMGQ1MTM0NWMyYjZjIiwiaWF0IjoxNzExNDYxMTA2LCJleHAiOjE3MTE1NDc1MDZ9.69OYxs7CBMEneMAdEQ03W1umhe1R-2EcF2vAkVuZu7M)

## new columns in booking table:

* rating: number
* ratingFeedback: string
* noShowHost: boolean

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3310](https://linear.app/calcom/issue/CAL-3310/new-workflow-message-template-rating)</sub>

**Comment by PeerRich** [comment]
i wonder where the settings should be.

should this be inside workflows or inside advanced settings?

![CleanShot 2024-03-16 at 18 42 45@2x](https://github.com/calcom/cal.com/assets/8019099/458197b4-ac9d-4568-82c5-8b5f9a0c8ed8)

**Comment by PeerRich** [comment]
maybe as a pre-installed, system workflow that you cant remove? by default off, of course 

<img width="817" alt="CleanShot 2024-03-25 at 13 30 05@2x" src="https://github.com/calcom/cal.com/assets/8019099/0ca14202-a150-41cc-975f-491f1cef0c7b">

**Comment by PeerRich** [comment]
rating URL when clicking the emoji: https://app.cal.com/booking/jnr4iTYMn3THXB8HopuTh9?rating=4

and no-show: https://app.cal.com/booking/jnr4iTYMn3THXB8HopuTh9?noShow=true

**Comment by alishaz-polymath** [comment]
https://app.cal.com/booking/jnr4iTYMn3THXopuTh9?noShow=true
What to show when the user clicks on this link in the email? Do we still show the feedback form or do we show a different screen?

**Comment by PeerRich** [comment]
yeah good question. i mean no show cant really be rated right.

maybe just the headline:

"Apologies your host wasn't there. We have informed them. Would you like to <u>reschedule</u>?

**Comment by alishaz-polymath** [comment]
> yeah good question. i mean no show cant really be rated right.
> 
> maybe just the headline:
> 
> "Apologies your host wasn't there. We have informed them. Would you like to reschedule?

Sounds good. So the default behaviour here would be to submit No Show as the attendee clicks on the specific no-show link in the email, or should we require them to submit that on this page before it mutates in the DB?
