### ISSUE TITLE
[CAL-3279] Troubleshooter is showing all times as not available

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#14112]
I have an availability schedule with availability set from 8.30am - 5.30pm. The availability is correct on my public calendar, but when I open the troubleshooter it looks like I'm never available.

[CleanShot 2024-03-16 at 11.25.38.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/01f6e3c4-d1ff-48bd-a01b-31def3ba8f1b/d99fb088-b9d6-421a-b56e-1980b4c87cac)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3279](https://linear.app/calcom/issue/CAL-3279/troubleshooter-is-showing-all-times-as-not-available)</sub>

**Comment by CarinaWolli** [comment]
fixed in https://github.com/calcom/cal.com/pull/14138
