### ISSUE TITLE
Date picker on availability page

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#14122]
Reported on x: https://x.com/Qw4z1/status/1769402570164802039?s=20
"arrows in the date picker moving due to resizing based on the days in a month. 

Super annoying to have the arrows move away from the mouse cursor when I want to jump ahead 2 months."

Loom https://www.loom.com/share/7130396697074aa391c2624d03c8a4b8

**Comment by KalpChaudhary** [comment]
hello @Udit-takkar, are you working on this?

**Comment by Qw4z1** [comment]
Thanks for reporting, @Udit-takkar. Let me know if I can do anything to help. =)

**Comment by Udit-takkar** [comment]
> hello @Udit-takkar, are you working on this?

yes
