### ISSUE TITLE
Wrong availability calculation

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#14134]
### Issue Summary

Certain availability time ranges do not appear to free up the time correctly.

### Steps to Reproduce

Set your availability to be an hour long, from quarter past or quarter to.
Make an event type that's duration in 1 hour long.
Try to book in that new availability.

### Actual Results

<img width="1094" alt="SCR-20240318-tvcp" src="https://github.com/calcom/cal.com/assets/53020786/610875a3-0b64-48ed-b428-03aa993ce3bf">
<img width="1033" alt="SCR-20240318-tveb" src="https://github.com/calcom/cal.com/assets/53020786/1c2be6a1-3f01-474b-91ef-c761d75bd78f">

### Expected Results

The slot should show available, like it does with times on the hour or half hour:
<img width="523" alt="SCR-20240318-tuxl" src="https://github.com/calcom/cal.com/assets/53020786/851270cd-05a5-4ee1-ba74-a3de24ed2190">
<img width="1091" alt="SCR-20240318-tuyt" src="https://github.com/calcom/cal.com/assets/53020786/b2c0f349-c9f4-4fcb-a631-7d29e5ac4043">

### Technical details

- Multiple versions tested, happens on self-hosted and app.cal.com

### Evidence

- In steps.

**Comment by Hybes** [comment]
To add, if I set my duration to 59 minutes, it works

**Comment by Udit-takkar** [comment]
@Hybes you can change time slots intervals in event type settings

<img width="1277" alt="Screenshot 2024-03-23 at 12 05 37 AM" src="https://github.com/calcom/cal.com/assets/53316345/d3486c41-ab7c-48c5-bc7f-4dabed30736f">

**Comment by Udit-takkar** [comment]
Feel free to re open if there are any other questions
