### ISSUE TITLE
Date override time picker display issue

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#14133]
### Issue Summary

On the Availability -> Date overrides -> Add an override.
The time selectors display incorrectly

<img width="811" alt="SCR-20240318-ttiw" src="https://github.com/calcom/cal.com/assets/53020786/e1658f9c-c732-4114-80c6-4a8fb476bfbf">

### Steps to Reproduce

On the Availability -> Date overrides -> Add an override.

### Actual Results

Time shows in area that we can't see and some parts are unclickable

### Expected Results

Time shows underneath or in a different form.

**Comment by Hybes** [comment]
Oh i just saw this is the same as: #14132

**Comment by Udit-takkar** [comment]
duplicate https://github.com/calcom/cal.com/issues/14133
