### ISSUE TITLE
[CAL-3887] Incorrect time zone in confirmation email for participants

### ISSUE THREAD

**Issue by philschlo** [calcom/cal.com#14155]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If the calendar stored is an Apple calendar in iCloud, the booker will be shown an incorrect time zone in the confirmation email.

### Steps to Reproduce

1. Add Apple Calendar
2. Book an appointment
3. View the confirmation email

### Technical details

- Browser: Chrome v 122.0.6261.129
- App hosted by cal.com

### Evidence

- Has been noticed in productive use with real appointment bookings, whereby the participants were confused with regard to the confirmed time.

<sub>[CAL-3887](https://linear.app/calcom/issue/CAL-3887/incorrect-time-zone-in-confirmation-email-for-participants)</sub>

**Comment by Shaik-Sirajuddin** [comment]
I have replicated the steps above , the timezone received in email matches the events timezone.
Could you elaborate on what was expected and actually received through email.

**Comment by keithwillcode** [comment]
Closing based on @Shaik-Sirajuddin comment above. Will reopen with more details.
