### ISSUE TITLE
[CAL-3292] Ability to Hyperlink text in Checkbox on Additional Questions

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#14163]
Many times, users need a checkbox for their attendees to agree to terms and conditions. They want to add URLs that are hyperlinked, so that attendees can read and agree to these conditions. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3292](https://linear.app/calcom/issue/CAL-3292/ability-to-hyperlink-text-in-checkbox-on-additional-questions)</sub>

**Comment by ciaranha** [comment]
Also requested here https://github.com/calcom/cal.com/issues/14613
