### ISSUE TITLE
[CAL-4158] Recurring meeting creates increasing number of Zoom events

### ISSUE THREAD

**Issue by flacoste** [calcom/cal.com#14171]
### Issue Summary

Creating a recurring event creates increasing number of Zoom events as the series adance

### Steps to Reproduce

1. Create a recurring event for 4 meetings with Zoom meeting.

![Screen Shot 2024-03-21 at 11 06 10 ](https://github.com/calcom/cal.com/assets/1485683/2d90fda0-4cf2-49e3-9c43-7928fc3d89d8)

![Screen Shot 2024-03-21 at 11 06 53 ](https://github.com/calcom/cal.com/assets/1485683/6472e818-df07-4f4f-a5fc-581eb38dd9db)

### Actual Results

- In the Zoom app, you'll see one Zoom meeting on the first event, two on the second, three on the third, etc.

![Screen Shot 2024-03-21 at 11 07 13 ](https://github.com/calcom/cal.com/assets/1485683/a05dd908-42dc-4f11-9252-f683643c95b5)
![Screen Shot 2024-03-21 at 11 07 20 ](https://github.com/calcom/cal.com/assets/1485683/e995e38a-447f-4e87-a8a3-23537bca3660)
![Screen Shot 2024-03-21 at 11 07 38 ](https://github.com/calcom/cal.com/assets/1485683/9343aae7-3844-4797-91aa-bff195b32e5a)
![Screen Shot 2024-03-21 at 11 07 55 ](https://github.com/calcom/cal.com/assets/1485683/94905143-639a-4d43-95d0-8ee61969ab39)

### Expected Results

- Only one Zoom event created on each day (or even better a recurring meeting - but a single meeting per event would be just fine).

<sub>[CAL-4158](https://linear.app/calcom/issue/CAL-4158/recurring-meeting-creates-increasing-number-of-zoom-events)</sub>

**Comment by Franz1241** [comment]
Same issue here.
If it helps this is what I did to solve it: I set up a small server to listen for Calcom webhooks for BOOKING_CREATED events. It checks for a recurringEvent key in the payload. If it finds one, it uses the Zoom API to change the meeting type from recurring to regular using the videoCallData.id in the payload as well

**Comment by SteveKekacs** [comment]
Have been experiencing the same issue, and many of our users use zoom's calendar to manage their weeks and this is making it almost unusable.

Not only does it add a ton of clutter to the calendar (see pic), they don't know which one to click on/the one with the zoom link that was sent to the attendee.

<img width="128" alt="Screenshot 2024-12-20 at 1 51 55 PM" src="https://github.com/user-attachments/assets/4b7838e9-fa53-45f3-97ea-700ae2030d17" />
