### ISSUE TITLE
Cancelling a booking doesn't remove the Zoom event

### ISSUE THREAD

**Issue by flacoste** [calcom/cal.com#14172]
### Issue Summary

Cancelling a booking doesn't remove the Zoom event

### Steps to Reproduce

1. Create a booking.

![Screen Shot 2024-03-21 at 11 25 24 ](https://github.com/calcom/cal.com/assets/1485683/9288da93-21f3-4369-8a9f-af972ba0072f)
![Screen Shot 2024-03-21 at 11 25 29 ](https://github.com/calcom/cal.com/assets/1485683/373d4daa-1871-4723-acde-1b77afb43d14)

3. Cancel the booking.
![Screen Shot 2024-03-21 at 11 26 12 ](https://github.com/calcom/cal.com/assets/1485683/ed45c4ee-730d-47e3-9fe6-af3a5ab39389)
![Screen Shot 2024-03-21 at 11 26 21 ](https://github.com/calcom/cal.com/assets/1485683/9ceaa307-9d3d-4665-b584-0885f356592b)

### Actual Results

- The Zoom meeting stays created after the cancellation.
![Screen Shot 2024-03-21 at 11 26 33 ](https://github.com/calcom/cal.com/assets/1485683/f7e9eaaa-1b18-4229-ab15-99fd41c35025)

### Expected Results

- The Zoom meeting should have been deleted.

**Comment by Shaik-Sirajuddin** [comment]
@flacoste  If you using self hosting , make sure to check the scope meeting:delete:meeting , 
after doing consider removing Zoom as your conferencing app and reinstalling it for your account.
It might help to update the scope details in the README for clarity. @ciaranha ?

**Comment by flacoste** [comment]
This on the cal.com hosted version.

**Comment by flacoste** [comment]
Although that seems to be working now on cal.com. So can be closed I guess.
