### ISSUE TITLE
[CAL-3303] ability to assign people to round robin from org members

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14190]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/333ad4eb-013e-401d-a2ba-801bf7cd53e7/ede6c7ad-bb99-4e11-828d-2b2266a47b4a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMzNhZDRlYi0wMTNlLTQwMWQtYTJiYS04MDFiZjdjZDUzZTcvZWRlNmM3YWQtYmI5OS00ZTExLTgyOGQtMmIyMjY2YTQ3YjRhIiwiaWF0IjoxNzEyODI5MzkzLCJleHAiOjE3MTI5MTU3OTN9.nStvG6TP84I6LH0DLklT6RkULws_c_4cA37FONOznow)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3303](https://linear.app/calcom/issue/CAL-3303/ability-to-assign-people-to-round-robin-from-org-members)</sub>

**Comment by Amit91848** [comment]
When we select a member, should only member's team's round robin events be shown? It would be an issue when multiple members from different teams are selected.
If not and we can assign them to other teams events, we would also have to invite them to that team right?
@PeerRich
