### ISSUE TITLE
[CAL-3459] Wrong calendar displayed in Out of Office page in Firefox

### ISSUE THREAD

**Issue by avinal** [calcom/cal.com#14197]
### Issue Summary

The Calendar displayed on the Out-of-Office page is wrong. There are **no dates in the Sunday column**. Thus causing all other dates to fall on the wrong days.

### Steps to Reproduce

1. Go to Settings -> Out of Office
2. Click on dates
3. he calendar has no dates under Sundays

### Actual Results

* The calendar is showing no dates under Sunday and thus all other dates have wrong days

For example, today is 24th March, Sunday, the calendar is showing Thursday, please refer to the attached screenshot

### Expected Results

* The calendar should show correct dates with days.

### Technical details

* Browser version: **Mozilla Firefox 124.0**

### Evidence

* How was this tested? This is quite mandatory in terms of bugs.

![2024-03-24T19:47:40,689214615+05:30](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d780f904-194c-4ae5-8e73-ed557669c35a/2fc1a820-583b-4a80-98ed-82c2d890ddde?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kNzgwZjkwNC0xOTRjLTRhZTUtOGU3My1lZDU1NzY2OWMzNWEvMmZjMWE4MjAtNTgzYi00YTgwLTk4ZWQtODJjMmQ4OTBkZGRlIiwiaWF0IjoxNzEzMjQ4MDk4LCJleHAiOjE3MTMzMzQ0OTh9.\_wWQjtizq0YlY0HZt_EVtzDzAvIRu5V8nEVfp6C_91E)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3459](https://linear.app/calcom/issue/CAL-3459/wrong-calendar-displayed-in-out-of-office-page-in-firefox)</sub>

**Comment by lokeshkumar0001** [comment]
Is this problem still pertinent? I attempted to replicate it but was unsuccessful. Could you provide additional context?

**Comment by alannnc** [comment]
The team is aware about this issue, but I was unable to reproduce it. Thank you for creating the issue for following up.

**Comment by avinal** [comment]
Hey @lokeshkumar0001 @alannnc , thank you for the response, I will try to put more context that may help resolve this issue.

**Comment by avinal** [comment]
I did some more troubleshooting. It seems like a Firefox problem. I tried reproducing on Chromium and Floorp (FireFox Like) but did not get the same issue. Also I do not see any error messages/log in the console. Please let me know what I can do to help you recognize the issue.
