### ISSUE TITLE
[CAL-3461] Stop same day bookings

### ISSUE THREAD

**Issue by mxstbr** [calcom/cal.com#14204]
### Is your proposal related to a problem?

Yes. I want people to able to book meetings from the next day, but not for today. The current "Minimum notice" setting doesn't allow me to limit it to "1 calendar day."

### Describe the solution you'd like

First option: new "Prevent same-day bookings" option that just prevents same day bookings.

Second option: add "calendar days" to "Minimum notice" setting. Saying "1 calendar day" would prevent bookings for the same day, but allow bookings for the next day.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

Setting "minimum notice" to "1 day" just does the same as "24 hours," which isn't what I want.

### Requirement/Document

N/A

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3461](https://linear.app/calcom/issue/CAL-3461/stop-same-day-bookings)</sub>

**Comment by marcinczenko** [comment]
+1 Thuis is indeed very useful to have.
