### ISSUE TITLE
[CAL-3312] Phone icon missing

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#14210]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/424155cd-f8af-4b98-9dfd-2b15c2e8f3f6/0bc9ce4b-a106-43f6-baaa-9213d03bcf19?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80MjQxNTVjZC1mOGFmLTRiOTgtOWRmZC0yYjE1YzJlOGYzZjYvMGJjOWNlNGItYTEwNi00M2Y2LWJhYWEtOTIxM2QwM2JjZjE5IiwiaWF0IjoxNzE0MzMwNTU3LCJleHAiOjE3MTQ0MTY5NTd9.F1tY2prz3kAnT4MFaIVEzeyXY5U5ddehZHJiMSo0LZk)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3312](https://linear.app/calcom/issue/CAL-3312/phone-icon-missing)</sub>

**Comment by ninadvyas** [comment]
Hello can I work on this issue?

**Comment by AbhishekGurav** [comment]
@baileypumfleet That image link seems broken, could you re-upload it if the issue still persists?

**Comment by CarinaWolli** [comment]
![Screenshot 2024-09-24 at 11 13 41 AM](https://github.com/user-attachments/assets/e1bff691-b3da-44d2-84d4-2726ffb028ae)
