### ISSUE TITLE
Embedded Cal Widget Cal Link Broken

### ISSUE THREAD

**Issue by mattburrell** [calcom/cal.com#14221]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Is your embedded Cal widget broken? The url is currently showing as undefined in the iframe.

### Steps to Reproduce

Follow instructions for embedding Cal as a React component
Inspect iframe url (cal link)
`<iframe class="cal-embed" name="cal-embed=" src="https://undefined/team/<your team>/<event type id>/embed... etc></iframe>`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by PeerRich** [comment]
you seem to be not generating the URL correctly. can you share your entire code?
