### ISSUE TITLE
[CAL-3315] redirect after booking: option to forward parameters

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14223]
right now by default we always forward parameters. lets give people the option to make it optional (opt-out).

by default this should be on:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/51578e96-1681-440d-a606-c776846f0e58/e5d7a249-1d7b-479f-afae-b57d563c4a95?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81MTU3OGU5Ni0xNjgxLTQ0MGQtYTYwNi1jNzc2ODQ2ZjBlNTgvZTVkN2EyNDktMWQ3Yi00NzlmLWFmYWUtYjU3ZDU2M2M0YTk1IiwiaWF0IjoxNzExNTM0NDEwLCJleHAiOjE3MTE2MjA4MTB9.gaJTQ9b-nzXpIIWZNlW_f4BFiVV93MuX4NniWn0_eCs)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3315](https://linear.app/calcom/issue/CAL-3315/redirect-after-booking-option-to-forward-parameters)</sub>

**Comment by piyush-panpaliya** [comment]
Hey I would like to work on it

**Comment by roopa-macm** [comment]
can i do it, i am looking to start my OS journey with it

**Comment by giteshsarvaiya** [comment]
Hello @PeerRich , can you pls attach the link of the image. Coz it is not loading
