### ISSUE TITLE
Can't Schedule Tomorrow

### ISSUE THREAD

**Issue by johnaweiss** [calcom/cal.com#14241]
### Is your proposal related to a problem?

Cal.com won't allow me to schedule appointment tomorrow, only the day after tomorrow. 
How to allow appointments tomorrow?

### Describe the solution you'd like

Enable tomorrow in booking tool

**Comment by jainakshitagithub** [comment]
Could you please give some example of the problem you are facing , because when i am scheduling event for tomorrow the event has scheduled without giving any warnings.

**Comment by ciaranha** [comment]
@johnaweiss can you check you don't have any limits set on your event type?
![image](https://github.com/calcom/cal.com/assets/4536123/66f22da1-3ead-4356-bb8a-ac64d2f90983)

**Comment by ciaranha** [comment]
I'm going to close this as I can't recreate and can't pass on steps to recreate for our enginneers. Please reach out to support using the chat button in the bottom right of the app when logged in to get help for your specific account if my previous suggestion didn't work.

**Comment by johnaweiss** [comment]
solved, it was the Limits. Thx!
