### ISSUE TITLE
[CAL-3477] User can't see their event types: "Something went wrong" 

### ISSUE THREAD

**Issue by jordankrueger** [calcom/cal.com#14258]
### Issue Summary

User receives an error when clicking on their Event Types menu option:

> Something went wrong \[Details\]
> TypeError: Cannot read properties of undefined (reading 'slug')

### Expected Results

Should show list of event types – which flash very briefly before we get the error – like other users.

### Technical details

* Chrome
* Mac

### Evidence

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4cfbb693-56f2-4eac-bd11-f4e3df50e3a0/2fe958a0-06eb-42c3-b9b4-0d7634f798bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80Y2ZiYjY5My01NmYyLTRlYWMtYmQxMS1mNGUzZGY1MGUzYTAvMmZlOTU4YTAtMDZlYi00MmMzLWI5YjQtMGQ3NjM0Zjc5OGJiIiwiaWF0IjoxNzEzMjcwODgyLCJleHAiOjE3MTMzNTcyODJ9.AflWgOMgF5jyr9oqzeEfruHnx529l2xTDYPQYdxmLYw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3477](https://linear.app/calcom/issue/CAL-3477/user-cant-see-their-event-types-something-went-wrong)</sub>

**Comment by prithvi009** [comment]
Hi @jordankrueger, can you provide more details on how to produce the issue because my event types menu is working fine?

**Comment by jordankrueger** [comment]
@prithvi009 This person simply selects the Event Types option, the event types "flash" on the screen before this error in the screenshot appears. 

What else would be helpful to clarify? Happy to provide any information as requested.

**Comment by CarinaWolli** [comment]
Hey @jordankrueger, if this is on cal.com (and not self-hosted) could you send your username to support@cal.com with a link to this issue?
