### ISSUE TITLE
Embeds breaking with framing issue

### ISSUE THREAD

**Issue by mreilly-lula** [calcom/cal.com#14254]
### Issue Summary
Routing form embeds are working normally, but when they route a user to an event type it breaks. 

```Refused to frame 'https://cal.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.datocms.com https://datocms.com".```

<img width="395" alt="Screenshot 2024-03-28 at 10 01 50 AM" src="https://github.com/calcom/cal.com/assets/57537896/b019a39e-cb6c-47de-af2f-5354d024c297">

### Steps to Reproduce

1. Click on an embed
2. Observe the bug

### Technical details

Happening on Chrome and Safari

**Comment by mreilly-lula** [comment]
https://codesandbox.io/p/sandbox/popup-on-click-of-an-existing-element-framework-agnostic-forked-6n4cfs?file=%2Findex.html%3A41%2C9

Codesandbox example

**Comment by milospuac** [comment]
@hariombalhara can you have a look?

**Comment by alexeybondarenko** [comment]
We are also affected by this.

**Comment by matthewjewell** [comment]
+1, came here to report this too.

**Comment by hariombalhara** [comment]
Seems to be working for me here https://codesandbox.io/p/sandbox/cal-component-embed-inline-demo-react-typescript-forked-2xd6tl

Demo Loom - https://www.loom.com/share/1f86069c503a44fb84c030a1f7bb40be

The sandbox linked shared above isn't accessible to me(maybe it isn't marked public).

**Comment by hariombalhara** [comment]
Also as per Perplexity and I agree, I think the problem is that the website you are embedding it in is restricting cal.com to be iframed and the website needs to change the header.

https://www.perplexity.ai/search/Refused-to-frame-qUU12DOVToyog2vRFXVaQw#0

**Comment by ciaranha** [comment]
We have resolved this issue
