### ISSUE TITLE
[CAL-3330] bad UX at end of month

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14260]
![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0fe4c5b9-86bd-489f-8059-c07cd3dbced8/88063f8d-1146-40fb-80ee-803b6c4c2865?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wZmU0YzViOS04NmJkLTQ4OWYtODA1OS1jMDdjZDNkYmNlZDgvODgwNjNmOGQtMTE0Ni00MGZiLTgwZWUtODAzYjZjNGMyODY1IiwiaWF0IjoxNzExNjU4MjA2LCJleHAiOjE3MTE3NDQ2MDZ9.TUEwDGpPmBpl4qI9VPgiXS-quWWokKaBCQnXTgNceJU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3330](https://linear.app/calcom/issue/CAL-3330/bad-ux-at-end-of-month)</sub>

**Comment by PeerRich** [comment]
https://x.com/martymadrid/status/1773440003512672612?s=46

**Comment by ASQUAREEE** [comment]
I just fixed the issue. If it's the last day of the month, then simply move to the next month

If you need any further changes, please let me know.

**Comment by CarinaWolli** [comment]
> I just fixed the issue. If it's the last day of the month, then simply move to the next month and don't display the NoAvailabilityOverlay

@PeerRich @ciaranha wouldn't it be better to always show the month that has the first available slots?

**Comment by ciaranha** [comment]
> > I just fixed the issue. If it's the last day of the month, then simply move to the next month and don't display the NoAvailabilityOverlay
> 
> @PeerRich @ciaranha wouldn't it be better to always show the month that has the first available slots?

Yea myself and Sean discussed this recently and have planned for him to do exactly that (he'll pick it up next milestone).
