### ISSUE TITLE
[CAL-3333] Webhook not listed in the webhooks, yet it's still active

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14265]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3333](https://linear.app/calcom/issue/CAL-3333/webhook-not-listed-in-the-webhooks-yet-its-still-active)</sub>

**Comment by advmt** [comment]
Hey this is an issue I'm having. I created a webhook months ago. The webhook triggered an automation to notify me in Slack when a new calendar event is created.

When I logged in recently to check, the webhook was gone, so I thought there must have been some changes to the webhook infrastructure and it got deleted. So I made another webhook that was identical to the one I had before.

But when I tested the new webhook by booking a call on my calendar, I got two identical Slack messages, indicating that the old webhook is still active somewhere, but not showing up in the actual UI.

**Comment by advmt** [comment]
bumping

**Comment by CarinaWolli** [comment]
Hi @advmt is this still an issue? I think you are maybe mixing up event-type specific webhooks and global webhooks. 

Global webhooks are listed here: https://app.cal.com/settings/developer/webhooks
- They trigger for all your event types 

Event type specific webhooks are listed here: https://app.cal.com/event-types/[id]?tabName=webhooks
- They only trigger for this specific event type

**Comment by keithwillcode** [comment]
Closing until we have confirmation this is an issue.
