### ISSUE TITLE
Build failing with Vercel

### ISSUE THREAD

**Issue by mayankjhaCA** [calcom/cal.com#14267]
Build keeps on failing when deploying with Vercel. I've followed the instructions available [in this guide to launch.](https://cal.com/docs/introduction/quick-start/self-hosting/vercel#getting-started)

I even tried modifying by using the suggested install command 

`@calcom/embed-react:build: src/index.ts (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.
@calcom/embed-react:build: src/index.ts (1:0) Module level directives cause errors when bundled, "use client" in "src/index.ts" was ignored.
@calcom/embed-react:build: src/Cal.tsx (1:0)
Error when using sourcemap for reporting an error: Can't resolve original location of error.
@calcom/embed-react:build: src/Cal.tsx (1:0) Module level directives cause errors when bundled, "use client" in "src/Cal.tsx" was ignored.
@calcom/embed-react:build: src/useEmbed.ts (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.`

`@calcom/web:build: Error: Invalid rewrite found
@calcom/web:build: ERROR: command finished with error: command (/vercel/path0/apps/web) yarn run build exited (1)
command (/vercel/path0/apps/web) yarn run build exited (1)`

<img width="1115" alt="Screenshot 2024-03-29 at 6 04 44 PM" src="https://github.com/calcom/cal.com/assets/36353432/e955f0b0-71c8-4bba-a11f-3881045bc9c6">
<img width="1192" alt="Screenshot 2024-03-29 at 6 04 53 PM" src="https://github.com/calcom/cal.com/assets/36353432/02ec6d7f-7214-49d2-a861-8302b605db84">

**Comment by Pils10** [comment]
How did you solve this error? Got the same one. Help would be greatly appreciated.

**Comment by Bananenbrot1** [comment]
I´m getting the same error, any solutions how to fix it?

**Comment by Bananenbrot1** [comment]
For everyone who is looking for a solution. There is a new env variable called `NEXT_PUBLIC_API_V2_URL`. If this is not set, the error above is shown.
