### ISSUE TITLE
Spelling mistake in cal.com/ai

### ISSUE THREAD

**Issue by prane-eth** [calcom/cal.com#14279]
"One on on with" is mentioned instead of "One-on-**one**"

https://cal.com/ai

![image](https://github.com/calcom/cal.com/assets/48318416/f20ab2c1-225e-4f3a-9bbc-30dd1f748019)

**Comment by prane-eth** [comment]
@anjana-psvel, there is no option to assign for cal.com. You should comment here before you start to work.
Then you should create a pull request by tagging the issue, and comment back here by tagging the pull request.

**Comment by prane-eth** [comment]
Please note that the part with wrong spelling is an image but not text.

**Comment by iamRajatSharma** [comment]
> Author

how you know that it is image or text.

**Comment by anjana-psvel** [comment]
Yes, I noticed that the typo is in the svg file. I tried changing it. Can you check if it's fine?
![One-on-one with Sally](https://github.com/calcom/cal.com/assets/97551556/39de015d-eff9-4378-ab86-c6f25519de0e)

**Comment by prane-eth** [comment]
@anjana-psvel It looks fine.
Can you please mention how you did that, here and in pull request?

**Comment by anjana-psvel** [comment]
I edited the svg file using Canva. I am currently trying to find the original svg file so that I can replace this with the new one.

**Comment by anjana-psvel** [comment]
Am i missing something here or can i go ahead?

**Comment by prane-eth** [comment]
@anjana-psvel You can create a pull request and tag that here.
Also tag the issue when creating pull request.

**Comment by anjana-psvel** [comment]
where can i find the code for website? tried searching, i couldn't find it

**Comment by prane-eth** [comment]
Here is the link to "apps/ai" folder.
https://github.com/calcom/cal.com/tree/main/apps/ai

**Comment by PeerRich** [comment]
the website is not open source. we are also changing this website right now. thank you for fixing tho!
