### ISSUE TITLE
Public booking page is inconsistent with available timings

### ISSUE THREAD

**Issue by ArvindhMangoleap** [calcom/cal.com#1427]
Found a bug? Please fill out the sections below. 👍

### Availability on public page is inconsistent with available timings

My Availability page time starts at 9am ends at 8pm for all day.

![72fe76c3-7a3a-4836-8698-08f024c52f8a](https://user-images.githubusercontent.com/72745366/148494309-17b3c9c8-df72-4492-953a-dc5276ac7f86.jpg)

My public booking page today. (6th) -  data is correct
![e5bc2ac4-d93d-469b-b1cd-442926a236f8](https://user-images.githubusercontent.com/72745366/148494506-df1bb4ae-004a-4cfa-a727-3a20b5a9c5c2.jpg)

My public booking page tomorrow. (7th) -  data is **incorrect**
![c4130c52-d15d-4ecc-a1b4-edb32fd3f997](https://user-images.githubusercontent.com/72745366/148494542-fea6ba0f-ae70-4805-8912-169cc2c2a23c.jpg)

My public booking page day after tomorrow (8th) - data is correct
![f87fd7e3-9823-4b6a-b433-e9118079e454](https://user-images.githubusercontent.com/72745366/148494902-95abc9bc-cbe5-4ba8-8790-efb8f306f205.jpg)

**Every day after 8th is correct. But always the data is incorrect for day after tomorrow.**

**Comment by ConnorGargano** [comment]
Hi @ArvindhMangoleap 
Can you please make sure you have no availability set directly in your event type advanced settings.
https://app.cal.com/event-types

**Comment by ArvindhMangoleap** [comment]
Hi @ConnorGargano 
This is how my event page advanced settings looks
![image](https://user-images.githubusercontent.com/72745366/148530617-5c331051-2b7d-4690-a26a-b03b5c288c70.png)

**Comment by manjufy** [comment]
I have the similar issue.
This is my observation so far.

- There is no availability set in event type
- There is also no availability set at the global level (i.e Availability) 

So its availability is defaulted.
The slots are actually incorrect for the first first day, however, it works for the following days.

![Screenshot 2022-01-10 at 12 55 04 AM](https://user-images.githubusercontent.com/5035624/148692394-1c48510c-61b2-42b3-af2e-05cbe2b97163.png)
![Screenshot 2022-01-10 at 12 58 23 AM](https://user-images.githubusercontent.com/5035624/148692401-2ec44155-89a1-47cd-bf17-be17322e7ca4.png)

I have been debugging this issue for 3-4 days now, could not get the the bottom of the problem

**Comment by manjufy** [comment]
My guess is that, the following date is being utsOffset twice. i.e. I'm in GMT+8,
following date being offset +8 + GTM+8 => Following day always starts with 04:00PM

**Comment by emrysal** [comment]
#1488 is now merged

**Comment by emrysal** [comment]
Closed as completed.
