### ISSUE TITLE
ability to schedule timezone changes

### ISSUE THREAD

**Issue by davidawad** [calcom/cal.com#14281]
### Is your proposal related to a problem?

Let's suppose I always work 9-5 in whatever time zone I'm in. 

If I travel from NYC to DXB, I will be working during the same hours (9AM-5PM), but often my scheduling tool thinks I'm still in NYC time; that means I'll end up with calls scheduled at 2AM Dubai time.

Savvycal has the ability to schedule time zone changes so that all my calls are during working hours of the time zone I've scheduled for those dates.

As far as I know, there is no way to do a similar thing in cal. 

### Describe the solution you'd like

A user interface for scheduling timezone changes (e.g. I'll be in DXB from date A to date B)

You select a range of dates, then select a time zone associated with those dates. 

### Describe alternatives you've considered

I do not know that there are viable alternatives here. it's entirely within the domain of the scheduling tool.

**Comment by Bnilesh0210** [comment]
Hey,
       While it's not ideal, you might need to manually adjust your schedule when traveling to different time zones until a feature like this is implemented. This could involve blocking off time in your calendar for travel or adjusting appointments manually.

**Comment by PeerRich** [comment]
i think this is something that goes live very soon cc @CarinaWolli
