### ISSUE TITLE
Unable to signup into calendso

### ISSUE THREAD

**Issue by joshuakp** [calcom/cal.com#1428]
### Issue Summary

Unable to signup into calendso, while running via docker

### Steps to Reproduce

1. Run docker-compose to launch calendso
2. http://localhost:3000/signup fails to render with the following error
3. 404 ERROR

This page does not exist.
The username localhost/signup is still available.

### Technical details

- docker-compose, calendso:latest

**Comment by delucca** [comment]
Same issue here

**Comment by milospuac** [comment]
Thanks for reporting this. Our team will address this.

**Comment by pdepip** [comment]
any updates on this?

**Comment by ilhamakbarki** [comment]
same error, can fast to fix it ?

**Comment by Jenietoc** [comment]
Hello everyone, I'm going to take a look at this issue

**Comment by PeerRich** [comment]
hey everyone. We need to clarify that account creation is not included in the open core, yet.

**Comment by PeerRich** [comment]
more context: https://github.com/calcom/cal.com/pull/1734
