### ISSUE TITLE
[CAL-3340] Platform Onboarding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14294]
we need a link that looks like this:

[https://app.cal.com/signup?redirect=https://app.cal.com/settings/platform/new](https://app.cal.com/signup?redirect=https://app.cal.com/settings/teams/new)

that handles all of the platform onboarding, payments and key creation for Cal.com Atoms

<sub>[CAL-3340](https://linear.app/calcom/issue/CAL-3340/platform-onboarding)</sub>

**Comment by adityayaduvanshi** [comment]
Can you please assign this to me?
