### ISSUE TITLE
[CAL-3738] Feat: Fix Proton Calendar with ICS

### ISSUE THREAD

**Issue by colans** [calcom/cal.com#14300]
### Is your proposal related to a problem?

Yes.  Currently, it's not possible to use cal.com with [Proton Calendar](https://proton.me/calendar).  See https://github.com/calcom/cal.com/issues/5756 for background on why integration isn't possible.

### Describe the solution you'd like

Just sending the usual iCal email message to all parties after booking, but don't write to the calendar. Proton users can then access their account, look at the message, and then hit the "Add to calendar" button. It's an extra step, but makes the system usable without requiring write access.  This has the added benefit of integrating with other calendar services that can't be written to via API.

Availability can be handled by https://github.com/calcom/cal.com/issues/3167 so no need to worry about that here.

All that would be required in user accounts is an option to not write to any calendar, which seems like a minimal amount of work.

### Describe alternatives you've considered

Somehow get access to Proton Calendar, but those folks have said that they have no plans to support this.

### Additional context

* https://github.com/calcom/cal.com/issues/5756
* https://github.com/calcom/cal.com/issues/3167

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3738](https://linear.app/calcom/issue/CAL-3738/send-ical-email-message-to-all-parties-on-booking-without-writing-to)</sub>

**Comment by warengonzaga** [comment]
Amazing, looking forward on this. In the meantime I'm gonna use outlook as my calendar for writing booking and then fecth the ICS feed back to Proton Calendar.

Kinda like this.

Proton Calendar -> Cal -> Outlook -> Proton Calendar

**Comment by warengonzaga** [comment]
I just discovered that if you have a confirmation enabled for the booking the booking from the scheduler will go through as normal. However, when you confirm the booking from your end, you'll see the error message about writing an error to the ICS. If we can let the cal send the invitation to the host email which is a proton mail user then that would work. Basically upon confirmation, the event type will not try to write to the ICS feed instead it should send the ICS invitation to the host and the scheduler separately. So that the proton mail user or the host can accept it from the proton calendar.

I think that should work, right now the workaround is to use Google Calendar or Outlook as your writing schedule just to make things work.

**Comment by PeerRich** [comment]
urgently prioritizing proton calendar now. unfortunately they dont have a good API so we kinda have to rely on a wonky ICS feed integration that is quiet unstable (ICS sucks)

**Comment by PeerRich** [comment]
/bounty 50 -- make proton calendar work

**Comment by rahullli** [comment]
Hey @PeerRich can you pls help me in understanding what is ICS all about and where to start. It would be helpful .

**Comment by AdityaSingh-02** [comment]
heyy @PeerRich, @colans, @warengonzaga ,
I am facing problems, I am sharing a notion page with all listed problems, I would like you to have a look.
I don't think so proton calendar integration is possible


https://efficacious-wanderer-833.notion.site/problems-with-proton-integration-46cfc3bde4ae4f1180b4b13281429ed8

**Comment by warengonzaga** [comment]
Hey @AdityaSingh-02 I read your notion and I think that will make the integration more complicated.

> I just discovered that if you have a confirmation enabled for the booking the booking from the scheduler will go through as normal. However, when you confirm the booking from your end, you'll see the error message about writing an error to the ICS. If we can let the cal send the invitation to the host email which is a proton mail user then that would work. Basically upon confirmation, the event type will not try to write to the ICS feed instead it should send the ICS invitation to the host and the scheduler separately. So that the proton mail user or the host can accept it from the proton calendar.
>
> I think that should work. Right now, the workaround is to use Google Calendar or Outlook as your writing schedule just to make things work.

Here's my finding: the ICS integration should work similarly. The only difference is that don't initiate the write function to the calendar; otherwise, it will cause trouble, like throwing an error message. Instead, we can just send the message to the Proton Mail because it can recognize ICS, which we can respond to.

**Comment by warengonzaga** [comment]
If we can modify the existing ICS integration to have the option to disable the execute write function. OR make another integration which is pretty similar to ICS just modify that part I think that helps.

**Comment by AdityaSingh-02** [comment]
That is cool I just tried creating a new event and added my proton mail, When I booked a event [here](https://cal.com/aditya-op/proton), it automatically got added to my proton calendar and also received a mail with 2 different .ics files

<img width="1460" alt="Screenshot 2024-05-23 at 12 08 47 PM" src="https://github.com/calcom/cal.com/assets/94185167/56eec03c-88a0-4701-bcff-c30158d0a5b7">

no need to do any extra step(if you enter proton mail during event booking)

For now we just need to add the ICS for getting their schedules with no write access.

<img width="1164" alt="Screenshot 2024-05-23 at 3 55 35 PM" src="https://github.com/calcom/cal.com/assets/94185167/92c295f2-3f29-44b1-a807-8091283b1644">

Here users can go to their profile setting and add their proton mail and get verified easily
and when someone schedules appointment it automatically gets added to proton calendar

This makes Proton integration Quite Easy as we just need their ICS without write access

**Comment by AdityaSingh-02** [comment]
heyy @warengonzaga What should I do? build a new Proton app or just modify the existing ICS feed app?

**Comment by colans** [comment]
I finally tried the ICS feeds, and I seem to get these ghost events that block entire days at a time.  They:
* aren't in the original calendar,
* don't show up when Thunderbird subscribes to them, and
* don't show up on Android with Samsung Calendar (via [ICSx<sup>5</sup>](https://f-droid.org/packages/at.bitfire.icsdroid/))

Here's what they look like in the troubleshooter.  On the left is the ghost event (they all do the "00:00-00:00" thing), and on the right (where it says nothing) is a real all-day event:

![Ghost events blocking](https://github.com/calcom/cal.com/assets/1258265/edb6a2e6-5160-4111-a554-60fd9fd17217)

So what's going on here?  Are these actually in the feed, and other subscribers are ignoring them, or are they somehow being inserted after they get here?

Thanks for all of your support on this.

**Comment by milospuac** [comment]
@PeerRich @keithwillcode who can investigate this one? Proton has been a headache for a while now

**Comment by warengonzaga** [comment]
> heyy @warengonzaga What should I do? build a new Proton app or just modify the existing ICS feed app?

Modifying the ICS feed or building a new app specifically for proton would work for me if you ask me.

**Comment by warengonzaga** [comment]
Let's build another app specifically for Proton integration based on the ICS feed app. I tried to do the ideal setup with ICS Feed for Proton, but we should remove the following function. 👇
![image](https://github.com/calcom/cal.com/assets/15052701/847642d1-88ff-4803-b92b-8b532e752388)

With Proton Mail, we don't need to write something to calendar. The integration should only send the invitation to the proton mail address, and from the calendar, we'll receive the invitation to accept it or not.

With the current setup with ICS, when someone book the event will try to write the event to ICS feed and ending it will throw an error but we'll receive the email invitation from our calendar which annoying to see it goes through but actually not from dashboard.

I think that's only my suggestion, if we are able to remove the function in the image that would fix the issue with Proton Mail.
