### ISSUE TITLE
[CAL-3352] SMS Workflow Not Triggering

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#14302]
SMS Workflow not Triggering on Event-Types 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3352](https://linear.app/calcom/issue/CAL-3352/sms-workflow-not-triggering)</sub>

**Comment by CarinaWolli** [comment]
we need more information here, normal SMS to specific number when new booking is made works

**Comment by shirazdole** [comment]
This problem is no longer occurring I believe
