### ISSUE TITLE
Unable to create books in Outlook

### ISSUE THREAD

**Issue by kelvinalfaro** [calcom/cal.com#1431]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to create event. Even shows successfully created in Bookings, but is not able to create it in the actual connected outlook calendar. 
![image](https://user-images.githubusercontent.com/1563599/148597620-4e54ad13-1d50-450f-83e8-8e427b0809aa.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
Self-hosted on Railway.app

**Comment by milospuac** [comment]
Thanks for the input, our engineering team will look into this

**Comment by OITDE** [comment]
Hi!
weve got the same error. Created the App in Azure twice. Reading the Calendar for free times is working.
Regards, Ingo

**Comment by PeerRich** [comment]
i think this has been fixed. can you try again with the latest version?
