### ISSUE TITLE
`destination` does not start with `/`, `http://`, or `https://` for route

### ISSUE THREAD

**Issue by olivierlambert** [calcom/cal.com#14310]
### Issue Summary

Updating from v3.8.5 to v3.9.4 leads to an error during `yarn build`

### Steps to Reproduce

1. git checkout on v3.9.4
2. yarn
3. yarn build

### Actual Results

```
@calcom/web:build: cache miss, executing c8414372ccbf40f0
@calcom/web:build: Duplicate value found in common.json keys:   seats_available_other and seats_available_one
@calcom/web:build: Duplicate value found in common.json keys:   location_variable and location
@calcom/web:build: Duplicate value found in common.json keys:   additional_notes_variable and additional_notes
@calcom/web:build: Duplicate value found in common.json keys:   already_have_account and already_have_an_account
@calcom/web:build: Duplicate value found in common.json keys:   timezone_variable and timezone
@calcom/web:build: Duplicate value found in common.json keys:   scheduling_for_your_team and workflow_automation
@calcom/web:build: Duplicate value found in common.json keys:   saml_sso and saml_config
@calcom/web:build: Duplicate value found in common.json keys:   advanced_managed_events_description and unified_billing_description
@calcom/web:build: `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v2/:path*","destination":"undefined/:path*"}
@calcom/web:build: 
@calcom/web:build: 
@calcom/web:build: Error: Invalid rewrite found
@calcom/web:build: ERROR: command finished with error: command (/data/cal/apps/web) yarn run build exited (1)
command (/data/cal/apps/web) yarn run build exited (1)

 Tasks:    6 successful, 7 total
Cached:    2 cached, 7 total
  Time:    18.504s 
Failed:    @calcom/web#build

 ERROR  run failed: command  exited (1)
```

### Expected Results

Build would work

### Technical details

- Node v18.19.0

**Comment by olivierlambert** [comment]
I didn't not change the .env file and I never had this issue before, so it might worth it to have an actual human taking a look at some point :D

I'm taking a deeper look on what I could have done wrong, but I found nothing right now.

**Comment by olivierlambert** [comment]
So it seems there's a new var in `env`, called `NEXT_PUBLIC_API_V2_URL`. I'm investigating what it should be in my self-hosted environment.

**Comment by olivierlambert** [comment]
Adding the var in `env` make it work, but I can't find a lot of documentation on what it does and if I need to use a different URL than the default one given in the `.env.example` file.

**Comment by livingmine** [comment]
> Adding the var in `env` make it work, but I can't find a lot of documentation on what it does and if I need to use a different URL than the default one given in the `.env.example` file.

@olivierlambert it's used here https://github.com/calcom/cal.com/blob/0ee81d0739cab4138e4db1daa46a4aacf5b99d4d/apps/web/next.config.js#L309 which explains why the invalid rewrite rule error is happening.

**Comment by JosephManni** [comment]
I'll take a look at this

**Comment by olivierlambert** [comment]
Understood. As long as the env file explains the new additions and what should be used (or a changelog), I am perfectly happy with it!
