### ISSUE TITLE
[CAL-3472] Improved date overrides: Interactive calendar view with manual time blocking or ability to "delete" / block slots in column view

### ISSUE THREAD

**Issue by EduNetEurope** [calcom/cal.com#14312]
It would be amazing to have a calendar view that lists all appointments and meetings across connected calendars. We would like to be able to block out times directly within this calendar view by clicking at the start time and dragging the cursor to the desired end time of the blocked time frame. This intuitive interaction would simplify the process of marking unavailable or busy times.

Alternatively, "deleting" / blocking slots in an internal version of column view would work equally well.

<sub>[CAL-3472](https://linear.app/calcom/issue/CAL-3472/improved-date-overrides-interactive-calendar-view-with-manual-time)</sub>

**Comment by ciaranha** [comment]
![CleanShot 2024-04-16 at 11 51 03@2x](https://github.com/calcom/cal.com/assets/4536123/fd1fa784-6ead-4408-9227-a77a1a456c9e)
We do have designs for features related to this so will definitely make it onto the roadmap.

**Comment by EduNetEurope** [comment]
Looks great!!!
