### ISSUE TITLE
[CAL-3357] Reorganize files inside @calcom/ui

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#14323]
We need to do some spring cleaning in `@calcom/ui` so we can enable this transform and reduce bundle sizes even further.

[https://github.com/calcom/cal.com/blob/3f02de82145e7edd5cc9f0a7338d0374923c54a8/apps/web/next.config.js#L198-L201](https://github.com/calcom/cal.com/blob/3f02de82145e7edd5cc9f0a7338d0374923c54a8/apps/web/next.config.js#L198-L201)

Right now we have components all over the place. Some are grouped as well. We need to either get them each one of them in a file or reduce the number of exports we do from from `packages/ui/index.ts`.

Basically these imports:

```ts
import {
  Avatar,
  AvatarGroup,
  UserAvatar,
  UserAvatarGroup,
  UserAvatarGroupWithOrg,
} from "@calcom/ui";
```

Should be able to be transformed into:

```ts
import { Avatar } from "@calcom/ui/components/Avatar";
import { AvatarGroup } from "@calcom/ui/components/AvatarGroup";
import { UserAvatar } from "@calcom/ui/components/UserAvatar";
import { UserAvatarGroup } from "@calcom/ui/components/UserAvatarGroup";
import { UserAvatarGroupWithOrg } from "@calcom/ui/components/UserAvatarGroupWithOrg";
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3357](https://linear.app/calcom/issue/CAL-3357/reorganize-files-inside-calcomui)</sub>

**Comment by sean-brydon** [comment]
Reached out to codemod.com to see if they can help us speed this up

**Comment by keithwillcode** [comment]
Backing this one down to medium. Definitely want to address this but it’s not at the same priority as other work at the moment.

**Comment by keithwillcode** [comment]
@sgriff96-brydon Yeah let's give it a go
