### ISSUE TITLE
"First Day of Week" Setting for "Add an Override" Calendar: Ability to Select Monday as First Day of Week

### ISSUE THREAD

**Issue by EduNetEurope** [calcom/cal.com#14334]
The "add an override" calendar view currently starts the week on Sunday, diverging from the booking page calendar, which starts on Monday. To enhance user experience consistency, could we introduce an option to set Monday as the start day for the week in the "Add an override" calendar view?

**Comment by ciaranha** [comment]
We can reflect the users preference from general settings here.

**Comment by shaik-zeeshan** [comment]
Hello, if this task has not been completed, can i take this issue?

**Comment by mf1511** [comment]
@dosu 
how to set the first week of the day on Monday in the events
