### ISSUE TITLE
[CAL-3360] bookings made via API don't include the specified location

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14341]
The bookings that have come through via API are all booking on cal video but the ones through the site directly actually use zoom as they should.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3360](https://linear.app/calcom/issue/CAL-3360/bookings-made-via-api-dont-include-the-specified-location)</sub>

**Comment by Oxygen-Labs-AI** [comment]
To be clear, this is happening whenever we create an api call to book via Air.ai.. We are running into an issue where it is booking through the api and creating the calendar appointment but when it does that the video provider is cal.com video vs the Zoom option chosen inside Cal.com

**Comment by lnvglr** [comment]
I would like to reopen this issue. I believe my issue is very similar to this one.

I create a booking through the API (`/v1/bookings`) with a phone number:
```
"location": {
  "optionValue": "phone",
  "value": "0179..."
}
```
The location is saved, but the specified phone number is nowhere to be found...
