### ISSUE TITLE
Where is the "API SUBMODULE" for Self-hosted deployment?

### ISSUE THREAD

**Issue by jjmills44** [calcom/cal.com#14346]
I have a deployed self-hosted instance, but it is Telling me I need enterprise?

The documentation mentions an API submodule... but I can't find it

Thank you!

![Screenshot 2024-04-04 132049](https://github.com/calcom/cal.com/assets/153874789/291ec7ec-3d4d-4374-b093-84103630d3e2)

![Screenshot 2024-04-04 131932](https://github.com/calcom/cal.com/assets/153874789/d6d61c34-e949-486a-ab6b-6b293d636c54)
![Screenshot 2024-04-04 131928](https://github.com/calcom/cal.com/assets/153874789/f56ef7b8-d481-4d69-8b38-c539ab9bbc83)

**Comment by PeerRich** [comment]
you can get a licesne here: https://cal.com/sales
