### ISSUE TITLE
Integrations architecture revamp

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1441]
Integrations are one of the keys to our success. There are so many platforms out there which we could integrate with, so we need to ensure that the integrations platform is as scalable, efficient and easy to use as possible.

We should do a revamp/refactor of how our integrations system works. Currently, integrations are a little messy and it may be difficult for inexperienced developers to understand how integrations work in our platform.

I think that we should use a 'hooks' based system, where for instance in a calendar integration, there are the following 'hooks' (this is an example list, it's not comprehensive):

- Get calendars
- Get events
- Create event
- Update event
- Delete event

Each integration should use these hooks in the code, and all that each integration has to do is fetch the data from the API and return the result

Here's what I mean in pseudocode:
```
function getCalendars() {
  // Get list of calendars here
  const result = googleApis.getCalendars();
  return result;
}

function getEvents() {
  // Add the code to get events here
}
```

Hence, we can have a template for calendar integrations and a template for video integrations which is a bunch of empty functions or something, where even an inexperienced developer could simply drop in the Outlook Calendar APIs for instance and link this up.

During this revamp, there should be a emphasis on a straightforward file/folder structure to make the code as easy to read as possible, a focus on making sure things are typed properly and TypeScript errors are resolved. We're also renaming integrations to apps, so the naming of files, folders and other references should be changed too.

We also should have clear documentation of everything that you need to do to develop and add an integration.

**Comment by baileypumfleet** [comment]
#1369 is merged
#1394 is in review
#1393 is in review

**Comment by baileypumfleet** [comment]
So far we have:

- Apple Calendar
- CalDAV (Calendar)
- Google (Calendar)
- Office 365 (Calendar)
- Stripe (Payments)
- Zoom (Video)

The calendar integrations should be relatively similar, in the sense that they all provide the same functionality (get calendars, create events etc), with the only differences being how we fetch the data and parse it.

I have very little knowledge of how integrations work though :)

**Comment by s-gbz** [comment]
Hey there @baileypumfleet - glad to see you guys progress so hugely!
Congrats on the 7 mil. deal! :tada: 

Quick question: There used to be a public discussion that laid out the roadmap.
Last time I checked CalDAV was broken.
Has the discussion been moved somewhere? (and is CalDAV officially safe to use?)

Keep on rocking 🤘

**Comment by baileypumfleet** [comment]
@s-gbz Thanks for the comment! We removed discussions because it was unclear where to add feature requests, but haven't moved over the integrations roadmap. However you can see which integrations we plan to ship in the next version on the products tab. Regarding CalDAV, it should be working, but there are some bugs to iron out

**Comment by PeerRich** [comment]
this is closed, right?

**Comment by sean-brydon** [comment]
Looks like this issue is closed - think app-store tied this all together
