### ISSUE TITLE
Out of Office does not block booking times

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [calcom/cal.com#14422]
### Issue Summary

Using the cal.com web app, I have set several Out of Office time ranges. However, bookers can still book slots during those dates. This seems like unexpected behavior to me, but perhaps there is a toggle somewhere. If there is a toggle somewhere, its location is not immediately clear to me (which could potentially warrant an improvement).

I acknowledge that this very well could be a user (i.e. me!) problem, in which case hopefully I can help identify why I am clueless once I am redirected. 👍 

### Steps to Reproduce

1. Go to My Settings
2. Click Out of Office
3. Add a time range
4. Click Create entry
5. Go and try to book a time during that period

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

Users can book during the Out of Office period.

### Expected Results

The Out of Office period should block booking (or give the users the option to set this).

### Technical details

- Microsoft Edge 123.0.2420.65 (64-bit) on Windows 11 using the web platform

### Evidence

Here are some Out of Office time ranges that I have set.

![image](https://github.com/calcom/cal.com/assets/8674072/11b10fc0-3566-48b3-8cad-79b15db842fe)

The blocks are still bookable.

**Comment by ciaranha** [comment]
@Andrew-S-Rosen Thanks for reporting. This should be fixed now.
