### ISSUE TITLE
Virtual (Cached) Calendar

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1442]
# Virtual Calendar
Store the user's availability in the database, which enables quick querying and additional functionality. We need a way to disable days on the calendar if they're fully booked, so we need to cache availability like Calendly, so when the page loads we fetch the data for which days are fully booked, then when you click on a date it loads the full available times for that day.

## Disable days which are fully booked
Once we have the user's availability cached, we can now easily query if a day is fully booked, and grey out that date instead of allowing the user to click it and then discover that they are fully booked for that day.

**Comment by IWGAG** [comment]
Please!!! highly needed feature. The UX and Customer Journey is breaking here. Our customers dont want to click 5 times to finde the right day.

**Comment by wemakefuture** [comment]
@baileypumfleet how is it going? We are watching this too. Does it come with this release?

**Comment by AbcSxyZ** [comment]
> Store the user's availability in the database, which enables quick querying and additional functionality.

It may be a great way to have a pre-filled calendar with host personal calendar (like if he's using a paper calendar). Actually, it needs to be synced with a caldav server, annoying when you don't have one, users can't know your real availability.

And even with a synced caldav it may be useful, for example I have a meeting where I have transport time before (and after) it, I can't specify in the app to avoid booking just before personal events.

No way to support it or develop it myself, but would be an important feature I guess. Being in this situation personally 😂 It's a personal barrier to cal.com adoption, not sure how I should deal with it.

**Comment by wemakefuture** [comment]
@PeerRich @baileypumfleet tested the caching and its in the online version not working. My availability is not changed

**Comment by PeerRich** [comment]
@wemakefuture can you try again? has it been improved?

**Comment by PeerRich** [comment]
added in v.1.7 🎉
