### ISSUE TITLE
[CAL-3736] All webhooks are being triggered, despite not being subscribed to the specific event type

### ISSUE THREAD

**Issue by ahmad-ali14** [calcom/cal.com#14426]
### Issue Summary

I have two webhooks, one for dev env and the other for prod. I created a test call and it only subscribes to the dev webhook. 

However, when I book a test call, both webhooks are triggered. 

I double-checked, and the dev webhook also gets triggered on prod bookings.

### Steps to Reproduce

1. Create two webhooks.
2. Create an event type.
3. Go to event type settings and subscribe it to *one webhook only*
4. Book a call of that type.
5. Notice that *both* webhooks are triggered, despite one of them never subscribed to the webhook.

### Actual Results

- All active webhooks are being triggered for all event types.
- An event type was able to trigger a webhook that is not instructed to listen to this event type.

### Expected Results

- I expect that an event type only triggers the subscribed webhooks and not all the active ones.
- I expect that newly created event types do not trigger existing webhooks unless explicitly stated in the event type settings. 

### Technical details

- Irrelevant; I do not self-host; no code is involved, only interface.

### Evidence

- The `Test Call` only has one webhook activated

![Screenshot 2024-04-05 at 11 45 05](https://github.com/calcom/cal.com/assets/46387030/d2777043-d6b2-4e9a-9971-a3ae2ae80aab)

- Both active webhooks are triggered.
![Screenshot 2024-04-05 at 11 43 50](https://github.com/calcom/cal.com/assets/46387030/3a3948fa-21e1-43cc-a423-de74e0ded12a)

<sub>[CAL-3736](https://linear.app/calcom/issue/CAL-3736/all-webhooks-are-being-triggered-despite-not-being-subscribed-to-the)</sub>

**Comment by thepradipvc** [comment]
Hey @ahmad-ali14, as per what I understand. All the webhooks you create from the following page `https://app.cal.com/settings/developer/webhooks` are subscribed to all the event-types in your account.

To set a webhook for a particular event-type, you need to add it to the edit page of event-type `https://app.cal.com/event-types/eventId?tabName=webhooks`.

**Comment by thepradipvc** [comment]
Yes, this is what I found while testing the webhooks to understand your problem. Also there is no way to select from the global webhooks created from settings in a particular event-type webhooks settings. So this confirms that it will be as per my understanding only.

You should try deleting the global webhooks and create separate webhooks for each event-type as it works as per your requirement at this moment at least.

I'm not sure if this is intended behaviour or the maintainers might choose to change it in future.

Hope this helps 😊

**Comment by ahmad-ali14** [comment]
@thepradipvcThank you very much; I will try this and update the issue.

I noticed that the webhook object can have only one eventType id although you would expect one-to-many relationship.

But yeah, someone needs to update the docs as this is really cpunter intuitive.

**Comment by thepradipvc** [comment]
> But yeah, someone needs to update the docs as this is really cpunter intuitive.

Yes, the docs are misleading. Should we mention any maintainer here to look at the issue?

**Comment by ahmad-ali14** [comment]
> Yes, the docs are misleading. Should we mention any maintainer here to look at the issue?

Yes please.

**Comment by thepradipvc** [comment]
Hey @PeerRich,
I don't know whom to mention for such an issue but I know you are one of the maintainers so I mentioned you.
Can you confirm from our above discussion if the documentation needs to be updated?

**Comment by PeerRich** [comment]
hey this has been under my radar, apologies. we are prioritizising this urgently!
