### ISSUE TITLE
Jitsi Meet

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1445]
Add a Jitsi Meet integration, which enables people to use the public Jitsi meet instance (meet.jit.si) or use their own self hosted Jitsi.

Jitsi integration is as simple as generating a UUID and setting that as the URL (e.g. meet.jit.si/d8sf97s8d9f7s9).

**Comment by wokawoka** [comment]
Yes, I agree, Jitsi is also open source.
I'm waiting for calendso to add a way to integrate jitsi to immediately switch to it.

**Comment by philippdormann** [comment]
> @philippdormann just when I began to worry about Jitsi support I saw your feature branch, nice job! Can you tell me if it's functional, yet? Thanks in advance
~ https://github.com/philippdormann/calendso/commit/4d6b4d44515ccd9108e67e1ac2402cbfa6e09c74#commitcomment-65780192

Hi @dominikfehr

**The feature branch is not quite ready yet.** The things left to do is generating the random meeting id in the VideoApiAdapter and displaying the meeting URL in the /success view.

I would probably handle configurable URLs (currently "meet.jit.si/cal/\<uuid>") and custom (self hosted) Jitsi instances in a new issue.


(meeting URLs might be "/cal/\<username>/\<meeting-type>+\<uuid>" or "/cal/\<username>/\<uuid>")
any thoughts on this? (cc @PeerRich)

**Comment by PeerRich** [comment]
we currently have daily video do: cal.com/call/3ZTC43qUPtVnTfEg4MzrnV 

i think we should do cal.com/jitsu/3ZTC43qUPtVnTfEg4MzrnV

**Comment by PeerRich** [comment]
@baileypumfleet whats your take on this?

**Comment by philippdormann** [comment]
> i think we should do cal.com/jitsu/3ZTC43qUPtVnTfEg4MzrnV

hm... with that you would kind of break the compatibility for other/ selfhosted Jitsi instances 🤔☹️ (if - ofc - you would want to support that. I would like custom instances to be supported.)

**Comment by dominikfehr** [comment]
+1 for support of other / selfhosted Jitsi instances. The main reason for myself to use the combination is the ability to be fully GDPR compliant. Therefor this feature would be quite useful.

**Comment by PeerRich** [comment]
> > i think we should do cal.com/jitsu/3ZTC43qUPtVnTfEg4MzrnV
> 
> 
> 
> hm... with that you would kind of break the compatibility for other/ selfhosted Jitsi instances 🤔☹️ (if - ofc - you would want to support that. I would like custom instances to be supported.)

no why would that break??

i meant <domain>/jitsu/meetingid not specifically cal.com

**Comment by philippdormann** [comment]
@PeerRich Let me explain - if you intend to only use the official Jitsi Meet instance (meet.jit.si), /jitsi/\<meetingid> would suffice.

If you intend to support custom ([selfhosted](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)) Jitsi Meet instances, the user needs to configure this (either as a user preference or on a global level via env).

I would propopse only building meet.jit.si support in this first version - using the direct meet.jit.si link via E-Mail or in the /success/ page.

Please hit me up for any questions 🙂 - Would love to ship this feature👍

**Comment by PeerRich** [comment]
> @PeerRich Let me explain - if you intend to only use the official Jitsi Meet instance (meet.jit.si), /jitsi/<meetingid> would suffice.
> 
> If you intend to support custom ([selfhosted](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)) Jitsi Meet instances, the user needs to configure this (either as a user preference or on a global level via env).
> 
> I would propopse only building meet.jit.si support in this first version - using the direct meet.jit.si link via E-Mail or in the /success/ page.
> 
> Please hit me up for any questions 🙂 - Would love to ship this feature👍

i think it s a great first MVP to just link to meet.jit.si/meetingid vs having it whitelable branded. go for it!

**Comment by wokawoka** [comment]
> If you intend to support custom ([selfhosted](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)) Jitsi Meet instances, the user needs to configure this (either as a user preference or on a global level via env).
> 
> I would propopse only building meet.jit.si support in this first version - using the direct meet.jit.si link via E-Mail or in the /success/ page.
> 
> Please hit me up for any questions slightly_smiling_face - Would love to ship this feature+1

@philippdormann hey philipp, thank you very much for your commits! 
still, I'm a little bit confused. I mange a couple of selfhosted jitsi installations and I would love to switch to using cal.com to book my appointments. The project looks great.
Are you guys by chance going to add the possibility to point to a selfhosted jitsi installation someday in the future?
Thank you again
