### ISSUE TITLE
[CAL-1110] Error page when rejecting Google Calendar permissions is blank

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1446]
We need a prettier way of handling permission rejection

<sub>[CAL-1110](https://linear.app/calcom/issue/CAL-1110/error-page-when-rejecting-google-calendar-permissions-is-blank)</sub>

**Comment by PeerRich** [comment]
i do agree, this is quite high in my opinion

**Comment by roae** [comment]
@Jaibles Is there a design for this?

**Comment by Jaibles** [comment]
Need to clean this up but start on designs [here](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr?node-id=4947:364321&locale=en&type=design)

**Comment by memoryStack** [comment]
@PeerRich i would like to work on this. but i can't access this [ticket](https://linear.app/calcom/issue/CAL-1110/error-page-when-rejecting-google-calendar-permissions-is-blank). pleaae provide me the access.
