### ISSUE TITLE
[CAL-3372] Workflow — Send Email to Specific Email

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#14466]
@lorenzo and I are working on getting calls booked for @peer + @baileypumfleet — it would be great to be notified when a call actually gets booked. 

I think this can be accomplished via the "Workflows" by adding "Send email to specific email" similar to how we do it for "Send text to specific number" 

I guess for now, I could add Lorenzo and my number to get text notifications when calls are booked as a work around

![CleanShot 2024-04-09 at 14.50.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5e766764-6408-4b72-97b3-45e085c476fe/b226060d-6ae0-4a2b-a0d5-7100ba530fe1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ZTc2Njc2NC02NDA4LTRiNzItOTdiMy00NWUwODVjNDc2ZmUvYjIyNjA2MGQtNmFlMC00YTJiLWEwZDUtNzEwMGJhNTMwZmUxIiwiaWF0IjoxNzEyNjQ1NTA0LCJleHAiOjE3MTI3MzE5MDR9.um5sHhP9U3-fiMGGN-SrqCHhAl-aibvsYFnT-5VxfzQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3372](https://linear.app/calcom/issue/CAL-3372/workflow-send-email-to-specific-email)</sub>

**Comment by ciaranha** [comment]
This was removed because it was being abused. We can add this back by adding a verification email when creating the workflow (like we do with SMS) cc @CarinaWolli @shirazdole
