### ISSUE TITLE
[CAL-3373] Typo — "wong email code"

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#14467]
![CleanShot 2024-04-09 at 14.52.30@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d1a0a4e5-ec84-4561-923c-68df79df57d9/07b4f3e6-c4ca-4852-80d0-40efcc9ece1e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kMWEwYTRlNS1lYzg0LTQ1NjEtOTIzYy02OGRmNzlkZjU3ZDkvMDdiNGYzZTYtYzRjYS00ODUyLTgwZDAtNDBlZmNjOWVjZTFlIiwiaWF0IjoxNzEyNjQ1NTkyLCJleHAiOjE3MTI3MzE5OTJ9.WgPdIYIC3tZ7lFo56mOsEOWYtrvlGnWxvQR87DuBITo)

![CleanShot 2024-04-09 at 14.52.30@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9e1d29fa-5e20-4822-b0c4-d24590d90e78/09664754-f193-41ec-8ff9-ffd5d015e8e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85ZTFkMjlmYS01ZTIwLTQ4MjItYjBjNC1kMjQ1OTBkOTBlNzgvMDk2NjQ3NTQtZjE5My00MWVjLThmZjktZmZkNWQwMTVlOGU5IiwiaWF0IjoxNzEyNjQ1NTkyLCJleHAiOjE3MTI3MzE5OTJ9.7dfdYbok33Ef2plOdpfay8gVCWeBjbLrmQxeMAL_-FM)

![CleanShot 2024-04-09 at 14.52.27@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/33fef0f8-4dfb-4384-97d3-c77902bbdb6e/98acef3f-a028-449d-acdb-eabcf98ae685?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zM2ZlZjBmOC00ZGZiLTQzODQtOTdkMy1jNzc5MDJiYmRiNmUvOThhY2VmM2YtYTAyOC00NDlkLWFjZGItZWFiY2Y5OGFlNjg1IiwiaWF0IjoxNzEyNjQ1NTkyLCJleHAiOjE3MTI3MzE5OTJ9.HHQ13nE-TZ-PsfiOuzCQ-IuXO3CP_x-UBfueOg7n0tc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3373](https://linear.app/calcom/issue/CAL-3373/typo-wong-email-code)</sub>

**Comment by PeerRich** [comment]
fixed https://github.com/calcom/cal.com/pull/14472
