### ISSUE TITLE
"This page does not exist." on every event page - also on docker

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#14483]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Went to a event page (/username/15-min)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Receiving a 404 on every event page

### Expected Results

- Seeing the event page

### Evidence

- We run the latest version of cal, freshly installed. We face the same error on the latest docker image. The console dowsnt throw any errors.
- 
![image](https://github.com/calcom/cal.com/assets/25285295/8fcde734-1269-41ab-898b-85d51f34cc48)

**Comment by dynahpointch** [comment]
i receive the following error in the log if i open a event page with a 404 error in v3.9.7

@calcom/web:start:  ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
@calcom/web:start: `themeBasis` is required for booking page theme support. Not providing it will cause theme flicker.
@calcom/web:start: react-i18next:: You will need to pass in an i18next instance by using initReactI18next
@calcom/web:start: Warning: data for page "/auth/login" is 150 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
@calcom/web:start: See more info here: https://nextjs.org/docs/messages/large-page-data

and where is this folder please specify ut with the full folder recursive from the \ root folder.
ensure you have a file named [username]/[event].tsx in the pages directory to correctly route requests to your EventPage

**Comment by lippoliv** [comment]
I'm having the same issue, any ideas?
