### ISSUE TITLE
Embed core - sdk events missing in Documentation and package Types

### ISSUE THREAD

**Issue by Shpadoinkle** [calcom/cal.com#14489]
### Issue Summary
While investigating capabilities of embeds and embed events.   `rescheduleBookingSuccessful` and `bookingCancelled` are present in the code and work when used by bypassing types with `any`

- These events are not listed in the documentation for embed events
  -  https://cal.com/docs/core-features/embed/embed-events#actions
- These event types also do not appear in the available types for `EventDataMap` for the @calcom/embed-core package
  - file `node_modules/@calcom/embed-core/dist/src/sdk-action-manager.d.ts`  

### Steps to Reproduce
- Install latest @calcom/embed-react
- attempt to pass in `rescheduleBookingSuccessful` and `bookingCancelled` as an action name. 
- you will get type errors

### Actual Results
type/compilation errors. 

### Expected Results
can pass in callback functions for `rescheduleBookingSuccessful` and `bookingCancelled`

### Technical details
Installed packages: 
 - @calcom/embed-react 1.3.2
   - @calcom/embed-core 1.3.3

### Evidence
- file `node_modules/@calcom/embed-core/dist/src/sdk-action-manager.d.ts`  does not include `rescheduleBookingSuccessful` or `bookingCancelled`

**Comment by hariombalhara** [comment]
@calcom/embed-react v1.4.0 published that includes these events.
