### ISSUE TITLE
I cant create bookings with the API

### ISSUE THREAD

**Issue by outerpreneur** [calcom/cal.com#14500]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Im trying to build a web app that creates bookings from cal.com using the API. 

### Steps to Reproduce

1. I have created a push button that creates bookings.
2. When the button is triggered, this is included in the POST request:
3. `    body: JSON.stringify({
      start: "2024-05-31T10:00:00.000Z",
      eventTypeId: "641549",
      metadata: {},
      responses: {
        name: "John",
        email: "johndoe@gmail.com",
      },
      timeZone: "Europe/Zurich",
      language: "en",
      status: "ACCEPTED",
    }),
  })`
4. I get an error message: {message: 'An error occured while querying the database.'}

I was expecting this to create. booking for 10:00 31st May 2024. This slot is available in the calendar event type and it has no clash.

### Actual Results

I get the error after trying multiple times

### Expected Results

- Make this booking happen

### Technical details

-Tested with Chrome in MacOS Sonoma.

### Evidence

[- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.](

https://www.loom.com/share/f14545d18f194208b1e23f0e1d70e9f7?sid=df104259-390c-4735-9b3b-0bd5546bd37b

The repository where I am doing this test:
https://github.com/outerpreneur/API-testing.git

**Comment by jonezy35** [comment]
I am also getting this error when attempting to create a booking

**Comment by skalingclouds** [comment]
glad i looked, ripping my hair out, this has to be a bug, looks like they had this issue on the docker version, i am hitting the cloud cal.com api, same error no matter what i do  {   "message": "An error occured while querying the database." }. @outerpreneur please help

**Comment by jonezy35** [comment]
> glad i looked, ripping my hair out, this has to be a bug, looks like they had this issue on the docker version, i am hitting the cloud cal.com api, same error no matter what i do { "message": "An error occured while querying the database." }. @outerpreneur please help

I figured it out by searching on the discord. In my case I had to remove the `value` wrapper from the request. So my request simply looks like:

```
data = {
            "eventTypeId": event_type_id,
            "start": block_start,
            "end": block_end,
            "responses": {
                "name": "Busy Period",
                "email": "noreply@example.com",
                "metadata": {},
                "location": "Unavailable"
            },
            "metadata": {},
            "timeZone": "UTC",
            "language": "en",
            "title": title,
            "description": "busy",
            "status": "PENDING"
        }
```

**Comment by salmoro** [comment]
@jonezy35 can you share the exact payload which works for you?
Also is `"data"` the body? or is that a field within the body?
The above doesn't seem to work for me and the documentation and error messaging here is very poor and inconsistent.

> > glad i looked, ripping my hair out, this has to be a bug, looks like they had this issue on the docker version, i am hitting the cloud cal.com api, same error no matter what i do { "message": "An error occured while querying the database." }. @outerpreneur please help
> 
> I figured it out by searching on the discord. In my case I had to remove the `value` wrapper from the request. So my request simply looks like:
> 
> ```
> data = {
>             "eventTypeId": event_type_id,
>             "start": block_start,
>             "end": block_end,
>             "responses": {
>                 "name": "Busy Period",
>                 "email": "noreply@example.com",
>                 "metadata": {},
>                 "location": "Unavailable"
>             },
>             "metadata": {},
>             "timeZone": "UTC",
>             "language": "en",
>             "title": title,
>             "description": "busy",
>             "status": "PENDING"
>         }
> ```

**Comment by jonezy35** [comment]
> @jonezy35 can you share the exact payload which works for you?
> 
> The above doesn't seem to work for me and the documentation and error messaging here is very poor and inconsistent.
> 
> > > glad i looked, ripping my hair out, this has to be a bug, looks like they had this issue on the docker version, i am hitting the cloud cal.com api, same error no matter what i do { "message": "An error occured while querying the database." }. @outerpreneur please help
> > 
> > 
> > I figured it out by searching on the discord. In my case I had to remove the `value` wrapper from the request. So my request simply looks like:
> > ```
> > data = {
> >             "eventTypeId": event_type_id,
> >             "start": block_start,
> >             "end": block_end,
> >             "responses": {
> >                 "name": "Busy Period",
> >                 "email": "noreply@example.com",
> >                 "metadata": {},
> >                 "location": "Unavailable"
> >             },
> >             "metadata": {},
> >             "timeZone": "UTC",
> >             "language": "en",
> >             "title": title,
> >             "description": "busy",
> >             "status": "PENDING"
> >         }
> > ```

So that's part of a test python script I was running. I'll just put the script here so you can see it.

```python
import requests

# Define the base URL
base_url = 'https://api.cal.com/v1/bookings'

# Your API key
api_key = 'yourapikey

# Append the API key as a query parameter
url = f'{base_url}?apiKey={api_key}'

# JSON data to be sent in the POST request
data = {
    "eventTypeId": 000000,
    "start": "2024-04-12T18:00:00.000Z",
    "end": "2024-04-12T18:30:00.000Z",
    "responses": {
      "name": "Hello Hello",
      "email": "hello@gmail.com",
      "metadata": {},
      "location": "Calcom HQ"
    },
    "metadata": {},
    "timeZone": "UTC",
    "language": "en",
    "title": "Debugging between Syed Ali Shahbaz and Hello Hello",
    "description": "busy",
    "status": "PENDING"
}

# Make the POST request
response = requests.post(url, json=data)

# Check if the request was successful
if response.status_code in [200, 201]:
    print("Success:", response.json())  # Prints the JSON response
else:
    print(f"Failed to submit data: {response.status_code}, Reason: {response.text}")
```

My error was I was using the data block within a value block like the documentation for the API shows [here](https://cal.com/docs/enterprise-features/api/api-reference/bookings#create-a-new-booking)
```
{
  "value": {
    "eventTypeId": 2323232,
    "start": "2023-05-24T13:00:00.000Z",
    "end": "2023-05-24T13:30:00.000Z",
    "responses": {
      "name": "Hello Hello",
      "email": "hello@gmail.com",
      "metadata": {},
      "location": "Calcom HQ"
    },
    "timeZone": "Europe/London",
    "language": "en",
    "title": "Debugging between Syed Ali Shahbaz and Hello Hello",
    "description": null,
    "status": "PENDING",
    "smsReminderNumber": null
  }
}
```

So for me just removing the outer `value` JSON block worked.

**Comment by salmoro** [comment]
@jonezy35 Thanks. In the end my issue was solved by adding headers `Content-Type: application/json`

**Comment by outerpreneur** [comment]
I can't believe it, but in my case, it was just a typo, I put eventypeId with strings instead of a number. It now works fine!

**Comment by ciaranha** [comment]
Resolved

**Comment by govindrai** [comment]
The API should not respond with a 500 if a client send bad data. Please fix the API to return proper validation error messages.
