### ISSUE TITLE
[CAL-3390] Browser Notifications

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14504]
![CleanShot 2024-04-10 at 20 34 42@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b43036a3-099c-41ae-ab2e-eb9ba51c0d19/6414260c-bf25-4187-9223-20e55502a751?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iNDMwMzZhMy0wOTljLTQxYWUtYWIyZS1lYjliYTUxYzBkMTkvNjQxNDI2MGMtYmYyNS00MTg3LTkyMjMtMjBlNTU1MDJhNzUxIiwiaWF0IjoxNzEyNzc3NzAxLCJleHAiOjE3MTI4NjQxMDF9.hBEedPDuCO7h7mqK_VwUspilVlorWWzQ_SsvP_XAoBw)

* have a button inside [app.cal.com/bookings](http://app.cal.com/bookings) to allow notifications
* use notifications API

send notifications for:

* incoming events that require confirmation
* any time a calendar event happens, have the location link as the destination of that notification

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3390](https://linear.app/calcom/issue/CAL-3390/browser-notifications)</sub>

**Comment by ashavijit** [comment]
Hey! Looking into it 😄

**Comment by webbdays** [comment]
can i work on this?

**Comment by suryansh-malik** [comment]
Do you prefer to receive notifications even when your browser is closed, or only when browser is opened and users actively using the application?

**Comment by suryansh-malik** [comment]
@PeerRich  push notification or local notification

**Comment by PeerRich** [comment]
> @PeerRich Do you want to receive notifications even when your browser is closed, or only when browser is opened and users actively using the application?

closed

**Comment by thepradipvc** [comment]
Hey @PeerRich ,
Can you just look at this PR https://github.com/calcom/cal.com/pull/14888 & confirm if it's something you want and also answer my questions that I have included in the [notion doc](https://boatneck-marmoset-399.notion.site/Cal-com-Notifications-Feature-7fc1e630b29a422b9e060408a09c353d)

**Comment by ranjanmangla1** [comment]
@PeerRich is this issue still valid, i already see a lot of prs here
