### ISSUE TITLE
[CAL-3393] Looks like we are not cancelling existing Teams subscriptions for someone that upgrades to Organization.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#14514]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3393](https://linear.app/calcom/issue/CAL-3393/looks-like-we-are-not-cancelling-existing-teams-subscriptions-for)</sub>

**Comment by sean-brydon** [comment]
Fixed by #15594
