### ISSUE TITLE
State Inconsistency issue on webhook edit modal

### ISSUE THREAD

**Issue by Chiranjeev-droid** [calcom/cal.com#14521]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Loom Video 
https://www.loom.com/share/e8cd12483cc34e8ea7fddfcf702ce97b?sid=ec3b8e61-6733-4096-aacc-8a01ee749d75

When editing a webhook, after editing and saving then it redirect us to webhook list page but when we click again on edit , it shows the previous state data . But if we again go back to list page and again click on edit , this time it shows correct data that is shown on webhooks listing page.
### Steps to Reproduce

1. Go to webhooks listing page , https://app.cal.com/settings/developer/webhooks
2. Edit an existing webhook url and then save.
3. Now you are on webhooks listing page again , now again click on edit btn and you will see the data which was there before editing.

If if is a feature then please close this issue , or if it is a bug then letme know i will fix it.

**Comment by sean-brydon** [comment]
Hey @Chiranjeev-droid i believe this is a bug yeah!
