### ISSUE TITLE
[CAL-3732] Embed.js - CORS issue

### ISSUE THREAD

**Issue by McPizza0** [calcom/cal.com#14547]
### Issue Summary

we use strict security at @un due to the nature of data we handle
one of the sercurity headers we have enabled is COEP (Cross-Origin-Embedder-Policy)

When using the Cal js embed, the component fails to load and we get multiple cors errors
![image](https://github.com/calcom/cal.com/assets/17185737/d4f7aac9-fb45-4416-b368-488a094a0ff9)

it seems that cal's embed does not have `Cross-Origin-Resource-Policy: cross-origin` enabled, thus breaking cors for sites that require it

can the correct security header be added so we can embed cal.com in our application please

<sub>[CAL-3732](https://linear.app/calcom/issue/CAL-3732/embedjs-cors-issue)</sub>

**Comment by sean-brydon** [comment]
@hariombalhara can you please let mr pizza here know the next steps he needs to take

**Comment by hariombalhara** [comment]
In the linked PR I have added the support for the headers but we can't merge it yet as certain third parties don't have CORP headers set. 

I am thinking about adding conditional support for CORP header. @McPizza0 How about we support a config to conditionally set CORP header and when that is set, certain analytic apps will stop working till they support CORP header e.g. Fathom analytics which can be installed as an app in cal.com and can be enabled per Event Type

**Comment by hariombalhara** [comment]
Moving it back to v4.2 as it is already ready for review
