### ISSUE TITLE
[CAL-3411] [CAL-3410] Unclear UI leads to am/pm mistakes

### ISSUE THREAD

**Issue by filiph** [calcom/cal.com#14564]
**NOTE:** Sorry if this is the wrong place to file the issue. I wanted to go through support on cal.com but it was a chatbot that didn't understand what I want and when I was given the option to talk to a person, I got "We'll be back online on Monday" and no further response. Not even the times and timezones. I tried to find an email for support, but couldn't find one on cal.com website.

### Issue Summary

Since I started using cal.com about 2 months ago, I've had 2 instances of similar mistakes. Here's the latest example.

* I was contacted by a potential business partner who mentioned that they're in California (PDT) but also plan to be in Germany (CET) soon.
* I send them to my cal.com address so we can schedule a video call.
* A meeting is scheduled by them for my 2pm Friday spot. Cool. 
* Since they might be in my timezone, it doesn't strike me as weird. If there was no indication that they might be in my timezone at the time, I'd probably double check if the time is correct.
* I have it in my calendar, let's go. 
* On Friday 2pm, they don't show up.

On Friday evening, I get the following email:

> I was getting ready for our meeting and realized that it was booked for 2 am instead of 2 pm Pacific Time. 
>
> Are you still available now or did your weekend already start? Let me know, I'm also happy to do it another day if that's easier for you!

And later:

> yeah, I just double checked with Cal.com. It does show am / pm, but not in the main selection window where it displays "02:00", but it was visible on the side. These timezones confused me! Sorry for that. 

### Steps to Reproduce

1. Try to book a meeting slot from someone in another timezone 

### Actual Results

- Times are listed as "02:00" or "03:00". If the timezone is sufficiently different and the availability is set to a subset of working hours, these times can look completely inconspicuous (e.g. 2:00 to 4:30)
- The am/pm information is on the screen but not where people are looking.

### Expected Results

- Times are listed with am/pm information attached: "2:00 am". (This seems to be the standard — something I just noticed Google Calendar scheduler does, for example.)

### Evidence

- I can send you the email threads for both instances of the similar mistake (made by my potential business partners).

I want to make it clear how big a deal this is. I use cal.com to make it easier for me to schedule things with people, some of whom might be in different timezones. Cal.com has been fantastic when it worked. It really does save time, and I love it. But from the less than 10 meetings I've had organized through cal.com so far, I had two complete misses. As in, lost times waiting for the other side to show up, then writing apologetic emails and explanations.

<sub>[CAL-3410](https://linear.app/calcom/issue/CAL-3410/unclear-ui-leads-to-ampm-mistakes)</sub>

**Comment by ayushpatil2122** [comment]
hey filiph can you just send the ss for the same so that i can see in which page this problem is

**Comment by filiph** [comment]
I asked the person who tried to book for screenshots and he was kind enough to provide the following:

----

> What happend: As a guest, I expected to see your availability adapted to my timezone, which immediately made sense to me when I saw times spanning from 01.00 to 4.00.
>
> ![image(1)](https://github.com/calcom/cal.com/assets/919717/371215fe-a274-42f1-8d35-1e77fba153af)
>
> Of course this was wrong, since I didnt see the 12/24 toggle (and I wasnt looking for it). Once the button is pressed, it all makes beautiful sense. I just didnt see it. 
>
> ![image(2)](https://github.com/calcom/cal.com/assets/919717/960d930a-81c7-4cdd-b298-1dbaf162ce45)

**Comment by ciaranha** [comment]
> Times are listed with am/pm information attached: "2:00 am". (This seems to be the standard — something I just noticed Google Calendar scheduler does, for example.)

While Google calendar does show "am" appended, it also only shows a 12-hour calendar. We also have it appended on the 12-hour calendar. It's a little weird to do this on 24-hour calendar, so we need to think about this one. Perhaps we could make 12-hour the default if you're timezone is US-based - then you would always see am or pm.

**Comment by filiph** [comment]
> It's a little weird to do this on 24-hour calendar

Yeah, I agree. 

Maybe all that's needed is a conditional warning. Something like:

> If user's timezone is different from the calendar's default timezone, and times between 01:00 and (let's say) 06:00 are listed, append a warning that warns the user that these times are during the night.

The heuristic could be different, of course. But it's basically: detect if this time slot listing can lead to mistakes, and if so, show the warning at the top of the list of time slots. For example, a listing that includes 23:00 and 0:00 and 1:00 will not lead to such mistakes. But the one you see in the screenshot above might.

Also, I think the business partner who had the problem has German locale, and maybe that's why he sees the 24-hour format instead of the 12-hour one? Because when I visit my cal.com page in an incognito window, I see it in the 12-hour format, and there's no confusion.

**Comment by ciaranha** [comment]
> Also, I think the business partner who had the problem has German locale, and maybe that's why he sees the 24-hour format instead of the 12-hour one? Because when I visit my cal.com page in an incognito window, I see it in the 12-hour format, and there's no confusion.

Ah that's good to know, thank you for sharing all the detail. And I like your suggestion around the conditional warning. Will think through what we can do that here.  🙏
