### ISSUE TITLE
[CAL-3412] a collective event of N people sends N invites

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14580]
apparently the person booking receives N emails and N calendar invites

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3412](https://linear.app/calcom/issue/CAL-3412/a-collective-event-of-n-people-sends-n-invites)</sub>

**Comment by PeerRich** [comment]
correct would be one invite, with N attendees. seems like this broke recently

**Comment by Amit91848** [comment]
Couldn't replicate, booker received a single email.


https://github.com/calcom/cal.com/assets/74371312/9f329b28-e6c9-4128-85d2-552d94092f09
