### ISSUE TITLE
Add Description to Calendar Body

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1459]
As well as the invitee being able to set the description via notes, the host user should be able to set a description that the invitee will see in the calendar event.

**Comment by PeerRich** [comment]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/8019099/161541792-a70386d5-0a19-4a53-a277-d09530ec9302.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/8019099/161541812-9ce2e861-6d10-4fbb-a33d-6b77d0213e3f.png">
