### ISSUE TITLE
[CAL-3455] Calender has wrong weekdays when selecting vacation periods

### ISSUE THREAD

**Issue by f0sh** [calcom/cal.com#14597]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The calender is shown incorrectly when selecting vacation periods on Android using [cal.com](http://cal.com) as PWA. (see screenshot)

![Screenshot_20240416-072429](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5b3da3ab-4d64-467d-b241-444746d51daf/294f097f-51f6-4fe9-89a3-a3042a968abf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81YjNkYTNhYi00ZDY0LTQ2N2QtYjI0MS00NDQ3NDZkNTFkYWYvMjk0ZjA5N2YtNTFmNi00ZmU5LTg5YTMtYTMwNDJhOTY4YWJmIiwiaWF0IjoxNzEzMjQ0ODMxLCJleHAiOjE3MTMzMzEyMzF9.p8hqh_zyEdQhgQf3VvY68yqLOd4A3xaLGJyjjSPGUCM)

### Steps to Reproduce

1. Click Profile > Away > Add
2. Select Starting / End Dates
3. Calender pops up

### Technical details

* Chrome Browser 123.0.6312.118
* Pixel 6a @ Android 14, Build AP1A.240405.002
* Language: German

### Evidence

![Screenshot_20240416-072429](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/67086426-1700-4a82-ba54-13448e6810cd/4a268cf6-ba9d-4634-8fe5-1549cbe64807?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82NzA4NjQyNi0xNzAwLTRhODItYmE1NC0xMzQ0OGU2ODEwY2QvNGEyNjhjZjYtYmE5ZC00NjM0LThmZTUtMTU0OWNiZTY0ODA3IiwiaWF0IjoxNzEzMjQ0ODMxLCJleHAiOjE3MTMzMzEyMzF9.TixX-DZGij8Jo77cr_vxepm4Z70JL8y2VIg5vLbv1T0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3455](https://linear.app/calcom/issue/CAL-3455/calender-has-wrong-weekdays-when-selecting-vacation-periods)</sub>

**Comment by ciaranha** [comment]
I’m can recreate this on iPhone. I think we established previous it’s a responsive issue with the date picker component 

![IMG_7052](https://github.com/calcom/cal.com/assets/4536123/9ba00e26-9dba-4f08-9f8c-ff3c738dcafb)

**Comment by ciaranha** [comment]
Related https://github.com/calcom/cal.com/issues/14197

**Comment by keithwillcode** [comment]
This was fixed in https://github.com/calcom/cal.com/pull/14713
