### ISSUE TITLE
[CAL-3467] Booking question not visible in the booking submission email

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14603]
It's only visible when you open the booking in the upcoming bookings - [https://app.cal.com/bookings/upcoming](https://app.cal.com/bookings/upcoming)

![Screenshot 2024-04-15 at 19.55.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/09529d0c-1ff0-41d4-9770-4e55e5f767e9/96bb4061-e613-4640-bf37-497ef9dd3a98?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wOTUyOWQwYy0xZmYwLTQxZDQtOTc3MC00ZTU1ZTVmNzY3ZTkvOTZiYjQwNjEtZTYxMy00NjQwLWJmMzctNDk3ZWY5ZGQzYTk4IiwiaWF0IjoxNzEzMjU5MzA3LCJleHAiOjE3MTMzNDU3MDd9.xkrrnPrQn6_cLz66zXyh9YhbtikjoEhv-qAX5WHM_mg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3467](https://linear.app/calcom/issue/CAL-3467/booking-question-not-visible-in-the-booking-submission-email)</sub>

**Comment by SomayChauhan** [comment]
Showing up For me 
https://www.loom.com/share/d55adb4cfff94ad999951b73ce66f5f5?sid=1c3f27b5-1655-4ef8-9b77-760f486b19cc
