### ISSUE TITLE
GDPR Compliance in the EU

### ISSUE THREAD

**Issue by perix90** [calcom/cal.com#14613]
### Is your proposal related to a problem?

Today when I was creating Events, I noticed that there's no way that I, as an individual who offers services to customers, can place my own terms and conditions in Cal.com in order to comply with the GDPR. 

When a customer wants to place a booking, they have to read and accept Cal.com's privacy policy. In this way, It should be created a way to do the same thing for businesses using Cal.com. 

### Describe the solution you'd like

I would like my customers to read my privacy policy before making a booking.

### Describe alternatives you've considered

So far what I did was to place the privacy policy link in the "About" section in my profile. In this way, such link is displayed before making a booking. 

### Requirement/Document

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by ciaranha** [comment]
Would be solved by https://github.com/calcom/cal.com/issues/14163
