### ISSUE TITLE
Change home page background color

### ISSUE THREAD

**Issue by DeepshikhaGupta0053** [calcom/cal.com#14623]
### Is your proposal related to a problem?

(This is not a problem but a suggestion. When I opened this website first time it did not, please me because of the black and white color all over the page.)

### Describe the solution you'd like

(If possible, try changing it to some light colors like #B7EEED, #C3EBEA.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by Bhanubediya** [comment]
Hi is this issue up ?
