### ISSUE TITLE
Simplify logic by removing unnecessary // ts-ignore

### ISSUE THREAD

**Issue by kaleem68** [calcom/cal.com#14621]
In `packages/platform/sdk/src/lib/entpoints/getEndpointData`

The `endpointData.constructUri` expects `string[]` and the code is forcefully converting `Record<string,string>` to `string[]` and suppressing with // ts-ignore

#### Suggestions

Either combine both if and else if and convert params to `string[]` to get rid of  ts-ignore OR 
make endpointData.constructUri accept `string[] | Record<string,string>`

<img width="752" alt="Screenshot 2024-04-17 at 3 53 32 AM" src="https://github.com/calcom/cal.com/assets/13909729/eeb7e1e5-03e2-40bd-801a-6168f2fb7af9">

**Comment by Aniruddha775** [comment]
hey is this issue still open?

**Comment by kaleem68** [comment]
@Aniruddha775 Yes issue is opened
I also have created  PR [Pr for 14621](https://github.com/calcom/cal.com/pull/14622)

**Comment by Aniruddha775** [comment]
@kaleem68  so it is not yet merged right, so can i work on this?

**Comment by kaleem68** [comment]
@Aniruddha775 Yes you can.
