### ISSUE TITLE
[CAL-3489] org-wide workflows

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14638]
that can be added and removed to an entire org

<sub>[CAL-3489](https://linear.app/calcom/issue/CAL-3489/org-wide-workflows)</sub>

**Comment by PeerRich** [comment]
if active, disable manual dropdown


![image](https://github.com/calcom/cal.com/assets/8019099/c1b55cc2-ace6-4602-b8d8-eba1f8b5aff2)

**Comment by PeerRich** [comment]
show upgrade banner for non-orgs

**Comment by keithwillcode** [comment]
I assume we want this off for platform orgs but let's discuss cc @MorganChetelat @ebruinsma @lauris @rajiv
