### ISSUE TITLE
[CAL-3493] replace team list view with org list view UI

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14646]
replace

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/45d7a98a-9a3e-4315-abc4-69fbf3153166/d61753de-3252-4d3d-a287-b91e23e0ab14?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80NWQ3YTk4YS05YTNlLTQzMTUtYWJjNC02OWZiZjMxNTMxNjYvZDYxNzUzZGUtMzI1Mi00ZDNkLWEyODctYjkxZTIzZTBhYjE0IiwiaWF0IjoxNzI0MDYwNzk3LCJleHAiOjE3NTU1OTY3OTd9.LhNhb5AMTg4dI5WGtIn83fs5bhfkJAGmd2Mm9N_NXkM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3493](https://linear.app/calcom/issue/CAL-3493/replace-team-list-view-with-org-list-view-ui)</sub>

**Comment by PeerRich** [comment]
lets show all installed apps here instead:

![CleanShot 2024-04-17 at 21 03 59@2x](https://github.com/calcom/cal.com/assets/8019099/3c5abf11-5c41-4cb0-a5fc-61f49aa5a3c9)

**Comment by animeshdas2000** [comment]
Hi, can I take up this one?

**Comment by smitgol** [comment]
@PeerRich not able to see first two images can you re upload it ?
