### ISSUE TITLE
[CAL-3741] The meeting ended trigger on Zapier isn't working

### ISSUE THREAD

**Issue by crisneda** [calcom/cal.com#14644]
The meeting ended trigger on Zapier isn't working. I've tried in various types of events, and it only logs in intermittently and with some delay, for example, the connections with Spreadsheets or Gmail.

<sub>[CAL-3741](https://linear.app/calcom/issue/CAL-3741/the-meeting-ended-trigger-on-zapier-isnt-working)</sub>

**Comment by ciaranha** [comment]
@CarinaWolli would [this pr](https://github.com/calcom/cal.com/pull/14864) have resolved this issue?

**Comment by CarinaWolli** [comment]
This should be fixed with: https://github.com/calcom/cal.com/pull/14864

Old bookings might still not trigger, but all new bookings will work. Also yes, there can be a delay of a few minutes. Is that an issue?
