### ISSUE TITLE
[CAL-3500] Date Override Modal Trims Date Picker

### ISSUE THREAD

**Issue by ThisIsJustUs** [calcom/cal.com#14658]
### Issue Summary

When using the data override and opening the time input, the modal trims the list which makes it hard to find the right time. This is not an urgent improvement, just something I wanted to bring up.

### Steps to Reproduce

1. Go to Availability
2. Go to Data Override
3. Click on the time slots

### Actual Results

![CleanShot 2024-04-18 at 17 16 50@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/908c2210-4670-48fc-b343-59aee70e2b68/ec2a06cf-56e0-481c-9ea0-b3df85162b8f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85MDhjMjIxMC00NjcwLTQ4ZmMtYjM0My01OWFlZTcwZTJiNjgvZWMyYTA2Y2YtNTZlMC00ODFjLTllYTAtYjNkZjg1MTYyYjhmIiwiaWF0IjoxNzEzNTI5ODYxLCJleHAiOjE3MTM2MTYyNjF9.HiA5VXivhcwAfSkYJMPYrvM0ryawHiCz8X26HMDzBac)

### Expected Results

The list should render downwards in my opinion or go beyond the modal height.

### Technical details

* Browser: Chrome Version 124.0.6367.62

### Evidence

Screenshot above

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3500](https://linear.app/calcom/issue/CAL-3500/date-override-modal-trims-date-picker)</sub>

**Comment by ayushhunt** [comment]
![image](https://github.com/calcom/cal.com/assets/87143358/b4756b23-5cd9-448f-a066-86cb5548bbe4)
well i am using  chrome in linux and it is rendering downwards same in gitpod.

**Comment by Nayanchandrakar** [comment]
Hii its just working fine my **linux fedora 39** 

Here is the proof: -
![Screenshot from 2024-04-20 12-53-01](https://github.com/calcom/cal.com/assets/100008163/45689447-76f0-430f-8fe3-710708287390)

**Comment by Amit91848** [comment]
Related #14132 ?

I can only reproduce it when you click the dropdown and then resize the window.

**Comment by smk1993** [comment]
Raised a PR for the same please review
