### ISSUE TITLE
Private URL in event type not working and changes on tab change

### ISSUE THREAD

**Issue by SaurabhGurde** [calcom/cal.com#14654]
Private url in event type is not working and when you change tab and come back again the url gets changed.
1) copy private url in advanced tab and search and it doesent work
2) change the tab and again come back in advanced tab
3) the private url gets changed
4) search the new url and again it doesent work

https://github.com/calcom/cal.com/assets/128987288/56bd98d9-b8f8-4b18-b4f2-c61c70e2e582

Uploading Event Types _ Cal.com - Brave 2024-04-18 16-00-26_resized.mp4…

**Comment by Amit91848** [comment]
@SaurabhGurde  That is the intended behavior, unless you save the event type after creating a private URL, changing tabs would create different links.

**Comment by SaurabhGurde** [comment]
> @SaurabhGurde That is the intended behavior, unless you save the event type after creating a private URL, changing tabs would create different links.

I saved the changes but still same error. url doesent work shows 404 error and url gets changed after tab change

**Comment by ayushhunt** [comment]
![image](https://github.com/calcom/cal.com/assets/87143358/0c1b5502-11bc-43ce-9859-8c2b3a3d2545)
After saving the private links, it works but in the calendar sidebar there's a cal video icon which I think is not clickable.

**Comment by Nayanchandrakar** [comment]
@

> > @SaurabhGurde That is the intended behavior, unless you save the event type after creating a private URL, changing tabs would create different links.
> 
> I saved the changes but still same error. url doesent work shows 404 error and url gets changed after tab change

yeah its not working in my browser also i checked this issue

**Comment by Nayanchandrakar** [comment]
reference how private url works :-
`https://cal.com/docs/core-features/event-types/single-use-private-links`
