### ISSUE TITLE
[CAL-3498] Can't select end of month dates when creating a new OOO entry 

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#14661]
### Issue Summary

When creating a new OOO entry, I can't seem to be able to click on last row of days.

### Steps to Reproduce

1. Went to http://ooo.new 
2. Clicked on New
3. Tried to select desired dates. April 29th in this specific case

### Actual Results

- Can't select desired dates

### Expected Results

- To be able to select from April 29th to May 3rd.

### Technical details

- Browser version, Safari Versión 17.4.1 (19618.1.15.11.14)

### Evidence

https://github.com/calcom/cal.com/assets/3504472/384f0d08-4618-44d7-87db-788ebb9d7c3d

<sub>[CAL-3498](https://linear.app/calcom/issue/CAL-3498/cant-select-end-of-month-dates-when-creating-a-new-ooo-entry)</sub>

**Comment by Yash-271120** [comment]
Hi I am using chrome, it is working fine on my end. Also tried to run it in the development environment works fine.

**Comment by rudrasgithub** [comment]
Yeah, from my side also it's working

**Comment by Yash-271120** [comment]
@rudrasgithub did you try it on safari? may be its a safari specific issue?

**Comment by Amit91848** [comment]
Breaking in safari works properly if you open it using the calendar icon.

Related issues:

https://github.com/wojtekmaj/react-date-picker/issues/274

https://github.com/wojtekmaj/react-date-picker/issues/288

https://github.com/wojtekmaj/react-datetimerange-picker/issues/48

**Comment by sean-brydon** [comment]
Seems like this is a safari only issue and is a problem with an external package. Will look at changing this out to see if this fixes the issue

**Comment by ciaranha** [comment]
> Seems like this is a safari only issue and is a problem with an external package. Will look at changing this out to see if this fixes the issue

I can recreate this on Arc and we've also had it reported from an Android
