### ISSUE TITLE
[CAL-3502] Challenge: Check In App

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14676]
# What's a challenge?

A challenge is a larger bounty that can turn into a proper startup. It'll be built outside of [Cal.com](http://Cal.com) but either uses [cal.com](http://cal.com) or is an app for the [https://cal.com/app](https://cal.com/app) store.

# Challenge: Check In

![CleanShot 2024-04-20 at 11 46 34@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e918392f-36c8-4e3a-861e-63ba423573eb/05fe9408-9b47-42c8-b384-16015efd04c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lOTE4MzkyZi0zNmM4LTRlM2EtODYxZS02M2JhNDIzNTczZWIvMDVmZTk0MDgtOWI0Ny00MmM4LWIzODQtMTYwMTVlZmQwNGM2IiwiaWF0IjoxNzEzNjEwMjk3LCJleHAiOjE3MTM2OTY2OTd9.TOPENYBnKkH8HLqy0NLi4CgCdMdDF2e-TFwhhidBOO4)

I would love to use an app called "checkin.app" or similar where I can submit a list of [Cal.com](http://Cal.com) links (contacts) that i know, i.e. friends, coworkers, family members and a duration of how many times i want to check in with them (often, every now and then, rarely).

It should not be a recurring event (that's kinda cringe to call your friend every monday at the same time -- they are not your tennis trainer)

It should be a somewhat more random. Important is, it needs to check your calendar (your [cal.com](http://cal.com) link) and their persons [cal.com](http://cal.com) link (again, you should be able to submit it)

you can add auth and save records on a db as well if you want to. if not, just save everything in localStorage and tell people your links are not saved anywhere if you wanna go fast. but i guess a db is better long-term

It has to work and look good, feel free to use shadcn/ui to get something out quick. In this repo, only open an "App Store" entry that links to your production app.

## Reward:

The best implementation wins $1000.

If you end up starting an open source business around this (think [https://www.donut.com/](https://www.donut.com/) for your friends, family and coworkers) I will invest $10k as the first check.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3502](https://linear.app/calcom/issue/CAL-3502/challenge-check-in-app)</sub>

**Comment by PeerRich** [comment]
$100 bonus if you livestream it on https://tv.algora.io while building it!

**Comment by PeerRich** [comment]
If you want to submit an App to our App Store, use https://cal.com/docs/how-to-guides/app-store-and-integrations/how-to-build-an-app#steps-in-creating-an-app

and use "link-as-an-app" and link to your production ready app. make sure to add screenshots and description to your app store entry

![CleanShot 2024-04-20 at 12 00 33@2x](https://github.com/calcom/cal.com/assets/8019099/a91f354e-032f-4a99-9e62-4e39e0cc7090)

**Comment by syedbarimanjan** [comment]
@PeerRich does it have to be an app or is it on us?

**Comment by PeerRich** [comment]
> @PeerRich Nice Idea!. Does it have to be an app or we are free to make anything we want? If an app, are there any ristrictions as to what technology or which app store we have to use?

it should be a webapp (nextjs or similar)

not a phone app

**Comment by syedbarimanjan** [comment]
> > @PeerRich Nice Idea!. Does it have to be an app or we are free to make anything we want? If an app, are there any ristrictions as to what technology or which app store we have to use?
> 
> it should be a webapp (nextjs or similar)
> 
> not a phone app

can I contact you on discord for further details?

**Comment by PeerRich** [comment]
> > > @PeerRich Nice Idea!. Does it have to be an app or we are free to make anything we want? If an app, are there any ristrictions as to what technology or which app store we have to use?
> > 
> > 
> > it should be a webapp (nextjs or similar)
> > not a phone app
> 
> can I contact you on discord for further details?

not very active on discord feel free to reply here or email me peer@cal.com

**Comment by justrach** [comment]
Hey guys, I have a few questions with regards to this:
What I am currently trying to do on the backend is the following:
1. Check availability of the users
2. Create an event which uses an algorithm to match the user to the respective N people in the field
3. Send them a booking

However, I am having issues with the endpoint https://api.cal.com/v1/availability/? <- as it breaks often(2/3 tries go through)<Tried it with Javascript libs (fetch only)<Axios works>>

```
Malformed_HTTP_Response: fetch() failed. For more information, pass `verbose: true` in the second argument to fetch()
```

Furthermore, when I try to use the bookings API i realise that the API key that is inputted only allows me to book events which the user has access to(event ID etc), is there a way to get this for any user, or would users have to input their API keys when using the said application?

E.g. When creating a booking via the `/bookings` endpoint:

```javascript
const booking = {...   
"eventTypeId": 684791...}

// the above eventTypeID is unique to every user, and the only way it seems from the docs is https://cal.com/docs/enterprise-features/api/api-reference/event-types#find-an-event-type 
// is to use /event-types to get all the user's events and store them prior to booking

```

Any help would be appreciated!

**Comment by syedbarimanjan** [comment]
@PeerRich Could you please set a deadline for submissions? After the deadline, you'll review all entries and select the best one. I'm currently working on my submission, and I'd appreciate the opportunity to have it considered.

**Comment by Ash-2k3** [comment]
Great project idea. I have also started working on it, expecting a couple of days more to finish it (I have my exams going on, so taking my time :) )

**Comment by syedbarimanjan** [comment]
> Great project idea. I have also started working on it, expecting a couple of days more to finish it (I have my exams going on, so taking my time :) )

@PeerRich it would be great if you set a deadline so we can catchup

**Comment by zmzlois** [comment]
> > Great project idea. I have also started working on it, expecting a couple of days more to finish it (I have my exams going on, so taking my time :) )
> 
> @PeerRich it would be great if you set a deadline so we can catchup

@syedbarimanjan but if he set the deadline how would he be able to wait and see what's the best out there?
