### ISSUE TITLE
[CAL-3746] Top right section overflows in Event page

### ISSUE THREAD

**Issue by Afrin127329** [calcom/cal.com#14682]
### Issue Summary

Not sure if this is a browser issue or not. But it kinda looks ugly when top right section is overflowing and it's blocking the stuff below it. Here are the examples. 

![cal2](https://github.com/calcom/cal.com/assets/125039325/6119cac1-96ea-4f30-ad58-fe6a6d4df149)
![cal3](https://github.com/calcom/cal.com/assets/125039325/e3bb392f-16ff-4ab1-a3d6-b7ef307800e3)

### Steps to Reproduce

1. login
2. Open any event link

### Expected Results

- The main section could use some more space at the top.

### Technical details

- Browser Mozilla, Chrome

<sub>[CAL-3746](https://linear.app/calcom/issue/CAL-3746/top-right-section-overflows-in-event-page)</sub>

**Comment by heykvr** [comment]
I would like to work on this issue @dosu

**Comment by PeerRich** [comment]
you are right, we need to have more padding at the top for smaller devices in height. adding to roadmap for this month
