### ISSUE TITLE
[CAL-3505] Issue with Webhooks (Meeting started/ended triggers)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14685]
> Hello!
> 
> Currently, after communicating with Zapier support, we have received information from them indicating that the error is likely on your side:
> 
> "We've checked the bug report filed for the Cal.com team and there is no update yet.
> ​
> As Ian mentioned, I might suggest you check with the Cal.com support team, if there might be some settings in Cal.com or some differences with particular meetings that could be preventing Cal.com from sending these notifications to Zapier. "
> 
> The situation is as follows:
> 
> - When scheduling a meeting, information is pulled from Calcom into our CRM ("Trial booked" status).
> - When canceling a meeting or successfully completing a meeting, information from Calcom is not pulled into our CRM (statuses "Canceled" and "Past").
> 
> That is, with the standard "Meeting Ended" event, information from Calcom is only transferred in 5-10% of cases.
> Since April 14th, only 4 users have had information pulled: 1799211, 1777800, 1763228, 1763963.
> 
> Please verify the information and provide a response as soon as possible.

<sub>[CAL-3505](https://linear.app/calcom/issue/CAL-3505/issue-with-zapier)</sub>

**Comment by capitanes** [comment]
Hello, do you have any idea about the approximate timeline for when you will be able to fix the bug? We have been waiting for a solution for over a month now. We have reached out to both Zapier and you, but there has been no result.

**Comment by milospuac** [comment]
@CarinaWolli have you had the time to look into this?

**Comment by CarinaWolli** [comment]
> @CarinaWolli have you had the time to look into this?

I am actively looking into that, but was not able to identify the issue yet why not all of your bookings trigger your zap. I am still on it

**Comment by CarinaWolli** [comment]
@capitanes I found the issue why the 'meeting ended' trigger is not working all the time. I am working on a fix for it

**Comment by capitanes** [comment]
Please, fix interation module "meeting ended" он Zapier, becouse its works with errors. https://prnt.sc/Hp9D6ZMJXb-Z

**Comment by CarinaWolli** [comment]
> Please, fix integration module "meeting ended" он Zapier, becouse its works with errors. [prnt.sc/Hp9D6ZMJXb-Z](https://prnt.sc/Hp9D6ZMJXb-Z)

What error are you getting?

**Comment by capitanes** [comment]
When I want to receive a test event to set up integration, I receive events of type "booking" instead of "meeting ended," which results in me getting the wrong set of data and unable to set up the integration.
https://prnt.sc/C7hQLkdbsjcz

**Comment by CarinaWolli** [comment]
> When I want to receive a test event to set up integration, I receive events of type "booking" instead of "meeting ended," which results in me getting the wrong set of data and unable to set up the integration.

There is an issue open for that: https://github.com/calcom/cal.com/issues/14776

Until then, you can still use any field that is coming in when the zap triggers. Here it's explained how to manually add variables: https://community.zapier.com/how-do-i-3/zapier-test-data-does-not-match-live-data-20869

**Comment by capitanes** [comment]
Thank you for the feedback. I'm glad the instructions helped with setting up the integration. However, we have noticed another issue with transmitting the "meeting ended" event through Zapier. Since my last message, 13 events have been completed in the Cal.com account, but none of them were transmitted to Zapier. There are no errors, they simply appear to be missing.

I can provide you with more information about the account if you contact me via email at ruslansungurov@gmail.com.

**Comment by capitanes** [comment]
@CarinaWolli Hello. Could you give me some guidance on the timing of solving the problem I mentioned above?

Yesterday, some data about "meeting ended" was transmitted through Zapier, but then it stopped being transmitted and has not been transmitted since then

**Comment by CarinaWolli** [comment]
@capitanes this should be fixed in our next release, #14864 is not yet in production. We should have a release today or tomorrow
