### ISSUE TITLE
[CAL-3509] Missing metadata for matomo

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14688]
https://app.cal.com/apps/matomo has no logo, no screenshots and no description

<sub>[CAL-3509](https://linear.app/calcom/issue/CAL-3509/missing-metadata-for-matomo)</sub>

**Comment by PeerRich** [comment]
![logo](https://github.com/calcom/cal.com/assets/8019099/4ee8babf-4afd-4c83-9a1d-e5b3d46e758b)

**Comment by PeerRich** [comment]
![image](https://github.com/calcom/cal.com/assets/8019099/34b1407c-14b5-497a-89bd-73620687982b)

**Comment by Amit91848** [comment]
Couldn't reproduce

![Screenshot 2024-04-22 at 10 20 17 AM](https://github.com/calcom/cal.com/assets/74371312/d55760ff-0215-45ec-b87d-2f26ad1c728a)

**Comment by priyanshu2k3** [comment]
@PeerRich what is the issue . there is logo ,description and one screenshot also .
