### ISSUE TITLE
[CAL-3510] bug: bookings tab is only showing a single team members events

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14689]
Seems the Bookings tab is only now showing a single team member's calendar events instead of all members like it's supposed to. The filter is currently set to all.

<sub>[CAL-3510](https://linear.app/calcom/issue/CAL-3510/bug-bookings-tab-is-only-showing-a-single-team-members-events)</sub>

**Comment by Amit91848** [comment]
It was reverted here #14561
