### ISSUE TITLE
[CAL-3889] Events with multiple seats become unavailable every time someone makes a booking

### ISSUE THREAD

**Issue by dreadted** [calcom/cal.com#14704]
### Issue Summary

As soon as a guest books a seat for a multi guest event, and the event is created in Google Calendar, the event also disappears from the available events calendar as if it were fully booked. If the Google Calendar event is deleted, the event becomes open for booking again, until next guest makes a reservation.

### Steps to Reproduce

1.  Go to [this calendar](https://cal.com/antropomorf/gubbangen) and book the first available event (should say 8 available seats)

2. When the booking is made, the event disappears altogether, instead of showing 7 available seats.

3. If the event is deleted from the linked Google Calendar, the event becomes available for one more booking, and then disappears again.

### Actual Results

Events with multiple seats become unavailable for booking immediatly after the first seat is taken

### Expected Results

Events with multiple seats should be available for booking until all seats are taken.

### Technical details

This is on the cal.com platform, not a standalone system.

<sub>[CAL-3889](https://linear.app/calcom/issue/CAL-3889/events-with-multiple-seats-become-unavailable-every-time-someone-makes)</sub>

**Comment by Stupac** [comment]
I"m having this same issue. Tried creating an event that had 30 seats open, but the moment the first person signed up, it closed the event on the calendar.

**Comment by Vincentig** [comment]
@dosu

I have same problem, seatsPerTimeSlot is set to 10 in my event.
But when the first person sign in, the event disapear in cal.com reservation page. 

In my google calendar, the event is still here but in busy state. 

If I switch it to available in google calandar, it come back in cal.com reservation page.

**Comment by guillaume-ro-fr** [comment]
I downgraded to version 3.9.8, and the problem disappeared.
Google Calendar + On-premise

**Comment by Vincentig** [comment]
This feature is unusable right now, I must check everyday to activate by hand the event. I probaly loose registration to my event ....

**Comment by keithwillcode** [comment]
Hey @CarinaWolli could you please take a look at this one?

**Comment by CarinaWolli** [comment]
> Steps to Reproduce
> Go to [this calendar](https://cal.com/antropomorf/gubbangen) and book the first available event (should say 8 available seats)
> 
> When the booking is made, the event disappears altogether, instead of showing 7 available seats.
> 
> If the event is deleted from the linked Google Calendar, the event becomes available for one more booking, and then disappears again.

I tested this on my account and on  [this calendar](https://cal.com/antropomorf/gubbangen) and it worked fine. Looks like this issue has been fixed. If you are still experiencing issues with that feel free to reopen 🙏

**Comment by matthew-lim-matthew-lim** [comment]
This is still an issue. I am experiencing it on Cal.com. Please re-open the issue. If you look at the `troubleshoot` section, the booking takes an entire slot.
