### ISSUE TITLE
[CAL-3516] During signup add a user to an organization based on email

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#14711]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3516](https://linear.app/calcom/issue/CAL-3516/during-signup-add-a-user-to-an-organization-based-on-email)</sub>

**Comment by heykvr** [comment]
@hariombalhara  can i pick this up?

**Comment by Preetam078** [comment]
hii @hariombalhara how can i get the access for [SyncLinear.com](https://synclinear.com/) to view the issue details for contribution ?

**Comment by Amit91848** [comment]
> hii @hariombalhara how can i get the access for [SyncLinear.com](https://synclinear.com/) to view the issue details for contribution ?


@Preetam078 that is just for tracking issues, it doesn't contain any additional details
