### ISSUE TITLE
[CAL-3883] Event booking - one input label lacks Polish translation

### ISSUE THREAD

**Issue by agilido** [calcom/cal.com#14734]
### Issue Summary

When booking a meeting, after choosing the hour, first input label is "Your name" instead of "Imię i nazwisko".

### Steps to Reproduce

1. Go to cal.com/(user)/(event)
2. Choose date and hour.

### Actual Results

- After choosing the hour, first input label is "Your name" instead of "Imię i nazwisko".

### Expected Results

- Input label "Your name" should say for Polish "Imię i nazwisko".

### Technical details

- Happens on every browser.

### Evidence

![image](https://github.com/calcom/cal.com/assets/75748053/caa0e8fe-022a-4006-ac70-1f5937836b45)

<sub>[CAL-3883](https://linear.app/calcom/issue/CAL-3883/event-booking-one-input-label-lacks-polish-translation)</sub>

**Comment by heykvr** [comment]
@dosu can i pick up this ?

**Comment by smitgol** [comment]
I found out found its not about the translation.

The issue is from configMap in fieldTypes.ts file. Where in name default Value is "Your Name" instead of your_name.And also when rendering name field in Component.tsx in formbuilder there we don't translating the any field Type variants.

**Comment by smitgol** [comment]
we can use this function getAndUpdateNormalizedValues(variantField, t) in Component.tsx file.But again we are only translating the defaultLabel not Label from configMap in fieldTypes.ts.So either we need to modify getAndUpdateNormalizedValues or add defaultLabel in defaultValue props in variants.

**Comment by smitgol** [comment]
tell me know which is better solution i will create pull request then

**Comment by smitgol** [comment]
#14863
