### ISSUE TITLE
[CAL-3526] /signup flickers i18n

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14733]
when visiting cal.com/sales the i18n strings flicker

https://github.com/calcom/cal.com/assets/8019099/b8e74aa7-856b-476f-8290-bbcef34b8497

<sub>[CAL-3526](https://linear.app/calcom/issue/CAL-3526/signup-flickers-i18n)</sub>

**Comment by ashishpooniaa** [comment]
attempt /#14733

**Comment by hbjORbj** [comment]
This issue will be gone once we migrate the page to app router.
