### ISSUE TITLE
Dashboard: Single use booking link

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1474]
Allow people to create disposable booking links, which don't give away their regular booking links.

**Comment by pietro14** [comment]
I think this would be a very useful feature!

**Comment by Jaibles** [comment]
@alishaz-polymath designs for this are now [here](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=5013%3A45828). There are one or two small final decisions to make about how to display the times and title with both options there but will be resolved in the next day or so and shouldn't be blocking for you to start. If you have any questions on this or want to sync up let me know!

**Comment by Jaibles** [comment]
Designs for this task are [here](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=5060%3A62515)

**Comment by ecam900** [comment]
Any news on when this will be implemented?

**Comment by Jaibles** [comment]
Hey @ecam900, we do have a feature that enables you to generate a one-off private link that doesn't expose you're personal URL. Would this meet your needs?
 
![CleanShot 2022-10-12 at 08 56 29@2x](https://user-images.githubusercontent.com/4536123/195284601-f857ef0c-65be-4018-9ff6-a1dd92e97be9.png)

If not, please let me know a little bit more about your intended use case!

**Comment by Jaibles** [comment]
cc @alishaz-polymath

**Comment by ecam900** [comment]
@Jaibles I want to be able to:

1. Send someone a one-time-use link, that I generate on the server.

2. I would then embed metadata into the generated link (some data pertaining to the appointment: e.g. orderID, requesterID, etc. ).

3. I want to then listen for webhooks, for when the event is scheduled, which would include the previously embedded Metadata, and execute business logic on my server.

**Comment by Jaibles** [comment]
@ecam900 thank you for clarifying. 🙏 Discussing with the team.

**Comment by PeerRich** [comment]
@ecam900 please open a new ticket for this so we can add an API endpoint for one-time links

**Comment by ecam900** [comment]
@PeerRich Will do - the title will be very similar to this one, which only deviates in the description of the issue. The implementation detail of hiding the event information is just an added constraint to the otherwise same task: an api endpoint that produces a one-time booking link.

With that being said, I'll open the ticket tomorrow.

Thanks again - if I get some free time, I will try to contribute towards this.

**Comment by ecam900** [comment]
> @ecam900 please open a new ticket for this so we can add an API endpoint for one-time links

https://github.com/calcom/cal.com/issues/5060#issue-1412218581

As requested!

**Comment by yamsu** [comment]
I would to see that if Generate Random link is enabled, then by default "copy link to event" and share options in app.cal.com provide the random link and not standard link with user info included.
