### ISSUE TITLE
[CAL-3854] App: Skype

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14747]
integrate with skype

https://www.skype.com/en/free-conference-call/

<sub>[CAL-3854](https://linear.app/calcom/issue/CAL-3854/app-skype)</sub>

**Comment by HyperDanisH** [comment]
There are very less resources about how to build an app for cal.com. Do you have any resources that can dive deep into it.

**Comment by mannyce** [comment]
I reckon it would be similar to how cal.com integrates with Microsoft Teams (work accounts). Microsoft has an API to enable creation of a Skype meeting or Microsoft Teams (personal accounts) meeting link for users authenticated to their account. I would suggest the same way you add a calendar to your Microsoft 365 account, you can do the same for your Outlook.com or Hotmail account and connect to this API. 

Details:
https://learn.microsoft.com/en-us/graph/choose-online-meeting-api
