### ISSUE TITLE
[CAL-3565] Improve Perform List endpoint for Zapier

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#14776]
The Perform List endpoint should check for recent items, to provide sample data in the Zap Editor. Currently /api/integrations/zapier/listBookings is used for all our Zapier triggers and it just returns the latest bookings. We should make sure that the exact same payload is returned as we do for when the zap is triggered. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3565](https://linear.app/calcom/issue/CAL-3565/improve-perform-list-endpoint-for-zapier)</sub>

**Comment by Narottamchy** [comment]
I will take a look onto it
