### ISSUE TITLE
More flexible "Invitees can schedule"

### ISSUE THREAD

**Issue by hammer** [calcom/cal.com#1478]
Thanks for the great open source product!

I would like to be able to limit the days on which invitees can schedule a meeting with more flexibility than is currently offered.

Currently, I can:
1. Choose a maximum limit of days relative to today.
2. Choose an absolute date range.

Here are a few things I'd like to be able to do:
1. Set a minimum limit of days relative to today. For example, don't allow meetings less than 5 days from today. `Minimum booking notice` could be used right now but its units are minutes, not days.
2. Allow meetings to be made only on a specific day of the week.

**Comment by PeerRich** [comment]
@Jaibles this would require the day-specific schedule feature that we were talking about

**Comment by Jaibles** [comment]
Work in progress designs are here: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6096%3A100073

**Comment by PeerRich** [comment]
new designs:

<img width="852" alt="CleanShot 2022-07-31 at 10 29 10@2x" src="https://user-images.githubusercontent.com/8019099/182017538-5d72b1de-578f-45e9-86fc-50e833dee705.png">
 
figma: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1526%3A76162

**Comment by ologbonowiwi** [comment]
I want to take a look at this one.

This should be on the Limits or on the Availability page? @PeerRich

**Comment by ologbonowiwi** [comment]
I ran some tests on the booking page, I could be wrong, but this one is already implemented. 

> 1. Set a minimum limit of days relative to today. For example, don't allow meetings less than 5 days from today. Minimum booking notice could be used now, but its units are minutes, not days.

We already have it 
<img width="642" alt="image" src="https://github.com/calcom/cal.com/assets/100464352/7da1e2ec-f0c3-4efe-a5b0-d26a9ee7a10d">
Unless we want to add more options (like months/years), it looks like it's already implemented.


> 2. Allow meetings to be made only on a specific day of the week.

Technically we can do it by editing the availability. Do we want to create a mechanism that overrides the availability here? In my opinion, we shouldn't; if we want, we'll need to dig deep into HOW we'll do it and any limitations/contradictions that this implementation could bring (by user error on inputting the data/setting the general availability and the weekday availability).

If we don't consider this one closed, we'll need an updated Figma design and get some discussions about what should be implemented. Any thoughts @PeerRich?

**Comment by gracebir** [comment]
@PeerRich is the figma design of this one available?

**Comment by ologbonowiwi** [comment]
@PeerRich can you confirm that we still need this and send the Figma or any specification that needs to be implemented?

**Comment by Jaibles** [comment]
@ologbonowiwi I think we can close this as done it's covered for the reasons you outlined.
