### ISSUE TITLE
[CAL-3581] [Api][v2] getEventType endpoint should be client agnostic

### ISSUE THREAD

**Issue by ThyMinimalDev** [calcom/cal.com#14798]
* remove getUserEventTypeForAtom
* get a standard event-type entity

formatting should be done inside of the hooks

* useGetEventTypeById

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3581](https://linear.app/calcom/issue/CAL-3581/[api][v2]-geteventtype-endpoint-should-be-client-agnostic)</sub>

**Comment by martinsione** [comment]
Is this being worked on and also is this open to community contributions? I'd love to contribute
