### ISSUE TITLE
[CAL-3576] App: Dialpad Conferencing

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14792]
https://www.dialpad.com/partners/integration-partners/

<sub>[CAL-3576](https://linear.app/calcom/issue/CAL-3576/app-dialpad-conferencing)</sub>

**Comment by Saisreeja5** [comment]
Can someone explain the issue

**Comment by Saisreeja5** [comment]
@PeerRich hello sir,can you please explain the issue?

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan hello ..can you please explain the issue?

Hey we have to build an app for the cal.com app store which will integrate dialpad conferencing.

**Comment by Saisreeja5** [comment]
> > @syedbarimanjan hello ..can you please explain the issue?
> 
> Hey we have to build an app for the cal.com app store which will integrate dialpad conferencing.

Thank you for the answer..

**Comment by syedbarimanjan** [comment]
@PeerRich to get an api key i will have to signup which needs billing information, could you get me the api key so i can test with it and can you specify that we only need to get the conferencing details and mark those dates as reserved in cal.com calender or we have to do more.thanks.

**Comment by princyym** [comment]
Dear @PeerRich,

I am eager to work on the issue. To begin the integration process, I must create an account on Dial Pad. However, I am encountering an issue as Dial Pad doesn't offer India as a country option. Please provide me with the information needed to resolve this issue.

Thank you for your time and assistance.

Best regards,
Princy Mangla

**Comment by Asmitpadia** [comment]
Can i use zoom to build it instead of dialpad
