### ISSUE TITLE
Error when booking on January (Month 1) 

### ISSUE THREAD

**Issue by parapar** [calcom/cal.com#1479]
Our installation of v1.1 is breaking and cannot render the success view and a booking when a booking is requested in January. It works ok in February and the following months. Even when the booking is created in DB, the mails are not sent, and the user can not see the message with the success of the booking. After some debugging, it seems related to some validation on the month in the start date: 

> 
Object { value: {…}, path: undefined, type: undefined, errors: (1) […], params: undefined, inner: (1) […], name: "ValidationError", message: "start[1] must be greater than or equal to 1" } (framework-d9c9992982ceff03.js:formatted:4279)

start[1] is the month that it seems indexed starting on 0 (January) when the validator is testing to be greater than or equal to 1.

**Comment by PeerRich** [comment]
have you tried the latest github pull? I believe this was fixed

**Comment by PeerRich** [comment]
btw. the next tagged release v.1.2 is coming out in 3 days.

**Comment by PeerRich** [comment]
i think this was fixed a log time ago
