### ISSUE TITLE
[CAL-3582] refactor: packages/app-store/closecom/pages/setup/index.tsx

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14804]
NIT:

```suggestion
                  const url = new URL("/api/integrations/closecom/add");
                  if (returnTo) url.searchParams.append("returnTo", `${returnTo}`);
                  const res = await fetch(url.href, {
```

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/14450#discussion_r1578149725_
            

<sub>[CAL-3582](https://linear.app/calcom/issue/CAL-3582/refactor-packagesapp-storeclosecompagessetupindextsx)</sub>

**Comment by mritosa** [comment]
@PeerRich is this issue still open? I would like to contribute to it if its possible.
