### ISSUE TITLE
[CAL-3596] wrong avatars

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14828]
- [ ] webhooks

![CleanShot 2024-05-01 at 09 13 06@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3a5014cb-67ce-4b52-b2fe-b95ced49475f/5c11172d-2013-4ce4-914b-7f5947282cb3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zYTUwMTRjYi02N2NlLTRiNTItYjJmZS1iOTVjZWQ0OTQ3NWYvNWMxMTE3MmQtMjAxMy00Y2U0LTkxNGItN2Y1OTQ3MjgyY2IzIiwiaWF0IjoxNzE0NTQ4MTcxLCJleHAiOjE3MTQ2MzQ1NzF9.8PBrGFUjcMfbFohZZPMWWp7o_Dx2EIRLh-foQW37tL0)

![CleanShot 2024-05-01 at 09 12 45@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e48ea367-1771-4b88-ac88-8f94f859f7f7/a25b499b-16cc-4c2f-b95a-770d12bdb6b8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNDhlYTM2Ny0xNzcxLTRiODgtYWM4OC04Zjk0Zjg1OWY3ZjcvYTI1YjQ5OWItMTZjYy00YzJmLWI5NWEtNzcwZDEyYmRiNmI4IiwiaWF0IjoxNzE0NTQ4MTcxLCJleHAiOjE3MTQ2MzQ1NzF9.EqxmqV-EEic3P17lSZGyaV0Vo3dKWP3S36mRlulJV-I)

![CleanShot 2024-05-01 at 09 13 32@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d0e0bcbc-cd32-4bd9-bd69-aafa6c0117f7/97230b64-cf76-4bf1-b18a-6dd6dc8eef5d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kMGUwYmNiYy1jZDMyLTRiZDktYmQ2OS1hYWZhNmMwMTE3ZjcvOTcyMzBiNjQtY2Y3Ni00YmYxLWIxOGEtNmRkNmRjOGVlZjVkIiwiaWF0IjoxNzE0NTQ4MTcxLCJleHAiOjE3MTQ2MzQ1NzF9.sD-3VW4vP0Hr5Z-zS6VMKjI1UbLosWp475Sfj9Tecw4)

- [ ] Routing forms

![CleanShot 2024-05-01 at 09 13 49@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e762862f-839f-4496-b155-1cb46c7bdc12/2003368f-04db-4fcf-a0bd-ea7bac123bf6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNzYyODYyZi04MzlmLTQ0OTYtYjE1NS0xY2I0NmM3YmRjMTIvMjAwMzM2OGYtMDRkYi00ZmNmLWEwYmQtZWE3YmFjMTIzYmY2IiwiaWF0IjoxNzE0NTQ4MTcxLCJleHAiOjE3MTQ2MzQ1NzF9.OqoZ9aMVhPpoGph408FEDzNl3IV2DXV0VMD-dy8zCao)

\- \[ \] Workflows

![CleanShot 2024-05-01 at 09 14 18@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/948f5159-21b6-40dc-afc0-4f1b1c58045c/57b2739e-5f19-4076-8306-78b26f766c04?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NDhmNTE1OS0yMWI2LTQwZGMtYWZjMC00ZjFiMWM1ODA0NWMvNTdiMjczOWUtNWYxOS00MDc2LTgzMDYtNzhiMjZmNzY2YzA0IiwiaWF0IjoxNzE0NTQ4MTcxLCJleHAiOjE3MTQ2MzQ1NzF9.8kGMN5kD1aYkkmHibuf-7U8GF1KxtAFLf0QqiEwd4b4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3596](https://linear.app/calcom/issue/CAL-3596/wrong-avatars)</sub>

**Comment by Bhanubediya** [comment]
is this issue still available and may ik where exactly the issue is in the image ?. As I'm new to this project. @PeerRich

**Comment by ninadvyas** [comment]
Hello I would like to work on this issue.
