### ISSUE TITLE
[CAL-3595] Org-Wide Webhooks

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14827]
Add your Org to the webhook dropdown

![CleanShot 2024-05-01 at 09 11 16@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3d42d23a-a5fe-4e48-b102-83c87dd2d679/97ca1d31-917a-4e67-a18e-d4a2ea27a918?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zZDQyZDIzYS1hNWZlLTRlNDgtYjEwMi04M2M4N2RkMmQ2NzkvOTdjYTFkMzEtOTE3YS00ZTY3LWExOGUtZDRhMmVhMjdhOTE4IiwiaWF0IjoxNzE0NTQ3NTExLCJleHAiOjE3MTQ2MzM5MTF9.TF-Zlu6Ld6-uiWm0z21NJKNnHfSPBoG33j1ZpEBMS-M)

![CleanShot 2024-05-01 at 09 12 31@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0076cc97-52e3-4612-bb5a-43dffe13cd56/dd728292-50d3-408a-a515-ff6d7defee62?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wMDc2Y2M5Ny01MmUzLTQ2MTItYmI1YS00M2RmZmUxM2NkNTYvZGQ3MjgyOTItNTBkMy00MDhhLWE1MTUtZmY2ZDdkZWZlZTYyIiwiaWF0IjoxNzE0NTQ3NTY0LCJleHAiOjE3MTQ2MzM5NjR9.s5qXfb72bzUOOaE7ppmC35JE_cZZKJg8sJrCwTQkjRg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3595](https://linear.app/calcom/issue/CAL-3595/org-wide-webhooks)</sub>

**Comment by kart1ka** [comment]
Will org-wide webhooks be triggered by bookings for all team events and all org members, or only by bookings for all team events within that org?

**Comment by CarinaWolli** [comment]
Org-wide webhooks will trigger for all team events and all org members
