### ISSUE TITLE
Cal.com website breaks when language change button pressed

### ISSUE THREAD

**Issue by thepradipvc** [calcom/cal.com#14826]
### Issue Summary

On the homepage of Cal.com. When I press the language change button in the footer, the website breaks saying a client-side exception happened.

### Steps to Reproduce

1. Go to the footer of the Cal.com website
2. Press the button saying "English" and the languages icon.
3. The website breaks.

### Actual Results

The website is breaking with a client-side exception.

### Expected Results

There should be an option to change the language

### Technical details

- Happening in all the latest browsers.

### Evidence

https://www.loom.com/share/8873a67ae3914fb498051824cdd9e6a8?sid=839d0754-9050-4cdb-8938-db7818108ec8

**Comment by thepradipvc** [comment]
I was trying to find the code for this but couldn't. Then I stumbled upon the cal.com handbook where there is a mention of the website app. But I couldn't find any app named website. Is is not public or what?
![image](https://github.com/calcom/cal.com/assets/88336529/7cbc1aa4-5e4f-4104-a053-b6b1411fb413)

**Comment by mritosa** [comment]
Hey , Im new to the Open source contributing. I would like to solve this issue if it's possible. Do I need some approval or I can just fork the project and try to fix the issue?

**Comment by thepradipvc** [comment]
Thank you @kmakkar20213 for updating the status. I'm closing this issue.
