### ISSUE TITLE
CAL-831: Team invite email not sent

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1483]
During a test with @emrysal we had no email notification of his pending invite to my team. Needs urgent investigation.

**Comment by jamiepine** [comment]
Just tested this in prod and it seems to be working fine. 
- Tested inviting to both roles `member` and `admin`.
- Tested inviting existing and non existing accounts.

Received all invite emails, closing this for now.

**Comment by PeerRich** [comment]
@sydwardrae is still experiencing this issue

**Comment by joeauyeung** [comment]
@PeerRich can I close this issue? I've seen that it's been opened and closed before.

I tested this locally and in production and it seems to be working.
