### ISSUE TITLE
[CAL-3606] Team events: go to Assignment tab after creation and warn if existing without assigning

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#14848]
For team event-types, after clicking "continue"

![CleanShot 2024-05-01 at 19 27 03@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/acdcbcb3-664a-4689-a589-a8d06becf02f/5d0f2207-7187-4c9a-8e29-ba432383f915?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hY2RjYmNiMy02NjRhLTQ2ODktYTU4OS1hOGQwNmJlY2YwMmYvNWQwZjIyMDctNzE4Ny00YzlhLThlMjktYmE0MzIzODNmOTE1IiwiaWF0IjoxNzE0NTg0NTE3LCJleHAiOjE3MTQ2NzA5MTd9.ZYCpsVrjhDzt_beR2I8ryXTF1dWP3NJGn92WXmZWQmo)

It should bring you directly to the **Assignment** tab instead of the **Event Setup** tab

![CleanShot 2024-05-01 at 19 27 28@2x](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/401c998c-b9a8-4e58-a013-055dce2d364b/28b1f085-b157-4215-a8b8-d6bbadc7035d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80MDFjOTk4Yy1iOWE4LTRlNTgtYTAxMy0wNTVkY2UyZDM2NGIvMjhiMWYwODUtYjE1Ny00MjE1LWE4YjgtZDZiYmFkYzcwMzVkIiwiaWF0IjoxNzE0NTg0NTE3LCJleHAiOjE3MTQ2NzA5MTd9.Y_UuOrl3jlSMcAvntFjqKGtGCUEmBDg7oa6fih8M5js)

If you try to exit out of an event type without assigning anyone, we should [throw a modal warning that you have not assigned anyone](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=6279-62333&mode=design&t=jgaz5OvjQRqyaTRC-11). 
![CleanShot 2024-05-03 at 10 23 00@2x](https://github.com/calcom/cal.com/assets/4536123/db815a49-490d-4e80-85b0-315c1bdeb484)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3606](https://linear.app/calcom/issue/CAL-3606/team-events-include-assignment-in-event-type-creation-dialog)</sub>

**Comment by ciaranha** [comment]
Is this better than landing them on the assignment tab?
