### ISSUE TITLE
[CAL-3602] Sender ID info not shown on hover

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#14842]
Hovering over the info icon doesn't show sender ID explanation. Also, should be in line with the text before it.

It should show the translation for sender_id_info:

"sender_id_info": "Name or number shown as the sender of an SMS (some countries do not allow alphanumeric sender IDs)",

![Screenshot 2024-05-01 at 10.08.53 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d893c522-4e97-477d-a773-fa99bbe13609/3c01a360-7d67-4185-8fcc-6b449b8bc264?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kODkzYzUyMi00ZTk3LTQ3N2QtYTc3My1mYTk5YmJlMTM2MDkvM2MwMWEzNjAtN2Q2Ny00MTg1LThmY2MtNmI0NDliOGJjMjY0IiwiaWF0IjoxNzE0NTcyNjg2LCJleHAiOjE3MTQ2NTkwODZ9.DyRa3oZj7bAoPWnwdjYVycnV-OAx1POHzF-wPCuU2g0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3602](https://linear.app/calcom/issue/CAL-3602/sender-id-info-not-shown-on-hover)</sub>

**Comment by AnkityadavIITR** [comment]
@CarinaWolli is this issue still open?

**Comment by CarinaWolli** [comment]
> @CarinaWolli is this issue still open?

There is all a PR up to fix this: https://github.com/calcom/cal.com/pull/14846
