### ISSUE TITLE
[CAL-3607] Scroll to time slots on booking page (Mobile size)

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#14851]
* Scroll till first slot only or scroll only after clicked on a date

![Screenshot 2024-05-02 at 1.26.35 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3cf29731-343d-4535-b5e1-8ec94d01779d/f2011602-a1f2-4c24-98b7-156652ec04da?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zY2YyOTczMS0zNDNkLTQ1MzUtYjVlMS04ZWM5NGQwMTc3OWQvZjIwMTE2MDItYTFmMi00YzI0LTk4YjctMTU2NjUyZWMwNGRhIiwiaWF0IjoxNzE0NjM2NzEwLCJleHAiOjE3MTQ3MjMxMTB9.Yv1C6Zr7AEtpl5p_DCi9BNSvhxUg7gcDPuFCjDEDmZY)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3607](https://linear.app/calcom/issue/CAL-3607/scroll-to-time-slots-on-booking-page-mobile-size)</sub>

**Comment by smitgol** [comment]
i have idea.In mobile we can have time slot on hourly basis and when user click on any slot we show exact time slot.This way we minimize time slots on ui
