### ISSUE TITLE
[CAL-3615] Update create and update event APIs in v1 to use start and end dates

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#14855]
"Good Morning-

It appears as the git for [cal.com](http://cal.com/) is missing some key features

1. In the create event API there are no start date & end date params.
2.  In the update event API there are no start date & end date params.

Looking forward to a solution."

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3615](https://linear.app/calcom/issue/CAL-3615/update-create-and-update-event-apis-in-v1-to-use-start-and-end-dates)</sub>

**Comment by hjain5164** [comment]
@keithwillcode I would like to work on this task. But I am little unclear on the ask. Are you talking about the Workflow page or the creation of new event type or am I missing something else here?

**Comment by Bhanubediya** [comment]
@keithwillcode can you elaborate more on this feature ?
