### ISSUE TITLE
UI breaking in AddActionDialog on reducing window height

### ISSUE THREAD

**Issue by utkershrajvenshi** [calcom/cal.com#14875]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On reducing window height, the AddActionDialog component doesn't show full content as the view isn't scrollable.

[Screencast from 2024-05-04 19-22-04.webm](https://github.com/calcom/cal.com/assets/79559223/643629de-ce3e-4d55-b0ee-a5968fb17515)

### Steps to Reproduce

1. Go to 'Workflow' -> Add/Update a workflow
2. Click on 'Add action'
3. Reduce the browser window height manually or from responsive view in Chrome DevTools and notice that partial information is shown to the user.

### Actual Results

- Due to absence of scroll behaviour in this view, complete content is not being shown

### Expected Results

- Dialog view should be scrollable like in `DateOverrideForm`

### Technical details

- Browser version: Chrome v123.0.6312.58
- Node.js version: v20.12.2

### Evidence

- Bug was tested using Responsive View in Chrome DevTools.

**Comment by raza001** [comment]
#14883
