### ISSUE TITLE
[BUG]:Time Zone Update Toast , Not disappear ... 

### ISSUE THREAD

**Issue by raza001** [calcom/cal.com#14881]
When I update the time zone on cal.com, it will show the toast in the bottom center, but it is stuck on the screen and does not disappear.
For ref -
`https://www.loom.com/share/4ed8779d814949f08da941d9b0d5cd44`

**Comment by smitgol** [comment]
i'll check this one

**Comment by infysumanta** [comment]
Hi @PeerRich , is anyone working on this bug? If not, could it be assigned to me?

**Comment by infysumanta** [comment]
@PeerRich the default TOAST visible duration is define so it should be an issue here i can see, seems to be some browser or dom related issue?

https://github.com/calcom/cal.com/blob/5c2b561a5c381171c99b338e20447f5085cc94d4/packages/ui/components/toast/showToast.tsx#L78-L87

@raza001 can you please share the issue in more details and process how the issue occurs? and reproduced steps.

**Comment by raza001** [comment]
I think it is a browser issue; it is working fine on Incognito
Pls , decrease TOAST_VISIBLE_DURATION

**Comment by infysumanta** [comment]
thanks @raza001 for the confirmation, but i guess 6 sec is normal time for a Toast.
