### ISSUE TITLE
[CAL-3655] Add API build cache in CI pipeline

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#14921]
We now build API v1 and v2 on every PR but they are not being cached, making future re-runs of the CI pipeline that have previously failed due to test flakes slower.

Update [https://github.com/calcom/cal.com/blob/main/.github/workflows/api-v1-production-build.yml](https://github.com/calcom/cal.com/blob/main/.github/workflows/api-v1-production-build.yml) and [https://github.com/calcom/cal.com/blob/main/.github/workflows/api-v2-production-build.yml](https://github.com/calcom/cal.com/blob/main/.github/workflows/api-v2-production-build.yml) to do what [https://github.com/calcom/cal.com/blob/main/.github/actions/cache-build/action.yml](https://github.com/calcom/cal.com/blob/main/.github/actions/cache-build/action.yml) is doing in terms of caching.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3655](https://linear.app/calcom/issue/CAL-3655/add-api-build-cache-in-ci-pipeline)</sub>

**Comment by utkershrajvenshi** [comment]
Hi @keithwillcode , opened up a PR for a possible fix. Please review and suggest any changes that are needed 🙏
