### ISSUE TITLE
[CAL-3668] Booking pages linked to ICS proton causing bookings to fail

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14951]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3668](https://linear.app/calcom/issue/CAL-3668/booking-pages-linked-to-ics-proton-causing-bookings-to-fail)</sub>

**Comment by PeerRich** [comment]
we have a different ticket for ICS Proton calendar and a bounty
