### ISSUE TITLE
[CAL-3670] i18n: German translations missing from the booking and success page

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14953]
![Screenshot 2024-05-09 at 10.27.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d9aa11b4-6bbb-473b-93a3-eb21a1785ac4/3bbaf903-4796-4bba-984e-acda06501698?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kOWFhMTFiNC02YmJiLTQ3M2ItOTNhMy1lYjIxYTE3ODVhYzQvM2JiYWY5MDMtNDc5Ni00YmJhLTk4NGUtYWNkYTA2NTAxNjk4IiwiaWF0IjoxNzE1MjQzMjU5LCJleHAiOjE3MTUzMjk2NTl9.6Nz-5U-nuG4LXkskDyh41jFcyRg2DQnvSFB2fxC8rmg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3670](https://linear.app/calcom/issue/CAL-3670/i18n-german-translations-missing-from-the-booking-and-success-page)</sub>

**Comment by smitgol** [comment]
i am sure about the time format but there is already pr raised for translation
