### ISSUE TITLE
[CAL-3675] Overlay calendar - enabled by default if supported calendar is installed

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#14969]
Overlay calendar should be enabled by default if you have a calendar we support for overlaying. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3675](https://linear.app/calcom/issue/CAL-3675/overlay-calendar-enabled-by-default-if-supported-calendar-is-installed)</sub>

**Comment by supalarry** [comment]
More context: only having Google Calendar as connected calendar enables overlay calendar

**Comment by CarinaWolli** [comment]
Covered in overlay calender v2: https://github.com/calcom/cal.com/issues/12763
