### ISSUE TITLE
[CAL-3680] Two google calendar entries for recurring event

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#14978]
A recurring event creates two google calendar entries for each instance except the first and last one. The two google calendar events also have different video link locations

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3680](https://linear.app/calcom/issue/CAL-3680/two-google-calendar-entries-for-recurring-event)</sub>

**Comment by divyanshchahar** [comment]
Unable to reproduce bug

- Event occurs only once google calendar

![google-calendar3](https://github.com/calcom/cal.com/assets/40364504/29ed8eb9-61d7-444d-aef4-7dd8904687b1)
![google-calendar2](https://github.com/calcom/cal.com/assets/40364504/907ed330-0984-48e2-b58d-d6cebf48d4cb)
![google-calendar1](https://github.com/calcom/cal.com/assets/40364504/57a12075-9b0a-4173-a6fa-828effdf8593)


- Event occurs only once in cal bookings as well 

![cal](https://github.com/calcom/cal.com/assets/40364504/6cb0de63-ebae-4cdc-a7cf-d98d3b33ebaa)

**Comment by hariombalhara** [comment]
@CarinaWolli Just tested this and I didn't see this issue. 
[https://www.loom.com/share/72b116cb3c6346908c23f03cd854ddb7](https://www.loom.com/share/72b116cb3c6346908c23f03cd854ddb7)

Is it replicable still? A loom would help.

**Comment by CarinaWolli** [comment]
I also can't reproduce this anymore
