### ISSUE TITLE
Apostrophes are not appearing correctly in email subjects.

### ISSUE THREAD

**Issue by ConnorGargano** [calcom/cal.com#1499]
Found a bug? Please fill out the sections below. 👍

Apostrophes are not appearing correctly in email subjects when displaying the title of an event type.

Event type in question: cal.com/connor/game

I have attached screenshots below.

<img width="910" alt="Screenshot 2022-01-13 at 16 39 40" src="https://user-images.githubusercontent.com/88032331/149372722-65aa9da8-f715-48cc-8cb2-f04f7908567d.png">

<img width="101" alt="Screenshot 2022-01-13 at 16 41 41" src="https://user-images.githubusercontent.com/88032331/149372730-64ba8ac5-db0f-4344-93ba-782ca5a4751e.png">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-Version: I am using the hosted version of cal.com
- Browser version: https://www.whatsmybrowser.org/b/GSFBX

**Comment by miguelnietoa** [comment]
Hi @ConnorGargano, would you know how to enable email sending in my development environment? Does this require additional configuration?

**Comment by GlitchWitch** [comment]
It appears that this is [still an ongoing issue](https://calendso.slack.com/archives/C01NXDSRY9W/p1658069352390929) unfortunately. Commenting here to bump this up as I saw the same thing with a booking I received this morning.

**Comment by zomars** [comment]
@sean-brydon can you take a look when you have time?

**Comment by zomars** [comment]
Linking a previous fixing attempt of reference #2855

**Comment by marvinvonhagen** [comment]
Just encountered a similar problem; fyi, the same issue applies to other commonly used special characters such as "<>"
