### ISSUE TITLE
Embed broken since 4.0.8

### ISSUE THREAD

**Issue by kaumudpa** [calcom/cal.com#14990]
Embed is broken since 4.0.8

Console gives error 

Match of WEBAPP_URL with ALLOWED_HOSTNAME failed {
  WEBAPP_URL: 'https://cal.ngx.0xmetalabs.com',
  ALLOWED_HOSTNAMES: 
   [
   
   ] 
}

**Comment by muhllys** [comment]
I tried hard coding NEXT_PUBLIC_EMBED_LIB_URL in .env, didn't work.
The only solution for me was to get the embed code and replace the embed url with the original cal.com one like this:

https://cal.ngx.0xmetalabs.com/embed/embed.js replace this to https://app.cal.com/embed/embed.js

But this definitely seems to be a bug that needs to be solved.

**Comment by l0g1x** [comment]
Hi there, any chance this can get a closer look? We use the react embed as a part of our sales process to allow people taken off our waitlist to schedule a demo. Right now, nobody can schedule a demo

**Comment by rafarc21** [comment]
In my humble opinion this should be of high priority since it breaks a main and client facing feature of the application.

**Comment by jbenguira** [comment]
This bug is still here in the latest version :(

**Comment by aribn** [comment]
Looks like this may be addressed with calcom/docker [PR #364](https://github.com/calcom/docker/pull/364), but we're still seeing it broken as of v4.3.1.

**Comment by jankarres** [comment]
Still broken as of [v4.3.4](https://github.com/calcom/cal.com/releases/tag/v4.3.4).

**Comment by hariombalhara** [comment]
@jankarres Could you confirm that you still don't have the embed folder with these files
![image](https://github.com/user-attachments/assets/87097f6c-e636-4917-b543-0794b153b7bb)

**Comment by jankarres** [comment]
@hariombalhara Sorry, it was my bad. We use the Docker container from `calcom.docker.scarf.sh/calcom/cal.com`. Inside, the requested files exist once we have upgraded to [v4.3.4](https://github.com/calcom/cal.com/releases/tag/v4.3.4)..
![2024-08-07_07-55-10 Screenshot](https://github.com/user-attachments/assets/46f9d258-7c88-460b-8469-c482d4c1083c)

But the reverse proxy with caching that we use before the instance has not yet been completely flushed. Due to the bug in the previous version, the 404 errors of the static files were still cached.

**Comment by hariombalhara** [comment]
Awesome !! Do you think those caching could be a fault from our end, like cache headers are not correct maybe for 404 pages.

Anyway, I am closing this ticket as you have verified that files exist

**Comment by jankarres** [comment]
The script is embedded via `/embed/embed.js` without a version number, e.g. as a query parameter, which also seems to make sense. However, this means that if reverse proxies cache static assets, these have to be flushed manually after an upgrade from Cal.com.

I see no issue here on your side.

**Comment by kaumudpa** [comment]
I can conform this is resolved in V4.3.5
