### ISSUE TITLE
Edge case: Changing a destination calendar and deleting a booking may fail to delete on the actual calendar

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#1501]
Right now the application tries to delete the Google event in the `primary` calendar instead of the actual calendar where the event is located in. e.g. `my-cal`.

My PR is more a quick fix, to validate the solution. Instead of `primary` it uses the destination calendar of the user, and "hopes" that is the correct one. This could still fail if we change the destination calendar to another one.

Steps:

1. Add Google Integration with 3 calendars: `primary`, `my-cal-1` and `some-cal-2`
2. Select `my-cal-1` as the destination calendar
3. Create a booking --> `event-1` is created in `my-cal-1`
4. Delete the booking --> with my PR it would be able to delete the event `event-1`, because event-calendar = destination-calendar
5. Create another booking --> `event-2` is created in `my-cal-1`
6. Change the destination calendar to `some-cal-2`
7. Delete the booking --> API call fails, because the event `event-2`, because event-calendar != destination-calendar and event-calendar != primary-calendar

Instead of implicitly assuming that the event is located in the `primary` or `destination-calendar`, we should store it with the BookingReference. 

**BookingReference**
| id | type | uid | bookingId | meetingId | **calendarId** |
|---|---|---|---|---|---|
| 24 | google_calendar | es6cd4qq7otkq885m5pnb9n7g8 | 23 | es6cd4qq7otkq885m5pnb9n7g8 | **some-cal-2** |

Here is the relevant Google Calendar API documentation:

https://developers.google.com/calendar/api/v3/reference/events/get

As you can see, it always requires an `eventId` **and** a `calendarId` to identify an event.

_Originally posted by @philprime in https://github.com/calendso/calendso/issues/1481#issuecomment-1011905053_

**Comment by PeerRich** [comment]
@joeauyeung was this fixed?
