### ISSUE TITLE
[CAL-3743] no description of location in api reference

### ISSUE THREAD

**Issue by GeneralKugelBlitz** [calcom/cal.com#15029]
Create new booking api reference link: https://docs.cal.com/docs/enterprise-features/api/api-reference/bookings#create-a-new-booking

### Issue Summary

there must be strings or JSON for each meeting provider, please provide us with the option strings in the api reference.

<sub>[CAL-3743](https://linear.app/calcom/issue/CAL-3743/no-description-of-location-in-api-reference)</sub>

**Comment by PeerRich** [comment]
@alishaz-polymath

**Comment by Hamza525318** [comment]
I dint understand what has to be done Can someone please elaborate

**Comment by alishaz-polymath** [comment]
Detailed docs added, accessible here: https://cal.com/docs/enterprise-features/api/api-reference/v1/bookings#location-object
