### ISSUE TITLE
[CAL-3713] Line breaks not reflecting in the event type description

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#15056]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3713](https://linear.app/calcom/issue/CAL-3713/line-breaks-not-reflecting-in-the-event-type-description)</sub>

**Comment by SySagar** [comment]
@milospuac Just want to confirm if I am thinking right direction.

Assume in description we type:
```mdx
line 1

line 2
``` 

currently it will show like this:
```mdx
line 1
line 2
``` 

So do we intent to make that one line break also appear as it is in ui?

**Comment by anikdhabal** [comment]
This is because we internally pass a short description to the component to show only the first line and hide the others to avoid making the list too big
