### ISSUE TITLE
Calendar Sync

### ISSUE THREAD

**Issue by kuna1bajaj** [calcom/cal.com#15065]
### Juggling calendars is really hard.

Cal.com should auto-copy events between calendars and have the option to create bi-directional calendar syncs. you can look at the features at https://reclaim.ai/features/calendar-sync for inspiration

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by PeerRich** [comment]
calendar syncing is not something we will be offering anytime soon. You can use Reclaim alongside cal.com 🥳
