### ISSUE TITLE
[CAL-3715] visiting "Organization" pages without access shows empty page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15061]
if you are not in an organisation and you visit a link like: [https://app.cal.com/settings/organizations/members](https://app.cal.com/settings/organizations/members)

you will see an empty page:

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/30525e8b-3775-4805-b478-659e5499ed8c/180eac92-f326-415e-916a-92f7f832a27e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMDUyNWU4Yi0zNzc1LTQ4MDUtYjQ3OC02NTllNTQ5OWVkOGMvMTgwZWFjOTItZjMyNi00MTVlLTkxNmEtOTJmN2Y4MzJhMjdlIiwiaWF0IjoxNzE1ODAzNzA1LCJleHAiOjE3NDczMzk3MDV9.C4ccI1iFEXLF0gwYJI22BLDMnExnvrgQiaQ1UMiUFHY)

instead we should link to [https://app.cal.com/enterprise](https://app.cal.com/enterprise)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3715](https://linear.app/calcom/issue/CAL-3715/visiting-organization-pages-without-access-shows-empty-page)</sub>

**Comment by Amit91848** [comment]
Similar with teams @PeerRich 


https://github.com/calcom/cal.com/assets/74371312/8ce64367-8402-409f-b307-a047dd377edb
