### ISSUE TITLE
[CAL-3754] Ability to provide a reason for event rejection

### ISSUE THREAD

**Issue by Bonapara** [calcom/cal.com#15079]
### Is your proposal related to a problem?

At Twenty, we have a "book a call" CTA on our homepage with a round-robin and the "Require confirmation" activated. When I get an email to confirm a meeting, I can only accept or reject the meeting without explanations.

### Describe the solution you'd like

The ability to provide a reason for the event rejection. I want to be redirected to a webpage to explain why I'm declining the event.

### Describe alternatives you've considered

I copy and paste the attendee's email and write them the reason directly (Often it is to reschedule)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3754](https://linear.app/calcom/issue/CAL-3754/ability-to-provide-a-reason-for-event-rejection)</sub>

**Comment by PeerRich** [comment]
i agree. within https://app.cal.com/bookings you can add a reason but not from email
