### ISSUE TITLE
[CAL-3727] Setup Prisma exceptions handlers to not cause 500 when prisma throws

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#15073]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3727](https://linear.app/calcom/issue/CAL-3727/setup-prisma-exceptions-handlers-to-not-cause-500-when-prisma-throws)</sub>

**Comment by vikrant845** [comment]
Do I just need to change the 500 status code to appropriate status codes based on error messages in the api routes??
