### ISSUE TITLE
[CAL-2872] Tweak forgot password for Google and SAML identities

### ISSUE THREAD

**Issue by deepakprabhakara** [calcom/cal.com#1508]
### Is your proposal related to a problem?

With the addition of Google and SAML identities (which do not have a password), we need to tweak the forgot password flow for these accounts.

### Describe the solution you'd like

We should tweak the email message to remind them that they do not have a password and they should use Google/SAML login.

### Describe alternatives you've considered

n/a

### Additional context

n/a

<sub>[CAL-2872](https://linear.app/calcom/issue/CAL-2872/tweak-forgot-password-for-google-and-saml-identities)</sub>

**Comment by milospuac** [comment]
Thanks Deepak! Our team will have a look at this.
