### ISSUE TITLE
[CAL-3750] Use new app install flow to make installing apps on organisations better

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#15087]
allow Org Admin/Owners to install an app on all teams at once.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3750](https://linear.app/calcom/issue/CAL-3750/use-new-app-install-flow-to-make-installing-apps-on-organisations)</sub>

**Comment by kart1ka** [comment]
Hi @SomayChauhan

Could you please elaborate on this feature?
I could see that Org owners are already able to install an app on all the teams in the org at once. See below Loom Video:
https://www.loom.com/share/ec63d8deb71148458a4fd0a49bbeab54?sid=9aa6283e-6624-413d-9f84-0a6920afbbb4

**Comment by SomayChauhan** [comment]
Hey, Man
I'm already working on it.
