### ISSUE TITLE
Apple iCal Integration

### ISSUE THREAD

**Issue by sydwardrae** [calcom/cal.com#1509]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

2 confirmed issues relating to integration with Apple iCal (potentially 2 - 3 more, waiting for cust to confirm they're integrating with iCal)

### Steps to Reproduce

Cust 1 - My cal.com calendar is in some strange state such that it marks tomorrow (“today +1”) as fully-booked/unavailable even though there are no bookings or slots taken. So, yesterday, on the the 12th, it showed today the 13th as completely unavailable, and today it shows tomorrow Friday 14th as unavailable. The 15th and later are not affected. I have the calendar integrated with Apple iCal. I have tried removing the integration (no affect); changing my Availability settings in cal.com in the hope of resetting/fix some internal problem, but nothing seems to work. 

Cust 2 -  I set up my available time for GMT +4 (Asia/Dubai/Abu Dhabi). But my event types preview show the timings completely wrong! Also, there's no way for me to see changes after setting intervals. Can you please check and help? I matched the same parameters (timezone and my avail timings) for both Availability page AND Event Types page (under “advanced settings”). I also created a “test” event and purposely DID NOT specify anything under advanced settings. It seems to match closer to my timezone, but this is not the solution. The whole idea is to be able to customize my availability and timezone PER event, correct?

**Comment by PeerRich** [comment]
hey @natelindev our iCal / Apple Calendar is using TSDav under the hood. maybe you can give this a look

**Comment by sydwardrae** [comment]
@natelindev , more context for this from the customer : 

"It looks like to me there’s a timezone math problem somewhere in your system. I’d almost say for sure it is client side, but I don’t know how your machinery is structured underneath.



I’m in Asia/Taipei +8 GMT. My cal is configured with my availability and timezone in Asia/Taipei.



If I do this:



1. Set my availability today for: 09:00 to 20:00



2. Open my cal, I will see some late after noon slots open:






3. If I set the tz to US Eastern time (-13 hrs from here bc of DST), suddenly things change:





4. Now my full Saturday, which is mostly unavailable to me and my customers in Taiwan, is available for booking.



5. However, note that prior to taking that screenshot, I had already booked the 20:00 slot using cal.com. The emails confirming it arrived as expected, and the Apple Calendar updated as expected. But cal.com still offers that Friday 20:00 EST slot, which is my Saturday 09:00 here. So, that’s a problem.



6. It’s seems like your software assumes time values have been normalized to UTC, but actually is doing time arithmetic with some values still representing local time. Like… my cal times were in UTC but then my local time were not converted to UTC prior to comparing them. Hence, it appears that the day is long past, and only late afternoon and evening slots are available.



7. Given this, perhaps the problem is more fundamental than an Apple Calendar integration problem. Or maybe there are multiple problems."

**Comment by RubenWaterman** [comment]
After updating to the latest version of Cal, I have the same issue (both with my Google calendar and iCal). The odd part is that on the current day, there is availability with the 120 minutes advance requirement (while this date was completely blocked out yesterday) but now tomorrow is blocked out entirely (which should be available as there are no bookings). I can also confirm what @sydwardrae wrote that if you play with the time zones, more timeslots become available.

<img width="746" alt="Screenshot 2022-01-18 at 10 19 47" src="https://user-images.githubusercontent.com/5938863/149907793-f9ec334b-3779-4804-a3ee-98f7b95e6c7d.png">

**Comment by PeerRich** [comment]
this issue was reported yesterday and @emrysal is already investigating!
