### ISSUE TITLE
[CAL-3753] Exclude location options for seated event

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#15090]
Location options are unnecessary for seated events because there will be only one location for multiple seats within a single time slot. Therefore, offering location choices to bookers is pointless.

[https://www.loom.com/share/20da97e6d30a4d7aa29f525a0886fcfa?sid=fa3c08cc-283a-437b-83f3-55c80c9f1977](https://www.loom.com/share/20da97e6d30a4d7aa29f525a0886fcfa?sid=fa3c08cc-283a-437b-83f3-55c80c9f1977)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3753](https://linear.app/calcom/issue/CAL-3753/exclude-location-options-for-seated-event)</sub>

**Comment by dilpreetsio** [comment]
Hey @SomayChauhan,
I was having a look at this one. Should we also limit the location to 1 for event maker for seated events or simply hide it for the booker?

**Comment by SomayChauhan** [comment]
Limiting the location to 1 for the event maker should work.
