### ISSUE TITLE
Set custom availability for specific dates (non-recurring, not week-day based availability)

### ISSUE THREAD

**Issue by EduNetEurope** [calcom/cal.com#15092]
We would like to be able to propose specific dates (in an email) without giving the email recipients the option to select any other dates.
So the current availability format that is based on recurring availabilites on week days does not work.

Instead, we would like to be able to pick specific availabilities in a very restricted time range for a given meeting.

**Comment by PeerRich** [comment]
this is currently being worked on

**Comment by EduNetEurope** [comment]
> this is currently being worked on

You closed this request "as not planned". Is it currently being worked on or not planned?
