### ISSUE TITLE
[CAL-3766] Offer seats events invites everyone regardless their availibility schedule

### ISSUE THREAD

**Issue by olivierlambert** [calcom/cal.com#15105]
### Issue Summary

When using an event with "offer seats", despite setting a round robin attribution for the event, all the hosts are invited, regardless their own availability.

### Steps to Reproduce

1. Create an event with seats
2. Have 2 hosts with their own availability (which are different/without overlap)
3. Book a meeting at an hour where only one host is available
4. Both hosts are invited

### Actual Results

- Both hosts are invited to the event despite their availability is incompatible with the booked slot

### Expected Results

- Only the available host should be invited, respecting their own availability

### Technical details

- Chrome/FF
- Node.js 18
- Cal v4.07

### Evidence

Round robin enabled with 2 hosts:

![image](https://github.com/calcom/cal.com/assets/1241401/4051fbec-4015-4ce3-8c29-dcc85ad28aa2)

![image](https://github.com/calcom/cal.com/assets/1241401/4c525d21-a83a-4f58-a0d9-70c54723fc92)

But the invite:

![image](https://github.com/calcom/cal.com/assets/1241401/427612e4-cb92-4f0e-8fe4-cfbbed67648f)

<sub>[CAL-3766](https://linear.app/calcom/issue/CAL-3766/offer-seats-events-invites-everyone-regardless-their-availibility)</sub>

**Comment by rk9595** [comment]
Can I take this issue?

**Comment by olivierlambert** [comment]
Hello there!

Anything I can do to make the PR merged?
