### ISSUE TITLE
[CAL-3760] Setup ADMIN UI in FE

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#15116]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3760](https://linear.app/calcom/issue/CAL-3760/setup-admin-ui-in-fe)</sub>

**Comment by keithwillcode** [comment]
@sean-brydon what’s this issue intended for?

**Comment by sean-brydon** [comment]
> @sean-brydon what’s this issue intended for?

It was an accidental sub issue that got made public from goblin.
