### ISSUE TITLE
[CAL-3765] Managed Events “Limit future bookings” settings gets reset when adding new user

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#15125]
When adding a new user to our managed event types, it looks like the “Limit future bookings” settings gets reset around whether the property is showing business days or calendar days based on the original setting.

The managed event types are supposed to not reset any field that's unlocked, even if new users are added to the managed event. In this case, under `limit future bookings` the selection of `business days` or `calendar days` keeps getting reset when a new user is added to an existing managed event, which is undesirable.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3765](https://linear.app/calcom/issue/CAL-3765/managed-events-limit-future-bookings-settings-gets-reset-when-adding)</sub>

**Comment by ZainGulbaz** [comment]
@alishaz-polymath  can you please explain it more?

**Comment by alishaz-polymath** [comment]
@ZainGulbaz I've updated the description 🙏

**Comment by alishaz-polymath** [comment]
Unable to reproduce this issue suggesting this has been sorted!
