### ISSUE TITLE
Forgot Password Email Box

### ISSUE THREAD

**Issue by ConnorGargano** [calcom/cal.com#1515]
Found a bug? Please fill out the sections below. 👍

When going to reset my password, the email address box is not the full length.

![image](https://user-images.githubusercontent.com/88032331/149575458-9a5db86f-7402-47b3-b0ec-76bb6354cec2.png)

A summary of the issue. This needs to be a clear detailed-rich summary.

Make the box longer.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The page where the issue can be seen: https://app.cal.com/auth/forgot-password

**Comment by sean-brydon** [comment]
<img width="596" alt="CleanShot 2022-04-27 at 09 10 15@2x" src="https://user-images.githubusercontent.com/55134778/165472250-665c17d4-2d5f-4e91-ad65-9e5037eaa39b.png">
This is fixed . Thank you
