### ISSUE TITLE
[CAL-3785] Analytics Apps: Track "Confirm" as an event (GTM, Fathom, etc.)

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#15168]
*Report from customer:*

We are trying to set up a google tag manager event for when a book submission occurs. The problem we are facing is that the tag is not firing based off the documentation found on your site. How do we set up a conversion event for when a cal demo is booked so we can track it in google analytics

"Confirm" should fire an event

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f3252cd2-d70b-42ac-b1aa-8a59ddfa5628/706992a6-99e3-401d-ae5d-38fb29dea445?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mMzI1MmNkMi1kNzBiLTQyYWMtYjFhYS04YTU5ZGRmYTU2MjgvNzA2OTkyYTYtOTllMy00MDFkLWFlNWQtMzhmYjI5ZGVhNDQ1IiwiaWF0IjoxNzE2NDEyNDUxLCJleHAiOjE3NDc5NDg0NTF9.yiXGYP14FjAluLs2nQY2oo941S32qWW9sXhDUb8FdgI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3785](https://linear.app/calcom/issue/CAL-3785/analytics-apps-track-confirm-as-an-event-gtm-fathom-etc)</sub>

**Comment by PeerRich** [comment]
i imagine he is referring to the "confirm" button which has no conversion tracking on it. we should add conversion tracking to all analytics apps, not only GTM

**Comment by PeerRich** [comment]
there is a chance we could achieve this with zapier today incase its urgent: 
![image](https://github.com/calcom/cal.com/assets/8019099/7823f23e-b3d3-4fd9-9dfa-a89770197561)
