### ISSUE TITLE
[Feature Request]: Hide Public Profile

### ISSUE THREAD

**Issue by nitrag** [calcom/cal.com#15165]
### Is your proposal related to a problem?

No, just a privacy concern.

### Describe the solution you'd like

A user should be able to disable their public profile or have a separate setting to disable the display of all the users different event types.

### Describe alternatives you've considered

...

### Additional context

It seems possible for someone to alter the booking url, see the users profile, then choose a different event type.

### Requirement/Document

N/A

**Comment by ciaranha** [comment]
Hey @nitrag, have you tried hiding all your event types?
