### ISSUE TITLE
[CAL-3805] Add tests for Editor

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#15199]
More information: [https://github.com/calcom/cal.com/pull/15198](https://github.com/calcom/cal.com/pull/15198)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3805](https://linear.app/calcom/issue/CAL-3805/add-tests-for-editor)</sub>

**Comment by ImBIOS** [comment]
I love to write automated test scripts and I'm confident able to deliver them. Can someone please assign me this issue? I'll work on it right now and open PR as soon as possible.

**Comment by Amit91848** [comment]
@ImBIOS we don't assign issues, you can open a PR and we will surely review it
