### ISSUE TITLE
File size for cal.com node_modules is close to 1 Tera bite.

### ISSUE THREAD

**Issue by Pratik-Kumar-621** [calcom/cal.com#15204]
### File Size while cloing.

File size after cloning and setting up cal.com locally is close to 1 Tera bite

### Steps to Reproduce

clone the repo and run yarn
<img width="1136" alt="Screenshot 2024-05-26 at 1 20 58 PM" src="https://github.com/calcom/cal.com/assets/70286186/6a176154-ae03-4d14-9f50-f5ed14c79372">

My ssd is of size 1 TB and was almost empty, still I was not able to setup cal.com

**Comment by Pratik-Kumar-621** [comment]
<img width="251" alt="Screenshot 2024-05-26 at 1 34 34 PM" src="https://github.com/calcom/cal.com/assets/70286186/055f115c-128e-4441-9335-626de29737c4">

After deleting cal.com available space is 800GB

**Comment by Pratik-Kumar-621** [comment]
<img width="251" alt="Screenshot 2024-05-26 at 1 34 34 PM" src="https://github.com/calcom/cal.com/assets/70286186/bddce474-c2af-46f7-85aa-9e02c4ab59fd">

After I deleted folder the available space comes 800+GB.

**Comment by PeerRich** [comment]
thats veeery weird. the entire mono repo is 10gb on my end with ALL node_modules of all sub-repos

<img width="327" alt="CleanShot 2024-05-30 at 15 24 13@2x" src="https://github.com/calcom/cal.com/assets/8019099/a91d56c8-29d6-4746-9b67-b88f18485e32">
