### ISSUE TITLE
Create a booking endpoint doesn't really work: code 400 {"message":"invalid_type in 'metadata': Required"}

### ISSUE THREAD

**Issue by harrydragon1** [calcom/cal.com#15205]
{
    "eventTypeId": 111111,
    "start": "2024-06-03T00:00:00.000Z",
    "end": "2024-06-03T00:30:00.000Z",
    "responses": {
        "name": "Harry Bolton",
        "email": "harry@email.com",
        "location": "Google Meet",
        "metadata": {
            "additionalInfo": "Some metadata information"
        }
    },
    "timeZone": "America/New_York",
    "language": "en",
    "title": "Mrketing Meeting Placeholder"
}

no matter what it will come out with: {"message":"invalid_type in 'metadata': Required"}

**Comment by harrydragon1** [comment]
> Hey @harrydragon1! 👋 I'm here to help you with any bugs, questions, or contributions while you wait for a human maintainer. Let's squash those bugs together!
> 
> To resolve the issue of receiving a 400 error code with the message `{"message":"invalid_type in 'metadata': Required"}`, you need to ensure that the `metadata` field is included at the root level of your JSON payload, not nested within the `responses` field.
> 
> Here is the corrected JSON payload:
> 
> ```json
> {
>     "eventTypeId": 111111,
>     "start": "2024-06-03T00:00:00.000Z",
>     "end": "2024-06-03T00:30:00.000Z",
>     "responses": {
>         "name": "Harry Bolton",
>         "email": "harry@email.com",
>         "location": "Google Meet"
>     },
>     "metadata": {
>         "additionalInfo": "Some metadata information"
>     },
>     "timeZone": "America/New_York",
>     "language": "en",
>     "title": "Marketing Meeting Placeholder"
> }
> ```
> 
> Make sure the `metadata` field is directly under the main object and not inside `responses` [[1]](https://github.com/calcom/cal.com/blob/main/packages/prisma/migrations/20221129125935_add_metadata_to_booking/migration.sql)[[2]](https://github.com/calcom/cal.com/blob/main/apps/api/v1/pages/api/bookings/_post.ts).
> 
> #### Details
> **About Dosu** This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> _To continue the conversation, mention @dosu._

does dosubot reply

**Comment by harrydragon1** [comment]
@dosu do u reply

**Comment by devstein** [comment]
Hey @harrydragon1 at the moment Dosu doesn't respond if issues are marked as closed
