### ISSUE TITLE
[CAL-3819] Two icons showing on the event type page, one of which gives a 500 error when clicked

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#15237]
[https://www.loom.com/share/396887740ba54f4da4ea175b212d3500](https://www.loom.com/share/396887740ba54f4da4ea175b212d3500)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3819](https://linear.app/calcom/issue/CAL-3819/two-icons-showing-on-the-event-type-page-one-of-which-gives-a-500)</sub>

**Comment by Udit-takkar** [comment]
fixed https://github.com/calcom/cal.com/pull/15239
