### ISSUE TITLE
[CAL-3816] Error "You need to have minimum teams" needs improving

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#15231]
I tried creating an org whilst belonging to less than 2 teams, and it just gives me the error "You need to have minimum teams".

a) this is an ambiguous error. we should instead display "You need to have a minimum of 2 teams to create an organization." or something

b) why is this a requirement? I was able to create the organization and then delete the 2 teams and everything was fine

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3816](https://linear.app/calcom/issue/CAL-3816/error-you-need-to-have-minimum-teams-needs-improving)</sub>

**Comment by PeerRich** [comment]
b) we have this so people dont spam that endpoint cause it requires a paid team

unfortunately we have to create the org before payment so you could technically spam orgs

we can change the requirement to 1 team instead
