### ISSUE TITLE
Cal availability timing issue

### ISSUE THREAD

**Issue by xboxhaxorz** [calcom/cal.com#15234]
https://vento.so/view/ae6c4930-e809-4d04-9886-5dadfb3e26ae?utm_medium=share

As shown in screengrab

If you select an hr meeting it only has a few time slots since it goes from 2,3,4,5 etc;
But if you do 30 mins you get way more options, same with 15 mins, but 45 has similar issue as above

**Comment by PeerRich** [comment]
if you want all events to start at the same interval, use this setting:

<img width="477" alt="CleanShot 2024-05-30 at 15 26 12@2x" src="https://github.com/calcom/cal.com/assets/8019099/6ef6412f-45c1-468e-bb5c-e7e9007d1bd7">

**Comment by xboxhaxorz** [comment]
Mine is set to the default, i never changed it

Best Regards

**Comment by lilyTokens** [comment]
Scheduling infrastructure at this level of complexity is genuinely hard to reason about. The edge case surface area for timezone handling alone is enormous. I have been using Cal.com as a reference for how to think about time-based coordination problems in an agentic context where agents need to schedule and coordinate with humans. The separation between availability logic and booking logic in the architecture is a useful model.
