### ISSUE TITLE
[CAL-3820] When using API, Google Meet location reverting to Calvideo

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#15238]
When booking the event normally it works but when booked through their platform for which they use our API, that's when the error happens ([https://www.lectrium.com/book-a-demo](https://www.lectrium.com/book-a-demo))

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3820](https://linear.app/calcom/issue/CAL-3820/when-using-api-google-meet-location-reverting-to-calvideo)</sub>

**Comment by PeerRich** [comment]
yep, google calendar must exist
