### ISSUE TITLE
Feature Request - Automatic redirect after scheduling an appointment

### ISSUE THREAD

**Issue by NightKing2k** [calcom/cal.com#1523]
### Is your proposal related to a problem?
I'm frustrated when I cannot redirect my website visitors after they book an appointment with me.

### Describe the solution you'd like
I'd like to have a feature where the user can be redirected to a webpage of my choice after they finish booking a call/appointment.

### Describe alternatives you've considered
Calendly is an alternative that I have used on a free trial to test it out.

### Additional context
none

**Comment by PeerRich** [comment]
that's a very good feature request and I'd love to add this in the next release. 

I think it could just be a textfield in the event-types and if, empty it'll use the pre-made success page.

All I wonder is, if it should redirect immediately or show a countdown: "We are redirecting you in 5, 4, 3, 2, 1 seconds to `mywebsite.com/thankyou`

![image](https://user-images.githubusercontent.com/8019099/149771297-2923da4e-d774-4332-a987-a3370f3b0e02.png)

**Comment by NightKing2k** [comment]
Yes, the text field in the event types is a great idea.

However, a countdown redirect will result in some users exiting the page. An automatic redirect will ensure that users don't bounce off the page. Most SaaS calendar apps are using an automatic redirect.

**Comment by PeerRich** [comment]
> Yes, the text field in the event types is a great idea.
> 
> 
> 
> However, a countdown redirect will result in some users exiting the page. An automatic redirect will ensure that users don't bounce off the page. Most SaaS calendar apps are using an automatic redirect.

sounds good. i also think an automatic redirect is easier to implement

**Comment by snikpic** [comment]
+1 - This is great stuff, would love to see it implemented
