### ISSUE TITLE
[CAL-3821] API: an error occurred while querying the database

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15240]
we are seeing an uptick in this error

<sub>[CAL-3821](https://linear.app/calcom/issue/CAL-3821/api-an-error-occurred-while-querying-the-database)</sub>

**Comment by pedroapolloniufscar** [comment]
Hey team,

I'm also running into this issue with the cal.com API when trying to post a booking. I'm getting a 500 error with the message "API: an error occurred while querying the database #15240."

Any updates on this? Also, if there's a workaround or something I can do to fix this temporarily, that would be awesome.

Thanks!
