### ISSUE TITLE
[CAL-72] Email Confirmation and Stripe Cancellation after Account Deletion

### ISSUE THREAD

**Issue by ConnorGargano** [calcom/cal.com#1524]
### Describe the solution you'd like

When deleting an account via cal.com, confirmation via email would be nice.

**Comment by PeerRich** [comment]
@alishaz-polymath do you wanna work on this when you build the Pre-deletion survey?

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath do you wanna work on this when you build the Pre-deletion survey?

@PeerRich Yeah I think that would be the way to go

**Comment by alishaz-polymath** [comment]
@joeauyeung @sean-brydon 
This should be a quick win if you guys have the bandwidth

**Comment by zomars** [comment]
> while we work on it, I would also add to cancel all pro subscriptions. cc @zomars

Let’s track that on another issue. We need to check how teams are going to be disbanded.
