### ISSUE TITLE
Issue with Duplicated Availability in the Troubleshooter

### ISSUE THREAD

**Issue by jtylerhartley** [calcom/cal.com#1526]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Linking multiple accounts (in my case two google calendar accounts) duplicates my availability in the troubleshooter. The two google accounts have completely separate calendars but somehow the availability from one calendar duplicates itself onto the troubleshooter twice when I have both calendars connected.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

<img width="604" alt="Troubleshooter Image" src="https://user-images.githubusercontent.com/70040274/149637482-894f189d-e23f-456f-8880-eca6e41cd50e.png">

### Technical details

- Browser version: Chrome 97
- Node.js version 
- Anything else that you think could be an issue.

**Comment by baileypumfleet** [comment]
Our engineering team will have a look into this!

**Comment by jtylerhartley** [comment]
Ok, thank you!

**Comment by jtylerhartley** [comment]
Any update on this. I am still having the issue unfortunately.

**Comment by matheusmuniz03** [comment]
@jtylerhartley can you tell me if the bug still occurs? I couldn't reproduce it

**Comment by jtylerhartley** [comment]
Yes, it seems like this issue has been fixed. Closing this for now. @matheusmuniz03 [matheusmuniz03](https://github.com/matheusmuniz03)
