### ISSUE TITLE
flaky round robin booking page title test

### ISSUE THREAD

**Issue by Amit91848** [calcom/cal.com#15289]
@Amit91848 this is causing the test to be flaky. Sometimes it expects `pro-user` instead of a team mate. and `pro-user` is not expected in the test.

```
expected: Team Event - 30min-team-id-277 between teammate-1 and Test Testson
received: Team Event - 30min-team-id-277 between pro-user and Test Testson
```

cc @Udit-takkar can you take a look as well? Since you have an approval here.

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/14245#discussion_r1622983767_

**Comment by Udit-takkar** [comment]
@Amit91848 is it fixed now? as you closed the PR

**Comment by Amit91848** [comment]
Yeah ig, I figured out what was causing it but that change was already made by zomars in https://github.com/calcom/cal.com/pull/15249/commits/fd118e9630c53abedee83f1333bb86752dde04cb, so waiting for his confirmation
