### ISSUE TITLE
event created after booking confirmation is entered on wrong calendar

### ISSUE THREAD

**Issue by woodwardjd** [calcom/cal.com#1528]
### Issue Summary

* Fresh install today as-of `33694196e1730fe28310e54d441235fd3a02d993` aka tag `v1.2`
* First integration to google calendar (account on google apps for domains or whatever they call that these days)
* Second integration to o365

Creating a booking which requires confirmation, and then confirming the booking, results in an event created on the first calendar of the second integration, no matter what calendar is selected as the "Destination Calendar" in `/integrations` ("Create events on:")

### Steps to Reproduce

1. Install calendso as-of `33694196e1730fe28310e54d441235fd3a02d993`
2. Integrate with one calendar (in my case, google calendar)
3. Integrate with another calendar (in my case, office365)
4. Select the Google Calendar as the "Create events on:" selection in `/integrations`
5. Create an Event Type (I used 50 minute in a 60 minute slot, confirmation required)
6. Book an event with that new Event Type
7. Go to Bookings, confirm the booking
8. Observe the event created on the second (office365) integration's first calendar
9. Repeat with any calendar in the "Create events on:" list selected, observe the event created on the second (office365) integration's first calendar.

Expected: event is created on the calendar selected in the "Create events on:" list.

### Technical details

I'm running this on Railway.  While manipulating the "Create events on:" select list I can watch the `DestinationCalendar` table's `externalId` and `integration` columns' values change (there's only one record in the table, because this is a fresh install with one user).  The value of `integration` matches an entry in Credential.type (I think?) and the value of `externalId` matches either what's displayed in the dropdown, or what looks like an internal identifier like `p#weather@group.v....` for `Weather`.  So, it appears some data is updated, and the UI remembers what I've selected when I refresh the page, but when the event is created it's not honoring that.

**Comment by woodwardjd** [comment]
This was a repeatable problem last night.  Demoing to my partner this morning I'm unable to reproduce.  It correctly writes to the selected "Destination calendar"  😠

**Comment by woodwardjd** [comment]
Yet another update: turns out the problem still exists as described.

Where it worked as expected today was on a "collaborative" event type with two people.  In that case it showed on my correctly selected "Destination Calendar" and did not show on the other person's registered calendar (only one).  If I get a chance I'll troubleshoot this second problem more and create another issue, no time right now.  The other person DID get an /email/ about it, it just didn't show on their calendar.

**Comment by PeerRich** [comment]
can you try again? a lot has changed since then.
