### ISSUE TITLE
[CAL-343] Allow clients to choose different duration for a meeting

### ISSUE THREAD

**Issue by pietro14** [calcom/cal.com#1529]
### Is your proposal related to a problem?

Currently, each meeting has its specific duration. If you want to allow a client to choose between a meeting of 1 hour and one of 30 minutes, you have to create two different meetings, one of 60 minutes and one of 30 minutes. That's not very practical if the description of the meeting is the same and if you want to offer meetings with several durations (15, 30, 60, 90 minutes).

### Describe the solution you'd like

It would be useful to be able to set different possible durations for a given meeting. I guess this could be a premium feature since it's like creating multiple meetings.

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
interesting idea. I think i've seen this somewhere before in another scheduling product. we'll think about this!

**Comment by pietro14** [comment]
Yes, that's right. It's a feature I found in this scheduling product:[ calendr.it](url)

**Comment by nCrazed** [comment]
I am currently considering trying out cal.com, but without this feature it's unusable to me

**Comment by PeerRich** [comment]
> I am currently considering trying out cal.com, but without this feature it's unusable to me

can you not create multiple event-types with different duration and give your clients the option to pick one?

i, for example, have 15 and 30: https://cal.com/peer

**Comment by huzaifahj** [comment]
> > I am currently considering trying out cal.com, but without this feature it's unusable to me
> 
> can you not create multiple event-types with different duration and give your clients the option to pick one?
> 
> i, for example, have 15 and 30: https://cal.com/peer

I still do think this feature is essential. What if we wanted the event type to be private? Just showing all the options on the main profile link is too inflexible and leads to a lot of duplication.

**Comment by PeerRich** [comment]
yes we're reprioritizing this now! could be potentially next milestone. lemme tag @Jaibles, he has some thoughts

**Comment by Jaibles** [comment]
Will add designs!

**Comment by Jaibles** [comment]
[Scheduler to determine duration - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=253%3A55169)

Designs attached!

**Comment by nCrazed** [comment]
Option B introduces an (imho) unnecessary click

**Comment by huzaifahj** [comment]
I think option B makes for a cleaner UI. Will there be an option for custom durations too? What if I want it to be 20 minutes.

**Comment by leog** [comment]
@Jaibles maybe we can leverage the textbox with arrows to increasing or decreasing minutes like we use for the recurring count when increasing or decreasing number of occurrences. And with 5min increments.

**Comment by Jaibles** [comment]
@leog the host will set the time increments in their event type settings. So the options may not be even increments so I would rather use a single select interaction rather than a standard number input.

**Comment by Jaibles** [comment]
Ag sorry @leog did you mean in the event type settings we could have that? We could certainly look at that alright. I'll take a look and see whether we need that or should keep it restricted but include all reasonable options. (20m would obviously be one of those.)
