### ISSUE TITLE
[CAL-3852] Org Owners Able to See ALL Bookings from Bookings Tab

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#15302]
Org owners should be able to see all users' bookings under their org from the bookings tab. There should not be the ability to turn this off from the individual settings on ORGs b/c the org owner owns all accounts.

* Any individual event-type
* Any managed event-type

If the org owner wants to be able to pull all bookings via API, then they will need to upgrade to Enterprise to have access to the admin API. However, they should be able to pull any data they want from the bookings tab. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3852](https://linear.app/calcom/issue/CAL-3852/org-owners-able-to-see-all-bookings-from-bookings-tab)</sub>

**Comment by shirazdole** [comment]
cc @keithwillcode — I know the team is swamped, but this is a pretty important improvement to consider after the retreat.

**Comment by SomayChauhan** [comment]
![Screenshot 2024-06-03 at 3.05.31 PM.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/02c2c8ce-178a-4017-a5e0-176306ad2588/5882f31c-3c98-4ff7-bb62-fc934e4aa9f0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wMmMyYzhjZS0xNzhhLTQwMTctYTVlMC0xNzYzMDZhZDI1ODgvNTg4MmYzMWMtM2M5OC00ZmY3LWJiNjItZmM5MzRlNGFhOWYwIiwiaWF0IjoxNzE3NDA3NDk3LCJleHAiOjE3NDg5NDM0OTd9.IjRZWL_g78EkJXTMB_WKVR3pUojx-WEvtxe5EX5mbSk)

adding these Pr's here for refference
[https://github.com/calcom/cal.com/pull/13591](https://github.com/calcom/cal.com/pull/13591#discussion_r1494413818)
[https://github.com/calcom/cal.com/pull/14079](https://github.com/calcom/cal.com/pull/14079)

ps: we should be able to reuse e2e tests at least
