### ISSUE TITLE
[CAL-3860] Add rescheduledBy & canceledBy fields in the DB

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#15317]
### Is your proposal related to a problem?

Currently, there is no way to tell who cancelled/rescheduled the metting/event. Usually, it is desirable to know the person cancelling or rescheduling the event for statistical and accountability purposes.

### Describe the solution you'd like

Add rescheduledBy & canceledBy fields in the DB, accessible via URL params in the cancellation page.

### Describe alternatives you've considered

N.A.

##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3860](https://linear.app/calcom/issue/CAL-3860/add-rescheduledby-and-canceledby-fields-in-the-db)</sub>

**Comment by dilpreetsio** [comment]
Hi @alishaz-polymath I'm working on it. I'm adding string types to store email id of the user who cancels or reschedules the booking. What do you think about it?

**Comment by pixelfact** [comment]
I am applying to this issue via [OnlyDust platform](https://staging-app.onlydust.com).

**Comment by AnthonyBuisset** [comment]
I am applying to this issue via [OnlyDust platform](https://staging-app.onlydust.com).
