### ISSUE TITLE
[CAL-3919] Hydration Error: nested <a> tags in EventTypes list when <Avatar /> is used.

### ISSUE THREAD

**Issue by balthazur** [calcom/cal.com#15311]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

While working on #14516 I discovered an hydration error. It happens when a team page from an unpublished organization is acessed, and one of the rendered event types renders an `<Avatar />`.

<img width="1510" alt="image" src="https://github.com/calcom/cal.com/assets/15075815/0382ac28-8ec8-456f-9284-b87ccbd9609c">

### Steps to Reproduce

I am working on e2e tests for #14516 so i have an unpublished organisation (no slug) with meta.requestedSlug = "example" setup, and configured my /etc/hosts to work with links like `http://example.cal.local:3000/team123?orgRedirection=true`
1. Create a team within an organisation
2. Create an even type, and configure it so an avatar will be rendered e.g. by setting type to round-robin and toggle "Round Robin Hosts - Add all team members, including future members" to be true.
3. Visit the team page. Can be from org link (e.g.`http://example.cal.local:3000/team123?orgRedirection=true`) or app link `http://app.cal.local:3000/team123?orgRedirection=true`.
4. Append `orgRedirection=true` to show the EventTypes list, as otherwise you will see the unpublished message. The hydration mismatch occurs.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- An hydration mismatch happens, presumably because of nested `<a>` elements. The parent `<a>` is the list element of the event type, the nested `<a>` is the avatar.

### Expected Results

- No hydration error, and no nested `<a> `elements.

### Technical details

Node 18
Chrome
MacOS 14.4.1 (23E224)

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

See Video [LOOM](https://www.loom.com/share/dcb4ed7a8ad842169e5620217b8387be?sid=1673e14d-63f7-41e6-bf80-6548c38884f4)

<sub>[CAL-3919](https://linear.app/calcom/issue/CAL-3919/hydration-error-nested-a-tags-in-eventtypes-list-when-avatar-is-used)</sub>

**Comment by souvikmishra** [comment]
if its still there and nobody is taking it up, i can take it up
