### ISSUE TITLE
[CAL-3894] Make the meeting duration time more visually toggleable 

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [calcom/cal.com#15327]
### Is your proposal related to a problem?

When a user goes to book a meeting, it is not immediately obvious that there is a way for them to alter the meeting duration. Everyone knows the middle section is where you pick the date, and the list of time slots on the right clearly invites the user to pick one. However, it is not obvious to everyone that the meeting duration time on the left can be toggled. Most of the items on the left are simply metadata that are not toggleable. While the timezone can be toggled, since it's determined automatically, most won't bother. This means that people are not focusing their attention on the left panel.

![image](https://github.com/calcom/cal.com/assets/8674072/bf401b6e-37ae-437a-af1c-cc48b9c11d1b)

### Describe the solution you'd like

There are some nice solutions by people on Twitter when I posted about this: https://x.com/peer_rich/status/1782166947636932930.

One suggestion: "**I would try it on the right above the time selection. Maybe reduce target size of 12hr/24hr bc that seems less important to me than duration, and might be mostly inferred by region?**"

Another suggestion was a slider of sorts that makes it clearer it can be toggled:

![image](https://github.com/calcom/cal.com/assets/8674072/04876830-2ff8-492e-9910-6f57c02d2bf9)

Either is reasonable to consider, but the former seems more straightforward.

### Describe alternatives you've considered

Not changing it, naturally.

##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3894](https://linear.app/calcom/issue/CAL-3894/make-the-meeting-duration-time-more-visually-toggleable)</sub>

**Comment by PeerRich** [comment]
@ciaranha

**Comment by PeerRich** [comment]
agree, can be improved

**Comment by ciaranha** [comment]
Yea I like that. Will definitely mock it up 👍

**Comment by anikdhabal** [comment]
![Screenshot 2024-06-07 015617](https://github.com/calcom/cal.com/assets/81948346/83f1e033-e05d-4652-bd9d-a77249f107ca)
@ciaranha @PeerRich

**Comment by ciaranha** [comment]
@bcakici edit it [here](https://www.figma.com/design/1wrADmXcZc4mMoU4Ru4uz9/Cal-DS---Patterns?node-id=18-85671&t=iPw0b1PGL6yKG1XP-11).

**Comment by hariombalhara** [comment]
@ciaranha Is the design that @anikdhabal shared good to go?
