### ISSUE TITLE
[CAL-3895] Increase the size of profile picture in the calendar booking page

### ISSUE THREAD

**Issue by Wisdom321321** [calcom/cal.com#15335]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3895](https://linear.app/calcom/issue/CAL-3895/increase-the-size-of-profile-picture-in-the-calendar-booking-page)</sub>

**Comment by gaurab-khanal** [comment]
@Wisdom321321  did you mean 
![image](https://github.com/calcom/cal.com/assets/40165867/b6d1ed7b-f873-475c-a210-b661e8f5d4f8)
the profile above the name?
If that is the issue you are trying to convey, I can fix it.

**Comment by Neon-20** [comment]
Hi, Can I work on this?
Thanks

**Comment by emrysal** [comment]
@Neon-20 I will close your pr as per "Needs approval" label. But I won't remove your branch so when @ciaranha approves this I will re-open.

As per:
> If this issue has a 🚨 needs approval label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
For clarity: Non-core member issues automatically get the 🚨 needs approval label.
Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by ciaranha** [comment]
Does this factor in team event types and group event types?

![CleanShot 2024-06-11 at 18 00 22@2x](https://github.com/calcom/cal.com/assets/4536123/ec2df478-3e18-4c85-adf7-048aaf8f4322)
