### ISSUE TITLE
have the second availability dropdown start after the value of the first one

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1534]
didnt come up with a better name for a ticket.

essentially have the second input start after 9:00 if the first input is 9:00 starting time (and not midnight)

![image](https://user-images.githubusercontent.com/8019099/149805923-fb0207e1-7ce2-4c76-a9f7-b4e3eedb15b4.png)

**Comment by jjromary** [comment]
I checked the Availability session and this functionality is already implemented.

![disponibilidade](https://user-images.githubusercontent.com/37199044/176949095-c8fad32e-d411-4c35-81eb-5d772606d885.jpg)
