### ISSUE TITLE
[CAL-3880] remove i18n for all <Meta> or figure out how to SSR

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15354]
we have a lot of key/string pairs in social media previews:

![image](https://github.com/calcom/cal.com/assets/8019099/7dd7b1d7-3ca1-44e5-9766-b55ec3cb5d68)

either option 1: we remove all t("no_meeting_found") etc. with  → "No meeting found" and enforce english for page titles

option 2: we figure out how to SSR the translations for Meta

<sub>[CAL-3880](https://linear.app/calcom/issue/CAL-3880/remove-i18n-for-all-meta-or-figure-out-how-to-ssr)</sub>

**Comment by adithyaakrishna** [comment]
@PeerRich IMO the easiest way would be to go with Option-1 but if we choose to go with option-2, we might have to use the locale param in the opengraph API along with SSR

**Comment by hunxjunedo** [comment]
Kindly assign this to me if the issue is still unresolved.

**Comment by akashMasih** [comment]
attempt #15354

**Comment by panzacoder** [comment]
@PeerRich Could you provide an example of a link that is incorrectly SSRing for different locales? Or is it all pages and only for certain locales? It seems from a quick peruse of the i18n code that server-side translations are already enabled so this ticket seems a bit more nuanced than just "figuring out" SSR.

Thanks in advance for any clarity you can provide!

**Comment by Suvendu-UI** [comment]
is it still open?

**Comment by arshad-muhammad** [comment]
@PeerRich since the issue is not closes yet i would like to work on this.

**Comment by sanduluca** [comment]
https://react.i18next.com/latest/ssr#using-the-usessr-hook
