### ISSUE TITLE
[CAL-3983] README fails to mention enterprise edition and its license

### ISSUE THREAD

**Issue by cweiske** [calcom/cal.com#15370]
### Issue Summary
The README states that cal.com is open source ("The open source Calendly successor"). The "License" section only states

> Distributed under the [AGPLv3 License](https://github.com/calcom/cal.com/blob/main/LICENSE). See LICENSE for more information.

The "enterprise edition" APIs and package a mentioned nowhere in the README, neither is the "philosophy":
> Our philosophy is simple, all "Singleplayer APIs" are open-source under AGPLv3. All "Multiplayer APIs" are under a commercial license.

It would be nice if the README would contain clear information about the real license and the [ee "philisophy"](https://github.com/calcom/cal.com/tree/main/apps/api/v2/src/ee).

### Steps to Reproduce

1. Read the README and decide the software suitable for your task
2. Spend two hours setting upcal.com on your local server
3. Find out that the Admin UI requires an enterprise license

### Actual Results

- README does not tell about the enterprise edition

### Expected Results

- README clearly describes the "open source for single users only" approach

Related: #633

<sub>[CAL-3983](https://linear.app/calcom/issue/CAL-3983/readme-fails-to-mention-enterprise-edition-and-its-license)</sub>

**Comment by PeerRich** [comment]
agree

**Comment by PeerRich** [comment]
will work on this

**Comment by PeerRich** [comment]
we will work on something similar to this: https://formbricks.com/docs/self-hosting/license

**Comment by PeerRich** [comment]
opened a PR https://github.com/calcom/cal.com/pull/15766

**Comment by cweiske** [comment]
Thank you.

**Comment by PeerRich** [comment]
thank you for reaching out!
