### ISSUE TITLE
[CAL-3913] Privacy Link Change

### ISSUE THREAD

**Issue by rw0007** [calcom/cal.com#15373]
### Is your proposal related to a problem?

On the bookings page I see following sentence "By proceeding, you agree to our [Terms](https://cal.com/terms) and [Privacy Policy](https://cal.com/privacy)." According to your help desk this cannot be customized.
I would like to translate the sentence and link to my privacy policy.

### Describe the solution you'd like

An option to customize the whole message incl. the links.

### Describe alternatives you've considered

Could not find any work around or alternative.

### Requirement/Document

<sub>[CAL-3913](https://linear.app/calcom/issue/CAL-3913/privacy-link-change)</sub>

**Comment by ameeetgaikwad** [comment]
Would like to work on this!

**Comment by DeepaPrasanna** [comment]
> Would like to work on this!

I think for issues with `feature` label, you can't start until they approve, add `🚨 needs approval` tag and remove it.

**Comment by ameeetgaikwad** [comment]
> > Would like to work on this!
> 
> I think for issues with `feature` label, you can't start until they approve, add `🚨 needs approval` tag and remove it.

alright!

**Comment by PeerRich** [comment]
go for it. this can be done via .env variables
