### ISSUE TITLE
[CAL-3905] Zoom integration Creates Two Calendar events

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#15384]
An organization customer shared that when Zoom app is connected, it creates two calendar events one that has the Zoom app connected and one that doesn't have the Zoom app connected

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3905](https://linear.app/calcom/issue/CAL-3905/zoom-integration-creates-two-calendar-events)</sub>

**Comment by PeerRich** [comment]
cant reproduce this 🤔

**Comment by shirazdole** [comment]
@milospuac is investigating - any updates from your calls Milos?
