### ISSUE TITLE
[CAL-3904] disable google-meet in user onboarding if google-calendar is not installed

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#15381]
in app store we can-not install google-meet unless we have installed google-calendar, but during the user onboarding flow we can. 
[https://www.loom.com/share/49a84fd58bb6475d8a44166b26c6014c?sid=cc871830-65b5-406d-a5e3-13b5de3038df](https://www.loom.com/share/49a84fd58bb6475d8a44166b26c6014c?sid=cc871830-65b5-406d-a5e3-13b5de3038df)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3904](https://linear.app/calcom/issue/CAL-3904/disable-google-meet-in-user-onboarding-if-google-calendar-is-not)</sub>

**Comment by PeerRich** [comment]
what if, instead, it asks you to install google calendar when clicking?

**Comment by SomayChauhan** [comment]
Hi @PeerRich @ciaranha 
![Screenshot 2024-07-09 at 4 19 34 PM](https://github.com/calcom/cal.com/assets/32706411/d70b4738-050e-4fa5-8460-9bd9fcf471f2)
Looking for some design suggestion

**Comment by SomayChauhan** [comment]
https://www.loom.com/share/14661885fa61484e87b8adc415357b73

perhaps this
