### ISSUE TITLE
Booked times are not taken into consideration when booking

### ISSUE THREAD

**Issue by DerpgonCz** [calcom/cal.com#1539]
### Issue Summary

When a booking is created, the time is still available to book even though it should not when no integrations are used.

### Steps to Reproduce

1. Login to account on cal.com
2. Book a 30min meeting at any available time
3. Open the calendar page again
4. Select the same day as before
5. Select the same time as before
6. Book a meeting again

Result:

![image](https://user-images.githubusercontent.com/3275947/149849607-4f4d6df8-72ab-495a-8bbe-1c4b308af822.png)

#### Expected result
The same time should not be available to book by another person.

**Comment by baileypumfleet** [comment]
Have you added any calendar integrations?

**Comment by DerpgonCz** [comment]
Like I said, "...when no integrations are used.".

All I am saying it should take the booked times into consideration.

Then a time is booked, it should not be bookable again by anyone else. When an event is set to require a confirmation, the time should be available, but the user should receive a notification if his booking was confirmed, and send a notification to all other users that booked the same time that their window was not confirmed (and preferably show a link to book a different time).

**Comment by duduribeiro** [comment]
I agree this behave is weird. 

I've setup cal and I don't have any calendar integration and anyone can book the same time with me because I still appear as available on the same booked time 😄

**Comment by PeerRich** [comment]
this has been fixed i believe. can you try again?
