### ISSUE TITLE
Allow setting Reminders per account and per meeting 

### ISSUE THREAD

**Issue by ianhyzy** [calcom/cal.com#1540]
### Is your proposal related to a problem?

When Cal creates an event on my Google calendar, it doesn't respect my default reminder settings and sets one reminder to be sent ten minutes before a meeting starts.

### Describe the solution you'd like

I would like Cal to use my default reminder settings, or allow me to set a reminder setting on my account or per event type. Respecting default is easiest but I could see a situation where I would want different reminders for different events.

**Comment by baileypumfleet** [comment]
Great idea, we'd love to work on this
