### ISSUE TITLE
[CAL-3922] Error with host name on email confirmation

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#15404]
When the hostname has an  (&) inside of the name. The confirmation email breaks and does not show the complete name.

on the hostname, I have Hello & World.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ba34150d-1ef9-41cd-b770-12a662cd6835/73562d4e-3fb5-4898-abf7-4a6860a3f6fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iYTM0MTUwZC0xZWY5LTQxY2QtYjc3MC0xMmE2NjJjZDY4MzUvNzM1NjJkNGUtM2ZiNS00ODk4LWFiZjctNGE2ODYwYTNmNmZkIiwiaWF0IjoxNzE4MTE1MTQwLCJleHAiOjE3NDk2NTExNDB9.dulhFHLaNbU9N1ETcdizAjdf1R5rMYGWZe9jjDPiquw)

To reproduce:

1. Create an organizer with & in the name: Hello & World
2. Make the event requiring confirmation.
3. Open the event link and book it.
4. The recipient will see Hello & World in the name.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3922](https://linear.app/calcom/issue/CAL-3922/error-with-host-name-on-email-confirmation)</sub>

**Comment by ubaish01** [comment]
Hey @joseuo94 , Unable to reproduce the issue. Can you check the linked image. 
![image](https://github.com/calcom/cal.com/assets/109113347/66fa6a72-6147-49fc-afef-d2a9155bd6cb)

**Comment by joseuo94** [comment]
Hey @ubaish01 make sure the booking requires booking confirmation.
