### ISSUE TITLE
Reminders (workflow) not getting sent

### ISSUE THREAD

**Issue by irobot1234** [calcom/cal.com#15411]
This seems to be a recurrent problem, since the past one week I have been using cal.com more often than not.. I love that it is a product which is simple and beautiful to use. The problem I am facing is that NO reminders are getting sent to my booked calls which is leading to increasing "no-shows"...Can you help ?

**Comment by irobot1234** [comment]
well, funnily enough it did work and I did get a reminder email an hour before the event is due to start, however, among all the details that were sent in that reminder email, the meeting URL inserted as {MEETING_URL}, is blank.. can you tell me the string to use in here that'll work?? maybe the {LOCATION} string?

also I am not a developer or so advance in my knowledge of coding so SQL query isn't something I can do..I am using the plain options available to me on my browser.. Could you explain to me my options accordingly??

**Comment by ciaranha** [comment]
@irobot1234 it seems like you have some varying issues, reminders not getting sent, then getting sent, then some questions about variables. Can you reach out to support in app with these queries as we may need to ask follow up questions to help you resolve this. I am closing this issue as there is no one clear bug for our developers to work on. There's a chat button in bottom right of app to ask for help.
