### ISSUE TITLE
[CAL-3926] Expand round robin availability beyond the default schedule

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#15416]
**Problem**

Currently with round robin event types, you can only use a person's default availability schedule

*User context:*

> We are reaching the limits of what we can achieve with the round robin's due to the limitations of what schedule's can be used for the [Hosts](http://hosts.ie/). They either all share a common one, which doesn't work us given the different times all our staff work, or it uses their default schedules only.
>
> We are hoping this could be expanded on to allow custom availability schedule per host for round robin event [types. As](http://types.As) we are reaching a bottle neck with our returning patients with our current use of single event types for each doctor, and the difficulty for us to check them one by one to find a doctor with a free timeslot.
>
> We are wanting to create a new round robin and enter patients back into it for follow up time slots, but without impacting the availability for new patients.

**Ideal scenario**

* Each user would be able to create a new availability schedule called “Returning patients” (already possible today)

* They could then add that specific schedule to a new round-robin event type called “Returning patient” etc. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3926](https://linear.app/calcom/issue/CAL-3926/expand-round-robin-availability-beyond-the-default-schedule)</sub>

**Comment by panzacoder** [comment]
@itsberkaya @ciaranha I see there is a Bounty but also that it needs design. Should I wait for designs before attempting?

**Comment by ciaranha** [comment]
Yep please wait we'll have designs by the end of the week.

**Comment by vijayraghav-io** [comment]
PFB proposed design and implementation -

https://www.loom.com/share/67d01ff0af33465fa0a5c38fdef375e9?sid=5fbadaf7-906b-4d48-9cb5-42d871634386

PR - https://github.com/calcom/cal.com/pull/15618

**Comment by ciaranha** [comment]
> PFB proposed design and implementation -
> 
> 
> 
> https://www.loom.com/share/67d01ff0af33465fa0a5c38fdef375e9?sid=5fbadaf7-906b-4d48-9cb5-42d871634386
> 
> 
> 
> PR - https://github.com/calcom/cal.com/pull/15618

Hey @vijayraghav-io this looks great. I think however it would be better to deal with the actual selecting of schedules in the availability tab, and to only do assignment in the assignment tab. I will mock up what I mean if it's not clear!

**Comment by vijayraghav-io** [comment]
Sure @ciaranha ,Thanks for your feedback, i got it.

**Comment by richardokonicha** [comment]
anyone working on this

**Comment by vijayraghav-io** [comment]
Yes @richardokonicha I am working on this,

**Comment by vijayraghav-io** [comment]
Found a issue with assignAllTeamMembers https://github.com/calcom/cal.com/issues/15653  while working on this.

**Comment by olivierlambert** [comment]
Hello, any news on this one? Thanks!

**Comment by Shpadoinkle** [comment]
will this also be manageable via the edit event type api for host assignment?

**Comment by vijayraghav-io** [comment]
> Hello, any news on this one? Thanks!

@olivierlambert  yes its being worked https://github.com/calcom/cal.com/pull/15618, waiting for some final reviews.
