### ISSUE TITLE
[CAL-3937] Confirmation email is not being send out when adding more attendees.

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#15439]
If we try to add more attendees 
upcoming bookings > edit> reschedule > add participants. it allows you to add another participant to the meeting but does not send a confirmation email to the new attendee.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a617e33f-6ac7-4d43-b464-77dd358d0a91/93769246-7df7-40df-b6a5-0a5b998d8721?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNjE3ZTMzZi02YWM3LTRkNDMtYjQ2NC03N2RkMzU4ZDBhOTEvOTM3NjkyNDYtN2RmNy00MGRmLWI2YTUtMGE1Yjk5OGQ4NzIxIiwiaWF0IjoxNzE4MzkwMjY2LCJleHAiOjE3NDk5MjYyNjZ9.FpsT4z1qAfT3kbEF-S7iZSLXIhw7jqyBYipNOYu8HFg)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fc2cff55-1f42-412f-8194-3ecf47ad336a/b8fff58f-e803-4b1d-a2d1-b70c7671c8b8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mYzJjZmY1NS0xZjQyLTQxMmYtODE5NC0zZWNmNDdhZDMzNmEvYjhmZmY1OGYtZTgwMy00YjFkLWEyZDEtYjcwYzc2NzFjOGI4IiwiaWF0IjoxNzE4MzkwMjY2LCJleHAiOjE3NDk5MjYyNjZ9.yPbSGbaR45mzLs5t2OtgAQjiHbJLa3dUW72y8uWo1YY)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b04dd6d4-6bce-4f4e-afb7-148a1dace6f6/5471a781-8510-4eee-aeea-fd3d6addebd1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iMDRkZDZkNC02YmNlLTRmNGUtYWZiNy0xNDhhMWRhY2U2ZjYvNTQ3MWE3ODEtODUxMC00ZWVlLWFlZWEtZmQzZDZhZGRlYmQxIiwiaWF0IjoxNzE4MzkwMjY2LCJleHAiOjE3NDk5MjYyNjZ9.2xCgQDuWJayzBgeL3KH3bYcBTO9IKXuNdcTDiV-0p4Q)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3937](https://linear.app/calcom/issue/CAL-3937/confirmation-email-is-not-being-send-out-when-adding-more-attendees)</sub>

**Comment by vijayraghav-io** [comment]
@joseuo94 not able to recreate this issue. Mail is sent to new attendee added.

https://www.loom.com/share/6cb89efd704f46c8a3bf5394a0c0e3cf?sid=cae54b95-5107-4b5a-9786-3ac71c86d273

**Comment by Preetam078** [comment]
@vijayraghav-io I also have seen you loom, I can see the fourth booker got the mail for event reschedule.

**Comment by vijayraghav-io** [comment]
@joseuo94 
As an update, yes this issue exists with the latest code . The confirmation mail is NOT sent to the NEW Attendee.
Apologies for my previous comment.
It seems this feature used to work earlier and some latest changes might have affected this mail trigger.

**Comment by hariombalhara** [comment]
I tried but I couldn't replicate the issue.

There is a weird unrelated issue that I saw in my account(where I don't receive reschedule emails at all) but I tested in a different account of mine and it works and the newly added guest does receive a reschedule email.
