### ISSUE TITLE
Creating a Webhook for Event Type of Team

### ISSUE THREAD

**Issue by jln13x** [calcom/cal.com#15449]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

- I am trying to create a webhook for a specific event type of my team
- I am using my personal api key for API Request. (There is no way to get an API key for a team right?)
- I have admin access to this team
- Fetching event types for a specific team id works
- POST `/webhooks` fails if the `eventTypeId` is from a team
- Probably related to `apps/api/v1/pages/api/webhooks/_post.ts` L84 because its being checked if the eventType belongs to the userId

### Steps to Reproduce

- Join a Team
- Get the Team ID of this Team
- Try to create a Webhook through the API with the `/v1/webhooks` endpoint

Example Payload:

```
{
  "subscriberUrl": "https://example.com",
  "eventTriggers": ["BOOKING_CREATED"],
  "active": true,
  "eventTypeId": ...
}

```

**Comment by alishaz-polymath** [comment]
We have team level access in V2, not in V1

**Comment by BrianUribe6** [comment]
@PeerRich  This issue is still happening on the V2 API, and it should be re-opened.  I'm the team owner and I get an HTTP 403 

when sending this request

```http
 POST https://api.cal.com/v2/event-types/{eventTypeId}/webhooks
 Authorization: Bearer Redacted
 Content-Type: application/json

{
  "active": true,
  "subscriberUrl": "<redacted>",
  "triggers": [
    "BOOKING_CREATED",
    "BOOKING_RESCHEDULED",
    "BOOKING_CANCELLED",
    "BOOKING_CONFIRMED",
    "BOOKING_REJECTED",
    "BOOKING_COMPLETED",
    "BOOKING_NO_SHOW",
    "BOOKING_REOPENED"
  ],
  "secret": "<redacted>"
}
```

It responds with 

```json
{
  "status": "error",
  "timestamp": "2025-06-04T19:06:18.343Z",
  "path": "/v2/event-types/{team-event-type-id}/webhooks",
  "error": {
    "code": "ForbiddenException",
    "message": "IsUserEventTypeWebhookGuard - User (<My User Id>) is not the owner of event type (<team-event-type-id>)",
    "details": {
      "message": "IsUserEventTypeWebhookGuard - User (<My User Id>) is not the owner of event type (<team-event-type-id>)",
      "error": "Forbidden",
      "statusCode": 403
    }
  }
}
```

This is clearly an authorization check issue. The team owner should be able to make this call to any event type in the team.
