### ISSUE TITLE
[CAL-3939] fix org banner

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15456]
before:

<img width="831" alt="image" src="https://github.com/calcom/cal.com/assets/8019099/5e627a88-4a2f-41f5-b742-f0f58056d7ed">

after:
<img width="931" alt="CleanShot 2024-06-17 at 14 10 42@2x" src="https://github.com/calcom/cal.com/assets/8019099/65c50d9e-4797-487e-a9e6-237cfa6ba0e8">

<sub>[CAL-3939](https://linear.app/calcom/issue/CAL-3939/fix-org-banner)</sub>

**Comment by theashishmaurya** [comment]
@PeerRich  let me know if i can solve this issue

**Comment by Preetam078** [comment]
Hello @PeerRich  Hi have implemented the UI as per the Requirement 
Here is the Screenshot Below 
<img width="1213" alt="Screenshot 2024-06-18 at 1 39 11 AM" src="https://github.com/calcom/cal.com/assets/81969353/69b08a54-adda-4660-a328-501f3b1ae436">


But What about The FallbackImage for the New Banner Avatar, Currently I am Dealing with the same Fallback Image as it is used in the Avatar Component, Here is the Screenshot Below 
<img width="877" alt="Screenshot 2024-06-18 at 1 39 21 AM" src="https://github.com/calcom/cal.com/assets/81969353/88b76e43-5d47-406a-b3b7-f077a210de11">


Suggestion: We also need to create a new Shimmer UI for the Banner Avatar, Currently we are dealing with the Avatar Shimmer only, Here is the ScreenShot

<img width="827" alt="Screenshot 2024-06-18 at 1 26 42 AM" src="https://github.com/calcom/cal.com/assets/81969353/7c67398a-ce60-4706-af6e-31a06b4318c2">

**Comment by theashishmaurya** [comment]
Hi @Preetam078  How you were able to access the organization? Because as of now I'm not able to enable it using the env.

**Comment by Preetam078** [comment]
HI @PeerRich, @sean-brydon is there any update on handling the Fallback Image in the New Banner UI, as I completed the hole development, just need a clarification on Fallback Image handling.

**Comment by PeerRich** [comment]
fallback? if no image is uploaded, dont show it
