### ISSUE TITLE
[CAL-3940] randomize "Tip Sidebar"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15458]
super easy, lets randomise this list, just in case people havent clicked through them:

<img width="251" alt="image" src="https://github.com/calcom/cal.com/assets/8019099/87f7dad3-24e0-4813-98a1-e74f2d3a4bf5">

<sub>[CAL-3940](https://linear.app/calcom/issue/CAL-3940/randomize-tip-sidebar)</sub>

**Comment by vijayraghav-io** [comment]
@PeerRich 
Please let me know if this is what expected

https://www.loom.com/share/25b64310e3624930a2cd6ae0ca0d87c0?sid=02b794fe-6bf5-41a4-adf6-68dee15e6c6d

**Comment by jscafe-dev** [comment]
@PeerRich Please review https://github.com/calcom/cal.com/pull/15469
Used lodash shuffle to randomize "Tips Sidebar"

**Comment by vijayraghav-io** [comment]
@PeerRich 
updated so that reshuffle/randomize happens automatically (without reload reqd) when there is no user focus.
https://github.com/calcom/cal.com/pull/15462

https://www.loom.com/share/d1eab1c4f91b4c43b2b155d111eb36be?sid=24bc5a44-a054-42aa-af4f-11b7ff9fd014

**Comment by jscafe-dev** [comment]
@PeerRich can you please clarify if we need to perform a shuffle after a certain interval? Or does it need to happen on page refresh?

**Comment by jscafe-dev** [comment]
hey @PeerRich just a quick reminder.

**Comment by PeerRich** [comment]
no interval

just whenever you visit the page

**Comment by jscafe-dev** [comment]
Cool. @PeerRich this PR does exactly what is asked https://github.com/calcom/cal.com/pull/15469
Please review and assign this issue to me.
