### ISSUE TITLE
[CAL-3932] Workflow variables in other language (spanish) not working

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#15450]
![Screenshot 2024-06-13 at 16.25.27.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/59fb13b5-ecb7-465c-b484-77483e0592f1/b75cabca-13c1-44b7-aeed-0372d9b1785f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81OWZiMTNiNS1lY2I3LTQ2NWMtYjQ4NC03NzQ4M2UwNTkyZjEvYjc1Y2FiY2EtMTNjMS00NGI3LWFlZWQtMDM3MmQ5YjE3ODVmIiwiaWF0IjoxNzE4NjA2MjUwLCJleHAiOjE3NTAxNDIyNTB9.JqrEk-vQdQOwYWH8gP2qU42ZvQg1e7zzvupP-avRaw4)

ripwallet is a customer

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3932](https://linear.app/calcom/issue/CAL-3932/workflow-variables-in-other-language-spanish-not-working)</sub>

**Comment by PeerRich** [comment]
marked as high priority, lets get this fixed and the customer notified when live 🙏
