### ISSUE TITLE
[CAL-3943] Zoom integration doesn't follow the zoom app settings for auto-record

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#15474]
![Screenshot 2024-06-18 at 10.05.46.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6a33141a-8d05-42dc-b3db-a3bafca54e32/3b421e60-5247-470c-a229-4533792a23bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy82YTMzMTQxYS04ZDA1LTQyZGMtYjNkYi1hM2JhZmNhNTRlMzIvM2I0MjFlNjAtNTI0Ny00NzBjLWEyMjktNDUzMzc5MmEyM2JiIiwiaWF0IjoxNzE4Njk4MTIzLCJleHAiOjE3NTAyMzQxMjN9.YbKMMfMzcUq7BtaR7N4FO2yYu__2o5wh-e9GBdBxGjc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3943](https://linear.app/calcom/issue/CAL-3943/zoom-integration-doesnt-follow-the-zoom-app-settings-for-auto-record)</sub>

**Comment by vijayraghav-io** [comment]
/attempt

This issue can be assigned to me, i am working on this -
- creating zoom api interface to fetch user settings ..users/me/settings
- retrieve recording settings from above api call
- call POST user/me/meetings with above setting

**Comment by sean-brydon** [comment]
> /attempt
> 
> @milospuac This issue can be assigned to me, i am working on this -
> 
> * creating zoom api interface to fetch user settings ..users/me/settings
> * retrieve recording settings from above api call
> * call POST user/me/meetings with above setting

Hey bud - we don't assign issues but please feel free to work on it and submit a PR

**Comment by vijayraghav-io** [comment]
sure @sean-brydon Thankyou!

**Comment by milospuac** [comment]
@sgriff96-brydon I think it also doesn't follow the password settings set in zoom. Link generated through Cal.com booking doesn't respect the password settings for the meeting. Can you include it into this one as well?

**Comment by vijayraghav-io** [comment]
@sean-brydon , this is generic implementation any future zoom user setting required can be easily updated.
https://github.com/calcom/cal.com/pull/15489

**Comment by achalliburton** [comment]
This item is not completed as reported here: https://github.com/calcom/cal.com/pull/15489
