### ISSUE TITLE
Add Website Field Type

### ISSUE THREAD

**Issue by rjhewitt3** [calcom/cal.com#15479]
I'm collecting prospective client's website address in the custom field section of my scheduler, but because it's plain text it keeps breaking my Zapier integration which requires a URL. For example, some people have entered "N/A" if they're a start up and don't have one yet. This breaks the zap run.

A website/URL validated field would be a great addition to the line up anyways—and would solve my headache!

**Comment by anikdhabal** [comment]
Yeah, that's true

**Comment by anikdhabal** [comment]
Yeah, there should be. Let me add.

**Comment by rjhewitt3** [comment]
Thanks @anikdhabal, that was fast! I'll look out for the PR merge.
