### ISSUE TITLE
[CAL-3944] Round robin event doesn't respect booking frequency limit

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#15477]
![Screenshot 2024-06-18 at 15.19.41.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/97fd1cf2-4a7e-44f1-999c-b72170eda855/247c0f5a-0587-4b2d-a3ca-15afcc6d3e8c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85N2ZkMWNmMi00YTdlLTQ0ZjEtOTk5Yy1iNzIxNzBlZGE4NTUvMjQ3YzBmNWEtMDU4Ny00YjJkLWEzY2EtMTVhZmNjNmQzZThjIiwiaWF0IjoxNzE4NzE3MDgyLCJleHAiOjE3NTAyNTMwODJ9.RTbIEc68OKJY2cRMDRaabaYSsl7RUy820Vb1v49r5cU)

Event type: [https://cal.com/team/wavo/discovery](https://cal.com/team/wavo/discovery)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3944](https://linear.app/calcom/issue/CAL-3944/round-robin-event-doesnt-respect-booking-frequency-limit)</sub>

**Comment by nishchal27** [comment]
@milospuac as per your concern you're expecting something like in the screenshot: A dynamic UI and a dynamic message based on the availability of the bookings for the current day or the next days
![cal com_booking_limit_ui](https://github.com/calcom/cal.com/assets/17685195/e63de912-72e3-4ef3-bc86-ae87afb590dd)

**Comment by ciaranha** [comment]
> @milospuac as per your concern you're expecting something like in the screenshot: A dynamic UI and a dynamic message based on the availability of the bookings for the current day or the next days? 

That's an ok solution @nishchal27 but a more ideal one is that the day just does not show as available at all like this:
![CleanShot 2024-06-19 at 22 32 29@2x](https://github.com/calcom/cal.com/assets/4536123/e12e9182-0866-4785-9f94-0f6cd812b1cc)

**Comment by nishchal27** [comment]
@ciaranha Yeah, you're right your approach is more reasonable

**Comment by nishchal27** [comment]
@milospuac this bug is fixed already, I have tried to reproduce this bug on live website it seems that the problem is solved
you can close this issue
