### ISSUE TITLE
[CAL-4159] Email address with ' (apostrophe) not accepted

### ISSUE THREAD

**Issue by andy-vdg** [calcom/cal.com#15471]
### Issue Summary

I've had someone try and use my scheduling page to book in but they couldn't because an email address with an ' (apostrophe) is not accepted as a valid email address. 

### Steps to Reproduce

1. Go to a scheduling page
2. Pick a date and time
3. Add an email address i.e. john.o'shean@domain.com
4. Address is not accepted

### Actual Results

- Email address not accepted

### Expected Results

- It should accept this email address as it is valid according to RFC5321/5322

### Technical details
Here's a regex that will correctly match all email addresses (according to ChatGPT)
```
^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$
```

### Evidence

![image](https://github.com/calcom/cal.com/assets/19990167/05b70170-87a9-4f88-9e36-de7ea53f031d)

<sub>[CAL-4159](https://linear.app/calcom/issue/CAL-4159/email-address-with-apostrophe-not-accepted)</sub>

**Comment by RajdeepDs** [comment]
@PeerRich 
Do we need to allow apostrophes in email validation for this page only, or should this change be applied across the entire application? While allowing apostrophes would improve compatibility with some email addresses.

**Comment by ciaranha** [comment]
> @PeerRich Do we need to allow apostrophes in email validation for this page only, or should this change be applied across the entire application? While allowing apostrophes would improve compatibility with some email addresses.

You should be able to book someone and sign up for an account with an email with an apostrophe.

**Comment by PeerRich** [comment]
ive never seen apostrophes in an email. didnt know that was a valid schema. i dont mind allowing it

**Comment by PeerRich** [comment]
we should be allowing it everywhere

**Comment by ciaranha** [comment]
> ive never seen apostrophes in an email. didnt know that was a valid schema. i dont mind allowing it

I've never seen one and I've seen a lot of Irish email addresses 😅 

![CleanShot 2024-06-21 at 11 59 59@2x](https://github.com/calcom/cal.com/assets/4536123/50bff455-bf9a-4ef1-b65c-b2f2094fef06)

**Comment by RajdeepDs** [comment]
Thanks for clarifying! I'm updating the email validations using regex, so an user with an apostrophe in their email, can able to sign up or book appointments.

**Comment by andy-vdg** [comment]
@ciaranha I hadn't come across it either before - but as luck would have it - this week I had two separate people from two different continents (UK and NZ) try and book in with a ' in their email address. 
Turns out even though Gmail doesn't allow it - Microsoft does. 
Thanks @RajdeepDs much appreciated.

**Comment by ciaranha** [comment]
> @ciaranha I hadn't come across it either before - but as luck would have it - this week I had two separate people from two different continents (UK and NZ) try and book in with a ' in their email address. Turns out even though Gmail doesn't allow it - Microsoft does. Thanks @RajdeepDs much appreciated.

Ah great to know, thanks for sharing @andy-vdg 🙏 Looks like we'll have a fix for this out pretty quickly!

**Comment by ArnavNath550** [comment]
Hi Guys!
I have just tried attempting this one, just take a look guys and see if this looks good ✨ 
attempt /#16348

Thank You,
AR. Nath
