### ISSUE TITLE
Transaltion for Dashboard Theme box is not available in all languages

### ISSUE THREAD

**Issue by Yasshu55** [calcom/cal.com#15480]
### Issue Summary

When we go to our profile, click on Appearance, and check the first theme box (Dashboard theme box), it is not translated into all the languages. It has correct translations in only 8 languages out of 26: Deutsch, Français, English, Hebrew (he), Hungarian (hu), Italiano, Português, and Chinese (zh-cn).

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

All the theme boxes in the appearance tab should be translated according to the user's selected language. However, not all the boxes are correctly translated into their selected language; only a few languages are fully translated and working.
### Actual Results

- Showing english language in 18 languages instead of correct translation

### Expected Results

- Show correct translations in all languages

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
![image](https://github.com/calcom/cal.com/assets/95294297/e5bca456-3d70-46ee-bc08-ccd5af3e34da) 
- For example in esponal language all the other boxes are correctly translated, whereas here the dashboard theme and its descprtion is in english only

![image](https://github.com/calcom/cal.com/assets/95294297/cbe8c868-67a0-431c-ad60-a78fea335280)
- As for the francais (and other mentioned 8 languages) are correctly translated

I would like to take up this issue and fix it

**Comment by PeerRich** [comment]
i looked at the timestamp and didnt see yours was first 

lemme try and merge both

**Comment by Yasshu55** [comment]
> i looked at the timestamp and didnt see yours was first
> 
> lemme try and merge both

Sure
