### ISSUE TITLE
[CAL-3951] Add input to change instant meeting duration

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#15499]
### Is your proposal related to a problem?

An input box in org event type settings to add waiting time for instant meeting

Requested by [https://calcominc.slack.com/archives/C04CWEU35NV/p1718298091875219](https://calcominc.slack.com/archives/C04CWEU35NV/p1718298091875219)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3951](https://linear.app/calcom/issue/CAL-3951/add-input-to-change-instant-meeting-duration)</sub>

**Comment by kmaity-9563** [comment]
hey i want to work on it
