### ISSUE TITLE
[CAL-558] Greenhouse Integration

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1549]
Be able to use [Cal.com](http://Cal.com) from Greenhouse to schedule meetings.

[https://greenhouse.io/](https://greenhouse.io/)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-558](https://linear.app/calcom/issue/CAL-558/greenhouse-app)</sub>

**Comment by leog** [comment]
I just filled in the integration request form at https://www.greenhouse.com/become-a-greenhouse-partner-integration-request-form to express our interest of building such an integration. I will keep this ticket updated with any progress.

**Comment by PeerRich** [comment]
any news here @leog ?

**Comment by leog** [comment]
> any news here @leog ?

@PeerRich forwarded you my attempt to get more info from Greenhouse.

**Comment by PeerRich** [comment]
we should use merge.dev here

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app
