### ISSUE TITLE
[CAL-584] Integromat / Make.com App

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1550]
similar to #1543 

<sub>[CAL-584](https://linear.app/calcom/issue/CAL-584/integromat-makecom-app)</sub>

**Comment by OvieMudi** [comment]
Hi @PeerRich, please can you provide more context on this feature?

**Comment by PeerRich** [comment]
take a look at our zapier app but for integromat / make

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by PeerRich** [comment]
doubled bounty ❤️

**Comment by ifndev** [comment]
As far as I know, a make.com app should be created on make's platform using existing api calls and webhooks from cal.com.  Does this fall into the scope of this repo ?

**Comment by sareensumanau** [comment]
@PeerRich Is this still up for grab ?

**Comment by ShaneMaglangit** [comment]
Right now, the only possible way to do this is through webhooks. To reduce friction, we need a way to have direct integration. I'll reach out to the Integromat team they can add a Cal.com app on their scenario editor and add templates for quick integration.

**Comment by shivamklr** [comment]
@aar2dee2 I see you are quite close to finishing this one. Let me know if you need my assistance here. Cheering for you 🥳

**Comment by aar2dee2** [comment]
> @aar2dee2 I see you are quite close to finishing this one. Let me know if you need my assistance here. Cheering for you 🥳

thanks, @shivamklr!

**Comment by aar2dee2** [comment]
thanks, everyone :)
