### ISSUE TITLE
[CAL-3959] Remove/Disable Duplicate button in Read Only mode of an event-type

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#15509]
Add a user to a team with MEMBER role. He can't create any event for that team. But for an existing event he sees duplicate button which errors in the end.

![image](https://github.com/calcom/cal.com/assets/1780212/16348238-fdde-4678-8e61-810c78c41c13)

<sub>[CAL-3959](https://linear.app/calcom/issue/CAL-3959/removedisable-duplicate-button-in-read-only-mode-of-an-event-type)</sub>

**Comment by pixelfact** [comment]
I am applying to this issue via [OnlyDust platform](https://staging-app.onlydust.com).

**Comment by AnthonyBuisset** [comment]
I am applying to this issue via [OnlyDust platform](https://staging-app.onlydust.com).

**Comment by DiveshHariani** [comment]
Hi, I have made an attempt to resolve this issue. Your feedback is welcome. Thank you!
