### ISSUE TITLE
reschedule will change the uid in the webhook payload

### ISSUE THREAD

**Issue by buschco** [calcom/cal.com#1551]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Book a appointment (I also tested with secret meetings and with or without metadata)
2. In the Mail to the appointment open the "Manage booking" link and reschedule the appointment
3. The `BOOKING_RESCHEDULED` webhook payload will have a different `uid`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out. https://www.whatsmybrowser.org/b/OQ7GJ
- Node.js version none
- Anything else that you think could be an issue.

**Comment by buschco** [comment]
As a fix, the `rescheduleUid` could be included in the payload.
I am sure there is a better solution, but this could be a good starting point.
https://github.com/calendso/calendso/pull/1557

**Comment by baileypumfleet** [comment]
Thanks for reporting this and submitting a PR! Our team will review this as soon as we can

**Comment by buschco** [comment]
I think this issue should be reopened.
I messed up the branch and the wrong thing was merged, so this issue was never addressed in any commit.

https://github.com/calcom/cal.com/pull/1556#issuecomment-1018587633

**Comment by PeerRich** [comment]
> I think this issue should be reopened.
> 
> I messed up the branch and the wrong thing was merged, so this issue was never addressed in any commit.
> 
> 
> 
> https://github.com/calcom/cal.com/pull/1556#issuecomment-1018587633

@alishaz-polymath
