### ISSUE TITLE
[CAL-3968] Desktop Apps Wishlist

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15538]
- [ ] [Native Notifications](https://docs.todesktop.com/recipes/sending-notifications)
- [ ] [storing data](https://docs.todesktop.com/recipes/storing-data)
- [ ] [badges for new bookings](https://docs.todesktop.com/javascript-api/app-icon-badging-bouncing-and-progress-bar)
- [ ] [application menu](https://docs.todesktop.com/javascript-api/application-menu)</div>

**Comment by nigrumpirate** [comment]
I'm eager to work on this. Could you please provide guidance on how to proceed?

**Comment by kmr-ankitt** [comment]
I am very much interested to over this. Can you assign me this?

**Comment by PeerRich** [comment]
just open a pr. no need to be assigned 🙏

**Comment by YashTote** [comment]
Is this a community only feature request? As I don't have 
the permission to access [CAL-3968](https://linear.app/calcom/issue/CAL-3968/desktop-apps-wishlist)

**Comment by PeerRich** [comment]
the link is identical. its just a copy of this ticket inside our linear

**Comment by DeepaPrasanna** [comment]
> How can i get more details on this as I do not have the permission for linear

Apart from team members, no one has permission for linear
