### ISSUE TITLE
Ability to respect personal schedule while using a common schedule

### ISSUE THREAD

**Issue by olivierlambert** [calcom/cal.com#15564]
Hi,

**First: thanks for your great product, always happy with it and how reactive you are to fix bugs. For this one, IDK if it's a bug or a feature, so I'll do my best to explain.**

### The problem

Right now, you have 2 options for an event:
* using the personal default schedule of every host that can be booked
* using a common schedule for all hosts

Option 2 is great, but it doesn't take the personal default schedule into account. I think it should, because otherwise, when using a schedule that might be on different timezone for the same purpose (eg a webinar on your product), you'd like to get slots that might NOT be doable for someone in one TZ, but doable for the whole team as living in multiple TZ.

Let me provide a real example with a round robin hosted event, a webinar:
* Dan is living in the US and CAN cover webinar slots late in CEST timezone (Paris time). Like 10PM for Europe on Thursday.
* Yannick is living in France, and he CANNOT cover this 10PM slot for obvious reasons (outside working hours).
* The webinar is only available at few slots per week, like 3 times a week, so we CANNOT use the personal schedule of every potential host, because that will be many many slots and we want to avoid this.

Right now, if we use the common schedule with few slots (like 10PM on Thursday), it happens than Yannick is sometimes selected in round robin, while he's NOT available at this time on his personal schedule. I don't know if it's expected or a bug.

### Describe the solution you'd like

Ideally, the solution should be checking both common schedule AND personal schedule to give available slots. Right now, it seems to ONLY check for common schedule, overriding the personal schedule.

### Describe alternatives you've considered

Creating different event (one for each timezone), but it defeats the Cal.com integration on your website, because one will have to choose the best event. It's not practical.

### Additional context

Happy to give more details/context if needed.

Thank you very much!

**Comment by vijayraghav-io** [comment]
should be solved by this issue - https://github.com/calcom/cal.com/issues/15416

**Comment by olivierlambert** [comment]
I've seen the demo, and it looks like a great solution! Thank you very much @vijayraghav-io for keeping me posted!
