### ISSUE TITLE
[CAL-3974] Multiple Slots.getSchedule requests being sent when typing email on booker page

### ISSUE THREAD

**Issue by Amit91848** [calcom/cal.com#15574]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When booking an event-type, entering email makes multiple requests for getSchedule. Tried with other question formats too but ig this is only broken for required email.

### Steps to Reproduce

1. Create event-type
2. Try making a booking for that event 
3. Open up chrome dev tools and check network tab

https://github.com/calcom/cal.com/assets/74371312/855b4d69-2781-4e88-af26-8154b1c11bde

### Actual Results

- Multiple unrelated requests are being sent 

### Expected Results

- No requests should be sent

<sub>[CAL-3974](https://linear.app/calcom/issue/CAL-3974/multiple-slotsgetschedule-requests-being-sent-when-typing-email-on)</sub>

**Comment by nishchal27** [comment]
These two Requests are called on every keystroke in the "Email address" field:

https://cal.com/api/trpc/public/slots.getSchedule
https://cal.com/api/trpc/public/checkIfUserEmailVerificationRequired

this happens when typing in "Email address" field only
