### ISSUE TITLE
[CAL-3975] Set background color to red for remove button in profile section

### ISSUE THREAD

**Issue by karanwaghh** [calcom/cal.com#15573]
### Issue Summary

In the profile section, the background of "Remove" button should change to red on hover. However, it has been observed that this functionality is not working as expected.

### Steps to Reproduce

1. Go to profile section
2. Hover on remove button

### Actual Results

- The background of remove button is not red
![image](https://github.com/calcom/cal.com/assets/115517304/20fb865a-24e4-4c35-a626-6f65dd888019)

### Expected Results

- The background color of remove button should be red on hover.

<sub>[CAL-3975](https://linear.app/calcom/issue/CAL-3975/set-background-color-to-red-for-remove-button-in-profile-section)</sub>

**Comment by karanwaghh** [comment]
If this issue is valid then I would like to work on this issue.

**Comment by VAISHNA1102** [comment]
@karanwaghh I would like to solve this issue. Can I take this issue?

**Comment by karanwaghh** [comment]
@VAISHNA1102 Ok

**Comment by PeerRich** [comment]
go for it. no need to ask
