### ISSUE TITLE
[CAL-3973] booking questions for long text: add min and max characters (both optionally) 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15577]
<img width="644" alt="CleanShot 2024-06-26 at 12 25 44@2x" src="https://github.com/calcom/cal.com/assets/8019099/ed818cec-728d-4077-a723-7be939e19db6">

validate: 

<img width="465" alt="CleanShot 2024-06-26 at 12 29 59@2x" src="https://github.com/calcom/cal.com/assets/8019099/52297652-b4e7-4048-a38e-1747ad4ef2b1">

<sub>[CAL-3973](https://linear.app/calcom/issue/CAL-3973/booking-questions-for-long-text-add-min-and-max-characters-both)</sub>

**Comment by rajeshj11** [comment]
@PeerRich 
![Screenshot from 2024-06-26 17-53-11](https://github.com/calcom/cal.com/assets/38752904/69828be3-5627-4870-9bb2-acbc00a00407)
I am not able to see those fields. may I know
which version you are using and also the browser

**Comment by rameshguditalu** [comment]
Even I don't see this Min Characters and Max. Characters changes in the code 
![image](https://github.com/calcom/cal.com/assets/82966243/1cb6a64d-839e-4743-ae82-7e534e78e3f5)

**Comment by rajeshj11** [comment]
> Even I don't see this Min Characters and Max. Characters changes in the code ![image](https://private-user-images.githubusercontent.com/82966243/343173872-1cb6a64d-839e-4743-ae82-7e534e78e3f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDkyMTgsIm5iZiI6MTcxOTQwODkxOCwicGF0aCI6Ii84Mjk2NjI0My8zNDMxNzM4NzItMWNiNmE2NGQtODM5ZS00NzQzLWFlODItN2U1MzRlNzhlM2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEzMzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDc4ZjgzMmZiMjcxODEyYTRlNDVkOWYxOWUwYTYwNThmOTQ4YTIzMTcxNGI0YzA5N2U0MGZmODY1NDA3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.grVyRtRW1FbfrUMfk37TXWDzQm-ozjhxk3vY6oslpiU)

Ok got it. we need those input fields for configuring the min and max characters right

**Comment by rameshguditalu** [comment]
@PeerRich Please provide more info on this requirement as we don't see Min Characters and Max. Characters from our end

**Comment by rajeshj11** [comment]
@sean-brydon hey, I did spent some time on this feature. Could you please review.
Added il8 and also handled the validations

**Comment by PeerRich** [comment]
the screenshot is meant to display how the new inputs should look like

the spec is to add those 

thats why they dont exist yet

**Comment by rameshguditalu** [comment]
> the screenshot is meant to display how the new inputs should look like
> 
> the spec is to add those
> 
> thats why they dont exist yet

Ok got it thank you.

**Comment by raza001** [comment]
> Even I don't see this Min Characters and Max. Characters changes in the code ![image](https://private-user-images.githubusercontent.com/82966243/343173872-1cb6a64d-839e-4743-ae82-7e534e78e3f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDA2NjAsIm5iZiI6MTcyMDUwMDM2MCwicGF0aCI6Ii84Mjk2NjI0My8zNDMxNzM4NzItMWNiNmE2NGQtODM5ZS00NzQzLWFlODItN2U1MzRlNzhlM2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA0NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNzIyZWQ0YWM4NTAxZDdhZjkwOTNkYjFiM2M1MDg1YTZhYjcxMzk2ZTYxYzhlYjEzOTg3ZTE1MjAwNTdiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aoNA3ivoZ8HpaLetuMMwxX7aKFoUu7zQD5qOJNpFRc0)

Bro it is  feature
