### ISSUE TITLE
Zoom does not appear as an option for team event types on self-hosted instance

### ISSUE THREAD

**Issue by mikelmao** [calcom/cal.com#15597]
### Issue Summary

Zoom does not appear as an option for Teams conferencing on self-hosted environments

### Steps to Reproduce

1. Set-up cal.com selfhosted
2. Upon configuring and installing, add Zoom as an app
3. Create a team
4. Create an event for the team
5. Even though the Zoom app is installed, the Zoom option does not appear under "location" for the team's event type

The other options (like cal.com video) do appear, yet zoom does not

### Actual Results

Zoom does not appear in the list of options under Location

### Expected Results

That zoom appears and is selectable as conferencing tool for team calendar types

### Technical details

- Self hosted
- Latest verison v4.2.2

### Evidence

![CleanShot 2024-06-27 at 17 15 03](https://github.com/calcom/cal.com/assets/1472972/e4e477a9-9ca7-4fb7-bbab-c36942e61ec8)

**Comment by anikdhabal** [comment]
Hey @mikelmao, currently, there is no option to select any installed app directly from the location field for the team Event type. Make any installed app your default app and select the organizer's default app, then we will use it.

**Comment by mikelmao** [comment]
Yup that did it! Thanks @anikdhabal :)
