### ISSUE TITLE
[CAL-3988] Two record icon in cal video in some cases

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#15608]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Go to any cal video room created before yesterday's release in which you are organizer 

![Screenshot 2024-06-28 at 12 53 52 PM](https://github.com/calcom/cal.com/assets/53316345/bdbe7b2e-d6fa-4036-a435-8714522d5572)

Affected users:-
- only organizer of the cal video meeting rooms created before 4.2.3 release 

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

<sub>[CAL-3988](https://linear.app/calcom/issue/CAL-3988/two-record-icon-in-cal-video-in-some-cases)</sub>

**Comment by PeerRich** [comment]
just to confirm there is no way to keep the default recording but with lower bitrate?
