### ISSUE TITLE
Allow restricting Google login to specific domains.

### ISSUE THREAD

**Issue by sammarks** [calcom/cal.com#1560]
### Is your proposal related to a problem?

I would like to enable Google login so it's easy for my teammates to create their own accounts on-demand. But currently, I can't restrict that to specific domains, so anyone would be able to create an account.

### Describe the solution you'd like

It would be nice to have an environment variable to be able to configure allowed domains for Login with Google (something like `GOOGLE_LOGIN_VALID_DOMAINS` or even just passing a comma-separated list of domains to `GOOGLE_LOGIN_ENABLED`).

### Describe alternatives you've considered

I can create accounts manually for my teammates, but that's relatively cumbersome. The other alternative is to leave the Google auth open to the public, which would allow others to create calendar accounts on our instance, which wouldn't be great 😄

**Comment by baileypumfleet** [comment]
This is something that we could build for the enterprise plan, but we probably wouldn't build this anytime soon, as it's not really applicable for our hosted solution.
