### ISSUE TITLE
[CAL-4047] Retrieve private URL or hashedLink through event-types API(s)

### ISSUE THREAD

**Issue by jfkisafk** [calcom/cal.com#15619]
### Is your proposal related to a problem?

Yes, this is a blocking issue to copy private urls from Raycast:
* related https://github.com/raycast/extensions/issues/13215
* related https://github.com/calcom/cal.com/issues/5106

### Describe the solution you'd like

We'd like a way to retrieve the hashedLink for the private URL through the APIs, either as:
* new key-value pair in the `GET /event-types` or `GET /event-types/{id}` response
* replacing the current `link` value in the response with the private URL in case user has it enabled.
* ...other alternative like a new API.

### Describe alternatives you've considered

No alternatives that I could find in the [API reference](https://cal.com/docs/enterprise-features/api/api-reference#the-basics).

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-4047](https://linear.app/calcom/issue/CAL-4047/retrieve-private-url-or-hashedlink-through-event-types-apis)</sub>

**Comment by sourabpramanik** [comment]
Is anybody working on this? If not then I would like to take this on

**Comment by ciaranha** [comment]
@sourabpramanik go for it.

**Comment by naman777** [comment]
@PeerRich @ciaranha can i work on this issue? Please assign it to me

**Comment by sourabpramanik** [comment]
> @PeerRich @ciaranha can i work on this issue? Please assign it to me

Hey @naman777 I am working on this thanks

**Comment by Stain19** [comment]
@sourabpramanik are u still working on this?

**Comment by sourabpramanik** [comment]
I am not having the bandwidth, please go ahead if you want to work on this @Stain19

**Comment by rkumar261** [comment]
@Stain19 are you working this?, If not, I'm interested in working on it.

**Comment by Stain19** [comment]
@rkumar261 No, not anymore. Go ahead 🤙

**Comment by shafiahmed12** [comment]
Hi @jfkisafk when you say 
replacing the current link value in the response with the private URL in case user has it enabled.

do you mean to change the value in the locations object when the type is set to link 
```
{
  "status": "success",
  "data": {
    "eventType": {
      "id": 1,
      "length": 60,
      "slug": "cooking-class",
      "title": "Learn the secrets of masterchief!",
      "description": "Discover the culinary wonders of the Argentina by making the best flan ever!",
      "locations": [
        {
          "type": "link",
          "link": "Add hashed link if private link is enabled"
        }
      ]
    }
  }
}
```

**Comment by jfkisafk** [comment]
Hey @shafiahmed12 , I just mean changing the `link` value for the eventType:

```json
{
  "status": "success",
  "data": {
    "eventType": {
      "id": 1,
      "length": 60,
      "slug": "cooking-class",
      "title": "Learn the secrets of masterchief!",
      "link": "...hashed link..."
    }
  }
}
```

**Comment by JOSU9435** [comment]
Is anyone currently working on this? If not, I would like to take it on.
