### ISSUE TITLE
Unable to create a new team on hosted platform

### ISSUE THREAD

**Issue by ConnorGargano** [calcom/cal.com#1562]
Found a bug? Please fill out the sections below. 👍

I am going to create a team within cal.com at https://app.cal.com/settings/teams however the button 'Create Team'
is unresponsive and nothing is happening, I am having this issue in multiple browsers.
Has anyone else reported this issue or is this an issue only happening to me?

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Head to app.cal.com/settings/teams
2. I press '+ New Team'
3. Type the name of the team
4. Press 'Create Team'
5. Then nothing happens, the button is unresponsive

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Due to being on the hosted platform, I would assume this is not working for multiple users.

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/L2MDH

**Comment by miguelnietoa** [comment]
It works in my case, do you still have the problem or is it already solved?

**Comment by zomars** [comment]
Hey @ConnorGargano can you try that flow with [this extension](https://birdeatsbug.com) so we can see the console and network calls?

**Comment by PeerRich** [comment]
@jamiepine you fixed this right

**Comment by ConnorGargano** [comment]
@zomars @PeerRich 

Looks to be working, it was actually the fact that the team name was already taken but I did not get any banner to say so.
Just no response.

Do you think a banner should be added or error box saying something like 'Team Name already taken'?

@zomars Here is what happened when I used the extension you provided: https://app.birdeatsbug.com/sessions/fxnJf-uCX7KX9K-wDqIB5?

**Comment by PeerRich** [comment]
@jamiepine build this already, i believe its not merged yet tho

**Comment by PeerRich** [comment]
fixed a long time ago
