### ISSUE TITLE
Sort order of team event types incorrect

### ISSUE THREAD

**Issue by verstratenbram** [calcom/cal.com#15636]
### Issue Summary

When changing the order of Event Types for a team, the order is not respected on the front-end. 

**_Note that this problem only occurs for team events._**

### Steps to Reproduce

1. Create a team
2. Add 3 or more events to the team
3. Change the event order
4. View the front-end page

### Actual Results

The order of the team events does not match the order in the back-end.

### Expected Results

The order of the team events on the front-end should match the order in the back-end.

### Technical details

The position field in the database appears to be updated correctly. The issue likely lies in how the records are fetched from the database.

### Evidence

![image](https://github.com/calcom/cal.com/assets/29309992/4b5471bf-70b6-4f15-ba95-227163f67063)

**Comment by fabio0296** [comment]
It's ok if take this one ? @verstratenbram
