### ISSUE TITLE
Problem with FB pixel

### ISSUE THREAD

**Issue by platonie** [calcom/cal.com#15645]
I tried to install a FB pixel. I  first install the FB meta pixel app on cal.com. I tried to follow the FB procedure. I create 3 pixels ( stupidely because I believed that I had made a mistake), but now, on my public page I got an error message : _No event type configured
PLATONIE / WINE TASTING has not configured an event type that you can book_

I have deleted the FB meta pixel app on cal.com, changed the URL but I still have the same error message.
I've put the original url back, as all my adverts were made using this url

How could I solve this big problem ? (because I made flyers with QRCode )

**Comment by platonie** [comment]
The problem is that PLATONIE / WINE TASTING" is not an event, this is the public page. It acts as if it is an event. This is not.
How can I solve this problem?

**Comment by ciaranha** [comment]
Duplicate: https://github.com/calcom/cal.com/issues/15650
