### ISSUE TITLE
Use correct translation key

### ISSUE THREAD

**Issue by RushikeshGandhmal** [calcom/cal.com#15656]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Use correct translation key

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by hariombalhara** [comment]
@RushikeshGandhmal I really don't understand what this issue is from the description

**Comment by RushikeshGandhmal** [comment]
Hi @hariombalhara,
I see, for event type google calendar is required got meet to work, redirecting the user to apps/google-calendar to install is better? what do u think ?
The key "event_type_requred_google_cal" isn't present anywhere.

https://www.loom.com/share/7f8ec97a78bc4f4ab56841935932da1d
