### ISSUE TITLE
[CAL-3996] Option to add guests through /bookings page

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#15663]
There is no direct way to add guests to a booking. User has to reschedule and then during the reschedule he can add more guests. But he has to ensure that he doesn't change the booking time during reschedule while adding the guests.

There could be a direct way to add guests on the /bookings/ page itself.

\- This came up as a problem faced by a user in Zendesk

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3996](https://linear.app/calcom/issue/CAL-3996/option-to-add-guests-through-bookings-page)</sub>

**Comment by anikdhabal** [comment]
Hey @hariombalhara fixed by this one https://github.com/calcom/cal.com/pull/14740

**Comment by SomayChauhan** [comment]
https://github.com/calcom/cal.com/pull/14740 -  only allows the organizer or host to add guests. However, I believe @hariombalhara is suggesting that the booker should also be able to add guests without needing to reschedule.

**Comment by hariombalhara** [comment]
I didn't think about the booker then but yeah it  makes sense to allow booker to do it too.

May be there could be a 'Add Guests' on booking success page as well.

**Comment by anikdhabal** [comment]
> #14740 - only allows the organizer/host to add guests. However, I believe @hariombalhara is suggesting that the booker should also be able to add guests without needing to reschedule.

Hey, it also allows booker to add guests.
