### ISSUE TITLE
[CAL-4028] Unable to reschedule due to rescheduleUid not being picked up although present in the url params

### ISSUE THREAD

**Issue by theonly1me** [calcom/cal.com#15665]
Discussed in #15640
<sub>originally posted by @Goul-duKat</sub>

Good day

We can not reschedule at all !
![Immagine 2024-07-03 152211](https://github.com/calcom/cal.com/assets/174621369/1d7ffca4-5cbb-4c51-9730-258a910f937b)

We are using all anonymous incoming users, so they don't need and will be not log ins in the system just managed on the single appointment for the personal information like email.

We started using cal.com with version  4.1.12 and now we updated to the 4.2.3, we seen this :
fix: Seat Attendee Rescheduling Logic by @joeauyeung in https://github.com/calcom/cal.com/pull/14784

But it was broken and still broken on last version.

Someone can take a look why we get the blue text and impossible to reschedule ?

Thanks
Cheers

_Originally posted by @Goul-duKat in https://github.com/calcom/cal.com/issues/15640#issuecomment-2206113744_
            

<sub>[CAL-4028](https://linear.app/calcom/issue/CAL-4028/unable-to-reschedule-due-to-rescheduleuid-not-being-picked-up-although)</sub>

**Comment by secretkontributer** [comment]
Can i work on this issue ?

**Comment by Goul-duKat** [comment]
The service is open on internet if someone want to test it, just i will not publish the whole url here for fear of DDOS or other attack, possible get in contact trough PM and i will give you the internet link for the site and you can try schedule and move the appointments

Just let me know of your tests and appointment to purge from system after the test, is already in production and touching our calendars

cheers

**Comment by Goul-duKat** [comment]
> The issue you're encountering, where rescheduling is not possible due to no available users despite the `rescheduleUid` being present in the URL parameters, can be caused by several conditions in the code:
> 
>     1. **Booking Status**: If the booking status is `CANCELLED` or `REJECTED`, rescheduling is not allowed.

Just freshly created, not cancelled or rejected.

[...]
Technical stuff, i'm not with hands trough the code, we just cooked a dokker image to use for an office schedule

> 
> To resolve this issue, ensure the following:
> 
>     * The booking is not cancelled or rejected.

They are not

> 
>     * The booking has a valid event type or dynamic event slug reference.
> 
>     * For seated events, ensure a seat reference UID is provided, and the user is either logged in and is a host or the owner of the event type.
> 
>     * Ensure that there are available users associated with the event to generate the reschedule link.

We are using the end page after you schedule, or the email link when you got the appoinment
All your questions are more technical
In the server there is just 1 user, the admin who have the office schedule published, no other users nor team configured.

**Comment by Goul-duKat** [comment]
This issue is related to : https://github.com/calcom/cal.com/issues/15862

Using together limits and reschedule give off this problem

I did removed the limits now and i can reschedule all the appointments

**Comment by CarinaWolli** [comment]
> Using together limits and reschedule give off this problem

Thanks for confirming this. Will close this issue in favor of: https://github.com/calcom/cal.com/issues/14584
