### ISSUE TITLE
[CAL-4002] [ApiV2] enable setting locale field for managed user

### ISSUE THREAD

**Issue by ThyMinimalDev** [calcom/cal.com#15688]
Post and Patch managed user should enable updating the locale of a user, locale is set to "en" by default, class validator should make sure we are not passing invalid values

check: 
/apps/api/v2/src/modules/users/inputs/update-managed-user.input.ts
/apps/api/v2/src/modules/users/inputs/create-managed-user.input.ts
PATCH apps/api/v2/src/ee/me/me.controller.ts
POST /apps/api/v2/src/modules/oauth-clients/controllers/oauth-client-users/oauth-client-users.controller.ts

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4002](https://linear.app/calcom/issue/CAL-4002/[apiv2]-enable-setting-locale-field-for-managed-user)</sub>

**Comment by fabio0296** [comment]
Hi @ThyMinimalDev can you explain further this?
For my understanding this is to add the abillity to set the user locale at the time of creation and updating a managed user?
