### ISSUE TITLE
bug: messed up stored timezones

### ISSUE THREAD

**Issue by albertborsos** [calcom/cal.com#15714]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

related PR:
https://github.com/calcom/cal.com/pull/15392

I think this PR messed up my (and I am sure all other user's) whole Availability.

This overwrote my saved timezone from Europe/Budapest to America/Sao Paulo.

And my booking page shows my whole calendar free for normal looking appointments, but the real appointments were in America/Sao Paolo timezone, so customers booked appointments for midnight instead of afternoon. And customers thought it is an appointment for afternoon, because it looked like afternoon....

I saved for Europe/Budapest, and now after 10 minutes it is America/Guatemala again...

Please rollback to 4.2.3

### Steps to Reproduce

1. Start booking and you will see it.

### Actual Results

- Maybe my stored timezone is overwritten by other users?

### Expected Results

- I can use my saved timezone on my booking page.

### Technical details

- I have locked timezone on my events.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by albertborsos** [comment]
And it happened third time:

<img width="385" alt="Képernyőfotó 2024-07-09 - 23 29 02" src="https://github.com/calcom/cal.com/assets/7307145/3b930863-2d7d-4746-a45b-48d4bdd85c02">

**Comment by itsstevenliu** [comment]
Hi, I'm experiencing the same here.. somehow my availability timezone was also changed to Sao_Paulo. This is an urgent issue
 
<img width="1175" alt="image" src="https://github.com/calcom/cal.com/assets/151034963/09fd491e-3bd8-470b-9de3-33b81e026ae8">

<img width="881" alt="image" src="https://github.com/calcom/cal.com/assets/151034963/49928ff6-6945-4c7b-a95e-435a56d5963c">

**Comment by hjonasson** [comment]
Confirm that it happened here as well.

**Comment by emrysal** [comment]
Hi @albertborsos @hjonasson & @itsstevenliu - 37 minutes after this issue was first reported by @albertborsos we reverted to v4.2.3; we're currently investigating impacted users and what went wrong.

**Comment by albertborsos** [comment]
@thgh I think it just overwrote your setting after the deploy. If you correct your timezone, than it stays as you saved it. Since the rollback it is working for me.

**Comment by PeerRich** [comment]
resolved
