### ISSUE TITLE
[CAL-4007] booking questions: ability to disabled input if url is prefilled

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15712]
give people the option to lock certain identifiers and if the URL parameter exists, disable the input:

<img width="588" alt="image" src="https://github.com/calcom/cal.com/assets/8019099/e13b7e73-27e9-4880-8bad-0aadf6fe3f72">

if this is active, and the link is: cal.com/peer/meet?**email=john@example.com** it should lock the email input.

<img width="436" alt="CleanShot 2024-07-09 at 20 43 32@2x" src="https://github.com/calcom/cal.com/assets/8019099/217a3ca4-629a-483f-b428-2906e3c14682">

ideally we can lock every identifier (also custom questions)

<sub>[CAL-4007](https://linear.app/calcom/issue/CAL-4007/booking-questions-ability-to-disabled-input-if-url-is-prefilled)</sub>

**Comment by cherish2003** [comment]
@PeerRich can i work on this issue ?

**Comment by Naveed-baig** [comment]
I can't understand the problem , Can you please describe what should be disabled and on which condition ?

**Comment by shirazdole** [comment]
@PeerRich any updates here? 

@hariombalhara - I'm wonder if we should have some kind of "legend" in the routing forms tab that makes it easy to know how to execute functions like this

**Comment by Aspireve** [comment]
Hey Hi!!
mihir5827 (from Discord) suggested that I try to solve this issue, could I solve it?

**Comment by rajeshj11** [comment]
Hello Everyone,

I have made significant progress on this issue and would appreciate any collaboration to help expedite its resolution. I am currently waiting for feedback from the team. If you have any suggestions, please leave them in the comments.

You can review the pull request here: [PR #15715](https://github.com/calcom/cal.com/pull/15715).

I am actively working on this and am open to collaboration. Please note that the bounty for this issue will be split based on contributions. If you have any contributions or ideas, feel free to share them.

Thank you!

**Comment by shirazdole** [comment]
Checking if this is live? I tried this link and doesn't look like it's working:

[cal.com/peer/meet?email=john@example.com](http://cal.com/peer/meet?email=john@example.com)

**Comment by hariombalhara** [comment]
Nope. It isn't live yet, just merged. Will be with next release.

Also, this option isn't enabled by default. You have to enable it per booking field

**Comment by hariombalhara** [comment]
@shirazdole This is live now
