### ISSUE TITLE
[CAL-4025] Invalid Input received on Attendee Address

### ISSUE THREAD

**Issue by aidandaly24** [calcom/cal.com#15727]
### Issue Summary

I'm currently helping a friend utilize Cal's in-line embed set up for an event. The event utilizes "In Person (Attendee Address)". When I test out the form after embedding it into the site it always throws an invalid input error on the Address section.

### Steps to Reproduce

1. Create Event for a calendar
2. Set location to "In Person (Attendee Address)"
3. Go to advanced tab
4. Click edit for Location inside Booking Questions
5. Change label for the question and save the event type
6. Go to event type link OR Embed into your site and test address

### Actual Results
<img width="1268" alt="Screenshot 2024-07-10 at 11 02 01 PM" src="https://github.com/calcom/cal.com/assets/99039782/191c5b45-b695-469c-b621-5bc2cc096119">

<img width="607" alt="Screenshot 2024-07-10 at 11 02 22 PM" src="https://github.com/calcom/cal.com/assets/99039782/a976e900-06a6-4304-baf8-90480fea43e9">

<img width="433" alt="Screenshot 2024-07-10 at 10 58 40 PM" src="https://github.com/calcom/cal.com/assets/99039782/ce2a7b36-fd0a-4acd-a9d1-995c2694ab8f">

### Expected Results

- The address be accepted

### Technical details

- Utilizing GoDaddy Website Builder
- Testing on Chrome latest version

### Evidence

- This was tested by embedding the in-line code given to me through cal.com to a Go Daddy Website Builder, then publishing the website and testing.

<sub>[CAL-4025](https://linear.app/calcom/issue/CAL-4025/invalid-input-received-on-attendee-address)</sub>

**Comment by MohitRathi1** [comment]
please may i new in which file is this form is

**Comment by aidandaly24** [comment]
How can I replicate that? I am still having the same issue.

**Comment by vijayraghav-io** [comment]
Yes this issue occurs irrespective of embed or non-embed ,when booking question is created with location identifier.

**Comment by vijayraghav-io** [comment]
Steps to recreate the issue -

https://www.loom.com/share/dd1094dca81d48039de31521f4bc6561?sid=79e39a7e-fd3d-412c-a50a-ec85bf2444c4

**Comment by Amit91848** [comment]
> How can I replicate that? I am still having the same issue.

@aidandaly24 You can change location and then set it back to attendee address but don't change the label for it. Please bear with us until we can get this issue fixed 


https://github.com/calcom/cal.com/assets/74371312/48212a7f-a5e9-41eb-863b-f9920a7324ee

**Comment by vijayraghav-io** [comment]
Root cause and detailed steps to recreate:

1. Create a new eventType
2. Edit the new eventType created
    1. Edit -> EventSetup (Tab) -> Location - change to ‘In Person (Attendee address)’
    <img width="958" alt="Screenshot 2024-07-12 at 12 57 31 PM" src="https://github.com/user-attachments/assets/68cba695-7acc-4b29-965a-5ee099ff3554">

    2. Things will be fine until now, and everything works just fine until you go to the ‘Advanced’ Tab and click on ‘Edit’ Button for Location inside Booking questions
    3. Once you click on Edit button. The following LOC will change type of booking field from radioinput to string
    https://github.com/calcom/cal.com/blob/c7c5cdf133bca0393d00314227de33957fb1e594/packages/features/form-builder/FormBuilder.tsx#L245
   <img width="1103" alt="Screenshot 2024-07-12 at 1 09 49 PM" src="https://github.com/user-attachments/assets/fac6ce23-bb79-471f-a70a-0b5f500dcb6f">

    4. But the booking form expects the location to still be object , Hence the input_error was occurring without much detailed message
    
3. Hence the zod-util.ts file is updated with z.union so that the location field can be either an object or a string. This accomodates the location field to be either object or string  and elimanates input_error in booking input form.
4. Also getBookingData.ts is updated to show the exact address if location is a string instead of radio input
