### ISSUE TITLE
Respect "Start of week" Setting also on Availability Dashboard

### ISSUE THREAD

**Issue by masteradhoc** [calcom/cal.com#15749]
### Issue Summary & Steps to Reproduce
Currently the account settings allow to override the default Start of the week.
As per my current settings the Start of the week is set to Monday.

Settingslink: https://app.cal.com/settings/my-account/general
![image](https://github.com/user-attachments/assets/2e6c259e-f6a8-40b8-a1a6-60054bc42be2)

On the Availability Overview Dashboard the set working hours still show Sunday first: https://app.cal.com/availability
![image](https://github.com/user-attachments/assets/4c86cb9f-e7f7-4a27-9af7-1a43eee9c419)

Please make sure to respect the Start of the Week Setting also on the Availability Dashboard.

### Actual Results
On Availability Dashboard still the Times show from Sunday to Saturday

### Expected Results
Based on the Setting the Start of Week Setting should be respected.
In our Case times should be Mondy - Sunday.

**Comment by vijayraghav-io** [comment]
Should be fixed by https://github.com/calcom/cal.com/pull/15753
https://www.loom.com/share/259b91928d0847f4af87e94808bee955?sid=f8716acf-ec14-4595-b78d-f66ee1853596
