### ISSUE TITLE
[Feature Request] Single-use link

### ISSUE THREAD

**Issue by fpellet** [calcom/cal.com#15776]
### Is your proposal related to a problem?

I'd like to be able to invite someone to make an appointment, and prevent them from using this link later to make another appointment.  
There's a feature that comes close to doing this by making the private event. You can then generate a single-use link. However, this doesn't meet my needs, because I can't invite several people at the same time, each with a unique link.

### Describe the solution you'd like

I'd like to be able to generate as many private links as I want.

### Describe alternatives you've considered

As a workaround, I can juggle several events, but it's complicated

### Additional context

An expiry date or a list of links still active with the option of deactivating them would be a bonus.

### Requirement/Document

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by abhinav700** [comment]
@fpellet According to what I can understand, following are your requirements.

Create a share event icon instead of copy link icon  with following features : 
 - generate one time link which cannot be used again to book an event
 - generate a  normal link which can be used repeatedly to generate options
 
 and the above functionalities should be available for secret events only. 

Am I correct?

**Comment by Souptik2001** [comment]
Raised a PR for this feature request!

Here's a demo -

https://www.loom.com/share/cb93616c775a4704bdc7590c6c1aa58e?sid=06bb210e-fd7b-4772-827a-e1d77e460ff3

cc: @anikdhabal @ciaranha

**Comment by fpellet** [comment]
Awesome! It meets my needs perfectly!

If it's simple to do, an icon to generate a new one-click link from the event list, as @abhinav700 suggested, would be icing on the cake.
