### ISSUE TITLE
Minor feature request: Add a sign out button to onboarding

### ISSUE THREAD

**Issue by Just-Moh-it** [calcom/cal.com#15787]
### Is your proposal related to a problem?

I usually log in and out of different accounts on cal.com to manage people's calendars. Sometimes, I log in via the wrong email and I get the onboarding screen, where the only way to exit is to clear cookies, and it's generally a bad experience

### Describe the solution you'd like

Having a sign out button on the onboarding page

![CleanShot 2024-07-16 at 2  56 58@2x](https://github.com/user-attachments/assets/96b508e1-1ebb-4dfb-93b3-8ac3d5fe7c54)

### Describe alternatives you've considered

N/A

### Additional context

For example, here's how reflect.notes does it

![image](https://github.com/user-attachments/assets/040a761c-3b5f-4b24-b184-86c6cf1a5431)

### Requirement/Document

N/A

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by ashishnd** [comment]
Hey @Just-Moh-it, @kemiller! I would like to give this feature request a shot! Should I go ahead with trying to integrate the necessary feature request?
