### ISSUE TITLE
[CAL-4052] Timezone select should show the selected timezone

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#15819]
Timezone select should show the selected value when select box is opened
![image](https://github.com/user-attachments/assets/1abf8f20-0374-4764-a823-31f9a78d294f)

https://www.loom.com/share/142198bce6ea47b7ae881a75c595e925

<sub>[CAL-4052](https://linear.app/calcom/issue/CAL-4052/timezone-select-should-show-the-selected-timezone)</sub>

**Comment by suprabhu77** [comment]
@hariombalhara  may i know the exact path where I can get this location tab?

**Comment by hariombalhara** [comment]
This is booking page of an event that I named location

**Comment by suprabhu77** [comment]
@hariombalhara 
https://github.com/calcom/cal.com/pull/15838
Can you review this PR?
