### ISSUE TITLE
Prevent two people booking one slot, even if first is pending

### ISSUE THREAD

**Issue by mmkal** [calcom/cal.com#15813]
### Is your proposal related to a problem?

We have a flow where patients go through an intake, and near the end, they book a video call with a doctor. Then, they complete the intake and pay us (not using cal.com payment, our own thing). Then our backend confirms the booking via API, but that can be several minutes after the meeting is booked.

Our traffic is spiky, so we will definitely get patients who both book the same slot, so the way it works now guarantees one of them will be rejected, and will have to book another appointment. Which is obviously a bad customer experience, and seems avoidable.

### Describe the solution you'd like

A toggle under "Requires confirmation" that says "Block pending slots" or similar. (I'd also be happy with making this the default or the non-configurable behaviour but @milospuac suggested some customers actually like having potential conficts... 🤷)

### Describe alternatives you've considered

calendly.com

### Additional context

Because of this feature, we are going to have to disable "Requires confirmation" entirely, meaning we will have "confirmed" appointments even for patients who drop off at the subsequent steps of our intake, and we will have to try to catch those cases and cancel them, which will be messy - but we have to do this because we want to err on the side of good customer experience vs our own effort.

### Requirement/Document

N/A

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by CarinaWolli** [comment]
Hi @mmkal, we just implemented this new feature https://github.com/calcom/cal.com/pull/16335. It will be live with with the next release and I think this would solve your issue 🙏

**Comment by mmkal** [comment]
Nice, thanks! CC @ariariel
