### ISSUE TITLE
RFC: Migrate to a monorepo

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#1581]
I'm borrowing @jamiepine original proposal and expanding upon it:

# Cal.com Monorepo Proposal

We're in the middle of big changes and the need to share code between new projects is increasing. This RFC is to discuss the best way to handle a posible migration to a monotipo approach.

The best contender so far IMO is [Turborepo](https://turborepo.org). It plays nice with our Vercel-based setup, is easy to use and quite performant. Suggestions are always welcome.

## Migration process

Here are some strategies we could follow:

- [Migrating to the monorepo](https://medium.com/lgtm/migrating-to-the-monorepo-582106142654)
- [Preserving Git Histories when Migrating other Projects to your Nx Workspace](https://nx.dev/migration/preserving-git-histories)

### Migration steps

- [ ] Create a new orphan branch
  ```
  git switch --orphan monorepo-migration
  ```
- [ ] Initialize new Monorepo
  ```
  npx create-turbo@latest
  ```
- [ ] Migrate Calendso
  ```
  git remote add calendso git@github.com:calcom/cal.com.git
  ```
  ```
  git fetch --all
  ```
  ```
  git read-tree --prefix=apps/web -u calendso/main
  ```
  ```
  git add apps/web
  ```
  ```
  git commit -m "Migrated cal.com to apps/web"
  ```
  ```
  git checkout main
  ```
  ```
  git pull --rebase
  ```
  ```
  git rebase monorepo-migration
  ```
  ```
  git push --force
  ```

### Existing PRs

We should strive to leave as less open PRs as possible for doing the migration.

We could solve this rather quick, at the expense of losing history and author information, is to apply a patch. We can get one for a PR by adding .diff to the end of the URL, and saving the contents to a file (let’s call it pr_patch). You can link to the original PR and stuff in the commit message, which is just-about good enough.

```
# assuming pr_patch exists with PR diff
git apply pr_patch --directory=apps/calendso
rm pr_patch
git commit...
```

## Requirements

- We should be able to handle private repos as package/modules.
- We should be able to preserve git history for every single repo.

## Structure

| Folder        | Purpose | URL | 
|---|---|---|
| `apps/web`        | The user facing app | app.cal.com |
| `apps/console`    | (**private**) The admin dashboard | console.cal.com |
| `apps/api`        | Both REST API endpoints and tRPC resolvers | api.cal.com |
| `apps/docs`        | Our current docs website | docs.cal.com |
| `apps/website`        | (**private**) Our marketing website | cal.com |
| `packages/ui` | Shared UI components | |
| `packages/font` | Our custom made Cal font | |
| `packages/lib`        | Shared logic and database CRUD | |
| `packages/prisma`     | Database schema | |
| `packages/config`     | Shared eslint/prettier config | |
| `packages/tsconfig`     | Shared TS config | |

`app`, `console` and `api` all have their own `pages` directory which we can use "Multi Zones" from Next.js to serve three separate deployments. 

Currently we have `pages/api/*` and `server/router/*` for our API and tRPC resolvers respectively. API routes feel weird served up from the same pages folder as the base app, and tRPC resolvers could be confused as being the primary API. In this re-structure they live together in an `api` directory and share logic from `lib`.

### Tests

Each of these directories have their own respective `tests` folder for modularity, I believe this will help encourage tests to be written and each layer of our application isolates concerns. `api/tests`, `api/tRPC/tests`, `lib/tests`, `components/tests` etc...

### Licensing

Instead of having a dedicated folder for `ee` we can license specific areas of our application accordingly.

**Comment by PeerRich** [comment]
looks really good already!

we also have /docs/ and /font/

**Comment by PeerRich** [comment]
i wonder if we find alternative names for the root folder `apps` 

maybe `core`?

**Comment by PeerRich** [comment]
do we even need the top folder?

why not

| Folder        | Purpose |
|---|---|
| `web`        | The user facing app |
| `console`    | (**private**) The admin dashboard |
| `api`        | Both REST API endpoints and tRPC resolvers |
| `docs`        | Our current docs website |
| `website`        | (**private**) Our marketing website |
| `packages/ui` | Shared UI components |
| `packages/lib`        | Shared logic and database CRUD |
| `packages/prisma`     | Database schema |
| `packages/config`     | Shared eslint/prettier config |
| `packages/tsconfig`     | Shared TS config |

**Comment by zomars** [comment]
> do we even need the `apps` folder?

That's a Turborepo default and it kinda makes sense.

**Comment by zomars** [comment]
Updated migration steps

**Comment by jamiepine** [comment]
> Updated migration steps

Very clever concept for preserving the git history. I'm just wondering how existing PRs will be affected if merged post monorepo migration? We could possibly test this on a fork of the repo if need be.

**Comment by zomars** [comment]
> > Updated migration steps
> 
> Very clever concept for preserving the git history. I'm just wondering how existing PRs will be affected if merged post monorepo migration? We could possibly test this on a fork of the repo if need be.

Added section for Existing PRs:


### Existing PRs

> We should strive to leave as less open PRs as possible for doing the migration.
> 
> We could solve this rather quick, at the expense of losing history and author information, is to apply a patch. We can get one for a PR by adding .diff to the end of the URL, and saving the contents to a file (let’s call it pr_patch). You can link to the original PR and stuff in the commit message, which is just-about good enough.
> 
> ```
> # assuming pr_patch exists with PR diff
> git apply pr_patch --directory=apps/calendso
> rm pr_patch
> git commit...
> ```

**Comment by PeerRich** [comment]
looks like the RFC has been resolved? or are more comments required? If not, I'll unpin and close this

more issues (like moving apps/website and apps/ui) can be created separately

**Comment by zomars** [comment]
Closing!
