### ISSUE TITLE
[CAL-4053] When users opt for annual pricing charged same day

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#15822]
Currently, when users opt for annual pricing, the initial charge is charged same day, but any subsequent added users are charged AT THE END of the ANNUAL billing period. 

Ideal behavior is we wait four hours and then batch together any added / deleted users within those four hours and charge the customer on one invoice. 

So if a customer adds 30 users between 12p and 2p, they should then receive a batched invoice at 4p with the four hour timer starting at the 12p point and an automatic charge to their billing on file. 

@keithwillcode I believe this is high priority 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4053](https://linear.app/calcom/issue/CAL-4053/when-users-opt-for-annual-pricing-charged-same-day)</sub>

**Comment by hmacr** [comment]
@keithwillcode I'd like to work on this if this is approved for implementation.

**Comment by PeerRich** [comment]
this would be solved with the trial period
