### ISSUE TITLE
Text in Embed Code Becomes Invisible on Selection

### ISSUE THREAD

**Issue by anku909** [calcom/cal.com#15832]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When selecting the provided embed code with the mouse, the selected lines become invisible (less visible) due to the text color and background color is same.

### Steps to Reproduce

1. Go to the Embed section of the calendar.
2. Try to select the text with the mouse.

### Actual Results

- On selection text is not visible.

### Expected Results

- When selected, the text should be visible.

### Evidence
![Screenshot_2024-07-19_10_18_37](https://github.com/user-attachments/assets/e5967851-daf9-4887-9ae1-e903269058bb)

**Comment by jenish-thapa** [comment]
Hey @PeerRich, I would like to work on this issue.

**Comment by surjeet88** [comment]
Hi Anku,

As I understand, when we select the embed code to copy, it becomes hard to see due to the text color and background color being the same. Is that correct?

I can work on improving this. Please let me know if there are any specific preferences for the colors.

**Comment by anikdhabal** [comment]
This issue only occurs in the React embed code and has already been fixed in the HTML embed.
