### ISSUE TITLE
"A new recurring event has been scheduled." in text/plain part of every approve request email

### ISSUE THREAD

**Issue by nepomuc** [calcom/cal.com#15848]
### Issue Summary

Every request for approval email to the organizer hat the text "A new recurring event has been scheduled." in it's plain/test part, even though the event is no recurring event.
It's quite confusing, since a bunch of mobile email clients use the plain/text part of an email to show the first sentence of an email below the title in the email list view.
**Should be very easy to fix, since the text is already not in the html part of the email.**

### Steps to Reproduce

1. Book an appointment for an event type that needs approval and then look at the text/plain part of the email the organizer received from the system.

### Actual Results

- Every approval request email contains "A new recurring event has been scheduled.". 

### Expected Results

- This sentence should only be in the email when it's actually a recurring event request.

### Technical details

- cal.com [v.4.2.3-sh] @ Docker

**Comment by od-hunter** [comment]
Can I be assigned this please?

**Comment by nepomuc** [comment]
> Hi @nepomuc ,Can I be assigned this please?

Sorry, I don't have any permissions to assign this issue to you. You can solve it and create a PR though.

**Comment by punitive1729** [comment]
@nepomuc raise a PR: https://github.com/calcom/cal.com/pull/15855
