### ISSUE TITLE
Screen sharing on other devices (iPad)

### ISSUE THREAD

**Issue by aleksandrakalas** [calcom/cal.com#15845]
### Is your proposal related to a problem?

I am always frustrated when I have to join a call in which I need to share a whiteboard. I would want to share from my iPad so that I can write more legibly. 

### Describe the solution you'd like

Please add an option on other devices to be able to share screens. Specifically on iPads. 

### Describe alternatives you've considered

I've tried using whiteboards on my laptop but this creates messy writing which is illegible. 

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

**Comment by ciaranha** [comment]
@aleksandrakalas are you using Cal.video? Have you tried using a different video conference app like Zoom?

**Comment by aleksandrakalas** [comment]
@ciaranha Yes I'm using Cal.video, we recently switched over as it provided a more seamless booking experience. So there isn't any chance that allowing additional sharing support is going to be changed in the near future?

**Comment by ciaranha** [comment]
@aleksandrakalas I'll check with the app that we use to provide the video service but I don't believe  it's something we have in our control to add.

**Comment by aleksandrakalas** [comment]
@ciaranha were you able to see if the app provides this feature?
