### ISSUE TITLE
[CAL-4058] managed event types: hovering over "Managed" should show a <Tooltip>: "Managed by {NameOfAdmin}"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15857]
the "Managed" badge should have a tooltip

i.e.: "Managed by Peer Richelsen"

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/772d919a-74f0-44dd-bcda-d6b63533dd5b/0c29376a-20dd-4dc2-b7b0-3e98dd36aa30?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83NzJkOTE5YS03NGYwLTQ0ZGQtYmNkYS1kNmI2MzUzM2RkNWIvMGMyOTM3NmEtMjBkZC00ZGMyLWI3YjAtM2U5OGRkMzZhYTMwIiwiaWF0IjoxNzIxNjM3MTM4LCJleHAiOjE3NTMxNzMxMzh9.JIGP2e0Ygxbw8vtWXhE9g0N1UiOhRURMMlFf8-wIZ5M)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4058](https://linear.app/calcom/issue/CAL-4058/managed-event-types-hovering-over-managed-should-show-a-tooltip)</sub>

**Comment by krishnendusukumar** [comment]
how to retrieve the {nameofadmin}?
