### ISSUE TITLE
Unintented access to all team bookings for a member of team via api ( update , cancel , e.t.c ) 

### ISSUE THREAD

**Issue by Shaik-Sirajuddin** [calcom/cal.com#15852]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A member of team is able to gain access to team bookings ( update , cancel , e.t.c ) in case of round robin event type , even if the user is not present as round robin host

- A team has A , B , C as its members
- Event Type X has scheduling type set to round robin with A , B as hosts 
- When a new user E books a meeting , one of A , B is assigned based on availabilty
- User C is not present in event type or booking in any form
- User C is able to cancel registered booking in above scenario via api

### Actual Results

- User is able to cancel a team booking , irrespective of involvement in the specific booking

### Expected Results

- User should only be able to cancel a team booking  , if the user is present in the booking ( as a host , attendee e.t.c )

### Evidence

Loom : [Video](https://www.loom.com/share/03416c6a934547748f9f948038e03cdb?sid=0fbc3d0b-2e1b-40fa-95b7-c1d246ebec98)

**Comment by Shaik-Sirajuddin** [comment]
In general admin of team would have access for all team bookings
Unsure whether this is expected behaviour

**Comment by Amit91848** [comment]
In case User C is owner / admin of the team, it can delete / modify any bookings of that team irrespective of whether the user is in the booking or not.  There is a PR open to allow admin / owner to cancel the booking via the app too

**Comment by CarinaWolli** [comment]
Can confirm that currently, members can access all team bookings. Members should only be able to access bookings they are part of
