### ISSUE TITLE
Links aren't rendering on cal.com/faq

### ISSUE THREAD

**Issue by Spiteless** [calcom/cal.com#15869]
### Issue Summary

Links on the `cal.com/faq` page aren't rendering

### Steps to Reproduce

1. Went to [cal.com/faq](https://cal.com/faq)
2. Clicked on `Where can I find the desktop app?`
3. Observed text `Having said that, if you would like to download and install our desktop app click here` and expected a link to be on `click here`

### Actual Results

- No link rendered on `click here`, see screenshots

<details>
<img width="992" alt="image" src="https://github.com/user-attachments/assets/8e1abd28-5114-4442-989c-e66cde3018f1">
<img width="696" alt="image" src="https://github.com/user-attachments/assets/668a409a-252e-4df2-a7a7-769537de8401">

<summary>Screenshots</summary>
</details>

### Expected Results

- Expected `click here` to go to the provided resource.

### Technical details

- Chrome Version 126.0.6478.127 (Official Build) (arm64)

Same behavior on 
- Firefox Version 127.0.2 (64-bit)

### Evidence

- Was reading `/faq` and wanted to check out the links :(

**Comment by anku909** [comment]
In the footer section of cal.com there is a Desktop App link : https://cal.com/download
 
![image](https://github.com/user-attachments/assets/45c8e40e-0a43-474e-9a63-f464523af388)

**Comment by harshsbhat** [comment]
does anyone know what directory we are storing these in?

**Comment by PeerRich** [comment]
the website repo is closed source. we will fix this. thank you for reporting

**Comment by Spiteless** [comment]
Thanks @PeerRich !
