### ISSUE TITLE
[CAL 4.2.3] Malfunction with limits

### ISSUE THREAD

**Issue by Goul-duKat** [calcom/cal.com#15862]
With CAL 4.2.3
when a new user try to schedule an appointment with a new email of the same host domain of someone else already present, it get impossible to schedule the appointment because of limit reach. But this person is a new person and not present in all the others appointments.

I needed to disable the limit check to make them schedule appointment correctly.

I think there is a malfunction on the logic of the check

![Immagine 2024-07-22 133054](https://github.com/user-attachments/assets/462e1121-b38a-429e-8812-2368bbf4ebc5)

**Comment by Souptik2001** [comment]
@Goul-duKat The meaning of this "Limit booking frequency" which you are talking about is - "How many times this event can be booked."

So, for example you set it to "1 per day". Then this translates to - "This event can be only booked 1 time in a day (irrespective of who is booking)". So, if you book before me then I will no longer be able to book. This Limit is not related to an user, this is related to the event itself.
So, your settings is "1 per year", which means only one booking can be made for this event in a year.

As far I know currently there is no feature to limit the booking by user.

Tagging @anikdhabal in case I am wrong.

**Comment by Goul-duKat** [comment]
> @Goul-duKat The meaning of this "Limit booking frequency" which you are talking about is - "How many times this event can be booked."

Per person ? 
I think is a waste if is just how many time can be booked total, because 1 time a year is like meh !?

> 
> So, for example you set it to "1 per day". Then this translates to - "This event can be only booked 1 time in a day (irrespective of who is booking)". So, if you book before me then I will no longer be able to book. This Limit is not related to an user, this is related to the event itself. So, your settings is "1 per year", which means only one booking can be made for this event in a year.

So how can i limit users who spam booking ? How to limit a person to book only 1 time and not book all the slots ?
There is no control and limit of it, you get the point ?
How to limit spammers ? I was thinking it was this tool
Otherwise how to keep spammers at bay ? 

> 
> As far I know currently there is no feature to limit the booking by user.

Ok so i really think it is needed because of problems exposed ;-)
Thanks
Cheers

> 
> Tagging @anikdhabal in case I am wrong.

**Comment by Goul-duKat** [comment]
Possible to have a per person limit of appointment locked on the email of the subscriber ?
Already having issue with people booking more appointment that they are meant too, cheers

**Comment by CarinaWolli** [comment]
> Possible to have a per person limit of appointment locked on the email of the subscriber ? Already having issue with people booking more appointment that they are meant too, cheers

Could you create a feature request for this?

I am closing this issue as it's no bug and that's how the booking limit feature currently works
