### ISSUE TITLE
Booking page vs Availability Time issues

### ISSUE THREAD

**Issue by francestanchanco** [calcom/cal.com#1586]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

For some reason, the time that appears on the booking page does not match the availability I set. 

I have set the availability for the booking to be 2:30pm - 3:00pm MWF

On the booking page, it is showing up as 10:30pm even though it is in the correct time zone. 

I have updated general availability to the correct range, but for some reason a 10:30pm session is still appearing. 

I have also made sure that the account time zone is correct.

We have temporarily fixed the solution but we had to change the availability time to 6:30am-7am on this page in order for it to appear correctly on the booking page 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
thank you for submitting! @emrysal can take a look at this

**Comment by andreaestefania12** [comment]
Hi, I would like to contribute to this issue. Could you assign it to me, please?

**Comment by PeerRich** [comment]
hey @andreaestefania12 assigned to you!
