### ISSUE TITLE
Add "first day of week" settings for teams

### ISSUE THREAD

**Issue by eazyAlf** [calcom/cal.com#1589]
### Is your proposal related to a problem?

Yes, indeed.
People that book meetings (especially when there is a timeslot every day) get easily confused by the layout starting on sundays.

### Describe the solution you'd like

Either global settings or add to team settings.

### Describe alternatives you've considered

Right now I have turned of all 7 day meetings so that it's more clear where the week starts but that isn't really an alternative for weekend bookings.

**Comment by milospuac** [comment]
Thanks for your feedback. Our team will have a look at this, and I'll upvote this for the next round of product improvements.

**Comment by milospuac** [comment]
Hey there! I just tested this out and your team should have the same Monday - Sunday setting as your profile. Change the first day of the week in your [Profile Settings](https://app.cal.com/settings/profile)

**Comment by eazyAlf** [comment]
Hi there,

I have a self hosted instance with the most updated version running on it.

I have tried re-setting the profile, creating a new team and a new event. It's fine on my personal page, it doesn't work for the team.

How can I help figuring out whats wrong?

**Comment by eazyAlf** [comment]
Personal:

![image](https://user-images.githubusercontent.com/58122515/152157343-d87b3fa3-077b-4e30-bbf8-1b08a4bf5eef.png)

Team:

![image](https://user-images.githubusercontent.com/58122515/152157553-af2ac9d8-1cba-4875-8dff-3b1d84286db2.png)

**Comment by eazyAlf** [comment]
@milospuac I just reinstalled, updated and tested this again on three machines with different local settings, too. When you create a team and you create an event for that team, regardless of the settings of the admin/user that owns the team: week starts on sunday.

**Comment by eazyAlf** [comment]
@milospuac wouldnt you say this is a bug actually? is this expected behaviour? shouldn't team day be according to profile day
