### ISSUE TITLE
Bug Report: 500 Error on Email ID Verification and Non-Functional "Go Back" Button (bug)

### ISSUE THREAD

**Issue by girishc24** [calcom/cal.com#15911]
### Issue Summary

When a new user signs up through email ID verification, If We click on Verify Email showing a 500 error is displayed. Despite the error, the email verification is completed successfully. Additionally, the "Go Back" button on the verification page is not functioning correctly.

![image](https://github.com/user-attachments/assets/854822b2-5659-46f1-a6ab-cf62adffb7bb)

### Steps to Reproduce

1. Go to the signup page.
2. Enter the necessary details to sign up with an email ID.
3. Click on the verification link sent to the email.
4. Observe the 500 error displayed after clicking the verification link.
5. Note that the email verification is still completed.
6. Attempt to click the "Go Back" button.

### Expected behavior

- No 500 error should be displayed after email ID verification.
- The email verification should complete without any errors.
- The "Go Back" button should function correctly and navigate to the previous page.

### Screenshots

https://www.loom.com/share/c9acdc33e32144d29fbce763bb9a3835?sid=9cc29db8-4bfd-41e3-a16f-45644c7b610c

**Comment by Mihir867** [comment]
Hi, I encountered the same issue and would like to work on it

**Comment by CarinaWolli** [comment]
This should be fixed already, @girishc24 feel free to reopen if you are still experiencing this issue 🙏

**Comment by girishc24** [comment]
Now it's Working 
Thanks
