### ISSUE TITLE
Dashboard Theme: system default incorrect card image

### ISSUE THREAD

**Issue by hichemfantar** [calcom/cal.com#15913]
### Issue Summary

The `System default` theme setting in the appearance settings renders the incorrect image.

### Steps to Reproduce

1. go to https://app.cal.com/settings/my-account/appearance
2. set dash theme to `dark`
3. dark image is shown
4. set theme to `system default` which is also dark
5. light image is show

### Expected behavior

dark image is shown when system theme is dark

### Other information

related to #15284

### Screenshots

theme `dark`
![image](https://github.com/user-attachments/assets/0e95eb24-c7e1-4b5d-b19a-65bac4663aa8)

theme `system default dark`
![image](https://github.com/user-attachments/assets/9fda9fdf-c143-4118-af36-eef27e8555e2)

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: macOS
- Browser: Chrome
```

**Comment by Souptik2001** [comment]
cc: @anikdhabal 👆
