### ISSUE TITLE
Add Custom Meeting Link

### ISSUE THREAD

**Issue by pavlvsd** [calcom/cal.com#15936]
### Is your proposal related to a problem?

I want to be able to share a static meeting link. I want to be able to record a podcast interview using VDO.ninja. It would be great to have a single link for this purpose.

### Describe the solution you'd like

I would love to have a custom field that allows for a custom meeting link for the Calendar Event Setup.

### Describe alternatives you've considered

I typically use solutions like Zoom, but would love a free high quality podcast interview recording option similar to VDO.ninja.

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by ciaranha** [comment]
@pavlvsd can you not just add it like this?

![IMG_7818](https://github.com/user-attachments/assets/31cea6b2-9a6e-4fd2-8876-002775f11ea3)

**Comment by pavlvsd** [comment]
That’s exactly what I was looking for!! Thanks so much! I feel silly for
not seeing it earlier. Appreciate the help.

**Comment by ciaranha** [comment]
Not your fault @pavlvsd ! Glad we have what you need!

**Comment by SamAmann** [comment]
I was wondering if there could be a way to add a randomized slug?

Something that would turn:
![image](https://github.com/user-attachments/assets/a407aa95-3674-4773-acb8-19b89738cc93)
Into:
![image](https://github.com/user-attachments/assets/4a565378-bf40-4e4c-bd40-f9e97033d15c)
when using the link.
