### ISSUE TITLE
[CAL-4076] Under available variables for custom event, we should inform about availability of booking question responses as well

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#15968]
Show more 
![image](https://github.com/user-attachments/assets/4bd931e1-9b6e-48e6-a87b-a2e7619a87b9)

e.g. for custom event name
![image](https://github.com/user-attachments/assets/d56ea855-3976-432d-9a21-41a990fba0ef)

This is what it looks like after booking
![image](https://github.com/user-attachments/assets/733d1e55-b020-4077-9328-96a9e15f0006)

owner1-acme@example.com was the booker/scheduler email. It is the value of {email} variable provided by Booking Questions. Any custom booking question data is also available for use

<sub>[CAL-4076](https://linear.app/calcom/issue/CAL-4076/under-available-variables-for-custom-event-we-should-inform-about)</sub>

**Comment by anikdhabal** [comment]
Yeah, we should show
