### ISSUE TITLE
The page needs a better UI When trying to reach an app that hasn't been already installed under an account

### ISSUE THREAD

**Issue by milkiyas-web** [calcom/cal.com#15973]
**Problem Description**
When trying to install/setup an app that hasn't already been installed in your account for example: cal.com/apps/make/setup 
You will see the page below. and i think it needs a little improvement.

![calsetup](https://github.com/user-attachments/assets/bade9608-5ae0-4db1-a164-91d6b4e3c163)

**Steps to reproduce**
head to cal.com/apps/<appname>/setup     

**Solution could be**
A centered avatar that could describe there is no such app, paragraph and a button to redirect to go to the appsotre.

**Comment by Mihir867** [comment]
Can I work on this @ciaranha  ?

**Comment by ciaranha** [comment]
@Mihir867 we'll create designs first. Once the 'needs design' label is removed it's good to go.

**Comment by itsberkaya** [comment]
https://www.figma.com/design/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=22458-19150&m=dev

**Comment by Mihir867** [comment]
Hi @ciaranha, I am working on this !!

**Comment by asharamseervi** [comment]
Hey @itsberkaya There is a hidden icon, I believe that is unintended, right?

<img width="444" alt="Screenshot 2024-08-07 at 9 01 18 PM" src="https://github.com/user-attachments/assets/d0600e2e-b879-4db6-a2dc-e456c1bb9d7a">
