### ISSUE TITLE
[CAL-4077] Already reviewed users/teams shouldn't be marked for review again (SMS sending)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#15987]
After accounts are marked as reviewed or unlocked for SMS sending in `/settings/admin/lockedSMS` they should not be locked or marked for 'review needed' again. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4077](https://linear.app/calcom/issue/CAL-4077/already-reviewed-usersteams-shouldnt-be-marked-for-review-again-sms)</sub>

**Comment by od-hunter** [comment]
Hi @CarinaWolli ,Is this open for contribution? If yes, can I be assigned please?

**Comment by CarinaWolli** [comment]
> Hi @CarinaWolli ,Is this open for contribution? If yes, can I be assigned please?

Hi @od-hunter! Yes, freel free to work on it :)  We don't assign to issues, just make sure to link the issue to your PR
