### ISSUE TITLE
[CAL-4081] Don't prefill country code in phone number input

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#15989]
Right now the country is automatically selected in the phone number input field. However, this is not always accurate and sometimes the wrong country code is selected. We want to remove the automatic prefill and users should enter the full phone number with country code themselves.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4081](https://linear.app/calcom/issue/CAL-4081/dont-prefill-country-code-in-phone-number-input)</sub>

**Comment by navneetthakor** [comment]
Hello @CarinaWolli I am interested in working on this issue. I am experienced in MERN stack and Next.js and that's why I strongly believe that I can solve it. Could you please assign it to me?

**Comment by Ishaani-14** [comment]
Hello @CarinaWolli can you please attach a video of this issue

**Comment by drmicheleross** [comment]
please allow for a default country to picked in the settings. For example, my clients all come from US and no one is typing "1" before their phone number, leading to wrong country code being picked. The UK autopopulates usually (incorrectly), leading to reminder texts being sent to wrong number.

**Comment by Sarthak-Sidhant** [comment]
@PeerRich is this not fixed yet?

**Comment by mrhut10** [comment]
i've just had this issue with a business thats only in australia so needed the `+61` area code prefilled on the phone number.

using the react-embed I found this fixed it. to be clear only setting the smsReminderNumber field actually fixed it

<img width="668" height="646" alt="Image" src="https://github.com/user-attachments/assets/e71368ff-02d0-4b0f-8cfa-d3052c7b1710" />
