### ISSUE TITLE
Whitelabelling event types 

### ISSUE THREAD

**Issue by FranBte** [calcom/cal.com#16043]
### Is your proposal related to a problem?

When someone books a meeting, they see the default name in my profile attached to the event type. They also see this name as the sender of the email invite. I need to be able to pick the name depending on which event they're booking.

### Describe the solution you'd like
It would be great to be able to be able to choose the name attached to an event type. I have multiple small products that I manage and would need to change the name depending on the business so I can white label each individual event type. 

I would like to select the name I want to display per event type in the same way that I select the calendar to book. 

### Describe alternatives you've considered

Right now, I just use my own name instead of my company name since I need to speak to people coming in across multiple products. 

### Requirement/Document

N/A

(P.S. I love cal.com; this is such a great tool 🙏)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by PeerRich** [comment]
i’m not sure if i get this. you can already have dynamic / custom event titles in advanced settings
