### ISSUE TITLE
[CAL-4102] Org Account Not Deactivated After Failed Payment

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#16045]
Supposedly, a team will remain active until the end of the billing cycle after cancelling. Once it reaches the end of the billing cycle, the webhook with the cancel event trigger which should run the downgrade logic.

We believe that this does not work for orgs right now cc @hariombalhara @zomars 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4102](https://linear.app/calcom/issue/CAL-4102/org-account-not-deactivated-after-failed-payment)</sub>

**Comment by CarinaWolli** [comment]
@hariombalhara @zomars is this still relevant?

**Comment by zomars** [comment]
@CarinaWolli this should be already addressed by #15366

**Comment by CarinaWolli** [comment]
> @CarinaWolli this should be already addressed by #15366

Nice 👌🏻
