### ISSUE TITLE
[CAL-4110] Whatsapp template in Spanish (Cal.com in Spanish), gets sent in English

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#16073]
![Screenshot 2024-08-05 at 14.56.40.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c863e236-8562-4ae9-a0f2-dce8e6a9fbc6/7842b033-30cd-4bb4-844b-9bcbd0b43f4d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jODYzZTIzNi04NTYyLTRhZTktYTBmMi1kY2U4ZTZhOWZiYzYvNzg0MmIwMzMtMzBjZC00YmI0LTg0NGItOWJjYmQwYjQzZjRkIiwiaWF0IjoxNzIyODYyNjYwLCJleHAiOjE3NTQzOTg2NjB9.Sz7iNi5pRjcvEYESUox74YAPqZbVO7ZGra-tK3MGsN8)

![Screenshot 2024-08-05 at 14.56.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b853e65e-dc84-49a2-a303-3ff3b3f490f6/12c18001-7b7f-48c4-b20b-fdb6b4eb49e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iODUzZTY1ZS1kYzg0LTQ5YTItYTMwMy0zZmYzYjNmNDkwZjYvMTJjMTgwMDEtN2I3Zi00OGM0LWIyMGItZmRiNmI0ZWI0OWU0IiwiaWF0IjoxNzIyODYyNjYwLCJleHAiOjE3NTQzOTg2NjB9.FHFzz8b7U6_JdbG0t6Ec9Fasnp2gnSXCc1dunHaCkUU)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4110](https://linear.app/calcom/issue/CAL-4110/whatsapp-template-in-spanish-calcom-in-spanish-gets-sent-in-english)</sub>

**Comment by CarinaWolli** [comment]
The message body for whatsapp shouldn't be editable and is only available in English. Closing this issue in favor of: https://github.com/calcom/cal.com/issues/16067
