### ISSUE TITLE
[CAL-4114] Hide Admin API Key from Individuals and Teams View

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#16079]
Only display to organization customers 

Instead of linking enterprise sales booking link, link cal.com/sales

cc @alishaz-polymath 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4114](https://linear.app/calcom/issue/CAL-4114/hide-admin-api-key-from-individuals-and-teams-view)</sub>

**Comment by PeerRich** [comment]
not urgent, is it?
