### ISSUE TITLE
[CAL-4130] App: workrooms.workplace.com

### ISSUE THREAD

**Issue by nathansudo** [calcom/cal.com#16077]
### Is your proposal related to a problem?

When adding other video links, it's frustrating to just be able to provide the link and not give it a clear name so it's easier for the user booking to understand where we're meeting.  

### Describe the solution you'd like

I would like to be able to add a name similar to how Zoom, Google Meet, Whatsapp etc have the name of the place you are meeting vs just a URL in the booking form. 

For example, I want my guests to meet in Virtual Reality in an app called Horizon Workrooms but the URL looks like this: https://workrooms.workplace.com/groupcall/LINK:acrkldyciflv/

I'd rather if it could say Horizon Workrooms in the booking form.  Or even Horizon Workrooms via Meta Quest or Video. 

### Describe alternatives you've considered

For now, I have just added the link but it's not clear, it could also be great to have some way to see more instructions in a tooltip or small description for custom locations. 

### Additional context

See that the URL if longer also extends past the UI so the custom name would help a lot with this issue too. 

![CleanShot 2024-08-05 at 14 18 27@2x](https://github.com/user-attachments/assets/59948fe5-39df-44ef-8bfb-226d1bc036cf)

### Requirement/Document

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

<sub>[CAL-4130](https://linear.app/calcom/issue/CAL-4130/app-workroomsworkplacecom)</sub>

**Comment by asharamseervi** [comment]
Hey @nathansudo, This is a small yet great add-on to User Experience. I appreciate you thought about it and planning to add this for cal.com

**Comment by PeerRich** [comment]
hey @nathansudo lemme make a Workspace App for the App Store

**Comment by nathansudo** [comment]
@PeerRich Sorry I missed these comments and then I can't seem to find the Workplace or Workrooms app? Did this go live?  I was originally thinking just a customize feature so you could use a platform that wasn't supported directly but maybe that's a separate feature request now but really interested in getting the Workrooms one working.   (Workplace and Workrooms are different even though Workrooms does use some of the Workplace backend, it doesn't function the same on the API I think)
