### ISSUE TITLE
[CAL-4117] fix desktop nav

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#16088]
<img width="211" alt="CleanShot 2024-08-06 at 13 34 00@2x" src="https://github.com/user-attachments/assets/7c5efc5d-5c1f-4f6b-8e6a-020df3f30e5d">

<sub>[CAL-4117](https://linear.app/calcom/issue/CAL-4117/fix-desktop-nav)</sub>

**Comment by readul-islam** [comment]
Could you please provide more details regarding this issue?

**Comment by PeerRich** [comment]
not needed, i am working on it
