### ISSUE TITLE
(bug) Build fails with type error for new code pushed works with code from 2 days ago. 

### ISSUE THREAD

**Issue by KamaniBhavin** [calcom/cal.com#16093]
### Issue Summary

Executing `yarn build` on the main branch fails due to a lint error in the recent code changes.

### Steps to Reproduce

1. Execute `yarn build` on the main branch.

### Expected Behavior

The apps/web should build without any errors.

### Other Information

The code is fairly new. The build is successful with code from two days ago.

### Screenshots

Screenshot:
<img width="1090" alt="Screenshot 2024-08-06 at 7 47 20 PM" src="https://github.com/user-attachments/assets/2ca848c9-8669-43d0-9d19-48e0ea02a0b7">

Linting:
<img width="1090" alt="Screenshot 2024-08-06 at 7 47 55 PM" src="https://github.com/user-attachments/assets/c6712cf0-913e-4450-b1ab-0684d282fd82">

### Environment

- [ ] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Mac OS Sonoma 14.5
- Node: v18.18.2
- npm: 9.8.1
```

**Comment by PeerRich** [comment]
can you try again? cant reproduce this
