### ISSUE TITLE
Unexpected token error when serever responds with 524 status code(bug).

### ISSUE THREAD

**Issue by ymohit1603** [calcom/cal.com#16101]
### Issue Summary

On 524 status code from server some ugly error rendered inside alert .

### Steps to Reproduce

1.Go to signup
2. try signing with dummy email
3. check console

### Expected behavior

Informative error must be shown to user like server time out or some other informative content.

### Screenshots

![Screenshot_2024-08-07_01_13_31](https://github.com/user-attachments/assets/0e53018a-73c0-4738-a4b7-d543225d6a9c)

### Environment

- [X] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:Linux
- Node:20.12.2
- npm:10.8.0
```

**Comment by sanskar9415** [comment]
can i work on this issue.

**Comment by ymohit1603** [comment]
yeah sure why not

**Comment by sanskar9415** [comment]
i cant reproduce this error everything working fine , can u help me in reproducing it?

**Comment by ymohit1603** [comment]
Just try signing in with a false email like xyz@gmail.com something like that

**Comment by PeerRich** [comment]
cant reproduce this either. can you record a loom.com video and open a new issue if it still happens?
