### ISSUE TITLE
400: BAD_REQUEST

### ISSUE THREAD

**Issue by archkage** [calcom/cal.com#16127]
### Issue Summary

400: BAD_REQUEST
Code: BAD_REQUEST
ID: sfo1::qfxwx-1723058294828-b546071beae5

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

The site is not loading

### Environment

- [X] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by hunterwilhelm** [comment]
I'm experiencing this 400 error too!

**Comment by empowernation** [comment]
I'm experiencing this as well.  Ouch.

**Comment by archkage** [comment]
It got solved on my end!

**Comment by archkage** [comment]
Thank you!
