### ISSUE TITLE
(bug) Metadata is not getting passed all the way through the from the form URL (to the booking page) to the webhook handler.

### ISSUE THREAD

**Issue by pannpichet** [calcom/cal.com#16140]
### Issue Summary

When adding metadata query string parameter to the URL (either on the form or the booking page), the metadata is not passed through to the webhook. 

This feature last worked a few weeks ago. 

### Steps to Reproduce

1. Started on (example) cal.com/forms/0123456789?metadata[context]=0987654321
2. Passed through to booking form (example) cal.com/team/example-team/example-form?metadata[context]=0987654321
3. Made a booking
4. Resulting webhook does not contain metadata.

### Expected behavior

Metadata in URL should be passed through webhook. 

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Node: chrome
- npm: 127
```

**Comment by nishchal27** [comment]
@pannpichet can you please elaborate on the issue you're facing with screenshots and videos? I'm not able to reproduce this issue.

**Comment by pannpichet** [comment]
@nishchal27 Looks like its working fine right now. Will reach back out if it becomes a problem again.

**Comment by amalshaji-dev** [comment]
Same issue
