### ISSUE TITLE
username error on sign up using in use email

### ISSUE THREAD

**Issue by ymohit1603** [calcom/cal.com#16156]
### Issue Summary

wasted 1 hour changing username because alert says user exists with that username
![Screenshot_2024-08-09_23_53_16](https://github.com/user-attachments/assets/1dd0cb61-7090-4c21-b357-ba89b6ae5e62)

### Steps to Reproduce

1. (for example) Went to cal.com/signup
2. use in use email with unique username
3. ...

### Expected behavior

In alert the message text should be email already taken.

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:linux
- Node:20.12.2
- npm: 10.8.0
```

**Comment by zerone0x** [comment]
Can I work on this?

**Comment by gaurab-khanal** [comment]
@alishaz-polymath
Can you assign me this issue? I want to work on this.

**Comment by alishaz-polymath** [comment]
Hey fellas, feel free to have a crack at it and raise a PR. You don't need to be assigned the issue 🙌 
As long as it's either a bug or an approved feature request, you can always go for it. Appreciate the help! 🙏

**Comment by iharsh02** [comment]
![image](https://github.com/user-attachments/assets/2f0115a9-f6ac-43de-8fa1-0f3448f06f30)
Not able to Produce the same error in local host

**Comment by ymohit1603** [comment]
@iharsh02 yeah its working in self hosted as i have't checked the boxin environment section of this issue it is on app.cal.com .

**Comment by PKBOSS26** [comment]
![Screenshot 2024-08-15 141216](https://github.com/user-attachments/assets/045d74b9-4fdc-4d3b-8a21-64f7ca17ca6f)
its already fixed ig

**Comment by anikdhabal** [comment]
It was fixed
