### ISSUE TITLE
Rescheduling a meeting causes the server to throw a 500 error

### ISSUE THREAD

**Issue by amvara-adrian** [calcom/cal.com#1615]
### Issue Summary

Doing tests on the bookings, I have found that when rescheduling them we get a 500 error. The bookings can be deleted.
This error occurs since [January 25, 2022 at 1:30 AM](https://prod.cometa.rocks/#/Default/Stage/457/run/89149/step/107988). [Test 457](https://prod.cometa.rocks/#/Default/Stage/457) have been run on app.cal.com

See also: #1556 

### Steps to Reproduce
1. Goto bookings.
![Bookings](https://user-images.githubusercontent.com/98409469/151014297-e6580ec9-bd3f-4589-a03f-ee3792b36ef8.png)
2. Click on one of the meetings there to reschedule it.
3. Wait for the calendar to appear on the screen, but I get a 500 error.
![Error_500](https://user-images.githubusercontent.com/98409469/151014343-d939d8ac-1fec-477b-b21d-bd2c79af98a2.png)
4. Console Error
![Console](https://user-images.githubusercontent.com/98409469/151014545-19bb8137-a7f9-4afd-bb01-7e7c21728c95.png)

### Technical details

- Cometa.rocks for testing [[Test 457](https://prod.cometa.rocks/#/Default/Stage/457) - Chrome 95]
- Browser version: [Chrome 97 Windows 10](https://www.whatsmybrowser.org/b/BVZBE)
- Tested in app.cal.com

**Comment by milospuac** [comment]
Hey there! Thank you for submitting this. Our team is working on it.

**Comment by raro42** [comment]
3x to 5x/day we receive "Could not reschedule the meeting" as seen in screenshot.

![2022-02-22 09_31_31-304001581-reschedule_broken](https://user-images.githubusercontent.com/29251049/155093128-b376f6fa-6b78-4481-a63e-0fc9f95e614a.png)

May this be related?

**Comment by alannnc** [comment]
Our entire reschedule flow has been upgraded. I'm gonna close this issue as this error found is no longer relevant with our current base code.
