### ISSUE TITLE
[CAL-4133] Add location to workflow reminder template

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16168]
Add Location/Meeting URL to Workflow reminder template.

After 'Attendees,' we should add 'Location' to display the meeting URL, or, if it's not a video location, to show the location string instead.

Now:

![Screenshot 2024-08-12 at 8.05.36 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/32bff238-0452-4472-83c4-83a029cd0ad0/98c757e8-db0e-454a-9ace-b1efb2b6fba0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zMmJmZjIzOC0wNDUyLTQ0NzItODNjNC04M2EwMjljZDBhZDAvOThjNzU3ZTgtZGIwZS00NTRhLTlhY2UtYjFlZmIyYjZmYmEwIiwiaWF0IjoxNzIzNDQyODIwLCJleHAiOjE3NTQ5Nzg4MjB9.LmtzyjrelAyOrJR7wJDppYASt-nViiHHomJb1ZFC8vE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4133](https://linear.app/calcom/issue/CAL-4133/add-location-to-workflow-reminder-template)</sub>

**Comment by akarsh-jain-790** [comment]
@CarinaWolli  I would like to work on this issue. Can you assign this to me?

**Comment by CarinaWolli** [comment]
Hey @akarsh-jain-790, we don't assign to issues but feel free to work on it and link this issue in your PR :)

**Comment by akarsh-jain-790** [comment]
> Hey @akarsh-jain-790, we don't assign to issues but feel free to work on it and link this issue in your PR :)

Got it, thanks!

**Comment by Souptik2001** [comment]
@CarinaWolli @anikdhabal Fix for this 👆
