### ISSUE TITLE
Add attachment to booking (additional inputs)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1616]
### Describe the solution you'd like

it would be dope to offer an additional input field "attachment" which could be a pdf or similar.

use cases:
- upload a pitch deck (fundraising or capital marketplaces)
- upload a cv (hiring marketplaces)
- upload a medical recipe / medical record  (telehealth)

### Describe alternatives you've considered

Button: "attach file"
 
![image](https://user-images.githubusercontent.com/8019099/151032690-c320c7ff-16a6-4706-b54d-d18fff3a7554.png)

open questions:
- where should the data go? S3 bucket? filestack.com integration?

**Comment by acvalencia** [comment]
Hello @PeerRich. How attachments will be visible in bookings? 
Is an option needed to display the details or add a link to download the file?

![image](https://user-images.githubusercontent.com/97113254/153281417-02b87deb-3d04-4c20-a425-11bca5394d50.png)

**Comment by PeerRich** [comment]
not planned for now
