### ISSUE TITLE
[CAL-4137] Users with no name shown at the top of dropdown (routing forms)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16171]
In the routing form dropdown, team members without a name are shown at the top:

![Screenshot 2024-08-12 at 1.02.41 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ccfdad64-8a44-499d-b6a9-9e76b7162a42/a58bb7f0-5f21-4226-8131-ed55b7942522?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jY2ZkYWQ2NC04YTQ0LTQ5OWQtYjZhOS05ZTc2YjcxNjJhNDIvYTU4YmI3ZjAtNWYyMS00MjI2LTgxMzEtZWQ1NWI3OTQyNTIyIiwiaWF0IjoxNzIzNDYwNzIzLCJleHAiOjE3NTQ5OTY3MjN9.zJceLW9ci8ssV1liNCrE_nBDj0BjjqtExOC46VFKlwQ)

Let's do it like we have it is for assigning hosts on team event types and use the email if the name is not available: 

![Screenshot 2024-08-12 at 1.03.52 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c7bb8809-270a-49b6-a981-d49ddd268d25/5ab87bbe-d3c3-460c-a698-67217f11cf84?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jN2JiODgwOS0yNzBhLTQ5YjYtYTk4MS1kNDlkZGQyNjhkMjUvNWFiODdiYmUtZDNjMy00NjBjLWE2OTgtNjcyMTdmMTFjZjg0IiwiaWF0IjoxNzIzNDYwNzIzLCJleHAiOjE3NTQ5OTY3MjN9.VVnzJIJk0lNlaI-HBaJBSpVJnCYHK4nfxonzsox2usE)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4137](https://linear.app/calcom/issue/CAL-4137/users-with-no-name-shown-at-the-top-of-dropdown-routing-forms)</sub>

**Comment by dilmohankumar** [comment]
can i work on this

**Comment by anikdhabal** [comment]
> can i work on this

Go for it

**Comment by shreya0204** [comment]
@CarinaWolli @anikdhabal 👆
