### ISSUE TITLE
[CAL-3969] Close.com can't be installed

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#16183]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3969](https://linear.app/calcom/issue/CAL-3969/closecom-cant-be-installed)</sub>

**Comment by Flash-Shivam** [comment]
@milospuac is it the case that upon entering the API key and clicking save lead to a prompt saying : "Failed to construct 'URL' : Invalid URL" and then nothing happens

https://www.loom.com/share/59de99c53b7f404e8598474a10f7a5a5
