### ISSUE TITLE
[CAL-4144] Duplicating org team event types not working

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16199]
Clicking continue doesn't do anything. It doesn't show any error messages

![Screenshot 2024-08-14 at 3.56.22 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5c714dd9-6601-4954-a6c6-d6e189b2b8e6/c8b30fe7-5fb8-43c4-be0f-cdafb895c664?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81YzcxNGRkOS02NjAxLTQ5NTQtYTZjNi1kNmUxODliMmI4ZTYvYzhiMzBmZTctNWZiOC00M2M0LWJlMGYtY2RhZmI4OTVjNjY0IiwiaWF0IjoxNzIzNjQzODczLCJleHAiOjE3NTUxNzk4NzN9.bm0lBImfFmvARsBXMoNAhYJQnMsrFQvK_Jdm4uIuXHQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4144](https://linear.app/calcom/issue/CAL-4144/duplicating-org-team-event-types-not-working)</sub>

**Comment by SySagar** [comment]
Would like to pick this up.

**Comment by SySagar** [comment]
Also I have checked that it only happens in case of teams not individual meet.

**Comment by Flash-Shivam** [comment]
@SySagar @CarinaWolli I was able to figure out the bug, have opened a PR to resolve the issue.
