### ISSUE TITLE
Allow users to more clearly see when a day is fully booked

### ISSUE THREAD

**Issue by Kaeson** [calcom/cal.com#162]
### Is your proposal related to a problem?

Two things:

1) Many people don't work 7 days per week, so it would be nice to select which days you are working when setting up availability.
2) If your calendar is blocked, i.e fully booked on any given day, this should be clearly visible in the calendar so that people who would like to book you don't have to go through every single day to find a time slot.

### Describe the solution you'd like

1) I'd like to be able to choose which days I am available for accepting bookings, e.g Monday - Friday. The rest of the days should be greyed out in a similar fashion as previous days.
2) If you are fully booked on any given day (or you are on PTO etc), the color should change from blue to red. This will give an immediate overview of which dates the user can check for availability, and perhaps it would be possible to add a "take me to the first available slot"-button at some point :)

### Additional context

Here's an example

<img width="857" alt="Calendso" src="https://user-images.githubusercontent.com/5095216/117279519-1490e400-ae62-11eb-8386-130350ee8f40.png">

**Comment by baileypumfleet** [comment]
We need some sort of 'is array empty' check. Also if no slots are available, the right pane is blank. Needs an empty state

**Comment by jimafisk** [comment]
This visual queue would be very helpful! Currently if you only are offering availability one day a week, the user has to do a lot of guessing to figure out when they can book time with you. I'm not sure about the red color, I would probably just opt for the existing grayed out style used for other unavailable days. I personally just need users to know if they can book or not, but maybe other folks need a distinction between a fully booked day and an unavailable day.

**Comment by baileypumfleet** [comment]
I was going to implement this the other day, but the problem is we only make the API call to check the user's availability once you've selected a date. We need a way to determine which days are completely blocked out before you click a date

**Comment by jimafisk** [comment]
@baileypumfleet with the new availability controls that are being rolled out (https://github.com/calendso/calendso/issues/78#issuecomment-862189244), I assume you could run a check against those before calling out to find the integrated availability? That paired with basic "no availability" text instead of showing a blank availability panel after calling the API to check the user's availability would go a long way!

**Comment by emrysal** [comment]
@jimafisk

"Red" slots are yet to be implemented, but using availability you can now configure the gray slots as per your screenshot. There's performance implications to get the red slots implemented - from an invitee POV the system would become unresponsive if we checked all the calendar freebusy at once. 

However; there is a "{USER} is fully booked" text now when a day is selected that is "Available but busy". Have a look at whether you think invitee interaction has improved by any margins; I think it has.

**Comment by PeerRich** [comment]
@Kaeson, @jimafisk the cached calendar was added last week in version v.1.7
