### ISSUE TITLE
[CAL-4151] Private URLs aren't working for org links

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16228]
My private org event-type link redirects to my normal org links that shows my username. Same happens for me locally as well. 

How to reproduce: 

1. Create event type in an org account 
2. Enable Private URL
3. Copy the private URL into the browser and see that it redirects to the normal event-type link

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4151](https://linear.app/calcom/issue/CAL-4151/private-urls-arent-working-for-org-links)</sub>

**Comment by Flash-Shivam** [comment]
This is not happening for me , I created a team , created an event type for the team , enable private link and viewed the links of the eventType both normal and private don't show my userName. Am I doing something wrong ?

PRIVATE LINK 

<img width="1470" alt="Screenshot 2024-08-16 at 2 38 02 PM" src="https://github.com/user-attachments/assets/8d97076c-eea2-4e64-a351-f5f105d61d5b">

NORMAL LINK 


<img width="1470" alt="Screenshot 2024-08-16 at 2 37 43 PM" src="https://github.com/user-attachments/assets/f7125be9-3ae3-44ae-9de7-4aeabaaaedcf">

**Comment by CarinaWolli** [comment]
> This is not happening for me , I created a team , created an event type for the team , enable private link and viewed the links of the eventType both normal and private don't show my userName. Am I doing something wrong ?

and this was a team inside an organization?

**Comment by Flash-Shivam** [comment]
What do you mean by organization ? I just created a team by clicking on new button in the teams tab

**Comment by Amit91848** [comment]
@CarinaWolli Since we are replacing private links with single use links, it is being handled in that pr itself #15896

**Comment by CarinaWolli** [comment]
> @CarinaWolli Since we are replacing private links with single use links, it is being handled in that pr itself #15896

Sounds good, did we test that single use links also work for orgs?

**Comment by Amit91848** [comment]
> Sounds good, did we test that single use links also work for orgs?

Yes changes were made and it works now
