### ISSUE TITLE
(bug) Build error on v4.4.0

### ISSUE THREAD

**Issue by olivierlambert** [calcom/cal.com#16232]
### Issue Summary

When building:

```
@calcom/web:build: ../../packages/features/ee/organizations/pages/settings/attributes/attributes-edit-view.tsx:30:11
@calcom/web:build: Type error: Property 'id' does not exist on type '{ id: string; } | null'.
@calcom/web:build: 
@calcom/web:build:   28 |   const { t } = useLocale();
@calcom/web:build:   29 |   // Get the attribute id from the url
@calcom/web:build: > 30 |   const { id } = useParams<{ id: string }>();
@calcom/web:build:      |           ^
@calcom/web:build:   31 |   // ensure string with zod
@calcom/web:build:   32 |   const attribute = trpc.viewer.attributes.get.useQuery({ id: id as string });
@calcom/web:build:   33 | 
@calcom/web:build: ERROR: command finished with error: command (/data/cal/apps/web) yarn run build exited (1)
command (/data/cal/apps/web) yarn run build exited (1)
```

### Steps to Reproduce

1. Fetch v4.4.0
2. Build it
3. Error during yarn build

### Expected behavior

Build sucessful

### Other information

Previous version worked

### Environment

- [ ] app.cal.com
- [x] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Debian 12
- Node: v18.19.0
- npm: 10.2.03
```

**Comment by olivierlambert** [comment]
Same error with v4.4.1

**Comment by Upellift99** [comment]
Same error with v4.4.1

**Comment by olivierlambert** [comment]
To recap on building:
* `v4.3.6`: :white_check_mark: 
* `v4.4.0`: :x: 
* `v4.4.1`: :x:

**Comment by anikdhabal** [comment]
fixed by this https://github.com/calcom/cal.com/pull/16243

**Comment by olivierlambert** [comment]
Thanks @anikdhabal 

Is there a way to skip the type testing in a `yarn build` process? I mean, on my side it's not needed and this take a pretty big amount of resources.
