### ISSUE TITLE
(bug) Overflow issue on booking page

### ISSUE THREAD

**Issue by SySagar** [calcom/cal.com#16241]
### Issue Summary

It seems that for a longer  message the timezone modal overflow.

### Steps to Reproduce

1. Go to this booking page, for example: https://cal.com/sy-sagar/a-brand-new-event?month=2024-08&date=2024-08-19
2. Change the timezone

### Expected behavior

It should not overflow

### Screenshots

https://github.com/user-attachments/assets/dab5a6be-81b9-4064-8a23-c9a8b7405bf3

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: windows
- Node: 20
- npm:
```

**Comment by pratiksrivastava01** [comment]
Are you still working @SySagar ??

**Comment by SySagar** [comment]
@pratiksrivastava01 this issue has been solved. Only merging ir required.
