### ISSUE TITLE
components overlaping

### ISSUE THREAD

**Issue by ymohit1603** [calcom/cal.com#16252]
### Issue Summary

![Screenshot_2024-08-17_15-28-52](https://github.com/user-attachments/assets/b42792ee-6671-44a5-995e-52acfd57d6b2)

### Steps to Reproduce

went to https://cal.com/nicwortel/online-consult?date=2024-08-19&layout=month_view

### Expected behavior

those two components must be well seperated

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:linux
- Node:
- npm:
```

**Comment by anikdhabal** [comment]
Hey, can’t reproduce this on any screen type or device screen. It only happens on large screens when you inspect the screen and increase the inspector menu. This isn’t a major issue
