### ISSUE TITLE
[CAL-4161] Bulk update schedule for existing event types missing

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16266]
When changing the default schedule in the list of availabilities (https://app.cal.com/availability) a modal opens to bulk update schedule for existing event types: 

![Screenshot 2024-08-19 at 2.38.33 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a5df0b6e-5d8e-4bd5-ba31-8d92b7f71db3/4dc6082c-754f-43b5-9c75-674d7a93d834?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hNWRmMGI2ZS01ZDhlLTRiZDUtYmEzMS04ZDkyYjdmNzFkYjMvNGRjNjA4MmMtNzU0Zi00M2I1LTljNzUtNjc0ZDdhOTNkODM0IiwiaWF0IjoxNzI0MDcxMjk1LCJleHAiOjE3NTU2MDcyOTV9.hpeXF5-ywgfwq-Y-F_3VePUQDn8iHeukrf2Zg68GGEk)

![Screenshot 2024-08-19 at 2.38.06 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/97659b50-3d4b-49dd-85d1-97e121382364/25ae55cb-fc72-4800-99b5-79dd3a344866?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85NzY1OWI1MC0zZDRiLTQ5ZGQtODVkMS05N2UxMjEzODIzNjQvMjVhZTU1Y2ItZmM3Mi00ODAwLTk5YjUtNzlkZDNhMzQ0ODY2IiwiaWF0IjoxNzI0MDcxMjk1LCJleHAiOjE3NTU2MDcyOTV9.3Gai2LPeUHML2W9VWycWCZ2fBB4H3FeEciqklti1ivQ)

But when you set the default schedule in the availability settings (https://app.cal.com/availability/<id>) this modal doesn't appear: 

![Screenshot 2024-08-19 at 2.39.32 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5ebbaa79-71f4-478a-a098-e9daadb23933/1982b809-bcb1-4676-abef-e0bd1cfdb9cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81ZWJiYWE3OS03MWY0LTQ3OGEtYTA5OC1lOWRhYWRiMjM5MzMvMTk4MmI4MDktYmNiMS00Njc2LWFiZWYtZTBiZDFjZmRiOWNiIiwiaWF0IjoxNzI0MDcxMjk1LCJleHAiOjE3NTU2MDcyOTV9.c-x6ZGcDzRetvFIHm72Yz9sfrcnaW-yVJUeLWWiQIVw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4161](https://linear.app/calcom/issue/CAL-4161/bulk-update-schedule-for-existing-event-types-missing)</sub>

**Comment by hemantvardani** [comment]
Hi, @SySagar looks like you have already solved it , That's great.

@SySagar  @CarinaWolli Is this an issue, I believe this should be considered as a feature, and I feel this is correct behavior.
Can you comment your take on this.

Thanks
