### ISSUE TITLE
(bug) Flickering between Light and Dark UI modes on embed

### ISSUE THREAD

**Issue by michaelpanik** [calcom/cal.com#16268]
### Issue Summary

We were able to replicate the flickering issue outline in https://github.com/calcom/cal.com/issues/8860, where a Cal embed flickers between light and dark mode when another Cal tab is opened in the opposite mode.

### Steps to Reproduce

1. Visit Cal.com in dark mode
2. Open another tab with the cal embed in light mode

### Expected behavior

Stays only in the mode set in `Cal("ui")`

### Environment

- [X] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by sameersuman573** [comment]
sir could you please elaborate and give photos

**Comment by PeerRich** [comment]
i think this is fixed
