### ISSUE TITLE
cal.com in Chinese traditional shows `multiple_duration_timeUnit` multiple durations of the event as a string

### ISSUE THREAD

**Issue by fixiabis** [calcom/cal.com#16275]
### Issue Summary

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/df363362-f0ab-4730-8a0f-48a5023d3147">
Although I saw that issue #16184 was resolved, I found that it still displays multiple_duration_timeUnit during actual use.

### Steps to Reproduce

Visit https://cal.com/fixiabis/secret, then would see:
<img width="206" alt="image" src="https://github.com/user-attachments/assets/6385c5e5-c162-48c3-bfd7-7ae5fbd5dde2">

### Expected behavior

<img width="207" alt="image" src="https://github.com/user-attachments/assets/eae8f1e6-2a30-47e4-a2bf-08084261071e">

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Amit91848** [comment]
Hey @fixiabis , #16184 is merged and will go live in next release, it will be fixed then.
