### ISSUE TITLE
(bug) Edit booking API docs are incorrect

### ISSUE THREAD

**Issue by xta** [calcom/cal.com#16299]
### Issue Summary

In the docs, it refers to `start` and `end` as valid keys https://cal.com/docs/enterprise-features/api/api-reference/v1/bookings#edit-an-existing-booking

> This API call is used to edit a specific booking of the user, identified by the booking id. Currently, you can only change the title, start, end, status and description of the booking.

However, trying to use the API, I get the error `{ message: "Unrecognized key(s) in object: 'start', 'end'" }`

With postman, the correct keys are present https://www.postman.com/calcom/workspace/cal-com-workspace/request/20666831-b83fffb5-16a1-44cd-9873-af7ca8904022

`startTime` and `endTime` work with the API to update a booking

### Steps to Reproduce

Follow API docs, got error 

### Expected behavior

Use Postman JSON body and it works

### Environment

- [ ] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by milospuac** [comment]
@alishaz-polymath can we make the changes?

**Comment by alishaz-polymath** [comment]
Sorted 🙏
