### ISSUE TITLE
[CAL-4162] Username update modal overflow

### ISSUE THREAD

**Issue by Ryukemeister** [calcom/cal.com#16297]
### Issue Summary

https://www.loom.com/share/5112a72ae42d4aae9bf42bf2aa4d20c3?sid=09aa27f8-b4f9-46b7-92be-e3a87aff80fe

### Steps to Reproduce

1. go to https://app.cal.com/settings/my-account/profile and try to change your username to a character that's really long

**Comment by C-W-D-Harshit** [comment]
Hi @Ryukemeister I fixed the issue and linked my pr to this issue.
