### ISSUE TITLE
(bug) Build error on v4.4.3

### ISSUE THREAD

**Issue by olivierlambert** [calcom/cal.com#16323]
### Issue Summary

In a very similar fashion than https://github.com/calcom/cal.com/issues/16232 but this time with:

![buildfailure](https://github.com/user-attachments/assets/6356d23e-fb06-4e2a-98f3-c905a869c202)

### Steps to Reproduce

Exactly same as https://github.com/calcom/cal.com/issues/16232

### Expected behavior

Same as https://github.com/calcom/cal.com/issues/16232

### Environment

- [ ] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
Same as https://github.com/calcom/cal.com/issues/16232
```

**Comment by olivierlambert** [comment]
Also same question than in https://github.com/calcom/cal.com/issues/16232 : I don't think it's relevant for a production build to do those tests, can we skip them somehow when doing a `yarn build`?

**Comment by olivierlambert** [comment]
Note: build works in `v4.4.2`, so it's a regression specific to `v4.4.3`.

**Comment by nebulade** [comment]
Came here to report the same when updating the Cloudron package (4.4.2 works):
```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Failed to compile.

../../packages/features/shell/Shell.tsx:218:36
Type error: 'pathname' is possibly 'null'.

  216 |   const banners = useBanners();
  217 |   const pathname = usePathname();
> 218 |   const isFullPageWithoutSidebar = pathname.startsWith("/apps/routing-forms/reporting/");
      |                                    ^
  219 |   const { data: user } = trpc.viewer.me.useQuery();
  220 |   const { boot } = useIntercom();
  221 |   const pageTitle = typeof props.heading === "string" && !props.title ? props.heading : props.title;
The command '/bin/bash -c yarn --cwd apps/web workspace @calcom/web run build' returned a non-zero code: 1
```

**Comment by httpways** [comment]
Hello,

I have the same error.

![Screenshot_20240824_184526](https://github.com/user-attachments/assets/df33f073-b9c0-4b96-a4cc-0db1bc847366)

I have not found any fix yet ...

**Comment by olivierlambert** [comment]
Great news! My question stands however: can we avoid doing type check in the build phase? If yes, how?
