### ISSUE TITLE
Allow _ in identifier for Booking Fields

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#16332]
Allow _ in identifier for Booking Fields e.g. utm_medium is a param passed automatically to pages. User would want the identifier to be same so that it can be auto-filled(especially after https://github.com/calcom/cal.com/pull/16330 is merged)

![image](https://github.com/user-attachments/assets/84033e9a-caa0-4f1a-961c-52de1cbd73d5)

Note that, we are restricting the special characters in there because those identifier become React Hook Form field names which have limiations for characters. So, we are being conservative, supporting only those characters that have a requirement.

Campsite Private Thread : https://app.campsite.co/cal/inbox/updates/71a8980dd7d9

**Comment by ArnavNath550** [comment]
Hey There!
I am looking into this one ✨

**Comment by ArnavNath550** [comment]
Hey there, 
This is actually my first time contributing to open source.. 
I am just having trouble finding this Identifier TextField in the codebase.. @hariombalhara would you happen to know where it could be?
