### ISSUE TITLE
[CAL-4175] Changing the location for a booking to 'Organizer's default App' makes it literally just the text

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#16366]
It doesn't actually generate the link as per the Organizer's default App.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4175](https://linear.app/calcom/issue/CAL-4175/changing-the-location-for-a-booking-to-organizers-default-app-makes-it)</sub>

**Comment by Vivek7038** [comment]
@hariombalhara can you help me out with where are the files of docs
