### ISSUE TITLE
[CAL-4173] Error when event type url already exists for user (managed event type)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16363]
When a new user is assigned to a managed event type but the user already has an event type with the same slug then it throws 'An unexpected Error occurred. Try again.' . Instead it should show the `ManagedEventDialog` 

Steps to reproduce: 
1. As a team admin create a new managed event type
2. Create a personal user event for the team admin with the same slug as the managed event type
3. In the assignment tab, assign a team admin to the managed event type
4. This should open the `ManagedEventDialog` but instead it throws an error

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4173](https://linear.app/calcom/issue/CAL-4173/error-when-event-type-url-already-exists-for-user-managed-event-type)</sub>

**Comment by SySagar** [comment]
Would look into this.

**Comment by Mihir867** [comment]
Hey, Can you tell me how can I replicate this ? It would be helpful in solving the same
