### ISSUE TITLE
Improve web experience

### ISSUE THREAD

**Issue by Neivoto** [calcom/cal.com#16377]
When you go to docs and click on the drop down list, we're unable to minimize the drop down list. We can only minimize the dropdown list if we try to go back to the previous page.

I think it's better if we are able to maximize and minimize the dropdown lists by clicking on it itself 
instead of having to click to go back to the previous page

To recreate it:
Step one: Go to Cal.com homepage
Step 2: Click on Docs
Step 3: Click on the dropdown items available on the left

![Screenshot 2024-08-27 182231](https://github.com/user-attachments/assets/1ecd8cf0-4f86-43b9-a6d7-e5b18743e25f)

**Comment by SujeetPawar** [comment]
can you assign it to me ?

**Comment by Vivek7038** [comment]
@Neivoto I am working on these one

**Comment by Vivek7038** [comment]
@PeerRich  can you approve these issue first , so that i can start working

**Comment by sreyas-b-anand** [comment]
@PeerRich  Hi! I'd like to work on this issue. Could you please provide approval or any additional guidelines?

**Comment by Himanshu-Kathania** [comment]
Hey, can you assign it to me?
