### ISSUE TITLE
(bug)

### ISSUE THREAD

**Issue by jasiukiewicztymon** [calcom/cal.com#16386]
### Issue Summary

While using the API i got somethimes the error "{"message":"no_available_users_found_error"}" after creating a booking with not real data in responses. But this but doesn't happen each time, it is being returned only sometimes.

### Steps to Reproduce

1. I send the request
2. `requests.post(
            "https://api.cal.com/v1/bookings?apiKey=cal_live_...",
            headers = {
                "content-type": "application/json"
            },
            json = {
                "eventTypeId": type,
                "start": f"{date}T{heure}:00.000Z",
                "responses": {
                    "name": f"{name}",
                    "email": f"{mail}",
                    "location": {
                        "value": "inPerson",
                        "optionValue": ""
                    }
                },
                "timeZone": "Europe/Berlin",
                "language": "en",
                "title": "Reservation made with the bot",
                "status": "PENDING",
            }
        )`
3. The response is sometimes ok sometimes not

### Expected behavior

I wish it make the book without error

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Python: 3.10
```

**Comment by CarinaWolli** [comment]
It throws `no_available_users_found_error` when the host isn't available at that time. Did you check that the host was available at the time you tried to book?

**Comment by jasiukiewicztymon** [comment]
```
1. getType [{'name': 'coupe enfant', 'id': 1016060}, {'name': 'TEST coupe-homme', 'id': 889245}, {'name': 'TEST barbe-homme', 'id': 890374}, {'name': 'TEST coupe-et-barbe-homme', 'id': 1005005}, {'name': 'coupe femme', 'id': 1010185}]
2. Hoolland 2024-09-05 13:00 889245
3. b'{"message":"no_available_users_found_error"}' 2024-09-05 13:00 889245 Hoolland
4. ['09:00', '09:40', '10:20', '11:00', '11:40', '12:20', '13:00', '13:40', '14:20', '15:40', '16:20'] 2024-09-05 889245
```

1. I list the events types
2. I list the datas (name, date, time, type event id)
3. error
4. slots for the day and type event id

So no, the slot is ok the problem is somewhere else and does not occure each time.

I had not this problem even once using my cal.com account datas (name and email).

**Comment by jasiukiewicztymon** [comment]
Here again:

```
getType [{'name': 'coupe enfant', 'id': 1016060}, {'name': 'TEST coupe-homme', 'id': 889245}, {'name': 'TEST barbe-homme', 'id': 890374}, {'name': 'TEST coupe-et-barbe-homme', 'id': 1005005}, {'name': 'coupe femme', 'id': 1010185}]
Louane 2024-09-12 09:00 1016060
{'eventTypeId': 1016060, 'start': '2024-09-12T09:00:00.000Z', 'responses': {'name': 'Tymon Jasiukiewicz', 'email': 'titicode2115@gmail.com', 'location': {'value': 'inPerson', 'optionValue': ''}}, 'metadata': {}, 'timeZone': 'Europe/Berlin', 'language': 'en', 'title': 'Reservation made with the bot', 'status': 'PENDING'}
b'{"message":"no_available_users_found_error"}' 2024-09-12 09:00 1016060 Louane
b'{"message":"no_available_users_found_error"}'
```

![image](https://github.com/user-attachments/assets/5cc512a4-8966-4a69-904a-6a7b172b8ee0)

The slug is accessible while it is showing in the cal.com interface but impossible to book it with the API.

**Comment by CarinaWolli** [comment]
> `'start': '2024-09-12T09:00:00.000Z`

This is utc, so that would be 11:00 in Berlin and you don't have an available slot at that time.

`'start': '2024-09-12T09:00:00.000+02:00` should work, let me know if that solves it for you 🙏

**Comment by CarinaWolli** [comment]
Feel free to reopen with more information if you are still experiencing this issue 🙏

**Comment by jasiukiewicztymon** [comment]
> Feel free to reopen with more information if you are still experiencing this issue 🙏

It was still buggy so I recreated a new account and since then this bug has not appeared.
