### ISSUE TITLE
(bug) Verify pin ui is broken on inline embed

### ISSUE THREAD

**Issue by laneme** [calcom/cal.com#16385]
### Issue Summary

The pin input fields overflows and becomes almost invisible sometime. 

![image](https://github.com/user-attachments/assets/799e4148-67f1-40fe-8f7d-5639eac8da40)

If **you have hide branding turned on, the inputs almost completely disappears.**

![image](https://github.com/user-attachments/assets/11cb46c0-deb3-4497-8d56-ced7f2bfa590)

I can consistently reproduce this in chrome. 
https://codesandbox.io/p/sandbox/embed-advanced-css-vars-forked-kzf5jj?file=%2Fsrc%2FApp.tsx

```tsx
import "./styles.css";
import { useEffect } from "react";

import Cal, { getCalApi } from "@calcom/embed-react";

export default function App() {
  useEffect(() => {
    getCalApi().then((cal) => {
      cal("ui", {
        theme: "light",
      });
    });
  }, []);

  return (
    <div className="App">
      <h1>Following is an inline cal.com React embed</h1>
      <Cal calLink="laneme/30min" />
    </div>
  );
}
```

### Steps to Reproduce

1. Open google **chrome on desktop (> 800px)** (the issue appears on chrome only)
2. Visit https://kzf5jj.csb.app/ (above codesandbox)
3. **Book a date with a long enough email**. Try `tester-longer@example.org`
4. You'll be prompted to verify email with a pin with the overflown inputs

### Why might be happening

**The longer email breaks into a new line, i assume this is why.**
When `hide branding` is turned on, I think the dialog tries to adjust to the height, thus completely hiding the inputs.

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windows 11, Linux
- Node: 18
- @cal/embed: `1.3.0`, `1.5.0`
```

**Comment by darshil89** [comment]
Hello , can you assign this to me ?

**Comment by darshil89** [comment]
This is actually not an issue as the height is also reduced which is relative to the width of pin boxes, when the height is set to default or viewed on mobile devices , it will look like this.

![Screenshot 2024-08-30 222817](https://github.com/user-attachments/assets/9138cbed-05c3-4095-8e39-3b23f4011fdf)

**Comment by laneme** [comment]
> This is actually not an issue as the height is also reduced which is relative to the width of pin boxes, when the height is set to default or viewed on mobile devices , it will look like this.

I did not test on mobiles or or in any vertical view.

As for default height, you mean when i dont specify height?
Well i tried both omitting and 100% height. 100% height is used in the snippet you can copy from your events in dashboard.

**Comment by laneme** [comment]
Anyone got to take a look?

Its makes the `require verify email` option unusable.

Matter of fact we found out about this issue because a customer reached out to us that he cant verify his email and cant book appointment.

**Comment by Amit91848** [comment]
Hey @laneme thanks for reporting the issue! Can you tell me the dimensions for your screen when you are facing the issue? I tried  your codesandbox link on chrome with different screen sizes but can't seem to replicate it

![Screenshot 2024-09-05 231333](https://github.com/user-attachments/assets/82448f9e-831a-4dfb-ba04-fd7fbcbb833d)

**Comment by laneme** [comment]
@Amit91848 Screens over`800px`.  But..

Sorry for the late reply, my reproduction suddenly became inconsistent. But maybe i figured it out why

The bug only shows up if you use a longer email. Try `tester-longer@example.org`.

Heres a video, notice its only broken for the longer email.

https://github.com/user-attachments/assets/bf5c11f0-d264-4f6f-8b40-40e8234bde50

_Updated my reproduction steps._

**Comment by JOSU9435** [comment]
Hey! Can I try working on this issue?
