### ISSUE TITLE
[CAL-4191] Wrong text for team admin that is not part of booking

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16392]
A team admin or owner can view all the teams' bookings, even when they are not part of the bookings.  When visiting the details of the booking (/booking/uid) as an admin it says 'You are meeting with Attendee Name' instead of 'Host Name is meeting with Attendee Name'

User is not part of this booking and it looks like that:

![Screenshot 2024-08-29 at 9.09.49 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8b46ec2a-d930-49ed-aeca-3ed9ab0c2aff/751410d9-5ed5-461e-8709-57e163a1aafe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84YjQ2ZWMyYS1kOTMwLTQ5ZWQtYWVjYS0zZWQ5YWIwYzJhZmYvNzUxNDEwZDktNWVkNS00NjFlLTg3MDktNTdlMTYzYTFhYWZlIiwiaWF0IjoxNzI0OTM3MTY5LCJleHAiOjE3NTY0NzMxNjl9.68b-4rLOX3ekWixqI5cXQLCxuVQu9vKuhXf_O7cxaBw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4191](https://linear.app/calcom/issue/CAL-4191/wrong-text-for-team-admin-that-is-not-part-of-booking)</sub>

**Comment by munnaverma-inventyv** [comment]
I want to this
can you please assign it to me

**Comment by pritam1322** [comment]
@CarinaWolli there can be many attendees, so adding all of them in title will not look good. Can you please suggest on this ?

**Comment by CarinaWolli** [comment]
> @CarinaWolli there can be many attendees, so adding all of them in title will not look good. Can you please suggest on this ?

I think it's fine to take on the first attendee. If I'm not mistaken, for team events, the first attendee should be the real attendee and the other hosts follow afterward.

**Comment by pritam1322** [comment]
@anikdhabal Can you let me know the reason why you closed my PR? although it had covered all the scenarios.
As it was my first open source commit, it would help me understand better as the PR you created is quite similar with little modification.
