### ISSUE TITLE
(bug) Cal is not defined. This shouldn't happen

### ISSUE THREAD

**Issue by toaomnk** [calcom/cal.com#16421]
### Issue Summary

React Component Fails to Render. I've created a React app, and am trying to embed Cal into a Drupal Module - Along with some services so that I can fill these in automatically in the booking form. 

Here is Services.js, the main file in the React App.

`import Cal from '@calcom/embed-react';
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';

console.log('Script loaded'); // This should be logged when the script is run

// Utility function to adjust the price
const adjustPrice = (price) => Math.ceil((price * 1.5) / 5) * 5;

// Utility function to normalize URLs
const normalizeUrl = (url) => url.replace(/\/+$/, '').toLowerCase();

export const loadCalScript = () => {
  return new Promise((resolve, reject) => {
    console.log('Attempting to load Cal script');
    if (window.Cal) {
      console.log('Cal script already loaded');
      resolve(true);
      return;
    }

    const script = document.createElement('script');
    script.src = "https://detailandsupply.com/sites/default/files/js/embedCal.js";
    script.async = true;

    script.onload = () => {
      console.log('Cal embed script loaded.');
      const checkCal = setInterval(() => {
        console.log('Checking if Cal object is available...');
        if (window.Cal) {
          console.log('Cal object is now available.');
          clearInterval(checkCal);
          resolve(true);
        }
      }, 100); // Check every 100ms

      setTimeout(() => {
        if (!window.Cal) {
          clearInterval(checkCal);
          console.error('Cal object did not load within the expected time.');
          resolve(false);
        }
      }, 7000); // Timeout after 7 seconds
    };

    script.onerror = () => {
      console.error('Failed to load Cal embed script.');
      reject(new Error('Failed to load Cal embed script.'));
    };

    document.head.appendChild(script);

    console.log('Appending Cal embed script to document head');
  });
};

// The main ServicesComponent that handles the rendering of services based on the current URL
export const ServicesComponent = ({ currentUrl }) => {
  const [isCalScriptLoaded, setIsCalScriptLoaded] = useState(false);
  const normalizedCurrentUrl = normalizeUrl(currentUrl);

  console.log('Normalized Current URL:', normalizedCurrentUrl);

  // Find the service based on the current URL
  const service = window.services?.find(service => normalizeUrl(service.url) === normalizedCurrentUrl);

  useEffect(() => {
    console.log('Running useEffect in ServicesComponent');

    if (!service) {
      console.error('Service not found for this URL.');
      return;
    }

    loadCalScript()
      .then((calLoaded) => {
        setIsCalScriptLoaded(calLoaded);
        console.log('Cal script successfully loaded:', calLoaded);

        if (window.Cal) {
          console.log('Cal object available:', !!window.Cal);

          window.Cal("init", { origin: "https://appointments.detailandsupply.com" });
          Object.entries(service.pricingMatrix).forEach(([key, pricing], index) => {
            const selector = `#cal-inline-${index}`;
            console.log('Selector for Cal:', selector);
            window.Cal("inline", {
              elementOrSelector: selector,
              calLink: pricing.fullButton.props.calLink,
              layout: 'month',
            });
          });
        } else {
          console.error('Cal object is not available.');
        }
      })
      .catch((error) => {
        console.error('Error loading Cal script:', error);
      });
  }, [service]);

  return (
    <div id="services-root">
      {service ? (
        Object.entries(service.pricingMatrix).map(([key, pricing], index) => (
          <div key={index} id={`cal-inline-${index}`} />
        ))
      ) : (
        <p>No service found for this URL.</p>
      )}
    </div>
  );
};

// The main Services component that initializes the rendering
const Services = () => {
  useEffect(() => {
    console.log('Running useEffect in Services');
    const rootElement = document.getElementById('services-root');
    const currentUrl = window?.drupalSettings?.customServices?.currentUrl || '';

    if (!rootElement) {
      console.error('Root element not found.');
      return;
    }

    console.log('Root element exists:', !!rootElement);

    loadCalScript()
      .then((calLoaded) => {
        console.log('Cal script successfully loaded:', calLoaded);
        if (rootElement && !rootElement.hasChildNodes() && calLoaded) {
          const root = createRoot(rootElement);
          root.render(<ServicesComponent currentUrl={currentUrl} />);
        } else {
          console.error('ServicesComponent does not appear to be rendered.');
        }
      })
      .catch((error) => {
        console.error('Error loading Cal script:', error);
      });
  }, []);

  return null;
};

window.ServicesComponent = ServicesComponent;
window.loadCalScript = loadCalScript;

export const services = [
  {
    pricingMatrix: {
      Coupe: {
        basePrice: 0.00,
        options:  [
          { basicExteriorDetail: { label: "Standard Exterior Detail - A 3 bucket hand wash, air dry, tires cleaned and shined, glass cleaned", price: adjustPrice(30) } },
          { clayBarTreatment: { label: "Clay Bar Treatment", price: adjustPrice(15) } },
          { bugTarRemoval: { label: "Bug & Tar Removal", price: adjustPrice(10) } },
          { paintDecon: { label: "Iron Removal Treatment", price: adjustPrice(25) } },
          { waxOrSealant: { label: "Brilliant Carnauba Wax", price: adjustPrice(30) } },
          { basicInteriorDetail: { label: "Standard Interior Detail", price: adjustPrice(30) } },
          { clothLeatherTreatment: { label: "Cloth & Leather Treatment", price: adjustPrice(40) } },
          { steamTreatment: { label: "Steam Treatment", price: adjustPrice(35) } },
          { lightStainRemoval: { label: "Light Stain Removal", price: adjustPrice(30) } },
          { odorRemoval: { label: "Odor Removal", price: adjustPrice(20) } }
        ],
        fullButton: (
          <Cal 
            calLink="team/detail-kings/auto-detailing-coupe"
            style={{width:"100%",height:"100%",overflow:"scroll"}}
            config={{layout: 'month_view'}}
            calOrigin="https://appointments.detailandsupply.com"
            embedJsUrl="https://detailandsupply.com/sites/default/files/js/embedCal.js"
          />
        ),
      },
    url: "/en/automotive-services/auto-detailing", 
];

window.services = services;

export default {
    ServicesComponent,
    services,
};
`

Here is CustomServicesBlock.php `<?php

namespace Drupal\custom_services\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a 'Custom Services' Block.
 *
 * @Block(
 *   id = "custom_services_block",
 *   admin_label = @Translation("Custom Services Block"),
 * )
 */
class CustomServicesBlock extends BlockBase implements ContainerFactoryPluginInterface {

  /**
   * Constructs a new CustomServicesBlock.
   *
   * @param array $configuration
   *   A configuration array containing information about the plugin instance.
   * @param string $plugin_id
   *   The plugin_id for the plugin instance.
   * @param mixed $plugin_definition
   *   The plugin implementation definition.
   */
  public function __construct(array $configuration, $plugin_id, $plugin_definition) {
    parent::__construct($configuration, $plugin_id, $plugin_definition);
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition
    );
  }

  /**
   * {@inheritdoc}
   */
  public function build() {
    $current_url = \Drupal::request()->getRequestUri();

    return [
        '#markup' => '<div id="services-root"></div>',
        '#attached' => [
            'library' => [
                'custom_services/react_services',
            ],
            'drupalSettings' => [
                'customServices' => [
                    'currentUrl' => $current_url,
                ],
            ],
        ],
    ];
  }
}`

and last but not least the libraries file for the Drupal module. 

`react_services:
  version: 1.x
  js:
    https://www.detailandsupply.com/react-app/custom-services-react/assets/js/326.bundle.js: {}
    https://detailandsupply.com/sites/default/files/js/embedCal.js: {}
    https://www.detailandsupply.com/react-app/custom-services-react/assets/js/main.bundle.js: {}
  dependencies:
    - core/jquery
    - core/drupal
`

I get the issue Uncaught Error: Cal is not defined. This shouldn't happen
    <anonymous> https://detailandsupply.com/sites/default/files/js/embedCal.js:88
    <anonymous> https://detailandsupply.com/sites/default/files/js/embedCal.js:88
[embedCal.js:88:190](https://detailandsupply.com/sites/default/files/js/embedCal.js)
    <anonymous> https://detailandsupply.com/sites/default/files/js/embedCal.js:88
    <anonymous> https://detailandsupply.com/sites/default/files/js/embedCal.js:88

and when I run 

`(function() {
  // 1. Check if the script is loading correctly
  console.log("Script is running");

  // 2. Verify that the root element exists
  let rootElement = document.getElementById('services-root');
  console.log('Root element exists:', !!rootElement);

  // 3. Check the content of the root element
  console.log('Root element content:', rootElement ? rootElement.innerHTML : 'Root element not found');

  // 4. Verify that the current URL is being captured correctly
  let currentUrl = window?.drupalSettings?.customServices?.currentUrl || '';
  console.log('Current URL:', currentUrl);

  // 5. Check if the normalized current URL matches any service URL
  let normalizedCurrentUrl = currentUrl.replace(/\/+$/, '').toLowerCase();
  console.log('Normalized Current URL:', normalizedCurrentUrl);

  // 6. Check if the service is found for the current URL
  let service = services.find(service => service.url === normalizedCurrentUrl);
  console.log('Service found:', !!service);
  if (service) {
    console.log('Service details:', service);
  }

  // 7. Verify if the Cal embed script is loading and initialized correctly
  let scriptLoaded = !!document.querySelector('script[src="https://detailandsupply.com/sites/default/files/js/embedCal.js"]');
  console.log('Cal embed script loaded:', scriptLoaded);

  if (scriptLoaded) {
    console.log('Cal object available:', !!window.Cal);
  }

  // 8. Check if the React component should have rendered (i.e., if the root element has children)
  if (rootElement && rootElement.hasChildNodes()) {
    console.log('ServicesComponent appears to be rendered.');
  } else {
    console.error('ServicesComponent does not appear to be rendered.');
  }
})();
`

I get [Log] Cal embed script loaded: – true
[Log] Cal object available: – false
[Error] ServicesComponent does not appear to be rendered.
	Console Evaluation (Console Evaluation 4:41)
	Console Evaluation (Console Evaluation 4:43)
< undefined

### Steps to Reproduce

Steps to Reproduce

    Create a React Application:
        Create a React application using create-react-app or any other method of choice.
        Add the provided Services.js file to your React project.

    Install Cal Embed Library:
        Install @calcom/embed-react via npm in your React application.
        Make sure the Cal component is imported and used as shown in the Services.js file.

    Create Drupal Module:
        Create a Drupal 10 custom module that will embed the React app.
        Add the provided CustomServicesBlock.php as a block in the module.
        Ensure the block is enabled and placed on a page in the Drupal site.

    Configure Drupal Libraries:
        Create the custom_services.libraries.yml file in your Drupal module with the provided configuration.
        Make sure the JavaScript files are correctly loaded from the specified URLs.

    Embed React App into Drupal:
        In the CustomServicesBlock.php, return a div with the id="services-root" where the React app will be rendered.
        Attach the library custom_services/react_services to load the necessary scripts.

    Test the Drupal Page:
        Visit the page where the custom block is placed.
        Open the browser's developer console and observe the logs and potential errors.

### Expected behavior

Expected Behavior

    The React component (ServicesComponent) should render inside the div#services-root element on the Drupal page.
    The Cal embed script should successfully load, and the Cal object should be available for initializing and embedding the Cal booking interface.
    The correct service should be identified based on the current URL, and the corresponding pricing matrix should be displayed within the rendered React component.
    No errors should appear in the console, and the page should function as intended.

Actual Behavior

    The console shows the following errors:
        Uncaught Error: Cal is not defined: This indicates that the Cal object is not being defined or loaded correctly from the embedCal.js script.
        ServicesComponent does not appear to be rendered.: This suggests that the React component is failing to render, likely due to the Cal object not being available as expected.
    The Cal embed script is reported as loaded (Cal embed script loaded: true), but the Cal object is not available (Cal object available: false), leading to the failure of the ServicesComponent to render correctly.

### Environment

- [ ] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Ubuntu 22.04
- Node: v27.7.0
- npm: 10.8.2
```

**Comment by Praashh** [comment]
working now
