### ISSUE TITLE
[CAL-4339] Recurring meetings set to "yearly" don't display "Every year for..." text on the booking page.

### ISSUE THREAD

**Issue by michaelcrusso** [calcom/cal.com#16432]
### Issue Summary

Simply put, when recurring meetings are set to weekly/yearly, they display "Every ____ for..." text on the booking page, like so:

![image](https://github.com/user-attachments/assets/5f1ac045-d101-4c47-98d6-03691ae014e8)

However, when they're set to yearly, the field seems to just be blank.

![image](https://github.com/user-attachments/assets/30d75d7c-8eb3-43b5-bbf5-5254762b4d32)

For that matter, after the input box it says "occurrences", whereas in a video demonstrating this feature that's swapped out with the pertinent value "Every **week** for [5] **weeks**", for example, which seems much clearer to whoever is booking an appointment.

### Steps to Reproduce

Set recurring meetings to yearly

### Expected behavior

It should display "Every year for..." before the number input box.

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windows 10 22H2
- Browser: Firefox 
- Version: 129.0.2
```

<sub>[CAL-4339](https://linear.app/calcom/issue/CAL-4339/recurring-meetings-set-to-yearly-dont-display-every-year-for-text-on)</sub>

**Comment by darshil89** [comment]
The only change to make was from `if (recurringEvent.interval && recurringEvent.freq) **`to`** if (recurringEvent.interval && recurringEvent.freq >= 0)`
