### ISSUE TITLE
(bug) Calendar Availability Not Displaying - TRPCClientError - viewer.public.slots.getSchedule in NextJS

### ISSUE THREAD

**Issue by joshuabuildsthings** [calcom/cal.com#16446]
### Issue Summary

My cal.com calendar is not loading my availability. I get a blank calendar screen with no listed availability; the UI feels like it's stuck on loading.

### Steps to Reproduce

1. Went to https://cal.com/
2. Waited for Calendar to load. When it took too long I opened it in another browser and got the same result.
3. Clicked the Dev Console in both browsers and saw an error.

### Expected behavior

I expect to be able to view my available booking slots.

### Other information

` << query #2 viewer.public.slots.getSchedule  
Object { input: {…}, result: TRPCClientError, elapsedMs: 35275, context: {…} }
​
context: Object { skipBatch: true }
​
elapsedMs: 35275
​
input: Object { isTeamEvent: false, eventTypeSlug: "initial-consulting-meeting", startTime: "2024-11-01T04:00:00.000Z", … }
​
result: TRPCClientError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
​​
cause: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
​​
columnNumber: 60650
​​
data: undefined
​​
fileName: "https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js"
​​
lineNumber: 1
​​
message: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
​​
meta: Object { response: Response }
​​
name: "TRPCClientError"
​​
shape: undefined
​​
stack: "TRPCClientError_TRPCClientError@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:60650\nfrom@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:60478\n22855/httpRequest/i</<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:66676\npromise callback*22855/httpRequest/i<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:66627\nhttpRequest@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:66499\njsonHttpRequester@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:65660\n22855/httpLinkFactory/</</</<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:69361\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:58911\n22855/createChain/<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:60028\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:58911\n22855/splitLink/</</<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:5:1342\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:58911\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:5:947\n22855/loggerLink/</</<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:5:1075\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:58911\n22855/createChain/<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:60028\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:58911\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:61165\n22855/requestAsPromise/r<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:61654\n@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:61514\nrequestAsPromise@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:61787\nquery@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:61972\nqueryFn@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:5:8161\nfetchFn@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:33694\nrun@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:49374\ncreateRetryer@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:49787\nfetch@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:34253\n#U@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:44148\nonSubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:42310\nsubscribe@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:50179\n82008/useBaseQuery/<@https://cal.com/_next/static/chunks/pages/_app-ce214c8994319102.js:1:55934\nki@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:133646\nRj@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:154184\nIk@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:183402\nz@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:177866\nJ@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:200736\nR@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:201278\nEventHandlerNonNull*9670@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:201456\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n22941@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:203238\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n52967@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:69766\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n28316@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:199330\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n17029@https://cal.com/_next/static/chunks/framework-47237789be70052d.js:1:199016\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n66059@https://cal.com/_next/static/chunks/main-cc69a710c932c339.js:1:9134\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n45286@https://cal.com/_next/static/chunks/main-cc69a710c932c339.js:1:18691\n__webpack_require__@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:526\n@https://cal.com/_next/static/chunks/main-cc69a710c932c339.js:6:17821\n__webpack_require__.O@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:1042\n@https://cal.com/_next/static/chunks/main-cc69a710c932c339.js:6:17843\ni@https://cal.com/_next/static/chunks/webpack-63c83201bcb23cb7.js:1:13681\n@https://cal.com/_next/static/chunks/main-cc69a710c932c339.js:1:387\n"`

### Screenshots

![image](https://github.com/user-attachments/assets/41816d5d-155d-48d1-a0aa-d530782d3b90)
![image](https://github.com/user-attachments/assets/3b83fe80-9bbd-4474-b513-ca2e7129318b)

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome & Firefox
```

**Comment by CarinaWolli** [comment]
Slots are loading find for me. @joshuabuildsthings Is this issue fixed for you? And did you change anything in your settings?

**Comment by joshuabuildsthings** [comment]
> Slots are loading find for me. @joshuabuildsthings Is this issue fixed for you? And did you change anything in your settings?

@CarinaWolli - Thank you for following up. I put in a support request via chat on cal.com and it was resolved. I forgot to come back & close this.
