### ISSUE TITLE
[CAL-4295] Global booking limits for teams

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#16557]
Similar to [https://github.com/calcom/cal.com/issues/8985](https://github.com/calcom/cal.com/issues/8985) but for teams. 

Booking limit of 2 per week means: Only allowing members to be booked two times a week (no matter what event type)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4295](https://linear.app/calcom/issue/CAL-4295/global-booking-limits-for-teams)</sub>

**Comment by kk7188048** [comment]
So the approach for this is to update the booking database and set a counter to 0 and  If the count exceeds 2, reject the booking.
Is this approach correct or is something related to in memory cache?
@CarinaWolli

**Comment by CarinaWolli** [comment]
I am already working on this one, PR will come soon
