### ISSUE TITLE
Location Change PR(#16379) Followup

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#16565]
1. https://github.com/calcom/cal.com/pull/16379/files/ae934daaeb4a89f65b380462c2c071351db3ab32#r1750442104
2. https://github.com/calcom/cal.com/pull/16379/files/ae934daaeb4a89f65b380462c2c071351db3ab32#r1750451755

PR: #16379

cc @joeauyeung

**Comment by Praashh** [comment]
fixed by PR: https://github.com/calcom/cal.com/pull/16379
