### ISSUE TITLE
Reset Password Screen style does not match other authentication screens

### ISSUE THREAD

**Issue by Fynn** [calcom/cal.com#1659]
### Issue Summary

The password reset screen **style** does not match other authentication screens

___
##### ⛔️Screenshot with not matching style:
![FORGOT-PASSWORD-FORM-BAD](https://user-images.githubusercontent.com/47244955/151725434-8e336f51-3140-4e59-a6c7-54c6f63cb32b.jpg)
##### ✅️Should match this style:
![LOGIN-FORM-GOOD](https://user-images.githubusercontent.com/47244955/151725503-35d160ed-ec65-4097-82a4-774086da4d39.jpg)

___
##### ⛔️Screenshot with not matching style:
![FORGOT-PASSWORD-MESSAGE-BAD](https://user-images.githubusercontent.com/47244955/151725576-6fc23072-39d1-497a-bcbc-de4018d361ca.jpg)
##### ✅️Should match this style:
![FORGOT-PASSWORD-MESSAGE-GOOD](https://user-images.githubusercontent.com/47244955/151725579-78d2b234-5c2a-4695-9f16-a738456d8213.jpg)
___

### Steps to Reproduce
1. Go to forgot password screen
2. Enter email address
3. Send email
4. Click on link in email

Something similar was done in #1627

**Comment by milospuac** [comment]
Hi there! Thanks for reaching out. Our team will have a look into this.

**Comment by acvalencia** [comment]
Hello @Fynn, I could take a look

**Comment by gracebir** [comment]
I am going to work on

**Comment by LuisChiej** [comment]
Hello @milospuac, shouldn't this issue be closed? as the [PR](https://github.com/calcom/cal.com/pull/1699) linked to it is closed
