### ISSUE TITLE
Daily digest request 

### ISSUE THREAD

**Issue by PidgePenPen** [calcom/cal.com#1660]
I am requesting a daily digest feature. I would love to have an email be able to be sent each day at a time I specify that Alerts me to the next days meetings that has been scheduled. Thank you!

**Comment by milospuac** [comment]
Hi there! That is actually a great idea. I will put this on our list of requested features and our team will have a look into it down the line. 

Thanks for reaching out.

**Comment by PidgePenPen** [comment]
Thank you! And if it's helpful, the other scheduling app I use through my website provider (Squarespace) has this feature. I believe the integration is with the shceudling app called Acuity (spelling). This feature on Cal.com would be so helpful. thanks again!

**Comment by agustif** [comment]
I think an integration with novu via app could make this feature more doable, I could try a stab at it if its found an acceptable compromise https://novu.co/

**Comment by PeerRich** [comment]
we have a monthly digest now. i think daily is too much
