### ISSUE TITLE
Access blocked: This app’s request is invalid

### ISSUE THREAD

**Issue by Shiva1325** [calcom/cal.com#16637]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

When clicked on this link (https://cal.com/rick/get-rick-rolled) displayed in home page before sign-in and toggled "Overlay my Calendar" leading to prompt for login. When clicked on login got this error: Access blocked: This app’s request is invalid

### Steps to Reproduce

1. (for example) Logout (if already logged-in)
2. Go to home page.
3. Scroll down till the section Schedule meetings without the email tennis(Which is in black box).
4. Now when you scroll till "Share you Link" is highlighted where you can see a button popup displaying "CAL.COM/RICK".
5. Click on this button which redirects you to different page.
6. On top right you can see toggle button which says "Overlay My Calendar". Toggle it.
7. Now a prompt appears click on the button "continue with cal.com".
8. When clicked login screen pops-up. Login using "Sign in with Google".
9. Now you can see the error (Instead of login). 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Not exactly sure but when logged in from home page login button the link or the request google recieves is from https://app.cal.com/auth/login. But when logged in using the above mentioned steps, the request is sent from the link https://cal.com/login?date=2024-09-14&month=2024-09&callbackUrl=%2Frick%2Fget-rick-rolled&overlayCalendar=true
and this domain might not be registered on the accessible domain list hence recieving this error or as the error says register the redirect URI in the Google Cloud Console. Doing this might resolve the issue. 

### Actual Results

- What's happening right now that is different from what is expected
It's throwing error. It should be redirected to web page.

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
I've tested this on my macbook air on chrome browser and got this error.
![Image 9-13-24 at 17 21](https://github.com/user-attachments/assets/d62b0673-b830-448c-b908-9c3253270061)
![Image 9-13-24 at 17 21 (1)](https://github.com/user-attachments/assets/83874857-25ee-4bc4-b341-0802ea96034d)

**Comment by CarinaWolli** [comment]
I can't reproduce this, I am getting redirected to `app.cal.com/auth/login`. But when I change the URL myself to `cal.com/auth/login` it happens for me as well

**Comment by Shiva1325** [comment]
@CarinaWolli ,
I think it’s fixed. Now I was able to login without any errors.
