### ISSUE TITLE
improve lighthouse score (google page speed) of mobile pages

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1664]
https://pagespeed.web.dev/report?url=https%3A%2F%2Fcal.com%2Fpeer

[cal.com/peer](https://cal.com/peer) has a great lighthouse score of 98 on desktop

![image](https://user-images.githubusercontent.com/8019099/151792925-524ce717-29d5-4a22-b938-bfc86f0b90fb.png)

but not on mobile:
![image](https://user-images.githubusercontent.com/8019099/151792950-3a677d01-07d5-48a0-93ec-7cbf8b6fad69.png)

**Comment by PeerRich** [comment]
https://cal.com/peer/15min looks a bit worse on mobile: 
![Uploading image.png…]()

**Comment by edgarlr** [comment]
@PeerRich, I notice the site is already using next.js 12, maybe to improve performance overall could help to move at least all marketing pages to getStaticProps and use [Next.js Middleware] to keep all the server-side functionality. Maybe will take more effort but it may be worth it, 🤔

**Comment by PeerRich** [comment]
> @PeerRich, I notice the site is already using next.js 12, maybe to improve performance overall could help to move at least more crucial pages to getStaticProps and use [Next.js Middleware] to keep all the server-side functionality. Maybe will take more effort but it may be worth it 🤔 maybe that along with ISR could help!

what do you mean by marketing pages? This repository doesn't include the marketing content, it's in a separate repository

**Comment by edgarlr** [comment]
yes, I just updated the comment! I meant maybe for crucial pages first (like /[user] or /index)
