### ISSUE TITLE
UI Bug: Feedback Button Overlapping App Bar Menu on Mobile Screens

### ISSUE THREAD

**Issue by omer-os** [calcom/cal.com#16643]
Found a bug? Please fill out the sections below. 👍

Issue Summary
When viewing the app on mobile screens, specifically in smaller resolutions, the feedback button overlaps the app bar menu.

Steps to Reproduce
Open the app on a mobile device or simulate a mobile screen resolution using Chrome Developer Tools
Navigate to the main interface of the app.

Technical details
Browser: Chrome
Screen resolution: 414 x 896 (iPhone X/11/12 Pro)
Node.js version: N/A
No specific console logs or network requests were noted, but the issue is easily replicable by adjusting the screen size to mobile dimensions.

Evidence
![image](https://github.com/user-attachments/assets/4269e045-01c6-4193-9939-0ffc1863a929)
![image](https://github.com/user-attachments/assets/fbf11432-2b83-4577-a81c-1f939ff71477)

**Comment by itsjatinnagar** [comment]
I would like to work on this issue. Please assign it to me.
Thanks

**Comment by sumukhj1219** [comment]
hey can you tell me exactly where this button file is located

**Comment by sumukhj1219** [comment]
its already been removed

**Comment by Sunilverma99** [comment]
its already been removed
