### ISSUE TITLE
UI accessibility bug

### ISSUE THREAD

**Issue by Dillonpw** [calcom/cal.com#16647]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Explore all apps link on the landing page has almost no contrast on mobile Safari and Chrome. Firefox not tested.

### Steps to Reproduce

1. Visit cal.com landing page and scroll to section about app connections on mobile device or responsive view in the dev tools
2.  explore all apps button has off-white background and almost the same shade text

### Actual Results

On viewports smaller than 768px wide the link loses all contrast, posing an accessibility issue

### Expected Results

Contrast should persist at all widths

### Technical details

N/A

### Evidence

Viewing the landing page on different devices and at different viewports exposed the contrast issue. on screens smaller than 768px wide the contrast issue is visible.

**Comment by VriaA** [comment]
Can I be assigned to this issue so I can work on it?

**Comment by rozam007** [comment]
Please assign me this issue

**Comment by Nikhildas10** [comment]
@Dillonpw could you be more specific, the social logos like discord and github being faded on mobile devices are the problem?

**Comment by Dillonpw** [comment]
@Nikhildas10 Of course. This is the section of the landing page while viewing on desktop.
![02074372-1C5F-4A7F-98CD-CCCBF86901B9_1_201_a](https://github.com/user-attachments/assets/88cfb9b4-bf4a-4d6f-84fe-0915d34d4825)

And this is the same section when viewing from mobile.
![BEFF8F06-406A-4B6F-A856-0F306DD7AD18_1_201_a](https://github.com/user-attachments/assets/d11c589c-0f7f-4bad-a3ea-b3330ff16c28)
any width under 768px the button loses its background-text contrast.

**Comment by Akshat-Jaiswal-8** [comment]
Hey @Dillonpw, could you tell me where I can find the code for the landing page? I've been trying for a long time but haven't had any luck. I also found something related to it here:
https://github.com/calcom/cal.com/discussions/16116

Please correct me if I'm wrong.

**Comment by askadityapandey** [comment]
> Hey @Dillonpw, could you tell me where I can find the code for the landing page? I've been trying for a long time but haven't had any luck. I also found something related to it here: #16116
> 
> Please correct me if I'm wrong.

Hey Akshat, Cal.com's main application, including most of its frontend, is indeed open source. However, the landing page (marketing site) is actually closed source.

**Comment by Akshat-Jaiswal-8** [comment]
@askadityapandey So that means, for now we can't contribute to it, right?

**Comment by askadityapandey** [comment]
> @askadityapandey So that means, for now we can't contribute to it, right?

Yes, checkout other issues if you want to contribute.

**Comment by Akshat-Jaiswal-8** [comment]
okay, thanks for the help @askadityapandey!

**Comment by CarinaWolli** [comment]
@nizzyabi could you take a look at that?

**Comment by nizzyabi** [comment]
on it!

**Comment by nizzyabi** [comment]
could you merge pr?

**Comment by CarinaWolli** [comment]
> could you merge pr?

merged 👍
