### ISSUE TITLE
UI Bug: Adding events to - label in the setting/calendar page is overflowing in mobile view

### ISSUE THREAD

**Issue by itsarunkumar** [calcom/cal.com#16652]
### Issue Summary
 when viewing the app in mobile device or smaller resolution , Adding events to : label in the setting/calendar path is overflowing.

### Steps to Reproduce

Open the app on a mobile device or simulate a mobile screen resolution using Chrome Developer Tools
Navigate to the settings tab and open calendar option

### Technical details

- Node.js version : NA
- Browser : Chrome 

### Evidence

![Screenshot 2024-09-15 222900](https://github.com/user-attachments/assets/d6943913-9c96-4777-a470-467f05a3ec32)

**Comment by ad956** [comment]
I'm interested in working on this issue.
