### ISSUE TITLE
don't load intercom on public booking pages (cal.com/peer)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1666]
to decrease js load, don't load intercom for public pages

**Comment by edgarlr** [comment]
Hey @PeerRich, maybe also looking into something like [Party town](https://github.com/BuilderIO/partytown) could help not only for intercom but for all third-party services 🤔  Should also help to improve page's performance

**Comment by PeerRich** [comment]
> Hey @PeerRich, maybe also looking into something like [Party town](https://github.com/BuilderIO/partytown) could help not only for intercom but for all third-party services 🤔 Should also help to improve page's performance

ohh interesting. are there any drawbacks? does Safari support web workers? do they offer polyfills if the browser doesn't offer web workers? https://caniuse.com/webworkers

**Comment by PeerRich** [comment]
have you worked with it before @edgarlr would you be down to make an MVP PR?

**Comment by edgarlr** [comment]
I've used it for a client's site a few months ago,  I'm not sure if they offer polyfills but I believe the strategy they use is to still load the scripts "normally" (like if it was a normal script) if the browser does not support web workers https://github.com/BuilderIO/partytown/wiki/Browser-Support). and sure, I can work on an MVP PR, and maybe that way would be easier to discuss it!

**Comment by PeerRich** [comment]
awesome thank you man!
