### ISSUE TITLE
[CAL-4354] The event summary in Hebrew (the email you send after scheduling an event) is aligned left to right instead of right to left.

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#16682]
The event summary in Hebrew (the email you send after scheduling an event) is aligned left to right instead of right to left.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4354](https://linear.app/calcom/issue/CAL-4354/the-event-summary-in-hebrew-the-email-you-send-after-scheduling-an)</sub>

**Comment by CarinaWolli** [comment]
duplicate of https://github.com/calcom/cal.com/issues/16681
