### ISSUE TITLE
TypeError: e.attendees[0] is undefined when trying to view /bookings/cancelled

### ISSUE THREAD

**Issue by jdaviescoates** [calcom/cal.com#16717]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Go to /bookings/cancelled
2. Get an error:

`TypeError: e.attendees[0] is undefined`

![Screenshot from 2024-09-19 09-48-19](https://github.com/user-attachments/assets/66b0c699-a314-4353-871a-6d81fb8a9554)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

The page loads for a split second and then errors.

### Expected Results

The page loads without errors

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by AnishKhadtare** [comment]
I tried to reproduce the bug but was not able to see the any bugs.
![image](https://github.com/user-attachments/assets/3b3534a1-bcf0-4e0c-93cb-de3c5737ce85)

**Comment by jdaviescoates** [comment]
@AnishKhadtare I'd guess that's very likely because you don't actually have any cancelled bookings so there isn't anything there to error out

**Comment by jdaviescoates** [comment]
This seems to be causing the issue:

![image](https://github.com/user-attachments/assets/5e017f2a-3038-492c-befd-e2270fb96fee)

https://paste.uniteddiversity.coop/?3dc9f913238d4528#87bJXyZP2RhnyScQ1M7SbtSCqSfSXRPxpCHc7i5RCG2p

In this file
https://app.cal.com/_next/static/chunks/framework-47237789be70052d.js

**Comment by Udit-takkar** [comment]
@jdaviescoates already fixed https://github.com/calcom/cal.com/pull/16716. should be live soon
