### ISSUE TITLE
`@calcom/sdk` Doesn't export TS types

### ISSUE THREAD

**Issue by nandorojo** [calcom/cal.com#16748]
### Issue Summary

`@calcom/sdk` on NPM ships no types with it. This is likely a problem with the build step, or the `files` getting put in `dist.

### Steps to Reproduce

`yarn add @calcom/sdk`

<img width="296" alt="Screenshot 2024-09-20 at 2 32 35 PM" src="https://github.com/user-attachments/assets/61ecaac6-e352-436e-a915-b78eb651d29e">

### Actual Results

No types shipped with the library. I think `package.json` needs to specify the `files`.

### Expected Results

Declaration files should be included.
### Evidence

Install the package.

**Comment by naaa760** [comment]
Hello @nandorojo : )

fix: #16741 

`
the @calcom/sdk package not including TypeScript declaration files, you need to ensure that the build process generates these files and that they are referenced in the package.json. First, check the build configuration to confirm that declaration files (*.d.ts) are being generated in the dist directory. Then, update the package.json to include the "types" field pointing to the main declaration file and use the "files" field to specify the output files in the dist directory. After making these changes, rebuild the package and publish it again.
`

**Comment by naaa760** [comment]
> Are you sure the issue you linked is related?

Yess!

**Comment by nandorojo** [comment]
I don’t see related files getting edited there. Has a fix been released?
