### ISSUE TITLE
[CAL-4387] Meeting URL variable does not work when we change location.

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#16769]
{MEETING_URL} variable does not work when we change the location for the event type. it sends out the previous conferencing link before the location is changed.

Workflow when the meeting is booked with the first link:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/57ffcc7e-321a-45ef-b5e1-07d0a35e527e/9b9c4627-0b8c-414f-9742-b238a905a2bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81N2ZmY2M3ZS0zMjFhLTQ1ZWYtYjVlMS0wN2QwYTM1ZTUyN2UvOWI5YzQ2MjctMGI4Yy00MTRmLTk3NDItYjIzOGE5MDVhMmJkIiwiaWF0IjoxNzI3MTAyMzk1LCJleHAiOjE3NTg2MzgzOTV9.orIXdZSZ7gLo1FZeRcmpPrQlGUEqFh9bBqUrEIbwX6Y)

Confirmation for location change:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fc2223d7-3bbf-45a6-aef6-cc953dfa9655/8935a827-1264-4ecb-a23e-4a373c00bcd4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9mYzIyMjNkNy0zYmJmLTQ1YTYtYWVmNi1jYzk1M2RmYTk2NTUvODkzNWE4MjctMTI2NC00ZWNiLWEyM2UtNGEzNzNjMDBiY2Q0IiwiaWF0IjoxNzI3MTAyMzk1LCJleHAiOjE3NTg2MzgzOTV9.NmJTFxp9qjQvwmcZ8XTEFEllIg0ult8vw3N8Czpjw-Y)

workflow 1H before the event starts (should have the new link with with the new location)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7872269b-2fe8-41f1-aca5-14920b9fa5ef/c24ba8b8-f644-475a-b99b-925f2bd87035?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83ODcyMjY5Yi0yZmU4LTQxZjEtYWNhNS0xNDkyMGI5ZmE1ZWYvYzI0YmE4YjgtZjY0NC00NzVhLWI5OWItOTI1ZjJiZDg3MDM1IiwiaWF0IjoxNzI3MTAyMzk1LCJleHAiOjE3NTg2MzgzOTV9.WzLOF-AKXmghufAq63lsaeB09e7tF-G3rwZOaowAddI)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4387](https://linear.app/calcom/issue/CAL-4387/meeting-url-variable-does-not-work-when-we-change-location)</sub>

**Comment by Aditya-A-G** [comment]
Hey, I would like to work on this issue.
