### ISSUE TITLE
[CAL-4420] remove -z-10 from booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#16838]
the `<a href>` is not clickable cause of z-index

either we make it clickable or remove -z-10

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ce36c666-3ba7-49f3-9244-951021c20c59/336aaf2a-6fe7-4041-9f09-109848d2b2e3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jZTM2YzY2Ni0zYmE3LTQ5ZjMtOTI0NC05NTEwMjFjMjBjNTkvMzM2YWFmMmEtNmZlNy00MDQxLTlmMDktMTA5ODQ4ZDJiMmUzIiwiaWF0IjoxNzI3Mzc0MjI3LCJleHAiOjE3NTg5MTAyMjd9.EstlimwDEMSX4KYLmrM5t6qMvA4Fv975kx206MeScdo)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4420](https://linear.app/calcom/issue/CAL-4420/remove-z-10-from-booking-page)</sub>

**Comment by mortale2004** [comment]
I am working on this
