### ISSUE TITLE
Tooltip must be used within TooltipProvider

### ISSUE THREAD

**Issue by mohamedosama113** [calcom/cal.com#16833]
I have this problem when I deployed cal using docker 
![image](https://github.com/user-attachments/assets/9efdb44a-1353-4091-94b9-9687c7a4b305)

**Comment by C-W-D-Harshit** [comment]
@mohamedosama113 can you share the screen recording so that we can clearly see, what is happening here. And I am not able to reproduce this error!

**Comment by canameti** [comment]
can confirm, freshly installed and happening on startup. docker install and without. both same issue

**Comment by drdrog** [comment]
Me too!
Had to build the image myself as there are no aarch64 images available and followed the instroctions on
[https://github.com/calcom/docker?tab=readme-ov-file#advanced-users-build-and-run-calcom](https://github.com/calcom/docker?tab=readme-ov-file#advanced-users-build-and-run-calcom)
Containers are running on a raspberry pi 4 (8GB) w/ debian 12

Web UI is displaying this error for - maybe - half a second
![grafik](https://github.com/user-attachments/assets/52bc605c-29be-4077-b501-5d455a0c3d80)
which then turns into a blank page.

No further errors in the calcom container logs

**Comment by controlaltnerd** [comment]
Can confirm the same issue here, fresh install and this occurs on first start of Docker container.

**Comment by Aldian1** [comment]
@canameti how do you change the Docker Image Version?

**Comment by FrancoAlbarra** [comment]
@canameti Im having the same issue on render deploying, is there any fix yet?

**Comment by canameti** [comment]
Adding the version tag at the end of the image variable in the docker-compose.yaml.
For example "image: canameti/project:v1.2"
V1.2 ist the version tag

**Comment by FrancoAlbarra** [comment]
> v
Im having the same issue on render deploying, is there any fix yet?

**Comment by FrancoAlbarra** [comment]
@mohamedosama113 Im having the same issue on render deploying, is there any fix yet?

**Comment by drdrog** [comment]
> did a little bit of research. Docker Image Version v4.5.1 seems to be the latest working image. Not a fix but a workaround for those who need the service as fast as possible back.

Can confirm that v4.5.1 is working when using the provided images (on arch amd64).
No luck with building my own image on aarch64 (Raspberry Pi) - possibly due to wrong building procedure :-(

Thanks for your help so far!

**Comment by Hybes** [comment]
Also got this issue today: Error: `Tooltip` must be used within `TooltipProvider`
