### ISSUE TITLE
Customizable e-mail with confirmation

### ISSUE THREAD

**Issue by marekeiba** [calcom/cal.com#1686]
### Is your proposal related to a problem?

I'd like to make confirmation emails more personal + add extra information like troubleshooting most common problems when a client can't connect to a call etc.

### Describe the solution you'd like

- Editable Textarea with confirmation email body text
- Added to Advanced settings section in Event Type detail (https://app.cal.com/event-types/XXX)
- Just basic text for the start, formatting can be dealt with later
- Button to save changes

### Describe alternatives you've considered

Sending an extra email after confirmation manually.

### Additional context

No.

**Comment by milospuac** [comment]
Thanks for the suggestion. Our team will have a look at this.

**Comment by PeerRich** [comment]
we're wroking on a proper email editor but it 'll take some time until that's live

**Comment by Dsujan** [comment]
Hi @PeerRich , I can see it has been a while - is this feature available in the paid teams version?

**Comment by Daltonstudio** [comment]
Yes, this is actually the one thing that prevents me from using cal.com. The wording is just not right, at least in my language.

I don't mind the branding, but being able to change the text is a requirement.

I tried setting up a workflow instead, but then it's just plaintext. I tried pasting a proper formatted html, but that wasn't possible.
I really hope this is coming soon so I can finally start using cal.com

**Comment by santivdt** [comment]
Would be amazing!

**Comment by norasutus** [comment]
I agree! It would be much more professional!

**Comment by bigbeka** [comment]
Hi @milospuac just checking if this feature has been implemented for hosted and paying users on cal.com? If not, is there a way to disable automatic email notifications? We could then implement custom notification workflows on our end.

**Comment by milospuac** [comment]
Once you enable workflows that send email upon booking to your attendees,
you can then disable our default confirmation email from the advanced
settings of that event type.

Let me know if you need any further help.

**Comment by bigbeka** [comment]
@milospuac Thanks for your reply.

How about the events that "Requires confirmation"?

How to disable "Your booking has been submitted" emails?

**Comment by bigbeka** [comment]
@milospuac Just checking in if we can disable all email notifications including `Your booking has been submitted` and `Confirmed/Rejected` emails?

**Comment by panomitrius** [comment]
Also wonder how to go about to edit the default confirmation email template! Can't find a way to do it.

**Comment by panomitrius** [comment]
> Let me know if you need any further help.

I also wonder how to go about to edit the default confirmation email template! Can't find a way to do it.

**Comment by panomitrius** [comment]
> Once you enable workflows that send email upon booking to your attendees,
> you can then disable our default confirmation email from the advanced
> settings of that event type.
> 
> Let me know if you need any further help.
> […](#)

I also wonder how to go about to edit the default confirmation email template! Can't find a way to do it.

**Comment by pyoneerC** [comment]
is this fixed? i would really like to customize this message

![Image](https://github.com/user-attachments/assets/88d3dee3-76b6-42eb-8e9f-eaa160223012)
