### ISSUE TITLE
Issue with DATABASE_DIRECT_URL not recognized in Prisma schema validation

### ISSUE THREAD

**Issue by ManavMalhotra** [calcom/cal.com#16875]
### **Title**: Issue with `DATABASE_DIRECT_URL` not recognized in Prisma schema validation

**Description**:  
I encountered a bug while running database migrations for the Cal.com project using Prisma. Even though the `.env` file is properly set at the root of the project, Prisma is throwing an error indicating that the `DATABASE_DIRECT_URL` environment variable is missing.

**Error Log**:  
```
Error: Prisma schema validation - (get-config wasm)  
Error code: P1012  
error: Environment variable not found: DATABASE_DIRECT_URL.  
  -->  schema.prisma:7  
   |  
 6 |   url       = env("DATABASE_URL")  
 7 |   directUrl = env("DATABASE_DIRECT_URL")  
   |  
Validation Error Count: 1
```

**Steps to Reproduce**:
1. Clone the Cal.com repository.
2. Set up the `.env` file at the root level with the required database URLs (`DATABASE_URL` and `DATABASE_DIRECT_URL`).
3. Run the following command:
   ```bash
   yarn workspace @calcom/prisma db-migrate
   ```
4. The error will occur during the schema validation step.

**Workaround**:  
I had to add the `DATABASE_DIRECT_URL` directly into the Prisma folder's `.env` file (relative to the Prisma directory) for the migration to work. This suggests that Prisma may not be correctly resolving the path to the root `.env` file.

**Expected Behavior**:  
Prisma should properly read the `DATABASE_DIRECT_URL` from the root `.env` file, as it does with `DATABASE_URL`.

**Environment**:
- Node.js version: `v20.15.1`
- Prisma version: `v5.4.2`

**Comment by CarinaWolli** [comment]
@jeevan4476 thank you for providing solution steps 🙏

**Comment by iqoOopi** [comment]
same issue, prsisma version 5.4.2, 
![image](https://github.com/user-attachments/assets/685376dc-0f11-4a61-8677-0eb3cb58a7f2)
Confirmed the db server is running. 

Have to create a new .env file under packages/prisma folder to make the "yarn workspace @calcom/prisma db-deploy" run. 

Agree with @ManavMalhotra there is a bug in calcom that prisma not using top level .env file.

**Comment by programmersEmperor** [comment]
@CarinaWolli 
I faced the same issue, when I was following the steps written in the readme file.

## I found out there are some missing points in the readme file :

- It mentions nothing about modifying the `.env` file inside `packags/prisma` 
- It mentions nothing about adding `DATABASE_DIRECT_URL` with `DATABASE_URL` in `packages/prisma/.env`  although it is required in order to run 
```bash
yarn workspace @calcom/prisma db-migrate
``` 

So I believed we need to update the readme file, don't you think so?
