### ISSUE TITLE
Add new user redirect looop

### ISSUE THREAD

**Issue by JackPala** [calcom/cal.com#16888]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When I visit the page to add new users, I click add user and the button does nothing. However it appends /add to my browser like so:

before:
```
/settings/admin/users
```

after clicking:
```
/settings/admin/users/add
```

then if I attempt to visit that page as a URL, it shows the user create page for a split second and then redirects back to the users page. Note this is not on the enterprise version, this is on the self hosted version.

### Steps to Reproduce

1. Visit admin / users
2. Click add user

### Actual Results

- nothing

### Expected Results

- a functional add user page

### Technical details

- Exists on chrome and brave and safari

### Evidence

Here is a video of what it does, the refresh is me hitting a redirect.

https://github.com/user-attachments/assets/d9377f25-e4a8-424a-b9da-fa2c6b8efc0c

**Comment by JackPala** [comment]
Am I to assume that multiple users are only allowed on the enterprise version? If I need 2 users I need to purchase 30 seats minimum? or is there something I am missing?

**Comment by naaa760** [comment]
Hello @JackPala :)

``
Please check the route configuration to make sure **`/settings/admin/users/add}** is appropriately set up and not returning back in order to resolve the "Add User" redirect issue. Make sure the user has the right permissions; the loop can be caused by an unauthorized change. Check the "Network" tab for 3xx faults or redirects, then use the browser's DevTools to look for any JavaScript errors. To rule out caching difficulties, consider using incognito mode or clearing the browser's cache. These actions ought to assist in fixing the issue.
``

**Comment by JackPala** [comment]
> Hello @JackPala :)
> 
> `` Please check the route configuration to make sure **`/settings/admin/users/add}** is appropriately set up and not returning back in order to resolve the "Add User" redirect issue. Make sure the user has the right permissions; the loop can be caused by an unauthorized change. Check the "Network" tab for 3xx faults or redirects, then use the browser's DevTools to look for any JavaScript errors. To rule out caching difficulties, consider using incognito mode or clearing the browser's cache. These actions ought to assist in fixing the issue. ``

Howdy @naaa760 ! I checked that and I have full admin perms, no redirect faults that I can see, and no errors on my reverse proxy side.

I spoke to @baileypumfleet via email and I was told in an email chain that I need to add users via the prism editor directly into the DB as adding users via a regular user interface is a feature that is reserved exclusively for enterprise license holders, not GPL self hosted users. A little dissapointing to hear, but as it is their code they can do with it what they wish.

As I have not found a better software that respects my freedom, I'll just add users via prism until the developers (hopefully) make the decision to include basic user additions for us "non" enterprise people.
