### ISSUE TITLE
[CAL-4434] feature request:  Add Eastern Time -US & Canada, Pacific Easter etc. in timezone picker

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#16880]
### Is your proposal related to a problem?

![Screenshot 2024-09-30 at 1 53 23 PM](https://github.com/user-attachments/assets/cce1eeaa-86e7-4868-875c-9cfbdc408fdb)

<sub>[CAL-4434](https://linear.app/calcom/issue/CAL-4434/feature-request-add-eastern-time-us-and-canada-pacific-easter-etc-in)</sub>

**Comment by AdityaGupta-cyber** [comment]
I am working on this.
