### ISSUE TITLE
Roadmap link `https://cal.com/roadmap` is broken

### ISSUE THREAD

**Issue by saurabh-619** [calcom/cal.com#1689]
### Issue Summary

The roadmap page on GitHub seems to be not available which is causing `https://cal.com/roadmap` to fail.
 

### Steps to Reproduce

1. Go to the home page - `http://localhost:3000/event-types`
2. Click on the Profile photo and then Roadmap Button
3. It takes us to the `https://github.com/orgs/calendso/projects/1/views/4` page, which is not available.

I don't if this is deliberate but I saw it on the `https://cal.com/web3`.

**Comment by PeerRich** [comment]
great catch! we recently renamed the repo and it looks like this was not renamed

**Comment by PeerRich** [comment]
fixed! deploying now
