### ISSUE TITLE
Individual Host Schedules for Round Robin Event types

### ISSUE THREAD

**Issue by Asher-Z-Engel** [calcom/cal.com#16897]
### Is your proposal related to a problem?

I need a way to have overlapping Round Robin Event Types, where hosts are only available at certain times for specific events but not others.

### Describe the solution you'd like

1. Overrides should be dynamic, so that a user can set themselves as available/unavailable at certain times for specific events, but not others. So for example, if Events A & B are running today, and they're both set to schedule based on the hosts' default schedule, but Host 1 is only available today for Event B, they would add an override to their default schedule that sets them as unavailable for Event A today, or else as only available for Event B.
2. To have shared schedules that can be customized for each user. So using the example from above, Event A would have a dedicated schedule called Schedule A, and then Host 1 could set themself as unavailable on Schedule A for today, while Event B has Schedule B, and Host 1 is available on Schedule B today. Then, at the same time, Host 2 could set themself as available today on Schedule A, while they are unavailable on Schedule B

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---

##### House rules

- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by vijayraghav-io** [comment]
should be solved by https://github.com/calcom/cal.com/pull/15618

**Comment by Asher-Z-Engel** [comment]
Yes it does look like that would be a good solution. Any idea when that will launch?
