### ISSUE TITLE
[CAL-4455] VERSION_2024_08_13 GET /bookings - Bad Request

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#16925]
Not sure how (if possible) to recover from this. I suspect the endpoint itself may be broken because without filters it should respond with all bookings. See screenshot on how to reproduce

<img width="854" alt="image" src="https://github.com/user-attachments/assets/1e84f709-169d-4511-9fa2-2d987182608c">

<sub>[CAL-4455](https://linear.app/calcom/issue/CAL-4455/version-2024-08-13-get-bookings-bad-request)</sub>

**Comment by ThoratSanchit** [comment]
can i solve

**Comment by ud4yy** [comment]
Can i work on this?

**Comment by Sankalpcreat** [comment]
There can be mainly some of issue like 

1.Verify API Documentation /v2/booking  check in there it could be possible that there are any specific query parameter or 
body parameter as its booking endpoint there could be filters or pagination issue during GET call'
2. Test minimal inputs  like ?limit=10 or any filter that api can expect
3. You have authorization and cal-api-version headers check that GET any other input is required or these are only 2
4. You can also check server side logs by checking endpoints if they are showing some error

Can i work on this feel free to i would love to work on this issue there are many edge cases that can be covered

**Comment by hunterwilhelm** [comment]
I am experiencing this issue too +1

**Comment by hunterwilhelm** [comment]
It works if attendeeEmail AND status filters set. But not each by themselves.

**Comment by fesoler** [comment]
Same here. I couldn't get it to work with those filters either.

**Comment by hunterwilhelm** [comment]
Had to switch back to calendly due to the broken API

**Comment by PeerRich** [comment]
hey @hunterwilhelm sorry you are experiencing this. i've prioritized this now as "high" and our team will look into this asap!

**Comment by emrysal** [comment]
Fixed in #17282
