### ISSUE TITLE
Meeting picker shows busy time slots but troubleshooter is correct

### ISSUE THREAD

**Issue by adriaanvanrossum** [calcom/cal.com#1693]
### Issue Summary

I use CalDAV with mailbox.org which shows me this event from 7:30 to 8:30 CET (6:30 to 7:30 GMT) ✅ 

<img width="477" alt="2022-02-03-03h03-screenshot@2x" src="https://user-images.githubusercontent.com/1079135/152269400-3dfedb0a-a3c7-4243-a31f-2e7d7a9b7245.png">

When selecting Europe/Amsterdam in the date scheduler, it shows the available timeslot for 8:00 CET. This should not be there as I already have an appointment from 7:30 to 8:30 CET. 🟥 

<img width="1067" alt="2022-02-03-03h03-screenshot 2@2x" src="https://user-images.githubusercontent.com/1079135/152269415-fdd7cb0b-1989-4d83-a215-218475629433.png">

When looking at the troubleshooter it shows an event from 6:30 to 7:30 GMT. Which is correct. ✅ 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/1079135/152269377-251ecccd-8304-4996-b616-ce8149a6120a.png">

### Steps to Reproduce

Settings for the meeting:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1079135/152270151-a031f934-09e5-4653-94c7-4fea43812e50.png">

These are the calendars connected:

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1079135/152269929-bb074b59-4a3e-4c35-97a9-65520e3fac79.png">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/VMP48
- Node.js version: v14.19.0

**Comment by adriaanvanrossum** [comment]
Today I found out it is behaving like expected when you set all time zones to UTC.

At `/settings/profile`:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1079135/152392839-60c27142-2a27-4b3f-b51e-46cc7c95776e.png">

At `/event-types/xxx`:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1079135/152392919-5e1ef768-7a0f-4664-b877-e69741ab53a2.png">

**Comment by Toledodev** [comment]
Hey @adriaanvanrossum, I was seeing this issue and when trying to reproduce it I saw that this problem is not happening :)
I follow every step in your readme
https://www.loom.com/share/88dc946237d64e198c92164318959b29

**Comment by adriaanvanrossum** [comment]
Maybe it's fixed? I don't use the open-source version anymore.

**Comment by Toledodev** [comment]
I guess so
