### ISSUE TITLE
[CAL-4491] [V2 Admin API] Add Missing Functionality to the Org Create Event Type Endpoint

### ISSUE THREAD

**Issue by SteveKekacs** [calcom/cal.com#16944]
### Is your proposal related to a problem?

The [v2 admin api org create event type endpoint](https://cal.com/docs/api-reference/v2/orgs-event-types/create-an-event-type) is missing a few pieces of functionality:
- For booking fields, the ability to set field to disable the input if the URL identifier is prefilled.
- Ability to configure a recurring event.
- Ability to configure seats for an event.
- Ability to override the default booking fields (to change the display name for the `name` and `email` fields).

### Describe the solution you'd like

- In the `bookingFields` array of objects, add a `disableIfPrefilled: boolean` or similar field.
- Add a new top level `recurringConfig?: { maxEvents: number, repeatConfig: { value: number, repeatInterval: "week" | "month" | "year"} }` (or similar) field.
- Add a new top level `seatsConfig?: { numSeats: number, shareAttendeeInfo: boolean, showNumberOfAvailableSeats: boolean }` (or similar) field.
- Allow overriding the default booking fields.

### Describe alternatives you've considered

Right now we're having to create events via the api, then go to the UI to configure these fields. We're creating many different event types for our use case, so this is a time consuming process.

### Additional context

N/A

### Requirement/Document

N/A

---

##### House rules

- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

<sub>[CAL-4491](https://linear.app/calcom/issue/CAL-4491/[v2-admin-api]-add-missing-functionality-to-the-org-create-event-type)</sub>

**Comment by alishaz-polymath** [comment]
cc: @keithwillcode @supalarry @ThyMinimalDev Can we line it up please?

**Comment by supalarry** [comment]
@SteveKekacs We have [this PR](https://github.com/calcom/cal.com/pull/17168/) in review that will allow:
1. Specifying `disableOnPrefill` property for each booking field.
2. Modify label, placeholder and `disableOnPrefill` for the default name and email fields.
I think if you click on Linear ticket linked to the task there is more context available if you are interested.

As for specifying event type recurrence and seats, it is already possible if you check [api docs for event types](https://cal.com/docs/api-reference/v2/orgs-event-types/create-an-event-type). Specifically `recurrence` and `seats` properties.

**Comment by SteveKekacs** [comment]
Great, thanks for the update @supalarry!

**Comment by supalarry** [comment]
@SteveKekacs sorry for late reply missed your issue above.

The reason for 400 is that for name and email booking fields you need to skip slug and simply denote their type. The slug for name and email are set automatically later on and is not accepted as input, because the slug is fixed. In your case  you need to submit:
```
{
    "bookingFields": [
    {
      "type": "email",
      "label": "Student Email",
      "required": true,
      "disableOnPrefill": true
    },
    {
      "type": "name",
      "label": "Student Name",
      "required": true,
      "disableOnPrefill": true
    },
    {
      "type": "multiemail",
      "slug": "guests",
      "label": "Guardian Emails",
      "required": false,
      "disableOnPrefill": true
    }
  ]
}
```

I confirm that with booking fields above it is a successful request.

**Comment by SteveKekacs** [comment]
Hi @supalarry, 

I'm still having issues with this. When I don't include the slug for name & email fields, I'm getting a 400 response on creating a new event:
```
Request:
{
  ...,
  "bookingFields": [
    {
      "type": "email",
      "label": "Student Email",
      "required": true,
      "disableOnPrefill": true
    },
    {
      "type": "text",
      "label": "Student Name",
      "required": true,
      "disableOnPrefill": true
    }
  ]
}


Response
{
  "status": "error",
  "timestamp": "2024-11-21T12:58:17.853Z",
  "path": "/v2/organizations/16327/teams/17510/event-types",
  "error": {
    "code": "BadRequestException",
    "message": "Each booking field must have a 'slug' property.",
    "details": {
      "message": "Each booking field must have a 'slug' property.",
      "error": "Bad Request",
      "statusCode": 400
    }
  }
}
```

**Comment by supalarry** [comment]
> Hi @supalarry,
> 
> I'm still having issues with this. When I don't include the slug for name & email fields, I'm getting a 400 response on creating a new event:
> 
> ```
> Request:
> {
>   ...,
>   "bookingFields": [
>     {
>       "type": "email",
>       "label": "Student Email",
>       "required": true,
>       "disableOnPrefill": true
>     },
>     {
>       "type": "text",
>       "label": "Student Name",
>       "required": true,
>       "disableOnPrefill": true
>     }
>   ]
> }
> 
> 
> Response
> {
>   "status": "error",
>   "timestamp": "2024-11-21T12:58:17.853Z",
>   "path": "/v2/organizations/16327/teams/17510/event-types",
>   "error": {
>     "code": "BadRequestException",
>     "message": "Each booking field must have a 'slug' property.",
>     "details": {
>       "message": "Each booking field must have a 'slug' property.",
>       "error": "Bad Request",
>       "statusCode": 400
>     }
>   }
> }
> ```

Booking fields of type `name` and `email` don't need a slug, but all other ones do. In the code above we have type `text` but it has a missing slug. If you try with the following it should work:
```
...
   {
      "type": "text",
      "slug": "student-name",
      "label": "Student Name",
      "required": true,
      "disableOnPrefill": true
    }
...
```

**Comment by supalarry** [comment]
> @supalarry ah I apologize 🤦‍♂️ missed that the name field type needs to be "name" not "text".

All good, glad to hear it's working! : )
