### ISSUE TITLE
[CAL-4741] [CAL-4467] add more columns to insights people table

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#16955]
| Person | Current Level | Total Meetings | Cancelled | No Shows (Host) | No Shows (Guests) | Calibration | Date Activated | Weight |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| Name, Email | Cell | Cell | Cell | Cell | Cell | Cell |Cell | Cell |

<sub>[CAL-4467](https://linear.app/calcom/issue/CAL-4467/add-more-columns-to-insights-people-table)</sub>

<sub>[CAL-4741](https://linear.app/calcom/issue/CAL-4741/[cal-4467]-add-more-columns-to-insights-people-table)</sub>

**Comment by vaibhav-60** [comment]
i can't work on this???

**Comment by PeerRich** [comment]
i’m already working on it
