### ISSUE TITLE
[BUG] : Change twitter icon and name to X icon on docs page

### ISSUE THREAD

**Issue by raghunandandev** [calcom/cal.com#16968]
### Issue Summary

The icon for "Twitter" which is now "X" should be changed on docs page which redirects us to X.

### Steps to Reproduce

1. Go to home page.
2. Clicked on docs in navigation bar
3. And then you will be redirected to the docs page.
4. Scroll down to the end and then you will see that there is previous Twitter icon and name which is now "X"

### Actual Results

- Now the page will show the current name and icon for X

### Evidence

- 
![BugTwitterIcon](https://github.com/user-attachments/assets/e540f7cd-b1ae-4dd2-b0ac-4cef7024f354)

**Comment by anikdhabal** [comment]
Hey @raghunandandev could you pls open the same issue here https://github.com/calcom/docs
