### ISSUE TITLE
[CAL-4503] Add back all cities in timezone select

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#17067]
![Screenshot 2024-10-11 at 9.02.25 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/51c511f8-38b1-4d62-b0dc-6e1861879b1b/4c8273e2-4148-406a-ba70-2128667d65a2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81MWM1MTFmOC0zOGIxLTRkNjItYjBkYy02ZTE4NjE4NzliMWIvNGM4MjczZTItNDE0OC00MDZhLWJhNzAtMjEyODY2N2Q2NWEyIiwiaWF0IjoxNzI4NjUxODc2LCJleHAiOjE3NjAxODc4NzZ9.2CtRXlbWa2cx18lSDBO1GiVl-khpHjXgBRJFvwWgq4Q)

These changes were made in [https://github.com/calcom/cal.com/pull/16974](https://github.com/calcom/cal.com/pull/16974)

We can add these additional timezones, but we should also keep all the cities we had before

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4503](https://linear.app/calcom/issue/CAL-4503/add-back-all-cities-in-timezone-select)</sub>

**Comment by Aditya-A-G** [comment]
Hey, I would like to work on this issue.
