### ISSUE TITLE
Bookings between 2 cal.com users show on both accounts, cancel email sends to wrong account

### ISSUE THREAD

**Issue by sec0ndhand** [calcom/cal.com#1708]
### Issue Summary

When creating an event between 2 people on cal.com (just for a test), The event shows up in both user's upcoming bookings.  This happened once in the past (sometime around December) when I met with Peer, and it happened again today between my 2 cal.com accounts.

### Steps to Reproduce

1. Create 2 accounts, account A and B on cal.com
2. View the calendar of account A
3. Schedule an event on account A using the email from account B
4. Log in to account B
5. Observe that you can see the event for account A

I don't think that account B should be able to see the events scheduled on account A's calendar/account

1. Cancel the event
2. Observe the cancel email is sent to account B instead of account A (using the link provided in account A) 

### Technical details

- Browser version: Chrome 97

**Comment by andreaestefania12** [comment]
Hi, I would like to contribute to this issue. Could you please assign me?

**Comment by hariombalhara** [comment]
IMHO, I should be able to see the bookings I am an attendee in. But yes, it is a problem if I cancel it and the cancellation email is sent to me only.

**Comment by hariombalhara** [comment]
@zomars what do you think ?

**Comment by zomars** [comment]
> IMHO, I should be able to see the bookings I am an attendee in. But yes, it is a problem if I cancel it and the cancellation email is sent to me only.

I didn't even knew that you could see your attending bookings from your Cal account. That is an unexpected feature if you ask me. IMO you should only be able to see you upcoming bookings where you're the host. I can see an use case where you would like to see your attending bookings in that view as well but we would delegate that to @Jaibles to decide how we should show that.

**Comment by hariombalhara** [comment]
@Jaibles What should we do here? Should we go ahead and remove the bookings where I am an attendee for now and work on showing attendee bookings somewhere else?(In a followup PR)

**Comment by Jaibles** [comment]
Personally I think there's a huge benefit to seeing events I'm attending as well as the ones where I'm the organiser. I do agree it's somewhat of a hidden feature but I think the solution to it is to call them out (and potentially have them filterable) as opposed to removing them. 

In the long run we want cal to become where you go to see your events so the more of your events we show the better. 

I'll provide designs.

**Comment by PeerRich** [comment]
agree 

i would like to keep the bookings in both peoples /booking page.

i like seeing my upcoming events that i booked on other peoples links
