### ISSUE TITLE
Support for multiple chains like polygon, celo, gnosis chain, etc

### ISSUE THREAD

**Issue by paulofonseca1987** [calcom/cal.com#1709]

**Comment by milospuac** [comment]
Thanks for the suggestion. Our team will have a look at your request.

**Comment by jschulman** [comment]
Confirmed this works out of the box.

I have an NFT on Polygon and it doesn't work unless I switch Metamask to Polygon.

The "to-do" here is:

1. pull down in meeting configuration after Smart Contract config to pick which Chain the smart contract sits on
2. When user is booking, prompt them to pick that chain in Metamask

**Comment by PeerRich** [comment]
closed in favor of https://github.com/calcom/cal.com/issues/1682
