### ISSUE TITLE
[CAL-4511] Meeting link sometimes missing in workflow email

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#17093]
We schedule workflow reminders in different places. I assume that we are missing somewhere to set `metadata: { videoCallUrl: meetingUrl }` for the calendarEvent that is passed

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4511](https://linear.app/calcom/issue/CAL-4511/meeting-link-sometimes-missing-in-workflow-email)</sub>

**Comment by alishaz-polymath** [comment]
They forgot to add {MEETING_URL} var in their workflow email template
