### ISSUE TITLE
[CAL-4540] track "last active" per user in user table (takes last booking or last usage of app.cal.com)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17153]
for both analytics but also as a column in the "Member List"

![image](https://github.com/user-attachments/assets/0d0d5f4c-4ba8-4ede-bea0-593b4c4eafcc)

<sub>[CAL-4540](https://linear.app/calcom/issue/CAL-4540/track-last-login-per-user-in-user-table)</sub>

**Comment by ezhil56x** [comment]
Hello @PeerRich. Should this track the last login time or last online time?
