### ISSUE TITLE
remove "edit location" dialog for non-in-person

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1716]
this dialog ![image](https://user-images.githubusercontent.com/8019099/152704323-3320744e-29de-403f-9530-0d11afb33f80.png)

should only be shown when selecting "in-person or link"
![image](https://user-images.githubusercontent.com/8019099/152704348-a827eb6d-7672-4aca-bab6-ade580a5d0d0.png)

**Comment by miguelnietoa** [comment]
Is this issue still available? Can I take it?
