### ISSUE TITLE
End Time not 24:00 for other TZ users after the end time check fix in #1673 issue

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#1718]
Reported by Cristian Le (@LecrisUT) on PR#1673
```
I believe this has created an issue that the end time for the day is no longer `24:00` if the user and browser or not on UTC timezone. 
```
![image](https://user-images.githubusercontent.com/25577083/152717033-39390692-c542-4a1e-9033-c5477127c70b.png)

_Originally posted by @LecrisUT in https://github.com/calcom/cal.com/issues/1673#issuecomment-1031018770_

**Comment by alishaz-polymath** [comment]
I think that the way time is processed in `/availability`, creating options based on UTC but then only their time (HH:MM) is considered later on, it allows for the possibility of an issue where logically, the end time can't be before start time in terms of the dayjs value but it can still be processed just fine in the API as only time is considered.

An example scenario:

- We set time from 16:00 to 21:00 in availability (GMT+5:30) without the checks introduced in PR#1673
- The time is updated and we can see in `/[user]/[type]` that the available time slots are between 16:00 & 21:00

Now, if we investigate further, the times options filled in the `start` & `end` dropdowns are not for the same day in case of +5:30 timezone which means, the options are spread from `18:30` previous day to `18:15` next day. And this means, any check based on dayjs value of the timeslot would fail in the above scenario.

**Comment by LecrisUT** [comment]
Unrelated, but an interesting btw, there are time systems that use `25:00`, etc. so that the continuity is not broken. This is only relevant if the fixed day of the week is relaxed and/or a continuous week view is adapted.

**Comment by alishaz-polymath** [comment]
@LecrisUT Thank you for pointing out the bug, btw, and thanks for this input. I'm currently exploring how we're processing the selectable timeslots in Availability to see if that can be improved. Rather than patching here and there, it would be better to ensure that the setup is coherent and stable in and of itself :)

**Comment by LecrisUT** [comment]
Also, relevant PR to work on top of is #1691
