### ISSUE TITLE
[CAL-4555] Reassign a booking to a specific user

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#17228]
When you hit edit on a booking, you have two options:
<img width="244" alt="Screenshot 2024-10-21 at 15 56 34" src="https://github.com/user-attachments/assets/2d1bab11-50c3-4039-a56e-1ba831cef4ef">

You can add another guest, or if you click 'reassign', it will push it back to the round robin pool.

I want to extend the reassign functionality so that you can pass a booking to another teammate. It doesn't need to check for conflicts on the assignee's calendar (as we assume they've discussed that already), but it just needs to remove it from person A's Cal.com and calendar, and put it on person B's Cal.com and calendar.

 I figure we can extend this modal to offer between reassigning to a specific person or pushing it back to the round robin pool.
<img width="591" alt="Screenshot 2024-10-21 at 15 58 00" src="https://github.com/user-attachments/assets/40d45926-fec4-49b4-a116-41751b76a6de">

<sub>[CAL-4555](https://linear.app/calcom/issue/CAL-4555/reassign-a-booking-to-a-specific-user)</sub>

**Comment by baileypumfleet** [comment]
I just made a rough design for this in Figma here: https://www.figma.com/design/xk4HOxtSI82J0F7enMxeak/Live?node-id=8983-18555&t=7FVc5fziZHvPT3mD-1

**Comment by PeerRich** [comment]
this is done
