### ISSUE TITLE
[CAL-4577] seated bookings leak attendee information

### ISSUE THREAD

**Issue by supalarry** [calcom/cal.com#17246]
I have a seated event type with Share attendee information between guests disabled.

First, Rajiv make a booking and then Somay made a booking on same day and time, and Somay was able to see that Rajiv is one of the attendees while only Somay should appear in attendees. Curious if someone else can try reproducing this.

Second, customer on [Slack](https://calcominc.slack.com/archives/C0727EKAM43/p1727960053181219) reported that seat attendee information is leaked in emails:
<img width="726" alt="Screenshot 2024-10-22 at 16 28 57" src="https://github.com/user-attachments/assets/c4351c53-193b-4ca1-bb2e-1485c863cc90">

When we tested this in web app same was true - after Somay cancelled his booking the email that he received said that booking between Lauris Skraucis (me) and Rajiv was cancelled. Shortly, if second person of a slot cancels seated booking then he / she receives e-mail mentioning first attendees name.

<sub>[CAL-4577](https://linear.app/calcom/issue/CAL-4577/seated-bookings-leak-attendee-information)</sub>

**Comment by anikdhabal** [comment]
Booking leak on success page was fixed by this:- https://github.com/calcom/cal.com/pull/17338
And the booking title issue is transferred here:- https://github.com/calcom/cal.com/issues/17367
