### ISSUE TITLE
Warn on calendar requests from disposable email adresses

### ISSUE THREAD

**Issue by raro42** [calcom/cal.com#1725]
### Is your proposal related to a problem?

I got bookings from people that are using disposable email adresses as seen on https://disposable.help/domain/mannawo.com

It would be nice to either not allow such emails to be used for booking or put a WARNING in the calendar entry.

### Describe the solution you'd like

Have an option in my app.cal.com settings that per default blocks disposable emails from booking my calendar.
or puts a WARNING in the calendar entry.

It would be really cool, if cal.com learned from users which emails are bad and from there could provide these learned email adresses as a blacklist for convinience to block right away.

**Comment by PeerRich** [comment]
lets see if we can find an email spam package that covers some of those things.

it would also be cool if the frontend warns you if you type in gnail.com instead of gmail.com

**Comment by tompec** [comment]
Hey @PeerRich, you can't fight this with a package because new domains are added daily.
I've built [MailCheck.ai](https://www.mailcheck.ai/) for that reason. It has a generous free tier that should solve your problem.
See also: https://www.mailcheck.ai/domain/mannawo.com
Let me know if I can help!

**Comment by PeerRich** [comment]
also for privacy reasons we cant send emails to your server

**Comment by tompec** [comment]
> also for privacy reasons we cant send emails to your server
There's an endpoint to send only domains. I've sent you an email!

**Comment by baubie** [comment]
Would be great to keep this discussion public please.  I'm curious if people feel that domains can be just as sensitive since small domains can be personally identifying.

**Comment by PeerRich** [comment]
> Would be great to keep this discussion public please.  I'm curious if people feel that domains can be just as sensitive since small domains can be personally identifying.

absolutely. we dont want to run any data through a third party.

**Comment by PeerRich** [comment]
it looks like we can use this: https://www.npmjs.com/package/deep-email-validator it also includes blacklisted emails

**Comment by Robinzon100** [comment]
Has this been abandoned? or am I missing a setting that I need to enable in the dashboard?
