### ISSUE TITLE
Slash (`/`) in meeting URLs throws a 404

### ISSUE THREAD

**Issue by AnandChowdhary** [calcom/cal.com#1729]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When editing an event type, you can add a URL with a slash (`/`).  For example, I tried to set up cal.com/anand/hiring/20 for a 20-minute introductory call for hiring. However, this throws a 404 error since the slug only matches one level of route param.

We should either add validation to prevent the use of certain special characters like slash, question mark, and hash, which are reserved for URLs. Alternately, we should allow nested URLs (which would be awesome since I can use /hiring/etc!) and update the route matching for it. In Next.js for example, the file name `[name].jsx` should be replaced with `[...name].jsx` to support this.

<img width="744" alt="CleanShot 2022-02-07 at 23 17 26@2x" src="https://user-images.githubusercontent.com/2841780/152843437-680fc68d-d194-4bd8-8988-dacc8512dc6c.png">

### Steps to Reproduce

1. Click on an event to edit it
2. Add a URL with a slash in it
3. Save the event
4. Try to open the event

**Comment by PeerRich** [comment]
i think nested routes could cause many side effects so we rather not allow it but we could add a duration overwrite hiring/15 overwrites the `hiring` event-types duration from 20 to 15

**Comment by AnandChowdhary** [comment]
That's a good idea! For now, maybe the best is to not allow a slash in the URL?

**Comment by Jenietoc** [comment]
Hi everyone, can I add the validation to disallow `/` in the URL

**Comment by PeerRich** [comment]
> Hi everyone, can I add the validation to disallow `/` in the URL

sure go for it! Thank you @Jenietoc
