### ISSUE TITLE
Bookings confirmed but not added to Outlook shared calendar 

### ISSUE THREAD

**Issue by aaronjedwards** [calcom/cal.com#17298]
### Issue Summary

We have been using Cal.com connected an Outlook account with access to a shared calendar and booking events to that shared calendar. We started noticing roughly two weeks ago that although the bookings are being completed via Cal.com and we are receiving email confirmations, the events are not actually being booked on the shared calendar.

### Actual Results

- Bookings are completed, but events are not being added to our shared calendar.

### Expected Results

- When specifying a shared calendar to book events to, the events should successfully be added to the calendar.

### Technical details

Using hosted Cal.com

EDIT:
In an attempt to fix this issue, I have uninstalled the Outlook app, with the idea that maybe reinstalling it will solve the problem. Unfortunately, I am unable to install the outlook app at all now. I tried this on a fresh account and with a different outlook account and it appears the Outlook integration is not properly installing at all anymore.

**Comment by toontoet** [comment]
I'm experiencing exact the same problem. Bookings are completed, but don't appear in a shared calendar. If I switch to a personal calendar it works perfectly.

There are no errors in the log that indicate anything wrong with the API.

There also seems to be a difference between certain outlook users. Some work and some don't. We've done some research but there is no difference in user rights on the shared calendar. Manually those users can fully edit the shared calendars.

Events that are manually added to the outlook shared calendar are properly synced when checking availability. So there seems to be some API connection.

The problems started to occur end of September. But the cal.com software was not updated around that time. Also after updating to the latest version it didn't resolve the problem.

**Comment by toontoet** [comment]
I tried to debug this issue a little more and I got this in the debug log:

```
calcom-calcom-1  | @calcom/web:start: 13:24:26:996	DEBUGCalendarManager Created calendar event {"calEvent":{"eventTypeId":8,"type":"test","startTime":"2024-11-18T09:30:00Z","endTime":"2024-11-18T09:45:00Z","schedulingType":null,"seatsPerTimeSlot":null,"requiresConfirmation":false,"uid":"XXX","iCalUID":"XXXl","title":"PiiFree:true"},"creationResult":{"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}}
```

I dug a little deeper in my Azure App configuration and saw that only the following API permissions where requested: "User.Read", "Calendars.Read", "Calendars.ReadWrite", "offline_access"
However to access shared calendars "Calendars.ReadWrite.Shared" should be added in packages/app-store/office365calendar/api/add.ts I think.

Maybe this worked before, but now it doesn't.

**Comment by toontoet** [comment]
Apart from the permission Calendars.ReadWrite.Shared that should be requested the error in case of an ErrorAccessDenied should also be handled I guess.

**Comment by aaronjedwards** [comment]
As far as I can tell, this has not been fixed so it might be worth it to re-open this for tracking purposes. The fix was reverted as part of https://github.com/calcom/cal.com/pull/18130. We are still experiencing this issue unfortunately. @keithwillcode or @toontoet do you have more information as to why this was reverted and how we can work towards a fix?

**Comment by toontoet** [comment]
I have no idea why the fix was reverted. It worked perfectly for me, and now it doesn't anymore. Maybe it caused issues with existing users, while there was no clean migration? Don't know... Would love to hear more about it.

**Comment by keithwillcode** [comment]
https://github.com/calcom/cal.com/pull/17760#issuecomment-2635814942
