### ISSUE TITLE
Duplicate Webhooks too, when duplicating event types

### ISSUE THREAD

**Issue by hiddenest** [calcom/cal.com#17297]
### Is your proposal related to a problem?

It was quite tedious for me when migrating to cal.com.
There was no option to set up webhooks for all events at once, and when duplicating event types, the webhook information didn't carry over. I had to configure each one manually.

### Describe the solution you'd like

1. Global webhook setting (setup to all event types automatically)
2. Duplicate webhook settings too, when duplicating event types

---

##### House rules

- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by hiddenest** [comment]
I just found that, 1) global webhook settings is in Developer > Webhooks.

**Comment by Praashh** [comment]
alrighty then closing this issue for now.
