### ISSUE TITLE
[CAL-4598] Search the people filter within insights

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#17304]
<img width="285" alt="Screenshot 2024-10-24 at 14 16 25" src="https://github.com/user-attachments/assets/6119425c-7ad2-4c0f-8b1f-436dd6ae6ed8">

<sub>[CAL-4598](https://linear.app/calcom/issue/CAL-4598/search-the-people-filter-within-insights)</sub>

**Comment by anikdhabal** [comment]
Fixed by this:- https://github.com/calcom/cal.com/pull/17320
