### ISSUE TITLE
[CAL-4756] Issue with missing email notifications for Attendees and Organizer when creating a booking via Cal.com API

### ISSUE THREAD

**Issue by alamosapp** [calcom/cal.com#17315]
Hello Support Team,

We are encountering an issue with the Creating a Booking API (Path: **_/api-reference/v2/bookings/create-a-booking_**). Despite successfully booking events via the API, neither the attendees nor the organizer are receiving email notifications.

This is a critical problem as email notifications are essential to ensure that all participants are informed about their scheduled events. We have verified that the email addresses for both attendees and the organizer are correct and the event creation process works as expected, except for the lack of notification emails. (We check the spam folder too)

Could you please investigate this issue and provide guidance on how to ensure email notifications are triggered when using the mentioned path?
Thank you for your support.

Best regards,

Armand Jensen-Bennet

Evidence:

![cal com screenshot](https://github.com/user-attachments/assets/6f3797a5-08be-4963-a1d0-4ba9870b1989)
![cal com screenshot headers](https://github.com/user-attachments/assets/de4ded3e-8dbb-4dcc-b7d7-d2242fdfab50)
GTM-05:00
![cal com screenshot booked](https://github.com/user-attachments/assets/2c26f71c-c398-4947-96d4-e6f88c346a24)

<sub>[CAL-4756](https://linear.app/calcom/issue/CAL-4756/issue-with-missing-email-notifications-for-attendees-and-organizer)</sub>

**Comment by andrebrito16** [comment]
Same issue here

**Comment by 111churchstreet** [comment]
yeah same shit here. puts all of the attendees email addresses and name under bookingFieldsResponses colelction and not attendees array. so none of the booking reminders work (because it works off attendee emails).

**Comment by 111churchstreet** [comment]
@PeerRich @keithwillcode @CarinaWolli look at this issue i think its the same as this issue: https://github.com/calcom/cal.com/issues/17662#issue-2661999747

attendee emails are showing up under "bookingFieldsResponses" in the outptut from https://api.cal.com/v2/bookings and not the "attendees" array so none of the workflows reminders are working (as they work off attendee emails)

**Comment by 111churchstreet** [comment]
> @PeerRich @keithwillcode @CarinaWolli look at this issue i think its the same as this issue: [#17662 (comment)](https://github.com/calcom/cal.com/issues/17662#issue-2661999747)
> 
> attendee emails are showing up under "bookingFieldsResponses" in the outptut from https://api.cal.com/v2/bookings and not the "attendees" array so none of the workflows reminders are working (as they work off attendee emails)

yo @dosubot u know whats going on

**Comment by keithwillcode** [comment]
@ThyMinimalDev @supalarry Can you please add this to the current milestone to fix?

**Comment by supalarry** [comment]
> yeah same shit here. puts all of the attendees email addresses and name under bookingFieldsResponses colelction and not attendees array. so none of the booking reminders work (because it works off attendee emails).

Email in the `attendees` array is filtered right now for privacy purposes in the response.
