### ISSUE TITLE
[CAL-4626] OOO does not allow to select a single day and behaves buggy

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#17359]
Minor issue affecting https://app.cal.com/settings/my-account/out-of-office

If you select e.g. Nov 1, from Nov 1 to Nov 1 - it allows you to do it, but if you save that; and click back in, Nov 1 - Oct 31 is selected. This should "correct" to Nov 1 - Nov 2

<sub>[CAL-4626](https://linear.app/calcom/issue/CAL-4626/ooo-does-not-allow-to-select-a-single-day-and-behaves-buggy)</sub>

**Comment by Praashh** [comment]
it's working now.
