### ISSUE TITLE
Location URL prefill breaks input form

### ISSUE THREAD

**Issue by vitis586** [calcom/cal.com#17394]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I want to be able to prefill everything for my customer, so they can just confirm and pay for the booking. However I encountered an issue with the location field.

Location is set to "In Person (Attendee Address)".

### Steps to Reproduce

1. Have an event with fields phone and location
2. Create an URL which prefills all the fields, like: https://cal.com/testing586/15min?date=2024-11-30&month=2024-10&slot=2024-11-30T12%3A15%3A00.000Z&name=Viktor&email=example@example.com&location=Italy&phone=+420725639838
3. Observe that the location field is hidden

![image](https://github.com/user-attachments/assets/800ef058-2e1f-4b91-b53a-961dd5911319)

### Actual Results

The booking is created but the Where is shown as `attendeeInPerson` instead of the desired Italy.

### Expected Results

I expect to see the location from the URL in the created booking.

### Technical details

Tested in latest Firefox and Opera browsers, on latest cal.com website and on 4.6.12 selfhosted.

### Evidence

I guess that clicking the link and see the bug is enough - https://cal.com/testing586/15min?date=2024-11-30&month=2024-10&slot=2024-11-30T12%3A15%3A00.000Z&name=Viktor&email=example@example.com&location=Italy&phone=+420725639838

**Comment by ajeet72** [comment]
Hey @vitis586 , I reproduced the issue, and it's working as expected.

you can see it here: https://cal.com/ajeet-kumar-6xsgri/15min?date=2024-10-31&month=2024-10&slot=2024-10-31T11%3A00%3A00.000Z

![image](https://github.com/user-attachments/assets/e53ddaec-033b-4166-80d7-20690008bafb)

**Comment by vitis586** [comment]
@ajeet72 Well, it works as I described. If you try to prefill the location, it breaks - the location. https://cal.com/ajeet-kumar-6xsgri/15min?date=2024-10-31&month=2024-10&slot=2024-10-31T11%3A00%3A00.000Z&location=Italy

![obrazek](https://github.com/user-attachments/assets/fc13647f-0fee-4a65-97a2-9566435fbe34)

I tried it it Chrome and Firefox on Android as well now.

@AdityaGupta-cyber You would have to cc someone from the team. I am just a user reporting this. 😉

**Comment by vitis586** [comment]
It can be done. It is just not as straightforward because the location field is still a radio button type even when just one option is available. The link should look like this

https://cal.com/testing586/15min?date=2024-11-30&month=2024-10&slot=2024-11-30T12%3A15%3A00.000Z&name=Viktor&email=example@example.com&phone=+420725639838&location={%22value%22:%22attendeeInPerson%22,%22optionValue%22:%22Italy%22}

More information can be found here - https://cal.com/help/en/articles/9937901-pre-fill-fields-questions
