### ISSUE TITLE
Additional inputs on booking page

### ISSUE THREAD

**Issue by KATT** [calcom/cal.com#1747]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Additional inputs are a bit funny looking with the `<br/><br/>`-stuff

<img width="1180" alt="Screenshot_2022-02-08_at_16_11_32" src="https://user-images.githubusercontent.com/459267/153016727-88667ee1-b589-48ae-ad1c-9167762e54b7.png">

### Steps to Reproduce

1. Add additional input (TEXT)
2. Book a meeting 
3. Go to `/bookings`

**Comment by PeerRich** [comment]
can you check if this fixes it? https://github.com/calcom/cal.com/pull/1750

**Comment by denik1981** [comment]
I'm not able to reproduce this locally (meaning without the #1750 fix). 
I have tried using different types of text input patterns (newline prefix, whitespace, multiline, etc)

**Comment by PeerRich** [comment]
> I'm not able to reproduce this locally (meaning without the #1750 fix). 
> 
> I have tried using different types of text input patterns (newline prefix, whitespace, multiline, etc)  

@KATT can you do another test?

**Comment by denik1981** [comment]
> @KATT can you do another test?


https://user-images.githubusercontent.com/66160623/153063579-7977a864-688c-45b5-88e3-4ac60cf44222.mov

**Comment by denik1981** [comment]
I tried every possible combination for `[\s-\t]*.*\n*` but I didn't include those in the video.
And I only test this locally (dev). MIght be happening in prod.
