### ISSUE TITLE
[CAL-4678] Assignment: "Add all team members, including future members" needs retoggle sometimes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17496]
<img width="696" alt="CleanShot 2024-11-05 at 18 27 46@2x" src="https://github.com/user-attachments/assets/999df877-b65e-43a2-99ae-071dce95b79f">

this toggle every now and then doenst pick up new members (which is the whole point).

and when that happens, the user has to toggle off and on again to add the new people 

<sub>[CAL-4678](https://linear.app/calcom/issue/CAL-4678/assignment-add-all-team-members-including-future-members-needs)</sub>

**Comment by Udit-takkar** [comment]
fixed https://github.com/calcom/cal.com/pull/17522/files
