### ISSUE TITLE
[CAL-4730] Slovak language support

### ISSUE THREAD

**Issue by pipozzz** [calcom/cal.com#17509]
### Is your proposal related to a problem?

I'd like to add Slovak translation, so Slovak clients whould understand it better.

<sub>[CAL-4730](https://linear.app/calcom/issue/CAL-4730/slovak-language-support)</sub>

**Comment by pipozzz** [comment]
Any update? I'd like to help you out with this if possible.

**Comment by PeerRich** [comment]
@keithwillcode can we add slovak to replexica?

**Comment by maxprilutskiy** [comment]
@PeerRich https://github.com/calcom/cal.com/pull/17652 🚀
