### ISSUE TITLE
Daily.co Cloud Recording on new booking

### ISSUE THREAD

**Issue by snikpic** [calcom/cal.com#1752]
### Is your proposal related to a problem?

Is there a way to ensure sessions are recorded when integrating Daily.co video calling ? There doesn't seem to be an option on either the booking or the interface when the call starts

### Describe the solution you'd like

Have recording button in the virtual conference room

### Describe alternatives you've considered

Have the option on the booking events and/or have a setting option to enable recording on calls

### Additional context

I have a full plan Daily.co in Scale (which has cloud recording included)

**Comment by milospuac** [comment]
Hi there! Thanks for sharing this. Our team will have a look see what can be done. Will update you once I know more

**Comment by lunchpaillola** [comment]
Hey, @snikpic! In your .env file if you set the Daily_Scale_Plan parameter to 'true' you'll have access to local recording which will allow you to see the record button and start a recording when you're in a meeting.

**Comment by sean-brydon** [comment]
Question has been answered - Thank you.
