### ISSUE TITLE
[CAL-4675] Move organization /settings/organizations/members to /members

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#17534]
* Move organization member list from settings to the root Navigation
* Only visible if in an org

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4675](https://linear.app/calcom/issue/CAL-4675/move-organization-settingsorganizationsmembers-to-members)</sub>

**Comment by ciaranha** [comment]
I think we should swap "Teams" in favour of the "Members" table solely for Orgs. Having "Teams" in the sidebar makes a ton of sense for upselling in a regular context, but in an Org it offers little value. You will setup your teams from the start, and very occassionally edit/add teams - it adds little or no value. Thoughts @peer @sgriff96-brydon

**Comment by keithwillcode** [comment]
@eunjae what you point out about the /members url only pointing to orgs members is indeed a bit odd since teams have members too. We’ll have some inconsistency there in terms of url structure

**Comment by keithwillcode** [comment]
Yeah that’s fine
