### ISSUE TITLE
[CAL-4686] [high] Seated events do not count the attendees already booked the event.

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#17542]
## **\[high\] Seated events do not count the attendees who already booked the event.**

Also tested it with my own event:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e68dd3d6-45f1-463f-b587-e0aed6ca0a94/6f4ac45b-9bc6-499f-95f1-81c77b1d51e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lNjhkZDNkNi00NWYxLTQ2M2YtYjU4Ny1lMGFlZDZjYTBhOTQvNmY0YWM0NWItOWJjNi00OTlmLTk1ZjEtODFjNzdiMWQ1MWU5IiwiaWF0IjoxNzMxMDA0MTg5LCJleHAiOjE3NjI1NDAxODl9.pGmetnGauFOsFJi4_mlUAXa4AsB7IRs1Nc0LfQL0F3c)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a85360e3-e2bb-49f1-9fec-ac070b08fb9f/89b2ffe9-cc04-4fb3-bd8c-5bf9f501e3ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hODUzNjBlMy1lMmJiLTQ5ZjEtOWZlYy1hYzA3MGIwOGZiOWYvODliMmZmZTktY2MwNC00ZmIzLWJkOGMtNWJmOWY1MDFlM2VkIiwiaWF0IjoxNzMxMDA0MTg5LCJleHAiOjE3NjI1NDAxODl9.oA8XwHd93VgkVyTKoYm0ui4eCMejouyv9U3VcHE3NQM)

I should have 3 seats left here:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c564c02a-259a-40e8-b87b-251ef4d5ea78/06e73ed7-2acc-42ae-bf73-1a1c870cc038?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jNTY0YzAyYS0yNTlhLTQwZTgtYjg3Yi0yNTFlZjRkNWVhNzgvMDZlNzNlZDctMmFjYy00MmFlLWJmNzMtMWExYzg3MGNjMDM4IiwiaWF0IjoxNzMxMDA0MTg5LCJleHAiOjE3NjI1NDAxODl9.GTbBYp_kqB58Bn0zkOLApEfohOzMoqMBGSAOQXuMd7E)

Even if the event is completely full, it still allows attendees to continue booking.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4686](https://linear.app/calcom/issue/CAL-4686/[high]-seated-events-do-not-count-the-attendees-already-booked-the)</sub>

**Comment by mecacounseling** [comment]
I'm experiencing the same problem #17541
