### ISSUE TITLE
Improve code quality with code climate

### ISSUE THREAD

**Issue by russellwmy** [calcom/cal.com#1755]
### Is your proposal related to a problem?

(Write your answer here.)
Since the codebase is getting complex and bigger, the workload for PR reviewers will be very high and the code quality is hard to maintain.

### Describe the solution you'd like

(Describe your proposed solution here.)
Add [code climate](https://codeclimate.com) to the CI/CD pipeline to automate code quality check.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by milospuac** [comment]
Hey Russell! Thanks for your suggestion. Our team will have a look.
