### ISSUE TITLE
[CAL-4693] regression: avatar missing in social media preview

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17562]
<img width="708" alt="CleanShot 2024-11-08 at 20 33 17@2x" src="https://github.com/user-attachments/assets/4271968e-b0b7-4e14-a5cc-950c7f30933d">

<sub>[CAL-4693](https://linear.app/calcom/issue/CAL-4693/regression-avatar-missing-in-social-media-preview)</sub>

**Comment by suman7802** [comment]
Hi @PeerRich,
I am new here and currently exploring open-source contributions. I came across an issue, but I am not sure how to reproduce the error. Could you please guide me on how to replicate this issue?

**Comment by hbjORbj** [comment]
Fixed by #17592

@suman7802 Would be great if you are open to working on other issues!
