### ISSUE TITLE
Adding google calendar should add all my existing calls to my calendar

### ISSUE THREAD

**Issue by hkirat** [calcom/cal.com#17587]
### Is your proposal related to a problem?
I just installed cal, but didnt give access to my calendar. 
3 people booked bookings, and to make sure I dont miss them I added the `Google Calendar App` from the Apps section

### Describe the solution you'd like

If I integrate google calendar, it should automatically add all my existing meetings to the calendar

### Describe alternatives you've considered
No alternates

### Additional context

Please feel free to close if this already happens, although attaching my calendar where I dont see 2 of my meetings for tomorrow

<img width="222" alt="Screenshot 2024-11-12 at 12 21 22 AM" src="https://github.com/user-attachments/assets/b30c5bfd-e9bf-4d97-b490-c62b89fef949">

<img width="1523" alt="Screenshot 2024-11-12 at 12 21 30 AM" src="https://github.com/user-attachments/assets/d29d6f9e-89af-4f10-81ed-874b4ea6d993">

**Comment by Praashh** [comment]
Hey @hkirat , did you enable overlay while booking?

![image](https://github.com/user-attachments/assets/96e42bd6-5223-41c5-9a14-b429334d4794)
in the above screenshot, you can see, that I have enabled that while booking a meet.

Both the organizer and user must be available at the time of booking. In the screenshot below, you can see that both parties are available at 4:30 PM IST, and consequently, the meeting was successfully added to their Google calendars. If either person is unavailable, the meeting will not be added to their calendar

### organizer 
![image](https://github.com/user-attachments/assets/0917a9aa-9516-43d6-8804-12a08e94ec86)

### user 
![image](https://github.com/user-attachments/assets/c03fa7c7-b308-46e4-a884-f7c70eef77b7)

I just wanted to let you know that it is working fine for me.

### organizer 
![image](https://github.com/user-attachments/assets/670539ad-4089-43b2-8353-e91cbeda0f20)

### user 
![image](https://github.com/user-attachments/assets/b2802f16-9964-4620-94c3-40318d2fb1fe)


Please try enabling the overlay option and let us know if there is still the same issue.

**Comment by hkirat** [comment]
Makes sense, not facing this issue anymore since I connected so closing for now
