### ISSUE TITLE
[CAL-4705] Type error: 'searchParams' is possibly 'null'

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#17602]
@neuhaus @abhi-slash-git  @sean-brydon this is now causing issues locally. I'm getting the same errors when building locally.

![image](https://github.com/user-attachments/assets/6edab1e8-bb7e-462e-8932-0ac4e0e8bc88)

_Originally posted by @zomars in https://github.com/calcom/cal.com/issues/16862#issuecomment-2471232983_
            

<sub>[CAL-4705](https://linear.app/calcom/issue/CAL-4705/type-error-searchparams-is-possibly-null)</sub>

**Comment by AnkityadavIITR** [comment]
Hii @zomars i've create the pr please let me know if anything needs to be update

**Comment by andreanicassio** [comment]
I am still getting this!
