### ISSUE TITLE
yarn db-reset throws "Can't reach database server"

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#1766]
### Issue Summary

Running `yarn db-reset` ends up in a Prisma Error within the migration step.
```
yarn run v1.22.17
$ run-s db-nuke db-setup
$ docker-compose down --volumes --remove-orphans
Stopping calcom_postgres_1 ... done
Removing orphan container "calcom_postgres_is_ready_1"
Removing calcom_postgres_1 ... done
Removing network calcom_default
Removing volume calcom_db_data
$ run-s db-up db-migrate db-seed
$ docker-compose up -d
Creating network "calcom_default" with the default driver
Creating volume "calcom_db_data" with default driver
Creating calcom_postgres_1 ... done
$ yarn prisma migrate dev && yarn format-schemas
$ /home/demian/code/open/calcom/calcom/node_modules/.bin/prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "calendso", schema "public" at "localhost:5450"

Error: P1001: Can't reach database server at `localhost`:`5450`

Please make sure your database server is running at `localhost`:`5450`.
error Command failed with exit code 1.
```
Running the inner tasks separately and in the proper order doesn't make the task fail.
Seems postgres isn't ready by the time prisma attempts to start the migrations.
  
### Steps to Reproduce

1. `yarn dx`
2. `yarn db-reset`

### Technical details

- yarn: '1.22.17'
- calendso: '1.0.0'
- node: '14.19.0'
- uname -orv: `5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 GNU/Linux`

**Comment by emrysal** [comment]
I think in this situation you can use `yarn prisma migrate reset` to reset and reseed the db - have a look whether this works for you and we'll probably update our scripts to match.

**Comment by denik1981** [comment]
I think the idea behind **db-reset** is to make a **hard** cleanup of the whole db. Meaning not just the migrations and the seed data but the physical volume as well which is something Prisma alone cannot do. IMHO is a good idea to have it in place for a life-saver and handy start-over task.
