### ISSUE TITLE
Attendee emails outputting under "bookingFieldsResponses" from https://api.cal.com/v2/bookings. Workflows wont fire on it (as it works on attendeees!!)

### ISSUE THREAD

**Issue by 111churchstreet** [calcom/cal.com#17703]
Attendee emails are showing up under "bookingFieldsResponses" in the outptut from https://api.cal.com/v2/bookings and not the "attendees" array. So my confirmation workflows aren't firing.

None of the workflow reminders are firing for that matter (as they work off attendee emails i suspect - am non technical)

here's my output:
  "meetingUrl": "integrations:google:meet",
                "location": "integrations:google:meet",
                "absentHost": false,
                "attendees": [
                    {
                        "name": "Harrison",
                        "timeZone": "America/New_York",
                        "language": "en",
                        "absent": false
                    }
                ],
                "bookingFieldsResponses": {
                    "email": "harrison@xxxx.com",
                    "name": "Harrison",
                    "additionalInfo": "Some metadata information"

Same issue in this other users post: https://github.com/calcom/cal.com/issues/17662

**Comment by asadath1395** [comment]
@Praashh  This is working fine now in the latest deployment. We can close this issue.
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/b69c3a67-dc18-4d33-9d08-731cd7aa122f" />

cc @PeerRich @keithwillcode

**Comment by Praashh** [comment]
alright, closing it for now 🙏 .
