### ISSUE TITLE
Event types page does not load once the onboarding is finished

### ISSUE THREAD

**Issue by miguelnietoa** [calcom/cal.com#1773]
### Issue Summary
Once the onboarding at route `/getting-started` is complete, it redirects to `/event-types` but the page does not load. It's necessary to reload the page.

### Steps to Reproduce

1. Sign up a user
2. Login this user
3. Complete the onboarding (`/getting-started`)
4. Page keeps loading...

https://app.birdeatsbug.com/sessions/8BJH3WZ7GycPFmqT7mC39

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/8RJH8
- Node.js version: `14.17.6`

**Comment by PeerRich** [comment]
has been fixed by @alishaz-polymath great stuff! thank you for reporting

**Comment by denik1981** [comment]
I can confirm this is happening as well. 
I have submitted PR #1981 which fixes this.

**Comment by PeerRich** [comment]
> I can confirm this is happening as well. I have submitted PR #1981 which fixes this.

awesome thank you! will test today
