### ISSUE TITLE
Show "Add to calendar" on booking confirmation page for non-host users

### ISSUE THREAD

**Issue by nikwen** [calcom/cal.com#17749]
### Is your proposal related to a problem?

When I am logged into my Cal.com account and use my own meeting link, I see an awesome section "Add to calendar" on the booking confirmation page:

![Screenshot](https://github.com/user-attachments/assets/7e3fe05e-0859-4487-aaae-5ba637588dd7)

This section is not visible when someone else uses my booking link (e.g. a customer).

However, having a way for my customers to add an event to their calendars from the booking page could dramatically help prevent no shows.

When the event is only sent via email, some people forget to add it to their calendars.

### Describe the solution you'd like

I'd love it if my customers saw the same "Add to calendar" section after booking an event with me.

That would remind them to make sure the event makes it onto their calendars.

### Describe alternatives you've considered

Currently, attendees have to go into their email inbox and add the event to their calendar.

Sometimes people forget, and then they don't show up to meetings.

### Additional context

This is the condition controlling the section:

https://github.com/calcom/cal.com/blob/7c5292e13beeb74f2488306198dc53a69620eccf/apps/web/modules/bookings/views/bookings-single-view.tsx#L792-L796

I know that you show a "Create your own booking link with Cal.com" section in the same place if the host hasn't disabled Cal.com branding.

So for me it would be fine if this section only showed up for paid accounts that have Cal.com branding disabled. (I'm happy to pay just for this feature!) Alternatively, you could show both sections.

### Requirement/Document

None

---

##### House rules

- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by sriharika13** [comment]
Hi @nikwen I understand the issue, can you assign it to me? I'm willing to work on it
