### ISSUE TITLE
404 Page has incorrect "claim username" URL

### ISSUE THREAD

**Issue by alii** [calcom/cal.com#1774]
### Issue Summary

Claim username page has invalid registration URL, has the username query param set to an apple-touch-icon

### Steps to Reproduce

Go to a username page that doesn't exist and click the "claim username" (check bottom left of screenshot)
![image](https://user-images.githubusercontent.com/25351731/153309631-b55827f7-15c3-4540-bcfe-0c27edf18da7.png)

**Comment by alii** [comment]
Also not sure if it's a bug or not, but I can't seem to access my personal URL `/@alistair` as it is causing this 404. I think it might be a caching issue but not running this locally so just wanted to report either way.

**Comment by miguelnietoa** [comment]
Could you be more specific about the scenarios in which this issue happens? Everything seems to work fine based on my tests 🤔

**Comment by arthurdenner** [comment]
I can reproduce it on different URLs on cal.com and on localhost after building the project - not in dev mode.

![image](https://user-images.githubusercontent.com/13774309/153365511-797530d6-73e5-4256-8655-836a5f93dea2.png)

Sometimes I got ?username=rss too. On localhost, after building the project, I got ?username=404 too.

I added a debugger to the code on cal.com and could see it happening:


https://user-images.githubusercontent.com/13774309/153367470-c3f6d4aa-79e4-4085-925f-1208cb7319bf.mp4

**Comment by PeerRich** [comment]
wtf that is pretty wild behavior.

**Comment by alii** [comment]
> Could you be more specific about the scenarios in which this issue happens? Everything seems to work fine based on my tests 🤔

I really couldn't unfortunately, it was literally just opening a 404 page and seeing that as the `username` query param.

>

**Comment by PeerRich** [comment]
i was able to reproduce it and got x.php which is really weird since we dont have a single php file in the repo lol

where the fck is this coming from

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/8019099/153400835-dc310da9-07a9-435d-a437-51a1810226f5.png">

**Comment by PeerRich** [comment]
it literally uses the same {username} variable that is being used to render **Register /testing-test** 

why does it work for text but not for a link?

https://github.com/calcom/cal.com/blob/main/pages/404.tsx#L180

**Comment by PeerRich** [comment]
added a Link component, lets see if it fixes it. https://github.com/calcom/cal.com/pull/1784

can't reproduce it on localhost for some reason

**Comment by alii** [comment]
This is so odd 😆

**Comment by PeerRich** [comment]
> This is so odd 😆

added `<Link>` and didn't help. still getting the weirdest strings

<img width="602" alt="image" src="https://user-images.githubusercontent.com/8019099/153583607-b63a7b6f-9d7c-4217-bdae-1afe0c254c8d.png">

**Comment by PeerRich** [comment]
OHH I have a hunch. this could be a caching error. someone may have entered cal.com/x.php before me

**Comment by PeerRich** [comment]
https://www.loom.com/share/1ed46db630ed4cea861432b2d67d6262
