### ISSUE TITLE
[CAL-4769] currently cant have overlapping OOO

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17772]
ijright now in [https://ooo.new](https://ooo.new) its a strict requirement that OOO cannot overlap. it throws an error

however, i think we should allow it

for example, if i go OOO 1 to 12 for "travel", i should still afterwards be able to go OOO on the 6th for "vacation"

the last entry will always overwrite, in this example it would show the travel emoji from 1-5 and 6 would be the vacation emoji and 7-12th would be travel again

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4769](https://linear.app/calcom/issue/CAL-4769/currently-cant-have-overlapping-ooo)</sub>

**Comment by itsalam** [comment]
@PeerRich shouldn't this be fixed by https://github.com/calcom/cal.com/issues/17368?
