### ISSUE TITLE
[CAL-4773] Availability: `copy times to` giving issues on prod

### ISSUE THREAD

**Issue by SomayChauhan** [calcom/cal.com#17793]
[https://www.loom.com/share/656bc1e5a431449b9df30006a30c59e9?sid=b8ecc2df-8a77-4b51-8f4d-d3d238a443f9](https://www.loom.com/share/656bc1e5a431449b9df30006a30c59e9?sid=b8ecc2df-8a77-4b51-8f4d-d3d238a443f9)

cancel and apply button also not working

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4773](https://linear.app/calcom/issue/CAL-4773/availability-copy-times-to-giving-issues-on-prod)</sub>

**Comment by ilyador** [comment]
Could not reproduce locally on `main` branch

**Comment by Praashh** [comment]
https://github.com/user-attachments/assets/f6b43214-6429-4fc8-ae01-9a0dda7e5541

working fine @SomayChauhan can you please check again?

**Comment by SomayChauhan** [comment]
Yes! Tested and it's working perfectly now.
