### ISSUE TITLE
bug: Hover effect missing on social media icons

### ISSUE THREAD

**Issue by Shreyagondole** [calcom/cal.com#17826]
### Issue Summary

The hover effect is not applied to navigation icons, making them appear static and non-interactive

### Steps to Reproduce

1. Go to the homepage.
2 . Hover over the navigation icons at the top.
3. Observe that no hover effect (e.g., color change or tooltip) is displayed.

### Actual Results

-Hovering over the icons does not trigger any visual feedback, such as a glow, tooltip, or color change

### Expected Results

- Hovering over the icons should display a hover effect (e.g., color change, scale, or tooltip) to indicate they are interactive

**Comment by askadityapandey** [comment]
LMAO! I wonder why people open such issues haha

**Comment by harshr029** [comment]
> LMAO! I wonder why people open such issues haha

Because everyone is not a pro, some are beginners and they want to learn by doing the stuff and for that they need to start from somewhere. The foundation of even the grandest building starts with a single brick.

**Comment by harshr029** [comment]
> LMAO! I wonder why people open such issues haha

Because some people are getting started with the open source and there's a thing called "good first issues", please let people learn things by doing the stuff and do not demotivate beginners. The foundation of even the tallest skyscrapers begins with a single brick.

**Comment by saketchaudhary94** [comment]
> > LMAO! I wonder why people open such issues haha
> 
> Because some people are getting started with the open source and there's a thing called "good first issues", please let people learn things by doing the stuff and do not demotivate beginners. The foundation of even the tallest skyscrapers begins with a single brick.

yes brother you are right , I am beginner and looking for good first issues .
