### ISSUE TITLE
[CAL-4789] Email to attendee when reassigning booking

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#17833]
When a booking is reassigned we currently don't send an email to attendees. We need to send an email to attendees with the updates because the meeting link and calendar event can change when the host changes. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4789](https://linear.app/calcom/issue/CAL-4789/email-to-attendee-when-reassigning-booking)</sub>

**Comment by PRANJALRANA11** [comment]
hey @CarinaWolli i tried to reproduce this issue but it seems like the attendee is getting the recheduling mail 
![image](https://github.com/user-attachments/assets/5461f881-dc06-49e9-a610-6107a705f855)
