### ISSUE TITLE
[CAL-4797] Removing user from teams doesn't remove them from round-robin Host table

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#17847]
### Issue Summary

This causes problems where the user can still be booked via round-robin selections when the "Assign all members" option is selected.

### Actual Results

* A Host record for the removed user stays around

### Expected Results

* The `Host` record is deleted and the user can not be booked as part of the round-robin event anymore

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4797](https://linear.app/calcom/issue/CAL-4797/[cal-4798]-removing-user-from-teams-doesnt-remove-them-from-round)</sub>

**Comment by ilyador** [comment]
Unable to reproduce. I used enterprise account.
Created RR meet for team 1.
Added users 2, 4, and 6 to host.
Removed user 2 from the team.
Now it's also gone from hosts.

<img width="854" alt="Screenshot 2024-11-26 at 14 57 24" src="https://github.com/user-attachments/assets/7fd51a54-e01f-4363-ab2c-a023b35fb590">

**Comment by Udit-takkar** [comment]
@ilyador the issue mentioned that Assign all members option is selected which is "Add all team members, including future memberships"

**Comment by keithwillcode** [comment]
Note that https://github.com/calcom/cal.com/pull/17369 is open which is somewhat related/similar to this bug. Perhaps we build on top of that to fix this.
