### ISSUE TITLE
[CAL-4813] show attributes in profile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17884]
we already show the attributes in the "edit overlay":

![CleanShot 2024-11-27 at 16 34 18@2x](https://github.com/user-attachments/assets/1b2b36c4-885e-4c8f-8b4e-1be6392bf170)

we should show it in the profile view too:

https://app.cal.com/settings/my-account/profile

![CleanShot 2024-11-27 at 16 33 25@2x](https://github.com/user-attachments/assets/25f597ce-85c9-4dea-84df-4052abf35fcb)

<sub>[CAL-4813](https://linear.app/calcom/issue/CAL-4813/show-attributes-in-profile)</sub>

**Comment by Yash-sudo-web** [comment]
@PeerRich @Praashh , is there any discord community for discussion regarding these issues?
