### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Ed-Svystun** [calcom/cal.com#17888]
Path: /self-hosting/apps/install-apps/google

Repopulate the App store by running: – WHAT?

**Comment by PeerRich** [comment]
https://cal.com/docs/self-hosting/apps/install-apps/google#adding-google-calendar-to-cal-com-app-store

![CleanShot 2024-11-29 at 19 20 32@2x](https://github.com/user-attachments/assets/63448fdd-aecc-43b5-8f16-18364942f7f5)

**Comment by PeerRich** [comment]
@alishaz-polymath can you check this?

**Comment by PeerRich** [comment]
should merge in a bit 🙏

**Comment by Ed-Svystun** [comment]
Thank you so much!
