### ISSUE TITLE
[CAL-4818] find out why "installing roam" took so long and fix it

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17900]
![CleanShot 2024-11-28 at 20 12 53@2x](https://github.com/user-attachments/assets/d6354747-5e75-46eb-9fa6-eda96b00d1ef)

<sub>[CAL-4818](https://linear.app/calcom/issue/CAL-4818/find-out-why-installing-roam-took-so-long-and-fix-it)</sub>

**Comment by PeerRich** [comment]
whoever takes this, please check other conferencing apps too

**Comment by itsalam** [comment]
It seems to affect all the button components that the "getting started" pages use. There doesn't seem to be any query invalidation/updating after the app is installed and is not redirected, and the `loading` prop is not properly wired.
