### ISSUE TITLE
[CAL-4825] Workflows are not getting executed (both Email and specially Text message workflows)

### ISSUE THREAD

**Issue by prashantxtim** [calcom/cal.com#17928]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The workflows are not working at all! The initial email works, but no other emails do. And for text message workflows, no text workflows work AT ALL! And yes, I know the event should be booked for at least 1 hour for this to execute. I have made sure there's enough time for the meeting. And yes, I am on the team plan as well.

This is extremely frustrating and is making me consider going back to Calendly, as I never had this major issue with them. If the workflows do not work, I close no clients. It's a massive bug that needs fixing and fast!

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

The booker is receiving the email confirmation and the first email from my sequence. But no other workflows are being executed.

### Expected Results

All my bookers should receive automated text and email reminders.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- I spoke about this with Milos from the support team and shared my screen to explain this, and he also thinks this is a bug as he himself tried booking a call, and the workflows simply did not execute.

<sub>[CAL-4825](https://linear.app/calcom/issue/CAL-4825/workflows-are-not-getting-executed-both-email-and-specially-text)</sub>

**Comment by iveaves** [comment]
We're having the same issue here, no "Before event starts" trigger workflows work (for email or SMS). I found that both email and SMS worked for "When new event is booked", so seems to be an issue on the scheduled workflows..

**Comment by prashantxtim** [comment]
Unfortunately, I ended up switching back to Calendly (at least temporarily) because of other multiple issues I faced. Would love to revisit Cal.com sometime in the future, but right now, the product has bugs that need fixing and fast. I love the UI and aesthetics but they don't really matter as much if the rest of the product has small broken parts.

**Comment by zomars** [comment]
@prashantxtim just being extra careful here. Are we talking about our hosted version? Or are you trying to make this work on a self-hosted version? If it the former can you open a ticker with [our customer support](https://go.cal.com/support)?

**Comment by CarinaWolli** [comment]
> We're having the same issue here, no "Before event starts" trigger workflows work (for email or SMS). I found that both email and SMS worked for "When new event is booked", so seems to be an issue on the scheduled workflows..

@iveaves Did you make sure you had at least 1 hour between when the booking happened and when the reminder was scheduled for?

**Comment by iveaves** [comment]
@CarinaWolli Yes

**Comment by zomars** [comment]
We found the issue. This was introduced in #18077 will revert back until we find a proper fix.
