### ISSUE TITLE
[CAL-4823] metadata and og image is broken

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#17931]
for team events:

https://www.opengraph.xyz/url/https%3A%2F%2Fi.cal.com%2Fsales%2Fexploration%3Fmonth%3D2024-12%26date%3D2024-12-02

broken og image URL: https://cal.com/_next/image?w=1200&q=100&url=%2Fapi%2Fsocial%2Fog%2Fimage?type=meeting&title=&meetingProfileName=

![image](https://github.com/user-attachments/assets/742b7747-e86a-42ca-93be-f3be6ee36f16)

--

for personal events:

og image for [i.cal.com/peer](http://i.cal.com/peer) since recently is broken too:

https://cal.com/_next/image?w=1200&q=100&url=%2Fapi%2Fsocial%2Fog%2Fimage?type=meeting&title=Meeting&meetingProfileName=Peer%20Richelsen&meetingImage=https%3A%2F%2Fcal.com%2Fapi%2Favatar%2Fc0e68239-b19e-4d30-b4f8-cf0b4b4cf457.png&names=Peer%20Richelsen&usernames=peer

see: 
https://www.opengraph.xyz/url/https%3A%2F%2Fi.cal.com%2Fpeer

<sub>[CAL-4823](https://linear.app/calcom/issue/CAL-4823/metadata-and-og-image-is-broken)</sub>

**Comment by PeerRich** [comment]
looks like bad gateway on cloudflare too cc @keithwillcode any ideas?
![image](https://github.com/user-attachments/assets/55d1f74b-c1af-4af8-8108-6af8313f5a0e)

**Comment by keithwillcode** [comment]
We already have fixes coming for this.

**Comment by mehul-m-prajapati** [comment]
@keithwillcode : I have debugged this yesterday for 3 hours and opened PR. Should I work on review changes or skip it?

**Comment by Praashh** [comment]
> @keithwillcode : I have debugged this yesterday for 3 hours and opened PR. Should I work on review changes or skip it?

Hey @mehul-m-prajapati fixed by https://github.com/calcom/cal.com/pull/17897 PR

**Comment by mehul-m-prajapati** [comment]
okay @Praashh , thanks for the update. I should be more aware on working issues which can be fixes by someone else next time,

**Comment by kamellperry** [comment]
> > @keithwillcode : I have debugged this yesterday for 3 hours and opened PR. Should I work on review changes or skip it?
> 
> Hey @mehul-m-prajapati fixed by #17897 PR

Does this PR fix the OG images not being generated in the self hosted docker version?

**Comment by Eghizio** [comment]
If this is closed & resolved I presume the **bounty should be removed** from the [page](https://cal.com/pl/jobs)?

**Comment by PeerRich** [comment]
yeah i dont know why the bounties dont update. will ask agora

**Comment by Eghizio** [comment]
@PeerRich yeah it seems that it's on Agora side as I've noticed similar behaviour on their website - bounties were still listed even after claiming.
