### ISSUE TITLE
Adding a dark theme on the home and other pages which are not in app or the docs. 

### ISSUE THREAD

**Issue by Gitstar-OC** [calcom/cal.com#17937]
### Is your proposal related to a problem?

I use dark theme most of the time and find out that there is no dark theme for the main website (website marketing). I believe it's better to have a dark theme with the same great UI.

### Describe the solution you'd like
I am happy to work on adding dark and light theme to the home / pricing / navbar links and enterprice page. It will look the same but the user will get the theme based on their preferences 

(Describe your proposed solution here.)

### Describe alternatives you've considered
N / A

### Additional context

N / A 

### Requirement/Document

https://github.com/user-attachments/assets/38dadfe1-edbe-459d-afb8-cee5f5fa6fcf

Just a small vidoe on how it will look but better :) 

##### House rules

- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by PeerRich** [comment]
not planned for now, thanks tho 🙏
