### ISSUE TITLE
[CAL-4843] Prevent rescheduling past events

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#17977]
When clicking on ‘reschedule‘ for past bookings it should redirect to the normal booking link and the original event won’t get canceled. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4843](https://linear.app/calcom/issue/CAL-4843/prevent-rescheduling-past-events)</sub>

**Comment by rizqyhi** [comment]
Hi @CarinaWolli would you mind sharing the reason behind this issue? We're currently utilizing this past event rescheduling feature and just found out that the feature is gone.

**Comment by CarinaWolli** [comment]
Hey @rizqyhi, we had complaints from customers that their attendee's rescheduled past events which caused issues because then then they avoid their official booking flow and they have missing context 

So we came to the conclusion: You can’t “reschedule something out of the past” really. its not how the world works.

@rizqyhi Can I ask about your use case why rescheduling past events is necessary and why creating a new booking instead won't work for you?

**Comment by angus0817** [comment]
Hey @CarinaWolli, we are using this feature as well and I have explained our use case in this [comment here](https://github.com/calcom/cal.com/pull/18003#issuecomment-2553132108).

Basically, reschedules don't always happen before a meeting occurs. Many times people forget or want to make changes at the very last minute. By disabling the option to reschedule past meetings, we end up having to schedule a brand new meeting with our clients, which means manually filling out the booking form again on their behalf and we also lose the original tracking UTM parameteres of the initial booking.

**Comment by CarinaWolli** [comment]
@angus0817 I understand. I’ve forwarded this to the team, and we’ll discuss it internally. I’ll update you once we’ve made a decision 🙏

**Comment by CarinaWolli** [comment]
The team agreed we want to add a new setting for this: https://github.com/calcom/cal.com/issues/18356

**Comment by angus0817** [comment]
@CarinaWolli Thank you, that's great to hear. Look forward to having the feature back again

**Comment by rizqyhi** [comment]
Hi @CarinaWolli sorry for the late reply. We got similar use case with @angus0817 and the new setting would be great. Thank you and we'll look forward to it.
