### ISSUE TITLE
When user is "Away", Booking Page shows no information on why the Event Types aren't available for booking

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#1801]
### Issue Summary

When a user set himself as  "Away" in profile, the booking Page is empty. It shows no information on why the Event Types aren't available for booking.

**This is how the booking page looks.**
<img width="1774" alt="Screenshot 2022-02-11 at 10 26 57 AM" src="https://user-images.githubusercontent.com/1780212/153539722-d9dd64d0-3487-4efd-9d7f-3a466117d586.png">

### Steps to Reproduce

1. Go to https://app.cal.com/event-types
2. Using bottom left User Dropdown, click "Set yourself as away."
3. Make sure that you have at least 1 Event Type created.
4. Go to your booking page https://cal.com/USERNAME
5. Notice that only your Avatar and details are there but no Event Types are visible which is okay. But, the person booking is not informed about it. It gives an impression that something is broken.

As a user
- I would expect all Event Types to be available but booking them should show info that the Event can't be booked as the user is away. 
- A prominent text should also be shown below the user details that the user is currently away

**Comment by ankitsridhar16** [comment]
Looking into it 👀
