### ISSUE TITLE
[CAL-4858] Paid Bookings: Use "Payment Element" instead of custom UI

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#18049]
lets use: https://docs.stripe.com/payments/payment-element

for:

![image](https://github.com/user-attachments/assets/c8b815c1-ee41-4ffc-898d-08cb105f751a)

so we can enable all possible stripe connect payment methods:

![CleanShot 2024-12-06 at 21 53 08@2x](https://github.com/user-attachments/assets/797299ca-e098-48d7-b355-f5f65170a44c)

<sub>[CAL-4858](https://linear.app/calcom/issue/CAL-4858/paid-bookings-use-payment-element-instead-of-custom-ui)</sub>

**Comment by mehul-m-prajapati** [comment]
Hi @PeerRich ,

I have enabled oauth on stripe and updated all env variables for the stripe in `.env` & `.env.appStore`
```
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_xxx
STRIPE_PRIVATE_KEY=sk_xxx
STRIPE_WEBHOOK_SECRET=whsec_xxx
STRIPE_CLIENT_ID=ca_xxx
PAYMENT_FEE_FIXED=10           # Take 10 additional cents commission
PAYMENT_FEE_PERCENTAGE=0.005   # Take 0.5% commission
```
I am getting the following error when installing Stripe app on my profile. Can you please help me with this?

![d1](https://github.com/user-attachments/assets/c99f22e5-240d-4960-987d-06208a9fa36e)

**Comment by rajesh-jonnalagadda** [comment]
> Hi @PeerRich ,
> 
> I have enabled oauth on stripe and updated all env variables for the stripe in `.env` & `.env.appStore`
> 
> ```
> NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_xxx
> STRIPE_PRIVATE_KEY=sk_xxx
> STRIPE_WEBHOOK_SECRET=whsec_xxx
> STRIPE_CLIENT_ID=ca_xxx
> PAYMENT_FEE_FIXED=10           # Take 10 additional cents commission
> PAYMENT_FEE_PERCENTAGE=0.005   # Take 0.5% commission
> ```
> 
> I am getting the following error when installing Stripe app on my profile. Can you please help me with this?
> 
> ![d1](https://private-user-images.githubusercontent.com/7879392/393467667-c99f22e5-240d-4960-987d-06208a9fa36e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDU2NDQsIm5iZiI6MTczMzU0NTM0NCwicGF0aCI6Ii83ODc5MzkyLzM5MzQ2NzY2Ny1jOTlmMjJlNS0yNDBkLTQ5NjAtOTg3ZC0wNjIwOGE5ZmEzNmUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMDQyMjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJjM2RjMDMwNDdlNzQzNmFlOGM3MDVmMWU0Yjk2ZWFhM2FhMDJiNzkyM2MzZDdhYTY5NjVjNjFjMjVlYjU0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qA4SpN1G8_LCfN8pnT9HGNqxIJX0fRE-KE0JK6If4iw)

Try hardcoding in the path below and run the yarn seed-app-store packages/Prisma folder.
packages/prisma/seed-app-store.ts

**Comment by itsalam** [comment]
@PeerRich,

Based on the [current configuration here](https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L269), we hold onto the cards regardless of payment type, which seems to conflict with the "pay on booking" description, but maybe this is for a reason beyond what I'm seeing. 

Regardless, due to this, there are hardly any options besides using a card even if we enable the option for multiple types of payment.

**Comment by rajesh-jonnalagadda** [comment]
> @PeerRich,
> 
> Based on the [current configuration here](https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L269), we hold onto the cards regardless of payment type, which seems to conflict with the "pay on booking" description, but maybe this is for a reason beyond what I'm seeing.
> 
> Regardless, due to this, there are hardly any options besides using a card even if we enable the option for multiple types of payment.
@itsalam 
Can we discuss this over discord? may we can work together. I have some blockers to test fully. I could use your help

**Comment by rajesh-jonnalagadda** [comment]
> @PeerRich,
> 
> Based on the [current configuration here](https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L269), we hold onto the cards regardless of payment type, which seems to conflict with the "pay on booking" description, but maybe this is for a reason beyond what I'm seeing.
> 
> Regardless, due to this, there are hardly any options besides using a card even if we enable the option for multiple types of payment.

@itsalam are you able to view other payment options in your local?

**Comment by itsalam** [comment]
@rajesh-jonnalagadda finally got it, you need to config the stripe account pretty heavily to view the options I'll post my fix
