### ISSUE TITLE
[CAL-4071] Booking questions apear in wrong order in confirmation email

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#18093]
Booking questions appear in the wrong order in the confirmation email.

the order that we set in the event type settings when the meeting is booked appears in a different order.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ee37e253-1ca6-4501-a9f2-aea8b6830340/f01d81ba-7341-44a2-bd77-1bd0dfc48e46?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9lZTM3ZTI1My0xY2E2LTQ1MDEtYTlmMi1hZWE4YjY4MzAzNDAvZjAxZDgxYmEtNzM0MS00NGEyLWJkNzctMWJkMGRmYzQ4ZTQ2IiwiaWF0IjoxNzMzODU4OTg1LCJleHAiOjE3NjUzOTQ5ODV9.5ciEBxso0zcxZMYjq28okFSiLUirGfNKWWtIi1sZC-w)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c44187b6-f9c6-4948-b705-a44eedb70fc1/2ca9ce34-1357-4c18-b790-99dc650cade0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jNDQxODdiNi1mOWM2LTQ5NDgtYjcwNS1hNDRlZWRiNzBmYzEvMmNhOWNlMzQtMTM1Ny00YzE4LWI3OTAtOTlkYzY1MGNhZGUwIiwiaWF0IjoxNzMzODU4OTg1LCJleHAiOjE3NjUzOTQ5ODV9.-GOmJsuSqsFe4tO3KiQ0xqxLpOJSRyCoFMOsz1GM47c)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4071](https://linear.app/calcom/issue/CAL-4071/booking-questions-apear-in-wrong-order-in-confirmation-email)</sub>

**Comment by Chetan0000** [comment]
Hey @joseuo94 I would like to work on this issue, can you please assign it to me

**Comment by VenkataRohan** [comment]
Hi @joseuo94 @emrysal , I have fixed this issue and raised a PR. Please review and let know me if anything is required.
