### ISSUE TITLE
create account with google creates empty user

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1809]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/8019099/153595240-907aef81-40a9-4846-b949-39c7b67e8672.png">

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/8019099/153595201-6d065a33-7146-4b4a-beff-87d90f1f0191.png">

i also can't find the "sign in with google" anymore on our app.cal.com auth page:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/8019099/153595334-d385074e-671c-4f2a-bacf-06ee24274558.png">

i swear it used to be there (missing .env since turbo repo maybe?)

**Comment by deepakprabhakara** [comment]
Google login needs to be enabled in the app, seems to have got disabled somehow.

**Comment by PeerRich** [comment]
> Google login needs to be enabled in the app, seems to have got disabled somehow.

i think it was caused by turbo repo migration. fixed now. closing
