### ISSUE TITLE
BUG in chatbot button

### ISSUE THREAD

**Issue by sanjeevkansyakar** [calcom/cal.com#18112]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The chatbot button randomly disappears and reappears, on click making it difficult for users to ask questions. This inconsistency negatively impacts the user experience as the primary method of interaction becomes unreliable.

### Steps to Reproduce

1. Go to the Home page.
2. Observe that the chatbot button vanishes on click, then reappears unpredictably.

### Actual Results

- The chatbot button intermittently disappears without user intervention, making it impossible to interact with the chatbot during those times.

### Expected Results

- The chatbot button should always remain visible and functional throughout the session unless explicitly hidden by the user or during navigation.

### Evidence

https://github.com/user-attachments/assets/1c7c2d6f-fda8-48f8-b048-96e77dd135cc

**Comment by AliyanA1** [comment]
hey!
I’m currently working on resolving the issue where the chatbot button intermittently disappears. I’m investigating the visibility and positioning of the button and will keep you updated with any progress. Please let me know if you have any additional insights or suggestions!

**Comment by amul69906995** [comment]
like i am not seeing any chat button in home page??

https://github.com/user-attachments/assets/b109b8d2-01df-48f7-be89-52382263cd93

**Comment by sanjeevkansyakar** [comment]
I think they are working on this, thats why they removed for now

**Comment by sanjeevkansyakar** [comment]
I think they are working on this, thats why they removed for now

**Comment by Praashh** [comment]
yes team is working on it.

**Comment by Praashh** [comment]
closing it for now, since there were no issue found in the chat button 🙏
