### ISSUE TITLE
Enable availability inputs to respond to typing

### ISSUE THREAD

**Issue by marcoscannabrava** [calcom/cal.com#1813]
### Issue Summary

Availability inputs don't respond to typing, only to selecting with the mouse via the dropdown.

### Steps to Reproduce

1. open availability page
2. try to change availability with keyboard without using the mouse

### Technical details

- Browser version: Chrome 98
- Node.js version: Cal.com's

**Comment by milospuac** [comment]
Hi there! Thanks for the suggestion. Our dev team will have a look at your request.

**Comment by PeerRich** [comment]
hey, can you try the latest version?
