### ISSUE TITLE
[CAL-4911] not checking google permissions throws an ugly error page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#18221]
submitting: 

![CleanShot 2024-12-16 at 21 14 41@2x](https://github.com/user-attachments/assets/554e330a-8cb9-4cde-af1a-e3063719222d)

shows:

![CleanShot 2024-12-16 at 21 14 49@2x](https://github.com/user-attachments/assets/8537d664-06a2-4a00-98e9-df57a455eb40)

instead we should throw 
`<EmptyScreen> `

with a call to action button to "Go Back"

<sub>[CAL-4911](https://linear.app/calcom/issue/CAL-4911/not-checking-google-permissions-throws-an-ugly-error-page)</sub>

**Comment by VK-RED** [comment]
[Screencast from 2024-12-17 08-13-39.webm](https://github.com/user-attachments/assets/06b50149-73f4-4280-9795-659ae08cc2c0)

Tried this in Prod and local, seems to be working fine ..

**Comment by Praashh** [comment]
I think fixed here #18228
