### ISSUE TITLE
[CAL-4913] Fix Optimistic UI when bulk assigning attributes to users

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#18230]
This worked when we initially made the PR but it doesnt seem to work anymore. We should fix this

![CleanShot 2024-12-17 at 10.10.49.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0c99b67c-6045-46ce-ab80-8059cee99f1f/f7323af0-3f9c-4307-8385-d7fa4cdf8e78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wYzk5YjY3Yy02MDQ1LTQ2Y2UtYWI4MC04MDU5Y2VlOTlmMWYvZjczMjNhZjAtM2Y5Yy00MzA3LTgzODUtZDdmYTRjZGY4ZTc4IiwiaWF0IjoxNzM0NDMwMjYwLCJleHAiOjE3NjU5NjYyNjB9.arkaFjNnu7Fs4-bMZbfzp-jd9Pn8d-wWU5nvtWwv5kw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4913](https://linear.app/calcom/issue/CAL-4913/fix-optimistic-ui-when-bulk-assigning-attributes-to-users)</sub>

**Comment by Praashh** [comment]
fixed by #18231 , closing it 🙏
