### ISSUE TITLE
[CAL-4924] Reschedule email shows wrong timezone

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#18248]
The reschedule email for the attendee shows the organizer's timezone instead of their set timezone on the booking page

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4924](https://linear.app/calcom/issue/CAL-4924/reschedule-email-shows-wrong-timezone)</sub>

**Comment by kart1ka** [comment]
Hi @CarinaWolli I am unable to produce the bug on the main branch. I booked a meeting with the booker timezone being America/New_York and the organizer's timezone being IST. The organizer then rescheduled the meeting. The rescheduled email sent to the booker was in New York timezone. Please see the video below:


https://github.com/user-attachments/assets/0aa5e9fa-366d-4953-bea1-b3a6e978de30
