### ISSUE TITLE
Password validation allows 7 characters, but the minimum requirement is 8 characters

### ISSUE THREAD

**Issue by Carlos-kadu** [calcom/cal.com#18250]
### Issue Summary

The password validation allows a minimum of 7 characters, despite the requirement being 8 characters. This discrepancy leads to inconsistent behavior between the documented and actual system validation.

### Steps to Reproduce

1. Go to the user registration page.
2. Enter a password with 7 characters.
3. Submit the registration form.
4. Alternatively, try to change your password to one with 7 characters and submit the change.

### Actual Results

The system accepts passwords with 7 characters, which violates the documented minimum length of 8 characters.

### Expected Results

The system should reject passwords that are shorter than 8 characters and display a validation error message.

### Technical details

- Browser version: Mozilla Firefox 133.0.3 (x64 pt-BR)

### Evidence

This issue was identified through black-box testing, specifically using boundary value analysis. The test involved providing a password with 7 characters to check if the system correctly enforces the minimum length of 8 characters. 

Submitting a form with a 6-character password
![image](https://github.com/user-attachments/assets/234c5788-a2a0-4ad3-b117-8d984b813e76)
![image](https://github.com/user-attachments/assets/b11d627f-f8a6-47cb-b62a-647f4b0b8573)

Submitting a form with a 7-character password
![image](https://github.com/user-attachments/assets/c1ada37e-e68f-4d0b-8d40-6c80586ba922)
![image](https://github.com/user-attachments/assets/bebd265b-f262-4d1f-a561-4dc52584bd4d)

**Comment by retrogtx** [comment]
damn now that's some bug

**Comment by retrogtx** [comment]
![image](https://github.com/user-attachments/assets/c49d16a6-14f3-4e60-8702-94a561165cb2)
upon trying to sign up, it asks for a minimum of seven characters

![image](https://github.com/user-attachments/assets/0b805cef-5572-420b-b572-6b6b2b024f2d)
same on the password reset page

can you please tell me on which page did you get the "minimum of eight characters" in a password reset form?

**Comment by Durgesh-05** [comment]
Yes, I've checked also on firefox browser but there is no text of 8 character password

**Comment by retrogtx** [comment]
so where is this occurring?

**Comment by Durgesh-05** [comment]
we have to validate from codebase that they are accepting 7 or 8 character password

**Comment by retrogtx** [comment]
> we have to validate from codebase that they are accepting 7 or 8 character password

I did a simple search for "eight", but nothing popped up related to password in the codebase

**Comment by Carlos-kadu** [comment]
I believe this might be a translation error in the Portuguese (pt-BR) version. The screenshots have been translated into English. In Portuguese, the minimum is displayed as eight characters on the registration page (I wasn't able to access the registration page in English).
![image](https://github.com/user-attachments/assets/9e02ba17-1fec-4458-b2d6-2ad5a27e831e)

**Comment by retrogtx** [comment]
oh wow interesting

**Comment by retrogtx** [comment]
could you please verify this?

Mínimo de sete caracteres <= Minimum seven characters

I used google translate for this. 

I believe the solution is to simply update the [apps/web/public/static/locales/pt-BR/common.json](https://github.com/calcom/cal.com/blob/a622c7b624c0802268081dd54b3b101028b1a156/apps/web/public/static/locales/pt-BR/common.json#L2).

**Comment by Carlos-kadu** [comment]
I verified the change. "Mínimo de sete caracteres" is correct.
