### ISSUE TITLE
stop sending "waiting for approval" email for opt-in bookings off the past

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1829]
### Issue Summary

when you forgot to accept or reject an opt-in booking, you still get 3 email reminders, even tho the date has already passed.

### Steps to Reproduce

1. make an event type with opt-in bookings
2. book it
3. wait for it to pass

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by jamiepine** [comment]
I might take this one, it bothers me too

**Comment by PeerRich** [comment]
fixed
