### ISSUE TITLE
 Portfolio "I want to change header portion theme".

### ISSUE THREAD

**Issue by RavishankarMahto** [calcom/cal.com#18316]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. when i open the portfolio then header portion not visible.

### Steps to Reproduce

1. Change the theme
2. UI theme based on JavaScript.
3. Convert into visible UI.

### Expected Results

- Should be fix this issue.

### Technical details

- [link]- https://ravishankarmahto.github.io/My-Portfolio/
- Screenshot:- 
![{76064B89-9D7A-4570-BF58-2710C9768986}](https://github.com/user-attachments/assets/8e878299-9157-4866-acf1-43e9bfd9230f)

### Evidence

- above mentioned the link and problem screenshot.

**Comment by Sreeman45** [comment]
![Screenshot 2024-12-21 193811](https://github.com/user-attachments/assets/5da5999d-7af5-40cf-aa06-7b8a18336175)
is this what u want

**Comment by Praashh** [comment]
not related to cal, closing it for now.
