### ISSUE TITLE
API endpoint for timezone change

### ISSUE THREAD

**Issue by ronissim** [calcom/cal.com#18347]
### Is your proposal related to a problem?

I want to automate the changing in my availability while traveling.
Ideally: not allow f2f meetings when I'm not at the office and change my working hours based off of timezone changes

### Describe the solution you'd like

an API endpoint for "schedule timezone change'
an API endpoint for changing meeting location availability for certain date ranges (or have the schedule timezone change affect that)

### Describe alternatives you've considered

using the undocumented api :(

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

---

##### House rules

- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.
  - Follow Best Practices lined out in our [Contributor Docs](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)

**Comment by Praashh** [comment]
@ronissim closing it
