### ISSUE TITLE
Option to hide the meeting link from site, or not have it shown at all

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#1836]
Customer wants the meeting link only shown in the confirmation email and not on site:

<img width="768" alt="(Screenshot) Brave Browser - Confirm your PATH Virtual Meeting with Adam Callaway  Cal com (2022  02  11)" src="https://user-images.githubusercontent.com/97884287/153829651-df6e0134-0a3d-4102-a120-1099658bfed3.png">
 
Would be great if we can build an option to hide the meeting link from this page. Or maybe not have it shown at all, I think the confirmation email is enough.

**Comment by Jenietoc** [comment]
I cannot reproduce the issue, the link to be hidden does not appear.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/89233604/153896161-e79aaa59-bcfd-4ce4-b9c6-e54422bd14f2.png">

**Comment by PeerRich** [comment]
hiding external URLs now: https://github.com/calcom/cal.com/pull/1844 it's a good idea to hide it before booking for privacy reasons

**Comment by PeerRich** [comment]
> I cannot reproduce the issue, the link to be hidden does not appear. <img alt="image" width="557" src="https://user-images.githubusercontent.com/89233604/153896161-e79aaa59-bcfd-4ce4-b9c6-e54422bd14f2.png">

i realised it's only for in-person/URL events
