### ISSUE TITLE
[BUG]: Email can be capitalized in the "Sign up with email" button in homepage

### ISSUE THREAD

**Issue by TanCodeX** [calcom/cal.com#18364]
**Describe the bug**
The "Sign up with email" button on the homepage should have the "E" in "email" capitalized for consistency and professionalism.

**To Reproduce**
Steps to reproduce the behavior :
1. Go to Home Page
2. Locate the Button that says Sign up with email

**Expected behavior**
The button on the homepage should display as "Sign up with Email" with the "E" in "Email" capitalized.

**Screenshots**

![image](https://github.com/user-attachments/assets/330a32a2-2fc5-4cb0-9053-bf0e788cba82)

**Comment by devTejaSrinivas** [comment]
Would it be good if we add a small generic email icon in the button just like how there is a google icon in sing up with google button  ??

**Comment by FurquanAnwer** [comment]
Please assign me this !

**Comment by TanCodeX** [comment]
> Would it be good if we add a small generic email icon in the button just like how there is a google icon in sing up with google button ??
@devTejaSrinivas Yes, adding an email icon to the button is a great idea for better recognition.

**Comment by TanCodeX** [comment]
> Please assign me this !
@FurquanAnwer Don't wait to get assigned, just fix it and make a PR.

**Comment by devTejaSrinivas** [comment]
@TanCodeX  OK sure

**Comment by devTejaSrinivas** [comment]
@TanCodeX Can you help me ? Which is the file that renders the homepage . My development setup took so long and now I am unable to locate the exact file .

**Comment by AliyanA1** [comment]
I've spent more than an hour trying to locate the exact file, but unfortunately, I couldn't find it. If anyone manages to locate it, please let me know. Thank you!

**Comment by devTejaSrinivas** [comment]
@AliyanA1 Yeah I have spent more than 3 hours from yesterday to find , used all possible ways from searching to copilot . NOT FINDING THE FILE

**Comment by retrogtx** [comment]
The landing page is not open source, guys

**Comment by Praashh** [comment]
@TanCodeX , The website isn't public.

Thank you for creating the issue. We'll fix it soon 🙏
