### ISSUE TITLE
Prisma commands don't work

### ISSUE THREAD

**Issue by miguelnietoa** [calcom/cal.com#1839]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Prisma commands don't work due to the project reorganization.

#### Running the Prisma commands found in the README.md file.
- ❌ `npx prisma studio`
![image](https://user-images.githubusercontent.com/39246879/153887677-44598202-c1a1-4252-8c2e-0c4a143d1207.png)

- ❌ `npx prisma migrate deploy`
![image](https://user-images.githubusercontent.com/39246879/153887677-44598202-c1a1-4252-8c2e-0c4a143d1207.png)

- ❌ `npx prisma migrate dev`
![image](https://user-images.githubusercontent.com/39246879/153887677-44598202-c1a1-4252-8c2e-0c4a143d1207.png)

#### Running with `--schema=apps/web/prisma/schema.prisma`
- ✅ `npx prisma studio --schema=apps/web/prisma/schema.prisma`
![image](https://user-images.githubusercontent.com/39246879/153888772-9cb80758-6059-4f86-9628-3688165de257.png)

- ❌ `npx prisma migrate deploy --schema=apps/web/prisma/schema.prisma`
![image](https://user-images.githubusercontent.com/39246879/153889022-8078b599-195c-4351-9ff4-c29a72074b1c.png)

- ❌ `npx prisma migrate dev --schema=apps/web/prisma/schema.prisma`
![image](https://user-images.githubusercontent.com/39246879/153889022-8078b599-195c-4351-9ff4-c29a72074b1c.png)

**Note that even when running the command specifying the schema file it does not load the `.env` file inside the `apps/web` folder.**

### Technical details
- Node.js version: `14.17.6`

**Comment by miguelnietoa** [comment]
Hi @milospuac, I found a way to fix those commands! 
But I have a question: To make a change to documentation is directly on `apps/docs/` or in https://github.com/calcom/docs?

**Comment by milospuac** [comment]
https://github.com/calcom/docs

**Comment by miguelnietoa** [comment]
This can be fixed in #1843
