### ISSUE TITLE
iCal Support

### ISSUE THREAD

**Issue by samtuke** [calcom/cal.com#1846]
Hey we use Harmonizely integrated with Nextcloud via iCal. If you support iCal you support lots of calendaring tools 😎  Harmonizely seems to have been sold and their service is deteriorating. We're looking for another solution which supports iCal as well.

**Comment by milospuac** [comment]
Yes, we do support iCal, although we are working at the moment on some issues with CalDav integrations. Should be fixed soon :)

**Comment by samtuke** [comment]
@milospuac Great to hear that - is there a ticket I can track for fully supported caldav?

**Comment by PeerRich** [comment]
What's missing for CalDav? Can you join our slack? https://cal.com/slack and join `#caldav` to help us debug
