### ISSUE TITLE
Allow using self-hosted Jitsi

### ISSUE THREAD

**Issue by ianhyzy** [calcom/cal.com#1847]
### Is your proposal related to a problem?

Currently, you can only use Jiti (https://meet.jit.si/) servers with Jitsi meetings.

### Describe the solution you'd like

I'd like the option to hosting meetings on my own Jitsi server on my own domain.

### Additional context
Jisti is the largest (only?) FOSS video calling solution, and it would be a great complement to the only FOSS scheduling solution.

**Comment by milospuac** [comment]
Thanks for the suggestion. We added Jitsi just recently into our integrations and this could be something to implement in the near future.

**Comment by saschafoerster** [comment]
As a workaround: aI manually change it in this file. When updating you have to a "git stash" and "git stash pop" like this to keep it working: 
```
git pull
git stash
git checkout V1.5
git stash pop
```

](https://github.com/calcom/cal.com/blob/f536d1040c2544fbfbdca3be0d27e499db81148a/packages/app-store/jitsivideo/lib/VideoApiAdapter.ts#L17)

I am also looking forward to use any selfhosted Jitsi installation. Isn't selfhosting the main reason, why we are using cal.com? :)

**Comment by saschafoerster** [comment]
@philippdormann I saw that you developed the Jitsi integration, which is really great. Maybe as a little easter-gift, it would be really nice, if you have time, to add a variable field, which allows to use selfhosted-jitsi-installations as well! I am just able to change existing code in small amounts, but not really able to add this feature.

**Comment by agustif** [comment]
Hey added new env var:
`JITSI_INSTANCE_URL`
When #2590 merges should be available.

Maybe in the future we could allow a setting from the user level, instead of the app level, to improve the jitsi app in the app-store with some configs, so each company using cal can use its own jitsi instance if desired (for privacy reasons whatsoever)

**Comment by saschafoerster** [comment]
@agustif I tried it out today with 1.6.2 but I guess with the move to .env.appStore the Jitsi-variables should also be moved. I am not really good in git stuff, but I try to help if I can, for instance with documentation.

**Comment by jdaviescoates** [comment]
> When #2590 merges should be available.

Just went to check the status of that and note it was closed (but that the feature is still not yet available)

**Comment by jdaviescoates** [comment]
Still hoping this is coming soon?

**Comment by PeerRich** [comment]
we'd rely on the community to build this. its not on our roadmap right now

**Comment by PeerRich** [comment]
you can achieve this by just using jitsu on your own server and then copying your room link as a "Link Event"

**Comment by jdaviescoates** [comment]
> we'd rely on the community to build this. its not on our roadmap right now

That's a shame :( 

It sounded like the #2590 PR request @agustif submitted was going to simply make the url configurable.

> you can achieve this by just using jitsu on your own server and then copying your room link as a "Link Event"

Thanks, but having to do that manually each time is a bit of a pain - would be **_so_** much better for the link to be auto-generated and added to the meeting.

PS it's jits**i** not jits**u** :)

**Comment by PeerRich** [comment]
> > we'd rely on the community to build this. its not on our roadmap right now
> 
> That's a shame :(
> 
> It sounded like the #2590 PR request @agustif submitted was going to simply make the url configurable.
> 
> > you can achieve this by just using jitsu on your own server and then copying your room link as a "Link Event"
> 
> Thanks, this is what I'm already doing, but having to do that manually each time is a bit of a pain - would be **_so_** much better for the link to be auto-generated and added to the meeting.
> 
> PS it's jits**i** not jits**u** :)

not sure why this was closed, @agustif? 🤔

**Comment by PeerRich** [comment]
do you have a static link or is it dynamic for each meeting?

**Comment by jdaviescoates** [comment]
I normally create a new link for each meeting. I guess I could experiment with using a static link too. I guess if I did that I may not need to paste it in each time?

**Comment by PeerRich** [comment]
if you have a static link, you can just put that into the "Link Meeting"

**Comment by chief-nerd** [comment]
In case you need a quick fix, until the PR is merged:

https://github.com/calcom/cal.com/pull/8636#issuecomment-1533723721
