### ISSUE TITLE
Date Widget Doesn't Work on Safari

### ISSUE THREAD

**Issue by frankgreco** [calcom/cal.com#1849]
### Issue Summary

https://user-images.githubusercontent.com/22604233/153989749-b1c42a7a-2588-48fe-9f7f-9a99a9ed5f28.mov

### Steps to Reproduce
Create a new event type with a custom date range.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
https://www.whatsmybrowser.org/b/1LKMS

**Comment by hariombalhara** [comment]
This is actually an issue on Safari. Works on Chrome. 
The bug exists in daterange-picker library. I have it replicable here https://codesandbox.io/s/react-daterange-picker-bug-with-radiogroup-from-radix-ui-on-safari-v9pji

I also filed an issue there https://github.com/wojtekmaj/react-daterange-picker/issues/114

**Comment by PeerRich** [comment]
hey, can you try the latest version?
