### ISSUE TITLE
Make Additional Inputs Available as Template Variables 

### ISSUE THREAD

**Issue by frankgreco** [calcom/cal.com#1861]
### Describe the solution you'd like

Currently, `{USER}` is the only template variable available for usage in the _Event Name_ field.

For example, considering a required input of _Location_, we could have, `Coffee with {USER} at {LOCATION}`.

**Comment by hariombalhara** [comment]
What other inputs do you see yourself using apart from Location?

**Comment by frankgreco** [comment]
Any that are custom defined. I think giving the ability for the user to use `{inputs.<name>}` is flexible. Hard coding what can and can't be used in the event name seems too strict.

**Comment by Colelyman** [comment]
I agree with @frankgreco to allow any that are custom defined. 

To give an example of my intended use case (which led me here), I am scheduling interviews for clients and I have a custom field `Company`. It would be great if I could have the event name be: `Interview with {USER} @ {inputs.Company}` (or something similar).

Thanks!

**Comment by PeerRich** [comment]
more variables added!
