### ISSUE TITLE
NIT: hide "additional notes" headline from email and calendar entry if empty

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1864]
email:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/8019099/154143504-81304a1b-2297-410f-9ffa-543c2753ce97.png">

calendar entry:
<img width="88" alt="image" src="https://user-images.githubusercontent.com/8019099/154143766-47b1a236-ffc7-406f-bd66-d794aad2d050.png">

**Comment by frankgreco** [comment]
I'd like to tackle this as a first issue :)

**Comment by PeerRich** [comment]
> I'd like to tackle this as a first issue :)

go for it!
