### ISSUE TITLE
Event Duration not Taken into Consideration When Offering Time Slots

### ISSUE THREAD

**Issue by frankgreco** [calcom/cal.com#1871]
### Issue Summary

Consider an event type with a _Duration_ of 60m and a _Time-slot Interval_ of 15m. This event type has a custom availability when ends at 11pm. The time slots that will be generated will go all the way until 10:45pm. If the duration were taken into account, the last slot would start at 10pm.

### Steps to Reproduce

Just follow the steps outlined in the previous section.

**Comment by milospuac** [comment]
Hi there,

Thanks for sharing this. Do you mind sending the screenshot of the custom availability of the event type?

**Comment by frankgreco** [comment]
These screenshots are for a different example than the one mentioned but here, the duration is 120m so I'd expect the last slot to be at 9pm. However, it's (internal time) before the end time.
<img width="699" alt="Screen Shot 2022-02-22 at 4 10 08 PM" src="https://user-images.githubusercontent.com/22604233/155241249-96232341-aea3-4461-ace6-f0fd209747ae.png">
<img width="599" alt="Screen Shot 2022-02-22 at 4 10 31 PM" src="https://user-images.githubusercontent.com/22604233/155241257-b869c7c4-c51b-4e95-962b-72a6d7ba341e.png">
