### ISSUE TITLE
Monthly limits to bookings

### ISSUE THREAD

**Issue by sydneyliu** [calcom/cal.com#1877]
### Is your proposal related to a problem?

Some events I don't want too many of on my calendar, especially ones on a monthly cadence

### Describe the solution you'd like

Monthly limits on an event. This event can only be booked 4x a month for example

### Describe alternatives you've considered

Calendly has daily limits, not monthly. Still looking at other options

### Additional context

Figma: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1526%3A76162

**Comment by milospuac** [comment]
Thanks for sharing this. Our team will put it into consideration.

**Comment by Jaibles** [comment]
@sean-brydon here are designs for this feature: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6096%3A100083

**Comment by PeerRich** [comment]
@sean-brydon assigned you since the previous DRAFT PR was closed due to inactivty

**Comment by PeerRich** [comment]
@sean-brydon let @zomars know if someone else should work on this

**Comment by PeerRich** [comment]
done in 2.2
