### ISSUE TITLE
auto-accept incoming calendar events

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1878]
right now you need a manual confirmation to attend a call when someone books you.

i initially thought it's a good idea but we should instead always auto-accept all incoming events from cal.com 

- [x] Google Calendar @emrysal 
- [ ] Outlook Calendar
- [ ] Apple Calendar
- [ ] CalDav Calendar

**Comment by PeerRich** [comment]
comment by @emrysal:

> add a new field to the Event Create - "attendees[].responseStatus" and set that to "accepted"

**Comment by PeerRich** [comment]
done!

**Comment by PeerRich** [comment]
@natelindev do you know if this is possible with CalDav?

**Comment by PeerRich** [comment]
closing until relevant again

**Comment by voyagermedical** [comment]
@PeerRich this would be an awesome feature, its what's stopping our firm from migrating from youcanbookme to cal.com. The big issue with not having this feature when plugged into Stripe means that we cannot do automatic telehealth services as we get a lot of bookings however as very little have confirmed in time very little of them get paid...

**Comment by PeerRich** [comment]
which calendar is missing for you?

**Comment by voyagermedical** [comment]
@PeerRich Sorry I dont udnerstand the question. I am using cal.com and have connected Stripe into this, you can see an instance of this on this page https://pharmacistmigration.com/contact-us/. I would like people to look at availability, book then pay and then this is sent into my calendar. At the moment people look for availability, book, payment is on hold, and a confirmation email is sent to me saying whether I would like to accept. This last stage is not applicable as I have already told the system that I am available on the specific times and dates. Other services get around this problem by getting me to input an "available for booking" slot in my calendar which the booking system liases with, it looks like this... <img width="591" alt="Screenshot 2022-11-07 at 10 15 00" src="https://user-images.githubusercontent.com/84501652/200200697-e68ec36b-521e-4124-a31f-b5d126b7da29.png">

**Comment by voyagermedical** [comment]
Im using iCal btw.
