### ISSUE TITLE
Images unable to load due to 502 gateway error

### ISSUE THREAD

**Issue by voyager163** [calcom/cal.com#1888]
### Issue Summary

After deploying the cal.com in azure cloud, the web portal random will not load the images (Attached Below).
 
![Screenshot 2022-02-17 at 5 42 27 PM](https://user-images.githubusercontent.com/4599055/154452696-ec48b0ab-c7c9-4f00-970e-529192eb5114.png)

### Steps to Reproduce

1. Go to the cal.com url
2. Login to the cal.com
3. Click on the Integration button
4. Images not load

* Sometime the images is loaded. However, sometime it is not loaded.

### Technical details

- I have utilised Azure Application Gateway and Azure Firewall.
- Node.js version -> 16.14.0

**Comment by milospuac** [comment]
Thanks for sharing this. Our engineering team will have a look

**Comment by gabamnml** [comment]
same happens when run `next build` and `next start`

**Comment by matheusmuniz03** [comment]
hi voyager, could you tell me more about this the Integration button? I'm not finding him in cal.com

**Comment by gabamnml** [comment]
I fix this issue. You need to add perms to write the cache folder of NextJS deploy in the server because the assets pipeline of NextJS are on-demand @voyager163
