### ISSUE TITLE
At Login:  500 | TypeError - The "data" argument must be of type ... Received undefined 

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#1907]
When I logged into the app using the `free@example.com` account I'm seeing this error through the server console.
The app, fortunately, runs "well" and it seems I'm able to authenticate myself with the server but I'm not sure if there are some hidden bad side effects because of this.

```
@calcom/web:dev: event - compiled client and server successfully in 352 ms (1395 modules)
@calcom/web:dev: error - TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
@calcom/web:dev: wait  - compiling /_error (client and server)...
@calcom/web:dev: event - compiled client and server successfully in 200 ms (1395 modules)
@calcom/web:dev: 05:22:00.276 timeZoneName DEBUG [error] server side logged this: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined 
@calcom/web:dev: 05:22:00.278 timeZoneName INFO  [error] return props,  
@calcom/web:dev: {
@calcom/web:dev:   statusCode: 500,
@calcom/web:dev:   hasGetInitialPropsRun: true
@calcom/web:dev: }
```

Bootstrapping with **DEBUG:*** (.env) gives you more information. 
I researched a little bit about this and I believe the root of this issue can be found in #1638. 
The avatar's fallback, while waiting for the user avatar, is fetching a non-existent resource at `localhost/undefined/avatar.png` which generates the error. This needs further research.
  
### Steps to Reproduce

- Login with test account free@example.com (psw: free) in development.
- Check the server console.

**Comment by milospuac** [comment]
Thanks for reporting this. Our team will have a look
