### ISSUE TITLE
Add line breaks, styling, and/or markdown to event description

### ISSUE THREAD

**Issue by kelseysmithdesign** [calcom/cal.com#1909]
### Is your proposal related to a problem?

I write a lot of text in the event description field because I need to keep my participants informed about the event type (namely user interviews) and what they are consenting to, their rights, and how their privacy is protected. The problem is that I cannot style the text, and it becomes a block paragraph. This is not usable - I would like to be able to add hierarchy and grouping with styling. 

### Describe the solution you'd like

I would like to be able to add line breaks, bolding, and italics to the text so that I'm providing a good experience to my users who book interviews. 

### Describe alternatives you've considered

I tried using markdown but it didn't work. In the end, I omitted important information so at least the message was concise. 

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
@agustif was proposing this!

**Comment by PeerRich** [comment]
we should add simple markdown support and small buttons like this: 

<img width="159" alt="image" src="https://user-images.githubusercontent.com/8019099/154851314-6c5080da-d6d5-460b-996e-8963e313f293.png">

i think we should strip down markdown to only offer:
- bold
- italic
- ordered list
- unordered list

**Comment by smithkelseyj** [comment]
Thanks for responding! Seems like a great solution. :)

**Comment by Brisklemonade** [comment]
Am I missing something? I don't see this available in the self-hosted or cal hosted versions.

![CleanShot 2024-11-23 at 11 23 36@2x](https://github.com/user-attachments/assets/5ab4d789-f582-48a6-82b3-a600c4b554e3)

**Comment by Joao-Marques-UA** [comment]
I would like to know the solution.

> Am I missing something? I don't see this available in the self-hosted or cal hosted versions. When I add the newline character (\n), it appears as is.
> 
> ![CleanShot 2024-11-23 at 11 28 55@2x](https://github.com/user-attachments/assets/8215ac42-07f3-4adf-8c22-94bd2d2bbb89)
> 
> ![CleanShot 2024-11-23 at 11 28 12@2x](https://github.com/user-attachments/assets/93039f22-8210-46ca-8158-fc4abacfe1af)
