### ISSUE TITLE
Sync issue when deleting appointments on Google Calendar

### ISSUE THREAD

**Issue by pietro14** [calcom/cal.com#1919]
### Issue Summary

After scheduling an appointment, if I cancel it directly from google calendar, the appointment remains on the Cal.com dashboard under the section "Bookings"

### Steps to Reproduce

1. (for example) Go to your Google Calendar and cancel an event that was created with cal.com
2. then go to Cal.com dashboard under the section "Bookings"
3. the appointment is still there (so I guess the invitee will still have his/her appointment on his/her calendar)

### Technical details

- Browser version: Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by milospuac** [comment]
Thanks for reporting this! Our team will address this issue

**Comment by miguelnietoa** [comment]
Hi, I would like to contribute to this issue. Could you please assign me?

**Comment by miguelnietoa** [comment]
Hey @PeerRich , do you think that when someone indicates that he/she will not attend, the event should be deleted from Cal.com?

**Comment by PeerRich** [comment]
@baileypumfleet maybe like a soft-delete?

**Comment by soplan** [comment]
At soplan.com we have full sync working with Google and Microsoft. So deleting or updating events in Outlook and Google will be updated in bookings accordingly. It took us some time to get it working as it's quite complex to solve without scanning and comparing bookings and calendars.

**Comment by leog** [comment]
Duplicate #5124, closing.

**Comment by oferhendin** [comment]
> Thanks for reporting this! Our team will address this issue

Hi, I have the same issue: when deleting an event from the organizer google calendar, it's not updated on cal.com "bookings" page and the time slot does not return to being available. 
can you pls help?

**Comment by PeerRich** [comment]
This is currently being worked on
