### ISSUE TITLE
RFC: Apps folder structure and hooks

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1923]
RFC summary of the recent discussion around `apps` (previously `integrations`) and what the best architecture is to build third-party apps

## Goals
- super easy to launch your own app 
- unified abstractions around installation, removal, authentication (i.e. OAuth)
- minimize merge conflicts
- touch as little lines of `core code` as possible (with smart abstractions)

## Status quo

- the new app store branch is introducing a new folder `apps` where each new app can live in (i.e. `apps/zoom`) with metadata, images, descriptions, etc., however, it is not clear yet how the zoom app will be hooked into the core app.
- right now, apps like "web3" are hardcoded into event-types and booking pages

## Proposal

What if we find a good abstraction (like WordPress, i know–different set of technologies) that allows adding apps to the core views without touching them.

## Example 1:

in `Shell.tsx`
https://github.com/calcom/cal.com/blob/8996c168cabcd37c605d9246b0ea7bf3c2029bb2/apps/web/components/Shell.tsx#L138

we have
```
const navigation = [
    {
      name: t("event_types_page_title"),
      href: "/event-types",
      icon: LinkIcon,
      current: router.asPath.startsWith("/event-types"),
    },
    {
      name: t("bookings"),
      href: "/bookings/upcoming",
      icon: CalendarIcon,
      current: router.asPath.startsWith("/bookings"),
    },
    {
      name: t("availability"),
      href: "/availability",
      icon: ClockIcon,
      current: router.asPath.startsWith("/availability"),
    },
    {
      name: t("integrations"),
      href: "/integrations",
      icon: PuzzleIcon,
      current: router.asPath.startsWith("/integrations"),
    },
    {
      name: t("settings"),
      href: "/settings/profile",
      icon: CogIcon,
      current: router.asPath.startsWith("/settings"),
    },
  ];
```

what if we extend this 

```
<nav className="mt-2 flex-1 space-y-1 bg-white px-2 lg:mt-5">
                  {navigation.map((item) => (
                    <Link key={item.name} href={item.href}>
                      <a
                        className={classNames(
                          item.current
                            ? "bg-neutral-100 text-neutral-900"
                            : "text-neutral-500 hover:bg-gray-50 hover:text-neutral-900",
                          "group flex items-center rounded-sm px-2 py-2 text-sm font-medium"
                        )}>
                        <item.icon
                          className={classNames(
                            item.current
                              ? "text-neutral-500"
                              : "text-neutral-400 group-hover:text-neutral-500",
                            "h-5 w-5 flex-shrink-0 ltr:mr-3 rtl:ml-3"
                          )}
                          aria-hidden="true"
                        />
                        <span className="hidden lg:inline">{item.name}</span>
                      </a>
                    </Link>
                  ))}
</nav>
```

with `appNavigation`:

```
<nav className="mt-2 flex-1 space-y-1 bg-white px-2 lg:mt-5">
                  {navigation.map((item) => (
                    <Link key={item.name} href={item.href}>
                      <a
                        className={classNames(
                          item.current
                            ? "bg-neutral-100 text-neutral-900"
                            : "text-neutral-500 hover:bg-gray-50 hover:text-neutral-900",
                          "group flex items-center rounded-sm px-2 py-2 text-sm font-medium"
                        )}>
                        <item.icon
                          className={classNames(
                            item.current
                              ? "text-neutral-500"
                              : "text-neutral-400 group-hover:text-neutral-500",
                            "h-5 w-5 flex-shrink-0 ltr:mr-3 rtl:ml-3"
                          )}
                          aria-hidden="true"
                        />
                        <span className="hidden lg:inline">{item.name}</span>
                      </a>
                    </Link>
                  ))}

                 <hr/>

                  {appNavigation.map((item) => (
                    <Link key={item.name} href={item.href}>
                      <a
                        className={classNames(
                          item.current
                            ? "bg-neutral-100 text-neutral-900"
                            : "text-neutral-500 hover:bg-gray-50 hover:text-neutral-900",
                          "group flex items-center rounded-sm px-2 py-2 text-sm font-medium"
                        )}>
                        <item.icon
                          className={classNames(
                            item.current
                              ? "text-neutral-500"
                              : "text-neutral-400 group-hover:text-neutral-500",
                            "h-5 w-5 flex-shrink-0 ltr:mr-3 rtl:ml-3"
                          )}
                          aria-hidden="true"
                        />
                        <span className="hidden lg:inline">{item.name}</span>
                      </a>
                    </Link>
                  ))}
</nav>
```

and `appNavigation` is dynamically built based on either file-system or other references in `apps/appRegistry.ts`

## Example 2:

`event-types/[type].tsx`
https://github.com/calcom/cal.com/blob/8996c168cabcd37c605d9246b0ea7bf3c2029bb2/apps/web/pages/event-types/%5Btype%5D.tsx#L419

should abstract all `video` apps and not hardcode them into the page

## Example 3:

DRAFT: Calendar Integrations

**Comment by agustif** [comment]
Awesome @Peer, my original insights I think come mainly from two open source projects, Im gonna share ‘em here.

I really lie the proposal! Adding my two cents here with some links to how other projects do it

I think our goal should be to aim for modularity which as much core and both first and third party packages as makes sense for us. We can mantain official ones, community can maintain the others. You can use both by doing a yarn add and adding something (import and declaration) to a config file..


I liked how both projects modularity evolved through time and you can just take a general look for ideas or best practices we can implement.

http://accountsjs.com
https://github.com/accounts-js/accounts
The first one is AccountsJS (What I used before finding next-auth) has a lot of modularity around different auth services etc. is a monorepo, etc

https://www.vendure.io/
https://github.com/vendure-ecommerce/vendure
Second one is a headless e-commerce framework. They have integrations too . Its a NestJS codebase which feels to angular imho but we can take some cues from there too


https://www.raycast.com/
https://github.com/raycast/extensions
And as a last one not an open source project but a great Alfred.app (App launcher) for mac called raycast.

They first started with scripts, and moved up to allowing an internal sdk to build integrations with and a marketplace.

**Comment by zomars** [comment]
This is what we have so far in #1869 

The chosen structure would be this one:

```text
cal.com/
├─ packages/
│  ├─ app-store/
│  │  ├─ example/               # The folder where the app will be contained (ie. zoomvideo, googlecalendar, etc.)
│  │  │  ├─ api/
│  │  │  │  ├─ ...              # API endpoints (add, callback, web hook, etc.)
│  │  │  │  └─ index.ts         # Re-exporting of api handlers
│  │  │  ├─ components/
│  │  │  │  ├─ ...              # Specific-to-app React Components (TDB how it's going to be consumed)
│  │  │  │  └─ index.ts         # Re-exporting of React components
│  │  │  ├─ lib/
│  │  │  │  ├─ ...              # Helpers, utils, VideoApiAdapaters, CalendarApiAdapaters
│  │  │  │  └─ index.ts         # Re-exporting of lib methods
│  │  │  ├─ package.json        # App metadata and dependencies
│  │  │  └─ index.ts            # Re-exporting of lib, api, components and app metadata (Name, description, etc.)
│  │  └─ index.ts               # The app registry, here you can "enable/disable" apps by re-exporting them.
```
