### ISSUE TITLE
Billing portal is broken for users without metadata.stripeCustomerId

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#1932]
### Issue Summary

There are many users that don't have a stripeCustomerId on their `users.metadata` column. We should add a step in our logic so this happens:

1. If user doesn't have a `stripeCustomerId`.
2. Look him up by email and if found save his `stripeCustomerId`.
3. If not found, create a new customer with his email and save the new `stripeCustomerId`.

This should happen on upgrade, and billing portal pages.

**Comment by PeerRich** [comment]
can we either (a) run a query to assign all or (b) show an error message to reach out to support?
