### ISSUE TITLE
rethink reschedule events as booking owner

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1934]
an owner of an event should instead "Request to Reschedule" that cancels the active event and sends an email to the attendee to re-book the same link

right now it shows the embed page of the owner (which is stupid, doesn't make sense because the owner doesn't know what works for the attendee)

<img width="430" alt="image" src="https://user-images.githubusercontent.com/8019099/155017697-d94faf19-050c-4bdc-b38a-45925977f1b5.png">

**Comment by PeerRich** [comment]
@Jaibles can you sketch out the emails or something missing?

**Comment by PeerRich** [comment]
it would also be great if we can have a mass-query API for rescheduling lets say an entire day (i.e. nuke-my-cal app which requests to reschedule the entire day of events)

**Comment by PeerRich** [comment]
@Jaibles I tagged you here because i don't know if this is ready for engineering. can you assign a dev once you think its ready?

**Comment by mountainsandcode** [comment]
One additional idea on reschedules: While I fully agree that it can be problematic for the owner to reschedule without knowing the attendee's availability, it might make sense for the owner to be able to choose a time outside of the availability schedule (perhaps showing a checkbox which allows the owner to select times outside of the availability schedule). Rationale being that they might try to accommodate a time that would normally not work for them to "make up" for having to reschedule?

**Comment by PeerRich** [comment]
@Jaibles once you are back from OOO can you post your new Figma workflow here and assign an engineer? 🎉  should be straight forward and would be great to be included in the [v.1.4 milestone](https://github.com/orgs/calcom/projects/1/views/1)

**Comment by Jaibles** [comment]
@PeerRich https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=4802%3A34616
Can you review this when you get a chance?

**Comment by Jaibles** [comment]
@PeerRich will I close this and add this to 1.5 instead https://github.com/calcom/cal.com/issues/2228 ?
