### ISSUE TITLE
Updated Custom Availability has No Effect

### ISSUE THREAD

**Issue by frankgreco** [calcom/cal.com#1948]
### Issue Summary

Consider an event with a custom availability from 1/1-1/7. Now update it to make it 1/1-1/6. After doing so, slots for 1/7 will still be shown.

### Steps to Reproduce

- create an event with custom availability
- modify the custom availability 
- observe that the slots were not modified

**Comment by milospuac** [comment]
Hey Frank, thanks for reaching out! Our team is already working on the custom availability for the event type.

**Comment by milospuac** [comment]
I don't think that there is an existing issue open. However, I tried setting up the custom availability for one of my event types and it looks like it's working now. I selected Tuesday and Wednesday from 12:00 to 17:00 and it's reflecting correctly

<img width="520" alt="Screen Shot 2022-02-24 at 08 40 38" src="https://user-images.githubusercontent.com/97884287/155479703-fb3f69df-9cba-4a5f-a919-cb4a4487a0ce.png">
<img width="773" alt="Screen Shot 2022-02-24 at 08 37 47" src="https://user-images.githubusercontent.com/97884287/155479738-bdc9d2d2-b3d1-455b-876f-5a84640c7b59.png">

What kind of availability for event type did you set? Also, what time zone are you in?

**Comment by NicoHood** [comment]
Where the heck can I find the custom availability setting? I am searching for that feature, but it is not shown in my UI. Is it only visible to pro users?

As far as I understand the docs (and this issue) it should be possible?
https://docs.cal.com/deep-dives/availability
https://docs.cal.com/deep-dives/event-types#availability

**Comment by PeerRich** [comment]
is it not in app.cal.com/availabillity? the screenshot from @milospuac is out of date

**Comment by NicoHood** [comment]
Sure, but I cant set any specific time, just general availability. What If I aint got time on THIS friday?

![image](https://user-images.githubusercontent.com/6888294/187618798-70eaaa7f-d8ab-4316-8663-7acb69d04e64.png)

![image](https://user-images.githubusercontent.com/6888294/187618678-dba2d2ac-156f-4e7c-bb76-80eb61d4ca27.png)

**Comment by PeerRich** [comment]
> Sure, but I cant set any specific time, just general availability. What If I aint got time on THIS friday?
> 
> ![image](https://user-images.githubusercontent.com/6888294/187618798-70eaaa7f-d8ab-4316-8663-7acb69d04e64.png)
> 
> ![image](https://user-images.githubusercontent.com/6888294/187618678-dba2d2ac-156f-4e7c-bb76-80eb61d4ca27.png)

date specific availability is being worked on right now by @emrysal

**Comment by NicoHood** [comment]
Is there an issue, where we can track the progress? This is really something that kept me from using cal.com for now. Super excited to hear that!

**Comment by PeerRich** [comment]
i believe there is a ticket somewhere, #2199 this one maybe?

**Comment by PeerRich** [comment]
hey, can you try the latest version?
