### ISSUE TITLE
Unable to create event in outlook calendar with external id

### ISSUE THREAD

**Issue by glekhak** [calcom/cal.com#1955]
**Issue Summary**
For Office 365 Calendar service microsoft provides different api's for creating events with & without external Id. Here in cal.com we are using same api for both. If external id is present it is not able to create event in connected calendar.

![image](https://user-images.githubusercontent.com/12994387/155342576-55980b10-1cf5-4704-b59f-d6f91553717b.png)

**Code causing issue**

  async createEvent(event: CalendarEvent): Promise<NewCalendarEventType> {
    try {
      const accessToken = await this.auth.getToken();

      const calendarId = event.destinationCalendar?.externalId
        ? `${event.destinationCalendar.externalId}/`
        : "";

      const response = await fetch(`https://graph.microsoft.com/v1.0/me/calendar/${calendarId}events`, {
        method: "POST",
        headers: {
          Authorization: "Bearer " + accessToken,

**Comment by milospuac** [comment]
Thanks for reporting the issue. Our team will have a look into this.
