### ISSUE TITLE
Half hours are ignored in booking page

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#1959]
### Issue Summary

Having this setup for an hour long event type:

![image](https://user-images.githubusercontent.com/3504472/155377371-64ebae2e-e159-4840-8732-087694f987ed.png)

One would expect to have only three slots with 10, 11:30 and 13. But the 11:30 slot starts at 12:

![image](https://user-images.githubusercontent.com/3504472/155377406-5a3e6cf8-6980-4ea2-8b6d-a11244e5823d.png)

### Steps to Reproduce

1. Add event type availability starting in half hours
2. Go to the booking page

**Comment by juliansg022** [comment]
Hello, I'll take a look at this
