### ISSUE TITLE
Encoding bug in notification emails

### ISSUE THREAD

**Issue by FlxMgdnz** [calcom/cal.com#1961]
### Issue Summary

Email clients do not properly display event titles that contain special characters.

### Steps to Reproduce

1. Create an event name that contains special characters, e.g., & or '
2. Book a meeting with that event
3. See email subject

### Technical details

- Bug reproduceable on iOS Mail and Gmail

![image](https://user-images.githubusercontent.com/20115649/155389971-95947ce2-4c9f-431c-99db-b7eba38b02fa.png)

![Screenshot 2022-02-23 200838](https://user-images.githubusercontent.com/20115649/155390102-9790c26a-d3eb-4acf-bcbf-be3b5dca299f.png)

![image](https://user-images.githubusercontent.com/20115649/155390344-20dd6cac-aa69-4a8d-9767-327c54d8d4ce.png)

**Comment by milospuac** [comment]
Thanks for reaching out! Our team will look into this.

**Comment by PeerRich** [comment]
@G3root can you look into this? should be a quick fix
