### ISSUE TITLE
mobile: grouped avatars line break

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1965]
![image](https://user-images.githubusercontent.com/8019099/155411622-1cd13da5-45da-4145-bf52-4377cd43c308.jpeg)

**Comment by hariombalhara** [comment]
@PeerRich I don't think it is an issue anymore.

<img width="734" alt="Screenshot 2022-03-08 at 12 35 06 PM" src="https://user-images.githubusercontent.com/1780212/157184611-ce700259-232b-42a1-a501-c96a17d4b000.png">
