### ISSUE TITLE
additional inputs cause <br> in /booking description 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1972]
right now, additional inputs are saved as pure HTML with `<br>` in the "description" column, which results in:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/8019099/155537821-f25ba5c8-f57d-40b4-8d2c-8d82fb1d7cbd.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/8019099/155537525-ca3b1a17-f3c4-45b7-b7db-67b3781140f5.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/8019099/155537547-4f9a07f2-d1c6-46d5-90b0-85e08fef6df2.png">

**Comment by miguelnietoa** [comment]
I don't think this happens anymore, right? @PeerRich

**Comment by adriaanvanrossum** [comment]
It still happens:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/1079135/162425013-8e61ede9-9f7f-4a18-84f8-f4b20711228d.png">

(this is the app.cal.com version of today)

**Comment by miguelnietoa** [comment]
> 

Does the picture come from any integration?

**Comment by adriaanvanrossum** [comment]
What do you mean? It's an event created by cal.com which gets added to my calendar automatically. We use mailbox.org as our CalDAV provider.

**Comment by miguelnietoa** [comment]
Ok, it is from a CalDav Server. 👍🏻  
I was asking because I tried it out on Google Calendar and the additional notes are shown properly.
So let's wait for a core team member to solve this.
