### ISSUE TITLE
Jitsi: No meeting link in Emails

### ISSUE THREAD

**Issue by dit7ya** [calcom/cal.com#1981]
### Steps to Reproduce

1. Schedule something.
2. Check the email received - the `Where` field.

It should have a link to the scheduled video call - but it only has the provider name.

For example
![2022-02-25_14-28](https://user-images.githubusercontent.com/14034137/155685956-0fd517bb-4ebe-41bc-b152-cb2d9a5ebc8f.png)

**Comment by milospuac** [comment]
Hi there! Thanks for reaching out. Our team will have a look into this.

**Comment by PeerRich** [comment]
does it appear in the calendar invite?

**Comment by imkrunal** [comment]
There seems to be issue with `BookingReference`. I have tried to create a jitsi meeting and huddle meeting. In jisti meeting it did not create booking reference when it should.

One more issue huddle meeting credentials received in email but not displayed on success page.

![image](https://user-images.githubusercontent.com/82360200/155984653-021a1eca-ecc4-4764-8017-fb3d708423c8.png)

I will try to fix this issue and send a pr.

**Comment by imkrunal** [comment]
Update: I have created PR. We were creating the jitsi link on the fly on success page instead of this i have created a booking reference like huddle integration and stored it then send the email with meeting link.

**Comment by philippdormann** [comment]
Yeah, good catch!
The reason i built `BookingPage.tsx` this way was to support directly displaying the meeting link on `/success` 👀

This will break with this PR - right?

**Comment by imkrunal** [comment]
> Yeah, good catch! The reason i built `BookingPage.tsx` this way was to support directly displaying the meeting link on `/success` eyes
> 
> This will break with this PR - right?

By break if you mean meeting link will not be displayed on success page then yes. I tried with huddle and it wasn't displaying link for it as well. Let me see if i can fix that.

**Comment by philippdormann** [comment]
exactly, that link display on `/success/` will break 😉

The returned string is used in the url as a query parameter.
```
return router.push({
        pathname: "/success",
        query: {
          ...
          location,
        },
      });
```
This can't use a much more complex data structure (such as the whole location info/ calEvent) if you were also thinking about that solution 🤔😁



Maybe we should accept this breaking for now and open a new feature request "/success/: directly show meeting url for non-opt-in meetings" 🙂
