### ISSUE TITLE
send email when booking an opt-in booking

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1988]
as of today we only send emails when a booking was confirmed

for opt-in bookings we should also send an email with this content: 

![image](https://user-images.githubusercontent.com/8019099/155882207-e585f25c-ab58-4766-a5ad-8b09dc0df894.png)

**Comment by Mayowa-Ojo** [comment]
I would like to take this on. Can get a PR up in a few hours
@PeerRich
