### ISSUE TITLE
Apple Calendar events seems to be handled with the wrong timezone

### ISSUE THREAD

**Issue by buschco** [calcom/cal.com#1992]
### Apple Calendar events seems to be handled with the wrong timezone

I have an appointment in my calendar which should prevent people from booking.

- In my timezone (Berlin) there is an event starting at 13.00 (1pm) on March 4 and ending 15.00 (3pm)
- I have availability from 12-13, 13-14, 14-15, 16-17 (12-1pm, 1pm-2pm, 2pm-3pm, 4pm-5pm)
- So the appointment should block: <s>12-13</s>, <s>13-14</s>, <s>14-15</s>, 16-17 (<s>12-1pm</s>, <s>1pm-2pm</s>, <s>2pm-3pm</s>, 4pm-5pm)
- but it shows a bookable slot at 13.00 (1pm) 
- the troubleshooter shows the event shifted by 1 hour but the hover shows the right time (not sure about the timezone though)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- I have everything in the same timezone (Berlin), but maybe there are settings I am not aware of.
- In Cal settings I have chosen GMT+1 (Berlin...) timezone

<img width="983" alt="Screenshot 2022-02-27 at 20 29 11" src="https://user-images.githubusercontent.com/14929556/155897557-741685b1-3a86-4f53-9ea6-32ed14993f54.png">
<img width="1087" alt="Screenshot 2022-02-27 at 20 29 56" src="https://user-images.githubusercontent.com/14929556/155897558-7fd4e6f0-99a6-4a38-8b09-75196ad746e9.png">
<img width="598" alt="Screenshot 2022-02-27 at 20 30 41" src="https://user-images.githubusercontent.com/14929556/155897559-4a4508cc-2a94-4ab4-a691-54bd904309d3.png">
<img width="798" alt="Screenshot 2022-02-27 at 20 30 02" src="https://user-images.githubusercontent.com/14929556/155897561-e969b740-958d-43bf-b469-c737047b1f85.png">
<img width="211" alt="Screenshot 2022-02-27 at 20 40 06" src="https://user-images.githubusercontent.com/14929556/155897562-3a844536-6a29-47f5-8564-b2fbe0dba4ed.png">

**Comment by agustif** [comment]
Hey there @buschco I've been able to reproduce the bug on my end too, and I'm further investigating to fix this.

Will let you know once it's fixed!

Thanks for the thorough report, really helps us do our work!

**Comment by Jacubeit** [comment]
currently testing cal.com - can confirm this.
Additional Info:
I connected three calendars (zoho caldav, apple caldav, google).
Timeslots in the google calendar are not bookable in cal.com. 
Apple and zoho are 1hour off.


Maybe there could be an issue with interpreting `TZID` in [iCalendar format](https://icalendar.org/iCalendar-RFC-5545/3-2-19-time-zone-identifier.html)? @agustif

**Comment by Jacubeit** [comment]
To add on my previous post. I managed to pull the caldav data directly.
It may help?

```BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//macOS 12.2.1//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20220308T070232Z
UID:XXX
DTEND;TZID=Europe/Berlin:20220309T100000
SUMMARY:test
LAST-MODIFIED:20220308T070239Z
DTSTAMP:20220308T070241Z
DTSTART;TZID=Europe/Berlin:20220309T090000
SEQUENCE:1
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
BEGIN:VALARM
X-WR-ALARMUID:XXX
UID:XXX
TRIGGER:-PT5M
X-APPLE-DEFAULT-ALARM:TRUE
ATTACH;VALUE=URI:Basso
ACTION:AUDIO
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:STANDARD
DTSTART:18930401T000000
RDATE:18930401T000000
TZNAME:CEST
TZOFFSETFROM:+005328
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19160430T230000
RDATE:19160430T230000
RDATE:19400401T020000
RDATE:19430329T020000
RDATE:19460414T020000
RDATE:19470406T030000
RDATE:19480418T020000
RDATE:19490410T020000
RDATE:19800406T020000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19161001T010000
RDATE:19161001T010000
RDATE:19421102T030000
RDATE:19431004T030000
RDATE:19441002T030000
RDATE:19451118T030000
RDATE:19461007T030000
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19170416T020000
RRULE:FREQ=YEARLY;UNTIL=19180415T010000Z;BYMONTH=4;BYDAY=3MO
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19170917T030000
RRULE:FREQ=YEARLY;UNTIL=19180916T010000Z;BYMONTH=9;BYDAY=3MO
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19440403T020000
RRULE:FREQ=YEARLY;UNTIL=19450402T010000Z;BYMONTH=4;BYDAY=1MO
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19450524T020000
RDATE:19450524T020000
RDATE:19470511T030000
TZNAME:CEMT
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19450924T030000
RDATE:19450924T030000
RDATE:19470629T030000
TZNAME:CEST
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19460101T000000
RDATE:19460101T000000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:STANDARD
BEGIN:STANDARD
DTSTART:19471005T030000
RRULE:FREQ=YEARLY;UNTIL=19491002T010000Z;BYMONTH=10;BYDAY=1SU
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:STANDARD
DTSTART:19800101T000000
RDATE:19800101T000000
TZNAME:CET
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:STANDARD
BEGIN:STANDARD
DTSTART:19800928T030000
RRULE:FREQ=YEARLY;UNTIL=19950924T010000Z;BYMONTH=9;BYDAY=-1SU
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
END:VCALENDAR```

and corresponding screenshots from calendar:
<img width="183" alt="Bildschirmfoto 2022-03-08 um 08 18 21" src="https://user-images.githubusercontent.com/2848440/157186995-8e594dbe-fad8-41c2-b5d8-cec8a31214a3.png">

cal.com:
<img width="596" alt="Bildschirmfoto 2022-03-08 um 08 18 39" src="https://user-images.githubusercontent.com/2848440/157187022-98b08705-3eff-4076-8680-670806d41069.png">

**Comment by ultrazeus** [comment]
I am experiencing the same issue. E.g. an Apple calendar entry from 10AM-11AM: this shows up on Cal.com as a bookable timeslot, whereas 11AM-12AM is blocked on Cal.com.
Any update on this?

**Comment by KrisKodira** [comment]
Same here. Any updates? Any possibilities for fixing this?

**Comment by buschco** [comment]
I tried to debug this today. Correct me if I am wrong, but booking these Events should not cause any collision in the calendars right? So it is a display issue and I also suppose it does not apply to Apple Calendar only.

I created this [PR](https://github.com/calcom/cal.com/pull/2296) maybe someone of the maintainers could have a look 🙏
