### ISSUE TITLE
iCloud from China could not connect.

### ISSUE THREAD

**Issue by daimajia** [calcom/cal.com#1998]
Thanks all your work on this awesome project. 

As you may know the iCloud in China is running by Cloud Guizhou. https://support.apple.com/en-hk/HT208351

I tried several times to connect iCloud, but failed. Have no idea how to solve this.

You could reproduce this issue by setting the account location to China. 

<img width="497" alt="图片" src="https://user-images.githubusercontent.com/2503423/155904040-935d953d-ce7d-4aa0-bb95-dc70f9d2ed9a.png">

**Comment by zomars** [comment]
Could you provide a reproduction as stated in the Issue template? (Using birdeatsbug.com)
