### ISSUE TITLE
Docs title showing untitled

### ISSUE THREAD

**Issue by imkrunal** [calcom/cal.com#2005]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

All the pages on docs showing `Untitled` as title.
![image](https://user-images.githubusercontent.com/17720036/156018766-533c759b-720d-4c78-9713-f9b570c10e91.png)

### Steps to Reproduce

1. Open any page in `docs.cal.com`

### Technical details

- Maybe new version nextra of docs broken the titles.

**Comment by milospuac** [comment]
Thank you for bringing this to our attention! Our team will fix this
