### ISSUE TITLE
Rescheduled/Cancelled Events Showing on Google Calendar

### ISSUE THREAD

**Issue by slavakurilyak** [calcom/cal.com#2009]
### Issue Summary

I would like to report a bug (or feature request) with Cal.

One of my clients scheduled and cancelled an event with me. When I went to check on my Google Calendar, I noticed the event was showing on my schedule. In other words, Cal did not delete my Google Calendar event.

I assume that Cal has user permissions to delete events on Google Calendar. If so, then the event should be deleted and should not appear on my schedule.

If Cal does not have user permissions to delete events on Google Calendar, then it would be great if Cal user interface shows “allow Cal to modify or delete events”.

![cal-bug](https://user-images.githubusercontent.com/6625584/156049745-c97a2d09-c195-42c3-bade-0bb90fd2de6f.jpg)

### Steps to Reproduce

When I clicked on the “Need to reschedule or cancel” link, I saw that the “This booking was already cancelled.”

![cal-bug-2](https://user-images.githubusercontent.com/6625584/156049699-b47fef3e-565f-44da-bd15-93cee188576f.jpg)

### Technical details

I assume this is a Cal app permission issue with Google Calendar.

**Comment by milospuac** [comment]
Hi there! Thank you for reaching out and reporting this. Our team is on it

**Comment by andreaestefania12** [comment]
Hi, I would like to contribute to this issue. Could you assign it to me, please?
