### ISSUE TITLE
HTTP 404 when trying to access `/[user]/book` route with username containing uppercase letters

### ISSUE THREAD

**Issue by LouisHaftmann** [calcom/cal.com#2010]
### Issue Summary

HTTP 404 when trying to access `/user/book` route with username containing uppercase letters

### Steps to Reproduce

1. Went to https://cal.com/UppercaseName/book?type=...&date=... (Username with uppercase letters)
2. HTTP 404 Error

### Reason

- missing `toLowerCase()` in [/[user]/book route](https://github.com/calcom/cal.com/blob/7826a34b007f5c59fc736ae8cffb6066500c64b2/apps/web/pages/%5Buser%5D/book.tsx#L29) line 29

**Comment by milospuac** [comment]
Hi there! Thanks for reaching out and reporting this. Our team will address the issue

**Comment by milospuac** [comment]
In fact, it's already opened  #2011
