### ISSUE TITLE
Input components selection - A11y 

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#2016]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Dark-mode selection color on booking components is against A11y Standards 
![image](https://user-images.githubusercontent.com/55134778/156145875-b7bd347e-b72c-493b-a53a-44f565ec81f0.png)

### Steps to Reproduce

1) Navigate to www.cal.com/[user]
2) Follow form steps till you get to the input components
3) Activate dark mode 
4) highlight text 

![image](https://user-images.githubusercontent.com/55134778/156146171-0e72a3cf-cd2a-48b2-b401-9639a1872a07.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

N/A

**Comment by sean-brydon** [comment]
Happy to pick this up in a PR :)

**Comment by PeerRich** [comment]
thank you!
