### ISSUE TITLE
[CAL-1682] Team members can create team events but can't update them

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#2035]
### Issue Summary

Being a member of a team allows you to create new event types from the team, but doesn't allow you to update them.

### Steps to Reproduce

1. Went to dashboard
2. Created a new event type for a team I'm a member of (not owner)
3. Can't update that same event type

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- https://app.birdeatsbug.com/sessions/As4F1pYE88T63MtT0LAZa

<sub>[CAL-1682](https://linear.app/calcom/issue/CAL-1682/team-members-can-create-team-events-but-cant-update-them)</sub>

**Comment by PeerRich** [comment]
is this still open?

**Comment by roae** [comment]
@zomars I can't create an event type for the team as a member, only owners and admin.  is this the desired behavior?

**Comment by zomars** [comment]
> @zomars I can't create an event type for the team as a member, only owners and admin. is this the desired behavior?

This issue was opened before we had de admin/owner behavior. Let's just double check that admin/owners can update created events and close this issue.

**Comment by zomars** [comment]
Closing as cannot reproduce anymore
