### ISSUE TITLE
Unusual Cal Events via Webhook

### ISSUE THREAD

**Issue by slavakurilyak** [calcom/cal.com#2043]
### Issue Summary

After setting up the Discord webhook for Cal, I am noticing unusual requests which do NOT show up in the [upcoming bookings](https://app.cal.com/bookings/upcoming).

### Steps to Reproduce

1. Set up Discord webhook for Cal
2. Receive unusual calendar requests

![01](https://user-images.githubusercontent.com/6625584/156515398-12b5470c-3264-42ec-a84e-49a7a1a07b87.jpg)
![02](https://user-images.githubusercontent.com/6625584/156515400-63875b5b-2005-4e65-91c8-426add593b24.jpg)
![03](https://user-images.githubusercontent.com/6625584/156515401-fab0ccf9-04da-4927-bed4-e9dae1f9e70b.jpg)
![04](https://user-images.githubusercontent.com/6625584/156515403-0ed1924b-ac1f-4a00-96a6-648f3f965690.jpg)

### Technical details

- I assume this is related to #1886

**Comment by alishaz-polymath** [comment]
Hi @slavakurilyak Thank you for reporting this. This is odd, as the webhook only fires once the event is booked, doesn't matter if we're using the webhook template (for discord) or otherwise. Can you check through the Past and Cancelled tabs as well, just to make sure it isn't in one of them?
Otherwise, I would imagine that the same webhook is being used by someone else which could only mean that your discord webhook URL is available to them.

**Comment by alishaz-polymath** [comment]
But I do figure that currently, the discord webhook template doesn't take the event trigger info into consideration, so that would need to be added as a follow up!

**Comment by slavakurilyak** [comment]
After deleting my Discord webhook and adding a new one, the issue still persists.

![screenshot](https://user-images.githubusercontent.com/6625584/157569762-a0b5b657-f957-4037-ab53-5a4d4ad20260.jpg)

I also checked my past and cancelled tabs using Cal.com but I did not see any related events.

No one has access to my webhooks.

![screenshot-2](https://user-images.githubusercontent.com/6625584/157570539-06633343-a917-44a4-b3d5-e4958fd04c6c.jpg)

**Comment by kb24x7** [comment]
Same issue here

**Comment by alishaz-polymath** [comment]
@kb24x7 @slavakurilyak This has only started happening recently?

**Comment by kb24x7** [comment]
I added my webhook yesterday so can't confirm the duration of how long its been happening since.

**Comment by alishaz-polymath** [comment]
The weirdest part of the payload is it is missing `'type'` (notice empty paranthesis in the `what`). I tried re-creating it locally, but to no avail. ALthough, I might know what's going on here, will run a few tests.

**Comment by alishaz-polymath** [comment]
Thank you @slavakurilyak for raising this issue. After a lot of debugging and testing, I have finally managed to re-create the issue and here are the steps:

1. Create a new webhook on one account.
2. Log in to another account and either create a new event-type (as you would need to delete this later for testing purposes)
3. Create a test booking on the new event
4. Delete the event-type
5. Now cancel the earlier booking
By now you should have received a webhook trigger with the details relating to the cancelled event on the account with the webhook integrated.

I'm working on the fix right now and it should be merged to main very soon!
