### ISSUE TITLE
event-type dropdown with duplicate and delete

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2050]
depends on https://github.com/calcom/cal.com/issues/2073 to be done first

<img width="411" alt="image" src="https://user-images.githubusercontent.com/8019099/156606087-69b29522-28e7-420e-a91b-86d2093c4ea6.png">

- later: archive

**Comment by imkrunal** [comment]
can i take this? @PeerRich

**Comment by PeerRich** [comment]
i noticed, let's do this ticket first: https://github.com/calcom/cal.com/issues/2073 and introduce a new `<Menu>` component before working on this
