### ISSUE TITLE
Clarify generic "remote meeting" link

### ISSUE THREAD

**Issue by astrojuanlu** [calcom/cal.com#2056]
### Is your proposal related to a problem?

I have a custom solution for videoconference calls I use for my meetings. However, none of the options for "Location" works in this case. These are the ones I see at the moment:

:x: Google Meet (nope)
:x: Daily.co (nope)
:x: Jitsi (close, but no cigar)
:x: Huddle01 (nope)
❓ Link or In-person meeting - closest, but the link seems to expect an address?

![Screenshot from 2022-03-04 13-13-21](https://user-images.githubusercontent.com/316517/156761523-774a1448-331c-4831-9dbb-8b14575f2665.png)

:x: Phone call (nope)

An in-person meeting is one thing, and a remote meeting on "none of the above" is a different thing.
 
### Describe the solution you'd like

Either

a) Separate "in-person meeting" (which asks for an address, coordinates, Google Maps link, whatever) and "custom videoconference" (which asks for a plain link), or
b) Reword current "link or in-person meeting" to clarify that custom videoconference solutions are also accepted.

### Describe alternatives you've considered

Not doing anything. Sure it's not the end of the world, but a small UX improvement would be nice.

### Additional context

Nope

**Comment by PeerRich** [comment]
Yeah I am open to have two options:

- Link (validates URLs)
- In-Person (validates for address, could even use auto-completion for addresses)

**Comment by sean-brydon** [comment]
Closing - Solution has been implemented

**Comment by astrojuanlu** [comment]
Just saw it deployed, awesome 🙌🏽 you rock!
