### ISSUE TITLE
Back Button on Event Booking page [user]/[type]

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2058]
### Is your proposal related to a problem?

I am not able to go and choose a different Event Type once I have chosen one.
See <img width="1304" alt="Screenshot 2022-03-04 at 6 47 09 PM" src="https://user-images.githubusercontent.com/1780212/156770249-29e84c78-cefe-43a0-bf83-3e4dbb0dd1f8.png">

### Describe the solution you'd like

There should be  a button to take me back to Event Types List page in case I change my mind and want to book a different Event

**Comment by sean-brydon** [comment]
Thanks for reporting this - Ill take a look at implementing this :)

**Comment by sean-brydon** [comment]
Merged - Thank you for reporting this. 

 Closing issue
