### ISSUE TITLE
RFC: EventTypes with slots/seats

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#2064]
## RFC: Event Types with slots/seats first steps
The following are all the description and ideas gathered for this new feature.

### Example User cases
- Private tutor can be booked "5 times per day" he has a 9 to 5 availability. He has 8 one-hour slots. But if he has been booked 5 times already, then he's done for the day and should appear unavailable even if he has slots left.
- Classroom has a 10 students per class limit. The time slot can be booked 10 times, one per student. After that the time slot can't be booked anymore but you can book other time slots.
- A conference-like event is taking place, it only has one time slot and can be booked 100 times. Each individual can book up to 5 seats. Once the 100 seats are booked the time slot is closed.

### Action Items

| Item             | Description                                                                       |
| ---------------- | --------------------------------------------------------------------------------- |
| seatsPerTimeSlot | max. quantity an event is allowed to be booked per individuals for each time slot |
| seatsPerAttendee | max. quantity an attendee is allowed to book for a time slot in a certain event   |
| bookingLimit     | max. quantity an event is available to be booked for a day/month/week             |
| bookingLimitType | string enum for type on bookingLimit (day/month/week)                             |

### Describe the solution you'd like

We have identified the next key features to develop:

- User can edit their **seatsPerTimeSlot** per event on the event type advanced settings section **(Required)**
- User can set an amount of _**seatsPerAttendee**_ for each booking. **(Required)**
- 5 or more seats availability is a PRO feature **(Required)**
- Attendee can book on an event based on its seat availability. **(Required)**
- Attendee can book up to _**seatsPerAttendee**_ and pay accordingly to number of seats selected **(Required)**
- Seat availability must be visible (Optional)
- Queue system, so if an attendee cancels users are moved within the queue (Optional)
- ~~User can set a window time availability for booking a event (Optional)~~ 

There was an attempt to this feature on PR #271, but if any challenge or something that can block development of this feature comes to your mind, let me know.

### Challenges
- How we should handle stripe and multiple seats selected? Payment, Invoice, Cancellation.
- What should happen when certain booking it's at its capacity and the User owner change slot availability to a less than previous max seats value?
- What approach to take for notifying User, when his event has reached capacity or all events available are booked?
- How synced calendars should display every booking made for the time-slot? Creation, updating, guest visibility for every calendar integration

### Opportunities 
- Send to the attendee a branded ticket number _# 001, # 002, ...# 006_ with a QR just like NextJs does on their events.
- Queue system in case there are no seats left.

@emrysal @alishaz-polymath @zomars

**Comment by PeerRich** [comment]
i think more than 5 people should be pro. more than 5 sounds like a commercial usecase and then it's fine to upgrade

**Comment by zomars** [comment]
Are seats counted per time slot? Per day? Or could it be configurable? Can we check for some actual use cases to validate the mvp features?

**Comment by alannnc** [comment]
@zomars So far it will be only per time slot. For configurations, you should only be able to assign a maxSeats number per event type and this translate to max seat per time slot available. Pro users can set a higher amount than trials.

**Comment by emrysal** [comment]
Looks good, is 3. optional? Seems required to me. 4 is optional but a low hanging fruit

**Comment by zomars** [comment]
Use cases that come to mind:

- Private tutor can be booked "5 times per day" he has a 9 to 5 availability. He has 8 one hour slots. But if he has been booked 5 times already, then he's done for the day and should appear unavailable even if he has slots left.
- Classroom has a 10 students per class limit. The time slot can be booked 10 times, one per student. After that the time slot can't be booked anymore but you can book other time slots.
- A conference-like event is taking place, it only has one time slot and can be booked 100 times. Each individual can book up to 5 seats. Once the 100 seats are booked the time slot is closed.

Side note. How seats can be handled for paid bookings with Stripe?

**Comment by alishaz-polymath** [comment]
> Use cases that come to mind:
> 
> * Private tutor can be booked "5 times per day" he has a 9 to 5 availability. He has 8 one-hour slots. But if he has been booked 5 times already, then he's done for the day and should appear unavailable even if he has slots left.
> * Classroom has a 10 students per class limit. The time slot can be booked 10 times, one per student. After that the time slot can't be booked anymore but you can book other time slots.
> * A conference-like event is taking place, it only has one time slot and can be booked 100 times. Each individual can book up to 5 seats. Once the 100 seats are booked the time slot is closed.
> 
> Side note. How seats can be handled for paid bookings with Stripe?

Agree with your analysis @zomars . I think there are a couple other important features/points that come to mind:

- we would potentially need an optional date range allowing people to book within that date range rather than using the the minimum booking notice for this purpose (since they might need to organize stuff accordingly and need more time, or be something like a flash booking where they only open it for a couple of days, but the event is a week into the future??)
- We would probably need a new emailing template which sends a booking confirmation to the organiser once the aforementioned date range/booking period ends or when the slot is fully booked to confirm the total number of attendees for their event (might be helpful/handy l in many cases, even though they can log in to view it) so that the organiser might open up spots for the same event if they so choose (although this might not be needed in the first MVP)
- We definitely need stripe use for seats as well because that would be need in most cases.

**Comment by alannnc** [comment]
Thank you for all the feedback, will start updating the details above.
I will start defining two user cases described by @zomars as our main goal for this development.
And for @alishaz-polymath comments, some of your points will be moved too optional and challenges.

**Comment by alishaz-polymath** [comment]
@alannnc amazing! I plan on getting started on this pretty soon. If everyone is in agreement on the discussed points wrt goals and expected outcome, I'll get started on it. 😄

**Comment by alannnc** [comment]
@alishaz-polymath Just updated all the details, before moving into code let's do a quick run of what the mentioned changes should affect current app flow.

**Comment by alishaz-polymath** [comment]
@alannnc Precisely!
@Jaibles Do we have a flow ready for this?

**Comment by PeerRich** [comment]
designs:
https://user-images.githubusercontent.com/8019099/155010924-2694ad1d-4f88-4bf1-97a2-1a9369850d23.png

**Comment by PeerRich** [comment]
> @PeerRich shouldn't filled seats simply not appear?

i think a disabled state with
"4/4 seats taken"

is the best so people know there used to be a time

**Comment by PeerRich** [comment]
this has been stale, who is working on this? @alishaz-polymath @alannnc @joeauyeung?

**Comment by alishaz-polymath** [comment]
> this has been stale, who is working on this? @alishaz-polymath @alannnc @joeauyeung?

@PeerRich Last I checked, it was @joeauyeung.
