### ISSUE TITLE
replace headlessui with radix-ui

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2073]
we still have some places where we use headless-ui
<img width="381" alt="image" src="https://user-images.githubusercontent.com/8019099/156919787-ce85636c-bde6-4590-b242-d992711355ec.png">

instead of `radix-ui`. Lets replace those components and remove the dependency.

`import { Switch } from "@headlessui/react";` => https://www.radix-ui.com/docs/primitives/components/switch

`import { Menu, Transition } from "@headlessui/react";` => https://www.radix-ui.com/docs/primitives/components/dropdown-menu

We need a new `<Menu/>` component (similar to `components/ui/Dropdown/Dropdown.tsx`) 

remember to abide by the tailwind design system and not use the default radix-ui styles

**Comment by leog** [comment]
@PeerRich can you point to where the new Menu component should be used and if there is a Figma design for it? I'm not needing such a component for #2050 so I will tackle this requirement separately alongside the move from headlessui to radix.

**Comment by agustif** [comment]
Could this be useful https://github.com/ecklf/tailwindcss-radix to us?

**Comment by PeerRich** [comment]
> @PeerRich can you point to where the new Menu component should be used and if there is a Figma design for it? I'm not needing such a component for #2050 so I will tackle this requirement separately alongside the move from headlessui to radix.

tagged you in twist
