### ISSUE TITLE
Time format not respected

### ISSUE THREAD

**Issue by k3davis** [calcom/cal.com#2082]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In my profile I've selected "12 Hour" time format, by on my events it lists available slots in 24 Hour time format (13:00, etc.). I could not find a time format setting on the event setup itself, which is what led me to believe the profile setting controlled this. Perhaps there is another location I have missed?

### Steps to Reproduce

1. Set time format to 12 Hour in profile settings
2. Expected to see time slots available for events in 12 Hour format, but did not

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- In case it is relevant, I experienced this issue on the hosted "app.cal.com" version (free saas version)

**Comment by agustif** [comment]
Hello @k3davis thanks for your report.

We recently implemented some improvements on the 24/12h settings.

What is your browser locale? Would make sense that your browser's locale and profile settings don't match and thus the different views? 

I'll look into this

**Comment by k3davis** [comment]
My browser local is `en_US`, so if the display is based on that it's even more odd to see 24h time by default. Thanks for looking into it!

**Comment by agustif** [comment]
Hey, we recently merged an update to our timeFormat lib.

Can you please tell me if you're still experiencing this issue or has been solved for you @k3davis thank you!

**Comment by k3davis** [comment]
Doesn't appear to be any change so far.

![image](https://user-images.githubusercontent.com/1307914/160017452-b7ce6a92-c0c2-4335-87c6-bfc71753b1a1.png)

**Comment by agustif** [comment]
> Doesn't appear to be any change so far.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1307914/160017452-b7ce6a92-c0c2-4335-87c6-bfc71753b1a1.png)
> 
> 

Will  check again and come back with news, sorry

**Comment by joeauyeung** [comment]
I found it had to do with `localStorage.24hourformat`. I was working on it on my desktop before leaving home so I'll try and finish it up next week.

**Comment by mholt** [comment]
Also experiencing the exact same issue. Thanks for looking into fixing this!

**Comment by k3davis** [comment]
I don't understand the issue on this one -- to this day on 2.0 "free" I have "12 hour" selected as time format here:

https://app.cal.com/settings/my-account/general

but the calendar still shows 24 hour time. In local browser storage `timeOption.is24hClock` is `true`. Even when I delete local storage, it is recreated as such. If I _manually_ change the browser storage value, it looks correct, but who is going to do that? What am I missing here?

**Comment by mholt** [comment]
@k3davis No, I'm seeing the same thing, definitely still doesn't appear to be fixed.

**Comment by k3davis** [comment]
@joeauyeung should we re-open this issue or should I put in another?

**Comment by k3davis** [comment]
Genuine kudos to the team working on this product for your frequent and numerous fixes and features, but man, if you could fix issue this I could actually use this product 🙃

I freely confess Americans (including myself) are lazy but I just don't see my visitors looking at something like 17:00 and intuitively knowing what they are signing up for, so they just won't. It's a blocker for me.

**Comment by PeerRich** [comment]
your visitors should see this:

![CleanShot 2022-12-03 at 15 53 44](https://user-images.githubusercontent.com/8019099/205446984-196a0b89-89ab-4bd3-9db7-775cb19b3022.jpg)


the time format in your dashboard settings is only for you, not the public page

**Comment by mholt** [comment]
Do you think it could be region-based? Coming from the US, for example, 24h is the default for all the booking pages, and that doesn't make sense for most people in the US.

**Comment by karolzlot** [comment]
I have similar issue. On one of my devices by default in incognito window I see 12h , but I would like to see 24h.
Calendly works ok on the same device, so I guess this is a bug in Cal.com

**Comment by PeerRich** [comment]
there currently is a region check but its quite flaky.

happy to accept incoming PRs to improve it

**Comment by fabregas4** [comment]
This still seems to be an issue?

I have slots open at unusual times to cater for an international audience.

When someone that's local to me goes to book and sees 1:00 and 2:00 at the top of the list after selecting a day, they just assume it's 1pm & 2pm. I've had this happen so many times already in the short time I've been using Cal.com, and have to keep checking with the attendee whether they accidentally booked the wrong time or not.

**Comment by adamvnovak** [comment]
This is still an issue for me.
