### ISSUE TITLE
User lands on 404 page after login in a specific case

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2085]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

User lands on 404 page after login if he had landed on the login page due to automatic redirection from a protected page

### Steps to Reproduce

1. Go to https://app.cal.com/event-types
2. You would get redirected to https://app.cal.com/auth/login?callbackUrl=https%3A%2F%2Fapp.cal.com%2F%2Fevent-types
3. Now, log in with your credentials
4. See that you are on a 404 page https://cal.com/https:/app.cal.com/event-types

**Comment by milospuac** [comment]
Thanks for sharing this. Our engineers will address this issue
