### ISSUE TITLE
Invalid Payment URL gives 500

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2088]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Accessing an invalid payment URL gives 500. It should simply give 404

### Steps to Reproduce

1. Go to https://cal.com/payment/asdfasdf

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will have a look at this

**Comment by jaysoni-ash42** [comment]
@milospuac can i work on this issue
