### ISSUE TITLE
only show 2 avatars in avatargroup on mobile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2096]
![image](https://user-images.githubusercontent.com/8019099/157498646-ef357a6c-d959-4f9b-8b1e-3e75dc37c6ce.jpeg)

**Comment by Mayowa-Ojo** [comment]
@PeerRich I'm picking this up. I have the `pr` ready. Just want to confirm if it's just for this page alone?

**Comment by PeerRich** [comment]
> @PeerRich I'm picking this up. I have the `pr` ready. Just want to confirm if it's just for this page alone?

i think you can do it on AvatarGroup level, so it's everywhere. 

maybe we wanna show a (+2) as a bubble like here 

![image](https://user-images.githubusercontent.com/8019099/157840008-f44fe3ef-62be-4f3a-aae6-6225dc3c992d.jpeg)

**Comment by Mayowa-Ojo** [comment]
@PeerRich Okay, makes sense

**Comment by PeerRich** [comment]
fixed
