### ISSUE TITLE
The slots seem to be off and somehow related to the UTC offset 

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#2102]
Found a bug? Please fill out the sections below. 👍

I'm not sure if this is intended but the slots seem to be off and somehow related to the UTC offset 🤔
Here's the loom video, please do tell if this is intended

[Test event | Syed Ali Shahbaz | Cal.com — Mozilla Firefox - 9 March 2022](https://www.loom.com/share/c3a23ef62cfa4314b13eaf7f37386ffe)[](https://www.loom.com/share/c3a23ef62cfa4314b13eaf7f37386ffe)

[Loom](https://www.loom.com/share/c3a23ef62cfa4314b13eaf7f37386ffe)

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Create an all day availability for the event
2. If the UTC offset is not whole hours (:30, 1:30, 2:30, etc.) then the slots are off from the UTC offset time

**Comment by PeerRich** [comment]
hey, can you try the latest version?

**Comment by PeerRich** [comment]
i think @emrysal fixed this a while ago
