### ISSUE TITLE
Website doesn't load on Chrome for Android

### ISSUE THREAD

**Issue by avinal** [calcom/cal.com#2110]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The website doesn't load properly on Chrome for Android. Initially, there is some appearance but then it disappears completely. Please see the attached recording.

https://user-images.githubusercontent.com/74113200/157820282-2d487506-7e85-4bfe-9645-6d4d8dc01b30.mp4

### Steps to Reproduce

1. Open Chrome for Android
2. Put your URL. *e.g cal.com/avinal*
3. See the behavior

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The website should load without this glitch.

### Technical details

- Chrome for Android 99.0.4844.58
- Node.js version - N/A
- Android 12, Pixel 4a Build/S3B1.220218.004
- *It might be possible that the beta version of Android 12L is causing the issue.*

**Comment by milospuac** [comment]
Thanks for sharing this. Our team will have a look

**Comment by PeerRich** [comment]
hey, can you try the latest version?

**Comment by avinal** [comment]
Thanks @PeerRich, I can confirm it is working now.
