### ISSUE TITLE
Availability checker not considering rejected or cancelled events 

### ISSUE THREAD

**Issue by shengslogar** [calcom/cal.com#2134]
Greetings! New to this project. Kudos for making it OSS! ✨ 

## Issue

Cancelled/declined events are included in availability logic, meaning cancelling an event won't truly free up that calendar slot and an end user would see a "Could not book the meeting." error message on the scheduling end.

## Potential Solution

https://github.com/calcom/cal.com/blob/71c9a7b931a54ef4c7db4a4dadae5c7ad151a1a8/apps/web/pages/api/book/event.ts#L432-L438

This block should be updated to something like:

```
const calendarBusyTimes: EventBusyDate[] = await prisma.booking
      .findMany({
        where: {
          userId: currentUser.id,
          eventTypeId: eventTypeId,
          // ++++++++++++++++++++++++++++++++++++++++
          NOT: {
            status: {
              in: [
                BookingStatus.REJECTED,
                BookingStatus.CANCELLED,
              ],
            },
          // ++++++++++++++++++++++++++++++++++++++++
          },
        },
      })
      .then((bookings) => bookings.map((booking) => ({end: booking.endTime, start: booking.startTime})));

```

## Considerations
- Availability troubleshooter (`/availability/troubleshoot`) already doesn't show rejected or cancelled; this logic could be extracted to a constant to keep these in parity. `const IgnoredBookingStatuses = [ ... ];`

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our team will have a look

**Comment by bhopmann** [comment]
In addition, it would be helpful if already accepted events do not appear in the appointment selection at all.

**Comment by PeerRich** [comment]
hey, can you try the latest version?
