### ISSUE TITLE
Missing `calendar_no_busy_slots` translation

### ISSUE THREAD

**Issue by shengslogar** [calcom/cal.com#2135]
### Issue Summary

Translation referenced here is missing from `en/common.json`:

https://github.com/calcom/cal.com/blob/8c4eed2bbc80f53a2fce96a490bf8cbd9f168ce9/apps/web/pages/availability/troubleshoot.tsx#L93

### Steps to Reproduce

1. Go to `/availability/troubleshoot` endpoint, select date with no events.

### Potential solution
```
"calendar_no_busy_slots": "All clear!"
```

### Technical details

N/A

**Comment by milospuac** [comment]
Thank you for addressing this

**Comment by PeerRich** [comment]
calendar_no_busy_slots has been translated
