### ISSUE TITLE
`You have no {{status}} bookings` unexpectedly capitalized

### ISSUE THREAD

**Issue by shengslogar** [calcom/cal.com#2136]
### Issue Summary

Status shouldn't be capitalized.

https://github.com/calcom/cal.com/blob/7add1f44e99480cec42d34b1e46efb1c71f0697b/apps/web/public/static/locales/en/common.json#L271-L272

<img width="1387" alt="Screen Shot 2022-03-14 at 02 36 39" src="https://user-images.githubusercontent.com/4350009/158134890-4f2bddf7-a7ad-44e6-829b-57b6fb135b51.png">

### Steps to Reproduce

1. Navigate to `/bookings/upcoming` when list is empty

### Proposed Solution
```
"no_status_bookings_yet": "No {{status.toLowerCase()}} bookings, yet",
"no_status_bookings_yet_description": "You have no {{status.toLowerCase()}} bookings. {{description}}",
```

### Technical details

N/A

**Comment by miguelnietoa** [comment]
Hey @shengslogar, why didn't you send a PR? you already have the solution haha
