### ISSUE TITLE
Notify me when sooner availability becomes available

### ISSUE THREAD

**Issue by vikramraja** [calcom/cal.com#2148]
### Is your proposal related to a problem?

I'm always frustrated when I get a scheduling link and the closest time is 2 weeks away

### Describe the solution you'd like

I would love an option to be notified when a sooner date becomes available, so I can meet with the person sooner. 

### Describe alternatives you've considered

I've considered asking the other person to notify me if any closer dates become available. Sometimes they are not aware that their calendar links are so booked up. 

### Additional context

(Write your answer here.)

**Comment by agustif** [comment]
Intresting use case, I wonder how this would work.

As an end-user, you see 2 weeks full, and want to provide your contact details and be notified if anything before that opens up.

This would require we ask you for your details, and save the lastAvailableDate (you didn't want to book)
And then would need some kinda recurring task /cron job whatever to check if any available date sooner than that is available. and notify you then sending you an email.

Maybe when virtual cached calendar lands this is easier, not sure if the feature is too niche /complicated to implement though

**Comment by PeerRich** [comment]
not planned yet. will revisit later
