### ISSUE TITLE
Bitcoin / BTCPay Server App

### ISSUE THREAD

**Issue by montespertoli-paktribune** [calcom/cal.com#2154]
### Is your proposal related to a problem?

Unfortunately, there is no self-hosted, open-source payment processor for cryptocurrencies.

### Describe the solution you'd like

Integration of the [BTCPay Server](https://btcpayserver.org/) into cal.com. Similar to the integration of Stripe.

### Describe alternatives you've considered

It would also be possible to add a field for a Bitcoin address. But this has the disadvantage that it supports address reuse. This is bad for the privacy of both sides.

### Additional context

[API documentation of the BTCPay Server](https://docs.btcpayserver.org/API/Greenfield/v1/)

**Comment by PeerRich** [comment]
we're likely only supporting lightning for accepting bitcoin due to the low prices for events

**Comment by montespertoli-paktribune** [comment]
The BTC Pay Server is made for all types of Bitcoin transactions. It supports Lightning and On Chain. The important thing is that it can be self-hosted like cal.com. 

coincharge has a public server that can be used for demo purposes. Just register and try.
https://btcpay.coincharge.io

https://coincharge.io/en/btcpay-server/
https://coincharge.io/en/btcpay-server-hosting/

**Comment by PeerRich** [comment]
Oh i was unaware that it supports LN! Thats epic. lets do it. Do you have experience implementing it?

**Comment by montespertoli-paktribune** [comment]
No, sadly i am not a web developer.

**Comment by PeerRich** [comment]
this is in progress!

**Comment by montespertoli-paktribune** [comment]
nice 👍

**Comment by PeerRich** [comment]
https://cal.com/apps/alby

**Comment by chaosyoga** [comment]
> https://cal.com/apps/alby

this isnt BTCPAY, which is self-hosted and open source (unlike alby)

BTCPay is much more powerful and versatile as it allows full control over your funds
