### ISSUE TITLE
Duplicate event type does not really duplicate the event type

### ISSUE THREAD

**Issue by mxwlf** [calcom/cal.com#2176]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
**Duplicate event type does not really duplicate the event type**

Given that I have an event type already with some extra parameters, such as fields to ask to the requestor, minutes in advance restrictions, etc. 

The expectation would be that once I have these set up for one event type I can simply duplicate it and just change the duration to create multiple similar event types that vary just in the time requested.

However, the newly created event doesn't really contain most of the values of the original event type. Fields I have observed are:

- Additional Inputs
- Opt-in booking
- Minimum booking notice

These are the fields I have changed from the default values so this list should not be considered exhaustive.

### Steps to Reproduce

Let's put as example:

![](https://i.imgur.com/KP4EwpM.png)

Given the above existing event type and its couple of extra fields.

- Go to https://app.cal.com/event-types > click on [...] > click on "Duplicate"

![](https://i.imgur.com/GmIIb0Q.png)

- Changing the basic fields and hitting *Continue*:

![](https://i.imgur.com/q4hxNDX.png)

Then clicking on *Show advanced settings*:

![](https://i.imgur.com/uzVWBYB.png)

As you can see the newly created event lacks the fields that were in the original event.

### Technical details
- My username is adrian@adrianpadilla.net
- My calendar alias is [https://www.cal.com/adrian](https://www.cal.com/adrian)

**OS**:
- MacOS Monterey
- System Version:	macOS 12.3 (21E230)
-  Kernel Version:	Darwin 21.4.0
-  Boot Volume:	ssd
-  Boot Mode:	Normal
-  Computer Name:	macwolf
-  User Name:	Adrian Padilla Vega (adrian)
-  Secure Virtual Memory:	Enabled
-  System Integrity Protection:	Enabled
**neofetch info**:
- OS: macOS 12.3 21E230 x86 64
- Host: MacBookPro14,3
- Kernel: 21.4.0
- Uptime: 16 hours, 39 mins
- Packages: 178 (brew)
- Shell: zsh 5.8
- Resolution: 1088×1920, 1080x1920, 1088x1920
- DE: Aqua
- WM: Quartz Compositor
- WM Theme: Blue (Dark)
- Terminal: tmux
- CPU: Intel 17-7928H0 (8) @ 3.10GHZ
- GPU: Intel HD Graphics 630, Radeon Pro 568
- Memory: 9786MiB 16384418
  
  
**Browsers**:
- Safari, Version 15.4 (17613.1.17.1.6)
- Chromium, Version 100.0.4869.0 (Developer Build) (x86_64)

**Hardware**:
- MacOS Monterey
- Model Name:	MacBook Pro
- Model Identifier:	MacBookPro14,3
- Processor Name:	Quad-Core Intel Core i7
-  Processor Speed:	3.1 GHz
-  Number of Processors:	1
-  Total Number of Cores:	4
-  L2 Cache (per Core):	256 KB
-  L3 Cache:	8 MB
-  Hyper-Threading Technology:	Enabled
-  Memory:	16 GB
-  System Firmware Version:	447.80.3.0.0
-  OS Loader Version:	540.100.7~14
-  SMC Version (system):	2.45f5
-  Serial Number (system):	C02WR0FXHTDH
-  Hardware UUID:	DB711B3A-F6D8-5900-9135-84697E93B73F
-  Provisioning UDID:	DB711B3A-F6D8-5900-9135-84697E93B73F

### Log from Chromium

[app.cal.com-1647484546174.log](https://github.com/calcom/cal.com/files/8280970/app.cal.com-1647484546174.log)

**Comment by denik1981** [comment]
Thanks for sharing this! 

It might be worth to instead of having the duplicate event type feature,  have a `set as a template` feature for the events that you create recurrently and shared similar settings.

**Comment by arthur1041** [comment]
I can work on this issue.

**Comment by arthur1041** [comment]
I can work on this issue.

**Comment by PeerRich** [comment]
hey, can you try the latest version again?
