### ISSUE TITLE
RFC: Recurring Events

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2180]
## Goals:

- offer customers to create an event-type with recurring events

## Target customers / use cases: 
- office hours
- workshops
- recurring therapy
- coaching
- gym memberships
- yoga lessons
- ...

![image](https://user-images.githubusercontent.com/8019099/158838407-129f3014-6dba-4f7c-90d9-680f421e3867.png)

## MVP:
for now we will not use the native "recurring event" APIs of each calendar and instead send `n` invites on a predefined schedule:
 
- we will "fake" recurring events by sending one calendar invite for each slot (i.e if monday 1. March 16:30 passes, then it sends a new invite for 8th March 16:30, until unsubscribed)

- recurring events should "overwrite" your own calendar, otherwise it'll be a mess to calculate the availabilty

## Booking Page:

![image2](https://user-images.githubusercontent.com/8019099/158836448-840cfd94-5f22-479a-8c75-3f327f25ae69.png)
![image3](https://user-images.githubusercontent.com/8019099/158836440-c924fb62-032c-4c40-af66-e4e07870b2a0.png)

![image4](https://user-images.githubusercontent.com/8019099/158836432-fd037032-31bc-46bc-b483-378002e8af53.png)

## Customer Story:

"The use case is that if when a client signs up, we schedule them for a recurring therapy session once a week for 16 weeks (the standard course of a treatment plan). We may need to update the individual calendar invites if they need to say change a wednesday apptment to a thurs, or update the entire set of recurring events"

<img width="344" alt="image" src="https://user-images.githubusercontent.com/8019099/162042360-f5a4cbd9-e323-483a-b9df-e27e60a04158.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/8019099/162042276-9861b24d-3ea3-4581-b6a5-d5d9c18f0c71.png">

**Comment by leog** [comment]
@PeerRich Wanted to gather information about what's out there when it comes to recurring events. I found Google's "Bookable Appointment Schedule" feature which is a revamped version of what's used to be the Slots feature I used in the past. I think it relates a lot to a schedule (option 2) rather than an event type option (option 1).

In terms of its implementation, we already have an interface to describe calendar apps, we can extend it to implement the creation of recurring events if they support it, otherwise, in its implementation a workaround can be put in place. Summoning @zomars for his input. Also, reminding @Jaibles of the `needs design` tag 😜 

Here is a screenshot of all its options:
![Google_Bookable_Appointment_Schedule](https://user-images.githubusercontent.com/467258/161402850-9804c823-a955-4cad-b8dd-528161d689aa.png)

**Comment by PeerRich** [comment]
the more i think of it, the more I'd like to have "recurring availability" in app.cal.com/availabilty than in /event-types

thoughts @baileypumfleet @Jaibles ?

**Comment by PeerRich** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/8019099/161403753-107d1e84-cff8-422e-8184-e05cf1e807dc.png">

**Comment by PeerRich** [comment]
a recurring schedule should also overwrite/ignore connected calendars

**Comment by PeerRich** [comment]
however, I wonder there is a reason to use a recurring schedule more than for one event type ... 🤔 probably not.

normal "Working Hours" you would use multiple times for different event-types.

recurring "Yoga Classes" probably not

**Comment by PeerRich** [comment]
and if it's one availability for one event-type, we may as well have the recurring logic in /event-types

**Comment by leog** [comment]
Just to be clear, inferring from information in the ticket, screenshots and chats with you @PeerRich:
1. having an option to have an event type be recurring and provide a number input for `n` occurrences will set how many times an event when booked is going to be repeated
2. when someone selects any day and time, that will be the repeated day and time each week for `n` times into the future
 - Should we make explicit the `n` times when we show "Every X day at Y time" to also say "for `n` times"? @PeerRich @Jaibles 
3. when one repetition ends, send a new invite for the next occurrence 
 - This means that there will be no way to change following instances before the new invite is sent. If I'm the owner and the client asks me to reschedule an occurrence two weeks from now, that will no be possible. Maybe we can just create all booking occurrences at once and group the corresponding emails to just one to say it's a recurring event. Then the owner can go into a booking in the future and reschedule it, triggering an email notification for just that occurrence.

**Comment by PeerRich** [comment]
> 1. having an option to have an event type be recurring and provide a number input for `n` occurrences will set how many times an event when booked is going to be repeated

yes, example: 16

> 2. when someone selects any day and time, that will be the repeated day and time each week for `n` times into the future
> 
> * Should we make explicit the `n` times when we show "Every X day at Y time" to also say "for `n` times"? @PeerRich @Jaibles

yes, explicit "how many times?"


> 3. when one repetition ends, send a new invite for the next occurrence

this could be a check box. some people want infinite recursion, some people want to sell "16 events with me"

**Comment by leog** [comment]
@Jaibles @PeerRich this is what I have at the moment, thought you guys might want to see it, any change request is welcome.

---

Event Type configuration option:
 - When the checkbox is unchecked, the "Every ___ week" is hidden
 - When the number is greater than 1, "week" turns into "weeks"
<img width="533" alt="Notification_Center" src="https://user-images.githubusercontent.com/467258/163886753-412c7ffd-7615-4e9a-8e20-a91e1c8febfc.png">

---

Event Type List:
 - When the number of weeks is greater than 1, shows "every X weeks"
<img width="763" alt="Notification_Center" src="https://user-images.githubusercontent.com/467258/163886893-80c24d15-ebcc-40f1-977c-71d859d127f5.png">

**Comment by PeerRich** [comment]
@leog has a PR been opened for this?

**Comment by Jaibles** [comment]
Chat continued in Twist and sharing [Figma link here](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=5807%3A99407) for reference.

**Comment by leog** [comment]
> @leog has a PR been opened for this?

Not yet. Only the FE I presented was implemented while definitions on the functionality settles to then tackle backend. I can create a draft PR anyway if needed.
