### ISSUE TITLE
Follow up for Schedules visual fixes

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#2185]
![image](https://user-images.githubusercontent.com/8019099/158844027-e23a075f-6547-43f1-80a6-2db6fd1804ac.png)

NIT: lack of padding and I believe we have an` <EmptyScreen/>` component already no?

lets reuse this:

![image](https://user-images.githubusercontent.com/8019099/158844341-05a13b52-a5b8-4177-a1e8-fd52fb57716f.png)

missing padding left on mobile 

![image](https://user-images.githubusercontent.com/8019099/158845668-6577d679-f4a3-4610-8f85-94505b1abd86.png)

weird scroll behavior, maybe some h-full or similar usage?

https://user-images.githubusercontent.com/8019099/158845888-c1b84f98-e8f0-46db-a7c6-0955e75e258b.MOV

_Originally posted by @PeerRich in https://github.com/calcom/cal.com/pull/2150#issuecomment-1071030165_

**Comment by PeerRich** [comment]
merged
