### ISSUE TITLE
Payment amount input leading 0

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#2192]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

While entering payment amount of stripe it displays a 0 before the selected amount.

![image](https://user-images.githubusercontent.com/4461358/158896098-5e736ae9-d0c7-49e8-af51-005d99988fad.png)

### Steps to Reproduce

1. Need stripe connected account
2. Go to event-types/[id], advanced settings
3. Try to edit payment amount input field

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
It's probably not handling value as a number.

### Technical details

- Chrome latest build version

**Comment by Toledodev** [comment]
Can you explain to me how i connect the "stripe account"?
