### ISSUE TITLE
Login auth callback is not fully sanitized.  

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#2196]
### Issue Summary

A double forward slash is injected into the callback and next-auth is sounding about it.

![image](https://user-images.githubusercontent.com/66160623/158947691-6126d5fa-cdfc-4f63-b912-ecd2e45fef27.png)

### Steps to Reproduce

1. Clean up your session.
2. Login with example credentials, or your own
3. Check the console.

Seems next-auth is fixing this for us despite complaining about it. Probably by compressing the double forward slash into one. 
I suspect this because redirection to the home page (event-types) is done well but I think this is a minor bug that can potentially lead to some other issues if we don't take care of it.

**Comment by milospuac** [comment]
Hey Demian. Thanks for the pull request, our team will review it.
