### ISSUE TITLE
[CAL-505] availability: date overwrite

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2199]
the date overwrite feature needs more visuals, @Jaibles 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/8019099/158982744-2b076a8d-5a06-45d3-a1dd-702902c8aab7.png">

<sub>[CAL-505](https://linear.app/calcom/issue/CAL-505/availability-date-overwrite)</sub>

**Comment by Jaibles** [comment]
@PeerRich let me know what you think when you've had a chance to review 
https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=4884%3A35105

**Comment by PeerRich** [comment]
> Designs here: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=4884%3A35105

left comments in twist

**Comment by farzaank** [comment]
Any ETA on this? Thanks in advance.

**Comment by Jaibles** [comment]
Designs updated here: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=15827%3A123562

**Comment by Jaibles** [comment]
Also requested here: https://github.com/calcom/cal.com/issues/3239

**Comment by PeerRich** [comment]
@emrysal this is marked as blocked, how can we help?

**Comment by emrysal** [comment]
Draft PR of WIP up @ https://github.com/calcom/cal.com/pull/4614

**Comment by aasargsian** [comment]
We are really looking forward to date overrides! 
Our doctors rarely have standard schedules and we typically only work with one-off availabilities.
Managing doctors' schedules once we switch to Cal.Com can become much more complicated without date overrides since we'll need to block a lot of slots out from their Google calendars.
@PeerRich @emrysal

**Comment by Jaibles** [comment]
@aasargsian we're aiming to include this in our 2.3 product release on the 15th of this month.

**Comment by aasargsian** [comment]
That would be just great! @Jaibles

**Comment by Jaibles** [comment]
@ZachTheDev our releases go out on  the 15th of each month. We're hoping to have it in our next release (tomorrow) although it's still a work in progress. If you've signed up for the product you should get our monthly product newsletter which will confirm what's been shipped this month.

**Comment by emrysal** [comment]
@ZachTheDev Follow the PR @ https://github.com/calcom/cal.com/pull/5991
