### ISSUE TITLE
RFC: Embedded Bookings

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2221]
### WIP:
https://github.com/calcom/cal.com/pull/2227

## Right now two options are there ## 
* Standard Iframe Embed
* Responsive Full-Screen Iframe Embed

**Known Issues**
- ~~Doesn't inherit the site theme~~
- ~~height problems with iframes (iframes commonly don't know the height of their content)~~
- performance (the iframe loads the entire Next.js app)
- Issues in accessing Cookies/WebStorage in a third-party context.[ The current stance of various browsers](https://www.cookiestatus.com/). E.g. see that in [Chrome Incognito, the booking page goes blank.]((https://codesandbox.io/s/full-screen-iframe-embed-forked-pixi3n?file=/index.html))
- ~~lack of more advanced embeds such as a bubble in the bottom right like intercom that opens cal as a dialogue~~

**What iframe does good**
- Automatic Styles Encapsulation
- Restrictions over what we want to offer in the free plan e.g. do we want to restrict full theming in the free plan?
- Reuse of same non embed booking page

## What do we want? ## 
* ~~Exists as a package in monorepo~~
* Installable as 
   * ~~React Component. Other framework-specific packages can be owned by our awesome community.~~
   * ~~Script Embed <script src="">~~
- **Improvements** 
	- ~~A **Post-messaging based API** that allows the user~~
		- To control the frame embed dynamically 
			- ~~Theming and Embed Component Styling~~
			- what to hide e.g. Calendly provides an option to hide Event Details in embeds.
		- ~~to receive events on what is going on in the frame~~
       		- e.g. [Booking Successful](https://github.com/calcom/cal.com/pull/2087#issuecomment-1067956622).
    		- ~~Analytics Related - Visited Events Listing, Selected 30min, chosen slot, etc.~~
	- ~~A configuration that would allow some init data to be passed to embed e.g. Theming!!~~
- Don't access WebStorage directly - If need be wrap that in try-catch and assume that it might not be available. 
* Improved Performance
  * Prevent page load from event-types page to book page.
  * Lighthouse Score improvements for all pages(event-types listing already sorted). 

**To Explore**
   - ~~Compatibility with other frameworks - How to ensure that any framework other than React can also use it?[We will be in iframe. So no compatibility issue]~~
   - ~~Iframe height problems can be solved by using a script at the top responsible for managing the iframe~~
   - ~~Full app loading is not mostly a problem with SSR. We would anyway have to improve the performance of non-embed booking pages and that would automatically improve performance for embed. Hydration is a performance problem that [React team is working on already](https://github.com/reactwg/react-18/discussions/37)[We would focus on performance for booking pages separately]~~
- Styling
	- Popular Customizations can be provided as the configuration in app. 
	- ~~Advanced CSS customizations can be solved by allowing user-provided CSS files inside the embed.[We are exposing what components and what properties can be modified]~~
- If need be a similar user given JS file can be allowed. Security-wise we can ensure those JS and CSS files are allowed only in embed and only if it is on a whitelisted domain. 
- ~~If the embed is to be opened on a user action we can use [page prefetching](https://addyosmani.com/blog/prefetching/) so that it's all there before the action.~~ 
- we can just allow framing booking pages and prevent everything else. Additionally, maybe allow framing only on whitelisted domains
- ~~We can still use tailwind for styling. But I am concerned about how advanced theming can be done by users if there are no classes. We would probably need classes also that tailwind doesn't require at all~~.
- iframe is automatically framework agnostic. If as a developer I am concerned about security, [iframe sandbox](https://www.html5rocks.com/tutorials/security/sandboxed-iframes/) is already there. 
- My only real concern with iframe is browsers' stance towards cross-site iframes. This can be solved by using first-party storage only. If embed needs to persist some data, its script counterpart would do that for it(post messaging to the rescue)

# Conclusion 
- We should use iframe only which would be managed by a script on the user website.
- Developer would have to install just that script and iframe would be managed by it. Framework specific packages would make that script installation and placement of iframe easy.

**Comment by PeerRich** [comment]
great RFC! Lets get going

**Comment by hariombalhara** [comment]
If the booking page is configured with a dark theme. Can the embedded booking page be configured with a light theme or system preference? 
Asking because it’s possible that the user's website doesn’t support dark mode and he would want dark mode for booking but his website doesn’t support it yet and keeping the booking page dark in embed would make it look out of place.

**Comment by PeerRich** [comment]
> If the booking page is configured with a dark theme. Can the embedded booking page be configured with a light theme or system preference? Asking because it’s possible that the user's website doesn’t support dark mode and he would want dark mode for booking but his website doesn’t support it yet and keeping the booking page dark in embed would make it look out of place.

I think that should be a very strong requirement to give people the power to decide what team to apply

**Comment by hariombalhara** [comment]
I have also added namespacing support allowing a website to embed multiple users' calendar on the same page. There would be separate roads for these namespaces. Any one subscriber to road-1(namespace-1) would only be able to see namespace-1 events. 

For anyone not interested in multiple namespaces api looks like namespaces don't exist. 

An example implementation is now on testpage in the branch.

**Comment by hariombalhara** [comment]
Here is the current state for those interested :)

## Embed Demo

![Embed Demo](https://user-images.githubusercontent.com/1780212/159699805-fe7831f4-f98b-40e7-9eda-e95338cc6bfb.gif)


## Preload/Prerender Demo

![prerender-demo](https://user-images.githubusercontent.com/1780212/159699888-245d2869-4443-4883-ab86-81a2b1ac440f.gif)

**Comment by PeerRich** [comment]
super cool!!

**Comment by hariombalhara** [comment]
This is a UI Styling demo for embed https://www.loom.com/share/222e5be836424917a3f9da0e74e75d70

**Comment by hariombalhara** [comment]
Bulk API Support also added.

<img width="917" alt="Screenshot 2022-03-25 at 6 51 51 PM" src="https://user-images.githubusercontent.com/1780212/160128544-53fbb988-d6e3-4857-8470-fc984e4c09d7.png">

**Comment by PeerRich** [comment]
@hariombalhara only the script generator missing, right?
<img width="714" alt="image" src="https://user-images.githubusercontent.com/8019099/162585959-64bd5a06-3888-433f-a636-a2d02e0bdd12.png">

**Comment by hariombalhara** [comment]
Majorly, yes, if we leave the embed for authenticated pages. 
Here is a list of things to be done. 
https://github.com/calcom/cal.com/tree/main/packages/embeds/embed-core#known-bugs-and-upcoming-improvements

**Comment by PeerRich** [comment]
@hariombalhara at what point do we close this RFC as finished and break out the open tickets into new issues?

**Comment by hariombalhara** [comment]
It can be done even now. But will close it with my next PR merge.

**Comment by duarteocarmo** [comment]
Any expected date for this embedding? I would love to have it :)

**Comment by hariombalhara** [comment]
@duarteocarmo You can start using it even now. These are the docs https://docs.cal.com/integrations/embed. 
If something is amiss, just let me know.

This is the PR I am working on which should be merged next week https://github.com/calcom/cal.com/pull/2499

**Comment by duarteocarmo** [comment]
Ah super! 

I was actually mentioning from a user perspective. 

I have a cal.com link working - but there is no option to get an iFrame?

**Comment by hariombalhara** [comment]
Oh, that is still pending in UI. I am hopeful this would be done in coming 2-3 weeks. A snippet generator is coming along with it.

But if you need to embed on your website it is still possible, with the steps mentioned in the doc.

**Comment by duarteocarmo** [comment]
For sure - thanks @hariombalhara  for all the help! Super product this is :)

**Comment by hariombalhara** [comment]
@duarteocarmo You can now get the embed link for an event type from UI.
See this loom https://www.loom.com/share/9741daa1df7446c2a8cec37454380f0b

**Comment by hariombalhara** [comment]
That was lightning fast 🚀

**Comment by niklasgrewe** [comment]
@hariombalhara looks really good. One question about this: I currently use the React component in my Remix app like this:

```js
import Cal from "@calcom/embed-react";

const MyComponent = () => (
  <Cal
    calLink="pro"
    config={{
      name: "John Doe",
      email: "johndoe@gmail.com",
      notes: "Test Meeting",
      guests: ["janedoe@gmail.com"],
      theme: "dark",
    }}
  />
);
```
it is also possible with this react component to listen to actions, if for example the booking was successful. The [documentation](https://developer.cal.com/embed/set-up-your-embed#actions) seems to only cover js at the moment:

```html
<script>
Cal("on", {
  action: "ANY_ACTION_NAME",
  callback: (e)=>{
    // `data` is properties for the event.
    // `type` is the name of the action(You can also call it type of the action.) This would be same as "ANY_ACTION_NAME" except when ANY_ACTION_NAME="*" which listens to all the events.
    // `namespace` tells you the Cal namespace for which the event is fired/
    const {data, type, namespace} = e.detail;
  }
})
</script>
```

**Comment by hariombalhara** [comment]
Yeah it is supported with that too. If you use the listener after the import Cal should be defined globally

**Comment by atanaka0313** [comment]
> Yeah it is supported with that too. If you use the listener after the import Cal should be defined globally

Could you please explain me how to use action listener in react by example? Thanks in advance.

**Comment by AmjadTotalPresent** [comment]
> Yeah it is supported with that too. If you use the listener after the import Cal should be defined globally

@hariombalhara Hi, will this work in React Native too?

**Comment by hariombalhara** [comment]
No. It isn't supported there. This is native JS events.

**Comment by hariombalhara** [comment]
@yueymiqua Are you talking about `bookingSuccessful` event fired by embed.? 
<img width="841" alt="Screenshot 2022-12-13 at 11 30 53 PM" src="https://user-images.githubusercontent.com/1780212/207409907-c49cc7cc-621e-49a8-9b22-fd7e3ccaef1f.png">

**Comment by yueymiqua** [comment]
> @yueymiqua Are you talking about `bookingSuccessful` event fired by embed.? <img alt="Screenshot 2022-12-13 at 11 30 53 PM" width="841" src="https://user-images.githubusercontent.com/1780212/207409907-c49cc7cc-621e-49a8-9b22-fd7e3ccaef1f.png">

Yes, that is correct!

**Comment by hariombalhara** [comment]
It should be quick to add bookingUid there. Maybe open an issue or even better open a PR :)
booking uid is readily available at the place `bookingSuccessful` event is fired
<img width="1106" alt="Screenshot 2022-12-13 at 11 43 15 PM" src="https://user-images.githubusercontent.com/1780212/207412411-28dad4ea-efe5-4cf1-b538-85fdda93dcab.png">

btw what's your usecase for reading booking uid ?
