### ISSUE TITLE
Meeting Booked by User1 with User2 is sending wrong email. Also, User2 didn't get notification for meeting booking.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2224]
I had scheduled a meeting with [/bailey](https://cal.com/bailey). It is showing as unconfirmed which I am assuming that it is because Bailey didn't confirm it.

But I got an email at the time of booking (which I now read thoroughly) that Hariom needs to confirm the booking when in fact I had booked the meeting. I had assumed Baily would need to confirm it 😃 

The email subject is also wrong.

Also, @baileypumfleet confirmed that he didn't get the meeting invite.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

- I went to https://cal.com/bailey and simply booked a 15min meeting

Meeting shown as unconfirmed
<img width="1528" alt="Screenshot 2022-03-21 at 5 43 04 PM" src="https://user-images.githubusercontent.com/1780212/159260484-55942f2d-eb8b-4f0b-afe9-a842c7b71eb1.png">

The Email that I received
<img width="1499" alt="Screenshot 2022-03-21 at 5 44 50 PM" src="https://user-images.githubusercontent.com/1780212/159260508-da168bdf-36b9-4690-920b-c4399fc862ce.png">

**Comment by Jaibles** [comment]
I can't recreate this issue. Just tested a booking with @baileypumfleet
<img width="1458" alt="CleanShot 2022-05-18 at 21 04 37@2x" src="https://user-images.githubusercontent.com/4536123/169146375-70811fbc-c0f8-42ab-9130-3cc1f8e9d541.png">

**Comment by hariombalhara** [comment]
Looks like it got fixed. Closing it.
