### ISSUE TITLE
[CAL-73] If a meeting is not booked, send a reminder email that if you are expecting the meeting to happen, it is not happening

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2225]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I booked a meeting with a user 2 days in advance and that user was supposed to confirm the booking. The day came and I thought the meeting was booked(my fault I should have checked) but cal.com should also notify me about this so that it doesn't create confusion.

An actual scenario where it happened https://github.com/calcom/cal.com/issues/2224

**Comment by coachlivinglegend** [comment]
@LuisChiej how do I get the integration configurations I'll need for the email integration?

**Comment by joeauyeung** [comment]
@Jaibles @hariombalhara when would be the ideal time to send the email to the attendee that the booking hasn't been confirmed? I'm thinking the day of.

**Comment by hariombalhara** [comment]
@Jaibles would be the best person for this. 

As a user, I would expect atleast one email a day before meeting day and probably on the meeting day.

**Comment by PeerRich** [comment]
@CarinaWolli can this be done with workflows?

**Comment by CarinaWolli** [comment]
> @CarinaWolli can this be done with workflows?

@PeerRich We could add a trigger for it. But if it is essential enough and if it is something that users would expect to happen then we should probably implement it in general for opt-in bookings

**Comment by PeerRich** [comment]
oh I misread the issue, yeah this should happen outside of workflows!
