### ISSUE TITLE
"Create events on" dropdown in Integrations UI is broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#2226]
### Issue Summary

- The "Create events on" dropdown goes over 2 lines with longer emails.
- There is also an issue where there appears to be an input in an input 

### Steps to Reproduce

1. Go to Integrations
2. Look at the "Create events on" dropdown
3. With a long email it goes over 2 lines
4. Also look at it with a shorter email - there appears to be a dropdown within a dropdown appearing.

Breaks with longer emails
<img width="787" alt="CleanShot 2022-03-21 at 12 33 49@2x" src="https://user-images.githubusercontent.com/4536123/159261851-1ba8e0ce-a25e-4939-b243-d79b608bf9be.png">

Input in an input
<img width="414" alt="CleanShot 2022-03-21 at 12 38 00@2x" src="https://user-images.githubusercontent.com/4536123/159262821-c8104334-c9a0-404c-aa41-64ebcc380afc.png">

**Comment by sean-brydon** [comment]
I am unable to replicate this - Guessing it could have been fixed? 

![CleanShot 2022-03-27 at 22 39 37](https://user-images.githubusercontent.com/55134778/160302153-1b0ebcff-30cc-4e01-a528-ad1b98b39a2e.png)
![CleanShot 2022-03-27 at 22 39 52](https://user-images.githubusercontent.com/55134778/160302163-0cd343e8-8196-488f-9ccc-9644d337b683.png)

I believe this came from @zomars commit https://github.com/calcom/cal.com/commit/785b156f951d03f824c2df561776bcfee4d6acea
