### ISSUE TITLE
RFC: Rescheduling bookings

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#2228]
### Overview

As a cal.com user I want to be able to reschedule bookings. There are two ways I may want to do this.
- I may want to choose a new time myself and effectively edit the booking.
- I may want to request that the scheduler picks a new time on my calendar (immediately cancelling the original booking)

### Describe the solution you'd like

The proposed solution is detailed in [this Figma file.](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=4566%3A34152) and explained in [this Loom](https://www.loom.com/share/8ed3fed021be441a9db92a6d6a578437).

### Additional context

This functionality is required before we can work on both the "wipe my cal" & "vital" app so however we implement this functionality will need to take those into consideration.

**Comment by denik1981** [comment]
I like the idea @Jaibles. I would like to suggest later extending this feature (version 2?) and giving the organizer also the option to mark available time slots where he suggests rescheduling this meeting and preventing going all over again with the rescheduling flow. So the UI might should to the scheduler the dates that are suggested by the organizer as mandatory or as optional (not sure about this). I can imagine many use cases where someone would like to bypass the general availability rules set, and define a special one linked to a particular Scheduler.

**Comment by Jaibles** [comment]
@denik1981 yea nice idea, this also overlaps with some other features we're designing in our very near-term roadmap which could be utilised to offer exactly what you mention. Will keep it in mind to include them for rescheduling when I look at them this week. Thanks!
