### ISSUE TITLE
"Undefined" appearing as event location in confirmation email when rescheduling

### ISSUE THREAD

**Issue by shengslogar** [calcom/cal.com#2229]
### Issue Summary

Event is improperly polluted by update API, causing the location type > label mapping to fail.

Email screenshot:

<img width="303" alt="Screen Shot 2022-03-21 at 11 31 32" src="https://user-images.githubusercontent.com/4350009/159330719-d69be820-1c52-450d-bfec-f484663cb19b.png">

### Steps to Reproduce

1. Schedule event.
2. Reschedule event.
3. Error occurs in rescheduled event confirmation.

### Technical details

The following line should be removed to match `EventManager.create`:

https://github.com/calcom/cal.com/blob/c437f15868c2f778352b47b0f8da74e2bf87354b/apps/web/lib/events/EventManager.ts#L221

This allows this code to function as expected:
https://github.com/calcom/cal.com/blob/f7dd0edf2fe7f4cde4f1204695424a2bf8b33eb8/apps/web/lib/emails/templates/organizer-scheduled-email.ts#L302-L308

**Comment by milospuac** [comment]
Thanks for reporting this. Our team will have a look

**Comment by bezalel001** [comment]
I am taking up this issue

**Comment by gitstart** [comment]
Hey @shengslogar! The issue is not reproducible anymore. Here's a video trying to reproduce the issue https://www.loom.com/share/d472bb6c080e4cf8b7f61551abd3fcc8
cc: @milospuac @Jaibles

**Comment by PeerRich** [comment]
i believe this has been fixed a long time ago
