### ISSUE TITLE
Bad UX when user wants to set the default Event Type Title

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2245]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
See https://www.loom.com/share/003c71cbe105426192b2b35adbe27904
A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce
1. I went to fix my even-type title.
2. I wanted to keep the default one(by cal). So I deleted mine and it showed me the default value
3. But I couldn't save it. No error was shown that you need to actually enter that value yourself.

**Comment by jaysoni-ash42** [comment]
@hariombalhara  can i work on this issue?

**Comment by hariombalhara** [comment]
Sure. Thanks 🙏
