### ISSUE TITLE
booking page: reduce routes (page changes) and use shallow routes instead

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2247]
https://user-images.githubusercontent.com/8019099/159696925-9c8f55a6-81c5-44d6-9cfa-456a079b1fed.mov

**Comment by hariombalhara** [comment]
@PeerRich I just found out that the redirect is actually caused only on `cal.com` and not on` app.cal.com`
Try booking through `app.cal.com` to see the difference.

See the difference in number of Document requests that are sent
<img width="1789" alt="Screenshot 2022-03-25 at 2 22 21 PM" src="https://user-images.githubusercontent.com/1780212/160088109-dd7e2f1d-8e24-4065-b470-167d5b26292c.png">

<img width="1788" alt="Screenshot 2022-03-25 at 2 22 49 PM" src="https://user-images.githubusercontent.com/1780212/160088150-11d551d1-a716-4d77-b083-968d4c16d434.png">

**Comment by hariombalhara** [comment]
@zomars @PeerRich The reason for redirects that I accidentally found out today(not sure if you guys know) is that _data URLs are not handled by rewrites which is why they give 404 which causes the page to reload.
This is somewhat related https://arihantverma.com/posts/2021/07/18/workaround-nextjs-data-urls-same-domain-multiple-apps/ but not exactly the same thing.

**Comment by PeerRich** [comment]
> @zomars @PeerRich The reason for redirects that I accidentally found out today(not sure if you guys know) is that _data URLs are not handled by rewrites which is why they give 404 which causes the page to reload.
> 
> This is somewhat related https://arihantverma.com/posts/2021/07/18/workaround-nextjs-data-urls-same-domain-multiple-apps/ but not exactly the same thing.

no way that's a great discovery.

any quick fixes? or do we need to change the entire rewrite system?

**Comment by zomars** [comment]
A temp workaround could be what I've proposed so we prioritize the web app and rewrite the marketing pages on top of it.

**Comment by PeerRich** [comment]
@zomars wanna do that? is there a way we can test this on staging? cal.dev

**Comment by zomars** [comment]
Yeah let's open a ticket for it.

**Comment by PeerRich** [comment]
@emrysal you said we can fix this by extracting the booking page? maybe we should hotfix this before

**Comment by PeerRich** [comment]
three options:
- fix 404
- reverse the redirect
- extract into its own package

**Comment by hariombalhara** [comment]
@PeerRich @zomars what should we do with it?

**Comment by zomars** [comment]
This will be significantly improved in #3035

**Comment by PeerRich** [comment]
@emrysal @hariombalhara lets tackle this this week

**Comment by zomars** [comment]
I propose going the reverse redirect route:
- Move the website to `website.cal.com`
- Assign the bare `cal.com` domain to `app.cal.com` (It will still work with both)
- Rewrite marketing pages from `cal.com` to `website.cal.com` (the user won't see the `website` subdomain at all)

**Comment by hariombalhara** [comment]
This is already fixed by @zomars by fixing the rewrites.
