### ISSUE TITLE
Changing timezone in event with DST

### ISSUE THREAD

**Issue by guillaume-ro-fr** [calcom/cal.com#2250]
### Issue Summary

Changing timezone before the daylight saving time (DST) with a date after the DST change available slots.
Maybe the DST is not evolved.

### Steps to Reproduce

1. Open en event booking page
2. Select a date
3. Change the timezone (Paris --> Sarajevo)
4. Select the same date: The datetime is correct
5. Change again the timezone (Sarajevo --> Paris)
6. Select the same date : Datetime is 1 hour delayed

### Technical details

- Recording: [https://app.birdeatsbug.com/sessions/ztUhRX9Au9UwQrnEvNlU-mdr_x2aaJnzQg6LEVdVTUzG](https://app.birdeatsbug.com/sessions/ztUhRX9Au9UwQrnEvNlU-mdr_x2aaJnzQg6LEVdVTUzG)

- Browser: Brave (Chrome 99.0.4844.74)
- OS: macOS & Debian Server
- Node: 14.19.0
- Cal version: [77266535e54668ae0dd33d27ee64ad649eb7cb38](https://github.com/calcom/cal.com/tree/77266535e54668ae0dd33d27ee64ad649eb7cb38)

**Comment by milospuac** [comment]
Hi there. Thanks for bringing this to our attention. Our team will have a look

**Comment by guillaume-ro-fr** [comment]
Resolved with #2296
