### ISSUE TITLE
Installation is taking too long and a fair comparisson between package managers

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#2265]
I have measured the installation time of Cal using `yarn`, `npm@8`, and `pnpm`.
Be aware that times are related to my machine. What matters here are percentages that I expect will stay similar to yours.

There are three measurements for each package manager corresponding to the installation order. The first time shouldn't be representative of the average because the package manager must request everything from the cloud instead of tripping to its cache, but I place it anyway so you can have a real measure.

_Note that between installations I have fully clean (turbo run clean) and I also include the `prisma generate` post-installation step as well._

`time yarn` _# yarn v1.22.17_
- 98,97s user 35,25s system 
- 37,70s user 17,58s system 
- 36,33s user 13,95s system 
 
`time npm install --legacy-peer-deps`  _# npm v8.5.5_
- 78,99s user 7,48s system 
- 32,16s user 5,96s system 
- 32,82s user 5,87s system 

 _**legacy-peer-deps** was needed to bypass a peer dependency (react@16) conflict with the `react-multi-email` package._
 
`time pnpm install` _# pnpm v6.32.3_
 - 84,74s user 11,38s system  
 - 17,77s user 4,64s system 
 - 17,82s user 4,92s system

### Some nice features about  **pnpm** you might not know
- It adds first-class extra features to work with monorepos. (filtering scopes, executing in the root scope from anywhere, etc)
- It adds concurrency execution out of the box. No need for third-party scripting packages to handle this.
- It lets you pipe a shell with ease (`pnpm exec ...`)

Any comments about this will be much appreciated

**Comment by milospuac** [comment]
Hey Demian. Thanks for reaching out and for reporting this. Our team will have a look

**Comment by emrysal** [comment]
Back when I've done a deep dive in getting Yarn 2 to work; Except for Prisma (node_modules/.prisma directory doesn't quite work as well when there is no node_modules). I've also investigated pnpm back then; 

The main reason we do not have npm at the moment is because the peer dependency issues in the project cause npm not to build, but in yarn these are simply warnings (this is mainly a problem in Railway/Heroku). Before we look at any alternative pkg managers I propose to first investigate & fix our peer dependency issues.

**Comment by denik1981** [comment]
Yes, I saw that peer dependency issue but I ultimately passed with both (with some tears in the process I won't deny that). 

What I saw with yarn (v1) is that it lets you bypass a peer dependency if it is hoisted at the root level of the mono. A practical example will be with `zod` which is a dependency of `@calcom/web` but a peer for `@calcom/prisma` issued by `zod-prisma`. Npm will fail if you don't add zod as a dependency of the later while yarn doesn't because it will look into the hoisted **Zod** package to resolve it. Yeah, all in all yarn (v1) is much more permissive than the rest.

The main issue with yarn is that is kind of abandoned. The core team has moved into berry, and maintenance is managed mostly by external contributors. I have faced some issues with it (not in Cal) that the solution was to downgrade the version or to migrate to a different package manager.  

And the only problem with pnpm is adoption. I'm not quite sure if you can deploy in Vercel using pnpm for example. Back before they were even restricted to working npm@8 as they have their own engine. All in all, this is mostly a thread today, a potential need in the future as yarnv1 is not moving forward anywhere.

**Comment by agustif** [comment]
> And in terms of pnpm it has the adoption problem. I'm not quite sure if you can deploy in Vercel using pnpm for example. 

Found this blog post from 6 days ago https://vercel.com/changelog/projects-using-pnpm-can-now-be-deployed-with-zero-configuration

Also vercel's sponsorship should keep pnpm maintained for the near future at least ;)

**Comment by denik1981** [comment]
@agustif awesome finding. Yes, in fact, turborepo's core always read making a special recommendation for using pnpm although they support all of them.  And it is really not difficult to learn. It is almost similar to npm (they tried to keep the same verbs for the CLI) but they added a few more like filter and exec. 

Check this very recent tweet from Jared Palmer the creator behind turbo.
[https://twitter.com/jaredpalmer/status/1506634649921064966](https://twitter.com/jaredpalmer/status/1506634649921064966)

**Comment by nimeshvaghasiya** [comment]
@zomars any update for pnpm usage?
