### ISSUE TITLE
Login redirects to cal.com website

### ISSUE THREAD

**Issue by hariprasadiit** [calcom/cal.com#2269]
### Issue Summary

After successful login user is redirected to https://cal.com

### Steps to Reproduce

1. Login to app.cal.com

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
User should be redirected to the portal

**Comment by hariombalhara** [comment]
The issue seems to be fixed.

**Comment by sean-brydon** [comment]
Agreed - I can't seem to replicate this issue. 

Closing the issue for now - Please reopen this issue if you are still having this issue. If this is the case please use https://birdeatsbug.com/ to demo the issue to us
