### ISSUE TITLE
Broken link on the website

### ISSUE THREAD

**Issue by dimadk24** [calcom/cal.com#2282]
### Issue Summary

A broken link on the landing page: https://app.cal.com/integrations throws 404 error

### Steps to Reproduce

1. Open https://cal.com/
2. Click on Apps in the header menu
3. Click on any integration except web3

And on the bottom of https://cal.com/pricing there's also a 404 iframe of something like this: https://imgur.com/a/7jOuvwV

**Comment by sean-brydon** [comment]
Closing Fixed in https://github.com/calcom/website/pull/99
