### ISSUE TITLE
Cannot logout when using the logout path route (/auth/logout)

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#2295]
### Issue Summary

A little weird behavior that when I navigate to the logout path, I got the message feedback that I have successfully logged out, but I'm actually still logged in. Navigating to the root "/", takes me to my home events page as usual. 

### Steps to Reproduce

1. Log in.
2. Navigate to [http://localhost:3000/auth/logout](http://localhost:3000/auth/logout), or your live hosted copy of Cal  
3. You will get an instant feedback message of being successfully logged out.
4. Navigate to the root (or any page within Cal). 
5. You are still logged in.

**Comment by milospuac** [comment]
Thanks for the contribution. One of our team members will review this
