### ISSUE TITLE
 error: Environment variable not found

### ISSUE THREAD

**Issue by AshnaSabu123** [calcom/cal.com#2299]
Hi,

While executing the yarn start command , getting the below error. Please have a look and kindly update as with the solution.

@calcom/prisma:db-deploy: Environment variables loaded from .env
@calcom/prisma:db-deploy: Prisma schema loaded from schema.prisma
@calcom/prisma:db-deploy: Error: Get config: Schema Parsing P1012
@calcom/prisma:db-deploy:
@calcom/prisma:db-deploy: error: Environment variable not found: .
@calcom/prisma:db-deploy:   -->  schema.prisma:6
@calcom/prisma:db-deploy:    |
@calcom/prisma:db-deploy:  5 |   provider = "postgresql"
@calcom/prisma:db-deploy:  6 |   url      = env("")
@calcom/prisma:db-deploy:    |
@calcom/prisma:db-deploy:
@calcom/prisma:db-deploy: Validation Error Count: 1
@calcom/prisma:db-deploy:
@calcom/prisma:db-deploy: error Command failed with exit code 1.
@calcom/prisma:db-deploy: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/prisma:db-deploy: error Command failed with exit code 1.
@calcom/prisma:db-deploy: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/prisma:db-deploy: Error: command finished with error: command (packages/prisma) yarn run db-deploy exited (1)
command (packages/prisma) yarn run db-deploy exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.638s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will have a look

**Comment by emrysal** [comment]
Hi @scantreed - could you have a look what https://github.com/calcom/cal.com/blob/main/packages/prisma/schema.prisma looks like (in both of your installs?) I would expect DATABASE_URL - also make sure to define the DATABASE_URL variable in ./packages/prisma/.env

**Comment by scantreed** [comment]
Thanks for getting back to me @emrysal 

My schema.prisma file matches the repository (I haven't changed anything, this is a fresh pull). Though what do you mean by "both of your installs"?

./packages/prisma/.env contains the following: 
```
# DATABASE_URL='postgresql://<user>:<pass>@<db-host>:<db-port>/<db-name>'
DATABASE_URL="postgresql://postgres:@localhost:5450/calendso"
.env (END)
```

**Comment by PeerRich** [comment]
hey, can you try the latest version again?

**Comment by kunaldo07** [comment]
Yarn dx is failing does anyone knows how to resolve this?

![image](https://github.com
![Screenshot 2023-06-19 212012](https://github.com/calcom/cal.com/assets/67819149/8a3faec4-28db-471e-9468-d6bf6e64352f)
/calcom/cal.com/assets/67819149/30394740-cf8f-4ed7-8edf-a880d9828d73)

**Comment by ayushgupta4002** [comment]
> Yarn dx is failing does anyone knows how to resolve this?
> 
> ![image](https://github.com ![Screenshot 2023-06-19 212012](https://user-images.githubusercontent.com/67819149/246878830-8a3faec4-28db-471e-9468-d6bf6e64352f.png) /calcom/cal.com/assets/67819149/30394740-cf8f-4ed7-8edf-a880d9828d73)

I am also facing the same issue

**Comment by HarshDeswal** [comment]
Still the same issue is there. 
> hey, can you try the latest version again?

![image](https://github.com/calcom/cal.com/assets/94471009/cd98256e-8e36-4818-ab3e-a58326a57c2e)

But as @emrysal has said if you give the `DATABASE_URL` in the `./packages/prisma/.env` . Then its working

**Comment by codewithsonyy** [comment]
I faced the same issue. 

![calcomerror](https://github.com/calcom/cal.com/assets/114895266/cb0e982f-2a04-4c53-8f7d-1237cf0eed5d)

I did tried the fix mentioned by @emrysal but the issue in not getting resolved.
![Screenshot (245)](https://github.com/calcom/cal.com/assets/114895266/ce8afe6e-7a66-4c50-bac2-6c7f71fd81f9)

**Comment by Afrin127329** [comment]
I was struggling with the same error. Then I had to add the DATABASE_URL directly on /packages/prisma/.env 
It finally worked.
