### ISSUE TITLE
Apps allow you to reinstall them and there is no visual feedback they have been installed 

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#2312]
### Issue Summary

If you go through the flow of adding an app from the new App Store, after it gets installed, it is still showing the app without any visual feedback that it has been installed, and even let you reinstall it again if you try so.

For example, after installing the zoom app  I got this response when I trip again to the App Store
![image](https://user-images.githubusercontent.com/66160623/160703733-3e5d94e8-76db-4f64-a48a-4791900c50d7.png)

### Steps to Reproduce

With zoom
1. Login with your user
2. Go to `http://localhost:3000/apps` (replace localhost:3000 with the base URL on where you are hosting Cal)
3. Search for the Zoom app and complete the installation.
4. Return to the same path on step 2 and check that you can repeat step 3

**Comment by denik1981** [comment]
@PeerRich I'm running some tests against the App Store so I would probably want to take in this one. 

What do you think should happen after the App gets added? Should we add an "Installed" label (replacing the Add button), or should it be removed from this page taking into account that it is also listed in the Installed section of the App Store?

**Comment by PeerRich** [comment]
> @PeerRich I'm running some tests against the App Store so I would probably want to take on this one. 
> 
> 
> 
> What do you think should happen after the App gets added? Should we add an "Installed" label (replacing the Add button), or should it be removed from this page taking into account that it is also listed in the Installed section of the App Store?   

@Jaibles and @zomars, thoughts?

**Comment by zomars** [comment]
> @PeerRich I'm running some tests against the App Store so I would probably want to take on this one.
> 
> What do you think should happen after the App gets added? Should we add an "Installed" label (replacing the Add button), or should it be removed from this page taking into account that it is also listed in the Installed section of the App Store?

It depends, for example in the case for calendars you may add multiple calendars so you can "install" them multiple times. In the case for video apps, it would make sense being able to install just once. Also there are these "global" installs that are available without user interaction like Daily.co and Huddle01.

**Comment by zomars** [comment]
Agreed, @Jaibles will have the last word on finding the optimal way of handling these.

**Comment by PeerRich** [comment]
hey, can you try the latest version again?
