### ISSUE TITLE
Issues with availability and event links 

### ISSUE THREAD

**Issue by MaiTemraz** [calcom/cal.com#2313]
### Issue Summary

My name is Mai Temraz and I'm a program manager at Manara (a job hunting program). Over 100 of our current participants uses Cal.com to schedule their mock interviewes and job interviews. Recently they've been reporting a lot of issues including:

- Their availability being wiped out

- Getting double booked

- Their event link getting changed 

- Not receiving a calendar invite after an event is being booked

This is really causing them a lot of problems scheduling their interviews. What can we do to ensure their accounts are being set up properly and that they don't face those issues again

**Comment by milospuac** [comment]
Hi Mai. Thanks for reaching out. 

- Availability being wiped out is a weird one, however, it's most likely an all-day calendar event that is marked as **Busy**. Those will take up the entire slot.
- Having opt-in bookings selected, you can get double-booked only if you confirm those requests for meetings. Technically you can get an unlimited amount of requests for the same slot unless you confirm one of them. 
- Event link getting changed - I'd really need more context here. Event type link? Changed how? 
- Also need more context. Is it a team event? What calendar is being used?

**Comment by PeerRich** [comment]
hey, this was a temporary downtime and should not happen with the latest version
