### ISSUE TITLE
Broken UI and wrong username is identified if query params are present and user doesn't exist.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2316]
<img width="1734" alt="Screenshot 2022-03-30 at 4 28 18 PM" src="https://user-images.githubusercontent.com/1780212/160816547-c2577eee-dc74-4c6e-8dfc-f16da19f951c.png">

This is mostly possible in case of embed.

It should have been just "pro"

**Comment by hariombalhara** [comment]
It detects wrong username if query params are there jn the URL. 
We should simple ignore query params and everything after that. 
![Screenshot_2022-04-06-18-36-40-951_com.android.chrome.jpg](https://user-images.githubusercontent.com/1780212/161981515-a3b7ec7d-288f-4090-a028-ffc4f257fd9e.jpg)

**Comment by coachlivinglegend** [comment]
@dev-eth @hariombalhara what's the update on this? I can reproduce this bug and i'm already trying to fix it.
