### ISSUE TITLE
CalDav calendar busy not working when there is non-parseable? start- or end-date

### ISSUE THREAD

**Issue by Lucas-Steinmann** [calcom/cal.com#2317]
### Issue Summary

We are using CalDav as CalendarService.
My colleague reported that sometimes the busy service is not working and people book events clashing with other events.
I used "availability/troubleshoot" to check that date.
It says: `calendar_no_busy_slots`.
Availability works for other dates.

### Steps to Reproduce

1. Go to: https://private-cal-url/availability/troubleshoot
2. Select the date, my colleague reported a clash of events

### Technical details

The following error is thrown:

` TypeError  Cannot read property 'toJSDate' of null`

I checked the code and assume it is one of these lines: https://github.com/calcom/cal.com/blob/main/packages/lib/CalendarService.ts#L253-L254

I tried deleting some events to check, which one is the culprit. But I couldn't move/delete all of them, since it is a live system and I didn't want to mess up the events and trigger some rescheduling mail. So I sadly cannot give you an .ical file to reproduce.

I think all events are in some form valid, since all other calendar clients in use can display them.
I guess the best solution, would be to skip events whose date can't be parsed?
That would make availability working for the other events of the day.
Currently, it doesn't work at all, if one event is not parsable.

If you have any further questions or need information, I'm happy to expand.

**Comment by milospuac** [comment]
Hi Lucas. 

Thank you for bringing this to our attention. Our team will have a look into this issue

**Comment by alishaz-polymath** [comment]
Hey @Lucas-Steinmann We have since improved upon the CalDAV integration and there have been no issues in relation to what you mention here for a while. I'm closing this ticket as I believe it is now obsolete given the massive changes and improvements we've already done towards making CalDAV integration more stable. However, do feel free to re-open this if you still face this issue with the latest version. 🙏
