### ISSUE TITLE
cal.com/web3 shows a not found page

### ISSUE THREAD

**Issue by miguelnietoa** [calcom/cal.com#2318]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

![image](https://user-images.githubusercontent.com/39246879/160876645-44df8810-ed44-403b-aea4-a40c5011803f.png)

### Steps to Reproduce

1. Went to cal.com/web3

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
If you see the requests, it seems like it makes a request to `https://cal.com/peerrich-eth/orangedao`.
![image](https://user-images.githubusercontent.com/39246879/160876984-d63f01b3-5fdb-4727-a411-e570b6c85790.png)

But `https://cal.com/peerrich-eth` has no event types.
![image](https://user-images.githubusercontent.com/39246879/160877503-285eb4d6-c09c-4531-b415-ad3791f3a953.png)

**Comment by milospuac** [comment]
Hi there. Thanks for reporting this. Our team will have a look

**Comment by PeerRich** [comment]
will fix!

**Comment by sean-brydon** [comment]
This appears to be fixed :) Thanks for reporting this
