### ISSUE TITLE
Allow booking links to be linked to a specific calendar

### ISSUE THREAD

**Issue by drochag** [calcom/cal.com#2326]
### Describe the solution you'd like

When creating a booking link, I'd like to select the specific calendar it would go to.

### Additional context

When having different calendars, it would be nice to share one link with the work calendar to coworkers, but having another link to your custom clients as a freelancer but that one linked to your personal account.

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Correct me if I understood incorrectly what exactly you are trying to achieve, but each event type that you created can have a different calendar to create an event on. You can set that up in the advanced settings of the event type 
<img width="898" alt="Screen Shot 2022-03-31 at 11 39 46" src="https://user-images.githubusercontent.com/97884287/161026077-5279f1c4-0ad4-49cf-a629-68600c147f44.png">

**Comment by drochag** [comment]
Definitely !

Thanks a lot, I didn't noticed because I hadn't upgraded to Premium when I first checked event types
