### ISSUE TITLE
Pricing doesn't convert

### ISSUE THREAD

**Issue by adityathakurxd** [calcom/cal.com#2327]
### Issue Summary

When I  set pricing for an event in INR it shows up in USD on the preview page.

![Connect Call _ Aditya Thakur _ Cal com - Google Chrome 3_31_2022 8_58_30 AM](https://user-images.githubusercontent.com/53579386/160971045-e000858c-1191-4593-978e-a5976b38beae.png)

**Preview Page:**

![Connect Call _ Aditya Thakur _ Cal com - Google Chrome 3_31_2022 8_58_18 AM](https://user-images.githubusercontent.com/53579386/160971092-e7ab5ff1-7c29-45e8-ae9e-0ed1274e2348.png)

**Comment by milospuac** [comment]
Hi there. Thanks for reporting this. Our team will have a look

**Comment by miguelnietoa** [comment]
Hello, I would like to contribute 👍🏻
