### ISSUE TITLE
Calendar design indicates that dates have availability when a date is "All booked today." 

### ISSUE THREAD

**Issue by kelseysmithdesign** [calcom/cal.com#2329]
### Issue Summary

**Context**
On the booking page, the calendar UI has 3 modes for dates: 
1. no availability = no box, gray text, not clickable
2. available to book that day = gray box, bold text, clickable
3. selected date = black box, bold text, status: clicked (times shown in the right panel)

<img width="757" alt="Frame 18" src="https://user-images.githubusercontent.com/56199177/161032216-a92d0451-ebe3-4a40-a379-95d12369dfff.png">

**Issue**
Dates that are completely booked are clickable and have the same appearance as dates with availability. This creates a frustrating user experience because the UI indicates to the user that there should be availability on that day. Users click on the day and see the message "All booked today". This adds extra steps for users who are looking for a booking slot. They might click on several days that are "All booked today" before they find an available date. 

<img width="769" alt="Screen Shot 2022-03-31 at 11 19 16" src="https://user-images.githubusercontent.com/56199177/161027657-8c874595-52e2-4384-8b94-21a02b6d2a50.png">

### Steps to Reproduce

1. I completely blocked off April 5th in my Google calendar.
5. I went to the booking page.
6. I saw that the calendar UI remained the same for April 5th (gray box is still there and its clickable).

### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I consider this a bug because the UI pattern doesn't align with user expectations. They expect to find availability on clickable dates. 

**Idea**
If a day is fully booked, then it can follow the same UI pattern as dates that are unavailable for booking. Regardless of the reasoning behind the unavailability, the user's goal is to find an available slot quickly.

<img width="757" alt="Frame 17" src="https://user-images.githubusercontent.com/56199177/161031182-6f4bb20e-997a-4f43-a7c7-de2b68b62a4e.png">

### Technical details

[sorry I'm a UX designer and can't dive too deep into the technical issues]

**Comment by milospuac** [comment]
Hey Kelsey,

Thanks for reaching out. Our team will have a look at your suggestion

**Comment by lharries** [comment]
Hi @milospuac, this is also something we'd really want too. It's currently a poor experience if lots of the days don't have availability

**Comment by PeerRich** [comment]
this is actively being worked on by @emrysal and will go live this month. its easier said than done– required us to rebuild the entire scheduling logic from scratch to cache the availability

**Comment by kelseysmithdesign** [comment]
Awesome @PeerRich! Thanks @emrysal! I'm excited to see the update. I see now that it's more work than expected. I really appreciate it. I'm a big fan of cal.com - thanks for all that you do.

**Comment by FlxMgdnz** [comment]
+1 for this. Just want to add that the bug also appears with only a single all-day event (e.g. a conference) that is set to "busy" in Google Calendar.

**Comment by emrysal** [comment]
Hi guys, this is in latest; and it works pretty wel (after some initial teething issues, hidden historical bugs, etc) - we're still working to improve the performance but that's getting along nicely.
