### ISSUE TITLE
Link meeting location of the event type - URL from certain platforms not showing in the mail confirmation 

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#2332]
So far, this has been happening with Nextcloud platform video call link, Zoom link, and Google Meet link

### Nextcloud

<img width="499" alt="Screen Shot 2022-03-29 at 10 55 58" src="https://user-images.githubusercontent.com/97884287/161085596-29216b34-db28-4306-8b64-f98ec90e7595.png">

### Zoom link

<img width="552" alt="Screen Shot 2022-03-31 at 09 47 44" src="https://user-images.githubusercontent.com/97884287/161086576-ad4b8651-75a9-414a-a563-c830a1aa9d30.png">
<img width="679" alt="Screen Shot 2022-03-31 at 17 00 11" src="https://user-images.githubusercontent.com/97884287/161087083-719ab82d-138e-4e3f-b5a2-900dcede5ae6.png">

### Google Meet link

<img width="519" alt="Screen Shot 2022-03-31 at 17 04 26" src="https://user-images.githubusercontent.com/97884287/161087851-ac3ca336-953a-4a5b-881d-7ab81601f7a1.png">
<img width="535" alt="Screen Shot 2022-03-31 at 17 05 22" src="https://user-images.githubusercontent.com/97884287/161087942-b0cd9b65-3589-4434-a131-832c2b831ca9.png">

**Comment by sean-brydon** [comment]
PR merged this should be now fixed :)

**Comment by bhopmann** [comment]
"No App Name" also appears when using a location for in_person_meeting, this seems not to be fixed with the merged PR.
