### ISSUE TITLE
Microsoft Teams Integration not completed/working?

### ISSUE THREAD

**Issue by EclipseKnight** [calcom/cal.com#2358]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cannot add/install Microsoft Teams app in the app-store.

### Steps to Reproduce

1. Click Apps
2. Click App Store
3. Click Microsoft 365/Teams 'Add'
4. Install App button is missing.

I looked through the [open integration issue](https://github.com/calcom/cal.com/issues/1462) but the branch it was merged to 'monorepo/app-store' No longer exists.

Is the integration completed or is it just a placeholder?

**Comment by sw506** [comment]
Still not working correctly when I try to connect Teams on self-hosted I get redirected to this URL:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&scope=User.Read Calendars.Read Calendars.ReadWrite offline_access&client_id=<omitted>&redirect_uri=https://<CAL_URL>/api/integrations/office365calendar/callback&state={"returnTo":"https://<CAL_URL>/apps/installed"}

And a second Outlook-Calendar is added, but no Teams.

**Comment by Razva** [comment]
Did you managed to make MS Teams "work"?

I have enabled the App from the Admin area.

<img width="447" alt="Screenshot 2023-04-11 at 18 43 18" src="https://user-images.githubusercontent.com/1668596/231216707-c01339c4-4006-426f-a177-e6013a0cc753.png">

Unfortunately I cannot find/install it in the "Installed Apps" area.

<img width="1389" alt="Screenshot 2023-04-11 at 18 44 34" src="https://user-images.githubusercontent.com/1668596/231217030-c5b5f91b-d1b0-4003-bca9-fa6da9efc2a9.png">
