### ISSUE TITLE
make huddle01 and jitsi uninstallable

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2372]
right now its built in a way that its preinstalled and cannot be removed

instead we should treat it like the web3 app and be able to add/remove it

- [ ] jitsi
- [ ] huddle01

**Comment by PeerRich** [comment]
@zomars can you take care of this?

**Comment by zomars** [comment]
Can you put a priority into this? @PeerRich

**Comment by zomars** [comment]
TODO: Find a way to make global apps opt-in, these can be achieved both by using the already made credentials model or add something new to save an enabled toggle on the user data.

**Comment by PeerRich** [comment]
@joeauyeung can you take a look instead?

**Comment by zomars** [comment]
> @joeauyeung can you take a look instead?

Thanks @PeerRich. Also @joeauyeung you can take a look at @alannnc implementation of WipeMyCal to handle it similarly: https://github.com/calcom/cal.com/blob/main/packages/app-store/wipemycalother/api/add.ts
