### ISSUE TITLE
Memory error on build after latest updates

### ISSUE THREAD

**Issue by dlemery** [calcom/cal.com#2381]
### Issue Summary

After updating to the latest via Git Pull, can no longer build the application with "yarn build." Get the error FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### Steps to Reproduce

1. git pull
2. yarn workspace @calcom/prisma db-deploy
3. yarn build
4. error occurs

### Technical details
yarn dev works. Some pages result in errors when using though.
Worked ok before, here is exactly what happens:

$ yarn build
yarn build
yarn run v1.22.18
$ next build
info  - Loaded env from /home/calendso/cal.com/apps/web/.env
info  - Checking validity of types ..
<--- Last few GCs --->

[186651:0x502ebe0]    32769 ms: Mark-sweep (reduce) 952.0 (955.8) -> 951.2 (957.0) MB, 856.4 / 0.0 ms  (average mu = 0.104, current mu = 0.007) allocation failure scavenge might not succeed
[186651:0x502ebe0]    33613 ms: Mark-sweep (reduce) 952.2 (956.0) -> 951.3 (957.3) MB, 837.2 / 0.0 ms  (average mu = 0.058, current mu = 0.008) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa3aaf0 node::Abort() [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 2: 0x970199 node::FatalError(char const*, char const*) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 5: 0xd769e5  [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 6: 0xd7756f  [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 7: 0xd853ab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 8: 0xd88f6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
 9: 0xd5764b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
10: 0x109fc0f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
11: 0x1448e19  [/home/calendso/.nvm/versions/node/v14.19.1/bin/node]
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dlemery** [comment]
I temporarily fixed this by bumping up the machine to 4GB of RAM (or higher) in order to build. 2GB of RAM not enough.

**Comment by zevaverbach** [comment]
@dlemery how little RAM are you able to get away with after install?

**Comment by mrkirchner** [comment]
Also seeing this when trying to deploy to Digital Ocean's App Platform.  According to DO  they have a combined RAM/disk 8gb limit.  I generally hit this limit when it build hits the  Linting and checking validity of types.  Not sure if there is anything that can be done.

**Comment by ameyer117** [comment]
@barryvdh - thank you, it worked for me.

**Comment by notflip** [comment]
I'm encountering this problem as well, @barryvdh the `esmExternal` is not to be found in the given file, I suppose they removed this in a later version?

**Comment by techguruagi** [comment]
Facing the same issue. Any other possibilities ?

**Comment by CodeShakingSheep** [comment]
Also running into this on a 12GB machine where only ~2GB are actively in use before running `yarn build`.

**Comment by Krislunde** [comment]
I am running into this on a 32GB machine. 

Have tried setting `--max-old-space-size=32768` in various ways through both the terminal, package.json, as well as .npmrc and .yarnrc - to no avail.

**Comment by jacobpennington821** [comment]
Also encountering this issue with 8GB of ram on ubuntu.

**Comment by quangdog** [comment]
I've also just run into this with a fresh git pull from today.
![Screenshot 2024-03-21 at 5 50 52 PM](https://github.com/calcom/cal.com/assets/1791619/cd00681a-2f2c-409a-83a3-26fbd534b522)

**Comment by quangdog** [comment]
This morning I gave my VM a bunch more ram (16GB, up from 4GB) and the build succeeded. Memory consumption on the server (that is a dedicated Ubuntu 22.04 VM just to try cal.com out) peaked around 8.5GB during the build.

**Comment by JMauclair** [comment]
I've had the same issue on the last version (4.9.3).
Running on AWS EC2, I took an t4g.large, with 2g Swap, and ran this command : 
sudo env NODE_OPTIONS="--max-old-space-size=10240" yarn build
And it finally worked.

Will building, I was checking free -h every seconds, building needed ~10Go of RAM at the peak in my case, my 2G of swap was nearly not enough.

**Comment by CptPlastic** [comment]
Same issues it just runs out of memory. Running in cloudron.
