### ISSUE TITLE
Allow organizer to set the meeting link for the booking later.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2393]
### Is your proposal related to a problem?
Someone booked a meeting with me. I didn't have any `location` set in the event type. The meeting got booked, but there is no URL where the meeting would occur. Now, I want to update it in the booking.

### Describe the solution you'd like

Allow organizer to set location in booking and email should be sent to the guests notifying about the meeting place.
Changing meeting place for the booking(one off thing) can be also be useful, if let's say I am facing temporary issues with a particular meeting tool.

**Comment by CarinaWolli** [comment]
Is this still relevant? I could work on that

**Comment by hariombalhara** [comment]
Yeah. It's not yet fixed
