### ISSUE TITLE
DATABASE_URL missing in schema.prisma:6

### ISSUE THREAD

**Issue by adriaanvanrossum** [calcom/cal.com#2396]
In 9d512e70c46fa09977c6e9458c11ec3657d110ee I get an error with about the DATABASE_URL:

```
@calcom/web:dev: error - Error:
@calcom/web:dev: Invalid `prisma.team.findFirst()` invocation:
@calcom/web:dev:
@calcom/web:dev:
@calcom/web:dev:   error: Environment variable not found: DATABASE_URL.
@calcom/web:dev:   -->  schema.prisma:6
@calcom/web:dev:    |
@calcom/web:dev:  5 |   provider = "postgresql"
@calcom/web:dev:  6 |   url      = env("DATABASE_URL")
@calcom/web:dev:    |
@calcom/web:dev:
@calcom/web:dev: Validation Error Count: 1
```

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1079135/161969233-034d32bd-f8cf-47a0-85ac-ca2ea9ce2300.png">

I moved DATABASE_URL from `.env` to `packages/prisma/.env`.

When I add `DATABASE_URL` to `.env` as well the command `yarn dev` works fine.

**Comment by miguelnietoa** [comment]
What command are you trying to run?

**Comment by adriaanvanrossum** [comment]
`npm run build`

**Comment by miguelnietoa** [comment]
Hmm, everything works fine from my local. Try to execute the commands with `yarn`: `yarn run build` 🤔

**Comment by adriaanvanrossum** [comment]
I gave up. Sorry.

**Comment by gmpreussner** [comment]
I'm seeing the same problem with latest in `master` from today. I have `DATABASE_URL` in `/packages/prisma/.env`; adding it to `/.env` as well doesn't fix it for me. Connection to the database in general works - this fails during the migration process in prisma:build

I'm running `yarn build` on the command line.

**Comment by gmpreussner** [comment]
Running `yarn dev` works

**Comment by vinyll** [comment]
This ticket should be open again :man_shrugging:

**Comment by gmpreussner** [comment]
FWIW I was able to make it work by hard-coding the `DATABASE_URL` into `node_modules/.prisma/client/schema.prisma`. This is probably not great, because from what I understand this file is generated by the compiler.

**Comment by jvence** [comment]
Having same issue

**Comment by jfk9w** [comment]
Removing surrounding quotes for `DATABASE_URL` value resolved the issue for me. Got the solution from [here](https://stackoverflow.com/questions/71736148/prisma-error-validating-datasource-db-the-url-must-start-with-the-protocol).

**Comment by itaibaruch** [comment]
I solve it by copying the `DATABASE_URL="postgresql://postgres:@localhost:5450/calendso"` from './packages/prisma/.env' to the root of the project env './.env' and './.env.example' (so it wont get deleted)

Hope it helps

**Comment by alishaz-polymath** [comment]
This is a symlink issue. The steps to resolve it are quite straightforward:

Run `git config --get core.symlinks` this is most likely false

Now, as a pre-requisite, please confirm the following:
Git tries to create a symbolic link during git init (which is run as a part of git clone) and sets core.symlinks = false if it can't confirm that you have permission to create a symbolic link (running as admin on windows, for example).

Next, run `git clone -c core.symlinks=true <URL>` for latest pull and it should work now. Since, we use symbolic links for the .env file inside `packages/prisma`, it requires ensuring that your git config is set to symlinks as true **AND** you have necessary permission (usually admin) to enable it during clone process.

This should resolve it entirely (tested on windows). Please also note, you would need to add the .env file in the root directory because the symlink requires it to work as it's just a symbolic link
🙏 

please confirm if this helped
@adriaanvanrossum @gmpreussner @vinyll @MarZab @jvence @jfk9w @itaibaruch

**Comment by rksingh2001** [comment]
@alishaz-polymath what is the <URL> in git clone -c core.symlinks=true <URL> ?

**Comment by alishaz-polymath** [comment]
It’s the GitHub repo URL @rksingh2001

**Comment by rksingh2001** [comment]
@alishaz-polymath I tried the command which you have mentioned, it it showing me 4k+ changes after just cloning it?

**Comment by alishaz-polymath** [comment]
Hi @rksingh2001 . The clone command is for when you need to create a new clone altogether. If you already have a clone set, all you need to do is set `core.symlinks` to true, and then save the .env file in `packages/prisma` With necessary privileges to confirm that symlinks  have been formed.

**Comment by rksingh2001** [comment]
@alishaz-polymath How can I set it to true if I already have a clone setup?

**Comment by rksingh2001** [comment]
I am still facing the same issue even after setting core.symlinks to true

**Comment by PeerRich** [comment]
@zomars

**Comment by zomars** [comment]
Can you provide more context @rksingh2001 what's your specific error?

**Comment by alishaz-polymath** [comment]
@rksingh2001 The only way I see in your case  is to re-save the .env file containing the symlink once it has been turned to true for the project you already have, with admin permissions. Otherwise, you'd need to reclone with the admin rights and with the command mentioned above. 🙏

**Comment by VinnyHS2** [comment]
I had the same problem and solved it by add the `DATABASE_URL="postgresql://postgres:@localhost:5450/calendso"` in the `package/prima/.env`

**Comment by alishaz-polymath** [comment]
@VinnyHS2 that's not recommended as it defeats the purpose of symlinks and might run into issues in the future if more env variables are added to the linked .env file

**Comment by alishaz-polymath** [comment]
For anyone else struggling with this issue, you can follow the steps mentioned in the documentation:
https://docs.cal.com/how-to-guides/how-to-troubleshoot-symbolic-link-issues-on-windows

**Comment by mpmadhuranga** [comment]
I followed @VinnyHS2  and worked for me, good stuff.
