### ISSUE TITLE
Booking confirm button turns to spinner even if form validation failed

### ISSUE THREAD

**Issue by Nico-J** [calcom/cal.com#240]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When booking an event (clicking the "confirm" button) without filling in any of the form fields (name, mail address, ...), the form validation fails and tells me to fill in these fields (so far so good).
Nevertheless, the "confirm" button turns to a spinner, suggesting that we're waiting for an API call that was actually never triggered.

### Steps to Reproduce
1. Went to my personal Calendso page (e.g. http://localhost:3000/Nico)
2. Clicked on an event type and choosed a date and time
3. Didn't fill out any of the form fields (see screenshot below)
![image](https://user-images.githubusercontent.com/14024119/120890775-2acac500-c605-11eb-9a32-0eab94838bab.png)
4. Click "Confirm". Now you can see the validation error (good) and the spinner in the button (bad):
![image](https://user-images.githubusercontent.com/14024119/120890806-4df57480-c605-11eb-9271-5d1c841ed838.png)

I'd expect that no spinner appears unless the form was actually ready to be submitted so that an API call was actually triggered.

### Technical details
* Browser version: Chrome 90, Ubuntu 20.04
* Node.js version: 12.16.2

**Comment by miguelnietoa** [comment]
This issue is already solved, right?
