### ISSUE TITLE
Multilingual-friendly public pages

### ISSUE THREAD

**Issue by parkervu** [calcom/cal.com#2403]
Loved the i18n efforts of the community, but some suggestions to make it more friendly for the international crowd?

P/S: current public pages does not link to admin's language preference. For example: my account is set in Vietnamese yet the public booking page is still English by default

1. Language switchers in the bottom, in native language
2. Things related to concept of time (April, May, etc...), if possible, could have numbers on it so that MM/YY is not language dependent + easier to understand
3. Timezones should have numbers attached and current system time for easier recognition?
4. (less important but would be great) Links that can have with ?lang= flag for easier directing, eg: cal.com/[users]/30min?lang=vi

Quick mockups
<img width="757" alt="Screenshot 2022-04-06 at 22 51 10" src="https://user-images.githubusercontent.com/48187449/162019218-f8631b3a-baaf-4d00-baee-bef9cad15a6f.png">

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will look into your suggestion

**Comment by PeerRich** [comment]
hey @Jaibles @baileypumfleet  thoughts on this? pretty good idea in my opinion

**Comment by PeerRich** [comment]
pretty sure this has been addressed

**Comment by andres-asm** [comment]
How, I don't see any way to change the language on the booking page

**Comment by andresilveirah** [comment]
Same here. My Cal.com UI is set to Portuguese, if I look at an event preview, the booking page is indeed in Portuguese, but if I open the same event on a incognito tab, the booking page is in English and I don't see a way to change it.

These two GH issues suggest the feature is not either not implemented or missing documentation
* https://github.com/calcom/cal.com/issues/8904
* https://github.com/calcom/cal.com/issues/8706

Someone suggested adding the query param `language=es` to the booking page (e.g. `cal.com/username?language=country_code`) should change the booking page's language, but that didn't work for me.

**Comment by marcospassos** [comment]
Same issue here :/

**Comment by JonasGieselmann** [comment]
An persistent Issue shouldn't be closed, right? @PeerRich
