### ISSUE TITLE
prevent layout shift in /event-types/[id]

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2407]
loading spinner of availabilty is causing Layout shift. instead, I would show a disabled input field with text: loading

https://user-images.githubusercontent.com/8019099/162043291-7f392f6b-9670-4828-b787-07c4c0de60ba.mov

**Comment by a-edwaar** [comment]
Would love to have a go at this as a first issue! 🙌

**Comment by PeerRich** [comment]
@a-edwaar cool go for it

**Comment by Graviis** [comment]
hi @PeerRich i have the fix for this #2475
