### ISSUE TITLE
Default schedule is not "always" defined properly 

### ISSUE THREAD

**Issue by denik1981** [calcom/cal.com#2412]
### Issue Summary

When I was preparing a test suite for the availability page and the schedule creation process a few issues escalate regarding the creation and reassignment of the default schedule. 

**Case 1**
When the user onboards and by following the defaults provided in the onboarding flow, the default schedule isn't quite the default. You can clearly note there is a "Default" badge on it but that's just logic that works in the visual layer assigning that badge to the only schedule available to render. In the DB layer, the default schedule for the user keeps being null (unassigned).

Things turned weirder when you start adding a second or third schedule to this user. The default becomes (visually) the last one added although none of them is the default in reality (not inside the DB). 

A workaround to bypass this issue is to "save" the schedule and then that schedule becomes the default one. Yes, it doesn't matter the first working schedule was supposed to be the default because it was never it.

[https://app.birdeatsbug.com/sessions/mc0pVGi6zLxDGOiW9ATL9yqFMsV5whYDGf2ZJMcZhwFh](https://app.birdeatsbug.com/sessions/mc0pVGi6zLxDGOiW9ATL9yqFMsV5whYDGf2ZJMcZhwFh
)

**Case 2**    
You start with an empty list of schedules. The user might have finished the onboarding process and skipped selecting the default schedule or he might delete all of them to start with an empty list. When this scenario is configured, the first schedule you add becomes the default, and it does not matter if you have to use the switch to make it the default. 

The logic allows Cal to have a list of schedules with no default schedule which I think is correct. But in this case, and to recall Case 1, the default is visually acknowledge by the Default badge when it is not the real default in the DB. And things become weirder again when you add a second schedule. Then suddenly the Default badge disappears from both of them which is in fact the correct view to expect because none is the actual default. 

[https://app.birdeatsbug.com/sessions/vV-viNOQCu-5d93bKCUx4R-8Y3BRt5iclXh6gjkxVRBp]( https://app.birdeatsbug.com/sessions/vV-viNOQCu-5d93bKCUx4R-8Y3BRt5iclXh6gjkxVRBp
)

**Case 3**
You have created 2 (or more) schedules and assigned the default to the first one. If you delete the default it won't be resigned to anyone unless is the last one which in this case it will be (visually) assigned to it but it won't be the true default in the DB.

[https://app.birdeatsbug.com/sessions/MIRYvjU4JqRmAuZtMbC83986IFUv_A4280LkB6t8ihfs](https://app.birdeatsbug.com/sessions/MIRYvjU4JqRmAuZtMbC83986IFUv_A4280LkB6t8ihfs
)

### Side note
You might recall I didn't hit the **Save** button always within the newly created schedule. This is because the schedule is already created once you name it  (within the modal) and then updated on its own screen. For some cases, the Save button will force you to make that schedule the default, even if you don't want to because the switch is not present and it is taken "default=true" by default.
  
### Steps to Reproduce
- Follow the steps on the video 
- You might also benefit from keeping an opened Prisma Studio session to check the User's table for the default schedule.

**Comment by milospuac** [comment]
Thanks for contributing, Demian!

**Comment by PeerRich** [comment]
i think this is fixed
