### ISSUE TITLE
cal.com/apps is blank for unauthed users

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#2420]
### Issue Summary

Seems like a recent change is prevented the /apps page to be publicly accessible.

### Steps to Reproduce

1. Logout if you're logged in
2. Go to https://cal.com/apps
3. See the blank page

**Comment by miguelnietoa** [comment]
I think it was introduced on this:
- Commit: d340ee62
- PR: https://github.com/calcom/cal.com/pull/2390

**Comment by miguelnietoa** [comment]
This is why this issue is happening, when the user is not authenticated the session is not defined, so it is returning null and we see a blank page.

https://github.com/calcom/cal.com/blob/fefc314d35d4b35c615e126df3ba8d7f3c0e897b/apps/web/components/Shell.tsx#L209-L211

**Comment by afzalsayed96** [comment]
oops
