### ISSUE TITLE
Unconfirmed bookings for opt-in meetings in the past lead to endless "Awaiting Approval" emails

### ISSUE THREAD

**Issue by bttger** [calcom/cal.com#2426]
### Issue Summary

Someone requested a booking for an opt-in meeting (see advanced meeting options). I did not respond in time and the meeting is now within the "past" tab - thus I can't confirm/decline it (it still shows the yellow "unconfirmed" chip). I still get endless "Awaiting Approval" emails for this meeting.

### Steps to Reproduce

1. Create opt-in=true meeting
2. Request a booking
3. Don't respond to the request until it shows in the "past" tab under your bookings
4. Get endless emails awaiting your approval for this booking request

**Comment by milospuac** [comment]
Hi Tom. Thanks for reporting this. Our team will address this issue

**Comment by jjromary** [comment]
@bttger , @milospuac . Can you show me with an image where the "non-optional" field is. I couldn't find it.

**Comment by bttger** [comment]
> @bttger , @milospuac . Can you show me with an image where the "non-optional" field is. I couldn't find it.

What do you mean with "non-optional field"? What I was talking about in the issue was the opt-in meeting option in the advanced settings of an event. At the moment it's a checkbox with the name "Requires confirmation".

**Comment by jjromary** [comment]
OK I understand. Thanks.

**Comment by jjromary** [comment]
Apparently this error has already been fixed in this Issue. [#3007](Prevents past booking confirmation emails to be sent #3007).

I also performed tests on localhost and the bug reported by you did not occur.

**Comment by bttger** [comment]
Sounds good but I'm sorry, I cant validate it since I've switched the tool.

**Comment by joeauyeung** [comment]
Closing, fixed in #3007
