### ISSUE TITLE
Need to update README.md

### ISSUE THREAD

**Issue by dev-eth** [calcom/cal.com#2428]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

- At the Manual setup section’s 3rd item, **schema.prisma** path is wrong.

`apps/web/prisma/schema.prisma` should be` packages/prisma/schema.prisma`.

- At the Setup section’s 3rd item, `cp apps/web/.env.example apps/web/.env` -> .env.example file does not exist in this path.
`cp apps/web/.env.example apps/web/.env` should be `cp .env.example .env`.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by milospuac** [comment]
Thanks for reporting this. Our team will have look into this

**Comment by dev-eth** [comment]
Ok.

**Comment by dev-eth** [comment]
In the README.md, we also need to mention about node version so the contributors can set up the correct one.

`The engine "node" is incompatible with this module. Expected version ">=14.x <15".`
