### ISSUE TITLE
Microsoft Exchange Server 2010: Couldn't retrieve message

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#2429]
### Issue Summary

When using an email adress, which runs on Microsoft Exchange Server 2010 (connected via smtp/imap), I always get these errors via email when scheduling or rescheduling:

```
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: mail@example.com
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 522
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Meeting with [...]"
From: "Not available" ("Not available")
Sent date: 07.04.2022 21:49:08

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
```

This probably seems to be a problem with the `event.ics` attached.

### Steps to Reproduce

1. Set an email adress in backend (Settings), that runs on Microsoft Exchange Server 2010 
2. Schedul a meeting
3. Recieve the error email instead of the scheduling notification.

### Technical details

- Browser version: Firefox 99.0
- Node.js version: v14.19.1
- cal.com selfhosted
- Anything else that you think could be an issue.

**Comment by milospuac** [comment]
Hey Benedikt. Thanks for reporting this, one of our engineers will look into the issue.

**Comment by bhopmann** [comment]
I investigated a little bit and probably found a solution by adding `method: "CONFIRM",`after `status: "CONFIRMED",` in the following both files:

https://github.com/calcom/cal.com/blob/a0057911c1e2b7753e98b80bce7157764ee39a29/apps/web/lib/emails/templates/attendee-scheduled-email.ts#L75

https://github.com/calcom/cal.com/blob/a0057911c1e2b7753e98b80bce7157764ee39a29/apps/web/lib/emails/templates/organizer-scheduled-email.ts#L73

**Comment by bhopmann** [comment]
Closed PR because I'm not really shure, if `CONFIRM`is the right `method` variable which seems to be missing.

**Comment by PeerRich** [comment]
@bhopmann wanna give this another look?

**Comment by PeerRich** [comment]
added a bounty

**Comment by PeerRich** [comment]
is this still open?
