### ISSUE TITLE
Zoom link missing when rescheduled from In-person meeting to zoom video

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#2431]
### Issue Summary

When rescheduling an event and changing from In-person meeting to zoom video, the zoom link is missing in the notification email:

<img width="403" alt="Bildschirmfoto 2022-04-08 um 09 48 36" src="https://user-images.githubusercontent.com/2770597/162390193-551e9d18-cfd3-48e7-9d74-82ea829b44b2.png">

### Steps to Reproduce

1. Set an event type with location options In-person meeting and zoom video
2. Schedule an event with location In-person meeting
3. Reschedule event to any time slot and change location from In-person meeting to zoom video
4. Have a look at the notification email

### Technical details

- Browser version: Firefox 99.0
- Node.js version: v14.19.1
- cal.com selfhosted

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will have a look into this issue

**Comment by andreaestefania12** [comment]
Hi, I would like to contribute to this issue. Could you assign it to me, please?

**Comment by bhopmann** [comment]
This sounds good @andreaestefania12 
If I understand it correctly @milospuac would have to make the assignment (I do not have the permissions to do this).

**Comment by PeerRich** [comment]
hey, can you try the latest version again?

**Comment by PeerRich** [comment]
i think this has been fixed
