### ISSUE TITLE
[CAL-2181] Canceled and rescheduled events not updated in Google Calendar

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#2434]
After a few test bookings I made and canceled yesterday, I noticed today that these events are still in my Google Calendar 

<img width="496" alt="Screen Shot 2022-04-08 at 13 03 22" src="https://user-images.githubusercontent.com/97884287/162452872-6ad550c3-4406-4798-8a92-0ee4f9f4867f.png">
<img width="454" alt="Screen Shot 2022-04-08 at 13 11 40" src="https://user-images.githubusercontent.com/97884287/162452958-9039e9ec-784e-4a14-b17b-1c05641147ad.png">

After that I tried to see if rescheduled events are moving - they are not.

<img width="1013" alt="Screen Shot 2022-04-08 at 13 08 10" src="https://user-images.githubusercontent.com/97884287/162453129-793c0a6a-943e-4059-8915-400339a3e7bb.png">
<img width="952" alt="Screen Shot 2022-04-08 at 13 08 23" src="https://user-images.githubusercontent.com/97884287/162453134-49b22ef1-2b58-47ab-b24e-2e7100e120a5.png">

<sub>[CAL-2181](https://linear.app/calcom/issue/CAL-2181/canceled-and-rescheduled-events-not-updated-in-google-calendar)</sub>

**Comment by dninomiya** [comment]
Apple Calendar has the same bug. Reschedule not synced and old appointments stuck.

**Comment by PeerRich** [comment]
> Apple Calendar has the same bug. Reschedule not synced and old appointments stuck.

@alishaz-polymath can you investigate this?

**Comment by PeerRich** [comment]
@joeauyeung @alishaz-polymath still open? if yes, high priority

**Comment by hariombalhara** [comment]
I don't think this is an issue anymore, it could have been a bug at that time, but there are no complaints anymore.
