### ISSUE TITLE
[CAL-895] Insert meeting times into email

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2438]
### Discussed in https://github.com/calcom/cal.com/discussions/973

<div type='discussions-op-text'>

<sup>Originally posted by **cherie-yang** October 16, 2021</sup>
**Feature suggestion: Insert suggested meeting times directly into email**

Sometimes, sending a link just doesn't cut it, and it's really handy to allow guests to see times and click directly to schedule from their email.

![image](https://user-images.githubusercontent.com/56347672/137595790-2cce1a9e-61e2-45d5-8a62-e3493deda370.png)
![image](https://user-images.githubusercontent.com/56347672/137595792-bae2e550-669d-4dd0-bca5-8f89f592ab20.png)

Need to have:
- Title of event
- Each time slot as a clickable link
- Time zone
- Link to 'view more' to see other times

Notes:
- Calendly allows you to add times from the Chrome extension or from the website. When [using the extension](https://calendly.com/blog/insert-availability-email/), you only view/select the dates, but cannot view/select **_specific times_**. This is quite frustrating when sending availability in a different time zone. You could end up with times that are at OOO hours for the recipient, and so there's some time wasted in picking out new dates that yield more favourable times.
- Having a max number of dates/times that can be selected is useful in reducing cognitive overload.</div>

<sub>[CAL-895](https://linear.app/calcom/issue/CAL-895/insert-meeting-times-into-email)</sub>

**Comment by juliansg022** [comment]
Hey @PeerRich, I want to work on this issue. Could you assign it to me, please?
