### ISSUE TITLE
Add webhook examples or native integration with n8n.io

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2439]
### Discussed in https://github.com/calcom/cal.com/discussions/926

<div type='discussions-op-text'>

<sup>Originally posted by **ianhyzy** October 12, 2021</sup>
I'm muddling through this on my own, but I think it would be super helpful for someone with more knowledge than me to provide examples of using Webhooks with n8n (cal.com is to Calendly as Zapier is to n8n). I have a basic flow here using Pushover to send me a notification when an event is booked, but I'm still working on making times show up in a human readable way:

![image](https://user-images.githubusercontent.com/3400872/137026564-84aaa9c7-67de-4f4f-9aa8-419bea2d25d8.png)
![image](https://user-images.githubusercontent.com/3400872/137026596-59854630-5f9c-49aa-af38-ce20ec64db81.png)

Of course, native integration is always great too.</div>

**Comment by saschafoerster** [comment]
I would also love to see a deep integration of Cal.com into N8N in two directions: 
- Cal.com Trigger: Someone creates or moves an event in cal.com, which then creates a trigger in N8N
- Some other integration of N8N can use the API of Cal.com to see if appointments are possible, and if booked, Sents the confirmation link? (I hope this makes sense?) 

Calend.ly has already some integration in N8n: https://docs.n8n.io/integrations/credentials/calendly/

**Comment by alishaz-polymath** [comment]
This is now merged 🚀

**Comment by saschafoerster** [comment]
@alishaz-polymath Where can I find it? I would like to try it out.

**Comment by alishaz-polymath** [comment]
Hi @saschafoerster 
It was merged 2 days ago [see here](https://github.com/n8n-io/n8n/commits/master) and should be availabe in their latest release.
🙏 
You can fork their repo and test it out locally right away or wait for their official release (not 100% sure when that is)

**Comment by saschafoerster** [comment]
@alishaz-polymath Are webhooks available for everyone or only licensed installations?

**Comment by alishaz-polymath** [comment]
Currently, they're available for all accounts at Cal.com

**Comment by alishaz-polymath** [comment]
The way it is designed, it should be usable for all self hosted installations as well. It is baked into the trigger events. However, this may change at a later stage. Until then, it is definitely usable in self hosted versions too!
