### ISSUE TITLE
Document current {USER} token & offer some additional?

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2443]
<div type='discussions-op-text'>

<sup>Originally posted by **timfee** September 22, 2021</sup>
I saw that the default title for an event was `Meeting with {USER}` but from that, I wasn't sure if `{USER}` would be replaced with my name, with the attendee name, etc. 

The [code](https://github.com/calendso/calendso/blob/main/lib/event.ts) suggests that `{USER}` is the attendee:
```ts
  return eventNameTemplate ? eventNameTemplate.replace("{USER}", name) : eventTitle + " with " + name;
```

1. It might be good to call this out in the UI / docs.
2. It'd be great to reference other primitive fields (e.g. location, `Zoom: User1 <> User2`)
3. I could see future use cases wanting to access custom fields, etc. 

For now, I was able to confirm that `{USER}` was the only magic token, and it is replaced with the *full text* entered by the invitee.  :) </div>

**Comment by milospuac** [comment]
The only problem would be that the same title appears in the attendee's calendar. 

For example, if your title for an event is `Meeting with {USER}`,  and I booked a meeting with you, In your calendar it would say `Meeting with Milos`, but the same title would appear in my calendar. Like I have a meeting with myself.  So you gotta be careful how you structure your variable.

**Comment by niklasgrewe** [comment]
as milospuac said, I also find it quite inconvenient that the event name is the same on both sides. It would be great if you could set the event name differently. This is already implemented in the email subjects, for example. If your title for an event is `Meeting with John` my email subject is `Confirmed: Meeting with John` and the subject for John is `Confirmed: Meeting with Niklas Grewe`

**Comment by Jaibles** [comment]
I also find this very confusing in the UI as to what {USER} refers to and what other parameters might be available to me if I was to change it.
