### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2450]
- show the weather of the day (https://www.producthunt.com/posts/weather-in-your-calendar) 
- add the weather of in-person events (based on address)
- auto-schedule going for a walk one a sunny day

**Comment by miguelnietoa** [comment]
Hey there, how can I contribute to this? Could you explain a little bit more, please?

**Comment by agustif** [comment]
@miguelnietoa 
This is the OG app, basically, make an app that can generate virtual calendars with upcoming weather from open weather map when app is installed in cal.com
https://github.com/vejnoe/weather-in-your-calendar
https://github.com/vejnoe/weather-in-your-calendar/blob/master/weather-cal.php

**Comment by jkdamilola** [comment]
Hey @agustif @PeerRich, I would like to work on this issue if no one else has already taken it up. Thank you.

**Comment by PeerRich** [comment]
sure @jkdamilola go for it!
