### ISSUE TITLE
Availability not updated when there is no calendar integration

### ISSUE THREAD

**Issue by superseby2** [calcom/cal.com#2457]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a user has no calendar integration, his/her availability slots are no corresponding to what's really available 

### Steps to Reproduce

1. a regular user with 1 event Type and availabilities going from 9am to 5pm every day 
2. create an event at 9:00AM using his/her booking page
3. re-open the booking page
4. the 9:00am slot is still proposed 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- Booking the slot will fail eventually.
- What is expected is not to see the 9:00am slot at all.

### Technical details
- The pb appears on hosted docker (1.4 tag) and on Cal.com

**Comment by milospuac** [comment]
Hi there! at this point in time, we do not yet check our own events for conflicts (intended to be added by the virtual calendar). This feature is currently being built, and until then, calendar integration is pretty much mandatory.  

Thanks for reaching out
