### ISSUE TITLE
Event Type Preview Link Not correct + Does CalDav Server support nextcloud Calendar?

### ISSUE THREAD

**Issue by barrenreaction278** [calcom/cal.com#2463]
Self Hosted Cal Ubuntu

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce
 
1. Went to Event Types the preview link is giving `https://example.com/undefined/example/15min` however when going to such link gettting 404 error the real link to scheduling is `https://example.com/example/15min `without the undefined how do I remove this fix this?

2. Go to Apps CalDav Server, Install App, input https://example.com/nextcloud/remote.php/dav (replaced (http://example.com/) with my domain ofcourse) and user/pass for nextcloud however getting error `Could not add this caldav`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
The preview link isnt the link for each event type undefined needs removing 
Does CalDav Server in Cal support nextcloud calendar?

**Comment by janbaykara** [comment]
We're using Cal.com with Nextcloud and it seems to more or less work.

**Comment by alishaz-polymath** [comment]
Closing this as obsolete due to inactivity and major upgrades since this was opened. Feel free to re-open if you face this issue with the latest pull 🙏
