### ISSUE TITLE
Visible Multiple renders on team booking page

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2467]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

See this https://app.birdeatsbug.com/workspaces/62c323a9-51c4-4184-84ab-72dd1c5f8def/sessions/jSL7NHZCT5xWX7X3foPRHZnTUKa8c6Fn0iLiY5zoHy1V

### Steps to Reproduce

1. Go to https://cal.com/team/krause-house-agents/1-on-1-with-a-kh-agent
2. Observe that the dates and profile pictures re-render twice on
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by gabriellferreira-dev** [comment]
I will work on this problem.

**Comment by PeerRich** [comment]
should be fine now
