### ISSUE TITLE
There is lot of hardcoding links in application

### ISSUE THREAD

**Issue by starpunjabi** [calcom/cal.com#2470]
Can you please move lot of hardcoding links/urls etc. in env or some constant file.
Everytime we pulled the code, we need to compare code and update our code very carefully as we have custom logo, custom web url, custom header footer link that point to home page of our application, but it is very time consuming process  when we pull new features.
adding constants to contant file and then updating code to respective files, so we have to update only .env file. 
Or is there any other workaround for this?
![image](https://user-images.githubusercontent.com/20169304/162944311-5d43e2db-1422-4398-a9b0-864a63cae25a.png)

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our team will look into this

**Comment by starpunjabi** [comment]
Can i fork and contribute in this task, so all hard links can be manage from constants without changing any output.

**Comment by PrincesaTyne** [comment]
@milospuac  Is there a list of all the links that need to be moved to the constants files or ones that should be left as is?
