### ISSUE TITLE
Giphy App

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2473]
select a gif in event types that'll be shown on the success page

**Comment by with-shrey** [comment]
Hey, @PeerRich I am new to this project, seems like a great issue to get started with :-).
Can I take this up? 

Let me know if you have any suggestions or pointers for me.

**Comment by PeerRich** [comment]
go for it! here's more: https://docs.cal.com/developer/app-store @joeauyeung @zomars  is this still up to date?

**Comment by joeauyeung** [comment]
Hey @with-shrey thanks for hopping on this. I'm waiting for the new changes to the app store doc to be reviewed but you can read it here:  https://github.com/calcom/cal.com/pull/2567

**Comment by with-shrey** [comment]
Thanks

**Comment by with-shrey** [comment]
@PeerRich 

Here is the plan of action that I am planning for. do let me know if you have any suggestions.

1. Add an app named "Giphy" under "Other" category ✅ 
2. The app would be installed by default for all users (Since we don't need authentication etc).
3. Add an input for Giphy selection on `/event-types/:eventId`.
4. Display the selected Giphy on `/success` in place of the green checkmark 

FYI: I have joined calcom slack.

**Comment by PeerRich** [comment]
> @PeerRich 
> 
> 
> 
> Here is the plan of action.
> 
> Do let me know if you have any suggestions.
> 
> 
> 
> 1. Add an app named "Giphy" under "Other" category ✅ 
> 
> 2. The app would be installed by default for all users (Since we don't need authentication etc).
> 
> 3. Add an input for Giphy selection on `/event-types/:eventId`.
> 
> 4. Display the selected Giphy on `/success` in place of the green checkmark 
> 
> 
> 
> FYI: I have joined calcom slack.

yes but i would not have it installed by default

**Comment by with-shrey** [comment]
@PeerRich 
Opened a PR for this [here](https://github.com/calcom/cal.com/pull/2580)
Let me know how this looks

**Comment by zomars** [comment]
> Haven't added tests for this yet, let me know what type of tests I need to add to get this merged. 

I don't think we need E2E tests for this use case for now.

> Also, do I need to find translations for the texts that I have added in English, or are there people who can help me out with that?

Once this is merged our Crowding collaborators will be notified that there are new strings to translate.
