### ISSUE TITLE
Event Cancelled/Rescheduled By

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#2477]
### Is your proposal related to a problem?

Currently, we don't provide any details about who cancelled the event. It is obvious for single user event types as it is either the organizer or the booker who cancels it, and both parties are aware. However, when we talk about collective events (Dynamic or Team), it would be nice to know who cancelled/rescheduled the event. 

(Write your answer here.)

### Describe the solution you'd like

- Everytime an event is cancelled or rescheduled, it should contain information of who cancelled or rescheduled the event.

**Comment by jjromary** [comment]
Hi, @alishaz-polymath. Can I work on implementing this feature?

**Comment by alishaz-polymath** [comment]
Hey @jjromary 
Of course. Have a go, we'd greatly appreciate it 🙏

**Comment by zomars** [comment]
From PR #3899 

> The issue #2477 is not on our Core roadmap nor has been properly discussed. We should not have PRs for features that haven't been approved. Even if this is a relative simple feature, it is still way too vague to know all the ramifications that can result into maintaining and improving upon this feature.
> 
> Some examples:
> 
> * Do we want to show the cancellation author email each time? If not, that another settings to add
> * Do we want to save the cancellation author in the DB?
> * Are there cases where this behavior is unexpected/unintented?

**Comment by aasargsian** [comment]
In case the feature request gets revisited, here is an additional business case: We typically used the cancelledBy attribute to better define the next action. For example, If the teleconsultation is canceled by the host - we call back the attendee to rescheduled. If the teleconsultation is cancelled by attendee - there is usually no action required.
