### ISSUE TITLE
Rescheduling a paid bookings shouldn't ask to repay

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#2481]
I tried to reschedule a paid booking and is asking me to pay again. Is this the intended behavior? cc @alannnc @Jaibles @PeerRich 

![image](https://user-images.githubusercontent.com/3504472/163276646-07d8254c-062a-4e7c-b672-e62f2272f8a4.png)

_Originally posted by @zomars in https://github.com/calcom/cal.com/issues/2351#issuecomment-1098523101_

**Comment by Jaibles** [comment]
This will be tackled in https://github.com/calcom/cal.com/issues/2794
