### ISSUE TITLE
Bug when checking availability and switching time zones

### ISSUE THREAD

**Issue by harish-kamath** [calcom/cal.com#2482]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to book an event, if I switch the time zone before clicking a specific date, then the proposed times do not update to the correct time zone.

### Steps to Reproduce

1. Go to any cal.com invite link.
2. Select a time zone different from the default _before_ selecting a date.
3. Select a date.

Notice that the proposed times are not updated, even though the time zone at the left reflects the updated time zone. Reselecting a time zone also does not help.

### Technical details

Using latest version of Google Chrome in Incognito mode.

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will have a look into this

**Comment by buschco** [comment]
I created a PR targeting this issue 

-> https://github.com/calcom/cal.com/pull/2506

**Comment by harish-kamath** [comment]
Looks great! 🚀
