### ISSUE TITLE
"Back to Bookings" doesn't work if cancellation page is opened directly.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2497]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cancellation link can be opened directly as it is shared in Google Calendar. "Back to Bookings" button doesn't work in that case.

### Steps to Reproduce

1. Go to Bookings Page
2. Choose a booking to cancel
3. Copy cancellation link and open in new tab
4. Notice that "Back to Bookings" doesn't work

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
https://app.birdeatsbug.com/sessions/Y32OmI-ID0VIROI3v5gVt3U9AHaNdgEiIiXVmc80nlaw?

**Comment by victorgbaye** [comment]
Could a loom video be attached to this issue to understand the issue better?

**Comment by hariombalhara** [comment]
There is a birdeatsbug recording link. Doesn't that help?

**Comment by joeauyeung** [comment]
Closing, fixed in #2634
