### ISSUE TITLE
No html in sent and received emails. Unable to find where email string is being created.

### ISSUE THREAD

**Issue by EclipseKnight** [calcom/cal.com#2510]
### Issue Summary

Emails being sent (while utilizing teams integration event-type, unsure of others) have no html formatting in the received and sent emails.

### Steps to Reproduce

1. booking, rescheduling, or any of the other email templates under the path apps>web>lib>emails>templates don't produce any html in the emails despite there visibly being html in the getTextBody() functions.

### Technical details

I made several attempts to pinpoint where the email string is being made but everything points back to the `getNodeMailerPayload()` call in the email template files. Upon trying to modify the fields `html: this.getHtmlBody()` & `text: this.getTextBody()` nothing actually happens and the emails send as normal. Even when trying to replace the getHtmlBody() calls with a string.

I confirmed changes were being applied on yarn build via several console logs and visual website modifications. 
My goal was to pretty up the email so its not just a single line of links with no styling of any sort, which I predict isn't the initial intent based on the html seen in the email templates. I also wanted to add audio conferencing information to the email.

I did everything to try and even break the call but no matter what I did in all of the email templates, the same string would be produced in the email. 

Both my colleague and I are absolutely lost as to where the string is being created since none of our attempt and breaking this seemed to have work.

At one point I did print out the payload right before it sent and saw no html in it at all, but once again it doesn't seem to be using the html and text fields in the record at least from my testing.

**Comment by sean-brydon** [comment]
Hey @EclipseKnight are you able to provide a demo of what your emails are looking like? On our end they look like this when they are sent 
![CleanShot 2022-04-15 at 21 47 32](https://user-images.githubusercontent.com/55134778/163630562-4ea72ec3-e395-4f9c-aacd-47c2eca7b719.png)

**Comment by EclipseKnight** [comment]
Here is from the sent mailbox (excuse the outlook darkmode).

![image](https://user-images.githubusercontent.com/32472185/163809333-8b68c254-7698-4b51-b608-c256720975ef.png)

checking the email's source:
```
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">What:
Test
  

Invitee Time Zone:
America/New_York
  

Who:

Jon Paquin - Organizer
organizer@email.com
  
test
attendee@email.com
      
  
Where:
Office365_video

Additional notes:
test
  

Need to reschedule or cancel?
https://cal.example.com/cancel/tcx71K2hgoBXm9QARK2Y4f
```

**Comment by sean-brydon** [comment]
Are you self hosting or using Cal.com ?

**Comment by EclipseKnight** [comment]
Self hosted

**Comment by PeerRich** [comment]
this seems to be specific to your email service. can you try a different one?
