### ISSUE TITLE
Input field only one digit

### ISSUE THREAD

**Issue by andreasklinger** [calcom/cal.com#2526]
### Issue Summary

The input field for "Invitees can schedule" is only 1 digit wide

### Steps to Reproduce

![](https://p195.p4.n0.cdn.getcloudapp.com/items/bLuKZJ1y/d6c962e4-c7d1-426a-9d5c-a5227835695d.jpg?source=viewer&v=37a6933f127224c2a42cef23ad91821a)

This number is 12

### Technical details

Browser Brave
Release Notes V1.37.116 (Apr 14, 2022)

**Comment by PeerRich** [comment]
thanks!

**Comment by PeerRich** [comment]
@alishaz-polymath or @sean-brydon can pick this up
