### ISSUE TITLE
Changing an email after signing in with google causes a bit of a mess

### ISSUE THREAD

**Issue by kof** [calcom/cal.com#2527]
### Issue Summary

I used google sign-in to create an account and connected zoom with it. Then I changed the email in the settings. 

After I did that, I couldn't disconnect zoom anymore, it would say it has successfully disconnected, but would still show it under installed apps.

**Comment by kof** [comment]
Now I logged out and logged in again, my email went back to the original one I used initially with google sign in

**Comment by kof** [comment]
Now I tried to change the email again, then logged out and tried to use google sign-in with the new email and got this error
<img width="494" alt="Screenshot 2022-04-16 at 11 03 46" src="https://user-images.githubusercontent.com/52824/163670827-a709b6e8-1e2f-4281-960b-0955fb6dd2c5.png">

**Comment by kof** [comment]
Then I went back to login and used original google login I used to sign up - it worked and settings now show again the original email.

**Comment by kof** [comment]
It seems that the problem with changing email in settings is that its only changing the email signature that is used in confirmation emails, but doesn't actually change my sign-in, maybe that's intentional? 

In any case, my issue has diverged from disconnecting zoom to changing email, those are 2 separate issues.

**Comment by kof** [comment]
Here is a complete picture of what has happened originally and how I fixed it:

1. I signed up with google sso using email A
2. I renamed my email from settings to email B
3. I tried to add Zoom connection, it worked, but was not adding a link to zoom channel, but instead just writing "Zoom" instead of a link

Fix

1. I logged out and logged in again from the original A account using google sso
2. It changed my email back to the original one
3. I disconnected and connected zoom again
4. Now zoom links are correct in the calendar and emails
5. Now I changed my email again to the B, so people see it in the email
6. Now the only discomfort is that I have to log in with email A (which is the private one) and I can't see how I can change the sign in to email B

**Comment by PeerRich** [comment]
i believe @agustif has been working on a fix for this

**Comment by PeerRich** [comment]
@deepakprabhakara is this related to SAML?

**Comment by PeerRich** [comment]
yes, agree we need to make switching ID provider easier. for now please message support@cal.com when switching
