### ISSUE TITLE
Wrong subject for Reschedule email

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2537]
<img width="1450" alt="Screenshot 2022-04-18 at 9 50 26 AM" src="https://user-images.githubusercontent.com/1780212/163753857-3fc22f78-24e4-4bc3-9e75-4c86f3a05e88.png">

Steps:
1. Schedule a booking for today with organizer@example.com using email example@example.com
2. Login as organizer and Wipe Today
3. See that the email received by example@example.com has the grammatical mistake.

**Comment by alannnc** [comment]
Can you provide me further information? Was this on production? Can you get me the uid? 
Did a quick test and find everything was working fine, but there should be something wrong with the original event title

**Comment by hariombalhara** [comment]
@alannnc Will try to replicate and share details.

**Comment by hariombalhara** [comment]
He @alannnc, just to be clear, 18th April, was the name so forget about that. I just noticed that it might be creating confusion. Sorry about that. 
The real problem that I was trying to report was, "Please book a new to time for". It should probably have been "Please book a new time for"

**Comment by hariombalhara** [comment]
Just confirmed that the subject is still grammatically wrong. Updated steps in description.

Also noticed another grammar mistake, 
<img width="625" alt="Screenshot 2022-04-20 at 9 48 05 AM" src="https://user-images.githubusercontent.com/1780212/164149866-336911a9-8a50-424f-8044-80710c43c518.png">

**Comment by alannnc** [comment]
You are right there, changed. Thank you! @hariombalhara
