### ISSUE TITLE
Feature Request : more Productive/Efficient time slots

### ISSUE THREAD

**Issue by esprush** [calcom/cal.com#2538]
Kudos for the great product. 

### Is your proposal related to a problem?

I have a feature request where the efficiency of time slots generated for a day can be better.
consider below case:
1. User has two event types 15 min and 30 min with working day as 9-6.
2. Invitee 1 books a 15 min slot at 9:00
3. Invitee 2 books another 15 min slot at 9:45
4. when invitee 3 tries to book a 30 min slot, the suggested times are 10:00,10:30....
5. Here another slot can be booked at 9:15-9:45

### Describe the solution you'd like

In the above use case would prefer to have the 9:15-9:45 slot also shown to the invitees. This will make the user's time more productive.
<hr/>

I can take this if we think this would be a valuable addition to the product.

**Comment by milospuac** [comment]
Hi there. 

Thanks for reaching out.

Do you have a buffer time selected?

**Comment by PeerRich** [comment]
you can achieve this with buffers
