### ISSUE TITLE
Field validation

### ISSUE THREAD

**Issue by JoeyFenny** [calcom/cal.com#2540]
### Is your proposal related to a problem?
No

### Describe the solution you'd like
Say I have a question on an event type. That question I want people to paste a URL. Right now I can use a text input field but there is no validation. They can type something in there that is not a URL.

### Describe your proposed solution here.
Allow people to set validation rules whether via regex or other means. If they type something that does not match, they should perhaps receive a toast notification and not be allowed to proceed.

### Describe alternatives you've considered

None exist that I'm aware of. For now, I've forked this repo and added a half-baked implementation of this.

**Comment by milospuac** [comment]
Hi Joey! Thanks for reaching out. Our team will look into this.

**Comment by Jaibles** [comment]
Resolved with https://github.com/calcom/cal.com/pull/2612

**Comment by JoeyFenny** [comment]
@Jaibles while #2612 is great, it is not exactly the feature I described. #2612 validates name and email. I was proposing a feature that allows users to set a validation rule for custom inputs. Perhaps a regex. If I ask people for a URL, it should pass on https://google.com and fail on "I don't have one". This can be done by allowing people to specify a regex when creating a text string. Then it will test against the user-provided regex and fail on a mismatch. Or for something like the number field, it should fail if the number is less than, or greater than, or not equal to, etc. Perhaps shows a warning label or toast upon fail. This allows people to keep the calendar clear from unqualified leads. #2612 only adds validation for name and email but no option for validation of user-created questions.

**Comment by JoeyFenny** [comment]
Note it wasn't an issue, it was a feature request.
