### ISSUE TITLE
Allow users to paste header code snippets

### ISSUE THREAD

**Issue by JoeyFenny** [calcom/cal.com#2542]
### Is your proposal related to a problem?

No

### Describe the solution you'd like

Allow us to paste code snippets into the document head. E.g. analytics tracking tag to see how many users are visiting the site.

### Describe alternatives you've considered

Using Cloudflare for analytics but this would be significantly less detailed than what I could obtain with a custom tracking code.

**Comment by agustif** [comment]
This seems highly dangerous to allow with *any* code snippets, I think your functionality might be more appropiate to a new app-store app that you can give your UA-XXXX tracker for GA or CloudFlare or whatever, but I cannot see us allowing any js snippet being run.

**Comment by JoeyFenny** [comment]
I agree. Just some sort of basic tracking, mainly something like: How many people visited the page? How many of those people actually booked a call? I think that would suffice.

**Comment by PeerRich** [comment]
we added a few analytics apps. for now we wont allow pasting scripts due to security reasons
