### ISSUE TITLE
Location isn't clickable nor preselected when rescheduling

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#2543]
### Issue Summary

When rescheduling, location isn't clickable nor preselected. Thus, the event can't be rescheduled.

### Steps to Reproduce

1. Make a new booking
2. Go to bookings in backend and edit the event

### Technical details
- Browser version: Firefox 99.0.1
- Node.js version: v14.19.1
- cal.com selfhosted

**Comment by milospuac** [comment]
Hey Benedikt. Thanks for reporting this. Our team will address the issue

**Comment by sean-brydon** [comment]
Thanks @bhopmann  for reporting this - I can't seem to replicate this myself would it be possible if you can use a bug reporting tool such as https://app.birdeatsbug.com/ to record a demo of this? Thanks

**Comment by bhopmann** [comment]
Thank you for your reply @sean-brydon - I've made a screenshot, which hopefully helps:

<img width="381" alt="Bildschirmfoto 2022-04-19 um 15 56 28" src="https://user-images.githubusercontent.com/2770597/164022438-a75bad1d-c51b-4ff6-a2fc-a6bfc86c323f.png">

**Comment by bhopmann** [comment]
A brief addition: It does work when only using one location. When using mutiple locations none of them is preselected nor clickable.

Using the Firefox-Debugger/Development-Tool, the sourcecode is missing any checked attribute, the linked `js`file seems to be invalid:

<img width="858" alt="Bildschirmfoto 2022-04-23 um 16 40 58" src="https://user-images.githubusercontent.com/2770597/164910752-6fe96c53-b7a1-4932-9c6b-d8e4ff5e2186.png">

**Comment by bhopmann** [comment]
This seems to be a similar issue report #2622

**Comment by sean-brydon** [comment]
Investigating this today @bhopmann  :) Thank you

**Comment by PeerRich** [comment]
location should be able to be changed!
