### ISSUE TITLE
[CAL-2875] Please add a `Minimum cancellation/rescheduling notice` time.

### ISSUE THREAD

**Issue by bassamanator** [calcom/cal.com#2546]
### Is your proposal related to a problem?

Our 'organizers' are professionals providing health services. It would be very frustrating if clients, aka attendees, were able to cancel/reschedule appointments 1 minute before the booking start time, for example.

### Describe the solution you'd like

In the advance settings section of event-types, there is already an option for `Minimum booking notice`. Please add an option for `Minimum cancellation/rescheduling notice`. It might also help to have separate settings for cancellation notice and rescheduling notice.

### Describe alternatives you've considered

I see no other option than removing the `manage link` from the emails sent to attendees. This is not desirable.

### Additional context

Minimum cancellation notice time is a standard requirement for many professional services.

<sub>[CAL-2875](https://linear.app/calcom/issue/CAL-2875/please-add-a-minimum-cancellationrescheduling-notice-time)</sub>

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Yep, being able to cancel a minute before doesn't quite ooze professionalism. I will share this with the product team

**Comment by MatheusBeniniF** [comment]
i'm working on this issue and i think i've already found a solution for it

**Comment by juliopiubello** [comment]
Hi @milospuac ! We want to contribute to this issue but we are not sure with what solution you would like to

- should we set a default minimum time before to cancel/reschedule of like 15 minutes
- should it be a new field to the event, adding it to the database the amount of time the user picked

**Comment by aspiers** [comment]
I don't think this should have been closed, as clearly it's a bad situation to allow last minute cancellations.

[**@juliopiubello**](https://github.com/juliopiubello) commented on [Jun 9, 2022, 7:13 PM GMT+1](https://github.com/calcom/cal.com/issues/2546#issuecomment-1151446149 "2022-06-09T18:13:36Z - Replied by Github Reply Comments"):
> Hi @milospuac ! We want to contribute to this issue but we are not sure with what solution you would like to
> 
> - should we set a default minimum time before to cancel/reschedule of like 15 minutes

Yes, there should be a default.

> - should it be a new field to the event, adding it to the database the amount of time the user picked

I think the minimum cancellation time should be set per event type rather than per event, just like all similar options (e.g. minimum time which doesn't require confirmation).

**Comment by itsberkaya** [comment]
https://www.figma.com/design/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=21984-750627

<img width="2503" alt="Ekran Resmi 2024-07-16 17 01 43" src="https://github.com/user-attachments/assets/beabed97-297e-4bf7-b782-6546c8174dc2">

**Comment by ciaranha** [comment]
Duplicate of https://github.com/calcom/cal.com/issues/15647
