### ISSUE TITLE
`Unconfirmed` bookings prevent other attendees from booking the same time slot.

### ISSUE THREAD

**Issue by bassamanator** [calcom/cal.com#2550]
### Issue Summary

I created an event-type that requires confirmation. Contrary to expectation, an **unconfirmed** booking is preventing other attendees from booking the same time slot. It should be up to the organizer to pick the attendee they would like to book if there are multiple attendees for the same time slot. **This also leaves room for mischief**: a bad-faith attendee could potentially block an organizer's schedule, creating a situation where the organizer would have to continuously watch for and reject bookings by said attendee.

### Steps to Reproduce

1. Create an event-type that requires confirmation.
2. Click preview to create a booking for this event-type (you're acting as attendee `John` in this step).
3. Do not confirm the booking.
4. Click preview again to create a booking and pick the same time that `John` picked (you're acting as attendee `Bob` in this step).
5. `Bob` will not be able to pick the same time slot that `John` picked *even though* `John's` booking was not confirmed by the organizer.

### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I'm calling this a bug because I don't remember encountering this behaviour in release v1.2. 

### Expected behaviour
The organizer should be able to pick and choose the attendee they would like to book if there are multiple attendees trying to book the same time slot.

### Technical details

No tech specs are relevant here.

@agustif

**Comment by MuriloAmarals** [comment]
When i was trying to reproduce the bug, i didn't have the same issue as you. I will paste here a link of the video I try to reproduce the bug.
https://www.loom.com/share/eff1cea609944dc3bfbf386871995fed

**Comment by bassamanator** [comment]
@MuriloAmarals Thanks for looking into this! You did not create a booking, however. The server does not keep track of bookings **were not made**. 

Please try again, but follow through with the booking and click Confirm at the end. There is a fix in the works it seems, this issue might be resolved before you have a chance to try.

Thanks!
