### ISSUE TITLE
The time format does not work as expected.

### ISSUE THREAD

**Issue by angel8au** [calcom/cal.com#2557]
Found a bug? Please fill out the sections below. 👍

The time format does not work as expected. In my settings I configured 12 hours and when I send the link of my availability the hours appear in 24-hour format.

I trying to find in the setting of the event but there is not anyting to configure 12 hours.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

Firefox

**Comment by milospuac** [comment]
Hi there.

Thanks for reaching out

The booking page follows the browser's preferred settings. Can you check that for me? 

Also, it would be good to clear your cache/cookies. 

Let me know

**Comment by clarkhacks** [comment]
Experiencing the same issue here. I've set browser preference to both 12 and 24 hours formats. The scheduling time is till stuck in 24hr. IOS, Android, Windows 11/10. Firefox, Safari, Edge, Chrome. All report the same issues.

**Comment by Thiagomn1** [comment]
I'm working on this issue

**Comment by PeerRich** [comment]
fixed a long time ago
