### ISSUE TITLE
[CAL-896] overlay your own calendar (see calendly, savvycal)

### ISSUE THREAD

**Issue by joshmcbride** [calcom/cal.com#2558]
### Is your proposal related to a problem?

When someone uses my cal.com link to book time, they have to toggle back and forth between their calendar and Cal. It would be great if they could connect their calendar and Cal surfaces  up mutually available times to book. 

### Describe the solution you'd like

I click on a Cal link, I then oAuth my Google Cal, Cal then suggested day/time blocks where me and the person using Cal are both free. 

### Describe alternatives you've considered

Calendly does this if both people are users of Calendly. Super helpful. 

### Additional context

(Write your answer here.)

<sub>[CAL-896](https://linear.app/calcom/issue/CAL-896/ability-for-person-looking-to-book-a-meeting-to-connect-their-calendar)</sub>

**Comment by milospuac** [comment]
Hey Josh. Thanks for reaching out. We don't have the exact timeline for this but we will be adding this feature down the line. 

Thanks

**Comment by PeerRich** [comment]
this is planned!

**Comment by PeerRich** [comment]
TDLR: this is planned with the new booker to "overlay" your own calendar

**Comment by joshmcbride** [comment]
Amazing. Thanks for following up on a request submitted over year ago. You
didn't forget lol!

**Comment by PeerRich** [comment]
ok new booker is out. we are really looking to ship this, so many other priorities came in the way tho!

**Comment by Jaibles** [comment]
Designs are not quite ready for dev but very close. 

https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=6078%3A574531&mode=design&t=fctsggcyUGSKKMFJ-1
