### ISSUE TITLE
Migrate team links to <company>.cal.com instead of cal.com/team/team

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#2559]
Currently team URLs are cal.com/team/team, so we should use Vercel Platforms to set up the ability to use a subdomain of cal.com (e.g. adidas.cal.com) instead.

Read the Vercel guide here: https://vercel.com/guides/nextjs-multi-tenant-application

**Comment by PeerRich** [comment]
how should we move forward here?

**Comment by PeerRich** [comment]
the question is, do we do that with ULTIMATE or in the normal TEAMS version

**Comment by PeerRich** [comment]
maybe company.cal.com is an ultimate feature but if you wanna have your own CNAME like cal.company.com you can do that with teams

**Comment by PeerRich** [comment]
tagged as needs design but rather want to talk to @Jaibles and @baileypumfleet about this

**Comment by PeerRich** [comment]
will be part of the organisation overhaul
