### ISSUE TITLE
(draft) RFC: Credits

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2560]
- be able to buy credits (connected to your email) 
- require credits to book

**Comment by pattiewilburn** [comment]
billing subscription options (ie every 4, 18, 12, 16, 3M, 6M, 12M) - sms reminders of any and all upcoming apts, credit limitations per client depending on subscription. is there a way to add the instructor name depending on when they book (we have 2-3 teachers per hour).

**Comment by PeerRich** [comment]
for sms reminders, see #1780

**Comment by PeerRich** [comment]
too niche for now
