### ISSUE TITLE
Users sometimes delete the same schedule multiple times due to delay before the schedule disappears

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#2569]
### Issue Summary

It's possible to delete the same Schedule multiple times if the connection is slow enough - there is nothing to visually show something is happening.

Schedule needs the following popup to be implemented, when a delete is in progress the "Delete Schedule" button should show the loading spinner to prevent further confusion/actions.

⚠️ As part of this fix the same loading spinner should be shown during "Disband Team" for completionism sake.

![image](https://user-images.githubusercontent.com/1046695/164504738-ddcd1df5-9f57-447c-a964-5957f4b52cb4.png)

### Steps to Reproduce

1. Press more actions on the Schedule
2. Press delete Schedule - the dropdown will close
3. Open the dropdown again
4. Press delete Schedule again.

**Comment by arthur1041** [comment]
I can work on this issue.
