### ISSUE TITLE
Location missing in emails when scheduling in-person meeting

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#2583]
### Issue Summary

When scheduling in-person meeting, the location is missing in all emails. Instead, `No App Name` is occuring.

<img width="561" alt="Bildschirmfoto 2022-04-23 um 20 55 55" src="https://user-images.githubusercontent.com/2770597/164942722-5f9fb4ad-fdb0-4103-b238-5736d6154670.png">

### Steps to Reproduce

1. Schedule an in-person meeting
2. See the confirmation email

### Technical details

- Browser version: Firefox 99.0.1
- Node.js version: v14.19.1
- cal.com selfhosted

**Comment by milospuac** [comment]
Hey Benedikt, the fix is almost up https://github.com/calcom/cal.com/pull/2589
