### ISSUE TITLE
show number of installs in app store

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2586]
- track installs with jitsu.track
- connect to jitsu db
- show total installs (across all instances) of each app in the AppCard and detail page

**Comment by PeerRich** [comment]
we should also use jitsu.track for our telemetry: https://github.com/calcom/cal.com/blob/8c173c840bd1bdf2697d4cccd449d807170637bf/apps/web/components/booking/pages/AvailabilityPage.tsx#L101-L106

**Comment by PeerRich** [comment]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/8019099/164948793-e693b299-2ffb-4722-b35b-e99d935a8cee.png">

**Comment by PeerRich** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/8019099/164948818-7475c812-1f07-4166-bc8a-c2789dea4e8a.png">

**Comment by Jaibles** [comment]
Discussing this with @baileypumfleet - have decided that it might be a good idea to hold off doing this until the counts are going to be higher? Will make a note to add this to the designs for the app store improvements.
