### ISSUE TITLE
Fix for the cancellation 500 error

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2613]
If a resource is gone we should catch that and treat it as "Can't delete what's not there" and fail silently.
Found that in some cases, Cancellation request can come again even if the calendar event is already cancelled and thus doesn't exist.

**Comment by LuisChiej** [comment]
Hello @hariombalhara, Could you give more context and possibly a stacktrace so I could help out

**Comment by Jaibles** [comment]
@hariombalhara I am experiencing a bug where I get a 500 error when I cancel a booking. Assume this is related to this issue?
<img width="1728" alt="CleanShot 2022-05-25 at 10 32 21@2x" src="https://user-images.githubusercontent.com/4536123/170231207-f9f9e7b0-90fd-45d4-87b1-aa77d1c8e4ec.png">

**Comment by hariombalhara** [comment]
@Jaibles yes. @joeauyeung is working on a quick fix.

**Comment by Jaibles** [comment]
Great thanks. @joeauyeung can you link your pr to this issue when you have it. Thanks 🙏

**Comment by joeauyeung** [comment]
PRs that fix the most common 500 bugs with Google cal
#2860 #2808 and #2882 that fixes the logic behind it. 

Looking at this I'm going to test without Outlook calendar as well to make sure it fails silently

**Comment by joeauyeung** [comment]
Tested it with Outlook calendar and it doesn't throw the error. Are we good to close this @Jaibles?

**Comment by joeauyeung** [comment]
All 3 PRs are merged and Outlook isn't throwing an error. Closing this issue
