### ISSUE TITLE
Iframe not working in incognito mode => fails to access localstorage

### ISSUE THREAD

**Issue by jakobsturm** [calcom/cal.com#2618]
### Issue Summary

I have embedded our calendar as an Iframe on our website. Unfortunately, it sometimes does not show up or just shows a white or black screen. I have noticed that this problem only occurs when in incognito mode or with restricted cookie settings. A colleague reported the same problem in Safari - but I can not confirm.

The page with the Iframe: https://clipflip.video/get-started.html

In console there is the following error message:
`framework-45ce3d09104a2cae.js:1 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### Steps to Reproduce

1. Embed Iframe on page
2. open incognito mode or strict cookie settings
3. check whether it works

### Technical details

- We are using the hosted version from Cal.com
- The cal.com URL is: https://cal.com/clipflip/demo

Thank you for your help.

**Comment by hariombalhara** [comment]
@jakobsturm There is a fix in review for Incognito issue which throws the error you shared.

For Safari issue, there is already a fix in new embed. Also, it would look much better then the current embed out of the box. This is how it would look https://www.loom.com/share/f8e0417a809045adb61f2f697b37c5b7

You need to remove the existing iframe and instead add the following code in place of that.

```
<script>
  (function (C, A, L) {
    let p = function (a, ar) {
      a.q.push(ar);
    };
    let d = C.document;
    C.Cal =
      C.Cal ||
      function () {
        let cal = C.Cal;
        let ar = arguments;
        if (!cal.loaded) {
          cal.ns = {};
          cal.q = cal.q || [];
          d.head.appendChild(d.createElement("script")).src = A;
          cal.loaded = true;
        }
        if (ar[0] === L) {
          const api = function () {
            p(api, arguments);
          };
          const namespace = ar[1];
          api.q = api.q || [];
          typeof namespace === "string" ? (cal.ns[namespace] = api) && p(api, ar) : p(cal, ar);
          return;
        }
        p(cal, ar);
      };
    })(window, "https://cal.com/embed.js", "init");

Cal("init");

Cal("inline", {
    elementOrSelector: ".w-embed", // You can also provide an element directly
    calLink: "clipflip/demo", // The link that you want to embed. It would open https://cal.com/jane in embed
});
</script>
 ```

**Comment by ropic** [comment]
Same problem v1.8.4 :(
