### ISSUE TITLE
Some hardcoded strings are missing

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#2626]
### Issue Summary

Hardcoded strings:

https://github.com/calcom/cal.com/blob/c22b6ca6703cb3b300ccff57c55b6c744ac3e49d/apps/web/lib/emails/templates/attendee-request-reschedule-email.ts#L187

https://github.com/calcom/cal.com/blob/c22b6ca6703cb3b300ccff57c55b6c744ac3e49d/apps/web/pages/settings/admin.tsx#L32 (error messages are also hardcoded: https://github.com/calcom/cal.com/blob/c22b6ca6703cb3b300ccff57c55b6c744ac3e49d/apps/web/ee/lib/impersonation/ImpersonationProvider.ts)

#### attendee-request-reschedule-email.ts
1. Schedule a meeting
2. Send request for rescheduling to attendee
3. See attendee notification email

Instead, translation string `book_a_new_time` should been used.

#### admin.tsx
1. See `settings/admin`

Translation string is missing in localised files.

### Technical details

- Browser version: Firefox 99.0.1
- Node.js version: v14.19.1
- cal.com selfhosted

**Comment by gracebir** [comment]
@bhopmann I am going to fix that
