### ISSUE TITLE
Sign in with Google not working - redirects to logout page

### ISSUE THREAD

**Issue by AnandBaburajan** [calcom/cal.com#2630]
### Issue Summary

"Sign in with Google" option redirects me to the logout page

### Steps to Reproduce

1. Went to https://app.cal.com/auth/login
2. Clicked on "Sign in with Google"
3. Chose my gmail account
4. Was redirected to https://app.cal.com/auth/logout

**Comment by victorgbaye** [comment]
https://www.loom.com/share/1b91b76fa8be4557991ac9f4787b8250

Sign in with Google appears to be working fine. could you share a loom to show the workflow of this issue. perhaps it is different from mine

**Comment by AnandBaburajan** [comment]
https://user-images.githubusercontent.com/2698932/166095095-12d514ad-fa77-4544-99a1-03bea7851ca4.mp4

**Comment by AnandBaburajan** [comment]
Just went to https://app.cal.com/event-types and noticed that I'm logged in. If I logout and login again, the bug is still there though.

**Comment by Emmanuel-Melon** [comment]
I'd like to work on this one

**Comment by Emmanuel-Melon** [comment]
> 1. https://app.cal.com/auth/login

I've tried to re-produce the bug using the steps you've shown but I get logged in normally every time.

**Comment by matheusmuniz03** [comment]
@AnandBaburajan I tried to reproduce this problem, but apparently everything is ok. 
my loom video: https://www.loom.com/share/44926623bb4e4d0c89d05e20d6f82150

probably this error is something cache related. try doing this in an anonymous tab

**Comment by Jaibles** [comment]
@AnandBaburajan we did some work on this issue recently (https://github.com/calcom/cal.com/pull/2594). Can you try clear your cache or test in incognito and see if you still experience the issue?

**Comment by AnandBaburajan** [comment]
Ah, worked in incognito. Thank you.
