### ISSUE TITLE
Time format on public scheduling page defaulting to 24 hour format

### ISSUE THREAD

**Issue by tjpatter** [calcom/cal.com#2632]
When an end-user access the public scheduling page, they are presented with available times in the 24 hour format instead of the 12 hour format with am/pm.

The end-user can select a the time format by using the time zone drop-down, but it would be great if we could either default to 12 hour format, or have the capability to define which option to use with the public page.

**Comment by aq-simei** [comment]
Hi, I would like to try solving this issue.

**Comment by milospuac** [comment]
Hi there. The page follows the browser locale settings. Did you try changing the time format in the browser?

**Comment by Emmanuel-Melon** [comment]
> 

What about adding the option to manually set the format + following the browser locale settings?

**Comment by tjpatter** [comment]
So, I have found that the initial page load does follow browser locale settings, but if (as an end-user on a public page) you click into a time slot, select a different date, the time slots are now in 24-hour format...

**Comment by alannnc** [comment]
@aq-simei Any luck solving this bug? From what I've seen it's not selecting user owner settings. I think we should always stick with user owner settings and not default to browser locale.

**Comment by timfee** [comment]
Hi there, I'm also seeing this. I'm in the US, where 12-hour time is the default, and I have configured 12-hour time as well, yet the public booking page is still showing 24-hour time.

<img width="911" alt="Screenshot_2022-08-13_07-08-06_PmPq1RRr" src="https://user-images.githubusercontent.com/3246342/184498856-3d0215c1-03e7-417d-91c7-8ffd8ce3a248.png">
<img width="1093" alt="Screenshot_2022-08-13_07-08-57_IjXmODx4" src="https://user-images.githubusercontent.com/3246342/184498860-8bd1a127-116b-472c-b087-72332f56d5de.png">

**Comment by PeerRich** [comment]
hey, can you try the latest version again?
