### ISSUE TITLE
Use a calendard to RSVP to upcoming events

### ISSUE THREAD

**Issue by thom4parisot** [calcom/cal.com#2638]
### Is your proposal related to a problem?

Currently, calendars are used to detect busy/available moments within time periods.
Given a few constraints, the UI let the user book a time within available one to one/group meetings.

However, our coop also provided "fixed time events" where people attend.
They are either online, or at given locations (exactly like in event types).

With the current behaviour of Calcom, we can only work with "office hours", which are recurring and rarely set to change.

### Describe the solution you'd like

I would like an event type where availability is based on calendar events (and/or manual entries).
People could RSVP, and get reminders as they already do with regular event types.

See it as a "public calendar where people RSVP/attend".

---

Another approach would be to "synchronize a set of working hours with a remove calendar" (we already have plenty of sources with CalDav/Big Brother Calendar/etc.). All the "free slots" of these working hours would match with these events. All attendees would also be added both to cal.com and both to the remote calendar event.

### Describe alternatives you've considered

The closed I've seen is time.ly but it is far too complicated.
TheEventCalendar wordpress plugin does that with their RSVP module but they don't have a meeting scheduler for what calcom does.

The only other solution I know is providing a generic form which a webhook that fills up a spreadsheet with declarative attendees, and manually remind them they registered to attend.

### Additional context

I am in a cooperative where there are many types of events : 

- informational meetings (on site, online) to show a presentation of how it works, and to answer people questions
- one to one meetings — when you decide to join, to proceed with paperworks and last minute questions
- one to one support meetings — when you have joined the coop, to get on some functional affairs (choose your payroll and benefits, sort out some business issues)
- coop gatherings — where dozens of coop members attend to celebrate what's up with our joint efforts

calcom is a perfect fit for one-to-one events, and for internal meetings.

It does not seem far fetched it could also work to deal with group meetings ("availability hours driven by calendar").

Let me know what do you think about it, and if there is a need to clarify the whys and what.

Cheers,

Thom

**Comment by PeerRich** [comment]
i dont think this is something we'll do. apologies for the long staleness

**Comment by thom4parisot** [comment]
No worries 🙂 thanks for having taken the time to think about it.
