### ISSUE TITLE
Request to reschedule not working in dynamic event

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#2646]
### Issue Summary

The issue is with dynamic links (which not too many people are using right now so it's not a big deal) but I can't

1.  request to reschedule an event done with dynamic link, or
2.  edit the event myself. It has updated in the UI and triggered an email - but it has not updated my calendar. Perhaps it's a matter of time but I did it about 40 mins ago. 

reported by @Jaibles

**Comment by LuisChiej** [comment]
Hello @alishaz-polymath, Could you list the steps to reproduce?

**Comment by alishaz-polymath** [comment]
Fixed by PR#2657
