### ISSUE TITLE
8x8 meet web conference

### ISSUE THREAD

**Issue by Tiger862000** [calcom/cal.com#2656]
### Is your proposal related to a problem?

In the Apps section for webmeetings only a few good applications are supported when I want to embed a webconference service with cal.com.

### Describe the solution you'd like

Include 8x8 meet service (8x8.vc ) in the Apps section of Cal.com

### Describe alternatives you've considered

Offer an API or a generic way to connect to other webconference services.

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app
