### ISSUE TITLE
Readd steps to create a new user

### ISSUE THREAD

**Issue by jaxxstorm** [calcom/cal.com#2665]
On the signup page, you tell users to create a new user via prisma or via a database connection

<img width="799" alt="image" src="https://user-images.githubusercontent.com/1622940/166405140-8cf8536c-28d1-4e87-a2d7-7ab67424fbb1.png">

This links to the following page, which is blank.

Please add it back

**Comment by MatheusBeniniF** [comment]
i'm working on this issue and i think i've already found a solution for it.
