### ISSUE TITLE
Remove open source references

### ISSUE THREAD

**Issue by jaxxstorm** [calcom/cal.com#2666]
The vart majority of the platform is no longer open source.

The API, admin interface and website are behind private git repos: https://github.com/calcom/cal.com/tree/main/apps

You are now open core, not open source.

Please don't mislead users

**Comment by baileypumfleet** [comment]
Like hundreds of other open source companies, we open-source the core of our application, but make certain non-core features such as the API and an admin panel paid enterprise features in able to have a sustainable business model. However the core functionality of Cal.com will always be free and open source.

It's not true that "the vast majority of the platform is no longer open source". In fact, most of the platform is open source. We only make certain new features enterprise only.

You can view the source code of the application online, so by definition it is open source and open core.
