### ISSUE TITLE
Disable email notifications

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#2670]
### Is your proposal related to a problem?

Being able to turn off email notifications is one request feature to keep track in this issue.

It was introduced as part of #2562 a way to disable emailing using the `noEmail` flag. It can be leveraged to achieve this feature.

### Describe the solution you'd like

I'm an organizer that wants to create an event type or edit an existing one to disable email notification. Probably disabling emails to attendees and organizer all at once or with different levels of disabling.

### Describe alternatives you've considered

No alternatives exist at the moment to achieve this.

### Additional context

A thread was created in Twist to follow up this requirement.

**Comment by Jaibles** [comment]
This feature is currently on hold and not in our current milestone but attaching current state of designs for reference anyway
https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6573%3A106028

**Comment by PeerRich** [comment]
i am still afraid people click this by accident and then complain

**Comment by mohit-nagaraj** [comment]
Any updates?
