### ISSUE TITLE
Request the inclusion of Asunción/Paraguay timezone

### ISSUE THREAD

**Issue by markimeyer** [calcom/cal.com#2678]
Hi, may I request the inclusion of Asunción/Paraguay timezone?

![image](https://user-images.githubusercontent.com/7417277/166714667-628d945b-d5f8-4049-b740-13ecffebca64.png)
![image](https://user-images.githubusercontent.com/7417277/166714687-c45bf6e0-a368-4339-915e-a6dfc76a0a23.png)

**Comment by milospuac** [comment]
Thanks for reaching out, our engineers will implement this soon

**Comment by Toledodev** [comment]
I will take a look on this
