### ISSUE TITLE
Dark mode not working on full site

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#2679]
https://www.loom.com/share/d09a4696451548de9e7f94a121e726e6

**Comment by milospuac** [comment]
It looks like your dark theme is actually light theme color 🤔
<img width="373" alt="Screen Shot 2022-05-05 at 16 38 32" src="https://user-images.githubusercontent.com/97884287/166947979-f720c969-62db-4a3e-8caa-215ad369cced.png">

**Comment by victorgbaye** [comment]
> It looks like your dark theme is actually light theme color 🤔 <img alt="Screen Shot 2022-05-05 at 16 38 32" width="373" src="https://user-images.githubusercontent.com/97884287/166947979-f720c969-62db-4a3e-8caa-215ad369cced.png">
<img width="984" alt="Screenshot 2022-05-05 at 17 10 00" src="https://user-images.githubusercontent.com/81493483/166966537-56dcc480-34e0-4f24-8ffa-1dfb8f424e5f.png">

I switched the colours but nothing changed still

**Comment by Toledodev** [comment]
I had changed the colors too, but as nothing had happened I decided to record the video the way it came when I cloned it

**Comment by hariombalhara** [comment]
Dark theme is currently applicable to public booking pages only

**Comment by Emmanuel-Melon** [comment]
Any updates on this issue?
