### ISSUE TITLE
Ability to click to view a booking

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#2681]
We want to be able to click on a booking from /bookings and be able to see the details of that booking, just like what you see after you make the booking.

**Comment by LuisChiej** [comment]
Hello @Jaibles, I would like to help with this, could you give a more detailed breakdown?

**Comment by Jaibles** [comment]
@LuisChiej working on designs right now - will share very shortly!

**Comment by victorgbaye** [comment]
> @LuisChiej working on designs right now - will share very shortly!

I'm available if it requires an extra hand. i want to work on some UI for my first issue.

**Comment by LuisChiej** [comment]
Hello @Jaibles, any update on the design and when could we look forward to it?
