### ISSUE TITLE
UI Improvements to the Giphy App

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#2682]
### Is your proposal related to a problem?

The current implementation of the Giphy app has some UI inconsistencies.

I've proposed updates in the following design:
https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6293%3A99883

**Comment by victorgbaye** [comment]
Hi @Jaibles i'd love to work on this but the version on the repo 
<img width="1440" alt="Screenshot 2022-05-05 at 12 04 58" src="https://user-images.githubusercontent.com/81493483/166911118-4119ec1f-9710-477d-ace8-2fb07e0fe294.png">
doesn't seem to have the dashboard on the sidebar

**Comment by dev-eth** [comment]
hi, @victorgbaye thanks for this.
Do you mean the cal.com repo does not have a dashboard component in the source code?

**Comment by victorgbaye** [comment]
> hi, @victorgbaye thanks for this. Do you mean the cal.com repo does not have a dashboard component in the source code?

yes that's what i mean.  when i run the project locally there is no dashboard section on the sidebar

**Comment by agustif** [comment]
@victorgbaye that's weird indeed, maybe you've zoom settings on your browser or are using a lower resolution where the sidebar is hidden?

**Comment by with-shrey** [comment]
@Jaibles 
How would this work if i want to change the search term ?
<img width="403" alt="image" src="https://user-images.githubusercontent.com/25253907/167489270-b699abb8-d4c1-4de5-8a4e-195f7d5729e9.png">

**Comment by with-shrey** [comment]
@agustif 
Quick question 

As you can see in the image above 
the tab has a black border 
which I think should change as per the user's theme color

Is there any CSS class that handles it?  
Could you point me to someplace where this is being handled?

**Comment by Jaibles** [comment]
Hey @with-shrey, I've included two options for changing the search term, one option is to go back to the previous step. The other option if it's possible, would be to allow the person to type a new search term & hit enter. [Designs also updated in Figma](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6358%3A101549).

![Image](https://user-images.githubusercontent.com/4536123/169018644-4891bd61-f114-4ab5-8aed-ace6fea4d1d8.png)

**Comment by with-shrey** [comment]
@Jaibles
Attaching the SS of what i have currently 

I think going back to change search keyword is a little non-intuitive.
Let me know your thoughts ? 

<img width="840" alt="Screenshot 2022-05-17 at 4 54 00 PM" src="https://user-images.githubusercontent.com/25253907/169021820-195fe4ad-700d-4484-9c6b-065e1ed9f32e.png">
<img width="765" alt="Screenshot 2022-05-17 at 4 53 47 PM" src="https://user-images.githubusercontent.com/25253907/169021854-64244160-dbfe-4668-95a3-fe59c1b2ff87.png">
<img width="895" alt="Screenshot 2022-05-17 at 4 53 41 PM" src="https://user-images.githubusercontent.com/25253907/169021860-9820a6ea-b76e-467e-9f90-80f1fa88809f.png">

**Comment by Jaibles** [comment]
@with-shrey this looks great!! Can they just research with the same input you have there then? If so I think this is perfect solution and no need to go back.

**Comment by Jaibles** [comment]
Looks good to me, thanks @with-shrey 🙏 really appreciate you taking care of these improvements.
