### ISSUE TITLE
API keys are not shown in settings

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#2689]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

API keys are not listed anymore

### Steps to Reproduce

1. Go to settings - security 
3. Clicked on 'Generate new API key'
4. Click on 'Save'
5. See that no API keys are listed

**Comment by LuisChiej** [comment]
> > Here is a loom video https://www.loom.com/share/4c96ad4917fc45658f21ce9a517c1887
> 
> Interesting, are you working on the newest version? https://www.loom.com/share/bea316c93c834903977537b9bd516fdc

I think so, have you tried updating it?
