### ISSUE TITLE
No error message shown when URL already exists

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#2701]
Found a bug? Please fill out the sections below. 👍

The user doesn't see any error message when an event-type is created (or edited) with an already existing URL. 
### Steps to Reproduce

1. Create a new event type with URL '15min'
2. Create another event type with URL '15min'
3. See it's not working and the user doesn't see any error message
4. Open developer console and you see the error 

### Technical details
![Screenshot 2022-05-09 at 11 42 39](https://user-images.githubusercontent.com/30310907/167384186-0b2eadcc-563e-4f5f-aa9a-f77ea1707c67.png)

**Comment by LuisChiej** [comment]
Hi @CarinaWolli, It's proving difficult reproducing the bug above

**Comment by Mitchell-Moore** [comment]
Hey @CarinaWolli I think I have the fix for this. I'm a little new to open source but I'll try and make a pull request
