### ISSUE TITLE
Replace additional notes for reschedule reason when editing booking

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#2709]
### Is your proposal related to a problem?

When editing booking there should be an input for the user owner that says Reason for reschedule instead of additional comments.

![image](https://user-images.githubusercontent.com/4461358/167447499-92b85bac-c00d-456d-adc3-cd668360803b.png)

### Additional context
Input should be optional, and save to DB field **cancellationReason**.

**Comment by MatheusBeniniF** [comment]
i'm working on this issue and i think i've already found a solution for it
