### ISSUE TITLE
Group Events (x/y seats left)

### ISSUE THREAD

**Issue by Freundschaft** [calcom/cal.com#271]
As the feature on calendly.

I've made a working draft for now that works "kind of" for what im building for a small project.

feel free to check out the fork at: https://github.com/freundschaft/calendso/

its still a wip and some features are implemented a bit dirty

<img width="1093" alt="Screenshot 2022-02-21 at 18 39 04" src="https://user-images.githubusercontent.com/8019099/155010924-2694ad1d-4f88-4bf1-97a2-1a9369850d23.png">

**Comment by PeerRich** [comment]
love this idea. i believe i've seen a lot of users mention something similar

**Comment by emrysal** [comment]
I had a think, does an invitee really need to see how many spots are left? I think the "Base" functionality is to be able to overlap bookings somehow

**Comment by phalox** [comment]
Hey everyone, what would it take to have this feature merged? We're looking for a solid solution for workshop bookings and a group booking feature is missing. We might be able to allocate some engineering work to make this happen.

The 'spots left' is configurable on calendly.

**Comment by baileypumfleet** [comment]
@phalox apologies for the late reply, but if somebody were to PR this, we'd be happy to get this merged in

**Comment by PeerRich** [comment]
@alishaz-polymath is working on it now!

**Comment by PeerRich** [comment]
for anyone reading here why it took a couple months: we had to make some major changes to the calendar system first in order to support this! 🎉
