### ISSUE TITLE
Delete event-type confirmation modal is wonky on mobile

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#2735]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Reference image: 
![image](https://user-images.githubusercontent.com/52925846/167851979-2a61c441-6d68-4975-a6d0-bf1e234859c0.png)

### Steps to Reproduce

Try to delete an event-type from the event-type list (`/event-type/` page)

**Comment by alishaz-polymath** [comment]
On desktop, it shows undesired & unnecessary scrollbars
![image](https://user-images.githubusercontent.com/52925846/167853976-ab2e8799-624d-4761-8a0e-4d22776982a6.png)

**Comment by MuriloAmarals** [comment]
Hello @alishaz-polymath my Delete event type window doesn't show scrollbars.

![Captura de tela de 2022-05-11 09-23-36](https://user-images.githubusercontent.com/87545137/167863772-91e2bf35-3a3c-45a2-a7f0-8bc6cf3a1f36.png)

**Comment by MuriloAmarals** [comment]
Hello @alishaz-polymath on my delete event type doesn't appear these scrollbars.

![Captura de tela de 2022-05-11 10-40-29](https://user-images.githubusercontent.com/87545137/167864236-d812241d-4b79-456f-919f-79a89dcf0600.png)

**Comment by alishaz-polymath** [comment]
Hi @MuriloAmarals. Thanks for your input. This is weird 🤔 It shouldn't happen in my case either, so definitely worth exploring
