### ISSUE TITLE
fine grained calendar sync

### ISSUE THREAD

**Issue by Freundschaft** [calcom/cal.com#274]
I propose a feature that has been v useful for me.
Ideally, each event type should be able to select both

- the calendar that should be used to detect collisions
- the calendar that should be used to create events

I have made an implementation for my fork at https://github.com/Freundschaft/calendso/blob/main/lib/calendarClient.ts#L226

**Comment by emrysal** [comment]
Have a look at the work recently by @Malte-D - you may find some overlap

**Comment by Jaibles** [comment]
> each event type should be able to select both the calendar that should be used to create events
This is now handled in each Event Type under "Advanced Settings"
<img width="896" alt="CleanShot 2022-05-18 at 15 26 56@2x" src="https://user-images.githubusercontent.com/4536123/169066139-abd10f02-1f17-4c4b-8af2-a6b2690af820.png">

For this scenario:
> the calendar that should be used to detect collisions
We do this at a global level. As soon as you connect a calendar and check it to check for clashes, we will do this across all your event types.

**Comment by PeerRich** [comment]
@Freundschaft feel free to re-open
