### ISSUE TITLE
@calcom/web:dev: error - TypeError: "ikm" must be at least one byte in length

### ISSUE THREAD

**Issue by hassanali1337** [calcom/cal.com#2740]
getting error after 
yarn run dev
when tried to login it failed
**`Something went wrong. Please try again and contact us if the issue persists.`**

also giving error on cmd
```

@calcom/web:dev: [next-auth][warn][NO_SECRET]
@calcom/web:dev: https://next-auth.js.org/warnings#no_secret
@calcom/web:dev: error - TypeError: "ikm" must be at least one byte in length
```

**Comment by nag-ramone** [comment]
You have to set up the `NEXTAUTH_SECRET` env variable.

**Comment by PeerRich** [comment]
@hassanali1337 did this help?
