### ISSUE TITLE
Bug(header): profile dropdown flickering on mobile

### ISSUE THREAD

**Issue by with-shrey** [calcom/cal.com#2742]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The profile dropdown in header flickers if i click on it.
On log press it seems to be working fine 

### Steps to Reproduce

1. Open cal.com.on mobile 
2. Tap on the user's icon/ avatar 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Android Firefox

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will look into this

**Comment by Thiagomn1** [comment]
Hello, I'm working on this issue
