### ISSUE TITLE
WebEx App

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2744]
- Getting Started: https://developer.webex.com/docs/getting-started
- Webex integrations: https://developer.webex.com/docs/integrations

**Comment by aar2dee2** [comment]
Hi,
Is this open to work on?

**Comment by PeerRich** [comment]
> Hi, Is this open to work on?

yes!

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by aar2dee2** [comment]
Hi,
I'm enjoying working on this! I have a few questions - please see comment in the PR.
Thanks!

**Comment by PeerRich** [comment]
how come the PR was closed?

**Comment by aar2dee2** [comment]
> how come the PR was closed?

Created a [new one](https://github.com/calcom/cal.com/pull/7651) on a different branch

**Comment by PeerRich** [comment]
lovely

**Comment by aar2dee2** [comment]
:)
Have some questions [here](https://github.com/calcom/cal.com/pull/7651#issuecomment-1463364222)

**Comment by ThisisErm** [comment]
@aar2dee2 @PeerRich Is this solved?

**Comment by aar2dee2** [comment]
thanks, calcom & algora!!
