### ISSUE TITLE
make hardcoded list of video providers dynamic based on apps in "video" category

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2753]
this file https://github.com/calcom/cal.com/blob/main/apps/web/lib/locationOptions.tsx

should be dynamic based on the video apps we have in the app store

**Comment by agustif** [comment]
Would an apps endpoint at our api be useful for such things? or better keep this at web.

Im thinking something of the lines of:
`{endpoint}/apps/installed?category="video"`
