### ISSUE TITLE
replyTo should be booker's email

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2754]
when sending the emails "A new event has been scheduled." it should contain the email of the other person in the replyTo field

<br class="Apple-interchange-newline">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/8019099/168296052-19631fb8-5ae4-463a-8995-e1cce471422c.png">

**Comment by MuriloAmarals** [comment]
Hey @PeerRich, i'm working on this issue.

**Comment by Chetan-B-B** [comment]
I'll also work on this
