### ISSUE TITLE
Implement dark mode in all site

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#2762]
The project don't have dark mode in all components

Currently the only component that has dark mode is AvailabilityPage(client-cal.com/apps/web/components/booking/pages/AvailabilityPage.tsx)

https://www.loom.com/share/6f8bc62260a644f6b9eb296d13075922

**Comment by sean-brydon** [comment]
@Jaibles Is this something we have any designs/capacity to start doing any time soon?

**Comment by Emmanuel-Melon** [comment]
I'd like t work on this, are there any designs to work with?

**Comment by PeerRich** [comment]
maybe for cal.com 2.0 @Jaibles?

**Comment by Jaibles** [comment]
I will include it for 2.0
