### ISSUE TITLE
Login error message doesn't disappear when button is clicked again 

### ISSUE THREAD

**Issue by LuisChiej** [calcom/cal.com#2771]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

An error message appears when wrong login details are entered, doesn't disappear when the right details are

### Steps to Reproduce

1. Go to the login page
2. Enter wrong login details and try to login, an error message is shown
3. Enter the right login details and try again, error message remains there

#### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Error message should disappear once login is attempted again

**Comment by jaysoni-ash42** [comment]
@LuisChiej  i want to work on this.
