### ISSUE TITLE
Issue with yarn dx; docker-compose.yml is invalid 

### ISSUE THREAD

**Issue by scantreed** [calcom/cal.com#2776]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When following the instructions on https://docs.cal.com/self-hosting/installation, after I run `yarn dx` I get the following error: 

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/104802114/168698717-6800176e-9838-4f66-b844-1979f2cb4ee3.png">

Furthermore, the instructions for self hosting keep changing. I am just trying to demo the product and it seems there is a different issue with launching it every time. Do we still need to copy the `.env.example` file to `.env`?

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will look into this

**Comment by PeerRich** [comment]
@zomars has experience with this

**Comment by PeerRich** [comment]
just making sure, you have docker installed? which version?

**Comment by scantreed** [comment]
I do have Docker installed. Docker version 20.10.14

**Comment by agustif** [comment]
Hey @scantreed maybe it's docker-compose the culprit and not docker directly?
https://stackoverflow.com/questions/71060072/docker-compose-depends-on-with-condition-invalid-type-should-be-an-array

Can you try with v2 if you're not already running it for `docker-compose`

```
➜ docker-compose --version
Docker Compose version 2.3.3
```

**Comment by scantreed** [comment]
that was it my dockercompose was out of sync with my docker version. Thank you @agustif
