### ISSUE TITLE
Migration 20220502154345_adds_apps does not create app entries

### ISSUE THREAD

**Issue by mzocher-gl** [calcom/cal.com#2778]
### Issue Summary
When moving the app store keys/secrets from .env to the App table, the migration [20220502154345_adds_apps](https://github.com/calcom/cal.com/tree/main/packages/prisma/migrations/20220502154345_adds_apps) does not create all app keys, and instead has a blank table.  Clicking on Apps->App Store shows an empty list, and trying to connect services under installed apps gives a 400 error.

### Steps to Reproduce

1. Start with 1.5.2 code base
2. Upgrade to main or 1.5.3 
3. Perform "yarn workspace @calcom/prisma db-deploy"
4. Check table, App will be empty and interface for App Store will be broken

Ideally, this migration would move the keys automatically from .env into the database in the correct locations, but even if it didn't, it should make the correct app keys.  Putting the dev seed data in DOES correctly make the keys.

### Technical details
(Feel free to reach @mzocher in Slack for questions)

**Comment by milospuac** [comment]
Hi there. Thank you for reaching out and bringing this to our attention. Our team will look into this.

**Comment by PeerRich** [comment]
fixed a long time ago
