### ISSUE TITLE
Confirm Booking gives 500 if it has Jitsi location in it but Jitsi was disconnected

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2787]
### Steps to Reproduce

- First add Jitsi as a location to your event type(that requires confirmation)
- Do a booking with the cal link
- Disconnect Jitsi
- Try to confirm the booking - 500 error comes.

**Comment by hariombalhara** [comment]
@zomars @Jaibles What should happen in such a scenario? 
- Do we fallback to default Cal Video ?
- Do we choose the new location set in event type ? But we might not always be able to use it in for the locations where the booker has to put information during booking.

**Comment by sean-brydon** [comment]
> @zomars @Jaibles What should happen in such a scenario?
> 
> * Do we fallback to default Cal Video ?
> * Do we choose the new location set in event type ? But we might not always be able to use it in for the locations where the booker has to put information during booking.

Falling back to cal video would be the ideal - however, we would need to take into consideration if any self-hosted user has cal video installed too.

**Comment by zomars** [comment]
Let’s just remove the location. Let the user know so he can choose a new one if desired

**Comment by zomars** [comment]
@andreaestefania12 made something similar when making a paid booking and then disconnecting the Stripe integration:


![image](https://user-images.githubusercontent.com/3504472/168861092-f9205380-4979-4a88-b5ab-3a9688ab6604.png)

**Comment by hariombalhara** [comment]
I am assuming there would be no confusion for the booker as he might have received some information on email about location(even before confirmation)

Also, there can be 2 types of bookings.
- Confirmed and still not happened(day/time hasn't come yet) =>  email has already been sent with Jitsi link (so they should get an email with update on location change)
- Pending Confirmation => Possibly some information about location has been shared(if not Jitsi URL, just the name of location is shared). These might also need update on location


Might be a good idea to get it wrapped up along with https://github.com/calcom/cal.com/pull/2658 as it has new emails flow as well.
