### ISSUE TITLE
Allow for self hosted accounts to have access to the broader cal.com marketplace

### ISSUE THREAD

**Issue by Awisemaninmotion** [calcom/cal.com#2795]
### Is your proposal related to a problem?

There's no good reason why the Cal.com marketplace shouldn't be accessible to self hosted accounts. 
I'm frustrate that there's no clear path, or documentation on how to install integrations listed as "not installed" from the integration page. 

### Describe the solution you'd like

Offer a seamless way for self hosted accounts to access and install items listed on the cal.com marketplace.

### Describe alternatives you've considered

Tried finding documentation to integrate Stripe integration for self hosted accounts to no avail. 
Reached out to help@cal.com in the hopes that they would be able to assist.
Was directed to this form.

**Comment by milospuac** [comment]
Thanks for sharing this. One of our team members will look into this.

**Comment by PeerRich** [comment]
hey @Awisemaninmotion, all you need to do is get the apps credentials and put it into the .env file

we don't have a tutorial for each app because most apps were done by contributors and we havent found the time yet to write a tutorial for each one

**Comment by PeerRich** [comment]
however, there is a proposal #2621 where you could use all apps on a self-hosted platform, and the apps are hosted by us. it's still in "request for comments"
