### ISSUE TITLE
Lark Suite

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2799]
https://www.larksuite.com/

**Comment by PeerRich** [comment]
@joeauyeung do you think we can get this in to v.1.7?

**Comment by PeerRich** [comment]
hey @joeauyeung will we get lark suite into v.1.8? (due 15th)

**Comment by joeauyeung** [comment]
It probably won't make it to v1.8. We're in the midst of testing right now and experiencing some bumps. I'm going back and fourth with Lark though and it'll help minimize the risk of bugs when we push to production.

**Comment by PeerRich** [comment]
long done
