### ISSUE TITLE
Event types breaking when no attendee has been added

### ISSUE THREAD

**Issue by lharries** [calcom/cal.com#2800]
I'm trying trying to edit one of our team events events but it's not loading the page. I suspect this is because there's no event attendee attached (as this is the only difference to the other events)

Please see the loom video for more info: https://www.loom.com/share/1f2fb6222142497ba0ece7e31a33a9c2

https://calendso.slack.com/archives/C01NXDSRY9W/p1652738007170249

**Comment by jaysoni-ash42** [comment]
@lharries  can i work on this

**Comment by Jaibles** [comment]
Resolved with https://github.com/calcom/cal.com/pull/2803

**Comment by lharries** [comment]
Thanks for fixing!
