### ISSUE TITLE
New EventTypes created within a team have the "Availability" connected to the creator rather than the attendee

### ISSUE THREAD

**Issue by lharries** [calcom/cal.com#2813]
### Issue Summary

New EventTypes created within a team have the "Availability" connected to the creator rather than the attendee

This is breaking the ability for us to create new eventtypes for the team

### Steps to Reproduce

1. Create a new EventType within a team
2. Replace yourself as an attendee with a different attendee that has different working hours "Availability"
3. Observe that the new eventtype will still be connected to your availability rather than the new attendee's availability

### Expected behavior

The expected behavior is that the calendar event's availability should match that of the attendee for a team event. Currently it's matching mine as (I think) the creator of the event

**Comment by MuriloAmarals** [comment]
I'm working on this

**Comment by lharries** [comment]
Thank you @MuriloAmarals!

**Comment by lharries** [comment]
@MuriloAmarals I've added the expected behavior to the comment "The expected behavior is that the calendar event's availability should match that of the attendee for a team event. Currently, it's matching mine as (I think) the creator of the event"

**Comment by MuriloAmarals** [comment]
@lharries Ok, i will try to reproduce, any problem i will update you.

**Comment by MuriloAmarals** [comment]
Did you reproduce this bug on localhost or cal.com deploy ?

**Comment by lharries** [comment]
I did it via the cal.com deploy - however I've tried to reproduce it again and haven't been able to do so successfully

**Comment by MuriloAmarals** [comment]
Oh ok, so will you close the PR ?
