### ISSUE TITLE
truncate user about text on team public page

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#2814]
If a user has a long About section when they are displayed on the about page it will visually break the layout.

![Image](https://user-images.githubusercontent.com/4536123/169095827-aeca114d-f201-4c05-9ee6-41edc5df28a7.png)

Solutions proposed (but not yet signed off) in [Figma](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6993%3A127726)

At the very least we should truncate the about text.

**Comment by MatheusBeniniF** [comment]
im working on this now

**Comment by MatheusBeniniF** [comment]
I'm working on this

**Comment by PeerRich** [comment]
no need to add "RFC" for this type of issue @Jaibles
