### ISSUE TITLE
Integration for n8n

### ISSUE THREAD

**Issue by artistro08** [calcom/cal.com#2815]
### Is your proposal related to a problem?

I'd love for you guys to integrate with n8n, an alternative to Zapier.

### Describe the solution you'd like

I would love to have an API integration that connects with n8n. It would provide everything that you guys have now.

### Describe alternatives you've considered

Zapier integration

**Comment by PeerRich** [comment]
@CarinaWolli you could give this a spin if you want to

**Comment by CarinaWolli** [comment]
> @CarinaWolli you could give this a spin if you want to

I will take a look into that!

**Comment by agustif** [comment]
I think @alishaz-polymath is working on this as he mentioned (n8n) when we were working together on adding the new webhooks CRUD API.

I would ping him to see how is that going!!

**Comment by alishaz-polymath** [comment]
Thanks @agustif 
Yes, I'm currently working on creating the Cal trigger node for n8n.

**Comment by alishaz-polymath** [comment]
The Cal trigger node is now integrated with n8n and can be used directly when using n8n 😄 
![image](https://user-images.githubusercontent.com/52925846/172312273-c7cb6fb5-88e5-4e85-a465-011217b33db8.png)

We would look into the possibility of a elaborate integration with n8n on our app-store in the coming months, but until then, this should suffice 🚀
