### ISSUE TITLE
Opt-in booking confirmation page & email are inconsistent

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#2816]
After making a booking request with someone who has Opt-In bookings enabled, it is not obvious the booking is not confirmed. The icon looks like a success and at a glance the header reads like one too. The title actually needs to read more like the subtitle. It's also inconsistent with the email.

The confirmation page
![Image](https://user-images.githubusercontent.com/4536123/169147068-84df02d9-4860-47f3-b5a6-b0e21da1ad43.png)

The email:
![Image](https://user-images.githubusercontent.com/4536123/169147101-74cba18e-432f-4623-bbf2-a89b3f514e56.png)

**Comment by MuriloAmarals** [comment]
Hey @Jaibles, i can do this optimisation.

**Comment by MuriloAmarals** [comment]
> @MuriloAmarals this looks great! I just have one or two suggestions for the copy to refine it. Can you link me to the pr so I can comment for you?

Hi @Jaibles sorry for the delay, what are the suggestions?

**Comment by Jaibles** [comment]
will be tackled as part of 2.0 https://github.com/calcom/cal.com/issues/3767
