### ISSUE TITLE
Bug: pre-fill email and name not working

### ISSUE THREAD

**Issue by lharries** [calcom/cal.com#2823]
### Issue Summary

When I pre-fill the email and/or name it flashes it on the screen but then removes it

Please see the loom video to demonstrate it https://www.loom.com/share/c1d21e3279084a6b923de6f5b6bec0d3

### Steps to Reproduce

1. Go to https://cal.com/team/fella-health-engineering/health-coach-checking-staging?email=test@test.com

Expected behavior: the email should be pre-filled as described in the docs: https://github.com/calcom/cal.com/blob/fcdd2ab81b9997648aea5a0ef948cc7a5c679ad4/apps/docs/pages/developer/pre-fill.mdx

**Comment by MychaelJales** [comment]
I was able to reproduce just by using your link. With my link it works normally.

https://www.loom.com/share/8255dd839ad74f3fbfea32240abbf26d

**Comment by aayestashn** [comment]
**I have the same issue:**

I am using a self-hosted version of Calendso. In a react typescript application I am trying to call the Caledso schedule form using the react embed library. 

In the configuration of the library, I put the values of email and name as you can see in the following code.

```html
 <Cal
    calLink={bookingLink}
    embedJsUrl={`${caledsoOrigin}embed/embed.js`}
    calOrigin={caledsoOrigin}
    config={{
      name: `${user?.first_name} ${user?.last_name}`,
      email: user?.email,
      theme: "light",
    }}
 />
```

In the dev tools, I am able to see the name and email correctly in the link but does not work, I made a test in a private window, and works fine. 

Example of the link: 
https://calendso-test.onrender.com/nbulla/15min?embed=&name=El+mago+Palacios&email=aayestas%2Bel%40ingsw.com&theme=light&__autoScroll=false&embedType=inline

The name is "El Mago Palacios" with the email is "aayestas+el@ingsw.com", but the schedule form displays the email: "noromi+coach@gmail.com" with the name: "Nicolas Oromi" there is an existing account in our Calendso.

You can see all the flow in the following video:

https://www.loom.com/share/5089e48dcd8d4b5ab0f622b2c194e16e

**Comment by joeauyeung** [comment]
@lharries @aayestashn is this bug still affecting you two? I've tried to reproduce the bug but it's working as expected

**Comment by lharries** [comment]
Maybe it's because I'm logged into a different account on Cal.com that it's causing this. When I open it in incognito the bug doesn't persist but the bug continues when I'm logged into cal.com with a different account to the email shown

**Comment by joeauyeung** [comment]
Thanks for the replay @lharries helped put it into perspective.
