### ISSUE TITLE
Options button at event-types flicking

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#2824]
### Steps to Reproduce

1. Create a meeting
2. In event types click on the button "settings" on the meeting

Loom video: https://www.loom.com/share/d891275210504361b2164e64bc8e8423

**Comment by matheusmuniz03** [comment]
hi @Toledodev, i will take a look at it

**Comment by matheusmuniz03** [comment]
rafael in my localhost the bug doesn't happen, just in deploy.

my loom: https://www.loom.com/share/23fde678acf8467c8122ab2fbe04cded

**Comment by luksdev** [comment]
I am working on this issue

**Comment by PeerRich** [comment]
I believe this is caused by a new animation that we have added

**Comment by gracebir** [comment]
@PeerRich, I can see that there is no animation effect locally, and in that way we can't reproduce this bug,
