### ISSUE TITLE
away mode should remove you from team events

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2844]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/8019099/169615445-765a2e54-f6f6-426e-93aa-68b46bbbbdc9.png">

going "away" should remove you from collective team events until you are back again

**Comment by leog** [comment]
So, the idea is to check if a user is marked as away to mark someone as away in collective team events. Once they are back, they mark themselves as online or similar and they will show in collective team events as usual. Right? Some visuals would be great to guide the changes needed, summoning 🕯@Jaibles🕯

**Comment by PeerRich** [comment]
yes!

**Comment by PeerRich** [comment]
what do we need visuals for? maybe a toast is enough?

**Comment by PeerRich** [comment]
I dont think you need visuals for this, do you? @leog

**Comment by PeerRich** [comment]
> Not sure, maybe we want to show someone as away from collective teams events instead of removing completely. If I'm away is not the same as not being there at all, maybe some indication to clarify that makes sense, but just a suggestion 🙂

lets add a new badge:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/8019099/170098847-8568ecaa-1ebf-41fc-a2cd-72f4b9a78292.png">

`self-center rounded-md border px-3 py-1 text-xs capitalize ltr:mr-2 rtl:ml-2 border-yellow-200 bg-yellow-50 text-yellow-700`

**Comment by JatinRanka** [comment]
Hey @PeerRich, I would like to contribute to this issue. But a bit confused about how to get started with this one. Any help would be really appreciated. TIA :)

**Comment by jkdamilola** [comment]
@JatinRanka Have you been able to work on this issue? Can I help?

**Comment by PeerRich** [comment]
@jkdamilola please go ahead, i dont believe this was worked on, yet.

**Comment by JatinRanka** [comment]
@jkdamilola I have some doubts. Pinging you on slack.

**Comment by jkdamilola** [comment]
@PeerRich is adding a new badge to the teams page enough to resolve this ticket? Do we also need to remove them from the attendees while booking?

**Comment by PeerRich** [comment]
> @PeerRich is adding a new badge to the teams page enough to resolve this ticket? Do we also need to remove them from the attendees while booking?

it would also need to pause them from collective and round robin events (remove until back from vacation)

**Comment by jkdamilola** [comment]
@PeerRich Awesome! What happens if everyone in the team goes on vacation? I'm not sure of the how frequent this would happen or if it would ever happen - I don't have the data. It's just an edge case that popped up while testing.

**Comment by PeerRich** [comment]
good question. lemme discuss in the team

**Comment by hariombalhara** [comment]
In that case the entire team should be considered away? and probably the same page would be shown as is shown when a user is away for user booking ?

**Comment by Udit-takkar** [comment]
@PeerRich  is this feature still required ?
