### ISSUE TITLE
docker-compose issue

### ISSUE THREAD

**Issue by HazemHeakal** [calcom/cal.com#2847]
When start 'yarn dx' command get this error,

"./docker-compose.yml' is invalid because services.postgres_is_ready.depends_on contains an invalid type, it should be an array error Command failed with exit code 1"

**Comment by zomars** [comment]
Hey @HazemHeakal what version of docker are you using?

**Comment by HazemHeakal** [comment]
Docker version 20.10.12
docker-compose version 1.26.2

**Comment by HazemHeakal** [comment]
No it's Ubuntu 20 server

**Comment by HazemHeakal** [comment]
So what steps i can take to install it in local server?

**Comment by zomars** [comment]
`yarn build` and `yarn start` basically

**Comment by HazemHeakal** [comment]
i get this "yarn run dev exited (137)"
and this "error: Environment variable not found: DATABASE_URL.
@calcom/web:dev:   -->  schema.prisma:6
@calcom/web:dev:    | 
@calcom/web:dev:  5 |   provider = "postgresql"
@calcom/web:dev:  6 |   url      = env("DATABASE_URL")
"

**Comment by zomars** [comment]
you need to provide you own DATABASE_URL. You may need to provide one from an external provider or setup your own. Also `yarn dev` is for local development `yarn start` is for production runtime.

**Comment by zomars** [comment]
Will close this issue as this is not a problem with the build process. If you feel that the README is not clear enough you're welcome to propose changes to it. 🙏🏽

**Comment by HazemHeakal** [comment]
Already have my own and created a user on it but loading of the cal is very slow also when i enter the credentials that i write in db it give me this error "error: Environment variable not found: DATABASE_URL.
@calcom/web:dev: --> schema.prisma:6
@calcom/web:dev: |
@calcom/web:dev: 5 | provider = "postgresql"
@calcom/web:dev: 6 | url = env("DATABASE_URL")

**Comment by zomars** [comment]
Please make sure you're following the README step by step. I cannot provide more guidance without more context. Also for these kind of questions feel free to post them in our slack. https://cal.com/slack
