### ISSUE TITLE
Add integration for Mirotalk

### ISSUE THREAD

**Issue by SrIzan10** [calcom/cal.com#2854]
### Is your proposal related to a problem?

No, I just want an integration for Mirotalk because this is a nice selfhosted web meetings website.

There's a Rest API which you can use to create meetings.

### Describe the solution you'd like

Add Mirotalk for creating meetings in cal.com

### Describe alternatives you've considered

nothing?

### Additional context

nope.

**Comment by PeerRich** [comment]
do you wanna give this a try?

**Comment by SrIzan10** [comment]
@miroslavpejic85

mentioned so you can also track this issue and do something with this.

**Comment by miroslavpejic85** [comment]
Thank you, @SrIzan10.

**Comment by SrIzan10** [comment]
np!

**Comment by PeerRich** [comment]
take a look at "whereby" app to copy it!

**Comment by miroslavpejic85** [comment]
> take a look at "whereby" app to copy it!

Forgive me, but I don't understand what should I copy?
I think MiroTalk not need to copy others, it has all the features for a video conferences and more.. :)

**Comment by PeerRich** [comment]
no, i am referring to the whereby app in our code base

**Comment by blaine07** [comment]
Would like this integration, too!
