### ISSUE TITLE
Making calendars easier to find

### ISSUE THREAD

**Issue by joshuakaufman** [calcom/cal.com#2856]
### Is your proposal related to a problem?

I'm a new user to Cal.com and was frustrated when I couldn't find where to add new calendars to the app.

### Describe the solution you'd like

Users can’t use Cal without integrating calendars. But you can use Cal without many of the other apps, so it would make sense to place calendars at higher level. For example, my email client (Spark) also features integrations but the email account information is in a unique place where it’s easier to find, separate from the rest of the integrations. In my experience, this patterns occurs in many other apps as well.

### Describe alternatives you've considered

I haven't thought of other solutions.

### Additional context

I'll want to pay for Cal.com but I feel that it lacks the usability that I expect from an app.

Thank you for reading.

**Comment by Jaibles** [comment]
@joshuakaufman thanks for raising this issue. This is something we are currently working on and are going to make a priority!

**Comment by Jaibles** [comment]
There are updated designs for this here...
- [Calendars will show up in settings](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS-v2.0?node-id=1546%3A86956)
- And also have their own specific section in [Installed apps](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS-v2.0?node-id=1440%3A65828)

**Comment by Jaibles** [comment]
This is being tackled as part of the 2.0 redesign in these two issues.

- https://github.com/calcom/cal.com/issues/3783
- https://github.com/calcom/cal.com/issues/3765
