### ISSUE TITLE
Recurring events from caldav server not blocked

### ISSUE THREAD

**Issue by m4tze** [calcom/cal.com#2864]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am running the docker version of calcom and I have two caldav backends configured for my user. There are many recurring events in my calendar and none of these is blocked. Normal (one-time) events are blocked as they should.

### Steps to Reproduce

1. start docker version
2. run a caldav server, e.g. radicale and create recurring events
3. import calendar into calcom
4. go to booking
5. realize, that blocked dates are still available

I think this is a bug, as recurring events should block the corresponding dates

**Comment by sr-verde** [comment]
Yeah, would be a necessary feature for me as well. Thank you!

**Comment by afoster** [comment]
I'm also seeing this with a Zimbra caldav backend.

**Comment by m4tze** [comment]
There seems to be some ongoing development reg recurring events: https://github.com/calcom/cal.com/tree/leog/recurring-event-improvements - maybe @leog can confirm?

**Comment by m4tze** [comment]
@leog I can confirm, that other entries (non recurring) behave as expected, they block the time for selection.

**Comment by leog** [comment]
@m4tze I can't seem to be able to reproduce the issue. Got myself radicale locally and Thunderbird to manage a calendar, created two events for one day, one regular and one recurring, and they are showing up as expected in the "Availability" tool to troubleshoot these scenarios, under your schedule. I'm assuming you have toggled your calendar in the Installed Apps configuration page to let Cal check specific calendars for conflicts. Any other information I might be missing? Happy to help.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/467258/172957699-f8c0f587-b828-4d65-a97c-63fff5a9b445.png">

**Comment by m4tze** [comment]
@leog I investigated this a bit. It works when I start this baremetal on my machine. It does not work for the Version built for the Docker container. I also changed the Dockerfile to use the sources form the productive branch, but this does not work. I do not see a different between the Docker version and the baremetal install. Have you tried the Docker version? Is this something related to outdated dependencies?

**Comment by m4tze** [comment]
@leog @milospuac this seems to be a timezone issue for recurring events. I further tried to find the failure and fortunately, I recognized the times blocked and saw, that the timezone of the recurring event itself is wrong (and thus, fell out of my usual business times) and was not blocked because of this. After changing the timezone in the Docker container, the times are successfully blocked. I cannot tell, where the problem with the timezone of the recurring event comes from (= whether the recurring event is wrong or the library implementation parsing it). Could you confirm this with your test setting?

**Comment by m4tze** [comment]
I extracted the calendar entry, maybe there is a problem interpreting the vtimezone information?! To me it looks correct.

```
BEGIN:VCALENDAR
PRODID:Zimbra-Calendar-Provider
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETTO:+0100
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:+0200
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:344856ce-4c83-4e23-9e57-6f413ae23010
RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR
SUMMARY:Daily Stand-up
DESCRIPTION:description redacted
LOCATION:location redacted
X-MOZ-RECEIVED-SEQUENCE:0
X-MOZ-RECEIVED-DTSTAMP:20220315T083616Z
X-MOZ-INVITED-ATTENDEE:mailto:redacted@example.com
ORGANIZER:mailto:redacted@example.com
DTSTART;TZID="Europe/Berlin":20220311T093000
DTEND;TZID="Europe/Berlin":20220311T100000
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:OPAQUE
LAST-MODIFIED:20220315T141935Z
DTSTAMP:20220315T141935Z
SEQUENCE:0
END:VEVENT
END:VCALENDAR

```

**Comment by leog** [comment]
Timezones are being taken into consideration when it comes to calculate availability, I think this is where it becomes relevant: https://github.com/calcom/cal.com/blob/main/packages/lib/CalendarService.ts#L255. Would be very interesting in seeing if that logic works as expected in the scenario you came across, let me know if you could follow that through, otherwise, I can try to replicate the scenario in my machine to help debugging.

**Comment by m4tze** [comment]
@leog, first, thank you for getting into this with me. I looked into the problem a bit more and I think, the error starts exactly here: https://github.com/calcom/cal.com/blob/main/packages/lib/CalendarService.ts#L286 - the quote is from the description of the caldav protocol (more specific the expand xml element) but not from icalendar specs. Thus, the interpretation seems wrong, as we are dealing with icalendar events - even though the backend is caldav. 

I made change to my fork to fix it and created a pull request here: https://github.com/calcom/cal.com/pull/3060

As I am absolutely no TypeScript dev => I have no idea about TS styleguides, best practices or testing. I am fine if you reject my pull request and create a better one.

**Comment by m4tze** [comment]
@leog btw., the current implementation seems to use the system's timezone and not UTC as the "default" timezone for the recurring events, which explains, that it worked on my baremetal installations with the right Europe/Berlin timezone but not in Docker with the UTC timezone.

I hope, this (wrong) assumption that the "default timezone" is UTC is not assumed elsewhere in the code. You should apply the timezone conversion in every case (you don't lose anything and you can only win better code) - even if it's from UTC to UTC.
