### ISSUE TITLE
new app store slider

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2875]
right now, the screenshots in the slider are currently distorted to a fixed width, however they should take a fixed height and then relative width based on their dimensions.

example:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/8019099/170225753-11e7f4f1-0c63-4c69-b973-27423fd87293.png">

I would much rather have a slider like product hunt https://www.producthunt.com/posts/lazy-search-by-sigmaos: 

<img width="727" alt="image" src="https://user-images.githubusercontent.com/8019099/170226066-95e57cd8-9c73-4cf0-81a7-8daff8846f4b.png">

**Comment by aar2dee2** [comment]
Hey!
Opened a PR for this, assuming this refers to the slider on the app description page in the App store.

**Comment by PeerRich** [comment]
> Hey!
> 
> Opened a PR for this, assuming this refers to the slider on the app description page in the App store.

yes, can you share a loom.com video?

**Comment by aar2dee2** [comment]
This is my first PR. What should I include in the video?

**Comment by aar2dee2** [comment]
https://user-images.githubusercontent.com/85004512/170863550-e6dadaa8-51b0-492c-8d64-44120844955d.mov

Is this alright?
