### ISSUE TITLE
Flicker on success page 

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#2881]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Fix the flicker on booking success page

### Steps to Reproduce

1. Go to Event Types and click preview
2. When scheduling a meeting successfully the flicker will appear

Loom video: https://www.loom.com/share/967770b9d36644dba419120b1f9cb976

**Comment by gracebir** [comment]
@Toledodev what is the expect here ?

**Comment by Toledodev** [comment]
I think the redirect is not necessary, because it was supposed to have a "back to bookings" button

**Comment by Toledodev** [comment]
Please take a look on this issue i fixed https://github.com/GitStartHQ/client-cal.com/pull/7
