### ISSUE TITLE
A booking was made for a time in the past

### ISSUE THREAD

**Issue by devinellis** [calcom/cal.com#2884]
We had someone make a booking for 10AM, but the event was created at 11:40AM 🤯 

Here's the relevant bits of the Booking DB record:
- startTime: 2022-05-25 17:00:00
- createdAt: 2022-05-25 18:40:53.369

At first I thought maybe the user opened the calendar earlier today, then booked the meeting afterwards. But looking at our logs, the user had not yet come to our site until just a few minutes before the createdAt time above.

Minimum booking notice is set to 120 minutes.

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out.
Our team will look into this
