### ISSUE TITLE
Team availability doesn't show blocked slots

### ISSUE THREAD

**Issue by kof** [calcom/cal.com#2897]
### Issue Summary

I created a team and I am looking at [team availability](https://app.cal.com/settings/teams/2149/availability) view that is supposed to show when is each member available, but shows all available hours, even where the slot should be blocked based on gmail calendar availability and based on booked events through cal.com, but both types of events don't show up there

### Steps to Reproduce

Let  me know if this requires more steps

### Technical details

Latest Chrome, Mac

**Comment by MatheusBeniniF** [comment]
hey @kof you can give me more details?

**Comment by kof** [comment]
@MatheusBeniniF  Under the link I showed (replace it with your user), I was expecting to see only available slots, but I see all the slots, is that intentional?

**Comment by MatheusBeniniF** [comment]
> @MatheusBeniniF Under the link I showed (replace it with your user), I was expecting to see only available slots, but I see all the slots, is that intentional?

for me to understand better, would you be able to send a loom video or a print of your screen?

**Comment by PeerRich** [comment]
hey @kof can you try again? lots has changed
