### ISSUE TITLE
When no location is set in an event, where would the meeting occur ?

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2900]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When no location is selected in an event, the email received after booking has a `Where` heading but no text. Maybe we should make it very clear that no location was selected by the organizer and the booker should contact the organizer for the meeting location.

Also, maybe we should not allow empty locations at all. If the organizer chooses to set no location, he should be asked to drop a comment about where the meeting is supposed to happen. 

This is to solve the confusion for a booker when such an event is booked.

<img width="608" alt="Screenshot 2022-05-27 at 11 10 55 AM" src="https://user-images.githubusercontent.com/1780212/170637308-90fef64d-a8ea-4bd9-96a6-517f08d2b82d.png">

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Create an event. By default it has Cal Video as location.
2. Go and remove that location.
3. Book a meeting
4. Check the email recieved.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by hariombalhara** [comment]
cc @Jaibles

**Comment by sean-brydon** [comment]
If I remember correctly the plan was to default to Cal Video if no location was found (Taking into consideration if the user is self hosted or not they might not have a DailyCo api key)

**Comment by 123om123** [comment]
would it be possible for me ot work on this?

**Comment by Jaibles** [comment]
@sean-brydon yes the plan was to default to Cal video.

I'm not sure what to do for self-hosted users but will think about it.

**Comment by om-ray** [comment]
@Jaibles Hi, could you or someone else review the PR?
