### ISSUE TITLE
Booking confirmation via email, but not found in bookings

### ISSUE THREAD

**Issue by peseotni** [calcom/cal.com#2903]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The client and organizer received a confirmation email but it is not found in the bookings. 
![280282758_1820287581494019_6747458617752315403_n](https://user-images.githubusercontent.com/22613392/170653600-41ceb27b-300b-4165-9bbb-1b92d6ed771d.png)

other clients are present, but not that booking.

### Steps to Reproduce

1. ?? because other bookings work.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Node.js 14.19.3

**Comment by milospuac** [comment]
Thanks for reporting this. Our engineering team will investigate.

**Comment by peseotni** [comment]
Update: The meeting appeared after the timeslot time. Strange.
