### ISSUE TITLE
Error when "Manage this event"  

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#2913]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I run 2 self hosted servers of cal.com, one for caldav, and another one for google. When clicking "Manage this event " on the received email of confirmation, on both I get the same 4 Unhandled Runtime Error . I can click "X" and I can see the Cancel / Reschedule options. On CalDav I can reschedule and cancel successfully. On Google, when clicking Cancel, I get error 500. When trying to reschedule, the email and name are empty spaces and cannot be edited. Thus when clicking Reschedule it won't continue as the fields are empty. 

### Steps to Reproduce

1. Sent out a default 30 min event.
2. Someone booked me for a random time.
3. I received an email with the confirmation.
4. Wanting to change the event, clicked "Manage this event" in the received email.
5. Unhandled Runtime Error was displayed.
6. Click "X".
7. Cick "Cancel Event".
8. 500 Error Occurred.
9. Refresh.
10. Click "X".
11. Click "Reschedule Event".
12. Select a date / time.
13. Click Reschedule.
14. Error "That doesn't look like an email address"
15. Email address and name is empty, while it should be Filled out with details of the person who booked me.
16. Cannot edit the empty name/email, which is normal.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

For CalDav Server, even if I ecnounter the same first 6 steps, I can cancel and reschedule successfully.

- Browser version, screen recording, console logs, network requests: 

- Version 102.0.5005.61 (Official Build) (64-bit)
- Node.js version v14.17.6

Not getting any errors on the server

**Error 1 out of 4**

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Call Stack
throwOnHydrationMismatch
../../node_modules/react-dom/cjs/react-dom.development.js (14388:0)
tryToClaimNextHydratableInstance
../../node_modules/react-dom/cjs/react-dom.development.js (14401:0)
updateHostComponent$1
../../node_modules/react-dom/cjs/react-dom.development.js (20711:0)
beginWork
../../node_modules/react-dom/cjs/react-dom.development.js (22447:0)
HTMLUnknownElement.callCallback
../../node_modules/react-dom/cjs/react-dom.development.js (4161:0)
Object.invokeGuardedCallbackDev
../../node_modules/react-dom/cjs/react-dom.development.js (4210:0)
invokeGuardedCallback
../../node_modules/react-dom/cjs/react-dom.development.js (4274:0)
beginWork$1
../../node_modules/react-dom/cjs/react-dom.development.js (27405:0)
performUnitOfWork
../../node_modules/react-dom/cjs/react-dom.development.js (26513:0)
workLoopSync
../../node_modules/react-dom/cjs/react-dom.development.js (26422:0)
renderRootSync
../../node_modules/react-dom/cjs/react-dom.development.js (26390:0)
performConcurrentWorkOnRoot
../../node_modules/react-dom/cjs/react-dom.development.js (25694:0)
workLoop
../../node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
../../node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
../../node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Error 2 out of 4**

Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.

Call Stack
checkForUnmatchedText
../../node_modules/react-dom/cjs/react-dom.development.js (9644:0)
didNotMatchHydratedTextInstance
../../node_modules/react-dom/cjs/react-dom.development.js (11361:0)
prepareToHydrateHostTextInstance
../../node_modules/react-dom/cjs/react-dom.development.js (14487:0)
completeWork
../../node_modules/react-dom/cjs/react-dom.development.js (19460:0)
completeUnitOfWork
../../node_modules/react-dom/cjs/react-dom.development.js (26552:0)
performUnitOfWork
../../node_modules/react-dom/cjs/react-dom.development.js (26524:0)
workLoopSync
../../node_modules/react-dom/cjs/react-dom.development.js (26422:0)
renderRootSync
../../node_modules/react-dom/cjs/react-dom.development.js (26390:0)
performConcurrentWorkOnRoot
../../node_modules/react-dom/cjs/react-dom.development.js (25694:0)
workLoop
../../node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
../../node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
../../node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Error 3 out of 4**

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Call Stack
throwOnHydrationMismatch
../../node_modules/react-dom/cjs/react-dom.development.js (14388:0)
tryToClaimNextHydratableInstance
../../node_modules/react-dom/cjs/react-dom.development.js (14401:0)
updateHostComponent$1
../../node_modules/react-dom/cjs/react-dom.development.js (20711:0)
beginWork
../../node_modules/react-dom/cjs/react-dom.development.js (22447:0)
beginWork$1
../../node_modules/react-dom/cjs/react-dom.development.js (27381:0)
performUnitOfWork
../../node_modules/react-dom/cjs/react-dom.development.js (26513:0)
workLoopSync
../../node_modules/react-dom/cjs/react-dom.development.js (26422:0)
renderRootSync
../../node_modules/react-dom/cjs/react-dom.development.js (26390:0)
performConcurrentWorkOnRoot
../../node_modules/react-dom/cjs/react-dom.development.js (25694:0)
workLoop
../../node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
../../node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
../../node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Error 4 out of 4**

Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Call Stack
updateHostRoot
../../node_modules/react-dom/cjs/react-dom.development.js (20658:0)
beginWork
../../node_modules/react-dom/cjs/react-dom.development.js (22444:0)
beginWork$1
../../node_modules/react-dom/cjs/react-dom.development.js (27381:0)
performUnitOfWork
../../node_modules/react-dom/cjs/react-dom.development.js (26513:0)
workLoopSync
../../node_modules/react-dom/cjs/react-dom.development.js (26422:0)
renderRootSync
../../node_modules/react-dom/cjs/react-dom.development.js (26390:0)
recoverFromConcurrentError
../../node_modules/react-dom/cjs/react-dom.development.js (25806:0)
performConcurrentWorkOnRoot
../../node_modules/react-dom/cjs/react-dom.development.js (25706:0)
workLoop
../../node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
../../node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
../../node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our team will look into this.

**Comment by newz666** [comment]
Quick Bug Update. After following steps 1-6, for CalDav, when rescheduling a meeting, it gets properly rescheduled under "Bookings", but it does not get updated in the calendar. The "Cancel" works fine.

**Comment by alishaz-polymath** [comment]
Hi @newz666 
A fix for a similar issue was merged a while back in relation to the CalDAV calendar not showing the rescheduled changes of the event. It should do that now, so if you could please confirm if you're facing this issue, we can explore further. Else, we can close this as complete. 🙏

**Comment by emrysal** [comment]
Closing as fixed :)
