### ISSUE TITLE
Unable to upgrade to pro

### ISSUE THREAD

**Issue by jamiepine** [calcom/cal.com#2920]
### Issue Summary
<img width="287" alt="Screen Shot 2022-05-30 at 12 48 17 AM" src="https://user-images.githubusercontent.com/32987599/170944019-e0901a73-18d8-4bb9-9189-de274f82d0b6.png">

None of the upgrade buttons within the app appear to be working, at least for me.

### Steps to Reproduce

1. Go to settings
2. Click upgrade now
3. Get redirected to the events page

### Technical details
Clicking the billing portal gives an "API handler not found" error, which is most likely the same issue that is causing the "upgrade now" button in the alerts to do nothing.

<img width="543" alt="Screen Shot 2022-05-30 at 12 41 39 AM" src="https://user-images.githubusercontent.com/32987599/170942642-0864ccf6-4a2c-4131-a31d-ae7b92bc544c.png">

**Comment by alannnc** [comment]
Hi @jamiepine, did a quick test and its working for me now? Can you try again? Or give me more details about it?

**Comment by jamiepine** [comment]
Happens on all browsers on my Cal.com account. Here's a video of it happening. I can't find anything helpful in the network logs unfortunately.

https://user-images.githubusercontent.com/32987599/171055626-b93b83c3-943b-4a1b-a04a-daa081c56107.mov

**Comment by zomars** [comment]
Can't seem to replicate locally nor on production. This seems like something Stripe account related. Will make some adjustments to facilitate debugging.

**Comment by zomars** [comment]
Can confirm that your account is working correctly now. Will close this issue for now. Feel free to re-open if you experience any more trouble 🙏🏽
