### ISSUE TITLE
Wrong color for Timezone selector on booking page

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2922]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I find it weird for Duration to be in light color and Timezone to be in dark color on  https://cal.com/hariom/30min

<img width="267" alt="Screenshot 2022-05-30 at 3 32 02 PM" src="https://user-images.githubusercontent.com/1780212/170969000-b76f34eb-4c03-4401-9872-b997530e258c.png">

Implement as per https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=3412%3A50674

**Comment by MuriloAmarals** [comment]
I will take a look on this!!! @hariombalhara

**Comment by hariombalhara** [comment]
Refer to this https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=3412%3A50674 by @Jaibles

**Comment by MuriloAmarals** [comment]
I did some changes. Take a look.
Do you think it's good ?

![Captura de tela de 2022-05-30 10-24-33](https://user-images.githubusercontent.com/87545137/171001752-44595d2b-f328-48c3-b570-ea6643077926.png)
![Captura de tela de 2022-05-30 10-24-11](https://user-images.githubusercontent.com/87545137/171001792-524342ac-c8a9-4146-b9ad-3e5c883d6fa7.png)
