### ISSUE TITLE
react-timezone-select: add popular cities for each timezone

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2939]
based on: https://twitter.com/peer_rich/status/1531906849733222400

lets use:
https://github.com/ndom91/react-timezone-select#-custom-timezones

to add cities such as San Francisco => PT, etc.

[csvData.csv](https://github.com/calcom/cal.com/files/8815222/csvData.csv)

**Comment by PeerRich** [comment]
found this too: https://twist.com/a/195135/ch/554218/t/3522106/

**Comment by Toledodev** [comment]
you mean this?
![Screenshot from 2022-06-01 16-04-10](https://user-images.githubusercontent.com/87545086/171482532-b1dcd5dc-a700-4b69-894c-7ab5f8b14683.png)
or just use as a filter?

**Comment by Toledodev** [comment]
In the library there is no kind of filter or key that refers to the capital or if the city is "popular".  Until now if I type the name of the city the corresponding timezone is selected, but not rendered in the options

**Comment by Toledodev** [comment]
Can I make all cities matching the input search be rendered in the options? as the user types more characters the options will decrease

**Comment by PeerRich** [comment]
> Please check my video :+1: 
> 
> https://www.loom.com/share/3fc511af5e4c4fb68946d85e2a0286ee

is it possible to show the city in the dropdown when typing?

**Comment by Toledodev** [comment]
Hey @PeerRich . there is no way to render the cities (or the corresponding timezones) in the dropdown without rendering it again
I was able to make it switch to the right timezone without being rendered on the dropdown (as I showed in a video above) and I was able to show the corresponding timezones when the dropdown is rendered again (https://www.loom.com/share/5d14b40950ef4c94b691d3efb37ef95e)

**Comment by Toledodev** [comment]
The console on loom video shows the filtered object (with the input value)

**Comment by Toledodev** [comment]
I opened an issue in the react time zone select repository, suggesting this feature, as they only provide the date with the timezones, without having cities to filter. When trying to make the relationship between react-timezone-select and city-timezones(library I used) I realized that react-timezone-select doesn't accept timezones different from theirs suggesting this feature

**Comment by Toledodev** [comment]
hey @PeerRich, as you can see there is no dynamic way to filter and render the desired cities
https://github.com/ndom91/react-timezone-select/issues/71

**Comment by aar2dee2** [comment]
@PeerRich 
I'm planning to add cities from [this Kaggle database](https://www.kaggle.com/datasets/juanmah/world-cities) directly to the [declared time-zones list](https://github.com/ndom91/react-timezone-select/blob/main/src/timezone-list.ts) in react-timezone-select. Here's a snapshot of the data in Kaggle:
<img width="967" alt="Screenshot 2022-06-21 at 3 45 43 PM" src="https://user-images.githubusercontent.com/85004512/174776309-66037752-8f76-44c0-a6f8-f909102487f7.png">

Is it better to include the `city` names or `city_ascii` names?

**Comment by aar2dee2** [comment]
update: just read the discussion [here](https://github.com/ndom91/react-timezone-select/issues/71). Happy to work with @Toledodev / others if we have consensus on the dataset to be used.

**Comment by PeerRich** [comment]
> update: just read the discussion [here](https://github.com/ndom91/react-timezone-select/issues/71). Happy to work with @Toledodev / others if we have consensus on the dataset to be used.

awesome yeah lets work in that repo 🙏

**Comment by aar2dee2** [comment]
Hey @Toledodev if you have a fork for `react-timezone-select` that you're adding the cities in, could you add me as collaborator?
