### ISSUE TITLE
booking page: recurring text breaks mobile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2940]
![image](https://user-images.githubusercontent.com/8019099/171448815-eb1d9305-8088-4024-9392-3303d6a76df0.png)

**Comment by matheusmuniz03** [comment]
Hi @PeerRich, I will take a look on this!

**Comment by PeerRich** [comment]
thank you @leog

**Comment by matheusmuniz03** [comment]
hey @PeerRich, my PR with the changes: https://github.com/GitStartHQ/client-cal.com/pull/64
