### ISSUE TITLE
RFC: Alarm System

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2944]
## Problem
- sometimes integrations fail, which is outside of our control
- sometimes credentials change or people remove permissions
- whenever that happens, Cal.com fails silently, and the solution is often to disconnect and reconnect an integration (i.e. Google Calendar)

## Solution
- an alarm system via Email
- similar to Zapiers alarm system when a Zap fails
- a clear "call-to-action" how to fix the problem

**Comment by alannnc** [comment]
Pretty much needed, some ideas that came to my mind:

- After setting up your integration, run a test to validate integration it's working.
- Cron job that daily test user integration, if something fails notify users.
- A button that a user can click to run test on integrations.

**Comment by joeauyeung** [comment]
I was thinking on going through our apps and sending an email on 401 "Unauthorized". 

Some questions I have are
- Is there another error we should look for that indicates the credentials are throwing the error
- Do we then delete the credential on behalf of the user?
	- I'm leaning towards no 	

>Cron job that daily test user integration, if something fails notify users.

Is this too overbearing? I'm thinking as our user base increases is this a good use of our compute resources?

**Comment by emrysal** [comment]
If an integration is broken we can no longer guarantee the correct functioning of the scheduling system, at that point we should disable all event types that require that integration and provide an alternative means of scheduling; simultaneously we must then inform the organizer something is wrong. At that point you don't need to run an E2E test to see a page is broken, all you need to do is run a simple PING.

**Comment by alannnc** [comment]
@emrysal @joeauyeung 

> all you need to do is run a simple PING.

Yeah we should do that, not every app integrations has its own ping test endpoint. I think we should define them based on what they do. In some apps user can omit a single permission and block us from working fully and we should let know to the user that we're missing specific permissions.
E.g. for calendar we should try to read any event, create/delete appointments and mark them on the integration as successfully working feature individually.
