### ISSUE TITLE
MS Teams cease workin - possible RefreshToken problem

### ISSUE THREAD

**Issue by ch-ruetgers-RMH** [calcom/cal.com#2946]
### Issue Summary

We use Cal.com on a self hosted instance. Our users connect against our Office365 Calendar and the same Teams Work account.

Events are configured to use Teams. 
The styled mail send from our Cal Server contain a Meeting-ID and the Meeting-URL.
The invite appears as an event in our Outlook calendar. The location shown is "Office365_Video". The appointment does not contain a Teams Link.

However, this works only for some minutes. If some creates further appointments no more Team Link is in the event. Not in the Cal Web Interface nor the mail. 

If some disconnect his Teams integration and connects freshly again, it will work for some minutes.

### Technical details

The log file shows

@calcom/web:start: 09:12:15.408 timeZoneName ERROR [lib] videoClient createMeeting failed
@calcom/web:start:  Error  Bad Request
@calcom/web:start: error stack:
@calcom/web:start: " 5184.js:1164 handleErrorsJson
@calcom/web:start:     .next/server/chunks/5184.js:1164:15
@calcom/web:start:
@calcom/web:start: " 8595.js:2307 refreshAccessToken
@calcom/web:start:     .next/server/chunks/8595.js:2307:71
@calcom/web:start:
@calcom/web:start: " 8595.js:2364 createMeeting
@calcom/web:start:     .next/server/chunks/8595.js:2364:33
@calcom/web:start:
@calcom/web:start: " 8595.js:7941 createMeeting
@calcom/web:start:     .next/server/chunks/8595.js:7941:28
@calcom/web:start:
@calcom/web:start: " 8595.js:7258 create
@calcom/web:start:     .next/server/chunks/8595.js:7258:28
@calcom/web:start:
@calcom/web:start: " event.js:1588 handler
@calcom/web:start:     .next/server/pages/api/book/event.js:1588:31
@calcom/web:start:
@calcom/web:start: " node.ts:255 apiResolver
@calcom/web:start:     node_modules/next/server/api-utils/node.ts:255:5
@calcom/web:start:
@calcom/web:start: " next-server.ts:541 runApi
@calcom/web:start:     node_modules/next/server/next-server.ts:541:5
@calcom/web:start:
@calcom/web:start: " base-server.ts:845 fn
@calcom/web:start:     node_modules/next/server/base-server.ts:845:27
@calcom/web:start:
@calcom/web:start: " router.ts:405 execute
@calcom/web:start:     node_modules/next/server/router.ts:405:26
@calcom/web:start:
@calcom/web:start: " base-server.ts:988 run
@calcom/web:start:     node_modules/next/server/base-server.ts:988:23
@calcom/web:start:
@calcom/web:start: " base-server.ts:615 handleRequest
@calcom/web:start:     node_modules/next/server/base-server.ts:615:14
@calcom/web:start:

and later
@calcom/web:start:   error: 'invalid_grant',
@calcom/web:start:   error_description: 'AADSTS9002313: Invalid request. Request is malformed or invalid.\r\n' +
@calcom/web:start:     'Trace ID: ad2af2a0-1e00-4955-bf41-e5f0a701c400\r\n' +
@calcom/web:start:     'Correlation ID: 96fc011d-8ce6-407c-be9f-dcb5c838b459\r\n' +
@calcom/web:start:     'Timestamp: 2022-06-02 09:12:15Z',
@calcom/web:start:   error_codes: [ 9002313 ],
@calcom/web:start:   timestamp: '2022-06-02 09:12:15Z',
@calcom/web:start:   trace_id: 'ad2af2a0-1e00-4955-bf41-e5f0a701c400',
@calcom/web:start:   correlation_id: '96fc011d-8ce6-407c-be9f-dcb5c838b459',
@calcom/web:start:   error_uri: 'https://login.microsoftonline.com/error?code=9002313'
@calcom/web:start: }

Best guess, something related to the token refresh against the API used by Teams goes wrong.

**Comment by PeerRich** [comment]
@joeauyeung was this fixed?

**Comment by joeauyeung** [comment]
Fixed in #4910. On Azure App Permissions ensure that you have enabled the "offline_access" permission.
