### ISSUE TITLE
Broken SpaceBooking App

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2952]
Found a bug? Please fill out the sections below. 👍

Example success page https://cal.com/success?date=2022-06-22T05%3A45%3A00%2B01%3A00&type=36837&eventSlug=30min&user=hariom&reschedule=false&name=sdf&email=fds%40sdf.com&location=Web+conferencing+details+to+follow+in+the+confirmation+email.&eventName=&bookingId=58365
### Steps to Reproduce

1. Go and install SpaceBooking App
2. Book a meeting
3. On success page, see that SpaceBooking content is broken
<img width="1507" alt="Screenshot 2022-06-03 at 3 59 42 PM" src="https://user-images.githubusercontent.com/1780212/171837424-33f5e555-e520-44b0-9dae-10b912dbfa99.png">

**Comment by PeerRich** [comment]
we should probably remove the app again, since May 4th is over
