### ISSUE TITLE
Not all information is shown on mobile (availability page)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#2954]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When booking an event the timezone and recurring event information is not shown in the mobile view. 

Desktop: 
<img width="922" alt="Screenshot 2022-06-03 at 14 28 01" src="https://user-images.githubusercontent.com/30310907/171853649-c7b4081f-cf0b-4d0c-8f65-92622d3ff0c5.png">

Mobile: 
<img width="528" alt="Screenshot 2022-06-03 at 14 28 30" src="https://user-images.githubusercontent.com/30310907/171853718-7bb3ee44-f80f-401d-a7aa-ac193da77a48.png">

**Comment by matheusmuniz03** [comment]
Hey @CarinaWolli. Here is my _[PR](https://github.com/GitStartHQ/client-cal.com/pull/69)_ with the changes I made.

Can you take a look?

**Comment by CarinaWolli** [comment]
Hey @matheusmuniz03, I can't open the link to your PR. It says 'Page not found'
