### ISSUE TITLE
Negative days in trial license period

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#2955]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On event-types page:
![Screenshot from 2022-06-03 08-40-01](https://user-images.githubusercontent.com/87545086/171860286-d31409cd-7f32-4a97-96ec-4f77b31c20b1.png)

### Steps to Reproduce
1. When you 14 days off free license expires, in the event-types page, the message shows a negative day

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by zomars** [comment]
On production we use a cron to actually downgrade expired user to the `FREE` plan. So technically they never see this negative number. Feel free to propose a PR to handle this if you seem necessary.
