### ISSUE TITLE
Handle EventType locations when missing/invalid credentials

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#2965]
---
> Indeed [Syed A](twist-mention://619027) , we should remove all locations that don’t have a valid credential:
> 
> * Available locations should be fetched from an endpoint
> * When removing a credential, we should cascade all event type locations and remove from there
> * When a credential becomes invalid we should alert the user and remove the locations as well.

ref: https://twist.com/a/195135/ch/554218/t/3530164/c/76574709

**Comment by joeauyeung** [comment]
First two problems addressed. Last one track on #2944
