### ISSUE TITLE
Unable to create API keys when sign in with google

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#2971]
### Issue Summary

If account is setup with sign in with google - API keys can not be generated 

<img width="1697" alt="CleanShot 2022-06-06 at 07 55 48@2x" src="https://user-images.githubusercontent.com/55134778/172111024-061495ee-ca1b-42a4-9336-33a36303ce24.png">

**Comment by agustif** [comment]
Hey sean, I think this is due to google not allowing password to be set, with new developer tab in 1.6.3 this should get fixed
https://github.com/calcom/cal.com/pull/2982/files#diff-712938a54b4bec8caf04d84b58ac90cdbed3e853f4677eac8302dc5237071d9c

**Comment by sean-brydon** [comment]
Closing - this should now be present in https://app.cal.com/settings/developer as per the latest release
