### ISSUE TITLE
The booker get’s the Ui option to reschedule but can’t reschedule

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#2985]
See loom https://www.loom.com/share/9a69f125ec5b490891c83d00622f93e9

In relation to https://github.com/calcom/cal.com/pull/2977, there is one more bug that I found that is pending fix.

**Bug Summary:**
After doing a booking by specifying email([free@ewxample.com](mailto:free@ewxample.com)) When I am logged in as booker([free@example.com](mailto:free@example.com)), I can see the booking and option to reschedule (through success page), but it takes to reschedule/undefined(This is unintentional bug due to recent security fix on success page I believe).

**Possible Solution:**
The question is should we disable the reschedule, cancel and Request Reschedule options for the booker.

**Comment by zomars** [comment]
Can we replicate this? I think the consensus was that you shouldn't see your booked events where you''re an attendee on upcoming bookings. You should only see the upcoming bookings you're hosting or part of as a team.

**Comment by PeerRich** [comment]
i believe this has been fixed
