### ISSUE TITLE
Can't connect CalDav/Lark Suite

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#2989]
Password for a third-party website was generated, yet this error pops up every time

<img width="1398" alt="CleanShot-2022-06-06-at-14-17-37-2x" src="https://user-images.githubusercontent.com/97884287/172325635-64964827-494c-4c54-b498-283b16e4b0ff.png">

Any ideas?

**Comment by alishaz-polymath** [comment]
According to [this](https://www.larksuite.com/hc/en-US/articles/360043178793) there isn't really a good way to directly sync CalDAV from our server to LarkSuite. And this isn't our problem but Lark Suite's app decision, so I'm closing this comment for now. If things change in the future, we can definitely re-visit

**Comment by PeerRich** [comment]
we're also wokring on a native lark app
