### ISSUE TITLE
Unable to login with first user

### ISSUE THREAD

**Issue by erzhan89** [calcom/cal.com#2991]
unable to login. 
created with Prisma Studio first user.. 
but getting error... 

in .env file
NEXT_PUBLIC_WEBAPP_URL='http://localhost:3000'

node v14.19.3
npm v6.14.17
yarn v1.22.19

![image](https://user-images.githubusercontent.com/7261370/172331551-a0c00c04-f487-42c4-a87d-0c8c3062b5a5.png)

**Comment by TheCapsLock** [comment]
Hi @erzhan89 if you have followed all the steps listed here : https://docs.cal.com/self-hosting/installation ; and have used the bcrypt tool to hash your password, take care that this tool adds extra spaces at the begining and at the end of the copied string.

You can also use this snippet to get a bcrypt hash (where "test" is the password to hash) :

```bash
python -c 'import bcrypt; print(bcrypt.hashpw(b"test", bcrypt.gensalt(rounds=10)).decode("utf-8"))'
```

**Comment by erzhan89** [comment]
@TheCapsLock, issue is solved. thanks!

**Comment by Silur** [comment]
@TheCapsLock the provided link here (and inside the app) is leading to a 404

**Comment by TheCapsLock** [comment]
@Silur moved here : https://developer.cal.com/getting-started/installation
