### ISSUE TITLE
Using a private link doesn't respect the availably set in the event type

### ISSUE THREAD

**Issue by artistro08** [calcom/cal.com#3012]
### Issue Summary

When I copy the private link for a hidden event, the availability is different than the one set on the event. 

### Steps to Reproduce

1. Open Private event
2. Click "Copy Private Link"
3. paste in browser
4. See the wrong availability

### Technical details

- Running latest chrome. Deployed via Railway
- using node 14.x

**Comment by MatheusBeniniF** [comment]
hey @artistro08 I reproduced the steps and it's working correctly, can you give me more details?

**Comment by artistro08** [comment]
Yes. Here's a self hosted private link I just generated. I have it set to Monday, Tuesday, Thursday Friday. But, it's using my default availability which is Monday & Friday

![image](https://user-images.githubusercontent.com/6427230/172615122-a20c8aa9-0792-4405-82fb-94a2743a793b.png)


Here's the link without the private masking displaying the right times

![image](https://user-images.githubusercontent.com/6427230/172615250-eb87dfee-9e61-4004-a8c2-9f6e50a00cb4.png)

**Comment by PeerRich** [comment]
hey there, @alishaz-polymath can take a look. he built the private link feature

**Comment by alishaz-polymath** [comment]
Hey @artistro08 
I'll  take a look at this on Monday. Will keep you posted with my findings!
🙏

**Comment by artistro08** [comment]
Yo. So this is fixed in Cal 1.7 works like a charm
