### ISSUE TITLE
It's not yet possible to deploy Cal on Cloudron

### ISSUE THREAD

**Issue by jdaviescoates** [calcom/cal.com#3026]
I've been using the hosted version and really like it, but I'd prefer to self-host and so I'd really love [Cloudron](https://cloudron.io/?refcode=5adcafc820c53c3d) to be added here:

![Cal com_deployment](https://user-images.githubusercontent.com/2113743/172667667-07b5d14c-5af2-4675-a409-815302a34295.png)

As would lots of other Cloudron users (it's currently the <strike>12th</strike> 6th most requested app on their App Wishlist), see:

https://forum.cloudron.io/post/29826 

For info about packaging apps for Cloudron see:

https://forum.cloudron.io/post/10712

**Comment by ianhyzy** [comment]
cal restricts SSO and provisioning behind their infrastructure tier, would that conflict with this?

**Comment by jdaviescoates** [comment]
> cal restricts SSO and provisioning behind their infrastructure tier, would that conflict with this?

I've no idea, but wouldn't that (if I've understood you correctly) only apply to the hosted version at cal.com and not to self-hosted instances?

**Comment by ianhyzy** [comment]
No, it's a separate version that you get after you pay is my understanding — SAML SSO and other features are listed as infrastructure or enterprise only, the FOSS features map closer to the free plan (sans limitations) I think: https://cal.com/pricing

**Comment by jdaviescoates** [comment]
You could be right, but it's not really very clear. Either way, LDAP or not I'd love to self-host on Cloudron (but hopefully it's possible with LDAP integration too).

**Comment by gramakri** [comment]
Co-founder of Cloudron here. If it's possible to just use local users on the self-hosted instance, that would be a good start already for the Cloudron package.

**Comment by PeerRich** [comment]
hey @gramakri whats the process? i dont mind having cal on cloudron. wanna submit a PR?

**Comment by jdaviescoates** [comment]
> You could be right, but it's not really very clear. Either way, LDAP or not I'd love to self-host on Cloudron (but hopefully it's possible with LDAP integration too).

I emailed them to ask  and they replied:

> So sorry for the late reply - here's what I got from our engineers "We don’t currently support LDAP, but should be easy to add to next-auth".

It is on the roadmap for us, but TBD as to when it will officially be implemented.

So sounds like one day self hosted version may well get LDAP in the future 😃

**Comment by ajtatum** [comment]
I'm also a Cloudron user and self-hosted Cal.com, but became too busy with other stuff that I wasn't able to maintain it, so if it could live in their ecosystem in any way, shape, or form that would be fantastic. LDAP would just be icing on the cake, not a requirement for me at least. I'm glad to see some potential here and look forward to seeing how this progresses. Thank you to the team at Cal.com for your willingness to look into this and thank you to the team at Cloudron for listening to and advocating for their users!

**Comment by jdaviescoates** [comment]
> hey @gramakri whats the process? 

@PeerRich just in case you didn't spot it, see this link from my OP for detail about how apps are packaged for Cloudron:

https://forum.cloudron.io/post/10712 :)

The top link on that post is this which covers what's involved:

https://docs.cloudron.io/packaging/tutorial/

Be great to have Cal on Cloudron! :pray:

**Comment by PeerRich** [comment]
> > hey @gramakri whats the process? 
> 
> 
> 
> @PeerRich just in case you didn't spot it, see this link from my OP for detail about how apps are packaged for Cloudron:
> 
> 
> 
> https://forum.cloudron.io/post/10712 :)
> 
> 
> 
> The top link on that post is this which covers what's involved:
> 
> 
> 
> https://docs.cloudron.io/packaging/tutorial/
> 
> 
> 
> Be great to have Cal on Cloudron! :pray: 
> 
> 

i was more referring to what the process is if someone wants to make a PR

cloudron is not on our roadmap for now but if someone wants to open a PR i am down to merge it

**Comment by marcusquinn** [comment]
We're happy to package for Cloudron, but this is currently a blocker: https://github.com/calcom/cal.com/issues/6780

Great think about having apps packaged on Cloudron is it gives developers and privacy-sensitive enterprises a quick way to trial. Anyone with a mission-critical reliance on an app typically then becomes an enterprise customer and sponsor anyway. The FOSS users just add to those influencers championing the app.

Also, typically we see FOSS support LDAP and Enterprise for SSO services. Next-auth maybe a good solution in the meantime, but LDAP is ideal, and enables quick team testing with Cloudron.

I can't think of any other server manager apps where you'll get as many experienced self-hosting privacy advocates and developers introduced to cal.com, so I'm certain solving this is a win-win for both communities.

**Comment by PeerRich** [comment]
@roae is a new hire for docker but currently working on the booking page perforamcen which has a higher priority, afterwards he can look at more docker related issues

**Comment by marcusquinn** [comment]
Great work @rjackson 🙇‍♂️

Correct on the bounty from @PeerRich ❤️

We'll ask @vladimirdulov to review once merged, and re-attempt the Cloudron App packaging with this solution. 🚀

**Comment by shashtag** [comment]
Has this issue been sorted? Or is there still something to work on?

**Comment by vladimirdulov** [comment]
We have managed to get Cal packaged for Cloudron, it's on review now and will be released soon.

**Comment by elr9** [comment]
> Hello! Do we know if there have been any updates on this?

**Comment by nebulade** [comment]
We've just pushed an initial package version now for testing. For curious readers, the package repo is at https://git.cloudron.io/cloudron/calcom-app

Thanks everyone, this can be closed then I guess.

**Comment by HarshithAlfred** [comment]
Is this issue closed ? but it shows open ,can we get on this and get bounty on this

**Comment by nebulade** [comment]
Not sure how this bounty system works, main work was done by @vladimirdulov with inspiration from https://github.com/calcom/docker as far as I can tell.

**Comment by github-luckow-org** [comment]
this issue can be closed since the app is published since quite some time. thanks for the great work.

**Comment by nebulade** [comment]
One of the Cloudron maintainer here. This is already long done by @vladimirdulov he should be eligible for the bounty.
