### ISSUE TITLE
Editing event location duplicates the event on my CalDAV calendar

### ISSUE THREAD

**Issue by jdaviescoates** [calcom/cal.com#3027]
### Issue Summary

If I edit the location of a booking, a whole new duplicate event is created on my Nextcloud calendar.

### Steps to Reproduce

1. Create a booking
2. Edit booking location
3. Notice there are now two duplicate events for the booking in my Nextcloud calendar.

### Technical details

- I'm currently using the hosted version of Cal.com connected to Nextcloud 24.0.1 on Cloudron 7.1.4 on Ubuntu 18.04

**Comment by gracebir** [comment]
@jdaviescoates , can I get access to NextCloud?

**Comment by jdaviescoates** [comment]
@gracebir presumably you mean access to my instance of Nextcloud?

What sort of access do you require?

**Comment by alishaz-polymath** [comment]
Fixed in #3585

**Comment by jdaviescoates** [comment]
I'm not sure if this fix has actually been pushed to Cal.com yet(?) but I just did a test and what happens in this:

1. edit location of a booking
2. no duplicate is created!

So, fixed, right?!?

Wrong.

No duplicate events are created, but also editing the event location had zero effect. The location was not changed anywhere.

So, at present it is seemingly not possible to actually edit the location of a booking!

**Comment by alishaz-polymath** [comment]
Hey @jdaviescoates , that's a different issue and clearly the issue title here suggests that it creates a duplicate event which it doesn't anymore. As for the issue you mention, the PR #3905 fixes the issue you mention in this latest comment. 🙏

**Comment by jdaviescoates** [comment]
I guess I'll have to trust you on that for now @alishaz-polymath :) 

(I'm just hoping the reason no duplicate happen when editing isn't that nothing actually happens when editing!) :)

**Comment by jdaviescoates** [comment]
Thanks @alishaz-polymath 

Once #3905 has merged how long will it take for it to be deployed to cal.com?

**Comment by alishaz-polymath** [comment]
We normally do a minor release and deployment every week, so you should expect it in a week or so at the latest (post merge) but normally it should be well under that time frame.
