### ISSUE TITLE
/ee/ & PRO: add your own logo in cal.com/video

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3028]
right now we show our logo:

<img width="254" alt="Screenshot 2022-06-08 at 21 23 47" src="https://user-images.githubusercontent.com/8019099/172699995-9f0edc03-831e-4be3-b9a4-576fc8cc544f.png">

it would be cool if you could upload your own logo.

not sure where the image uploader should be in (settings or teams?)

**Comment by PeerRich** [comment]
also, we would need to tell the customer to have a transparent background and white logo

**Comment by joaoGabriel55** [comment]
Hello @PeerRich! Can I get this task?

**Comment by joaoGabriel55** [comment]
I need to ask. How can I access the video call link in development mode?

**Comment by PeerRich** [comment]
> Hello @PeerRich! Can I get this task? I think would be needed define the requirements to upload the logo.

i need to check in with @Jaibles where the best place is for an image uploader but afterwards yes! will give you a staging key too
