### ISSUE TITLE
Infinity loop when the action "booking Successful" is triggered using the @calcom/embed-react lib.

### ISSUE THREAD

**Issue by aayestashn** [calcom/cal.com#3039]
### Issue Summary

I am using the @calcom/embed-react lib, with a react with typescript application, and also a self-hosted Cal.com version.

When I am trying to schedule a meeting with the embed lib, the application enters the infinity loop as you can see in the following video:
[Video](https://www.loom.com/share/f79a0664466144aab7152aa68ff67bd2
)

I am using this example that was a recommendation for the cal.com team. [link](https://codesandbox.io/embed/action-event-listeners-demo-react-cmj1c8?file=/src/App.js&codemirror=1)

### Steps to Reproduce

In this link, you can see the problem by the code example.

1. Go to this [link](https://codesandbox.io/s/epic-lumiere-7rc137?file=/src/App.js:90-109)

**Comment by hariombalhara** [comment]
@aayestashn you seem to have deployed a pretty old version of cal.com on https://calendso-test.onrender.com.
The bug exists in that old version. Can you try updating it.

Latest(on https://app.cal.com):
<img width="1240" alt="Screenshot 2022-06-12 at 10 37 27 AM" src="https://user-images.githubusercontent.com/1780212/173215546-8377ff13-b464-43f4-9eeb-0264e9e8a981.png">

Outdated(on https://calendso-test.onrender.com):
<img width="1259" alt="Screenshot 2022-06-12 at 10 37 10 AM" src="https://user-images.githubusercontent.com/1780212/173215520-a98e8caf-8c6e-409b-806e-8bd2332d32b7.png">

**Comment by hariombalhara** [comment]
Closing the issue as it was alread fixed in latest main
