### ISSUE TITLE
Round-robin not working

### ISSUE THREAD

**Issue by jkaczmarek1** [calcom/cal.com#3046]
When I tried to book team event with round-robin scheduling type, this event doesn't show at team members calendars (only showed at "Bookings" tab in cal.com).

Steps to reproduce:

1. Create team in settings tab
2. Create team event
3. Every team member should have their Google calendar connected
4. Set scheduling type to "Round Robin"
5. Book event

**Comment by gracebir** [comment]
@jkaczmarek1 , could you attack a loom video to this issue please?

**Comment by gitstart** [comment]
Hi @jkaczmarek1 ! hope this message finds you well

we tried your issue but it looks like that for us, it is working properly, can u check and see if there is anything different on the video?

https://www.loom.com/share/44a0287e5e7d4f4aa182801d0de05431

**Comment by PeerRich** [comment]
can you record a video showing that its not working? @jkaczmarek1

**Comment by emrysal** [comment]
Closing this as it's not the same as #3531 and it cannot be reproduced.
