### ISSUE TITLE
BUILD not working on Debian Server (10) after last update

### ISSUE THREAD

**Issue by thedevale** [calcom/cal.com#3056]
I have a self-hosted version on debian server. No docker, plain hosting

I just updated my system following the guide, and now the build doesn't work anymore

the error I am getting in yarn dev is:

TypeError [ERR_INVALID_OPT_VALUE] [ERR_INVALID_OPT_VALUE]: The value "undefined" is invalid for option "entryTypes"
@calcom/web:dev:     at PerformanceObserver.observe (perf_hooks.js:384:13)
@calcom/web:dev:     at eval (webpack-internal:///../../packages/lib/server/defaultResponder.ts:15:45) {
@calcom/web:dev:   code: 'ERR_INVALID_OPT_VALUE'
@calcom/web:dev: }

Same error occuring in build

@calcom/web:build: > Build error occurred
@calcom/web:build: TypeError [ERR_INVALID_OPT_VALUE] [ERR_INVALID_OPT_VALUE]: The value "undefined" is invalid for option "entryTypes"
@calcom/web:build:     at PerformanceObserver.observe (perf_hooks.js:384:13)
@calcom/web:build:     at /var/www/cal.com/apps/web/.next/server/chunks/1052.js:14615:63 {
@calcom/web:build:   type: 'NodeError',
@calcom/web:build:   code: 'ERR_INVALID_OPT_VALUE'
@calcom/web:build: }
@calcom/web:build: error Command failed with exit code 1.

**Comment by PeerRich** [comment]
@zomars any ideas?

**Comment by zomars** [comment]
Hi @thedevale can you give us more context starting with which node version does your server is using? We recently upgraded to v16 ourselves but there might be some v14 conflicts there.
