### ISSUE TITLE
Inline Embed have few issues

### ISSUE THREAD

**Issue by JOduMonT** [calcom/cal.com#3075]
1. one is when you choose **Inline Embed HTML** and click Copy; it's the Inline Embed code for React, we copy.
~~2. even if I select **light theme**, it's still appearing in dark theme.~~
![Untitled](https://user-images.githubusercontent.com/5204724/174011510-14945a67-8e80-4492-874c-98287ca81e1a.gif)

**Comment by PeerRich** [comment]
@hariombalhara can you take a look?

**Comment by hariombalhara** [comment]
@JOduMonT Thank you so much for reporting these issues.
1. I can replicate the 'Copy Code' bug. Should be fixed soon.
2. Translation seems to work correctly in embed for me on Chrome. Which browser did you try on ?
<img width="1145" alt="Capture d’écran 2022-06-16 à 5 02 48 PM" src="https://user-images.githubusercontent.com/1780212/174061120-a0a1df8f-453c-44dc-bf3d-b07474ecfc37.png">
3. Also, I am not able to replicate the safari bug too. Can you share the URL where you have embedded cal.
Tried with full width and 50% width
https://www.loom.com/share/ec64540cfe914610bb7a380cf27a42d3
https://www.loom.com/share/085636b2550b4632924785bc9c4db444
https://www.loom.com/share/c9f3ae43ff49474288a56bdb13912c47

**Comment by hariombalhara** [comment]
Only 1 issue is fixed with the PR. So reopening it as it got auto closed

**Comment by hariombalhara** [comment]
I am closing this issue. Please open a fresh one if you feel that the issue still exists.
