### ISSUE TITLE
Missing attendees in caldav events

### ISSUE THREAD

**Issue by TheCapsLock** [calcom/cal.com#3076]
### Issue Summary

Attendees are not set in events saved to caldav (they are only shown in event's description)
When I edit an event created by calcom in my calendar, there is no attendees in the corresponding section of the UI (eg in Gnome Evolution). If I try to change something like event's description and hit save button ; an error is raised saying that a meeting must have at least one attendee

### Steps to Reproduce

1. book something on calcom for an organizer which uses caldav sync
2. go to an app and edit corresponding booking
3. change something (like add some details to the description or add reminders)
4. try to save changes: the Calendar app (Evolution) tells that there must be at least one attendee at the meeting.

### Technical details

- Firefox 100.0.2 ; cal.com v1.6.3 ; node v14.19.3
- Caldav server : nextcloud 24.0.1

**Comment by Toledodev** [comment]
Can you send a loom video about the bug?

**Comment by alishaz-polymath** [comment]
Currently, the CalDAV data sent out does not include ATTENDEE property which is the reason that this issue exists. Currently we're only sending all the data through the description, which isn't great. I'll get started on this now and hopefully resolve this soon! 
🙏 
Thanks for bringing this into our attention, and sincere apologies for the delay
