### ISSUE TITLE
Error ESLint

### ISSUE THREAD

**Issue by Ratatom** [calcom/cal.com#3085]
I'm getting this error when trying to upload the project to production on a private server. 
Can someone help me?

@calcom/web:build: Generated `apps.server.generated.ts` and `apps.browser.generated.tsx`
@calcom/web:build: info  - Checking validity of types...
@calcom/web:build: 
@calcom/web:build: Failed to compile.
@calcom/web:build: 
@calcom/web:build: ./pages/api/auth/saml/token.ts
@calcom/web:build: 15:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/api/auth/saml/userinfo.ts
@calcom/web:build: 41:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/api/auth/signup.ts
@calcom/web:build: 84:2  Error: Insert `⏎`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./pages/api/teams/[team]/invite.ts
@calcom/web:build: 109:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/apps/[slug]/index.tsx
@calcom/web:build: 25:31  Warning: 'placeholder' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./pages/auth/signup.tsx
@calcom/web:build: 32:34  Warning: 'email' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 168:1  Error: Delete `··`  prettier/prettier
@calcom/web:build: 199:3  Error: Insert `⏎`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./pages/auth/sso/[provider].tsx
@calcom/web:build: 104:19  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/settings/profile.tsx
@calcom/web:build: 123:48  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 124:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 125:45  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 126:54  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 127:46  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 128:52  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 129:64  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 
@calcom/web:build: ./lib/QueryCell.tsx
@calcom/web:build: 71:34  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:51  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:56  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:61  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:66  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:71  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:76  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./lib/app-providers.tsx
@calcom/web:build: 4:37  Warning: 'useMemo' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./lib/config/next-seo.config.ts
@calcom/web:build: 28:12  Error: Insert `⏎`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./lib/hooks/useSlots.ts
@calcom/web:build: 194:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 
@calcom/web:build: ./lib/jackson.ts
@calcom/web:build: 22:21  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./lib/slots.ts
@calcom/web:build: 52:3  Warning: 'currentSeats' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./lib/telemetry.ts
@calcom/web:build: 87:13  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:27  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 93:49  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./lib/types/inferSSRProps.ts
@calcom/web:build: 3:35  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 5:35  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 7:48  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
@calcom/web:build: error Command failed with exit code 1.
@calcom/web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:build: Error: command finished with error: command (apps/web) yarn run build exited (1)
command (apps/web) yarn run build exited (1)

 Tasks:    4 successful, 5 total
Cached:    1 cached, 5 total
  Time:    33.316s 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will investigate this.

**Comment by Udit-takkar** [comment]
@lienista thanks for reporting this. only password requirement for an admin user has been changed to 16 character because of SOC2 compliance. i have raised a PR to change the text here.

**Comment by Udit-takkar** [comment]
@lienista have you tried build on the current main branch? it is not throwing any eslint error for me
