### ISSUE TITLE
[CAL-769] Unable to send Email, tried different SMTP servers. 

### ISSUE THREAD

**Issue by erzhan89** [calcom/cal.com#3098]
### Issue Summary

@calcom/web:start: SEND_BOOKING_CONFIRMATION_ERROR Error: Connection timeout
@calcom/web:start:     at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:start:     at SMTPConnection._onError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:start:     at Timeout.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:start:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:start:     at processTimers (internal/timers.js:500:7) {
@calcom/web:start:   code: 'ETIMEDOUT',
@calcom/web:start:   command: 'CONN'
@calcom/web:start: }
@calcom/web:start: sendEmail Error: Connection timeout
@calcom/web:start:     at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:start:     at SMTPConnection._onError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:start:     at Timeout.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:start:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:start:     at processTimers (internal/timers.js:500:7) {
@calcom/web:start:   code: 'ETIMEDOUT',
@calcom/web:start:   command: 'CONN'
@calcom/web:start: }

### Steps to Reproduce

Tried different SMTP accounts.. but no luck... Gmail, Office365.. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Node.js version 14
- Anything else that you think could be an issue.

<sub>[CAL-769](https://linear.app/calcom/issue/CAL-769/unable-to-send-email-tried-different-smtp-servers)</sub>

**Comment by milospuac** [comment]
Thanks for reaching out and sorry about the delay. Our team will investigate this

**Comment by erzhan89** [comment]
Is there any news about it ?

**Comment by manntam** [comment]
same here! does anyone have an idea how to fix this? No emails are being sent at all

**Comment by PeerRich** [comment]
can you try the most recent version?

**Comment by TheMo0102** [comment]
Hi, i have the same issue with this error, i have installed the Main Version of cal.com.
