### ISSUE TITLE
Optional chaining syntax missing from `eventType.seatsPerTimeSlot`

### ISSUE THREAD

**Issue by pryley** [calcom/cal.com#3110]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When the "Offer seats" event option is disabled, the public meeting confirmation screen shows a black "0". 

<img width="859" alt="Screenshot 2022-06-20 at 13 22 31" src="https://user-images.githubusercontent.com/134939/174591152-405e3854-01af-47ed-9cfd-91e3f5882d6a.png">

<img width="818" alt="Screenshot 2022-06-20 at 13 21 24" src="https://user-images.githubusercontent.com/134939/174590986-7b2ac356-9f78-4ab3-a851-47e60a904a82.png">

It looks like the optional chaining syntax is missing here:

<img width="887" alt="Screenshot 2022-06-20 at 13 25 13" src="https://user-images.githubusercontent.com/134939/174591666-a41ab93b-7e1f-4195-a4e7-26333b8b4964.png">

Shouldn't it be: `{eventType?.seatsPerTimeSlot && ( ... )}` ?

### Technical details
cal.com v1.7.1

**Comment by Toledodev** [comment]
I tried to reproduce the behavior now, but the interface is a little different from the one you showed (the "0" didn't appear either). Please try giving a "git pull" on your machine

**Comment by emrysal** [comment]
@pryley is correct here; it's caused by having the seats feature when you set the amount of seats to 0, which is falsy but not as a string. I've PR'ed the fix & set this issue to close upon merge, I expect it to go live today as part of the normal release.
