### ISSUE TITLE
Huddle01 installation (no success message and no redirect )

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3142]
### Issue Summary

When installing Huddle01, I don’t get any message that it was successfully installed and it also doesn't redirect to installed apps. I didn't experience that with any other apps so far.

[Loom Video](https://www.loom.com/share/e126916015a3418aa3b1d3ac577b49ba
)
### Steps to Reproduce

1. Disconnect Huddle01 (if already installed)
2. Install Huddle01
3. See that no success message appears and that you are not redirected
4. Go to installed apps to see that it is installed

**Comment by noobyogi0010** [comment]
Hey, @CarinaWolli 
If no one is working on this issue I would like to take it up.
Thanks!
