### ISSUE TITLE
Inconsistencies between already booked events and scheduling

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#3143]
### Issue Summary

Scheduling seems to ignore already booked events (Availability is set to thursday, 11-12h; two events 11:30-11:45 and 11:45-12:00 are booked). In addition the calender is blocked with another non cal.com related event between 11:00-11:30h.

<img width="250" alt="Bildschirmfoto 2022-06-23 um 09 25 10" src="https://user-images.githubusercontent.com/2770597/175242656-c7ea2833-aaa2-4a93-9c55-5bf040723f5b.png">

<img width="745" alt="Bildschirmfoto 2022-06-23 um 09 25 18" src="https://user-images.githubusercontent.com/2770597/175242701-24a55c18-0a72-4365-9e18-60fc97b978b0.png">

<img width="597" alt="Bildschirmfoto 2022-06-23 um 09 48 11" src="https://user-images.githubusercontent.com/2770597/175245321-f5a8058a-82b4-42c3-9b74-ef8aa9c47c74.png">

### Steps to Reproduce

1. Book event 
2. Already booked event not always is blocked in scheduling picker

Until cal.com version 1.6.3 there has been no problems. 

### Technical details
- Browser version: Firefox 101.0.1
- Node.js version: v14.19.3
- CalDAV-Server radicale
- cal.com selfhosted (fef6f3baff040bb4d5212f92223e4b1d88115c36)

**Comment by MuriloAmarals** [comment]
Hey @bhopmann, I reproduced your issue on my localhost and it didn't appear this bug.

![Opera Instantâneo_2022-06-27_093146_localhost](https://user-images.githubusercontent.com/87545137/175944069-3bd876b7-cfab-40d2-b411-46f119622227.png)

![Opera Instantâneo_2022-06-27_093916_localhost](https://user-images.githubusercontent.com/87545137/175944074-b6f1482e-19a3-4ef8-918a-745c34b87bf8.png)

**Comment by peseotni** [comment]
I also have the version 1.6.3 on self-hosted server and the same issue, multiple users reserved the same timeslot.
![same_timeslot](https://user-images.githubusercontent.com/22613392/176375209-01cfe906-6d8c-4a1e-97b2-856662f6a109.jpg)

**Comment by alishaz-polymath** [comment]
Hi @peseotni , Can you please confirm if you have a destination calendar selected? 

Eg: 
![image](https://user-images.githubusercontent.com/52925846/179685569-5726e011-b31f-4b97-9907-cfc645cd91bd.png)

**Comment by emrysal** [comment]
Closed as fixed
