### ISSUE TITLE
Availability page displays two Timezone dropdown button for mobile view

### ISSUE THREAD

**Issue by niteshsingh1357** [calcom/cal.com#3158]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Availability page displays two Timezone dropdown button for mobile view

### Steps to Reproduce

1. Go to Event Types
2. Click on Preview button for any one of the Event Types
3. Follow the link in a new tab
4. Enable mobile view
5. Notice one more Timezone dropdown button just below the calendar

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- https://www.loom.com/share/ad5975aa1878499380753c0b2877a494
<img width="383" alt="Screen Shot 2022-06-26 at 8 50 14 AM" src="https://user-images.githubusercontent.com/31402501/175797682-31b069d0-d9ad-4c35-8537-28e8f987f53d.png">

### Expected Behaviour

- Second dropdown button below the calendar should not be displayed

**Comment by PeerRich** [comment]
nice catch and easy fix! will do

**Comment by gracebir** [comment]
can take a look on this

**Comment by gracebir** [comment]
https://github.com/calcom/cal.com/blob/main/apps/web/components/booking/pages/AvailabilityPage.tsx#:~:text=%3Cdiv%20className%3D%22mt%2D4%20ml%2D1%20block%20sm%3Ahidden%22%3E%7BtimezoneDropdown%7D%3C/div%3E

@PeerRich , I would to understand why we need this other timezone dropdown, and in which scenario is it going to be displayed?

**Comment by PeerRich** [comment]
a PR has been opened
