### ISSUE TITLE
language sometimes switching to wrong locale

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3160]
@zomars EDIT:

Some user reported that their account was switched to German and a moment later it switched back to English.

Issue was replicated, but it was happening to that specific user.

Investigating if it may have something to do with browser/locale combination.

**Comment by PeerRich** [comment]
https://twist.com/a/195135/ch/554218/t/3579296/

**Comment by gracebir** [comment]
@PeerRich , is it possible please to use another tool for describing the issue, cause we are not able to access `twist` work space?

**Comment by PeerRich** [comment]
one of the core team members is already looking into this

**Comment by PeerRich** [comment]
yeah i myself havent had more context 🙏

**Comment by manuelgu** [comment]
I have had the same issue (english to swedish).

**Comment by zomars** [comment]
@manuelgu Can you go https://www.whatsmybrowser.org and post here the generated url?

**Comment by manuelgu** [comment]
@zomars https://www.whatsmybrowser.org/b/3W9DE

**Comment by hariombalhara** [comment]
The issue is fixed now.
