### ISSUE TITLE
Signup goes from /signup to /login with no confirmation of account creation

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3164]
Creating an account on the live app takes me straight to a login page with no account confirmation (bar a toast).

https://user-images.githubusercontent.com/4536123/175927740-f74b91b9-61f2-4446-aa63-a678d8bbd473.mp4

Relevant designs: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=3412%3A40621

**Comment by gracebir** [comment]
@Jaibles , for some reason I ignore, that functionality has been removed, cause it suppose to be in this folder `apps/web/lib/emails/templates`, but it was deleted

**Comment by agustif** [comment]
https://github.com/calcom/website/pull/172
Also related https://github.com/calcom/cal.com/pull/3580
Has been merged to main, (where it works as expected) but did get the infinite redirect loop again on production, we will investigate tomorrow / try again at deploying during the week.

**Comment by PeerRich** [comment]
@agustif were you able to test this again on staging?

**Comment by PeerRich** [comment]
this needs to work for 2.0

**Comment by PeerRich** [comment]
assigned @hariombalhara now fyi @agustif

**Comment by hariombalhara** [comment]
@agustif @PeerRich Is there any work in progress on implementing those screens from figma?
