### ISSUE TITLE
[CAL-2979] ICS feed support for checking against double bookings

### ISSUE THREAD

**Issue by sihma** [calcom/cal.com#3167]
### Is your proposal related to a problem?

I teach a language on italki. When people book lessons, the lessons event get dynamically updated in an .ics file calendar that's hosted through http. I use software (Thunderbird on my computer and ICSx5 on my Android smartphone) to see this calendar along my usual calendar (in CalDAV).

[Cal.com](http://Cal.com) has the ability to check my CalDAV for events that are present when someone want to book a meeting. Sadly, if someone booked a lesson on italki, the lesson will only show in the read-only ICS calendar. Therefore, someone could book a meeting on my [Cal.com](http://Cal.com) page even though I'm already booked on italki.

I have no abilities to automatically import the ICS feed in my CalDAV calendar for [Cal.com](http://Cal.com) to see when I'm busy.

### Describe the solution you'd like

I would click on addons, click on ICS calendar, enter the link and press okay. [Cal.com](http://Cal.com) would check this one and my CalDAV calendar and prevent double bookings.

It would be awesome if [Cal.com](http://Cal.com) had an app to read the ICS calendar (the same way it reads my CalDAV calendar) when someone is trying to book a meeting. ICS calendars are very easy to set up (just a link) and I believe there wouldn't be much to be changed from the CalDAV [Cal.com](http://Cal.com) support app code.

Integrated support for ICS feeds is common in most calendar solution, so it would only make sense [Cal.com](http://Cal.com) also does. (IOS, Google and Thunderbird all support it. Sadly, not automatic import, because it doesn't really make sense except for my use case).

### Describe alternatives you've considered

I've added the calendar as a subscription to my CalDAV calendar (hosted at Infomaniak), but [cal.com](http://cal.com) is totally incoherent when it comes to seeing them or not (sometimes it does and I can't book times where I'm unavailable and sometimes it doesn't). As such, I think it would work better if this was part of [Cal.com](http://Cal.com) features.

![addedcalendars](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/187ef17f-c7c7-48e9-b78f-aafe9b1e9da9/8fb2d917-d38a-44be-b666-d1f0ffa555b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8xODdlZjE3Zi1jN2M3LTQ4ZTktYjc4Zi1hYWZlOWIxZTlkYTkvOGZiMmQ5MTctZDM4YS00NGJlLWI2NjYtZDFmMGZmYTU1NWI5IiwiaWF0IjoxNzA1NzU2NTI2LCJleHAiOjE3MDU4NDI5MjZ9.eUyKtLH34gaBra6iZu54v4fRORccJU4ee--MZMP0QYk)

### Additional context

Thanks for your answer and work on [Cal.com](http://Cal.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2979](https://linear.app/calcom/issue/CAL-2979/ics-feed-support-for-checking-against-double-bookings)</sub>

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our team will look into this.

**Comment by PeerRich** [comment]
after looking into this, it seems like a fairly sized feature to build with not a lot of people requesting it. 

maybe someone from the community wants to pick this up and release it as an app in the app store?

**Comment by christianpetty** [comment]
This feature would enable support for Proton Calendar and other encrypted platforms that offer availability via ICS links.

**Comment by aspiers** [comment]
Yes, there are many platforms which export availability via ICS URLs.  My guess for the reported low number of people requesting it is that it's the kind of feature which won't occur to most people as useful until they actually see it implemented.  IMHO the ubiquity of ICS as a well-adopted standard makes this a very desirable feature for growing the platform.

I guess it would be fine as an app.  I don't know the code base yet, but I'm a bit surprised to hear that it would be a fairly sized feature to build, since isn't it pretty much the simplest app you could build?  It just has to fetch data from a single URL and integrate it.  Probably I'm missing a bunch of complexity.  Or is it just that even building a simple app is quite a lot of work?

**Comment by TobiTenno** [comment]
Is there a place we can express our desire for this? I don't want to cause noise on a ticket, but as Christian mentioned, this would be highly impactful

**Comment by PeerRich** [comment]
maybe @alishaz-polymath can look into this as he is working closely with caldav

**Comment by aspiers** [comment]
# Related issues

#2054 is very similar to this, but see https://github.com/calcom/cal.com/issues/2054#issuecomment-1211943072 for the difference.

#3810 is a request for the "opposite" feature, i.e. cal.com being able to export an aggregated ICS feed (which could be a collection of either VFREEBUSY or VEVENT) to other systems, in contrast to this and #2054 which are both about cal.com importing an ICS feed. I see great value in both features, even though they are pretty much exact opposites of each other.

**Comment by alishaz-polymath** [comment]
I just want to mention here that this feature is up next for us in CalDAV as soon as we have stabilized the integration enough to consider it robust. This could still take some time, but it is surely now in our sight 🙏

**Comment by christianpetty** [comment]
@alishaz-polymath that’s awesome!

**Comment by penyuan** [comment]
> I just want to mention here that this feature is up next for us in CalDAV as soon as we have stabilized the integration enough to consider it robust. This could still take some time, but it is surely now in our sight pray

Can't wait! Cal.com being able to *subscribe* to published ICS feeds would be a killer feature for me. Without it I literally can't use Cal.com right now...

**Comment by sepehr** [comment]
This would be much appreciated! I'd rather publish & connect a redacted ICS instead of full caldav credentials.

**Comment by penyuan** [comment]
Is this on the roadmap for a future version? Like 2.x?

**Comment by NightmindOfficial** [comment]
This is also a great feature for people who cannot import their calendars due to organization administrator restrictions. 

As an example, I am currently a student and my university does not allow me to import my Outlook calendar into cal.com as this requires elevated privileges. However, I do have an .ics feed that I already imported to other apps such as Google calendar etc. showing me all internal events in read-only mode. 

With the feature mentioned above, cal.com could prevent double-bookings colliding with read-only calendars, which is kind of a hygiene factor.

**Comment by mschneiderwng** [comment]
/bounty 100  for checking against a .ics urls for non-availability to prevent double-bookings. 

- It should be possible to use with other apps like Google Calendar, Exchange or CalDav.
- It should query the .ics before a booking (not import the .ics once and then never update).
- It should be possible to add multiple .ics urls.

**Comment by algora-pbc** [comment]
👋 Hey @mschneiderwng, only the [Cal.com members on Algora](https://console.algora.io/org/cal/members) are authorized to create bounties. You can sign up with a @cal.com address to auto join the org.

Alternatively, you can [create a community bounty](https://console.algora.io/org/cal/bounties/new) on behalf of your personal account.

**Comment by Hitesh-sisara** [comment]
attempt #3167

**Comment by saschafoerster** [comment]
I would like to control team availabilities, so that an admin can add an calendar with holidays or other closing days, and then no one of the team is available, independent of the individual settings: 
Maybe this fit's in here? .../availability?type=team
For instance we could use an Apple ics with the german holidays for that: 
https://calendars.icloud.com/holidays/de_de.ics

**Comment by tweetandcode** [comment]
Hello 👋, this looks interesting.
I want to work on this if I can.

**Comment by skyrunner360** [comment]
Hey! @Hitesh-sisara @tweetandcode Do you want to work on this together and split the bounty?

**Comment by AliYar-Khan** [comment]
Whats the progress on this ?

**Comment by penyuan** [comment]
I'm not a programmer, but I'm a user who can't wait for robust open source ICS feed support and literally can't use Cal.com for my purposes without it.

Is there a way for me to add some money to the bounty to make things happen quicker??

**Comment by algora-pbc** [comment]
Hi @penyuan, absolutely! You can add a bounty for this issue here 👉 https://algora.io/org/cal/bounties/new

**Comment by penyuan** [comment]
Hi @algora-pbc thanks for the link. But I think someone else has already created a bounty for this issue? If so, my question is if I can add more $$$ to that existing bounty?

**Comment by algora-pbc** [comment]
@penyuan we pool all bounties for the same issue into a single bounty pot, so that would be the same thing :innocent:

**Comment by Faknit** [comment]
Just chipping in here to say that I'm so stoked that this is finally getting traction. I also literally can not use cal.com until this feature is active (no admin approval for work calendar). I'm also adding to the bounty.

**Comment by algora-pbc** [comment]
💎 **$100** bounty has been added to the prize pool by @Faknit!

**Comment by penyuan** [comment]
> @penyuan we pool all bounties for the same issue into a single bounty pot, so that would be the same thing 😇

Oh I see, understood! Can't wait for ICS feed to get 1st class support!

**Comment by dgrocks22** [comment]
Is this Bounty still open ?

**Comment by PeerRich** [comment]
>  Is this Bounty still open ?

 

yes

**Comment by PlanetKumbhaj** [comment]
Attempt

**Comment by PlanetKumbhaj** [comment]
Is the issue is live?

**Comment by ezhil56x** [comment]
An app should be added to the store which supports managing multiple ics urls. When there is a clash between the time slots in cal.com and the ics calendar schedule. It should be blocked and users shouldn't be able to book for a meeting in the particular slot.

**Comment by mschneiderwng** [comment]
@jkcs No, the ics should not be **imported**. ics urls have to be managed (see my original requirements and @ezhil56x comment above).

**Comment by ezhil56x** [comment]
I would like to also add that it should be realtime not like importing once when the ics url is provided.

**Comment by Faknit** [comment]
For my use case, I have a work calendar that I'm unable to get admin privileges for, but I'd like cal.com to check against that for availability. Calendly does this one way or another, I think by essentially subscribing to the .ics and checking free/busy. Bonus points if I can tell cal.com specifically which events from the .ics I want it to consider free/busy in my availability.

And as @ezhil56x said, the key is **subscribing** vs importing.

**Comment by sy425191** [comment]
Hey, can you all confirm if I understood it correctly?

- [] Creating app inside cal.com which can be used for referencing ICS links to user's account
- [] Users can enable, disable ICS links for particular event types.
- [] When someone is trying to book a meeting, then we should query the ICS link and prevent double booking on already booked slots
- [] Add check on backend to prevent double booking.

**Comment by Faknit** [comment]
Replies in line


> Hey, can you all confirm if I understood it correctly?
> 
>     * Creating app inside cal.com which can be used for referencing ICS links to user's account

**This sounds right to me, but I'm unable to use Cal.com at the moment so I don't know the workflow.**

> 
>     * Users can enable, disable ICS links for particular event types.

**I'm not sure about event types, exactly. Here is an example of what I'm looking for: On January 17th, I have 6 meetings scheduled on my work calendar, which Cal.com subscribes to and sees as events. BUT, 1 of those meetings is not super important, so I'm okay with being double booked for that specific event. I'd like to be able to mark that time slot as available on Cal.com.**

> 
>     * When someone is trying to book a meeting, then we should query the ICS link and prevent double booking on already booked slots
> 
>     * Add check on backend to prevent double booking.

**I'm not sure what the difference is between the last 2 bullet points. But they both sound right.**

**Comment by mogery** [comment]
> **I'm not sure about event types, exactly. Here is an example of what I'm looking for: On January 17th, I have 6 meetings scheduled on my work calendar, which Cal.com subscribes to and sees as events. BUT, 1 of those meetings is not super important, so I'm okay with being double booked for that specific event. I'd like to be able to mark that time slot as available on Cal.com.**

That'd be really cool, but Cal.com is *really* not set up to handle that on an app level. Unfortunately it'd probably have to be done by someone with a deeper understanding of the codebase.

**Comment by Faknit** [comment]
This is a tad bit embarrassing, but I can't figure out how to "give" a bounty..

**Comment by algora-pbc** [comment]
Hi @Faknit, you can complete the payment from [your org dashboard](https://console.algora.io/org/faknit/bounties) on Algora :raised_hands:

**Comment by algora-pbc** [comment]
Ah it looks like you're logged out! You'll see a reward button once you login:

![](https://github.com/calcom/cal.com/assets/136125894/a436d0e7-b7f8-423f-8d1e-8b91a9cef475)

**Comment by Faknit** [comment]
I was about to ban myself from the internet if I forgot to login. But, the plot thickens:
![image](https://github.com/calcom/cal.com/assets/106571835/6284a414-91bf-4871-9920-87cf0ae39290)

**Comment by mogery** [comment]
> I was about to ban myself from the internet if I forgot to login. But, the plot thickens:
> 
> ![image](https://github.com/calcom/cal.com/assets/106571835/6284a414-91bf-4871-9920-87cf0ae39290)
> 
> 

Also, my `/claim` command only claimed the calcom bounty on my side of the interface, not the other two bounties set by non-org people.

**Comment by algora-pbc** [comment]
Just sent you an email (from zafer@algora.io) to get this sorted out, apologies for the inconvenience here. My best guess is that you're logged in as another user who doesn't have access to the org

**Comment by mogery** [comment]
Thank you!

**Comment by ezhil56x** [comment]
@mogery Good job! 🚀

**Comment by mogery** [comment]
And thank you as well! <3

**Comment by penyuan** [comment]
Thanks @mogery where can I find this feature in cal.com??? I can't find it under apps.... Please advise, thanks!

**Comment by lucasskluser** [comment]
> Thanks @mogery where can I find this feature in cal.com??? I can't find it under apps.... Please advise, thanks!

Looks like it should be already added to app store. Maybe it's not being shown because the version specified is 0.0.0.

![CleanShot 2024-02-20 at 11 44 39](https://github.com/calcom/cal.com/assets/28795323/4ae3b91e-0676-4bb8-8dff-c1745d0594aa)

[Link to the file](https://github.com/calcom/cal.com/blob/72c493ee21cb669e7a935df5e1c9476beb107c75/packages/app-store/ics-feedcalendar/package.json#L5C3-L5C22)

**Comment by wivaku** [comment]
[Release notes](https://github.com/calcom/cal.com/releases/tag/v3.8.4) for 3.8.4 refer to ICS feed icon, in this ticket it refers to 3.8 and 3.9 milestone. Does this mean ICS feed is available in 3.8.4? Same for me: could not find it under calendar apps.

**Comment by wivaku** [comment]
ICS feed is available in v3.9. Have not been able to add an ICS calendar yet though. 
E.g. iCloud public holidays: https://calendars.icloud.com/holidays/us_en-us.ics
or Outlook: https://outlook.office365.com/owa/calendar/<...>/<...>/calendar.ics

Both give error: `No handlers found for ics-feed`

**Comment by penyuan** [comment]
Same here, I'm getting the same error as @wivaku. I shared Outlook 365 calendar under my control with full view permissions, with URL in the form of `https://outlook.office365.com/owa/calendar/<...>/<...>/calendar.ics`, and copied it into the "ICS Feed" app. And I got an error saying: 

`No handlers found for ics-feed`

@mogery and other developers: Can you please advise? Thank you!!

**Comment by mogery** [comment]
Hey there! Sorry that it's not working for you, maybe something was brought in between the merge and now that broke things. I don't have a whole lot of time on my hands immediately, but I will look into it as soon as possible.

**Comment by penyuan** [comment]
> Hey there! Sorry that it's not working for you, maybe something was brought in between the merge and now that broke things. I don't have a whole lot of time on my hands immediately, but I will look into it as soon as possible.

Oh hey thanks for the quick response @mogery!! ❤️ Really appreciate you investigating this issue as soon as possible.

**Comment by Rubenkl** [comment]
Thanks for all the commits! I really was impatient to this feature, so I found a workaround for it. Just sharing here in case someone is interested.

I use the following script to automatically "copy" an ICS calendar to a separate google calendar (runs by itself every 15 minutes). Then, I can just import that calendar in cal.com like a regular calendar:
https://github.com/derekantrican/GAS-ICS-Sync

**Comment by warengonzaga** [comment]
> This feature would enable support for Proton Calendar and other encrypted platforms that offer availability via ICS links.

How about writing to Proton Calendar?

**Comment by colans** [comment]
For those interested in Proton Calendar integration, give a :+1:  to https://github.com/calcom/cal.com/issues/14300.  That's where the Proton stuff is happening now that https://github.com/calcom/cal.com/issues/5756 is closed.

**Comment by warengonzaga** [comment]
> For those interested in Proton Calendar integration, give a :+1:  to https://github.com/calcom/cal.com/issues/14300.  That's where the Proton stuff is happening now that https://github.com/calcom/cal.com/issues/5756 is closed.

Followed! Looking forward to the feature!
