### ISSUE TITLE
Troubleshooter fails when viewing next month

### ISSUE THREAD

**Issue by chasebolt** [calcom/cal.com#3169]
### Issue Summary

Today is June 27th and I am attempting to troubleshoot an issue with my calendar for July 5th. When I selected a date the is not in my current month (June), the troubleshooter fails to use the correct date.

![image](https://user-images.githubusercontent.com/1222984/176035310-d4ce6f32-4eac-4196-ab24-832e4c1ae252.png)

### Steps to Reproduce

1. Went to Troubleshooter
2. Changed the date to a date residing in the next month
3. The times listed will not be the selected date

### Technical details

- Running the docker container with version 1.7.2 built

**Comment by zomars** [comment]
This was fixed in 1.7.3 [here](https://github.com/calcom/cal.com/commit/58b2a6425a9fcef485f1778f959a0f70894eb319#diff-a6b39df52ae3ed655264e3f592ac13e6c710be8b7bb75dbcd7047c6b524d1073)

**Comment by chasebolt** [comment]
👋 @zomars this doesn't appear to be fully fixed in 1.7.3

Here is a screen recording of the issue https://share.vidyard.com/watch/k9GvynTwWJaMDmvJMZzRrq

**Comment by zomars** [comment]
Hey @chasebolt thanks I think I've misunderstood the original issue. Will investigate 🙏🏽

**Comment by chasebolt** [comment]
> Hey @chasebolt thanks I think I've misunderstood the original issue. Will investigate 🙏🏽

np! sometimes a video is the best way to show the issue 😅

**Comment by PeerRich** [comment]
we're working on an entire new troubleshooter

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/issues/6729
