### ISSUE TITLE
Link to specific event slot in the future always jumps to current month

### ISSUE THREAD

**Issue by manuelgu** [calcom/cal.com#3170]
### Issue Summary

When opening a link to a Cal event type that already has a specific `date` selected, the view does not jump to the actual date to schedule the meeting but instead shows the current month with no bookable dates left.

### Steps to Reproduce

1. Take your Cal link
2. Append `?date=2022-09-08%2B0200` to the link
3. Open page and see that the current month (currently: June) is visible in the calendar screen

Intended behavior: The calender view jumps to the month of the "pre-selected" date + showing available times of that day on the sidebar

![image](https://user-images.githubusercontent.com/4404335/176037070-f46bb24a-5a40-4dea-af83-c79f851b60ef.png)

**Comment by milospuac** [comment]
Hi there. This should be fixed now. Can you confirm?

**Comment by MuriloAmarals** [comment]
Hey @milospuac , I did a git pull in my branch and bug appeared again.

**Comment by jjromary** [comment]
Hi, @manuelgu. Apparently I followed the steps you provided correctly and this error did not occur for me.

https://www.loom.com/share/3c64f57ba0094958be48e71498969a22

**Comment by manuelgu** [comment]
I am getting a new error now when trying to reproduce it 
![image](https://user-images.githubusercontent.com/4404335/176971334-bafe4d45-50c0-4809-943e-e5431a91807d.png)

It seems that the URL structure has changed entirely -- at least do I not recognize `https://cal.com/:username/30min?month=2022-09&date=2022-09-08`. Using that pattern correctly displays the selected month/date.

**Comment by agustif** [comment]
We recently split date to two params (date and month), so it's one for the month selector and other for the date selector @manuelgu. This allows us to fix the bug and others and so you can switch months and have a different selected date. I think the described issue has been resolved?

https://cal.com/ag/quick-chat?date=2022-07-08&month=2023-02

**Comment by manuelgu** [comment]
Yes, sounds like it! Thank you.
