### ISSUE TITLE
500 error on links that clash with locale

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3175]
Any random cal link with `locale` as event type name causes this error.
e.g. https://cal.com/solve/it

Internal Twist Thread:  https://twist.com/a/195135/ch/554218/t/3579118/

This is actually a bug in Next.js https://github.com/vercel/next.js/issues/33739(which is closed). The other duplicate which is still open is https://github.com/vercel/next.js/issues/21714

If someone has this issue, suggestion would be to rename the link for now.

**Comment by PeerRich** [comment]
has this been fixed?

**Comment by PeerRich** [comment]
nope, still happening: https://cal.com/peer/de

**Comment by PeerRich** [comment]
would it be hard to make this work?

**Comment by PeerRich** [comment]
i looked into the data and there are quite a few with less than 3 characters so we should not just make a min. char count

**Comment by hariombalhara** [comment]
@PeerRich Making it work is difficult(as far as I remember debugging it). Can be done in long term.
Maybe we can maintain a whitelist of all locales?

**Comment by PeerRich** [comment]
> Maybe we can maintain a whitelist of all locales?

lets do that

**Comment by hariombalhara** [comment]
It would be a two step thing
- Run a Query and figure out what users would loose their username. Maybe doesn't matter that much because there links might be broken any way, but good to have a list and inform them. A plan for self-hosting users as well.
- Just reserve the list I guess.
