### ISSUE TITLE
timeslot multiple times occupied

### ISSUE THREAD

**Issue by peseotni** [calcom/cal.com#3190]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

different clients have reserved the same timeslot.

### Steps to Reproduce

1. fresh installation version 1.6.3
2. setup the event type and assign availability
3. different clients were able to reserve the same timeslot

![same_timeslot](https://user-images.githubusercontent.com/22613392/176374650-29b26e1b-e40e-4383-9b06-3e6f183f4ebd.jpg)

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. What is the calendar that you integrated? Are you on our hosted version? If yes, what is your username?

**Comment by peseotni** [comment]
It is self-hosted and has no calendar integration

**Comment by gracebir** [comment]
@peseotni , I can't see this issue on my hand, maybe you are using an hold version

**Comment by Geczy** [comment]
i've got this issue as well

**Comment by Geczy** [comment]
the timeslot is just never removed from the booking page when someone books it

**Comment by Geczy** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/1036968/178343600-153c6373-625b-499f-9dde-6762cb567051.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/1036968/178343624-cb4fb543-aca6-46d8-a906-1462531486ac.png">

**Comment by PeerRich** [comment]
> i found the issue here:
> 
> ```js
>       // if ROUND_ROBIN - slots stay available on some() - if normal / COLLECTIVE - slots only stay available on every()
>       const filterStrategy =
>         !eventType.schedulingType || eventType.schedulingType === SchedulingType.COLLECTIVE
>           ? ("every" as const)
>           : ("some" as const);
> ```
> 
> i am doing round robin events, but the user should not show multiple events if they already have an event for this scheduled. so i think there needs to be an extra filter of the current logged in user's availabilities ?
> 
> if i change `some` to `every` it correctly filters

@emrysal can you test this?

**Comment by peseotni** [comment]
The client doesn't have different team members, it is just her.
I just updated it to the latest version 1.8.4, and again this happend:

![297584651_579880060333889_8581486758287397767_n](https://user-images.githubusercontent.com/22613392/183043903-67d49e69-a683-432e-ac39-da3e51813f45.jpg)

I have not connected her self-hosted instance to any calendar (google or outlook), is that maybe the reason why people can book the same timeslot multiple times?

**Comment by PeerRich** [comment]
pretty sure this has been fixed
