### ISSUE TITLE
missing string “someone_requested_an_event” in emails for bookings that require confirmation

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3191]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/8019099/176391104-e8689cf6-bcd6-448e-9e70-d58f1ea235a1.png">

**Comment by gracebir** [comment]
I am going to work on this

**Comment by matheusmuniz03** [comment]
Hey @PeerRich can you give me details of where this page?

**Comment by PeerRich** [comment]
> Hey @PeerRich can you give me details of where is this page?

it's in the email thats being sent asking to confirm the meeting

**Comment by matheusmuniz03** [comment]
@PeerRich that's it? Here on my localhost it seems right.

loom video: https://www.loom.com/share/88976182499d45feb2c03ce0acd6136d

**Comment by PeerRich** [comment]
interesting. maybe there was just a hickup

**Comment by PeerRich** [comment]
seems to be fixed
