### ISSUE TITLE
When free@example.com, requested a reschedule, this email was sent to him.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3203]
- The email doesn‘t convey that the reschedule as been requested. Instead it says Rescheduled
- Similarly Email Content Heading says that “Event has been scheduled“. It should convey that we have requested the scheduler to rebook and cancelled your booked meeting.

![image](https://user-images.githubusercontent.com/1780212/176610261-4bc1cdd6-aadd-46c1-82dc-9947da013d12.png)

**Comment by alannnc** [comment]
@hariombalhara There was indeed an error while selecting required email template when rescheduling. A PR has been made 
https://github.com/calcom/cal.com/pull/3227
