### ISSUE TITLE
When there is something wrong with calendar we don’t show which calendar it is.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3204]
![image](https://user-images.githubusercontent.com/1780212/176610792-363af763-f0c1-4484-a04f-93cc867b24cf.png)

**Comment by hariombalhara** [comment]
@jjromary The error that you see is `calendar_error` as shown in screenshot. You can try to get that condition to true
<img width="1041" alt="Screenshot 2022-07-01 at 11 10 42 AM" src="https://user-images.githubusercontent.com/1780212/176831029-d16bb1dc-05f7-47b3-9dcf-344842db025a.png">

**Comment by AaronPresley** [comment]
@PeerRich I believe this can be closed, as @leog seems to have addressed this as part of [this PR](https://github.com/calcom/cal.com/pull/4645).

I've included a screenshot of what it looks like now on Production (which matches @leog's screenshots from that PR):

| Desktop | Mobile |
| ----- | ----- |
| ![Screenshot 2023-02-01 at 12-54-08 Installed Apps Cal com](https://user-images.githubusercontent.com/155617/216161191-7bb06726-ca39-461c-aa53-86033d632c58.png) | ![Screenshot 2023-02-01 at 12-54-52 Installed Apps Cal com](https://user-images.githubusercontent.com/155617/216161260-145e31bc-1c0b-4e22-a565-3f9ade1de498.png) |

Please let me know if any other work is needed here 👍

**Comment by PeerRich** [comment]
correct
