### ISSUE TITLE
Calls exodia.io/api/trending?page=1

### ISSUE THREAD

**Issue by TheCapsLock** [calcom/cal.com#3207]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cal.com calls exodia.io and should not. OR it should be possible to disable it

In other words : we expect cal.com to be a schedule app not a NFT / crypto thing.

### Steps to Reproduce

1. Open network inspector
2. Edit an event type
3. 🍿

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by TheCapsLock** [comment]
Root cause is here https://github.com/calcom/cal.com/blob/d732a984c2cc1877fb683f9a21877e08134ddcdf/apps/web/pages/event-types/%5Btype%5D.tsx#L360

Introduced by https://github.com/calcom/cal.com/pull/1603

**Comment by agustif** [comment]
Hello @TheCapsLock, First of all, thank you for bringing this up.

I'll try to explain a bit, as I have some context of when I looked into upgrading our web3 code .
this code is part of our web3/metamask app, sadly this app was shipped just before we moved the codebase to the new monorepo (meaning code is actually really interwinded with whole webapp, and not separated from it), and also before the new -app store- for time, which makes each new app have it's own code separated/not executed if possible if the app is not enabled in the instance. (Which in cal.com is, as a user you can enable it or not for yourself)

Anyways, we had planned on moving the web3 app to rainbowkit/wagmi, and a user even approached me recently about working on that in our Slack, but as it stands it currently has some inter-winded code.

As an easy -hotfix- we could just make the call conditional on having web3/metamask enabled or not in your cal.com profile settings. In the future we will discard this altogether probably and implement it differently.

**Comment by TheCapsLock** [comment]
Hi @agustif Thanks a lot for your feedback which gives more details about the situation. I'm very excited about the roadmap to handle this issue - thank you

**Comment by PeerRich** [comment]
oh i was unaware it sends a request. yeah lets conditionally render it @agustif

**Comment by PeerRich** [comment]
@TheCapsLock the entire call was removed
