### ISSUE TITLE
Self-hosted instance is failing with `undefined` in the URL

### ISSUE THREAD

**Issue by hhimanshu** [calcom/cal.com#3211]
### Issue Summary

I self-installed Calendso, using Railway, one-click deployment. I performed all the steps as needed and got my app working.

However, 
1. When I go to the settings page, I see `undefined` before my userName.
2. Also, when I add Google Calendar app, it fails with `Error 400: invalid_request` request and following error
```
If you’re the app developer, make sure that these request details comply with Google policies.
 - redirect_uri: https://undefined/api/integrations/googlecalendar/callback
```

I have created a demo video to showcase the same issue

https://user-images.githubusercontent.com/6589036/176932702-29ca1683-3a9b-4865-9838-e81556ce342c.mp4

As I debugged the code, I thought I had to add `WEBAPP_URL` in the environment variable, but even adding that did not fix the issue.

I do not have a specific `.env` file, but I have set all environment variables in Railway project > Variables settings.

### Technical details

I am using the Railway one-click button to deploy

**Comment by agustif** [comment]
Hello @hhimanshu can you try naming the environment setting `NEXT_PUBLIC_WEBAPP_URL` instead?

This is how we read it, guess it might have thrown you off with the naming on the error logs
`export const WEBAPP_URL = process.env.NEXT_PUBLIC_WEBAPP_URL || `https://${process.env.VERCEL_URL}`;
`

**Comment by agustif** [comment]
Also was just thinking if there's. a VERCEL_URL equivalent for railway/heroku.

In case of railway `RAILWAY_STATIC_URL` https://docs.railway.app/develop/variables

@zomars do you think it would be worth it to add those as fallbacks if no `NEXT_PUBLIC_WEBAPP_URL` or `VERCEL_URL` are found?


```diff
- export const WEBAPP_URL = process.env.NEXT_PUBLIC_WEBAPP_URL || `https://${process.env.VERCEL_URL}`;
export const WEBAPP_URL = process.env.NEXT_PUBLIC_WEBAPP_URL || `https://${process.env.VERCEL_URL}` || `https://${RAILWAY_STATIC_URL}`

Heroku doesn't seem to like exposing that in a default env https://devcenter.heroku.com/articles/dyno-metadata

**Comment by hhimanshu** [comment]
Thank you, @agustif , I can confirm that when I added my railway provided domain with `NEXT_PUBLIC_WEBAPP_URL` as key, the error was gone.

**Comment by agustif** [comment]
Closing as solved
