### ISSUE TITLE
Placeholder variables in email text preview line

### ISSUE THREAD

**Issue by karstenwinter** [calcom/cal.com#3213]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Went to cal.com/{xy}
2. Clicked on 15 min
3. entered a date, submitted
4. opened the confirmation mail
5. the mail has a preview line (not present in email body) that contains `{{variables}}`
![image](https://user-images.githubusercontent.com/4852618/176966208-3403e9c7-12a0-4271-bdb6-f87377665a45.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser: Chrome 103.0.5060.66 (Offizieller Build) (64-Bit)
- Mail Program: Windows Mail 16005.14326.20970.0

**Comment by karstenwinter** [comment]
same for cancelled, a technical_id is shown in the preview line

![image](https://user-images.githubusercontent.com/4852618/176967076-e407ade1-bb3e-4b5c-aea5-77b87a720773.png)

**Comment by noobyogi0010** [comment]
Can I work on this issue?

**Comment by matheusmuniz03** [comment]
Guys, I'm using Ethereal to receive emails, and here it`s:

![Captura de tela de 2022-07-05 10-12-22](https://user-images.githubusercontent.com/87545749/177335861-e411d6ff-338f-4510-9011-940dbe6a2c9e.png)

**Comment by PeerRich** [comment]
i think this has been fixed a long time ago
