### ISSUE TITLE
Enable DB branching for each PR preview

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#3216]
Blocked by #3212 #3215

We're looking into using `neon.tech` so we can create branches from our staging DB so we can test out migrations without disrupting the rest of the contributors.

Here's a [comprehensive example](https://github.com/kelvich/branching_demo_ts/blob/main/.github/workflows/test_migrations.yaml) on how can we achieve that with GitHub actions.

**Comment by PeerRich** [comment]
we tried and failed, should we try again?
