### ISSUE TITLE
"someone_requested_an_event" in "An event is waiting for your approval" emails

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3225]
### Is your proposal related to a problem?
<img width="465" alt="image" src="https://user-images.githubusercontent.com/8019099/177204273-2e6d696a-819f-4d8f-abad-3e5736c7bb57.png">

# reproduce

- create a booking that requires confirmation
<img width="532" alt="image" src="https://user-images.githubusercontent.com/8019099/177204328-bcd8b22e-608f-4cfb-8b61-0eb47012db40.png">

- book yourself

- check inbox

**Comment by fool1280** [comment]
Hi Peer, I'm new to open source, and first time working with a big codebase, but I'd love to explore this issue. Please let me know! Thank you!
