### ISSUE TITLE
Hard crash when a user has an availability schedule with no days available

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#3237]
Example:
![image](https://user-images.githubusercontent.com/1046695/177369769-d421ad91-50cc-4544-9b24-d47088fd1458.png)

Causes getSchedule to 500.

**Comment by jjromary** [comment]
HI @emrysal. Can you let me know the steps you did so I can try to reproduce the same bug? I am not able to reproduce it.

![image](https://user-images.githubusercontent.com/37199044/177415129-342ff995-4697-450c-9e59-c00cc8fb202c.png)

**Comment by PeerRich** [comment]
seems to be working
