### ISSUE TITLE
Avoid duplicating any video credential

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#3246]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Previously there was a bug on our app store, that led some users install multiple instances of any app, this created multiple records for any video app integration. We should make sure any time a video credential its saved/installed we delete any previous or update the current entry of that credential type.

### Steps to Reproduce

1. Try to install any zoom/ google meet app twice and it should leave you with 2 rows of the app.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by matheusmuniz03** [comment]
Hey @alannnc could you check out this [loom video](https://www.loom.com/share/2b1b78d2bb20478aaa61ade0ef9c8e17)? Apparently this bug doesn't happen anymore.

**Comment by alannnc** [comment]
@matheusmuniz03 Thanks for reaching out, yeah I created this issue to remember myself to add some code validations if any frontend error happens our backend should take care of this.
You can take a look on ->
https://github.com/calcom/cal.com/blob/main/packages/app-store/office365video/api/callback.ts#L73-L93
That’s how I handled it on office365.
This should be an easy fix, if you still want to collaborate with us.

**Comment by gracebir** [comment]
> @matheusmuniz03 Thanks for reaching out, yeah I created this issue to remember myself to add some code validations if any frontend error happens our backend should take care of this. You can take a look on -> https://github.com/calcom/cal.com/blob/main/packages/app-store/office365video/api/callback.ts#L73-L93 That’s how I handled it on office365. This should be an easy fix, if you still want to collaborate with us.

@alannnc , I just want to confirm, are we going to reproduce the same thing for zoom or google meet video?
