### ISSUE TITLE
Wipe Today from WipeMyCal app not working

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3248]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

'Wipe Today' from the WipeMyCal app is not working for me

Getting this error: 
<img width="383" alt="Screenshot 2022-07-06 at 14 10 53" src="https://user-images.githubusercontent.com/30310907/177615996-753b1ddb-4c19-4b31-94b0-4baae18e84f5.png">

### Steps to Reproduce

1. Install WipeMyCal 
2. Go to bookings
3. Click 'Wipe Today' 
4. Click 'Confirm' 
5. Button gets disabled but nothing else happens until error message shows up

**Comment by matheusmuniz03** [comment]
hey @CarinaWolli I'm testing the bug here on my localhost and apparently it's not happening anymore. Can you check this?

loom video[https://www.loom.com/share/696a010f57d74ac6a8cfb3f6c2de71f6]

**Comment by noobyogi0010** [comment]
Hey @CarinaWolli 
If this is still an issue, I would love to work on this.
Thanks

**Comment by CarinaWolli** [comment]
I still get the error in production. However, I just tested it locally and it worked as expected. I think @alannnc implemented this feature, maybe he can help!

**Comment by alannnc** [comment]
I will definitely take a look of it on production and inform on this thread what I found.

**Comment by noobyogi0010** [comment]
Hey, @alannnc 
Were you able to find something?
