### ISSUE TITLE
[CAL-753] Meeting titles with a backslash send a confirmation email with &#x2F; instead

### ISSUE THREAD

**Issue by galligan** [calcom/cal.com#3250]
### Issue Summary

I have a meeting type with `/` in its title and when I received an email confirmation for a booked meeting, it showed `&#x2F;` instead.

<img width="548" alt="CleanShot 2022-07-06 at 14 55 12@2x" src="https://user-images.githubusercontent.com/25037981/177622590-be790a3c-0f5a-471c-9fbb-28ed436e45d9.png">

### Steps to Reproduce

1. Change meeting title to include a `/`
2. A meeting is scheduled
3. Receive meeting confirmation that shows `&#x2F;` in subject instead of `/`

<sub>[CAL-753](https://linear.app/calcom/issue/CAL-753/meeting-titles-with-a-backslash-send-a-confirmation-email-with-andx2f)</sub>

**Comment by PeerRich** [comment]
looking at &amp it seems like other chars are not being shown either

**Comment by Priyankcoder** [comment]
Hi @PeerRich, I am new to the codebase. Can I try to fix this? Further follow-ups would be much appreciated.

**Comment by jjromary** [comment]
Hi, @galligan. I produced the steps and didn't get the same error as you did. The title of my email remained with the text displaying the `/` and not the equivalent hexadecimal code `&#x2f;` 

My project is hosted locally and nodemailer was configured with [Ethereal](https://ethereal.email/)

![barra](https://user-images.githubusercontent.com/37199044/178396182-88f386c4-c312-4e4f-a578-8a0d0fac98df.jpg)

**Comment by galligan** [comment]
@jjromary not sure if it might have anything to do with the mailer…but in my case I'm using cal.com directly cc @PeerRich

**Comment by PeerRich** [comment]
@G3root wanna look into this?
