### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by 89itworld** [calcom/cal.com#3266]
Hello contributors,

I am facing the following error, can you please help me out with this issue.

I am attaching the screenshot.

![Screen Shot 2022-07-08 at 6 46 59 PM](https://user-images.githubusercontent.com/3927785/178004911-906187f7-81a0-4a9c-adf6-b08c042f2cf4.png)

**Comment by PeerRich** [comment]
can you give more context of your environment and what steps you have taken?

**Comment by 89itworld** [comment]
> can you give more context of your environment and what steps you have taken?

Hi @PeerRich ,

Thanks for your fast response.
I cloned the project, did necessary changes in env files, run yarn, and then yarn dev.
----------------------------
error - Error: Cannot find module '/Applications/XAMPP/xamppfiles/htdocs/projectname/node_modules/@hookform/resolvers/zod/dist/zod'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.mod._resolveFilename (/Applications/XAMPP/xamppfiles/htdocs/projectname/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.@hookform/resolvers/zod/dist/zod (/Applications/XAMPP/xamppfiles/htdocs/projectname/.next/server/pages/event-types.js:944:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/Applications/XAMPP/xamppfiles/projectname/node_modules/@hookform/resolvers/package.json',
  page: '/event-types'
}
18:42:50.920 timeZoneName DEBUG [error] server side logged this: Error: Cannot find module '/Applications/XAMPP/xamppfiles/htdocs/projectname/node_modules/@hookform/resolvers/zod/dist/zod' 
18:42:50.921 timeZoneName INFO  [error] return props,  
{
  statusCode: 500,
  hasGetInitialPropsRun: true
}

**Comment by PeerRich** [comment]
what node version do you run on?

node -v

**Comment by 89itworld** [comment]
> what node version do you run on?
> 
> node -v

v14.18.0

**Comment by zomars** [comment]
Try using `v16` and run:
- yarn clean
- yarn
- yarn build
- yarn start

**Comment by 89itworld** [comment]
Ok fine.

**Comment by 89itworld** [comment]
> * yarn clean

error Command "clean" not found.

**Comment by 89itworld** [comment]
I tried almost everything even with v16, but facing the same problem.

imeZoneName DEBUG [error] server side logged this: Error: Cannot find module '/Applications/XAMPP/xamppfiles/htdocs/projectname/node_modules/@hookform/resolvers/zod/dist/zod'
18:42:50.921 timeZoneName INFO [error] return props,

**Comment by zomars** [comment]
This seems like an issue with your specific deployment server. I'm afraid there's not much we can do without a proper reproduction. Will close this temporarily until a proper reproduction is provided.

**Comment by 89itworld** [comment]
> This seems like an issue with your specific deployment server. I'm afraid there's not much we can do without a proper reproduction. Will close this temporarily until a proper reproduction is provided.

Wow, Now I can add you in my git repo, which I just cloned from cal and did changes in env only as per instructed by cal, I sent you screen shot, the error I am facing, Even I tried on another machine as well and facing the same issue.

I followed the steps:

1. I cloned the repo from cal.
2. Did the changes in env.
3. run yarn
4. yarn dev
5. and facing this issue
Please let me know if I am doing something wrong.

Thanks in advance.

**Comment by zomars** [comment]
I really don't know what can be happening on your machine. Here some things you can try:

- look up that specific error
- check that the file exists in node_modules
- Remove node_modules and install again
- Check if it is a windows/mac/linux specific or known error

If you do find a solution for your case please let us know so we can improve the instructions 🙏
