### ISSUE TITLE
Error Code: 404. Cal Link seems to be wrong on jobs page

### ISSUE THREAD

**Issue by DigitalGreyHat** [calcom/cal.com#3273]
### Issue Summary

There is a problem loading the cal.com embed on cal.com/jobs/.... Initially, it loads, then displays cal.com's "normal" 404 page for a split second. Following that, it displays just a simple text: Error Code: 404. Cal Link seems to be wrong.

### Steps to Reproduce

1. Go to [https://cal.com/jobs/senior-full-stack-engineer](https://cal.com/jobs/senior-full-stack-engineer)
2. Scroll down to the bottom

I expected that the cal.com embed would load without errors; instead, I received a 404 error.

### Technical details

- Browser versions: Firefox, Chrome, Edge
- Screenshot:
![image](https://user-images.githubusercontent.com/90456651/178120071-e6451764-992c-459e-9bdd-d5d946215757.png)

**Comment by PeerRich** [comment]
ah whoops, changed the link

**Comment by PeerRich** [comment]
fixed
