### ISSUE TITLE
BUG Availability and Prefetch not working on M365

### ISSUE THREAD

**Issue by wemakefuture** [calcom/cal.com#3310]
### Issue Summary

Microsoft prefetch and calendar checkup does not work. 

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/28114725/178162754-a80f0bac-f5a6-46ec-9f9e-becc3dae13b6.png">

I am not available at 10. I checked it with 2 different cal.com accounts. With gsuite it works. With MS it does not. 

### Steps to Reproduce

Availability prefetch and check does not work on MS.

**Comment by PeerRich** [comment]
hey @emrysal or @alishaz-polymath would you be down to test this?

**Comment by alishaz-polymath** [comment]
I can have a crack at it this week @PeerRich

**Comment by wemakefuture** [comment]
@alishaz-polymath feel free to chat with me if you need help to reproduce!

**Comment by wemakefuture** [comment]
@alishaz-polymath @PeerRich  any updates here - we can barely use cal.com that way in our MS infrastructure.

**Comment by alishaz-polymath** [comment]
Hey @wemakefuture 
I noticed through impersonation that this toggle isn't activated.
![image](https://user-images.githubusercontent.com/52925846/178949269-9f12fd85-bd75-4246-b299-18b2b8639a9f.png)

can you please enable it and then test if that helps at all?

**Comment by wemakefuture** [comment]
@alishaz-polymath yeah sorry facepalm... anyway default active would be great and a section in your docs. 

I wasted hours and created a bug / wasted your time by missing documentation. 

Sorry again! Please close the Bug.

**Comment by PeerRich** [comment]
hey @wemakefuture no worries! sorry for the struggles as well, we'll ship a feature where it takes the primary as default

**Comment by rennoco** [comment]
Actually, this issue persists for me even AFTER enabling the calendar.

It shows full availability, even on slots in the day when I am definitely busy or am out of office entirely:

![image](https://user-images.githubusercontent.com/107069911/179824342-ffb897ba-52c0-4b6b-90e0-be3fc2992c14.png)

**Comment by mathiasjakob** [comment]
For me, the problem still exists as well. 
Self hosts environment and I just updated to v1.8.1. I also double checked that the correct calendar was selected in the event.

**Comment by alishaz-polymath** [comment]
Hi @rennoco and @mathiasjakob 
Im reopening this since you both seem to have an issue. @joeauyeung can you please take a look at this 🙏
