### ISSUE TITLE
Disallow search engine indexing of hidden event types

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3311]
### Discussed in https://github.com/calcom/cal.com/discussions/3285

<div type='discussions-op-text'>

<sup>Originally posted by **GlitchWitch** July  5, 2022</sup>
### Is your proposal related to a problem?

When creating a hidden event type, there is the chance that if the link is shared that it will be crawled and indexed by search engines.

### Describe the solution you'd like

When marking an event type as hidden, we should add `<meta name="robots" content="noindex">` to the page html header to [prevent indexing](https://developers.google.com/search/docs/advanced/crawling/block-indexing).

### Describe alternatives you've considered

Another possible solution is to add a checkbox to allow the user to decide if the event type can be indexed or not, however I think just linking this to the hidden parameter is good enough.

### Additional context

One of my hidden event types currently shows up in search engines as I share it on a public post with a specific CTA and purpose. However I have deliberately chosen to make this event type hidden and do not want it indexed. </div>

**Comment by gracebir** [comment]
I am going to take a look on

**Comment by PeerRich** [comment]
> I am going to take a look on

thank you!

**Comment by PeerRich** [comment]
cc @glitchwitch I reopened it here

**Comment by gracebir** [comment]
@PeerRich , is this the expected the behavior?
![INDEXISSUE](https://user-images.githubusercontent.com/46535846/178249417-1d5657ca-e2b2-4a5d-968c-c645e49ab695.png)

**Comment by MuriloAmarals** [comment]
Hey @gracebir @PeerRich i'm already resolved!

**Comment by gracebir** [comment]
> Hey @gracebir @PeerRich i've already resolved! Even today gitstart will send the PR of the resolution.

sure

**Comment by PeerRich** [comment]
n

> Hey @gracebir @PeerRich i've already resolved! Even today gitstart will send the PR of the resolution.

awesome, feel free to link the PR here
