### ISSUE TITLE
Whereby room is linked to a single person in round robin event

### ISSUE THREAD

**Issue by martincollignon** [calcom/cal.com#3316]
### Is your proposal related to a problem?

For a round robin event, I'm frustrated as I can only input a single Whereby room as location. 

### Describe the solution you'd like

I'd like the Whereby room to be linked to the participants in the team, ie if I book a time with Peter, I get linked to Peter's Whereby room.

### Describe alternatives you've considered

I haven't considered alternatives

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
oh i see. yea we havent thought about this yet, how we can have individual rooms for each participant of a team. 

this is not whereby related but any location link in general

**Comment by martincollignon** [comment]
It's also problematic as it doesn't allow for concurrent meetings.

**Comment by PeerRich** [comment]
yeah that is the downside of the room link-based video tools. 

we could extend the whereby app and give it a settings: to introduce a new field 
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/8019099/178304498-03b4acc5-aadc-4a4d-b0d9-d47fe6619cb6.png">

**Comment by martincollignon** [comment]
That sounds clever. And there could be a team room field which could also be used as a fallback, should a team member not have a personal room setup.

**Comment by PeerRich** [comment]
that doesnt sound so trivial 🤔

**Comment by Jaibles** [comment]
Designs for this feature are [here](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13315%3A78702)
