### ISSUE TITLE
Slack app installation not working

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3327]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to install the Slack app it says 'Something went wrong when authorizing this app':

<img width="1114" alt="Screenshot 2022-07-11 at 18 25 23" src="https://user-images.githubusercontent.com/30310907/178368952-ffc951d0-ac89-4aef-8898-aa3f6b660d43.png">

### Steps to Reproduce

1. Install Slack App
2. You will be redirected to slack.com/oauth/.... which shows an error

**Comment by sean-brydon** [comment]
This issue in itself should be fixed as our clientID got mixed up within the the DB (not sure how) 

Looking at further issues with the Oauth callback
