### ISSUE TITLE
Reason for rescheduling should not be disabled

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#3332]
### Issue Summary

When rescheduling, all previously filled fields are in read-only mode. Also there's a new field "Reason to reschedule" this field is also on read-only mode and it should not be.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/3504472/178400733-8b1d27ec-b77f-4e40-ad6d-f435e4179d2d.png">

### Steps to Reproduce

1. As attendee, book an opt-in booking
1. As host, accept the booking
1. As attendee, click the link for rescheduling on the email
1. Try to fill the "Reason to reschedule" field

**Comment by gracebir** [comment]
@zomars ,  "Reason to reschedule" field is not disable on my hand ( I mean locally)

**Comment by zomars** [comment]
Agree @mocherfaoui either we enable it for both or hide it for non-owners to prevent confusion. I'm tagging @Jaibles to hear his feedback.

**Comment by ayoubphy** [comment]
Have you guys settled on a decision about this ? I would like to work on it and make it my first contribution to this project.

**Comment by Jaibles** [comment]
@zomars I agree that both parties should be able to provide a reason to reschedule.

**Comment by MatheusBeniniF** [comment]
@zomars @Jaibles, this issue has already fixed, right?
![image](https://user-images.githubusercontent.com/88898100/197790156-506e2e3a-e929-4b9d-b85d-35d655422b11.png)

**Comment by Jaibles** [comment]
@MatheusBeniniF yes.
