### ISSUE TITLE
Display the times I’m selecting in the other users Time Zone as well

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3333]
### Is your proposal related to a problem?

Since Cal is a global product, it would be nice to see what timezone the other party is in to help me determine how early or late I am booking a time with them if I’m trying to be polite. I realize there’s the argument of “everyone’s an adult,” but I’m a firm believer we need to help users protect themselves.. From themselves.

### Describe the solution you'd like

Proposed Solution: Display the other time in their timezone side by side. Have a toggle to turn this on or off as needed. 

Proposed Solution: It would be good to see the confirmed booking time not just in my time zone, but in their timezone afterwards as well.

Example:
When Shiraz: (see attached image)
When Peer:
June 23
10:30 PM - 11:00 PM (Where
<img width="685" alt="CleanShot 2022-07-11 at 17 17 22@2x" src="https://user-images.githubusercontent.com/16177678/178401292-4b93fd5c-fb85-4cce-b867-3a4b54cdd3ba.png">
ver he is in the world)

### Describe alternatives you've considered

(Write your answer here.)

Slack displays the local time of the user you are messaging: (see attached image)
<img width="479" alt="CleanShot 2022-07-11 at 17 17 35@2x" src="https://user-images.githubusercontent.com/16177678/178401256-dcc41b15-10a5-4c13-9c02-baeb4e70e42b.png">

(Write your answer here.)

**Comment by blam404** [comment]
@PeerRich I did some poking around in the code yesterday and I think I might be able to do this.

**Comment by PeerRich** [comment]
do we need designs for this @Jaibles ?

**Comment by Jaibles** [comment]
Yes definitely good to design this one. Need to ensure we don't create any sense of confusion and that it can handle 4 & 5 people across multiple timezones etc.

**Comment by codewithmitesh** [comment]
hey, @Jaibles Instead of showing the targeted person's time zone and location, we could simply show how much time ahead or behind their time zone is from ours. This would be more user-friendly for most people, who are not familiar with different time zones. GitHub does this, and it seems to work well. 


<img src="https://i.ibb.co/3ssmnYK/Screenshot-from-2023-06-07-22-37-47.png" alt="Screenshot-from-2023-06-07-22-37-47" border="0">

**Comment by Jaibles** [comment]
I like this but I would like to note that it's not necessarily "Instead of showing the targeted person's time zone and location.." it's actually in addition to.

**Comment by shirazdole** [comment]
I believe the implementation of this would be a great detail in our booking experience and that scheduling is won or lost in the details, but it seems quite difficult to implement so I'm happy to close this for another time @Jaibles @PeerRich

**Comment by ZainGulbaz** [comment]
Hi @PeerRich, Should I work on it?

**Comment by ZainGulbaz** [comment]
Hi @shirazdole, what if we show the difference of the host and the guest time zone while booking the appointment like this:
![image](https://github.com/calcom/cal.com/assets/90947550/9a3167ce-a4d3-4bc3-82d4-379e1ed68409)
![image](https://github.com/calcom/cal.com/assets/90947550/6f449ce7-c0fb-40b1-965a-cbf4a3ff317a)

**Comment by zaid-ahmad** [comment]
Hi, just to clarify do we need to implement the design, implement the feature or do both?
