### ISSUE TITLE
Hovering Text over Button

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3335]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you hover over certain buttons in Cal.com's event page, there is no text that shows up as opposed to other buttons that are hovered over. Specifically on the Availabilities page by the day. Need to add some text over these two buttons:
<img width="671" alt="CleanShot 2022-07-11 at 17 24 45@2x" src="https://user-images.githubusercontent.com/16177678/178402019-e51c8d2e-29f2-447c-aff8-c345adf51b7a.png">

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by gracebir** [comment]
I will take a look on

**Comment by noobyogi0010** [comment]
Hey @shirazdole 
Can I work on this issue if no one else has taken it up?

**Comment by shirazdole** [comment]
> Hey @shirazdole Can I work on this issue if no one else has taken it up?

For sure you can! Thank you 🙏

**Comment by gracebir** [comment]
> Hey @shirazdole Can I work on this issue if no one else has taken it up?

@noobyogi0010 , this isssue is solved and the code will be pushed

**Comment by noobyogi0010** [comment]
Hey @gracebir 
Were you able to push the code to resolve this issue?
