### ISSUE TITLE
Avatar on New Event Type

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3336]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When selecting a new event type, if you have an individual plan as well as a team plan. The Team Plan's Avatar shows, but the individual users avatar does not show. For consistency, the users avatar should show as well.
<img width="437" alt="CleanShot 2022-07-11 at 17 26 38@2x" src="https://user-images.githubusercontent.com/16177678/178402252-fdd03b2d-bd6b-4c60-b7a2-3e13eeb21101.png">

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
yeah simple fix worth adding

**Comment by PeerRich** [comment]
> Hey @PeerRich I would like to work on this issue if no one else has already taken it up. Thanks!

sure go ahead!

**Comment by noobyogi0010** [comment]
Hey @PeerRich 
Can you let me know what `user avatar` needs to be used here?

**Comment by azmy60** [comment]
Any updates?

**Comment by noobyogi0010** [comment]
Hey @azmy60 
I am waiting on @PeerRich to let me know of the user avatar to be used for this fix.
thanks!

**Comment by PeerRich** [comment]
<img width="158" alt="image" src="https://user-images.githubusercontent.com/8019099/179488295-c6a17b78-bc9d-4cef-bf5c-d6a97aad59b1.png">
just use the one the shell gives you
