### ISSUE TITLE
No days available to schedule a meeting

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#3340]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When I click "preview" to schedule a meeting time, there is no available day

### Steps to Reproduce

1. Create a new event
2. Click on preview

All options are off:
![Screenshot from 2022-07-12 09-31-26](https://user-images.githubusercontent.com/87545086/178491336-9cbd0354-102b-4464-ad58-f38f9b81cdda.png)

**Comment by PeerRich** [comment]
this is on localhost right?

@emrysal you mentioned

**Comment by Toledodev** [comment]
Yes

**Comment by PeerRich** [comment]
hey, can you try the latest version again?
