### ISSUE TITLE
Formatting of description missing (bold, italic, new line)

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#3348]
### Is your proposal related to a problem?

right now I cannot provide structured information to register a calendar entry. Everything goes into one long line with arbitrary line breaks.

### Describe the solution you'd like

on event types, there is a description field.
Here it is missing to be able to use common formatting:

- bold
- italic
- underlined

and the most painfull issue

- new line is missing and cannot be entered

**Comment by PeerRich** [comment]
as simple as this: 

https://user-images.githubusercontent.com/8019099/178832437-751bf918-9cda-45d3-b758-ee7b429afda6.mov

**Comment by dpalic** [comment]
@PeerRich 
markdown style, perfect, would already solve many of my issues!

**Comment by PeerRich** [comment]
just added to our 1.9 roadmap

**Comment by om-ray** [comment]
@PeerRich There's a lightweight tool called [markitup!](https://markitup.jaysalvat.com/home/), if you think that looks good then I would love to work on adding it!

**Comment by PeerRich** [comment]
> @PeerRich do you think i could work on this?

of course, go ahead!

**Comment by om-ray** [comment]
@PeerRich Thanks! ill get on it asap!

**Comment by om-ray** [comment]
@zomars as long as I sanitize the input would it be ok if I use `dangerouslySetInnerHTML`? since Next renders `<b>Event description</b>` as plain text when that is the input, really the only way to apply MD formatting to it would be to change innerHTML

**Comment by zomars** [comment]
I'll give a proper review in a bit @om-ray 🙏🏽
