### ISSUE TITLE
Internal and External title & description needed

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#3349]
### Is your proposal related to a problem?

if using many different event types, it is not always clear what event type is for what.
So for internal use, I want to have long titles or subtitles, which get displayed on the overview page of all event types
Also I need a different description for internal use, which is invisible to clients.
E.g. in the description could be instructions for users/maintainers of the event type

Therefore the external description for clients is mostly the same with some minor changes.

### Describe the solution you'd like

so would like to have 

- a internal title or subtitle, invisible to client, but visible on event types overview list
- add an additional description field, Internal Description, which has the same capabilities of the Description field, except it is invisible to the client

see also  #3348 as it is related to the capabilities needed for Description field

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will look into feature requests next quarter including this one and prioritize accordingly. 

Best,

**Comment by PeerRich** [comment]
i wonder how we can do that without confusing people who don't need this. most people don't need internal/external info

**Comment by dpalic** [comment]
@PeerRich 
you are right, from UX perspective
With your feedback it would be great to have a checkbox 
"title and description for internal (team) use"
and if this is selected to provide the both requested input fields

**Comment by PeerRich** [comment]
I dont think this is something we'll be able to add in v.1.9 milestone, but if someone from the community has some ideas, happy to look at it

**Comment by TyceHerrman** [comment]
@PeerRich or @milospuac was this actually completed? I don't see anyway of having internal only title or description.
