### ISSUE TITLE
[CAL-91] For Multi-Location Event Type, required dependent "Additional Inputs"

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#3350]
### Is your proposal related to a problem?

Assume you can provide a client the choice if he want to be at our office, or at his office, or at video call, or meeting at a business restaurant

In all the cases you have different questions to ask.

* For Video call, no additional location question needed
* For on site meeting, the client needs the address details of our office branch
* For meeting at client location, the client needs to provide mandatory the location to visit
* For meeting at a business restaurant, the address is also mandatory. But the restaurant could be provided by us or by client
* 

### Describe the solution you'd like

in the first step it would be helpful if we could decide which Additional Inputs entry is depending to which selected location. So we could decide what to show in the case the the clients selection

Better would be the option, that we can somehow provide a link with a predefined address/location or the client can select and enter a predefined location. In both cases a geolocation lookup shall be done, to ensure there is no typo. (e.g. google geo coder api)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-91](https://linear.app/calcom/issue/CAL-91/for-multi-location-event-type-required-dependent-additional-inputs)</sub>

**Comment by milospuac** [comment]
Hey Darko, thanks for reaching out. Our engineering team will look into this request.

**Comment by Jaibles** [comment]
@hariombalhara sounds like this could be handled with conditional inputs in the form builder?

**Comment by hariombalhara** [comment]
This is easily solved with a radioInput type question. I have handled the location in this way now. 

radioInput is different from radio that it can have an input corresponding to every radio option.
