### ISSUE TITLE
MercadoPago integration

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#3352]
Payments by MercadoPago (Latin america mainly)
https://github.com/mercadopago/sdk-nodejs

**Comment by zomars** [comment]
I swear I had an issue about this but I couldn't find it. May be lost on Linear...

**Comment by PeerRich** [comment]
does it offer the "stripe connect" feature?

**Comment by zomars** [comment]
AFAIK there's no marketplace functionality with MercadoPago unfortunately. But neither with PayPal #1546

**Comment by zomars** [comment]
Adding references to current attempts #8620 #11246
