### ISSUE TITLE
zapier trigger: after booking AND the meeting is done

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3357]
https://twitter.com/flexbox_/status/1547139632684568583

**Comment by flexbox** [comment]
To give some context here is a scenario

```
As a user
I can send automated follow-up emails
So that I can automatically ask for feedback or send additional information
```

Thanks you!

**Comment by PeerRich** [comment]
@CarinaWolli do you think this is a higher priority than Zapier Templates?

**Comment by CarinaWolli** [comment]
> @CarinaWolli do you think this is a higher priority than Zapier Templates?

@PeerRich Yes, I think I would give this a higher priority than Zapier Templates
