### ISSUE TITLE
Dynamic variables for custom template (Workflows)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3378]
### Is your proposal related to a problem?

Currently, we only allow a simple text input for our the custom template in Workflows. We should also give the option to add dynamic variables, for example: 

- Organizer name
- Attendee name 
- Location 
- Date 
- etc. 

### Describe the solution you'd like

Similar to what we already have for dynamic event names:
<img width="797" alt="Screenshot 2022-07-14 at 21 38 37" src="https://user-images.githubusercontent.com/30310907/179129509-df64b699-ad9e-44c4-8171-3874cf7cd16d.png">

**Comment by dpalic** [comment]
having the very same requirement too

so my suggestion here would be to provide:
a variable name to the additional inputs in the event type
with the variable name we could use it as a text template

e.g. 
additional input:
label: Your preferred restaurant
variableName: locationRestaurantPreferredByClient  <== missing
type: longtext
hoverText: please provide your preferred restaurant for our business meeting   <== missing

Now I would like to reuse {locationRestaurantPreferredByClient} to provide it e.g. in Notifications, but mostly in the invitation title

any chance to get it in 1.9.0?
