### ISSUE TITLE
Self-hosted onboarding first admin wizard

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#3384]
<div type='discussions-op-text'>

<sup>Originally posted by **@zomars** July 14, 2022 in [Twist thread](https://twist.com/a/195135/ch/555266/t/3624478/)</sup> 

We should strive to improve self-hosted experience by including an onboarding for new installs. This is very common for PHP Symfony projects (cc @emrysal who reminded me of this) to have a “[Create your first user](https://docs.boltcms.io/5.0/manual/first-user)” screen when you’re on a new install:

<img src="https://user-images.githubusercontent.com/467258/179259019-0a273503-002b-45bd-9203-b928989cf8fa.png" width="400"/>

We already have the new onboarding design on console so it should be trivial to make a new screen for it.

</div>

<div type='discussions-op-text'>
> @PeerRich: this should live in the deployment wozard

@zomars: Agreed but also should live on webapp on a new install without users
</div>

**Comment by zomars** [comment]
- On `/auth/login` check the `prisma.users.count` being `0`
- Redirect to `/auth/setup` (new page) where the wizard will be displayed to create the first admin user.
- Once created, redirect back to `/auth/login`

**Comment by zomars** [comment]
We're planning to add more customization to the wizard later on. So we might just do it like this from start. Also we delegate this decision to self-hostess. Nothing is blocking them to make their own seeder for their own needs.

**Comment by leog** [comment]
Implemented by #3486.
