### ISSUE TITLE
[CAL-341] Consider sqlite as initial DB

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#3388]
---

> Thinking about possible [DX enhancements](twist-thread://3609969) my prefect experience would be:
>
> * Clone
> * yarn
> * yarn dev
>
> All without having to fill any env variables to have a working copy to explore the product. I’ve seen several stater repo that provide prisma with a sqlite db out of the box. This is perfect to test the waters as we can avoid using docker and setting up a postgres db for people who just want a quick test. (I’m thinking of [Ciarán](twist-mention://619023) trying to run the project earlier)
>
> We can also update the docs so we recommend switching to postgres before going to production

ref: [https://twist.com/a/195135/ch/554218/](https://twist.com/a/195135/ch/554218/)

> From [SyncLinear.com](https://synclinear.com)

**Comment by zomars** [comment]
Prisma isn't ready yet. We need them to add support for JSON fields on SQLlite first.https://github.com/prisma/prisma/issues/3786

**Comment by ColourfulField** [comment]
> Prisma isn't ready yet. We need them to add support for JSON fields on SQLlite first.[prisma/prisma#3786](https://github.com/prisma/prisma/issues/3786)

Seems like Prisma has finally implemented https://github.com/prisma/prisma/issues/3786

Could you reconsider adding this feature please? @zomars
