### ISSUE TITLE
Cleanup: Migrate DailyEventReference to BookingReference

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#3389]
In our attempts to keep our DB as generic as possible, we should try to clean it up a little bit. A quick win would be updating the Daily video specific model into using `BookingReference`.

**Comment by gracebir** [comment]
@zomars , I just want to confirm, are we going to update `dailyRef` field into Booking model ? I mean, get rid of `dailyRef` in Booking Replacing it with `bookingRef`, but I've also realized that I've already have `reference` field in booking model. Could you give a little clarification here please?

**Comment by zomars** [comment]
No. We want to get rid of the Daily model in favor of the generic Booking one.

**Comment by gracebir** [comment]
sure @zomars , I am going to work on

**Comment by gracebir** [comment]
@zomars , by getting rid of `DailyEventReference` model, we will no longer be able to use dailyVideo (daily.co), means we have to get rid of it to?

**Comment by zomars** [comment]
> @zomars , by getting rid of `DailyEventReference` model, we will no longer be able to use dailyVideo (daily.co), means we have to get rid of it to?

No. We must keep Daily functionality intact, just migrating the data to the `BookingReference`:

![image](https://user-images.githubusercontent.com/3504472/180020792-8888cbc6-ba71-4ae4-aee1-39d47159b57b.png)

If you feel this is quite complex don't worry, I feel that a @calcom/core member can take care of it. But thanks for the introspection. 🙏

**Comment by shapel** [comment]
👋 @gracebir @zomars   

How much data do you have? Do you consider using a step-by-step data migration process?

Instead of doing all data movement as one migration and switching all code to `BookingReference`, it might require some other strategy to prevent service unavailability.

@gracebir, I'd like to tackle this if you change your mind about this issue.

**Comment by zomars** [comment]
We have around 6k records in the `DailyEventReference` table. @shapel feel free to make a proposal and PRs are always welcome.

**Comment by shapel** [comment]
The number of records doesn't look too big, so it seems like we can do data migration in one go.
I'm going to tackle this one.

**Comment by shapel** [comment]
👏 @zomars,  
Can you review the draft PR to ensure that I got the idea correctly?
What else needs to be done? e.g. E2E or something like that...
PS 
I still see significant room for improvement in the 'pages/video/{uid}' section (way to handle meeting not found/unavailable/ended), but I suppose this could be done in other PR.
