### ISSUE TITLE
Not capable to open schedule and select time slot on localhost

### ISSUE THREAD

**Issue by benzogang389** [calcom/cal.com#3396]
### Issue Summary

When I open the public page for selecting time slot, I don't see any slots are available, while there is a timetable which covers all daily hours. 
I am performing that on local machine.

### Steps to Reproduce

1. Do ```docker compose up database -d``` for the database as it's in the steps for calcom/docker repo
2. Run the build and up commands locally, following the steps from calcom/docker repo
4. Open profile page where people can arrange a meeting
5. Press F12 to see errors
6. Run ```docker logs container_id``` for your running calcom/docker build in terminal

console log from docker container I run

`@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: Something went wrong ReferenceError: performance is not defined
@calcom/web:start:     at Procedure.resolve [as resolver] (/calcom/apps/web/.next/server/chunks/5017.js:3195:41)
@calcom/web:start:     at Array.<anonymous> (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:101:36)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async Procedure.call (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:144:20) {
@calcom/web:start:   originalError: ReferenceError: performance is not defined
@calcom/web:start:       at Procedure.resolve [as resolver] (/calcom/apps/web/.next/server/chunks/5017.js:3195:41)
@calcom/web:start:       at Array.<anonymous> (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:101:36)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async Procedure.call (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:144:20),
@calcom/web:start:   cause: ReferenceError: performance is not defined
@calcom/web:start:       at Procedure.resolve [as resolver] (/calcom/apps/web/.next/server/chunks/5017.js:3195:41)
@calcom/web:start:       at Array.<anonymous> (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:101:36)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async Procedure.call (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:144:20),
@calcom/web:start:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:start:   name: 'TRPCError'
@calcom/web:start: }
`
### Technical details

- nothing in both repos was changed

**Comment by PeerRich** [comment]
hey @benzogang389, @emrysal will take a look at this. I believe this was introduced in the last update, not sure why it doesn't work on localhost but on production

**Comment by reachkrishnaraj** [comment]
@PeerRich I am seeing this issue as well.

**Comment by agustif** [comment]
Are you guys running on node v16?

Asking because we use performance.now() calls in the slots router viewer. I think that's causing the issue as[ performance is not available in node < v16](https://stackoverflow.com/questions/46436943/referenceerror-performance-is-not-defined-when-using-performance-now) versions and needs to be imported from perf-hooks.

Can you confirm if using node v16 solves this issue?

## Possible followup tasks for cleaning up

- [ ] Need to update engines in package.json so it fails if < 16 
- [ ] If using v16 is not possible , requiring performance like in the answer could also fix this. But not sure we want to support older versions ? @zomars

**Comment by agustif** [comment]
Also, since you mentioned using our docker repo, I see we updated only 5 days ago the Dockerfile to node:v16
https://github.com/calcom/docker/blob/main/Dockerfile

Can you guys try again with latest version and let us know if it's fixed for you?

Thank you very much @reachkrishnaraj @benzogang389

**Comment by krumware** [comment]
Totally, and it doesn't need to be in the same repo.
I'd actually like to hook up the docker image build as a necessary check on PRs to help eliminate the issues with the two sides getting out of sync. Would that be ok with y'all?

**Comment by PeerRich** [comment]
@zomars is our master of actions. deferring the decision to him

**Comment by zomars** [comment]
I'm ok with that
