### ISSUE TITLE
German translation issues

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#3399]
### Issue Summary

Notification:
https://cal.com/success?date=2022-07-18T16
Dieses Meeting ist geplant

IS:
Sie müssen eine Änderung vornehmen?
Abbrechen [link] oder Reschedule [link]

Should be:
Termin ändern?
Absagen [link] oder neu planen [link]

In Sum:
Translation of Cancel => absagen (for Schedules correct)
so  also
in Cancellation mail
Ihr geplantes Ereignis wurde abgebrochen
should be
Ihr geplantes Ereignis wurde abgesagt

Seems the translations are done on some places well (e.g. E_Mail but not on the UI)

**Comment by PeerRich** [comment]
do you wanna open a PR straight away?

**Comment by dpalic** [comment]
> do you wanna open a PR straight away?

sure, if you point me to the source files referring to it. I will provide the changes.

**Comment by PeerRich** [comment]
> sure, if you point me to the source files referring to it. I will provide the changes.

https://github.com/calcom/cal.com/blob/main/apps/web/public/static/locales/de/common.json

**Comment by noobyogi0010** [comment]
@dpalic were you able to fix this issue?
