### ISSUE TITLE
Fix Spacing between Globally Installed and Add Another button in App Marketplace

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3408]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In the App Marketplace, when you navigate to say "Cal.video" app, if it is "Globally Installed" the spacing between the Globally installed" and "Add Another" button is too close and needs some padding.

<img width="1198" alt="CleanShot 2022-07-17 at 12 42 03@2x" src="https://user-images.githubusercontent.com/16177678/179427744-9023bce4-b39a-4d48-991e-00f16fb84c2d.png">

**Comment by gibranlamarca** [comment]
Hello @shirazdole, how are you? I'm trying to reproduce the issue but for some reason the Add another button doesn't show up for me, as it seems below:
<img width="1221" alt="Screen Shot 2022-07-18 at 9 18 16 AM" src="https://user-images.githubusercontent.com/70969354/179509864-ba4383c8-2a70-4bdc-9a63-da9522636f82.png">

**Comment by PeerRich** [comment]
@shirazdole can you try again?

**Comment by nerdjfpb** [comment]
@PeerRich  @gibranlamarca 
I tried refresh on this page - https://app.cal.com/apps/daily-video and I can see the button here too. 

![cal bug](https://user-images.githubusercontent.com/47062625/179563838-3fdbf784-7021-43b9-80d5-5be895bf5624.png)

**Comment by gibranlamarca** [comment]
@nerdjfpb In fact I can see it too accessing by cal.com, but not in localhost for some reason.. I'm investigating why

**Comment by PeerRich** [comment]
yup, can reproduce. will fix!

**Comment by PeerRich** [comment]
@sean-brydon will work on this

**Comment by Jaibles** [comment]
![Image](https://user-images.githubusercontent.com/4536123/179738074-4eeb1a64-c9bf-4e1e-a932-ce6178dd9fac.png)
