### ISSUE TITLE
When changing calendar integrations older selectedCalendars conflict with new.

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#341]
### Issue Summary
Previous selectedCalendar configuration preventing current integrations from being checked.

### Steps to Reproduce
1. Add a Google Calendar integration
2. Select some calendars
3. Remove the Google Calendar integration
4. Add the Office 365 integration
5. Now, Office 365 is no longer checked against as the following code is triggered:

  ```javascript
  /*
   * selectedCalendarIds: []
   * selectedCalendars: [
   *   {
   *     userId: 1,
   *     integration: 'google_calendar',
   *     externalId: '...'
    *   },
    *   ...
   */
  if (selectedCalendarIds.length == 0 && selectedCalendars.length > 0) {
    // Only calendars of other integrations selected
    return Promise.resolve([]);
  }
  ```

**Comment by thierrysantos** [comment]
Hello, I'm trying to reproduce this behavior and that is the bug?

<img width="616" alt="Screen Shot 2021-07-12 at 23 43 23" src="https://user-images.githubusercontent.com/14885967/125381896-1a77d980-e36b-11eb-9251-d2a8f393c8ff.png">
  
After following these steps above the Calendar from Office 365 should be selected?

**Comment by emrysal** [comment]
@0xthierry So sorry I never came back to you on this! I must've read your response but forgotten about it as I was heavily brainfogged at the time (Covid mid-July 2021). Closing now as it's probably fixed now.
