### ISSUE TITLE
Weird bugs in App with Next.js 12.2.x with middleware

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3410]
- https://github.com/vercel/next.js/pull/37716 - This bug seems to be the reason for shallow routing not working anywhere. It caused /booking navigations to stop working. [+Client side bookings navtabs broken](https://twist.com/a/195135/ch/554218/t/3628515/)
- Embed Modal Box doesn’t close
- Deleting a routing Form doesn’t update UI.
- Add a new routing form, doesn’t show the new Form in UI(which is the reason the tests are failing which @Peer R reported.) - 
_Happens only in production mode and not in dev mode._

All the bugs are demoed in here https://www.loom.com/share/dcf41ca221024bdc9de1fe8cd7c41449

**Comment by hariombalhara** [comment]
It also seems to be related dynamic catch-all routes.  I have observed that, when we go to Routing Forms(`/apps/routing_forms/forms`) through client-side navigation,` /apps/routing_forms/forms.json` request is sent after the page is rendered(which is the reason on next visit to the page, it loads correct number of forms)

**Comment by zomars** [comment]
Is this related to our production shenanigans that we patched in 1.8.3?

**Comment by zomars** [comment]
I'm setting up a small repro here: https://github.com/zomars/next-middleware-dynamic-route-static-page-repro

**Comment by PeerRich** [comment]
still open?

**Comment by hariombalhara** [comment]
I think we can close it. We have worked around all such issues AFAIK
