### ISSUE TITLE
Can't sign in with Google (OAuth policy error)

### ISSUE THREAD

**Issue by gibranlamarca** [calcom/cal.com#3414]
Found a bug? Please fill out the sections below. 👍

I'm trying to sign in with my Google email but i'm getting an error about OAuth 2.0 policy error, as you can see in the Loom video.

### Steps to Reproduce

1. Went to cal.com 
2. Clicked on Sign in with Google

https://www.loom.com/share/16ff4ea898764880987fdf30d5f2468a

**Comment by PeerRich** [comment]
hey @gibranlamarca we'll investigate immediately!

**Comment by emrysal** [comment]
@gibranlamarca What happens if you remove the callbackUrl from the URL? That may be what's causing the mismatch.

**Comment by PeerRich** [comment]
to be extra clear, remove this: 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/8019099/179549122-692033c8-b28b-4e25-b151-f92109141292.png">

**Comment by emrysal** [comment]
Additionally; on the google auth "Authentication Error" page - could you paste the URL to here so we can have a look what it received for the `redirect_uri` ?

**Comment by emrysal** [comment]
I have been able to reproduce this issue, it happens when the login URL lives on cal.com.

`https://cal.com/auth/login` is broken, but `https://app.cal.com/auth/login` works. - @gibranlamarca as a workaround, please use https://app.cal.com/auth/login to login.

As a result cal.com

**Comment by gibranlamarca** [comment]
Hello @PeerRich and @emrysal! First of all: removing the callback solves the issue, without it I could normally sign in. The (possible) problem is: I just typed cal.com and my browser suggested cal.com/bookings/upcoming and I hit enter, and this is what generated that callback URL, and since this is kinda of a "normal" thing to do, probably other users are falling into the same issue!

**Comment by emrysal** [comment]
Thank you very much; I think you've found a workaround; we're working on a fix 👍

**Comment by PeerRich** [comment]
> Hello @PeerRich and @emrysal! First of all: removing the callback solves the issue, without it I could normally sign in. The (possible) problem is: I just typed cal.com and my browser suggested cal.com/bookings/upcoming and I hit enter, and this is what generated that callback URL, and since this is kinda of a "normal" thing to do, probably other users are falling into the same issue!

very good point. thank you for the feedback. this should be easily resolved (unless I am wrong)

**Comment by denik1981** [comment]
This is usually solved with a sessionStorage key. You will store the path the user is attempting to visit prior to login, then do the OAuth flow to authenticate the user, you get redirected back to the registered URI and finally check your session storage to see if there is a some path in there to reroute the user once it has been authenticated. If no path is found take him back to the default registered URI. No need to have the callback in the URL.

**Comment by PeerRich** [comment]
i believe this has been fixed
