### ISSUE TITLE
Missing Zoom link when meeting is rescheduled

### ISSUE THREAD

**Issue by mcnaveen** [calcom/cal.com#3419]
### Issue Summary

When the meeting is rescheduled. The email doesn't contain a Zoom link.

### Steps to Reproduce

1. Create a New Meeting 
2. In the incoming email click on Manage this event
3. Now reschedule the meeting
4. You'll get a new email for rescheduling and there will be no zoom link inside that.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Since the meeting has been rescheduled, a user must get a new zoom link to join a meeting.

### Technical details
 I'm using Free version of cal.com

### Screenshot
![image](https://user-images.githubusercontent.com/8493007/179570188-e4bd9c7a-ef4c-4cf5-a2f2-6b1216461310.png)

**Comment by zomars** [comment]
It's in production now. We found some trouble with paid Zoom accounts that weren't sending a password field

**Comment by mcnaveen** [comment]
Thanks for the update.

**Comment by mcnaveen** [comment]
I hope this issue got fixed and rolled out already.
