### ISSUE TITLE
Example workflows on workflow page

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3425]
### Issue Summary

Showing example workflows on the workflow page to give users inspiration for what they can do. These could even potentially be templates at some point.

### Describe the solution you'd like
Something like that: 

<img width="1175" alt="Screenshot 2022-07-19 at 17 50 12" src="https://user-images.githubusercontent.com/30310907/179855312-2d35ff7a-7716-472b-84f2-6092907e350d.png">

For templates, users should be able to click on it so they get redirected to the workflow editing page where the steps are already created for them.

Examples for now could be: 
- Send SMS Reminder before event starts to Organizer 
- Send SMS Reminder before event starts to Attendee 
- Send Email Reminder before event starts to Organizer 
- Send Email Reminder before event starts to Attendee

**Comment by PeerRich** [comment]
love this

**Comment by noobyogi0010** [comment]
@PeerRich I would like to work on this if no one else has already taken it up.
Thanks!

**Comment by PeerRich** [comment]
> @PeerRich I would like to work on this if no one else has already taken it up. Thanks!

I believe @CarinaWolli is already working on it

**Comment by CarinaWolli** [comment]
I am not yet working on it. @noobyogi0010 you can work on it, let me know if you have any questions

**Comment by PeerRich** [comment]
@Jaibles do you have designs for this by any chance?

**Comment by noobyogi0010** [comment]
Alright, @CarinaWolli I will start working on it.
Thanks!

**Comment by PeerRich** [comment]
> Alright, @CarinaWolli I will start working on it. Thanks!

can you wait another few days, the designs aren't ready yet @Jaibles

**Comment by Jaibles** [comment]
Yep they're very nearly ready. Will have them within 2 days.

**Comment by noobyogi0010** [comment]
@Jaibles Okay, cool!

**Comment by Jaibles** [comment]
@noobyogi0010 I have designs here for what this screen will look like when the templates are just suggestions:
[View in Figma →](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13725%3A118180)

To the right you can see what these will look like when they become templates. A lot of things still a work in progress on this screen but this should unblock you for now.

**Comment by noobyogi0010** [comment]
@Jaibles Thank you so much for these designs. I will start working on these.
@CarinaWolli how should I decide whether its a suggestion or a template to use directly?

**Comment by CarinaWolli** [comment]
> @CarinaWolli how should I decide whether its a suggestion or a template to use directly?

I would say, ideally we would implement them all as templates. Looking forward to seeing your results @noobyogi0010 🙌🏻

**Comment by noobyogi0010** [comment]
@CarinaWolli 
Okay, I will implement them as templates.
Thank you!

**Comment by noobyogi0010** [comment]
@CarinaWolli I'm getting the following error when I am trying to run `yarn dx` command:
```
 Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported.
```

**Comment by zomars** [comment]
> @CarinaWolli I'm getting the following error when I am trying to run `yarn dx` command:
> 
> ```
> 
>  Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported.
> 
> ```

Please try `yarn workspace @calcom/prisma db-reset` and then `yarn dx` again

**Comment by noobyogi0010** [comment]
Thank you @zomars it worked.

But now to access the workflow feature I need a calcom license key. How can I get it?

**Comment by CarinaWolli** [comment]
> But now to access the workflow feature I need a calcom license key. How can I get it? @CarinaWolli

@noobyogi0010  For local development you can just return true in the checkLicense function (https://github.com/calcom/cal.com/blob/main/packages/features/ee/common/server/checkLicense.ts)

**Comment by Jaibles** [comment]
Will be closed by https://github.com/calcom/cal.com/issues/3793
