### ISSUE TITLE
[CAL-897] Faulty text display in mail, Line height might be off

### ISSUE THREAD

**Issue by karstenwinter** [calcom/cal.com#3428]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Headings are hard to read, lines overlap
![image](https://user-images.githubusercontent.com/4852618/179700698-fbe44484-7fe8-4360-a698-8afcba25f00f.png)

### Steps to Reproduce

1. (for example) Went to https://cal.com/peer
2. Booked an appointment 
3. opening confirmation mail 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- G-mail for Android from 11.7.2022

<sub>[CAL-897](https://linear.app/calcom/issue/CAL-897/faulty-text-display-in-mail-line-height-might-be-off)</sub>

**Comment by gracebir** [comment]
@karstenwinter ,I am going to make a look on this

**Comment by PeerRich** [comment]
@G3root can you test this?

**Comment by G3root** [comment]
fixed in  #8130
