### ISSUE TITLE
[CAL-898] Static Typecheck Javascript for Node14+ compatibility

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3430]
I accidentally introduced a bug by using `replaceAll` which isn't supported in Node 14. It passed all checks and landed in production because CI and most of us were using Node 16.

We should have static type checking configured for the Node version defined in package.json engines.

<sub>[CAL-898](https://linear.app/calcom/issue/CAL-898/static-typecheck-javascript-for-node14-compatibility)</sub>

**Comment by zomars** [comment]
We dropped support for Node 14 a while ago. The current recommended version is 16 and we're moving towards 18 soon.
