### ISSUE TITLE
zoom is missing in app store (self hosted)

### ISSUE THREAD

**Issue by wzrdtales** [calcom/cal.com#3431]
that is all that is there...

![image](https://user-images.githubusercontent.com/1786821/179715741-34ebb633-066e-4407-997d-d13efc8261cf.png)

**Comment by wzrdtales** [comment]
ok after trying to pull a latest container again, it shows more apps now, but zoom is still not in there and by that nun functional now

**Comment by matheusmuniz03** [comment]
Hello @wzrdtales! You need to do this setup for the rest of the apps to appear:
![Captura de tela de 2022-07-19 07-55-45](https://user-images.githubusercontent.com/87545749/179734205-4cf36067-e239-4f5f-8989-33fc08a255bc.png)


My localhost after setup:
![Captura de tela de 2022-07-19 07-58-36](https://user-images.githubusercontent.com/87545749/179734802-8d137aef-469a-4ac1-8cba-dff91a08392f.png)

**Comment by wzrdtales** [comment]
and in your setup is also no zoom.

As I updated in my second comment: there are now more apps since an update again. but still no zoom. see here


![image](https://user-images.githubusercontent.com/1786821/179751870-4e8035eb-7acd-4dcc-ad52-09d86e76e1e1.png)

**Comment by sjcotto** [comment]
i also can't see the apps

**Comment by PeerRich** [comment]
@zomars can you help out?

**Comment by zomars** [comment]
Can you check if zoom is not your App database model?

**Comment by wzrdtales** [comment]
model or data? The row with the zoom entry is there yes, model don't know where to check?

**Comment by wzrdtales** [comment]
It has that row yes it gets created upon startup.

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick
________________________________
Von: Omar López ***@***.***>
Gesendet: Montag, 1. August 2022 21:18
An: calcom/cal.com
Cc: Tobias Gurtzick; Mention
Betreff: Re: [calcom/cal.com] zoom is missing in app store (self hosted) (Issue #3431) 

In you DB there's an "App" table, it should have a row with zoom slug and your app keys as well.

**Comment by ZHconsultores** [comment]
Fresh install here, Zoom shows in 'App' table with proper 'key' on the DB (loaded from .env when docker image was build) but doesn't show in 'App Store' web page either. Also Microsoft Teams doesn't show (keys are loaded in DB) Any update on this?

**Comment by PeerRich** [comment]
hey, can you try the latest version again?
