### ISSUE TITLE
Make sure that turbocache isn't reused across Vercel environments

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3435]

**Comment by PeerRich** [comment]
still open?

**Comment by hariombalhara** [comment]
Yeah never got a chance to work on it.

**Comment by PeerRich** [comment]
how important is this?

**Comment by hariombalhara** [comment]
This doesn't happen often but when it happens it can possibly deploy preview code to production.
1. Preview - `build` command runs. Get's cached
2. Production - Reuses the same `build` cache and those artifacts gets deployed.

This is obviously not that straightforward to happen and has only happened with website deployment(but multiple times) when preview embed build got deployed to production.

**Comment by PeerRich** [comment]
any wy to reproduce this?

**Comment by emrysal** [comment]
Closing this, haven't seen this recently
