### ISSUE TITLE
Missing Google meet link when meeting is scheduled

### ISSUE THREAD

**Issue by xlincw0w** [calcom/cal.com#3438]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When the meeting is scheduled. The email doesn't contain a Google meeting link.

### Steps to Reproduce

1. Create a New Event Type and mark Google meet as your location or set an already existing Event Type's location to Google Meet
2. Book a meeting

![image](https://user-images.githubusercontent.com/32910910/179765188-16b5301e-2cf6-47ea-a6ba-5df90f3db16f.png)

**Comment by mcnaveen** [comment]
This is happening when rescheduling the meeting or the new meeting itself?

Check #3419

**Comment by achammah** [comment]
Hey ! have the same issue, it happens when first creating the meeting (so new meeting), don't know the root cause

**Comment by xlincw0w** [comment]
When creating a new one, don't know about rescheduling but i guess it both

**Comment by PeerRich** [comment]
I can’t reproduce it :( 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/8019099/180257883-042aa80b-b2ca-4022-b568-b072c241c27e.png">

**Comment by zomars** [comment]
@xlincw0w are you self hosting? Is this our `cal.com` hosted version? Do you have a Google Calendar connected? If you're self-hosting what version are you on? Please consider adding additional context so we can investigate further.

**Comment by xlincw0w** [comment]
Hey @zomars 

1. This is indeed self hosted
2. Google calendar and Google meet are connected through with GOOGLE_API_CREDENTIALS
3. Cal version is 1.8

**Comment by zomars** [comment]
Do you have a google-meet app in your database App table?

**Comment by xlincw0w** [comment]
Hey @zomars Sorry for the late reply
Yes i do have it 
![image](https://user-images.githubusercontent.com/32910910/183042592-bef9fd81-2ce6-4ba3-9e2e-6e9e21ffcc78.png)

**Comment by PeerRich** [comment]
just fyi why this has been open: it's hard to reproduce given its working on app.cal.com and we use the same code base. we're still investigating

**Comment by PeerRich** [comment]
one thing: make sure you have an active Google Calendar connection. Google Meet needs Google Calendar active

**Comment by artistro08** [comment]
@PeerRich would uninstalling and reinstalling the app make a difference?

**Comment by PeerRich** [comment]
> @PeerRich would uninstalling and reinstalling the app make a difference?

it does for some people

**Comment by bfollington** [comment]
> one thing: make sure you have an active Google Calendar connection. Google Meet needs Google Calendar active

Thanks for this, fwiw you need google calendar connected AND it has to be the calendar that events are added to for the URL generation to work. I had both Google Calendar and my iCloud calendar connected, with iCloud as the default and experienced this issue.

This is on app.cal.com, not self-hosting.

**Comment by ssuds** [comment]
I'm having the same issue as @bfollington on app.cal.com with an Outlook and Google Calendar account linked.

The google meet link generates if I have events added to my gmail account. No link generates if I have events added to my Outlook account.

**Comment by PeerRich** [comment]
pretty sure this was fixed a while ago

**Comment by aelmasry** [comment]
Hey  ! have the same issue, it happens when first creating the meeting (so new meeting), don't know the root cause

**Comment by nepomuc** [comment]
@PeerRich My self-hosted cal.com instance falls back to the unremovable Cal Video integration too as soon as I confirm a booking which is supposed to use Google Meet. This doesn't seem to be fixed. Please reopen this issue or add a note to the Google Meet integration that it only works if the events are added to a Google calendar. It would be best if cal.com would be able to create a Google Meet link independently from which calendar is used to save the events to, though.

**Comment by notflip** [comment]
Same here! I see "Google" as a location with a link to Google Maps. It doesn't make sense.

**Comment by francescogatto** [comment]
same here! sometimes google meet video doesn t work and it appears:
Google Meet: The meeting URL is included in the confirmation email.
