### ISSUE TITLE
Tests Required: There should be some tests for cal api in cal.com repo

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3447]
Turns out we can accidentally break api build without realizing. We can start with a very simple build command as the first test which verifes that build succeeds. It can be followed by running more API tests

Refer to https://github.com/calcom/cal.com/pull/3446

**Comment by PeerRich** [comment]
we would need to make more specific issues for each API endpoint, no? @zomars

**Comment by keithwillcode** [comment]
This is now addressed with the API living in the cal.com repo. We are immediately aware of breaking changes.
