### ISSUE TITLE
O365 Calendar not syncing for multiple Users

### ISSUE THREAD

**Issue by sw506** [calcom/cal.com#3462]
### Issue Summary

UPDATE: While it didnt work for for one user constantly, now it doesn't work for all Users...

On a fresh installation the O365 Calendar Plugin does not work anymore for one User, while it works for others and worked on a previous installation for the same user. Users are all added with exactly the same settings in the DB.
User tried to remove and re-add Outlook Calendar, without any sucess. The Calendar in questions toggle is activated.

### Steps to Reproduce

1. Pick any meeting link from the user e.g. https://cal.example.org/user-name/15min
2. Click on date
3. ... All times are free to book, although theere are already appointments in Outlook

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Tested from multiple devices with multiple Browsers
- node v16.16.0 @ Ubuntu 20.04
- calendso Release v1.8.0
- Log output while selecting Date: https://gist.github.com/sw506/cba02b8e1b99b42702465feefe8274b4
- Developer-Console while selecting Date:
![Bildschirmfoto 2022-07-20 um 11 43 07](https://user-images.githubusercontent.com/100691505/179951603-5aea297f-5eeb-4c8e-819e-bca75f38e1f6.png)

**Comment by PeerRich** [comment]
just to confirm, you added the microsoft API token etc.?

**Comment by sw506** [comment]
Yep, API token is in .env.appStore and works for Teams link creation. At least for some Users.

**Comment by ch-ruetgers-RMH** [comment]
Thank you @sw506 - we stumbe across the very same issue. ATM Cal is not usable for us unless we had rolled it out with great success and our clients are quite disappointed we can had to stop this service.

**Comment by PeerRich** [comment]
> Thank you @sw506 - we stumbe across the very same issue. ATM Cal is not usable for us unless we had rolled it out with great success and our clients are quite disappointed we can had to stop this service.

hey @ch-ruetgers-RMH we're working hard to resolve this issue right now @alannnc @joeauyeung

**Comment by joeauyeung** [comment]
@alannnc created a major fix for this issue. PR is approved and should be included in the next release.

https://github.com/calcom/cal.com/pull/3534

**Comment by PeerRich** [comment]
fyi, next release is tomorrow cc @zomars

**Comment by PeerRich** [comment]
hey, can you try the latest version again?
