### ISSUE TITLE
refactor: use <EditableHeading/> in event-types/[type].tsx

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3466]
right now we only use `<EditableHeading/>` in /availability page but we should also use it in `event-types/[type].tsx`

<img width="212" alt="image" src="https://user-images.githubusercontent.com/8019099/179975884-de1bb34c-5270-4f8e-acad-1b27e86261c5.png">

**Comment by PeerRich** [comment]
awesome, go for it!

**Comment by shapel** [comment]
@PeerRich I find out that https://github.com/calcom/cal.com/blob/main/apps/web/components/PencilEdit.tsx was also abstracted from `/event-types/[type]`. Should I merge its functionality to `EditableHeading` and use it everywhere?

**Comment by PeerRich** [comment]
> @PeerRich I find out that [https://github.com/calcom/cal.com/blob/main/apps/web/components/PencilEdit.tsx](https://github.com/calcom/cal.com/blob/main/apps/web/components/PencilEdit.tsx?rgh-link-date=2022-07-20T14%3A19%3A56Z) was also abstracted from `/event-types/[type]`. Should I merge its functionality to `EditableHeading` and use it everywhere?

yes please 🙏

**Comment by shapel** [comment]
👋 @PeerRich, I've already done this in #3468 🤓
