### ISSUE TITLE
Responsive issue on embedded popup on mobile

### ISSUE THREAD

**Issue by MathisTimo** [calcom/cal.com#3476]
### Issue Summary

When on mobile the bottom part of the pop up is not in the viewport

### Steps to Reproduce

1. Went to [my website](https://www.philocks.fr/)
2. Clicked on "RDV Départ de locks en twist" button
3. Opened chrome dev tool, selected mobile view, switched to iPhone SE view
4. Tried to scroll to the bottom

### Technical details

I'm not self hosting cal. This also happens on app.cal.com on the embed preview section. 
Chrome Version:  103.0.5060.114

**Comment by PeerRich** [comment]
@hariombalhara can take a look

**Comment by hariombalhara** [comment]
I can replicate the issue and I have a fix. Will push it live tomorrow after testing.

Seems like it got broken sometime back when I gave padding at the top. Would consider the offsetTop for the modal box to fix it

**Comment by hariombalhara** [comment]
This is fixed and live now. Verified on https://www.philocks.fr/ as well.
