### ISSUE TITLE
Design issues on success page in some languages 

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3489]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Design issues on the success page in some other languages than English. Only tested it in German:

<img width="488" alt="Screenshot 2022-07-21 at 20 21 44" src="https://user-images.githubusercontent.com/30310907/180336172-bc43adb4-8382-429b-9955-1571d404d2c8.png">

English: 

<img width="474" alt="Screenshot 2022-07-21 at 20 25 39" src="https://user-images.githubusercontent.com/30310907/180336510-fd77368a-bc8d-462d-ae9d-ab8d0d17878b.png">

**Comment by PeerRich** [comment]
we should make a line break:

Add to Calendar
[Icon] [Icon] [Icon] [Icon]

**Comment by matheusmuniz03** [comment]
do you like something like this? Or do you prefer the links on the left?
![Captura de tela de 2022-07-22 08-27-27](https://user-images.githubusercontent.com/87545749/180430179-7fc1ef4e-6eae-43b7-9b11-7080c184cbd7.png)

**Comment by CarinaWolli** [comment]
> do you like something like this? Or do you prefer the links on the left?

I would definitely put the links to the left if we add a line break

**Comment by CarinaWolli** [comment]
Also, this is not in line (in English it is):

<img width="493" alt="Screenshot 2022-07-21 at 20 23 30" src="https://user-images.githubusercontent.com/30310907/180498372-5a751672-7629-4a2f-93f5-a9705f7fa1b4.png">

**Comment by PeerRich** [comment]
lets involve @Jaibles

**Comment by mocherfaoui** [comment]
does this look any good @CarinaWolli ?
![Screenshot 2022-07-22 201823](https://user-images.githubusercontent.com/37941426/180511890-f12dc1a9-ffba-4f29-b1db-72ba7764e36a.png)
this is how it looks on mobile:
![Screenshot 2022-07-22 201743](https://user-images.githubusercontent.com/37941426/180512016-17360bdc-9fb2-4b71-99e4-c7afc308382d.png)
one thing though, I wanted to test how will this look on an RTL language like Arabic, but when I switched to Arabic everything is still LTR?

**Comment by CarinaWolli** [comment]
> does this look any good @CarinaWolli ?

@mocherfaoui  The screenshots look good to me 👍


> one thing though, I wanted to test how this will look on an RTL language like Arabic, but when I switched to Arabic everything is still LTR?

Not sure about that. Maybe somebody else from @calcom/core knows more about that
