### ISSUE TITLE
[CAL-841] Add status on /bookings API endpoint

### ISSUE THREAD

**Issue by vpul** [calcom/cal.com#3515]
### Is your proposal related to a problem?

Bookings API does not show status ('canceled', 'pending confirmation', etc) which makes it difficult to work with. Also, I couldn't find API to cancel, reschedule or confirm bookings.

### Describe the solution you'd like

- Show the current status of a particular booking. 
- API endpoints to cancel, reschedule and confirm the pending booking.

**Comment by agustif** [comment]
Hello @vpul, we've recently extracted out our trpc routes so they can be shared between public API and webapp. And so we will be addressing both of those issues soon thanks to it. I will keep you posted here, thanks for bringing it up.

**Comment by vpul** [comment]
Hey @agustif . Thanks for responding. I was wondering if I should use the webapp API routes in the meantime to augment the public API. 

I know these are not documented but I just need the 'confirm booking' route for now. Of course, these will be a temporary workaround until the public API is ready. What do you think?

**Comment by emrysal** [comment]
Can be closed (has been implemented for a while now)
