### ISSUE TITLE
Improve Internationalization with having one backend and independent of "frontend" language

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#3519]
### Is your proposal related to a problem?

no it is a feature request (or is it a bug?)

### Describe the solution you'd like

As a admin of the cal.com, I want to use the backend in English. (error reporting is easier, easier to handover to other international colleagues and so on). so that I can use the backend in English, without impacting the frontend language to the users.

The frontend of the users can be arbitrary language.
So there are multiple options:

- provide translation options for the cal entries (best path, since users decide in which langauges to provide all custom texts)
- provide independence from backend, so that the cal can be used in one specific language

right now, if you switch the backend language of the admin user, all language entries of the cal meeting pages are also in english. Bad if you have mostly (in my case German speaking bookers)

### Describe alternatives you've considered

- great would be, that I am able to decide what backend language to use
- even more great would be that I can decide what languages I require for the meeting
- and if I select the meeting languages, that I have additional translation fields to write the texts also in the given language
- and it would be great, if the language would be detected by the browsers language settings and provided to the user of the meeting booking to choose if he/she wants a different available language

**Comment by PeerRich** [comment]
just to clarify, by "backend" you mean the signed in area?

**Comment by karolzlot** [comment]
Yes, admin panel should be independent from booking page.

I would like to have option to set booking page to arbitrary language (currently I see it is English only, no way to change it).

Another option is to use auto-detection on booking page to detect user's locale (with dropdown allowing user to change it, sometimes users have wrong settings and they are not technical enough to change it).

**Comment by karolzlot** [comment]
Ok, I see language on booking page is auto-detected, I had wrong settings in my browser...

**Comment by PeerRich** [comment]
> Ok, I see language on booking page is auto-detected, I had wrong settings in my browser...

yes, the booking page should be based on the visitors browser. I think this is the best solution right now
