### ISSUE TITLE
Team Gantt view for Timezones

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3524]
### Is your proposal related to a problem?

It's hard to know what timezone my team members are in. Especially for a remote company, it can be difficult to know when is a good time to message them for something or scheduling meetings.

Team Gantt view for Timezones

### Describe the solution you'd like

Navigate to the team page within cal.com and see a gantt view of all my team members and be able to search by name and pull up their name/time more easily. It would be great to also have command k capabilities (timezone/shiraz) and then it pull ups my timezone. I would also love the ability to have an easy URL to pull up the view as well (cal.com/team/cal/timezone)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Toledodev** [comment]
Hey @shirazdole, can you explain me more about the feature?

**Comment by shirazdole** [comment]
Hi @Toledodev for some reason it didn't pull all the details, here you go:
### Is your proposal related to a problem?



Team Gantt view for Timezones

### Describe the solution you'd like



(Describe your proposed solution here.)

### Describe alternatives you've considered



(Write your answer here.)

### Additional context



(Write your answer here.)

**Comment by shirazdole** [comment]
@Toledodev just updated my comment :)

**Comment by leog** [comment]
Here is an open source library to handle Gantt charts: https://github.com/MaTeMaTuK/gantt-task-react
Saw a bunch being paid libraries so wanted to contribute free alternatives.

**Comment by leog** [comment]
Another open source alternative which is looking for library maintainers: https://github.com/namespace-ee/react-calendar-timeline by @ilaiwi

**Comment by zomars** [comment]
[Some inspiration](https://everytimezone.com/s/34cdd78d?t=62e32300,3c0):

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/3504472/181408878-520342aa-656e-4862-ba66-1d34025f7a3d.png">


Now, picture this view but with each team member displaying their "default availability" laid out for comparison.

**Comment by zomars** [comment]
@JeroenReumkens this is the chart we discussed on the call

**Comment by PeerRich** [comment]
i am still not sure if we want to add this, it feels like we are distracting ourselves from our core roadmap. its nice don't get me wrong, but kinda Nice-to-Have only
