### ISSUE TITLE
Round Robin booking assigned to unavailabe team member

### ISSUE THREAD

**Issue by RebeccaCotton** [calcom/cal.com#3531]
### Issue Summary

When a meeting with a round robin team is scheduled, the meetings are always scheduled with the event type creator, even on slots they are not available at

### Steps to Reproduce

1. create a team with at least two, users (in our example U1 created the team and U2 is a team member)
2.  Set their availabilities, e.g. U1 = Monday, 9-11AM, U2 = Friday 1-3PM and set both schedules to default
3. Create a round robin event type with these two team members, and copy the meeting link
5. Log out of cal.com with both users
6. Use the link to book a meeting for that event type
7. Select a slot from U2, on Friday
8. Confirm the booking
9. Check the booking page for the new meeting

**Actual behaviour**:
- The meeting has been booked with U1 on a timeslot that they are not available at, according to their schedule

**Expected behaviour**
- The meeting should have been booked with U2, who is available at the selected time slot.

### Technical details

System: Self Hosted, cal.com, version 1.8.0 - but we already discovered this bug in an earlier version
I also think this issue might be what is causing this issue: https://github.com/calcom/cal.com/issues/3190

**Comment by milospuac** [comment]
Hi Rebecca. Thanks for reporting the issue. 

Our team will investigate this. 

Best,

**Comment by RebeccaCotton** [comment]
Hi, we have discovered, that this is not actually fixed for events with multiple users

We have users configured here with the following availabilities:
- Mon 9-11 User1 available
- Mon 11-12 Both available
- Mon 12-17 User2 available
- Wed 9-12 User1 available
- Wed 14-17 User1 available
- Fri 14-17 User2 available

We see all events being booked with User2. Even events on Wednesday, where that user does not even have times available at all are booked with them. 
![image](https://user-images.githubusercontent.com/14073417/187080902-52e55a7e-f159-487a-87c7-20832b22b2f9.png)

Here is a video with the problem: [https://youtu.be/4AaUl302mXQ](https://youtu.be/4AaUl302mXQ)

[Here is the event we used for testing](https://cal.com/team/testteam---bug-round-2/teamtestevent---both-users)

**Comment by bilalfaisal-ct** [comment]
Any fix for this we're still getting this error and not able to use cal
