### ISSUE TITLE
In Event Type settings: Show the default selected calendar - Right now it looks like no calendar is selected.

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3535]
### Is your proposal related to a problem?

When creating a new event type, there is no calendar selected when creating the event. This is a crucial step to ensure users have a calendar connected. I believe most users will "assume" that there calendar is connected, but the fact is no calendar is connected when an event type is set up. A user needs to go into advance settings and select their calendar from there.

### Describe the solution you'd like

From the event type creation page, give users the ability to select the calendar they want to use. Add text saying _you can edit this calendar in the advanced settings of the event type page_
![CleanShot 2022-07-26 at 11 56 45@2x](https://user-images.githubusercontent.com/16177678/181119792-3dab5814-18d1-4ada-a71b-820a5f8d1972.png)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by shirazdole** [comment]
@Jaibles something worth potentially looking into 🙏

**Comment by gracebir** [comment]
@shirazdole , we need to add up a datepicker right ?

**Comment by Toledodev** [comment]
Hey @shirazdole, Where in advance settings would the user have to go?

**Comment by Toledodev** [comment]
@shirazdole Something like this, right?
![Screenshot from 2022-07-27 09-04-52](https://user-images.githubusercontent.com/87545086/181242643-82e648de-5f9b-466d-90ff-00f4f32b80a0.png)

**Comment by Toledodev** [comment]
Why should a user have a calendar connected? Also, I created a Event Type and went to advanced settings but I didn't find anything to select calendar

**Comment by gracebir** [comment]
is this what we are expected?
![selected](https://user-images.githubusercontent.com/46535846/181297851-2140b4de-ed35-4a4d-abda-8abd748e0fd9.png)

**Comment by Jaibles** [comment]
Hi @gracebir - thanks for the idea!

Right now this is an app wide setting that we get people to setup in onboarding and then it's setup for all their event types. The majority of our users want their bookings/events going to the same calendar.
<img width="1491" alt="CleanShot 2022-07-28 at 09 46 02@2x" src="https://user-images.githubusercontent.com/4536123/181463211-61e02e7d-520e-448a-a67d-1016b6c2f6e6.png">

They can manage this in "Installed Apps" 
<img width="1482" alt="CleanShot 2022-07-28 at 09 48 43@2x" src="https://user-images.githubusercontent.com/4536123/181463630-4980299e-72e8-4cdf-bcfa-5a87fb7da264.png">

And soon will also be able to edit in settings (new designs).
<img width="1482" alt="CleanShot 2022-07-28 at 09 45 37@2x" src="https://user-images.githubusercontent.com/4536123/181463551-376a0783-a2d8-4fe7-8fc5-ef58d3cb2c69.png">

If they want to override this global setting on a per event basis we allow them to do this in advanced settings
<img width="1482" alt="CleanShot 2022-07-28 at 09 49 40@2x" src="https://user-images.githubusercontent.com/4536123/181463818-80c54c7f-850b-4fa4-8574-8b74d851b93a.png">
_Again these are new designs but the UX is similar now in that it's in advanced settings_

Where I do think there is an issue however and where we could use your idea, is if they don't have a calendar connected at all (ie if they've skipped that step in the onboarding) or disconnected all their calendars. In that scenario, I think it would be good to call out that they should connect a calendar (although it is not essential as @Toledodev has eluded to).

I will explore design solutions for when people go to create event types but don't have a calendar connected. Thank you!

cc @shirazdole

**Comment by gracebir** [comment]
@Jaibles , which solution are you suggesting here ? Cause I was about to add `AdditionalCalendarSelector`, and this the solution that I am thinking about

**Comment by shirazdole** [comment]
@Jaibles Not quite sure if we are still on the same page, lmk if this is helpful? https://www.loom.com/share/ea0f848512674fdea38ef7436f8cd054

**Comment by Jaibles** [comment]
@shirazdole we're definitely on the same page here. It should automatically create events on your default calendar. You should not have to do anything in the event type settings. I suspect this is just an issue where that dropdown is not showing your default. If it's in fact a bug where no calendar is selected this is worse and should be reported as a critical bug.

**Comment by Vishrut19** [comment]
Is this issue still open??

**Comment by Jaibles** [comment]
This issue is fixed.
https://github.com/calcom/cal.com/assets/4536123/80c61a87-b8ff-43ec-882b-4b6f9bb69220
