### ISSUE TITLE
Trial verbiage on Pro Plan

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3536]
### Is your proposal related to a problem?

Clean up the Trial Language on the Pro Plan on billing:
<img width="600" alt="CleanShot 2022-07-26 at 12 25 39@2x" src="https://user-images.githubusercontent.com/16177678/181122943-1d66e3f2-a878-46d2-888f-de0ca7fe7203.png">
You're currently on the TRIAL plan.
Upgrade your account to the PRO plan to unlock all of the features we have to offer.

### Describe the solution you'd like

New verbiage:
You're currently on the TRIAL plan.
Upgrade your account to the PRO plan to **keep** _(unlock)_ all of the features we have to offer after your trial is over.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by shirazdole** [comment]
@Jaibles if I'm not mistaken, users get access to all pro features during their trial. This small tweak may clear up any confusion :)

**Comment by PeerRich** [comment]
trial is going away soon
