### ISSUE TITLE
[CAL-88] Disconnected Calendar still Showing as Calendar to Create Events On

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3537]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When disconnecting a Google Calendar from calendars through installed apps (in this use case there are two calendars connected). The calendar that is disconnected, first does not go away after being disconnected (it still shows and goes away once you refresh the page), but when you look at the selector for where events are created, it still shows the old calendar rather than the current calendar available.

I disconnected shirazdole@gmail.com, so only shiraz@cal.com should be available, but shirazdole@gmail.com still shows

### Steps to Reproduce

1. Click on installed apps
2. Disconnect a calendar
3. See if the calendar goes away or if have to refresh
4. If have to refresh, see if the disconnected calendar is removed from the "Events created on:" selector
![1f2d-426e-8a5b-89b6a72230ba](https://user-images.githubusercontent.com/16177678/181129718-335ed43b-4e8c-4ca0-931f-d7d991dc71f0.png)

https://app.birdeatsbug.com/sessions/EuuiOPhVIXDDjzesajiSWU4tY8geCOfcYAX4aMGKTYkX

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by Udit-takkar** [comment]
it's fixed now https://github.com/calcom/cal.com/pull/5912
