### ISSUE TITLE
Rescheduling is done but the email informing the rescheduling is not sent.

### ISSUE THREAD

**Issue by jjromary** [calcom/cal.com#3538]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am able to reschedule events on my calendar, but the email informing me of this rescheduling is not being sent.

### Steps to Reproduce

1. Schedule any event on your calendar.
2. Reschedule this event
3. See in VScode console the error
4. 
this error is in `apps\web\pages\api\book\event.ts`

![image](https://user-images.githubusercontent.com/37199044/181130870-737d65a0-34b6-4171-b4da-b7e64aad25e6.png)

### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

It was expected that an email would be sent to the organizer and participant informing them of the new scheduled time.
Until recently this function worked normally in my localhost application, but as of this week I could no longer use this function.

If all this information is not enough, please let me know that I can pass on additional information.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version 16.0.0
- Google Chrome
- Win 10

**Comment by milospuac** [comment]
Hi there

Thanks for reaching out. Our team will investigate this

Best,

**Comment by jjromary** [comment]
HI, @milospuac. You have a new update?

**Comment by jjromary** [comment]
Update my project and this problem was resolved
