### ISSUE TITLE
Create events on more than one connected calendar

### ISSUE THREAD

**Issue by MehmetAdemi** [calcom/cal.com#3544]
Problem:
I have two calendars (private & work) connected to my cal.com. Now when someone books a meeting with me the event gets created only in one of my calendars.

Requested feature:
I would appreciate it if there would an option to select both connected calendars (or all connected calendars).

**Comment by milospuac** [comment]
Hi Mehmet, 

Already forwarded this to the product team to consider for the next version :) 

Best,

**Comment by pksunkara** [comment]
Will this be solved by the organization feature?

**Comment by PeerRich** [comment]
essentially the dropdown "where to add the event" needs to become a multi select?

**Comment by MehmetAdemi** [comment]
That would be the best solution, so yes.

**Comment by PeerRich** [comment]
in the meantime, can y'all use something like reclaim.ai to sync your calendars?

**Comment by utsengar** [comment]
Just dropping in a note that I vote for this feature
In the team time, any workarounds?
