### ISSUE TITLE
Outlook Calendar Sync Issues

### ISSUE THREAD

**Issue by RobynOllie** [calcom/cal.com#3546]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A member of our Ollie team on Cal, Abby (https://cal.com/abby-doubell) has been experiencing issues with their calendar not syncing correctly. She tried disconnected and re-adding her Outlook calendar but it's still not picking up when she's busy and is making her available all the time. I've check the event type settings and her availability etc and not sure what else to do? Please compare the screenshot from troubleshooter below vs her availability for tomorrow here and you'll see what I mean: https://cal.com/abby-doubell/45-minute-therapy-session?date=2022-07-28

<img width="389" alt="image" src="https://user-images.githubusercontent.com/110086895/181203324-039b52b9-c8d2-47e7-a3d7-78322df27a87.png">

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by xlincw0w** [comment]
Hello there, i'm having the same problem users can book in a time where i'm already set busy (calendar used: outlook)

**Comment by PeerRich** [comment]
hey @RobynOllie is this still happening?
