### ISSUE TITLE
Provide query/url-parameter for hidden fields

### ISSUE THREAD

**Issue by dpalic** [calcom/cal.com#3547]
### Is your proposal related to a problem?

Assume you work on a high load ticket system. Now you have to schedule events via the ticket system. But you have no option to pass a hidden field like a ticket-ID.
The agents working on the ticket system have to do a lot of manual work to find the corresponding ticket to the corresponding scheduled event. Since the e-mail used on the cal.com may differ or a representative was elected to do the call or many other options may happen (and happen in our case)

### Describe the solution you'd like

I would like to have an option to pass a query/url-parameter to the cal.com event, which can be generated by the ticket system

e.g.
cal.com/mysomethingevent?refId=abcedfed
cal.com/mysomethingevent?refId=12234567

This refId schall be added to the title and the body, or even better, via a template/variable like 

{refId} and the admin of the event can decide where to put the refId 

### Describe alternatives you've considered

I have no idea about and additional/alternative solution.
The only option would be to have a additional field, which can be named freely by the cal.com admin and this field can be used also 
in the query/url as parameter

e.g.

additional field:  blaSomethingTicketId
this field is read only, so cal.com event booker cannot change the field
and the ticket-system can pass this field blaSomethingTicketId

like

cal.com/mysomethingevent?blaSomethingTicketId=12345678

this is providing us currently tons of pain (during additional effort) and would be great if it could be priorized for the next production version.

Willing also to support in pre-production/stage if you need some help there - as giving back my effort to support you

**Comment by PeerRich** [comment]
interesting idea! i see some use cases for this

**Comment by zomars** [comment]
Don't we already do this?

**Comment by zomars** [comment]
You Can add a hidden field and prefill it like [explained here](https://github.com/calcom/cal.com/blob/main/apps/docs/pages/developer/pre-fill.mdx). 

Cc @PeerRich  this doc is not on GitDoc yet BTW

**Comment by PeerRich** [comment]
@baileypumfleet can you make sure to move over all docs to gitbook?

**Comment by dpalic** [comment]
@zomars I cannot use this feature?

Added a Additional Input:

- input type: text
- Label: TicketNumber
- placeholder: some description text
- required: true

if I pass 
?TicketNumber=12345 to the cal link, the field is NOT prefilled?

can you please let me know how to use it?

**Comment by dpalic** [comment]
ohh...
it is working
but not that obvious from the page

1. the query params have to be lower cased
2. also not clear from doc that UI Addition Input Label is lowerCase(Label) is the query parameter

now can implement my requirement, but doc shall be improved.

**Comment by zomars** [comment]
Thanks for the feedback @dpalic will use this to improve the docs

**Comment by PeerRich** [comment]
@alishaz-polymath can you investigate if our docs are up to date?

**Comment by hariombalhara** [comment]
<img width="361" alt="Screenshot 2023-06-20 at 4 46 01 PM" src="https://github.com/calcom/cal.com/assets/1780212/66d1bbf7-5f89-4381-bd22-46e7d640355a">
Have you tried toggling off the field? Toggled Off(Hidden field) can still be prefilled.

**Comment by elberon** [comment]
I didn't even notice that toggle. Thank you for pointing it out!

**Comment by kwanso-suleman** [comment]
@hariombalhara but it does not solve the overall problem, why do our hidden fields show to the booker mail, I just wanna use it for internal operations.

**Comment by xta** [comment]
> @hariombalhara but it does not solve the overall problem, why do our hidden fields show to the booker mail, I just wanna use it for internal operations.

Same. I see the "hidden" field in the booking e-mail confirmation. It's not hidden.

There are many valid use cases for passing information the person booking the event does not need to see. Showing this  adds unnecessary confusion.
