### ISSUE TITLE
Feature Request: Send invites as Organiser from the calendar that is booked (not from Cal.com login email)

### ISSUE THREAD

**Issue by rittaaka** [calcom/cal.com#3553]
Currently, if a user connects Calendar A - where the organiser is Email Address A - and Calendar B - where the organiser is Email Address B - invitees can book in to both Calendar A and Calendar B, depending on which Calendar the event type pushes to. 

However, supposing that the user's Cal.com account is associated with Email Address A, even if Calendar B is booked, the invitation will come from Email Address A (not email Address B). 

The objective is that anyone who books into the calendar connected to Email Address B receives invites from Email Address B, and anyone who books into the calendar connected to Email Address A receives invites from Email Address A.

This would enable Cal.com to be a truly multi-calendar user experience.

**Comment by milospuac** [comment]
Thanks for presenting your case. Our team will look into this.

**Comment by PeerRich** [comment]
we're planning to work on multi-email very soon

**Comment by rittaaka** [comment]
Awesome! looking forward to this.

**Comment by PeerRich** [comment]
> very soon

sorry about this.

still planned tho

**Comment by tomtitherington** [comment]
+1 👍

**Comment by PeerRich** [comment]
related: #8007
