### ISSUE TITLE
center and space buttons on cancel page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3554]
on /cancel/ we need to horizontally center the buttons and give it space-y-2 margin between the buttons 

<img width="462" alt="CleanShot 2022-07-27 at 20 16 48@2x" src="https://user-images.githubusercontent.com/8019099/181343717-55cb6477-7348-46e9-b7e7-804d2891ec95.png">

**Comment by jjromary** [comment]
![image](https://user-images.githubusercontent.com/37199044/181370554-d3cb0c5a-f67a-4431-9feb-180ed2ff93f4.png)

Does this Style meet your request?

**Comment by Udit-takkar** [comment]
@PeerRich can i take this one? 
And can you send where this component  is ? can't read this language

**Comment by PeerRich** [comment]
of course! this is the /cancel/ page when cancelling an event

**Comment by PeerRich** [comment]
wait, @Jaibles actually has new designs for this

**Comment by PeerRich** [comment]
here: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13658%3A93949 

it says still work in progress, @Jaibles what's missing?

**Comment by Udit-takkar** [comment]
@Jaibles just comment here when design is completed.

**Comment by Jaibles** [comment]
It's ready now.

**Comment by om-ray** [comment]
@Jaibles Would it be possible for me to work on this?

**Comment by Udit-takkar** [comment]
@om-ray i am working on this. was busy because something came up.

**Comment by om-ray** [comment]
Ahh ok, thanks for letting me know
