### ISSUE TITLE
Invite to team doesn't generate a notification/mail

### ISSUE THREAD

**Issue by karstenwinter** [calcom/cal.com#3564]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I just found out by chance and when my colleague told me he invited me to a team that there was something.

Found it by clicking through the settings until I found https://app.cal.com/settings/teams.

I would expect a notification in the dashboard UI and a mail :)

### Steps to Reproduce

1. Invite someone to join a team

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Chrome, Windows Mail

**Comment by milospuac** [comment]
Thanks for reaching out. I notified our product team to investigate this

**Comment by milospuac** [comment]
I actually just tested this out and it's working. What is the mail provider that you're using? Also, it would be good to check your spam folder

**Comment by karstenwinter** [comment]
Checked spam and unknown

Can you invite me to a test team and check if the system sends a mail?
cal.com/karsten

**Comment by PeerRich** [comment]
@karstenwinter 
can confirm working for me, too.

what email service? can you test a gmail account, too?
