### ISSUE TITLE
close dropdown in teams to prevent z-index bug

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3566]
## problem

on https://app.cal.com/settings/teams when clicking 

<img width="250" alt="CleanShot 2022-07-28 at 13 58 21@2x" src="https://user-images.githubusercontent.com/8019099/181499559-c4695ef1-c687-4e57-92d8-916e3bcf0cee.png">

and selecting "disband team" it shows:

<img width="762" alt="CleanShot 2022-07-28 at 13 57 20@2x" src="https://user-images.githubusercontent.com/8019099/181499401-f7bce562-3188-440e-99ee-c9647b721d84.png">

## solution:

close dropdown when clicking "disband team"

**Comment by PeerRich** [comment]
> I tried to fix this issue and arrived at two solutions
> 
> * currently the menu is being rendered in a portal and its `z-index` is `2147483646`  if we pass `portalled={false}` to `DropdownMenuContent` in `TeamListItem.tsx` the issue is fixed
> * we can change the `z-index` of the Dialog component to `2147483647` which is one more than the `z-index` of the portal in which the `DropdownMenuContent` is being rendered
> 
> I tried to fix the zIndex of the `Dropdown` component but I guess Radix-UI doesn't allow to change it

why not close it? if possible we can change z-index but this problem would also be solved by just closing the dropdown

**Comment by sairajchouhan** [comment]
Ya that would be a better approach

**Comment by sairajchouhan** [comment]
I guess closing the dropdown is not what we should look for because we are stopping the click propagation at the modal trigger so the menu is not getting closed, even though we clicked the menu item, any feedback on this?

```
    <DropdownMenuItem>
                      <Dialog>
                        <DialogTrigger asChild>
                          <Button
                            onClick={(e) => {
                              e.stopPropagation();
                            }}
                            color="warn"
                            size="sm"
                            className="w-full rounded-none font-medium"
                            StartIcon={Icon.Trash}>
                            {t("disband_team")}
                          </Button>
                        </DialogTrigger>
                        <ConfirmationDialogContent
                          variety="danger"
                          title={t("disband_team")}
                          confirmBtnText={t("confirm_disband_team")}
                          isLoading={props.isLoading}
                          onConfirm={() => {
                            props.onActionSelect("disband");
                          }}>
                          {t("disband_team_confirmation_message")}
                        </ConfirmationDialogContent>
                      </Dialog>
                    </DropdownMenuItem>
```

**Comment by PeerRich** [comment]
would need to see this in action, wanna open a PR?

**Comment by sairajchouhan** [comment]
Ya sure

**Comment by dezerb** [comment]
There are currently two solution used in project:
1. dropdown with ConfirmationDialogContent, like this place or remove team member

![image](https://user-images.githubusercontent.com/14241061/181906133-0e62c813-81f5-4fa0-bfe0-99af7d37f9e2.png)

2. or separate dialog with trigger button in dropdown like

![image](https://user-images.githubusercontent.com/14241061/181906166-ce6cb009-4979-454c-9f0c-f948227fa456.png)

the solution could be to prepare all dropdown like the second one, or add extra div like proposed PR

**Comment by PeerRich** [comment]
I don't know which alternative is better. I wonder how the team behind radix-ui is thinking of this (since both components are from radix)

**Comment by dezerb** [comment]
@PeerRich I found discussion na radix github page. The solution is pretty straight forward and doesn't duplicate properties for potential new modals 
https://github.com/radix-ui/primitives/discussions/1436
I updated the PR https://github.com/calcom/cal.com/pull/3607. When it be accepted the same should be done for the "remove member" modal

**Comment by PeerRich** [comment]
> @PeerRich I found discussion na radix github page. The solution is pretty straight forward and doesn't duplicate properties for potential new modals 
> 
> https://github.com/radix-ui/primitives/discussions/1436
> 
> I updated the PR https://github.com/calcom/cal.com/pull/3607. When it be accepted the same should be done for the "remove member" modal

we will review and merge on monday 🙏 thank you

**Comment by ivinayakg** [comment]
I would want to work on this.

**Comment by PeerRich** [comment]
go for it!

**Comment by PeerRich** [comment]
this has been fixed a while ago
