### ISSUE TITLE
REPLY_TO in hello@cal.com emails

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3572]
it turns out quite a few people reply to the transactional emails that we send them from hello@cal.com

We need to add the booking owners email to the REPLY_TO field when sending emails about bookings 

here's how:
https://stackoverflow.com/a/16194253

**Comment by gracebir** [comment]
means we are going to have a replyTo list of all attendee, right ?

**Comment by PeerRich** [comment]
> @PeerRich ,means we are going to have a replyTo list of all attendees, right ?

correct! is that possible?

**Comment by gracebir** [comment]
> correct! is that possible?
@PeerRich , I just figure it out

**Comment by mf1511** [comment]
@dosu, 
mate how to modify the reply-to email address on a selfhosted instance? 
With a instance that is deployed on Railway

Thank you
