### ISSUE TITLE
Team Availability not Pulling Through

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3575]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

For the collective links, I’ve noticed some issues around availability not being pulled through. Most recently with this link: https://cal.com/team/cal/sales (I checked the link as well and my availability is not being pulled)

![913d-4270-4df3-816219199b29 (1)](https://user-images.githubusercontent.com/16177678/181628258-b6f2fe24-e1a3-433d-82f2-76569e938268.png)

Someone was able to book a time outside working hour my availability:
![913d-4270-4df3-816219199b29](https://user-images.githubusercontent.com/16177678/181628285-6f46c27b-7cc7-4577-828b-2a21eb850816.png)

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by zomars** [comment]
- How is your availability set?
- Does this event has a custom selected calendar?
- What availability do you have set as default?
- Do you have any selected calendar?

**Comment by shirazdole** [comment]
@zomars my availability is set through my Working Hours in Availability:
<img width="1228" alt="CleanShot 2022-08-02 at 07 24 53@2x" src="https://user-images.githubusercontent.com/16177678/182436471-79123d7b-bd19-4397-8b2d-546712f53e32.png">

- I don't believe there is a custom selected calendar
- 
<img width="808" alt="CleanShot 2022-08-02 at 07 26 10@2x" src="https://user-images.githubusercontent.com/16177678/182436704-ddf82c3c-11fb-4987-94f7-4a1ee15e757d.png">

- By selected calendar do you mean this: 
<img width="1246" alt="CleanShot 2022-08-02 at 07 27 36@2x" src="https://user-images.githubusercontent.com/16177678/182436932-f2369861-81b7-45ca-a7c4-04c7c2f0aee1.png">

**Comment by sydwardrae** [comment]
confirming this is also happening with another customer 

<img width="753" alt="CleanShot 2022-08-02 at 16 55 55@2x" src="https://user-images.githubusercontent.com/94979838/182471904-fa5d3a96-5dad-442f-98d3-3c7af88e8edf.png">
