### ISSUE TITLE
Cal.com Status Page for Outages

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3577]
### Is your proposal related to a problem?

When there is an outage, we need a better way to communicate to our customers what's happening outside of replying to customer support emails or twitter.

### Describe the solution you'd like

Either a banner at the top of the website or a status page notifying customers that a certain feature is down and being worked on. This gives customers the ability to be aware of how they should also prepare for this issue too.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by shirazdole** [comment]
Flagging for @baileypumfleet @PeerRich and @Jaibles

**Comment by PeerRich** [comment]
we used to have a status page--no clue where that went @baileypumfleet ?

**Comment by PeerRich** [comment]
no need for design

**Comment by agustif** [comment]
In case we don't find the old one. Do we want to use an external FOSS package/app for this?
https://cachethq.io/
https://demo.cachethq.io/

**Comment by PeerRich** [comment]
> In case we don't find the old one. Do we want to use an external FOSS package/app for this? https://cachethq.io/ https://demo.cachethq.io/

i love FOSS -- happy to use one and host it at status.cal.dev (in case cal.com is down)

**Comment by PeerRich** [comment]
cachethq.io looks good -- @baileypumfleet wanna set this up under status.cal.dev?

**Comment by PeerRich** [comment]
@baileypumfleet was faster and already set up https://status.cal.com/
