### ISSUE TITLE
Can't Leave Embed Page

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3581]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Could not reproduce, but I was on the embed page, went away from my laptop, re-visited the page and I couldn't leave the embed page unless I refreshed. https://app.birdeatsbug.com/sessions/5b5dB1kfarq9hhv3JPzK5sVx_tTjdF_ApM8xK0b67m6G

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
can reproduce, neither ESC nor clicking outside the dialog closes it @hariombalhara

**Comment by hariombalhara** [comment]
This is known and reported in #3410.
Next.js update is responsible for this, need to figure out a workaround.

**Comment by PeerRich** [comment]
other dialogs close tho? 🤔

**Comment by hariombalhara** [comment]
Yeah, something weird going on here

**Comment by hariombalhara** [comment]
This is still in `main`, yet to go live to be considered closed.

**Comment by hariombalhara** [comment]
This is in production now
