### ISSUE TITLE
Cursor didn't show pointer when passing the dropdown

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#3594]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On preview page when I open the timezones dropdown the cursor doesn't show "pointer"

### Steps to Reproduce

1. Create a new event typr
2. Go to preview
3. Try to change the selected timezone

https://www.loom.com/share/e508412db357439fbf0239c8f064cbea

**Comment by PeerRich** [comment]
we're using react-timezone-select here, i think its better to open that issue here: https://github.com/ndom91/react-timezone-select/issues
