### ISSUE TITLE
Rescheduling an Opt-in booking bypasses opt-in and doesn't add rescheduled event to calendar

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3595]
### Issue Summary
An opt-in booking when rescheduled is automatically “accepted“ but doesn’t show up on the calendar (double jeopardy)

### Steps to Reproduce
1. Book an opt-in booking
2. Reschedule it to a different slot (date or time). Note that the rescheduled booking is accepted even if the initial booking wasn’t.
4. Check your calendar for the rescheduled time (not there)
5. The host can also still accept the original request and end up with two bookings in cal.

**Comment by PeerRich** [comment]
to clarify: a meeting that "requires confirmation" is an opt-in booking (old name) 

<img width="881" alt="CleanShot 2022-07-29 at 15 15 55@2x" src="https://user-images.githubusercontent.com/8019099/181768421-2ff234df-650b-4401-bb33-e4643f6ed18d.png">
