### ISSUE TITLE
Feature: Demo Zapier integrations

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3597]
Zapier has a template editor, we should predefine common zaps and show them somewhere in our product like betteruptime.com and others do:

<img width="1013" alt="CleanShot 2022-07-29 at 16 02 40@2x" src="https://user-images.githubusercontent.com/8019099/181776999-e98cc4af-09b4-4f7c-8a1b-e8d36ccb5bec.png">

## Templates:

- [ ] google sheets (add all events into google sheets as they come in)
- [ ] airtable (add all events into a base as they come in)
- [ ] gmail (send an email)
- [ ] close.com, hubspot.com, salesforce.com (add bookings to CRM based on email)
- [ ] todoist, asana, trello (add bookings as a todo)
-

**Comment by PeerRich** [comment]
@CarinaWolli do you wanna look into this? happy to help brainstorm some templates

**Comment by CarinaWolli** [comment]
Looks interesting, I'll take a look. I try to start with some simple ones like 'Send email with gmail when an event is created' or 'Adding an airtable record for created events'. @PeerRich Would be great if you could give some more suggestions on what templates you would think make sense! Or anybody else of course

**Comment by PeerRich** [comment]
> Looks interesting, I'll take a look. I try to start with some simple ones like 'Send email with gmail when an event is created' or 'Adding an airtable record for created events'. @PeerRich Would be great if you could give some more suggestions on what templates you would think make sense! Or anybody else of course

added some ideas to the original issue

**Comment by PeerRich** [comment]
hey @CarinaWolli is the info i provided enough or do you need more context?

**Comment by CarinaWolli** [comment]
> hey @CarinaWolli is the info i provided enough or do you need more context?

@PeerRich  I think that's enough 👍 I just started preparing the first templates. I'll let you know if I end up needing some more context

**Comment by PeerRich** [comment]
EPIC

we should add them to our app, too!

**Comment by PeerRich** [comment]
EPIC

we should add them to our app, too! 

I'll open a new ticket to add those cards for each template in our app

**Comment by jordanurbs** [comment]
Just curious, I can't seem to find the answer anywhere--is it possible to use these Zapier templates with a self-hosted Cal.com installation? Or only using the cal.com service itself?

**Comment by CarinaWolli** [comment]
> Just curious, I can't seem to find the answer anywhere--is it possible to use these Zapier templates with a self-hosted Cal.com installation? Or only using the cal.com service itself?

These templates are using the official Cal.com zapier integration, so they won't work on a self-hosted instance. Self-hosters would need to create there own zapier integration
