### ISSUE TITLE
Where are you publicly disclosing that the stripe integration collects a fee?

### ISSUE THREAD

**Issue by zeluspudding** [calcom/cal.com#3601]
As mentioned in [Stripe payments fees sometimes are of 100%](https://github.com/calcom/cal.com/issues/2888#issue-1249661991) and shown in [seed-app-store.ts](https://github.com/calcom/cal.com/blob/1be5510c5ea6c17a8ae80b9ece1a2855d9bc23be/packages/prisma/seed-app-store.ts):

```
    await createApp("stripe", "stripepayment", ["payment"], "stripe_payment", {
      client_id: process.env.STRIPE_CLIENT_ID,
      client_secret: process.env.STRIPE_PRIVATE_KEY,
      payment_fee_fixed: 10,
      payment_fee_percentage: 0.005,
      public_key: process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY,
      webhook_secret: process.env.STRIPE_WEBHOOK_SECRET,
    });
```
we see that **Cal.com, Inc** is collecting a Stripe Connect fee off of self hosted installations of cal.com installed from this repo. Where is the disclosure in your docs indicating this is happening? I can't seem to find it in any readme or even on your [commercial pricing page](https://cal.com/pricing?saas). Is this disclosed in the app? In my mind this fee should be made clear to users.

**Comment by zomars** [comment]
@zeluspudding as you can see on the lines before the ones you posted:

https://github.com/calcom/cal.com/blob/1be5510c5ea6c17a8ae80b9ece1a2855d9bc23be/packages/prisma/seed-app-store.ts#L219-L233

You need to set your own Stripe keys as we don't share our own. And only then, that will be added to your DB App keys. We don't share our Stripe keys for obvious reasons and there's no way as of today that self-hosted users can access our keys if we never share them.
