### ISSUE TITLE
Bug: O365 Availability Not Shown in Links (but in troubleshooter) - SELF HOSTED

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3610]
### Discussed in https://github.com/calcom/cal.com/discussions/3541

<div type='discussions-op-text'>

<sup>Originally posted by **mzocher-gl** July 27, 2022</sup>
We are enterprise users of cal with a self hosted instance on a virtual Ubuntu 20.04 server (Node v16.16.0, disk has 13gb free)

Since we bumped up to the 1.7.x branch, our booking links are showing full availability, even though the troubleshooter shows that there are appointments that would impact availability.  When you go through the public booking process to the end, the user gets an error that the appointment could not be booked.  This problem happens even now with 1.8.3.

Things I've tried to fix:
- Disconnected/reconnected my Office 365 calendar (making sure that a calendar is selected)
![image](https://user-images.githubusercontent.com/62898546/181147329-ba1925b1-4306-48d8-bb20-3116a58001a4.png)
- Manually changing my booking types to save events on said O365 calendar
- Tried different browsers (latest Chrome, Firefox, Edge Chromium)

All times are CDT (UTC -5).  You can see that I have blockers at 10a, 11a, and 11:30a for 7/29/2022:
![image](https://user-images.githubusercontent.com/62898546/181146472-dd4946d4-a3d2-487b-9a9a-842b3e6af9c4.png)

And here I show all times are available:
![image](https://user-images.githubusercontent.com/62898546/181146743-4cf040c9-d471-44bf-9327-23f7f1a528b7.png)
You can view my availability page at https://book.gravislaw.com/mzocher/30min?date=2022-07-29 and try looking for meeting times at 10a CDT (I have a standing meeting each day then, so it should never be available)

Running in Yarn Dev i didn't see anything in my console.  The browser showed this error:
`_app-9520180fb81f86eb.js:1  << query #18 viewer.public.slots.getSchedule Object
(anonymous) @ _app-9520180fb81f86eb.js:1
(anonymous) @ _app-9520180fb81f86eb.js:1
p @ _app-9520180fb81f86eb.js:1
(anonymous) @ _app-9520180fb81f86eb.js:1
onDone @ _app-9520180fb81f86eb.js:1
done @ _app-9520180fb81f86eb.js:1
n.cancel @ _app-9520180fb81f86eb.js:1
t @ _app-9520180fb81f86eb.js:1
cancel @ _app-9520180fb81f86eb.js:1
t.removeObserver @ _app-9520180fb81f86eb.js:1
n.updateQuery @ _app-9520180fb81f86eb.js:1
n.setOptions @ _app-9520180fb81f86eb.js:1
(anonymous) @ _app-9520180fb81f86eb.js:1
ei @ framework-dbb4adbd2655d20c.js:1
ws @ framework-dbb4adbd2655d20c.js:1
us @ framework-dbb4adbd2655d20c.js:1
jl @ framework-dbb4adbd2655d20c.js:1
(anonymous) @ framework-dbb4adbd2655d20c.js:1
ks @ framework-dbb4adbd2655d20c.js:1
rs @ framework-dbb4adbd2655d20c.js:1
S @ framework-dbb4adbd2655d20c.js:1
T @ framework-dbb4adbd2655d20c.js:1
`
</div>

**Comment by alannnc** [comment]
This problem should be solved on v1.8.4
