### ISSUE TITLE
Improve docs around setting up apps

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3624]
Explain step by step how to set up all apps. One page per app in developer.cal.com 

- [ ] https://github.com/calcom/cal.com/discussions/3623
- [ ] https://github.com/calcom/cal.com/discussions/3622

**Comment by PeerRich** [comment]
is the readme still up to date? https://github.com/calcom/cal.com/blob/main/README.md

lets move each app into one subpage in a developer.cal.com subpage

**Comment by PeerRich** [comment]
I wonder if its possible to have the apps in the setup wizard, too? @leog

**Comment by leog** [comment]
Beyond possible, @joeauyeung did it already @PeerRich 😆 
I guess this issue is still relevant, I created the [HubSpot one already](https://docs.cal.com/deep-dives/apps/hubspot)
