### ISSUE TITLE
Improve design of reminder email

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3639]
### Issue Summary

Improve design of reminder email: 

<img width="591" alt="Screenshot 2022-08-02 at 00 27 35" src="https://user-images.githubusercontent.com/30310907/182291724-78e476c4-d837-45af-b784-afaff220090a.png">

**Comment by PeerRich** [comment]
awesome!

**Comment by PeerRich** [comment]
very clean, nothing fancy
