### ISSUE TITLE
IFrame embed doesn't deal with height well

### ISSUE THREAD

**Issue by ColinChartier** [calcom/cal.com#364]
When you use the iframe embed, you basically just get the "regular page" embedded, which has a grey background with a foreground widget.

It'd be nice to have a query parameter like ?embed=true that made the widget be properly sized (100% width) so that the parent iframe could be set to an appropriate height.

It'd also be nice if the embed page could emit 'recommended height events' so that the parent iframe could automatically resize

**Comment by PeerRich** [comment]
Hey Colin, thank you for your issue. We're reworking the embed right now! Hoping to launch v.1.0 release candidate within the next 30 days!

**Comment by baileypumfleet** [comment]
Good point. As Peer said, we will be reworking the embed stuff
