### ISSUE TITLE
cannot reschedule unconfirmed events in the past

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#3641]
### Issue Summary

If a booking is made which needs confirmation, but is not confirmed before the time of the event passes, it cannot be rescheduled.

### Steps to Reproduce

1. Configure an event type which requires confirmation prior to booking
2. Someone requests a booking using this event type
3. Ignore request until time of booking passes
4. Observe that booking appears in the `Past` tab, but is permanently stuck there and cannot be rescheduled:

![image](https://user-images.githubusercontent.com/100738/182364910-33be4fd2-7ebd-4525-a2c4-6c7964381146.png)
 
### Expected behaviour

I would expect to have options which are similar to the ones available for bookings in the `Upcoming` tab:

![image](https://user-images.githubusercontent.com/100738/182365360-82136e9c-454c-48e6-9ba9-8d1faed5140e.png)

The motivation is that if someone has put in the effort to try and book my time, and I didn't respond to their request quick enough, I want to make it up to them by working with them to find a new time.  This is much preferable to requiring them to start the booking process over from scratch, which would have disadvantages:

1. It would require me to message them somehow outside of cal.com to explain what happened and ask them to rebook.
2. The consequent rebooking would create a second set of unrelated emails in both parties' inboxes.

**Comment by PeerRich** [comment]
fair point. this is something I had on my mind for a while now. lets get this done, maybe before 2.0. will cycle back with the team

**Comment by dallenpyrah** [comment]
I started taking a look at this issue yesterday, I've got the feature working in my system. I will be creating a PR tonight to be looked at.
