### ISSUE TITLE
event-types group-hover of icons not working

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3642]
somehow only the "preview link" icon is behaving correctly:

https://user-images.githubusercontent.com/8019099/182370312-95d045c3-94b0-49b3-9f9e-d7a92088091e.mp4

**Comment by Udit-takkar** [comment]
so you want something like this ? 

https://user-images.githubusercontent.com/53316345/182676911-930b0797-11fe-44d5-9c1b-71a76acee835.mov
