### ISSUE TITLE
Cannot read properties of undefined (reading 'map') error with Outlook 365

### ISSUE THREAD

**Issue by sydwardrae** [calcom/cal.com#3647]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am getting this error when trying to install/connect Outlook 365 Calendar:
Algo salió mal, intente volver a conectar su calendario con todos los permisos necesarios
Cannot read properties of undefined (reading 'map')

### Steps to Reproduce

1. Tried to connect Outlook Calendar 
2. Got error message Cannot read properties of undefined (reading 'map')

**Comment by alannnc** [comment]
Gonna take a deep dive on this later, I think it's unrelated to newest patch for availability and it's more on the installation side.

**Comment by sw506** [comment]
Can confirm, same issue for us, happened right after the update from 1.8.3 to 1.8.4.

**Comment by PeerRich** [comment]
> Can confirm, same issue for us, happened right after the update from 1.8.3 to 1.8.4.

we're already working on a fix for outlook @joeauyeung

**Comment by joeauyeung** [comment]
Should be fixed with #3698

**Comment by alannnc** [comment]
No longer being reported to my knowledge.

**Comment by zaheerahmad33** [comment]
I am getting the error!!!
