### ISSUE TITLE
Setup Wizard Not Pulling Timezone

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3654]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a user joins Cal.com, they go through a set-up wizard, part of that set-up wizard is Step 1 selecting your timezone. Currently, it doesn't auto-pull my timezone based on my location (no VPN running) 
<img width="1055" alt="CleanShot 2022-08-02 at 09 41 02@2x" src="https://user-images.githubusercontent.com/16177678/182459766-59bdbe9b-6cc3-4016-8762-b01d24e9b36f.png">

### Steps to Reproduce

1. Create a new account
2. Navigate to the first step and check to see if your timezone pulls through or not

Solution: Pull through the correct timezone (HST)

### Technical details

- Brave browser, Macbook pro MacOS Monterey

**Comment by emrysal** [comment]
If someone is interested in picking this up: `dayjs.tz.guess()` is your friend 👍

**Comment by Udit-takkar** [comment]
@emrysal can you assign it to me?

**Comment by PeerRich** [comment]
> @emrysal can you assign it to me?

assigned

**Comment by MatheusBeniniF** [comment]
I'm already working on this issue, just with a problem to set the user to check if the code I made is right
