### ISSUE TITLE
Event Type not updating/saving when "Redirect on booking" is used 

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#3659]
### Issue Summary

Event Type not updating/saving when "Redirect on booking" is used.

### Steps to Reproduce

https://user-images.githubusercontent.com/2770597/182472212-e9cb0fe7-957d-4ad2-b158-fe922d9fd559.mov

### Technical details

- Firefox 103.0.1
- Node.js version v16.16.0
- cal.com selfhosted v1.8.4
- CalDAV-Server: Radicale 3.1.8

**Comment by Toledodev** [comment]
Hey @bhopmann, I checked here and this error did not occur, try to update your main branch

**Comment by Toledodev** [comment]
Is working normally https://www.loom.com/share/787e21f1b7cb4c33b0720141d0a5605e

**Comment by bhopmann** [comment]
It seems to have been fixed with https://github.com/calcom/cal.com/commit/53de4ddaafe3baf34b452247dc268b5da8a3b81c
