### ISSUE TITLE
BUG: Buffer Times Not Working

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3662]
### Issue Summary

If I put a buffer for an hour before an event and hour after the event. The buffer did not work for before the event, but it created a buffer TWO HOURS after the event. https://www.loom.com/share/61dfcc80a8bc46bba6567ba92404261c

![buffer1](https://user-images.githubusercontent.com/16177678/182480288-f05b3460-6800-4b76-ac3b-f0767ac816b5.png)
![buffer2](https://user-images.githubusercontent.com/16177678/182480293-a8118e27-219a-4293-bbb7-e811cd029e32.png)
<img width="793" alt="buffer 3" src="https://user-images.githubusercontent.com/16177678/182480300-b40a93fe-38dd-43da-96b1-64ed14617423.png">

### Steps to Reproduce

1. Add buffer times to your event type
2. Create an event 
3. Check to see if buffer times are being pulled around that event

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Another customers if facing issue as well. See [HelpScout #1127](https://secure.helpscout.net/conversation/1965606618/1127/)

[Twist thread](https://twist.com/a/195135/ch/554218/t/3666113/)

**Comment by shirazdole** [comment]
cc @zomars @emrysal

**Comment by GlitchWitch** [comment]
I'm running into the same issue.
As an example, I have my cal.com availability set for 13:30-15:30 on Monday.
I have a single meeting in my linked Google calendar for 14:00-14:30 on Monday.
My cal.com event type has a buffer time of 30 minutes before and 60 minutes after.
However my cal.com calendar show's a single meeting spot available for 13:30.
