### ISSUE TITLE
Can't "Request reschedule" from a team event 

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3668]
### Issue Summary

This happened with a teams link. Not sure if it's the case with a regular event.

### Steps to Reproduce

1. Book an event from a teams link
2. Try request that the booker reschedule the event

https://user-images.githubusercontent.com/4536123/182721011-b9228c6d-0574-4551-80bb-effeaebd8d42.MOV

**Comment by jjromary** [comment]
Hi, @Jaibles! You are trying to upload the video but it has not been uploaded. Can you try uploading again?
