### ISSUE TITLE
Error when connecting calendar `prisma.credential.create()` invocation - same issue on docker

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#3673]
Hey,

when I try to add caldav it throws me the following in the logs: 
`prisma:warn `rejectOnNotFound` option is deprecated and will be removed in Prisma 5. Please use `prisma.user.findFirstOrThrow` method instead
17:24:21.532 timeZoneName ERROR Could not add this caldav account
 Error
Invalid `prisma.credential.create()` invocation:

  Foreign key constraint failed on the field: `Credential_appId_fkey (index)`
details:
{
  code: 'P2003',
  clientVersion: '4.1.0',
  meta: {
    field_name: 'Credential_appId_fkey (index)'
  }
}
error stack:
• index.js:28658 handleRequestError
    node_modules/@prisma/client/runtime/index.js:28658:13

• index.js:28640 request
    node_modules/@prisma/client/runtime/index.js:28640:12

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29618 consumer
    node_modules/@prisma/client/runtime/index.js:29618:18

• index.js:29639 _request
    node_modules/@prisma/client/runtime/index.js:29639:16
`

Any ideas on this? Its a fresh install on Ubuntu 20 with node 16.

**Comment by alishaz-polymath** [comment]
hi @timowevel1 
Please try and fetch the latest main and then test if the issue persists. Do let us know your findings please.
