### ISSUE TITLE
Missing apps

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#3674]
Hey,

I dont know if this may be related to the other issue I reported, but it doesnt show me any apps.
![image](https://user-images.githubusercontent.com/25285295/182660652-e752dc8d-4ad8-4dba-b2b1-59d4d53759f6.png)

E.g. the caldav app is missing. Also in the database there is no entry for it.

Thanks.

**Comment by Toledodev** [comment]
Hey @timololipop, on localhost you need to do an initial configuration to show the available apps

**Comment by PeerRich** [comment]
we'Re wokring on a more straight forward app wizard @leog is looking into this

**Comment by timololipop** [comment]
> Hey @timololipop, on localhost you need to do an initial configuration to show the available apps

Can you give me a hint which configuration?

**Comment by leog** [comment]
@timololipop take a look at https://github.com/calcom/cal.com#integrations and this file: https://github.com/calcom/cal.com/blob/main/.env.appStore.example

**Comment by timololipop** [comment]
So I need to configure google to get the caldav app? Caldav isnt working in the setup wizard when I try to add my nextcloud, thats my issue currently..

**Comment by leog** [comment]
> @leog So I need to configure google to get the caldav app? Caldav isnt working in the setup wizard when I try to add my nextcloud, thats my issue currently..

I see. Do you happen to have CalDav in your App table in the database?
![image](https://user-images.githubusercontent.com/467258/182675461-8e7902be-9e47-4e98-8e0d-6d4905645fb2.png)

**Comment by timololipop** [comment]
Is it correct like that?
![image](https://user-images.githubusercontent.com/25285295/182678726-d8b5fb2d-38c3-41ea-8c2b-b1e44a1b50a7.png)

**Comment by leog** [comment]
Yeah, everything seems to be OK from the database. Weird that you are not getting the available apps and just Cal.com Video. Is there any error in the browser or command line console?

**Comment by timololipop** [comment]
Getting some stripe errors, although I didnt configure anything with it
![image](https://user-images.githubusercontent.com/25285295/182686836-91cef4a0-b580-4e02-a55a-92659ec95ee4.png)

**Comment by timowevel1** [comment]
@leog Is there a list with all apps available and which slugs I need to add them etc?

**Comment by PeerRich** [comment]
@zomars is the seeder broken? i thought the seeder would add all apps to the DB

**Comment by fastbone** [comment]
same here ... fresh install ... pulled 3 hours ago

database table App only contains "daily-video"

**Comment by pbdco** [comment]
Same here, pulled 24hs ago

![image](https://user-images.githubusercontent.com/64397076/182842130-803d6638-874c-4b26-98da-46f8d8466f07.png)

**Comment by hariombalhara** [comment]
This should be fixed in https://github.com/calcom/cal.com/pull/3693

**Comment by hariombalhara** [comment]
This should be fixed in latest main. Please check.

**Comment by timowevel1** [comment]
Nothing changed, had setup a new instance with the latest, still only the video app

**Comment by hariombalhara** [comment]
@timowevel1 Did you take the latest main? or the latest tagged release?

**Comment by timowevel1** [comment]
I did git pull https://github.com/calcom/cal.com.
Yes will send the log soon

**Comment by fastbone** [comment]
everything fine for me again ....

git pull
yarn clean
yarn
yarn build
yarn run

all fine

**Comment by timowevel1** [comment]
@fastbone When do you feed the database?
yarn workspace @calcom/prisma db-deploy

**Comment by fastbone** [comment]
i was just updating so i didn't do it but typically after "yarn"

**Comment by timowevel1** [comment]
So you already hat these Apps in the database? I am doing a fresh install, no update

**Comment by fastbone** [comment]
> So you already hat these Apps in the database? I am doing a fresh install, no update

no ... but it worked without "yarn workspace @calcom/prisma db-deploy"

**Comment by timowevel1** [comment]
What I do:
git pull
yarn
yarn workspace @calcom/prisma db-deploy
yarn build

No apps

**Comment by timowevel1** [comment]
@hariombalhara 
`root@InvoiceNinja:/opt/cal.com/apps/web# yarn build
yarn run v1.22.19
$ next build
info  - Loaded env from /opt/cal.com/apps/web/.env
warn - axiom: Envvars not detected. If this is production please see https://github.com/axiomhq/next-axiom for help
warn - axiom: Sending Web Vitals to /dev/null
warn - axiom: Sending logs to console

./pages/api/auth/saml/token.ts
15:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./pages/api/auth/saml/userinfo.ts
47:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./pages/api/auth/setup.ts
24:45  Warning: 'res' is defined but never used.  @typescript-eslint/no-unused-vars

./pages/api/teams/[team]/invite.ts
109:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./pages/apps/[slug]/index.tsx
25:31  Warning: 'placeholder' is defined but never used.  @typescript-eslint/no-unused-vars

./pages/auth/sso/[provider].tsx
104:19  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./pages/event-types/[type].tsx
75:11  Warning: 'NFT' is defined but never used.  @typescript-eslint/no-unused-vars

./pages/getting-started.tsx
149:48  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion

./pages/settings/profile.tsx
128:48  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
129:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
130:45  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
131:54  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
132:46  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
133:52  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
134:64  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion

./components/Embed.tsx
1148:11  Warning: 't' is assigned a value but never used.  @typescript-eslint/no-unused-vars

./components/booking/pages/AvailabilityPage.tsx
376:5  Warning: React Hook useMemo has a missing dependency: 'timeFormat'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/eventtype/CreateEventType.tsx
10:10  Warning: 'WEBAPP_URL' is defined but never used.  @typescript-eslint/no-unused-vars

./components/ui/AvatarGroup.tsx
5:8  Warning: 'Avatar' is defined but never used.  @typescript-eslint/no-unused-vars

./components/ui/UsernameAvailability/PremiumTextfield.tsx
74:28  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
95:6  Warning: React Hook useEffect has missing dependencies: 'currentUsername', 'debouncedApiCall', and 'userIsPremium'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
106:6  Warning: React Hook useEffect has a missing dependency: 'userIsPremium'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/ui/UsernameAvailability/UsernameTextfield.tsx
40:28  Warning: React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead.  react-hooks/exhaustive-deps
58:6  Warning: React Hook useEffect has missing dependencies: 'currentUsername' and 'debouncedApiCall'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./components/webhook/WebhookDialogForm.tsx
60:6  Warning: React Hook useEffect has a missing dependency: 'form'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./lib/QueryCell.tsx
67:34  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
88:51  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
88:56  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
88:61  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
88:66  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
88:71  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
88:76  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./lib/hooks/useSlots.ts
191:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion

./lib/jackson.ts
22:21  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./lib/types/inferSSRProps.ts
3:35  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
5:35  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
7:48  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types

warn - The `@variants` directive has been deprecated in Tailwind CSS v3.0.
warn - Use `@layer utilities` or `@layer components` instead.
warn - https://tailwindcss.com/docs/upgrade-guide#replace-variants-with-layer

warn - The RTL features in Tailwind CSS are currently in preview.
warn - Preview features are not covered by semver, and may be improved in breaking ways at any time.
info  - Creating an optimized production build
warn  - Compiled with warnings

./pages/api/version.ts
Should not import the named export 'version' (imported as 'pjson') from default-exporting module (only default export is available soon)

info  - Collecting page data
[=   ] info  - Generating static pages (0/641)react-i18next:: You will need to pass in an i18next instance by using initReactI18next
No README.mdx provided for: dailyvideo
[=== ] info  - Generating static pages (533/641)Warning: data for page "/404" is 137 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data
info  - Generating static pages (641/641)
info  - Finalizing page optimization

Page                                            Size     First Load JS
┌ λ /                                           248 B           160 kB
├   /_app                                       0 B             160 kB
├ λ /[user]                                     7.3 kB          198 kB
├ ● /[user]/[type]                              690 B           358 kB
├ λ /[user]/book                                776 B           332 kB
├ ○ /404                                        2.99 kB         170 kB
├ ○ /500                                        2.03 kB         164 kB
├ λ /api/app-store/[...static]                  0 B             160 kB
├ λ /api/app-store/installed                    0 B             160 kB
├ λ /api/auth/[...nextauth]                     0 B             160 kB
├ λ /api/auth/changepw                          0 B             160 kB
├ λ /api/auth/forgot-password                   0 B             160 kB
├ λ /api/auth/reset-password                    0 B             160 kB
├ λ /api/auth/saml/authorize                    0 B             160 kB
├ λ /api/auth/saml/callback                     0 B             160 kB
├ λ /api/auth/saml/token                        0 B             160 kB
├ λ /api/auth/saml/userinfo                     0 B             160 kB
├ λ /api/auth/setup                             0 B             160 kB
├ λ /api/auth/signup                            0 B             160 kB
├ λ /api/auth/two-factor/totp/disable           0 B             160 kB
├ λ /api/auth/two-factor/totp/enable            0 B             160 kB
├ λ /api/auth/two-factor/totp/setup             0 B             160 kB
├ λ /api/availability/[user]                    0 B             160 kB
├ λ /api/availability/calendar                  0 B             160 kB
├ λ /api/availability/day                       0 B             160 kB
├ λ /api/availability/eventtype                 0 B             160 kB
├ λ /api/book/confirm                           0 B             160 kB
├ λ /api/book/event                             0 B             160 kB
├ λ /api/book/request-reschedule                0 B             160 kB
├ λ /api/cancel                                 0 B             160 kB
├ λ /api/collect-events                         0 B             160 kB
├ λ /api/cron/bookingReminder                   0 B             160 kB
├ λ /api/cron/downgradeUsers                    0 B             160 kB
├ λ /api/cron/workflows/scheduleEmailReminders  0 B             160 kB
├ λ /api/cron/workflows/scheduleSMSReminders    0 B             160 kB
├ λ /api/email                                  0 B             160 kB
├ λ /api/eventType                              0 B             160 kB
├ λ /api/import/calendly                        0 B             160 kB
├ λ /api/import/savvycal                        0 B             160 kB
├ λ /api/integrations                           0 B             160 kB
├ λ /api/integrations/[...args]                 0 B             160 kB
├ λ /api/integrations/stripepayment/webhook     0 B             160 kB
├ λ /api/intent-username                        0 B             160 kB
├ λ /api/me                                     0 B             160 kB
├ λ /api/schedule                               0 B             160 kB
├ λ /api/teams                                  0 B             160 kB
├ λ /api/teams/[team]                           0 B             160 kB
├ λ /api/teams/[team]/invite                    0 B             160 kB
├ λ /api/teams/[team]/membership                0 B             160 kB
├ λ /api/teams/[team]/profile                   0 B             160 kB
├ λ /api/teams/[team]/upgrade                   0 B             160 kB
├ λ /api/trpc/[trpc]                            0 B             160 kB
├ λ /api/upgrade                                0 B             160 kB
├ λ /api/user/[id]                              0 B             160 kB
├ λ /api/user/avatar                            0 B             160 kB
├ λ /api/user/me                                0 B             160 kB
├ λ /api/user/membership                        0 B             160 kB
├ λ /api/user/profile                           0 B             160 kB
├ λ /api/username                               0 B             160 kB
├ λ /api/version                                0 B             160 kB
├ ● /apps                                       2.83 kB         284 kB
├ ● /apps/[slug]                                5.63 kB         293 kB
├   └ /en/apps/daily-video
├ λ /apps/[slug]/[...pages]                     137 kB          452 kB
├   └ css/f90103d9ff04f242.css                  616 B
├ ● /apps/[slug]/setup                          899 B           161 kB
├ ● /apps/categories                            947 B           272 kB
├ ● /apps/categories/[category]                 1.41 kB         267 kB
├   └ /en/apps/categories/video
├ ○ /apps/installed                             3.63 kB         305 kB
├ λ /auth/error                                 3.3 kB          170 kB
├ λ /auth/forgot-password                       7.46 kB         339 kB
├ λ /auth/forgot-password/[id]                  4.01 kB         186 kB
├ λ /auth/login                                 9.42 kB         341 kB
├ λ /auth/logout                                3.52 kB         170 kB
├ ○ /auth/new (708 ms)                          281 B           160 kB
├ λ /auth/setup                                 7.1 kB          329 kB
├ λ /auth/signup                                5.93 kB         187 kB
├ λ /auth/sso/[provider]                        505 B           160 kB
├ ○ /auth/verify                                3.51 kB         170 kB
├ ○ /availability                               5.35 kB         280 kB
├ ● /availability/[schedule]                    4.66 kB         393 kB
├ ○ /availability/troubleshoot                  1.9 kB          268 kB
├ ● /bookings/[status]                          10.3 kB         428 kB
├   ├ /en/bookings/upcoming
├   ├ /en/bookings/recurring
├   ├ /en/bookings/past
├   └ /en/bookings/cancelled
├ λ /cancel/[uid]                               14 kB           220 kB
├ ○ /cancel/success                             3.24 kB         170 kB
├ λ /d/[link]/[slug]                            356 B           358 kB
├ λ /d/[link]/book                              434 B           332 kB
├ ○ /event-types                                11.8 kB         492 kB
├ λ /event-types/[type]                         47 kB           575 kB
├   └ css/ee19099814a1d4e3.css                  1.14 kB
├ λ /getting-started                            6.52 kB         434 kB
├ λ /payment/[uid]                              10.5 kB         204 kB
├ λ /reschedule/[uid]                           264 B           160 kB
├ ● /sandbox                                    2.77 kB         165 kB
├ ● /sandbox/Alert                              4.13 kB         166 kB
├ ● /sandbox/Badge                              3.22 kB         165 kB
├ ● /sandbox/Button                             4.31 kB         166 kB
├ ● /sandbox/form                               5.45 kB         181 kB
├ ● /sandbox/List                               4.53 kB         166 kB
├ ○ /sandbox/preview-error-page                 2.1 kB          162 kB
├ ○ /sandbox/RadioArea                          4.78 kB         164 kB
├ ○ /sandbox/test-async-error                   1.84 kB         161 kB
├ λ /sandbox/test-error                         1.51 kB         161 kB
├ λ /settings/admin                             2.98 kB         278 kB
├ ○ /settings/billing                           5.87 kB         272 kB
├ ○ /settings/developer                         9.48 kB         326 kB
├ λ /settings/profile                           10.1 kB         549 kB
├ ○ /settings/security                          5.38 kB         435 kB
├ ○ /settings/teams                             5.8 kB          414 kB
├ ○ /settings/teams/[id]                        15.9 kB         589 kB
├ ○ /settings/teams/[id]/availability           8.29 kB         509 kB
├ λ /success                                    37.9 kB         282 kB
├ λ /team/[slug]                                9.27 kB         366 kB
├ λ /team/[slug]/[type]                         358 B           358 kB
├ λ /team/[slug]/book                           434 B           332 kB
├ λ /video/[uid]                                36.5 kB         198 kB
├ λ /video/meeting-ended/[uid]                  3.71 kB         186 kB
├ λ /video/meeting-not-started/[uid]            3.75 kB         186 kB
├ ○ /video/no-meeting-found                     3.01 kB         170 kB
├ ○ /workflows                                  5.17 kB         335 kB
└ ● /workflows/[workflow]                       46.5 kB         377 kB
    └ css/f02696cf4de12297.css                  710 B
+ First Load JS shared by all                   160 kB
  ├ chunks/framework-dbb4adbd2655d20c.js        45 kB
  ├ chunks/main-0d294b9a94f7a9b8.js             35.6 kB
  ├ chunks/pages/_app-00545aaa6501dc94.js       75.8 kB
  ├ chunks/webpack-95917da3ff9a8fc8.js          3.21 kB
  └ css/5916373f9ee1906c.css                    16.5 kB

ƒ Middleware                                    34.4 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

Done in 277.61s.`

**Comment by hariombalhara** [comment]
Okay. I got the problem. You should run `yarn build` from the root of the repo. We use `turbo.json`which kicks in only when run from root.

**Comment by timowevel1** [comment]
That did the trick, thank you!

**Comment by timowevel1** [comment]
But still, the outlook app e.g. is missing

**Comment by fastbone** [comment]
> But still, the outlook app e.g. is missing

Did you add the according config records to .env?

**Comment by fastbone** [comment]
> > > But still, the outlook app e.g. is missing
> > 
> > 
> > Did you add the according config records to .env?
> 
> In my .env.example were no records about it, could you give me a quick hint where I find them? Thank you.

https://github.com/calcom/cal.com#obtaining-microsoft-graph-client-id-and-secret

**Comment by timowevel1** [comment]
> > > > But still, the outlook app e.g. is missing
> > > 
> > > 
> > > Did you add the according config records to .env?
> > 
> > 
> > In my .env.example were no records about it, could you give me a quick hint where I find them? Thank you.
> 
> https://github.com/calcom/cal.com#obtaining-microsoft-graph-client-id-and-secret

Do I need to run anything for that to appear?

**Comment by fastbone** [comment]
cd packages/prisma
yarn seed-app-store

restart

**Comment by timowevel1** [comment]
![image](https://user-images.githubusercontent.com/25285295/183903821-070b75e6-b492-4061-912f-ee026c7dc171.png)

Restarted, no outlook app. I think cal hates me. MS_GRAPH_CLIENT_ID and MS_GRAPH_CLIENT_SECRET is set.

**Comment by PeerRich** [comment]
reopening. @hariombalhara maybe you can give this a look?

**Comment by timowevel1** [comment]
![image](https://user-images.githubusercontent.com/25285295/183975656-0d6a218e-ce04-44d8-9521-6b2997a863a5.png)
Its in my db

**Comment by hariombalhara** [comment]
So, the situation so far is that apps are being seeded to DB. That was the first problem and it is taken care of.
Now, even though the Outlook App is in DB, it is not showing up in the App Store.

@timowevel1 Am I correct in my assessment of the situation right now?
If yes, can you tell me if there is any other app that is missing in your App Store but is there in [Cal.com App Store ](https://app.cal.com/apps)? I want to know this to find a pattern if there is any.

**Comment by timowevel1** [comment]
@hariombalhara It gives me a 404.
![image](https://user-images.githubusercontent.com/25285295/184083285-e505e2af-6725-4370-ab10-8641611efd2b.png)

Yes, you are correct.
These are the apps I see:
![image](https://user-images.githubusercontent.com/25285295/184083347-e8e78dc1-3a94-4dee-b931-066330736f48.png)

**Comment by hariombalhara** [comment]
Well, this is super strange. I tried adding office 365 env vars with random values and I can still see the app.

Can you give me the complete row for office365-calendar from DB?
It would really help if you can put logs at all places where it returns `notFound:true` here https://github.com/calcom/cal.com/blob/main/apps/web/pages/apps/%5Bslug%5D/index.tsx#L101

- We know that it's in DB
- We know that it's in filesystem(as it's committed in repo).

We need to know what else can cause this.

**Comment by timowevel1** [comment]
@hariombalhara 
I will try a complete reinstall later, maybe there went anything wrong. I will keep you updated.

**Comment by timowevel1** [comment]
A reinstall fixed it. So I guess there was anything wrong with the yarn build run

**Comment by timowevel1** [comment]
I already saw that somewhere else, but do I have to setup google when I just want to use caldav? Bc caldav doesnt work on my instance
________________________________

**Comment by hariombalhara** [comment]
@alishaz-polymath might know more.
