### ISSUE TITLE
[CAL-1424] Disable standard confirmation email in even type settings

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3680]
### Is your proposal related to a problem?

No

### Describe the solution you'd like

Possibility to disable the standard confirmation email in event type settings.

### Additional context

Requested by a user. He wants to set up his own confirmation email with workflows. 

<sub>[CAL-1424](https://linear.app/calcom/issue/CAL-1424/disable-standard-confirmation-email-in-even-type-settings)</sub>

**Comment by PeerRich** [comment]
<img width="858" alt="CleanShot 2022-08-04 at 12 32 53@2x" src="https://user-images.githubusercontent.com/8019099/182826519-dc0635fd-014a-4d5b-beee-c32e43798e86.png">
could be added as a checkbox in the new advanced settings:

**Comment by dezerb** [comment]
@CarinaWolli @PeerRich 
I prepared some proposal based on current design. There is additional flag saved od eventType object and according to them mail is or not sent to the attendee.  By default it's true.
https://github.com/calcom/cal.com/pull/3695/files

![image](https://user-images.githubusercontent.com/14241061/182870005-8beaf391-8205-444b-8fd9-46d6f35fdecb.png)

**Comment by PeerRich** [comment]
> @CarinaWolli @PeerRich 
> 
> I prepared some proposal based on current design. There is additional flag saved od eventType object and according to them mail is or not sent to the attendee.  By default it's true.
> 
> https://github.com/calcom/cal.com/pull/3695/files
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/14241061/182870005-8beaf391-8205-444b-8fd9-46d6f35fdecb.png)
> 
> 

i think this should be negated:

- [ ] "Don't send email confirmation"

with an explanation text

"Disable email confirmation in case you want to send your own custom emails"

**Comment by PeerRich** [comment]
we'll need to think harder on this, its not trivial and can cause a lot of issues for people who mistakenly check that box. no checkbox should ever turn of core parts of the product. that'll be a debugging nightmare for customer support. 

we will likely add this checkbox in workflows whenever you create an email alternative but haven't found a good way for the UI yet. 

we will revisit in october

**Comment by CarinaWolli** [comment]
The feature to disable our standard confirmation email got requested again (the user wants to send a customized confirmation email with workflows)

@Jaibles Should we add that? If yes, how? as @PeerRich mentioned, we want to avoid that users turn off emails by mistake

**Comment by PeerRich** [comment]
yeah i think we can add it. maybe when active put a small warning helptext below
