### ISSUE TITLE
Profile dropown not closing after clicking on it

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#3701]
### Issue Summary
After tapping profile icon when dropdown in open should close it.

### Steps to Reproduce

https://user-images.githubusercontent.com/53316345/182912184-5c8c0e94-332b-4fc4-a5ea-b69cf6a10989.mp4

**Comment by Udit-takkar** [comment]
weird thing. this is only happening in mobile view.  In desktop view `packages/ui/Shell.tsx` If i click on profile icon DropdownMenuContent onInteractOutside is called and closes the dropdown but in mobile DropdownMenuTrigger onClick is getting called right after it

**Comment by om-ray** [comment]
@Udit-takkar I cant seem to reproduce this

**Comment by Udit-takkar** [comment]
@om-ray use phone or select phone layout in dev tools . Just draging console side bar to left won't reproduce this bug

**Comment by om-ray** [comment]
I tried with phone mode from the console and on mobile, but i cant reproduce it

**Comment by Udit-takkar** [comment]
tried again. so it is happening when you doing it in quick succession

https://user-images.githubusercontent.com/53316345/183243318-6fff1158-5d4b-4cff-bce6-ba677effa275.mov
