### ISSUE TITLE
cancel booking buttons are not responsive

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#3702]
![image](https://user-images.githubusercontent.com/53316345/182912704-53f2c595-8980-4208-b504-5a8209939f6d.png)

### Steps to Reproduce
1) click on cancel on a booking

**Comment by Udit-takkar** [comment]
@Jaibles  can you tell how should the three buttons look in mobile view?

**Comment by PeerRich** [comment]
@Jaibles do we need "never mind" at all?

**Comment by MatheusBeniniF** [comment]
@PeerRich what do you think about this solution?
https://www.loom.com/share/fe67459f00a64775bd79cf72f8ae5cff

**Comment by PeerRich** [comment]
@Jaibles do we have mobile screens for this?

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/183512971-12205660-da89-485a-843e-a79730723490.mov

almost done
