### ISSUE TITLE
new triggers: after event has finished

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3708]
- "after event has finished"

for workflows:
<img width="434" alt="CleanShot 2022-08-04 at 22 10 10@2x" src="https://user-images.githubusercontent.com/8019099/182943394-63e2aefd-22de-461b-a65e-9c9e5f86625f.png">

and webhooks:
<img width="371" alt="CleanShot 2022-08-04 at 22 10 21@2x" src="https://user-images.githubusercontent.com/8019099/182943416-af2ba507-5a10-48e1-8771-f953fdb45e4a.png">

**Comment by PeerRich** [comment]
@CarinaWolli wanna add this? this would enable things like sending a follow up email or a survey or ask for a rating etc.

**Comment by CarinaWolli** [comment]
> @CarinaWolli wanna add this? this would enable things like sending a follow up email or a survey or ask for a rating etc.

@PeerRich Yes, just started working on the Zapier trigger ( #3357). I will implement the trigger for workflows and webhooks too 👍🏻
