### ISSUE TITLE
App: Vacation tracker

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3716]
a simple app that lets people go on vacation easier (from start to date) which blocks out the calendar (creates an all-day OOO event).

it would also enable "away mode" which already exists and temporally remove people from team event types

a team owner would be able to see vacation status of team members

**Comment by emrysal** [comment]
Date overrides enables all this in core; so not sure we need this 🤔

**Comment by PeerRich** [comment]
> Date overrides enables all this in core; so not sure we need this 🤔

I am not quite sure how that would work? 🤔 am I trippin

**Comment by emrysal** [comment]
So Date Override allows blocking out time on a specific date but only that date, non repeating - a Work Hour schedule is a weekly repeating block out time.

**Comment by PeerRich** [comment]
ok but what i refer to is an app that you just open and say "I am on vacation from 1th to 8th of September" and we do the rest

**Comment by PeerRich** [comment]
also 
> a team owner would be able to see vacation status of team members

is not covered by date overwrites is it?

**Comment by emrysal** [comment]
That's a number of date overrides under the hood, maybe discuss with @Jaibles if there is a significant enough improvement to UX in this regard, but this very much should still use the same underlying logic we use for date overrides - on hold until 1.9 is released? (As it will depend on that logic)

**Comment by PeerRich** [comment]
oh this one should be after 2.0 easily. not a priority
