### ISSUE TITLE
Account Creation Wizard not Working

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3722]
### Issue Summary

When creating an account there are numerous issues with the account creation wizard:

- Even though Name, About Me, and Timezone is entered, that does not pull through to the actual profile of the account.
- In some cases, once completing the account creation wizard, there is an error message presented to the user. If the user goes back, they'll be taken directly to their account — this is not a great experience.

[Link to Twist thread](https://twist.com/a/195135/ch/554218/t/3671992/) with Bird Eats Bug with confidential information

**Comment by shirazdole** [comment]
I believe @alannnc is tackling this

**Comment by alannnc** [comment]
I'm gonna close this, to my knowledge this was reported when we have an error on session with our magic link update. I can't no longer replicate this scenario.
