### ISSUE TITLE
[CAL-94] Hide Guest List for Cal.com Seats Feature

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3732]
### Is your proposal related to a problem?
When using the Seats feature on an Event Type, there should be a toggle button to hide the guest list from other guests. This is potentially a privacy issue for many companies who don't want the emails of their other guests shared. 

This issue is originally flagged by a customer in [HelpScout](https://secure.helpscout.net/conversation/1970079412/1166/) #1166, but when I was at On Deck, this would have been a big issue for me personally as well. 

_"We have created an event and we have kept a capacity of 50 seats. However, when user joins the event, an email is sent to each user with his email along with emails of other users who are joining this event.

This is a major privacy issue and we cannot share the email details of all users with the entire group. Is there an option to hide this information?"_

### Describe the solution you'd like

A checkbox that I can click to hide the guest list from other users. 
![CleanShot 2022-08-07 at 16 05 31@2x](https://user-images.githubusercontent.com/16177678/183324197-7d0dd89e-cd8a-481e-a695-b6bd7fef0e98.png)

At the very least, for now, there should be a disclaimer that the guest list is not hidden and that guests will see other users emails.

**Comment by shirazdole** [comment]
cc @emrysal I see you have Google Calendar (although this applies to most calendars probably) as an expertise on the sheet and tagging @alannnc for the event-type portion 

@Jaibles for design thoughts

**Comment by emrysal** [comment]
This work was completed.

**Comment by shirazdole** [comment]
Wooooooh!!
