### ISSUE TITLE
While going to edit whereby video location, the input isn't prefilled existing URL

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3733]
See this loom https://www.loom.com/share/9ed9afaaf2194f0a80e42ada1199c330

I expect https://whereby.com/hariom to be prefilled when I edited the location.

**Comment by PeerRich** [comment]
cc @sean-brydon

**Comment by sean-brydon** [comment]
Good spot - will pick this up at some point :) Thank you

**Comment by mocherfaoui** [comment]
hey @sean-brydon can you review my PR?
Thank you!

**Comment by SauravL3010** [comment]
I think this issue is fixed ? isn't it.

**Comment by hariombalhara** [comment]
Yeah it should be fixed
