### ISSUE TITLE
Location and team members not shown on /book page.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3734]
We should show location on /book page as well. There is enough space available and it is important information to be shown.
https://www.loom.com/share/3ff7282e622448f5b766048565e28a59

**Comment by hariombalhara** [comment]
cc @PeerRich @Jaibles

**Comment by om-ray** [comment]
@hariombalhara Could i work on this?

**Comment by hariombalhara** [comment]
@om-ray That would be awesome !!

I am just waiting on @PeerRich to confirm if it makes sense to implement it.

**Comment by om-ray** [comment]
Great, ill start working on it as soon as he responds

**Comment by PeerRich** [comment]
yes, this is a bug. also I believe we don't wanna show the link by default unless you check the box "display on booking page"

can you test that? 


<img width="305" alt="CleanShot 2022-08-08 at 10 37 51@2x" src="https://user-images.githubusercontent.com/8019099/183376340-d633bc89-4d1e-49db-afa8-d2300fd83132.png">

**Comment by om-ray** [comment]
@PeerRich I tested it and even when I checked the box "display on booking page" it still doesn’t show up on the /book page

https://www.loom.com/share/93c9a920e9a44386bc5f35b2bdad6105

**Comment by PeerRich** [comment]
@sean-brydon

**Comment by hariombalhara** [comment]
@om-ray That's the bug you need to fix. /book page doesn't show the location no matter what. The previous page has correct implementation.

Also, I found a similar issue which can be fixed together with it. For a team event, team members are also not shown on /book page
https://www.loom.com/share/eadc3370fdb040ff924cc961e431ceca?from_recorder=1&focus_title=1

**Comment by om-ray** [comment]
@hariombalhara Ok, I'll start working on it asap

**Comment by om-ray** [comment]
@PeerRich @hariombalhara Could I get a review on PR #3762?
