### ISSUE TITLE
Locations has the wrong display on AvailabilityPage

### ISSUE THREAD

**Issue by matheusmuniz03** [calcom/cal.com#3741]
### Issue Summary

The css for eventType.locations on the AvailabilityPage page is different from the others.

### Steps to Reproduce

Try to book a meeting that has a location and see that it is different from the others

![Captura de tela de 2022-08-08 09-18-36](https://user-images.githubusercontent.com/87545749/183416895-4ea70e81-25e9-4e58-b465-848a7cb8d1bd.png)

**Comment by Udit-takkar** [comment]
done. thanks for reporting this
