### ISSUE TITLE
Collective event where the attendees don't have any intersection in availability It should display as "Unavailable" but right now it just displays the availability of the first attendee

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#3746]
This is a great improvement but there's also a new flaw that you may be aware of. If there's a collective event where the attendees don't have any intersection in availability It should display as "Unavailable" but right now it just displays the availability of the first attendee.

Is still way better than we currently have. We may follow up this in another issue.

Great work as always @emrysal 🙏🏽

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/3742#pullrequestreview-1065738876_

**Comment by Jaibles** [comment]
Closed by https://github.com/calcom/cal.com/pull/3742#pullrequestreview-1065738876
