### ISSUE TITLE
/cancel  and /success page: Buttons too small for long languages (German)

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#3750]
Hey,

for me some buttons got the wrong size. The language is German.

/success page
![image](https://user-images.githubusercontent.com/25285295/183622887-e388dec5-28c6-4927-b2d3-3cbde6330049.png)

/success page
![image](https://user-images.githubusercontent.com/25285295/183623033-732a3909-8bab-4733-aad0-69729980ceef.png)

Same on official cal.com instance.

**Comment by Udit-takkar** [comment]
2nd image if i am not wrong is for add to calendar which has been fixed and merged but not pushed on production probably. https://github.com/calcom/cal.com/pull/3703

for 1st image i can't read the language but it looks it is this on success page

<img width="499" alt="Screenshot 2022-08-09 at 5 15 53 PM" src="https://user-images.githubusercontent.com/53316345/183639352-5e68e30e-ed4f-4849-99f0-abafee4c96f5.png">

this is not merged yet https://github.com/calcom/cal.com/pull/3748

**Comment by timowevel1** [comment]
@Udit-takkar It is german, got this wrong size on my selfhosted instance and on cal.com

**Comment by PeerRich** [comment]
we're currently redesignign this screen to make it work for more languages.🙏

**Comment by Jaibles** [comment]
Will be tackled in 2.0

**Comment by Jaibles** [comment]
Will be tackled in 2.0
