### ISSUE TITLE
Can't get dynamic group booking to work. "Unavaliable: Some of the users in the group have currently disabled dynamic group bookings"

### ISSUE THREAD

**Issue by isaiahdahl** [calcom/cal.com#3755]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I'm not even 100% sure if this is a bug or not because I can't find documentation on how this part of the tool is actually suppose to work. But I can't get a dynamic group booking to work.

I'm running 1.8.4 self-hosted on railway.app 

### Steps to Reproduce

Try going to https://cal.praisecharts.com/isaiah+devan 
The page loads this:
![CleanShot 2022-08-09 at 09 40 23](https://user-images.githubusercontent.com/23046374/183708856-f0e311f2-9945-4b63-871b-f84fd3ed7f77.png)

But we both have it turned on.

In searching for docs on if maybe I'm using the tool wrong I found this blog https://cal.com/blog/cal-v-1-5 where it references this example link: https://cal.com/peer+bailey Which also shows the same error. Which makes me think it's a bug.

### Technical details

When I hit the route for our instance. I see this in the logs
```
@calcom/web:start: Warning: data for page "/[user]" is 380 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
@calcom/web:start: See more info here: https://nextjs.org/docs/messages/large-page-data
```

**Comment by hussamkhatib** [comment]
That page seems to work.

**Comment by isaiahdahl** [comment]
Yea latest release works for me in my fork now too. 

Must have been fixed.
