### ISSUE TITLE
Improve rescheduling between 2 Cal.com users

### ISSUE THREAD

**Issue by andreasklinger** [calcom/cal.com#3763]
### Is your proposal related to a problem?

- A requester schedules an event using my cal.com link.
- I, as host, would like to reschedule.
- Currently i have to ask the requester themselves to reschedule via my cal.com reschedule link
- This is frustrating and disrespectful of their time
   - if rescheduling is short-notice (eg day before) its also frequently unreliable
   - forcing me to first cancel the event and then send an explanatory email

### Describe the solution you'd like

(this assumes the requester also has an cal.com account with a linked calendar)

- As a host i am able to reschedule an event as well
- I click on my reschedule link
- See my event-type availability but overlapped their availability
 

### Describe alternatives you've considered

- Using the requesters public cal.com links instead
- This would assume they have public links
- This would assume that the event type has no specifics that are relevant
   -  eg duration, zoom links, questionaire, etc
 
I think both assumptions make this a stop-gap solution at best

### Additional context

Done well this could create network effects for cal.com

**Comment by jdaviescoates** [comment]
I'm not sure what's happening for you, or maybe you've just not spotted this, but hosts can already reschedule, I do it all the time. You just go to your upcoming bookings https://app.cal.com/bookings/upcoming click on Edit and then on Reschedule booking:

![image](https://user-images.githubusercontent.com/2113743/211797934-eac8cdae-32cc-44f7-895a-76e6877741de.png)

**Comment by jdaviescoates** [comment]
Ah, but re-reading your issue in more detail it sounds like you'd like to automatically be able to reschedule based on their availability too, I guess that would be a nice feature request for teams who are all using cal, but it's not particularly clear from the issue title you used.

**Comment by zomars** [comment]
The title is a bit misleading. This is more about overlapping two Cal.com users availability when scheduling/rescheduling. Which would be nice to have.
