### ISSUE TITLE
2.0 Event Types Individual {View}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3764]
[Designs in Figma →](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A65854)

![Image](https://user-images.githubusercontent.com/4536123/185591785-3867fba5-45ff-4de5-a553-efa27baaa051.png)

**Comment by PeerRich** [comment]
this one is almost done, the button hovers are not implemented yet @sean-brydon

**Comment by sean-brydon** [comment]
This should be fixed - closing
