### ISSUE TITLE
2.0 Availability / Single - View & Edit which events it's "Active on" {New feature}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3775]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=14084%3A98429)

![Image](https://user-images.githubusercontent.com/4536123/185594236-aa754f68-fa17-470b-b523-5b8439ee7b6c.png)

**Comment by Jaibles** [comment]
@emrysal have you started on this or should we move to 2.1?

**Comment by PeerRich** [comment]
just talked to alex, yep – 2.1.

**Comment by keithwillcode** [comment]
@Jaibles Is this still valid?

**Comment by Jaibles** [comment]
@keithwillcode yes it's still valid but considering we've gone this long with out it let's just close.
