### ISSUE TITLE
2.0 Apps / App Store / Category {View}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3778]
[View in Figma →](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13429%3A85919)

![Image](https://user-images.githubusercontent.com/4536123/185594282-9d3b60f7-2404-4914-b264-a2cb66eea54e.png)

**Comment by PeerRich** [comment]
@leog are you working on this right?

**Comment by leog** [comment]
@PeerRich yes!
