### ISSUE TITLE
2.0 Apps / Installed Apps

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3780]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1440%3A65827)

![Image](https://user-images.githubusercontent.com/4536123/185592862-998bf670-4f1f-4f13-8435-26d056eda520.png)

**Comment by Udit-takkar** [comment]
@Jaibles  can you assign this to me?
