### ISSUE TITLE
2.0 Event Types / Embed {Flow}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3788]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A112136)

**Comment by Jaibles** [comment]
@agustif is this planned for 2.0?

**Comment by agustif** [comment]
Yes, finishing it up, will send PR for review soon! @Jaibles
