### ISSUE TITLE
2.0 Event Types with Team {View}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3790]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13574%3A90404)

![Image](https://user-images.githubusercontent.com/4536123/185591859-24e65c31-a9c0-49e7-bda8-96bea860bacd.png)

**Comment by sean-brydon** [comment]
https://github.com/calcom/cal.com/pull/3549 Implemented here
