### ISSUE TITLE
2.0 Workflows Empty State {View}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3793]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13385%3A113560)

**Comment by noobyogi0010** [comment]
@Jaibles I'm halfway to its implementation. I'll raise a PR against this issue.
Thanks!

**Comment by noobyogi0010** [comment]
@Jaibles I moved to a new system, and I'm trying to locally set up the project. But I'm getting the following error:

```
error - Cannot read properties of null (reading '1')
```

Any idea what might be the reason for this?
Thanks!
