### ISSUE TITLE
2.0 Sign in {View}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3796]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=15301%3A134828)

![Image](https://user-images.githubusercontent.com/4536123/185593144-05f2fd87-314f-40fb-a69e-fabd9d6185f2.png)

**Comment by JeroenReumkens** [comment]
I'll be picking this up. Either today or this weekend ✌️

**Comment by sean-brydon** [comment]
Thank you @JeroenReumkens  - I've just pushed some V2 changes to [forget password ](https://github.com/calcom/cal.com/pull/4327) that might be useful here.

**Comment by JeroenReumkens** [comment]
Cool, thanks @sean-brydon! I will make sure to pull in main once this has been merged 👍

**Comment by JeroenReumkens** [comment]
![Screenshot 2022-09-09 at 15 56 44](https://user-images.githubusercontent.com/2969573/189367019-8bc5099d-ac6e-4f0e-8105-fc6048482dd6.png)
@sean-brydon @Jaibles  Is there a process around updating translations? I'm now specifically looking at the "I don't have an account" text. Left is design, right is code. If I change this in EN, of course all the translations should get updated as well. So I was wondering what the process is for this 🙂

**Comment by sean-brydon** [comment]
To my knowledge we just add them to EN then we have a GitHub bot that does the rest? We ideally should have a cleanup of our translations in the future as a believe many of them are deprecated.

**Comment by Jaibles** [comment]
Thoughts on whether just the text "Forgot?" is enough?  I think it is since it's so close to the password field. Also if we can just ensure that text is vertically aligned with the label :)

**Comment by JeroenReumkens** [comment]
Haha, don't look at the design implementation yet! 😬  Lots of work to do still, haha. Already fixed the alignment of the forgot password indeed, it was hurting my eyes as well 😉 

For me "Forgot?" also makes a lot of sense. Could already implement that if everyone agrees 🙂

**Comment by JeroenReumkens** [comment]
Anyone who wants to follow on the progress, you find the WIP branch here: https://github.com/JeroenReumkens/cal.com/tree/feat/3796-new-ui-for-signin ;)

**Comment by PeerRich** [comment]
feel free to open a PR in DRAFT
