### ISSUE TITLE
2.0 Create Account {View}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3797]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=15301%3A134845)

![Image](https://user-images.githubusercontent.com/4536123/190342610-f6ab4a63-7517-4687-bb27-f2951a0be5d9.png)

**Comment by om-ray** [comment]
@Jaibles Could you assign this to me?

**Comment by alannnc** [comment]
Not required anymore.
