### ISSUE TITLE
No connected calendar badge appearing beside every event type

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#3799]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Currently no destination calendars are assigned to a specific event type so the "No connected calendar" badge is appearing beside every event type.

![image](https://user-images.githubusercontent.com/65426560/183908187-9a69d95f-c753-4259-9891-90ec6e53c773.png)

**Comment by timfee** [comment]
+1

<img width="453" alt="Screenshot_2022-08-15_15-08-48_GlF7sPGQ" src="https://user-images.githubusercontent.com/3246342/184726224-822ffc42-f2e1-4437-8d6a-fa2c78b9971d.png">

**Comment by PeerRich** [comment]
didnt we remove this @zomars ?

**Comment by zomars** [comment]
Seems like got replaced on prod deploy

**Comment by PeerRich** [comment]
oh dear. can we re-fix this? @zomars

**Comment by PeerRich** [comment]
i temporally removed this. its in `main` waiting to be merged into prod
