### ISSUE TITLE
invite title bug

### ISSUE THREAD

**Issue by tootshani** [calcom/cal.com#3802]
invite title comes out with template fields vs. customized
![Screenshot_20220810-013108_Calendar](https://user-images.githubusercontent.com/30983122/184006592-5258f624-633b-42ff-9f99-f1ef5ed11753.jpg)

**Comment by milospuac** [comment]
Hi there

To dynamically display the name of your attendee and you as a host it goes the other way around: {HOST/ATTENDEE}

**Comment by PeerRich** [comment]
this has been fixed a long time ago
