### ISSUE TITLE
Issues with number of occurrences of recurring events

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#3803]
### Issue Summary

1. Should show 5 here: 
<img width="475" alt="Screenshot 2022-08-10 at 16 07 54" src="https://user-images.githubusercontent.com/30310907/184010851-a4bc232a-86e3-4b35-97dd-5bcda1ce0977.png">

2. It should be every 2 weeks for 5 occurrences here: 
<img width="242" alt="Screenshot 2022-08-10 at 16 33 16" src="https://user-images.githubusercontent.com/30310907/184014612-62a19375-8c6e-42e5-ac8c-26e5f7731cb2.png">

3. Hovering over an unconfirmed recurring event does not show any dates:
<img width="237" alt="Screenshot 2022-08-10 at 16 35 03" src="https://user-images.githubusercontent.com/30310907/184015000-7b108297-6b08-43eb-823d-19075642e04f.png">

**Comment by Udit-takkar** [comment]
can you tell how to reproduce this?

It is displaying correct to me.

<img width="474" alt="Screenshot 2022-08-11 at 8 38 10 PM" src="https://user-images.githubusercontent.com/53316345/184166426-733b5df2-dfe0-4884-a7bb-397e289b9dcd.png">

**Comment by CarinaWolli** [comment]
> can you tell how to reproduce this?
> It is displaying correct to me.

1. Create an event type that repeats every week with max. 12 occurrences 
2. Book the recurring event with 5 occurrences 
3. Now my success page says: 
Every week for 12 occurrences, instead of every week for 5 occurrences


@Udit-takkar Let me know if you can reproduce it

**Comment by Udit-takkar** [comment]
Ok i am able to reproduce it now

**Comment by Udit-takkar** [comment]
for 2nd image i think the issue is it takes some time to get the actual count . when i scroll the count get updated to correct value


https://user-images.githubusercontent.com/53316345/184549915-449222f5-8f46-4200-b616-ff8fba94176c.mov

**Comment by Udit-takkar** [comment]
i don't get the 3rd one. how did you create an unconfirmed recurring event?
