### ISSUE TITLE
2.0 Event Types {Empty State}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3806]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=15302%3A117356)

**Comment by om-ray** [comment]
@Jaibles Could i work on this?

**Comment by sean-brydon** [comment]
@om-ray  hey Sorry, @om-ray I didn't see this issue/your comment before today. 

This issues is already being worked on  within the main PR for 2.0 https://github.com/calcom/cal.com/pull/3549.

**Comment by om-ray** [comment]
@sean-brydon Ah, that's fine, I'll look for another issue then. Thanks for letting me know!

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/pull/3549
