### ISSUE TITLE
[CAL-90] Event Types Single / Allow multiple physical locations

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3822]
Right now people can enter multiple video conferencing options and allow people to choose from them, but they can only add one physical location. People should be able to add multiple physical locations and allow the booker to choose.

![Image](https://user-images.githubusercontent.com/4536123/184340054-be2c4b5b-86a0-41b0-9897-71dc592731af.png)

![Image](https://user-images.githubusercontent.com/4536123/184340097-cfd5c9de-018d-4503-ab7d-3ef5f0603ca0.png)

**Comment by JohanForngren** [comment]
Also multiple links would be useful, that could enable integration of multiple unsupported video apps.

**Comment by Jaibles** [comment]
Customer request: Would be really useful if you could create multiple in-person locations that the attendee could choose from. For example, I could list 3 coffee shops that are in my area

**Comment by leventdeniz** [comment]
I'd like to work on this, if it's still unassigned

**Comment by Jaibles** [comment]
@leventdeniz go for it!

**Comment by leventdeniz** [comment]
I'll give it a go and let you know if any issues arise. Do I have to take the Ticket on gitstart? I don't have an account there.

**Comment by Jaibles** [comment]
@leventdeniz, nope ignore that.

**Comment by Jaibles** [comment]
@leventdeniz going to assume you've not started this? I'll hand it over if you've not had a chance.

**Comment by leventdeniz** [comment]
> @leventdeniz going to assume you've not started this? I'll hand it over if you've not had a chance.

Sorry, I did not start yet. If this is urgent assign someone else please.

**Comment by PeerRich** [comment]
reassigned @gitstart-calcom
