### ISSUE TITLE
Bug with Console on Deployment

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3826]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to finish setup for a deployment on console.app.com (step 2) there is an error message that prevents me from going further: "Cannot delete properly 'rejectOnNotFound' of #<Object>"

### Steps to Reproduce

@agustif has reproduced already

https://app.birdeatsbug.com/sessions/VeEuGID3TBDZ21wyohFkLcJKJ7c-FyEyQdjbQWL3Q4SF

[Twist thread](https://twist.com/a/195135/ch/554218/t/3689534/)

**Comment by shirazdole** [comment]
@agustif could you add lables please

**Comment by PeerRich** [comment]
@agustif do you know when this happens?

**Comment by agustif** [comment]
Hey this was due to a deprecation in prisma client!
Was fixed on this PR https://github.com/calcom/console/pull/27
