### ISSUE TITLE
Past bookings are cancellable 

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#3845]
i am able to cancel past bookings. is this a bug or expected behavior? 

https://user-images.githubusercontent.com/53316345/184550214-9dd61978-c6f0-47be-8bc7-d760e8387051.mov

**Comment by om-ray** [comment]
@PeerRich Is this a bug or should we be able to cancel past bookings?

**Comment by PeerRich** [comment]
a bug. but seems low priority
