### ISSUE TITLE
Canceled appointment doesnt get removed in outlook calendar

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#3849]
### Issue Summary

An appointment which got booked and canceled afterwards doesnt get removed from the connected outlook calendar.

### Steps to Reproduce

1. Book a meeting
2. Cancel the meeting
3. Check outlook calendar

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Appointment should get removed from the calendar, else it is very unreliable.

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will investigate this.

**Comment by timowevel1** [comment]
Any news on that? Will it get fixed in the next release? Its quite annoying :D 

Thank you.

**Comment by PeerRich** [comment]
> Any news on that? Will it get fixed in the next release? Its quite annoying :D
> 
> Thank you.

I've noticed this before. lemme find an engineer to fix this

**Comment by PeerRich** [comment]
moved to 2.1. unless @alannnc is avail to look at this
