### ISSUE TITLE
Improvement: Make locations dropdown searchable

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3852]
Locations dropdown is not searchable
![image](https://user-images.githubusercontent.com/1780212/184588967-b175bc57-182d-4a57-b6ff-70df68c6cbc1.png)

**Comment by JatinRanka** [comment]
@hariombalhara I would like to contribute to this issue.

**Comment by hariombalhara** [comment]
@JatinRanka sure go ahead
