### ISSUE TITLE
Collective checkForAvailability incorrect on self hosted

### ISSUE THREAD

**Issue by CodingRockz** [calcom/cal.com#3853]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

Individual availability and booking of 1-on-1 meetings are accurate based on individual availability. However when these individuals are part of a team and a team event is scheduled as a collective event, the group availability shows no output.

### Steps to Reproduce

1. Self Hosted from Main branch
2. Created 3 users with availability and completed onboarding
3. Added the three users to a new team
4. Created a event type with the team and made the Schedule type as Collective

Bug

The team availability is showing nothing, even when collective availability is true.

### Technical details

The debug output shows:
 10:45:57.692 timeZoneName DEBUG getSlots took 22.06039099767804ms and executed 31 times
 10:45:57.692 timeZoneName DEBUG checkForAvailability took 0ms and executed 0 times
10:45:57.693 timeZoneName SILLY Available slots: {"2022-08-01":[],"2022-08-02":[],"2022-08-03":[],"2022-08-04":[],"2022-08-05":[],"2022-08-06":[],"2022-08-07":[],"2022-08-08":[],"2022-08-09":[],"2022-08-10":[],"2022-08-11":[],"2022-08-12":[],"2022-08-13":[],"2022-08-14":[],"2022-08-15":[],"2022-08-16":[],"2022-08-17":[],"2022-08-18":[],"2022-08-19":[],"2022-08-20":[],"2022-08-21":[],"2022-08-22":[],"2022-08-23":[],"2022-08-24":[],"2022-08-25":[],"2022-08-26":[],"2022-08-27":[],"2022-08-28":[],"2022-08-29":[],"2022-08-30":[],"2022-08-31":[]}

![image](https://user-images.githubusercontent.com/108911973/184622603-805de187-f6f4-46dc-bcaa-1347bd639e8c.png)

**Comment by PeerRich** [comment]
i think this has been fixed a long time ago. can you try a new version?
