### ISSUE TITLE
2.0 Select / Datepicker {Component}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3855]
The simple datepicker (not the one from the public booking page)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13738%3A97458)

**Comment by PeerRich** [comment]
![Image](https://user-images.githubusercontent.com/8019099/185482671-1fe21da7-a6b7-4138-8e5a-9ce692d57f20.png)
