### ISSUE TITLE
NEW Team Availability Bug not Pulling

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3872]
### Issue Summary

I’m not sure if this is affecting more than just our team (I assume so?), but our collective team links are not pulling the proper availability from both parties. [See Loom here explaining the first use case.](https://www.loom.com/share/5155781941c74e9593b370b8aaefc89d) — https://cal.com/team/cal/shiraz

It’s also not pulling in the normal availability for these links:

https://cal.com/team/cal/sales
https://cal.com/team/cal/hiring
This one looks like it’s working: https://cal.com/team/cal/marketing
https://cal.com/team/cal/product

I checked it against individual team members’ availability:

https://cal.com/bailey/30min
https://cal.com/ciaran/design
https://cal.com/peer/30min
https://cal.com/sydney/30min
https://cal.com/shiraz/30min

To reiterate, I believe ALL are available for the slot. That’s why I checked each event type and ensured that there were mutual times available, but that isn’t pulling onto the collective event.

For example:
[cal.com/peer/30](http://cal.com/peer/30) - Peer is available at 7:00a PST on 9/15

[cal.com/shiraz/30min](http://cal.com/shiraz/30min) - Shiraz is available at 7:00a PST on 9/15

[cal.com/team/cal/shiraz](http://cal.com/team/cal/shiraz) (collective of Peer and Shiraz) - does not show availability at 7:00a PST on 9/15

See here for a real example: https://share.cleanshot.com/zGW55v

### Steps to Reproduce

1. Navigate to a collective link between two or more people
2. Check to see if all the mutual availability is being pulled 

[Twist Thread for Context](https://twist.com/a/195135/ch/554218/t/3684574/)

**Comment by shirazdole** [comment]
cc @zomars and @emrysal to look into potentially 🙏

**Comment by shirazdole** [comment]
This is not the same as this issue: https://github.com/calcom/cal.com/issues/3575

**Comment by CodingRockz** [comment]
I have also witnessed the same issue in my self hosted testing. The collective team slot logic is flawed.

**Comment by CodingRockz** [comment]
Please Note: I already reported this in #3853. In some instances the array return for the collective team event type is empty. Some cases, it is showing incorrect limited slots which seem to vary depending on who is first in the team, similar to what @shirazdole has stated here.

**Comment by Jaibles** [comment]
<img width="1548" alt="CleanShot 2022-08-17 at 09 12 55@2x" src="https://user-images.githubusercontent.com/4536123/185075671-8fc6e754-78e1-4dbe-8b16-0aad53bf024d.png">

**Comment by CodingRockz** [comment]
My investigation shows a flaw in the workingHours object return for Team.

For example in my case:

User 1 individual calendar returns -
WorkingHours [{"days":[1,2,3,4,5],"startTime":60,"endTime":540}]

User 2 individual calendar returns - 
WorkingHours [{"days":[1,2,3,5],"startTime":60,"endTime":450}]

Team Calendar where both User 1 and User 2 are in a collective Schedule -
WorkingHours [{"days":[2,3],"startTime":60,"endTime":540}]

Trying to now look further into the WorkingHours logic for Team
