### ISSUE TITLE
[CAL-98] Improve Payments Page for Infra Customers

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3875]
### Issue Summary

Infra customers cannot cancel their plan on their own. Currently, they can only cancel their plan by emailing the team. 

Can we add a billing page to the infrastructure page for customers to manage their payments?

**Comment by shirazdole** [comment]
cc @Jaibles as you think about the infra design

**Comment by joeauyeung** [comment]
What's the current flow of someone getting on the infra plan? I'm working on team billing and can probably tackle this next.

**Comment by Jaibles** [comment]
@shirazdole bump on @joeauyeung's question above. And how often does this issue arise right now? Trying to assess priority.

**Comment by shirazdole** [comment]
I actually think someone fixed this? People can cancel now, but I'm not sure of the flow @joeauyeung @Jaibles

**Comment by shirazdole** [comment]
Not a priority
