### ISSUE TITLE
BUG: TypeError cannot read properties of undefined….

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3882]
Receiving this error when visiting the App Store.
<img width="1450" alt="CleanShot 2022-08-17 at 08 29 03@2x" src="https://user-images.githubusercontent.com/4536123/185060484-c660e357-058e-4e51-8819-cb1fe7299f35.png">

Also experienced a similar error yesterday when on the settings page
<img width="1443" alt="CleanShot 2022-08-16 at 12 10 11@2x" src="https://user-images.githubusercontent.com/4536123/185060813-3c2f64e5-6cf1-42da-9ae9-3815f3d2bc52.png">

**Comment by PeerRich** [comment]
still ongoing?

**Comment by leog** [comment]
Can't repro, any special step before getting these errors @Jaibles?

**Comment by Jaibles** [comment]
@leog no unfortunately not. Can't reproduce today.
