### ISSUE TITLE
can't cancel dynamic booking link

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3884]
https://app.birdeatsbug.com/sessions/SC-Thth6y88nY1k1YqFx8qd_r8mo-VSUmeJtZW9ezxVD?isInstantReplay=true

getting a 500

**Comment by alishaz-polymath** [comment]
https://www.loom.com/share/9b54407fabe94b73b3b406dc5d59e4e6

Unable to re-create it. Tested a few times locally. Might as well not be related to Dynamic Booking links. 🤔

**Comment by alishaz-polymath** [comment]
Update: It did cancel the event, just returned 500 error on the page. My bet is an unexpected return or something failing after the event had already been cancelled.
