### ISSUE TITLE
2.0 Feature Promotion in App Sidebar {Component}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3901]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=16307%3A155271)

![Image](https://user-images.githubusercontent.com/4536123/185587092-78b344dc-36c7-40f2-a38a-594f55db5f30.png)

**Comment by PeerRich** [comment]
merged
