### ISSUE TITLE
Cal Video disappears after adding & removing it

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3903]
see https://www.loom.com/share/4005435b37264dc38c90c287a721dce1

**Comment by hariombalhara** [comment]
I think it's a scroll issue. User doesn't think the list is scrollable, but it is. Unless he tried to scroll it but it wasn't scrollable.

See my attempt https://www.loom.com/share/e30e680b381a4ee692367e582b60350b at seeing Cal Video

**Comment by hariombalhara** [comment]
Also, with a recent change, the list is searchable as well now. So, we can just type Cal Video and it would show
