### ISSUE TITLE
“add another calendar” button

### ISSUE THREAD

**Issue by sydwardrae** [calcom/cal.com#3907]
### Is your proposal related to a problem?

 this is definitely not intuitive at all I feel like. I just went in to see how to add another calendar on for an event type, and it took me 5ever to realize that I had to go to the app store, and add it from there.

### Describe the solution you'd like

even if it just reroutes to the calendar section of the app store there should be something under this category that says “add another calendar” or something similar

![image](https://user-images.githubusercontent.com/94979838/185662466-ef2c34a3-6532-4223-8237-b71031bb1793.png)

**Comment by PeerRich** [comment]
would it work if the first line is "Add another calendar" and link to https://app.cal.com/apps/categories/calendar ?

**Comment by PeerRich** [comment]
i'll pick this up

**Comment by PeerRich** [comment]
moved to 2.1 since we refactor the event-types page right now

**Comment by Jaibles** [comment]
![Image](https://user-images.githubusercontent.com/4536123/187879890-860d8c4d-e4b2-4bd7-a485-e3f96ee4fdfd.png)

**Comment by PeerRich** [comment]
added
