### ISSUE TITLE
team owner should see all team bookings in /bookings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3910]
pretty self explanatory

**Comment by Udit-takkar** [comment]
can i work on this ?

**Comment by PeerRich** [comment]
> can i work on this ?

sure go for it! 🙏

**Comment by Udit-takkar** [comment]
should the team owner be able to cancel/reschedule booking  (in which he is not an attendee) ?

<img width="1440" alt="Screenshot 2022-08-20 at 4 15 53 PM" src="https://user-images.githubusercontent.com/53316345/185742472-5b0ba8c9-ad95-4d29-a9ca-47d7b7d9c570.png">

**Comment by Udit-takkar** [comment]
or should we create another tab to display all the team bookings ?

**Comment by PeerRich** [comment]
> 1)should the team owner be able to cancel/reschedule booking (in which he is not an attendee) ?
> 
> <img alt="Screenshot 2022-08-20 at 4 15 53 PM" width="1440" src="https://user-images.githubusercontent.com/53316345/185742472-5b0ba8c9-ad95-4d29-a9ca-47d7b7d9c570.png">

I think it would be great to give team owners the control to make change to any team booking, whether they are involved or not. often the team owner is someone who doesn't do calls (an operator lets say)

I wouldn't add a new tab, but maybe use the `<Badge>Team</Badge>` component somewhere
