### ISSUE TITLE
Allow me to Uninstall Google Meet & Cal Video

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3915]
Right now there's two apps in my Installed Apps page (Google Meet & Cal Video) that I can't uninstall.  

Expectations
- To be able to to uninstall both.
- Cal Video to come pre-installed, but that I can uninstall it. 
- Google Meet to **not** come pre-installed

**Comment by PeerRich** [comment]
right now we cant. is this something a user asked?

**Comment by Jaibles** [comment]
No one asked. Would be nice if it was easy but not something we need to prioritise now.

**Comment by PeerRich** [comment]
the thing about google meet is, that you cant install it either. it comes with google calendar so its hard to give it the same props as something you can install and uninstall

**Comment by Jaibles** [comment]
Ahh... perhaps we could have something near the uninstall button to explain this. Will be less of an issue in 2.0 installed apps anyway. Right now any installed app takes up a lot of valuable real estate.

**Comment by PeerRich** [comment]
true we could visually hide them, yea
