### ISSUE TITLE
Outlook Calendar "all day event" not recognized as busy

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#3916]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Create a new "all day event" in Outlook for a desired day and check Cal if the day is available

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The day shouldnt be available anymore.

### Technical details

**Comment by milospuac** [comment]
Hi there

Thanks for reaching out. I just tried to reproduce it but it reflects in my availability correctly. 

Can you please make sure your all day event in outlook is marked as "Busy"?
<img width="1099" alt="Screenshot 2022-08-23 at 14 22 41" src="https://user-images.githubusercontent.com/97884287/186157003-de3b9989-7569-48e9-af97-875aa6e993f7.png">
