### ISSUE TITLE
2.0 use new color palette classes for dark mode booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3919]
<img width="1256" alt="CleanShot 2022-08-22 at 11 10 26@2x" src="https://user-images.githubusercontent.com/8019099/185884694-519deea5-58fc-4c81-bd05-827d7c4bbed1.png">

[View in Figma ](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1375%3A63696)

**Comment by sean-brydon** [comment]
Fixed already :)
