### ISSUE TITLE
2.0 Cancel a booking {flow} & {view}

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3920]
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=14383%3A105018)

![Image](https://user-images.githubusercontent.com/4536123/187392122-0d11731c-20af-4a7f-8c79-bf9d49dc5e03.png)

![Image](https://user-images.githubusercontent.com/4536123/185886695-d8ce6a8d-865e-4012-bc4f-ca6b17c34628.png)

**Comment by PeerRich** [comment]
this could be a component
