### ISSUE TITLE
reschedule unexpected error

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3928]
![image](https://user-images.githubusercontent.com/8019099/185983576-1ae8a236-a97e-4866-8367-65fc7e05b3fc.png)potentially after already rescheduled?

**Comment by Jaibles** [comment]
Also experiencing this issue

On first attempt:
<img width="840" alt="CleanShot 2022-08-25 at 09 43 11@2x" src="https://user-images.githubusercontent.com/4536123/186630690-5a6d5afb-f573-4356-961a-cf0c665058c8.png">

On second attempt:
<img width="1424" alt="CleanShot 2022-08-25 at 09 46 19@2x" src="https://user-images.githubusercontent.com/4536123/186630709-abeda6c1-f86c-4908-b001-1166b5e509a9.png">

**Comment by Jaibles** [comment]
it actually does reschedule - but I just get the error an no email confirmation or anything


![Image](https://user-images.githubusercontent.com/4536123/186663305-d4ab0fe6-49ce-401f-bd3a-350506adf0f0.png)
