### ISSUE TITLE
Hidden additional fields

### ISSUE THREAD

**Issue by hamletdev** [calcom/cal.com#3930]
### Is your proposal related to a problem?

I'm using the hosted version and I need to pre-fill a custom input field on the Cal react component.
I then want to capture that value from the payload in the "BOOKING_CREATED" webhook that fires after the event is scheduled. 

I could add an additional input field to the event type and pre-fill it, but this is not a field that I want to expose to the customer in the booking form.

### Describe the solution you'd like

It would be great to have an additional field of type: "hidden" available in the advanced event type settings.
Alternatively, having some input options on the component would be good.

Peer suggested adding a hidden checkbox in the additional field UI.

![IMG_7070](https://user-images.githubusercontent.com/109113454/186291009-3ebcc452-4638-4460-9828-2e5e1e8c7d3c.jpg)

### Describe alternatives you've considered

Exposing the field to the user. 
Currently I'm getting the value on the server in the webhook listener but I'd rather just pass it along to the Cal component and retrieve it from the payload.

### Additional context

Hidden fields are very commonly used across a wide range of verticals, for marketing and dev purposes.
Would be a great addition to the "consumer" side of the product!

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will look into this and will be considered for the next version

**Comment by owen-whalecard** [comment]
I am hoping this can be added as well.

**Comment by PeerRich** [comment]
> I am hoping this can be added as well.

yes we are already working on it 🙏

**Comment by emrysal** [comment]
@hamletdev I'm closing this as this is already possible (and would like to prevent people spending more time). Feel free to re-open if you believe your use-case cannot be achieved in the manner below.

The way I read your requirement is that you are looking to pre-fill some data from the booking form - for that reason we've got something called metadata as explained in the following video: https://www.youtube.com/watch?v=5MybtA2rdBU. As explained in the video, using `https://cal.com/rick?metadata[user_id]=123` you can send data, hidden to the user (except for in the URL - we can look into hiding that too but we didn't feel the need when developing this) to your backend through the webhook. 

Using a hidden field you could use this field to hardcode data into your user page, this is not exactly what metadata is used for but if you need to hardcode data into your user page we always thought there was no benefit to doing that over on the consumer side. What metadata was meant to do is forward UTM's and other data from a shareable link (for whichever purposes you desire).

**Comment by hamletdev** [comment]
Makes sense!

Would be a good one to chuck in the docs!

Thanks Alex

**Comment by PeerRich** [comment]
> @hamletdev I'm closing this as this is already possible (and would like to prevent people spending more time). Feel free to re-open if you believe your use-case cannot be achieved in the manner below.
> 
> The way I read your requirement is that you are looking to pre-fill some data from the booking form - for that reason we've got something called metadata as explained in the following video: https://www.youtube.com/watch?v=5MybtA2rdBU. As explained in the video, using `https://cal.com/rick?metadata[user_id]=123` you can send data, hidden to the user (except for in the URL - we can look into hiding that too but we didn't feel the need when developing this) to your backend through the webhook.
> 
> Using a hidden field you could use this field to hardcode data into your user page, this is not exactly what metadata is used for but if you need to hardcode data into your user page we always thought there was no benefit to doing that over on the consumer side. What metadata was meant to do is forward UTM's and other data from a shareable link (for whichever purposes you desire).

@alishaz-polymath can you add this to gitbook?

**Comment by sovetski** [comment]
I found this documentation: https://cal.com/docs/how-to-guides/bookings/how-to-hide-and-prefill-booking-question-in-embeds#step-1:-accessing-the-event-type-settings

But it does not work correctly, the hidden field is shown at the end when user confirm the last step, it should be hidden

**Comment by alishaz-polymath** [comment]
> I found this documentation: https://cal.com/docs/how-to-guides/bookings/how-to-hide-and-prefill-booking-question-in-embeds#step-1:-accessing-the-event-type-settings
> 
> But it does not work correctly, the hidden field is shown at the end when user confirm the last step, it should be hidden

Hey @sovetski can you share a loom or steps to recreate the issue please?

**Comment by rnqewmq** [comment]
can we add in this metadata for FORM_SUBMITTED trigger event? it doesn't seem to be working for me.
