### ISSUE TITLE
Unable to view connected calendars

### ISSUE THREAD

**Issue by timfee** [calcom/cal.com#3931]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Went to resolve "No default calendar connected" error message -- even though nothing changed and I don't think I should be seeing this message:
<img width="716" alt="Screenshot_2022-08-23_10-08-50_j1nSU9DU" src="https://user-images.githubusercontent.com/3246342/186230573-6033a704-f2e7-4f7e-81b9-8b3d31d66e38.png">

2. Page hung forever here -- see errors in the console.
![Screenshot_2022-08-23_10-08-44_EVajUjWV](https://user-images.githubusercontent.com/3246342/186230695-da351d95-bd01-45ed-a537-c29b662f52ad.png)

**Comment by timfee** [comment]
Note that the end-user booking an appt sees this:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/3246342/186231688-153467a6-b6d5-4d4e-b0ff-f1ea7f7afd0b.png">

**Comment by timfee** [comment]
This might be two issues.

w/r/t the error message -- Inside of each event type's "Advanced Settings" it was trying to use a default calendar called `tim@timfeeley.com` -- but there was no calendar by that name; the name is `Personal`. I'm not sure if I renamed it or something else happened, but it looks like it was trying to resolve that way?

**Comment by KrisKodira** [comment]
Same Issue here. I use an Apple Calendar and after connecting the apple calendar, the data doesnt get saved in the right way in the database. It must be saved in a JSON Format but for some reason calendso saves it as just the key
<img width="762" alt="image" src="https://user-images.githubusercontent.com/24395956/186257472-8faae6c6-6403-4279-aaf3-5bef75d321a9.png">

**Comment by PeerRich** [comment]
> Same Issue here. I use an Apple Calendar and after connecting the apple calendar, the data doesnt get saved in the right way in the database. It must be saved in a JSON Format but for some reason calendso saves it as just the key <img alt="image" width="762" src="https://user-images.githubusercontent.com/24395956/186257472-8faae6c6-6403-4279-aaf3-5bef75d321a9.png">

@alishaz-polymath you are looking a lot into CalDav (which Apple Calendar) is based off, wanna give this a try?

**Comment by PeerRich** [comment]
yyes, these are two issues. Closing this one. the "missing calendar" has been fixed, can you open the new ticket?
