### ISSUE TITLE
weird dark mode for react-select-dropdown

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3938]
@Jaibles do we have designs for dark mode dropdowns?

this looks odd right now
<img width="813" alt="CleanShot 2022-08-24 at 11 00 14@2x" src="https://user-images.githubusercontent.com/8019099/186376943-350f1e11-216f-48ce-af59-7312a34e3fea.png">

**Comment by Jaibles** [comment]
No we don't. We don't have a fully fledged dark mode yet. Just designs for the booking pages. I can work on this though.

**Comment by sean-brydon** [comment]
![CleanShot 2022-08-25 at 10 07 22](https://user-images.githubusercontent.com/55134778/186624030-72a4038e-020d-43b7-bfc8-6f37aa51100c.png)
I created some V2 designs for this yesterday :)

**Comment by PeerRich** [comment]
@sean-brydon wanna work on this?

**Comment by sean-brydon** [comment]
For sure will pick this up today @PeerRich

**Comment by alishaz-polymath** [comment]
@sean-brydon I'm currently trying to wrap up the Datepicker module, and I'll pick up the V2 Select next. Unless there's some form of urgent diversion, I will pick this up when I work on the Select 👍

**Comment by sean-brydon** [comment]
Should be fixed with new select component
