### ISSUE TITLE
Onboarding / Hide "Import from Calendly / Savvycal" until we get it work more smoothly

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#3941]
I just tested the Calendly importer in the onboarding process and I'm not sure any part of it worked. 

- The link to learn how to get your secret key is a broken link
- Availability doesn't copy over. I don't think is a bug, I don't think it ever did, but we should be clear what we're copying over and what we're not so you know
- My event types did not copy over.

Let's hide and make a task to fix this post 2.0

**Comment by PeerRich** [comment]
I'm picking this up @Jaibles @alannnc

**Comment by alannnc** [comment]
@PeerRich I've just uploaded a PR for this.
