### ISSUE TITLE
[CAL-250] routing forms .csv download needs a header

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#3948]
when clicking "download csv"
<img width="349" alt="CleanShot 2022-08-24 at 18 56 24@2x" src="[https://user-images.githubusercontent.com/8019099/186478070-a7a55d88-62b3-470a-acc8-d97b28711cc8.png](https://user-images.githubusercontent.com/8019099/186478070-a7a55d88-62b3-470a-acc8-d97b28711cc8.png)">

it'll give you a csv with this format:
<img width="565" alt="CleanShot 2022-08-24 at 18 56 07@2x" src="[https://user-images.githubusercontent.com/8019099/186478052-8367b64f-06a6-4dc2-952c-aaf3983dd9c6.png](https://user-images.githubusercontent.com/8019099/186478052-8367b64f-06a6-4dc2-952c-aaf3983dd9c6.png)">

whereas we need a format like this:

<table>
<tr>
<td> What Problem are you trying to solve?
<td> Do you plan to Self-Host?
<td> ..
<td> ..
<tr>
<td> I want to schedule sales calls
<td> True
<td> ..
<td> ..
<tr>
<td> Workout with a trainer
<td> True
<td> ..
<td> ..
</table>

the way to achieve this is just have the top row be the column name

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by hariombalhara** [comment]
The problem with that is the changing number of questions during the journey of response collection. 

If we can agree that whatever questions are there in the form at the moment, just show only those responses, this is simple to do. 

This means that, if a question was deleted from the form, it's collected data won't be available in CSV.

**Comment by PeerRich** [comment]
> The problem with that is the changing number of questions/columns during the journey of response collection.
> 
> If we can agree that whatever questions are there in the form at the moment, just show responses for those questions, this is simple to do.
> 
> This means that, if a question was deleted from the form, it's collected data won't be available in CSV.

oh i see. that's bad. how does other companies do that? how does typeform do this?

**Comment by PeerRich** [comment]
closing for now until people ask again

**Comment by hariombalhara** [comment]
Started work on this.
