### ISSUE TITLE
[CAL-77] Alarm system, sending broken integration email even on success

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#3949]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Broken integration emails for calendars were being sent to users even if their calendars were successfully updated.

**Comment by PeerRich** [comment]
do you wanna work on this @joeauyeung ?

**Comment by joeauyeung** [comment]
Since there's been a lot of PRs fixing bugs related to calendars but none solving this issue there must be something even deeper. @alannnc and I were going to tackle this after V2.0

**Comment by PeerRich** [comment]
moved to 2.1

**Comment by Jaibles** [comment]
@joeauyeung should I assign this to you then?

**Comment by PeerRich** [comment]
@alannnc you are on it, right?

**Comment by alannnc** [comment]
@PeerRich I believe I've already fixed this and then the code was commented because it was still failing. I will make some time to pay a revision to this for sure.

**Comment by alannnc** [comment]
Not being reported anymore.
