### ISSUE TITLE
Metamask Integration Broken

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#3950]
### Issue Summary

A user attempted to use the Metamask app integration for his booking page and users attempting to book with him received an error message that the feature is only for enterprise customers. 

However, only open source self hosters should receive that message, not SaaS Pro Customers. 

In addition, when a user tries to book, they receive another error message that the "return value is invalid" — could be a problem with an expired API key. 

### Steps to Reproduce

1. Navigate to a Cal.com booking link with a Metamask integration
2. Attempt to book with them
3. See if there is an error 

<img width="427" alt="CleanShot 2022-08-24 at 11 29 56@2x" src="https://user-images.githubusercontent.com/16177678/186495757-e428769d-cad5-4469-a292-1930c257eb4b.png">

<img width="988" alt="CleanShot 2022-08-24 at 11 28 21@2x" src="https://user-images.githubusercontent.com/16177678/186495363-ec919be4-bfc6-42fc-8ed5-ba1eb71a6ae8.png">

<img width="585" alt="604e-5857-6796-9ffee24a68bb" src="https://user-images.githubusercontent.com/16177678/186495289-0a0f3eda-9991-4902-a0f4-65eaa5f8f8a7.png">

**Comment by PeerRich** [comment]
we'll need to remove the current metamask app because it seems like their API has changed and we will move to rainbowkit instead https://www.rainbowkit.com/
