### ISSUE TITLE
[CAL-95] FR: make confirmation requirement dependent on notice threshold

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#3964]
### Problem description

Ideally, I would never check the `Requires confirmation` checkbox for any of my event types, since this just adds extra overhead to the booking process, and the whole point of cal.com is to make booking as low friction as possible:

![image](https://user-images.githubusercontent.com/100738/186641892-0ca5d21d-484e-4aa1-b796-b6b6a2283813.png)

However, currently I need to check it, because I want to allow people the _chance_ to book slots with me at short notice (e.g. 3 hours):

![image](https://user-images.githubusercontent.com/100738/186642203-3313499a-24bf-46fc-a3fd-c093865c2941.png)

but if I don't require confirmation then there is a risk that if someone requests a slot in 3 hours from now, I might be busy with other things and not notice the booking notification until after the slot - and of course a no show is embarrassing and unprofessional.

In contrast to this short notice scenario, if someone requests a slot at least 24 hours from now, I can be confident that I will notice the booking notification in time, therefore I don't need to play it safe by requiring a confirmation.

### Describe the solution you'd like

Extend the `Requires confirmation` to something like this:

![image](https://user-images.githubusercontent.com/100738/186785028-54bf1078-7a42-44d5-a232-d1d83222cca0.png)

In this example, if the booking is more than 24 hours away from the time it was created, no confirmation would be required, but if it's sooner than 24 hours, then confirmation would be required.

**Comment by PeerRich** [comment]
this is a really good idea! and also great visual!

**Comment by PeerRich** [comment]
we'll look into this for 2.1 version as 2.0 is already super packed. 2.1 is scheduled for 15th of October, is that ok @aspiers ?

**Comment by aspiers** [comment]
[**@PeerRich**](https://github.com/PeerRich) commented on [August 25, 2022 9:36 PM](https://github.com/calcom/cal.com/issues/3964#issuecomment-1227737417 "2022-08-25T20:36:41Z - Replied by Github Reply Comments"):
> we'll look into this for 2.1 version as 2.0 is already super packed. 2.1 is scheduled for 15th of October, is that ok [@aspiers](https://github.com/aspiers) ?

It's not (just) OK, it's amazing!! :stuck_out_tongue_winking_eye:  Thank you so much, I'm very excited for both 2.0 and 2.1! :heart:

**Comment by aspiers** [comment]
BTW I just realised that my mockup above should probably have also had a third radio button labelled `Never`.

**Comment by aspiers** [comment]
Updated the mockup to add the third radio button.

**Comment by sean-brydon** [comment]
Just created a design for the V2 version of this also :) Great idea @aspiers 

![CleanShot 2022-08-26 at 10 43 41](https://user-images.githubusercontent.com/55134778/186876873-95a14be3-d437-4ee7-8c5f-b8ecc8efaf00.png)

**Comment by aspiers** [comment]
Love it, that looks way better than my design!

**Comment by PeerRich** [comment]
very slick @sean-brydon

**Comment by Jaibles** [comment]
[Event type / Advanced 2.1 \[Requires Confirmation On\] - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=20%3A24769&t=FRUbeHSjntnsEpw9-1)
