### ISSUE TITLE
On EvenType creation with API call, the default availability is not being displayed.

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#3974]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On creation of EventType with an API call, the default availability is not reflect, thus it's displaying a 24/7 availability (Self-Hosted)

### Steps to Reproduce

1. Create a new EventType with ApiCall
2. Go to Event Types -> Preview the newly created Even Type
3. The availability is being displayed as 24/7, instead of displayed the default availability.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by emrysal** [comment]
@zomars I believe this is fixed now, but could you confirm?
