### ISSUE TITLE
fix/credential-details-apple-calendar-setup

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#3976]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I believe apple calendar uses apple ID which is always an email, we can improve our apple-calendar/setup page changing Username for Apple ID as label text. Also we can remove autocomplete on those fields.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/4461358/186777483-df2b1218-3bac-488a-910b-fd865c4b10f6.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/4461358/186777528-b5395dcc-11c3-4832-b74c-d83b4fcfd10e.png">

### Steps to Reproduce

1. Navigate to /apps/apple-calendar/setup
2. Found username and password field

**Comment by edgarallanglez** [comment]
picking this up to know the project.
