### ISSUE TITLE
Swap `getServerSideProps` to tRPC queries in /v2/settings pages

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#3978]
Follow up to #3874

- Let's try removing all `getServerSideProps` calls inside ALL pages in `apps/web/pages/v2/settings/...`
- This will allow us to statically load skeletons
- Since it's a dashboard we don't really need SSR here
- Let's migrate those calls into tRPC instead

> Let's take full advantage of tRPC here

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/3874#discussion_r955504389_

> Can we avoid using `getServerSideProps` over `tRPC` ?

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/3874#discussion_r955501631_

**Comment by joeauyeung** [comment]
I posed this question in Twist before but when would we want to use `getServerSideProps` vs tRPC then?

**Comment by zomars** [comment]
> I posed this question in Twist before but when would we want to use getServerSideProps vs tRPC then?

Almost never 😅

Only for very specific use cases when making a tRPC router wouldn't make sense, but I can't seems to think about a valid use case right now.

**Comment by Udit-takkar** [comment]
working on this 👍

**Comment by Udit-takkar** [comment]
Should close this issue. the PR has been merged.

**Comment by joeauyeung** [comment]
Fixed in #4484
