### ISSUE TITLE
Accept license prompt persists after updating environment variables

### ISSUE THREAD

**Issue by mitcharseneau** [calcom/cal.com#3979]
The prompt "Accept our license by changing the .env variable NEXT_PUBLIC_LICENSE_CONSENT to 'agree'." does not disappear after updating the environment variable NEXT_PUBLIC_LICENSE_CONSENT to agree on Heroku.

To reproduce:

1. Deploy cal.com using the "Deploy to Heroku" button on repo [README.md
](https://github.com/calcom/cal.com#readme)
2. Set NEXT_PUBLIC_LICENSE_CONSENT to "agree" in Heroku "Config Vars"
3. Log in as an administrative user
4. Prompt is displayed as shown below (unable to accept and dismiss)

https://user-images.githubusercontent.com/65558728/186790099-1fe2514b-b282-464b-9bb3-a56206111a35.mov

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will look into this

**Comment by zlwaterfield** [comment]
@zomars it looks like there is no logic to actually write to the .env file. Is there meant to be? Or should we just update the copy in the modal to say "You need to restart your server"?

**Comment by zomars** [comment]
> it looks like there is no logic to actually write to the .env file. Is there meant to be? Or should we just update the copy in the modal to say "You need to restart your server"?

Yeah the button is definitely misleading, this is a step that needs to be done manually. Also we cannot add logic for doing so since there are many self-hosted environment that don't use an `.env` file for setting environment variables. The `.env` file is mostly used for local development.

**Comment by PeerRich** [comment]
we'll remove this entire dialog all-together once we have the onboarding wizard by @leog I believe? Lets show that text there to accept license

**Comment by PeerRich** [comment]
opened a new ticket: https://github.com/calcom/cal.com/issues/4052

**Comment by zomars** [comment]
Also for the OG issue, @mitcharseneau you need to restart your dyno after settings the env variable to see the changes.

**Comment by mitcharseneau** [comment]
> 

Thanks for the help! I have restarted the associated dyno with no change and the message persists.

**Comment by PeerRich** [comment]
this has been fixed a long time ago
