### ISSUE TITLE
Nav bar select for apps doesn't have scroll

### ISSUE THREAD

**Issue by ace4port** [calcom/cal.com#3980]
### Issue Summary

It's not an issue on bigger screens but on ones with less height, some items are hidden with no way to scroll to them.

### Steps to Reproduce

1. Went to Cal.com
2. Clicked on Apps on Navbar
3. These are what get displayed
![image](https://user-images.githubusercontent.com/39233007/186812891-ca500914-c2b3-41b0-8686-6fa87bad2f46.png)
Zooming out it reveals there more/additional content
![image](https://user-images.githubusercontent.com/39233007/186812961-467051f0-5cae-435c-89e0-967c1e449924.png)
 
At the very least there should have been a scroll.

### Technical details

Solution: Add `height` and `overscroll-y: auto` will fix for all screens

**Comment by milospuac** [comment]
Hey Abdullah, this will be fixed with the new site that will be launched on Sep 15th 

Best,
