### ISSUE TITLE
Improvements/Bugs in Locations/Video Apps

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#3981]
This is a continuation of https://github.com/calcom/cal.com/pull/3825. A list of things that I found when working on that PR.

- [ ] [Code Improvement] Remove special handling for Google Meet(in terms of adding/using `hangoutLink`) in rendering emails and other places. . It is handled separately because it works automatically through google calendar as well.
- [ ] [Bug] Google Meet shows up installed always. It can’t be uninstalled. But if Google calendar is not connected, it doesn’t actually work as a location
- [ ]  [Bug] link value overrides when switching from **Around**(or any other Video App) to **Link** in EventType Edit. After a user sees **Around** link, when he sees **Link** link, it shows **Around** link instead of it's own value.
- [ ]  [Bug] In Edit Location - Changing just the value and keeping the location type same(e.g. Changing Video URL of Around Video doesn’t trigger an email)
- [ ]  [Bug]During Reschedule the location chosen by the user isn’t shown. It shows the first one only as selected.
- [ ]  [Code Improvement] Find out **daily-video, Daily Video, and GoogleMeet** references and clean them up.
- [ ]  [Improvement] Add App icon in **where**  on success pages and emails.
- [ ]  [Bug] `formMethods.getValues("locations").length !== locationOptions.length` - It causes Add Location button to not show on V1 when an app is uninstalled but picked.
- [ ]  [Improvement]Add icon in Edit Location in upcoming bookings.
- [ ]  [Improvement] Store the location type as well along with location value for a booking. This would allow the following
    - [ ]  When showing the **where**, we know the App name and we can show the app’s logo.
    - [ ]  {LOCATION} template variable would be able to show the same App name. Right now it is just a URL with no context. URLs don’t look good in Subject
    - [ ]  Make a better sentence for Event Title e.g. `Meeting at Place` vs `Meeting on Phone Number: 91919199191`
- [ ]  [Bug] Reschedule doesn’t allow changing location
- [ ]  Fix `locationFormMethods.unregister` calls hardcoding things.
- [ ]  [Bug] Custom Booking Title is not considered in the Email subject. It is still the default. - There are different subject templates and it needs to be thought about how those subjects might be generated

**Comment by PeerRich** [comment]
@hariombalhara what do you think is the priority of this? have some of those things been addressed?
