### ISSUE TITLE
[CAL-97] Booked meeting slots are being ignored by other event types

### ISSUE THREAD

**Issue by RebeccaCotton** [calcom/cal.com#3988]
**Steps to reproduce**
1. Create two event types
2. Book a meeting in Eventtype 1
3. Book a meeting on Eventtype 2 on the same date and time

**Actual behaviour:**
- The booked slot is still available in Eventtype two, so one user can have multiple bookings at the same time

**Expected behaviour**:
- If a confirmed event with me has been booked in one event type (team or single user event), then I should not be shown as available in other event types

![screenshot-app cal com-2022 08 25-16_31_13](https://user-images.githubusercontent.com/14073417/186919263-718b0c07-11c0-45b3-b0fa-a686b1121eff.jpg)
![screenshot-app cal com-2022 08 25-16_22_40](https://user-images.githubusercontent.com/14073417/186919267-7a4bd113-6fb8-4928-8933-f725c66d1ce1.jpg)
![screenshot-app cal com-2022 08 25-16_20_53](https://user-images.githubusercontent.com/14073417/186919270-08251478-a34e-40dd-b920-bed3d341f827.jpg)
![screenshot-cal com-2022 08 25-16_20_04](https://user-images.githubusercontent.com/14073417/186919273-70b225e0-01be-416b-bc23-7e2839c9f9dc.jpg)
![screenshot-cal com-2022 08 25-16_18_20](https://user-images.githubusercontent.com/14073417/186919276-ee21294a-a110-4c8a-9a3d-47b8485b1744.jpg)

**Comment by PeerRich** [comment]
is this on localhost or app.cal.com? have you connected a calendar?

**Comment by RebeccaCotton** [comment]
> is this on localhost or app.cal.com? have you connected a calendar?

Both on app.cal.com and on local. No, there is no calendar connected.

**Comment by RebeccaCotton** [comment]
@PeerRich It looks like this is the same issue, as the one mentioned here: https://github.com/calcom/cal.com/issues/3190

**Comment by PeerRich** [comment]
ok we'll try to reproduce this on localhost without a calendar.

does it work with a calendar connected? that is typically a requirement

**Comment by emrysal** [comment]
Hi @RebeccaCotton - this has been fixed (I just checked and it is no longer occuring)
