### ISSUE TITLE
Send email to external address action in workflows

### ISSUE THREAD

**Issue by olivermrbl** [calcom/cal.com#3989]
### Is your proposal related to a problem?

I'd like to be able to add notifiers to booking created event. E.g. for when recruiters needs to be notified of interview calls.

### Describe the solution you'd like

Add "Send email to an external address" to actions in workflows.

### Describe alternatives you've considered

Setting up a webhook, but that would be an overkill for something that can be achieved through an existing feature.

**Comment by PeerRich** [comment]
forwarded to @CarinaWolli, could be a simple feature
