### ISSUE TITLE
heroku, fly.io: slug size too big

### ISSUE THREAD

**Issue by nosovk** [calcom/cal.com#3995]
Recently [there were small problems with size](https://github.com/calcom/cal.com/discussions/3837), but after recent update to v2
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1398808/187027746-2e226d81-4df5-403f-bc9d-8fea7c02f332.png">
Now it couldn't be deployed to Heroku or fly.io

**Comment by PeerRich** [comment]
oh that is odd @zomars

**Comment by zomars** [comment]
@nosovk what does it mean with "slug size" ?

**Comment by nosovk** [comment]
According to [doc](https://devcenter.heroku.com/articles/slug-compiler#:~:text=gitignore%20file.-,Slug%20size,such%20as%20ls%20and%20du%20.) it's a resulting JS bundle.

**Comment by zomars** [comment]
There was a recent fix there some uncompressed images we're being bundled as part of the JS. It should be solved by next release and that should also help reducing the overall bundle size.

**Comment by nosovk** [comment]
ok, current master fails, will redo in a week.

**Comment by nosovk** [comment]
hm, still failing :(

**Comment by jansroka** [comment]
Still failing with 2.4.3

```
-----> Compressing...
 !     Compiled slug size: 928M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
```

**Comment by PeerRich** [comment]
still failing @nosovk ?

**Comment by nosovk** [comment]
Oh, I've moved from self-hosted solution, can't check now
