### ISSUE TITLE
Calendar conflicts of synced calendars are being ignored by the app in team meetings with more than one member

### ISSUE THREAD

**Issue by RebeccaCotton** [calcom/cal.com#4004]
### Issue Summary

If I have a team meeting set up with 2+ members calendar conflicts in their synced calendars (tested with outlook & gmail) are being ignored when showing their availability.

### Steps to Reproduce

1. Create two users, with calendar events blocking some of their available time
2. Create a team event which contains both users
3. Check their availability in the event VS what should be their availability according to the synced calendars: [https://cal.com/team/testteam---bug-round-2/teamtestevent---both-users?date=2022-09-07&month=2022-09](https://cal.com/team/testteam---bug-round-2/teamtestevent---both-users?date=2022-09-07&month=2022-09) 

Our setup:
Free slots by user should be:

- Mon 9-11 User1 available
- Mon 11-12 Both available
- Mon 12-17 User2 available
- Wed 9-12 User1 available
- Wed 14-17 User1 available
- Fri 14-17 User2 available

Going by user this is how they are set up:
**User 1**
Availability: Mon, Wed 9-17h
Calendar blocker - gmail Monday 12-20h
Calendar blocker - outlook - Wed, 12-14h

**User 2**
Availability: Mon, Fri - 11-17h
Calendar blocker - gmail: Friday 10-14h

**Actual behaviour**:
The calendar blockers of both users are being ignored.
Availability shown to the user is: 
- Mon: 9-17h - this is fine
- Wed: 9-17h - the blocker from User1 12-14h is being ignored
- Fri: 11-17h - the blocker from User2  10-14h is being ignored

![image](https://user-images.githubusercontent.com/14073417/187079021-a7d21285-8827-4587-a658-6d735dc2a1c6.png)
![image](https://user-images.githubusercontent.com/14073417/187079037-4778b1b2-465e-42b9-804a-63c8817585e8.png)

**Expected behaviour:**

Free slots by user should be as follows:
- Mon 9-11 User1 available
- Mon 11-12 Both available
- Mon 12-17 User2 available
- Wed 9-12 User1 available
- Wed 14-17 User1 available
- Fri 14-17 User2 available

### Notes
- We did test this with a team event with only one user and in this case the calendar blockers are being taken into consideration
- [Sample event with only the User1](https://cal.com/team/testteam---bug-round-2/teamtestevent): You can see that no slots are available Wednesday from 12-14h, which is the expected behaviour. The same could be reproduced with User 2.
![image](https://user-images.githubusercontent.com/14073417/187079255-6a4dd8b8-0f4f-4b6c-aaf2-a4b7a766be38.png)

### Technical details

- we tested this with gmail and outlook, on firefox and chrome
- this behaviour occurs both on local, our self hosted instance and your cloud service

**Comment by PeerRich** [comment]
@emrysal or @alishaz-polymath can you try to reproduce this?

**Comment by emrysal** [comment]
Closing this; obviously has been fixed for quite some time but confirmed this is indeed fixed
