### ISSUE TITLE
[CAL-78] Availability page is taking a lot of time to load 

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#4007]
When i connected my outlook calendar with cal.com the time to load availability page has been increased dramatically(~40 seconds).

https://user-images.githubusercontent.com/53316345/187177060-e5558aa8-a779-4efa-93a7-4af72d539608.mov

dont't know if this is due to outlook or because of too many events in the calendar.

<img width="1440" alt="Screenshot 2022-08-29 at 3 34 37 PM" src="https://user-images.githubusercontent.com/53316345/187177287-646edf21-4818-432b-ada6-b87ee4f649a4.png">

**Comment by vernonstinebaker** [comment]
I'm having the same experience with a calendar with a lot fewer entries, so I don't think the problem is too many events.

**Comment by PeerRich** [comment]
yeah this seems super odd. tagging @emrysal here to reproduce

**Comment by PeerRich** [comment]
is this still ongoing @Udit-takkar ?

**Comment by Udit-takkar** [comment]
just tried again and it is still taking too much time with outlook calendar connected.

**Comment by emrysal** [comment]
It's a combination of factors, many events in addition to calls to outlook being slow in general, adds up to being remarkably slow. We'll need to improve caching for these situations

**Comment by emrysal** [comment]
Moved to v2.1 as discussed @PeerRich
