### ISSUE TITLE
routing forms embeds: fix dark mode

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4030]
<img width="1051" alt="CleanShot 2022-08-30 at 15 28 55@2x" src="https://user-images.githubusercontent.com/8019099/187449691-f4a192a9-b689-4392-aebf-cfc2d68c7365.png">

**Comment by Toledodev** [comment]
Hey @PeerRich, what color should we use?

**Comment by PeerRich** [comment]
i believe this has been fixed

**Comment by PeerRich** [comment]
ahh nope, still ongoing

<img width="930" alt="CleanShot 2022-09-08 at 17 59 51@2x" src="https://user-images.githubusercontent.com/8019099/189169952-e1fae358-9394-4397-8b12-106c40da9858.png">

**Comment by PeerRich** [comment]
we dont have dakr mode for inpouts yet. we should just force white mode for embeds for now.

i am taking this

**Comment by PeerRich** [comment]
submitted a fix https://github.com/calcom/cal.com/pull/4304

dark mode for the Select is another ticket for 2.1
