### ISSUE TITLE
Can't sign up with Google account

### ISSUE THREAD

**Issue by markflorkowski** [calcom/cal.com#4046]
### Issue Summary

When I attempt to sign up with a google account, noting appears to happen on screen. There is a debug message in the browser console. 

### Steps to Reproduce

1. Enter a username
2. Click the "sign in with Google" button
3. Observe that nothing appears to happen

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
Browser: Version 104.0.5112.101 (Official Build) (arm64) -- also appears to happen on intel mac.
Operating System: MacOS Monterey 12.5.1

https://user-images.githubusercontent.com/11494384/187517030-6fd58565-2720-4034-be07-113cc002c5b5.mov

**Comment by PeerRich** [comment]
we'll investigate immediately. maybe @deepakprabhakara can help, too

**Comment by hariombalhara** [comment]
This is fixed now
