### ISSUE TITLE
[CAL-96] show zapier templates and link to them

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4048]
take the templates from https://github.com/calcom/cal.com/issues/3597 and show them in the app

**Comment by PeerRich** [comment]
like this 
<img width="799" alt="CleanShot 2022-08-30 at 21 27 06@2x" src="https://user-images.githubusercontent.com/8019099/187525928-fb1ea85e-a216-4c88-aced-6c641b1c41b2.png">

**Comment by PeerRich** [comment]
@Jaibles where would you like to show these template cards?

**Comment by PeerRich** [comment]
i'll make those components ready and then we can decide when and where to show them

**Comment by Jaibles** [comment]
@PeerRich what about in here?
![CleanShot 2022-08-31 at 11 34 15@2x](https://user-images.githubusercontent.com/4536123/187659359-946e4e50-1a5f-44c3-af19-e528bc6f80d9.png)

**Comment by PeerRich** [comment]
great idea as an app-specific settings
