### ISSUE TITLE
refactor: turn booking information into a component

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4050]
right now, the left booking information box is quite messy and written twice (in [id].tsx and in /book.tsx)

<table>
<tr>
<td>
<a href="https://cal.com/bailey/15min">https://cal.com/bailey/15min</a>
</td>
<td>
<a href="https://cal.com/bailey/book?type=1&date=2022-08-31T10%3A00%3A00%2B02%3A00&slug=15min&count=">https://cal.com/bailey/book?type=1&date=2022-08-31T10%3A00%3A00%2B02%3A00&slug=15min&count=</a>
</td>
</tr>
<tr>
<td>
<img width="348" alt="CleanShot 2022-08-30 at 21 41 59@2x" src="https://user-images.githubusercontent.com/8019099/187528590-fee42229-a3f8-405c-8c11-06d32cdab9bd.png">

</td>
<td>
<img width="510" alt="CleanShot 2022-08-30 at 21 43 17@2x" src="https://user-images.githubusercontent.com/8019099/187528815-ac82bdbd-2505-4c47-b60e-b396537a2cf2.png">

</td>
</tr>
</table>

we should do something like: 

```
<BookingDescription
avatars={}
owner=”Bailey Pumfleet”
title=”Quick Chat (15 mins)”
description=”Please provide …”
requiresConfirmation={true} …
/>
```

**Comment by PeerRich** [comment]
while writing i realised we should probably merge the two files/routes ([id].tsx and /book.tsx)

**Comment by G3root** [comment]
i like to take on this issue.

**Comment by PeerRich** [comment]
cool thank you @G3root
