### ISSUE TITLE
[CAL-99] remove "NEXT_PUBLIC_LICENSE_CONSENT" and banner and move it into onboarding wizard

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4052]
since we're launching our "getting started" onboarding wizard when UserCount = 0 we can show the "Accept License" part in the onboarding wizard and remove NEXT_PUBLIC_LICENSE_CONSENT from .env and also remove the Banner component

**Comment by PeerRich** [comment]
this would fix https://github.com/calcom/cal.com/issues/3979

**Comment by lienista** [comment]
What is this variable supposed to be? Inside .env.example it shows a simple `` and no variable. Who do we contact to accept consent?

**Comment by PeerRich** [comment]
@lienista dont worry, it'll be removed in the next update
