### ISSUE TITLE
[CAL-100] Incorrect Time in Booking Confirmation Email Subject

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#4056]
Found a bug? Please fill out the sections below. 👍

The confirmation email's subject contains incorrect time (probably doesn't take Timezone into account)
![image](https://user-images.githubusercontent.com/52925846/187596956-d9926a98-0d32-419d-b539-ae53588382b5.png)

A summary of the issue. This needs to be a clear detailed-rich summary.

Once a booking is made, the confirmation email's subject contains incorrect time which might be due to timezone not considered.

**Comment by Udit-takkar** [comment]
@alishaz-polymath  i tried reproducing this. the email subject returns the time ( in time zone ) of the availability page which i think is correct .

**Comment by alishaz-polymath** [comment]
It could be possible that this is taken from the booker's timezone. It definitely isn't correct in production.

**Comment by Jaibles** [comment]
@alishaz-polymath @Udit-takkar can one of you try to resolve this in our 2.3 milestone and could you clarify when you think this is happening? Would like to get a sense of how many bookings this could affect 🙏

**Comment by alishaz-polymath** [comment]
I could explore this, yes. Let me add this to my next week's agenda 🙏

**Comment by alishaz-polymath** [comment]
There were changes to the Email subject altogether and I am since unable to re-create this.
