### ISSUE TITLE
/event-types: Embed button has no action

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#4060]
Reimplement Embed button within /event-type/[type] as the current implementation was clashing with the tab navigation that we now use in V2

`tabName` prop should ideally be renamed in the embed component to something else to prevent the clash

<img width="295" alt="CleanShot 2022-08-29 at 13 51 30@2x" src="https://user-images.githubusercontent.com/8019099/187194928-0a90061a-9cac-42bd-a01c-73cccd27b611.png">

**Comment by Jaibles** [comment]
This should use the button group component (combined)
https://ui.cal.com/?path=/story/button-group--combined

![Image](https://user-images.githubusercontent.com/4536123/188612774-18ab48e8-03bb-4342-8d11-ad7d18663a9a.png)

**Comment by sean-brydon** [comment]
> This should use the button group component (combined) [ui.cal.com/?path=/story/button-group--combined](https://ui.cal.com/?path=/story/button-group--combined)
> 
> ![Image](https://user-images.githubusercontent.com/4536123/188612774-18ab48e8-03bb-4342-8d11-ad7d18663a9a.png)

This should be fixed in main now :) 

Embed button issue still stands

**Comment by PeerRich** [comment]
> Embed button issue still stands

who's working on this? @hariombalhara you?

**Comment by hariombalhara** [comment]
@PeerRich PR is up.
