### ISSUE TITLE
collective event-types not saving

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4088]
from a user:

- Changes that were made to collective event types didn't save 
- This was the most painful for us. We had updated an event type, saved it, confirmed that the new link worked, then we sent it to an investor who later told us the link was invalid. The configurations had somehow been reset and we looked like amateurs. This is ultimately what caused us to churn.
- Troubleshooting collective booking times was difficult.
- The interface made it difficult for users to find an available time with us.

**Comment by zomars** [comment]
Is this still a thing?

**Comment by PeerRich** [comment]
i dont think so
