### ISSUE TITLE
/settings, replace Loader with skeleton (Loader in settings is huge)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4101]
<img width="1012" alt="Screenshot 2022-09-01 at 17 06 24" src="https://user-images.githubusercontent.com/30310907/188013078-d7dbeea1-8f3d-41a3-9108-afeabb4f5cd0.png">

**Comment by PeerRich** [comment]
we wanna get rid of this loader anyway, right @zomars ?

**Comment by PeerRich** [comment]
cc @joeauyeung for your info: we wanna use skeletons over this loader

**Comment by zomars** [comment]
Affirmative @PeerRich

**Comment by PeerRich** [comment]
closing because @joeauyeung is replacing it with skeleton

**Comment by joeauyeung** [comment]
Sorry @PeerRich, I'm going to reopen this and close it once it's completed to help me keep track of things. I'm going to create a seperate PR from the settings shell PR as it's getting pretty big
