### ISSUE TITLE
[CAL-107] settings/my-account/calendars: width way too long and goes out of screen

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4103]
<img width="1251" alt="Screenshot 2022-09-01 at 17 15 47" src="https://user-images.githubusercontent.com/30310907/188014488-e7e1d788-183b-4624-8ee0-b758f24589bf.png">

**Comment by MuriloAmarals** [comment]
Hey @PeerRich and @Jaibles how can I add a calendar on my localhost?

![image](https://user-images.githubusercontent.com/87545137/196198578-cd14d9e3-af8d-48ff-b93b-0526f771bd4a.png)

**Comment by joeauyeung** [comment]
Can't replicate. I believe I fixed this in a previous PR
