### ISSUE TITLE
/settings Sidebar needs formatting & links fixing (Compare with Figma)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4105]
[Compare with Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17937%3A171647)

![Image](https://user-images.githubusercontent.com/4536123/188153029-9573874e-16a9-4f9f-ab4a-aa54dde1090e.png)

**Comment by Jaibles** [comment]
Also @joeauyeung, the top level items should not be clickable. Right now the "My Profile" one at the top goes to 500 screen


https://user-images.githubusercontent.com/4536123/189128383-36051eb9-8421-4047-996e-67c86ca60446.mp4
