### ISSUE TITLE
Sticky internal sidebars

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4110]
- [x] In Event types single
<img width="1163" alt="CleanShot 2022-09-02 at 09 44 25@2x" src="https://user-images.githubusercontent.com/4536123/188101183-51e38cfe-888d-447c-8986-c69c7d6b25af.png">

- [ ] In Bookings
<img width="1468" alt="CleanShot 2022-09-02 at 09 38 59@2x" src="https://user-images.githubusercontent.com/4536123/188101204-2a71df29-2327-4ff0-a4d0-f4eefbf73349.png">

`24px` gap from top

**Comment by PeerRich** [comment]
@Jaibles do you have a screenshot or video?

**Comment by Jaibles** [comment]
Desired behaviour would be this:
<img width="1468" alt="CleanShot 2022-09-02 at 09 38 59@2x" src="https://user-images.githubusercontent.com/4536123/188100250-9a68bca2-e26f-4bd6-a31e-bf8777eedaef.png">

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17933%3A169946)

**Comment by JeroenReumkens** [comment]
Consider it done @Jaibles  😉
https://github.com/calcom/cal.com/pull/4145
