### ISSUE TITLE
[CAL-103] All Bookings show up under Today and Today should be uppercase

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4111]
Task should probably just be to remove "Today"?

If the quickest thing to do here is not group things that's a perfectly ok fix. Grouping can be a future task as it likely requires complex logic.

<img width="897" alt="Screenshot 2022-09-01 at 16 56 27" src="https://user-images.githubusercontent.com/30310907/188011437-5568917a-697a-4665-b757-8c4f565f9634.png">

**Comment by PeerRich** [comment]
hidden for now. moving to 2.1

**Comment by Toledodev** [comment]
Hey @PeerRich, I think this "today" doesn't exist anymore
![Screenshot from 2022-09-21 09-44-06](https://user-images.githubusercontent.com/87545086/191506976-d79cda73-28d3-43b6-a0d1-8d757fe747a8.png)

**Comment by PeerRich** [comment]
yeah the "Today" was temporally removed until we have the logic to filter only for today

**Comment by Toledodev** [comment]
Can I try to implement this logic?

**Comment by PeerRich** [comment]
> Can I try to implement this logic?

sure go for it @Toledodev

**Comment by Toledodev** [comment]
Hey @PeerRich I created a logic to filter only the meetings of the day, is this something you are looking for?
![Screenshot_2](https://user-images.githubusercontent.com/87545086/194782246-e0fd05a4-bbc1-4b34-9be8-8a23d20e700e.png)

**Comment by Toledodev** [comment]
Hey @PeerRich, I made some changes, what do you think?
![Screenshot_9](https://user-images.githubusercontent.com/87545086/195696268-8029e334-c4e5-485e-8982-906ca428af37.png)

**Comment by PeerRich** [comment]
@Toledodev 

this is great, can you open a PR? 🙏

**Comment by Toledodev** [comment]
Sure :)
