### ISSUE TITLE
/event-type: Dropdown list still needs formatting in mobile and desktop version

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4115]
<img width="554" alt="CleanShot 2022-09-02 at 11 26 56@2x" src="https://user-images.githubusercontent.com/8019099/188109293-460161d1-4e72-4ab5-8b78-c47f0f1bdd34.png">

**Comment by PeerRich** [comment]
`<Button>` likely needs a new variant="menuItem" @sean-brydon
