### ISSUE TITLE
Move the "Team Webhooks" add button

### ISSUE THREAD

**Issue by owen-whalecard** [calcom/cal.com#4129]
### Issue Summary

Not exactly a bug but I spent way to long trying to figure out why I was unable to add a "Team Webhook".  The button seems to blend into the background that I didn't even notice it. My team had the same problem. I would probably move it to the left or add a background colour to it.

<img width="1728" alt="Screen Shot 2022-09-02 at 3 19 10 PM" src="https://user-images.githubusercontent.com/100158053/188223512-156ffed6-9878-429c-a1d4-c2290bf7c06a.png">

### Steps to Reproduce

1. Click on a team event page with no webhooks on laptop or larger screen
2. Scroll to bottom of page

**Comment by PeerRich** [comment]
this entire page is currently getting a makeover and will look very different in around 10 days
