### ISSUE TITLE
[CAL-102] /event-types make switch async

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4130]
right now it seems like the switch state is based on the return of the server, i think we shouldnt wait for the response and fake the state switch

https://user-images.githubusercontent.com/8019099/188223838-c9cfcc82-3967-4a5c-9362-292279cde06c.mp4

**Comment by PeerRich** [comment]
hard to see but there is like a second delay when pressing

**Comment by Udit-takkar** [comment]
this thing is already done https://github.com/calcom/cal.com/pull/4721
