### ISSUE TITLE
Icon button tooltip should be 4px off the button

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4133]
Currently
![Image](https://user-images.githubusercontent.com/4536123/188227018-46631c8c-50bc-4317-af39-6f2e344ee864.png)

![Image](https://user-images.githubusercontent.com/4536123/188227022-57093304-6059-4636-99de-7fc9770aefd3.png)

Should be
![Image](https://user-images.githubusercontent.com/4536123/188226977-bc0ead73-48b9-4050-b63d-d8e93b35483c.png)

@sean-brydon looks like a fix needed at component level?

**Comment by PeerRich** [comment]
im taking this

**Comment by Jaibles** [comment]
ah ok sorry 😅 thought I'd added you by accident cause it happened virtually at creation time

**Comment by Udit-takkar** [comment]
> ah ok sorry 😅 thought I'd added you by accident cause it happened virtually at creation time

Peer is speed
![image](https://user-images.githubusercontent.com/53316345/188227742-fcb1b472-7e47-471b-a03d-b6881183f8e3.png)

**Comment by PeerRich** [comment]
done 🏎️💨
