### ISSUE TITLE
use autoanimate for re-ordering

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4135]
<img width="236" alt="CleanShot 2022-09-03 at 12 56 36@2x" src="https://user-images.githubusercontent.com/8019099/188267328-473417ee-4aeb-45bd-bfb3-a5400d1e3746.png">

see demo: https://auto-animate.formkit.com/#demo

**Comment by Sagargajare** [comment]
@PeerRich I would love to contribute to this project.

Can you assign it to me?

**Comment by PeerRich** [comment]
> @PeerRich I would love to contribute to this project.
> 
> Can you assign it to me?

go for it.👏

**Comment by Sagargajare** [comment]
Thanks.

**Comment by Udit-takkar** [comment]
@PeerRich  this has been already done.
