### ISSUE TITLE
/event-types detail header actions - Toggle label text, toggle spacing, missing divider

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4154]
Currently
![Image](https://user-images.githubusercontent.com/4536123/188409694-b085d751-384d-43f3-a480-0fd26607e271.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/188409732-e92c1234-227e-47a5-a8d9-6506ced894e5.png)

- [ ] Label text size
- [ ] Also check the spacing around the toggle. It should have a padding
- [ ] Add dividers between actions

**Comment by PeerRich** [comment]
i'm taking this

**Comment by sean-brydon** [comment]
Oh okay :)

**Comment by Jaibles** [comment]
@PeerRich spec for this header in case you need it.

![Image](https://user-images.githubusercontent.com/4536123/188432822-0edf6ce9-819b-4248-9514-f6191d9fe6d6.png)

**Comment by PeerRich** [comment]
i'm creating a new `VerticalDivider` component, too

**Comment by PeerRich** [comment]
done
