### ISSUE TITLE
/event-type detail / apps - empty state text is not centered and spacing is off from header.

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4162]
- [x] text should be centered
- [x] button should be secondary not primary
- [x] spacing at top
- [x] Should read "0 active" not "0 Active" - we use Sentence case everywhere so that we don't have inconsistency.

![Image](https://user-images.githubusercontent.com/4536123/188434320-3b01b151-023c-42fa-8c5a-d7952eecac8d.png)

spacing from top should be 32px

![Image](https://user-images.githubusercontent.com/4536123/188434355-51a9dbe3-3bd4-43e8-b3be-7128197ffd70.png)

**Comment by PeerRich** [comment]
done in https://github.com/calcom/cal.com/pull/4165
