### ISSUE TITLE
/workflows empty state - button not centered & cards wrong padding

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4168]
Currently
<img width="1113" alt="CleanShot 2022-09-05 at 13 23 21@2x" src="https://user-images.githubusercontent.com/4536123/188448796-d7004966-7838-40f2-a817-2397de410a5a.png">

Should be
![CleanShot 2022-09-05 at 13 27 34@2x](https://user-images.githubusercontent.com/4536123/188449268-3586cfce-79b6-4419-86ac-892959abd220.png)

<img width="1070" alt="CleanShot 2022-09-05 at 13 32 22@2x" src="https://user-images.githubusercontent.com/4536123/188450043-38b0bfa3-3ddc-4b74-9bc9-2ce39dc93b44.png">

**Comment by PeerRich** [comment]
i believe @CarinaWolli is currently working on this page

**Comment by PeerRich** [comment]
done. font-semibold looks very odd so i'm going with the default weight
