### ISSUE TITLE
Skeleton loader styling

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4169]
![Image](https://user-images.githubusercontent.com/4536123/188452126-db7f5a6f-6c5f-4f86-ba70-654c92782a71.png)

**Comment by Jaibles** [comment]
@PeerRich I think all loading things have a harsh border radius on them. Shuold probably all be 6px

![Image](https://user-images.githubusercontent.com/4536123/188458647-6db00f2e-ce7d-4546-ae12-9f190c9e371f.png)

**Comment by CarinaWolli** [comment]
> @PeerRich I think all loading things have a harsh border radius on them. Shuold probably all be 6px

Fixed border radius for Skeleton Buttons here: #4397

**Comment by hariombalhara** [comment]
@CarinaWolli I guess you are working on it. Should I assign this to you?

**Comment by CarinaWolli** [comment]
Fixed with #4402
