### ISSUE TITLE
/event-type-detail - spacing not being applied between text

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4174]
I think there's a `pb-2` followed by a `-mt-2` resulting in no space here.
![Image](https://user-images.githubusercontent.com/4536123/188456684-1d750b8a-953c-4838-b2e5-4de59db085b1.png)

There should be space

![Image](https://user-images.githubusercontent.com/4536123/188457095-0a725f29-f668-4614-aa26-8a5c96406811.png)

Double check all spacing in here while we're here :)

![Image](https://user-images.githubusercontent.com/4536123/188457200-0e885c1c-09c3-4cc9-b72c-817f574053bc.png)

**Comment by PeerRich** [comment]
this is a bigger ticket, I dont think the limits page has been worked on yet?

**Comment by PeerRich** [comment]
fixed spacing in https://github.com/calcom/cal.com/pull/4213 but the rest of limits hasn't been touched yet and needs a proper ticket on its own
