### ISSUE TITLE
/event-types-detail /workflows component - multiple UI issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4175]
- [ ] check spacing
- [ ] title text weight?
- [ ] edit button has no hover state

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13992%3A98805)

Check all spacing and sizing on this
![Image](https://user-images.githubusercontent.com/4536123/188458015-5d6332a7-bfe1-4ff4-b820-85126ec0ad12.png)

![Image](https://user-images.githubusercontent.com/4536123/188458091-1bc8a29c-f3dd-44b2-a788-d50c94b96b68.png)

![Image](https://user-images.githubusercontent.com/4536123/188458180-e754871e-b40e-4eab-9dee-7211f20c18ce.png)

Also check hover states

![Image](https://user-images.githubusercontent.com/4536123/188458319-54e58fb8-a61c-42dc-9d7c-e130dbe234b2.png)

**Comment by PeerRich** [comment]
@CarinaWolli can you take this off of @sean-brydon ?

**Comment by CarinaWolli** [comment]
I will work on this
