### ISSUE TITLE
/event-types detail - Hide from profile shuold have a toast when toggled?

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4177]
If we have one for copying link, should we have one for hiding from profile...or is it cause this isn't saved yet? If so, I think it feels weird not having one...

https://user-images.githubusercontent.com/4536123/188459114-98107909-05e5-418d-b4bc-d612046927b6.mp4

..Maybe saying "Will be hidden when saved"...🤔.. thoughts?

**Comment by PeerRich** [comment]
for 2.1 we should add auto-save and show a toast whenever saved @sean-brydon
