### ISSUE TITLE
/event-types-detail /recurring - I spy an input with 38px height 🧐

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4178]
![Image](https://user-images.githubusercontent.com/4536123/188459774-38231dc3-39b8-4ccd-9ba8-6835073f6a52.png)

**Comment by PeerRich** [comment]
also @sean-brydon we can use auto animate here, no?

**Comment by Jaibles** [comment]
check all spacing while we're in here.. (if we actually are in here and if it's not the component we're in)
![CleanShot 2022-09-05 at 14 26 11@2x](https://user-images.githubusercontent.com/4536123/188460586-a78693eb-62eb-4052-a40a-1175a162c35a.png)
![CleanShot 2022-09-05 at 14 26 07@2x](https://user-images.githubusercontent.com/4536123/188460594-d7db4d22-ce25-44f7-908a-001a894717e8.png)

**Comment by sean-brydon** [comment]
> also @sean-brydon we can use auto animate here, no?

Don't see why not
