### ISSUE TITLE
/routing-form-detail - header actions - combined button component has double border

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4181]
![Image](https://user-images.githubusercontent.com/4536123/188462807-5ecc681b-259e-4c8c-b332-1b63a366c198.png)

And divider has rounded corners :)

![Image](https://user-images.githubusercontent.com/4536123/188491316-f56702dd-017b-4780-b5c8-8a0c6c95f5f4.png)

**Comment by PeerRich** [comment]
i cant seem to figure out why this isn't working. it has "combined" as a prop. @sean-brydon can you give this look?

**Comment by sean-brydon** [comment]
Okay it makes sense why this doesn't work  - took me a while to figure out if im honest 

The download button is actually a `a` tag and the rest are buttons. Therefore our [selectors](https://tailwindcss.com/docs/hover-focus-and-other-states#first-of-type) are not working. 

Now I just need to figure out how to fix it
