### ISSUE TITLE
/event-types & /routing-forms - List item action changes

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4186]
I've made some updates to the actions at the end of list items to be more consistent across the board.

- [x] **Event types**

<img width="946" alt="CleanShot 2022-09-05 at 18 29 26@2x" src="https://user-images.githubusercontent.com/4536123/188495452-f1b66af2-734c-4a25-be1b-3453617830a6.png">

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1504%3A82984)

- [x] **Routing forms**
<img width="581" alt="CleanShot 2022-09-05 at 18 47 04@2x" src="https://user-images.githubusercontent.com/4536123/188497004-9b5d871d-99c9-4663-849b-6f79fbcf2cef.png">

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=13462%3A97710)

@sean-brydon forgive me for the changes here 🙏

**Comment by PeerRich** [comment]
note: this should become the default anytime we have a list with buttons (also in availability or workflows @emrysal @CarinaWolli )
