### ISSUE TITLE
Some menu items are hiding under the footer (z-index issue)

### ISSUE THREAD

**Issue by nerdjfpb** [calcom/cal.com#4191]
### Issue Summary

Some menu items are hiding under the footer. In navbar z-index `10` and footer z-index `50`

### Steps to Reproduce

1. Go to cal.com 
2. Scroll down to the bottom (while full footer is visible) and click on the `Apps`

### Screenshot
![menu item issue](https://user-images.githubusercontent.com/47062625/188531016-83cb47da-0865-4e04-baac-b76e5d232da1.png)

**Comment by PeerRich** [comment]
wont fix -- new page is days away from going live.🙏
