### ISSUE TITLE
/event-types new dropdown misaligned

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4192]
<img width="428" alt="CleanShot 2022-09-06 at 08 50 23@2x" src="https://user-images.githubusercontent.com/8019099/188566199-b9ebac70-8ee8-45fa-85b6-cfc536295d15.png">

**Comment by Jaibles** [comment]
Should be
![Image](https://user-images.githubusercontent.com/4536123/188572321-909a3ccb-8dc1-4059-a3fd-e746d66aba08.png)


[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A110084)
