### ISSUE TITLE
Create app.cal.com/more for mobile menu

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4196]
We need to reduce the number of items in our menu on mobile. To tackle this we have an overflow menu which will take Routing Forms, Workflows & Settings. 

[Prototype ](https://www.figma.com/proto/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?page-id=15217%3A117835&node-id=15217%3A119635&viewport=1547%2C448%2C0.83&scaling=min-zoom&starting-point-node-id=15217%3A119635&show-proto-sidebar=1) | [View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=15217%3A118384)

https://user-images.githubusercontent.com/4536123/188568981-7d1fdcd5-fc41-46b4-b526-c7faa26a0ed7.mp4

![Image](https://user-images.githubusercontent.com/4536123/188568668-2fac2ccb-5c70-4191-abc6-da27e498b877.png)

![Image](https://user-images.githubusercontent.com/4536123/188568750-45f3a1df-aba9-4e49-95d5-383263b44bf6.png)

**Comment by PeerRich** [comment]
@joeauyeung wanna work on this, given you are working on settings?

**Comment by joeauyeung** [comment]
Is this immediate for V2 or can it wait for V2.1?

**Comment by PeerRich** [comment]
lets put this at the end of 2.0 if we have space

**Comment by PeerRich** [comment]
i think the /more page is easy but the bottom logic requires some more thought:

<img width="786" alt="CleanShot 2022-09-06 at 21 44 26@2x" src="https://user-images.githubusercontent.com/8019099/188724801-723e53ee-d0be-43f5-a61a-b0c287e5beb3.png">


is it ok if settings links to /settings/profile for now @Jaibles ? if yes I can take this

**Comment by Jaibles** [comment]
> i think the /more page is easy but the bottom logic requires some more thought:
> 
> 
> 
> <img width="786" alt="CleanShot 2022-09-06 at 21 44 26@2x" src="https://user-images.githubusercontent.com/8019099/188724801-723e53ee-d0be-43f5-a61a-b0c287e5beb3.png">
> 
> 
> 
> 
> 
> is it ok if settings links to /settings/profile for now @Jaibles ? if yes I can take this

Yes, definitely @PeerRich

**Comment by PeerRich** [comment]
done in https://github.com/calcom/cal.com/pull/4219
