### ISSUE TITLE
/event-types - New event type dropdown broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4199]
Currently
![Image](https://user-images.githubusercontent.com/4536123/188570535-37df9064-0a73-4a1c-8458-e4ca9496e1f6.png)

Should be
![Image](https://user-images.githubusercontent.com/4536123/188572321-909a3ccb-8dc1-4059-a3fd-e746d66aba08.png)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A110084)

**Comment by PeerRich** [comment]
done
