### ISSUE TITLE
/settings - conferencing broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4200]
Currently
![Image](https://user-images.githubusercontent.com/4536123/188572655-9da748c9-ed18-4097-b937-00853633b169.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/188572814-dc29cbe6-bd2b-44f1-9ed3-13bf31b4bf6c.png)

**Comment by joeauyeung** [comment]
@Jaibles I noticed this as well and I added it as a quick fix as part of #3987

**Comment by Jaibles** [comment]
perfect yea, sorry I submitted that thinking that was merged 👍
