### ISSUE TITLE
[CAL-108] refactor: replace react-select with radix

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4212]
https://www.radix-ui.com/docs/primitives/components/select

**Comment by G3root** [comment]
i'd like to take on this issue. can you list out which components to be replaced.

**Comment by sean-brydon** [comment]
Hey @G3root - The main component that would require work is 

`packages/ui/v2/core/form/Select.tsx` We would like the new select to match the styles of the current one Figma [here](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=364%3A25456)

Off that back of this there could be some implementation changes across the app. 

Thanks for picking this up - please drop us a message if you need a hand!

**Comment by G3root** [comment]
@sean-brydon i looked around radix-ui select component. look's like it doesn't support multi select, whereas current implementation depends on it. how should i go with this ?

**Comment by PeerRich** [comment]
@sean-brydon will replace this with our own new select component
