### ISSUE TITLE
/event-types-detail - Active apps count is wrong

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4221]
Currently says 2 active when 0 are active. Should say "2 apps, 0 active"

![Image](https://user-images.githubusercontent.com/4536123/188748681-d3dbe628-0d13-48b2-9c55-4923d3ff87d3.png)

**Comment by PeerRich** [comment]
also those two horizontal lines, are they supposed to be there?

**Comment by leog** [comment]
> also those two horizontal lines, are they supposed to be there?

Horizontal line was gone when fixing the other stuff, but an excessive margin was still there, fixed now, PR #4405.
