### ISSUE TITLE
recurring events don't show up in upcoming

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4229]
i believe this used to work in v2? @leog 

![CleanShot 2022-09-07 at 09 58 00](https://user-images.githubusercontent.com/8019099/188823084-e15d42af-735f-4499-8f7c-bf172b335032.gif)

**Comment by leog** [comment]
@PeerRich I don't remember seeing any recurring event in v2 TBH

**Comment by PeerRich** [comment]
> Also notice as the "Bookings" side menu item gets deselected when you switch to "Recurring" submenu item.

oh thats a separate ticket

**Comment by MatheusBeniniF** [comment]
Hi @PeerRich you want to show recurring events even if there is no confirmation?
