### ISSUE TITLE
/settings/appearance - change the theme options to a 3 option fancy radio with image

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4232]
![Image](https://user-images.githubusercontent.com/4536123/188854170-e32823ed-3fe6-442d-a8f4-8c363bb70fe1.png)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=16644%3A151004)

**SVGS ready.. with grainy effect in SVG!!**

![Image](https://user-images.githubusercontent.com/4536123/188918280-5f4ed661-c796-4c11-a95b-5b19e78ab450.svg)
![Image](https://user-images.githubusercontent.com/4536123/188918279-aa7ac9e5-a5b4-47cd-8556-aa4b27fc9862.svg)
![Image](https://user-images.githubusercontent.com/4536123/188918281-3898183c-bc5e-4a95-8b21-d6cf50af5134.svg)

**Comment by emrysal** [comment]
Hi @noahflk we're more than happy for you to do so; have a look @ https://flowbite.com/docs/forms/radio/#advanced-layout for how we thought it could be implemented.

**Comment by PeerRich** [comment]
> Hi @noahflk we're more than happy for you to do so; have a look @ https://flowbite.com/docs/forms/radio/#advanced-layout for how we thought it could be implemented.

with radix UI tho

**Comment by emrysal** [comment]
@PeerRich Not in this case IMO, Radix UI has nothing built-in that works for this without overheads. ToggleGroup can do it but brings with it a lot of state where we do not need state. Using native we prevent unnecessary re-renders.
