### ISSUE TITLE
/booking replace large buttons with icons

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4239]
currently:
<img width="1512" alt="CleanShot 2022-09-07 at 21 29 23@2x" src="https://user-images.githubusercontent.com/8019099/188961318-ae7bb08f-354d-45b2-975f-7c3174e6d7b9.png">

should be:
![Image](https://user-images.githubusercontent.com/4536123/188917615-273ce886-0b11-4ce9-9808-f64ebb9b8dcb.png)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=18501%3A175947)

**Comment by PeerRich** [comment]
(a) come up with a smaller layout
(b) turn left nav into pills earlier
(c) turn buttons into dropdowns earlier

**Comment by Jaibles** [comment]
<img width="1126" alt="CleanShot 2022-09-07 at 16 09 22@2x" src="https://user-images.githubusercontent.com/4536123/188913654-af03e65d-ce03-49fc-a698-fca3d8977bd0.png">
[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=18501%3A175947)

**Comment by PeerRich** [comment]
you need to switch to 2.0 at the bottom left

**Comment by PeerRich** [comment]
i'll take this for now

**Comment by PeerRich** [comment]
i dont think the UI is trivial enough to have icon only buttons
