### ISSUE TITLE
/event-type-detail /recurring - toggle goes down a row when active

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4245]
![Image](https://user-images.githubusercontent.com/4536123/188933729-c16e167e-fffd-47c6-b660-b2b8b17eab37.png)

**Comment by PeerRich** [comment]
not sure what this ticket means

**Comment by agustif** [comment]
@PeerRich 
disabled: 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/6601142/188948484-e1f73a5f-cad2-4ed1-a498-58631e9c69d0.png">

enabled: 
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/6601142/188948524-dbd2993e-d909-43a7-ac76-d99b90a26da0.png">


PS: I found another bug in this page, if you're inside one of the tabs and refresh (cmd+r) you get a 500 error, guessing the extra params on the url are breaking something on server side?

**Comment by agustif** [comment]
@Jaibles I'll take this as is an easy fix
