### ISSUE TITLE
/event-types - Hidden label should be beside toggle

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4248]
Current

![Image](https://user-images.githubusercontent.com/4536123/188934485-d1704be6-a3de-4fc9-a827-ef728f0df0dc.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/188934500-47dd8608-9f22-4f52-a903-c2cfcbd4f070.png)

Always better to have results beside actions.

**Comment by noahflk** [comment]
Did you undo this change on purpose in 3e0f14ea294e70bff27e64d1fd48edf49d191b19 @zomars ?

**Comment by zomars** [comment]
I don't recall @noahflk is it missing on main?

**Comment by noahflk** [comment]
Yes, it looks like this commit reverted my change. Do you want to adjust your commit or should I submit a new PR? @zomars

**Comment by zomars** [comment]
Please do @noahflk 🙏🏽
