### ISSUE TITLE
/routing-form-detail - Combined button has tooltips missaligned, double border and no border radius on the end

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4250]
- [ ] no border radius on end
- [ ] tooltip is off
- [ ] double border (in another issue also)

![Image](https://user-images.githubusercontent.com/4536123/188935325-47d61cbe-b99c-4cf0-9b4f-bedf2a9889b3.png)

**Comment by PeerRich** [comment]
@sean-brydon can you take a look? you just touched the double border issue

**Comment by PeerRich** [comment]
this has been fixed
