### ISSUE TITLE
og-image (social media preview) for apps (app.cal.com/apps/zoom)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4252]
<img width="1058" alt="CleanShot 2022-09-07 at 19 43 03@2x" src="https://user-images.githubusercontent.com/8019099/188944148-4afd63cf-7284-4127-9f80-c73b4479a7c1.png">

like raycast: https://www.raycast.com/eluce2/cal-com-share-meeting-links

<img width="599" alt="CleanShot 2022-09-07 at 19 49 55@2x" src="https://user-images.githubusercontent.com/8019099/188945319-9b967033-9a09-40d1-821f-9a1f26186d2e.png">

**Comment by PeerRich** [comment]
we already have https://github.com/calcom/og-image for the public booking links

**Comment by JeroenReumkens** [comment]
@Jaibles Would you be able to make a design for these social images? 
Currently we have this image for a meeting with one person: 

![image](https://user-images.githubusercontent.com/2969573/194844584-0f6538e2-3863-4c5d-b85c-ff2b08275f70.png)

However, that image probably isn't fully matching our design. In total we need 3 types of images:
1. Meeting with one person
2. Meeting with multiple persons (team)
3. App image
