### ISSUE TITLE
/apps/app-store - App card actions are mis-aligned

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4255]
@leog not sure if this is a known issue or not so adding in case!

![Image](https://user-images.githubusercontent.com/4536123/188954556-d10d4860-75a2-4654-b98e-2f09986c4ef4.png)

**Comment by leog** [comment]
@Jaibles would be great to have visuals on what the card should look like regarding the buttons when the resolution is smaller

**Comment by Jaibles** [comment]
@leog we can drop to 3 cols instead of 4? .. then down to 2 and so on? [View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=18563%3A172402)

![1080](https://user-images.githubusercontent.com/4536123/188985402-4e69ec40-0be1-49eb-9035-65a55cde519a.png)
![780](https://user-images.githubusercontent.com/4536123/188985395-4e91d597-d16b-4197-b6fe-dfa796602270.png)

**Comment by leog** [comment]
@PeerRich @Jaibles it depends on the resolution, there is a responsive condition to wrap the buttons when the card size becomes too small. I will make sure the buttons are not wrapped, but the quantity of cards reduces.
