### ISSUE TITLE
"Remove" button in app store when app is already installed

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4257]
- right now we throw a toast "App already installed" 
- we should show the "Remove" button when app is already installed (vs showing another "Install" Button that doesn't work)

<img width="717" alt="CleanShot 2022-09-07 at 21 20 59@2x" src="https://user-images.githubusercontent.com/8019099/188960086-c364f575-60dc-44a0-9d04-e405ea661022.png">

like in installed apps:
<img width="1275" alt="CleanShot 2022-09-07 at 21 21 43@2x" src="https://user-images.githubusercontent.com/8019099/188960176-cbbb14e6-5113-466c-9483-47e21de8f191.png">

**Comment by PeerRich** [comment]
unless an app can be added multiple times (like calendar)

**Comment by Udit-takkar** [comment]
i worked on some similar issue before and i remember /pages/apps/[slug] already has this functionality of showing installed button.

i think the query to check installed is not working properly now.

<img width="370" alt="Screenshot 2022-09-08 at 2 48 29 PM" src="https://user-images.githubusercontent.com/53316345/189085072-3e9887f7-3a23-492e-b35c-44c34669c234.png">

**Comment by PeerRich** [comment]
@leog can you check this out?

**Comment by hariombalhara** [comment]
I thought this was fixed with the linked PR.

**Comment by leog** [comment]
Yeah, it should be fixed. Closing for now unless it comes up due to clients feedback.
