### ISSUE TITLE
Option to let invitees see who has signed up for other time slots

### ISSUE THREAD

**Issue by bilfri** [calcom/cal.com#426]
A great use case for Calendso is volunteers signing themselves up for shifts in eg. a cafe. For that, it would be awesome for the volunteers to see who has the shift after them or similar. Calendly doesn't do this, so this feature would make Calendso the go-to option for all sorts of self-assign-scheduling.

**Comment by PeerRich** [comment]
i’m having a hard time visualising this feature. can you make a simple mockup (figma or even low-res)

**Comment by bilfri** [comment]
something like this:
![calendso-visible-sign-up-suggestion](https://user-images.githubusercontent.com/74826234/128632337-d764244a-87ff-426d-8e84-83c162dd3a76.png)
So instead of the taken slots disappearing, they change appearance, become unclickable and display the name of the person that has taken the slot. Then the other volunteers would know - oh, the shift from 10:40 to 10:50 was covered by Stevie Wonder so it's him I should ask why the neighbours complained about too loud funk music.

**Comment by mihaic195** [comment]
I would agree with saying that the time slot is reserved, which can be nice to have, but not to show who has reserved it.

**Comment by emrysal** [comment]
I'm currently very far along implementing this like so, this is expected this week:

![image](https://user-images.githubusercontent.com/1046695/128851532-26e32c90-f617-4f71-a330-98186d64e086.png)

**Comment by bilfri** [comment]
That's so awesome @emrysal!
It's a bit different from the reason I originally suggested the issue though. To me the idea is about being able to communicate directly to the other people that have signed up without all communication having to pass by the calendso admin. The purpose would be to reduce the organisational overhead, by letting eg. volunteers sort issues out by themselves. Ideally we'll want everyone 'on the floor' and no one having to sit at a desk with e-mails. Calendso already gives a big jump towards that dream, but I think the suggested feature could make it better yet (and support a use case that calendly doesn't). 

I definitely see the point about privacy. And I also like the simplicity of only showing empty slots. So I wouldn't suggest this to be the default, but instead one of the options that could be set when creating the event. For my use case it would be enough to show the name that people sign up with, since most of the volunteers at our cafe know each other. But, I also think the more general case where people would be able to e-mail others that have signed up is also very valid, even though it would need to come with additional spam protection and so on.

Just my two cents, hope you like it.
