### ISSUE TITLE
"Something went wrong when authorizing this app." during installation of Slack via App store

### ISSUE THREAD

**Issue by jakw0j** [calcom/cal.com#4262]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to install Slack App I am presented with the screen "Something went wrong when authorising this app"
"Error details
Invalid client_id parameter"

### Steps to Reproduce

1. Went to "App Store"
2. Clicked on Slack
3. Clicked on Install
4. After series of redirections I've landed on aforementioned website with error

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

OS: macOS Version 12.5.1 (Build 21G83)

Every browser that I've tried.
Microsoft Edge Version 105.0.1343.27 (Official build) (arm64)
Google Chrome Version 105.0.5195.102 (Official Build) (arm64)
Vivaldi 5.4.2753.47 (Stable channel) (arm64)

**Comment by PeerRich** [comment]
thank you for the ticket, @sean-brydon will be fixing this for 2.1 which starts after 15th of September.🙏

**Comment by sean-brydon** [comment]
More info: https://github.com/calcom/cal.com/issues/4268#issuecomment-1240532896

**Comment by PeerRich** [comment]
we will bring slack back eventually
