### ISSUE TITLE
/event-types/detail wrong empty screen for workflows

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4265]
- [ ] border missing
- [ ] button should be secondary

Should look like empty screen for Apps:
<img width="1206" alt="Screenshot 2022-09-22 at 16 23 46" src="https://user-images.githubusercontent.com/30310907/191843953-adb9e334-27ee-415f-b3f1-96d26565d828.png">

**Comment by sean-brydon** [comment]
@PeerRich I actually believe them update/cancel buttons are meant to be deleted - I removed them way back when but it looks like they made their way back in with a merge along the lines 

https://media.giphy.com/media/xCyjMEYF9H2ZcLqf7t/giphy.gif

**Comment by matheusmuniz03** [comment]
Hi @PeerRich!  How do i get to this page?

**Comment by PeerRich** [comment]
> Hi @PeerRich!  How do i get to this page?

you can opt-in to v2 at the bottom left

**Comment by sean-brydon** [comment]
Hi @matheusmuniz03 are you still interested in picking this up? If so could you let us know ASAP so we can pick this issue up if not - we would like to get this resolved for our V2 release

**Comment by matheusmuniz03** [comment]
@PeerRich @sean-brydon 
Guys, I updated the project and my screen is like this (with the border and without the button). Do you want me to implement both buttons (Cancel and Update) or do you prefer to open another updated issue?

![Captura de tela de 2022-09-12 14-09-48](https://user-images.githubusercontent.com/87545749/189716540-e017d448-d06d-4f3b-a3ec-e3df620b5bb3.png)

**Comment by matheusmuniz03** [comment]
Hey @PeerRich, I was trying to resolve this issue, but I noticed that the "cancel" and "update" buttons no longer exist in the "Apps" part. Is the implementation needed for "Workflows"?
Loom Video: https://www.loom.com/share/ea94b07dafcd44ba8c0d782797f354a4

**Comment by CarinaWolli** [comment]
> Hey @PeerRich, I was trying to resolve this issue, but I noticed that the "cancel" and "update" buttons no longer exist in the "Apps" part. Is the implementation needed for "Workflows"?

@matheusmuniz03 The update/cancel button is no longer needed Workflows. But the border is still missing and the button should be secondary. I will update the issue
