### ISSUE TITLE
slack broken

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4268]
- logo
- also app in general

<img width="247" alt="CleanShot 2022-09-08 at 11 13 00@2x" src="https://user-images.githubusercontent.com/8019099/189083983-185cd850-e530-4547-9d1b-2f2fa3547e59.png">

**Comment by sean-brydon** [comment]
Still waiting for slack support to get back to me - they're super confused how our app has just vanished from their marketplace with no errors on ourside/theirs 

Will give it a few more days for them to respond - If not I'll create a new app in their marketplace (Only downside is we have to wait for verification again :( )
