### ISSUE TITLE
/availability - list-item using old icon button component

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4275]
looks like old button component?

![Image](https://user-images.githubusercontent.com/4536123/189093928-7d7a7388-2c76-4c96-a206-d7e00bdc65eb.png)

**Comment by PeerRich** [comment]
ah shit, this is out of date. @Jaibles made some last minute changes: https://github.com/calcom/cal.com/issues/4186

**Comment by emrysal** [comment]
Re-open as /event-types is out of date but this issue is talking about /availability - fix is in #4281 which I believe is final

**Comment by PeerRich** [comment]
both should have these buttons: https://github.com/calcom/cal.com/issues/4186 but we can merge this and then do a follow up PR
