### ISSUE TITLE
/app-store/category page - app cards missing install button

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4287]
![Image](https://user-images.githubusercontent.com/4536123/189122998-95374eb0-e45a-4fdb-a093-012c77965fc0.png)

**Comment by MuriloAmarals** [comment]
Hey @Jaibles on my localhost it's different
![image](https://user-images.githubusercontent.com/87545137/189741165-ff99a271-73d0-4f1d-b599-43cb90c62a81.png)

**Comment by leog** [comment]
Hey @MuriloAmarals. @Jaibles is talking about the categories page under `/apps/categories/calendar` for example. And I have the answer about why that happens Ciarán extracted from [here](https://github.com/calcom/cal.com/pull/4220#issuecomment-1244210225): 

> This is by design. The reason that we can't have it in v2 is that the categories page is static, using the credential version of app registry to populate the page will make the page dynamic, and as discussed with @zomars we prioritize loading the entire page faster than make an app installable from it.
