### ISSUE TITLE
[CAL-101] Add/Edit location dialog: "can't find the right video app? visit our app store"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4298]
link with target="_blank" to app store here: 

"Can't find the right video app? Visit our `<a target="_blank" href="/apps/categories/video">App Store</a>`"

make sure to use i18n correctly: https://react.i18next.com/latest/trans-component#using-with-react-components

<img width="596" alt="CleanShot 2022-09-08 at 17 21 18@2x" src="https://user-images.githubusercontent.com/8019099/189161454-12bd5894-72be-486c-bdf4-d448fb946873.png">

**Comment by sean-brydon** [comment]
Gonna leave this as a note:  You'd best be using the `Link` component from next instead of `a`

**Comment by PeerRich** [comment]
ah yes of course

**Comment by SauravL3010** [comment]
I am working on this one. 
I was wondering, if there is a easier way to translate the given text to all supported languages ? 

PS. I am new to i18n standards, I started manually translating the text to different languages, please let me know, if there is a better approach. 


This is what it looks like:
![Image](https://user-images.githubusercontent.com/65268462/195640974-ed5c368a-5e35-464b-8f22-27d2b164078b.png)

**Comment by MatheusBeniniF** [comment]
> I am working on this one. 
> I was wondering, if there is a easier way to translate the given text to all supported languages ? 
> 
> PS. I am new to i18n standards, I started manually translating the text to different languages, please let me know, if there is a better approach. 
> 
> 
> This is what it looks like:
> ![Image](https://user-images.githubusercontent.com/65268462/195640974-ed5c368a-5e35-464b-8f22-27d2b164078b.png)
> 
> 

Hey @SauravL3010, Im already worked on that and the PR is ready for review.

**Comment by SauravL3010** [comment]
@MatheusBeniniF thanks for letting me know, can I checkout your PR ? 
Whats your workaround for i18n ? do you translate the text for each language ?
