### ISSUE TITLE
Unable to reschedule meeting. (Phone number input disabled)

### ISSUE THREAD

**Issue by owen-whalecard** [calcom/cal.com#4299]
### Issue Summary

When trying to rebook meetings the phone number parameter is unable to be input into.

### Steps to Reproduce

1. Schedule a meeting.
2. Go to email response for successful meeting booked.
3. Click "manage this event"
4. Try to rebook meeting at another time
5. Unable to fill in phone number parameter to complete the rescheduling

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Unable to reschedule meetings through prompt will need to cancel then reschedule.

### Technical details

https://user-images.githubusercontent.com/100158053/189160705-71727124-37c5-47ab-97b7-1a4ecda65314.mov

**Comment by PeerRich** [comment]
@alishaz-polymath can you give this a look? it seems like we shouldn't make these required + disabled? alternatively keep them required but enabled?

**Comment by alishaz-polymath** [comment]
Yep, on it 🙏

**Comment by CarinaWolli** [comment]
Fixed by #4322
