### ISSUE TITLE
new <Button> has no dark mode

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4303]
since we use the v2 Button component on some public booking pages, that have dark mode, we need dark buttons for primary and secondary 

<img width="288" alt="CleanShot 2022-09-08 at 18 23 23@2x" src="https://user-images.githubusercontent.com/8019099/189174748-5d70704e-be71-4442-8da4-cd166a48953d.png">

also, focus is broken:

![image](https://user-images.githubusercontent.com/8019099/190645620-2692325a-8dc4-4a38-9922-702160bd35e7.png)

**Comment by sean-brydon** [comment]
There is a reason why a lot of components don''t currently have dark mode built in - If we start adding dark mode to button components before we have V2 main screens dark mode - we will have random elements in light mode that take on dark mode (due to system default)

**Comment by PeerRich** [comment]
i see. so we need dark mode for the entire logged in area firstß

**Comment by sean-brydon** [comment]
I believe so - I'm not entirely sure if we force white mode in the entire logged in area (then check system preferences for public) 

But to my understanding we just don't have any dark mode components in the logged in area. Will do some testing in the morning in regards to this :)

**Comment by Jaibles** [comment]
https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=198%3A41491

**Comment by PeerRich** [comment]
the Button component should get a hasDark prop (boolean) so we can enable it on public booking pages

**Comment by PeerRich** [comment]
or maybe wrapping it in `<div className="light">` helps? haven't tried
