### ISSUE TITLE
When booking a meeting on a mobile device, after date select available time slots render out of view with no visual interaction.

### ISSUE THREAD

**Issue by isaiahdahl** [calcom/cal.com#4307]
### Is your proposal related to a problem?

I think that this is a UX problem. When I book a meeting on a mobile device, after I select a calendar date, all of the available time slots render below the calendar. But there is no UI interaction that lets me know that happened, SO I click again, until I realize you can scroll down to see the available time slots.

Here's a screen capture: 

Notice around second 9, when I select the date. That's the part I'm having a hiccup with. 

https://user-images.githubusercontent.com/23046374/189177473-307e471b-ab69-450e-bc9d-139bd16d3be5.MP4

### Describe the solution you'd like

I'd like a better experience as a user for booking a meeting. Or as someone who is sending this link out, I want the people who will commonly use it on a phone to have a good experience. 

Maybe the calendar could close into a summary view of the selected day, that when clicked would open back up to the calendar, but while a day is selected, you at least have the time slots brought into the field of view.

### Additional context

I'm self-hosting, updated to the latest 1.9.4

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. I can't reproduce this on the hosted account but will notify our team to investigate this.

**Comment by PeerRich** [comment]
i believe this has been fixed a long time ago. can you try again with the most recent version?

we added a scrollDown function when clicking
