### ISSUE TITLE
merge /team layout with user layout

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4316]
right now we have code duplication for the teams page:

https://cal.com/team/cal and https://cal.com/peer

that should use the same component

**Comment by Udit-takkar** [comment]
is there any specific part of the page which you want to abstract and create component ? or we need a one shared component which would handle both the pages completely?

**Comment by nnaemekaibe** [comment]
I'll be working on this. @PeerRich

**Comment by nikospapcom** [comment]
@PeerRich can I work on this? is still available?

**Comment by PeerRich** [comment]
@nikospapcom yes still available. maybe team up with @Udit-takkar ?

**Comment by Udit-takkar** [comment]
hey @nikospapcom  you can work on this issue. just ping me on slack if you face any problems.

**Comment by PeerRich** [comment]
after new booking page!
