### ISSUE TITLE
getBusyTimes doesn't consider user busy unless they are the booking owner.

### ISSUE THREAD

**Issue by isaiahdahl** [calcom/cal.com#4318]
### Issue Summary

With a collective booking, when a meeting is accepted. All people who are attached to that event type should have their availability blocked off for that booking. 

Currently, it will only consider the event owner blocked off. 

### Steps to Reproduce

1. Create a collective booking with more than one member.
2. Book the "collective event"
3. try and book a personal meeting with one of the members that didn't initially create that collective booking during the same time slot as the collective event.

When you got to step 3, every person in the collective event should be considered busy during that time slot.

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our team will address this.

**Comment by isaiahdahl** [comment]
@milospuac it didn't seem to link here but I did open a PR with the fix.

**Comment by PeerRich** [comment]
@emrysal any insights why #4319 was closed?
