### ISSUE TITLE
replace <Loader> with <Skeleton>

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4332]
only files in /v2/ for now since we will remove /v1/ soon

- [x] EventTypeSingleLayout
- [ ] availability @emrysal 
- [x] Apps Setup @CarinaWolli 
- [x] Troubleshooter @emrysal 
- [x] Workflows @CarinaWolli 

maybe @zomars can help out, too

<img width="585" alt="CleanShot 2022-09-09 at 12 24 09@2x" src="https://user-images.githubusercontent.com/8019099/189329323-214329f0-c06b-4c99-a7cd-977b1e6067cb.png">

**Comment by PeerRich** [comment]
@CarinaWolli most of them are still in workflows, not sure if you are working on that already

**Comment by emrysal** [comment]
PR for troubleshooter @ https://github.com/calcom/cal.com/pull/4335

**Comment by CarinaWolli** [comment]
@PeerRich Not yet, will start after I am done with teams settings

**Comment by emrysal** [comment]
@PeerRich  The EventTypeSingleLayout uses the feather icon loader

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1046695/190247115-916cc705-a4b1-414a-8e16-0752ed4f2e5e.png">

We may want to keep it in the AuthContainer though.. @sean-brydon ?

**Comment by emrysal** [comment]
Found no remaining instances in packages/app-store, well done @CarinaWolli
