### ISSUE TITLE
Other means of going back to calendar

### ISSUE THREAD

**Issue by mluks-klap** [calcom/cal.com#4338]
When on the time slot booking page (the one where the person booking provides their details), it would be nice if there was a more obvious button to go back to the calendar / the previous page. The "Cancel" button is subtle and makes it sound quite final.

**Comment by PeerRich** [comment]
what do you recommend instead?

**Comment by mluks-klap** [comment]
Probably a button in the top left corner with something along
the lines of:

⬅️ Back to calendar



--
Marvin Luksenberg

**Comment by jaysoni-ash42** [comment]
@PeerRich  is this issue still active ? CC @mluks-klap

**Comment by PeerRich** [comment]
i believe this has been fixed a long time ago. can you try again with the most recent version?
