### ISSUE TITLE
app store: button layout odd on mobile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4339]
![image](https://user-images.githubusercontent.com/8019099/189362260-fc51af8e-717f-4f15-84a1-570283286078.png)

**Comment by matheusmuniz03** [comment]
I'm trying but my page is like this
![Captura de tela de 2022-09-09 14-10-06](https://user-images.githubusercontent.com/87545749/189406633-30036ba7-a69b-4fde-ae18-41f8bd4ea827.png)

**Comment by PeerRich** [comment]
fixed by @leog
