### ISSUE TITLE
/public-booking - The timezone if very far away from the times

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4341]
![Image](https://user-images.githubusercontent.com/4536123/189388024-2101a584-9cb9-4f5a-9c96-10a229f4dce4.png)

**Comment by PeerRich** [comment]
yeah I think we should move it somewhere else
<img width="166" alt="CleanShot 2022-09-10 at 17 54 11@2x" src="https://user-images.githubusercontent.com/8019099/189491365-1e2372cc-7727-4bc4-a92a-9cc842c96789.png">

**Comment by MatheusBeniniF** [comment]
Hi @Jaibles @PeerRich, where should we put the time zone?

**Comment by Jaibles** [comment]
I'm honestly not sure I'm in favour of moving this over there. We also have a separate pr in the works that puts the 12/24hr toggle top right too. I think it's going to get very cluttered.

**Comment by MatheusBeniniF** [comment]
so should we ignore it?

**Comment by Jaibles** [comment]
That's my vote. @PeerRich any thoughts on this?
