### ISSUE TITLE
Booking - Confirmation screen shows a different title than calendar invite

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4342]
<img width="765" alt="CleanShot 2022-09-09 at 16 40 39@2x" src="https://user-images.githubusercontent.com/4536123/189388873-dbfa4b4a-3ace-44e0-8c1c-9c2623abfb66.png">

As the person booking, it would be nice if the calendar invite actually included the name of your company (Cal.com) versus only the person's name

**Comment by rksingh2001** [comment]
Hey, Can I take up this issue?

**Comment by PeerRich** [comment]
> Hey, Can I take up this issue?

yes please @rksingh2001

**Comment by berat** [comment]
If anybody doesn't take it, maybe I can try

**Comment by arjunbharti** [comment]
I was trying to replicate the issue but seems like it is already resolved by someone. So, the maintainer can close this one!
cc @baileypumfleet @hariombalhara
