### ISSUE TITLE
/onboarding/step-4 - Upload button looks weird

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4343]
![Image](https://user-images.githubusercontent.com/4536123/189389538-f69c6c20-2f23-4857-97de-d5556a072530.png)

**Comment by Udit-takkar** [comment]
<img width="335" alt="Screenshot 2022-09-10 at 3 12 15 PM" src="https://user-images.githubusercontent.com/53316345/189477900-e86255be-163e-4cdd-9293-65cfe8653d2a.png">

Can't figure out what is causing this dark gray corners only in safari. do you have any idea @PeerRich  ?

**Comment by PeerRich** [comment]
> <img width="335" alt="Screenshot 2022-09-10 at 3 12 15 PM" src="https://user-images.githubusercontent.com/53316345/189477900-e86255be-163e-4cdd-9293-65cfe8653d2a.png">
> 
> 
> 
> Can't figure out what is causing this dark gray corners only in safari. do you have any idea @PeerRich  ?

can you try this? https://tailwindcss.com/docs/appearance

**Comment by Udit-takkar** [comment]
> > <img alt="Screenshot 2022-09-10 at 3 12 15 PM" width="335" src="https://user-images.githubusercontent.com/53316345/189477900-e86255be-163e-4cdd-9293-65cfe8653d2a.png">
> > Can't figure out what is causing this dark gray corners only in safari. do you have any idea @PeerRich  ?
> 
> can you try this? https://tailwindcss.com/docs/appearance

already tried appearance-none on button component.

**Comment by PeerRich** [comment]
very odd. is this for every button on safari or just this one?

**Comment by CarinaWolli** [comment]
@Udit-takkar & @PeerRich, I fixed it in my PR. Not sure why this happened, but this fixes it: https://github.com/calcom/cal.com/pull/4350/files#r967962730
