### ISSUE TITLE
/public-booking 12/24hr toggle is broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4353]
https://user-images.githubusercontent.com/4536123/189479672-9e041d2a-2697-4221-8f43-d0c9899d4a64.mp4

https://user-images.githubusercontent.com/4536123/189479640-50f65fa0-edc3-4d89-a3f4-bce71edb12d1.mp4

**Comment by PeerRich** [comment]
it should use the new switch we have
