### ISSUE TITLE
Email title includes wrong time?

### ISSUE THREAD

**Issue by ColinChartier** [calcom/cal.com#436]
I got this email from calendso today:

New event: Rick Astley - 4:00 PM Wednesday, August 11, 2021 - Technical Support

Both me and the invitee are in ET, but the ics file includes:
```
DTSTART:20210811T150000Z
```

i.e., 3pm UTC / 11am EDT.

Where did the 4pm in the email title come from?

**Comment by joshsny** [comment]
I have also experienced the wrong time in the email title. Has anyone else reproduced this?

**Comment by baileypumfleet** [comment]
This should have been fixed. Can anyone confirm if this is still happening?

**Comment by sean-brydon** [comment]
This ticket appears to be fixed and due to inactivity it is being closed- please reopen if you experience this issue again.
