### ISSUE TITLE
Ability to block specific dates (e.g. vacation)

### ISSUE THREAD

**Issue by kpak130** [calcom/cal.com#4362]
### Is your proposal related to a problem?

Oftentimes, I want to block certain dates like when I'll be on vacation. Currently, there isn't any way to block specific dates.

### Describe the solution you'd like
Add an ability in the availability to block certain dates and times (See Calendly's 'Add date overrides' feature)

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by milospuac** [comment]
Hi there

Thank you for reaching out. This can be done with your integrated calendar. You can create all-day events in your integrated calendar (for example holidays) and set those days to Busy. Cal.com "sees" those days and will block them accordingly.

See how I've done this with my Google Cal connection
<img width="755" alt="Screenshot 2022-09-12 at 11 36 49" src="https://user-images.githubusercontent.com/97884287/189629934-9257474a-df3b-472a-bb19-9974754da3a4.png">

The selected dates will be blocked on your booking page

<img width="781" alt="Screenshot 2022-09-12 at 11 39 38" src="https://user-images.githubusercontent.com/97884287/189630034-b6414400-5eef-479e-b342-6e84a99c1b07.png">

Let me know if this helps
