### ISSUE TITLE
opening a dropdown blocks scroll unless focus changes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4363]
i believe this is supposed to be fixed by radix ui but i am not sure if we updated everything yet

https://user-images.githubusercontent.com/8019099/189540605-29330bf4-997e-4477-a454-3c405b7def19.MOV

**Comment by MuriloAmarals** [comment]
Hey @PeerRich this behavior is default of radix, it adds, for example, pointer-avents-none to the body when the dropdown is opened. I don't know how I can resolve this default behavior.

**Comment by PeerRich** [comment]
hmm thats pretty annoying.. maybe it was fixed in a new radix update? #4151

**Comment by PeerRich** [comment]
ideally we find a way to fix this. again, haven't tried the latest radix update yet. maybe we can also open a ticket in radix

**Comment by PeerRich** [comment]
@JeroenReumkens maybe you find a way to fix this?

**Comment by JeroenReumkens** [comment]
@PeerRich  Just retested this and it seems to be working for me! I think the recent update to Radix 1.0 indeed fixed this. Could you please retest?
