### ISSUE TITLE
[CAL-113] routing forms needs mobile love

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4365]
https://user-images.githubusercontent.com/8019099/189541050-e69c3014-ffd0-44c8-9214-65d98086253a.MOV

**Comment by jaysoni-ash42** [comment]
@PeerRich  i want to work on this issue. but didn't get what needs to be done can you add more details on the description?

**Comment by sean-brydon** [comment]
@jaysoni-ash42 if you'd like to pick this up - I'd take some inspiration from other mobile pages - `https://app.cal.com/event-types/[type]` is a good example

If you'd like some designs to work off please let me / @Jaibles know

**Comment by jaysoni-ash42** [comment]
@sean-brydon  yeah designs would be great CC @Jaibles

**Comment by PeerRich** [comment]
@jaysoni-ash42 i assigned you

**Comment by JeroenReumkens** [comment]
@jaysoni-ash42  Do you think you still have time to pick this up? Otherwise I could take over from you. Thanks 🙏

**Comment by Jaibles** [comment]
Designs at the bottom of [this page ](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak?node-id=26:101616&comments-enabled=1) for reference.

**Comment by Toledodev** [comment]
I think this has been resolved: [loom](https://www.loom.com/share/c66e3e60aa404958a27294f91123e805)
