### ISSUE TITLE
[CAL-114] better design for public booking empty screen

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4366]
if someone has no public event-types:

<img width="1062" alt="CleanShot 2022-09-11 at 19 44 29@2x" src="https://user-images.githubusercontent.com/8019099/189541601-903151be-ffbf-40d0-b572-5eee51c00614.png">

**Comment by MatheusBeniniF** [comment]
Hi @PeerRich and @Jaibles, Is this printscreen the new design you want?

**Comment by PeerRich** [comment]
we dont have designs yet, @Jaibles comes back to office monday

**Comment by MatheusBeniniF** [comment]
some updates on that?

**Comment by PeerRich** [comment]
priority has changed for 2.2 which is next month

**Comment by Jaibles** [comment]
Two options proposed here for designs: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=20797%3A168990

**Comment by PeerRich** [comment]
we should not expose the users email there

**Comment by Jaibles** [comment]
We can drop that. Was just a proposal for if a user wanted to choose to explose it.
