### ISSUE TITLE
operation app store screenshots

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4367]
we need min 3 screenshots for each app

apps without screenshots:

- [x] apple calendar
- [x] CalDav
- [ ] Microsoft Exchange 2013 Calendar
- [ ] Microsoft Exchange 2016 Calendar
- [x] Cal Video
- [x] Jitsi Video (only one right now)
- [x] Close.com (only one right now)
- [x] Rainbow (description broken, too)
- [x] Zapier
- [ ] Routing Forms
- [x] Whereby (only two right now)
- [x] Around (only one right now)

**Comment by sydwardrae** [comment]
https://drive.google.com/drive/folders/15ccM0ytpxL5YEDwiqjUEAOIjUJeHrX9U?usp=sharing

**Comment by sydwardrae** [comment]
https://drive.google.com/drive/folders/1LYMFF9WEnOAbzm7A-OHPoAd_mLI4l6Z0?usp=sharing

**Comment by sydwardrae** [comment]
https://drive.google.com/drive/folders/1wbl3Qbp1oHCdDId5XY0K1JMSL9TtxNL5?usp=sharing

**Comment by sydwardrae** [comment]
@PeerRich can we also do videos in addition to the screencaps? aka would you want the routing forms vid in there?

**Comment by sydwardrae** [comment]
also, for the Cal Video, do you want to use Daily product pics? or should we use only Cal Video stuff? we don't have a ton right now of just Cal video, and Daily has some great resources lmk

**Comment by PeerRich** [comment]
> @PeerRich can we also do videos in addition to the screencaps? aka would you want the routing forms vid in there?

that's a great idea. will do

**Comment by PeerRich** [comment]
> also, for the Cal Video, do you want to use Daily product pics? or should we use only Cal Video stuff? we don't have a ton right now of just Cal video, and Daily has some great resources lmk

daily should be nice
