### ISSUE TITLE
V2 - When href is applied to dropdown menu item styling is wrong

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#4377]
When "href" gets applied to menu item it loses all styling

![CleanShot 2022-09-12 at 09 43 36](https://user-images.githubusercontent.com/55134778/189610917-28179e9d-1dd6-4054-af8f-f18cd34cfbc6.png)

This seems to only happen in safari :')

**Comment by PeerRich** [comment]
fixed
