### ISSUE TITLE
/availability /single-view -  Plus icon-button & "Copy to all" button UI & copy issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4381]
- [x] Remove the copy all button

Current

![CleanShot 2022-09-12 at 11 01 57@2x](https://user-images.githubusercontent.com/4536123/189627020-aafcd391-73a3-4d8b-866c-42a0c3cb7922.png)

- [ ] Plus in the icon button shuold be same as the copy one.

<img width="674" alt="CleanShot 2022-09-12 at 11 06 25@2x" src="https://user-images.githubusercontent.com/4536123/189627872-60a35de8-8d9a-4ce1-a6f6-67f4c9a8580e.png">

**Comment by JeroenReumkens** [comment]
Picking this one up 🙋‍♂️

**Comment by emrysal** [comment]
Hi @JeroenReumkens - Pinging you to let you know that a new version of the Schedule is currently under development for the Availability single view / Date override functionality, as part of this I need to touch the button rendering system as copy functionality is not desirable in standalone day mode. Hope I caught you before you did any work on this :)

**Comment by JeroenReumkens** [comment]
Thanks for the heads up @emrysal! I already did work on this for a bit, but it definitely makes sense to scratch this if there's a new version coming up 😄
