### ISSUE TITLE
Multiple seats for an event - can't book more than 1 seat

### ISSUE THREAD

**Issue by clafee** [calcom/cal.com#4387]
### Issue Summary

Hello,

I created an event with multiple time slots, each with 5 seats available. I gave the link to my users. The first one to book a specific time slot has no issues. At this time, there are now 4/5 seats available. However, when a second user wants to book the same time slot, he is faced with the name and email address of the previous user. Once this second user enters his informations, the following error appears : (translated part, originally in french) The meeting couldn't be booked. (second part of the error is in english) No available users found.

### Steps to Reproduce

1. Go to the booking page
2. On a time slot where multiple seats are available, and one is already taken, click to book
3. You will see the name/email address of the user who has booked the first seat. Replace his name and email, click submit, and you'll have the error message.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser: MS Edge, Version 105.0.1343.33 (Incognito Window)
- Calendar hosted on Cal.com (free version)

Thanks

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. 

Our team will look into this issue.

**Comment by deganl** [comment]
Hi, any news here? We have the same problem with the self hosted version. I tried with 1.9.4 and 2.0.1.

**Comment by PeerRich** [comment]
@joeauyeung can you look into this?

**Comment by joeauyeung** [comment]
This is fixed with #4646 in v2.0.2. Just tested on production to confirm and it should be working now.
