### ISSUE TITLE
[CAL-628] When cancelling a Zoom meeting, Google Calendar event or Office Calendar event the booking is not cancelled

### ISSUE THREAD

**Issue by joshsny** [calcom/cal.com#439]
There is no functionality ~for webhooks~ to handle when someone cancels an event from their calendar or the zoom meeting from Zoom.

Cancelling the event from your calendar is quite a common occurrence, so I think it's important to get that working.

To do:

- [ ] Setup event webhooks for Google Calendar
- [ ] Setup event webhooks for Microsoft Office Calendar
- [ ] Setup meeting webhooks for Zoom

I thought I'd submit this as an issue in case people already started working on some of this functionality.

<sub>[CAL-628](https://linear.app/calcom/issue/CAL-628/when-cancelling-a-zoom-meeting-google-calendar-event-or-office)</sub>

**Comment by ConnorGargano** [comment]
Hi @joshsny,
I have created a ticket for you and have sent the issue to the engineering team
-Thanks Connor

**Comment by PeerRich** [comment]
@alishaz-polymath is this something you can look into?

**Comment by alishaz-polymath** [comment]
I can explore this. I believe we do not have such a functionality in place to begin with, but I can take a look to see what's needed to get this working 👍

**Comment by PeerRich** [comment]
especially removing from a calendar should cancel the event. most scheduling apps do that. surprised we dont do that yet

**Comment by PeerRich** [comment]
i'd say for now you should cancel meetings in the calendar, not in zoom
