### ISSUE TITLE
Mobile: hide bottom nav on any sub page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4398]
use next router and check if it has two /stuff/ slashes 

hide bottom nav on detail pages:
- /event-types/123
- /workflows/123

etc

use auto-animate

![image](https://user-images.githubusercontent.com/8019099/189693267-ae6c33b7-d8ef-4dca-ab53-d5025523c4e8.jpeg)

**Comment by PeerRich** [comment]
maybe even giving it margin bottom -100px may give a cool animation effect

**Comment by hariombalhara** [comment]
What's the motivation here @PeerRich? I would want the nav on subpages as well to quickly go to any other main page.

**Comment by PeerRich** [comment]
@Jaibles and i discussed its better to not have it on sub pages.

whats your motivation to keep it on sub pages? most apps hide it (i.e. Whatsapp)

**Comment by hariombalhara** [comment]
A navigation is for ease of access of important pages. I personally prefer the nav to be always there no matter which page is it.
e.g.  On Upcoming bookings page, I am seeing the list of upcoming bookings for an event. Now, if I want to edit the EventType, I don't see any link to go to Event Types(which means that probably every subpage should have a back button, before that's there, it would be wrong to remove navigation.)
Even if there was a back button, that's an unnecessary click of a Back button that I need to do to reach Event Types page.

<img width="486" alt="Screenshot 2022-09-22 at 10 01 56 AM" src="https://user-images.githubusercontent.com/1780212/191658873-b909cd33-d6e3-4bfe-8533-05071935d52f.png">

**Comment by Jaibles** [comment]
@PeerRich @hariombalhara I definitely did not expect the nav to hide on the booking page. I guess technically whatever way we defined in code, these tabs created an "inner" page, but they would not be what I would define an inner page. 

Things I would define as an inner page are when you click into are  

- [ ] Event type edit
- [ ] Availability Preset
- [ ] Workflow edit
- [ ] App single or App category
- [ ] Routing form edit

**Comment by PeerRich** [comment]
> @PeerRich @hariombalhara I definitely did not expect the nav to hide on the booking page. I suspect by the fact that this happens as soon as you click bookings in the nav, that this was an oversight. Perhaps technically whatever way we defined in code, these tabs created an "inner" page? They would not be what I would define as an inner page. 
> 
> 
> 
> Things I would define as an inner page are when you click into are:
> 
> 
> 
> - [ ] Event type edit
> 
> - [ ] Availability Preset
> 
> - [ ] Workflow edit
> 
> - [ ] App single or App category
> 
> - [ ] Routing form edit
> 
> 
> 
> Essentially all pages that have a back button on desktop.
> 
> 
> 
> [Issue created](https://github.com/calcom/cal.com/issues/4664)
> 
> 
> 
> <img width="1304" alt="CleanShot 2022-09-22 at 09 38 32@2x" src="https://user-images.githubusercontent.com/4536123/191700325-9af636a2-cbeb-4ef9-b328-144ab3fd5354.png">
> 
> 

ok lets undo the bottom nav PR @hariombalhara
