### ISSUE TITLE
[CAL-636] Recurring events time is off after several occurrences

### ISSUE THREAD

**Issue by carlosrojas** [calcom/cal.com#4400]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

After x number of occurrences the time shifts back by one hour. This seems to be due to daylight savings. See image in Pacific time zone.

<img width="339" alt="Screen Shot 2022-09-12 at 10 23 15" src="https://user-images.githubusercontent.com/1188898/189717399-92344717-9364-4f56-adca-7f1405d5f86a.png">

### Steps to Reproduce

1. In event settings, set recurring event
2. Any date after daylight saving ends will be shifted back by an hour.

I would expect the time to stay the same even if there's a daylight saving change.

### Technical details
- Node.js version: 16.17.0
- Cal Version 1.9.4

<sub>[CAL-636](https://linear.app/calcom/issue/CAL-636/recurring-events-time-is-off-after-several-occurrences)</sub>

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out

Our team will look into this.

**Comment by mrkirchner** [comment]
also running into this issue due to daylight savings

**Comment by PeerRich** [comment]
@emrysal I believe worked on some DST, not sure if it works with recurring, too. cc @leog

**Comment by emrysal** [comment]
This has been fixed for a while - I remember @leog and I having a few pair programming sessions to get to the bottom of this - apologies for the late close.
