### ISSUE TITLE
Floating action buttons on mobile issues

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#4407]
https://user-images.githubusercontent.com/3504472/189771243-10366d14-7cc4-4ebc-933d-7334a15328b4.MOV

This happens on iOS Safari

**Comment by jaysoni-ash42** [comment]
@PeerRich  i want to work on this issue? what should be done make the icons to be on top of the screen like on other screen?

**Comment by PeerRich** [comment]
fixed in https://github.com/calcom/cal.com/pull/4741
