### ISSUE TITLE
/availability /detail-view - "Copy" icon-button dropdown issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4412]
- [ ] When the copy icon button is active, it should be in focus state instead of the default.
- [ ] Need more spacing for the dropdown. Bottom row buttons should be Cancel, Apply

Current
<img width="956" alt="CleanShot 2022-09-13 at 05 46 25@2x" src="https://user-images.githubusercontent.com/4536123/189811076-a90c9feb-105c-4d90-836a-b08143176f3b.png">

Should be
<img width="1480" alt="CleanShot 2022-09-13 at 05 45 38@2x" src="https://user-images.githubusercontent.com/4536123/189811088-2ab797b6-7ca7-454b-89e7-9d147b2787f3.png">

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=19152%3A177957)

**Comment by emrysal** [comment]
What do you think about the following implementation @Jaibles ? Proposing a slightly decreased width so we can keep auto-width but otherwise as per design.

![image](https://user-images.githubusercontent.com/1046695/190189054-bdd1d062-ce74-4032-a29f-530c70d075b3.png)

**Comment by Jaibles** [comment]
Looks great @emrysal 👍
