### ISSUE TITLE
/availability - default badge should be a toggle

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4413]
Set as default should be as toggle instead of the icon+default.

Currently
![CleanShot 2022-09-13 at 05 48 22@2x](https://user-images.githubusercontent.com/4536123/189811326-ac94d2d5-242b-46bd-82ce-0c707432322f.png)

Should be
<img width="568" alt="CleanShot 2022-09-13 at 05 49 18@2x" src="https://user-images.githubusercontent.com/4536123/189811425-a301d81e-5efd-447c-b403-caf901f9b2db.png">

**Comment by G3root** [comment]
i'd like to take on this issue
