### ISSUE TITLE
/availlabillity - save button position should be top right

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4414]
Currently 
<img width="1202" alt="CleanShot 2022-09-13 at 05 52 33@2x" src="https://user-images.githubusercontent.com/4536123/189811792-73978e18-54cb-44a7-a20f-9d2f00f29887.png">

Should be 
<img width="1623" alt="CleanShot 2022-09-13 at 05 50 27@2x" src="https://user-images.githubusercontent.com/4536123/189811801-a28b4c18-eeb4-4586-afd1-65c8cc8c646b.png">

**Comment by Emmanuel-Melon** [comment]
@Jaibles what about the cancel button? Should it remain in the same position?

**Comment by Jaibles** [comment]
@Emmanuel-Melon the Cancel button is replaced by a back icon button beside the title.

**Comment by Emmanuel-Melon** [comment]
> @Emmanuel-Melon the Cancel button is replaced by a back icon button beside the title.

Got it! It seems like the issue has already been resolved. There's a slight difference. Can I still go ahead and make a PR to match the design you shared?

<img width="1920" alt="Screen Shot 2022-09-20 at 13 29 22" src="https://user-images.githubusercontent.com/21015204/191235163-2b131706-fec4-449c-92c5-1252f7e76165.png">

**Comment by Emmanuel-Melon** [comment]
@Jaibles I'd also like your feedback on this other [issue](https://github.com/calcom/cal.com/issues/4523#issuecomment-1250697068)

**Comment by MatheusBeniniF** [comment]
@Jaibles, this issue has already solved, right?
![image](https://user-images.githubusercontent.com/88898100/197633395-0cad8c1c-7c1f-410b-b436-b6dcb2a5d3e5.png)
