### ISSUE TITLE
/app-store /category view - Breadcrumb wrong font-weight

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4415]
Make breadcrumb `font-semibold` so that it matches the single app view breadcrumb

Current
<img width="835" alt="CleanShot 2022-09-13 at 05 58 33@2x" src="https://user-images.githubusercontent.com/4536123/189812666-0ec75b2f-e3c9-4f95-aeb3-477da2a60dfe.png">

Should be
<img width="502" alt="CleanShot 2022-09-13 at 05 58 42@2x" src="https://user-images.githubusercontent.com/4536123/189812679-94bed160-1007-40e7-b4b0-066425bfb0af.png">

**Comment by leog** [comment]
> Current <img alt="CleanShot 2022-09-13 at 05 58 33@2x" width="835" src="https://user-images.githubusercontent.com/4536123/189812666-0ec75b2f-e3c9-4f95-aeb3-477da2a60dfe.png">
> 
> Should be <img alt="CleanShot 2022-09-13 at 05 58 42@2x" width="502" src="https://user-images.githubusercontent.com/4536123/189812679-94bed160-1007-40e7-b4b0-066425bfb0af.png">

@Jaibles are these the other way around? 😅 done!

**Comment by Jaibles** [comment]
Yes. Follow what I said not showed. (Sorry! GitHubs drag and drop wasn't working for awhile which did not help!)
