### ISSUE TITLE
/app-store - 2 small ui changes

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4416]
- [ ] border on cards to `border-gray-200` so they don't appear above buttons
- [ ] reduce title size to `text-base`

https://user-images.githubusercontent.com/4536123/189813768-da73adc3-2542-4939-a4d8-e17dafb3751c.mp4

**Comment by leog** [comment]
> * reduce title size to `text-base`

@Jaibles is that for the "App Store" page title? because the card title although not explicitly, has that size.

**Comment by Jaibles** [comment]
> > * reduce title size to `text-base`
> 
> 
> 
> @Jaibles is that for the "App Store" page title? because the card title although not explicitly, has that size.

The section titles. Check out the video :)
