### ISSUE TITLE
/app-store - buttons going over two lines

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4417]
<img width="1168" alt="CleanShot 2022-09-13 at 06 08 42@2x" src="https://user-images.githubusercontent.com/4536123/189814037-82c89c1f-88df-4e18-858c-e605cb7e5211.png">

**Comment by Jaibles** [comment]
@leog I know we discussed this so not sure if this is a known issue but i still see them over 2 lines. Let me know if you need help with this.

**Comment by leog** [comment]
@Jaibles there were two PRs with different fixes, now everything is in associated branch in this issue, feel free to give it a try, should be fixed as discussed.

**Comment by Jaibles** [comment]
Thank you @leog. Looking now 👀
