### ISSUE TITLE
/event-types /single-view - Sidebar doesn't have active item

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4433]
**Current**
![CleanShot 2022-09-13 at 19 06 01@2x](https://user-images.githubusercontent.com/4536123/189887101-0e728a95-6707-4d6d-83ff-eb7ef002e656.png)

**Should be**
<img width="1097" alt="CleanShot 2022-09-13 at 19 06 20@2x" src="https://user-images.githubusercontent.com/4536123/189887150-9f784918-6285-4ca2-9b23-a03d258e7442.png">

**Comment by thevolcanomanishere** [comment]
@Jaibles Seems to be fixed already?

![Image](https://user-images.githubusercontent.com/9613565/191248867-de344219-86a8-4b16-93ee-e136f3c665af.png)

**Comment by Jaibles** [comment]
Yes this is fixed thanks @thevolcanomanishere
