### ISSUE TITLE
Cal not detecting any conflicts with Zoho Calendar and Apple Calendar/iCloud events

### ISSUE THREAD

**Issue by hiramfromthechi** [calcom/cal.com#4436]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Despite displaying a connection to both CalDAV (using Zoho Calendar) and Apple Calendar, Cal does not detect events (and thus conflicts), leaving my event availability wide open.

So even though there are events on Zoho Calendar (which uses CalDAV), and they're set to show me as _busy_, Cal is not detecting those events. Same goes for Apple Calendar, using Work/Family/Personal/etc. iCloud calendars.

The strangest thing is that it worked for about 2 weeks, and then nothing. This issue has existed for at least 1.5 years now. I keep swinging back to Cal and trying to use it, but the issue persists.

### Steps to Reproduce

1. Connect Cal to Apple Calendar using an app-specific password (since 2FA is enabled).
2. Connect Cal to CalDAV using an app-specific password (since 2FA is enabled).
3. View Cal availability and compare it to both Apple Calendar and Zoho Calendar, which reveals that Cal is not detecting events.

I have my Zoho Calendar synced to Apple Calendar, so Apple Calendar becomes the one main source of truth, since both iCloud events and Zoho Calendar events are visible on Apple Calendar. By contrast, only Zoho Calendar events are on ZCalendar, and not iCloud events.

### Technical details

Tried on Firefox, Brave, and even the desktop Cal app. Doesn't appear to be a client-side issue.

**Comment by PeerRich** [comment]
@alishaz-polymath can you look into this with high priority?

**Comment by alishaz-polymath** [comment]
Yes @PeerRich 
In fact, it's already being worked on. This is a common theme for caldav calendars because of the way tsdav functions. I've already been in touch with Nate(creator of tadav) and he says he's looking into it. In the mean time, I'll explore it further as well. 🙌

**Comment by Kaminoan-Dev** [comment]
Any updates on this issue? Not been able to detect CalDAV events (Zoho Calendar) defeats the purpose of using cal.com since I have to manually check if there is a conflict every time.

**Comment by alishaz-polymath** [comment]
Hey @Kaminoan-Dev 
We're still working on the issue. We have a call with the maker of tsDAV this week and we hope to resolve the issue soon after.

**Comment by alishaz-polymath** [comment]
We have also narrowed it down enough to a behavior where all the events for a day are detected if there is at least one cal.com event that exists on that day. The calls are sent out normally, and yet for some reason return null calendar object, which is why we're facing this issue. You can try to re-create it and confirm. Simply create a cal.com event on a day, and then create any apple calendar/icloud event directly on that day and see if they're picked up. We would greatly appreciate your input on this.
cc: @Kaminoan-Dev @hiramfromthechi

**Comment by Kaminoan-Dev** [comment]
I am using Zoho Calendar, and unfortunately when I create a cal.com event on a day, and then create an event on Zoho directly on that same day it is still not detected.

**Comment by alishaz-polymath** [comment]
@hiramfromthechi okay. Let's get this resolved then 🙌 
Can you do the following and then share here?
1. Remove the connected calendars and add them again. 
2. Create a loom.com video showcasing the issue and how I can re-create on my end easily 
3. Share the video link here.

If I need anything else after that I'll let you know. 🙏

**Comment by zaidakram** [comment]
Can confirm. Cal doesn't detect conflicts with Zoho calendar (added as CalDav).

**Comment by emrysal** [comment]
@zaidakram A fix is in progress - was something we detected today; conflict detection was broken, the booking page was also behaving really slow for CalDav Zoho.

**Comment by zaidakram** [comment]
Awesome. Thanks for the quick response. Really appreciate the work you guys are putting in. Thank You!

**Comment by alishaz-polymath** [comment]
Hi @zaidakram Zoho isn't officially supported yet with our CalDAV, however, we have it lined up next for the major CalDAV integration. You can check the exhaustive list of all supported CalDAV services here:
https://github.com/calcom/cal.com/issues/3457
Thanks for your patience in the mean time 🙏

**Comment by PeerRich** [comment]
moving to the other issue #3457
