### ISSUE TITLE
/availability /detail-view - hide "Active on" until we build it fully

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4440]
Assuming this is a work in progress cause it's supposed to be a dropdown, but the count appears to always be zero no matter how many it's active on. Let's just hide this if we don't have the dropdown ready and it's not trivial to fix.

 
<img width="558" alt="CleanShot 2022-09-13 at 18 19 19@2x" src="https://user-images.githubusercontent.com/4536123/189966049-2a80c7e9-f217-4346-a859-b3d184182c38.png">

**Comment by emrysal** [comment]
Descoped for now, will hide.

**Comment by Jaibles** [comment]
Perfect thanks alex. Updated the issue so it's just to hide it. We can close this when it's hidden
