### ISSUE TITLE
/availability - Add ability to set as default in the dropdown.

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4443]
<img width="1234" alt="CleanShot 2022-09-13 at 18 38 58@2x" src="https://user-images.githubusercontent.com/4536123/189972572-bbc7ead2-684e-41a4-b12b-6d7d86e4a6ee.png">

**Comment by gGh00sTt** [comment]
Hello @Jaibles . I was trying to work on this issue. Can you see this implementation video and check if it matches the requirements?

https://www.loom.com/share/d6d35d527194413ca9f8a63979cce5e3

**Comment by Jaibles** [comment]
@gGh00sTt this looks great thank you 🙏
