### ISSUE TITLE
/bookings - Going off screen

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4445]
https://user-images.githubusercontent.com/4536123/189972808-43feb13a-3d9c-4f9c-baea-d33fb386598a.mp4

**Comment by davidtaing** [comment]
Hi all, I'm looking to contribute and gain some experience.

@MuriloAmarals it looks okay on fullscreen 1080p (1920W), but I got it to overflow on other screen sizes.

I was able to replicate this on Chrome & Firefox on my Windows machine and on Safari on my Macbook. I've tested the following widths on Chrome & Firefox: 320W, 375W, 768W, 1440W.

Quick question @Jaibles, are we officially supporting viewports with 320 width? Or widths 375 and above?

## 320 Width - Overflowing
<img width="320" alt="320W" src="https://user-images.githubusercontent.com/8443215/192714152-85a97375-e57a-465f-8d4e-b2eb74011f32.png">

## 375 Width - OK
<img width="320" alt="375W" src="https://user-images.githubusercontent.com/8443215/192714203-7ed435bf-25e4-4196-ad78-17216ab661ee.png">

## 768 Width - OK
<img width="600" alt="768W" src="https://user-images.githubusercontent.com/8443215/192714205-b8583af0-de39-4e6e-823f-8b4dbdd0538f.png">

## 1024 Width - Overflowing
<img width="600" alt="1024W" src="https://user-images.githubusercontent.com/8443215/192714210-a4bcc2bc-35df-4bba-8e92-05008df68279.png">

## 1440 Width - OK
<img width="600" alt="1440W" src="https://user-images.githubusercontent.com/8443215/192714207-d6975ec8-006d-4a60-8bb1-edcb9700e6c7.png">

**Comment by Udit-takkar** [comment]
hey @davidtaing  are you working on this issue ?

**Comment by davidtaing** [comment]
No, I'm not working on this one.

**Comment by davidtaing** [comment]
@Udit-takkar it looks like the Core Team is working on this.

https://github.com/calcom/cal.com/issues/4691#issuecomment-1261462905
