### ISSUE TITLE
Deployment failure to Heroku because of a big slug size

### ISSUE THREAD

**Issue by coachatapp** [calcom/cal.com#4453]
When deploy to Heroku, the build was successful but the push to deployment failed.

Error message on Heroku:

-----> Compressing...

 !     Compiled slug size: 651.8M is too large (max is 500M).

 !     See: http://devcenter.heroku.com/articles/slug-size

 !     Push failed

Tried the remove unnecessary dependencies following the link but no success.
https://github.com/vercel/next.js/issues/32183

Anyone please help?

**Comment by stockm** [comment]
Did you resolve this issue ? I am seeing the same

**Comment by coachatapp** [comment]
I cannot solve it as it's a bug confirmed by Cal.com. I've switched to another vendor.

**Comment by PeerRich** [comment]
can you try again with the most recent version?

**Comment by mingzew** [comment]
I am also encountering this issue @PeerRich, I am on 2.8.1

`
-----> Compressing...
 !     Compiled slug size: 1001.2M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
 `
