### ISSUE TITLE
Attendee Phone Number - Input field missing when default

### ISSUE THREAD

**Issue by svnwa** [calcom/cal.com#4454]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On the booking page the input field to input the attendee phone number is missing when the "Attendee Phone Number" field is the default choice (first choice).

### Steps to Reproduce

1. Create a new event type
2. Pick the "Attendee Phone Number" option as the first location option and save
3. Go to e.g. the live preview, pick da date and time
4. See the "Attendee Phone Number" choice is picked by default because its the first one, but no input field is showing
5. Change the input and then back to "Attendee Phone Number" to see the input field

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I would expect the input field to also show by default if the attendee phone number choice is the default choice.

### Technical details

https://app.birdeatsbug.com/sessions/4EplphYyB1N8vApSqQItfzKimzdnL9MVHNGqb0iiPKOl
https://app.birdeatsbug.com/sessions/NDB9f2Y3lQiU_XG6ui8NLnwLvsZ9IIboep-KHUS1LKAl

**Comment by milospuac** [comment]
Hi there. Thank you for reporting this. Our team will investigate what went wrong here and fix it

**Comment by emrysal** [comment]
Hi @svnwa - closing as this is fixed now 👍
