### ISSUE TITLE
/event-types /detail - We have an Update and a Save button, should be one

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4457]
From a design perspective we only need one of these. Ideally just the update button on the top right. Currently are these all separate forms so we can't remove the update button? Would like to know so we can at least remove one of these. It's super confusing right now.

![Image](https://user-images.githubusercontent.com/4536123/190103440-497cc885-a8bb-473f-97ce-a44cf6449849.png)

**Comment by emrysal** [comment]
Open PR @ https://github.com/calcom/cal.com/pull/4472 with concerns that should be addressed before merging.
