### ISSUE TITLE
/event-types /detail /apps -  large spacing below app

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4458]
Currently
![Image](https://user-images.githubusercontent.com/4536123/190104570-a8849d42-4c53-4075-b0c7-79e97ca3509d.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/190105256-c3c6ec91-c107-44d7-8072-66e2abd00129.png)

**Comment by hussamkhatib** [comment]
hey can I pick up this issue
