### ISSUE TITLE
Embeds - Layout discrepencies between design

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4459]
Current
![Image](https://user-images.githubusercontent.com/4536123/190105721-c5cfc7e3-6315-4d91-afe5-02ec02d82835.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/190105924-cbe71b07-d94a-4b59-8b58-593ef83b4d41.png)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A112251)

**Comment by hariombalhara** [comment]
Already fxed
