### ISSUE TITLE
/workflows /detail-view - Add variable button hover alignment is off

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4461]
Currently

![Image](https://user-images.githubusercontent.com/4536123/190108090-c2454f5b-c799-46c6-866b-29a050efe64d.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/190108210-93d6e42f-c024-4fa3-a226-67d530c5d56a.png)

**Comment by Priyankcoder** [comment]
@Jaibles Hi, I am new to this project. Can I pick this?

**Comment by Jaibles** [comment]
@Priyankcoder go for it :)

**Comment by Priyankcoder** [comment]
Awesome, I'm on it. Thanks :)

**Comment by Priyankcoder** [comment]
Hey @Jaibles,  I don't have calcom license key. How to proceed further?

<img width="1727" alt="Screenshot 2022-09-15 at 11 18 49 AM" src="https://user-images.githubusercontent.com/39910453/190324897-40a7579a-2b0a-43de-8177-d533df472d2c.png">

**Comment by matheusmuniz03** [comment]
Hey @Jaibles, apparently this problem no longer exists, can we close this issue??
![Captura de tela de 2022-09-21 10-36-02](https://user-images.githubusercontent.com/87545749/191518534-d7724282-1bf4-4945-80c4-c18eb63fecf1.png)

**Comment by matheusmuniz03** [comment]
I managed to reproduce the problem now, sorry. The expected result to correct is this?
![Captura de tela de 2022-09-21 11-47-56](https://user-images.githubusercontent.com/87545749/191536901-0f8ca505-f55b-43ab-a76e-d1993edd8ab9.png)

**Comment by Jaibles** [comment]
@matheusmuniz03 that's much better, any chance we can get the chevron icon center aligned with the text also? looks aligned with the bottom currently.

**Comment by matheusmuniz03** [comment]
Better now?
![Captura de tela de 2022-09-21 11-59-52](https://user-images.githubusercontent.com/87545749/191539871-53cae926-bf82-4607-a698-bc8c0e6b1c46.png)

**Comment by Jaibles** [comment]
yea much better! 
(If i was going to be really annoying I'd say that I'd love if these text items aligned.. but I suspect this is perhaps not so easy and you've used your patience on this one 😅 so I'm happy with this if it's as much as is easy, because it's a huge improvement!) Thank you🙏

<img width="1161" alt="CleanShot 2022-09-21 at 16 18 43@2x" src="https://user-images.githubusercontent.com/4536123/191544051-c8cb82fa-51e0-40a3-b6ba-8fcd0646f70d.png">

**Comment by matheusmuniz03** [comment]
I also agree @Jaibles . Made!
![Captura de tela de 2022-09-21 13-50-00](https://user-images.githubusercontent.com/87545749/191564823-e5042afc-8bbb-43ac-a8fb-1d5732fac537.png)

**Comment by Jaibles** [comment]
perfect @matheusmuniz03 thank you 🙏
