### ISSUE TITLE
/routing-forms - External redirect input label shouldnt be shown

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4463]
![Image](https://user-images.githubusercontent.com/4536123/190109220-df32f79f-276e-4fb7-b356-888ef1b5dda7.png)

**Comment by G3root** [comment]
@Jaibles is the label `externalRedirectUrl` should be present ?

**Comment by Jaibles** [comment]
@G3root no it shouldn't be 👍

**Comment by G3root** [comment]
> @G3root no it shouldn't be +1

ok, i'll send a PR
