### ISSUE TITLE
/routing-forms - reordering alignment is not centered

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4464]
![CleanShot 2022-09-14 at 09 57 48@2x](https://user-images.githubusercontent.com/4536123/190109919-17a16085-1c5d-4e9c-8c14-792b71ef0950.png)

**Comment by gracebir** [comment]
@Jaibles , what are the steps to reproduce in order of accessing the `routing-form` cause I am not able to access it

**Comment by Jaibles** [comment]
hey @gracebir, you need to install Routing Forms from the App Store first.
