### ISSUE TITLE
/apps /installed apps - Toast is v1 component and copy needs updating

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4465]
**Current**
<img width="1171" alt="CleanShot 2022-09-14 at 10 00 15@2x" src="https://user-images.githubusercontent.com/4536123/190110549-5cf075fc-395a-4aaa-9e55-f6828d36c7ab.png">

**Should be v2 component and say...**
<img width="803" alt="CleanShot 2022-09-14 at 10 02 28@2x" src="https://user-images.githubusercontent.com/4536123/190110912-a66f1238-dee0-4f07-b695-ccd5c10d623b.png">

**Comment by leog** [comment]
@Jaibles Done!
