### ISSUE TITLE
v2 dark mode: email input wrong colors

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4499]
<img width="463" alt="CleanShot 2022-09-15 at 16 14 05@2x" src="https://user-images.githubusercontent.com/8019099/190454875-28ea9d36-11e3-4014-b486-78aeafaf4a4c.png">

**Comment by MatheusBeniniF** [comment]
Hi @PeerRich , Im trying to do this issue but I on my browser the color is right
![image](https://user-images.githubusercontent.com/88898100/191030085-15e9b8aa-1d2d-403d-901f-d8e1eca9934f.png)

**Comment by PeerRich** [comment]
fixed
