### ISSUE TITLE
dropdown: focus not working on all items

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4501]
![CleanShot 2022-09-15 at 16 50 41](https://user-images.githubusercontent.com/8019099/190462333-be7ce148-cc81-4a2f-a571-b29210fcd032.gif)

it should be 1px outline black not 2px blue

**Comment by rksingh2001** [comment]
@PeerRich Can I take up this issue?

**Comment by PeerRich** [comment]
@rksingh2001 yes please.🙏

**Comment by afzalsayed96** [comment]
@PeerRich @rksingh2001 the issue has been fixed in #4565. Kindly validate 🙏🏻

**Comment by PeerRich** [comment]
oh awesome, will check @afzalsayed96

**Comment by rksingh2001** [comment]
@PeerRich @afzalsayed96 Shouldn't we ask for tickets to be assigned first before starting with the ticket?

**Comment by afzalsayed96** [comment]
Sorry about that will keep in mind in future!

**Comment by emrysal** [comment]
@rksingh2001 Agreed - will keep that in mind as well but I do have some concerns (if we assign someone who then does not actually start working on it, they potentially block others from starting work). Closing as confirmed fixed 👍
