### ISSUE TITLE
reordering slow, needs async + animation

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4504]
- [x] dont wait for backend response, make visual update async instantly
- [x] use autoanimate for reordering

![CleanShot 2022-09-15 at 21 14 36](https://user-images.githubusercontent.com/8019099/190510036-5e1bdd3c-819c-4bb9-9f0e-377ff69dd5d5.gif)

**Comment by emrysal** [comment]
Fixed through https://github.com/calcom/cal.com/pull/4611
