### ISSUE TITLE
settings: sub pages have no active state

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4505]
https://user-images.githubusercontent.com/8019099/190510348-1faea00d-2dba-4041-becf-c042ea8f6632.mp4

should be same bg-color than the other active settings pages

**Comment by Toledodev** [comment]
Hey @PeerRich, I was seeing that the sidebar when the screen is in fullscreen has a different style from the others
![Screenshot from 2022-09-20 17-00-44](https://user-images.githubusercontent.com/87545086/191353797-6e2b79b3-6a17-4a69-8f77-cf4af5be5340.png)
I changed the style to it to be like the others and added the hover 
https://www.loom.com/share/9c1e9b00ee544c68bd4736cc4f9a46c5
This is good for you?

**Comment by PeerRich** [comment]
> Hey @PeerRich, I was seeing that the sidebar when the screen is in fullscreen has a different style from the others
> 
> ![Screenshot from 2022-09-20 17-00-44](https://user-images.githubusercontent.com/87545086/191353797-6e2b79b3-6a17-4a69-8f77-cf4af5be5340.png)
> 
> I changed the style to it to be like the others and added the hover 
> 
> 
> 
> https://www.loom.com/share/9c1e9b00ee544c68bd4736cc4f9a46c5
> 
> 
> 
> This is good for you?
> 
> 
> 
> 

yes please open a PR🙏

**Comment by Toledodev** [comment]
ok :+1:

**Comment by Toledodev** [comment]
I think this has already been fixed [loom](https://www.loom.com/share/b0edde6090804c8ebd55f0a93d819e65)
