### ISSUE TITLE
/installed-apps: truncate calendar url in dropdown

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4506]
https://user-images.githubusercontent.com/8019099/190510775-c8137cf6-ff8b-432d-9f97-0fba95bb24ed.mp4

**Comment by gGh00sTt** [comment]
@PeerRich , I was trying to work on this issue but was unable to see the url in the dropdown options recently in the local version. Is this issue still valid?

**Comment by gGh00sTt** [comment]
@PeerRich , any updates regarding this issue and its validity?

**Comment by PeerRich** [comment]
> @PeerRich , any updates regarding this issue and its validity?

I believe its fixed
