### ISSUE TITLE
use new v2 Dropdown in booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4508]
<img width="683" alt="CleanShot 2022-09-15 at 22 14 33@2x" src="https://user-images.githubusercontent.com/8019099/190518107-f2297abd-88a3-47e5-8573-65a187ad267f.png">

**Comment by JeroenReumkens** [comment]
@sean-brydon  Just came across this issue now —  I will already do the majority of this work when converting this component to support dark mode (and thus implement select v2). Just so you know.
