### ISSUE TITLE
Scroll to Time After Selecting Date on Mobile

### ISSUE THREAD

**Issue by nsomaru** [calcom/cal.com#451]
### Is your proposal related to a problem?

Users are confused on mobile when tapping a date because it is not obvious when doing so that the times appear under the calendar on mobile.

### Describe the solution you'd like

Scroll to the top of the time area when date is clicked, maybe print the selected date above the available times.

### Describe alternatives you've considered

Make the times appear in a new screen all together that replaces the calendar screen.

**Comment by PeerRich** [comment]
thats a neat idea. let me try to build this

**Comment by AbhinavGoswami-011** [comment]
@PeerRich found some interesting alternatives to this on dribble which may seem neater especially on the mobile. 
https://dribbble.com/shots/5573651-Adobe-live-stream
https://dribbble.com/shots/15024585-Medical-App
https://dribbble.com/shots/15289895-Medical-App-Concept
Having a full month calendar view on mobile doesn't help always imo, as seldom do people schedule time beyond 7-10 days. A new screen may just increase the interaction points without much tangible benefit

**Comment by PeerRich** [comment]
I agree that scrolling doesnt solve much. the problem with scroll on click is that if you want to change the date, you always need to move back up. I tried it locally. 

we'll either keep the current design, or as you've send some inspiration, make a mobile concept that has a very different layout than our current one
