### ISSUE TITLE
Embed Dialog Width and Height should be increased to give preview enough space.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4514]
<img width="1781" alt="Screenshot 2022-09-15 at 10 18 57 AM" src="https://user-images.githubusercontent.com/1780212/190316991-f5fc10b6-e066-4b34-9c1a-879691574979.png">
@Jaibles We should increase the width and height in V2 Embed as well because Preview isn't of desktop even on desktop.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/issues/4477#issuecomment-1247578967_

**Comment by Jaibles** [comment]
@hariombalhara 👍 ok makes sense. Go as wide as we need to for a desktop preview. The overall padding around the modal currently looks too big
