### ISSUE TITLE
/workflows - Showing pro feature banner

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4517]
![Image](https://user-images.githubusercontent.com/4536123/190587046-7fd0c639-3122-494e-96ef-6ebdefe8badf.png)

**Comment by hariombalhara** [comment]
Not clear what needs to be done here(apart from translating that string) as Workflows won't be available to free users.

**Comment by Jaibles** [comment]
If a user has no teams plan... Show an empty state adapted for teams...
<img width="1548" alt="CleanShot 2022-09-16 at 10 10 56@2x" src="https://user-images.githubusercontent.com/4536123/190612668-d7838131-564c-4b83-9ac4-1b24be3ea054.png">

**Comment by matheusmuniz03** [comment]
Hey @Jaibles, would it be this? because for me it is already appearing
![Captura de tela de 2022-09-21 11-20-46](https://user-images.githubusercontent.com/87545749/191529901-d4230f0b-7dea-45d6-9505-f6dd9fdcce4e.png)

**Comment by Jaibles** [comment]
@hariombalhara did we just make Workflows available to everyone yea?

**Comment by hariombalhara** [comment]
Yeah this PR was merged few days back https://github.com/calcom/cal.com/pull/4518/files
