### ISSUE TITLE
No way to exit 'Create a new team screen'

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4523]
No way to go back on this screen
<img width="1381" alt="Screenshot 2022-09-16 at 3 18 12 PM" src="https://user-images.githubusercontent.com/1780212/190611371-658e606e-c460-4d7f-a6f8-e35e5ba1aa26.png">

**Comment by Emmanuel-Melon** [comment]
> No way to go back on this screen <img alt="Screenshot 2022-09-16 at 3 18 12 PM" width="1381" src="https://user-images.githubusercontent.com/1780212/190611371-658e606e-c460-4d7f-a6f8-e35e5ba1aa26.png">

Would you like a "Back" button that takes you back to the settings page?

**Comment by hariombalhara** [comment]
Yeah I think that would be good cc @Jaibles

**Comment by Emmanuel-Melon** [comment]
> Yeah I think that would be good cc @Jaibles

Sure, where can I find examples of secondary action buttons?

**Comment by Emmanuel-Melon** [comment]
> Yeah I think that would be good cc @Jaibles

<img width="1440" alt="Screen Shot 2022-09-19 at 11 01 31" src="https://user-images.githubusercontent.com/21015204/190974667-651cc4a0-362f-45c7-a847-87f9ee05d3eb.png">
Something like this?

**Comment by Emmanuel-Melon** [comment]
> Yeah I think that would be good cc @Jaibles

Created two other variations:
- Button says "Exit"
<img width="1920" alt="Screen Shot 2022-09-20 at 12 32 59" src="https://user-images.githubusercontent.com/21015204/191223388-02

- Button says "Cancel"
<img width="1920" alt="Screen Shot 2022-09-20 at 12 32 16" src="https://user-images.githubusercontent.com/21015204/191223432-1aa92180-ddca-416d-b31d-7e8a3f705456.png">
b8b2ca-343d-4564-b17f-6416e962743a.png">

**Comment by Jaibles** [comment]
<img width="1476" alt="CleanShot 2022-09-20 at 11 48 38@2x" src="https://user-images.githubusercontent.com/4536123/191238843-cfb4e854-5803-448d-a5c3-fd3f432c281f.png">

**Comment by Emmanuel-Melon** [comment]
> <img alt="CleanShot 2022-09-20 at 11 48 38@2x" width="1476" src="https://user-images.githubusercontent.com/4536123/191238843-cfb4e854-5803-448d-a5c3-fd3f432c281f.png">

Okay got it!

**Comment by Emmanuel-Melon** [comment]
> <img alt="CleanShot 2022-09-20 at 11 48 38@2x" width="1476" src="https://user-images.githubusercontent.com/4536123/191238843-cfb4e854-5803-448d-a5c3-fd3f432c281f.png">

Updated design:
<img width="1920" alt="Screen Shot 2022-09-20 at 20 37 44" src="https://user-images.githubusercontent.com/21015204/191327085-7e2506e6-9fc7-42b0-a4a0-754596bf8afe.png">

**Comment by Jaibles** [comment]
Nice work @Emmanuel-Melon looks good to me!
