### ISSUE TITLE
[CAL-79] Settings Page should have User dropdown.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4524]
No way to know who I am logged in as on this screen. There should be user dropdown here as well.

<img width="1777" alt="Screenshot 2022-09-16 at 3 19 43 PM" src="https://user-images.githubusercontent.com/1780212/190611663-34299d67-bd31-4e88-b9ce-59f3b52fd842.png">

cc @Jaibles

**Comment by Jaibles** [comment]
I'll add designs.

**Comment by Emmanuel-Melon** [comment]
> I'll add designs.

I'd like to work on this! Let me know if the designs are ready.

**Comment by hariombalhara** [comment]
This is actually fixed now.
