### ISSUE TITLE
Landing page navigation bar flickers on hover on macOS Safari 16.1

### ISSUE THREAD

**Issue by wongmjane** [calcom/cal.com#4530]
### Issue Summary

Cal.com’s new landing page flickers on hover, presumably due to some glitches that happened during CSS transition

https://user-images.githubusercontent.com/1332975/190679134-7aa17b75-11eb-4b18-a6ac-eb02d0af625f.mov

### Steps to Reproduce

1. Go to the landing page of https://cal.com using macOS Safari 16.1
2. Move your cursor over to the navigation bar
3. It flickers while trying to transition the styling

### Technical details

- Browser: macOS Safari 16.1 (18614.2.3.1.1)

**Comment by PeerRich** [comment]
thank you @wongmjane 🙏 will investigate
