### ISSUE TITLE
Custom brand colors are not saved

### ISSUE THREAD

**Issue by jahirfiquitiva** [calcom/cal.com#4531]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I went to the appearance section, changed the colors and after hitting update, it does not save.

### Steps to Reproduce

![Shot 2022-09-16 at 11 03 58](https://user-images.githubusercontent.com/10360816/190684971-199d5fa2-be72-41c1-a363-cb753d09065e.gif)

### Technical details

- Browser version, screen recording, console logs, network requests: https://app.birdeatsbug.com/sessions/bDImBpzttmrAooVtNUVOqj2D6Gw8NcaLoyNslhl6ui4G

**Comment by PeerRich** [comment]
@zomars is this the same bug we fixed today?

**Comment by PeerRich** [comment]
it seems like settings are not being saved

**Comment by zomars** [comment]
> @zomars is this the same bug we fixed today?

It is not

**Comment by emrysal** [comment]
@zomars This issue seems to have been resolved 💯
