### ISSUE TITLE
Selected calendars for event conflicts checking are not saved

### ISSUE THREAD

**Issue by jahirfiquitiva** [calcom/cal.com#4532]
### Steps to Reproduce

![Shot 2022-09-16 at 11 31 52](https://user-images.githubusercontent.com/10360816/190686899-2b7b0aff-e5f5-4767-8ceb-f68bf7be0885.gif)

### Technical details

- Browser version, screen recording, console logs, network requests: 
https://app.birdeatsbug.com/sessions/LTDzJN9QlG20gw5I5OCR69WOsUd-WNbx0p6wcILJ9VMj

**Comment by Guray00** [comment]
Same problem with Google Calendar.

**Comment by PeerRich** [comment]
we'll look into this first thing in the morning!

**Comment by StudioVDS** [comment]
I see this issue is closed but I still have the same issue. I cleared cache, logged out and logged in again. Anything I missed?

**Comment by PeerRich** [comment]
@emrysal can you try again?

**Comment by PeerRich** [comment]
or @alannnc

**Comment by jahirfiquitiva** [comment]
@PeerRich this is working for me now 🙌
