### ISSUE TITLE
[CAL-119] Initial rendering of calendar takes 3-5 seconds!

### ISSUE THREAD

**Issue by timfee** [calcom/cal.com#4535]
See image -- on a fast connection, with a single calendar configuration -- painfully slow.

![Screenshot_2022-09-16_09-09-20_1o326Lzi](https://user-images.githubusercontent.com/3246342/190690056-8d71601b-3d69-4177-9d9b-b29ad5752fff.gif)

**Comment by timfee** [comment]
15 minute chat | Tim Feeley | Cal.comcal.com

**Comment by timfee** [comment]
https://cal.com/tim/15

**Comment by Jaibles** [comment]
related: [https://linear.app/calcom/issue/CAL-281/10-seconds-load-time-for-availability](https://linear.app/calcom/issue/CAL-281/10-seconds-load-time-for-availability)

**Comment by Jaibles** [comment]
Update from @emrysal 

> I think that's a bad ticket - it's been improving slowly ever since that was assigned to me but I'm not sure what is possible and it's continual improvement

**Comment by Tom-Potanski** [comment]
We also experience this issue. A lot.

**Comment by PeerRich** [comment]
we have an ongoing task to improve performance of this. the main issue is that the cold boot of serverless functions is slow. this gets better if your app is used more frequenlty -- i know not a perfect solution. we're trying to find a way to do this without cold boot

**Comment by PeerRich** [comment]
note to self: https://cal.com/peer/30min is faster, surprisingly

**Comment by leerob** [comment]
What API is it using? What file? Random guess: https://github.com/calcom/cal.com/blob/main/apps/web/pages/api/book/event.ts

You might consider using Edge API Routes, which will help you get faster cold startups: https://nextjs.org/docs/api-routes/edge-api-routes

```ts
export const config = {
  runtime: 'edge',
}

export default async function handler(req: Request) {
  return new Response()
}
```

But I think would need to verify this is possible with `next-auth`.

**Comment by lukasklein** [comment]
> note to self: https://cal.com/peer/30min is faster, surprisingly

the `getSchedule` request for your calendar takes almost 3s for me to complete as well

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/1492869/210725985-405b2449-90e8-4447-8a90-767ff6525b27.png">

```
~ ❯ time curl 'https://cal.com/api/trpc/viewer.public.slots.getSchedule?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22eventTypeId%22%3A127%2C%22eventTypeSlug%22%3A%2230min%22%2C%22usernameList%22%3A%5B%22peer%22%5D%2C%22startTime%22%3A%222023-01-02T23%3A00%3A00.000Z%22%2C%22endTime%22%3A%222023-01-31T22%3A59%3A59.999Z%22%2C%22timeZone%22%3A%22Europe%2FBerlin%22%2C%22duration%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22duration%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D' > /dev/null --compressed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1394    0  1394    0     0    684      0 --:--:--  0:00:02 --:--:--   686
curl  --compressed > /dev/null  0.02s user 0.01s system 1% cpu 3.048 total
```

**Comment by leerob** [comment]
Woah.

> In this release, we have decreased the size of our engine files by an average of 50%. The size of the Query Engine used on Debian, with OpenSSL 3.0.x, for example, went from 39MB to 14MB. We will also remove some smaller engines to decrease the total size in future versions.

https://github.com/prisma/prisma/releases/tag/4.8.0

You might want to update!

**Comment by PeerRich** [comment]
@lukasklein  
> the getSchedule request for your calendar takes almost 3s for me to complete as well

well 3 seconds is still better than 5 to 10 seconds (which we have seen too)

**Comment by PeerRich** [comment]
anyone interested in this, we're making a bit of progress. stay tuned.🙏

**Comment by PeerRich** [comment]
we have identified that one of the slowness reasons is a slow caldav server for the affected users.

we can still improve prisma and cold boots tho

**Comment by roae** [comment]
@PeerRich I have an idea that could solve this, i will submit a pull request soon.

**Comment by PeerRich** [comment]
we ended up hiring @roae 🙏

**Comment by zomars** [comment]
> https://cal.com/tim/15

@timfee we just released Data Proxy. Can you verify if it's still slow?

**Comment by timfee** [comment]
See attachment. Still seems like it's a bit slow, but better than before!

https://user-images.githubusercontent.com/3246342/225504906-9a1148e1-7913-4d4a-a92e-381b31428fd0.MOV
