### ISSUE TITLE
Wrong logo for stripe

### ISSUE THREAD

**Issue by sairajchouhan** [calcom/cal.com#4536]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
wrong logo for stripe when I hover on `apps` in the navbar of landing page

### Steps to Reproduce

1. visit `cal.com`
2. hover on `apps` in the navbar
3. see the wrong logo for stripe

![Screenshot 2022-09-16 at 10 20 15 PM](https://user-images.githubusercontent.com/57995897/190690996-9b49c168-fbde-404e-9253-22c2f5220396.png)

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by Toledodev** [comment]
Hey @sairajchouhan, I didn't see this error 
![Screenshot from 2022-09-17 09-49-55](https://user-images.githubusercontent.com/87545086/190857733-712e2c3e-c1cb-4d17-b3f0-dfd91dfb2f43.png)

**Comment by sairajchouhan** [comment]
it's fixed now
