### ISSUE TITLE
event types skeleton is off

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4540]
![image](https://user-images.githubusercontent.com/8019099/190826602-8caa9804-94da-4615-a595-7103d366aa68.jpeg)

vs

![image](https://user-images.githubusercontent.com/8019099/190826642-8687a344-39f2-4426-bb75-01b2e74fb67b.png)

**Comment by jonathangiardino** [comment]
Fixed in #4550

**Comment by PeerRich** [comment]
thank you @jonathangiardino !
