### ISSUE TITLE
[CAL-116] Dark theme support required for button component

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4544]
https://www.loom.com/share/a7545b343c8043268dfe270040fb0628

**Comment by hussamkhatib** [comment]
Hi can I fix this?

**Comment by hariombalhara** [comment]
@hussamkhatib Sure. You just need to make sure that the buttons inside the app(logged in area) are in the dark mode. This is required because app doesn't support dark mode yet. Only public pages support dark theme

**Comment by hussamkhatib** [comment]
I am not able to reproduce it as I am not able to set my theme to dark mode.
I am discussing this issue in slack at the moment.

**Comment by gracebir** [comment]
@hariombalhara , I can reproduce this one my hand, is there any figma design?

**Comment by hussamkhatib** [comment]
@gracebir you can find the figma file in readme

**Comment by Jaibles** [comment]
@JeroenReumkens has this been taken care of? Let's move to 2.3 if not 🙏

**Comment by JeroenReumkens** [comment]
@Jaibles  No actually it is not. I put most of the UI updates on hold until we have a single source of truth for a component. But since this applies to the public booking page as well, I'm actually picking this up right now, so at least the booking page looks neat 👌
