### ISSUE TITLE
I can't change the language

### ISSUE THREAD

**Issue by StudioVDS** [calcom/cal.com#4549]
When going to settings and than general. It is possible to change the language, when choosing for an other language and clicking the save button nothing happens.

Steps to Reproduce
Went to Settings -> General
Choose a new language (Dutch to English)
Clicked the save button
Nothing happens

Technical details
Chrome 105, Mac OS 12.4

**Comment by PeerRich** [comment]
hey, we'll look into this! the new settings were shipped last minute and we'll see why it doesn't work for durch

**Comment by PeerRich** [comment]
just tested, can confirm I can't change the language either
