### ISSUE TITLE
[CAL-121] Improvements in local setup instructions

### ISSUE THREAD

**Issue by hussamkhatib** [calcom/cal.com#4575]
### Is your proposal related to a problem?

The section *Setup your first user* is not required imo.
There are already all kinds of users created using the [seed data](https://github.com/calcom/cal.com/blob/main/packages/prisma/seed.ts)

### Describe the solution you'd like

Replace that section with paragraph describing how to quickly sign in as a particular user.

**Comment by PeerRich** [comment]
we're working on better DX getting started docs, cc @alishaz-polymath

**Comment by alishaz-polymath** [comment]
This should be resolved quite soon. 🙏 
Thank you for waiting

**Comment by alishaz-polymath** [comment]
The _Setup your first user_ step is actually useful in case `yarn dx` isn't used for a quick setup, which requires Docker and Docker Compose. 
As for signing in from various users, the notes specify that the credentials are logged and available on the console when running `yarn dx`
