### ISSUE TITLE
/auth: show password button misaligned

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4578]
<img width="220" alt="CleanShot 2022-09-18 at 18 49 26@2x" src="https://user-images.githubusercontent.com/8019099/190923613-0e23a72a-b97b-4164-9f01-e57d55abc4cb.png">

**Comment by rksingh2001** [comment]
@PeerRich can I take up this issue?

**Comment by Emmanuel-Melon** [comment]
> <img alt="CleanShot 2022-09-18 at 18 49 26@2x" width="220" src="https://user-images.githubusercontent.com/8019099/190923613-0e23a72a-b97b-4164-9f01-e57d55abc4cb.png">

Can you add more context? Which pages? Browser? Maybe a bigger screenshot? I can't reproduce this issue.

**Comment by PeerRich** [comment]
fixed
