### ISSUE TITLE
dark mode switcher not working

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4580]
this input is not changing the public booking page theme

<img width="833" alt="CleanShot 2022-09-18 at 19 02 31@2x" src="https://user-images.githubusercontent.com/8019099/190924128-9c013c27-be37-4f36-beea-bc9a8e026a9a.png">

**Comment by JeroenReumkens** [comment]
Tested this yesterday in production and it actually does seem to work. The only thing is that because of SWR the theme seems to be cached for one extra refresh. Not sure if we want to (and can / should) fix this?

**Comment by emrysal** [comment]
@JeroenReumkens I'm pretty sure this got fixed also by a recent settings update, closing as fixed 👍
