### ISSUE TITLE
/settings/api keys not using new dropdown

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4581]
<img width="365" alt="CleanShot 2022-09-18 at 19 37 21@2x" src="https://user-images.githubusercontent.com/8019099/190925353-fedcfb87-b07a-4998-823f-302be4c3718b.png">

**Comment by matheusmuniz03** [comment]
Hey @PeerRich, how do I get the CALCOM_LICENSE_KEY? 
![Captura de tela de 2022-09-19 09-47-08](https://user-images.githubusercontent.com/87545749/191020931-e14faaa2-2b10-4908-aa77-8041a3b64fdd.png)

**Comment by PeerRich** [comment]
> Hey @PeerRich, how do I get the CALCOM_LICENSE_KEY? 
> 
> ![Captura de tela de 2022-09-19 09-47-08](https://user-images.githubusercontent.com/87545749/191020931-e14faaa2-2b10-4908-aa77-8041a3b64fdd.png)
> 
> 

for production: console.cal.com

for debugging you can enable 

IS_E2E=1

**Comment by matheusmuniz03** [comment]
Hey @PeerRich, can you look at these prints? I think this issue has been resolved
![Captura de tela de 2022-09-21 09-44-07](https://user-images.githubusercontent.com/87545749/191507320-a091edd1-0a13-481d-8998-0909405a011a.png)
![Captura de tela de 2022-09-21 09-45-15](https://user-images.githubusercontent.com/87545749/191507330-5433d059-814b-4e6f-9577-43c25fa353b5.png)

**Comment by PeerRich** [comment]
done
