### ISSUE TITLE
[CAL-117] Layout of settings shell for longer languages is broken

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#4583]
### Issue Summary

Layout of settings shell is broken for longer languages: 

<img width="321" alt="Screenshot 2022-09-18 at 15 55 36" src="https://user-images.githubusercontent.com/30310907/190925998-dc2af7ae-db60-4b06-b445-cad3f09ad6de.png">

**Comment by PeerRich** [comment]
@CarinaWolli do we just truncate? i think that's best

**Comment by jjromary** [comment]
@CarinaWolli This solution meets your needs?

![image](https://user-images.githubusercontent.com/37199044/193083911-694d9ad4-5b77-4610-aa67-109cc630d086.png)

**Comment by CarinaWolli** [comment]
I just saw that the setting shell now has a horizontal scroll, even for english when no words are overflowing. See here: https://www.loom.com/share/0d5d6db20aa34640a11221d5e6702582

@Jaibles do we want that horizontal scroll in the settings shell?

**Comment by Jaibles** [comment]
@CarinaWolli I'm getting a 404 on the loom but assuming we do not want that horizontal scroll. Any objection to truncating as Peer suggested?

**Comment by CarinaWolli** [comment]
@Jaibles Here is another loom how it currently looks with the scroll (definitely does not look right): https://www.loom.com/share/35ea5ba6f71449c894a7c4223b923bd2

I don't have any objection to truncating 👍

**Comment by G3root** [comment]
hey @CarinaWolli i'd like to take on this issue if no one is working.

**Comment by CarinaWolli** [comment]
@G3root For sure 👍 So the goal is to disable the horizontal scroll and to truncate words that are too long for the settings shell

**Comment by G3root** [comment]
@CarinaWolli is this implementation correct ?
![Screenshot 2022-10-20 21:22:10](https://user-images.githubusercontent.com/84864519/196997882-f5d85a36-e25e-4ed1-825e-162a508d815d.png)

**Comment by CarinaWolli** [comment]
@G3root Maybe we can add the same padding to the right side as it is on the other sides and also add an ellipsis ('...') at the end so it is clear that the word is truncated
