### ISSUE TITLE
Skeleton loader for settings/api-keys empty state looks wrong

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#4585]
### Issue Summary

That's how it currently looks: 
<img width="1512" alt="Screenshot 2022-09-18 at 16 33 48" src="https://user-images.githubusercontent.com/30310907/190927225-ea0d9d8b-aec0-497d-af8a-ad602c5f6a3b.png">

But it should look the same as the empty state of settings/webhooks

**Comment by Emmanuel-Melon** [comment]
> ### Issue Summary
> That's how it currently looks: <img alt="Screenshot 2022-09-18 at 16 33 48" width="1512" src="https://user-images.githubusercontent.com/30310907/190927225-ea0d9d8b-aec0-497d-af8a-ad602c5f6a3b.png">
> 
> But it should look the same as the empty state of settings/webhooks

What's the expected behavior? Is there a design reference that I can look at?

**Comment by CarinaWolli** [comment]
Like webhooks, it just shouldn't show the skeleton loader and empty state view at the same time.
<img width="1505" alt="Screenshot 2022-09-19 at 10 38 32" src="https://user-images.githubusercontent.com/30310907/191043992-b04e8111-9aa9-470f-a979-6e0602963851.png">

**Comment by Emmanuel-Melon** [comment]
> Like webhooks, it just shouldn't show the skeleton loader and empty state view at the same time. <img alt="Screenshot 2022-09-19 at 10 38 32" width="1505" src="https://user-images.githubusercontent.com/30310907/191043992-b04e8111-9aa9-470f-a979-6e0602963851.png">

This is strange. I can't reproduce this issue locally but I can see it in the production environment.
