### ISSUE TITLE
Increase max minimumBookingNotice or make it a text input instead of dropdown

### ISSUE THREAD

**Issue by bcneese** [calcom/cal.com#4590]
### Is your proposal related to a problem?

I like to be able to look at my calendar at night to get a picture of what my next day will be like, but because the maximum value for minimum booking notice is 2 hours I can't do this.

### Describe the solution you'd like

Please increase the max option to be more than 120 minutes or maybe make an option for me to type in a number of minutes of my choosing.

### Describe alternatives you've considered

My current workaround is to intercept my post request when I update the event and manually change the 120 minutes to some higher value, but this is a pain.

### Additional context

N/A

**Comment by flagu** [comment]
https://github.com/calcom/cal.com/issues/3962

**Comment by bcneese** [comment]
Yes, that seems like it would be a great solution. I don't know why I wasn't able to find that issue before I wrote this one

**Comment by PeerRich** [comment]
fixed a long time ago it seems
