### ISSUE TITLE
Prompt booker to input location

### ISSUE THREAD

**Issue by bcneese** [calcom/cal.com#4591]
### Is your proposal related to a problem?

I meet with a lot of people at coffee shops, but I prefer to let them choose the shop that they would like. Cal doesn't allow me to leave a blank location if I choose "In-person" and doesn't include an option to let the booker choose the location (I believe it's a feature with calendly).

### Describe the solution you'd like

I would like to be able to choose an option (as a sub-option of "in person") for the booker for choose the location, and then the booker has a small Google maps-like interface to enter the address of where we will meet. Another thing that would be above and beyond is if I could set a pin somewhere and say that the location they choose needs to be within X miles/km of my pin, but that sounds much more involved.

### Describe alternatives you've considered

My current workaround is to leave the location field blank and add my own additional field for location so that they can type in what they want, but this doesn't provide address checking, or if someone writes "Starbucks" without specifying which of the million locations it can lead to problems. This also causes the location field to be blank in the calendar event, which doesn't look as nice or work as well with phones that can let you know when to leave based on travel time to the location of your next event.

### Additional context

Thanks for all your hard work on this amazing product! I'm working on my coding skills and hope to be able to make code contributions one day, but for now I figured providing feedback was better than just using the app without giving any input.

**Comment by WispOfTheWinds** [comment]
Just want to second this! I have a similar use case that would benefitfrom this.

I have clients create appointments with me for services at their home. Using Additional Inputs definitely works, but letting them set the actual event location upon booking would be a much better experience.

**Comment by PeerRich** [comment]
how much different is this to just adding an "additional input"? not really no?

**Comment by WispOfTheWinds** [comment]
It's definitely more of a UX thing for the host specifically, there's not really core functionality that's missing.

For my use case where I tend to be checking addresses to put into my GPS multiple times a day, I have the attendee input their address as 5 Additional Inputs: Address Line 1, Address Line 2, City, State, ZIP (this is pretty standard format for address format on forms). Doing this makes the address split up and difficult to read on the calendar event.

Allowing the attendee to input a location for the calendar event would make the address easier to read and easier to input into a GPS app (most calendar apps allow one tap to automatically open the event location in Maps).

It's definitely not a make or break issue and Additional Units do work, they just have their annoyances. It would be VERY nice to have this feature 😄

**Comment by PeerRich** [comment]
oh i see. yeah we could use something like google maps street auto complete which we could add as a type in "additional inputs" and it gives you a clean JSON of the data via webhooks or inside the app

**Comment by PeerRich** [comment]
I think we added this as a location option. can you check?
