### ISSUE TITLE
Can't enable more than one CalDav calendar in settings / enabled calendars get reset on reload

### ISSUE THREAD

**Issue by SamuelBlickle** [calcom/cal.com#4592]
### Issue Summary

When selecting more than one CalDav calendar to check for conflicts on cal.com, the selection is getting reset when the page is reloaded. Only the calendar selected to add new bookings to stays enabled. Therefore I am unable to select multiple CalDav calendars at the same time.

### Steps to Reproduce

1. Set up a CalDav connection as usual
2. Go to settings > calendars
3. Switch an additional calendar on (other than the one for bookings to be added to)
4. Reload the page or switch to an other one and then come back to the calendars settings page

### Technical details

- Current Firefox and Chrome browser
- No funny business in the web console
- Only 200 status responses to all requests sent

![caldav](https://user-images.githubusercontent.com/19328605/190968119-5105fec5-f48d-4e8b-ab73-f1177a93a7f2.gif)

**Comment by ConnorGargano** [comment]
Hi @SamuelBlickle,

Many thanks for raising this with our team!

It looks like this issue is ongoing with google calendars also.

I will inform the team to take a look at this.

Kind regards,
Connor

**Comment by alishaz-polymath** [comment]
So, I can see that this isn't true, please see the loom video here:
https://www.loom.com/share/1f08ff08c9804f29a25b8d991cf11aff
Hence, closing this ticket for now. 
Please feel free to re-open this if you still face the issue and the loom video experience is different from your experience.
