### ISSUE TITLE
Cal.com show I'm busy even if google calendar is free

### ISSUE THREAD

**Issue by Guray00** [calcom/cal.com#4596]
### Issue Summary
I'm using cal.com with Google Calendar integration (only this). There are random days where cal.com says I'm busy between hour x and hour y even if I have nothing planned and also even if i totally disabled conflicts check (in particular on any friday).

### Steps to Reproduce
1. Sync google Calendar with cal.com
2. Check for conflicts on some days

It should show me free and allow booking in that days. I'm using the right google calendar account. I have no calendar hidden.

In the photo:

> Your calendar shows you as busy between 09:00 and 12:00 on 20 September 2022 - (source: google-calendar)

### Technical details
![image](https://user-images.githubusercontent.com/30523962/191003613-7e64e208-2693-4865-a12f-bf25b2eb77d1.png)
![image](https://user-images.githubusercontent.com/30523962/191003667-e48dbddf-8340-4236-a82d-a986528b18ac.png)
![image](https://user-images.githubusercontent.com/30523962/191003693-b99626c4-3410-4820-b0ab-3430f1abf8d2.png)

**Comment by Guray00** [comment]
Still having problem

**Comment by Guray00** [comment]
Still having problem

**Comment by PeerRich** [comment]
@alannnc can you investigate?

**Comment by alannnc** [comment]
Hey @Guray00 I will be investigating this issue. 
My guess is there still some kind of recurrent event in your calendar. Feel free to book a 1:1 with me to debug this https://cal.com/alancalcom/15min
In the meanwhile I will take a look at the code to see if I can detect anything.

**Comment by Guray00** [comment]
Thanks you for your support, how much before should I book?

I I should not have any recurring event, with calendy I haven't got any issue

**Comment by Guray00** [comment]
i'm sorry, i booked for 12 AM instead of 12PM, my bad, I'm not used with it...

**Comment by Guray00** [comment]
> Hey @Guray00 I will be investigating this issue. 
> My guess is there still some kind of recurrent event in your calendar. Feel free to book a 1:1 with me to debug this https://cal.com/alancalcom/15min
> In the meanwhile I will take a look at the code to see if I can detect anything.

Hey @alannnc , when can we meet? I booked for today with no luck

Have a good day!

**Comment by alannnc** [comment]
My bad, I just stepped my game for notifications on bookings if you wanna do that again. After a deep dive at our code I find that the troubleshooter it's not working properly with certain timezones (A fix will be on his way soon). But from our data looks like an All day Google Calendar on your side that's recurring on Friday. In troubleshooter you can see that we display busy on your Thursday from 6pm till Friday 6pm this is because something not working properly on our end with the timezone. I can help you look for that if you want.

**Comment by Guray00** [comment]
Yes of course, I will book another one for tomorrow (now is 1 am here). Let me know If I can help in any way, but I'm pretty sure that the calendar doesn't have that recurring event (and i will show you in the call). Thanks for all your work, I really like cal and i would really like to use it :)
@alannnc

**Comment by alannnc** [comment]
Sure no worries, in the meanwhile you can try removing Google calendar for a minute and see if Friday comes available again. @Guray00

**Comment by Guray00** [comment]
Removed the plugin and added again after some minutes with no luck, still busy on Friday. I booked a meeting for tomorrow if you are free @alannnc

**Comment by alannnc** [comment]
See you tomorrow! @Guray00

**Comment by alannnc** [comment]
Good news @Guray00, there was a conflict on our side that was picking up old connected calendars you had before. Did you ever happen to install a Lark suite calendar? We've done the fixes and now your availability is back to normal.

**Comment by Guray00** [comment]
Yes of course, I will book another one for tomorrow (now is 1 am here). Let me know If I can help in any way, but I'm pretty sure that the calendar doesn't have that recurring event (and i will show you in the call). Thanks for all your work, I really like cal and i would really like to use it :)
@alannnc I checked now, it's working thanks! Is really strange, I installed the lark suite because it was not working Google calendar for the mentioned bug. 

The only minor issue I'm facing is that, if I'm not wrong, is saying I'm available until 22 (GMT +1), but we setup free until 23:45.

Really nice work! If I will see something I will report as soon as possible if can help, have a nice day!

**Comment by Guray00** [comment]
Yes of course, I will book another one for tomorrow (now is 1 am here). Let me know If I can help in any way, but I'm pretty sure that the calendar doesn't have that recurring event (and i will show you in the call). Thanks for all your work, I really like cal and i would really like to use it :)
@alannnc I checked now, it's working thanks! Is really strange, I installed the lark suite because it was not working Google calendar for the mentioned bug. 

The only minor issue I'm facing is that, if I'm not wrong, is saying I'm available until 22 (GMT +1), but we setup free until 23:45.

Really nice work! If I will see something I will report as soon as possible if can help, have a nice day!

**Comment by alannnc** [comment]
> The only minor issue I'm facing is that, if I'm not wrong, is saying I'm available until 22 (GMT +1), but we setup free until 23:45.
This is because between 23:00 and 23:45 a 60 min slot wouldn't fit. Probably having the option to set end time to 23:59 would fix this.

Thanks to @emrysal for the help too.

**Comment by alannnc** [comment]
Closing as main issue was solved.
