### ISSUE TITLE
Avatar overflow when scrolling in settings

### ISSUE THREAD

**Issue by QuiiBz** [calcom/cal.com#4607]
### Issue Summary

When navigating to the [settings](https://app.cal.com/settings/my-account/profile) with a smartphone and scrolling, the avatar and "Change Avatar" button overflows the top navbar. Also, when scrolling back up, it's hard to show again the "Profile" title and description - looks like there are two scrollable containers?

### Steps to Reproduce

1. Go to https://app.cal.com/settings/my-account/profile on a smartphone
2. Scroll down, the avatar should overflow

https://user-images.githubusercontent.com/43268759/191064063-eb563de8-83cb-4265-9328-f654593cc6a1.mp4

### Technical details

- Safari
- iOS 16
- iPhone 14 Pro

**Comment by PeerRich** [comment]
i think this has been fixed, not sure

**Comment by QuiiBz** [comment]
Couldn’t reproduce so I assume it has been fixed!
