### ISSUE TITLE
[CAL-122] Editing default availability from an event type causes a 404

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#4608]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When editing the availability of an event type with the default availability it navigates to a 404 page because the default availability does not contain an id. 																																																																															

### Steps to Reproduce

1. Go to an event type with the default availability.
2. Go to the availability tab and edit the availability
3. It should redirect to a 404 page

**Comment by howardwkim** [comment]
It's not just that the "Edit availability" link it redirects to a 404 page, It seems that no availability data is getting pulled in.

![image](https://user-images.githubusercontent.com/8857643/191819403-7dd6ab14-9736-4f06-bf05-3091805e5a2a.png)

**Comment by howardwkim** [comment]
I found the Availability page and was able to set hours. However, the Edit availability button still opens to `https://app.cal.com/availability/undefined`

![image](https://user-images.githubusercontent.com/8857643/191820392-deacc36a-75f1-4096-b240-d5bcb4d2875b.png)

**Comment by KlingerMatheus** [comment]
Hello @joeauyeung. Can I work on this one?

**Comment by joeauyeung** [comment]
@KlingerMatheus sure, I just unassigned myself. Thanks!

**Comment by PeerRich** [comment]
@KlingerMatheus  any update? if not, we'll work on it

**Comment by KlingerMatheus** [comment]
@PeerRich Hello, sorry for late response. I can't reproduce this issue anymore, the `Edit availability` button is redirecting correctly here in my machine, that's why I couldn't work the PR. Could you try reproduce it and confirm, please?
