### ISSUE TITLE
Embed: Customization Improvements

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4617]
Some of the feedback directly from customers
- ~~Configure Calendar Size~~
- ~~A advanced custom CSS option that should be able to rewamp the entire embed~~

**Comment by mikayelh** [comment]
hey there, 

1. would love better branding options/customizability: Currently, the only place brand colors are implemented is the day selector color and the date and time in the next screen. We'd need more options, such as coloring the buttons (for booking), hyperlinks (e.g. rescheduling/cancellation) and the background (in the calendar).

2. Far, more importantly, need to be able to have a mini calendar (in the current implementation, for instance, you waste three-four lines that can be condensed into one with time zone/mode of call, etc).  If we could switch to a minimized version (e.g. quarter of the current one), that would work without the need to scroll if the size is minimized, that'd be 

3. You currently offer adaptive design based on user's system for dark mode. Would be cool to have some sort of parameter out-of-the-box we can use to adapt it ourselves w/o the need to poke around the css.

**Comment by hariombalhara** [comment]
Thanks for the feedback @mikayelh. This is a good feedback 🙏
Regarding point no - 3, if you simply mean to enable dark mode/light mode/user preference for embed, this is already possible. If not, could you please explain it a bit more.

**Comment by mikayelh** [comment]
we have a dark mode toggle on our website, so looking for very obvious ways to hook those two up (we've already achieved this but looking for something more intuitive).

**Comment by LilaRest** [comment]
@hariombalhara Any news on this ? This [page](https://cal.com/resources/feature/embed) mentions that the embeded calendars can be customized to feel "like an indiscernible part of your website", but actually it seems that customization options are very limited.

I'm even not able to change the background color of the hours selection box, or maybe am I missing some resources ?

**Comment by zacsanter** [comment]
Surely this should be a higher priority if your live marketing page says it's possible?

**Comment by hariombalhara** [comment]
@LilaRest Here is a codesandbox showing what's possible now. If you have something else in mind let me know.

**Comment by LilaRest** [comment]
Hi @hariombalhara ! It sounds great thanks, but cannot find the link in your message. Did you forget it?

**Comment by hariombalhara** [comment]
Oh here it is https://github.com/calcom/cal.com/issues/8841 😂
The ticket had the link
