### ISSUE TITLE
[v2 Component] Input prefix & suffix components spacing is too large

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4621]
Currently
![Image](https://user-images.githubusercontent.com/4536123/191232554-34ced2ab-cf64-4cc7-81e5-03bc065d7c1e.png)

Should be

![Image](https://user-images.githubusercontent.com/4536123/191234387-b87ebf25-beb2-48cb-9c7f-0d2a2b9b4761.png)

**Comment by imkrunal** [comment]
#4623 @Jaibles
