### ISSUE TITLE
[v2 component] Toast does not animate up onto the screen.

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4622]
Currently the toast just appears. It should animate up and into the screen so it grabs the attention a little more. (We used to have it like this). Now it just suddenly appears and is not effective at subtly confirming user actions.

Note: The subsequent toasts do animate in as expected.

https://user-images.githubusercontent.com/4536123/191244127-d953d298-b2c1-4816-b59a-d5de5f064a6a.mp4

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/191348609-1675892c-ff1b-4f12-9149-f03fce153910.mov

i tried adding some custom transitions. is this fine ?

**Comment by atharvapatil46** [comment]
Hello @Jaibles Sir, can I work on this one?
