### ISSUE TITLE
No time limitation on 'Minimum notice'

### ISSUE THREAD

**Issue by peachboy7** [calcom/cal.com#4624]
### Is your proposal related to a problem?

Currently, the minimum notice time can be set maximum up to 120 minutes. However, for someone like me who is working at VC, we want to take meetings at least with a day or two of minimum notice. Sometimes this can be up to a week. This is because we do not want such sudden meetings that can hamper our current schedule (given we do not add many offline activities to our calendar). So keeping a longer minimum notice mitigates that risk. This is the only thing that is holding me off from switching to Cal fully. 
### Describe the solution you'd like

The best solution for this can be no time limitation on minimum notice. Meaning I can manually set a custom range (eg: 24 hours, 7 days, 1 month, etc.) as the minimum notice period. 
### Describe alternatives you've considered

I have considered Zcal as my second option if Cal does not have this.
### Additional context

No

**Comment by emrysal** [comment]
Hi @peachboy7,

This was a recently introduced limitation that should not be there, it will be brought back as it's original form and in the future more work will follow as per https://github.com/calcom/cal.com/issues/4590
