### ISSUE TITLE
/calendars /check for conflicts - Show toasts to confirm changes to which calendars to check for conflicts on

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4628]
Currently when you toggle a calendar to check for conflicts, we seem to show a toast if there's an error, but not to confirm the successful update.

This needs to be updated in 

- [ ] /apps/installed-apps/calendars
- [ ] /settings/calendars

Currently
https://user-images.githubusercontent.com/4536123/191273372-1263a44e-c97d-4793-836f-826310a72c66.mp4

Should be

![Image](https://user-images.githubusercontent.com/4536123/191273998-65f440f3-b3d9-438c-a9c9-11549e06a236.png)

**Comment by harshsinghatz** [comment]
Can i work on this?

**Comment by PeerRich** [comment]
> Can i work on this?

yes please @harshsinghatz

**Comment by harshsinghatz** [comment]
@PeerRich I would love to pick this up, but currently, I don't have the bandwidth due to exams at my college. I would be available from Tuesday. So if it's not a priority task I can pick it up later.

**Comment by PeerRich** [comment]
> @PeerRich I would love to pick this up, but currently, I don't have the bandwidth due to exams at my college :( . I would be available from Tuesday. So if it's not a priority task I can pick it up later.
> 
> I had the bandwidth when I asked to pick the task initially

that's ok, focus on your exams!

**Comment by harshsinghatz** [comment]
@PeerRich is this still open?

**Comment by emrysal** [comment]
This is now implemented using a spinner - closing this as it's basically superseded by a suitable implementation.
