### ISSUE TITLE
Calendar Overview Page: Options disappear with delay

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4631]
When clicking on a date with apple calendar activated first all meeting options show up (in the working hours range) and after two seconds the already booked times disappear.

https://user-images.githubusercontent.com/88643432/191280645-d1aaf2e9-6313-4eda-b4e1-97216d75ad2e.mov

**Comment by lukasklein** [comment]
I'm seeing the same behavior on my calendar (cal.com/lukasklein/meet), in addition, if a day is fully booked (like tomorrow/thursday/friday is for me this week), the days are shown as available in the overview, but when you click them, after a couple of seconds, all options for the day disappear and the day gets disabled. If you're fast enough, you can even select an unavailable time (though the booking doesn't go through later)

As a user, I would expect the overview to only allow selecting days with at least one available time-slot.

![2022-09-20 20 33 52](https://user-images.githubusercontent.com/1492869/191338141-47402059-b0c6-423a-b992-942d2c87bb34.gif)

**Comment by PeerRich** [comment]
@emrysal can you test this?

**Comment by PeerRich** [comment]
i believe this has been fixed a long time ago. can you check?
