### ISSUE TITLE
Duplicate sidebar on settings

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#4642]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When opening the sidebar with the split screen and then increasing the screen the sidebar is duplicated

### Steps to Reproduce

1. Go to http://localhost:3000/settings
2. Decrease the screen size and open the sidebar
3. The side bar will be duplicated

![Screenshot from 2022-09-21 09-28-54](https://user-images.githubusercontent.com/87545086/191503825-78a49849-1852-4c40-852c-8792cbca1c44.png)

Loom video: https://www.loom.com/share/e469fc0292174d13b65fee736191259b

**Comment by PeerRich** [comment]
great discovery, we'll fix

**Comment by Toledodev** [comment]
I was trying to solve this problem and what I thought was just omitting one sidebar when another one is open, something like this:

https://www.loom.com/share/0cd0369b8dfd4c7c8909c76728a5a49a
