### ISSUE TITLE
[CAL-123] /settings sidebar doesn't match figma designs

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4643]
There are some subtleties to spacing in the settings sidebar that make it easier to scan, particularly the sectioning of different settings areas that are not reflected from the Figma designs.

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17937%3A171647)

<img width="1148" alt="CleanShot 2022-09-20 at 22 06 16@2x" src="https://user-images.githubusercontent.com/4536123/191364539-ab7a6433-c505-4667-a28e-e807f8b2114e.png">

**Comment by harshsinghatz** [comment]
Can i work on this?

**Comment by Jaibles** [comment]
Yep go ahead @harshsinghatz

**Comment by harshsinghatz** [comment]
Sure

**Comment by Udit-takkar** [comment]
<img width="593" alt="Screenshot 2022-09-22 at 2 04 25 AM" src="https://user-images.githubusercontent.com/53316345/191605040-f8e99ff8-ca63-45a9-8703-7f94e4e07b61.png">

one more thing in mobile sidebar the team logo is not centered in teams.

**Comment by harshsinghatz** [comment]
I will take a look at that as well!

**Comment by AdityaPainuli** [comment]
Hey is anyone working on this issue or can I work on this one ?

**Comment by harshsinghatz** [comment]
> Hey is anyone working on this issue or can I work on this one ?
> 

Currently, I am working on it

**Comment by AdityaPainuli** [comment]
> > Hey is anyone working on this issue or can I work on this one ?
> 
> Currently, I am working on it

Ok no worries 👍

**Comment by Jaibles** [comment]
There's also a line-height issue with the nav items causing it to not be vertically centered.

[35e7a9ac-dc46-473b-ab9b-9a3ca5bf6fb2](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ae93d516-cbea-4285-b0f0-d8d924b7afa2/35e7a9ac-dc46-473b-ab9b-9a3ca5bf6fb2)

**Comment by harshsinghatz** [comment]
@Jaibles Got it!, is it a priority fix? or can i do this in a few days?
Because currently my exams are going on, so i would be active after the exams are done!

**Comment by Jaibles** [comment]
in a few days is ok! thanks @harshsinghatz  🙏 and good luck in the exams :)

**Comment by Jaibles** [comment]
@Udit-takkar fancy having a go at this one?

**Comment by Jaibles** [comment]
This is still not done

[a79e5a16-e0fb-46e3-a77a-1da74d8ae025](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ed366b0d-d6a0-42ef-ac46-9bcd8083e6ac/a79e5a16-e0fb-46e3-a77a-1da74d8ae025)
