### ISSUE TITLE
Onboarding, input validation error isn't positioned correctly

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4660]
<img width="1270" alt="Screenshot 2022-09-22 at 9 40 23 AM" src="https://user-images.githubusercontent.com/1780212/191656610-dd1f99db-77c6-417d-96de-016d83c7cb4c.png">
Error isn't properly placed. Looks like it's missing some padding.

**Comment by Emmanuel-Melon** [comment]
Added `py-2` to bo both error components. Let me know what you think.
<img width="662" alt="Screen Shot 2022-09-22 at 17 12 36" src="https://user-images.githubusercontent.com/21015204/191771777-d9228495-4314-45c0-97f0-34c90009d79e.png">
<img width="678" alt="Screen Shot 2022-09-22 at 17 17 25" src="https://user-images.githubusercontent.com/21015204/191771803-a18bb12b-2437-40b7-b042-624c01573400.png">

**Comment by Emmanuel-Melon** [comment]
> Added `py-2` to bo both error components. Let me know what you think. <img alt="Screen Shot 2022-09-22 at 17 12 36" width="662" src="https://user-images.githubusercontent.com/21015204/191771777-d9228495-4314-45c0-97f0-34c90009d79e.png"> <img alt="Screen Shot 2022-09-22 at 17 17 25" width="678" src="https://user-images.githubusercontent.com/21015204/191771803-a18bb12b-2437-40b7-b042-624c01573400.png">

@Jaibles I'll check if there are more instances of this in other forms.

**Comment by Jaibles** [comment]
@sean-brydon @hariombalhara would I be right in thinking that the resolution to this is by ensuring we're using v2 components as opposed to making individual adjustments across the app?

**Comment by hariombalhara** [comment]
Yeah error should be part of component

**Comment by Emmanuel-Melon** [comment]
> @sean-brydon @hariombalhara would I be right in thinking that the resolution to this is by ensuring we're using v2 components as opposed to making individual adjustments across the app?

Yeah, having to make the fix once is definitely the right approach but I'm not sure if this issue persists across the entire app or simply those two occurrences. I wanted to go through more components to confirm the need for a global fix.

**Comment by Emmanuel-Melon** [comment]
> @Emmanuel-Melon that looks better thank you. Can we change the text from italic to just regular text please?
> 
> <img alt="CleanShot 2022-09-22 at 15 40 48@2x" width="542" src="https://user-images.githubusercontent.com/4536123/191777450-429d2a66-cbd5-42f1-bd5f-d394224f47a3.png">
> 
> @sean-brydon @hariombalhara would I be right in thinking that the correct resolution to this is to ensure we include this in our v2 component and only have to make this fix once, rather than have it be added/fixed in many instances across the app?

I haven't found other instances so I think this fix is okay. And definitely, I will change it to regular 😁
