### ISSUE TITLE
/booking show date and time on mobile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4663]

**Comment by nnaemekaibe** [comment]
@PeerRich Please can i have more details on where the date and time should be shown.

**Comment by hariombalhara** [comment]
@nnaemekaibe You can refer to this https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A65855

**Comment by PeerRich** [comment]
@Udit-takkar you fixed this right?

**Comment by Udit-takkar** [comment]
yes
