### ISSUE TITLE
Mobile - Bookings: Bottom nav should show on all tabs

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4664]
Whatever way we set the navbar to hide, it has included all tabs on the booking page. The nav should show on the booking page no matter what tab you are on.

[Previous discussion here](https://github.com/calcom/cal.com/issues/4398#issuecomment-1254704056)

![Image](https://user-images.githubusercontent.com/4536123/191700038-59d38854-cfaa-431c-8034-b6977d8104b6.png)

**Comment by gracebir** [comment]
@Jaibles , is this the expected behavior [https://www.loom.com/share/f9d10960faf148ac9e5b191285a847ff](https://www.loom.com/share/f9d10960faf148ac9e5b191285a847ff)

**Comment by gracebir** [comment]
sure @Jaibles

**Comment by PeerRich** [comment]
@hariombalhara you fixed this right?
