### ISSUE TITLE
Fix Integration Tests that require MSW server side mocking

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4667]
<img width="893" alt="Screenshot 2022-09-22 at 3 42 50 PM" src="https://user-images.githubusercontent.com/1780212/191720859-b5cf9cf4-bdb1-46fc-807d-f587fa6a294e.png">

**Comment by Rajashekarksreddy** [comment]
I would like to work on this issue, I have some idea about it. /attempt #4667

**Comment by hariombalhara** [comment]
@Rajashekarksreddy Sure please go ahead

**Comment by omkarg01** [comment]
@hariombalhara how to run these test to check what is the result ?

**Comment by ologbonowiwi** [comment]
What do we need to do on this one?

Do we need to set it up MSW, remove it, or change it to a new tool?

**Comment by hariombalhara** [comment]
We need to be able to mock test third party API endpoints. So, if MSW works, then that's perfect, but there was some issue with MSW due to which we had to disable it. I think @joeauyeung would be working on this, so I would suggest not to focus on this now.

**Comment by ptdatta** [comment]
Is this issue solved?

**Comment by hariombalhara** [comment]
Not a priority for me a the moment. So, removing it from milestone.

**Comment by mak2002** [comment]
I would love to fix this issue! Will give it a shot.

**Comment by webbdays** [comment]
/attempt #4667
> We need to be able to mock test third party API endpoints. So, if MSW works, then that's perfect, but there was some issue with MSW due to which we had to disable it. I think @joeauyeung would be working on this, so I would suggest not to focus on this now.
@hariombalhara 
What is the issue with msw? Please describe.
Thank you.

**Comment by hariombalhara** [comment]
I think we are instead focussing on real testing with third parties instead of mocking the responses.

We have some tests as well now for that flow. So, closing this one.
