### ISSUE TITLE
public page: border and padding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4671]
- [ ] more padding bottom on mobile 
- [ ] wrong border color
- [ ] remove border on mobile

![image](https://user-images.githubusercontent.com/8019099/191779234-c6c2df70-e7d0-47be-bd25-bdf1815cfd5e.jpeg)

![image](https://user-images.githubusercontent.com/8019099/191779309-ba76ab09-852f-4a2f-8256-870247aae45a.jpeg)

![image](https://user-images.githubusercontent.com/8019099/191779400-2dbb8c49-84d3-406b-924e-6045c1170938.png)

**Comment by KlingerMatheus** [comment]
Hello @PeerRich. Can I work on this one?

**Comment by jaysoni-ash42** [comment]
@PeerRich  do we have a design for the changes like how much more padding what should be the default border color ?

**Comment by KlingerMatheus** [comment]
@PeerRich 

* [ ] More padding bottom on mobile ->

![4671 - PADDING ON MOBILE](https://user-images.githubusercontent.com/50892465/191918106-c0dd18f5-cbe5-404e-9bd5-e99f05a71e8a.png)
_________________________________
* [ ] Wrong border color -> 

![4671 - WRONG BORDER COLOR](https://user-images.githubusercontent.com/50892465/191918367-8369d529-cd33-49b1-8e4c-37d9311bfb5a.png)
_________________________________
* [ ] Remove border on mobile ->

![4671 - REMOVE BORDER ON MOBILE](https://user-images.githubusercontent.com/50892465/191918439-97f7d573-bae2-41d6-8675-110762dbac35.png)

_________________________________
**I took the liberty to make this preview and would like to know, what do you think of it?**

**Comment by PeerRich** [comment]
> @PeerRich 
> 
> 
> 
> * [ ] More padding bottom on mobile ->
> 
> 
> 
> ![4671 - PADDING ON MOBILE](https://user-images.githubusercontent.com/50892465/191918106-c0dd18f5-cbe5-404e-9bd5-e99f05a71e8a.png)
> 
> _________________________________
> 
> * [ ] Wrong border color -> 
> 
> 
> 
> ![4671 - WRONG BORDER COLOR](https://user-images.githubusercontent.com/50892465/191918367-8369d529-cd33-49b1-8e4c-37d9311bfb5a.png)
> 
> _________________________________
> 
> * [ ] Remove border on mobile ->
> 
> 
> 
> ![4671 - REMOVE BORDER ON MOBILE](https://user-images.githubusercontent.com/50892465/191918439-97f7d573-bae2-41d6-8675-110762dbac35.png)
> 
> 
> 
> _________________________________
> 
> **I took the liberty to make this preview and would like to know, what do you think of it?**
> 
> 

looks awesome!!

**Comment by PeerRich** [comment]
@KlingerMatheus did you submit a PR yet?
