### ISSUE TITLE
Google calendar stuck

### ISSUE THREAD

**Issue by odama626** [calcom/cal.com#4674]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When creating account I added a google calendar and only checked the first of the two permissions.  now when looking at calendars I get an an error message "something went wrong" "insufficient permissions" this also happens when looking at installed apps page.

![image](https://user-images.githubusercontent.com/11347689/191834309-04e54a45-c564-4900-900d-1d13b6dab6e0.png)
![image](https://user-images.githubusercontent.com/11347689/191834423-d9dcb750-fb06-4e82-95c4-ac468bd171c5.png)

also -- the app is currently unusable for me from this I believe?  and I'm unable to remove that calendar to fix the problem

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by milospuac** [comment]
Hi there

Both permissions are necessary in order for Cal.com to connect with your Google Calendar, however, that is not the behavior intended. There should be an option to remove that failed calendar integration and start all over, but right now the account is unusable. Sorry about that. 

Our engineers are aware of this and currently are working on a fix. 

Thank you for your patience.

**Comment by PeerRich** [comment]
I am quite sure this was fixed a long time ago
