### ISSUE TITLE
Layout shift when editing availability 

### ISSUE THREAD

**Issue by MFCo** [calcom/cal.com#4677]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When loading the editing availability page, there's a layout shift + a flash with non-human readable placeholders.

### Steps to Reproduce

1. Went to one of my events
2. Clicked on `Edit Availability`

I do not think it's a high-impact bug, but taking into consideration how polished is most if the UI, it's worth mentioning. Here is a video on it

https://share.cleanshot.com/zALpil

### Technical details

- Chrome Version 105.0.5195.125
- MacOS 12.5.1

**Comment by emrysal** [comment]
Thanks for reporting @MFCo - you're entirely right - I have opened a PR with improvements.
