### ISSUE TITLE
Apple Calendar: Seems like only one calendar get's checked for duplicates at the time

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4684]
We've connected 3 calendars but only 1 get's checked for duplicates

**Comment by milospuac** [comment]
Hi there

What is the calendar in question? The other two don't get checked for conflicts?

**Comment by jorit-vasconezgerlach** [comment]
Hi @milospuac, I've connected Apple Calendar with CalCom and selected in this connection 3 calendars to check for conflicts.

**Comment by PeerRich** [comment]
@alishaz-polymath can you reproduce this? have you heard of this?

**Comment by alishaz-polymath** [comment]
I couldn't reproduce this earlier. Week test one more to be sure 🙏
