### ISSUE TITLE
Add description where selected theme colours will be visible

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4685]
We've set the colours, but don't really know what they influence.

Our exception without description: They'll be added on our booking page and maybe on mails

<img width="870" alt="Bildschirm­foto 2022-09-24 um 01 13 32" src="https://user-images.githubusercontent.com/88643432/192068250-882e7152-2fab-4c63-9b00-8ed1b28bfd6d.png">

**Comment by PeerRich** [comment]
thats easy. will fix

**Comment by PeerRich** [comment]
will be redone with new themes support once ready
