### ISSUE TITLE
Update Event Setting Menu on Event Time Change

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4686]
On the left side under "Event-Einrichtung" stands still 30mins also after saving the change to 20m.

It's a small detail, but it's helpful to see if event updated

<img width="1208" alt="Bildschirm­foto 2022-09-24 um 01 18 03" src="https://user-images.githubusercontent.com/88643432/192068654-2ee86737-5edd-4f07-9daa-05eeb9f97a03.png">

**Comment by PeerRich** [comment]
this has been fixed
