### ISSUE TITLE
Redirection of users landing on your 404

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4687]
## Problem

For example I create

cal.com/calcom/30m

and later decide to only provide a shorter time and update it to

cal.com/calcom/20m

users that'll try the old url will land on an 404 page, it looks nice but will decrease the conversion extremely

<img width="200" alt="Bildschirm­foto 2022-09-24 um 01 25 44" src="https://user-images.githubusercontent.com/88643432/192068968-e6010f37-6543-483c-bc69-fb97a697002e.png">

#### Importance

This could happen unknowingly and cause a big loss of conversions

## Idea

Introduction of an redirection option.

For the start maybe toggle to redirect every 404 to start root (cal.com/calcom/ in example)

Later even select an event to redirect to, for better conversion.

**Comment by jorit-vasconezgerlach** [comment]
I think this should be an initial checked option

**Comment by PeerRich** [comment]
we could redirect, yeah. lemme think about it

**Comment by PeerRich** [comment]
(a) we save the history of all names of an event-type

(b) we just redirect back to the profile page (i.e. cal.com/peer/45 which is broken redirects to cal.com/peer)

**Comment by PeerRich** [comment]
I advocate for (b)

**Comment by PeerRich** [comment]
lets just redirect all 404 of users back to the profile. no?

i.e. cal.com/peer/broken-link goes to cal.com/peer

**Comment by ologbonowiwi** [comment]
Fixed it on #9325. Can you please address someone to review? @PeerRich

**Comment by muescha** [comment]
As a user, I would expect to see a tooltip or a notice at the top of the page that informs me about the redirect. Otherwise, I would be left wondering why I am seeing the user page instead of a detailed page.

**Comment by ologbonowiwi** [comment]
There's anything that needs to be done here @PeerRich? If not I guess we can close this issue; if we need I'll be happy to help 🙂

**Comment by SuyashPatil-29** [comment]
Lmk if the issue still exists. I'd be happy to contribute.

**Comment by jorit-vasconezgerlach** [comment]
Yes, this "issue" still exists.

**Comment by DubeySandeep** [comment]
@jorit-vasconezgerlach As per [this comment](https://github.com/calcom/cal.com/pull/9325#issuecomment-1576946080) it looks like we already have the 404 redirections for an invalid URL (And I've also tested it locally on `main`.)

As per the [discussion](https://github.com/calcom/cal.com/pull/9325#issuecomment-1576666780), either (1) we need to have a custom 404 page for the invalid event OR (2) have the general 404 page (what we have as of now).

We are not planning for a custom 404 page as of now ([ref](https://github.com/calcom/cal.com/pull/9325#issuecomment-1576946080)), can you please update the requirements of this issue as needed?

/cc @PeerRich
