### ISSUE TITLE
Replacement Parameter visible after loading on password reset page (Maybe only in german)

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4690]
<img width="1440" alt="Bildschirm­foto 2022-09-24 um 01 39 32" src="https://user-images.githubusercontent.com/88643432/192069762-44422fa7-484d-4198-92cd-7b6adee60169.png">

**Comment by CarinaWolli** [comment]
I think this is already fixed in PR #4546 @hariombalhara can you please confirm that, and close the issue if it is fixed

**Comment by hariombalhara** [comment]
Yeah it should be fixed already on production
