### ISSUE TITLE
Scrollable page overflow on bookings page

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4691]
<img width="1440" alt="Bildschirm­foto 2022-09-24 um 01 50 10" src="https://user-images.githubusercontent.com/88643432/192070379-6119f5ff-c30b-4597-8fef-928399666bc2.png">

**Comment by AdityaPainuli** [comment]
Hey, @jorit-vasconezgerlach can you tell me how can I work on this issue?

**Comment by PeerRich** [comment]
we're working on this right now

**Comment by PeerRich** [comment]
@Udit-takkar is looking into making /booking more responsible

**Comment by jorit-vasconezgerlach** [comment]
@PeerRich I think this is fixed now

**Comment by Udit-takkar** [comment]
yes
