### ISSUE TITLE
Duplicate event action does not duplicate event location

### ISSUE THREAD

**Issue by dplanella** [calcom/cal.com#4693]
### Issue Summary

When using the Duplicate action to duplicate an event, all event settings are duplicated as expected, except from Location, which is reset to Cal Video.

### Steps to Reproduce

1. Go to Events
1. Navigate to an existing event, which has been set up with Zoom video as location
1. On the right-hand side, click on the ellipsis for that event
1. On the drop-down menu, click on Duplicate
1. Fill in the necessary details on the `Add event type` dialog
1. Click on Accept
1. On the next screen with the newly created event settings, Location has been reset to Cal Video

Expected:
- The Location of the new event is set to Zoom in the same way it was on the original event

### Technical details

- Browser version: Firefox 105
- OS version: Ubuntu 22.04

**Comment by milospuac** [comment]
Thanks for reaching out. 

Our team will investigate this.

**Comment by PeerRich** [comment]
tested and works. can't reproduce. likely fixed in the last few updates. if self-hosting can you update to the latest version?
