### ISSUE TITLE
Onboarding wizard: UI unfriendly to mid/long lengthed url

### ISSUE THREAD

**Issue by krumware** [calcom/cal.com#4703]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

For longer URLs on new instances, the first half of the URL/user input field extends to take up the entire row. This makes it appear to a user like they are unable to define their first username and begin setup.
The URL span should probably have a max-width and perhaps a text-overflow: ellipsis;

Short:
![image](https://user-images.githubusercontent.com/17303782/192108921-c31db039-31f3-4101-bd27-535a4e3eb164.png)

Long:
![image](https://user-images.githubusercontent.com/17303782/192108989-e290b3bf-9263-4584-86c1-e8f901649372.png)

### Steps to Reproduce

1. Set up a new cal.com instance
2. use a long URL for webapp_url
3. access URL
4. observe "disabled field"

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
@leog

**Comment by leog** [comment]
On it @PeerRich. Thanks for reporting it @krumware 👍
