### ISSUE TITLE
Zapier app installation not working

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#4706]
### Issue Summary

Zapier App installation is not working. The following error is thrown:

<img width="906" alt="Screenshot 2022-09-25 at 17 18 22" src="https://user-images.githubusercontent.com/30310907/192166058-5ae829ca-7a4d-4c39-84da-023011381cd3.png">

**Comment by Kfelts** [comment]
Also having an issue. When selecting the "install app" button, it shows visibly that it was selected and an event should be happening, but then nothing.
<img width="1424" alt="Screen Shot 2022-09-26 at 2 58 31 PM" src="https://user-images.githubusercontent.com/51497445/192358153-8dea0fee-4c9f-4aa7-b7af-e33773625e82.png">
<img width="1162" alt="Screen Shot 2022-09-26 at 2 58 38 PM" src="https://user-images.githubusercontent.com/51497445/192358158-ed86c9ff-dba5-43ae-a850-94b2d1fd59c9.png">
