### ISSUE TITLE
[CAL-1686] Meetings cannot be booked, with error "Could not book the meeting. JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

### ISSUE THREAD

**Issue by dplanella** [calcom/cal.com#4709]
### Issue Summary

Yesterday someone was still able to book a meeting using my 30 minute event. As of today, it's not possible to book meetings using that event. As soon as the details are entered on the event, the following error message is shown:

> Could not book the meeting. JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

No meeting is booked on the calendar after receiving this error.

I was able to reproduce it myself by trying to schedule the meeting with the person who first alerted me of this. Then I tried to use the event to schedule a meeting with myself, with the same result.

Once the error is shown, the meeting slot that was intended to be used is no longer available if one tries to book another meeting.

### Steps to Reproduce

1. Go to https://cal.com/dplanella/
2. Click on the 30 min meeting
3. Choose a date
4. Enter the meeting details
5. Click on Confirm
6. Error is shown: `Could not book the meeting. JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`. See screenshot below.
7. No meeting is booked
8. The slot used to book the failed meeting is no longer available to schedule further meetings.

![Error](https://user-images.githubusercontent.com/1689781/192276948-136610bf-5d0a-4120-b36e-b2dbcb208d59.png)

### Technical details

- Browser version: Firefox 105.0.1
- OS version: Ubuntu 22.04

<sub>[CAL-1686](https://linear.app/calcom/issue/CAL-1686/meetings-cannot-be-booked-with-error-could-not-book-the-meeting)</sub>

**Comment by milospuac** [comment]
Hi there

Thank you for reaching out. Can you try reinstalling your calendars? Make sure you tick all the necessary permissions and once you reconnect them test it out one more time

Let me know

**Comment by dplanella** [comment]
@milospuac thanks. I did as suggested, but I got a new set of messages, error and was unable to book a meeting:

1. Removed calendars
2. Re-added calendar

Then:

1. Go to https://cal.com/dplanella/
2. Click on the 30 min meeting
3. Choose a date
4. Choose a time. Confused by the "1/2 Seats available" and "2/2 Seats available" messages. See Screenshot no. 1 below
6. Enter the meeting details. Note message on "1/2 Seats available", which I can't understand.
7. Click on Confirm
8. Error is shown: `Could not book the meeting. Already signed up for time slot`. See screenshot no. 2 below.
9. No meeting is booked

Screenshot 1:
![Captura de pantalla de 2022-09-26 22-02-30](https://user-images.githubusercontent.com/1689781/192369825-e9b38613-03f3-4023-ad70-ef6d703dfcd2.png)

Screenshot 2:
![Captura de pantalla de 2022-09-26 22-03-10d](https://user-images.githubusercontent.com/1689781/192370272-ed515266-7232-4b52-8170-b3767f6dd9bf.png)

**Comment by PeerRich** [comment]
ideally we never show an error *after* clicking confirm and somehow catch the error earlier. maybe even hot-reload the page if something changes

**Comment by PeerRich** [comment]
@Udit-takkar can you investigate what is causing this?

**Comment by PeerRich** [comment]
pretty sure htis has been fixed
