### ISSUE TITLE
Individual Calendar Availability Leads to a 404

### ISSUE THREAD

**Issue by Kfelts** [calcom/cal.com#4714]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When selecting "edit availability" on individual calendars, the browser routes to an undefined url, leading to a 404. The availability time zone is also not in sync with the default time zone.

### Steps to Reproduce

1. Went to "Event Types"....select a specific calendar..."Edit"...."Availability"
2. Clicked on "edit availability"
3. New browser tab opens to a non-existent page. The routing isn't configured leading to this address: "https://app.cal.com/_next/data/Lana7_vyxUTEEIi32hxW1/en/availability/undefined.json"

### Technical details

-Chrome 105.0.5195.125 and Safari 15.5

**Screenshots**
<img width="817" alt="Screen Shot 2022-09-26 at 3 10 41 PM" src="https://user-images.githubusercontent.com/51497445/192361801-5da52638-832e-4be8-8935-a7659b931976.png">
<img width="1432" alt="Screen Shot 2022-09-26 at 3 10 51 PM" src="https://user-images.githubusercontent.com/51497445/192361805-e2b84ccf-b239-4a0a-a189-dc3812d03654.png">
<img width="1437" alt="Screen Shot 2022-09-26 at 3 13 46 PM" src="https://user-images.githubusercontent.com/51497445/192361809-de3ed8d7-fb93-4e35-bed0-bd447a485d22.png">

**Comment by jjromary** [comment]
@Kfelts  You selected availability before click in "edit availability" ?

**Comment by Kfelts** [comment]
> 

So, I attached this screenshot to better show which selection is leading to the 404. In the lower right-hand corner, It's based on the individual calendar itself, not the default availability.

<img width="1397" alt="Screen Shot 2022-09-26 at 8 08 40 PM" src="https://user-images.githubusercontent.com/51497445/192402470-5c5e987b-16bf-4ad4-9213-b40aab2fe9a3.png">

**Comment by KlingerMatheus** [comment]
same as #4608

**Comment by PeerRich** [comment]
can you try the latest version? we fixed a lot
