### ISSUE TITLE
how to close the iframe only by clicking on the X button

### ISSUE THREAD

**Issue by TikoAbelyan** [calcom/cal.com#4717]
HI all.
Please help me how to do that issue

**Comment by Udit-takkar** [comment]
@TikoAbelyan  can you explain a bit more ? what iframe are you talking about ? and attach any screenshot/video.

**Comment by Udit-takkar** [comment]
so you don't want to close the popup when clicked outside ? and only by X button.

**Comment by TikoAbelyan** [comment]
yup

**Comment by PeerRich** [comment]
that is not intended right now and also not planned to be changed
