### ISSUE TITLE
Cannot navigate away from team creation page in desktop app

### ISSUE THREAD

**Issue by peterferguson** [calcom/cal.com#4718]
### Issue Summary

On the mac app I navigated to create a team but cannot navigate away

### Steps to Reproduce

1. Went to `Settings`
2. Clicked on `Add a team`
3. Cannot navigate away. Must quit the app to go back

![image](https://user-images.githubusercontent.com/7002211/192514586-0a4da8f4-5cbc-4867-b494-adaf490ff25e.png)

**Comment by KlingerMatheus** [comment]
same as #4523

**Comment by PeerRich** [comment]
ah thank you, will work on this

**Comment by PeerRich** [comment]
fixed.🙏 will go live soon
