### ISSUE TITLE
Skeleton loader for workflows in event-type settings

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#4720]
### Issue Summary

Add skeleton loader for workflows in event-type settings.

<img width="1230" alt="Screenshot 2022-09-27 at 15 21 00" src="https://user-images.githubusercontent.com/30310907/192537757-6a57005e-e7d6-498b-ac06-d1eb61afe13c.png">

**Comment by MuriloAmarals** [comment]
Hey @CarinaWolli how can I activate the workflows on my localhost?

**Comment by MatheusBeniniF** [comment]
hey @CarinaWolli, what is the expect behavior?

**Comment by CarinaWolli** [comment]
Hi @MatheusBeniniF, I already started working on this. We are trying to get rid of the loaders you see in the screenshot above and use skeleton loaders instead
