### ISSUE TITLE
Password reset on account settings still has placeholder

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4723]
<img width="819" alt="Bildschirm­foto 2022-09-27 um 22 29 03" src="https://user-images.githubusercontent.com/88643432/192629806-f2a7c0ab-0e81-478a-b543-1cc5aaecb21f.png">

**Comment by okellogabrielinnocent** [comment]
@PeerRich, what would be the desired functionality here is it to remove the oldPassword_placeholder
