### ISSUE TITLE
Add original link zoom in mail reminder with a dynamic text variable

### ISSUE THREAD

**Issue by Sidonie82** [calcom/cal.com#4733]
### Is your proposal related to a problem?

Can't send original zoom link automatically in mail reminder as in calendly

### Describe the solution you'd like

Add a dynamic text variable to add automaticaly the zoom link created alone the first time appointment is taken

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

Thank you

**Comment by milospuac** [comment]
Thanks for the suggestion. Our engineers will look into this

**Comment by CarinaWolli** [comment]
Duplicate of #5421
