### ISSUE TITLE
Payment Page has old UI

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4752]
<img width="961" alt="Screenshot 2022-09-29 at 11 52 40 AM" src="https://user-images.githubusercontent.com/1780212/192954561-289d7259-84cc-44b7-bbed-5f7a75d8c0eb.png">

**Comment by matheusmuniz03** [comment]
how can I get to this page?

**Comment by hariombalhara** [comment]
This is payment/[uid].tsx

**Comment by hariombalhara** [comment]
Actually you can directly visit the page with any uid and modify the component code to fake the response it needs to render the page. THat is the easiest approach, otherwise you would need to setup stripe.

**Comment by matheusmuniz03** [comment]
@hariombalhara @Jaibles Do we have a design for this? Figma?

**Comment by PeerRich** [comment]
i think only the button is wrong?
