### ISSUE TITLE
Timzone Offset due to Daylight Time Saving change

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#4753]
### Issue Summary

https://user-images.githubusercontent.com/2770597/192957428-cb6996b0-8d49-4ab3-b98e-a1aba7e701d3.mov

### Steps to Reproduce

1. Availability is set to tuesday, 13-14h 
2. Event date range is set from 18.10.2022 to 31.01.2023
3. Timzone used everywhere: GMT+2:00 Berlin

### Technical details

- Browser version: Firefox 105.0.1
- Node.js version: v16.17.1
- cal.com selfhosted: v2.0.2
- calendar: CalDAV server radicale v3.1.8

**Comment by gGh00sTt** [comment]
I was able to reproduce it

**Comment by PeerRich** [comment]
cc @alishaz-polymath and @emrysal

**Comment by alishaz-polymath** [comment]
Is it the Daylight saving time acting up again @emrysal ?

**Comment by alishaz-polymath** [comment]
I can confirm it isn't related to CalDAV alone, so it is most likely the Daylight saving time related issue

**Comment by PeerRich** [comment]
i believe DST was fixed
