### ISSUE TITLE
 error - Cannot read  properties of null (reading '1')   

### ISSUE THREAD

**Issue by saifullah-N** [calcom/cal.com#4765]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

changed DATABASE_URL and given values to CALENDSO_ENCRYPTION_KEY ,NEXTAUTH_SECRET
done migrations
yarn dev

while running the project it shows
@calcom/web:dev: warn - axiom: Envvars not detected. If this is production please see https://github.com/axiomhq/next-axiom for help
@calcom/web:dev: warn - axiom: Sending Web Vitals to /dev/null
@calcom/web:dev: warn - axiom: Sending logs to console
@calcom/web:dev: info  - automatically enabled Fast Refresh for 1 custom loader
@calcom/web:dev: error - Cannot read properties of null (reading '1')
@calcom/web:dev: wait  - compiling...
@calcom/web:dev: error - Cannot read properties of null (reading '1')

![err](https://user-images.githubusercontent.com/79261602/193068863-225ee77b-37e2-4dad-81cc-b38ccedeaf76.png)

###THANKS IN ADVANCE

**Comment by CarinaWolli** [comment]
@saifullah-N Are you working on a windows system? If yes, this might be the same issue as discussed here: [Discussion](https://github.com/calcom/cal.com/discussions/4053)

If that is the case, @alishaz-polymath is currently working on that, and here is a temporary solution for it: [Comment](https://github.com/calcom/cal.com/discussions/4053#discussioncomment-3566212)
