### ISSUE TITLE
Spelling Mistake on german booking success page

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#4780]
on german booking success page spelling mistake = ~~gebuhct~~ should be gebucht
<img width="1439" alt="Bildschirm­foto 2022-10-01 um 00 50 35" src="https://user-images.githubusercontent.com/88643432/193366647-8cc9d359-60c2-4b4c-b12b-7de4413d5189.png">

**Comment by CarinaWolli** [comment]
Already fixed on latest main

<img width="662" alt="Screenshot 2022-10-03 at 09 50 26" src="https://user-images.githubusercontent.com/30310907/193526557-8cad3c1d-a8d9-4354-be02-67ab19bca890.png">
