### ISSUE TITLE
Enable Sales, Research and other teams using Cal.com to send Gift Cards/other perks to meeting participants

### ISSUE THREAD

**Issue by uchibeke** [calcom/cal.com#4782]
## Is your proposal related to a problem?

For Sales, Research and UI/UX teams, providing incentives for participants is key to increasing engagement.

Some teams manually send out Gift cards or others perks from third party platforms even when they use cal.com for meeting scheduling

There should be a way to send perks/initiate the sending of perks like Gift card or Crypto from within the cal.com dashboard

## Describe the solution you'd like

_This is a proposal and I'd like feedback before I or anyone else goes ahead to implement it. Please, be gentle 😄_

The solution is to build a Cal.com app that integrates [Chimoney's API ](https://chimoney.readme.io/reference/post_v0-2-payouts-chimoney)to enable 1-click sending of Gift Cards, Crypto, Mobile Money or Bank transfer to the email of a participant, all participants or select participants of a meeting

Using the app, withing the cal.com dashboard, the account owner/organizer of the meeting can initiate the Gift sending from and the recipient (Survey participant, Sales call participant, etc) gets an email in the email they joined the meeting with

### 1) Email notification

[<img width="1400" alt="Screen Shot 2022-09-30 at 7 46 11 PM" src="https://user-images.githubusercontent.com/5677552/193369957-1cbed44c-1186-4493-9678-eded593dc39c.png"> ](https://chimoney.io/chipay)

### 2) Recipient picks from a list of Gift Cards or other options

[<img width="1792" alt="Screen Shot 2022-09-30 at 7 48 24 PM" src="https://user-images.githubusercontent.com/5677552/193370087-9ac406bf-3880-4164-a538-5cbd397df02e.png">](https://dash.chimoney.io/redeem)

This simplifies reward payouts + gives the recipient of the gift options to pick from regardless of what country they're based in

## Describe alternatives you've considered

The alternatives are that Sales, Research, and other teams that use cal.com will need to copy the emails of participants manually to other platforms for sending the Gift to them. This is slow and breaks their workflow or does not encourage stickiness of cal.com

## Additional context

Open to feedback and suggestions, please 🙏🏾

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will consider adding this for one of our next versions.

**Comment by PeerRich** [comment]
i dont think this is a priority right now, if at all, it'll be an app in the app store -- but not build by the core team

**Comment by uchibeke** [comment]
Hi, @PeerRich great idea! Yes, it's better as an App and @chimoney is happy to work on it and open a PR.

I know that having an easy way to reward participants is a huge need for Sales and Research calls. But I am curious if the number of people that use cal.com for Sales and Research Interviews is large

**Comment by PeerRich** [comment]
closing due to staleness
