### ISSUE TITLE
Able to add a post even trigger in Workflow

### ISSUE THREAD

**Issue by JOduMonT** [calcom/cal.com#4785]
I simply love Cal
and even more with the free workflow and the n8n integration and ...
in any case
I think it would be wonderful to being able to directly in the workflow to add after even action
such as simply as a thank you note for showing up, to proposing another meeting or a appreciation survey

**Comment by CarinaWolli** [comment]
Hi @JOduMonT, I am currently working on a new workflow trigger that triggers after a meeting ended (#3708). This would allow you to send thank you notes or any other customized emails/SMS. Does that solve your issue?
