### ISSUE TITLE
INVALID_URL error

### ISSUE THREAD

**Issue by Mindbowser** [calcom/cal.com#4796]
### Issue Summary

We have setup cal.com on our own ec2 server along with APIs codebase. APIs seems to be accessible and running on port 3002. But when we try to access it using postman it is throwing below error

> TypeError [ERR_INVALID_URL]: Invalid URL\n    at new NodeError (node:internal/errors:387:5)\n    at URL.onParseError (node:internal/url:564:9)\n    at new URL (node:internal/url:640:5)\n    at eval (webpack-internal:///(api)/../../packages/lib/constants.ts:35:17)\n    at Object.(api)/../../packages/lib/constants.ts (/usr/startupos-cal.com-9eafe1154e10/apps/api/.next/server/pages/api/attendees.js:622:1)\n    at __webpack_require__ (/usr/startupos-cal.com-9eafe1154e10/apps/api/.next/server/webpack-api-runtime.js:33:42)\n    at eval (webpack-internal:///(api)/./lib/helpers/customPrisma.ts:10:79)\n    at Object.(api)/./lib/helpers/customPrisma.ts (/usr/startupos-cal.com-9eafe1154e10/apps/api/.next/server/pages/api/attendees.js:492:1)\n    at __webpack_require__ (/usr/startupos-cal.com-9eafe1154e10/apps/api/.next/server/webpack-api-runtime.js:33:42)\n    at eval (webpack-internal:///(api)/./lib/helpers/withMiddleware.ts:10:71)

### Steps to Reproduce

1. Using postman call http://IP-ADDRESS:3002/v1/attendees

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
We used random API key as we are not able to generate APi key from webapp due to enterprise license issue, this we did just to check APIs are working or not, we thought because of wrong API key we should have got some different error and that also in JSOn format but we got HTML response and its error details pasted above. So not sure what is the issue. Is this error related to license we have? Will it go if we buy the license?

**Comment by milospuac** [comment]
Hi there

Thanks for reaching out. 

Our team will look into this

**Comment by emrysal** [comment]
Hi @Mindbowser - I think we've nailed this now 👍 (Had a look yesterday in Slack since this ticket was opened)
