### ISSUE TITLE
[CAL-166] Improve the App uninstallation cleanup per event by keeping a relation of EventType to App.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4799]
Improve this uninstallation cleanup per event by keeping a relation of EventType to App, instead of keeping data in metadata.

<img width="1284" alt="Screenshot 2022-10-03 at 5 13 12 PM" src="[https://user-images.githubusercontent.com/1780212/193568940-3a494b1e-8a1f-470b-a96a-7c84402318be.png](https://user-images.githubusercontent.com/1780212/193568940-3a494b1e-8a1f-470b-a96a-7c84402318be.png)">

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@hariombalhara has this been fixed?

**Comment by hariombalhara** [comment]
Not yet.
