### ISSUE TITLE
[CAL-178] Phone number from SMS notifications workflow not available

### ISSUE THREAD

**Issue by MistrFana** [calcom/cal.com#4813]
### Is your proposal related to a problem?

I have created a workflow with SMS notifications. I love it! But I don't have the attendee's phone number available. Is there any chance to get it? I don't want to have two "phone number" inputs in the booking form.

### Describe the solution you'd like

I would love to have new variable available with given phone number to be able to use it in Workflows and also have it available in the Reservation detail and in all transaction email.

### Describe alternatives you've considered

Have two phone number inputs in the booking form. One from the workflow and one extra number field.

### Additional context

Thanks in advance

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by milospuac** [comment]
Hi there. Thanks for reaching out. Our engineering team might implement this in one of our next versions. 

Best,

**Comment by PeerRich** [comment]
@CarinaWolli could look into this

**Comment by CarinaWolli** [comment]
@MistrFana Do you mean to have the phone number as a dynamic text variable for a custom workflow template? 

So to add it here: 
<img width="508" alt="Screenshot 2022-10-07 at 18 14 50" src="https://user-images.githubusercontent.com/30310907/194600008-d3f07297-6bc9-4bbb-a00d-7ec2609c2c01.png">

Or what exactly do you mean by _I would love to have new variable available with given phone number to be able to use it in Workflows_

**Comment by WispOfTheWinds** [comment]
I'm going to piggyback off of this -- it seems I have the same, or at least a very similar issue.

Using an SMS reminder workflow doesn't attach the phone number to the event like an Additional Input would. There's currently no way for the host to see the attendees phone number if it's collected this way.

Attaching the SMS reminder number in the event details would be fantastic!

**Comment by CarinaWolli** [comment]
@WispOfTheWinds Yes makes sense. I will add the SMS reminder number to the booking details
