### ISSUE TITLE
show dialog to change timezone when moving timezones

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4817]
like todoist:

<img width="641" alt="CleanShot 2022-10-04 at 10 12 14@2x" src="https://user-images.githubusercontent.com/8019099/193781771-3eaf649e-e3f2-424e-ba3f-47a59eff328f.png">

**Comment by MatheusBeniniF** [comment]
Hey @PeerRich, where do you want the "View my settings" button to go?
