### ISSUE TITLE
[CAL-124] Improve loading time for Embed

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#4820]
The target is to reduce the amount of time the loader shows for.

- Generate embed specific pages on the fly which would allow Embed UI to be rendered from backend itself. This should allow us to remove the loader completely from the parent and never hide the content in iframe.

**Comment by zomars** [comment]
> [user]/[type] to [user]/[...type] to allow a page like /user/30min/embed to work.

Why do we need this again?

**Comment by hariombalhara** [comment]
To allow embed pages(which are the same like non embed pages with a few styling changes done using useEmbed hook detection) to be statically generated.

**Comment by zomars** [comment]
@hariombalhara I mean, why do we need to use the `[user]/[...type]` approach instead of `[user]/[type]/embed`

**Comment by hariombalhara** [comment]
That's because an embed is just UI changes over the already working booking links. Embed should obviously get all the updates that happen in booking pages automatically.

If I create a separate route like [user]/[type]/embed, I would need to be able to share everything from /[user]/[type] with it.

**Comment by zomars** [comment]
You can just re-export the same page and inside the code check if you're one or another

**Comment by hariombalhara** [comment]
<img width="1003" alt="Screenshot 2022-10-11 at 5 16 51 PM" src="https://user-images.githubusercontent.com/1780212/195081591-f1b81729-8267-4473-b918-2fa33b0208a8.png">
Tried the re-export approach, though earlier I was thinking there would be a lot of glue code, it seems clean and DRY.
Thanks @zomars

**Comment by zomars** [comment]
I think we should strive to make all routes as portable as possible regardless of usage. But I think I'll delegate this decision to you since you're the most hand-on on this issue. 🙏🏽
