### ISSUE TITLE
When added as a guest on a calcom booking page, the event is not showing up by default in the guests calendar

### ISSUE THREAD

**Issue by serglo** [calcom/cal.com#4822]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When added as a guest on a calcom booking page, the event is not showing up by default in the calendar. 

Calendar: Google Calendar (via G Suite)

### Steps to Reproduce

1. Booking page
2. Add guests
3. Guests get calcom email, but it is not showing up in the calendar unless they actively add it -> leads to missing calls.

### Technical details

- gCal

**Comment by Ambesh69** [comment]
Not only when you add guests. Even when someone schedules a call from my cal link, none of us are receiving the meeting room link. It just shows 'Huddle01 video' *attaching a file below*

![Screenshot_20221006-103842__01](https://user-images.githubusercontent.com/67411052/194219887-24066bed-d1dd-4fe0-931d-3d9b7ce53959.jpg)

**Comment by milospuac** [comment]
Thanks for reaching out and reporting this. Our team will address this

**Comment by PeerRich** [comment]
i believe some of this was partly fixed
