### ISSUE TITLE
Dynamic Booking Link sends email with "Nameless" as title

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4832]
<img width="578" alt="CleanShot 2022-10-04 at 16 38 00@2x" src="https://user-images.githubusercontent.com/8019099/193864239-ffe71470-9844-4840-8ecf-ad841ac3d080.png">

**Comment by PeerRich** [comment]
is this still a thing? @Udit-takkar can you test this? cal.com/peer+bailey

**Comment by Udit-takkar** [comment]
<img width="589" alt="Screenshot 2023-07-19 at 7 32 44 PM" src="https://github.com/calcom/cal.com/assets/53316345/01f10e97-ff49-4bb8-90ef-eb8d07ee4593">

no "nameless" in the title

**Comment by alishaz-polymath** [comment]
No longer an issue!
