### ISSUE TITLE
Allow default country code for SMS number

### ISSUE THREAD

**Issue by cseeger** [calcom/cal.com#4838]
### Is your proposal related to a problem?

Allowing for a default country code setting would alleviate confusion for users where 99% are from a single country. 

### Describe the solution you'd like

Allow a config option to default to a specific country code for SMS.

### Describe alternatives you've considered

Was unable to find a setting in admin or a `data-cal-config` option.

**Comment by PeerRich** [comment]
can you show a screenshot where this would need to be implemented?

**Comment by cseeger** [comment]
<img width="367" alt="Screen Shot 2022-10-06 at 3 55 53 PM" src="https://user-images.githubusercontent.com/90306/194433415-acb755e6-eed8-4595-9747-fedb4e1600a0.png">

Above is the default prompt, where I assume the user is to select their country. However, this is not obvious in our opinion. 

<img width="363" alt="Screen Shot 2022-10-06 at 3 56 46 PM" src="https://user-images.githubusercontent.com/90306/194433519-1bb32b81-82be-475a-8458-4f2c35166317.png">

Here's an example where the US area code for San Francisco has been used with the following number: `415-867-5309`. The user intent here is certainly not to select the Swiss country code.

<img width="367" alt="Screen Shot 2022-10-06 at 3 57 13 PM" src="https://user-images.githubusercontent.com/90306/194433587-d3897107-494f-47d6-b495-f848af0ac030.png">

Here's an example where the US area code for Manhattan has been used with the following number: `212-867-5309`. Notice here, the default prompt remains. 

An ideal solution, for us, would be to set a config parameter whereby we could default to a given country.

Thanks for your time.

**Comment by PeerRich** [comment]
oh i see. can you not add a "1" to it?

**Comment by PeerRich** [comment]
i believe this is behaviour by the library that we're using. its probably better to raise an issue there. will investigate

**Comment by cseeger** [comment]
Interesting, perhaps there's already a mechanism for this type of configuration. 

All said, we're convinced that our customer base is largely within the US, and it's our opinion that many folks in the US **rarely** use country codes. Hence, the source of confusion. 

Appreciate your help with this.

**Comment by PeerRich** [comment]
i see that makes sense. 

https://www.npmjs.com/package/react-phone-number-input

it seems like there is a setting to ignore country codes, not sure how it works tho

**Comment by PeerRich** [comment]
I think a better option would be to guess the local phone number as a default. maybe with vercel middleware?

**Comment by cseeger** [comment]
I could see where that would work, but it would be nice to simply disable country codes, at least in my case.

Thanks for the response.

**Comment by PeerRich** [comment]
@Udit-takkar you were looking into this right?

**Comment by Udit-takkar** [comment]
@PeerRich yeah i am free now. will finish this by tomorrow

**Comment by cseeger** [comment]
Awesome -- thanks!

**Comment by John-H-Smith** [comment]
As this issue is closed - what is the final solution on that?
Currently, I am using the "Phone number" location. It always defaults to the us flag, even if my system and browser language are another than english. Is there a way to preselect that country flag to one of my choice?

**Comment by Udit-takkar** [comment]
@John-H-Smith we only support international numbers in the phone type input. so you can enter this number 415-867-5309.

<img width="418" alt="Screenshot 2023-10-30 at 6 34 40 PM" src="https://github.com/calcom/cal.com/assets/53316345/a047041f-f72d-4f99-958b-02844f0158eb">

if you want to preselect the country flag for smsReminder Phone input you can just add a param smsReminderNumber

For eg:- http://localhost:3000/pro/zoom?smsReminderNumber=+91

**Comment by John-H-Smith** [comment]
> @John-H-Smith we only support international numbers in the phone type input. so you can enter this number 415-867-5309.
> 
> <img width="418" alt="Screenshot 2023-10-30 at 6 34 40 PM" src="https://github.com/calcom/cal.com/assets/53316345/a047041f-f72d-4f99-958b-02844f0158eb">
> 
> if you want to preselect the country flag for smsReminder Phone input you can just add a param smsReminderNumber
> 
> For eg:- http://localhost:3000/pro/zoom?smsReminderNumber=+91
> 
> 
> 

Alright, thanks! How do I find out which parameters I can use?

**Comment by Udit-takkar** [comment]
@John-H-Smith for booking question you can use identifier as parameter name
