### ISSUE TITLE
Cal.com doesn't create a meeting in HubSpot

### ISSUE THREAD

**Issue by alefattorini** [calcom/cal.com#4845]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I installed the hubspot app, the sync is correctly and I see cal.com in the hubspot page
I have created some meetings but I didn't find meetings or any entry in the hubspot contact page.
What miss?

### Steps to Reproduce

1. install hubspot app
2. check if the contact exists among the hubspot contacts
3. organize a new meeting with the contact
4. no entry or info in the contact page

I'd like to see a new entry meeting/note in the contact page

**Comment by PeerRich** [comment]
@leog can you look into this?

**Comment by leog** [comment]
@PeerRich of course

@alefattorini thanks for reporting this.

There is a known behavior in which case HubSpot would get meetings and that is when you have other calendars installed. Our system does the meeting creation in just the calendar as it prioritize external calendars. Do you have an external calendar installed?

**Comment by alefattorini** [comment]
I didn't install any external calendar on hubspot

**Comment by leog** [comment]
> I didn't install any external calendar on hubspot

I meant external calendars installed within Cal. Like Google Calendar or CalDAV. If you have one, then HubSpot will not get the meetings as they go through that other external Calendar.
