### ISSUE TITLE
12/24h time format on booking page not updating according to settings page when app runs on different (sub)domain

### ISSUE THREAD

**Issue by JeroenReumkens** [calcom/cal.com#4851]
### Issue Summary

In #4771 we did a fix to ensure that your 12/24 time formats where honoured on the bookings page. The solution however is **not** working on cal.com. The reason is the settings page lives on `app.cal.com` and the public booking page on `cal.com/....`. Because of that the localstorage set on the settings page will be set on the subdomain and won't be updated on the root domain. 

### Steps to Reproduce

1. Update your 12/24h time format on https://app.cal.com/settings/my-account/general
2. Go to a public bookings page
3. Conclude that the 12/24h format isn't honoured
4. If you're more technical: Note that the localstorage item `timeOption.is24hClock` isn't updated either.

**Comment by Toledodev** [comment]
Hey @PeerRich @JeroenReumkens How we can test this? I'm trying to solve the problem but how can I check?
I'm thinking in something like this in /apps/web/pages/v2/settings/my-account/general.tsx
![Screenshot_2](https://user-images.githubusercontent.com/87545086/194137886-29ced0a7-6ce1-472e-854d-c006d0ce6f9e.png)

**Comment by PeerRich** [comment]
this is a different problem. the settings page was never meant to change the booking page.

the booking page should use the user agent
