### ISSUE TITLE
waiting list on session

### ISSUE THREAD

**Issue by fitmesas** [calcom/cal.com#4870]
### Is your proposal related to a problem?

 When I use the planning I organize session (1 hour) for a limit number of people. But for people arriving too late, it could be awesome to have a waiting list in case of delete seat from the first booking.

(Write your answer here.)

### Describe the solution you'd like

 Here is my use case : in a Crossfit box, a session is 1 hour for 12 seats. For the 12 first people is fine. But for people arriving after, is already full. Everytime, some people from the 12 first seats delete. So the fist user on waiting list can take the available seat, etc. So we could fix for example 10 more seats on waiting list and notice them that they take a seat. 

(Describe your proposed solution here.)

### Describe alternatives you've considered

 example with this app: https://resawod.com/en/functionalities/  or this one https://www.deciplus.fr/application-mobile-reservation?hsCtaTracking=66a68e07-87a4-488a-a158-4308c80328de%7Cf16af9a9-6e14-409d-8d5b-9086b4480ae4 

(Write your answer here.)

### Additional context

 My goal is to make a nocode app (with Glide) and embed Cal.com with this new feature to manage session booking and waiting list. 

(Write your answer here.)

**Comment by milospuac** [comment]
Thanks for the suggestion @fitmesas

**Comment by PeerRich** [comment]
not sure if we will do this anytime soon, sorry!
