### ISSUE TITLE
Event type availability does not respect 12h/24h account setting.

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#4885]
On an account with 12-hour time format display

<img width="352" alt="image" src="https://user-images.githubusercontent.com/1046695/194373701-83c87be8-3719-4c9f-8953-8ef4c06f1ed0.png">

**Comment by MuriloAmarals** [comment]
Hey @emrysal on my localhost this bug is not happening.
https://www.loom.com/share/77409357642e4ceca7e457b0cfb48f01

**Comment by Udit-takkar** [comment]
Not able to reproduce this. It is working fine for me.
