### ISSUE TITLE
Wrong focus ring on Help Dropdown

### ISSUE THREAD

**Issue by MuriloAmarals** [calcom/cal.com#4889]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Wrong CSS on Dropdown of User in Help Item.

https://www.loom.com/share/89cfb0b84c1b487c95040ce02b9f7b44

**Comment by milospuac** [comment]
Hey Murilo, thanks for reaching out. Our team will address this

**Comment by MuriloAmarals** [comment]
Hey @milospuac , I'm working on this problem here and I'm thinking that the best way to solve this bug is removing the ring of `DropdownMenuContent`. Also because the Event Types Dropdown does not have `this focus:ring`. What do you think?

**Comment by MuriloAmarals** [comment]
> Hey @milospuac , I'm working on this problem here and I'm thinking that the best way to solve this bug is removing the ring of `DropdownMenuContent`. Also because the Event Types Dropdown does not have `this focus:ring`. What do you think?

I thought it was better to leave it without to maintain a default in the site's Dropdowns. 👍

**Comment by MuriloAmarals** [comment]
Hey @milospuac @PeerRich I managed to put `focus-ring` in Help without it losing its functionality. What did you think?

https://www.loom.com/share/8b157165b9904326b5bb19b6e47fc8fb

**Comment by PeerRich** [comment]
@MuriloAmarals

awesome! please open a PR, will review🙏
