### ISSUE TITLE
[CAL-37] linear snyc #2

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4891]
what if this has an image?

or a list?

* lets go
* hell yea

1. lets go
2. to the moon

![1.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1aaa0448-4023-4a7e-8edd-6a95352db72d/03bf5ac2-e6e8-4236-83c4-08c62d32f998)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
sheeesh

**Comment by PeerRich** [comment]
does this work?

> From peer@cal.com on Linear

**Comment by sean-brydon** [comment]
Test test test

**Comment by PeerRich** [comment]
hmm

> From peer@cal.com on Linear
