### ISSUE TITLE
'Cancel all remaining' button needs design

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#4894]
### Issue Summary

<img width="1223" alt="Screenshot 2022-10-07 at 10 04 37" src="https://user-images.githubusercontent.com/30310907/194504388-407bdb9e-ca8f-404b-93b7-f1d2ac438b02.png">

If the button has enough space, the text should fit in one line. Otherwise, it should at least have the right padding on top and bottom.

**Comment by matheusmuniz03** [comment]
Hey @CarinaWolli, this issue has already been resolved in [this](https://github.com/calcom/cal.com/issues/4850).
![Captura de tela de 2022-10-07 06-38-51](https://user-images.githubusercontent.com/87545749/194524359-a2eb4c31-d46a-41a0-9f0c-7a3dc76c3131.png)

**Comment by CarinaWolli** [comment]
Thank you @matheusmuniz03 for pointing that out 🙏
