### ISSUE TITLE
Re-organise Event Type Settings

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#4896]
A lot of things are just getting added to advanced settings when they don't fit into any of the other categories. 

Create some more specific categories and move things about this page. 

OR

Come up with a better way to display toggles that don't fit into specific parts of the settings

**Comment by PeerRich** [comment]
i'm voting to add a new category: "Guests" and move

- Disable Guests
- Offer Seats
- (soon): Also invite ... (which @emrysal is working on)

into that section

___


also

<img width="891" alt="CleanShot 2022-10-07 at 11 20 31@2x" src="https://user-images.githubusercontent.com/8019099/194531900-2c244cba-1b8d-4361-ad3c-e96289e4974e.png">

should be in event setup not additional settings

**Comment by sean-brydon** [comment]
Created a Figma mockup of this @PeerRich  https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=20334%3A167573 

@Jaibles please correct If anything is wrong :)
