### ISSUE TITLE
/event-types/requirements

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4905]
- [ ] add new tab
- [ ] move "Require confirmation" in here
- [ ] new: require password
- [ ] new: require account
- [ ] later: require geo-location

we can extend the `<Gate>` component

<img width="1017" alt="CleanShot 2022-10-07 at 13 10 41@2x" src="https://user-images.githubusercontent.com/8019099/194550397-57e6d098-c51f-4a5c-8f1d-5926e7813bea.png">

**Comment by omshakti3159** [comment]
@PeerRich can you assign this to me, I want to work on this feature.

**Comment by PeerRich** [comment]
we will have to revisit this later once the new booking page is merged
