### ISSUE TITLE
/event-types: be able to hide additional notes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4915]
Also is there a way to remove additional notes?

[Slack Message](https://calendso.slack.com/archives/C01NXDSRY9W/p1665165353348449?thread_ts=1665165353.348449&cid=C01NXDSRY9W)

**Comment by aasargsian** [comment]
Seems like there is no way to do that now. 
We are actually would like to be able to remove Additional notes input too. 
We are gathering a lot of other information on the booking stage and an extra input of Additional notes might decrease the conversion

**Comment by emrysal** [comment]
@aasargsian Closing this in favour of https://github.com/calcom/cal.com/issues/5536#issuecomment-1331121117 which this precedes but with less context.
