### ISSUE TITLE
Optionally make time zone a required entry field (and display local times)

### ISSUE THREAD

**Issue by TjrGithub** [calcom/cal.com#4930]
### Is your proposal related to a problem?

I am dealing with recruiters based in a different time zone. It has happened several times they call an hour off: They seem to think the displayed time is in their local time. But cal.com seems to show my availability in my time zone. Second cause, many recruiters mentally correct for the time zone offset and never check whether it's already corrected for. 

### Describe the solution you'd like

I would like for cal.com to show my availability in the viewers' time zone. And I would like an option to make the user select a time zone - to deal with recruiters who mentally overcorrect the time zone.

Please display the time zone right next to the time so they are one unit visually.

Maybe add a map that shades the countries of the selected time zone.  The user should be able to spot the error without reading stuff.

### Describe alternatives you've considered

Things that don't work:
* Doodle - I get a mix of correct and overcorrected time zone replies
* Telling people to mind the time zone, and putting it into the heading.

**Comment by milospuac** [comment]
Hi there 

Thanks for reaching out

Cal.com is always fetching the browser locale, so if for example, I end up on your booking page, it will automatically show your slots in MY time zone. Not yours. Of course, you will see your slots in your own time zone. 

Also, there is a time zone dropdown on each booking page so if the viewer wants to see your slots in a time zone different from the one they are located in, they can do that. 

Let me know if we are on the same page here.

**Comment by TjrGithub** [comment]
I know it can be done. The point is making it in-your-face. Recruiters are busy and run on autopilot, so errors happen with anything that isn't part of the main workflow.

**Comment by PeerRich** [comment]
@TjrGithub can you provide a figma mockup or something similar how you'd want it?

**Comment by TjrGithub** [comment]
@PeerRich  rather than make you wait for a perfect graphic, here is my idea in words:

After you click on a date, the various available times open as buttons on the right hand side. Currently, they are labeled with the time only, e.g. **"12:45"**. I suggest to label it with **"13:45        (TjrGithub's time: 12:45)"*** instead. The owner's-time part maybe could  be inside the button, in smaller font, and separated with ~4 spaces from the "main" time.

I'm suggesting concrete time stamps for explicit people, to lower the cognitive load and because errors in both directions.
