### ISSUE TITLE
[CAL-53] More flexible workflow templates

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#4944]
We want to allow the user to edit our predefined workflow templates. When a user chooses a template we prefill the text fields with our predefined text. The user can then make any changes to the templates.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Jaibles** [comment]
@CarinaWolli might be better to task this under just allowing a user to create their own templates themselves and not connect it with the ones we've created?
 https://github.com/calcom/cal.com/issues/6435
