### ISSUE TITLE
Name under Availability in Event types doesn't change as per the Availability Name

### ISSUE THREAD

**Issue by gGh00sTt** [calcom/cal.com#4946]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Name under Availability in Event types doesn't change as per the Availability Name and remains "Working Hours" even though the availability name has changed. 
Don't think this necessarily as bug but maybe for better user experience 

### Steps to Reproduce

1. Create a new Availability with name other than Working Hours
2. Set the new Availability as default
3. Create a new Event

Video : https://www.loom.com/share/b0e568a442e94720924ca384691220d4

**Comment by milospuac** [comment]
Hi there

I think that is just a description/suggestion and not necessarily a name of your past availability, the same way how under _Limits_ there is _How often you can be booked_

Best,
