### ISSUE TITLE
[CAL-54] SIU routing forms not saving

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4950]
[https://app.birdeatsbug.com/sessions/4QAk-rDvlDH5nGJO9DTXvUtB6Ka7WaYSoplDNrFA-Vic](https://app.birdeatsbug.com/sessions/4QAk-rDvlDH5nGJO9DTXvUtB6Ka7WaYSoplDNrFA-Vic)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by hariombalhara** [comment]
I am checking this. Super weird that I can't replicate it locally.
