### ISSUE TITLE
[CAL-56] cant confirm bookings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4957]
[https://twitter.com/oliverflueckige/status/1579865405589696512?s=46&t=pCOGF79ZkCUIdmklv3ZjUA](https://twitter.com/oliverflueckige/status/1579865405589696512?s=46&t=pCOGF79ZkCUIdmklv3ZjUA)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by milospuac** [comment]
@PeerRich Looking into it

**Comment by milospuac** [comment]
@PeerRich Reached out to him in Help Scout, will continue there. Looks like it's the issue with confirming meetings that have Zoom location

**Comment by PeerRich** [comment]
seems to be a zoom error
