### ISSUE TITLE
[CAL-63] cancel meeting still using v1 designs

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4964]
> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MatheusBeniniF** [comment]
Hey @PeerRich, can you give me more details?

**Comment by PeerRich** [comment]
> Hey @PeerRich, can you give me more details?

![image](https://user-images.githubusercontent.com/8019099/195458237-c317d6a2-e3c9-499d-bcaf-2f7b4d092a87.png)

this screen still old design

**Comment by MatheusBeniniF** [comment]
> > Hey @PeerRich, can you give me more details?
> 
> ![image](https://user-images.githubusercontent.com/8019099/195458237-c317d6a2-e3c9-499d-bcaf-2f7b4d092a87.png)
> 
> this screen still old design

Thanks, I will take a look on this.

**Comment by MatheusBeniniF** [comment]
@PeerRich, what is the new design do you want?

**Comment by PeerRich** [comment]
actually, we are getting rid of this page. opening a new ticket
