### ISSUE TITLE
DestinationCalendar.credentialId does not exist

### ISSUE THREAD

**Issue by Silur** [calcom/cal.com#4967]
When trying to set up a new user according to the readme, prism shows the following error:

```
Failed to commit changes: 
Invalid `prisma.user.create()` invocation:


  The column `DestinationCalendar.credentialId` does not exist in the current database.
```

Migrations successfully ran and checking the table in question is indeed missing this field

Running:
calcom-docker (freshly pulled and built images)

```bash
export DOCKER_BUILDKIT=1
docker compose up -d database
docker compose up --no-cache --pull -d calcom
docker compose up studio
# enter new User into studio
```

**Comment by milospuac** [comment]
Thanks for the report. Our team will investigate this

**Comment by PeerRich** [comment]
i think this was fixed
