### ISSUE TITLE
[CAL-82] /settings/teams/new: auto-add team URL when typing in team name

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4970]
![CleanShot 2022-10-12 at 12 41 38](https://user-images.githubusercontent.com/8019099/195333794-6368dce5-8766-4586-b050-f2ce37212bd1.gif)

same as in event-types:

https://user-images.githubusercontent.com/8019099/195334237-8ce50699-e742-41e6-a913-6ae281dfe0fe.mp4

**Comment by harshsinghatz** [comment]
Can I work on this??

**Comment by PeerRich** [comment]
> Can I work on this??

sure!

**Comment by Udit-takkar** [comment]
PR has been merged. Closing this
