### ISSUE TITLE
[CAL-126] onboarding: step 3 not mobile friendly

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4980]
![965E388F-BC66-4D45-B7EB-A1A520E8B1A6.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c82ec2c6-065e-4cc8-a38c-77e3bb368dde/1f4a0371-d138-4fe6-90c6-74483cd7c918)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by matheusmuniz03** [comment]
hey @PeerRich , do we have any designs in figma for this?

**Comment by matheusmuniz03** [comment]
hey @PeerRich @Jaibles any updates about figma?

**Comment by Jaibles** [comment]
I haven't done it yet but do have the availability page itself done on mobile so should give a good idea what to do. Will update designs also.

**Comment by MatheusBeniniF** [comment]
@Jaibles, so on mobile we need hidden copy buttons and show `Copy time to all`, right?

**Comment by Jaibles** [comment]
Looks great @MatheusBeniniF 👏

**Comment by MatheusBeniniF** [comment]
the same bug happens here, https://www.loom.com/share/7ad89fb8555d45c48028b6e25204bb82, you want to fix this in the same pr or create a new ticket for this?

**Comment by PeerRich** [comment]
> @Jaibles, @PeerRich what do you think of something like this? [loom.com/share/e353a0b4a650486c93c5c908e1f3486e](https://www.loom.com/share/e353a0b4a650486c93c5c908e1f3486e)

looks great, ship it!
