### ISSUE TITLE
[CAL-131] dynamic booking links: wrong avatar border

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#4983]
![CleanShot 2022-10-13 at 10.35.23@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c111ce35-e0c9-44d9-a87e-bc03942671fc/33259377-af57-4919-b428-e60c8130497e)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by matheusmuniz03** [comment]
@PeerRich do we know what the desired edge is? Is there this in figma?

**Comment by PeerRich** [comment]
yea the desired one is in the teams dark mode page: https://cal.com/team/cal

**Comment by matheusmuniz03** [comment]
Okay @PeerRich thanks! I will do that.

**Comment by PeerRich** [comment]
eventually we should merge the two layouts, there is no reason to have two separate ones @alishaz-polymath

**Comment by PeerRich** [comment]
fixed
