### ISSUE TITLE
[CAL-151] Update website copy from $174 to $185

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#4991]
![CleanShot 2022-10-13 at 18.25.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/43d105e0-6b52-4213-9f41-362810f66c6c/2fb80aa8-50fd-4965-a4d1-efdf485cd073)

Currently, the slider has the old $174 price that needs to be updated to $185: [https://cal.com/platform](https://cal.com/platform)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by shirazdole** [comment]
nice

**Comment by PeerRich** [comment]
done
