### ISSUE TITLE
/getting-started/setup-availability the table of days breaks depending on the language

### ISSUE THREAD

**Issue by matheusmuniz03** [calcom/cal.com#4993]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When we are configuring our account for the first time when opening the site, depending on the language that the user uses, the days table can break.

English Version: 
![Captura de tela de 2022-10-13 15-59-16](https://user-images.githubusercontent.com/87545749/195684049-9d221135-22bf-4249-873a-2512085e457b.png)

Portuguese Version:
![Captura de tela de 2022-10-13 15-38-54](https://user-images.githubusercontent.com/87545749/195683618-470d741f-6edd-47f2-9264-5392bb069b1b.png)

**Comment by matheusmuniz03** [comment]
I'm solving this issue and would like to know if you guys like this solution? @PeerRich @Jaibles 
![Captura de tela de 2022-10-13 16-11-14](https://user-images.githubusercontent.com/87545749/195688443-0ecf4a28-f492-4a7e-92f3-1353ebf63276.png)

**Comment by matheusmuniz03** [comment]
@PeerRich @Jaibles can you check this?

**Comment by PeerRich** [comment]
looks good, feel free to open a PR @matheusmuniz03
