### ISSUE TITLE
[CAL-153] Wrong redirect when clicking user or teams avatar in event types

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5002]
This is what we currently do: 

[https://www.loom.com/share/3cad7ca8ee4d4a06a8ef439e8eeedb7a](https://www.loom.com/share/3cad7ca8ee4d4a06a8ef439e8eeedb7a)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MatheusBeniniF** [comment]
hey @CarinaWolli, the expect behavior of redirect are going to `/settings/my-account/profile` when clicking user?

**Comment by CarinaWolli** [comment]
I would propose redirecting to: 
- `/settings/my-account/profile` for user avatar
- `settings/teams/<teamId>/profile` for a team's avatar

@Jaibles what do you think, should we implement it like that?

**Comment by PeerRich** [comment]
NIT: we should move teams out of settings, no? @Jaibles

**Comment by Jaibles** [comment]
Even if we move some parts of teams out, a team will always have settings that will live in the settings area in the same way an individual will. We pulled teams out into the sidebar as a temporary fix until we have a switcher.

**Comment by PeerRich** [comment]
makes sense. we can keep it for now there
