### ISSUE TITLE
Time Options not showing all the time

### ISSUE THREAD

**Issue by junaid33** [calcom/cal.com#5014]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Time options are not shown all the time. 24hr is being selected by default for all our users, but when users try to change it, the option is not there all the time. Please see attached screenshot.

### Steps to 

<img width="770" alt="CleanShot 2022-10-14 at 15 05 02@2x" src="https://user-images.githubusercontent.com/34615258/195932983-3533ea4f-d3c1-4a48-9970-c446567a048a.png">

### Technical details

Cal.com version v.2.0.5-sh-PRO

**Comment by PeerRich** [comment]
if you are logged in, this is hidden and used by your settings in your cal.com app

**Comment by junaid33** [comment]
Ah that makes sense
