### ISSUE TITLE
[CAL-159] event-types/availability not mobile friendly

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5024]
![5923A55C-2072-4416-BE78-7ABA67721F18.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/83de04d4-56ae-4abb-aeb8-45ad960f4dcb/1d83f463-11ee-414f-839a-ed457eb41d5e)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Udit-takkar** [comment]
should we make website to be responsive even for smaller screens like 320px ? @peer 

There are many ui bugs like this.

![Screenshot 2022-10-17 at 9.50.21 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f49694a6-9dab-4494-b9c6-7fc7aa97c3d9/782d5a4a-c40b-416b-96f1-f4c60eef79d1)

![Screenshot 2022-10-17 at 9.51.02 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/68c90402-a66c-4520-8eaf-e9a17ab82d0b/94ada4e9-e0ff-4b77-aae7-f2408a001cea)

[efaaa73c-a21d-4e85-ba1c-b55f159e50da](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/04d5498c-5821-433f-9fd8-a6ad21b500f2/efaaa73c-a21d-4e85-ba1c-b55f159e50da)

**Comment by PeerRich** [comment]
eventually, yea. it's tough tho at that screen size but definitely worth doing

**Comment by Udit-takkar** [comment]
ok will try to fix all responsive bugs.
