### ISSUE TITLE
Wrong css on teams and routing forms dropdown button

### ISSUE THREAD

**Issue by Toledodev** [calcom/cal.com#5027]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Dropdown item does not fill divs correctly

### Steps to Reproduce

1. Create a team
2. Go to /teams
3. Click on dropdown

or

 1. Go to apps/routing-forms/forms
 2. Create a form
 3. Click on dropdown

Loom video: 
https://www.loom.com/share/142bb0e8f45f4671a327a365615a9325
https://www.loom.com/share/a984bbf50c9f472ab5e868c7fa71c762

**Comment by Toledodev** [comment]
As I already made a similar issue I will take a look at it :)

**Comment by PeerRich** [comment]
fix afaik
