### ISSUE TITLE
[CAL-163] i18n with better defaults

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5041]
![CleanShot 2022-10-17 at 09.25.55@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4f34cf94-3180-46f7-9162-1770df20dfb4/44f0f67f-f50b-4d3d-8b2a-3e9cb5703820)

the crawler doesnt execute i18n when creating the social media page, is there a way to fall back to the English words as a default instead of showing app_store_description?

we can’t just remove the key_string and hardcode english strings because they are loaded dynamically

![CleanShot 2022-10-17 at 09.26.08@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7405bbc5-424d-4726-a4bf-8d8961432a3d/ec65bc91-4f29-4a5e-a58e-c78a8fdc4f7a)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Udit-takkar** [comment]
This has been fixed [https://github.com/calcom/cal.com/pull/5098](https://github.com/calcom/cal.com/pull/5098)
