### ISSUE TITLE
[CAL-169] Bookings page with no event types needs redesign

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5048]
If a user hides all their event types and sends a hidden 30-minute booking link, when a user presses the "back button" the page says "This user hasn't set up any event types yet."

I believe the solution here is to remove the back button when all event types are hidden. 

![CleanShot 2022-10-17 at 15.11.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/22d3bb4e-8fae-4ffd-9f91-93991fd337e4/b00c526d-f09c-4485-839f-55b527859934)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by shirazdole** [comment]
cc @ciaran

**Comment by gGh00sTt** [comment]
Hello @shirazdole .  I wanted to know if there design available for this issue or removing the back button for the case of all event types hidden does the work.
