### ISSUE TITLE
Add ability to generate event type booking link with prefilled inputs (i.e. guests)

### ISSUE THREAD

**Issue by RobertWSaunders** [calcom/cal.com#5055]
### Describe the solution you'd like

We have a use case where we'd like to send a user of ours to a specific event type booking link. Right now it's a suboptimal experience because they have to input their information, we should be able to provide the users details as query params to pre-fill the inputs for the event booking. Additionally, some of our events are more than 1:1 events, we'd like to have the guest list prefilled so the booking user doesn't need to worry about making sure to add the right people.

### Describe alternatives you've considered

There is currently no alternative in Cal.com AFAIK.

**Comment by emrysal** [comment]
So the one thing I am not sure about is with custom inputs, but a lot of this is in fact possible:

For example @ https://cal.com/peer/book?guest=peer%40cal.com&guest=alex@cal.com&type=112334&date=2022-10-27T12%3A00%3A00%2B01%3A00&slug=programming&count=&notes=hello&email=me@cal.com&name=Alex

**Comment by RobertWSaunders** [comment]
@emrysal ah nice! That's what I was looking for, is there a way to disable the scheduler from being able to remove guests?

**Comment by emrysal** [comment]
At the moment no, needs a bit of thought if we want that and also how to technically get it to be readonly 💭

**Comment by RobertWSaunders** [comment]
Yeah, what's weird is you can still provide these query params if the event type has guests disabled, by supplying the query params it effectively disables the disable. I tried that out because I was hoping the query params would add the guests and not allow the addition of any more or the removal of them. 

It would be nice to support some version of this feature. Our platform schedules meetings between our employees and our clients. We'd like to automatically the collaborators of the scheduling client to the booking and not let them be able to remove the guests since they are required to be at the meeting.

**Comment by jacksonblankenship** [comment]
This would be huge for us, too

**Comment by PeerRich** [comment]
can I close this? wanna open a new ticket for a read only mode? (not sure how this would look like)
