### ISSUE TITLE
[CAL-207] Can't update email when using Google as identity provider

### ISSUE THREAD

**Issue by RobertWSaunders** [calcom/cal.com#5058]
### Issue Summary

If you signed in with Google initially and navigate to your profile account to update your email it asks you for your password. When you use Google you don't have a password so its not possible to update your email.

### Steps to Reproduce

1. Create account with Google
2. Try to update email

Workaround is to logout, and use "Forgot Password" to set a password to be able to update your email.

### Technical details

* [Cal.com](http://Cal.com) v.2.1.0-h-pro

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by shirazdole** [comment]
Thank you for flagging! Tagging @Jaibles and @zomars

**Comment by PeerRich** [comment]
We're aware of this, but its not quite easy. will look into a solution, soon. Until then, please email support@cal.com (cc peer@cal.com) so we can do it manually

**Comment by Udit-takkar** [comment]
i think this has been fixed here https://github.com/calcom/cal.com/pull/5160 . i have removed password requirement when updating profile with identity provider.
