### ISSUE TITLE
Add ability to add an attendee to a booking and send an invitation email

### ISSUE THREAD

**Issue by RobertWSaunders** [calcom/cal.com#5059]
### Describe the solution you'd like

From what I can tell, you can't add someone to a booking and send them an event invite email once the booking is created?

**Comment by shirazdole** [comment]
Great question! 

If you're talking about once a booking is booked, then the only way to do this is by adding them to the calendar event. 

Another way I'm interpreting your question is "how do I send an attendee an invite without them booking anything, and this can be accomplished by going to the appropriate booking link, adding someone manually as an attendee with their email, and then they'll get a google calendar invite! 

Let me know if I'm understanding correctly

**Comment by PeerRich** [comment]
that is correct. you would need to do this with your calendar

**Comment by PeerRich** [comment]
i dont htink this is something we can do, because some calendars dont have an update event API
