### ISSUE TITLE
[CAL-177] Empty location in /[user]/book

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#5066]
![Screenshot 2022-10-18 at 3.34.43 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e6c10ce5-c557-4fee-869c-35239b0dc95e/40b66666-bb37-466b-87bd-27f3565fd9a8)

But it is Cal Video.

![Screenshot 2022-10-18 at 3.35.13 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7f9dd5a6-230f-4d4b-9dbe-89fe150a206f/c972e6aa-5fbe-4ed2-834b-c111dd4abb64)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by sugaya24** [comment]
Hi @Udit-takkar 
If there is one or less location available to be selected, nothing seems to appear including heading. Are there any requirements to reproduce this?

**Comment by Udit-takkar** [comment]
@sugaya24 It's showing up here https://cal.com/udit/30min. Not sure what is causing this. behaviour

<img width="867" alt="Screenshot 2022-10-20 at 12 09 25 PM" src="https://user-images.githubusercontent.com/53316345/196874483-a9298b12-deeb-4a98-88b7-fd2a8afb751b.png">

**Comment by sugaya24** [comment]
It seems to have been fixed here. #5074
