### ISSUE TITLE
[CAL-264] Recurring Error when Scheduling

### ISSUE THREAD

**Issue by gadgetb0y** [calcom/cal.com#5073]
#### Instance: [Cal.com](http://Cal.com) hosted

Anyone attempting to schedule a meeting on any event type receives the following error:

`Could not book the meeting. invalid_type in 'id': Required; invalid_type in 'onlineMeetingUrl': Required`

This has been occurring since Monday morning US Central Time.

### Steps to Reproduce

Completion of any booking form.

### Technical details

Browser: Most recent versions of Firefox, Chrome, Edge
OS: Most recent versions of MacOS, Windows 10

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by mattsmallman** [comment]
How did you fix this to close? I have the same issue.

**Comment by gadgetb0y** [comment]
I didn't. I canceled my Cal.com account and switched to Calendly.

**Comment by PeerRich** [comment]
hey @gadgetb0y that's sad to hear. We'll reopen this issue and investigate

**Comment by PeerRich** [comment]
i believe this was fixed a long time ago. haven't heard any reports
