### ISSUE TITLE
Whereby URL needs wrapping

### ISSUE THREAD

**Issue by ConnorGargano** [calcom/cal.com#5075]
Found a bug? Please fill out the sections below. 👍

Using a whereby URL as a location doesn’t look so good on the calendar view.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

Wrap the text to not overflow on the calendar
This can be seen here: https://cal.com/patrickludewig/30min

[image](https://user-images.githubusercontent.com/88032331/196442978-7bc1d1b4-ee0a-41f2-892a-d80bd4727e1f.png)

**Comment by Udit-takkar** [comment]
<img width="780" alt="Screenshot 2022-10-18 at 8 42 26 PM" src="https://user-images.githubusercontent.com/53316345/196470813-641a07fc-3fa7-49ae-88a3-6228f572ecc9.png">

@ConnorGargano  it will look something like this. is this fine?

**Comment by PeerRich** [comment]
> Yeah that's good

I wonder if we just truncate + tooltip maybe?

**Comment by PeerRich** [comment]
@JeroenReumkens what do you think?

**Comment by JeroenReumkens** [comment]
Perhaps we could put a text that we have more control of, like "online meeting", which is an anchor that links to the actual link? 🤔

**Comment by Udit-takkar** [comment]
<img width="321" alt="Screenshot 2022-10-19 at 4 47 34 PM" src="https://user-images.githubusercontent.com/53316345/196676646-763d6f6f-4abc-429c-9232-477a10fb965f.png">

This url bug is also in other pages.

**Comment by PeerRich** [comment]
> > I wonder if we just truncate + tooltip maybe?
> 
> I tried this but you want be able to copy the url from tooltip.

well you can just link to it with target="_blank" no?

**Comment by Udit-takkar** [comment]
oh yeah right. will add this
