### ISSUE TITLE
[CAL-179] event-types/availability edit buttons throw 404

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5076]
![CleanShot 2022-10-18 at 15.05.01@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c71b5910-a74f-4b2c-bd5e-ac3199fff3f7/349ba70a-794c-4498-b1d0-a64fe485cd5d)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MatheusBeniniF** [comment]
hey @PeerRich , here it is working normally
https://www.loom.com/share/3786c2f540984be781fd1433e98f2919

**Comment by MatheusBeniniF** [comment]
any updates on that?

**Comment by PeerRich** [comment]
I believe it was fixed
