### ISSUE TITLE
[CAL-183] email and calendar still use old “cancel/reschedule” screens

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5081]
![2F9E35DD-EB80-4373-BD6C-250B879D71CA.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3871fd8b-5a5d-49df-9a86-d342e7977c00/d38b6174-b20f-46c3-b092-f0dc54f1c0f9)

![E88A97D8-D34B-47BD-B8AB-3284F7AC0394.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bfb04183-fbca-458a-96be-c29fc75d5915/2263bd6d-1bf3-4120-9549-163fd014b6a1)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MuriloAmarals** [comment]
@PeerRich Could you take a look at the [PR](https://github.com/calcom/cal.com/pull/5149) with the solution to the issue?
