### ISSUE TITLE
[CAL-184] Cancel a booking flow needs updating

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5082]
Current flow:

[9962697e-7f84-47e9-99d6-39df030209ab](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4bedcfa7-c406-4873-a9cf-2044d0255c7c/9962697e-7f84-47e9-99d6-39df030209ab)

Flow should be: 

[containers - ❖ Cal DS v2.0 (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17954%3A199476)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by matheusmuniz03** [comment]
@Jaibles Do you want the new version to look like this?

**Comment by PeerRich** [comment]
important to note: we have this success page, but if you visit the /cancel/ or /reschedule/ URL, it should scroll down and open the correct box (cancel) or (reschedule)

**Comment by Jaibles** [comment]
Note: Clicking reschedule should take you on this flow as it does currently:

https://user-images.githubusercontent.com/4536123/196656889-0b9ffe33-fc74-4a0c-adc8-78ff63398ad9.mp4

**Comment by PeerRich** [comment]
@carina wanna work on this?

**Comment by CarinaWolli** [comment]
@PeerRich Yes, I can take this 👍

**Comment by PeerRich** [comment]
we need to make sure to replace the /cancel/ and /reschedule/ URLs to redirect to the correct new page

**Comment by CarinaWolli** [comment]
I think the refactor of the booking success query (#5053) should be done first. After that it should be pretty straightforward to redirect to `/success?uid={bookingUID}?cancel=true` instead of `/cancel?uid={bookingUID}`

**Comment by Jaibles** [comment]
Reschedule won't go to this page though. It will follow the route it currently has right? There's no issues with that as far as I can see

[97fee62c-fa45-4dce-8a51-4e4ac089971d](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/08d4f505-e9cf-4971-99e2-11b2553b96bb/97fee62c-fa45-4dce-8a51-4e4ac089971d)

**Comment by PeerRich** [comment]
so its only cancel then

**Comment by Jaibles** [comment]
Currently experiencing an issue where an already cancelled event is still on my calendar and it links to here:

![CleanShot 2022-11-01 at 10.59.16@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/662b71c7-80ba-4ca8-b98b-48b12e39f094/59c150ad-11be-496c-a896-e330975467e4)

This should be replaced by this:

[Cancelled - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=13%3A20662)
