### ISSUE TITLE
[CAL-185] /event-types: apps > available apps not mobile friendly

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5083]
![491B1011-F25D-489A-9A5E-CA794AFB675F.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/797faf56-e7cd-4e3d-ab68-8d1ef064899b/60cf0e46-862a-47a8-b8aa-9cf136e4edbb)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MuriloAmarals** [comment]
Hey @PeerRich what do you want me to improve on this page?

**Comment by Udit-takkar** [comment]
should be fixed from https://github.com/calcom/cal.com/pull/5071
