### ISSUE TITLE
Chrome Exentsion: Add button to Gmail that copies times as list with links

### ISSUE THREAD

**Issue by cozysd** [calcom/cal.com#5086]
One of my most common use cases is responding to an email with time slots for availability. I'd like to do more than hit people with a link to go figure it out themselves; I'd rather offer them times I've selected for us to meet and in a click (or two) let them schedule it up.

Some, but not all, of the competitors support some way of copying a list of times from inside the app, then pasting it into an email. This feels archaic, but gets the job done and I'd consider this a minimal implementation. Ideally, there's a button in my Gmail that can make this quicker.

And, of course, it should look just lovely in the email. :)

**Comment by PeerRich** [comment]
i saw someone make a chrome extension, this could be build into it

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by sudoliyang** [comment]
Hi, I'm looking for similar feature. Is it support to copy the time slots to past in email?
Thanks a lot.

**Comment by PeerRich** [comment]
duplicate of https://github.com/calcom/cal.com/issues/4692
