### ISSUE TITLE
[CAL-187] Make an Embed element that can be used to make any page embed compatible

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5090]
Some of the things that it would take care

* Adding a main element
* Adding mx-auto and max-width 
* Maybe doing runtime checks of some invalid descendants of  Embed element

Motivation:

Booking Pages and Routing forms all have their own JSX which currently is required to have these common things mentioned above

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
this sounds like an atom @sean-brydon @JeroenReumkens
