### ISSUE TITLE
[CAL-191] Allows adding "reply-to" header in email workflows

### ISSUE THREAD

**Issue by dschuermann** [calcom/cal.com#5092]
### Is your proposal related to a problem?

It would be great if people could reply to emails sent using the workflow. Their emails should not go to [hello@cal.com](mailto:hello@cal.com) instead these replys should go to my email address.

### Describe the solution you'd like

I would like to be able to set a "reply-to" header inside workflows. This is a very simple way to solve the problem.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
I believe we did that, no @alishaz-polymath ?

**Comment by dschuermann** [comment]
Hm, at least I don't see this in the emails I get when I press "Test action" in the workflow.

**Comment by alishaz-polymath** [comment]
@PeerRich I’m not sure we do. @CarinaWolli probably knows better about it 🤔

**Comment by CarinaWolli** [comment]
We have not done this yet, but that should be a simple fix. @PeerRich @Jaibles Do we want to have settings in workflows to define the reply-to email or do we just always want the organizer's email to be the reply-to email

**Comment by Jaibles** [comment]
I would think the reply to being the organiser's email is totally fine. 

@dschuermann is there a specific reason you'd want to it to be anything other than this?

**Comment by dschuermann** [comment]
> Reply-to being the organiser's email is totally fine imo @CarinaWolli. It keeps the UX simpler and presumably the implementation.
> 
> @dschuermann any specific reason you'd want it to be anything other than the email address of your cal account or are you happy for us to default to that?

I am happy if you use to the ORGANIZER email address :)

**Comment by Jaibles** [comment]
Thank you @dschuermann. A data point of one is all we need in this instance :)

**Comment by aaronjedwards** [comment]
As I understand it, there was a change that just makes the default reply to the organizers email address. We have a use case in which we use workflows to email an account connected to our help desk and it would be nice to have the reply-to be the attendee email, in which case, replying to the email (via the help desk) would reply to the attendee.

Thoughts on this?

**Comment by CarinaWolli** [comment]
@aaronjedwards feel free to create an issue for it, if more people are interested in that we will look into it!
