### ISSUE TITLE
[CAL-188] Embed Modal doesnt' close on success page, if clicked just outside the content

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5093]
> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by matheusmuniz03** [comment]
Hey @hariombalhara , could you give me more information about this issue?
Would this be the success page? What would be the Embed Modal?
![Captura de tela de 2022-10-19 16-41-18](https://user-images.githubusercontent.com/87545749/196788429-90736a29-d11a-4039-9db8-8a4d64a24fc0.png)

**Comment by hariombalhara** [comment]
Yeah this is the success page. I will record a loom of the bug. But what happens is that, when you are embedding a cal link and do a booking through it. When you reach the success page, try to close the embed modal box, by clicking just outside the modal box. It won't close. It works for other pages.

**Comment by hariombalhara** [comment]
Here is a loom showing the issue. https://www.loom.com/share/63b76d5258ba4a23ae364edd488e8318

This is the test codesandbox https://codesandbox.io/s/embed-popup-on-click-of-an-existing-element-demo-react-sc967e?file=/src/App.js

**Comment by asadath1395** [comment]
@hariombalhara Can we close this bug? Seems like this is addressed
