### ISSUE TITLE
[Integration:n8n] Add 'event_ended' trigger

### ISSUE THREAD

**Issue by Maybach91** [calcom/cal.com#5094]
### Is your proposal related to a problem?

I want to use automations based on the trigger, when an event is ended. This is currently only possible with the Zapier integration, but not with the n8n integration. There is the trigger missing.

<table>
<tr valign="top">
	<td>
n8n Triggers:  
<img width="370" alt="n8n available triggers" src="https://user-images.githubusercontent.com/1867543/196672990-008f8980-36ed-4bd1-903a-2953c76edf91.png">
  </td>
	<td>
Zapier Triggers:  
<img width="370" alt="zapier available triggers" src="https://user-images.githubusercontent.com/1867543/196673228-85e0d6c7-efe9-4393-96e3-1ac5fdd55de2.png">
</td>
</table>

### Describe the solution you'd like

Make the `event_ended` trigger in the n8n integration available as well.

### Describe alternatives you've considered

Nothing aware of.

### Additional context

I want to create a database entry in Notion (for Event Notes) automatically when an event created (perfect would be if it really started to avoid a second automation to delete cancelled events). After the Event ended, I want to send the attendees an e-mail with a link to my notes. Maybe you can create something similar to this differently. Zapier is currently to expensive for this multi step workflow (getting notion entry to compose the email)

**Comment by milospuac** [comment]
Thanks for the suggestion @Maybach91, our team will look into implementing this soon.

**Comment by PeerRich** [comment]
@CarinaWolli wanna extend all wrokflows to n8n? or should @alishaz-polymath do it?

**Comment by Maybach91** [comment]
Will this feature be planned any time soon? My switch to cal.com is depending on this integration (unfortunately, haha).

**Comment by PeerRich** [comment]
yes, we assigned @alishaz-polymath for it

**Comment by Maybach91** [comment]
Are there any updates on this?

**Comment by alishaz-polymath** [comment]
Yeah, PR is up for it. Awaiting merge
https://github.com/n8n-io/n8n/pull/5331

**Comment by alishaz-polymath** [comment]
PR merged and released https://github.com/n8n-io/n8n/pull/5331#issuecomment-1463788936
