### ISSUE TITLE
Cancelling a Booking doesn't remove the event from my Nextcloud CalDAV calendar

### ISSUE THREAD

**Issue by jdaviescoates** [calcom/cal.com#5101]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cancelling a Booking doesn't remove the event from my Nextcloud CalDAV calendar

### Steps to Reproduce

1. Cancel a booking
2. Spot that it is still in my calendar.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@alishaz-polymath

**Comment by alishaz-polymath** [comment]
Hey @jdaviescoates Can you confirm if this is still occurring? I remember fixing this a while back, not sure if there was regression in the mean time. 🙏

**Comment by jdaviescoates** [comment]
Yes, you obviously did fix it because it worked for me last time I had to cancel a booking. Thanks!
