### ISSUE TITLE
[CAL-196] /apps/<detail>: Layout Shift when loading screenshots

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5110]
- [ ] show skeleton instead

https://user-images.githubusercontent.com/8019099/196755305-1cd7d51e-78de-402b-b01a-214fc9371410.mp4

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by noobyogi0010** [comment]
Hey @PeerRich 
I would like to work on this if one else has already taken it up.
Thanks!

**Comment by PeerRich** [comment]
@noobyogi0010 go for it!

**Comment by Udit-takkar** [comment]
hey @noobyogi0010  just checking in. are you still working on this issue ?

**Comment by harshsinghatz** [comment]
@Udit-takkar if it's still open can i work on this?

**Comment by Udit-takkar** [comment]
@harshsinghatz it's still open but i don't if @noobyogi0010 is working on this or not

**Comment by noobyogi0010** [comment]
@harshsinghatz and @Udit-takkar 
I'm working on this but I'm getting the following error while running `yarn dx` command:
```
@calcom/web:dx: error - Cannot read properties of null (reading '1')
```

Do you have any idea why this might be coming?

**Comment by harshsinghatz** [comment]
> @harshsinghatz and @Udit-takkar 
> I'm working on this but I'm getting the following error while running `yarn dx` command:
> ```
> @calcom/web:dx: error - Cannot read properties of null (reading '1')
> ```
> 
> Do you have any idea why this might be coming?

Try running yarn clean and yarn

**Comment by noobyogi0010** [comment]
@harshsinghatz I am still getting the same error.
I believe @Udit-takkar you can take it up as I think this error can be a blocker for me to resolve the issue.
Do let me know if you come across such error and know the fix for it.

**Comment by Udit-takkar** [comment]
@noobyogi0010  can you join our slack https://cal.com/slack and post the error that you are facing there ?
