### ISSUE TITLE
[CAL-197] sent email of routing form results to owner

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5111]
When submitting a routing form, it should send the results to the routing form owner by email:

> **What's your name?**
> Peer
>
> **How big is your team?**
> 1000

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@hariom wanna work on this?

**Comment by hariombalhara** [comment]
Sure, This seems like a workflow thing but something that should be automatically enabled(without manual workflow configuration).
Have we thought about using workflows internally as well for such things

Cc@CarinaWolli

**Comment by CarinaWolli** [comment]
@hariombalhara How exactly would you wanna use workflows for it?

**Comment by hariombalhara** [comment]
The way I understand it, a workflow can be used to take some action based on an event in Cal.com
These are the supported events right now. All of these events happen for an EventType.
First of all we can add Routing Form Event link Form_Submitted and on which a user can do all some RoutingForm related actions. One of those actions can be to email Routing Form owner as requested in this ticket.
<img width="1179" alt="Screenshot 2022-10-20 at 4 46 15 PM" src="https://user-images.githubusercontent.com/1780212/196934383-2086409c-1401-404d-8d62-2c2987e55162.png">


This is what a user would need to do to to receive email for each response. But what if we have a preset for it and in Routing Form UI user would just enable that preset?

**Comment by CarinaWolli** [comment]
> When submitting a routing form, it should send the results to the routing form owner by email

I think for this specific issue, a simple checkbox somewhere in routing forms should be enough no?

**Comment by hariombalhara** [comment]
Do we want it to be an automatically enabled option? or would it be an option in UI(enabled/disabled by default?).

Also, where exactly we want the option to come?

A sample email from my local that's working. Need confirmation on text as well

![Screenshot 2022-10-25 at 7.51.00 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fc87c599-fa17-4eac-8d9a-0bc80deeb705/50c85c3b-d479-457f-8762-3a2b4f318f61)

**Comment by hariombalhara** [comment]
cc @ciaran @peerrich

**Comment by PeerRich** [comment]
looks great!

**Comment by Jaibles** [comment]
On by default seems logical. Perhaps a toggle or check here?

![CleanShot 2022-10-26 at 14.06.20@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d2c81c11-f7a3-45a7-b0b0-fdaf5862d356/c672eefd-e5c2-444f-b1e4-2448a3464586)
