### ISSUE TITLE
[CAL-202] App Store: redirectUrl open in target="_blank"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5117]
![CleanShot 2022-10-19 at 22.39.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5bca7e84-4da4-4006-a26a-b928f77f7544/8b65e3dc-0b15-40ac-a691-16d85dc147ae)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by hariombalhara** [comment]
@PeerRich If we start opening in new tab what should be happen on cal.com webapp tab. Should it redirect to apps/installed?

**Comment by PeerRich** [comment]
it could just stay imo
