### ISSUE TITLE
[CAL-203] App Store: Add <iframe> as an option in the slider

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5118]
![CleanShot 2022-10-19 at 22.44.17@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a05b595f-797b-4338-8293-157ab5a74acd/11298215-722e-4f40-a01a-c9f1a2f65f6f)

right now we only accept paths to images, but an iframe to youtube would be great, too

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by KlingerMatheus** [comment]
Hello @PeerRich, which page it is using this slider? I'm not finding here.

**Comment by PeerRich** [comment]
@hariombalhara can help out with this

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, do we want to add support for an `iframe` to the slider component or the app detail component?
Do we want to add an `iframe` to these components?
![Screenshot 2023-02-21 at 3 54 10 PM](https://user-images.githubusercontent.com/121884634/220314882-5ad9f3d6-613c-47f4-8c6d-8e36f20b9def.png)

**Comment by PeerRich** [comment]
no. this ticket is referring to the app store detail page, like this one: https://app.cal.com/apps/google-calendar 

some apps have a youtube video and I wanna embed it

**Comment by gitstart-calcom** [comment]
Does it not already support that?
https://app.cal.com/apps/pipedream

Or do we want to embed it to the left panel?

**Comment by PeerRich** [comment]
yep in the left panel but i dont mind closing this if its low priority high complexity.

only add it in the slider if its easy

**Comment by gitstart-calcom** [comment]
Got it, thanks
