### ISSUE TITLE
[CAL-204] Routing Form - Improved CSV Exports

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5122]
## Current Status:

* 

```
```

* CSV is downloaded immediately. As responses in a Routing Form increase, this time would keep on increasing.

## What do we want to achieve?

* 

```
```

* Should support thousands of responses
* 

```
* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~I am thinking that the fields that are currently present in the Routing Form should be shown in one Sheet and the fields that are less relevant(because of being deleted) should be shown in separate sheet. If we go with the approach, we can either have 2 Download CSV buttons or a single excel sheet download that can have 2 sheets.~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

* If responses are less, the download should possibly be immediate but otherwise, the report should be emailed or put into downloading status inside app. Once the download is ready, it can be downloaded from the app.

### Some Facts first:

* Vercel Serverless Function has an execution limit of 60s in PRO plan. It can possibly exceed the limit when there are thounds of responses in the picture.
* Vercel Serverless Function has memory limit of 1024MB. It can be increased to 3008MB for PRO Plan. If we don't do a steaming write, this limit can exceed with thousands of responses, depending on how much text based fields were there in the form and what kind of input they had.

### Approach:

* Do the response to CSV conversion in the Serverless Function itself with a limit(that allows doing conversion within the limits of Serverless Function) and offset.  The Serverless fn can call itself recursively with changing offsets till entire responses table is consumed and written into a CSV.
* Every execution of serverless fn would append to CSV that would be in AWS S3.
* Once the iterations are complete, we can update *reports(a new table)* table with
  * formId
  * A URL of CSV file
  * lastResponseTime: The time of the last response in CSV
  * Possibly a hash of the CSV file
* Whenever request to download report is received, we can query responses with createdTime greater than lastResponseTime
  * If no entry is there, serve the existing CSV
  * If a new entry is there, start appending to the CSV starting from those new responses.
* There is no **flush/discard data button available**, but it should be.Once it's there, we should delete the CSV file and remove the entry from *reports* table.

The above approach considers the fact that we want Routing Forms to be easy to install and maintain for our Infra users as well. But it does add a new dependency of AWS S3 bucket configuration which I believe won't be a pain to setup and use. We can add other connectors as well.

> From [SyncLinear.com](https://synclinear.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-204](https://linear.app/calcom/issue/CAL-204/routing-form-improved-csv-exports)</sub>

**Comment by PeerRich** [comment]
i think this has been done @hariombalhara right?

**Comment by hariombalhara** [comment]
Non strikedthrough things are pending

**Comment by PeerRich** [comment]
lets add this to the "routing forms" milestone that we plan soon
