### ISSUE TITLE
[CAL-211] Confirmed booking page for rescheduled event should show previous time and reschedule reason

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5134]
[Scheduled - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=68%3A95398)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MatheusBeniniF** [comment]
@Jaibles, I don't have permission to see the figma link

**Comment by Jaibles** [comment]
@MatheusBeniniF apologies, permission on the file updated. Please try again.

**Comment by MatheusBeniniF** [comment]
@Jaibles what do you think about this?
![image](https://user-images.githubusercontent.com/88898100/197053673-e2fad7ab-b6b9-4ce1-a641-f03b33da5b80.png)

**Comment by Jaibles** [comment]
@MatheusBeniniF sorry thought I had replied this this. Looks great 👍

**Comment by Jaibles** [comment]
What do we need to do to get this approved and merged? Designs look good.
