### ISSUE TITLE
[CAL-215] some events get confirmed without user action but then don’t show up

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5139]
I had three events, that needed conformation from my side, but in the backend there where shown as regular planned and confirmed events. They didn’t show up in my synced iCal calender though.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by hariombalhara** [comment]
This might have already fixed it. https://github.com/calcom/cal.com/pull/5141

**Comment by saschafoerster** [comment]
Have the same issue, waiting for a new release to test it. :)
