### ISSUE TITLE
[CAL-216] Confirming a booking shows old toast

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5140]
![Screenshot 2022-10-21 at 10.44.07 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e31a9ff6-83fd-4480-850f-e90fa3d6ef3c/ee4b0b2f-b35f-4ecc-89c4-6f9b40e14488)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MuriloAmarals** [comment]
Hey @hariombalhara do you have the design of the new one?

**Comment by hariombalhara** [comment]
It's used throughout the app. It is just that import needs to happen from ui/v2/core. Also, it would be great if you can remove the old packages/lib/notification along with it's usage throughout the app
<img width="634" alt="Screenshot 2022-10-21 at 10 57 14 AM" src="https://user-images.githubusercontent.com/1780212/197119403-4d356496-e784-4839-bff3-153725a4ee7c.png">

**Comment by MuriloAmarals** [comment]
Let me take a look!

**Comment by MuriloAmarals** [comment]
@hariombalhara this apps/website/lib/notification.ts is not appearing on my search.
![image](https://user-images.githubusercontent.com/87545137/197121349-bfa563b7-efc2-42db-bcd6-5f4264cf2506.png)

**Comment by hariombalhara** [comment]
Forget about website/lib. That's a private repo. You just need to delete packages/lib/notification.ts

**Comment by MuriloAmarals** [comment]
@hariombalhara Now that I delete packages/lib/notification.ts and replace the imports it's not showing any toast when I booking a meeting, is that correct?

**Comment by MuriloAmarals** [comment]
@hariombalhara I deleted the old file and changed the imports to v2 import `{ showToast } from "@calcom/ui/v2/core";` but the toast stopped showing.
