### ISSUE TITLE
[CAL-267] MS Teams No URL - Only works for sometime

### ISSUE THREAD

**Issue by CodingRockz** [calcom/cal.com#5158]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Add MSTeams 365 app
2. Add a event with MS Teams location
3. create a booking and find the link does not have the url

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

After the previous update that claimed to have fixed this issue, i updated and tried this again. It worked as expected when i removed and added the app again. It was working for 1 hour, and then it stopped working. I have not changed anything on my end for it to stop working.

Yarn start shows the following

@calcom/web:start:   videoCallData: {
@calcom/web:start:     type: 'office365_video',
@calcom/web:start:     id: undefined,
@calcom/web:start:     password: '',
@calcom/web:start:     url: undefined
@calcom/web:start:   },
@calcom/web:start:   metadata: {}

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by CodingRockz** [comment]
@joeauyeung Any update on this. This is an issue that was identified months ago, and re-raised as not being fixed multiple times. The azure account has offline mode also allowed as per the previous request

**Comment by joeauyeung** [comment]
Thanks for your patience @CodingRockz. I just created a booking with MS Teams after not using it for >1hr. I also manually edited the expiry date of the token in the DB. In both instances, a Teams URL was generated. 

In `packages/app-store/office365video/lib/VideoApiAdapter.ts` are you able to log the `resultObject` on line 140 and share it with us? You can omit the `joinInfo` key as it won't contain anything useful for us.

**Comment by joeauyeung** [comment]
Resolved in https://github.com/calcom/cal.com/pull/5886. No new logs with MS Teams errors
