### ISSUE TITLE
[CAL-239] Alert teams when subscription needs to be paid (retroactive & expired subscriptions)

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#5167]
> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by joeauyeung** [comment]
@ciaran, what would be the best way to alert team owners that their subscription is expired / not paid? I'm thinking of having a banner on the top of the screen, like what we did for V2.

**Comment by Jaibles** [comment]
Yea a top banner is a good idea since this is a high priority issue. Will try dig it out!

**Comment by Jaibles** [comment]
[Option A - Top Banner persistent across app - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=15%3A24691)

@joe here we are

**Comment by Jaibles** [comment]
@sean probably a component we should consider adding the the DS if we're going to be re-using it?

**Comment by sean-brydon** [comment]
For sure - if its in DS on figma could you create an issue and pass it over?

**Comment by sean-brydon** [comment]
@joe are you needing this component now? I will create it in main if so - if not i will create it in our storybook-cleanup branch

**Comment by joeauyeung** [comment]
@sean-brydon, some stuff popped up, so I don't need it right now. But if you're creating it in storybook, then that's awesome!

**Comment by zomars** [comment]
PR here [https://github.com/calcom/cal.com/pull/5541](https://github.com/calcom/cal.com/pull/5541)
