### ISSUE TITLE
[CAL-242] cal.com/apps/[appname] keeps loading

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#5177]
[c84e40f4-0443-4f6c-a780-c11f725d72c5](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/68123193-2390-40ac-bff0-ac05a08d79c9/c84e40f4-0443-4f6c-a780-c11f725d72c5)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by harshsinghatz** [comment]
![image](https://user-images.githubusercontent.com/51085015/197573013-65e894e7-99a1-48cd-8956-e60c22f1757c.png)
@Udit-takkar works fine on my end, can you check again!
