### ISSUE TITLE
[CAL-243] Google Calendar showing busy every time

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#5185]
Anyone know why the Availability Troubleshooter would be telling me then, when it's definitely not the case

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/09c8443f-c85e-4b8d-8c30-39ba5acbea93/558f01e5-0405-4f78-b2fc-a277b061724b)

Every day is like this, as far as the troubleshooter (and Cal app) is concerned, while my calendar on google has open availability. I've disconnected  and reconnected the Google Calendar app in Cal a few times, and I've revoked permission on the google side of things, then reauthorised... still showing as all day every day being busy.

[https://calendso.slack.com/archives/C01NXDSRY9W/p1666624150861239](https://calendso.slack.com/archives/C01NXDSRY9W/p1666624150861239)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by milospuac** [comment]
Didn't toggle his calendars to be checked for conflicts @udit

**Comment by Udit-takkar** [comment]
ok thanks @milos
