### ISSUE TITLE
[CAL-245] remove link from cal video logo

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5188]
> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MuriloAmarals** [comment]
Hey @PeerRich Where can I find this cal video logo?

**Comment by MuriloAmarals** [comment]
The link you mentioned above is the `url`?

![image](https://user-images.githubusercontent.com/87545137/197845792-8d51ff72-bed9-4a0f-ac97-8e7e3485d67e.png)

**Comment by PeerRich** [comment]
I'll work on this, no worries
