### ISSUE TITLE
Disbanding a team gets stucks on limbo

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#519]
### Issue Summary

Whenever you disband a team an try to create a new one with the same name, the form doesn't present any errors but the team isn't created either.

When inspecting the network tab we get this error:

```json
{"errorCode":"TeamNameCollision","message":"Team name already take."}
```

### Steps to Reproduce
1. Create a team with a name "test123"
2. Disband the team
3. Try to re-create the team with the same name

**Comment by PeerRich** [comment]
@zomars is this still happening?

**Comment by zomars** [comment]
> @zomars is this still happening? 

Not sure. Will retest on Monday and update accordingly

**Comment by emrysal** [comment]
@zomars Just tested this; it's fixed (there was another bug I discovered whilst testing which is probably fixed by the time you read this @ https://github.com/calcom/cal.com/pull/2454)
