### ISSUE TITLE
[CAL-247] CSV Routing Forms - More columns that we can add

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5195]
* Which Event was the user Routed to and whether he booked that event. Also add `bookingId`
* If the user wasn't taken to an EventType for booking, 
  * What custom message was shown to him
  * Which URL was he redirected to.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
I think we do that already, no?
