### ISSUE TITLE
[CAL-248] Problem with the integration of a button in react

### ISSUE THREAD

**Issue by flaviomoceri** [calcom/cal.com#5196]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Put useEffect in the component
2. Put data-cal-link in a buttton using this url [https://cal.com/team/\[your_username\]](https://cal.com/team/%5Byour_username%5D)
3. When you try to click this button and then click an event it will appear this url [https://cal.com/team/\[slug\]/\[your_username\]/30-minuti-meeting](https://cal.com/team/%5Bslug%5D/%5Byour_username%5D/30-minuti-meeting). The problem is because in the url there is \[slug\] and obv it will appear cal link doesn't work. Please fix that
4. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by flaviomoceri** [comment]
Please someone fix that. The problem I think is very easy, but at the same time this little problem makes a big problem because nobody can book through the link.

**Comment by Udit-takkar** [comment]
hey @flaviomoceri i am unable to understand the bug and steps to reproduce. what do you mean by put useEffect in component and put data-cal-link [https://cal.com/team/[your_username]](https://cal.com/team/%5Byour_username%5D) ?

**Comment by flaviomoceri** [comment]
https://github.com/calcom/cal.com/issues/5206 here I explain how to see the error

**Comment by flaviomoceri** [comment]
please fix it

**Comment by flaviomoceri** [comment]
https://codesandbox.io/s/embed-popup-on-click-of-an-existing-element-demo-react-forked-c5g8lk?file=/src/App.js check this example

**Comment by Udit-takkar** [comment]
okay i am looking into it

**Comment by flaviomoceri** [comment]
Thanks

**Comment by flaviomoceri** [comment]
I think that this is urgent because this little problem makes a big problem because nobody can book through the link

**Comment by harshsinghatz** [comment]
> I think that this is urgent because this little problem makes a big problem because nobody can book through the link

Yeah sure, will try to fix this asap

**Comment by flaviomoceri** [comment]
ok thanks, please write me when you fix it

**Comment by hariombalhara** [comment]
This is fixed now

**Comment by harshsinghatz** [comment]
@hariombalhara Thanks!, I had a laptop issue
