### ISSUE TITLE
Include summer / winter time difference in availability calculation

### ISSUE THREAD

**Issue by JonasUllrich** [calcom/cal.com#5200]
### Is your proposal related to a problem?

I am currently in summer time and would like to display the available time slots for an appointment in winter time. Unfortunately, the available dates displayed are outside the booking period. 

(Write your answer here.)

### Describe the solution you'd like

All available dates, regardless of the time, should be within the booking period. 

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by PeerRich** [comment]
do you have a visual proposal how it could look like?

**Comment by PeerRich** [comment]
would this require UI changes? If yes, can you mock them?
