### ISSUE TITLE
[CAL-251] If Google Meet is the location, confirmation email doesn't get sent

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#5202]
[https://app.birdeatsbug.com/sessions/Af1G2hCruXmnQi_GX3hjo8U0MMSuZhFCXq96hlTTsu7l](https://app.birdeatsbug.com/sessions/Af1G2hCruXmnQi_GX3hjo8U0MMSuZhFCXq96hlTTsu7l)\\

When I try any other location I get confirmation emails as intended

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by GlitchWitch** [comment]
I'm seeing the same issue. We have `Requires confirmation` enabled, after confirming an event no email is sent and no calendar entry is made.

**Comment by Udit-takkar** [comment]
fixed https://github.com/calcom/cal.com/pull/5205

**Comment by GlitchWitch** [comment]
Can confirm, #5205 looks to have solved this. :tada:
