### ISSUE TITLE
Could not book the meeting. invalid_type in 'id': Required; invalid_type in 'onlineMeetingUrl': Required

### ISSUE THREAD

**Issue by mattsmallman** [calcom/cal.com#5209]
### Issue Summary

Instance: Cal.com hosted

Anyone attempting to schedule a meeting on any event type receives the following error:

Could not book the meeting. invalid_type in 'id': Required; invalid_type in 'onlineMeetingUrl': Required

A meeting is created in bookings, but no invite is sent or the confirmation given to users.

The time appears to be blocked off and can't be rebooked but doesn't appear in O365 calendar.

### Steps to Reproduce

Completion of any booking form 

### Technical details

Apps for Zoom, MS Teams and Office 365 installed.
Removing all apps and reconnecting to all services seems to work for a while but breaks again within 24hrs

Most recent versions of Safari, MacOS

**Comment by mattsmallman** [comment]
Just checked the sign in logs from our O365 tenant and there are repeated failures to authenticate from cal.com when you are trying to refresh your token. 

`Failure Reason: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '{identifier}'.`

There are success logs for the initial token collection but the refresh appears to be failing please contact direct if you need more diagnostics

**Comment by milospuac** [comment]
@joeauyeung can you have a look? I think it happened again. However, I just tried to connect my Outlook calendar and it worked.

**Comment by mattsmallman** [comment]
Any luck with this? - I had to move back to acuity but would love to come back.

**Comment by mattsmallman** [comment]
@joeauyeung and @milospuac - I am no longer getting the errors when booking after 24 hours - but the meeting location shows "Office365_video" instead of a teams link (having been correct for approx 24 hours) - there are no failures to authenticate in my AD logs this time.

**Comment by PeerRich** [comment]
this issue seems to be fixed? @mattsmallman can you open a new ticket for your new issue?
