### ISSUE TITLE
Add: loading progress bar on the top of the page

### ISSUE THREAD

**Issue by harshsinghatz** [calcom/cal.com#5214]
### Is your proposal related to a problem?

- Currently, if it takes a considerable amount of time for changing routes/ loading something there is no feedback to the user on the state of loading, which sometimes makes it seems that nothing is happening

### Describe the solution you'd like

- Adding the loading bar on the top of the page 
- eg: 
![image](https://user-images.githubusercontent.com/51085015/197854409-3f1024a0-96ce-4751-bbac-eaa80a31613f.png)

**Comment by harshsinghatz** [comment]
@Jaibles Is this something we can try implementing?

**Comment by PeerRich** [comment]
page-wide loading screens have fallen a bit out of fashion. youtube recently removed them. 

we're mostly using skeleton loaders nowadays

**Comment by PeerRich** [comment]
> if it takes a considerable amount of time for changing routes/ loading something there is no feedback to the

instead we should improve page speed & optimistically load / safe things

**Comment by harshsinghatz** [comment]
> page-wide loading screens have fallen a bit out of fashion. youtube recently removed them.
> 
> we're mostly using skeleton loaders nowadays

Oh didn't knew it's not preferred nowadays

**Comment by harshsinghatz** [comment]
> > if it takes a considerable amount of time for changing routes/ loading something there is no feedback to the
> 
> instead we should improve page speed & optimistically safe things

Yeah, always an better option
