### ISSUE TITLE
[CAL-268] enable a corresponding variable for all input fields (add variable for email)

### ISSUE THREAD

**Issue by rice-b** [calcom/cal.com#5223]
### Is your proposal related to a problem?

Not exactly in the workflow I want to be able to state the users email not just attendee name.
I use the workflow message Custom/ an option to add variables to the email body. However, the variable for the email of the attendee isn't available just yet.

### Describe the solution you'd like

All input fields from the event screen are available as custom text variables in an alphbetised list.

(Describe your proposed solution here.)
I'd like to click on workflow / custom / then click to add text variables and then click to add the relevant field into my email

### Describe alternatives you've considered

(Write your answer here.)

Not really - just adjusted my wording so it's not required.

### Additional context

(Write your answer here.)
Nope - I raised a support ticket so it's now just about requesting the feature

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by CarinaWolli** [comment]
I will add the attendee's email to the dynamic text variables 👍
