### ISSUE TITLE
[CAL-265] Guests should be able to add their own location for in-person meetings

### ISSUE THREAD

**Issue by J4VMC** [calcom/cal.com#5226]
### Is your proposal related to a problem?

(Write your answer here.)

One of the main issues that we're facing with [cal.com](http://cal.com) is when our guests want us to go to their office or warehouse.

### Describe the solution you'd like

(Describe your proposed solution here.)

When creating an event type, if in location you select ***In person***, you must specify the address. However, when selecting the option for phone number, [cal.com](http://cal.com) already allows the guest to specify the phone number. The location for in-person meetings should work the same as with the phone numbers.

### Describe alternatives you've considered

(Write your answer here.)

I tried the suggestion the support team gave, which is adding a new required field to the booking form for the guest to add the location while typing in their details. This workaround isn't good enough, as the functionality should be built in like with the phone numbers as location for the meeting.

### Additional context

(Write your answer here.)

Calendly has this functionality already, and [cal.com](http://cal.com) truly needs it.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by mattsmallman** [comment]
+1 for this and for option of URL location to be entered by guest when for instance they are inviting you to an internal meeting

**Comment by om-ray** [comment]
@PeerRich If you would like this to be fixed, I would love to work on this

**Comment by PeerRich** [comment]
@om-ray waiting for the response to my question first, but then go for it!

**Comment by mattsmallman** [comment]
I would add as new fields for consistency with phone number (Attendee Location + Attendee URL) and to allow for "My Office" to be set by organiser as an option with attendee's able to add their own.

**Comment by J4VMC** [comment]
I'd add a new field, for consistency. Something like "In-person Guest suggestion" or something catchier

**Comment by om-ray** [comment]
I agree, I think a new field, possibly by the name of "In-person (Attendee's location)"

**Comment by PeerRich** [comment]
> I agree, I think a new field, "In-person (Attendee Address)" would be best if we also changed the field name for the other one to "In-person (Organizer Address)"

I like that.

wanna open a PR?

first a PR without address validation

**Comment by om-ray** [comment]
@PeerRich yes ill make one as soon as i finish

**Comment by om-ray** [comment]
@PeerRich @J4VMC @mattsmallman Please review the PR 🙏🏾

**Comment by PeerRich** [comment]
will do

**Comment by ddm231** [comment]
Thank you for this feature. How can I translate the label "In Person (Attendee Address)" on my booking site?

**Comment by J4VMC** [comment]
Thanks for this feature. When will it be deployed?
