### ISSUE TITLE
[CAL-260] Events Remaining display wrong list of remaining events on event deletion

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#5230]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Booking -> Recurring -> Events Remaining not displaying the correct remaining events

### Steps to Reproduce

1. Create a recurring event
2. Go to Bookings -> Upcoming and delete an event from the beginning or middle of the recently created recurring event list.
3. Go back to Bookings -> Recurring -> under  "Events remaining" it deletes the event at the end of the list, but not the one that was actually deleted.

### Technical details

Self hosted on main branch V2.1.1

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by newz666** [comment]
Thank you @MatheusBeniniF . It got magically fixed to me as well this morning on our Self Hosted instance, even though I haven't updated it or anything.Thank you.

**Comment by newz666** [comment]
I still think that's a bug. It's displaying the wrong data at the creation, but it's getting fixed on it's own after 15 minutes. Can we please take a look at it one more time?

**Comment by melissamarvin** [comment]
Looks like it's still listing it in the tool tip in recurring, but the event is removed if you look in bookings --> upcoming.

https://user-images.githubusercontent.com/117048096/199064882-7e3190a5-df2c-4da8-9b7e-020fd9003634.mp4

**Comment by PeerRich** [comment]
@leog

**Comment by leog** [comment]
Will be fixed by #5253

**Comment by emrysal** [comment]
This should be fixed now 👍
