### ISSUE TITLE
[CAL-258] Upcoming recurring events list gets duplicated when cancelling and rescheduling events.

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#5232]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Upcoming recurring events list gets duplicated at the end of initial list, when cancelling and rescheduling events.

### Steps to Reproduce

1. Create a recurring event
2. See min 2.23 all event dates are displaying one day, and at 2.27 it's shifts all dates +1.
3. Reschedule an event (3.19), the list is displayed correctly.
4. Cancel the rescheduled event, the list still displays the right events.
5. Cancel another event 4.06 - scroll down and you'll see the events displayed the second time.

### Technical details

Adding video in slack

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@emrysal can you look into this?

**Comment by melissamarvin** [comment]
Was this one also fixed by toggling on Personal in Calendar?

**Comment by emrysal** [comment]
Hi @melissamarvin - I'll close this as I believe this is fixed but feel free to reopen if this is still an issue.
