### ISSUE TITLE
[CAL-259] /apps/installed/calendar: weird "add new" button

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5233]
[ec28d950-2a68-4071-b69b-4bbb9d56818d](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/49713e19-f462-49db-88a3-2dd027431f4c/ec28d950-2a68-4071-b69b-4bbb9d56818d)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MuriloAmarals** [comment]
Hey @G3root do you know how add calendar on localhost?

**Comment by Udit-takkar** [comment]
hey @G3root , @PeerRich  this has been fixed.
