### ISSUE TITLE
[CAL-547] SSO settings are interchanged

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5235]
### Issue Summary

Now I noticed that when I enable `HOSTED_CAL_FEATURES`, SSO is displayed in Security and not under Team. I suspect that is wrong with me.

### Steps to Reproduce

1. install cal.com self-hosted
2. set `HOSTED_CAL_FEATURES` to '1'
3. open settings and try sso

PR: https://github.com/calcom/cal.com/pull/4938#issuecomment-1282234708

<sub>[CAL-547](https://linear.app/calcom/issue/CAL-547/sso-settings-are-interchanged)</sub>

**Comment by devkiran** [comment]
@rene-mueller where did you set the value for `HOSTED_CAL_FEATURES`? Can you please double check `HOSTED_CAL_FEATURES` set on your environment?

**Comment by rene-mueller** [comment]
@devkiran yes I'll set the value `HOSTED_CAL_FEATURES` in my environment with the value '1': `HOSTED_CAL_FEATURES=1`

**Comment by rene-mueller** [comment]
@devkiran any Updates?

**Comment by PeerRich** [comment]
@deepakprabhakara @devkiran @zomars

**Comment by PeerRich** [comment]
wait, i think its right to do under security, no?

**Comment by devkiran** [comment]
@rene-mueller As i mentioned above, please confirm the env variable is set for `process.env.HOSTED_CAL_FEATURES`. Please do a `console.log(process.env.HOSTED_CAL_FEATURES)` and see it has a value.

Instead you can update `export const HOSTED_CAL_FEATURES=1` https://github.com/calcom/cal.com/blob/b3ba89c074d5862887a204931f5fe16aa2bf936b/packages/lib/constants.ts#L25

**Comment by devkiran** [comment]
@PeerRich Yes, it is under the `Settings` > `Security` for self-hosted version.

**Comment by rene-mueller** [comment]
@devkiran i have now done further tests and found that when i set a value in HOSTED_CAL_FEATURES via the .env, the check does not work as desired. i have done some logging in a few places and the result is as follows:

To prevent errors when converting the number 1 to a boolean i have converted the value to a boolean in constants.ts:

![grafik](https://user-images.githubusercontent.com/48084558/201652271-b3d8aa66-5d48-4911-b12d-97a45d661d26.png)

as you can see, the value 1 is always set. additionally as you can see here, true is always set. in the screenshot you can also see that SSO is disabled for teams and only "general" is available.

Next, i have added some additional console.logs in SettingsLayout.tsx:

![grafik](https://user-images.githubusercontent.com/48084558/201653104-ff10e3e1-76be-41fc-a183-218622ef17ed.png)

here you can see the console.log in the if won't execute. nevertheless, the push into the tab is executed.

Last, I tested what happens when I swap the check in constants.ts with the current BASE_URL:

![grafik](https://user-images.githubusercontent.com/48084558/201654555-dd00df9e-e3e1-40a1-b9a1-0ee96b371032.png)

**Comment by rene-mueller** [comment]
@devkiran any updates?

**Comment by rene-mueller** [comment]
@PeerRich @zomars can you have a look for the problem or reassign it?

**Comment by rene-mueller** [comment]
@PeerRich any updates?

**Comment by zomars** [comment]
@G3root do you have bandwidth to check on this?

**Comment by G3root** [comment]
> @G3root do you have bandwidth to check on this?

Yeah , Happy to look into this
