### ISSUE TITLE
[CAL-263] First load is slow (cold boot maybe?)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5239]
Hey guys - I must be doing sth wrong. ~I have cal setup on vercel, and it’s crazily slow.~

Edit by @PeerRich: not vercel specific

• first loading of the availabilities
• then the form UI to go through the booking
is that happening for you as well? What can I do?

Thanks!

Example here: [https://meet.tocco.earth/baptistedebever/30min](https://meet.tocco.earth/baptistedebever/30min)

> From [Linear-GitHub Sync](https://synclinear.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-263](https://linear.app/calcom/issue/CAL-263/first-load-is-slow-cold-boot-maybe)</sub>

**Comment by PeerRich** [comment]
just to let everyone know, we have a special ops team looking into this

**Comment by zomars** [comment]
I'll post here some findings:
- https://github.com/prisma/prisma/issues/4972
- https://github.com/prisma/prisma/issues/14691
- https://github.com/prisma/prisma/issues/11266

Stil investigating...

**Comment by keithwillcode** [comment]
Update on this: our team has been in discussions with folks from Vercel and they were able to determine that the next-auth-options import, which happens in many places, is causing major delays. 

In terms of next steps, we're going to get that resolved and also investigate installing and running cal.com on many different cloud providers that do not use serverless technology.
