### ISSUE TITLE
[CAL-272] Cannot pre-fill using ?location query param anymore

### ISSUE THREAD

**Issue by davidknezic** [calcom/cal.com#5244]
### Issue Summary

I honestly don't know if this was possible accidentally or if there was proper support for it, but we used to add the `?location=` query param to our event links so we could pre-fill individual on-boarding URLs per customer. We just recently upgraded from an old self-hosted [cal.com](http://cal.com) version (from around March this year) to the most recent one. Since then, pre-filling the location doesn't work anymore.

### Steps to Reproduce

1. Append `?location=https://example.com` to your event page
2. Book
3. Location is either the statically pre-configured one or empty (if no location was pre-configured)

### Technical details

* [cal.com](http://cal.com) version 352ce35b40cc68b3d7830619198e78e58946c259
* bundled with [github.com/calcom/docker](https://github.com/calcom/docker)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
this looks like something we should do

**Comment by G3root** [comment]
hey @PeerRich , i'd like to take on this issue

**Comment by G3root** [comment]
hi @PeerRich can you elaborate more on this. if the location query param exist, does it have to be the default value on the location input field or should post query param rather than location saved on the DB, while form submission ?

**Comment by PeerRich** [comment]
if there is a location query it should replace it

**Comment by PeerRich** [comment]
@G3root has this been addressed?
