### ISSUE TITLE
[CAL-275] issue with embed

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5257]
Here is a gif of the flow.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by harshsinghatz** [comment]
@PeerRich can you give more info on this?

**Comment by Udit-takkar** [comment]
@matheusmuniz03 @harshsinghatz  here https://calendso.slack.com/archives/C01NXDSRY9W/p1661206658357059?thread_ts=1661168659.369119&cid=C01NXDSRY9W it's reported from slack

**Comment by Udit-takkar** [comment]
just check once if it has been fixed or not

**Comment by hariombalhara** [comment]
THis isn't an embed related issue and is probably fixed a long time back already.
