### ISSUE TITLE
CSFR Token issue with migrated instance/LogIn not possible

### ISSUE THREAD

**Issue by Procuria** [calcom/cal.com#526]
### Issue Summary
I created a calendso-instance with the domain name _abc.domain.tld_ on a server with the IP _1.2.3.4_ 
I set up a Let's encrypt certificate for _abc.domain.tld_ with certbot.
I set up a NGINX reverse proxy with OCSP Stapling and HSTS.
Everything worked flawless.
Whenever I create the instance with  _abc.domain.tld_ on another IP _5.6.7.8_ I get an error message regarding the CSFR-token and can't log in, although I use an exact copy of all the config files (despite of the IP's of course ;) ) on the instance _5.6.7.8_
The only other difference is that I created a new SSL-Cert but for the same  _abc.domain.tld_
This happened now 3 times. 
I cleared all Browser Cookies etc. but nothing worked out.

As soon as I choose  a new name for the service, let's say _xyz.domain.tld_ and adjust everything accordingly to this name it works flawlessly again.
Could you point me into direction what I am missing or doing wrong here?
Unfortunately I can provide the exact error not now but will add this as soon as possible.

### Steps to Reproduce
1. Setup working instance
2. Setup new working instance on another IP and reroute DNS to it 
3. Get strange CSFR Token errors and can't login. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
The same behaviour goes for profile pictures. 

### Technical details
* Chrome, Firefox, Edge, Opera, Brave - all latest
* node.js from LTS Fermium to latest
* NGINX reverse proxy with OCSP Stapling and HSTS configured
*Let's Encrypt Certificate generated with certbot 

Thanks again for your awesome work on this project!

**Comment by PeerRich** [comment]
@Procuria can you try again? a lot has changed. will reopen if issue persists
