### ISSUE TITLE
[CAL-276] Changing the time zone on the booking page shifts to wrong date

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#5260]
[https://app.birdeatsbug.com/sessions/kVsA1IF7MBAGItYt7ruRzhCFCW_6ijkJ0vcmd_SwJV3k](https://app.birdeatsbug.com/sessions/kVsA1IF7MBAGItYt7ruRzhCFCW_6ijkJ0vcmd_SwJV3k)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by MuriloAmarals** [comment]
Hey @milospuac this bis bug is no ocurring
https://www.loom.com/share/4f720e17c510474fbb2c970e09f1084f

**Comment by MuriloAmarals** [comment]
I also tested with closer time zones.

**Comment by milospuac** [comment]
@MuriloAmarals thanks for looking into it. Are you by any chance self-hosting?

**Comment by milospuac** [comment]
@MuriloAmarals Tested it a bit more and it looks like it's only happening after I switch to the time zone that is at least one hour ahead of me.  So it's working for every time zone in GMT -X but as soon as I switch from GMT+2 to GMT +3-4-5 etc, it shows the wrong date.

**Comment by MuriloAmarals** [comment]
https://www.loom.com/share/4bc0956584d0489a9ac620ca8369cf70

**Comment by MuriloAmarals** [comment]
bizarre bug, only happens when you move ahead.

**Comment by emrysal** [comment]
@MuriloAmarals - fixed in attached PR - thank you for being observant. Bit of an explanation to why it was happening too in the PR.
