### ISSUE TITLE
[CAL-277] Setting up 2FA does not toggle to "enabled" until page is refreshed.

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#5262]
Expected behaviour is that 2FA is toggled enabled as soon as you finish setting up with the Authenticator app.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Thiagomn1** [comment]
Hey @emrysal i tried reproducing this issue but it seems to be working as expected already, check out this loom:
https://www.loom.com/share/0986e1e468a9453cba067915835be3a9
