### ISSUE TITLE
[CAL-278] MS Edge browser doesn't show correctly the information for months but other browser do

### ISSUE THREAD

**Issue by antoniolocandro** [calcom/cal.com#5264]
I open my calendar in MS Edge and this is what is showing up

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/996c2c89-7876-4c33-b8e4-57af19aa6c73/e82a2ebd-1b01-4179-adb3-eaece47677ca)

If I open with Opera it works fine

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/638bd760-6c14-47e3-8a61-d53360e23916/8e32fb77-6801-4fdf-a189-a8043d9227ea)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by jjromary** [comment]
Hei @antoniolocandro This working for me

![image](https://user-images.githubusercontent.com/37199044/200056691-ddc13b30-7183-49bd-8ab2-614ff8c7648d.png)

**Comment by PeerRich** [comment]
@emrysal saw this earlier

**Comment by PeerRich** [comment]
should be fixed now

**Comment by PeerRich** [comment]
try again @antoniolocandro

**Comment by emrysal** [comment]
@antoniolocandro We've now launched our complete revamp of the new booker - I expect this to have fixed the issue but if you are still experiencing this we'll pick this up with urgency as there's now a higher focus on stability.
