### ISSUE TITLE
It creates an event on top of another event

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#5267]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I create a one time regular event. Then I selected a recurring event-type and I was able to book on top of the already booked time.

### Steps to Reproduce

1. Select a time slot in a single session event-type.
2. Select a recurring event type, and select the same time as on previous step
3. Two events are being created on the same time and date.

![Screenshot from 2022-10-28 15-45-14](https://user-images.githubusercontent.com/74431325/198906054-9d13ef75-881d-4b4d-a510-c04c20725bf3.png)

### Technical details

Self Hosted v.2.1.1-sh-pro on main branch

**Comment by newz666** [comment]
[Screencast from 10-30-2022 09:22:57 PM.webm](https://user-images.githubusercontent.com/74431325/198913345-7430a65d-f580-4829-849a-d30b4c4e7298.webm)

**Comment by newz666** [comment]
We went to Settings -> Calendar -> toggled on Person , which fixed the issue
![Screenshot from 2022-10-30 21-33-25](https://user-images.githubusercontent.com/74431325/198916228-623ce58a-bcfc-4da6-9409-23177840d135.png)

**Comment by Udit-takkar** [comment]
@newz666 yes the toggle prevents double bookings.
