### ISSUE TITLE
Even when Weekly Limit is reached, week is still shown as available

### ISSUE THREAD

**Issue by 3699n** [calcom/cal.com#5268]
### Issue Summary

- I set my Event Type to have a weekly booking limit of 5. Even when I have 5 sessions booked in a week, all the days in the week are still being show as available on my link. Only when the user then tries to book another sessions during that week do they receive an unclear error message.
- This does not seem to be a browser issue, as many of my clients have been reporting this issue to me.
- Instead of showing the user an error message when they try to book, I would instead expect Cal.com to just mark the days in a week unavailable, if the booking limit for that week has been reached. 
- 
![image](https://user-images.githubusercontent.com/7414843/198720402-a4af7dae-5346-4a32-9b46-bbbbe212502d.png)

### Technical details

Using the official Cal.com instance on the pro plan.

**Comment by PeerRich** [comment]
Agree. it should hide the week and not throw an error

**Comment by PeerRich** [comment]
@Udit-takkar can you investigate this?

**Comment by Udit-takkar** [comment]
@PeerRich booking limits are working fine. ( tested daily, weekly ). just one minor issue https://github.com/calcom/cal.com/pull/6720

**Comment by PeerRich** [comment]
does it hide the week?

**Comment by Udit-takkar** [comment]
Yes
