### ISSUE TITLE
User located on EST impersonating a cal user on PT time booking outside the available time

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#5270]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

User located on EST impersonating a cal user on PT time booking outside the available time
### Steps to Reproduce

1. A user on EST impersonated a cal host on PT time
2. The cal host availability for the day was 9 am 5 pm PT
3. The user that impersonated the user created a booking (user the impersonated is located in EST) for 4pm PT / 7pm EST.
4. The event got created at 7pm PT / 10pm EST - which is outside the availability and it's displaying incorrect.  

![Screenshot from 2022-10-28 17-54-54](https://user-images.githubusercontent.com/74431325/198905981-8d47ccbf-aa47-494a-8414-9686b50960a4.png)

![Screenshot from 2022-10-28 17-38-56](https://user-images.githubusercontent.com/74431325/198905968-c67cc1c4-391d-4fec-ab0f-defab27484f6.png)

**Comment by melissamarvin** [comment]
This one seems like it's the same bug as https://github.com/calcom/cal.com/issues/5271

**Comment by PeerRich** [comment]
duplicate
