### ISSUE TITLE
[CAL-294] In the availability the Working Hours are being displayed in standard time and below they are displayed in military time

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#5272]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In the availability the Working Hours are being displayed in standard time and below they are displayed in military time

### Steps to Reproduce

1. After a user located in EST impersonated a user in PT, the availability Working Hours were displayed in standard time as set before, while below they switched to Military time

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d310b83d-9f6b-40e5-8f51-c27916b198e0/2f4b2c18-5673-47e5-92e9-ee64e1f49290)

### Technical details

Self Hosted Maine branch v2.1.1

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by melissamarvin** [comment]
User did not set clock to 24 hours.  

I did however, and this is the bug I see.  The upper times under working hours are in 12 hour and the start and end times of the day are in 24.  

![2022-10-30_20-54-44](https://user-images.githubusercontent.com/117048096/198917108-8985957a-fd28-442b-a788-3ffbd747ee2a.png)

**Comment by melissamarvin** [comment]
We may have two issues, unsure.  The first is that the clock is getting changed after an impersonation; the 2nd is the mix of time stamps on the page.  If these are two bugs, they need to be separated.  Thoughts?

**Comment by PeerRich** [comment]
yeah please edit this issue and open a new one 🙏

**Comment by PeerRich** [comment]
@Udit-takkar @JeroenReumkens wanna look into tis?

**Comment by Udit-takkar** [comment]
sure

**Comment by melissamarvin** [comment]
Changing to the 24 hour clock on impersonation is still occurring.

**Comment by Udit-takkar** [comment]
@melissamarvin ok, will also fix this

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2022-11-07 at 9 14 51 PM" src="https://user-images.githubusercontent.com/53316345/200352755-36b9a584-2079-4bc8-b576-81d906983e88.png">

@melissamarvin  i tried reproducing this and for me after impersonating the clock did not changed to 24 hour.

**Comment by Udit-takkar** [comment]
here's what i did
- Admin account had clock set to 24-hour, while trial example account uses 12-hour clock
- after impersonating the clock did not changed.

**Comment by Udit-takkar** [comment]
any update @melissamarvin  are you still facing this issue or should i close this ticket ?

**Comment by PeerRich** [comment]
@tedspare we still have broken screenshots in linear, see here

**Comment by Udit-takkar** [comment]
I'm closing this because there hasn't been any activity and I can't reproduce the problem.
