### ISSUE TITLE
Confirming & Canceling Recurring Appointments Fails to Sync to Google Calendar on All But First Occurrence

### ISSUE THREAD

**Issue by brianclements** [calcom/cal.com#5273]
### Issue Summary

Using "Confirm all" and "Cancel All" buttons for recurring events only synchronizes the first instance of that event to google calendar.

### Steps to Reproduce

1. Book a recurring appointment that needs confirmation
2. Confirm using the "Confirm All" button in the "Bookings" section
3. Check that all appointments in the "Bookings" section are there as expected
4. Go to synced google calendar and only find the first instance of that recurring event is there.

To bypass this:
1. On the same event type above, uncheck "Requires confirmation"
2. Book a recurring appointment
3. Find all events syncing to google calendar

But, now we have the same behavior with "canceling" recurring events. While you can cancel individual events, if you try to "Cancel all remaining" from the "Recurring" section of Bookings, you'll notice it only effects the first instance.

1. Book a recurring appointment that **does not** need confirmation
2. Check that all appointments in the "Bookings" section are there as expected
4. Check that all have synced to google calendar
5. Now try to "Cancel all remaining" from the Bookings/Recurring section
6. Find that only the first instance is canceled and synchronized to google calendar.

### Technical details

Using Cal.com v.2.1.1-h-PRO

**Comment by PeerRich** [comment]
@leog

**Comment by leog** [comment]
> @leog 

This should be already fixed.

**Comment by brianclements** [comment]
This is still an issue for me. Exact same behavior using the exact same steps.
