### ISSUE TITLE
[CAL-285] Custom Workflow Become Empty after save.

### ISSUE THREAD

**Issue by lawweiliang** [calcom/cal.com#5274]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Type something over custom workflow, then clicked save, Then, all the data that you enter are gone.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/951098df-02a2-453a-bd8a-ffdf21b95219/6e99c912-9fdd-45d0-b352-0ee35075af9e)

### Steps to Reproduce

1. Add data over custom message
2. Clicked Save

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by harshsinghatz** [comment]
Is this still an issue because it works fine on my end!

**Comment by PeerRich** [comment]
@CarinaWolli can you test?

**Comment by CarinaWolli** [comment]
It also works fine for me. I tested it in production and locally

**Comment by lawweiliang** [comment]
Hi Everyone, thanks for all your fast response.  
This weekend I take sometime to record a youtube video on the problem and send it to your.

Put this problem on-hold first yeah.

**Comment by CarinaWolli** [comment]
@lawweiliang Did you experience this in production or locally? I did some more tests and in production everything still works as expected, but I had some weird behavior locally that I can not reproduce in production

**Comment by lawweiliang** [comment]
@CarinaWolli 
I experience this in production. I try to customize the message for re-schedule workflow. When I type in the message and clicked save button. All my message gone, that why I open this issue.

Another difficulty that I found when I create the custom message is I don't know what global variable name I can use. 
I do look around the documentation, could not find a clear list for that. I might open a new issue regarding this.

**Comment by lawweiliang** [comment]
Hi @CarinaWolli ,
Here is the video that demo the problems. Feel free to take a look.
https://www.youtube.com/watch?v=EDlTVzx5BA4

Hope it's help. 😄

**Comment by lawweiliang** [comment]
@PeerRich,

Would like to what standard did you use to re-name the issue? Why have to add [CAL-285] over the title?

Reason why I want to know is
Next time I use your standard to name the issue.

**Comment by PeerRich** [comment]
the title comes from our linear sync when we add the "linear" ticket

**Comment by PeerRich** [comment]
@CarinaWolli will look into it tomorrow, she is OOO today
