### ISSUE TITLE
[CAL-281] 10 seconds load time for availability

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5277]
FWIW I'm having a similar issue using the embed on my wordpress site I'm creating. Response times for [https://app.cal.com/api/trpc/viewer.public.slots.getSchedule?batch=1&input=%7B%220\[…\]999Z%22%2C%22timeZone%22%3A%22America%2FLos_Angeles%22%7D%7D%7D](https://app.cal.com/api/trpc/viewer.public.slots.getSchedule?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22eventTypeId%22%3A86558%2C%22eventTypeSlug%22%3A%2220min%22%2C%22usernameList%22%3A%5B%22birdspringfinancial%22%5D%2C%22startTime%22%3A%222022-10-01T07%3A00%3A00.000Z%22%2C%22endTime%22%3A%222022-11-01T06%3A59%3A59.999Z%22%2C%22timeZone%22%3A%22America%2FLos_Angeles%22%7D%7D%7D) have taken 10 seconds plus for my October availability. I've seen as slow as 25 seconds

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by jacksonblankenship** [comment]
We started playing with Cal.com today (currently assessing a move from Calendly) and we've noticed slow load times already, too.

**Comment by Tom-Potanski** [comment]
We also experience this. A lot.

**Comment by hjwgarcia** [comment]
This has been an issue for us, and it is compounded for team calendars, as it takes increasingly more time to get the calendar for each person.

**Comment by keithwillcode** [comment]
@PeerRich Can you try loading this tRPC endpoint again. Note that it moved to `/api/trpc/public/slots.getSchedule`.

**Comment by emrysal** [comment]
@keithwillcode Occassionally this can still take long for very big team events, e.g. 30 members in round-robin.
