### ISSUE TITLE
[CAL-283] broken kbar links

### ISSUE THREAD

**Issue by philippdormann** [calcom/cal.com#5280]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

multiple kbar links are currently broken

### Steps to Reproduce

1. open kbar
2. Click on `API Keys`
3. land on a broken page, not even a 404

(should load `https://app.cal.com/settings/developer/api-keys`, actually links to `https://app.cal.com/settings/developer`)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@alishaz-polymath this wasnt moved in the v2 migration

**Comment by PeerRich** [comment]
@Udit-takkar you could also pick this

**Comment by Udit-takkar** [comment]
@PeerRich  👍

**Comment by philippdormann** [comment]
cool, good job 🙌
