### ISSUE TITLE
[CAL-284] Unable to upload Avatar on Self-Hosted

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5281]
### Discussed in [https://github.com/calcom/cal.com/discussions/5164](https://github.com/calcom/cal.com/discussions/5164)

<div type='discussions-op-text'>

<sup>Originally posted by **Javihache** October 21, 2022</sup>
Hi guys,

deployed on 500GB free disk space VPS running Ubuntu 22.04. Everything seems to work fine, but I am unable to upload Avatars. I upload it, when I click update on the user or team... poof! the avatar disappears. Is there some format/size constraint that I am missing?</div>

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Udit-takkar** [comment]
similar https://github.com/calcom/cal.com/issues/5275
