### ISSUE TITLE
[CAL-287] Create top banner component

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5287]
[Top banner - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=21311%3A144646)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
nice!

**Comment by PeerRich** [comment]
tagging #5578 here
