### ISSUE TITLE
[CAL-291] Username issue

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5297]
Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=23d2c08d-ef47-4519-971b-b711aae3d1fd](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=23d2c08d-ef47-4519-971b-b711aae3d1fd)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment]
@alex
