### ISSUE TITLE
Embed crashes if a previous booking has been made.

### ISSUE THREAD

**Issue by sradu** [calcom/cal.com#5305]
Using the react embed I book a meeting. I refresh the page and click 'book a meeting' again. I would expect for it to tell me that I have already have a booking.

Instead it allows to me to go through the flow and at a certain points returns this.

<img width="1536" alt="Screen Shot 2022-10-31 at 11 29 56 AM" src="https://user-images.githubusercontent.com/82214/199083485-92ca0286-d03d-4999-9a16-90ddff7579af.png">

**Comment by PeerRich** [comment]
hey @hariombalhara can you check this?

**Comment by hariombalhara** [comment]
This isn't related to embed and I think it should not be an issue right now.
