### ISSUE TITLE
[CAL-295] reorder fails

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5308]
[https://www.loom.com/share/35ef84cc72b2499a8f3be92baa9b625f](https://www.loom.com/share/35ef84cc72b2499a8f3be92baa9b625f)

Created via Threads. See full discussion: [https://threads.com/34432217390](https://threads.com/34432217390)

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
@alex test

**Comment by Udit-takkar** [comment]
fixed on main https://github.com/calcom/cal.com/pull/5291
