### ISSUE TITLE
[CAL-296] iCalendar timezone is off (doubles) CalDAV

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#5309]
iCalendar timezone is off and doubles for some people. This suggests that often (but apparently not always) the calendar object has the from/to time in the correct timezone, causing the timezone update to be an extra one.

> From [SyncLinear.com](https://synclinear.com)

**Comment by noxan** [comment]
Can confirm the issue, a lot of my events are in the middle of the night apparently 😅
