### ISSUE TITLE
[CAL-297] Settings not being saved

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5313]
[https://www.loom.com/share/41b653398888484cb47611a780319b15](https://www.loom.com/share/41b653398888484cb47611a780319b15)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/199227318-c8a3ae43-4460-4842-a445-ce33290072ef.mov

@Jaibles  not able to reproduce. tried on both main and prod.

**Comment by PeerRich** [comment]
@Udit-takkar can you reinvestigate? I think it has been fixed but just in case

**Comment by Udit-takkar** [comment]
@PeerRich  setting being saved is working fine but sometimes when you switch tabs and return back to same tab then new changes are not reflected without refreshing. i am refactoring setting to use trpc instead of getServerSideprops here https://github.com/calcom/cal.com/pull/5959.

**Comment by leog** [comment]
Can't repro either, closing.
