### ISSUE TITLE
[CAL-298] Select component needs updating to 2.0

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5315]
This is still very much a v1 component.

![CleanShot 2022-11-01 at 11.46.47.gif](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b01e79ac-a1b4-4c13-8ce3-fe8ef66921f7/9f3f41b1-b6da-49ca-97c8-090a3792b4bb)

[Dropdown Menu Brief - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=385%3A33491)

The border colour, radius doesn't match v2 designs.

> From [SyncLinear.com](https://synclinear.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-298](https://linear.app/calcom/issue/CAL-298/select-component-needs-updating-to-20)</sub>

**Comment by Jaibles** [comment]
I'll have to take another look but to me it looks like this component has v1 colours and border radius 🤔

**Comment by MatheusBeniniF** [comment]
@Jaibles, updates on that?

**Comment by MatheusBeniniF** [comment]
updates on that?

**Comment by Jaibles** [comment]
There's been some discussion on the team about this. @sean-brydon care to translate the update 😂? I'm not sure I'd do a great job of explaining the outcome.

**Comment by MatheusBeniniF** [comment]
can I do that?

**Comment by Jaibles** [comment]
I've no objections! If you hit any issues or questions reach out to @sean-brydon perhaps. He's looked into this a little bit I know and warned me that it's perhaps not a task that's as easy as it looks :)
