### ISSUE TITLE
[CAL-299] Calendar dropdown has partial dark mode while it shouldn't

### ISSUE THREAD

**Issue by JeroenReumkens** [calcom/cal.com#5317]
[https://www.loom.com/share/ccefdf948db642ad8b692549a3304190](https://www.loom.com/share/ccefdf948db642ad8b692549a3304190)

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
also [CAL-300](https://linear.app/calcom/issue/CAL-300/event-types-advanced-settings-show-default-calendar-and-not-the-first) related. it should not say "Default Calendar ()"

**Comment by gGh00sTt** [comment]
@PeerRich, I am unable to replicate the issue. Is it already fixed?

**Comment by JeroenReumkens** [comment]
Yes you're right @gGh00sTt  this has been fixed. Thanks for checking though 🙏
