### ISSUE TITLE
[CAL-300] /event-types: advanced settings show "Default calendar()" and not the first entry

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5320]
![CleanShot 2022-11-01 at 13.45.20@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/44c09a89-ac6a-4e7d-86bf-b56e87a2068b/1dfec7e9-846c-439f-bee8-f151ebce52b6)

this should by default take the first calendar

(sorry for the potato quality, screengrabbed this from a loom)

> From [SyncLinear.com](https://synclinear.com)

**Comment by MatheusBeniniF** [comment]
@PeerRich, how can I add this label? here it is like this
![image](https://user-images.githubusercontent.com/88898100/199254657-2ce87a03-f467-463b-9066-4415ff863bab.png)

**Comment by PeerRich** [comment]
i think you need a google calendar first, no? @baileypumfleet

**Comment by baileypumfleet** [comment]
Yes, that's correct
