### ISSUE TITLE
[CAL-302] Installed Apps / Automation / Zapier - Zaps UI Issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5324]
Currently there's a few differences from the Figma designs including

* Designs use a background behind the Zaps
* There should be no border around the logos
* The **Use Zap** button should be on a new line

Current

![CleanShot 2022-11-01 at 15.57.51@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e398b30c-140f-41d8-86e8-a35800f609ba/1a7a060f-44d0-42dd-928f-acaacfd5b531)

Should be

![CleanShot 2022-11-01 at 15.58.40@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/94996474-6c78-44a4-9fe6-3b5489e3ff4c/0ceea40e-25ef-4674-b4d0-a821bf5fab7f)

View in Figma

[App Store / Installed Apps / Workflow automation - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=161%3A96057)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Jaibles** [comment]
@PeerRich I'd envisaged settings going in a modal more so than being displayed here. 

Proposal:

![CleanShot 2022-11-01 at 16.39.12@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/70c181aa-fc02-4579-a8f4-322b0a47a8ed/a2a7df32-9bcd-4afe-993e-a08a3ede06c7)

Which apps currently have settings so I can check/test and see.

**Comment by PeerRich** [comment]
> @PeerRich I'd envisaged settings going in a modal more so than being displayed here.
> 
> Proposal:
> 
> ![CleanShot 2022-11-01 at 16.39.12@2x.png](https://camo.githubusercontent.com/0c34af89951c38c13166f6d50410dac551ca2cdd37583a3b52ed1573e21ca793/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f37306331383161612d666330322d343537392d613866342d3332326230613437613865642f61326137646633322d396263642d346166652d393933652d613038613365646530366337)
> 
> Which apps currently have settings so I can check/test and see.

that makes sense

**Comment by om-ray** [comment]
@PeerRich @Jaibles If you want this fixed, I'd love to work on this issue!

**Comment by Jaibles** [comment]
Yes please @om-ray 🙏

**Comment by om-ray** [comment]
@Jaibles Great I'll start on it asap!

**Comment by om-ray** [comment]
@Jaibles @PeerRich Please review the PR!

**Comment by Jaibles** [comment]
What I can see in your screenshot looks great.
