### ISSUE TITLE
[CAL-304] Booking Page Event Location Bad Link

### ISSUE THREAD

**Issue by wei** [calcom/cal.com#5327]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On the booking page, Zoom Video contains a bad link in the href.

### Steps to Reproduce

1. Go to a booking page of an event set up with Zoom Video.
2. Observe that the href is "Zoom Video" which is not a valid link.

<img width="225" alt="image" src="[https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png](https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png)">
<img width="974" alt="image" src="[https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png](https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png)">

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
  Chrome
* Node.js version
  N/A
* Anything else that you think could be an issue.
  [https://github.com/calcom/cal.com/blob/edabf27929beb5f6d53926fcb3780a014e52f7d8/apps/web/components/booking/AvailableEventLocations.tsx#L27-L29](https://github.com/calcom/cal.com/blob/edabf27929beb5f6d53926fcb3780a014e52f7d8/apps/web/components/booking/AvailableEventLocations.tsx#L27-L29)
  L29 is the root cause.

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
thank you! added to roadmap

**Comment by wei** [comment]
Looks like there is a bug with SyncLinear the edits it made caused the screenshots I attached to break. 😅 

<img width="659" alt="image" src="https://user-images.githubusercontent.com/5880908/199487955-d10a633c-9963-4ab2-adde-9dc77129dee5.png">

It converted

```html
<img width="225" alt="image" src="https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png">
<img width="974" alt="image" src="https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png">
```

to

```html
<img width="225" alt="image" src="[https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png](https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png)">
<img width="974" alt="image" src="[https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png](https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png)">
```

**Comment by PeerRich** [comment]
> Looks like there is a bug with SyncLinear the edits it made broke the screenshots. 😅
> 
> <img alt="image" width="650" src="https://user-images.githubusercontent.com/5880908/199487955-d10a633c-9963-4ab2-adde-9dc77129dee5.png">
> 
> It converted
> 
> ```
> <img width="225" alt="image" src="https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png">
> <img width="974" alt="image" src="https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png">
> ```
> 
> to
> 
> ```
> <img width="225" alt="image" src="[https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png](https://user-images.githubusercontent.com/5880908/199403607-81c13804-af82-4b09-ae11-307bf97a651d.png)">
> <img width="974" alt="image" src="[https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png](https://user-images.githubusercontent.com/5880908/199403124-4cbf434b-b6b6-4a07-aa8d-16835e79c210.png)">
> ```

ah right, opened a ticket in synclinear github repo

**Comment by G3root** [comment]
@PeerRich where should the link point out ?

**Comment by PeerRich** [comment]
> @PeerRich where should the link point out ?

I think we should have no link there at all. just remove the link
