### ISSUE TITLE
Introduce availability override / Allow adding events manually

### ISSUE THREAD

**Issue by LoveIsGrief** [calcom/cal.com#5335]
### Is your proposal related to a problem?

I would like to make myself unvailable for just one time segment on a specific day.
Right now I have to visit my link and add a few events with fake emails. Especially for longer unavailability e.g half day, then that requires adding 8 events for the 30 sections.

This is also related to a bug where using another invite link e.g https://cal.com/somebody/4hours instead of https://cal.com/somebody/30min will create an event, but https://cal.com/somebody/30min will still show those time slots as available (maybe related to #2342).

### Describe the solution you'd like

Please provide a simple way to override availability for a single day by showing the calendar and resizing an individual availability.

### Describe alternatives you've considered

An "admin" view of the calendar that allows simply creating events there (like a normal calendar).

**Comment by PeerRich** [comment]
@emrysal thoughts?

**Comment by PeerRich** [comment]
@emrysal is currently working on it

**Comment by PeerRich** [comment]
see https://github.com/calcom/cal.com/pull/6538

**Comment by emrysal** [comment]
Closing as done
