### ISSUE TITLE
[CAL-308] Success page always shows the additional notes of the first seat

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#5338]
When booking the second (or more) seat of an event the additional notes of the first seat is shown, this happens also when **Hide notes in calendar** is selected and has the potential to leak confidential information of the first seat member.

> From [SyncLinear.com](https://synclinear.com)

**Comment by om-ray** [comment]
@emrysal @PeerRich I'd love to work on this!

**Comment by alannnc** [comment]
@om-ray Sorry I forgot to assign myself but I already have something for this.

**Comment by alannnc** [comment]
You can help me review it @om-ray.
