### ISSUE TITLE
[CAL-309] Rescheduling shows emails of other attendees when they should be hidden.

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#5339]
When rescheduling to different events, I am able to see the emails of all other attendees, regardless of the **Share attendee information between guests** setting.

Desired behaviour: The emails of other guests should not be shown when rescheduling an event when the **Share attendee information between guests** setting isn't enabled.

> From [SyncLinear.com](https://synclinear.com)

**Comment by om-ray** [comment]
@PeerRich @emrysal This issue was fixed by PR #5361

**Comment by alannnc** [comment]
You're right it's no longer happening.
