### ISSUE TITLE
[CAL-310] As an attendee I can't manage a multi-seat booking through my email if someone joined after me.

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#5340]
I am unable to reschedule a multi-seat event as the attendee if other people joined after me.

Cancellation results in "This booking is already cancelled" & Rescheduling action returns a 404

> From [SyncLinear.com](https://synclinear.com)

**Comment by alannnc** [comment]
Things to consider we should support.

- Individual seats status/info. Right now we lost any additionalDescription entered by user.
- Paid seats, reschedule them.
- When owner reschedule move entire attendees.
- When user reschedule only remove him from attendee and create new booking.

**Comment by alannnc** [comment]
Also found seats still count when booking is cancelled.
