### ISSUE TITLE
[CAL-311] When using seats, other guests (name, email) are always listed on the success page

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#5341]
Other guests should only be listed when "Share attendee information between guests" has been selected.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/1046695/199581174-f26ae106-e2e9-429a-8395-0b8299727ec8.png">

> From [SyncLinear.com](https://synclinear.com)

**Comment by om-ray** [comment]
@PeerRich If this is something you want fixed, I would love to work on this!

**Comment by PeerRich** [comment]
> @PeerRich If this is something you want to be fixed, I would love to work on this!

sure go for it @om-ray

**Comment by emrysal** [comment]
@om-ray For added context there is a setting that should power this in the eventType->Advanced tab: **Share attendee information between guests**. If this setting is toggled it should show everyone's email in the success page, if not it shouldn't. 🙏 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1046695/199747761-03aa9a9b-dcd1-467b-938e-d91473614c95.png">

**Comment by om-ray** [comment]
@PeerRich Could you assign this issue to me?

**Comment by alannnc** [comment]
I'm already investigating other seats related bugs, if you beat me to this do let me know so I can review it. @om-ray

**Comment by om-ray** [comment]
@alannnc Sure! I'll let you know when I finish

**Comment by om-ray** [comment]
@alannnc I've fixed the issue! It was just an extra `not` operator in the ternary!
