### ISSUE TITLE
Add: notifications section to get all the user/team related notifications directly on the app

### ISSUE THREAD

**Issue by harshsinghatz** [calcom/cal.com#5346]
### Is your proposal related to a problem?

(Write your answer here.)
For eg: if i am inviting anyone to the team, the person i am inviting to gets an email with the joining link. But we can make it an in-house experience by adding a notifications section that will contain all the notifications related to a user/team

### Describe the solution you'd like
1. We can use web sockets to get real time updates on the notifications

**Comment by harshsinghatz** [comment]
I think this would be a big change and not an urgent one currently
I would love to work on this issue, can i pick this task with a longer deadline? 
@Jaibles @PeerRich

**Comment by harshsinghatz** [comment]
@PeerRich should I work on this?

**Comment by Jaibles** [comment]
I would like to first list what other things we can use notifications for and give this a bit more thought and likely design it first. Introducing notifications for 1 very occasional notification seems like potentially a big lift for a small win.

**Comment by harshsinghatz** [comment]
> I would like to first list what other things we can use notifications for and give this a bit more thought and likely design it first. Introducing notifications for 1 very occasional notification seems like potentially a big lift for a small win.
> 
> - Invited to a team
> - Booking request awaiting response (for opt-in booking) (we are already surfacing this in Bookings area)

Yes, making the whole feature for only one use case seems like an over kill
Maybe we can take three or four use cases and then incrementally improve and keep adding more 
Would love if you can provide the design and some other use cases as well

**Comment by harshsinghatz** [comment]
@Jaibles updates on this?

**Comment by PeerRich** [comment]
we'll put this on the backburner, maybe Q1 or Q2
