### ISSUE TITLE
Availability Override

### ISSUE THREAD

**Issue by onecallcloser** [calcom/cal.com#5352]
Currently can't override and block out my availability when last minute things pop up.

There should be an override feature like in calendly.

**Comment by PeerRich** [comment]
@emrysal is working on it and it should go live in the next 15 days

**Comment by PeerRich** [comment]
#4614

**Comment by emrysal** [comment]
Hi @onecallcloser so this has been implemented for a while already - Closing this but we're also rolling out a feature soon that will allow overriding any day, where as currently you can only override existing working hours.
