### ISSUE TITLE
Stripe Payment Integration and UPI

### ISSUE THREAD

**Issue by TPAteeq** [calcom/cal.com#5354]
I wanted to integrate stripe payments with my bookings but the payment only accepts cards, it would be great if it also accepted other popular methods such as net banking or UPI for India.

**Comment by PeerRich** [comment]
does Stripe offer UPI? for now we only offer Stripe,  but we can add more payment options.

it's been on my mind for a while, I also wanna offer Lightning Network payments

**Comment by Kfelts** [comment]
Additionally, profession specific processors like Lawpay (Affinipay) would be a huge draw from the legal network. Since it handles IOLTA requirements for us, it avoids compliance issues that we face with Stripe and other non-compliant platforms.

**Comment by PeerRich** [comment]
can you raise a feature request for lawpay? @Kfelts cal.com/feature

**Comment by TPAteeq** [comment]
Hi,
Thanks for replying to my emails and clearing my doubts.
I also would like to know if there is an api call I can make to confirm a
booking using my application instead of having to do it manually from the
dashboard.

**Comment by PeerRich** [comment]
yes, there is an endpoint to confirm bookings. lemme pull in @alishaz-polymath for docs

**Comment by TPAteeq** [comment]
That would be great.

**Comment by alishaz-polymath** [comment]
@TPAteeq So currently we don't allow confirming bookings from what I can see (I would need to re-confirm), but I have raised a request for this nonetheless and I believe the support should be added very soon (potentially in a day or two) unless there's a reason I'm not currently aware of. I will post here again once I have the confirmation on how to confirm a booking using the API. To clarify, we have the endpoint in place that should allow it, but it is simply disabled currently.

**Comment by TPAteeq** [comment]
Alright thanks

**Comment by PeerRich** [comment]
@alannnc woudl the new payment flow allow UPI?
