### ISSUE TITLE
[CAL-315] Certain timeZone situations can cause daysInMonth = 1 🤯 

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#5362]
Viewing from America/New_York

Traced the cause to a bug report in Dayjs:
[https://github.com/iamkun/dayjs/issues/1272](https://github.com/iamkun/dayjs/issues/1272)

<img width="879" alt="image" src="https://user-images.githubusercontent.com/1046695/199860834-7344c299-aca8-4093-8b46-6c94707874bb.png">

> From [SyncLinear.com](https://synclinear.com)

**Comment by JeroenReumkens** [comment]
@emrysal  How can I exactly reproduce this? The description isn't fully clear to me. Thanks 🙏
