### ISSUE TITLE
n8n trigger throws 404 error

### ISSUE THREAD

**Issue by dschuermann** [calcom/cal.com#5373]
### Issue Summary

I was creating a n8n workflow and added the cal trigger. The credential connection says "Connection tested successfully" but the actual "listen for event" results in a 404 error as shown on the screenshot's bottom right corner.

### Technical details

![Screenshot_20221104_144844](https://user-images.githubusercontent.com/321888/199988209-cac5ab4e-bf2c-45ba-82b6-2c5bba6d1c54.png)

**Comment by CarinaWolli** [comment]
@alishaz-polymath I saw that we are calling the `/hooks` endpoint in n8n but I think this got renamed to [`/webhooks`](https://github.com/calcom/api/tree/main/pages/api/webhooks) in our API. Not sure if this has anything to do with it, I didn't have enough time yet to look into our n8n code in detail

**Comment by PeerRich** [comment]
can someone test if n8n actually works? some community member I believe build it

**Comment by dschuermann** [comment]
just fyi: I am currently using cal.com wehooks directly in n8n and not using the cal trigger in n8n.

**Comment by alishaz-polymath** [comment]
Fixed in https://github.com/n8n-io/n8n/pull/5331#issuecomment-1463788936

**Comment by dschuermann** [comment]
:+1:
