### ISSUE TITLE
[CAL-318] If Apple Calendar is the default destination, Google Meet URL will not show in the confirmation

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#5377]
Tested this multiple times with the customer. They have Google Cal connected in order to use Google Meet.

With Apple calendar as the default destination 

![Screenshot 2022-11-04 at 16.08.46.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e2117c40-7e00-4107-8acd-679b28e2b8a0/df60990e-c96f-4f0d-aa92-b5fba7ef9bf7)

With Google Cal as destination 

![Screenshot 2022-11-04 at 16.02.58.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cfe4b224-bf23-4596-8637-335f0541b37b/427b04ec-b180-40a6-be5f-1740a25f45cd)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
duplicate https://github.com/calcom/cal.com/issues/5376

**Comment by PeerRich** [comment]
duplicate. please keep closed https://github.com/calcom/cal.com/issues/5376
