### ISSUE TITLE
[CAL-323] The recurring session scheduled midway (3 pm /Havana Time) rendered “Unexpected end of JSON input” 

### ISSUE THREAD

**Issue by melissamarvin** [calcom/cal.com#5385]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Json error when trying to schedule a recurring session.

### Steps to Reproduce

Cannot schedule recurring events

1. have user 1 use a recurring event that already existed (unsure if this matters)
2. have user 1 send the recurring session to another user
3. have user 2 click the recurring event
4. have user 2 select a time and date to schedule
5. click confirm

Notice you get a json error.  Note, I used an already existing recurring event when I originally found this.  When I created a new recurring event, the message was no available users have been found.  I think they're caused by the same issue, so I've combined these behaviors here.

### Technical details

Self hosted, main

> From [SyncLinear.com](https://synclinear.com)

**Comment by melissamarvin** [comment]
Version, because I didn't know what it was when I wrote the case.   v.2.1.2


melissamarvin opened this issue 18 hours ago · 0 comments
Comments
@melissamarvin
 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or teamReference an issue or pull request
Add saved reply
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Json error when trying to schedule a recurring session.

### Steps to Reproduce

Cannot schedule recurring events

1. have user 1 use a recurring event that already existed (unsure if this matters)
2. have user 1 send the recurring session to another user
3. have user 2 click the recurring event
4. have user 2 select a time and date to schedule
5. click confirm

Notice you get a json error.  Note, I used an already existing recurring event when I originally found this.  When I created a new recurring event, the message was no available users have been found.  I think they're caused by the same issue, so I've combined these behaviors here.

### Technical details

Self hosted, main

> From [SyncLinear.com](https://synclinear.com)
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
@PeerRich PeerRich added 🐛 bug Something isn't workinglinear Sync Github Issue from community members to Linear.applabels 17 hours ago
@PeerRich PeerRich changed the title The recurring session scheduled midway (3 pm /Havana Time) rendered “Unexpected end of JSON input” [CAL-323] The recurring session scheduled midway (3 pm /Havana Time) rendered “Unexpected end of JSON input” 17 hours ago
@melissamarvin

 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Version, because I didn't know what it was when I wrote the case.  


No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its contributing guidelines, security policy, and code of conduct.
Assignees
No one assigned
Labels
🐛 bug
Something isn't working
linear
Sync Github Issue from community members to Linear.app
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications

**Comment by PeerRich** [comment]
@leog can you investigate this?

**Comment by leog** [comment]
Yes, added to my plate, been talking with @emrysal about this.

**Comment by ohiomoba** [comment]
Pointing out that the bug is in current main branch and that it prevents scheduling any booking with a recurring event type.
