### ISSUE TITLE
[CAL-321] We have high volume booking and appointments get “stolen” during the booking process when a user is slow.

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#5386]
We have a form that users fill out during their booking flow.
1) choose appointment time
2) complete form
We are getting complaints that users submit the form to then receive an error message that the slot is no longer available.
We will work on changing the order of the flow but some users asked why the appointment times don’t get “held” like tickets at an event.

[https://calendso.slack.com/archives/C01NXDSRY9W/p1667578932384469](https://calendso.slack.com/archives/C01NXDSRY9W/p1667578932384469)

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
interesting. classic "shopping cart" problem where people buy items before others. we'll need to block out dates once the person already selects it and then wait for 5 min until releasing it again if the person doesnt confirm it

**Comment by PeerRich** [comment]
this has been fixed with the reserve system
