### ISSUE TITLE
[CAL-327] Reschedule Event Team Bug (Round Robin → Collective)

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5404]
LFE — Reschedule Event Team Bug (Round Robin → Collective)

Created via Threads. See full discussion: [https://threads.com/34433029591](https://threads.com/34433029591)

Using a collective event-type with user **A** and **B**. we changed it from Collective to Round Robin. **C** booked a time with **A** using the **ROUND ROBIN collective event last week.** Today (or yesterday) I changed the event type back to collective.

I believe when I made that change, **C** rescheduled the meeting afterward.

**C** receieved a succesful flow on her end, but we didn't receive a new calendar invite nor email. In fact, the calendar event stayed the same. The video link also was not working which is what I think caused that as well. There is nothing in the bookings tab for **A** or **B**.

> From [SyncLinear.com](https://synclinear.com)

**Comment by shirazdole** [comment]
![CleanShot 2022-11-08 at 13.47.32@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c42a6c87-3471-4871-b9b0-3175348474ee/aaabe50d-e03c-4d5d-a7ab-bd6e0a370687)

Had a customer share that they're facing the following issues as well: [https://calendso.slack.com/archives/C0449HFN78B/p1667908612831219](https://calendso.slack.com/archives/C0449HFN78B/p1667908612831219)

**Comment by shirazdole** [comment]
Could be related, but I canceled a meeting with an attendee, the flow was succesful and the event was removed, but after 20 minutes or so the calendar event was back on my calendar again, but both attendees aren't confirmed 

![CleanShot 2022-11-09 at 13.01.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1d0f173d-ac92-44cc-b95f-e0ca5784dc26/fa1c8041-f48c-4e37-aace-be9c4d812c6d)

![CleanShot 2022-11-09 at 13.00.59@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0ad6e8da-e037-4a71-ba08-91619200deb9/83615a56-8102-43ba-878a-2fb6d51630c1)
