### ISSUE TITLE
[CAL-333] Meeting link as a dynamic text variable in workflows

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5421]
Currently {LOCATION} only shows the meeting type like 'Zoom Video'. We want to show the meeting link instead

> From [SyncLinear.com](https://synclinear.com)

**Comment by JohanForngren** [comment]
I think it would be nice to have both {LOCATION} and something like {LINK} or {URL}. One use case of the former would be to  include the location in the email subject. More options is better 😃

**Comment by CarinaWolli** [comment]
Yes makes sense, I will add a new variable 👍

**Comment by JohanForngren** [comment]
Duplicate of #4733?

**Comment by CarinaWolli** [comment]
@JohanForngren Thank you it is a duplicate indeed. I am currently working on it, PR is coming soon
