### ISSUE TITLE
"Need to make a change? - Cancel" on recurring events, deletes just the next upcoming event

### ISSUE THREAD

**Issue by newz666** [calcom/cal.com#5431]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

"Need to make change? - Cancel" on recurring events, deletes just the next upcoming event instead of the entire series. 

### Steps to Reproduce

1. Schedule a recurring event
2. After creating the event click on "Cancel" next to "Need to make a change".
3. It cancels the next upcoming event instead of the entire series of events.
4. The similar behavior when clicking on an existing recurring event in Bookings -> Recurring, and opens a similar page with the same option to Cancel next to "Need to make a change?"

![Screenshot from 2022-11-09 01-06-11](https://user-images.githubusercontent.com/74431325/200752425-1bad0e13-36be-4e9e-943b-d32bc18447d0.png)

### Technical details

Self hosted, main branch, v2.1.3

**Comment by CarinaWolli** [comment]
Already fixed this in my branch when working on #5082. PR should come up soon
