### ISSUE TITLE
[CAL-339] Radio option in additional questions on public booking page

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5444]
> From [SyncLinear.com](https://synclinear.com)

**Comment by shirazdole** [comment]
Excellent, thank you!

**Comment by Jaibles** [comment]
Working on this now. Still a wip but will remove the "needs design" label when done :)
https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=495%3A67954&t=YRGcltGPVNnZPHaS-1

**Comment by Jaibles** [comment]
@shirazdole designs are ready for review! 

Let me know if you have any feedback. 

[Additional inputs - Single & Multi Selection - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=495%3A67954&t=szkBGC4oYsyHx0wJ-1)

**Comment by shirazdole** [comment]
@Jaibles this looks fantastic!!! You killed it. Especially the "Other" option one. Let me share with our potential customer for feedback too.

**Comment by aasargsian** [comment]
This is exactly what we are looking for :) Minor question - will there be a way to temporarily turn off a question or it can only be deleted?

**Comment by Jaibles** [comment]
> This is exactly what we are looking for :) Minor question - will there be a way to temporarily turn off a question or it can only be deleted?

@aasargsian interesting idea. Hadn't considered it but don't see why we can't propose it in design and get an estimate on the difficulty from engineering!

**Comment by aasargsian** [comment]
@Jaibles Just wanted to quickly check if the radio buttons are still in the works?
We are looking forward to this functionality. We will be waiting for radio buttons to roll out Cal.Com at SleepDoctor ;)

**Comment by Jaibles** [comment]
@aasargsian I have an engineer working on it :) We're aiming to include it in our next release on the 15th but will keep you posted.

**Comment by aasargsian** [comment]
@Jaibles fantastic news! We are looking forward to ot
