### ISSUE TITLE
[CAL-340] Toggle to disable success page when success redirect is enabled

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5446]
When using the event "redirect" feature to another website, the redirect shows the confirmation page still then goes to the redirect, is it possible to add a toggle to disable showing the confirmation page

— Requested by a customer

cc @shirazdole

> From [SyncLinear.com](https://synclinear.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-340](https://linear.app/calcom/issue/CAL-340/toggle-to-disable-success-page-when-redirect-is-enabled)</sub>

**Comment by hariombalhara** [comment]
It's doable. But we still need to show that banner which tells which URL(it being external) the user is being redirected to. So I presume on the booking page itself we would show that for some time and then redirect the user to the external URL.

**Comment by aasargsian** [comment]
@hariombalhara This one is actually heaving requiested by our team. Let me prvide some context. We are using our own success page because:
- there is a layer of important medical information we need to share with patient on the confirnation page. And the text in Cal.Com's success page isn't editable.
- we have Facebook pixel embedded on our own success page to track our marketing results. Seems like this isn't possib;e with Cal.Com's success page either.
- we are using Cal.Com on our own domain (sleepdoctor.me) and redirecting them to a success page on our own domain too. So it's not really and external URL, is it
- we have been using redirect in Calendly and it would just smoothly redirect the patient without any notice.

**Comment by hariombalhara** [comment]
@aasargsian I got the reasoning now.

> we have Facebook pixel embedded on our own success page to track our marketing results. Seems like this isn't possible with Cal.Com's success page either.

Facebook Pixel isn't there yet but it should be quick to add. We already have GA4, Plausible and Fathom.

> we are using Cal.Com on our own domain (sleepdoctor.me) and redirecting them to a success page on our own domain too. So it's not really and external URL for us

I think then if we skip the banner fir same domain redirect, that would solve your problem.

**Comment by PeerRich** [comment]
i wonder if we should offer self-hosters the option to have direct redirects without waiting. they can decide on their level of risk-aversion

**Comment by hariombalhara** [comment]
@PeerRich Yeah for self hosters a separate option makes sense.

**Comment by hariombalhara** [comment]
Yeah I am not in favour of removing the banner. 2 things make sense and can be done here
- Same domain redirect should have no waiting time(banner).
- Allow self-hosters to disable wait time(banner). That would allow them to disable it even for different domain redirects.

**Comment by PeerRich** [comment]
go for it

**Comment by hariombalhara** [comment]
I am making a slight change in implementation. This would be the new approach:
-On Hosted : Same domain redirect won't usually happen because it would be a redirect to cal.com itself and we need to see what use case there can be. Doing a redirect without staying on the success page might be problematic(without giving an option to disable it).
- On SelfHosted: Allow self-hosters to disable wait time(banner). That would allow them to disable it even for different domain redirects

**Comment by hariombalhara** [comment]
@PeerRich Also I think it might be a good idea to show the Self Hosted settings on Hosted Cal.com(but disabled with a badge). That would indicate what additional configurations are available if user self hosts. Should I do it?

**Comment by PeerRich** [comment]
ok
