### ISSUE TITLE
Dynamic Collective title

### ISSUE THREAD

**Issue by heathermeeker** [calcom/cal.com#5448]
### Issue Summary

All my cal.com appointments are entitled "Dynamic Collective" events.

### Steps to Reproduce

Any appointment created by Cal.com.

This is confusing, as it presents a brand I was not aware of, and has nothing to do with the topic of the meeting or the attendees.

### Technical details

- using Chrome browser
- enterprise subscription to Cal.com

**Comment by PeerRich** [comment]
can you send me a link to test? peer@cal.com
