### ISSUE TITLE
Integration with Zoho Bigin

### ISSUE THREAD

**Issue by proofrating** [calcom/cal.com#5450]
### Is your proposal related to a problem?

Yes it is.  Just want to be able to have my calendar app integrate with my CRM.

Frustrated when you have to use a third party to connect your calendar bookings with your CRM.

### Describe the solution you'd like

I'd like a direct integration with Zoho Bigin CRM where when a cal.com appointment is booked it creates the appropriate task/event.

### Describe alternatives you've considered

 Cal.com integration with Zoho Mail.  Then use zapier or Zoho Flow to connect events.  but this is time consuming and adds another 3rd party to the mix.

### Additional context

bigin.com

**Comment by proofrating** [comment]
I don't think Bigin has webhooks option yet - it does have open APIs to integrate though






---- On Thu, 10 Nov 2022 10:27:57 -0500 Peer Richelsen ***@***.***> wrote ---





have you tried webhooks?

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by ShaneMaglangit** [comment]
Working on this :+1:

**Comment by ShaneMaglangit** [comment]
@PeerRich anyone assigned on this yet? Otherwise, would love to work on this.

**Comment by ShaneMaglangit** [comment]
Working on this :rocket:
