### ISSUE TITLE
[CAL-345] Integration with Zoho calendar

### ISSUE THREAD

**Issue by proofrating** [calcom/cal.com#5451]
### Is your proposal related to a problem?

I'd like [cal.com](http://cal.com) to allow me to connect my Zoho calendar for work.

### Describe the solution you'd like

I'd like the integration to work between Zoho calendar and [Cal.com](http://Cal.com)

### Describe alternatives you've considered

Tried using a free Google calendar and then sharing that Google calendar with my Zoho calendar for it to appear.  This is so backwards and brings more softwares into the mix then there needs to be.

### Additional context

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
on the roadmap!

**Comment by SyndicatedPillbug** [comment]
Glad it's on the roadmap! I second this!

**Comment by murtajaziad** [comment]
Hi, can you assign me this issue?

**Comment by PeerRich** [comment]
done

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by ShaneMaglangit** [comment]
Hi @murtajaziad,  just wondering if you're actively working on this or if I can take over?

**Comment by murtajaziad** [comment]
Hi @ShaneMaglangit, yeah it's almost done, it just needs some final touches.

**Comment by ShaneMaglangit** [comment]
@murtajaziad Hey, it's been a while. How's this one going? I actually need this integration for my calendar.

**Comment by murtajaziad** [comment]
Hi @ShaneMaglangit, sorry for the delay. I'll be making the pull request by today or tomorrow maximum.

**Comment by ShaneMaglangit** [comment]
> Hi @ShaneMaglangit, sorry for the delay. I'll be making the pull request by today or tomorrow maximum.

Sweet, looking forward to it :bow:

**Comment by The-Robin-Hood** [comment]
Is this bounty still alive or someone working on it ??

**Comment by prince-panwar** [comment]
hi, @murtajaziad  are you still working on this issue?

**Comment by murtajaziad** [comment]
> hi, @murtajaziad are you still working on this issue?

Yep.
