### ISSUE TITLE
[CAL-342] Inputs with suffixed icons are currently way too big

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5458]
Current

![CleanShot 2022-11-10 at 10.41.40@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/61225223-b45d-484e-a95c-ca651b2facb1/fc278ffd-a09f-451e-89e6-39da37b9df27)

In the designs these should have no background or borders. If we need to keep them for any reason, can we ensure it still just a square and not an elongated rectangle like now.

Should be

![CleanShot 2022-11-10 at 10.40.46@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6d24d16e-34bf-4362-bf54-d79d16387e5b/fbaa428a-58da-444a-bfe3-c0091e5745fb)

![CleanShot 2022-11-10 at 10.43.06@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1598bbba-0402-453d-aef6-f04adfe1d7b3/d841c83e-9f5c-46c7-88b3-be59d9432f8f)

[Text Field Brief - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=346%3A30200)

> From [SyncLinear.com](https://synclinear.com) | [CAL-342](https://linear.app/calcom/issue/CAL-342/inputs-with-suffixed-icons-are-currently-way-too-big)

**Comment by MatheusBeniniF** [comment]
@Jaibles, which is this page?

**Comment by Jaibles** [comment]
@MatheusBeniniF this particular example is in event type settings under the advanced tab but I would like this edit made at the component level so it's fixed everywhere if possible 🙏

**Comment by zomars** [comment]
Fixed by #5584
