### ISSUE TITLE
[PRO-26] event-type-settings nav UI issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5461]
The icons are misaligned in the sidebar nav

![CleanShot 2022-11-10 at 10.44.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/90d90f25-8271-448a-ac34-2b803da4c01d/bed1a968-6b73-4b64-b51f-7cf3a76f0d9e)

> From [SyncLinear.com](https://synclinear.com) | [PRO-26](https://linear.app/calcom/issue/PRO-26/event-type-settings-nav-ui-issues)

**Comment by PeerRich** [comment]
<img width="99" alt="CleanShot 2022-11-10 at 15 03 41@2x" src="https://user-images.githubusercontent.com/8019099/201129067-4780c806-0383-4586-abb3-d3aa5e6f064d.png">
also the text is being cut off (maybe related)

**Comment by Udit-takkar** [comment]
@PeerRich  yeah checking why is this happening
