### ISSUE TITLE
[CAL-346] Changing location of booked meeting does not send mail and new location is not saved

### ISSUE THREAD

**Issue by chrisgick** [calcom/cal.com#5464]
### Issue Summary

Changing location of booked meeting does not send mail and new location is not saved.

### Steps to Reproduce

1. Edit booked meeting
2. Change location and save

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
This is the current design

<img width="595" alt="Screenshot 2022-11-17 at 12 43 50 AM" src="https://user-images.githubusercontent.com/53316345/202272000-001f4520-7566-4a81-9fe4-e1bd5a294fd4.png">

should i update it like the figma one and include text box for location change ? cc: @PeerRich 

<img width="595" alt="Screenshot 2022-11-17 at 12 44 21 AM" src="https://user-images.githubusercontent.com/53316345/202272085-9b52694b-9089-43ae-8391-ff7ffd83954a.png">

**Comment by chrisgick** [comment]
Good idea!

**Comment by Udit-takkar** [comment]
<img width="1005" alt="Screenshot 2022-11-19 at 3 37 41 PM" src="https://user-images.githubusercontent.com/53316345/202845625-68ab21a5-7b75-46b9-9b76-f391d37c9786.png">

@chrisgick attendees are receiving mail when location is changed. can you try once again ?

**Comment by rene-mueller** [comment]
@Udit-takkar which branch should be tested?

**Comment by Udit-takkar** [comment]
@rene-mueller i tried on main branch

**Comment by rene-mueller** [comment]
@Udit-takkar the mail delivery works now :)

**Comment by Udit-takkar** [comment]
great
