### ISSUE TITLE
Add options in time slot interval up to 2 h (by 15 min) instead of limitation to 60 min.

### ISSUE THREAD

**Issue by tbalbous** [calcom/cal.com#5472]
### Is your proposal related to a problem?

This is maybe just a limitation, maybe a simple parameter in the app.

When I set an event type, I can only select time slot interval up to 60 min.
I’m sometimes working with 90 min slots and I do want to take a 30 min break.
I want to be able to open slots every 2 h or every 90 min. (not being limited to 60 min).
Because if can client can schedule at 9 am instead of only 8 or 10 am, I’m loosing a 2 hours slot. (want 2 slots on the morning, and still have lunch at 12)

(Write your answer here.)

### Describe the solution you'd like

Add more options in the time slot intervals so we can have bigger slots.
My recommendation is up to 2 h, by 15 min, though it’s 4 more entries.
(Describe your proposed solution here.)

### Describe alternatives you've considered

For now I’ve created an availability with 2 h slots every days and used that one for that type of event than need 2 h time slot interval.
(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by sean-brydon** [comment]
I believe we have something already that may suit your use case a little nicer than the issue you have described above.

If you take a look into the limits tab you will see two drop downs for before and after limits. If you set a after limit for 30 minutes for example this will block you from being booked for 30 minutes after any existing meetings in your calendar.

**Comment by tbalbous** [comment]
Hi,

Yes, I do agree, but it still allows the first visitor to pick the 9 am meeting that ruins my 2 slots morning.
Let say availability is 8 am to 12 pm with 60 min time slots intervals.
People can see and choose 8 am, 9 am, 10 am or 11 am.
if they pick 9 am for 90 min, + 30 min buffer, there in no space for another meeting on the morning.

With the same availability but a time slot interval of 120 min.
People can see and choose 8 am or 10 am. And I do have my to slots.

I did try the options with the buffer but it only works if/when the first person pick the first slot.

That is why I have created 2 h slots in availability, but it is not suitable because I have to create different availability patterns for the same periods of time.

Thank you
Tremeur


------- Original Message -------

**Comment by sean-brydon** [comment]
@emrysal what's your thoughts on this?

**Comment by emrysal** [comment]
I think the ability for longer time intervals is useful, e.g. I want to have two meetings; one in the morning and one in the afternoon - worth a think on how to achieve this; but 60 minutes max time is a bit arbitrary and can be a quick win to implement 90min and 120min

**Comment by milospuac** [comment]
@emrysal should I add this to linear then?

**Comment by sean-brydon** [comment]
Yeah @milospuac please do - ill pick this up should be a very simple fix to just add 90 and 120

**Comment by tbalbous** [comment]
For what I was able to track it happens here
https://github.com/calcom/cal.com/blob/main/apps/web/components/eventtype/EventLimitsTab.tsx

```
Could be changed by : 
       ...[5, 10, 15, 20, 30, 45, 60,75,90,105,120].map((minutes) => ({
                  label: minutes + " " + t("minutes"),
                  value: minutes,
```

Not sure, and not aware of the possible impacts.

Kind of test I can imagine:
If my availability start at 8am and end at 12:30pm, and slot of 75min, I should have possible appointments at 8 am, 9:15am, 10:30 am, (not enough time for a slot at 11:45.
If my availability start at 8:30am and end at 12:00pm, and slot of 120min, I should have possible appointments at 8 am, 10:00 am.
If my availability start at 8am and end at 12:30pm, and slot of 90min, I should have possible appointments at 8 am, 9:30am, 11:00 am.

Does not really make sense to me to have interval longer than 2 h (120min) because that does not fit naturally in half days. 
Btw, we can imagine someone wanting to book slots like 8 am, 11 am, 2pm, 5pm.
Even myself I very often book 4 h slots for a client when I facilitate ½ day workshops. But in that case, it’s rare to do the booking through the app.
Could that be a parameter that a user can define in the settings like the apps to connect? If so, probably another, less «urgent» feature.

Current code
```
       <div className="w-full">
          <Label htmlFor="slotInterval">{t("slot_interval")} </Label>
          <Controller
            name="slotInterval"
            control={formMethods.control}
            render={() => {
              const slotIntervalOptions = [
                {
                  label: t("slot_interval_default"),
                  value: -1,
                },
                **...[5, 10, 15, 20, 30, 45, 60].map((minutes) => ({
                  label: minutes + " " + t("minutes"),
                  value: minutes,**
                })),
              ];
              return (
                <Select
                  isSearchable={false}
                  onChange={(val) => {
                    formMethods.setValue("slotInterval", val && (val.value || 0) > 0 ? val.value : null);
                  }}
                  defaultValue={
                    slotIntervalOptions.find((option) => option.value === eventType.slotInterval) ||
                    slotIntervalOptions[0]
                  }
                  options={slotIntervalOptions}
                />

```

Thanks a lot for you reactivity
