### ISSUE TITLE
[CAL-348] When updating user email in profile, the confirmation password input doesn't show the email when eye toggle button is clicked

### ISSUE THREAD

**Issue by gzuzmark** [calcom/cal.com#5473]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When updating user email in profile, the confirmation password input doesn't show the email when eye toggle button is clicked

### Steps to Reproduce

1. Login and go to settings/profile page
2. Change email
3. Click "Update" button
4. Fill the password input
5. Click the eye button to see the password and not the dots

### Technical details

* cal user profile

[https://user-images.githubusercontent.com/5327036/201168158-ca2dc008-582e-4e2c-9412-34f8c612ab9d.mp4](https://user-images.githubusercontent.com/5327036/201168158-ca2dc008-582e-4e2c-9412-34f8c612ab9d.mp4)

> From [SyncLinear.com](https://synclinear.com)

**Comment by gzuzmark** [comment]
If needed I can take this one, since I think the behavior is in web/pages/settings/my-account/profile.tsx

**Comment by Udit-takkar** [comment]
hey @gzuzmark , thanks for reporting this bug. you can go ahead and raise a PR if you want
