### ISSUE TITLE
[CAL-350] Issue with create a new team dialog

### ISSUE THREAD

**Issue by imjlk** [calcom/cal.com#5474]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In `/teams` page, When the enter key is pressed in the create a new team dialog, a new team is not created and refreshed with parameter `/teams/name={myInputForTeamName}`.
It's reproduce also in `app.cal.com`

Click the button `Create a new team` for creating is working correctly.

### Steps to Reproduce

1. Go to `/teams` page
2. Click the `+ New` button or `Create Team` button
3. Input team name and press the Enter key

### Technical details

* Chrome 107.0.5304.87 (arm64)
* Node.js 16.x, git cloned current release (v2.1.4)
* [Captured video link](https://drive.google.com/file/d/1wA1R7wssKB9hwOyg6xPGJt10b5n-xviS/view)

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
@Udit-takkar

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2022-11-11 at 7 32 18 PM" src="https://user-images.githubusercontent.com/53316345/201355942-1f20c557-9cf0-43a0-b25f-ce5f756c11d2.png">

@imjlk  which version are you using ? I see a different flow for creating a team

**Comment by imjlk** [comment]
@Udit-takkar As I wrote it happens in v2.1.4.
Now(v.2.1.5-h-trial, Current version of https://app.cal.com), in the screenshot you posted, still some problem with press Enter key. If you press Enter multiple time, team created multiple time with same name.

Also Step2, when clicking Publish team, `Missing required param: line_items[0][currency].` this error message notified.

**Comment by Udit-takkar** [comment]
@imjlk thanks for reporting this we have fixed the step 2 and it would live soon

**Comment by Udit-takkar** [comment]
and i'll raise a PR to fix the step 1 soon
