### ISSUE TITLE
[CAL-349] In edit team page, team URL is not validated appropriately

### ISSUE THREAD

**Issue by imjlk** [calcom/cal.com#5475]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In edit team page, team URL is not validated appropriately.
It looks like anything can be input and save

### Steps to Reproduce

1. Go to `/teams` page, Select one team for editing
2. In `/settings/teams/{selectedTeamID}/profile` page, Input something in `Team URL` field.
3. Click `Update` button.
4. Check the saved Team URL.

In my test case, it could be updating with not percent encoding characters. (like <, >, +, etc...)

Furthermore, I think when create a team, Non-english characters are need to be encoded with percent encoding. Currently, It's just replace with `-`.

### Technical details

* Chrome 107.0.5304.87 (arm64)
* Node.js 16.x, git cloned current release (v2.1.4)

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
@Udit-takkar

**Comment by Udit-takkar** [comment]
@PeerRich  should we only allow english alphabets, numbers and "-" in team URL ?

**Comment by PeerRich** [comment]
probably a good idea
