### ISSUE TITLE
[CAL-355] Set individual video links per user through team collective events

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5485]
* How can we set individual video links per doctor through team collective events
  Scenario: they have a round robin of all their doctors, when one doctor gets booked, how do they make sure it's their individual private link for a separate video streaming service they use

Created via Threads. See full discussion: [https://threads.com/34433289866](https://threads.com/34433289866)

> From [SyncLinear.com](https://synclinear.com) | [CAL-355](https://linear.app/calcom/issue/CAL-355/set-individual-video-links-per-user-through-team-collective-events)

**Comment by shirazdole** [comment]
The way Calendly does this is on the collective event, under the location field, they have a "Video Configurator" which basically allows the host to pick which accounts Zoom or Daily link they want to use. 

They also have a field saying "use this person as video configurator, but they still need to connect a Zoom account"

**Comment by shirazdole** [comment]
Need to take the video link of the person, not the actual event type

**Comment by aasargsian** [comment]
Our team used to utilize this feature actively in Calendly. Here is a reference of how it looks there: 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/33749906/203252915-b2702c6f-1dc0-4f44-a636-d39bbc0f1f50.png">

**Comment by aasargsian** [comment]
@shirazdole I am wondering if this feature is still low priority? We are looking forward to it's implementaiton and are open to provide more context if required :)

**Comment by shirazdole** [comment]
@aasargsian, @emrysal is looking into this! :) we just synced this week about it 

cc @Jaibles

**Comment by emrysal** [comment]
@aasargsian This has become high priority pending some other work, so definitely bumped and due implementation within weeks

**Comment by aasargsian** [comment]
@emrysal that is great news! 
We used this heavily in Calendly. In any team event type (collective / round-robin) for each seelted team memeber we were able to assign an individual location. Here is how it would look in the event setting:
![image](https://user-images.githubusercontent.com/33749906/212069841-b68a23be-a65c-4a38-b4bc-f1efc629ff7a.png)

For us the meeting link is the same for all users. It would even make more sense to be able to assign this link once per each user in their account settings.

**Comment by PeerRich** [comment]
we'll look into adding this in the next release!

**Comment by aasargsian** [comment]
@emrysal @shirazdole hi! Just wanted to quickly check if individual meeting links are still planned?

**Comment by shirazdole** [comment]
@aasargsian yes! Here you go: https://github.com/calcom/cal.com/pull/7811

**Comment by cmonaghan1** [comment]
Is there any further updates on this? The 'organiser's default app' added in #7811 isn't suitable for my use case as far as i'm aware.

What I'd need is to specify a 'link meeting' location that is dynamic based on who your booking is assigned to - basically what @aasargsian has been describing with Calendly

**Comment by keithwillcode** [comment]
@Jaibles Shall we close this in favor of #9430?
