### ISSUE TITLE
[CAL-357] Hide Confirmation Page on Redirect to Another Website

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5488]
When using the event "redirect" feature to another website, the redirect shows the confirmation page still then goes to the redirect, is it possible to add a toggle to  disable showing the confirmation page

\--
From Hariom: That's doable. But we still need to show that banner which tells which URL(it being external) the user is being redirected to.

So I presume on the booking page itself we would show that for some time and then redirect the user to the external URL.

Created via Threads. See full discussion: [https://threads.com/34433289874](https://threads.com/34433289874)

> From [SyncLinear.com](https://synclinear.com) | [CAL-357](https://linear.app/calcom/issue/CAL-357/hide-confirmation-page-on-redirect-to-another-website)

**Comment by shirazdole** [comment]
@Jaibles @hariombalhara - created a ticket, but not sure who this should be assigned to

**Comment by PeerRich** [comment]
been fixed
