### ISSUE TITLE
[CAL-359] env variables runtime checks

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5489]
[https://github.com/calcom/cal.com/pull/3586](https://github.com/calcom/cal.com/pull/3586)

> From [SyncLinear.com](https://synclinear.com) | [CAL-359](https://linear.app/calcom/issue/CAL-359/env-variables-runtime-checks)

**Comment by PeerRich** [comment]
this one feels like it would solve a lot of docker issues right? lets prioritize this higher

**Comment by zomars** [comment]
You read my mind

**Comment by McPizzaIs** [comment]
I built a module for Nuxt recently that effectively halted build/start based on init scripts: https://www.npmjs.com/package/nuxt-server-init
I will check to see if there are similar hooks within NextJS, but Im not too familiar with the ecosystem so it may take a bit longer.
