### ISSUE TITLE
[CAL-361] Add manypkg to monorepo

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5491]
From [Turborepo handbook.](https://turbo.build/repo/docs/handbook/troubleshooting#handling-mismatched-package-versions) Useful for managing version across packages.

> From [SyncLinear.com](https://synclinear.com) | [CAL-361](https://linear.app/calcom/issue/CAL-361/add-manypkg-to-monorepo)

**Comment by PeerRich** [comment]
i tagged this as low priority @zomars
