### ISSUE TITLE
[CAL-362] Consider adopting Changesets for versionning/releasing

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5492]
[https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing)

> From [SyncLinear.com](https://synclinear.com) | [CAL-362](https://linear.app/calcom/issue/CAL-362/consider-adopting-changeset-for-versionningreleasing)

**Comment by PeerRich** [comment]
great idea. should we pursue this now?

**Comment by zomars** [comment]
Yes. I have it in my TODOs for investigation

**Comment by zomars** [comment]
Although we don't really "publish" to NPM for example but we can use the workflow for deployments. Maybe docker as well
