### ISSUE TITLE
[CAL-365] Troubleshooting page is confusing and potentially not working as expected

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#5505]
As per a customer's feedback

> The troubleshoot page is awesome, and much needed, but quite confusing (delayed feedback on date change, day entries mixed up together, scrolling automatically jumps back to top of the page at 17 seconds). Also in my case the troubleshooting doesn't explain why zero available appointments are shown on my calendar this week.

[Screencast Video](https://nextcloud.lightmeter.io/index.php/s/jDKfqj5FHJmkG75)

> From [SyncLinear.com](https://synclinear.com) | [CAL-365](https://linear.app/calcom/issue/CAL-365/troubleshooting-page-is-confusing-and-potentially-not-working-as)

**Comment by PeerRich** [comment]
agree
