### ISSUE TITLE
[CAL-366] Google Calendar conflict not checked

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#5506]
Reported by a customer:

> [cal.com](http://cal.com) allowed someone to double book a meeting, though the correct Google calendar was setup to check for conflicts in my [cal.com](http://cal.com) account

> From [SyncLinear.com](https://synclinear.com) | [CAL-366](https://linear.app/calcom/issue/CAL-366/google-calendar-conflict-not-checked)

**Comment by Kfelts** [comment]
I am also experiencing this issue. I have been consistently from the start. I have my calendar connected, but I'm not sure what it does. It doesn't add events to my calendar and it doesn't seem to conflict check. I've tried disconnecting it multiple times and reconnecting it to no avail. I have to manually add all events and double check that bookings aren't double or overbooked.

**Comment by PeerRich** [comment]
i dont think this is happening anymore. at least I cant reproduce this

**Comment by PeerRich** [comment]
please reach out to support@cal.com with your username if this is happening to you, so we can investigate.
