### ISSUE TITLE
[CAL-367] Routing Forms - Improvements

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5507]
* Reporting
  * Add operators
    * **is Empty** → Doesn’t seem doable with JSON query because isEmpty can be in 2 ways
      * a.b === “”
      * a.b doesn’t exist → This doesn’t seem doable with json query.
    * i**s not Empty** → Would make sense together with isEmpty. So, add it when is Empty operator is added.
* Handle `jsonLogic.errors` object to show errors while saving or adding a logic and if not that atleast during form submission
* ***Make equal and other text comparisons case insensitive***
* **MultiSelect** and **Select** should allow search for any text(instead of selection of current options_ because if form owner changed options after some data has been recorded, old options can’t be filtered.

#5122

> From [SyncLinear.com](https://synclinear.com) | [CAL-367](https://linear.app/calcom/issue/CAL-367/routing-forms-improvements)

**Comment by PeerRich** [comment]
we should make a dedicated milestone for routing forms. lots of quick wins that can be packaged up
