### ISSUE TITLE
[CAL-368] RFC: Routing Forms - Reusability and Extensibility of Router

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5508]
* Allow a Router to be created outside of a Form - Call it a **Global Router**
* User can create a **Global Router** which would have just Form and Routing tabs.
  * This is because a Router can't be created without Form Fields.
* When a new Form is created user can optionally select which **Global Router** to use. We can call such a Form as **Global Router Linked Form**
  * It would automatically add all the fields required by the Router in addition to Routing Rules
* Characteristics of **Global Router Linked Forms**
  * Such a form has a Global Router which can be edited at one place and all Global Router Linked Forms linked to that Global Router would have the effect.
  * would have **Global Router Fields** locked
  * would have **Global Router Rules** locked
  * User can add more fields.
  * User would be able to add more Routing Rules
  * ~The way user can click Add a rule, user can do 'Add a Global Router'. This allows a scenario like Having a Global Router as 'Enterprise Client'(reusable across multiple forms) and make it AND/OR with other form specific rules.~ The ~striked off~ approach won't work as a Router also has the corresponding Route and not just the AND/OR condition. The only thing that's possible is to decide where exactly Global Router would come in ordered Routes list. So, there can be
    * R1, R2, GR(Global Route)
    * GR, R1, R2
    * R1, GR, R2
* **Global Routers** should list which Forms are linked to it.
* User can save an existing form as `Global Router` as well
* **Global Router Fields** still can be re-ordered inside a Global Router Linked Form. That reordering would impact only that Form and not other Global Router Linked Forms or the Global Router itself. It can also be said that Global Router doesn't care about the ordering of fields. Global Router Linked Form cares about that.
* User would be able to delete Global Router fields(Would be a soft delete only)

Legend:

* Router is the Routing Rules which are available under the **Routing** tab

From [SyncLinear.com](https://synclinear.com/) | [CAL-368](https://linear.app/calcom/issue/CAL-368/rfc-routing-forms-reusability-and-extensibility-of-router)

> From [SyncLinear.com](https://synclinear.com)

**Comment by shirazdole** [comment]
@hariombalhara could you share exactly what a "router" is?

**Comment by hariombalhara** [comment]
A router is the Routing Rules which are available under the **Routing** tab
