### ISSUE TITLE
[CAL-370] Troubleshooter and Bug Reporter for Infra Users.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#5511]
More details on [threads](https://threads.com/34433595232?s=vM3WCmpvNa9FtyCLaKYmFx)

Would be a continuation of https://github.com/calcom/cal.com/pull/3586

> From [SyncLinear.com](https://synclinear.com) | [CAL-370](https://linear.app/calcom/issue/CAL-370/troubleshooter-and-bug-reporter-for-infra-users)

**Comment by PeerRich** [comment]
@hariombalhara unassigning you due to inactivity
