### ISSUE TITLE
[CAL-371] Dynamic events create collective event instead of single event for each attendees

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5517]
Currently, when sending a dynamic booking, it creates a separate event for each guest. It should create one collective event with all parties.

However, there is an issue of selecting who the event host should be. Is there a way to add this on as well? Currently, the person who books the meeting is the event host, but it should be the person who SENDS the dynamic link that should become the event host. A potential work around is have the first name in the sequence be the event host, however, right now we set the dynamic link in alphabetical order. 

I.e. when cal.com/shiraz+peer is sent, it auto adjusts to cal.com/peer+shiraz

> From [SyncLinear.com](https://synclinear.com) | [CAL-371](https://linear.app/calcom/issue/CAL-371/dynamic-events-create-collective-event-instead-of-single-event-for)

**Comment by PeerRich** [comment]
@alishaz-polymath any update?

**Comment by alishaz-polymath** [comment]
Oh forgot to update.
I tested this just now, and it creates a single event with one of the users as the Host while others in the dynamic list as attendees. It **Does** create a single event, only that it adds the other dynamic users as attendees.
Closing this for now, unless @shirazdole can confirm that it is still not working as I state.

**Comment by alishaz-polymath** [comment]
Also, relating to the following:
> Currently, the person who books the meeting is the event host, but it should be the person who SENDS the dynamic link that should become the event host

This isn't quite true as the Booker is the primary attendee while the first one on the dynamic user list is the host.
