### ISSUE TITLE
[CAL-498] Include video location in web hooks

### ISSUE THREAD

**Issue by kg4201** [calcom/cal.com#5518]
### Is your proposal related to a problem?

We want to use the webhook events to save the video location's url (ie google meet / zoom etc)

### Describe the solution you'd like

```
Webhook (Created)
triggerEvent: "BOOKING_CREATED",
payload:{
location: 'integrations:google:meet' //This is where we should include the video link URL for any of the video platforms (Cal, Google Meet, Zoom, etc).
}

Webhook (Rescheduled)
triggerEvent: "BOOKING_RESCHEDULED",
payload:{
location: 'integrations:google:meet' //This is where we should include the video link URL for any of the video platforms (Cal, Google Meet, Zoom, etc).
}

Webhook (Cancelled)
triggerEvent: "BOOKING_CANCELLED",
payload:{
location: 'integrations:google:meet' //This is where we should include the video link URL for any of the video platforms (Cal, Google Meet, Zoom, etc).
}
```

### Describe alternatives you've considered

N/A Feature does not exist currently

### Additional context

This is data point / feature available on other platforms (ie Calendly)

<sub>[CAL-498](https://linear.app/calcom/issue/CAL-498/include-video-location-in-web-hooks)</sub>

**Comment by hariombalhara** [comment]
cc @alishaz-polymath

**Comment by milospuac** [comment]
@hariombalhara I think Carina mentioned something that she will work on it, no?

**Comment by hariombalhara** [comment]
Yeah, she is on it
