### ISSUE TITLE
[CAL-375] Rescheduling a meeting should show the previous time crossed out & the reschedule reason on the confirmation page & in email

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5534]
Currently a reschedule meeting shows this

![CleanShot 2022-11-15 at 13.53.26@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b9c4b408-25ac-4af1-a1f2-6ec6a2bdde3e/982495d8-920c-41a0-bfc3-6520b24aa387)

It should show this

![CleanShot 2022-11-15 at 13.55.33@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2263f8c2-2158-4439-b1ad-86bbddcc3565/28ac7bc3-79d9-483f-9606-a1a2882297d0)

(pretty sure this was tackled in a pr recently but can't find it)

> From [SyncLinear.com](https://synclinear.com) | [CAL-375](https://linear.app/calcom/issue/CAL-375/booking-page-rescheduling-a-meeting-should-show-previous-time-crossed)

**Comment by Jaibles** [comment]
@leog based on this pr:[https://github.com/calcom/cal.com/pull/5035](https://github.com/calcom/cal.com/pull/5035) should I still have been seeing the behaviour screenshotted above today?

**Comment by leog** [comment]
@Jaibles yes, that PR only fixes showing the new rescheduled date crossed out, does not include the old date

**Comment by MatheusBeniniF** [comment]
@Jaibles, this issue is duplicated, https://github.com/calcom/cal.com/issues/5134 is the other and already has a PR

**Comment by Jaibles** [comment]
Ah I see. I've given the design my blessing anyway! We need to poke an engineer to approve the code.

**Comment by Jaibles** [comment]
duplicate
