### ISSUE TITLE
[CAL-376] Move "Additional notes" into Additional inputs

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5536]
Move this..

![CleanShot 2022-11-15 at 14.56.58@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/246b3655-98f3-4243-8362-a37a6ecb48a0/ca5f0798-dae7-4c41-bb39-088386eea9e6)

Into additional inputs

[4a46ad2f-0f83-4be8-9e04-da58714cac04](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2d74d509-345c-42e0-a981-72f20cc27bcc/4a46ad2f-0f83-4be8-9e04-da58714cac04)

> From [SyncLinear.com](https://synclinear.com) | [CAL-376](https://linear.app/calcom/issue/CAL-376/move-additional-notes-into-additional-inputs)

**Comment by emrysal** [comment]
I talked with @PeerRich about this last week and we both thought it wasn't a bad idea to build a form builder with by default having:

* Name
* Email
* Add guests
* Notes

And make everything user-controlled.

**Comment by Jaibles** [comment]
Have made a separate issue to design something more inline with what you're describing 👍

Basically the idea is to have a tab that controls everything the booker sees. This will include what you're talking about plus where they'll edit things like what layout options to make available to the user (weekly / monthly) etc.

**Comment by aasargsian** [comment]
@Jaibles @emrysal Great to see this in the works!
It would be amazing if we were able to:
- Remove Additional notes input altogether
- Have an option to gather Last name and First name as separate imputs
- Be able to turn questions on/off

We have been using all these smaller features in Calendly. I will share a few screenshots :)
<img width="326" alt="image" src="https://user-images.githubusercontent.com/33749906/204616773-7c007394-93c6-425c-95eb-9525c777c1fc.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/33749906/204616860-7abc75d0-e27b-47b6-8628-bbd75ec29244.png">
