### ISSUE TITLE
[CAL-377] avatar preview wont update after new image uploaded on UserProfile page

### ISSUE THREAD

**Issue by luiisca** [calcom/cal.com#5538]
### Issue Summary

Avatar preview won't update after a new image is uploaded on the UserProfile page

### Steps to Reproduce

1. Go to [UserProfile page](https://app.cal.com/getting-started/user-profile)
2. Save profile photo change

I don't know if this behavior was intended or not. But either way, it'd be nice to provide a preview of the updated profile image to improve UX.

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
@luiisca thanks for reporting this bug.

**Comment by Udit-takkar** [comment]
@zomars should i remove getServerSideProps from /getting-started/[[...step]].tsx  and use trpc so that i can invalidate user query result ?
