### ISSUE TITLE
[CAL-471] Calendar conflict is ignored in Round Robin meetings using individual default availability

### ISSUE THREAD

**Issue by RebeccaCotton** [calcom/cal.com#5539]
### Issue Summary

Calendar conflict is ignored when showing the available timeslots in Round Robin meetings using individual default availability.

### Steps to Reproduce

1. create two users, both with an availability set as follows: user1 (Mo, Wed 9-5), user 2 (Fri 9-5)
2. Create a round robin event with both users, this behaviour occurs both with common schedule and with individual schedules
3. Connect the calendar of user 1 and create an event in the calendar of user 1 blocking one of their days (e.g. all of Wednesday)
4. Connect the calendar of user 2 and create an event in the calendar of user 2 blocking one of their days (e.g. all of Friday)
5. Now got to the events appointment page and see the available timeslots

### Actual behaviour
- the user sees the timeslots only taking into account the default availability, but not the calendar conflict, so all times are shown as available
- For our example this means that the user sees available slots on Mo, Wed, Fri, even though user 1 is not available on the Wednesday due to the calendar event and user 2 is only available on Fridays.
- as a booking user I can select the timeslot (on the time which should not be available), but see an error when booking

### Expected behaviour
- as a booking user I should not see available timeslots when no user is available taking into consideration their calendar conflicts AND availabilty

### Technical details
![Screenshot_20221115_172955](https://user-images.githubusercontent.com/14073417/201977466-757592fe-5184-4158-9ce3-156112f86c8c.png)
![Screenshot_20221115_172921](https://user-images.githubusercontent.com/14073417/201977473-9bd4def8-7acb-4482-9ef7-52fdbba8d529.png)

- Tested on production on cal.com

<sub>[CAL-471](https://linear.app/calcom/issue/CAL-471/calendar-conflict-is-ignored-in-round-robin-meetings-using-individual)</sub>

**Comment by PeerRich** [comment]
@emrysal

**Comment by zomars** [comment]
@leog do you have bandwidth to investigate this one?

**Comment by leog** [comment]
> @leog do you have bandwidth to investigate this one?

@zomars talked with @emrysal and he will take a look, I'm second in line just in case
