### ISSUE TITLE
[CAL-416] Bookings are bypassing required confirmation and worflows/webhooks are not firing

### ISSUE THREAD

**Issue by Kfelts** [calcom/cal.com#5542]
Found a bug? Please fill out the sections below. 👍

### Summary

I had a booking submitted around 4 pm EST, which requires both payment and confirmation. The booking was immediately placed in "upcoming" but did not appear under "unconfirmed." It also did not give me the option of confirming the appointment. I checked the settings and made sure that it was set up to require a confirmation from me due to the nature of the appointment. All settings appear configured properly.

Additionally, any triggers or webhooks that have been set up are not activating. I should have received two separate workflow notifications for that event, but I didn't receive anything. I went into the workflow to confirm it was attached to the event, that it was enabled, and then tested it. The test worked and I received my notification, but it does not happen without manually triggering a test. The webhook did not fire at all, nor did my Zapier integration.

### Steps to Reproduce

1. Configure an appointment to require confirmation and set up workflows that are triggered for booking
2. Tested the workflow triggers and they worked without issue
3. Tested webhook configuration and pulled test data into Zapier without issue
4. When a booking is done organically, it is automatically confirmed and/or bypasses needing confirmation entirely
5. The appointment is added to upcoming, with no option to confirm the booking, just to cancel or reschedule
6. No notifications or triggers alerted me to the booking, rendering all automation non-existent.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

1. When an event is configured to require booking confirmation, then the event is added as unconfirmed with the option of confirming the appointment or rejecting it.
2. When the trigger for a new booking occurs, all enabled workflows and webhooks should engage without manual interaction.

### Technical details

N/A

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/eef1d470-319e-4ac9-bdf6-3e052b7499dc/1542eb1b-6ff5-4f4d-bc5a-31dd07f1c5be)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5ed2a240-4da9-43ac-b6b3-370ee130ad2c/fc68c008-691d-4246-bbe0-fc896d17f771)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e44a1864-ff84-42ea-be09-215ea8556699/476dc4fc-3e60-415a-8f10-532dafb35af9)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c8f78cc8-396b-43bc-a70d-d6d495431c35/14c319a8-b709-4218-a564-f1eb13acc019)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/96feca80-d227-4a3e-b156-b0408a3d4aa1/50b2ab0f-508a-43ae-a1a0-803f48fe3d6a)

> From [SyncLinear.com](https://synclinear.com)

**Comment by CarinaWolli** [comment]
> I had a booking submitted around 4 pm EST, which requires both payment and confirmation. The booking was immediately placed in "upcoming" but did not appear under "unconfirmed."

@alannnc could that be because the event-type requires payment?

**Comment by alannnc** [comment]
@CarinaWolli That could be something but not so sure right now, we should do a test replicating this scenario and work on a fix from that.

@Kfelts Thanks for reporting we are gonna try to fix this as soon as we can.

**Comment by Kfelts** [comment]
Just wanted to follow up and say it occurred again with a new booking for me. They also aren't showing up on my calendar.

**Comment by Kfelts** [comment]
Looking further, in my email notifications, it appears that the event is automatically approved around a minute after the initial request is sent to me.
<img width="587" alt="Screenshot 2022-11-21 at 11 29 44 AM" src="https://user-images.githubusercontent.com/51497445/203108977-a8bf4bdf-875f-4e43-9673-91db8041d139.png">
<img width="626" alt="Screenshot 2022-11-21 at 11 30 42 AM" src="https://user-images.githubusercontent.com/51497445/203108984-655e6be9-84b9-4795-9929-d17035a814d3.png">
