### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by lienista** [calcom/cal.com#5543]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I could not build the project.

### Steps to Reproduce

1. `yarn dev` started server but has issue. It started the server at `localhost:3000`, rather than specified url port from `.env` file
2. `yarn build` fails 
3. environment variables: 
NEXT_PUBLIC_WEBAPP_URL='http://localhost:8000'
NEXT_PUBLIC_WEBSITE_URL='http://localhost:8000'
NEXT_PUBLIC_CONSOLE_URL='http://localhost:8004'
NEXT_PUBLIC_EMBED_LIB_URL='http://localhost:8000/embed/embed.js'
 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

# Yarn dev does not use env vars. (due to not able to build before running instance)

`yarn dev`
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1018672/202061523-2be393f8-475c-4174-9bf4-0b6c668f32a5.png">
yarn run v1.22.15
$ echo 'Checking env files'
Checking env files
$ turbo run dev --scope="@calcom/web"
• Packages in scope: @calcom/web
• Running dev in 1 packages
//:env-check:app-store: cache bypass, force executing 664b7a9cb5df0bdd
//:env-check:common: cache bypass, force executing c5c330c6628bdb7d
//:env-check:app-store: $ dotenv-checker --schema .env.appStore.example --env .env.appStore
//:env-check:common: $ dotenv-checker --schema .env.example --env .env
//:env-check:common:
//:env-check:common: [ DOTENV-CHECKER ] - Initializing checks for .env files consistency & sync...
//:env-check:common:
//:env-check:app-store:
//:env-check:app-store: [ DOTENV-CHECKER ] - Initializing checks for .env files consistency & sync...
//:env-check:app-store:
//:env-check:common: 📗 [ INFO ]  ✅ Schema file (.env.example) checked successfully
//:env-check:app-store: 📗 [ INFO ]  ✅ Schema file (.env.appStore.example) checked successfully
//:env-check:app-store: 📗 [ INFO ]  ✅ Environment file (.env.appStore) checked successfully
//:env-check:common: 🚧 [ WARN ]  ⚠️  Environment file (.env) differs from .env.example
//:env-check:common:
//:env-check:common:   !! Alert !! The following keys are not present in the ".env.example" file:
//:env-check:common:                - DB_USERNAME
//:env-check:common:                - DB_PASSWORD
//:env-check:common:                - DB_HOST
//:env-check:common:                - DB_POST
//:env-check:common:                - DB_NAME
//:env-check:common:                - SHADODOW_DB_URL
//:env-check:common:                - NEXT_PUBLIC_DEBUG
//:env-check:common:                - VERCEL_URL
//:env-check:common:
//:env-check:common: 📗 [ INFO ]  ✅ Environment file (.env) updated successfully
@calcom/web:dev: cache bypass, force executing a1bb4d2ea2e288c4
@calcom/web:dev: $ next dev
@calcom/web:dev: warn  - Port 3000 is in use, trying 3001 instead.
@calcom/web:dev: ready - started server on 0.0.0.0:3001, url: http://localhost:3001
@calcom/web:dev: warn  - Invalid next.config.js options detected:
@calcom/web:dev:   - The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
@calcom/web:dev:   - The value at .experimental has an unexpected property, images, which is not in the list of allowed properties (adjustFontFallbacks, amp, appDir, browsersListForSwc, cpus, craCompat, disableOptimizedLoading, disablePostcssPresetEnv, esmExternals, externalDir, fallbackNodePolyfills, forceSwcTransforms, fullySpecified, gzipSize, incrementalCacheHandlerPath, isrFlushToDisk, isrMemoryCacheSize, largePageDataBytes, legacyBrowsers, manualClientBasePath, modularizeImports, newNextLinkBehavior, nextScriptWorkers, optimizeCss, optimisticClientCache, outputFileTracingRoot, pageEnv, profiling, proxyTimeout, runtime, scrollRestoration, serverComponents, sharedPool, sri, swcFileReading, swcMinify, swcMinifyDebugOptions, swcPlugins, swcTraceProfiling, urlImports, workerThreads).
@calcom/web:dev:
@calcom/web:dev: See more info here: https://nextjs.org/docs/messages/invalid-next-config
@calcom/web:dev: warn  - You have enabled experimental feature (images) in next.config.js.
@calcom/web:dev: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
@calcom/web:dev:
@calcom/web:dev: warn - axiom: Envvars not detected. If this is production please see https://github.com/axiomhq/next-axiom for help
@calcom/web:dev: warn - axiom: Sending Web Vitals to /dev/null
@calcom/web:dev: warn - axiom: Sending logs to console
@calcom/web:dev: info  - automatically enabled Fast Refresh for 1 custom loader
@calcom/web:dev: event - compiled client and server successfully in 2.7s (1142 modules)
@calcom/web:dev: warn  - You are using an experimental edge runtime, the API might change.
@calcom/web:dev: wait  - compiling /auth/setup (client and server)...
@calcom/web:dev: event - compiled client and server successfully in 1673 ms (1666 modules)
@calcom/web:dev: warn(prisma) Conflict for env vars DB_USERNAME, DB_PASSWORD, DB_HOST, DB_POST, DB_NAME, SHADODOW_DB_URL, NEXT_PUBLIC_DEBUG, VERCEL_URL, NEXT_PUBLIC_LICENSE_CONSENT, CALCOM_LICENSE_KEY, DATABASE_URL, NEXT_PUBLIC_WEBAPP_URL, NEXT_PUBLIC_WEBSITE_URL, NEXT_PUBLIC_CONSOLE_URL, NEXT_PUBLIC_EMBED_LIB_URL, SAML_DATABASE_URL, SAML_ADMINS, PGSSLMODE, NEXTAUTH_URL, NEXTAUTH_SECRET, NEXTAUTH_COOKIE_DOMAIN, CALCOM_TELEMETRY_DISABLED, CRON_API_KEY, CALENDSO_ENCRYPTION_KEY, NEXT_PUBLIC_INTERCOM_APP_ID, NEXT_PUBLIC_ZENDESK_KEY, NEXT_PUBLIC_HELPSCOUT_KEY, SEND_FEEDBACK_EMAIL, SENDGRID_API_KEY, SENDGRID_EMAIL, TWILIO_SID, TWILIO_TOKEN, TWILIO_MESSAGING_SID, NEXT_PUBLIC_IS_E2E, NEXT_PUBLIC_STRIPE_PRO_PLAN_PRICE, NEXT_PUBLIC_STRIPE_PREMIUM_PLAN_PRICE, NEXT_PUBLIC_IS_PREMIUM_NEW_PLAN, NEXT_PUBLIC_STRIPE_PREMIUM_NEW_PLAN_PRICE, STRIPE_TEAM_MONTHLY_PRICE_ID, STRIPE_WEBHOOK_SECRET, STRIPE_PRIVATE_KEY, STRIPE_CLIENT_ID, API_KEY_PREFIX, EMAIL_FROM, EMAIL_SERVER_HOST, EMAIL_SERVER_PORT, EMAIL_SERVER_USER, EMAIL_SERVER_PASSWORD, NEXT_PUBLIC_TEAM_IMPERSONATION, CLOSECOM_API_KEY, NEXT_PUBLIC_SENTRY_DSN, SENTRY_IGNORE_API_RESOLUTION_ERROR in ../../.env and ../../packages/prisma/.env
@calcom/web:dev: Env vars from ../../packages/prisma/.env overwrite the ones from ../../.env
@calcom/web:dev:
@calcom/web:dev: prisma:query SELECT COUNT(*) FROM (SELECT "public"."users"."id" FROM "public"."users" WHERE 1=1 OFFSET $1) AS "sub"
@calcom/web:dev: react-i18next:: You will need to pass in an i18next instance by using initReactI18next
@calcom/web:dev: Do not add <script> tags using next/head (see inline <script>). Use next/script instead.
@calcom/web:dev: See more info here: https://nextjs.org/docs/messages/no-script-tags-in-head-component
@calcom/web:dev: wait  - compiling /middleware (client and server)...
@calcom/web:dev: wait  - compiling /api/trpc/[trpc] (client and server)...
@calcom/web:dev: event - compiled successfully in 1364 ms (854 modules)
@calcom/web:dev: wait  - compiling /api/auth/[...nextauth] (client and server)...
@calcom/web:dev: [next-auth][error][CLIENT_FETCH_ERROR]
@calcom/web:dev: https://next-auth.js.org/errors#client_fetch_error request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000 {
@calcom/web:dev:   error: {
@calcom/web:dev:     message: 'request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000',
@calcom/web:dev:     stack: 'FetchError: request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000\n' +
@calcom/web:dev:       '    at ClientRequest.<anonymous> (/Users/lien/Documents/github/letterchefs/calendso/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)\n' +
@calcom/web:dev:       '    at ClientRequest.emit (node:events:390:28)\n' +
@calcom/web:dev:       '    at ClientRequest.emit (node:domain:475:12)\n' +
@calcom/web:dev:       '    at Socket.socketErrorListener (node:_http_client:447:9)\n' +
@calcom/web:dev:       '    at Socket.emit (node:events:390:28)\n' +
@calcom/web:dev:       '    at Socket.emit (node:domain:475:12)\n' +
@calcom/web:dev:       '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
@calcom/web:dev:       '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
@calcom/web:dev:       '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
@calcom/web:dev:     name: 'FetchError'
@calcom/web:dev:   },
@calcom/web:dev:   url: 'http://localhost:8000/api/auth/session',
@calcom/web:dev:   message: 'request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000'
@calcom/web:dev: }
@calcom/web:dev: [next-auth][error][CLIENT_FETCH_ERROR]
@calcom/web:dev: https://next-auth.js.org/errors#client_fetch_error request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000 {
@calcom/web:dev:   error: {
@calcom/web:dev:     message: 'request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000',
@calcom/web:dev:     stack: 'FetchError: request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000\n' +
@calcom/web:dev:       '    at ClientRequest.<anonymous> (/Users/lien/Documents/github/letterchefs/calendso/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)\n' +
@calcom/web:dev:       '    at ClientRequest.emit (node:events:390:28)\n' +
@calcom/web:dev:       '    at ClientRequest.emit (node:domain:475:12)\n' +
@calcom/web:dev:       '    at Socket.socketErrorListener (node:_http_client:447:9)\n' +
@calcom/web:dev:       '    at Socket.emit (node:events:390:28)\n' +
@calcom/web:dev:       '    at Socket.emit (node:domain:475:12)\n' +
@calcom/web:dev:       '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
@calcom/web:dev:       '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
@calcom/web:dev:       '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
@calcom/web:dev:     name: 'FetchError'
@calcom/web:dev:   },
@calcom/web:dev:   url: 'http://localhost:8000/api/auth/session',
@calcom/web:dev:   message: 'request to http://localhost:8000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:8000'
@calcom/web:dev: }
@calcom/web:dev: [OK][0.0001s] query 'viewer.public.i18n'
@calcom/web:dev: [OK][0.0002s] query 'viewer.public.session'
@calcom/web:dev: event - compiled successfully in 390 ms (808 modules)

# Yarn build
`yarn build` (same error with `yarn dx`)

@calcom/web:build: error Command failed with exit code 1.
@calcom/web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:build: ERROR: command finished with error: command (apps/web) yarn run build exited (1)
command (apps/web) yarn run build exited (1)

 Tasks:    7 successful, 8 total
Cached:    2 cached, 8 total
  Time:    53.273s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Udit-takkar** [comment]
@lienista meanwhile can you try with these variables
```
NEXT_PUBLIC_WEBAPP_URL='http://localhost:3000'
# Change to 'http://localhost:3001' if running the website simultaneously
NEXT_PUBLIC_WEBSITE_URL='http://localhost:3000'
NEXT_PUBLIC_CONSOLE_URL='http://localhost:3004'
NEXT_PUBLIC_EMBED_LIB_URL='http://localhost:3000/embed/embed.js'
```

**Comment by lienista** [comment]
yes I did, and it defeats the purpose of build. I would need to build if I wanted to add more env vars for new features that I need

**Comment by PeerRich** [comment]
@lienista can you try the above tip + latest version?

**Comment by michaelklopf** [comment]
@PeerRich 

What do you mean trying it? You can set the `.env` vars, but they are not used, instead it takes those from deeper in the package dependencies. I have no idea how to counter that behaviour.

When you run more than one container, you don't want to use Port 3000 as it is the default port for different applications.

I have no clue how the application is put together, but something that could be related to the problem is mentioned here https://github.com/prisma/prisma/issues/18542
