### ISSUE TITLE
Landing on /undefined 404 after registration

### ISSUE THREAD

**Issue by chrisgick** [calcom/cal.com#5545]
### Issue Summary

Landing on /undefined 404 after registration of a new account

### Steps to Reproduce

1. Register new account
2. Login for the first time

**Comment by suthargk** [comment]
In which is the environment getting undefined? Can you please give steps to reproduce.

**Comment by Udit-takkar** [comment]
@chrisgick i am unable to reproduce the bug. 
i created a new account at /signup and tried logging in (auth/login) and i was redirected to /event-types ( the default page)

**Comment by chrisgick** [comment]
Seems to be fixed, I also can not reproduce it any more.
