### ISSUE TITLE
[CAL-380] Move form component (in components directory) to its own file, instead of being place in input.tsx

### ISSUE THREAD

**Issue by JeroenReumkens** [calcom/cal.com#5550]
See [https://github.com/calcom/cal.com/pull/5514#pullrequestreview-1182472654](https://github.com/calcom/cal.com/pull/5514#pullrequestreview-1182472654)

> From [SyncLinear.com](https://synclinear.com) | [CAL-380](https://linear.app/calcom/issue/CAL-380/move-form-component-in-components-directory-to-its-own-file-instead-of)

**Comment by PeerRich** [comment]
is this done?
