### ISSUE TITLE
[CAL-381] Zoom link disappears/breaks when you reschedule a meeting

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5553]
**Steps to reproduce**

* Book a call with me [https://cal.com/ciaran/catchup](https://cal.com/ciaran/catchup)
  * The zoom link gets added and Zoom is included
* Reschedule the meeting
  * The Zoom link drops off the meeting

I got an email about this but Zoom is correctly set in the event type.

![CleanShot 2022-11-16 at 14.33.30@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/66e10410-8214-4587-8c00-f166a0186685/69bb51b1-fdf5-4dd2-8a66-fb0171a1afc4)

Is removing and adding the app the only way to fix this?

> From [SyncLinear.com](https://synclinear.com) | [CAL-381](https://linear.app/calcom/issue/CAL-381/zoom-link-disappearsbreaks-when-you-reschedule-a-meeting)

**Comment by Jaibles** [comment]
Woohoo this is fixed?! 🙏

**Comment by Udit-takkar** [comment]
yes
