### ISSUE TITLE
[CAL-382] Minimum booking notice conversion are incorrect

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5555]
### Issue Summary

It seems like the Minute / Hour / Days conversion for the minimum booking notice are incorrect:

[https://user-images.githubusercontent.com/3504472/202286359-fb0cba3c-cc84-4f4a-9569-35a0f87fd023.mov](https://user-images.githubusercontent.com/3504472/202286359-fb0cba3c-cc84-4f4a-9569-35a0f87fd023.mov)

### Steps to Reproduce

1. Go to an event type page
2. Go to limits tab
3. Play around with the minimum booking notice values and see how conversion is wrong.

> From [SyncLinear.com](https://synclinear.com)

**Comment by JeroenReumkens** [comment]
Closed by #5557
