### ISSUE TITLE
[CAL-407] Better phone number field

### ISSUE THREAD

**Issue by cachil0** [calcom/cal.com#5556]
I would be good to have a more intuitive field for phone number.

Where you can choose the country, the number length based on country. Also the possiblity to pre-populate this field on URL

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
@cachil0 which page contains this phone number input field ?

**Comment by cachil0** [comment]
> @cachil0 which page contains this phone number input field ?

the only way I found to insert phone with the right pattern is choosing location as the attendee phone. I would be better to have the same field as custom input field, and also having the possibility to pre-populate this field into url parameter.

got it?
