### ISSUE TITLE
[CAL-384] Link in calendar description of a booking is missing reschedule option

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5559]
* Right now there's just a single link in the calendar description that assumes I want to cancel. 
* To reschedule I have to click "Nevermind" then reschedule..

[1257ef5e-02ad-4d36-85f4-dbfb5432f13b](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9f265e38-6abb-41ae-bd8f-d8176f55a6ce/1257ef5e-02ad-4d36-85f4-dbfb5432f13b)

It should have the options like in the email

Need to make a change? [Reschedule](http://url8844.cal.com/ls/click?upn=i3chcWsW1q3st3RzzypZscrjKOhaa-2Bnd-2Fv1W9N5JlVlCmq548sV0MDUv-2Fy1h1-2F7SYOKUGpSj2ss25JOaUf2ogw-3D-3DFRyA_LE4Bi-2FawWTK4UL841azGX4cQwvJnqGoNDb2smHZvuPDXwh-2FzotO2KviDlg-2FkLGeP71bjaIPyL5LRExSQu3vb3K1Rt614VAJOqRUNSpwEDeBHduv-2FssBXJbGBGxP0cMQiVm82hLmicNYt4S8phNbBM7ryQEMHFAis3OqGZQ8-2F3Os1GA48L7rYPfhn-2BPr1utUfeUwNYVm52cq-2F60frwfXksQ-3D-3D) or [Cancel](http://url8844.cal.com/ls/click?upn=i3chcWsW1q3st3RzzypZsT67h-2Be13oZ7eVyg6MDUBqVwXUYAaJtwmaFaGgFSE6-2Bx7ngrf7sRim1NNPLE9fpZYA-3D-3DqnX3_LE4Bi-2FawWTK4UL841azGX4cQwvJnqGoNDb2smHZvuPDXwh-2FzotO2KviDlg-2FkLGePPE0LLmIfgdkLP94AnHHEH4c2f-2FyzgmryZ9hoLaYix87VY6NMLi3Z-2BYChIJ-2FSkt-2FHHFC-2BqDgr2S9rZXmeR-2B0JLcddeUDx2xrdFCF6GCNhQyZNUsL4IUwQ0ihsM-2Bj4oXYCq-2FG4tDigDOBDRsRhe5kEVQ-3D-3D)

![CleanShot 2022-11-17 at 08.03.55@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4e93c85d-0010-4532-9be4-dfa332fc805a/2c802d2b-36e8-469e-a5af-ec4e58d4fc01)

This spacing also needs to be fixed in the email 👆

> From [SyncLinear.com](https://synclinear.com) | [CAL-384](https://linear.app/calcom/issue/CAL-384/link-in-calendar-description-of-a-booking-is-missing-reschedule-option)

**Comment by niteshsingh1357** [comment]
Hey @Jaibles, I think recent changes have resolved this issue. Now the link in the description is
http://localhost:3000/booking/eZCQX9ue7ANc4wXVAGc2NZ?changes=true
which redirects to the following page
<img width="669" alt="Screenshot 2022-12-05 at 10 08 42 AM" src="https://user-images.githubusercontent.com/31402501/205549486-e773d986-66e0-49a9-b068-4f90956be5c8.png">
