### ISSUE TITLE
[CAL-387] Admin view to see all bookings per collective events

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5565]
Admins/Owners should be able to see the bookings per collective event. A similar experience to how you can go to the bookings tab and see your individual bookings.

A good example is the [cal.com/team/cal/shiraz](http://cal.com/team/cal/shiraz) link — it would be awesome to have a bookings tab in the settings where I can see all the bookings Peer and I have had. It would also be good to highlight who is exactly assigned to those bookings if it's a round robin.

> From [SyncLinear.com](https://synclinear.com) | [CAL-387](https://linear.app/calcom/issue/CAL-387/admin-view-to-see-all-bookings-per-collective-eventsi)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-387](https://linear.app/calcom/issue/CAL-387/admin-view-to-see-all-bookings-per-collective-events)</sub>

**Comment by erik-bower-daily** [comment]
This story will be complete when: 

- A team admin can go to teams, bookings and see all the meetings across team members. 
- A team admin can see if any meeting requests have not been accepted by a sales rep
- A team admin can reassign a calendar invite to another sales person if for some reason there is a conflict or the account belongs to another rep, or the rep hasn't accepted the invite in the proper amount of time

Bonus points if you can provide a way to capture UTM parameters on the meeting requestor and then push all meeting requestors into salesforce into a single campaign as campaign members with the utm attribution attached. THat would give me as a marketing person complete visibility into what is converting and would allow attribution for deals to be attributed to cal.com Effectively if you do this, then we can do away with reg forms entirely. But for that we'd need to be able to stop bogus submissions - check out this servcie: https://demo.serviceobjects.com/LeadValidationInternational/ValidateLeadInternationalExamples. I've had this idea for a while now that event registration like splashthat, hubspot, etc - you could do away with reg forms and have people register by adding to calendar. ANyways - too much scope for this ticket< i'll be happy just being able to manage the sales people and also just being able to see if the embed is working.

**Comment by shirazdole** [comment]
cc @Jaibles on the above

**Comment by Jaibles** [comment]
Cheers @shirazdole I'm going to work on the designs this week

**Comment by shirazdole** [comment]
@Jaibles legend!!

**Comment by shirazdole** [comment]
Designs are fantastic @Jaibles — especially the reassign one! Great work 🚀

**Comment by shirazdole** [comment]
@erik-bower-daily created a ticket for the tracking: https://github.com/calcom/cal.com/issues/5870

**Comment by aasargsian** [comment]
@shirazdole @erik-bower-daily we are also looking for a way to capture UTM parameters
