### ISSUE TITLE
[CAL-388] Cannot Delete Pending Members

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5567]
I'm trying to remove a member from a team and I get this prompt, is it worth a thread or a ticket?

After waiting several minutes, the member from my team was deleted.

Not sure exactly what is happening.

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=b670e596-be0a-43f2-b625-d91c7882e5dc](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=b670e596-be0a-43f2-b625-d91c7882e5dc)

> From [SyncLinear.com](https://synclinear.com) | [CAL-388](https://linear.app/calcom/issue/CAL-388/cannot-delete-pending-members)

**Comment by shirazdole** [comment]
cc @zomars - I believe you built user deletion

**Comment by zomars** [comment]
It sounds like some cache invalidation issue. Since the team is actually being deleted.

**Comment by PeerRich** [comment]
is this still happening?
