### ISSUE TITLE
[CAL-389] If Outlook is the default calendar GMeet URL not generated

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#5568]
If Outlook is the default destination calendar GMeet URL doesn't get generated

Created via Threads. See full discussion: [https://threads.com/34434383642](https://threads.com/34434383642)

> From [SyncLinear.com](https://synclinear.com) | [CAL-389](https://linear.app/calcom/issue/CAL-389/if-outlook-is-the-default-calendar-gmeet-url-not-generated)

**Comment by PeerRich** [comment]
yes, that is a known issue based on how google meet is currently implemented. @zomars i think had some ideas how we can make google meet independent of google calendar
