### ISSUE TITLE
[CAL-392] top banner not responsive

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5578]
https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6548026c-f818-470b-a331-e2ac66d5e574/cd681ef2-87b2-46b7-b4ff-ce3cf10b1e4a

> From [SyncLinear.com](https://synclinear.com) | [CAL-392](https://linear.app/calcom/issue/CAL-392/top-banner-not-responsive)

**Comment by PeerRich** [comment]
@Udit-takkar wanna take this up?

**Comment by Udit-takkar** [comment]
@Jaibles any figma for mobile view of top banner ?

**Comment by Jaibles** [comment]
@Udit-takkar 
https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=21311%3A144646&t=BTohhd5ULMwJ2CLG-1

<img width="375" alt="CleanShot 2022-11-21 at 14 52 37@2x" src="https://user-images.githubusercontent.com/4536123/203085450-f77c2e95-2a8c-4cda-aaff-927fa3014d9f.png">

**Comment by Udit-takkar** [comment]
![image](https://user-images.githubusercontent.com/53316345/203097149-a3f7dbc8-583a-4e2d-b777-569bb1ca2a13.png)

banner z index bug when a modal is open
