### ISSUE TITLE
[CAL-396] hard to read black on black text on select popups

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#5582]
### Issue Summary

On nearly all of my devices the selection popup text is hard to read, because it's black on black. On some it works, but on hovering it's having the same issue.

### Technical details

* safari, chrome or cal for mac
* theme is system standard
* brand colours #db5cff for light theme and #fafafa for dark theme
* already user before cal 2.0

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1ef6e6cb-c900-4dfe-a1e6-ae3b856f53b2/3de4395b-8d8c-43c1-8ac2-b23476c49135)

[https://user-images.githubusercontent.com/88643432/202698698-db0b4fb3-6844-4621-baa4-c0bab7f55809.mov](https://user-images.githubusercontent.com/88643432/202698698-db0b4fb3-6844-4621-baa4-c0bab7f55809.mov)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
@jorit-vasconezgerlach thanks for reporting this. although i am not able to reproduce i will take a look at the code

https://user-images.githubusercontent.com/53316345/202716934-87ae6b58-d7f1-40d6-a415-540f1fd5c588.mov

**Comment by Udit-takkar** [comment]
just use 292929 brand color in light theme.
<img width="1439" alt="Screenshot 2022-11-18 at 10 33 38 PM" src="https://user-images.githubusercontent.com/53316345/202760901-7051bcbb-1695-47aa-9a66-39d93f70a578.png">

**Comment by jorit-vasconezgerlach** [comment]
Thank's this works. For the general user base it may be good to either disable this functionality completely or implement it so that
- the UI doesn't broke
- it really effects the theme and not only some outline

**Comment by Udit-takkar** [comment]
@jorit-vasconezgerlach  ok thanks for your feedback
