### ISSUE TITLE
[CAL-400] faster copying of private link & no access to public link if private link is enabled

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#5583]
### Is your proposal related to a problem?

It's kind of annoying to every time have to go on edit mode to copy the private event link. so yes.

### Describe the solution you'd like

If the option 'generate private link' is enabled on an event, on the event overview the copy button should directly provide you the private link.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7e5524d9-a45e-408d-8ac3-7c522cd88eef/ea9df743-3f81-4af2-81c8-2edeaa6be072)

For me the option copying the public link when the event is private doesn't make sense. I'd also **remove the public link** completely so that no-one can rebook the event without a new private link. There may be a select when the private link is enabled to choose where users should redirect to ('event overview (standard)', 'specified url', 'event x', 'event y', ...)

If people really need public and private then the solution would be having a switch or adding an option to the select "also allow public link" and if this is enabled the user should be asked on copying the link trough event overview: "You want to copy the public or private link?"

### Additional context

summary of my request

* [ ] if event has 'generate private link' option enabled, the link copy button on event overview should provide you with the private link
* [ ] if private link is enabled do not allow people to use this event, redirect them to the event overview or specific event

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
great feedback, @alishaz-polymath can take a look. he built the private events

**Comment by alishaz-polymath** [comment]
@PeerRich I'm not 100% sure if we wish to disable the public link if we enable generation of private link primarily because it is a one-time use link to begin with. The idea of a private link generation and use is to be able to share the event without really sharing the permanent slug of the event, and is focused towards a one-time usage. 
cc: @Jaibles What do you think?
