### ISSUE TITLE
Nextjs error on performe "yarn dev"

### ISSUE THREAD

**Issue by thomasmazon** [calcom/cal.com#5586]
Wndows: 10 Pro
Node: v16.15.0
yarn workspace v1.22.19
yarn run v1.22.19

@calcom/web:dev: error - Cannot read properties of null (reading '1')

unable to execute project.

`@calcom/web:dev: error - Error: Cannot find module 'G:\source\open-source\cal.com\apps\web\.next\fallback-build-manifest.json'
@calcom/web:dev: Require stack:
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\load-components.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\next-server.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\next.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\lib\start-server.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\cli\next-dev.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\lib\commands.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\bin\next
@calcom/web:dev:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
@calcom/web:dev:     at Function.mod._resolveFilename (G:\source\open-source\cal.com\node_modules\next\dist\build\webpack\require-hook.js:27:32)
@calcom/web:dev:     at Function.mod._resolveFilename (G:\source\open-source\cal.com\node_modules\next\dist\build\webpack\require-hook.js:27:32)
@calcom/web:dev:     at Function.mod._resolveFilename (G:\source\open-source\cal.com\node_modules\next\dist\build\webpack\require-hook.js:27:32)
@calcom/web:dev:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
@calcom/web:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@calcom/web:dev:     at require (node:internal/modules/cjs/helpers:102:18)
@calcom/web:dev:     at Object.loadDefaultErrorComponents (G:\source\open-source\cal.com\node_modules\next\dist\server\load-components.js:22:24)
@calcom/web:dev:     at DevServer.getFallbackErrorComponents (G:\source\open-source\cal.com\node_modules\next\dist\server\dev\next-dev-server.js:1008:43)
@calcom/web:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
@calcom/web:dev:   code: 'MODULE_NOT_FOUND',
@calcom/web:dev:   requireStack: [
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\load-components.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\next-server.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\next.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\lib\\start-server.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\cli\\next-dev.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\lib\\commands.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\bin\\next'
@calcom/web:dev:   ]
@calcom/web:dev: }
@calcom/web:dev: Error: Cannot find module 'G:\source\open-source\cal.com\apps\web\.next\fallback-build-manifest.json'
@calcom/web:dev: Require stack:
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\load-components.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\next-server.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\next.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\server\lib\start-server.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\cli\next-dev.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\lib\commands.js
@calcom/web:dev: - G:\source\open-source\cal.com\node_modules\next\dist\bin\next
@calcom/web:dev:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
@calcom/web:dev:     at Function.mod._resolveFilename (G:\source\open-source\cal.com\node_modules\next\dist\build\webpack\require-hook.js:27:32)
@calcom/web:dev:     at Function.mod._resolveFilename (G:\source\open-source\cal.com\node_modules\next\dist\build\webpack\require-hook.js:27:32)
@calcom/web:dev:     at Function.mod._resolveFilename (G:\source\open-source\cal.com\node_modules\next\dist\build\webpack\require-hook.js:27:32)
@calcom/web:dev:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
@calcom/web:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@calcom/web:dev:     at require (node:internal/modules/cjs/helpers:102:18)
@calcom/web:dev:     at Object.loadDefaultErrorComponents (G:\source\open-source\cal.com\node_modules\next\dist\server\load-components.js:22:24)
@calcom/web:dev:     at DevServer.getFallbackErrorComponents (G:\source\open-source\cal.com\node_modules\next\dist\server\dev\next-dev-server.js:1008:43)
@calcom/web:dev:     at async DevServer.renderErrorToResponse (G:\source\open-source\cal.com\node_modules\next\dist\server\base-server.js:1093:40) {
@calcom/web:dev:   code: 'MODULE_NOT_FOUND',
@calcom/web:dev:   requireStack: [
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\load-components.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\next-server.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\next.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\server\\lib\\start-server.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\cli\\next-dev.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\lib\\commands.js',
@calcom/web:dev:     'G:\\source\\open-source\\cal.com\\node_modules\\next\\dist\\bin\\next'
@calcom/web:dev:   ]
@calcom/web:dev: }`

**Comment by gGh00sTt** [comment]
Running `yarn install` might help

**Comment by PeerRich** [comment]
can you try 

`yarn`

`yarn dx` (make sure docker is up and running)

**Comment by PeerRich** [comment]
yarn dx works. let me know if i have to reopen
