### ISSUE TITLE
[CAL-399] Events are added twice to calendars

### ISSUE THREAD

**Issue by jahirfiquitiva** [calcom/cal.com#5588]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When an event is created I get two events: one in the default account calendar, and one in the calendar that I have chosen in `cal.com`

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0b6b038e-1b6e-4ee2-b6b2-2c400a6cdd85/fbfd7b09-3ccd-4bcb-89aa-bd43ae2b590a)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c57051f4-c77d-43c3-8724-9a7383fdd722/6abaecc8-69f6-4ef1-a2cf-8c83f5d618db)

☝️
Blue is events added to my default email calendar.
Pink is events added to the secondary calendar I've setup to add events to (`calcom`)

### Steps to Reproduce

1. Setup a secondary calendar as the calendar to add events to.
2. Schedule a meeting
3. Get events in both your default account calendar and the secondary you setup.

### Technical details

* Browser version, screen recording, console logs, network requests: All browsers. Happens with anyone scheduling a meeting with me.

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
interesting, we'll investigate!

**Comment by jahirfiquitiva** [comment]
@PeerRich giving it a more detailed look, I noticed a few things:

- the pink calendar events (default for `cal.com`) are events where I'm kind of the organizer, there are no options to confirm/deny attendance, and I can also see everyone in the meeting.
- the blue calendar events (my personal calendar) are events where I'm like an attendee, I can confirm if I'm attending or not, and I cannot see other attendees

![Shot 2022-11-23 at 10 54 59@2x](https://user-images.githubusercontent.com/10360816/203592008-0c0b2f04-ef38-4bec-86a8-e7585d016222.png)
![Shot 2022-11-23 at 10 53 53@2x](https://user-images.githubusercontent.com/10360816/203592014-6e35cfb3-cb90-45cd-aae6-bb0c9766b659.png)

**Comment by PeerRich** [comment]
@alishaz-polymath or @Udit-takkar can you try to reproduce this?

**Comment by Guray00** [comment]
i don't know if it is my bad, but i have the same problem. I have set event "A" to add to google calendar "category X" in both the event setting and calendar setting, but I get 2 event on the calendar: one in "Category X" and one in "general calendar".

**Comment by rebryk** [comment]
I have the same issue :(
