### ISSUE TITLE
[CAL-406] "link-based" apps in app store open in two external tabs

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5600]
to debug:

in packages/app-store/pipedream/api/add.ts

there is in line 13: `redirect` which takes an URL and `newTab` true

[https://www.loom.com/share/bb15f730593c475b9d82990544ffe172](https://www.loom.com/share/bb15f730593c475b9d82990544ffe172)

> From [SyncLinear.com](https://synclinear.com) | [CAL-406](https://linear.app/calcom/issue/CAL-406/link-based-apps-in-app-store-open-in-two-external-tabs)

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/203347609-a6204966-956f-4b2a-a8f9-7b67cbe24314.mov

not able to reproduce.

**Comment by PeerRich** [comment]
ok closing for now
