### ISSUE TITLE
[CAL-417] “e is undefined” error when adding CalDAV

### ISSUE THREAD

**Issue by xplosionmind** [calcom/cal.com#5604]
### Issue Summary

I see the following error when trying to add a Nextcloud CalDAV url to my [cal.com](http://cal.com) account. **Note**: I already added another CalDAV Nextcloud calendar and everything went smoothly.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2efd6216-ba6f-42f5-8048-e37a8783cf94/35a8dc6a-e4f9-46ff-a26e-6a7f7a9f1dc8)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0dd4c500-9009-42e6-a94a-56df0d347928/f663aa4b-ab58-4b0b-8e3b-33ea76575a38)

### Steps to Reproduce

1. Click on “add CalDAV” calendar in `https://app.cal.com/apps/installed/calendar?hl=caldav-calendar`
2. Trying to add two different URLs: `https://nuvola.scambi.org/apps/calendar/p/zogAXYXHjYHwksDp` (public calendar link) and `https://nuvola.scambi.org/remote.php/dav/principals/users/tommi/`
3. The error I shared pops up

---

Related to #3457

> From [SyncLinear.com](https://synclinear.com)

**Comment by alishaz-polymath** [comment]
Thanks for the report. I'll add it to the list 🙏

**Comment by larseggert** [comment]
Same issue here against a https://sabre.io/baikal/ server

**Comment by alishaz-polymath** [comment]
Hey @larseggert could you please provide me with steps to reproduce the error?
Thanks

**Comment by alishaz-polymath** [comment]
Hey @xplosionmind 
Could you please create a test account and share credentials with me so that I can test it locally?
Thanks 🙏

**Comment by handkerchief333** [comment]
I have the same problem with my Nextcloud calendar.

My steps to reproduce:
1. Install a nextcloud instance with the setup-nextcloud.php from the community: 
https://nextcloud.com/install/
DOWNLOAD Server --> COMMUNITY PROJECTS --> Web installer
2. On your installed Nextcloud platform, go to the Calendar: /index.php/apps/calendar/dayGridMonth/now
3. On the bottom left, click on "calendar settings"
4. Click on "copy CalDAV address"
5. This gives you something like this: https://yourownnextcloudurl/remote.php/dav
6. Switch to your cal.com account: /apps/caldav-calendar
7. Click on install app
8. Fill in the url from step 5.
9. Fill in your nextcloud login credencials
10. Boom, same error message "e is undefined".

PS: The same CalDAV sync with my nextcloud calendar was successful for my android calendar, with DAVx5: 
https://docs.nextcloud.com/server/latest/user_manual/en/groupware/sync_android.html#with-the-nextcloud-mobile-app

Does this information help you or is there anything else i can do?

Greetings

**Comment by xplosionmind** [comment]
> Could you please create a test account and share credentials with me so that I can test it locally?

Hi @alishaz-polymath, sure! But I do not understand, do you want me to create a test account on the CalDAV server or on cal.com, or both?

**Comment by alishaz-polymath** [comment]
just the CalDAV server @xplosionmind 
Essentially, I'll connect to that account in a local instance of Cal.com and run diagnostics to see what's going on. 🙏

**Comment by xplosionmind** [comment]
Ok, I did it. Where could I share the credentials privately?

**Comment by alishaz-polymath** [comment]
> Ok, I did it. Where could I share the credentials privately?

You can send them over to `ali@cal.com` Thanks :)

**Comment by alishaz-polymath** [comment]
Hey guys, just an update that we're going through revamping the CalDAV integration as it is quite unpredictable at the moment. I'll report back once there's more to add. 🙏

**Comment by alishaz-polymath** [comment]
Hey @xplosionmind Just as a FYI, I'm currently working on re-building CalDAV setup from scratch, so this might take a bit of time. We're currently planning to fully support iCalendar 2.0 ([RFC-5545](https://www.rfc-editor.org/rfc/rfc5545)) as that seems to be a more robust solution altogether. 🙏 
I'll keep you guys posted here as I progress. Thank you for your wait in the mean time 🙌
