### ISSUE TITLE
[CAL-408] Fixed Round Robin

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5605]
MVP of Fixed Round Robin

Person A is fixed Person B round robins through a pool of individuals selected in the event type

> From [SyncLinear.com](https://synclinear.com) | [CAL-408](https://linear.app/calcom/issue/CAL-408/fixed-round-robin)

**Comment by Jaibles** [comment]
Designs for this feature here

[ ↳ Fixed Round Robin - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=369%3A57072&t=wHxAuMzYCHqUG9ri-1)
