### ISSUE TITLE
[CAL-409] Weighted Round Robin

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5606]
Apply weights to the Round Robin attendees

Potential weights:

* Based on # of bookings
* Based on seniority
* Based on a star system (5 Stars, person with a 4 star is selected over person given a 3 star)

> From [SyncLinear.com](https://synclinear.com) | [CAL-409](https://linear.app/calcom/issue/CAL-409/weighted-round-robin)

**Comment by keithwillcode** [comment]
Could be related to #11545 11545
