### ISSUE TITLE
[CAL-411] Round Robin Handover

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5608]
The scenario is when there is an Account Executive (Person A) on a Fixed Round Robin with a DevRel (Person B) Round Robining on their link.

When an AE has a call booked, but they want to reschedule the Round Robin Dev Rel to another Dev Rel, there is not an easy way to do that.

* Person A is the Fixed Attendee and Person B is the Round Robin Attendee
* If Person B (DevRel) is already selected, *the ask is to be able to* reassign Person B
* You can then pick from a drop down from Person C, Person D, Person E (etc) of who you want to reschedule in.
* Bonus points if you can see who is actual available at that time (Maybe a green dot next to their name)

Another ask is to have the ability to easily see everyones availability in one place for the reschedule as well. Potentially show a list of available DevRels that could be slotted in (this is kind of the same thing being asked but in a different format presented).

> From [SyncLinear.com](https://synclinear.com) | [CAL-411](https://linear.app/calcom/issue/CAL-411/easily-reschedule-person-b-in-a-round-robin)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-411](https://linear.app/calcom/issue/CAL-411/easily-reschedule-person-b-in-a-round-robin)</sub>

**Comment by shirazdole** [comment]
@samuells would you want to give AEs the ability to edit anything in the event? 

Some scenarios on my mind:
- AEs can edit everything in the event-type
- AEs cannnot edit anything in the event-type
- AEs can edit everything BUT the round-robin 

Based on your answers @Jaibles can brainstorm ways to maybe have toggles in place to adjust levels of permission per team event type

**Comment by samuells** [comment]
I would go for not able to edit (2.) if I would need to choose one - because they will not have the whole context and they don't need to know everything. I would love to have a dedicated person who will just do it for them.

**Comment by shirazdole** [comment]
Great, thank you! @samuells

**Comment by emrysal** [comment]
Descoped for v3.2 - planned for v3.3

**Comment by CarinaWolli** [comment]
@joeauyeung Can we close this? We can instead create a separate issue for 'reassign RR host to a specific available host'
