### ISSUE TITLE
[CAL-412] Teams Onboarding - UI quick wins

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5611]
[https://www.loom.com/share/b1732998a2b84a2dacc8a2b9e2d73cbb](https://www.loom.com/share/b1732998a2b84a2dacc8a2b9e2d73cbb)

@Udit-takkar I'll provide designs for these but some of them are possible to tackle even without.

[Create a team → Step 1 - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A69689&t=hHQFqEMaQohJZFMR-1)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
<img width="603" alt="Screenshot 2022-11-24 at 6 58 23 PM" src="https://user-images.githubusercontent.com/53316345/203795943-588397a7-18f4-42e2-8c5e-4edf51181e79.png">

should i change the label to email instead of "email or username" ?

**Comment by Jaibles** [comment]
are we able to add someone via username?

**Comment by Udit-takkar** [comment]
ok it is also working if i enter cal username. but this was not written in designs on figma.

**Comment by Jaibles** [comment]
yea sorry an oversight on my part. I didn't realise we could.
