### ISSUE TITLE
[CAL-415] Social Image no longer working on WhatsApp after commit: File size too big

### ISSUE THREAD

**Issue by theJoshMuller** [calcom/cal.com#5613]
### Issue Summary

In the past, sharing my [Cal.com](http://Cal.com) link on WhatsApp showed the social image/`og:image` properly, until October 17. All my subsequent shares don't show the social image.

The problem appears to be because of file-size. [WhatsApp's Social Images are limited to a maximum of 300kb](https://stackoverflow.com/a/39182227) in size, where the current file size of the `og:image` that the `/api/social/og/image` API returns (at least, on my personal [Cal.com](http://Cal.com) link) clocks in at **771kb**.

Looks like the commits that caused the change was probably [5c01467](https://github.com/calcom/cal.com/commit/5c01467caab0e49ac517d1a624c6859587945861).

*Ultimately, the file size of the image produced by the* `/api/social/og/image` needs to be reduced to 300kb or less, or it won't show up when sharing on WhatsApp.

### Steps to Reproduce

1. Share personal [Cal.com](http://Cal.com) link on WhatsApp
2. Title and description information will correctly be pulled from meta-data, but social image will not show

*Why do you consider this a bug and what did you expect to happen instead?*

WhatsApp is used by 2 billion people. Would be great if the social images could show up again like they used to. Feature regression isn't super fun.

### Technical details

* Android 10
* WhatsApp version 2.22.23.77

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
@JeroenReumkens can you look at this when you are back from OOO?

**Comment by theJoshMuller** [comment]
Thanks @PeerRich & @JeroenReumkens !
