### ISSUE TITLE
[CAL-419] Intercom app

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#5617]
Create an Intercom app similar to Calendly: [https://www.intercom.com/app-store/apps/calendly](https://www.intercom.com/app-store/apps/calendly)

> From [SyncLinear.com](https://synclinear.com) | [CAL-419](https://linear.app/calcom/issue/CAL-419/intercom-app)

**Comment by PeerRich** [comment]
duplicate of https://github.com/calcom/cal.com/issues/1490
