### ISSUE TITLE
Password requirement mismatches backend in setup wizard

### ISSUE THREAD

**Issue by krumware** [calcom/cal.com#5620]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

New installations currently require a 15 character minimum on passwords for the new user, but the UI says 8 characters. The failure is not reflected to the UI, and the spinner stays active.

Expected:
UI should handle the error
UI should also probably match the requirements being enforced by the backend (or visa versa).

### Steps to Reproduce

1. Create a fresh installation
2. Access the UI
3. Attempt to set up user account with a password that matches the UI requirements, but less than 15 characters
4. Observe forever-spinner
5. Check network tab for more info

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by Udit-takkar** [comment]
hey @krumware  thanks for reporting this bug. i have fixed this already here https://github.com/calcom/cal.com/pull/5577 and it will be pushed to production in few days.

**Comment by krumware** [comment]
awesome, sorry for the double report! Thanks!

**Comment by leog** [comment]
Closing as was fixed in #5577
