### ISSUE TITLE
[CAL-432] On impersonation, a blank page loads first.  You must refresh to see anything.  

### ISSUE THREAD

**Issue by melissamarvin** [calcom/cal.com#5625]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On first impersonating another user, a blank screen loads.  See video for dev console error.

### Steps to Reproduce

1. login with a user with admin permissions
2. click settings
3. click impersonate under admin
4. enter the person you wish to impersonate
5. click impersonate

Notice the page that loads is blank

similar behavior to this bug
[https://github.com/calcom/cal.com/issues/5382](https://github.com/calcom/cal.com/issues/5382)

### Technical details

Self hosted, v2.2.2

[https://user-images.githubusercontent.com/117048096/203171103-ffff935e-5ce8-4f59-b4f2-926d22dece4f.mp4](https://user-images.githubusercontent.com/117048096/203171103-ffff935e-5ce8-4f59-b4f2-926d22dece4f.mp4)

> From [SyncLinear.com](https://synclinear.com)

**Comment by sean-brydon** [comment]
Hi thanks for reporting this :) I'll investigate this issue in the next few days @melissamarvin
