### ISSUE TITLE
[CAL-430] Event confirmation page shows incorrect event name

### ISSUE THREAD

**Issue by jahirfiquitiva** [calcom/cal.com#5626]
### Issue Summary

I have setup my event to have the name `{ATTENDEE} / {HOST}`, but the confirmation page is showing it as `{HOST} / {HOST}`.

This does not affect the event created in calendars.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/46ce2910-3b3e-4cd1-825c-b1171a7f02e5/72a15deb-c13f-4072-a6df-d3b63643a76f)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c3186871-a693-4905-8c60-f3c83e9a7514/9c2a1ea8-2116-49d8-a0ab-4c757186e806)

### Steps to Reproduce

1. Change event name to `{ATTENDEE} / {HOST}`
2. Schedule a meeting/event.
3. Get to the confirmation page to see `{HOST} / {HOST}`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Browser version, screen recording, console logs, network requests: [Bird Eats Bug recording](https://app.birdeatsbug.com/sessions/6_phJTNT3d3FIRrgyYx9THuEegEZe0IIvyUs70PsfDbg)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Udit-takkar** [comment]
hey @jahirfiquitiva thanks for reporting this bug. we are investigating it.
