### ISSUE TITLE
[CAL-423] Video/Conferencing App category naming inconsistency

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5628]
It's called "Video" in the app store and "Conferencing" in Installed apps.

Change it to Conferencing in the app store.

> From [SyncLinear.com](https://synclinear.com) | [CAL-423](https://linear.app/calcom/issue/CAL-423/videoconferencing-app-category-naming-inconsistency)

**Comment by PeerRich** [comment]
just double checked. renaming from video to conferencing will bork a lot of active URLs such as app.cal.com/apps/categories/videos

**Comment by PeerRich** [comment]
closing for now since renaming could bork a lot of routes

**Comment by Jaibles** [comment]
@PeerRich what about changing "Conferencing" to "Video" in installed apps then?

**Comment by PeerRich** [comment]
that may bork it in other places. I could research

**Comment by PeerRich** [comment]
yup. similar effort / risk ratio of borking something unfortunately. reminder: be careful when naming things haha
