### ISSUE TITLE
[CAL-424] Ability to set a default conferencing app

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5629]
We need to add the ability to set a default conferencing app.

* **Issue 1:** After creating an account and connecting a Google calendar, both Cal Video & Google Meet appear to be defaults. I don't understand how you can have two defaults, it should be one or the other.
* **Issue 2:**
  * I should be able to set which one is the default
  * I should also be able to install a new conferencing app and set that as a default.

**Current**

![CleanShot 2022-11-22 at 10.22.19@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b3b4dd4f-fd1d-4963-b7d3-4c8cfad7356f/46003088-0e3b-4e26-a9f8-0ad80f915726)

**Should be**

![CleanShot 2022-11-22 at 10.25.21@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/801b638f-7ace-4113-bf26-f1f6bbe9cd85/ec18ec35-1de3-4efa-bd61-084663c238be)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=1440%3A65904&t=MZpjLyBpov163H9F-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-424](https://linear.app/calcom/issue/CAL-424/ability-to-set-a-default-conferencing-app)</sub>

**Comment by rene-mueller** [comment]
@Jaibles what about Dynamic Events?

**Comment by PeerRich** [comment]
i wonder how that would work if people have different dynamic events

**Comment by PeerRich** [comment]
maybe the first person in the link will be used? like cal.com/peer+bailey will have my default whereas cal.com/bailey+peer has bailey's default

**Comment by PeerRich** [comment]
@Jaibles btw. the default here is actually a wrong word, it should be "installed"

because right now there is no way to uninstall google meet. we should change that and keep Cal Video as default for now.

![CleanShot 2022-11-24 at 18 43 11](https://user-images.githubusercontent.com/8019099/203849477-d56e476b-7e51-4451-a45d-0adb3ebcb993.jpg)

**Comment by Jaibles** [comment]
Right, Cal video should start as the default but you should be able to change the default right?

**Comment by rene-mueller** [comment]
@Jaibles I think it's good as a default, but it should be changeable, possibly in the admin area for self-hosted. For dynamic events, the default should come from the first person, as @PeerRich wrote.

**Comment by Jaibles** [comment]
> ...it should be changeable, possibly in the admin area for self-hosted.

Why not closer to the installed app like the designs above?

**Comment by PeerRich** [comment]
i think on cal.com it should always be cal video as default when creating new event types

its easy enough to change

i see this as a low priority, high complexity issue

rather postpone to be honest

**Comment by Jaibles** [comment]
Is it not a quick fix to at least just communicate that cal video is the default?

**Comment by Jaibles** [comment]
![CleanShot 2023-01-27 at 13.10.59@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4ac3aa85-3d7c-4b21-8a76-4c29884e6873/db4d76ed-613e-4c2a-9812-5e96870474f7)

Another request for this. Is it really that complicated to fix yea? Not sure I see this as low priority given the poor ux it creates.

**Comment by Jaibles** [comment]
Setting the default in the Installed Apps page:

[App Store - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A56982&t=JxClWoJllqV3zJeC-1)

Setting the default in settings:

[📐SPEC: Settings/ My Account/ Conferencing - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A60417&t=JxClWoJllqV3zJeC-1)

**Comment by Jaibles** [comment]
Related: [https://linear.app/calcom/issue/PRO-65/discuss-defaults-for-locations-teams-maybe-too](https://linear.app/calcom/issue/PRO-65/discuss-defaults-for-locations-teams-maybe-too)
