### ISSUE TITLE
[CAL-427] Event type location - Improve the dropdown menu in location edit modal

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5631]
**Current**

![CleanShot 2022-11-22 at 10.56.43@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/72a0bbaa-cf18-4cee-9c14-78dadb8fe758/9032b899-6281-4a53-ab4d-e6448f5bfff3)

**Optimal**

![CleanShot 2022-11-22 at 11.01.19@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6021ffab-7477-40c1-90ea-e35f8588de7e/bc67a371-cc4c-4e78-b511-dd1f99221a27)

If we can't add titles & icons can we at least make it bigger (higher), order the items better and make the terms consistent?

> From [SyncLinear.com](https://synclinear.com)

**Comment by PeerRich** [comment]
agree, both changes are very useful. we can definitley show the logo
