### ISSUE TITLE
[CAL-438] gCal without selected calendars still blocks availablity

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5655]
@zomars No, i didnt connect google Cal – do i need to in order to send emails as google cal event?

I didn't connect it as it's working buggy:
• When it's not connected, all availabilities a displayed correctly (see first screenshot).
• When it's connected *without the calendars toggled for checking conflicts*, immediately some availabilities in my calcom disappear. How come?
I only want the event to be added in my google calendar, but calcom should not check for conflicts.

I could build a workaround with zapier, but i guess it should work with you google cal app integration. But toggle option doesnt work for me – please help :)

[Video Reference](https://calendso.slack.com/files/U047NUEQSCW/F04FRF4LUKD/cal.mov)

> From [SyncLinear.com](https://synclinear.com) | [CAL-438](https://linear.app/calcom/issue/CAL-438/gcal-without-selected-calendars-still-blocks-availablity)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-438](https://linear.app/calcom/issue/CAL-438/gcal-without-selected-calendars-still-blocks-availablity)</sub>

**Comment by alannnc** [comment]
@zomars It could be. We should verify this on the DB.

**Comment by alishaz-polymath** [comment]
I've added the video reference to the summary of this issue. Apparently, **when no calendar is toggled**, the availability is checked against **all calendars**. So, this might be a simple case of unintended bad check.

**Comment by PeerRich** [comment]
can we force a default? as in, you cant deselect a calendar and min. have one?

**Comment by roae** [comment]
> can we force a default? as in, you cant deselect a calendar and min. have one?

@PeerRich I think we can force at least one to be selected. like this #4384

**Comment by hariombalhara** [comment]
I don't have the entire context. [Video Reference link](https://calendso.slack.com/files/U047NUEQSCW/F04FRF4LUKD/cal.mov) is also not working.

Confirming the requirement:
- We need to prevent deselecting all the calendars. There must always be one calendar selected at all times?
- By doing this it is clear to user that atleast one calendar would be checked for availability. But this doesn't solve the initial user problem where he didn't want any calendar to be checked for availability, but he wanted to create events on the calendar.

**Comment by PeerRich** [comment]
who wants to look into this? @roae @hariombalhara

**Comment by roae** [comment]
This was fixed here [https://github.com/calcom/cal.com/pull/9192](https://github.com/calcom/cal.com/pull/9192), it seems the getAvailability function is getting events for the calendar event if the user has no calendar selected in some calendar integrations.

**Comment by emrysal** [comment]
Need to get to the bottom of this; may have something to do with the issues we've been experiencing @milospuac

**Comment by CarinaWolli** [comment]
Do we have an idea what the issue is here? I am not able to reproduce it. 

I see @alannnc has a draft PR open for it, would this solve it or is this already outdated?
