### ISSUE TITLE
[CAL-439] Hash My Url tests are flaky

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5658]
It seems like sometimes the hashed URL returns 404 on tests:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ee54b1d8-b576-4a35-9a4e-dbd3208d1815/c1d8a07a-f827-4306-9ee3-e0b14eebf66c)

> From [SyncLinear.com](https://synclinear.com) | [CAL-439](https://linear.app/calcom/issue/CAL-439/hash-my-url-tests-are-flaky)

**Comment by emrysal** [comment]
No longer flaky
