### ISSUE TITLE
Incorrect link on "claim username" footer of blog

### ISSUE THREAD

**Issue by hrtzg** [calcom/cal.com#5661]
### Issue Summary

The claim username button in the footer of blog posts redirects to an incorrect link. Takes you to `https://cal.com/blog/signup?username=` over `https://cal.com/signup?username=`.

### Steps to Reproduce

1. Visited blog post such as https://cal.com/blog/solving-the-mixed-availability-problem-for-good
2. Clicked on claim username button in footer of page

Being caused by /blog/ being included in the link. Should be a minor fix.

**Comment by PeerRich** [comment]
thank you!

**Comment by PeerRich** [comment]
fixed
