### ISSUE TITLE
[CAL-440] Font size of text area gets larger on mobile

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5663]
### Issue Summary

The font size of text area gets larger with a smaller screen.

**Normal screen:**

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/23daae55-ceb6-4a1d-b9fa-5962489d63d6/f91fc0ec-c31a-49de-ae2f-d7fd43e7453d)

**Mobile:**

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/75591bf2-8cc2-4c0e-b681-0a2598a642d4/6b85ee65-d04d-4bfc-bb4b-768bf2fed4f4)

> From [SyncLinear.com](https://synclinear.com)

**Comment by Toledodev** [comment]
Hey @CarinaWolli , I'm pretty sure I already fixed the problem, could you show me how I get to that TextArea in the screenshot?

**Comment by CarinaWolli** [comment]
Hey @Toledodev, the screenshot is from https://app.cal.com/settings/developer/webhooks/new when adding a custom payload template

**Comment by Toledodev** [comment]
Ok, I checked now and I fixed the problem. I will open a PR, thanks 😄
