### ISSUE TITLE
[CAL-443] Broken page for events that do not exist

### ISSUE THREAD

**Issue by mishushakov** [calcom/cal.com#5665]
### Issue Summary

When you visit an event which does not exist, the title of the page turns `undefined` and no slots are available
No 404 Page is displayed

### Steps to Reproduce

Go to a event that does not exist
example: [https://cal.com/user/30m](https://cal.com/user/30m)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Any Browser
* Using hosted version ([cal.com](http://cal.com))

> From [SyncLinear.com](https://synclinear.com)

**Comment by milospuac** [comment]
@emrysal if you type in a wrong URL for the event type it should return 404, right?

**Comment by leog** [comment]
Fixed by #5700.
