### ISSUE TITLE
[CAL-442] Groups within teams

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5667]
We will need some way to be able to organise departments within teams.

[Cal.com](http://cal.com/)﻿

* Sales at Cal
* Engineering at Cal
* Marketing at Cal

> From [SyncLinear.com](https://synclinear.com) | [CAL-442](https://linear.app/calcom/issue/CAL-442/groups-within-teams)

**Comment by shirazdole** [comment]
Certain team members should only have access to certain teams? 

This feels kinda relevant here as well: [https://linear.app/calcom/issue/CAL-385/ability-to-make-a-user-an-owner-of-a-single-team-event-rather-than-the](https://linear.app/calcom/issue/CAL-385/ability-to-make-a-user-an-owner-of-a-single-team-event-rather-than-the)

**Comment by PeerRich** [comment]
i think alternatively we introduce "Organisations" one layer above teams. so you are part of an Org and then the team is just "Sales"

**Comment by rene-mueller** [comment]
> i think alternatively we introduce "Organisations" one layer above teams. so you are part of an Org and then the team is just "Sales"

That sounds great :)

**Comment by Jaibles** [comment]
I agree with this.

**Comment by PeerRich** [comment]
for now, the cal.com/ultimate plan fixes this. will reopen if we need it on cal.com free and team plans, too

**Comment by shirazdole** [comment]
@PeerRich — I realize you've explained this multiple times for me, but could you explain again why Ultimate fixes this?

**Comment by PeerRich** [comment]
@shirazdole 

ultimate customers OWN the entire database which means they can open a team "marketing" that wont have a name-conflict with others

essentially:

acme.cal.com/team/marketing

would work for acme

whereas on a TEAM plan it would need to be

cal.com/team/acme-marketing

the subdomain is the organisation

**Comment by shirazdole** [comment]
I don’t believe we are talking about the same thing here then 🙏🏽

What Ciarán and I are discussing is a department sitting within a company or organization 

So everyone belongs to the organization, but not everyone belongs to say Marketing or Sales 

Within the “‘Marketing Team” there will be team events that belong just to that team

**Comment by PeerRich** [comment]
that is exactly what i am explaining

everyone belongs to 

acme.cal.com

but only marketing belongs wto acme.cal.com/team/marketing

**Comment by Jaibles** [comment]
not currently planned
