### ISSUE TITLE
[CAL-447] rethink google meet

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5672]
* dont make it installed by default
* ability to use google meet without google calendar

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-447](https://linear.app/calcom/issue/CAL-447/rethink-google-meet)</sub>

**Comment by PeerRich** [comment]
@joeauyeung I think you were working on some of those right?

**Comment by joeauyeung** [comment]
So I've already separated Google Meet into it's own app so it is no longer installed by default.

Currently there is no API for Google Meet so we still need to use Google Calendar. I linked to a comment below.
https://github.com/calcom/cal.com/issues/6180#issuecomment-1404319854
