### ISSUE TITLE
Event Requiring confirmation gets automatically removed from /Bookings/Unconfirmed upon rescheduling

### ISSUE THREAD

**Issue by gGh00sTt** [calcom/cal.com#5678]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If the user books an event that requires confirmation and reschedules it, the event gets automatically removed from /Bookings/Unconfirmed without the confirmation by event creator. Also, no rescheduling mail gets sent to the event creator or one who booked after rescheduling. However, the events didn't appear on the calendar so the events may still be unconfirmed. 

### Steps to Reproduce

1. Create an event that requires confirmation
2. Book a meeting for the event. The event will appear as unconfirmed
3. Now, reschedule the meeting for the event. The event will get removed from the unconfirmed.

**Comment by PeerRich** [comment]
@Udit-takkar can you investigate this?

**Comment by gGh00sTt** [comment]
Hello @PeerRich, I was trying to see if I can fix this issue. But I figured out that this really isn't a bug. It happens only when we are testing on a local machine using the same browser where the event owner is logged in to make the booking and reschedule the booking. The user's session id was compared with the current user id  to determine if the user is the event owner. If the event owner tries to reschedule the PENDING event status is automatically changed to ACCEPTED upon rescheduling but this doesn't happen if the event owner is different from the one rescheduling the event. So, if I use a different browser (with my account not logged in)  to reschedule the event requiring confirmation, the event still remained unconfirmed on rescheduling.

**Comment by PeerRich** [comment]
ohhh that makes sense

**Comment by Udit-takkar** [comment]
@gGh00sTt  ok thanks so should i close this ticket now.
