### ISSUE TITLE
[CAL-449] Usage of old select component

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5681]
### Issue Summary

The old select component is used everywhere. 

No rounded corners: 
![Screenshot 2022-11-25 at 13 12 01](https://user-images.githubusercontent.com/30310907/203983831-94ab98de-54da-41f7-99d9-d4b58f471302.png)

<sub>[CAL-449](https://linear.app/calcom/issue/CAL-449/usage-of-old-select-component)</sub>

**Comment by CarinaWolli** [comment]
@JeroenReumkens I think it's coming from this PR: #5561

**Comment by Toledodev** [comment]
Hey @CarinaWolli, are you sure this pr will solve this issue? I took a look at it and I didn't find something to replace the select

**Comment by CarinaWolli** [comment]
@Toledodev I was thinking that the changes from this PR may have caused this issue

**Comment by Toledodev** [comment]
Ok, I will fix this 😁

**Comment by JeroenReumkens** [comment]
Hey @Toledodev  Were you already able to take a look at this? The fix for this is pretty minor, so if you didn't have the time yet I'd love to take this over from you so we can have to fix live asap. Thanks 😁
