### ISSUE TITLE
Public booking page does not work at all in Firefox

### ISSUE THREAD

**Issue by kolaente** [calcom/cal.com#5685]
### Issue Summary

The booking page does not work in Firefox. I only see a blank page:

![image](https://user-images.githubusercontent.com/13721712/204003325-4451745a-54b3-477b-90d9-c2e1cd262964.png)

The same page works fine in Chrome.

I discovered this on my self-hosted instance but it does not seem to work on the SaaS at cal.com either.

### Steps to Reproduce

1. Open any public booking page in Firefox, for example https://cal.com/kolaente/test
2. See white page

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/): Firefox 107.0 on NixOS
- Node.js version: I don't know, whatever is running on cal.com (also probably not relevant).

There are a few errors logged into console:

![image](https://user-images.githubusercontent.com/13721712/204002951-b226debe-b379-4146-bc48-10856dfd421c.png)

**Comment by CarinaWolli** [comment]
It is working for me: 
<img width="929" alt="Screenshot 2022-11-25 at 18 43 15" src="https://user-images.githubusercontent.com/30310907/204034950-d243367e-e0cd-42b8-8152-b42af717a8df.png">

**Comment by kolaente** [comment]
I've tried this on a Windows and Ubuntu system as well and it seems to work fine there. Looks like this only does not work on _my_ firefox.

**Comment by kolaente** [comment]
Does not seem to be a problem of any of my addons. (restarted in safe mode, does not work either)

Is there a way I can debug this properly? Maybe with some kind of debug build?

**Comment by kolaente** [comment]
Looks like this is fixed in 2.3.4.

**Comment by dit7ya** [comment]
Broken for me as well.

**Comment by dit7ya** [comment]
@kolaente launching firefox with a clean profile and the `firefox-bin` package on NixOS fixes the issue for me. So I am thinking it has something to do with my heavily customized firefox configuration. 

Digging at the console, it seems like it has something to do with the `dayJs` library. 

```
Uncaught RangeError: invalid date
    toISOString utc.js:1
    K AvailabilityPage.tsx:69
    G AvailabilityPage.tsx:151
```

The relevant line - https://github.com/calcom/cal.com/blob/55035398563097a5abe4b7d7d1b9f9d5675afa02/apps/web/components/booking/pages/AvailabilityPage.tsx#LL69

Maybe this is also relevant - https://stackoverflow.com/questions/70989043/invalid-date-returned-by-day-js-in-firefox

**Comment by kolaente** [comment]
@dit7ya I got the same error with a clean profile or in safe mode. Looks like it's not the customizations in my case.

**Comment by kolaente** [comment]
Okay but it looks like this is different between the `firefox` and `firefox-bin` packages. I was able to use my profile from the `firefox` package with the `firefox-bin` package and cal.com worked without issues.

So I guess it's a NixOS issue after all? Really wired.
