### ISSUE TITLE
[CAL-907] Allow for users to use individual Zoom Accounts

### ISSUE THREAD

**Issue by PiotrKrzyzek** [calcom/cal.com#5693]
### Is your proposal related to a problem?

We are able to create one Zoom integration with one account and set the secret and private Zoom developer keys in the environment file, and that all works well. Though that integration works and is set for only one Zoom user.

This creates limitations as users then cannot add their own zoom accounts for scheduling private meetings. Nor are users able to use that joint account in anything other than Team meetings. This also has the limitation of not allowing a system admin to add the Zoom meeting integration to a team event from another zoom where that other user is the one with the Zoom App integration currently set in the environment file.

### Describe the solution you'd like

It would be wonderful to 
- create individual Zoom integrations 
- Admin can add existing Zoom integration to Team event where Zoom was integrated through another user

<sub>[CAL-907](https://linear.app/calcom/issue/CAL-907/allow-for-users-to-use-individual-zoom-accounts)</sub>

**Comment by MacBadger** [comment]
Yes! I came here for this (and multiple location one). I would also suggest the docs make this limitation absolutely clear too.
I tried musing another physical location ("zoom") as a workaround. But only one location allowed!
