### ISSUE TITLE
[CAL-454] Our new top banner component doesnt reflect dialog blur

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#5695]
![CleanShot 2022-11-25 at 22.11.27@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6123d206-1b25-4380-93fd-dc324b47da4d/7f0a9c1d-4d61-4667-a92b-52799cf29a16)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-454](https://linear.app/calcom/issue/CAL-454/our-new-top-banner-component-doesnt-reflect-dialog-blur)</sub>

**Comment by Udit-takkar** [comment]
yeah i have raised this issue here https://github.com/calcom/cal.com/issues/5578#issuecomment-1322259511
