### ISSUE TITLE
Add: pre-push instead of pre-commit 

### ISSUE THREAD

**Issue by harshsinghatz** [calcom/cal.com#5701]
### Is your proposal related to a problem?

- Currently we are using husky pre-commit hook which works fine but it leads to a bad DX as it provides resistance for the developer to make smaller and frequent commits
- I like to make small commits but waiting for the pre-commit to run every time makes me not want to do it

### Describe the solution you'd like
- Add pre-push hook rather than pre-commit

**Comment by PeerRich** [comment]
@zomars i am open to do pre-push instead

**Comment by zomars** [comment]
We're only doing lint/formatting in pre-commit. We're not running any tests. Commits should not take that long to run. I would agree if we were doing more heavy intensive work but it's not the case.

Also you can always add the `-n` to skip it locally but we need the code formatted and listed in CI anyways so the failure will be translated to the cloud instead.

**Comment by harshsinghatz** [comment]
@zomars I think we're also running build and add scripts for app-store, but yeah they don't take much time. Also would there be any other problem related to pre-push because i think we still would be able to do lint/formatting in pre-push?
