### ISSUE TITLE
Default Availability is what is used for ALL events

### ISSUE THREAD

**Issue by Zo-Bro-23** [calcom/cal.com#5706]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have two availabilities: Working Hours and Flexible. Flexible is what I use for my hobbies, and it consists only of afternoon hours while Working Hours consists of most of the day. I have two events: Quick Chat (Working Hours) and Flexible (Flexible). Both the events, however, show the same availability, and this is whatever the default availability is. If the default availability is set as Working Hours, both show Working Hours, and if the default availability is set as Flexible, both show Flexible.

![image](https://user-images.githubusercontent.com/62234360/204117788-fe870516-2cad-4433-b778-888a605c1a31.png)
![image](https://user-images.githubusercontent.com/62234360/204117790-4c70490c-cf21-477c-8e67-b5c821af4975.png)

### Steps to Reproduce

1. Have two different availabilities
2. Create two events with those two availabilities
3. Go to preview page - Both have the same availabilities

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
- Events are both hosted at https://cal.com/zobro23

### Technical details

- Firefox, but issue persisted with Android Chrome too - Likely an issue with the backend server, not the browser

**Comment by PeerRich** [comment]
@emrysal

**Comment by Zo-Bro-23** [comment]
This seems like a pretty bad issue, if I'm not wrong, so do you mind adding the high priority label? Thanks!

**Comment by emrysal** [comment]
Confirmed this is happening, pretty bad regression. Thanks for your report @Zo-Bro-23 - working on a fix with top priority.

**Comment by emrysal** [comment]
I've already cherry-picked this to production.

@Zo-Bro-23 Thank you for the quick spot; existing availability wasn't broken but on save of an event type the availability would be overriden by the default. A fix is already cherry-picked to production and a backport is in PR @ https://github.com/calcom/cal.com/pull/5710.

It also contains an backward compatibility fix so it will rectify itself on next save for users that are affected.

**Comment by Zo-Bro-23** [comment]
OMG, thanks so much! This is a really quick fix!
