### ISSUE TITLE
[CAL-459] disable save button when nothing has changed in /event-types/[type]

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#5709]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/571e3c13-0802-4e53-8a92-492e28ac47e5/d5b3b01c-6cbe-44ef-b1ff-8ea8d4372b10)

The save button on top right should be active only when something has changed.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-459](https://linear.app/calcom/issue/CAL-459/disable-save-button-when-nothing-has-changed-in-event-types[type])</sub>

**Comment by AFZL210** [comment]
@Udit-takkar can I work on this?

**Comment by Udit-takkar** [comment]
@AFZL210 i think this would be very tricky to detect if something has changed or not on all the tabs. you can take up any other simpler issue for now

**Comment by Ahsankhalid618** [comment]
@Udit-takkar Can i try this one if you are not working on it already?
