### ISSUE TITLE
Full HTML formating for emails

### ISSUE THREAD

**Issue by welovewebeu** [calcom/cal.com#5723]
We would like to request an improvement to the autoresponder email editor. 
Now the possibility of formatting the email that arrives after booking a date is very limited.

It would be great if it would be **possible to use all standard html tags** to format the email message.

That way we could insert images, format text, add a signature, etc.

**Comment by PeerRich** [comment]
where exactly? In workflows or where?

**Comment by PeerRich** [comment]
i dont think this is a good idea, can lead to many issues down the road with people using/abusing HTML mails
