### ISSUE TITLE
"Confirmed: 30 minute meeting with null"

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#573]
### Issue Summary

The invitee address received an email referring to a meeting with "null".  The email subject was:

> Confirmed: 30 minute meeting with null on 10:30 AM Wednesday, September 8, 2021

and the body looks like this:

![image](https://user-images.githubusercontent.com/100738/132097310-0baa73a3-a4fe-4546-8e24-0b15eb390f18.png)

I'm 95% sure that when pretending to be the invitee and submitting the event, I did provide a name.  But even if I didn't, this should never happen.
 
### Steps to Reproduce
1. Sent an invite to myself using a separate test address
2. Read the resulting email.

**Comment by emrysal** [comment]
The who of the invitee email is due to the organizer display name not being set - (See profile) - but I agree this should be handled more gracefully (Not sure what to default to, though).

**Comment by aspiers** [comment]
Ah OK, I did wonder if that was related.  I think you could just default to the username instead, since that will always exist.

**Comment by emrysal** [comment]
Did think about that, that isn't the case yet is because it doesn't look particulary good either; "Booked with aspiers" - but the alternative is null so concludingly - everything is better than null.

**Comment by aspiers** [comment]
Yes exactly.  I think "Booked with aspiers" looks fine.  Some people will prefer to choose a relatively anonymous nickname and not specify their actual name, in which case using the nick makes perfect sense.

**Comment by noobyogi0010** [comment]
@emrysal @aspiers I would like to work on this, if possible.
