### ISSUE TITLE
[CAL-572] Webhooks: not triggering

### ISSUE THREAD

**Issue by gzim-joinfella** [calcom/cal.com#5735]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Hey cal.com team,

We at Fella health have been using cal.com for a while now. 
Recently, we had the need to add a new coach to our team, and we added two new event types. We quickly noticed that we are no longer receiving webhook events for these new event types. 

Basically, it works fine for our existing team members/event-types, but not for the recently added ones. 

Trying to solve this issue, I discovered that there is now a different screen to manage webhooks. If I remember correctly (please let me know if this is not the case), webhooks were previously managed at the edit screen of a specific event type. Now, there is no such option and we have to use the module under /settings. 

I added our webhook listener url to the new webhooks module and the 'Test' button correctly replies with our response. However, for actual bookings, we are not receiving any webhooks for neither old event types or the new event types. 

Our onboarding journey is heavily affected by this because our customers can't move to next onboarding steps without booking an appointment, which, they are doing, but we have no way of knowing that so they are stuck. 

Very much would appreciate your support here, thanks! 

<sub>[CAL-572](https://linear.app/calcom/issue/CAL-572/webhooks-not-triggering)</sub>

**Comment by PeerRich** [comment]
alternatively, @CarinaWolli can take a look too

**Comment by CarinaWolli** [comment]
@gzim-joinfella Could you try to add the same webhook to the accounts of all team members with the role admin or owner? I think this might be the issue here. As far as I know, webhooks are only triggering for the event types that the user has created themselves.

**Comment by gzim-joinfella** [comment]
@CarinaWolli I created the mentioned event types with the same account that I've used to set up the 'centralized' webhook.

**Comment by CarinaWolli** [comment]
@gzim-joinfella  I don't think we have something like 'centralized' webhooks. Looking into our data, it looks like you don't have any webhooks defined in your account and only your team owner has them defined. This means that for the two event types that you have created no webhooks will trigger. So as a first simple solution, please try to create a webhook in your own account and test if it is working for the team event types that you have created

**Comment by shirazdole** [comment]
@gzim-joinfella thank you for the feedback you shared with us. Please see @Jaibles ticket above. We will incorporate webhooks at the event type level and then eventually at the organization level. Cheers!

**Comment by gzim-joinfella** [comment]
@shirazdole thank you!! we are still very much needing this features since we can't receive any webhook events for the two new added coaches on our team. We are seriously considering going away from cal.com because webhooks are essential to our system. 

Hopefully this fix will be available soon! thanks again.

**Comment by gzim-joinfella** [comment]
@shirazdole any updates on this, this issue is really affecting our day to day operations and the only workaround we have right now is to allow our users press a button 'I confirm I scheduled this meeting'. 

thanks!

**Comment by PeerRich** [comment]
we'll re-investigate!

**Comment by alishaz-polymath** [comment]
I just tested and can confirm that webhooks aren't triggering for me. These aren't team-event type webhooks but general webhooks. I'll investigate further and keep it updated here.

**Comment by alishaz-polymath** [comment]
Fix was merged #6120
