### ISSUE TITLE
[CAL-473] RFC: paid addons in app store

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5737]
Problem:

- we need a way to charge for features (SMS reminders, cal video recordings, disable branding) 
- but we don't have a PRO plan anymore, only TEAMS
- for solo people, it doesn't make sense to upgrade to TEAM (and its confusing, why would I need to create a team to disable branding)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-473](https://linear.app/calcom/issue/CAL-473/come-up-with-an-[upgrade]-badge-for-team-features)</sub>

**Comment by PeerRich** [comment]
Question. We plan to have “TEAM” features outside of teams, such as SMS reminders and Cal Video Recording… now thats gonna be tricky, how do we communicate this to the user?

previously we had a (PRO) badge next to it, but PRO is gone

A (TEAM) badge next to something is rather confusing

**Comment by PeerRich** [comment]
Also, will it force you to create a team (remember, team checkout comes after creating a team).

Imagine a user: “single individual, no team members, wants to use SMS reminders.”

sees (TEAM), clicks (TEAM) and now has to create a team?! Very confusing

**Comment by PeerRich** [comment]
Option A: We keep (PRO) badges, even tho we dont have a pro plan on the pricing page

Option B: ..?

**Comment by PeerRich** [comment]
Option B: We make "micropayments" for each feature. instead of upgrading to a teams plan, you are on a FREE plan + addons.

different features can be different addon subscription per month.

all addons could live in the app store as paid apps

"SMS Reminders" could be an app in the app store that adds ~$5/month to your monthly bill

**Comment by PeerRich** [comment]
like this: 
![CleanShot 2022-12-08 at 22 20 04](https://user-images.githubusercontent.com/8019099/206569777-1c2f570d-e9b7-429e-84e0-a3a5ec87a606.jpg)

**Comment by baileypumfleet** [comment]
I don’t like Option B, but I have discussed with Ciarán before that it should be communicated that it’s okay to be a one person team. For instance, you might use a personal scheduling link for social events, but also have a one man yoga studio which is a single person team, so therefore we just need to change or claify that it’s totally fine to have a team for one person to unlock professional/business oriented features

**Comment by PeerRich** [comment]
if not Option B: we need to figure out the best way to explain upgrading from FREE to TEAMS and how to label paid features
