### ISSUE TITLE
[CAL-474] /event types - Teams promo banner on empty state page

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5738]
Adds a promo banner to the event types page for people who don't have teams.

[   ↳ Teams promo banner in event types - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=923%3A95999&t=qFRVBQa7sYYtMQ5r-1)

* we already have a cookie for hiding sidebar tips which can be reused: only show if notInTeam

![CleanShot 2022-11-28 at 16.59.50@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7cfd67e3-2d1e-4218-b1e7-6a7ab060abe1/9f43e3eb-fbfb-4346-a693-e8cda6ab0a73)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-474](https://linear.app/calcom/issue/CAL-474/teams-promo-banner-on-empty-state-page)</sub>

**Comment by PeerRich** [comment]
I'll work on this instead cc @Udit-takkar
