### ISSUE TITLE
[CAL-475] Additional notes added on booking have a formatting issue in the confirmation email

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5739]
Additional notes added on booking have a formatting issue in the confirmation email

Created via Threads. See full discussion: [https://threads.com/34435710075](https://threads.com/34435710075)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-475](https://linear.app/calcom/issue/CAL-475/additional-notes-added-on-booking-have-a-formatting-issue-in-the)</sub>

**Comment by zomars** [comment]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/551326f0-b658-4f73-ac76-d6ef78b7a1c7/8780aa28-d01d-40e8-8fab-23f2c82c7b21)

**Comment by leog** [comment]
Issue seems to be coming up again, opening to investigate Gmail specifically.

**Comment by PeerRich** [comment]
@leog go for it

**Comment by keithwillcode** [comment]
Can't repro this. Closing.
