### ISSUE TITLE
[CAL-483] add new "Calendar View" in new <Scheduler/> as a Prop and new Booker App

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5747]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-483](https://linear.app/calcom/issue/CAL-483/add-new-calendar-view-in-new-scheduler-as-a-prop-and-new-booker-app)</sub>

**Comment by sean-brydon** [comment]
See more here too: [CAL-398](https://linear.app/calcom/issue/CAL-398/new-booking-layout-weekly-view)
