### ISSUE TITLE
ability to block book time so calendar slots will not be available

### ISSUE THREAD

**Issue by rice-b** [calcom/cal.com#5748]
I got booked when I was unavailable because my cal.com allowed the user to book my diary when I had something else on.
I'd like for it to not allow for bookings if my linked calendar already has a calendar event scheduled.

Could I add a recurring all day booking or long term calendar invite to stop bookings - i.e. over Christmas / holidays. But I also think there is a conflict feature it just doesn't do this.

**Comment by rice-b** [comment]
it might be something in "Limit future bookings" to allow for a section to add in dates that are not bookable.

**Comment by PeerRich** [comment]
we do that already. can you try the latest version? maybe something is wrong with your calendar. Can you try a different calendar such as Google Calendar or MS Office?
