### ISSUE TITLE
Recurring Event Booking does not block off earlier dates that overlap with the booking

### ISSUE THREAD

**Issue by frill-overwrite** [calcom/cal.com#5754]
### Issue Summary

Given you have a recurring event that runs for *2 occurrences*,
if the event is booked on Friday 12/9 at 5pm (which then correctly creates a booking for both 12/9 & 12/16 both at 5pm as expected), it would also be expected that Friday 12/2 at 5pm would no longer be available due to a collision between the prior booking and the second occurrence of the attempted booking on 12/9 @5pm ET.

As expected, upon attempting to book 12/2 at 5pm, the booking fails: 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/94943824/204440985-4bc1abdb-8b49-483f-8a6b-c3e1fb003542.png">

Friday 12/2 at 5pm should not be displayed as available.

### Steps to Reproduce

1. Make an event with "recurring event" turned on to N occurrences  (N = 2 is sufficient)
2. Make a booking for next week 
3. Attempt to book the same day and time this week (which is listed as available)
4. Booking fails despite being listed as available

currrent outcome: same day and time this week is still available 
desired state: same day and time this week is not listed as available

**Comment by PeerRich** [comment]
hey @leog  can you investigate this?
