### ISSUE TITLE
Unable to register on cal.com - 500 Internal Server Error

### ISSUE THREAD

**Issue by janjaromirhorak** [calcom/cal.com#5757]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Not sure if it belongs here, since it is possibly only an issue with the official deployment on cal.com. But I was not able to find a support contact there, so I am trying my luck here.

I am not able to register to the app. After entering the preferred username, e-mail and password and clicking on "Sign up for free", a "Something went wrong!" toast shows up on the screen.

When investigating the issue, I have found that the call to `https://cal.com/api/signup` returns `500 Internal Server Error`. 

### Steps to Reproduce

1. Go to [cal.com/signup](https://cal.com/signup)
2. Enter username, e-mail, password so it is valid according to client-side validation.
3. Click "Sign up for free"
4. "Something went wrong!" message shows up.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- The official app deployment on cal.com
- Browser: Mozilla Firefox 107.0, but this is probably irrelevant since it seems to be a backend issue

**Comment by PeerRich** [comment]
this looks like a one-time hiccup. Can you try again?
