### ISSUE TITLE
[CAL-910] Pre-select country for phone number

### ISSUE THREAD

**Issue by vallbrd** [calcom/cal.com#5759]
Currently when a person has to enter his phone number, he has to select the country or enter the code after "+"

![image](https://user-images.githubusercontent.com/99829906/204486474-e03e66c9-3b94-4495-bcff-c18247b78978.png)

We should add the possibility to pre-select a country for a form

![image](https://user-images.githubusercontent.com/99829906/204486785-bd64fb17-86bb-4d7b-85c7-4cf241647f88.png)

<sub>[CAL-910](https://linear.app/calcom/issue/CAL-910/pre-select-country-for-phone-number)</sub>

**Comment by PeerRich** [comment]
great request. we could potentially use the nextjs middleware to get location @zomars
