### ISSUE TITLE
[CAL-488] Timezone selection has a weird double dropdown

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5762]
![CleanShot 2022-11-29 at 10.18.29@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/53cf3cc1-d43a-4296-87ca-b9ed9daff132/787ebce7-b166-4c75-8457-35239037aa38)

**Should be**

![CleanShot 2022-11-30 at 08.49.53@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2cc54e6a-88a0-417d-bdd5-3496ea0358f5/118de7da-5065-4062-83e9-70183d51be34)

[Public booking page / Date picker {Timezone dropdown:Open} - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=1%3A5765&t=RIi6FRJLVeaGGHaa-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-488](https://linear.app/calcom/issue/CAL-488/timezone-selection-has-a-weird-double-dropdown)</sub>

**Comment by PeerRich** [comment]
urgh

**Comment by PeerRich** [comment]
@gitstart-calcom let me know if you need more context.
