### ISSUE TITLE
[CAL-490] Allow hyperlinks in descriptions?

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5764]
![CleanShot 2022-11-29 at 11.43.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e0995e98-0d15-447e-8135-75a81915c34b/8461960d-e51e-4e16-9805-efbc53e3d58e)

[e32dffae-e3e7-4c7c-a3f3-0519882bfdcf](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2f621082-a5ac-42fa-bdb9-5d0daa276fec/e32dffae-e3e7-4c7c-a3f3-0519882bfdcf)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-490](https://linear.app/calcom/issue/CAL-490/allow-hyperlinks-in-descriptions)</sub>

**Comment by PeerRich** [comment]
i am not so sure. is it a good idea to link to external pages from here, losing the focus?

**Comment by Jaibles** [comment]
Whether it's a good idea or not, people will do it. This is our own team doing it sure. We might as well clean it up.

**Comment by PeerRich** [comment]
ok cool. lets auto turn urls into clickable links. I wonder if @CarinaWolli's new markdown description box helps with this

**Comment by PeerRich** [comment]
@CarinaWolli wanna work on this? texted you on threads about this

**Comment by CarinaWolli** [comment]
Will implement that with our `Editor` component
