### ISSUE TITLE
[CAL-491] Remove the back arrow

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5765]
![CleanShot 2022-11-29 at 11.43.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ec92046c-0db3-4d58-82c9-c8a5e61d5a30/089f2db5-e4ef-4d52-9c1e-3528f3ca36a1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-491](https://linear.app/calcom/issue/CAL-491/find-a-better-spot-for-the-back-arrow)</sub>

**Comment by PeerRich** [comment]
potentially remove it. its been quite flaky. if people complain we can re-add it

**Comment by PeerRich** [comment]
why reopen @Jaibles ?
