### ISSUE TITLE
[CAL-494] We need to communicate a load state between selecting a time and the next page

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5768]
When you pick a timeslot, there is nothing to suggest anything is happening while we wait on the next page to submit details to load and sometimes this is not a short time.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-494](https://linear.app/calcom/issue/CAL-494/we-need-to-communicate-state-between-selecting-a-time-and-the-next)</sub>

**Comment by PeerRich** [comment]
this will be fixed once the two routes have been merged and we got rid of /book

**Comment by JeroenReumkens** [comment]
Correct. I'll add this issue as a "fixes" issue to the booker PR.

**Comment by JeroenReumkens** [comment]
Yesterday we merged #6792 🔥 This contains a new layout where both the form and the datepicker are on the same state. That resolves this issue regarding loading states. The new view is still behind a feature toggle, but will be available soon.
