### ISSUE TITLE
[CAL-497] Top banner is behind command K menu

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5772]
\~Z-index issue:\~

The issue:

![CleanShot 2022-11-29 at 13.03.33@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1a766895-40b3-4f6d-b1fb-14f5e0265623/de3bf05a-6b78-4b4f-9ca9-c872be64eb18)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-497](https://linear.app/calcom/issue/CAL-497/top-banner-is-behind-command-k-menu)</sub>

**Comment by Udit-takkar** [comment]
command K menu uses portal and not z index

**Comment by Jaibles** [comment]
I'll stop trying to diagnose problems and just point them out 😂

**Comment by Udit-takkar** [comment]
what is the expected behaviour here ?

**Comment by Jaibles** [comment]
The order `if i was using z-index, hypothetically would be something like`
- command k  `50`
- overlay  `49`
- banner `10`

**Comment by PeerRich** [comment]
@Udit-takkar are you taking this? if not i can give this a look

**Comment by Udit-takkar** [comment]
@PeerRich  yeah you can take this up.

**Comment by PeerRich** [comment]
done
