### ISSUE TITLE
[CAL-499] Choosing the email you want to be displayed as the organizer

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#5774]
**Problem**

* I have a personal [cal.com](http://cal.com) account for (eg [myname@gmail.com](mailto:myname@gmail.com)).
* I also want to use [cal.com](http://cal.com) for my work purposes. To do that I attached my corporate Gmail calendar (eg [myname@mycompany.com](mailto:myname@mycompany.com)) to the existing personal [cal.com](http://cal.com) account. As a result now I get scheduled events in the right calendar ([myname@mycompany.com](mailto:myname@mycompany.com)) but as a participant I am displayed there with my personal email ([myname@gmail.com](mailto:myname@gmail.com))

**Desired outcome**

* Let the user choose on a per event basis which email address for them to appear as the organiser for.
* The list of choices should be pulled from their list of connected calendars.
* We would likely place this alongside the "Add to calendar" UI in the event type settings

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-499](https://linear.app/calcom/issue/CAL-499/choosing-the-email-you-want-to-be-displayed-as-the-organizer)</sub>

**Comment by Jaibles** [comment]
Designs here: https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1021%3A104990&t=aHu8nYgrxUial0XA-1

**Comment by gitstart-calcom** [comment]
Hi @Jaibles, do we have any update on this issue?

**Comment by PeerRich** [comment]
Update: Lets use the email of the selected calendar in the "advanced settings" of the event-type.

that way we dont need to add additional UI and its quite trivial:

![image](https://user-images.githubusercontent.com/8019099/231549459-06473d7b-f8b3-4a23-8a28-81c43a36624d.png)

vs

![image](https://user-images.githubusercontent.com/8019099/231549484-9083814f-bdb5-48e7-9856-8863087b988f.png)

**Comment by PeerRich** [comment]
it's almost always the user wants to send private events to private calendars and then have confirmations sent to the private email

i cannot think of a scenario where thats not the case.

**Comment by PeerRich** [comment]
only downside: are there calendars without email? or maybe weird privacy-first calendars that are like: proxy-email-123@proxycalendar.io or similar

**Comment by PeerRich** [comment]
for those cases we (1) tell users its not possible (2) later add an additional input field where you can potentially add an external email.

for now I think the new above solution does 90% of the use cases

**Comment by hariombalhara** [comment]
I think Zoho Calendar doesn't have an associated email. Was testing Zoho Calendar App(in Review) some time back and noticed then.

**Comment by moxplod** [comment]
I have a similar issue, not sure if its the exact same one. 
Personal and company email calendars connected. Primary is the personal one and defaults to this for all events. 

I created a company event which saves all new events to the company calendar perfectly. 

Problem - it adds my personal email as an organizer in the description of the calendar event that is sent to my work calendar.

Expected behavior: Personal email is not shown in the description of the event.

**Comment by ciaranha** [comment]
> I have a similar issue, not sure if its the exact same one. 
> 
> Personal and company email calendars connected. Primary is the personal one and defaults to this for all events. 
> 
> 
> 
> I created a company event which saves all new events to the company calendar perfectly. 
> 
> 
> 
> Problem - it adds my personal email as an organizer in the description of the calendar event that is sent to my work calendar.
> 
> 
> 
> Expected behavior: Personal email is not shown in the description of the event.

@Udit-takkar or @joeauyeung we are working on a fix for this issue right?

**Comment by Udit-takkar** [comment]
> @Udit-takkar or @joeauyeung we are working on a fix for this issue right?

yes
