### ISSUE TITLE
[CAL-455] Immediately Select Members after creating Team Event Type

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5776]
The current flow when creating a Round Robin is you navigate to the top right → click the team → then select the event type you want.

Once you complete creating the event-type you are presented with the settings of the event and then have to navigate to the Scheduling Type and then Add Attendees. The problem is that this is confusing and I believe the creator of the team event type would prefer to immediately add an attendee.

The Add Attendees portion should be part of the main create a collective/round robin event type flow as well.

![CleanShot 2022-11-26 at 12.42.26@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/245c813c-74f3-4db7-9076-a4d1bfac1c59/d40649f2-5827-4a7c-b226-70577461bbe5)

![CleanShot 2022-11-26 at 12.45.02@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cb0a3dfa-dbac-4b03-9d6c-123c6634a633/a061e5e5-6d04-42b5-91e0-ff442e24779b)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-455](https://linear.app/calcom/issue/CAL-455/immediately-select-members-after-creating-team-event-type)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-455](https://linear.app/calcom/issue/CAL-455/immediately-select-members-after-creating-team-event-type)</sub>

**Comment by shirazdole** [comment]
@Jaibles — I left this private for now as it's not urgent, but a nice improvement when made

**Comment by PeerRich** [comment]
agree, @Jaibles lets change this workflow. maybe even have members in the dialog as a second step
