### ISSUE TITLE
[CAL-718] Ability to collect First Name and Last Name inputs separately

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#5784]
We are facing an issue with **Name** input collecting both First and Last name in one field.

In our database, first and last name are stored as separate attributes and used actively in email/SMS communication. And there is no good way to automatically split the full name into first and last names. This is especially challenging in locations where second names are commonly used.

We would like to be able to collect First and Last names as separate inputs.
Ideally, we would like to be able to control all Inputs in a separate section of Event settings.

---

Tagging @alishaz-polymath since we discussed this on a call today :) I, unfortunately, can't add labels to the issue.

---

Sharing a few screenshots from the previous booking solution that we used: 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/33749906/204623440-dbdea85f-5fbf-446c-9070-81af9c869f8a.png">
<img width="695" alt="image" src="https://user-images.githubusercontent.com/33749906/204623538-e3983b1c-5a8f-4fad-ad4c-14c286fbc5fe.png">

<sub>[CAL-718](https://linear.app/calcom/issue/CAL-718/ability-to-collect-first-name-and-last-name-inputs-separately)</sub>

**Comment by automationsClub** [comment]
I second that - It's a really needed feature.
Moreover, It will be great to be able to edit all the input fields and also control their labels.
As my audience isn't speaking English, it's funny to have the name,email,notes questions in English and the custom questions in Hebrew...

**Comment by PeerRich** [comment]
we're rethinking the entire form builder right now and this could be a great option in the form builder. with a form builder you could make your own inputs and then just make an input for "First name" and "Last Name" separately 

cc @Jaibles

**Comment by automationsClub** [comment]
@PeerRich 
That's awesome! 
Any ETA on that?

**Comment by PeerRich** [comment]
not yet

**Comment by aasargsian** [comment]
@PeerRich are there any designs on the form builder or an open issue? I would love to review / comment. This sounds very promising :)

**Comment by Jaibles** [comment]
@aasargsian I need to do the designs first. I'll attach here when I have them.

**Comment by aasargsian** [comment]
@Jaibles sounds great, lookimg forward to it!

**Comment by Jaibles** [comment]
Designs for this are here

[Additional inputs - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1807%3A120640&t=Aiw1Icg3cGdHMn8X-1)

**Comment by automationsClub** [comment]
> Designs for this are here
> 
> [Additional inputs - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1807%3A120640&t=Aiw1Icg3cGdHMn8X-1)

@Jaibles 
It looks great, but I'm not clear on the last page - is it in the flow?
![2023-01-14_18-22](https://user-images.githubusercontent.com/89608662/212486615-1da86fd8-dadc-43f6-8e57-ce5a7e1e21de.png)

**Comment by Jaibles** [comment]
@automationsClub i think we have another engineer @hariombalhara picking this up next week.

**Comment by hariombalhara** [comment]
PR is still in review on low priority. So, moving it to next milestone.

**Comment by hariombalhara** [comment]
@keithwillcode @Jaibles What's the priority here? PR is set to low priority but the ticket is medium 
https://github.com/calcom/cal.com/pull/8671

**Comment by Jaibles** [comment]
@hariombalhara I'd put it at medium.
