### ISSUE TITLE
[CAL-529] Hide event type details in embed

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#5792]
Hi! We are looking for a way to embed the Cal.Com's calendar to our website without event type details.

Expected behaviour would be embedding the calendar widget only, without event name, host's name, location or duration.

This is important for us for a smoother experience on mobile - 95% of our traffic is mobile :)

We used to use the Hide event details option in Calendly - I'll attach a screenshot, might be useful 
<img width="488" alt="image" src="https://user-images.githubusercontent.com/33749906/204632851-e7a5f30f-59cb-4108-8bb7-b6e66eec4482.png">
m

---

Tagging @alishaz-polymath and @hariombalhara as we discussed this on a call today :)

<sub>[CAL-529](https://linear.app/calcom/issue/CAL-529/hide-event-type-details-in-embed)</sub>

**Comment by alishaz-polymath** [comment]
cc: 
@Jaibles for design
@hariombalhara for dev

**Comment by aasargsian** [comment]
@hariombalhara @alishaz-polymath could you pls help me use this new toggle? This doesn't seem tobe available to be in inline embed
