### ISSUE TITLE
Tracking cancelledBy attribute

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#5793]
Seems like there is no way to track who cancelled the event - host or attendee.

We typically use the cancelledBy attribute to better define the next action. For example, If the teleconsultation is canceled by the host - we call back the attendee to rescheduled. If the teleconsultation is cancelled by attendee - there is usually no action required.

**Comment by zomars** [comment]
Feel free to join the discussion in #2477

**Comment by PeerRich** [comment]
continuing in https://github.com/calcom/cal.com/issues/2477
