### ISSUE TITLE
[CAL-515] MS Teams Install Blank Popup

### ISSUE THREAD

**Issue by Epod** [calcom/cal.com#5797]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On a fresh self hosted install of Cal.com, MS Teams will show a white popup when attempting to install. You can not progress further. 

Linking Office 365 Calendars works fine, and the Graph API appears to work as intended on that front. 

![Screen Shot 2022-11-29 at 9 03 06 PM](https://user-images.githubusercontent.com/49006/204689545-c8d82823-4e46-408a-a8fd-983fa47bbf33.png)

### Steps to Reproduce

1. Clean Cal.com Install
2. Access domain.com/apps/msteams
3. Click "Install App"

<sub>[CAL-515](https://linear.app/calcom/issue/CAL-515/ms-teams-install-blank-popup)</sub>

**Comment by zebinho20-belenus** [comment]
same here....

**Comment by PeerRich** [comment]
investigating! we recently made a tiny update to dialogs and it seems like they crashed some

**Comment by PeerRich** [comment]
will go live in the next minor release @epod
