### ISSUE TITLE
[CAL-508] /public booking - Show "No times in month" notice

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5799]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f8e20b06-5ea6-4777-889d-5eb8aa56a812/7e347c3c-00ea-4232-9617-5bba51474f1b)

[Designs in Figma](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1022%3A105723&t=mjPOx0fUV9UtclBM-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-508](https://linear.app/calcom/issue/CAL-508/public-booking-show-no-times-in-month-notice)</sub>

**Comment by akshayraichur** [comment]
Hey @Jaibles 
I am interested in working on this issue. 
Could you let me know which components will be affected by this change. 
And, in order to create a design mock up for this issue, where I can get design resources specific to cal.com 

Thanks!

**Comment by PeerRich** [comment]
@akshayraichur still waiting for designs but should be done by @Jaibles very soon

**Comment by Jaibles** [comment]
Designs attached https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1022%3A105723&t=mjPOx0fUV9UtclBM-1

**Comment by akshayraichur** [comment]
@PeerRich @Jaibles thank you! 

I will take a look at the designs and get started. 

Also wanted to know if there is discussion forum(apart from GitHub issues) where I can join, it will be very convenient to discuss about the issue and to ask any doubts if I have.

**Comment by PeerRich** [comment]
we have a slack: https://cal.com/slack

**Comment by PeerRich** [comment]
will work on this too, @akshayraichur havent heard from you yet
