### ISSUE TITLE
[CAL-509] UI issue: No border radius on button group hover state right side

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5800]
[16c74fca-5ab1-4425-9c88-25cd7e4fb58f](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/630a3067-0828-4ca1-a580-87b00f472c8e/16c74fca-5ab1-4425-9c88-25cd7e4fb58f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-509](https://linear.app/calcom/issue/CAL-509/ui-issue-no-border-radius-on-button-group-hover-state-right-side)</sub>

**Comment by Jaibles** [comment]
@Udit-takkar I'd be curious if this is something on a component level that appears everywhere or just here.

**Comment by sumedh1996** [comment]
@Jaibles Looked into this issue and this is just related to the specific component
