### ISSUE TITLE
[CAL-510] Make the location select dropdown much higher

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5801]
![CleanShot 2022-11-30 at 08.54.32@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d8fdec7f-2b70-4212-a2c9-dd10d037cccb/a43a62b2-0f3d-4343-9b64-26b85827c0d6)

Right now it looks like there are no more options

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-510](https://linear.app/calcom/issue/CAL-510/make-the-location-select-dropdown-much-higher)</sub>

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/205656962-b2eb5253-3533-4b5f-ba17-95141e9899d0.mov

It's working fine

**Comment by Jaibles** [comment]
It works, but can we make it higher by default @Udit-takkar? There's no reason why to start we should only be able to see the video options and have to scroll to see more.

**Comment by Udit-takkar** [comment]
okay will increase the height here
