### ISSUE TITLE
[CAL-511] Event type location: Zoom - Saying "Cal will provide a Zoom Video URL"

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5802]
![CleanShot 2022-11-30 at 09.09.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bbadbeff-1416-449b-a8c7-ab6b8d564320/64f9d42e-f526-4c51-a4de-9fb5b7e341db)

This text is confusing and making me think that it is not using my Zoom account. I assume it is, but the text is wrong as opposed to this is communicating something else as I have Zoom installed.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-511](https://linear.app/calcom/issue/CAL-511/zoom-location-saying-cal-will-provide-a-zoom-video-link)</sub>

**Comment by Udit-takkar** [comment]
@Jaibles is there any other text that we should display?
