### ISSUE TITLE
[CAL-513] /teams - Improve the empty state

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5806]
[Teams Empty State 5 - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1010%3A107690&t=TtPJpYisjxaiJsao-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-513](https://linear.app/calcom/issue/CAL-513/teams-improve-the-empty-state)</sub>

**Comment by PeerRich** [comment]
on it!
