### ISSUE TITLE
[CAL-514] Direct links to accept/reject booking

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#5807]
Right now, when getting a confirmation email for a booking, you need to click the button in the email, log in, 2FA, and click accept/reject again in upcoming bookings page.

Much like unsubscribe link in automated emails, we could include an Accept and Reject button, each with a unique direct link to directly perform the action without having to log in.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-514](https://linear.app/calcom/issue/CAL-514/direct-links-to-acceptreject-booking)</sub>

**Comment by PeerRich** [comment]
i like that

**Comment by PeerRich** [comment]
heard it a couple times but never executed so far

**Comment by leog** [comment]
@PeerRich @Jaibles Regarding question, when rejecting, there's the reason why a user rejects a booking. We could potentially do two things, not mutually exclusive of each other:
 - Include a form input in the email to let the user directly say why the rejection and clicking in a button will go to the page I'm working on, rejecting the booking with that reason and simply showing "Booking rejected" and the info of the booking. Including a simple "GET" form in an email is supported enough in different email clients.
 - Let the user specify a couple of reasons he want to be able to use to reject a booking directly from an email, those would be in the event type settings under Requires Confirmation, and the buttons in the email would say "Confirm", "Reject: reason1" and "Reject: reason2"
 - Include just a "Reject" button in the email and the reason can be added in a textarea in the page that shows up

**Comment by Jaibles** [comment]
The third option seems the easiest and a perfectly good option. It's nice and simple.

**Comment by PeerRich** [comment]
agree #3

**Comment by Jaibles** [comment]
In fact, could it be exactly like our cancel flow? The state of the booking would just be "tentative" rather than confirmed. 
<img width="1471" alt="CleanShot 2022-12-07 at 21 02 16@2x" src="https://user-images.githubusercontent.com/4536123/206295059-2aaaada6-fe9f-4254-adb2-8129ad287304.png">

And what the booker sees after the request
<img width="1475" alt="CleanShot 2022-12-07 at 21 03 26@2x" src="https://user-images.githubusercontent.com/4536123/206295220-06e5bfcc-9aa3-4073-bab0-4395056978a2.png">

**Comment by leog** [comment]
> @leog are we offering the option to reschedule also somewhere in that email?

As of now, just a link to the upcoming bookings page to choose what to do. I was thinking to also keep it simple and once the user sends the reason for rejection, show it was rejected and there's that.

**Comment by leog** [comment]
> In fact, could it be exactly like our cancel flow? The state of the booking would just be "tentative" rather than confirmed.

I was already using the same design 👍
 
> And what the booker sees after the request 

I would just show a confirmation that the booking was rejected and that's it. Remember this flow can be done without you having to log in, so having more stuff in it would make it difficult to implement.

**Comment by leog** [comment]
@Jaibles BTW, I don't think we have the screens you showed me anymore since we changed the booking page URL 🤔 I tried clicking in a booking from the upcoming or unconfirmed list and I see the booking page info as if I just booked it. Hopefully it's just me.
