### ISSUE TITLE
Limit register page to a specific domain

### ISSUE THREAD

**Issue by siddjellali** [calcom/cal.com#5817]
### Is your proposal related to a problem?
Anyone can access to registration page :( 

### Describe the solution you'd like

Enabble control on email domain registration page.

**Comment by PeerRich** [comment]
which register page are you referring to?

**Comment by siddjellali** [comment]
oh yeah sorry 
I’m referring to register page in onprem deployment (docker)

**Comment by PeerRich** [comment]
I am not quite sure what this ticket means. can you give more context?

**Comment by PeerRich** [comment]
do you want to disable signup on your self-hosted instance? you could touch the signup file and disable it

**Comment by gitwittidbit** [comment]
I believe the OP doesn't want random strangers to be able to register as users on his on-prem installation (as appears to be the case per default).

I, too, don't want that either on my on-prem installation and when looking for a solution I landed on this page.

The OP proposes to create a setting that would allow people to register on his on-prem installation only, if they have an email address from a specified domain (under his control). 

This is a relatively common setting for self hosted applications and I would like to add my +1 to his proposal.

Thanks!
