### ISSUE TITLE
[CAL-911] Reservation System: Multiple bookings on a single slot

### ISSUE THREAD

**Issue by lukaszervudakis** [calcom/cal.com#5820]
### Issue Summary
When customers book simultaneously, multiple bookings are registered on a single slot.

I'm hosting a rather popular event which is booked out very quickly. However, when customers book at the exact same time, a single slot configured for only one participant is getting overbooked with 2-3 confirmed appointments.

### Steps to Reproduce

1. Create event with one participant per slot
2. Book one slot with multiple devices at the same time
3. Slot is overbooked

### Technical details

- Using official  cal.com  v.2.3.3-h-PRO
- Happens with any device / browser

<sub>[CAL-911](https://linear.app/calcom/issue/CAL-911/multiple-bookings-on-a-single-slot)</sub>

**Comment by PeerRich** [comment]
we'll soon be working on a "reservation" system which means the first person to select a date will "reserve" it before confirming for ~5 minutes which will prevent this problem for high-volume customers

**Comment by PeerRich** [comment]
@alannnc is wroking on this

**Comment by alannnc** [comment]
Should be already done by @roae.
