### ISSUE TITLE
[CAL-518] Fix availability troubleshooter

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#5824]
It's has been outdated for a while and now has several bugs with timezones and day with multiple hour schedules.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-518](https://linear.app/calcom/issue/CAL-518/fix-availability-troubleshooter)</sub>

**Comment by PeerRich** [comment]
yea the troubleshooter causes more troubles

**Comment by PeerRich** [comment]
do many people use the troubleshooter I wonder

**Comment by zomars** [comment]
It should be first class citizen if you ask me. That's the main user facing debugging tool that we have.

**Comment by saschafoerster** [comment]
I would be actually happy if it would be working, especially for debugging CalDAV it is super helpful. Right now I can't use it for debugging, as it is buggy itself. 
<img width="333" alt="Bildschirm­foto 2023-02-25 um 20 50 10" src="https://user-images.githubusercontent.com/1153741/221376813-77bbbbaf-4f09-42f6-9cfc-12e867cd6646.png">

**Comment by aspiers** [comment]
And it needs to be easy to use too.  Again, it's worth learning from Calendly here, who have done a really good job with the UI:

![image](https://github.com/calcom/cal.com/assets/100738/7639bcbc-10e3-453d-9bdd-1899dc3ab484)

**Comment by aspiers** [comment]
Just noting for reference that https://cal.com/blog/v-3-5 announced:

> We have a really exciting feature right around the corner enabling you to troubleshoot your availability right from inside Cal.com with a highly visual calendar UI. With our troubleshooter, you will be able to see any time you’re not available and see exactly why you’re not available at that time. This will cover events coming from your calendar, your times from your availability schedule, and any date overrides you may have added. This feature will be released within the next week.

Can't wait to see this!
