### ISSUE TITLE
[CAL-520] Password at login is always displayed

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5826]
### Issue Summary

When you want to log in into [Cal](https://app.cal.com/auth/login) the password is always displayed. Independent of hide and show button (in the input).

### Technical details

Tested in following Browser:
- Firefox Developer Edition 108.0b9 (64-Bit)
- Firefox 107.0.1 (64-Bit)

Operating system is MacOS Monterey 12.5.1

<sub>[CAL-520](https://linear.app/calcom/issue/CAL-520/password-at-login-is-always-displayed)</sub>

**Comment by PeerRich** [comment]
agree 
![CleanShot 2022-12-02 at 11 03 57](https://user-images.githubusercontent.com/8019099/205267788-c040e045-87ac-4015-9cc6-73ed95b27968.jpg)

thats new. hmm @Udit-takkar
