### ISSUE TITLE
[CAL-521] move all whitelabeling settings into console.cal.com

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5830]
right now we have some whitelabel options in .env and it should better live in [console.cal.com](http://console.cal.com) and require and /ee/ license

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-521](https://linear.app/calcom/issue/CAL-521/move-all-whitelabeling-settings-into-consolecalcom)</sub>

**Comment by rene-mueller** [comment]
connected to that pr #5821
