### ISSUE TITLE
[CAL-522] Issues with Merge Fields

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5833]
A customer is having an issue with the following merge issues:

\- in the email subject of rescheduled meeting
\- in the email subject of created meeting
\- in a page on Teams but I don't have a screenshot, I will send it if I find it back

The language they are using is French if helpful

![Issue 1.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/89c3c430-79a4-4807-b3dd-5c128fb11ae9/0976d081-a998-45cf-adee-45af5919b8d7)

![Issue 2.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/be0dca6c-0025-4832-b089-854744454c1a/f273f02b-06dc-4156-ba4b-45a11d8781ba)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-522](https://linear.app/calcom/issue/CAL-522/issues-with-merge-fields)</sub>

**Comment by shirazdole** [comment]
cc @Jaibles

**Comment by CarinaWolli** [comment]
Fixed with #5843
