### ISSUE TITLE
Change Calendar "Location" Field To Meeting Link

### ISSUE THREAD

**Issue by Epod** [calcom/cal.com#5845]
Currently, when a invite goes out, the "Location" field in the invite (the actual calendar invite attachment) just says the name of the video service, such as "Google".

Instead of just saying "Google" it should just be the URL of the Meeting link instead. 

Strangely enough, not all video services do this. Jitsi for example has the location as the meeting URL, which is the desired result.

**Comment by PeerRich** [comment]
Can you try again? I believe this was a temporary issue.
