### ISSUE TITLE
[CAL-912] Phone Dial In Information In Invites

### ISSUE THREAD

**Issue by Epod** [calcom/cal.com#5846]
Some services will optionally include dial in information. 

When "normally" scheduling a invite that includes a Microsoft Teams link for example, that calendar invite body will include dial in information as well. 

When scheduling through cal.com however, only the meeting link is picked up and included in the invite email. 

If dial in information is present in a particular video service, it would be beneficial to also include it in the cal.com invites. 

Potentially some help with where that data is stored below (for the services I am familiar with): 

MS Teams: https://learn.microsoft.com/en-us/graph/choose-online-meeting-api
> Through the onlineMeeting property, access: conferenceId, quickDial, phones, tollFreeNumbers, tollNumber.

Google: https://developers.google.com/calendar/api/v3/reference/events#conferenceData.entryPoints

Zoom: https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/meetingCreate
> global_dial_in_numbers

<sub>[CAL-912](https://linear.app/calcom/issue/CAL-912/phone-dial-in-information-in-invites)</sub>

**Comment by shashivardhan-dev** [comment]
Hello @Epod , It would be great if you can share, steps to reproduce

**Comment by avanisingh0105** [comment]
@Epod Please share steps to reproduce. Not able to resolve it without reproducing @PeerRich

**Comment by Nayaker** [comment]
I would like to do this, what's the process?

**Comment by ologbonowiwi** [comment]
@Nayaker comment /attempt #issue-number and go for it!

Don't forget to /claim #issue-number on the PR body!

**Comment by Vishnupriya-github** [comment]
Could you please add some screenshots?
