### ISSUE TITLE
UX issues on the german booking-pages

### ISSUE THREAD

**Issue by saschafoerster** [calcom/cal.com#5855]
<img width="893" alt="Bildschirm­foto 2022-12-04 um 20 25 16" src="https://user-images.githubusercontent.com/1153741/205511826-034494d4-0f3e-448a-a131-28ce420681b4.png">

I found some small issues with the german UX and translations of the german booking page. 

- In Person (Organizer // Attendee Adress) should be made translatable. 
- Timezone: Would be great if I could choose "Europa/Berlin" instead of the englisch location of Amsterdam "Europe/Amsterdam". 
- The date in german would be written "Do., 8. Dezember" instead of "Do, Dezember 8"

**Comment by PeerRich** [comment]
I am pretty sure this has been resolved. Let me know if not

**Comment by saschafoerster** [comment]
@PeerRich One of three is solved. :) 

<img width="1041" alt="Bildschirm­foto 2023-01-25 um 17 27 55" src="https://user-images.githubusercontent.com/1153741/214619970-2d27338f-d1ab-4ce1-8b2b-9578f9c7bef2.png">

**Comment by PeerRich** [comment]
@emrysal i thought we are using the native javascript function to get the date format correct

**Comment by tadwohlrapp** [comment]
@PeerRich I concur with the mentioned timezone issue.
"Europe/Amsterdam" probably confuses some users as it could be read as the meeting's location.

It would be great if there were more detailed options, like there already are in the autocomplete dropdown. Searching for "Berlin" returns "Berlin GMT +1:00". Would it be possible to display this selected option instead of the Amsterdam fallback?

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2788192/224943956-05e0528a-341b-48ff-8e64-a118b2850664.png">

Also an option to hide the timezone completely would be greatly appreciated. In my experience, users in European countries deal with timezones much less than American ones, since most countries here are contained within a single timezone.

**Comment by PeerRich** [comment]
we won't be able to translate this:

![CleanShot 2023-03-14 at 12 12 07@2x](https://user-images.githubusercontent.com/8019099/224983856-920f616c-1106-401d-a55f-192d833fd1b1.jpg)

it's a third party library and the loading time is already quite high (loads every popular city) and if we had to translate everything it would be too slow to load

**Comment by PeerRich** [comment]
remember, city names are different too:

Munich / München

**Comment by PeerRich** [comment]
at least for now we dont plan to translate that component

**Comment by PeerRich** [comment]
> @PeerRich I concur with the mentioned timezone issue. "Europe/Amsterdam" probably confuses some users as it could be read as the meeting's location.

we haven't heard this before, the location is also above.

> It would be great if there were more detailed options, like there already are in the autocomplete dropdown. Searching for "Berlin" returns "Berlin GMT +1:00". Would it be possible to display this selected option instead of the Amsterdam fallback?

the dropdown is a third party lib which is not so trivial to edit. we could "guess" the closest city to you but it feels like overengineering right now

> Also an option to hide the timezone completely would be greatly appreciated. In my experience, users in European countries deal with timezones much less than American ones, since most countries here are contained within a single timezone.

disagree, this would cause more issues in my opinion

**Comment by PeerRich** [comment]
![CleanShot 2023-03-14 at 12 15 51@2x](https://user-images.githubusercontent.com/8019099/224984798-1eb35206-7de0-4306-8273-c80c26845498.jpg)

will look into this

**Comment by PeerRich** [comment]
i think this is fixed on the new booking page, right @JeroenReumkens ?

**Comment by saschafoerster** [comment]
@PeerRich @JeroenReumkens It is still there. I am using Safari 16.5, german language settings, MacOS 13.4
<img width="668" alt="Bildschirmfoto 2023-05-19 um 08 18 09" src="https://github.com/calcom/cal.com/assets/1153741/2995ca59-2477-489b-9713-09b7f8d4d16a">
Instead of: 
Mi, Jun 28
I would prefer: 
Mi, 28. Juni

**Comment by JeroenReumkens** [comment]
@PeerRich  I see in #8484 @sean-brydon  even removed the full date from here and only shows `Wed 24` for example. Not sure if I really like that change, but it also makes a lot of sense I think – considering the limited space but also the fact that the calendar is on the left. 

So either this isn't an issue anymore, or it's an issue that we definitely want to improve. Let me know.
