### ISSUE TITLE
[CAL-550] Make Google Meet removable (Cal Video as well)

### ISSUE THREAD

**Issue by saschafoerster** [calcom/cal.com#5856]
<img width="682" alt="Bildschirm­foto 2022-12-04 um 20 52 19" src="https://user-images.githubusercontent.com/1153741/205512336-f2179137-f364-4411-bd37-1de1d5970b1c.png">

I want to allow my team to only use Jitsi for videoconferencing. My reasons is mainly for GDPR: I don't want to offer them options, where we don't have data protection contracts (for Jitsi, I change it to our own server URL). So it's a kind of compliance question. If it is not possible via web interface, I would be also happy about hints, if it is possible to remove it from code and then rebuild. 

<sub>[CAL-550](https://linear.app/calcom/issue/CAL-550/make-google-meet-removable-cal-video-as-well)</sub>

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2022-12-05 at 2 16 27 PM" src="https://user-images.githubusercontent.com/53316345/205593209-e2d28df7-1a71-48ff-8be9-be0ea343f13f.png">

In /event-types event setup you can select the location of the meeting. they won't see more options other than that you have selected in the location. doesn't matter how many apps you have installed

**Comment by saschafoerster** [comment]
@Udit-takkar Exactly that is the problem, that my team and users of Cal.com are able to select Google Meet when they should not be even able to have that option.

**Comment by Udit-takkar** [comment]
<img width="794" alt="Screenshot 2022-12-05 at 6 37 30 PM" src="https://user-images.githubusercontent.com/53316345/205644708-cb567ec7-f261-4d5f-8c9a-526130094b92.png">

@saschafoerster if you see here i have only added two location in my event type ( cal video and google meet) and only these two options are showing up on the booking page.

**Comment by saschafoerster** [comment]
@Udit-takkar I try to explain in more detail: 

We have three groups involved: 
- admin (that is me): I am responsible for installing cal.com and data protection
- team: this are my coworkers. They have the right to create bookings in the backend and to configure them as they which. As responsible admin for my team, I have to make sure, they can only choose options they are allowed to chose
- customers: Our customers will be guided to the frontend, where they can chose a date and a location. The team is able to device which locations are visible to customers. 

You showed me a screnshot from the front end to the customers. I know, that the team is able to select from the locations and show to customers only certain options. 
What I am talking about is, that I as an admin want to select, which locations are visible to my team. I don't want that my team is able to offer customers Google meetings. Of course I can tell them, that they are not allowed to, but it would make my live much easier if I could just deactivate Google Meets. This is my requirement as an admin, so I can control where data of our company is processed. Also Cal Video should be removable, same reasoning. I hope you understand what I mean. :)

**Comment by saschafoerster** [comment]
@Udit-takkar @joeauyeung With version 2.3.7., I can turn apps as admin on and off. :) I think that is what I was searching for. 

<img width="757" alt="Bildschirm­foto 2022-12-09 um 08 30 17" src="https://user-images.githubusercontent.com/1153741/206648682-b8559a2c-4166-412c-b424-a7fef376b9d6.png">
