### ISSUE TITLE
[CAL-541] Account deletion won't work

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5864]
### Issue Summary

If a user wants to delete their account, the user can do it from the Profile menu item in the Settings. When clicking the button, a modal opens with the re-entry of the password. Upon confirmation, the user will be logged out. If the user now logs in again, he is in the profile, again.

### Steps to Reproduce

1. Go to https://app.cal.com/settings/my-account/profile
2. Clicked on "Delete account"
3. re-enter the password
4. re-login to the account with the same credentials

### Technical details

Browser:
- Firefox Developer Edition 108.0b9 (64-Bit)

<sub>[CAL-541](https://linear.app/calcom/issue/CAL-541/account-deletion-wont-work)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar can you investigate this?
