### ISSUE TITLE
[CAL-530] Attendee Name Missing — Host Name coming up Twice on Booking

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5869]
![CleanShot 2022-12-05 at 14.54.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9fa58e17-c5b6-468a-8dc9-7a65e5f5d92f/c78b8996-53be-47ac-b72d-20bacc1d1c56)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-530](https://linear.app/calcom/issue/CAL-530/attendee-name-missing-host-name-coming-up-twice-on-booking)</sub>

**Comment by shirazdole** [comment]
cc @Udit-takkar

**Comment by Udit-takkar** [comment]
<img width="582" alt="Screenshot 2022-12-08 at 6 37 31 PM" src="https://user-images.githubusercontent.com/53316345/206454371-3be7341a-f35e-4b38-b4bf-496f19a5f5c5.png">

@shirazdole  not able to reproduce this one

**Comment by Udit-takkar** [comment]
fixed https://github.com/calcom/cal.com/pull/5848
