### ISSUE TITLE
[CAL-532] Duplicating Event Type Issues

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5871]
When duplicating an existing event type, most of the settings of the existing event type are not applied to the new event type. 

The ideal scenario is for a 1:1 duplication of the settings in the event type in it's entirety.

<sub>[CAL-532](https://linear.app/calcom/issue/CAL-532/duplicating-event-type-issues)</sub>

**Comment by PeerRich** [comment]
in the making https://github.com/calcom/cal.com/pull/5851

**Comment by PeerRich** [comment]
i think this has been addressed. can you try again?
