### ISSUE TITLE
[CAL-533] fix ButtonGroup border-radius on hover

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5872]
i think we should fix this on a component level for ButtonGroup, otherwise we need to hotfix this everytime we use ButtonGroup @sean-brydon @JeroenReumkens

_Originally posted by @PeerRich in https://github.com/calcom/cal.com/issues/5828#issuecomment-1337799251_
      

<sub>[CAL-533](https://linear.app/calcom/issue/CAL-533/fix-buttongroup-border-radius-on-hover)</sub>

**Comment by Udit-takkar** [comment]
Related: https://github.com/calcom/cal.com/issues/5800#issuecomment-1337630123

**Comment by Udit-takkar** [comment]
@mocherfaoui yeah i noticed the same after i removed the tooltip prop from  Button and thanks for suggesting Tooltip.Portal.
