### ISSUE TITLE
[CAL-536] Upgrade to Teams Not Working

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5874]
Upgrade to Teams not working

Created via Threads. See full discussion: [https://threads.com/34436813370](https://threads.com/34436813370)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-536](https://linear.app/calcom/issue/CAL-536/upgrade-to-teams-not-working)</sub>

**Comment by PeerRich** [comment]
@alannnc can you find time?

**Comment by PeerRich** [comment]
cant reproduce
