### ISSUE TITLE
[CAL-537] Teams Video Connection not Working

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5876]
Several customers have shared that Microsoft Teams Video conferencing connection isn't working. 

Created via Threads. See full discussion: [https://threads.com/34436816895](https://threads.com/34436816895)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-537](https://linear.app/calcom/issue/CAL-537/teams-video-connection-not-working)</sub>

**Comment by shirazdole** [comment]
Could be related? cc @joeauyeung 
<img width="790" alt="CleanShot 2022-12-08 at 10 33 17@2x" src="https://user-images.githubusercontent.com/16177678/206424815-642789a7-f461-43f4-9301-6f266c9e28d3.png">

**Comment by PeerRich** [comment]
@joeauyeung can you investigate MS Teams?

**Comment by AllenBalaj** [comment]
> Could be related? cc @joeauyeung <img alt="CleanShot 2022-12-08 at 10 33 17@2x" width="790" src="https://user-images.githubusercontent.com/16177678/206424815-642789a7-f461-43f4-9301-6f266c9e28d3.png">

To clarify, my issue isn't related to Teams conferencing, it's only related to pulling in Microsoft 365 calendars. I can't access the Thread conversation linked earlier to confirm, but it this is a video issue only then you can safely dissociate my calendar problems from this ticket.
