### ISSUE TITLE
[CAL-538] Apple Calendar not Connecting

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5877]
Apple Calendar Connecting

Created via Threads. See full discussion: [https://threads.com/34436816070](https://threads.com/34436816070)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-538](https://linear.app/calcom/issue/CAL-538/apple-calendar-not-connecting)</sub>

**Comment by Hybes** [comment]
without having threads I can't see this - but are you getting an issue with Key Length, because I am too 

[[https://i.imgur.com/YGWoYDU.png](url)](https://i.imgur.com/YGWoYDU.png)

**Comment by shirazdole** [comment]
Hi @Hybes — this actually wasn't an issue, the user didn't follow the proper Apple Calendar setup steps: 
![image](https://user-images.githubusercontent.com/16177678/206851471-79c764c7-d562-4c6d-9b36-4e52460cd81a.png)

**Comment by Hybes** [comment]
> Hi @Hybes — this actually wasn't an issue, the user didn't follow the proper Apple Calendar setup steps: 
> 
> ![image](https://user-images.githubusercontent.com/16177678/206851471-79c764c7-d562-4c6d-9b36-4e52460cd81a.png)
> 
> 

So should I raise a new issue for the one I am seeing?

**Comment by PeerRich** [comment]
> So should I raise a new issue for the one I am seeing?

@Hybes yes please
