### ISSUE TITLE
[CAL-539] Avatars not Loading for New Users

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5878]
Avatars not Loading for New Users. In some cases, the choose file button is not available. 

<sub>[CAL-539](https://linear.app/calcom/issue/CAL-539/avatars-not-loading-for-new-users)</sub>

**Comment by Udit-takkar** [comment]
@shirazdole  can you tell on which page . i tried creating a new account and it seem to be working fine on both of these pages.

https://user-images.githubusercontent.com/53316345/205714224-54f0b64f-82fc-4d6b-9ea2-42916aaea705.mov


https://user-images.githubusercontent.com/53316345/205714309-a4977ce4-e4be-44dc-b626-6b09b9005e12.mov

**Comment by Udit-takkar** [comment]
i have fixed something similar before in /getting-started page https://github.com/calcom/cal.com/pull/5549. should be live after it has been deployed.

**Comment by shirazdole** [comment]
Hi @Udit-takkar — I don't actually, but I'll ask the customer where it is occuring

**Comment by hariombalhara** [comment]
Removed caching from Avatar endpoint in cloudflare. Avatar endpoint shouldn't be cached as it's dynamic
