### ISSUE TITLE
Provide more informed Error message when CalDAV connection fails [BAIKAL]

### ISSUE THREAD

**Issue by wetneb** [calcom/cal.com#588]
### Issue Summary

When trying to add a CalDAV service on my account on the official instance (calendso.com), I get the message "Error: Could not add this caldav account". It would be nicer to have a more explicit error message.
The credentials I supply to Calendso work fine when used via Thunderbird/Lightning.
The CalDAV server is a Baikal 0.8.0 instance (https://sabre.io/baikal/).

### Steps to Reproduce
1. (for example) Went to https://app.calendso.com/getting-started
2. Clicked on "Caldav"
3. Filled in my CalDAV URL and credentials.
4. Get the error message

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: Firefox ESR
* Node.js version - don't know

**Comment by wetneb** [comment]
@femyeda if you want credentials to test the integration on my Baikal instance, just shoot me an email ( firstname @ lastname . eu) :)

**Comment by femyeda** [comment]
I'll be in touch.

**Comment by llldar** [comment]
Tested with baikal, can add a baikal account succfully.

Just make sure you set `System Settings` -> `WebDAV authentication type` -> `Basic` and save changes
otherwise the authentication will fail.

**Comment by wetneb** [comment]
Thanks! I will try it again then.

**Comment by wetneb** [comment]
I did not realize this actually requires me to change Baikal's authentication method. It would be nicer if Calendso could support Digest authentication directly (I believe this is a basic feature of most HTTP client). At the very least, the error message you get in the dialog to add a calendar should point to this temporary solution.

Also, the integration suffers from other problems:
- Availability checking is too slow to be usable (#479 )
- When I make a booking, it does not get added to my CalDAV calendar
- Calendso lets me book meetings at times when I am already booked
- There is an inconsistency between the times displayed in the availability checking dialog and the confirmation page (I clicked on the time slot 10:15 and got a confirmation for a booking at 11:15).

I am sorry that I do not have time to open individual issues about all those problems.

**Comment by natelindev** [comment]
Other issues are tracked and being fixed, sorry for the inconveince.

**Comment by ykktrcb7** [comment]
> Tested with baikal, can add a baikal account successfully.
> 
> Just make sure you set `System Settings` -> `WebDAV authentication type` -> `Basic` and save changes otherwise the authentication will fail.

Hi, I did change this configuration in Baikal and this started working with similar services.
Unfortunately, it did not fix it with calendso.
Am I missing something or do I need to do something else?

Thanks in advance.

**Comment by PeerRich** [comment]
it seems like it's still not working @natelindev. got another issue from a customer today

**Comment by ykktrcb7** [comment]
Update on my side:
once there is a valid certificate on my server I was able to connect via Caldav. I will continue with testing and update if I find anything else.

**Comment by PeerRich** [comment]
@natelindev there seems to be still issues with Baikal
<img width="609" alt="image" src="https://user-images.githubusercontent.com/8019099/154372713-2596048e-f986-4590-88fc-608508d2af2a.png">

**Comment by cveneziani** [comment]
Hey there, I'm the author of the message from the screenshot :point_up: 

After sending this report, I joined the cal.com Slack team and found a thread mentioning my issue.
I tried what has been proposed: switch from **digest** to **basic authentication**, and it finally works.

What about providing a link next to the `Could not add this caldav account` ?
The link could point to a page that lists a few known open source caldav servers and how to configure them so that they work with Cal.com 

That might reduce support tickets :)

**Comment by alishaz-polymath** [comment]
@cveneziani Thank you for confirming that it works for you, and for the wonderful suggestion. I'm keeping this ticket open for the time being, to make sure we can provide a better context with the error message. 🙏
