### ISSUE TITLE
[CAL-540] Select Full and Multiple Days from an Event Type

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5881]
Ability to give users the ability to add a single or multiple days booking abilities to event types. Similar to blocking an entire day or multiple days in Google Calendar.

The use case varies from co-working spaces to booking items.

<img width="303" alt="CleanShot 2022-12-05 at 18 32 29@2x" src="https://user-images.githubusercontent.com/16177678/205714803-2df56e87-6159-4c5f-b6a9-dd1391c2bbdf.png">
<img width="461" alt="CleanShot 2022-12-05 at 18 32 33@2x" src="https://user-images.githubusercontent.com/16177678/205714812-8cf68289-1d00-4f44-885e-56460b4e1aa3.png">

<sub>[CAL-540](https://linear.app/calcom/issue/CAL-540/select-full-and-multiple-days-from-an-event-type)</sub>

**Comment by harshsinghatz** [comment]
@Jaibles do we have designs for this?

**Comment by PeerRich** [comment]
we have to deprioritize this and do this later. lots of implications
