### ISSUE TITLE
[CAL-548] Failed to load resource the server responded with a status of 500

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#5890]
### Steps to Reproduce

1. Create an event type with the following setting: Redirect on booking (Redirect to a custom URL after a successful booking) 
2. Click on the cancellation hyperlink in the received confirmation and reminder notifications

**Actual Result:** For a few seconds, I see a 500 Internal Server Error page

![50SOLpTw4R](https://user-images.githubusercontent.com/108827171/205879464-90594f5a-8e45-4796-af49-b888a2c258b0.png)
 [Failed to load resource the server responded with a status of 500.log](https://github.com/calcom/cal.com/files/10164922/Failed.to.load.resource.the.server.responded.with.a.status.of.500.log)

<sub>[CAL-548](https://linear.app/calcom/issue/CAL-548/failed-to-load-resource-the-server-responded-with-a-status-of-500)</sub>

**Comment by PeerRich** [comment]
@G3root can you investigate this?

**Comment by PeerRich** [comment]
or @hariombalhara who built redirects

**Comment by guri-kndegwa** [comment]
this is also happening for me and causing other bugs within the application.

**Comment by hariombalhara** [comment]
Not able to replicate this issue. There has to be something else. @Shahane-Aloyan If it's on cal.com, can you share the cal link.

@guri-kndegwa Possible to share the errors from next.js server that's running

**Comment by guri-kndegwa** [comment]
@hariombalhara I have self-hosted it at [this URL](https://appointments.guritech.co/kimani-ndegwa/30min)

**Comment by hariombalhara** [comment]
@guri-kndegwa I don't have access to the logs for your server. You would need to see the logs. You will certainly see some error there. Please share that error here,

**Comment by guri-kndegwa** [comment]
Sorry @hariombalhara . i misunderstood your question.
THis seems to be the most prevalent issue on the server logs.

```
RangeError: Invalid time value
@calcom/web:start:     at Date.toISOString (<anonymous>)
@calcom/web:start:     at M.u.toISOString (/app/node_modules/dayjs/plugin/utc.js:1:1907)
@calcom/web:start:     at useSlots (/app/apps/web/.next/server/chunks/3942.js:697:31)
@calcom/web:start:     at SlotPicker (/app/apps/web/.next/server/chunks/3942.js:765:40)
@calcom/web:start:     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@calcom/web:start:     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@calcom/web:start:     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@calcom/web:start:     at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
@calcom/web:start:     at bd (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
@calcom/web:start:     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
@calcom/web:start:     at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
@calcom/web:start:     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
@calcom/web:start:     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@calcom/web:start:     at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
@calcom/web:start:     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
@calcom/web:start:     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

```

**Comment by hariombalhara** [comment]
@emrysal Is this the issue where some unsupported timezone or something like that is selected?

**Comment by guri-kndegwa** [comment]
@hariombalhara any update on this? i tried playing around ith the timeones but it is still failing

**Comment by piotrski** [comment]
@hariombalhara you can create a new project from the cal template on Railway here https://railway.app/template/cal to reproduce this problem. You will get 500 when you try to open the `AvailabilityPage`.

**Comment by PeerRich** [comment]
i dont think that template is up-to-date anymore
