### ISSUE TITLE
[CAL-543] /settings /calendars - multiple UI issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5892]
* [ ] UI issues in screenshot below
* [ ] No save feedback, if it's auto-saving - please show a toast.

![CleanShot 2022-12-06 at 10.16.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/220944ba-485e-4684-b117-7b79df7b4a6e/f0dec54d-d4d2-4774-94a1-547b11148285)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-543](https://linear.app/calcom/issue/CAL-543/settings-calendars-multiple-ui-issues)</sub>

**Comment by Udit-takkar** [comment]
UI issues solved here https://github.com/calcom/cal.com/pull/5879
