### ISSUE TITLE
[CAL-544] Wrong Cal.com link should throw off a 404

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5893]
When you type in the wrong cal.com link, you get a "null" booking page instead of a 404 page.

For example: cal.com/shiraz/swag - this doesn't exist, but this page is created:

![CleanShot 2022-12-06 at 10.19.19@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4dcde39b-4b74-4450-b95d-305bebb633e9/c086b7aa-eec4-48b2-b80c-4d1ca612bfe2)

Something like this should be presented instead: [https://cal.com/ultimate/pricing](https://cal.com/ultimate/pricing)

![CleanShot 2022-12-06 at 10.20.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2ad35950-f212-4e3e-b773-b41caef01440/1db23590-ad1b-4cd0-9299-ce53c1abfea6)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-544](https://linear.app/calcom/issue/CAL-544/wrong-calcom-link-should-throw-off-a-404)</sub>

**Comment by harshsinghatz** [comment]
https://github.com/calcom/cal.com/pull/5700#event-7967532900 this is actually solved and merged yesterday but i don't know when would this go live. I don't much about the release cycle @PeerRich

**Comment by PeerRich** [comment]
we are preparing a new bundled release this week! @zomars
