### ISSUE TITLE
[CAL-555] Editing of existing Event-type returns an error if “Allow booker to select duration” is active

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5894]
### Issue Summary

On editing of an existing event-type with “Allow booker to select duration” enabled, I've got the following error:

> Event Setup: Please select a valid default duration.

I think the value for “default duration” won't be set on editing, even when displayed:

![grafik](https://user-images.githubusercontent.com/48084558/205895474-abe71f84-abd2-4f27-b560-ecc5013956be.png)

### Steps to Reproduce

1. Create an event-type with “Allow booker to select duration” set and multiple durations
2. Reload the page
3. Click “Save”

### Technical details

Browser:
Firefox Developer Edition 108.0b9 (64-Bit)

<sub>[CAL-555](https://linear.app/calcom/issue/CAL-555/editing-of-existing-event-type-returns-an-error-if-allow-booker-to)</sub>

**Comment by Udit-takkar** [comment]
@rene-mueller thanks for reporting. i will try to reproduce this

**Comment by rene-mueller** [comment]
@Udit-takkar if you need help feel free to contact me
