### ISSUE TITLE
[CAL-545] Duration Doesn't Auto-Save

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5895]
When setting Duration as "Allow Booker to Select Duration" after setting the parameters, if I navigate to "availability," but did not press save, it returns back to the previous duration. 

When I set my duration, I also changed my location and that auto-saved.

![CleanShot 2022-12-06 at 11.13.33@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b136263f-17cb-4d6a-b8c0-ee426a2669d6/d8470b7c-efde-4f5b-bfbe-2ae1ff9bfd79)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-545](https://linear.app/calcom/issue/CAL-545/duration-doesnt-auto-save)</sub>

**Comment by Emmanuel-Melon** [comment]
> cc @leog

So would you like to autosave on navigation or after you're done making the desired changes?
