### ISSUE TITLE
[CAL-546] Available Durations selected out of order doesn't auto order by duration

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5896]
![CleanShot 2022-12-06 at 11.15.54@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/07e53851-c1ff-4c57-96cb-68638985e2ae/4fb31d3e-a86e-4e59-8975-2975884b7faa)

If you select, 5-mins, 10-mins, 20-mins, then 15-mins, 15-mins should be auto rearranged before 20-min

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-546](https://linear.app/calcom/issue/CAL-546/available-durations-selected-out-of-order-doesnt-auto-order-by)</sub>

**Comment by shirazdole** [comment]
cc @leog @Udit-takkar

**Comment by shirazdole** [comment]
Not urgent

**Comment by harshsinghatz** [comment]
@shirazdole  https://www.loom.com/share/8d2d68788ee74fa58824b65e687e15a3 can you check this and confirm that this is the implementation you wanted!
