### ISSUE TITLE
[CAL-549] Redirect after event deletion

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#5898]
###Steps to Reproduce

1. Create an event type with the following setting: Redirect on booking (Redirect to a custom URL after a successful booking)
2. Go to the canceled event page 
3. Or click the  black "Cancel Event" button

**Actual Result:** After 8 seconds, I'm redirected to the page where we thank the customer for a booking 
** Expected result** I should only be redirected after a successful booking and not if the event is canceled
![11T3HzO6SS](https://user-images.githubusercontent.com/108827171/205905686-11b798ae-1023-49f8-9ce4-b6eac36d4753.png)

<sub>[CAL-549](https://linear.app/calcom/issue/CAL-549/redirect-after-event-deletion)</sub>

**Comment by PeerRich** [comment]
@hariombalhara can you investigate? you built the redirect
