### ISSUE TITLE
[CAL-551] Poll Event-type

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#5902]
In order to select the best time taking into account multiple bookers, there should be an option to make an event type a poll, say my "Stand-up" Event Type, that gathers multiple booking options from each booker, then in the last step, name and email is required, but the final action is not booking, it's sending poll response.

On the other hand, the organizer should receive an email each time someone sends a poll response, seeing all the options marked as possible by bookers, to be able to see matching booking options and the number of bookers available for each option. Also, there should be a Poll Results page within the event type configuration to be able to see the exact same information.

The organizer should be able to select an option from the available ones, and book the meeting, for which the bookers that were available at that time should get a booking invitation, allowing the organizer to opt to send a booking invitation to the unavailable bookers for the selected option.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-551](https://linear.app/calcom/issue/CAL-551/poll-event-type)</sub>

**Comment by SterArcher** [comment]
This is quite an important feature, it is really important to have an option to create an event with multiple people voting on the time and date like alternatives allow (e.g. Rallly, Calendly) and then host choosing the one most suitable.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/29688990/216840892-168951ed-7991-490d-9666-a52beae39500.png">

**Comment by PeerRich** [comment]
it is on the roadmap but a very big project so bare with us

**Comment by jenningsb2** [comment]
Excited for this one! 

SavvyCal's implementation is incredible if you're looking for inspo 🎨: https://savvycal.com/meeting-polls/

**Comment by leog** [comment]
@PeerRich Willing to take this one after orgs v1 is completely closed unless someone else was assigned this after Jeroen

**Comment by Jaibles** [comment]
> @PeerRich Willing to take this one after orgs v1 is completely closed unless someone else was assigned this after Jeroen

We might need you to tackle a v2 of managed event types before this 👀

**Comment by leog** [comment]
> We might need you to tackle a v2 of managed event types before this 👀

@Jaibles sure, I’m up for that too! Any GH issue to see specs and designs? First things first: make sure orgs v1 is completely closed of course.

**Comment by PeerRich** [comment]
closing as this is very low priority, too low for a "low priority" since it is an entirely new app basically. maybe next year but i dont want anyone to get their hopes too high
