### ISSUE TITLE
[CAL-552] app store: analytics category whitescreen

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5907]
[https://app.birdeatsbug.com/sessions/O4k5CeZxdKOJBwUpixnAYlRN2Bsw1Wq-itjpPMTDFRf7](https://app.birdeatsbug.com/sessions/O4k5CeZxdKOJBwUpixnAYlRN2Bsw1Wq-itjpPMTDFRf7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-552](https://linear.app/calcom/issue/CAL-552/app-store-analytics-category-whitescreen)</sub>

**Comment by leog** [comment]
I don't think this is reproducible anymore, could you please recheck @PeerRich 🙏

**Comment by PeerRich** [comment]
still reproducable

**Comment by PeerRich** [comment]
fixed a long time ago
