### ISSUE TITLE
[CAL-554] Time format hint in general settings is broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5917]
![CleanShot 2022-12-07 at 16.48.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/91b8b732-c4b0-476f-bf29-0e809b01c232/93f6156d-039c-4c8b-b6be-b48bcc308a6b)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-554](https://linear.app/calcom/issue/CAL-554/time-format-hint-in-general-settings-is-broken)</sub>

**Comment by Udit-takkar** [comment]
@harshsinghatz translation is missing for the key timeformat_profile_hint . try looking git history to get the text from common/en.json or look into figma file.

**Comment by harshsinghatz** [comment]
@Udit-takkar made the fix. But i randomly jumped to a on older commit to get the missing variable. Is there a better way to actually see at which point the changes were made?

**Comment by Udit-takkar** [comment]
@harshsinghatz it's fine as we don't know when this key was removed by mistake.
