### ISSUE TITLE
[CAL-559] Add {location_link} or similar as a variable in workflows

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5922]
Created via Threads. See full discussion: [https://threads.com/34437276982](https://threads.com/34437276982)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-559](https://linear.app/calcom/issue/CAL-559/add-location-link-or-similar-as-a-variable-in-workflows)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli

**Comment by CarinaWolli** [comment]
Duplicate of https://github.com/calcom/cal.com/issues/5421 and already implemented. Variable is called {MEETING_URL}
