### ISSUE TITLE
[CAL-560] Outdated variables in translations

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5923]
![Screenshot 2022-12-02 at 16.06.13.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/708e9dc0-788d-4f36-9bc3-f09e8494525d/2796ff0a-f09c-40d7-a532-997fdaa7f5b7)

Maybe we can add a Github Action check to ensure that all common.json files have same variables for the same keys. Ordering won't matter, just all the variables should be present. We can consider english one as the expected value and compare all languages with it.

Full threads conversation: [https://threads.com/34436586866?u=34431284497&pl=UNREAD](https://threads.com/34436586866?u=34431284497&pl=UNREAD)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-560](https://linear.app/calcom/issue/CAL-560/outdated-variables-in-translations)</sub>

**Comment by PeerRich** [comment]
is this still open?
