### ISSUE TITLE
[CAL-562] Console.cal.com Stripe Billing Portal

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5926]
Some console clients cannot manage their console subscription from the Stripe Billing Portal

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-562](https://linear.app/calcom/issue/CAL-562/stripe-billing-portal)</sub>

**Comment by PeerRich** [comment]
they find their billing in console.cal.com

**Comment by PeerRich** [comment]
@zomars is it possible to show the console billing in app.cal.com stripe's billing portal too?

**Comment by zomars** [comment]
> @zomars is it possible to show the console billing in app.cal.com stripe's billing portal too?

They're treated as different customers as they might not be related at all (a console user may not use cal.com paid features) And are different databases

**Comment by PeerRich** [comment]
@shirazdole tell them to log into console and then go to billing
