### ISSUE TITLE
Text field for Location at booking

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5930]
### Is your proposal related to a problem?

Possibility that the user who books a meeting gets a text field in which he can enter the location.

**Comment by PeerRich** [comment]
i think we have that, no?

**Comment by rene-mueller** [comment]
@PeerRich currently there is only the possibility that the member provides a link. however, it is not possible that the booking party provides a link.

**Comment by PeerRich** [comment]
hmm for this edge case i would recommend just having an additional input

**Comment by rene-mueller** [comment]
@PeerRich of course this can be solved by this. but unfortunately the location cannot be disabled in the event type settings. So it is not clear for the user where the event happens, because there are two locations.

**Comment by PeerRich** [comment]
hmm... any advice how we should call this in the location select? 

![CleanShot 2023-02-08 at 16 22 26@2x](https://user-images.githubusercontent.com/8019099/217572807-b1688b9b-4dc6-414e-baf7-69816c491d64.jpg)

**Comment by PeerRich** [comment]
i dont think this is planned. unless someone reopens this with a good usecase

**Comment by rene-mueller** [comment]
@PeerRich the best usecase is that a participant is not allowed to use any of the platforms provided. Thus, the participant can use bring a own platform.
