### ISSUE TITLE
[CAL-566] error in workflows

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5940]
from a user:

When designing my workflows, I encountered the following error:
TypeError: e.steps[0] is undefined.

I've attached a screenshot of the situation below. Currently, I cannot edit or use any workflows which is annoying. Can you maybe reset my workflows so I can work on them again?

![image](https://user-images.githubusercontent.com/8019099/206572631-64e19664-2daf-46ca-9082-fbe3527c1922.png)

<sub>[CAL-566](https://linear.app/calcom/issue/CAL-566/error-in-workflows)</sub>

**Comment by NightmindOfficial** [comment]
I'm the user reporting this.

Some further information I forgot mentioning when writing the ticket, I think I may have tried to save an invalid workflow by leaving a required field blank. So this might be an error resulting from missing input validation.

**Comment by PeerRich** [comment]
oh thats great feedback. lemme look into your account to see if I can reset the workflow

**Comment by NightmindOfficial** [comment]
Following up on my initial assumption of the issue being caused by missing input validation, I could not reproduce this issue. As of now, empty fields are accepted and filled with default input.

**Comment by CarinaWolli** [comment]
@NightmindOfficial Sorry for the late response, is this still an issue?

**Comment by PeerRich** [comment]
i dont think this is happening anymore
