### ISSUE TITLE
[CAL-567] Booking limit not working

### ISSUE THREAD

**Issue by Guray00** [calcom/cal.com#5941]
### Issue Summary

If I put a booking limit to an event of  “1 per day”, not always seems to work: in some days is possible to book more than once and other ones is not possible to book even one event (no other bookings or availability conflicts). I tried to set “1 per year” and even after that I could book twice.  I'm on GMT+1 

### Steps to Reproduce

1. Set a day limit to "1 per day"

<sub>[CAL-567](https://linear.app/calcom/issue/CAL-567/booking-limit-not-working)</sub>

**Comment by emrysal** [comment]
Should be fixed by #6119 👍
