### ISSUE TITLE
[CAL-574] SMS reminder not working for workflows

### ISSUE THREAD

**Issue by sydwardrae** [calcom/cal.com#5943]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Reported by customer and tested myself, send SMS reminder to a specific number doesn't work in testing or in application. 

### Technical details

<sub>[CAL-574](https://linear.app/calcom/issue/CAL-574/sms-reminder-not-working-for-workflows)</sub>

**Comment by CarinaWolli** [comment]
I just tested everything around SMS workflow actions and it's working fine for me. @sydwardrae With it doesn't work in testing, do you mean the 'Test Action' button does not work either?

**Comment by sydwardrae** [comment]
@CarinaWolli yeah, the test action also wasn't working for me. I wonder if it's something with US phone numbers? if that's even a possibility? the customer said his wasn't working either and he was based in the US
