### ISSUE TITLE
[CAL-893] Disable branding, only possible for owner of team

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5947]
### Issue Summary

Disable the branding is only possible for owner of a team. For the Administrators, the input is disabled.

### Steps to Reproduce

1. Invite someone to a team
2. Switch accounts
3. Accept the membership on the new account
4. Try to disable the branding for own account (in appearance)

### Technical details

Browser: Firefox Developer Edition 108.0b9 (64-Bit)

<sub>[CAL-893](https://linear.app/calcom/issue/CAL-893/disable-branding-only-possible-for-owner-of-team)</sub>

**Comment by rene-mueller** [comment]
Belongs to #5913

**Comment by rene-mueller** [comment]
@sean-brydon

**Comment by PeerRich** [comment]
i think this works now, can you test?

**Comment by rene-mueller** [comment]
@PeerRich i didn't got your notification. I'll tested it and it worked :)
