### ISSUE TITLE
[CAL-570] Show more times on public booking page

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5949]
Allow people to have ranked availability that enables people to click "show more times" if there isn't time slots that are available to them.

It allows people to set less preferred hours that they can be booked that they want to make available to someone only if they can't find a slot in their preferred hours.

It removes the need for people to have to do this:

![CleanShot 2022-12-09 at 12.16.09@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5885c358-5d11-4a00-b4db-3c089ccb94a2/334760f2-1e6d-4d19-986e-349260f41527)

In your event type settings you can toggle on more than 1 availability schedule and set your preferred one.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-570](https://linear.app/calcom/issue/CAL-570/show-more-times-on-public-booking-page)</sub>

**Comment by PeerRich** [comment]
can you explain this more?

**Comment by Jaibles** [comment]
[9862e4d9-5007-444d-8a3f-cf82733ce4e7](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/43a8b44c-1cf2-4b79-b1d6-70b3ac88bc8d/9862e4d9-5007-444d-8a3f-cf82733ce4e7)

@PeerRich

**Comment by PeerRich** [comment]
revisiting once we have the new booking page merged

**Comment by TyceHerrman** [comment]
I don't think this was ever revisited, at least on GH issues. Coming from Savvycal, which was the inspiration for the original request, and really missing this feature. @ciaranha @PeerRich can this get reopened?
