### ISSUE TITLE
[CAL-579] Highlight required inputs instead of yellow warning message

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#5950]
### Issue Summary

We have updated one of the Cal.Com events with text inputs, now it has radio buttons. 
![0PGYOhniKE](https://user-images.githubusercontent.com/108827171/206701336-eb597b32-a8d1-4035-8720-3e1aaff242dd.png)

1. And when I navigate to the event page with text inputs
2. And don't click on any of the obligatory inputs
3. Click on the "Confirm" button 

Actual Result: I see a yellow warning message - `**Could not book the meeting. invalid_type in 'customInputs,0,value':** `
which does not explain well to the average user why he cannot book the meeting 

Expected Result: I expect them to be highlighted in red

<sub>[CAL-579](https://linear.app/calcom/issue/CAL-579/highlight-required-inputs-instead-of-yellow-warning-message)</sub>

**Comment by sean-brydon** [comment]
Very good point - I will pick this up tomorrow as this could deffo have some UX/UI improvements incase of failure :)  

Thanks for reporting this
