### ISSUE TITLE
Google Meet installation fails

### ISSUE THREAD

**Issue by NightmindOfficial** [calcom/cal.com#5954]
### Issue Summary

Installing the app "Google Meet" is not possible. The thrown error code is:
![grafik](https://user-images.githubusercontent.com/62300272/206710533-fc6aaf12-5c56-41a3-a4b0-2555e658a6af.png)

### Steps to Reproduce

1. Go to Apps --> App Store
2. Either click directly on the install button on the Google meet card, or open the app page and try to install it from there

### Technical details

- Browser version: Firefox 107.0.1, Chrome 108.0.5359.99

**Comment by PeerRich** [comment]
this should be fixed by now, waiting for deployment @joeauyeung

**Comment by joeauyeung** [comment]
Fixed in ##5953
