### ISSUE TITLE
[CAL-571] When CalDAV server is slow, scheduling a meeting leads to: `unexpected character at line 1 column 1 of the JSON data`

### ISSUE THREAD

**Issue by victorpaleologue** [calcom/cal.com#5955]
### Issue Summary

I have setup the CalDAV app, and an event of 1 hour of call via cal.com.
People can schedule appointments here: https://cal.com/victor-paleologue/1h.
They receive an e-mail notification, but not me, and the form displays an error (sorry for my French):
> La réunion n'a pas pu être réservée. unexpected character at line 1 column 1 of the JSON data

![image](https://user-images.githubusercontent.com/8899804/206712338-194f283e-0ac5-45f3-b49f-8cdaaa79b831.png)

### Steps to Reproduce

1. Schedule an appointment here: https://cal.com/victor-paleologue/1h
2. Be very clear that this is a test, please.
3. See for yourself =)

### Technical details

- Firefox 107.0.1
- Mac OS Ventura 13.0.1
- arm64 processor

<sub>[CAL-571](https://linear.app/calcom/issue/CAL-571/when-scheduling-a-meeting-unexpected-character-at-line-1-column-1-of)</sub>

**Comment by PeerRich** [comment]
@alishaz-polymath can you investigate this? 

@victorpaleologue can you confirm that this is only happening with CalDav?

**Comment by victorpaleologue** [comment]
@PeerRich could you detail a little bit how to check with something else than CalDAV without uninstalling the CalDAV integration ? I did not see a way to specify which calendar to work with for an event type.

**Comment by PeerRich** [comment]
if possible uninstall it and add another calendar. do you have a Gmail by any chance?

**Comment by victorpaleologue** [comment]
Actually I can tell cal.com to schedule the meeting on the Google Agenda without uninstalling the CalDAV one.

Here is the setup :

![image](https://user-images.githubusercontent.com/8899804/207300358-a7381635-5cba-4566-825a-0cf4372ac0e4.png)

It works fine with this setup.

But I need it to work with CalDAV.

**Comment by victorpaleologue** [comment]
Note that it takes a loooong time before it fails.
The error says the JSON could not be parsed, as if it was replaced with an error message or simply nothing.
So I suspect a timeout error.

**Comment by sashajenner** [comment]
I can't seem to reproduce this error by scheduling an appointment from your webpage https://cal.com/victor-paleologue/1h

**Comment by victorpaleologue** [comment]
I can confirm. It's probably due to the new version of cal.com.
Who should I thank?
There's that bounty to claim...

**Comment by victorpaleologue** [comment]
Sorry, I had switched back to using Google Calendar. It's back to not working =)

**Comment by bopearce** [comment]
Sounds good. Let me know when you have tried. Thanks!
________________________________

**Comment by victorpaleologue** [comment]
I have tried, it fails.

**Comment by bopearce** [comment]
What is the link to the new cal invite? Can you send me a screenshot of the cal invite settings? Do you have any advanced settings set or are they basic settings? Does this happen on every calendar event?

A SS similar to this:
[cid:cf3caa32-84b1-4b79-b6f8-2079e246b78e]
________________________________

**Comment by victorpaleologue** [comment]
https://cal.com/victor-paleologue/test
It's using the default settings.
It happens on every calendar event.
What is the SS?

**Comment by bopearce** [comment]
A screenshot
________________________________

**Comment by bopearce** [comment]
I see the problem, but it is very bizarre. I'm not sure what exactly is causing it. The issue is apparent here when the request is made to create the calendar invite:
[cid:248f415f-7fd6-4632-9a6d-9bab4c53d017]
The Response in the above screenshot returns 502 bad gateway. The request should return a JSON blob, it isn't returned and then the javascript on the site fails with the error "Could not book the meeting. unexpected character at line 1 column 1 of the JSON data" because it is expecting a response with JSON not some random HTML content.

This led me to think that it was maybe an issue with the Event, but obviously not. Which makes me think it must be an error with your account.

Can you please create a new test account and see if you encounter the same issue? Thanks.
________________________________

**Comment by PeerRich** [comment]
@alishaz-polymath can you investigate this?

**Comment by victorpaleologue** [comment]
With a test account, using a test account on the nextcloud instance, it works : https://cal.com/testvictorpaleologue/15min

**Comment by victorpaleologue** [comment]
With the same cal.com test account, if I try to tie it to my actual nextcloud instance, it failed. I tried again twice, and then it worked. It seems related to my nextcloud account.
Anyways, there is an issue when reporting the error. The HTTP code is clearly not a 200, so it should not be blindly parsing the JSON, and it should report what really happened : the nextcloud account has an issue.

**Comment by victorpaleologue** [comment]
I mean, more precisely : please let this error message be transparent of the error code of the remote calendar.

**Comment by victorpaleologue** [comment]
Can you re-open the issue, or should I write another issue to get the poor error message fixed?

**Comment by emrysal** [comment]
@victorpaleologue Probably closed on accident, no need to be rude about it 👎

**Comment by victorpaleologue** [comment]
Sorry, I did not take well seeing the issue closed so fast, but it's no excuse for being rude.

**Comment by PeerRich** [comment]
wops, yea by accident

**Comment by victorpaleologue** [comment]
Good morning, it appears the error message changed today. It is now:
```La réunion n'a pas pu être réservée. No available users found.```

**Comment by alishaz-polymath** [comment]
Good Morning @victorpaleologue 
That's strange. From the initial assessment it appeared as though the server was timing out, but this response suggests there's a failure of availability for the user in contention. I still wonder if server timeout is actually throwing this error (which is inaccurate, obviously) 🤔

**Comment by victorpaleologue** [comment]
I have just updated my Nextcloud instance just in case, I get the same issues.

**Comment by alishaz-polymath** [comment]
But you do confirm that this doesn't happen when attempted with the test account on the same nextcloud instance?

**Comment by victorpaleologue** [comment]
Yes, with the Nextcloud test account on the same Nextcloud instance, it works.
The biggest difference I can think of between the two Nextcloud accounts is the size of the agenda and tasks. Seen from cal.com, is it still giving a 502 error?

**Comment by victorpaleologue** [comment]
After figuring out ways to optimize the nextcloud instance, scheduling an event works.
However if the event is in an extended slot from a "date override", I get the `No available users found.` error. That one is therefore another issue. Shall I open it?

**Comment by victorpaleologue** [comment]
I can confirm that if I extend the schedule instead of using a date override, I can schedule the meeting.

**Comment by victorpaleologue** [comment]
Well in the end, I had it working again.
So let's say @bopearce has solved it and get on with it.
I'll write another issue about the poor error message, and another one about "No available users found.".

**Comment by victorpaleologue** [comment]
@bopearce reminder to go reclaim [the bounty](https://app.bountysource.com/issues/114483666-cal-571-when-caldav-server-is-slow-scheduling-a-meeting-leads-to-unexpected-character-at-line-1-column-1-of-the-json-data).
