### ISSUE TITLE
Reset password instruction mail has the wrong support-mail 

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5957]
### Issue Summary

When a user requests a password reset, there will send a mail with the wrong support mail-address. That is, specially for self-hosted pages, not good.

![grafik](https://user-images.githubusercontent.com/48084558/206722270-6efb4e1c-0663-4e46-858a-a17bdb9ce4b6.png)

### Steps to Reproduce

1. Reset your password 
2. Watch the mail

**Comment by PeerRich** [comment]
oh yeah that should use the new .env support email
