### ISSUE TITLE
[CAL-575] Apps Admin Panel: Some apps appear as disabled when they're not

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#5963]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/35032f70-ebb0-471e-9129-d48feee78464/380c7352-a71d-4c76-862b-604a5e908750)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-575](https://linear.app/calcom/issue/CAL-575/apps-admin-panel-some-apps-appear-as-disabled-when-theyre-not)</sub>

**Comment by joeauyeung** [comment]
Not sure if it was a weird bug but they're all displaying properly. Closing for now.

**Comment by zomars** [comment]
Still happening @joeauyeung specifically in the "Other" category:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/3504472/207413674-b473a2c5-f4e1-4498-894a-3cb590281be8.png">
