### ISSUE TITLE
[CAL-576] Round Robin not Displaying Actual Available Times

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5964]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-576](https://linear.app/calcom/issue/CAL-576/round-robin-not-displaying-actual-available-times)</sub>

**Comment by PeerRich** [comment]
do you have more context? screenshots or a loom?

**Comment by shirazdole** [comment]
Updated: I tried to recreate the bug, but wasn't able to: [https://app.birdeatsbug.com/sessions/RQrsnruvaRdUTX0KdvSeo6dLfnxRujzh1dwD_MDybFYN](https://app.birdeatsbug.com/sessions/RQrsnruvaRdUTX0KdvSeo6dLfnxRujzh1dwD_MDybFYN)

Here is how I tested it based on their feedback:

**Feedback:** "Issue with the Round Robin link displaying times that are not actually available. My 1:1 link is displaying the correct availabilities."

**How I tested: "**For the test, I created a round robin with just me and compared it against my 1:1 link. It pulled the availability properly."

Followed up with customer for a Loom or screenshots or if I did the test correctly or not.

**Comment by shirazdole** [comment]
Update:

Round Robin displays times that are actually not available, and when a user goes to book that time, they are prompted it is not available. A loom is shared by the customer in Threads Here: [https://threads.com/34437675713?s=fxHeEaHd8XxLFhFJtti38W](https://threads.com/34437675713?s=fxHeEaHd8XxLFhFJtti38W)
