### ISSUE TITLE
Free access or discount for non-profit organizations

### ISSUE THREAD

**Issue by jahirfiquitiva** [calcom/cal.com#5965]
### Is your proposal related to a problem?

Not really

### Describe the solution you'd like

I am one of the organizers of [Boyacá Dev](https://github.com/boyaca-dev). We are a non-profit organization or community, we organize events both online and in-person to share knowledge and cover different technology and software development related topics.

Every now and then we'd like to meet with possible sponsors for the events and community. Anyway, the sponsorships are invested into:
- server/domain costs
- online event stream platform
- speaker and/or event swag/gifts
- other organization fees

So there's little left to cover additional costs, but as I mentioned before, we'd like to use `cal.com` to be able to have the different team members accounts connected and be able to schedule calls with our possible sponsors; so free access or even a discounted price, would be highly appreciated.

Please let me know your thoughts about this idea. Thanks in advance!

**Comment by PeerRich** [comment]
yes, we have non-profit discounts. email me: peer@cal.com
