### ISSUE TITLE
[CAL-577] Enable user profile custom domain

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#5971]
Let users assign a custom domain to their profile page to give them the flexibility to share their own custom domain to get a booking.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-577](https://linear.app/calcom/issue/CAL-577/enable-user-profile-custom-domain)</sub>

**Comment by PeerRich** [comment]
lets go!!

**Comment by PeerRich** [comment]
this can live somewhere in the user settings. I think it has to be a paid feature

**Comment by PeerRich** [comment]
lets ship subdomains for organisations first
