### ISSUE TITLE
Exclude the possibility to book events with invalid email addresses

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#5972]
I provide a list of invalid email addresses with which you can book events, but the user should not be able to do this

あいうえお@example.com - Unicode char as address
email@-example.com - The leading dash in front of the domain is invalid
email@example.web - .web is not a valid top-level domain
email@111.222.333.44444 - Invalid IP format
just”not”right@example.com

**Comment by PeerRich** [comment]
agree. we should have a Zod validation on that input
