### ISSUE TITLE
[CAL-582] Team admin can see all connected caldav of all members

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#5982]
"Yep, that is the case: I am admin and I can see all the CalDAV calendars from my team in the backend, where I only should see my own calendar (my-account)"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-582](https://linear.app/calcom/issue/CAL-582/team-admin-can-see-all-connected-caldav-of-all-members)</sub>

**Comment by rene-mueller** [comment]
@alishaz-polymath i think the issue can be closed :) fyi @PeerRich

**Comment by alishaz-polymath** [comment]
Thank you for confirmation🙏
