### ISSUE TITLE
[CAL-583] Dialog not scrollable and cut off if too long

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5987]
### Issue Summary

Dialog is not scrollable anymore and gets cut off if it is too long:
![Screenshot 2022-12-12 at 16 14 59](https://user-images.githubusercontent.com/30310907/207081859-d82f90f8-17db-4906-b857-3d588a68b8cb.png)
(Screenshot from 'Test Preview' in routing forms)

This was our old dialog and scrolling worked:
![CleanShot 2022-11-09 at 10 15 22](https://user-images.githubusercontent.com/30310907/207082232-823081a6-e943-4494-b52b-63649286fa24.gif)

<sub>[CAL-583](https://linear.app/calcom/issue/CAL-583/dialog-not-scrollable-and-cut-off-if-too-long)</sub>

**Comment by CarinaWolli** [comment]
@JeroenReumkens Could you maybe take a look at that? We had a conversation about that a while ago

**Comment by PeerRich** [comment]
still open? @CarinaWolli
