### ISSUE TITLE
[CAL-585] dynamic group links + flexible schedule

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5989]
instead of showing the 3 event-types with different time, it should instead directly show the booking page with 3 times to pick from

now that we can allow multiple schedules, we can get rid of this screen:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/18c36318-930f-479c-b3ee-dfb30c579dbf/8b5a4db3-163e-4281-b30a-332a4327e6cf)

instead, we can do [cal.com/peer+bailey](http://cal.com/peer+bailey) which immediately shows this:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fc848208-f057-4865-92eb-945a8cf14b3b/351afea6-a73a-4951-8849-b96b5ab06d65)

but with 3 different durations (15, 30, 60)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-585](https://linear.app/calcom/issue/CAL-585/dynamic-group-links-flexible-schedule)</sub>

**Comment by hussamkhatib** [comment]
Hey @PeerRich, 
I would like to pick up this issue.

approach:
- conditonal rendering based on single or group meet.
- If it is group meet, render the second screen and provide a dropdown to select 15, 30, 60 min respectively.

**Comment by PeerRich** [comment]
> Hey @PeerRich, I would like to pick up this issue.
> 
> approach:
> 
> * conditonal rendering based on single or group meet.
> * If it is group meet, render the second screen and provide a dropdown to select 15, 30, 60 min respectively.

sure go for it, tho @JeroenReumkens is currently refactoring the entire booking page into a standalone app, which means your PR may not be merged but used in his PR

**Comment by PeerRich** [comment]
@hussamkhatib wanna work on this?

**Comment by hussamkhatib** [comment]
sure

**Comment by hussamkhatib** [comment]
Hey @PeerRich,
Could you reshare the loom video if possibe.
