### ISSUE TITLE
[CAL-586] Admin Onboarding: Choose License

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#5998]
to replace "LICENSE_CONSTENT" and "LICENSE_KEY" in .env, we should move this into the database.

we should add a "Choose License" step to the admin onboarding (when User = 0)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d70698fa-81e9-465f-8313-0c951e6eb5d6/5914160b-0b9a-4368-b395-06257ade46c8)

next step if "enterprise is selected"

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e851c981-6bba-4b15-94bf-01785f080e2f/80a31c0e-acce-4483-b05e-225fc8789dc7)

disabled if input is empty:

![CleanShot 2022-12-13 at 12 53 57](https://user-images.githubusercontent.com/8019099/207311040-c305e0fe-c2fd-4ca2-b410-b1686533bcdc.jpg)

[https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1426%3A116568](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1426%3A116568)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-586](https://linear.app/calcom/issue/CAL-586/admin-onboarding-choose-license)</sub>

**Comment by zomars** [comment]
This need some prep-work discussed here: #6014

**Comment by PeerRich** [comment]
lets also move all the whitelabel settings *after* selecting "/ee/ license"

**Comment by leog** [comment]
@PeerRich @Jaibles I'm not sure what the "Do later" button does, it's just skipping the step? How would the user come back? I don't think we have any link to the setup in the app settings.

**Comment by Jaibles** [comment]
Remove it please @leog :)
