### ISSUE TITLE
[CAL-591] Mark days/weeks as unavailable instead of showing error message about booking limits

### ISSUE THREAD

**Issue by caseyg** [calcom/cal.com#6002]
### Is your proposal related to a problem?

When users try to book or reschedule an event, they are shown days and weeks that have already reached their booking limits, then given a (confusing) error message

<img width="369" alt="Screenshot 2022-12-13 at 8 06 00 AM" src="https://user-images.githubusercontent.com/462020/207326628-c75cff6c-54a5-4b88-b374-b5e39a47be52.png">

The next step is to return to the previous screen and find a new date, but the only options available are "Cancel" and "Re/Schedule" -- neither of which are intuitive.

### Describe the solution you'd like

A better user experience would be to mark days/weeks where booking limits have been reached as unavailable on the date selector, so that users cannot enter dates that have hit their limits and attempt to book unavailable slots, ending up with a confusing error message and unclear next steps.

### Describe alternatives you've considered

A short term workaround could be to improve the copy of the error message: 

> "Could not (re)schedule the meeting. Booking Limit for this event type has been reached"

To include instructions on what to do next:

> "Could not (re)schedule the meeting. Booking Limit for this event type has been reached. Please hit Cancel to return to the previous screen and find an alternative date."

### Additional context

Related issue: #5941 

<sub>[CAL-591](https://linear.app/calcom/issue/CAL-591/mark-daysweeks-as-unavailable-instead-of-showing-error-message-about)</sub>

**Comment by PeerRich** [comment]
we're reworking a lot of parts of the booking experience and our goal is to get rid of all errors *after* booking

**Comment by emrysal** [comment]
Fixed by #6119
