### ISSUE TITLE
[CAL-587] Display of Team URL in the settings page is wrong

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6006]
Current:

![CleanShot 2022-12-13 at 15.20.02@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/383ac458-748c-4e05-b8d2-b1a7fb5b5961/e010b84c-5d31-49da-a95d-0251db9f3be9)

The URL does not have "app" in it. The URL should be

[https://cal.com/team/cal](https://cal.com/team/cal)

Also check if this issue exists in onboarding.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-587](https://linear.app/calcom/issue/CAL-587/display-of-team-url-in-the-settings-page-is-wrong)</sub>

**Comment by Udit-takkar** [comment]
i think i fixed it somewhere . let me check again
