### ISSUE TITLE
[CAL-593] Validate CALENDSO_ENCRYPTION_KEY its the right format AES256 and 32 bytes

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#6028]
One self hosted user had problem when encrypting their api_keys for sendgrid. The error didn't match with what currently was happen underneath. We should validate on server init.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-593](https://linear.app/calcom/issue/CAL-593/validate-calendso-encryption-key-its-the-right-format-aes256-and-32)</sub>

**Comment by PeerRich** [comment]
we should also rename this to CAL_ENCRYPTION_KEY at some point
