### ISSUE TITLE
[CAL-595] Production Build failing when using Node v18, but works fine for Dev build

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#6031]
Currently, production build is failing when using Node v18 while the dev build works just fine. With node v16, production build works again. Tested locally

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-595](https://linear.app/calcom/issue/CAL-595/production-build-failing-when-using-node-v18-but-works-fine-for-dev)</sub>

**Comment by PeerRich** [comment]
@alishaz-polymath still?
