### ISSUE TITLE
Limit future bookings by days in the future not working

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6033]
### Issue Summary

I have limited my event types to be schedulable no more than 14 days in advance - [cal.com/chip](https://cal.com/chip)
It seems you are able to book events 21 days in advance.

### Steps to Reproduce

1. Set "Limit future bookings" to 14 days & save:
![firefox_2022-12-15_10-55-31](https://user-images.githubusercontent.com/3164166/207841639-2ea053fb-ca1f-4ac3-a111-d3f1ff37b0ec.png)

2. Observe the available slots via the public link:
![firefox_2022-12-15_10-58-57](https://user-images.githubusercontent.com/3164166/207842395-297dccde-bbde-4b3f-9eeb-d1ff83ba0e7a.png)
![firefox_2022-12-15_10-58-30](https://user-images.githubusercontent.com/3164166/207842322-0c4fe549-7c65-41fe-99b7-b2d0e8d00107.png)

3. Attempt a booking beyond the threshold limit and observe a successful booking:
![firefox_2022-12-15_10-57-46](https://user-images.githubusercontent.com/3164166/207842142-b38d10d6-8bd4-4152-9f41-1cbfd0707da2.png)

**Comment by ChipWolf** [comment]
I see the phrase "business days" used in the limits section, however, my working days in cal.com are configured for all days to be business days.
So, perhaps this is semi-intentional, but unexpected behaviour for the user in that cal.com defines business days statically as Mon-Fri?

**Comment by ChipWolf** [comment]
Flipping the selector from `business days` to `calendar days` leads to expected behaviour.

![firefox_2022-12-15_11-05-05](https://user-images.githubusercontent.com/3164166/207843757-669087e3-a351-4368-8f66-3ec56765c262.png)


I will leave this issue open as I believe `business days` means something different to other groups of people and it should probably represent the schedule attached to the event type.

**Comment by ChipWolf** [comment]
I will leave this issue open as `business days` is loosely defined; especially given many work weekends only, and others are moving to 4-day working patterns, among other use-cases.

Perhaps a clear `(Mon-Fri)` should be appended to the `business days` option and a third `available/working/schedulable days` option which accounts for variants on the working week could be added.

![firefox_2022-12-15_11-11-19](https://user-images.githubusercontent.com/3164166/207844755-5b5dd684-b796-4577-941a-451658c6a45d.png)

**Comment by ChipWolf** [comment]
Alternatively for better UX; perhaps the selector should allow you to choose between `days`, `specific days` [which would open up a selector to choose the days of the week], or `availability days` as above.

![firefox_2022-12-15_11-21-52](https://user-images.githubusercontent.com/3164166/207846847-a6d90ad1-3e7f-4117-92d8-f66bec2abbdf.png)

**Comment by PeerRich** [comment]
pretty sure this has been addressed by now
