### ISSUE TITLE
[CAL-597] force lowercase for links

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6041]
this used to work

[cal.com/Peer](http://cal.com/Peer) is 404 whereas [cal.com/peer](http://cal.com/peer) works

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6aeb4745-513f-4490-99b6-ab8e9060a2b9/666efb5d-1413-4803-bce4-bb314c24deb9)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-597](https://linear.app/calcom/issue/CAL-597/force-lowercase-for-links)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar can you take this up? you may need to look into calcom/website signup.tsx

**Comment by PeerRich** [comment]
or someone else

**Comment by hussamkhatib** [comment]
Hey, I can look into this.

**Comment by hussamkhatib** [comment]
I Think it is intentional @PeerRich
https://github.com/calcom/cal.com/commit/2c7fcbcf51d1ff951ae4a72a4a249e3a62b97700

**Comment by Udit-takkar** [comment]
@PeerRich  zomars is already working on this.

**Comment by Udit-takkar** [comment]
fixed here https://github.com/calcom/cal.com/commit/2fe9c782d4695a9a654d8c37a6c1989472dbe9e9
