### ISSUE TITLE
[CAL-598] Date overrides aren't shown in troubleshooter if there are more than 1 availabilities and date override is used in second one.

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6042]
Date overrides aren't shown in troubleshooter if there are more than 1 availabilities and date override is used in second one. 

This seems to be due to the reason that `getUserAvailability` picks the first availability/schedule(because eventTypeId isn't provided)
If a default schedule is set, I think that's used.

<img width="1031" alt="Screenshot 2022-12-15 at 1 15 31 PM" src="https://user-images.githubusercontent.com/1780212/207802062-36afb070-1705-4cc8-a764-54731dd152f6.png">

This seems to be a bug in troubleshooter flow and not specific to Date overrides.
cc @emrysal 

Also, I am confused as to if troubleshooter  is expected to troubleshoot one schedule or all the schedules of user in general.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/6027#discussion_r1049309145_
      

<sub>[CAL-598](https://linear.app/calcom/issue/CAL-598/date-overrides-arent-shown-in-troubleshooter-if-there-are-more-than-1)</sub>

**Comment by PeerRich** [comment]
there are more troubleshooter issues open #5824
