### ISSUE TITLE
[CAL-662] Recurring No User Found

### ISSUE THREAD

**Issue by mrkirchner** [calcom/cal.com#6047]
### Issue Summary

When scheduling recurring meetings, it appears the ui doesn't check if all recurring events are available.  So upon submitting confirming your apt you get a no user found error.  Looking into reason why it fails it appears because one occurring event happens on an already schedule event. 

- Alert message does not convey why it failed to book well
- Would be better if picking date was a bit smarter about what is available for recurring

<img width="233" alt="Screen Shot 2022-12-15 at 8 08 59 PM" src="https://user-images.githubusercontent.com/13805753/208013494-13ed363a-2e8b-461b-ac70-9ca2e63a6987.png">

### Steps to Reproduce

1. Setup an recurring event that happens more than 4 or so times.  We have one that is 12x
2. Ensure person your doing book has 1 of days in future busy
3. Schedule event so that it overlaps on the busy future date
4. Observe error

### Technical details

- Running Self hosting instance

Log from server `2-12-16 02:58:45] @calcom/web:start: calendarBusyTimes==>>> [
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:   {
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     start: '2023-11-07T00:00:00.000Z',
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     end: '2023-11-07T00:45:00.000Z',
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     source: undefined,
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     title: undefined
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:   }
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start: ]
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start: Error: No available users found.
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at ensureAvailableUsers (/calcom/apps/web/.next/server/pages/api/book/event.js:897:15)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at runMicrotasks (<anonymous>)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:988:32)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:596:21)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async /calcom/apps/web/.next/server/chunks/2157.js:58:28
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async Object.apiResolver (/calcom/node_modules/next/dist/server/api-utils/node.js:366:9)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async NextNodeServer.runApi (/calcom/node_modules/next/dist/server/next-server.js:481:9)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async Object.fn (/calcom/node_modules/next/dist/server/next-server.js:735:37)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async Router.execute (/calcom/node_modules/next/dist/server/router.js:247:36)
[docker-calcom] [2022-12-16 02:58:45] @calcom/web:start:     at async NextNodeServer.run (/calcom/node_modu`

<sub>[CAL-662](https://linear.app/calcom/issue/CAL-662/recurring-no-user-found)</sub>

**Comment by mrkirchner** [comment]
After more testing it seems to happen during daylight savings time.

**Comment by PeerRich** [comment]
can you test this on app.cal.com so we can make sure its not a self-hosting issue?

**Comment by PeerRich** [comment]
pretty sure this has been fixed. please reopen a new issue if now
