### ISSUE TITLE
[CAL-601] Translation issue on console

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#6048]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fffb7b54-dacf-4821-84f7-47a18358cd2b/933366f5-9800-47fe-a575-7d4ff7ea9b29)

notice "current_step_of_total" at the bottom

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-601](https://linear.app/calcom/issue/CAL-601/translation-issue-on-console)</sub>

**Comment by Udit-takkar** [comment]
@leog you fixed this one. right ?

**Comment by PeerRich** [comment]
@zomars

**Comment by PeerRich** [comment]
i thought we had a solution for this 🤔

**Comment by zomars** [comment]
We did. It may been reverted or mismerged

**Comment by zomars** [comment]
Odd that locally it works fine tho: 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/3504472/211161260-ea563f75-64b0-4f4f-bf6d-dafe4a8d60fb.png">

Will redeploy without cache and see what happens

**Comment by zomars** [comment]
Redeployment worked

<img width="762" alt="image" src="https://user-images.githubusercontent.com/3504472/211162043-0e42f048-6f0c-4f54-baf1-cc83ae3eb99f.png">

**Comment by PeerRich** [comment]
nice!
