### ISSUE TITLE
[CAL-602] Remove Underlines between Words

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6049]
When creating a new team, there are underlines between the words on the setup flow. Will include screenshots

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-602](https://linear.app/calcom/issue/CAL-602/remove-underlines-between-words)</sub>

**Comment by shirazdole** [comment]
![D63DFCDD-9BAA-4C47-8DEB-ABE7E63E922A.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d77cb069-2072-4bd1-bf80-ee4523981cd6/9198f926-37bb-4c59-94ce-8a483a65bd5b)

![4D34AD15-F13A-4E7D-832C-D3AFCDEB9512.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8b70b2e3-9fa2-4b97-ba60-6a8771520569/dd9b6b55-e384-467f-ad77-0bf437478afe)

**Comment by PeerRich** [comment]
thats a different issue. it's not taking the i18n strings. could be an error in common.json

**Comment by PeerRich** [comment]
![CleanShot 2022-12-16 at 11 10 55](https://user-images.githubusercontent.com/8019099/208075498-14966d60-a584-4c2a-8b72-b32016ff3f61.jpg)
can't reproduce

**Comment by PeerRich** [comment]
can you try again and hard reload your browser? COMMAND + R

**Comment by shirazdole** [comment]
@PeerRich this was during a demo with a customer/friend who was creating a team. I'll ask her to go through the flow again and let me know what they see, but it's night now for them

**Comment by sean-brydon** [comment]
@shirazdole was this running locally or on prod? Sometimes locally translations dont load - never experienced this on prod tho

**Comment by shirazdole** [comment]
@sean-brydon production — it was during an onboarding call with a customer

**Comment by shirazdole** [comment]
The underline marks are gone
