### ISSUE TITLE
[CAL-603] Date overrides need some love in mobile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6050]
instead it should be a full width row on mobile

Created via Threads. See full discussion: [https://threads.com/34438575187](https://threads.com/34438575187)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-603](https://linear.app/calcom/issue/CAL-603/date-overrides-need-some-love-in-mobile)</sub>

**Comment by Udit-takkar** [comment]
@PeerRich any design?

**Comment by PeerRich** [comment]
> @PeerRich any design?

I have a pretty good idea, lemme take this issue ok?

**Comment by PeerRich** [comment]
@emrysal fixed it already
