### ISSUE TITLE
Multi-day availability hours and event bookings.

### ISSUE THREAD

**Issue by 12ian34** [calcom/cal.com#6054]
### Is your proposal related to a problem?

- When using Availability hours, the last available time in the 'end time selector' is 23:45.
- This means that it isn't possible for events to be booked than run past 23:45.
- I would like to be able to have events booked across midnight.
- Availability hours are currently set per each single day, via specific time slot periods, each with start and end times, in "time periods" that can only start after the previously set "time period" has finished. This is quite annoying, because it isn't a great representation of "free time".

![image](https://user-images.githubusercontent.com/9979944/208084215-9aa2b137-0fb9-421d-84fd-2ab5a16b128c.png)

### Describe the solution you'd like

Events should be able to be booked across midnight.
I think allowing the Availability Hours to be set a different way would help fix this problem.
Perhaps by showing the whole week graphically, allowing people to "colour in" their free time AND having an option that says "allow multi-day events" or "allow events to cross midnight"

### Describe alternatives you've considered

I've tried using the "Add new time slot" button to counteract this problem, but it still won't allow events to be booked across midnight.

### Additional context

n/a

**Comment by PeerRich** [comment]
huh interesting. we'd need to investigate how to do this best

**Comment by emrysal** [comment]
@12ian34 I believe this may be fixed by https://github.com/calcom/cal.com/pull/6137

**Comment by 12ian34** [comment]
Interesting! Thanks @emrysal for following up. Does the fix then allow for overnight bookings? I'd guess that it technically wouldn't since there is an unaccounted gap between 11:59:00 and 00:00:00 ?

**Comment by emrysal** [comment]
The end time isn't used for the most part while scheduling, it's mainly based on start times - but the lack of the 23:59 option prevented the 23:45 option from being selected (23:30 being the latest possible to select). A complicated story short, in theory an overnight booking should now work

**Comment by 12ian34** [comment]
Unfortunately @emrysal it didn't work :(
