### ISSUE TITLE
[CAL-609] refactor: replace react-feater with import { Icon } from "@calcom/ui";

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6064]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/495582b5-f513-4619-9196-742096eadf18/dff23ff8-c7fc-4d20-82af-6bdf09649d64)

instead of

`import { Check } from "react-feather";`

we should:

`import { Icon } from "@calcom/ui";`

and use:

`<Icon.FiCheck />`

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-609](https://linear.app/calcom/issue/CAL-609/refactor-replace-react-feater-with-import-icon-from-calcomui)</sub>

**Comment by Ravina-Deogadkar** [comment]
Can I work on this task?

**Comment by mehranShG** [comment]
Hello, Sorry i didnt completely undrestand. you wanted to only change Check or others too,i only changed Check.

**Comment by PeerRich** [comment]
no "Check" was just an example, all of the imports of " from "react-feather";

**Comment by PeerRich** [comment]
fixed in https://github.com/calcom/cal.com/pull/6090

**Comment by PeerRich** [comment]
thank you @mehranShG
