### ISSUE TITLE
Google Calendar: Access token expired or revoked

### ISSUE THREAD

**Issue by HendrikRoth** [calcom/cal.com#6076]
### Issue Summary

The google calendar access token expires after about 1 week.

### Steps to Reproduce

1. Install the google calendar app
2. Authorize
3. After about 1 week the access token is expired

**Comment by HendrikRoth** [comment]
Found the solution for this case: My oauth application was in "testing" state. This limits to 7 days.

**Comment by gretzke** [comment]
My `Production status` is "In production" in the OAuth consent screen, however I'm still seeing these issues.
