### ISSUE TITLE
[CAL-612] Toggle to hide “book a team member instead” on public team events type page

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6078]
![3B29C024-9A8A-433C-BFDB-9A8889E1EBF3.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b0bc2d29-0461-4155-908e-307648b17c4d/89c2e2c9-1876-474c-aa9a-6f80462581aa)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-612](https://linear.app/calcom/issue/CAL-612/toggle-to-hide-book-a-team-member-instead-on-public-team-events-type)</sub>

**Comment by shirazdole** [comment]
chatted with Bailey about this 🙏🏽

**Comment by Udit-takkar** [comment]
fixed here [https://github.com/calcom/cal.com/pull/6294](https://github.com/calcom/cal.com/pull/6294)
