### ISSUE TITLE
[CAL-613] Individual event type appearance settings to team event type settings

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6079]
Have the same appearance options like changing the color of the event page from black to white as individual events have on collective and round robin event types

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-613](https://linear.app/calcom/issue/CAL-613/individual-event-type-appearance-settings-to-team-event-type-settings)</sub>

**Comment by PeerRich** [comment]
agree, right now the theme of team event-types cant be changed

**Comment by PeerRich** [comment]
@G3root wanna work on this?

**Comment by PeerRich** [comment]
add this:
![CleanShot 2023-01-24 at 20 16 11@2x](https://user-images.githubusercontent.com/8019099/214387204-0ebff3e0-63ad-4ea3-ae30-0de66a2c6ee6.jpg)

to team > appearances 

![CleanShot 2023-01-24 at 20 16 41@2x](https://user-images.githubusercontent.com/8019099/214387317-3cfea746-abf6-4e8a-9069-e846967bc672.jpg)
