### ISSUE TITLE
[CAL-1073] Incorrect calendar conflict checking when using flexible durations

### ISSUE THREAD

**Issue by dinoboy197** [calcom/cal.com#6083]
### Issue Summary

(I was directed by customer support to file a bug ticket here).

When using flexible duration events, calendar conflicts are not checked correctly for long durations selected by the booker.

### Steps to Reproduce

My timezone and booker's timezone are UTC-10 (Pacific/Honolulu).

1. Create future calendar entries in connected Google Calendar with three hour gap: 8am–10am and 1pm–4pm. For example, I have created two calendar events with a three hour gap between them on December 20th:

![image](https://user-images.githubusercontent.com/631178/208257433-7cc5ceff-6a42-4d05-ac35-67766550e171.png)

2. Create cal.com event with a variety of flexible schedules for the booker to choose (30 mins, 60 minutes, 90 minutes, 180 minutes), with 30 minutes before and after each calendar event of mandatory buffer, and set to 15 minute intervals. (The event that I've created to replicate this issue is at https://app.cal.com/event-types/156829). See how this event is configured:

![image](https://user-images.githubusercontent.com/631178/208260748-cd28ec94-df77-4c98-b417-90bfb57b80be.png)

![image](https://user-images.githubusercontent.com/631178/208260795-6762c513-390f-441e-b7b4-2a56ef910b4e.png)

3. Access booking page for this event using a different browser profile (not connected to that Google Calendar or cal.com account).
4. Select the day of the calendar events (in my case, December 20th).
5. Select individual durations on the page, and verify the start times available on that day for each duration. These should respect the 15 minute scheduling timelock and 30-minute buffer before and after existing calendar events. Here are the meeting start times that should appear between 7:00am and 1pm:
* 30-minute meeting: 7:00am, 10:30 am, 10:45am, 11:00am, 11:15am, 11:30am, 11:45am, 12:00pm
* 60-minute meeting: 10:30 am, 10:45am, 11:00am, 11:15am, 11:30am
* 90-minute meeting: 10:30 am, 10:45am, 11:00am
* 180-minute meeting: <none>

Instead, the following times are shown as available in the cal.com UI:
* 30-minute meeting: 7:00am, 7:15am, 10:45am, 11:00am, 11:15am, 11:30am, 11:45am, 12:00pm, 12:15pm
* 60-minute meeting: 7:00am, 7:15am, 10:45am, 11:00am, 11:15am, 11:30am, 11:45am, 12:00pm, 12:15pm
* 90-minute meeting: 7:00am, 7:15am, 10:45am, 11:00am, 11:15am, 11:30am, 11:45am, 12:00pm, 12:15pm
* 180-minute meeting: 7:00am, 7:15am, 10:45am, 11:00am, 11:15am, 11:30am, 11:45am, 12:00pm, 12:15pm

Here are screenshots:

30-minute duration selected for Dec 20th:
![image](https://user-images.githubusercontent.com/631178/208261982-a391f16b-0353-4b67-9c0a-59cae6251495.png)

60-minute duration selected for Dec 20th:
![image](https://user-images.githubusercontent.com/631178/208262064-1cb01777-350f-4a55-aa18-c5e14c5f503e.png)

90-minute duration selected for Dec 20th:
![image](https://user-images.githubusercontent.com/631178/208262172-1fe8f718-2e72-48c9-8493-0e899712178f.png)

180-minute duration selected for Dec 20th:
![image](https://user-images.githubusercontent.com/631178/208261336-0d1d26ae-d137-4ffa-bfa9-5d5ce2d1f59a.png)

### Technical details

- Browser: Brave, [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)](https://brave.com/latest/)
- OS: Ubuntu Linux, 18.04.6 LTS

<sub>[CAL-1073](https://linear.app/calcom/issue/CAL-1073/incorrect-calendar-conflict-checking-when-using-flexible-durations)</sub>

**Comment by PeerRich** [comment]
hey @leog  you worked on flexible duration, can you check?

**Comment by siferati** [comment]
Any updates on this? I'm having the same problem, which means the flexible duration feature is basically useless since it will lead to overlapping meetings.

**Comment by leog** [comment]
@siferati I will take a look, there might be an issue with caching, which was reworked recently. Would you mind reconfirming this is still an issue? Thanks.

**Comment by siferati** [comment]
Yes, still an issue. It doesn't happen with fixed duration events, only with the flexible duration ones

**Comment by max-mykhailenko** [comment]
I have similar problem when combine somehow
* buffer before
* buffer after
* time slot intervals

I have less booking slots inside the interface compared to the real availability in the calendar.

**Comment by siferati** [comment]
@PeerRich Can we get some info on why this issue was closed please? I don't see a PR linked to this. Has it been fixed already?
