### ISSUE TITLE
[CAL-616] Time zone and encoding issues on direct link accept/reject page

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#6086]
### Issue Summary

Time zone and encoding issues on direct link accept/reject page as reported by @PeerRich and @hariombalhara.

### Steps to Reproduce

1. Book a request confirmation booking
2. Get the Accept/Reject email as organizer
3. Click on Accept or Reject, time zone will not be shown correctly, and if used through Sendgrid (PROD) there might be an error due to "Array must contain at most 4 element(s) accessing"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-616](https://linear.app/calcom/issue/CAL-616/time-zone-and-encoding-issues-on-direct-link-acceptreject-page)</sub>

**Comment by zomars** [comment]
How does these encoding issues looks like?

**Comment by PeerRich** [comment]
it only happens if sendgrid link tracking is active, which is not right now

**Comment by leog** [comment]
> How does these encoding issues looks like?

@zomars Sendgrid redirection reverses any encodeURIComponent done in the hash added in the last part of a direct link, and those hashed may have slashes which would add an extra part in the URL which is not expected
