### ISSUE TITLE
German Translation Issue

### ISSUE THREAD

**Issue by fiskare** [calcom/cal.com#6087]
### Issue Summary

The translation in the Bookings menu is partially incorrect:

Unbestätigt:
Es gibt noch keine unbestätigt Buchungen -> Es gibt noch keine unbestätigten Buchungen
Sie haben keine unbestätigt Buchungen. -> Sie haben keine unbestätigten Buchungen.

Wiederkehrend:
Es gibt noch keine wiederkehrend Buchungen -> Es gibt noch keine wiederkehrenden Buchungen
Sie haben keine wiederkehrend Buchungen.  -> Sie haben keine wiederkehrenden Buchungen. 

Vergangen:
Es gibt noch keine vergangen Buchungen -> Es gibt noch keine vergangenen Buchungen
Sie haben keine vergangen Buchungen. -> Sie haben keine vergangenen Buchungen.

<img width="516" alt="Screenshot 2022-12-17 at 23 42 13" src="https://user-images.githubusercontent.com/4365328/208268874-4800bc61-bf55-43b2-94f5-aa440a559f6b.png">
<img width="490" alt="Screenshot 2022-12-17 at 23 43 39" src="https://user-images.githubusercontent.com/4365328/208268876-4b8a7499-1491-43b0-b656-ee061118748d.png">
<img width="527" alt="Screenshot 2022-12-17 at 23 43 01" src="https://user-images.githubusercontent.com/4365328/208268877-82a7d166-4a71-41e3-b847-8c14cdb27c4f.png">

**Comment by PeerRich** [comment]
ah this sucks. the way this was built is this:

"no_status_bookings_yet": "Es gibt noch keine {{status}} Buchungen",

which means we need to refactor the entire string

**Comment by PeerRich** [comment]
fixed, the only "downside" is that now the sidebar has pluralised strings, but I think its fine


![CleanShot 2022-12-18 at 10 51 34](https://user-images.githubusercontent.com/8019099/208291770-7286f550-3232-43e5-b4dc-3b73dbe72e19.jpg)
