### ISSUE TITLE
[CAL-622] /event-types - event type list items UI discrepencies

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6105]
![CleanShot 2022-12-19 at 13.50.52@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8ea952ae-d04a-4545-a3d0-c1e4acb97314/9058c1f2-2d4d-4e3b-89da-3fb2d19f3511)

[Details in Figma](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=20%3A14593&t=GylQRxLIVeItCckQ-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-622](https://linear.app/calcom/issue/CAL-622/event-types-event-type-list-items-ui-discrepencies)</sub>

**Comment by PeerRich** [comment]
taking this
