### ISSUE TITLE
[CAL-624] /teams /public profile - weird borders around event types

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6107]
Appears to be a double border issue and the border radius around all of the list items is wrong.

![CleanShot 2022-12-19 at 13.15.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c99abb8c-e378-45cd-8e23-5b0458c3953b/b5f15fc6-04f6-42da-b248-849e0e00d5eb)

Should match the appearance on single persons booking page like:

![CleanShot 2022-12-19 at 13.15.11@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e0bb3f20-b269-43be-a9d5-b1bb0bb9e84b/0ecb0695-3bcf-4122-805d-2b670b36d052)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-624](https://linear.app/calcom/issue/CAL-624/teams-public-profile-weird-borders-around-event-types)</sub>

**Comment by PeerRich** [comment]
@JeroenReumkens can you investigate this since you are moving this into its own app?

**Comment by JeroenReumkens** [comment]
@PeerRich @Jaibles  already did a quick improvement on the current version in #6141 . Couldn't stand this.. 😬  Will improve further in the new version indeed.
