### ISSUE TITLE
[CAL-632] Admin Managed Event Template for the Organization.

### ISSUE THREAD

**Issue by kg4201** [calcom/cal.com#6116]
### Is your proposal related to a problem?

Looking to set up Managed Events for Organizations. Essentially a template that the admin creates which will become available to everyone in the Organization. Admin can lock certain fields so that they cannot be edited. 

Calendly offers a similar functionality - "Managed Events"

### Describe the solution you'd like

Use case: When a new member is added to the organization, certain managed event is available. Template should be managed on the team level, the Admin has the ability to push updates to all the other team members in that organization.

On an organization level: 
- Admin should be able to edit and lock the title,
- Admin should be able to edit and lock the url,
- Admin should be able to edit and lock the duration
-  Admin should be able to edit and lock the location (ie google meet)
- Admin should be able to edit and lock the duration
- Any booking made on this event should be able to fire web hooks 
 
### Describe alternatives you've considered

Offered by calendly.

### Additional context

this is a critical feature needed for my org.

<sub>[CAL-632](https://linear.app/calcom/issue/CAL-632/admin-managed-event-template-for-the-organization)</sub>

**Comment by PeerRich** [comment]
yes we are working on this

**Comment by PeerRich** [comment]
cc @Jaibles

**Comment by PeerRich** [comment]
just wanted to inform this is in the making!

**Comment by shirazdole** [comment]
Had another potential customer ask for this!

**Comment by RyanBetteridge** [comment]
A good feature to add is allowing admin to choose the preferred location for the managed event (e.i. Google Meet) and lock it, and if left unlocked - each assigned member can then override location with their preferred location (e.g. Zoom)

**Comment by Jaibles** [comment]
> A good feature to add is allowing admin to choose the preferred location for the managed event (e.i. Google Meet) and lock it, and if left unlocked - each assigned member can then override location with their preferred location (e.g. Zoom)

This is how we have it designed 👍. Will be ready in 3.0 release very soon!
