### ISSUE TITLE
[CAL-633] /embed - Call duration is not set to the default

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6127]
When I go to book a call in the embed, it does not preselect the default duration

![CleanShot 2022-12-20 at 16.02.16@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/58aea156-fe38-479f-b68d-411a6ab20695/e9310f4d-8426-4583-bb1c-32a91d63c35a)

I then end up with "undefined minutes"

![CleanShot 2022-12-20 at 16.01.11@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/95cef862-467c-485a-bff2-38bfdc014d83/a8d4c1c9-9e1c-467a-b983-94ac70d1605a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-633](https://linear.app/calcom/issue/CAL-633/embed-call-duration-is-not-set-to-the-default)</sub>

**Comment by hariombalhara** [comment]
That seems like a bug without embed as well. @leog could you check this please ?

**Comment by Jaibles** [comment]
It seemed to choose the default time for me on my regular link

![CleanShot 2022-12-20 at 16.20.10@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b9add736-f67d-4d11-bfac-9e7d7acf9fbc/69091820-5554-483c-a9ba-79db250b8bde)

**Comment by leog** [comment]
Can't seem to repro this one @Jaibles. Could you point out how you bumped into it?
Using the [CodeSandbox embed example](https://codesandbox.io/s/embed-popup-on-click-of-an-existing-element-demo-react-forked-tv9uxi?file=/src/App.js) to bring up Cal clicking on a button, I was able to select the multiple duration event type and default duration got selected by default: 
<kbd><img width="1189" alt="image" src="https://user-images.githubusercontent.com/467258/208740911-41b212a4-6dc3-4b9c-b1fe-301edae5db1a.png"></kbd>

**Comment by Jaibles** [comment]
@leog click book a call on [here](https://ciaran.design)
