### ISSUE TITLE
[CAL-635] /bookings: past events should not be editable or cancellable 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6132]
![CleanShot 2022-12-20 at 22 42 58](https://user-images.githubusercontent.com/8019099/208772613-d80edd86-7106-4230-8629-241f25f8650f.jpg)

<sub>[CAL-635](https://linear.app/calcom/issue/CAL-635/bookings-past-events-should-not-be-editable-or-cancellable)</sub>

**Comment by mocherfaoui** [comment]
this was introduced here #3641 as a feature request, is it going to be removed entirely or reworked?

**Comment by PeerRich** [comment]
ok but we need to remove "cancel" for sure

**Comment by Jaibles** [comment]
@mocherfaoui 
- Yes we should still allow people to reschedule a request for a booking that was not accepted. 
- I think we could change "Cancel" to a delete option also? The implication being that we're not going to trigger emails etc. we're just going to remove it from bookings.

**Comment by mocherfaoui** [comment]
@Jaibles 
this means that "Cancel" and "Edit" dropdown should be both removed?
