### ISSUE TITLE
[CAL-615] Changing the time zone on a booking page makes the date override available available.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6136]
Changing the time zone on a booking page makes the day available.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-615](https://linear.app/calcom/issue/CAL-615/changing-the-time-zone-on-a-booking-page-makes-the-date-override)</sub>

**Comment by Guray00** [comment]
I have not changed the timezone, but since today in GMT+1 the data override is not working correctly, showing unavailable days as available. I have not done any edit, after the problem i tried updating the informations with no luck.
