### ISSUE TITLE
[CAL-914] Booking of different time duration than the settings should not be possible

### ISSUE THREAD

**Issue by odicho** [calcom/cal.com#6155]
### Issue Summary

You can make modifications to the URL parameters and essentially override the calendar owner's settings. For example, if I only want others to be able to schedule 10 minutes meetings every 10 minutes, I don't want them to be able to just change a URL parameter and request a 1 hour meeting and block out my schedule like that.

### Steps to Reproduce

1. The duration in settings is set to 10 minutes:
![image](https://user-images.githubusercontent.com/53154523/209111152-94a2d832-29f7-45cc-ae53-c14cd0d4c261.png)

2. Go to my link and add a URL param of duration, for example:
https://cal.com/amanuel/30min?duration=15

3. The UI actually lists a slot every 15 minutes and 15 minutes in length 
![image](https://user-images.githubusercontent.com/53154523/209111381-eec2bb3e-e1f9-4c1b-9e06-e4905eb42f79.png)

4. Booking is actually confirmed for 15 minutes:
![image](https://user-images.githubusercontent.com/53154523/209111579-f0a21e26-ea22-4f41-87e3-84aaaa4f1313.png)

5. It also shows up in my dashboard under upcoming bookings:
![image](https://user-images.githubusercontent.com/53154523/209111742-7fdfb4fa-c4f6-4025-bd40-de1d8789d1be.png)

6. This can be reproduced using any number for the duration.

<sub>[CAL-914](https://linear.app/calcom/issue/CAL-914/booking-of-different-time-duration-than-the-settings-should-not-be)</sub>

**Comment by PeerRich** [comment]
@leog can you investigate this after License Onboarding?
