### ISSUE TITLE
https://cal.com - Antivirus complains

### ISSUE THREAD

**Issue by Monpoke** [calcom/cal.com#6159]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Hello, I found your project through the list of SelfHosted applications. When I tried to access your website, my antivirus blocked it. It appears that you have been flagged as a phishing site. I just wanted to let you know!
https://www.virustotal.com/gui/url/cf27f8b946b450f1308736ba8f94f4a92899ee2cd7fa12abbc81de2d51dc334f

### Steps to Reproduce
1. Browse to https://cal.com
2. Antivirus complains

### Technical details
- Avast 22.12.6044

**Comment by PeerRich** [comment]
thank you, will reach out to that spam filter to report a false positive!

**Comment by PeerRich** [comment]
resolved. thank you for flagging 

![CleanShot 2022-12-22 at 21 33 59](https://user-images.githubusercontent.com/8019099/209221274-5d9ea251-a43f-4f6e-bf90-225464e4ebcc.jpg)
