### ISSUE TITLE
Required additional inputs prevent form from being submitted

### ISSUE THREAD

**Issue by LilaRest** [calcom/cal.com#6160]
### Issue Summary
When adding a "required" additional radio input to one of my events, even if the user has selected one of the options, the form cannot be submitted because of a missing required input.

### Steps to Reproduce
1. Create an event
2. In Advanced, add an additional radio input and set it to "required"
3. Save and try to book that event from the attendee perspective.

### Technical details
Tried on Firefox Flatpak for Linux and Fennec for Android.

**Comment by PeerRich** [comment]
@LilaRest this has been fixed. should go live in the next update next week
