### ISSUE TITLE
[CAL-641] templated event-types

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6164]
admin controlled events for team members. you change it in one template and it populates throughout the rest of people's event-types

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-641](https://linear.app/calcom/issue/CAL-641/templated-event-types)</sub>

**Comment by SKG2310** [comment]
looks like a subset of functionality proposed in #7956

**Comment by PeerRich** [comment]
continuing in https://github.com/calcom/cal.com/issues/7956
