### ISSUE TITLE
Clearer UX when allowing booker to select duration

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6165]
### Is your proposal related to a problem?

I've had feedback from users of my calendar that the UX on event types that have been set to allow the booker to choose an event length is not clear and easily missed.

### Describe the solution you'd like

I'd like the duration selection to be mandatory/before they are able to select a time to make it clearer.

### Describe alternatives you've considered

I have an additional mandatory checkbox question asking the user if they selected the duration on the previous page.

**Comment by PeerRich** [comment]
do you have a UX recommendation for this?

**Comment by ChipWolf** [comment]
> do you have a UX recommendation for this?

Couple of ideas:

- Preferred: a new screen prior to the date-time selector allowing the user to select a duration before being distracted by the calendar _(presumably more economical in terms of API requests also)_

- Workaround: leave the UI as-is, but block interactions to the date-time selector with a haptic indication on the duration button cluster and/or a warning modal

As a positive side-effect to either option - they would support removing the hard requirement for a default duration.

Unfortunately, without new UI, I don't have a good idea for how a default duration would work with the second option other than a [potentially clunky] warning on the confirmation screen.

I'd assume the majority of use-cases for custom duration wouldn't benefit from a default duration.

**Comment by ChipWolf** [comment]
@PeerRich 

**Option 1** _(preferred)_**:** Implement a separate duration selection interface before displaying the calendar view

Benefits:
- Improves user focus by separating duration selection from the calendar view, encouraging a task-oriented interaction and reducing cognitive load.
- API efficiency by minimizing superfluous requests.
- Increases design adaptability with a variety of duration input methods, such as duration sliders or natural language text fields.
- Refines user flow by removing the requirement for a predefined default duration.

Drawbacks:
- Requires additional UI design effort.
- Adds an extra interaction point to the user's clickstream.

Considerations:
- Integrate visual cues for a suggested duration to retain consistency with the "default duration" concept.
- Apply a progressive disclosure approach, allowing the datetime selector to seamlessly expand from the duration selector, preserving user context and minimizing interaction cost.

---

**Option 2:** Retain the current UI and manage interactions through visual-haptic cues

Benefits:
- Preserves the existing UI structure, reducing design and development overhead.

Drawbacks:
- Heightens the risk of unfavorable user experiences due to initial confusion and frustration clicks in duration selection.

Considerations:
- If a user interacts with the calendar component before choosing a duration, employ visual-haptic cues on the duration selector to signal the necessity.
- Maintain feature parity with the "default duration" concept through visual cues such as highlighted suggestions, notification modals, and warning messages on the confirmation screen if the user does not alter the default selection.

---

In both scenarios, it is presumed that most custom duration use-cases would not require a default duration, so the potential loss of feature parity may not be a significant concern.

**Comment by PeerRich** [comment]
lmao

![CleanShot 2023-03-18 at 14 00 44@2x](https://user-images.githubusercontent.com/8019099/226107856-9d40170b-a7eb-4ac9-9a26-311041227c83.jpg)

**Comment by Jaibles** [comment]
Let me think about this...

Option 1 sounds a bit like the old way of doing things that we had before:
<img width="954" alt="CleanShot 2023-03-21 at 09 28 44@2x" src="https://user-images.githubusercontent.com/4536123/226565574-63d67bc8-9144-4bcf-b045-276949caba29.png">

**Comment by ChipWolf** [comment]
@Jaibles see https://cal.com/chip, after lots of feedback from users of my calendar, I added some preset times with suggested uses; there is always some reason where someone needs a very specific amount of time for a reason that falls outside of any of the scopes I define

In essence, the "custom" option where the user can select their own time could be more flexible for the user. If they've opted against using a "preset", then an extra activation point in the clickstream to use some form of slider/button cluster input to choose their own time would be preferable.

Imagine you had 3 event types for different locations, or different team members, or different forms/templates, but all need some kind of input before presenting the calendar.
With the flow I'm suggesting, that form with the input fields which is normally presented after choosing a time could be presented first. It opens the doors to more workflow flexibility.

**Comment by PeerRich** [comment]
we'll keep this for now
