### ISSUE TITLE
[CAL-644] Caches are not cleared when changing locations or recurring event settings

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6166]
### Issue Summary

Changes to events are not reflected on the public event type pages immediately.

### Steps to Reproduce

1. Enable/disable recurrence, or add/remove/amend a location on an event type.
2. Visit the event's public page and observe the old settings in the sidebar. Wait several hours and observe the same old settings.
3. Select an available time, then return to the event page to see the cache has been updated.

<sub>[CAL-644](https://linear.app/calcom/issue/CAL-644/caches-are-not-cleared-when-changing-locations-or-recurring-event)</sub>

**Comment by PeerRich** [comment]
that is odd. I cant reproduce this. my changes are immediately when doing command + R hard reload

**Comment by ChipWolf** [comment]
> that is odd. I cant reproduce this. my changes are immediately when doing command + R hard reload

Replicated, video here:

https://user-images.githubusercontent.com/3164166/209448849-90ee95cf-767a-4ea6-8b3c-d733da4b4db9.mp4

**Comment by PeerRich** [comment]
@leog can you investigate this?

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/212740935-06541291-5d07-40cf-b166-fb1936a562b2.mov

 can't reproduce this. tried on both local and prod

**Comment by Udit-takkar** [comment]
@ChipWolf are you still facing the issue. i am unable to reproduce this.

**Comment by ChipWolf** [comment]
> @ChipWolf are you still facing the issue. i am unable to reproduce this. 

I have successfully replicated this again with the steps above on a fresh account with different devices/browsers.

**Comment by ChipWolf** [comment]
@PeerRich I'll write some selenium unit tests for this to make sure you guys can replicate it

**Comment by PeerRich** [comment]
cheers!

**Comment by ChipWolf** [comment]
> @PeerRich I'll write some selenium unit tests for this to make sure you guys can replicate it

I did write some tests for this but they're not rugged enough to distribute yet. For now I can say I can replicate this repeatedly without fail on different accounts/devices.

**Comment by ChipWolf** [comment]
@PeerRich attached is a Selenium IDE file to replicate the issue
It's a very basic test, I can add more steps but this is a good starting point:

![firefox_2023-03-03_17-32-26](https://user-images.githubusercontent.com/3164166/222788456-262dea38-ffce-408c-80ba-e5dfc23b12ca.png)

- The two `Open public page` steps will need the target adjusted with your username
- Note, the test suite assumes the **first** event type in your list is both:
  - Public & has recurring events disabled

[cal-cache.zip](https://github.com/calcom/cal.com/files/10884783/cal-cache.zip)

**Comment by PeerRich** [comment]
@roae

**Comment by roae** [comment]
thank you very much for your comments @ChipWolf  they help us a lot, 

I will try to replicate it locally, but I am almost sure that we must revalidate the cache when updating the event type.
