### ISSUE TITLE
[CAL-642] Can't embed two calendars on the same page

### ISSUE THREAD

**Issue by 0Lilian** [calcom/cal.com#6169]
### Issue Summary
Since the Cal.com embed script seems to create a global `Cal` object, when putting two embedded calendars, the latter will override the setup of the former, breaking the former.

I've successfully reverse engineered the tiny embed script to allow two distinct `Cal` objects, but now I get that console error "Cal is not defined. This shouldn't happen". It seems at that point that app.cal.com/embed/embed.js doesn't support the trick I've done :o 

So it seems that I cannot do anything on my side to make this work.

<sub>[CAL-642](https://linear.app/calcom/issue/CAL-642/cant-embed-two-calendars-on-the-same-page)</sub>

**Comment by 0Lilian** [comment]
A possible way to solve that could be to not store the `Cal` object globally or to give it a different name for each embedded cal.

**Comment by PeerRich** [comment]
hey @0Lilian, my colleague @hariombalhara will look into it. he is the embed expert

**Comment by hariombalhara** [comment]
@0Lilian Embed natively supports as many embeds on the same page as you want. You can refer to [Embed Playground](https://github.com/calcom/cal.com/blob/main/packages/embeds/embed-core/index.html) which has many embeds on the same page.

The key here is to use different namespaces for different embeds. The first argument to "init" instruction is namespace.
```
// First namespace
Cal("init", "first");
// Now Use Cal.ns.first() instead of Cal()

// Second namespace
Cal("init", "second");
// Now Use Cal.ns.second() instead of Cal()
```

**Comment by hariombalhara** [comment]
Closing the issue as it's supported already

**Comment by 0Lilian** [comment]
Thanks for that, it works now :)

**Comment by PeerRich** [comment]
oh nice
