### ISSUE TITLE
Add pre-fill ability for phone number input

### ISSUE THREAD

**Issue by gavry** [calcom/cal.com#6179]
### Is your proposal related to a problem?

I do not want to require users to input their phone numbers after I've already collected them internally.

### Describe the solution you'd like

Allow pre-filling of the phone number field within the Cal Embed.

### Describe alternatives you've considered

Tried inspecting the inputs and adding "smsReminderNumber" to the search params / config. Unfortunately it didn't connect :(

### Additional context

Not sure if there's a specific reason this was decided against, or if it just hasn't been needed yet. I believe the change would be to add router.query.smsReminderNumber to the return statement of the defaultValues function here:
https://github.com/calcom/cal.com/blob/69925af17c501ed51c54a9f21dd94dc2014ded20/apps/web/components/booking/pages/BookingPage.tsx#L200-L242

(coalescing after booking.smsReminderNumber? Could also argue for before as an override).

Happy to make the change and open a pull request if this would be a helpful feature in general. Thanks!

**Comment by PeerRich** [comment]
@hariombalhara can we prefill phone numbers with parameters?

**Comment by hariombalhara** [comment]
I am adding support to prefill all form fields in the new form builder that's cooking. 

It's not supported currently.

**Comment by PeerRich** [comment]
this is wroking now, no? @hariombalhara

**Comment by hariombalhara** [comment]
It was working earlier. Looks like when we replaced react-phone-input with a different library it broke.
So, it is getting reverted after prefill. It might be country detection as well.
https://www.loom.com/share/4fc663b3ccc8424aa0ac4193e594c71b
