### ISSUE TITLE
Google Meet link not generated / sent

### ISSUE THREAD

**Issue by LilaRest** [calcom/cal.com#6180]
### Issue Summary
When a customer books an appointment with me and choose "Google Meet" as location, the confirmation mail sent doesn't contain the Google Meet url.

### Technical details
- The only calendar I connected is through CalDav and I've seen in some other issues that this problem was also observed when people where using Outlook as their main calendar

**Comment by 0Lilian** [comment]
After some tests it seems that the link is properly generated and sent when Google Calendar is set as my default calendar.
Is that behaviour a bug or expected ? 🤔 

At the moment I cannot see why technically using Google Calendar is required to make Google Meet links working.

**Comment by PeerRich** [comment]
i think right now it requires google calendar but there is an open PR to make it standalone

**Comment by PeerRich** [comment]
cc @joeauyeung

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/pull/5904 not sure if this one will fix it

**Comment by PeerRich** [comment]
@LilaRest can you try again?

**Comment by LilaRest** [comment]
> @LilaRest can you try again?
Sure I will in the next hours, thanks for your time.

**Comment by LilaRest** [comment]
@PeerRich So I've performed some tests and it seems that #5904 hasn't changed the behavior of the Google Meet integration. That PR have simply isolated the Google Meet in its own app, allowing us to disable this one. 

But in order to make Google Meet working, enabling Google Calendar as main calendar is still required. Now there's even a clean message when editing my events' locations indicating :
> "The “Add to calendar” for this event type needs to be a Google Calendar for Meet to work. Change it [here.](https://cal.com/event-types/159608?tabName=advanced) We will fall back to Cal video if you do not change it."

To be sure I've tested to book an appointment and indeed, it fallbacks to Cal video if Google Calendar is not set as main calendar.

Can you re-open that issue ? :blush:

**Comment by PeerRich** [comment]
i dont think there is another way to do this right now other than requiring google calendar

**Comment by LilaRest** [comment]
@PeerRich Yeah it seems that creating Google Meet link using Google Calendar is the only option for non-paid Google users.

That said it also seems totally possible that the Google Meet plugin requires a Google Calendar connected but not set as default calendar.

This would allow users to use another calendar while being able to offer Google Meet appointments (if they have also connected a Google Calendar). What do you think about that ?

**Comment by LilaRest** [comment]
@PeerRich To make things cleaner we could even imagine distinct authentication processes for both Google Meet and Google Calendar apps. That way one can use one app or the other in a standalone way. In other words, by doing so we don't have to explain to users that one app (Google Meet) depends on the other (Google Calendar).

**Comment by joeauyeung** [comment]
Hi @LilaRest, I worked on separating the two apps. Right now, Google doesn't have an API to generate Google Meet links separate from a calendar event. 

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/65426560/214708063-149ddfac-0e0f-4da7-b828-b2eb92b37e46.png">


While it is possible to set a different destination calendar, we would still have to generate calendar events on that Google Calendar. We want to be transparent that whatever is set as the destination calendar will be the only calendar that Cal.com creates events on.

**Comment by LilaRest** [comment]
Hi @joeauyeung ! Firstly, thanks for your response and your work on the Google Meet app.

Then, I totally understand that it's a very bad UX to create events on the Google Calendar if users haven't chosen it as main calendar. 

But IMHO, there is an alternate way that doesn't sacrifice UX for features :
- Actually, when a user installs the "Google Calendar" app it is prompted by the Google OAuth page to allow Cal.com to manage its Google calendar
- Similarly, when a user installs the "Google Meet" app it could be prompted to give calendar permissions to Cal.com. This would result in distinct Google OAuth processes, which allows users to use the Google Meet app without even having the Google Calendar installed.
- Finally in the events interface, instead of displaying a message that tells users that Google Calendar is required to use Google Meet, we could display a message stating that every Google Meet appointment will show up in the users' Google Calendar (even if this one is disabled or is not the default calendar)

In both cases we have to display a message to the user that reveals the usage of the Google Calendar trick, but with my solution we allow the usage of Google Meet with other calendars by making Google Meet fully standalone.

What do you think about that ?

**Comment by LilaRest** [comment]
@PeerRich @joeauyeung Would it be possible to re-open this issue that hasn't been solved ATM ? :slightly_smiling_face:

**Comment by PeerRich** [comment]
i believe we show an error now if you don't have a google calendar connected

**Comment by LilaRest** [comment]
> i believe we show an error now if you don't have a google calendar connected

Yup @PeerRich that's what I mentionned in my long above message.

My proposition is to make Google Meet and Google Calendar apps independant from each other by requiring two independant Google authentications. So one can use Google Meet without Google Calendar.

**Comment by LilaRest** [comment]
@PeerRich I'm planning to create a PR implementing the behavior I've described above. 

But before starting to code I wanted to be sure that you agree with this design and so will merge it.
