### ISSUE TITLE
Default calendar to book in, changes after adding/syncing new google calendars

### ISSUE THREAD

**Issue by l0g1x** [calcom/cal.com#6181]
### Issue Summary

After adding 2 new google calendar integrations to 'Check for Conflicts', calcom seems to automatically change the default 'Add to Calendar' setting of an individual event-type link. The 'Add to Calendar' setting on an individual event-type link should not automatically change from the globally defined 'Add to Calendar' setting. See pictures below. Picture 1 shows the global 'Add to Calendar' setting set to krgebis@gmail . After adding 2 more google calendar integrations for 2 other emails I have, it seems calcom automatically changes the default 'Add to Calendar' email in one of my event-type links, without my explicit direction (Picture 2)

Picture 1:
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/5489842/209439592-bb7b71bb-0f63-4277-baa1-aa7ec9a0e018.png">

Picture 2:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5489842/209439608-871d7074-7da9-46e1-8258-d876db817b8e.png">

### Steps to Reproduce

0. Started with only 1 google calendar integration (krgebis@gmail.com)
1. Added 2 new google calendar integrations (krystian@shippercrm.com & krystian@freightcaviar.com)
2. Clicked on 'Event Types' tab
3. Clicked 'Edit' on 25 Minute meeting link
4. Clicked 'Advanced' settings option
5. View 'Add to Calendar' and see the default calendar automatically changed to krystian@shippercrm.com (one of the 2 new google calendars I added globally) - (Picture 2)
6. It should be krgebis@gmail.com, just like it says on the global calendar settings - (Picture 1)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Wasn't able to capture any logs as I only noticed this issue after already adding 2 new calendars

**Comment by l0g1x** [comment]
Without making any changes, it now seems that the default 'Add to Calendar' email is no longer different from the global 'Add to Calendar' settings page.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5489842/209577180-f20e9b20-1e9b-48c0-bf3d-109d298411ca.png">

**Comment by PeerRich** [comment]
does that mean its fixed?

**Comment by l0g1x** [comment]
yes it (magically) fixed itself! not sure how that is possible, but thought it would be worth mentioning incase this actually is a bug. Feel free to close
