### ISSUE TITLE
[CAL-647] Per event-type limit

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6182]
[From Carson on Slack](https://calendso.slack.com/archives/C01V37YT188/p1671855751622699)

> One of the things I know calendly doesn't do is an overall booking quantity limit.
>
> Yes, both [cal.com](http://cal.com) and calendly provide a per-event type limit, as in, only allow up to 3 of Event A per day.
>
> What I'm looking for are daily (maybe weekly, monthly) limits  on all meeting types. For example:
> Event A: daily limit of 3
> Event B: daily limit of 2
> Overall daily limit: 1
>
> So if a user books any event, I will show up as unavailable for that day, because my overall daily limit has been reached.
>
> It might also be cool to have these put into "booking limit groups". For example:
>
> GROUP 1
> Event A: daily limit of 3
> Event B: daily limit of 2
> Group 1 daily limit: 1
> Event C: daily limit of 5
>
> And if a user books an event A or B, that group's limit will have been reached, an no longer show as available. However, event C, not being part of the Group Limit, will still be able to be booked up to 5 times per day.
>
> This would be SO COOL!!

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-647](https://linear.app/calcom/issue/CAL-647/per-event-type-limit)</sub>

**Comment by carsonbird** [comment]
Writing this so it keeps me up to date!

**Comment by PeerRich** [comment]
i dont think we can fit this into the roadmap anytime soon but happily accepting PRs
