### ISSUE TITLE
[CAL-648] Managed Event-Types by admins

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#6184]
Give a team admin the ability to manage event-types for its members, to facilitate having common event-types between all members. The admin-created event-types could be part of a new section in each member’s profile to distinguish event types created by the member and the ones created by the admin.

As a sales manager (admin), want to:

* Create an event type for my entire sales assistants (members) to be able to use as individuals.
* I want to create and edit once, and assign to many
* Their should be locked settings and unlocked settings
* Unlocked settings for a member would be:
  * set their own availability
  * connect their own calendar
  * connect their own conferencing app
* Locked settings would include
  * I think everything else.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-648](https://linear.app/calcom/issue/CAL-648/team-event-types-admin)</sub>

**Comment by Jaibles** [comment]
In terms of design, we should ensure that we cover the needs for this feature in here.

[Admin of an small 1-10 person organisation (1 team) - Cal.com Teams (Figma)](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=302%3A39823&t=hfOoBW8HBoJkpY2k-1)

**Comment by Jaibles** [comment]
Designs are a wip here 

[2.6 Managed event types (wip) - Cal.com Teams (Figma)](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=698%3A108980&t=aympfpaHJesazFDb-1)
