### ISSUE TITLE
Plausible should work for self-hosted Plausible deployments

### ISSUE THREAD

**Issue by joshavant** [calcom/cal.com#6191]
### Is your proposal related to a problem?

Currently, the only supported style of Plausible deployment is one that's hosted by Plausible.

Self-hosters cannot configure Cal.com to use a self-hosted Plausible deployment.

### Describe the solution you'd like

I would like to configure the Cal.com Plausible app, using the native web UI, to integrate my self-hosted Plausible deployment.

### Describe alternatives you've considered

Editing source files

**Comment by PeerRich** [comment]
for this niche use case i think editing the one line in code is quicker
