### ISSUE TITLE
[CAL-809] Flaky: Self-hosters can't manage Pro features

### ISSUE THREAD

**Issue by joshavant** [calcom/cal.com#6194]
### Issue Summary

Self-hosters are unable to manage Pro features in the web UI.

### Steps to Reproduce

1. Try to toggle this switch:
<img width="799" alt="screenshot_2022-12-23_at_12 50 50_am" src="https://user-images.githubusercontent.com/830519/209563987-89c0aacd-77ad-4e1a-9d8b-2ba9d26200cb.png">

Expected: The switch can be toggled

Actual: The switch cannot be toggled

### Technical details

- Browser version: Safari Version 16.1 (18614.2.9.1.12)
- Cal.com v2.4.2

<sub>[CAL-809](https://linear.app/calcom/issue/CAL-809/flaky-self-hosters-cant-manage-pro-features)</sub>

**Comment by phishy** [comment]
@joshavant Just checked out the code and did a little test. If you make a team, logout, and log back in, you can disable the branding user a user or a team.

Looks like since Cal.com switched to team pricing, the `users.disableBranding` takes less precedence than `user.belongsToActiveTeam`.

**Comment by PeerRich** [comment]
@Udit-takkar @alishaz-polymath can you two test this a bit more and make it more seamless?

**Comment by Udit-takkar** [comment]
The toggle is working for me and i did open up a issue about belongsToActiveTeam not updating without logout here https://github.com/calcom/cal.com/issues/6455
