### ISSUE TITLE
[CAL-655] locale of date/month/day in the confirmation email is not in the receiver's locale

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6197]
![8AFC2590-3A1C-4D45-82ED-709E1CA4EBEE.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a1a0fe31-d540-4b0b-a6ad-ed7fee711398/ea2350d1-2f09-424e-824e-95b559f9b220)

that should be in en_US even if the person sending the invite does not have their locale set to en_US

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-655](https://linear.app/calcom/issue/CAL-655/locale-of-datemonthday-in-the-confirmation-email-is-not-in-the)</sub>

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, can you please give more context on the issue. When we tried reproducing the issue, the entire mail content was in organizer's locale not just  date/month/day.

![Screenshot 2023-01-11 at 6 30 40 PM](https://user-images.githubusercontent.com/121884634/211809557-6e36e901-dcf5-4703-8132-f575e76b5c43.png)

**Comment by PeerRich** [comment]
can't be reproduced anymore. seems fixed
