### ISSUE TITLE
feat(calendar): ability to add subscribed calendars as blockers

### ISSUE THREAD

**Issue by juliusmarminge** [calcom/cal.com#6199]
### Is your proposal related to a problem?

For school, we have a central calendar where we enter our courses and then get our schedule generated and a subscribe link we can add to our calendars so we have all the lectures etc in any calendar we want.

I subscribe to this on my Apple Calendar, which I have linked to my Cal.com account, however I can't select it as a blocker. 

<img width="770" alt="CleanShot 2022-12-27 at 13 02 20@2x" src="https://user-images.githubusercontent.com/51714798/209663971-b7a62a03-b683-47d5-8f2b-afb7abfd0d6c.png">

### Describe the solution you'd like

I'd like to be able to toggle the subscribed calendar as a blocker in my Cal.com schedule. I think it should be off by default since you may subscribe to a lot of calendars which aren't blocking your daily activities, but being able to have it as an option would be nice.

### Describe alternatives you've considered

None really, keeping it as is might be totally fine and I could be a one-off here?

### Additional context

I can see how this might not be that high up on your priority list since I would think most have their events in their own calendars and not subscribed ones.

There may also be limitations in the APIs which forbids this?

If this is something you'd consider adding, and would like to give me some context of the code base and the relevant parts, I might be able to take a crack at it myself.

**Comment by ChipWolf** [comment]
Give https://reclaim.ai a go, you can sync that secondary calendar into a fresh one you control, that can be used as a blocking calendar in cal.

I do the same thing for my work calendar.

**Comment by PeerRich** [comment]
I think reclaim is the best way to do this
