### ISSUE TITLE
Short and extended description for event types w/ optional confirmation

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6203]
### Is your proposal related to a problem?

To prevent overwhelming users, I try to keep the event type descriptions short, but would prefer to elaborate on them if the user chooses one.

I'd also like to ensure the user understands the option they have selected before they're able to select a slot.

### Describe the solution you'd like

An [optional] secondary description field when configuring event types that replaces the description on the event page if configured.

For bonus points, an [optional] confirmation modal occluding the event page with this extended description to confirm the user's selection and/or potentially diverting them to related options they may prefer.

**Comment by PeerRich** [comment]
hey chip, thank you for the feature request.

i dont think this is happening for many people -- will deprioritize and close for now, unless more people are reaching out to have this 🙏
