### ISSUE TITLE
Multiline 'about' field for profile page

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6204]
### Is your proposal related to a problem?

The about field currently only allows a single line of text, to ensure additional information is readable, I'd like this field to support multiple lines.

The hint text suggests 'a few sentences', but this becomes quickly unreadable.

### Describe the solution you'd like

Using - or | as separators between sentences to differentiate between points in the about section.

![image](https://user-images.githubusercontent.com/3164166/209709111-76d32d8d-d4f7-454a-a66d-696f8768cf6b.jpeg)

![image](https://user-images.githubusercontent.com/3164166/209709123-d97381e1-5df2-472f-a19e-0bb9e9bc75df.jpeg)

**Comment by phishy** [comment]
Coming right up!
