### ISSUE TITLE
Getting started - input gets reset when switching tabs

### ISSUE THREAD

**Issue by kuba-orlik** [calcom/cal.com#622]
### Issue Summary

The input values get reset in the Getting Started view if the user switches tabs.

### Steps to Reproduce

1. Log in for the first time
2. See the getting started guide
3. Connect a caldav calendar
4. Get asked for availability
5. Fill in some availability details
6. switch tabs in the browser
7. come back to the tab with calendso
8. all input is gone

### Technical details
* Browser version: Firefox 92

**Comment by llldar** [comment]
cannot repoduce, tested on both chrome and firefox

**Comment by alishaz-polymath** [comment]
This issue cannot be reproduced, hence going ahead to close this. Please feel free to re-open this issue in case you can still reproduce this issue in the latest pull 🙏
