### ISSUE TITLE
[CAL-665] investigate deployment buttons

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6231]
[https://github.com/calcom/cal.com#deployment](https://github.com/calcom/cal.com#deployment)

can someone test

* [ ] heroku
* [ ] railway
* [ ] vercel

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-665](https://linear.app/calcom/issue/CAL-665/investigate-deployment-buttons)</sub>

**Comment by phishy** [comment]
I can take a look tomorrow. I also wanted to look into serverless via serverless-nextjs and trpc serverless adaptor. Also devcontainer/codespaces 1 click dev setup. I'll make some issues for those when ready.

**Comment by PeerRich** [comment]
epic!

**Comment by phishy** [comment]
So far, the slug for Heroku is about twice the size of the maximum. Looking into if there's a way to pare that down. There are lots of apps and node_modules.

**Comment by rjherrera** [comment]
Hi guys, any ideas on how to reduce the slug size? We can't deploy on Heroku because of that. If you've got suggestions for how to temporarily fix the issue in our own fork, that would be very helpful.

**Comment by PeerRich** [comment]
not sure. will investigate this quarter
