### ISSUE TITLE
Event Title Personalization

### ISSUE THREAD

**Issue by joshavant** [calcom/cal.com#6241]
### Is your proposal related to a problem?

Currently, the event title UI cannot be customized.

It is currently a constant value, configured in the user's dashboard.

When distributing direct links to event scheduling pages, (e.g. `https://calendar.foo.com/joe/15-min`) the UI will always be generic, in the sense that the title can only ever say '15 Minute Call'.

This can contribute to a less personalized UX for recipients (e.g. marketing targets, friends, family, etc).

For many uses of Cal.com, personalization is an important aspect of the UX.

### Describe the solution you'd like

It would be useful to be able to parameterize an event's title.

For example, a Cal.com user could distribute a link with URL parameters formed like so:
`https://calendar.foo.com/joe/15-min?person=Peer`

And, when that link is clicked, the displayed title would be:
'15 Minute Call with Peer'

Without a `person` parameter, the default behavior would be:
'15 Minute Call'

With this feature, when Peer (in this case, the recipient of the booking link) clicks the link, he will see '15 Minute Call with Peer' in the UI and the booking UX will feel customized to him, rather than an impersonal intake form from the sender.

### Describe alternatives you've considered

Dynamic Bookings appear to parameterize around invitees within the org. This doesn't allow customization of the title UI.

**Comment by PeerRich** [comment]
i dont think this is something we plan to do anytime soon. low demand and high complexity

**Comment by PeerRich** [comment]
you could, however, use routing forms and write certain routes that link to different types of event types
