### ISSUE TITLE
[CAL-670] Incorrect SkeletonLoaders

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6244]
![CleanShot 2023-01-03 at 11.34.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f10349ef-42bf-4721-8ecb-661c32ffa355/f9b9f51f-7477-4947-9136-6ea912446682)

Lots of places in the app are using the skeleton loader that is exported from apps. This is the incorrect design and doesn't match the UI that is being loaded.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-670](https://linear.app/calcom/issue/CAL-670/incorrect-skeletonloaders)</sub>

**Comment by draqist** [comment]
I'd like to work on this, could you give a better description?

**Comment by Raj7Dev** [comment]
Can you assign this task to me?

**Comment by gambhirsharma** [comment]
> Can you assign this task to me?

Are you working on this issue rn.

**Comment by virinchimanepalli** [comment]
@sean-brydon is it still open?  i could like to contribute. can you assign it to me?

**Comment by sean-brydon** [comment]
Hi @virinchimanepalli I'm going to pass this issue to @gambhirsharma since he was interested before you - please tag me in any other issues you fancy and i will assign <3

**Comment by gambhirsharma** [comment]
Hey! @sean-brydon can you please provide more detail on this issue?

**Comment by PeerRich** [comment]
whoever is interested just raise a PR, no need to be assigned first

**Comment by JaideepGuntupalli** [comment]
@sean-brydon, I think this was fixed since I can't find any `SkeletonLoaders` with similar imports, as mentioned in the screenshot of the issue. For example, this is the screenshot of the current state of the same file, and it is being imported correctly.

**So, the issue should be closed.**

cc: @PeerRich 

<img width="1680" alt="Screenshot 2023-06-11 at 19 10 00" src="https://github.com/calcom/cal.com/assets/63718527/0d172d0a-2c69-45a7-93ac-797f5eb668fc">

**Comment by sean-brydon** [comment]
> @sean-brydon, I think this was fixed since I can't find any `SkeletonLoaders` with similar imports, as mentioned in the screenshot of the issue. For example, this is the screenshot of the current state of the same file, and it is being imported correctly.
> 
> **So, the issue should be closed.**
> 
> cc: @PeerRich
> <img alt="Screenshot 2023-06-11 at 19 10 00" width="1680" src="https://user-images.githubusercontent.com/63718527/244941143-0d172d0a-2c69-45a7-93ac-797f5eb668fc.png">

Thank you
