### ISSUE TITLE
[CAL-672] turn description into a multi-line field

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6253]
*Issue: Description form field is conflicting on Create Modal vs Edit Page*

When creating an event type, the description field is a multi line field, whereas when you are editing the event type description it turns into a single line field.

I like to space out my descriptions (as attached below) which I am able to do nicely when creating but on edit I get confused and can’t tell (see attached).

On another but similar note, where should I put feature requests?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-672](https://linear.app/calcom/issue/CAL-672/turn-description-into-a-multi-line-field)</sub>

**Comment by phishy** [comment]
I added an autosizing textarea for multiline bios here if that's any use. https://github.com/calcom/cal.com/pull/6216

**Comment by phishy** [comment]
@PeerRich Yeah that PR has an issue with a type that it's currently ignoring. But yeah, changing it to an autosizing field would fix it. Going a step further, might even want to add some [Markdown WYSIWYG buttons](https://uiwjs.github.io/react-md-editor/).

**Comment by PeerRich** [comment]
we have a WYSIWYG in the workflow email textfield cc @CarinaWolli

**Comment by Udit-takkar** [comment]
fixed here https://github.com/calcom/cal.com/issues/6267
