### ISSUE TITLE
[CAL-673] Weird color when clicking "new" button on events page

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6254]
![CleanShot 2023-01-03 at 15.16.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9b2c1ef-2fc6-4c63-8830-886a514d088c/4d800d82-0449-4c83-b4f6-b2eab2e90b92)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-673](https://linear.app/calcom/issue/CAL-673/weird-color-when-clicking-new-button-on-events-page)</sub>

**Comment by phishy** [comment]
@shirazdole What browser is that? Production? I can't reproduce.

**Comment by emrysal** [comment]
Removed Quick Wins label as it needs more info @shirazdole. Unable to reproduce on my end too.

**Comment by PeerRich** [comment]
can't reproduce here either

**Comment by PeerRich** [comment]
can reproduce on production, but not on main. seems like it was fixed
