### ISSUE TITLE
Option to add self-hosted Jitsi

### ISSUE THREAD

**Issue by gokceozan** [calcom/cal.com#6262]
### Is your proposal related to a problem?

It is wonderful to have Jitsi as an option for a meeting. But it is frustrating to not be able to use a self-hosted (or collective-hosted) instance. I am sure privacy-focused individuals would prefer a self-hosted instance as an option.

### Describe the solution you'd like

Have the option on the app to connect to a self-hosted (or collective-hosted) Jitsi instance as the provider. Failing to provide that would result in public Jitsi servers. Similar to the CalDav connection.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by PeerRich** [comment]
we would need community contributions for this. happy to accept incoming PRs

**Comment by sopel** [comment]
This duplicates https://github.com/calcom/cal.com/issues/1847.

* Note that the conversation lists some attempts/workarounds to use a self-hsoted Jitsi instance, so depending on your requirements that might already work for you.

**Comment by chief-nerd** [comment]
There is an open pull request from me that would add this feature: https://github.com/calcom/cal.com/pull/8636
