### ISSUE TITLE
[CAL-676] Make WYSIWYG Editor reusable

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#6267]
Make the WYSIWYG Editor reusable. So we can use it for event type description and the about section ([https://github.com/calcom/cal.com/pull/6216](https://github.com/calcom/cal.com/pull/6216))

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-676](https://linear.app/calcom/issue/CAL-676/make-wysiwyg-editor-reusable)</sub>

**Comment by PeerRich** [comment]
epic
