### ISSUE TITLE
[CAL-679] Layout : Sidebar - Padding, Margins off

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6270]
![CleanShot 2023-01-04 at 14.21.50.gif](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/31e31aad-dda9-41c5-9477-fe56e58b5bd1/a6e7ae99-3850-4eba-b340-eaca19a12a3f)

[Full spec in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=17937%3A171148&t=BvyDUX1KlCJHvzJS-1)

[Sidebar/Default Anantomy - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=17937%3A171148&t=BvyDUX1KlCJHvzJS-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-679](https://linear.app/calcom/issue/CAL-679/layout-sidebar-padding-margins-off)</sub>

**Comment by Udit-takkar** [comment]
@Jaibles  which tool are you using to see switch between figma and prod ?

**Comment by Jaibles** [comment]
@Udit-takkar i did that in Figma but will have a look if there's a tool to do it - Feels like there should be one! If not I'll do this for a lot more pages in Figma.
