### ISSUE TITLE
[CAL-889] Duplicate Event gives an error

### ISSUE THREAD

**Issue by oliversum-ch** [calcom/cal.com#6272]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Duplicating an event on cal.com leads to an error:
```
Failed to load resource: the server responded with a status of 500 ()
_app-67a5f2ac0b961226.js:1  << mutation #7 viewer.eventTypes.duplicate Object
```

### Steps to Reproduce

1. on "event types" I selected "duplicate event" in the menu
2. I added a unique name
3. The URL isn't correct
4. "An unexpected error occurred. Try again."
![image](https://user-images.githubusercontent.com/75724465/210587494-a021d967-ce92-4482-bd4d-76b84417fafd.png)

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
Sidekick Version 106.33.1.28265 (Official Build) (64-bit)

<sub>[CAL-889](https://linear.app/calcom/issue/CAL-889/duplicate-event-gives-an-error)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar can you look into this?

**Comment by Udit-takkar** [comment]
Okay

**Comment by Udit-takkar** [comment]
@PeerRich https://github.com/calcom/cal.com/pull/6730#issue-1558192188 duplicate event is working fine. can't reproduce this even on production and URL thing would be deployed in next release
