### ISSUE TITLE
[CAL-683] UI issue - Confirmed event page - URLs can break layout

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6278]
Long links can break out of the layout. Can we force these onto a new line?

![CleanShot 2023-01-04 at 20.46.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2cf6b139-fd58-4237-aae0-337882a63dac/d022c69e-4119-418a-8715-406652ef5469)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-683](https://linear.app/calcom/issue/CAL-683/ui-issue-confirmed-event-page-urls-can-break-layout)</sub>

**Comment by mocherfaoui** [comment]
hey @Jaibles, is this good enough?
![Screenshot 2023-01-11 134133](https://user-images.githubusercontent.com/37941426/211808904-a2199843-7c6d-4902-9ea8-46854ed6e651.png)
note that it will break long words too like in [Tailwind docs](https://tailwindcss.com/docs/word-break#break-words)

**Comment by Jaibles** [comment]
Looks great to me @mocherfaoui thank you 🙏
