### ISSUE TITLE
[CAL-724] When cancelling recurring set only the first event get removed from the calendar

### ISSUE THREAD

**Issue by jacobzukerman** [calcom/cal.com#6281]
When canceling a recurring set of invites, "cancel all remaining." Bookings get removed from the Cal UI, but only the first Calendar invitation gets removed from the Host and Attendee. 

Steps to Reproduce:
1. Set up a recurring event
2. Book the recurring event with self or another email
3. Cancel the recurring event (all remaining)

Video walking through the issue:
https://www.loom.com/share/26f7f0a2e9be430797e1084ccd266fa3

We have been able to reproduce this consistently in our self-hosted experience and in the publicly available version via cal.com. 

<sub>[CAL-724](https://linear.app/calcom/issue/CAL-724/when-cancelling-recurring-set-only-the-first-event-get-removed-from)</sub>

**Comment by PeerRich** [comment]
@leog can you investigate this?
