### ISSUE TITLE
[CAL-687] Rescheduling round robin events issues

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6283]
Bug with round robin events when rescheduling

Created via Threads. See full discussion: [https://threads.com/34440612390](https://threads.com/34440612390)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-687](https://linear.app/calcom/issue/CAL-687/rescheduling-round-robin-events-issues)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli and @emrysal wanna peer-program this?
