### ISSUE TITLE
[CAL-690] use i18n in routing forms pages

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#6290]
### Issue Summary

https://github.com/calcom/cal.com/pull/6261#pullrequestreview-1237283067

<sub>[CAL-690](https://linear.app/calcom/issue/CAL-690/use-i18n-in-routing-forms-pages)</sub>

**Comment by saideepesh000** [comment]
hey @Udit-takkar , can u assign this to me and provide me some more details

**Comment by PeerRich** [comment]
assigned oyu @saideepesh000
