### ISSUE TITLE
[CAL-695] Google calendar - calendar owner not available when choosing destination calendar

### ISSUE THREAD

**Issue by TymonSliwinski** [calcom/cal.com#6299]
### Issue Summary

Account owner's calendar is not visible as a destination calendar for events when connecting Google Calendar; only shared or subscribed calendars are available. Only after removing a couple of subscribed calendars the account owner's calendar shows as an option.

### Steps to Reproduce

I cannot reliably reproduce this issue, but I had this happen with 2 different accounts. Both accounts have lots of shared and subscribed calendars. Removing a few subscribed calendars, so that there was only ~35 left, fixed this issue in both cases.

### Technical details

Both accounts used to connect to calendar were in the same google workspace

<sub>[CAL-695](https://linear.app/calcom/issue/CAL-695/google-calendar-calendar-owner-not-available-when-choosing-destination)</sub>

**Comment by joshlevinson** [comment]
I ran into this issue as well. Makes Cal pretty much unusable if I can't pick my own calendar...

**Comment by joshlevinson** [comment]
In my case, I removed many calendars and the issue persisted - just kept pulling other seemingly random calcs from my account. Suggest that Cal prioritizes own calendar.
