### ISSUE TITLE
[CAL-697] allow date overrides when all availability is off

### ISSUE THREAD

**Issue by phishy** [calcom/cal.com#6311]
### Is your proposal related to a problem?

Yes. Cal.com is almost an event booking system. One tweak and it could be. For example, if I want to host 3 different event types, each representing a different cuisine cooking class, I can make an availability matrix for each. Likely, I would turn off all availability, and add date overrides for each scheduled event. This would allow people to book for only specific days.

Currently, if all availability is switched off, turning on an override does nothing last time I checked. Correct me if I'm wrong.

As a user's business grows, it would likely turn into a more permanent recurring calendar, thus allow the user to continue using Cal.com for its intended purpose of booking up a calendar of slots.

One other thing to note, is that it would be nice for each event type to have its own conflict calendar for this same purpose. Otherwise, there's no way to host discrete classes on specific datetimes and not have them battle eachother with multiple global conflict calendars.

### Describe alternatives you've considered

In order to meet this need, we turned to TicketTailor, but ultimately Cal.com could be a good fit for this use case.

<sub>[CAL-697](https://linear.app/calcom/issue/CAL-697/allow-date-overrides-when-all-availability-is-off)</sub>

**Comment by PeerRich** [comment]
interesting. we'll investigate this how we can best do this

**Comment by PeerRich** [comment]
so what you want is to disable availability but overwrite and enable certain dates. I think we already think about doing this @emrysal @Jaibles

**Comment by karolzlot** [comment]
This is how it works in Calendly, please implement it.

**Comment by PeerRich** [comment]
I believe this was opened by @emrysal
