### ISSUE TITLE
Unclear error forwarding with CalDAV slow servers

### ISSUE THREAD

**Issue by victorpaleologue** [calcom/cal.com#6313]
### Issue Summary

In [this issue](https://github.com/calcom/cal.com/issues/5955) there was a 502 Bad Gateway error that was not reported clearly by the appointment scheduling interface:
> La réunion n'a pas pu être réservée. unexpected character at line 1 column 1 of the JSON data

![image](https://user-images.githubusercontent.com/8899804/206712338-194f283e-0ac5-45f3-b49f-8cdaaa79b831.png)

### Steps to Reproduce

1. Setup a Nexcloud account on a slow server, not optimized, and with a lot of events in the agenda.
2. Create a Cal.com account with the CalDAV URL provided for the Nextcloud account.
3. Setup an event type and schedule an event.
4. If the Nextcloud instance is bad enough, it may produce a 502 error, which gets inaccurately reported.

### Technical details

- Independent from browser.

**Comment by PeerRich** [comment]
lets add this to #3457

**Comment by PeerRich** [comment]
lets continue here: https://github.com/calcom/cal.com/issues/3457
