### ISSUE TITLE
[CAL-759] `No available users found.` error when appointing on a date-overriden slot

### ISSUE THREAD

**Issue by victorpaleologue** [calcom/cal.com#6314]
### Issue Summary

When scheduling an appointment on a slot made available by date overriding, it fails with the error `No available users found.`. The Cal.com account was configured with CalDAV provided by a Nextcloud instance.

### Steps to Reproduce

1. Configure a Cal.com account with the CalDAV app, configured with a Nextcloud account.
2. Setup your availability.
3. Add a date override to open a slot earlier than the first available hour on a future date.
4. Try to schedule a meeting at the beginning of the slot.

### Technical details

- It was not tried an app other than CalDAV.

<sub>[CAL-759](https://linear.app/calcom/issue/CAL-759/no-available-users-found-error-when-appointing-on-a-date-overriden)</sub>

**Comment by grapeslush** [comment]
I imagine this is related to the bug I posted about with the same error. Seeing a lot of this and all it seems to be related to daylight savings time.

https://github.com/calcom/cal.com/issues/6217

**Comment by PeerRich** [comment]
hey @Udit-takkar, @G3root can you investigate? Potentially a CalDav bug, maybe pull in @alishaz-polymath 

if its an availability bug, then pull in @emrysal

**Comment by PeerRich** [comment]
can you try again?

**Comment by victorpaleologue** [comment]
Still did not work, but the error message is more elegant :

![image](https://user-images.githubusercontent.com/8899804/226971767-6d4f73de-b983-4dbc-bfa6-c329c67027fd.png)

**Comment by PeerRich** [comment]
what's your link? this could be due to a different bug

**Comment by PeerRich** [comment]
feel free to also send the link to support@cal.com if you don't want to publish it here (public)

**Comment by PeerRich** [comment]
i think this has been fixed
