### ISSUE TITLE
[CAL-698] RFC: Consider start splitting translation files per module/route/etc.

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6315]
Right know we concentrate all of our translations string in a single `common.json` file which was fine for the time being. But as the app keeps growing we're starting to get some size warnings from next:

```
@calcom/web:dev: Warning: data for page "/auth/login" is 174 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
@calcom/web:dev: See more info here: https://nextjs.org/docs/messages/large-page-data
```

The main culprit being that we download the whole `common.json` file on each page.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/30b2409f-ce28-4e34-a85c-4a1842b54ef3/08162aae-4a85-40d1-8677-6fa2a6eeb96b)

We could create namespaces for specific routes and call then on the get props methods as [described in the docs](https://github.com/i18next/next-i18next#4-declaring-namespace-dependencies).

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-698](https://linear.app/calcom/issue/CAL-698/rfc-consider-start-splitting-translation-files-per-modulerouteetc)</sub>

**Comment by PeerRich** [comment]
urgh.. i really like a mono file, it makes many things easier in crowdin. but if performance is in the way I guess we need to extract them.

its a ton of work tho

**Comment by PeerRich** [comment]
I also find it a lot more work to add new pages/components when you also need to add new language files, add them to crowdin, etc.

**Comment by PeerRich** [comment]
it's already slowing down devs to add and extract t("key_string"), if it means to also add a new language file i can see that become an issue over time.

i guess there is no way to only partially load the common.json right? would be surprised. 

or maybe there is a script that breaks up the file on build?

**Comment by PeerRich** [comment]
also the benefit of having one file is that i can easily download "all german strings" and send it to a translator whereas having a bunch of files that are spread out in different folders will make this a lot hardere

**Comment by PeerRich** [comment]
> The main culprit being that we download the whole common.json file on each page.

can we not download the file once?

**Comment by zomars** [comment]
I'm looking into ways to "download once use it everywhere". But we would need to to it outside Next.js so it doesn't include it in it's paload.

**Comment by PeerRich** [comment]
keeping a mono-file would be my preference to be honest. i know its a tradeoff between performance and developer experience

**Comment by PeerRich** [comment]
any news re: "download once use it everywhere"? If not I could also reach out to nextjs i18n experts to see what they recommend

**Comment by PeerRich** [comment]
my vote is still: preferably mono-file

**Comment by zomars** [comment]
I got it on hold for now. Any input on this would be nice for sure.

**Comment by PeerRich** [comment]
ok will search for some nextjs experts!

**Comment by cstrnt** [comment]
I think it might be possible to handle this by altering next-i18next

**Comment by AaronPresley** [comment]
Hello 👋 G11N / I18N consultant here and happy to weigh in.

I do NOT recommend splitting up a single language's keys into multiple files. This will add a lot of logistics that are guaranteed to frustrate dev experience and add even more overhead to the translation flow.

Step 1 I recommend name-spacing your keys (ex: "cool-key" becomes "route1.cool-key").

Next you'd serve your keys through a BE endpoint that allows you to filter (ex: "/api/i18n?filter=route1")

This allows you to keep the keys organized into one file per lang while being able to more easily change your mind later by changing the namespaces.

I would not recommend using anything but the key's name to achieve this - like an additional data field - as that info could be lost when sending off to a translation vendor (not all of them support metadata fields).

This is the approach I recommend to clients, and is what Nike is using throughout their various systems. I've used many different approaches to this problem but this is the least bad in my experience.

Happy to discuss in more detail if desired. Thanks.

**Comment by PeerRich** [comment]
hey @AaronPresley would love to get your help! opened a bounty just now

**Comment by cstrnt** [comment]
@AaronPresley amazing idea! I was thinking about altering the HTML/JSON files that next outputs to clear out unused fields, but yours feels like the better DX

**Comment by AaronPresley** [comment]
Hello! I've just met with @PeerRich to discuss the specifics around this issue, and am summarizing our discussion here. This is a bit lengthy, but am aiming for clarity upfront.

Firstly, GREAT work on a solid I18N foundation 👍. Your team clearly cares a lot about creating a good experience for non-US or non-English speakers. I'm excited to build upon what you've already started.

## My Discoveries
I pulled the code locally, and confirmed that not only are I18N keys strings pulled on reach route change, but they're also pulled periodically even without a route change. Peer didn't seem surprised by this.

A few other notes that weigh on my recommendations:
- There are a bit more than 1,500 keys in the project. This is relatively few compared to some projects.
- English translations are by far the most commonly used, according to your [open data](https://cal.com/open). This file comes in at around `86kb`. French and German are close behind at `185kb` and `176kb` respectively.

## Potential Solutions
There are several approaches one could take to improve this. The following are what Peer and I discussed.

### Possible Solution 1: Do Nothing
Considering the small sizes of the translation files, I would typically tell a company it'd be easier to reduce file size in other parts of the codebase. This would be significantly less effort than completely changing your translation workflow.

That said, it seems the team here has a priority on performance. At only `86kb` the translation file is one of the larger files sent on Production builds (which is impressive 🚀 ). This makes me think the team would want to pursue a fix despite the small file sizes, and Peer agreed.

### Possible Solution 2: Namespace Keys + Filter from BE Call

This is my original recommendation. See [that comment](https://github.com/calcom/cal.com/issues/6315#issuecomment-1405621323) for more context.

After investigating further, I no longer recommend this approach. Changing your key names is a big undertaking. Not only would you have to update the codebase, but each translation file of each language would also have to be modified. This would be a significant amount of work for such a small number of keys.

### Recommended Solution: Store Keys In `LocalStorage`

Translations typically change very infrequently. For this reason I recommend caching them. In the case of `calcom`, there are no iOS or Android apps to consider at this time. For this reason I would recommend caching the current language's I18N keys in the browser's `LocalStorage`, along with some mechanism to invalidate the cache.

#### Concerns With This Approach

**What if we run out of room in `LocalStorage`?**

Local Storage has a max capacity of around 10MB, making space concerns negligible for now.

**What will value the in `LocalStorage` look like?**

This is something I would expect the team to agree on, but I recommend something like the following:

```json
{
    "lastPull": "<Date of Last Pull from BE>",
    "lang": "de",
    "keys": {
        "some_key_1": "Some Translation 1",
        "etc": ".."
    }
}
```

This type of structure will allow for easy cache invalidation in the event the user changes their language or the `lastPull` date is beyond the agreed upon cache expiration.

**What about mobile browsers?**

`LocalStorage` is supported on mobile browsers as well 👍 

## Next Steps

I've agreed to submit a PR for this effort, however I would like any contributors to weigh in on the following:

1. Agree or Disagree with the recommended approach? Please mention any issues I might have missed, or am misunderstanding
2. How long should the keys be cached? I recommend 1 to 2 hours, as this is short enough to fix any typos that might get released, but long enough to preserve keys throughout multiple sessions for more active users.
3. I'll review previous PR's as a guide to how this team manages them, but please let me know if there are any specifics guides or processes I should follow.

I'll begin work in the coming 24 hours or so, please let me know of any concerns or thoughts you have on what I've outlined above.

**Comment by PeerRich** [comment]
agree "Possible Solution 2" is not worth the effort for such little performance gain 

localStorage sounds like a really smart idea! we can invalidate it every time someone visits "Settings", too

**Comment by PeerRich** [comment]
@zomars any objections to have @AaronPresley make a PR with a LocalStorage solution?

**Comment by zomars** [comment]
Can we achieve the same result by querying taking advantage of react query caching? In theory we could:

1. Avoid batching in i18n endpoint so we can...
2. Add a more aggressive caching header in that specific endpoint (1-2 hours)
3. Maybe delay the time that endpoint is revalidated as well

This would allow us to keep using locales as always without implementation changes. Only config tweaking.

**Comment by PeerRich** [comment]
i like that too since we already have some caching with trpc/react query

**Comment by AaronPresley** [comment]
@zomars that's a great approach as well. My biggest concern with my recommendation was changing how the code was using `i18next`, but caching the endpoint itself could address that problem.

I'll begin the PR by exploring that approach and bring you in if I come across any issues there.

**Comment by PeerRich** [comment]
@AaronPresley thank you for getting back and offering a PR. I think the react query approach is better to start and if that doesnt help, we can still explore a LocalStorage approach

**Comment by PeerRich** [comment]
@gitstart-calcom unassigned you

**Comment by PeerRich** [comment]
assigned @AaronPresley

**Comment by cstrnt** [comment]
@PeerRich @AaronPresley I'm wondering how you want to use react-query here as next-i18next loads the locales initially via SSR and then puts them into a provider. I don't think you're able to alter the data in the provider thus making the react-query approach not viable?

**Comment by AaronPresley** [comment]
@cstrnt I'll take your and @zomars's guidance on the implementation specifics here, as I'm just getting familiar with the codebase.

At a high level I do feel caching the endpoint is a good first step, though I don't think it's the only improvement that could be made here. You can see [in this function](https://github.com/calcom/cal.com/blob/main/apps/web/pages/api/trpc/%5Btrpc%5D.ts#L32-L62) that currently the I18N endpoint is intentionally _not_ being cached. I'm working on a PR right now to address this problem.

From there I was expecting to invalidate the query when the user changes their language. There are some edge cases with this flow (which I'll address in that PR), but I think this is a good first step with the least amount of effort.

Of course please weigh in on anything I'm misunderstanding.
