### ISSUE TITLE
[CAL-704] Availability cannot span past midnight

### ISSUE THREAD

**Issue by ahmedsadman** [calcom/cal.com#6323]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have one event where the duration is 60 minutes and slot increment is 30 minutes. My selected availability is 10:30PM - 2:00AM. Given that, it should have a slot at 11:30PM so the meeting would be on 11:30PM - 12:30AM. But, the application doesn't allow booking at 11:30PM. See the attached screenshot. I should mention that I have selected my availability up to [11:59PM for a day](https://github.com/calcom/cal.com/pull/6137).

### Steps to Reproduce

1. Make your availability 10:30PM - 2:00AM
2. Make the event duration 60 mins
3. Make the slot increment 30 mins
4. Try to book a meeting at 11:30PM from your public page link, you won't find 11:30PM (unexpected)

**Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?**

Try to book a meeting at 11:30PM from your public page link, you won't find 11:30PM (unexpected). The expectation is that you can book that meeting at 11:30PM.

### Technical details

Not applicable
![Screenshot 2023-01-07 224452](https://user-images.githubusercontent.com/11042267/211161567-fa0a12fb-78d6-4a34-941f-6495c078be21.png)

<sub>[CAL-704](https://linear.app/calcom/issue/CAL-704/availability-cannot-span-past-midnight)</sub>

**Comment by PeerRich** [comment]
can you try again? we made a hotfix

**Comment by ahmedsadman** [comment]
> can you try again? we made a hotfix

Unfortunately, it still doesn't work for me. Not seeing any 11:30 PM option

![Screenshot 2023-01-27 013032](https://user-images.githubusercontent.com/11042267/214931903-0609d621-e026-49fe-85a1-e362b52b6c63.png)

**Comment by 12ian34** [comment]
Also related is #6054 - now I'm not sure why that was closed.

**Comment by PeerRich** [comment]
this is a really low hanging plus hard to fix issue. We're reworking the entire booking page right now and will revisit this later
