### ISSUE TITLE
[CAL-702] Fix Routing Forms E2E test: F1<-F2 Relationship

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6324]
[This test](https://github.com/calcom/cal.com/blob/3fe02fba266eb61677032e85efed70ed32491318/packages/app-store/ee/routing-forms/playwright/tests/basic.e2e.ts#L63-L66) has been failing randomly with PRs that don't touch any of the routing forms code ([example1](https://github.com/calcom/cal.com/actions/runs/3862888657/jobs/6584738478)):

```

1121
  1 failed
1122
    [@***com/app-store] › packages/app-store/ee/routing-forms/playwright/tests/basic.e2e.ts:64:7 › Routing Forms › Zero State Routing Forms › F1<-F2 Relationship › Create relationship by adding F1 as route.Editing F1 should update F2 
1123
  2 skipped
1124
  8 passed (1m)
1125
Error:   1) [@***com/app-store] › packages/app-store/ee/routing-forms/playwright/tests/basic.e2e.ts:64:7 › Routing Forms › Zero State Routing Forms › F1<-F2 Relationship › Create relationship by adding F1 as route.Editing F1 should update F2 
1126
    Error: expect(received).toBe(expected) // Object.is equality
1127

1128
    Expected: 2
1129
    Received: 0
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-702](https://linear.app/calcom/issue/CAL-702/fix-routing-forms-e2e-test-f1-f2-relationship)</sub>

**Comment by hariombalhara** [comment]
This is already fixed
