### ISSUE TITLE
[CAL-703] Fix E2E Flaky test: hash my url

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6325]
[This test](https://github.com/calcom/cal.com/blob/6f48869021055e12e2cfef4cdfbfbfd734aa95d5/apps/web/playwright/hash-my-url.e2e.ts#L8-L9) has been failing randomly.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-703](https://linear.app/calcom/issue/CAL-703/fix-e2e-flaky-test-hash-my-url)</sub>

**Comment by emrysal** [comment]
No longer flaky

**Comment by O4epegb** [comment]
> No longer flaky

But it should be enabled then? Or not? 😄 Why close without changing?
