### ISSUE TITLE
[CAL-706] Allow click-and-drag to set availability

### ISSUE THREAD

**Issue by exercismnow** [calcom/cal.com#6332]
### Is your proposal related to a problem?

It's tedious and error prone to set availability by adding time-frames one-by-one, especially for people with a non-standard work day. For example, a standard work day might be 9 AM - 5 PM. Whereas my workday might be 5 AM - 8 AM, 12 PM - 3 PM, 5 PM - 8 PM

Currently, you need to enable or disable a weekday, and then enter in each time frame one at a time, repeating this process for each weekday.

Entering in date overrides is even more tedious, since you need to first select the date, and then set each time-frame one-by-one.

### Describe the solution you'd like

https://user-images.githubusercontent.com/119020198/211178917-7f9d5bbd-a281-4470-89b9-7e20316360d0.mp4

Click-and-drag to pick times is implemented in apps like when2meet - https://www.when2meet.com. Example video attached.

For the regular weekday availability, please enable us to click and drag from a weekly calendar.

For date-override availability, please present a screen similar to the regular weekday availability, but with specific dates on it. We can then select times via click and drag, and then click an arrow to navigate between weeks.

### Describe alternatives you've considered

Any alternative for the date override availability is to let us select the day from the calendar as we currently do, and then click-and-drag to select time-frames.

<sub>[CAL-706](https://linear.app/calcom/issue/CAL-706/allow-click-and-drag-to-set-availability)</sub>

**Comment by Jaibles** [comment]
We can re-use our weekly view for this.

**Comment by davidmucci** [comment]
> We can re-use our weekly view for this.

@Jaibles Definitely! 

Cron does a great job with this UX, however, they do it in a slightly different context than what was referenced above by @exercismnow. Sometimes I send out my normal Cal.com link, which has set the availability, but if I want to only send out a few days and times, then I use this feature in Cron. It would be nice to make custom links on the fly so I can do all of this in Cal. Made a Loom for reference!

https://www.loom.com/share/ce3722c9be794874afddb04fade65bb6

**Comment by Jaibles** [comment]
Hey @davidmucci we actually explored designs for this so long ago that it's in our previous design of the app, but you can get a sense of what we have planned [here](https://www.figma.com/file/k5XE5yYxg7jEyhohtJee9H/%F0%9F%93%9D-Cal-Feature-Work?node-id=257%3A15888&t=konoZeVFjmNopEwD-1). We're doing updated designs with our new weekly view  [here](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=15%3A52442&t=vMuHYgZMRlvFd5oL-1) - we'll have them up to date within the next week.

We have built the weekly view which this feature depends upon. We're currently doing some refactoring to our booking pages which is causing a delay in getting it live, but we should have it soon as it's actively being worked on.

Once we have that we'll be looking at adding this feature. I'm Cron power user myself so totally get what you're after and why :)

**Comment by exercismnow** [comment]
Great example, @davidmucci . I would love to send these custom invite links on the fly in Cal.com. If click-and-drag could be used for ad-hoc and regular availability, that would be awesome.

And great to hear that you're planning to add the feature, @Jaibles !

**Comment by davidmucci** [comment]
@Jaibles Thanks for the explanation! Excited about what's coming 🚀

**Comment by davidmucci** [comment]
> Weekly view nearly ready so we can prioritise this now. Will prepare designs. cc @sean-brydon

Fired up!!
