### ISSUE TITLE
[CAL-710] /App store : Spacing issues - Check all margins against design

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6336]
* I have clearly spec'd all spacing in designs. Check all margin & spacing
* Also check the styles of the headers.

![CleanShot 2023-01-08 at 12.41.02@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/96400cec-c92f-49b3-8fb4-e2df61ea5e78/dcd13372-019e-4726-bf47-210bb7d8011a)

[View in Figma](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A53096&t=AeM4S9etPe88eosE-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-710](https://linear.app/calcom/issue/CAL-710/app-store-spacing-issues-check-all-margins-against-design)</sub>

**Comment by G3root** [comment]
@Jaibles i'll take this
