### ISSUE TITLE
[CAL-756] Approval email - click on "accept" leads to an error

### ISSUE THREAD

**Issue by oliversum-ch** [calcom/cal.com#6340]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I received an approval email: "An event is still waiting for your approval"

### Steps to Reproduce

1. Turn on event approval
2. Once you receive an approval reminder, click on "Approve"
3. error: {"message":"invalid_type in 'userId': Required"} on https://app.cal.com/api/link?token=[replaced due to privacy]

### Technical details

- Browser version: Sidekick (based on Chrome), but I can reproduce that on any other device
- Node.js version: not relevant, as it's on cal.com

<sub>[CAL-756](https://linear.app/calcom/issue/CAL-756/approval-email-click-on-accept-leads-to-an-error)</sub>

**Comment by oliversum-ch** [comment]
Update: Same if I click on "reject":
`{"message":"invalid_type in 'userId': Required"}`

**Comment by zomars** [comment]
That means that the received email is missing the organizer user id in here: 

https://github.com/calcom/cal.com/blob/b34a568a9306cc16dd7e235dbd537af449c68ee3/packages/emails/src/templates/OrganizerRequestEmail.tsx#L8

**Comment by jdaviescoates** [comment]
I just hit this too. The accept button in the original "awaiting approval" emails work fine, but the ones in the reminder "still awaiting approval" emails don't.

**Comment by zomars** [comment]
> I just hit this too. The accept button in the original "awaiting approval" emails work fine, but the ones in the reminder "still awaiting approval" emails don't.

So we can pinpoint this to the reminder email then. Thanks for clarifying 🙏🏽

**Comment by jdaviescoates** [comment]
> Thanks for clarifying 🙏🏽

You're welcome.

FYI, the only difference in the links seems to be that the tokens in the reminder are shorter. Perhaps they are getting truncated somehow. :man_shrugging:

**Comment by leog** [comment]
Fixed by #6422
