### ISSUE TITLE
[CAL-719] Dependency "next-transpile-modules" is deprecated by Author

### ISSUE THREAD

**Issue by ElTimuro** [calcom/cal.com#6342]
### Is your proposal related to a problem?

No. it should be done, but not pressing. The "next-transpile-modules" dependency is deprecated b the author since it was added to the newest release (13.1) for NextJS: [Next.js 13.1 - Built-in module transpilation (stable)](https://nextjs.org/blog/next-13-1#built-in-module-transpilation-stable)

### Describe the solution you'd like

When updating to Next 13.1 the module should be replaced by the quite elegant built-in solution. Example:

const nextConfig = {
  transpilePackages: ['@acme/ui', 'lodash-es'],
};

module.exports = nextConfig;`

### Describe alternatives you've considered

Since the package is still working it could be left in place, but since unmaintained, the upgrade should be done as soon as next 13.1 is used, which could take a while anyway.

### Additional context

Message from the Author on the [NPM page:](https://www.npmjs.com/package/next-transpile-modules)

`This package has been deprecated
Author message:

All features of next-transpile-modules are now natively built-in Next.js 13.1. Please use Next's transpilePackages option :)`

<sub>[CAL-719](https://linear.app/calcom/issue/CAL-719/dependency-next-transpile-modules-is-deprecated-by-author)</sub>

**Comment by PeerRich** [comment]
yep, we plan to do this + also fix the barrel imports
