### ISSUE TITLE
[CAL-714] caldav speed test when adding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6345]
when adding a caldav calendar [https://app.cal.com/apps/caldav-calendar](https://app.cal.com/apps/caldav-calendar) run an initial speed test and ping the server.

if too slow, send a warning that you may wanna add a different server or upgrade your caldav server

partly fixes [https://github.com/calcom/cal.com/issues/4535](https://github.com/calcom/cal.com/issues/4535)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-714](https://linear.app/calcom/issue/CAL-714/caldav-speed-test-when-adding)</sub>

**Comment by mykeels** [comment]
I get 404 when I try to access https://cal.com/apps/caldav

**Comment by PeerRich** [comment]
whops, https://app.cal.com/apps/caldav-calendar is the correct URL

**Comment by PeerRich** [comment]
@alishaz-polymath do you think this is valuable adding somewhere to caldav? to check connection speed

**Comment by alishaz-polymath** [comment]
Yes. It's on the list of CalDAV experience improvement features I'm currently compiling. definitely useful specially once we've added a timeout/lazy load to CalDAV integration so that it doesn't break the entire app Store/calendar pages
