### ISSUE TITLE
[CAL-717] make switching between "Sign in with Google" and "email + password" easier

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6350]
right now it needs a customer support agent to switch the sign in provider.

Also, if "peer@cal.com" exists as an email + password method, and I sign in with Google Workspace (same email: peer@cal.com) it should work and overwrite the password.

most SaaS apps do that. I think we currently throw an error 

<sub>[CAL-717](https://linear.app/calcom/issue/CAL-717/make-switching-between-sign-in-with-google-and-email-password-easier)</sub>

**Comment by sean-brydon** [comment]
We should be careful - we will require TFA / email verification before we implement this. 

Say you signed up with gmail social signin 

I can currently just create an account as the same email 

This would mean i'd have access to your main account

**Comment by sean-brydon** [comment]
Not sure if this is smart - See security FAQs [https://next-auth.js.org/faq](https://next-auth.js.org/faq)

**Comment by zomars** [comment]
This should be solved by embracing "linking mulitple accounts" https://authjs.dev/reference/adapters/models#account

Also planned for auth.cal.com

**Comment by PeerRich** [comment]
this is by far # 1 customer support ticket

**Comment by PeerRich** [comment]
duplicate
