### ISSUE TITLE
[CAL-722] dark mode spike for dashboard

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6352]
test one day how far we get with dark mode and see if its viable

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-722](https://linear.app/calcom/issue/CAL-722/dark-mode-spike-for-dashboard)</sub>

**Comment by sean-brydon** [comment]
Behind the scenes me and @Jaibles are slowly trying to group all dark/light mode colors together 

Should make this a lot easier

**Comment by PeerRich** [comment]
can you explain this with an example?

**Comment by PeerRich** [comment]
i am trying to explore a way to NOT have className="bg-white dark:bg-black" everywhere

**Comment by PeerRich** [comment]
related: https://twitter.com/peer_rich/status/1612441457943535621
