### ISSUE TITLE
[CAL-726] Collective team event emails - not all team members appear in who section

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#6359]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4da64887-4b94-4ea8-ae55-155a1368c040/bc704d21-0bb1-429d-9acb-cfc019eb8a5b)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-726](https://linear.app/calcom/issue/CAL-726/collective-team-event-emails-not-all-team-members-appear-in-who)</sub>

**Comment by PeerRich** [comment]
upgraded to high priority since it impacts the core product (booking people)

**Comment by kemilbeltre** [comment]
@PeerRich  could provide more details about the users that aren't appearing? Thanks
