### ISSUE TITLE
[CAL-729] adding too many timeslots breaks layout

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6366]
adding all of the time slots also causes the booking object to look like this:

edit:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4742fb66-3f03-4d18-929b-53dc4290799c/376432c9-3ca2-440d-9853-8e7098b419f3)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-729](https://linear.app/calcom/issue/CAL-729/adding-too-many-timeslots-breaks-layout)</sub>

**Comment by zomars** [comment]
It seems images aren't synced to Github 🤔

**Comment by PeerRich** [comment]
this one came from slack, maybe thats why

**Comment by PeerRich** [comment]
added image

**Comment by Udit-takkar** [comment]
final?

**Comment by leog** [comment]
hahah something is wrong with sync-linear, sorry for the spam @Udit-takkar, got the same BTW

**Comment by PeerRich** [comment]
thank you @tedspare for opening an issue
