### ISSUE TITLE
[CAL-734] hide "view recording" button if there is no recording

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6371]
hide this button

![CleanShot 2023-01-10 at 16 03 30@2x](https://user-images.githubusercontent.com/8019099/211586474-63c55f02-e1b1-4a04-a70e-dee5b949f088.jpg)

if there is no recording for the booking

![CleanShot 2023-01-10 at 16 02 33@2x](https://user-images.githubusercontent.com/8019099/211586374-fb1a3eb4-ab6a-4899-9302-610d708b528a.jpg)

<sub>[CAL-734](https://linear.app/calcom/issue/CAL-734/hide-view-recording-button-if-there-is-no-recording)</sub>

**Comment by zomars** [comment]
Not viable, we would need to fetch recordings for each single booking. Would make the overall page very slow. Unless we can batch call them and merge them on the original bookings call.

**Comment by Udit-takkar** [comment]
@zomars there is no batch end point. we would have to call *getRecordingsOfCalVideoByRoomName function on every booking.*

**Comment by Udit-takkar** [comment]
anything i should look into to make this work fast ?

**Comment by PeerRich** [comment]
can we not just write the recording URL into the booking table?

**Comment by Udit-takkar** [comment]
a link is only valid till 12 hrs. i am using [https://docs.daily.co/reference/rest-api/recordings/get-recording-link](https://docs.daily.co/reference/rest-api/recordings/get-recording-link) end point to get new meeting URL whenever user requests.

**Comment by PeerRich** [comment]
if its in the booking table, it wouldnt slow down the UI - it would load like any other entry of booking

**Comment by Udit-takkar** [comment]
@PeerRich i could add a field(viewRecordings) in booking table and mark it as true after recording created webhook is created.  zomars suggested to first try zapier webhooks https://threads.com/34443332158?s=3ZRZHaboWNmBnYFRsnE6Y9.
