### ISSUE TITLE
[CAL-735] Getting 401 Unauthorised while trying to edit event-type

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#6373]
### Issue Summary
https://threads.com/34441034893?s=o8bvFmPgsP8vd6YViAS2Tc

<sub>[CAL-735](https://linear.app/calcom/issue/CAL-735/getting-401-unauthorised-while-trying-to-edit-event-type)</sub>

**Comment by PeerRich** [comment]
upgraded to high priority

**Comment by Udit-takkar** [comment]
@emrysal i think you merged a query to fix this bug for ?

**Comment by emrysal** [comment]
This is fixed
