### ISSUE TITLE
[CAL-737] Location dropdown is overflowing

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#6376]
### Issue Summary
Location dropdown is overflowing in /event-types/:id?tabName=setup

<img width="1440" alt="Screenshot 2023-01-10 at 10 11 32 PM" src="https://user-images.githubusercontent.com/53316345/211610661-388a2d9f-d960-4865-bd65-67c719a543f7.png">

<sub>[CAL-737](https://linear.app/calcom/issue/CAL-737/location-dropdown-is-overflowing)</sub>

**Comment by thomasbrodusch** [comment]
The bug comes from `Select.tsx` which implements [`react-select`](https://github.com/jedwatson/react-select) who seems to be involved here.
We can maybe open a new issue on the `react-select` repository.
