### ISSUE TITLE
[CAL-740] Adding Team Member Potentially Broken

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6381]
When creating a new team and inviting a new team member, even after the new team members creates an account and accepts the invitation to join the team, they are not added to the team.

However, once the team admin removes them from the team and re-adds them, only then does the team actually show up in their account.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-740](https://linear.app/calcom/issue/CAL-740/adding-team-member-potentially-broken)</sub>

**Comment by shirazdole** [comment]
This issue may only result when it's a new user who doesn't already have an account created - worth testing with an already created account user too

**Comment by PeerRich** [comment]
this seems like rather urgent, no?

**Comment by shirazdole** [comment]
This problem was first detected when onboarding a new customer, the new customer - "user A" created a new account, then created a new team, then invited "user b" who did not have an account yet.

User b then went to their email, accepted the invitation, and followed the prompt to create a new account (since they didn't have one yet), when user B logged into their account, there was no sign of the team they were invited to. When user B went back to the invitation email and pressed on it, they were prompted again to create a new account, rather than be taken directly to the account they received the invite to (they were still logged in) this could be a completely different issue as well.

User A then removed them from the team and then re-added them back, with the new invitation email, they were able to then login and see the account they were invited to

**Comment by shirazdole** [comment]
Could these two be related? [https://linear.app/calcom/issue/CAL-779/creating-teams-bug](https://linear.app/calcom/issue/CAL-779/creating-teams-bug)

**Comment by joeauyeung** [comment]
Had a call with @shirazdole. When creating invites via email, the emails were case-sensitive, causing issues. Ex "Joe@cal.com" was not equal to "joe@cal.com". There are other improvements I want to make to the signup page as well, but I'll push this change first.

I shared the specific data in the thread.
