### ISSUE TITLE
[CAL-742] Users receiving two confirmation emails w/ different times

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6382]
When two users are in different timezones, the recipient booking the meeting receives two confirmation emails.

One with THEIR timezone and another with THE OTHER USERS timezone. This is confusing and only one email should be sent out. 

In a perfect world, the one email would say "User A booking at x Time" "User B booking at x Time" so that it's clear to the recipient what time the user they booked the meeting with is at. (i.e. oh this person is running late, "checks email," looks like I booked it for 8a so they probably slept in) 

![CleanShot 2023-01-10 at 10.51.29@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b87c8381-b7be-4e28-a773-cbbb5ee6c12e/8f1a5571-7641-4988-849f-168e02a96fdf)

![CleanShot 2023-01-10 at 10.50.55@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a4b87755-a28f-4203-9de3-b4b42a9d07d6/3bc795e1-9e47-42bc-a1f5-269f0eca13f0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-742](https://linear.app/calcom/issue/CAL-742/users-receiving-two-confirmation-emails-w-different-times)</sub>

**Comment by jacobzukerman** [comment]
We had a user report the same issue this week on a self-hosted instance. I believe one email was in their time local time and the other was UTC.

**Comment by PeerRich** [comment]
upgraded to high, impacts core booking
