### ISSUE TITLE
[CAL-743] Set-up Wizard not pulling correct timezone

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6383]
When creating a new account, the timezone presented is "London," even when the user is not in London. If the user leaves the timezone as London, and then goes through the flow, when they finish the flow, they are prompted to change their timezone to the correct timezone. In my case, it was "LA"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-743](https://linear.app/calcom/issue/CAL-743/set-up-wizard-not-pulling-correct-timezone)</sub>

**Comment by PeerRich** [comment]
just made a new account and experienced this too! lets fix this. @Udit-takkar or @G3root one of you available?

**Comment by PeerRich** [comment]
its during the first screen of onboarding. it always takes "London"
