### ISSUE TITLE
[CAL-746] /event-type settings - Location showing translation string?

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6393]
Currently showing an underlined string

![CleanShot 2023-01-11 at 08.22.07@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/28672a3f-de62-43b4-bd7a-b9562982faaa/e593df2a-5519-43cd-98f4-dcd8cbf1c03b)

Should be

![CleanShot 2023-01-11 at 08.21.52@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a4b07be8-2e17-4ab3-9dd8-86cdf22b8da0/a708850a-ea3c-4938-ada7-2052501fb07a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-746](https://linear.app/calcom/issue/CAL-746/event-type-settings-location-showing-translation-string)</sub>

**Comment by Udit-takkar** [comment]
should be fixed by [https://github.com/calcom/cal.com/pull/6363](https://github.com/calcom/cal.com/pull/6363)
