### ISSUE TITLE
[CAL-750] avatars not showing (+N) people

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6399]
I have a team link with 4 members:

![CleanShot 2023-01-11 at 11.10.29@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2bfef8a4-da1f-4431-bf6b-fc469d313a1f/644cd478-02f5-43c2-8b12-691761e260d5)

but only 3 avatars (1 logo + 2 avatars) are being shown:

![CleanShot 2023-01-11 at 11.11.16@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2a119766-995d-4187-b40f-afe74c9fc600/4f0a6423-0292-4c42-a322-cb011645b529)

they used to overlap and there was also a (+2) Icon if I believe

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-750](https://linear.app/calcom/issue/CAL-750/avatars-not-overlapping-and-not-showing-n-people)</sub>

**Comment by Jaibles** [comment]
Related: [https://linear.app/calcom/issue/CAL-711/component-ui-issue-avatar-grouped-not-overlapping](https://linear.app/calcom/issue/CAL-711/component-ui-issue-avatar-grouped-not-overlapping)
