### ISSUE TITLE
[CAL-758] Booking page availability initially displaying false information

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6402]
### Issue Summary

When going to book a new event, the calendar initially shows all days as available, until the day is clicked on, then it fetches the data and says its fully booked.

### Steps to Reproduce

1. Fill a calendar for a few days, weeks or something.
2. Go to book a new event on one of the blocked days.
3. Day will initially show available until clicked on

Example Video - https://www.loom.com/share/1a5bc8ddee5a48ef98d339cb805c42d1

### Technical details

- Chrome 1.46.153
- Node 16

<sub>[CAL-758](https://linear.app/calcom/issue/CAL-758/booking-page-availability-initially-displaying-false-information)</sub>

**Comment by zomars** [comment]
Would you kindly provide more context? What calendars do you have connected?

**Comment by Hybes** [comment]
Of course, I have an Apple Calendar connected and am expecting the booking page to already be blanked out. In other booking systems, if the organiser is booked out - or away for a week, those days will not be selectable in the first place. 
In cal, what were seeing is the day being selectable, then quickly saying 'nope it's booked' and the day is no longer selectable. 
It should not be selectable in the first place.

**Comment by zomars** [comment]
I also have Apple Calendar and it's working fine here. So we need to dig little deeper. Care to share a booking link to test?

**Comment by Hybes** [comment]
Of course, try this link: https://cnnct.uk/ben/chat
and attempt to book in for any of the days before the 15th, it initially shows available, until you click it - I have blocked it out in my calendar until the 15th

**Comment by alannnc** [comment]
It looks like availability problem here. cc @emrysal I had to change to his initial event type to see the error.

**Comment by Hybes** [comment]
My god, you're right - it's works as expected on my 'Complete Project Launch' page, which was my first created event type

**Comment by zomars** [comment]
@alannnc @Hybes care to elaborate? Does this means that we have and issue with the default event types?

**Comment by Hybes** [comment]
@zomars seems that the function only works on the initial event type. if you click through to https://cnnct.uk/ben/complete - which I imagine was my initial (15 mins meeting), the dates are removed on the first load, where as any of the other pages. e.g. https://cnnct.uk/ben/chat initiallt doesnt load the booked days in my calendar.

**Comment by zomars** [comment]
> @zomars seems that the function only works on the initial event type. if you click through to https://cnnct.uk/ben/complete - which I imagine was my initial (15 mins meeting), the dates are removed on the first load, where as any of the other pages. e.g. https://cnnct.uk/ben/chat initiallt doesnt load the booked days in my calendar.

@emrysal can you take a look at this?

**Comment by Hybes** [comment]
still no movement or response on this one? @zomars @emrysal @PeerRich

**Comment by emrysal** [comment]
There is @Hybes - work is ongoing to refactor in a draft PR right now @ https://github.com/calcom/cal.com/pull/6538 - will be complete soon

**Comment by Hybes** [comment]
excellent, thank you

**Comment by PeerRich** [comment]
pretty sure this has been fixed
