### ISSUE TITLE
[CAL-754] Multiple duration causing issues saving event type settings

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6404]
We've had a few people report issues when trying to save an event type with multiple durations

![CleanShot 2023-01-11 at 10.45.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/335127bd-7f7e-4ca2-8765-e2544e0889d5/fc3be9e2-e034-4630-9015-b5bc9f50f009)

![CleanShot 2023-01-11 at 10.45.24@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/766b2d7c-1515-4cb7-b0bd-04823c2aacee/2a9bdde8-c363-4219-947b-993b69c6ed98)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-754](https://linear.app/calcom/issue/CAL-754/multiple-duration-causing-issues-saving-event-type-settings)</sub>

**Comment by Udit-takkar** [comment]
it is not live yet https://github.com/calcom/cal.com/pull/6378

**Comment by Jaibles** [comment]
Fantastic thanks @Udit-takkar 🙏
