### ISSUE TITLE
[CAL-755] Editing/Adding Webhooks UI Design - Layouts, spacing & type issues.

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6414]
A lot of issues, particularly around the ping test area where font sizes are all over the place.

**Currently:**

![CleanShot 2023-01-11 at 16.07.59@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/aec27729-2a78-48b0-8937-3794a14d6967/8f74d603-b123-4df9-b831-c99ce3c32040)

**Should be**

![CleanShot 2023-01-11 at 16.08.24@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0c032565-55e4-4e33-a972-684d7aae6de2/cb179bdd-916a-4167-a7f9-e8c584f18fe4)

[Settings/ Developer/ Webhooks/Add - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A59917&t=3hNynQ6hBKZ73ols-1)

I'll add more spec shortly but if anyone can see the issues by comparing with the designs feel free to take on.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-755](https://linear.app/calcom/issue/CAL-755/editingadding-webhooks-ui-design-layouts-spacing-and-type-issues)</sub>

**Comment by joeshajan** [comment]
Hey, @Jaibles I found the differences. I would like to work on this issue. Can you assign this to me?

![CURRENT](https://user-images.githubusercontent.com/69904519/212020155-003b196f-1cca-4c74-abbc-319930c15ea6.jpg)

**Comment by PeerRich** [comment]
![CleanShot 2023-01-12 at 21 43 50@2x](https://user-images.githubusercontent.com/8019099/212176957-f9cae6f4-51e7-4572-9d7b-0abd1911721f.jpg)

@Jaibles are you sure to delete that switch?

**Comment by zomars** [comment]
> ![CleanShot 2023-01-12 at 21 43 50@2x](https://user-images.githubusercontent.com/8019099/212176957-f9cae6f4-51e7-4572-9d7b-0abd1911721f.jpg)
> 
> @Jaibles are you sure to delete that switch?

I was going to comment this. We need this. Althought we could enable/disable from the listing itself.

**Comment by Jaibles** [comment]
> > ![CleanShot 2023-01-12 at 21 43 50@2x](https://user-images.githubusercontent.com/8019099/212176957-f9cae6f4-51e7-4572-9d7b-0abd1911721f.jpg)
> 
> > 
> 
> > @Jaibles are you sure to delete that switch?
> 
> 
> 
> I was going to comment this. We need this. Althought we could enable/disable from the listing itself.

Yea sorry meant to comment about that. I was questioning whether on creation we should just enable by default and you can turn it off from the webhooks screen or by editing. Don't mind leaving it though.

**Comment by joeshajan** [comment]
> > > ![CleanShot 2023-01-12 at 21 43 50@2x](https://user-images.githubusercontent.com/8019099/212176957-f9cae6f4-51e7-4572-9d7b-0abd1911721f.jpg)
> > 
> > 
> > > 
> > 
> > 
> > > @Jaibles are you sure to delete that switch?
> > 
> > 
> > I was going to comment this. We need this. Althought we could enable/disable from the listing itself.
> 
> Yea sorry meant to comment about that. I was questioning whether on creation we should just enable by default and you can turn it off from the webhooks screen or by editing. Don't mind leaving it though.

Yeah got it will keep that in mind.
