### ISSUE TITLE
[CAL-757] UI Dropdown menu's are inconsistent all over the app

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6417]
It's all detailed in Figma: 

[   ↳ Dropdown menu - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=1359%3A151225&t=3hNynQ6hBKZ73ols-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-757](https://linear.app/calcom/issue/CAL-757/ui-dropdown-menus-are-inconsistent-all-over-the-app)</sub>

**Comment by joeshajan** [comment]
So is this the right way to do?

![image](https://user-images.githubusercontent.com/69904519/211975568-43a3bb59-331b-457b-b9da-a2880c0afab4.png)

**Comment by Jaibles** [comment]
Correct @joeshajan. We have a dropdown component. It should look like this and be used everywhere in the app our dropdowns are used.

**Comment by sean-brydon** [comment]
![image](https://user-images.githubusercontent.com/55134778/212172156-fc809499-4807-4fd6-b318-13b1dd447490.png)
https://app.cal.com/event-types/[type]

![image](https://user-images.githubusercontent.com/55134778/212172300-a3053e27-4198-46ab-8d2d-aef3fa7fd482.png)
https://app.cal.com/teams 

both have weird hover states applied to them. I know there was a few more  @Jaibles mentioned in the figma file

**Comment by PeerRich** [comment]
nice!
