### ISSUE TITLE
[CAL-760] Emails: Design Tokens are not update to 2.0

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6426]
![CleanShot 2023-01-12 at 10.28.42@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/01c6fa65-19aa-4d86-ad48-79fc666a63a4/1374dfa1-209c-4947-9630-09fb08225e78)

All our emails appear to have the old flat gray colour, and old border radius. The background colour is #f5f5f5 for example.

Should be:

![CleanShot 2023-01-12 at 10.34.05@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/077ca5d7-18f8-4993-83dc-b24a750b00fd/b7272cbb-58ea-474d-855c-74178551de6e)

[View in Figma](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=13%3A20721&t=07TnV6783hWGav4o-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-760](https://linear.app/calcom/issue/CAL-760/emails-design-tokens-are-not-update-to-20)</sub>

**Comment by gitstart-calcom** [comment]
Hi @Jaibles! Is this issue just about updating the background color and border radius or update the layout design as well? Please confirm

**Comment by Jaibles** [comment]
Hey @gitstart-calcom just update colours & border radius. Also double check the text for colours please 🙏 Thanks for clarifying
