### ISSUE TITLE
[CAL-768] Analytics on Public Profile page

### ISSUE THREAD

**Issue by paragkatoch** [calcom/cal.com#6431]
### Is your proposal related to a problem?

There are ways to add analytics for event types but there isn't any way to add analytics on public profile page

### Describe the solution you'd like

There can be a way to add analytics to public profile page by giving option in settings

<sub>[CAL-768](https://linear.app/calcom/issue/CAL-768/analytics-on-public-profile-page)</sub>

**Comment by PeerRich** [comment]
@hariombalhara we should add all analytics apps also to the profile page: cal.com/peer
