### ISSUE TITLE
[CAL-764] Allow workflow templating

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#6435]
Allow a way to create templates on workflows which can be re-used in multiple workflows

cc: @CarinaWolli @PeerRich

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-764](https://linear.app/calcom/issue/CAL-764/allow-workflow-templating)</sub>

**Comment by CarinaWolli** [comment]
Just want to add. This would also be nice to have team-wide. So that for example the admin of a team can create custom templates, that the whole team can reuse

**Comment by alishaz-polymath** [comment]
Precisely @CarinaWolli 🙌
