### ISSUE TITLE
[CAL-765] Allow Global workflows in teams

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#6436]
The ability to use same workflow for every member in the team where the Admin/Owner is the only one who can modify the workflow.

cc: @CarinaWolli @PeerRich

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-765](https://linear.app/calcom/issue/CAL-765/allow-global-workflows-in-teams)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli you are currently working on team workflows, no?

**Comment by CarinaWolli** [comment]
We already have team workflows 🙌🏻
