### ISSUE TITLE
Timeslots component does not move up on some mobile devices

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#6449]
1.  When I navigate to  Cal.com from the following mobile devices
iPhone from iOS, v15.2 to iOS, v14.4
Android - from v12.0 to v7.0
2. And choose the date 
3.  Then the timeslots component does not move up and I have to scroll the page to see the timeslots component
4. But when I navigate to Cal.com from the following  mobile devices
iPhone iOS v16.0
iPhone iOS v16.2
iPhone iOS  v16.1
5. Then  the timeslots component moves up and the calendar is no longer displayed

Expected result: The timeslots component should move up and become visible on all  mobile screens

**Comment by aasargsian** [comment]
A few additional notes: this is an iFrame inline embed.

Here is the screen recording of the bug: 
https://user-images.githubusercontent.com/33749906/212273762-8ea23c00-a319-46e7-8066-e32e4d40583e.mp4

And the screenrecording of the expected behaviour:
https://user-images.githubusercontent.com/33749906/212277820-cd4ffe2b-f541-4da8-bdc1-b25a3a3abc2e.mp4

**Comment by PeerRich** [comment]
@hariombalhara this is interesting. it scrolls as intended but somehow you cant scroll back up again. maybe an overflow:hidden issue when using the embed?

**Comment by aasargsian** [comment]
@PeerRich The automatic scrolling also doesn't seem to work for certain devices as you can see in this video: https://user-images.githubusercontent.com/33749906/212273762-8ea23c00-a319-46e7-8066-e32e4d40583e.mp4

Devices:
iPhone from iOS, v15.2 to iOS, v14.4
Android - from v12.0 to v7.0

**Comment by PeerRich** [comment]
that is very weird. we cant reproduce this locally. are you calling this embed in some sort of container that has maybe overflow:hidden or similar?

**Comment by PeerRich** [comment]
if this doesnt get solved, maybe just link to your booking page with a button for now. that way its not a blocker

**Comment by PeerRich** [comment]
@Shahane-Aloyan can you try again?
