### ISSUE TITLE
 Iframe not loading for iOS13.3 and less

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#6450]
When I go to the Cal.com page from the following mobile devices
iPhone 11 v13.3
iPhone XS v12.1
iPhone X v11.2
iPhone 7 v10.3
Then the page doesn't load.

**Comment by PeerRich** [comment]
can you send the link you were visiting here?

**Comment by aasargsian** [comment]
@PeerRich Sure!

Link: https://rdv.sleepdoctor.me/
We use inline embed HTML version.
Recording: https://user-images.githubusercontent.com/33749906/212287452-8290aae3-cae0-4f49-a34f-15d6fb4c129d.mp4

**Comment by aasargsian** [comment]
@PeerRich just checking if the issue got reproduced? I shared the recording above
