### ISSUE TITLE
[CAL-773] Localisation in iframe

### ISSUE THREAD

**Issue by Shahane-Aloyan** [calcom/cal.com#6451]
1. When I navigate to the booking page from a mobile device
2. And  the language of the phone is French
3. Then  the page is in English
4. But when I choose the date
5. Then it updated to French
6. And the capital letter of the month and weekday get updated to small letters

Expected result:  If the language has changed, then I should see the page in that language instantly
                            The month and the day of the week should always be capitalized

<sub>[CAL-773](https://linear.app/calcom/issue/CAL-773/localisation-in-iframe)</sub>

**Comment by aasargsian** [comment]
Additional note: this localisation bug was initially noticed for iframe inline embed

When I try on my phone, it get initially loaded in English. But when I close the app and reopen it OR I choose a date - widget gets localaised. 

Here is the recording: https://user-images.githubusercontent.com/33749906/212280085-faf2cc30-f9e5-4565-89b6-ef282229d1aa.MP4

**Comment by PeerRich** [comment]
@hariombalhara

**Comment by hariombalhara** [comment]
@aasargsian I think the issue is because localisation kicks in on client side and it gets a little late because it requests translations from client.

Can you just wait on the page and see if the page is translated automatically without clicking on the dates?

**Comment by hariombalhara** [comment]
@PeerRich Because the booking page is statically generated it can only be translated into English server side and then preferred translation happens at client. So, there comes a delay in translation

**Comment by aasargsian** [comment]
@hariombalhara yes, seems like the localisation happens with a delay. It's just not ideally since vast majority of our users are French

**Comment by arturoovf** [comment]
Well I Just have same/similar problem with iframe language, it appears English only and is not changing even if I wait there, it stays English.  Mail sent to the user is English as well but Mail sent to organizator is correct language.
