### ISSUE TITLE
[CAL-774] Calendar widget on iPads

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#6452]
Short description of the issue:

For some devices on a page with embedded iFrame the timeslots become invisible after being chosen the second time.

**Environment:**
- Chrome/Safari on iPad Pro 11 2022 v16.0 Viewport 834 X 1075 px
- Chrome/Safari on iPad Pro 12.9 2022 v16.0 Viewport 1024 x 1292 px

**Steps to reproduce:**
1. Navigate to a page with embedded inline iframe from iPad (exact devices listed above)
3. Click on one of the dates from the calendar
4. Click on another date

**Actual Result:** When a date is selected  a second time,  the time slots component moves up and **becomes invisible**
**Expected Result**: The timeslots in iFrame should be visible

Recording: 
https://user-images.githubusercontent.com/33749906/212281901-a75f0a70-a39e-494b-85ac-a12ad5e6bf5d.mp4

<sub>[CAL-774](https://linear.app/calcom/issue/CAL-774/calendar-widget-on-ipads)</sub>

**Comment by PeerRich** [comment]
is this the official embed? or just an iframe? 

we have a js embed script and a react component

**Comment by Mordorreal** [comment]
@PeerRich It's iframe which use selfhosted backend. 

`<iframe class="cal-embed" name="cal-embed" src="https://*/teleconsultation/embed?email=&amp;++++metadata%5ButmCampaign%5D=null&amp;++++metadata%5ButmSource%5D=null&amp;++++metadata%5ButmMedium%5D=null&amp;++++metadata%5ButmContent%5D=null&amp;++++metadata%5ButmTerm%5D=null&amp;embed=&amp;__autoScroll=false&amp;embedType=inline" style="height: 424px; width: 100%;"></iframe>`

**Comment by aasargsian** [comment]
@PeerRich 
The use the embed code from the web app from the HTML tab. 
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/33749906/212288219-b5e47116-87dd-4f5f-a394-8feb1de53af1.png">

Link: https://rdv.sleepdoctor.me/

**Comment by PeerRich** [comment]
weird. i cant reproduce this but it seems like something wrong is up. cc @hariombalhara

**Comment by PeerRich** [comment]
Oh I may know why. We have a scrollTo() trigger when clicking a day and it seems like the outside container is too big so it scrolls to the bottom. 

@hariombalhara we should only trigger the scrollTo on mobile

**Comment by PeerRich** [comment]
this fix goes live in the next weeks release
