### ISSUE TITLE
[CAL-775] user session does not get updated when subscribed to teams plan

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#6455]
### Issue Summary

After any user subscribes to teams plan session?.data?.user?.belongsToActiveTeam still returns false but only gets updated after user logs out and log in again.

<sub>[CAL-775](https://linear.app/calcom/issue/CAL-775/user-session-does-not-get-updated-when-subscribed-to-teams-plan)</sub>

**Comment by zomars** [comment]
I don't think `belongsToActiveTeam` should live in the session at all. That should come from the `me` query as it should be always fresh or cached. cc @sean-brydon
