### ISSUE TITLE
[CAL-777] We could not add the office365video meeting link to your scheduled event.

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6461]
![CleanShot 2023-01-13 at 14 09 22@2x](https://user-images.githubusercontent.com/8019099/212327402-0c4196ac-753c-48c0-b1a7-d7a6bc2bec7d.jpg)

ticket: https://secure.helpscout.net/conversation/2123913636/2455?folderId=6459017

<sub>[CAL-777](https://linear.app/calcom/issue/CAL-777/we-could-not-add-the-office365video-meeting-link-to-your-scheduled)</sub>

**Comment by PeerRich** [comment]
@joeauyeung are you aware of ongoing issues with `office365video` integration?

**Comment by joeauyeung** [comment]
@PeerRich thanks for the heads up. I added extra logging details and cherry picked it into prod so I'm keeping an eye out on that.

**Comment by joeauyeung** [comment]
Fixed w/ #6607
