### ISSUE TITLE
[CAL-778] Plausible not working

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#6462]
Plausible can't work as it uses {TRACKING_DOMAIN} as variable and BookingPageTagManager doesn't understand this variable.

<sub>[CAL-778](https://linear.app/calcom/issue/CAL-778/plausible-not-working)</sub>

**Comment by PeerRich** [comment]
should be a quickfix, no? wanna work on it?

**Comment by hariombalhara** [comment]
`BookingPageTagManager` now supports any dynamic variable. So, we can choose variable names as we see fit with following restriction:
Should be uppercase only. Can have _ and numbers only in addition to A-Z
