### ISSUE TITLE
[CAL-781] Embed/Timezone select positioning

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#6469]
Reported in slack when trying to select timezone select goes out of frame.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/434d82b0-c77c-49e4-a179-f218a3742825/2d1aa857-626a-4eb3-bd0b-e9d2d262e1e1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-781](https://linear.app/calcom/issue/CAL-781/embedtimezone-select-positioning)</sub>

**Comment by PeerRich** [comment]
we wanna replace this dropdown anyway and immediately show the select

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/issues/5301 this one

**Comment by PeerRich** [comment]
I believe this was fixed. can you try again?
