### ISSUE TITLE
[CAL-782] creating an event-type called “book” throws an error (/book is an API endpoint)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6472]
we would need to either re-route it or forbid the use of “book”

preferably the first

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-782](https://linear.app/calcom/issue/CAL-782/creating-an-event-type-called-book-throws-an-error-book-is-an-api)</sub>

**Comment by PeerRich** [comment]
first reported https://twitter.com/codingwithmanny/status/1613844100746199042?s=46&t=fOnOWwxi3zWEejwVizFOaA

**Comment by michael-azogu** [comment]
or append the user input with a zero width space if it's called book

**Comment by michael-azogu** [comment]
> we would need to either re-route it or forbid the use of “book”
> 
> preferably the first
> 
> <sub>From [SyncLinear.com](https://synclinear.com) | [CAL-782](https://linear.app/calcom/issue/CAL-782/creating-an-event-type-called-book-throws-an-error-book-is-an-api)</sub>

or append the user input with a zero width space if it's called book

**Comment by PeerRich** [comment]
> or append the user input with a zero width space if it's called book

interesting ...

**Comment by michael-azogu** [comment]
on second thought I don't know about the details. that was just the first thing that popped into my mind

**Comment by gitstart-calcom** [comment]
If we would have to modify the event name in any way, wouldn't it be better to forbid the use in the first place to make things easier for future use? cc: @PeerRich

**Comment by PeerRich** [comment]
i am not sure. would need to pass this question to another dev

**Comment by PeerRich** [comment]
discussing now

**Comment by PeerRich** [comment]
we'll get rid of the /book endpoint with @JeroenReumkens help

**Comment by zomars** [comment]
> we'll get rid of the /book route with @JeroenReumkens help

I'm working on that BTW @PeerRich https://github.com/calcom/cal.com/pull/6656
