### ISSUE TITLE
[CAL-788] downloading an .ics with zoom link shows "integration:daily"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6478]
very odd, when downloading the .ics of an event with zoom it says

location = integrations:daily

it should show the zoom link instead

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bbc52596-c8ea-4737-9c75-befe66adb2f2/5d9d7a28-1043-4a3d-8451-92be49509f14)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-788](https://linear.app/calcom/issue/CAL-788/downloading-an-ics-with-zoom-link-shows-integrationdaily)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar wanna look into this? it should obviously show the zoom link (or whatever link was selected)

not sure why it even shows integration:daily

**Comment by Udit-takkar** [comment]
<img width="573" alt="Screenshot 2023-01-28 at 1 31 25 AM" src="https://user-images.githubusercontent.com/53316345/215186074-fbc9dcb2-2623-4769-97b7-93c120496094.png">

@PeerRich why exactly are we displaying this even when event does not require confirmation ?

**Comment by PeerRich** [comment]
> <img alt="Screenshot 2023-01-28 at 1 31 25 AM" width="573" src="https://user-images.githubusercontent.com/53316345/215186074-fbc9dcb2-2623-4769-97b7-93c120496094.png">
> 
> @PeerRich why exactly are we displaying this even when event does not require confirmation ?

it's wrong. we should always show it there

**Comment by PeerRich** [comment]
unless requires confirmation

**Comment by PeerRich** [comment]
i dont know why we built it this way
