### ISSUE TITLE
[CAL-791] tablet: sidebar profile dropdown trigger too wide and not centered

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6484]
https://user-images.githubusercontent.com/8019099/212493676-fca55045-3876-4639-ad87-1dbff6b48f94.mp4

should be:
![CleanShot 2023-01-14 at 20 50 42@2x](https://user-images.githubusercontent.com/8019099/212493671-398629e6-fb3c-4412-9630-cbb3e2899e85.jpg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-791](https://linear.app/calcom/issue/CAL-791/tablet-sidebar-profile-dropdown-trigger-too-wide-and-not-centered)</sub>

**Comment by gitstart-calcom** [comment]
Hi @PeerRich! Is this issue resolved now?

**Comment by PeerRich** [comment]
> Hi @PeerRich! Is this issue resolved now?

yes
