### ISSUE TITLE
Build Error when building from root dir

### ISSUE THREAD

**Issue by timowevel1** [calcom/cal.com#6485]
Hey,

we just bought the enterprise license but we face build problems...

I am at the root dir, run yarn build. It builds successful: Tasks:    8 successful, 8 total

Related to https://github.com/calcom/cal.com/issues/4948?

When I try yarn start, it says: Error: Could not find a production build in the '/root/cal.com/apps/web/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

Any ideas?

**Comment by PeerRich** [comment]
we'll investigate!

**Comment by PeerRich** [comment]
@zomars

**Comment by timowevel1** [comment]
Fixed by ignoring typescript errors
