### ISSUE TITLE
[CAL-795] Promo Codes for Teams

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6494]
Ability to create, share, and/or apply promo codes to teams either through % discount or offering # of seats for free

Created via Threads. See full discussion: [https://threads.com/34442257352](https://threads.com/34442257352)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-795](https://linear.app/calcom/issue/CAL-795/promo-codes-for-teams)</sub>

**Comment by PeerRich** [comment]
i always thought this worked already, no? @joeauyeung  can you checkout the team upgrade stripe flow and see if there is a promo code input?

**Comment by joeauyeung** [comment]
Confirmed there is an input for promo codes
![image](https://user-images.githubusercontent.com/65426560/212713446-dae8bf3f-a34d-4498-ba5e-f8c09ae96f29.png)

**Comment by PeerRich** [comment]
can you DM me which code doesnt work?

**Comment by shirazdole** [comment]
This has been resolved 🙏🏽 — there's an additional step in Stripe to add the promocode after initial creation
