### ISSUE TITLE
Broken cancellation for disabled success page

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#6497]
**Short description**
When [success page is disabled in the settings](https://github.com/calcom/cal.com/pull/6225), both host and attendees are unable to reschedule or cancel bookings. 
We expected success page to be disabled for booking, not cancellation.

**Steps to reproduce**
For host:

1. Navigate to the “Bookings” page
2. Click on the “Cancel” button for any booking

For attendee:

1. Navigate to booking confirmation email
2. Click on the “Cancel” button in the email
 
Actual result: I am redirected to a redirect URL from settigns. The booking is not canceled. 
Expected result: I should not be redirected to a success page when cancelling. The booking should be cancelled.

Recording: https://www.loom.com/share/618193a816804218accb9850cd5703f5

**Comment by hariombalhara** [comment]
@aasargsian Fixed the cancellation flow in the PR(looms attached there). Reschedule was already working unless I am missing something.
