### ISSUE TITLE
Webhook is not called during dynamic group meetings

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#6499]
### Issue Summary

webhook is not called during booking a dynamic group meetings

### Steps to Reproduce

1. Create a Webhook that calls something
2. Create a meeting with a dynamic link

**Comment by PeerRich** [comment]
thats intended, I dont think we have an option to do that yet. we'd need to investigate

**Comment by PeerRich** [comment]
i dont think this is planned due to technical limitations of dynamic booking links
