### ISSUE TITLE
[CAL-798] mobile: /event-types - tabs for teams

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6501]
* [ ] fix margin
* [ ] add tabs for teams (if available. if no teams, hide tabs)

![CleanShot 2023-01-16 at 10.51.18@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/efd734b5-9165-43a3-9f51-cdb27f005c2d/70d07c67-98c7-491c-abb3-303ae10a289f)

bad, too much margin:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9534c56a-99b4-4397-8aa9-fb84b3496bfe/1f4b4a29-eee7-449a-9fea-8215e754b747)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-798](https://linear.app/calcom/issue/CAL-798/mobile-event-types-tabs-for-teams)</sub>

**Comment by G3root** [comment]
@Jaibles what should be the purpose of the tab ?

**Comment by Jaibles** [comment]
Uploading CleanShot 2023-01-16 at 12.52.06.mp4…

**Comment by PeerRich** [comment]
do we want the tabs on desktop too?

**Comment by Jaibles** [comment]
I would say hold off on doing it for desktop yet. We'll look at a more full scale approach to solving this and ensure it will work for our plans in routing forms & workflows too.
