### ISSUE TITLE
[CAL-799] Teams: Workflows

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6502]
Separate team & personal event types like Event Types. [View in Figma](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=709%3A126680&t=gMu9ySHjCDpBskBP-1)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c60f3e91-61b7-4697-9520-aa19f7a14007/a59d3528-7e47-4fbb-ba34-bb08fb4d7d22)

[Workflows - Cal.com Teams (Figma)](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=709%3A126680&t=gMu9ySHjCDpBskBP-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-799](https://linear.app/calcom/issue/CAL-799/teams-workflows)</sub>

**Comment by PeerRich** [comment]
reuse the same event-types component
