### ISSUE TITLE
[CAL-803] /insights

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6507]
figma: https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=514%3A80787&t=h4kM3EyGKfIPY9o8-4

![CleanShot 2023-01-16 at 14 51 05@2x](https://user-images.githubusercontent.com/8019099/212693685-c8a75e85-7157-41f7-9525-193545a346c0.jpg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-803](https://linear.app/calcom/issue/CAL-803/analytics)</sub>

**Comment by Jaibles** [comment]
@PeerRich passing along specific data/chart requests from a customer:

* How many booking have been made in specific time slot at given showroom
* How many customer have cancel their appointment both showroom and time slot
* average cancel rate
