### ISSUE TITLE
[CAL-811] Avatar icon not redirecting user back to the main page.

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6514]
### Issue Summary

The booking page used to have the avatar clickable and take you back to the list of events, now the button wont click or take you anywhere.

### Steps to Reproduce

Go to booking page, click on to one, see that the avatar icon isn't clickable and wont redirect you back a page, when it should / used to.

### Technical details

- Latest Chrome
- Node 16

<sub>[CAL-811](https://linear.app/calcom/issue/CAL-811/avatar-icon-not-redirecting-user-back-to-the-main-page)</sub>

**Comment by PeerRich** [comment]
I agree this used to work. regressing. let me assign someone

**Comment by PeerRich** [comment]
@gitstart-calcom 

this avatar for solo events should link back to cal.com/peer

![CleanShot 2023-01-17 at 14 34 42@2x](https://user-images.githubusercontent.com/8019099/212912555-b7122dde-2802-498a-8cce-3215b35ee363.jpg)
