### ISSUE TITLE
[CAL-805] /app-store - ordering of apps in "all apps" section seems random

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6515]
Ordering of apps in all apps is not alphabetical, I can't work out if there's any logic to the ordering but assuming not, can we make them alphabetical.

![CleanShot 2023-01-17 at 07.04.38@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c6cd0b0d-1c77-4c48-ac44-624ac17bccc6/be8b8dc7-572d-4efb-a8bc-78e982ebe7e7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-805](https://linear.app/calcom/issue/CAL-805/app-store-ordering-of-apps-in-all-apps-section-seems-random)</sub>

**Comment by Jaibles** [comment]
@leog was there any logic to this that I'm missing?

**Comment by PeerRich** [comment]
is it important?

**Comment by leog** [comment]
@Jaibles I don't think there is any order, no.

**Comment by PeerRich** [comment]
i dont htink we need an order ,but  a better ticket would be to change "Trending Apps" to "Most Popular" and order by installations

**Comment by Jaibles** [comment]
https://github.com/calcom/cal.com/issues/6528
