### ISSUE TITLE
[CAL-813] Change "Trending Apps" to "Most Popular" and order by installations

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6528]
We currently have a duplicated section in that Trending apps mimic the apps order below

![CleanShot 2023-01-17 at 12.52.24@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0f3253ff-3037-4889-92f3-27852109ce5e/bb29f9b3-7326-4bf9-b0f4-08320055a2e9)

Change the Trending apps section to have the most popular apps. Use the installation count to pick them out.

Also fix this alignment issue while in there

[ad13200b-d6ce-4106-9ecb-a39ffb2fb6e9](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/20acf146-fa2a-4f47-aeb9-c1c5008851b0/ad13200b-d6ce-4106-9ecb-a39ffb2fb6e9)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-813](https://linear.app/calcom/issue/CAL-813/change-trending-apps-to-most-popular-and-order-by-installations)</sub>

**Comment by Udit-takkar** [comment]
@hariombalhara can we get number of installation of any app ? where do we store it ?

**Comment by hariombalhara** [comment]
Yup, credential has an entry for every install.

**Comment by Udit-takkar** [comment]
so we want we want to show on the /apps is globally trending apps which includes installation by all the users.  won't this slow down the app as there would be too many records?
