### ISSUE TITLE
[CAL-814] /book endpoint can't be directly embedded.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#6529]
Hi guys, can someone help me?
I just want to open the link '/omgitsshark/book?type=7&amp;date=2023-01-17T13%3A30%3A00%2B01%3A00&amp;slug=30min&amp;count=12&amp;getsignature' in embed solution by calLink but recieve 404 page, if I visit link directly(<https://staging.cal.profi.io/omgitsshark/book?type=7&amp;date=2023-01-17T13%3A30%3A00%2B01%3A00&amp;slug=30min&amp;count=12&amp;getsignature>) - all is fine. Also I want to extend Cal init payload to pass user information when user authorized in our application, do you have documentation about this?

[Slack Message](https://calendso.slack.com/archives/C04ACKUDN30/p1673952690235209?thread_ts=1673952690.235209&cid=C04ACKUDN30)

<sub>[CAL-814](https://linear.app/calcom/issue/CAL-814/book-endpoint-cant-be-directly-embedded)</sub>

**Comment by hariombalhara** [comment]
I think I found the issue, you want to directly open /book which is something I didn't expect users would do. Will have to handle it.
Normally the flow is that the booker would pick the timeslot which is the previous page and from there onwards the flow works

**Comment by JeroenReumkens** [comment]
@hariombalhara  Also take into account that when the new booker is done, both the datepicker + booking form will be on one page. So from that moment on the /book page won't exist anymore.

**Comment by hariombalhara** [comment]
We don't want to support embedding it. See [https://github.com/calcom/cal.com/pull/7801#issuecomment-1486440101](https://github.com/calcom/cal.com/pull/7801#issuecomment-1486440101)
