### ISSUE TITLE
Round robin: optimize for equal distribution

### ISSUE THREAD

**Issue by TymonSliwinski** [calcom/cal.com#6536]
### Is your proposal related to a problem?

Optimizing for equal distribution allows for the most even distribution of meetings across hosts. This way no member will be behind in number of meetings.

### Describe the solution you'd like

Calendly has their own solution [here](https://help.calendly.com/hc/en-us/articles/4402432846999-How-does-round-robin-distribution-work-#how-does-optimize-for-availability-work--0-1)

**Comment by PeerRich** [comment]
this is almost done @TymonSliwinski

**Comment by emrysal** [comment]
This got very complicated very quickly in the old slot logic, but we've rewritten that from scratch - a new version of this pr will go in in 3.2
