### ISSUE TITLE
[CAL-818] when impersonating wrong username is displayed shown in sidebar

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#6542]
### Issue Summary

![image](https://user-images.githubusercontent.com/53316345/213142871-33d7c12f-e068-458c-9ea9-e040eff388a7.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

<sub>[CAL-818](https://linear.app/calcom/issue/CAL-818/when-impersonating-wrong-username-is-displayed-shown-in-sidebar)</sub>

**Comment by PeerRich** [comment]
pretty low prioirty, impersonating is mostly relevant for us

**Comment by sean-brydon** [comment]
I also can't replicate this - @shirazdole is this something youve seen before? Or was it just a one off?

**Comment by Udit-takkar** [comment]
@shirazdole reported this in the #engineering channel
