### ISSUE TITLE
[CAL-819] Date overrides not working on days you have two or more availability blocks

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6546]
You can't create a date override on a day your availability consists of two (or more) availability blocks

![Screenshot 2023-01-18 at 12.23.39.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7204b059-4921-4e8b-8eeb-2abddf2240c8/67508c25-df7f-467a-957d-cdb04c3a9277)

![Screenshot 2023-01-18 at 12.23.09.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6de1f999-1f75-4ed8-a95f-93b63e8f4d47/8f45b7a5-28f8-4572-bf15-053ca9993101)

Created via Threads. See full discussion: [https://threads.com/34441038456](https://threads.com/34441038456)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-819](https://linear.app/calcom/issue/CAL-819/date-overrides-not-working-on-days-you-have-two-or-more-availability)</sub>

**Comment by emrysal** [comment]
Looking into this now, it doesn't seem to overwrite the second block properly 🔬
