### ISSUE TITLE
[CAL-822] issue with "seat" bookings

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6551]
Hey there, I created two event types Home Return & Home Exchange where 5 people can book a seat every day for their return. When someone books it replaces the person that booked previously I don’t get it 😬

[https://secure.helpscout.net/conversation/2128702483/2494/](https://secure.helpscout.net/conversation/2128702483/2494/)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-822](https://linear.app/calcom/issue/CAL-822/issue-with-seat-bookings)</sub>

**Comment by joeauyeung** [comment]
Closing - using seats feature not for its intended use
