### ISSUE TITLE
[CAL-825] Breakpoint mismatch on event type edit view

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6557]
### Issue Summary

Found a bug while streaming:

https://www.twitch.tv/videos/1711398308

### Steps to Reproduce

1. Edit an event type
2. Size your window to 1265px (IDK why only here happens)
3. Navigate through tabs

<sub>[CAL-825](https://linear.app/calcom/issue/CAL-825/breakpoint-mismatch-on-event-type-edit-view)</sub>

**Comment by PeerRich** [comment]
this is weird. @Udit-takkar wanna take a look?

**Comment by Udit-takkar** [comment]
<img width="1188" alt="Screenshot 2023-05-22 at 4 13 31 PM" src="https://github.com/calcom/cal.com/assets/53316345/90af9fd1-6ea1-4232-88c1-d269de367ce9">

@PeerRich i think this has been fixed
