### ISSUE TITLE
[CAL-830] `{{eventType}}` not parsed in "Awaiting Approval" email subject

### ISSUE THREAD

**Issue by c-ehrlich** [calcom/cal.com#6562]
### Issue Summary

I got an email that had the handlebars (?) variable for `{{eventType}}` in the title. The meeting is type is just the default 30-minute meeting that comes with a new account, except that I made it confirmation required.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/8353666/213387383-2ed61323-d9c9-4a30-8ca1-a972af7037ec.png">

### Steps to Reproduce

1. add "confirmation required" to the default 30 minute event
2. have someone book it, and wait for the "Awaiting Approval" email

<sub>[CAL-830](https://linear.app/calcom/issue/CAL-830/eventtype-not-parsed-in-awaiting-approval-email-subject)</sub>

**Comment by PeerRich** [comment]
a fix has been applied 3 days ago, will go live today https://github.com/calcom/cal.com/pull/6496

**Comment by PeerRich** [comment]
@G3root is working on it and @emrysal will merge today
