### ISSUE TITLE
[CAL-828] Add analytics on Routing Form and Profile Page

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#6564]
supersedes #6431 
<sub>[CAL-828](https://linear.app/calcom/issue/CAL-828/add-analytics-on-routing-form-and-profile-page)</sub>

**Comment by hariombalhara** [comment]
Adding support to Profile page is straightforward as that page is eventType page only and we probably just need to add `<BookingPageTagManager eventType={eventType} />`

But a Routing Form has no context of EventType, it can redirect to any EventType. So, it seems that to enable analytics per Routing Form, we need per Routing Form - EventType App configuration cc @PeerRich 

I am also thinking wouldn't people want the same analytics for all their EventType and Routing Forms, why provide per eventType configuration for this?

**Comment by PeerRich** [comment]
Yeah i know what you mean. What if Apps can have multiple settings? Maybe we just show the Routing Form Settings, too

**Comment by alkarimlalani** [comment]
Here's a real-life use case - check out how we've embedded it on our site: https://www.rollout.com/get-started
One routing form can send you to two different events. If you're adding analytics, there's a high chance you're doing it for inbound sales/contact form and want both Google Analytics/Google Tag Manager to work across all your routing forms (now that you can chain them) as well as across your various events. Global config here would be intuitive & help me not forget to config an event when I update the embedded form.

**Comment by hariombalhara** [comment]
@PeerRich That still doesn't solve the problem. 

I configure Routing Form with Tracking ID 1
Routing Form takes to the EventType configured with Tracking ID 2.

The journey would be broken for both tracking IDs.

**Comment by PeerRich** [comment]
hmmm i see. i am not quite sure how to do this

**Comment by hariombalhara** [comment]
We can introduce a global App Level Option that enables tracking for all the Booking Pages(including Profile Page and Routing Form) at once with a single Tracking ID.

Would we miss something? Do people really want to have different Trackers(or same tracker with different tracking Ids) for different EventTypes

**Comment by PeerRich** [comment]
cool !
