### ISSUE TITLE
[CAL-829] Migrate from react select. Fix UI issues

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6567]
Migrate away from react-select take a look at [https://www.downshift-js.com/](https://www.downshift-js.com/)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-829](https://linear.app/calcom/issue/CAL-829/migrate-from-react-select-fix-ui-issues)</sub>

**Comment by PeerRich** [comment]
are we 100% in agreement to use downshift? or get in touch with radix team?

**Comment by PeerRich** [comment]
remember we also have react-select-timezone

**Comment by Jaibles** [comment]
@sean-brydon can probably cancel this one?
