### ISSUE TITLE
[CAL-832] [CAL-834] Inviting Team Members on Teams Buggy

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6578]
When adding a member to a team, even if the user check the “Send an invite email” option, the invited team member is not receiving any email. They invited several people to the team and none of them received it.

Created via Threads. See full discussion: [https://threads.com/34443144252](https://threads.com/34443144252)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-832](https://linear.app/calcom/issue/CAL-832/[cal-834]-inviting-team-members-on-teams-buggy)</sub>

**Comment by Udit-takkar** [comment]
this has been fixed https://github.com/calcom/cal.com/pull/6674
