### ISSUE TITLE
[CAL-835] Ability to select Organizer on a Collective event

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6580]
The ability to select the organizer of the event should be able to be customized. Right now, it appears that it's done alphabetically.

Created via Threads. See full discussion: [https://threads.com/34443143806](https://threads.com/34443143806)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-835](https://linear.app/calcom/issue/CAL-835/ability-to-select-organizer-on-collectiveround-robin-events)</sub>

**Comment by Jaibles** [comment]
@shirazdole it makes sense for a collective. For a round Robin should the organiser not just be the person it lands on?

**Comment by shirazdole** [comment]
Correct, it should 👌🏽

**Comment by Jaibles** [comment]
@shirazdole presumably we need to create a separate issue to ensure the organiser on a round robin event is the person it lands on?

**Comment by shirazdole** [comment]
@Jaibles isn't that only if the implementation of this doesn't work properly? :o
