### ISSUE TITLE
[CAL-841] `/apps/wipe-my-cal` layout looks broken due to missing screenshots.

### ISSUE THREAD

**Issue by G3root** [calcom/cal.com#6588]
![Screenshot 2023-01-20 at 08-16-45 WipeMyCal Cal.com.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/faee6339-c0da-4e6b-9ab2-b7c27867a483/6ef93560-b7f4-4a00-9745-6ed77cb947b0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-841](https://linear.app/calcom/issue/CAL-841/appswipe-my-cal-layout-looks-broken-due-to-missing-screenshots)</sub>

**Comment by PeerRich** [comment]
easy, taking tis
