### ISSUE TITLE
[CAL-844] /event-type/single - The default for what it says in the "Event name" input does not reflect what's actually happening

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6591]
When I create a new event type, it says that this is what the Event name is:

![CleanShot 2023-01-20 at 10.26.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3a084549-db5d-4dc4-aef9-6b18cbbc2dc7/257486f9-f8df-4046-9634-e33983b39425)

When someone actually books the event, the name is:

![CleanShot 2023-01-20 at 10.25.27@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0e42933b-929f-457e-a266-d6db2dde532b/d4f7aeff-29ff-48c7-9127-b5b5bc6fc89f)

Which to me looks like

`{event_type_title} with {organsiser_full_name} and {schedulder_full_name}`

This is a good default. What we show in the event type screen input should match what we're actually doing.

Also if `event_type_title` is something a user can use, it should be in this modal:

![CleanShot 2023-01-20 at 10.29.29@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f8a5aeee-55ea-41cc-9e50-273fa7edc7d7/2e6122e6-7a04-43a6-9fc7-f77983a50926)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-844](https://linear.app/calcom/issue/CAL-844/event-typesingle-the-default-for-what-it-says-in-the-event-name-input)</sub>

**Comment by G3root** [comment]
@Jaibles looks like this has been fixed

![Screenshot 2023-02-20 19:12:55](https://user-images.githubusercontent.com/84864519/220124477-6d9c45fd-a12f-4451-94bf-fae75c212339.png)

**Comment by Jaibles** [comment]
@G3root it should be filled not placeholder right? Since it's actually what's happening - it's not a suggestion.
