### ISSUE TITLE
[CAL-845] Improve the custom event name modal UI/UX

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6592]
Currently:

![CleanShot 2023-01-20 at 10.36.17@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/421bdec5-2ce6-43da-b790-c626762f16ca/2abce212-3ee5-4a02-89c8-0c00ca492db9)

Should be

![CleanShot 2023-01-20 at 10.36.07@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7c1a6a1d-1256-4328-8cfe-fac45622f92a/0f71a942-4b25-4167-8836-0b9bf1d8042b)

[Event type / Advanced \[Edit event name\] - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=20%3A24821&t=H83Rf75IpkiqPZuD-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-845](https://linear.app/calcom/issue/CAL-845/improve-the-custom-event-name-modal-uiux)</sub>

**Comment by PeerRich** [comment]
oh i love that preview @Jaibles
