### ISSUE TITLE
[CAL-846] Improve multiselect component

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#6593]
Make multiselect component function more like this: [https://blueprintjs.com/docs/#select/multi-select2](https://blueprintjs.com/docs/#select/multi-select2)

**The main things are:**

* We want to show that an item is selected instead of removing it from the dropdown once selected
* The box needs to stay open
* We need search
* Toggle between showing all items (it currently expands onto a new line) or show a "+2 more items" at the end *(this isn't a necessity right now but would be ideal)*

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-846](https://linear.app/calcom/issue/CAL-846/improve-multiselect-component)</sub>

**Comment by PeerRich** [comment]
maybe we can convince radix-ui to work on a super dope multi-select with auto complete as well

**Comment by sean-brydon** [comment]
If they dont want to take this on. I understand it was discussed previously on their issues and it would require ALOT of work to work with their current implementation of their select primitive.  - I will create our own with downshift. see https://threads.com/34443301979
