### ISSUE TITLE
Ability to add an Icon/Emoji for each event type that displays on public page next to the event

### ISSUE THREAD

**Issue by joelwreed** [calcom/cal.com#6600]
I have coffee meetings, happy hours, lunches, virtual meetings, group, 1-on-1's. Just like everyone else.

Would be nice to see a "cup of coffee" icon/emoji next to that event type. A beer next to the happy hour event type. Etc. 

This might help 1st time users of my scheduling page more quickly find what they are looking for. Hopefully the scheduling page will look better as well!

**Comment by PeerRich** [comment]
why not just add the emojis to your event-type name?

![CleanShot 2023-01-20 at 16 51 55@2x](https://user-images.githubusercontent.com/8019099/213743763-216293d6-1e74-4798-b455-a1802786aede.jpg)

![CleanShot 2023-01-20 at 16 52 06@2x](https://user-images.githubusercontent.com/8019099/213743799-6dc2d04b-d14c-45bb-8d71-8d34554d6d69.jpg)

**Comment by joelwreed** [comment]
Yes, tried this, but it's really not big enough to be a distinguishing factor on the public scheduling page. (imho)

<img width="50" alt="image" src="https://user-images.githubusercontent.com/100404/213788336-7532245c-0daf-49fc-b52a-fef2cc417a0a.png">

I recognize I am suggesting what I perceive to be a visual enhancement and that the team may feel differently. Thanks for considering the request at least.

**Comment by joelwreed** [comment]
Here's an example from another scheduling system I use:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/100404/213788701-b227157a-d170-4e9d-a83d-fea1bdb80240.png">

**Comment by joelwreed** [comment]
They have these icon options:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/100404/213788802-4f3e3013-abe2-471d-8eb4-eccc26e5d14a.png">

**Comment by PeerRich** [comment]
i see. will pass this feedback to @Jaibles

**Comment by Jaibles** [comment]
I really like this idea. I think I can incorporate this into some current exploration around differentiating team and personal events. I'll share ideas here shortly.
