### ISSUE TITLE
[CAL-758] Booking page availability initially displaying false information

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6606]
### Issue Summary

When going to book a new event, the calendar initially shows all days as available, until the day is clicked on, then it fetches the data and says its fully booked.

### Steps to Reproduce

1. Fill a calendar for a few days, weeks or something.
2. Go to book a new event on one of the blocked days.
3. Day will initially show available until clicked on

Example Video - [https://www.loom.com/share/1a5bc8ddee5a48ef98d339cb805c42d1](https://www.loom.com/share/1a5bc8ddee5a48ef98d339cb805c42d1)

### Technical details

* Chrome 1.46.153
* Node 16

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-758](https://linear.app/calcom/issue/CAL-758/booking-page-availability-initially-displaying-false-information)</sub>

**Comment by emrysal** [comment]
I'm not seeing this happen anymore in the new booker 👍
