### ISSUE TITLE
[CAL-857] Sidebar shouldn't scroll when we have the top banner

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6613]
https://user-images.githubusercontent.com/8019099/213945384-ca4f3f9f-d57b-4013-8a12-cbd38456cd17.mp4

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-857](https://linear.app/calcom/issue/CAL-857/sidebar-shouldnt-scroll-when-we-have-the-top-banner)</sub>

**Comment by Hanaffi** [comment]
@emrysal can you assign me this? or find me some other task :) ?

**Comment by Hanaffi** [comment]
@PeerRich  can you assign me this? or find me some other issue :) ?

**Comment by PeerRich** [comment]
sure! assigned

**Comment by PeerRich** [comment]
@G3root unassigned you fyi

**Comment by PeerRich** [comment]
I wonder if the top banner should just be positioned as fixed and overlay the rest

**Comment by Jaibles** [comment]
Almost certain this was working perfectly 2 weeks ago.
