### ISSUE TITLE
[CAL-858] Stripe not installing

### ISSUE THREAD

**Issue by boringcommerce** [calcom/cal.com#6615]
I've been trying to add stripe to my cal account, but unable to.

Here are the screenshots: <img width="752" alt="image" src="https://user-images.githubusercontent.com/102703835/213911997-aaa5d954-8757-483d-8234-bf9f89e22afd.png">

<img width="2174" alt="image" src="https://user-images.githubusercontent.com/102703835/213912034-74a27a68-16dd-4f31-92e4-9439b28948f9.png">

Kindly help. My id is **anishjajodia**

<sub>[CAL-858](https://linear.app/calcom/issue/CAL-858/stripe-not-installing)</sub>

**Comment by PeerRich** [comment]
we are on it!
