### ISSUE TITLE
[CAL-859] PREMIUM username should also unlock all team features

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6616]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-859](https://linear.app/calcom/issue/CAL-859/premium-username-should-also-unlock-all-team-features)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli technically, now that we have a useHasTeam hook, we can check for Premium plan, too right?

**Comment by PeerRich** [comment]
cc @zomars

**Comment by zomars** [comment]
Optimally we should use feature flags, but we can check for user metadata for `isPremium` for a quick fix.

**Comment by hariombalhara** [comment]
Isn't premium username a one-time payment or this is something that got changed?
