### ISSUE TITLE
Rescheduling to out of availability

### ISSUE THREAD

**Issue by OfficialCRUGG** [calcom/cal.com#6619]
### Is your proposal related to a problem?

Sometimes, it's quite hard to find a time that works with my normal availability. For example this week, lots of things suddenly came up and I have to reschedule a meeting. I'm usually not available for meetings on Mondays but want to move this meeting to Monday, but I can't do that.

### Describe the solution you'd like

The ability to reschedule my meeting to times outside of my availability

### Describe alternatives you've considered

I could add a small slot of availability for that day, but that wouldn't really be a good solution

### Additional context

N/A

**Comment by PeerRich** [comment]
hey, I think for those edgecases i would just do it manually. i am not sure how we could make this better with a feature

**Comment by OfficialCRUGG** [comment]
What do you mean by "do it manually"? I can't... I would need to cancel the meeting...

**Comment by PeerRich** [comment]
can you not drag and drop the meeting to monday in your calendar?

**Comment by PeerRich** [comment]
i dont know a better technical solution on our end yet
