### ISSUE TITLE
[CAL-921] Clearer UX for adding additional guests

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6620]
### Is your proposal related to a problem?

When people book via my booking links and wish to add multiple guests, the UX for adding guests isn't clear.

There's a small icon that doesn't draw attention, so people have always forwarded on invites to multiple guests.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/60fdff4d-5ac6-4b84-acff-f7cd95e0e4db/1817c7f1-1a6d-4d67-b0c8-4d0b78853ac5)

### Describe the solution you'd like

An option to clearly display the additional guests functionality, possibly with a hard activation point to confirm there are no additional guests for the booking.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d09a5c04-c45d-43e0-9b53-0a7d440edd56/6e1305a4-d377-4bae-823f-7b9d7343605c)

### Describe alternatives you've considered

Informing regular bookers of the feature or adding a required checkbox to point them to the feature as I've had to do for #6165 as you can see in the screenshot above.

### Additional context

Related #1320
Related #6165

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-921](https://linear.app/calcom/issue/CAL-921/clearer-ux-for-adding-additional-guests)</sub>

**Comment by PeerRich** [comment]
@Jaibles I was afraid this would happen. we should look into a non-icon option

**Comment by Jaibles** [comment]
Designs: https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=1%3A5695&t=Qp3rLQeRTeNjLLZ2-1

**Comment by PeerRich** [comment]
this has been fixed
