### ISSUE TITLE
[CAL-862] Assume international format when provided a regional phone number

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6621]
### Is your proposal related to a problem?

Users sometimes provide a number in regional formatting, the phone number input fields expect an internationally formatted number.

![image](https://user-images.githubusercontent.com/3164166/213919554-82391c36-327d-4a49-9fe6-4a03738118cc.jpeg)

### Describe the solution you'd like

There are a number of ways an international number can be inferred from a regional number, perhaps libphonenumber.

Alternatively a default country code and stripping the leading 0 from UK numbers as a soft solution for this specific use case.

### Describe alternatives you've considered

Accepting that the recorded value isn't accurate & cleaning up the data myself.

<sub>[CAL-862](https://linear.app/calcom/issue/CAL-862/assume-international-format-when-provided-a-regional-phone-number)</sub>

**Comment by PeerRich** [comment]
hey @ChipWolf, we'll look into this. I bet there is a better lib out there than we currently use

**Comment by PeerRich** [comment]
@Udit-takkar wanna look into this and find a way to imrpove this? please test a range of numbers

**Comment by Udit-takkar** [comment]
@ChipWolf so i looked into docs of libphonenumber-js and react-phone-number-input.

users can still pass their regional number in the phone number text input but they would have to first select their country from this dropdown. ( as default is international number)

https://user-images.githubusercontent.com/53316345/214383408-6a7f76bc-4bc4-4153-8b8c-5c338e746efa.mov


It is not possible to validate a regional phone number without getting the region. so we can't just convert a regional number to international format.

**Comment by Udit-takkar** [comment]
@ChipWolf so i looked into docs of libphonenumber-js and react-phone-number-input.

users can still pass their regional number in the phone number text input but they would have to first select their country from this dropdown. ( as default is international number)

https://user-images.githubusercontent.com/53316345/214383408-6a7f76bc-4bc4-4153-8b8c-5c338e746efa.mov


It is not possible to validate a regional phone number without getting the region. so we can't just convert a regional number to international format.

**Comment by Udit-takkar** [comment]
we can try to get user country and use it as defaultCountry in phone number input instead of having international as the default  because it is not very obvious that phone number input type is international and one has to change it to their country in the dropdown and regional numbers would throw error ( as the input field cannot infer the region of the regional number)

cc: @Jaibles

**Comment by Jaibles** [comment]
@Udit-takkar detecting country seems helpful. 

Regarding the regional part

> regional numbers would throw error ( as the input field cannot infer the region of the regional number)

It sounds like libphonenumber as suggested by @ChipWolf could help with this?

**Comment by Udit-takkar** [comment]
@Jaibles yeah I tried libphonenumber-js. Either you set default country in the input or pass in the region code from drop-down to accept regional number of any country.
