### ISSUE TITLE
[CAL-863] No available users found error on confirming booking for an open slot

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#6622]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have not replicated this personally, but I have had different users report this error on more than occasion.

When confirming an individual booking [not a team page], some users have seen this error: "Could not book the meeting. No available users found."

![image](https://user-images.githubusercontent.com/3164166/213919823-21bfdcc7-0d5a-4330-98ff-d62f0e9c92aa.jpeg)

<sub>[CAL-863](https://linear.app/calcom/issue/CAL-863/no-available-users-found-error-on-confirming-booking-for-an-open-slot)</sub>

**Comment by PeerRich** [comment]
by any chance, is your event-type link called "book"? thats an ongoing issue we are fixing right now

**Comment by ChipWolf** [comment]
> by any chance, is your event-type link called "book"? thats an ongoing issue we are fixing right now

It isn't, it's called `bau`

**Comment by PeerRich** [comment]
weird...

we're putting in a lot of work right now in the booking page, maybe a team member knows more. you said you cant reproduce this. any idea what this could cause?

**Comment by stephane-klein** [comment]
Same error for me, with 2 different contacts (without account in cal.com).

**Comment by PeerRich** [comment]
upgraded to urgent. we need to get rid of this error message all-together and get to the bottom of this

**Comment by milospuac** [comment]
@ChipWolf Is this slot made available through a date override?

**Comment by chadamski** [comment]
This is also impacting users trying to book through my cal.com link. The slots are *not* available through date overrides, just normal, open slots.

**Comment by stephane-klein** [comment]
I think that the "No available users found." error message come from [this line](https://github.com/calcom/cal.com/blob/333801d2ae21fe48f19928c81f2496fd43d43d01/packages/features/bookings/lib/handleNewBooking.ts#L293).

**Comment by stephane-klein** [comment]
Why [this line](https://github.com/calcom/cal.com/blob/333801d2ae21fe48f19928c81f2496fd43d43d01/packages/features/bookings/lib/handleNewBooking.ts#L240)

```
const { busy: bufferedBusyTimes, workingHours } = await getUserAvailability(
```

don't [get `dateOverrides`](https://github.com/calcom/cal.com/blob/333801d2ae21fe48f19928c81f2496fd43d43d01/packages/core/getUserAvailability.ts#L268) variable? :thinking:

**Comment by PeerRich** [comment]
@emrysal

**Comment by ChipWolf** [comment]
> @ChipWolf Is this slot made available through a date override? 

Yes

**Comment by stephane-klein** [comment]
@ChipWolf @PeerRich Question: do you have a Merge Request in work in progres to share about this is issue ?

**Comment by PeerRich** [comment]
not yet, i believe different issues cause the same (bad) error message of "No available users found"

**Comment by stephane-klein** [comment]
Some news about this issue?

I'm stuck, waiting for this bug to be fixed and I don't know if it's better if I try to fix this bug myself or if I should go to https://calendly.com/ or https://savvycal.com 🤔

**Comment by PeerRich** [comment]
hey, we are actively working on this, it seems to be some sort of user error because it doenst show up for each user. 

I understand this is super annoying which is why it has an urgent flag

**Comment by PeerRich** [comment]
lemme also give it a bounty

/bounty 1000

**Comment by PeerRich** [comment]
@stephane-klein I cannot reproduce this on your link

![CleanShot 2023-02-05 at 10 42 03@2x](https://user-images.githubusercontent.com/8019099/216811918-ca658270-596e-464f-8a75-2c0955ad9ddf.jpg)

**Comment by PeerRich** [comment]
ok i was able to reproduce it on this link:

![CleanShot 2023-02-05 at 10 42 48@2x](https://user-images.githubusercontent.com/8019099/216811935-9215fe5b-b198-42de-90fc-10a9fdb7753f.jpg)

**Comment by PeerRich** [comment]
i think i know why: for that link you have a different availability that has no available dates: 

![CleanShot 2023-02-05 at 10 46 19@2x](https://user-images.githubusercontent.com/8019099/216812074-0b3521de-2ab1-486e-b27f-38ef258adf75.jpg)

**Comment by mischarouleaux** [comment]
@PeerRich 
Hi everyone!

@JeroenReumkens shared this issue with me and I have found a fix for it. I'm doing some testing now and once done I'll open a PR for you to review!

**Comment by mischarouleaux** [comment]
@PeerRich @JeroenReumkens Just submitted the PR, feel free to add people to review it!

**Comment by chadamski** [comment]
I am trying to track progress on this issue across a couple of different threads, so I apologize if this is the wrong place for this comment, but just wanted to register that the error is popping up on my account even though I am *not* actively making use of date overrides.

**Comment by PeerRich** [comment]
can you check if you have availability?

**Comment by chadamski** [comment]
Yeah, for me this is happening on normal calendar bookings with completely available dates, no overrides. Started happening about 1.5/2 weeks ago, or at least that's when a client of mine first reported it to me.

**Comment by AdrianKrebs** [comment]
I same issue here, prospective clients notified me about it. Definitely an urgent issue.

**Comment by manntam** [comment]
Same issue, although it also sometimes shows up as: Could not book the meeting. invalid_type in 'api_key': Required... Weird because everything was working fine as of yesterday

**Comment by manntam** [comment]
I updated everything and rebuilt the calcom docker. The availability issue and the "API_key" issue resolved itself.

**Comment by mischarouleaux** [comment]
I just did a retest if the issue from @ChipWolf and @stephane-klein was resolved with the rebuilt of docker. 
But I still get an error by using date overrides when trying to book an event!

I already created a PR on Monday which probably fixes the problem, so the user's availability check will also include the date overrides of an user, but it is still waiting for a review. @PeerRich could you check if this PR can get a review as this issue is marked as urgent!

**Comment by AdrianKrebs** [comment]
Any updates on this? I got the second customer reaching out that some timeslots are not working. I might end up just switching back to Calendly then

**Comment by ShaneMaglangit** [comment]
I found another way to replicate this issue, here's how to reproduce:

1. Create an event with a limit of 1 booking frequency.
2. Open the booking page for this event in two tabs (let's call them tab A and B).
3. Book a meeting to the event using Tab A.
4. Switch back to Tab B: User can still book for the same day. Slot won't show as fully booked unless page is refreshed.

This would likely appear for events with high traffic even without date overrides.

I've submitted a PR that resolves this edge case.

**Comment by chadamski** [comment]
I believe that #7071 has resolved this for me. I can no longer replicate the problem. Thanks, everyone!

**Comment by tbalbous** [comment]
Hi,
I have the same problem since feb 1st.
no override, but leaving in France and the bug seems to happen after the summer time change. (maybe an under the hood override)
Any projection of a release date for the correction ?

**Comment by Airback** [comment]
I am still suffering from this bug as it seems. Using the cloud version with google calendar: 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/16556794/220650477-734556f3-913c-4ebb-a9e5-2b70709209aa.png">

**Comment by PeerRich** [comment]
we are currently investigating this for some users! see status.cal.com

cc @emrysal @roae @zomars

**Comment by cpunnelliehealth** [comment]
Having this issue as well, still present on cal version 2.6.6. Steps to reproduce:

Set working schedule limits e.g., 9am-5pm M-F. Timezone America/Toronto (or New_York)
Try to schedule a time that crosses the daylight savings time period, e.g., current date Feb 26, 2023 and attempting to book March 16, 2023 at 9am, which is at the earliest possible time of Availability.

Get this error message:

<img width="771" alt="Screen Shot 2023-02-26 at 7 26 10 PM" src="https://user-images.githubusercontent.com/126418022/221447270-2f5be7e0-0eed-418e-8241-f9ebcc2619e2.png">


I suspect this is due to the shift in DST not being accounted for in the Availability, so it may appear as if I'm trying to book an 8am timeslot but in fact it is 9am because of DST.

**Comment by yunghannz** [comment]
i have the same issue:

`Termin konnte nicht gebucht werden. No available users found.`

**Comment by elmerohueso** [comment]
@roae @PeerRich 
I can confirm it appears to be incorrectly factoring for DST.
I'm in the America/Boise timezone, which is currently GMT-7. During daylight savings time (starting March 12), the offset will be GMT-6.
- On the appointment time selection page for March 12 and after, the availability times are shown as starting and ending one hour before my actual availability.
- If I create an availabilty override for March 12 or later, the times shown after hitting "Save Override" are one hour earlier that the times I'd selected.

Test:

1. Logged into app.cal.com
2. Went to the settings page for one of my appointment type
3. Under "Date overrides", clicked "Add an override"
4. Selected 8:00PM-10:00PM March 12th, and clicked "Add Override"
5. Noticed it showed 7:00PM-9:00PM (instead of 8-10) on March 12th was added (DST is being improperly applied here)
6. Went to my appointment booking page for March 12
7. Noticed it showed my availability as 6:00PM-8:00 (yet another hour earlier)

I'm guessing that, on the backend, cal is compounding the additional hour offset from DST.

**Comment by fiehtle** [comment]
I have the same issue with other cal.com users and with my cal.com

**Comment by ChipWolf** [comment]
Can we omit these events back over to Google Analytics or something visible in the console so we can keep check of which bookings failed to convert b/c of platform errors

**Comment by RussQuan** [comment]
> I have the same issue with other cal.com users and with my cal.com

I have the same issue too!

**Comment by wamoyo** [comment]
Same issue for me. 

URL: `https://cal.com/innovationbound/book?type=211681&month=2023-04&date=2023-04-03T09%3A00%3A00-04%3A00&slug=45-min-meeting&count=`

![Screenshot from 2023-03-02 21-29-42](https://user-images.githubusercontent.com/1170326/222616441-faaeca4b-3597-4e31-b541-9eb63a0ca32e.png)

**Comment by elmerohueso** [comment]
@zomars When should this fix go live on the website, so I can tell my users/clients?

**Comment by zomars** [comment]
@elmerohueso Monday we will tag a release

**Comment by elmerohueso** [comment]
Great!

**Comment by ShaneMaglangit** [comment]
Glad that this is getting resolve.

I would suggest that we re-evaluate having Dayjs as the dependency. It has been getting a lot of complaints due to how buggy it is when dealing with timezones (due to daylight savings) and how unresponsive the maintainer is. Last commit was 3 weeks ago.

Its practically unmaintained: https://github.com/iamkun/dayjs/pulse/monthly

**Comment by elmerohueso** [comment]
@roae It looks likes the problem still exists for March 12th (DST starts at 2AM on March 12th). It does, however, appear to be working after that.

**Comment by PeerRich** [comment]
@ShaneMaglangit whats a good alternative? 

@emrysal you experience a lot of issues with dayjs. is it time switching?

**Comment by emrysal** [comment]
The primary issue with dayjs is the ease in which you can make errors: 

E.g. `dayjs("2023-01-02T22:00:00Z").utc()` is NOT the same as `dayjs.utc("2023-01-02T22:00:00Z")` - in this example the resulting time can be miles off, both will be in UTC mode but one is adjusted to the local time and the other is not. 

Every dayjs line has to be carefully considered and taking into account the three timezones we are dealing with - organizer, system and booker time.

**Comment by tomml** [comment]
I am facing the same error message.
My appointment is a 25minutes slot. Availability starting from 1pm till 4:15pm. Prebooking is set to one specific date, currently the 16th of march.
I know that a 25minutes slot will not fit with the availability as it needs to be set to 16:20. BUT this is not available to be selected. Only 15min slots here, but for the appointment one can set the time to an exact minute. 
How to resolve this issue? My appointment needs to be 25minutes long, also the availability is fixed.

**Comment by ShaneMaglangit** [comment]
> I am facing the same error message, but maybe a different scenario here. See my bookings: https://cal.com/mobile-massage-rgb/25 There, the appointment for 3:55pm (timezone is europe/amsterdam as I am from germany) should be bookable, but if I understand correctly it does not fit my availability. The availability time slot can only be set by 15min slots. Mine is set to 1pm till 4:15pm. The appointment time by the other hand can be an exact 1min slot. 25minutes in my case. I tried to make my availability till 4:30pm, but then there appears another appointment starting at 4:20pm, which also does not fit the availability schedule. With this time settings always the last appointment slot is not bookable by my clients facing the error message OP posted. How to resolve that issue?

Yup, this is a slightly different issue from this. I had a PR meant to address this https://github.com/calcom/cal.com/pull/7215, but is yet to be merged.

**Comment by ShaneMaglangit** [comment]
> I am facing the same error message, but maybe a different scenario here. See my bookings: https://cal.com/mobile-massage-rgb/25 There, the appointment for 3:55pm (timezone is europe/amsterdam as I am from germany) should be bookable, but if I understand correctly it does not fit my availability. The availability time slot can only be set by 15min slots. Mine is set to 1pm till 4:15pm. The appointment time by the other hand can be an exact 1min slot. 25minutes in my case. I tried to make my availability till 4:30pm, but then there appears another appointment starting at 4:20pm, which also does not fit the availability schedule. With this time settings always the last appointment slot is not bookable by my clients facing the error message OP posted. How to resolve that issue?

Yup, this is a slightly different issue. I can create a quick PR to fix this as I have already identified where this bug is found before. Just have to check if there any existing PR for this.

**Comment by PeerRich** [comment]
we ended up hiring @roae ❤️

**Comment by roae** [comment]
Fixed on #7792

**Comment by ShaneMaglangit** [comment]
@PeerRich still randomly encountering this error btw

**Comment by PeerRich** [comment]
yeah the amount has really decreased. we're investigating the last couple times

**Comment by kirillrogovoy** [comment]
Experiencing the same error with anybody trying to book a meeting with me, and it's extremely frustrating.

When I change the event duration to 30 minutes, it works well. But I need it to be 120 minutes. In that case, it always shows the error.

<img width="390" alt="image" src="https://github.com/user-attachments/assets/f6319bf5-b8e1-4f42-8fc0-8d3780c94063">

Booking URL: https://cal.com/kirillrogovoy/tech-interview

**Comment by clear-design** [comment]
Also experiencing this behaviour at cal.com/seriously/75mins
Appears to only happen with the first few available dates provided, moving out further into the future books successfully.

**Comment by ropl-btc** [comment]
![IMG_7550](https://github.com/user-attachments/assets/3893ed84-e382-4b1f-ad89-7446b77b8854)

same issue here. i’m using ICS feed with Proton Calendar.

**Comment by Gummba** [comment]
Another issue was raised which seems to provide the actual reproduction scenario. In my case, it is also related to a calendar with recurring events (lunch time daily), some of which events have been cancelled.

For reproduction scenario: see https://github.com/calcom/cal.com/issues/25947
