### ISSUE TITLE
[CAL-861] Allow favicon customization

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#6628]
<sup>Originally posted by @joshavant January 22, 2023</sup>

Currently, the user is unable to customize the favicon used for booking pages:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5a345a4f-2662-4b01-a477-8cfac2dac8da/9a35e17c-fd90-458a-835f-9c6391a7c3da)

### Describe the solution you'd like

It would improve branding customization to be able set a custom favicon.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-861](https://linear.app/calcom/issue/CAL-861/allow-favicon-customization)</sub>

**Comment by PeerRich** [comment]
Hey @joshavant I dont think this is on our list of priorties right now. if you self-host, you can easily change that.

happily accepting PRs but i dont think many people would use this.
