### ISSUE TITLE
[CAL-866] /event-type/single - Default "Add to calendar" is misleading

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6634]
![CleanShot 2023-01-23 at 09.52.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2bf914dc-5e59-4a40-98a6-8280f4ddab9f/2c85445e-0e1f-4e5a-af09-031d74d916ca)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-866](https://linear.app/calcom/issue/CAL-866/event-typesingle-default-add-to-calendar-is-misleading)</sub>

**Comment by milospuac** [comment]
[https://www.loom.com/share/8e5c54c0799f4d93b48a1550d95c9bb5](https://www.loom.com/share/8e5c54c0799f4d93b48a1550d95c9bb5)

@joeauyeung I think whatever calendar is first in the installed apps will show as the default calendar in the event types, but it's not behaving as the default - the events are still being added to the actual default calendar.
