### ISSUE TITLE
On the "Select the dates to override" dialog modal, I notice a bad positioning of the time picker

### ISSUE THREAD

**Issue by stephane-klein** [calcom/cal.com#6635]
On the "Select the dates to override" dialog modal, I notice a bad positioning of the time picker.

<img width="1482" alt="Capture d’écran 2023-01-23 à 13 17 18" src="https://user-images.githubusercontent.com/54498080/214038060-4ba6b5b5-b858-4bfb-b5a6-9d4a85351201.png">

Navigation to this page:

- go to https://app.cal.com/availability
- click on one row
- click on `+Add on override` button
- select a date day
- click on time field

**Comment by emrysal** [comment]
Thank you - adding some of the description for easier finding of the tracking issue @ #6555

**Comment by Udit-takkar** [comment]
fixed here [https://github.com/calcom/cal.com/pull/6636](https://github.com/calcom/cal.com/pull/6636)
