### ISSUE TITLE
[CAL-880] [BUG] Disabled apps  are listed as installable

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6652]
Hi @emrysal,

I've got a bug :

Here are my apps enabled

![Capture d’écran du 2023-01-23 09-21-04](https://user-images.githubusercontent.com/50081751/213998174-2168ee29-b6be-4d7e-9bd2-e32787cdda23.png)

But in an event type, apps unavailable are listed and installable

![Capture d’écran du 2023-01-23 09-20-36](https://user-images.githubusercontent.com/50081751/213998410-b721d233-4432-48f8-b403-bb1b50d6ca5f.png)

_Originally posted by @Quentin-Guillemin in https://github.com/calcom/cal.com/issues/6570#issuecomment-1399990431_
            

<sub>[CAL-880](https://linear.app/calcom/issue/CAL-880/[bug]-disabled-apps-are-listed-as-installable)</sub>

**Comment by asdf4w3t5** [comment]
This doesn't seem to have ever been fixed.
