### ISSUE TITLE
[CAL-883] Use new multi-select component

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6659]
I'm assuming this isn't something we have well componentised, and that to fix this we have to fix it in the 80 or so places we have it. I would love if we could build one multi-select component that we re-use everywhere but for many reasons that doesn't seem possible, so I'm creating a task to just try improve what we're currently dealing with.

**Here is the spec for what a multi-select should look like:**

![CleanShot 2023-01-24 at 09.43.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1ada8988-3161-4f48-8790-8662466fbb38/7ec725e3-2dad-4f82-8768-781322721dcf)

[Multi-select - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=1359%3A151787&t=vc3S5TKuQBTko1yC-1)

I've also documented some of the main issues with some common examples, however, there's no doubt in each place we have the multi-select component there will be various other issues. Please refer to the design spec to try find those.

Find as many as you can and fix please

![CleanShot 2023-01-24 at 09.34.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4e9ef4d6-a17f-4e03-968e-d2471f4412c3/f4cf3fdf-85da-40ac-9d27-507aab5190ae)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-883](https://linear.app/calcom/issue/CAL-883/clean-up-our-multi-select-component)</sub>

**Comment by Jaibles** [comment]
Re-assigning to you @sean-brydon as you can use this when refining the UI for the current implementation

**Comment by PeerRich** [comment]
not a quick win unfortunately 😆

**Comment by sean-brydon** [comment]
I'd like to say this is done? On a component level anyway - may not be 100% to figma but me and @Jaibles went through on a call and made it to how we thought looked best with the few limitations we have with the new approach

**Comment by PeerRich** [comment]
but its not implemented everywhere yet is it?

**Comment by Jaibles** [comment]
definitely not.

**Comment by PeerRich** [comment]
renamed ticket to "Use new multi-select component"

**Comment by sean-brydon** [comment]
Closed in favour of using react-select
