### ISSUE TITLE
[CAL-885] seats: first person gets the link, subsequent attendees dont

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6664]
In events that have seats, when the first attendee books a session there is a Cal Video/Google Meet link generate and included in the invite. However, for subsequent attendees booking a seat in the same session, the invite they get does not include any google meet link/Cal video link. I also noticed that the link is then removed from the event in my Google Calendar with the location just showing up as google.

<sub>[CAL-885](https://linear.app/calcom/issue/CAL-885/seats-first-person-gets-the-link-subsequent-attendees-dont)</sub>

**Comment by ayushman-kc** [comment]
Upgraded our self-hosted to 2.6, and we're still facing this issue when the event location is set to Google Meet. It is fixed for Cal Video though.
