### ISSUE TITLE
[CAL-901] RFC: Consider adding timezone to request headers

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6679]
This would allow us to compute most of needed data from the server.

We could use x-vercel-ip-timezone from Vercel by default with the option to override from the client if desired.

Some links about this:

[https://twitter.com/leeerob/status/1551273570713698304/photo/1](https://twitter.com/leeerob/status/1551273570713698304/photo/1)

[https://github.com/vercel/examples/blob/main/edge-functions/geolocation-country-block/middleware.ts](https://github.com/vercel/examples/blob/main/edge-functions/geolocation-country-block/middleware.ts)

[https://vercel.com/docs/concepts/edge-network/headers#x-vercel-ip-timezone](https://vercel.com/docs/concepts/edge-network/headers#x-vercel-ip-timezone)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-901](https://linear.app/calcom/issue/CAL-901/rfc-consider-adding-timezone-to-request-headers)</sub>

**Comment by PeerRich** [comment]
i just realised this only works on vercel, we have a fall back right?

**Comment by zomars** [comment]
We don't have a fallback yet. We would no to degrade gracefully and not rely on the headers only.
