### ISSUE TITLE
[CAL-903] Onboarding not allowing all times to be selected

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#6684]
![819146C4-4EB2-4933-95D4-DF52B944627E.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b8a6d33c-ab4d-47c6-9685-37cb6c22420b/c64c1139-135e-4a55-a440-d0e5590bd718)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-903](https://linear.app/calcom/issue/CAL-903/onboarding-not-allowing-all-times-to-be-selected)</sub>

**Comment by Udit-takkar** [comment]
<img width="820" alt="Screenshot 2023-01-26 at 1 31 21 AM" src="https://user-images.githubusercontent.com/53316345/214676564-36246285-134f-496e-b1d5-f9fd8f90d4ec.png">

@baileypumfleet  i am able to select 12:00 am to 11:59 PM in onboarding.

**Comment by baileypumfleet** [comment]
Unable to reproduce, closing
