### ISSUE TITLE
[CAL-904] Booking made in time zone not supported by Day.js

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#6686]
![A81EFFE0-40D1-4EED-AE11-A17FBAB52474.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/50040d72-4dc0-4d4f-956b-2061d6f0253a/c5635b3f-4bb2-446a-8316-2bc78fe0a500)

Someone booked me with a time zone that you can select in timezone-select, but it isn’t supported by day.js.

I can confirm that Kolkata is a real place, it isn’t invalid.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-904](https://linear.app/calcom/issue/CAL-904/booking-made-in-time-zone-not-supported-by-dayjs)</sub>

**Comment by alishaz-polymath** [comment]
Isn't that supposed to be `Asia/Kolkata`? 🤔 
Can confirm that we can't select 'India/Kolkata' from the dropdown now. Closing this ticket. Please feel free to open it if it is still selectable, wasn't the case when I tested it.
