### ISSUE TITLE
[CAL-908] Event deleted from calendar still shows in bookings, errors when trying to cancel

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#6695]
![CleanShot 2023-01-25 at 14.16.42@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/88e93709-9b0a-4fc5-9a7e-a28f87a72567/f80a5046-b3ab-4567-bf48-55dd4706c984)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-908](https://linear.app/calcom/issue/CAL-908/event-deleted-from-calendar-still-shows-in-bookings-errors-when-trying)</sub>

**Comment by hussamkhatib** [comment]
@Jaibles 
 Can I pick up this issue ?

**Comment by Jaibles** [comment]
Oh, ok thank you for looking into it @hussamkhatib 🙏 

@alannnc can you confirm this issue would be resolved by #5427? If so we can close this one.

**Comment by keithwillcode** [comment]
Confirmed the 500 is resolved. We need to implement 2-way sync to delete bookings upon calendar deletion. See #5124 for more discussion around this.
