### ISSUE TITLE
[CAL-909] "No user available" is a wrong error. Ideally: never show an error

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6696]
we neeed to get to the bottom of this error message and get it to zero. 

![image](https://user-images.githubusercontent.com/8019099/214594281-66fc0ccf-442a-44ab-8656-16f819065a77.png)

<sub>[CAL-909](https://linear.app/calcom/issue/CAL-909/no-user-available-is-a-wrong-error-ideally-never-show-an-error)</sub>

**Comment by PeerRich** [comment]
can we look into our logs and see what causes it?

**Comment by PeerRich** [comment]
do we have logs, @zomars ?

**Comment by kemilbeltre** [comment]
Hi, @PeerRich  what is expected to solve this issue? thanks
