### ISSUE TITLE
Cannot destructure property 'auth' of 'e' as it is undefined.

### ISSUE THREAD

**Issue by SyndicatedPillbug** [calcom/cal.com#6697]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to set up a CalDav link between Cal.Com and Zoho Calendar, I get the following error: "Cannot destructure property 'auth' of 'e' as it is undefined."

### Steps to Reproduce

1. Navigate through initial set-up to (https://app.cal.com/apps/caldav-calendar/setup)
2. Enter Zoho information (since 2FA is enabled, I used an app-specific password generated in Zoho).
3. Copied the "CalDav URL" that's available in Zoho.
4. Encountered the following error when I tried to save: "Cannot destructure property 'auth' of 'e' as it is undefined."

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: Brave browser latest version.
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment]
hey can we move this to https://github.com/calcom/cal.com/issues/3457 ?
