### ISSUE TITLE
[CAL-922] Right Icon Button not working as expected

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6703]
Right Icon Button not working as expected and doesnt match designs

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-922](https://linear.app/calcom/issue/CAL-922/right-icon-button-not-working-as-expected)</sub>

**Comment by G3root** [comment]
@sean-brydon can you provide me more context on this ?

**Comment by emrysal** [comment]
Just checked, this has been fixed @G3root
