### ISSUE TITLE
[CAL-923] chore: remove defined but never used variables

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6704]
![CleanShot 2023-01-25 at 18 56 46@2x](https://user-images.githubusercontent.com/8019099/214644369-fa0c5fe5-a225-463d-8481-2bf59a7f5e92.jpg)

<sub>[CAL-923](https://linear.app/calcom/issue/CAL-923/chore-remove-defined-but-never-used-variables)</sub>

**Comment by blam404** [comment]
@PeerRich I can take on this task. This is my first time doing open source contributions and this makes me less terrified of breaking something.

**Comment by PeerRich** [comment]
@blam404 go for it! as long as you dont remove too much hehe!
