### ISSUE TITLE
[CAL-930] About section gets auto focused on team settings

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6721]
About section gets auto focused on team settings

[https://user-images.githubusercontent.com/55134778/214815295-1b1725e1-8a1c-4d4f-a4ca-3b9b99e57bda.mp4](https://user-images.githubusercontent.com/55134778/214815295-1b1725e1-8a1c-4d4f-a4ca-3b9b99e57bda.mp4)

Desired behaviour is not to start the focus anywhere

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-930](https://linear.app/calcom/issue/CAL-930/about-section-gets-auto-focused-on-team-settings)</sub>

**Comment by AFZL210** [comment]
I could not find the main reason why it is getting focused on the `about` section, and it is very inconsistent. However, what we can do is use `useLayoutEffect` and explicitly focus on the body right after the DOM is loaded

@Udit-takkar If you are not working on this issue, then I would love to create a pull request for this

https://user-images.githubusercontent.com/79896602/235313015-0da812a2-c2e2-4f93-a846-9b30c8f204fc.mp4

**Comment by Udit-takkar** [comment]
@AFZL210 i am not working on this issue currently. you can start working on it
