### ISSUE TITLE
[CAL-932] Creating a workflow with two actions won't save

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6723]
* 1st step was to send a reminder email an hour before with the Reminder template to the HOST.
* 2nd step was to send a reminder email an hour before with the Reminder template to the ATTENDEE.

*submitted via feedback in app* 

[1aa22b01-5124-463d-9411-4fd357be9048](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7891f69e-1e95-43e6-b7f4-9b3457ac50ef/1aa22b01-5124-463d-9411-4fd357be9048)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-932](https://linear.app/calcom/issue/CAL-932/creating-a-workflow-with-two-actions-wont-save)</sub>

**Comment by CarinaWolli** [comment]
Already fixed in #6670 (not yet in production)
