### ISSUE TITLE
[CAL-933] on cal.com, add canonical metatag for cal.com/<username> pages

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6726]
right now we have both: https://app.cal.com/peer and https://cal.com/peer

we need a canonical meta tag in that page that says the default URL is cal.com/peer to prevent duplicate content

<sub>[CAL-933](https://linear.app/calcom/issue/CAL-933/on-calcom-add-canonical-metatag-for-calcomusername-pages)</sub>

**Comment by PeerRich** [comment]
on self-hosters this should be {BASE_URL}?

**Comment by PeerRich** [comment]
https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls

**Comment by PeerRich** [comment]
something like

<link rel="canonical" href={"https://cal.com/"+ username} />

and

<link rel="canonical" href={"https://cal.com/"+ username + slug} />

or is there a better way?

**Comment by emrysal** [comment]
TODO:
- [ ] Add canonical from https://app.cal.com/[user]/[type]
- [ ] Add canonical from https://app.cal.com/[user]
- [ ] Add canonical from https://app.cal.com/team/[team]/[type]
- [ ] Add canonical from https://app.cal.com/team/[team]

**Comment by p6l-richard** [comment]
> TODO:
> 
> * [ ]  Add canonical from [https://app.cal.com/[user]/[type]](https://app.cal.com/%5Buser%5D/%5Btype%5D)
> * [ ]  Add canonical from [https://app.cal.com/[user]](https://app.cal.com/%5Buser%5D)
> * [ ]  Add canonical from [https://app.cal.com/team/[team]/[type]](https://app.cal.com/team/%5Bteam%5D/%5Btype%5D)
> * [ ]  Add canonical from [https://app.cal.com/team/[team]](https://app.cal.com/team/%5Bteam%5D)

Since I couldn't find any page that exists on app.cal.com that doesn't also exist on cal.com, what about defining the canonical everywhere to be https://cal.com?

E.g. something like this:
https://github.com/calcom/cal.com/pull/6693/files#diff-7a6e13bc35f6130398aea815a3973fd34c2327f124c1d0ba57880dbf67f0d28fR77-R78

I don't know why the PR is getting linting issues on parts of the code that I haven't even touched tbh (I'm unable to inspect the vercel deployments because of missing authorization).

**Comment by p6l-richard** [comment]
> on self-hosters this should be {BASE_URL}?

changed to: 
```ts
  // build the canonical url to ensure it's always cal.com (not app.cal.com)
  const router = useRouter();
  const calcomUrl = (`https://cal.com` + (router.asPath === "/" ? "" : router.asPath)).split("?")[0]; // cut off search params
  const defaultUrl = IS_SELF_HOSTED ? getBrowserInfo()?.url : calcomUrl;
```

**Comment by PeerRich** [comment]
btw. there is a variable isCalcom that checks for `https://cal.com/ + (router.asPath === "/"`

now that you mention it, I don't think there are any side-effects to have all canonical links point to cal.com

**Comment by PeerRich** [comment]
packages/lib/isCalcom.ts

**Comment by p6l-richard** [comment]
Here is a [Google Sheet](https://docs.google.com/spreadsheets/d/14dGnNu2dziS1ua50MuPaZpkb9UerMGHm_yOB8KLSWTM/edit#gid=1871090508) that contains pages that haven't been indexed by Google.

Now, that we have the canonical implemented, these are perfect to see if Google respects our tag.

**Comment by PeerRich** [comment]
amazing!
