### ISSUE TITLE
[CAL-937] When duplicating event > UI: URL missing username

### ISSUE THREAD

**Issue by McPizzaIs** [calcom/cal.com#6727]
### Issue Summary

When you duplicate an event, the settings popup is missing the user's name from the address field
<img width="689" alt="image" src="https://user-images.githubusercontent.com/17185737/214838372-7ffe7c81-e92a-4815-9901-263b900c78f1.png">

### Steps to Reproduce

1. Duplicate an existing event
2. In the "Duplicate Event" popup the user's username is not rendered in the UI

### Technical details

- Safari 16.2

<sub>[CAL-937](https://linear.app/calcom/issue/CAL-937/when-duplicating-event-ui-url-missing-username)</sub>

**Comment by Udit-takkar** [comment]
It has been fixed https://github.com/calcom/cal.com/pull/6657 and will be deployed soon
