### ISSUE TITLE
[CAL-973] Redirect after booking with disabel success page in iframe

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#6734]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Create event with redirect and disabled success page
2. Embed the event - I am using inline embed
3. Book using embedded version

**Actual result:** The page crashes, I see a grey screen and the following message: sleepdoctor.me refused to connect.

**Expected result:** I should be redirected to URL mentioned in settings.

**Recording**:  https://drive.google.com/file/d/1bBsrCgJzK5efjSqKbMbbsYLPwrrgkG9w/view?usp=sharing

<sub>[CAL-973](https://linear.app/calcom/issue/CAL-973/redirect-after-booking-with-disabel-success-page-in-iframe)</sub>

**Comment by aasargsian** [comment]
Here is where you can replicate the issue: https://rdv.sleepdoctor.me/

**Comment by PeerRich** [comment]
@hariombalhara can look into this

**Comment by hariombalhara** [comment]
This is already resolved over slack. It wasn't a bug in cal.com. iframing is disabled for the website
