### ISSUE TITLE
[CAL-939] [CAL-789] Installed Apps: Layout, spacing issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6735]
Currently

![CleanShot 2023-01-10 at 11.07.49@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f912e69b-78c3-4a27-945f-8187631fb4b3/41b4d2d6-dacc-4207-9bf3-7860867f70aa)

Should be

![CleanShot 2023-01-10 at 11.14.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d7ea0619-2934-4662-970a-9364e9e7c992/2c795963-7c9c-4fe4-a620-0b8c6c1401ff)

View in Figma

[📐SPEC: Installed Apps - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=1256%3A108316&t=2RhzAobvSiPXOBD0-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-789](https://linear.app/calcom/issue/CAL-789/installed-apps-layout-spacing-issues)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-789](https://linear.app/calcom/issue/CAL-789/installed-apps-layout-spacing-issues)</sub>

**Comment by saideepesh000** [comment]
hey @Jaibles , can i take this up?

**Comment by PeerRich** [comment]
yes sure!

**Comment by PeerRich** [comment]
unless @G3root is already on it
