### ISSUE TITLE
[CAL-942] Old inputs still being used throughout the app

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6742]
old input

Search  `<input` to get a rough estimate

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-942](https://linear.app/calcom/issue/CAL-942/old-inputs-still-being-used-throughout-the-app)</sub>

**Comment by saideepesh000** [comment]
hey @sean-brydon , please assign this to me

**Comment by saideepesh000** [comment]
So here, native <input /> tag should be replaced with <Input /> component?

**Comment by sean-brydon** [comment]
Correct - mainly for text inputs/number inputs

**Comment by sean-brydon** [comment]
Hello @saideepesh000 are you still woking on this? 

Just though i'd clear up what we need here in a bit more detial.

Not every `<input` tag needs to be swapped - its mainly inputs where 

``` 
type="password"
type="number"
type="text"
or no type present
``` 
A lot of old inputs still use a standard structure like
<img width="672" alt="CleanShot 2023-01-31 at 13 20 16@2x" src="https://user-images.githubusercontent.com/55134778/215771592-3d2fa63f-e668-4b44-b329-99ee674c2c5a.png">
However we can replace all of this boilerplate with our `TextField` component
<img width="702" alt="CleanShot 2023-01-31 at 13 20 46@2x" src="https://user-images.githubusercontent.com/55134778/215771694-628d1ea0-c44e-4c0a-8236-60cdd9770662.png">

**Comment by saideepesh000** [comment]
Hey @sean-brydon , yeah, will rise the PR by this weekend

**Comment by saideepesh000** [comment]
hey, was busy in weekend, will raise the PR in a couple of days

**Comment by DivyaMaddipudi** [comment]
Why this issue is still open?

**Comment by PurvishDhameliya** [comment]
#10394 Does this issue still exist?
