### ISSUE TITLE
[CAL-945] /booking - Users select component needs max height

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6752]
We have a team of 100 people joining soon. Our people filter needs search or it's going to be very difficult to use.

It also needs a max-height, right now it seems to expand the height of all people.

Current:

![CleanShot 2023-02-16 at 19.06.16@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2a67f0ea-b613-4535-bcfd-d469f5d0f898/db7e9bf3-58f8-4d30-8d88-9c2281c3e3e5)

Desired behaviour:

[https://user-images.githubusercontent.com/8019099/215060092-fe3e3065-886e-406e-89c7-843c28d52e02.mp4](https://user-images.githubusercontent.com/8019099/215060092-fe3e3065-886e-406e-89c7-843c28d52e02.mp4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-945](https://linear.app/calcom/issue/CAL-945/booking-users-select-component-needs-max-height)</sub>

**Comment by Jaibles** [comment]
@sean-brydon can we use the updated react component you built here?

**Comment by sean-brydon** [comment]
> @sean-brydon can we use the updated react component you built here?

Yeah will pick this up tomorrow

**Comment by sean-brydon** [comment]
Fixed : [https://github.com/calcom/cal.com/pull/7170](https://github.com/calcom/cal.com/pull/7170)
