### ISSUE TITLE
[CAL-947] first time signing in: empty dashboard flashes before onboarding 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6755]
when finishing signup and logging in the first time, it flashes the empty dashboard for half a second before going to onboarding

<sub>[CAL-947](https://linear.app/calcom/issue/CAL-947/first-time-signing-in-empty-dashboard-flashes-before-onboarding)</sub>

**Comment by joeshajan** [comment]
Hey @PeerRich I would like to work on this. Can you assign this to me?

**Comment by PeerRich** [comment]
awesome! assigned you

**Comment by joeshajan** [comment]
Hey, @PeerRich I'm not able to recreate this issue. When I'm signing up it's working fine. Not able to see the empty dashboard.

Can someone please help me with this?

**Comment by PeerRich** [comment]
it flashes for a very brief moment

**Comment by PeerRich** [comment]
correct!

**Comment by joeshajan** [comment]
How can I signup through this page?

![image](https://user-images.githubusercontent.com/69904519/216645054-f70b6912-fa07-45bd-b83a-0e4df63ddd08.png)

Instead when I'm running locally different signup page is showing

![image](https://user-images.githubusercontent.com/69904519/216648808-ff18aa22-9a5a-4ce8-b7ce-bcc32e6d95e2.png)

**Comment by joeshajan** [comment]
And when I signup through this page the dashboard is not flashing. It's directly taking me to onboarding.

**Comment by PeerRich** [comment]
ah right that would require access to our website repo. hmm lemme assign this to someone in our team. its good the other signup page works

**Comment by joeshajan** [comment]
Yeah sure
