### ISSUE TITLE
[CAL-948] [CAL-949] Nextcloud not syncing busy times

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6756]
Nextcloud not syncing busy times but attendee isn't able to book that slot

Created via Threads. See full discussion: [https://threads.com/34444599487](https://threads.com/34444599487)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-948](https://linear.app/calcom/issue/CAL-948/nextcloud-not-syncing-busy-times)</sub>

**Comment by PeerRich** [comment]
lets move this here: https://github.com/calcom/cal.com/issues/3457
