### ISSUE TITLE
[CAL-950] Use markdown editor for bio in onboarding

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6757]
We use markdown in settings so we should probably offer this during onboarding too

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-950](https://linear.app/calcom/issue/CAL-950/use-markdown-editor-for-bio-in-onboarding)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli is on it already!

**Comment by CarinaWolli** [comment]
Already in onboarding as well:
<img width="716" alt="Screenshot 2023-01-30 at 07 57 12" src="https://user-images.githubusercontent.com/30310907/215483887-764135c2-9b18-49ea-afbe-e8e543caeddb.png">
