### ISSUE TITLE
[RFC] Start considering reducing bundle size

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#676]
### Is your proposal related to a problem?

Now that the v1.0 is released. I think it's good time to start focusing on reducing the bundle size of the overall application.

As for now the main public pages are getting a little bit chunky:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/3504472/133696219-530b8118-f19a-4edc-b76f-483dbe7dc966.png">

### Describe the solution you'd like

As a first step, I'm planning to add a bundle analyzer so we can pinpoint exactly what's causing this chunkyness.

**Comment by zomars** [comment]
And the main culprits are in:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/3504472/133701344-e960882d-f107-4e40-88e1-b04dc877a8ef.png">

**Comment by aguilaair** [comment]
Maybe switching react with [preact](https://preactjs.com/guide/v10/switching-to-preact) on prod could help with bundle sizes. I've had quite good success with it (does not always work, though).

**Comment by baileypumfleet** [comment]
An immediate thing I see here is moment.js. We use day.js, so moment should not be used. Not sure why it's here. Removing that should be an easy way to reduce bundle size

**Comment by baileypumfleet** [comment]
Furthermore, we do need to move away from react-timezone-select anyway, so removing that and it's dependencies would be beneficial to bundle size.

**Comment by PeerRich** [comment]
@zomars has this improved?

**Comment by zomars** [comment]
It may but also there are new packages since then. Will run a new audit and post an update

**Comment by PeerRich** [comment]
lets close this and reopen when we have a new audit
