### ISSUE TITLE
[CAL-957] SIU: Round Robin inconsitencies

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6773]
\:fire: Hi @Emrysal / @PeerRich  We are unfortunately still having issues with the *Round Robin* functionality not behaving properly - which is preventing us from going live. We managed to reproduce at least one of the issues in cal,com proper. The details are attached.

We think it may be similar to an issue in the past with UTC times for long meetings going beyond the day boundary - but not entirely sure. We are also seeing some strange issues in our environment, where we add a person to the round-robin meeting, and by adding them the slots for a given day get reduced (the last slot is no longer offered). (CC: @Heather Murray @Peer @U035KNTE3EJ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-957](https://linear.app/calcom/issue/CAL-957/siu-round-robin-inconsitencies)</sub>

**Comment by adowbor** [comment]
[round-robin-issue-objeto.pdf](https://github.com/calcom/cal.com/files/10528644/round-robin-issue-objeto.pdf)

**Comment by aasargsian** [comment]
We also have very critical issues with round-robin in our environment for 20 days. Also blocking us fom going live. 

Video with steps to reproduce: https://drive.google.com/file/d/1m1UzieZR4sqwIVyCq6_U6S-4hFoiL7TV/view?usp=sharing

1. Create round-robin event for a team 
2. Set up no fixed hosts
3. Choose 2 round-robin hosts
-> Page shows no available slots.

Event shows slots only if scheduling type is collective. Doesn’t work for round-robin

**Comment by aasargsian** [comment]
@zomars I have added a separate report

**Comment by emrysal** [comment]
@PeerRich This was fixed in 2.7 but all communication went over Slack, so this issue has been fixed for a while and is very stale.
