### ISSUE TITLE
[CAL-959] Round-robin doesn't function

### ISSUE THREAD

**Issue by aasargsian** [calcom/cal.com#6782]
### Issue Summary

Round-robin team events are not working in our environment for almost 20 days which is blocking us from going live. 

### Steps to Reproduce

Video with steps to reproduce: https://drive.google.com/file/d/1m1UzieZR4sqwIVyCq6_U6S-4hFoiL7TV/view?usp=sharing

1. Create round-robin event for a team
2. Set up no fixed hosts
3. Choose 2 round-robin hosts
-> Page shows no available slots.
Event shows slots only if scheduling type is collective. Doesn’t work for round-robin

### Technical details

We are using self-hosted platform version

<sub>[CAL-959](https://linear.app/calcom/issue/CAL-959/round-robin-doesnt-function)</sub>

**Comment by PeerRich** [comment]
@emrysal @CarinaWolli

**Comment by reachkrishnaraj** [comment]
I am using a self hosted version @ www.tbd.health and we are seeing this issue too.

**Comment by reachkrishnaraj** [comment]
hey @aasargsian Did you try this ? This seem to fix the issue that I faced on my side as well.

Use default working hours instead of Collective Availability Schedule
Use Round Robin WITHOUT any Fixed Hosts i.e. assign all as Round Robin Hosts
