### ISSUE TITLE
[CAL-966] Admin Users page shows no users

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6785]
### Issue Summary

On the admin page for users, there are no users displayed:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/53020786/215468904-9a71a828-e110-4c5a-8d4f-5f8812220e58.png">

### Steps to Reproduce

Log in as an admin, on a system with other users
Go to Settings -> Admin -> Users
See there are no users listed, like my image above

### Technical details

- Latest Chrome
- Node 16

<sub>[CAL-966](https://linear.app/calcom/issue/CAL-966/admin-users-page-shows-no-users)</sub>

**Comment by PeerRich** [comment]
ah, this moved to console.cal.com. will make a PR addressing this

**Comment by Hybes** [comment]
I respect that you want to have more features in your console for paid users, but this feature surely only allows us to see a list of users and impersonate from the list? Otherwise, how are we supposed to know what accounts have been made?

**Comment by Hybes** [comment]
I believe, that users on our own self-hosted platform, should all be accessible by us, keeping in line with the entire point of self-hosting, which avoids using additional companies and keeping all data internal/on your own servers.

**Comment by PeerRich** [comment]
there is nothing stoppig you from using prisma cloud, postico, or even retool from managing users. we believe the open and free open source code base should cater towards hobbyists and or small teams with less than 100 users which does not require sophisticated user management

most open source tools dont have tools baked into managing the userbase. (wordpress has no usermanagement either)

**Comment by PeerRich** [comment]
and its quite easy for you right now to just look at the username and then impersonate as an admin for one-off changes

**Comment by Hybes** [comment]
perhaps we're misaligned with our visions of what User Management is, but i'd say Wordpress includes user management, it display all the users that exist, allows you to send a password reset, add, or delete users from within the free, self-hosted wordpress.

**Comment by Hybes** [comment]
> and its quite easy for you right now to just look at the username and then impersonate as an admin for one-off changes

how do i look at the username easily? i'd need to know that a user has signed up and what their URL is? I may be running a small server, but if I dont disable signups, anyone can sign up without me knowing?

**Comment by PeerRich** [comment]
something like https://postgresapp.com/ is easy to use, or cloud.prisma.io

just add your db string and then navigate to "Users" table.

Metabase.com would work too if you want a read-only tool

**Comment by PeerRich** [comment]
submitted a fix to link to console

**Comment by Hybes** [comment]
Peer, I understand part of your reasoning behind shutting the ticket for user management, but Wordpress is a poor example, they allow you to view users, that's essentially all this feature should do on all platforms, just query the DB for users would be enough. I am in an environment where no machine can access the DB other than my Cal instance, for safety and security - this should be the case for many users, so therefore how would using something like postgresapp or prisma cloud work in this scenario?

**Comment by PeerRich** [comment]
that is true, however your environment manager can set up a read only metabase or retool. 

I dont think most tools will also provide in-depth user management as we want to provide for commercial customers

**Comment by PeerRich** [comment]
what environment are you in? If its educational or non-profit or similar we have big discounts on the commercial license which is recommended for any "bigger" use case that requires a lot more user managemnt

**Comment by Hybes** [comment]
currently in development environment still, but I'm not expecting this feature to provide any in-depth features, purely a list of users as it quite frankly says it should "User Listing" - it doesn't need to be much more than that, perhaps just a button with it to straight away impersonate, but even thats not really needed.

**Comment by Hybes** [comment]
the data's already there, i mean the query is even already there - it should just be a list of users at minimum? is that unreasonable?

**Comment by PeerRich** [comment]
that is something that *you* expect, just a list, but others want editing, deleting, etc. 

we simply cant move this into the free open core

**Comment by Hybes** [comment]
understood, a list seems fair to be in the free package, but hey ho, no point trying to further justify it

**Comment by PeerRich** [comment]
i wish we had the capacity to make everything free, and not charge anyone. I know its painful to make these decisions which is why we have a framework for this:

- does it not restrict hobby plans?
- are there alternatives? (there is: metabase.com, postico, postgres.app)
- does it only impact big instances with >100 users

=> make it console.cal.com only

**Comment by PeerRich** [comment]
we could think about a list only and then link to the console plan if you need more. let me think about it. you are, however, the first person to ask for user management in the FOSS plan

**Comment by PeerRich** [comment]
can you not just ask them to send you the link? i mean thats what we do since its a lot faster than looking in the user management table

**Comment by Hybes** [comment]
> what company/org is this for? Let me see if you qualify for a commercial licence discount. Again, hobby plans and small teams don't need user management

I'm not qualify for any discounts, it's all still development for hobby/small team work. nothing that's even close to commercial - helping out local's in the village is the plan in a few months.

**Comment by PeerRich** [comment]
i see. then why can you not access prod db if its just you?

**Comment by Hybes** [comment]
> can you not just ask them to send you the link? i mean thats what we do since its a lot faster than looking in the user management table

course we can - and i guess it's what we're going to have to do 😛

**Comment by PeerRich** [comment]
can you ask your admin for a metabase.com instance and make you a dashboard of the User table. literally takes 2 mins

**Comment by Hybes** [comment]
> i see. then why can you not access prod db if its just you?

runs on a cloud server, and im not always at home XD

**Comment by PeerRich** [comment]
we need to draw the line at some point of what we can justify moving into the core and what not hehe. if we dont draw the line people will ask for things way beyond user management, etc.

**Comment by Hybes** [comment]
i'll take a deeper look at this other sites to manage the DB, but my main thoughts are that the data is already being queried in [user].tsx to why it can't be just displayed was my struggle to see past this paywall, but again - ultimately it's up to you and your team, and if you don't see it fit, I'll just move on haha

**Comment by PeerRich** [comment]
i mean since you are self-hosting you can just call that endpoint yourself and display it there, no?

**Comment by Hybes** [comment]
it's possible yeah, im just explaining my reasoning behind the issue
