### ISSUE TITLE
[CAL-963] ability to "plan" your timezone in the future when traveling

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6790]
As someone who travels frequently, I want the ability to schedule a timezone change for a specific date range in the future.

**User flow**

* I should be able to go into my General settings and where I edit my timezone, see an action to "Schedule a timezone change".
* This will open a modal with a date range selection and the timezone editor.
* I enter my dates, pick the timezone (of the location I will be travelling to) and click confirm.
* I can then see the timezone override below the timezone select. Format:
* 
  * (GMT+01:00) Central European Standard Time
* 
  * March 1, 2023 — March 31, 2023
* I can also delete it

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/03b38a3e-daa2-4888-ad2f-4609a1186803/d6839eff-e1fb-4c46-83d1-d4ac78c71490)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-963](https://linear.app/calcom/issue/CAL-963/ability-to-plan-your-timezone-in-the-future-when-traveling)</sub>

**Comment by PeerRich** [comment]
could this live in the Date Overwrite?

**Comment by McPizzaIs** [comment]
Adding the ability to select a range of dates, and change timezone within "Date Override" would solve this.
Currently its on a per day basis which could be annoying to set up for longer trips.

Another alternative is to create a separate Availability calendar, and allow the event to schedule switching between them. 
i.e. On Feb 1st use "Home Working Availability", On Feb 15th use "On the Road", Feb 22nd back to "Home Working"

**Comment by harshsinghatz** [comment]
@McPizzaIs Yes i think adding a date range would be essential here. @PeerRich  Can i please work on this??

**Comment by PeerRich** [comment]
we would need to discuss this internally and research first and probably do some designs, too

**Comment by harshsinghatz** [comment]
@PeerRich Cool, lmk if i can work on this

**Comment by Jaibles** [comment]
> could this live in the Date Overwrite?

I would do it in settings alongside your timezone. It's more about ensuring you don't change your availability when you travel 
ie I always want to be available 9-5 when whether I'm in London or New York. 
Perhaps we could put something in availability to link to it, but ultimately it's a timezone change not an availability one

**Comment by McPizzaIs** [comment]
@Jaibles I think there's also use cases for when you're traveling you have less availability, or only availability during specific hours.

The settings/general would just shift the current availability +/- specific hours depending on TZ diff - correct?

**Comment by Jaibles** [comment]
If you have a timezone change scheduled, you could then set a date override in availability?

So timezone change:
- Feb 1st to 14th - San Diego timezone

Date override
- Feb 1st to 14th - 1pm - 5pm

I can see why it would be good to communicate the timezone override in availability, and communicate that you can set this up - but these features should work largely independent to each other right?

**Comment by Jaibles** [comment]
[![See Figma Designs](https://shields.io/badge/-designs-black?logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGlkPSJMYXllcl8xIiB2aWV3Qm94PSIwIDAgMjAwIDMwMCIgd2lkdGg9IjE2NjciIGhlaWdodD0iMjUwMCI+PHN0eWxlIHR5cGU9InRleHQvY3NzIj4uc3Qwe2ZpbGw6IzBhY2Y4M30uc3Qxe2ZpbGw6I2EyNTlmZn0uc3Qye2ZpbGw6I2YyNGUxZX0uc3Qze2ZpbGw6I2ZmNzI2Mn0uc3Q0e2ZpbGw6IzFhYmNmZX08L3N0eWxlPjx0aXRsZT5GaWdtYS5sb2dvPC90aXRsZT48ZGVzYz5DcmVhdGVkIHVzaW5nIEZpZ21hPC9kZXNjPjxwYXRoIGlkPSJwYXRoMF9maWxsIiBjbGFzcz0ic3QwIiBkPSJNNTAgMzAwYzI3LjYgMCA1MC0yMi40IDUwLTUwdi01MEg1MGMtMjcuNiAwLTUwIDIyLjQtNTAgNTBzMjIuNCA1MCA1MCA1MHoiLz48cGF0aCBpZD0icGF0aDFfZmlsbCIgY2xhc3M9InN0MSIgZD0iTTAgMTUwYzAtMjcuNiAyMi40LTUwIDUwLTUwaDUwdjEwMEg1MGMtMjcuNiAwLTUwLTIyLjQtNTAtNTB6Ii8+PHBhdGggaWQ9InBhdGgxX2ZpbGxfMV8iIGNsYXNzPSJzdDIiIGQ9Ik0wIDUwQzAgMjIuNCAyMi40IDAgNTAgMGg1MHYxMDBINTBDMjIuNCAxMDAgMCA3Ny42IDAgNTB6Ii8+PHBhdGggaWQ9InBhdGgyX2ZpbGwiIGNsYXNzPSJzdDMiIGQ9Ik0xMDAgMGg1MGMyNy42IDAgNTAgMjIuNCA1MCA1MHMtMjIuNCA1MC01MCA1MGgtNTBWMHoiLz48cGF0aCBpZD0icGF0aDNfZmlsbCIgY2xhc3M9InN0NCIgZD0iTTIwMCAxNTBjMCAyNy42LTIyLjQgNTAtNTAgNTBzLTUwLTIyLjQtNTAtNTAgMjIuNC01MCA1MC01MCA1MCAyMi40IDUwIDUweiIvPjwvc3ZnPg==&style=for-the-badge)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=2844%3A199062&t=OFGRK9CmDnuhWjAB-1)

**Comment by PeerRich** [comment]
@Jaibles lets revisit this for 3.2

**Comment by mxstbr** [comment]
Strong +1 👍 to this. SavvyCal has this feature and it's a lifesaver for a leadership role where I travel across timezones frequently and want to make sure people schedule meetings at the right time:

<img width="779" alt="CleanShot 2023-11-22 at 11 26 33@2x" src="https://github.com/calcom/cal.com/assets/7525670/789073f8-7fc7-4d90-8eae-e49b2bd17537">

**Comment by ronissim** [comment]
+1 for this - a few notes:
* Ithink it would be most powerful to allow both shifting hours and availability times. This is especially important as different metting types have different availability and I wouldn’t want to have to update the time zone for each meeting type separately
* Expose an api for this
* I used chatgpt to identify flights in my calendar and auto identify what time zone I’ll be in - it was easy so might be easy for you to add as well and suggest an auto time zone shift
* Ideally I’d like to not allow scheduling a f2f meeting (one of my meeting types) when I’m traveling

**Comment by ronissim** [comment]
Reopening this as the feature was added under "schedule timezone change'
Can you please add a public API endpoint for this? I'd like to automatically schedule changes based off of a travel app.
I would also like to disable certain meetings types while traveling (the f2f ones)
