### ISSUE TITLE
[CAL-964] unpublished teams have url: /null/

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6793]
i believe @zomars may know more

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-964](https://linear.app/calcom/issue/CAL-964/unpublished-teams-have-url-null)</sub>

**Comment by harshsinghatz** [comment]
@PeerRich more info on this?

**Comment by PeerRich** [comment]
i just saw it in a screenshare, basically if a team has no valid billing method, it gets unpublished. on the event-type site it'll show the slug. "/null/"

**Comment by zomars** [comment]
That is correct @PeerRich is this in self-hosted tho? It shouldn't happen on self hosted

**Comment by PeerRich** [comment]
both is on app.cal.com

**Comment by PeerRich** [comment]
i think we should find an alternative way to unpublish teams vs making it `null`

**Comment by PeerRich** [comment]
it could also throw a better error than a 404. not sure what. i wonder what other tools do
