### ISSUE TITLE
[CAL-965] Backslash or apostrophe not rendering correctly in bookings tab/confirmation email

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6798]
Backslash or apostrophe not rendering correctly in bookings tab/confirmation email.

Confirmation email details: Gmail browser version

Created via Threads. See full discussion: [https://threads.com/34444985754](https://threads.com/34444985754)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-965](https://linear.app/calcom/issue/CAL-965/backslash-or-apostrophe-not-rendering-correctly-in-bookings)</sub>

**Comment by G3root** [comment]
fixed by #7591
