### ISSUE TITLE
[CAL-967] Add the ability to schedule a timezone change

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6804]
As someone who travels frequently, I want the ability to schedule a timezone change for a specific date range in the future.

User flow

* I should be able to go into my General settings and where I edit my timezone, see an action to "Schedule a timezone change".
* This will open a modal with a date range selection and the timezone editor. 
* I enter my dates, pick the timezone (of the location I will be travelling to) and click confirm.
* I can then see the timezone override below the timezone select. Format:
  * (GMT+01:00) Central European Standard Time
  * March 1, 2023 — March 31, 2023
* I can also delete it

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-967](https://linear.app/calcom/issue/CAL-967/add-the-ability-to-schedule-a-timezone-change)</sub>

**Comment by McPizzaIs** [comment]
I think this could be merged with #6790

**Comment by Jaibles** [comment]
Closing as it's a duplicate.
