### ISSUE TITLE
[CAL-984] Metadata is ignored when you create a booking.

### ISSUE THREAD

**Issue by pavnaumenko** [calcom/cal.com#6808]
### Issue Summary

Metadata is ignored when you create a booking.

### Steps to Reproduce

1. Add metadata to query parameters of the event link, e.g. `http://localhost:3000/john-foo-zrurxq/30min?metadata[user_id]=123`
2. Open the link in the browser;
3. Book a meeting.
4. Call the `GET v1/bookings` endpoint and find created booking.

Expected: To see created booking with `metadata` provided in query params.
Actual: `metadata` is null.

<sub>[CAL-984](https://linear.app/calcom/issue/CAL-984/metadata-is-ignored-when-you-create-a-booking)</sub>

**Comment by PeerRich** [comment]
@baileypumfleet this used to work, right? i believe you were working on this a long time ago. who could investigate this?

**Comment by G3root** [comment]
@PeerRich is this open ?

**Comment by PeerRich** [comment]
not yet. go for it!
