### ISSUE TITLE
[CAL-970] Date overrides section in availability isn't translated

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6811]
date overrides section in availability isn't translated

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/907406a5-3564-4033-98ce-6107ae5fc52d/84053921-9578-45f8-a76d-f2aa7b5cb16e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-970](https://linear.app/calcom/issue/CAL-970/date-overrides-section-in-availability-isnt-translated)</sub>

**Comment by joeshajan** [comment]
Can you explain more on this?

**Comment by PeerRich** [comment]
it's a translation issue, not a code issue. will get our translation team going on it
