### ISSUE TITLE
[CAL-972] fix "create your own booking link" input box

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6814]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-972](https://linear.app/calcom/issue/CAL-972/fix-create-your-own-booking-link-input-box)</sub>

**Comment by joeshajan** [comment]
Hey, @PeerRich I'm new to calcom. So need some help.

Are you talking about this input box? If yes what's the issue here?

![image](https://user-images.githubusercontent.com/69904519/215821732-e024a8a3-83de-464a-9571-fbea71c56d2e.png)

**Comment by joeshajan** [comment]
Am I able to access linear. If yes how?

![image](https://user-images.githubusercontent.com/69904519/215823464-e646b3b3-a023-4574-a79d-889d990ce1bd.png)

**Comment by PeerRich** [comment]
someone of our team actually submitted a fix for this already. closing!
