### ISSUE TITLE
[CAL-974] Stripe team event does not work with hosts that do not have Stripe setup correctly

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#6820]
### Issue Summary

When an event type is configured with stripe, if a booking tries to be made with a host that does not have a connected Stripe account; the booking throws an error. Untested on Collective event but I imagine the same happens.

### Steps to Reproduce

1. Setup a team event with Stripe payments
2. Add a couple of round-robin hosts
3. Don't connect install the Stripe app on those hosts
4. (Attempt to) make a booking

### What should happen instead?

@PeerRich to fill in, but the host should be excluded from the round-robin event / collective event and needs to be notified.
And / or the host shouldn't be allowed to be installed if he doesn't have Stripe installed in the first place.

<sub>[CAL-974](https://linear.app/calcom/issue/CAL-974/stripe-team-event-does-not-work-with-hosts-that-do-not-have-stripe)</sub>

**Comment by alannnc** [comment]
I think we should start using team credentials.

**Comment by PeerRich** [comment]
how important is this? seems to get stale right now

**Comment by alannnc** [comment]
I think this will be solved once orgs apps goes live. Let's wait on that and make a test for it.

@PeerRich

**Comment by alannnc** [comment]
Closing as it no longer should be an issue since we created team credentials.
