### ISSUE TITLE
[CAL-976] /teams: Unpublished teams are only visible if there is at least one published team

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6827]
loom: [https://www.loom.com/share/184fc127a1094a99ab5d0651923b0f76](https://www.loom.com/share/184fc127a1094a99ab5d0651923b0f76)

we may wanna rethink how we identify unpublished teams in general @zomars maybe a status?

status === "PUBLISHED"
status === "UNPUBLISHED"

etc.

currently we only check for "has slug" and then return "Unpublished team" if there is no slug

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ef6641ed-d5d1-4097-951c-478e0cfe16e0/f1a6b586-ebbc-4cd4-afd5-4781f5feb874)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-976](https://linear.app/calcom/issue/CAL-976/teams-unpublished-teams-are-only-visible-if-there-is-at-least-one)</sub>

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, after looking into the issue we discovered the following:

`TeamListing` is  a child component of `UpgradeTip` that gets rendered by `UpgradeTip` only if `hasPaidPlan` is `true`
https://github.com/calcom/cal.com/blob/c3d6df2dcfd7d52b71b573833c2489568da88dbf/packages/features/tips/UpgradeTip.tsx#L36-L38

But `hasPaidPlan` is returned `false` from `hasTeamPlan` if `slug` is `null`, which is the case for "Unpublished" teams
https://github.com/calcom/cal.com/blob/c3d6df2dcfd7d52b71b573833c2489568da88dbf/packages/trpc/server/routers/viewer/teams.tsx#L699-L709

So, to display the "unpublished" team, we have to update the above query.

How do you think this should be handled?

**Comment by PeerRich** [comment]
> Hi @PeerRich, after looking into the issue we discovered the following:
> 
> `TeamListing` is a child component of `UpgradeTip` that gets rendered by `UpgradeTip` only if `hasPaidPlan` is `true`
> 
> https://github.com/calcom/cal.com/blob/c3d6df2dcfd7d52b71b573833c2489568da88dbf/packages/features/tips/UpgradeTip.tsx#L36-L38
> 
> But `hasPaidPlan` is returned `false` from `hasTeamPlan` if `slug` is `null`, which is the case for "Unpublished" teams
> 
> https://github.com/calcom/cal.com/blob/c3d6df2dcfd7d52b71b573833c2489568da88dbf/packages/trpc/server/routers/viewer/teams.tsx#L699-L709
> 
> So, to display the "unpublished" team, we have to update the above query.
> 
> How do you think this should be handled?

i dont think that solves it. let me ping @zomars

**Comment by PeerRich** [comment]
@zomars i think this has been fixed
