### ISSUE TITLE
[CAL-977] event type settings - Turning on "Offer seats" creates confusion notification for "Opt-in"

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6828]
[https://www.loom.com/share/952e4f6a9b394616bc653bec2cc847e7](https://www.loom.com/share/952e4f6a9b394616bc653bec2cc847e7)

**What is happening**

* When I turn on "Offer seats" we're throwing a warning in the "Requires confirmation" setting.

**Problem**

* It's making me think something is wrong given the visual treatment we're giving it. Particularly if you contrast this to what we do with "Disable Guests" right below where we just set it accordingly and disable it.

**What we should do**

* Toggle the "Requires confirmation" OFF and disable it.
* When hovering on the toggle, we should show a tooltip explaining why you can't toggle it on.

I will add designs for this but the instructions above should provide clarity to get started.

We have a disabled tooltip [in our DS](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=534%3A32275&t=eDni2uRGkdAQr6az-1), and also a tooltip on hover.

![CleanShot 2023-02-01 at 12.05.53@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cb5672dc-2501-4a7d-bacb-330f4412e01f/4c3da44e-88b7-45fb-973a-36db34e4eb0b)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-977](https://linear.app/calcom/issue/CAL-977/event-type-settings-turning-on-offer-seats-creates-confusion)</sub>

**Comment by Udit-takkar** [comment]
@Jaibles the loom link is not working

**Comment by Jaibles** [comment]
I'll re-record.
