### ISSUE TITLE
Let guests provide their own call-in link

### ISSUE THREAD

**Issue by sigikluckner** [calcom/cal.com#6834]
### Is your proposal related to a problem?

As freelancer, we tend to be pretty agnostic to video calling platforms; if a client would like to use their own, I would want to allow them to provide a link. 

### Describe the solution you'd like

Analogue to "attendee address" or "attendee phone number", add another option for a link and optional password field for using their conference tool. 

### Describe alternatives you've considered

Currently using the "attendee address" and asking them to paste the link in there, but it does not allow for an additional password.

**Comment by PeerRich** [comment]
does this happen often? can you make an example where this is useful?

**Comment by sigikluckner** [comment]
My default is Teams, and I found it difficult for some people to use Teams for variety of reasons (firewall & company policies), so we sometimes have to switch to their instance of <whatever> during the meeting time, mostly zoom or webex (and since they already have a license... ;-) ). It should work with the address, but of course might be misleading for people who read the details..

**Comment by PeerRich** [comment]
i would recommend to use a "booking question" for this edge case
