### ISSUE TITLE
Script to Extract Translatable Keys

### ISSUE THREAD

**Issue by AaronPresley** [calcom/cal.com#6836]
### Is your proposal related to a problem?

Based on [this tweet](https://twitter.com/peer_rich/status/1620771067173404676) from @PeerRich. 

### Describe the solution you'd like

From my experience in G11N, I have a handful of scripts that allow the ability to traverse a given codebase and extract translatable keys from a given pattern. I will use these same patterns to enable this within the `calcom` codebase.

For now I'll create this code as a `calcom` package. Eventually I've wanted to put these scripts into an open source dependency, but that would add additional delay.

Note that this will not be a heavily optimized script, and is NOT intended to be called at runtime. It's rather intended to be run locally on a machine to simplify the process of gathering translatable strings.

### Describe alternatives you've considered

There are a handful of options that operate as IDE as extensions. In my experience they work very unreliably, and are typically strongly correlated with a specific I18N library. My preferred approach is one that makes very few assumptions on specific libraries or frameworks.

### Additional context

Currently a single translatable string's format looks something like the following:
```jsx
<Button>{t("some_label_here")}</Button>
```
While this approach is _fine_, it isn't ideal. A better approach would be something like the following:

```jsx
<Button>{t("some_label_here", "Some Default Value", "This some label on the button")}</Button>
```
This approach would enable a script to automatically extract "Some Default Value" into a translatable file. The third parameter would be a description of the text for the benefit of the translator. This would allow for a better Developer Experience, as they would be able to create new translatable keys within the code itself, and rely on the extraction script to move the default value into a new file for translation.

This ticket will _not_ include the above, but I'm clarifying here for the sake of future improvements.

**Comment by PeerRich** [comment]
ha, someone messaged me they build a VSCode plugin that doenst. will test this week
