### ISSUE TITLE
<UpgradeScreen> component has untranslated keys

### ISSUE THREAD

**Issue by AaronPresley** [calcom/cal.com#6838]
### Issue Summary

It seems [this PR](https://github.com/calcom/cal.com/pull/6594) has resulted in the following bug:

![image](https://user-images.githubusercontent.com/155617/216168900-11470170-f129-4f19-a5e3-8aad753aeee7.png)

As you can see, it seems the component is outputting the key name instead of the translation value belonging to the given key.

### Steps to Reproduce

1. Be a pro user
2. Go to https://cal.com/teams

I'm guessing this is a very minor issue, but should be an easy fix.

**Comment by PeerRich** [comment]
fixed already, should be live today
