### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by Zo-Bro-23** [calcom/cal.com#6839]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Login with Google not working. Using email/password gives the error message "Your account was created using an Identity Provider".

### Steps to Reproduce

1. Went to https://cal.com.
2. Clicked "Login" in the top right.
3. Clicked "Sign in with Google".
4. Nothing happened.

Open clicking "Sign in with Google", the browser redirects to https://app.cal.com/auth/login?callbackUrl=https%3A%2F%2Fapp.cal.com%2Fauth%2Flogin&error=OAuthSignin. Nothing else happens, and clicking the button again only adds this URL as the callback URL. That is, https://app.cal.com/auth/login?callbackUrl=https%3A%2F%2Fapp.cal.com%2Fauth%2Flogin%3FcallbackUrl%3Dhttps%253A%252F%252Fapp.cal.com%252Fauth%252Flogin%253FcallbackUrl%253Dhttps%25253A%25252F%25252Fapp.cal.com%25252Fauth%25252Flogin%26error%3DOAuthSignin&error=OAuthSignin.

Using Chrome DevTools, Sentry seems to be giving a 429 error, but that shouldn't affect the Google login. No other errors are showing up in either the Console or Network tabs.

### Technical details

- Browser version: 108.0.5359.71
- Operating system: Ubuntu 20.04.1 LTS
- Node.js version: NA
- Screen recording: [BirdEatsBug recording](https://app.birdeatsbug.com/sessions/vqWpyGl-p021tS2SCuolgIozkAmLNQuoQcq6SqNcSgpT?consolePane=true)

**Comment by emrysal** [comment]
We have reverted v2.5.7 pending investigation

**Comment by Zo-Bro-23** [comment]
Fixed 🎉
