### ISSUE TITLE
[CAL-983] After 26th none of the slots can be booked from 8 to 9 am

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6844]
No available user found error on each slot from 8 - 9 am. Happens only after the 26th of March (CET summer time)

(Attachment: )

Created via Threads. See full discussion: [https://threads.com/34445914943](https://threads.com/34445914943)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-983](https://linear.app/calcom/issue/CAL-983/after-26th-none-of-the-slots-can-be-booked-from-8-to-9-am)</sub>

**Comment by gchenavier** [comment]
Good morning, I have the same problem, the first slot of the day causes the error from the time change. it is very penalizing for our activity.

**Comment by gchenavier** [comment]
UP

**Comment by milospuac** [comment]
Hi, there. @emrysal is still investigating this one.

**Comment by roae** [comment]
Fixed on #7792
