### ISSUE TITLE
Dark mode for dashboard

### ISSUE THREAD

**Issue by bvairet** [calcom/cal.com#6845]
### Is your proposal related to a problem?

The dark mode is as important or more important for the admin part than for the client part. I personally work all day on a computer and white backgrounds break my eyes.

### Describe the solution you'd like

Simple dark mode for dashboard.

### Describe alternatives you've considered

There is not.

### Additional context

No.

**Comment by PeerRich** [comment]
coming, not sure when

**Comment by McPizzaIs** [comment]
Using https://github.com/RyanClementsHax/tailwindcss-themer, you would only need to implement the theme switcher, and customize the colors for the dark theme.

All components can keep their current TW color references, and for anything that looks a bit off, or needs tweaking, you can add the traditional 'dark:' overwrite.

I can see imports of @calcom/config/tailwind-preset but can't locate it in any repos.

**Comment by PeerRich** [comment]
ohohhh interesting! i would love to have an option that doenst require dark: everywhere and this looks nice

**Comment by sean-brydon** [comment]
> Using https://github.com/RyanClementsHax/tailwindcss-themer, you would only need to implement the theme switcher, and customize the colors for the dark theme.
> 
> All components can keep their current TW color references, and for anything that looks a bit off, or needs tweaking, you can add the traditional 'dark:' overwrite.
> 
> I can see imports of @calcom/config/tailwind-preset but can't locate it in any repos.

Hey - our tailwind base is located https://github.com/calcom/cal.com/blob/main/packages/config/tailwind-preset.js 

We have an issue where our dark colors are not an exact 1-1 swap but this is deffo a good shout. Thanks for the suggestion will see how far we can get with this :)

**Comment by McPizzaIs** [comment]
Ah perfect @sean-brydon I guess the search failed me.

Ping me if anything goes awry!

**Comment by sean-brydon** [comment]
> Ah perfect @sean-brydon I guess the search failed me.
> 
> Ping me if anything goes awry!

Will do! Is this something you were wanting to give a shot or shall I pick this up when i get time?

**Comment by PeerRich** [comment]
@sean-brydon feel free to pick this up and give it a try

**Comment by sean-brydon** [comment]
Oh this is done :)
