### ISSUE TITLE
[CAL-987] Progressive web app

### ISSUE THREAD

**Issue by bvairet** [calcom/cal.com#6847]
### Is your proposal related to a problem?

Managing my reservation calendar from my cell phone is not easy.

### Describe the solution you'd like

A progressive webapp, easier to set up than a mobile application.

### Describe alternatives you've considered

There is not.

### Additional context

No.

<sub>[CAL-987](https://linear.app/calcom/issue/CAL-987/progressive-web-app)</sub>

**Comment by PeerRich** [comment]
you can add app.cal.com to your homescreen which will open as a full-screen app. we don't have service workers yet for storing UI etc.

**Comment by PeerRich** [comment]
thats odd

**Comment by zomars** [comment]
@bvairet care to share screen recording or screenshot? 

https://user-images.githubusercontent.com/3504472/218835330-b158eeb9-57a6-4cf4-bac9-6bf303060b05.MP4
