### ISSUE TITLE
[CAL-988] Limit total appointment time per day/week/month

### ISSUE THREAD

**Issue by bvairet** [calcom/cal.com#6852]
### Is your proposal related to a problem?

I want to control the amount of time I spend per day on appointments. Example, no more than 4 hours on Tuesday, no more than 6 hours on Wednesday, etc.

### Describe the solution you'd like

I would like a time limit function per day/week/month to block my calendar if I am overloaded.

### Describe alternatives you've considered

The current appointment limit function is not effective, as not all appointments have the same duration. In my opinion, it is a useless function that should be replaced by a duration limit function.

### Additional context

No.

<sub>[CAL-988](https://linear.app/calcom/issue/CAL-988/limit-total-appointment-time-per-dayweekmonth)</sub>

**Comment by PeerRich** [comment]
you can do that already in "limits" in event-types

**Comment by PeerRich** [comment]
that is true i didnt read the issue correctly.

**Comment by PeerRich** [comment]
i think it depends on the person. i think adding a time limit makes sense. will discuss with the team

**Comment by ShaneMaglangit** [comment]
Hey @PeerRich , just wondering if this is already being worked on? Otherwise, I would love to work on this.

Are there any discussion on how this feature would be implemented?
- Should we replace the existing booking limit (frequency) as OP suggested?
- Or, do we implement it as a new option while retaining the previous ones?

**Comment by PeerRich** [comment]
go for it! there is an open bounty too 

> 📝 To bid on this bounty, [click here](https://console.algora.io/bounties/cldokfd350000la082gddrpgb)

**Comment by PeerRich** [comment]
no it should not replace the current limit. it should be another option

**Comment by ShaneMaglangit** [comment]
Working on it, thanks!

**Comment by PeerRich** [comment]
@bvairet can you look at this? https://www.loom.com/share/c494bbe683604d349a7dd9ec889b1dac

**Comment by PeerRich** [comment]
agree

**Comment by ShaneMaglangit** [comment]
> > @bvairet can you look at this? https://www.loom.com/share/c494bbe683604d349a7dd9ec889b1dac
> 
> @PeerRich very nice, that would be even better to set up multiple time limit frequency, for instance : no more than 4h a day, no nore than 16h a week

Hi, the button to add limits was hidden in the Avatar on the bottom left but this should already be possible in that same preview 😄

**Comment by ShaneMaglangit** [comment]
https://www.loom.com/share/bdbbb945a2cb49fc8ebe84be75960de9

**Comment by ShaneMaglangit** [comment]
> go for it! there is an open bounty too
> 
> > 📝 To bid on this bounty, [click here](https://console.algora.io/bounties/cldokfd350000la082gddrpgb)

Hi @PeerRich, I just recalled that there was a bounty for this. Just wondering if its not too late to submit a bid?

**Comment by ShaneMaglangit** [comment]
> I am not sure to understand how it works. Why is the topic closed ? What is a bounty, what is a bid ? The feature is ready yet or finally won’t be added ? The answer is not clear to me as a non developer.

Hi @bvairet, you may expect the feature (as demonstrated in the loom video) to be added on the next version release AFAIK.

**Comment by ShaneMaglangit** [comment]
> > go for it! there is an open bounty too
> > > memo To bid on this bounty, [click here](https://console.algora.io/bounties/cldokfd350000la082gddrpgb)
> 
> Hi @PeerRich, I just recalled that there was a bounty for this. Just wondering if its not too late to submit a bid?

Following up on this 😅 cc @PeerRich

**Comment by PeerRich** [comment]
@ShaneMaglangit  I think you can submit a bid here: https://console.algora.io/bounties/cldokfd350000la082gddrpgb

**Comment by ShaneMaglangit** [comment]
> @ShaneMaglangit I think you can submit a bid here: https://console.algora.io/bounties/cldokfd350000la082gddrpgb

I'm not familiar with the usual rate for the bounties. I would appreciate if you can suggest an appropriate amount. Thanks!

**Comment by PeerRich** [comment]
i gave it $200

**Comment by PeerRich** [comment]
@ShaneMaglangit can you increase the min-width?

**Comment by ShaneMaglangit** [comment]
> @ShaneMaglangit can you increase the min-width?

Definitely, I send a PR for this soon.
