### ISSUE TITLE
[CAL-990] Team event type not showing the correct first day of the week

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6870]
Regular event type and team event type from the same account side by side.

(Attachment: 2 attachments (1/2))(Attachment: 2 attachments (2/2))

Created via Threads. See full discussion: [https://threads.com/34446320535](https://threads.com/34446320535)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-990](https://linear.app/calcom/issue/CAL-990/team-event-type-not-showing-the-correct-first-day-of-the-week)</sub>

**Comment by G3root** [comment]
@emrysal  does the team should have a separate section for configuring the week start or it should take the value from the event type owner ?
