### ISSUE TITLE
[CAL-991] When radix menu is active - it removes rounded

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6872]
When opening a radix dropdown on event types it for some reason removes rounded on parent 

<img width="207" alt="CleanShot 2023-02-03 at 16 47 39@2x" src="https://user-images.githubusercontent.com/55134778/216660147-9da12d0c-9fcf-4561-94ba-1da2af1030e0.png">

_Originally posted by @sean-brydon in https://github.com/calcom/cal.com/pull/6871#pullrequestreview-1283319310_
            

<sub>[CAL-991](https://linear.app/calcom/issue/CAL-991/when-radix-menu-is-active-it-removes-rounded)</sub>

**Comment by PeerRich** [comment]
i think @gitstart-calcom has an open PR to address this

**Comment by PeerRich** [comment]
does this fix it? https://github.com/calcom/cal.com/pull/6854

**Comment by gitstart-calcom** [comment]
Yes, this issue has been addressed in #6854 
<img width="254" alt="Screenshot 2023-02-07 at 7 28 43 AM" src="https://user-images.githubusercontent.com/121884634/217126653-07e1299a-8568-40c5-917b-261d4baedaba.png">

**Comment by darshandamre** [comment]
looks like this is fixed, can we close this issue? @sean-brydon @PeerRich
