### ISSUE TITLE
[CAL-993] Multiple destination calendar support

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#6875]
As a user with multiple active calendars, I would prefer avoiding having to share the heck out of my calendars to see my events across them just by being able to mark more than one calendar as destination.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-993](https://linear.app/calcom/issue/CAL-993/multiple-destination-calendar-support)</sub>

**Comment by PeerRich** [comment]
wait, we can already connect multiple calendars. are you asking to add the same event to multiple ones?

**Comment by leog** [comment]
> wait, we can already connect multiple calendars. are you asking to add the same event to multiple ones?

@PeerRich exactly
