### ISSUE TITLE
[CAL-995] date overwrite buttons misaligned

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6888]
* [ ] (i) button wrong size and color
* [ ] button group misaligned

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a805ae77-1d01-4147-a0eb-206cad5c13cc/29c88df8-df2a-4edc-b47c-5a22f4a0c08d)

supposed to be:

figma: [https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=841%3A103063&t=SSDLKvFXcAmQOPR7-4](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=841%3A103063&t=SSDLKvFXcAmQOPR7-4)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8b20fc59-f82c-4944-a341-1b8817ee7d3d/377add79-84d6-4f92-90b1-6c74eb15f24a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-995](https://linear.app/calcom/issue/CAL-995/date-overwrite-buttons-misaligned)</sub>

**Comment by saideepesh000** [comment]
hey @PeerRich , can u assign this to me, I'm working on it

**Comment by PeerRich** [comment]
assigned @saideepesh000
