### ISSUE TITLE
Apple Calendar Authentication Error

### ISSUE THREAD

**Issue by xdaluca** [calcom/cal.com#6889]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Apple Calendar Authentication Error "Cannot destructure property 'auth' of 'e' as it is © undefined."

### Steps to Reproduce

1. Go to Add calendar
2. Clicked on apple calendar
3. add login and password
-> GET ERROR (See screenshot)

### Technical details

- Brave browser [Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64)](https://brave.com/latest/)
![Screenshot 2023-02-05 at 11 55 30](https://user-images.githubusercontent.com/80516439/216815029-7ed70af7-198a-4e28-9431-519003c5ade3.jpg)

**Comment by PeerRich** [comment]
did you use an app-specific password? make sure to not use your apple ID. use this: https://appleid.apple.com/account/manage
