### ISSUE TITLE
[CAL-1688] Inconsistent time availability slots on current day in the middle of availability

### ISSUE THREAD

**Issue by odicho** [calcom/cal.com#6896]
### Issue Summary

Inconsistent availability slots when the current day is in the middle of an availability time interval.

### Steps to Reproduce

I will give an example on reproduction for my scenario, you can edit the times based on your current date/time. Right now, it is 15:16 local time for me on Sunday.
1. Set availability for 09:00 - 17:00 (with event length of 35 minutes) on Sunday, and any other day in the future just for reference.
2. Since my local time is 15:16, it will obviously only show me the availabilities in the future, in my case: [15:45, 16:20]
3. Then go to a day in the future and look at the availabilities: [..., 14:50, 15:25, 16:00, ...]

The problem is this inconsistency. The availability seems to be computed depending on the current time, which is not correct for a booking system. As someone who wants to have time slots throughout the day, you want them to be static and consistent. So in this example, I am expecting time slots to be [15:25, 16:00]. It's a bit difficult to explain, so let me know if that didn't make any sense.

<sub>[CAL-1688](https://linear.app/calcom/issue/CAL-1688/inconsistent-time-availability-slots-on-current-day-in-the-middle-of)</sub>

**Comment by emrysal** [comment]
Hi @odicho this should now be fixed - we've reworked our slot logic from the ground up and we no longer use the beginning of the day as our starting point. Feel free to re-open if you have further suggestions; your feedback was much appreciated.

**Comment by odicho** [comment]
Thank you so much, I'm amazed at how effective you are! I haven't looked at the repo for a while but I'll see if I can block some time to inspect the overall algorithm to find anything else. I can definitely tell that the repo is growing at a quick pace so it's definitely important to be diligent with the correctness of this core part of the product.
