### ISSUE TITLE
Calendar shows availability that lets attendee book a time that goes beyond the set availability.

### ISSUE THREAD

**Issue by odicho** [calcom/cal.com#6897]
### Issue Summary

If I have availability from 09:00 - 17:00, it is expected that the earliest booking can occur at 09:00, and the latest booking can at most end at 17:00. It is currently possible for an attendee to book a 35 minute time slot at 16:35, with an ending time of 17:10, which is incorrect.

### Steps to Reproduce

1. Set availability 09:00 - 17:00 for any day in the future (to see all the slots from startTime to endTime)
2. Set event length 35 minutes and also show available slots every 35 minutes.
3. Observe available time slot at 16:35.

![image](https://user-images.githubusercontent.com/53154523/216851975-6e802d0a-c9ae-42b9-a263-845c07a2a67f.png)
![image](https://user-images.githubusercontent.com/53154523/216851989-0f06b15b-94ef-46ca-9c7e-5f6cf462c03b.png)
![image](https://user-images.githubusercontent.com/53154523/216852000-d97e06c2-3d75-4709-b2ea-0ebc4dad6cc4.png)
![image](https://user-images.githubusercontent.com/53154523/216852016-e708531a-4433-49c8-974c-ee142cf68a27.png)

**Comment by asadath1395** [comment]
@odicho I think this is no longer an issue, right now it only shows till `16:00`
![image](https://github.com/calcom/cal.com/assets/37188392/228d4728-16d1-4bf1-b754-d8d3ed7914ec)

cc @PeerRich
