### ISSUE TITLE
[CAL-997] epilepsy warning: aggressive flashing on success page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6902]
Video attached. Just a warning that it’s pretty aggressive flashing.

[https://user-images.githubusercontent.com/8019099/217012778-fde56938-53ad-4f1c-b089-b61ed77247c5.mov](https://user-images.githubusercontent.com/8019099/217012778-fde56938-53ad-4f1c-b089-b61ed77247c5.mov)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-997](https://linear.app/calcom/issue/CAL-997/epilepsy-warning-aggressive-flashing-on-success-page)</sub>

**Comment by PeerRich** [comment]
reuploaded.



something is odd with the theme provider

**Comment by solace** [comment]
Howdy, that video was submitted to @PeerRich by me.

Additional info, this was reported on Chrome (Version 110.0.5481.77 (Official Build) (x86_64)). I have multiple Chrome profiles and a separate cal.com account for different purposes.

The first instance, which is what that video was for, the flashing occurred with the same link on multiple Chrome profiles, and on reload until I cancelled the booking.

This most recent instance was using a different cal.com account and I had clicked confirm booking from email. Loading the same link in a different profile loaded fine, and when I reloaded the flashing tab, it started working again. I will DM Peer the relevant (though now working) link in Slack.

For reference, in the console of the flashing tag, I see the following in the console, but I also see the same console messages in the tabs that don't flash as well.
 
![Screen Shot 2023-02-12 at 16 55 47 pm](https://user-images.githubusercontent.com/374583/218301825-9c4b3ceb-bcc4-49cf-87b2-ca2185391008.png)

Given this is intermittent, I know it's super annoying to diagnose, but let me know if there is anything you'd like me to do in the event it happens again.

**Comment by PeerRich** [comment]
@sean-brydon you said you may know what this causes?

**Comment by PeerRich** [comment]
has this been resolved?

**Comment by sean-brydon** [comment]
I believe a fix got merged for it just before [https://github.com/calcom/cal.com/pull/7112](https://github.com/calcom/cal.com/pull/7112)
