### ISSUE TITLE
[CAL-1000] Bookings Filter Text not Updating

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#6910]
When update the filter view you want from the bookings filter, from "all bookings" to "your bookings" it DOES update the bookings to YOUR BOOKINGS, but the text does not say "YOUR BOOKINGS" 

![CleanShot 2023-02-06 at 16.10.19@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d3aa9190-6f64-4398-be9e-9bb427947c26/8514c696-959a-4b19-8f3f-4687b494b007)

![CleanShot 2023-02-06 at 16.10.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/165a9bbd-c405-49cf-be31-a65d42c97f81/b0a3a9c8-2908-45d1-8e54-cedb89743a6a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1000](https://linear.app/calcom/issue/CAL-1000/bookings-filter-text-not-updating)</sub>

**Comment by joeshajan** [comment]
Hey, @shirazdole I would like to work on this. Can you assign this to me?
