### ISSUE TITLE
Support for cal.com/{user}/emoji

### ISSUE THREAD

**Issue by jbronssin** [calcom/cal.com#6916]
### Is your proposal related to a problem?

Hey!
I would like to use emojis for some of my booking links. Unfortunately, they get converted by "https://cal.com/{user}/--" on save.

**Comment by PeerRich** [comment]
i am not sure if all browser support emojis

**Comment by jbronssin** [comment]
> i am not sure if all browser support emojis

Hey Peer! 
In fact, all modern browsers are compatible with emoji domains, what they do is convert it on the fly. But the link is nice to share.
ex:
- [I😀.WS](https://xn--i-jv3s.ws/)

[Ref Wikipedia](https://en.wikipedia.org/wiki/Emoji_domain#:~:text=An%20emoji%20domain%20is%20a,instead%20of%20the%20intended%20characters.)

**Comment by PeerRich** [comment]
i dont think its particulary nice to share because it would render `xn--i-jv3s`

**Comment by jbronssin** [comment]
It would indeed render as a weird looking text but... it's cool to share at first 😅 
Ok, ok, we can close this issue =)
