### ISSUE TITLE
In the App page in an Event - the Google Analytics toggle generates an error even if deactivated

### ISSUE THREAD

**Issue by jbronssin** [calcom/cal.com#6917]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

https://app.cal.com/event-types/{event-id}?tabName=apps
If you just toggle on and off the Google Analytics app (leaving it empty) even if it's empty, you get the error that the tracking ID is not set. It prevents you from saving.

### Steps to Reproduce

![Screen Recording 2023-02-07 at 10 09 04 AM](https://user-images.githubusercontent.com/65334819/217201974-8b3e6821-00cf-435a-b88a-d150a17e65b4.gif)

**Comment by PeerRich** [comment]
i cant reproduce this. can you remove and reinstall the app?

https://user-images.githubusercontent.com/8019099/217535011-8efdb236-1dc4-48b1-aea9-ddc2a1be715d.mp4

**Comment by jbronssin** [comment]
I just did it again: 
1. GA is installed
2. I go to an event type
3. Apps Tab
4. I toggle GA but don't put anything in the field
5. Toggle off GA
6. try to save -> get the error.
