### ISSUE TITLE
[CAL-1002] Profile page has a weird hover

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6919]
![CleanShot 2023-02-07 at 10.11.10.gif](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ff2bc3d4-bca6-4ab2-8d78-aafd892ec10d/ffe88a3e-5f68-44ad-a31b-b4f6305337d5)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1002](https://linear.app/calcom/issue/CAL-1002/profile-page-has-a-weird-hover)</sub>

**Comment by joeshajan** [comment]
Hey, @sean-brydon I would like to fix this. Can you assign this to me? And what is the expected behaviour?

**Comment by PeerRich** [comment]
@Jaibles what is expected here?

**Comment by Jaibles** [comment]
@PeerRich what about this:
<img width="1474" alt="CleanShot 2023-02-07 at 20 32 59@2x" src="https://user-images.githubusercontent.com/4536123/217358684-4093c33d-a53b-4eca-9113-854ba5ca9553.png">
https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=2758%3A128580&t=KT05dKeJIKgPrVh6-1

**Comment by joeshajan** [comment]
> @PeerRich what about this: <img alt="CleanShot 2023-02-07 at 20 32 59@2x" width="1474" src="https://user-images.githubusercontent.com/4536123/217358684-4093c33d-a53b-4eca-9113-854ba5ca9553.png"> https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=2758%3A128580&t=KT05dKeJIKgPrVh6-1

This looks nice. When this is finalized can you assign this to me? I would like to work on this.

**Comment by PeerRich** [comment]
a lot better, go for it @joeshajan

**Comment by joeshajan** [comment]
Hey, @PeerRich I fix this issue. Can you please check if this solves our problem?
