### ISSUE TITLE
Bio's not displaying on Team page.

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6925]
### Issue Summary

When on the team page, the users Bio's no longer show

### Steps to Reproduce

Go to a team page, see that the people don't have bio's

I think it may only apply on Safari, not sure - it's weird on mobile

### Technical details

- Brave (Mobile), Safari (Mac and Mobile)
- Node 16

<img width="819" alt="image" src="https://user-images.githubusercontent.com/53020786/217335506-7ef126a8-3e83-45c2-83a4-7293e8698c63.png">
![4ABB34FC-5629-4E67-8B65-464F0E62F769_1_201_a](https://user-images.githubusercontent.com/53020786/217335664-4c7b3aec-eec7-4958-b997-c73d49cbad99.jpeg)

**Comment by PeerRich** [comment]
will do a redesign of this page instead https://github.com/calcom/cal.com/issues/6938
