### ISSUE TITLE
Zoom being being set to UTC (wrong time), after confirming a meeting.

### ISSUE THREAD

**Issue by lyk2020** [calcom/cal.com#6928]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Availability is set to require confirmation when booking within 90 min. Using the Zoom App for conferencing.
Without confirmation, the zoom meeting time is correct in EST. When it needs to be confirmed, the zoom meeting get's set to the UTC time, even though I'm in EST.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
may be linked to https://github.com/calcom/cal.com/issues/6927

![image](https://user-images.githubusercontent.com/59542102/217370981-294efe92-3d1e-4979-9a92-1136e7a974f3.png)

**Comment by PeerRich** [comment]
same here, @joeauyeung can you investigate?

**Comment by lottamus** [comment]
@joeauyeung @zomars are you sure this is fixed? I'm still seeing this issue as of today:

I scheduled a test meeting for 3/17 at 1:30pm CST, but the Zoom meeting was scheduled for 3/15 at 5:38 pm CST. Happy to share any additional details that could be helpful.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/7423098/225465771-5a9f9d54-903b-4f20-b104-36138fdc699d.png">

<img width="644" alt="image" src="https://user-images.githubusercontent.com/7423098/225465804-8e1e9329-6f00-471e-bb4f-29bbcfe02815.png">
