### ISSUE TITLE
Calendso not respecting "Buffer Value"

### ISSUE THREAD

**Issue by SBagaria2710** [calcom/cal.com#693]
### Issue Summary
I've tried setting the Buffer value as 10mins/1hours, but it doesn't seem to respect it in both cases.

<img width="608" alt="Screenshot 2021-09-18 at 10 29 53 PM" src="https://user-images.githubusercontent.com/33802361/133906825-4d323486-f1c9-4485-9f1f-d4361a689373.png">

Here: Set buffer value to **1 hour** , StartTime to 3PM and EndTime to 6PM
Ideally, I should be getting **3:00PM** and **5:00PM** as options.

Here is what I got instead 👇🏼 

<img width="1276" alt="Screenshot 2021-09-18 at 10 30 07 PM" src="https://user-images.githubusercontent.com/33802361/133906828-d3ffb84e-26a9-42fc-9aa5-dfa0927ee0df.png">

### Steps to Reproduce
1. Went to availability section from the sidebar and set buffer value by clicking at `
2. Set `buffer value` by clicking at `change available time`
3. Click on the public link, people would be using to schedule an invite.

Buffer value wasn't taken into account.

### Technical details
* Browser version: Chrome 93
* Node.js version: v14.17.6

**Comment by PeerRich** [comment]
@emrysal

**Comment by ChipWolf** [comment]
I'm not seeing an option for the buffer at all @PeerRich @emrysal

**Comment by rjherrera** [comment]
I can't find that option either 🤔

**Comment by PeerRich** [comment]
i believe @emrysal is bringing it back as "bufferBefore" and "bufferAfter" events

**Comment by KrisKodira** [comment]
> yes, actively being worked on by @emrysal. should go live soon!

When is soon?

**Comment by PeerRich** [comment]
> > yes, actively being worked on by @emrysal. should go live soon!
> 
> When is soon?

days, if it wasn't holidays haha

**Comment by ChipWolf** [comment]
> > > yes, actively being worked on by @emrysal. should go live soon!
> > 
> > 
> > When is soon?
> 
> days, if it wasn't holidays haha

Total respect for the holiday season, but come January could we possibly see some use of GitHub's milestones and project tracking so we have a rough idea of where the focus is?

**Comment by PeerRich** [comment]
> Total respect for the holiday season, but come January could we possibly see some use of GitHub's milestones and project tracking so we have a rough idea of where the focus is?

@emrysal is already working on buffer. it'll be ready when its ready

just yesterday we made our entire list of internal tickets public: cal.com/open

we, similar as other open source projects, dont use github issues and milestones as our "ground truth" roadmap for several reasons

**Comment by zeorin** [comment]
The current version has it implemented as separate before and after buffers, but they are not being respected. Really annoying as I specifically set those so that I'd have time to prepare for the events, which in several cases I have now _not_ had because it's not being respected.

**Comment by Jaibles** [comment]
Thanks for reporting 🙏 This should be resolved now
