### ISSUE TITLE
[CAL-1004] Improve App list design in initial Setup

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6931]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b522dd59-e4ed-4a99-8990-82a3b32d964e/c3085d49-2da0-41f6-967b-c17e9c2202de)

Due to size constraints, we cannot should the proper toggle to enable/disable. Also it is not clear that you must/need setup some keys for certain apps.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1004](https://linear.app/calcom/issue/CAL-1004/improve-app-list-design-in-initial-setup)</sub>

**Comment by PeerRich** [comment]
can we not just make the entire container bigger?

**Comment by leog** [comment]
@PeerRich @zomars no matter how much space I give it, the toggle doesn't show up. Even in Settings it's not showing. Perhaps there is no toggle anymore? 🤔

<kbd><img width="1501" alt="image" src="https://user-images.githubusercontent.com/467258/217621018-a1ebebb8-b1c7-450f-874f-c16b21df5048.png"></kbd>

**Comment by zomars** [comment]
@joeauyeung may have more info on thi

**Comment by PeerRich** [comment]
can we look into this? some people have been reaching out its quite unusable in this state

**Comment by hariombalhara** [comment]
Seems to be working for me. Maybe it got fixed sometime back
https://www.loom.com/share/cc36202a33974debb29c718b0f0708ce
