### ISSUE TITLE
Booking not working properly from a different timezone

### ISSUE THREAD

**Issue by lyk2020** [calcom/cal.com#6932]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I'm in EST have availability set, also using the feature to block out some time.
When trying to schedule using EST (GMT -5), the availability shows up fine. 
When switching to another Time Zone (Tried GMT +2) it shows more availability then there is, then errors when trying to book.
The error is "Could not book the meeting. No available users found."

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Using Edge (chromium)
- may be related to https://github.com/calcom/cal.com/issues/6928 or https://github.com/calcom/cal.com/issues/6927

EST
![2023-02-07_23h14_30](https://user-images.githubusercontent.com/59542102/217431981-2e4e5e28-61d8-4cc4-a6a3-572da32d5cdd.png)
GMT +2
![2023-02-07_23h01_31](https://user-images.githubusercontent.com/59542102/217432109-543ac98c-a6dc-439c-bbac-3f6c5335ed07.png)
Error
![image](https://user-images.githubusercontent.com/59542102/217432223-e0635511-aed8-43e0-832c-dc0bfca6111c.png)

**Comment by milospuac** [comment]
@lyk2020 hi there. This bug is being investigated. Thank you for your patience.

**Comment by PeerRich** [comment]
@zomars i think having efrain look into these in the future would make sense, too

**Comment by chadamski** [comment]
I am also encountering the same error message with clients attempting to book, but I'm using Google Meet for video conferencing. Any chance the timezone mismatch issue is universal?

**Comment by PeerRich** [comment]
i think this has been fixed. can you confirm?
