### ISSUE TITLE
[CAL-1005] Overwrite booking page language (currently browser language)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6933]
For context: right now we use the browser language to set the language for guests when booking

Reported by a user:

**Feature request:**

It would be awesome to be able to select the language for each event page/form individually. My business targets different groups of customers in different languages, so having language per event type would be very helpful. Also, I prefer English for the app UI, so making sure to separate the public even form language from the admin UI language would also be really nice.

**More context:**

Are there any plans to make that overrideable?

In my case for example, I provide an event type description and also add custom form fields to collect other information needed for the appointment. Since that is custom input, it always displays in the language that I typed it in, so it makes the forms look inconsistent when parts of the UI are automatically translated and the custom portion is not. I think it would be a better end user experience and a more professional look for the businesses using your software if we could choose a the language to present them in.

<sub>[CAL-1005](https://linear.app/calcom/issue/CAL-1005/overwrite-browser-language-of-visitor-per-event-type)</sub>

**Comment by PeerRich** [comment]
maybe we can use the new i18n urls such as cal.com/de/30min?

**Comment by michelezaccaria** [comment]
> maybe we can use the new i18n urls such as https://cal.com/de/peer/30min?

This could be a good solution. I am looking forward to this new feature because now you cannot customise the questions in the form well because you do not have complete control over the language. In fact, if you configure the questions in English and then the booking page is automatically rendered in German, you get a poor result with the mix of the two languages.
