### ISSUE TITLE
Bio's not displaying on Safari

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6934]
Very peculiar bug here with seemingly Safari only, but if a users Bio is too long for the box in the team's card, then the text disappears. 
For example:
"Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test " will break the box, but "Test Test Test" wont.

I don't see this issue in chrome, or brave on my laptop, just safari - but safari on both mac and ios, as well as brave on ios.

### Issue Summary

Here's a selection of screen sizes and where it breaks:
No data
![image](https://user-images.githubusercontent.com/53020786/217504451-d28397d9-8034-4e49-a64c-cde22ba058fb.png)
No data
![image](https://user-images.githubusercontent.com/53020786/217504523-2f6bf6f1-b640-482c-b8bd-b043267f9159.png)
Data shows for user 2, where the bio is short enough to fit in
![image](https://user-images.githubusercontent.com/53020786/217504614-f630bd59-0248-41e8-af9a-234074e91bbd.png)

Brave mobile demo if it not working:
![4ABB34FC-5629-4E67-8B65-464F0E62F769_1_105_c](https://user-images.githubusercontent.com/53020786/217505017-d6751daa-633f-454f-a895-a5c17115287b.jpeg)

### Steps to Reproduce

Set users with a range of lengths of Bio's - then put them in a team.
Navigate to the team's public page and view it on a range of devices, browsers.
Like I say, this is mainly iOS/Mac Safari, but does show on other mobile browsers too.

You can see a live example on https://dev.cnnct.uk/team/test-team

### Technical details

- Browser version kinda ranged here, but safari ios, mac os, brave ios are noticeable issues.
- Node 16
- Latest commit of Cal.com (as of #6574)

**Comment by milospuac** [comment]
@Hybes Hi Ben. This is being investigated. I appreciate your patience.

**Comment by Hybes** [comment]
@milospuac cheers, if you need anymore info - feel free to reach out to me on Slack

**Comment by PeerRich** [comment]
i believe we will instead redesign this page @Jaibles vs fixing this edge case. the redeisgn should be cross-browser safe

**Comment by PeerRich** [comment]
closing and opening a new ticket for redesign

**Comment by Jaibles** [comment]
Yea, I think there's a high likelihood that we show more custom attributes on this page and less of the description, possibly even only showing the description on the individual page. Will redesign.
