### ISSUE TITLE
[CAL-1008] Booking filters weird edge case

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#6937]
When selecting your bookings you for some reason cant click all bookings

![CleanShot 2023-02-08 at 12.35.14.gif](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/11d0510c-5a36-44d7-9238-3a607e71df47/67e08bfb-da10-419e-ae7f-9f894fbb5b63)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1008](https://linear.app/calcom/issue/CAL-1008/booking-filters-weird-edge-case)</sub>

**Comment by PeerRich** [comment]
would your new dropdown not fix this?

**Comment by sean-brydon** [comment]
> would your new dropdown not fix this?

Might require some hacking - this isnt a select so to speak as the "All Bookings"/"your bookings" requires some additional logic
