### ISSUE TITLE
[CAL-1009] redesign team member page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6938]
fixes https://github.com/calcom/cal.com/issues/6934

this page https://cal.com/team/cal?members=1 deserves a redesign

<sub>[CAL-1009](https://linear.app/calcom/issue/CAL-1009/redesign-team-member-page)</sub>

**Comment by Hybes** [comment]
ok ty, do we have a timescale on this, i've had the users rewrite the descriptions for now.

**Comment by PeerRich** [comment]
yep, soon

**Comment by angel8au** [comment]
Hi, I would like to contribute to the redesign of this page, but first I would like to have more context. What is the current problem with the team page? Why is it being redesigned? Do you have any goals for this page? How and when is this page used? Or any information that could help me better understand the context?
