### ISSUE TITLE
[CAL-1011] App: File Upload (Starting with Amazon S3)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6939]
starting with S3, organisers can ask guests for a file upload (i.e. a CV or similar)

for security reasons, organisers need to provide their own S3 bucket since [Cal.com](http://Cal.com) does not want to host your files

this app would be of type "EventTypeApp"

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9c3da452-e393-4e1e-9497-c14cb86718d1/561dbae9-1f73-4575-a7f0-c806049b8de3)

in event-types:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c1bfb263-2440-4634-ab4b-50d9c535fb5e/82fbe0b8-4fcd-4431-a5dd-b3fe601502b7)

booking page:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4f07c951-d75c-4a58-87bb-d72ec2f44342/7cd9fbe6-302e-404f-bbb5-a629285076b7)

questions:

should this be always optional? or always required? or ability to decide?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1011](https://linear.app/calcom/issue/CAL-1011/app-file-upload-starting-with-amazon-s3)</sub>

**Comment by PeerRich** [comment]
alternatively we have one app per service which is probably cleaner (also gives us better insights). 

it can have identical implementation too, just duplicated app meta data

**Comment by PeerRich** [comment]
one app for Dropbox, one app for Google Drive, etc.

**Comment by Jaibles** [comment]
Looks great! 

Some suggested subtle UI adjustments. Main things are
- Check spacing above & below drag and drop area
- Font-weight inside it
- Suggested circle around icon so we can give it more visual weight without having to go so big & bold.
- Should we add a label to the area so it's consistent with the other inputs? I think it help makes it look more standalone and less apart of the question above it.

<img width="1496" alt="CleanShot 2023-02-08 at 14 04 57@2x" src="https://user-images.githubusercontent.com/4536123/217552166-10cbb73c-c404-43c7-a46d-3c6e5e787359.png">


https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=2787%3A129690&t=QRzD1Dx5TsLxWmvP-1

**Comment by PeerRich** [comment]
cheers!

**Comment by zomars** [comment]
Should we impose limits? I can see a bot filling up our users buckets with trash data.

**Comment by PeerRich** [comment]
rate limits, yea. we need to be very careful when we roll this out (if at all. its still in idea stage)

**Comment by Mythie** [comment]
The best win here would be to initially have an S3 compatible support so you'll get things like Backblaze, R2, and so on. Likewise we can have a configurable file limit for the user alongside the in-memory rate limits that we already enforce elsewhere within the application.

**Comment by PeerRich** [comment]
if anyone wants to pick this up, here's how to make an app: https://docs.cal.com/how-to-guides/how-to-build-an-app

**Comment by miguelnietoa** [comment]
Hi everyone!

This would certainly be a very useful app!

I've been looking around to pick this up. IMO this should work along with the recent feature of **Booking questions**... Do you think this is a good approach? CC @hariombalhara (I noticed that you implemented this 😅)

**Comment by PeerRich** [comment]
i think it would be nice to add this into booking questions UI but keep it standalone as an app

**Comment by hariombalhara** [comment]
@miguelnietoa Yeah it fits well into the Booking Questions feature. I would recommend the way we manage smsReminderNumber field/question which is added by workflows in Booking Questions

**Comment by miguelnietoa** [comment]
@hariombalhara I think you mean to use the `upsertBookingField` function as you did with the smsReminderNumber field, right?

Or do you recommend that the app works like webhooks? Because it doesn't really make sense to me via webhooks...

**Comment by hariombalhara** [comment]
Yeah I meant upserBookingField only

**Comment by miguelnietoa** [comment]
Got it, totally agree with both of you! Excited to work on this @PeerRich 🚀

**Comment by miguelnietoa** [comment]
Hey @andresobral, are you currently tackling this issue?

**Comment by andresobral** [comment]
Hi @miguelnietoa ! Yes, I am on it. I will submit a PR soon. Just to confirm, this should not be a app anymore and it will happen in the booking questions feature, correct?

**Comment by miguelnietoa** [comment]
> i think it would be nice to add this into booking questions UI but keep it standalone as an app

@andresobral No, It should be standalone as an app

**Comment by joe-shajan** [comment]
Hey, @andresobral and @miguelnietoa are you guys still working on this? If not can I take a look into this?

**Comment by miguelnietoa** [comment]
Hey @joe-shajan  I just came back to work on this haha, since @andresobral didn't create the PR. Anyway, in these days I'll submit it! 😅

**Comment by Hitesh-sisara** [comment]
can i attempt this ?

**Comment by matijamandic-sc** [comment]
What is the status of this?

**Comment by mitibirru** [comment]
Hey @PeerRich I noticed a pull request.
Is this feature still unresolved?

**Comment by PeerRich** [comment]
weve decided to not do this right now
