### ISSUE TITLE
[Urgent] cal.com not loading through an iframe

### ISSUE THREAD

**Issue by gzim-joinfella** [calcom/cal.com#6946]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
<img width="829" alt="Screenshot 2023-02-08 at 16 05 07" src="https://user-images.githubusercontent.com/100677978/217568209-e1e82a70-75b8-42da-afd9-54439a5ad188.png">

cal.com not loading through an iframe. This is blocking our customers to schedule appointments through cal.com. 

### Steps to Reproduce

1. Load a cal.com event link through an iframe
2. Refused to display error will show up

**Comment by gzim-joinfella** [comment]
Code line: https://github.com/calcom/cal.com/blob/cfc3644d512b40d94b4a239cb0f2213d56ac7b7c/apps/web/next.config.js#L193

**Comment by gzim-joinfella** [comment]
Change was merged yesterday: https://github.com/calcom/cal.com/commit/c42674595c2de5d79cb76fb955a98aaae8b1969b

**Comment by emrysal** [comment]
Hi @gzim-joinfella You can use the /embed endpoint which is whitelisted from this DENY - see also the embed instructions on the event-types pages.

**Comment by gzim-joinfella** [comment]
@emrysal our links look like: https://cal.com/team/<our-team>/<our-event-type>


can you give me an example how this link would look like when using the `/embed` endpoint please?

**Comment by gzim-joinfella** [comment]
is it possible to revert that change temporary until the customers have moved to the new way on setting up cal.com as an embed? I imagine there are other customers facing the exact issue as we speak. 

@PeerRich tagging you for visibility, thanks!

**Comment by PeerRich** [comment]
@emrysal can we just whitelable /team and /username pages?

**Comment by PeerRich** [comment]
we can allow /team but we cant allow /username for now because there is no difference between /event-type which needs deny and /peer which needs allow from a schema point of view

**Comment by gzim-joinfella** [comment]
@PeerRich /team is all we need right now to get unblocked. thanks!

**Comment by PeerRich** [comment]
will be fixed today!

**Comment by PeerRich** [comment]
PR is up, new release goes out within this hour

**Comment by gzim-joinfella** [comment]
@emrysal @PeerRich Not sure if the deployment has gone through, but the issue is still there (since you marked the issue as closed). thanks!
