### ISSUE TITLE
[CAL-1013] teams empty screen gone

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6947]
![CleanShot 2023-02-08 at 16.55.32@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b74d22b3-b8d6-4850-8f64-863a937ada5a/201ed1b8-19d2-41ca-a4f6-492572a60511)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1013](https://linear.app/calcom/issue/CAL-1013/teams-empty-screen-gone)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar @G3root

**Comment by G3root** [comment]
Can you share the steps to reproduce this ?

**Comment by PeerRich** [comment]
i think its fixed 🤔
