### ISSUE TITLE
[CAL-1014] Pending payment badge with stripe disabled

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#6948]
### Issue Summary

My bookings show 'Pending payment':
![Screenshot 2023-02-08 at 10 51 31](https://user-images.githubusercontent.com/30310907/217580957-286ad0dc-d01f-4f35-a978-bdd1b6e1d388.png)

I had stripe enabled, but now it is disabled: 
![Screenshot 2023-02-08 at 10 51 22](https://user-images.githubusercontent.com/30310907/217581077-a0819674-f28a-4845-b951-286a696acbec.png)

### Steps to Reproduce

1. Install stripe app 
2. Enable stripe app on an event-type
3. Disable stripe app 
4. Book event 
5. Go to /bookings and see that booking has 'pending payment' badge

<sub>[CAL-1014](https://linear.app/calcom/issue/CAL-1014/pending-payment-badge-with-stripe-disabled)</sub>

**Comment by zomars** [comment]
What should happen here? it is not wrong. Even with stripe disabled the booking was a paid one at the time of creation. Maybe cancel them? or ask the user?

**Comment by CarinaWolli** [comment]
@zomars Already at the time of booking, stripe is disabled. The attendee never gets asked for payment but it shows up as ‘pending payment’ for the organizer. Sorry, I maybe didn’t make that clear.

**Comment by zomars** [comment]
I see, we should maybe disable paid event types or remove the paymentData from those

**Comment by hariombalhara** [comment]
It's working fine for me. I think it got fixed with [https://github.com/calcom/cal.com/pull/9181](https://github.com/calcom/cal.com/pull/9181)

[https://www.loom.com/share/519e69fb3ded44d28483f9abf436b68e](https://www.loom.com/share/519e69fb3ded44d28483f9abf436b68e)
