### ISSUE TITLE
Unique constraint error thrown when booking a slot

### ISSUE THREAD

**Issue by virajsoni06** [calcom/cal.com#695]
Hi, this is a pretty amazing project.

Found the below error is thrown when a cancelled slot is booked.

![image](https://user-images.githubusercontent.com/13236286/133919947-e09ab530-f6c5-44d6-a34a-6cae0c4bbe40.png)

To reproduce the issue
1. Create a booking slot
2. Cancel that booking slot
3. Attempt to re-book the slot. 

The success window is shown but the logs throw a unique constraint error

PS: The error goes away if the database entry is deleted.

**Comment by ConnorGargano** [comment]
Hi @virajsoni06,
Allow me to send this over to the engineering team to have a look into this for you and see what can be resolved.
-Thanks Connor

**Comment by PeerRich** [comment]
i think this was fixed a log time ago
