### ISSUE TITLE
[CAL-1016] i think its a good idea to invalidate password once someone clicks "Sign in with Google"

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6953]
i think its a good idea to invalidate password once someone clicks "Sign in with Google"

_Originally posted by @PeerRich in https://github.com/calcom/cal.com/issues/6874#issuecomment-1422428377_
            

<sub>[CAL-1016](https://linear.app/calcom/issue/CAL-1016/i-think-its-a-good-idea-to-invalidate-password-once-someone-clicks)</sub>

**Comment by PeerRich** [comment]
we are reworking the entire auth right now
