### ISSUE TITLE
App: Apple FaceTime

### ISSUE THREAD

**Issue by alexandertsukanov** [calcom/cal.com#6965]
I am writing to express my interest in having FaceTime integration added to Caldav app. As a user of your app, I believe that this feature would greatly enhance the app’s functionality and overall user experience.

I want to be able to use FaceTime as an option as a user. So, my clients will have an option to choose “FaceTime” location at cal.com in my schedule.

Regards, Oleksandr T.

**Comment by PeerRich** [comment]
hey, its not quite easy, Apple does not provide an API to generate a FaceTime URL. We could make it in a way where you can copy paste in your FaceTime Link but i believe the link changes over time

**Comment by PeerRich** [comment]
we could also ask for a phone number and then generate a deeplink like this: [facetime://0123456789](facetime://0123456789)

**Comment by Mythie** [comment]
> hey, its not quite easy, Apple does not provide an API to generate a FaceTime URL. We could make it in a way where you can copy paste in your FaceTime Link but i believe the link changes over time

So there are two types of FaceTime links we can support, the first being the new FaceTime link that allows both Android and PC users to join your call which will use a web client. These links are generated in app and are permanent until you delete them in app. Secondly, and for users on operating systems prior to iOS 15 and MacOS Montery there is the native app link scheme of `facetime:<address>`.

We can support both of these within a single app by validating that the address either belongs to the `facetime.apple.com` domain or uses the `facetime:` url scheme. 

I'd be happy to do the work on this 😄

**Comment by PeerRich** [comment]
oh yeah that makes sense. please go ahead! you can see how we do the whereby app with validating the schema and just do both regex'es

**Comment by PeerRich** [comment]
assigned you @Mythie
