### ISSUE TITLE
[CAL-1023] availability mobile: margin bottom missing

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6966]
![F253A415-8608-422F-9A54-6CC0E8D3E8C3.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8dc8ec79-0d07-4e76-af53-4eb12804480e/f2289c16-9d4e-44b5-bbf6-d9dd9128c0c2)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1023](https://linear.app/calcom/issue/CAL-1023/availability-mobile-margin-bottom-missing)</sub>

**Comment by joeshajan** [comment]
I would like to fix it. Can you assign this to me @PeerRich?

**Comment by PeerRich** [comment]
assigned @joeshajan
