### ISSUE TITLE
[CAL-1025] Bookings can't be rejected

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#6969]
Try to make a booking that requires confirmation and reject it from the bookings tab

![Screenshot 2023-02-09 at 13.42.05.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f731966f-6f50-4407-a62f-fe04cfce1380/20c2d24b-eed7-4f7b-9f10-b6e4c76c09dd)

Created via Threads. See full discussion: [https://threads.com/34447694005](https://threads.com/34447694005)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1025](https://linear.app/calcom/issue/CAL-1025/bookings-cant-be-rejected)</sub>

**Comment by zomars** [comment]
* Unpaid bookings cannot be rejected, you should be able to reject an unpaid booking AND disable the payment link
* There's a bug that trying to reject an unpaid booking from email link actually confirms it
