### ISSUE TITLE
Adding advanced option "file uploads"

### ISSUE THREAD

**Issue by FUF1** [calcom/cal.com#6970]
### Is your proposal related to a problem?

No, it is a feature request to make the product even more awesome.

### Describe the solution you'd like

Having the advanced option to not only ask bookers for notes etc. but also for multiple file uploads for preparing documents would be very helpful.

### Describe alternatives you've considered

Currently I just ask them to send it to me by mail. But would be nice to have it all integrated and maybe as a link/mail attachement or as a page on the cal.com app.

### Additional context

No additional context yet.

**Comment by PeerRich** [comment]
duplicate #6939

**Comment by jayonsoftware** [comment]
Can we support file upload as a field ?
