### ISSUE TITLE
Availability Date overrides appear to have time zone issue

### ISSUE THREAD

**Issue by peterkagey** [calcom/cal.com#6978]
### Issue Summary

I have Working Hours on Monday 5–6PM and Thursday 4–6PM in the America/Los_Angeles time zone. When I attempt to add an override, it only allows me to select Tuesdays and Fridays.

### Steps to Reproduce

1. In the availability tab, set working hours to Monday 5–6PM and Thursday 4–6PM in the America/Los_Angeles time zone.
2. Click on `+ Add an override`.
3. Wrong days of the week on the calendar show up.

### Technical details

- MacOS 13.0.1 & Firefox 109.0.1.

**Comment by mbode** [comment]
Unfortunately this is a bit of a pain, especially when using many slots per day (because all of them need to be adjusted manually). Do you have a rough plan when this will be investigated?
