### ISSUE TITLE
[CAL-1027] Buttons on /bookings have scrollbars

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6983]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/570f3153-3e61-4fc0-ac3f-0bc4241ed4b1/ef7d89a4-49e9-4586-b1fe-5fff76d5144f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1027](https://linear.app/calcom/issue/CAL-1027/buttons-on-bookings-have-scrollbars)</sub>

**Comment by harshmange44** [comment]
Hey, I'd like to fix this

**Comment by zomars** [comment]
Sure @harshmange44 🙏🏽

**Comment by PeerRich** [comment]
@harshmange44 assigned you. also the down icon is now vertically centered

**Comment by draqist** [comment]
has the issue been resolved? if it hasn't I'd like to fix it

**Comment by PeerRich** [comment]
yep, fixed
