### ISSUE TITLE
The about field in profile section gets focused automatically

### ISSUE THREAD

**Issue by ArindamBiswas-dev** [calcom/cal.com#6990]
### Issue Summary

The about field in profile section gets focused automatically when visiting.
![image](https://user-images.githubusercontent.com/69881224/217947020-708cd124-af31-41d7-b95c-e04b75851acf.png)

### Steps to Reproduce

1. Go to Settings -> profile
2. check the about section

**Comment by PeerRich** [comment]
fair point, quick fix but low priority

**Comment by ArindamBiswas-dev** [comment]
can I work on this?

**Comment by PeerRich** [comment]
sure
