### ISSUE TITLE
[CAL-1030] mobile dropdown menu layout issues

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6992]
found another issue on mobile

- [ ] flickering border
- [ ] double border for delete button

https://user-images.githubusercontent.com/8019099/217485440-22d1d56d-4c65-4475-ac3a-a8008bb5073a.mp4

_Originally posted by @PeerRich in https://github.com/calcom/cal.com/pull/6854#pullrequestreview-1288750773_
            

<sub>[CAL-1030](https://linear.app/calcom/issue/CAL-1030/mobile-dropdown-menu-layout-issues)</sub>

**Comment by amirfakhrullah** [comment]
I'd like to fix this

**Comment by PeerRich** [comment]
go for it @amirfakhrullah

**Comment by amirfakhrullah** [comment]
This PR is ready to be reviewed: https://github.com/calcom/cal.com/pull/7036
