### ISSUE TITLE
[CAL-1036] brandColor not applied for buttons and hover

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7030]
the confirm button (or primary buttons in general) used to be based on the brand color

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9ae7189c-1885-4596-98e8-f3adcb8ecde6/9ae1a2cf-a014-4690-ace8-2728e8ebf8ee)

same with the hover of a date selection:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4f065fa1-0ebc-4470-93a0-d29c9683974f/e0d90b91-b51b-4804-b345-70a60fd560f5)

that used to be:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c349626a-aaf5-48f8-89e0-450e60487831/a7e84287-7bfd-4e29-ba67-c19014416f13)

and

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cf3afbaa-f6ac-47c7-a50d-399415ab74cf/1c6403b4-2c01-4aa5-a580-1498e63c2e07)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1036](https://linear.app/calcom/issue/CAL-1036/brandcolor-not-applied-for-buttons-and-hover)</sub>

**Comment by draqist** [comment]
Has this been fixed, would like to give it a try

**Comment by draqist** [comment]
Has this been fixed, would like to give it a try

**Comment by PeerRich** [comment]
been fixed!
