### ISSUE TITLE
[CAL-1038] avatar group buggy with +0

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7032]
![CleanShot 2023-02-10 at 12.12.39@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9ee5363a-83df-4573-b73b-a6fa892b5966/0cb81055-420c-424e-b65b-ccfa51704d0a)

see here: [https://cal.com/peer+bailey+ciaran+seanbrydon ](https://cal.com/peer+bailey+ciaran+seanbrydon)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1038](https://linear.app/calcom/issue/CAL-1038/avatar-group-buggy-with-0)</sub>

**Comment by amirfakhrullah** [comment]
I would like to fix this

**Comment by PeerRich** [comment]
assigned you @amirfakhrullah 

for questions, ask @sean-brydon

**Comment by amirfakhrullah** [comment]
I able to fix the `AvatarGroup`, can refer the image here:
![image](https://user-images.githubusercontent.com/73758525/218167715-aa633f24-7b8d-4ef7-a389-93c49ff62657.png)

Is this the right behaviour 👆 @sean-brydon @PeerRich ?

**Comment by PeerRich** [comment]
![CleanShot 2023-02-10 at 19 46 49@2x](https://user-images.githubusercontent.com/8019099/218173089-80895731-f4a8-46c9-80e6-525b31e339c0.jpg)

https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=1573%3A77912&t=m2tLxC6kyrKmON4Q-4

**Comment by amirfakhrullah** [comment]
PR for this fix is up for review: https://github.com/calcom/cal.com/pull/7044 @PeerRich @sean-brydon
