### ISSUE TITLE
[CAL-1039] Bulk apply default conferencing app to already created events

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7034]
As a user with many existing event types, I want to be able to bulk apply my default to those existing events.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1039](https://linear.app/calcom/issue/CAL-1039/bulk-apply-default-conferencing-app-to-already-created-events)</sub>

**Comment by PeerRich** [comment]
sorry we wont work on this. that user has to do it manually

**Comment by PeerRich** [comment]
is this really a common thing?

**Comment by Jaibles** [comment]
It's been asked. Will try find. In general changing default is asked a lot. Imo changing default for only new events is only half the feature. Priority is low.
