### ISSUE TITLE
[CAL-1040] routing-forms: ability to write a placeholder

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7035]
![CleanShot 2023-02-10 at 13.40.29@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/617e564c-0aca-4ece-87c4-17bd33b8383e/da0549c5-463c-4203-86f8-d6083938180b)

will show:

![CleanShot 2023-02-10 at 13.40.54@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3b3efa6c-b934-4cd8-9e7a-7fb3d3decd88/7a288b61-a0e0-44f3-b3f3-dfb227d75136)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1040](https://linear.app/calcom/issue/CAL-1040/routing-forms-ability-to-write-a-placeholder)</sub>

**Comment by darshandamre** [comment]
i would like to work on this

**Comment by PeerRich** [comment]
sure @darshandamre
