### ISSUE TITLE
[CAL-1042] Public booking with multiple location options

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7042]
* Move the location selection to the left panel
* Only ask for any info in the form.

![CleanShot 2023-02-10 at 15.57.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/13d310e4-d3e4-4804-9e83-2ba125138a8a/8d844b8d-cc70-41e8-bdb1-88ca87a58134)

[utility/container - Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=2847%3A131372&t=hgmRjSBoCrcIeCnR-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1042](https://linear.app/calcom/issue/CAL-1042/public-booking-with-multiple-location-options)</sub>

**Comment by amirfakhrullah** [comment]
Can I tackle this one?

**Comment by PeerRich** [comment]
sure @amirfakhrullah

**Comment by PeerRich** [comment]
or should we wait for @sean-brydon's new select component?

**Comment by sean-brydon** [comment]
@PeerRich  Maybe yeah - its just looking for a review now. Already to go

**Comment by amirfakhrullah** [comment]
Lemme know once the new select component merged so I can start working on this

**Comment by sean-brydon** [comment]
> Lemme know once the new select component merged so I can start working on this

For sure :) Hopefully soon!
