### ISSUE TITLE
[CAL-1247] Empty variables: {{eventType}} + {{name}}  in Email Subject 

### ISSUE THREAD

**Issue by prononext** [calcom/cal.com#7046]
I noticed when a event-type is on confirmation only mode, that the email to the attendee has empty variables in the header. 

`Booking created: {{eventType}} with {{name}} at... Email Subject has empty variables in the Header`

<sub>[CAL-1247](https://linear.app/calcom/issue/CAL-1247/empty-variables-eventtype-name-in-email-subject)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar

**Comment by paulette560** [comment]
Hi @Udit-takkar I have the same issue than @prononext 

Here is a screenshot.
Thanks !

![CleanShot 2023-03-14 at 12 05 40@2x](https://user-images.githubusercontent.com/127837000/224983398-bc27090b-1414-48f9-914e-0e85b497dcc3.png)
