### ISSUE TITLE
[CAL-1043] Phone custom field automatically update country by IP

### ISSUE THREAD

**Issue by cachil0** [calcom/cal.com#7049]
Is it possible to add an automatic IP recognition for phone custom field?

When this field is available, the person needs to choose the country and then type the number.

In mobile it may be not intuitive, getting the country by IP would be very good.

Eg: someone from Brazil's IP gets automatically Brazil selected with no need to choose the country.

<sub>[CAL-1043](https://linear.app/calcom/issue/CAL-1043/phone-custom-field-automatically-update-country-by-ip)</sub>

**Comment by PeerRich** [comment]
it is possible, we just havent done that yet. @AaronPresley would you be interested in this? we use react-phone-number-input

https://www.npmjs.com/package/react-phone-number-input

**Comment by Udit-takkar** [comment]
@PeerRich I am already working on this https://github.com/calcom/cal.com/pull/6880. It's almost complete.
