### ISSUE TITLE
Fulfill form information with URL parameters

### ISSUE THREAD

**Issue by cachil0** [calcom/cal.com#7050]
This feature would be to fulfill all the fields in a form using url parameters.

eg: I have a form that asks name, email and custom field for phone. Then I can create a url parameter that when opened automatically fulfills the form.

cal.com/test/name=test&email=test@test.com&phone=123456789

**Comment by PeerRich** [comment]
yep, this is coming cc @hariombalhara 

also for custom fields

**Comment by hariombalhara** [comment]
Yup. This is in review now. You can even hide the fields.

**Comment by cachil0** [comment]
@hariombalhara is it done?

**Comment by hariombalhara** [comment]
@cachil0 Yeah it's done. name and email were already possible to be prefilled but phone number wasn't supported.
Right now there 2 reasons a phone number can be asked for in a booking form
- Location(Where meeting would occur) -> Prefill it with `location={"value":"phone","optionValue":"%2B919999999999"}`
- Sms Reminder Number(To send reminder on that phone number) -> Prefill it with `smsReminderNumber=%2B919999999999`

Note: **%2B** represents **+**

<img width="1777" alt="Screenshot 2023-03-14 at 10 26 13 AM" src="https://user-images.githubusercontent.com/1780212/224897128-e82e1c48-6679-4f7c-8724-9ab787e51342.png">

**Comment by cachil0** [comment]
@hariombalhara good! and abot hiding fields? is it working?

**Comment by hariombalhara** [comment]
Yeah. You can hide certain default fields and all of user fields
