### ISSUE TITLE
RFC: Reduce the size of the profile and event type pages bundle to increase performance

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#7052]
![imagen](https://user-images.githubusercontent.com/525369/218233136-daf1081d-64bd-4732-84f8-a82ae97daf21.png)

The first load of each page should be close to 100 kb, and user pages are more than 400 kb.

![Captura de pantalla 2023-02-10 a la(s) 7 00 56 p m](https://user-images.githubusercontent.com/525369/218233667-16aac8ae-477a-4fbb-8a7f-6e297a2c9175.png)

**How does bundle size affect performance?**

Large amounts of JavaScript negatively affect site speed in two distinct phases:

- **During page load:** big bundles take longer to download.
- **During parse and compile:** big bundles take longer to be turned into machine code, which delays JS initialisation.

https://calibreapp.com/blog/bundle-size-optimization
---

As we know bundle size affect directly to cold start so we need to reduce bundle size of booking pages and API endpoints to.
After some changes we could reduce bundle size of booking pages.

- Dayjs Locales removed
- Crypto with md5 package from Avatar component

![imagen](https://user-images.githubusercontent.com/525369/227395417-3e55e5c6-0933-4337-995b-f4981d2624c7.png)

## /[user]/[type] Current bundle page

![imagen](https://user-images.githubusercontent.com/525369/227620231-7d215b45-09f8-4181-b435-6bda25c6bfda.png)

As we can see in the image above Prisma, i18n y Zod are main dependencies affecting bundle size.
- Can we remove zod from these pages?
- how can we improve i18n to decrease the bundle size?
- Why is Prisma in the client's bundle?

## Middleware Bundle

![imagen](https://user-images.githubusercontent.com/525369/227630224-26de5cb6-f1a0-410b-b323-9abf533a8697.png)

- can we remove zod depency from middleware?
- it seems that zod has tree shaking support

## /api/trpc/[trpc] bundle

![imagen](https://user-images.githubusercontent.com/525369/227631633-590fd262-c3b2-4883-b212-c9408e213961.png)

**This is a huge bundle!**  😱

- can we load routes dinamicaly?

The main TRCP endpoints that the booking pages need are slots.getSchedule, user.me, cityTimezones and i18n which represent the biggest bottleneck of the page.

All these endpoints are affected by slow cold starts, caused by the bundle size of the TRCP middleware.

## Experiment results [WIP]

- Experiment to measure cold starts Prisma vs. raw postgres queries
- Experiment to measure cold starts without TRPC

**Comment by PeerRich** [comment]
is this still open?
