### ISSUE TITLE
[CAL-1047] Dynamically load Toast on booking Page - They don't have it yet

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7062]
Can we dynamic load them? I don't want to increase booking pages bundle size any more.

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/6560#discussion_r1103483219_
            
            
            

<sub>[CAL-1047](https://linear.app/calcom/issue/CAL-1047/dynamically-load-toast-on-booking-page-they-don)</sub>

**Comment by saideepesh000** [comment]
can I pick this up @hariombalhara @PeerRich ?

**Comment by hariombalhara** [comment]
Sure @saideepesh000. Go for it !!

**Comment by saideepesh000** [comment]
hey @hariombalhara , so toast as in toast components?, can u give some more details?

**Comment by hariombalhara** [comment]
I am taking specifically about Toaster component here. For `showToast` method to work the page needs to have Toaster Component.
But it's not being used on Booking Pages, so no toast is being show to bookers in that flow.
<img width="1375" alt="Screenshot 2023-02-27 at 12 51 20 PM" src="https://user-images.githubusercontent.com/1780212/221499393-79adca4e-36de-4834-9f23-cc1fab9e7f6d.png">

**Comment by saideepesh000** [comment]
ok, to confirm, this issue is adding a toast component on the booking page and dynamically loading them, right?

**Comment by hariombalhara** [comment]
@saideepesh000 Yes, we need to add Toaster component but dynamically. The goal is to not increase the bundle size for booking page for a toast that is seldom shown

**Comment by PeerRich** [comment]
why do we need to toast on the booking page?

**Comment by hariombalhara** [comment]
If some unexpected error occurs anywhere on the flow, that error is to be shown using Toast.

e.g. our Form component shows it's error using Toast
