### ISSUE TITLE
[CAL-1048] Lazy load Phone Number Input on BookingPages

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7063]
Can we lazy load this component?

_Originally posted by @zomars in https://github.com/calcom/cal.com/pull/6560#discussion_r1103483352_
            

<sub>[CAL-1048](https://linear.app/calcom/issue/CAL-1048/lazy-load-phone-number-input-on-bookingpages)</sub>

**Comment by esau-morais** [comment]
May I be assigned to work on this issue?

**Comment by hariombalhara** [comment]
@esau-morais Sure. Done

**Comment by esau-morais** [comment]
Correct If I'm wrong, but when I was taking a look closely to the code and trying to understand the component highlighted in this issue, I've found there's already a dynamic import for it, but it just is used nowhere. Can I then just implement it at the `BookingPage.tsx`?

![packages/ui/form/PhoneInputLazy.tsx](https://user-images.githubusercontent.com/55207584/218630525-01d5873e-e28d-4496-8bf2-c34158523fc4.png)

**Comment by zomars** [comment]
Will close for now. This was an oversight of my part. Thanks again for you contribution 🙏🏽
