### ISSUE TITLE
[CAL-1049] Arrow scrollbar showing on dropdown

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#7064]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0b7469c4-8bc1-4fdc-8aed-8e390494af01/6a2b4c04-027b-4cc3-a272-7522c38e0080)

There is an arrow scrollbar on the right hand side of the dropdowns on the /bookings page.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1049](https://linear.app/calcom/issue/CAL-1049/arrow-scrollbar-showing-on-dropdown)</sub>

**Comment by esau-morais** [comment]
May I be assigined to solve this issue?
