### ISSUE TITLE
[CAL-1051] Some variables in custom webhook template do not work

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7067]
Some variables in custom webhook template do not work. For example, the yellow marked ones do not work: 

[Screenshot 2023-02-13 at 07.55.10](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cf9cdb48-0211-4099-96a4-bc68cabc3d3c/f3a64249-166d-4a21-b190-d5afcbdf1d91)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1051](https://linear.app/calcom/issue/CAL-1051/some-variables-in-custom-webhook-template-do-not-work)</sub>

**Comment by ajitzero** [comment]
Related #7097 - Potentially the same root cause.
