### ISSUE TITLE
[CAL-1052] Support a purely HTML embed

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7068]
Created via Threads. See full discussion: [https://threads.com/messages/263f3faa-645f-468a-b845-62d27fb7b5a6?messageID=9a54e5c7-321e-440f-8229-c7a2e42972f6](https://threads.com/messages/263f3faa-645f-468a-b845-62d27fb7b5a6?messageID=9a54e5c7-321e-440f-8229-c7a2e42972f6)

users are having problem embedding the iframe directly. That option is required because of certain website builders not allowing scripts and only HTML.

![Screenshot 2023-02-13 at 6.34.56 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/522c111f-1285-4a72-84e9-1010568dd594/17f34731-295f-4a3e-9983-472d2e3ba535)

As part of this ticket I would also be adding an HTML(or maybe IFRAME) option.( After renaming HTML to script because it adds a script tag), that would just give an iframe HTML with no Javascript. Will need to add a disclaimer as well that it won't be as good as the other supported versions and only recommended if you can't add Javascript/Script tag

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1052](https://linear.app/calcom/issue/CAL-1052/ability-to-embed-the-calcomusername-page)</sub>

**Comment by esau-morais** [comment]
Can I be assigned to solve this issue?

**Comment by PeerRich** [comment]
hmmmmm not sure if we wanna support iframes. i mean we could, it just causes other issues

**Comment by PeerRich** [comment]
honestly they can just copy the url into an iframe no?

**Comment by sean-brydon** [comment]
> honestly they can just copy the url into an iframe no?
![image](https://user-images.githubusercontent.com/55134778/218568778-662a0a54-0a12-48f5-bf3d-55cbbaf9d3d8.png)
Looks like it ... They dont get the config options i can imagine that being a pain to support with Iframe anyway 🤔

**Comment by PeerRich** [comment]
yeah the config smartness is the whole point of the script

**Comment by hariombalhara** [comment]
Closing the issue as we don't want to do it.
