### ISSUE TITLE
[CAL-1056] Consistent Behavior in Displaying Timezones on Availabilities

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#7073]
When you create an availability but have all days blocked off, the time zone for that availability shows. 

The timezone for availability *should* always show, regardless of whether there are no days available.

![CleanShot 2023-02-13 at 08.18.56@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/eff1b43c-0434-4ae4-a98e-6c1b3d7ef8b0/5bbdf4a5-e69a-4b32-8e48-d9276ff73506)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1056](https://linear.app/calcom/issue/CAL-1056/consistent-behavior-in-displaying-timezones-on-availabilities)</sub>

**Comment by PeerRich** [comment]
things cant be a bug and improvement

**Comment by shirazdole** [comment]
Dope good to know
