### ISSUE TITLE
[CAL-1101] Terms & Conditions Check Box 

### ISSUE THREAD

**Issue by geoffjohnsonphoto** [calcom/cal.com#7074]
### Is your proposal related to a problem?
Yes
 I'm trying to find a solution for my clients to agree to terms and conditions when booking appointment.  

### Describe the solution you'd like

I would like to have a terms & conditions solution, by allowing me to list my terms or a link to my terms and a check box option next to it.

### Describe alternatives you've considered

I tried to setup a check box with this statement, but you have no where to list the Terms OR a way to add a link other than on the main booking page.  I want them to be able to review the terms and check all from the same page.

### Additional context

[(Write your answer here.)]
(https://cal.com/lumierestudio/book?type=179415&date=2023-02-28T09%3A45%3A00-06%3A00&slug=2-hours-studio-rental&count=)

<sub>[CAL-1101](https://linear.app/calcom/issue/CAL-1101/terms-and-conditions-check-box)</sub>

**Comment by PeerRich** [comment]
i was looking into this earlier. there are two options worth exploring: 

(a) have a proper "Terms of Service" component that takes a link

or

(b) enable URLs inside of our existing checkboxes

**Comment by Jaibles** [comment]
Preference for (b). 
- Useful for other use cases and many users.
- No downside on the result (what ends up on the booking page)
- No additional cognitive load as it doesn't require the addition of a specific setting to wade through and ignore for those who don't need it.

**Comment by PeerRich** [comment]
ok. we could enable markdown links in checkboxes: `[Terms of Service](https://cal.com/terms)` => [Terms of Service](https://cal.com/terms)

**Comment by masteradhoc** [comment]
@PeerRich just came here from calendly as they dont offer something like this and we need it for GDPR Reasons.
Waiting for the new Version to see it but would suggest that we can additionally highlight to the user that markdown is supported here or have the seperate component additionally in the future.
