### ISSUE TITLE
[CAL-1058] chore: reduce rerenders of sidebar when changing routes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7077]
right now we rerender the entire sidebar when changing routes and it prevents us from using animation on the `<Tips>` component

once thats fixed, we can have a nice animation on the tips, but if we add animations now, it would animate for each route change

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1058](https://linear.app/calcom/issue/CAL-1058/chore-reduce-rerenders-of-sidebar-when-changing-routes)</sub>

**Comment by joeshajan** [comment]
Hey, @PeerRich I think we can achieve this by making the sidebar a pure component. I would like to work on this. Can you assign this to me?

**Comment by PeerRich** [comment]
sure @joeshajan go for it!

**Comment by joeshajan** [comment]
Hey, @PeerRich can you please give me more context about this issue?

**Comment by PeerRich** [comment]
the tips sidebar is briefly flickering.

if we add the "autoanimate" ref to it, it would re-animate for every route change

https://user-images.githubusercontent.com/8019099/219694372-6d0d9633-fc76-4141-a69d-2b827a2f476b.mp4

**Comment by joeshajan** [comment]
> the tips sidebar is briefly flickering.
> 
> if we add the "autoanimate" ref to it, it would re-animate for every route change

Yeah got it thanks

**Comment by PeerRich** [comment]
also feel free to re-add this line afterwards and check if it doesnt re-animate for each page change

https://github.com/calcom/cal.com/blob/578308a8cb8f7e57f919d5ab783d7fea44c77e7a/packages/features/tips/Tips.tsx#L115

**Comment by joeshajan** [comment]
> also feel free to re-add this line afterwards and check if it doesnt re-animate for each page change
> 
> https://github.com/calcom/cal.com/blob/578308a8cb8f7e57f919d5ab783d7fea44c77e7a/packages/features/tips/Tips.tsx#L115

sure

**Comment by joeshajan** [comment]
The flickering of tips is fixed in this pr #8065. But the animation is not still added.

So I tried uncommenting this line `ref={animationRef}` and this is how it behaves now I'm not sure if it's working. is this what we want?



https://user-images.githubusercontent.com/69904519/230739250-0eeb73da-a540-4f89-a77a-a57817bb44db.mp4


But the entire tips component is rerendered each time. Can this be the issue?

https://user-images.githubusercontent.com/69904519/230739294-7d12cb0a-4c92-489d-9af8-55981bff3b85.mp4

**Comment by G3root** [comment]
> But the entire tips component is rerendered each time. Can this be the issue?

re-rendering of Tips components is an expected behaviour. regarding the animation i'm not sure about though.

cc: @sean-brydon
