### ISSUE TITLE
Theme color (light) not applied on public event page

### ISSUE THREAD

**Issue by toontoet** [calcom/cal.com#7089]
### Issue Summary

When I choose for the light theme in my Appearance settings, it is applied to my public profile page, but not to the the specific event pages. 

### Steps to Reproduce

1. Change the theme to 'light' in Settings -> Appearance
2. Open your public profile page: it should be light.
3. Click on a public event: It shows dark.

### Technical details

- Tested on Firefox & Chrome on Mac
- Release Docker v.2.5.10-sh-ce

**Comment by toontoet** [comment]
Seems fixed in the latest 2.5.13 release

**Comment by PeerRich** [comment]
thank you for coming back and closing!
