### ISSUE TITLE
Not possible to select a custom duration on public event page

### ISSUE THREAD

**Issue by toontoet** [calcom/cal.com#7090]
### Issue Summary

When I choose 'Allow booker to select duration' while creating a new event-type, the option to select the duration in the public event page doesn't show up.

<img width="463" alt="Screenshot 2023-02-14 at 14 20 29" src="https://user-images.githubusercontent.com/4571503/218751250-552a61fd-264c-4f2b-ab46-9d2ff4d282ce.png">

### Steps to Reproduce

1. Create or edit an Event-type and select 'Allow booker to select duration' 
2. Select a couple of durations and a default
4. Save the event
5. Open you public profile page. The event shows the various durations:
<img width="236" alt="Screenshot 2023-02-14 at 14 20 52" src="https://user-images.githubusercontent.com/4571503/218751783-0ff3680d-37d1-4a72-a79a-08a1eb59a5ec.png">

6. Click on the event. The event page doesn't show different durations anymore:
 <img width="218" alt="Screenshot 2023-02-14 at 14 21 04" src="https://user-images.githubusercontent.com/4571503/218751916-be9591fc-08de-4e79-9618-028d4779679d.png">

### Technical details

- Tested on Firefox & Chrome on Mac
- Docker release v.2.5.10-sh-ce

**Comment by toontoet** [comment]
Seems fixed in the latest release!

**Comment by Timmer2021** [comment]
I don't believe this issue is fixed.. using version V2.6.6 and I can reproduce the fault as the OP mentions..

**Comment by Timmer2021** [comment]
Also noticed that the location shown is not correct..  For instance, if I choose "in person (attendee address)" in the location section of the event setup, hit save, the from the public area, it shows "Teams" (I have it installed).. instead.. which isn't correct.. 

This is a fresh installed and I was playing around with creating and editing events.. When I first started playing with the settings, everything was working.. but as I deleted and edited and added events, the problem started..

**Comment by Timmer2021** [comment]
More to add..  noticing that each event created creates a URL for that event.. once the URL is created, there is no way to edit it.. So let's say for instance I create an event and call it "meetandgreet".. the url, once you save the event is http...... /meetandgreet.. the initial save works fine.. but then if you go to edit the event with the url remaining at /meetandgreet, the edit doesn't save.. BUT if you edit the event and enter a different name in the url to, let's say meetandgreet1, hit save, that new url works fine.. 

Hope this helps..
