### ISSUE TITLE
[CAL-987] Progressive web app

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7100]
### Is your proposal related to a problem?

Managing my reservation calendar from my cell phone is not easy.

### Describe the solution you'd like

A progressive webapp, easier to set up than a mobile application.

### Describe alternatives you've considered

There is not.

### Additional context

No.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-987](https://linear.app/calcom/issue/CAL-987/progressive-web-app)</sub>

**Comment by zomars** [comment]
Cannot reproduce
