### ISSUE TITLE
[CAL-1074] Deactivated apps reappear after upgrade (settings/admin/apps)

### ISSUE THREAD

**Issue by saschafoerster** [calcom/cal.com#7107]
### Issue Summary

After every upgrade, I have to go trough all the apps and re-check their activation status. I deactivate most of the apps there, but it seems like this is reset after every upgrade. 
Also the redesign makes it hard to see instantly, which app is active and which is not. You have to click on the three dots for every single app to check. 

### Steps to Reproduce

- Edit activation status of an app in the admin-interface
- Upgrade a version of cal.com
- All these settings are lost. 

### Technical details

- Happened with the last self hosted version, docker, upgrade from 2.5.10 to 2.5.15

<sub>[CAL-1074](https://linear.app/calcom/issue/CAL-1074/deactivated-apps-reappear-after-upgrade-settingsadminapps)</sub>

**Comment by leog** [comment]
@saschafoerster could you elaborate a bit more on the steps you take to upgrade? what kind of treatment gets your database in that process?

**Comment by saschafoerster** [comment]
This is my upgrade process: 

_cd /home/calcom-docker
git pull
git submodule update --remote --init
docker compose pull
DOCKER_BUILDKIT=0 docker compose build calcom
docker compose up -d_

**Comment by PeerRich** [comment]
fyi @saschafoerster : @leog is working on a different high priority ticket right now

**Comment by saschafoerster** [comment]
No pressure, just a confirmation: it's still happening with upgrades from 2.8.7. to 2.9.8

**Comment by saschafoerster** [comment]
@PeerRich Oh, that is sad. Why are there settings anyway if they get overwritten after every update? Alternatively: is there a script or way to activate only the apps I really want to be used by our team?
