### ISSUE TITLE
[CAL-1067] Availability for collective events is not correctly calculated 

### ISSUE THREAD

**Issue by saschafoerster** [calcom/cal.com#7110]
### Issue Summary

I want to offer collective events with my colleague. But then there are appointments visible to customers, that shouldn't be available, as we are both unavailable. 

### Steps to Reproduce

- I checked my own calender in the debug view. The availabilities are correctly displayed. (Only “problem”, the debug view shows entrys not just from the same day but from a lot of days around, but that's a different bug).
<img width="578" alt="Bildschirm­foto 2023-02-15 um 10 25 03" src="https://user-images.githubusercontent.com/1153741/218987189-0b42ee5a-4979-44c8-8dbf-b6f87bc42b4d.png">
- I checked the availabilities of my team-mate for the same day (there are just the same): 
<img width="560" alt="Bildschirm­foto 2023-02-15 um 10 17 55" src="https://user-images.githubusercontent.com/1153741/218987469-29f867bb-ce88-46b2-bef4-a16eb1cd3579.png">
-So then I checked, what customers can book during that same day: 
<img width="1024" alt="Bildschirm_foto 2023-02-15 um 10 19 02" src="https://user-images.githubusercontent.com/1153741/218987695-dc23984e-95be-45c7-ad64-1c88f3ce29bc.png">

I would expect that there are no events available. 

### Technical details

We are using a self hosted instance of Cal.com, we use docker and we are on the latest version 2.5.15 (bug existed with 2.5.10 also, but I waited some releases). 

<sub>[CAL-1067](https://linear.app/calcom/issue/CAL-1067/availability-for-collective-events-is-not-correctly-calculated)</sub>

**Comment by PeerRich** [comment]
this could be an unsupported caldav server, what are you using?

**Comment by saschafoerster** [comment]
Kerio, happy to create test accounts and help debugging.

**Comment by emrysal** [comment]
It is very likely this is fixed nowadays @saschafoerster sorry about the sluggish follow up. I've tested plenty of collective events over the last few weeks and am 99% sure this can be closed, but feel free to re-open.
