### ISSUE TITLE
[CAL-1089] Availability is ignored and can schedule event extending over available time

### ISSUE THREAD

**Issue by siferati** [calcom/cal.com#7114]
### Issue Summary

Notice how my availability ends at 20:00, but a 30min event can still be scheduled at 19:45.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/15384781/219028103-4f30e2a7-5e9d-4b94-aeea-c27d05bbd8fe.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/15384781/219028498-6fd072c5-0d8f-4d59-941d-95256e6b666b.png">

### Steps to Reproduce

1. Set availability to 17:45 - 20:00
2. Create new event 30min event
3. Event can be booked at 19:45

<sub>[CAL-1089](https://linear.app/calcom/issue/CAL-1089/availability-is-ignored-and-can-schedule-event-extending-over)</sub>

**Comment by PeerRich** [comment]
are you on the latest version? your availability screen looks old

![CleanShot 2023-02-15 at 20 08 48@2x](https://user-images.githubusercontent.com/8019099/219128472-0ab1d906-c6fe-4d37-86da-fef8d5a3aa95.jpg)

**Comment by siferati** [comment]
> are you on the latest version? your availability screen looks old

I'm just using the website [cal.com](https://cal.com/)

**Comment by PeerRich** [comment]
ok, we'll investigate this!

**Comment by PeerRich** [comment]
@emrysal are you aware of this?

**Comment by emrysal** [comment]
I wasn't actually - replacing this part of the logic though so should be fixed this week @PeerRich
