### ISSUE TITLE
[CAL-1071] BOOKING_CREATED event is not triggered in case of "Paid" events and "Requires confirmation" events.

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7120]
\-- Edit by Hariom
When payment is initiated, BOOKING_PAYMENT_INITIATED(or similar) event should be triggered
When payment is done, BOOKING_REQUESTED event should be triggered. Along with a BOOKING_PAYMENT_SUCCESSFUL event maybe

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1071](https://linear.app/calcom/issue/CAL-1071/booking-created-event-is-not-triggered-in-case-of-paid-events-and)</sub>

**Comment by hariombalhara** [comment]
I would be first working on doing a basic(quickly mergeable) refactor of handleNewBooking along with some unit tests.
