### ISSUE TITLE
[CAL-1072] Confirm a booking for an event that "Requires Confirmation" using the API.

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7121]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1072](https://linear.app/calcom/issue/CAL-1072/confirm-a-booking-for-an-event-that-requires-confirmation-using-the)</sub>

**Comment by alishaz-polymath** [comment]
I believe it is already doable with 'status': "ACCEPTED" in _patch request @zomars , no?
