### ISSUE TITLE
[CAL-1076] Link to undefined when loading availability in event type page

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7124]
The "Edit availablity" links to `/availablity/undefined` when loading.

Also unrelated but this is endpoint sometimes gets stuck on loading locally.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/32a392cc-a411-45e9-a454-72ecca84fcdd/c4619064-3530-4129-aa5d-24fc1506b22d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1076](https://linear.app/calcom/issue/CAL-1076/link-to-undefined-when-loading-availability-in-event-type-page)</sub>

**Comment by Mythie** [comment]
Gotcha, raising a PR now!
