### ISSUE TITLE
[CAL-1077] Allow drag and drop to rearrange event types

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7125]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ce6342fa-1697-4b2d-b2f7-49b0eb58f52a/545a2d2a-83ed-4a80-ad48-05078032a342)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1077](https://linear.app/calcom/issue/CAL-1077/allow-drag-and-drop-to-rearrange-event-types)</sub>

**Comment by PeerRich** [comment]
drag and drop is a really odd API and very flaky. since this works already lets keep it low priority or *wont-fix*

**Comment by zomars** [comment]
Partially agree. But if you have 10 event types and want the newest one to be on top it is not a very pleasant UX either.

**Comment by PeerRich** [comment]
i wonder if we should add new events at the top?

**Comment by zomars** [comment]
I would be the same story if you want the new event at the bottom

**Comment by PeerRich** [comment]
of course, I wonder what people prefer tho so you need to do it the least often

**Comment by zomars** [comment]
Maybe a "Send to top" and "Send to bottom" button would suffice.
