### ISSUE TITLE
[CAL-1078] Wrong Spanish translation

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7126]
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8fb6c5e8-ffe6-4229-8b3a-142e6b71e437/0b5f57ec-63d4-483c-be9c-095a4580a955)

I suspect this button is "Nevermind" in english but in spanish "No tiene importancia" means "It doesn't matter" in this context it doesn't makes sense. As it should say something more like "Regresar" to avoid confusion with "Cancel the event".

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1078](https://linear.app/calcom/issue/CAL-1078/wrong-spanish-translation)</sub>

**Comment by PeerRich** [comment]
will fix

**Comment by PeerRich** [comment]
fixed
