### ISSUE TITLE
[CAL-1080] Display On bookingpage bug

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#7128]
When adding multiple locations of the same type you can only set display on booking page on one of the values. Even tho it looks like it is toggled on all of them. 

Thus

cal.com/packages/app-store/locations.ts:212

doesnt display the location as its set to private. 

![CleanShot 2023-02-15 at 20.44.50@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1d393f7c-16a5-431e-a051-91c0a1f570da/b421acf2-09a4-454e-be20-b47bd90d30c8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1080](https://linear.app/calcom/issue/CAL-1080/display-on-bookingpage-bug)</sub>

**Comment by heyanurag** [comment]
Hi team! I've been learning new things from the codebase recently. Can I work on this issue as my first contribution?

**Comment by PeerRich** [comment]
sure @heyanurag go for it!

**Comment by heyanurag** [comment]
Thanks Peer! 
I wanted to ask, why can't I see the `Add a location` button in my local setup? 

![image](https://user-images.githubusercontent.com/63957920/219971029-1b087e1f-1165-4967-8d84-b179925849a3.png)

I checked the code and the button is currently behind a check `validLocations.length > 0`. I tried loggin the `validLocations` array but its empty.

![image](https://user-images.githubusercontent.com/63957920/219971074-5b54fa8e-d77c-44ce-b5bb-a0d4c4bc4957.png)

Any help will be appreciated :)

**Comment by sean-brydon** [comment]
Hey @heyanurag this appears to be a recent bug which happens when you delete the location from the select box. Not 100% sure whats causing it right now as im on mobile. I believe if you create a new event type you should see add a location button

**Comment by heyanurag** [comment]
@sean-brydon even after creating a new event the issue still exists. I also created a new database but no change.

**Comment by PeerRich** [comment]
hey, we have a PR fixed for this, will go live today!

**Comment by Vikram125609** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/93823479/235609958-afee0f11-d14d-450a-8934-10477be52935.png">
Hello @PeerRich you were talking about this "Display on booking page" which is below of united states flag

**Comment by JaideepGuntupalli** [comment]
Hey, @sean-brydon, I think the issue is fixed and should be closed. Pls, look at the following loom. And also there is another issue in ui with adding the same type of locations the states are saved on the component, as can be observed in the given loom. Should I open another issue for it to be explained in detail?

Loom:
https://www.loom.com/share/fa15cc24c3f14722b832ec9feced2a10

**Comment by sean-brydon** [comment]
> Hey, @sean-brydon, I think the issue is fixed and should be closed. Pls, look at the following loom. And also there is another issue in ui with adding the same type of locations the states are saved on the component, as can be observed in the given loom. Should I open another issue for it to be explained in detail?
> 
> Loom: https://www.loom.com/share/fa15cc24c3f14722b832ec9feced2a10

Nice find! Please raise another issue <3 I'll close this one
