### ISSUE TITLE
[CAL-1081] Typing CMD + K shortcuts with the command palette closed still triggers

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7129]
Is this intended? I typed `a` + `s` while reviewing and it took me to the App Store (I didn't open up the command palette)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/282f207d-179b-414a-895d-ccc3fcbe951d/b1726bd5-5ab4-4308-bdac-a6dfdc97bb6d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1081](https://linear.app/calcom/issue/CAL-1081/typing-cmd-k-shortcuts-with-the-command-palette-closed-still-triggers)</sub>

**Comment by Mythie** [comment]
This is intentional, the keys next to the command are telling you the shortcut that you can use to perform the command outside of the selector. Or at least that's my understanding of it all.

**Comment by PeerRich** [comment]
yep intended behavior

**Comment by zomars** [comment]
I think the confusion came when trying to actually write `as` in a disabled input.
