### ISSUE TITLE
[CAL-1082] UI issue: Installed apps / Calendars

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7135]
Currrently

![CleanShot 2023-02-16 at 09.36.54@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dace8760-96c5-49a6-aa05-5ce872779b1d/25f3b066-f475-400d-8445-e7bd710d1578)

Should be

![CleanShot 2023-02-16 at 09.47.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/92b5fee9-2cac-4205-ad21-4bc02c356a31/ae171a6f-5d32-40a3-8d12-67d42f7c17a4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1082](https://linear.app/calcom/issue/CAL-1082/ui-issue-installed-apps-calendars)</sub>

**Comment by Udit-takkar** [comment]
fixed here [https://github.com/calcom/cal.com/pull/7209](https://github.com/calcom/cal.com/pull/7209)
