### ISSUE TITLE
[CAL-1083] Build list item component

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7136]
[📐 Spec - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R?node-id=34256:91348&t=9oeQWwG0vDa3BNlf-1&locale=en&type=design)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1083](https://linear.app/calcom/issue/CAL-1083/build-list-item-component)</sub>

**Comment by mahaveer0496** [comment]
If this is ready for dev, I'd happily take it. Also, the Figma link shows this only. 
<img width="2010" alt="image" src="https://github.com/calcom/cal.com/assets/23198481/03497d44-8702-402f-b9c4-a3e5743ebc09">

It would be great if expected behavior could be described in the ticket/design

@Jaibles

**Comment by Jaibles** [comment]
> If this is ready for dev, I'd happily take it. Also, the Figma link shows this only. 
> 
> <img width="2010" alt="image" src="https://github.com/calcom/cal.com/assets/23198481/03497d44-8702-402f-b9c4-a3e5743ebc09">
> 
> 
> 
> It would be great if expected behavior could be described in the ticket/design
> 
> 
> 
> @Jaibles

Link updated. It is ready for dev @mahaveer0496 but this task would be a huge undertaking as this component touches almost everything in our app.

**Comment by mahaveer0496** [comment]
I can start with development in isolation and if that get merged migrate the usages PR by PR

**Comment by mahaveer0496** [comment]
I've gone through the Figma file. Do I have to create component accepting props exactly as in Figma or am I free to choose how to implement it?
For example - I wouldn't explicitly add props `firstBadge, secondBadge` but rather something like `badges` and
 I also wouldn't have separate props for `toggle, button, more` but rather make it composable and let consumers decide.

@Jaibles

**Comment by ciaranha** [comment]
> I've gone through the Figma file. Do I have to create component accepting props exactly as in Figma or am I free to choose how to implement it?
> 
> For example - I wouldn't explicitly add props `firstBadge, secondBadge` but rather something like `badges` and
> 
>  I also wouldn't have separate props for `toggle, button, more` but rather make it composable and let consumers decide.
> 
> 
> 
> @Jaibles 

Sorry @mahaveer0496 recently changed my username (@Ciaranha) so didn't get notification. @sean-brydon can you help with above query.

**Comment by mahaveer0496** [comment]
Any update? 😅 @sean-brydon @ciaranha
