### ISSUE TITLE
[CAL-1084] Remove premium username warning in /settings/my-account/profile

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7137]
For some reason we've added a warning that the user saying: "You need to reserve your premium username for $29/mo". There should be no warning here.

![CleanShot 2023-02-16 at 09.57.49@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f1ea7b2c-9f69-4afd-aae9-3a089d420a47/87560734-18a4-48bd-aeaf-99c73d852e40)

If I happen to update the username and land on a premium one, then we can tell them. If we can run that check as they type, we can use the helper text to say "You've chosen a premium username for $29/mo"

We can also improve this modal

![CleanShot 2023-02-16 at 09.59.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9833f406-2298-4768-a4db-b9b519c7704e/ffe495ba-9db8-4ebe-9cc2-ecaa61ea7f71)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1084](https://linear.app/calcom/issue/CAL-1084/remove-premium-username-warning-in-settingsmy-accountprofile)</sub>

**Comment by emrysal** [comment]
The incorrectly shown "You need to reserve your premium username for $29/mo" will be remedied on release of  https://github.com/calcom/cal.com/pull/7099.
