### ISSUE TITLE
[CAL-1086] Can't add more than 4 locations to an EventType

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7138]
See loom https://www.loom.com/share/8d3e6338b67e49d59f8a56592fa606bb

<sub>[CAL-1086](https://linear.app/calcom/issue/CAL-1086/cant-add-more-than-4-locations-to-an-eventtype)</sub>

**Comment by Mythie** [comment]
What would propose as a reasonable upper limit for this? I would agree it could be bumped from 4 to say 20?

**Comment by hariombalhara** [comment]
There is not intentional limit right now. This is an accidental thing AFAIK. 
User is the best judge of what he wants

**Comment by esau-morais** [comment]
May I work on this issue?

**Comment by esau-morais** [comment]
Is there a reason why `validLocations` length should be different from `locationOptions`? 

![image](https://user-images.githubusercontent.com/55207584/219659201-e7610881-5a17-411f-8bbc-ef7e8a7273cd.png)

**Comment by esau-morais** [comment]
Could help try to understand why the `locationOptions` should be different from `locations`?

![locations](https://user-images.githubusercontent.com/55207584/219883215-2548b5ca-996c-460b-98e0-1f406f2c2af1.png)
![locationOptions](https://user-images.githubusercontent.com/55207584/219883217-469e3bf5-2ec3-4582-9c82-b1acfbcf383f.png)
![EventSetupTab.tsx](https://user-images.githubusercontent.com/55207584/219883260-bd072572-49fd-47df-af3c-28271ab548f5.png)

**Comment by hariombalhara** [comment]
@esau-morais Can you checkout previous commits to see how it was working earlier.
