### ISSUE TITLE
[CAL-1087] Gcal events from March 1st not being picked up

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7140]
SIU: From the 1st of March, Gcal events are not being picked up, but can't be booked. No available users found error on booking

Created via Threads. See full discussion: [https://threads.com/34449334803](https://threads.com/34449334803)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1087](https://linear.app/calcom/issue/CAL-1087/gcal-events-from-march-1st-not-being-picked-up)</sub>

**Comment by melalj** [comment]
I'm getting a similar issue:
![CleanShot 2023-02-18 at 14 59 16@2x](https://user-images.githubusercontent.com/3869766/219869858-c3d33099-03dd-4510-a63a-b9af7e527a5b.jpg)

**Comment by PeerRich** [comment]
@emrysal and @roae can you two look into this?

**Comment by roae** [comment]
I'm on it

**Comment by roae** [comment]
I could not replicate the error.


![Captura de pantalla 2023-02-20 a la(s) 12 40 27 p m](https://user-images.githubusercontent.com/525369/220405641-bb44c518-d375-4339-8ecf-c0328487c87a.png)

**Comment by melalj** [comment]
I'm still experiencing issues with this.
Timeslots starting from March 1st are not supposed to be shown available to book because there are conflicting events (marked as busy) on my calendar.

I have recorded a screencast to showcase the error. Is there an email I can send this privately to?

**Comment by melalj** [comment]
Do you happen to have any updates on this? This seems critical as I must ensure the cal.com link shows proper slots, and I can trust using it.

**Comment by roae** [comment]
@melalj In which time zone are you located?

**Comment by melalj** [comment]
> @melalj In which time zone are you located? Are you using GCal as well?

Central European Summer Time

**Comment by roae** [comment]
@melalj this was fixed on #9282 
Could you help me verify that is working on your end?

I going to close it, we can re-open it if is needed.
