### ISSUE TITLE
Availability screen – copying time 

### ISSUE THREAD

**Issue by ai-slave** [calcom/cal.com#7143]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6696080/219357565-8da4b6bc-e9b0-4ea6-a020-03de9ed55c57.png">

When I click apply the popover doesn't close and there's no way to understand it worked.
https://app.cal.com/getting-started/setup-availability

**Comment by esau-morais** [comment]
May I work on this issue?

**Comment by PeerRich** [comment]
sure!
