### ISSUE TITLE
[CAL-1100] Overlapping events because Google Calendar is not properly checked

### ISSUE THREAD

**Issue by lukas-at-harren** [calcom/cal.com#7153]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

**This is what I would consider an urgent issue**.
The most basic promise of cal.com does not work, I now had to reschedule client bookings for that reason.
I am running a cal.com instance with Docker-container `calcom/cal.com:v2.5.15`.

Here is how my Google Calendar looks like:
![Screenshot 2023-02-16 at 4 32 41 PM](https://user-images.githubusercontent.com/79307500/219418881-2136a707-8c16-4f97-9450-d5835052b883.png)

And here is what cal.com offers on my schedule page 🤦‍♂️:
![g7n37](https://user-images.githubusercontent.com/79307500/219419616-b9d42385-8978-4cb9-8f38-8cf5febae2a8.png)

I setup the instance to connect to Google Calendar and there it looks like this:
![Screenshot 2023-02-16 at 4 31 04 PM](https://user-images.githubusercontent.com/79307500/219419697-92b452b5-1648-4d5d-8e21-fa584d190c89.png)

### Steps to Reproduce

1. Use cal.com with the given Docker version
2. Setup Google Calendars
3. Check multiple calendars to be checked for availability
4. Booking shows bookings that are available on the cal.com-instance but not on Google Calendar. Boom double bookings... 🤦‍♂️

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Docker container `calcom/cal.com:v2.5.15`

<sub>[CAL-1100](https://linear.app/calcom/issue/CAL-1100/overlapping-events-because-google-calendar-is-not-properly-checked)</sub>

**Comment by Udit-takkar** [comment]
@lukas-at-harren are you still facing this issue ?

**Comment by lukas-at-harren** [comment]
@Udit-takkar thanks for looking at it.
I found a problem with Google Calendar in fact, and it was not with cal.com.

Google Calendar seemed to sometimes create entries showing "as free" and not "as busy" (my default).
