### ISSUE TITLE
[CAL-1096] Embed selection modal - UI update

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7157]
Currently

![CleanShot 2023-02-16 at 19.32.02@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0a671ab2-d67f-4505-8204-cebb87c4878b/074ed943-0b1d-4ace-8db4-5e0728f7fa3b)

Shuold be

![CleanShot 2023-02-16 at 19.33.34@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/40b3f33f-10b3-44f4-b1e8-00f0a925d2a5/b719a58b-87f9-4541-8f7b-dcbff2d89c18)

Main issues:

* svgs have the old grays
* border radius's are off
* other subtle changes required like the hover state and other font issues

[View in Figma](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=22%3A38047&t=AQX9GWSFsCzlRrEy-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1096](https://linear.app/calcom/issue/CAL-1096/embed-selection-modal-ui-update)</sub>

**Comment by addegbenga** [comment]
Hey @Jaibles i will like to work on this.

**Comment by PeerRich** [comment]
hey @addegbenga its already been assigned!
