### ISSUE TITLE
[CAL-1099] Availability section in Event Types configuration doesn't match defined hours

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#7163]
### Issue Summary

After configuring "Personal hours" in the Availability section, selecting this availability type when configuring an event type shows the wrong availability information

### Steps to Reproduce

1. Configure availability like this:

![image](https://user-images.githubusercontent.com/100738/219520024-d2a925f8-78b4-4a9e-8453-6dd9d8407580.png)

2. Set up an event type

3. Click on the Availability section

4. Observe that neither the description of the availability, nor the hours match:

![image](https://user-images.githubusercontent.com/100738/219520251-5645bdfa-86f4-4cb4-baf7-a20cad2b09ce.png)

In this example, it should say "Personal hours" on the left, rather than "Working Hours", since I have "Working hours" defined completely differently:

![image](https://user-images.githubusercontent.com/100738/219520367-a634dda0-3981-4d9e-bd3c-2d4310e01d25.png)

Also it should say 12:30pm not 0:30pm.

### Technical details

- Chrome Version 110.0.5481.96 (Official Build) (64-bit)

<sub>[CAL-1099](https://linear.app/calcom/issue/CAL-1099/availability-section-in-event-types-configuration-doesnt-match-defined)</sub>

**Comment by PeerRich** [comment]
hey @Udit-takkar can you take a look at this? should be quick to fix

**Comment by abhisht51** [comment]
Would it be okay If I pick this up as a good first issue for myself ? Although I would appreciate if I could be pointed to the file or function which displays this

**Comment by Udit-takkar** [comment]
@abhisht51 you can try looking in the apps/web/components/eventtype/AvailabilityTab

**Comment by abhisht51** [comment]
@Udit-takkar sure am at it. If you aren't actively working on it, can I try my hand at it ?

**Comment by abhisht51** [comment]
Hi, 
Just adding some additional issue to this thread. In the dropdown for time-picker, I can't seem to see all the time of day. Please refer to the short loom - https://www.loom.com/share/34e9190117aa4494bdc020586d99e5ab 

Am I missing something here? I have tried looking into account settings to see if this value is limited to 5PM for me for some reason but I couldn't find anything. cc: @PeerRich

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2023-02-24 at 12 35 56 AM" src="https://user-images.githubusercontent.com/53316345/221005731-59f66011-c880-4cc1-81eb-676414934440.png">

@abhisht51 you are seeing time ranges till 5:45 because the end time range is fixed to 6:00 if you update it to let's say 11:59 you would see more slots in the dropdown

**Comment by abhisht51** [comment]
For 1, I have tried adding additional prop of `Availability` to the `formMethods` context but the Availability section on the left is rendered before the value is set. See commit here - https://github.com/abhisht51/cal.com/commit/cfeeff5cbdcf1f342bc23c6a3d2cdff75e3f193a 
 
 
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/39940817/221033060-4c0cd973-82f5-4dc7-bb75-ff4727a72eb7.png">

@Udit-takkar can you suggest a way to get the default value on first load ? I am a bit new to this much state management. 

I am also trying to replicate 2 on my end

**Comment by Udit-takkar** [comment]
@abhisht51 can you create a draft PR so we can see how can we fix it. one way is using useEffect but there could be other better ways

**Comment by Udit-takkar** [comment]
@aspiers i didn't understand your 2nd point. 00:00 is 12 AM and 12:00 is 12 PM ( if you are using 24 hour clock)
