### ISSUE TITLE
[CAL-1102] Choosing a longer duration doesn't consider the busy calendar event

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7172]
[https://app.birdeatsbug.com/sessions/kSeCDwNtMApZ8dIvhH0mNDyro6-1XAhH7cTisceHFfIE](https://app.birdeatsbug.com/sessions/kSeCDwNtMApZ8dIvhH0mNDyro6-1XAhH7cTisceHFfIE)

Created via Threads. See full discussion: [https://threads.com/34449624411](https://threads.com/34449624411)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1102](https://linear.app/calcom/issue/CAL-1102/choosing-a-longer-duration-doesnt-consider-the-busy-calendar-event)</sub>

**Comment by emrysal** [comment]
Fixed in v3.0.15
