### ISSUE TITLE
[CAL-1104] Non Cal link for Cal Video on success page

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7176]
When CalVideo is chosen as the location, the success page (`/booking/[uid]`) doesn't show cal.com/video link. The link is correct in email that is received.

Email:
<img width="694" alt="Screenshot 2023-02-17 at 5 30 06 PM" src="https://user-images.githubusercontent.com/1780212/219648456-83f57add-b1cf-47c1-8ece-a75c9068c223.png">

Success Page:
<img width="1776" alt="Screenshot 2023-02-17 at 5 27 13 PM" src="https://user-images.githubusercontent.com/1780212/219647897-a632c497-3df8-4355-9805-74b55bb9c52f.png">

<sub>[CAL-1104](https://linear.app/calcom/issue/CAL-1104/non-cal-link-for-cal-video-on-success-page)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar is fixing this right now
