### ISSUE TITLE
Accessibility: Toggle "Products" Navigation Menu Viewport on Focus/Blur

### ISSUE THREAD

**Issue by esau-morais** [calcom/cal.com#7199]
### Is your proposal related to a problem?

Most of the time I use my keyboard to navigate through the page and when I was accessing the Landing page and focused the "Products" Item, nothing happened till I hovered with the mouse.

### Describe the solution you'd like

It'd be great to make the "Products" item more accessible by adding the feature to show/hide the navigation menu viewport component (if I'm not wrong) when the user focus, or after focusing and using the enter/space.

### Additional context

I'm considering a case which the user uses keyboard most of the time (I'm pretty sure I'm not the only one)

**Comment by PeerRich** [comment]
oh you mean cal.com? @julianbenegas

**Comment by esau-morais** [comment]
Yes, exactly

**Comment by esau-morais** [comment]
I might get to work on this issue, but I'm struggling to solve some pending issues

**Comment by SamuelKatsaros** [comment]
Are you able to share some insight on how to get to the landing page? I'm currently viewing the calendar post-login, however I'd like to get tot he landing page but don't see a way to.
