### ISSUE TITLE
Conflict checks break with Apple Calendar

### ISSUE THREAD

**Issue by bryanmylee** [calcom/cal.com#7201]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Adding an Apple Calendar app causes all conflict checks to break.

### Steps to Reproduce

1. Set up a Google calendar
2. Check that existing events block available slots on cal.com
3. Add an Apple calendar
4. Check again that all slots become available on cal.com

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I have a few all-day events in my Apple account, but none of the calendars with all-day events are selected for conflict checks.

#### Browser

Chrome Version 110.0.5481.100 (Official Build) (x86_64)

#### Screen recording

https://user-images.githubusercontent.com/42545742/219881388-06a33866-5158-4a38-a6ff-e855f9c1fd97.mov

**Comment by bryanmylee** [comment]
Checking back on this, has there been any discoveries recently? I've been putting off using cal.com for some of my clients until this is resolved but I'd appreciate a timeline if possible

**Comment by alishaz-polymath** [comment]
I've set up to explore it further this week. 🙏

**Comment by alishaz-polymath** [comment]
This was fixed in the PR #7934
