### ISSUE TITLE
Conflict check not working in some events

### ISSUE THREAD

**Issue by solace** [calcom/cal.com#7211]
### Issue Summary

I have 3 event types of 15 min, 30 min, and 60 min durations. All set up pretty much the same way.

I have added several calendars (2x caldav, 2x google) to check against for conflicts.

The 15 min and 30 min events honour conflicts. The 60 min displays all slots even if they have conflicts but when the guest attempts to (re)schedule it, they receive the warning "Could not reschedule the meeting. No available users found."

### Steps to Reproduce

Let me know how to PM the affected calendar events for repro.

### Technical details

I don't know the browser the guest used, but I have been able to reproduce this in Chrome on MacOS.

**Comment by PeerRich** [comment]
can you send us your username here or to support@cal.com? its not possible for us to reproduce this without it

**Comment by PeerRich** [comment]
so both reschedule and scheduling the 60 min doesnt work?

**Comment by solace** [comment]
Just emailed support with the relevant links for repro.

Both rescheduling and scheduling new are returning that error and showing all slots instead of the ones without conflict. The error suggests it's checking, but the calendar grid doesn't prevent scheduling attempts.

Also, I think that the 60 min event is the only one I created from scratch, the other two would have come from the default events that were created on sign up.

**Comment by PeerRich** [comment]
interesting. will investigate immediately. have a lovely rest of your sunday!

**Comment by PeerRich** [comment]
replied to your email. found something interesting. I made a new 60 min event that is working

**Comment by PeerRich** [comment]
can you use the new link I created for you? that should work. I cannot figure out what is wrong with your previous link but the link I made for you works now with 60 min.

will continue to monitor this situation.

thank you for reaching out!

**Comment by PeerRich** [comment]
reopening. fix not fully working
