### ISSUE TITLE
Hydration Error on /[user]/book.tsx when 24h format is enabled

### ISSUE THREAD

**Issue by ShaneMaglangit** [calcom/cal.com#7213]
React hydration error is thrown when opening any /[user]/book page with **24h format** enabled.

### Steps to Reproduce

1. Run the project locally.
2. Open any booking page with 24h format enabled.

### Technical details

This is caused by `parseDate(...)` on BookingPage.tsx[590:81] which depends on `isBrowserLocale24h` that uses `localStorage` under the hood. Essentially, the pre-rendered page parses the date in 12h format while browser tree rendered something in 24h.

**Comment by PeerRich** [comment]
thank you @echo304

**Comment by echo304** [comment]
I have no idea how to deal with it. What am I supposed to do? 🤔 
<img width="927" alt="스크린샷 2023-02-24 오후 3 24 38" src="https://user-images.githubusercontent.com/16456651/221107546-4385f519-b16a-44e2-9579-a594c600c237.png">
