### ISSUE TITLE
[CAL-1115] Consider using @clack/prompts for AppStore CLI

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7220]
It might make App Store CLI super cool.

[https://twitter.com/n_moore/status/1624951793829519362](https://twitter.com/n_moore/status/1624951793829519362)

Created via Threads. See full discussion: [https://threads.com/34448365390](https://threads.com/34448365390)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1115](https://linear.app/calcom/issue/CAL-1115/consider-using-clackprompts-for-appstore-cli)</sub>

**Comment by G3root** [comment]
@hariombalhara is this open ?

**Comment by hariombalhara** [comment]
@G3root Yeah, not sure about priority at the moment though.

**Comment by G3root** [comment]
from the labels its seems low priority. i'll pick another ticket
