### ISSUE TITLE
[CAL-1116] double border in installed apps

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7222]
[https://www.loom.com/share/6abe035446d94e9faf29903ecde5e8cb](https://www.loom.com/share/6abe035446d94e9faf29903ecde5e8cb)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1116](https://linear.app/calcom/issue/CAL-1116/double-border-in-installed-apps)</sub>

**Comment by esau-morais** [comment]
May I work on this issue?
