### ISSUE TITLE
[CAL-1117] /event type location settings - remove it from the modal

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7223]
[Figma link](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=2463%3A143103&mode=dev)

<img width="1488" alt="CleanShot 2023-04-12 at 09 54 19@2x" src="https://user-images.githubusercontent.com/4536123/231390574-e4471fa1-d995-4792-a2ef-6e144fa26986.png">

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1117](https://linear.app/calcom/issue/CAL-1117/event-type-location-settings-remove-it-from-the-modal)</sub>

**Comment by esau-morais** [comment]
May I work on this issue?

**Comment by gitstart-calcom** [comment]
Hi @PeerRich @ciaranha what do you think about adding this arrow right icon to submit?
<img width="924" alt="image" src="https://github.com/calcom/cal.com/assets/121884634/70654aa7-150a-4b83-88c1-fafe9c18561d">
