### ISSUE TITLE
[CAL-1121] reminder emails being sent even after cancellation

### ISSUE THREAD

**Issue by lucaseatp** [calcom/cal.com#7225]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

reminder emails being sent even after cancellation

### Steps to Reproduce

1. set up a workflow with emails
2. appoint a meeting with email workflow
3. cancel the meeting
4. reminder emails still being received

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead? expected to not receive any reminder

<sub>[CAL-1121](https://linear.app/calcom/issue/CAL-1121/reminder-emails-being-sent-even-after-cancellation)</sub>

**Comment by esau-morais** [comment]
Once the meeting has been successfully scheduled, an email is sent to the user confirming it. Isn't it the expected behaviour? The cancellation just removes the meeting from your scheduled provider (e.g.: Google Calendar)

**Comment by CarinaWolli** [comment]
Working on it, fix for this is coming today!
