### ISSUE TITLE
round robin with no dates available

### ISSUE THREAD

**Issue by lucaseatp** [calcom/cal.com#7226]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

calendar shows no available date if you're using round robin with no fixed hosts

### Steps to Reproduce

1. create an event
2. choose round robin type
3. leave fixed hosts blank, only fill round robin hosts
4. calendar will be unavailable

that's a bummer

**Comment by PeerRich** [comment]
need more context. can you send me your link? works on our end

**Comment by PeerRich** [comment]
investigating!

**Comment by PeerRich** [comment]
i have availability there
