### ISSUE TITLE
Email sender should be the event organizer instead of the app name

### ISSUE THREAD

**Issue by verstratenbram** [calcom/cal.com#7228]
### Is your proposal related to a problem?

When our customers receive e-mails about an event, the sender is the current app name "Awesome app" instead of the event organizer "John Doe's Hair Design" (these are just example names 🙂). This is confusing for the customer because they did not make an appointment with "Awesome app".

### Describe the solution you'd like

It would be better if the e-mails were sent in the organizer's name. In this example they would be sent from "John Doe's Hair Design". Some e-mail templates already use the organizer name (like the `attendee-location-change-email` template), but this is not consistent in all the templates.

### Describe alternatives you've considered

--

### Additional context

--

**Comment by PeerRich** [comment]
I am not sure if this is actually possible. we send emails via sendgrid and I am not sure if we can change the name across users

**Comment by zomars** [comment]
The issue I see with this is that you're still sending from `hey@cal.com` (in our case). So it seems strange to change only the name.

**Comment by PeerRich** [comment]
yeah and it can cause issues with a lot of email clients that save the name (i.e. first time you get an email from John Doe but next time it may be from Anna but it'll show John)

**Comment by PeerRich** [comment]
keeping it Cal.com at least will always be Cal.com
