### ISSUE TITLE
404 error on embedded routing forms

### ISSUE THREAD

**Issue by lucaseatp** [calcom/cal.com#7229]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

404 error on embedded routing forms

### Steps to Reproduce

1. create a routing form
2. embed on your website
3. 404 error displays instead of routing form

**Comment by PeerRich** [comment]
i cannot reproduce this. cal.com/sales works

**Comment by PeerRich** [comment]
whats your link? or username?
