### ISSUE TITLE
[CAL-1118] Availability not loading, throws BookingDateInPastError 

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7230]
### Issue Summary

Availability for the current month isn't loading when min minimum notice of event is 0 minutes and event duration is 1 minute. 

### Technical details

`guardAgainstBookingInThePast` function throws `BookingDateInPastError` (message: Attempting to book a meeting in the past.)

<sub>[CAL-1118](https://linear.app/calcom/issue/CAL-1118/availability-not-loading-throws-bookingdateinpasterror)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli is this still open?

**Comment by CarinaWolli** [comment]
Yes, availability is still not loading for that specific case. Error message: 
`{"error":{"json":{"message":"Attempting to book a meeting in the past.","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"slots.getSchedule"}}}}`
