### ISSUE TITLE
[CAL-1119] Wrong format of location on cancelled booking view

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7231]
### Issue Summary

Cancelled booking view should show integration name. It currently says integrations:daily
![Screenshot 2023-02-20 at 09 56 30](https://user-images.githubusercontent.com/30310907/220139831-43f8bf63-5406-4cb0-bc70-91f69bed2c3e.png)

<sub>[CAL-1119](https://linear.app/calcom/issue/CAL-1119/wrong-format-of-location-on-cancelled-booking-view)</sub>

**Comment by esau-morais** [comment]
If I'm not wrong, this is probably related to this [condition](https://github.com/calcom/cal.com/blob/main/apps/web/pages/booking/%5Buid%5D.tsx#L198-L201):
![pages/booking/[uid].tsx](https://user-images.githubusercontent.com/55207584/220159252-c55f0628-0e3e-4084-ad0e-f02f1528afcc.png)

**Comment by CarinaWolli** [comment]
@esau-morais Good point! Not sure. @Jaibles should we still show the location on the cancelled view?

**Comment by PeerRich** [comment]
> @esau-morais Good point! Not sure. @Jaibles should we still show the location on the cancelled view?

no. we can hide the "Where" on cancellations
