### ISSUE TITLE
[CAL-1120] Add Floating Button popup tests.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7233]
```
          Also, e2e were passing. It means that we don't have floatingButton popup tests. Need to add those.
```

*Originally posted by @hariombalhara in* [*https://github.com/calcom/cal.com/pull/7212#discussion_r1112183659*](https://github.com/calcom/cal.com/pull/7212#discussion_r1112183659)

[There are ](https://github.com/calcom/cal.com/tree/4be2eee2da2f39395ba7b448af168606ee825c99/packages/embeds/embed-core/playwright/tests)`inline` embed  and 'click on an element ' embed tests already. These would be very similar to those with just one difference that the tests would execute on floating button popup

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1120](https://linear.app/calcom/issue/CAL-1120/add-floating-button-popup-tests)</sub>

**Comment by esau-morais** [comment]
May I give a try to this issue? (I've never written E2E tests before to be honest, but I'm interest on learning more about it)

**Comment by hariombalhara** [comment]
Happy to help out in any way I can :)

**Comment by esau-morais** [comment]
I wanted to run the tests only related to embed, but it keeps failing:

```shell
yarn test-e2e --project=@calcom/embed-core
```

Once it starts running them, it throws the following errors:

```shell
[WebServer] Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}
```

```shell
Error: Process from config.webServer was not able to start. Exit code: 1




  61 skipped
  1 error was not a part of any test, see above for details

To open last HTML report run:

  npx playwright show-report test-results/reports/playwright-html-report

error Command failed with exit code 1.
```

**Comment by hariombalhara** [comment]
Follow embed-core README to run the embed tests.
