### ISSUE TITLE
Migrate from getSession to getServerSession to reduce page navigation latency

### ISSUE THREAD

**Issue by Mythie** [calcom/cal.com#7242]
### Is your proposal related to a problem?

When using the local environment and production environment, there is some noticeable latency when navigating from `/event-types` to `/bookings/upcoming` or `/availability`. This latency is due to ``getServerSideProps` needing to complete before the page can transition.

This delay is leading to a poor UX where it feels as though the site has gone unresponsive for a second.

You can see the latency in effect here:

https://www.loom.com/share/ef3ee9ca7a9046b18d81169e83dfcb1b

### Describe the solution you'd like

To solve this we need to reduce the amount of time spent in `getServerSideProps` so navigation can be as snappy as possible. 

This will require migrating from `next-auth/react`'s `getSession` method to `next-auth/next`'s `getServerSession` method which will not perform an outbound request to itself in order to fetch session details.

See: https://next-auth.js.org/configuration/nextjs#getserversession

### Describe alternatives you've considered

N/A

### Additional context

I've already taken a crack at this but it needs to be refined as we have handlers in `@calcom/trpc` and `@calcom/features` that can not easily get access to `authOptions` which is a requirement for `getServerSession`.

You can see the current experiment at: https://github.com/Mythie/cal.com/commit/f5b9e10bfb6544a10724449957a6e8413070a590

Performing these changes will result in a drastic reduction for session fetching with the time taken reducing from 200ms to 25ms in local environments.

**Before:**

![image](https://user-images.githubusercontent.com/13398220/220215356-61d116a8-a142-49a8-b063-8f49d656b668.png)

**After:**
![image](https://user-images.githubusercontent.com/13398220/220215382-a1aedb2e-725d-4425-af2b-4038cc06c4b5.png)

**Comment by Mythie** [comment]
Do note that while this is less relevant since you're no longer server rendering. This is still a significant cause of latency on the `/api/trpc/[trpc]` route and should still be investigated 😄

**Comment by zomars** [comment]
Thanks for the suggestion @Mythie we're looking into this 🙏🏽

**Comment by Mythie** [comment]
> Thanks for the suggestion @Mythie we're looking into this 🙏🏽

Cheers! Just wanted to make sure it doesn't get buried since the first issue has been alleviated :)

**Comment by PeerRich** [comment]
@Mythie do you wanna work on this or should someoene of our team look into this?

**Comment by Mythie** [comment]
I could look into this, in the current state we can do the updates I've proposed in my experiment a little cleaner and start by updating the `[trpc].ts` api route. This would yield the quickest win in terms of performance and reduce the amount of time spent with loading spinners when using the product.

Following that we could chase it up with a PR that handles other API routes, specifically those that are imported from another package e.g. `features/ee` and such.

I'm not sure how heavily trafficked these routes are and thus getting the first iteration out which covers the majority would be my priority with this. For the second part I'd probably need to liase with the Cal.com team to figure out the best path forward without performing too many potentially large changes.

**Comment by Mythie** [comment]
Took a crack at the whole change today, progress so far can be found in the logs below. As you can see these changes have a notable impact on performance which should be more pronounced in a production environment.

## Before changes

```
API Request to /api/trpc/viewer.public.i18n took 599ms
API Request to /api/trpc/viewer.availability.schedule.get,viewer.availability.schedule.get,viewer.availability.list took 635ms
API Request to /api/trpc/viewer.public.session,viewer.me,viewer.eventTypes.getByViewer,viewer.teams.getUpgradeable,viewer.appById,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.teams.list,viewer.teams.hasTeamPlan took 637ms
API Request to /api/trpc/viewer.public.i18n took 220ms
API Request to /api/trpc/viewer.eventTypes.getByViewer,viewer.me,viewer.public.session took 249ms
API Request to /api/trpc/viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById took 434ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.teams.list,viewer.teams.listMembers,viewer.eventTypes.getByViewer,viewer.bookings.get took 358ms
API Request to /api/trpc/viewer.public.i18n took 211ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.availability.list,viewer.eventTypes.getByViewer took 329ms
API Request to /api/trpc/viewer.availability.schedule.get,viewer.availability.schedule.get took 124ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.teams.hasTeamPlan,viewer.teams.list,viewer.eventTypes.getByViewer took 230ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.eventTypes.getByViewer took 208ms
API Request to /api/trpc/viewer.workflows.list,viewer.workflows.getByViewer took 189ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.eventTypes.getByViewer took 152ms
API Request to /api/trpc/viewer.workflows.list took 125ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.eventTypes.getByViewer took 157ms
API Request to /api/trpc/viewer.public.i18n took 475ms
API Request to /api/trpc/viewer.eventTypes.get,viewer.public.session took 544ms
API Request to /api/trpc/viewer.eventTypes.getByViewer,viewer.me,viewer.apps took 168ms
API Request to /api/trpc/viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.locationOptions took 374ms
API Request to /api/trpc/viewer.public.i18n took 198ms
API Request to /api/trpc/viewer.public.session,viewer.eventTypes.get,viewer.apps,viewer.me,viewer.eventTypes.getByViewer,viewer.teams.getUpgradeable,viewer.appById,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.locationOptions took 299ms
API Request to /api/trpc/viewer.availability.list,viewer.me,viewer.availability.schedule.get took 138ms
API Request to /api/trpc/viewer.connectedCalendars took 127ms
API Request to /api/trpc/viewer.apps took 646ms
API Request to /api/trpc/viewer.appById,viewer.appById,viewer.appById took 408ms
API Request to /api/trpc/viewer.appById took 409ms
API Request to /api/trpc/viewer.appById,viewer.appById took 412ms
API Request to /api/trpc/viewer.me took 173ms
API Request to /api/trpc/viewer.appById took 106ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.teams.list,viewer.teams.listMembers,viewer.eventTypes.getByViewer,viewer.bookings.get took 310ms
```

## After Changes
```
API Request to /api/trpc/viewer.public.i18n took 48ms
API Request to /api/trpc/viewer.eventTypes.getByViewer,viewer.me,viewer.public.session took 188ms
API Request to /api/trpc/viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById took 77ms
API Request to /api/trpc/viewer.public.i18n took 47ms
API Request to /api/trpc/viewer.public.session,viewer.me,viewer.eventTypes.getByViewer,viewer.teams.getUpgradeable,viewer.appById,viewer.bookingUnconfirmedCount,viewer.teams.listInvites took 213ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.teams.list,viewer.teams.listMembers,viewer.eventTypes.getByViewer,viewer.bookings.get took 147ms
API Request to /api/trpc/viewer.public.i18n took 56ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.availability.list,viewer.eventTypes.getByViewer took 139ms
API Request to /api/trpc/viewer.availability.schedule.get,viewer.availability.schedule.get took 35ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.teams.hasTeamPlan,viewer.teams.list,viewer.eventTypes.getByViewer took 102ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.eventTypes.getByViewer took 100ms
API Request to /api/trpc/viewer.workflows.list,viewer.workflows.getByViewer took 37ms
API Request to /api/trpc/viewer.me,viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.eventTypes.getByViewer took 68ms
API Request to /api/trpc/viewer.eventTypes.get,viewer.public.session took 121ms
API Request to /api/trpc/viewer.eventTypes.getByViewer,viewer.me,viewer.apps took 120ms
API Request to /api/trpc/viewer.teams.getUpgradeable,viewer.bookingUnconfirmedCount,viewer.teams.listInvites,viewer.appById,viewer.locationOptions took 138ms
API Request to /api/trpc/viewer.availability.list,viewer.me,viewer.availability.schedule.get took 187ms
API Request to /api/trpc/viewer.connectedCalendars took 61ms
API Request to /api/trpc/viewer.appById,viewer.appById took 115ms
API Request to /api/trpc/viewer.appById took 115ms
API Request to /api/trpc/viewer.apps took 129ms
API Request to /api/trpc/viewer.appById,viewer.appById took 161ms
API Request to /api/trpc/viewer.appById took 149ms
API Request to /api/trpc/viewer.me took 101ms
API Request to /api/trpc/viewer.workflows.list took 102ms
```

**Comment by Mythie** [comment]
Actually, let's use a table for conciseness. Some results feel skewed due to dev server route compiling but it paints a pretty good picture overall.

| Path                                            | Before Avg | After Avg | Before Med | After Med | Before Min | After Min | Before Max | After Max |
| ----------------------------------------------- | ---------- | --------- | ---------- | --------- | ---------- | --------- | ---------- | --------- |
| /api/trpc/viewer.appById                        | 341.47ms   | 124.25ms  | 460.00ms   | 56.00ms   | 40.00ms    | 40.00ms   | 771.00ms   | 538.00ms  |
| /api/trpc/viewer.apps                           | 397.00ms   | 221.00ms  | 387.00ms   | 387.00ms  | 55.00ms    | 55.00ms   | 820.00ms   | 387.00ms  |
| /api/trpc/viewer.availability.list              | 299.00ms   | 171.50ms  | 295.00ms   | 295.00ms  | 48.00ms    | 48.00ms   | 613.00ms   | 295.00ms  |
| /api/trpc/viewer.availability.schedule.get      | 149.67ms   | 91.67ms   | 197.00ms   | 112.00ms  | 47.00ms    | 47.00ms   | 227.00ms   | 116.00ms  |
| /api/trpc/viewer.bookings.get                   | 276.00ms   | 300.00ms  | 300.00ms   | 300.00ms  | 252.00ms   | 300.00ms  | 300.00ms   | 300.00ms  |
| /api/trpc/viewer.bookingUnconfirmedCount        | 455.06ms   | 228.44ms  | 499.00ms   | 240.00ms  | 87.00ms    | 87.00ms   | 911.00ms   | 499.00ms  |
| /api/trpc/viewer.connectedCalendars             | 286.00ms   | 136.50ms  | 228.00ms   | 228.00ms  | 45.00ms    | 45.00ms   | 738.00ms   | 228.00ms  |
| /api/trpc/viewer.eventTypes.get                 | 151.50ms   | 65.00ms   | 238.00ms   | 65.00ms   | 65.00ms    | 65.00ms   | 238.00ms   | 65.00ms   |
| /api/trpc/viewer.eventTypes.getByViewer         | 343.24ms   | 218.00ms  | 260.00ms   | 209.00ms  | 157.00ms   | 157.00ms  | 783.00ms   | 351.00ms  |
| /api/trpc/viewer.getUsersDefaultConferencingApp | 67.50ms    | 15.00ms   | 120.00ms   | 15.00ms   | 15.00ms    | 15.00ms   | 120.00ms   | 15.00ms   |
| /api/trpc/viewer.integrations                   | 103.69ms   | 45.88ms   | 102.00ms   | 35.00ms   | 20.00ms    | 20.00ms   | 275.00ms   | 118.00ms  |
| /api/trpc/viewer.locationOptions                | 443.50ms   | 251.00ms  | 636.00ms   | 251.00ms  | 251.00ms   | 251.00ms  | 636.00ms   | 251.00ms  |
| /api/trpc/viewer.me                             | 353.63ms   | 106.50ms  | 174.00ms   | 98.00ms   | 48.00ms    | 48.00ms   | 912.00ms   | 174.00ms  |
| /api/trpc/viewer.public.i18n                    | 280.00ms   | 141.67ms  | 210.00ms   | 130.00ms  | 85.00ms    | 85.00ms   | 757.00ms   | 210.00ms  |
| /api/trpc/viewer.public.session                 | 383.00ms   | 214.00ms  | 218.00ms   | 218.00ms  | 210.00ms   | 210.00ms  | 721.00ms   | 218.00ms  |
| /api/trpc/viewer.teams.getUpgradeable           | 358.12ms   | 101.67ms  | 160.00ms   | 83.00ms   | 50.00ms    | 50.00ms   | 773.00ms   | 160.00ms  |
| /api/trpc/viewer.teams.hasTeamPlan              | 547.50ms   | 82.00ms   | 1013.00ms  | 82.00ms   | 82.00ms    | 82.00ms   | 1013.00ms  | 82.00ms   |
| /api/trpc/viewer.teams.list                     | 310.00ms   | 249.50ms  | 383.00ms   | 383.00ms  | 116.00ms   | 116.00ms  | 500.00ms   | 383.00ms  |
| /api/trpc/viewer.teams.listInvites              | 378.82ms   | 129.56ms  | 233.00ms   | 119.00ms  | 64.00ms    | 64.00ms   | 781.00ms   | 233.00ms  |
| /api/trpc/viewer.teams.listMembers              | 381.00ms   | 269.00ms  | 493.00ms   | 269.00ms  | 269.00ms   | 269.00ms  | 493.00ms   | 269.00ms  |
| /api/trpc/viewer.workflows.getByViewer          | 151.50ms   | 67.00ms   | 236.00ms   | 67.00ms   | 67.00ms    | 67.00ms   | 236.00ms   | 67.00ms   |
| /api/trpc/viewer.workflows.list                 | 213.25ms   | 181.00ms  | 255.00ms   | 289.00ms  | 73.00ms    | 73.00ms   | 289.00ms   | 289.00ms  |
