### ISSUE TITLE
[CAL-1125] back arrow not centered in app detail page

### ISSUE THREAD

**Issue by G3root** [calcom/cal.com#7246]
![Screenshot 2023-02-21 at 11-40-25 Zoom Video Cal com](https://user-images.githubusercontent.com/84864519/220261993-b5ab8f26-2bfb-4267-8acc-c7649d19c712.png)

<sub>[CAL-1125](https://linear.app/calcom/issue/CAL-1125/back-arrow-not-centered-in-app-detail-page)</sub>

**Comment by leventdeniz** [comment]
I could do this

**Comment by PeerRich** [comment]
thank you! assigned you @leventdeniz
