### ISSUE TITLE
[CAL-1126] Add GCal warning to Amie & Vimcal

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#7254]
Add the same warning from Meet to Amie & Vimcal. Also have the component check if GCal is already installed

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fa3c885c-e7dc-4c1f-9242-e2229e7a0948/e58aebed-b7de-46f3-a009-de4980e1af37)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1126](https://linear.app/calcom/issue/CAL-1126/add-gcal-warning-to-amie-and-vimcal)</sub>

**Comment by sean-brydon** [comment]
@Jaibles we created some new designs around this alert here right? 

From what i remember we were both very confused why we actually see this alert when you already have a google calendar account connected. Seems a bit like YEAH i know i do?

**Comment by Jaibles** [comment]
> @Jaibles we created some new designs around this alert here right? 
> 
> 
> 
> From what i remember we were both very confused why we actually see this alert when you already have a google calendar account connected. Seems a bit like YEAH i know i do? 

Yep, should be on the main live file. Will get link shortly

**Comment by Jaibles** [comment]
@sean-brydon @joeauyeung here you go. Any questions or thoughts let me know!

 [It's in the main Figma live file](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=2835%3A129472&t=hhHaooo8Wt9FsJAv-1).

![CleanShot 2023-02-22 at 16 05 12@2x](https://user-images.githubusercontent.com/4536123/220684798-5a8cba19-957c-4bb1-b091-4a674fed1601.png)

![CleanShot 2023-02-22 at 16 05 29@2x](https://user-images.githubusercontent.com/4536123/220684632-74060f5d-0f09-476a-8e87-32a9ef62c096.png)

**Comment by PeerRich** [comment]
ah perfect much better
