### ISSUE TITLE
[CAL-1128] Fix booking payment message

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#7259]
Check if message display only when required.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9ad7f2e-168a-4372-95ea-6354c5ef0ca5/7dabf719-1e7f-429a-82de-a812724f458e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1128](https://linear.app/calcom/issue/CAL-1128/fix-booking-payment-message)</sub>

**Comment by esau-morais** [comment]
Maybe you could already close this issue, once the PR has been merged (?)
