### ISSUE TITLE
[CAL-1130] Customer organizer receives 2 google event on email.

### ISSUE THREAD

**Issue by alannnc** [calcom/cal.com#7263]
Whenever a book calendar event occurs, user receives 1 update on event from [cal.com](http://cal.com) and other from google.

Let's find a way to prevent this and it should only arrive 1 wether it's from cal or google.

* Also investigate for a way for user owners to customize every email sent from an event type.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1130](https://linear.app/calcom/issue/CAL-1130/customer-organizer-receives-2-google-event-on-email)</sub>

**Comment by abhisht51** [comment]
I have been trying to look at some good backend issues in this repo to contribute. This one caught my attention, however I was unable to replicate it on my end. 
Could you please share what the required preconditions are for this event

**Comment by Udit-takkar** [comment]
@alannnc does this happen when you add events to a secondary calendar like https://github.com/calcom/cal.com/issues/5588 ?

**Comment by alannnc** [comment]
Fixed on https://github.com/calcom/cal.com/pull/7920
#7920
