### ISSUE TITLE
[CAL-1131] Ability to Duplicate Teams

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#7264]
Ability to easily duplicate a team and all event types within that team. Similar to how an event type is duplicated, we will need the same ability to duplicate that team and the event types within the team. 

My bigger question is, do all team members get pulled into that new team as well? 

* We could have a checkmark box saying, "would you like to add all existing team members to this new team as well," but then how do we handle billing? 
* Should we have it where it's a list of all team members that are auto-selected, and then the admin can go in and remove team members they don't want on that new team?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1131](https://linear.app/calcom/issue/CAL-1131/ability-to-duplicate-teams)</sub>

**Comment by PeerRich** [comment]
i dont think we should be doing this. i think this is hard to do and has many edge cases and is very rarely needed

**Comment by shirazdole** [comment]
cc @Jaibles - this may be asked for the Lumistry product call (they asked for this feature initially)
