### ISSUE TITLE
[CAL-1132] Dialog content blurry in Chrome

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7265]
### Issue Summary

Dialog content is sometimes blurry in Chrome. 

Create webhook in team event type settings: 
![Screenshot 2023-02-21 at 15 00 27](https://user-images.githubusercontent.com/30310907/220446218-ff7a4cec-9f28-4aae-977c-358e4b6463b4.png)

Custom event name (with smaller screen size)
![Screenshot 2023-02-21 at 14 58 43](https://user-images.githubusercontent.com/30310907/220446537-4c656db1-b189-47b5-b0dd-243d3861183e.png)

### Technical details

- Only happens in Chrome
- It happens because of the translate(-50%, -50%) to center the dialog

<sub>[CAL-1132](https://linear.app/calcom/issue/CAL-1132/dialog-content-blurry-in-chrome)</sub>

**Comment by sean-brydon** [comment]
> translate(-50%, -50%) 

Wait does radix do this :O 

Should be easy to fix if we use some asChild + our own styles 

(Should)
