### ISSUE TITLE
Building the latest release (2.6.3) with docker fails

### ISSUE THREAD

**Issue by kolaente** [calcom/cal.com#7277]
### Issue Summary

(Please move this issue if you think it belongs to the docker repo)

Trying to build the latest release 2.6.3 with the steps outlined [here](https://github.com/calcom/docker#advanced-users-build-and-run-calcom) fails with this error message:

```
@calcom/embed-snippet:build: [vite:terser] terser not found. Since Vite v3, terser has become an optional dependency. You need to install it.
@calcom/embed-snippet:build: error during build:
@calcom/embed-snippet:build: Error: terser not found. Since Vite v3, terser has become an optional dependency. You need to install it.
@calcom/embed-snippet:build:     at loadTerserPath (file:///calcom/node_modules/vite/dist/node/chunks/dep-9912c491.js:13812:19)
@calcom/embed-snippet:build:     at Object.renderChunk (file:///calcom/node_modules/vite/dist/node/chunks/dep-9912c491.js:13848:32)
@calcom/embed-snippet:build:     at file:///calcom/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24160:40
@calcom/embed-snippet:build:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@calcom/embed-snippet:build: error Command failed with exit code 1.
@calcom/embed-snippet:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/embed-snippet:build: ERROR: command finished with error: command (packages/embeds/embed-snippet) yarn run build exited (1)
command (packages/embeds/embed-snippet) yarn run build exited (1)
```

**Comment by PeerRich** [comment]
@krumware maybe because of the vite change?

**Comment by krumware** [comment]
@PeerRich it looks like it's used in embed-snippet and needs to be added as a dev dependency there (or where the monorepo requires)

https://github.com/calcom/cal.com/tree/445cdd7cbfaf2d3fb22e603350a872ca1b64e2c8/packages/embeds/embed-snippet
(remarks about adding the npm dev dependency here): https://vitejs.dev/blog/announcing-vite3.html#bundle-size-reduction

**Comment by krumware** [comment]
@hariombalhara just to follow up, the build failure did occur in the docker repository, but it isn't currently embedded as a standard check on the cal.com repository side
