### ISSUE TITLE
Sync not working properly (several issues) resulting in overlapping appointments/double-bookings

### ISSUE THREAD

**Issue by domjour** [calcom/cal.com#7278]
### Issue Summary
![Bildschirm­foto 2023-02-22 um 10 15 02](https://user-images.githubusercontent.com/126060707/220575913-f52cfc68-db62-4a28-99b6-c4465f7f3c5e.png)
Yesterday and today two users booked appointments at times that were already blocked with other appointments in my calendar (which is a critical problem for me).
On top there are several other issues (see below).

### Steps to Reproduce
1. I have two calendars that were checked for conflicts. Because of this problem I now switched to only one calendar but there are still problems.
2. I checked the current availabilities and some of the availabilities are shown correctly, others though are not.
3. E.g. one day (march 1st) is shown with full availability (even though there are appointments that day).
<img width="229" alt="Bildschirm­foto 2023-02-22 um 10 31 11" src="https://user-images.githubusercontent.com/126060707/220580636-32bfef26-0d2e-494c-a626-0f163dba64d9.png">

![Bildschirm­foto 2023-02-22 um 10 37 19](https://user-images.githubusercontent.com/126060707/220582557-d1a70c19-0085-4c61-8875-2fe9ab8e47d8.png)

4. But when I try to book an appointment on this day it says "No available users found."
![Bildschirm­foto 2023-02-22 um 10 26 43](https://user-images.githubusercontent.com/126060707/220578282-d0b5c7ac-017b-4875-bfb7-7fe53d8c4fa5.png)
6. This error occured already at edge times the last two weeks. My working hours are set till 6 pm with 1 hour appointment, so the latest possible should be 5 pm. But still cal shows 5.15 pm. When someone tries to book it, it shows the same error as above.
7. Another issue: On some days it shows for about 2 seconds all availabilities before limiting it to the real ones.

### Technical details
We have a self-hosted version of cal.com (2.6.0) and the calendar is synced with Google Calendar.

**Comment by PeerRich** [comment]
hey @domjour we will immediately investigate!

**Comment by PeerRich** [comment]
have you tried upgrading to 2.6.3?

**Comment by domjour** [comment]
Hey @PeerRich, thanks for your quick reply. We'll try that. I will give an update afterwards.

**Comment by roae** [comment]
@domjour the events on your calendar have a busy mark?

![imagen](https://user-images.githubusercontent.com/525369/220735701-70870a8f-89c5-445b-85e5-b12285994c20.png)

**Comment by domjour** [comment]
So we upgraded (or try to upgrade) our version, but it seems there were issues as well. The person responsible for it, gave me the following information:
- The update to v2.6.3 wasn’t possible because of an internal dependency bug in Cal, but v2.6.2 worked.
- The UI still shows v2.6.0 but it is running v2.6.2, probably a display bug.

Upgrading (to v2.6.2) didn´t help. The above mentioned sync issues are still there. @PeerRich 

@roae Yes, all the events are marked as busy in Google Calendar.

**Comment by PeerRich** [comment]
ok @roae will take a deeper look today. would it help to jump on a screenshare call?

**Comment by toontoet** [comment]
I can confirm this using Google Calendag, but also using Outlook. In my case, events that I manual add to my calendar won't show up as unavailable time on the booking page.

**Comment by domjour** [comment]
Thanks for sharing @toontoet.

In the cal Slack channel "#docker" someone posted: "a bunch of users are having some serious issues with date availability including dates being bookable when they shouldn't, overrides not actually working and "Could not book the meeting. No available users found."..." Several from our team are experiencing the same issues.

If it helps to narrow down the error causes, I´m open for a screenshare call.

**Comment by domjour** [comment]
@PeerRich @roae **Any updates on these issues?**
Today one of my team members had a double booking again. Combined with the incorrectly displayed availabilities in some cases and the "no available users found" bug, this is a real problem that is costing us a lot of time to fix. Looking at the other reports here in github and Slack with similar issues, this seems to be more of a general problem. We would be very grateful if you could resolve this issue with high priority.

**Comment by luvs** [comment]
We have similar issues

**Comment by oowl** [comment]
I have the same issue.

**Comment by toontoet** [comment]
For me it looks like a caching issue. If I block some times using my regular calendar, these time stay available on the calcom booking page. I waited some time, but it didn't seem to sync.
After I called `/api/revalidate-calendar-cache/[username]` the timeslots I blocked were also not available anymore on the booking page.
How does the invalidation of the calendar cache work? If performance of real-time loading of the calendar data is an issue, it might be worth to implement it as a background-job running every minute or so.

Is there a way to disable calendar-caching in the mean time?

**Comment by niconomaa** [comment]
@PeerRich 

still experiencing the same problem as @domjour at v2.6.12, may what @toontoet be a potential fix?

**Comment by domjour** [comment]
As mentioned before the issues (not showing the right availability & double bookings) still persist even with the newest version (v.2.6.12).
I just found out that switching the toggle in the general settings to check for conflicts (see screenshot) **off and on again**, leads to showing the right availability.
![Bildschirm­foto 2023-03-14 um 13 51 05](https://user-images.githubusercontent.com/126060707/225007255-ce7f9325-c6b4-4eee-bbcb-6d669c9c9abb.png)

**Steps to reproduce**
1. Create a new meeting in Google Calendar, e.g. at 9am.
2. The time slot 9am is still (wrongly) shown at cal.com.
3. Go to the general settings and switch the mentioned toggle off and on again.
5. The time slot at 9am vanishes at cal.com.

So it seems that the update/sync with the Google Calendar only happens then.
Could you please look into it again or give any updates on this?

**Comment by roae** [comment]
@domjour can you try again in the latest release please?

**Comment by Timmer2021** [comment]
I can confirm with domjour that toggling the callendar (as shown in his pic) does a re-sync to the calender it is subscribed to.. I am currently having the same issue.. If I manually plug something into my outlook calendar, the time is not acknowledged in Cal.com until a re-sync is, in this case, manually done..  Any resolution to this problem in the works? Currently using version 2.7.3

**Comment by domjour** [comment]
@roae As mentioned in Slack here is the video showing the problems we still have. This is **version 2.7.5 (self-hosted)**.
https://www.loom.com/share/f8d84c4e9d254bb9bc1b347fbfbe93b8

What it shows:
1. The first 30 seconds show that the available options are displayed correctly (at the beginning) and that booking a new appointment works as it should and the calendar is updated correctly. **But then the problems start.
2. Adding a meeting at 2pm in Google Calendar, but it still incorrectly shows a free slot at 2pm in the cal-Calendar.
3. Booking a meeting at 2pm in Cal results in a double booking.
4. Adding a meeting at 4pm in Google Calendar, but it incorrectly still shows a free slot at 4pm in cal-calendar. (same problem as in 2.)
5. "Forcing" cal-calendar to refresh by going to Settings and switching the toggle for conflict checking off and on again as well as clicking again on the selected calendar. This gets the desired behaviour and the slots are displayed correctly.

**Comment by Timmer2021** [comment]
@roae 

Just following up on domjour's message.. this is exactly what I' experiencing as well.. Can you advise if there is any development to resolve the issue? Unfortunately with this fault, I can't put my cal instance in production.. 

Even some sort of cronjob would be beneficial at this point to "force" the refresh, as point 5 listed in the message above.. 

Any update would be greatly appreciated. 

T.
