### ISSUE TITLE
I can see private/removed event types by changing URL query parameter

### ISSUE THREAD

**Issue by anton-isaykin** [calcom/cal.com#7280]
### Issue Summary

By changing the `type` query parameter in the URL, I can reveal private/removed meetings.

### Steps to Reproduce

1. Go to the booking page https://cal.com/username
2. Click by date and time then.
3. You are on page https://cal.com/username/book?type=ID&date=DATE&slug=SLUG
4. Change `ID` in the URL to any other numeric ID. You will see removed or private event types belonging to the same person.

Finding a proper ID on cal.com is difficult because of the number of users, but finding an existing ID for the self-hosted version is no issue.

### Technical details

- Release [v2.5.15](https://github.com/calcom/cal.com/releases/tag/v2.5.15).

**Comment by PeerRich** [comment]
hmmm i am not sure if this is a big enough security concern. will talk to the team

**Comment by PeerRich** [comment]
i think since this requires guessing, and private links can always be guessed, we can close this
