### ISSUE TITLE
Markdown syntax in profile description not sanitised out in OG metadata

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#7281]
### Issue Summary

If markdown syntax is used in profile descriptions, the raw syntax is displayed in social embeds and included in the OG metadata.

Related #6204

**Comment by PeerRich** [comment]
can you post an example?

**Comment by ChipWolf** [comment]
@PeerRich 

`Cal`
![](https://i.imgur.com/4BQg0Yz.png)


`Discord`
![](https://i.imgur.com/KJ80eoa.png)


`Twitter`
![](https://i.imgur.com/TKxHVbb.png)
