### ISSUE TITLE
[CAL-1136] Setting another conferencing app as default still uses Cal Video

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7286]
… for event types that have no location set

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e5e51da1-550c-41d3-874e-e8b3a335a26e/297c0d39-7ab8-4340-b443-014cef73a178)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/492a6cee-1436-4703-8161-81508eeff35b/774c21ed-e659-4944-ad93-ed6d90347d56)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7bcc8399-b08e-4126-bb89-d75a3d216f33/9a3ece28-5548-4643-ba37-265deaf03c74)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1136](https://linear.app/calcom/issue/CAL-1136/setting-another-conferencing-app-as-default-still-uses-cal-video)</sub>

**Comment by rksingh2001** [comment]
Can I take this issue?

**Comment by rinkuhasija** [comment]
Yes, @ygpta is right here.
I also tried to reproduce the issue, but looks like it's already fixed.

Can you confirm @zomars

**Comment by Shriom-Trivedi** [comment]
Yes, this looks like it is fixed.
@zomars can you please confirm this.
