### ISSUE TITLE
[CAL-1137] missing margin top on mobile event types

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7290]
![16CEC9EE-0539-4D7A-9FE1-75108B688841.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9cb85e0f-598c-47ef-8033-e7d0c4d4a641/6230126b-0676-41a9-90e7-b11c9ea2d761)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1137](https://linear.app/calcom/issue/CAL-1137/missing-margin-top-on-mobile-event-types)</sub>

**Comment by esau-morais** [comment]
Maybe this could be added to #7257, once it's also (probably) related to the `Shell`. What do you say?

Availability page
![image](https://user-images.githubusercontent.com/55207584/220924196-baac0cd6-31c1-4fe1-9a77-481d015fda9c.png)

**Comment by PeerRich** [comment]
yeah it seems to be affected in Shell. Do you wanna give this a try? seems to be only on mobile, desktop seems fine

**Comment by esau-morais** [comment]
The changes have been merged, if you can please close the issue
