### ISSUE TITLE
[CAL-1140] App: Ability to sync Cal.com Routing Forms to HubSpot routing Forms

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7298]
requested by a user

> Also something that couldn't find on the platform is a way to connect the Routing form with Hubspot, I already installed the HubSpot app on the platform, but I cannot find a way to match the form on the routing forms to Hubspot

<sub>[CAL-1140](https://linear.app/calcom/issue/CAL-1140/app-ability-to-sync-calcom-routing-forms-to-hubspot-routing-forms)</sub>

**Comment by darshandamre** [comment]
will work on this, who should i reach out to if i have any question?
