### ISSUE TITLE
[CAL-1141] Add new events to webhook BOOKING_PAID, BOOKING_CONFIRMED, BOOKING_REJECTED

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#7299]
Add new events to webhook, namely:

* BOOKING_PAID | When a booking has been paid for successfully
* BOOKING_REQUESTED | When an opt-in booking is made (not yet confirmed)
* BOOKING_REJECTED | When an opt-in booking is REJECTED

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1141](https://linear.app/calcom/issue/CAL-1141/add-new-events-to-webhook-booking-paid-booking-confirmed-booking)</sub>

**Comment by CarinaWolli** [comment]
Currently, BOOKING_CREATED is triggered once a booking is confirmed. So this would be changed then, that it already triggers once a booking that requires confirmation is booked, right? 
Do we have any concerns here for already existing webhooks with BOOKING_CREATED triggers?

**Comment by ologbonowiwi** [comment]
I'm thinking about handling this one.

Do you have any guidance or a place where I can start?

**Comment by Josh-Archer** [comment]
Is this just adding to the enum?

**Comment by alishaz-polymath** [comment]
@ologbonowiwi Thank you for looking into this 🙌 
You do need to update the schema and add enum as @Josh-Archer mentioned, but that would only add it at the Database level. 

```
enum WebhookTriggerEvents {
  BOOKING_CREATED
  BOOKING_RESCHEDULED
  BOOKING_CANCELLED
  FORM_SUBMITTED
  MEETING_ENDED
  BOOKING_PAID
  BOOKING_REQUESTED 
  BOOKING_REJECTED 
}
```

The next step would be to update the codebase to identify which hook should fire at what point. This would primarily be in the booking handler. Finally, these would need to be added to the webhook form to store them as webhook triggers.

Please pay close attention to the migration to make sure it doesn't destroy any existing webhooks 🙏 

All the best! 🎉

**Comment by shivamklr** [comment]
I'm excited to help with the project and this issue seems perfect for me. I noticed that no one has claimed it yet. @alishaz-polymath Can I take this up and work on it over the weekend? I'll send you a PR as soon as possible.

**Comment by ologbonowiwi** [comment]
I added the `BOOKING_PAID` webhook. Can you take a look @alishaz-polymath?

Thank you!

**Comment by shivamklr** [comment]
@alishaz-polymath @PeerRich I have a two questions, 
- Do we fire the Booking_Requested Webhook when a **slot** with event type, confirmation required, is created?

- If the above it true, what will be the type of data sent in the webhook?

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath @PeerRich I have a two questions,
> 
>     * Do we fire the Booking_Requested Webhook when a **slot** with event type, confirmation required, is created?

**YES** 🙏 

>     * If the above it true, what will be the type of data sent in the webhook?

Essentially the same payload as confirmation, except with the booking status being PENDING

**Comment by shivamklr** [comment]
@alishaz-polymath I guess we can use sendGenericWebhookPayload for BOOKING_REQUESTED and BOOKING_CONFIRMED webhooks then. 
[https://github.com/calcom/cal.com/blob/94917dbb1ec002f49c9dd2cfed3eeadb323279dd/packages/features/webhooks/lib/sendPayload.ts#L128](url)

**Comment by shivamklr** [comment]
Hi @alishaz-polymath , I noticed that @ologbonowiwi has implemented the BOOKING_PAID EventTrigger in the source code. I have also added the BOOKING_REQUESTED and BOOKING_REJECTED events in the handlers. I have created a PR for this and I would appreciate your feedback on my code. Please let me know if there are any issues that need to be fixed. 
Thank you

**Comment by alishaz-polymath** [comment]
Hey @shivamklr 
Thanks a lot for your PR. I'm currently OOO but I'll review it as soon as I can. I'm also certain one of the team members would probably review it very soon. 🙏
