### ISSUE TITLE
[CAL-1142] CSP Violation[Report Only]: PhoneInput component loads flags from different domain

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7300]
PhoneInput loads flags from a different domain which I am not sure we should trust blindly.
<img width="1757" alt="Screenshot 2023-02-23 at 8 32 21 PM" src="https://user-images.githubusercontent.com/1780212/220944778-9ee9937d-ec34-4c67-bd38-c6b889891ffd.png">

CSP has reported this and I think we should find a way to host these flags ourselves.

<sub>[CAL-1142](https://linear.app/calcom/issue/CAL-1142/csp-violation[report-only]-phoneinput-component-loads-flags-from)</sub>

**Comment by jemiluv8** [comment]
I'd like to work on this.
