### ISSUE TITLE
[CAL-1143] RFC: Feature Flags

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7304]
right now to disable a certain part of the app you need to comment the code out, which causes merge conflicts.

it would be great to have an area inside [console.cal.com](http://console.cal.com) where you can activate and de-activate certain features for your self-hosted platform product

* every link in navigation (i.e. disable "App Store" or "Workflows" link)
* send emails
* ...

what else?

EDIT: by @zomars

## Types of feature flags

Basically we have 4 kinds of feature flags (taken from this [nice article](https://www.martinfowler.com/articles/feature-toggles.html)):

* Release Flags
* Experiment Flags
* Operation Flags
* Permission Flags

### Release flags

These are used to turn certain features on or off. This helps us work on new features without breaking anything that's already working. Product managers can also use Release Flags to hide new features from users until they're ready. Release Flags are temporary and usually only last for a short time, and they're easy to change if needed. Using Release Flags is a way to make sure that new things are added to software without causing problems for users.

### Experiment flags

These are used to test different versions of a feature to see which one works better. We can put different people into different groups and send them down different paths to see what happens. This helps us figure out what people like and what they don't like, and we can use this information to make things better. Experiment Toggles need to stay in place for long enough to get lots of information, but not too long that the information becomes outdated. They're always changing because different people use them all the time.

### Operation Flags

These can turn parts of the system on and off, just in case there's a problem. For example, if we add a new feature to our system and we're not sure if it will work properly, we can use an Ops Toggle to quickly turn it off if we need to. Most Ops Toggles are only used for a short time, but some are kept for a long time, like a "Kill Switch," which helps us turn off less important parts of the system when there's too much work to do. It's important to be able to change these buttons quickly in case something goes wrong, so we don't have to wait too long to fix things.

### Permission Flags

These control which users can access certain features or product experiences. For example, we may have special features that only paying customers can use, or we may have features that are only available to our internal team or a specific group of beta testers. This technique of turning on new features for a set of internal or beta users is called a Champagne Brunch. It's similar to a Canary Release, which exposes new features to a randomly selected group of users. Permissioning Toggles may be used for a long time, especially when managing features that are only accessible to premium users. This is because permissions are user-specific, so the toggle decision needs to be made for each user request.

## Possible usage examples (taking inspiration from happykit)

On client:

```ts
// pages/index.js
import { useFlags } from "@calcom/features/flags/client";

export default function IndexPage(props) {
  const { flags } = useFlags();

  return flags.new-booking === "true"
    ? "You get the new booking"
    : "You get the old booking";
}
```

On server:

```ts
import { GetServerSideProps } from "next";
import { getFlags } from "@calcom/features/flags/server";

export const getServerSideProps = async (
  context
) => {
  const { flags, data } = await getFlags({ context });
  return { props: { flags, data } };
};
```

On middleware:

```ts
import { NextRequest, NextResponse } from "next/server";
import { getEdgeFlags } from "@calcom/features/flags/edge";

export const config = { matcher: "/demo/middleware" };

export async function middleware(request: NextRequest) {
  const { flags, cookie } = await getEdgeFlags({ request });

  const nextUrl = request.nextUrl.clone();
  nextUrl.pathname = `/demo/middleware/${flags?.checkout || "full"}`;
  const response = NextResponse.rewrite(nextUrl);

  if (cookie) response.cookies.set(...cookie.args);

  return response;
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1143](https://linear.app/calcom/issue/CAL-1143/rfc-feature-flags)</sub>

**Comment by rmzNadir** [comment]
Interesting feature!

Have we given any thought to how we'd want to implement such a thing?

I could see [flagsmith ](https://github.com/Flagsmith/flagsmith) being a good option for this use case for example

**Comment by zomars** [comment]
> Interesting feature!
> 
> Have we given any thought to how we'd want to implement such a thing?
> 
> I could see [flagsmith ](https://github.com/Flagsmith/flagsmith) being a good option for this use case for example

Thanks for the suggestion @rmzNadir We're considering if adopting a third party would a good options for us. The thing is, whatever third party we adopt, we also "forcing" all self-hosted users to adopt it a well since it will be deeply ingrained to the core code. We may start with some in-house feature flags and consider migrating to a third-party if it grows too much.

**Comment by roae** [comment]
This would be very interesting to develop.

what if we have a skeleton wrapper, and the Feature Flags services (flagsmith, [edge config](https://vercel.com/docs/concepts/edge-network/edge-config), etc) can be adapted to the wrapper, like next-auth or passport and the default provider is a local json file for self-hosted users.

**Comment by zomars** [comment]
> This would be very interesting to develop.
> 
> 
> 
> what if we have a skeleton wrapper, and the Feature Flags services (flagsmith, [edge config](https://vercel.com/docs/concepts/edge-network/edge-config), etc) can be adapted to the wrapper, like next-auth or passport and the default provider is a local json file for self-hosted users.

Some pseudo code would be helpful to visualize this

**Comment by rmzNadir** [comment]
> This would be very interesting to develop.
> 
> 
> 
> what if we have a skeleton wrapper, and the Feature Flags services (flagsmith, [edge config](https://vercel.com/docs/concepts/edge-network/edge-config), etc) can be adapted to the wrapper, like next-auth or passport and the default provider is a local json file for self-hosted users.

I like this! It's similar to what I was thinking, having some kind of abstraction that allows us to easily offer different adapters for different feature flagging services would bring the best of both worlds between having to build everything from the ground up and having access to the feature rich services that already exist.

One thing I'm not so sure about is the JSON file/building a FF service for the default option as that would require us to also keep track of the flag target cohorts/segments ourselves somewhere and depending on how complex we want to allow them to be that may not be worth it? i.e. too complicated to implement for no real benefits over allowing the user to pick a provider and use the corresponding adapter. This could also be a potential issue between different providers as I would expect them to have varying capabilities on what they allow you to select for a cohort/segment 🤔
