### ISSUE TITLE
[CAL-1144] Custom event type name: Differentiate b/w valid & invalid variable

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7305]
* Differentiate b/w an invalid variable and a valid variable in cases where variable value is decided during booking
* Also show "John Doe" for the preview of the {Scheduler} variable.

![CleanShot 2023-02-23 at 17.05.19@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2f4776ad-3616-48b5-8c23-0a56d3da6a1d/8e6c606f-b526-404c-a6ef-0507f683c5a6)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1144](https://linear.app/calcom/issue/CAL-1144/custom-event-type-name-differentiate-bw-valid-and-invalid-variable)</sub>

**Comment by rksingh2001** [comment]
Can I take up this issue?
