### ISSUE TITLE
[CAL-1146] Date overrides bug

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7307]
[c1248a7b-cbe0-4f13-9bcd-a0a1e3ddb9fe](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/56e77d0a-640e-45fa-8228-045228a6f7cb/c1248a7b-cbe0-4f13-9bcd-a0a1e3ddb9fe)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1146](https://linear.app/calcom/issue/CAL-1146/date-overrides-bug)</sub>

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2023-02-24 at 12 27 19 AM" src="https://user-images.githubusercontent.com/53316345/221003906-05444376-9fc8-46b7-b774-df38e29830ce.png">

@Jaibles not able to reproduce it

**Comment by Udit-takkar** [comment]
tried locally and app.cal.com

**Comment by Jaibles** [comment]
@udit try first adding the override as an available time, then edit it to be unavailable entire day. That might be what I did.

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/221021984-e25f3f66-c5d2-47cd-893c-4ec003c1c233.mov

still not able to reproduce

**Comment by domjour** [comment]
I experience the same bug for certain days (s. below).
![Bildschirm­foto 2023-02-24 um 08 47 24](https://user-images.githubusercontent.com/126060707/221121780-c34eac30-e7a6-4729-9d1d-cb72a8ffd00d.png)

**Comment by Udit-takkar** [comment]
@domjour what time zone have you selected ?

**Comment by domjour** [comment]
Time zone is Europe/Amsterdam

**Comment by Jaibles** [comment]
https://www.loom.com/share/5126452bd11b4dd7b1c0a6807410f817
