### ISSUE TITLE
[CAL-1147] Insights upgrade screen

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7309]
[Insights - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=23641%3A169934&t=NDOZahMULeleh5qW-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1147](https://linear.app/calcom/issue/CAL-1147/insights-upgrade-screen)</sub>

**Comment by PeerRich** [comment]
added to the PR
