### ISSUE TITLE
[CAL-1148] ability to add more email addresses to a profile

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7314]
below email input there should be a button to add another email address:

![CleanShot 2023-02-23 at 23 00 03@2x](https://user-images.githubusercontent.com/8019099/221040236-653a07b5-970f-4b10-83a1-e4609f1a4a03.jpg)

then in event-types add another dropdown:

![CleanShot 2023-02-23 at 23 01 59@2x](https://user-images.githubusercontent.com/8019099/221040604-69331b64-d5fc-4118-b704-4ecfd1d28505.jpg)

<sub>[CAL-1148](https://linear.app/calcom/issue/CAL-1148/ability-to-add-more-email-addresses-to-a-profile)</sub>

**Comment by draqist** [comment]
Do i have to design the UI or develop it and it'd be reviewed?

**Comment by draqist** [comment]
Do i have to design the UI or develop it and it'd be reviewed?

**Comment by PeerRich** [comment]
@Jaibles will need to look into this, not sure about the priority tho

**Comment by priddhesh** [comment]
@PeerRich Sir, I can work on this issue.Can you please assign me this task?

**Comment by Jaibles** [comment]
Designs for that are here: https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/3.-Cal---New-Features?type=design&node-id=4549%3A409085&t=dOS7Zonn0jrfqDys-1

**Comment by sayande2002** [comment]
can work on this issue? assign it to me.

**Comment by alceil** [comment]
Can I take a dab at this? @PeerRich

**Comment by surajgjadhav** [comment]
Hi @PeerRich ,
I have analyzed code base of profile section and understood basics of that flow.
can I take this issue ?

**Comment by surajgjadhav** [comment]
Hi @Jaibles ,
can we use this design for initial state of personal info where user has only one email ID:
(Sry for that space between add email and email box, I have edited the existing design using sketch 😅  )
![image](https://github.com/calcom/cal.com/assets/31582237/cdb6d4f5-e813-4e36-93fa-7878a3ae2bfc)
instead of keeping it as it is:
![image](https://github.com/calcom/cal.com/assets/31582237/11aeed95-e915-4d1a-a4e9-fd291f8e8a98)

So, that the uniformity will also be maintained and it will be easy to under for user

Please Check
Thanks

**Comment by mateeyow** [comment]
Hi, I just wanted to check if we have specs for the input fields:
<img width="672" alt="image" src="https://github.com/calcom/cal.com/assets/6420838/feb834bf-b565-466d-9c9a-a6e0375c5800">
We don't have anything with the same style as what we have on Figma.

**Comment by SomayChauhan** [comment]
hi @keithwillcode @PeerRich 
i was workin on this but i got blocked by some edge cases that needs some clarification
* this additional email is only to receive email notifications right, we can not log in with that email ?
* when we send an email to confim that email, lets say the user is not logged in when he opens that link, now he enters his primary email to log into cal.com account and then we verify that token using some logic, according to me that a bit confusing which email to enter, instead we should send a verification code and prompt the user to enter that code (like when we create a organization)
* what if i make an email my primary but that email was alredy registerd with some other cal.com account and its primary account

**Comment by asadath1395** [comment]
@keithwillcode This is implemented in this PR https://github.com/calcom/cal.com/pull/13678 and i think we can close this issue.

cc @PeerRich
