### ISSUE TITLE
[CAL-1145] Sailfish OS browser displaying the wrong date, day of the week and start of the week

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7325]
Every other browser displays it correctly. Notes from a customer:

*Problem occurs on my native Sailfish OS browser, currently based on Gecko ESR 78 engine. I understand this probably falls beyond your testing matrix, but as it functions normally everywhere else, there's still probably some edge case bug in your code.*

*One interesting symptom is that my native Browser displays week as first day Sunday. I didn't see a week start day configuration option anywhere, so it's probably auto-detected somehow, and getting it wrong here.*

Created via Threads. See full discussion: [https://threads.com/34451020389](https://threads.com/34451020389)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1145](https://linear.app/calcom/issue/CAL-1145/sailfish-os-browser-displaying-the-wrong-date-day-of-the-week-and)</sub>

**Comment by PeerRich** [comment]
what is sailfish OS 🤣
