### ISSUE TITLE
[CAL-1149] Duplicate google event

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7329]
Booked event is created on both the default calendar and the calendar/email that is associated with the [cal.com](http://cal.com) account under the condition that both of those calendars are within the single connection

Created via Threads. See full discussion: [https://threads.com/34451450211](https://threads.com/34451450211)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1149](https://linear.app/calcom/issue/CAL-1149/duplicate-google-event)</sub>

**Comment by PeerRich** [comment]
seems to be still happening. maybe its due to another change

**Comment by PeerRich** [comment]
this may be fixed with 2.7.3, not sure

**Comment by Udit-takkar** [comment]
@leog @PeerRich is this still happening ?
