### ISSUE TITLE
[CAL-1151] mobile: set your availability

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7351]
figma: [https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&mode=design](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&mode=design)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1151](https://linear.app/calcom/issue/CAL-1151/mobile-set-your-availability)</sub>

**Comment by esau-morais** [comment]
The real question is if the suggested change would fix the design inconsistency in mobile devices. I might get to design something first and return it soon here if it sounds right.

**Comment by PeerRich** [comment]
yeah lets try and make the figma work

@esau-morais assigned oyu

**Comment by esau-morais** [comment]
Do you think it's better to have a single button to copy the first avaibility time to all the rest?

![image](https://user-images.githubusercontent.com/55207584/221379314-28ddb01c-bd61-4af3-9202-656258e0f532.png)

**Comment by farhan787** [comment]
![Screenshot 2023-07-04 at 3 10 51 PM](https://github.com/calcom/cal.com/assets/38656082/4109da4d-1453-43de-9531-8a1a3780eab3)

Hi @PeerRich, I've made the changes except for the availability settings UI. `Availability Settings` is supposed to be a new next.js page or a sliding sidebar (ambiguous in the Figma design). If it's a sidebar, is it supposed to take ~80% of the width or full width of the page?
