### ISSUE TITLE
Immediate redirection to specific URL after booking

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7367]
Can you make it possible that also people with the Free or Team Plan have the option to jump immediately to the redirect URL, so without delay because of the success page?

**Comment by PeerRich** [comment]
its a security concern to immediately link to certain things

**Comment by PeerRich** [comment]
abusers could send you to a phishing link

**Comment by RainerZufall9393** [comment]
Oh okay, that make sense

**Comment by PeerRich** [comment]
you can disable the delay on a self-hosted plan
