### ISSUE TITLE
Fully customizable success page and email on successful booking, rescheduling or cancellation of appointment

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7368]
Can you include a way to make the success page, as well as the corresponding emails, completely customizable? I'd like to be able to do it myself, even have my customers have a consistent experience as far as my entire funnel (which means scheduling as well) is concerned.

**Comment by milospuac** [comment]
You will be able to select the email where the confirmation is being sent https://github.com/calcom/cal.com/issues/7314 

We do have workflows that you can send along with each booking, would that be a good workaround until we implement something that would be satisfactory?

**Comment by PeerRich** [comment]
i would recommend the redirect feature for this. with workflows you can send emails and you can disable the "default" confirmation too
