### ISSUE TITLE
Scroll position bug

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7369]
The scroll position in the scheduling page keeps jumping up as soon as I select a date and then scroll to the corresponding time.

Tested on: iPhone, Safari
Integration type: Inline code in a popup box

https://user-images.githubusercontent.com/126205884/221206655-33b40814-0b5f-439b-8597-a57bf5069c34.mp4

**Comment by emrysal** [comment]
A few minutes ago we released v2.6.5 - this includes https://github.com/calcom/cal.com/pull/7282 - could you have a look whether this is still happening? The screenshot was taken 5 minutes before the release.

**Comment by RainerZufall9393** [comment]
Oh well perfect! Now it works without these jumps. Thanks!

**Comment by emrysal** [comment]
Closing, thanks for verifying this as fixed @RainerZufall9393 🙏 

P.s. @G3root 👍
