### ISSUE TITLE
Set default country for phone number

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7373]
Is it possible that you include the option to set the default country for the phone number beforehand? For example, that Germany (+49) is always selected by default? 90% of my customers come from Germany and if this is not preset, it quickly comes to confusion.

<img width="826" alt="Bildschirm­foto 2023-02-24 um 15 54 00" src="https://user-images.githubusercontent.com/126205884/221209599-7218988a-319d-49f5-8b46-8f7e223d2f8f.png">

**Comment by RainerZufall9393** [comment]
An alternative would be the automatic detection of the location via the IP address. This way, the country in which you are located can be automatically pre-filled.

This is not always suitable, but the most important thing is that it is easier to recognize that you have to enter your country code there.

**Comment by PeerRich** [comment]
i believe there is a PR for this in review, no? @Udit-takkar

**Comment by Udit-takkar** [comment]
@PeerRich yeah it's working for cal.com but for self hosters the things alex and zomars suggested is not working https://github.com/calcom/cal.com/pull/6880#issuecomment-1442394401 so we will have to think of some other way to make it work for self hosters.
