### ISSUE TITLE
URL of the routing forms customizable

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7374]
Can you make the URL of the routing forms customizable? Currently they are very long and not memorable. A URL format like the normal events would be great.

Currently:
https://cal.com/forms/1999f474-0ab8-4b89-9b10-0fb6979 …

In the future:
https://cal.com/username/custom-domain-ending

**Comment by PeerRich** [comment]
we probably wont work on this, its very low priority unless more people are asking for this.

most forms are recommended to be embedded anyways
