### ISSUE TITLE
Integration of a customer database and appointment booking outside normal appointment times

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7375]
Can you integrate the function of a customer database, as Acuity Scheduling already does?

I always found it really handy to see a clear list of all the people who have ever booked an appointment with me. There I could also see which appointments they had booked and whether they had taken place or been rescheduled.

But what I liked best about it was that I could also schedule or reschedule appointments for these people directly, even OUTSIDE of my normal call times. That way, I could give them appointments that fit better into their schedule.

I've never seen this done anywhere other than Acuity, and it's the only big feature I really miss.

<img width="1440" alt="SCR-20230224-mps-2" src="https://user-images.githubusercontent.com/126205884/221218688-f9496af0-5d33-45e8-a214-45f50d93eff6.png">

**Comment by PeerRich** [comment]
we're working on an analytics product called "Insights" which will have a lot more reporting tools, yes
