### ISSUE TITLE
[CAL-1152] Back button always redirecting to /event-types

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#7379]
### Issue Summary

check this video
https://github.com/calcom/cal.com/pull/7377#pullrequestreview-1314077558

<sub>[CAL-1152](https://linear.app/calcom/issue/CAL-1152/back-button-redirecting-to-event-types)</sub>

**Comment by esau-morais** [comment]
May I work on this issue?

Quick discussion: Always redirect to last route, unless it is the first accessed one and default to `/event-types`

**Comment by Udit-takkar** [comment]
@esau-morais yeah it should redirect to last route
