### ISSUE TITLE
Duplicated Issues

### ISSUE THREAD

**Issue by esau-morais** [calcom/cal.com#7397]
### Issue Summary

Is this expected?

![image](https://user-images.githubusercontent.com/55207584/221278975-b7733e50-df81-4756-8a1e-0850db9e8ad7.png)

### Steps to Reproduce

Go to issues page
Filter by `todo` label

https://github.com/calcom/cal.com/blob/main/.github/workflows/todo-to-issue.yml

**Comment by PeerRich** [comment]
yikes. @zomars

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/pull/7401
