### ISSUE TITLE
[CAL-1154] You might want https://github.com/tatethurston/nextjs-routes

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7402]
You might want https://github.com/tatethurston/nextjs-routes

_Originally posted by @KATT in https://github.com/calcom/cal.com/issues/7377#issuecomment-1444718904_
            

<sub>[CAL-1154](https://linear.app/calcom/issue/CAL-1154/you-might-want-httpsgithubcomtatethurstonnextjs-routes)</sub>

**Comment by esau-morais** [comment]
Is it actually necessary, once type-safe routes will be released soon?

**Comment by esau-morais** [comment]
May I work on this issue?

**Comment by zomars** [comment]
> Is it actually necessary, once statically typed links have been released on Next.js 13.2? Maybe this could be added to the roadmap

AFAIK Statically type routes will only work using the `app` and there's still quite a long way for us to adopt it.

> May I work on this issue?

Sure go for it! 🙏🏽

**Comment by PeerRich** [comment]
@esau-morais still interested?

**Comment by esau-morais** [comment]
> @esau-morais still interested?

Unfortunately I've been out of time so I get to focus on job and study, I'm sorry :(

**Comment by zomars** [comment]
Closing as we're moving to appDir soon enough.
