### ISSUE TITLE
[CAL-1155] Auto docker releases

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7407]
we add a "release" action in the docker repo with the release tag as an input for a workflow_dispatch trigger. That action then checks out the submodule based on the release tag input, then creates and tags the release. (that would then trigger the existing build workflow)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1155](https://linear.app/calcom/issue/CAL-1155/auto-docker-releases)</sub>

**Comment by PeerRich** [comment]
@krumware wanna work on this?

**Comment by krumware** [comment]
I can pick it back up 👍

**Comment by keithwillcode** [comment]
This is done
