### ISSUE TITLE
[CAL-1156] make /availability skeleton look more like content

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7410]
make ![image](https://user-images.githubusercontent.com/8019099/221381486-1d679148-7f35-4d55-b827-1f59e4faaa03.png)

look more like

![image](https://user-images.githubusercontent.com/8019099/221381488-953e933c-b1a7-4ab3-8d6c-39307754ffcc.png)

<sub>[CAL-1156](https://linear.app/calcom/issue/CAL-1156/make-availability-skeleton-look-more-like-content)</sub>

**Comment by rksingh2001** [comment]
Can I take up this issue?
