### ISSUE TITLE
Routing form UI update

### ISSUE THREAD

**Issue by gitstart-calcom** [calcom/cal.com#7413]
Current design

<img width="1437" alt="Screenshot 2023-02-26 at 5 17 55 PM" src="https://user-images.githubusercontent.com/121884634/221407972-08909de7-6abb-4317-a921-b34b6ca5f46b.png">

Should be

<img width="893" alt="Screenshot 2023-02-26 at 5 17 06 PM" src="https://user-images.githubusercontent.com/121884634/221407912-e7cea08f-3863-44e6-a0ff-9db190332b06.png">

https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A101718

**Comment by gitstart-calcom** [comment]
Hi @Jaibles, do you think this checkmark would be necessary?
When an item is clicked it either opens a modal immediately or opens a page immediately. There won't be time to show the checkmark first

![Untitled design (7)](https://user-images.githubusercontent.com/121884634/221532145-6057ed11-f3ca-43cf-a133-c44924be2292.png)

**Comment by Jaibles** [comment]
@gitstart-calcom apologies, no idea why that checkmark is in there - should just be like this:
<img width="534" alt="CleanShot 2023-02-27 at 12 54 05@2x" src="https://user-images.githubusercontent.com/4536123/221569024-8a624bb6-84e3-4058-9712-31565055ff20.png">

**Comment by gitstart-calcom** [comment]
Hi @Jaibles we noticed that the `Embed` button is hidden for medium and smaller screen sizes.
https://www.loom.com/share/d3dd618b448f481d9623c958ddf29608

Do we want the same behavior when the `Embed` is moved to `ButtonGroup`?
https://www.loom.com/share/601ce9e356b54f829adcd0651410d595

**Comment by Jaibles** [comment]
yes please. The assumption is it's unlikely people will need to embed on mobile.
