### ISSUE TITLE
Workflows with the trigger "m/h/d/ before event" do not work

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7418]
I have the problem that any workflows with the trigger "m/h/d/ before event" do not work for me. No mails or SMS are sent at the corresponding time.

This is a huge problem in my case, as I rely on this exact workflow in my collaboration with my prospects and clients to send appointment reminders before events. So I can only really use Cal.com if this gets fixed in a timely manner.

By the way: The workflows, where the mails or SMS are sent directly after the booking, work without any problems.

Workflows with the triggers "cancellation", "rescheduling" or "after completion of the event" were not tested by me.

**Comment by CarinaWolli** [comment]
Hi @RainerZufall9393, I tested our "before event starts" trigger and everything works fine for me. One thing to mention here, if you were trying to test the trigger yourself: Reminders can only be scheduled at least 60 minutes in advance. 

So if you want to test a workflow that triggers 10 minutes before an event starts, the earliest you can make your test booking is `time now + 70 minutes`

Could that have been your issue? Or are you experiencing something else?

**Comment by RainerZufall9393** [comment]
Hey @CarinaWolli, that's great that you say that! Have now tried it again, with more than 60 minutes in between and then it worked. Thank you so much! :)

**Comment by CarinaWolli** [comment]
Awesome, glad I could help :)
