### ISSUE TITLE
[CAL-1166] Dropdown menu for forms

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7432]
A dropdown menu for the forms (similar to Calendly) would be great.

<img width="436" alt="Bildschirm­foto 2023-02-28 um 04 46 08" src="https://user-images.githubusercontent.com/126205884/221748939-6575446b-4b68-4f1c-b36d-5792d0017476.png">

<sub>[CAL-1166](https://linear.app/calcom/issue/CAL-1166/dropdown-menu-for-forms)</sub>

**Comment by Jaibles** [comment]
@RainerZufall9393 Can you provide a little more info here? What exactly is this drop-down for? It's a little hard to work out what the context of this drop-down is right now :)

**Comment by RainerZufall9393** [comment]
This is about the appointment booking form, so where the interested party signs up.

I would like to put choices there, similar to the radio buttons.

The problem with the radio buttons is that they quickly become too cluttered if you use a lot of them (since they can't be collapsed).

In my case, I would like to specify the age, the profession and the desired weight loss, between which can then be selected.

**Comment by Jaibles** [comment]
Ah ok perfect thank you 🙏 definitely something we can and will do!

**Comment by RainerZufall9393** [comment]
Wuhu! Nice to hear :)

**Comment by Jaibles** [comment]
This has been shipped.
<img width="890" alt="CleanShot 2023-05-05 at 00 03 38@2x" src="https://user-images.githubusercontent.com/4536123/236348262-9aed3f4d-c061-47b0-9c60-ad8596ff11b8.png">



https://user-images.githubusercontent.com/4536123/236348108-8de7c05b-1586-4892-a1a8-a8fc99bc2009.mp4
