### ISSUE TITLE
Add CalLink / team slug / user slug to event-types api endpoint

### ISSUE THREAD

**Issue by michelson** [calcom/cal.com#7434]
### Is your proposal related to a problem?

1. In order to build cal links from an event types list provided by `event-types` API endpoint, one has to do a second potential API call to get the team slug name
2. When displaying an event types list from an account with many users organizations there is no way to retrieve event owner name or team names from that list.

### Describe the solution you'd like
as we discussed with @hariombalhara on the slack channel, Ideally, the API endpoint should have the calLink itself(in addition to just slug).

**Comment by hariombalhara** [comment]
@G3root Maybe you want to pick it. This one should be quick

**Comment by michelson** [comment]
It would be nice if the `event-type` also included the name of the owner of the event, along with the calLink.

**Comment by hariombalhara** [comment]
I am not sure if the owner name makes sense there. `calLink` makes sense because it's the direct property of event. If we send the owner id that should be enough. User details can be queried using owner id.

**Comment by michelson** [comment]
Hi @hariombalhara, thanks for taking the time to take this over. 
Having the user name in the list will be very useful; for instance, when you display the list of available events in the UI, you would expect an extra label that could differentiate the event types without doing extra queries. Our use case is to let users pick one of the account's events and send it over through a chat. So when the user gets the list, they currently see the following:

![image](https://user-images.githubusercontent.com/11976/222897561-0ac4adf3-a3bb-43d7-98ec-0b0d0c2a1159.png)

As you can see, without an owner's name, there is no way for the client to know what event belongs to whom. 
In theory, I would need to do an extra API call for each item on the list to get the name and then merge that into the result. That could take a lot of time to process, and the experience would not be optimal.
