### ISSUE TITLE
Incorrect slots shown on 1st day of the month

### ISSUE THREAD

**Issue by vik-y** [calcom/cal.com#7447]
### Issue Summary
Incorrect availability on the first day of every month. 

I have recurring time blocks set on my calendar. For some reason for every 1st day of the month cal.com shows slots which are actually not available on my calendar. 

( I am checking for timezone Asia/Kolkata) 

For instance  - check this: 
https://cal.com/vik-y/60min?date=2023-03-01&month=2023-03 
-> The slots shown here are actually booked on my calendar. And if you try to book one - the booking will fail. It's showing all slots as per my availability - even though those slots are not free on my calendar.

If you check for 2nd March 
https://cal.com/vik-y/60min?date=2023-03-02 -> It's working fine as expected

Check for 1st April - Same problem - I have my calendar blocks set but it's still showing all slots as available.
https://cal.com/vik-y/60min?date=2023-04-01&month=2023-04

Same for May 1st
https://cal.com/vik-y/60min?date=2023-05-01&month=2023-05

Seems like we are hitting an edge case. Another weird issue is that - for a fraction of a second it does show correct slots - but then probably it makes another API call and the data changes.

I've been able to narrow down the API calls which are returning different data 

(Incorrect Response)
https://cal.com/api/trpc/viewer.public.slots.getSchedule?
input=%7B%22json%22%3A%7B%22
eventTypeId%22%3A206142%2C%22
eventTypeSlug%22%3A%2260min%22%2C%22
usernameList%22%3A%5B%22vik-y%22%5D%2C%22
startTime%22%3A%222023-02-28T18%3A30%3A00.000Z%22%2C%22
endTime%22%3A%222023-03-01T18%3A29%3A59.999Z%22%2C%22timeZone%22%3A%22Asia%2FCalcutta%22%2C%22duration%22%3A%2259%22%7D%7D

(Correct Response) 
https://cal.com/api/trpc/viewer.public.slots.getSchedule?input=%7B%22json%22%3A%7B%22
eventTypeId%22%3A206142%2C%22
eventTypeSlug%22%3A%2260min%22%2C%22
usernameList%22%3A%5B%22vik-y%22%5D%2C%22
startTime%22%3A%222023-02-26T18%3A30%3A00.000Z%22%2C%22
endTime%22%3A%222023-03-31T18%3A29%3A59.999Z%22%2C%22
timeZone%22%3A%22Asia%2FCalcutta%22%2C%22duration%22%3A%2259%22%7D%7D

### Steps to Reproduce

I have shared all the API calls above

### Technical details
I am attaching the har file of the network calls extracted from Chrome in case if that helps with the investigation: https://drive.google.com/file/d/1ys9nJJr1W8qLvkSpeDhFiMHvTsJWuxPO/view?usp=share_link

**Comment by RainerZufall9393** [comment]
I can confirm. For me, times are also displayed on the 01st of a month, although they are blocked in my calendar.

If you want to book an appointment there, it is displayed "Appointment could not be booked. No available users found.

But does not seem to be dependent on the time zone. I am from Germany and it is the same here.

**Comment by zomars** [comment]
will be fixed by #7462

**Comment by Udit-takkar** [comment]
closing this as PR has been merged https://github.com/calcom/cal.com/pull/7462
