### ISSUE TITLE
[CAL-1168] Collective Event Displaying Not Available Time Slot

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#7460]
This link is displaying a time slot at 6p on Thursday as available, but it’s not available 

[https://cal.com/team/mirage/canvas-onboarding](https://cal.com/team/mirage/canvas-onboarding)

Customer has attempted to disconnect and reconnect the calendar

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1168](https://linear.app/calcom/issue/CAL-1168/collective-event-displaying-not-available-time-slot)</sub>

**Comment by emrysal** [comment]
Need a little bit more info, what timeZone are you in, BTW we 100% sure it's not marked as free?

**Comment by shirazdole** [comment]
They're based in California so most likely PST and I asked them to double check and they told me yes it's marked busy for both 🙏🏽

**Comment by PeerRich** [comment]
closing due to stale
