### ISSUE TITLE
Settings: Success toast displayed in previously selected language

### ISSUE THREAD

**Issue by gitstart-calcom** [calcom/cal.com#7464]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The success toast displayed when the language is changed is still shown in the previously selected language

### Steps to Reproduce
https://user-images.githubusercontent.com/121884634/222378618-b63adfae-d031-41ba-929b-cd707afe930a.mov

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by PeerRich** [comment]
i think that is fine for now. could be better but very low priority
