### ISSUE TITLE
[CAL-1170] Some users are not able to download recording

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#7488]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

<img width="696" alt="Screenshot 2023-03-03 at 2 32 23 AM" src="https://user-images.githubusercontent.com/53316345/222552049-681eb0be-17a7-4dfd-a5b2-fe2484953a78.png">

<sub>[CAL-1170](https://linear.app/calcom/issue/CAL-1170/some-users-are-not-able-to-download-recording)</sub>

**Comment by PeerRich** [comment]
user: alexs@uniform.dev
