### ISSUE TITLE
[CAL-1174] Booking Pages don't honour system theme if theme is already persisted in localStorage.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7497]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b3ab49cb-0e48-4480-9d90-4063525a612a/408b8b60-36cf-450b-97e1-9cead5480349)

We used forcedTheme option to force light theme in the app(we don't support dark theme there). But on Booking Pages as well,

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/09ceefb7-6c66-4cbe-a0a6-c8250fd51028/d040faa2-194f-4764-94c1-d0a0992f3ba1)

Steps to replicate:

* Switch to Dark mode
* Login to the [cal.com](http://cal.com) app and open your preview link
* Make sure that profile has System theme chosen
* You would land on something like [cal.com/YOUR_CAL_USERNAME](http://cal.com/YOUR_CAL_USERNAME). Notice that it would be using dark theme.
* Change it to [app.cal.com/YOUR_CAL_USERNAME](http://app.cal.com/YOUR_CAL_USERNAME). Notice that it isn't in dark theme. The reason being now booking page is sharing the same origin as app and localStorage value is being read.

Note: This should normally not be a problem as Cal link is [cal.com](http://cal.com) only. But in self hosting scenarios users might be using same domain for Booking Pages.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1174](https://linear.app/calcom/issue/CAL-1174/booking-pages-dont-honour-system-theme-if-theme-is-already-persisted)</sub>

**Comment by PeerRich** [comment]
@hariombalhara has this been fixed with the new booking page?
