### ISSUE TITLE
No * for mandatory fields like name, email and phone

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7498]
No red stars (*) are displayed for required fields such as name, email, and phone.

<img width="368" alt="Bildschirm­foto 2023-03-03 um 16 08 47" src="https://user-images.githubusercontent.com/126205884/222756105-87d17767-4209-423c-836d-4c1c51c43a90.png">

**Comment by CarinaWolli** [comment]
@hariombalhara should be fixed with #6560, right?

**Comment by hariombalhara** [comment]
Yeah it should be

**Comment by CarinaWolli** [comment]
Closing because already fixed in main
