### ISSUE TITLE
Appointments are mistakenly entered in several calendars

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7499]
Appointments are entered in my private (blue in the screenshot) and business (red in the screenshot) calendar, although it is set that they should all end up in the business calendar.

The private calendar is only additionally specified for the synchronization of the available appointments.

I use Google Calendar.

<img width="1120" alt="SCR-20230303-ojox-2" src="https://user-images.githubusercontent.com/126205884/222758152-56cb1b46-71cc-41d8-8a20-19d10c5eaccb.png">

**Comment by Udit-takkar** [comment]
i think i fixed this bug. let me check

**Comment by Udit-takkar** [comment]
the fix has been merged https://github.com/calcom/cal.com/pull/7406 and will be deployed soon
