### ISSUE TITLE
[CAL-1178] Difficult visibility of the choices (Routing forms)

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7501]
The individual selection options in the routing forms are difficult to see due to the background color. An optimization would be great.

<img width="963" alt="Bildschirm­foto 2023-03-03 um 18 56 32" src="https://user-images.githubusercontent.com/126205884/222793928-a23881b5-a3b6-4afd-8cb7-271d546e5d6c.png">

<sub>[CAL-1178](https://linear.app/calcom/issue/CAL-1178/difficult-visibility-of-the-choices-routing-forms)</sub>

**Comment by Udit-takkar** [comment]
@RainerZufall9393  can you confirm once if your using these brand colors ? ( you can check them at https://app.cal.com/settings/my-account/appearance)

<img width="841" alt="Screenshot 2023-03-03 at 11 42 43 PM" src="https://user-images.githubusercontent.com/53316345/222796149-401f0983-be3e-4c60-a017-67e9a99ffb68.png">

**Comment by Udit-takkar** [comment]
try using the ones i send. that should fix the issue

**Comment by RainerZufall9393** [comment]
Yes, that works. Then the display problems are gone. However, I then no longer have my branding color in the booking forms. @Udit-takkar

**Comment by Udit-takkar** [comment]
@RainerZufall9393 ok i'll try fix this to make it work for other branding colors also
