### ISSUE TITLE
[CAL-2791] Assign colors to events to make them easier to find in the booking overview

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7507]
Would be cool to be able to assign different colors to individual events so that they can be better visually assigned in the overview of booked events (see Calendly).

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/000e0d95-9b98-443c-9d33-87c7d4101980/4694ba1c-de8c-4748-b421-6641d1a16d4c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8wMDBlMGQ5NS05Yjk4LTQ0M2MtOWQzMy04N2M3ZDQxMDE5ODAvNDY5NGJhMWMtZGU4Yy00NzQ4LWI0MjEtNjY0MWQxYTE2ZDRjIiwiaWF0IjoxNzAyMzY2OTU5LCJleHAiOjE3MDI0NTMzNTl9.WjEFKyXo27Snj37ICFOFTSn6y0JCe_0yzjuC36egbJ0)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/81a13c79-c9e7-4a09-b5f9-ecffe1468f9e/6dd6ca57-16cd-465c-a735-0a605fb606e8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84MWExM2M3OS1jOWU3LTRhMDktYjVmOS1lY2ZmZTE0NjhmOWUvNmRkNmNhNTctMTZjZC00NjVjLWE3MzUtMGE2MDVmYjYwNmU4IiwiaWF0IjoxNzAyMzY2OTU5LCJleHAiOjE3MDI0NTMzNTl9.hbLnVw1uGw4egIvMUmS_qG8zClqkUrNKqCwJwBzMutM)

By the way: Categories for the event types would also be great. This way you can bring more order into it, if you offer many different types of events, like me.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2791](https://linear.app/calcom/issue/CAL-2791/assign-colors-to-events-to-make-them-easier-to-find-in-the-booking)</sub>

**Comment by PeerRich** [comment]
@Jaibles was thinking about this a while ago. will look into it!

**Comment by RainerZufall9393** [comment]
Hey, wanted to ask if there is any news on this yet? @PeerRich @Jaibles

**Comment by ciaranha** [comment]
[Designs are ready here](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=4456%3A265837&mode=design&t=M4l7cxrNJ4YS8JXt-1)
