### ISSUE TITLE
This is Fake OpenSource Project

### ISSUE THREAD

**Issue by OpenSourceLawyer** [calcom/cal.com#7510]
I saw this[ Reddit post](https://www.reddit.com/r/selfhosted/comments/11e3fh9/calcom_selfhostable_opensource_scheduling_high/)

You guys are using an AGPL license and shipping property software, which is a shame.

**Comment by Udit-takkar** [comment]
@OpenSourceLawyer  https://www.reddit.com/r/selfhosted/comments/11e3fh9/comment/javblop/?context=3
