### ISSUE TITLE
[CAL-1180] RFC: Multi-Tenency and why we need it 

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#7512]
Multitenancy is a a way out app can serve multiple different users or organisations whose data is kept private from the other users of the system. One approach would be to have a unique DB per user. 
XXX gets their own unique instance. etc etc  (Not what we should do and defo not cost effective is most cases of needing a org)

Right now the UI/UX is awful for organisations - having to create loads of teams and managing their whole UX around being on this one "Cal instance" 
Linear.app does this in a super nice way of having this organisation structure for your entire app.  
![image](https://user-images.githubusercontent.com/55134778/222875375-5e44e6b8-4ed1-4be3-894c-037f2d6c30ec.png)

Now this would require ALOT of refactoring and this is why its not been done yet or even fully talked about until @zomars made a post about it in threads the other day. 
This would require us to have a full revamp in how we handle our db and its not at all a light task (might not be as bad as we are thinking if we migrate everything to a new organisation called Calcom)

![image](https://user-images.githubusercontent.com/55134778/222875411-fdb27d59-138a-4903-b73b-001a12a3fd9b.png)

However, with this approach it would allow an organisation to have their own event types (separated by orgId) and also it would be possible for an organisation to have teams within itself. 
Inspiration from this came from exploring our invite flow and looking at the feature designs we have for this organisation structure
REF: https://blog.bullettrain.co/teams-should-be-an-mvp-feature/﻿

<sub>[CAL-1180](https://linear.app/calcom/issue/CAL-1180/rfc-multi-tenency-and-why-we-need-it)</sub>

**Comment by leog** [comment]
As @emrysal was saying in Threads, we got to talk about this when discussing alternative solutions for managed event types. I suggested we should go the parent/child way to support organizations, as I’m shaping managed event types by admins. I can give the concept a try once I finish children/parent event types, and auth.cal.com which I also have in my plate.

**Comment by PeerRich** [comment]
lets merge this with https://github.com/calcom/cal.com/issues/7142
