### ISSUE TITLE
[CAL-1181] fix scroll bar

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7515]
[https://github.com/calcom/cal.com/pull/7295#pullrequestreview-1324563922](https://github.com/calcom/cal.com/pull/7295#pullrequestreview-1324563922)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1181](https://linear.app/calcom/issue/CAL-1181/fix-scroll-bar)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar cant reproduce, can you try and fix it?

**Comment by Udit-takkar** [comment]
<img width="256" alt="Screenshot 2023-08-18 at 3 05 30 PM" src="https://github.com/calcom/cal.com/assets/53316345/cfbd6713-78ca-48cc-894d-81b74a637e8b">

fixed already
