### ISSUE TITLE
Apple calendar not connecting or restoring.

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#7517]
### Issue Summary

Adding Apple Calendar presents:

![image](https://user-images.githubusercontent.com/53020786/222930532-3040d825-a361-4100-bab2-b101e43c5ae1.png)

Reloading the page now shows:

![image](https://user-images.githubusercontent.com/53020786/222930541-5b34beb2-cce1-4075-b0fd-13cddf5643a6.png)

After some investigation it occured around the time of commit: #7428 and #6701 
b9064b1f7225d327c6ea74b6a749bc63be304e38
2a98ca4b9198e3dc64c6df9c61f679f382a01c47

### Steps to Reproduce

1. New instance
2. Add an apple calendar
3. Doesn't work

If I go back to using an older commit, one such as:
641301afabe77868ff54831dfd09943604a6f54b

Then it all works fine again, using the same info from the DB

### Technical details

- Latest Chrome
- Node.js 16

**Comment by Hybes** [comment]
I believe that you need to add the calendar before updating past the broken commit - so that it's fetching the data from before the updates are in place, but I may be wrong.

**Comment by PeerRich** [comment]
@alishaz-polymath can you look into this?

**Comment by alishaz-polymath** [comment]
Upon further investigation, I can confirm this was introduced in #6701 and that this breaks CalDAV entirely as well. Debugging this now 🙏
