### ISSUE TITLE
Allow Team Admins to set Auto-Recording for Teammates

### ISSUE THREAD

**Issue by agreea** [calcom/cal.com#7519]
### Is your proposal related to a problem?

We're running a platform that connects startups with designers. We currently use Calendly + Zoom to power our scheduling + conferencing. One of the Zoom settings we use is auto-recording every Zoom meeting hosted by our designers. Currently Cal.com doesn't enable Team admins to set teammates' meetings to auto-record.

### Describe the solution you'd like

As a team admin, I'd like to be able to enable auto-recording for my teammates in the Cal video app. Ideally this would be something that could be admin controlled so we could ensure consistent configuration across all of our teammates.

### Describe alternatives you've considered

Currently using Zoom, but with Cal Video's release - this feature is the only thing keeping us on Zoom.

### Additional context

There's opportunity here for some powerful workflows down the road, like piping recordings for transcription, summarization, etc.

**Comment by PeerRich** [comment]
we are using daily.co to power cal video and I don't think they have a feature to "auto record" yet.

will ask them

**Comment by PeerRich** [comment]
not possible yet
