### ISSUE TITLE
Duplicated events when using multiple calendars

### ISSUE THREAD

**Issue by vimtor** [calcom/cal.com#7525]
### Issue Summary

I'm not sure if this is a bug, something I have miss-configured or the intended behaviour. But when people book me a meeting two events get created at the same time for the different mails. 

### Steps to Reproduce

1. Connect 2 Google calendar accounts
2. Send the link to book a meeting
3. Two events get created like in the picture below

![CleanShot 2023-03-05 at 21 53 21@2x](https://user-images.githubusercontent.com/36263538/222985462-f2b75bef-8e00-4273-8b29-e37ab2878aef.png)
![CleanShot 2023-03-05 at 21 50 58@2x](https://user-images.githubusercontent.com/36263538/222985463-d226df78-d56d-437d-bb63-47a535cacbd8.png)

In the pictures `victor@vimtor.io` is my personal email (the one that created my Cal.com account) and `victor.navarro@mankind.technology` is my work email (the one that the link is configured to book).

**Comment by PeerRich** [comment]
i think this has been fixed. can you try again?
