### ISSUE TITLE
[CAL-1183] Choose duration feature allows a booking for a time that isn't available.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7529]
Created via Threads. See full discussion: [https://threads.com/34453489508](https://threads.com/34453489508)

It blocks all the slots properly for all other durations, but once you select 60 minutes it shows 10:00 slot when that shouldn't be available

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1183](https://linear.app/calcom/issue/CAL-1183/choose-duration-feature-allows-a-booking-for-a-time-that-isnt)</sub>

**Comment by davlet61** [comment]
I am experiencing the same. I have 90 minutes slots with 60 min events. Whenever a slot is booked, all the other slots get changed, or shifted half an hour.

---

Here is an example:

### Initial Slots (How it is supposed to be):
![inital_slots](https://github.com/calcom/cal.com/assets/30911739/05d4c62d-1dcc-41f1-a1a2-372cb04e63da)

### Slots after some of them are booked:
![booked](https://github.com/calcom/cal.com/assets/30911739/a9cb1943-a1da-4897-965c-696ab6cbd4d2)

---

I tried adding buffer time, but that doesn't help either
