### ISSUE TITLE
Scroll bar because auto height adjustment doesn't take <0.5 values into account

### ISSUE THREAD

**Issue by LartyHD** [calcom/cal.com#7548]
### Issue Summary

Scroll bar because auto height adjustment doesn't take <0.5 values into account

**Here you can see that on the right the CSS height is `424.297px` but the height of the Iframe only got updated to `424px`**

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/23587853/223284191-d6ac2462-48cc-4856-83c7-77f3053202fa.png">

**Result for the bug is this ugly scrollbar**

<img width="820" alt="image" src="https://user-images.githubusercontent.com/23587853/223284805-05beb8d6-188b-45f4-9418-c9f4fba168f9.png">

## Solution sugestion
`(i.style.height = o.iframeHeight + n),` would need to up round the `o.iframeHeight`

<img width="697" alt="image" src="https://user-images.githubusercontent.com/23587853/223285156-9e9e098a-3291-42bd-924e-cf9c12c5532d.png">

**Comment by PeerRich** [comment]
hey @LartyHD just saw you raised a PR. thank you for that! 

@hariombalhara left a comment https://github.com/calcom/cal.com/pull/7549#discussion_r1127462338
