### ISSUE TITLE
[CAL-1333] No * at phone number and location, although required.

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7552]
Nice to see you have now included the * in the name and email address. Just noticed that it is missing from the phone number and location though.

The location can also not be set to required in the settings.

<img width="367" alt="Bildschirm­foto 2023-03-07 um 03 59 39" src="https://user-images.githubusercontent.com/126205884/223319995-23e33a66-9af9-4396-a80b-f6c45ccffc1c.png">
<img width="378" alt="Bildschirm­foto 2023-03-07 um 03 59 29" src="https://user-images.githubusercontent.com/126205884/223319997-2e95b741-338e-459f-b8ed-811c8b536641.png">

<sub>[CAL-1333](https://linear.app/calcom/issue/CAL-1333/no-at-phone-number-and-location-although-required)</sub>

**Comment by Udit-takkar** [comment]
similar to points here https://github.com/calcom/cal.com/issues/7541
