### ISSUE TITLE
html formatting in event descriptions/text fields

### ISSUE THREAD

**Issue by AUT-TOM** [calcom/cal.com#7554]
I'm coming from calendly and do see quite a good progress on cal.com

One must have feature I'm missing to make the switch for scheduling my outdoor trainings, is the possibility to create html links to locations (maps). In my case this is needed so people can choose where to meet up and without html links this is pretty much impossible.

I know that you can enter links for locations in the event type, but adding google map links like https://goo.gl/maps/de7WzkbLddNAXPa26 for example was just not working (and I'd like to give it certain names instead of the full URI)

I also tried raw html which is not parsed (i guess for security reasons)

Neither in Event descriptionss, nor in additional text fields or radio button fields I can create links to send people to the exact location on a map.

I see this little WYSIWYG editor feature already enabled in the profile, could we get the same in those other fields too please?

tia and keep up the good work
TOM

**Comment by PeerRich** [comment]
you can add links to the description, doesnt that help?

**Comment by PeerRich** [comment]
![CleanShot 2023-03-07 at 13 49 26@2x](https://user-images.githubusercontent.com/8019099/223426770-5766b154-a6a8-4bee-92a2-79399531c9c3.jpg)

**Comment by PeerRich** [comment]
or do you refer to the link location? in that case, you can use the setting: "Link" when adding a location

![CleanShot 2023-03-07 at 13 50 25@2x](https://user-images.githubusercontent.com/8019099/223426983-820ba11f-7a1d-481c-9294-146ad0d32a37.jpg)

**Comment by AUT-TOM** [comment]
Weird, I swear I didn't have the option to do bold/italic/links in descriptions yesterday in the GUI

Anyways, I've now added my three locations/links which attendees could choose from in the description like that:

![grafik](https://user-images.githubusercontent.com/127188675/223440689-d4bb83f6-3373-46b9-b3b1-eb3dbc9a50b9.png)

In chrome I can scroll the description:

![grafik](https://user-images.githubusercontent.com/127188675/223441038-8027dc87-31c1-43ba-9cc9-bb3540d6f6b2.png)

But in firefox the view is broken:

![grafik](https://user-images.githubusercontent.com/127188675/223441093-551624c3-4c21-4d1b-b7f6-dad7a34b5b81.png)


And regarding the Link as location suggestion: I'd like to use it, but it does not work for me. You can take a look at my Location, which is a google maps link, but it renders as a non clickable "//goo.gl/maps/de7WzkbLddNAXPa26"

![grafik](https://user-images.githubusercontent.com/127188675/223441541-405969fd-aea1-4d85-95ef-28f988816710.png)

**Comment by PeerRich** [comment]
ohhh let me look into firefox. can you post the link here?

**Comment by AUT-TOM** [comment]
There you go: https://cal.com/pkaustria/parkour-einzeltraining

**Comment by PeerRich** [comment]
yep. can reproduce. will hotfix

**Comment by PeerRich** [comment]
fixed for firefox. will go live asap

**Comment by AUT-TOM** [comment]
Thanks for looking into this bug on firefox

Regarding the location/link behaviour:
Could you tell me if the location/URL behaviour is normal like that?

For me this string of text is not usable in prodiction, as a link to a location.
It would be usable if I could set a URL (maps for example) with a self defined link-name (like in the description)

**Comment by PeerRich** [comment]
https://cal.com/pkaustria/parkour-einzeltraining?duration=90 is working for me, i can click the link

**Comment by PeerRich** [comment]
maybe i misunderstand your comment

**Comment by AUT-TOM** [comment]
> https://cal.com/pkaustria/parkour-einzeltraining?duration=90 is working for me, i can click the link

I've put the google maps link as location back, for you to have a look into it
