### ISSUE TITLE
[CAL-1194] Cannot book events with seats enabled

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7558]
### Issue Summary

I am getting this warning when trying to book an event with seats:
<img width="748" alt="Screenshot 2023-03-07 at 10 06 31" src="https://user-images.githubusercontent.com/30310907/223462163-8c8ec800-da09-48bd-b7f9-27bd6d1352b7.png">

The booking is going through and will show up in /bookings, but I am not redirected to the /booking/[uid] page and this warning is shown (Production and local)

<sub>[CAL-1194](https://linear.app/calcom/issue/CAL-1194/cannot-bock-events-with-seats-enabled)</sub>

**Comment by laxmikanta415** [comment]
Hey @CarinaWolli  may i pick this issue ?

**Comment by CarinaWolli** [comment]
A lot of changes coming to seats with PR #5427, it might already be fixed there

**Comment by laxmikanta415** [comment]
Okay

**Comment by CarinaWolli** [comment]
@laxmikanta415 Great to hear 🙌🏻 maybe you find something here: [help wanted](https://github.com/calcom/cal.com/issues?q=is:issue+is:open+label:%22%F0%9F%99%8B%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8Fhelp+wanted%22)

**Comment by PeerRich** [comment]
can someone try to reproduce this?

**Comment by PeerRich** [comment]
i hink this has been fixe
