### ISSUE TITLE
[CAL-1195] Google calendar token expired

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#7564]
<img width="1436" alt="Screenshot 2023-03-07 at 11 25 46 PM" src="https://user-images.githubusercontent.com/53316345/223508114-b3f88a6c-fa9d-48e6-ad61-39ce799899d8.png">

This is what is displayed when access token expires. There is an error refreshing tokens in the logs

@calcom/web:dev: 23:24:16.998 ERROR [[lib] google_calendar Error refreshing google token 
@calcom/web:dev:  Error  invalid_grant

@calcom/web:dev:     data: {
@calcom/web:dev:       error: 'invalid_grant',
@calcom/web:dev:       error_description: 'Token has been expired or revoked.'
@calcom/web:dev:     },

Moreover, this prevents events from syncing with Google Calendar.

Need to  inform user when token expires through email or better figure out if refreshing token is possible as all the booking made when user token expires won't show up in the calendar.

<sub>[CAL-1195](https://linear.app/calcom/issue/CAL-1195/google-calendar-token-expired)</sub>

**Comment by eeshaan** [comment]
Same as #5796.
This bug makes self-hosted Cal pretty much unusable for me.

**Comment by PeerRich** [comment]
we're urgently investigating!

**Comment by zomars** [comment]
@alannnc can you replicate in your self-hosted instance?

**Comment by ilyasubkhankulov** [comment]
Are the Oauth "[in production](https://support.google.com/cloud/answer/10311615?hl=en#zippy=:~:text=publishing%20status%20of-,In%20production,-if%20they%20meet)" on google's side?

**Comment by eeshaan** [comment]
@ilyasubkhankulov Just the switched the OAuth credentials to "In production" — was not before. Will report back in a week or so.

**Comment by eeshaan** [comment]
@ilyasubkhankulov Things seem to be fine now! Can't be sure if that was the fix, but maybe it would be best to add that step to the README just in case it was.

**Comment by hariombalhara** [comment]
@alannnc @zomars @roae Is something need to be done here.

In my knowledge, credentials refresh automatically and it works.

**Comment by emrysal** [comment]
Closing this as resolved 🙏
