### ISSUE TITLE
E2E Test for Embeds is Failing

### ISSUE THREAD

**Issue by ShaneMaglangit** [calcom/cal.com#7565]
### Issue Summary

A change that is merged on the main branch seems to be causing an E2E to fail and has been affecting multiple PRs.

https://github.com/calcom/cal.com/actions/runs/4355954491
https://github.com/calcom/cal.com/actions/runs/4356847979

### Steps to Reproduce

1. Start a fresh project from the `main` branch.
2. In `/event-types`, select an event and click the `•••` icon and click embed.
3. Select any of the three options and go to the `preview` tab.
4. This should render nothing and there would be an error in the console from zod saying that eventPage is undefined.

This accurately demonstrates what the E2E test for embeds is complaining about.

### Technical details

- Browser: Chrome
- Node.js: 18
- Version: Latest `main`

**Comment by emrysal** [comment]
This actually seem to be two separate issues:

* One is the embeds test, it's very flaky (and doesn't seem to retry) - causing the embed test to fail; an example of this passing is in here: https://github.com/calcom/cal.com/pull/7528
* The second one is a bug that seems to have been introduced in a PR last week, I can't see a negative effect of that bug (besides the console error) 

Assigned @CarinaWolli to have a looksy at the console error 🙏
