### ISSUE TITLE
[CAL-1196] remove // from links and fix icon size

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7568]
* [ ]  it seems like the regex only takes away https not https://
* [ ] link icon too small

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f831337e-e63f-4df7-b3fe-d9b2e4ff365b/88f9910d-b546-46ef-8cf0-9ace658b99f2)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1196](https://linear.app/calcom/issue/CAL-1196/remove-from-links-and-fix-icon-size)</sub>

**Comment by lucas-barros** [comment]
@PeerRich I created a PR for this icon size issue. It seems the url issues was solved by https://github.com/calcom/cal.com/pull/7528.
