### ISSUE TITLE
CalDav NextCloud integration has stopped working

### ISSUE THREAD

**Issue by Frikster** [calcom/cal.com#7570]
### Issue Summary

CalDav integration has been working fine for over a month. This week I noticed that clients could book on dates where I already had events on my calendar - strangely only events that were "recurring" though they were marked as "busy." Another strange thing I noticed when I went to settings is that the CalDav calendar had disconnected and the Google calendar I had also connected had been set to the default calendar.

I have a phone and desktop calendar app and both sync fine with my CalDav Nextcloud server, so I concluded there was something weird up with the cal.com calendar sync and removed both calendars only to now find I cannot reconnect to my CalDav calendar at all...

 Is this a known issue that is being worked on or handled elsewhere? I might investigate it myself if nobody is already dealing with it.

### Steps to Reproduce

I have _also_ tested these steps with a completely different nextcloud provider and a brand new cal.com account, so it doesn't seem to be an issue specific to either the provider or my account.

1. Connect to a NextCloud CalDav server
2. Get error message below

On the Linux desktop application I see:

![image](https://user-images.githubusercontent.com/10172142/223526263-28a78e0a-4b42-4e97-994c-7d1acd2302ae.png)

On the web browser I see:

![image](https://user-images.githubusercontent.com/10172142/223526344-b20353be-60d6-43f5-b22e-91fd89ebd80b.png)

### Technical details

Whether using [Brave Browser](https://brave.com/) [Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)](https://brave.com/latest/)
Or [LibreWolf](https://librewolf.net/) 109.0.1-2 (Firefox-based) I get the same issue.

Console logs I see in case useful:
![image](https://user-images.githubusercontent.com/10172142/223526658-7c181918-6f55-4cf4-81a8-9c415ba91299.png)

Disconcertingly I also get error messages when I try to remove NextCloud CalDav calendars that failed to get added:
![image](https://user-images.githubusercontent.com/10172142/223535416-6d81d21d-369e-48ac-83a8-fb63706246c0.png)

(also tested and I get this error on a brand new cal.com account using a brand new Nextcloud provider account)

Let me know if any additional info might be useful

**Comment by alishaz-polymath** [comment]
A similar error was fixed in #7557 
Can you confirm if that sorts it out once the release is out?

**Comment by Frikster** [comment]
@alishaz-polymath Will do. Just ping me once it's in prod

**Comment by PeerRich** [comment]
can you try again @Frikster ?

**Comment by PeerRich** [comment]
fixed

**Comment by Frikster** [comment]
@PeerRich Excuse the delay. Just to confirm: fixed.
