### ISSUE TITLE
[CAL-1200] /settings - back button: should take me back out of settings, not to most recent page

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7583]
[c7daa114-3f5e-4e1d-b302-c7e90293d6e9](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fd8c6a5d-cda3-4b4a-b70b-aa92096a813a/c7daa114-3f5e-4e1d-b302-c7e90293d6e9)

This back button should always just exit me out of setings.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1200](https://linear.app/calcom/issue/CAL-1200/settings-back-button-should-take-me-back-out-of-settings-not-to-most)</sub>

**Comment by G3root** [comment]
fixed by  #7634
