### ISSUE TITLE
Rename "attendee phone number" to "phone call" or give us the possibility to manuell rename it

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7586]
Can you rename "attendee phone number" to "phone call" or give us the possibility to manuell rename it? I think, otherwise it is a bit confusing.
<img width="409" alt="Bildschirm­foto 2023-03-08 um 17 34 36" src="https://user-images.githubusercontent.com/126205884/223773248-f738731f-03ba-408a-98bb-9d0df083f413.png">

At this point, "attendee phone number" makes no sense. There should be only "phone number" or in German "Telefonnummer".
<img width="390" alt="Bildschirm­foto 2023-03-08 um 17 45 28" src="https://user-images.githubusercontent.com/126205884/223776306-feb4d806-f5de-4ef9-8103-009ea4bb96cd.png">

**Comment by PeerRich** [comment]
![CleanShot 2023-03-14 at 12 28 42@2x](https://user-images.githubusercontent.com/8019099/224987435-01fe0e77-0039-4b98-8aa0-cf3292a70286.jpg)
done.
 should go live in next update
