### ISSUE TITLE
[CAL-1201] Small bug with the automatic country detection for the phone number

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7593]
Small bug with the automatic country detection for the phone number

https://user-images.githubusercontent.com/126205884/223770600-93779e64-a4f3-4dd9-9413-9ef2ef0cd371.mov

<sub>[CAL-1201](https://linear.app/calcom/issue/CAL-1201/small-bug-with-the-automatic-country-detection-for-the-phone-number)</sub>

**Comment by RainerZufall9393** [comment]
The bug is still present despite the update @Udit-takkar

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/224081016-90201560-83bf-40d2-8b88-756890908a51.mov

@RainerZufall9393 it works fine here test this https://cal.com/udit/15min?duration=15

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/224081653-6ee62d4e-6849-400a-a3b0-23125ebd3dc9.mov

It's working fine you can test this https://cal.com/udit/15min?duration=15

**Comment by RainerZufall9393** [comment]
Try it on my side. It is best to switch back and forth a few times. https://cal.com/robbyn-gellert/gespraech

@Udit-takkar

**Comment by RainerZufall9393** [comment]
Try it on my side. It is best to switch back and forth a few times. https://cal.com/robbyn-gellert/gespraech

@Udit-takkar

**Comment by Udit-takkar** [comment]
@RainerZufall9393 it's happening on this event type because when you select attendee phone number a new component is added and Telefonnummer is removed. i don't think we can pass this data between these independent components.

**Comment by RainerZufall9393** [comment]
Yes, I believe that this is difficult. However, I'm not concerned about the transfer of the phone number, but only about the automatic country code at the beginning. When changing the phone number, the code is set to US (+1) instead of Germany (+49).

But it wouldn't be a big deal if this can't be fixed. :) @Udit-takkar

**Comment by RainerZufall9393** [comment]
Uploading IMG_8546.MOV…

**Comment by Udit-takkar** [comment]
@RainerZufall9393 ok I can try getting the country code from cache rather than default value.
