### ISSUE TITLE
[CAL-2081] More generic date overrides (weekly monthly yearly)

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7600]
Yearly repeating date overrides would also be useful. For example, if you want to offer different times on certain days like Christmas, New Year's Eve, etc. and this is always handled that way.

[https://user-images.githubusercontent.com/126205884/223822895-e7c4f4c3-9f0c-4e1f-a8b2-d582045c4963.png](https://user-images.githubusercontent.com/126205884/223822895-e7c4f4c3-9f0c-4e1f-a8b2-d582045c4963.png)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2081](https://linear.app/calcom/issue/CAL-2081/more-generic-date-overrides-weekly-monthly-yearly)</sub>

**Comment by PeerRich** [comment]
in general i think having the ability to do more generic stuff like:

every first (second, third, fourth) monday
every friday of a month
every first (n-th) day of the month
every nth day of a year etc.

**Comment by saschafoerster** [comment]
I would like to be able to add an ICS file or use any calendar with holidays that also works on a team level. For instance one could use this ICS 
https://calendars.icloud.com/holidays/de_de.ics/
This would then block all bookings on the complete team level and you don't need to enter all holidays day by day, every year a new. For all other exceptions, the existing overrides are fine, but also it would be helpful to have them on a team level for everyone.

**Comment by AndrejGajdos** [comment]
+1
