### ISSUE TITLE
Appearing available when not actually available

### ISSUE THREAD

**Issue by 12ian34** [calcom/cal.com#7602]
### Issue Summary

Slots on my booking page are appearing available when not actually available.

### Steps to Reproduce

April seems to have available slots on the booking page

<img width="974" alt="image" src="https://user-images.githubusercontent.com/9979944/223824623-c4950381-bfe6-4222-ad16-1de876600882.png">

In my Google Calendar, this period is definitely "Busy"

![Untitled](https://user-images.githubusercontent.com/9979944/223825036-487a67da-5725-4479-a8be-f7e8bf367ee7.jpg)

And on attempting to book one of the apparently available slots, this error arises:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/9979944/223825151-ecca6fc8-0674-4b08-b53b-dc978bfdfb4b.png">

### Technical details

- I have experimented with non-all day events. They don't seem to be working either.
- I have triple checked my Calendar connection settings. The correct calendar is being checked for conflicts.
- I have triple checked my Availability Hours settings, see below:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/9979944/223825662-c0004440-822a-4bf8-9027-ef046c3cfb27.png">

**Comment by roae** [comment]
@12ian34 Thank you for the details,are very helpful, this is a known bug, I'm already investigating it

**Comment by melalj** [comment]
This is extremely frustrating and it has been the case for the last 2 weeks:
![CleanShot 2023-03-09 at 00 59 34@2x](https://user-images.githubusercontent.com/3869766/223880533-ebb393da-ed6c-4326-adae-e6efce9a3311.jpg)
