### ISSUE TITLE
[CAL-1203] radio group buttons have odd styling

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7606]
hello, radio group on question is not clear. Issue on style

[Slack Message](https://calendso.slack.com/archives/C01NXDSRY9W/p1678292694768899?thread_ts=1678292694.768899&cid=C01NXDSRY9W)

<sub>[CAL-1203](https://linear.app/calcom/issue/CAL-1203/radio-group-buttons-have-odd-styling)</sub>

**Comment by zomars** [comment]
duplicate of #7603
