### ISSUE TITLE
The webhook is not sending the customInputs of the event types generated in version 2.6.8

### ISSUE THREAD

**Issue by M22Daniel** [calcom/cal.com#7610]
When custom fields are added to an event as of version 2.6.8 these are not sent in the webhook, only: "description" is sent. Event types previously created with custom fields continue to send correctly.

![Captura](https://user-images.githubusercontent.com/97559544/223890029-df6e1173-284c-4921-8133-64132d3b86e5.PNG)

**Comment by PeerRich** [comment]
@CarinaWolli or @alishaz-polymath wanna look into this?

maybe due to @hariombalhara recent introduction of "Questions"?

**Comment by hariombalhara** [comment]
These are available in `userFieldsResponses` now. `responses` has all the responses including those of system fields.
Only old event-types that aren't modified would keep on receiving `customInputs`.

<img width="1207" alt="Screenshot 2023-03-15 at 3 36 11 PM" src="https://user-images.githubusercontent.com/1780212/225276566-ffbe189d-f93c-4fe6-949c-ffe97af02308.png">

**Comment by M22Daniel** [comment]
> These are available in `userFieldsResponses` now. `responses` has all the responses including those of system fields. Only old event-types that aren't modified would keep on receiving `customInputs`.
> 
> <img alt="Screenshot 2023-03-15 at 3 36 11 PM" width="1207" src="https://user-images.githubusercontent.com/1780212/225276566-ffbe189d-f93c-4fe6-949c-ffe97af02308.png">

Thank you very much, it's just what I was looking for.

**Comment by M22Daniel** [comment]
Many thanks to @hariombalhara 
Fields are now in 'responses' and 'userFieldsResponses'

**Comment by CarinaWolli** [comment]
@hariombalhara does that mean we can close the issue?

**Comment by hariombalhara** [comment]
@CarinaWolli Yeah. Closing it.
