### ISSUE TITLE
Missing documented event guest addition option

### ISSUE THREAD

**Issue by kaerez** [calcom/cal.com#7613]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Documentation shows management of the event booker ability to add guests as a simple and clear
toggle: https://docs.cal.com/core-features/event-types/disable-guests
However this option does not exist and is instead controlled by a misleading and mislabeled toggle.

### Steps to Reproduce

Review the documentation link and the UI.
Recorded video (00:20 to 00:48): https://www.loom.com/share/77adbd7946cf428d9d901673b58bedbf

### Technical details

N/A

**Comment by PeerRich** [comment]
hey @kaerez i believe our new docs (whch are going live today) will be better

**Comment by PeerRich** [comment]
https://cal-docs.motif.land/core-features/event-types/disable-guests can you take a look here?

**Comment by kaerez** [comment]
> https://cal-docs.motif.land/core-features/event-types/disable-guests can you take a look here?
### I'm afraid the beautiful, simple, UI shown in this documentation isn't aligned with the actual configuration. I just checked both in an existing event and in a new event. @PeerRich

**Comment by PeerRich** [comment]
oh ok. @alishaz-polymath can you take a look

**Comment by alishaz-polymath** [comment]
Yep, taking a look. Thanks 🙏

**Comment by alishaz-polymath** [comment]
This is sorted.
Ref: https://cal.com/docs/core-features/event-types/disable-guests
