### ISSUE TITLE
[CAL-2083] Data collection - default selection

### ISSUE THREAD

**Issue by kaerez** [calcom/cal.com#7616]
### Is your proposal related to a problem?

Consider a medical clinic or another booking page where most of the bookers need the same data entry,
such as "regular appointment" or "no referral code", however some bookers would need to select
a different option (such as "urgent meeting").

The ability to default select/enter would excuse most bookers from dealing with this data entry/selection field while allowing those who need it the ability to flag/notify about it.

This entered data could also later be used in workflows and reduces the need to have duplicate
event types for the sole purpose of providing a solution to this default selection issue.

Sample use case - recorded video (00:14 to 00:20): https://www.loom.com/share/77adbd7946cf428d9d901673b58bedbf

### Describe the solution you'd like

The ability to select (radio, dropdown) or enter (text, pickers) a default option should be available.

### Describe alternatives you've considered

Create multiple booking forms and using routing / post event analysis of free text

<sub>[CAL-2083](https://linear.app/calcom/issue/CAL-2083/data-collection-default-selection)</sub>

**Comment by PeerRich** [comment]
have you tried the "booking questions" feature?

**Comment by PeerRich** [comment]
in advanced settings: 
![CleanShot 2023-03-10 at 20 39 51@2x](https://user-images.githubusercontent.com/8019099/224412273-9d6ab5ff-4781-499a-9e7e-dd31784f0901.jpg)

**Comment by kaerez** [comment]
Hi @PeerRich, yes I have and that's what I am currently doing; however it does not allow a default selection to be made.

**Comment by PeerRich** [comment]
@hariombalhara should we add a "default value" option? 🤔

**Comment by hariombalhara** [comment]
Yeah makes sense.
