### ISSUE TITLE
[CAL-1230] Event duplication failure

### ISSUE THREAD

**Issue by kaerez** [calcom/cal.com#7617]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cannot duplicate an event

### Steps to Reproduce

1. Configure Cal.com free account
2. Connect GCAL as default calendar
3. Connect O365 as additional calendar
4. Create an event requiring confirmation, custom radio question requiring a response (three options; include comma and period in text)
5. Select a non default calendar: O365
6. Choose a long custom event stub and hide the event from the user's page
7. Try to duplicate the event

### Technical details

Recorded video (00:48): https://www.loom.com/share/77adbd7946cf428d9d901673b58bedbf

<sub>[CAL-1230](https://linear.app/calcom/issue/CAL-1230/event-duplication-failure)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli can you look into this? youre looking into duplication right now

**Comment by CarinaWolli** [comment]
I tested a lot of different scenarios and it did actually throw the error sometimes. However, now I again can't reproduce it. @Udit-takkar could you maybe test that as well? I saw you are assigned to another issue about that https://github.com/calcom/cal.com/issues/6272

**Comment by Udit-takkar** [comment]
@CarinaWolli yeah not able to reproduce. @kaerez can you send url of this event type booking page ?

**Comment by kaerez** [comment]
Issue seems to be resolved
