### ISSUE TITLE
Problems with full days blockings

### ISSUE THREAD

**Issue by seem2810** [calcom/cal.com#7621]
I've added my vacation in my private apple calendar.
But my booking calendar is free - how can i change it?

**Comment by sean-brydon** [comment]
Hi @seem2810  sorry for the late reply!

You can do this by adding what we call "Date Overrides"

Please see our documentation if you need help doing this https://docs.cal.com/core-features/availability/date-overrides

**Comment by seem2810** [comment]
> Hi @seem2810 sorry for the late reply!
> 
> You can do this by adding what we call "Date Overrides"
> 
> Please see our documentation if you need help doing this https://docs.cal.com/core-features/availability/date-overrides

I've done - but for 3 weeks vacation I need to create 21 entries ?
Why can't add a date range?
