### ISSUE TITLE
Workflow creates mandatory SMS field

### ISSUE THREAD

**Issue by AUT-TOM** [calcom/cal.com#7640]
I do have an event type with two workflows attached. Those two workflows do send E-Mails to the customer if the event date changes and a reminder 24 hours before the event starts.

You can see the workflow setting here:
![2023-03-09 16_40_48-24h Reminder _ Cal com – Mozilla Firefox](https://user-images.githubusercontent.com/127188675/224076301-d76d4813-7a3c-498b-90ff-bd1f834a90a7.png)

Although I have no option to send SMS the system creates fields to enter phone numbers for SMS notifications in my event like that

![2023-03-09 16_40_18-Ninja Warrior Einzeltraining _ Termintyp _ Cal com – Mozilla Firefox](https://user-images.githubusercontent.com/127188675/224076240-7039e1a9-d6a3-4a9b-a670-bf9f59854551.png)

![2023-03-09 16_44_20-Bestätigen Sie Ninja Warrior Einzeltraining mit Parkour Austria _ Cal com – Mozi](https://user-images.githubusercontent.com/127188675/224076635-64f1bf22-b349-459e-abaf-4b2aee82794c.png)

I can't toggle those fields off or delete them, as long as the event type is connected with this E-Mail notification workflow.

Those Telephone Number Fields should not automatically be attached to event-types, when not in use.

thanks in advance for looking into it

**Comment by PeerRich** [comment]
@AUT-TOM this is already work in progress
