### ISSUE TITLE
[CAL-1217] Fix Linear Check

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7645]
With bookings questions I think the name field lost it's id="name" attribute.

We should either add it back or [update the checkly test](https://app.checklyhq.com/checks/224dd474-4dc8-49ef-a353-15349f7ec0c1/browser/edit):

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3752d99f-c72a-43f2-8632-30640b9846a8/c8bb95f6-d117-44d7-a227-cd40f9459fb2)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1217](https://linear.app/calcom/issue/CAL-1217/fix-linear-check)</sub>

**Comment by hariombalhara** [comment]
<img width="1307" alt="Screenshot 2023-03-10 at 1 37 20 PM" src="https://user-images.githubusercontent.com/1780212/224259008-69e27cd9-8d71-4237-a3ed-6c4347584b53.png">
Fixed the check, new selector is `[name="name"]`
