### ISSUE TITLE
Success page of a group booking is not correctly displaying attendees

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#7648]
Found a bug? Please fill out the sections below. 👍

I made a group booking and it only showed my information and the host's information was duplicated.

![34454665462_image2048](https://user-images.githubusercontent.com/525369/224197320-5592fe7e-5219-4bb9-89f7-bc5f0ba797fe.png)

**Comment by G3root** [comment]
@roae i can't seems to reproduce this locally

![Screenshot 2023-03-10 at 11-03-38 Your booking has been confirmed Cal com](https://user-images.githubusercontent.com/84864519/224232528-b6e80c7b-dbad-4981-b6b9-73e242183920.png)

**Comment by PeerRich** [comment]
i think this is dynamic booking links: cal.com/peer+bailey+zomars

**Comment by joeauyeung** [comment]
I also can't reproduce this locally on main or production using dynamic booking links

**Comment by joeauyeung** [comment]
Looking into it, the booking that was created had Bailey as the host and listed as an attendee instead of Peer.

**Comment by roae** [comment]
> Looking into it, the booking that was created had Bailey as the host and listed as an attendee instead of Peer.

that's exactly what happened @joeauyeung.

**Comment by joeauyeung** [comment]
> Looking into it, the booking that was created had Bailey as the host and listed as an attendee instead of Peer.

Sorry, should have specified it's saving like this on the DB and not just the frontend
