### ISSUE TITLE
Error when booking meeting/incorrect meeting time showing as available

### ISSUE THREAD

**Issue by richiemcilroy** [calcom/cal.com#7659]
### Issue Summary

My meetings are set to 20 mins long. My calendar is set to max of 5:45pm. It shows an available time slot on my calendar of 5:40pm.

### Steps to Reproduce

1. Meeting length set to 20 mins
2. Calendar time set to max of 5:45pm
3. Available time slot in my calendar of 5:40pm
4. Meeting at 5:40pm shows an error when trying to book

I would expect the calendar slot at 5:40pm not to show, since my max time is set to 5:45pm. But if it is supposed to show, I would expect the 5:40pm meeting to correctly book and not show an error.

### Technical details
-MacBook Pro 13" M1, Google Chrome

### Screenshots
Calendar settings image:

Ability to schedule / reschedule appointments outside of regular appointment times.
![CleanShot 2023-03-14 at 12 54 04@2x](https://user-images.githubusercontent.com/8019099/224993202-1ae379cf-6bbc-4c54-944a-4fe754e1840e.jpg)

Calendar availability image:

![CleanShot 2023-03-14 at 12 53 28@2x](https://user-images.githubusercontent.com/8019099/224993024-c4acd333-e541-42cc-9f0a-e39286903f42.jpg)

Calendar booking error image:

![CleanShot 2023-03-14 at 12 53 41@2x](https://user-images.githubusercontent.com/8019099/224993066-4173a071-876b-4025-acc1-e29214cf8633.jpg)

**Comment by CarinaWolli** [comment]
@richiemcilroy  I can not open the images, could you try to upload them differently?

**Comment by richiemcilroy** [comment]
Apologies @CarinaWolli, looks like the auth on the images had a short expiration. Just re-uploaded 😄

**Comment by PeerRich** [comment]
added inline images

**Comment by richiemcilroy** [comment]
Thank you @PeerRich!
