### ISSUE TITLE
[CAL-1222] Timezone dropdown shows london several times 

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7660]
### Issue Summary

When you search 'London' in the timezone dropdown it shows 3 times 'London GMT' but two of them are wrong. Two of them are timezone -5 and when clicking them it shows America/Detroit 

<img width="375" alt="Screenshot 2023-03-10 at 10 16 13" src="https://user-images.githubusercontent.com/30310907/224353842-f9db5c5f-0ec2-4a66-bea4-9633a87aa51e.png">

<sub>[CAL-1222](https://linear.app/calcom/issue/CAL-1222/timezone-dropdown-shows-london-several-times)</sub>

**Comment by PeerRich** [comment]
maybe there is a london in the US?

**Comment by PeerRich** [comment]
![image](https://user-images.githubusercontent.com/8019099/224379303-e7ba81cf-7e46-4db7-ac98-7e9c42751258.png)

**Comment by CarinaWolli** [comment]
But it shouldn't show GMT then

**Comment by CarinaWolli** [comment]
that definitely confused me, as the American one is also the first option

**Comment by Toledodev** [comment]
@PeerRich We can hide the other options

**Comment by PeerRich** [comment]
can we run a duplicate check?

**Comment by PeerRich** [comment]
@Toledodev yes please

**Comment by Toledodev** [comment]
Sure

**Comment by Toledodev** [comment]
Hey @PeerRich @CarinaWolli I'm thinking in create a function to check all the duplicate cases and return the 
the option with the largest population, what do you think?

**Comment by PeerRich** [comment]
you mean a script to go over it once right? and then change the underlying json 

or do you wanna call this function everytime? 🤣

**Comment by Toledodev** [comment]
Yes only once

**Comment by PeerRich** [comment]
go for it
