### ISSUE TITLE
[CAL-1228] Wrong time format in emails

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7663]
In the e-mails, the set 24-hour format is not applied, but the 12-hour format.

![BD0E2765-8711-4E67-9C9E-1F7BC904C86A](https://user-images.githubusercontent.com/126205884/224400048-076873c0-3d93-46c5-ba5f-5085a0c835ba.jpeg)

The date format is also wrong. In Germany we do not write Monday, March 20, 2023 but Monday, 20. March 2023

<sub>[CAL-1228](https://linear.app/calcom/issue/CAL-1228/wrong-time-format-in-emails)</sub>

**Comment by brymut** [comment]
Hi @PeerRich / @RainerZufall9393 , happy to take this on, I've submitted a bid on Algora. I've got experience building with Nextjs/TypeScript. 🙂

**Comment by lucas-barros** [comment]
@PeerRich bid submitted. I have a working solutions, awaiting the bid approval.

**Comment by lucas-barros** [comment]
![image](https://user-images.githubusercontent.com/11845759/224555314-a9c382e5-43fb-4459-81ac-66f23e6f4c40.png)

**Comment by PeerRich** [comment]
accepted! great work

**Comment by Udit-takkar** [comment]
@PeerRich isn't this issue duplicate of https://github.com/calcom/cal.com/issues/7614 ?
