### ISSUE TITLE
[CAL-1233] Bookings for any 6pm (America/Detroit) do not work, no availability msg

### ISSUE THREAD

**Issue by cpunnelliehealth** [calcom/cal.com#7667]
Timezone America/Detroit (have not tested on other timezones)

Set availability for past 6pm, for example 9am - 8pm 

Pick a weekday in the future for 6pm timeslot (60 minute event), I tried March 20, March 29 and April 17 randomly.  

Error shows no availability. 5pm or 7pm bookings will work, just not 6pm. Something strange/special about 6pm EDT that is causing the no availability bug.

This is occurring on Cal.com as well as our self hosted instance running 2.6.7

<img width="822" alt="Screen Shot 2023-03-10 at 5 23 02 PM" src="https://user-images.githubusercontent.com/126418022/224439886-2514cfcc-6166-49ed-9ddd-236d6e0e7fee.png">
<img width="842" alt="Screen Shot 2023-03-10 at 5 22 28 PM" src="https://user-images.githubusercontent.com/126418022/224439888-1c157fe1-09e6-4999-9c49-bab136c79735.png">

<sub>[CAL-1233](https://linear.app/calcom/issue/CAL-1233/bookings-for-any-6pm-americadetroit-do-not-work-no-availability-msg)</sub>

**Comment by cpunnelliehealth** [comment]
This is now working, I think there are still unresolved issues related to making bookings that cross daylight savings time relative to the current date. e.g., https://github.com/calcom/cal.com/issues/6622

**Comment by PeerRich** [comment]
we will investigate! thank you

**Comment by PeerRich** [comment]
can you post the link here? or another link that we can reproduce

**Comment by roae** [comment]
hi @cpunnelliehealth, I could not replicate this in the new version we released today. Can you try again please?

**Comment by roae** [comment]
Fixed on #7792
