### ISSUE TITLE
[Feature Request] Blue Jeans Integration for Cal.com

### ISSUE THREAD

**Issue by alexandertsukanov** [calcom/cal.com#7676]
Site: https://bluejeans.com/

### Description
As a user of the Cal.com app, I would like to have the ability to schedule and join Blue Jeans meetings directly from within the app. This integration would allow for a more seamless and efficient scheduling process, as well as provide a more streamlined experience for joining meetings.

### Features
-  Ability to schedule Blue Jeans meetings directly from the calendar app
-  Option to include Blue Jeans meeting details (e.g. meeting link, dial-in information) in calendar invites
-  One-click access to join scheduled Blue Jeans meetings from within the calendar app
-  Integration with calendar notifications to remind users of upcoming Blue Jeans meetings

### Benefits
-  Saves time and improves efficiency by eliminating the need to switch between multiple apps to schedule and join meetings
-  Provides a more streamlined and user-friendly experience for scheduling and joining Blue Jeans meetings
-  Reduces the likelihood of scheduling conflicts or missed meetings by centralizing meeting information in one location

**Comment by shivamklr** [comment]
@PeerRich Is this similar to the whereby app integration? Or are we looking for any additional features?

**Comment by rjackson** [comment]
I have requested access to Blue Jeans APIs, will explore this once granted access.

/attempt #7676

**Comment by rjackson** [comment]
BlueJeans have invited me to a 30 minute call on Thursday, June 8th at 18:00 BST (my time, or 17:00 UTC) to learn more about my interest in their developer hub & APIs.

I'll make it absolutely clear that I have no direct affiliation with Cal.com, of course, but explain that the project is open-source and I'm looking at this feature request as an independent contributor.

I'm happy to forward the invite on if there's anybody from Cal.com that would like to join the call as well?

**Comment by rjackson** [comment]
No meaningful update. Yesterday's call was more of an outreach from their commercial partnerships team, as my signing up for dev access put my details into their partnerships pipeline.

They shared a few links & resources that I might find helpful, but overall I'm still waiting to be granted access to their developer platform.

**Comment by vickywane** [comment]
@alexandertsukanov @rjackson 

This looks like an interesting issue, and would love to work on it. 

I should be able to get access to BlueJeans developer API ( I will start this process )

**Comment by b4s36t4** [comment]
https://www.bluejeans.com/blog/bluejeans-being-sunset I think we don't need to support this anymore.

**Comment by compgeniuses** [comment]
shouldnt we close this issue

**Comment by itsxdamdam** [comment]
@PeerRich I'd like to know if this issue is still open and attempt it.

**Comment by alexandertsukanov** [comment]
Hey, guys! I believe the issue is no longer relevant as Blue Jeans has announced plans to close the company.

**Comment by alexandertsukanov** [comment]
Thank you, everyone, for participating in this topic.
