### ISSUE TITLE
[CAL-1231] mobile menu rerendering

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7677]
https://user-images.githubusercontent.com/8019099/224544929-08711027-9006-49d3-8a93-1d12d0030255.MOV

<sub>[CAL-1231](https://linear.app/calcom/issue/CAL-1231/mobile-menu-rerendering)</sub>

**Comment by hariombalhara** [comment]
I can't replicate this issue. Seems like it's fixed now. So, closing it.

[https://www.loom.com/share/9391f259bfff46949b5e8660f8e6d369](https://www.loom.com/share/9391f259bfff46949b5e8660f8e6d369)
