### ISSUE TITLE
Baïkal (CalDAV) Not Showing Existing Events to Block From Booking

### ISSUE THREAD

**Issue by Swamp2k9** [calcom/cal.com#7679]
I've managed to sync my Baïkal calendar to cal.com (all calendars appear), but I'm unable to block off unavailable dates/times on my booking page. I've went through Cal's calendar settings and made sure that the calendar is checked under "Check for Conflicts".

The same calendar is working fine in SimplyMeet. It blocks off unavailable/booked times.

My WebDAV authentication type is set to "Basic" in Baïkal.

Also, you can't save "Check for Conflicts" unless you change the "Add to Calendar" option above it.

###########
How to Reproduce

1. Add event to Baïkal calendar 
2. Go to Cal's Event Booking page (client-facing)

**Comment by PeerRich** [comment]
@alishaz-polymath will investigate

**Comment by PeerRich** [comment]
moving to: https://github.com/calcom/cal.com/issues/3457
