### ISSUE TITLE
[CAL-1237] html formatting in E-Mail wrong (description)

### ISSUE THREAD

**Issue by AUT-TOM** [calcom/cal.com#7686]
The Event description in E-Mails is wrongly formatted, as you can see in this screenshot

![2023-03-13 10_49_27-Webmail - ALL-INKL COM - tom@stfu at – Mozilla Firefox](https://user-images.githubusercontent.com/127188675/224667310-6ff93a06-7bd2-4c1c-9fcc-daffccfef789.png)

Also I see that cal.com is sending E-Mail from "hello@cal.com", when a customer blindly answers these E-Mails they will end in nirvana... is there a chance to set the sender E-Mail Address to direct them to an E-Mail which is read? My fear is that customers ask something and they'll never get an answer because of that.

<sub>[CAL-1237](https://linear.app/calcom/issue/CAL-1237/html-formatting-in-e-mail-wrong-description)</sub>

**Comment by CarinaWolli** [comment]
I will fix the formatting of the email

I don't think we can send from other email addresses with SendGrid, but we might be able to change the reply-to email. I will look into that as well
