### ISSUE TITLE
[CAL-1251] bookable timeslots calculated wrong

### ISSUE THREAD

**Issue by AUT-TOM** [calcom/cal.com#7687]
I have two event types, one is correct and the second one does not count my availability correct.

My availability times are:

![2023-03-13 11_22_07-Ninja Warrior Einzeltraining _ Termintyp _ Cal com – Mozilla Firefox](https://user-images.githubusercontent.com/127188675/224674349-b6135e5d-605f-4ad2-8c0d-4faa72cd5829.png)

so until 8pm with an 90 minutes event

![2023-03-13 11_24_29-Ninja Warrior Einzeltraining _ Parkour Austria _ Cal com – Mozilla Firefox](https://user-images.githubusercontent.com/127188675/224674951-7819c25a-1029-4402-bace-19203c2d86d1.png)

But the system calculates my last bookable time at 5:30pm => it should be 6:30pm

I've also double and triple checked my time limits and browser cache.
I've also created a whole new availability "work time" but it still does not calculate it correctly, but only for my second event type.. the first one calculates correct.

<sub>[CAL-1251](https://linear.app/calcom/issue/CAL-1251/bookable-timeslots-calculated-wrong)</sub>

**Comment by Udit-takkar** [comment]
@AUT-TOM can you share your booking url for this event type?

**Comment by AUT-TOM** [comment]
> 

This is one example
https://cal.com/pkaustria/ninja-warrior-einzeltraining?duration=90&date=2023-03-24

**Comment by AUT-TOM** [comment]
@Udit-takkar 

U need any more information to look into that problem?
I have no idea where to start looking, but what I can see is that this date calculates wrong https://cal.com/pkaustria/ninja-warrior-einzeltraining?duration=90&date=2023-03-24 and this calculates right https://cal.com/pkaustria/ninja-warrior-einzeltraining?duration=90&date=2023-03-26 altough those days should have the same time slots until 6:30pm

this issue is a show-stopper for me, I hope you can fix this asap

**Comment by Udit-takkar** [comment]
@AUT-TOM thanks for reaching out. We are investigating this bug. Maybe the cause of this big is DST

**Comment by AUT-TOM** [comment]
@Udit-takkar 
should the problem be fixed? Because the bug is closed, but it's still not working on my side

https://cal.com/pkaustria/parkour-einzeltraining?duration=90&date=2023-03-25 (18:00) => https://cal.com/pkaustria/parkour-einzeltraining?duration=90&date=2023-03-26 (19:00)

And there are also random timeslots missing, like 10:30 / 15:00 etc.

So I don't see the timeslots calculation working properly

**Comment by Udit-takkar** [comment]
@AUT-TOM yeah the PR is in production. Not sure why it is not working cc: @emrysal

**Comment by AUT-TOM** [comment]
can someone re-open the ticket or give any feedback here?

I think the calculation of bookablle timeslots is a core functionality and if it's broken, there should be some attention on it.

**Comment by kortenkamp** [comment]
I can confirm that there is still a problem – it looks like current appointments (which are in my calendar as "Mitteleuropäische Zeit", but are in daylight saving time) are miscalculated by one hour.

**Comment by emrysal** [comment]
Hi @kortenkamp we've worked on this for a while in silence but I've just marked this issue to be fixed btya PR that is intended to rework and simplify our slot rendering - thank you for your patience

**Comment by kortenkamp** [comment]
Thanks for the update!!
