### ISSUE TITLE
Widget flashing between light and dark on MacOS dark theme

### ISSUE THREAD

**Issue by dschuermann** [calcom/cal.com#7695]
### Issue Summary

The cal.com widget is flashing between light and dark on Mac OS with dark theme enabled. This should not happen. We explicitly set the cal.com style to "light" inside the embed code.

### Steps to Reproduce

1. Set dark theme on Mac OS
2. Go to https://www.heylogin.com/en/compliance-whitepaper-download
3. The cal.com widget flashes between light and dark

This is how it looks:

https://user-images.githubusercontent.com/321888/224729744-ffc2da56-1fdb-4646-a3df-1946d424079f.mov

**Comment by PeerRich** [comment]
@sean-brydon @hariombalhara you two looked into this before, what could this be?

**Comment by hariombalhara** [comment]
It might be related to this https://github.com/calcom/cal.com/issues/7497.  

The issue isn't replicable through the steps mentioned. @dschuermann Do you see the issue when you open the page in an incognito tab or a fresh instance with no persistence of app.cal.com

**Comment by dschuermann** [comment]
@hariombalhara Looks like it is gone, also without using an incognito tab. It's probably gone because I set the "light" theme inside cal.com user settings.
