### ISSUE TITLE
Cannot book seemingly available time slot

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#7701]
### Issue Summary

When attempting to book an event with Peer, I received an error saying "Could not book the meeting. Can you try again with a different time? Go back"

![Screen Shot 2023-03-13 at 10 33 16 AM](https://user-images.githubusercontent.com/2538462/224756535-2ba9ba85-1818-49ea-9d6a-a057888dc9d7.png)

Related to #6696, #6932?

### Steps to Reproduce

1. Use cal.com/peer/30 and attempt to book an available slot

### Technical details

- Chrome

**Comment by PeerRich** [comment]
for context, this error throws around 20 to 50 times per day, which, given the amount of bookings is not a lot, yet important




![CleanShot 2023-03-13 at 22 49 43@2x](https://user-images.githubusercontent.com/8019099/224839987-7709a648-9b48-4676-a6b0-00a6174a0585.jpg)


also: it doesn't show up for everyone, 99.99% of my bookings never have this error, this is the first time i saw it. its working now and for others

**Comment by ksergazy** [comment]
This happened today for us when client tried to reschedule. In our case cal.com silently added meeting but without sending email notification for it. Started happening after we updated from 2022 Dec version to 2.7.5

**Comment by wihlner-addcream** [comment]
This happens for us as well. We're using the embedded version, no selfhosting or api.

**Comment by PeerRich** [comment]
i dont see this being reported often. is this been resolved? can someone check?
