### ISSUE TITLE
[CAL-1243] Public booking form: Remove placeholders

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7705]
![A7DCF1AA-20AB-493D-8D83-C1D96872A880.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/09c6c22d-f9c7-4c66-9530-729f5acf6aae/093b17a3-d7f0-4d58-ac03-8d4173d27d6c)

We should just remove these. People know what the expected values are here

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1243](https://linear.app/calcom/issue/CAL-1243/public-booking-form-remove-placeholders)</sub>

**Comment by HiMoritz** [comment]
I was hoping to work on this as my first open-source contribution, but I missed that this issue was already assigned. I have a solution working locally, should I still proceed and open a PR for review?

**Comment by PeerRich** [comment]
@HiMoritz yes please
