### ISSUE TITLE
Manage user or disable option

### ISSUE THREAD

**Issue by rvmadeit** [calcom/cal.com#7707]
Hi, I'm on self-hosted, is there a way to manage user and disable user to create account ?

**Comment by PeerRich** [comment]
do you want to disable account creation for everyone?

**Comment by rvmadeit** [comment]
Yes I want to disable this option and if possible create user with admin panel because when I click on user's settings I'm redirected to the plan price page

**Comment by PeerRich** [comment]
#7459 #7304

**Comment by zomars** [comment]
> we are adding feature flags soon. disabling account creation can be one flag @zomars

That could work. Will update my PR.
