### ISSUE TITLE
When using EMOJI as username Avatar breaks 💀

### ISSUE THREAD

**Issue by McPizza0** [calcom/cal.com#7718]
### Issue Summary

When the username is set to an emoji, the user's avatar fails to load.
Looking at the network calls, it seems that the avatar is downloaded twice, with the version from Gravtar failing to load.

This could be due to the encoding of the emoji to gravtar url

### Steps to Reproduce

1. Set username to an emoji
2. Avatar in account/public page is no longer loading

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Only tested with single character (emoji) username https://cal.com/🍕
Has not been tested with usernames with mixed alphanumeric + emoji (e.g. McPizza🍕)

### Technical details

N/A - applies across browsers

_`P.S. Very low priority`_

**Comment by PeerRich** [comment]
ahhhh i know why. we add it to the route, as in https://app.cal.com/peer/avatar.png which means the emoji will cause issues.

should be a simple fix, we need to strip emojis for that endpoint

**Comment by PeerRich** [comment]
@G3root wanna look into this?

**Comment by PeerRich** [comment]
agree low priority

**Comment by PeerRich** [comment]
i dont even know how many people use emojis as usernames. must be max. a handful

**Comment by McPizza0** [comment]
Yup, very very rare use case, but could have implications elsewhere

Potentially a good first issue/contribution?

**Comment by abdallahalsamman** [comment]
@jgimitola same here. it should be happening because of the `slugify` call.
<img width="896" alt="image" src="https://user-images.githubusercontent.com/12014839/229716152-c409260d-769b-4c8a-b2d8-d62bd27ddd52.png">

@McPizza0 can you still reproduce this issue?

**Comment by McPizza0** [comment]
> @McPizza0 can you still reproduce this issue?

Yes, still able to reproduce
I'm using Cloud version with the following steps:

Go to Settings
Enter 🍕 as username (Requires Premium and reserved usernames subscription)
1st save didnt work correctly (showed "--" as username after save)
2nd save worked
Navigate to cal.com/🍕 - Avatar is missing


p.s. please note that I now use the username /mc due to this and other issues

**Comment by abdallahalsamman** [comment]
@McPizza0 I can't test it out on prod since I don't have a premium account.

**Comment by bhumit070** [comment]
Hi, @PeerRich I think encoding emojis would be a nice one,
But I suggest that we put validations to only allow combinations of name and numbers usernames what do you think?

**Comment by pranjalg13** [comment]
Hey I am thinking to modify the slugify regex to update the emoji, it is working local. Working on getting a PR ready.

cc: @PeerRich

**Comment by pranjalg13** [comment]
@AyushMainali123 can we ensure if there is an open pr for an issue not to raise another one 👍 ?

**Comment by McPizza0** [comment]
@PeerRich How about just blocking emoji's from the name?
People who have it can keep, but new ones won't work.
Zod recently introduced `string().emoji()`
Perhaps we can do some Zod validation on the input to check if it contains an emoji, and if it does, fail the parsing?
