### ISSUE TITLE
[CAL-1248] A utility to validate the variables across all languages for all strings.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7721]
I think we should be able to write a utility that can ensure that a string has the same variables in all languages. I have seen this kind of language-specific issue many times. It's difficult to identify during testing and only the users who use the language end up facing the issue.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/7720#discussion_r1135480419_
            

<sub>[CAL-1248](https://linear.app/calcom/issue/CAL-1248/a-utility-to-validate-the-variables-across-all-languages-for-all)</sub>

**Comment by Udit-takkar** [comment]
maybe we can use this https://www.npmjs.com/package/typesafe-i18n#typesafety
