### ISSUE TITLE
[CAL-1252] Facetime app not accessible on cal.com

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7724]
Well this should ideally be accessible on app as the PR is merged. I checked local and it's there.

Something wrong on production. Maybe app seed didnt' run on production <@U02BS9YFFL7>

[Slack Message](https://calendso.slack.com/archives/C01NXDSRY9W/p1678095576850579?thread_ts=1678092772.129469&cid=C01NXDSRY9W)

<sub>[CAL-1252](https://linear.app/calcom/issue/CAL-1252/missing-facetime-app-seed-on-production)</sub>

**Comment by PeerRich** [comment]
maybe its disabled via admin?

**Comment by PeerRich** [comment]
no its enabled 

![CleanShot 2023-03-14 at 20 03 29@2x](https://user-images.githubusercontent.com/8019099/225110490-442c271d-
2bf6-4572-a662-8bd3ba1cb1a2.jpg)
