### ISSUE TITLE
[CAL-1302] Inviting an Email Address to Your Team via API

### ISSUE THREAD

**Issue by agreea** [calcom/cal.com#7733]
### Is your proposal related to a problem?

Yes

### Describe the solution you'd like

We'd like to automate onboarding new teammates, including inviting them to our Cal.com team. Currently if you do it manually, it calls Cal.com's TRPC API. Is there a way to expose this same functionality via the Developer API? You'd just need to send up a payload like:
```
{
  email: "name@example.com",
  teamId: 1
}
```
It would only work if you were an Admin of the team, of course.

### Describe alternatives you've considered

Manually inviting the user, which requires an additional interface + context switch as part of the onboarding process.

### Additional context

<sub>[CAL-1302](https://linear.app/calcom/issue/CAL-1302/inviting-an-email-address-to-your-team-via-api)</sub>

**Comment by PeerRich** [comment]
good point, will forward to the team!

**Comment by zomars** [comment]
Right now there's no specific "invite" endpoint. You can create a [new membership for existing users](https://documenter.getpostman.com/view/20666831/Uz5ArJni#d97a48f5-cd17-44ef-8a4f-61b22a4960c1) tho:

```js
{
  userId: 1,
  teamId: 1
}
```
