### ISSUE TITLE
[CAL-1264] Booking Questions - Unable to remove duplicates

### ISSUE THREAD

**Issue by tylerdh12** [calcom/cal.com#7737]
### Issue Summary

In the past, a location boolean was added to the fields that were added as a booking question. As the user wanted to add a question for the user to enter the actual address they created a new field with the same name (location). Now the location questions are not able to be modified or removed. 

### Steps to Reproduce

1. Navigate to a Booking
2. Select the Advanced option from the left navigation
3. Scroll to the Booking Questions section
4. I currently have 2 questions that are labeled location (You may not as this was added before some of the newer functions that now allow you to create more custom question fields).
5. If you change anything within the booking it displays an error toast "BAD_REQUEST: Duplicate booking field name: location"
6. Unfortunately I am not able to edit, remove, or disable either of the duplicated fields. 

This is demonstrated in the video here:
https://share.icloud.com/photos/042ja6dgV9x3JI8qOMmwYK36Q

Safari Version 16.3 (18614.4.6.1.6)

<sub>[CAL-1264](https://linear.app/calcom/issue/CAL-1264/booking-questions-unable-to-remove-duplicates)</sub>

**Comment by Udit-takkar** [comment]
@tylerdh12 what is cal user name and booking link for this event type ?

**Comment by tylerdh12** [comment]
Username: champmassageBooking 1: https://cal.com/champmassage/30-minute-equine-assessmentBooking 2: https://cal.com/champmassage/60-minute-equine-massageOn Mar 15, 2023, at 6:43 AM, Udit Takkar ***@***.***> wrote:﻿
@tylerdh12 what is cal user name and booking link for this event type ?
