### ISSUE TITLE
Workflows don't send emails

### ISSUE THREAD

**Issue by druwadi** [calcom/cal.com#7739]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I've created a 15 minute calendar event, and attached a very basic workflow that will send a custom email to the participant 10 minutes before the event starts. The issue is when testing this, or having others test my link, we are never receiving the emails for the reminders via the workflow. It is not in spam nor in my main inbox. It seems like either the cron is not sending the email at all or perhaps some additional documentation is needed. 

<img width="1159" alt="Screen Shot 2023-03-14 at 11 38 56 PM" src="https://user-images.githubusercontent.com/10395129/225200435-b6c40096-5d3f-4aeb-b609-58a3b306e599.png">

<img width="1155" alt="Screen Shot 2023-03-14 at 11 39 21 PM" src="https://user-images.githubusercontent.com/10395129/225200479-c817ef57-945a-4944-a39c-d69d25bd00d5.png">

### Steps to Reproduce

1. Navigate to https://cal.com/david-ruwadi-ii-omaw4h/15min
2. Sign up for a 15 minute meeting, a email should arrive 10 minutes prior as a reminder. (no email arrives)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I can help debug this further if there is an api endpoint or UI area where I can monitor outgoing emails for my workflows.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

I don't think the browser version is necessary since the workflow piece is handled via Cal.com's backend presumably, but can update if necessary.

**Comment by CarinaWolli** [comment]
When you tested the workflow email, was the workflow email scheduled less than 1 hour away? Because currently workflow emails can only be scheduled more than 1 hour in advance. 

I tested my workflow, and I received the email. I will try to find another solution to also schedule workflow emails that are sent within 1 hour

@druwadi please let me know if that was the case for you

**Comment by druwadi** [comment]
Hi @CarinaWolli can confirm booking > 1hr works. Thanks for the tip there! Going to close this out since other issues seem to be more of a priority.
