### ISSUE TITLE
[CAL-1256] No way to exit Editor when in dialog

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#7740]
[d017b396-0927-4d23-aa31-5efcabe2e0c0](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9cd7293-c869-4fa8-a304-487d0a9167d4/d017b396-0927-4d23-aa31-5efcabe2e0c0)

Pressing escape closes dialog and does not leave focus from the editor

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1256](https://linear.app/calcom/issue/CAL-1256/no-way-to-exit-editor-when-in-dialog)</sub>

**Comment by rayyanQ** [comment]
Can I take on this issue?
