### ISSUE TITLE
[CAL-1262] /bookings Date time is flipped

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7747]
EDIT: this could be a DST bug, not a display bug

[https://app.cal.com/bookings/upcoming](https://app.cal.com/bookings/upcoming)

Weird Date Formatting:
Why is 3:30 PM - 2:45 PM mixed? Is this a regression?

![CleanShot 2023-03-15 at 13.58.13@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bb116c4f-3ae9-4992-b9a3-903ff14ad1a9/dcd776f1-fc29-4b20-91a6-9184b1a18f55)

Created via Threads. See full discussion: [https://threads.com/34455940013](https://threads.com/34455940013)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1262](https://linear.app/calcom/issue/CAL-1262/bookings-date-time-is-flipped)</sub>

**Comment by PeerRich** [comment]
@gitstart-calcom unassigned you

**Comment by roae** [comment]
fixed on #7792 included on v2.7.1
