### ISSUE TITLE
[CAL-1263] booking questions (formerly additional inputs) need full width not coluns

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7748]
for all additional inputs (now called booking questions) we should make it full width and not columns

now:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d26a2be4-2aa0-4670-b50c-195a328e034e/0dd830a0-b636-4487-a0b9-df7ed7319e37)

should be:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c2b5d177-a254-4d19-9406-a2398204dcb7/a2864eb7-a4a9-40ba-bc12-e3605ec2c7f1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1263](https://linear.app/calcom/issue/CAL-1263/booking-questions-formerly-additional-inputs-need-full-width-not)</sub>

**Comment by hariombalhara** [comment]
This was intentionally done here https://github.com/calcom/cal.com/issues/7492. @Jaibles can you confirm if this is how you want it? This is a valid problem when field has a long label.
