### ISSUE TITLE
[CAL-1266] Improve UX on away toggle

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#7749]
[cad99e55-b438-4e8a-935a-a43a3c92e3d9](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/eace4853-6ea0-43f5-b55d-e9c9a6ba63dc/cad99e55-b438-4e8a-935a-a43a3c92e3d9)

Currently there is a massive delay as the request is sent on click then updated on the trpc refetch. This should be handled by local state then an error toast if it fails for some reason

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1266](https://linear.app/calcom/issue/CAL-1266/improve-ux-on-away-toggle)</sub>

**Comment by joeshajan** [comment]
Hey, @sean-brydon I would like to fix this. Can you assign this to me?

**Comment by PeerRich** [comment]
assigned @joeshajan

**Comment by harshsinghatz** [comment]
:/ I missed the conversation here, my bad!

**Comment by joeshajan** [comment]
It's ok @harshsinghatz . Since you are almost done with the issue. I'm unassigning myself.
