### ISSUE TITLE
[CAL-1268] Update embed e2e commited snapshots

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7757]
Right now the commited snapshots are suffixed with `-darwin` since they we're generated in macos but the CI ones are generated on linux. Causing them to fail.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1268](https://linear.app/calcom/issue/CAL-1268/update-embed-e2e-commited-snapshots)</sub>

**Comment by hariombalhara** [comment]
I am not testing snapshots. Could never get it to work as actual screenshots should also be generated in CI. Was using `--update-snapshots` to run the tests.

I will just remove snapshotting for now, it's dead code any way.
