### ISSUE TITLE
Incorrect translation when canceling the appointment (german)

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7760]
Wrong German translation when canceling the meeting. Instead of "Egal" it should say "Abbrechen". "Cancel this appointment" can then be shortened to "Termin absagen" so that both buttons still fit next to each other.
"Egal" doesn't make that much sense in German, in this context.

![IMG_8612](https://user-images.githubusercontent.com/126205884/225469454-f06b61bc-6429-418f-8330-7a7a23a30e6d.jpg)

However, on the booking confirmation page (and the associated email), "Neuplanen oder Abbrechen" should then be changed to "Neuplanen oder Absagen" so that there is no confusion due to the previous change.

![IMG_8613](https://user-images.githubusercontent.com/126205884/225469472-349bbffe-2a6a-4284-8878-ffe028b60d55.jpeg)

**Comment by PeerRich** [comment]
will fix! great feedback

**Comment by PeerRich** [comment]
done! will be live next minor release
