### ISSUE TITLE
[CAL-1271] Missing asterisk for phone number in booking form

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7761]
An asterisk is missing at the end to mark the mandatory information. "Telefonnummer Teilnehmer*in" should also be renamed to "Telefonnummer".

<img width="464" alt="Bildschirm­foto 2023-03-16 um 01 05 14" src="https://user-images.githubusercontent.com/126205884/225474346-9f74f581-0d64-4565-ab20-a97d82e87a66.png">

<sub>[CAL-1271](https://linear.app/calcom/issue/CAL-1271/missing-asterisk-for-phone-number-in-booking-form)</sub>

**Comment by Udit-takkar** [comment]
@RainerZufall9393 have you only added phone number in event type location?

**Comment by RainerZufall9393** [comment]
Yes, the phone number oft the attendee is the only location at this event. @Udit-takkar

**Comment by Udit-takkar** [comment]
should be fixed by https://github.com/calcom/cal.com/pull/7734
