### ISSUE TITLE
Dropdown fields "bounce" when clicked.

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7762]
Dropdown fields "bounce" when clicked. Not sure if this is how it is supposed to be. Occurs in the booking forms, but also in the routing forms and the dashboard.

https://user-images.githubusercontent.com/126205884/225476243-9278ba01-4aaa-446c-8ed4-2d2f6d1962d6.mov

https://user-images.githubusercontent.com/126205884/225476270-fd4848e7-86ce-4c6e-91ae-3fcbec1d34b4.mov

**Comment by emrysal** [comment]
@PeerRich - guess we figured out what `h-` was doing.

**Comment by Vicolas11** [comment]
Can this task be assigned to me?

**Comment by Vicolas11** [comment]
Nothing is showing on the workflow page. I need to access it so I can see the bouncing Dropdown field.
![Error](https://user-images.githubusercontent.com/46172140/226899005-1ed1c26a-9474-45bb-a1f0-9a95379c4715.JPG)

**Comment by PeerRich** [comment]
you dont need access to workflows to test this. the input component is the same

**Comment by PeerRich** [comment]
you can test it on the booking page: localhost:3000/pro

**Comment by Vicolas11** [comment]
Alright. Thanks

**Comment by Vicolas11** [comment]
This is what I got. I am not seeing what I wanted.

![Error](https://user-images.githubusercontent.com/46172140/227372353-da508cca-239a-421f-b805-408bcd2ea832.JPG)

**Comment by Vicolas11** [comment]
I though as much too. Thanks

**Comment by abdallahalsamman** [comment]
@PeerRich can we close this issue if it's really fixed?
