### ISSUE TITLE
[CAL-1272] updating password ui bug

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#7775]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

1) go to http://localhost:3000/settings/security/password enter old password and new password
2) if you clicked update when both old password and new password you would see error message as expected but even if you change the new password . you are not able to update password.

https://user-images.githubusercontent.com/53316345/225638285-e4d57b84-741f-41dc-98fc-3b9d03a093de.mov

<sub>[CAL-1272](https://linear.app/calcom/issue/CAL-1272/updating-password-ui-bug)</sub>

**Comment by joeshajan** [comment]
Hey, @Udit-takkar are you working on this? If not I would like to work on this. Can you assign this to me?
