### ISSUE TITLE
[CAL-1273] Outlook Calendar connection expires?

### ISSUE THREAD

**Issue by asalvi0** [calcom/cal.com#7777]
### Issue Summary

Outlook Calendar connection seems to be expiring or lost after some time(it usually takes a couple of hours).

### Steps to Reproduce

1. Go to Settings -> Calendars
2. Add a Calendar -> Select **Outlook Calendar**
3. Authenticate with your MS account
4. The calendars will be listed and connection is successful, appointments are added to the calendar.

After some time, the calendar connections are empty and appointments are no longer added to the calendar, so I have to remove and add it again:

![image](https://user-images.githubusercontent.com/775410/225646311-e9467fbf-c2d5-40c5-84a9-a770ad80169b.png)

<sub>[CAL-1273](https://linear.app/calcom/issue/CAL-1273/outlook-calendar-connection-expires)</sub>

**Comment by Udit-takkar** [comment]
cc: @joeauyeung

**Comment by joeauyeung** [comment]
@milospuac I know you created a message but I want to track it here. I made a fix for this here: [https://github.com/calcom/cal.com/pull/7805](https://github.com/calcom/cal.com/pull/7805).

Please let me know if this is still happening after the PR is on prod.

**Comment by JohanForngren** [comment]
I'm experiencing the same issue, will test as soon as it's live.

**Comment by emrysal** [comment]
Hi @JohanForngren This fix just went live 🚀

**Comment by JohanForngren** [comment]
It reconnected without me having to re-auth. Seems promising! I'll wait a few days before marking the issue as resolved to give it a change to expire again.

Thanks for your hard work!

**Comment by asalvi0** [comment]
Same, here. Still connected after days of not doing it manually.

Thanks for the great work.

**Comment by PeerRich** [comment]
we shipped 2.7.2 which I believe fixed this, can y'all try?

**Comment by dominikfoldi** [comment]
I am on v.2.7.6-h-ce and the issue still persists. My personal Outlook calendar disconnects. It is connected to two different cal.com accounts (one is a company-wide and the other is personal), this information might also help with the investigation.

**Comment by PeerRich** [comment]
@joeauyeung can you reinvestiage this?

**Comment by joeauyeung** [comment]
> @joeauyeung can you reinvestiage this?

Can I get some context? PR https://github.com/calcom/cal.com/pull/7805 is live and should have fixed the issue. I haven't heard anything new about the connection expiring.

**Comment by asalvi0** [comment]
Hi @joeauyeung I think the issue was fixed with #7805, after several weeks my Outlook calendar connection hasn't expired.
