### ISSUE TITLE
[CAL-1290] Make it necessary to enter a reason for canceling the appointment

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7780]
Your new update makes it possible to require the reason to reschedule the event. Can you do the same for the reason of cancellation of an event? So far, this is still completely optional.

<img width="702" alt="Bildschirm­foto 2023-03-16 um 17 24 20" src="https://user-images.githubusercontent.com/126205884/225690641-e4b4f529-af10-43b5-a4ab-183ea9bb3e5e.png">

<sub>[CAL-1290](https://linear.app/calcom/issue/CAL-1290/make-it-necessary-to-enter-a-reason-for-canceling-the-appointment)</sub>

**Comment by PeerRich** [comment]
yes, great idea. @hariombalhara can add that!

**Comment by hariombalhara** [comment]
The cancellation page isn't powered by Form Builder right now. Will need to first do that and it would add Cancellation Reason to list of Booking Questions. Then, I will be able to mark this field as required.

**Comment by hariombalhara** [comment]
@Jaibles I would be showing **Reason for Cancellation** in the Booking Questions as part of this task. What would be the appropriate place for it there.

**Comment by hariombalhara** [comment]
The PR blocking it is still in review with low priority. Moving it to 3.1
