### ISSUE TITLE
[CAL-1279] Availability Timezone Not Auto Updating

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#7790]
When a user updates the timezone within an availability, it doesn't automatically display on the main availability page. You need to refresh the page for the changes to show.

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=d6811ff2-73e9-4a81-a118-01a2d7f10b64](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=d6811ff2-73e9-4a81-a118-01a2d7f10b64)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1279](https://linear.app/calcom/issue/CAL-1279/availability-timezone-not-auto-updating)</sub>

**Comment by joeauyeung** [comment]
Can you create a video? I can't replicate this.

**Comment by shirazdole** [comment]
Lol it's working now 😅
