### ISSUE TITLE
Can not book an appointment

### ISSUE THREAD

**Issue by erarta** [calcom/cal.com#7793]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I switched off my daily calendar availability at all (monday - sunday are off). I added overrides with custom availabitlity.

### Steps to Reproduce

1. go to https://cal.com/doctor-dubskaya/60min
2. Choose the date and click on time available
3. Enter name, phone, email, reason for appointment
4. Click book appointment
5. You get the message "Can not book an appointment, try again later" with not particular reason

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
Chrome latest. Tried different browsers, firefox and safri
- Node.js version
- Anything else that you think could be an issue.

**Comment by erarta** [comment]
Guys please help me, need this to work asap.

**Comment by PeerRich** [comment]
@roae @emrysal

**Comment by erarta** [comment]
Ok, I figured out one thing...

I was able to book event if I enable all days of week with some time range. 
The problem is that I don't have some specific weekdays enabled for booking every week. I only have some specific (and changing) dates every month that I want to be booked at some time.

How can I do it guys?

If I disable all week for the event and then try to override for example one date in month that I want to be booked I will not be able to book because probably system thinks I have that day disabled in my weekdays.

Do you get I what I mean? How can I overcome?

Really appreciate your time and help.

**Comment by Veercodeprog** [comment]
is this assigned to coworkers only?
if not , i can work on this provided some more details about it
