### ISSUE TITLE
[CAL-1282] Characters ignored in the username field - can't sign up

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7794]
SIU: Sign up broken

Created via Threads. See full discussion: [https://threads.com/34456589429](https://threads.com/34456589429)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1282](https://linear.app/calcom/issue/CAL-1282/characters-ignored-in-the-username-field-cant-sign-up)</sub>

**Comment by PeerRich** [comment]
resolved yesterday
