### ISSUE TITLE
[CAL-1692] 500 error while cancelling event

### ISSUE THREAD

**Issue by erarta** [calcom/cal.com#7795]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Book any date and get confirm email
2. Click on cancel booking
3. Write a reason and click cancel button
4. See error 500 with message unable to delete the booking

Here is the API request with 500 (I removed the token)

curl 'https://app.cal.com/api/cancel' \
  -X 'DELETE' \
  -H 'authority: app.cal.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://app.cal.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://app.cal.com/booking/dRbzKPMAbqX4NiPkYYXV7o?cancel=true&allRemainingBookings=false&(calEvent)=%3E%7B%0D%20%20%20%20return%20calEvent.attendeeSeatId%20?%20seatReferenceUid=$%7BcalEvent.attendeeSeatId%7D%20:%20%22%22;%0D%7D' \
  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' \
  --data-raw '{"id":279761,"cancellationReason":"","allRemainingBookings":false}' \
  --compressed

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

<sub>[CAL-1692](https://linear.app/calcom/issue/CAL-1692/500-error-while-cancelling-event)</sub>

**Comment by PeerRich** [comment]
can you try again? I think this has been fixed in 2.7.2

**Comment by Udit-takkar** [comment]
@erarta are you still facing any issue?

**Comment by edubskiy** [comment]
Hey, Yes, I am.

Steps are the same.
 - I book a date (any date)
 - I got email with confirmation
 - I click on cancel link
 - I see confirmation for cancellation and cancel button
 - I click cancel button
 - I see 500 error message,  although I see that event has been removed from my calendar successfully. 

I have users constantly asking me about this error... Can you please fix it?

**Comment by erarta** [comment]
Hey, Yes, I am.

Steps are the same:
- I book a date (any date)
- I got email with confirmation
- I click on cancel link
- I see confirmation for cancellation and cancel button
- I click cancel button
- I see 500 error message, although I see that event has been removed from my calendar successfully.
- I have users constantly asking me about this error... Can you please fix it?

**Comment by erarta** [comment]
I have tried myself and was able to reproduce the issue above.

**Comment by erarta** [comment]
Just got the same error today (500), here is the cURL (token is removed). Can you track and fix?

curl 'https://app.cal.com/api/cancel' \
  -X 'DELETE' \
  -H 'authority: app.cal.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://app.cal.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://app.cal.com/booking/wSsJomRcPRDVbHKYosd5ww?cancel=true&allRemainingBookings=false&(calEvent)=%3E%7B%0D%20%20%20%20return%20calEvent.attendeeSeatId%20?%20seatReferenceUid=$%7BcalEvent.attendeeSeatId%7D%20:%20%22%22;%0D%7D' \
  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' \
  --data-raw '{"uid":"wSsJomRcPRDVbHKYosd5ww","cancellationReason":"","allRemainingBookings":false}' \
  --compressed

**Comment by Udit-takkar** [comment]
@erarta can you send your booking url for this event type ?

**Comment by erarta** [comment]
Sure, this one `https://cal.com/doctor-dubskaya/60min?duration=60`

**Comment by erarta** [comment]
Hey there. Just want to follow up here, is there any update guys?

**Comment by erarta** [comment]
Any update?

**Comment by erarta** [comment]
@PeerRich can you please take a look?

**Comment by PeerRich** [comment]
i zhink this has been fixed, can you try again?
