### ISSUE TITLE
Conflict checks stopped working

### ISSUE THREAD

**Issue by dschuermann** [calcom/cal.com#7796]
### Issue Summary

I am using CalDAV with mailbox.org and cal.com is no longer recognizing recurring events from mailbox.org as blocked. So now I need to reschedule a lot of things :/

This worked before!

### Steps to Reproduce

1. Go to https://www.heylogin.com/call/dominik
2. You'll see that you can book Fridays in my calendar, but Fridays are fully blocked with recurring events
3. Individual events (for example 17-19th April) are recognized correctly

![image](https://user-images.githubusercontent.com/321888/225862651-12a93ed9-2503-4e85-8f70-a3393dc09699.png)

**Comment by dschuermann** [comment]
I now blocked Mondays and Fridays in cal.com using the availability function. But this needs to be fixed, if not I will probably stop using cal.com

**Comment by PeerRich** [comment]
caldav is still in beta and I am not even sure if mailbox.org is fully supported yet

**Comment by PeerRich** [comment]
but given you said it worked before I am tagging @alishaz-polymath to look into this asap!

**Comment by dschuermann** [comment]
thanks @PeerRich . It definitely worked before.

**Comment by PeerRich** [comment]
ok thank you for the report. we will investigate asap

**Comment by alishaz-polymath** [comment]
Hey @dschuermann 
I can see Fridays greyed out on my end. Can you please confirm if you have added other events to manually take care of blocking them or if the issue has somehow subsided?

**Comment by dschuermann** [comment]
@alishaz-polymath yes I disabled Mondays and Fridays in cal.com availability itself, without using my calendar.

**Comment by alishaz-polymath** [comment]
Thank you. I'll take a look at this today
