### ISSUE TITLE
[CAL-1284] Cleanup destination calendar components

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#7798]
We have three for some reason?

From what i can see they all do the same thing 

![CleanShot 2023-03-17 at 17.39.22@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7c3f41f7-d28e-4eb1-8a60-0b33bfdd8ca5/3e36f2ed-f9c3-4bb9-bf96-ff1038c64830)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1284](https://linear.app/calcom/issue/CAL-1284/cleanup-destination-calendar-components)</sub>

**Comment by Vicolas11** [comment]
Can this issue be assigned to me, please?

**Comment by PeerRich** [comment]
assigned you @Vicolas11
