### ISSUE TITLE
Pass meeting details in query or body to redirection URL

### ISSUE THREAD

**Issue by pbdco** [calcom/cal.com#7802]
If post-reservation URL redirection is enabled, it would be VERY important to OPTIONALLY pass all the meeting details to the URL, in the query or body.

Currently, the only parameters that are passed in the query are the following:

```
isSuccessBookingPage:true
email:example@email.com
eventTypeSlug:secret
```

This should include also meeting date, question responses, etc. (The same way as calendly does).

Additionally, it would be great to CONFIGURE the DELAY of the redirection. Currently the redirection is donde after 10 or more seconds after the confirmation page is shown. This is way TOO much, before the redirection occurs probably the user has closed the window. 
Ideally the seconds of the redirection should be configurable from admin settings.

**Comment by titanventura** [comment]
would like to sign up for this. Please assign !

**Comment by pbdco** [comment]
@titanventura In my opinion, having the option to enable or disable completely the feature (to pass the arguments to URL) would be more than enough. 

If enabled: it should pass all the available arguments and details from the meeting to the redirect URL.
If disabled: do not pass any argument at all to the redirect URL.

Have you got the chance to look into the delay configuration feature for the redirection as well? 
Thanks in advance for you collaboration!

**Comment by titanventura** [comment]
I feel like these parameters are enough to be passed extra

- title
- description
- customInputs
- responses
- startTime
- endTime
- location
- metadata
- user object
- attendees.

What is your opinion ?

To answer to your previous question, Sure, will take the redirection config feature as a part of this PR !

**Comment by hariombalhara** [comment]
I am wondering why would someone want to disable passing those query params?

**Comment by pbdco** [comment]
In my case, it is not 100% necessary.. it is much more important to have the params passed at least :) 
But I think its always a good idea to add a feature toggle to enable or disable it when possible, specially when the feature is new.. Maybe it could break someone's integration based on the params body, or similar.. but I'm just guessing.

**Comment by pbdco** [comment]
@hariombalhara that's a good point. A good alternative would be to POST the params data on the body of the request.
The URL that should be requested could be configurable... but in some way this feature should be available, it is a very basic feature.

**Comment by pbdco** [comment]
Hey @titanventura @hariombalhara , any news?
