### ISSUE TITLE
Cancellation page shows "Nameless" instead of the attendee name (+ bonus cosmetic snag)

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#7817]
### Issue Summary

When cancelling a booking with the cancellation link sent to the attendee, the attendee's name is displayed as "Nameless"

![](https://i.imgur.com/ZrHBeT8.gif)

Also note Giphy is enabled for the event type shown above & it appears to render incorrectly.

### Steps to Reproduce

1. Book event
2. On the confirmation page, click the cancel button
3. Observe the above behavior

**Comment by PeerRich** [comment]
@Udit-takkar can you look into this?
