### ISSUE TITLE
Disable branding doesn't remove Cal.com from page title (regression)

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#7818]
good point! we'll see how we can fit that into the roadmap 🙏

_Originally posted by @PeerRich in https://github.com/calcom/cal.com/issues/1290#issuecomment-993644795_

This bug appears to have regressed #1290

**Comment by PeerRich** [comment]
interesting, is that true for every page?

**Comment by ChipWolf** [comment]
Seems to @PeerRich
