### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by rishab22** [calcom/cal.com#7825]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. When I log in to my application the popup appears and stays on top of the page. Even my password length is 18 characters.
    You are set as an admin but you do not have a password length of at least 15 characters

- 
![image](https://user-images.githubusercontent.com/13703887/226167115-9b57cf4c-227e-4aef-a76a-339e2953f68f.png)

**Comment by PeerRich** [comment]
ah I believe you are missing 2FA. I am working on a better banner right now. can you try adding 2FA?

**Comment by PeerRich** [comment]
renamed! should go live this update
