### ISSUE TITLE
[CAL-1291] Email contains User Added question response as undefined

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7829]
<img width="760" alt="Screenshot 2023-03-20 at 12 49 16 PM" src="https://user-images.githubusercontent.com/1780212/226272070-984b0309-2ccf-449a-87bb-9d71889cf7f1.png">

It happened when the field was marked hidden and wasn't prefilled.

<sub>[CAL-1291](https://linear.app/calcom/issue/CAL-1291/email-contains-user-added-question-response-as-undefined)</sub>

**Comment by piyushgarg-dev** [comment]
@hariombalhara Please check the PR #9240
