### ISSUE TITLE
[CAL-1295] Clicking a time on the Availability page doesn't do anything

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#7834]
Seems to happen sometimes, clicking a time slot does nothing.

<sub>[CAL-1295](https://linear.app/calcom/issue/CAL-1295/clicking-a-time-on-the-availability-page-doesnt-do-anything)</sub>

**Comment by G3root** [comment]
@emrysal you mean clicking this card right ?
![Screenshot 2023-03-21 at 13-51-36 Availability Cal com](https://user-images.githubusercontent.com/84864519/226551385-947aafdf-c9df-4221-a847-f7c4aec02c95.png)
