### ISSUE TITLE
[CAL-1296] MultiSelectCheckboxes should merge with Select

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#7836]
MultiSelectCheckboxes should merge with Select and should be controlled via variant prop. There is no real reason for us to make these two seperate things

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1296](https://linear.app/calcom/issue/CAL-1296/multiselectcheckboxes-should-merge-with-select)</sub>

**Comment by PeerRich** [comment]
assigning you, ok?

**Comment by Devansh-365** [comment]
If this issue is still open. Can you assign this to me? I am very interested in contributing to cal.com and exploring the code source from the day I found out about this.

**Comment by sean-brydon** [comment]
Hey @Devansh-365 feel free! Sorry i missed this in my inbox - Gimme a shout if you have any questions. 

We have a few selects that need cleaned up but the one we want to merge with is at 

packages/ui/components/form/select/Select.tsx

**Comment by ExplorerAadi** [comment]
Hey @sean-brydon & @PeerRich , I was working on this refactor but this is only implemented in workflows section and I cannot test it because accessing workflows need some license. Could you please help me out with it?
![image](https://user-images.githubusercontent.com/52901335/235234831-b78bef88-495d-46f9-833a-c49505a63457.png?raw=true)

**Comment by sean-brydon** [comment]
> Hey @sean-brydon & @PeerRich , I was working on this refactor but this is only implemented in workflows section and I cannot test it because accessing workflows need some license. Could you please help me out with it? ![image](https://user-images.githubusercontent.com/52901335/235234831-b78bef88-495d-46f9-833a-c49505a63457.png?raw=true)

Hey bud can you DM me on our slack or hit me up on [twitter](https://twitter.com/SeanBrydon13) DMs . I'll get this sorted for you

**Comment by ExplorerAadi** [comment]
@sean-brydon Thanks for the help, I have raised a PR with the refactor:
https://github.com/calcom/cal.com/pull/8623

**Comment by dhruvgupta0503** [comment]
@keithwillcode is the issue still open?
