### ISSUE TITLE
Conditional Event Locations

### ISSUE THREAD

**Issue by leoherzog** [calcom/cal.com#7837]
### Is your proposal related to a problem?

I work part-time remote and part-time in the office. I want to offer one event type, but make "in-person" options only available on certain days.

### Describe the solution you'd like

I wish I could go into an event's settings, and for each location option, specify what days of the week those are selectable. Google Meet? Every day. In-Person? Only these days.

### Describe alternatives you've considered

I could instead create multiple event types called "Test Meeting (In-Person)" and "Test Meeting (Virtual)" with different availability, but that clutters up my list of all event types by having two choices for each type.

**Comment by PeerRich** [comment]
i think that could be quite tricky to get the right UI for

**Comment by leoherzog** [comment]
As far as UI goes, I was picturing something like this.

![Conditional Event Locations Mockup](https://user-images.githubusercontent.com/5376265/226467194-9cd47888-f659-4544-b7e2-2bbd985bb51d.png)

**Comment by PeerRich** [comment]
this is interesting, but what if someone wants to be even more granular? 

not sure how many people want this

we need to be cautious not adding too many "niche" features

**Comment by PeerRich** [comment]
great mockup btw!

**Comment by leoherzog** [comment]
Upon further consideration, you guys already have a system in cal.com for building out availability... with Availabilities! Perhaps it makes more sense to have an option to assign multiple Availabilities per event type, dependent on location?

![location-specific-availability-mockup](https://github.com/calcom/cal.com/assets/5376265/eb39c9d1-33e9-4e00-9787-5c49208bdb8b)

**Comment by PeerRich** [comment]
i think for now i would recommend setting up one event type for location specific availability
