### ISSUE TITLE
Confirm button also in the branding color

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#7848]
Would be great if the "Confirm" button on the booking page would also be displayed in the branding color (settings). On the event cancellation page please do likewise.

<img width="289" alt="Screenshot 2023-03-20 at 21 18 10" src="https://user-images.githubusercontent.com/126205884/226455923-348655ab-7c1f-4b69-8ccf-5346f74e967d.png">

**Comment by PeerRich** [comment]
i think we had that once. should be easy!
