### ISSUE TITLE
[CAL-1298] Staging Signup seems busted

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7850]
thanks for the response @Peer! yea i've been paying for a production account since january but would like to get this working on `localhost` for testing. i can create new user accounts fine on \[app.cal.dev\]([http://cal.dev/signup|cal.dev/signup](http://cal.dev/signup%7Ccal.dev/signup)> but none of them can sign into [http://console.cal.dev|console.cal.dev](http://console.cal.dev%7Cconsole.cal.dev) via <[http://app.cal.dev](http://app.cal.dev)). it keeps telling me username or password is incorrect for multiple diff accounts i've created now trying to get signed in.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1298](https://linear.app/calcom/issue/CAL-1298/staging-signup-seems-busted)</sub>

**Comment by PeerRich** [comment]
we should add a sandbox inside of console.cal.com vs asking people to sign up for .dev IMO

**Comment by PeerRich** [comment]
or a 7 day trial cc @alannnc that should be easy to do with stripe
