### ISSUE TITLE
[CAL-1301] [CAL-1300] Dropdown action menu

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7854]
[Dropdown Action Menu Item Brief - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=1071%3A38976&t=Ky6UXnl5mQS1sHCf-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1300](https://linear.app/calcom/issue/CAL-1300/dropdown-action-menu)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1300](https://linear.app/calcom/issue/CAL-1300/dropdown-action-menu)</sub>

**Comment by sean-brydon** [comment]
@Jaibles Closing this as IIRC its fixed. 

we should tackle filters in a different issue
