### ISSUE TITLE
[CAL-1303] UI issues webhook list

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7857]
### Issue Summary

Badge has two lines when subscriber URL is short: 
<img width="387" alt="Screenshot 2023-03-21 at 12 16 36" src="https://user-images.githubusercontent.com/30310907/226590434-98d57c98-4f3f-44ce-8bdd-e08c6de61b89.png">

Long subscriber URL goes out of list and buttons are not visible anymore
<img width="306" alt="Screenshot 2023-03-21 at 12 17 57" src="https://user-images.githubusercontent.com/30310907/226590702-80cd3d38-31a9-455f-b863-43c8656ecef6.png">

We should truncate long subscriber URLs and use the FiMoreHorizontal button in mobile view to safe some space 
<img width="49" alt="Screenshot 2023-03-21 at 12 19 39" src="https://user-images.githubusercontent.com/30310907/226591040-9c8f9ee4-bd68-42c6-a2f4-0bdd1d81726d.png">

<sub>[CAL-1303](https://linear.app/calcom/issue/CAL-1303/ui-issues-webhook-list)</sub>

**Comment by PeerRich** [comment]
what should this button do:
![image](https://user-images.githubusercontent.com/8019099/226593524-2e5a9ca4-28fb-46bb-9dc3-08e973a8cbe6.png)

**Comment by CarinaWolli** [comment]
> what should this button do: ![image](https://user-images.githubusercontent.com/8019099/226593524-2e5a9ca4-28fb-46bb-9dc3-08e973a8cbe6.png)

Instead of the edit and delete:
<img width="331" alt="Screenshot 2023-03-21 at 12 51 43" src="https://user-images.githubusercontent.com/30310907/226598102-b31bf4ae-3721-4430-82a5-4578b4ec545a.png">

So it should open a dropdown with edit and delete

**Comment by PeerRich** [comment]
ah right!
