### ISSUE TITLE
[CAL-1310] deleting apple calendar throws error (still works tho)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7864]
![CleanShot 2023-03-21 at 16 37 54@2x](https://user-images.githubusercontent.com/8019099/226659381-7a9ece3e-a482-4033-9a1a-ab9efd1d83a0.jpg)

<sub>[CAL-1310](https://linear.app/calcom/issue/CAL-1310/deleting-apple-calendar-throws-error-still-works-tho)</sub>

**Comment by MayurAnklekar** [comment]
Hi @PeerRich, I tried to install Apple Calendar by going to Apps and clicking Install on Apple Calendar
I was asked to create an app-specific password, which I did
However, I am still not able to install it

<img width="1434" alt="Screenshot 2023-04-30 at 11 09 57 PM" src="https://user-images.githubusercontent.com/72290958/235367906-110eebdf-ca5f-4d61-81c7-02c3d2127ba0.png">

Am I missing something here?

**Comment by virinchimanepalli** [comment]
@PeerRich
hey is this still active? if yes could you assign it to me, please?

**Comment by PeerRich** [comment]
@virinchimanepalli no need to ask, go for it!

**Comment by alishaz-polymath** [comment]
Unable to re-create the issue. The Apple Calendar is removed normally without any errors 🤔 
Are there any steps I can follow to re-create the bug?

**Comment by alishaz-polymath** [comment]
Unable to re-create this, so closing it for now. Please feel free to re-open it if this is a mistake 🙏
