### ISSUE TITLE
Can't use admin...

### ISSUE THREAD

**Issue by CodebijSven** [calcom/cal.com#7866]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. I logged in on localhost:3000
2. I see the dashboard
3. I see the banner: "You cant use admin as your password is not 15+ caracters long" (not exactly because it is dutch.)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser Version: Google Chrome - 111.0.5563.65 (Version)
- Docker build

**Comment by PeerRich** [comment]
you need to set up 2FA, i have a PR open to mention that in the banner
