### ISSUE TITLE
Add Europe/Vienna to the time zones

### ISSUE THREAD

**Issue by fawadakram** [calcom/cal.com#7877]
### Is your proposal related to a problem?

It's a bit confusing using another country for the timezone.   Our customers will book from Vienna, Austria.
I'm using Europe/Amsterdam.  From a quick glance, when booking, it looks like the location is Europe/Amsterdam.

### Describe the solution you'd like

The time zone is the same as Amsterdam but having "Europe/Vienna" as an option is an easy thing to add and will make the booking form clearer for users in Austria.

**Comment by RainerZufall9393** [comment]
Europe/Berlin would also be great

**Comment by PeerRich** [comment]
Hey, we are using a library which has these as pre-defined. You can enter Vienna as a search and it'll show up the right time

**Comment by PeerRich** [comment]
will get in touch with the lib-maker and see if its possible

**Comment by PeerRich** [comment]
wont fix for now
