### ISSUE TITLE
[CAL-1316] Zapier for teams

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7886]
A team owner/admin should be able to create a Zapier API key which also triggers for all team event types.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1316](https://linear.app/calcom/issue/CAL-1316/zapier-for-teams)</sub>

**Comment by PeerRich** [comment]
![image](https://github.com/calcom/cal.com/assets/8019099/c1904f82-b8b8-4675-87ca-89a92b79d11a)
