### ISSUE TITLE
[CAL-1317] Some environment variables have to be added in .env.example

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#7887]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

some environment variables such as

1. GOOGLE_API_CREDENTIALS
2. GOOGLE_LOGIN_ENABLED

These variables have to added in .env file  as mentioned here [https://cal.com/docs/introduction/quick-start/self-hosting/install-apps/google](https://cal.com/docs/introduction/quick-start/self-hosting/install-apps/google) but these keys are not present in .env.example and it's not mentioned in the docs that these also have to be added in .env.appStore

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1317](https://linear.app/calcom/issue/CAL-1317/some-environment-variables-have-to-be-added-in-envexample)</sub>

**Comment by PeerRich** [comment]
still open I guess?
