### ISSUE TITLE
[CAL-1322] [CAL-1323] Availability time select - No options

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7897]
[8e6adbd6-c922-486f-b166-d2696237d855](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/97095a44-6aa7-4866-8776-3855d4ea0311/8e6adbd6-c922-486f-b166-d2696237d855)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1322](https://linear.app/calcom/issue/CAL-1322/availability-time-select-no-options)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1322](https://linear.app/calcom/issue/CAL-1322/availability-time-select-no-options)</sub>

**Comment by lapaz17** [comment]
Could not reproduce

**Comment by Jontes-Tech** [comment]
When editing a previous overwrite, the "begin" date of the first time slot is showing "No Options"
![image](https://github.com/calcom/cal.com/assets/84264740/7d1ff137-9136-42d4-8720-27278c7d8634)

I'm looking for a fix, but the temporary solution is to delete and readd the overwrite. Sucks, I know. I'm looking into a fix.
