### ISSUE TITLE
[CAL-1404] Error when canceling a booking

### ISSUE THREAD

**Issue by pavnaumenko** [calcom/cal.com#7904]
### Error when canceling a booking

When I cancel a meeting on a public link I am able to cancel it but I receive an error on UI
![image](https://user-images.githubusercontent.com/89968721/227276418-75694372-609d-4fe3-8ad7-a738c9f6795e.png)

### Steps to Reproduce

1. Open the event link
2. Create an event
3. Click on the "Cancel" button
4. Confirm cancellation

Expected: booking is canceled;
Actual: booking is canceled but with an error on UI.

On dev tools: 
![image](https://user-images.githubusercontent.com/89968721/227277346-cc2f1797-82d1-42c0-baf0-f3a463de2f15.png)

<sub>[CAL-1404](https://linear.app/calcom/issue/CAL-1404/error-when-canceling-a-booking)</sub>

**Comment by Udit-takkar** [comment]
@pavnaumenko can you send your booking url for this event type?

**Comment by PeerRich** [comment]
i think this has been fixed
