### ISSUE TITLE
Users cannot book appointments

### ISSUE THREAD

**Issue by chas-uk** [calcom/cal.com#7905]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Went to booking page, completed name, number, location etc
2. Went to book and it says 'Could not book the meeting. No available users found'
3. Admin can book however guests cannot

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by Udit-takkar** [comment]
@chas-uk can you send your cal booking link for this event type?

cc: @emrysal @roae

**Comment by PeerRich** [comment]
i think this has been fixed
