### ISSUE TITLE
[CAL-1321] Calendar list not loading in installed apps

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7906]
a user has installed google (based on the google calendar app store page it says "already installed") but when navigating to installed apps or settings it won't load

[https://app.birdeatsbug.com/sessions/3zxAWRnUUnTC2wzVMr841tD0twbDOh8tmvJj56hyq9ch](https://app.birdeatsbug.com/sessions/3zxAWRnUUnTC2wzVMr841tD0twbDOh8tmvJj56hyq9ch)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1321](https://linear.app/calcom/issue/CAL-1321/calendar-list-not-loading-in-installed-apps)</sub>

**Comment by Udit-takkar** [comment]
@PeerRich just tried this after impersonating the account. It took ~11 seconds

<img width="742" alt="Screenshot 2023-03-24 at 1 29 39 PM" src="https://user-images.githubusercontent.com/53316345/227459851-f4e71888-e8a0-4891-98ef-8580591987f4.png">

@alishaz-polymath does caldav integration took a lot of time to load ?

**Comment by victorpaleologue** [comment]
This morning the list showed up!
Did you change something?

**Comment by PeerRich** [comment]
probably. I think we should really add our "cached" calendar in between so we always call OUR  calendar not wait for other calendars @emrysal

**Comment by PeerRich** [comment]
> This morning the list showed up! Did you change something?

we released a new update yea! @victorpaleologue

**Comment by abdallahalsamman** [comment]
@PeerRich is this issue fixed?

**Comment by alishaz-polymath** [comment]
Hi @nopeee535 
The load time depends upon the CalDAV service provider you're using. If they respond slow, it'll take time as things stand. We're currently working on how we can improve this aspect. Your patience is appreciated 🙏
