### ISSUE TITLE
[CAL-1324] /availability - date overrides: Allow user to select multiple days

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7909]
[https://github.com/calcom/cal.com/assets/8019099/cc3ea8ba-2a3d-4c90-9b17-1d3256cf8ed4](https://github.com/calcom/cal.com/assets/8019099/cc3ea8ba-2a3d-4c90-9b17-1d3256cf8ed4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1324](https://linear.app/calcom/issue/CAL-1324/availability-date-overrides-allow-user-to-select-multiple-days)</sub>

**Comment by Just-Moh-it** [comment]
Hey! I'd love to take this on

**Comment by Just-Moh-it** [comment]
@mehuylsharma woah dude that was quick!

**Comment by emrysal** [comment]
This is a one-liner change once @CarinaWolli and I are done with the slot logic revamp (due this week) - assigned it to me to reflect this.

**Comment by mehuylsharma** [comment]
@emrysal I've opened a PR that's WIP should I close it in that case?

**Comment by emrysal** [comment]
Hi @mehuylsharma - No go ahead, your code looks good 👍 - bonus points if you can get the DatePicker to work with TypeScript 💯

**Comment by ologbonowiwi** [comment]
@mehuylsharma you still plan to work on this?

I want to check if it's ok I give it a try

**Comment by mehuylsharma** [comment]
@ologbonowiwi sure go for it :D

**Comment by ologbonowiwi** [comment]
How do I get access to linear to see the details @PeerRich?

**Comment by PeerRich** [comment]
> How do I get access to linear to see the details @PeerRich?

somehow the video URL broke, reuploaded
