### ISSUE TITLE
invalid_admin_password banner is always shown

### ISSUE THREAD

**Issue by alexgorbatchev** [calcom/cal.com#7914]
### Issue Summary

`AdminPasswordBanner` always shows `invalid_admin_password` (You are set as an admin but you do not have a password length of at least 15 characters) message.

This probably means that for whatever reason the password isn't being recognized/processed correctly, however I am able to login after changing the password.

### Steps to Reproduce

https://user-images.githubusercontent.com/65633/227329269-4fc58f5c-7b2e-4345-9726-7078970ed871.mp4

### Technical details

- Self hosted via [`docker.io/calcom/cal.com:latest`](https://hub.docker.com/r/calcom/cal.com)

**Comment by kolaente** [comment]
Same thing here after upgrading to 2.7.3. My password is 50 characters long.

**Comment by PeerRich** [comment]
i was attempting to fix this, you need 2FA on! the text is incorrect

**Comment by JACHES-EH** [comment]
Cant believe it, I was having the same issue, but with the 2FA on the message just disappeared. Thanks!

**Comment by olivierlambert** [comment]
Same issue here :)

**Comment by PeerRich** [comment]
this should be fixed
