### ISSUE TITLE
[CAL-1326] Transferring Account Ownership

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7925]
Be able to change Team Owner (who is billing partner) and move over Stripe Subscriptions accordingly

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1326](https://linear.app/calcom/issue/CAL-1326/transferring-account-ownership)</sub>

**Comment by PeerRich** [comment]
Actually, I think the easiest would be to be able to add a billing email inside the team settings. regardless of who the owner is

**Comment by PeerRich** [comment]
I realised you can already change billing email 

![CleanShot 2023-03-24 at 09 56 35@2x](https://user-images.githubusercontent.com/8019099/227472336-f263160a-6d45-4faa-b83e-a3df7a4e9aa6.jpg)


Account transfer would be nice too, but low priority

**Comment by PeerRich** [comment]
alternatively, is it possible to have more than one owner? That way an owner can make another member an owner and then turn themselves into a member

**Comment by zomars** [comment]
> alternatively, is it possible to have more than one owner? That way an owner can make another member an owner and then turn themselves into a member

It is possible for an owner to set another owner. But if the original owner leaves then there's no way to pass over the subscription since the payment methods belongs to the original owner.

**Comment by PeerRich** [comment]
is it possible to pass over the payment method to another owner?

**Comment by zomars** [comment]
> is it possible to pass over the payment method to another owner?

That's another can of worms I would not like to open. Is like sharing your credit card. Ideally we would prompt the new owner to set up a valid payment method.

**Comment by PeerRich** [comment]
fair point
