### ISSUE TITLE
[CAL-1335] move LOGO_URL into .env to make cal.com easier to customise

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7939]
(a) we could add LOGO_URL to .env and when set, replace [cal.com/logo](http://cal.com/logo)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9cee2c50-8e8a-46de-b041-4c7056978c73/cccd37c1-6b96-493f-84c3-327b31118ca7)

(b) we would need an image uploader when setting up the app and store the logo in the DB + have a way to change the logo inside the product (in the admin area)
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1335](https://linear.app/calcom/issue/CAL-1335/move-logo-url-into-env-to-make-calcom-easier-to-customise)</sub>

**Comment by zomars** [comment]
Related:
- https://github.com/calcom/cal.com/discussions/4244
- https://github.com/calcom/cal.com/issues/5998
- https://github.com/calcom/cal.com/issues/5830

Also I would rather save this data in the DB itself so it can be changed without a redeploy:

https://github.com/calcom/cal.com/issues/6014
