### ISSUE TITLE
bug x cross-site scripting on mail

### ISSUE THREAD

**Issue by alejandroaguilarhiguera** [calcom/cal.com#794]
I wrote the tag with an image in the name of the team then invited a contact
![image](https://user-images.githubusercontent.com/43346195/134938745-59497f94-e2c2-4cab-b7ef-183c4e7f49b5.png)

**Comment by Azhariel** [comment]
Tried to reproduce this error bug now I have some questions.
I set the user's display name and the team name as long `<img>` tags, but they weren't compiled shown as images on the email. This does show the issue of long strings being permitted as display name and team name, but that's another issue.

This was my result:
![image](https://user-images.githubusercontent.com/9439404/168931548-1933a16f-e6e7-488b-92cb-fbc430e5c615.png)

So my questions are:
1. Did the image show on your test? 
2. If they didn't, is this a security issue?
3. Should we disallow special characters for users and teams display names?
4. Should we implement a max length for those fields or just fix their display on the email?
