### ISSUE TITLE
[CAL-1336] Mobile: Menu position is broken

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7942]
![230C9D81-402B-4724-9AD5-192E4AD12F53.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3357f241-4f36-40b5-a7cd-c70d58ff56ac/1739bb8c-8a95-4957-8dd3-317233074f00)

The menu is not on the bottom of the screen. Tested on iphone. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1336](https://linear.app/calcom/issue/CAL-1336/mobile-menu-position-is-broken)</sub>

**Comment by PeerRich** [comment]
cant reproduce this
