### ISSUE TITLE
[CAL-1342] 404 when rescheduling booking with deleted event type

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7948]
When trying to reschedule a booking for which the event type was already deleted, /reschedule/\[uid\] throws 404  

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1342](https://linear.app/calcom/issue/CAL-1342/404-when-rescheduling-booking-with-deleted-event-type)</sub>

**Comment by G3root** [comment]
@CarinaWolli what should be the expected behaviour ?

**Comment by CarinaWolli** [comment]
Not sure to be honest, but I don't think it is good to link the user somewhere that throws 404. Maybe a message that this event type is not available anymore and a link to the user's profile with their event types? 

@Jaibles What do you think should happen? Or are we ok with a 404 in that case?
