### ISSUE TITLE
[CAL-1343] Webhooks and workflows not always firing with events with seats

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7950]
I tested the "Booking created" and "Booking cancelled" trigger for webhooks and both are not always firing for events with seats. I think "Booking created" is only firing when the first slot is booked

Same with workflows, "booking created" triggers only when the first seat is booked

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1343](https://linear.app/calcom/issue/CAL-1343/webhooks-and-workflows-not-always-firing-with-events-with-seats)</sub>

**Comment by alannnc** [comment]
Passing it to @CarinaWolli
