### ISSUE TITLE
[CAL-1345] Misaligned Booking Frequency toggle

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7954]
<img width="918" alt="Screenshot 2023-03-27 at 8 23 33 PM" src="https://user-images.githubusercontent.com/1780212/227977747-0cd138db-a063-450d-8eca-aa0640a2c47e.png">

<sub>[CAL-1345](https://linear.app/calcom/issue/CAL-1345/misaligned-booking-frequency-toggle)</sub>

**Comment by rafael-c-alexandre** [comment]
I'll take on this one as a way to get acquainted with the codebase, if that's okay!
