### ISSUE TITLE
[CAL-1346] Ensure that comma is removed during migration of custom inputs to Booking Questions

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#7955]
Fixed this particular issue. The bug occurred because the field `name` is having a comma, which `react-hook-form` doesn't work well with. I have just removed the comma from the two field names.

This happened because the fields were created as custom inputs and were migrated to new Booking Questions with name same as label.Followup would be ensure that during migration, **comma** is removed. We don't want to make any other modifications so that the we remain compatible with the data that we were posting earlier in webhooks

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/issues/7953#issuecomment-1485341418_
            

<sub>[CAL-1346](https://linear.app/calcom/issue/CAL-1346/ensure-that-comma-is-removed-during-migration-of-custom-inputs-to)</sub>

**Comment by PeerRich** [comment]
still open?

**Comment by hariombalhara** [comment]
I think we might not need it. Haven't seen any reports now. Maybe all custom inputs are already migrated to bookingFields and are in correct state now.
