### ISSUE TITLE
[CAL-1347] RFC: Export/Import your event type configurations

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#7956]
As discussed in the recent Roast me event. And now that Managed Events are almost ready to merge. It came to the discussion the possibility to export your current event type configurations.

This would help with many cases like:

* As a large team admin, I want to bulk export import event type for my team members so I can save time setting up my team
* As a experimenting user, I want to be able to backup my current setup so I can experiment without losing my last working setup.
* As a new user, I want to be able to use a previously shared template (Babershop, Therapist, etc.) to quickly setup my new account.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1347](https://linear.app/calcom/issue/CAL-1347/rfc-exportimport-you-event-type-configurations)</sub>

**Comment by PeerRich** [comment]
we should definitely add a "Templates" Section inside the App Store
