### ISSUE TITLE
[CAL-1348] improvement: throw a toast when adding a new member

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7958]
after this dialog:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d72f6684-7887-44f6-8ecf-4a1e59941910/903bb133-b230-476c-9c59-7e3bc429a220)

throw toast: "{email} has been invited"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1348](https://linear.app/calcom/issue/CAL-1348/improvement-throw-a-toast-when-adding-a-new-member)</sub>

**Comment by okanisildar** [comment]
If it's ok for you I can take this one

**Comment by Devansh-365** [comment]
Is this issue still open? If possible can you assign this to me?
