### ISSUE TITLE
[CAL-1349] Replace React-Icons with Lucide.dev

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7959]
We really only use Feather Icons from React-Icons and Lucide.dev is the successor of React Feathers.

while there is a PR open to add Lucide to React Icons, it's been open since September 2022 and I lost faith it'll get merged anytime soon.

https://github.com/react-icons/react-icons/pull/602

Is there any objections replacing react-icons with lucide.dev's react implementation? https://lucide.dev/docs/lucide-react

<sub>[CAL-1349](https://linear.app/calcom/issue/CAL-1349/replace-react-icons-with-lucidedev)</sub>

**Comment by GermaVinsmoke** [comment]
Hi @PeerRich 
Would like to work on this.
Can you tell what's the reason for replacing `react-icons` with `lucide-react`?

**Comment by PeerRich** [comment]
the reason is, that we want to use lucide for a long time but react-icons only ships with "feather icons" which is the unmaintained package. lucide.dev is the successor of react feather (including react feather + more)

**Comment by GermaVinsmoke** [comment]
Besides feather icons, the codebase is using other icons also.

```
packages/ui/components/bade/Badge.tsx - Github octicons
apps/web/pages/auth/login.tsx - Font Awesome
apps/web/components/eventtype/EventTypeSingleLayout.tsx - Tabler icons 
apps/web/components/eventtype/EventTeamWebhooksTab.tsx - Tabler icons
```
