### ISSUE TITLE
[CAL-1351] Only one seat counts when two or more users books an event without occupied seats.

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#7967]
if more than one user books an event with seats, when there are no seats occupied yet, only 1 seat will count.

Steps to reproduce:

1. Create an event with seats
2. Choose in 2 different browser windows/tabs the same slot with all available seats.
3. Complete the reservation in the 2 tabs/windows
4. Return to the event type page, and you will see that only one seat es occupied.

I think it is because bookingUid is generated when the first booking occurs. then the others booking has the same uuid. But in this scenario, all the users who selected the slot before the uuid was generated, will generate a different one.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1351](https://linear.app/calcom/issue/CAL-1351/only-one-seat-counts-when-two-or-more-users-books-an-event-without)</sub>

**Comment by McPizza0** [comment]
May be related to: #9749
Even when booking 2nd seat, new event is generated
