### ISSUE TITLE
BlueJeans

### ISSUE THREAD

**Issue by kaerez** [calcom/cal.com#7971]
With the new pricing for BlueJeans basic tier; it should be included in the AppStore
for dynamic meeting generation.

Further information:

Verizon launches free basic tier for Bluejeans with unlimited meeting lengths and up to 25 attendees.

Press release:
https://www.verizon.com/about/news/bluejeans-verizon-releases-better-meetings-free-bluejeans-basic

Bluejeans:
https://www.bluejeans.com/free-video-conferencing/launch

Full tiers comparison:
https://www.bluejeans.com/pricing/meetings

**Comment by rjackson** [comment]
Duplicate of #7676?
