### ISSUE TITLE
[CAL-1707] Routing Forms misinformation

### ISSUE THREAD

**Issue by kaerez** [calcom/cal.com#7973]
The [Routing forms App](https://app.cal.com/apps/routing-forms) is stated as free but is not available after installation without a team account.

<sub>[CAL-1707](https://linear.app/calcom/issue/CAL-1707/routing-forms-misinformation)</sub>

**Comment by hariombalhara** [comment]
We should use UpgradeTip badge as used in [TeamsListing.tsx](https://github.com/calcom/cal.com/blob/df85a1f209d0150bc05b7484ed821e87e0f1dddc/packages/features/ee/teams/components/TeamsListing.tsx#L10) to clearly prevent installation and provide an easy way to upgrade from there itself.

**Comment by PeerRich** [comment]
agree. lets fix this
