### ISSUE TITLE
[CAL-1354] Can't change language in settings

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#7976]
### Issue Summary

When trying to change the language in settings it says 'Settings successfully updated' but the language is still the old one when reloading the page. 

Loom: https://www.loom.com/share/2f93f4604ae7446694ba034bb64beecf

<sub>[CAL-1354](https://linear.app/calcom/issue/CAL-1354/cant-change-language-in-settings)</sub>

**Comment by CarinaWolli** [comment]
The options in the select to edit a location are translated in the language I picked. Everything else is still english:
![Screenshot 2023-03-28 at 13 27 14](https://user-images.githubusercontent.com/30310907/228222010-3ec3fa85-4b02-48b4-a6b5-955e16882c43.png)

**Comment by thgh** [comment]
Refreshing the page after changing the language changes it right back to the original.
