### ISSUE TITLE
[CAL-1356] No automatic calendar entries for team members for booked team event

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7978]
Team members not getting a calendar entry, only Team owner.

**Comment by emrysal** [comment]
This is due to the Google change that no longer auto-adds events to the google calendar. We should add the invite manually to the team member calendar.

**Comment by PeerRich** [comment]
how do we move forward here @emrysal ?

**Comment by hariombalhara** [comment]
How is a Team User different from a Guest or Booker in terms of getting calendar invites. They all receive emails for the same calendar invite. 

I think this is solved by following https://cal.com/blog/google-s-new-spam-policy-may-be-affecting-your-invitations. This is applicable to everyone except the organizer, on whose calendar the event is created.

**Comment by hariombalhara** [comment]
Closing this issue as per my last comment. Feel free to reopen.
