### ISSUE TITLE
Broken link on webhook docs

### ISSUE THREAD

**Issue by thgh** [calcom/cal.com#7980]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Broken link: "[customize the payload](https://cal.com/docs/core-features/webhooks#undefined)"

### Steps to Reproduce

1. Click the link

It should first explain what the default payload contains and then show how to customize it.

**Comment by PeerRich** [comment]
@alishaz-polymath

**Comment by alishaz-polymath** [comment]
Fixed. Thanks for bringing this up @thgh 🙏
