### ISSUE TITLE
[CAL-1358] Weird Prisma Error When Removing Team Member from Team

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#7982]
![CleanShot 2023-03-28 at 08.21.00@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c2c8678d-fcf6-4710-8244-77ed365611fc/4b7d8c8e-35ea-4ac7-bb47-04d98b0988c6)

Went to remove the first pending user and got the above error message, a few seconds later I was notified the user was removed, but it's still there in the pane

I tried removing the other user and received "unauthorized"

![CleanShot 2023-03-28 at 08.22.10@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/66a357f4-d533-48d2-9420-8e0203d002b3/030dd2e2-9abd-4c47-b08c-2cd6e9034c09)

Turns out, I was logged into another account which is why I received these error messages 🤔 — should the move to be  logged out of this window or get a message saying "Admin Access needed. Contact Team owner xyz"? 

Feel free to disregard if too much of an edge case 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1358](https://linear.app/calcom/issue/CAL-1358/weird-prisma-error-when-removing-team-member-from-team)</sub>

**Comment by PeerRich** [comment]
i dont think this is happening anymore
