### ISSUE TITLE
[CAL-1359] /teams: Members should not see "Next steps" since they can't take any

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7983]
![CleanShot 2023-03-28 at 16.33.51@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2cca420b-4b04-445c-88c0-223e0c88bf8d/03db980e-4500-4d86-8caf-30b8e78630a4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1359](https://linear.app/calcom/issue/CAL-1359/teams-members-should-not-see-next-steps-since-they-cant-take-any)</sub>

**Comment by PeerRich** [comment]
only team owners and admins should see this
