### ISSUE TITLE
[CAL-1360] /embed: Confirmation screen UI issues

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7984]
![CleanShot 2023-03-28 at 16.40.56@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/75450d57-98fc-432e-a6f2-3b431632df91/7cb739a6-d070-4bc8-beb7-69e7c3139dc8)

The previous screen has a height of 434px, I'm not sure if explicitly hard coding a min-height is they way to go, but it should stay the same height as the previous step.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1360](https://linear.app/calcom/issue/CAL-1360/embed-needs-a-min-height)</sub>

**Comment by MayurAnklekar** [comment]
Hi, I would like to work on this issue, could you assign it to me?

**Comment by keithwillcode** [comment]
@MayurAnklekar You still up for taking this one?

**Comment by iprime2** [comment]
@ciaranha please upload new screenshot as old is not visible anymore.

**Comment by shekharkalshetti** [comment]
can i work on this issue?
@keithwillcode

**Comment by keithwillcode** [comment]
No need to be assigned. Feel free to open a PR and we’ll review
