### ISSUE TITLE
[CAL-1361] /public booking - height on details screen should stay the same previous

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#7985]
[https://github.com/calcom/cal.com/assets/8019099/b97ed408-0924-4963-8ef5-521c6460a70d](https://github.com/calcom/cal.com/assets/8019099/b97ed408-0924-4963-8ef5-521c6460a70d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1361](https://linear.app/calcom/issue/CAL-1361/public-booking-height-on-details-screen-should-stay-the-same-previous)</sub>

**Comment by PeerRich** [comment]
yeah seems like a min-height is missing. the box is smaller because you disabled "additional notes" which used to be required

**Comment by PeerRich** [comment]
this is fixed in v2.0 booking
