### ISSUE TITLE
[CAL-1362] Feature: Make it easier for Admins to edit team members

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7987]
As a Team Admin I want to be

... able to change Team members data easier (Change bio, change Avatar, ...)

Right now I have to 

... Impersonate, make changes, log out, log in again

<sub>[CAL-1362](https://linear.app/calcom/issue/CAL-1362/feature-make-it-easier-for-admins-to-edit-team-members)</sub>

**Comment by sean-brydon** [comment]
@Jaibles do we have any designs for this?

**Comment by shirazdole** [comment]
* Org. Role (ability to change)
* Teams Part of 
* Bio (ability to change)
* Avatar (ability to change)
* Availability (ability to change)
* Timezone (ability to change)
* Managed events types (ability to remove)
* Manage any and all apps — Similar to seeing if Google Calendar is connected or not, conferencing apps (Zoom, Google Meet, MSFT Teams) - ability to send email prompt to user to connect said app

**Comment by Jaibles** [comment]
Work in progress designs here: 

[\[CAL-1362\] Admin view (Members) - Teams (Figma)](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Teams?type=design&node-id=4204%3A199174&t=TtcdzV14BuRoBo9j-1)
