### ISSUE TITLE
[CAL-1363] No meeting link in booking invite

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#7998]
"The attendee mentioned that he got an invite but it didn't have a meeting link in it, which is odd because mine did"

@Jaibles will get the booking link off the user to investigate.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1363](https://linear.app/calcom/issue/CAL-1363/no-meeting-link-in-booking-invite)</sub>

**Comment by Udit-takkar** [comment]
Not able to reproduce
