### ISSUE TITLE
Cannot connect to Communigate Pro CalDAV server

### ISSUE THREAD

**Issue by kortenkamp** [calcom/cal.com#8003]
I am trying to connect to a Communigate Pro CalDAV server, but it fails with all combinations of server URL and user name that I could think of. 

In iCal I have the following –working– settings (host, university and username replaced with generic names):

**Server:** `host.university.de`
**Serverpath:** `/UserDAV/username@university.de/`
**User:** `username`

Our configuration documents suggest to use `host.university.de` for Thunderbird as CalDAV URL, so the full URL should be discoverable by the client. 

When I use `https://host.university.de` as URL when adding the calendar, it fails with

```
ERROR Could not add this caldav account
 Error  cannot find homeUrl
error stack:
• tsdav.cjs.js:1164 <anonymous>
    node_modules/tsdav/dist/tsdav.cjs.js:1164:15

• tsdav.cjs.js:45 fulfilled
    node_modules/tsdav/dist/tsdav.cjs.js:45:58

• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
```

When I use `https://host.university.de/UserDAV`as URL the same error message is shown.

When I use the URL composed from the server and path in iCal, `https://host.university.de/UserDAV/username@university.de/`, the message _The string did not match the expected pattern._ is shown in the browser, but no error message appears in the server logs.

Any advice? Has somebody configured calcom successfully with a Communigate Pro calendar server?

**Comment by PeerRich** [comment]
we dont support this provider yet. please visit https://github.com/calcom/cal.com/issues/3457 and comment there

**Comment by PeerRich** [comment]
@alishaz-polymath can take a look after!
