### ISSUE TITLE
[CAL-1368] upgrade banner background image missing

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8005]
![CleanShot 2023-03-29 at 12 57 52@2x](https://user-images.githubusercontent.com/8019099/228513095-5af3f942-3ab0-42de-8bb4-ab4c23ebe0c6.jpg)

is this only me?

<sub>[CAL-1368](https://linear.app/calcom/issue/CAL-1368/upgrade-banner-background-image-missing)</sub>

**Comment by PeerRich** [comment]
somehow working for @Udit-takkar

**Comment by GermaVinsmoke** [comment]
Visible on latest main commit

**Comment by PeerRich** [comment]
its adblock

will rename folder
