### ISSUE TITLE
[CAL-1370] RFC: DB Region select in signup

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8008]
Some customers have strict database region requirements (i.e. Canadian Healthcare companies need Canada as region)

i.e. Canada:

![CleanShot 2023-03-29 at 15 16 43@2x](https://user-images.githubusercontent.com/8019099/228550223-a488d204-cec1-4401-bc3e-a3e34879766e.jpg)

Regions:
- USA (default)
- Europe
- Canada
- Singapore
- Australia

Requirements:
- usernames still have to be unique, which means we need to store usernames in the USA db and check against it

<sub>[CAL-1370](https://linear.app/calcom/issue/CAL-1370/rfc-db-region-select-in-signup)</sub>

**Comment by keithwillcode** [comment]
First thought that comes to mind is to implement directory sharding (example: [https://aws.amazon.com/what-is/database-sharding/](url). At a middleware layer, we can detect which customer is accessing the site and perform a shard lookup based on the customer.

**Comment by emrysal** [comment]
Sharding is one approach, another approach I'm speculating we could take is https://github.com/aiji42/prisma-data-proxy-alt/tree/main - instead of just data proxy (this is a much faster implementation of data proxy) this flow would look like this.

**Comment by PeerRich** [comment]
this has been deprioritized and 2 more weeks were added

**Comment by PeerRich** [comment]
gonna be interesting/complex how we will have teams in different regions

can members of a team be in different regions?

likely no, because you need to open a team in your current region 

but can you then invite people from other regions? 😭

**Comment by PeerRich** [comment]
i think if a US user gets invites to a EU team, it should migrate the entire account over to EU

what happens if you are in two teams tho? 🤯

**Comment by zomars** [comment]
>   * Each request will be processed by middleware, username checked in the global lookup, matched to the company/user and from there subsequent database calls to retrieve data will rely on the shard settings found for the company/user.

Wouldn't this introduce a lot of latency?

>   * Global lookup of usernames will be used to keep unique usernames across all regions

How will this functionality differ between our hosted and self-hosted offerings?

**Comment by keithwillcode** [comment]
> Wouldn't this introduce a lot of latency?
No, it should be trivial, especially if we use solid caching techniques.

> How will this functionality differ between our hosted and self-hosted offerings?
Self-hosted would have this disabled by default.

**Comment by zomars** [comment]
Reviving this thread since #21364 will enable this.
