### ISSUE TITLE
[CAL-1371] /settings - team members: Show people's booking link

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8009]
Currently it shows the email and no username

edit by @PeerRich: show "•" instead of "|" as separator

![CleanShot 2023-03-29 at 14.51.34@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/34611735-27e4-4a59-a84c-445f655b35c4/b2eb5ef1-a5a4-4ef3-81ba-e53ee9951e1b)

We should also show the booking link of all team members.

Designs:

![CleanShot 2023-03-29 at 15.02.15@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/01632a12-3688-47cf-8aac-bae7060a64cb/c3971906-3968-4da2-8a9c-31ff0a139d82)

[View in Figma →](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A69603&t=GyqQV5A60KRJ3jdf-1)

**Make sure to use our** [**list item component **](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=27844%3A90422&t=GbbAFEFKW3r9VpPC-1)**@sean-brydon built.**

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1371](https://linear.app/calcom/issue/CAL-1371/settings-team-members-show-peoples-booking-link)</sub>

**Comment by PeerRich** [comment]
lets do • instead of |
