### ISSUE TITLE
Can't set 2FA because of "Invalid key length"

### ISSUE THREAD

**Issue by KaratekHD** [calcom/cal.com#8017]
### Issue Summary

As per #7914, it seems like admins need to have 2FA enabled. However, when trying to enable 2FA, the user only sees "Something went wrong.".

![image](https://user-images.githubusercontent.com/38097062/228652571-02c5c965-c55d-40b1-a3ea-cb84540e4803.png)

### Steps to Reproduce

1. Sign in to your cal.com instance
2. Click on Settings &rarr; Two factor auth
3. Check "Two factor authentication"
4. Enter your password
5. Click "Continue"

### Technical details

- Browser Version: Firefox 109.0.1 and Edge 112.0.1698.0 on openSUSE Tumbleweed
- Cal.com Docker container v2.7.6
- server log:
```
@calcom/web:start: RangeError: Invalid key length
@calcom/web:start:     at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
@calcom/web:start:     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
@calcom/web:start:     at new Cipheriv (node:internal/crypto/cipher:249:3)
@calcom/web:start:     at Object.createCipheriv (node:crypto:141:10)
@calcom/web:start:     at symmetricEncrypt (/calcom/apps/web/.next/server/chunks/8650.js:29:66)
@calcom/web:start:     at handler (/calcom/apps/web/.next/server/pages/api/auth/two-factor/totp/setup.js:329:107)
@calcom/web:start:     at async Object.apiResolver (/calcom/node_modules/next/dist/server/api-utils/node.js:372:9)
@calcom/web:start:     at async NextNodeServer.runApi (/calcom/node_modules/next/dist/server/next-server.js:513:9)
@calcom/web:start:     at async Object.fn (/calcom/node_modules/next/dist/server/next-server.js:815:35)
@calcom/web:start:     at async Router.execute (/calcom/node_modules/next/dist/server/router.js:243:32)
@calcom/web:start:     at async NextNodeServer.runImpl (/calcom/node_modules/next/dist/server/base-server.js:432:29)
@calcom/web:start:     at async NextNodeServer.handleRequestImpl (/calcom/node_modules/next/dist/server/base-server.js:375:20)
@calcom/web:start:     at async /calcom/node_modules/next/dist/server/base-server.js:157:99 {
@calcom/web:start:   code: 'ERR_CRYPTO_INVALID_KEYLEN'
@calcom/web:start: }
```
- The browser tries to post to `/api/auth/two-factor/totp/setup`, which results in HTTP 500 (Internal Server Error)

**Comment by rusty1281** [comment]
I have the same exact error using the 2.7.9 version.

**Comment by lpadula** [comment]
Same problem here!

**Comment by eduardstal** [comment]
Same problem here!

**Comment by sneridagh** [comment]
A PR is needed to update: https://github.com/viaayni/cal.com/blob/8781466fcc6be25865ae4fd9e4dd12a273b42258/.env.example#L90
