### ISSUE TITLE
[CAL-1375] All attendees shown in location update email (seats)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#8025]
### Issue Summary

Even when 'Share attendee information between guests' is disabled we show the attendee information of all booked seats in the Location update email. We should only show the organizer and the person who received the email. 

<sub>[CAL-1375](https://linear.app/calcom/issue/CAL-1375/all-attendees-shown-in-location-update-email-seats)</sub>

**Comment by joeauyeung** [comment]
Fixed in #8033
