### ISSUE TITLE
[CAL-1376] /booking: cant accept or reject if filter is "All bookings"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8027]
when "Requires confirmation" is true, it won't show the buttons if: "All bookings"

![CleanShot 2023-03-30 at 14 37 49@2x](https://user-images.githubusercontent.com/8019099/228838208-722773f9-53e4-4530-adc4-49c1f0cb1d58.jpg)

They only show up if you select "Your bookings"
![CleanShot 2023-03-30 at 14 38 59@2x](https://user-images.githubusercontent.com/8019099/228838460-76c37cf8-bdb2-4fcb-a4e3-e6eb6aebbe28.jpg)

<sub>[CAL-1376](https://linear.app/calcom/issue/CAL-1376/booking-cant-accept-or-reject-if-filter-is-all-bookings)</sub>

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, can you please give more context on the issue? We are not experiencing any change in behavior for different selections.
https://www.loom.com/share/759f94bf4ecc47b29a531c37bd7bd8f2
