### ISSUE TITLE
[CAL-1378] Choosing a different duration makes unavailable slot available

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8039]
More issues with "choose duration"

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d0171b7f-2cbf-40c0-9565-195875fc5b74/9189e178-e5db-48b6-8771-d55b1ec6007e)

The slots are at 30-minute intervals but once you choose 60-minute duration 09:00 isn't available
<img width="669" alt="Screenshot 2023-05-16 at 12 49 56" src="https:/

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c1a7c207-9bd6-4ba6-afa5-d815ef9b1f7f/c2931a4b-6f5c-4535-9715-803e1a824eed)

Created via Threads. See full discussion: [https://threads.com/34460673303](https://threads.com/34460673303)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1378](https://linear.app/calcom/issue/CAL-1378/choosing-a-different-duration-makes-unavailable-slot-available)</sub>

**Comment by milospuac** [comment]
@emrysal Should this one be assigned to you?

**Comment by emrysal** [comment]
Confirmed this is fixed after v3.0.15 💯
