### ISSUE TITLE
[CAL-1382] Issue when deleting date overrides

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8043]
[https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71](https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71)
[https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71](https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71)

Created via Threads. See full discussion: [https://threads.com/34460761924](https://threads.com/34460761924)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1382](https://linear.app/calcom/issue/CAL-1382/issue-when-deleting-date-overrides)</sub>

**Comment by bharat2913** [comment]
Hey, @milospuac 
Can I work on this?

**Comment by milospuac** [comment]
@bharat2913 sure, thank you for your contribution 🫡
