### ISSUE TITLE
[CAL-1383] Cleanup full raw avatar responses from tRPC endpoints

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#8044]
Found one in `packages/trpc/server/routers/viewer/eventTypes.ts`

This response:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/90c63551-7dea-4265-957e-6d206005675a/f4098265-781e-4060-9e9b-9c7bbd876752)

Should be:

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/df79800a-ccc5-443e-85a8-4d921eb49920/4ae588c5-ef50-4c26-bcac-21b59f6bbfd5)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1383](https://linear.app/calcom/issue/CAL-1383/cleanup-full-raw-avatar-responses-from-trpc-endpoints)</sub>

**Comment by ShekharDhangar** [comment]
hey @zomars, I want to work on this issue, just have few doubts.
1. The avatar string is coming from prisma as base64 encoded string, right?, so instead of using that base64 string, use this url as expected `https://app.cal.com/${user.username}/avatar.png` , is that correct?
