### ISSUE TITLE
[CAL-1386] Timezone Loader doesn't look propery aligned

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8051]
Notice the 2 dots in front of Timezone. This is shown when booking an event.

![image](https://user-images.githubusercontent.com/1780212/229413303-083c3ce0-f232-4be4-b90f-d8864316ae6e.png)

<sub>[CAL-1386](https://linear.app/calcom/issue/CAL-1386/timezone-loader-doesnt-look-propery-aligned)</sub>

**Comment by lmnnarciso** [comment]
@hariombalhara Can you write the steps to get the similar screen you got in the screenshot?
