### ISSUE TITLE
[CAL-1390] "No Available user found" error when user tries to reschedule to a slot that he already has a seat for.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8054]
![229441429-44fca4dc-643f-4676-9cba-42e567b10f5e](https://user-images.githubusercontent.com/1780212/229441917-455bf444-a3bf-43a3-bde7-bd8cfef3c410.png)

<sub>[CAL-1390](https://linear.app/calcom/issue/CAL-1390/no-available-user-found-error-when-user-tries-to-reschedule-to-a-slot)</sub>

**Comment by joeshajan** [comment]
Hey, @hariombalhara, I tried reproducing this issue and found that the error occurs when the user tries to reschedule the meeting for the same time as before, is that correct? In my opinion, it doesn't make sense for the user to reschedule it for the same time (sorry if I'm wrong), so this behavior is correct. Do you agree, or should the user be able to reschedule it for the same time?


![image](https://user-images.githubusercontent.com/69904519/230706497-4e931fe2-24f2-4be5-9278-ac3351614834.png)

**Comment by hariombalhara** [comment]
Yeah, he shouldn't be able to select that slot ideally. It should be removed from slots list.

**Comment by joeshajan** [comment]
Okay, got it. So just to confirm, when the user tries to select the same slot again, it should be disabled, right? In the screenshot below, 9:45 was the previous time. Therefore, when the user tries to reschedule, this slot should be disabled. If yes, I would like to start working on this. Can you assign this to me? @hariombalhara 

![image](https://user-images.githubusercontent.com/69904519/230707449-6f1231ad-4003-46d8-af4d-d8e53e244d02.png)

**Comment by hariombalhara** [comment]
It should just not show up. If you would test a simple slot booking scenario(without seats). An already booked slot, goes away from the list.
The tricky part is that the slot needs to be removed for the person who has already booked that slot. Other persons can still book that slot depending on the remaining seats. Now, on that slots listing page, user hasn't even shared his info(as to who he is. That information is asked on the next page). So, this approach of removing slot might not work

Maybe we can improve the error in this specific case. Instead of a generic 'Couldn't reschedule the meeting`, we can say you have already booked this slot.

I would let @alannnc comment on how it should be done.

**Comment by joe-shajan** [comment]
> It should just not show up. If you would test a simple slot booking scenario(without seats). An already booked slot, goes away from the list. The tricky part is that the slot needs to be removed for the person who has already booked that slot. Other persons can still book that slot depending on the remaining seats. Now, on that slots listing page, user hasn't even shared his info(as to who he is. That information is asked on the next page). So, this approach of removing slot might not work
> 
> Maybe we can improve the error in this specific case. Instead of a generic 'Couldn't reschedule the meeting`, we can say you have already booked this slot.
> 
> I would let @alannnc comment on how it should be done.

sure 👍
