### ISSUE TITLE
[CAL-1393] Link Meeting value shown to user on payment page.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8059]
Location Link Value shown for Paid Event event(on payment/[uid] page) if 'Display on booking page' is not checked
<img width="829" alt="Screenshot 2023-04-03 at 5 02 41 PM" src="https://user-images.githubusercontent.com/1780212/229497433-92f55884-8c56-4cae-bcde-b4aaba3fd395.png">

<img width="810" alt="Screenshot 2023-04-03 at 5 01 36 PM" src="https://user-images.githubusercontent.com/1780212/229497194-b7223e9a-e10a-4c99-98f9-b1bbe033d714.png">

It works correctly for other pages.
<img width="816" alt="Screenshot 2023-04-03 at 5 00 58 PM" src="https://user-images.githubusercontent.com/1780212/229497053-a6fc9155-68e3-4875-9a6d-920d1e1b4806.png">

<sub>[CAL-1393](https://linear.app/calcom/issue/CAL-1393/link-meeting-value-shown-to-user-on-payment-page)</sub>

**Comment by ShekharDhangar** [comment]
hey @hariombalhara , here by location link you mean `googlemeet/zoom` right? or `Asia/Kolkata`?

**Comment by ShekharDhangar** [comment]
ok understood, what to show there  instead of value `Link Meeting` ?

**Comment by hariombalhara** [comment]
@ShekharDhangar It's the correct implementation where we show "Link Meeting" because the organizer has not ticked **Display on Booking Page**.
![image](https://user-images.githubusercontent.com/1780212/229740664-e64fa5ca-c83b-4658-8c45-07f4f68a295b.png)

The bug is that Payment page shows the actual value 'http://google.com' even after that.

**Comment by lmnnarciso** [comment]
@hariombalhara Can I be assigned for this? I'll look into it.

**Comment by hariombalhara** [comment]
@ShekharDhangar seems to be working on it. Can you confirm @ShekharDhangar

**Comment by ShekharDhangar** [comment]
yes I'm working on this @hariombalhara , please assign this to me

**Comment by bhumit070** [comment]
Hello @hariombalhara I guess this issue has been fixed and should be closed please check I wanted to work on this issue as it is still open and there is no reply from @ShekharDhangar  so I checked and it is working as expected please close this issue if it is fixed , and let me know please if I am wrong.

**Comment by nitishsaini706** [comment]
@hariombalhara yes please look into this

**Comment by JaideepGuntupalli** [comment]
Hey, @PeerRich this issue isn't still fixed so I have opened a pull request. Pls, review it.

cc: @hariombalhara

**Comment by Sanketh149** [comment]
I want to work on this issue @hariombalhara
