### ISSUE TITLE
[CAL-1394] Booking fails in reschedule scenario - No Available User found error

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8060]
If a booking that was created when calendar connection was broken is rescheduled(when calendar connection is working), booking fails with the following error
<img width="1400" alt="Screenshot 2023-04-03 at 5 27 59 PM" src="https://user-images.githubusercontent.com/1780212/229502494-eeb14c04-aba9-44d2-a5d8-8f9b9fc0303b.png">

<sub>[CAL-1394](https://linear.app/calcom/issue/CAL-1394/booking-fails-in-reschedule-scenario-no-available-user-found-error)</sub>

**Comment by hariombalhara** [comment]
I think this issue occurs for a booking that's already rescheduled. It seems like we are able to reschedule an already rescheduled booking.

**Comment by PeerRich** [comment]
do we address this or not?

**Comment by hariombalhara** [comment]
Yeah it should certainly be fixed.
