### ISSUE TITLE
[CAL-1395] routing forms: send email to person receiving the call

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8061]
right now, we only send the content of the routing form to the email of the creator of the form

it would be better if the email ALSO goes to the person whoever the form routed to

if the routing destination is a round robin event, it should go to the person getting the round robin

if its collective, send to all team members of that collective event type

<sub>[CAL-1395](https://linear.app/calcom/issue/CAL-1395/routing-forms-send-email-to-person-receiving-the-call)</sub>

**Comment by hariombalhara** [comment]
There is a hackish(and quick) way where I can derive the username from the URL the routing is going to happen. So, if someone routes to [cal.com/hariom/30min](http://cal.com/hariom/30min), I should be able to derive it from here.
﻿
I would have to see how I can implement it the right way where I can store metadata along with a routing condition. That metadata would have the userId for the cal Link to which routing is happening

**Comment by chamaraw** [comment]
@hariombalhara we have a requirement to send indidividual team member call link when book via round robin meeting, Is this ties up with this request?

**Comment by hariombalhara** [comment]
@chamaraw People who are part of the meeting already receive an email with conferencing link. Can you elaborate on the requirement
