### ISSUE TITLE
[CAL-1456] Booking area flickring after embedding

### ISSUE THREAD

**Issue by aliezaheer** [calcom/cal.com#8068]
The booking area is flickering badly after embedding I tested it on multiple websites and the result is the same.

Video link: https://www.loom.com/share/68a7b6ad672344228df18134d2b31a03

<sub>[CAL-1456](https://linear.app/calcom/issue/CAL-1456/booking-area-flickring-after-embedding)</sub>

**Comment by kentond18** [comment]
Mine is doing the same exact thing. Looking at the CSS in dev tools, it seems that the logic for detecting the user's preferred theme based off light or dark mode setting is conflicting at some point and causing a constant reload.

[Reloading Error Video Link](https://www.loom.com/share/fa0dfa48ed814c1ba4e446772be72466)

Let me know if you need more info.
