### ISSUE TITLE
[CAL-1409] special characters not rendering in og-images

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8088]
![image](https://user-images.githubusercontent.com/8019099/229848471-573d9526-095e-437a-bb7f-da07bc77649e.png)

Hey team, I'm having an issue with the thumbnail metadata - it says &amp in mine instead of & Founder. Any ideas why?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1409](https://linear.app/calcom/issue/CAL-1409/special-characters-not-rendering-in-og-images)</sub>

**Comment by shubhams167** [comment]
I checked an Open Graph preview with special characters and it looks good.

@PeerRich are you still facing this issue? or we can close this issue?

**Comment by devarshishimpi** [comment]
Issue seems already resolved!
