### ISSUE TITLE
[CAL-1410] Tokens update - Lightmode issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8089]
* [ ] Shadow & border on public booking page timezone dropdown is gone. Need to check others

![CleanShot 2023-04-04 at 22.01.53@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8566d851-84a3-405d-bf6c-14aade6dd918/b98f85a9-d2f0-45c2-86eb-920e995b2156)

* [ ] Toggle "Off" has wrong styling. [Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=309%3A44841&t=30onBbWkRyrGOgzn-1)

![CleanShot 2023-04-04 at 22.04.52@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/49a5d80d-9141-4a66-82b9-97dc2d45ffe4/8c2ca395-7fc7-44e5-bbbf-0b950f7b0382)

- [ ] black "x" in select
![CleanShot 2023-04-04 at 22 25 22@2x](https://user-images.githubusercontent.com/8019099/229912265-e51f7143-3498-47ce-89f6-d1f91a14e396.jpg)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1410](https://linear.app/calcom/issue/CAL-1410/tokens-update-lightmode-issues)</sub>

**Comment by Toledodev** [comment]
Hey @Jaibles, could you provide more information about where I find this select with the black "x"? I checked in some places and didn't find this wrong x
![image](https://user-images.githubusercontent.com/87545086/232893532-731fa350-e80d-41c3-bd4d-146f862ad96c.png)
