### ISSUE TITLE
[CAL-1411] tailwind refactor: replace ltr and rtl with new ms- and me- prefixes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8090]
use this instead:

[https://tailwindcss.com/blog/tailwindcss-v3-3#:\~:text=installation footprint small.-,Simplified RTL support with logical properties,-We’ve made it](https://tailwindcss.com/blog/tailwindcss-v3-3#:\~:text=installation%20footprint%20small.-,Simplified%20RTL%20support%20with%20logical%20properties,-We%E2%80%99ve%20made%20it)

example:

`<div className="ltr:ml-2 rtl:mr-2">`

is now

`<div className="ms-2"  />`

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1411](https://linear.app/calcom/issue/CAL-1411/tailwind-refactor-replace-ltr-and-rtl-with-new-ms-and-me-prefixes)</sub>

**Comment by joeshajan** [comment]
Can someone not from Cal team contribute to this issue? When I open the above gitstart link it says unauthorized.
