### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#8099]
Redirection for embeds is now done directly at the embed location and not on a new page.

<img width="1440" alt="Bildschirmfoto 2023-04-05 um 12 51 17" src="https://user-images.githubusercontent.com/126205884/230060150-a6545a9a-f6c9-4dcb-a7e8-5e72d295cfb1.png">

**Comment by PeerRich** [comment]
@hariombalhara is it possible to do the redirect in the entire page, not inside the embed dialog?
