### ISSUE TITLE
[CAL-1413] self-hosted admins: show "A new update of Cal.com is available"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8100]
if self-hosted version < github tagged release then show topBanner "A new update of Cal.com is available" 

button: "See update" link to https://github.com/calcom/cal.com/releases

github API: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28

<sub>[CAL-1413](https://linear.app/calcom/issue/CAL-1413/for-admins-show-a-new-update-of-calcom-is-available)</sub>

**Comment by joeshajan** [comment]
Hey, @PeerRich can you give me some idea about where should we display it?

Does that component already exist?

Is there any documentation on self-hosting?

**Comment by PeerRich** [comment]
topBanner. there is a component for this
