### ISSUE TITLE
[CAL-1415] more app store categories and add illustrations

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8103]
- [ ] better categories: https://docs.google.com/spreadsheets/d/1ELnRtVtjujGCpRcWXA-EXgKJ_ZIUcVG1UnM7WHA7cPU/edit?usp=sharing﻿
- [ ] new illustrations

<sub>[CAL-1415](https://linear.app/calcom/issue/CAL-1415/more-app-store-categories)</sub>

**Comment by hariombalhara** [comment]
In some cases migration might be required. I will identify the steps and document them.
