### ISSUE TITLE
Custom Field missing from "Get All Bookings" API request

### ISSUE THREAD

**Issue by mywebmasteruk** [calcom/cal.com#8106]
### Issue Summary

When I use the API to get all bookings, it does not return the custom fields added to the booking form (free tier)

**Comment by PeerRich** [comment]
@alishaz-polymath can you look into adding this?

**Comment by alishaz-polymath** [comment]
It has since been resolved, custom inputs have been deprecated and `responses` have taken their place. Responses are returned as part of the GET bookings API request.
