### ISSUE TITLE
[CAL-1419] Change Detroit to New York as a default for EST time zone

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8119]
![CleanShot 2023-04-06 at 11 54 49@2x](https://user-images.githubusercontent.com/8019099/230342891-1b01a683-ef63-43fb-91a3-0fb860edebec.jpg)

Detroit as default for EST is weird.

- [ ] Instead do `America/New York`
- [ ] Also: lets replace "_" with " ": 

![CleanShot 2023-04-06 at 11 55 34@2x](https://user-images.githubusercontent.com/8019099/230343116-5252095a-266f-4fb4-ad88-2c457641ac23.jpg)

Los_Angeles => Los Angeles

Created via Threads. See full discussion: [https://threads.com/34461922510](https://threads.com/34461922510)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1419](https://linear.app/calcom/issue/CAL-1419/change-detroit-to-new-york-as-a-default-for-est-time-zone)</sub>

**Comment by joeshajan** [comment]
But there is no **new york** in `import { allTimezones } from "react-timezone-select";`

Should we add a custom one? @milospuac
