### ISSUE TITLE
[CAL-1421] No confirmation emails sent, only workflow

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8121]
Customers comments: 

"Attendee only Received my workflow messagae "thanks for booking'
Attendee's calendar is also empty.

Even I (host) haven't received that someone booked a call with me, but in calendar I can see it."

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1421](https://linear.app/calcom/issue/CAL-1421/no-confirmation-emails-sent-only-workflow)</sub>

**Comment by milospuac** [comment]
I opened this issue when

**Comment by joeshajan** [comment]
Hey @milospuac can you please explain it a little more 😊

**Comment by PeerRich** [comment]
is this still happening?

**Comment by PeerRich** [comment]
@CarinaWolli can you investigate?

**Comment by CarinaWolli** [comment]
Was never able to reproduce that. @milospuac do you know the customer who reported that?
