### ISSUE TITLE
[CAL-1426] Research merge.dev for integrations

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#8124]
[https://merge.dev/](https://merge.dev/)

This service is used by many companies to unify APIs between integrations. We are looking into it for hooking up things like Greenhouse, Lever, Salesforce, etc.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1426](https://linear.app/calcom/issue/CAL-1426/research-mergedev-for-integrations)</sub>

**Comment by PeerRich** [comment]
tldr: not worth it
