### ISSUE TITLE
[CAL-1429] Fix order on pricing page in Console

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8132]
Starter (99) → Essentials (299) → Scale (2499) → Enterprise

![CleanShot 2023-04-07 at 06.17.34@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5b55ad94-5428-4c6f-a2b8-0827c694b95b/71688edc-ac80-414c-8364-6af19022e315)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1429](https://linear.app/calcom/issue/CAL-1429/fix-order-on-pricing-page-in-console)</sub>

**Comment by sumitshinde-84** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by abhishekjha1907** [comment]
Hi, can you assign me this issue, I would like to work on this.

**Comment by abdallahalsamman** [comment]
@abhishekjha1907 @sumitshinde-84 I tried to work on this issue but couldn't find these components in the repo, maybe this is something only cal.com employees have access to?

**Comment by PeerRich** [comment]
fixing this

**Comment by PeerRich** [comment]
seems to be fixed
