### ISSUE TITLE
many (stale) branches

### ISSUE THREAD

**Issue by DanielRuf** [calcom/cal.com#8140]
Currently there are hundreds of branches. Many of them are stale and probably obsolete because the relevant PRs are closed (see for example https://github.com/calcom/cal.com/branches/all?page=6).

Do you plan to clean this up?

**Comment by PeerRich** [comment]
we can, is this causing any downsides keeping open tho?

**Comment by DanielRuf** [comment]
> we can, is this causing any downsides keeping open tho?

In general it might happen that every contributor fetches all these branches when doing a local Git clone.

As best practice in other big projects the source branches are deleted after the PRs are merged or closed.
If you really do not need them after that, you can safely delete them.

**Comment by PeerRich** [comment]
i think these branches are only open when closed. i think we auto delete when merged. we'll clean up some branches
