### ISSUE TITLE
[CAL-1433] refactor: deprecate @variants, use @layer instead

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8149]
```
The `@variants` directive has been deprecated in Tailwind CSS v3.0.
warn - Use `@layer utilities` or `@layer components` instead.
```

<sub>[CAL-1433](https://linear.app/calcom/issue/CAL-1433/refactor-deprecate-variants-use-layer-instead)</sub>

**Comment by joeshajan** [comment]
Hey, @PeerRich we are using `@variants` in one place only and that's global.css.

And is this a correct fix?

![image](https://user-images.githubusercontent.com/69904519/230717990-94726508-9102-4340-971d-e7a19855cd1c.png)
