### ISSUE TITLE
[CAL-1435] Emptyscreen for App Store if no external app has been configured

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8154]
right now we only show Cal Video and instead we should show our EmptyScreen saying "No app has been configured yet. Please contact your admin"

![CleanShot 2023-04-08 at 18 46 47@2x](https://user-images.githubusercontent.com/8019099/230733141-19ec9de3-4c56-4cad-95e7-89f0621a09f6.jpg)

<sub>[CAL-1435](https://linear.app/calcom/issue/CAL-1435/emptyscreen-for-app-store-if-no-external-app-has-been-configured)</sub>

**Comment by joeshajan** [comment]
Do we already have a component for that?

I would like to work on this can you assign this to me?

**Comment by PeerRich** [comment]
we should probably jsut show the `<Emptyscreen/>` if no apps are installed
