### ISSUE TITLE
[CAL-1436] Install cal.com prod instance on Flight Control

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#8156]
fc.cal.com

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1436](https://linear.app/calcom/issue/CAL-1436/install-calcom-prod-instance-on-flight-control)</sub>

**Comment by keithwillcode** [comment]
@zomars Can you confirm that we didn't see much improvement in terms of performance here?

**Comment by zomars** [comment]
Got it on hold as there were some quirks when deploying with a custom domain, but the overall performance was pretty similar.
