### ISSUE TITLE
[CAL-1437] booker: missing shadow for timezone dropdown

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8159]
this:

![image](https://user-images.githubusercontent.com/8019099/230768307-9cddbf41-3048-4396-9ea0-2fd158f58f4e.png)

should be:

![CleanShot 2023-04-09 at 12 48 30@2x](https://user-images.githubusercontent.com/8019099/230768305-c1ee21bd-06da-4b0d-940e-7b48089ed39b.jpg)

<sub>[CAL-1437](https://linear.app/calcom/issue/CAL-1437/booker-missing-shadow-for-timezone-dropdown)</sub>

**Comment by sumitshinde-84** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by sean-brydon** [comment]
Sorry @sumitshinde-84 missed this comment I can assign it to you if youre still interested in picking this up

**Comment by sumitshinde-84** [comment]
@PeerRich Yes, I am still interested to resolve issue

**Comment by sumitshinde-84** [comment]
Thank you so much  @Udit-takkar for assigning this issue to me. Additionally, I have already submitted a pull request in which I resolved the issue.
