### ISSUE TITLE
[CAL-1439] toggle: keep white on "off"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8161]
![CleanShot%202023-04-09%20at%2011 10 46@2x](https://user-images.githubusercontent.com/8019099/230768413-b54c992d-fc8e-40f9-ae66-41e8d07e21ac.jpg)

should be:

![CleanShot 2023-04-09 at 12 52 53@2x](https://user-images.githubusercontent.com/8019099/230768435-2cd6774c-671f-48d8-a3c4-992525c0ce9d.jpg)

<sub>[CAL-1439](https://linear.app/calcom/issue/CAL-1439/toggle-keep-white-on-off)</sub>

**Comment by lapaz17** [comment]
@PeerRich I cannot access linear link you provided. I was going to investigate where this occurred. It would be my first issue (albeit it is taken).

**Comment by sean-brydon** [comment]
This got fixed with brand colour implementation
