### ISSUE TITLE
[CAL-1440] refactor: fix active states of inputs 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8162]
right now this has 3 different active states:

https://user-images.githubusercontent.com/8019099/230768459-e2356c47-1bbe-4914-be47-472ff02d3346.mp4

this is because its not using our design system input classes and still use old `<input className`

Figma: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=309-44674

<sub>[CAL-1440](https://linear.app/calcom/issue/CAL-1440/refactor-fix-active-states-of-inputs)</sub>

**Comment by sumitshinde-84** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by joeshajan** [comment]
So we are expecting this input field, right?

![image](https://user-images.githubusercontent.com/69904519/230846230-d8dea53b-1f1c-43bd-a40b-3b9ea4c3533c.png)

**Comment by G3root** [comment]
fixed by #8165
