### ISSUE TITLE
[CAL-1441] dark banners for upgrade screens

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8163]
![CleanShot 2023-04-09 at 13 26 02@2x](https://user-images.githubusercontent.com/8019099/230769825-ef7fca06-fffb-4100-92c9-349607c1e730.jpg)

<sub>[CAL-1441](https://linear.app/calcom/issue/CAL-1441/dark-banners-for-upgrade-screens)</sub>

**Comment by sumitshinde-84** [comment]
I would like to work on this issue, can you please assign it to me?
