### ISSUE TITLE
[CAL-1442] CalDAV recurring events only block the first occurence

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#8166]
Currently, for recurring events, the availability check only blocks the first occurrence even if another occurrence is present in the month.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1442](https://linear.app/calcom/issue/CAL-1442/caldav-recurring-events-only-block-the-first-occurence)</sub>

**Comment by syclops** [comment]
@alishaz-polymath Thanks for the work on #8031. I'm currently still seeing this bug on v.2.7.15-h-ce on cal.com.

On Fridays I only have 12:00 and 12:30 open. This coming Friday, that is what's shown, but on the following Friday, it still shows me as available at every possible time during the working day. Would you like me to:

- Make a new issue?
- Reopen the old one (#8070)?
- Discuss on the PR (#8031)?
- Continue discussing here?

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath Thanks for the work on #8031. I'm currently still seeing this bug on v.2.7.15-h-ce on cal.com.
> 
> On Fridays I only have 12:00 and 12:30 open. This coming Friday, that is what's shown, but on the following Friday, it still shows me as available at every possible time during the working day. Would you like me to:
> 
> * Make a new issue?
> * Reopen the old one ([Recurring CalDAV events only show as unavailable on the next occurrence #8070](https://github.com/calcom/cal.com/issues/8070))?
> * Discuss on the PR ([Caldav/refactor: Mutiple Fixes and General code improvement #8031](https://github.com/calcom/cal.com/pull/8031))?
> * Continue discussing here?

Hey there @syclops 
It is merged but not released yet. Please give it time to release and retest thereafter. If the issue still persists, comment here and we'll sort it out on a call 🙌
