### ISSUE TITLE
[CAL-1448] banner for admins to show if the current version is not the latest

### ISSUE THREAD

**Issue by G3root** [calcom/cal.com#8179]
Add banner for admins to show if current version is not the latest, showing different severities depending on major, minor or patches version diff

Created via Threads. See full discussion: [https://threads.com/34462886080](https://threads.com/34462886080)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1448](https://linear.app/calcom/issue/CAL-1448/banner-for-admins-to-show-if-the-current-version-is-not-the-latest)</sub>

**Comment by PeerRich** [comment]
i like this idea

**Comment by PeerRich** [comment]
there should be a github API to check for latest tagged relase
