### ISSUE TITLE
Discord URL validation incorrect

### ISSUE THREAD

**Issue by elliottcal** [calcom/cal.com#8182]
### Issue Summary

Using the new Discord App on V2.7.10 (self hosted), the URL validation doesn't allow Discord links that are not discord.gg e.g. discord.com/channels...does not work.

It should be able to handle discord.gg and discord.com links.

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/124416829/231090408-4ced210b-c200-4acb-adf2-f5c36124414e.png">

### Steps to Reproduce

1. Create a new or use existing event type
2. Add a location
3. Click Discord
4. Add a Discord URL that isn't discord.gg
5. Shows validation error

### Technical details
1. Microsoft Edge -  111.0.1661.44 (Official build) (arm64)

**Comment by niduy** [comment]
The URL from the example works as expected in 2.8.1

**Comment by elliottcal** [comment]
Still doesn't work in 2.8.5
<img width="563" alt="SCR-20230420-lbfa-2" src="https://user-images.githubusercontent.com/124416829/233350415-070614e1-09b6-406e-9000-29de36e7823b.png">

**Comment by elliottcal** [comment]
Still doesn't work in V2.8.9

**Comment by hariombalhara** [comment]
It expects discord.gg

**Comment by elliottcal** [comment]
That's exactly what I've shared above.  It should also be able to handle discord.com

**Comment by hariombalhara** [comment]
cc @PeerRich

**Comment by PeerRich** [comment]
yeah lets allow both.

the discord.gg is the invite link
