### ISSUE TITLE
[CAL-1451] Cancelled booking doesn't show the booker any more

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8185]
Someone booked a call with me. I cancelled it and now their details no longer show up on the booking when I view the booking link. It shows in the email correctly.

Email:

![CleanShot 2023-04-11 at 12.04.41@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1aa34407-4ec0-42ef-899f-22e07dcd1710/73d84371-8ffc-40ce-bc90-57667b42d330)

Booking:

![CleanShot 2023-04-11 at 12.03.33@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1198d513-5bcf-41cc-87d9-214c10d06a1e/5c143c59-feab-4a09-8d36-d646f3f01183)

[View the booking](https://app.cal.com/booking/cZkScdhAQTURUnHg9MA2EF?allRemainingBookings=false&email=)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1451](https://linear.app/calcom/issue/CAL-1451/cancelled-booking-doesnt-show-the-booker-any-more)</sub>

**Comment by Jaibles** [comment]
@G3root have you had a chance to look at this yet?

**Comment by G3root** [comment]
@Jaibles there's a PR up for that but it needs some confirmation from @zomars or @emrysal
