### ISSUE TITLE
[CAL-1452] Darkmode issues master list

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#8186]
Issues:
- [x] Next themes requiring a hard refresh when changing from forced lightmode -> darkmode (https://github.com/calcom/cal.com/pull/8188) 
- [x] Required label '*' needs `text-emphasis`
- [x] Input add on leading and add on suffix border needs updating
- [x] Check all divide-y -> any without a colour will likely need divide-subtle also applied (See date overrides for an example)
- [x] Radio select items on booking page need text-default
- [x] Select border/shadow in light and dark was lost in transfer to tokens
- [x] webhooks border and divide color needs `border-subtle divide-subtle` 
- [x] "Powered By" needs text color updating 
- [ ] <meta theme> needs updating on mobile - darkmode still has light searchbar
- [x] Mobile "invert" logo trick doesn't seem to be working - Cal.com logo is still black
- [x] Availability skeleton hover 
- [x] App Store markdown some text isnt the right colour -> This is due to the styling being applied by `prose` and not really us - need to target them individually to update 

<sub>[CAL-1452](https://linear.app/calcom/issue/CAL-1452/darkmode-issues-master-list)</sub>

**Comment by PeerRich** [comment]
![image](https://user-images.githubusercontent.com/8019099/231129856-92b0f5eb-39ef-4974-be05-6c44cea1d9c4.png)

**Comment by PeerRich** [comment]
![image](https://user-images.githubusercontent.com/8019099/231129880-59298b5d-d050-4073-be2f-4e09882b939a.png)

**Comment by PeerRich** [comment]
![image](https://user-images.githubusercontent.com/8019099/231129897-e5d6f233-9f15-453d-90ee-b084b40e7248.png)

**Comment by PeerRich** [comment]
![image](https://user-images.githubusercontent.com/8019099/231129942-0369c5f5-ad0e-43b2-8b23-effc9383c86d.png)

**Comment by RainerZufall9393** [comment]
The selection of the duration of the call is also difficult to read
<img width="265" alt="Bildschirmfoto 2023-04-11 um 14 35 16" src="https://user-images.githubusercontent.com/126205884/231164051-7667d0f8-c300-4ba6-ba43-7c9224e80d31.png">

**Comment by emrysal** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/1046695/231439576-6f5f4b90-5a95-4078-b159-6bfaed23c5dc.png">
