### ISSUE TITLE
[CAL-1453] Update https://console.cal.dev/ in docs.cal.com

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8187]
![CleanShot 2023-04-11 at 17.06.45@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/91eb1ba5-d6b7-45a6-9ae8-6209cc6e2694/87fdc1b4-9a1c-4cbf-b42c-b2ea3f33a418)

[https://cal.com/docs/how-to-guides/acquire-and-manage-a-license-key](https://cal.com/docs/how-to-guides/acquire-and-manage-a-license-key)

that needs to be updated

Lets add this: 59c0bed7-8b21-4280-8514-e022fbfc24c7

for localhost testing in a sandbox

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1453](https://linear.app/calcom/issue/CAL-1453/update-httpsconsolecaldev-in-docscalcom)</sub>

**Comment by shirazdole** [comment]
cc @PeerRich @alishaz-polymath

**Comment by alishaz-polymath** [comment]
Done!
