### ISSUE TITLE
[CAL-1460] Add mail catching service for local development

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#8199]
Some options:

* [MailSlurper](https://github.com/mailslurper/mailslurper)
* [MailCatcher](https://mailcatcher.me/)
* [MailDev](https://maildev.github.io/maildev/)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1460](https://linear.app/calcom/issue/CAL-1460/add-mail-catching-service-for-local-development)</sub>

**Comment by Jonathan1599** [comment]
So, after thinking this through, I think having a service like MailDev or [MailHog](https://github.com/mailhog/MailHog) running in docker using the docker-compose file triggered by running `yarn dx` would be the best and simplest approach to monitor emails being sent in a local environment. I would of course have to change the values assigned to env variables in .env.example namely `EMAIL_SERVER_HOST` and `EMAIL_SERVER_PORT`.

Let me know if this approach is good or if anyone had something else in mind.

**Comment by keithwillcode** [comment]
Sounds like a good approach, @Jonathan1599! Will look at your PR soon. Thanks so much 🙏🏼
