### ISSUE TITLE
[CAL-1462] Add paid booking metadata to Stripe

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#8205]
Recently a Customer asked to add booking metadata to Stripe so they can know from Stripe what booking it is related too.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1462](https://linear.app/calcom/issue/CAL-1462/add-paid-booking-metadata-to-stripe)</sub>

**Comment by PeerRich** [comment]
this is actually higher priority, i had 2 more customers asking

**Comment by zomars** [comment]
@PeerRich what specific data should we add? The whole booking object?

**Comment by akash1520** [comment]
Can I work on this? It doesn't seem that hard.

**Comment by PeerRich** [comment]
go for it @akash1520

**Comment by PeerRich** [comment]
@akash1520  still interested?

**Comment by kcrimi** [comment]
@PeerRich I've opened a PR to accomplish this
https://github.com/calcom/cal.com/pull/11221
