### ISSUE TITLE
[CAL-1464] round robin bookable even tho fixed host is OOO

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8207]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1464](https://linear.app/calcom/issue/CAL-1464/round-robin-bookable-even-tho-fixed-host-is-ooo)</sub>

**Comment by CarinaWolli** [comment]
Looks like this happens when the fixed host has a date override. I'll take a look at this one

**Comment by PeerRich** [comment]
fix had to be reverted

**Comment by CarinaWolli** [comment]
Fixed here: https://github.com/calcom/cal.com/pull/9802
