### ISSUE TITLE
HubSpot CRM app missing on self hosted 

### ISSUE THREAD

**Issue by melakhvision** [calcom/cal.com#8216]
I have made a self hosted installation but the hubspot CRM app is missing.

![hubsport crm missing](https://user-images.githubusercontent.com/45154979/231318558-0fa2e305-1146-49c5-81c1-642c3fe54420.png)

But the hubspot exist on the paid cal online app.
![hubspot cal](https://user-images.githubusercontent.com/45154979/231319002-233b9c70-0b4c-4a6c-82ce-be738e68722a.png)

### Issue Summary

Do I need to have a licence or does it exist only on specific cal version

### Steps to Reproduce

1. I'm using Ubuntu server
2. I deploy cal using docker
3. Everything is working except what I have mentionned.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
HubSpot CRM app missing on self hosted

**Comment by melakhvision** [comment]
Any help ?

**Comment by PeerRich** [comment]
you need to add your credentials and activate the app in the admin settings
