### ISSUE TITLE
Heroku: slug size too big

### ISSUE THREAD

**Issue by eduardstal** [calcom/cal.com#8221]
### Issue Summary

```
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
 !     Compiled slug size: 999.9M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
```

### Steps to Reproduce

1. Fork cal.com
2. Update yarn.lock file by running `yarn`. Push the modified yarn.lock to the fork. 
3. Create a heroku app from template. `https://dashboard.heroku.com/new?template=https://github.com/user/fork`

### Technical details

Not necessary 
Fork: https://github.com/eduardstal/calendar

## Additional details.
The default "Deploy to heroku" button from README is broken. 
```
       ➤ YN0000: ┌ Post-resolution validation
       ➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
       ➤ YN0000: └ Completed in 0s 314ms
```

If that wouldn't happen, the deploy would still fail due to the Prisma DB not migrating automatically. To circumvent this 
`cd packages\prisma\schema.prisma`
Get the postgres url after the build has been started in heroku, modify 
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL") ## for some reason, this will not read the URL from .env <- Modify from
  url = postgresql://<user>:<pass>@<db-host>:<db-port> <- Modify to
}
``` 
Modify the URL there and run `yarn workspace @calcom/prisma db-migrate` before your build on heroku.com finishes, and is able to notice that the schema does not exist.

**Comment by eduardstal** [comment]
Is there any release where the slug size is appropriate for Heroku deployments? If yes, what release version should I look into?

**Comment by gabamnml** [comment]
any update about this?

**Comment by PeerRich** [comment]
i dont think we will get the size down right now. seems like heroku also stopped free deployments so maybe its better to move on

**Comment by PeerRich** [comment]
unless someone has an idea how to fix this

**Comment by vojtabiberle** [comment]
Same issue here

**Comment by PeerRich** [comment]
we stopped supporting heroku for noiw
