### ISSUE TITLE
[CAL-1469] public booking - Improve location display & selection when multiple are available

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8222]
[https://www.loom.com/share/f5bd0bea14e647dfaa7175993732ed66](https://www.loom.com/share/f5bd0bea14e647dfaa7175993732ed66)

![CleanShot 2023-04-12 at 10 02 24@2x](https://user-images.githubusercontent.com/4536123/231392689-ac5c6f8c-caa8-40d0-9d5f-84c5b644ed2a.png)

[View designs in Figma](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=3636%3A253394&t=jHoAds6GP8j7vb3t-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1469](https://linear.app/calcom/issue/CAL-1469/public-booking-improve-location-display-and-selection-when-multiple)</sub>

**Comment by PeerRich** [comment]
i think this has been addressed already, no @JeroenReumkens ?

**Comment by JeroenReumkens** [comment]
Yes, this has been fixed an discussed with @Jaibles 
Right now looks like this: 
![CleanShot 2023-05-17 at 19 37 12@2x](https://github.com/calcom/cal.com/assets/2969573/12e0a53b-7dfa-4741-b365-52e340901290)
![CleanShot 2023-05-17 at 19 37 16@2x](https://github.com/calcom/cal.com/assets/2969573/a024973f-f6bc-4add-8e19-ebe9fe270eee)

We landed on this solution eventually after this discussion: 
![CleanShot 2023-05-17 at 19 38 36@2x](https://github.com/calcom/cal.com/assets/2969573/e758aa6b-4002-4bf4-b562-eba75183292a)

If you agree I think we can close this @PeerRich
