### ISSUE TITLE
[CAL-1471] Customer can't enable 2FA

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8225]
Created via Threads. See full discussion: [https://threads.com/34463528868](https://threads.com/34463528868)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1471](https://linear.app/calcom/issue/CAL-1471/customer-cant-enable-2fa)</sub>

**Comment by zomars** [comment]
Will close until we can properly reproduce
