### ISSUE TITLE
[CAL-1472] Make sure that apps/web/public/app-store doesn't have stale files.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8226]
This happened I guess because sylaps was renamed in the middle of development and our current logic doesn't remove old files and the wrong path keeps working locally.
<img width="1113" alt="Screenshot 2023-04-12 at 2 42 14 PM" src="https://user-images.githubusercontent.com/1780212/231411308-030dac03-75a5-4aab-8380-9d809fa22909.png">

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/8224#discussion_r1163851354_
            

<sub>[CAL-1472](https://linear.app/calcom/issue/CAL-1472/make-sure-that-appswebpublicapp-store-doesnt-have-stale-files)</sub>

**Comment by gitstart-calcom** [comment]
The folder does not have any stale files
![Screenshot 2023-09-11 at 8 25 35 PM](https://github.com/calcom/cal.com/assets/121884634/834fa46f-55c8-48cc-9412-a47a8f79ea98)
