### ISSUE TITLE
[CAL-1479] Cal.com booking seeing events on a calendar that is no longer connected to the account.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8248]
[https://www.loom.com/share/0ba51d820af84896983c97f8b261897d](https://www.loom.com/share/0ba51d820af84896983c97f8b261897d)

Created via Threads. See full discussion: [https://threads.com/34463893484](https://threads.com/34463893484)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1479](https://linear.app/calcom/issue/CAL-1479/calcom-booking-seeing-events-on-a-calendar-that-is-no-longer-connected)</sub>

**Comment by emrysal** [comment]
Fixed back in April
