### ISSUE TITLE
[CAL-1486] windows: scroll bar 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8254]
![image](https://user-images.githubusercontent.com/8019099/231854088-deb9cc51-6e54-4387-97b3-8ca673511cb9.png)

![image](https://user-images.githubusercontent.com/8019099/231854301-5fd9c12e-bc0f-41c6-9e7e-7702f3f0e11c.png)
![image](https://user-images.githubusercontent.com/8019099/231854374-895976f3-85d7-4ac9-b5ed-fc6f1c4d8b53.png)

![image](https://user-images.githubusercontent.com/8019099/231855247-09263d0e-19e6-43d7-ad94-c8f9c6c4fdbb.png)

<sub>[CAL-1486](https://linear.app/calcom/issue/CAL-1486/windows-scroll-bar)</sub>

**Comment by PeerRich** [comment]
we could use our scroll-bar class here

**Comment by joe-shajan** [comment]
Do we already have scrollbar classes set up? If yes where can I find that?

I would like to tackle this. Can you assign this to me?
