### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#8281]
### Issue Summary

I am going through the documentation to use the quick starter but it got me this issue:

@calcom/prisma:db-up: cache bypass, force executing e76312803b2da5cd
@calcom/prisma:db-up: failed to read \cal.com\packages\prisma\.env: line 1: unexpected character "/" in variable name
@calcom/prisma:db-up: failed to read \cal.com\packages\prisma\.env: line 1: unexpected character "/" in variable name
@calcom/prisma:db-up: ERROR: command finished with error: command (C:\Users\Abdurrahman\Documents\GitHub\cal.com\packages\prisma) yarn run db-up exited (1)

**Comment by joe-shajan** [comment]
I'm also facing this same issue. I don't know why this is happening. and I'm using Windows.

and what I do to fix this is add the `DATABASE_URL` in `packages > prisma > .env` and remove `../../.env`

this is a temporary fix. and we can wait for the response from someone on the team

![image](https://user-images.githubusercontent.com/69904519/232225724-3e3f3691-6125-48a1-8d2b-44ebb006113e.png)

**Comment by a0m0rajab** [comment]
I believe this is related to this slack thread: https://app.slack.com/client/T01N4FWPGPP/C02QP4Z3G4E 

Thre is such an issue previously: https://github.com/calcom/cal.com/issues/2396 

Plus we can see this guide for that: https://cal.com/docs/how-to-guides/how-to-troubleshoot-symbolic-link-issues-on-windows#enable-symbolic-links 

it would help, for me I went to manual setup to be able to run the program.
