### ISSUE TITLE
[CAL-1498] dark <meta> theme on "standalone"

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8283]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

the white appbar should be dark on dark mode

steps to reproduce:

- on iOS, visit app.cal.com on safari 
- add to homescreen
- open 

![image](https://user-images.githubusercontent.com/8019099/232170593-57e45b13-9f95-4dac-a74e-cca3281e74f3.jpeg)

<sub>[CAL-1498](https://linear.app/calcom/issue/CAL-1498/dark-meta-theme-on-standalone)</sub>

**Comment by PeerRich** [comment]
`<meta name="theme-color" media="(prefers-color-scheme: light)" content="cyan" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="black" />`

**Comment by MayurAnklekar** [comment]
Hi, can you assign this issue to me?

**Comment by tap0212** [comment]
hi @PeerRich raised a fix PR #8583 please have a look.
LMK if there's anything needed here 🚀
