### ISSUE TITLE
Managed Event-types not working with workflows

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#8288]
### Issue Summary

Managed event-types can't be added to workflows by either team owner or the user itself.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by CarinaWolli** [comment]
@leog Not a bug and coming in the next version, right?
