### ISSUE TITLE
[CAL-1501] Date ranges to Date Overwrites (not only one day at a time)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8299]
as a user I want to

... be able to select a date range in date overwrites 

alternatively

... I need to click every day individually

<sub>[CAL-1501](https://linear.app/calcom/issue/CAL-1501/date-ranges-to-date-overwrites-not-only-one-day-at-a-time)</sub>

**Comment by shohan2001** [comment]
@PeerRich Can you please assign this to me
