### ISSUE TITLE
Add DateTime to booking questions input types

### ISSUE THREAD

**Issue by greekquestionmark** [calcom/cal.com#8306]
### Is your proposal related to a problem?

I need to age-verify potential customers for specific classes that are required by law to be age restricted. That way, instantly determine eligibility. For other course types, DateTime could be used for implementing custom age-verification through Zapier or similar integrations. DateTime can also be used to assess currency of credentials or other timeframes that aren't specific to age.

### Describe the solution you'd like

Implement age-verification. Allow the custom type to determine what the age restriction is and check the user's input against that value.

Add error page for throwing 'too young' or 'future date' when expecting a date in the past, and vis versa.

### Describe alternatives you've considered

I've looked into the integrations, but there's no clear solutions within those integrations. I've considered short-text as a solution, but I'm not a developer and wouldn't know where to start making these filters. 
### Additional context

This is a feature request by and for an end-customer, not a developer.
I provide firearms instruction as one of many services. Due to current interpretations of International Traffic in Arms Regulations stemming from the Arms Export Control Act of 1976, I cannot offer training anyone ineligible to purchase a firearm per ATF Form 4473. One of the restricting items on that form is age, and I need to ensure that I am in compliance.

**Comment by Dax911** [comment]
While this is a specific use case and problem. I think this is something that is worth considering. In the meantime consider implementing age verification before making an appointment for the course.

**Comment by PeerRich** [comment]
can you not just ask for the birthday year as a number field?

**Comment by PeerRich** [comment]
i think this should be solved as @Dax911 mentioned before showing the link. i don't think we'll be adding this anytime soon

**Comment by PeerRich** [comment]
like this:
![CleanShot 2023-05-17 at 22 09 15@2x](https://github.com/calcom/cal.com/assets/8019099/9d9f2e56-038f-4284-8dae-67882f2650bc)

you can also combine a booking question with our opt-in bookings to require confirmation first: https://cal.com/resources/feature/opt-in
