### ISSUE TITLE
[CAL-1476] Overriden availability doesn't change to different timezone if you change it on the booking page

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8329]
![Screenshot 2023-04-12 at 16.52.38.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b01a1cc1-734e-481f-917e-6cf0c2bfdde1/35d2fb4d-a674-4fa8-a93d-bff0ae0a33f8)

![Screenshot 2023-04-12 at 16.52.48.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/83bb4fe8-4845-4965-98b6-315bc0d58c4d/3250699c-90eb-4764-a9f5-058bc65262d6)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1476](https://linear.app/calcom/issue/CAL-1476/overriden-availability-doesnt-change-to-different-timezone-if-you)</sub>

**Comment by PeerRich** [comment]
fix had to be reverted
