### ISSUE TITLE
Offset start time for 25-/50-minute meetings

### ISSUE THREAD

**Issue by mxstbr** [calcom/cal.com#8336]
### Is your proposal related to a problem?

I have back-to-back meetings all day and would like to have automatic biobreaks / communications checkin time in between every single one.

### Describe the solution you'd like

1. **Only allow 25- & 50-minute meetings** (so that each hour technically has 10 minutes of break). The reason that this alone isn't enough is because when meetings start at :00 and end at :50, people (particularly external ones that are used to 30/60 minute meetings) don't realize and go over.
2. **Only allow scheduling meeting at :05 / :10 past the full hour/full half** hour. This will make it such that all my meetings are e.g. 1:35pm to 2:00pm or 10:10am to 11:00am. By starting the meeting late, all participants have to start at that time and they can't go over.

### Describe alternatives you've considered

I currently use SavvyCal, which doesn't support this unfortunately.

### Additional context

I'd be happy to switch to (and thus pay for) a scheduling solution that allows me to do this.

**Comment by mxstbr** [comment]
Can I put [a bounty](https://console.algora.io/org/cal/bounties) on this? 🤔

**Comment by PeerRich** [comment]
more context: https://twitter.com/mxstbr/status/1649801791444520967

and:  https://twitter.com/mxstbr/status/1649805752801071105

**Comment by ernestwong1027** [comment]
I can pickup this PR

**Comment by rjackson** [comment]
Ah I've also been looking into this one! I've got all the code ready except for some of the frontend form changes.

**Comment by kt0598023-collab** [comment]
/attempt #8336
/claim #8336

# Fix: Configurable Start-Time Buffers & Speedy 25m/50m Slots (#8336)

- **Bounty Amount:** $150 USD
- **Solution Verification:** Passed unit test suite for offset calculations.

Implemented `SlotOffsetEngine` enabling 25-minute and 50-minute meeting slots with configurable start-time buffers and offset alignment.
