### ISSUE TITLE
save button in close.com dialog box not visible in dark mode

### ISSUE THREAD

**Issue by joe-shajan** [calcom/cal.com#8358]
### Issue Summary

![image](https://user-images.githubusercontent.com/69904519/232846592-b154901d-aec5-4851-841c-8695fa11e41f.png)

**Comment by 9520prashant** [comment]
Hey @joe-shajan I can Fix this issue through changing the button color can you assign me this issue ?

**Comment by PeerRich** [comment]
this has been fixed
