### ISSUE TITLE
Deployment issue on Railway

### ISSUE THREAD

**Issue by rittmang** [calcom/cal.com#837]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Deployment with current codebase fails in the Railway environment, possibly due to a Next issue

### Steps to Reproduce

1. Deploying on Railway

### Technical details
- Node.js version: v14.18.0 apparently. Here's a complete log:

=================
Using Buildpacks!
=================

20: Pulling from heroku/buildpacks
Digest: sha256:e35818056b33883bba8434c2f087bcd680c286040931fb507f2262c6d2c3d66b
Status: Image is up to date for heroku/buildpacks:20

20: Pulling from heroku/pack
Digest: sha256:301fce41b887a049dd152ee83a185d49ee8ec002a307a9ffd95eec9ad1be45ce
Status: Image is up to date for heroku/pack:20
===> DETECTING
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
heroku/nodejs-yarn       0.1.5
===> ANALYZING
Previous image with name "registry.railway.app/ef28074b-eff6-431d-8fe5-3b848eb5ea92" not found
===> RESTORING
===> BUILDING
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[Installing Node]
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v14.18.0

[Parsing package.json]
[INFO] Parsing package.json

[Installing yarn]
[INFO] Installing yarn@1.22.15
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v6.14.15 from Node
[INFO] Installing node modules
npm WARN deprecated @types/stripe@8.0.417: This is a stub types definition. stripe provides its own type definitions, so you do not need this installed.
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> prisma@2.30.3 preinstall /workspace/node_modules/prisma
> node scripts/preinstall-entry.js

> prisma@2.30.3 install /workspace/node_modules/prisma
> node scripts/install-entry.js

> @prisma/engines@2.30.1-2.b8c35d44de987a9691890b3ddf3e2e7effb9bf20 postinstall /workspace/node_modules/@prisma/engines
> node download/index.js

> core-js@3.18.1 postinstall /workspace/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> https://paypal.me/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> @prisma/client@2.30.3 postinstall /workspace/node_modules/@prisma/client
> node scripts/postinstall.js

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.30.3) to ./node_modules/@prisma/client in 503ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

> cypress@8.5.0 postinstall /workspace/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 8.5.0)

[STARTED] Task without title.
[TITLE]  Downloading Cypress      0% 0s
[TITLE]  Downloading Cypress      3% 3s
[TITLE]  Downloading Cypress      10% 2s
[TITLE]  Downloading Cypress      17% 1s
[TITLE]  Downloading Cypress      26% 1s
[TITLE]  Downloading Cypress      35% 1s
[TITLE]  Downloading Cypress      44% 1s
[TITLE]  Downloading Cypress      52% 1s
[TITLE]  Downloading Cypress      62% 0s
[TITLE]  Downloading Cypress      72% 0s
[TITLE]  Downloading Cypress      81% 0s
[TITLE]  Downloading Cypress      91% 0s
[TITLE]  Downloading Cypress      100% 0s
[TITLE]  Downloaded Cypress     
[SUCCESS]  Downloaded Cypress     
[STARTED] Task without title.
[TITLE]  Unzipping Cypress        0% 0s
[TITLE]  Unzipping Cypress        1% 53s
[TITLE]  Unzipping Cypress        1% 54s
[TITLE]  Unzipping Cypress        1% 55s
[TITLE]  Unzipping Cypress        1% 56s
[TITLE]  Unzipping Cypress        1% 57s
[TITLE]  Unzipping Cypress        1% 58s
[TITLE]  Unzipping Cypress        1% 59s
[TITLE]  Unzipping Cypress        1% 60s
[TITLE]  Unzipping Cypress        2% 30s
[TITLE]  Unzipping Cypress        2% 31s
[TITLE]  Unzipping Cypress        2% 32s
[TITLE]  Unzipping Cypress        2% 33s
[TITLE]  Unzipping Cypress        2% 34s
[TITLE]  Unzipping Cypress        3% 22s
[TITLE]  Unzipping Cypress        3% 23s
[TITLE]  Unzipping Cypress        3% 24s
[TITLE]  Unzipping Cypress        3% 25s
[TITLE]  Unzipping Cypress        4% 18s
[TITLE]  Unzipping Cypress        4% 19s
[TITLE]  Unzipping Cypress        4% 20s
[TITLE]  Unzipping Cypress        4% 21s
[TITLE]  Unzipping Cypress        4% 22s
[TITLE]  Unzipping Cypress        4% 24s
[TITLE]  Unzipping Cypress        4% 25s
[TITLE]  Unzipping Cypress        4% 27s
[TITLE]  Unzipping Cypress        4% 28s
[TITLE]  Unzipping Cypress        4% 29s
[TITLE]  Unzipping Cypress        5% 23s
[TITLE]  Unzipping Cypress        5% 24s
[TITLE]  Unzipping Cypress        5% 25s
[TITLE]  Unzipping Cypress        6% 21s
[TITLE]  Unzipping Cypress        6% 22s
[TITLE]  Unzipping Cypress        7% 19s
[TITLE]  Unzipping Cypress        7% 20s
[TITLE]  Unzipping Cypress        8% 18s
[TITLE]  Unzipping Cypress        9% 16s
[TITLE]  Unzipping Cypress        9% 17s
[TITLE]  Unzipping Cypress        10% 15s
[TITLE]  Unzipping Cypress        10% 16s
[TITLE]  Unzipping Cypress        11% 14s
[TITLE]  Unzipping Cypress        12% 13s
[TITLE]  Unzipping Cypress        12% 14s
[TITLE]  Unzipping Cypress        13% 12s
[TITLE]  Unzipping Cypress        13% 13s
[TITLE]  Unzipping Cypress        14% 12s
[TITLE]  Unzipping Cypress        14% 13s
[TITLE]  Unzipping Cypress        15% 12s
[TITLE]  Unzipping Cypress        16% 11s
[TITLE]  Unzipping Cypress        16% 12s
[TITLE]  Unzipping Cypress        17% 11s
[TITLE]  Unzipping Cypress        18% 11s
[TITLE]  Unzipping Cypress        19% 10s
[TITLE]  Unzipping Cypress        20% 10s
[TITLE]  Unzipping Cypress        21% 10s
[TITLE]  Unzipping Cypress        22% 10s
[TITLE]  Unzipping Cypress        23% 10s
[TITLE]  Unzipping Cypress        24% 9s
[TITLE]  Unzipping Cypress        24% 10s
[TITLE]  Unzipping Cypress        25% 9s
[TITLE]  Unzipping Cypress        26% 9s
[TITLE]  Unzipping Cypress        27% 8s
[TITLE]  Unzipping Cypress        27% 9s
[TITLE]  Unzipping Cypress        28% 8s
[TITLE]  Unzipping Cypress        29% 8s
[TITLE]  Unzipping Cypress        30% 8s
[TITLE]  Unzipping Cypress        31% 8s
[TITLE]  Unzipping Cypress        32% 7s
[TITLE]  Unzipping Cypress        33% 7s
[TITLE]  Unzipping Cypress        34% 7s
[TITLE]  Unzipping Cypress        35% 7s
[TITLE]  Unzipping Cypress        36% 7s
[TITLE]  Unzipping Cypress        37% 6s
[TITLE]  Unzipping Cypress        37% 7s
[TITLE]  Unzipping Cypress        38% 6s
[TITLE]  Unzipping Cypress        39% 6s
[TITLE]  Unzipping Cypress        40% 6s
[TITLE]  Unzipping Cypress        40% 7s
[TITLE]  Unzipping Cypress        41% 7s
[TITLE]  Unzipping Cypress        42% 7s
[TITLE]  Unzipping Cypress        43% 7s
[TITLE]  Unzipping Cypress        44% 6s
[TITLE]  Unzipping Cypress        44% 7s
[TITLE]  Unzipping Cypress        45% 6s
[TITLE]  Unzipping Cypress        45% 7s
[TITLE]  Unzipping Cypress        46% 6s
[TITLE]  Unzipping Cypress        46% 7s
[TITLE]  Unzipping Cypress        47% 6s
[TITLE]  Unzipping Cypress        48% 6s
[TITLE]  Unzipping Cypress        49% 6s
[TITLE]  Unzipping Cypress        50% 6s
[TITLE]  Unzipping Cypress        51% 6s
[TITLE]  Unzipping Cypress        52% 5s
[TITLE]  Unzipping Cypress        53% 5s
[TITLE]  Unzipping Cypress        54% 5s
[TITLE]  Unzipping Cypress        55% 5s
[TITLE]  Unzipping Cypress        56% 5s
[TITLE]  Unzipping Cypress        57% 5s
[TITLE]  Unzipping Cypress        58% 5s
[TITLE]  Unzipping Cypress        59% 4s
[TITLE]  Unzipping Cypress        60% 4s
[TITLE]  Unzipping Cypress        61% 4s
[TITLE]  Unzipping Cypress        62% 4s
[TITLE]  Unzipping Cypress        63% 4s
[TITLE]  Unzipping Cypress        64% 4s
[TITLE]  Unzipping Cypress        65% 4s
[TITLE]  Unzipping Cypress        66% 3s
[TITLE]  Unzipping Cypress        67% 3s
[TITLE]  Unzipping Cypress        68% 3s
[TITLE]  Unzipping Cypress        69% 3s
[TITLE]  Unzipping Cypress        70% 3s
[TITLE]  Unzipping Cypress        71% 3s
[TITLE]  Unzipping Cypress        72% 3s
[TITLE]  Unzipping Cypress        73% 3s
[TITLE]  Unzipping Cypress        74% 3s
[TITLE]  Unzipping Cypress        75% 2s
[TITLE]  Unzipping Cypress        76% 2s
[TITLE]  Unzipping Cypress        77% 2s
[TITLE]  Unzipping Cypress        78% 2s
[TITLE]  Unzipping Cypress        79% 2s
[TITLE]  Unzipping Cypress        80% 2s
[TITLE]  Unzipping Cypress        81% 2s
[TITLE]  Unzipping Cypress        82% 2s
[TITLE]  Unzipping Cypress        83% 2s
[TITLE]  Unzipping Cypress        100% 0s
[TITLE]  Unzipped Cypress       
[SUCCESS]  Unzipped Cypress       
[STARTED] Task without title.
[TITLE]  Finished Installation   /home/heroku/.cache/Cypress/8.5.0
[SUCCESS]  Finished Installation   /home/heroku/.cache/Cypress/8.5.0

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

> calendso@1.0.0 postinstall /workspace
> prisma generate

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.30.3) to ./node_modules/@prisma/client in 478ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

> calendso@1.0.0 prepare /workspace
> husky install

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@11.1.2 (node_modules/next/node_modules/@next/swc-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@11.1.2: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@11.1.2 (node_modules/next/node_modules/@next/swc-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@11.1.2: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@11.1.2 (node_modules/next/node_modules/@next/swc-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@11.1.2: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-multi-email@0.5.3 requires a peer of react@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-multi-email@0.5.3 requires a peer of react-dom@^16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN goober@2.0.41 requires a peer of csstype@^2.6.2 but none is installed. You must install peer dependencies yourself.

added 1525 packages from 968 contributors and audited 1537 packages in 76.542s

141 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> calendso@1.0.0 build /workspace
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Skipping validation of types...
info  - Creating an optimized production build...

> Build error occurred
Error: You cannot use different slug names for the same dynamic path ('idOrSlug' !== 'slug').
    at handleSlug (/workspace/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:90:31)
    at UrlNode._insert (/workspace/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:127:17)
    at UrlNode._insert (/workspace/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:138:40)
    at UrlNode.insert (/workspace/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:8:14)
    at /workspace/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:161:46
    at Array.forEach (<anonymous>)
    at Object.getSortedRoutes (/workspace/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:161:21)
    at /workspace/node_modules/next/dist/build/index.js:230:44
    at Span.traceFn (/workspace/node_modules/next/dist/telemetry/trace/trace.js:53:20)
    at /workspace/node_modules/next/dist/build/index.js:222:85
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! calendso@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calendso@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-10-01T10_29_30_525Z-debug.log
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51

======= Build Completed ======

Deployment failed
Build Failed! Please see output for more information

**Comment by rittmang** [comment]
Error: You cannot use different slug names for the same dynamic path ('idOrSlug' !== 'slug')

**Comment by alexonufrak** [comment]
@rittmang I've recreated this error and successfully deployed by:

1. Running `railway run npx prisma db push`
2. Go to your railway dashboard and create a user following [railway's instructions](https://blog.railway.app/p/calendso#:~:text=Next%2C%20head%20over%20to%20your,Create%20user)
3. Then `railway up`

Cal should then successfully build and deploy.

**Comment by munjalpatel** [comment]
> @rittmang I've recreated this error and successfully deployed by:
> 
> 1. Running `railway run npx prisma db push`
> 2. Go to your railway dashboard and create a user following [railway's instructions](https://blog.railway.app/p/calendso#:~:text=Next%2C%20head%20over%20to%20your,Create%20user)
> 3. Then `railway up`
> 
> Cal should then successfully build and deploy.

@alexonufrak does authentication properly work for you after you do this?
When I do this ( as described in #851 ), I keep redirected back to the login page after successful login.

**Comment by alexonufrak** [comment]
> > @rittmang I've recreated this error and successfully deployed by:
> > 
> > 1. Running `railway run npx prisma db push`
> > 2. Go to your railway dashboard and create a user following [railway's instructions](https://blog.railway.app/p/calendso#:~:text=Next%2C%20head%20over%20to%20your,Create%20user)
> > 3. Then `railway up`
> > 
> > Cal should then successfully build and deploy.
> 
> @alexonufrak does authentication properly work for you after you do this? When I do this ( as described in #851 ), I keep redirected back to the login page after successful login.

I had a similar issue. This is probably not recommended, but I rolled back the #730 commit (removed the jwt secret requirement/parameter) and was able to be properly redirected.

**Comment by PeerRich** [comment]
i believe this was fixed. happy to reopen
