### ISSUE TITLE
No availability if CalDAV app is installed

### ISSUE THREAD

**Issue by victorpaleologue** [calcom/cal.com#8370]
Today, my cal.com page says I have no availability at all.
See screenshot below:

![image](https://user-images.githubusercontent.com/8899804/233022448-112c14c8-bc3e-484e-a49c-fa0c3e3c8855.png)

My availabilities are well set:
![image](https://user-images.githubusercontent.com/8899804/233022692-702c91e2-f68a-443d-adea-870aad4b364c.png)

And my calendar is not busy at all.
So far I was using CalDAV with Nextcloud, but since I know it is still beta, I tried disabling it and using Google Calendar: the issue was still there.

Then I actually deleted the CalDAV app: it works again!

**Comment by alishaz-polymath** [comment]
Hey, is it possible for you to create a test account that I could use and debug this?

**Comment by alishaz-polymath** [comment]
Amazing!
Must be a weird stale bug. I'm closing this for now but if you manage to reproduce this issue, please feel free to re-open this 🙏 
And thanks a lot for helping us clear out the instability 🎉
