### ISSUE TITLE
[CAL-1522] When there is two different time slots for the same day it will show that day as unavailable

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8371]
[https://www.loom.com/share/37d63f458897439187531481e72a27f5](https://www.loom.com/share/37d63f458897439187531481e72a27f5)

Created via Threads. See full discussion: [https://threads.com/34465559765](https://threads.com/34465559765)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1522](https://linear.app/calcom/issue/CAL-1522/when-there-is-two-different-time-slots-for-the-same-day-it-will-show)</sub>

**Comment by PeerRich** [comment]
any update here @emrysal @CarinaWolli ?

**Comment by CarinaWolli** [comment]
This is fixed already
