### ISSUE TITLE
[CAL-1523] Setting end time for a certain day past 5pm makes the next day unavailable

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8372]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1523](https://linear.app/calcom/issue/CAL-1523/setting-end-time-for-a-certain-day-past-5pm-makes-the-next-day)</sub>

**Comment by CarinaWolli** [comment]
This got fixed with https://github.com/calcom/cal.com/releases/tag/v2.8.4.1
