### ISSUE TITLE
[CAL-1521] Rescheduling not updating my calendar

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8377]
"they get an email confirming the reschedule, but my calendar doesn't get updated nor do I get an email with the confirmation request."

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1521](https://linear.app/calcom/issue/CAL-1521/rescheduling-not-updating-my-calendar)</sub>

**Comment by keithwillcode** [comment]
This is a duplicate of #7728
