### ISSUE TITLE
[CAL-1526] Out of the many seats booked, even if only one cancels, it cancels the entire booking

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8378]
(Attachment: )

Created via Threads. See full discussion: [https://threads.com/34465600394](https://threads.com/34465600394)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1526](https://linear.app/calcom/issue/CAL-1526/out-of-the-many-seats-booked-even-if-only-one-cancels-it-cancels-the)</sub>

**Comment by CarinaWolli** [comment]
@joeauyeung Can this be closed? It works for me
