### ISSUE TITLE
"About" section in profile not updating

### ISSUE THREAD

**Issue by brianclements** [calcom/cal.com#8387]
### Issue Summary

In the Settings>Profile>About section, when I edit the text, the "Update" button doesn't activate. It does for all the other text fields. So I can't update my "About" section text. 

As a side test, I even modified both the "About" field and the "Full name" field to activate the button, but after clicking the "Update" button, the original text in the "About" section reverted and did not update, however the "Full name" text updated as expected.

### Steps to Reproduce

1. Navigate to Settings>Profile and edit the "About" section text
2. Try to click the "Update" button
   1. Expected: it is clickable and updates
   2. Actual: button doesn't activate, no updates

Alternate test

1. Edit the "About" section text and one other field so that the "Update" button activates and is clickable.
2. Click "Update" button
   1. Expected: both fields update
   2. Actual: The other field will update, but the "About" section text will revert.

### Technical details

- firefox & chrome on linux
- cal.com app v.2.8.4-h-ce

**Comment by CarinaWolli** [comment]
Fixed in main (https://github.com/calcom/cal.com/pull/8379) not yet in production
