### ISSUE TITLE
Allow custom display name in booking

### ISSUE THREAD

**Issue by abdulhdr1** [calcom/cal.com#8388]
### Is your proposal related to a problem?

I've got a big name, > 30 letters, so I don't find it aesthetically pleasing to display my full name whenever someone tries to book a meeting with me. Currently, the only way to solve this is by changing the full name setting on the profile, hence modifying the intended use of the field. 

### Describe the solution you'd like

Add a new field in the profile, like "Booking display name", that only changes the name that is shown on your booking link

**Comment by PeerRich** [comment]
can you not use this?

![CleanShot 2023-05-17 at 22 03 47@2x](https://github.com/calcom/cal.com/assets/8019099/ffa64e8f-6792-474a-834c-3677c5fe23b6)


and just hard code your name?

**Comment by abdulhdr1** [comment]
I get what you said but that changes the event name, I was referring to the page that allows the person booking an event to choose the event. 
This page:
![image](https://github.com/calcom/cal.com/assets/63007787/532eaea9-6ed3-4231-8c8d-66eb10d64299)
Allowing me to show just *Abdul Haidar* without messing up my full name on the settings
