### ISSUE TITLE
Slot picker, disable button after selection is made

### ISSUE THREAD

**Issue by cpunnelliehealth** [calcom/cal.com#8403]
Could we get the slot picker buttons to be disabled once an option is clicked? 

Right now, it’s possible to click multiple selections and the last one selected is chosen, not ideal if there is a bit of lag to process the selection:

https://user-images.githubusercontent.com/126418022/233367338-04b93ca5-b8cd-4581-93e2-ccba070711d9.mov

**Comment by RT-1904129** [comment]
Hi team 
I will fix this essue
Thanks & Regards
Rishabh Tripathi

**Comment by RT-1904129** [comment]
hi Team
I am setting the project encounter with this issue:- 
` The system cannot find the file specified.
@calcom/embed-core:build: command not found: copy
@calcom/embed-core:build: ERROR: command finished with error: command (C:\Users\Rishabh Tripathi\Downloads\Semester-8\cal.com\packages\embeds\embed-core) yarn run build exited (1)`

Can anyone please guide me on how to rectify this issue
Thanks & Regards
Rishabh Tripathi

**Comment by pranjalg13** [comment]
@cpunnelliehealth have you checked if this is happening on prod too or just local?

**Comment by PeerRich** [comment]
this is being fixed with our v2.0 booking page which is already under a feature flag: app.cal.com/api/newbooker/enable
