### ISSUE TITLE
[CAL-1537] Create a Calendar Template

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8408]
Goal:

Create  a Calendar template that can be shown in the list

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/67b52018-7319-4834-ba4a-cd8fd9cd5f7e/dcb9e03f-4ab5-48c2-b9c0-8169080dedff)

What that Calendar should do to keep the code quality good and make new calendar apps that come up maintainable.

**Utilities like the following should be abstracted, to be shared across all Calendar apps and other non calendar apps as well**

* isTokenValid
* refreshToken
* ....

Should have logger in built and debug logs added at appropriate places already using the shared utilities.

Google Calendar can be taken as an example Calendar app for creating the template and then we can refactor it achieve the goal

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1537](https://linear.app/calcom/issue/CAL-1537/create-a-calendar-template)</sub>

**Comment by PeerRich** [comment]
@hariombalhara if you arent working on the templates, those ticket need better descriptions 🙏

**Comment by hariombalhara** [comment]
@PeerRich Done.
