### ISSUE TITLE
Zoom app not including meeting location

### ISSUE THREAD

**Issue by shunkakinoki** [calcom/cal.com#841]
Found a bug? Please fill out the sections below. 👍
### Issue Summary

Zoom app is not including meeting location

### Steps to Reproduce

1. Installed zoom app
2. Zoom app does not include meeting location
3. Can't do anything

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
- Node.js version
- Anything else that you think could be an issue.

**Comment by Jaibles** [comment]
Resolved

**Comment by chan-onehash** [comment]
Hi.. {{ .Subscriber.Name }}
        
        
        
        
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        
    

     
    
        










Building the AWS of Open Source








Hi there! Ciarán Hanrahan!




Hope you're all doing great! I wanted to fill you in on how we're supercharging our operations with Cal at OneHash. Here's the scoop:




1. Scheduling Interviews: Cal ID keeps our interview scheduling sleek and hassle-free, ensuring everyone finds the perfect slot without the back-and-forth.




2. Group Interviews: From panel discussions to team huddles, Cal’s group scheduling feature helps us sync up multiple schedules effortlessly.




3. Sales Calls: Our sales team crushes it with Cal ID, booking meetings with prospects faster than ever and seamlessly integrating with our sales pipeline.




4. Customer Success Calls: OneHash Cal keeps us on point with clients, making sure we deliver top-notch support and follow-ups on time.











OneHash Cal








Plus, we've got an exciting offer: We are happy to offer OneHash Cal for free forever for your fund and portfolio companies. 🌟




Let's sync up soon to brainstorm how we can optimize OneHash Cal even more for your workflows. Just pick a slot that works for you using my Calendar ID




Looking forward to our chat! 🚀




Cheers, RohitCofounder & CEO




---About OneHash:OneHash, a pioneering startup, is revolutionizing the open-source software industry for SMBs with its suite of cloud-based applications. Our vision of creating a 'Creator’s Economy' rewards open-source contributions, fostering innovation and empowering SMBs with advanced, affordable technology tools.
 
3cba4347-27bd-42e3-b623-30d78fef35bd




    
    
    
        Powered by OneHash

**Comment by chan-onehash** [comment]
Hi.. {{ .Subscriber.Name }}
        
        
        
        
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        
    

     
    
        










Building the AWS of Open Source








Hi there! Ciarán Hanrahan!




Hope you're all doing great! I wanted to fill you in on how we're supercharging our operations with Cal at OneHash. Here's the scoop:




1. Scheduling Interviews: Cal ID keeps our interview scheduling sleek and hassle-free, ensuring everyone finds the perfect slot without the back-and-forth.




2. Group Interviews: From panel discussions to team huddles, Cal’s group scheduling feature helps us sync up multiple schedules effortlessly.




3. Sales Calls: Our sales team crushes it with Cal ID, booking meetings with prospects faster than ever and seamlessly integrating with our sales pipeline.




4. Customer Success Calls: OneHash Cal keeps us on point with clients, making sure we deliver top-notch support and follow-ups on time.











OneHash Cal








Plus, we've got an exciting offer: We are happy to offer OneHash Cal for free forever for your fund and portfolio companies. 🌟




Let's sync up soon to brainstorm how we can optimize OneHash Cal even more for your workflows. Just pick a slot that works for you using my Calendar ID




Looking forward to our chat! 🚀




Cheers, RohitCofounder & CEO




---About OneHash:OneHash, a pioneering startup, is revolutionizing the open-source software industry for SMBs with its suite of cloud-based applications. Our vision of creating a 'Creator’s Economy' rewards open-source contributions, fostering innovation and empowering SMBs with advanced, affordable technology tools.
 
870df40a-5cdc-4b23-b6ce-3da0ea415d82




    
    
    
        Powered by OneHash
