### ISSUE TITLE
[CAL-1540] [CAL-1539] With a fixed host, round robin event assigned to only one round robin host

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8410]
Created via Threads. See full discussion: [https://threads.com/34466039351](https://threads.com/34466039351)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1539](https://linear.app/calcom/issue/CAL-1539/with-a-fixed-host-round-robin-event-assigned-to-only-one-round-robin)</sub>

<sub>[CAL-1540](https://linear.app/calcom/issue/CAL-1540/[cal-1539]-with-a-fixed-host-round-robin-event-assigned-to-only-one)</sub>

**Comment by afrieirham** [comment]
Hey @milospuac, may I know how do I access the full discussion in threads.com? I've signed up but not sure what to do next.

**Comment by emrysal** [comment]
Fixed in v3.1.4
