### ISSUE TITLE
[CAL-1543] Fix the footer in modals

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8414]
Issue arose due to an issue where users "Can't see "Save" option on a longer form/booking question"

Designs: 

Modal /Documentation: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=29898%3A100590&t=4ZLIcu91Nx69ib75-1

Created via Threads. See full discussion: [https://threads.com/34466132294](https://threads.com/34466132294)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1543](https://linear.app/calcom/issue/CAL-1543/cant-see-save-option-on-a-longer-formbooking-question)</sub>

**Comment by joe-shajan** [comment]
Not able to access the thread can you give screenshots here

![image](https://user-images.githubusercontent.com/69904519/234081469-4dafa6e8-f817-4756-a845-0d0f8ab8a7f8.png)
