### ISSUE TITLE
[CAL-1544] RFC: Be able to invite team members and assign them before they made an account

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8418]
## Right now

as a team admin I want to
... invite people
... setup up a team and team event types
... assign members to team event types

## Problem 

I run into the problem that I need to wait for every team member
... to create the account
... accept the invite
... join the team

until I can add them

## Solution
Same as in Slack where you can already tag people who haven't joined, I want to be able to add people already to teams and event-types before they have signed up and accepted. 

<sub>[CAL-1544](https://linear.app/calcom/issue/CAL-1544/rfc-be-able-to-invite-team-members-and-assign-them-before-they-made-an)</sub>

**Comment by joe-shajan** [comment]
So what I understand is, here in this below team there are 3 members and 2 of them are pending.

![image](https://user-images.githubusercontent.com/69904519/235836568-368bca07-74c2-48d7-aa83-c017b1b549a1.png)

And in the assignment tab dropdown, I can only see one member. Instead, I should also be able to see and select the pending members right? @PeerRich 

![image](https://user-images.githubusercontent.com/69904519/235836623-6a664d9f-852e-4e13-84fb-bd0600d5634a.png)

If yes can you assign this to me? I will start working on it.

**Comment by zomars** [comment]
I don't think this is a desirable behavior for current account holders. Only for new accounts. What happens if I get invited to a team I don't want to be in and they add me to an event type? Will I get event notifications until I abandon the team or reject the invite?

**Comment by Siddharth-2382** [comment]
> I don't think this is a desirable behavior for current account holders. Only for new accounts. What happens if I get invited to a team I don't want to be in and they add me to an event type? Will I get event notifications until I abandon the team or reject the invite?

@zomars @PeerRich We can make it so that when a pending team member is assigned an event type, they won't receive any event notifications till they don't accept the invitation. This will allow team admins to create teams, add and assign members to different event types as well as not clutter the members emails. What are your thought on this?

**Comment by keithwillcode** [comment]
@zomars @PeerRich Ping for thoughts on this
