### ISSUE TITLE
[CAL-1566] Issues with OIDC

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8431]
Clicking "Sign in with SAML" doesn't work

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1566](https://linear.app/calcom/issue/CAL-1566/issues-with-oidc)</sub>

**Comment by santosh-kuchetti** [comment]
@PeerRich 
But we can't even see the Sign in with Google and Sign in with SAML in localhost while login

**Comment by prakhart4** [comment]
Both saml and oidc are working, tested with https://mocksaml.com/ and GCP
