### ISSUE TITLE
[CAL-1567] Feature: Enforce 2FA

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8432]
for members of an organisation

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1567](https://linear.app/calcom/issue/CAL-1567/feature-enforce-2fa)</sub>

**Comment by joe-shajan** [comment]
Do you mean something like OTP verification? @PeerRich

**Comment by PeerRich** [comment]
we already have 2FA. we just need a setting for organisation owners to enforce it across all organisation members

**Comment by PeerRich** [comment]
@leog assigned you but feel free to deprioritze

**Comment by jemiluv8** [comment]
I'd like to work on this.

**Comment by bikrantjajware** [comment]
Hey, is this still open to work ?  I see there's a linked PR but no reviews/comments on it, is it planned to be in future?

**Comment by VenkateshSircilla123** [comment]
what is 2FA ?

**Comment by VenkateshSircilla123** [comment]
@PeerRich is this issue still open , can i work on this
