### ISSUE TITLE
[CAL-1569] Selecting Fort-de-France from Setup Wizard does not Display Fort-de-France

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8437]
![CleanShot 2023-04-21 at 18.02.18@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6eb09e71-c552-411a-9d09-af472e203dfc/89e2f88a-8aeb-4cc4-84e1-4190f854e8c9)

Instead, America/Caracas is shown, but if you click into the module, it shows France is selected

![CleanShot 2023-04-21 at 18.03.24@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9b1a1217-65fa-4d73-8a80-d254dce6fb68/bb560151-69be-4c41-a769-67d3ff28217e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1569](https://linear.app/calcom/issue/CAL-1569/selecting-fort-de-france-from-setup-wizard-does-not-display-fort-de)</sub>

**Comment by ExplorerAadi** [comment]
Hey @shirazdole I looked around and I don't believe this is a bug but a default feature of the timezone library being used, I am attaching a loom video to explain in detail:
https://www.loom.com/share/54e4524ae5b74c299526362fa47fe0b0

There are a default list of timezones with their UTC differences as shown in the beginning of the video and as you search for any other city, it fetches the matching timezone for that city from the default list and then renders that.
Ex - India has the same timezone in New Delhi and Kolkata, therefore no matter which one I choose, it will default to one of them (in this case, the Asia/Kolkata one.)

I hope this provides enough clarity.

**Comment by ksgokul2501** [comment]
I think this issue should be closed. :)
