### ISSUE TITLE
[CAL-1570] 20 Second Delay on Button Color Showing on Selecting Calendar in Calendar Installation

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8438]
![CleanShot 2023-04-21 at 18.06.47@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b5fc886a-978c-46bb-a5cf-13d2d48552e5/f43f3a1e-feda-4a14-b4cc-6be99760bfde)

![CleanShot 2023-04-21 at 18.08.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a9200da2-0ee7-4aa4-8f3a-1f637261a6e1/e99c38e0-8e44-4a39-a997-b2529750d401)

eventually button color loaded

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1570](https://linear.app/calcom/issue/CAL-1570/20-second-delay-on-button-color-showing-on-selecting-calendar-in)</sub>

**Comment by shirazdole** [comment]
This occurs when selecting other calendars as well… may not be a 20 second delay, I know for sure you have to refresh for the color to change to black

**Comment by vaibhav135** [comment]
Hi, can I take this issue.

**Comment by ExplorerAadi** [comment]
I am not able to connect google calendar on my local setup as the apps/google-calendar route throws 404.
@Udit-takkar Can you please help me with this?
![image](https://user-images.githubusercontent.com/52901335/235236127-da9fd238-d69a-4188-a45d-7e6b9f54f350.png?raw=true)

**Comment by Udit-takkar** [comment]
@ExplorerAadi you would first have add google API credentials follow the steps here https://github.com/calcom/cal.com#obtaining-the-google-api-credentials and then these commands https://github.com/calcom/cal.com#adding-google-calendar-to-calcom-app-store.

then you would be able to see the google calendar in the app store. do let me know if you are stuck somewhere

**Comment by vaibhav135** [comment]
Guys I am already working on this.
