### ISSUE TITLE
[CAL-1571] Checkbox and Text alignment problem

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8442]
checkbox and text doesn't look aligned properly to me.

Created via Threads. See full discussion: [https://threads.com/messages/ef1928b9-ab1a-4903-bad2-670138a519e6?messageID=517a4c71-8bd3-46c6-9b2f-096072d54556](https://threads.com/messages/ef1928b9-ab1a-4903-bad2-670138a519e6?messageID=517a4c71-8bd3-46c6-9b2f-096072d54556)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1571](https://linear.app/calcom/issue/CAL-1571/checkbox-and-text-alignment-problem)</sub>

**Comment by meritonferati** [comment]
@hariombalhara cannot access the thread discussion. Can you please add the relevant information to this issue for which checkbox and text you are talking about? Thanks in advance.
![image](https://user-images.githubusercontent.com/39864684/233851098-48766197-2452-490a-8a11-173fd2cbe87f.png)

**Comment by hariombalhara** [comment]
![Screenshot_2023-04-23-23-50-31-257_com.android.chrome.jpg](https://user-images.githubusercontent.com/1780212/233857802-44663841-66ce-45f6-b1a0-b18e9f6d171b.jpg)

Sorry for the inconvenience. It's the checkbox component. You can select a checkbox type booking question that will show you the issue on booking form page
