### ISSUE TITLE
[CAL-1694] Duplicate events when using the event approval feature.

### ISSUE THREAD

**Issue by gniting** [calcom/cal.com#8444]
### Issue Summary

If I have event approval turned on (so that new events don't get added until I approve them) and someone reschedules an event, I get an approval request for the reschedule and the event gets rescheduled automatically as well. The moment I approve the reschedule via the email I receive, cal.com ends up creating two events for the same time but with two separate video call-in details (they are essentially two events), which ends up confusing me and the attendees.

### Steps to Reproduce

1. Turn on event approval in settings
2. Invite someone to request a new meeting
3. Accept/approve this meeting
4. Ask the person to reschedule
5. Approve the reschedule request

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
→ I don't expect two events to be created.

### Technical details

- MS Edge on MacOS (both on their respective latest versions as of this writing).

<sub>[CAL-1694](https://linear.app/calcom/issue/CAL-1694/duplicate-events-when-using-the-event-approval-feature)</sub>

**Comment by hariombalhara** [comment]
I tested this exact scenario and it isn't replicable as of this moment. I think it has been fixed already as I remember seeing a similar report a long time back.

**Comment by hariombalhara** [comment]
Wow, thanks for the prompt reply. I certainly want to get this issue fixed and not close it.

Would you be willing to get on a call to get this sorted quickly?

**Comment by hariombalhara** [comment]
You can book me here https://cal.com/hariom/30min or please share your link. Also, I am on discord as hariombalhara if you are there.

**Comment by gniting** [comment]
The steps to recreate are very simple and straight forward:

**Steps to Reproduce**
- Turn on event approval in settings
- Invite someone to request a new meeting
- Accept/approve this meeting
- Ask the person to reschedule
- Approve the reschedule request

Give that a go and if your results are not the same as mine, then we can hop on a call sometime later today. I am in the CEST TZ.

**Comment by hariombalhara** [comment]
I can replicate the issue locally now. Thanks @gniting. 


Expect a fix soon.

**Comment by aspiers** [comment]
Thanks so much @hariombalhara!  BTW I am 70% sure that I have seen this happen even when there wasn't rescheduling but I'll try to check.
