### ISSUE TITLE
[CAL-1578] UI: Timezone icon & time is off on final step

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8449]
![CleanShot 2023-04-21 at 17.46.49@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f8d8df16-58fa-414c-8c6d-47868454fb6a/2ba757ec-385a-481a-b1de-58fb82c484d6)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1578](https://linear.app/calcom/issue/CAL-1578/ui-timezone-icon-and-time-is-off-on-final-step)</sub>

**Comment by lakshyamunjal** [comment]
can you please assign me this task? Thanks.
