### ISSUE TITLE
Refactor README.md 

### ISSUE THREAD

**Issue by vaibhav135** [calcom/cal.com#8467]
### Is your proposal related to a problem?
Hi, I am a new contributor here and while setting up the project in my local machine. I found that a lot of the things that are mentioned in the README are outdated.

### Describe the solution you'd like
As of now I have found few things to update.
- Suggest a new way to setup database (since heroku is not free anymore). I suggest setting db locally or something like railway or render.
- In the intergration section [here](https://github.com/calcom/cal.com#adding-google-calendar-to-calcom-app-store), It should also be mentioned that we need to save our apps related env's in `.env.appStore`. And also that the `DATABASE_URL` will be in both the env's i.e `.env` and `.env.appStore`.

### Additional context
For now I only know about these two things but I would love to have suggestion on the other things that needs updation.

**Comment by alishaz-polymath** [comment]
We are working on a sync between github and Motif for consistent documentation synchronization. 
You can take a look at cal.com/docs in the mean time for up to date docs. 🙏 
I believe we would currently be updating the readme to point to our official docs at cal.com/docs until the synchronization is ready.

**Comment by vaibhav135** [comment]
@alishaz-polymath I am looked at cal.com/docs and couldn't find much about setting setting up the project in local. And integration of these apps in local?

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath I am looked at cal.com/docs and couldn't find much about setting setting up the project in local. And integration of these apps in local?

I'm not entirely sure what part are you referring to. You have the local setup steps mentioned here:
https://cal.com/docs/introduction/quick-start/self-hosting/installation
🤔

**Comment by vaibhav135** [comment]
@alishaz-polymath Thanks for the info. Actually I was trying the fine the local setup in this section ->  https://cal.com/docs/knowledgebase/contributors-guide . Btw can I make a PR for the suggested changes if those makes sense. I will also try to sync the current README.me with the cal.com docs.

**Comment by alishaz-polymath** [comment]
Of course, thanks 🙏
Much appreciated!
