### ISSUE TITLE
[CAL-1585] UI: When you select a date, then change months, the layout shifts

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8481]
Select a date, times appear, change date and the layout shifts. In the current booker the times stay shown on the right and this avoids the layout shift.

Current behaviour:

[96776727-74bd-47fd-b75b-cc28bb50c012](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fb4c15b1-6fb6-4cb3-9a1b-ba5ee3cc04e8/96776727-74bd-47fd-b75b-cc28bb50c012)

More context:

[https://www.loom.com/share/b0bd30e1a9404f3289664b97585e3258](https://www.loom.com/share/b0bd30e1a9404f3289664b97585e3258)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1585](https://linear.app/calcom/issue/CAL-1585/ui-when-you-select-a-date-then-change-months-the-layout-shifts)</sub>

**Comment by JeroenReumkens** [comment]
Fixed in PR #6792
