### ISSUE TITLE
[CAL-1586] Recurring event only creating the first event of the series in the calendar

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8485]
Needs investigation, can't reproduce

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1586](https://linear.app/calcom/issue/CAL-1586/recurring-event-only-creating-the-first-event-of-the-series-in-the)</sub>

**Comment by keithwillcode** [comment]
This cannot be reproduced. If it arises again, let's reopen this with steps performed.
