### ISSUE TITLE
Forgot password form doesn't submit after entering error state

### ISSUE THREAD

**Issue by gone** [calcom/cal.com#8502]
### Issue Summary

After attempting to reset password and getting the old value wrong, correcting the old value and hitting submit does nothing

### Steps to Reproduce

1. on self hosted app to go change password screen
2. type in same password in both boxes (old and new)
3. Hit submit -> error state on old password is incorrect
4. correct old password to current password
5. hit submit and nothing happens.

**Comment by ashish1233** [comment]
hi @gone it says. "New password matches your old password. Please choose a different password."
and i think this is accepted behaviour

if u are referring to this page : https://app.cal.com/settings/security/password

**Comment by gone** [comment]
Ah yeah my mistake in the description - that message is expected, but after correcting the new password to not match the old one you can't submit

**Comment by ashish1233** [comment]
conside a case when you are changing your password my old password is 12345678 and i want to add 0 in my new password 
so new password is 123456780 and then i hit submit its giving me your password is successfully updated and i think this is expected behaviour.
