### ISSUE TITLE
[CAL-1593] Component: Segments are rendering at the wrong height

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8511]
All segments are rendering at 46px high. They should be 36px high, the same as inputs.

Designs: left ; Live: right

![CleanShot 2023-04-25 at 08.31.28@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f18f757d-8dbb-4b21-87cc-9cf0edf8fa40/1738dbc6-92c2-4bb0-a3cb-6700bf3273d0)

[Double check all tokens from Figma while updating also.](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=15212%3A117411&t=p5OTxjr1wkCAybAQ-1)

* radius
* borders
* text color
* bg for active, hover 
* etc.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1593](https://linear.app/calcom/issue/CAL-1593/component-segments-are-rendering-at-the-wrong-height)</sub>

**Comment by hwdsjtu97** [comment]
I'd like to give it a try
