### ISSUE TITLE
[CAL-1595] event not removed from calendar after cancelling

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8513]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

How to reproduce ?

1) book a meeting 
2) now cancel the meeting and you would see on calendar of both organiser and attendee that the event is still present

<sub>[CAL-1595](https://linear.app/calcom/issue/CAL-1595/event-not-removed-from-calendar-after-cancelling)</sub>

**Comment by Bhardwaj-Himanshu** [comment]
Does the event does not close even after waiting for a few minutes? or just a matter of some seconds and not instantly?

Also, could you attach a screenshot of the same of what it shows in your browser?

**Comment by joe-shajan** [comment]
In outlook, it's working fine. In which calender do you face this issue @Udit-takkar? 

https://user-images.githubusercontent.com/69904519/235587357-12dcb38d-6242-4b16-bdcc-2160b42490d3.mp4

**Comment by Udit-takkar** [comment]
@joe-shajan it was reported for Google Calendar

**Comment by joe-shajan** [comment]
> @joe-shajan it was reported for Google Calendar

Ok lets check it in google calender then

**Comment by joe-shajan** [comment]
I tried with Google calender and it's working but it takes few seconds. @Udit-takkar 

https://user-images.githubusercontent.com/69904519/235593819-4446d008-39f2-4e27-95ff-bed856ec7d55.mp4

**Comment by jacobzukerman** [comment]
We ended up running into this issue this afternoon. For the same user, we canceled one recurring event, and everything got removed correctly. Then we canceled a second one, and the Google Calendar events did not get removed. 

Loom video:
https://www.loom.com/share/9f53bafa6711408990ad83b7b3249ce8

**Comment by jacobzukerman** [comment]
I took a look at our Google API & Services Console and noticed that once in a while, `calendar.v3.Events.Delete` fails. 

<img width="1311" alt="Screen Shot 2023-05-03 at 3 25 30 PM" src="https://user-images.githubusercontent.com/37521186/236063813-db10ea13-8ed1-401e-8f19-e1c398fcf534.png">

**Comment by zomars** [comment]
Should we add a retry mechanism whenever the call fails?

**Comment by PeerRich** [comment]
is this still open?

**Comment by Udit-takkar** [comment]
@PeerRich i was unable to reproduce the bug the last time i tried
