### ISSUE TITLE
[CAL-1709] Enable "Check for conflicts" on a per event type basis

### ISSUE THREAD

**Issue by suburbanbuddha** [calcom/cal.com#8542]
### Is your proposal related to a problem?

[Cal.com](http://Cal.com) has the same long-standing flaw [Calendly.com](http://Calendly.com) does, in that the calendars to check for conflicts is set globally, and applied to all Event Types.

An (admittedly trivial) use case might be someone who works from home asking their dog walker to book times this week, regardless of what's in your calendar.

### Describe the solution you'd like

Vimcal allows a user to select the calendars to check for conflicts each time you create a "personal link" - a.k.a.: Event Type.

### Describe alternatives you've considered

I've chatted with [Cal.com](http://Cal.com) support, and unfortunately, was offered the same workarounds Calendly support has in the past - i.e.: setting your events to "free", creating a seperate account that doesn't check calendars, fork and customize, etc.

### Additional context

I apologize if this is a duplicate - I searched, but couldn't find something that clearly matched, and didn't want to accidently convolute other issues.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1709](https://linear.app/calcom/issue/CAL-1709/enable-check-for-conflicts-on-a-per-event-type-basis)</sub>

**Comment by PeerRich** [comment]
tagging @Jaibles to figure out if/how we wanna do this!

**Comment by keithwillcode** [comment]
@ciaranha is this issue still valid?

**Comment by ciaranha** [comment]
> @ciaranha is this issue still valid? 

Yes it's still valid. The challenge would be to add the functionality without creating additional steps or complications who want and expect the default behaviour of checking conflicts across all calendars. 

The example provided, while of course valid, sounds niche. I can see a scenario where we get a lot of support requests where people have different "Check for conflicts" across different event types and get booked unexpectedly.
