### ISSUE TITLE
ui improvement for contrast warning

### ISSUE THREAD

**Issue by jorit-vasconezgerlach** [calcom/cal.com#8545]
(less important) in the overall very clean look of cal the following warning looks disappointing. this may be persistent collapsible.

<img width="834" alt="Bildschirm­foto 2023-04-27 um 11 10 15" src="https://user-images.githubusercontent.com/88643432/234827085-9bdb0c08-3a36-4414-96ed-91b59b589afc.png">

**Comment by Udit-takkar** [comment]
cc: @Jaibles

**Comment by sean-brydon** [comment]
This issue should only display this one time IIRC. If you close and re-open Cal this should disapear. 

I agree we could do with some work here tho

**Comment by vedant-jain03** [comment]
@jorit-vasconezgerlach Can i work on this issue?
