### ISSUE TITLE
[CAL-1600] Duplicate values in en.json 

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8546]
### Issue Summary

There are many duplicate values in the locales/en/common.json file. for example key booking_submitted 

<sub>[CAL-1600](https://linear.app/calcom/issue/CAL-1600/duplicate-values-in-enjson)</sub>

**Comment by zomars** [comment]
Are there any instances where we actually need to duplicate values? Let's say we have a "Submitted" string that is available for both "Payment submitted" or "Booking submitted"?

Should we abstract it to a generic submitted key? Also what about context specific keys like "page_title" and "page_description"?

**Comment by Udit-takkar** [comment]
@zomars i don't think we need to use duplicate values in the example that you gave and choose a key that is more closer to the text value.  For example we had two keys request_reschedule_title_attendee and request_reschedule_booking for "Request to reschedule your booking" so i picked request_reschedule_booking key in this case.

 a lot of duplicate values were added by mistake like attendee_in_person and in_person_attendee_address have the same value In Person (Attendee Address).  https://github.com/calcom/cal.com/pull/8547/files.

**Comment by Udit-takkar** [comment]
@zomars we can create generic keys like this but maybe it can get difficult to update and add new keys in the future. we have translations for words like "who", "where", "when" etc.

```
{
  "booking": "Booking",
  "payment":"Payment",
  "title_submitted": "{{title}} submitted",
}
```
