### ISSUE TITLE
Copy paste multi line text in rich text editor

### ISSUE THREAD

**Issue by tgroutars** [calcom/cal.com#8557]
### Issue Summary

When copy pasting multiline text into the rich text editor of notifications, the first line is added in the right place, but the rest is added at the end of the text.

### Steps to Reproduce

1. Go to workflow and create a new notification
2. Copy multiple lines of text (at least from Calendly, haven't tried this from other sources)
3. Paste somewhere in the middle of the rich text editor

### Technical details

https://user-images.githubusercontent.com/7382760/235110649-90edc50e-5b16-444d-88cf-809509cf7950.mov
I'm on Chrome 112.0.5615.137 on app.cal.com

**Comment by Udit-takkar** [comment]
@tgroutars not able to reproduce this

https://user-images.githubusercontent.com/53316345/235134061-449f5fcb-a33e-4303-b017-e14e97f81fe6.mov

**Comment by tgroutars** [comment]
Might be specific to text copied from calendly? 🤔

**Comment by Udit-takkar** [comment]
@tgroutars yeah maybe you can try copying text from calendly to notes app or pastebin and then copy again from notes app.
