### ISSUE TITLE
UI Improvement for Sign UP page

### ISSUE THREAD

**Issue by Aarize29** [calcom/cal.com#8559]
Found a bug? Please fill out the sections below. 👍

I was exploring sign up page, later I found that the form section has no margin top which create little bad UI look

![Screenshot (50)](https://user-images.githubusercontent.com/97665948/235215979-7ba0dc6b-15fd-4a62-a460-a179e23dd3be.png)
 
we can decrease the height of that component , so that it can fit properly.

### Steps to Reproduce

1)Height of component can be reduced..

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by udayfakie** [comment]
Hi there, I'm interested in working on this issue. Is it available for anyone to work on? If so, may I take on the task? I'd be happy to help improve the UI of the sign-up page by reducing the height of the form component and adjusting its CSS styling as needed. Please let me know if this is something I can work on, appreciated. Thank you!

**Comment by tarunclub** [comment]
@Aarize29 I don't think it's an issue because if we try to make it fit inside the view with the help of vh property the font size and the margin between the components within the signup form will be effected and that will make the UI even worse.

**Comment by Aarize29** [comment]
> @Aarize29 I don't think it's an issue because if we try to make it fit inside the view with the help of vh property the font size and the margin between the components within the signup form will be effected and that will make the UI even worse.

Got it

**Comment by Aarize29** [comment]
> @Aarize29 I don't think it's an issue because if we try to make it fit inside the view with the help of vh property the font size and the margin between the components within the signup form will be effected and that will make the UI even worse.

We can adjust the margin and font size as per need??

**Comment by Vishrut19** [comment]
Can I work on this issue?

**Comment by Sheikh-JamirAlam** [comment]
It looks fine for me?
![image](https://user-images.githubusercontent.com/48979376/235339493-baab986f-cf72-4483-8b8f-ba01fca3a6dd.png)

**Comment by Aarize29** [comment]
> It looks fine for me? ![image](https://user-images.githubusercontent.com/48979376/235339493-baab986f-cf72-4483-8b8f-ba01fca3a6dd.png)

Then it's alright👌
I guess, it was my laptop's problem
