### ISSUE TITLE
UI Fixes issue

### ISSUE THREAD

**Issue by kumarankit999** [calcom/cal.com#8562]
In this Current Version Webpage, We See in the Top-bar of  the Page ,Where the Sentence " Scheduling infrastructure for Everyone " is Written and the upper Calendar is being touched, Which Should not be happens. There Should be some Margin top of Some Pixels 
 (Ex: 30px)

![image](https://user-images.githubusercontent.com/111564362/235315346-273d72ed-904c-452b-bfc4-f131d32665a9.png)

**Comment by elhadis** [comment]
Hi @kumarankit999  I'm interested , it help me start contributing , so let me know if I can make it plz.
thanks and  have nice day.

**Comment by takshakmudgal** [comment]
It shows fine on my system.

**Comment by Udit-takkar** [comment]
<img width="1440" alt="Screenshot 2023-04-29 at 11 53 33 PM" src="https://user-images.githubusercontent.com/53316345/235318338-490cfe3f-9323-429f-aca5-c9b35279b7d5.png">

@kumarankit999 it looks fine to me

**Comment by iamjamesfrancis** [comment]
![image](https://user-images.githubusercontent.com/55175085/235338241-f2836a11-98af-43d2-bb61-c692d4073aaf.png)

In various screen resolutions, it shows different

**Comment by Vishrut19** [comment]
I would like to work on this issue

**Comment by karthiknadar1204** [comment]
@kumarankit999 if this issue is up for grabs,i wuld like to work on it,please assign it to me

**Comment by Vishrut19** [comment]
hey @kumarankit999 I have asked for it first

**Comment by Udit-takkar** [comment]
Hey folks the code for the landing page is not open source for now. you can contribute to other issues
