### ISSUE TITLE
Bottom part of some lowercase characters are hidden on user profile section

### ISSUE THREAD

**Issue by Jonathan1599** [calcom/cal.com#8563]
### Issue Summary

Characters such as j,q,y etc have their bottom section hidden on the user profile section

![image](https://user-images.githubusercontent.com/55296387/235316806-4d580875-dc0d-4197-8b53-9146fa682bd8.png)

### Technical details

-Tested on chrome and firefox

**Comment by udayfakie** [comment]
Hi, I am interested in working on this issue and I believe I have the skills required to fix it. If it's alright with you, I would like to take on this task

**Comment by Udit-takkar** [comment]
@udayfakie assigned to you

**Comment by prafulbbandre** [comment]
Hi @Udit-takkar I would like to work on this issue.

**Comment by udayfakie** [comment]
@Udit-takkar Thank you for assigning this issue to me, I will work on it and provide a fix as soon as possible.

**Comment by udayfakie** [comment]
@Udit-takkar I have fixed the issue with hidden characters in the user profile section.
#8571
