### ISSUE TITLE
[CAL-1605] Cal video Meeting URL generated when Jitsi Video is selected in location

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8565]
Found a bug? Please fill out the sections below. 👍

Reported here https://calendso.slack.com/archives/C01NXDSRY9W/p1682531916114919

![image](https://user-images.githubusercontent.com/53316345/235318604-acf1b423-1fd7-417a-9aaa-efe486bf142e.png)

![image](https://user-images.githubusercontent.com/53316345/235318613-dadf4f7d-f874-4fd8-914a-dc36668d4eda.png)

<sub>[CAL-1605](https://linear.app/calcom/issue/CAL-1605/cal-video-meeting-url-generated-when-jitsi-video-is-selected-in)</sub>

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this?

**Comment by Udit-takkar** [comment]
@Sheikh-JamirAlam it was reported in the slack channel. you can ask the person who reported this bug i have provided the link to the conversation in the description

**Comment by Sheikh-JamirAlam** [comment]
@Udit-takkar Alright, will do that.

**Comment by SridharPerepu** [comment]
This is not reproducible. I have tried to create using Jitsi meet, and it did gave me correct jitsi link.
