### ISSUE TITLE
Full Name not refreshing after Profile Update 

### ISSUE THREAD

**Issue by Keyurkd** [calcom/cal.com#8567]
### Issue Summary

Left Navigation Profile Name not refreshed after Full Name update under My Profile on this route: `/settings/my-account/profile`

### Steps to Reproduce

1. Went to Settings -> MyAccount -> Profile page
2. Modified Full Name and Clicked on Update
3. Full Name didn't update/refresh immediately on the Left Navigation.

Refer to the screenshot below:

<img width="1481" alt="Screenshot 2023-04-29 at 2 41 22 PM" src="https://user-images.githubusercontent.com/12368271/235319208-f1b309ed-b1cd-4330-b32a-68b94dca299a.png">

### Technical details

- Google Chrome version: 112.0.5615.137
- Node.js version: v16.19.0

**Comment by KOLEAJEOLAYINKA** [comment]
**Hello, I am enthusiastic about tackling this issue and I am confident that my skillset is suitable for resolving it. May I request permission to handle this task?**

**Comment by Sheikh-JamirAlam** [comment]
Can I get assigned to this issue?

**Comment by AshishBarvaliya** [comment]
Addition to this bug 

The avatar is also not being updated when user information changes.

<img width="686" alt="Screenshot 2023-04-29 at 6 08 59 PM" src="https://user-images.githubusercontent.com/49753983/235326061-2a2d8cf1-8d30-4bcf-880a-d09c798bb659.png">

FIY: currently working on it

**Comment by mickg13** [comment]
can I get assigned to this issue if you don’t mind?

**Comment by amrinder1189** [comment]
Hi, I am trying to solve this

**Comment by 17rawat** [comment]
hey I looked into this, name on the sidebar comes from session storage, it stores the user info when the user logs in 
Any idea how can I update the session info?

**Comment by 17rawat** [comment]
> Addition to this bug
> 
> The avatar is also not being updated when user information changes.
> 
> <img alt="Screenshot 2023-04-29 at 6 08 59 PM" width="686" src="https://user-images.githubusercontent.com/49753983/235326061-2a2d8cf1-8d30-4bcf-880a-d09c798bb659.png">
> 
<img width="1440" alt="Screenshot 2023-05-02 at 9 23 00 PM" src="https://user-images.githubusercontent.com/123530078/235719106-9b40fb71-453c-4987-8484-8a6d7de7ace6.png">

> FIY: currently working on it

hey, Its updated when u reloads the page.
