### ISSUE TITLE
[UI] : Background not changing in toggler

### ISSUE THREAD

**Issue by vedant-jain03** [calcom/cal.com#8578]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The toggler is working unexpected in getting started form, delay in `on` and `off`. Attached video of the behavior:

https://user-images.githubusercontent.com/76901313/235349920-74d32f3d-943f-4f69-8b71-4fcef278ef82.mov

### Steps to Reproduce

1. (for example) Went to `https://app.cal.com/getting-started/connected-calendar`
2. Click on the toggle 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
- The toggler should be changing the background instantly.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by vedant-jain03** [comment]
cc @PeerRich Can I work in this issue?

**Comment by iamsanat** [comment]
Assign this issue to me

**Comment by bhumit070** [comment]
Hello @vedant-jain03 on which calendar connect you get this erorr

**Comment by prashanthcm** [comment]
Hi @bhumit070, we can reproduce this issue when google calendar is selected. @PeerRich can this issue be assigned to me?

**Comment by bhumit070** [comment]
Yeah, I get it but when I run it locally I don't get the google calendar option to select @prashanthcm  I think instead of asking to assign the issue if you have generated the same on your local you should fix it and create a PR that will save time, let me know if I am wrong.

**Comment by vedant-jain03** [comment]
> Yeah, I get it but when I run it locally I don't get the google calendar option to select @prashanthcm I think instead of asking to assign the issue if you have generated the same on your local you should fix it and create a PR that will save time, let me know if I am wrong.

Always follow code of conduct in open source, try not to work or raise PR on issue for which other's have asked or wait for maintainers to assign it to someone(if they find issue valid). 

cc @PeerRich

**Comment by vedant-jain03** [comment]
The delay is happening due to API calls for each toggle, what we can do is to separate API call with toggling, let handle toggling before API calls, such that to make it smooth!

WDYT @PeerRich

**Comment by PeerRich** [comment]
this has been fixed
