### ISSUE TITLE
[CAL-1606] New Booker: Shows team event in place of user event if both have same slugs.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8579]
<img width="1078" alt="Screenshot 2023-04-30 at 6 35 12 PM" src="https://user-images.githubusercontent.com/1780212/235354440-075ca9be-b0e8-49e5-a280-ec60be7acf6d.png">

When there are two events with the same slugs(One a Team event and other an individual event), getPublicEvent just fetches the first one it can get.

<img width="1514" alt="Screenshot 2023-04-30 at 6 38 16 PM" src="https://user-images.githubusercontent.com/1780212/235354551-f6283964-aeab-4b4d-a719-5400a1f7e9cf.png">
<img width="1511" alt="Screenshot 2023-04-30 at 6 38 28 PM" src="https://user-images.githubusercontent.com/1780212/235354557-f62875a7-0127-44af-b49a-84f81aafdf55.png">

<sub>[CAL-1606](https://linear.app/calcom/issue/CAL-1606/new-booker-shows-team-event-in-place-of-user-event-if-both-have-same)</sub>

**Comment by sumitshinde-84** [comment]
i would like take on this issue @hariombalhara

**Comment by hariombalhara** [comment]
I would wait for @JeroenReumkens' reply here. New booker is not in use right now, so this can wait.
