### ISSUE TITLE
Create a full independent docker environment to run the project on

### ISSUE THREAD

**Issue by ologbonowiwi** [calcom/cal.com#8591]
### Is your proposal related to a problem?

I tried to get one "good first issue" and was kind of annoying to setup a database externally just to start to contribute to the project

### Describe the solution you'd like

It would be nice to have a `docker-compose.yml` setup with everything that we need to run the app, something that with a `docker-compose up` on the repo's source we'll be able to run the project easily.

**Comment by antipr000** [comment]
Hey @ologbonowiwi, can you be a bit more specific about what was the issue that you faced? If you follow the [setup doc](https://github.com/calcom/cal.com#setup), it is actually a one line command to get things started. There is already a docker-compose [file](https://github.com/calcom/cal.com/blob/main/packages/prisma/docker-compose.yml) for postgres setup and seeding the database.

**Comment by ologbonowiwi** [comment]
So I need to 
```
cd packages/prisma
docker-compose up
```

And then run the APP with yarn?

**Comment by zeeshanbhati** [comment]
> 

Yes, the app isn't running on docker only the database run's on docker container, the application is not containerized, also you can use ```yarn dx``` in the root directory to spin up the container

**Comment by XLAR-8** [comment]
@PeerRich  I would like to suggest having a make file or bash file that can execute all the necessary local setup with just one command. Additionally, there is already a repository available that contains a Docker Compose setup for local development.
what do you think?

**Comment by tcchawla** [comment]
Hey @ologbonowiwi @PeerRich, can you assign me, I would like to take up this issue.

**Comment by ologbonowiwi** [comment]
Hey @tcchawla, I'm already working on this one, making a `docker-compose.yml`, but if you want to try another approach, please feel free to do it

**Comment by ologbonowiwi** [comment]
@PeerRich @zeeshanbhati @antipr000 can you take a look at the PR #9017 that I created?

I needed to delete the `db-up` from the `turbo.json`, which I know isn't the best approach, but I had to start from somewhere. It would be nice to have your thoughts on my implementation before we merge to get it 100% working 😄

**Comment by PeerRich** [comment]
@krumware can review!

**Comment by ologbonowiwi** [comment]
@PeerRich @krumware sorry for the spam, guys, but it looks like it's ready to review 😄 

I was able to fix the issue and clone a brand new repo, run `yarn install && yarn dx`, and the project started successfully (database, mail service, and web app).

Would anyone be able to take a look? It should be a quick one 😄

**Comment by krumware** [comment]
Can we take the conversation over to [calcom/docker]( https://www.github.com/calcom/docker)? most of these tools already exist over there. The PR submitted uses the image generated from cal.com/docker as a base image and doesn't actually generate a new image with the user's source-code, so it might misdirect users to thinking that the dockerfile in this repo is the correct one to use for building their images.

It seems like the devex problem we're experiencing, as well as trying to solve, is how effectively we're directing users to calcom/docker.
Another option is to migrate calcom/docker into calcom/cal.com (which we've talked about in the past), to eliminate the submodule workflow and the secondary repo.

@PeerRich thoughts?

p.s. testing final multi-arch updates now

**Comment by ologbonowiwi** [comment]
bring calcom/docker here would be the best option. What made me create this issue was the toughness to run the project for the first time, and the need to co over `calcom/docker` to do it doesn't seem like the best option, but I also think that this would change the purpose of this issue.

If you see [this part of my PR](https://github.com/calcom/cal.com/pull/9426/files#diff-b66bff8f428370268dcfdc8f8a6c26fc877b32e250d7ea24511f4dba01dba819R13-R15), you'll see that I'm overriding the `apps/web` and `packages` using the local source code. Probably the optimal option, in this case, would be to copy the `package.json` and re-install the dependencies, but this took too long to run here, and I removed it from my implementation (which I can change due to version incompatibility issues that this approach can bring)

**Comment by ologbonowiwi** [comment]
@PeerRich @krumware @emrysal guys, I think I found a mid-term that doesn't go against the past decisions on the project and still has the benefits of running the project in one single command. Can anyone review #9995? I appreciate any help you can give me.

**Comment by KSSaiTeja** [comment]
as i am beginner.. i can't work on this issue.. please assign to someone else

**Comment by ologbonowiwi** [comment]
It's been four months since I opened the issue. I tried three approaches to solve this, but we merged none.

Would you mind tipping me for my work and closing the issue @PeerRich?

If you still have anything you expect from this issue, I'll happily implement it. But I tried a couple of times now, but none seemed ideal.

**Comment by SauravChanda** [comment]
@ologbonowiwi Is this issue still open for contribution, if it's the dev environment we want, maybe we can use something like [Vagrant](https://www.vagrantup.com/), In my case I used `yarn dx` to create the dev env and it was very straight forward for me.
