### ISSUE TITLE
[Bug] Cancellation page is outdated

### ISSUE THREAD

**Issue by Shubhdeep12** [calcom/cal.com#8592]
Found a bug? Please fill out the sections below. 👍

### Cancellation page is outdated
On deleting an account, the user is redirected to https://cal.com/cancellation

Screen recording
https://vimeo.com/823957017/67cf556f73

It seems like the page is outdated:
1. Navbar height is inconsistent.
2. Navbar options don't match the ones on the home page.
3. The title and translations are also missing.

Attached some screenshots
![image](https://user-images.githubusercontent.com/43654389/235409684-96fa4ebe-c8f0-45d6-bf35-114843f3f23a.png)
![image](https://user-images.githubusercontent.com/43654389/235409707-d8dabae9-6a49-4c34-8b51-c131ae9f857f.png)
![image](https://user-images.githubusercontent.com/43654389/235409723-c06cdb24-b3c0-464f-a8d3-ac3419f537ed.png)

### Steps to Reproduce

1. Delete an account.
2. User will be redirected to https://cal.com/cancellation

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by Shubhdeep12** [comment]
Would love to fix this. Please confirm if this is a valid issue.
Thanks

**Comment by jwala-anirudh** [comment]
I don't see this as a bug/issue. The main section below nav is of same color and we don't see such out of place nav width

**Comment by Shubhdeep12** [comment]
Added screen recording in description

**Comment by PeerRich** [comment]
fixed. deploying!
