### ISSUE TITLE
[CAL-1608] When certain limits in place - "Could not book a meeting" error

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8594]
![Screenshot 2023-05-01 at 09.30.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c03caec0-2355-442e-8510-294fa6ad9d5b/05a99417-3f71-4bf8-9db4-3a375b97f203)

![Screenshot 2023-05-01 at 09.30.26.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bc08f2c9-6021-4849-a21c-66f4cfa2e895/4e73a00c-d938-419e-9235-76a4f1563673)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1608](https://linear.app/calcom/issue/CAL-1608/when-certain-limits-in-place-could-not-book-a-meeting-error)</sub>

**Comment by manasCodes13** [comment]
Guys, can I work on this issue.

**Comment by afrieirham** [comment]
Hey @milospuac, can you fix the screenshot here? It's broken for people with no access to SyncLinear 🙏

**Comment by CarinaWolli** [comment]
Can't reproduce this one, do we know if this is still an ongoing issue?

**Comment by emrysal** [comment]
As date overrides are mentioned as the primary cause I'm thinking this has a high chance of being fixed, we can assume it is; @milospuac
