### ISSUE TITLE
[CAL-1609] Verify that Zoho CRM app is creating events correctly. If not fix that.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8600]
@hariombalhara pushed some stuffs for the solution we found earlier.

Note: we might have to fix the Zoho CRM app. A large part of this PR was derived off that and its likely to have the same bug with the api domain.

_Originally posted by @ShaneMaglangit in https://github.com/calcom/cal.com/issues/8158#issuecomment-1525510196_

More Context:
- For India, the host that we need to connect to is zoho.in and not zoho.com. The host is available as token.api_domain and that should be used.          

<sub>[CAL-1609](https://linear.app/calcom/issue/CAL-1609/verify-that-zoho-crm-app-is-creating-events-correctly-if-not-fix-that)</sub>

**Comment by sumitshinde-84** [comment]
i would like take on this issue @hariombalhara

**Comment by hariombalhara** [comment]
Awesome!! Assigned to you
