### ISSUE TITLE
[CAL-1610] Every CalendarService must send externalCalendarId

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8601]
This was causing reschedule to not update the Bigin Event. This might be a problem with other CRM apps as well.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/8158#discussion_r1181552060_

If a CalendarService doesn't set externalCalendarId, it's updateEvent never get's called.
This check exists here and I think we should do away with this requirement in `updateAllCalendarEvents`
https://github.com/calcom/cal.com/blob/810a4e6b7f829183dee8a798e08346f082cfb8f9/packages/core/EventManager.ts#L459 

cc @zomars

<sub>[CAL-1610](https://linear.app/calcom/issue/CAL-1610/every-calendarservice-must-send-externalcalendarid)</sub>

**Comment by zeeshanbhati** [comment]
@hariombalhara, the external id has references in the updateEvent of CalendarManager.ts, should I go ahead and remove those too?

**Comment by zeeshanbhati** [comment]
@hariombalhara , When I checked the update event function in the Calendar service it doesn't need externalId as parameter, I am unable to understand why it is used in the calendar.updateEvent function in Calendar Manager. 

![image](https://github.com/calcom/cal.com/assets/53969232/cc3c0ab2-e42e-45b0-ae97-26bca3ac5c07)

CalendarManager, if I am not getting it wrong then calendar is an instance of **CalendarService**


**Function Definition of update event in CalendarService.tsx**

![image](https://github.com/calcom/cal.com/assets/53969232/4eb574ec-0c27-41ff-a6b2-30f341f48045)
