### ISSUE TITLE
Profile picture does not update on the left sidebar

### ISSUE THREAD

**Issue by oneknucklehead** [calcom/cal.com#8610]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The profile picture does not update on the leftside navbar even though the profile picture has been updated already and the page has been refreshed continuously.

![Screenshot 2023-05-02 012913](https://user-images.githubusercontent.com/75200954/235521299-a3ad2570-54da-49d0-8381-7037dc070425.png)

### Steps to Reproduce

1. Go to https://app.cal.com/settings/my-account/profile
2. try updating your profile picture

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by loki1205** [comment]
Hi, I know how to solve this issue. What's happening here is that the image data from the navbar is set to a source that gets data on the user login. Hence, when you sign out and again sign in, fresh data is stored and now the sidebar will have new data (image). Kindly assign this issue to me, and I can help you solve it.

Also, there were some UI changes. Like, in the profile settings section, there must be an edit button, which users can click on to edit their profile. Until the edit button is clicked, the profile data must be read-only. Also, when the "Update" button is clicked message 'Profile updated successfully' should be displayed and the profile should go back to read-only. Do you this is a good idea?

**Comment by ujjwal-45** [comment]
@oneknucklehead  I have reproduced the bug that you have mentioned above , but the profile picture is updating on the sidebar too. Here is the scree
![Screenshot 2023-05-02 at 12-08-08 Profile Cal com](https://user-images.githubusercontent.com/106880198/235597204-6eacad42-9d4e-463f-8621-e74263d1c2f1.png)
nshot ..

**Comment by loki1205** [comment]
> @oneknucklehead I have reproduced the bug that you have mentioned above , but the profile picture is updating on the sidebar too. Here is the scree ![Screenshot 2023-05-02 at 12-08-08 Profile Cal com](https://user-images.githubusercontent.com/106880198/235597204-6eacad42-9d4e-463f-8621-e74263d1c2f1.png) nshot ..

Sorry, I didn't understand. Is this on localhost? Or on the server, https://app.cal.com/settings/my-account/profile. Do you mean, you have fixed the bug or that the bug is not showing up for you?

**Comment by ujjwal-45** [comment]
Yes, this is on localhost and the bug is not showing.

**Comment by loki1205** [comment]
> Yes, this is on localhost and the bug is not showing.

Did you try it on https://app.cal.com/settings/my-account/profile? If not, create an account on cal.com and then try updating the profile picture. You should face the issue.

**Comment by ajaxbo360** [comment]
can you assign me to this issue and thanks

**Comment by ujjwal-45** [comment]
@loki1205 , i have created an account on cal.com and updated my profile but I am still not getting the bug. I have refreshed it one or two times.
![Screenshot 2023-05-02 at 21-17-46 Profile Cal com](https://user-images.githubusercontent.com/106880198/235718207-4592b68d-eaf5-4fdf-8aef-1451963ed1b6.png)

**Comment by ajaxbo360** [comment]
same here @ujjwal-45

**Comment by Himanshu2561** [comment]
![Screenshot 2023-05-02 225803](https://user-images.githubusercontent.com/88238521/235740222-20d51567-c5bd-4a0a-a23e-056378742f6b.png)

Hey! @loki1205 The bug is also showing to me on the live version.
I have created new account and gone through profile page and the blank avtar image shows up.

**Comment by ajaxbo360** [comment]
did you refresh the page @Himanshu2561

**Comment by Himanshu2561** [comment]
yes @ajaxbo360

**Comment by Himanshu2561** [comment]
Try creating a new account @ajaxbo360

**Comment by ajaxbo360** [comment]
i tried creating a new account still didn’t see any bug @Himanshu2561

**Comment by MBWankhade** [comment]
I also don't see any issue , all is working fine thanks.

**Comment by zeeshanbhati** [comment]
I guess the issue of not updating the profile picture in the sidebar is before doing a refresh, when we update the profile image the data in the sidebar becomes stale, we need to explicitly revalidate it when the profile picture gets updated, I hope that will fix this issue :)

**Comment by mrb1nary** [comment]
![image](https://user-images.githubusercontent.com/55779046/236208624-1be74efa-7219-4109-9ffa-70268bee84aa.png)

Somehow I was able to reproduce the issue

**Comment by keithwillcode** [comment]
This was fixed in #8570
