### ISSUE TITLE
[CAL-1611] Dark mode text in recurring event 

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8611]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Both text and icon are not visible in dark mode

<img width="1440" alt="Screenshot 2023-05-02 at 1 43 16 AM" src="https://user-images.githubusercontent.com/53316345/235523035-ab5f1177-dfa5-440b-9c45-22f64643c4e4.png">

### Steps to Reproduce

1) Go to  booking page of recurring event type ( http://localhost:3000/pro/tennis-class )

<sub>[CAL-1611](https://linear.app/calcom/issue/CAL-1611/dark-mode-text-in-recurring-event)</sub>

**Comment by oneknucklehead** [comment]
Hey @Udit-takkar , just found out that even though i have changed the theme to dark mode, the changes does not seem to appear.
Ref:
![image](https://user-images.githubusercontent.com/75200954/235530471-0906f058-9b24-4a62-8c2a-d2c961579f69.png)
