### ISSUE TITLE
[CAL-1695] Excessive resource consumption on AWS EC2

### ISSUE THREAD

**Issue by praveentestkit** [calcom/cal.com#8615]
### Issue Summary

I installed a cal.com on an EC2 instance as instructed here: https://cal.com/docs/introduction/quick-start/self-hosting/installation#requirements

I managed to install it successfully.

When browse http://localhost:3000 and browse pages it stops responding after some time.

The application is consuming all the available server resources. See the below screenshot with 'htop'.

![2-G](https://user-images.githubusercontent.com/130727591/235576764-55f89355-56fb-4f81-850e-69d0951cf408.png)

### What I have tried

I read the other issues and could not find a solution

I upgraded the instance (e.g. from 2 GB to 4 GB). The problem still persists. See below image.

![4-G](https://user-images.githubusercontent.com/130727591/235576859-1fcd348b-89bd-4dfd-ac91-d943de09e451.png)

What could be the reason for this?

### Steps to Reproduce

1. Clone the cal.com repo
2. Install according to the documentation
3. Run 'yarn dev'
4. Browse pages on http://localhost:3000

I even managed to install apps and activate Google Calendar, etc. But when I browse it does not respond after some time.

### Technical details

- Node 16
- Ubuntu server on AWS EC2

<sub>[CAL-1695](https://linear.app/calcom/issue/CAL-1695/excessive-resource-consumption-on-aws-ec2)</sub>

**Comment by zeeshanbhati** [comment]
Hey @praveentestkit, can you please mention the ec2 type ? or can you mention the specs of the EC2 server other than the ram

**Comment by praveentestkit** [comment]
Initially, 't3.small' was used. Then it was upgraded to 't3.medium'. 

![Screenshot from 2023-05-04 14-27-21](https://user-images.githubusercontent.com/130727591/236158288-db76417e-2799-4d91-9ae9-789815c11f06.png)

you can find more info about the types here: https://aws.amazon.com/ec2/instance-types/ @zeeshanbhati if medium instance is not enough, can you please recommend a suitable one?

Later, I created a 2GB swap volume too. (images does not show it) Still the issue persists.

**Comment by zeeshanbhati** [comment]
@praveentestkit Were you using a separate rds instance for the database or running on the same instance by a docker container?

**Comment by praveentestkit** [comment]
@zeeshanbhati not using a separate RDS instance. Using Postgre installation on Ubuntu. And docker is not used. Yes, medium instance should be enough.

**Comment by praveentestkit** [comment]
@zeeshanbhati I tried to setup this locally on my laptop (Ubuntu). I am getting this warning 

```
failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /tmp/turbod/e1c068f04a70e6cb/turbod.pid is not running, and remove /tmp/turbod/e1c068f04a70e6cb/turbod.pid
        - check the logs at /root/.local/share/turborepo/logs/e1c068f04a70e6cb-cal.log
        - the unix domain socket at /tmp/turbod/e1c068f04a70e6cb/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

I installed turbo with `npm install turbo --global`. But still the warning persists.

**Comment by zeeshanbhati** [comment]
> 
I don't think you need to do that just follow the installation guide that should work

**Comment by PeerRich** [comment]
do you have telemetry active or not? I believe this could be due to telemetry

**Comment by praveentestkit** [comment]
I have not disabled it. (if it is activated by default, then it should be enabled.) I managed to get everything working as expected on my laptop (inside a docker container). _I am developing/testing some functions/features for my client. So far it worked without any resource issues._

**Comment by keithwillcode** [comment]
We installed a test instance on AWS and verified it’s working now with no issues. Will reopen if further reports come through.
