### ISSUE TITLE
Paypal App

### ISSUE THREAD

**Issue by cnhhoang850** [calcom/cal.com#8634]
### Is your proposal related to a problem?

No

### Describe the solution you'd like

I would like to have PayPal ap. 

### Describe alternatives you've considered

I've tried looking into Zapier but this doesn't work 

### Additional context

Would this be a worthwhile feature to develop? It is being actively worked on? 
I really need this feature so I'm happy to contribute this app to the app store.

**Comment by joe-shajan** [comment]
#1546 Is this what you want?

**Comment by AbleLincoln** [comment]
working on it now! any special features you would like to request?

**Comment by PeerRich** [comment]
duplicate
