### ISSUE TITLE
Back to bookings link disappears on hover

### ISSUE THREAD

**Issue by AbleLincoln** [calcom/cal.com#8635]
### Issue Summary

_Back to bookings_ link when previewing a booking has a hover state that blends in the background
![Screen Recording 2023-05-02 at 11 20 14 PM](https://user-images.githubusercontent.com/12586676/235844825-a6625cc2-ac63-4a8c-ad7f-7b50b853f3ad.gif)

### Steps to Reproduce

1. Make an event type
2. Preview
3. Finish the flow then try to hover over this link (top left)

### Technical details
- Firefox on Mac, not sure if user theme (dark) has anything to do with this

**Comment by sumitshinde-84** [comment]
i would like to work on this issue

**Comment by Bharathyamaha23** [comment]
on hover it turns to thick black color which matches your user theme.

> ### Issue Summary
> _Back to bookings_ link when previewing a booking has a hover state that blends in the background ![Screen Recording 2023-05-02 at 11 20 14 PM](https://user-images.githubusercontent.com/12586676/235844825-a6625cc2-ac63-4a8c-ad7f-7b50b853f3ad.gif) [ ![Screen Recording 2023-05-02 at 11 20 14 PM](https://user-images.githubusercontent.com/12586676/235844825-a6625cc2-ac63-4a8c-ad7f-7b50b853f3ad.gif) ](https://user-images.githubusercontent.com/12586676/235844825-a6625cc2-ac63-4a8c-ad7f-7b50b853f3ad.gif) [ ](https://user-images.githubusercontent.com/12586676/235844825-a6625cc2-ac63-4a8c-ad7f-7b50b853f3ad.gif)
> 
> ### Steps to Reproduce
> 1. Make an event type
> 2. Preview
> 3. Finish the flow then try to hover over this link (top left)
> 
> ### Technical details
> * Firefox on Mac, not sure if user theme (dark) has anything to do with this

on hover it turns to black color which matches your user theme.

**Comment by Udit-takkar** [comment]
@AbleLincoln do you want to work on this issue or should i assign it to @sumitshinde-84  ?

**Comment by AbleLincoln** [comment]
No, you can assign it to them

**Comment by Udit-takkar** [comment]
@sumitshinde-84 you can start working on this

**Comment by sumitshinde-84** [comment]
hii @Udit-takkar please review this PR #8658  I have made appropriate changes
