### ISSUE TITLE
[CAL-1708] Basecamp integration

### ISSUE THREAD

**Issue by proofrating** [calcom/cal.com#8641]
### Is your proposal related to a problem?
**It is not.  I'd just like to have Cal.com show up in the integrations with Basecamp besides pasting an external link.  Just is better image wise and promotes Cal.com.  The only one there is Calendly.**
<!--
  Provide a clear and concise description of what the problem is.
  **I'd like for Cal.com to show up in the integrations for Basecamp.  So it opens up directly in basecamp instead of an external link right now.  You can see Calendly is in basecamp.**

<sub>[CAL-1708](https://linear.app/calcom/issue/CAL-1708/basecamp-integration)</sub>

**Comment by Jonathan1599** [comment]
Hey @proofrating ,I can't seem to find the integration for Calendly on basecamp. Could you let me know how you've integrated it with basecamp?
