### ISSUE TITLE
[CAL-1613] Issues with webhook for multi-seat meetings

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8644]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1613](https://linear.app/calcom/issue/CAL-1613/issues-with-webhook-for-multi-seat-meetings)</sub>

**Comment by EvandroCaruso** [comment]
Hello everyone! Could you please prioritize this issue as high? I have migrated from Calendly, and my business currently operates with 2 (sometimes more) seats, involving different and occasionally challenging individuals. However, I am encountering an issue where the webhook only triggers for the first seat. I heavily rely on the webhook in conjunction with a tool I developed to send alerts and messages through WhatsApp. Do you have any estimate on the timeframe for resolving this?

It is important to note that actions such as cancellations and modifications need to be handled separately for each meeting seat, with distinct UUIDs and independent webhook triggers.

**Comment by PeerRich** [comment]
@CarinaWolli can you look into this? or @alishaz-polymath

**Comment by alannnc** [comment]
> Duplicate of #7950
> 
> I'll take a look @alannnc any updates on this one? Didn't you make a fix for this already, at least for workflows?

@CarinaWolli This was solved but only for workflows I think. I'll assign me on this one.
