### ISSUE TITLE
[CAL-1614] [Managed Event Types] Assign user searchable

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#8646]
Make select user searchable 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1614](https://linear.app/calcom/issue/CAL-1614/[managed-event-types]-assign-user-searchable)</sub>

**Comment by joe-shajan** [comment]
Hi @sean-brydon I have already raised a pr #8637 for the same issue #8412

**Comment by sean-brydon** [comment]
Duplicate 

fixed by https://github.com/calcom/cal.com/pull/8637
