### ISSUE TITLE
Event type is allowed to be created with a negative value of "duration"

### ISSUE THREAD

**Issue by MaheshB77** [calcom/cal.com#8648]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
- Event type is allowed to be created with a negative value of "duration"

### Steps to Reproduce

1. Go to **Event Types**
2. Edit event
3. In the **duration** field user can put a negative value, please check the screenshots attached below

![issue-4](https://user-images.githubusercontent.com/47536121/236036070-f073dbfb-13a4-475c-b25e-5e5d3a168361.png)
![issue-5](https://user-images.githubusercontent.com/47536121/236036103-96d1dbef-0d03-4161-a944-527a2991ab23.png)

**Comment by MaheshB77** [comment]
@Udit-takkar @keithwillcode  Can I work on this issue?

**Comment by Udit-takkar** [comment]
yeah go ahead
