### ISSUE TITLE
Placeholder in additional notes is not working. 

### ISSUE THREAD

**Issue by johnsmithodom** [calcom/cal.com#8651]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Placeholder in additional notes is not working. 

### Steps to Reproduce

1. Set placeholder  additional notes
2. Clicked on save
3. Trying schedule with one self.  (placeholder text is not showing up） 

![image](https://user-images.githubusercontent.com/120798996/236096189-972bd310-da95-49ea-a81b-541b9cd5cb93.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by 17rawat** [comment]
Hey can i work on this?

**Comment by Arunaks007** [comment]
Hey, can you share more details on this bug?
I tried to replicate, its not happening. Please find below

![image](https://user-images.githubusercontent.com/70270364/236133655-f02b31ba-3644-4cab-96c7-d4516d040953.png)
![image](https://user-images.githubusercontent.com/70270364/236133731-bbdfe748-8d96-42a6-a916-c4b039c25e5f.png)

Please share more details. @johnsmithodom

**Comment by elhadis** [comment]
Hi @johnsmithodom can I take the issuse plz

**Comment by johnsmithodom** [comment]
just tested, now it saved. Thank you all for the quick response.
