### ISSUE TITLE
The time that you confirm on a particular date for a meeting needs to show an action of getting clicked

### ISSUE THREAD

**Issue by kanakpandit17** [calcom/cal.com#8652]
### Issue Summary
You can click on any time you want to hold the meeting but it doesn't show any action of getting selected. After clicking, it takes 2 seconds to go to your final meeting dashboard. Also you can make multiple clicks on different time slots but the final one is considered which sounds irritating. It would be great to see if instead, users can select the option they want to hold the meeting and click "Ok" that would help them realize at what time they wish to hold the meeting.

![no_action](https://user-images.githubusercontent.com/86275069/236097755-891c4e4c-7aee-40c7-9d2c-330703dbe8e4.gif)

### Steps to Reproduce

1. Go to any meeting scheduled
2. Click on Preview
3. Select time 

This causes unnecessary irritation as the user wont know whether the click he has made is acceptable or not, and

**Comment by HeratPatel** [comment]
@kanakpandit17 Can I take this?

**Comment by Arunaks007** [comment]
@kanakpandit17 I can fix this, We can show a change of color when time is clicked. This way user can know whether its being selected or not.

**Comment by HeratPatel** [comment]
@Arunaks007 @kanakpandit17 
We should also stop user to select other time slots after clicking first one by disabling the other time slots.

**Comment by kanakpandit17** [comment]
> @kanakpandit17 Can I take this?

ok

**Comment by HeratPatel** [comment]
> > @kanakpandit17 Can I take this?
> 
> ok

Started working on it.

**Comment by JeroenReumkens** [comment]
This issue will be resolved with our new booker, since it combines both the date+time picker view and the form into a single view. So for that reason I'm gonna close this issue. 

Thanks a lot for reporting @kanakpandit17
