### ISSUE TITLE
[CAL-1616] Confirmation emails not being sent

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8661]
I tried test booking this customer but I didn't get the confirmation email. They are complaining that they are not getting the email as well.

Customer: mjoannes

Created via Threads. See full discussion: [https://threads.com/34469333794](https://threads.com/34469333794)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1616](https://linear.app/calcom/issue/CAL-1616/confirmation-emails-not-being-sent)</sub>

**Comment by yp969803** [comment]
@milospuac i want to work on this issue

**Comment by PeerRich** [comment]
looking into the records of sendgrid, mjoannes has recently received emails. cannot reproduce this

**Comment by 0xLunch** [comment]
Reopening because I didn't get email either when my friend did a test booking on my new account.

lunchdev is the username.
