### ISSUE TITLE
[CAL-1617] Bookings rejected on a date overridden day.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8666]
Created via Threads. See full discussion: [https://threads.com/34469350238](https://threads.com/34469350238)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1617](https://linear.app/calcom/issue/CAL-1617/bookings-rejected-on-a-date-overridden-day)</sub>

**Comment by vaibhav135** [comment]
Hi, am not able to access the threads.
It says this
<img width="783" alt="image" src="https://user-images.githubusercontent.com/39329182/236628210-e75bec02-85b4-4e76-9fff-1eab021590f2.png">
