### ISSUE TITLE
[CAL-1619] Lark calendar events not picked up

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8678]
Created via Threads. See full discussion: [https://threads.com/34469532690](https://threads.com/34469532690)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1619](https://linear.app/calcom/issue/CAL-1619/lark-calendar-events-not-picked-up)</sub>

**Comment by yogeshgirmal** [comment]
@milospuac I will solve this bug, can you please assign it to me?

**Comment by 9520prashant** [comment]
Hey @milospuac I have not access of thread how should understand the issue?

**Comment by yogeshgirmal** [comment]
Im trying to look into code but it would be great if I look into the conversation also. (This thread does not exist or you do not have access to it.)
![Screenshot 2023-05-06 171403](https://user-images.githubusercontent.com/110414416/236622031-a8845b35-c529-42bd-9443-b49e3618eccc.png)

**Comment by milospuac** [comment]
There isn't any conversation, I created the issue through threads integration when raising the issue in threads. 

Here is my busy event in Lark calendar and the associated slot in cal.com booking page showing instead of not being there 
<img width="1286" alt="Screenshot 2023-05-04 at 18 58 59" src="https://user-images.githubusercontent.com/97884287/236790405-0745ed79-5c06-4f86-879a-0f01ea609df6.png">

**Comment by zgayjjf** [comment]
Is there any progress?
We can only switch to calendly for now because of this bug.

Hope this issue can be fixed soon.
😄

**Comment by PeerRich** [comment]
@zgayjjf i dont think calendly supports Lark

**Comment by zgayjjf** [comment]
Is there any update?

**Comment by wsxiaoys** [comment]
My organization heavily relies on the Lark Calendar for scheduling, and currently, it's a significant obstacle preventing us from becoming paying customers of cal.com.

**Comment by milospuac** [comment]
@PeerRich what is the verdict here, Lark isn't usable for months now

**Comment by wsxiaoys** [comment]
Kindly ping for updates.
