### ISSUE TITLE
[CAL-1337] Add a step for video conferencing in onboarding

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8685]
Add another step in the onboarding where you can install video apps (after showing the calendar setup step)

[Updated onboarding - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?type=design&node-id=4452%3A265471&t=vZWkgeeHkFpRLNe1-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1337](https://linear.app/calcom/issue/CAL-1337/add-a-step-for-video-conferencing-in-onboarding)</sub>

**Comment by 9520prashant** [comment]
hey @Jaibles can i know bit more about the issue??

**Comment by kanakpandit17** [comment]
> Add another step in the onboarding where you can install video apps (after showing the calendar setup step)
> 
> Full discussion: https://threads.com/34458106681
> 
> From [SyncLinear.com](https://synclinear.com) | [CAL-1337](https://linear.app/calcom/issue/CAL-1337/add-a-step-for-video-conferencing-in-onboarding)

how to get access to this thread?

**Comment by 9520prashant** [comment]
Same for me

**Comment by Jaibles** [comment]
This still "needs design", I'm working on it but will attach them today.

**Comment by 9520prashant** [comment]
Awesome,

**Comment by Jaibles** [comment]
[Updated onboarding - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?type=design&node-id=4452%3A265471&t=vZWkgeeHkFpRLNe1-1)
