### ISSUE TITLE
[CAL-1620] Full Screen: Align Calendar at bottom

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8700]
This:

![CleanShot 2023-05-05 at 15.02.31@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0d7ed016-d3bd-41d2-95c3-47b34e89b235/4117f9ed-6707-49d9-a70d-c46c5be1ea70)

Should be:

![CleanShot 2023-05-05 at 15.03.23@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/88875df9-be40-4958-aa23-b0260a4e9220/58860dea-dbbb-46ca-8abe-0adb3fe492f2)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1620](https://linear.app/calcom/issue/CAL-1620/full-screen-align-calendar-at-bottom)</sub>

**Comment by Shalom2212** [comment]
can I contribute on this issue

**Comment by vaibhav135** [comment]
@PeerRich where can I find this calendar? Please assign this to me.
