### ISSUE TITLE
[CAL-1621] Grow Dialog in Height

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8701]
scrolling is not clear and we have the space

![CleanShot 2023-05-05 at 15.04.41@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7908de31-534a-4688-9747-3c946d7f4c24/c23e1880-23d9-4068-af43-56a3df6b98cc)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1621](https://linear.app/calcom/issue/CAL-1621/grow-dialog-in-height)</sub>

**Comment by vaibhav135** [comment]
Hi can you please provide more info on this. Also assign this to me.
