### ISSUE TITLE
[CAL-1622] Consider centered confirmation page instead of the current Dialog

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8702]
![CleanShot 2023-05-05 at 15.08.12@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4a4a4b4f-5d07-44b0-96e6-20a2e891c0d8/b09d08d5-8926-4a60-b2f2-1db39a2646ae)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1622](https://linear.app/calcom/issue/CAL-1622/consider-centered-confirmation-page-instead-of-the-current-dialog)</sub>

**Comment by joe-shajan** [comment]
Right now, we have these two pages. Do we need to combine them as shown above? Is that what we want? @PeerRich 

![image](https://user-images.githubusercontent.com/69904519/236485671-faaa1401-ecaf-4522-a105-8c819dcbf84d.png)

![image](https://user-images.githubusercontent.com/69904519/236485705-42475d8b-e39e-45b0-bfbe-4a3ee3306448.png)

**Comment by sean-brydon** [comment]
@Jaibles please review this 

Not a fan of all the whitespace in this design. Modal/popover makes way more sense to me when in fullscreen view
