### ISSUE TITLE
Search Bar Alignment in App Store

### ISSUE THREAD

**Issue by 9520prashant** [calcom/cal.com#8707]
In App Store Search Bar not align on it's right position [https://app.cal.com/apps](url)
Steps to Reproduce

1. Go to cal.com
2. Click on Go App
3. Click on App Store
4. then click on search bar and you can find the issue,

![Screenshot (210)](https://user-images.githubusercontent.com/99237795/236507530-00ad5b67-5241-4e00-a17d-3bc6527b2a14.png)

**Comment by 9520prashant** [comment]
I have fixed it please assign me this issue @PeerRich 

![Screenshot (211)](https://user-images.githubusercontent.com/99237795/236508145-a55b2b28-befd-4d2b-9aa4-400ac069399e.png)

**Comment by headshigh** [comment]
can i be assigned?

**Comment by 9520prashant** [comment]
Bro I have fixed this issue but only required some permission to make some
changes in codebase

**Comment by pankaj-ramchandani** [comment]
Resolved both alignment and border issues please assign to me.

**Comment by swarajbachu** [comment]
#8741

**Comment by 9520prashant** [comment]
Great Work Bro

**Comment by 9520prashant** [comment]
Udit bro is it not fixed?

**Comment by Udit-takkar** [comment]
@9520prashant the PR is still open

**Comment by 9520prashant** [comment]
Ok let's fix this as early as possible
