### ISSUE TITLE
[CAL-1810] Confirm Button Missing

### ISSUE THREAD

**Issue by Kfelts** [calcom/cal.com#8716]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Unable to confirm new appointment requests. The only option is "reject"

<img width="960" alt="Screenshot 2023-05-05 at 7 41 13 PM" src="https://user-images.githubusercontent.com/51497445/236585300-bd8aab82-6384-4609-a102-d1f1a3c25636.png">

<sub>[CAL-1810](https://linear.app/calcom/issue/CAL-1810/confirm-button-missing)</sub>

**Comment by abhijain2003** [comment]
hey, can I work on this?
we can add a accept button similar to Reject one, but what api we need to call it to send confirm request

**Comment by imshubh4141** [comment]
Hey @Kfelts,

For the latest code on main I see confirm button is provided. Trying pulling the latest code and kindly verify.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/53164776/236602218-2b4bf47c-ee66-4c37-ac95-71865837a7ea.png">

**Comment by Udit-takkar** [comment]
@abhijain2003 we already have an accept button

**Comment by Kfelts** [comment]
This is on the Cal.com hosting site. So I'm not able to pull code- just wait until it's implemented on the platform.

**Comment by PeerRich** [comment]
very weird. we have an accept button but not sure why it doesn't show up there. @Kfelts whats your username?
