### ISSUE TITLE
calcom setup issue

### ISSUE THREAD

**Issue by Tejas-Valame** [calcom/cal.com#8720]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Project setup issue

I was trying to setup this project in my local machine as instructed in the readme file 
I got an error when running `yarn dx`

### Steps to Reproduce
Follow the steps to install project as in readme
At the step `yarn dx` i got this error

@calcom/prisma:db-up: cache bypass, force executing ec1eb6666d840f81
@calcom/prisma:db-up: **unexpected character "/" in variable name near "../../.env"**
@calcom/prisma:db-up: unexpected character "/" in variable name near "../../.env"
@calcom/prisma:db-up: ERROR: command finished with error: command (C:\Users\Valame\Downloads\OpenSourceContri\cal.com\packages\prisma) **yarn run db-up exited** (1)
command (C:\Users\Valame\Downloads\OpenSourceContri\cal.com\packages\prisma) yarn run db-up exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    10.993s

 ERROR  run failed: command  exited (1)
Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The DATABASE_URL env variable was set up in .env file in root folder
The secrets were also saved.

Could this be due to saome newer packages that I have used?

FIX:
When we add this DATABASE_URL var to ./packages/prisma/.env file this issue resolves

`DATABASE_URL="postgresql://postgres:@localhost:5450/calendso"`

### Technical details

Win 10 Enterprise 19045.2846

$ node v18.16.0
$ yarn 3.4.1
$ Docker version 20.10.22, build 3a2c30b

**Comment by zeal2end** [comment]
You are using wrong version of node : https://github.com/calcom/cal.com#prerequisites

**Comment by Tejas-Valame** [comment]
Thanks for pointing out.
It works with node version 17 now

**Comment by pawelborkar** [comment]
> It works with node version 17 now

You can close this issue now.
