### ISSUE TITLE
[CAL-1625] Update CalendarSwitch.tsx to use react-query state

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#8722]
Follow up of #8677              

@sean-brydon My reasoning for it is the same as there for the `Save` button(except that it has a possibly larger payload and can take more time). When you click on the Save button, there is a loader that runs because it is updating something. We wouldn't want `save` to be considered done when we know it can fail.
There are 2 ways we are using toggles in the app. 

- Here toggling it doesn't actually update anything unless you click the Save button later.
 <img width="1217" alt="Screenshot 2023-05-06 at 12 33 26 PM" src="https://user-images.githubusercontent.com/1780212/236608748-dede3add-4a44-45eb-a8c5-c74108c06c31.png">

- Current case that we are discussing, where toggling it actually updates something. [This case is similar to the Save button]
You mentioned that it's not using tRPC, but it's using react-query already so we can do an optimistic update to further improve the experience. That would then match the local state implementation in terms of responsiveness.

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/issues/8677#issuecomment-1537077269_
            

<sub>[CAL-1625](https://linear.app/calcom/issue/CAL-1625/update-calendarswitchtsx-to-use-react-query-state)</sub>

**Comment by SohamRatnaparkhi** [comment]
Hello @sean-brydon , I would love to work on this issue. Can you assign it to me.

**Comment by vaibhav135** [comment]
@sean-brydon I will raise the MR for this. I think it's quite similar to what I have implemented here in #8595

**Comment by sean-brydon** [comment]
> @sean-brydon I will raise the MR for this. I think it's quite similar to what I have implemented here in #8595

I think youre right! Thanks again @vaibhav135  :)

**Comment by sean-brydon** [comment]
@vaibhav135 if you work on this before #8677 is merged would you please base your branch off that PR so we dont have to deal with merge changes?

**Comment by vaibhav135** [comment]
@sean-brydon yes sure I'll do that.

**Comment by vaibhav135** [comment]
@sean-brydon if we are doing optimistic UI updates. Then should we have a middle state for the switch?

enable
<img width="184" alt="image" src="https://user-images.githubusercontent.com/39329182/236672071-4dd71480-b9a9-4c9e-abf4-905d736e6645.png">

intermediate (loading)
<img width="184" alt="image" src="https://user-images.githubusercontent.com/39329182/236672109-b45ef6a0-1fbb-460a-82cd-777279d6fd39.png">


disable
<img width="184" alt="image" src="https://user-images.githubusercontent.com/39329182/236672122-3dfe2606-5f46-4019-821f-8a50615eb6df.png">


or do I just remove the useState simply and just rely on the switch loader, like how you have mentioned [here](https://github.com/calcom/cal.com/pull/8677#issuecomment-1536347085).
