### ISSUE TITLE
Navigation Link becomes invisible when hovered

### ISSUE THREAD

**Issue by headshigh** [calcom/cal.com#8724]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The navigation link that is supposed to take you to previous page after confirmation of a booking becomes invisible on hover.
### Steps to Reproduce

1. Go to meeting scheduled page
2. hover the link on the top left

The color of text in the link should not have changed to background colo

https://user-images.githubusercontent.com/93933601/236622481-82a5b347-a5a1-4816-a144-3276a06252ba.mp4

**Comment by Shalom2212** [comment]
how can i reproduce this bug

**Comment by kanakpandit17** [comment]
I am not getting this issue

**Comment by Vikram125609** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/93823479/236626396-2c4df151-7539-4602-b6ea-3c1668ab5547.png">

There is no such link on the meeting schedule page

**Comment by Vikram125609** [comment]
Can you please help to reproduce the issue ?

**Comment by vaibhav135** [comment]
Yes I am gettting this same issue I'll create an MR for this.
