### ISSUE TITLE
Custom Light/dark mode Restriction for a few cases

### ISSUE THREAD

**Issue by YOKESHCR** [calcom/cal.com#8726]
When the dark theme/light theme color doesn't pass the contrast check, the update functionality might be restricted. It might be good for a few cases like in the below example.

![image](https://user-images.githubusercontent.com/27686539/236630967-f7181dae-363d-499f-8b50-928996ab2dbf.png)
![image](https://user-images.githubusercontent.com/27686539/236631309-ba55b023-8498-4df8-a461-956890d26bed.png)

But for a majority of the cases in the dark mode it looks quite odd like the one in the below example when the buttons or links are hovered.
![image](https://user-images.githubusercontent.com/27686539/236631517-8792b4cf-5cc8-4e74-9005-c0bc6ce61e10.png)
![image](https://user-images.githubusercontent.com/27686539/236631545-4c22cf29-518e-47b4-b195-a40036f677f1.png).

This is also the same for light mode contrast check. It would be better if the Update functionality is restricted for such scenarios

**Comment by sean-brydon** [comment]
Hey - we dont stop you from setting a colour that doesnt past a contrast check incase this is your brand colour and want to use it. 

I dont believe we should force the user to have a brand colour that passes this. Doesnt make too much sense - if you ignore the error you will likely end up with links/hovers looking a bit off.

**Comment by Vishrut19** [comment]
Hey! I want to take up this issue. Can I?

**Comment by YOKESHCR** [comment]
Hi @sean-brydon,

Sorry for the late response. I can understand what you are actually trying to explain but if these cases are allowed then the purpose of Light/Dark mode will be nullified.

Is there any other way that this can be solved other than just ignoring those error messages when trying to update them.

Thanks,
Yokesh.

**Comment by PeerRich** [comment]
just ignore the warning. its not an error

**Comment by JOduMonT** [comment]
I understand it's only a warning but the whole math logic seams is wrong. 

I'm my case I use: Indigo-900 (#312e81) which has a contrast ratio of roughly 11.4:1 against white, which way beyond the contrast ratio criteria [(AAA's 7:1) suggested by W3C](
https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html).

The math genuinely isn't the problem anymore.
This points to a bug in Cal.com's contrast checker, not your color choice. There's a documented Cal.com GitHub issue about the contrast check misbehaving and restricting updates in cases where it shouldn't.
