### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by thekrprince** [calcom/cal.com#8727]
### A change is needed in the documentation regarding setting up the database in Heroku.

The step is documented as "Create a free account with Heroku", but it's not free now.
Want to change it to "Create an account with Heroku".

![image](https://user-images.githubusercontent.com/39616644/236633299-04ff0896-6e2b-49b8-ac96-b3468cdcdc84.png)

**Comment by Aytida-dev** [comment]
Hii can i work on this issue

**Comment by thekrprince** [comment]
I am waiting for this issue to be confirmed by the maintainer of this repo. @Aytida-dev

**Comment by vaibhav135** [comment]
Hi @thekrprince please close this issue as I've already created a similar issue few days back and have already raised an MR for it check #8467

**Comment by thekrprince** [comment]
Sure. Thanks for the info. @vaibhav135
