### ISSUE TITLE
Asterisk sign needed for the mandatory fields while creating new team

### ISSUE THREAD

**Issue by mMARUF** [calcom/cal.com#8731]
### Issue Summary

Asterisk sign needed for the mandatory fields while creating new team
### Steps to Reproduce

1. Go to cal.com
2. Go to Settings
3. Click on **ADD A TEAM** button
4. In the team creating page, the mandatory fields do not have any asterisk sign 

### Technical details
OS: MacOS Ventura 13.3.1 (a)
Browser: Chrome 113.0.5672.63 

### Attachment
<img width="687" alt="Screenshot 2023-05-07 at 2 46 28 PM" src="https://user-images.githubusercontent.com/45368054/236667697-79ccb2bb-9fff-473a-8bbf-30b8e888508d.png">

**Comment by kanakpandit17** [comment]
Can you assign this to me?

**Comment by kshitiz-goel07** [comment]
Hello @mMARUF , 
I would like to work on this issue.
This issues seems to be a perfect start for my Open-source contribution journey 
Please Assign it to me !

**Comment by mMARUF** [comment]
Sorry, I do not have permission to assign the issue.

**Comment by mMARUF** [comment]
Sorry, I do not have permission to assign the issue.

**Comment by Jaibles** [comment]
Reason for closing:

While in some cases it can be helpful to use an asterix, within our app the majority of our fields are in fact required. This means it's better to take the approach of indicating which fields are optional. Not all users know what the asterix means.

In this context all fields are required, so we don't need to add anything. It's also not reasonable for a user to think they can create a team without a name or URL and it's not the case where some are required and some are optional leaving the user to guess. And if they do try, we have feedback in place to guide them.
