### ISSUE TITLE
Email with space in prefix and postfix should not be considered as a different user 

### ISSUE THREAD

**Issue by mMARUF** [calcom/cal.com#8732]
### Issue Summary

Email with space in prefix and postfix should not be considered as a different user – while adding member to a team

### Steps to Reproduce

1. Open cal.com and log in
2. Go to Settings
3. Press on **ADD A TEAM** button
4. Start creating a new team
5. In the step-2 of creating a new team, invite someone to the team who is not a user
 of cal.com
6. Now, again, try to invite the same email address to the team by using space in prefix and postfix of the email address (example: {space} email {space} )
7. The app recognizes the email address as a different user and shows error- "Invite failed because there is no corresponding user for *************"

### Actual Results
7. The add recognizes the email address as a different user and shows error- "Invite failed because there is no corresponding user for *************"

### Expected Results
Email with space in prefix and postfix should not be considered as a different user – while adding member to a team

### Technical details
OS: MacOS Ventura 13.3.1 (a)
Browser: Chrome 113.0.5672.63

**Comment by Hammad9219** [comment]
Please assign this to me

**Comment by Ash9311** [comment]
I would like to work on this issue

**Comment by pranjalg13** [comment]
It is easily resolvable by using` .trim`

**Comment by kshitiz-goel07** [comment]
Is this issue still open ?
If yes, I would like to work on it

**Comment by AliYar-Khan** [comment]
@mMARUF is this still not solved. I can fix that. Looking forward to your response
