### ISSUE TITLE
Ignore Double Booking / Allow Overbook

### ISSUE THREAD

**Issue by chief-nerd** [calcom/cal.com#8744]
### Is your proposal related to a problem?
Sometimes I "block" work or lunch in the calendar ... I want people to overbook / double book that time.

e.g.  
I block lunch in my calendar every day - to rescue that free time. However I want people to be able to overbook those with lunch dates, but no other meeting should be allowed to do so.
Regular meeting respect the booking, but lunch bookings should be able (after confirmation) to overbook the blocker.

### Describe the solution you'd like
Checkbox in Availability: `Ignore Double Bookings` or `Allow overbooking` or something like that ...

### Describe alternatives you've considered
Multiple calendars .... meh

**Comment by PeerRich** [comment]
urgh i think this can cause many weird side effects. not sure how I feel about this

**Comment by fredphyoyekhant** [comment]
This is also an issue that I face. I want the scheduler to schedule appointments in my calendar even though I marked down as a time for myself, like lunch or something but I do want other people to be able to book this time so that I can just propose a new time from the calendar invitation without having to go to another comms channel to discuss about this.

**Comment by supermarsx** [comment]
I think it would be useful to allow overbooking in certain types of scenarios, if i have two suppliers coming at the same time i would like to have them both separately in the same time slot

**Comment by pythonicode** [comment]
+1 here, this makes Cal.com unusable for our business use-case since we want to allow multiple bookings where the "user" is actually a booking with our business which has multiple available people to help

**Comment by hunterwilhelm** [comment]
I require this feature. There is a company event about which I am automatically sending invites to everyone.

However, if the host has an event at the same time as the company event, cal.com throws an error!

Workaround:
So, I'll have to create a dummy team member and email, whose SOLE purpose is to have a free calendar so it doesn't block the company event on accident.

**Comment by aaronwangj** [comment]
We really need this and are migrating to another calendar library because of it

**Comment by ulyngs** [comment]
Also essential for our use case! We use calendar overrides to set up specific times for each event type. We require an option to tell an event type to only avoid overlapping events within its own type, and ignore any potential overlaps with *other* event types.

**Comment by hunterwilhelm** [comment]
So my workaround I mentioned above is BAD, the dummy gmail account got flagged for spam!!! This is not acceptable because it breaks many of the features of cal.com if that happens.

Please, cal.com, we NEED this feature!!!

**Comment by michielswaanen** [comment]
Need this feature as well to efficiently book meetings at our booth during an in-person event.

**Comment by Leololololo** [comment]
acuity scheduling does that with a simple override schedule checkbox. Please Please add this. https://github.com/calcom/cal.com/issues/5779

**Comment by mvcautomation** [comment]
we need this feature too. we book meetings for our clients and want to be the host so we can admin the meetings for them but if we're the host on every meeting it keeps reducing available times for all clients even if just one client is taking that time.

please let us ignore other cal bookings in availability settings!

**Comment by criadoperez** [comment]
I could also use this feature. Its a good way to mark certain events you want o have cal.com ignore, but still show as busy in your calendar.
Think of it, like a "I'm busy for most, but available for you because you are VIP" :-)

**Comment by gusdudey2k** [comment]
This is important for our use case (healthcare practice management system) to allow a practice administrator to book a 'squeeze in' or 'walk in'

**Comment by hunterwilhelm** [comment]
This is also important to our workflow. We need this for automation to go smoothly without errors being thrown when the automation runs.
