### ISSUE TITLE
Block availability based on delegated calendar with only busy/free access

### ISSUE THREAD

**Issue by pelletencate** [calcom/cal.com#875]
### Is your proposal related to a problem?

I want my personal Google calendar to be blocked by events on my work Google calendar. I've shared my work calendar with my personal Google account. For privacy reasons, I'm only allowed to share free/busy info, not full event details.

While free/busy info should be enough to block availability, the calendar does not show up on my "select calendars" list.

### Describe the solution you'd like

I'd like for calendars that are only sharing busy/free data to show up in the "select calendars" list, so that I can block availability based on them

### Describe alternatives you've considered

One alternative is to integrate both accounts, once #858 gets merged. But this only works if you actually have access to that calendar. I can imagine multiple situations where someone wants to do this on a calendar not owned by an account they have access to.

### Additional context

[Slack thread](https://calendso.slack.com/archives/C01NXDSRY9W/p1633599318086800)

**Comment by PeerRich** [comment]
i think this was fixed a log time ago

**Comment by PeerRich** [comment]
can you try again?
