### ISSUE TITLE
Select all in the schedule page

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#8751]
### Is your proposal related to a problem?
In the availability page: https://app.cal.com/availability/
when you change the time and copy it to all you need to select the whole days manually, it would be great to have an option to select all. 
![image](https://user-images.githubusercontent.com/18273833/236812897-54fad23b-1b87-4b9e-b59d-500dec4556df.png)

I would like to be assigned to work on this.

**Comment by a0m0rajab** [comment]
Related code: https://github.com/calcom/cal.com/blob/main/packages/features/schedules/components/Schedule.tsx#L147

**Comment by mudrikapandey** [comment]
Hey, @a0m0rajab  assign this issue to me.

**Comment by a0m0rajab** [comment]
@mudrikapandey I am not a contributor to this repo, but I was working on this yesterday. Just opened my PR. 
If you like you can check it and feel free to update it or give your thoughts :)
