### ISSUE TITLE
Dark mode app install/save button

### ISSUE THREAD

**Issue by Saga-sanga** [calcom/cal.com#8756]
### Issue Summary

The save button in dark mode for app configuration when installing an app has a very dark-coloured 'Save' button which could be easily mistaken for an inactive/disabled button.

### Steps to Reproduce

1. Go to http://localhost:3000/apps
2. Click on Install on any app that requires setup e.g. Apple Calendar.
3. Wait for the setup modal.

### Screenshot
<img width="902" alt="Screenshot 2023-05-08 at 8 43 06 PM" src="https://user-images.githubusercontent.com/35249409/236864354-17b04d8d-1f60-44f5-9650-3ebd6ce3ec55.png">

### Technical details

- Browser version: Brave Browser Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (arm64)
- Node.js version v16.19.1

**Comment by Saxenaa218** [comment]
Hey @Saga-sanga, can you confirm what the button should look like? like the below one?
![Screenshot 2023-05-08 at 9 39 12 PM](https://user-images.githubusercontent.com/19265034/236874365-b71a5403-2c6c-45b5-aa25-dee51486737c.png)

**Comment by Aaryansh1** [comment]
Hey, I would like to fix this issues if someone assigns it to me
