### ISSUE TITLE
[CAL-1633] Seated event not generating Google Meet URL for each subsequently booked seat.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8765]
<img width="587" alt="Screenshot 2023-05-09 at 10 03 52" src="https://user-images.githubusercontent.com/97884287/237035682-ddd59d72-54c5-47fa-b3cd-0346f3a02a3d.png">
<img width="846" alt="Screenshot 2023-05-09 at 10 04 28" src="https://user-images.githubusercontent.com/97884287/237035698-8d2b3cde-0bfb-461d-abae-f58750cd1073.png">
Once the first seat has been booked, Google Meet URL is in both confirmation email and google calendar as intended. However, once each subsequent seat is booked Google Meet URL isn't there anymore for both the attendee and the organizer.
Created via Threads. See full discussion: [https://threads.com/34471280408](https://threads.com/34471280408)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1633](https://linear.app/calcom/issue/CAL-1633/seated-event-not-generating-google-meet-url-for-each-subsequently)</sub>

**Comment by francescogatto** [comment]
still happens!
