### ISSUE TITLE
Email can be changed without confirmation

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#8767]
### Steps to Reproduce

1. Navigate to profile settings
2. Change email address to anything & save
3. Cal accepts this without confirmation

Imagine a scenario where a typo is made etc

**Comment by pranjalg13** [comment]
Hey @ChipWolf , you need to enter your password in order to confirm the email.

So I think that is a enough validation for user to change email
<img width="1200" alt="Screenshot 2023-05-09 at 8 41 49 PM" src="https://github.com/calcom/cal.com/assets/47600057/d41de4fd-d60f-4902-83ea-13693c62d247">

**Comment by PeerRich** [comment]
we're also adding email verification right now cc @sean-brydon
