### ISSUE TITLE
[CAL-1635] Banner Notification for Disconnected Calendar

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8770]
When a calendar is not connected or a calendar connection fails — have a banner notification on web and mobile to notify the user to connect or reconnect their calendar 

Context from customer issue: [https://calcominc.slack.com/archives/C04CWEU35NV/p1683622346411839](https://calcominc.slack.com/archives/C04CWEU35NV/p1683622346411839)

![BFCD6378-BC89-449F-8B7B-A59A71184F92.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/333f7e19-6d62-4b13-bc42-9abb06a0da2b/4ffd619a-255a-4393-88f6-bb1e8c1b7279)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1635](https://linear.app/calcom/issue/CAL-1635/banner-notification-for-disconnected-calendar)</sub>

**Comment by Hybes** [comment]
in addition to this - could we allow the user to mark a calendar is IMPORTANT, so if it disconnects, their account is paused until it has been reconnected. 
this will avoid, disconnected calendar and bookings being made while unattached.
it could/should also email the user when it disconnects?

**Comment by riteshsp2000** [comment]
@shirazdole I'd like to work on this issue.

**Comment by shirazdole** [comment]
> in addition to this - could we allow the user to mark a calendar is IMPORTANT, so if it disconnects, their account is paused until it has been reconnected. 
> 
> this will avoid, disconnected calendar and bookings being made while unattached.
> 
> it could/should also email the user when it disconnects?

Interesting feedback @Jaibles
