### ISSUE TITLE
[CAL-1636] Notification for disconnected calendar not showing on the event types screen

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#8771]
When a calendar becomes disconnected, we need to treat this as a high priority error for our users and show a top banner across all pages on the app.

This should appear on desktop and mobile.

**Desktop**

![CleanShot 2023-05-09 at 10.00.49@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/00ee36c1-4a44-4114-98f9-d45caa9df68d/3ea26165-ae35-4071-b460-1a90fc5c4d33)

**Mobile**

![CleanShot 2023-05-09 at 10.00.59@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dcafdf16-047f-43c7-8ef8-35bcccfe4209/4cf293b2-7b24-47d8-97e9-0b4578784d45)

[It should use our Top banner component from our DS](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?type=design&node-id=29886%3A100211&t=FFcaf4EhyN0w4RuP-1)

Context where issue arose: https://calcominc.slack.com/archives/C04CWEU35NV/p1683622346411839

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1636](https://linear.app/calcom/issue/CAL-1636/notification-for-disconnected-calendar-not-showing-on-the-event-types)</sub>

**Comment by G3root** [comment]
@Jaibles should the banner dismissible in desktop also ?

**Comment by Jaibles** [comment]
> @Jaibles should the banner dismissible in desktop also ?

Good catch. I actually meant to remove it on mobile before posting. I don't think it should be dismissible. I think if you previously had a calendar connected, you should have to reconnect. If you want the banner to go away, you would have to reconnect or delete it from your calendar connections entirely. @shirazdole wdyt?

**Comment by Jaibles** [comment]
@G3root No need to wait for @shirazdole response here btw, we can tackle it as non dismissable and edit later if we need.
