### ISSUE TITLE
[CAL-1637] /settings/conferencing missing "Add" button.

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8772]
There should be an "Add" button at the top of the page (similar to /settings/calendars) that takes you to [https://app.cal.com/apps/categories/video](https://app.cal.com/apps/categories/video)

![CleanShot 2023-05-09 at 10.13.33@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9665fcfe-3988-43d3-8b55-65d5296fb8b9/15c5fbe8-e718-4437-906d-40b22354100a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1637](https://linear.app/calcom/issue/CAL-1637/settingsconferencing)</sub>

**Comment by asadath1395** [comment]
@Jaibles I would like to work on this, please assign this on my name. Thanks

**Comment by Saga-sanga** [comment]
@Jaibles If no one's working on this I'd like to take up this issue, please.

**Comment by Jaibles** [comment]
Thanks @asadath1395 @Saga-sanga. Going to take the first in the door on this one so I've assigned @asadath1395. If you run in to any issues please let us know asap so we can pass it on 🙏

**Comment by asadath1395** [comment]
@Jaibles Seems like @paridhi7 raised a PR even though the issue was not assigned to @paridhi7
