### ISSUE TITLE
[CAL-1638] [CAL-1579] Fix Team Invite Text and Logos

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8778]
The logos and text on team invite are off in the email

Image in threads
Created via Threads. See full discussion: [https://threads.com/34466378425](https://threads.com/34466378425)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1579](https://linear.app/calcom/issue/CAL-1579/fix-team-invite-text-and-logos)</sub>

<sub>[CAL-1638](https://linear.app/calcom/issue/CAL-1638/[cal-1579]-fix-team-invite-text-and-logos)</sub>

**Comment by PeerRich** [comment]
cant reproduce either
