### ISSUE TITLE
[CAL-1640] Booked collective event sends confirmation email to only one member.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8782]
The team event in question https://cal.com/team/storyblok/partner-alignment-interview 

I noticed that this team was created by another member of the storyblok team. And the avatar of the event type creator somehow appears after the slot selection. 

See video:

﻿https://app.birdeatsbug.com/sessions/2g8dpxBEZSckP1Ltwze5SIg1s-UHIk4aK1t-zS6vrtFf﻿

Created via Threads. See full discussion: [https://threads.com/34469889848](https://threads.com/34469889848)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1640](https://linear.app/calcom/issue/CAL-1640/booked-collective-event-sends-confirmation-email-to-only-one-member)</sub>

**Comment by pranjalg13** [comment]
@milospuac can you make the video available public I cannot access the link

**Comment by richardjlo** [comment]
Hi! This bug is also affecting our cal.com instance. We're using the self-hosted version.

**Comment by emrysal** [comment]
Fixed in v3.1.4
