### ISSUE TITLE
Teams page banner image breaks content on smaller screens

### ISSUE THREAD

**Issue by Saga-sanga** [calcom/cal.com#8785]
### Issue Summary

https://app.cal.com/teams banner background image makes text content unreadable on smaller screens.

### Steps to Reproduce

1. Go to app.cal.com/teams
2. Resize Screen

### Screenshot
<img width="466" alt="Screenshot 2023-05-09 at 8 52 18 PM" src="https://github.com/calcom/cal.com/assets/35249409/7ac2b20c-74c3-4f57-8238-93691f8597e7">

### Suggestion
Perhaps remove background image entirely on smaller screens.

**Comment by imshubh4141** [comment]
Can you assign me this? @Saga-sanga
