### ISSUE TITLE
Tab on Create Event richt text doesn't skip to next field

### ISSUE THREAD

**Issue by jobenjada** [calcom/cal.com#8800]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Tab on Create Event richt text doesn't skip to next field. Instead it adds a tab to the richt text.

### Steps to Reproduce

1. Create an event
2. In the description, hit TAB

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

![grafik](https://github.com/calcom/cal.com/assets/72809645/8f5905b8-9a97-4b55-bfad-1d926e6298cf)

**Comment by RayAsh37** [comment]
This is a fix that is being worked on by facebook/lexical team. Here is the link
https://github.com/facebook/lexical/issues/2854

**Comment by Udit-takkar** [comment]
@RayAsh37 Ok i am fixing conflicts and reviewing it
