### ISSUE TITLE
Copy time to - not working 

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#8805]
### Issue Summary

When you use multiple days to copy the time to, then remove one of those days and click the apply button. It only copy time to the removed day! 😕 

### Steps to Reproduce

1. Go to: https://app.cal.com/availability
2. Chose a time schedule
3. Change time in one of the days,
4. Press the copy to and chose multiple days, 
5. Remove one of those days and press apply 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

https://github.com/calcom/cal.com/assets/18273833/dbea2928-97d3-4f79-8a85-fd86c27394cb

**Comment by Jittojoyes98** [comment]
is this an easy fix?

**Comment by a0m0rajab** [comment]
This is happening due to the slice return value here: 
https://github.com/calcom/cal.com/blob/main/packages/features/schedules/components/Schedule.tsx#L400
A simple solution could be just using the filter method for the array or even using a set (which is more suitable for this case) 

I used the filter approach at this PR: https://github.com/calcom/cal.com/pull/8796 

Yet, a refactor to use Set is more valuable and makes the code easier to read and understand. 

The reason of this issue is that slice returns a shallow copy of the selected array, 
it would be better to use splice, but then it will return the selected element (first google search get this) 
Filter will return an array which meet the condition that we have. 

Set will allow us to remove and add elements easily without using extra logic. 

```js
let array = [1,2,3,4,5]
array.slice(array.indexOf(3),1)
```
This return an empty array and does nothing
```js
array.splice(array.indexOf(3),1)
```
this return the elements that removed. 
```js
array = [1,2,3,4,5]
array.slice(array.indexOf(3),1)
```

Ref: 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

**Comment by Jittojoyes98** [comment]
Woh thanks , will look into it after i set up locally. Iam new here will need some time though.

**Comment by Iam-Arjun23** [comment]
I think this issue is fixed!!
[Screencast from 2023-05-12 22-23-35.webm](https://github.com/calcom/cal.com/assets/81867699/18d78c8a-a294-44f2-a17d-ab7c92ead473)

**Comment by a0m0rajab** [comment]
It's not fixed yet, but I opened a PR to fix it.

**Comment by a0m0rajab** [comment]
what's missing in your video is: deselect one of the days and pressing apply.

**Comment by Iam-Arjun23** [comment]
Oh! got it. Thanks

**Comment by a0m0rajab** [comment]
Fixed in: https://github.com/calcom/cal.com/pull/8796
