### ISSUE TITLE
[CAL-1643] Error on booking but the confirmation is sent and event gets created on the organizer'ss calendar

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8806]
Event in question [https://cal.com/prof-feld/lutheran-chapel-service?duration=30](https://cal.com/prof-feld/lutheran-chapel-service?duration=30)

![Screenshot 2023-05-10 at 10.56.06.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1beede35-b2c3-46c6-94e6-cff9e93ecb2a/ac76d6ad-bb79-4c10-bc7e-af13afa5167e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1643](https://linear.app/calcom/issue/CAL-1643/error-on-booking-but-the-confirmation-is-sent-and-event-gets-created)</sub>

**Comment by kunal8411** [comment]
I tried to reproduce this issue but not able to reproduce the same. Once I select the time and date I see the confirmation page and the same event calendar invite i got in email.

**Comment by PeerRich** [comment]
tested, cant reproduce
