### ISSUE TITLE
[CAL-1645] Add additional email addresses

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#8809]
As a user I want the ability to be able to 

* add multiple email addresses to my account.
* change which email address is my primary email
* use either email address on an event type link and have the chosen email show as the organiser

[View in Figma](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr?node-id=1021:104990&locale=en)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1645](https://linear.app/calcom/issue/CAL-1645/add-additional-email-addresses)</sub>

**Comment by paridhi7** [comment]
Hi @Jaibles can you please assign this to me?

**Comment by Jaibles** [comment]
Designs attached:

https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr?node-id=1021:104990&locale=en

**Comment by riteshsp2000** [comment]
Hey @Jaibles @hariombalhara 

I'd like to work on this issue. Looks like this will be requiring both backend and frontend changes. I can share my solution and we could discuss it accordingly.
