### ISSUE TITLE
[CAL-1646] Date overrides icon not centered

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8813]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Icon is not centered with text

<img width="698" alt="Screenshot 2023-05-10 at 4 35 14 PM" src="https://github.com/calcom/cal.com/assets/53316345/5a726aae-183a-4001-90d9-1f60790770a5">

### Steps to Reproduce

1. Go to http://localhost:3000/availability
2. click on any availability

<sub>[CAL-1646](https://linear.app/calcom/issue/CAL-1646/date-overrides-icon-not-centered)</sub>

**Comment by RayAsh37** [comment]
I have opened a PR, Please review @Udit-takkar

**Comment by yp969803** [comment]
@Udit-takkar i want to work on this
