### ISSUE TITLE
[CAL-1648] Webhooks tab is empty

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8815]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

<img width="1440" alt="Screenshot 2023-05-10 at 4 50 32 PM" src="https://github.com/calcom/cal.com/assets/53316345/24c60e7b-5944-455f-b31e-ae59ba0d90ef">

### Steps to Reproduce

1. on http://localhost:3000/event-types click on any event type
2. click on webhooks tab

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

<sub>[CAL-1648](https://linear.app/calcom/issue/CAL-1648/webhooks-tab-is-empty)</sub>

**Comment by RayAsh37** [comment]
I think it's just loading very slowly. It's showing on mine.
![Screenshot (7)](https://github.com/calcom/cal.com/assets/70441807/3764e04e-7e4f-4214-8ce1-9b5366cc65ff)

But yes, the changes are not visible in production.

**Comment by Kfelts** [comment]
It's not loading at all on mine. I was worried it was gone.
