### ISSUE TITLE
[CAL-1649] Create a template for zoom like Conferencing app.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8821]
We have templates for different types of apps. We need one to create an app similar to zoom. Right now people copy zoom or other conferencing apps. Copying has the problem that they keep on using legacy code. There are a lot of problems in that code. To name a few

* Hardcoded slug, appId, type everywhere
* Copying of common functions that would be required by almost all the conferencing apps that are like zoom

The template that we want to create should abstract out all common functions and improve the code quality. Now, when someone creates a conferencing app from that template, it would use the good quality code.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6cf763f0-d1c8-4304-a5db-546236c10e00/fcfad1c0-4a47-4469-ae26-e88cfa14b0a0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1649](https://linear.app/calcom/issue/CAL-1649/create-a-template-for-zoom-like-conferencing-app)</sub>

**Comment by unni-alokin** [comment]
can you elaborate on the issue
