### ISSUE TITLE
[CAL-1671] Bio details overflow issue on user profile

### ISSUE THREAD

**Issue by Chiranjeev-droid** [calcom/cal.com#8822]
### Issue Summary

When testing responsiveness on the Cal website, I added random text to my bio details and noticed that the text appears to overflow on the single user profile page, both on desktop and mobile devices. To reproduce the issue, simply sign in to Cal, update your bio details with random big text, and go to your profile link. The overflowing content is clearly visible.

---
![WhatsApp Image 2023-05-10 at 19 17 03](https://github.com/calcom/cal.com/assets/66114276/1c4ae969-20d3-4d23-8c63-7cae11a9d246)

<img width="1436" alt="Screenshot 2023-05-10 at 1 05 13 PM" src="https://github.com/calcom/cal.com/assets/66114276/e9d23809-eaf4-49b4-af45-90338afba833">
---
### Steps to Reproduce

1. Sign in to Cal.
2. Edit your bio details to include random non breaking big text.
3. Save the changes.
4. Navigate to profile page link.
5. Observe that the bio details overflow and the text is not properly wrapped.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Actual behavior:** The text in the bio details overflows on both desktop and mobile devices.

**Expected behavior:** The text in the bio details should be properly wrapped and displayed within the allocated space.

---
![image](https://github.com/calcom/cal.com/assets/66114276/2b176ef4-d8d9-475a-9e30-ffa3f28fcab2)

![image](https://github.com/calcom/cal.com/assets/66114276/a34dee70-36e4-4dc3-b6ef-c8a9f5b16703)

---

<sub>[CAL-1671](https://linear.app/calcom/issue/CAL-1671/bio-details-overflow-issue-on-user-profile)</sub>

**Comment by Veer0x1** [comment]
assign me this issue

**Comment by santosh-kuchetti** [comment]
I am working on this issue

**Comment by Chiranjeev-droid** [comment]
@santosh-kuchetti This issue has already been resolved in the pr #8824

**Comment by santosh-kuchetti** [comment]
@Chiranjeev-droid  cool thanks for updating
