### ISSUE TITLE
[CAL-1651] Possible issue with delete meetings in Video Apps like Zoom

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8831]
The `credentialId` is set to the calendar's `credentialId` [here](https://github.com/calcom/cal.com/blob/main/packages/core/EventManager.ts#L141).
This does not cause errors in [`updateMeeting`](https://github.com/calcom/cal.com/blob/main/packages/core/EventManager.ts#L534) because the correct video credentials are obtained using [`getVideoCredentials`](https://github.com/calcom/cal.com/blob/main/packages/core/EventManager.ts#L365).

However, the `handleCancelBooking` handler directly calls `deleteMeeting` in the `videoClient` and does not use `getVideoCredentials` to obtain the video integration credentials. Accordingly, no `videoAdapter` is found for `deleteMeeting`.

_Originally posted by @aar2dee2 in https://github.com/calcom/cal.com/issues/7651#issuecomment-1485382423_
            

<sub>[CAL-1651](https://linear.app/calcom/issue/CAL-1651/possible-issue-with-delete-meetings-in-video-apps-like-zoom)</sub>

**Comment by hariombalhara** [comment]
@alannnc assigned this issue to you, let me know if someone else should take care of it.

**Comment by shaikhazrath** [comment]
i want fix this assign it to me

**Comment by aar2dee2** [comment]
Happy to work on this. Please feel free to assign/share how you want to proceed.

**Comment by alannnc** [comment]
@aar2dee2 Assigned, please let me know if you still can work on this.
It looks like we should fetch credentials before calling deleteMeeting?

**Comment by aar2dee2** [comment]
thanks @alannnc

I'd made a fix in one of the commits in the [Webex app PR](https://github.com/calcom/cal.com/pull/7651)
See the `packages/features/bookings/lib/handleCancelBooking.ts` file [here](https://github.com/calcom/cal.com/pull/7651/commits/7c3612b636fc6ec373fd5423b9918dfec881d6f6#diff-87a46901f0685bc1affbfaab91860fb47aaf0f689c17bd379a56d8a9aaa51716)

Would that approach be suitable?

**Comment by alannnc** [comment]
Solved here

[https://github.com/calcom/cal.com/pull/9281](https://github.com/calcom/cal.com/pull/9281)
