### ISSUE TITLE
[CAL-1672] Calendar override with the wrong dates and time

### ISSUE THREAD

**Issue by CarlosSoares** [calcom/cal.com#8833]
### Issue Summary

When we set the availability for an timezone for example Europe/Berlin and enable Saturday from 12:00 am to 12:15 am on the date override instead of showing the Saturday appears the Friday between 10 pm to 10:15 pm.

This was reproduced in our system and in app.cal.com

### Steps to Reproduce

1. Go to Availability
2. Create a new one
3. Select the Timezone Europe/Amsterdam (set your computer to the same timezone)
4. Enable Saturday and put it from 12:00 am to 12:15 am
5. Save the availability 
6. Add an override 
7. In this step instead of showing the Saturday it will show the Friday

### Attatchments
<img width="1693" alt="image" src="https://github.com/calcom/cal.com/assets/1266477/0ac74eca-236c-4ab3-a586-1d13d766286a">
<img width="1672" alt="image" src="https://github.com/calcom/cal.com/assets/1266477/7f2ac072-6220-499c-9174-d6437ba962cb">
<img width="1661" alt="image" src="https://github.com/calcom/cal.com/assets/1266477/f19ef8b9-9337-4760-bca5-6e519e0b31ad">

<sub>[CAL-1672](https://linear.app/calcom/issue/CAL-1672/calendar-override-with-the-wrong-dates-and-time)</sub>

**Comment by ameeetgaikwad** [comment]
@CarlosSoares assign me this!

**Comment by ameeetgaikwad** [comment]
I've reproduced the issue

**Comment by CarlosSoares** [comment]
@ameeetgaikwad I can't assign it to you, maybe I don't have the right permissions

**Comment by CarlosSoares** [comment]
@COFFINSELLAR I can reproduced all the time in all new calendars

**Comment by ameeetgaikwad** [comment]
@COFFINSELLAR it does for me

**Comment by COFFINSELLAR** [comment]
Somehow I am not able to replicate it 😑
![Screenshot 2023-05-11 112129](https://github.com/calcom/cal.com/assets/87764254/039bc282-34f9-4935-abe4-e41bfefeefac)

**Comment by AyushMainali123** [comment]
Hi all, just wanted to let you know that I've started working on this bug. I've reproduced the issue on my local environment and have been investigating the code to identify the root cause.

**Comment by sanudutta45** [comment]
Hi all, I believe that the dates and times in the calendar are being determined based on the user's default availability time zone, rather than the time zone the user has selected.

**Comment by PeerRich** [comment]
@ameeetgaikwad feel free to work on it, no need to be assigned here!

**Comment by prakhart4** [comment]
Do we want the Date overrides selection calendar to show the user's timezone date and time (which would be converted from the schedule's timezone to the user's timezone) or always the schedule's timezone date and time?
