### ISSUE TITLE
[CAL-1652] Embed code examples that demo how one can change the look and feel of the embed.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8841]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1652](https://linear.app/calcom/issue/CAL-1652/embed-code-examples-that-demo-how-one-can-change-the-look-and-feel-of)</sub>

**Comment by zacsanter** [comment]
Surely this should be a higher priority if your live marketing page says it's possible?

**Comment by hariombalhara** [comment]
@zacsanter I quickly set up a codesandbox that shows how CSS variables can be customized in the embed.
See https://codesandbox.io/s/embed-advanced-css-vars-x2sdgy?file=/src/App.tsx
<img width="1013" alt="Screenshot 2023-07-31 at 4 12 44 PM" src="https://github.com/calcom/cal.com/assets/1780212/95972a1c-0719-4b7c-83a1-0e62e23a80d0">

<img width="1164" alt="Screenshot 2023-07-31 at 4 12 52 PM" src="https://github.com/calcom/cal.com/assets/1780212/875ecd52-b99c-4d55-afca-2acd04206326">
<img width="1089" alt="Screenshot 2023-07-31 at 4 13 11 PM" src="https://github.com/calcom/cal.com/assets/1780212/175d901a-ca1c-434d-b8f3-d2623246f02e">

There are more CSS variables that can be configured. Let me know if you have something else in mind.

**Comment by zacsanter** [comment]
Thanks for this. I can't work out how to change the main background colour though. That's what's clashing the most with my website.

**Comment by hariombalhara** [comment]
Changing the background color is quite easy but we don't really want to allow that because that would mean that the text might not be clearly visible on that background.

Is it possible for you to share a screenshot of how you would want it to look. I am interested in seeing the background color and how the booking page text looks on it.

**Comment by hariombalhara** [comment]
I have created a new issue https://github.com/calcom/cal.com/issues/10710 to track the progress of it. Let's discuss over there.

**Comment by hariombalhara** [comment]
![Image](https://github.com/user-attachments/assets/a2c3ad5e-d2f9-48bf-b594-8c0ba243824c)
This is how it appears, I believe you might have unintentionally tampered with a CSS variable
