### ISSUE TITLE
Possible undesirable mobile homepage layout

### ISSUE THREAD

**Issue by JesseKoldewijn** [calcom/cal.com#8844]
### Issue Summary

Not sure if the styling below is intentional but it looks kind of off to me.

### Steps to Reproduce

See screenshot below.
![image](https://github.com/calcom/cal.com/assets/60965908/266237d4-539b-43ec-9fbb-51b98e8146e5)

**Comment by JesseKoldewijn** [comment]
Mainly talking about the toasts floating abouve the calender entry.

**Comment by abhijain2003** [comment]
I think we should shift these toasts to the top so, user can see it more clearly

can I work on this?

**Comment by JesseKoldewijn** [comment]
> I think we should shift these toasts to the top so, user can see it more clearly
> 
> can I work on this?

Not my call man😜 I'd say go for it. I just wanted to point it out cuz it kinda looked odd to me😅

**Comment by abhijain2003** [comment]
sure, I am in

**Comment by PeerRich** [comment]
this is supposed to be like it is 🙏
