### ISSUE TITLE
[CAL-1655] Embed on mobile button stays above booking modal

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8851]
![DE316375-F10F-49B5-8D80-778DBA55B10A.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9baf223-df2b-48c1-812f-822122070a3c/ce120f0d-4c85-4c43-a224-01ce225d11c8)

So I can’t actually click to confirm the booking. This floating button should disappear while modal is open. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1655](https://linear.app/calcom/issue/CAL-1655/embed-on-mobile-button-stays-above-booking-modal)</sub>

**Comment by thebishalniroula** [comment]
Hi @Jaibles , can I work on this?

**Comment by Jaibles** [comment]
@Udit-takkar did you start on this yet?

**Comment by riteshsp2000** [comment]
@hariombalhara @Jaibles I'd like to work on this if it's still up for grabs.

**Comment by hariombalhara** [comment]
Go for it. I don't think @thebishalniroula is working on it.

**Comment by iamgauravbisht** [comment]
hi, can I work on this?
