### ISSUE TITLE
need UI fixes my-account/profile

### ISSUE THREAD

**Issue by 98rahul** [calcom/cal.com#8854]
### open the [url](http://localhost:3000/settings/my-account/profile)
_on focusing  the input field border came._

![image](https://github.com/calcom/cal.com/assets/71221556/fd8b1b03-e4d5-48a4-9141-84945e67d9c3)

**Comment by sachin-vinod** [comment]
I want to work on this issue

**Comment by sachin-vinod** [comment]
I want  to work on this issue, but can you confirm is i am getting this problem statement correctly or not. When you say that the input field border "came" when focusing, I assume you mean that a border or outline appears around the input field when it is selected or clicked on. This is a common visual indicator used in web development to show that a particular input field is active and ready to receive user input.

**Comment by 98rahul** [comment]
its done 🏁✔

> I want to work on this issue, but can you confirm is i am getting this problem statement correctly or not. When you say that the input field border "came" when focusing, I assume you mean that a border or outline appears around the input field when it is selected or clicked on. This is a common visual indicator used in web development to show that a particular input field is active and ready to receive user input.

its done 🏁✔

**Comment by 98rahul** [comment]
@Udit-takkar 
if you do focus on the field there's extra border coming out form the username, fullname,email  input text field..
