### ISSUE TITLE
[CAL-1670] No verification required, when changing email

### ISSUE THREAD

**Issue by dhairyamodi2** [calcom/cal.com#8856]
### Issue Summary

No verification required, when changing email.

### Steps to Reproduce

1. Went to profile section in settings
2. Changed email

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/784bb168-a5b7-4e30-a642-b658c7630da8/a6d4090b-a0d0-41c2-a7d5-b63352fbd103)

A verification mail can be sent to confirm that user has not misspelled his/her email. And user can retrieve his/her account in case he/she forgot password.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1670](https://linear.app/calcom/issue/CAL-1670/no-verification-required-when-changing-email)</sub>

**Comment by pranjalg13** [comment]
<img width="1422" alt="Screenshot 2023-05-12 at 3 57 44 PM" src="https://github.com/calcom/cal.com/assets/47600057/0d71fa62-d70f-475e-bf8c-551368a5eaf8">

Hey, @dhairyamodi2 it requires a password to update your email. Not able to reproduce too, please take a pull from master once

**Comment by dhairyamodi2** [comment]
Got it. That change hasn't been deployed to production yet.

**Comment by dhairyamodi2** [comment]
In the screenshot you are referring to, login is done via email and password. But when I sign in with google, no such overlay pops up to confirm password, and email can be updated without verification.

**Comment by PeerRich** [comment]
@sean-brydon is working on email verification for both signup and changing emails

**Comment by keithwillcode** [comment]
@sean-brydon is going to test to see if this is still an issue.
