### ISSUE TITLE
[CAL-1657] App store: Replace the "Weather in your calendar" app icon

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8857]
Currently it's a GIF. It looks bad. We need to replace it.

[Favourite - 3. Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/3.-Cal---New-Features?type=design&node-id=4670%3A356355&t=MwZa1ewzubyhUc6y-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1657](https://linear.app/calcom/issue/CAL-1657/app-store-replace-the-weather-in-your-calendar-app-icon)</sub>

**Comment by pranjalg13** [comment]
Hey @Jaibles, would love to work on this.
Please assign me.

Thanks

**Comment by Jaibles** [comment]
Hey @pranjalg13, feel free to push a pr and mention/link this issue when you've done so and someone from the team will review 🙏

**Comment by pranjalg13** [comment]
@Jaibles please review the pr once
thanks

**Comment by Jaibles** [comment]
> @Jaibles please review the pr once thanks

Link?
