### ISSUE TITLE
[CAL-1659] Light Mode-Dark Mode flicker in embed

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#8860]
> [https://share.getcloudapp.com/OAuo5xgZ](https://share.getcloudapp.com/OAuo5xgZ)
> If Cal is embedded on a site and open in dark theme mode, but a second page in the same (Chrome) browser is open with Cal embedded (in white theme mode), the colors of the black Cal embeds start flickering from black to white continuously in seconds.
> [Screen Recording 2023-05-12 at 09.31.53 AM](https://share.getcloudapp.com/OAuo5xgZ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1659](https://linear.app/calcom/issue/CAL-1659/light-mode-dark-mode-flicker-in-embed)</sub>

**Comment by kanakpandit17** [comment]
Can you give steps to reproduce

**Comment by alishaz-polymath** [comment]
> If Cal is embedded on a site and open in dark theme mode, but a second page in the same (Chrome) browser is open with Cal embedded (in white theme mode), the colors of the black Cal embeds start flickering from black to white continuously in seconds.

**Comment by PeerRich** [comment]
@hariombalhara can you look if this is still ongoing?

**Comment by StariMarco** [comment]
Hi! I think I have the same issue. 

https://github.com/calcom/cal.com/assets/49818192/c74b0635-7df3-4266-87b4-3e79c9c9c648

**Comment by StariMarco** [comment]
Hi, I think I'm experiencing the same issue.

https://drive.google.com/file/d/1GRBvzFwe2fIbbWpx8DuOFuVsbKOOzuUY/view?usp=sharing

**Comment by StariMarco** [comment]
Okay, I changed the theme from "System default" to "Light" in Settings > Appearance and now it seems to be working fine.

![Screenshot at May 14 23-00-02](https://github.com/calcom/cal.com/assets/49818192/a7edb024-fb4f-42e1-8f5a-40982e454136)
