### ISSUE TITLE
New Availability Override Calender Showing wrong days selected 

### ISSUE THREAD

**Issue by sanudutta45** [calcom/cal.com#8862]
###  Issue Summary

I may have encountered an issue with the availability calendar where incorrect days are being selected or highlighted when creating a new calendar. Can someone help me investigate this further?

This was reproduced in app.cal.com

### Steps to Reproduce

1. Go to Availability
2. Create a new one
3. Disable one or more day(s)
5. Add an override
In this step, instead of highlighting only the days we have selected, it's highlighting all the days from my default availability. I think can be misleading.

If you can approve this as a bug then I can start working on it.

![image](https://github.com/calcom/cal.com/assets/60579654/f3b02896-a929-49af-b43d-a3fff2c1db2d)

**Comment by HARI-124** [comment]
I think It is working fine because we might override a day if we are unavailable and normal working hours will be usual I think the existing one is fine?

**Comment by PeerRich** [comment]
cant reproduce this

**Comment by PeerRich** [comment]
also we're reworking date overwrites so this will probably be more stable in the next update of this feature
