### ISSUE TITLE
[CAL-1667] bottomNav: only border top

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8868]
![CleanShot 2023-05-12 at 20 23 55@2x](https://github.com/calcom/cal.com/assets/8019099/7e08ebce-0ecf-483e-8d28-fe4906abf0b5)

<sub>[CAL-1667](https://linear.app/calcom/issue/CAL-1667/bottomnav-only-border-top)</sub>

**Comment by virinchimanepalli** [comment]
@PeerRich I wanted to work on this. could you assign it to please?

**Comment by PeerRich** [comment]
i'm already assigned and pushing a PR
