### ISSUE TITLE
Delete button in availability should show tooltip based on schedules length

### ISSUE THREAD

**Issue by VinoV1999** [calcom/cal.com#8876]
### Issue Summary

When hover the delete button it shows tooltip of message **"You are required to have at least one schedule"** though we have more than 1 schedules.

### Steps to Reproduce

1. Go to Availability
2. Select any schedule

I feel, better to make it **"Delete"** if we have more than 1 schedules else **"You are required to have at least one schedule"**. like how we're disabling the button?

<img width="389" alt="avalibility expected delete tt img" src="https://github.com/calcom/cal.com/assets/123581387/6c239f6a-0f1f-4219-9291-ccf7d4ae0e3c">

<img width="410" alt="Avalibility existing delete tt img" src="https://github.com/calcom/cal.com/assets/123581387/15401b4c-3951-4403-ae28-ea3fe537544c">

**Comment by VinoV1999** [comment]
hey prakhart/pramitbhar i'm not sure whether it's required r not. That's why i haven't  pushed though i fixed it

**Comment by Udit-takkar** [comment]
will be fixed here https://github.com/calcom/cal.com/pull/8630
