### ISSUE TITLE
[CAL-1669] Limit future bookings darkmode issues

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#8880]
<img width="613" alt="image" src="https://github.com/calcom/cal.com/assets/1046695/0f6edca9-a4f6-429b-820d-bef5c644252d">

<sub>[CAL-1669](https://linear.app/calcom/issue/CAL-1669/limit-future-bookings-darkmode-issues)</sub>

**Comment by Siddhesh4501** [comment]
Can you assign me this issue. I will try my best to solve it.

**Comment by ParthSharma99** [comment]
Hi @emrysal, can I be assigned this issue ?

**Comment by Mr-Usman** [comment]
I would like to solve this bug @emrysal  :)

**Comment by PeerRich** [comment]
great work @ParthSharma99
