### ISSUE TITLE
Restriction of more page according to media query

### ISSUE THREAD

**Issue by YOKESHCR** [calcom/cal.com#8881]
When the screen page is reduced to a smaller screen size the links teams,workflows,insights and settings will be reduced within more link which redirects to the more page
![image](https://github.com/calcom/cal.com/assets/27686539/3475cd94-0ee0-4a62-8dd9-77070cb59163)
But when the screen size is increased I am still able to view the More page. Can the code be changed such that when the screen size is increased it is actually redirected to the home page (Event-Page)
![image](https://github.com/calcom/cal.com/assets/27686539/b1a2e0b6-e7b2-49da-9307-f5100f819962)
If this is considered, I can actually contribute to it.

**Comment by PeerRich** [comment]
i think this is a very rare edge case and not bad per se. closing as priority is too low/the behavior is not bad enough to be fixed
