### ISSUE TITLE
Text colour remains white even when the button is inactive.

### ISSUE THREAD

**Issue by virinchimanepalli** [calcom/cal.com#8883]
## Issue Description
The Text color remains white even when the button is inactive. making it difficult to read the text.

### Current Behavior
The text color remains white even when the button is inactive.
<img width="261" alt="image" src="https://github.com/calcom/cal.com/assets/50209716/6e8bfa45-da2a-4f9e-bcff-b548be373deb">

### Expected Behavior
When the button is inactive, the text color could be grey. 
<img width="290" alt="image" src="https://github.com/calcom/cal.com/assets/50209716/50c0bc15-22cc-4376-8c9c-a382205ea243">

### Steps to Reproduce[image attached]
1. Visit the Home page of the schedule section.
2. Notice that only the button color changes, while the text color remains the same.

If this issue is confirmed as a valid bug and not fixed yet, kindly assign it to me. I would like to take responsibility for fixing it.

### Screenshots or Code Snippets
<img width="834" alt="Screenshot 2023-05-14 at 3 51 34 PM" src="https://github.com/calcom/cal.com/assets/50209716/9041da25-7896-45bd-9531-a0303da46654">

**Comment by abhijain2003** [comment]
ya this must be a css issue

**Comment by UtkarshDixit-py** [comment]
I can work on this, please assign this to me.

**Comment by PeerRich** [comment]
ah this is on website. fixed. deploying now

![CleanShot 2023-05-14 at 21 29 08@2x](https://github.com/calcom/cal.com/assets/8019099/cafb1dc8-4fb6-4559-912f-65cadd373199)
