### ISSUE TITLE
[CAL-1696] invisible icon - email

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#8890]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you get an email to confirm/reject, the icon of rejections is not visible due to its color: 
![image](https://github.com/calcom/cal.com/assets/18273833/ea17de2f-178d-4acd-b2d6-98bfcc70a45e)

### Steps to Reproduce

1. Open your schedule, 
2. Set a slot that needs a confirmation 
3. Book a time with confirmation 
4. check your email

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

As a solution, this could be solved with 
```css
filter: invert(100%);
```
in the CSS but it's needed to be passed as props. 

The related code: https://github.com/calcom/cal.com/blob/main/packages/emails/src/templates/OrganizerRequestEmail.tsx

<sub>[CAL-1696](https://linear.app/calcom/issue/CAL-1696/invisible-icon-email)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar can you investigate this?

**Comment by a0m0rajab** [comment]
can I work on his @PeerRich, I think it needs a props to be passed to the call to action component and use it in the style. 
Like this: 

```js
  <CallToAction
            label={props.calEvent.organizer.language.translate("reject")}
            href={`${actionHref}&action=reject`}
            startIconName="rejectIcon"
            startIconStyle = {{{filter: 'invert(1)'}}}
            secondary
          />
```

Then use it in the call to action component https://github.com/calcom/cal.com/blob/main/packages/emails/src/components/CallToAction.tsx

**Comment by Udit-takkar** [comment]
@a0m0rajab  We use filter: "brightness(50%)" to do this task. ( You can check CallToActionIcon.tsx file)

which works fine if you navigate to http://localhost:3000/api/email

<img width="302" alt="Screenshot 2023-05-22 at 2 39 57 AM" src="https://github.com/calcom/cal.com/assets/53316345/55306ee6-07f0-43fd-9fc0-646131f481f6">

but for some reason the filter property is not added in the style of image in email. I tested bunch of things like adding filter: "invert(1)" also but still trying to debug

<img width="200" alt="Screenshot 2023-05-22 at 2 37 18 AM" src="https://github.com/calcom/cal.com/assets/53316345/b8113f0b-4264-41bc-bfb7-2e76a51371b0">

I

**Comment by a0m0rajab** [comment]
@Udit-takkar I just double checked seems that the web emails HTML is way different than the HTML we use daily, not all of the properties are supported neither all options are possible to use there. 

Here is a list of the CSS properties that are supported by [Gmail](https://developers.google.com/gmail/design/css), and here is a guide from [Mailchimp for emails ](https://templates.mailchimp.com/resources/email-client-css-support/)as well. 
Neither of them has filter as an option, I think it would be better to have the image as an image added directly without using filters or CSS and keep it as not for any future development for HTML e-mails to not face the same issue. 

Related [StackOverFlow question](https://stackoverflow.com/questions/42388757/css-properties-not-appearing-in-email)

**Comment by Udit-takkar** [comment]
@a0m0rajab yeah this is what i did here https://github.com/calcom/cal.com/pull/9031

**Comment by a0m0rajab** [comment]
Awesome! Great work 👍
