### ISSUE TITLE
[CAL-1677] Wrong language for months in confirmation email of a recurring booking.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8893]
### Issue Summary

Scheduled a recurring event and received a confirmation email with months in German which I think is of the organizer in this case.

Expected: I should have received it in English

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dcf48b55-0c18-4936-82f5-445663efeb12/fbcac480-7a89-419c-a394-bb6000c627da)

Another related bug:
When I added the event through invite.ics file to my calendar. It shows what, when and timezone in German.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0bb6c068-d567-453c-94eb-e3f436e7fe09/072b4db5-ccc9-4b47-987d-6fa361a93adf)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1677](https://linear.app/calcom/issue/CAL-1677/wrong-language-for-months-in-confirmation-email-of-a-recurring-booking)</sub>

**Comment by vedant-jain03** [comment]
@hariombalhara I would like to work on it!

**Comment by hariombalhara** [comment]
Sure @vedant-jain03. I am assigning it to you.

I think @Udit-takkar might be able to help if you need any. There was similar PR he was working on, not sure if it's the same issue.

**Comment by vedant-jain03** [comment]
<img width="563" alt="Screenshot 2023-05-16 at 9 13 29 AM" src="https://github.com/calcom/cal.com/assets/76901313/4c5c6a51-9ed5-46d0-986e-de9dab44836e">

@hariombalhara I try to reproduce the issue, but it was showing correct language. I made the event recurring. Let me know any particular step to reproduce the bug

**Comment by G3root** [comment]
fixed by #8941
