### ISSUE TITLE
Impersonation enable/disable toggle issue 

### ISSUE THREAD

**Issue by YOKESHCR** [calcom/cal.com#8907]
The impersonation toggle button is not working as expected. When the button is clicked it should be enabled/disabled but it is working as mentioned in the screen recording below 

https://github.com/calcom/cal.com/assets/27686539/20ad2f98-72d6-4705-ad2d-3beb7020599a

If this is considered as an issue I can contribute to it

**Comment by abhijain2003** [comment]
this is Logic Issue I think

if you can change the logic condition how it has applied 
if may work

all the best

**Comment by shaharyar-shamshi** [comment]
@YOKESHCR I think this is intended behaviour I don't there is any bug
