### ISSUE TITLE
Events Group control

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#8912]
### Is your proposal related to a problem?

I am hosting a podcast in two languages, I wanted to have a way to limit the episode schedule for both languages from the same place instead of doing this manually, but it was not possible. 

![image](https://github.com/calcom/cal.com/assets/18273833/184a9d67-8736-4c1f-a22d-2ae4c6687214)
At this place, it would be great to have an option like: connected events, where I can set an event to connect and have rules applied to both of them, for example, once a week. 

### Describe the solution you'd like

It would be possible to have an option to connect events

**Comment by PeerRich** [comment]
i am not sure i understand the issue. why not have two different event-types?

**Comment by a0m0rajab** [comment]
I have two event-types, but I thought it would be nice to connect two event types together. 

I will share the scenario: 
I have a podcast with two languages, each language has a different schedule and two different event types, but I want only to allow one appointment per week from these two event types. 

So if someone booked from event type A, B event type should not allow be booked at the same week.

**Comment by PeerRich** [comment]
oh i see. i dont think we'll hotfix this for this use case anytime soon. sorry

**Comment by a0m0rajab** [comment]
Should it be a feature request? (how feature requests works?)

**Comment by a0m0rajab** [comment]
Thank you for the information though.
