### ISSUE TITLE
[feat] : Option to generate random route for URL

### ISSUE THREAD

**Issue by vedant-jain03** [calcom/cal.com#8916]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

- We can give an option to generate random route in the URL. 
<img width="565" alt="Screenshot 2023-05-16 at 9 33 17 AM" src="https://github.com/calcom/cal.com/assets/76901313/fb9b3bcc-85d4-4198-9c46-6c3bab6b72a2">

- We can have an option "generate" that will fill the input with random value(using uuid).
- This can be helpful in quickness and security for the events.

**Comment by vedant-jain03** [comment]
@hariombalhara WDYT?

**Comment by hariombalhara** [comment]
I am not sure. These are generally supposed to be easily guessable names as they are visible on the user's profile as well.

**Comment by vedant-jain03** [comment]
Make sense, it will just make things easy for them. Have a look:


https://github.com/calcom/cal.com/assets/76901313/e4c68512-4336-4d65-a9db-17c94b110977


cc @hariombalhara

**Comment by gsriram24** [comment]
A URL is already getting automatically filled based on the title, which might seem to be a much better indicator of the event rather than a UUID.

**Comment by vedant-jain03** [comment]
> A URL is already getting automatically filled based on the title, which might seem to be a much better indicator of the event rather than a UUID.

Make sense, closing this.
