### ISSUE TITLE
[CAL-1700] Outlook always checking for conflicts in self-hosted (2.9)

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8929]
[https://www.loom.com/share/6ad4bc66498843eb9e67e8002e1ba8ff](https://www.loom.com/share/6ad4bc66498843eb9e67e8002e1ba8ff)

Created via Threads. See full discussion: [https://threads.com/34474890953](https://threads.com/34474890953)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1700](https://linear.app/calcom/issue/CAL-1700/outlook-always-checking-for-conflicts-in-self-hosted-29)</sub>

**Comment by npcoder2k14** [comment]
@PeerRich @milospuac  Please assign this bug to me. I'd like to fix it.
