### ISSUE TITLE
[CAL-1991] [CAL-1705] The Switcher

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#8956]
Create a switcher in the side menu to be able to switch between organizations

[The Switcher - 4. Orgs / Teams. - New Features (Figma)](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/4.-Orgs-%2F-Teams.---New-Features?type=design&node-id=3682-228253&t=Y4oVfM0RzKMWQ99w-4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1705](https://linear.app/calcom/issue/CAL-1705/the-switcher)</sub>

<sub>[CAL-1991](https://linear.app/calcom/issue/CAL-1991/[cal-1705]-the-switcher)</sub>

**Comment by mayank** [comment]
Picking this!
