### ISSUE TITLE
"Meeting Password: undefined" when user's zoom doesn't require meeting passwords

### ISSUE THREAD

**Issue by namesphill** [calcom/cal.com#896]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you schedule a meeting with a zoom video conference location with a user whose zoom settings don't require passwords for meetings, the email sent to all parties regarding the event's video call will read:

*Meeting Password*: undefined.

### Steps to Reproduce

1. Have your zoom account settings like so:
![168ea847-13b5-4126-91c0-704631170b97](https://user-images.githubusercontent.com/32855126/136722825-483e8486-de06-4976-b53f-853826646d09.png)
3. Schedule a meeting with yourself on an event type with zoom location
3. Read the delivered email

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect the "Meeting Password" to be absent or to indicate that the meeting in question doesn't require a password.

### Technical details

- Browser version: Safari 15
- Node.js version: v14.15.1

**Comment by ConnorGargano** [comment]
Hi @namesphill,
I will get this passed over to the engineering team to look into and see if we can make this more understanding in the booking confirmation.
-Thanks Connor

**Comment by PeerRich** [comment]
i think this was fixed a log time ago
