### ISSUE TITLE
handle browser javascript disabling

### ISSUE THREAD

**Issue by kirangurung2023** [calcom/cal.com#8961]
### Issue Summary
I've noticed that when JavaScript is disabled in the browser while using cal.com, the UI keeps loading indefinitely. This can lead to a less-than-ideal user experience and confusion.

### Steps to Reproduce
https://www.loom.com/share/f85a270c57874100aaee29eb73c549c9

###  Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
This is considered a bug because the application does not handle the scenario of JavaScript being disabled. Instead of providing a clear message or alternative content, the UI keeps loading indefinitely, leaving the user without any guidance or feedback on how to proceed.

### Technical details
Tried on chrome, hoping it is same for other borwser as well

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by imkrngrng** [comment]
I have attempted a simple solution to address this issue, but I am uncertain if it is the most appropriate approach. I would appreciate guidance and input regarding the best way to handle this situation effectively and ensure an optimal user experience.
PR : https://github.com/calcom/cal.com/pull/8958

**Comment by PeerRich** [comment]
are there really still people out there disabling javascript?

**Comment by imkrngrng** [comment]
@PeerRich probably not, but it can still be beneficial to have a feature that notifies users in case JavaScript is accidentally disabled or affected by certain web extensions. This can help prevent confusion maybe. Sorry if my answer doesn't make sense :-).

**Comment by official-Ayush** [comment]
is this issue still open?

**Comment by PeerRich** [comment]
not needed to be fixed. very unlikely case
