### ISSUE TITLE
[CAL-1715] Routing Form can't submit with an alert that 'No route is defined'

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8962]
It isn't possible to have no route right now, because there is always a fallback route. So, this scenario shouldn't happen

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/82130b92-f9fa-4a31-9a05-0cf734e6775f/a43e1119-99d9-4aa6-8547-9c2855dacbd6)

More details in [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=de841945-fb47-4fcf-b0ea-6c2e1a801b68](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=de841945-fb47-4fcf-b0ea-6c2e1a801b68)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1715](https://linear.app/calcom/issue/CAL-1715/routing-form-cant-submit-with-an-alert-that-no-route-is-defined)</sub>

**Comment by shirazdole** [comment]
When you have a routing form, and you don't add one of the variables as a choice for a route, then when a user clicks on that choice and wants to submit the form, they get the above response.

For example, say "10-50" is a choice in your form, but you don't properly link it to a route, you can still save the route and have it as an option to be selected from, but you don't have it linking to a route so you get the above issue.

**Comment by shirazdole** [comment]
If i were to remove 0-100 here in the routing, but it's still available in the form, that's when this issue occurs: 

![CleanShot 2023-05-18 at 12.44.33@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0519d650-4348-4722-8e76-c312e8d18931/ca80a255-15c0-4a16-9304-0aa25f5fd4e8)

![CleanShot 2023-05-18 at 12.44.16@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7e705503-9e7b-4146-9a81-911f8022475e/e16e8dbd-c16d-4962-a165-2a95dae98425)
