### ISSUE TITLE
[CAL-1718] Code Cleanup: All accounts are PRO now, so remove isProOnly flag from App Store Apps

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8963]
<img width="458" alt="Screenshot 2023-05-18 at 11 56 35 AM" src="https://github.com/calcom/cal.com/assets/1780212/50a5445b-9fe7-4670-88a4-de39e7be9081">

<sub>[CAL-1718](https://linear.app/calcom/issue/CAL-1718/code-cleanup-all-accounts-are-pro-now-so-remove-isproonly-flag-from)</sub>

**Comment by Sudhanshu10Sathawane** [comment]
Hii @hariombalhara I am new to open source contribution and would like to work on this issue.
Thank you

**Comment by Swapnil-2502** [comment]
So I just removed the lines of codes you mentioned above, I guess that was the requirement can you confirm it, should i request a PR now ?

**Comment by hariombalhara** [comment]
It should be  those lines in general. You should understand that logic and then test out that the flow is working now for apps installation.

**Comment by Swapnil-2502** [comment]
So actually when I run "yarn dev" 

It gives me this error:

@calcom/web:dev: error - PrismaClientInitializationError: 
@calcom/web:dev: Invalid `prisma.user.count()` invocation:
@calcom/web:dev: 
@calcom/web:dev: 
@calcom/web:dev: Can't reach database server at `localhost`:`5450`

What I might have done wrong ?

**Comment by shivamklr** [comment]
@Swapnil-2502 Try `yarn dx` command. You should have docker compose installed as well.

**Comment by Swapnil-2502** [comment]
@shivamklr I already have docker desktop installed but still "yarn dx" is not working.

**Comment by Swapnil-2502** [comment]
Docker is running locally.

But at VS code I am getting this error: 
<img width="1440" alt="Screenshot 2023-05-19 at 11 05 06 PM" src="https://github.com/calcom/cal.com/assets/69076366/9d8ddb11-115c-4db8-9a48-e3581b267f6e">

And this is after yarn dx

<img width="1372" alt="Screenshot 2023-05-19 at 11 05 40 PM" src="https://github.com/calcom/cal.com/assets/69076366/1dfe72de-8f2c-44e3-816b-df21bebc6164">

**Comment by HeratPatel** [comment]
@hariombalhara can I take this?
This is my first contribution with the project.
I have successfully setup the project in my local environment.

**Comment by HeratPatel** [comment]
@hariombalhara generated the PR (https://github.com/calcom/cal.com/pull/8996), please have a look.

**Comment by shivamklr** [comment]
@Swapnil-2502 If you are still facing an issue with the repository setup, consider reaching out on Slack.

**Comment by Swapnil-2502** [comment]
Just got done one hour ago, thanks
