### ISSUE TITLE
[CAL-1719] React-select overflow on Webhooks

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#8964]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/37f583ac-4853-4314-a4fa-bd58a2f506ba/af0d9e5e-7c91-45a5-8ef5-6314723ae9a7)

Webhooks select overflows when a large amount of items are selected.

Solution - scroll horizontal/increase container size vertically

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1719](https://linear.app/calcom/issue/CAL-1719/react-select-overflow-on-webhooks)</sub>

**Comment by CarinaWolli** [comment]
It's in Webhooks not Workflows

**Comment by sean-brydon** [comment]
> It's in Webhooks not Workflows

Half asleep :P Thank you will fix

**Comment by alceil** [comment]
Can I work on this @sean-brydon ?
