### ISSUE TITLE
[CAL-1721] Dark mode icons for Riverside and Sirius Video aren't visible

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#8966]
<img width="1239" alt="image" src="https://github.com/calcom/cal.com/assets/1780212/355d4d16-249b-42ba-af3c-2e37b8017798">

<sub>[CAL-1721](https://linear.app/calcom/issue/CAL-1721/dark-mode-icons-for-riverside-and-sirius-video-arent-visible)</sub>

**Comment by doesnots** [comment]
@hariombalhara can I take up this issue?

**Comment by hariombalhara** [comment]
Assigned. Thank you 🙏

**Comment by ParthSharma99** [comment]
@hariombalhara The images seem to be dark svg and seem to blend in with the background. Probably need to add some sort of background to make it visible in dark mode

**Comment by doesnots** [comment]
@hariombalhara @saurabbot's pr is quite commendable. You can review that. Thank you.

**Comment by chwasifjameel** [comment]
Is this issue closed?

**Comment by emrysal** [comment]
No @chwasifjameel but it is assigned, re-opened the associated PR which is likely to be merged.

**Comment by chwasifjameel** [comment]
Sounds good. Thank you

**Comment by ishsarin** [comment]
Hi, if this issue is open could I contribute?

**Comment by varun325** [comment]
Can you assign this to me please, seems like a fairly simple issue to fix for me.

**Comment by CoderGhost37** [comment]
@PeerRich @hariombalhara I have made a pr to resolve this issue. This is my first pr on this repo.
