### ISSUE TITLE
Wrong redirect after adding Ping.gg app

### ISSUE THREAD

**Issue by rkreddy99** [calcom/cal.com#8970]
Found a bug? Please fill out the sections below. 👍

After adding the **Ping.gg** app from App Store, the user is being redirected to **other** section in the **Installed Apps** instead of **conferencing** section

### Steps to Reproduce

1. Go to App Store
2. Install Ping.gg add on
3. User gets redirected to Installed Apps > other

https://www.loom.com/share/78485f1fc74a40679d84836948f945f8

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect the user to be redirect to the conferencing section, because that's where the Ping.gg is being shown

**Comment by rkreddy99** [comment]
@hariombalhara If this is a valid one, can I work on this and create the pr

**Comment by hariombalhara** [comment]
That's weird. Looks valid though. Thanks for reporting. Assigned to you
