### ISSUE TITLE
User full name overflowing nav bar width on settings page

### ISSUE THREAD

**Issue by ouwargui** [calcom/cal.com#8977]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.
Because nav bar has a fixed width, when the user has a long name, it overflows the nav bar width.

<img width="247" alt="image" src="https://github.com/calcom/cal.com/assets/44242141/f49cb472-1f1d-4ae0-8771-d71790dcc9d9">

### Steps to Reproduce

1. Go to settings page
2. If you have a long full name like me you'll see the name overflowing the nav bar width

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
The text is expected to wrap and show the user's full name

### Technical details

- Arc Version 0.103.0 (38794) | Chromium Engine Version 113.0.5672.92

**Comment by kshitiz-goel07** [comment]
Hey @ouwargui , 
Thank You for raising this bug 
Can you assign it to me 

 I can resolve it.

**Comment by sanudutta45** [comment]
We have to decide whether we want to wrap words or ellipse them.

**Comment by ouwargui** [comment]
@kshitiz-goel07 @sanudutta45 I have an open PR #8978 where I'm working on solving this problem, we are wrapping the text and the height of the text container needs to be fixed too.
