### ISSUE TITLE
[CAL-1723] Collective Event types - Search bar + borders

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#8984]
Found a bug? Please fill out the sections below. 👍

Create collective event  for a team

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f01a39a5-eef3-4fb5-84da-702a758faec7/647bd7f6-eabd-4d2d-8dae-87ea1e368de3)

Goto assignment

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/61e01b6b-9010-41c3-a400-0447b5dd473d/b56ded0b-31e6-49a4-a97e-0d6229c4a991)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4736df67-7a4b-4146-b860-10dddef9688a/d18370d8-c7c9-48f7-b14f-e1548b680a42)

Search bar should be searchable

divider colour is wrong should match the outer border (border-subtle off the top of my head)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1723](https://linear.app/calcom/issue/CAL-1723/managed-event-types-search-bar-borders)</sub>

**Comment by sanudutta45** [comment]
Can you provide me with some more info? Thank you

**Comment by varunsood2003** [comment]
Hey is this issue already solved ?
Or can I contribute to this issue

**Comment by laxmanStarx** [comment]
what was the issue, I didn't understand what the issue was describing?

**Comment by sanudutta45** [comment]
The search bar thing is still pending.

**Comment by doesnots** [comment]
Hey @PeerRich the Search bar is not merged yet, you might want to check that one again. You closed this issue.
