### ISSUE TITLE
[CAL-1726] UI: seats input focus too wide

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8994]
https://github.com/calcom/cal.com/assets/8019099/338df3d0-417f-47d5-bbc0-dc173d9a8c9b

<sub>[CAL-1726](https://linear.app/calcom/issue/CAL-1726/ui-seats-input-focus-too-wide)</sub>

**Comment by PeerRich** [comment]
please fix on component level and check other places where this is being used

**Comment by zephyrus21** [comment]
Hey @PeerRich can I take on this issue?
