### ISSUE TITLE
[CAL-1727] UI: Dark mode switch hover is wrong

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8995]
![CleanShot 2023-05-19 at 19 05 05@2x](https://github.com/calcom/cal.com/assets/8019099/afe65251-c4c9-4879-b8a8-c8a6ab15f5cb)

@Jaibles can you post the figma here?

<sub>[CAL-1727](https://linear.app/calcom/issue/CAL-1727/ui-dark-mode-switch-hover-is-wrong)</sub>

**Comment by zephyrus21** [comment]
Hey @PeerRich  I would like to work on this issue. Thanks.

**Comment by gitstart-calcom** [comment]
Hi @PeerRich @Jaibles, we were taking a look at our assigned issues, and we think the hover is still wrong, do you want that us solve it? please take a look at this short video

https://github.com/calcom/cal.com/assets/121884634/bd058ac7-e706-4581-a33e-8f262f571c8a

**Comment by ujwalkumar1995** [comment]
Hey @PeerRich 
Is this still an issue? I am unable to replicate it.


https://github.com/calcom/cal.com/assets/20976813/68b6e3ca-2906-4f58-9d15-1793a26a0793

**Comment by KSSaiTeja** [comment]
@PeerRich can i work on it.. i will fix it in one minute

**Comment by gitstart-calcom** [comment]
Hi @PeerRich This issue is not happening anymore https://www.loom.com/share/1da9bf541e9a42f1a0ee581b18d0ccc3?sid=231766de-30df-42b0-8fab-433674dd4d39
