### ISSUE TITLE
Caldav support

### ISSUE THREAD

**Issue by 3nprob** [calcom/cal.com#9]
In order to be able to integrate with existing calendar software, ability to sync to a caldav server would be covering the majority of calendar integrations (including [Google Calendar](https://developers.google.com/calendar/caldav/v2/guide) but also most on-prem solutions).

**Comment by baileypumfleet** [comment]
Thanks for your suggestion! We certainly will be looking into CalDAV support, and we've just posted It on our feature request/voting page. Check it out at: https://feedback.calendso.com/posts/9/caldav-support

**Comment by 3nprob** [comment]
![2021-04-24-125944_1042x436_scrot](https://user-images.githubusercontent.com/74199244/115946556-ff7c9280-a4fc-11eb-8b54-0cffdef614cf.png)

**Comment by ColinMaudry** [comment]
Has it been added in the end?

**Comment by ColinMaudry** [comment]
It's on the roadmap, discussions from feedback have been moved to Github discussions: https://github.com/calendso/calendso/discussions/62

**Comment by ConnorGargano** [comment]
Hi @3nprob @ColinMaudry 
Good news! The engineering team have been working hard and I can now confirm that the CalDav integration has been added to Calendso 😁

**Comment by PeerRich** [comment]
🔥 🔥 🔥

**Comment by 3nprob** [comment]
That's  great news, thanks for updating @ConnorGargano :)

**Comment by dotesfera** [comment]
Is this implemented already?

**Comment by 3nprob** [comment]
@dotesfera Yes, as per [v1.0](https://github.com/calcom/cal.com/releases/tag/v1.0) (for next time in a similar situation, you could have just searched for `caldav` in releases and commits)

**Comment by dotesfera** [comment]
Ok, sorry about that. But I was asking this because I'm experiencing strange issue when trying to connect a CalDAV, when I press OK nothing happens.
![image](https://user-images.githubusercontent.com/30806279/151985067-5c3d17ba-4c0f-437c-b762-e7473bd93152.png)

**Comment by dotesfera** [comment]
Hi @baileypumfleet I assumed you closed this issue because it was solved?

**Comment by baileypumfleet** [comment]
Yes, I closed this as we now have CalDAV support

**Comment by dotesfera** [comment]
Yes but this error I present on the issue is still there. Is it something I can fix on my side?

**Comment by dotesfera** [comment]
Hi @baileypumfleet  sorry to insist, but this is not working on my side, do you have any idea why that error happens?

**Comment by dotesfera** [comment]
Hi, still having the same error on the newest version of cal.com. any updates?

**Comment by alishaz-polymath** [comment]
Hey @dotesfera are you still facing issues connecting CalDAV?

**Comment by dotesfera** [comment]
> Hey @dotesfera are you still facing issues connecting CalDAV?

Hi! After your comment, I have updated to latest version, and now i can connect my caldav and it shows up! Thank you!

Other issues I experienced:

- Didn't received a confirmation email after schedule meeting.
- NEXT_PUBLIC_WEBAPP_URL this seems to not work, it always redirect to localhost instead of the https://example.com url I set in the env

Do you have any idea?

**Comment by cyango** [comment]
Issue is happening again in version 2.6.1. I think i'm giving up on cal.com...every new version as problem appears...

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/30806279/219873902-4252d898-3f78-45e7-af0e-d3995879c4ef.png">

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/30806279/219873935-0f77fa7d-bf71-4605-a4e4-082923d1dbf4.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/30806279/219873965-d2cd3a66-be68-41ea-9bea-13beb1cf6c6d.png">

**Comment by alishaz-polymath** [comment]
Hey @cyango 
I’m sorry to hear that. Would you please provide further details around your service provider and if you have a test account I can use to debug, that’ll be amazing. 🙏

**Comment by cyango** [comment]
I can give you access, how do I provide you the credentials?

**Comment by alishaz-polymath** [comment]
Please email to ali@cal.com
