### ISSUE TITLE
Update CONTRIBUTING.md with database and tests info

### ISSUE THREAD

**Issue by jayantamadhav** [calcom/cal.com#9001]
### Is your proposal related to a problem?

Not related to a problem, rather a request for addition of missing information related to project setup instructions in `CONTRIBUTING.md` which might help any new contributors.  
1. `Developing` section should include database setup instructions.
2. `Testing` section should include instructions on how to add new tests.  

### Describe the solution you'd like

1. Add database setup instructions
2. Add instructions on how to add new tests.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by Jagannathmaity110** [comment]
Is this issue still open?
I want to solve the issue.
