### ISSUE TITLE
[CAL-1730] Former time in wrong time zone (Rescheduling)

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9024]
### Issue Summary

When rescheduling a booking the former time is always in the organizer's time zone. It should be in the timezone the user selects on the booking page when picking a new slot. 

<img width="418" alt="Screenshot 2023-05-22 at 09 26 53" src="https://github.com/calcom/cal.com/assets/30310907/fad023cf-96b9-4168-ac5d-332099d75419">

<sub>[CAL-1730](https://linear.app/calcom/issue/CAL-1730/former-time-in-wrong-time-zone-rescheduling)</sub>

**Comment by Aashish-Upadhyay-101** [comment]
I want to work on this 🚀

**Comment by Bhavyaatrivedi** [comment]
I want to work on this

**Comment by TrustAFK** [comment]
Hello , can you please assign me this 😄

**Comment by CarinaWolli** [comment]
There is already a PR open and approved for this: https://github.com/calcom/cal.com/pull/9039
