### ISSUE TITLE
[CAL-1733] Revalidate Issue on Event-Type Page

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9032]
Whenever I make changes to my event-type, and I try to save, I get presented with this issue. Changing location, changing duration, adding confirmation, all of them. 

![CleanShot 2023-05-22 at 10.51.54@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3565fd71-f1b5-4001-a13a-9fdd47537ea8/eb3d3e71-f219-4ec3-a981-c3d79ddbb11d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1733](https://linear.app/calcom/issue/CAL-1733/revalidate-issue-on-event-type-page)</sub>

**Comment by shirazdole** [comment]
cc @Jaibles @keith this seems quite urgent as it's the event-type page

**Comment by PeerRich** [comment]
i've had this before, lemme try to reproduce

**Comment by Subhojit-Dey1234** [comment]
Can anyone help me to recreate it?

**Comment by sanudutta45** [comment]
Couldn't reproduce.
