### ISSUE TITLE
[CAL-1735] FORM_SUBMITTED webhook doesn't have formId and other details of forms

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9037]
It just has the responses. Like EventType webhooks it would make sense to provide form details as well.

Also, add the routing action taken for the submission.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1735](https://linear.app/calcom/issue/CAL-1735/form-submitted-webhook-doesnt-have-formid-and-other-details-of-forms)</sub>

**Comment by PeerRich** [comment]
@hariombalhara moved to 3.1

**Comment by PeerRich** [comment]
unless youre already working on it
