### ISSUE TITLE
[CAL-1740] Implement app theme toggle in settings appearance.

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9047]
Implement theme toggle in settings that controls our APP theme for the user and not their booking theme. -> Force lightmode even if system theme is dark. 

@Jaibles can we  have a figma design for this 

I made but we could probably do with having different images for the selectors/move booking appearance elsewhere?

 https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/2.-Cal---Live?type=design&node-id=26-60131&t=XQRa4jpyHwcLCv3S-4

<sub>[CAL-1740](https://linear.app/calcom/issue/CAL-1740/implement-app-theme-toggle-in-settings-appearance)</sub>

**Comment by Subhojit-Dey1234** [comment]
I have created the pull request for the issue.

**Comment by rkreddy99** [comment]
https://www.loom.com/share/cdc94fe097d54cd6bf2ce09dcffff403 
@Jaibles I have worked on this issue, is this what were you expecting

PS: the labelling part is not done yet, i have just implemented the feature

**Comment by Jaibles** [comment]
@rkreddy99 functionally that's it exactly. We just need to do new illustrations to have ones that reflect the app so we have some visual differentiation between changing appearance for the app vs the booking page. I'll work on them today/tomorrow.

**Comment by Jaibles** [comment]
<img width="1435" alt="CleanShot 2023-05-23 at 15 33 19@2x" src="https://github.com/calcom/cal.com/assets/4536123/2e8acd64-a1fe-457a-9fad-be4bb881958f">
These work cc @sean-brydon ?
https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/2.-Cal---Live?type=design&node-id=26%3A60253&t=p748TaivFZz0ii2W-1

**Comment by Jaibles** [comment]
https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=26%3A60119&mode=design&t=r8BbEEtmgvnfnFTK-1

**Comment by sean-brydon** [comment]
Already implemented
