### ISSUE TITLE
repeated prompts to update timezone + doesn't actually save it

### ISSUE THREAD

**Issue by Dieterbe** [calcom/cal.com#9054]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Bug 1

1. travel to cyprus
2. open cal.com
3. on the "Update Timezone?" popup, hit the 'Update Timezone' button to update to Asia/Nicosia.
4. go to another page, such as bookings or availability
5. GOTO 3

the cycle from 3 to 5 keeps repeating indefinitely. any page you open, will retrigger it.
Unless you do the below:

### Bug 2

6. Then go to settings > General.
7. Notice that timezone is set to Europe/Bucharest
8. type 'nicosia' in the search field, Asia/Nicosia appears. click on it. It's again set to Europe/Bucharest and the 'Update' button is unavailable

### Technical details

- Bug 2 reproduces in firefox developer edition and qutebrowser. bug 1 only in qutebrowser

**Comment by Dieterbe** [comment]
is it possible that nicosia and bucharest are some sort of alias,
but then still the UI behavior in general settings is weird.

**Comment by PeerRich** [comment]
we will monitor this. i havent seen this report before
