### ISSUE TITLE
[CAL-1747] [CAL-1746] The meeting ended trigger (Zapier, Webhooks, Workflows, Pipedream) does not work for event types that require payment.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9070]
![Screenshot 2023-05-23 at 11.42.56.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2df1cb74-cb3c-472c-9145-5e6681872418/8e89b665-26c6-4d79-ad2d-a2e76a128540)

Created via Threads. See full discussion: [https://threads.com/34476523757](https://threads.com/34476523757)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1746](https://linear.app/calcom/issue/CAL-1746/the-meeting-ended-trigger-zapier-webhooks-workflows-pipedream-does-not)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1746](https://linear.app/calcom/issue/CAL-1746/the-meeting-ended-trigger-zapier-webhooks-workflows-pipedream-does-not)</sub>

**Comment by PeerRich** [comment]
@CarinaWolli can you investigate this?

**Comment by CarinaWolli** [comment]
@joeauyeung will take this when he is back next week. But I already started looking in it and found that MEETING_ENDED trigger for webhooks is also not working for normal event types either (workflows work fine). I am keeping @joeauyeung updated as I will then be off most of next week
