### ISSUE TITLE
Better scale for `Deployment` table

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#9072]
### Is your proposal related to a problem?

To scale the `Deployment` table, the format should be changed. Currently there is a table with columns like logo or theme.

### Describe the solution you'd like

It would be better to fill the table according to the key value principle.

|key (primary)|value|
|---|---|
|logo|iVBO...|
|theme|dark|

**Comment by PeerRich** [comment]
cc @leog

**Comment by PeerRich** [comment]
lets move forward with the current table layout. we can refactor this later
