### ISSUE TITLE
Eventhough, After updation of Appearance Theme. Update button is still enabled

### ISSUE THREAD

**Issue by VinoV1999** [calcom/cal.com#9073]
### Issue Summary

Eventhough Appearance theme is update. The update button is still enabled and disabled when we try to select the previous theme.

https://github.com/calcom/cal.com/assets/123581387/555ea77b-2814-4e83-8318-00bb92d94aa0

### Steps to Reproduce

1. Went to Settings -> Appearance.
2. Update theme.
3. select the previous theme.

Once we updated, update button should be disable and only enables when changes occurs.

**Comment by VinoV1999** [comment]
@hariombalhara  I already fixed the issue. kindly assign the bug to me if it's approved.

**Comment by headshigh** [comment]
can you assign this to me

**Comment by VinoV1999** [comment]
Hi @headshigh, sorry to inform u that. I had the fix in my local. Kindly look for other issues :)

**Comment by headshigh** [comment]
Did you just remove !Isdirty tag from disabled disabled prop of input or were you able to refetch user theme preference once he has made changes and put it on default values?

**Comment by VinoV1999** [comment]
Yeah have reset the default values with the updated values
