### ISSUE TITLE
[CAL-1749] Adding gCal via /admin/apps fails when parsing back

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#9079]
* As an admin on a new install, enable via Google Calendar via admin UI in  `/settings/admin/apps`
* As a non-admin user, install Google Calendar
* Calendars on /apps/installed never finish loading

This is the error in the console

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cfab9569-08ab-4bfb-9959-9bdb96436e5f/ede7e017-fedf-4e7b-945f-25077d16ddcd)

The issue it that when we're saving `redirect_uris` we save it as a string when it should be an array of strings.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1749](https://linear.app/calcom/issue/CAL-1749/adding-gcal-via-adminapps-fails-when-parsing-back)</sub>

**Comment by tanmaysharma2001** [comment]
Hello @zomars, Good Day. I was trying to recreate this issue. But for some reason i am not able to see Google Calendar in the calendar options. So i dont know how to add it like you did above. Is it normal? I am attaching the screenshot.
![image](https://github.com/calcom/cal.com/assets/78191188/100b3cba-b1d1-438e-8665-41970a81d0b5)

**Comment by zomars** [comment]
@tanmaysharma2001 updated the description:

> As an admin on a new install, enable via Google Calendar via admin UI in  `/settings/admin/apps`

**Comment by bahattincinic** [comment]
I'm also facing the same issue. I've istalled it 2 times from scratch.

When I installed the Google Calendar plugin, the apps page stuck in the loading section.

Example screenshot below;

![image](https://github.com/calcom/cal.com/assets/1684999/7c296d1c-c119-42e9-842d-cdcb6cc49364)

**Comment by chriskol** [comment]
FWIW I seem to have this same issue but I suppose it's possibly because I'm using the ARM docker container and that's 7 months old?
