### ISSUE TITLE
[CAL-1752] Dark instead of transparent background on success page in embed.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9084]
It would look really bad in an inline embed.
https://www.loom.com/share/da6707443dde43efb9f536ed4a7a612f

<sub>[CAL-1752](https://linear.app/calcom/issue/CAL-1752/dark-instead-of-transparent-background-on-success-page-in-embed)</sub>

**Comment by riteshsp2000** [comment]
@hariombalhara @PeerRich I'd like to work on this one.

**Comment by hariombalhara** [comment]
Thanks @riteshsp2000 there is a PR already open and linked to it.
