### ISSUE TITLE
[CAL-1753] Embed: Update e2e tests to verify that methods like getEmbedNamespace, getEmbedTheme, isEmbed work correctly.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9086]
We can hook an assertion at some place that would ensure that while testing any flow in embed, the methods `getEmbedNamespace`, `getEmbedTheme`, `isEmbed` return the same values consistently. 

<sub>[CAL-1753](https://linear.app/calcom/issue/CAL-1753/embed-update-e2e-tests-to-verify-that-methods-like-getembednamespace)</sub>

**Comment by ologbonowiwi** [comment]
What's the expected solution for this issue, @hariombalhara?

Is creating a test that checks these three functions enough?

**Comment by hariombalhara** [comment]
@ologbonowiwi Yeah that's the idea. Tests for `isEmbed` have been added some time back. Maybe we can add these there only https://github.com/calcom/cal.com/blob/fcf3e9ee557a4855716cd5fec0ee936185ea75c9/packages/embeds/embed-core/playwright/tests/embed-pages.e2e.ts#L48

**Comment by ologbonowiwi** [comment]
I noticed, @hariombalhara, that `getEmbedTheme` always returns `auto` and `getEmbedNamespace` returns the embed param on the URL. Is that expected (and what I need to validate)

**Comment by hariombalhara** [comment]
that's not the case with `getEmbedTheme`. See https://github.com/calcom/cal.com/blob/b97c25cfc694d86eca2e026fa23b50be0dc65184/packages/embeds/embed-core/embed-iframe-init.ts#L32

Similarly `getEmbedNamespace` implementation is more nuanced.

We need to cover the all the scenarios for the functions

**Comment by ologbonowiwi** [comment]
#11318 was created to close this issue. Can you review it, @hariombalhara?
