### ISSUE TITLE
[CAL-1759] dark mode fixes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9093]
wrong icon color:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1571aaa1-a812-4fcb-beae-c7d89f278065/034c6fea-0f5f-429c-91a8-228cd00902b2)

wrong vertical divider color:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/316684dc-9489-4bf5-b0cd-293310cb8631/a8ff9f9d-9e09-44a0-a2bf-e75c78a66015)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1759](https://linear.app/calcom/issue/CAL-1759/dark-mode-fixes)</sub>

**Comment by riteshsp2000** [comment]
Hey, @PeerRich @alishaz-polymath If this is still up for grabs I'd like to raise a fix.
