### ISSUE TITLE
[CAL-1760] Embed Docs revamp

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9098]
The embed docs need revamp. They were written when Embed Code Snippet Generator didn't exist. Now that it exists, we should refer to that and explain how to use that instead.

They can just be two documents

* Embeds
  * We would still need to define various instructions that are available. Some are already document but some are missing. e.g. 'off' is missing in there.
* Using Embeds with Self Hosted

**Also, let's move all sandboxes to examples repo**

cc @alishaz-polymath

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1760](https://linear.app/calcom/issue/CAL-1760/embed-docs-revamp)</sub>

**Comment by riteshsp2000** [comment]
@hariombalhara @PeerRich I'd like to work on this.

We have to update the documentation for embeds right? Currently, the documentation for the Embeds section has 4 sub-sections and must be replaced with the above-mentioned 2 sections. 

Are there any guidelines for the documentation that I should be following for this?

**Comment by alishaz-polymath** [comment]
Hi @riteshsp2000 
@hariombalhara is takin care of this one AFAIK. Thank you for the offer, and he can confirm if that isn't the case 🙏

**Comment by hariombalhara** [comment]
Moving it to next milestone because it's not High or urgent priority.

**Comment by hariombalhara** [comment]
Docs are in review now.

**Comment by alishaz-polymath** [comment]
Docs are live 🚀
