### ISSUE TITLE
[CAL-1761] Issue installing Zoho Bigin App

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9100]
There is some issue right now in configuring the app for Bigin in Zoho Console. I will get back with an update.

Also see [https://github.com/calcom/cal.com/pull/8158#issuecomment-1561463895](https://github.com/calcom/cal.com/pull/8158#issuecomment-1561463895)

[Slack Message](https://calendso.slack.com/archives/C01NXDSRY9W/p1684943797015129?thread_ts=1684892080.130999&cid=C01NXDSRY9W)

I think we will need to publish the Zoho App that we create in Zoho Market place. But I am not aware of Zoho APIs and market place. @ShaneMaglangit Need your help with it.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1761](https://linear.app/calcom/issue/CAL-1761/issue-installing-zoho-bigin-app)</sub>

**Comment by ShaneMaglangit** [comment]
@hariombalhara hmm, seems like another instance of "works on my machine" :thinking: Atleast, locally

**Comment by hariombalhara** [comment]
Does it work for you if you use 2 different accounts of zoho, one for app creation and one for connecting to the app?

**Comment by ShaneMaglangit** [comment]
> Does it work for you if you use 2 different accounts of zoho, one for app creation and one for connecting to the app?

Yup, I still had my old setup and keys. I just created a new Bigin account and used that for another installation. Still works fine.
