### ISSUE TITLE
[CAL-1772] patch `scheduleId, bookingLimits, recurringEvent` fields

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#9118]
Hi Cal Team
It is not possible to patch `scheduleId, bookingLimits, recurringEvent` fields when patch EventType through the api. Any chance to fix it or explanation why it's restricted right now?

[Slack Message](https://calendso.slack.com/archives/C04ACKUDN30/p1678442514508419?thread_ts=1678442514.508419&cid=C04ACKUDN30)

<sub>[CAL-1225](https://linear.app/calcom/issue/CAL-1225/patch-scheduleid-bookinglimits-recurringevent-fields)</sub>

<sub>[CAL-1772](https://linear.app/calcom/issue/CAL-1772/[cal-1225]-patch-scheduleid-bookinglimits-recurringevent-fields)</sub>

**Comment by Veercodeprog** [comment]
hi,
can you explain a bit, what needs to be done ?
