### ISSUE TITLE
[CAL-1788] Impossible to create a team for another user using admin's access token

### ISSUE THREAD

**Issue by Entropius** [calcom/cal.com#9120]
Although other endpoints allow creating entities under other user's ID with the admin's access token, POST on /teams doesn't handle the `userId` parameter in the request body. 

<sub>[CAL-1788](https://linear.app/calcom/issue/CAL-1788/impossible-to-create-a-team-for-another-user-using-admins-access-token)</sub>

**Comment by keithwillcode** [comment]
@alishaz-polymath is this still valid?

**Comment by alishaz-polymath** [comment]
@keithwillcode Yeah, we don't use Admin Access Token to create teams for other users yet.

**Comment by asadath1395** [comment]
@Entropius  I think we have it implemented here https://github.com/calcom/cal.com/pull/13211 now. Mind checking this again

cc @keithwillcode
