### ISSUE TITLE
[CAL-1776] Path in swagger is wrong for deleting team

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#9124]
https://github.com/calcom/api/blob/main/pages/api/teams/%5BteamId%5D/_delete.ts#L10

The swagger path for team deletion seems wrong and needs to be updated to match the API endpoint

<sub>[CAL-1776](https://linear.app/calcom/issue/CAL-1776/path-in-swagger-is-wrong-for-deleting-team)</sub>

**Comment by emrysal** [comment]
Fixed by me in https://github.com/calcom/api/pull/250
