### ISSUE TITLE
[CAL-1778] Booking API not hooked with integrated calendars

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#9131]
Booking created/removed using the booking API doesn't add/remove event from connected calendars

<sub>[CAL-1778](https://linear.app/calcom/issue/CAL-1778/booking-api-not-hooked-with-integrated-calendars)</sub>

**Comment by emrysal** [comment]
Both create and cancel are now running the same logic as the frontend so I'm sure this is fixed 🙏
