### ISSUE TITLE
[CAL-1798] Feat: Add the ability to filter bookings by attendee emails in GET /bookings

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#9149]
It is useful for the users to filter the GET /bookings request by attendee emails.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1798](https://linear.app/calcom/issue/CAL-1798/feat-add-the-ability-to-filter-bookings-by-attendee-emails-in-get)</sub>

**Comment by AAYUSH-droid** [comment]
can i get this issue assigned?

**Comment by alishaz-polymath** [comment]
Hi @AAYUSH-droid 
It's already being taken care of in the PR mentioned above ( PR #9143 )
Thank you for offering the help though, we appreciate it! 🙏

**Comment by Jaibles** [comment]
@alishaz-polymath is this request also related to being able to do it in the UI of the app or just an API request?
