### ISSUE TITLE
toast notification is positioned at bottom left on mobile

### ISSUE THREAD

**Issue by nebulahh** [calcom/cal.com#9150]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

After updating my timezone, the toast notification is always on the bottom right even on mobile. it might look good on desktop but not so much on mobile.

### Steps to Reproduce

1. Change your computer timezone
2. Go to event types dashboard
3. Update your timezone after being prompted

the toast could always be centered on mobile and desktop or centered on mobile and positioned at the bottom right on desktop.

**Comment by Jaibles** [comment]
Toast in bottom right is fine.
<img width="483" alt="CleanShot 2023-06-19 at 15 18 39@2x" src="https://github.com/calcom/cal.com/assets/4536123/e68b7b6a-8152-4a4c-9c9f-bcfede2bb6a9">
