### ISSUE TITLE
Incorrect meeting URL in Google Cal/mail

### ISSUE THREAD

**Issue by McPizza0** [calcom/cal.com#9151]
### Issue Summary

As an attendee of an event using Cal Video;

I received two different URLs in the confirmation email.

The URL within the content was  `https://app.cal.com/video/`
But google event preview showed the domain `https://cal.video/`

Google calendar event picked out the domain from the event preview - which led to an error

![image](https://github.com/calcom/cal.com/assets/17185737/cb06852e-93d9-4e40-a86c-517f4877612b)

### Steps to Reproduce

Have group event (May be unrelated)
Using Google Mail account, register as guest
Observe email confirmation for URLs

### Technical details

Observed in Google Mail/calendar - not sure if reproducible elsewhere

**Comment by basilaslam** [comment]
I tried to recreate the issue you reported but was unable to encounter it. Can you please confirm if this issue has been resolved on your end? If not, could you provide more details or steps to reproduce the problem?

**Comment by McPizza0** [comment]
I think this issue has been resolved with other fixes - closing
