### ISSUE TITLE
[CAL-1799] prevent zoom on mobile usage

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9155]
on mobile, disable pinch to zoom

<sub>[CAL-1799](https://linear.app/calcom/issue/CAL-1799/prevent-zoom-on-mobile-usage)</sub>

**Comment by AAYUSH-droid** [comment]
Hi! can i get the issue assigned

**Comment by PeerRich** [comment]
sure @AAYUSH-droid
