### ISSUE TITLE
On the Booking questions section, "Identifier" label is not being translated into other languages.

### ISSUE THREAD

**Issue by ujwalkumar1995** [calcom/cal.com#9164]
### Issue Summary

On the Booking questions section, "Identifier" label is not being translated into other languages. 

### Steps to Reproduce

- Open any event type.
- Click on Advanced.
- Try to edit or create a new booking question
- "Identifier" label will only be displayed in English no matter your browser's language.

(You can modify your browser's default language to replicate this)

### Technical details
In the below screenshot, my browser's language has been set to German but I don't see "Identifier" being translated but the label below this field is being translated.
![Screenshot 2023-05-28 211023](https://github.com/calcom/cal.com/assets/20976813/d500097f-7b35-4d23-8710-f7bad97e800e)

**Comment by headshigh** [comment]
assign this to me
