### ISSUE TITLE
At the time of edit or rescheduling event, there is no option to add guest

### ISSUE THREAD

**Issue by HeratPatel** [calcom/cal.com#9167]
<img width="1792" alt="Screenshot 2023-05-29 at 9 41 00 AM" src="https://github.com/calcom/cal.com/assets/22561658/c5de4cb3-8544-459b-832f-baeb0c7cd7a4">

<img width="1792" alt="Screenshot 2023-05-29 at 9 51 16 AM" src="https://github.com/calcom/cal.com/assets/22561658/2c24f3f0-f834-4aa6-9ec8-45fe8d917c65">

### Is your proposal related to a problem?

No, my proposal is not related to any problem

### Describe the solution you'd like

We should add "add guest" option at the time of edit or rescheduling the event.

**Comment by jmadkins** [comment]
I thought I was missing something really obvious because this seems like such a must-have feature. I was shocked to discover it wasn't already added.

**Comment by PeerRich** [comment]
agree. odd this doenst work. adding a high priority

**Comment by jemiluv8** [comment]
> agree. odd this doenst work. adding a high priority

Editing the guests list when resheduling a booking was
intentionally not allowed. So it was not a case of an 
existing feature not working.
