### ISSUE TITLE
[CAL-1807] Date Overwrites with Timezone (for traveling in advance)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9171]
from a user:

> Hi 
> 
> love your product,
> simple but very functional 
> 
> Im currently traveling a lot, and I struggled with the override time, for example, i'll be 3 weeks in SF, when Im usually located in Israel, I didn't find the issue to choose date range and change the timezone just for this range
> 
> hopefully its something that coming close in your roadmap, cause now Im stuck!
> 
> thanks 🙌

__

I agree, it would be great to also be able to mark your timezone in overwrites, that way you can plan trips in advance where you'll be

<sub>[CAL-1807](https://linear.app/calcom/issue/CAL-1807/date-overwrites-with-timezone-for-traveling-in-advance)</sub>

**Comment by Jaibles** [comment]
We do have designs for scheduling a timezone change here:
https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/3.-Cal---New-Features?type=design&node-id=2844%3A199062&t=fwtZI0VSbiQxGBcR-1

**Comment by PeerRich** [comment]
lets do this instead: https://github.com/calcom/cal.com/issues/6790
