### ISSUE TITLE
[CAL-1812] App Store / Most Popular showing same 3 apps

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9179]
![CleanShot 2023-05-29 at 13.59.10@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/bbc1f6cd-a715-4b97-ab5f-522a13128a21/b5110db2-e039-4480-98af-12011c61d0aa)

This should show the top 3-5 apps with the most installs.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1812](https://linear.app/calcom/issue/CAL-1812/app-store-most-popular-showing-same-3-apps)</sub>

**Comment by PeerRich** [comment]
actually @zomars will quick fix this
