### ISSUE TITLE
[CAL-1813] /event-type /apps - doesn't match designs

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9180]
Spacing, padding, margins is all over the place.

![CleanShot 2023-05-29 at 14.05.02@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/31ee3fb4-6e37-4495-8e42-4fef49c0fd2a/8665eb80-5d23-4a32-9543-b000199249b1)

Check Figma

[Event type / Apps \[active\] - 2. Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/2.-Cal---Live?type=design&node-id=4876%3A157420&t=sYFxEjRy2rlPuKmG-1)

There are components we should be reusing here.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1813](https://linear.app/calcom/issue/CAL-1813/event-type-apps-doesnt-match-designs)</sub>

**Comment by adarshlilha** [comment]
i would like to contribute on this, if it's up for grabs, TIA

**Comment by Jaibles** [comment]
@adarshlilha go for it.

**Comment by Kaneki-Ken-7** [comment]
hey @Jaibles can you assign me this issue? And the figma even has grey color background for available apps. so that also needs to be fixed right?
