### ISSUE TITLE
[CAL-2512] Rescheduled & Cancelled Events double notififcation

### ISSUE THREAD

**Issue by mywebmasteruk** [calcom/cal.com#9187]
When rescheduling / cancelled an event, the default automatic notifications email still sends even when you create a custom response, the attendee and organiser both get double emails. 

using app.cal.com

<sub>[CAL-2512](https://linear.app/calcom/issue/CAL-2512/rescheduled-and-cancelled-events-double-notififcation)</sub>

**Comment by PeerRich** [comment]
you mean the email sent from the calendar provider such as Google? I don't think we can prevent that

**Comment by PeerRich** [comment]
or is a cal.com email being sent twice?
