### ISSUE TITLE
[CAL-1819] Add 'Copy link to Headless Router' button to a routing-form

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9196]
![Screenshot 2023-05-30 at 10.57.43 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3b8fcb89-1b89-45e0-b315-65860469e166/c8c87d18-83b1-47e9-8c09-c79ce86e2c61)

This can be added with similar icon as 'Copy link to form'

A headless router URL is same as redirectUrl for typeform form [https://github.com/calcom/cal.com/blob/main/packages/app-store/routing-forms/components/FormActions.tsx#L378](https://github.com/calcom/cal.com/blob/main/packages/app-store/routing-forms/components/FormActions.tsx#L378)

The goal here is to give people access to the headless router. We should also have an article on headless router

cc @PeerRich @Jaibles Should we add it besides 'Copy link to form' ?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1819](https://linear.app/calcom/issue/CAL-1819/add-copy-link-to-headless-router-button-to-a-routing-form)</sub>

**Comment by Jaibles** [comment]
This feels more like an advanced setting. Wherever we put it, we will need to offer an explanation of what it does as right now I would have no idea.

**Comment by hariombalhara** [comment]
@Jaibles It is certainly advanced. Some people might need it more frequently than others.

@saurabbot Thanks for the PR. Let's wait first, for the decision on where to show it .
