### ISSUE TITLE
Unable to remove the toast using Onclick

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#9204]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to remove the toast using Onclick.

https://github.com/calcom/cal.com/assets/81948346/c00f2d27-73b6-4649-b7de-9fcc387f57d1

**Comment by N-NeelPatel** [comment]
@anikdhabal - what is the intended functionality? should it get closed after few seconds? 
because, currently it gets closed after few second.

**Comment by PeerRich** [comment]
typically it disappears quickly. cant reproduce unfortunately

**Comment by PeerRich** [comment]
we could give it an "onClick" to hide it too if someone wants to do it

**Comment by anikdhabal** [comment]
@PeerRich Yes, I want to work.

**Comment by Vivek7038** [comment]
Just for confirmation do you want the toast to disappear when we click on toast or after some seconds

**Comment by N-NeelPatel** [comment]
can also have a cross icon upon clicking it the toast will close along with default few seconds timer to close the toast.

**Comment by PeerRich** [comment]
both. a few seconds (which should be the case already) and onClick

**Comment by PeerRich** [comment]
no cross icon needded
