### ISSUE TITLE
[CAL-1822] opt-in: confirm button in email not working

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9207]
![CleanShot 2023-05-30 at 14 55 31@2x](https://github.com/calcom/cal.com/assets/8019099/dccaa349-fc27-4c1f-9119-f5f355672463)

this button just takes me to this:

![image](https://github.com/calcom/cal.com/assets/8019099/aea580e6-cce6-4e00-98f7-eb4aa98d1422)

this used to work 

<sub>[CAL-1822](https://linear.app/calcom/issue/CAL-1822/opt-in-confirm-button-in-email-not-working)</sub>

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, we could not reproduce the issue. The button is working as expected
https://www.loom.com/share/aac3b53dd151437587e59076740f1b12

**Comment by PeerRich** [comment]
try not being logged in

**Comment by anurag0608** [comment]
Hi @PeerRich, I'm new to this project and was going through the issues list and found this one.
As you mentioned I tried booking the calender by not being loggedIn (opened a new tab in incognito tab). But I was able to book the meeting slot. The button is working as expected.

**Comment by Udit-takkar** [comment]
@anurag0608 @gitstart-calcom 

You have to enable opt in booking in event type settings.

If you log out of your account and open the confirm link from your email you are redirected to this page

![image](https://github.com/calcom/cal.com/assets/53316345/04f6d371-0db4-4ac0-b6ab-925a2fa641fd)

You can see the text "Peer still need to accept" so the booking has not been accepted when you( organiser) click on the confirm button. we want this button to work even when organizer has not logged in like it did before.

**Comment by Udit-takkar** [comment]
@gitstart-calcom no we can't simply make this route public as you can check the confirm.handler file we have to make sure the person is authorized to accept the meeting. i think we would have to pass some token as parameter in confirm link for authentication. i am looking into the code maybe someone removed it.
