### ISSUE TITLE
[CAL-1823] Delete verificationTokens after they have been used 

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9208]
There is no point keeping them in the DB after they have been successfully used

lets remove them after we have verified that they have been used. This would also prevent them from having more than one use

Thanks @hariombalhara for the suggestion 

<sub>[CAL-1823](https://linear.app/calcom/issue/CAL-1823/delete-verificationtokens-after-they-have-been-used)</sub>

**Comment by suasnomy** [comment]
I am new here and found this project interesting. I want to continue with this. Can please anyone guide me.

**Comment by sean-brydon** [comment]
Done in some places - should be flagged in PRs from here on out
