### ISSUE TITLE
[CAL-1824] 404: wrong slack icon color

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9210]
![CleanShot 2023-05-30 at 18 53 14@2x](https://github.com/calcom/cal.com/assets/8019099/492d6b12-a58b-4b59-9ee6-50ca97e80da6)

both light and dark are wrong

<sub>[CAL-1824](https://linear.app/calcom/issue/CAL-1824/404-wrong-slack-icon-color)</sub>

**Comment by G3root** [comment]
fixed by #8946
