### ISSUE TITLE
[CAL-1826] App Signup page wrong password validation

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9215]
* [Wrongly tells that one character password is acceptable by showing the hint in green](https://www.loom.com/share/1bf5c9af3e294092b2098079a9326e29)
* It looks like there is just number of characters as validation. I was able to just set 1234567 as password

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1826](https://linear.app/calcom/issue/CAL-1826/app-signup-page-wrong-password-validation)</sub>

**Comment by rvikunwar** [comment]
I would like work on this issue

**Comment by piyushgarg-dev** [comment]
Made a Pull Request

**Comment by piyushgarg-dev** [comment]
@hariombalhara Please Check Now

**Comment by abhishektiwari47** [comment]
Are you still working
