### ISSUE TITLE
[CAL-1827] Misplaced update Cancel button group

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9216]
![Screenshot 2023-05-31 at 10.45.05 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/acbeaeb3-fabe-4835-afda-dc0738fb30aa/04ced0de-584a-433b-abd4-d11cf1256cfe)

It should be aligned like this

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/abe2d2cf-e31c-4aa5-a99f-877b2940ff85/2f413213-5f6b-4dad-8a5c-0823a897beb7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1827](https://linear.app/calcom/issue/CAL-1827/misplaced-update-cancel-button-group)</sub>

**Comment by prasad5795** [comment]
@hariombalhara kindly allow me to work on this bug? I want to learn open source contributions

**Comment by AkshayBandi027** [comment]
Hey @hariombalhara, can you please provide more context on the issue,  while tried to understand but linear doesn't allow access to the issue . So please kindly give more context to the issue.
