### ISSUE TITLE
[CAL-1828] settings/admin page isn't ready but it's in production

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9217]
[https://github.com/calcom/cal.com/blob/e8f160cca5bfd33208ff8749d0731a8bedcff85e/apps/web/pages/settings/admin/index.tsx#L19](https://github.com/calcom/cal.com/blob/e8f160cca5bfd33208ff8749d0731a8bedcff85e/apps/web/pages/settings/admin/index.tsx#L19)

I thin we should redirect settings/admin to one of the tabs of admins @Jaibles @PeerRich 

![Screenshot 2023-05-31 at 11.16.42 AM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d9b269ec-b562-44fc-9415-06560d13f3bc/1660c104-9a1f-4752-b0ef-a1d43924431a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1828](https://linear.app/calcom/issue/CAL-1828/settingsadmin-page-isnt-ready-but-its-in-production)</sub>

**Comment by sohamdata** [comment]
fixed in pr #9222
