### ISSUE TITLE
[CAL-1829] I miss a duplicate event-type button on event-type page.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9223]
It's there on event-types list but not on event-type page.

cc @PeerRich @Jaibles 

![Screenshot 2023-05-31 at 2.14.33 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9d8a4a86-ee56-4df0-abf3-0239a2776391/41dc544e-66fa-4a44-8ed5-aa7ea9e407e3)

![Screenshot 2023-05-31 at 2.12.11 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1c78ec65-b2bd-408e-bf81-9d56ecef755c/d80f1dce-3ba2-4b25-9e92-deea78f2b361)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1829](https://linear.app/calcom/issue/CAL-1829/i-miss-a-duplicate-event-type-button-on-event-type-page)</sub>

**Comment by alicehack2020** [comment]
@hariombalhara  can you assign this issue to me

**Comment by sohamdata** [comment]
fixed in #9235

**Comment by Jaibles** [comment]
We can add this and I'm not saying it's of no use, but as a workflow - you probably wouldn't go into an event type to duplicate it. It's currently out on the event types page in the same way the "New" button is - You create event types from the event types page where you can duplicate existing or create new.
