### ISSUE TITLE
[CAL-1830] Why not remove Additional Notes from email? if it's empty

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9224]
See the following screenshot.

![Screenshot 2023-05-31 at 2.21.29 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/52110700-c420-406e-bb84-3b1acc714b49/4f6a51f3-83e2-44e9-8a5d-1947abc0e36d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1830](https://linear.app/calcom/issue/CAL-1830/why-not-remove-additional-notes-from-email-if-its-empty)</sub>

**Comment by piyushgarg-dev** [comment]
Can you assign it to me?

**Comment by sohamdata** [comment]
fixed in #9237

**Comment by piyushgarg-dev** [comment]
@hariombalhara @PeerRich Please check PR #9272

**Comment by PeerRich** [comment]
i like @piyushgarg-dev solution, its very short and simple

**Comment by PeerRich** [comment]
actually, they are both identical now. will merge @sohamdata because he was faster

**Comment by ujwalkumar1995** [comment]
Hey Folks,
Is this issue still open for contribution? I saw two unmerged PRs, so not sure if it is still open or not.

**Comment by hariombalhara** [comment]
Yeah @ujwalkumar1995 maybe you can work with @sohamdata and together fix it. He needs some help to fix the issue https://github.com/calcom/cal.com/pull/9237#discussion_r1228441413
