### ISSUE TITLE
[CAL-1832] Make 'We emailed you and the other attendees a calendar invitation with all the details.' text dynamic

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9239]
![Screenshot 2023-05-31 at 6.12.22 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d98ad75b-4c2d-4b6b-9734-3d2538050ed7/89e3fd6a-a86a-460d-a797-2b69c53339bb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kOThhZDc1Yi00YzJkLTRiNmItOTczNC0zZDI1MzgwNTBlZDcvODllM2ZkNmEtYTg2YS00NjBkLWE3OTctMmI2OWM1MzMzOWJiIiwiaWF0IjoxNjkwMTk0MzA0LCJleHAiOjE2OTAyODA3MDR9.7nu1SCReH7jnOBzfKGactfAzd4S8Zk8tfkJ5lkS149o)

1. If there is just booker only and no guests.
   1. "We emailed you a calendar invitation with all the details." →
2. If there is just booker and atleast one guest:
   1. "We emailed you and the other attendees a calendar invitation with all the details."

We should see all the occurrences of such texts and fix accordingly.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1832](https://linear.app/calcom/issue/CAL-1832/make-we-emailed-you-and-the-other-attendees-a-calendar-invitation-with)</sub>

**Comment by sagarsingh23** [comment]
Hi hariombalhara, I just wanted to confirm that this text change should have to be done for all the languages, right?

**Comment by Malav20** [comment]
@hariombalhara Do we need to change the message for all locales?

**Comment by hariombalhara** [comment]
We should introduce a new key and translate it only in english and delete the translation for old key everywhere. Translation would be done by crowdin later.

**Comment by Vivek7038** [comment]
> We should introduce a new key and translate it only in english and delete the translation for old key everywhere. Translation would be done by crowdin later.

hey i can fix it now  
did you mean that it should be 
"emailed_you_and_attendees": "We emailed you with all the details.",
"emailed_you_and_attendees_recurring":"We emailed you and the other attendees a calendar invitation with all the details.".

if this fixes i can fix it immediately

**Comment by Vivek7038** [comment]
give me the key and value

**Comment by hariombalhara** [comment]
@marvinhomburg I was reviewing the PR and noticed that. 'Other attendees' might refer to the host as well who is always there and he is also emailed.

cc @PeerRich Would it make sense to change it ?

**Comment by marvinhomburg** [comment]
> @marvinhomburg I was reviewing the PR and noticed that. 'Other attendees' might refer to the host as well who is always there and he is also emailed.
> 
> cc @PeerRich Would it make sense to change it ?

@hariombalhara I think the suggested solution for bookers without guests ("We emailed you a calendar invitation with all the details.") is clearer and reduces potential confusion. Since the host is always part of the appointment, the text implies that the host gets all the details.

**Comment by gitstart-calcom** [comment]
We didn't push a PR to solve it because already have an open PR here, do you want us to solve this?

**Comment by marvinhomburg** [comment]
Any news on this issue?

**Comment by hariombalhara** [comment]
@marvinhomburg We think that it's unnecessarily adding complexity in code. How about we change the text in general to

"We sent an email with a calendar invitation with the details to everyone"

**Comment by PeerRich** [comment]
easiest fix out there

**Comment by marvinhomburg** [comment]
@hariombalhara sounds almost perfect. How about
"We sent an email with a calendar invitation with the details"
