### ISSUE TITLE
[CAL-1833] Mark `eventType.price` deprecated and make sure it's not set anywhere.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9241]
The only reference of it makes sense at the place where we are reading it for backward compatibility for some of the existing event-types(that predate eventType.metadata.apps.stripe)

If it's used anywhere else, the code would be buggy.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1833](https://linear.app/calcom/issue/CAL-1833/mark-eventtypeprice-deprecated-and-make-sure-its-not-set-anywhere)</sub>

**Comment by roy9495** [comment]
Hi there are two references and they are in  cal.com/packages/app-store/_utils/getEventTypeAppData.ts and they are for backward compatibility

![Capturecal](https://github.com/calcom/cal.com/assets/98920199/13aed3be-64a8-4a8b-9407-01919c9a7b38)

**Comment by hariombalhara** [comment]
If that's the case we can close the issue.

**Comment by hariombalhara** [comment]
Thanks @roy9495 for verification.
