### ISSUE TITLE
[CAL-1836] Add google spam warning on booking confirmation page for gmail users

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9247]
Add the warning and tell users what they can do about it.

Context: [https://cal.com/blog/google-s-new-spam-policy-may-be-affecting-your-invitations](https://cal.com/blog/google-s-new-spam-policy-may-be-affecting-your-invitations)

We will only do this when we detect a gmail email address.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1836](https://linear.app/calcom/issue/CAL-1836/add-google-spam-warning-on-booking-confirmation-page-for-gmail-users)</sub>

**Comment by Jaibles** [comment]
[\[CAL-1836\] Google spam warning - 3. Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/3.-Cal---New-Features?type=design&node-id=5357%3A328352&t=thWGWKUuFf41Xmk1-1)

**Comment by PeerRich** [comment]
working on it

**Comment by PeerRich** [comment]
@gitstart-calcom 

- make sure to use the existing alert component
- make sure to show this only if attendeeEmail.contains("gmail.com")
