### ISSUE TITLE
[CAL-1992] [CAL-1842] User onboarding for post org creation for Owner

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9248]
We will re-use the existing onboarding 

[Onboarding Admin in Org - 5. Organizations (Figma)](https://www.figma.com/file/mWENDNaJPdRfZMtA75MghZ/5.-Organizations?type=design&node-id=123%3A38131&t=xDd11xtb8oANiXKj-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1842](https://linear.app/calcom/issue/CAL-1842/user-onboarding-for-post-org-creation-for-owner)</sub>

<sub>[CAL-1992](https://linear.app/calcom/issue/CAL-1992/[cal-1842]-user-onboarding-for-post-org-creation-for-owner)</sub>

**Comment by leog** [comment]
Done
