### ISSUE TITLE
[CAL-1843] Port slots.getSchedule to public APIa

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#9251]
### Is your proposal related to a problem?

Currently we don't have a way to get available slots from API. It has now be requested multiple times.

### Describe the solution you'd like

Port our tRPC logic from `slots.getSchedule` to API.

<sub>[CAL-1843](https://linear.app/calcom/issue/CAL-1843/port-slotsgetschedule-to-public-apia)</sub>

**Comment by a5r0n** [comment]
@zomars The docs should be updated as well
