### ISSUE TITLE
[CAL-1845] Update Manage Booking Questions tests to add an e2e for PhoneInput

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9261]
Why this test?. See [https://github.com/calcom/cal.com/pull/9258](https://github.com/calcom/cal.com/pull/9258)

Test can be added to this file [https://github.com/calcom/cal.com/blob/main/apps/web/playwright/manage-booking-questions.e2e.ts#L11](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/manage-booking-questions.e2e.ts#L11)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1845](https://linear.app/calcom/issue/CAL-1845/update-manage-booking-questions-tests-to-add-an-e2e-for-phoneinput)</sub>

**Comment by piyushgarg-dev** [comment]
@hariombalhara Please check PR #9265
