### ISSUE TITLE
[CAL-2187] Remember which tab you came from when clicking "Back to bookings" on booking screen

### ISSUE THREAD

**Issue by keithwillcode** [calcom/cal.com#9275]
While going through dozens of unconfirmed bookings for hiring calls, I was clicking through each unconfirmed booking to look at the details added by candidates. After reviewing the details, I was using "Back to bookings" to go back to my list of bookings. This link takes you to "Upcoming" bookings. It does not remember the tab you were on when you clicked on a booking.

### Describe the solution you'd like
It would be great to have the app remember that I was in the "Unconfirmed" tab so that when clicking "Back to bookings", I'm taken back to the same tab I was on.

### Describe alternatives you've considered

You can use the browser's back button just fine, but it's not an ideal UX in my opinion.

<sub>[CAL-2187](https://linear.app/calcom/issue/CAL-2187/remember-which-tab-you-came-from-when-clicking-back-to-bookings-on)</sub>

**Comment by piyushgarg-dev** [comment]
Please Assign it to me, I am working on it 🙌🏻.

**Comment by piyushgarg-dev** [comment]
While I am thinking on this, I guess the browser back button would be ideal because we can even support native back actions such as the user pressing the back button on mobile or slide gesture on iPhone to go back to the prev tab.

@keithwillcode What do you think about this?

**Comment by piyushgarg-dev** [comment]
@keithwillcode Please check PR #9276

**Comment by keithwillcode** [comment]
@piyushgarg-dev Great thanks a lot for putting up the PR. 🙏 When I mentioned the browser back button, I just meant that currently that's the only way to get back to the tab you were on.

**Comment by piyushgarg-dev** [comment]
@keithwillcode 
Ah Okay Okay. Got It, Sorry My bad 😄. 
Hopefully, PR https://github.com/calcom/cal.com/pull/9276 would fix this issue 🙌🏻. 
Waiting for the merge request to me merged ✨.

**Comment by keithwillcode** [comment]
@piyushgarg-dev No, no worries at all! Thanks for the PR.
