### ISSUE TITLE
[CAL-1850] Modal footer padding is off

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9280]
This needs to be fixed at a component level

![CleanShot 2023-06-01 at 22.42.56@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/49c03ce7-75e1-41b3-ae56-aca04886028e/543850e8-329e-4644-bb74-cf81e40b366b)

Refer to spec in Figma

[Modal /Documentation - 1. Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/1.-Cal-DS?type=design&node-id=29898%3A100590&t=62LvZCZAEZm5zDdw-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1850](https://linear.app/calcom/issue/CAL-1850/modal-footer-padding-is-off)</sub>

**Comment by rvikunwar** [comment]
@Jaibles didn't get what's the issue here, Could you please guide me here
