### ISSUE TITLE
[CAL-1851] Refactor of handleNewBooking along with some unit tests.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9284]
* Scope would be to just move existing nested functions inside `handler` to outside of it. 
* Also, will kickstart some unit tests to get some confidence while changing the function.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1851](https://linear.app/calcom/issue/CAL-1851/refactor-of-handlenewbooking-along-with-some-unit-tests)</sub>

**Comment by hariombalhara** [comment]
@emrysal You told me some time back that you are working on a refactor for it. I would re-start work here when that's done

**Comment by kesh-007** [comment]
Hello @PeerRich 
I'd love to work on this!
Is there anything I can do?

**Comment by hariombalhara** [comment]
@joeauyeung has kicked off refactoring which would gradually happen.
I have taken care of unit tests in the flow already.

So, we should be good to close it.
