### ISSUE TITLE
[CAL-1853] Support button doesn't open intercom

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9288]
Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=24102760-8fb7-486b-af94-7bf7a6fd4f45](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=24102760-8fb7-486b-af94-7bf7a6fd4f45)

[https://app.birdeatsbug.com/sessions/852TCOqvIx-Ku-sgfncXA6rd7U2ViPKZwN6Pg32QrVaD](https://app.birdeatsbug.com/sessions/852TCOqvIx-Ku-sgfncXA6rd7U2ViPKZwN6Pg32QrVaD)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1853](https://linear.app/calcom/issue/CAL-1853/support-button-doesnt-open-intercom)</sub>

**Comment by piyushgarg-dev** [comment]
The Production application is missing the INTERCOM_SECRET on the server side at `/api/intercom-hash` route.

![Screenshot 2023-06-02 at 6 25 37 PM](https://github.com/calcom/cal.com/assets/44976328/b128333a-ce39-4483-8c5b-03c2d4aae3db)

**Comment by Kaneki-Ken-7** [comment]
hey @piyushgarg-dev can you explain me a little like what happened here? I can see that contact support doesnt have a link to it where it should redirect to.

**Comment by PeerRich** [comment]
great catch @piyushgarg-dev  just added. no clue how this key not made its way into prod.
