### ISSUE TITLE
[CAL-1855] API: /bookings incorrect Unauthorized when server config is invalid (Daily).

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#9289]
When the Daily Video Integration throws a 403 error this is bubbled up to the API consumer as "Unauthorized" - this should become a 500 Internal error on the API side & log the Daily integration failure clearly in the console for server config resolution.

<sub>[CAL-1855](https://linear.app/calcom/issue/CAL-1855/api-bookings-endpoint-incorrect-unauthorized)</sub>

**Comment by daredevilteja** [comment]
Hi @emrysal, I would like to take this up.

**Comment by emrysal** [comment]
Should triage if this still is an issue @calcom/platform ?
