### ISSUE TITLE
[CAL-1856] chore: remove deprecated metamask and rainbow 

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9293]
weve sunset web3 stuff: [https://cal.com/blog/sunsetting-web3-app-rainbow](https://cal.com/blog/sunsetting-web3-app-rainbow)

lets remove all code related to `metamask` and `rainbow`

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/08365293-5a82-4fa3-851c-efebe469a6c0/d6355025-99e5-45cf-a920-96cca7fc21db)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c5de4a1a-e0e0-4e98-8e35-82b4ddc76f99/effd122d-938b-45c2-bbad-3f347c1f91bd)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1856](https://linear.app/calcom/issue/CAL-1856/chore-remove-deprecated-metamask-and-rainbow)</sub>

**Comment by joe-shajan** [comment]
Hey, @PeerRich I would like to work on this can you assign this to me?

**Comment by Udit-takkar** [comment]
Go ahead @joe-shajan
