### ISSUE TITLE
Convert Card component to CVA

### ISSUE THREAD

**Issue by AyushMainali123** [calcom/cal.com#9301]
### Converting cardTypeByVariant to cva

While examining the Card component, I discovered the `cardTypeByVariant` object in the `packages/ui/components/card` file. This object contains classnames that are applied to the card component. However, this component has not yet been converted to cva.

I'm interested in converting this component to cva. Please let me know if we should proceed with the conversion.

![image](https://github.com/calcom/cal.com/assets/49358949/65dd2df5-c6e9-48f1-8d64-e61bba0cf43f)

**Comment by rielAsh24** [comment]
Hey @AyushMainali123! I would be glad to work on this feature and proceed with the conversion😄

**Comment by PeerRich** [comment]
please go ahead!
