### ISSUE TITLE
[CAL-2513] Unlocked Pre and Post Buffer Times for Managed Events

### ISSUE THREAD

**Issue by wormhoudt** [calcom/cal.com#9307]
### Is your proposal related to a problem?

Our platform hosts live one on one soft skills trainings in the workplace. Our trainers are not technical and need as many things automated as possible. Managed events are perfect for this. They allow us to set all the properties that we want to be held consistent and then distribute them to our trainers. Our issue is that trainers need a widely varying amount of time in between trainings. Right now the times between events for a managed event type are locked at the admin level and cannot be set by each trainer. This either requires us to set a window that is comfortable for some but inefficient for others or set a window that is efficient for some and uncomfortable for others.

### Describe the solution you'd like

It would be very helpful for us if the managed event types allowed the individual team members to change the currently locked fields. Specifically for us that is the amount of time in between scheduled events (buffer times).

### Describe alternatives you've considered

We are currently in Beta of our scheduling feature and have implemented Calendly. Calendly supports the feature described here. However, Calendly has presented other problems for us with their embed and how it fires (or doesn't fire) events related to event reschedule and cancel that require brittle technical workarounds that we are less than comfortable with. 

### Additional context

I recognize that this feature is in progress. My hope is that this request can provide context for why a feature like this matters in a real world use case.

Thanks for your consideration.

<sub>[CAL-2513](https://linear.app/calcom/issue/CAL-2513/unlocked-pre-and-post-buffer-times-for-managed-events)</sub>

**Comment by PeerRich** [comment]
Hey @leog, after Org we can focus on this.

**Comment by leog** [comment]
Sure! Added to my plate. Managed event types v2 is coming next. @Jaibles FYI, we need designs.

**Comment by shm-dsgn** [comment]
> Sure! Added to my plate. Managed event types v2 is coming next. @Jaibles FYI, we need designs.

Can anyone contribute to designs?

**Comment by Jaibles** [comment]
> > Sure! Added to my plate. Managed event types v2 is coming next. @Jaibles FYI, we need designs.
> 
> Can anyone contribute to designs?

@shm-dsgn it's not something we have a formal process around but you can access our design system [here](https://cal.com/figma). Just duplicate it to your drafts and you should have all the components you need to design whatever you need.

The feature design around managed event types was done [here](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/4.-Orgs-%2F-Teams.---New-Features?type=design&node-id=698%3A108980&t=xlPnx8BHGlmLCT96-1) also.

**Comment by keithwillcode** [comment]
Will be implemented in https://github.com/calcom/cal.com/pull/12320
