### ISSUE TITLE
deleteMeeting error

### ISSUE THREAD

**Issue by viseshrp** [calcom/cal.com#9308]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

Error canceling a booking.

Self-hosted
Running version: v.2.9.6

### Steps to Reproduce

1. Went to an existing booking
2. Cancelled it
3. Get a 500 but booking is actually deleted though

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Booking must be cancelled without errors.

### Technical details

- Browser version - Chrome 112
- Node.js version - 18

```
calcom-docker-calcom-1  | @calcom/web:start: TypeError: _calcom_app_store__WEBPACK_IMPORTED_MODULE_4__.Z[appName] is not a function
calcom-docker-calcom-1  | @calcom/web:start:     at getVideoAdapters (/calcom/apps/web/.next/server/chunks/57541.js:96:102)
calcom-docker-calcom-1  | @calcom/web:start:     at deleteMeeting (/calcom/apps/web/.next/server/chunks/57541.js:188:37)
calcom-docker-calcom-1  | @calcom/web:start:     at /calcom/apps/web/.next/server/pages/api/cancel.js:1330:110
calcom-docker-calcom-1  | @calcom/web:start:     at Array.forEach (<anonymous>)
calcom-docker-calcom-1  | @calcom/web:start:     at handler (/calcom/apps/web/.next/server/pages/api/cancel.js:1328:99)
calcom-docker-calcom-1  | @calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/cancel.js:605:12)
calcom-docker-calcom-1  | @calcom/web:start:     at async /calcom/apps/web/.next/server/chunks/47810.js:25:28
calcom-docker-calcom-1  | @calcom/web:start:     at async /calcom/apps/web/.next/server/pages/api/cancel.js:1770:13
calcom-docker-calcom-1  | @calcom/web:start:     at async Object.apiResolver (/calcom/node_modules/next/dist/server/api-utils/node.js:372:9)
calcom-docker-calcom-1  | @calcom/web:start:     at async NextNodeServer.runApi (/calcom/node_modules/next/dist/server/next-server.js:513:9)
calcom-docker-calcom-1  | @calcom/web:start: [PERF]: getByViewer(1) took 156.2622879743576ms
```
<img width="580" alt="image" src="https://github.com/calcom/cal.com/assets/11642379/40d3bbd8-ea9d-49e9-88c9-403952f9e401">

**Comment by adarshlilha** [comment]
seems like issue with a JS piece, would like to take this up!

**Comment by sohamdata** [comment]
Hi, @viseshrp , couldn't reproduce, both from the host side and the client side.

![image](https://github.com/calcom/cal.com/assets/78294692/986372ef-db6f-4a10-ab88-7a97d478e81e)
![image](https://github.com/calcom/cal.com/assets/78294692/1f1790e3-80d2-4d9d-b867-6e5715dd0690)

**Comment by viseshrp** [comment]
@sohamdata I can reproduce on the recent 2.9.6 released two days ago. Earlier versions are fine. Which version are you on?

**Comment by il3ven** [comment]
@viseshrp Have you enabled any video app? If yes, may I know which one?

**Comment by viseshrp** [comment]
@il3ven yes, Telegram

**Comment by adarshlilha** [comment]
I can see the error reported in the issue, after setting up a meeting, reschedule and cancel options are available
@viseshrp I tried adding a facetime link but it throws 500, so I guess we would need to debug the code below:

Canceling the meeting fires an api call to `/cancel` api endpoint - `apps/web/pages/api/cancel.ts` the handler here calls `handleCancelBooking` method in `packages/features/bookings/lib/handleCancelBooking.ts`

`handleCancelBooking` calls `deleteMeeting` method where finally `getVideoAdapters` is invoked - this is where the error is thrown
I am struggling with setting up the debugger for nextjs api endpoints to debug the exact issue here
