### ISSUE TITLE
[CAL-1858] refactor: fix skeleton for side bar

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9309]
see:

[https://github.com/calcom/cal.com/assets/8019099/c8ecb3c1-291e-46cd-be18-6efb14b70159](https://github.com/calcom/cal.com/assets/8019099/c8ecb3c1-291e-46cd-be18-6efb14b70159)

issues:

* layout shift (different heights)
* skeleton has no padding left to the icon
* hover should be disabled while loading

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1858](https://linear.app/calcom/issue/CAL-1858/refactor-fix-skeleton-for-side-bar)</sub>

**Comment by PeerRich** [comment]
bonus points: give the skeleton different widths to make it more natural

**Comment by Ash9311** [comment]
i would like to work on this issue

**Comment by piyushgarg-dev** [comment]
@PeerRich Please Check PR #9310
