### ISSUE TITLE
[CAL-1862] Wrong Organizer Name shown in "Event name in calendar"

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9314]
On a collective event-type, when you select "Shiraz Dole" as the round robin for example, and you go to the "advanced tab" and look at "Event name in calendar" it doesn't always show the round robin host listed

I've reproduced this before in another event type and it says "Peer Richelsen" instead of "Shiraz Dole," this one in particular says "Bailey Pumfleet" (he was never selected nor is currently selected)

Maybe, it's pulling in Workspace Owners? 

It should instead pull in the name of whoever is listed 

**Fortunately, when the booking is actually booked, it does display the correct name:**

![CleanShot 2023-06-04 at 10.33.30@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2dd2df8e-55f4-4172-989c-fe64e5318bbf/4eef5696-762a-43b9-945a-b21429410468)

![CleanShot 2023-06-04 at 10.32.02@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dac75b70-c726-40b5-a50b-8cfd87984ccf/ff6fcc9b-6815-489a-85e9-e1a22237142a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1862](https://linear.app/calcom/issue/CAL-1862/wrong-organizer-name-shown-in-event-name-in-calendar)</sub>

**Comment by a0m0rajab** [comment]
In a quick look, this might be related to: 

https://github.com/calcom/cal.com/blob/26400403593382056d45650cee3c62abd4e4e1d8/apps/web/public/static/locales/en/common.json#L327

and 

https://github.com/calcom/cal.com/blob/26400403593382056d45650cee3c62abd4e4e1d8/apps/web/public/static/locales/en/common.json#L714

Can you share how to reproduce this?

**Comment by a0m0rajab** [comment]
Did dig a bit further and here are the related stuff: 

The event name is getting the first user, why? 
https://github.com/calcom/cal.com/blob/26400403593382056d45650cee3c62abd4e4e1d8/apps/web/components/eventtype/EventAdvancedTab.tsx#L56-L63

The code has two places for the event name in calendar: 

https://github.com/search?q=repo%3Acalcom%2Fcal.com+%22event_name_in_calendar%22&type=code 

Might be worth checking both of them and knowing which one is affected.

**Comment by PeerRich** [comment]
this still happening @shirazdole ?
