### ISSUE TITLE
[CAL-1863] Availability Name does Not Update

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9315]
![CleanShot 2023-06-04 at 10.40.10@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/82df6a55-3786-41b6-901a-21caeef2e224/0e7175e2-1a1b-4c68-8994-6f6488d4c509)

The schedule does pull properly through to the proper event-types, it just doesn't update under the "Availability" tag 

Similar how if the event type is changed from round robin to collective, the wording under "Assignment" changes to Collective

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1863](https://linear.app/calcom/issue/CAL-1863/availability-name-does-not-update)</sub>

**Comment by kanakpandit17** [comment]
Can you give steps to reproduce?

**Comment by kanakpandit17** [comment]
can you assign the issue to me?

**Comment by shirazdole** [comment]
Hi @kanakpandit17 ! For sure, here you go:
1. Navigate to the collective event
2. Click on "Availability"
3. Toggle on "common schedule" 
4. Pick a new schedule that isn't the default "Working Hours" i.e. "Enterprise"
5. The schedule under "Availability" on the left _should_ update, but it doesn't 

We can't assign, but your welcome to work on it 🙏🏽

**Comment by a0m0rajab** [comment]
@shirazdole what is a collective event? And is this related to enterprise features?
