### ISSUE TITLE
better accessibility in advanced form (UX)

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#9321]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you create a form and you go to checkbox it will have a scroll opened in the whole dialog, it would be great to have the scroll on the selected area, which would give a more intuitive UX for the user. 

![image](https://github.com/calcom/cal.com/assets/18273833/53a8cc4c-edd8-426b-a4af-55cf5176e11b)

### Steps to Reproduce

1. go to an event
2. click on advanced
3. click on add a question
4. click on checkbox 
5. you will see the issue

### Expected solution:

The user should be able to scroll while they are hovering on options, instead of hovering on the clear area in the form.

**Comment by a0m0rajab** [comment]
Just wondering why capitalization?

**Comment by HARISH-SATHISH** [comment]
> Just wondering why capitalization?

@a0m0rajab just in case if any one would help me ..

**Comment by MutiatBash** [comment]
@HARISH-SATHISH Hello do you still need help?
