### ISSUE TITLE
GitHub Actions: Disable the ESLint Report Analysis For Unchanged Files

### ISSUE THREAD

**Issue by muescha** [calcom/cal.com#9331]
### Is your proposal related to a problem?

The ESLint Report Analysis For Unchanged Files greatly expands the "Files Changed" view, even when only a few files have actually been modified.

### Describe the solution you'd like

- Disable `ESLint Report Analysis` For `Unchanged Files`

**Comment by PeerRich** [comment]
until we have those leftovers fixed we should keep it
