### ISSUE TITLE
Provide cal.com through Public Cloud Marketplaces (GCP/AWS)

### ISSUE THREAD

**Issue by daallgeier** [calcom/cal.com#9341]
### Is your proposal related to a problem?

As Independent Software Providers and Resellers we work with Google Cloud Platform, Amazon Web Services, and others to enable our customers to take advantage of applications on their respective infrastructures and through their marketplaces.  

### Describe the solution you'd like

Publish cal.com Ultimate and Platform on Cloud Marketplaces with Public and Private Pricing.  See also how GitLab is doing it: https://about.gitlab.com/partners/technology-partners/google-cloud-platform/

### Describe alternatives you've considered

Help customers deploy on GCP through terraform with the open source code (and no kickback to cal.com) 

### Additional context

https://about.gitlab.com/handbook/support/license-and-renewals/workflows/self-managed/gcp_marketplace_license.html

**Comment by PeerRich** [comment]
this is planned but not a github issue 🙏
