### ISSUE TITLE
Improving Developer Experience

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#9343]
### Is your proposal related to a problem?

The primary purpose of this issue is to improve the process we have right now in calcom and make it more friendly for new contributors. 

This is related to the last roundtable call between calcom and contributors, which we had with @PeerRich. 
 

The main issues we had: 
- Vague readme for beginners due to having multiple pieces and coverage 
- Vague database migration for new updates (reported by @rjackson 

Besides that I suggested: 
- Adding a release update Actions like the one used in [open sauced](https://github.com/open-sauced/insights/pull/1111#issuecomment-1522184607)
- Adding a welcome message for new contributors to remind maintainers to be more empathetic. [related action](https://github.com/actions/first-interaction), [Open Sauced example](https://github.com/open-sauced/hot/blob/528880f43c66831ececc99a1547e25739f4506af/.github/workflows/compliance.yml#L56-L68), [Action example](https://github.com/open-sauced/insights/pull/1204)

Furthermore we can work on the next: 
- The issue templates right now is not having any enforcement we can use the GitHub template to make it more user friendly and use the fields related to that. Instead of showing a one block of MarkDown it would be nice to show fields. This will unify names and template. and make it clearer. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
![Example fields](https://docs.github.com/assets/cb-80507/mw-1440/images/help/repository/sample-issue-form.webp)
- We can enable this templates and actions on all repos, if we used the [community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
- The tests that's running with actions right now is now showing any message on the issue, we can enable this through the action we have and write a comment for the contributors to be aware of it. We can do this by using the same [action](https://github.com/calcom/cal.com/blob/8a58a51a2cb2451d1813935fbf83b7d66e469ed7/.github/workflows/semantic-pull-requests.yml#L1-L21) and updating the message or using a [new one](https://github.com/mtfoley/pr-compliance-action) [Example usage](https://github.com/open-sauced/hot/blob/528880f43c66831ececc99a1547e25739f4506af/.github/workflows/compliance.yml#L25-L54)
Example view from [open sauced](https://github.com/open-sauced/insights/pull/1241)
![image](https://github.com/calcom/cal.com/assets/18273833/36888d98-b181-45b4-8980-345b75d58afb)

Extra information: 
The [semantic PR](https://github.com/amannn/action-semantic-pull-request) can be used with [semantic release](https://github.com/semantic-release/semantic-release), here is the release [example ](https://github.com/open-sauced/ai/blob/b7664d3e61803f2f2937a060c5d5d0eddbc3f63d/.github/workflows/release.yml#L1-L92)I shared with peer

**Comment by a0m0rajab** [comment]
Hi @Udit-takkar if Peer is okay with these suggestions, I would like to start working on it slowly.

**Comment by Udit-takkar** [comment]
@a0m0rajab okay looks fine. i'll just confirm with peer once

**Comment by PeerRich** [comment]
@keithwillcode can leave his opinion here. I think your suggestions look fine!

**Comment by keithwillcode** [comment]
@a0m0rajab Agreed. These look like great suggestions!

**Comment by a0m0rajab** [comment]
Thank you for the review, I will start working with this slowly. Here is a short list of suggestions: 

- update readme: 
  - Migration
  - first contributors 
 - Add actions
   - Welcome message 
   - Comment semantic commits errors
   - Comment release  
 - Update issue template
   -  on `.github` repo 
   - On `calcom` repo

**Comment by PeerRich** [comment]
awesome

**Comment by PeerRich** [comment]
anything more that should be done here? or can I close it @a0m0rajab

**Comment by a0m0rajab** [comment]
@PeerRich I wanted to continue with updating the readme, add the release action and the templates, I just did not have the bandwidth in the last few weeks.

**Comment by a0m0rajab** [comment]
Will open a new issue for that though.
