### ISSUE TITLE
[CAL-1868] Meeting ended trigger for webhooks and zapier not always working

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9347]
### Issue Summary

Didn't have enough time to investigate this, but I think the trigger only works if the time of when the meeting ends is not far away from when the time the meeting was initially booked. I think it is because of `node-schedule` which is used to schedule a job to trigger the webhooks.

<sub>[CAL-1868](https://linear.app/calcom/issue/CAL-1868/meeting-ended-trigger-for-webhooks-and-zapier-not-always-working)</sub>

**Comment by piyushgarg-dev** [comment]
I am not sure but I guess the `cancelScheduledJobs()` must be awaited as it returns a Promise.
https://github.com/calcom/cal.com/blob/40c5d5871e1988846c3aa95856f1847c62d4a514/packages/features/bookings/lib/handleCancelBooking.ts#L638-L643
