### ISSUE TITLE
Cross Calendar Event Blocking (sync) ala cron.com

### ISSUE THREAD

**Issue by daallgeier** [calcom/cal.com#9350]
### Is your proposal related to a problem?

I have multiple Google Workspace Accounts each within different organisations.  People within organisation usually expect to book events based on availability in Google Calendar.  To allow this today people need to either always invite all the other accounts or allow users to view calendar availability across organisations (but people also need to be remember to always check all orgs calendars in this solution). 

### Describe the solution you'd like

Enable cal.com to sync all events from one calendar to another by creating a "Private" with the type "Busy" and configurable levels of details.
1. Name is "Blocked" Only (minimal viable solution)  & no details in description
2. Name is "Blocked by [email-domain or email address or persons/calendar name] & no details in description
3. Name is original name & no details in description
4. Name is original name & details are in description (incl. meeting link) 

### Describe alternatives you've considered

Cron (by Notion) has the Minimal Viable Solution from above as a feature available. https://cron.com/changelog/2022-04-11-event-blocking

**Comment by ciaranha** [comment]
I can definitely see the benefit of this within Cal.com, but ultimately it's more a calendar problem since it's about solving scheduling problems within a workspace and not in cal.com (and there already is a calendar solution with Cron) so this won't be on the near term roadmap unfortunately. We may reopen in the future!
