### ISSUE TITLE
[CAL-1869] Make Routing Form a core component.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9351]
We are going to support creating a Routing Form for a team.

After that, it would require all team members to be able to access a Routing Form(even if the Routing Form App isn't installed by that user). 

So, it makes even more sense to move it to core now.  

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1869](https://linear.app/calcom/issue/CAL-1869/make-routing-form-a-core-component)</sub>

**Comment by PeerRich** [comment]
lets make it core, yeah. out of the app store

**Comment by hariombalhara** [comment]
Moving out of v3.1 as the focus is on high priority and urgent PRs only.
