### ISSUE TITLE
[CAL-1871] Send Download link to organiser

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#9355]
### Is your proposal related to a problem?

Currently we send emails to all the attendees with the download link if the event was recorded in cal video but not the organiser.

<sub>[CAL-1871](https://linear.app/calcom/issue/CAL-1871/send-download-link-to-organiser)</sub>

**Comment by PeerRich** [comment]
@Udit-takkar is this still open?

**Comment by Udit-takkar** [comment]
@PeerRich ahh yes i have to do this
