### ISSUE TITLE
[CAL-1877] Make E2E test: Attendee #1 Should be able to reschedule his booking

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9363]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1877](https://linear.app/calcom/issue/CAL-1877/make-e2e-test-attendee-1-should-be-able-to-reschedule-his-booking)</sub>

**Comment by rjackson** [comment]
I'll claim a few of these if that's alright, I think I've got a good idea how to build them out and they should all be very similar.

/attempt #9362

**Comment by rjackson** [comment]
The "Should reschedule booking with seats" test in `booking-seats.e2e.ts` should already cover this case, but it has problems.

I have extended the test to verify the attendee who rescheduled has a new booking created just for them – it does. But their new booking copies across the attendee email addresses from the original booking – which is a bug.

Confusingly, this does not happen when testing manually. I'm struggling to track down why we're seeing a difference in test vs live behaviour.

**Comment by emrysal** [comment]
Thanks @ologbonowiwi - yes it should
Turns out this doesn't work:
<img width="212" alt="image" src="https://github.com/calcom/cal.com/assets/1046695/38caa518-c262-4f28-8e63-ecba7363be8c">

(only the first is closed)
