### ISSUE TITLE
[CAL-1879] Make E2E test: Pending payment booking should not be confirmed by default

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9365]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1879](https://linear.app/calcom/issue/CAL-1879/make-e2e-test-pending-payment-booking-should-not-be-confirmed-by)</sub>

**Comment by zodman** [comment]
Hi here a bounty hunter... 

I saw the playwright test in the stripe integration:: `  todo("Pending payment booking should not be confirmed by default");` that's the task to implement ?

the stripe integration  test is disabled at the top of the file and the flow its not updated to the lastest version 
https://github.com/calcom/cal.com/blob/main/apps/web/playwright/integrations-stripe.e2e.ts#L34

Does it need to be integrated ?

**Comment by zodman** [comment]
stripe integration working again: https://github.com/calcom/cal.com/pull/9462

**Comment by zodman** [comment]
ping

**Comment by zodman** [comment]
/claim 9365

rock yeah my first bounty!
