### ISSUE TITLE
[CAL-1880] Make E2E test: Payment should confirm pending payment booking

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9366]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1880](https://linear.app/calcom/issue/CAL-1880/make-e2e-test-payment-should-confirm-pending-payment-booking)</sub>

**Comment by ologbonowiwi** [comment]
@zodman @adarshlilha any of you folks had success implementing this one? I'm working on #9370, but not sure about how do I confirm a pending payment.

**Comment by ologbonowiwi** [comment]
Hey @PeerRich @roae, created #10243 handling confirmation of pending paid booking, it ran on the pipeline, and the test passed. Can you take a look? 😄
