### ISSUE TITLE
[CAL-1881] Make E2E test: Payment should trigger a BOOKING_PAYMENT webhook

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9367]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1881](https://linear.app/calcom/issue/CAL-1881/make-e2e-test-payment-should-trigger-a-booking-payment-webhook)</sub>

**Comment by adarshlilha** [comment]
this is similar to the other tests
/attempt #9367

**Comment by zodman** [comment]
I think the webhook is `BOOKING_PAID`

**Comment by ologbonowiwi** [comment]
yes @vivasvan1, go for it
