### ISSUE TITLE
[CAL-1883] Make E2E test: Paid booking should be able to be canceled

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9369]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1883](https://linear.app/calcom/issue/CAL-1883/make-e2e-test-paid-booking-should-be-able-to-be-canceled)</sub>

**Comment by zodman** [comment]
Sorry guys but this needs to implement the stripe hook in the e2e its already done on my incoming PR.

**Comment by ologbonowiwi** [comment]
Hey @PeerRich @roae! I closed my first PR to this one because I wanted to give space to others to contribute, but since no one did the payment confirmation so far, I decided to move further on my implementation; can you take a look at #10243? Looks like all test cases passed already.

**Comment by ologbonowiwi** [comment]
Can we close this?

It's done already @roae @PeerRich @keithwillcode

**Comment by ologbonowiwi** [comment]
hey guys, let's close this one
