### ISSUE TITLE
[CAL-1886] Make E2E test: Can add Office CalDav Calendar

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9372]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1886](https://linear.app/calcom/issue/CAL-1886/make-e2e-test-can-add-office-caldav-calendar)</sub>

**Comment by tachyonicbytes** [comment]
Will try to tackle this together with the Google Calendar
/attempt #9372

**Comment by mahaveer0496** [comment]
If this is still up for grabs I'm happy to tackle.

**Comment by Vijaykv5** [comment]
Is this issue still up. I see an inactivity here.
If it's still up, I would love to work on it
