### ISSUE TITLE
[CAL-1887] Make E2E test: Can add Apple Calendar

### ISSUE THREAD

**Issue by roae** [calcom/cal.com#9373]
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1887](https://linear.app/calcom/issue/CAL-1887/make-e2e-test-can-add-apple-calendar)</sub>

**Comment by kanakpandit17** [comment]
Is there anyway I can get access to the threads?

**Comment by ologbonowiwi** [comment]
Hey @PeerRich! Implemented testing of the Apple Calendar authentication. Can you address someone to review it?
