### ISSUE TITLE
[CAL-1889] Layout toggle improvements

### ISSUE THREAD

**Issue by JeroenReumkens** [calcom/cal.com#9378]
* By default if no settings are set, we only want to see monthly view. This way not everyone gets the new layout without changing something themselves. 
* Disabled buttons for default layouts if that layout is not enabled
* Hide default layout selection completely when you only enable one layout.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1889](https://linear.app/calcom/issue/CAL-1889/layout-toggle-improvements)</sub>

**Comment by Jaibles** [comment]
@JeroenReumkens this is done right?

**Comment by JeroenReumkens** [comment]
Yes It's done! The Linear issue is closed, but this didn't seem to auto close too 😁 Closing it now.
