### ISSUE TITLE
[CAL-1890] Extra spacing up top when only the column view is an option

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9379]
![CleanShot 2023-06-07 at 08.39.53@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c192577e-5a29-4d19-9279-f2d8d1432a57/954cd51d-e07d-4894-ba4f-9b2094fd5d3a)

Can we tighten that up?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1890](https://linear.app/calcom/issue/CAL-1890/extra-spacing-up-top-when-only-the-column-view-is-an-option)</sub>

**Comment by kisharnath** [comment]
can i take this issue?

**Comment by Shriom-Trivedi** [comment]
Hi @Jaibles I would love to work on this

**Comment by Jaibles** [comment]
Thanks but we already have someone assigned.
