### ISSUE TITLE
[CAL-1901] Unit Test: window.isEmbed()

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9386]
Avoids this bug, https://github.com/calcom/cal.com/pull/9385

Check the manual tests done in the PR and add unit tests for those 
<img width="839" alt="Screenshot 2023-06-07 at 2 08 30 PM" src="https://github.com/calcom/cal.com/assets/1780212/1185386d-7e0d-4d0e-99e0-6aca25c04f96">

e.g. set window.name correctly and verify that isEmbed returns true

<sub>[CAL-1901](https://linear.app/calcom/issue/CAL-1901/unit-test-windowisembed)</sub>

**Comment by JaideepGuntupalli** [comment]
@roy9495 are you still working on this?

**Comment by JaideepGuntupalli** [comment]
@hariombalhara I was wondering if should i make a new file for the unit test or make one in the `booking-pages.e2e.ts`. Can you pls advise?
