### ISSUE TITLE
[CAL-1906] Slot available not showing on the booking page

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9391]
Created via Threads. See full discussion: [https://threads.com/34480096109](https://threads.com/34480096109)

There should be time available past 21:00 and yet it's not showing. 

![Screenshot 2023-06-07 at 14.19.10.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/846c64b7-63d4-42e3-9eb4-5b1b6975bf00/30eb64bd-dda1-4216-864e-a5579e59bed5)

![Screenshot 2023-06-07 at 14.19.18.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9cc76b2-8391-432a-82ea-049a163ee640/0d369d98-340e-4f14-b3a9-9a68d495df15)

![Screenshot 2023-06-07 at 14.19.34.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8ffe821d-4d5e-4a9e-9572-388e91d4faf8/920d2067-e50d-44a7-a10f-b323be3c7325)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1906](https://linear.app/calcom/issue/CAL-1906/slot-available-not-showing-on-the-booking-page)</sub>

**Comment by ashish1233** [comment]
@milospuac, I just join as a contributor,
tried to replicate it but unfortunately couln't, as its showing slot avalability in my case.

on Friday, as you can see my availability is 14:00-22:00
 
<img width="1639" alt="image" src="https://github.com/calcom/cal.com/assets/20872233/659246b8-019e-4427-b2ba-366acf2288c9">

and the slot availability is showing correcly.
<img width="1156" alt="image" src="https://github.com/calcom/cal.com/assets/20872233/d1ec3cf5-ff07-4b72-80b6-c4d9a04acc55">


it would be great if have more detail.
also i am not able to access this. https://threads.com/34480096109

**Comment by ashish1233** [comment]
@Udit-takkar, i just joined as contributor, can you please help me to replicate this?

**Comment by Udit-takkar** [comment]
@ashish1233 I am able to reproduce the bug locally. Make sure to connect your calendar and block time in it like in the 3rd image. ( make sure to turn on the toggle to prevent double booking in calendar settings)

<img width="1440" alt="Screenshot 2023-06-14 at 1 10 37 AM" src="https://github.com/calcom/cal.com/assets/53316345/3f7d40f4-5e9f-48dd-8997-9054a94d2a75">
