### ISSUE TITLE
[CAL-1909] Add dark mode for inline banner component

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9400]
[  - 1. Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/1.-Cal-DS?type=design&node-id=32791%3A97702&t=3kZdyhjHGQ69asxV-1)

![CleanShot 2023-06-07 at 15.31.15@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ed4364e4-8f9b-4c01-b02b-7f78b41691cc/ced9b7d1-b293-4cec-9cdd-284350f73b8e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1909](https://linear.app/calcom/issue/CAL-1909/add-dark-mode-for-inline-banner-component)</sub>

**Comment by Hormor** [comment]
@Jaibles  I would like to be assigned this task as there seems to be no work done on this yet.

**Comment by queen-x-vee** [comment]
Hi 🙋‍♀️, can I work on this feature pls?
