### ISSUE TITLE
[CAL-1919] Responsive design issues

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9407]
* [ ] Drop 2 two columns below 400px? 
* [ ] Center align day/date
* [ ] Empty state should also be centered

![CleanShot 2023-06-07 at 22.08.59@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cae2277a-3675-464d-ab72-15017be6315b/d4fe0a48-3a3f-41b1-a254-d5f3fc59809b)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1919](https://linear.app/calcom/issue/CAL-1919/responsive-design-issues)</sub>

**Comment by Jaibles** [comment]
@JeroenReumkens was this tackled yet? If not, feel free to remove yourself if you don’t have time!

**Comment by JeroenReumkens** [comment]
@Jaibles  See Linear. I think all issues are fixed yeah, I also closed the issue in linear, but somehow that update + the comment isn't reflected here..
