### ISSUE TITLE
Unable to setup project locally

### ISSUE THREAD

**Issue by JaideepGuntupalli** [calcom/cal.com#9410]
### Issue Summary

I wanted to contribute to the project, so I tried to set up the project locally on my m1 mbp. I followed the contributing docs carefully and step by step. I already have yarn installed, but my turbo commands are not working. I have been trying to figure this out for the past few days but couldn't.

For example, when I run `yarn dev` or `yarn dx`, i get the following message:
```
• Packages in scope: 
• Running dev in 0 packages
• Remote caching disabled

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    159ms 
```

### Steps to Reproduce

1. I have cloned the project
2. yarn installed all packages
3. then run `yarn dev` command

### Technical details

- Node.js version: v18.16.0
- Yarn version: 3.4.1
- Docker version 20.10.23, build 7155243
- MacOS Ventura 13.4 (22F66)

Pls, let me know what else you need to help me out.

**Comment by TheSmasherDev** [comment]
### Issue with setup

Hi @JaideepGuntupalli , when I tried to install the packages with yarn, I encountered the following error. Do you know how to fix it?

**Error**: @storybook/react-docgen-typescript-plugin@npm:1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0: ENAMETOOLONG: name too long

### Technical Details

- Node.js version: v20.2.0
- Yarn version: 3.6.0
- Ubuntu 20.04.6

**Comment by nitinmadelyn** [comment]
@JaideepGuntupalli the chronological order would look like this:

1. Folk the repo
2. Clone it to your computer
3. Install `yarn` if not exists, make sure you install it globally using `-g` param
4. Go to cal.com folder
5. Install dependency using `yarn` command
6. Execute `yarn dx` to setup local `postgres` database using docker. Make sure you have `Docker` & `Docker Compose`  installed or `Docker Desktop `running on your machine
7. After following all above steps you should now be able to run the app using `yarn dev`

**Comment by JaideepGuntupalli** [comment]
@TheSmasherDev I have no clue
@nitinmadelyn thanks it worked. I was running yarn dev before yarn dx. But not sure why `yarn dx` wasnt working too then. But it worked now for whatever reason now. Also add the step to update `.env` file, so if anyone else faces same issue they can refer to it.
