### ISSUE TITLE
🚨 Dashboard Stuck in Loading State

### ISSUE THREAD

**Issue by piyushgarg-dev** [calcom/cal.com#9411]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The Dashboard is stuck in the skeleton loading state. No button and contents are clickable.

### Steps to Reproduce

1. Go to `cal.com`
2. Click on Login
3. log in to your account
4. In the `https://app.cal.com/event-types` page, you'll see everything is stuck in a loading state.

### Video Recording
https://github.com/calcom/cal.com/assets/44976328/0b5133ab-19b6-4384-9e39-380c941c817f

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
- I feel that there is some issue with the intl package.

### Technical details
- Browser: Chrome on Mac
- Browser Version: Version 113.0.5672.126 (Official Build) (arm64)
- Internet Speed: 100Mbps

**Comment by sohamdata** [comment]
can't reproduce it, did you try clearing the cache and reloading (ctrl+shift+r)?

**Comment by piyushgarg-dev** [comment]
Yes @sohamdata, Even tried it on a different machine.

**Comment by piyushgarg-dev** [comment]
It's working now, not sure if I should close this issue or not.
@PeerRich
