### ISSUE TITLE
[CAL-1920] Implement upload CSV for team bulk invites

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9413]
Currently there is a button that is disabled.  This should be active and the implementation for uploading a CSV should populate the box above.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/70819d19-7fec-4f5d-9de4-6462b6d67031/ee98acbf-f421-4588-b47a-2c3730364156)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1920](https://linear.app/calcom/issue/CAL-1920/implement-upload-csv-for-team-bulk-invites)</sub>

**Comment by Meetcpatel** [comment]
Do we need to limit the file size?
