### ISSUE TITLE
need a change in documentation

### ISSUE THREAD

**Issue by zaidy2468** [calcom/cal.com#9414]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In README.md -> in Manual setup section .  Both migration command should be there one for development environment and other for production environment.  Now there is only one  **yarn workspace @calcom/prisma db-deploy.**  It should be mentioned like it i mentioned in Upgrading section.

### Steps to Reproduce

1. check the readme.md.
2. Go to Manual setup section .
3.  Step 4 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

-

**Comment by chirag1718** [comment]
Hello, I would like to update it! Do I need to be assigned or should create a pull request?

**Comment by Udit-takkar** [comment]
@chirag1718 there is already an open PR for this issue
