### ISSUE TITLE
[CAL-1923] Opt-in Reject Message

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9421]
When an opt-in meeting is "rejected" the pop-up says that it's been "canceled." It can only be canceled if it was confirmed, then canceled. 

The language needs some updating:

![CleanShot 2023-06-08 at 17.25.15@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/16625c1e-4f65-4b6f-9891-96a28c876fd9/cb3f5d82-6220-4506-a27e-d9a4a7f20557)

"This event has been rejected" "This event has been declined" are a couple of options. 

I also did not have the opportunity to put a reason. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1923](https://linear.app/calcom/issue/CAL-1923/opt-in-reject-message)</sub>

**Comment by gupta-piyush19** [comment]
I can pick this up, I want to get started with contributing to this project. @shirazdole can you please assign me this?

**Comment by Subhojit-Dey1234** [comment]
Is this still available?

**Comment by queen-x-vee** [comment]
I’ll love to work on it too.
