### ISSUE TITLE
sendEmail Error: Missing Credentials for "PLAIN"

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#9436]
### Issue Summary

By default, the command `yarn dx` creates a mailhog container. No email reaches mailhog, in the UI `http://localhost:8025`. We see an error in the logs.
[image](https://imgur.com/a/C6mJHYl)  

### Steps to Reproduce

1. Follow development setup instructions
2. An action that requires sending an email from the backend.

**Comment by keithwillcode** [comment]
See https://github.com/calcom/cal.com/pull/10018#issuecomment-1664069434 for solution
