### ISSUE TITLE
[CAL-1926] Convert NEXT_PUBLIC_TEAM_IMPERSONATION to feature flag

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#9440]
### Is your proposal related to a problem?

Team impersonation toggle existed before feature flags, but it makes sense that this is converted to a feature flag.

<sub>[CAL-1926](https://linear.app/calcom/issue/CAL-1926/convert-next-public-team-impersonation-to-feature-flag)</sub>

**Comment by tibicle-henil** [comment]
Hello, 

Can this been assigned to me

**Comment by PeerRich** [comment]
@tibicle-henil no need just raise a PR 🙏
