### ISSUE TITLE
[CAL-2514] Stripe Fees are hardcoded in the component

### ISSUE THREAD

**Issue by vsviridov** [calcom/cal.com#9447]
The settings for the fee percentage are set to 0 but Stripe component still renders "0.5% fee + $0.10  commission"
![image](https://github.com/calcom/cal.com/assets/221684/8cd7fa8d-fadc-4d43-9d51-4e89d8cbb615)

<sub>[CAL-2514](https://linear.app/calcom/issue/CAL-2514/stripe-fees-are-hardcoded-in-the-component)</sub>

**Comment by sital002** [comment]
I would like to work on this issue

**Comment by sidsaurav** [comment]
Hey @vsviridov Can you tell me in which component the settings for the fee percentage are set?

**Comment by sidsaurav** [comment]
I think we need to import the PAYMENT_FEE_FIXED and PAYMENT_FEE_PERCENTAGE value from .env and use it to set the value of "stripe_description" in all the json in "apps/web/public/static/locales/**/" folder accordingly. Not sure how to do this 😐.

**Comment by vsviridov** [comment]
`packages/app-store/stripepayment/components/EventTypeAppCardInterface.tsx` lines 50, 51

**Comment by sidsaurav** [comment]
> `packages/app-store/stripepayment/components/EventTypeAppCardInterface.tsx` lines 50, 51

Thanks a lot. I'll be working on it today.

**Comment by sidsaurav** [comment]
Can you tell me steps to reproducee this issue. Not able to figure it out myself.

**Comment by vsviridov** [comment]
You'd have to wire up Stripe connect, via env vars, it's not so straight
forward..., I'm on the road right now, will update once i get home

**Comment by vsviridov** [comment]
I think in order to be exposed to the UI, the env var must be prefixed with `NEXT_PUBLIC`, otherwise it's not getting included in the bundle for the front-end components, but I'm only 80% confident in this diagnosis.

**Comment by vsviridov** [comment]
I think that those settings might have to come from the App table via
prisma, because there's currently a mix of using that versus environment
variables. There's another stripe related ticked that goes over these
issues.
