### ISSUE TITLE
Design; Make it obvious that durations are available

### ISSUE THREAD

**Issue by McPizza0** [calcom/cal.com#9457]
When booking a call on an event that allows the user to choose a meeting duration;
It's not immediately obvious that multiple durations are available.
The "Duration" selection is in the bottom left, under details of the event
![image](https://github.com/calcom/cal.com/assets/17185737/713b5b42-a486-44e2-9d02-2258860c81d4)

### Describe the solution you'd like

I would like for the duration selection to be above the time slot selection
This gives a more natural flow of planning:
Choose Date > Choose Duration > Choose Time

It may cause some issues if: Date has availability for short duration but not long

**Comment by N-NeelPatel** [comment]
@McPizza0 - does it make sense for duration selection to be just below the Agenda of the meeting? instead of showing on the right which is dedicated specifically for the time slots.
I would love to know your thoughts.

**Comment by iamr-kumar** [comment]
@McPizza0 @N-NeelPatel Do you think instead of having it below the Agenda, it would make more sense to have it, perhaps as a dropdown, at the top right corner, between the date, and time format selection?
Let me know what you think.

**Comment by PeerRich** [comment]
we'll keep this for now
