### ISSUE TITLE
[CAL-1930] remove scrollbar for some overflowing elements

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9460]
here for example:

![CleanShot 2023-06-11 at 20 54 35@2x](https://github.com/calcom/cal.com/assets/8019099/e65d91ad-ab69-4c17-a2a3-79c9307daed6)

use className="no-scrollbar"

ideally we look out for a few more places and remove the scroll bar 

<sub>[CAL-1930](https://linear.app/calcom/issue/CAL-1930/remove-scrollbar-for-some-overflowing-elements)</sub>

**Comment by PeerRich** [comment]
for easier debugging on MacOS there is a setting:
![CleanShot 2023-06-11 at 20 56 09@2x](https://github.com/calcom/cal.com/assets/8019099/094cab8c-b6ff-4d4b-a328-37aed07ed3b1)

**Comment by joe-shajan** [comment]
I can't find the issue is this only happens in MacOs

![image](https://github.com/calcom/cal.com/assets/69904519/491c0462-911a-4c2e-b86e-4d4b5bbb6238)

**Comment by sohamdata** [comment]
@PeerRich `no-scrollbar` is already present in the VerticalTabs className, not sure why that happened.

![image](https://github.com/calcom/cal.com/assets/78294692/4e1fc748-d570-4d36-8034-2a0a206f6b7e)
