### ISSUE TITLE
tRPC "logger link" is enabled on cal.com but not app.cal.com

### ISSUE THREAD

**Issue by McPizza0** [calcom/cal.com#9461]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When booking via cal.com/profile, tRPC  "logger link" is enabled in production.
It is disabled on app.cal.com

I think it should be disabled in production for both domains.
Docs for tRPC have example: https://trpc.io/docs/client/links/loggerLink

### Steps to Reproduce

visit cal.com/USERPROFILE in production
open console
select event/date
tRPC logger link will print queries and mutations to the console.

--- Edit

Visible in Safari, not in brave/arc

This could be an issue with detecting the browser and activating based on that?

**Comment by The-Robin-Hood** [comment]
Hi @McPizza0 could you please share screenshots of this issue.

**Comment by McPizza0** [comment]
Following the reproduction steps above  produces the following:
![image](https://github.com/calcom/cal.com/assets/17185737/ef95eed8-a1dc-4f68-9295-285fb0707d2c)

**Comment by McPizza0** [comment]
Checked in multiple browsers, only visible in Safari

**Comment by PeerRich** [comment]
mustve to do something with our redirects. i think this is low?

**Comment by McPizza0** [comment]
Can no longer replicate, closing as fixed by timezone pixies
