### ISSUE TITLE
Phone Number update modal in event setup tab is not having default value defined

### ISSUE THREAD

**Issue by JaideepGuntupalli** [calcom/cal.com#9464]
### Issue Summary

The phone number update modal in the event setup tab is not having a default value defined when we click on it to edit.

### Steps to Reproduce

![cal issue](https://github.com/calcom/cal.com/assets/63718527/a9c895b6-6c51-4491-8a41-07a2368dfb09)

**Comment by JaideepGuntupalli** [comment]
> Hey, I would like to work on this issue.

I am not a maintainer, but I already have fixed it and am about to make a PR

**Comment by iamr-kumar** [comment]
Cool, thanks for letting me know
