### ISSUE TITLE
Add a page for invalid token while verifying email.

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#9469]
### Is your proposal related to a problem?
While verifying the email on signup, instead of clicking directly on the email link, if they copy the link and accidently add new characters in the token, they see token Not Found error as json response.
Visit /api/auth/verify-email?token=validToken
[Image link](https://imgur.com/a/jV3XkVU)
Refer to feature #9081 
### Describe the solution you'd like

 Instead of showing the json response to the user, we should show them a page that tells the user that the token is invalid/not found.

### Describe alternatives you've considered

Clicking on the link is always works, but some users have a habit not to click on links sent in the emails.

**Comment by iamr-kumar** [comment]
The [PR](https://github.com/calcom/cal.com/pull/9499) is ready for review. Pretty straightforward change.
