### ISSUE TITLE
[CAL-1937] Routings forms has two 'New' buttons when no forms

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9478]
### Issue Summary

Routing forms has two 'New' buttons when there are no routing forms. It should not show the button in the shell when we show the empty view.

Currently:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8f3f1fe5-ccf0-4c84-96c1-e0cf6def6a23/0dcca061-24ec-4f67-bfd7-abe78c64e3af)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1937](https://linear.app/calcom/issue/CAL-1937/routings-forms-has-two-new-buttons-when-no-forms)</sub>

**Comment by Nikeshkumar-tk** [comment]
Can i take this issue

**Comment by CarinaWolli** [comment]
@Nikeshkumar-tk Yes, you can work on it. Just link this issue when opening the PR :)

**Comment by Nikeshkumar-tk** [comment]
Ok thank U

**Comment by Nikeshkumar-tk** [comment]
[Routing form two "New" button issue](https://github.com/calcom/cal.com/pull/9479)

**Comment by Nikeshkumar-tk** [comment]
#9479

**Comment by evoxf1** [comment]
> #9479

did u worked on this
