### ISSUE TITLE
[CAL-1941] Not able to run npx playwright [test]

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#9489]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/178a285a-b9c4-41b3-812d-237c5443cb7f/a51202b4-88aa-43c0-8075-28178790a7b4)

* tried upgrading @playwright/test to 1.35.0 version

[https://github.com/calcom/cal.com/pull/9472#pullrequestreview-1477014044](https://github.com/calcom/cal.com/pull/9472#pullrequestreview-1477014044)

### Steps to Reproduce

1. run this command npx playwright test apps/web/playwright/manage-booking-questions.e2e.ts

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1941](https://linear.app/calcom/issue/CAL-1941/not-able-to-run-npx-playwright-[test])</sub>

**Comment by JaideepGuntupalli** [comment]
I was able to run the command.

Did you try running `npx playwright install` and then running the test?

**Comment by Udit-takkar** [comment]
@JaideepGuntupalli yeah i did that but still getting the same error after npx playwright test apps/web/playwright/manage-booking-questions.e2e.ts

**Comment by GourabSanyal** [comment]
command is running at my end too
