### ISSUE TITLE
Internal Server Error: 500 at app.cal.com/auth/login

### ISSUE THREAD

**Issue by piyushgarg-dev** [calcom/cal.com#9495]
### Issue Summary
I am getting an internal server error after logging in to the application at `app.cal.com/auth/login` route.

### Steps to Reproduce

1. Go to app.cal.com
2. log in to cal.com
3. You should get Internal Server Error

### Screenshot
<img width="467" alt="Screenshot 2023-06-14 at 12 32 41 AM" src="https://github.com/calcom/cal.com/assets/44976328/0d496792-1e76-419f-b7cf-efe780ba1c93">

**Comment by N-NeelPatel** [comment]
I am also getting this for a while now

**Comment by Udit-takkar** [comment]
vercel was down https://www.vercel-status.com/incidents/cqkdqrzqksp at that time
