### ISSUE TITLE
[CAL-1942] Update "Cancelled" to "Canceled" anywhere within the app

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9502]
I recently canceled an event, and the British style of "cancelled" appeared. We should adjust to American, "Canceled." One "l" 

![CleanShot 2023-06-14 at 09.55.51@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8393d673-f9b3-4741-8e45-4389bf7e0722/a821974f-16ff-401c-b28a-3affc1aee8e9)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1942](https://linear.app/calcom/issue/CAL-1942/update-cancelled-to-canceled-anywhere-within-the-app)</sub>

**Comment by Vivek7038** [comment]
hey could you check my pull request and share if there are any suggestions for me to fix

**Comment by MahendraDani** [comment]
@Vivek7038 
In the issue it is clearly mentioned that "Cancelled" should be changed to "Canceled" in entire APP.
But you changed in just one location.

P.S : You should first get the issue assigned to you before raising a P.R for it.

**Comment by Vivek7038** [comment]
Can you assign  it to me now? I can fix it for entire app .
