### ISSUE TITLE
[CAL-2182] Release feature is NOT in docker version

### ISSUE THREAD

**Issue by chief-nerd** [calcom/cal.com#9503]
### Issue Summary

I have been working on a feature in PR https://github.com/calcom/cal.com/pull/8835 with was merged into main successfully.
I was published in version [v2.9.5.1](https://github.com/calcom/cal.com/releases/tag/v2.9.5.1) according to the release notes.

However if I checkout the latest Docker Version (2.9.8)
<img width="204" alt="Screenshot 2023-06-14 at 11 09 17" src="https://github.com/calcom/cal.com/assets/9266151/cba6b8b2-e72f-4134-942c-343cb7260da8">

The feature is NOT there:
<img width="574" alt="Screenshot 2023-06-14 at 11 09 08" src="https://github.com/calcom/cal.com/assets/9266151/1f19374d-0e86-4e3b-8df4-d3969020a771">

... there are NO error messages and the feature was working correctly when merged.
This must therefore be a problem with the deployment pipeline to docker hub AFAIK.

### Steps to Reproduce

1. Check if features that are merged are also in the release and on docker hub.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Open questions:
- Which Versions are deployed to Docker Hub?
- Is there a pipeline I can check?

<sub>[CAL-2182](https://linear.app/calcom/issue/CAL-2182/release-feature-is-not-in-docker-version)</sub>

**Comment by PeerRich** [comment]
yeah it seems docker is very out of date. @krumware

**Comment by PeerRich** [comment]
will close this and instead open a ticket to keep docker automatically in sync

**Comment by scebll** [comment]
@PeerRich indeed, it seems that this is what @krumware mention.

the features are not being added to the docker images that are published in the hub, so even if you upgrade, the image does not contain that feature.

is the image published from an action here on github?

**Comment by krumware** [comment]
The action is in the calcom/docker repo. The source code in the docker images is the same that is in the repo here, via submodule. The image is being updated, and timely, and does contain the updated source code.

The additional features are added through a database seeding process. Some features, such as the Google features require the existence of env vars at the time the database seeding script is run. Some apps appear in the marketplace and some are added automagically, while some others seem to have deeper requirements. It is unclear if that is how this particular integration is added, or what other mechanism is required to make that appear in the UI.

I don't think the image update is the right thread to pull (the auto update still needs to happen).

But clarifying how to configure various plugins are made available does and verifying that the configs are being consumed by the container properly does need to be investigated.

Can you provide a de-identified copy of your env vars or .env file being passed to the docker images when it is being run? That will help me replicate.

**Comment by chief-nerd** [comment]
The thing is ... this feature was and is NOT depending on ENVs at all.
There was a previous version that was depending on ENVs but this was removed in favour of the dialog you see in the screenshot.

What is more mysterious and not fitting to the ENV / config story:
I worked on 2 PRs:  https://github.com/calcom/cal.com/pull/8636 and https://github.com/calcom/cal.com/pull/8835
... both related to Jitsi. The first established the pure host config you see in the screenshot -> this one worked. The second PR a couple of days later is the one missing. Both PRs are NOT depending on ENVs.

In any case here are my ENVs - nothing special:
```
NEXT_PUBLIC_LICENSE_CONSENT=agree
LICENSE=agree

NEXT_PUBLIC_WEBAPP_URL=https://schedule.domain.my
NEXTAUTH_SECRET="<redacted>"

CALENDSO_ENCRYPTION_KEY=<redacted>

POSTGRES_USER=<redacted>
POSTGRES_PASSWORD=<redacted>
POSTGRES_DB=calcom
DATABASE_HOST=host.docker.internal:5432
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
GOOGLE_API_CREDENTIALS=<redacted>

# Set this to '1' if you don't want Cal to collect anonymous usage
CALCOM_TELEMETRY_DISABLED=1

EMAIL_FROM=notification@domain.my

# Configure SMTP settings (@see https://nodemailer.com/smtp/).
EMAIL_FROM='Schedule@Domain.my <schedule@domain.my>'
EMAIL_SERVER_HOST=mail.domain.my
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=notification@domain.my
EMAIL_SERVER_PASSWORD=<redacted>

NODE_ENV=production
```

**Comment by chief-nerd** [comment]
@PeerRich -- I think this needs to be re-opened due to the ongoing discussion

**Comment by PeerRich** [comment]
interesting. our team will investigate. @krumware any ideas? @roae maybe too?

**Comment by krumware** [comment]
Ok I think I understand, just confirming it isn't not that the app isn't available, it's that the admin settings -> conferencing -> jitsi dropdown is missing the option to edit the configuration. Does that sound right @chief-nerd ? sorry if that's obvious

**Comment by chief-nerd** [comment]
@krumware exactly.
Each PR added a field there. Only one field is present.

**Comment by nicktrn** [comment]
@chief-nerd
Looks like this is working now. Clean install via:
```sh
git clone https://github.com/calcom/docker.git && cd docker
cp .env.example .env
sed -i "s~\(NEXTAUTH_SECRET=\).*~\1$(openssl rand -base64 32)~" .env
sed -i "s~\(CALENDSO_ENCRYPTION_KEY=\).*~\1$(openssl rand -base64 24)~" .env
docker compose up -d
```
Setup wizard:
![screenshot1](https://github.com/calcom/cal.com/assets/55853254/bfa7d752-5a2e-4f27-a9cd-c6ee502db6cc)

Admin settings:
![screenshot2](https://github.com/calcom/cal.com/assets/55853254/4c36183e-d64b-46be-8327-d11c9822761c)

**Comment by krumware** [comment]
Thanks for following up on this!

**Comment by keithwillcode** [comment]
Glad to hear it's working!

**Comment by scebll** [comment]
@keithwillcode was included in any release or is just on dev for the moment?
I was taking a look into the latest releases but didn't see anything about.

**Comment by 0x100001** [comment]
@chief-nerd was this ever included? I cant seem to find that option. I am on v5.9.3
