### ISSUE TITLE
Problem with timezones in Cal.com

### ISSUE THREAD

**Issue by buzzard10** [calcom/cal.com#9506]
Hello Guys,
as you can see below we have a lot of countries in GMT+2 timezone. Unfortunately they're not available on timezones list in Cal.com. It may be weird for customers..

![image](https://github.com/calcom/docker/assets/17282191/63ce850d-d81a-4e93-ae6c-291ac532b173)

List of countries in Cal.com:
![image](https://github.com/calcom/docker/assets/17282191/5bf8966c-37f3-4c29-a873-12587f54779e)

**Comment by vsviridov** [comment]
Same thing for American timezones. Mine's set in the database as `America/Vancouver` but shows up as `America/Dawson` in the profile page.

**Comment by emillod** [comment]
I have the same problem! :(

**Comment by PeerRich** [comment]
what exactly is the issue? that it just says the wrong name? or does it actually cause a wrong booking time?

**Comment by buzzard10** [comment]
I don't have my own country timezone. I think there may be a situation where timezone will change in my country and i'll have to adjust settings in calcom.

**Comment by shivamklr** [comment]
@buzzard10 @vsviridov Try typing the name of the city, after you open the drop down, to see if that works. 
If your city still does not show up let us know.

**Comment by Udit-takkar** [comment]
yeah so i also encountered this bug sometimes. when you click on a city say from dropdown "Berlin" you get some other city which has the same timezone.

**Comment by buzzard10** [comment]
@Udit-takkar yes, same here, and it shouldn't work that way. It should show YOUR timezone.
