### ISSUE TITLE
[CAL-1943] [UI] - Implement checkbox design

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9507]
For some reason our checkbox seems to use the default tailwind form colours

Figma : [Here](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=381-25547)

We ideally have a

* Checkbox Field component
* Single Checkbox

Please update storybook if needed

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1943](https://linear.app/calcom/issue/CAL-1943/[ui]-implement-checkbox-design)</sub>

**Comment by Nikeshkumar-tk** [comment]
Can i work on this ?.

**Comment by sean-brydon** [comment]
Go for it @Nikeshkumar-tk

**Comment by developernarendra** [comment]
Like what actually do we need to do this only one single checkbox needed there?

**Comment by sean-brydon** [comment]
To clarify what we need 

- A Checkbox Field -> Thas has the same options as the current Checkbox component we have - label description etc 
- Checkbox -> A styled checkbox that is JUST the input component with no added labels etc. That can be used when we dont need the label/description etc

**Comment by ty-kerr** [comment]
@sean-brydon @PeerRich , i was working on this while it got merged and closed and noticed the dark mode ui and figma design doesnt match. would it be possible for me to work on the dark mode ui for this component?
