### ISSUE TITLE
[CAL-1944] Round Robin event has wrong person as part of the event

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#9509]
In Round-Robin team event, if we don't select any host (both round robin host and fixed host being empty), and the person who created the event is no longer part of the team (or even [Cal.com](http://Cal.com) cloud\~ the account is removed) they still show up as part of the event.

I suspect, this is because of a clean-up issue where once they are removed from the event, they still remain as the owner of the event-type as they are the ones who created it. The UI on the other hand, shows someone else as the owner, but probably, that's not the case in the back-end as the person who doesn't exist in the team is still showing up as part of the meetings.

Steps to reproduce:

1. Create a round robin event type with Person 1.
2. Remove Person 1 from the team.
3. Make sure no Fixed Host or Round Robin host is selected.
4. Make a booking with that event type

Also reportedly,

1. Create a round robin event type with any user.
2. Add Person 1 to the team.
3. Later on, remove Person 1 from the team.
4. Make a booking with that event type

You should see Person 1 as part of the meeting.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1944](https://linear.app/calcom/issue/CAL-1944/round-robin-event-has-wrong-person-as-part-of-the-event)</sub>

**Comment by alishaz-polymath** [comment]
cc: @emrysal

**Comment by PeerRich** [comment]
also @CarinaWolli who is helping out

**Comment by emrysal** [comment]
@PeerRich @alishaz-polymath fixed by https://github.com/calcom/cal.com/pull/9722 🙏
