### ISSUE TITLE
[CAL-1945] Change Reject Behavior in Opt-in Meeting Emails

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9510]
Currently, when an opt-in meeting is submitted, if you press the "reject," button from an email, it says the meeting is canceled.

That's the wrong flow, the meeting should not be canceled because it was never booked. The correct flow should

* give the user the ability to add a reason and then reject it, just like what happens when you cancel from the bookings page.
* It will then show "This meeting has been declined"

I think the wrong action is linked

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3cd86e6d-8f13-4072-a350-41dd83a3b8b1/d3514ea7-47d3-47bd-a6fa-fc227938d095)

![CleanShot 2023-06-14 at 12.48.25@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4cf09cd9-a1a4-450d-8595-e7f297e68415/32ccb2b1-e828-4b22-ab35-aa06cbd509a5)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1945](https://linear.app/calcom/issue/CAL-1945/change-reject-behavior-in-opt-in-meeting-emails)</sub>

**Comment by Jaibles** [comment]
Doesn't need much design but just want to flesh this out properly in Figma given how core it is to the experience.

**Comment by shirazdole** [comment]
Looks like the "reject," button isn't working, the booking was still unconfirmed in the bookings tab for me and I had to reject it again: 
![CleanShot 2023-06-14 at 13 01 31@2x](https://github.com/calcom/cal.com/assets/16177678/66b63ee1-2054-42db-9792-996e451d2218)
