### ISSUE TITLE
[CAL-1946] improvement: when changing email after using Google Sign in, show dialog and change ID provider to email + pw

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9515]
when i make an account with Google Workspace: "[peer@cal.com](mailto:peer@cal.com)" and then change this:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fe0018e6-a764-4ffc-9f46-759a30e3ea04/a7d74592-9750-4eff-9f8c-6c52988a148e)

it should show a dialog like canva:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/37ad64a2-1bf7-4973-9060-09d887d4c9eb/6498a4f9-c78a-4ef9-a05c-8bd864b6c78f)

and afterwards change my identity provider to "CAL" from "GOOGLE" and delete the ID Token from google.

changing email does still require an email verification

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1946](https://linear.app/calcom/issue/CAL-1946/improvement-when-changing-email-after-using-google-sign-in-show-dialog)</sub>

**Comment by JaideepGuntupalli** [comment]
Hey i want to work on this.

So, basically when we login with google and change the email, it should change the identity provider and all the other stuff you mentioned? @PeerRich

**Comment by PeerRich** [comment]
@alannnc it seems like gitstart is working on this already

**Comment by PeerRich** [comment]
> Hey i want to work on this.
> 
> So, basically when we login with google and change the email to any email, it should change the identity provider and all the other stuff you mentioned? @PeerRich

hey @JaideepGuntupalli correct.

when going from Google => change email it should change id provider and send a password reset link

**Comment by gitstart-calcom** [comment]
Hi @PeerRich We didn't push a PR to solve it because already have an open PR here, do you want us to solve this?
