### ISSUE TITLE
[CAL-1947] Booking a recurring event type is slow

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#9517]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The availability loading is fast but It sometime takes \~10seconds or more to book the meeting. I have tried both on production and locally.

### Steps to Reproduce

1. Create a recurring event type
2. Make a booking

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1947](https://linear.app/calcom/issue/CAL-1947/booking-a-recurring-event-type-is-slow)</sub>

**Comment by JaideepGuntupalli** [comment]
Can I work on this?

**Comment by JaideepGuntupalli** [comment]
hey @Udit-takkar just to confirm we are on same page. You mean when we press confirm booking right?

**Comment by Udit-takkar** [comment]
@JaideepGuntupalli  yes
