### ISSUE TITLE
Stripe Payments padding -- Request to remove component padding to inherit from parent. 

### ISSUE THREAD

**Issue by devarcher** [calcom/cal.com#9525]
### Is your proposal related to a problem?

I really like how the calendar embed works with my parent component styling.  The Stripe Payments component has padding added that changes the continuity of design from the calendar to payment, especially on mobile. 

### Describe the solution you'd like

It would be great to remove padding from the component so it keeps the look of the calendar from the previous pages. 

This line has padding: 
```
<div class="flex min-h-screen items-end justify-center px-4 pt-4 pb-20 text-center sm:block sm:p-0">
```

Removing padding keeps look from previous pages as the calendar inherits padding from parent.
```
<div class="flex min-h-screen items-end justify-center text-center sm:block">
```

### Describe alternatives you've considered
Living with the padding isn't the worst, but it would be nice to keep the calendar and payment page padding behavior consistent.

**Comment by PeerRich** [comment]
do you have a screenshot of before and after?
