### ISSUE TITLE
Add duplicate button to availability

### ISSUE THREAD

**Issue by a0m0rajab** [calcom/cal.com#9528]
### Is your proposal related to a problem?

The availability page right now has only delete option, it would be great to have duplicate one as well. 
![image](https://github.com/calcom/cal.com/assets/18273833/fb2b39e5-a10f-455a-a86b-5dff3ac2d8aa)

https://app.cal.com/availability

This will be helpful to create a schedule with minor changes. 

### Describe the solution you'd like
add option to duplicate. 

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by iamr-kumar** [comment]
Could anyone help me out with this?

**Comment by N-NeelPatel** [comment]
@iamr-kumar - looks good, what help do you need?

**Comment by iamr-kumar** [comment]
@N-NeelPatel so there are couple of ways the duplication can be handled. The one implemented here is the most basic one. One way could be to mimic how event types are duplicated, where upon clicking the menu button, a modal appears with the selected event's configurations for edit. In short, edit happens before actual entry is created in the DB.

What this PR does is creates a duplicate schedule in the db first and then allows for editing.

The former would require a bit more effort and probably even designs. If the current version fulfils the needs just fine, then I would be happy to finalise this PR, after some clean ups, of course.
