### ISSUE TITLE
[CAL-1950] Can't log in after entering 2FA

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9533]
Created via Threads. See full discussion: [https://threads.com/34481844369](https://threads.com/34481844369)

I think these are accounts managed by Google and SAML.

![Screenshot 2023-06-15 at 11.31.01.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/16909031-94a7-4335-b39f-76db4a965ed3/1f7507cb-8ce5-46f4-a64d-88f1c2beb203)

![Screenshot 2023-06-15 at 11.04.35.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/905319b5-55c8-4447-96d2-9ad188715b8b/83aa59d8-6204-4950-bc74-437b1b09004c)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1950](https://linear.app/calcom/issue/CAL-1950/cant-log-in-after-entering-2fa)</sub>

**Comment by mishushakov** [comment]
Having the same issue (as a user) here. Very critical

**Comment by PeerRich** [comment]
we're still looking into it!

**Comment by zomars** [comment]
@PeerRich @baileypumfleet  @keithwillcode @emrysal  Should GOOGLE and SAML accounts have 2FA enabled at all? Should we cleanup the DB? Should we implemented 2FA for those accounts?

**Comment by PeerRich** [comment]
i dont think they should

**Comment by PeerRich** [comment]
whats easier? blocking SAML and Google from adding 2FA or enabling 2FA for both? @zomars

**Comment by mgmorcos** [comment]
I have this issue as an email/password user (not SAML).

**Comment by frayos** [comment]
Same issue,
Email / Password.

A) I'm able to setup 2FA and validate the 6 digits.
B) I'm also able to Disable and validate 6 digits during disablement
C) Yet between A and B if I try to login I get a 401 on credentials endpoint

**Comment by sean-brydon** [comment]
Also encountered this on my own personal account.  [https://threads.com/thread/34560685620?s=sPCxVLFSzcjgoRJQU9Cui9](https://threads.com/thread/34560685620?s=sPCxVLFSzcjgoRJQU9Cui9)
