### ISSUE TITLE
[CAL-1951] No spacing b/w Filter and Event-Types list in smaller view

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9534]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ed456d1f-89e4-4aea-a06a-0b7213f8a467/8f33732e-787e-4ddd-9c45-3830ae751dd9)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1951](https://linear.app/calcom/issue/CAL-1951/no-spacing-bw-filter-and-event-types-list-in-tablet-view)</sub>

Also there is an unnecessary divider(which is only needed in bigger view)

**Comment by varunsood2003** [comment]
Hey I would like to work on this could you please assign me

**Comment by varunsood2003** [comment]
Where to find this issue could you specify

**Comment by hariombalhara** [comment]
You would see it when you go to localhost:3000/event-types and choose a lower viewport size in Emulation

**Comment by varunsood2003** [comment]
I'm having problem to run the project locally, specifically with the database and docker. Could you suggest how can I do it.
