### ISSUE TITLE
[CAL-1954] When refreshing on app.cal.local:3000 after logging in as an organisation admin, I see Nameless during loading

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9537]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ba65b32d-ac80-406a-af53-680a34788406/924ea7e3-8d53-4f46-ae0f-33f1f4750f0f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1954](https://linear.app/calcom/issue/CAL-1954/when-refreshing-on-appcallocal3000-after-logging-in-as-an-organisation)</sub>

**Comment by PeerRich** [comment]
lets finally get rid of nameless and instead not render this thing. or just call it t("more")

**Comment by hariombalhara** [comment]
This is already fixed
