### ISSUE TITLE
[CAL-1955] Possible conditional hook usage issue

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9539]
Error while testing the user onboarding locally. Can be replicated by creating a new user.

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9138f5f3-c5e2-4608-9b0d-240ac9c74fb1/202bc277-608f-4b6e-af3e-78f746c14483)

We should make that usage unconditional.
cc @sean-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon-brydon

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1955](https://linear.app/calcom/issue/CAL-1955/possible-conditional-hook-usage-issue)</sub>

**Comment by xmayukx** [comment]
Hey @hariombalhara could you please assign it to me? I would like to work on this issue.

**Comment by kemilbeltre** [comment]
I would like to check this issue as well
