### ISSUE TITLE
[CAL-1957] Owner of the organization can't see the teams he created during onboarding) on /teams page. 

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9542]
* Noticed that the owner of the organization can't see the teams he created(during onboarding) on /teams page. Happening because, we aren't creating the membership of that user with the teams. I think we need to fix it, so that he can add members to the teams later on.
* Also, I don't see any invite sent to the user I added during onboarding

\*Originally posted by @hariombalhara in \*[*https://github.com/calcom/cal.com/issues/9231#issuecomment-1593046893*](https://github.com/calcom/cal.com/issues/9231#issuecomment-1593046893)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1957](https://linear.app/calcom/issue/CAL-1957/owner-of-the-organization-cant-see-the-teams-he-created-during)</sub>

**Comment by leog** [comment]
@hariombalhara thanks for cc-ing @sean-brydon as I will need his help with invitations part, fixing the membership issue, good catch!
