### ISSUE TITLE
[CAL-1958] New translation needed for dutch "Forgotten password" button

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#9547]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/592cc364-4943-4b83-9107-58dbd0a2dc49/bbdf4061-911d-47fb-9ecc-56e486e840f1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1958](https://linear.app/calcom/issue/CAL-1958/new-translation-needed-for-dutch-forgotten-password-button)</sub>

**Comment by saaagarsingh** [comment]
hey I would like to work just need some more insight to understand the issue better.

**Comment by JaideepGuntupalli** [comment]
"Verstuur wachtwoord herstel e-mail" is this a better translation? @emrysal

PS: I am not Dutch or know how to speak dutch, but based on Googling and chatgpt that was my suggestion.
