### ISSUE TITLE
[CAL-1959] Remove duplicate value warnings on starting dev server.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9553]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8fc6d228-ffde-469c-bc80-735ef7bbcf58/4a40a884-bc42-457b-a387-9363333fb2c2)

These warnings can be removed by removing the keys that have the same value.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1959](https://linear.app/calcom/issue/CAL-1959/remove-duplicate-value-warnings-on-starting-dev-server)</sub>

**Comment by sagarsingh23** [comment]
Hi hariombalhara, i am picking this issue.
I have one doubt do we have to remove the key which have the same value or just change the value of it also if we have to remove so should i make change for all the languages  common.json file.

**Comment by sagarsingh23** [comment]
I have created a pull request for this fix. can you please check.
[https://github.com/calcom/cal.com/pull/9555](url)
