### ISSUE TITLE
[CAL-1960] Sidebar UI discrepancies with design

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9559]
* [ ] [Refer to spec in Figma.](https://www.figma.com/file/mWENDNaJPdRfZMtA75MghZ/Organizations?type=design&node-id=2417%3A96765&t=2RZfrIANLqRmn1nu-1) Main issue is the avatar in the top not lining up with the icons.

![CleanShot 2023-06-16 at 10.21.42@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/15663d69-5947-490d-84c8-c2fe727fe997/034f7aab-5a37-4384-acbb-5f53cd241d30)

* [ ] Are there any javascript libraries that can do a better truncation than CSS? There's loads of space left here for more letter.

  ![CleanShot 2023-06-16 at 10.15.36@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5ca7b12e-649d-42c3-ad44-9aaa231166e3/ac2b7850-29be-4e07-af71-ee5e4add26e9)

  Make sure to get a review from @jaibles before merging.

Side by side view of issues

![CleanShot 2023-06-16 at 10.24.38@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/68225878-3915-44a1-9150-561cd6f58d3b/201b7ed4-39bc-47a2-b30d-003110d890d0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1960](https://linear.app/calcom/issue/CAL-1960/sidebar-ui-discrepancies-with-design)</sub>

**Comment by VinoV1999** [comment]
Before:-
<img width="1262" alt="Screenshot 2023-06-18 at 9 24 49 AM" src="https://github.com/calcom/cal.com/assets/123581387/35eecc8e-4b2a-4c01-8d1c-ff96bee4009a">


After:-
<img width="1262" alt="Screenshot 2023-06-18 at 9 25 13 AM" src="https://github.com/calcom/cal.com/assets/123581387/26a5823c-7fa0-4dd3-81a2-bfe31510e6a3">


it seems like an margin issue. @Jaibles is this fine shall make a pr
