### ISSUE TITLE
[CAL-1966] Top banner for verifying email doesn't match designs

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9565]
Should be

![CleanShot 2023-06-16 at 12.26.29@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/696c4429-feb1-40db-a96e-016081ad07f2/0bcff37c-4d50-436e-8a87-6c5d38e41250)

Currently

![CleanShot 2023-06-16 at 12.25.10@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1c64e663-9bd4-4ed6-8e61-7c2468102e5f/4ac1f155-dd7a-410b-aaf4-85e1bad15944)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1966](https://linear.app/calcom/issue/CAL-1966/top-banner-for-verifying-email-doesnt-match-designs)</sub>

**Comment by niteshseram** [comment]
Hi @Jaibles Can i work on this?

**Comment by tanbirali** [comment]
Hello, I want to work on this issue. Can you please assign this to me.

**Comment by mHasnaat-Iftikhar** [comment]
Hi,
I can easily fix that issue. Can I start working on that?
