### ISSUE TITLE
[CAL-1967] When a button with data-cal-link="" prop contains child elements - popup doesn't work

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9567]
![Screenshot 2023-06-16 at 14.27.42.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/49ec8c81-7a63-424c-8fca-3292a4b48e24/be1a775c-82f2-4468-a287-4500742bcb08)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1967](https://linear.app/calcom/issue/CAL-1967/when-a-button-with-data-cal-link=-prop-contains-child-elements-popup)</sub>

**Comment by santiagorodriguezbermudez** [comment]
Hey there team and @milospuac,

I've been encountering the same issue outlined in [CAL-1967] and have been exploring workarounds, including adding the data-cal-link attribute to every child element of the parent. However, this approach seems to be quite cumbersome and not very practical.

I'm reaching out to inquire if there's any plan to address this issue in the future. It would be really helpful to know if a fix is being considered, as this functionality is quite important for the project I'm working on. Any updates or alternative suggestions would be greatly appreciated!

Thanks for your time and assistance.

**Comment by niteshsrivats** [comment]
@santiagorodriguezbermudez setting `pointer-events: none;` on the children seems to fix it.
