### ISSUE TITLE
[CAL-1968] Weekly/Col/Monthly default setting not working

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9571]
Set to weekly

![CleanShot 2023-06-16 at 14.39.01@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/cfc7b0e7-bea6-441b-b1a4-4e651188db1e/e6db7cb1-d77d-4ae3-97ed-950d34351aad)

Still showing monthly

![CleanShot 2023-06-16 at 14.38.57@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/61a09bb4-8d59-410e-9ae6-75abbcad0fad/6cadeae8-e9ec-42aa-9002-582d481baab0)

View [https://cal.com/ciaran/design](https://cal.com/ciaran/design?duration=30)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1968](https://linear.app/calcom/issue/CAL-1968/weeklycolmonthly-default-setting-not-working)</sub>

**Comment by emrysal** [comment]
Fixed in https://github.com/calcom/cal.com/pull/9570
