### ISSUE TITLE
🚨 Redirect after booking is not working.

### ISSUE THREAD

**Issue by bmottershead** [calcom/cal.com#9585]
Redirect after booking stopped working.   To reproduce, try booking on https://cal.com/bmotters/system-review   This is a test event-type, which is set up to redirect.

**Comment by emrysal** [comment]
Thanks for reporting this @bmottershead

**Comment by Meetcpatel** [comment]
Hi @bmottershead!

I tried to reproduce this way, it seems the redirect is working. Or I missed something?

https://www.loom.com/share/4e67e66b024441b4b586f5897d44da22?sid=143411d2-a8b5-4f1d-a192-22a6ce18dfd9

**Comment by bmottershead** [comment]
@Meetcpatel, your video shows setting up the redirect to be https://google.com .  I don't have any problem with setting up the redirect.  Where I have a problem is when I book the event type, it doesn't redirect.    

If you are saying then when you booked the event type in your video, it redirected to google.com just fine, then that is different from the behaviour I observe.   It would mean that it works for some event types or redirect URL's (such as google.com) and not others.    

Did you  try with the test event I gave up above?   That is set up to redirect after booking to https://dev.riverscape.info/booking/calcom/success2.html  . This isn't google.com, but it is a valid URL.    The event type I gave had been redirecting just fine for a couple of weeks before yesterday.

**Comment by PeerRich** [comment]
fixed. deploying now!

**Comment by bmottershead** [comment]
Impressive response.  You folks are good.  Thank-you.

**Comment by PeerRich** [comment]
fixed
