### ISSUE TITLE
🚨 Booking form buttons not visible in safari

### ISSUE THREAD

**Issue by McPizza0** [calcom/cal.com#9586]
### Issue Summary

When on the an event public booking form in Safari
The Back and Confirm buttons are not visible
They are rendered for a few milliseconds, but then are pushed way off screen
![image](https://github.com/calcom/cal.com/assets/17185737/a9d19312-ca87-4da3-9e47-407a9c4de842)
![image](https://github.com/calcom/cal.com/assets/17185737/dde3ae50-eda6-485c-ad20-3015a6770bbe)

Works fine in Chromium browsers

### Steps to Reproduce

1. Use safari and navigate to an event page
2. Select a timeslot and wait for form to render
3. Check css for buttons

--
This only happens on the default booking view, not the new cool views

### Technical details
 Safari Version 16.5 (18615.2.9.11.4)

**Comment by McPizza0** [comment]
Issue is resolved when removing the `mt-auto` on the button parent div.
The `mt-auto` might be needed by other new views and thus should not just be removed.

**Comment by emrysal** [comment]
Yeah this goes way further than the mt-auto, assigning @JeroenReumkens to have a look - thank you!

**Comment by JeroenReumkens** [comment]
Looking at it right now!

**Comment by McPizza0** [comment]
`Insert meme: "Its not much but its honest work"`
