### ISSUE TITLE
[CAL-1977] Improper spacing for Recurring Event in new booker

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9591]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2717ae53-f79f-48a0-ae4f-e8168ac6d20d/1bf74184-ba0f-4b20-aff2-44911bcd78e3)

Input seems to be extra wide.
Also there seems to be some extra space below the input

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1977](https://linear.app/calcom/issue/CAL-1977/improper-spacing-for-recurring-event-in-new-booker)</sub>

**Comment by KaranKaira** [comment]
@hariombalhara  pls assign this to me

**Comment by kemilbeltre** [comment]
@hariombalhara  how can I reproduce this? I tried to access the same URL (http://localhost:3000/new-booker/teampro/recurring) and got a 404 error.

**Comment by kemilbeltre** [comment]
Hi, @hariombalhara please review this PR. Thanks

**Comment by nitish799** [comment]
@hariombalhara  is it still open ?

**Comment by uday7981** [comment]
Can you explain more about the issue please

**Comment by hariombalhara** [comment]
Closing this for now
