### ISSUE TITLE
[CAL-1979] column view: only show available times

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9593]
for example: I have a weekly recurring office hours: [https://cal.com/peer/office-hours?date=2023-06-22](https://cal.com/peer/office-hours?date=2023-06-22) and I wanna show all fridays (its only on fridays)

right now in column view we show unavailable days:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b5301acd-1b59-44e5-9f68-686ce7282bfd/5ac29581-2f5a-4f0f-bb7b-59d8c96e7e18)

[https://github.com/calcom/cal.com/assets/8019099/20fab7d3-8fe9-4775-80f8-cf43dba56d0b](https://github.com/calcom/cal.com/assets/8019099/20fab7d3-8fe9-4775-80f8-cf43dba56d0b)

instead, we should show only days with availability:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/28fdfb56-e067-4496-9440-dbb98c21eadb/bfd5c5db-d5df-43dc-8122-1e7228ab5970)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1979](https://linear.app/calcom/issue/CAL-1979/column-view-only-show-available-times)</sub>

**Comment by PeerRich** [comment]
we will need to spend a bit more time on this, but ideally we will do this

**Comment by VinoV1999** [comment]
https://github.com/calcom/cal.com/assets/123581387/84663dda-f288-40a2-bcf5-0720f58a1f43


I think it's was better to keep only month and year in heading. Bcz the right and left and right arrow forward and backwards a week. Result, slots remains same unless we cross over a month. Let's forward and back a month instead.

@PeerRich  WDYT

**Comment by PeerRich** [comment]
yeah thats what i am afraid of, the week switch makes little sense. maybe it shows the range and then goes + 5 and - 5?

**Comment by Jaibles** [comment]
I think there's enough context provided here now?

![CleanShot 2023-06-20 at 13 21 25@2x](https://github.com/calcom/cal.com/assets/4536123/e8685833-45a5-43e5-8964-2a8b8845c2ba)

And it's more context than we're currently offering as we don't communicate the change of month.

<img width="1255" alt="CleanShot 2023-06-20 at 13 25 45@2x" src="https://github.com/calcom/cal.com/assets/4536123/754913db-9185-4daa-b259-5a4059e66d1f">

**Comment by VinoV1999** [comment]
https://github.com/calcom/cal.com/assets/123581387/aeb3a978-9de3-498b-8ca4-9c0b6e1e7ff3



Hi have done something, that will show 6 available continuous slots. and jumps to forward and back to the next 6 slots. That is available. Hope this will met the requirements.

@PeerRich WDYT about it..?

**Comment by PeerRich** [comment]
perfect! can you open a PR? @VinoV1999 

lemme also add a bounty

**Comment by ologbonowiwi** [comment]
@VinoV1999 don't forget to `/claim #numberOfIssue` to claim the bounty :)
