### ISSUE TITLE
App is crashing if user type a huge number of events

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9606]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When we create a recurring event, there are 20 events as a limitation, however, users can set the number of events to have recurred. As this is not limited to 20, users can add huge numbers here and it can cause a crash.

### Steps to Reproduce

1. Create a recurring event with any number of events, limited to 20
2. In another tab, try to book for this event type
3. Set a day
4. Check that it's possible to have more than the limitation from the event type (20 in that case)
5. Type 999999999 as the number of events
6. Set a time
7. Check that the app will crash 
8. If refresh the page, it cost a lot of time to recover 
9. After recovery, it shows that there are 20805 more events, but if you try to mouse over that, it will crash again

### Technical details

- Google Chrome v114.0.5735.134 (Official Build) (64-bit)
- Tested on Version preview for that PR (https://cal-5luk9i0hk-cal.vercel.app/event-types)

![image](https://github.com/calcom/cal.com/assets/10250819/bbf8c76f-8c90-44f6-8104-496ff3fac2f2)

![image](https://github.com/calcom/cal.com/assets/10250819/e4ffaf0d-8029-4743-aa9e-660596692d07)

**Comment by Chiranjeev-droid** [comment]
This has been solved in some pr i guess as i tested in local setup.
