### ISSUE TITLE
[CAL-1197] French translation missing for Attendee phone number location

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9607]
Created via Threads. See full discussion: [https://threads.com/34454254567](https://threads.com/34454254567)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1197](https://linear.app/calcom/issue/CAL-1197/french-translation-missing-for-attendee-phone-number-location)</sub>

**Comment by PeerRich** [comment]
fixing via crowdin
