### ISSUE TITLE
[CAL-1980] chore: clean up old booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9608]
remove all components of the old booking page to prevent confusion for contributors

<sub>[CAL-1980](https://linear.app/calcom/issue/CAL-1980/chore-clean-up-old-booking-page)</sub>

**Comment by kemilbeltre** [comment]
@PeerRich I would like to take this one, what is the old booking page? thanks

**Comment by rene-mueller** [comment]
@PeerRich i can do this now.

**Comment by kemilbeltre** [comment]
@PeerRich Do we want to keep the old `booking` pages where they are or move them to features as well?
