### ISSUE TITLE
Website home page is not responsive on the Samsung Galaxy Fold

### ISSUE THREAD

**Issue by shubhamkhunt04** [calcom/cal.com#9614]
### Issue Summary

Website home page is not responsive on the Samsung Galaxy Fold

### Steps to Reproduce

1. Open browser dev tools
2. Select the dimension galaxy fold
3. Check the home page

### Expectation
It should be responsive on such popular device

### Technical details and reference video

- Node.js version 18
- Video steps to Reproduce

![cal](https://github.com/calcom/cal.com/assets/55044317/bd61f817-f0e3-481c-afab-8b3b40daf94c)

**Comment by shubhamkhunt04** [comment]
@milospuac @hariombalhara I would like to work on this issue

**Comment by 01vishu** [comment]
I am interested in contributing to your project and would like to request to be assigned to the project. I believe I have the necessary skills and expertise to make meaningful contributions to the project.

**Comment by PeerRich** [comment]
hey y'all, the website is not open source unfortunately
