### ISSUE TITLE
[CAL-1981] mobile: hide event type filter

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9616]
we only want these on desktop

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/83c3336f-472d-4f65-b657-f7a2400c6b7c/cdbc707e-8758-4ce8-bdad-8cd4d644116d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1981](https://linear.app/calcom/issue/CAL-1981/mobile-hide-event-type-filter)</sub>

**Comment by manavsiddharthgupta** [comment]
@PeerRich can you review my pr.
