### ISSUE TITLE
Embed details modal has weird height

### ISSUE THREAD

**Issue by LorensoD** [calcom/cal.com#9623]
### Issue Summary

Apparently the name details stap of the (inline)embed has been changed to a modal. The height of this modal is however a bit weird. It's very narrow. Whereas the date picker does have a normal height.

<img width="313" alt="image" src="https://github.com/calcom/cal.com/assets/25841435/27af9003-c976-4c73-bf55-274a5c1f849b">

### Steps to Reproduce

1. Go to https://dagostino.digital
2. Click contact, (top right in the menu)
3. In the modal that opens, select a date and time.
4. You will see that the details modal suddenly has a weird height

This also happens in the embed preview on the cal.com site.

### Technical details

- React embed (`"@calcom/embed-react": "^1.1.1"`)

Also it would be nice to not have a modal for the inline embed. It looks a bit weird against the white background of the section where I put the inline embed.
<img width="769" alt="image" src="https://github.com/calcom/cal.com/assets/25841435/66171188-e03b-490b-90bf-c3d89970b319">

**Comment by Faizan711** [comment]
If this issue is open and no one is working on it, i would like to be assigned to work on it.

**Comment by LorensoD** [comment]
Now the embed seems to work like earlier again. So without the modal. The height is also as I would expect now.
