### ISSUE TITLE
[CAL-1983] User profile dropdown UI issues

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9626]
### Issue Summary

Space of 8px missing between name and ChevronDown icon:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f402801d-cb15-42e1-bd6b-3620c0382ae8/08672855-4249-4ef3-9bd0-a5428a3584db)

User name is cut off early, there is still some space to show more of the username

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/863d0a82-088a-4c47-aafd-b03d19284b76/65ea602a-15b5-4078-9552-93f0e13b34ab)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1983](https://linear.app/calcom/issue/CAL-1983/user-profile-dropdown-ui-issues)</sub>

**Comment by Zahidd02** [comment]
Hey can you share a picture and the link where this issue is present. I'd like to take a look.

**Comment by Udit-takkar** [comment]
@Zahidd02 i think this issue has been fixed
