### ISSUE TITLE
[CAL-1985] settings: skeleton issues

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9627]
[https://github.com/calcom/cal.com/assets/8019099/4bef7828-0d8f-47c5-9533-59fd4418332a](https://github.com/calcom/cal.com/assets/8019099/4bef7828-0d8f-47c5-9533-59fd4418332a)

see:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/aa14bec0-00a7-45ad-a049-8fdc04b86e0e/a31c3730-0b45-43a1-a972-ac4507c88386)

* the i18n string should be a skeleton and not my_account
* the padding between icon and headline is missing
* the padding between avatar skeleton and title is missing
* avatar skeleton has wrong size

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2c7192a5-0a05-4789-bac4-10c5c91527ec/62573843-cb48-4096-aaa0-1a3d7357693d)

ideally there is as little layout shift as possible

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1985](https://linear.app/calcom/issue/CAL-1985/settings-skeleton-issues)</sub>

**Comment by emrysal** [comment]
This has much improved with 9641 but I'm still not happy with the current skeleton, I don't think you will be too @PeerRich

**Comment by gitstart-calcom** [comment]
@emrysal @PeerRich We took a look and seems to be right, but if have any problem we can solve it, we just need to know where

**Comment by gitstart-calcom** [comment]
Hey @keithwillcode This issue can be closed, It's not happening anymore
