### ISSUE TITLE
[CAL-1990] Error when canceling or rescheduling seated event

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9640]
### Issue Summary

Error when canceling booking (event still gets canceled):

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b46f8458-794f-4c3a-95c4-8b1b05a2ce95/aa5b1654-8c38-48ad-9acc-8f74778dadce)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5f29233c-e0f2-42b6-a3f2-a542c22c2a9a/a7ea265b-359b-48c5-8f67-88e61017ad27)

Error when rescheduling seated event (also goes through):

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c433dd1f-cabf-4f8d-afdf-228cd0c5f200/03948be3-97d9-48f1-975d-478e9c0d4362)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ab67d839-4a1e-40ad-96d6-af3acbe5b1d0/2c743c2d-2fd1-40d3-a253-e97018710b96)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1990](https://linear.app/calcom/issue/CAL-1990/error-when-canceling-or-rescheduling-seated-event)</sub>

**Comment by ashish1233** [comment]
Hi @CarinaWolli , I am new Contributor

Not able to replicate.
I made a booking and cancelled it.
<img width="1711" alt="image" src="https://github.com/calcom/cal.com/assets/20872233/90a28103-0b76-48ff-a58d-d3403d7bc0b2">

**Comment by JaideepGuntupalli** [comment]
Hey, @CarinaWolli can you pls provide the exact steps to replicate this since I can't replicate the issue.

**Comment by CarinaWolli** [comment]
Looks like this is not seats related, also some of my other event types are throwing the error. I will investigate, and create a new issue when I find the cause of it
