### ISSUE TITLE
Error 404 on JS embed when selecting timeslot

### ISSUE THREAD

**Issue by Krysand** [calcom/cal.com#9644]
### Issue Summary

When embeding a cal.com calendar and the user selects a timeslot he is routed to an URL which does not exist.
<img width="778" alt="image" src="https://github.com/calcom/cal.com/assets/33368899/66631de8-6f05-4798-ae43-663d465a96c7">

<img width="1045" alt="image" src="https://github.com/calcom/cal.com/assets/33368899/2db3de64-bbc3-4e6d-a9bd-4a6dff9d09da">

https://app.cal.com/krysand/book?embedType=modal&embed=&type=243752&duration=20&date=2023-06-22T14%3A40%3A00%2B02%3A00&slug=general&timeFormat=h%3Amma&count=

### Steps to Reproduce

1. Cal("preload", { calLink: "krysand/xxx" });
2. Clicked on date and then timeslot
3. Error 404 

### Technical details

Embed via call to https://cal.com/embed.js

**Comment by gavry** [comment]
Also experiencing this, personally using the React wrapper

**Comment by Schmedu** [comment]
Same here

**Comment by digitdustin** [comment]
Getting this aswell

**Comment by PeerRich** [comment]
can you try again? I think this has been fixed

**Comment by gavry** [comment]
Yup! Fixed for me. Thank you!
