### ISSUE TITLE
[CAL-2004] Use Storybook controls

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#9655]
### Is your proposal related to a problem?

Storybook Controls gives you a graphical UI to interact with a component's arguments dynamically without needing to code. It creates an addon panel next to your component examples ("stories"), so you can edit them live.

Read more here [https://storybook.js.org/docs/react/essentials/controls](https://storybook.js.org/docs/react/essentials/controls)

Currently our stories are not configured to handle controls

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b0ebb9f2-2182-4ec0-978c-9be54e5c54e5/abbba882-751f-4847-9d21-34fcedf56a53)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2004](https://linear.app/calcom/issue/CAL-2004/add-storybook-controls)</sub>

**Comment by JaideepGuntupalli** [comment]
I am working on this!! @Udit-takkar
