### ISSUE TITLE
[BUG] : Contact Us title needs more margin

### ISSUE THREAD

**Issue by pragatiailani** [calcom/cal.com#9662]
### Issue Summary
The title in Pricing section that says "Contact Us" needs more margin in the bottom.

![image](https://github.com/calcom/cal.com/assets/53570121/c3536f90-98f5-46d0-b0ef-aff7f9040108)

### Steps to Reproduce

1. Go to the cal.com landing page
2. Click on the pricing button on the navbar.
3. see the last article whose heading is "Contact Us".

### Technical details

- Browser : Brave
- Node.js version

**Comment by JaideepGuntupalli** [comment]
@pragatiailani Hey, whats your screen size?

**Comment by pragatiailani** [comment]
@JaideepGuntupalli 
Screen Size: 33.78 cm (13.3 in)
And yes, it is giving the same output in the incognito mode (of brave browser).

I checked this on different browsers (chrome and edge), they were giving different outputs: 
![image](https://github.com/calcom/cal.com/assets/53570121/6b39a932-56c4-43a0-a1c0-c13dcd8d54c6)

**Comment by JaideepGuntupalli** [comment]
Sadly i cant replicate this on my end:

https://www.loom.com/share/71a1a7c4d1c74154aa56acd643673c1a?sid=ed49d7db-9ad1-473f-832c-057b49211a8f

**Comment by PeerRich** [comment]
![CleanShot 2023-06-26 at 22 26 07@2x](https://github.com/calcom/cal.com/assets/8019099/2ddeb5c3-23dd-4020-b8c9-588b75a0679b)
looks good on my end
