### ISSUE TITLE
[CAL-1902] Review / Sync event types with different layouts in /settings/appearance

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#9672]
![CleanShot 2023-06-07 at 09.41.08@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/60c97e12-ec13-4efc-9ccf-3e24ee1818a6/d1b079d5-7d14-49c5-b875-ad74e6154651)

![CleanShot 2023-06-07 at 09.41.52@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9b1def3b-2fdf-4f7d-a4a1-3d5797c6c756/775c84aa-0aab-45f2-b957-7440573c448d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1902](https://linear.app/calcom/issue/CAL-1902/review-sync-event-types-with-different-layouts-in-settingsappearance)</sub>

**Comment by JaideepGuntupalli** [comment]
@Jaibles I would like to work on this. So as far as i understand this is a new feature right?
