### ISSUE TITLE
[CAL-2008] Public calendar: Weekly view has weird border all left side of calendar

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9677]
The border all down the left side of the weekly view calendar is inconsistent. It should just be a 1px line with the `border-default`token all down the left side. It looks doubled at the top, then lighter and lighter again. There should also be a border just right of the times that looks missing or too light.

The header of the calendar should also just be a white bg.

![CleanShot 2023-06-21 at 07.46.27@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d665f57e-e7a8-4152-8cc9-8a87cf2b0a81/082d4dc9-6013-4aa5-97c4-379adbb05bae)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2008](https://linear.app/calcom/issue/CAL-2008/public-calendar-weekly-view-has-weird-border-all-left-side-of-calendar)</sub>

**Comment by Aryanshu919** [comment]
Hey please assign this issue to me.

**Comment by shammirbaig** [comment]
Hi @Jaibles ,Im unable to view that weekly view of public calender,If you dont mind can you please tell me how to view that weekly view

**Comment by shammirbaig** [comment]
![image](https://github.com/calcom/cal.com/assets/66933858/424c0b99-915d-4132-81c9-080813dc14df)

**Comment by maheshkeswani** [comment]
Hey @Jaibles  , Please Assign this issue to me
