### ISSUE TITLE
[CAL-2009] the phone input not prefilling (disappearing)

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9682]
the phone input not prefilling (disappearing) is a regression of this PR: [https://github.com/calcom/cal.com/pull/8705](https://github.com/calcom/cal.com/pull/8705)
It changes the country on page load based on your IP address. But as a result of that country changing, it also clears the input field.

A note for the person picking this up; Locally the prefill is working because the API (packages/trpc/server/routers/publicViewer/countryCode.handler.ts) is always returning US. If you change that manually to a different country, then you will be able to replicate the behavior.

[https://www.loom.com/share/2ea2002b854648fa9b854a36bdf1c5a5?sid=552dda3f-6fb4-43cb-8ed8-a7124dd9337c](https://www.loom.com/share/2ea2002b854648fa9b854a36bdf1c5a5?sid=552dda3f-6fb4-43cb-8ed8-a7124dd9337c)

Created via Threads. See full discussion: [https://threads.com/34482909231](https://threads.com/34482909231)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2009](https://linear.app/calcom/issue/CAL-2009/the-phone-input-not-prefilling-disappearing)</sub>

**Comment by AryanS-2004** [comment]
Could you please assign it to me? I would like to work on it.

**Comment by anmol242** [comment]
Just raised a PR for this fix @milospuac
