### ISSUE TITLE
Sorting from event-types won't work

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#9689]
### Issue Summary

when i try to sort an event-type, it is only displayed at the new possition after reloading the website.
![grafik](https://github.com/calcom/cal.com/assets/48084558/812a2468-722c-4894-8a24-046f037f26c2)

### Steps to Reproduce

1. Go to https://app.cal.com/event-types
2. Try to sort an existing event-type

**Comment by PeerRich** [comment]
works for me

https://github.com/calcom/cal.com/assets/8019099/ddb38d7e-696b-4a10-8b60-5297f0496589
