### ISSUE TITLE
Undefined value in the Email Template on the questions

### ISSUE THREAD

**Issue by ghost** [calcom/cal.com#9691]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There is an undefined value in email template if users provides no response to the custom questions.
### Steps to Reproduce

1. Book a meeting.
2. Leave a custom question as empty.
3. Check your Email confirmation and you will see the undefined in the result.

**Comment by afrieirham** [comment]
Looks fine on my side

Custom value is filled
<img src="https://github.com/calcom/cal.com/assets/32460534/da013d7e-a472-4f91-b5c1-9a4f8bcf7c6d" width="300px" />

Custom value is blank
<img src="https://github.com/calcom/cal.com/assets/32460534/6c52488a-1416-4496-aecb-165117b375be" width="300px" />

**Comment by gitstart-calcom** [comment]
We will check if this is still happening, we can fix it if so

**Comment by gitstart-calcom** [comment]
Hi @keithwillcode this issue is not happening anymore
