### ISSUE TITLE
Public pages button are enabled for pending users

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9701]
### Issue Summary

After inviting users for a team, they are in pending status and their username is still `null`. The `Public page` buttons for those pending users are also enabled. After clicking on that button, it returns a 404 page as there are no users called `null`

### Steps to Reproduce

1. Create an organization and set up a team
2. Invite users for that team
3. Confirm that they are in pending status
4. Click on the `View public page` button for any pending user

### Actual Results

- `View public page` buttons are enabled for pending users
- A 404 page is shown after clicking on the buttons as there is no `null` user

### Expected Results

- `View public page` buttons should be disabled for pending users

Note: Do you think that we should have "reserved" usernames? Or kind of a list with not allowed usernames like that

### Technical details

- Tested on Chrome (114.0.5735.134) and Firefox (114.0.2)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/4f186a6c-97a4-4bf9-9e56-d55770db60c0)

![image](https://github.com/calcom/cal.com/assets/10250819/c607b5b8-161c-49b7-b240-33bdc5fdedac)

**Comment by Parthib314** [comment]
Can I work on it?

**Comment by AnitKrJha** [comment]
![image](https://github.com/calcom/cal.com/assets/103268398/38b2527d-708b-4d7b-8acc-0384c6fa6081)
Also the button in the dropdown doesn't have the link to the page! 
 
I am working on it!
