### ISSUE TITLE
[CAL-2069] Use Organization Logo instead of Avatar

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9702]
### Is your proposal related to a problem?

When click on upload a logo for an organization, another window is opened and it is calling to change the Avatar.

### Describe the solution you'd like

It could be better if instead of Avatar. For organizations, it could be something like Logo or Picture or something different than Avatar.

[https://github-production-user-asset-6210df.s3.amazonaws.com/10250819/247781950-9f5b57e9-9986-4077-9813-3cf0acda474c.png](https://github-production-user-asset-6210df.s3.amazonaws.com/10250819/247781950-9f5b57e9-9986-4077-9813-3cf0acda474c.png)
[https://github-production-user-asset-6210df.s3.amazonaws.com/10250819/247781950-9f5b57e9-9986-4077-9813-3cf0acda474c.png](https://github-production-user-asset-6210df.s3.amazonaws.com/10250819/247781950-9f5b57e9-9986-4077-9813-3cf0acda474c.png)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2069](https://linear.app/calcom/issue/CAL-2069/use-organization-logo-instead-of-avatar)</sub>

**Comment by Vivek7038** [comment]
Instead of "avtar"you want it to be "logo" right ? If only  ui needed to be changed I can do it.

**Comment by N-NeelPatel** [comment]
@ericrommel - can you tell how to create organization?

**Comment by ericrommel** [comment]
> @ericrommel - can you tell how to create organization? or how to update information about organization.

Just go to `/settings/organizations/new`.
