### ISSUE TITLE
CalDAV for Confluence

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#9711]
### Issue Summary

Connection to Confluence works, but there are no events.

**Comment by rene-mueller** [comment]
CC @alishaz-polymath

**Comment by alishaz-polymath** [comment]
That's weird. Could you please create a test account and share credentials on my email for me to test and debug this?

**Comment by rene-mueller** [comment]
@alishaz-polymath sure. can you go on slack?

**Comment by alishaz-polymath** [comment]
Yes 👍
