### ISSUE TITLE
[CAL-2027] bug: uploading team avatar not working

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9716]
not sure why this is not working

https://app.birdeatsbug.com/sessions/lepgpP8pMzdbueBX4YGNibmR2LlA93iRLiEsztaZQLJR

<sub>[CAL-2027](https://linear.app/calcom/issue/CAL-2027/bug-uploading-team-avatar-not-working)</sub>

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, we could not reproduce the issue.
https://www.loom.com/share/10104373ab554d66827626524ac482f4
