### ISSUE TITLE
Correct date format issues in reminder emails

### ISSUE THREAD

**Issue by zenminimalist** [calcom/cal.com#9723]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to change the date format for a message template under "workflows" in cal.com from the default setting (ddd, MMM D, YYYY H:mmA) , I can't seem to get the proper output. I'm trying to get the following format: 

![CleanShot 2023-06-22 at 19 01 08](https://github.com/calcom/cal.com/assets/7798503/07b7f669-434c-4cda-8bea-ba0ada79dcba)

12.046.2023 - 19:15PM (Europe/Berlin)

I tried various formats and iterations (see below), but can't seem to be able to change it to this format. 

I played with: 
- {EVENT_DATE, D.MM.YYYY HH:mm} - {EVENT_END_TIME} ({TIMEZONE})
- {EVENT_DATE_D.MM.YYYY HH:mm} - {EVENT_END_TIME} ({TIMEZONE})
- {EVENT_DATE, DD.MM.YYYY HH:mm} - {EVENT_END_TIME} ({TIMEZONE})

Not sure if this is a bug or I'm missing something. 

### Technical details

- Vivaldi browsers (Chrome-based)

**Comment by afrieirham** [comment]
I'm interested to work on this, anyone can assign this to me?

**Comment by CarinaWolli** [comment]
So I just tested with: 
{EVENT_DATE_D.MM.YYYY HH:mm} - {EVENT_END_TIME} ({TIMEZONE})

And it looks right in my workflow email 🤔
<img width="422" alt="Screenshot 2023-06-28 at 16 40 04" src="https://github.com/calcom/cal.com/assets/30310907/25e16526-62f1-4c9b-a98d-389ae20a4ca1">

![Screenshot 2023-06-28 at 16 40 17](https://github.com/calcom/cal.com/assets/30310907/d35c0021-ae13-415d-b273-bcdad5a03e2f)


@afrieirham Can you reproduce that?

**Comment by afrieirham** [comment]
@CarinaWolli it works on my side too.
<img width="331" alt="image" src="https://github.com/calcom/cal.com/assets/32460534/b552feef-8fb4-4f45-a653-c1ad3aa97550">

maybe @zenminimalist can verify if this is what he wants.

**Comment by zenminimalist** [comment]
@afrieirham Works now. That's really strange...
Either it was a hiccup in the system or something changed, as I've tried of half a dozen of times. I'll keep an eye on it to see if it creeps in again.
