### ISSUE TITLE
[CAL-2030] team events have a broken <title>

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9724]
| | [Cal.com](http://Cal.com)

looks odd

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/aa231f10-938e-471d-b07d-d29db269a566/9abc875a-af2e-4880-9878-8c73f9a49c72)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2030](https://linear.app/calcom/issue/CAL-2030/team-events-have-a-broken-title)</sub>

**Comment by kunxl-gg** [comment]
do you want to remove the vertical lines from the title

**Comment by PeerRich** [comment]
It should show the title of the event and then the vertical.

like so:

Enterprise Technical Evaluation | Cal.com

**Comment by PeerRich** [comment]
and yea, @kunxl-gg go for it! 🙏

**Comment by kunxl-gg** [comment]
I am so sorry for taking so much time. How do you reproduce this error? I managed to set it up locally 
day before yesterday itself
