### ISSUE TITLE
[CAL-2034] Follow up on location details

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#9736]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

[https://github.com/calcom/cal.com/pull/9710#issuecomment-1603679829](https://github.com/calcom/cal.com/pull/9710#issuecomment-1603679829)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2034](https://linear.app/calcom/issue/CAL-2034/follow-up-to-location-details)</sub>

**Comment by PeerRich** [comment]
i think this has been fixed in the new booker no?
