### ISSUE TITLE
[CAL-2183] Fix sluggish parts of event type overview

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#9741]
### Issue Summary

Using the event type overview is very sluggish. When I select an event type, it takes at least 4 seconds for the event type to load. A skeleton should be used here to give the user direct feedback that something is about to happen.

<sub>[CAL-2183](https://linear.app/calcom/issue/CAL-2183/fix-sluggish-parts-of-event-type-overview)</sub>

**Comment by rene-mueller** [comment]
CC @PeerRich

**Comment by PeerRich** [comment]
@roae @keithwillcode lets focus on this while looking into that endpoint

**Comment by leog** [comment]
@keithwillcode @PeerRich Is this a duplicate of #9944?

**Comment by PeerRich** [comment]
yep but #9944 is closed already? is event-type view faster now?

**Comment by leog** [comment]
> yep but #9944 is closed already? is event-type view faster now?

@PeerRich I think event-type page feels better yeah

**Comment by satya-nishanth** [comment]
> > yep but #9944 is closed already? is event-type view faster now?
> 
> @PeerRich I think event-type page feels better yeah

Yes definitely better and now it also shows progress, which is good feedback for the user.

**Comment by leog** [comment]
Tackled by #9944.
