### ISSUE TITLE
[CAL-2080] UI inconsistency relating to high loading time

### ISSUE THREAD

**Issue by ahmedsadman** [calcom/cal.com#9742]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Some portion of the management page, when clicked, does not show any loading indicator. It stays on the same page and redirects to the intended page about 10-15 seconds later. I was consistently able to reproduce this issue on the App page. So, I'll be sharing it here.

### Steps to Reproduce

1. Land on the Cal.com management page
2. From the left pane, click Apps. Nothing will happen for the first 10 seconds
3. After approx. 10 seconds, you will be redirected to the app page

**Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?**

This hampers user experience. Users sometimes click 3-4 times and wonder why it's not loading (this happened in my case as well). See the technical details section for more context. If the load time is high, the user should see some kind of indicator that his request is being processed. Such indicators should be shown in all sections of the app, as required.

### Technical details

- Google Chrome - Version 114.0.5735.134 (Official Build) (64-bit)
- A quick peek at the Network tab reveals that a `GET` call on `https://app.cal.com/_next/data/KaRZJ2CMJ0Uyuf72oF6lh/en/apps.json` takes approx **10-13 seconds** to complete on initial load.
- The given load time might vary depending on network quality, but such load times are unusual. In any case, the user should have some kind of indicator feedback.

<sub>[CAL-2080](https://linear.app/calcom/issue/CAL-2080/ui-inconsistency-relating-to-high-loading-time)</sub>

**Comment by rene-mueller** [comment]
associated with #9741

**Comment by PeerRich** [comment]
instead of adding a loading bar we will revisit all pages and increase its speed that it'll be instantaneous

**Comment by PeerRich** [comment]
misclicked. was not meant to be closed

**Comment by sean-brydon** [comment]
Yeah the plan is to split up the pages into one - some tech debt that we just keep adding to. 

Not sure if i'm gonna be the one picking this up but we have talked in threads about how to optimise this
