### ISSUE TITLE
Cannot add multiple time slots

### ISSUE THREAD

**Issue by ahmedsadman** [calcom/cal.com#9743]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A second time slot cannot be added to the last-day entry. Screen recording attached

### Steps to Reproduce
See the recording for clarification

1. Land on the default Cal management page
2. Go to Availability
3. Select Default Availability
4. Offtopic: Notice the time delay between the mouse click and the actual page load (relates to https://github.com/calcom/cal.com/issues/9742)
5. On the last day in the list (Saturday for me), make sure only one entry is there. Now try adding a second slot
6. Nothing would happen (unexpected)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Users should be able to add the time slot.

### Technical details

- Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- 

https://github.com/calcom/cal.com/assets/11042267/37bbe033-c7ec-4a1f-b940-51d591a8e8e2

**Comment by maheshkeswani** [comment]
Hey @ahmedsadman , I would Like to Work On this Issue , please assign it to me  .

**Comment by ahmedsadman** [comment]
> Hey @ahmedsadman , I would Like to Work On this Issue , please assign it to me .

I'm just reporting bugs here. I don't have the privilege to assign any issues to anyone. Thanks for the understanding.

**Comment by anmol242** [comment]
This is because the platform doesn't support to backtrack while adding new time slots and the time you selected was already `11.59 pm` which is end of Day. I have created a PR for this fix https://github.com/calcom/cal.com/pull/9789. Will soon mark this as review after adding loom video 😄
