### ISSUE TITLE
Custom Meeting links overflow in new scheduling system

### ISSUE THREAD

**Issue by eliasfaltin** [calcom/cal.com#9753]
### Issue Summary

Using a long, custom, meeting link leads to the link overflowing onto the calendar part of the booking page.

### Steps to Reproduce

1. Use Arc (probably the culprit)
2. go to cal.com/eliasfaltin/gather
3. See this: 
![CleanShot 2023-06-23 at 16 36 43@2x](https://github.com/calcom/cal.com/assets/36010212/8b534ab8-fe7b-4861-90d0-1a1268681b22)

I would expect the link to wrap or be cut off and only visible in full on hover (a functionality that already exists).

### Technical details

- Arc Version 0.108.1 (39609) - Chromium Engine Version 114.0.5735.133

**Comment by kemilbeltre** [comment]
@eliasfaltin I wonder which will be better:

Break the rest into a new line:

![image](https://github.com/calcom/cal.com/assets/20250204/819574ee-7ac4-4508-9084-afe4cfa5ccf1)

Or hiding the rest (we can see the link by hovering):

![image](https://github.com/calcom/cal.com/assets/20250204/ad755f0e-f0b3-4f98-9ff5-901c963f3b1a)

**Comment by eliasfaltin** [comment]
I agree with that! Option one is best.
It bothered me with the old scheduling page that the link was cut off.

On the other hand, it would be great if I could set a "Link text" when setting up a custom link (so it can just say "My Gather office").  In that case show the full link on hover.

A toggle, whether the link should be available (on hover) from the scheduling page would be nice as well.

For Gather.Town links, it would be nice to hide them since some companies don't want to or can't put their full space link "out there".

Another use case for the toggle is folks at bigger institutions that can't link Zoom (because the IT department handles app approvals) and want to use a Zoom link as a custom link. I have this issue with my job at a university.
