### ISSUE TITLE
[CAL-2040] Booker shows loading of monthly, if only view is weekly or column

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9758]
We shouldn't see a flash of the monthly view is the only calendar available is monthly or column

[https://github.com/calcom/cal.com/assets/4536123/9726b5e4-dddd-4079-8af6-aa09e8d9ba07](https://github.com/calcom/cal.com/assets/4536123/9726b5e4-dddd-4079-8af6-aa09e8d9ba07)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2040](https://linear.app/calcom/issue/CAL-2040/booker-shows-loading-of-monthly-if-only-view-is-weekly-or-column)</sub>

**Comment by afrieirham** [comment]
Hey @Jaibles, can you fix the screenshot for this? It seems like SyncLinear doesn't import it properly.

**Comment by Jaibles** [comment]
@afrieirham sorry synclinear keeps auto-breaking any media I upload in the description. Tried many times. Use this instead: https://share.cleanshot.com/ZCdPPtvp

And you can recreate here: https://cal.com/ciaran
