### ISSUE TITLE
API key expiration time calender is out of theme, text is not visible dark mode

### ISSUE THREAD

**Issue by Veer0x1** [calcom/cal.com#9760]
### Issue Summary

Dates are not visible in dark mode in calender in cal.com API section in dark mode

### Steps to Reproduce

1. Click on settings on bottom left
2. Select API keys from side bar
3. Try to choose expiration time from calender

or if you're logged in you can simpley click this [link](https://app.cal.com/settings/developer/api-keys)
<img width="1435" alt="Screenshot 2023-06-23 at 10 16 31 PM" src="https://github.com/calcom/cal.com/assets/96714915/344a37b2-9ad9-4906-8f9e-930d9497e537">
pp.cal.com/settings/developer/api-keys)

**Comment by chaithanya009** [comment]
Hi Team. I fixed the issue .However, when attempting to raise a pull request (PR) and reference the specific ticket, I'm being redirected to a different issue. 
If there is a different process or specific instructions to properly reference the correct issue, please let me know

**Comment by PeerRich** [comment]
we should use our own date picker here @sean-brydon

**Comment by PeerRich** [comment]
or maybe instead of picking a date, we just give a dropdown of a few selects:
- 7 days
- 31 days
- 3 months
- 1 year

**Comment by PeerRich** [comment]
/bounty 20

turn the date picker into a dropdown with

- 7 days
- 31 days
- 3 months
- 1 year

**Comment by AnitKrJha** [comment]
@PeerRich Hi can you please review this asap !🌟

**Comment by B2-krunalrana** [comment]
Thank You This code explain me lots :)
