### ISSUE TITLE
Dropdown menus do not show the Team and user avatar

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9765]
### Issue Summary

From this [PR](https://github.com/calcom/cal.com/pull/9504) I found that all dropdown menus do not show the Team and User avatar set.

### Steps to Reproduce

1. Create an Organization (/settings/organizations/new) and set up a Team. For both, set an Avatar
2. Go to the Workflow page
3. Click on the button to create a new one
4. Observe the dropdown menu avatar
5. Repeat that process to Webhook, Event Type and Routing Form

### Actual Results

- No picture or "big two letters" are being shown 

### Expected Results

- If there are avatar set, they should be shown in all dropdown menus

### Technical details

- Tested on Chrome (114.0.5735.134) and Firefox (114.0.2)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/6a9a770b-6d1e-46f9-bd54-a91d9439e402)

**Comment by PeerRich** [comment]
has this been fixed? @ericrommel

**Comment by ericrommel** [comment]
> has this been fixed? @ericrommel

I don't think so. @CarinaWolli mentioned that it would be fixed later.

**Comment by AshutoshNanaware** [comment]
Hi @PeerRich, @ericrommel , @CarinaWolli I have gone through the issue and I have some questions.
1- If  we don't have any avatar for the user then what will be the default avatar?

**Comment by CarinaWolli** [comment]
> Hi @PeerRich, @ericrommel , @CarinaWolli I have gone through the issue and I have some questions.
> 1- If we don't have any avatar for the user then what will be the default avatar?

As shown in the screenshots, here you have default user and team avatar shown: 
![Screenshot 2023-07-03 at 09 20 44](https://github.com/calcom/cal.com/assets/30310907/c993e949-4e1e-4da4-aa76-59ec5e14da72)

**Comment by hariombalhara** [comment]
This should be fixed by it #10062
