### ISSUE TITLE
"Explore all Apps" text is not visibile due to white text color in cal.com home page

### ISSUE THREAD

**Issue by shammirbaig** [calcom/cal.com#9776]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Explore all Apps button in the cal.com home page is not visible at all due to white background and white text color

### Steps to Reproduce

Go to cal.com
Scroll to connect your Apps section

### Technical details
![Screenshot from 2023-06-24 23-05-12](https://github.com/calcom/cal.com/assets/66933858/79163a15-9fa8-4893-9809-bd0ed2560129)

Chrome

**Comment by akash19coder** [comment]
I am trying to find the component that consists the button could someone please me?

**Comment by ysnarafat** [comment]
Please assign this to me.

**Comment by PeerRich** [comment]
the website repository is not open source unfortunately

**Comment by ysnarafat** [comment]
Ah, then I have to look for another issue to work on.

**Comment by PeerRich** [comment]
fixed
