### ISSUE TITLE
[CAL-2042] a11y: improve onboarding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9782]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0e621f61-8602-4016-9c02-f43df98b96ea/7ae73f7c-84a2-4e49-a20b-b263414ab3ab)

[https://twitter.com/jacobmparis/status/1672975781956554752](https://twitter.com/jacobmparis/status/1672975781956554752)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2042](https://linear.app/calcom/issue/CAL-2042/a11y-improve-onboarding)</sub>

**Comment by Dhruwang** [comment]
@PeerRich So should we increase the height of those steps ?
Or any other solution to it ?

**Comment by PeerRich** [comment]
i think these should not be clickable in the first place. i dont think this is worth working on right now
