### ISSUE TITLE
[CAL-2044] avatar yanky, doesnt load after onboarding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9784]
[https://twitter.com/jacobmparis/status/1672975817591377921](https://twitter.com/jacobmparis/status/1672975817591377921)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8cf64875-b74b-4341-8022-fb84affad8db/a90cf438-953e-4f93-8cf0-957d9c08b788)

in general quite slow sometimes and flaky

[https://twitter.com/jacobmparis/status/1672975825925451777](https://twitter.com/jacobmparis/status/1672975825925451777)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/407c501d-a1a3-4889-b3b6-1aa1d02fb55f/7bcf4a0b-002d-446b-b720-00ffc96a0124)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2044](https://linear.app/calcom/issue/CAL-2044/avatar-yanky-doesnt-load-after-onboarding)</sub>

**Comment by jacobparis** [comment]
I think it's quite likely it just hadn't finished uploading before I completed the onboarding wizard. I apologize on behalf on all users with slow internet connections: we can be a real pain.

**Comment by PeerRich** [comment]
no i mean even then we need to fail better

**Comment by ashish1233** [comment]
#hi @jacobparis, no i don't think is quite likely. The experience is not seamless.
we need to refresh the page to see updated image.


https://watch.screencastify.com/v/gzF4MELcgzynoUC5xbW3

cc: @PeerRich

**Comment by PeerRich** [comment]
so all good now?

**Comment by ashish1233** [comment]
Yeah, it seems avatar has been removed from lower part from sidebar.
But the avatar is getting updated on upper part of sidebar.


<img width="245" alt="image" src="https://github.com/calcom/cal.com/assets/20872233/41aa2572-0438-408c-bfc6-b859ff631240">


We can close this now. @PeerRich
