### ISSUE TITLE
[CAL-2045] improve first load of app

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9785]
[https://twitter.com/jacobmparis/status/1672975913036943362](https://twitter.com/jacobmparis/status/1672975913036943362)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5be6e30f-3540-4a8d-8a79-eee48d0e3b34/5181586c-d097-4d31-9338-ca7f7e965606)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2045](https://linear.app/calcom/issue/CAL-2045/improve-first-load-of-app)</sub>

**Comment by keithwillcode** [comment]
We made major improvements with cold boots
