### ISSUE TITLE
Saving Event Type automatically converts slug to lowercase

### ISSUE THREAD

**Issue by alanmontefiore** [calcom/cal.com#9790]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I use the API to create Event Types and often my generated slugs are a mixture of lower and uppercase letters and numbers. This works fine unless I use the UI to edit the event type. When I save the the Event Type, the URL (slug) is automatically converted to lowercase.

### Steps to Reproduce

1. Create an Event Type through the API and set the slug to have a mixture of uppercase and lowercase characters. E.g. FGcfd788guJB
2. Click into the newly created event type in the cal.com UI and the click 'Save'.
3. The slug is automatically changed to all lowercase. E.g. fgcfd788gujb

This makes it difficult to maintain the connection between my application and the cal.com data.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by emrysal** [comment]
Hi @alanmontefiore - we're planning to update the API to also be lowercase -only, we just don't want the situation where you have a cal.com/rick/30Min to be a different event than the cal.com/rick/30min 

Follow up @ https://github.com/calcom/cal.com/issues/9934
