### ISSUE TITLE
[CAL-2048] implement formbricks cancellation and PMF survey

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9793]
- replace cancellation survey with in-app 
- add PMF survey (how disappointed would you be)

<sub>[CAL-2048](https://linear.app/calcom/issue/CAL-2048/implement-formbricks-cancellation-and-pmf-survey)</sub>

**Comment by kemilbeltre** [comment]
@PeerRich do i need to have access to linear (to see more details) to implement this feature? thanks

**Comment by PeerRich** [comment]
i am already assigned and working on it
