### ISSUE TITLE
[CAL-2053] New Booker Booking Page Selector Wrong Time Shown

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9797]
![CleanShot 2023-06-26 at 11.17.26@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9e94c2b6-9383-4094-bb43-a4e0820d7fb5/7318d132-fb83-4351-ae89-04473e807756)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2053](https://linear.app/calcom/issue/CAL-2053/new-booker-booking-page-selector-wrong-time-shown)</sub>

**Comment by kemilbeltre** [comment]
@shirazdole could you  fix the link to the screenshot? Thanks

**Comment by kemilbeltre** [comment]
How could I have access to it?

**Comment by sean-brydon** [comment]
@shirazdole are you still having this issue? Can't reproduce at all
