### ISSUE TITLE
Issue with main page after update to v3.0.7

### ISSUE THREAD

**Issue by buzzard10** [calcom/cal.com#9812]
### Issue Summary

After update docker version of calcom to 3.0.7 today i have on main (book.domain.com) page error 404
### Steps to Reproduce

1. Open main page, i.e. book.domain.com

![image](https://github.com/calcom/cal.com/assets/17282191/5f9cc0bc-464f-46fa-98c3-aca8a4b2721b)

If i enter manually book.domain.com/bookings/upcoming it'll show proper page with upcoming bookings

**Comment by carsonbird** [comment]
I'm experiencing the same issue.

**Comment by carsonbird** [comment]
#9768

**Comment by keithwillcode** [comment]
This has been fixed in v3.0.9.
