### ISSUE TITLE
Update the Contrbuting.md

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#9813]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There's a step is missing in the step 5 of inside contributing.md file. To setup the .env file we have to copy the .env.example to .env first.

Expected: -
![Screenshot 2023-06-27 095419](https://github.com/calcom/cal.com/assets/81948346/f45b5f9c-386c-47b7-92fb-14a962fdb0f7)

Actual:-
![Screenshot 2023-06-27 095437](https://github.com/calcom/cal.com/assets/81948346/d98df11f-dcf6-481f-92f2-857153d0c4d4)

### Steps to Reproduce

1. Go to contributing.md

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by Parthib314** [comment]
@anikdhabal  Hey I changed [this](https://github.com/calcom/cal.com/pull/9814) please check.
