### ISSUE TITLE
TypeError in calcom/react-embed

### ISSUE THREAD

**Issue by jobenjada** [calcom/cal.com#9817]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There seems to be a TypeError in the, `layout` cannot be used

### Steps to Reproduce

1. Install calcom/react-embed
2. Use the code from the embed page
3. See type error

![grafik](https://github.com/calcom/cal.com/assets/72809645/ad5f2d65-41c2-4516-80e5-217f6eafdf6c)

**Comment by hariombalhara** [comment]
Hey @jobenjada 
 Yeah, layout isn't enabled for embeds fully. It would still work with some issues. Plan to enable it and support typing for layout within 1-2 days itself.

**Comment by hariombalhara** [comment]
This is fixed now. See https://codesandbox.io/s/week-view-element-click-react-3vwz2t?file=/src/App.js
