### ISSUE TITLE
Add progress bar to indicate route transitions

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [calcom/cal.com#9823]
### Is your proposal related to a problem?
When a user clicks on a nav item(navigates to a page), it feels like nothing has happened or happening. Making the user feel stuck on the current page.

### Describe the solution you'd like
A progress bar should be shown at the top of the page telling the user something is happening (just like any loading screen) till the route navigation completes.

### Describe alternatives you've considered
none

### Additional context
There's a [package](https://www.npmjs.com/package/nprogress) that can easily do this.

**Comment by Dhruwang** [comment]
would like to work on this !

**Comment by PeerRich** [comment]
no package needed. this can easily be achieved with simple CSS as a `<Loading>` component.

however, I am not sure if we actually want this loading bar. instead we should really invest in getting page load down and have good skeletons wherever needed

**Comment by PeterKwesiAnsah** [comment]
> can you list which pages load slow?

The Apps, Insights page and the get started page( had to make a couple of extra clicks to the 'next step' button because nothing was happening)

**Comment by PeerRich** [comment]
closing in favor of https://github.com/calcom/cal.com/issues/9837
