### ISSUE TITLE
[CAL-2060] Tab title is missing data

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9824]
Team event:

[https://github-production-user-asset-6210df.s3.amazonaws.com/30310907/249287306-94396d31-30fc-4ebc-8db8-30c9b5c92c28.png](https://github-production-user-asset-6210df.s3.amazonaws.com/30310907/249287306-94396d31-30fc-4ebc-8db8-30c9b5c92c28.png)

This is how it looks for user event type:

[https://github-production-user-asset-6210df.s3.amazonaws.com/30310907/249287280-5993bab0-1b3e-4ff1-8107-604aa1796ed8.png](https://github-production-user-asset-6210df.s3.amazonaws.com/30310907/249287280-5993bab0-1b3e-4ff1-8107-604aa1796ed8.png)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2060](https://linear.app/calcom/issue/CAL-2060/tab-title-is-missing-data)</sub>

**Comment by ujwalkumar1995** [comment]
Hi @CarinaWolli 
We are unable to see the screenshots shared by you.
![Screenshot 2023-06-27 220212](https://github.com/calcom/cal.com/assets/20976813/e7acc9fe-6759-4c7e-b52c-af759edb4eab)

**Comment by CarinaWolli** [comment]
Sorry for that, updated the screenshots

**Comment by PeerRich** [comment]
our sync tool is having issues, here: 

https://github-production-user-asset-6210df.s3.amazonaws.com/30310907/249287306-94396d31-30fc-4ebc-8db8-30c9b5c92c28.png

https://github-production-user-asset-6210df.s3.amazonaws.com/30310907/249287280-5993bab0-1b3e-4ff1-8107-604aa1796ed8.png

**Comment by ujwalkumar1995** [comment]
Hey Folks
Thank you for the screenshots. I think this issue is duplicate for #9724 
I have raised a PR on that issue. I think that would close both these issues.
