### ISSUE TITLE
[CAL-2067] fix slow pages

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9837]
* Event Types [https://github.com/calcom/cal.com/issues/9944](https://github.com/calcom/cal.com/issues/9944)
* Apps #9921
* Insights page
* Get started page

> had to make a couple of extra clicks to the 'next step' button because nothing was happening)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2067](https://linear.app/calcom/issue/CAL-2067/fix-slow-pages)</sub>

**Comment by keithwillcode** [comment]
Going to close this one in favor of the individual issues we have for each of these.
