### ISSUE TITLE
[CAL-2068] UI: make hover brand color

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9838]
[https://github.com/calcom/cal.com/assets/8019099/5d7cc736-20b9-4159-8bed-81e6ee93db01](https://github.com/calcom/cal.com/assets/8019099/5d7cc736-20b9-4159-8bed-81e6ee93db01)

this should be brand:

[https://github.com/calcom/cal.com/assets/8019099/3617c2c4-c248-4c4b-b004-f4c061215506](https://github.com/calcom/cal.com/assets/8019099/3617c2c4-c248-4c4b-b004-f4c061215506)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2068](https://linear.app/calcom/issue/CAL-2068/ui-make-hover-brand-color)</sub>

**Comment by karthiknadar1204** [comment]
@PeerRich If this issue is up for grabs, I would like to work on it

**Comment by PeerRich** [comment]
sure @karthiknadar1204 go for it. no need to ask
