### ISSUE TITLE
[CAL-2070] reduce i18n skeletons

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9840]
we have a lot of skeletons in place where we are loading i18n strings (translated words)

if we dont have these skeletons, it would show something like "event_types_title" for a brief second

if we do SSR for all pages, we'd wait for the string to load and then load the entire page, causing no skeletons, no string flickering but slower pages (we are bascially blocking the UI till all strings are loaded)

\_\_

is there no way to load the entire en/common.json once, and keep it somehow warm/around without constant skeletons?

ideally we get away without SSR

EDIT by @zomars:

Made a more detailed explanation of the desired solution here: [https://github.com/calcom/cal.com/issues/10198](https://github.com/calcom/cal.com/issues/10198)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2070](https://linear.app/calcom/issue/CAL-2070/reduce-i18n-skeletons)</sub>

**Comment by rjackson** [comment]
Looks like there's a few caching tricks we can configure. First load will be "slow", but subsequent loads can pull from browser localStorage.

Will have to look into cache invalidation to make sure latest locales are pulled when the locale files are updated.

/attempt #9840

**Comment by rjackson** [comment]
Haven't had a chance to jump back to this in any great detail yet, but from my earlier explorations I'd notice that we don't _really_ use Next.js' i18n features at all (i.e. no subdomain or path routing to identify locale).

I think our integration via `next-i18next` therefore confuses the codebase a little bit and we might be better off dropping it and plugging into `react-i18next` directly, with our own dedicated adapter layer to manage our custom requirements (how we load locale, avoiding flash of untranslated tokens). That would be a much larger refactor / technical debt task, however. I don't know if that should form part of this work, but I'm feeling like it probably won't be necessary.

Now understanding our i18next integration properly, I think we'll be able to introduce our own LocalStorage layer to maintain the locale files client-site. This should greatly reduce (maybe eliminate) loading skeletons when caches are warm, and possibly greatly reduce the amount of i18n API lookups we're making. To minimise stale cache issues we can vary those cache IDs by the Next.js build ID (make sure updates to the lang files always come through again), locale (avoid lookups for languages we've seen before), and make sure we refresh all relevant state when the user changes language.

I'm unlikely to be able to start on this today, but might be able to put some time into this later in the week – if nobody beats me to it :)

**Comment by PeerRich** [comment]
>  might be able to put some time into this later in the week

this would be terrific!

**Comment by PeerRich** [comment]
@rjackson i can increase the bounty if neede

**Comment by zomars** [comment]
Made a more detailed explanation of the desired solution here: https://github.com/calcom/cal.com/issues/10198

**Comment by surajgjadhav** [comment]
Hi @PeerRich , @zomars 
We should modularize the i18n translation files. so, it will not load all translations at once and it will load only the required translation for current loading page.
like creating :
- `common.json` -> for common translations 
- `validation.json` -> for validation messages
- `payment.json` -> for payment page transaltion // translation files per module/page

this will reduce loading time of our landing page.
suppose our landing page will only need common.json & that page specific translation, then it will load only those translations instead of importing all translations at once.

We can do like that, let me know if you are okay with this solution 👍 

Thanks
