### ISSUE TITLE
[CAL-2071] Broken UI for App Removing Dialog -

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9846]
Dialog is too wide probably and content is not centered.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2071](https://linear.app/calcom/issue/CAL-2071/broken-ui-for-app-removing-dialog)</sub>

**Comment by hariombalhara** [comment]
![image](https://github.com/calcom/cal.com/assets/1780212/6c70f8b5-56bf-4170-ad9a-506b491782e2)

**Comment by anikdhabal** [comment]
> ![image](https://user-images.githubusercontent.com/1780212/249749696-6c70f8b5-56bf-4170-ad9a-506b491782e2.png)

And I think only "yes" is sufficient ,there's no need "yes, remove app".
