### ISSUE TITLE
Preview button into an event is pointing to the wrong URL

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9850]
### Issue Summary

Inside an event, the Preview button is pointing to the wrong URL. It works if opened from the Event Type page.
 
### Steps to Reproduce

1. Open the Event Type page (/event-types)
2. Click on the Preview button for any Event
3. Check that the calendar is opening in the correct link (e.g.: http://acme.cal.local:3000/john/quick-chat?duration=15)
4. Back to the Event Type page
5. Click on the Edit button for any Event
6. Click on the Preview button for that event
7.  Check that the 404 page is shown as the link is wrong (e.g.: http://localhost:3000/john/quick-chat)

### Actual Results

- Getting 404 page as the link is wrong

### Expected Results

- The links should be the same on the Event Type page and the Event itself

### Technical details

- Tested on Chrome (114.0.5735.134) and Firefox (114.0.2)

### Evidence
![image](https://github.com/calcom/cal.com/assets/10250819/78e6d500-ce9e-48bd-8b20-f2284b0c7657)

![image](https://github.com/calcom/cal.com/assets/10250819/46d899f5-0a31-4d59-9eff-d9b834b73143)

**Comment by keithwillcode** [comment]
@ericrommel this seems to be an environment configuration issue and not a bug, correct?

**Comment by ericrommel** [comment]
> @ericrommel this seems to be an environment configuration issue and not a bug, correct?

Not sure. @sean-brydon asked me to create this issue to check it better.
