### ISSUE TITLE
Make it possible to link a specific calendar to an event

### ISSUE THREAD

**Issue by thisisallnew** [calcom/cal.com#9855]
### Is your proposal related to a problem?

 I use Google Calendar and subscribe to multiple calendars within GCal.  I organise events and usually create calendars for those events.  In the current set-up, I can choose from one or more calendars for all events. 

(Write your answer here.)

### Describe the solution you'd like

 I would love to be able to select which calendar Cal.com should pick from.

(Describe your proposed solution here.)

### Describe alternatives you've considered

 Setting up a separate cal.com account for each event

(Write your answer here.)

### Additional context

 No

(Write your answer here.)

**Comment by PeerRich** [comment]
i believe you can do this already inside the event-type advanced settings, no?
![image](https://github.com/calcom/cal.com/assets/8019099/b640dfbb-c85b-42f6-95fb-5445af36dd31)

**Comment by georgekrax** [comment]
Although I am able to do it and choose my preferred calendar, at the end Cal.com books the call on the default calendar I have settled in the Google Calendar settings in the App page :(

**Comment by thisisallnew** [comment]
Hi. I'm offered calendar options in my primary calendar eg organise a 30
minute meeting with me, but I'm not offered that option for other events
I've created.
