### ISSUE TITLE
[CAL-2076] /settings/profile - if you try save without name the error message copy needs updated

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9857]
If you try save your profile without adding name it shows the following:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/173d0a05-ed3c-4c6e-994a-8f203e39a0d6/50c0a48a-be11-4da4-9483-63dd898b626a)

If we're making this field required, we should update the copy to say something like:

"You need to add a name"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2076](https://linear.app/calcom/issue/CAL-2076/settingsprofile-if-you-try-save-without-name-the-error-message-copy)</sub>

**Comment by ujwalkumar1995** [comment]
Hey @Jaibles 
Although not part of the original issue, I have also added a fix to not allow just spaces as a name. Please let me know if that is not needed.
