### ISSUE TITLE
[CAL-2078] title and icon not aligned in ConfirmationDialogContent

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#9866]
### Issue Summary

This is our dialog to confirm if event type should get deleted:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/29aa4fba-2c09-46c8-a4bd-61b2f751ce18/92ed7390-5a80-4933-9f52-5938d1c066d8)

As you can see title and icon are not aligned:

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2c6141be-9ff8-44ed-a093-f13ff0618556/ab3c03a9-00d7-4c40-9b3d-007701cb681e)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2078](https://linear.app/calcom/issue/CAL-2078/title-and-icon-not-aligned-in-confirmationdialogcontent)</sub>

**Comment by karthiknadar1204** [comment]
@CarinaWolli If this issue is still up for grabs, I would like to work it out, could you also elaborate which part the alignment is to be fixed
