### ISSUE TITLE
Routing form accepts blank as its name

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9871]
### Issue Summary

To have a name is something mandatory for the routing form, however, it accepts blank as a name.
 
### Steps to Reproduce

1. Install the routing form app
2. Click to add a new routing form
3. Type a single space
4. Click on the Continue button
5. Observe

### Actual Results

- It's accepting blank as a name

### Expected Results

- It should validate that there is no valid value

### Technical details

- Tested on Chrome (114.0.5735.134)

### Evidence

![image](https://github.com/calcom/cal.com/assets/10250819/f01fc6a5-2223-491e-abf5-507b80466165)

![image](https://github.com/calcom/cal.com/assets/10250819/04d99680-7371-46cf-96cd-1d3b9a4ffc6b)

![image](https://github.com/calcom/cal.com/assets/10250819/fbbf6fa9-a42a-4d23-bbd3-c41f008db17e)

**Comment by Aditay2002** [comment]
claim #9871
@PeerRich amde changes in the existing PR for this issue

**Comment by AnitKrJha** [comment]
@PeerRich no need to add the javascript validation logic to the Name field , just adding required will suffice. Anyways the `urls` for the forms are `based on the uuid` not the `name`
