### ISSUE TITLE
[CAL-2079] `URL Case sensitive bug`, while booking a meeting

### ISSUE THREAD

**Issue by hritik2002** [calcom/cal.com#9872]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There's a case sensitive bug while booking a url.
Example:
`URL1 = "https://cal.com/hritik2002/30min"`
`URL2 = "https://cal.com/Hritik2002/30min"`

Should ideally redirect to the same page.

A summary of the issue. This needs to be a clear detailed-rich summary.

Ideally, the urls "[https://cal.com/hritik2002/30min](https://cal.com/hritik2002/30min)" and "[https://cal.com/Hritik2002/30min](https://cal.com/Hritik2002/30min)" should redirect me to the same page.
The only difference between both the `urls` is the `first letter` of the `userNames`:
`hritik2002`/30min
and
`Hritik2002`/30min

As, the urls "[https://cal.com/hritik2002](https://cal.com/hritik2002)" and "[https://cal.com/Hritik2002](https://cal.com/Hritik2002)" redirect me to the same page (user profile page), this means that the userNames are not stored as case sensitive.

### Steps to Reproduce

1. Type [https://cal.com/hritik2002/30min](https://cal.com/hritik2002/30min) on your browser, this will take you to a specific page
2. Now, type, [https://cal.com/Hritik2002/30min](https://cal.com/Hritik2002/30min) in the browser, this will take you to a 404 page, the only difference is `h` and `H` as the first letter of the userNames in both the `url`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b4b3e982-70e5-4d16-ab71-84444bb8d234/457037c0-8259-4886-8502-0cd35c06f200)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2ad42916-23e0-4797-aa1f-2939c599ec76/863741ea-857a-4fe5-bbae-0135123beb6a)

Compare the `url's` in both the attached screenshots, they should ideally redirect me to the same page, but they fail to do so.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2079](https://linear.app/calcom/issue/CAL-2079/url-case-sensitive-bug-while-booking-a-meeting)</sub>

**Comment by JaideepGuntupalli** [comment]
@PeerRich @zomars This isnt replicable at localhost for some reason, the username is being sanitized before querying about the event.
```typescript
username: username.toLowerCase().replace(/( |%20)/g, "+"),
``` 
**Link to codeblock:**
https://github.com/calcom/cal.com/blob/407b0518b3e9fe08ff1fc4f466414f4a11025a0a/apps/web/pages/%5Buser%5D/%5Btype%5D.tsx#L94C4-L94C4

**Comment by afrieirham** [comment]
@JaideepGuntupalli i think it's because the production app is using this component instead `package/features/bookings/Booker/Booker.tsx`, link here https://github.com/calcom/cal.com/blob/main/packages/features/bookings/Booker/Booker.tsx

you need to add `/new-booker` in front of route for localhost for some reason.

so instead of `http://localhost:3000/admin/15-min` you need to change it to `http://localhost:3000/new-booker/admin/15-min`

i've experience the same issue fixing #9758 with #9873

**Comment by JaideepGuntupalli** [comment]
@afrieirham thanks for the help.
