### ISSUE TITLE
Incomplete error message for domain clash while creating a new organization.

### ISSUE THREAD

**Issue by iamr-kumar** [calcom/cal.com#9874]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Incomplete error message for domain clash while creating a new organization.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Go to `settings/new/organization`
2. Fill the first form with an organization email that is already registered
3. Fill name and URL
4. Submit and then enter the verification code.
5. `domain_taken_team` message is displayed instead of proper error message.

<img width="768" alt="Screenshot 2023-07-02 at 2 55 08 AM" src="https://github.com/calcom/cal.com/assets/58480195/b1e52c9a-0e7c-47fa-a702-36ba7010b69c">

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Tested on Brave 1.52.129 on production

**Comment by PeerRich** [comment]
organisations is still work in progress. i think this has been fixed but lemme ping @leog here too

**Comment by iamr-kumar** [comment]
@PeerRich cool. Let me know if anything on this is required as I have a PR almost ready for this.
