### ISSUE TITLE
Copy Availability Times Disables The Current WeekDay

### ISSUE THREAD

**Issue by piyushgarg-dev** [calcom/cal.com#9884]
### Issue Summary
In the availability section, when we copy the time from one weekday to another weekday, it disables the currently selected weekday.

### Video
https://github.com/calcom/cal.com/assets/44976328/dc40e245-bb27-4973-8b6f-1ed42b0d15d0

**Comment by piyushgarg-dev** [comment]
This seems like a re-render issue to me.
CC @PeerRich

**Comment by sravanth299** [comment]
@piyushgarg-dev I couldn't replicate the issue, is it fixed already?

**Comment by keithwillcode** [comment]
This looks to have been fixed. I can't replicate either.
