### ISSUE TITLE
One-click app for CapRover

### ISSUE THREAD

**Issue by nileshtrivedi** [calcom/cal.com#989]
[CapRover](https://caprover.com/) is a self-hosted PAAS for FOSS webapps. It is based on Docker, is very stable and has a [catalogue of many apps](https://github.com/caprover/one-click-apps) that can be installed with a single click.

I have filed an [app suggestion there for Calendso](https://github.com/caprover/one-click-apps/issues/519) to make it available in the catalogue but it seems Calendso does not yet provide a Dockerfile that can be migrated to CapRover's one-click config. There is a `docker-compose.yml` file in the repo but it only runs the postgres instance, and does not run the main app.

**Comment by lcx** [comment]
looks like somebody added it to caprover
https://github.com/caprover/one-click-apps/blob/master/public/v4/apps/calendso.yml

**Comment by zenflow** [comment]
@lcx Yup, it's not the official image though. See https://github.com/caprover/one-click-apps/pull/394#issuecomment-951546025
