### ISSUE TITLE
[CAL-2085] Slot visibility issue on mobile

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9896]
[38720fd4-c722-4340-82aa-91525d2a0bac](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/67605281-238d-40cb-9735-1b78299a9f29/38720fd4-c722-4340-82aa-91525d2a0bac)

Created via Threads. See full discussion: [https://threads.com/34485420527](https://threads.com/34485420527)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2085](https://linear.app/calcom/issue/CAL-2085/slot-visibility-issue-on-mobile)</sub>

**Comment by emrysal** [comment]
Thanks for being involved @bhargavagonugunta - it was already assigned to @sean-brydon - it's now fixed. Also apologies for the lack of transparency
