### ISSUE TITLE
Enhance the UI inside Bookings

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#9905]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.
No need to add scrollbar in the "Event type" dialog box
![Screenshot 2023-07-04 104618](https://github.com/calcom/cal.com/assets/81948346/ed19ebe3-3e4e-4d04-aa05-ccc2ad6c5d1c)

### Steps to Reproduce

1. Went to Bookings

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by anikdhabal** [comment]
I want to work on this.

**Comment by PeerRich** [comment]
go for it!
