### ISSUE TITLE
2FA: download backup code

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9910]
- add a button to download a backup.txt when creating a 2FA code
- add a button to upload it when you lost your 2FA device (show this during the 2A step)

![image](https://github.com/calcom/cal.com/assets/8019099/02db6293-8bbc-4c0d-9576-2e89ffcc3f20)
https://github.com/calcom/cal.com/assets/8019099/02db6293-8bbc-4c0d-9576-2e89ffcc3f20

**Comment by PeerRich** [comment]
if anyone has a better idea for "I lost my access" go ahead

**Comment by iSatVeerSingh** [comment]
@ViswanthSwarna are you working on it?
