### ISSUE TITLE
[CAL-2089] No availability in a conflicting setting scenario.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9915]
![GitHub-hosted image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2cc7c525-656c-4b9f-9223-64e0fb52691f/e6c93fa9-c3ff-4fd0-be7f-5f83888c363f)

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/2cc7c525-656c-4b9f-9223-64e0fb52691f/e6c93fa9-c3ff-4fd0-be7f-5f83888c363f)

[Source image](https://github.com/calcom/cal.com/assets/1780212/c8a8d376-7ade-4be8-8a28-daaa84431cad)

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/218e475b-de6a-4807-b480-53ee7f90c4fa/a8d8cb4a-0076-4676-91a6-e9004ac00b48)

[Source image](https://github.com/calcom/cal.com/assets/1780212/a3ebcc5e-69f6-449e-a275-872a0278b35c)

Should probably prevent this situation where the booker is allowed to book only 2 days in future but Minimum notice is 5 days.

or Maybe 2 days in future should be counted after minimum notice.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2089](https://linear.app/calcom/issue/CAL-2089/no-availability-in-a-conflicting-setting-scenario)</sub>

**Comment by AyushGovil** [comment]
Hey @hariombalhara , I can add a validation on this section which will display a error message on the top of this mentioning "Cannot be less than 'minimum notice days'".
![image](https://github.com/calcom/cal.com/assets/33975149/0293cd7b-eab6-468f-8fde-a96e460e71bf)

**Comment by pratik-codes** [comment]
hi @hariombalhara can you explain a little more on this would like to work on this issue.

If the user selects more than 2 days should we show a error and dsiable save button?
What is minimum notice in this case which you have mentioned?
How should the error be show in this case.

This would help me going ahead with working on this issue. Thanks!

**Comment by CarinaWolli** [comment]
I propose to show an error message that the minimum booking notice can't be greater than the day limit for future bookings (and also the other way around, depending on what input came last). If the user still clicks save, we can throw an error with an appropriate message. 

We can show the error message below the input fields

**Comment by emrysal** [comment]
@PeerRich this is low priority at best; just don't do this is a suitable alternative to fixing 😅
