### ISSUE TITLE
[CAL-2090] Weird layout on empty upcoming bookings page.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9916]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1c9d5838-7215-425a-a248-e7b4cfdea653/0f11e6a5-418d-445c-a222-5bcf822556ef)

[Source image](https://github.com/calcom/cal.com/assets/1780212/8e196995-4030-4ec4-9581-1e04e425643c)
This looks weird, I think that zero state layout should be wider ?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2090](https://linear.app/calcom/issue/CAL-2090/weird-layout-on-empty-upcoming-bookings-page)</sub>

**Comment by anikdhabal** [comment]
fixed by #9908
