### ISSUE TITLE
Not able to visit cal.com/docs in Twitter browser

### ISSUE THREAD

**Issue by LazyCalum** [calcom/cal.com#9918]
### Issue Summary
When clicking through to cal.com/docs in the Twitter Browser, a client-side exception occurs.

### Steps to Reproduce

1. Click on the cal.com url in @calcom Twitter bio
2. Click through to the cal.com/docs page
3. Client-side exemption occurs

https://github.com/calcom/cal.com/assets/131798949/5ad6c443-9e72-41e4-b9d1-f2db12195f80

### Technical details
- iOS 16.3
- Twitter app Version 9.64

**Comment by alishaz-polymath** [comment]
Unable to recreate the issue. I did however, have to click refresh once. But it shows up. I'll explore if there's a reason why we need to tap refresh in there.

https://github.com/calcom/cal.com/assets/52925846/280672c5-1c98-4659-bbd5-ba0198974743

**Comment by alishaz-polymath** [comment]
Can't seem to be able to recreate it anymore
