### ISSUE TITLE
[CAL-2091] remove SSR for App Store

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9921]
later make an app store replica in the calcom/website repo that is SEO optimised

<sub>[CAL-2091](https://linear.app/calcom/issue/CAL-2091/remove-ssr-for-app-store)</sub>

**Comment by PeerRich** [comment]
remove getServerSideProps

https://github.com/calcom/cal.com/blob/b5fd33d689ca3a7986dbc50d03d7bbdc3b477042/apps/web/pages/apps/index.tsx#L91

**Comment by adilkhan510** [comment]
I think for this PR what you need to do is take the logic of getServerSideProps function and implement it in the component function and call that function in a useEffect hook on initial render. The component needs to access the categories and appStore still.

**Comment by adilkhan510** [comment]
@ShivamBhardwaj93

**Comment by Yashh56** [comment]
is this issue is solved ?

**Comment by utkarshtenguriya** [comment]
is this issue resolved ?
