### ISSUE TITLE
[CAL-2092] Introduce prefetching to app store

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#9922]
Using \`ssr.dehydrate()\`

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2092](https://linear.app/calcom/issue/CAL-2092/introduce-prefetching-to-app-store)</sub>

**Comment by hariombalhara** [comment]
@joeauyeung Could you explain in more detail what we really want to achieve here?

**Comment by hariombalhara** [comment]
Not a priority for me at the moment.
