### ISSUE TITLE
[CAL-2097] RFC: Migrating next/router hooks to next/navigation hooks

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#9929]
Part of the App Router migration plan #9923

[Official docs about migrating to next/navigation](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-5-migrating-routing-hooks)

* [ ] Replace router.query usages with useSearchParams
* [ ] Replace router.asPath with usePathname
* [ ] Replace router.pathname with usePathname
* [ ] Remove the router.isFallback usages
* [ ] Replace router.isReady with true
* [ ] Reduce number of router.push  and router.replace arguments to 1
* [ ] Remove router.basePath usages and implement this feature in a different way
* [ ] Remove router.locale, router.locales , router.defaultLocale, and router.domainLocales and implement internationalization in a different way
* [ ] Remove router.events
* [ ] Replace useRouter from next/router to useRouter from next/navigation

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2097](https://linear.app/calcom/issue/CAL-2097/rfc-migrating-nextrouter-hooks-to-nextnavigation-hooks)</sub>

**Comment by alex-from-intuita** [comment]
[notes from meeting with Omar] ETA: end of this week (21JUL)
