### ISSUE TITLE
Support scheduled changes of timezones

### ISSUE THREAD

**Issue by kortenkamp** [calcom/cal.com#9937]
### Is your proposal related to a problem?

When traveling overseas, it is necessary to adjust the timezone of available times. However, this can only be done for the current timezone, so it is extremely difficult to offer bookable timeslots in advance.

### Describe the solution you'd like

If it were possible to enter future timezone changes this would solve the problem. This could be implemented by adding a „schedule time zone change“ field with a time and date and timezone when this is scheduled to happen. However, it needs some work in the availability calculation.

### Describe alternatives you've considered

As a workaround this can be solved by adding and removing availability time manually. But this is rather annoying.

**Comment by emrysal** [comment]
Hi @kortenkamp - we've got an existing issue for exactly what you described - it's indeed very annoying. https://github.com/calcom/cal.com/issues/6790 - Designs are done and ready for development. This'll likely be completed by 3.1 or 3.2 at the latest.

**Comment by kortenkamp** [comment]
Ah, ok, sorry, I did not search for it before.
