### ISSUE TITLE
[CAL-2100] Rescheduled Meeting Shows No Availability

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#9939]
When rescheduling a meeting, some times no availability is shown and only after refreshing a few times does availability show 

This bug is hard to reproduce, but occurs every now and then 

![Linear-hosted image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ff1da605-cfe8-4680-b428-cd778fe2fd21/fa660263-9e2d-4f37-b22b-17b9f4cb6e2b)

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ff1da605-cfe8-4680-b428-cd778fe2fd21/fa660263-9e2d-4f37-b22b-17b9f4cb6e2b)

assigning @sgriff96-brydon based on the areas of expertise, but feel free to unassign/reassign to someone else 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2100](https://linear.app/calcom/issue/CAL-2100/rescheduled-meeting-shows-no-availability)</sub>

**Comment by keithwillcode** [comment]
Closing because we've fixed tons of availability bugs. Reopen if seen again.
