### ISSUE TITLE
[CAL-2101] Not all seat members get the location URL of the meeting

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#9940]
(Attachment: )

Created via Threads. See full discussion: [https://threads.com/34486668891](https://threads.com/34486668891)

![Linear-hosted image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/01f69fc7-b6b6-4817-9390-792af883b2f9/fa113d77-45c7-4c36-b0ff-719bc2e1613a)

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/01f69fc7-b6b6-4817-9390-792af883b2f9/fa113d77-45c7-4c36-b0ff-719bc2e1613a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2101](https://linear.app/calcom/issue/CAL-2101/not-all-seat-members-get-the-location-url-of-the-meeting)</sub>

**Comment by alannnc** [comment]
We can create a test that validates locationUrl of bookings created in seat events for this issue.
