### ISSUE TITLE
Embed > Slot disappears if user cancels while booking

### ISSUE THREAD

**Issue by Krysand** [calcom/cal.com#9942]
### Issue Summary

When a user selects a slot and decides to go back and cancel the booking process (before clicking on confirm), the slot disappears in the booking overview and cannot be booked. 

### Steps to Reproduce

1. Select slot (13:15) on embedded Cal.com booking page 
<img width="981" alt="image" src="https://github.com/calcom/cal.com/assets/33368899/97299f62-9515-448e-a506-fec2734f8dc2">

2. Clicked on "Cancel"
<img width="783" alt="image" src="https://github.com/calcom/cal.com/assets/33368899/ec003029-9824-4a40-b2b2-ec1aa6ae28ab">
3.  13:15 slot is not available anymore, although booking process was cancelled
<img width="1000" alt="image" src="https://github.com/calcom/cal.com/assets/33368899/91d0a42d-e1e2-4eeb-8ad1-20a95b331c06">

The slot will appear after approx. 10 mins. 

### Technical details

- Embed Cal.Com Javascript in Vue.JS application

**Comment by ashish1233** [comment]
Can i work on this?

**Comment by Krysand** [comment]
Yes true, but I would assume that if a user clicks on cancel the slot should be released to be booked again. 
Same like it works on the normal booking page. You click on "back" and then you still have the option to go to the slot again. 

![image](https://github.com/calcom/cal.com/assets/33368899/408780ab-544c-4206-8c55-a27c504fab04)

The embedded version seams to act different with the "cancel" button instead of a "back" button

**Comment by PeerRich** [comment]
@alannnc can you check why "going back" does not release the slot?
