### ISSUE TITLE
Loading time after clicking edit

### ISSUE THREAD

**Issue by AyushGovil** [calcom/cal.com#9944]
### Issue Summary

Short lag happens when user clicks on the edit button for any event in the event types page. Possible improvement could be to add a loader to improve the user experience.

### Steps to Reproduce

* Go to the event types page.

https://github.com/calcom/cal.com/assets/33975149/80e212d5-021f-4f79-873d-58e9a5b79155

### Describe the solution you'd like

We can add a loader same as given below. It will enhance the user's experience.

![image](https://github.com/calcom/cal.com/assets/33975149/cc98a633-0300-45bf-bd2f-9e1ba91ad8ba)

**Comment by PeerRich** [comment]
relevant: https://github.com/calcom/cal.com/issues/9944
