### ISSUE TITLE
[CAL-2103] RFC: FreeBusy API endpoint

### ISSUE THREAD

**Issue by emrysal** [calcom/cal.com#9946]
### Is your proposal related to a problem?

We currently don't provide an easy way of figuring out bookable slots through the API. This proposal aims to introduce a new endpoint and some mechanisms to easily figure out availability for booking & calendar availability.

#### Example Call

Goal of the call; figure out busy times from the API and get available bookable slots from 1:n hosts.

POST [https://api.cal.com/v1/freebusy](https://api.cal.com/v1/freebusy)

```
{
  "timeZone": "Europe/London",
  "startTime": "2023-07-06T10:00:00",
  "endTime": "2023-07-06T12:00:00",
  "hosts": [
    "8f1b4c60-ef1f-4f76-9a22-2a2b5f6a4a68@cal.com",
    "56e7a0a4-b1a1-4e36-a9c4-7f27bdb87c8e@cal.com"
  ],
  "eventTypeId": 1,
  "slotInterval": 30
}
```

Note the eventTypeId is optional. Without eventTypeId you do not get the "availability" but you do get "freebusy".

#### Example Response

```
{
  "availability": [
    {
      "start": "2023-07-06T10:00:00+5:30",
      "end": "2023-07-06T10:30:00+5:30",
    },
    {
      "start": "2023-07-06T11:00:00+5:30",
      "end": "2023-07-06T11:30:00+5:30",
    },
    {
      "start": "2023-07-06T11:30:00+5:30",
      "end": "2023-07-06T12:00:00+5:30",
    }
  ],
  "freebusy": {
    "8f1b4c60-ef1f-4f76-9a22-2a2b5f6a4a68@cal.com": [
      {
        "calendar": "rick@gmail.com",
        "busy": [
          {
            "start": "2023-07-06T10:30:00+5:30",
            "end": "2023-07-06T11:00:00+5:30"
          }
        ],
      },
      {
        "calendar": "8f1b4c60-ef1f-4f76-9a22-2a2b5f6a4a68@cal.com",
        "busy": [
          {
            "start": "2023-07-06T10:30:00+5:30",
            "end": "2023-07-06T11:00:00+5:30"
          }
        ]
      }
    ]
  },
  "errors": {
    "56e7a0a4-b1a1-4e36-a9c4-7f27bdb87c8e@cal.com": {
      "code": 404,
      "message": "Unable to access host. Ensure the correct permissions are set."
    }
  }
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2103](https://linear.app/calcom/issue/CAL-2103/rfc-freebusy-api-endpoint)</sub>

**Comment by zomars** [comment]
Hey @emrysal can you elaborate more on this part of the POST call?

```
{
  "hosts": [
    "8f1b4c60-ef1f-4f76-9a22-2a2b5f6a4a68@cal.com",
    "56e7a0a4-b1a1-4e36-a9c4-7f27bdb87c8e@cal.com"
  ]
}
```

Are we referring to the actual user emails or am I missing something here?

**Comment by emrysal** [comment]
@zomars This is a way to have a reference for internal calendars; between all calendars there is a "consensus" to use emails and also in the future we might want Cal.com emails unique to each user. @alishaz-polymath and I discussed how to generate it and are thinking of a uuidv5 based on numeric userid as seed and a v5 namespace. 

It needs to be something that never changes (usernames, emails do) but the id doesn't. But user-1@cal.com isn't really a great option. uuidv5 does meet our requirements of being "unguessable" and unique / persistent throughout the customer's existence.

**Comment by zomars** [comment]
Thanks for clearing that out. Also, how does this differ from our [current slots](https://www.postman.com/calcom/workspace/cal-com-workspace/example/20666831-00633731-9f53-4ab4-8a63-ea222897be68) endpoint?

**Comment by emrysal** [comment]
We were actually discussing quite a bit whether we needed the "availability" bit at all as part of the /freebusy - the main requirement is to return busy times. But as the busy times are a big part of /slots, having to call /freebusy and /slots separately to get the full picture is double the work - whereas returning availability here is no overhead. 

But this is also why I'd like some community input on this; Freebusy is a frequent ask but I'm not clear 100% what the usecases and workflows are that would implement this endpoint.

@alishaz-polymath

**Comment by alishaz-polymath** [comment]
Based on my interaction with many members of the community around the slots endpoint, they are mostly looking for an endpoint that can work for them as an alternative to slotpicker in the UI. So, ideally, they would send a query to find out the free slots between two datetimes for an event type, and get the array of free slots to choose from. Once they choose it, they can simply use that in the POST booking request to book the user.

**Comment by krystofai** [comment]
Hi!
I'm trying to automate calendar availability checks using Make.com (Integromat) by calling Cal.com API via the HTTP module. I want to retrieve busy times for a specific calendar to verify if a selected time slot is free.

I'm using this endpoint:

bash
GET https://api.cal.com/v2/calendars/busy-times
Query parameters:

loggedInUsersTz: Europe/Prague

credentialId: taken from setup

externalId: user’s email

dateFrom and dateTo: in ISO format (YYYY-MM-DD)

Authorization header:

nginx

Bearer cal_live_...
❌ The Problem:
The API always returns a 401 Unauthorized error with the message "Invalid Access Token", even though I use a valid token generated via the official Make + Cal.com integration.

I also tried the alternative endpoint:

bash
POST https://api.cal.com/v1/freebusy
with the correct JSON body, but got a 405 Method Not Allowed error.

✅ What I need to achieve:
Automatically check if a specific time (e.g., 2025-07-23 10:00) is available.

If it’s not, suggest a different time.

All of this should happen inside Make via the HTTP module – no manual work.

So my main question:
Is there something wrong with the access token permissions, or am I formatting credentialId and externalId incorrectly?

Thanks a lot for your help! 🙏
Krystof



<img width="920" height="1606" alt="Image" src="https://github.com/user-attachments/assets/feaabde3-839d-4907-877e-0ef63d642a86" />

<img width="1050" height="1586" alt="Image" src="https://github.com/user-attachments/assets/e0cde84b-3eeb-477f-9f1d-6eae8b1bd9a3" />
