### ISSUE TITLE
Toast onClose not removing specific toast

### ISSUE THREAD

**Issue by anikdhabal** [calcom/cal.com#9947]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Toast component's onClick event not removing specific toast. When clicked any specific toast to remove, all of them are overlapped and removed together.

https://github.com/calcom/cal.com/assets/81948346/ced7d5a3-b515-463b-a329-760fadfdd7b6

### Steps to Reproduce

1. Generate more than one toast
2. Click any toast

**Comment by anikdhabal** [comment]
And also, if we use "remove()" method instead of "dismiss()" method, then the method will be quick.
Can I work on this issue?

**Comment by PeerRich** [comment]
@anikdhabal go for it!
