### ISSUE TITLE
[CAL-2104] booking page: location icon is not showing up

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9951]
we used to show the icon of the app next to the name.

now we only show the generic location icon next to "Discord"

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3410ed0e-3991-4a6e-a616-ce15d15846b5/434d5f5a-f478-4868-94a1-156baea1c01a)

[Source image](https://github.com/calcom/cal.com/assets/8019099/9a228119-6ea1-443f-b472-145eae84d050)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2104](https://linear.app/calcom/issue/CAL-2104/booking-page-location-icon-is-not-showing-up)</sub>

**Comment by kushagra-goyal-14** [comment]
so the icon needs to be removed ?,
Can you please provide more information about the issue that what needs to be shown in place of the location icon

**Comment by VinoV1999** [comment]
@PeerRich if the length of the location is greater then 1, shall keep the icon as mapPin..?

**Comment by PeerRich** [comment]
only invert if the image ends with _dark I believe
