### ISSUE TITLE
[CAL-2106] Modal footers are supposed to be fixed to the bottom

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9954]
Currently

[7b44a221-c5d7-4c7e-910e-e55b0197c5c2](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7f1e50bc-7a42-4f19-8908-6402d3846b64/7b44a221-c5d7-4c7e-910e-e55b0197c5c2)

Should be

![Linear-hosted image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fd406f99-c44e-4dc4-bf5f-a64442767711/0a23c53c-7de7-40ab-b680-889942b32a79)

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/fd406f99-c44e-4dc4-bf5f-a64442767711/0a23c53c-7de7-40ab-b680-889942b32a79)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=30043%3A116775&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2106](https://linear.app/calcom/issue/CAL-2106/modal-footers-are-supposed-to-be-fixed-to-the-bottom)</sub>

**Comment by xmayukx** [comment]
The Picture you have attached seems to be broken. Could you please re-upload it?

**Comment by Jaibles** [comment]
https://share.cleanshot.com/wLF8XGk3
https://share.cleanshot.com/66ywlJHb

**Comment by Raghul18** [comment]
@Jaibles : I would also like to work on this issue.

**Comment by Opssy** [comment]
HI @Jaibles  The current and it should be is not clear enough 
is the scrollbar the main issue or you want the design to be worked on again
