### ISSUE TITLE
[CAL-2107] bug: Hide invite member button on /teams if you are only a team member

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9955]
```
          Note related to the PR but we should hide Invite Team Member option for a non admin/owner user.
```

![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/32d89629-9a4e-416b-96b2-ac297cb0fa31/08761b0c-130e-4f56-bf59-ba22ab72abe8)

[Source image](https://github.com/calcom/cal.com/assets/1780212/dda94499-fbe5-449d-aa16-cc64f1dc7208)

This is allowed only in UI, backend rejects the request if initiated.

\*Originally posted by @hariombalhara in \*[*https://github.com/calcom/cal.com/issues/9945#issuecomment-1623254856*](https://github.com/calcom/cal.com/issues/9945#issuecomment-1623254856)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2107](https://linear.app/calcom/issue/CAL-2107/bug-hide-invite-member-button-on-teams-if-you-are-only-a-team-member)</sub>

**Comment by iamr-kumar** [comment]
I will take this up
