### ISSUE TITLE
[CAL-2108] Teams Page doesn't seem to have a zero state.

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9956]
![](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/68faf1c9-ca62-4c2e-8621-4585a299e9b8/3bd3827a-6e4d-4907-89fa-138129964274)

[Source image](https://github.com/calcom/cal.com/assets/1780212/b83d24a9-8288-4fe8-a11e-791e3458c11e)

I was invited into a team but I left the team and this is what I see.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2108](https://linear.app/calcom/issue/CAL-2108/teams-page-doesnt-seem-to-have-a-zero-state)</sub>

**Comment by naveen8801** [comment]
Hey @PeerRich, I'd like to contribute, can I pick this?

**Comment by keithwillcode** [comment]
@naveen8801 sure thing. If you submit a PR, we will review
