### ISSUE TITLE
[CAL-2110] Fix storybook build

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#9958]
![Linear-hosted image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5f0c835e-a662-47c1-9c30-81641b8cb72a/d9d86a38-cf31-413f-b603-bf0b14d7e1c7)

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5f0c835e-a662-47c1-9c30-81641b8cb72a/d9d86a38-cf31-413f-b603-bf0b14d7e1c7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2110](https://linear.app/calcom/issue/CAL-2110/fix-storybook-build)</sub>

**Comment by habeeb-an** [comment]
Hi
I'm new to this repo
how gain access to view images

**Comment by Aayush-23** [comment]
#9996
