### ISSUE TITLE
[CAL-2111] Managed event does not fire Webhooks if it has multiple team members

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#9962]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A managed event doesn't fire webhook if the it contains multiple team members. If it has a single team member, the webhooks fire.

### Steps to Reproduce

1. Create a managed event
2. Add a webhook to this event with BOOKING.CREATED trigger enabled
3. Make booking and confirm that the webhook works
4. Now add more team members to the event
5. Make another booking, and how it shouldn't trigger the webhook

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Production

<sub>[CAL-2111](https://linear.app/calcom/issue/CAL-2111/managed-event-does-not-fire-webhooks-if-it-has-multiple-team-members)</sub>

**Comment by rene-mueller** [comment]
@alishaz-polymath are you on the issue? @PeerRich can you create a bounty?
