### ISSUE TITLE
Session not getting refreshed

### ISSUE THREAD

**Issue by The-Robin-Hood** [calcom/cal.com#9965]
### Issue Summary

Changing the username will not alter the data stored in session, which means that the data retrieved from session and utilized will remain unaffected. An example of this is the public URL page in the sidebar, which will not be updated.

### Steps to Reproduce

1. Change the username
2. Check Whether the public url in sidebar is changed 

When you login with google provider an username will be autogenerated, when you change this username that will not be reflected in ui immediately due to the session problem.

Suggestion: Next-auth v4.22.1 has a function to update the sesison

**Comment by detronetdip** [comment]
I would like to work on this issue. @PeerRich  can you please assign me this issue?

**Comment by The-Robin-Hood** [comment]
@detronetdip Am currently working on this, mate. @PeerRich Shall we update next-auth to latest version or write a manual way for updating session ?

**Comment by PeerRich** [comment]
i think changing the email has some weird behaviour right now too.

**Comment by PeerRich** [comment]
> Shall we update next-auth to latest version

@The-Robin-Hood yes please
