### ISSUE TITLE
[CAL-2118] Page Crashes after creating a team

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9979]
https://www.loom.com/share/6749d3f14fd14182b0fcec05f448136d

<sub>[CAL-2118](https://linear.app/calcom/issue/CAL-2118/page-crashes-after-creating-a-team)</sub>

**Comment by sean-brydon** [comment]
Can't replicate 🤔 https://www.loom.com/share/8002bb2c907443d4ad2477c07bed6c52
