### ISSUE TITLE
[CAL-2119] Upload a CSV CTA isn't actionable fully

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9980]
[https://www.loom.com/share/8e7962ed0bf340eb8cc992886d4024d2](https://www.loom.com/share/8e7962ed0bf340eb8cc992886d4024d2)

CSV upload opens only when clicking in center when infact the button is so wide. This is because the label for the upload input isn't as wide as bugtton

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2119](https://linear.app/calcom/issue/CAL-2119/upload-a-csv-cta-isnt-actionable-fully)</sub>

**Comment by sivasathyaseeelan** [comment]
![Screenshot (101)](https://github.com/calcom/cal.com/assets/95441117/2894051f-6049-498a-93cb-69e970b421de)

I can't access the http://localhost:3000/settings/organizations/members. Can you please tell me how can I proceed on this issue?
