### ISSUE TITLE
[CAL-2120] Org owner/admin can't see the teams created by other owner/admin

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9982]
He should be able to see all teams so that he can add himself to any team he wants.
He shouldn't be able to see a team's event-types unless he has added him to the team.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2120](https://linear.app/calcom/issue/CAL-2120/org-owneradmin-cant-see-the-teams-created-by-other-owneradmin)</sub>

**Comment by alannnc** [comment]
I think this is more on the server side. Would you mind if I take it from you @sean-brydon?
