### ISSUE TITLE
[CAL-2121] /signup isn't properly validating password. 

### ISSUE THREAD

**Issue by hariombalhara** [calcom/cal.com#9984]
It allows even a single char password but backend then crashes with 500 status code. Backend should throw a 400 for this and show a proper message in UI.

frontend should also validate the password same as on [cal.com/signup](http://cal.com/signup)

[Source image](https://github.com/calcom/cal.com/assets/1780212/01542599-ceec-4e8e-85c8-2bd1040262d6)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2121](https://linear.app/calcom/issue/CAL-2121/signup-isnt-properly-validating-password)</sub>

**Comment by keithwillcode** [comment]
@sean-brydon can you please verify this is fixed as part of the signup refactor.

**Comment by TaduJR** [comment]
I can't reproduce it. Is it fixed?

**Comment by sean-brydon** [comment]
> @sean-brydon can you please verify this is fixed as part of the signup refactor.

https://github.com/calcom/cal.com/assets/55134778/ca8ed46a-7be3-4211-9b21-054f863b841a


Missed this - yes fixed in signup PR
